### ISSUE TITLE
🐛 Nested fragments don't work with `@client` directive

### ISSUE THREAD

**Issue by AndreyCashia** [apollographql/apollo-client#10003]
**Intended outcome:**

I want to get my mock data when I use a resolvers with `@client` directive and nested fragments.

**Actual outcome:**

I get an error when I use this fragment

```
fragment locationFields on Location {
    formattedAddress
    coordinates {
        ...geoCoordinatesFields
    }
}
```

```
query GetWalletScreenInfo {
    me {
        id
        wallets {
            ...walletFields
        }
    }
    duePaymentRequests @client {
        id
        issuer {
            email
            id
            name
            tag
            phone
            addresses {
                id
                location {
                    ...locationFields
                }
              ...
```

`auth.tsx->errorLink->graphQLErrors {"locations": [{"column": 1, "line": 36}], "message": "Fragment \"geoCoordinatesFields\" is never used."}`

but it works fine when I use not nested fragments like 

```
fragment geoCoordinatesFields on GeoCoordinates {
    lat
    long
}
```

```
query GetWalletScreenInfo {
    me {
        id
        wallets {
            ...walletFields
        }
    }
    duePaymentRequests @client {
        id
        issuer {
            email
            id
            name
            tag
            phone
            addresses {
                id
                location {
                    formattedAddress
                    coordinates {
                        ...geoCoordinatesFields
                    }
                }
               ...
```

not issues

**How to reproduce the issue:**

You can use fragments of any nesting level for reproduce this issue

**Versions**

 ```
System:
    OS: macOS 12.4
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Safari: 15.5
  npmPackages:
    @apollo/client: ^3.4.10 => 3.4.10 
    apollo-absinthe-upload-link: ^1.7.0 => 1.7.0 

```

**Comment by dylanwulf** [comment]
Hi, just a reminder to please wrap `@client` in backticks (\`\`) to avoid accidentally tagging the github user `client`. Thanks!

**Comment by AndreyCashia** [comment]
Maybe someone knows how to solve this issue?

**Comment by dylanwulf** [comment]
Not sure if this will help with your issue, but if your GraphQL schema has unions or interfaces make sure you have `possibleTypes` configured correctly: https://www.apollographql.com/docs/react/data/fragments/#defining-possibletypes-manually

**Comment by alessbell** [comment]
Hi @AndreyCashia 👋 Do you have a runnable reproduction you can share? Thanks!
