### ISSUE TITLE
Align @defer v1 implementation with latest proposed spec updates

### ISSUE THREAD

**Issue by alessbell** [apollographql/apollo-client#10019]
While `@defer` support work is in flight (https://github.com/apollographql/apollo-client/pull/10018), it has been implemented against a now-outdated version of the proposed spec.

This is a placeholder issue for aligning with the latest implementation (`graphql-js` PR here https://github.com/graphql/graphql-js/pull/3659, spec edits PR here https://github.com/graphql/graphql-spec/pull/742)

**Comment by jpvajda** [comment]
See https://github.com/robrichard/defer-stream-wg/discussions/41

**Comment by jpvajda** [comment]
See https://github.com/robrichard/defer-stream-wg/discussions/50

**Comment by alessbell** [comment]
Closing this as done as the latest changes have been incorporated as of https://github.com/apollographql/apollo-client/pull/10018/commits/c44b38c80c2a36e8cf851e3080b73c6f92633a8a

**Comment by jpvajda** [comment]
@alessbell thank you! It's likely we'll have another change to consider in the future as the spec evolves and is ratified, but we can create that ticket when the time comes.
