### ISSUE TITLE
How does work  the fetchPolicy field for useLazyQuery ?

### ISSUE THREAD

**Issue by RustamKarimov3** [apollographql/apollo-client#10048]
My code is

const [getSome] = useLazyGetSome({
  fetchPolicy: 'cache-only',
})

<Button onClick={.getSome } />

When I invoke getSome by clicking button  this runs request to the server despite the fetchPolicy: 'cache-only' and I am little confused about how fetchPolicy works with lazy query. I did not found any related information about that in docs. Could you help me to get more intelligent with using fetchPolicy and lazyQuery?

**Comment by MrDoomBringer** [comment]
Hi there!
We try to keep Github Issues reserved for bugs. Please direct usage questions to https://community.apollographql.com/. 

On testing locally, I don't see network requests being made with `fetchPolicy: "cache-only` - it's possible the issue may lie somewhere else in your implementation, so I'll be closing this for now. If do you believe this to be a bug, feel free to let me know with more information and I'll be happy to reopen this.

All the best,
Emmanuel, Intern :-)

**Comment by MrDoomBringer** [comment]
P.S.: The repo I used for testing the behavior is here https://github.com/MrDoomBringer/fullstack-tutorial/tree/useLazyQuery-fetchPolicy (based on our full-stack tutorial app,) with changes made only to [`client/src/pages/launch.tsx`](https://github.com/MrDoomBringer/fullstack-tutorial/blob/useLazyQuery-fetchPolicy/final/client/src/pages/launch.tsx)
