### ISSUE TITLE
@defer documentation

### ISSUE THREAD

**Issue by jpvajda** [apollographql/apollo-client#10057]
See #10012  & #10018 

- [x] Team initially documents the feature
- [x] PM review by @jpvajda 
- [x] Docs Review by @StephenBarlow  or @rkoron007

**Comment by jpvajda** [comment]
@alessbell 👋 We could probably "borrow"  t[his  content](https://github.com/apollographql/apollo-kotlin/blob/88a602faa7041985eb57c758e3ec5b268310ff58/docs/source/fetching/defer.mdx) That @martinbonnin  wrote for our Apollo  web client docs, if we want to release some beta documentation in this next release. 😎

**Comment by jpvajda** [comment]
@bignimbus is going to take this one 🥳

**Comment by bignimbus** [comment]
Back to you @jpvajda :)
