### ISSUE TITLE
How to stop polling when there is no in flight request

### ISSUE THREAD

**Issue by skysantoroa** [apollographql/apollo-client#10058]
My client is polling my graphql backend and will stop polling whenever a condition is met.

```
React.useEffect(() => {
    if (condition) {
      transaction.stopPolling()
    }
  }, [..., transaction, ...])
```

The problem is that I need to invoke `stopPolling` only when there are no network request that have been launched or that are waiting to receive the result. I tried the util method `isNetworkRequestInFlight` without success.

Any insight?

**Comment by jpvajda** [comment]
Thank you for reporting this! I suggest posting this in our [Apollo Community](https://community.apollographql.com/) for guidance from other Apollo users, as other's may have input into your question. I'll also leave it open here as well.

**Comment by jerelmiller** [comment]
Hey @skysantoroa 👋 ! Thanks for your patience! 

This should be possible with the [`client.getObservableQueries()`](https://github.com/apollographql/apollo-client/blob/895ddcb546b5692cd53caae1b604412728641374/src/core/ApolloClient.ts#L574) method on `ApolloClient`. By default, this will return all "active" queries, where an "active" query is one that has observers and a `fetchPolicy` other than `standby` or `cache-only`. This returns a [`Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map), so you can check its [`size`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/size) property to see if there are any active queries.

Apologies this isn't in the documentation! I'll add an issue to ensure we get this in there.

Hope this helps!
