### ISSUE TITLE
Infinite loops with babel-plugin-graphql-tag and hooks

### ISSUE THREAD

**Issue by UjinT34** [apollographql/apollo-client#10064]
Enabling babel-plugin-graphql-tag makes this code to go into an infinite loop:

```
function MyComponent() {
    const {data} = useQuery(gql`query Q {
        someObject {
            someField
        }
    }`);
    const [count, setCount] = useState(0);
    
    useEffect(() => {setCount(c => c +1)}, [data]);

    return null;
}
```

Same thing happens with `fetchPolicy: 'cache-and-network'`:

```
function MyComponent() {
    const {data} = useQuery(gql`query Q {
        someObject {
            someField
        }
    }`, {
        fetchPolicy: 'cache-and-network'
    });

    return null;
}
```

Possible reason: babel-plugin-graphql-tag transpiles `gql` into something like `var a = {....}` resulting in a new object being passed to `useQuery` on every render.

Expected behavior: treat queries produced by babel-plugin-graphql-tag as unchanged between renders and return same data objects.

**Comment by UjinT34** [comment]
Might be related to #7436

**Comment by jerelmiller** [comment]
Hey @UjinT34 👋 ! Thanks for your patience on this issue. 

Is it possible for you to extract that query into a global variable? This might help workaround the fact that a new object is created every render.

```tsx
const QUERY = gql`
  query Q {
    someObject {
      someField
    }
  }
`;

function MyComponent() {
  const { data } = useQuery(QUERY, { fetchPolicy: 'cache-and-network' });

  return null;
}
```
