### ISSUE TITLE
Improve the `@defer` client side demo in supegraph fed 2 demo

### ISSUE THREAD

**Issue by jpvajda** [apollographql/apollo-client#10067]
In the supergraph fed 2 demo we added code to allow someone to run a deferred query in a simple web app See [PR 212](https://github.com/apollographql/supergraph-demo-fed2/pull/212) for instructions.  This demo was based on my prototype app I built in this [repo](https://github.com/jpvajda/ac-defer-example) 

Though when you run the demo you can't see the deferred query side by side with the non-deferred query. Ideally we could allow someone to see the 2 types of queries side by side, similar to what is show in the PR https://github.com/apollographql/apollo-client/pull/10018

`It be nice to see this`

![CleanShot 2022-08-22 at 08 51 38](https://user-images.githubusercontent.com/5139846/185925857-2a020340-dba9-4ca6-976c-4739f14c1993.gif)

`but we now see this`

![Screen Shot 2022-09-02 at 5 12 57 PM](https://user-images.githubusercontent.com/1395158/188245320-5704e687-93f7-41b1-a68e-23ed3100b76a.png)

**Comment by jpvajda** [comment]
@prasek mentioned he had to [comment out](https://github.com/apollographql/supergraph-demo-fed2/pull/212/files#diff-b8a3bed0c492362178fc6e1056741af48ce94b0287fde80929963e584c41389bR129) the non-deferred example code. 

> I had commented that out because both were doing the same query (one deferred, one non-deferred) and when either of them resolved correctly it would update the AC entity cache and both deferred and non-deferred widgets would update (essentially overwriting the error condition for the deferred query)

So I'm curious if there is anything we can do to allow us to do a side by side defer example in supergraph demo? @alessbell

**Comment by prasek** [comment]
@jpvajda for the purposes of the side-by-side demo (not something we'd recommend for general use), I updated the client demo to use a `fetchPolicy: "no-cache"` on [PR 212](https://github.com/apollographql/supergraph-demo-fed2/pull/212/commits/209bd55c3c5523051415ec3b9db76b5e92a3fd50) and it seems to work as we'd want it to. 👍

**Comment by jpvajda** [comment]
@prasek  Thanks! I pulled the changes down locallly and I'm still seeing this view, but maybe it's a docker cache issue?

<img width="1311" alt="Screen Shot 2022-09-02 at 6 02 18 PM" src="https://user-images.githubusercontent.com/1395158/188248068-0e1ea691-9982-415b-8645-6385e2194065.png">

**Comment by prasek** [comment]
@jpvajda router just dropped [1.0.0-alpha.1](https://github.com/apollographql/router/releases/tag/v1.0.0-alpha.1) earlier today and changed `experimental_defer_support` to `preview_defer_support` and it's now on by default, so updated [PR 212](https://github.com/apollographql/supergraph-demo-fed2/pull/212/commits/426edd7baf54da9394bba98981f78e8cd1690ade) just now to use that

This means to just run the supergraph stuff you can `make docker-up-local-router` and it will use the pre-built router 1.0.0-alpha.1 docker image and then you can just manually startup the defer-ac demo app.

Alternatively you can rebuild everything with `make docker-build-router-main-with-subgraphs-no-cache` and then startup the demo on PR 212 like before.

**Comment by jpvajda** [comment]
This is done now. so closing this one out.
