### ISSUE TITLE
Merge in Dependency PRS ☂️ 

### ISSUE THREAD

**Issue by jpvajda** [apollographql/apollo-client#10063]
Given we have a decent amount of [dependency PRs ](https://github.com/apollographql/apollo-client/pulls?q=is%3Apr+is%3Aopen+label%3A%22%3Achristmas_tree%3A+dependencies%22)stacking up, I thought I'd add an issue so we can focus on either merging those, or not merging those.

### Merged/closed

- https://github.com/apollographql/apollo-client/pull/10042
- https://github.com/apollographql/apollo-client/pull/9936
- https://github.com/apollographql/apollo-client/pull/10010
- https://github.com/apollographql/apollo-client/pull/10043
- https://github.com/apollographql/apollo-client/pull/10070
- https://github.com/apollographql/apollo-client/pull/9956
- https://github.com/apollographql/apollo-client/pull/8175
- https://github.com/apollographql/apollo-client/pull/9955
- https://github.com/apollographql/apollo-client/pull/10091

### Discuss with team
- https://github.com/apollographql/apollo-client/pull/10041
  - when would we like to land TS 4.8 upgrade - still planning for AC v3.8? (edit: now targeting 3.7)
  - ~do we want to start running tsc on tests (e.g. during `build`)?~ edit: we do via ts-jest and the test step which fails on TS errors in tests
- https://github.com/apollographql/apollo-client/pull/8969
  - current node LTS is [16.17.0](https://nodejs.org/dist/v16.17.0/node-v16.17.0.pkg)
  - should keep types aligned with node version https://github.com/apollographql/apollo-client/pull/9840
- https://github.com/apollographql/apollo-client/pull/10090
  - lots of errors and 3 major version ahead of current version (11), how would we like to prioritize this?

**Comment by alessbell** [comment]
The TS upgrade is still in progress but the rest of the planned upgrades have been merged. Closing as completed.
