### ISSUE TITLE
Mutating a state within onComplete callback

### ISSUE THREAD

**Issue by FahmyChaabane** [apollographql/apollo-client#10083]
Hi, I am not really sure wethere if i am missing something.. 

I am using useLazyQuery, and i am mutating a state within onComplete callback, it does not mutate the state.

To be more precise, it does not mutate the state, when the query result is already in the cache. (the state is mutated when the data request is not yet saved in the cache).

onComplete does indeed bring the right data within the callback, but useStateAction does not mutate the state.

When i added to the params "fetchPolicy: “network-only”… the state now is mutating correctly.

I also could solve the issue with async/await approach. there is some issue with onComplete callback.

**Comment by jpvajda** [comment]
Hello! It be helpful to see a reproduction of this issue. You can create a reproduction using https://github.com/apollographql/react-apollo-error-template and link to it here. If you prefer an in-browser way to create reproduction, try: https://codesandbox.io/s/github/apollographql/react-apollo-error-template
