### ISSUE TITLE
TypeError: (0 , ts_invariant__WEBPACK_IMPORTED_MODULE_0__.invariant) is not a function

### ISSUE THREAD

**Issue by idonov** [apollographql/apollo-client#10085]
Webpack 5 build crashes on run because of error "invariant is not a function"

**Actual outcome:**
![image](https://user-images.githubusercontent.com/7294596/189333194-9710e7fb-f4ae-4daa-9fb0-5d2d2db3c966.png)
I can actually see the package in the map:
![image](https://user-images.githubusercontent.com/7294596/189333825-21cc557f-0a91-4af2-acb1-6b950ad418a9.png)

Tried using Yarn resolutions to no avail.

Also previously had similar issues(is not a function) with other imports from apollo, had to import them directly:
![image](https://user-images.githubusercontent.com/7294596/189334412-1e1e847a-b417-4dfc-b64a-b6291283ff2a.png)

**Versions**
System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.135
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.27)
  npmPackages:
    @apollo/client: ^3.6.9 => 3.6.9

**Comment by jpvajda** [comment]
👋  Could you try deleting your `node_modules` folder, deleting your `package-lock.json` file and then running npm install again?
