### ISSUE TITLE
"Demystifying Cache Normalization" blog article seems to be wrong

### ISSUE THREAD

**Issue by srmagura** [apollographql/apollo-client#10080]
[This article](https://www.apollographql.com/blog/apollo-client/caching/demystifying-cache-normalization/) from apollographql.com says:

> For example, if we were to:
>
> 1. Perform a GetAllTodos query, normalizing and caching all todos from a backend
> 2. Call GetTodoById on a todo that we had already retrieved with GetAllTodos
>
> … then Apollo Client could just reach into the cache and get the object directly without making another request.

I tested this and `GetTodoById` did NOT retrieve the todos from the Apollo Cache.

**Intended outcome:**

The official blog post accurately documents the behavior of Apollo Client.

**Actual outcome:**

The official blog post does NOT accurately document the behavior of Apollo Client.

I created a project to show this: https://github.com/srmagura/how-does-apollo-work. It is a trivial GraphQL API server and a React client which calls the server. The client first calls `getAllTodos` which returns 5 todos. When you click the button, the client calls `getTodoById` for each todo. **Each GraphQL request for `getTodoById` results in a network call.** This contradicts what the blog post says should happen.

For what it's worth, I think Apollo Client is behaving correctly and the blog post is just wrong.

**How to reproduce the issue:** Clone and run the repository I linked to in the previous section.

**Versions**
```text
  System:
    OS: macOS 12.5.1
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.16.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Firefox: 104.0.1
    Safari: 15.6.1
```

**Additional reference**
StackOverflow answer that backs up what I said: https://stackoverflow.com/a/50839798/752601

**Comment by bignimbus** [comment]
Hi @srmagura 👋🏻  I pulled down your repo (thanks for that!) and inspected the source code.  I think you're correct.  I'll follow up in this thread with next steps.  Thanks again!

**Comment by bignimbus** [comment]
Hi @srmagura, I'm planning to push an update to that blog post next week.  I'll update this thread once I've drafted it.  Thanks again!

**Comment by markusgabriel** [comment]
Hi @bignimbus do I understand this correctly, that apollo does not query from the cache first if the data is present there? I am a bit confused over this thread, because I would think apollo acts exactly how it is described in the blog post. Or am I missing something?

**Comment by srmagura** [comment]
@markusgabriel Apollo cannot know the true behavior of your GraphQL server (i.e. resolvers). So Apollo cannot assume `getTodoById(id: "123")` returns the todo with ID="123". Therefore, Apollo must make the network call — it cannot simply look up the `Todo` in the cache.

If it helps, imagine you had a query like `getAllTodosExcept(id: "123")`. You would be upset if Apollo used the cache and returned the `Todo` with ID="123" in this case!

**Comment by dylanwulf** [comment]
This is mentioned in the stackoverflow link in the issue description, but for anyone who finds this thread looking for a solution: this functionality does exist in apollo client, it just needs a little bit of manual setup. You can find instructions here: [Cache Redirects](https://www.apollographql.com/docs/react/caching/advanced-topics/#cache-redirects)

**Comment by markusgabriel** [comment]
@srmagura ok, thanks for making that clear. Now it makes sense to me. I was already trying to set up the cache redirects, but I am still having problems.

**Comment by bignimbus** [comment]
Hi @srmagura, I've pushed a small update to the linked blog post with an additional example and a link to the Cache Redirects documentation.  Thanks a bunch for calling our attention to this!
