### ISSUE TITLE
@apollo/client sub-packages have no license

### ISSUE THREAD

**Issue by dodosiz** [apollographql/apollo-client#10095]
**Intended outcome:**
I am using the [LicenseWebpackPlugin](https://github.com/xz64/license-webpack-plugin/blob/master/DOCUMENTATION.md) to scan node modules for licenses and add them into a license.txt file. When the plugin scans the @apollo/client package it does not find any license in the sub modules and it crashes.

**Actual outcome:**
The submodules:
```
@apollo/client/cache

@apollo/client/core

@apollo/client/errors

@apollo/client/link/core

@apollo/client/link/http

@apollo/client/link/utils

@apollo/client/react

@apollo/client/react/context

@apollo/client/react/hooks

@apollo/client/react/parser

@apollo/client/utilities

@apollo/client/utilities/globals
```
should be shipped with an open source license like MIT.

The issue is even worse when you are using [spx-license-data](https://www.npmjs.com/package/spdx-license-list) to generate a license file. Because the license is not there it crashes the whole build:
```
[webpack-cli] HookWebpackError: ENOENT: no such file or directory, open '/home/local/user/project/node_modules/spdx-license-data/data/licenses/null.txt'
```

**How to reproduce the issue:**
If you are using [webpack](https://webpack.js.org/) to build your project configure the license plugin:
```
plugins: [
		new LicenseWebpackPlugin({
			handleMissingLicenseText: packageName => {
				console.log("Cannot find license for " + packageName);
				return "UNKNOWN";
			},
		})
	],
```
After building it, you should see warning messages like this:
```
WARNING in license-webpack-plugin: could not find any license type for @apollo/client/core in its package.json

WARNING in license-webpack-plugin: could not find any license type for @apollo/client/react in its package.json

WARNING in license-webpack-plugin: could not find any license type for @apollo/client/utilities/globals in its package.json

WARNING in license-webpack-plugin: could not find any license type for @apollo/client/utilities in its package.json

WARNING in license-webpack-plugin: could not find any license type for @apollo/client/link/utils in its package.json

WARNING in license-webpack-plugin: could not find any license type for @apollo/client/cache in its package.json

WARNING in license-webpack-plugin: could not find any license type for @apollo/client/errors in its package.json

WARNING in license-webpack-plugin: could not find any license type for @apollo/client/link/core in its package.json

WARNING in license-webpack-plugin: could not find any license type for @apollo/client/link/http in its package.json

WARNING in license-webpack-plugin: could not find any license type for @apollo/client/react/context in its package.json

WARNING in license-webpack-plugin: could not find any license type for @apollo/client/react/hooks in its package.json

WARNING in license-webpack-plugin: could not find any license type for @apollo/client/react/parser in its package.json

```

**Versions**
```
npx: installed 1 in 0.837s

  System:
    OS: Linux 5.14 Ubuntu 20.04.5 LTS (Focal Fossa)
  Binaries:
    Node: 14.20.0 - /usr/bin/node
    npm: 6.14.17 - /usr/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 104.0
  npmPackages:
    @apollo/client: ^3.6.9 => 3.6.9 
    @apollo/react-hooks: ^4.0.0 => 4.0.0
```

**Comment by jpvajda** [comment]
@dodosiz Thanks for reporting this, we'll take a look at this and determine what actions to take.

**Comment by jpvajda** [comment]
@dodosiz I spoke to the team about this and here is some of the feedback for consideration.

These are not independent packages, so they aregoverned by the top-level license of the @apollo/client package. It seems like you might be scanning for package.json files without licenses in them, and found our nested package.json files in the process.

**Comment by dodosiz** [comment]
So the solution here is just to exclude them?
`new LicenseWebpackPlugin({excludedPackageTest: (packageName: string) => packageName.startsWith("@apollo/client")})`

**Comment by jpvajda** [comment]
@dodosiz Yes, I'd just exclude the nested packages in your scan, as all packages in Apollo Client SDK are governed by the top-level license of the `@apollo/client` package.
