### ISSUE TITLE
Hidden timeout on apollo client requests?

### ISSUE THREAD

**Issue by Pixelatex** [apollographql/apollo-client#10101]
I noticed my requests were failing with a timeout error. Yet the same requests work in my playground. So the culprit seems to be the apollo client.

Searching the docs doesn't provide me with any information on timeout options.

Is there a timeout option that I can configure for my apollo client? Or per request?

**Comment by bignimbus** [comment]
Hi @Pixelatex 👋🏻 thanks for reaching out! Is there more information you can provide about what you're seeing? Maybe a console message or test failure? Thanks and have a good day!
