### ISSUE TITLE
Who is the maintainer of the graphql-anywhere package on npm?

### ISSUE THREAD

**Issue by wereHamster** [apollographql/apollo-client#10114]
The package is not allowing graphql 16 as peer dependency (even though it works with it just fine). I'd like to push a update that modifies the package.json to mark it as compatibkle with graphql 16.

**Comment by alessbell** [comment]
Hi @wereHamster 👋 As of the release of `@apollo/client@3.0.0` ~2 years ago, `graphql-anywhere` was removed from this repository in https://github.com/apollographql/apollo-client/pull/5159 and is no longer maintained. This is mentioned in the [Migration Guide for AC3](https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/#graphql-anywhere), but we will look at updating the package README with a deprecation notice.

If you're using npm v7+ you can run `npm i --legacy-peer-deps` to install with a peer dependency of `graphql@16`. I'll close this issue for now but let me know if there's anything else we can help with. Thanks!

**Comment by wereHamster** [comment]
I know the workaround, and I know it is a workaround, hence why I asked who the maintainer is so I can ask them to patch the package.json file, or if they are busy give me brief access to the package on npm so I can upload the patched version myself.

I also know the package is deprecated, but it's still being used, for example by apollo-link-rest. They know about this issue but due to lack of resources can't address it in a timely manner.

**Comment by wereHamster** [comment]
I know, though that would fix it only for myself, if graphql-anywhere would be my direct dependency. The apollo-link-rest team could fork it and it would fix it for them (and their users). But this wouldn't fix it for all the other people who have a direct or indirect dependency on that package.

What argument is there to not publish a new version which bumps the peer deps range?

What if I offer myself as the maintainer of that package?

**Comment by alessbell** [comment]
@wereHamster thanks to @benjamn, `graphql-anywhere@4.2.8` was just published with an [updated peer deps range for `graphql`](https://github.com/apollographql/apollo-client/blob/release-2.x/packages/graphql-anywhere/package.json#L48-L50). (It also includes a [deprecation notice](url).)

That should take care of the issue when running `npm i` with npm v7+, you can install it at the `latest` tag right now :)
