### ISSUE TITLE
Explore @swc/jest as an alternative to ts-jest

### ISSUE THREAD

**Issue by alessbell** [apollographql/apollo-client#10121]
Memory leak issues with jest + ts-jest have been reported since ~2020. There are several open issues on both projects:

- https://github.com/kulshekhar/ts-jest/issues/1967
- https://github.com/facebook/jest/issues/7874
- https://github.com/facebook/jest/issues/11956

There are also a number of confounding factors: memory consumption seems to have increased considerably when running this repository's tests in Node.js v16.11+, for example, but the commonly suggested workarounds (using ts-jest's `isolatedModules` option, jest's `--runInBand` or any combination of other "fixes") don't solve the issue for Apollo Client's tests.

Running the tests with Node.js v18.9.0 results in a hanging test (https://github.com/apollographql/apollo-client/pull/10120).

## @swc/jest

I've created the branch [`swc-jest`](https://github.com/apollographql/apollo-client/compare/swc-jest) to explore the use of `@swc/jest` + `@swc/core` as a replacement for `ts-jest`.

**Comment by amans1690** [comment]
@alessbell I am curious to know why you chose `@swc/jest` instead of `babel-jest` as an alternative? Is this just because of performance benefit in case of `@swc/jest`.

**Comment by alessbell** [comment]
@amans1690 yes exactly—`@swc/jest`'s perf is really impressive! Unfortunately there are a few things blocking our migration path so we'll be sticking with `jest` + `ts-jest` for now. Closing as won't do.
