### ISSUE TITLE
Use Lazy Query not rendering the correct data

### ISSUE THREAD

**Issue by LuisChiej** [apollographql/apollo-client#10130]
**Intended outcome:**
When using useLazyQuery, the correct data is not being rendered but the network tab shows that it retrieves the correct data
<img width="578" alt="Screenshot 2022-09-26 at 20 56 28" src="https://user-images.githubusercontent.com/54555805/192368192-0341121e-4db5-4257-b3db-7df37c2dd859.png">

**Actual outcome:**

Instead it renders the first array across the multiple arrays, duplicating the data
<img width="778" alt="Screenshot 2022-09-26 at 20 57 46" src="https://user-images.githubusercontent.com/54555805/192368563-adde829a-ad72-45e9-beaf-851a4ddbf69e.png">

**How to reproduce the issue:**

**Versions**

**Comment by LuisChiej** [comment]
@hwillson, Please help

**Comment by bignimbus** [comment]
Hi @LuisChiej 👋🏻  thanks for submitting this issue!  To narrow things down a bit, could you share what version of Apollo Client you're using?  Also it would expedite things if the team could take a look at a code sample that shows how to reproduce this issue.  Hope to hear from you!

**Comment by LuisChiej** [comment]
@bignimbus, I am presently using v3.6.9, and the 
<img width="710" alt="Screenshot 2022-09-27 at 10 23 37" src="https://user-images.githubusercontent.com/54555805/192488176-ff6cc65f-ce3c-4157-ae4c-58d554ee00af.png">
this is a code sample, but the main takeaway is I am trying to return and render an array of objects in this scenario

**Comment by dylanwulf** [comment]
I think your problem is that the `id` field is null. If `id` is nullable then I would recommend changing your [keyFields](https://www.apollographql.com/docs/react/caching/cache-configuration/#customizing-cache-ids) to something else.

**Comment by LuisChiej** [comment]
Solved, @dylanwulf, Thank you very much
