### ISSUE TITLE
What do I do if I don't want trigger useLazyQuery when changing a query?

### ISSUE THREAD

**Issue by hyjoong** [apollographql/apollo-client#10136]
![스크린샷 2022-09-28 오후 2 13 30](https://user-images.githubusercontent.com/105196220/192693188-1b22b5ed-18d7-488f-b80c-417d92bdf2c1.png)

In the photo above, the elements selected in the check box are updated to queryList, and useLazyquery is trigger
Click the Lookup button to update the query with the selected elements in the check box

I implemented to get as many queries as I clicked on the check box. Even if you modify the check box and check it, it will be executed.

If I check only one thing in the check box, 
```javascript
queryList = 'orderID';
```
If I check three in the check box,

```javascript
queryList = 'orderID useName productName';
```

```javascript
  const getOrderItemQuery = gql`
    query getOrderItems($getOrderItemsInput: GetOrderItemsInput!) {
      getOrderItems(getOrderItemsInput: $getOrderItemsInput) {
        ${queryList}
      }
    }
  `;

  const [orderItemQuery, setOrderItemQuery] = useState(getOrderItemQuery);


  const [getOrderItemData, { loading: orderItemLoading}] = useLazyQuery(
    orderItemQuery,
    {
      onCompleted: data => {
       ...
      },
      
    },
  );


const handleLookup = () => {
    // now pathname = /payment?startOffset=100&size=50
     
     setOrderItemQuery(getOrderItemQuery)
     // Update with checked queries 
     // 1. useLazyQuery trigger -> canceled  
    //  data fetch (startOffset=100, size=50)
    //  i don't want useLazyQuery trigger (change orderItemQuery)

    router.push(`/payment?startOffset=0&size=50`);
   // 2. useEffect useLazy trigger (i want once trigger) 
   // startOffset=0, size=50
 };


useEffect(()=>{
   getOrderItemData({
         variables: option?.variables,
         context: { clientName: 'payment' },
         fetchPolicy: 'no-cache',
     })
},[query])


return (
   <button onClick={handleLookup}> Search </button>
)
```

![image](https://user-images.githubusercontent.com/105196220/192694700-f822f105-93d6-4b4d-b8ad-09f0706064b9.png)

    "@apollo/client": "^3.5.10",

**Comment by dylanwulf** [comment]
You could possibly look into using `client.query()` or `client.watchQuery()` instead of `useLazyQuery`. That would give you much better control over what happens and when it happens.

**Comment by dylanwulf** [comment]
@hyjoong you can find the [docs for client.query and client.watchQuery here](https://www.apollographql.com/docs/react/api/core/ApolloClient)

The client object can be accessed through the [useApolloClient hook](https://www.apollographql.com/docs/react/api/react/hooks/#useapolloclient)

**Comment by hyjoong** [comment]
@dylanwulf Thank you for your answer. I solved the problem. used client.query 👌🏼

```javascript
import { initializeApollo } from '@lib/apollo';

  const apolloClient = initializeApollo();

  const getLookupData = async () => {
    setIsLoading(true);
    const { data } = await apolloClient.query({
      query: requestQuery,
      variables: option.variables,
      context: { clientName: 'payment' },
      ...

<button onClick={getLookupData}> get Data </button>
```
