### ISSUE TITLE
onCompleted and onError are not called when using testing-library/react-hooks

### ISSUE THREAD

**Issue by nikhilchinni** [apollographql/apollo-client#10141]
Hi Team,

Good Day.

I am following the official apolloclient repo where there are multiple test cases to cover the onCompleted and onError callbacks . But Unfortunately I am not able to replicate .

I am attaching the repo link also where i find the usage of renderhook.

[useQuery](https://github.com/apollographql/apollo-client/blob/main/src/react/hooks/__tests__/useQuery.test.tsx) 

With this I am attaching the codeblock in the repo in which i followed the same exact pattern to test my application graphqlquery. you can have a look in to below test case.

```ts
it("should call onCompleted when variables change", async () => {
  const query = gql`
    query people($first: Int) {
      allPeople(first: $first) {
        people {
          name
        }
      }
    }
  `;
  const data1 = { allPeople: { people: [{ name: "Luke Skywalker" }] } };
  const data2 = { allPeople: { people: [{ name: "Han Solo" }] } };
  const mocks = [
    {
      request: { query, variables: { first: 1 } },
      result: { data: data1 },
    },
    {
      request: { query, variables: { first: 2 } },
      result: { data: data2 },
    },
  ];
  const onCompleted = jest.fn();
  const wrapper: React.FC<
    React.PropsWithChildren<{ variables: { first: number } }>
  > = ({ children }) => ({ children });
  const { result, rerender, waitForNextUpdate } = renderHook(
    ({ variables }) => useQuery(query, { variables, onCompleted }),
    {
      wrapper,
      initialProps: {
        variables: { first: 1 },
      },
    }
  );
  expect(result.current.loading).toBe(true);
  await waitForNextUpdate();
  expect(result.current.loading).toBe(false);
  expect(result.current.data).toEqual(data1);
  expect(onCompleted).toHaveBeenLastCalledWith(data1);
  rerender({ variables: { first: 2 } });
  expect(result.current.loading).toBe(true);
  await waitForNextUpdate();
  expect(result.current.loading).toBe(false);
  expect(result.current.data).toEqual(data2);
  expect(onCompleted).toHaveBeenLastCalledWith(data2);
  rerender({ variables: { first: 1 } });
  expect(result.current.loading).toBe(false);
  expect(result.current.data).toEqual(data1);
  expect(onCompleted).toHaveBeenLastCalledWith(data1);
  expect(onCompleted).toHaveBeenCalledTimes(3);
});
```

Here you can see `await waitForNextUpdate();` after  first truthy expect . 

But in my application when i am running test cases  its showing timedout error and its not moving further and rest of the test executions are not executing.

Can you help on this error

The above test case what i kept here was from the official apollo client repo link which i kept and trying to say the same pattern i followed while writing test cases for my application to cover the onCompleted and onError callbacks

Thanks ,
Nikhil.

**Comment by jerelmiller** [comment]
Hey @nikhilchinni! Thanks for writing in. I edited your issue to add some formatting to the code block to make it a bit easier to read if thats alright.

From first glance, it looks like your `wrapper` is missing a [`<MockedProvider />`](https://github.com/apollographql/apollo-client/blob/main/src/react/hooks/__tests__/useQuery.test.tsx#L37) which helps resolve the query in a test. 

I'd highly recommend checking out the [docs on `MockedProvider`](https://www.apollographql.com/docs/react/development-testing/testing#the-mockedprovider-component) as I think they'll give you a great overview on how to properly mock queries for tests. Alternatively, feel free to ask this question in our [community forum](https://community.apollographql.com/) where you can find a lot of help! 

Let us know if this helps!

**Comment by nikhilchinni** [comment]
Hi @jerelmiller Thanks so much for editing and formatting the issue.

I want to highlight the mockprovider some how its going off when i am typing and keeping so keeping the reference for the same.

![image](https://user-images.githubusercontent.com/40667039/192867944-49ad4b17-38ae-4bdd-ab63-bbb217acdece.png)

Here mockProvider already in place.

**Comment by jerelmiller** [comment]
@nikhilchinni gotcha! I didn't see the `MockedProvider` in the initial post so I must have missed that 😆. 

Would you do me a favor and try the [simple query test](https://github.com/apollographql/apollo-client/blob/721b400e744dc3cac2ab532a2c12f1c5587b64b0/src/react/hooks/__tests__/useQuery.test.tsx#L27-L50) to see if you are able to get this to pass? This test uses no variables and only checks a single render. I want to see if you're able to get a simple case working before we diagnose the more complex one in the initial post.

**Comment by nikhilchinni** [comment]
@jerelmiller I have tried with that simple query test which u asked me but its  showing the same timedout error

**Comment by jerelmiller** [comment]
@nikhilchinni bummer! It must be some combination of the versions of libraries or something.

Would you be willing to setup a repo or CodeSandbox with reproduction? Make sure the same versions of each library are installed and the jest config is relatively the same as what you're working with. This would really help me dig in a bit further so I can best understand why its hanging.

Again, feel free to post in our [community forum](https://community.apollographql.com/) as well. Others may or may not have encountered this issue and might be able to provide some guidance.

**Comment by jerelmiller** [comment]
Hey @nikhilchinni 👋 !

Since this issue is getting pretty stale and we are unable to reproduce the issue, I'm going to close this for now. Feel free to open it back up if you need additional help. A reproduction would be super helpful if you choose to do so. Thanks!
