### ISSUE TITLE
Apolo in SSR mode - error " __DEV__ is not defined"

### ISSUE THREAD

**Issue by websitevirtuoso** [apollographql/apollo-client#10171]
**Intended outcome:**
I am trying to implement ssg for vue 3 project with apollo 

**Actual outcome:**

Getting error
![image](https://user-images.githubusercontent.com/5112918/194796808-13520784-4b78-4fc3-8338-e76b21a68d71.png)

**How to reproduce the issue:**

I pushed the project to review.
https://github.com/websitevirtuoso/vite-ssg-apollo
Please run
```
yarn install
yarn ssg:build
```

I had to implement patch to had ability to use apollo in SSR mode and it worked for some repos but this currect project much bigger.
Please check 2 last commits in my repo to have more idea
https://github.com/antfu/vite-ssg/issues/241
but I am getting another error not connected with ssg.
This is apollo specific error connected with SSR

**Versions**
```
System:
    OS: Linux 5.15 KDE neon 5.25
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 675.72 MB / 15.49 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
  Browsers:
    Chrome: 106.0.5249.91
    Firefox: 105.0
```

Thanks for great lib.Hope to get your support

**Comment by alessbell** [comment]
Hi, @websitevirtuoso 👋  We have an alpha release with a change that should improve things here, you can install it with `npm i @apollo/client@alpha` or the package manager of your choice :) If you have a chance to test it out, would love to know if that helps!

**Comment by websitevirtuoso** [comment]
@alessbell Thanks. I will try to test it. And Will inform you about any changes. Thanks For everything

**Comment by bignimbus** [comment]
Hi @websitevirtuoso 👋🏻  just wanted to follow up here - we are closing this issue as completed.  Please do feel free to open a new issue if you continue to see this happening after trying `npm i @apollo/client@alpha` 🙏🏻
