### ISSUE TITLE
Subscriptions seem to stop working after a app goes into idle state

### ISSUE THREAD

**Issue by mattdwardle** [apollographql/apollo-client#10172]
**Intended outcome:**
Subscription data and WebSocket stays connected with data being live.

**Actual outcome:**
After minimizing the app and putting it into background mode for roughly 5 minutes the subscriptions seem to stop working. I have tried polling and that seems to fix the issue but this doesn't resolve the actual issue with the subscriptions. 

**How to reproduce the issue:**
I have tried the useSubscription hook first and recently tried useQuery with subscribeToMore. Both seem to have the same issue. I have also tried increasing timeout and inactivityTimeout to be larger than the 5 minutes. It doesn't seem to be the WebSocket disconnecting or anything as we have logs of the WebSocket connection status and it seems to stay connected.

He is an example of how I have the Websocket Client setup.

```const wsClient = (
  !isServer
    ? new SubscriptionClient(
        `wss://localhost/graphql`,
        {
          reconnect: true,
          lazy: true,
          timeout: 300000,
          inactivityTimeout: 300000,
          connectionCallback: (error) => {
            if (error) {
              console.error('WS CONNECTION_CB ERROR::: ', error)
            }
            ack = true
            return ack
          }
        }
      )
    : null
) as SubscriptionClient
```

**Versions**
I am using `subscriptions-transport-ws` instead or `graphql-ws` because our provider doesn't work with `graphql-ws` as of yet. 

Not sure if someone else has had this issue.

**Comment by jpvajda** [comment]
👋 @mattdwardle  thanks for asking this question, our docs [have some suggestions ](https://www.apollographql.com/docs/react/data/subscriptions#the-older-subscriptions-transport-ws-library)when working with `subscription-transport-ws` as it's not actively maintained anymore so it can be a bit tricky to use. 

to get more details on this  t be helpful to see a reproduction of this issue. You can create a reproduction using https://github.com/apollographql/react-apollo-error-template and link to it here. If you prefer an in-browser way to create reproduction, try: https://codesandbox.io/s/github/apollographql/react-apollo-error-template
