### ISSUE TITLE
Apollo Client seems to interfere with vite define global

### ISSUE THREAD

**Issue by nnzo** [apollographql/apollo-client#10197]
I'm using Apollo client version 3.7.0. (with vite 3.1.10)

In my `vite.config.js`, I have declared 'global' like the following:

```
define: {
    // By default, Vite doesn't include shims for NodeJS/
    // necessary for segment analytics lib to work
    'global': {},
}
```

This seems to be interfering with the Apollo client, (but only in production?)
```
vite v3.1.3 building for production...
✓ 27 modules transformed.
[commonjs--resolver] Unexpected token (10:20) in /Users/me/myproject/node_modules/@apollo/client/utilities/globals/index.js
file: /Users/me/myproject/node_modules/@apollo/client/utilities/globals/index.js:10:20
 8: removeTemporaryGlobals();
 9: export { maybe } from "./maybe.js";
10: export { default as global } from "./global.js";
                        ^
11: export { invariant, InvariantError };
12: checkDEV();
error during build:
SyntaxError: Unexpected token (10:20) in /Users/me/myproject/node_modules/@apollo/client/utilities/globals/index.js
```

**Comment by bignimbus** [comment]
Hi @nnzo, thanks for reaching out!  I'm not sure how the team might be able to dig into this with the information given.  Is there a reproduction you can share (e.g. a repository or codesandbox)?  Additionally, this sounds like a question that would be perfect to ask in our [community forum](https://community.apollographql.com/):

**Comment by bignimbus** [comment]
Closing this for now, happy to re-open if there's something actionable for the team.  Thanks!

**Comment by keeganstothert** [comment]
@nnzo did you resolve this? i'm having the same exact issue, in production only as well

**Comment by nnzo** [comment]
> @nnzo did you resolve this? i'm having the same exact issue, in production only as well

Unfortunately I didn't. I ended up switching to urql instead. Sorry I can't help :(

**Comment by ms-sz** [comment]
> 

In case you still need a fix: 
```
define: {
    // By default, Vite doesn't include shims for NodeJS/
    // necessary for segment analytics lib to work
    'window.global': {},
}
```

Renaming from `global` to `window.global` should do the trick.
