### ISSUE TITLE
Add an `ignoreResults` option to the `useSubscription` API

### ISSUE THREAD

**Issue by jpvajda** [apollographql/apollo-client#10216]
### Overview 

Some issues have been brought to our attention that the `useSubscription` [API](https://www.apollographql.com/docs/react/data/subscriptions#options) doesn't have an option of [ignoreResults](https://www.apollographql.com/docs/react/data/mutations#ignoreresults), similar to the `useMutation` [API](https://www.apollographql.com/docs/react/data/mutations#options).  

### Issue 
Unfortunately, unlike `useMutation`, there is no "magic parameter" like `ignoreResults`, and a component will be rendered each time you get new data on subscription. `useSubscription` returns a value, and because it does, that means we need to update it, which requires components to re-render. Whereas `useMutation` allows someone to avoid the re-renders by passing an` ignoreResults` option.   

### Purpose
We could offer an `ignoreResults` option in `useSubscription` which would not return a value from `useSubscription` thereby avoiding re-renders This would be useful to allow a developer to  to not re-render a component on certain occasions if they wish.

### Details

- **Name**: ignoreResults
- **Type** boolean
- **Functionality:**  If true, the subscription's data property is not updated with the subscription's result.
- **Default:** false
	
### References

- https://stackoverflow.com/questions/61876931/how-to-prevent-re-rendering-with-usesubscription
- https://dagster.io/blog/web-workers-performance-issue
- https://medium.com/@seniv/improve-performance-of-your-react-apollo-application-440692e37026

**Comment by kjhuang-db** [comment]
+10000

**Comment by phryneas** [comment]
This has been implemented in https://github.com/apollographql/apollo-client/pull/11921 and will be released in Apollo Client 3.11.
