### ISSUE TITLE
custom headers omited in the preflight OPTIONS request

### ISSUE THREAD

**Issue by casertap** [apollographql/apollo-client#10217]
**Intended outcome:**
If I set a custom header using this code:
```
const httpLink = new HttpLink({
  uri: "https://api.newrelic.com/graphql",
});

const authMiddleware = new ApolloLink((operation, forward) => {
  operation.setContext(({ headers = {} }) => ({
    headers: {
      ...headers,
      "api-key": "123",
    },
  }));

  return forward(operation);
});

const client = new ApolloClient({
  link: concat(authMiddleware, httpLink),
  cache: new InMemoryCache(),
});
```
I expect the header: `"api-key": "123"` do be part of the preflight OPTIONS request

**Actual outcome:**
The actual request that apollo-client is fetching is this:
```
fetch("https://api.newrelic.com/graphql", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-GB,en-US;q=0.9,en;q=0.8",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "cross-site"
  },
  "referrer": "http://localhost:3000/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "OPTIONS",
  "mode": "cors",
  "credentials": "omit"
});
```
request from the browser (using react-apollo-error-template) The request is missing the header `api-key: 123`

<img width="1065" alt="Screen Shot 2022-10-22 at 8 14 42 pm" src="https://user-images.githubusercontent.com/284394/197331493-e77df0b7-97d9-4930-9507-4014aace4692.png">

**How to reproduce the issue:**
I used the `react-apollo-error-template` and I created a simple commit: https://github.com/casertap/react-apollo-error-template/commit/7158714ce977f07e5cf8d76fa46851569f0f3c59

The repo is here: https://github.com/casertap/react-apollo-error-template

**Versions**
npx: installed 1 in 1.305s

  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 12.20.0 - ~/.nvm/versions/node/v12.20.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.20.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 106.0
    Safari: 15.6.1
  npmPackages:
    @apollo/client: ^3.7.0 => 3.7.0

**Comment by casertap** [comment]
trying a few different settings.
This is telling fetch to include the CORS credentials. 
```
const httpLink = new HttpLink({
  uri: "https://api.newrelic.com/graphql",
  credentials: "include",
});

const authLink = setContext((_, { headers }) => {
  return {
    headers: {
      ...headers,
     // trying to test different headers
      "api-key": "123",
      "test-key": "678",
      authorization: `Bearer 456`,
      "Access-Control-Allow-Credentialsi": true,
    },
  };
});

const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: authLink.concat(httpLink),
});
```
But the OPTIONS request still doesn't include auth headers 
<img width="1037" alt="Screen Shot 2022-10-24 at 9 01 19 am" src="https://user-images.githubusercontent.com/284394/197420242-e3a08c33-42f5-4ea1-9285-4327706385a9.png">

**Comment by bignimbus** [comment]
Hi @casertap, thanks for submitting this issue!  I pulled your repo down and looked at the Network tab.  I was able to see `api-key` being sent in the POST request headers.  The screenshot you shared is of an OPTIONS request.  I hope that helps!  I'll close this issue but please do feel free to add a post to our [community](https://community.apollographql.com/) to keep the conversation going!

<img width="1624" alt="Screen Shot 2022-10-24 at 9 57 12 AM" src="https://user-images.githubusercontent.com/3976692/197543988-f277a4f1-15a8-46e8-9d16-e3c4b1a6a4d8.png">

**Comment by bignimbus** [comment]
@casertap apologies for opening and re-closing, I initially left a comment that was not fully addressing your issue.  Looking at this closer!

**Comment by bignimbus** [comment]
@casertap I'm not able to reproduce the issue when using `no-cors` mode - does that address what you're trying to accomplish?

```diff
diff --git a/src/index.jsx b/src/index.jsx
index 3452abf..84763ed 100644
--- a/src/index.jsx
+++ b/src/index.jsx
@@ -85,6 +85,9 @@ function App() {
 const httpLink = new HttpLink({
   uri: "https://api.newrelic.com/graphql",
   credentials: "include",
+  fetchOptions: {
+    mode: 'no-cors',
+  }
 });
 
 const authLink = setContext((_, { headers }) => {
```

**Comment by jerelmiller** [comment]
@bignimbus looks like `no-cors` will omit anything but [simple headers](https://developer.mozilla.org/en-US/docs/Web/API/Request/mode#no-cors).

> Prevents the method from being anything other than HEAD, GET or POST, and the headers from being anything other than [simple headers](https://fetch.spec.whatwg.org/#simple-header). 

I've tried the above and with `no-cors` and see that the `api-key` is omitted in the request. FWIW, I'm not able to successfully call New Relic's API using plain `fetch` either, so I'm not so sure this is an issue with Apollo Client.

I actually think this is an issue with New Relic's API itself. The [docs](https://docs.newrelic.com/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph/) use `curl` or GraphiQL for the examples, so unfortunately they don't help much either.

I used to work at New Relic and have emailed someone that I know that works on the team in charge of the API. I'll post back here when I hear back to see if that API allows CORS requests. More than likely, you'll need to open an issue with New Relic to see if they will allow CORS requests to allow browser apps to use the API. I'm surprised I didn't see more of this in my time there!

---

@casertap FYI, the `Access-Control-Allow-Credentials` is response header from the server that tells the browser whether to expose the response to JavaScript (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials) so unfortunately setting that header in the request won't have any effect.

**Comment by jerelmiller** [comment]
@casertap I just got a reply back from my contact at New Relic:

> Yeah, NerdGraph doesn't allow CORS requests outside NR domains :/ It's a security thing if I recall correclty. I think 3rd party nerdlets are the only way to write UI code that hits NerdGraph.

So if you want to use New Relic's NerdGraph API in any way, you'll either need to [write your own app](https://developer.newrelic.com/build-apps/) inside of New Relic's platform, or you'll need to proxy the New Relic API using a server, which won't suffer from CORS issues.

**Comment by jerelmiller** [comment]
@casertap since this issue looks like its on New Relic's end, I'm going to go ahead and close this. Feel free to open it back up if you need additional help!
