### ISSUE TITLE
[3.4.16] Does the type-level merge:true policy deeply merge the object?

### ISSUE THREAD

**Issue by Fishfaceeast** [apollographql/apollo-client#10227]
My question is :

Does the type-level `merge:true` policy deeply merge the object? Why the type policy added to `ProcessorType` could merge `priceInfo` but the type policy added to `CoreType` could not work? 

The example extended from https://github.com/apollographql/apollo-client/issues/5762. 
Schema is like this:
```
const PriceInfoType = new GraphQLObjectType({
  name: 'PriceInfoType',
  fields: {
    rawPrice: {
      type: GraphQLString,
    }
  }
})
const ProcessorType = new GraphQLObjectType({
  name: 'ProcessorType',
  fields: {
    priceInfo: {
      type: PriceInfoType,
    },
    model: {
      type: GraphQLString,
    },
    clockSpeed: {
      type: GraphQLInt,
    }
  }
})

const CoreType = new GraphQLObjectType({
  name: 'CoreType',
  fields: {
    cpu: {
      type: ProcessorType,
    }
  }
}) 


const ComputerType = new GraphQLObjectType({
  name: 'ComputerType',
  fields: {
    id: {
      type: GraphQLID,
    },
    name: {
      type: GraphQLString,
    },
    core: {
      type: CoreType,
    }
  }
})
```
Given that we cache some data with a query (`MODEL_AND_PRICE_QUERY`) like this:
```
  query ModelAndPrice {
    computer {
      id
      core {
        cpu {
          priceInfo { 
            rawPrice
          }
          model
        }  
      }
    }
  }
```  
and later in the program run a query (`CLOCK_SPEED_QUERY`) like this (with cache-first fetch policy):
```
  query ClockSpeed {
    computer {
      id
      core {
        cpu {
          clockSpeed
        }  
      }
    }
  }
``` 
When cache policy is like this:
 ```
typePolicies: {
    ProcessorType: {
      merge: true
    },
}, 
 ```   
The cpu data (`ProcessorType`) could be deep merged, including its non-normalized field priceInfo(`PriceInfoType`)
  
When cache policy is added to the parent type `CoreType`, like this:
```
typePolicies: {
    CoreType: {
      merge: true
    },
  },
 ```
The cpu data (`ProcessorType`) could not be deep merged , with priceInfo(`PriceInfoType`) overwritten by query ClockSpeed.   

How to reproduce the issue:
Here is a reproduction of the issue: https://github.com/Fishfaceeast/apollo-client-issue-2/tree/3.4.16

Checkout branch 3.4.16 and start the app.

Click `Model&Price` button - The program fetches data. Then Model and price data is dislayed
Click `Clock speed` button - The program fetches data. Model and price data is overwritten by clock speed data. 
Click `Model&Price` again -  Model and price data is gone from the cache. The program fetches data again.

@apollo/client Version: 3.4.16

**Comment by Fishfaceeast** [comment]
Hi. Anyone checking this issue?

**Comment by Fishfaceeast** [comment]
I've cloned this question to community forum.

**Comment by bignimbus** [comment]
Hi @Fishfaceeast, I'll close this issue since we're discussing this at https://community.apollographql.com/t/3-4-16-does-the-type-level-merge-true-policy-deeply-merge-the-object/4905/2 .  For those following this thread, see the issue @Fishfaceeast linked above for additional context.  Thank you!
