### ISSUE TITLE
Reconnection strategy for Subscriptions

### ISSUE THREAD

**Issue by patroza** [apollographql/apollo-client#1025]
Currently I fetch the status of an ongoing (long running background) operation, and subscribe to further notifications of changes.
If I loose the websocket connection and it comes back up, how would I bring my UI back up to speed?
And how do I prevent out-of-order problems caused by events arriving sooner than my initial query?
I think it would be great if the framework could assist in this, or at the least documentation that provides guidance.

Thoughts so far:
1. Monitor the WebSocket connection client-side, once reconnected, fetch the current status again, just like when we started, and wait for notification of changes again
  Downside: What if a new notification comes in sooner than my Query request is finished, my Query request might overwrite my current state with older information. Versioning the status/messages would be one way to address this but I think it's relatively error prone.
2. Upon subscription on the server call a loader to get the "initial value", and publish it as the event. This would then automatically take care of reconnecting as well, but also suffers from the order problem - what if a new event comes in sooner than the querying finished

some additional thoughts:
- To make approach 1. work, a "reconnected" event should be fired from the WebSockets Client, once a) the connection is up again, and b) the subscriptions have finished re-registering.

**Comment by helfer** [comment]
@sickboy right now you have to handle most of that yourself. You have to add quite a bit of logic on top of graphql to stay in sync with the server - essentially the same as implementing a distributed log.

If you don't need 100% perfect synchronization I would just recommend refetching when your websocket reconnects, and maybe adding a timestamp so you don't apply outdated. If you need something better than that, you'll have to impelment a legit synchronization protocol.

**Comment by thebigredgeek** [comment]
I agree with @helfer .  You can keep a "last heartbeat" value in redux or whatever... and then upon reconnection you can refetch what you need based on that stamp.  Not perfect, but you could probably use a HOF to combine the subscription with a query so that query automatically runs with the "last heartbeat" value whenever the WS reconnects

**Comment by sickboy** [comment]
@helfer and @thebigredgeek thanks! do you agree that a connection status change event should be built into the apollo websockets client? Right now im drilling into the object hierarchy from the outside, to get to the websocket and related events.

**Comment by thebigredgeek** [comment]
There should definitely be an exposed API.

**Comment by helfer** [comment]
@sickboy yes, I think that would be useful addition. You could make a PR to the subscriptions-transport-ws package. Once we have it there, we could consider exposing it via `networkStatus` as well, thus making consumption of it even easier.

**Comment by Urigo** [comment]
Have you got the chance to check out this PR? https://github.com/apollostack/subscriptions-transport-ws/pull/53

**Comment by helfer** [comment]
I'm going to close this issue here because it concerns subscriptions-transport-ws and not so much apollo client (other than maybe exposing a "disconnected" status)

**Comment by helfer** [comment]
Actually, I'm going to reopen it because it would be cool if someone did the work to implement this in the client and the websocket package 🙂

**Comment by Urigo** [comment]
@helfer do you mean implementing a strategy?
because about the connection status, that exists in the new version of `graphql-subscriptions` and `subscriptions-transport-ws`

**Comment by helfer** [comment]
Ok, I think we can close this again. If someone wants to make a PR to expose subscription status in Apollo Client, that would still be appreciated. 😄

**Comment by gilesbradshaw** [comment]
To prevent out of order problems (eg subscription results arriving before and being overwritten by out of data query results) imo you are best off running everything over a websocket.

Then this pull request

https://github.com/apollographql/apollo-link/pull/235

* makes a callback for subscription status change
* automatically re executes queries when the ws connection reconnects

**Comment by devthejo** [comment]
If it can helps someone here is the hook I use:
```js
const wsLink = new WebSocketLink({
  url: GRAPHQL_WS_URI,
  connectionParams: () => {
    const { userToken } = getAuthState();
    const headers = {
      "Sec-WebSocket-Protocol": "graphql-transport-ws",
    };
    setBearerHeader(headers, userToken);
    return { headers };
  },
  keepAlive: 30000,
  retryAttempts: Infinity,
  retryWait: async function waitForServerHealthyBeforeRetry() {
    await new Promise((resolve) =>
      setTimeout(resolve, 1000 + Math.random() * 3000)
    );
  },
  on: {
    connected: (_socket) => {
      // here is my own implementation of zustand state management
      // this method set connectedDate used after to (new Date().toISOString())
      networkActions.WSConnected();
    },
  },
});
```

```js
import { useRef, useEffect } from "react";
import { useQuery } from "@apollo/client";

import { useNetworkState } from "~/stores";

const defaultUpdateQuery = (prev, { subscriptionData }) =>
  subscriptionData.data || prev;

export default function useQueryWithSubsciption({
  query,
  subscription,
  updateQuery = defaultUpdateQuery,
  queryParams = {},
  subscriptionParams = {},
  variables = {},
}) {
  const { connectedDate } = useNetworkState(["connectedDate"]);
  const result = useQuery(query, {
    variables,
    ...queryParams,
  });
  const { subscribeToMore, refetch } = result;

  const connectedDateRef = useRef(connectedDate);
  useEffect(() => {
    if (
      connectedDateRef.current !== null &&
      connectedDateRef.current !== connectedDate
    ) {
      // console.log("refetch");
      refetch();
    }
    connectedDateRef.current = connectedDate;
    const unsub = subscribeToMore({
      document: subscription,
      updateQuery,
      variables,
      ...subscriptionParams,
    });
    return unsub;
  }, [
    connectedDate,
    connectedDateRef,
    refetch,
    subscribeToMore,
    subscription,
    subscriptionParams,
    updateQuery,
    variables,
  ]);

  return result;
}

```

```js
const {data, error, loading} = useQueryWithSubscription({
  query: MY_QUERY,
  subscription: MY_SUBSCRIPTION,
  variables: {
    id,
  },
});
```

This method can be improved and refetch when disconnected, it can be very easily improved for a usage where you want to rely on previous connectedDate to get only what you missed, passing it to custom callback for generating query and subscription variables for example.

Hope it helps :-)
