### ISSUE TITLE
useQuery won't stop polling when a certain variable is present

### ISSUE THREAD

**Issue by sithembiso** [apollographql/apollo-client#10252]
**Intended outcome:**
I'm trying to load data from the server using `useQuery` in the following way:
```ts
const { data, loading, refetch } = useQuery(GET_STREAMS, {
  variables: {
    username: username,
    assignee: assignee,
    archived: false,
    dueDate: {
      between: {
        max: new Date()
      }
    }
  }
});
```
I expect this to fetch data from the server without any issues. 

**Actual outcome:**
The query does retrieve data from the server, but it won't stop polling until I remove this variable:
```ts
dueDate: {
    between: {
        max: new Date()
    }
}
```
https://user-images.githubusercontent.com/6559905/199137362-934b756b-8009-423f-b754-000bfe53d92b.mov

**How to reproduce the issue:**
I'm not really sure, but every time I put that filter back, it starts again.

**Versions**
```
  System:
    OS: macOS 12.0.1
  Binaries:
    Node: 14.17.3 - /usr/local/opt/node@14/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/opt/node@14/bin/npm
  Browsers:
    Firefox: 104.0.2
    Safari: 15.1
  npmPackages:
    @apollo/client: ^3.4.16 => 3.4.16 
    @apollo/react-testing: ^4.0.0 => 4.0.0 
    apollo-upload-client: ^17.0.0 => 17.0.0 
```

**Comment by dylanwulf** [comment]
This is not an issue with apollo client, this is more of a side-effect of how React works. Every time React renders your component, a _brand new_ Date object is being created and passed into apollo client. Apollo client is fetching data from the server every time the variables change, as it was designed to do. To fix this, store your Date in state.

**Comment by sithembiso** [comment]
Coincidentally I came to the same realization just a few minutes ago. Thank you for the explanation, I had started digging deep into the cache revalidation mechanism 🤦🏾‍♂️
