### ISSUE TITLE
two queries with the same typeName

### ISSUE THREAD

**Issue by liorpevzner** [apollographql/apollo-client#10256]
I have two different queries that both return the an object with the same key, and typeName but the value is different.
apollo cache overrides those queries.
I tried following this thread, but I got confused and it wasn't exactly the same:
https://github.com/apollographql/apollo-client/issues/9192

so my firstQuery returns:

```
{
  "data": {
    "getCurrent": {
     {....some object"},
      "__typename": "Customer"
    }
  }
}
```

the second query returns:

```
{
  "data": {
    "getCurrent": {
      {... different object}
      },
      "__typename": "Customer"
    }
  }
}
```

im trying to define the typePolicies correctly... 
so I can do:

```
Customer:{
keyFields:[?],
}
```

Can anyone point me to the right direction?

**Comment by bignimbus** [comment]
Hi @liorpevzner, thanks for opening this issue!  If you think this is related to the issue you referenced, may I suggest closing this issue and posting your comment in that thread to consolidate?  If this is a distinct concern, though, would you be open to posting some more details?  I think the data in `some object` and `different object` may be information that can help narrow down what might be happening.  Our [community forums](https://community.apollographql.com/) are a great place to ask and answer questions like this as well.  Thanks again!
