### ISSUE TITLE
Persisted queries link should look at error `code` extension, not just message

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-client#10253]
The persisted queries link has logic that relies on looking for particular errors in the response.

That logic looks at the error's `message` field. But error messages are intended for human use are are often localized, scrubbed, etc. Apollo's errors all have a `code` extension that is more appropriate for error comparisons, and since [the original implementation in Apollo Server](https://github.com/apollographql/apollo-server/pull/1149/files#diff-24a64652be8a9bcdd92f25caf46a8fbf021f73ae2ecf14abfddf0197eb935daa) these errors have set specific `code`s (as does the [original implementation in Apollo Router](https://github.com/apollographql/router/pull/433/files#diff-0c8725450345103d430a00719d21ba9f69b834a9d5103feb103c69382a31f761R119-R123).  Users have [run into issues](https://github.com/apollographql/apollo-server/issues/2429#issuecomment-1173523777) where APQs stop working if they reformat error messages.

Apollo Client's persisted queries link should change to first look for `PERSISTED_QUERY_NOT_FOUND` and `PERSISTED_QUERY_NOT_SUPPORTED` in `error.extensions.code`, and only to secondarily fall back to looking at error messages. (The only reason to fall back to error messages at all would be to support non-Apollo-Server/Router implementations that set the expected message without the expected code.)

**Intended outcome:**

Users should be able to tweak error messages in their servers without breaking the APQ link.

**Actual outcome:**
Changing the PersistedQueryNotFound error message affects the APQ link.

**How to reproduce the issue:**
Read the source

**Versions**
All versions supporting APQs

**Comment by maclockard** [comment]
A related issue I've noticed is that when apollo client encounters unrelated errors, such as a `400` due to missing required arguments, it not only retries the query without a hash, it stops sending hashes for _all_ future queries.
