### ISSUE TITLE
🐛: Mutations with @defer only responds with the first part

### ISSUE THREAD

**Issue by lleadbet** [apollographql/apollo-client#10272]
> To clarify, this is happening from a non-federated AS4 instance, not router.

**Intended outcome:**
Using the `useMutation` hook with a mutation with `@defer` results in only the first chunk loading. 

For example, given a server responding with: 

```

---
content-type: application/json; charset=utf-8

{"hasNext":true,"data":{"makePayment":{"id":"1afa84cc-26a5-4820-a496-33c8366e03cd","__typename":"MakePaymentResult"}}}
---
content-type: application/json; charset=utf-8

{"hasNext":false,"incremental":[{"path":["makePayment"],"data":{"paymentStatus":{"__typename":"PaymentSuccess","id":"2a3a1ddd-81e1-4535-8a9c-e8dc1ce38026","billedAmount":39.854330085558395},"__typename":"MakePaymentResult"}}]}
-----
```

Only 
```
{"makePayment":{"id":"1afa84cc-26a5-4820-a496-33c8366e03cd","__typename":"MakePaymentResult"}
``` 
is reported in the `data` object. 

**Actual outcome:**
Mutations update with the correct data, same as with `useQuery` which works as expected. 

**How to reproduce the issue:**
Example Repo: https://github.com/lleadbet/graphql-galaxy-demo

**Versions**
```
  System:
    OS: macOS 12.6
  Binaries:
    Node: 16.16.0 - ~/.volta/tools/image/node/16.16.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.11.0 - ~/.volta/tools/image/node/16.16.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 106.0.5
    Safari: 16.0
  npmPackages:
    @apollo/client: ^3.7.1 => 3.7.1 
   ```

**Comment by alessbell** [comment]
This will require some changes to `QueryManager` most likely, inside of the `markMutationResult` method.

**Comment by jpvajda** [comment]
@alessbell  just to confirm, is there any change Apollo Router has to consider here or is this strictly on the client side? cc @abernix

**Comment by alessbell** [comment]
@jpvajda I don't have a test case that works against the router yet, but I'm not sure if the issue is in my local subgraph. @abernix, is there a mutation example you can share? If not I will go ahead and open a bug.

**Comment by lleadbet** [comment]
To clarify, this is happening from a non-federated AS4 instance, not router

**Comment by alessbell** [comment]
Yep - I was referring to my attempt to reproduce the issue using the router. When I use a subgraph with the same schema used in https://github.com/lleadbet/graphql-galaxy-demo, I get a "cannot query field 'makePayment' on type 'Query'" error from the router.

**Comment by jpvajda** [comment]
@lleadbet That's good info, thanks for clarifying that.

**Comment by alessbell** [comment]
Opened the router issue here: https://github.com/apollographql/router/issues/2099
