### ISSUE TITLE
useMutation - onError callbacks both called in hook and mutate options

### ISSUE THREAD

**Issue by leepowelldev** [apollographql/apollo-client#10287]
When using `useMutation` and setting a callback handler in the hook options as well as a handler in the mutate function options, both handlers are called when an error occurs. According to the docs this should not happen.
```
If you provide the same option to both useMutation and your mutate function, the mutate function's value takes precedence.
```
**Intended outcome:**
Only the mutate function `onError` callback should be called.

**Actual outcome:**
Both callback handlers are called.

**How to reproduce the issue:**
Repo can be found here reproducing the issue:
https://github.com/leepowelldev/apollo-client-bug-2

**Versions**
  System:
    OS: macOS 13.0.1
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Edge: 107.0.1418.42
    Firefox: 106.0.5
    Safari: 16.1
  npmPackages:
    @apollo/client: ^3.7.1 => 3.7.1 

![Screenshot 2022-11-15 at 21 03 55](https://user-images.githubusercontent.com/602052/202024909-95d9d0c0-d600-4739-9f97-9d16e700e770.png)

**Comment by leepowelldev** [comment]
Thanks!

**Comment by jerelmiller** [comment]
Hey @leepowelldev 👋 !

Version [v3.7.4](https://github.com/apollographql/apollo-client/releases/tag/v3.7.4) was just released which contains a fix for this issue. Thanks again for submitting the issue!
