### ISSUE TITLE
useLazyQuery default fetch policy changed after 3.6.6

### ISSUE THREAD

**Issue by maciejregula** [apollographql/apollo-client#10285]
Before version 3.6.6 of Apollo Client `useLazyQuery` was using "network-only" fetch policy.
Right now, we have to manually point that we want to use "network-only" fetch policy. The "cache-first" policy doesn't make sense for useLazyQuery

```js
  const [
    myLazyQuery
  ] = useLazyQuery(
    MY_LAZY_QUERY
  );

<button onClick={() => myLazyQuery()}>test lazy query button</button>
```
If we click button 3 times, the query will be executed only once (first click will cause network request, second and third click will result only cache response). If we want useLazyQuery working properly, we have to manually point network policy.

```js
  const [
    myLazyQuery
  ] = useLazyQuery(
    MY_LAZY_QUERY,
    {
       fetchPolicy: "network-only"
    }
  );

<button onClick={() => myLazyQuery()}>test lazy query button</button>
```

After upgrading Apollo Client, we have to add in every lazyQuery network policy manually :/

**Comment by jerelmiller** [comment]
Hey @maciejregula 👋 

Apologies for the churn here! I'm having a bit of trouble locating this change as [v3.6.6](https://github.com/apollographql/apollo-client/releases/tag/v3.6.6) looks like it added the `defaultOptions` API to `useLazyQuery`.

I'm not seeing much action on our part here so I'm going to go ahead and close this issue. Thanks!
