### ISSUE TITLE
subscribeToMore does not seem to use the already passed client nor does not have option to pass a custom Apollo Client instance

### ISSUE THREAD

**Issue by hussainb** [apollographql/apollo-client#10295]
Setup: Apollo Client with ReactJs using ApolloProvider.

Due to a requirement, I need to connect to the graphQL endpoint using a different Authorization token on a particular page while still holding on to the initially generated Auth token for later use.

To do this, once I acquire the new Auth token, using the new token I am creating a new ApollClient instance (with new httpLink and wsLink):

I then use the new client instance with useQuery and useLazyQuery functions as shown below:

```
  const [
    getData,
    { loading, error, data, subscribeToMore, refetch }
  ] = useLazyQuery(QUERY_GET_PROJECT_SUBMITTALS, { client: GQLClient });  // new client instance passed here
```

when I execute the getData() method, Iit fetches the data as expected, i.e using the new client instance.

But, when I try to subscribe to the data using subscribeToMore, it does not use the newly passed client instance but refers to the already configured client using the `<ApolloProvider>`

```
const unsubscribe = subscribeToMore({
      document: SUBSCRIBE_TO_DATA,
      variables: { projectId: params.projectId },
      updateQuery: (prev, { subscriptionData }) => {
        if (!subscriptionData.data) return prev;
        return subscriptionData.data;
      }
    });
```

**Comment by jerelmiller** [comment]
Hey @hussainb 👋 

We've made a number of fixes to `useLazyQuery` in recent versions of Apollo Client. Would you mind trying the latest version of the client (`v3.7.11` at the time of this writing) to see if the issue is fixed?
