### ISSUE TITLE
"Unknown type" messages are ambiguous to the point of being worthless

### ISSUE THREAD

**Issue by jcollum-nutrien** [apollographql/apollo-client#10304]
This is what I'm fighting with today: 

```
 "message": "Unknown type \"RecommendationListQueryInput\".",
            "locations": [
                {
                    "line": 1,
                    "column": 34
                }
            ],
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED",
                "exception": {
                    "stacktrace": [
                        "GraphQLError: Unknown type \"RecommendationListQueryInput\".",
                        "    at Object.NamedType (/usr/src/app/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:57:29)",
                        "    at Object.enter (/usr/src/app/node_modules/graphql/language/visitor.js:323:29)",
                        "    at Object.enter (/usr/src/app/node_modules/graphql/utilities/TypeInfo.js:370:25)",
```

OK, so I go to Apollo studio and look for the type: 

![image](https://user-images.githubusercontent.com/99687439/203195244-2c8598ec-ce76-4ab1-ad8d-82bd767dd7f2.png)

Well there it is. So what's the issue here? I'm stuck with guessing. Was one of the fields on that input the wrong type? Maybe.  This is no help. What's at line 1:34? The type `RecommendationListQueryInput`. That doesn't tell me where the issue lies. 

Surely this can be improved.

**Comment by henryqdineen** [comment]
You're probably aware but that error message is coming from [graphql-js](https://github.com/graphql/graphql-js). Can you show what you are trying to do with Apollo Client that causes the error to occur?

**Comment by jcollum-nutrien** [comment]
```
export const RECOMMENDATION_LIST_QUERY = gql`
  query RecommendationList($input: RecommendationListQueryInput!) {
    recommendationList(input: $input) {
    [redacted]
```

```
const usePrescriptionListQuery = (
  input: PrescriptionListQueryInput,
  skip?: boolean
): QueryResult<RecommendationListResult> => {
  const { dataProductClient } = useDataProductClient();

  const query = useQuery(RECOMMENDATION_LIST_QUERY, {
    skip,
    variables: { input: input },
    client: dataProductClient,
  });

  return query;
};
```

I'd rather keep the particulars of the query out of it for IP reasons. 

Should I post this feedback in the gql-js issue tracker?

**Comment by henryqdineen** [comment]
Thanks! And that error is happening in the browser console or where?

**Comment by jcollum-nutrien** [comment]
React code.

**Comment by jerelmiller** [comment]
Hey @jcollum-nutrien, is this error coming back from your server? Can you see this in the response from the network tab in your browser?

Could you also try executing this query to your backend with a plain `fetch`? It would be helpful to narrow down whether this is an Apollo client issue, or an issue with the server. You can use something like the following to get roughly the same request that Apollo client is making. Add/replace any values in the `fetch` call that you pass to your `HttpLink. You may also need additional headers depending on your server:

```ts
import { print } from 'graphql';

const RECOMMENDATION_LIST_QUERY = gql`
  query RecommendationList($input: RecommendationListQueryInput!) {
    recommendationList(input: $input) {
      # ...
    }
  }
`;

fetch('https://example.com/graphql', {
  method: 'POST',
  headers: {
    accept: '*/*',
    'content-type': 'application/json'
  },
  body: JSON.stringify({ 
    query: print(RECOMMENDATION_LIST_QUERY),
    operationName: 'RecommendationList',
    variables: { ... }
  })
})
  .then(res => res.json())
  .then(res => console.log(res))
```
