### ISSUE TITLE
Not semver compatible

### ISSUE THREAD

**Issue by epinault** [apollographql/apollo-client#10308]
hello

this is the 2nd time I am upgrading Appollo client from one minor to another where we end up with breaking changes affecting us

per https://semver.org/

```
Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes
MINOR version when you add functionality in a backwards compatible manner
PATCH version when you make backwards compatible bug fixes
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
```

this https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#potentially-disruptive and https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#potentially-disruptive-changes

should have likely been marked at Major would have been a better choice

I am just putting it out there as a suggestion to help with upgrade communication

thanks for your hard work

Need help or want to talk all things Apollo Client? Issues here are reserved for bugs, but one of the following resources should help:

* Apollo GraphQL community forums: https://community.apollographql.com
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests

**Comment by alessbell** [comment]
Hi @epinault 👋 I very much appreciate you taking the time to open this issue. I agree with the points you've raised: we generally avoid including non-backward compatible bug fixes in patch/minor releases, but we've made exceptions depending on the nature of the regression. I will share this with the team so we can review, and, again, we really appreciate this valuable feedback!
