### ISSUE TITLE
How do I distinguish between two queries to get Apollo Client typePolicies cache to work properly?

### ISSUE THREAD

**Issue by TanNguyenEnouvo** [apollographql/apollo-client#10313]
How do I distinguish between two queries to get Apollo Client typePolicies cache to work properly?

I have two GraphQL queries from our GraphQL server (see below), One gets all the invoices, and the second one filter the invoice which has the status “Paid”. When I use just one query all works fine. But when I use both queries, Apollo Client cache gets confused. A second query overrides the cache of the first query
The Apollo Client typePolicies are configured like this:

```
typePolicies: {
    Query: {
      fields: {
        getInvoices: {
          keyArgs: [],
          merge(existing = { items: [] }, incoming: any) {
            return mergeCache(existing, incoming);
          },
        },
      },
    },
  },
```

Query one:
```
const { data } = useGetInvoicesQuery({
    fetchPolicy: 'network-only',
    variables: {
      queryParams: {
        filters: [],
        limit: 10,
        page: 1,
      },
    },
  });
```
Which returns:
```
{
  "data": {
    "getInvoices": {
      "__typename": "IInvoices",
      “Items”: [
        {
          “id”: "195087645541707",
          "invoiceStatus": “Draf”,
          “totalAmount”: 60000
        },
        {
          “id”: "195086809826559",
          "invoiceStatus": "Paid",
          “totalAmount”: 88000
        },
        {
          “id”: "135407645541707",
          "invoiceStatus": “Partially Paid”,
          “totalAmount”: 90000
        },
      ]
    }
  }
}
```
And query two:
```
const { data } = useGetInvoicesQuery({
    fetchPolicy: 'network-only',
    variables: {
      queryParams: {
        filters: [
          {
            data: 'Paid',
            field: 'InvoiceStatus.name',
            operator: Query_Operator.Eq,
          },
        ],
        limit: 10,
        page: 1,
      },
    },
  });
```
Which returns:
```
{
  "data": {
    "getInvoices": {
      "__typename": "IInvoices",
      “Items”: [
        {
          “id”: "12387645541707",
          "invoiceStatus": “Paid”,
          “totalAmount”: 60000
        },
        {
          “id”: "195086809826559",
          "invoiceStatus": "Paid",
          “totalAmount”: 88000
        },
        {
          “id”: "13540762341707",
          "invoiceStatus": “Paid”,
          “totalAmount”: 90000
        },
      ]
    }
  }
}
```

How do I have to set up my typePolicies so that the cache can distinguish between the two queries?

**Comment by dylanwulf** [comment]
It's hard to know what you need without seeing the query & schema. My best guess would be this: 
`keyArgs: ['queryParams', ['filters']]`
See more here https://www.apollographql.com/docs/react/pagination/key-args#keyargs-array

**Comment by yj7** [comment]
Possibly related issue -> https://github.com/apollographql/apollo-client/issues/10296

**Comment by TanNguyenEnouvo** [comment]
> It's hard to know what you need without seeing the query & schema. My best guess would be this: `keyArgs: ['queryParams', ['filters']]` See more here https://www.apollographql.com/docs/react/pagination/key-args#keyargs-array

It's work, thank you so much
