### ISSUE TITLE
Refetch gets partial data from cache with errorPolicy none

### ISSUE THREAD

**Issue by EvertEt** [apollographql/apollo-client#10317]
**Intended outcome:**

Refetch (from useQuery) should have the same behaviour as the first fetch in regards to errorPolicy

**Actual outcome:**

Refetch does return partial cached data. 
1. query field A and B
2. A returns, B errors so query errors with partial data for A
3. refetch
4. Get data for A, not for B

**How to reproduce the issue:**

https://codesandbox.io/s/queries-example-app-final-forked-q2yzkk?file=/src/index.js:0-2069

**Versions**

  System:
    OS: macOS 12.6
  Binaries:
    Node: 16.15.1 - ~/Library/Caches/fnm_multishells/64442_1668614128695/bin/node
    Yarn: 3.2.3 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/Library/Caches/fnm_multishells/64442_1668614128695/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 103.0.2
    Safari: 16.1
  npmPackages:
    @apollo/client: ^3.5.9 => 3.5.9 
    apollo3-cache-persist: ^0.8.0 => 0.8.0 
    react-native-apollo-devtools-client: ^1.0.4 => 1.0.4

**Comment by alessbell** [comment]
Hi @EvertEt 👋  Thanks for reporting the issue and for the reproduction here! Indeed this looks like a bug - I'm in the process of writing a failing test and checking to see if it was caused by a regression. I'll post an update once I have more to share :)
