### ISSUE TITLE
Getting "reducer not a function" when doing `fetchMore`

### ISSUE THREAD

**Issue by Sawtaytoes** [apollographql/apollo-client#1032]
When I do `data.fetchMore()`, I get this error:
```
TypeError: reducer is not a function
    at mapFn (eval at <anonymous> (main.bundle.js:6389), <anonymous>:117:24)
    at eval (eval at <anonymous> (main.bundle.js:6389), <anonymous>:194:84)
    at Object.tryFunctionOrLogError (eval at <anonymous> (main.bundle.js:6587), <anonymous>:4:16)
    at ObservableQuery.updateQuery (eval at <anonymous> (main.bundle.js:6389), <anonymous>:194:41)
    at eval (eval at <anonymous> (main.bundle.js:6389), <anonymous>:122:19)
tryFunctionOrLogError @ VM41065:8
ObservableQuery.updateQuery @ VM41043:194
(anonymous) @ VM41043:122
```

I don't know what's causing it. I do have Redux in here, but I was getting that error before I hooked up the store in the `ApolloProvider` component directly. Even after adding it to my list of reducers I still get this error.

**You can find the full code here:**
https://github.com/Sawtaytoes/Twitter-Style-App-in-React/tree/feature/graphql

## package.json
```json
"apollo-client": "^0.5.19",
"react": "^15.4.1",
"react-apollo": "^0.7.1",
```

## apollo-client.jsx
```js
import ApolloClient, { createNetworkInterface } from 'apollo-client'

export const client = new ApolloClient({
  networkInterface: createNetworkInterface({
    shouldBatch: true,
    uri: '/api/graphql',
  }),
})
```

## tweets.jsx
```js
const GET_TWEETS = gql`query {
tweets {
  content
  postTime {
    time
    unixTime
  }
  user {
    username
  }
}}`

class Tweets extends PureComponent {
  static propTypes = { data: PropTypes.object };
  static defaultProps = { data: {} };

  render() {
    const { data } = this.props
    return (
      <div>
        <TweetList tweets={data.tweets} refresh={() => data.fetchMore(GET_TWEETS)} />
      </div>
    )
  }
}

export default graphql(GET_TWEETS)(stylesLoader.render(Tweets))
```

**NOTE:** The `TweetList` component does **not** have `connect()` or Redux enabled in this test.

**Comment by Sawtaytoes** [comment]
Firstly, I believe this need to be moved to the apollo-react issues. Since I don't know how to do that, I'm closing it here and re-posting it there.

**Comment by helfer** [comment]
As written in https://github.com/apollostack/react-apollo/issues/370, we need a better error message when `updateQueries` isn't provided. Maybe also a documentation issue.

**Comment by Sawtaytoes** [comment]
After this experience, I agree, the error should be more specific. It took me a while in the first place to even figure out it required an object at all as it kept erroring about getting `query` of `undefined`.

**Comment by stubailo** [comment]
The right way to do what you're trying to do is to call "refetch" right?
