### ISSUE TITLE
Migrate tests from `@testing-library/react-hooks` to `@testing-library/react`

### ISSUE THREAD

**Issue by jerelmiller** [apollographql/apollo-client#10333]
React hooks testing library does not have React 18 support and has [migrated](https://github.com/testing-library/react-testing-library/pull/991) `renderHook` to the core `@testing-library/react` library. As stated in the [README](https://github.com/testing-library/react-hooks-testing-library#a-note-about-react-18-support):

> As part of the changes for React 18, it has been decided that the renderHook API provided by this library will instead be included as official additions to both react-testing-library ([PR](https://github.com/testing-library/react-testing-library/pull/991)) and react-native-testing-library ([PR](https://github.com/callstack/react-native-testing-library/pull/923)) with the intention being to provide a more cohesive and consistent implementation for our users.

With the introduction of [suspense](https://github.com/apollographql/apollo-client/pull/10323) to Apollo client, its become more obvious that we need to work with a version of `renderHook` that works with React 18 since it uses the new [concurrent rendering APIs](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis). To ensure Apollo client works with React 18 out of the box, it's imperative we run our React 18 tests in a way that we expect our users will use React 18.

There is one tricky issue though... with the migration of `renderHook` to the core library, we [can't run](https://github.com/testing-library/react-testing-library/issues/1121) our React 17 tests through it. The suggestion is to use `@testing-library/react^12` (which we do), but unfortunately the `renderHook` function is not exported from that version. We should be able to patch that behavior using [`patch-package`](https://www.npmjs.com/package/patch-package). In fact, the [suspense PR](https://github.com/apollographql/apollo-client/pull/10323/files#diff-50bd25fc977459fcebb6384986bb41ef9ab4e5300597523f533c0fe69b9140a7) does this for us. Once this change is in `main`, we can look to slowly update our tests over time to use hook from the core testing library.

We can use [this migration guide](https://github.com/testing-library/react-hooks-testing-library/blob/chore/migration-guide/MIGRATION_GUIDE.md) to migrate over when we are ready.

**Comment by alessbell** [comment]
I have a few branches with these tests migrated already :) will be great to get the patch-package diff in there and then I will pick this up.
