### ISSUE TITLE
Source map locations are incorrect

### ISSUE THREAD

**Issue by tgriesser** [apollographql/apollo-client#1035]
First off great work on Apollo. Minor issue here, but the source map locations for the `.ts` files get lost in the current build script. For example in `index.js.map` the value 
```
"sources":["../../src/index.ts"]
``` 
is incorrect, it should be: 
```
"sources":["./index.ts"]
``` 
since the files all get merged into the same directory when released to npm

**Comment by helfer** [comment]
@tgriesser thanks! Best way to fix this would probably be to get rid of our custom deploy script. I'm not even sure why we had this any more. But I'd also be happy to accept a PR that fixes only the source maps, if you have time to make one! 👍

**Comment by helfer** [comment]
I think this is no longer a problem with the UMD bundle. At least I'm not having the issue. If it's still current, please re-open.
