### ISSUE TITLE
Can't complete the create mutation and the only response I get is bad request

### ISSUE THREAD

**Issue by MincePie** [apollographql/apollo-client#10360]
Hi all - thanks for the conversation here.  Because server responses with non-2xx status codes may contain payloads that do not conform to the GraphQL specification, your UI will have to define how to handle those payloads.  This can be done in Apollo Client via [Error Link](https://www.apollographql.com/docs/react/api/link/apollo-link-error/).  Hope that helps!

_Originally posted by @bignimbus in https://github.com/apollographql/apollo-client/issues/9568#issuecomment-1346938577_

**Comment by bignimbus** [comment]
Hi @MincePie 👋🏻  how can we help here?

**Comment by MincePie** [comment]
Does anyone know what this means or how to approach investigating it? 

I have an object with 2 strings, which I provide as my payload in my form. I can't complete the create mutation and the only response I get is bad request, with a network error that points to the initiator error as createHttpLink. 

I have added the network error catch to my apollo error handler, but still can't reveal any information that helps to point me in the direction of the next place to look for the source of the issue.

**Comment by jerelmiller** [comment]
@MincePie it might be helpful if you could try running this query with a plain `fetch` and see if you're getting the same or similar response back as you're seeing with Apollo Client. At the very least, this helps narrow down whether it's a server issue or Apollo Client issue.

Try this snippet of code in your browser console. This is approximately what Apollo Client is doing under the hood (add any headers/options you provide to your `createHttpLink` and replace the `...` with your actual values). NOTE: `query` should be a plain query string, not the value returned by `gql`.

```ts
fetch('https://your.url/graphql', {
  method: 'POST',
  headers: {
    accept: '*/*',
    'content-type': 'application/json'
  },
  body: JSON.stringify({ query: '...', variables: {...}, operationName: '...' })
}).then(res => res.json()).then(response => console.log(response))
```

If you're seeing a similar error in this case, I'm afraid there is not much Apollo Client can do. You'll need to see if you can figure out why your server is responding the way it is.
