### ISSUE TITLE
 One resource with multiple __typenames 

### ISSUE THREAD

**Issue by kdaniel21** [apollographql/apollo-client#10367]
Hey,

The problem we’ve been facing is that we have certain resources that can occasionally also appear with different `__typename`s. These alternative `__typename`s usually extend the original one. However, when performing cache updates, only one specific “version” (`__typename`) gets updated (as expected), and the others do not.

As a simple example:
```
interface BaseResource {
  name: String!
  age: Number!
}

type OriginalResource implements BaseResource {
  name: String!
  age: Number!
}

type ExtendedResource implements BaseResource {
  name: String!
  age: Number!
  extraField: Number!
}
```
There are queries that resolve `OriginalResource`, but some resolve `ExtendedResource` (the extra fields, in this case `extraField` is obviously not available when resolving `OriginalResource`). Hence, in the normalized cache there can be both `OriginalResource:1` and `ExtendedResource:1`. When updating `ExtendedResource:1`.`name`, one would expect `OriginalResource:1` to also reflect the changes but Apollo Client is not aware of any connection between the two and therefore `OriginalResource:1` remains not updated.

My question is whether Apollo (Client) has some neat feature to deal with this or we should restructure the schema.

**Comment by jerelmiller** [comment]
Hey @kdaniel21 👋

Take a look at the [`dataIdFromObject`](https://www.apollographql.com/docs/react/caching/cache-configuration#customizing-identifier-generation-globally) function you can pass to the `InMemoryCache`. I think this is what you're looking for since it allows you to customize the entire cache key.

Try something along the lines of this:

```ts
new InMemoryCache({
  dataIdFromObject(responseObject) {
    switch (responseObject.__typename) {
      case 'OriginalResource':
        // intentional fallthrough
      case 'ExtendedResource':
        // use the appropriate field here 
        return `Resource:${responseObject.id}`
      default:
        return defaultDataIdFromObject(responseObject);
    }
  }
})
```

**Comment by jerelmiller** [comment]
Hey @kdaniel21! I'm hoping the above [comment](https://github.com/apollographql/apollo-client/issues/10367#issuecomment-1351831276) addresses your issue so I'm going to go ahead and close this. Feel free to re-open if you need something else. Thanks!
