### ISSUE TITLE
Promise return value is neither rejected nor resolved when a fetch is aborted after component unmount

### ISSUE THREAD

**Issue by bwittenberg** [apollographql/apollo-client#10365]
Fetches are aborted when a component that uses a `useLazyQuery` hook is unmounted after querying. When a fetch is aborted, the returned promise is neither rejected nor resolved. See codesandbox for reproduction of the issue. The reproduction is simplified to show that the promise stays in a pending state, but it doesn't show why a consumer might care if the promise is resolved or rejected. I could explain in more detail if necessary, however, the current behavior seems undesirable. Returning a promise that is never resolved nor rejected seems like it could lead to more bugs than only the specific scenario where it caused a bug for me.

It seems like the returned promise should be rejected after a fetch is aborted.

**Intended codesandbox outcome:**

1. Click on button
2. expect query in chrome dev tools network tab
3. expect button to unmount
4. expect query in chrome dev tools network tab to be canceled
5. expect fetchPromise to reject
6. expect console log

**Actual codesandbox outcome:**

5. fetchPromise remains pending (not rejected, or resolved)
6. no console log

**How to reproduce the issue:**

https://codesandbox.io/s/lucid-solomon-zflnqp

**Versions**

3.7.2

**Comment by HitDaCa** [comment]
I'm facing the same issue

**Comment by jerelmiller** [comment]
Hey @bwittenberg 👋 !

Thanks for opening this issue! I've just opened #10427 that I'm confident will fix this issue. I've tested the PR against your reproduction and it appears this is fixed. This will likely go out with the next patch release. I'll let you know when that happens. Thanks!

**Comment by jerelmiller** [comment]
Hey @bwittenberg 👋 !

Version [v3.7.4](https://github.com/apollographql/apollo-client/releases/tag/v3.7.4) was just released which contains this fix. Thanks again for submitting the issue!

**Comment by bwittenberg** [comment]
Thanks for the update @jerelmiller , nice work!
