### ISSUE TITLE
The query argument is unknown! Please regenerate the types.

### ISSUE THREAD

**Issue by odwrotnie** [apollographql/apollo-client#10378]
**Intended outcome:**

Autogenerated `gql` file should not have:
```
export function gql(source: string): unknown;
```

**Actual outcome:**

The file contains comment about it:

```
/**
...
 * The query argument is unknown!
 * Please regenerate the types.
**/
export function gql(source: string): unknown;
```

**How to reproduce the issue:**

The project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).

**Versions**

```
  System:
    OS: macOS 12.6
  Binaries:
    Node: 19.3.0 - /opt/homebrew/bin/node
    npm: 9.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 15.6.1
  npmPackages:
    @apollo/client: ^3.7.0 => 3.7.1 
```

tsconfig.json

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "src"
  ]
}
```

**Comment by jerelmiller** [comment]
Hey @odwrotnie! Would you go into a bit more detail on what you mean here?

> Autogenerated `gql` file should not have:

What is being autogenerated here and what outcomes are you expecting?

---

As an FYI, Apollo Client itself does not do any code generation. Are you perhaps using [GraphQL Code Generator](https://the-guild.dev/graphql/codegen)? If so, you might consider opening this issue over there as there is nothing we will be able to do on the Apollo Client side.

**Comment by odwrotnie** [comment]
I can see that `npm run compile` it has generated 4 files:
- src/lib/graphql/fragment-masking.ts
- src/lib/graphql/gql.ts
- src/lib/graphql/graphql.ts
- src/lib/graphql/index.ts

But I can not use `gql` function in my classes since it has this message. I can see that all necessary classes are available in `src/lib/graphql/graphql.ts`.

**Comment by jerelmiller** [comment]
@odwrotnie Would you be willing to share what your `compile` script in your `package.json` looks like?

**Comment by odwrotnie** [comment]
Compile = `graphql-codegen`.

The codegen.ts looks like this:

```
import { CodegenConfig } from '@graphql-codegen/cli';
import { instap } from "./src/instap.config";

// https://www.apollographql.com/docs/react/development-testing/static-typing/
const config: CodegenConfig = {
    schema: instap.graphql.schemaUrl,
    documents: ['src/**/*.tsx'],
    generates: {
        './src/lib/graphql/': {
            preset: 'client',
            plugins: [],
            presetConfig: {
                gqlTagName: 'gql',
            }
        }
    },
    ignoreNoDocuments: true,
};

export default config;
```

The command prints:

```
npm run graphql

> instap-react@0.1.0 graphql
> graphql-codegen

✔ Parse Configuration
✔ Generate outputs
```

**Comment by jerelmiller** [comment]
@odwrotnie thanks! It looks like this is an issue for the [`graphql-code-generator` repo](https://github.com/dotansimha/graphql-code-generator/issues/new/choose). Would you mind opening this issue over there? Unfortunately there is not much we can do on our end as that repo is owned by a different org than Apollo. Hope they are able to help you with your issue!
