### ISSUE TITLE
Taro alipay miniprograme with apollo/client 3.7.3: ReferenceError: __DEV__ is not defined

### ISSUE THREAD

**Issue by sunan112** [apollographql/apollo-client#10380]
Taro : 3.5.10
apollo client: 3.7.5

The program works fine when I don't use apollo/client, and the ReferenceError when I use apollo/client times
ReferenceError: __DEV__ is not defined
![image](https://user-images.githubusercontent.com/15712613/208818471-935094bd-1225-4675-99de-476cc2c3209a.png)

This is how I define it
![image](https://user-images.githubusercontent.com/15712613/208818229-881afcb2-b8a2-4e85-b47f-4d0c8b64cb74.png)

**Comment by bignimbus** [comment]
Hi @sunan112 👋🏻  this is addressed in #10521, which when merged will be included in out 3.8 release.  If you get a moment please let us know if that fix is working on your end.  CC @benjamn

**Comment by alessbell** [comment]
The change @bignimbus was referring to is now released in our latest an alpha: you can install it with `npm i @apollo/client@alpha` or the package manager of your choice :) If you have a chance to test it out, would love to know if that helps!

**Comment by bignimbus** [comment]
Hi @sunan112 👋🏻  just wanted to follow up here - we are closing this issue as completed.  Please do feel free to open a new issue if you continue to see this happening after trying `npm i @apollo/client@alpha` 🙏🏻
