### ISSUE TITLE
Exports ES

### ISSUE THREAD

**Issue by msf-caesar** [apollographql/apollo-client#10393]
I have done extensive testing using Svelte 3.55.0 in conjunction with Apollo Client and the performance has been excellent. However, I suggest improving exports to ES, as in production environments it is necessary to specify `cache/cache.cjs` to avoid execution problems. In development, everything works smoothly.

![image](https://user-images.githubusercontent.com/113716133/210033557-217b425a-d899-4520-bb6e-fc2be7bfa3a2.png)

**Comment by bignimbus** [comment]
Hi @msf-caesar 👋🏻 does [this PR](https://github.com/apollographql/apollo-client/pull/9697) capture what you're asking for?  If so, this is something we'd like to ship with the next major version to avoid breaking changes for 3.x users.  Let us know!

**Comment by msf-caesar** [comment]
Perfect, that's what I'm looking for, thanks.
