### ISSUE TITLE
GraphQLWsLink throws ApolloError("undefined") on websocket errors

### ISSUE THREAD

**Issue by lovasoa** [apollographql/apollo-client#10394]
When a websocket error occurs an `ApolloError` is thrown with the string `"undefined"` set as its message property (tested on firefox). 

**Intended outcome:**
The error description string would say something like `"An error occurred in the connection with the websocket server"`, or another descriptive description string.

**Actual outcome:**
The error being passed is

```json
{
  "networkError": {
    "name": "ApolloError",
    "graphQLErrors": [
      {
        "isTrusted": true
      }
    ],
    "clientErrors": [],
    "networkError": null,
    "message": "undefined"
  }
}
```

**How to reproduce the issue:**
Create an apollo websocket connection using `GraphQLWsLink`, open the application in firefox, and disconnect from the network.

**Details**

The code in apollo that handles websocket errors seems to treat all error events that it doesn't detect as "close" events as graphQL errors: https://github.com/apollographql/apollo-client/blob/7dff5ebe9b3d295afb16177284dca5917d3f68f6/src/link/subscriptions/index.ts#L62-L81

And here is the error event that this code mishandles:
![image](https://user-images.githubusercontent.com/552629/210060306-00998913-f3fc-4c4d-a3ae-ad3b2bb73d2a.png)

The `"undefined"` string seems to be generated here: 
https://github.com/apollographql/apollo-client/blob/7dff5ebe9b3d295afb16177284dca5917d3f68f6/src/errors/index.ts#L21-L25

where `generateErrorMessage` expects all the elements in graphQLErrors to be instances of `Error`, even though `GraphQLWsLink` pushes an element of type `Event` in it.

**Comment by manojkumar3692** [comment]
can someone help on this , even im stuck here

**Comment by lovasoa** [comment]
Can anyone help me get my PRs merged ? @alessbell, maybe ? This bug is impacting our product.

**Comment by alessbell** [comment]
Hi again @lovasoa 👋  There was a problem with the above snapshot release that meant it did not contain your changes, but I've resolved the issue and re-published. You can now `npm i @apollo/client@0.0.0-pr-10410-20230217165056`. Sorry about the confusion!

I've confirmed that it contains your changes, so you should be set to test it out there while we review your PR. Thanks!

**Comment by lovasoa** [comment]
Hi ! Are there any news about the PR themselves ? Do you think they can be merged soon ? They are both quite small.

**Comment by lovasoa** [comment]
Hi ! Anything new ? Can I help with getting the PRs merged ?

**Comment by alessbell** [comment]
Hi @lovasoa! Appreciate your patience here, I've updated https://github.com/apollographql/apollo-client/pull/10586 and it's ready for review, you can follow that PR for updates. I hope to have it merged within a week. Thanks!

**Comment by alessbell** [comment]
[3.7.11](https://github.com/apollographql/apollo-client/releases/tag/v3.7.11) was just released with the relevant fixes. Thanks for the issue + PRs, @lovasoa!
