### ISSUE TITLE
Query strange behavior - unlimited loading state after success mutation with react-apollo

### ISSUE THREAD

**Issue by ARMGAMES** [apollographql/apollo-client#1039]
Created issue at react-apollo, but there guys suggested that this apollo bug. This is issue link -https://github.com/apollostack/react-apollo/issues/368

**Comment by helfer** [comment]
@SachaG mentioned in the other issue that he has tracked this down to partial data being provided to the reducer. I think we currently throw an error if there's partial data outside a fragment, but we don't do so when partial data is inside a fragment due to how we detect fragments.

I think a refactor will be needed to make sure that we can catch missing data in fragments as well.

**Comment by donedgardo** [comment]
I thought #980 fixed this. I'm having trouble with this too.
In my case my render method has a `if` statement that renders if the `this.props.data.loading` is false otherwise loads a spinner.
I `console.log` the data and it logs correctly:
```json
{"variables":{},"loading":false,"networkStatus":7,"foodtrucks":[{"name":"FoodTruck #1","__typename":"FoodTruck"},{"name":"FoodTruck #2","__typename":"FoodTruck"}]}
```
 but my app crashes with an odd error.
```
Error in observer.next 
```

**Comment by helfer** [comment]
@donedgardo #980 was a fix for a different issue. I'm not sure your error is related since it indicates loading: false. It's a bit hard to tell what your error is, because it doesn't include a stack trace. Did you forget to paste it, or is there just no stack trace?

**Comment by donedgardo** [comment]
My issue was isolated, i got it fixed, sorry and thanks.

**Comment by scf4** [comment]
Ran into a similar (or same) bug recently and was planning to open an issue.

If I use $unset it works fine (prepends item to list) but $push (to append) has me stuck in loading state.

**Comment by scf4** [comment]
Okay yes I believe my issue is related to the partial result bug.

I have this query:
```
thread: {
  posts: {
    edges: {
      node: {
        id
        content
      }
    }
}
```

and the mutation only returns `{ id, content }` of course.

So mutations can't work with Apollo if we want to use edges?

**Comment by helfer** [comment]
@scf I'm sorry, I can't really tell what your issue/question is. From experience, it seems that unlimited loading state is often the result of a `updateQuery` function not returning all data.

If it's indeed the case that the only difference is $unshift vs. $push, then it would be great if you could make a PR with a failing test. Just find the current test most relevant to your issue, copy, rename and adapt it to fail when using $push, but pass when using $unshift.

**Comment by helfer** [comment]
Is anyone still encountering this issue? If yes, please let me know and I'll reopen the issue.

**Comment by c10b10** [comment]
I am, response from the server is correct, `networkStatus` stuck at `2`, and `loading` stuck to `true`.
