### ISSUE TITLE
GraphQL general caching strategies

### ISSUE THREAD

**Issue by danielvanmil** [apollographql/apollo-client#10414]
There's a lot of information about how the Apollo client cache works technically. What I can't seem to figure out well is how it could be used in for example an application with concurrent users like a CMS? Can and if so, how would a client use the cache as data becomes stale very fast? What are strategies/techniques to determine whether the data in the cache is stale for a specific UX flow etc.

Or are in general the kind of systems where data changes often not suitable for using (GraphQL) client caches...

Anyone any more info about this?

**Comment by jerelmiller** [comment]
Hey @danielvanmil 👋 

I'd recommend posting this question in the [community forum](https://community.apollographql.com/) to get broader visibility across the Apollo community. Thanks!

**Comment by danielvanmil** [comment]
done, thanks!
