### ISSUE TITLE
Apollo client fetchMore not updating data cache?

### ISSUE THREAD

**Issue by siamahnaf198** [apollographql/apollo-client#10419]
I am try to use `@apollo/client` in my `nextjs` application (only frontend). My backend is done using `nestjs-graphql`. I am facing one problem using `@apollo/client`.

Here is my code-

`client.ts`

```
//Initialize apolloClient
let apolloClient: ApolloClient<NormalizedCacheObject>;

//Creating link
function createIsomorphLink() {
    return new HttpLink({
        uri: "http://localhost:5000/piechat",
        credentials: 'same-origin'
    })
}

//Create apollo client
function createApolloClient() {
    return new ApolloClient({
        ssrMode: true,
        link: createIsomorphLink(),
        cache: new InMemoryCache()
    })
}

//Initialize Apollo
export function initializeApollo(initialState = null) {
    const _apolloClient = apolloClient ?? createApolloClient()
    if (initialState) {
        const existingCache = _apolloClient.extract()
        const data = merge(initialState, existingCache)
        _apolloClient.cache.restore(data)
    }
    if (!apolloClient) apolloClient = _apolloClient
    return _apolloClient
}

//Use Apollo
export function useApollo(initialState = null) {
    const store = useMemo(() => initializeApollo(initialState), [initialState])
    return store
}
```

Then in nextjs `getServerSideProps`-

```
export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const apolloClient = initializeApollo()
  await apolloClient.query({
    query: GET_CONVERSATION_LIST,
    context: { headers: { authorization: `Bearer ${ctx.req.cookies["session"]}` } },
    errorPolicy: "all"
  })
  return {
    props: {
      initialApolloState: apolloClient.cache.extract(),
    }
  }
}
```

Then in one `conversation.tsx`(I use this data)-
`
const { data } = useQuery<GetConversationData>(GET_CONVERSATION_LIST);`

On the other component (`createConver.tsx`) I use `fetchMore` function-

```
const { fetchMore } = useQuery(GET_CONVERSATION_LIST)

useEffect(() => {
    if (data) { //If new data creation is success
        fetchMore({
            context: { headers: { authorization: `Bearer ${getCookie("session")}` } }, updateQuery(_, { fetchMoreResult }) {
                return fetchMoreResult
            }
        })
    }
}, [data])
```

Everything is well. But when I refresh my page, I see that new data not comes. please see this gif- enter image description here

![Problem](https://user-images.githubusercontent.com/78312010/211150821-b26fc789-5d7c-48c6-9a8f-d719af848649.gif)

But I am not understanding what is the problem. I am not getting any docs or any things else. Please help me anyone.

**Comment by diegomarcuz** [comment]
Have you debugged the response of the `GET_CONVERSATION_LIST` query to check how many conversations exist? It seems your `fetchMore` is not merging the previous result with the new one

**Comment by diegomarcuz** [comment]
There is one another possibility using [`refetch`](https://www.apollographql.com/docs/react/data/queries#refetching) with new params, is not good for your case?

**Comment by siamahnaf198** [comment]
I can solve this. I have some wrong code in client.ts. Thank you very much. But If you help me in the following, I will be great to you.

Qustion-

I use refetchQueries after mutations like this-

 ```
const [createConversation, { data, error, loading }] = useMutation<CreateConversationData>(CREATE_CONVERSATION, {
        awaitRefetchQueries: true,
        refetchQueries: [{
            query: GET_CONVERSATION_LIST,
            context: { headers: { authorization: `Bearer ${getCookie("session")}` } }
        }]
    });
```

Here in refetch queries, I have to send `context`. But my question is, is there any way to set `context` globally for all refetch queries in my projects.

**Comment by bignimbus** [comment]
Hi @siamahnaf198 👋🏻  thanks for posting!  Does `setContext` in `Apollo Link` address your need for setting `context` globally?  https://www.apollographql.com/docs/react/api/link/introduction/#example

**Comment by diegomarcuz** [comment]
Hey @siamahnaf198, sorry about the delay and glad you got the resolution. As @bignimbus said, when you instantiate the apollo client you can set the header
