### ISSUE TITLE
Getting issue following issue related to my Apollo-client   while upgrading angular project to v15

### ISSUE THREAD

**Issue by gourango121** [apollographql/apollo-client#10426]
I am trying to migrate my angular project but stuck in following issue ,

Error: node_modules/apollo-link/lib/types.d.ts:5:18 - error TS2430: Interface 'ExecutionResult<TData>' incorrectly extends interface 'ExecutionResult<{ [key: string]: any; }, { [key: string]: any; }>'.
  Types of property 'data' are incompatible.
    Type 'TData | null | undefined' is not assignable to type '{ [key: string]: any; } | null | undefined'.
      Type 'TData' is not assignable to type '{ [key: string]: any; } | null | undefined'.
        Type 'TData' is not assignable to type '{ [key: string]: any; }'

**Intended outcome:**

**Actual outcome:**

**How to reproduce the issue:**

  "@angular-devkit/build-angular": "^15.0.4",
    "@angular/compiler-cli": "^15.0.4",
    "@angular/language-service": "^15.0.4",
    "@commitlint/cli": "^8.0.0",
    "@commitlint/config-conventional": "^8.0.0",
    "@commitlint/prompt-cli": "^8.0.0",
    "@graphql-codegen/cli": "1.16.3",
    "@graphql-codegen/near-operation-file-preset": "^1.17.0",
    "@graphql-codegen/typescript": "1.16.3",
    "@graphql-codegen/typescript-apollo-angular": "1.16.3",
    "@graphql-codegen/typescript-operations": "1.16.3",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.12.39",
    "codelyzer": "^6.0.0",
    "graphql-cli": "^4.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "prettier": "^2.0.5",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0"

**Versions**

**Comment by bignimbus** [comment]
Hi @gourango121 👋🏻  thanks for opening this issue!  I was looking for which version of `@apollo/client` (and maybe `apollo-angular`) you were using.  I think you pasted your `devDependencies` list but not `dependencies` though, so it may be tough to narrow down what could be going on.  This is just a wild guess but try ensuring that `apollo-angular` (if you're using it) and `@apollo/client` are set to the latest releases of both.  I'll close this for now but please do feel free to ping me if you need more support here 🙏🏻
