### ISSUE TITLE
useFragment + SRR results in "Missing getServerSnapshot" error

### ISSUE THREAD

**Issue by lennyburdette** [apollographql/apollo-client#10457]
### Issue Description

Trying to use `useFragment_experimental` in an server-side-generated or -rendered React app results in this error:

```
Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.
```

It looks like `useFragment_experimental` doesn't provide the third `getServerSnapshot` parameter as described in the [React docs](https://beta.reactjs.org/reference/react/useSyncExternalStore#adding-support-for-server-rendering)

https://github.com/apollographql/apollo-client/blob/0b07aa955bab2e929f21590b565507a66f930539/src/react/hooks/useFragment.ts#L74-L96

I'm pretty sure you can just pass the second `getSnapshot` param twice and it'll work (I hacked at my node_modules and it seemed to work fine?)

### Link to Reproduction

https://github.com/lennyburdette/ubiquitous-dollop

### Reproduction Steps

```
npm i
npm run subgraph # terminal 1
npm run router # terminal 2
npm run dev # terminal 3
```
open [http://localhost:3000](http://localhost:3000).

Observe the error modal. You can also navigate to [http://localhost:3000/client-only](http://localhost:3000/client-only) to see the hook working correctly in the browser.

**Comment by alessbell** [comment]
Closed via https://github.com/apollographql/apollo-client/pull/10458, will be released in `3.7.5.`. Thanks!
