### ISSUE TITLE
Remove unused fragments with local resolver

### ISSUE THREAD

**Issue by danielvanmil** [apollographql/apollo-client#10477]
When we have a (pseudo code) schema like:

```
type Item {
  name: String
  user: User
}

type User {
  name: String
}

Query {
  getItem(): Item
}
```

And a query:

```
fragment UserFragment on User {
  name
}

query getItem {
  getItem {
    name
    user @client {
      ...UserFragment 
    }
  }
}
```

Apollo sends to the server:

```
# This fragment should not be send
fragment UserFragment on User {
  name
}

query getItem {
  getItem {
    name
  }
}
```

Apollo still sends the UserFragment in the query and the server responds with a "Unused fragment ..." error

Should the fragment not be sent by Apollo client or are there any other options to fix this? (we also use GraphQL generator etc.)

**Comment by bignimbus** [comment]
Hi @danielvanmil 👋🏻  thanks for opening this issue!  I'd like to help narrow down what might need to be done here.  I think the `pseudo code` qualification might be a limitation since the details of the syntax matter.  One thing I noticed is that in your schema the output type of the `getItem` field is `Item`.  The type condition for `UserFragment` is `User`, however.  That may be a factor here.  Does that help?

**Comment by danielvanmil** [comment]
Thanks for the quick reply! Updated comment, more clear now?

**Comment by bignimbus** [comment]
Thanks for the update @danielvanmil - one more question: which server are you using?

According to [the spec](https://spec.graphql.org/October2021/#sec-Fragments-Must-Be-Used):

> #### Fragments Must Be Used
> 
> **Formal Specification**
> 
> * For each {fragment} defined in the document.
> * {fragment} must be the target of at least one spread in the document
> 
> **Explanatory Text**
> 
> Defined fragments must be used within a document.
> 
> For example the following is an invalid document:
> 
> ```raw graphql counter-example
> fragment nameFragment on Dog { # unused
>   name
> }
> {
>   dog {
>     name
>   }
> }
> ```

I was able to write a failing test, can you confirm this describes what you're seeing?

```diff
diff --git a/src/utilities/graphql/__tests__/transform.ts b/src/utilities/graphql/__tests__/transform.ts
index 7a5f3dc39..21bb33306 100644
--- a/src/utilities/graphql/__tests__/transform.ts
+++ b/src/utilities/graphql/__tests__/transform.ts
@@ -948,4 +948,31 @@ describe('removeClientSetsFromDocument', () => {
     const doc = removeClientSetsFromDocument(query)!;
     expect(print(doc)).toBe(print(expected));
   });
+
+  it('should remove fragments from documents where all fields in the fragment are annotated with @client', () => {
+    const query = gql`
+      fragment authorInfo on Author {
+        name
+      }
+
+      query Book {
+        book {
+          title
+          author @client {
+            ...Author
+          }
+        }
+      }
+    `;
+
+    const expected = gql`
+      query Book {
+        book {
+          title
+        }
+      }
+    `;
+    const doc = removeClientSetsFromDocument(query)!;
+    expect(print(doc)).toBe(print(expected));
+  });
 });

```

**Comment by danielvanmil** [comment]
@bignimbus : I think our use case uses a nested fragment, should this one succeed (as it doesn't)?:

```
it('should remove fragments from documents where all fields in the fragment are annotated with @client', () => {
    const query = gql`
      fragment authorInfo on Author {
        name
        ...addressInfo
      }

      fragment addressInfo on Address {
        street
      }

      query Book {
        book {
          title
          author @client {
            ...authorInfo
          }
        }
      }
    `;

    const expected = gql`
      query Book {
        book {
          title
        }
      }
    `;
    const doc = removeClientSetsFromDocument(query)!;
    expect(print(doc)).toBe(print(expected));
  });
```

**Comment by bignimbus** [comment]
Thanks @danielvanmil - it looks like that's a failing case, good catch.  I found https://github.com/apollographql/apollo-client/issues/5192 so I will close this issue do we don't have duplicates.  That issue has a PR attached to it from a community member but it's pretty stale.  I'll make a note of this for the team.  Please do follow that issue to track progress.  Thanks so much!
