### ISSUE TITLE
useLazyQuery ignores changes to the query document

### ISSUE THREAD

**Issue by laytong** [apollographql/apollo-client#10496]
### Issue Description

Despite what the documentation for useLazyQuery appears to suggest. Updating the "Query" option inside the trigger of the lazyQuery does nothing.

i.e. 
`const [fetchMyQuery] = useLazyQuery(QUERY_1)`

and later calling `fetchMyQuery({ query: SOME_OTHER_QUERY})` still calls QUERY_1

### Link to Reproduction

https://codesandbox.io/embed/great-mestorf-f9nmze?fontsize=14&hidenavigation=1&theme=dark

### Reproduction Steps

useLazyQuery with a default gql query,

Override it

The original query is executed and changes are ignored.

**Comment by jerelmiller** [comment]
Hey @laytong 👋 

This looks related to #10198, just used in a slightly different way. Seeing as `useQuery` supports the ability to [swap queries](https://github.com/apollographql/apollo-client/blob/b4a4bd16a911a233de6ada47780c84512f885401/src/react/hooks/__tests__/useQuery.test.tsx#L775-L810), I see no reason this shouldn't either. 

I can't guarantee a time frame on a fix, but we will try to get to this when we can!
