### ISSUE TITLE
Query doesn't read from cache after a mutation is run.

### ISSUE THREAD

**Issue by Zikoat** [apollographql/apollo-client#10498]
### Issue Description

Hi,

The script `reproduceBug.js` in the repo has a bug where we get into a state where we cannot update the cache. The script logs 2 values to the console. One is running the query and one is getting it from the cache. These returned values be the same, but the query seems to be "disconnected" from the cache, and any updates to the cache does not have an effect on the query. I have tried stepping through the apollo client code, but it is slightly too complex, so it would be nice if you could take a look and give us a monkey-patch we can use to workaround this issue.

### Link to Reproduction

https://github.com/Zikoat/apollo-client-mutation-cache-bug

### Reproduction Steps

* Clone repo
* run `npm i`  
* `npm start`
* open the app, and check the console

At the end of the script we are in a bad state. All updates to the cache for the `hello` field will not be returned from `client.query()`, and it will instead return the last value before we ran the mutation. The new value we write to the cache is still returned by `client.readQuery()`.

Expected behavior: `client.query()` returns  { hello: "world! 2" }.
Actual behavior: `client.query()` returns { hello: "world! 1" }.

This behavior can be seen in the following versions:

- vue 2 + vue-apollo@3.1.0 + apollo-client@2.6.10
- @apollo/client@3.7.5

**Comment by Zikoat** [comment]
Hi again,

I am purposefully not passing a link in the apollo client. This is because we don't want to send network requests, but only get the items from the cache. I have also tried creating the client with a terminating link, but this created the same behavior

```diff
+ const terminatingLink = new ApolloLink((vars) => {
+   return null;
+ });
+
 const client = new ApolloClient({
+  link: terminatingLink,
   cache: new InMemoryCache(),
 });
 ```

I tried a few different ways of creating a terminal link, like `return new Observable(()=>undefined)` but it didn't work.

However, when reading through the tests i see this line, which shows how to create a terminating link:
https://github.com/apollographql/apollo-client/blob/b214dd1d31cdfe6b5477bb5887a7d9615a302b27/src/link/core/__tests__/ApolloLink.ts#L949

## solution

So after adding this, the code works:

```diff
 const terminatingLink = new ApolloLink((vars) => {
-  return null;
+  return Observable.of(vars);
 });
 ```

It would be nice to write in the documentation how to create a terminating link, or add a terminating link by default if there are none passed to the ApolloClient constructor, or warn if the terminating apollo link is set up incorrectly/returns an invalid value.

**Comment by jerelmiller** [comment]
Hey @Zikoat 👋 !

Does [this snippet](https://www.apollographql.com/docs/react/api/link/introduction#the-terminating-link) in the docs about terminating links help? We always welcome suggestions to our documentation, so if there is more info that you'd like to see, let us know! Thanks for the feedback.
