### ISSUE TITLE
Modifying useQuery offset issue

### ISSUE THREAD

**Issue by snownoop** [apollographql/apollo-client#10505]
So i created a query and tried to modify variable (useRef) that i used as offset for useQuery hook, inside variable object.
And i noticed that after i modify this variable my query is called again automatically, overriding my previous results. Any ideas why it is happening, and any docs/examples where i can understand why it is happening ?
Here is code example:

```
const { data, loading, fetchMore } = useQuery<fetchPosts>(GET_POSTS, {
    variables: {
      offset: someUseRefVar.current,
      limit: LOAD_LIMIT,
    },
    onError: (err) => {
      toggleNotification({ content: err?.message, duration: 5000 });
    },
    onCompleted: (ddata) => {
      totalPostsCount.current = ddata?.postsWithTotal.total;
    },
  });
  
  // So here after someUseRefVar.current got changed query is called again automatically, but i want to do it manually with fetchMore
  useEffect(() => { someUseRefVar.current += 5 })
```

**Comment by bignimbus** [comment]
Thanks for opening this issue @snownoop 👋🏻 

In short, whenever the `variables` are modified then the query will fetch new data.  Changing the value of `variables.offset` from `5` to `10` will produce that effect.  I'll close this as completed for now but please do feel free to continue this conversation in our [discord server](https://discord.gg/graphos)!
