### ISSUE TITLE
Considering allowing passing fetch options to `.query/.mutation` methods

### ISSUE THREAD

**Issue by patrick91** [apollographql/apollo-client#10525]
Hi there! I was playing around with Next.js 13 and I was using Apollo Client in a Server Component, and I noticed we don't allow passing custom fetch options when doing a query or mutation[1] so we can't use Next.js [custom caching options](https://beta.nextjs.org/docs/api-reference/fetch#fetchurl-options), which would help since Next.js does cache any http request done in Server Components[2].

<img width="650" alt="CleanShot 2023-02-06 at 18 19 52@2x" src="https://user-images.githubusercontent.com/667029/217053601-8bcf6d51-4844-4eaf-8778-68f6bc11cca8.png">

I imagine the API looking like this:

```tsx
const NowApollo = async () => {
  const { data } = await client.query({ 
    query,
    fetchOptions: {
       next: { revalidate: 10, }
    }
   });

  return <ResultRow text="Now via Apollo" result={data.currentTime} />;
};
```

Let me know if you have any question about this :)

[1] might not be important for mutation, but I guess it is worth being consistent 😊
[2] if you need to revalidate the whole page you can do that with a segment config, see https://beta.nextjs.org/docs/api-reference/segment-config#revalidate

**Comment by jerelmiller** [comment]
@patrick91 does using `context` help you here? It looks like `HttpLink` will pull [`fetchOptions`](https://www.apollographql.com/docs/react/api/link/apollo-link-http#fetchoptions-1) from context and use those:

```ts
await client.query({
  context: {
    fetchOptions: {
      next: { revalidate: 10 }
    }
  }
});
```

**Comment by patrick91** [comment]
@jerelmiller yup, thanks, that works like a charm, sorry I totally missed it!
