### ISSUE TITLE
Nested fields in fragments not passed to props if it is a mix of a  type and interface

### ISSUE THREAD

**Issue by bmsuseluda** [apollographql/apollo-client#10531]
### Issue Description

Hello together,

when using multiple fragments, normally the props are merged, but not if im using a fragment from a interface

Query:
```gql
  query people {
    people {
      ...PersonFromType
      ...PersonFromInterface
    }
  }

  fragment PersonFromType on ExtendedPerson {
    id
  }

  fragment PersonFromInterface on Person {
    id
    name
  }
```

Schema:
```gql
  type Query {
    people: ExtendedPerson
    peopleWithStreet: ExtendedPerson2
  }

  interface Person {
    id: ID!
    name: String!
  }

  type ExtendedPerson implements Person {
    id: ID!
    name: String!
    age: Int
  }
  
  type ExtendedPerson2 implements Person {
    id: ID!
    name: String!
    street: String
  }
```

With this i would expect to get id and name from people, but i'm getting id only.
Interestingly, i get both fields from the backend in the network console in our application, but they are not in the result of the query in javascript.

I hope you can help us.
Thanks

### Link to Reproduction

https://github.com/bmsuseluda/apollo-client-merge-bug

### Reproduction Steps

Just start the app and you can see the result on the page.

**Comment by dylanwulf** [comment]
Do you have the `possibleTypes` option set up in your apollo-client config? It's required if you want to use fragments on interfaces
https://www.apollographql.com/docs/react/data/fragments/#using-fragments-with-unions-and-interfaces

**Comment by bmsuseluda** [comment]
That was the trick. Thank you very much
To generate the possibleTypes we are using https://the-guild.dev/graphql/codegen/plugins/other/fragment-matcher
