### ISSUE TITLE
useQuery and useMutation hooks stuck on loading state ONLY when testing with IOS Testflight

### ISSUE THREAD

**Issue by evanj354** [apollographql/apollo-client#10535]
I am building a react-native application using expo-sdk, with a GraphQL server as the backend. I've tested the application locally, and my useQuery and useMutation hooks are working fine with the backend server. However, as soon as I build the application binaries and push them to IOS testflight for validation, all of the hooks stop working. The interesting part is, I can see server-side logs for the hook request being sent from the application on testflight, so it isn't an issue with the requests reaching the backend. The server is processing the requests and preparing response payload, but the apollo client doesn't seem to ever receive the response and hence doesn't update its loading state.

```
const [ listCustomers, { loading, error, data } ] = useMutation(listCustomersGraphQl, {
  fetchPolicy: 'network-only',
  variables: { username }
});

if (loading) { // Loading is perpetually true
  return <View style={styles.loadingStyle}><Text>Loading</View>
}
```

npmPackages:
@apollo/client: 3.5.10
expo: 46.0.0
react-native: 0.68.0
react: 17.0.2
graphql: 16.3.1

**Comment by bignimbus** [comment]
Hi @evanj354 👋🏻  thanks for opening this issue.  Unfortunately it's hard to say what might be going on here without the ability to run your application.

I'm looking at your code sample and am having a bit of trouble understanding it.  Here are some observations.  First, I'm accustomed to a variable name like  `listCustomers` to be used in a query, not a mutation.  Second, I'm wondering why you're passing variables in the second argument to `useMutation` rather than the `listCustomers` function.

But to the main point, for this issue we'll need to be able to run your code to help narrow down what might need to be changed or to determine whether there's a bug.  Let us know how you'd like to proceed and thanks again!

**Comment by evanj354** [comment]
Thanks for the response @bignimbus. Apologies, I'm not sure how I came up with that code snippet, but it is not the correct one. Here's a direct link to the code in the github repo that is not working. https://github.com/MeetCelebrities/MeetCelebrities/blob/main/app/screens/CelebrityList.js#L15-L26. The useQuery hook I highlighted never returns data and is perpetually stuck on loading state. 

As I mentioned, everything works perfectly when I start an expo server locally and test. However, as soon as I deploy the app to IOS Testflight or the IOS appstore itself, the hook stop working. I also tried out the useMutation hooks as well as switching the useQuery to useLazyQuery and it gives the same result.

I saw other users having similar issues with perpetual loading states with specific versions of react + @apollo/client. I've tweaked versions of both to see if that would fix the issue, but that didn't seem to work. Do you have any idea why this might be working when testing locally but not on IOS Testflight? Could it have something to do with how apollo client operates after the IOS binaries are built?

**Comment by evanj354** [comment]
Not sure about the best way to reproduce this, as the issue is only present on Testflight. I could potentially add you as a beta tester for the app if you think that would be useful.

**Comment by bignimbus** [comment]
Thanks for that info - can you try updating to the latest release (as of now, 3.7.7) and see if that helps?

**Comment by evanj354** [comment]
I just tried that out and to no avail. I've been playing around with many different versions of @apollo/client and react, as changing those versions seems to fix the issue for others encountering similar problems (Ex: https://github.com/apollographql/apollo-client/issues/9668). Are there any custom logs I could enable to see more details on how the apollo client is handling responses from the server, if any?

**Comment by bignimbus** [comment]
This is very odd and must be very frustrating. Regarding logging, have you tried this?

```ts
import { setLogVerbosity } from "@apollo/client";
setLogVerbosity("debug");
```

Also are you able to use `debugger;` or breakpoints with your TestFlight build?

**Comment by evanj354** [comment]
Hi bignimbus. After some more debugging, I was able to determine that the issue was not caused by Apollo client. The issue was, after the useQuery hook finished, a RN Image within another sub component was supposed to appear, but was never loading in Testflight. For some reason the `defaultSource` property on a RN Image worked locally, but not on testflight after the app binaries were built (due to some issues finding the path of the local image source after build). Since there were no error logs in Tesflight from the image load failure and the component never appears, it gave the impression that the apollo hook was stuck loading. After fixing the faulty image path, everything worked perfectly. Thanks for your help with debugging this!

**Comment by bignimbus** [comment]
Thanks for the update @evanj354, glad you were able to figure out what was going on! Have a good weekend 🙂
