### ISSUE TITLE
unsubscribe from subscribeToMore upon filter parameters change

### ISSUE THREAD

**Issue by zned45** [apollographql/apollo-client#10570]
Hi everyone, I am building a dashboard with a real-time list that has filters that affect the results shown. So my approach to this is query results from API and the subscribe to the updates on results. Since we have some filters, everytime the use changes the filter parameters, we need to query for results and change the subscription parameters, which is what brings me today, since I haven't been able to understand how to change the active subscription parameters or even cancel it and resubscribe.

```
const RECORDS_QUERY = gql`
...
`;

const RECORDS_SUBSCRIPTION = gql`
...
`;

...
const [records, setRecords] = useState([]);

...
const [getRecords, { subscribeToMore }] = useLazyQuery(RECORDS_QUERY);

...

const getRecordsFromAPI = async(filters) => {
  const { data, error } = await getRecords({variables: filters});
  if (!error) {
    setRecords(data.records);
    subscribeToMore({
       document: RECORDS_SUBSCRIPTION,
       variables: filters,
       updateQuery: (prev, data) => {
         setRecords(data.subscriptionData.data.records);
       }
    })
  }
}

```

If you could provide me some help it would be great!

Thank you for your time.

**Comment by jerelmiller** [comment]
Hey @zned45 👋 

The `subscribeToMore` function returns a function that allows you to unsubscribe from the subscription. You should be able to then call `subscribeToMore` again with the updated parameters to resubscribe to that subscription.

```ts
const unsubscribe = subscribeToMore({...})

unsubscribe();

// ...

subscribeToMore({ variables: updatedFilters })
```

---

In general these questions are great conversation in our [discord server](https://discord.gg/graphos) or [community forums](https://community.apollographql.com/). Hope this helps!
