### ISSUE TITLE
New Fetch Policy 

### ISSUE THREAD

**Issue by yarosdev** [apollographql/apollo-client#10583]
Hi, there is one policy that could be very helpful, I call it `cache-or-network`.

First it loads data from cache if there is a data then it done. If there is no cache then it makes a request via network.

Use case, for example, we have a news feed with infinity scrolling feature. When I scroll down and  jump to the post view page then I click a back button (history mode) after I return to the feed page and I want to preserve scroll position without reloading a list with posts.

So it would looks like
```
useQuery(..., { 
        fetchPolicy: savedScrollPosition ? 'cache-or-network' : 'cache-and-network' 
});
```

**Comment by phryneas** [comment]
Could you explain how that would differ from the default of `cache-first`?
It seems to me that you are describing exactly that.
![image](https://user-images.githubusercontent.com/4282439/220156148-f911a1db-47bc-4e1d-b668-f688bafd1ef7.png)

**Comment by yarosdev** [comment]
I have not noticed that, sorry. It's exactly what I described
