### ISSUE TITLE
Subscription sub/unsub is non-sequential

### ISSUE THREAD

**Issue by Bingdom** [apollographql/apollo-client#10619]
### Issue Description

Using subscribe() and unsubscribe() on an observer is transmitted non-sequentially.

We can observe that in React, these events are being fired in the order I'd expect:
![image](https://user-images.githubusercontent.com/19663343/222356611-119a0e07-874e-4d66-8c55-53863dc3022e.png)

However, "subscribe" is being called before "complete" in the graphql websocket
![image](https://user-images.githubusercontent.com/19663343/222356750-45ccc97a-7582-4fcf-89f2-3e7c2125267e.png)

This is causing me issues as I'm using a pub/sub model, where I need a register to know where to dispatch events to. This is subbing to something already, then unsubbing.

### Link to Reproduction

https://codesandbox.io/s/keen-sara-prg63s

### Reproduction Steps

Please use the provided link. Ensure you're on the subscription page.

Switch between A and B and view console logs.
In addition, view networking logs. You can see that the console logs don't reflect the network logs.

**Comment by bignimbus** [comment]
Hi @Bingdom 👋🏻  I'm having trouble running this reproduction in CodeSandbox.  I get errors using `graphql-ws` that are resolved when downgrading to `4.9.0` but then I see the following in the console:

```
Firefox can’t establish a connection to the server at wss://uifesi.sse.codesandbox.io/graphql. [sandbox.6190e30a5.js line 1 > eval:256:31](https://codesandbox.io/static/js/sandbox.6190e30a5.js%20line%201%20%3E%20eval)
Uncaught Error: Socket closed with event 1006
```

Any advice?  Apologies if I'm missing something obvious 😅

**Comment by Bingdom** [comment]
Hey @bignimbus 

I should've kept the original text, but essentially I noticed the api endpoints aggressively shut down.
We can wake them up by connecting to this URL:
https://uifesi.sse.codesandbox.io/graphql

As specified in the original template (when it notices a connection error):
https://codesandbox.io/s/github/apollographql/react-apollo-error-template

**Comment by bignimbus** [comment]
Thanks @Bingdom!  I'm able to see what you see now.  Unfortunately this is not something that we can reliably control in the client - managing the order of events in websockets is not something we can guarantee.  There may opportunities to structure your application code to work around the constraints you're dealing with here though!  Please do feel free to start a thread in our [Discord](https://discord.gg/graphos) or [community forum](https://community.apollographql.com) and I'm sure one of the maintainers or community members can offer some suggestions!

**Comment by Bingdom** [comment]
Hello,

Thanks for your response.

Apologies for my stubbornness-
Websockets is based on TCP. The order is chronological and the only way it could change is if there was an intermediary somewhere.

Is there a reason why the order cannot be chronological? Perhaps I could put together another test and see if it's all just reversed somehow? It seems to be consistently in the wrong direction.

**Comment by phryneas** [comment]
Hi there :)

Frankly, we never guarantee the order of operations you expect here anywhere in the documentation. It's just an assumption you made about how things should work.    
For Apollo Client, it is beneficial to start a new query or subscription before tearing down the last one - sometimes, things can be reused, and it's unnecessary to make another request to the server that way.

Even if Apollo Client would do this itself, this order of operation could be interrupted by custom links with asynchronous initialization or teardowns of different lengths or even by the final link that uses `graphql-ws` (which we don't control).

Given all this, there is no way we can guarantee that things will always happen in the order you expect.

On the other hand, the assumption you are making here has a lot of implications on your side: even if we would have this kind of sequence, you could never start a second subscription from the same client, as they would "interweave" in the same way as you are seeing right now.

If you *need* to solve this problem on the client, you could create a new websocket connection for every running subscription - but I'd try to avoid that.  
I'd recommend solving this on the server side by storing your subscriptions in relation to the subscription id in some way - that would end up being the most robust.

As @bignimbus already wrote, we'd be happy to assist you with that on the [Discord](https://discord.gg/graphos) or [community forum](https://community.apollographql.com/) .
