### ISSUE TITLE
[TS] Namespace clashes with dependencies

### ISSUE THREAD

**Issue by rricard** [apollographql/apollo-client#1061]
apollo-client rely on a lot of external typedefs. Those typdefs are exposed as dependencies. This often clashes in projects using apollo also relying on the same or similar typedefs (ex: graphql, chai, etc ...).

This issue was found by @schickling on their project (https://github.com/graphcool/homepage).

The suspected dependencies are here: https://github.com/apollostack/apollo-client/blob/master/package.json#L78:L88

My proposal is to move them into devDeps where they won't reappear in the user's project.

~Same thing should be done in react-apollo.~ Nope, react-apollo does things well apparently...

**Comment by schickling** [comment]
Thanks for opening this issue @rricard. We've spent many, many hours trying to find workarounds and fixes for this. Would be great if #1062 fixes this.

**Comment by rricard** [comment]
@schickling can't really test that without shipping it to NPM unfortunately. @stubailo did you find how we can do a kind of "preversion" in npm?

**Comment by schickling** [comment]
You can use github urls in `package.json`

**Comment by rricard** [comment]
@schickling not with apollo-client, at least not without changing the `.npmignore` and adding a `postinstall` script triggering the build (went there before when using a custom fork...) of the apollo client (and in this case we need to download all @types, effectively making all of this exercise pointless...). So, I will clearly need to publish it on npm. Maybe, I may get away with a kind of npm link but I have to admit I don't have much time letting me do that... I'll try when possible

**Comment by schickling** [comment]
Running `npm link` locally should be pretty easy. 🙂

**Comment by rricard** [comment]
@schickling will still not ensure it'll behave well after being pushed to registry, I'll try though...

**Comment by helfer** [comment]
@schickling @rricard is this still an issue? If yes, please reopen!
