### ISSUE TITLE
NextJS 13 + Apollo Client + Windows 10/11 - Network Error on v3.7.x

### ISSUE THREAD

**Issue by nategarrow** [apollographql/apollo-client#10634]
### Issue Description

When I run `yarn dev` on a NextJS + Contentful project using Apollo Client on my personal computer (Windows 11 Pro), I immediately get `[network error] - ApolloError: Cannot read properties of undefined (reading 'name')`. 

However, if I switch to my MacBook Pro, their is no error. Same results confirmed by coworkers on both PC and MacOS. 

## Config
| package | version |
| --------  | -------- |
| node      | 18.2.0  |
| next       | ^13.1.5 |
| @apollo/client | ^3.7.x |
| graphql  | ^16.6.0 |

### Workaround 
I can remove this network error if I install `@apollo/client@3.6.10` but hoping for an issue that doesn't require any downgrades.

### Related & non-GitHub issue
Closed issue [#9659](https://github.com/apollographql/apollo-client/issues/9659) - the 'solution' was to just downgrade `@apollo/client` and upgrade the `package.json` file??
[Strapi Forum](https://forum.strapi.io/t/nextjs-and-apolloclient-networkerror-apolloerror-with-wsl2/23064) - Nextjs and ApolloClient networkError / ApolloError with WSL2

### Link to Reproduction

https://forum.strapi.io/t/nextjs-and-apolloclient-networkerror-apolloerror-with-wsl2/23064

### Reproduction Steps

Personal setup is very similar to the reproduction link and related issues previously noted. Will try to get my own reproduction repo setup later.

1. install packages
2. run `yarn dev`
3. Immediately receive ApolloError (traced to networkError fired by `onError`)

![image](https://user-images.githubusercontent.com/35861254/223843396-bdc92007-0625-4e55-89ba-8769df1f99b2.png)

### Troubleshooting steps already taken
- to make sure it wasn't a browser/extension issue, I tried both Firefox Dev Ed. and Chrome, deactivating all browser extensions.
- Confirmed all secrets are valid by recreating and testing on a MacBook pro - everything worked.

**Comment by phryneas** [comment]
The reproduction you have linked is unfortunately not complete enough to run on its own.

Could you provide a full project with this error, so I can try reproducing it from my window machine? I suspect this is very specific to your setup, so it doesn't make sense to try and blindly reproduce it on my end.
