### ISSUE TITLE
Error handle

### ISSUE THREAD

**Issue by yarosdev** [apollographql/apollo-client#10666]
I am catching an error ApolloError it's ok. But how to get context? It's available only in http link? But many libraries such as axios etc. provide a response object in the error so I can get some extra headers like 'request-id' etc...

How to deal with it?

**Comment by phryneas** [comment]
If you are using `HttpLink`, that should be on `error.response` for thrown errors.

**Comment by yarosdev** [comment]
Yes, it is. But I wonder if it is possible to get it in .catch method of a promise when executing a mutation

**Comment by yarosdev** [comment]
Yes, I think it is a good way to do it

**Comment by phryneas** [comment]
Then I assume your question is answered and will close this issue :)

Have a great day!
