### ISSUE TITLE
support passing metadata at request time

### ISSUE THREAD

**Issue by roippi** [apollographql/apollo-client#1066]
**Use case:**

I am implementing persisted queries for my own custom backend.  To do this, in production I generate a build artifact that goes along with the query.  Then I want to write a middleware to modify the request on the way out to simply replace the serialized query with the build artifact.  On the server, the artifact gets transformed back into the query.

_The problem_: there is no (real) way for me to send this artifact through the request for my middleware to consume.  The only way I could get this to work is to "smuggle" it through `variables` as a magic field that gets extracted out by my `NetworkInterface`.

This would be much nicer if I could just pass that build artifact through the request to have the middleware swap it out.

**Could this be a plugin?**

Maybe.  Middleware comes very close to doing everything I need, I just don't have a good API to send it the extra bit of data it needs.

**Is there a workaround?**

Yes, see above about smuggling it through `variables`.  However this is super hacky, I would prefer to do it correctly.

Note: [the interface for Request](https://github.com/apollostack/apollo-client/blob/master/src/transport/networkInterface.ts#L33) indicates that one can pass in additional key/value pairs, but this data unfortunately does not survive to the `NetworkInterface`/middleware layer.

**Comment by helfer** [comment]
@roippi I think the right thing to do here would be to make sure that those additional keys don't get stripped out any more. There's probably a line somewhere in the middleware stack or network interface that currently does this. If you find it, please submit a PR!

**Comment by roippi** [comment]
Yep, can do.

**Comment by roippi** [comment]
So as brought up in the (closed) PR the issue is here: https://github.com/apollostack/apollo-client/blob/master/src/core/QueryManager.ts#L937

These keys get stripped out before the middleware stack.  My fix unfortunately was too permissive and simply passed through everything on `options`.  While technically the interface of `Request` permits that, it has some unfortunate side effects like also sending `operationName` over the wire.

The idea of using `extensions` was brought up but I'm not 100% sure that fits - the spec defines that on the response, not the request.  https://facebook.github.io/graphql/#sec-Execution.  And to clarify, I'm not trying to send any extra params over the wire, I'm just trying to get metadata to survive to the middleware layer.

`QueryOptions` even has a `metadata` field that I didn't notice before.  This again would be fine for me to use but it gets stripped out in `QueryManager.fetchRequest` at the aforementioned point.  https://github.com/apollostack/apollo-client/blob/master/src/core/watchQueryOptions.ts#L73

Looking at how things are architected now, this is altogether not an easy ask, since I'm asking for `metadata` to live through to the `networkInterface` implementation.  I could write code to strip out `metadata` in `HTTPFetchNetworkInterface.prototype.fetchFromRemoteEndpoint` but that's just one network interface implementation... user-provided ones will not be expecting this extra metadata field.

**Comment by wizardzloy** [comment]
@roippi I believe `metadata` is the ideal place for "custom" information to be stored. I would like to utilize it for marking certain queries as the ones that require "global" loading spinner. So that I could use that info in a middleware to dispatch the action that will show the spinner. 

Do you see any harm in passing `metadata` all the way to the networkInterface?

**Comment by helfer** [comment]
I think we could consider passing metadata to the network interface, but we'd have to make sure to strip it out in the networkInterface then. I'd be open to a PR if someone wants to try.

**Comment by roippi** [comment]
The problem is that `NetworkInterface` is a public-facing API; [the docs](http://dev.apollodata.com/core/network.html) freely recommend subbing in your own.  For those that do, this will be a breaking change since they generally won't strip it out.

One way to make this reasonably backwards-compatible is to extract the metadata from the `request` and shuffle it into some parallel param that gets passed down along with it.  Third-party NetworkInterfaces will just discard it gracefully then.

**Comment by wizardzloy** [comment]
@roippi @helfer  are we talking about adding `metadata` field to [GraphQLRequest](http://dev.apollodata.com/core/network.html#GraphQLRequest) interface? If so, I don't see any breaking changes here, we are adding new stuff, not removing it, I might not see the whole picture though

@roippi Could you please give an example of a situation when this becomes a problem?

**Comment by tnrich** [comment]
@roippi , can you weigh in on whether what @wizardzloy is saying true? That adding metadata wouldn't be a breaking change? I don't see why passing a new field (metadata) to custom network interfaces would break them? 

I think for my use case, passing info about how to batch transactions as described in #1656, a metadata field would be a very nice way to solve it.

Thanks!
