### ISSUE TITLE
Apollo Client doesn't stop retries for 400 errors even with RetryLink max=1

### ISSUE THREAD

**Issue by javierxbrenes1** [apollographql/apollo-client#10674]
Hey I am working on a React App I have my setting for ApolloClient this way
```
const retryLink = new RetryLink({
  attempts: {
    max: 1,
  },
});

const httpLink = new HttpLink({
  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
  uri: import.meta.env.VITE_GRAPHQL_URL,
});

const client = new ApolloClient({
  link: ApolloLink.from([retryLink, httpLink]),
  cache: new InMemoryCache(),
});
```

I am using Apollo Server as well for BE, 
Got a query that fails with a 400, the problem is that apollo doesn't stop retries, it basically gets into a loop

Am I missing anything? 
repo and code can be found here: https://github.com/javierxbrenes1/be-strong-app

* Apollo Discord server: https://discord.gg/graphos
* Apollo GraphQL community forums: https://community.apollographql.com
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests

**Comment by jerelmiller** [comment]
Hey @javierxbrenes1 👋 

Would you mind adding the `@apollo/client` version you're using? Thanks!

**Comment by javier-brenes-zen** [comment]
@jerelmiller I am using latest version https://github.com/javierxbrenes1/be-strong-app/blob/master/package.json#L26

**Comment by javierxbrenes1** [comment]
@jerelmiller I am using latest version https://github.com/javierxbrenes1/be-strong-app/blob/master/package.json#L26

**Comment by jerelmiller** [comment]
Oh right, I should have checked there first 🤣. Thanks!

**Comment by javierxbrenes1** [comment]
@jerelmiller sorry I made you to waste time on this, there is nothing wrong with the library, It was my code 
I was doing this 
```
const { loading, data, error } = useQuery<QueryType>(HOME_COUNTERS, {
    variables: {
      year: getCurrentYear(),
      today: new Date(),
    }
});
```

as you can see I am setting a `new Date()` as a variable, this trigger a rerender since value changes everytime, I will close this.

Thanks for the help

**Comment by jerelmiller** [comment]
@javierxbrenes1 glad you hear you figured out the issue! 🎉 🎉
