### ISSUE TITLE
sqlite on demand offline cache support

### ISSUE THREAD

**Issue by andresribeiro** [apollographql/apollo-client#10691]
With apollo3-cache-persist all data is loaded and read at once. This has a cost in performance as more data needs to be saved offline. Both apollo ios and apollo kotlin have sqlite caching support, where data is loaded on demand, without consuming memory or adding a delay in startup time because you have to wait for the data to load completely. React Native has extremely fast sqlite databases, which could be used to implement this, optimizing the overall performance

Related: #7951

**Comment by jerelmiller** [comment]
Hey @andresribeiro 👋 

It looks like you're wanting some new functionality added to `apollo3-cache-persist` so I'd recommend opening this issue [in that repo](https://github.com/apollographql/apollo-cache-persist/issues/new). That project is actually a community-led project. Apollo as an organization does not maintain that project, so we can't guarantee much support there. 

I'm going to go ahead and close this issue, but please let me know if I've made a mistake in understand your ask here and I'd be happy to open this issue again. Thanks!
