### ISSUE TITLE
Loading is false while fetching data

### ISSUE THREAD

**Issue by dylanwulf** [apollographql/apollo-client#10737]
### Issue Description

I have my apollo client set up with `cache-and-network` as the default fetch policy. When my queries mount, they fetch regardless of whether there is data in the cache or not. The `loading` status should reflect that, but I am seeing `loading: false` while fetching if there is data in the cache. The fetch itself still works fine, only the loading status is broken.

### Link to Reproduction

https://codesandbox.io/s/loading-false-while-fetching-d5tgp2?file=/src/index.jsx

### Reproduction Steps

See reproduction link above

**Comment by jerelmiller** [comment]
Hey @dylanwulf 👋 

We are having a bit of an internal debate on this one to make sure we all understand the desired behavior here. It looks like our docs are a bit ambiguous about the loading state unfortunately so we don't have a "source of truth" if you will. FWIW I tend to lean toward your understanding of the loading state as the correct one. I'd like to ensure this is actually the intended and understand behavior though before we commit one way or the other.

Thanks for raising the issue!

**Comment by dylanwulf** [comment]
@jerelmiller Thanks for getting back to me! My goal is to show the loading state to the user as a kind of warning, like "the data on your screen may or may not change shortly". If the loading state returned from apollo-client is false, then I have no way of knowing whether the data has a possibility of changing soon. If the loading state returned from apollo-client is true, then I get to choose whether that loading state gets shown to the user. So I really would prefer to have the loading state be true when fetching, even if there is data returned from the cache.

**Comment by jerelmiller** [comment]
@dylanwulf that reasoning is sound and I agree. Its a common pattern to have some kind of UI indication on screen, even with cached data, to indicate that some network activity is in-progress. The same reasoning can be applied to a refetch.

I'm mostly doing a sanity check with the team to make sure I'm not missing something obvious in case, for whatever reason, this was a deliberate choice.

**Comment by jerelmiller** [comment]
@dylanwulf chatted a bit more with @benjamn about this and we both concur this is considered buggy behavior. I've updated the label on this issue to reflect as such.

**Comment by namoscato** [comment]
@jerelmiller, do you have an estimate on when this will be fixed? This behavior seemed to regress from our perspective somewhere in between v3.4.16 to v3.7.11.

**Comment by jerelmiller** [comment]
@namoscato I don't have a timeline on this right now. We'll likely come back to this after 3.8.0 is released (within the next few weeks). We're pretty heads down working to get that release done. You're welcome to submit a PR if you're interested in taking a look at this and we'd be happy to review!

**Comment by dylanwulf** [comment]
Hello! Congrats on v3.8 being released 🎉! I'm just wondering if there are any plans to look at this bug now that the release is out? It's not critical but this is definitely affecting our users. Thanks!

**Comment by jerelmiller** [comment]
Thanks @dylanwulf!!

I've been doing my best to reproduce this in our tests given your reproduction, but I'm having a heck of a hard time. Turns out if I upgrade your reproduction to the latest version, the bug goes away. Seems we might have inadvertently fixed it with the latest release.

Check it out! https://codesandbox.io/s/loading-false-while-fetching-forked-fjtm5l?file=/src/index.jsx

Can you verify that the latest version fixes what you're seeing on your end? If so, I'll go ahead and close this issue as completed.

**Comment by dylanwulf** [comment]
@jerelmiller Yes, I think you're right! I don't see the problem anymore in 3.8.1. Hopefully we can upgrade to that version soon. Thanks!
