### ISSUE TITLE
RefetchQueries does not work when a mutation is triggered inside a popstate event

### ISSUE THREAD

**Issue by andreicutmadalina** [apollographql/apollo-client#10753]
Hello, 

I'm running into this issue: whenever the URL changes, the popstate event is fired and a mutation is triggered. 
The problem is that the refetchQueries are not triggered. 
Does anyone have any idea why is this happening?

**Comment by alessbell** [comment]
Hi @andreicutmadalina 👋 

Without a reproduction of the issue, there's not much we can do to help. I'm going to close this out for now, but please feel free to add some more information here and I'd be more than happy to re-open it. Alternately, feel free to check out our [Discord](https://discord.gg/graphos) where you can ask questions about your implementation to the community. Cheers!
