### ISSUE TITLE
Custom ApolloLink Documentation Bug

### ISSUE THREAD

**Issue by harshagarwal-mono** [apollographql/apollo-client#10756]
### Issue Description

```
import { ApolloLink } from '@apollo/client';

const reportErrors = (errorCallback) => new ApolloLink((operation, forward) => {
  const observable = forward(operation);
  // errors will be sent to the errorCallback
  observable.subscribe({ error: errorCallback })
  return observable;
});
```

Using this code i am trying to create a error logger link. But this does not work. But when i comment the subscribe line it started working.   In order to resolve this issue i create a new observable and returned that and that starts working. So is this the recommended way to create a new observable and then return or there is any kind of bug due to which we are not able to do so.

### Link to Reproduction

N/A

### Reproduction Steps

```
{
  "name": "@mtf/webui",
  "version": "0.0.3",
  "private": true,
  "author": "Monotype",
  "license": "",
  "scripts": {
    "_clean": "node tools/cleanHelper.ts",
    "build": "nuxt build",
    "start": "nuxt dev --dotenv .env.staging",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "_checkLicenses": "licensee --production --errors-only"
  },
  "devDependencies": {
    "@nuxt/devtools": "^0.2.3",
    "@nuxtjs/eslint-module": "^4.0.2",
    "@nuxtjs/i18n": "^8.0.0-beta.10",
    "@nuxtjs/web-vitals": "^0.2.4",
    "@rollup/plugin-graphql": "^2.0.3",
    "@types/ramda": "^0.28.23",
    "@vite-pwa/nuxt": "^0.0.6",
    "@vueuse/core": "^9.13.0",
    "@vueuse/nuxt": "^9.13.0",
    "nuxt": "^3.3.1",
    "nuxt-vitest": "^0.6.9"
  },
  "dependencies": {
    "@apollo/client": "^3.7.11",
    "@mtf/components-vue-generated": "*",
    "@mtf/locales": "*",
    "@mtf/mosaic-core-utils": "*",
    "@vue/apollo-composable": "^4.0.0-beta.4",
    "@vue/apollo-option": "^4.0.0-beta.4",
    "graphql": "^16.6.0",
    "graphql-tag": "^2.12.6",
    "ramda": "^0.29.0"
  }
}
```

**Comment by jerelmiller** [comment]
Hey @harshagarwal-mono 👋 

Would you be able to create a small runnable example? You can fork our [CodeSandbox](https://codesandbox.io/s/github/apollographql/react-apollo-error-template) template as a starting point.

---

I'd love to know a bit more about what you're looking for. You mentioned it "doesn't work". Could you describe in more detail what that means and the outcomes you're looking for? Having a runnable example would help us determine what's going on and what the intended behavior is so we can either give you a recommendation or look at this a bit more in-depth. Thanks!
