### ISSUE TITLE
Title of the codeblocks is mismatched with the language specified in the tab.

### ISSUE THREAD

**Issue by jitiendran** [apollographql/apollo-client#10769]
In [Query Docs](https://www.apollographql.com/docs/react/data/queries) some code blocks have mismatched title.

Title of the code block should match with the language specified

**Actual Behavior:**
 
![image](https://user-images.githubusercontent.com/61231497/219058981-83e36bc0-b9f6-48ed-830e-cbbad515b147.png)

Here the language is `TypeScript` but the title says `index.js`.

**Expected Behaviour**

![image](https://user-images.githubusercontent.com/61231497/219059382-755aa9da-651c-45c9-bb80-eea1a8b9cb7f.png)

Here If you see the title `index.ts` matches  with language specified `TypeScript`.

**Comment by jerelmiller** [comment]
Hey @jitiendran 👋 

Thanks for catching this! Looks like this was fixed in #11007 so I'm going to go and and mark this as completed 🙂.
