### ISSUE TITLE
Auto strip `__typename` does not correctly handle JSON scalars

### ISSUE THREAD

**Issue by jerelmiller** [apollographql/apollo-client#10767]
### Issue Description

#10724 introduced the ability to automatically strip `__typename` fields from `variables` before a request is made to a server. While this works well for the majority of cases, the change is a bit over-eager as it will also strip `__typename` from JSON-related scalars. Since a JSON scalar allows you to pass any arbitrary data, we should be a good citizen and avoid stripping `__typename` in these cases. NOTE: JSON scalars do not have to be named `JSON`. A schema can defined any arbitrarily named scalar type that represents a JSON blob (though `JSON` is the most common name for this type of scalar).

We'll need a mechanism that allows users to opt-in/opt-out of this behavior for these scalars.

There are two approaches we can consider:

1. Opt-out behavior

In this approach, stripping the `__typename` would be considered the default behavior. Users would need to opt-out of this behavior by listing the types where `__typename` should be left alone.

2. Opt-in behavior

On the flipside, we would consider this feature as _opt-in_ which means stripping the `__typename` does not happen automatically. Users would need to opt-in to this behavior by listing the types where the `__typename` should be removed.

There is a good case to be made for either approach and I think both are valid. 

---

There is a scenario that adds a bit of a wrinkle. If you declare an `input` type where one of its fields is a JSON scalar, detecting the boundary at which `__typename` could be left alone cannot solely be done by inspecting the query document. For example, lets say I have this query:

```graphql
mutation UpdateUser($user: UserInput!) {
  updateUser(user: $user) {
    id
  }
}
```

And `UserInput` is defined as:

```graphql
input UserInput {
  id: ID!
  config: JSON
}
```

Here we'd want to strip any `__typename` on the top-level `user` variable, but leave anything inside `config` alone.

We'll need to provide a mechanism for users to specify field paths as well as types to ensure this is handled correctly for all scenarios.

### Link to Reproduction

n/a

**Comment by jerelmiller** [comment]
After some internal discussion, I'm convinced we will not be able to ship this as an opt-out solution because we break backwards compatibility for anyone that relies upon `__typename` as part of a JSON scalar. `__typename` _is_ allowed when used as part of a JSON scalar and people may be using this solution as a workaround for the fact that GraphQL doesn't yet support [input unions](https://github.com/graphql/graphql-wg/blob/main/rfcs/InputUnion.md).

Additionally, there are a few downsides to the approach in https://github.com/apollographql/apollo-client/pull/10724.

1. The change is limited to `HttpLink`, `BatchHttpLink` and `GraphQLWsLink`. If anyone is using a custom terminating link, or the older `WebSocketLink`, this functionality is missed.
2. This functionality needs to be duplicated in every terminating link that should include this functionality. This can lead to increased bundle size.
3. Users that don't need this functionality, either because they strip typenames themselves, or because they don't use data that includes a `__typename` in their variables, suffer from a larger bundle size since the underlying code cannot be tree-shaken away.

---

Instead, the plan is to create a newly exported `ApolloLink` that will provide this functionality. For the sake of this discussion, I'll call it a `StripTypenameLink` (final name TBD).

Shipping a custom link has several advantages that counter the downsides above:

1. We are no longer limited to our built-in terminating links to provide this functionality. You can simply drop a `StripTypenameLink` in your link chain and this will propagate to any terminating link in your app
2. We reduce duplication in our built-in terminating links since this functionality is included in a single place
3. We can reduce bundle size for those that don't need this functionality, since this link can be tree-shaken away if not used.
4. We can include any needed configuration for this behavior in the link itself. Configuring JSON scalars that should allow `__typename` through can be done alongside the link that is stripping the typename.

### Design

We want to allow for simplicity as much as possible. This link should be easy to drop-in with minimal configuration as possible to reduce friction.

#### Requirements

* Make it easy to opt-in to stripping `__typename` from everything. Gauging by the number of user-provided solutions in https://github.com/apollographql/apollo-feature-requests/issues/6 that don't handle JSON scalars in any meaningful name, this feels like the most common use case.
* Allow a user to define types that should leave `__typename` in-tact. These can be detected from the variable definitions in the query document NOTE: We can't assume all JSON scalars are named `JSON`, since a schema could define a more semantically meaningful name (e.g. `Config`), hence why we need this to be configurable.
* Allow a user to define a property path that should leave `__typename` in-tact. If a JSON scalar is a key in a deeply nested input object, simply trying to detect the input type is not enough (see the description in this issue for an example of this problem).

I propose the following behaviors:

1. Optimize for the common case, which is to strip `__typename` from everything. JSON scalars, while useful, are typically seen as an anti-pattern since they discourage strong types. 

```ts
// final name/import TBD
import { StripTypenameLink } from '@apollo/client/link/stripTypename';

// pass nothing to strip everything by default
const stripTypenameLink = new StripTypenameLink();
```

2. Allow users to _exclude_ types that should not adhere to this behavior, instead of forcing the user to include types that should adhere to this behavior. Explicit types should be the norm and each of these do not allow keys with `__` (double underscore). This should allow for a more minimal configuration.

```ts
import { StripTypenameLink } from '@apollo/link/stripTypename';

const link = new StripTypenameLink({
  // simple types
  exclude: ['JSON', 'Config', 'SomeOtherJSONScalarType'],

  exclude: [
    // Keep `__typename` for the `config` property of a `UserInput` type, but strip all others
    ['UserInput', ['config']],

    // Keep `__typename` on multiple paths inside a single type
    ['UserInput', [['config'], ['anotherConfig']],

    // Keep __typename for a deeply nested JSON type
    ['DashboardInput', ['widgets', 'config']]
  ],
});
```

Suggestions welcome on the API!

**Comment by phryneas** [comment]
What about
```js
new StripTypenameLink({
  exclude: {
    UserInput: { config: true },
    DashboardInput: {
      deeply: { nested: { field: true }},
      another: { field: true }
    }
  }
});
```
?

Or, if we generally think about a Link that can be used to transform outgoing data:
```js
new TransformDataLink([
  strip('UserInput', 'config'),
  strip('DashboardInput', 'deeply', 'nested', 'field'),
  strip('DashboardInput', 'another', 'field'),
])
```

If users had a lot of fields, they could abstract over `strip` to make that work best for them.

**Comment by jerelmiller** [comment]
@phryneas those are interesting ideas!

> ```ts
> new StripTypenameLink({
>   exclude: {
>     UserInput: { config: true },
>     DashboardInput: {
>       deeply: { nested: { field: true }},
>       another: { field: true }
>     }
>   }
> });
> ```

I love the readability of this example. It's much easier to parse than something like this: `['JSON', ['UserInput', ['config']], ['UserInput', ['anotherConfig']]]`

The only thing I don't love about this is the fact that `true` is the only value that makes sense here, so at a glance, people might assume there is an equivalent `false`.

Perhaps we could just make the leaf nodes an array in that case?

```ts
new StripTypenameLink({
  exclude: {
    UserInput: ['config'],
    DashboardInput: {
      deeply: { nested: ['field'] },
      another: ['field']
    }
  }
});
```

This gets rid of the `true`, but could get weird in other cases, where yours would handle this nicely:

```ts
new StripTypenameLink({
  exclude: {
    DashboardInput: {
      // How I envision a leaf field + another nested field at the same level
      deeply: ['another', { nested: ['field'] }],
    }
  }
});
```

---

> ```ts
> new TransformDataLink([
>   keepTypename('UserInput', 'config'),
>   keepTypename('DashboardInput', 'deeply', 'nested', 'field'),
>   keepTypename('DashboardInput', 'another', 'field'),
>   stripTypename(),
> ])
> ```

This is an interesting idea, though in some ways it feels similar to `ApolloLink` already: `ApolloLink.from([link1, link2])`. In this case, what "data" would you see this operating on? Would this be strictly outgoing data (query, variables, context, etc?)? Would you limit this to just a subset of the `operation`?

**Comment by phryneas** [comment]
Huh, that's an interesting edge case.

My original idea would also not be able to handle this I believe 🤔

```js
new StripTypenameLink({
  exclude: {
    UserInput: { config: true },
    DashboardInput: {
      // how to keep `__typename` here?
      deeply: { nested: { field: true } },
      another: { field: true },
    },
  },
});
```

Another version that could do this, and is a bit clearer, although it is more code, could look like this:

```js
import { StripTypenameLink, keepTypename } from "...";

new StripTypenameLink({
  exclude: {
    UserInput: {
      config: {
        [keepTypename]: true,
      },
    },
    DashboardInput: {
      // this works now
      [keepTypename]: true,
      deeply: {
        nested: {
          field: {
            [keepTypename]: true,
          },
        },
      },
      another: {
        field: {
          [keepTypename]: true,
        },
      },
    },
  },
});
```

And then we could get it shorter again, by mixing both approaches and allowing a shortnotation in the form of `fieldName: keepTypename`:

```js
import { StripTypenameLink, keepTypename } from "...";

new StripTypenameLink({
  exclude: {
    // keepTypename makes more sense than `true` here
    UserInput: { config: keepTypename },
    DashboardInput: {
      // now this works
      [keepTypename]: true,
      deeply: { nested: { field: keepTypename } },
      another: { field: keepTypename },
    },
  },
});
```


> Would you limit this to just a subset of the operation?

Honestly, I have no idea - I just had the thought that we could explore into that direction and didn't want to immediately dismiss it, so I jotted it down. Your interpretations here are as good as mine ^^


I have to admit that generally, I'm not a big fan of the "nested array" variants - while they are shorter, they are very hard to explain, and they might be very easy to get wrong.

**Comment by jerelmiller** [comment]
> I have to admit that generally, I'm not a big fan of the "nested array" variants - while they are shorter, they are very hard to explain, and they might be very easy to get wrong.

I would agree. Its fine for small things, but can get very difficult to read the more nested arrays you have. I do like the idea of an object-like syntax for readability, we just have to settle on the way to denote the leaves of the field paths.

**Comment by jerelmiller** [comment]
Another potential option:

```
new StripathTypenameLink({
  excludeTypes: ['JSON'],
  exclude: {
    UserInput: `
      config {
        widgets { config }
      }
    `
});
```

**Comment by jerelmiller** [comment]
Completed in #10853
