### ISSUE TITLE
useQuery.networkStatus doesn't update status to (4). The refetch happens from mutation with refetchQueries

### ISSUE THREAD

**Issue by CavidM** [apollographql/apollo-client#10827]
here is mutation trigs refetching 
```ts
const [removeFromCart, { data, loading, error }] = useMutation(MutationRemoveFromCart, {
    variables: { deviceId: parseInt(device as string) },
    refetchQueries: [{ query: QUERY_GET_DEVICE, variables: { id: device } }]
  })
```

here networkStatus is always 7
```ts
const { data, loading, networkStatus, error } = useQuery<DeviceGetType>(QUERY_GET_DEVICE, {
    variables: { id: device }
  });
```
  
  
  Reproduction steps:
create any query. and send your first request.
on some another place run some mutation and pass refetchQueries to the query you just run.
you expect to see networkStatus is 4 during refetching but it is 7 and only after the query is done

**Comment by bignimbus** [comment]
Hi @CavidM 👋🏻 thanks for opening this issue!  I'd be happy to take a look at this but I'm not certain how to help with the information given.  We have a [CodeSandbox template](https://codesandbox.io/s/github/apollographql/react-apollo-error-template) that you could fork to demonstrate the issue in a way that matches how your Apollo Client instance is configured.  Any more detail you could provide would be helpful 🙏🏻

**Comment by CavidM** [comment]
Hi. Sure, please see my code under comment (javid's code).
Here is my changes: https://codesandbox.io/s/blissful-snowflake-7yg54l?file=/src/index.jsx:895-1017
`notifyOnNetworkStatusChange: true` added to ALL_PEOPLE query
`refetchQueries: [{ query: ALL_PEOPLE }]` added to ADD_PERSON mutation

**Comment by bignimbus** [comment]
A few other findings I'm sharing for posterity:

1. This PR changed the docs to recommend the `{ query: MY_QUERY }` syntax: https://github.com/apollographql/apollo-client/pull/9708
2. As demonstrated in [this fork](https://codesandbox.io/s/nervous-sanderson-stfggq), you can also work around this issue by setting `refetchQueries: [ALL_PEOPLE]`

This code snippet was of interest:

https://github.com/apollographql/apollo-client/blob/86ca77cff6376e4ce967860267734f923bd9f562/src/core/QueryManager.ts#L806-L808

Based on the fact that an object with a `query` property is named `legacy` I'm strongly inclined to say that our docs should be updated.  I'll get some clarity here and post another update when I can!

**Comment by bignimbus** [comment]
And one more finding:

https://github.com/apollographql/apollo-client/pull/7813 introduced this `legacyQueryOptions` concept.  This inline comment explains the intent further:

https://github.com/apollographql/apollo-client/blob/86ca77cff6376e4ce967860267734f923bd9f562/src/core/QueryManager.ts#L845-L847

Given this context, it makes sense why you're seeing `networkStatus` go from `1` (loading) to `7` (ready) without stopping at `4` (refetch).  So I'll double down on my above guidance and recommend filling your `refetchQuery` arrays with query document nodes or query operation names instead of the syntax that's in our docs.

**Comment by CavidM** [comment]
Thank you so much @bignimbus. 
It works and the solution is more enough. I agree with you regarding the documentation.
