### ISSUE TITLE
[3.8 alpha] Use within Codesandbox is broken

### ISSUE THREAD

**Issue by alessbell** [apollographql/apollo-client#10856]
### Issue Description

When building a demo with a snapshot release for a branch off of `release-3.8`, I came across this error:

![CleanShot 2023-05-11 at 13 58 03](https://github.com/apollographql/apollo-client/assets/5139846/8885afb3-7cb3-45ba-b9b8-ac17096dc00c)

![CleanShot 2023-05-11 at 15 29 51](https://github.com/apollographql/apollo-client/assets/5139846/9ada8064-599f-4e90-8683-0f1bfd10ea1d)

It seems to be caused by a breaking change to how optimism is generating sourcemaps in the version we bumped it to in `0.17.0`: locally it warns in the console, but Codesandbox throws an error. I'll look at the upstream fix, but also created an issue here so we don't lose track of this one, since we'll need to either bump the version once that PR lands or roll back before releasing.

### Link to Reproduction

https://codesandbox.io/s/beautiful-lucy-z82hul?file=/package.json

**Comment by jerelmiller** [comment]
#10886 was also reported. I'm going to leave that one open for now since its affecting v3.7.x

**Comment by alessbell** [comment]
Replied over there, too, but these look like two different issues.

**Comment by jerelmiller** [comment]
Ah thank you. I saw some of the same modules in the stack trace and thought they were related. Appreciate the assist!

**Comment by alessbell** [comment]
Was closed by https://github.com/apollographql/apollo-client/pull/10888.
