### ISSUE TITLE
TypeError: _client.HttpLink is not a constructor in jest test

### ISSUE THREAD

**Issue by jyoVerma15** [apollographql/apollo-client#10850]
TypeError: _client.HttpLink is not a constructor in jest:: 

I have same issue with HttpLink `HttpLink is not a constructor`, i tried different versions... if i comment this, next say that 

`TypeError: _apollo_client__WEBPACK_IMPORTED_MODULE_0__.gql is not a function
  1 | import { gql } from '@apollo/client';`

graphql 16.3.0

Try versions:
apollo/client 3.5.9
apollo/client 3.5.7
apollo/client 3.4.13
apollo/client 3.4.0

_Originally posted by @Resmedia in https://github.com/apollographql/apollo-client/issues/9230#issuecomment-1041552475_
            [Resmedia](https://github.com/Resmedia) , were you able to resolve this issue? because I am getting the same and i have tried different versions but still getting the same issue

**Comment by bignimbus** [comment]
Hi @jyoVerma15 👋🏻 is this only an issue in Jest or are you seeing this in your application as well?

**Comment by jyoVerma15** [comment]
> Hi @jyoVerma15 👋🏻 is this only an issue in Jest or are you seeing this in your application as well?

I am just seeing this error in jest while running mocking apollo client.

**Comment by jerelmiller** [comment]
Hey @jyoVerma15 👋 

Would you be able to create a runnable reproduction? I can't say I've seen this failure before and we've had plenty of people run Apollo inside of tests. My guess is there is something with your setup that is causing you some issues.

If you could help us out and share some more details on your setup and/or get us a reproduction of the issue, that would go a long ways to helping us figure out whats going on. Thanks!

**Comment by jyoVerma15** [comment]
Hey, @jerelmiller ,

I am trying to mock @apollo/client in my jest file with LWC component.But not able to mock it properly i guess.

here is the code below: 
```
import { ApolloClient, makeVar, InMemoryCache } from '@apollo/client';
jest.mock('@apollo/client', () => jest.fn(() => null));
const mockClient = new ApolloClient({
    link: new HttpLink({
        uri: appConfig['DEV'].EVENTS_API_URL,
        fetch: fetch,
    }),
    cache: new InMemoryCache({
        addTypename: false,
    }),
});
ApolloClient.setClient(new Response(JSON.stringify(mockClient)));
```
After mocking like above getting below error :

<img width="1290" alt="Screenshot 2023-05-12 at 11 41 23 AM" src="https://github.com/apollographql/apollo-client/assets/109670554/4f18d56a-cf88-4b4a-a923-63f122c54262">

@jerelmiller can you please tell me if i am mocking the apollo/client correctly or not.

**Comment by phryneas** [comment]
It seems to me that you are replacing the whole `@apollo/client` import with `null` here, which is why `ApolloClient` there is not a constructor any more.

Might I ask why you are mocking any of those in the first place? What do you expect to get out of that?
