### ISSUE TITLE
"Failed to parse source map from...": from the dependency `@wry`

### ISSUE THREAD

**Issue by xli12** [apollographql/apollo-client#10886]
### Expected behaviour

No warning should be given when starting my React application with Apollo client as a dependency.

The application works normally though.

### Actual behaviour

When starting my application, it gives this warning from webpack:

```
WARNING in ./node_modules/@wry/context/lib/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/blablaProject/node_modules/@wry/context/src/index.ts' file: Error: ENOENT: no such file or directory, open '/blablaProject/node_modules/@wry/context/src/index.ts'

WARNING in ./node_modules/@wry/context/lib/slot.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/blablaProject/node_modules/@wry/context/src/slot.ts' file: Error: ENOENT: no such file or directory, open '/blablaProject/node_modules/@wry/context/src/slot.ts'

WARNING in ./node_modules/@wry/equality/lib/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/blablaProject/node_modules/@wry/equality/src/index.ts' file: Error: ENOENT: no such file or directory, open '/blablaProject/node_modules/@wry/equality/src/index.ts'

webpack compiled with 3 warnings
```

### Version
- `@apollo/client 3.7.14`

### How to reproduce
1. Create an application using create-react-app. In my example, `blablaProject` was created.
2. Install `@apollo/client`, version 3.7.14
3. Start your application. You'll see the warnings.

**Comment by jerelmiller** [comment]
Hey @xli12 👋 

We are aware of this issue and will have a fix for it soon. We are tracking this in #10856. Thanks for the heads up!

**Comment by alessbell** [comment]
This is an issue with `@wry` packages, not `optimism` as https://github.com/apollographql/apollo-client/issues/10856 describes, but luckily it also looks like this issue was reported and fixed over on the wryware repo 🎉  https://github.com/benjamn/wryware/issues/492

Try removing your lockfile and doing a fresh `npm i` to get the next patch version(s) installed/written into your lockfile which should contain the fix (e.g. `@wry/context 0.7.3`) and let me know if that solves your issue :)

**Comment by xli12** [comment]
Hi @jerelmiller and @alessbell ,

Thank you very much for helping out! After introducing the fix suggested https://github.com/benjamn/wryware/issues/492 , I confirm that the warning disappeared 🥳

The fix: We use `yarn` as the package manager in our project. In `package.json` we added the following part to pin the versions which contain the fix for `@wry`:

```
"resolutions": {
    "@wry/context": "^0.7.3",
    "@wry/equality": "^0.5.6"
  },
```

**Comment by jerelmiller** [comment]
Glad to hear that did it 🎉 🎉!! I'll go ahead and close this issue. Feel free to ping us if you need anything else. Thanks!
