### ISSUE TITLE
In version 3.7.11+ useQuery returns wrong data for given variables if correct data are in cache

### ISSUE THREAD

**Issue by vitexikora** [apollographql/apollo-client#10894]
### Issue Description

This bug appears in apollo-client versions 3.7.11-3.7.14. Versions 3.6.9 up to 3.7.10 are not affected.
I had to currently resolve it by downgrading to 3.7.10.

Situation:

```js
const [date, setDate] = useState(moment().format('YYYY-MM-DD'))

const { data } = useQuery(MenuListDocument, { variables: { filter: {date} } })

return (
  <>
    <DateSelect date={date} setDate={setDate} />
    <Offer data={data} />
  </>
)
```

Problem:
- Current day is loaded to cache and displayed. OK.
- Go quickly forward several (say 3) days, wait for this D+3 day to load. OK.
- Go quickly back to D+0, cached data are correctly immediately displayed. OK.
- Request for D+1 day comes back from GQL API. **Apollo client returns D+1 data while I am still on D+0 !**

Other notes:
 - using fetch policy of **"cache-and-network"** seems to resolve this, however in that case, I want to use the policy of **"cache-first"**.
 - in release notes of 3.7.11 you say "Kicking off multiple requests in parallel with the execution function will now ensure each returned promise is resolved with the data from its request". For me, the opposite happenned. It may be related?

### Link to Reproduction

I have zero time now, I may provide later, if you fail to find it.

**Comment by dylanwulf** [comment]
Hello! I'm not sure if this will help, but this post sounded similar so I thought I would share here in case it's helpful: https://community.apollographql.com/t/results-for-different-keyargs-value-queries-are-getting-passed-to-mixed-up-in-merge-type-policy/6249
