### ISSUE TITLE
NextSSRInMemoryCache empty 

### ISSUE THREAD

**Issue by walhallyus** [apollographql/apollo-client#10896]
### Issue Description

I think there is a bug in NextSSRInMemoryCache strategy, I have played with apollo client server on a next application and cant make the cache to transfer from server to client. When NextSSRInMemoryCache is created the data is empty on it.
I have also searched on window object on apollo objects and the data is empty object {} until I do the first client request
Is there a way to debug the cache transfer? (a console.log on server side and the in client to compare)

### Link to Reproduction

@@

**Comment by walhallyus** [comment]
I'm doing a graphql query, I'm able to send the results to the client with props but I want to transfer the cache so when the same query happens on the client to use cache-first

**Comment by walhallyus** [comment]
I do it like this: 
await getClient().query({ query });

I have this integration on next 13
https://www.apollographql.com/blog/apollo-client/next-js/how-to-use-apollo-client-with-next-js-13/

**Comment by phryneas** [comment]
That was the way to do it before this library was released (and even then, only in React Server Components, which are completely independent of SSR and `NextSSRInMemoryCache`).

Please set up the whole project as described in the [README](https://github.com/apollographql/apollo-client-nextjs#readme) of this projects and our [examples](https://github.com/apollographql/apollo-client-nextjs/tree/main/examples).

**Comment by walhallyus** [comment]
Yes, my setup it's exactly the same

**Comment by phryneas** [comment]
But it seems that you are not using Apollo Client in combination with Next.js as it is meant to - with this library, you use the `useSuspenseQuery` hook in your component, in combination with `useFragment`. 

You do not call `client.query` from Client Components. `getClient()` is only used in React Server Components (it will even throw an error if used from server components), and we are very clear that there is no data transport from server components to client components, as per a direct recommendation from the React team. You should not have shared data between those systems, as updates to data in client components will not update your server components and your UI will get out of sync.

Please take another look at the examples and how they use the library.

**Comment by walhallyus** [comment]
Sorry for miss leading you on this, this is my scenario and implementation:
I have a next 13 using app route. (with [hack-the-supergraph-ssr](https://github.com/apollographql/apollo-client-nextjs/blob/main/examples/hack-the-supergraph-ssr) implementation)

I have a page React Server Components, that is doing a query 
`await getClient().query({ GetResourcesDocument }); `
This page also have some child components that are 'only client' (React Client Components). And I do the same query of GetResourcesDocument but with useSuspenseQuery and fetchPolicy: '**cache-first**'.

I expect this behaviour React Server Components to make the request, then to apollo to transfer the query cache to the client and when the client component is rendered to take the data directly from cache. But for me is making a new request on the client.
I also debugged NextSSRInMemoryCache and when is instantiated in apollo-wrappper, the .data is an empty object {}.

To exclude timing I also tested with the client component in a conditional rendering, with a toggle show button(default as false). I have the same result. First time when I display/toggle the client component is doing a client request but after that on the next show/toggle is taking the data directly from cache without a request. 

Is there a way to debug the cache transfer? (a console.log on server side) or do you know if I'm able to check some variables(that should come from server)  in browser console directly on **window object**?
Thanks!

**Comment by phryneas** [comment]
> I expect this behaviour React Server Components to make the request, then to apollo to transfer the query cache to the client and when the client component is rendered to take the data directly from cache. But for me is making a new request on the client.

That is not the behaviour.

Right now, there is no way of transporting client cache data from React Server Components to the Browser.  
That has the reason that we talked with the React team about this, and they essentially advised us not to move that data over.  
If you retrieve that data in a React Server Component, chance is that you also display it to the user - and then you cannot use that data in a Client Component any more. If that data were ever to update on the client, you would have updated data in your client components, but the server components stay the same. 

That is why we state this in our README:
![image](https://github.com/apollographql/apollo-client/assets/4282439/64c8361f-87ab-420f-8916-dd2ecd84623d)


The `NextSSRInMemoryCache` is there to move data from **SSR** to the Browser. As I already said, **RSC and SSR are two different things**. 
Next SSR renders your Client Components on the server. If you use `useSuspenseQuery` in them, the data fetched during that will be moved over to the browser and rehydrated there. 
Again, this has nothing to do with React Server Components and that data should not be mixed.

We have a [very long document here](https://github.com/apollographql/apollo-client-nextjs/blob/pr/RFC-2/RFC.md) describing how the Next.js app directory works with RSC and SSR in mind.
