### ISSUE TITLE
Ongoing mutation results are not ignored when calling `MutationResult.reset()`

### ISSUE THREAD

**Issue by ItaiYosephi** [apollographql/apollo-client#10927]
### Issue Description

When resetting a mutation while there is an ongoing request, response should be ignored, and `data` should remain empty.

### Link to Reproduction

https://codesandbox.io/s/heuristic-river-41d7tj?file=/src/index.jsx

### Reproduction Steps

Click `Generate Token`, and then click `reset` in less then 3 seconds.
Loading will change to `false`, but response will eventually will be rendered.

**Comment by phryneas** [comment]
This should be fixed over in #10931. I already tried it with your Sandbox (my clone: https://codesandbox.io/s/reverent-nightingale-ekm9vu ) and that seems good. 

If you want to give it a try in your code base:

`npm i @apollo/client@0.0.0-pr-10931-20230530114442`
