### ISSUE TITLE
After a mutation, when i refetchQueries, how do i give the same (last used) variables?

### ISSUE THREAD

**Issue by pvinis** [apollographql/apollo-client#10939]
I have in one screen this:
```
  const { data, loading, fetchMore, refetch } = useTransactionsQuery({
    variables: { page: initialPage, query },
  });
```

and in another this
```

  const [updateTransactionStatusMutation, { data, loading, error }] =
    useUpdateTransactionStatusMutation({
      refetchQueries: [{ query: transactionsQuery }],
    });
```

now in the second component, when i call `updateTransactionStatusMutation({ variables: { wow: true }})`, i would expect the top query to rerun with the latest variables, whatever was given last time. is there a way to do this? or is the only way to pass the variables from the first comp to the second comp, so i can pass then in the refetch?

**Comment by bignimbus** [comment]
For transparency: I'm discussing this with @pvinis in [this Discord thread](https://discord.com/channels/1022972389463687228/1113842307486203904/1113842307486203904)
