### ISSUE TITLE
Requests silently do nothing when `uri` is undefined

### ISSUE THREAD

**Issue by dylantf** [apollographql/apollo-client#10932]
### Issue Description

I'm not sure if this is a bug or intended behavior, but I accidentally instantiated a client with an undefined `uri` when I was missing an environment variable. I got no output or errors of any kind, but my useQuery hooks would just hang forever with `{ loading: true, called: true }` but no network request attempted.

Should there perhaps be a warning or error if a client is created without a uri? It was a bit hard to debug because the code was all "correct" but nothing happens. Feel free to just close if this is intended so it can be run in cache only mode.

**Comment by bignimbus** [comment]
Hi @dylantf 👋🏻  I did some digging and here's what I found:

https://github.com/apollographql/apollo-client/blob/720bc42a508db11720ec58255747e467714668be/src/core/ApolloClient.ts#L155-L157

Based on what you shared, `ApolloLink.empty()` is being used if `uri` is falsy.  Here's that code:

https://github.com/apollographql/apollo-client/blob/720bc42a508db11720ec58255747e467714668be/src/link/core/ApolloLink.ts#L38-L40

That noop function appears to have been added intentionally.  Here's an inline comment from five years ago:

https://github.com/apollographql/apollo-client/blob/4f723feea8fbb68de039ddf5af33bcedc9714c24/packages/apollo-client/src/ApolloClient.ts#L135-L139

From that comment I think the intention here is that the client is usable without a `uri`.  That makes sense, though to your point I wonder whether there is more we can do to help developers catch this.  Any suggestions?
