### ISSUE TITLE
document `addTypePolicy`

### ISSUE THREAD

**Issue by phryneas** [apollographql/apollo-client#10933]
### Issue Description

It seems like we don't have addTypePolicy anywhere in the docs - we should definitely add that.

This came up here: 

### This came up here

https://stackoverflow.com/questions/76356769/apollo-client-is-there-a-way-to-define-apollo-client-type-policy-after-the-clie/76359617

**Comment by sahilmanchanda1999** [comment]
Hi @phryneas,

I would like to contribute to this issue. I have implemented my suggestions in the document at this link (https://github.com/apollographql/apollo-client/blob/main/docs/source/caching/cache-configuration.mdx').

Please review the screenshot and let me know if you have any questions or feedback.

<img width="809" alt="image" src="https://github.com/apollographql/apollo-client/assets/36594384/ed2fc6ca-2afe-418b-948d-5cb069ba64d7">

Thanks,
Sahil Manchanda

**Comment by jerelmiller** [comment]
@sahilmanchanda1999 feel free to submit a PR! My at-a-glance read through of this looks good, but we can provide more detailed feedback in a pull request. Thanks for volunteering!

**Comment by sahilmanchanda1999** [comment]
Hi @jerelmiller,

Thanks for the feedback. I have created a pull request for the same. https://github.com/apollographql/apollo-client/pull/10967

Regards,
Sahil Manchanda

**Comment by sahilmanchanda1999** [comment]
Hi @jerelmiller,

I apologize for the delay. I have made the requested updates based on your suggestion https://github.com/apollographql/apollo-client/pull/10967 . If there are any further modifications needed, please let me know.

Regards,
Sahil Manchanda
