### ISSUE TITLE
Error not handled when accessing reactivevar via query

### ISSUE THREAD

**Issue by devshun** [apollographql/apollo-client#10943]
### Issue Description

Hi, maintainer👋

This report pertains to scenarios where variables declared in reactivevar are accessed through a query. I define the reference of the query using typePolicies as shown below:

```
...
type SampleVar = {
  id: number;
  name: string;
  email: string;
  isActive: boolean;
  createdAt: Date;
};

const sampleVar = makeVar<SampleVar>({
  id: 0,
  name: "",
  email: "",
  isActive: false,
  createdAt: new Date(),
});

const cache: InMemoryCache = new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        sample: {
          read: () => sampleVar(),
        },
      },
    },
  },
});
...
```

Next, I call the query in the component as follows:

```
...
const GET_SAMPLE_QUERY = gql`
  query {
    sample @client {
      id
      name
      email
      isActive
      createdAt
      # add unknown fields
      unknownField
    }
  }
`;

function App() {

  const { data, error } = useQuery(GET_SAMPLE_QUERY);

  console.log(data, error);
 // to be console -> undefined undefined
...
```

In the above scenario, even when trying to retrieve a field not defined in the query, no error is displayed in the console, and the error variable is also fetched as undefined. It would be more developer-friendly if an error such as `Error: Field unknownField doesn't exist on type ~~~` could be fetched when trying to retrieve a field not defined in the query. I wish you would handle errors in such cases.

### Link to Reproduction

https://github.com/devshun/reactivevar-query-sample

**Comment by devshun** [comment]
@bignimbus

Thank you for your response!!

As you suggested, I created a case using the GraphQL code generator.

[demo](https://github.com/devshun/reactivevar-query-sample/tree/43c5d028d6a0c386795b85fc7af4ce9c0e64e5ec)

When I run the code generator and define a field that isn't in the query, an error is generated.

graphql
Copy code
GraphQL Document Validation failed with 1 errors;
      Error 0: Cannot query field "unknownField" on type "Sample".
This seems to largely resolve the issue I mentioned earlier.

However, in another scenario where I attempt to retrieve a variable that's defined in the schema but not in the reactive variable, the code generator still runs successfully. As with the previous issue, the error ends up being undefined. [In this example](https://github.com/devshun/reactivevar-query-sample/tree/b1dedf389773d375040d2afa410da30d2e9926c8), I've added the unknownfield (which isn't defined in reactivevar) to the Sample's query type. Is there a method to strictly verify the conformity between the schema defined in reactivevar and the GraphQL schema?

**Comment by bignimbus** [comment]
Thanks @devshun - I don't think there's a way to do that with the available tooling.  If a field is included in the schema there could be any number of places where that field could be resolved.  I imagine that what you're describing is a feature that theoretically could be developed but it would probably be a very large effort.  I'll close this issue for now, let me know if you feel like there's something else for the maintainers to address here 🙏🏻
