### ISSUE TITLE
Errors in reducer function get swallowed

### ISSUE THREAD

**Issue by helfer** [apollographql/apollo-client#1094]
Tried to write a test for query variables yesterday, and errors thrown in the reducer function didn't show up anywhere. This may only be happening in the tests, but we should fix it anyway.

**Comment by eminaz** [comment]
+1 on this. Currently I have to write the same code in updateQueries first to find what the errors are, after making sure there are no more errors, then move the code to the reducer function.

**Comment by gpsamson** [comment]
+1 for this too. I've been running around in circles for about an hour and it turns out a reducer error was thrown and stored in the store, but it was never logged to the console.

The reducer error was thrown because I wasn't explicitly setting optional arguments to null. I'll be opening an issue for this specifically if it doesn't exist.

**Comment by calebmer** [comment]
@eminaz and @gpsamson could you try reproducing with `0.6.0`, it may have been fixed because a test reproducing the error passes. See https://github.com/apollostack/apollo-client/pull/1143. Are you using `react-apollo`? Currently `react-apollo` doesn’t log unhandled errors.

**Comment by gpsamson** [comment]
@calebmer I can confirm that an error is logged if you don't define all of the variables.

**Comment by colvint** [comment]
+1 for reducer errors getting swallowed. In my case, I was returning an object from my reducer which was *missing* a field which was *present* in the underlying query / fragment it was intended to update.

**Comment by helfer** [comment]
This _might_ be fixed now. If it's still an issue, please open a new issue!
