### ISSUE TITLE
Using MockedProvider for tests, ... gql fragments not working

### ISSUE THREAD

**Issue by BrandonALittle** [apollographql/apollo-client#10953]
### Issue Description

I'm trying to use the MockedProvider component in Jest (v29.5.0) tests. Some time ago, we changed the data model for one of our queries, resulting in the following structure for our query mock:
```
...
result: {
  data: {
    todaysWorkout: {
      id: 'mockWorkout',
      slots: {
        slot1: {...},
        slot2: {...},
        slot3: {...},
        slot4: {...},
        slot5: {...},
      },
    },
  },
},
```

The data the comes through to our component query in tests loses all of the `slot` entries in the `slots` object, resulting in `data` being the following:
```
{
  todaysWorkout: {
    id: 'mockWorkout',
    slots: {},
  },
}
```

If I change `slots` in the mock to seemingly ANY OTHER WORD, such as `slotss` (with two final `s`) or `abracadabra` or `bobsYourUncle`, the data comes through correctly, and we get all of our `slot` entries (`slot1`, `slot2`, ...).

Is `slots` a reserved word or something?

### Link to Reproduction

Nope

**Comment by bignimbus** [comment]
Hi @BrandonALittle 👋🏻 do you have a repo we could take a look at?  There could be any number of things going on in your source code that could narrow down what might need to be done here.  FWIW `slots` is not a reserved word.  Hope to hear from you!

**Comment by BrandonALittle** [comment]
Thanks for the quick reply. Much appreciated. I unfortunately can't share source code publicly. Our other mock queries work fine, and this seems to be limited to the use of the key `slots`. I'll keep trying on my end.

**Comment by BrandonALittle** [comment]
Here is a DemoComponent:
```
const DemoComponent = () => {
  const { data } = useGetTodaysWorkoutQuery({
    variables: {
      knownSlugs: [],
    },
  })

  console.log('data: ', data)

  return <></>
}

export default DemoComponent
```

With a test:
```
const apolloMocks = [
  {
    request: {
      query: GetTodaysWorkoutDocument,
      variables: {
        knownSlugs: [],
      },
    },
    result: {
      data: {
        todaysWorkout: {
          id: 'mockWorkout',
          slots: {
            slot1: {},
            slot2: {},
            slot3: {},
            slot4: {},
            slot5: {},
          },
        },
      },
    },
  },
]

describe('DemoComponent', () => {
  it('receives correct workout data', async () => {
    render(
      <MockedProvider mocks={apolloMocks} addTypename={false}>
        <DemoComponent />
      </MockedProvider>,
    )

    await act(async () => {
      await new Promise((resolve) => setTimeout(resolve, 0))
    })
  })
})
```

When running the test, the component logs `data` to the console:
```
data:  { todaysWorkout: { id: 'mockWorkout', slots: {} } }
```

This is a simplification of what I'm seeing, but this is essentially the problem.

**Comment by BrandonALittle** [comment]
`useGetTodaysWorkoutQuery`:
```
export function useGetTodaysWorkoutQuery(baseOptions: Apollo.QueryHookOptions<GetTodaysWorkoutQuery, GetTodaysWorkoutQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<GetTodaysWorkoutQuery, GetTodaysWorkoutQueryVariables>(GetTodaysWorkoutDocument, options);
      }
```

`GetTodaysWorkoutDocument` is generated from a graphql file:
```
fragment WorkoutGame on WorkoutGame {
  lastGamePlay {
    finishedAt
    id
  }
  game {
    slug
  }
}

fragment WorkoutSlots on WorkoutSlots {
  slot1 {
    ...WorkoutGame
  }
  slot2 {
    ...WorkoutGame
  }
  slot3 {
    ...WorkoutGame
  }
  slot4 {
    ...WorkoutGame
  }
  slot5 {
    ...WorkoutGame
  }
}
query GetTodaysWorkout($knownGameSlugs: [String!]!) {
  todaysWorkout(knownGameSlugs: $knownGameSlugs) {
    id
    slots {
      ...WorkoutSlots
    }
  }
}
```

**Comment by bignimbus** [comment]
What happens if you consolidate the nested fragments so that `GetTodaysWorkout` looks like this:

```graphql
query GetTodaysWorkout($knownGameSlugs: [String!]!) {
  todaysWorkout(knownGameSlugs: $knownGameSlugs) {
    id
    slots {
      slot1 {
        lastGamePlay
        # etc
      }
      # slot2, slot3, etc
    }
  }
}
```

I'm wondering whether the type conditions in the fragments are playing a role here.  If so, maybe including `__typename` in your JSON data might help?

**Comment by BrandonALittle** [comment]
I'll give the consolidation a try. I have already tried adding the `__typename` though, and that doesn't change anything.

**Comment by BrandonALittle** [comment]
Example with `__typename`s:
```
{
  "data": {
    "todaysWorkout": {
      "id": "mockWorkout",
      "slots": {
        "slot1": {
          ...
          "__typename": "WorkoutGame"
        },
        "slot2": {
          ...
          "__typename": "WorkoutGame"
        },
        "slot3": {
          ...
          "__typename": "WorkoutGame"
        },
        "slot4": {
          ...
          "__typename": "WorkoutGame"
        },
        "slot5": {
          ...
          "__typename": "WorkoutGame"
        },
        "__typename": "WorkoutSlots"
      },
      "__typename": "Workout"
    }
  }
}
```

**Comment by bignimbus** [comment]
I don't see any indication that `MockedProvider` treats fragments any differently than the rest of the library.  It's a very small class:

https://github.com/apollographql/apollo-client/blob/a1dac639839ffc5c2de332db2ee4b29bb0723815/src/testing/react/MockedProvider.tsx#L27-L75

Can you verify that your query is working as expected outside of your test environment?

Also, what version of `@apollo/client` are you using?

**Comment by BrandonALittle** [comment]
The query has been working correctly in our app for well over a year, and we've never had any issues with it in the app. I am currently on version `3.7.15` of `@apollo/client`. As far as the `...`, I'm copying and pasting a working query response from our app and using it as the mock:
```
result: {
      data: {
        todaysWorkout: {
          id: 'ff4a4d9a-bb5b-4a69-9ddf-2f8b7b396687',
          slots: {
            slot1: {
              lastGamePlay: { finishedAt: 1686071958030, id: 209, __typename: 'GamePlay' },
              game: { slug: 'mockGameName1', __typename: 'Game' },
              __typename: 'WorkoutGame',
            },
            slot2: {
              lastGamePlay: { finishedAt: 1686071969630, id: 210, __typename: 'GamePlay' },
              game: { slug: 'mockGameName2', __typename: 'Game' },
              __typename: 'WorkoutGame',
            },
            slot3: {
              lastGamePlay: { finishedAt: 1686071976163, id: 211, __typename: 'GamePlay' },
              game: { slug: 'mockGameName3', __typename: 'Game' },
              __typename: 'WorkoutGame',
            },
            slot4: {
              lastGamePlay: { finishedAt: 1686071983431, id: 212, __typename: 'GamePlay' },
              game: { slug: 'mockGameName4', __typename: 'Game' },
              __typename: 'WorkoutGame',
            },
            slot5: {
              lastGamePlay: { finishedAt: 1686071990297, id: 213, __typename: 'GamePlay' },
              game: { slug: 'mockGameName5', __typename: 'Game' },
              __typename: 'WorkoutGame',
            },
            __typename: 'WorkoutSlots',
          },
          __typename: 'Workout',
        },
      },
    }
```

**Comment by jerelmiller** [comment]
@BrandonALittle do you know the last version of `@apollo/client` you were using when this was last working? You might try downgrading patch versions until you see this working again. That might be able to help us narrow down the set of changes that might have contributed to the change in behavior.

**Comment by BrandonALittle** [comment]
I don't think that this has ever worked with this query as is. At some point, maybe a year ago, our graph changed, and as a result our query changed. I recently upgraded jest, and this upgrade revealed warnings around our mocks that we previously weren't seeing, meaning that we didn't know that the mocks weren't working as expected. I'm trying to resolve this, but unfortunately my colleagues who worked on this last year are no longer with our team.

**Comment by jerelmiller** [comment]
@BrandonALittle totally understand!

> I recently upgraded jest, and this upgrade revealed warnings around our mocks that we previously weren't seeing, meaning that we didn't know that the mocks weren't working as expected.

To confirm what you're saying here, are you saying that when this doesn't work (the query with fragments), you are seeing the [warning message](https://github.com/apollographql/apollo-client/blob/a1dac639839ffc5c2de332db2ee4b29bb0723815/src/testing/core/mocking/mockLink.ts#L108-L114) in your test?

**Comment by BrandonALittle** [comment]
No, sorry for the confusion. A long time ago, our query was structured differently. I wrote tests around it using a mock that worked. A year ago, another teammate made code changes and added this `slots` concept, along with the fragments. The mocks were never changed. I recently upgraded Jest to the latest version, and I started seeing the warnings pointing out that the mocks were misconfigured. I dug in and discovered that the tests were not working as intended all this time. I encountered this weird issue in the process of trying to fix the tests.

**Comment by BrandonALittle** [comment]
I found that setting `addTypename` to `true` on the `cache` that is passed to the `MockedProvider`'s `cache` prop, OR removing the `addTypename` property from the cache configuration while also removing the `addTypename` prop from the MockedProvider allowed the mock to fully come through in the test. I don't understand this, as another mock in the very same test suite comes through on its own without needing to adjust this prop. The query mocked in that case also contains fragments.

**Comment by jerelmiller** [comment]
@BrandonALittle I did my best to try and reproduce the issue in our test suite, but didn't have much luck doing so. See my reproduction here: https://github.com/apollographql/apollo-client/compare/mocked-provider-reproduction

If you pull down and run that new test, you'll see that it passes. Would you be willing to fork this test and/or provide an alternate reproduction for me where you are able to see a failing test? Without access to your code, its difficult to tell where the differences are between my test and yours.

**Comment by BrandonALittle** [comment]
I understand. Thanks for digging in. Our code is doing basically exactly what you've done in your test. I'm out of ideas, but I'll try to recreate the problem.

**Comment by jerelmiller** [comment]
@BrandonALittle I'd be happy to do a zoom call to pair on this a bit if nothing else. Not sure if that would be feasible from your end or not, but if thats of interest, let me know and I can set something up!

**Comment by BrandonALittle** [comment]
Thank you for the example test. I wrote more tests with various scenarios, and I think I found the problem. We use a simple QueryLoader component to render a loading indicator while waiting for query data:
```
interface QueryLoaderProps {
  loading: boolean
  error: ApolloError | undefined
  data: any
  children: any
}

const QueryLoader: React.FC<QueryLoaderProps> = ({ loading, error, data, children }) => {
  if (loading) {
    return <LoadingIndicator />
  }

  if (error) {
    console.error(error)
    return <Error />
  }

  if (!data) {
    console.log('No data returned from query')
    return <Error />
  }

  if (data) {
    return children
  }
}
```

This naive implementation has worked fine for us for a long time in our app, but it seems that, in tests, queries running inside `children` or lower in the tree need `__typename` properties.

**Comment by jerelmiller** [comment]
Gotcha! Glad you were able to find the source of the issue! Is there anything here we can help with or does it seem like you'll be able to solve it from your end?

**Comment by BrandonALittle** [comment]
We can solve it our end, I think. If you have any suggestions, they would be appreciated. We'll set `addTypename` to `true` for now, and look to refactor our QueryLoader component at some point. Thank you so much for all the help!

**Comment by jerelmiller** [comment]
You're welcome!

As for suggestions, not sure I can give any good specific advice without seeing the entirety of the tests. You're always welcome to check out how we test [`useQuery` internally](https://github.com/apollographql/apollo-client/blob/main/src/react/hooks/__tests__/useQuery.test.tsx) if that may give you some clues as to how to structure some of your tests, though granted this isn't a full application so we have a lot of dummy queries/data in there 😄.

I'll go ahead and close out this issue, but feel free to ping us if you need anything more!
