### ISSUE TITLE
How to specify a refetch handler globally

### ISSUE THREAD

**Issue by EmmanuelPonnudurai** [apollographql/apollo-client#10971]
Hello, this is my use case,
- Apollo Client fires the first request, which is a HTTP GET with a hash (created from the query or whatever)
- Backend (graphql dotnet backend) looks at the hash and says I don't have it in my store and returns a specific error
- Apollo Client look at this specific error response and says refetch the same, this time with hash + query in HTTP POST
- Backend now stores the query with the hash and fulfills the request and sends response.
- Next time the same hash is used as HTTP GET, backend knows what the query is and can just fullfill the request. 

This is exactly like [apollo persisted queries](https://www.apollographql.com/docs/apollo-server/performance/apq/), except in my case im trying to get it working via a non-apollo backend. 

Can someone tell me if there is a hook or a handler or callback that I can pass along in HttpLink or ApolloLink or ApolloClient globally, to achieve this kind of an automatic retry? 

I looked at the code and couldn't find if there is an option exposed like this in a generic manner. 

It would be great if I could achieve this. 

Any suggestions are welcome. Thank you in advance.

**Comment by jerelmiller** [comment]
Hey @EmmanuelPonnudurai 👋 

Have you tried either the [`RetryLink`](https://www.apollographql.com/docs/react/api/link/apollo-link-retry) or [`onError` link](https://www.apollographql.com/docs/react/data/error-handling/#on-graphql-errors)? This seems to fit what you're trying to achieve.

Depending on what type of error the server returns might depend on which of these you want to use. Try either of these out to see what works best in your case, but either way, this should allow you to retry the request.

Let me know if this helps!

**Comment by EmmanuelPonnudurai** [comment]
Hi @jerelmiller. Thanks for the suggestion ill try it out and keep you posted.

**Comment by EmmanuelPonnudurai** [comment]
Hello @jerelmiller I tried the `onError` link approach and this works as expected. Thank you for pointing me to the right place.

**Comment by EmmanuelPonnudurai** [comment]
You can go ahead and close this issue. Once again, I am very happy with the prompt response from you and your team. It's immensely helpful. 

Much appreciated and keep up the great work.

**Comment by jerelmiller** [comment]
Glad to hear that worked! Let us know if you need anything else!
