### ISSUE TITLE
Inconsistent cache update behavior

### ISSUE THREAD

**Issue by dulguun0225** [apollographql/apollo-client#10978]
### Issue Description

Some queries merge and some queries update the cache field, even if they select exactly the same fields. I don't think this behavior is desirable in any way.

### Link to Reproduction

https://github.com/dulguun0225/apollo-client-cache-reproduction

### Reproduction Steps

1. Run the server and client
2. Press getUser and observe `User:1`'s `details { a b }`.
3. Press getUserLessDetail and see that it doesn't change `User:1`'s `details { a b }`
4. Press getPost and notice that it removes `b` from `User.details`

Both `getUserLessDetail` and `getPost` selects exactly the same fields of `User`. But it modifies the cache differently. 

It happens becaues `getUserLessDetail` hits the cache and `getPost` don't. But this behavior is very unintuitive and inconsistent, if you look from the perspective of what data is being selected.

**Comment by phryneas** [comment]
This is the behavior I see after adding some logging to your example:

![image](https://github.com/apollographql/apollo-client/assets/4282439/e658320d-11b7-4191-9520-1e9b3f0a7a5b)

Note that unlike you, step 3. is already removing `b` - which is kind of expected, as also indicated by that big warning message.

**Comment by dulguun0225** [comment]
I guess this is not of technical but of opinion difference. Forcing people to put id in every nested object is kind of rigid approach, I guess. 

Sometimes nested types like these
```
detail {
 a 
 b
 c
}
```
are just there to avoid something like
```
detailA
detailB
detailC
```

**Comment by dulguun0225** [comment]
Is it possible to set the type policy to merge, on the server side schema? Maybe, some kind of custom directive, so that the client can read it and set `merge: true` for those types.

**Comment by phryneas** [comment]
No, but as mentioned in the other thread you can have a fuzzy typePolicy that just applies to all your entities. But I would really recommend you not to do that - there is a reason we don't merge by default. It will cause a bug sooner or later.
