### ISSUE TITLE
 Enable Query/Mutation Fetching with Boolean Flag

### ISSUE THREAD

**Issue by Abdel-Monaam-Aouini** [apollographql/apollo-client#10979]
### Issue
Currently, Apollo Client does not provide a built-in mechanism to enable or disable fetching data based on a boolean flag. This feature request aims to enhance Apollo Client's functionality by introducing a flag that allows developers to control whether queries or mutations should be executed based on the value of a boolean flag.

### Proposed Solution
The suggested solution involves adding a new configuration option to the Apollo Client setup, which would enable or disable the fetching of data based on a specified flag. This flag could be a simple boolean value that developers can set based on their application's requirements.

### Expected Behavior
When the **enableFetching** flag is set to **true**, Apollo Client will perform the usual fetching of queries and mutations.

### Motivation
This feature would be beneficial in scenarios where developers want to conditionally control data fetching based on dynamic flags or feature toggles. It can help optimize network traffic and improve performance by preventing unnecessary requests.

**Comment by Abdel-Monaam-Aouini** [comment]
> Right now, this could be done in a custom Link.
> 
> Could you elaborate a little more how this should be different from an implementation that is currently possible with a custom Link?
> 
> A possible implementation might look like
> 
> ```js
> let locked = false;
> let waitForUnlock: Promise<void> | undefined
> let signalUnlock: () => void | undefined;
> 
> export function enableExternalDataSources(value: boolean) {
>   if (!value) {
>     if (locked) return
>     locked = true;
>     waitForUnlock = new Promise(resolve => {
>       signalUnlock = resolve;
>     });
>   } else {
>     if (!locked) return
>     locked = false;
>     waitForUnlock = undefined;
>     signalUnlock?.();
>   }
> }
> 
> export const externalDataSourcesLink = new ApolloLink((operation, forward) => {
>   if (locked) {
>     return new Observable((observer) => {
>       waitForUnlock!.then(() => {
>         forward(operation).subscribe(observer);
>       });  
>     })
>   }
>   return forward(operation); 
> });
> ```

Nice 😊

**Comment by phryneas** [comment]
I'm gonna close this one - if you have any follow-up questions, feel free to reopen :)
