### ISSUE TITLE
Ambiguous caching of fields with optional variables

### ISSUE THREAD

**Issue by JohannCooper** [apollographql/apollo-client#10977]
### Issue Description

If an object type is queried that contains a field with an optional variable, and no value is specified for the variable when the query is executed, the field is cached two different ways depending on whether the variable is referenced.

For example, when executing this query without specifying a value for `prefix` (an optional variable), two `prefixedName` fields are created in the cache.
```gql
query AllPeople($prefix: String) {
  people {
    prefixedName1: prefixedName
    prefixedName2: prefixedName(prefix: $prefix)
  }
}

"""
EXAMPLE CACHE RECORD

Person:1
__typename:"Person"
prefixedName:"..."
prefixedName({}):"..."
"""
```

This behavior causes issues when updating the cache manually. When using `updateFragment` for example, the fragment used will need to include both the field with a reference to the variable and the field without a reference to the variable in order to update all cached query responses that may have requested the field using either strategy. 

```gql
fragment MyFragment on Person {
  prefixedName
  prefixedName(prefix: $prefix)
}
```

In my mind these fields should be cached as a single field since they represent the same case (no variables specified). If this behavior is intentional, is there any way to configure the in-memory cache to generate the same cache record for both cases?

### Link to Reproduction

https://github.com/JohannCooper/apollo-duplicate-cache-fields

### Reproduction Steps

1. Run the `main` branch of the linked repository.
2. Open the Apollo Client Devtools.
3. Select any of the `Person` records in the "CACHE" tab.
4. Notice that each record has two fields representing the case where no variables are specified for the `prefixedName` field:
```
prefixedName: "..."
prefixedName({}): "..."
```

**Comment by jerelmiller** [comment]
Hey @JohannCooper 👋 

This behavior is by design and intentional. From our [docs](https://www.apollographql.com/docs/react/caching/cache-field-behavior#specifying-key-arguments):

> **By default, all of a field's arguments are key arguments.** This means that the cache stores a separate value for every unique combination of argument values you provide when querying a particular field.

What you're looking for is to configure a [`keyArgs`](https://www.apollographql.com/docs/react/caching/cache-field-behavior#specifying-key-arguments) value on your type policy to tell the cache which of the arguments should store data separately. You can set `keyArgs` to `false` to turn if off completely (likely what you're after here). Doing so will treat both the field with the argument and the one without as the same field.

Hope this helps!

**Comment by JohannCooper** [comment]
Hi @jerelmiller, thanks for the quick response.

I don't think modifying `keyArgs` will address my issue. In the example I provided, the `prefix` variable does affect the return value of the `prefixedName` field. Because of this, I want the `prefix` value to affect how the field is cached. This would required it to be a key argument.
```
Person:1
__typename:"Person"
id:"1"
name:"John Smith"
prefixedName:"John Smith"
prefixedName({}):"John Smith"
prefixedName({"prefix":"Mr."}):"Mr. John Smith"       # Return value changed!
```

What I tried to describe were two cases where no value was specified for the `prefix` variable (once when referenced in the query and once when it was not) that produced two different values for the field in the cache. According to the docs, the intention of `keyArgs` is to indicate "which arguments are key arguments that affect the field's return value". But in both cases I am not passing a value for the variable so there is no way the return value could be affected. And yet, two different cache values are created.

The behavior I would have expected is for any variable that is a key argument that is given a value, it will be used in the caching of the field. If the variable is a key argument and it is not given a value (either because it is not referenced in the query or not given a value when calling the query), it will not be used in the caching of the field.

**Comment by jerelmiller** [comment]
I think I understand what you're saying. Essentially you want `prefixedName(prefix: $prefix)` and `prefixedName` to cache on the same key when `prefix` is not given a value via `variables`. Does that sound correct?

In that case, a `keyArgs` function is probably going to be your best bet:

```ts
new InMemoryCache({
  typePolicies: {
    Person: {
      fields: {
        prefixedName: {
          keyArgs: (args) => {
            if (!args || !args.prefix) {
              return false;
            }
  
            return ['prefix'];
          }
        }
      }
    }
  }
});
```

In this case, if you query for `prefixedName` (no args) or `prefixedName(prefix: $prefix)` and provide no variables, these will result in storing the value in the same key. If you do provide a prefix, it will store it on a separate key.

I've created what I believe is a [reproduction](https://codesandbox.io/s/cranky-wood-jsxcz4?file=/src/index.jsx) of this behavior so you can see how this works. Check the console to see the full cache. You'll see that removing the argument to `name`, or ommitting the `prefix` variable will store the value in the same field. As soon as you provide a `variables: { prefix: ... }`, this will be stored separately.

Does this address what you're looking for?

**Comment by JohannCooper** [comment]
@jerelmiller 
This is exactly what I was looking for! Thank you for the patient and thourough response, greatly appreciated :slightly_smiling_face:

**Comment by jerelmiller** [comment]
@JohannCooper fantastic! Glad to hear that works for you!!
