### ISSUE TITLE
Setting up Intellisense for with localSchemaFile is broken 

### ISSUE THREAD

**Issue by alex-tang-carta** [apollographql/apollo-client#10975]
Having issues getting VSCode extension (apollographql.vscode-apollo) to find my graphql file. Am I missing some configuration?

apollo.config.cjs file:
```
module.exports = {
    client: {
        service: {
            name: "default",
            localSchemaFile: './src/schema.graphql'
        },
    },
};
```

folder structure:
```
- src/
       - schema.graphql
- apollo.config.cjs
```

<img width="1615" alt="image" src="https://github.com/apollographql/apollo-tooling/assets/89428176/f10e3ae1-3fb3-46c8-96b8-bfde6d91c5be">

**Comment by jerelmiller** [comment]
Hey @alex-tang-carta 👋 

Would you mind opening this issue in the [`vscode-graphql`](https://github.com/apollographql/vscode-graphql) repo? This is more a question for the VSCode extension than the core library.

Alternatively, you might be able to get community help by asking in our [Discord channel](https://discord.gg/graphos) or [community forums](https://community.apollographql.com). Thanks!
