### ISSUE TITLE
 How can I refetch a specific query among multiple queries with the same name but each one with different variables?

### ISSUE THREAD

**Issue by guilhermemiua** [apollographql/apollo-client#10985]
Hi!

I have a Kanban board with multiple columns. In each column, I make a "GetCards" query call by passing the "id" of that column to list its cards.

When creating a new card, I want to only refetch the "GetCards" query of the first column. But when I use the "GetCards" in the prop `refetchQueries` of the `useMutation`,  the "GetCards" of each column is refetched.

```
// Column.tsx
const { data } = useQuery(GetCards, {
  variables: {
    columnId,
  }
});

// Kanban.tsx
<Column columnId={1} key="column-1" />
<Column columnId={2} key="column-2" />
<Column columnId={2} key="column-2" />

// CreateCardModal.tsx
const [createCard] = useMutation({
  refetchQueries: ["GetCards"]
});
```

Is there a way for refetching only one specific query among multiple queries with the same name but each one with different variables? Here at the `CreateCardModal.tsx` I don't have access to each column variables used to fetch the "GetCards".

For this scenario I can't manually update the cache, I need to refetch the data.

Thanks! :)

**Comment by phryneas** [comment]
Assuming that you get your `columnId` back from the mutation in some way, you could do something along the lines of

```js
const [createCard] = useMutation(CreateCard, {
  refetchQueries: result => [{query: GetCards, variables: { columnId: result.data.columnId } }]
});
```

**Comment by alessbell** [comment]
Is there anything else we can help you with @guilhermemiua? Given your 👍 reaction, I'm thinking @phryneas's reply addressed your concern so I'll go ahead and close this issue, but let me know if there's anything else!
