### ISSUE TITLE
`useQuery` causes infinite request loop

### ISSUE THREAD

**Issue by Banou26** [apollographql/apollo-client#10997]
### Issue Description

There is a case where ApolloClient enters an infinite request loop whenever there is 2 `useQuery` with the same query but different variables, e.g
```ts
  const { data } = useQuery(GET_PACKAGES, { variables: { search: 'foo', app: true } })
  const { data: data2 } = useQuery(GET_PACKAGES, { variables: { search: 'foo', app: false } })
```

If `possibleTypes` is correctly set, it seems to work fine, but for my fully fledged project, this still doesn't fix the infinite loop for some reason

I assume it might be caused by what the cache merging message warns about, but I'm not sure what could be the type policy to use child arguments as parent key arguments

### Link to Reproduction

https://github.com/Banou26/apollo-client-issue-infinite-request-loop

### Reproduction Steps

`npm i`, `npm run dev`, go to the link and see console

**Comment by jerelmiller** [comment]
Hey @Banou26 👋 

This looks a lot like #10992. Can you take a look at that issue and see if it looks relevant to your queries?

**Comment by Banou26** [comment]
Oh, yes, the timing, I checked for similar issues yesterday and didn't find any, i guess i should'v checked today again, thanks
