### ISSUE TITLE
useLazyQuery only triggers once

### ISSUE THREAD

**Issue by muriloalvestravelpass** [apollographql/apollo-client#11005]
### Issue Description

Hello guys, how are you?

So before I describe the bug I need to give a little bit of context, because I believe it will help. I'm working in Call Center application, in a certain point of the call our customers have to say their credit card data to the agent who is helping them, so the application has a feature to mask the call recording, so the credit card data won't be saved in the recording. The agent can mask/unmask the call multiple times.

The above description is what I'm trying to achieve, I partly have achieved, but it only works once. The agent mask, then unmask the call, great it worked. But if he tries to do that again, the network request doesn't happen.

I'm using `useLazyQuery` that is called when the agent clicks in the button. The `fetchPolicy` is set as `no-cache`, I also tried `network-only` but it didn't work either. So I really don't know what is happening, why `useLazyQuery` it only works once? The funny/bizarre thing is, if I save the file even without any changes, the `hot reload` from react happens and then I'm able to mask/unmask multiple times, meaning, I'm able to call the function from `useLazyQuery` multiple times. That's really weird and I don't know why/how that happens. 

  
_**Dependencies**_
```
"@apollo/client": "^3.6.9",
"graphql": "^16.5.0",
"react": "^18.0.0",
"graphql": "^16.5.0",
```

**_Component_**
```
import { useLazyQuery } from '@apollo/client'
import { useState } from 'react'
import { isCallMasked, setIsCallMasked } from 'src/App/common/utils.maskUnmask' //It uses localStorage
import { useCallVariables } from 'src/config/lucency'
import { useIsCallActive } from 'src/hooks'
import { maskCallQuery, unmaskCallQuery } from 'src/pages/checkout/common'

export const MaskUnmaskButton = () => {
  const [isMasked, setIsMasked] = useState(isCallMasked())
  const { REAL_VALUE_OMITTED01, REAL_VALUE_OMITTED02 } = useCallVariables()
  const isCallActive = useIsCallActive()
  const variables = {
    key01: REAL_VALUE_OMITTED01,
    key02: REAL_VALUE_OMITTED02,
  }

  //GraphQL Queries
  const [stopsCallRecording, { loading: maskLoading }] = useLazyQuery(
    maskCallQuery,
    {
      fetchPolicy: 'no-cache',
      variables,
      onCompleted: () => updateCallState(true),
    }
  )
  const [restartsCallRecording, { loading: unmaskLoading }] = useLazyQuery(
    unmaskCallQuery,
    {
      fetchPolicy: 'no-cache',
      variables,
      onCompleted: () => updateCallState(false),
    }
  )

  const updateCallState = (masked: boolean) => {
    setIsMasked(masked)
    setIsCallMasked(masked)
  }

  //Irrelevant code omitted

  const handleOnClick = () => {
      if (!isMasked) stopsCallRecording()
      else restartsCallRecording()
  }

  if (!isCallActive) return null

  return (
    <button
      disabled={maskLoading || unmaskLoading}
      className={getContainerStyle()}
      onClick={handleOnClick}
    >
      {getIcon()}
    </button>
  )
}


```

### Link to Reproduction

#

**Comment by jerelmiller** [comment]
Hey @muriloalvestravelpass 👋 

I see you're using v3.6.9. We added a number of fixes in [v3.7.11](https://github.com/apollographql/apollo-client/releases/tag/v3.7.11) for `useLazyQuery` that may or may not fix what you're looking for here. Could you try upgrading to at least 3.7.11 to see if it fixes your issue or not? If not, we'll see if we can dig in further. Thanks!

**Comment by muriloalvestravelpass** [comment]
I tried, but the same is still happening. Have you seen someone report a bug similar to this? If not, do you see any error in my code that could be causing it

**Comment by jerelmiller** [comment]
@muriloalvestravelpass dang, I was hoping the upgrade would help here. At a glance, there is nothing that sticks out to me wrong with your code. Could I have you try one more thing to see if it makes any difference? Rather than passing `variables` to `useLazyQuery`, can you pass them in the function call itself?

```ts
const [stopsCallRecording, { loading: maskLoading }] = useLazyQuery(
  maskCallQuery,
  {
    fetchPolicy: 'no-cache',
    onCompleted: () => updateCallState(true),
  }
)

// ...

stopsCallRecording({ variables })
```

---

I expect this to behave the same, but figured I'd have you try this to see if it makes any difference. Short of this, its difficult for us to dive in further without a reproduction of the issue. If a reproduction is difficult to create, sending us a [Replay](https://docs.replay.io/workflows/recording-bug-reports) of the issue would really help us dig in deeper (if you're able to). If there is sensitive info in there, feel free to email me a link to the Replay so its not here in public.

**Comment by muriloalvestravelpass** [comment]
Man, god bless you, I ran some tests and it worked.

I had to do two changes:

1. I passed the variables to the function as you said
2. I had to use `.then` to update my local state, because apparently `onCompleted` wasn't working/being called. Actually today while I was searching a solution for this bug, I saw people complaining about that. Maybe you could check it.

Anyways, thank you SO much. Here is the code updated:


**_Queries_**
  ```
const [stopsCallRecording, { loading: maskLoading }] = useLazyQuery(
    maskCallQuery,
    {
      fetchPolicy: 'no-cache',
    }
  )
  const [restartsCallRecording, { loading: unmaskLoading }] = useLazyQuery(
    unmaskCallQuery,
    {
      fetchPolicy: 'no-cache',
    }
  )
```
   
**_Trigger function_**

```
  const handleOnClick = () => {
      if (!isMasked) {
        stopsCallRecording({ variables })
          .then(() => updateCallState(true))
          .catch(() => toggleFeedback('Error trying to mask the call.'))
      } else {
        restartsCallRecording({ variables })
          .then(() => updateCallState(false))
          .catch(() => toggleFeedback('Error trying to unmask the call.'))
      }
  }
```

**Comment by jerelmiller** [comment]
@muriloalvestravelpass I'm soooooo glad to hear you were able to get a working solution! We will definitely check on `onCompleted`. Makes sense that it not triggering the callback would be a source of issue in your code. I personally like your solution of using `.then(...)` a bit more anyways as I've found it to typically be a bit more reliable and direct since its used at the function call site.

Let us know if you need anything else!
