### ISSUE TITLE
WebSocket connection to 'ws://localhost:3001/graphql' failed:

### ISSUE THREAD

**Issue by CrispenGari** [apollographql/apollo-client#11003]
I'm having a graphql server that have  subscriptions at `/graphql` and i'm trying to listen to these subscriptions using `apollo` and `useSubscription` hook in react. Here is how I'm setting my client provider:

```ts
import {
  split,
  ApolloClient,
  ApolloProvider,
  InMemoryCache,
  ApolloLink,
} from "@apollo/client";
import { Observable, getMainDefinition } from "@apollo/client/utilities";
import { GraphQLWsLink } from "@apollo/client/link/subscriptions";
import { createClient } from "graphql-ws";
import { createUploadLink } from "apollo-upload-client";
const serverDomain = "localhost:3001";
const requestLink = new ApolloLink(
  (operation, forward) =>
    new Observable((observer) => {
      let handle: any;
      Promise.resolve(operation)
        .then(async (operation) => {
          const jwt = "hello";
          if (jwt) {
            operation.setContext({
              headers: {
                authorization: `Bearer ${jwt}`,
              },
            });
          }
        })
        .then(() => {
          handle = forward(operation).subscribe({
            next: observer.next.bind(observer),
            error: observer.error.bind(observer),
            complete: observer.complete.bind(observer),
          });
        })
        .catch(observer.error.bind(observer));
      return () => {
        if (handle) handle.unsubscribe();
      };
    })
);

const wsLink = new GraphQLWsLink(
  createClient({
    url: `ws://${serverDomain}/graphql`,
  })
);

const httpLink = createUploadLink({
  uri: `http://${serverDomain}/graphql`,
  credentials: "include",
});

const splitLink = split(
  ({ query }) => {
    const definition = getMainDefinition(query);
    return (
      definition.kind === "OperationDefinition" &&
      definition.operation === "subscription"
    );
  },
  wsLink,
  ApolloLink.from([requestLink, httpLink])
);

const client = new ApolloClient({
  link: splitLink,
  cache: new InMemoryCache(),
  credentials: "include",
});

interface Props {
  children: React.ReactNode;
}
const ApolloGraphQLProvider: React.FC<Props> = ({ children }) => (
  <ApolloProvider client={client}>{children}</ApolloProvider>
);

export default ApolloGraphQLProvider;
``` 

I'm wrapping my app with this provider as follows:

```ts
import React from "react";
import ReactDOM from "react-dom/client";
import "./index.css";
import App from "./App";
import ApolloGraphQLProvider from "./Provider";

const root = ReactDOM.createRoot(
  document.getElementById("root") as HTMLElement
);
root.render(
  <React.StrictMode>
    <ApolloGraphQLProvider>
      <App />
    </ApolloGraphQLProvider>
  </React.StrictMode>
);
```

Now when i try to make subscriptions in the `App.tsx` as follows:

```tsx
import "./App.css";
import { gql, useSubscription } from "@apollo/client";

const Doc = gql`
  subscription OnNewFriendRequest($input: OnNewFriendRequestInputType!) {
    onNewFriendRequest(input: $input) {
      message
      friend {
        id
        nickname
      }
    }
  }
`;
function App() {
  const { data, loading } = useSubscription(Doc, {
    variables: {
      input: { id: "ef7c5256-80f0-4de0-9893-51f3e3e9926e" },
    },
  });

  console.log(JSON.stringify({ data, loading }, null, 2));
  return (
    <div className="app">
      <pre>
        <code>{JSON.stringify({ data, loading }, null, 2)}</code>
      </pre>
    </div>
  );
}

export default App;
```

I'm getting the following logs in the console:

```shell
client.mjs:141 WebSocket connection to 'ws://localhost:3001/graphql' failed: 
....
App.tsx:22 {
  "loading": false
}
```

What is posibly the issue here because if i test the subscription in the playground it is working

**Comment by jerelmiller** [comment]
Hey @CrispenGari 👋 

There are a couple different websocket protocols for handling subscriptions and its possible you're using one that your server doesn't support. I'd start investigating there to see if thats the issue.

There is both the newer [protocol](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md) from [`graphql-ws`](https://github.com/enisdenjo/graphql-ws) (which you're using here) and the older [subscriptions-transport-ws protocol](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md). You might try using the [older package/link](https://www.apollographql.com/docs/react/api/link/apollo-link-ws/) just to make sure this isn't the source of your issue.

I'd also recommend taking a look at your network tab to see if you're able to spot the error returned from your server. The `WS` tab should show you the websocket connections for your current tab.

Let us know if any of this helps!

**Comment by alessbell** [comment]
Hi @CrispenGari - was about to say the same thing as @jerelmiller :) I'd take a look at your WebSocket server and make sure it's running properly and _using the same subprotocol as your front end code is via `graphql-ws`_.

I've created a [reproduction in our error template](https://github.com/apollographql/react-apollo-error-template/tree/issue-11003) app with your link code copied over verbatim with just the WS/HTTP URLs changed to point to a CodeSandbox back end. Once you start the WS server by visiting https://uifesi.sse.codesandbox.io/graphql you'll see the front end works as expected.

I'm going to close out this issue, but feel free to [join our Discord](https://discord.gg/graphos) and ask any questions in our [frontend channel](https://discord.com/channels/1022972389463687228/1040406910228254720).
