### ISSUE TITLE
Graph

### ISSUE THREAD

**Issue by sammyfilly** [apollographql/apollo-client#11014]
Thanks for your interest in helping make Apollo Client better!

Feature requests and non-bug related discussions are no longer managed in this repo. Feature requests should be opened in https://github.com/apollographql/apollo-feature-requests.

**Comment by alessbell** [comment]
@sammyfilly looks like opening this was accidental, but if you intended to open a feature request you can file it over on the https://github.com/apollographql/apollo-feature-requests repo. Thanks!
