### ISSUE TITLE
Subscription is creating new subscribe despite the one for particular variables already exists

### ISSUE THREAD

**Issue by Wozniaxos** [apollographql/apollo-client#11022]
### Issue Description

Hi, I couldn't make repro repository since this requires quite lot, i spotted in on private project that i can't give access to and i couldn't find some open GQL API with parametrized subscriptions to make a repro `app` i'll try to explain the bug in the most details i can.

1. I have 2 components that are rendered. One component uses 3 subscriptions (`bid`, `ask` and `bidAskQuote`) like this:

```js
const { data } = useBidSubscription({ variables: { venueAccount: 'BITMEX-testnet1',  symbol: 'BTCUSDT@FOREX@BitMEX' } })
const { data } = useAskSubscription({ variables: { venueAccount: 'BITMEX-testnet1',  symbol: 'BTCUSDT@FOREX@BitMEX' } })
const { data } = useBidAskQuoteSubscription({ variables: { venueAccount: 'BITMEX-testnet1',  symbol: 'BTCUSDT@FOREX@BitMEX' } })
```

the second:

```js
const { data } = useBidSubscription({ variables: { venueAccount: 'BITMEX-testnet2',  symbol: 'BTCUSDT@FOREX@BitMEX' } })
const { data } = useAskSubscription({ variables: { venueAccount: 'BITMEX-testnet2',  symbol: 'BTCUSDT@FOREX@BitMEX' } })
const { data } = useBidAskQuoteSubscription({ variables: { venueAccount: 'BITMEX-testnet2',  symbol: 'BTCUSDT@FOREX@BitMEX' 
} })
```

I can see that for each of those on initial render there are created subscriptions properly

<img width="2337" alt="Screenshot 2023-06-28 at 12 03 53" src="https://github.com/apollographql/apollo-client/assets/26778061/a26ff5d2-0378-4484-af08-ca6fe3985fab">

2. Now in the component that used `BITMEX-testnet2` i switch to `BITMEX-testnet1` variables (dynamic change by select) and behaviour seems to be correct: 3 subscriptions from `BITMEX-testnet2` are closed, and none new subscription is opened since other component already have for `BITMEX-testnet1`

<img width="630" alt="Screenshot 2023-06-28 at 12 03 57" src="https://github.com/apollographql/apollo-client/assets/26778061/b92adf99-a92d-4694-9319-0f2ba0334173">

3. I switch back to `BITMEX-testnet2` and as expected 3 new subscriptions that was previously closed are opening
<img width="2379" alt="Screenshot 2023-06-28 at 12 04 01" src="https://github.com/apollographql/apollo-client/assets/26778061/7082e068-c445-4a08-9359-6c01c83510b7">

4. Now, the magic starts to happen, I received messages for `bidAskQuote` (for the `BITMEX-testnet1` subscription) it shows up nicely in the component that is currently using that subscription

<img width="2210" alt="Screenshot 2023-06-28 at 12 04 19" src="https://github.com/apollographql/apollo-client/assets/26778061/515c2ec7-3fca-4c8b-b5d2-ad4a3d967514">

5. I am switching back first component (component using currently `BITMEX-testnet2`) to `BITMEX-testnet1` and i thought that 3 subscriptions for `BITMEX-testnet2` would be closed as previously, none of the subscription would be open and the value would be taken from cache - but no, the new subscription is opened:
<img width="2382" alt="Screenshot 2023-06-28 at 12 04 25" src="https://github.com/apollographql/apollo-client/assets/26778061/4419b0ed-f34a-4e6c-a14b-f56e3248a7aa">

The interesting thing is that it is only open for the subscription that already received message, the other 2 ones (`bid`, `ask`) are not opened. This results in 2 opened subscriptions for the exactly same variables:

<img width="2219" alt="Screenshot 2023-06-28 at 12 05 26" src="https://github.com/apollographql/apollo-client/assets/26778061/2acbd75b-6dbf-4570-a806-80739f904e88">

There is no different policies in each subscription, this is super regular subscription without even any extra options

```js
const useBidAskQuote = ({ venueAccount, symbol } : Props) => {
  const {
    data: bidAskQuoteData,
    loading: bidAskQuoteLoading,
    error: bidAskQuoteError,
  } = useBidAskQuoteSubscription({
    variables: {
      venueAccount,
      symbol,
    },
  })

  return {
    bidAskQuoteData,
    bidAskQuoteLoading,
    bidAskQuoteError,
  }
}
```

`useBidAskQuoteSubscription`

is generated subscription from codegen

```js
export function useBidAskQuoteSubscription(
  baseOptions: Apollo.SubscriptionHookOptions<
    BidAskQuoteSubscription,
    BidAskQuoteSubscriptionVariables
  >
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useSubscription<BidAskQuoteSubscription, BidAskQuoteSubscriptionVariables>(
    BidAskQuoteDocument,
    options
  );
}
```

I use latest `3.7.16` `apollo/client` but the error occured also on older versions

### Link to Reproduction

https://github.com/apollographql/apollo-client

**Comment by alessbell** [comment]
Hi @Wozniaxos 👋 

Looks like I've also replied to your thread on Discord, but thanks for opening this issue with more details. I'll repeat what I said there for anyone else who comes across this thread:

Can you confirm that the subscription operation you're passing `useSubscription` contains an `id` field (so the response can be normalized)?

The reason I ask is: if you don't have an `id` or primary key field for that entity, Apollo's `InMemoryCache` can't normalize it, so while each payload will be stored under the `ROOT_SUBSCRIPTION` key in the cache and get overwritten on update, you won't have normalized cached entities.

I realize you can't share the source code directly, but a reproduction would help here - our [error template](https://github.com/apollographql/react-apollo-error-template) has a basic subscriptions set-up which would likely save several steps.

**Comment by Wozniaxos** [comment]
Hi @alessbell thank you for response! I don't have id field in the subscription messages but i've configured cache `keyFields` for the messages like so:

```js
typePolicies: {
    UserResponse: {
      keyFields: ['username'],
    },
    GroupResponse: {
      keyFields: ['name'],
    },
    BidAskQuoteResponse: {
      keyFields: ['venueAccount', 'symbol'],
    },
    BidResponse: {
      keyFields: ['venueAccount', 'symbol'],
    },
    AskResponse: {
      keyFields: ['venueAccount', 'symbol'],
    }
  },
```

it looks cached properly

<img width="1074" alt="Screenshot 2023-06-29 at 12 01 55" src="https://github.com/apollographql/apollo-client/assets/26778061/9db35d65-2184-4624-8c5d-172262b66a94">

**Comment by alessbell** [comment]
Hi @Wozniaxos - I'm curious about the shape of the data stored under the `BidAskQuoteResponse:{"venueAccount":"BITMEX-testmet1","symbol":"BTCUSDT@FOREX@BitMEX"}"` entity that `__ref` is pointing to, but it's difficult to dive in further without a reproduction. Since the subscription back-end is hard to recreate here, sending us a [Replay](https://docs.replay.io/workflows/recording-bug-reports) recording of the issue would be extremely helpful if you're able to. If it contains non-public/sensitive data, feel free to share it privately with me at alessia@apollographql.com :)
