### ISSUE TITLE
useQuery hook becomes slower with more data

### ISSUE THREAD

**Issue by TLaMars** [apollographql/apollo-client#11024]
### Issue Description

Hi!
I can't create a repro because it is for a private project, and that requires a lot of work.
When we are using `useQuery` normally we don't have any problems with the response time. But we are now implementing translations that are coming from the GraphQL api and we are encountering that the `useQuery` hook takes a lot of time next to the network request time before we get the result. Is there something we are missing, or does the `useQuery` hook become slow with larger number of items?

We are currently talking about 300 translations we are getting back, but in the future it can become more like 1000 translations. 

The `useQuery` hook takes about 3 to 4 seconds on average before we get the data back from the hook and the loading state goes from true to false.
<img width="345" alt="Screenshot 2023-06-29 at 11 03 37" src="https://github.com/apollographql/apollo-client/assets/16527824/957e6263-9645-476f-8edf-d91c2865b041">
<img width="339" alt="Screenshot 2023-06-29 at 11 03 08" src="https://github.com/apollographql/apollo-client/assets/16527824/90210961-475f-44c8-8e7c-606372adeee5">

When we compare this to the actual length of the network call to the backend or in the GraphQL Playground from the Backend, we are talking about a 2 to 3 seconds difference in getting the data. These network calls take on average 700-900 milliseconds
_Playground:_
<img width="1858" alt="image" src="https://github.com/apollographql/apollo-client/assets/16527824/7de53c46-a8b4-4a47-9f49-26d250903246">
_In the App:_
<img width="1204" alt="Screenshot 2023-06-29 at 10 54 51" src="https://github.com/apollographql/apollo-client/assets/16527824/38ace17c-b34f-4ded-bf39-46ee7d804027">

We also compared this by using the query function on the client and noticed that this was a lot faster than the `useQuery` hook. It takes as long as the network calls with around 700-900 milliseconds.
<img width="187" alt="Screenshot 2023-06-29 at 11 15 20" src="https://github.com/apollographql/apollo-client/assets/16527824/d8128092-882c-4970-bd69-ff046cdade2f">
<img width="183" alt="Screenshot 2023-06-29 at 11 14 38" src="https://github.com/apollographql/apollo-client/assets/16527824/fcae25e0-6ded-4607-a830-c2b2792f997a">
<img width="195" alt="Screenshot 2023-06-29 at 11 14 15" src="https://github.com/apollographql/apollo-client/assets/16527824/46555683-0fcf-4427-8f1a-f63afcafe3db">

This is how we execute the `useQuery` hook in a component
```tsx
const AemContentConnector: React.FC = () => {
  const { locale } = useLanguage();
  const { data, loading, refetch } = useQuery(QueryGetKeyValueList, {
    context: {
      headers: {
        "Accept-Language": locale,
      },
      henk: true,
    },
    fetchPolicy: "network-only",
  });

  return (
    <SomeComponents />
  );
};
```

And this is the query
```ts
import { graphql } from "gql/codegen/gql";

export const QueryGetKeyValueList = graphql(`
  query GetKeyValueList {
    getKeyValueList {
      items {
        key
        value
      }
    }
  }
`);
```

### Link to Reproduction

https://github.com/apollographql/apollo-client

**Comment by bignimbus** [comment]
Hi @TLaMars 👋🏻 thanks for bringing this to our attention!  Can you give a little more information about the runtime?  Are you using React Native or is this in a web browser?  Is that `35.7kB` value the size of the server response?  What happens when you change `network-only` to `no-cache` for the `fetchPolicy`?

**Comment by TLaMars** [comment]
Hi @bignimbus!

Thanks for your response! It is indeed a React Native application we are working on and encountering this issue.
The `35.7kB` is the value size of the server.

When changing to the `fetchPolicy` `no-cache` or no fetchPolicy at all we don't see a drop in response time from the `useQuery` hook unfortunately.
![Screenshot 2023-06-30 at 10 22 07](https://github.com/apollographql/apollo-client/assets/16527824/d622bde7-b8f9-4938-b58c-384a729af8b8)
![Screenshot 2023-06-30 at 10 14 02](https://github.com/apollographql/apollo-client/assets/16527824/3d7a490f-738b-4300-b3f5-66685c76ad49)
![Screenshot 2023-06-30 at 10 14 52](https://github.com/apollographql/apollo-client/assets/16527824/d5fa57fa-8fa5-4064-a2db-4a92942360ad)

**Comment by phryneas** [comment]
Could you try to create a reproduction based on https://github.com/apollographql/rn-apollo-client-testbed and share that?

**Comment by TLaMars** [comment]
@phryneas from within the company I work it is not allowed to share any API or code related stuff, which makes it really hard to make a reproduction repo. I can share a part of the package.json if that would help?

**Comment by phryneas** [comment]
You could try to create a reproduction on your side and only share a performance profile (instructions in the linked repo) with us, or create a fake api with similar response sizes and build a reproduction against that. 

But in the end, if we don't have anything tangible from you, we can only make educated guesses - and even for that, we are not really getting enough information from you - I'm sorry :/

**Comment by TLaMars** [comment]
Hi!
We found the issue, and it is not related to the `useQuery` hook.
It takes that long because of React and how it updates/rerenders the app.

Thanks for your help!
