### ISSUE TITLE
useFragment returns data {} after entity was evicted

### ISSUE THREAD

**Issue by slivlikh** [apollographql/apollo-client#11039]
Hello Apollo team.
My case, I need to render list of entities, to get array of ids I use useQuery, to get entity data I use useFragment.
I need to delete entity item, I invoke cache.evict in the mutation update hook,  first was updated the component with removed entity and I got data {} from useFragment, and only then was updated parent component with query.
 
If I substituse useFragment on useQuery to get entity data than will be updated only parrent component without triggering component with removed entity. 
I use @apollo/client: 3.7.16
Is this expected behaviour?
[Link to reproduction](https://codesandbox.io/s/apollo-todo-list-forked-r3dv5n)

**Comment by alessbell** [comment]
Hi @slivlikh 👋

@phryneas worked on the fix here and I've confirmed it fixes your reproduction using the snapshot release: https://codesandbox.io/s/apollo-todo-list-forked-vh3gwm?file=/src/apollo/resolvers/index.js

This fix will be released in `3.8.0` which will be out in the next week or so. Closing this issue but thanks for reporting and let us know if anything else comes up!
