### ISSUE TITLE
Discussion on Storing ApolloClient in React Context to Manage TokenPair State

### ISSUE THREAD

**Issue by magrinj** [apollographql/apollo-client#11056]
Hello everyone,

I'm currently working on an open source CRM called [Twenty](https://github.com/twentyhq/twenty), where I am considering storing `ApolloClient` in React's context, mainly to maintain the state of our token pair (somewhat similar to a `recoilState`). This approach is under consideration due to the need to prevent recreating the entire ApolloClient instance every time the token pair changes. 

Here is a snippet of the `ApolloClient` instance creation, made using a custom `ApolloFactory`. The `ApolloFactory` used here is a customized factory function that creates an ApolloClient instance, which sets up necessary links like errorLink, authLink, and retryLink, and includes some additional configurations such as token pair management and debug mode:

```typescript
export function useApolloFactory() {
  const apolloRef = useRef<ApolloFactory<NormalizedCacheObject> | null>(null);
  const [isDebugMode] = useRecoilState(isDebugModeState);

  const [tokenPair, setTokenPair] = useRecoilState(tokenPairState);

  const apolloClient = useMemo(() => {
    apolloRef.current = new ApolloFactory({
      uri: `${process.env.REACT_APP_API_URL}`,
      cache: new InMemoryCache({
        typePolicies: {
          CommentThread: {
            fields: {
              commentThreadTargets: {
                merge(
                  existing: CommentThreadTarget[] = [],
                  incoming: CommentThreadTarget[],
                ) {
                  return [...incoming];
                },
              },
            },
          },
        },
      }),
      defaultOptions: {
        query: {
          fetchPolicy: 'cache-first',
        },
      },
      initialTokenPair: tokenPair,
      onTokenPairChange(tokenPair) {
        setTokenPair(tokenPair);
      },
      onUnauthenticatedError() {
        setTokenPair(null);
      },
      extraLinks: [],
      isDebugMode,
    });

    return apolloRef.current.getClient();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [setTokenPair, isDebugMode]);

  useUpdateEffect(() => {
    if (apolloRef.current) {
      apolloRef.current.updateTokenPair(tokenPair);
    }
  }, [tokenPair]);

  return apolloClient;
}
```

In this implementation, I need to handle situations such as token renewals due to expiry or errors. Additionally, I'm planning to add a websocketLink later, and I am wary that recreating the client might cause connectivity issues or disrupt ongoing connections. It's why I'm avoiding it for now.

One concern I have is that this approach may introduce a memory leak if the client is recreated each time the token pair changes. This would undoubtedly impact the performance of the application.

I'm curious to hear your thoughts on these points:
- Is it a recommended practice to put an imperative API like ApolloClient into the React context?
- Is it necessary or beneficial to avoid the re-creation of the entire ApolloClient when the tokenPair changes?
- Could this potentially lead to a memory leak, and if so, how can it be mitigated?

I appreciate any insight or advice you could provide on these matters.

Thank you!

**Comment by phryneas** [comment]
> * Is it a recommended practice to put an imperative API like ApolloClient into the React context?

Tons to unpack here :)

Generally: you never store anything in Context. Context is a transportation mechanism, not a storage mechanism. You would store something in local component state and then use Context to pass it down to other components. 
With that background: 
That's what `ApolloProvider` does: it uses Context to pass your client instance down to your components.

So I'm not 100% sure what you want to do here to be honest?

>     * Is it necessary or beneficial to avoid the re-creation of the entire ApolloClient when the tokenPair changes?

You should probably never recreate ApolloClient, period. But usually you shouldn't require this many bells and whistles for that.  
Assume this:

```js
function ApolloClientWrapper(props){
  const clientRef = useRef()
  if (!clientRef.current) {
    clientRef = new ApolloClient({ /* options */ })
  }
  return <ApolloProvider client={clientRef.current}>{props.children}</ApolloProvider>
}
```

What problems do you need to solve that this (recommended approach if you want to store your client within a component)  doesn't give you? What's the purpose of all the factories?

>     * Could this potentially lead to a memory leak, and if so, how can it be mitigated?

I think let's take a little step back and see if you need this in the first place :)

**Comment by magrinj** [comment]
Hey @phryneas ,

Thank you for your enlightening explanation about the usage of Context in React. I realize my earlier phrasing might have been misleading. What I intended to discuss was about initiating the ApolloClient within a hook or render function, not about storing anything directly in the Context.

In our project, we use a custom abstraction function, the ApolloFactory, which sets up the ApolloClient with all necessary links, handles authentication errors, and manages token renewals.

In our team, we've had some divergent viewpoints about how to manage the ApolloClient instance. The current implementation uses useRef to hold the instance of the ApolloClient, and then useUpdateEffect is used to directly update the tokenPair in the ApolloFactory instance. This way, we avoid recreating all the links every time the token pair changes.

However, some team members are advocating for a different approach. They suggest that we should use a useMemo and let the ApolloClient be rebuilt every time the tokenPair changes, contrary to the current implementation.

Your response clarifies a lot about the recreation of ApolloClient. It was particularly helpful to understand that the ApolloClient should not be unnecessarily recreated, especially when the tokenPair changes.

Thank you once again for your guidance. We will consider these valuable points as we move forward with our project.

**Comment by phryneas** [comment]
> However, some team members are advocating for a different approach. They suggest that we should use a useMemo and let the ApolloClient be rebuilt every time the tokenPair changes, contrary to the current implementation.

You definitely should not do this. You also should never store anything that should not get lost in a `useMemo` - React might at any point in time decide to destroy and recreate it. `useMemo` is just a perfomance optimization, but not a guarantee of a constantly stable value.  
Using either `useState`, or `useRef` for this is fine.

I want to pick up on this one, because it seems to be at the core of your problem:

> This way, we avoid recreating all the links every time the token pair changes.

Have you considered putting the token into the `context` and making it available to your links this way? That is the recommended way of making changing data available to links. You should not need to recreate your links just because a value changes.

**Comment by phryneas** [comment]
@magrinj I believe your questions here have been answered, so I'll close the issue - but feel free to reopen if you have any more follow-up questions!
