### ISSUE TITLE
"WebSocket is not defined" in NodeJS

### ISSUE THREAD

**Issue by jarkt** [apollographql/apollo-client#11063]
### Issue Description

If you use the Apollo Client in NodeJS you have to declare the WebSocket implementation like so:

```
const wsLink = new GraphQLWsLink(createClient({
    url: "wss://project.local/graphql",
    webSocketImpl: WebSocket,
}))
```

But in many cases I've got the error message "ReferenceError: WebSocket is not defined".
I followed the trace and noticed that the function isLikeErrorEvent uses "WebSocket.CLOSED", which results in an error.
You can handle this by setting `global.WebSocket = WebSocket` before.

### Link to Reproduction

x

**Comment by bignimbus** [comment]
Thanks for posting this tip here @jarkt! I'm going to close this issue since there's nothing actionable for the maintainers.  Have a good weekend!
