### ISSUE TITLE
"cache-and-network" is missing from `FetchOptions` type-definition.

### ISSUE THREAD

**Issue by ryami333** [apollographql/apollo-client#11077]
### Issue Description

It's mentioned even in the [doc-block that precedes the definition](https://github.com/apollographql/apollo-client/blob/87823ccd86b129e7a0ae8b9690dd887766ff9c0f/src/core/watchQueryOptions.ts#L19), but for some reason the value is omitted from the enum itself.

### Link to Reproduction

Not applicable

### Reproduction Steps

```ts
const client = new ApolloClient({
  // …
  defaultOptions: {
    query: {
      fetchPolicy: "cache-and-network", // error TS2322: Type '"cache-and-network"' is not assignable to type 'FetchPolicy | undefined'
    },
  },
});
```

**Comment by phryneas** [comment]
That's because `'cache-and-network'` does not work with `client.query` and would cause an error there. `client.query` returns a single result, so it cannot return from two sources.

If you want to set `fetchPolicy` to `'cache-and-network'`, you need to set that for `watchQuery` instead:
```js
const client = new ApolloClient({
  // …
  defaultOptions: {
    watchQuery: {
      fetchPolicy: "cache-and-network",
    },
  },
});
```
