### ISSUE TITLE
Interface 'ExecutionResult<TData>' incorrectly extends interface 'ExecutionResult<{ [key: string]: any; }, { [key: string]: any; }>'.

### ISSUE THREAD

**Issue by shaheedac** [apollographql/apollo-client#11076]
### Issue Description

node_modules/apollo-link/lib/types.d.ts:5:18 - error TS2430: Interface 'ExecutionResult<TData>' incorrectly extends interface 'ExecutionResult<{ [key: string]: any; }, { [key: string]: any; }>'.

  Types of property 'data' are incompatible.
    Type 'TData | null | undefined' is not assignable to type '{ [key: string]: any; } | null | undefined'.
      Type 'TData' is not assignable to type '{ [key: string]: any; } | null | undefined'.
        Type 'TData' is not assignable to type '{ [key: string]: any; }'.

using angular  "@angular/cli": "~15.2.9" , "typescript": "~4.9.5", "apollo-link": "^1.2.8", "apollo-angular-link-http": "^1.11.0",
"graphql": "^15.8.0"

**Comment by phryneas** [comment]
Likewise, you probably want to use `apollo-angular/http` instead of `apollo-angular-link-http` - that one is not maintained by us, but has in a similar fashion not been updated for three years and moved into the other package.
