### ISSUE TITLE
What does this error message mean?: Invariant Violation: 37 

### ISSUE THREAD

**Issue by john1625b** [apollographql/apollo-client#11075]
I tried googling for this error but nothing showed up specifically for "Invariant 37". It's a vague error message so I'm wondering what it could be. 

I don't think my code is relevant since I just need to know what that error is actually about. If a snippet of my code is absolutely necessary, let me know.

**Comment by jerelmiller** [comment]
@john1625b would you be able to provide a bit more context and how you're seeing this error? What version of apollo client you're using, the full error message you're seeing in the console, etc?

**Comment by john1625b** [comment]
@jerelmiller 

I found [this repo](https://github.com/apollographql/invariant-packages#error-codes) that shows you how to decipher the invariant error codes. 

relevant snippet:
> node_modules/@apollo/client/invariantErrorCodes.js

in the case of Invariant 37:

>  37: {
    file: "@apollo/client/react/parser/index.js",

    node: invariant(operation.type === type, "Running a ".concat(requiredOperationName, " requires a graphql ") +
        "".concat(requiredOperationName, ", but a ").concat(usedOperationName, " was used instead."))
  },
  
In my case, I was using a mutation for the useQuery hook. Closing
