### ISSUE TITLE
UI flickering with relayStylePagination and cache-and-network

### ISSUE THREAD

**Issue by malininss** [apollographql/apollo-client#11087]
### Issue Description

I am using relayStylePagination and fetchPolicy: 'cache-and-network'.

I want to have the following caching logic: first, data from the cache is displayed, then a request to the server is made. After receiving a response from the server, I update the data in the component.

I am encountering a problem when I have a lot of data in the cache (for example, 20 items), but from the component, I am requesting only a portion (for example, for the first page only the first 5 items). Initially, ALL items from the cache are displayed, and only after receiving the server response, the data is updated and only the necessary part is displayed. Because of this, there is a certain "jump" of the page and it looks like a UI bug.

I have prepared an example with a bug: https://codesandbox.io/s/apollo-cache-pagination-bug-6mq2xl

On the page https://www.apollographql.com/docs/react/pagination/cursor-based/#relay-style-cursor-pagination I see the paragraph:

> Note that the relayStylePagination function generates a field policy with a read function that simply returns all available data, ignoring args, which makes relayStylePagination easier to use with fetchMore. This is a non-paginated read function. There's nothing stopping you from adapting this read function to use args to return individual pages, as long as you remember to update the variables of your original query after calling fetchMore.

But in InMemoryCache, the read function in fetchPolicy is not called every time I fetch items, but only once AFTER receiving the server response. Thus, I cannot control how much data I need to display by customizing this read function.

In the component itself, I cannot trim the items to the necessary amount because I cannot know exactly when to trim them. The only solution to this problem in the context of working with the current version of Apollo that I came up with is: on the first render of the component, once fetch the cache and modify the data in the cache according to how much data on the page we want to see.

```
export const useSlicePaginationCache = ({
  // the object to determine exactly which property of the cache we are updating
  objectWithType,
  // the name of the property to update (for example, deposits)
  cacheFieldToUpdate,
  // how many items can be on the page
  perPage,
}) => {
  // we can only update the cache once on the first render
  const wasSlicedRef = useRef(false);
  const client = useApolloClient();

  useEffect(() => {
    if (!wasSlicedRef.current && objectWithType) {
      client.cache.modify({
        id: client.cache.identify(objectWithType),
        fields: {
          [cacheFieldToUpdate]: (dataInCacheWithEdges) => {
            const newData = {
              ...dataInCacheWithEdges,
              // we cut the number of items to what is needed on the first
              edges: dataInCacheWithEdges.edges.slice(0, perPage - 1),
            };

            return newData;
          },
        },
      });

      wasSlicedRef.current = true;
    }
  }, [cacheFieldToUpdate, perPage, client.cache, objectWithType]);
};
```

But this solution seems very hacky.
How is it intended to work with data in such cases?

### Link to Reproduction

https://codesandbox.io/s/apollo-cache-pagination-bug-6mq2xl

### Reproduction Steps

1. Open the page. Initially, 5 items are displayed.
2. Click on the fetchMore button, now 10 items are displayed.
3. Click on the ToggleNamesList button.
4. Click on the ToggleNamesList button again.
5. Initially, 10 items are displayed, and then, after the request is completed, 5 items are displayed.

**Comment by bignimbus** [comment]
Hi @malininss 👋🏻 thanks for opening this issue!  Out of the box, this isn't supported by `relayStylePagination` and should be implemented in user space.  There may be a simpler way than the workaround you shared.  Here are some ideas the team came up with:

1. Consider a virtualized element list like [this](https://github.com/TanStack/virtual) or [that](https://github.com/bvaughn/react-virtualized) or maybe [this](https://github.com/bvaughn/react-window)?
2. In your app code, consider combining `useMemo` with an `Array.slice` along the lines of your code snippet

I hope that helps, let us know!

**Comment by malininss** [comment]
Hi @bignimbus . Thank you very much for the answer! Virtual lists are a bit of a different topic.
At the moment, I solved the problem in the following way:

1. I created a state called `isFirstPage`, which is true by default but changes to false when calling on `fetchMore`.
2. In the component, using `useMemo` with dependencies `data` (response from the server) and `isFirstPage`, I slice the result if we are on the first page.

Here's the fixed code from the reproduction above:
https://codesandbox.io/s/apollo-cache-pagination-bug-fixed-5yvqsr?file=/src/NamesList.jsx

In my real project, I use auto-generated code with the `graphql-codegen` library.

There I rewrote the global creation of the generated hooks, where I implemented the slicing logic at the level of hook generation, without the need to create code with data slicing into each component.

However, all of this feels like a workaround. It seems that when requesting the first page, all the information from the cache shouldn't be displayed.

I would be very grateful if you could explain why it is currently implemented this way in Apollo, and whether there are plans for adjustments in the future. Thank you!

**Comment by bignimbus** [comment]
Thanks a bunch for sharing @malininss, that looks great!  I’m not 100% sure how to respond to the question of why it was implemented this way beyond what’s written in the docs so hopefully the following is helpful.  Pagination can be simple or complex depending on how frequently the client fetches fresh data from the server and how volatile the paginated list is.  The problem space is so broad that any assumptions or opinions we bake into the library will impact different applications in different ways.  In this scenario, the UI is not just concerned with the correctness of the underlying data but also the way it’s presented to the user.  You can modify the data so that it aligns with what you want to show to the users, or you can selectively hide a portion of the UI.  Fetch policies, cache evictions, and other aspects of the Apollo Client API can help if you want to do the former, and aspects of the React API can help do the latter.  That said, we’re open to specific suggestions as to what could be updated in the docs or API to better serve folks trying to do what you’re doing!
