### ISSUE TITLE
[3.8] Introduce `skipToken` API in Suspense hooks

### ISSUE THREAD

**Issue by alessbell** [apollographql/apollo-client#11093]
### Issue Description

- the `skip` option in `useSuspenseQuery` and `useBackgroundQuery` still exists as a migration path from `useQuery` but is immediately deprecated
- `skipToken` provides a way to skip a query by making both the query document optional (if no options are passed to the hook) via `skipToken` or allowing `skipToken` as a variable

### Link to Reproduction

N/A

**Comment by jerelmiller** [comment]
This was completed with #11112
