### ISSUE TITLE
Passing extra variables using usequery

### ISSUE THREAD

**Issue by darklord77** [apollographql/apollo-client#11097]
Hello, I have a problem using the last version of apollo client, while I was using apollo client v2 I could send as much variables not related to the queries as I wanted so the backend could get this variables and work with them, but since the last version iI could only send variables that are required by the queries.

Is there a way I can send variables not related to the query so the backend could get them? or this is a deprecated behaivour and should look in other ways to pass this informacion? 
This can serve as an example of hat i try to accomplish:

Using this query:
`
gql` query GetUsers { getUsers { status result{data{allDataHere}}]`

`
I try to send variables using this:

`
const responseData = useQuery<any, any>(queryGetUsersHere, {client:client, variables:{variableIwantToSend:{data1:01, data2:02, data3:03}},...
`

But the variable "variableIwantToSend" is not sent, but in apollo cliente v2 this works find and the variable is sent.
Thanks for your help

**Comment by phryneas** [comment]
Going by the [Graphql Specification](https://spec.graphql.org/October2021/#sec-All-Variables-Used) your server should throw an error on any unused variables that we send to it - so to have the request adhere to the spec, we have to remove the variable.  
Can you work around this setting request headers instead?

**Comment by darklord77** [comment]
I see, so my only option will be or use the apollo version v2 or start passing the variables in the header.

I will have to ask my backend team if this is viable and if it is I will move the variables to the header.

Thanks for your help

**Comment by phryneas** [comment]
@darklord77 sorry I didn't get to replying you any more yesterday. 
I've taken another look - you might want to use the `includeUnusedVariables` option to `HttpLink`.

**Comment by darklord77** [comment]
That is exactly what I needed :) Thanks a lot
