### ISSUE TITLE
Getting cors error while a similar another query is running perfectly

### ISSUE THREAD

**Issue by dawudarif** [apollographql/apollo-client#11110]
```
const client = new ApolloClient({
  cache,
  link: new HttpLink({
    uri: 'http://localhost:4000/graphql',
    credentials: 'include',
  }),
});

client
  .query({
    query: gql`
      query MyQuery {
        tasks {
          id
          text
        }
      }
    `,
  })
  .then((result) => console.log(result));
```
 the client.query returns data but when i run a query in the browser as  
` const { data: taskQuery, error } = useQuery(query);`
it will give me the console error basically saying network error and in the network tab only it will give a CORS error.
One query works and another doesn't when both of the queries are running at the same instance.

**Comment by jerelmiller** [comment]
Hey @dawudarif 👋 

Since this appears to be similar to #11106, let's continue the conversation over in that issue.
