### ISSUE TITLE
How does the performance of the useFragment hook compare to useQuery?

### ISSUE THREAD

**Issue by brianmmorton** [apollographql/apollo-client#11118]
Wondering if anyone has done investigation into performance of these two hooks. I'd assume that this unlocked performance benefits in two areas: CPU/memory usage and network request waterfalls (due to using useBackgroundQuery instead of multiple useQuery's). Anyone done research on this?

**Comment by brianmmorton** [comment]
Hi @alessbell. Thank you so much for the thoughtful response. This is excellent. For context, my team is considering switching from Apollo to Relay to unlock the performance benefits of useFragment in Relay. It's a major improvement for Apollo to support this, and we are now going to stick with Apollo until these experimental hooks are released so that we can utilize them before making a decision. In most cases for our application, we render leaf nodes that are keyed by id, like you mentioned, and use useQuery hooks with cache-only fetch policies to avoid waterfall network requests. Using useFragment will make this much easier, and excited about the performance benefits. Thank you!

**Comment by alessbell** [comment]
@brianmmorton very glad to hear you'll be trying out the new hooks! You may have seen 3.8 was released on Monday, so all of those APIs are now fully supported and marked stable.

Our team is active on [our Discord](https://discord.gg/graphos) in the frontend channel if you ever have general comments/questions. I'm going to go ahead and close this issue out, but looking forward to any other thoughts/feedback you may have!
