### ISSUE TITLE
Unity returns "400 (Bad Request) Error" on sending login-mutation to local graphql-server

### ISSUE THREAD

**Issue by lnmr24** [apollographql/apollo-client#11155]
hey, i try to login into my local graphql-server from unity. the mutation works from apollo-client and postman, but with the unity.webrequest i get 2 errors.

the first one:

`Network error: HTTP/1.1 400 Bad Request
UnityEngine.Debug:LogError (object)
GraphApi/<LoginMutation>d__3:MoveNext () (at Assets/GraphApi.cs:61)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)
`

and the second:

`Response body: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>SyntaxError: Unexpected token % in JSON at position 0<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at createStrictSyntaxError (C:\snapshot\agent\_work\43\s\src\PLF\Exe\Services\GraphQL\NodeJsServer\node_modules\body-parser\lib\types\json.js:160:10)<br> &nbsp; &nbsp;at parse (C:\snapshot\agent\_work\43\s\src\PLF\Exe\Services\GraphQL\NodeJsServer\node_modules\body-parser\lib\types\json.js:83:15)<br> &nbsp; &nbsp;at C:\snapshot\agent\_work\43\s\src\PLF\Exe\Services\GraphQL\NodeJsServer\node_modules\body-parser\lib\read.js:128:18<br> &nbsp; &nbsp;at AsyncResource.runInAsyncScope (node:async_hooks:203:9)<br> &nbsp; &nbsp;at invokeCallback (C:\snapshot\agent\_work\43\s\src\PLF\Exe\Services\GraphQL\NodeJsServer\node_modules\raw-body\index.js:231:16)<br> &nbsp; &nbsp;at done (C:\snapshot\agent\_work\43\s\src\PLF\Exe\Services\GraphQL\NodeJsServer\node_modules\raw-body\index.js:220:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (C:\snapshot\agent\_work\43\s\src\PLF\Exe\Services\GraphQL\NodeJsServer\node_modules\raw-body\index.js:280:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (node:events:525:35)<br> &nbsp; &nbsp;at endReadableNT (node:internal/streams/readable:1358:12)</pre>
</body>
</html>`

and here is the c# code:

`UnityEngine.Debug:LogError (object)
GraphApi/<LoginMutation>d__3:MoveNext () (at Assets/GraphApi.cs:64)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)here`
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Networking;
using TMPro;
using System.Net.Http;
using System;
using System.Threading.Tasks;
using static Unity.IO.LowLevel.Unsafe.AsyncReadManagerMetrics;
using static UnityEditor.Progress;
using static UnityEditor.ShaderData;
using System.Drawing;
using Unity.VisualScripting;

public class GraphApi : MonoBehaviour
{
    public TextMeshProUGUI text;
     public class BypassCertificate : CertificateHandler
    {
        protected override bool ValidateCertificate(byte[] certificateData)
        {
            // Bypass-Zertifikatvalidierung
            return true;
        }
    }
    void Start()
    {
        StartCoroutine(LoginMutation());
    }

    IEnumerator LoginMutation()
    {
        Debug.Log(@"""" == "\"");

        string graphqlEndpoint = "https://notebook65/graphql/";
        string mutation = @"mutation Login {
                   login(username: ""admin"", password: ""xxx"") {
                        token
                        error {
                                 code
                                 description
                              }
                          }
                    } ";

          string jsonRequestBody = "{\"mutation\" : \"" + mutation + "\"}";
          Debug.Log(jsonRequestBody);
          text.text = jsonRequestBody;

          using UnityWebRequest www = UnityWebRequest.Post(graphqlEndpoint, jsonRequestBody);

          //www.SetRequestHeader("Accept", "application/json");
          www.SetRequestHeader("Content-Type", "application/json");

          // Deaktivieren der SSL-Verifikation
          www.certificateHandler = new BypassCertificate();

          yield return www.SendWebRequest();

          if (www.result != UnityWebRequest.Result.Success)
          {
              Debug.LogError("Network error: " + www.error);
              if (!string.IsNullOrEmpty(www.downloadHandler.text))
              {
                  Debug.LogError("Response body: " + www.downloadHandler.text);
              }
          }
          else
          {
              string responseBody = www.downloadHandler.text;
              Debug.Log("Response body: " + responseBody);
              text.text = responseBody;
          }
      }
  }`

I have tried a lot of different versions of the query s, whether with "query" or "mutation", upper or lower case, but always get the same error.

**Comment by jerelmiller** [comment]
Hey @lnmr24 👋 

This repo handles the TypeScript `@apollo/client` npm package, so anything to do with Unity or C# is not something we handle here. Are you sure this issue was opened in the right repo? I'm not quite sure I'm seeing anything actionable on our end.
