### ISSUE TITLE
my watchquery refetchs after updating a fragement and removes all the pagination

### ISSUE THREAD

**Issue by marwanknows** [apollographql/apollo-client#11158]
i have a watchquery + fetchmore with the same query but when i update a fragment after mutation it removes all the pagination and restart the query from page 0 since i use relayStylePagination(). how can i stop the query from removing the pagination data like in cache evict

**Comment by jerelmiller** [comment]
Hey @marwanknows 👋 

Would you be able to provide a more detailed reproduction? Its difficult to recommend a solution without knowing how you've set this up in your application.

`relayStylePagination` is only going to work with whats in the cache, so if your mutation is overwriting all the data for that field in the cache, it might result in what you're seeing here. About the only thing I can recommend here without seeing more code is to ensure your mutation merges the result with the existing data in the cache for this paginated field to ensure it doesn't overwrite what you've already loaded via pagination. Not sure if thats helps any or not!
