### ISSUE TITLE
Elements in `graphQLErrors` not `instanceof GraphQLError`

### ISSUE THREAD

**Issue by rottbers** [apollographql/apollo-client#11168]
### Issue Description

The elements in `ApolloError.graphQLErrors` does not seem to be an instance of `GraphQLError` from [`graphql`](https://www.npmjs.com/package/graphql) as the typing indicates, instead it's a plain object. Perhaps intentional for good reason but in that case should the typing be updated?

```tsx
import { onError } from '@apollo/client/link/error';
import { GraphQLError } from 'graphql';

const errorLink = onError(({ graphQLErrors }) => {
  if (graphQLErrors) {
    for (const graphQLError of graphQLErrors) {
        console.log(graphQLError instanceof GraphQLError); // false, but I would expect true
      }
    }
  }
);
```

### Link to Reproduction

https://codesandbox.io/s/laughing-sky-mqx7j7?file=/src/index.jsx

**Comment by jerelmiller** [comment]
@bignimbus if I'm understanding correctly, our [types](https://github.com/apollographql/apollo-client/blob/5951f6fba5aa1be3acfef2c01b9a4c2eed336d3a/src/errors/index.ts#L20) indicate the array of errors should be a list of `GraphQLError` (which is an actual error class exported from the `graphql` package), but its not, hence the `instanceof` check failing here.

@rottbers does that sound correct?

If that is the case, I think we have a bug with either our types here, or we need to wrap those raw object values and make them each a `GraphQLError` instance to match the type.

**Comment by rottbers** [comment]
Yep, it all makes sense except the type 🙂. Apart from being typed as a class, there are required keys (e.g. `name`, `toJSON`) on the `GraphQLError` class that doesn't exist on the plain object so the shape isn't fully honored.

```ts
type GetRequiredKeys<T> = {
  [K in keyof T as undefined extends T[K] ? never : K]: T[K];
};

type RequiredKeys = keyof GetRequiredKeys<GraphQLError>; // typeof Symbol.toStringTag | "extensions" | "toString" | "toJSON" | "name" | "message"
```

Perhaps using `GraphQLFormattedError` as the type for the object would be appropriate?

**Comment by bignimbus** [comment]
Thanks @jerelmiller and @rottbers!  My understanding was that `instanceof` would be executed at runtime in JavaScript so it wouldn't necessarily be aware of our type annotations, whether correct or not.  I don't think we're calling `new GraphQLError` or the equivalent outside of our unit tests.
