### ISSUE TITLE
is possible nested fragments query in apollo client? it is can in apollo studio.

### ISSUE THREAD

**Issue by lisiver** [apollographql/apollo-client#11182]
Need help or want to talk all things Apollo Client? Issues here are reserved for bugs, but one of the following resources should help:

Hello, I am a frontend developer working with Apollo Client and graphql-codegen to use GraphQL. In Apollo Studio, when I write the query below, it fetches the values correctly. However, strangely enough, when I craft the query in the frontend code using Apollo Client (graphql-tag), it doesn't work as expected. Is this the intended behavior? Or could it be a bug with Apollo Client or graphql-tag?

```
fragment SitemapFields_Sitemap on Sitemap {
  __typename
  id
  title
}

fragment CommonMenu_iMenu on IMenu {
  id
  title
  description
  sitemap {
    id
    title
  }
  parent {
    id
    title
  }
}

fragment boardMenuFields_BoardMenu on BoardMenu {
  __typename
  id
  permissionViewMenuGroups {
    id
    title
  }
  board {
    id
    title
    slug
    description
    isMentorBoard
  }
}

fragment simpleMenuFields_SimpleMenu on SimpleMenu {
  __typename
  id
  permissionViewMenuGroups {
    id
    title
  }
}

fragment shortcutMenuFields_ShortcutMenu on ShortcutMenu {
  __typename
  id
  url
  permissionViewMenuGroups {
    id
    title
  }
}

fragment OnMenu_iMenu on IMenu {
  ...CommonMenu_iMenu
  ... on BoardMenu {
    ...boardMenuFields_BoardMenu
  }
  ... on SimpleMenu {
    ...simpleMenuFields_SimpleMenu
  }
  ... on ShortcutMenu {
     ...shortcutMenuFields_ShortcutMenu
  }
}

query gqlCommunitySitemaps {
  sitemaps {
    nodes {
      ...SitemapFields_Sitemap
      children {
        ...OnMenu_iMenu
        children {
          ...OnMenu_iMenu
          children {
            ...OnMenu_iMenu
            children {
              ...OnMenu_iMenu
              children {
                ...OnMenu_iMenu
                children {
                  ...OnMenu_iMenu
                }
              }
            }
          }
        }
      }
    }
  }
}
```

* Apollo Discord server: https://discord.gg/graphos
* Apollo GraphQL community forums: https://community.apollographql.com
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by phryneas** [comment]
I suspect some of these are interfaces, and you are not passing `possibleTypes`?

Can you take a look at https://www.apollographql.com/docs/react/data/fragments/#using-fragments-with-unions-and-interfaces and see if that solves your problem?
