### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getObservableQueries')

### ISSUE THREAD

**Issue by darr1s** [apollographql/apollo-client#11192]
### Issue Description

I am currently facing this issue without any what could go wrong. There isn't precaution or hints.

My apollo factory.
https://dpaste.org/qA6F4

![image](https://github.com/apollographql/apollo-client/assets/21124691/bbf0f4b3-f099-44ee-a680-b9580450b56f)

*(Sorry for not able to create a reproduction link. This is really an unique occurence)

### Link to Reproduction

https://dpaste.org/qA6F4

**Comment by simplecommerce** [comment]
> [darr1s](/darr1s)

I have the same issue after updating my @apollo/client to the latest version.
For some reason it seems to be related to `connectToDevTools`.
If I comment it, it works, if I leave it there, it crashes on the client side.
It works if I remove the browser extension and leave it there.
But if I install the browser extension while the option is there, it crashes again.

No idea why.

**Comment by jerelmiller** [comment]
@simplecommerce we added a new [registration mechanism](https://github.com/apollographql/apollo-client/pull/11117) between the client and Apollo DevTools to try and make the connection a bit more robust, but looks like we might need to look at the change a bit closer. Appreciate that nugget of info as that should make it easier for us to narrow down.

@darr1s thanks for reporting this!

**Comment by phryneas** [comment]
I think this is fixed in #11193 
Could you please test this build and report back if it fixes the problem for you?

```sh
npm i @apollo/client@0.0.0-pr-11193-20230905102117
```

**Comment by simplecommerce** [comment]
> 

Seems to work for me on my instance. I did the test by enabling the dev tools and then no errors appeared, I put the latest version back and it appeared again, so it seems ok for me.

**Comment by jerelmiller** [comment]
Hey all 👋 

A fix for this has been published in [v3.8.3](https://github.com/apollographql/apollo-client/releases/tag/v3.8.3). Thanks for reporting the issue!
