### ISSUE TITLE
Do we really need `cache-and-network`?

### ISSUE THREAD

**Issue by toknT** [apollographql/apollo-client#11197]
It's 'return result from cache first (if it exists), then return network result once it's available.', but I had been blamed by boss and replase it with `network-only` not only once .lol...

**Comment by jerelmiller** [comment]
Hey @toknT 👋 

Appreciate the feedback, but this is something unlikely to change. There are use cases for it and we certainly have developers that use it successfully. If you have more detail to share feel free. Have a great day!

**Comment by toknT** [comment]
@jerelmiller . yeah I am a programmer and unserstand `cache` so `cache-and-network` is preference too. But **explaining what's cache** to my boss(bosses) is a hard work ... (and afer some days later you need explain it again, if they not accepted then should change to `network-only`,I can't understand why my china bosses don't want use the data in cache,even it's the rich text data of post,lol)
