### ISSUE TITLE
Enable `strict` setting in tsconfig.json

### ISSUE THREAD

**Issue by jerelmiller** [apollographql/apollo-client#11199]
### Issue Description

Our codebase does not currently use the `strict` setting for our codebase. Enabling this causes our codebase to fail due to the [`strictFunctionTypes` rule](https://www.typescriptlang.org/tsconfig#strictFunctionTypes).

As a best practice, we should be using `strict` to avoid subtle bugs that may arise without this enabled.

### Link to Reproduction

The codebase

### Reproduction Steps

Add `strict: true` to `tsconfig.json` and watch all the tests fail due to TS issues (primarily with `src/utilities/graphql/transform.ts`).

**Comment by billnbell** [comment]
you van ignore node_modules/** in tsconfig.json
