### ISSUE TITLE
Add typePolicies after ApolloClient initialization

### ISSUE THREAD

**Issue by DiRover** [apollographql/apollo-client#11218]
Hello, I need to add config with typePolicies to cache after ApolloClient was initialized.

For example:

```
import { ApolloClient, InMemoryCache } from '@apollo/client';


const client = new ApolloClient({

  cache: new InMemoryCache(),
});
```

After that I need to add config with typePolicies for specific fields, something like this:

```
const client = useApolloClient();
client.cache.config = {...typePolicies} // it doesn't works
```

Is there any way to do this?

**Comment by phryneas** [comment]
Yes, you can call `cache.policies.addTypePolicies`.

**Comment by DiRover** [comment]
@phryneas Thank you so much!

**Comment by phryneas** [comment]
Thank you for bringing it up - we had a PR to put this into the documentation that got kinda buried (https://github.com/apollographql/apollo-client/pull/10967). Your question here finally pushed that forward ;)

I'm going to close this for now - I think your question has been answered :)
