### ISSUE TITLE
How to clear all reactive variables states?

### ISSUE THREAD

**Issue by konrazem** [apollographql/apollo-client#11224]
Is there any method, hook that I can use to reset all reactive variables states in the react application? I understand I cannot use client.resetStore or clearStore as reactive variable is "representing local state outside of the Apollo Client cache". 

I can do
```tsx
const resetAllReactiveVariables = () => {
  myReactiveVariableA({});
  myReactiveVariableB(null);
  myReactiveVariableC(false);

... 52 more
```
however it is not elegant solution and I am not sure if this will make 55 rerenders? 

I am looking something like 
```tsx
const { rv } = useApolloClient()

const resetAllReactiveVariables = () => rv.clear()
```

Where reactive variable state is saved if not in cache?

**Comment by bignimbus** [comment]
Hi @konrazem 👋🏻 thanks for the question!  The functionality you're describing with reactive variables is not currently available in Apollo Client.  You could try using local resolvers to do the same thing, however.  Does that help?

**Comment by konrazem** [comment]
Yes, thank you for your answer. I understand there is no such option and I have to do it one by one.
