### ISSUE TITLE
Use generated types and operations from codegen to update cache after mutation

### ISSUE THREAD

**Issue by rofazayn** [apollographql/apollo-client#11236]
I'm working on an application and I'm using a complex strategy for state management. Therefore, I consider switching to apollo client as my state manager for its built-in caching mechanism.

I'm using codegen to generate hooks to interact with my graphql server, here is an example
```ts
const [createProductMutation, { data, loading, error }] = useCreateOneProductMutation({
    // options here
})
```

According to the documentation I can update the cache by providing the update function to my mutation call, and the hook that I generated also accepts the update method as an option..
```ts
const GET_TODOS = gql`
  query GetTodos {
    todos {
      id
    }
  }
`;

const [addTodo] = useMutation(ADD_TODO, {
    update(cache, { data: { addTodo } }) {
      cache.modify({
        fields: {
          todos(existingTodos = []) {
            const newTodoRef = cache.writeFragment({
              data: addTodo,
              fragment: gql`
                fragment NewTodo on Todo {
                  id
                  type
                }
              `
            });
            return [...existingTodos, newTodoRef];
          }
        }
      });
    }
  });
```

There is an update method in the hook generated by codegen, but according to the docs I have to pass in query/fragment I would like to update, but I am storing my queries in a seperate folder in .graphql files and in graphql language. Any ideas on how I can pass the query without copy pasting it into the update method of the hook everytime?

**Comment by bignimbus** [comment]
Hi @rofazayn 👋🏻 thanks for opening this issue!  Can I ask you to confirm that this is what you want?

```ts
import NEW_TODO_FRAGMENT from "path/to/fragments/NewTodo.graphql";

// ...
const newTodoRef = cache.writeFragment({
  data: addTodo,
  fragment: NEW_TODO_FRAGMENT,
});

```

**Comment by bignimbus** [comment]
Thanks @rofazayn! To be clear, there are some configuration details you may need to add to your bundler of choice in order to make that syntax work. I don't have a snippet off the top of my head but it would involve extracting the text of the GraphQL document, passing it to `gql`, and returning the output.

**Comment by rofazayn** [comment]
@bignimbus sorry for the late reply, I am aware of the configuration that should be added to the bundler, in my case I am using a create-react-app boilerplate, I got around configuring it to import from graphql files without ejecting the CRA by using a package called `graphql.macro`

First I import the loader and pass the path of the query/fragment to it
```ts
import { loader } from 'graphql.macro'

const PRODUCTS = loader('../graphql/queries/products.graphql')
```

and here is an example on how I used it with apollo cache
```ts
await createProductMutation({
  variables: {
    data: {
      name: values.name,
      make: values.make,
      type: values.type,
      description: values.description,
      category: values.category
        ? { connect: { id: values.category } }
        : undefined,
      purchasePrice: values.purchasePrice,
      price: values.price,
      wholesalePrice: values.wholesalePrice,
      halfWholesalePrice: values.halfWholesalePrice,
    }
  },
  update: (cache, { data }) => {
    const newProduct = data?.createOneProduct;
    const existingProducts = cache.readQuery({
      query: PRODUCTS,
    }) as any

    cache.writeQuery({
      query: PRODUCTS,
      data: {
        products: [...existingProducts.products, newProduct]
      }
    })
  }
});
```

Works like a charm, thank you for your help!
PS: I am using `typescript-react-apollo` generated hooks from the guild's codegen https://the-guild.dev/graphql/codegen

**Comment by jerelmiller** [comment]
Hey @rofazayn 👋 

Just wanted to check in, do you need any additional assistance here? Looks like your question may have been resolved from the looks of it so I'm going to go ahead and close out this issue. Let me know if I've made a mistake and I'd be happy to reopen the issue if you need more help here. Thanks!

**Comment by rofazayn** [comment]
> Hey @rofazayn 👋
> 
> Just wanted to check in, do you need any additional assistance here? Looks like your question may have been resolved from the looks of it so I'm going to go ahead and close out this issue. Let me know if I've made a mistake and I'd be happy to reopen the issue if you need more help here. Thanks!

Nope, all good!

Thank you all for your help.
