### ISSUE TITLE
Investigate potential memory leaks in SSR scenarios

### ISSUE THREAD

**Issue by phryneas** [apollographql/apollo-client#11242]
Over time, we had different reports of potential memory leaks in SSR scenarios.

I'm going to spike out for a while and try to create some benchmarks and test scenarios that allow us to detect such cases.

See this Milestone for a list of related Apollo Client PRs: https://github.com/apollographql/apollo-client/milestone/37

Related "external" PRs for visibility:

* https://github.com/benjamn/wryware/pull/553
* https://github.com/benjamn/optimism/pull/615
* ~https://github.com/benjamn/optimism/pull/599~ (superseded)
* https://github.com/benjamn/wryware/pull/568
* https://github.com/benjamn/wryware/pull/569

External discussions: https://github.com/react-native-community/discussions-and-proposals/issues/741

**Comment by rflament** [comment]
Not sure if this is the right place to report this, but we're investigating a memory issue in our next.js server and one of the cause seems to be SSR + useLazyQuery. It looks like even if the options ssr: false is passed to useLazyQuery, the QueryInfo is added to the queries set of QueryManager in the function watchQuery, but since the query is never executed on the server side, it stays in the queries variable forever.

As we use one single instance of ApolloClient, the queries variable of the QueryManager grows until OOM.

**Comment by phryneas** [comment]
@rflament Thank you for the report, I'll look into that!

> As we use one single instance of ApolloClient, the queries variable of the QueryManager grows until OOM.

Independently of the outcome of that - please never do that! You will end up mixing private data of multiple users. When you're doing SSR, please create a new instance of Apollo Client for every request!

**Comment by rflament** [comment]
Thanks! 

In our case the data fetched on the SSR side do not depend on the user, we don't pass the cookies to the apollo client, so the fact that the cache would be reused in all requests seemed a good thing.

**Comment by phryneas** [comment]
I'd still recommend the single store per request, since (as you noticed), Apollo Client isn't really tested for potentially thousands of requests per second on one instance, but only for "normal application usage" scenarios.

**Comment by phryneas** [comment]
@rflament I've moved this out into #11445. This is a bigger conceptual problem and might need quite a lot of reworking of internals, so I can't give you a timeframe for this at this point.

So far, my recommendation is really to create a new AC instance per request.

**Comment by phryneas** [comment]
The beta is out, and we're now waiting for feedback to dial in the right default cache limits.

For everyone who was following along: please give it a try and report back - you can find all the details in this blog post: https://www.apollographql.com/blog/apollo-3-9-beta-feature-spotlight-the-memory-story

**Comment by rflament** [comment]
I confirm that creating a new client instance per request fixed the memory leak, thanks!

**Comment by phryneas** [comment]
Going to close this with the release of 3.9.
