### ISSUE TITLE
switch context between HttpLink and BatchHttpLink

### ISSUE THREAD

**Issue by NikolaySolodukhin** [apollographql/apollo-client#11253]
Hi. Please could help me how setContext Apollo Client in react component. I found close issue https://github.com/apollographql/apollo-link/issues/394 with hoc graphql but it deprecated now. 

I init Apollo client like this
```

      const batchHttpLink = new BatchHttpLink({
            uri: this.baseUri,
            fetch,
            batchInterval: this.batchInterval
        })

        const normalHttpLink = new HttpLink({
            uri: this.baseUri,
            fetch
        })

        const link = new RetryLink().split(
            (operation) => {
                console.log(operation.getContext().noBatch)
                return Boolean(operation.getContext().noBatch)
            },
            normalHttpLink,
            batchHttpLink
        );

        const client: ApolloClient<NormalizedCacheObject> = new ApolloClient({
            link,
            cache,
        });

```

So, my question: how i setContext in react component? 

react-component

```
const withNoBatch = setContext((request, previousContext) => ({
   noBatch: true
}));

```
where I call this method?

**Comment by bignimbus** [comment]
Hi @NikolaySolodukhin 👋🏻 as you noted, `apollo-link-context` is an outdated package so our recommendation would be to update to the latest version of Apollo Client.  What versions of Apollo packages are you using?

**Comment by NikolaySolodukhin** [comment]
Hi, [bignimbus](https://github.com/bignimbus). I use "@apollo/client": "3.7.0". Perhaps my example with setContext don't correct, but I didn't found in docs how to correct setSontext to one request.

**Comment by NikolaySolodukhin** [comment]
I find solution. SetContext in useQuery.
