### ISSUE TITLE
resetStore messes with fetchPolicy and loading state updates

### ISSUE THREAD

**Issue by 522122** [apollographql/apollo-client#11256]
### Issue Description

In 3.8.x refetch causes loading updates. This did not happen in 3.7.17.

### Link to Reproduction

https://codesandbox.io/p/sandbox/friendly-panini-g7dprw

### Reproduction Steps

- have a query with fetchPolicy 'cache-and-network'
- call refetch - loading is updated from false -> true -> false
- call client.resetStore
- call refetch - loading is no longer updating

**Comment by bignimbus** [comment]
Hi @522122 👋🏻  thanks for your patience!  I'm looking at your codesandbox and I'm not seeing a difference between 3.7 and 3.8.  I'm probably missing something obvious, apologies in advance!  If you could give me just a bit more guidance it would help me know what to look for.

**Comment by 522122** [comment]
Hi, thanks for reply, `3.8.6` is working the same way as `3.7.17`. But at the time of opening this, in `3.8.4` refetch caused updates of loading state and after calling `resetStore` it stopped updating loading states. 
My best guess is that it was fixed in https://github.com/apollographql/apollo-client/pull/11235

**Comment by 522122** [comment]
Maybe better examples:

3.8.4
https://codesandbox.io/p/sandbox/friendly-panini-g7dprw?file=%2Fsrc%2Findex.jsx%3A80%2C1

3.8.6
https://codesandbox.io/p/sandbox/dreamy-cherry-yhyg22?file=%2Fsrc%2Findex.jsx%3A36%2C45

**Comment by phryneas** [comment]
As the issue seems to be fixed (thanks for those CodeSandboxes demonstrating that!), are you okay with us closing the issue? :)
