### ISSUE TITLE
It is possible to skip some updates from websocket subscriptions?

### ISSUE THREAD

**Issue by believer-ufa** [apollographql/apollo-client#11257]
Sometimes our server send to client outdated entities data through websocket connection. As I understand from words of our backend devs - this is because of async nature of our current events transport.

So sometimes we face problem with getting firstly last version of some entity and right after it - its previous version.

I would happy to have ability to write such typePolicy, for example, which can read current cached entity data and get its `updatedAt` field value. And after it compare it with this field in data which we just received from websocket subscription. And update local browser cache of Apollo Client only if we received newest version of entity.

As I understand, we can write some custom typePolicy like this:

```ts
const customFieldPolicy: FieldPolicy = {
  // Define how to merge the new data with existing data in the cache
  merge(existing, incoming, options) {
    // Custom logic to merge the data, e.g., by overwriting or merging properties
    return {
      ...existing,
      ...incoming,
    };
  },
};
```

But the problem with such approach - that we work here only with references for objects in normalized cache. So I can get current value of item in cache using `options` object, but I still can't read incoming data because eveything that I have here (as I understand) is only data in current cache and references to objects.

So it is possible to somehow skip some specific update of local cache from subscriptions because we already have in our local cache newest data of this entity? Will be very glad for any good answers. Thank you.

**Comment by phryneas** [comment]
This relates to #11221 - the current answer is no, unfortunately you cannot do that in a fieldPolicy at this point.
You could try to implement this as a link that just swallows a few incoming results by checking if the timestamp and discarding results there.

**Comment by believer-ufa** [comment]
Writing a custom websocket link only to resolve this issue feels like overengineering unfortunately. I will read further answers, maybe someone suggest some different approach. Thank you.

**Comment by phryneas** [comment]
I am not talking about implementing a full WebSocket link. 
Links can be chained, and you can have a link in front of your WebSocket link that just "drops" some of the responses coming through.

```js
const droppingLink = new ApolloLink((operation, forward) => {
  return new Observable((observer) => {
    forward(operation).subscribe({
      next(value) {
        if (
          operation.operationName === "MySubscription" &&
          value.data.someCondition
        ) {
          return; // skip this value
        }
        observer.next(value);
      },
      error(error) {
        observer.error(error);
      },
      complete() {
        observer.complete();
      },
    });
  });
});

new ApolloClient({
  link: droppingLink.concat(yourWebSocketLink),
});
```

**Comment by jerelmiller** [comment]
Hey @believer-ufa 👋 

Appreciate the full solution here! Just to check in, did you need anymore help on this issue? From what I gather, it looks like you've found a solution that works, so is it cool if I close out this issue?

**Comment by believer-ufa** [comment]
@jerelmiller yes, my personal issue were arrived l solved with help of @phryneas. So of course you can close it if your think it would be right :)

**Comment by jerelmiller** [comment]
Good to hear! I'll go ahead and close this then. Thanks!
