### ISSUE TITLE
Uncaught ApolloError: Error message not found.

### ISSUE THREAD

**Issue by leon-up9** [apollographql/apollo-client#11250]
I have onError Link function.

```
const logUserOut = () => {
      if (getCurrentUser()) {
        logout();
        navigate?.('/login');
      }
    };
    const error = graphQLErrors?.[0];
    // @ts-ignore
    const { code } = error || {};
    if (error?.extensions?.code === 'UNAUTHENTICATED' || code === 401 || code === 403) {
      logger.info('User logged out due to authentication error', error);
      logUserOut();
    } else if (networkError?.message === 'Failed to fetch') {
      logUserOut();
    }
    LogRocket.error(error || networkError);
```

what is the reason for the error mention above?

**Comment by bignimbus** [comment]
Hi @leon-up9 👋🏻  the source code for that message can be found here:

https://github.com/apollographql/apollo-client/blob/76539d91b0f4f8b031938081f21ae59d5e872925/src/errors/index.ts#L48-L68

Which is called when instantiating an `ApolloError` here:

https://github.com/apollographql/apollo-client/blob/76539d91b0f4f8b031938081f21ae59d5e872925/src/errors/index.ts#L107

So I believe what you're seeing is a case where an error is coming back in a format that doesn't conform to expected values in a network error or GraphQL error.

I can help debug further if you can send a Replay of the session or share what the response is from the Network tab.  Thanks!
