### ISSUE TITLE
Error message not displayed properly (encoding issue)

### ISSUE THREAD

**Issue by JonasDoe** [apollographql/apollo-client#11260]
### Issue Description

In the console log, I see an error:
`An error occurred! For more details, see the full error text at https://go.apollo.dev/c/err#%7B%22version%22%3A%223.8.4%22%2C%22message%22%3A10%2C%22args%22%3A%5B%22chatChannel%22%2C%22%7B%5Cn%20%20%5C%22__typename%5C%22%3A%20%5C%22Group%5C%22%2C%5Cn%20%20%5C%22intro%5C%22%3A%20%5C%22%5C%22%2C%5Cn%20%20%5C%22info%5C%22%3A%20%5C%22%5C%22%2C%5Cn%20%20%5C%22locatedByAddress%5C%22%3A%20null%2C%5Cn%20%20%5C%22categorizedBy%5C%22%3A%20null%2C%5Cn%20%20%5C%22administeredBy%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22__typename%5C%22%3A%20%5C%22MembershipConnection%5C%22%2C%5Cn%20%20%20%20%5C%22count%5C%22%3A%200%2C%5Cn%20%20%20%20%5C%22edges%5C%22%3A%20%5B%5D%5Cn%20%20%7D%2C%5Cn%20%20%5C%22id%5C%22%3A%20%5C%22U%3A8f443196-5370-4ac2-a997-d8211042e972%3AGroup%5C%22%2C%5Cn%20%20%5C%22name%5C%22%3A%20%5C%22adsfadsfadsfdsf%5C%22%2C%5Cn%20%20%5C%22slug%5C%22%3A%20%5C%22S%3Aadsfadsfadsfdsf1%3AGroup%5C%22%2C%5Cn%20%20%5C%22imagedByImage%5C%22%3A%20null%5Cn%7D%22%5D%7D`
Following that links seems to suffer from some encoding issues, b/c the error message I can see there is truncated to `Missing field 'chatChannel' while writing result %o`.

### Link to Reproduction

https://go.apollo.dev/c/err#%7B%22version%22%3A%223.8.4%22%2C%22message%22%3A10%2C%22args%22%3A%5B%22chatChannel%22%2C%22%7B%5Cn%20%20%5C%22__typename%5C%22%3A%20%5C%22Group%5C%22%2C%5Cn%20%20%5C%22intro%5C%22%3A%20%5C%22%5C%22%2C%5Cn%20%20%5C%22info%5C%22%3A%20%5C%22%5C%22%2C%5Cn%20%20%5C%22locatedByAddress%5C%22%3A%20null%2C%5Cn%20%20%5C%22categorizedBy%5C%22%3A%20null%2C%5Cn%20%20%5C%22administeredBy%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22__typename%5C%22%3A%20%5C%22MembershipConnection%5C%22%2C%5Cn%20%20%20%20%5C%22count%5C%22%3A%200%2C%5Cn%20%20%20%20%5C%22edges%5C%22%3A%20%5B%5D%5Cn%20%20%7D%2C%5Cn%20%20%5C%22id%5C%22%3A%20%5C%22U%3A8f443196-5370-4ac2-a997-d8211042e972%3AGroup%5C%22%2C%5Cn%20%20%5C%22name%5C%22%3A%20%5C%22adsfadsfadsfdsf%5C%22%2C%5Cn%20%20%5C%22slug%5C%22%3A%20%5C%22S%3Aadsfadsfadsfdsf1%3AGroup%5C%22%2C%5Cn%20%20%5C%22imagedByImage%5C%22%3A%20null%5Cn%7D%22%5D%7D

### Reproduction Steps

Folllow the link basically.

**Comment by phryneas** [comment]
Thanks for the bug report! This was an error in our Documentation error page and will be fixed soon via #11261.

In the meantime, you can get these errors to display with the full text locally by adding

```
import { loadErrorMessages, loadDevMessages } from "@apollo/client/dev";

if (__DEV__) {  // Adds messages only in a dev environment
  loadDevMessages();
  loadErrorMessages();
}
```
to your codebase.

**Comment by JonasDoe** [comment]
Oh, I see! Sorry for hassle then, and thank you for the quick response and the workaround!

**Comment by phryneas** [comment]
No, thanks a lot for bringing this up - your issue here triggered me creating that fix :)

**Comment by JonasDoe** [comment]
> No, thanks a lot for bringing this up - your issue here triggered me creating that fix :)

Just coming to my mind - the max URL length might cause some trouble as well in some browsers. Anyway, thank you and have a nice day! :)
