### ISSUE TITLE
ApolloClient - server side caching based on headers

### ISSUE THREAD

**Issue by morriq** [apollographql/apollo-client#11277]
### Issue Description

Hello, I render server side some views using apollo.

This is my client SSR:

```
const client = new ApolloClient({
  ssrMode: true,
  cache: new InMemoryCache({
    resultCacheMaxSize: 10_000,
  }),
  defaultOptions: {
    watchQuery: {
      fetchPolicy: 'cache-and-network',
    },
    query: {
      fetchPolicy: 'cache-first',
    },
  },
});

  const httpLink = new HttpLink({
    uri: 'http://localhost:4321/graphql',
    credentials: 'include',
    headers: {
      cookie: context.request.headers.get('cookie') || '',
    },
  });

  client.setLink(from([httpLink]));
```

As you can see, I'm caching queries, but some requests are depending on headers.cookie (user token). How can I tell apollo to make cache id based on headers?
 

### Link to Reproduction

none

**Comment by phryneas** [comment]
We really recommend that you create a new `ApolloClient` for every incoming request, and treat those 100% isolated from all other requests.

As you already noted, there is a high risk of cross-contamination of user data, so that's the only way to 100% avoid that.

**Comment by morriq** [comment]
got it, thank you sir :)
