### ISSUE TITLE
The section `get-started` should recommend Vite instead of CRA.

### ISSUE THREAD

**Issue by gento-ogane** [apollographql/apollo-client#11305]
The section [`get-started`](https://www.apollographql.com/docs/react/get-started) explains how to build react app with CRA, but [CRA is entrying maintenance mode](https://github.com/facebook/create-react-app/issues/11180#issuecomment-874748552).
[Official React doc also doesn't describe](https://react.dev/learn/start-a-new-react-project) about CRA anymore, and now refers Vite.

If this proposal is approval, I will try to create PR which updates descriptions about CRA to Vite in get-started.

**Comment by bignimbus** [comment]
Hi @gento-ogane, I've added this request to an upcoming team meeting to talk it through.  Thanks for this suggestion, it seems reasonable 🙏🏻

**Comment by bignimbus** [comment]
@gento-ogane we would be eager to review a PR to replace CRA with Vite in our docs.  Please let us know how we can be helpful, thanks for volunteering to take this on! 🚀

**Comment by gento-ogane** [comment]
@bignimbus 
Thank you for your response!
I will create PR.  If I'm in trouble, I'll ask questions!!

**Comment by gento-ogane** [comment]
Here is the working branch.
https://github.com/gento-ogane/apollo-client/tree/11305-update-doc-replace-to-vite

**Comment by gento-ogane** [comment]
@bignimbus 
I created [Pull Request](https://github.com/apollographql/apollo-client/pull/11352)!!
Please review this.
