### ISSUE TITLE
resetStore throws InvariantError when no queries were in flight

### ISSUE THREAD

**Issue by tunesmith** [apollographql/apollo-client#11316]
### Issue Description

Our code does:

```
        await client.resetStore();

... // a few lines further down; same function
          try {
            ({ data, errors } = await client.query<
              MyQuery,
              MyQueryVariables
            >({ query: MY_QUERY }));
          } catch (e) {
            if (e instanceof InvariantError) {
              // log errors
            } ...
          }
```

It throws an InvariantError, complaining about refreshing queries in flight. (error code 18: `Store reset while query was in flight (not completed in link chain)`). The rub is that there are no previous queries in flight. I'm able to tell by logging all the client queries in the session, and they all complete before `await client.resetStore()` is reached.

The query it is complaining about being in flight is the `MY_QUERY` query, which does not initiate until after the `await client.resetStore()` is invoked.

We are able to avoid the problem by putting an `await new Promise((resolve) => setTimeout(resolve, 5000));` just after `client.resetStore()` but we don't want to do that.

We're trying to work around this with an exponential backoff/retry, but I'm wondering what we're missing here. Is this a bug in the client that doesn't properly reset the store? It seems that `await` should wait until the store is entirely reset before it starts trying to initiate new queries later on in the same code flow.

Note: `client.stop()` is not an answer in our case, because then MY_QUERY would often simply silently fail as there was no client set up in time to properly send the query.

### Link to Reproduction

see above

**Comment by bignimbus** [comment]
Hi @tunesmith 👋🏻  thanks for opening this Issue!  I know creating a runnable reproduction can be time-consuming but it will significantly expedite the process.  When we have something runnable we can triage whether this is a bug or a userland issue relatively quickly and communicate that back to you.

That said, we'll take a look as soon as we can!  Can you provide some more details?  E.g. `@apollo/client` version, etc.
