### ISSUE TITLE
error TS1005: '?' expected  - in apollo client v 3.5.10

### ISSUE THREAD

**Issue by bkrajendra** [apollographql/apollo-client#11313]
### Issue Description

I am using apollo client v 3.5.10
currently facing issue with jenkins build:
error:
```
[INFO] Error: node_modules/@apollo/client/cache/core/types/common.d.ts:52:110 - error TS1005: '?' expected.
[INFO] 
[INFO] 52 type StoreObjectValueMaybeReference<StoreVal> = StoreVal extends Array<infer Item extends Record<string, any>> ? ReadonlyArray<AsStoreObject<Item> | Reference> : StoreVal extends Record<string, any> ? AsStoreObject<StoreVal> | Reference : StoreVal;
```
Everything was working till few days back and suddenly started getting this issue.
there is no change in build environment.

maven buil env:
```
<nodeVersion>v14.17.0</nodeVersion>
<npmVersion>6.14.13</npmVersion>
```
package.json
```
"@apollo/client": "^3.5.10",
"typescript": "4.6.2",
```

what could be the issue?

### Link to Reproduction

NA

**Comment by phryneas** [comment]
I'm sorry to say that, but you are working with a very outdated environment and all your tools and libraries are years behind and unsupported by their respective maintainers at this point.

You are using the caret (`^`) version for Apollo Client, so `^3.5.10` includes every 3.x version higher than that - it doesn't really tell us which version of Apollo Client you currently have installed. It *could* even be the current `3.8.6` version.
  
There is a good chance that some part of your build environment is not able to parse a newer release of Apollo Client as there might e.g. newer TypeScript syntax in there that might not be supported by the TypeScript version you have installed. Your best chance is probably to slowly increase your other tooling versions until it works again.

**Comment by bkrajendra** [comment]
Thanks for the quick reply.
For now temporary fix I applied is to use "@apollo/client": "3.5.10" (removed ^)
But we will definitely have to upgrade to the latest version of the library.
Thanks again.

**Comment by phryneas** [comment]
Just keep in mind that doing this could also mean that you e.g. accidentally downgraded from `3.7.12` to `3.5.10` - you don't know which version you really were on. 
I'd recommend that you look at the git history of your `package-lock.json` to find that out.

**Comment by phryneas** [comment]
Either way, I think there's nothing really actionable from our side, so I'm closing this issue. I hope you get this resolved as good as possible :)
