### ISSUE TITLE
Input type error is swallowed

### ISSUE THREAD

**Issue by DimitryDushkin** [apollographql/apollo-client#1132]
I've setup SSR with react-apollo. Here is RootQuery:
```graphql
        type Query {
            patient(medicalId: String!): Patient
        }
```
`medicalId` is required and should be `String`.
If `undefined` is passed as `medicalId` SSR just hangs. I've found out that Error is actually thrown [here in graphql-js](https://github.com/graphql/graphql-js/blob/master/src/execution/values.js#L78), but it looks like it has been swallowed by `apollo-client` [here](https://github.com/apollostack/apollo-client/blob/master/src/core/QueryManager.ts#L668).

Apparently
```
    // `fetchQuery` returns a Promise. In case of a failure it should be caucht or else the
    // console will show an `Uncaught (in promise)` message. Ignore the error for now.
```
no one `catch` or `console.error` this error.

If [this line is removed](https://github.com/apollostack/apollo-client/blob/master/src/core/QueryManager.ts#L668) error is thrown and visible. That's much more clearer that just request hang and no errors at all.

**Comment by helfer** [comment]
As I commented on a PR, I think this error should usually be propagated through the store and thrown on the observer. Is that not the case for you?

**Comment by helfer** [comment]
Closing old issues. 🚪
