### ISSUE TITLE
useLazyQuery seems to be broken

### ISSUE THREAD

**Issue by sa-ma** [apollographql/apollo-client#11338]
### Issue Description

The `useLazyQuery` hook is fraught with some issues.
- it fires twice #9448 
- The `onCompleted` hook is called once no matter how many times the hook is called
- The `stopPolling` function doesn't stop polling

I'm on v3.8.4

### Link to Reproduction

I'll provide additional replay if it is requested

**Comment by phryneas** [comment]
I'm sorry, but a `meta`-issue like this is just not actionable. As such, I'm going to close it. 

If there is no issue already open for your second and third complaint here (although I believe they are), please open a new one.

Generally: We are trying to help with issues as good as we can, but we have to balance it with other parts of our work (like adding new features, speaking at conferences and general refactorings), so please don't expect each problem you bring up to be resolved in a certain amount of time.
