### ISSUE TITLE
jest, RTL, Apollo-Client ^3.5: Client Cache is not a constructer

### ISSUE THREAD

**Issue by SvmkWebplatDevs** [apollographql/apollo-client#11331]
### Issue Description

Utilizing the setup found here https://www.apollographql.com/docs/react/development-testing/testing/#testing-with-the-cache to test a component which utilizes cache and this error will throw. Removing cache and `MockLink` will throw a similar error. Replacing `Cache` with InMemoryCache` will still throw the same error.

```javascript
 FAIL  src/components/BasePage/__tests__/BasePage.test.js
  ● Test suite failed to run

    TypeError: _client.Cache is not a constructor

      33 | // const cache = new Cache({});
      34 | const apolloClient = new ApolloClient({
    > 35 |   cache: new Cache({}),
         |          ^
      36 |   link: new MockLink([]),
      37 | });
      38 |

      at Object.<anonymous> (src/components/BasePage/__tests__/BasePage.test.js:35:10)
```

Simple setup of the client being passed into the component
```javascript
import { ApolloClient, Cache } from '@apollo/client';
import { MockedProvider, MockLink } from '@apollo/client/testing';

const apolloClient = new ApolloClient({
  cache: new Cache({}),
  link: new MockLink([]),
});
```

### Link to Reproduction

https://bug-free-space-spoon-97776ww9vwqwf7vjp.github.dev/

**Comment by SvmkWebplatDevs** [comment]
@phryneas it doesn't go away. Anything I swap out in this case leads to the same error. I can strip down to just `new ApolloClient` and it will error out saying ApolloClient isn't a constructor.

**Comment by phryneas** [comment]
That sounds like a problem with imports in your local setup - maybe something related to mocking or ESM imports in Jest? Seems like those `import` statements return `undefined`.
