### ISSUE TITLE
Apollo seems to hit the network consistently, even if "cache-only" is the fetch policy

### ISSUE THREAD

**Issue by glebdv** [apollographql/apollo-client#11341]
Trying to figure out if im doing something wrong here.

Query: (we're using codegen to generate types from the schema)

![image](https://github.com/apollographql/apollo-client/assets/33739704/a807f8dc-b379-45bd-8e12-a66451971e9c)

ROOT_QUERY cache:

![image](https://github.com/apollographql/apollo-client/assets/33739704/16725856-0214-4622-8f9b-72e85bc77a89)

The component is basically a two part `radio` group toggle that either fetches all `availableHospitalsForAppointment` with `deptId: null` or per department scpecific hospitals.

However, it seems that every time the call is made, a network request is always made, and always hits the backend.

All of the below calls are `GetAvailableHospitalsForAppointment` queries

![image](https://github.com/apollographql/apollo-client/assets/33739704/f902d774-3d91-4d68-b3fc-34758e52efef)

we have custom typePolicies for certain things, but none for that graphtype

any thoughts on why this could happen? I set it `cache-only` just to check, but it always seems to hit the backend, otherwise we have it at `cache-first`

**Comment by glebdv** [comment]
does it maybe have anything to do with the fact that we are refetching the query?
![image](https://github.com/apollographql/apollo-client/assets/33739704/e1bfeb78-03dc-4cef-9a11-1b89d64ef941)

**Comment by glebdv** [comment]
ok like 99% convinced its because of that; is there any way of setting the fetch policy or will I have to transform this to a lazyQuery?

**Comment by glebdv** [comment]
100% convinced its that. I just changed it to a lazyQuery that fires on load although I try to avoid the useEffects as much as I can

**Comment by phryneas** [comment]
Yes, it's due to the `refetch` - there's no more explicit way of saying "I really want this to hit the network layer" than calling `refetch`. 

Question: why do you not skip any `useEffects` and just set a state with the variables you want to use for your query? The component will rerender and the `useQuery` hook will execute for those new variables.

**Comment by glebdv** [comment]
good point, I did exactly that,thank you!
