### ISSUE TITLE
nextFetchPolicy function is not called sometimes

### ISSUE THREAD

**Issue by jeel2308** [apollographql/apollo-client#11365]
### Issue Description

I am using latest version of apollo client v3.8.7. 
I am providing default `nextFetchPolicy` function to update fetchPolicy, if query has `fetchPolicy` of `cache-and-network`. According to the docs, `nextFetchPolicy` function should be called after request is done(reason `after-fetch`) and when variables are changed (reason `variables-changed`). 
However, `nextFetchPolicy` function is not called after variables are changed(with reason `variables-changed`). It is only called when request is done.
Here is the code snippet that I am using,

```
const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: httpLink,
  defaultOptions: {
    watchQuery: {
      fetchPolicy: "cache-and-network",
      notifyOnNetworkStatusChange: true,
      nextFetchPolicy: (
        currentFetchPolicy,
        { reason, initialFetchPolicy, observable }
      ) => {
        if (reason === "variables-changed") {
          return initialFetchPolicy;
        }

        if (
          reason === "after-fetch" &&
          ["cache-and-network"].includes(currentFetchPolicy)
        ) {
          return "cache-only";
        }

        return currentFetchPolicy;
      }
    },

    query: {
      fetchPolicy: "network-only"
    }
  }
});
```

Issue is solved if I comment out code inside `after-fetch` condition, but it limits usability of nextFetchPolicy function.

### Link to Reproduction

https://codesandbox.io/p/sandbox/eloquent-cori-2jngr7?file=%2Fsrc%2Findex.jsx

### Reproduction Steps

- Change values from dropdown and check logs in console. 

- Comment out code inside `after-fetch` condition in nextFetchPolicy function and check logs again.

- Current outcome:
  - NextFetchPolicy function is called with reason 'after-fetch' whenever request is completed and not called when variables are changed(with reason `variables-changed`).
  
- Intended outcome:
  - NextFetchPolicy function should be called whenever variables are updated. Then it should be called again, if variable change triggers request with reason `after-fetch`.

**Comment by bignimbus** [comment]
Hi @jeel2308 👋🏻 thanks for opening this issue!

Your reproduction includes the use of the `graphql` higher-order component, which is deprecated as of 2020 (see the relevant [docs page](https://www.apollographql.com/docs/react/api/react/hoc)).  Have you seen this behavior with the currently-supported React API?

**Comment by jeel2308** [comment]
Hi @bignimbus, thanks for your reply.

I have updated reproduction to use `useQuery` instead of `graphql` . Issue is still observed.

**Comment by jeel2308** [comment]
Any update on this? Are you planning to ignore this issue like other open issues?:)

**Comment by phryneas** [comment]
Hi Patel,
I've taken a look, and this is caused by these lines:
https://github.com/apollographql/apollo-client/blob/3f7eecbfbd4f4444cffcaac7dd9fd225c8c2a401/src/core/ObservableQuery.ts#L882-L884

I'll change this to a bug with a reproduction, but right now I can't give you a timeframe on a fix here, as we are in the middle of finalizing Apollo Client 3.9 right now.

**Comment by jeel2308** [comment]
Hi, any updates on this? If you are busy on upcoming release, then can I raise PR for it?

**Comment by phryneas** [comment]
I'll try to take a stab at this next week :)

**Comment by phryneas** [comment]
@jeel2308 you can give the release PR in #11626 a stab if it solves your problem :)

**Comment by jeel2308** [comment]
Sure. I will have look. Thank you for the update
