### ISSUE TITLE
[Next.js] When to do `cache.extract()` and include it in the HTML doc with Suspense SSR?

### ISSUE THREAD

**Issue by jackyef** [apollographql/apollo-client#11383]
I have read some issues regarding React 18 + Apollo Client 3.8 Suspense SSR support, in particular:
- https://github.com/apollographql/apollo-client/issues/8365
- https://github.com/apollographql/apollo-client/issues/10231

In non-Suspense world, we previously would await `getDataFromTree()` and call `cache.extract()` after it. 

Now that we are in Suspense world, is there a way to know when all the queries has been resolved, but before the HTML document has been sent to the browser in Next.js? How do we sent the serialized cache of SSR-resolved-suspense-queries to the browser?

The RFC mentioned this
> @/benjamn has proposed an interesting idea of potentially transmitting the whole query results produced via SSR rather than normalized cache results that would need to be serialized. Queries might then be able to use these query results immediately which would then make their way into the cache. This is something we should consider via an ApolloLink.

but I am not sure if any further development has surfaced since the 3.8 release.

**Comment by jackyef** [comment]
Thanks for your reply @phryneas !

What about page router use cases though? Correct me if I am wrong, but it seems like Suspense does work with page router as well. Here's a repo to play around with it: https://github.com/jackyef/next-apollo-suspense-ssr

Are you saying for this case we should still do the `getDataFromTree`? Wouldn't that mean the performance will actually be worse because before React 18, we would only be doing 2-pass render, and with React 18 the SSR would happen while waiting for Suspense and then we do 2-pass render again? 🤔

**Comment by phryneas** [comment]
Since between those 2-pass-renders you would be waiting for all queries to finish, and the suspense queries will be "instant" if data is already in the cache, that will come out to the same performance as before.

**Comment by jackyef** [comment]
Ah, so you are essentially saying page router wouldn't be able to benefit from `useSuspenseQuery` then? As they would still need to rely on `getDataFromTree()`?

Also, does this mean the recommendation for page router is still to do `getDataFromTree` in the `getInitialProps`?

**Comment by phryneas** [comment]
The benefit here is that `useSuspenseQuery` gives you a much nicer DX regarding loading states and error handling.

> Also, does this mean the recommendation for page router is still to do getDataFromTree in the getInitialProps?

If it works, I assume so. I have to admit I haven't tried it with the page router, but I wouldn't see how things would suddenly be different. The pages router uses `renderToString`, and that's all that counts for how you do SSR in the end.

**Comment by jackyef** [comment]
Gotcha, but in regards to SSR perf, they would still be the same. 

Ah, I was wondering if the page router does streaming or not, but I wasn't able to find it in the Next.js repo, that explains a lot.

Thanks a lot for your elaborate answers!

**Comment by jerelmiller** [comment]
Hey @jackyef 👋 

If I'm reading this right, it looks like your question has been resolved. As such, I'm going to go ahead and close out this issue. If I've missed something or there is still something actionable here, feel free to reopen. Thanks!
