### ISSUE TITLE
Support for @stream in apollo-client?

### ISSUE THREAD

**Issue by sgedda** [apollographql/apollo-client#11391]
I´ve been working with graphql for a while and was introduced to @ defer and @ stream directives recently. I managed to use the @ defer directive with "@apollo/client": "^3.8.6" in a react native repo. Does anyone here know the status of support for @ stream in apollo client?

**Comment by jerelmiller** [comment]
Hey @sgedda 👋 

Appreciate the interest in `@stream`! We are currently looking into supporting it across the entire Apollo platform and working on trying to figure out the best way to roll this functionality out. We will have more details to share in the coming days.

For now I'm going to close this issue as a duplicate and keep the discussion going over in https://github.com/apollographql/apollo-feature-requests/issues/3. Thanks!
