### ISSUE TITLE
Migrate docs example sandboxes to use Vite instead of CRA

### ISSUE THREAD

**Issue by alessbell** [apollographql/apollo-client#11392]
### Issue Description

There are three codesandboxes that live in the [docs-examples](https://github.com/apollographql/docs-examples/tree/main/apollo-client/v3) repo and are referenced in our docs.

We'd like to migrate them to use Vite instead of CRA, as we're updating our guidance in the getting started part of our guide, and have already updated our error reproduction sandbox.

If there are other codesandboxes that don't yet live in docs-examples, we should move those over and also update them to use Vite.

While the PR(s) for the sandboxes themselves will be against `docs-examples`, any updates to file names should be reflected in the file names referenced in our docs in the relevant pages.

### Link to Reproduction

https://github.com/apollographql/docs-examples/tree/main/apollo-client/v3

**Comment by alessbell** [comment]
cc: @apollographql/docs I wanted to surface this CRA > Vite move with you as well. Feel free to share any thoughts here, and if there are no objections we'll carry on :)

**Comment by Meschreiber** [comment]
Thanks for the heads-up @alessbell ! No concerns on my end.

**Comment by hmousavin** [comment]
To prevent rework: I made [PR](https://github.com/apollographql/docs-examples/pull/133) to make this done

**Comment by jerelmiller** [comment]
Finished in https://github.com/apollographql/docs-examples/pull/133
