### ISSUE TITLE
Is there a defaultOptions for Subscription?

### ISSUE THREAD

**Issue by iblislin** [apollographql/apollo-client#11411]
Hi,

  I want to set the default `errorPolicy` for Subscription, but there aren't one for Subscript in the [DefaultOptions](https://www.apollographql.com/docs/react/api/core/ApolloClient/#DefaultOptions). Are there any ways to set the default globally?

**Comment by phryneas** [comment]
I'm sorry, but at this point we have no such option.

You could create your custom `useSubscription` hook for this:

```ts
const useSubscriptionWithDefaults: typeof useSubscription = (
  subscription,
  options
) => useSubscription(subscription, { errorPolicy: "myNewDefault", ...options });
```

**Comment by iblislin** [comment]
ah, thanks.

Any plans for support it in `DefaultOptions`? 
I really need that cool option supported, since I'm using apollo-angular + codegen, and using a custom hook seems not applicable for codegen I guess.

I can try to make a PR and I'm wondering to known the concerns of adding it?

**Comment by bignimbus** [comment]
Hi @iblislin 👋🏻 is it fair to say that you're looking for something like what's described here?  https://github.com/apollographql/apollo-feature-requests/issues/169

If so, the team would be happy to review a PR 🙏🏻

**Comment by alessbell** [comment]
Hi @iblislin 👋  Circling back here. Since you're using apollo-angular, you could use a similar approach suggested by @phryneas but in Angular it would look something like:

```ts
const COMMENTS_SUBSCRIPTION = gql`
  subscription onCommentAdded($repoFullName: String!){
    commentAdded(repoFullName: $repoFullName){
      id
      content
    }
  }
`;

function subscribeWithDefaultOptions(options) {
  return apollo.subscribe({
    errorPolicy: "myNewDefault",
    ...options
  });
}

 
@Component({ ... })
class CommentsComponent {
  constructor(apollo: Apollo) {
    subscribeWithDefaultOptions({
      query: COMMENTS_SUBSCRIPTION,
      variables: {
        repoName: `kamilkisiela/apollo-angular`
      }
    }).subscribe((result) => {
      if (result.data?.commentAdded) {
        console.log('New comment:', result.data.commentAdded);
      }
    });
  }
}
```

Since we have a tracking issue for the feature request, I'll go ahead and close this issue out. If you have any other questions, feel free to drop by our [Discord](https://discord.gg/graphos), too. Thanks!
