### ISSUE TITLE
Cant test useSuspenseQuery with jest

### ISSUE THREAD

**Issue by GasparAdragna** [apollographql/apollo-client#11418]
### Issue Description

Changing the dog example just a little breaks the tests.

If you change useQuery for useSuspenseQuery on the dog.tsx file, you no longer get anything rendered.

### Link to Reproduction

https://codesandbox.io/p/devbox/y48t28

### Reproduction Steps

take the dog demo and change the useQuery for useSuspenseQuery (@apollo/client 3.8.8)
the tests breaks.

**Comment by jerelmiller** [comment]
Hey @GasparAdragna 👋 

It looks like you're missing a [Suspense boundary](https://react.dev/reference/react/Suspense) in your React tree, so its unable to render a fallback. See the ["Fetching with Suspense"](https://www.apollographql.com/docs/react/data/suspense#fetching-with-suspense) section in the docs for an example.

Does this help/?

**Comment by alessbell** [comment]
I'll close this issue out as there's no bug here, but feel free to head over to our [Discord](https://discord.gg/graphos) to ask any other related questions :) Thanks.
