### ISSUE TITLE
Header automatically convert the lower case 

### ISSUE THREAD

**Issue by raja-OX** [apollographql/apollo-client#11429]
Custom headers automatically convert into lowercase.

**Comment by jerelmiller** [comment]
Hey @raja-OX 👋 

I'm not quite sure what you're looking for here. Is there something actionable you are looking for?

FWIW headers are [case-insensitive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers). We do some [header normalization](https://github.com/apollographql/apollo-client/blob/main/src/link/http/selectHttpOptionsAndBody.ts#L202-L232) to try and detect duplicates to avoid sending headers that overwrite each other.

If you need to preserve casing on your headers for whatever reason, you can pass the [`preserveHeaderCase` option](https://www.apollographql.com/docs/react/api/link/apollo-link-http#preserveheadercase-1) to `HttpLink`.

Please let us know if there is anything actionable. Thanks!

**Comment by raja-OX** [comment]
@jerelmiller Thank for your response. I was unaware of the [preserveHeaderCase option](https://www.apollographql.com/docs/react/api/link/apollo-link-http#preserveheadercase-1). 

This is working for my scenario. I am closing this issue. Thank you.
