### ISSUE TITLE
Mutiple Refetch: Issue in response

### ISSUE THREAD

**Issue by yespai** [apollographql/apollo-client#11456]
### Issue Description

When query is attempted to be refetched multiple times with different variables, multiple API requests get fired.
And if the previous API gets resolved after the current API, the data becomes blank.

Normal loading (initial)
![init](https://github.com/apollographql/apollo-client/assets/150657789/8d320834-4fcb-4fd1-a8af-23bc9b2aab9e)

Refetched clicked multiple times
![refetch](https://github.com/apollographql/apollo-client/assets/150657789/f1652084-7135-494c-a1dd-7dbb3db0a368)

Above it can be seen that latest API gets resolved first and then the previous one. The react component re-renders with empty data.

**Config**: 
Framework: Web - React

```
const apolloClient = new ApolloClient({
  cache: new InMemoryCache(),
  defaultOptions: {
    watchQuery: {
      fetchPolicy: "network-only",
      nextFetchPolicy: "network-only",
      notifyOnNetworkStatusChange: true,
    },
  },
});
```

**Comment by jerelmiller** [comment]
Hey @yespai 👋 

What Apollo Client version are you using? Would you be able to provide more information about how you're calling `refetch`, how you're setting up the query, etc? Its pretty difficult to understand how to reproduce the issue without more information. Thanks!

**Comment by jerelmiller** [comment]
@yespai the more I look at this, the more I think this is similar to https://github.com/apollographql/apollo-client/pull/10912 which was fixed with https://github.com/apollographql/apollo-client/pull/11078. Would you be willing to try the latest 3.9 beta version (`npm i @apollo/client@next`) to see if this resolves your issue?

**Comment by yespai** [comment]
I am using 3.8.8. Let me try it on latest beta version

**Comment by yespai** [comment]
Looks good on **3.9.0-beta.1**
I assume we don't have to worry about cancelling the request with these changes. 
Thanks.

**Comment by yespai** [comment]
Looks good on **3.9.0-beta.1**
I assume we don't have to worry about cancelling the request with these changes.
Thanks.
