### ISSUE TITLE
fetchPolicy labels are not visible using site's light theme

### ISSUE THREAD

**Issue by jzwood** [apollographql/apollo-client#11462]
### Issue Description

Fetch policies are invisible on Chrome and Firefox when the docs site is using light theme.

![Screenshot 2024-01-04 at 10 08 13 AM](https://github.com/apollographql/apollo-client/assets/13749324/2a5ee5f4-1c98-44b5-bca9-1ccd60d57ef5)
![Screenshot 2024-01-04 at 10 08 35 AM](https://github.com/apollographql/apollo-client/assets/13749324/bad11aea-60e6-4d9d-af9c-76738a817297)

### Link to Reproduction

https://www.apollographql.com/docs/react/data/queries/#supported-fetch-policies

**Comment by jerelmiller** [comment]
Hey @jzwood 👋 

This has been fixed and deployed. Thanks for opening the issue!
