### ISSUE TITLE
Error: Unsatisfied version 0 from platform of shared singleton module @apollo/client/core (required ^3.8.9)

### ISSUE THREAD

**Issue by sevikk** [apollographql/apollo-client#11475]
### Issue Description

nx-workspace

main.ts:6

`Error: Unsatisfied version 0 from platform of shared singleton module @apollo/client/core (required ^3.8.9)`

shared module @apollo/client/core -> /path/app/node_modules/@apollo/client/core/index.js - Warning: No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file /path/node_modules/@apollo/client/core/package.json, or manually specify version in shared config.

shared module @apollo/client/link/batch -> /path/app/node_modules/@apollo/client/link/batch/index.js - Warning: No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file /path/app/node_modules/@apollo/client/link/batch/package.json, or manually specify version in shared config.

Missing version property exposed from package.

Webpack build with module federation is failied.

### Link to Reproduction

link

<img width="1180" alt="image" src="https://github.com/apollographql/apollo-client/assets/17278237/c17643c5-d33b-42a9-a593-456484b17e29">

**Comment by phryneas** [comment]
That does look like a bug in `nx-workspace` to be honest - they should always check the top-level `package.json` of a library, not nested entry points - so they should check `node_modules/@apollo/client/package.json`, not `node_modules/@apollo/client/link/batch/package.json`.

Those nested `package.json` files are used by many packages, and they usually don't contain any version information.

Did you open an issue over there?

**Comment by MaxSassen** [comment]
![image](https://github.com/apollographql/apollo-client/assets/6112704/9a11a762-181e-4b24-a10d-983cec76940e)

im having the same issue, @sevikk  saw you completed this 3 weeks ago. How did you resolved this issue?
