### ISSUE TITLE
Updating an object with a mutation that returns a different type

### ISSUE THREAD

**Issue by SachaG** [apollographql/apollo-client#1147]
I have a `vote` mutation that’s used to upvote different types of documents: posts, comments, etc. Since I want to use a single mutation for all these types I can’t have it return a `Post` or `Comment` type, so I created a new `VoteResult` type. And I’m using `dataIdFromObject`, so the update happens automatically as soon as the mutation returns.

The optimistic response works properly (I’m setting the `__typename` manually), but when the mutation returns the real result, something goes wrong and the optimistic response is overturned

Could this be because the mutation doesn't return an object of the same GraphQL type as the object in the store that needs to be updated? In other words, can a mutation that returns type `A` be used to update a document of type `B` in the store?

By the way I can confirm that if both types are the same (i.e. I change `vote` to return `Post` object), I’m not seeing any issues.

**Comment by stubailo** [comment]
> something goes wrong and the optimistic response is overturned

The optimistic update is always removed once the response from the server is received. You have a few options:

1. Modify your mutation to return an object of the correct type by using an interface. Define an interface called `Votable` with a field `votes`, and have all types that can be upvoted belong to that. Since `__typename` will be correct, everything will work as planned.
2. Use reducers or updateQueries to update the objects manually.
3. Write a custom reducer on the store to update the appropriate object (right now we don't have a specific feature for updating an object manually but we should)

I think (1) is the best option because it makes sense to me that an API that updates an object would return that type of object.

**Comment by SachaG** [comment]
Oh you're right, an interface sounds exactly like what I need, thanks! I'll read up on that and report back :)

**Comment by rnenjoy** [comment]
@SashG some code example when you have a working version of this would be great to see! We should even put it in the documentation since i think many people will run into this.

**Comment by smolinari** [comment]
Agree with @rnenjoy. Please let us know the solution. Very interesting.

Scott

**Comment by calebmer** [comment]
Sounds like we’ve come to a solution. @SachaG since it seems like there is some interest in the solution please let us know if there’s anything that can be learned from your approach 👍

**Comment by SachaG** [comment]
Well, we know what to do in theory but when @xavcz tried it he ran into some issues, so I don't really have a working solution yet. I'll update the thread when I do.

**Comment by Poincare** [comment]
Maybe we should keep this issue open in the meantime?

**Comment by stubailo** [comment]
I don't  think we should have a built in way of updating an object of a different type, these kinds of exceptions is exactly what updateQueries is for. I think requiring objects to be of the same type to update automatically is pretty reasonable.

**Comment by SachaG** [comment]
OK, it took me a while but I figured it out. The most important point (and something that's not really spelled out) is that when using a union, you have to change your query to use fragments. 

So instead of:

```
  mutation vote($documentId: String, $voteType: String, $collectionName: String) {
      vote(documentId: $documentId, voteType: $voteType, collectionName: $collectionName) {
          _id
          upvotes
          upvoters {
            _id
          }
        } 
    }
```

I had to write:

```
mutation vote($documentId: String, $voteType: String, $collectionName: String) {
      vote(documentId: $documentId, voteType: $voteType, collectionName: $collectionName) {
        ... on Post {
          _id
          upvotes
          upvoters {
            _id
          }
        }
        ... on Comment {
          _id
          upvotes
          upvoters {
            _id
          }
        }
      }
    }
```

Apart from that, just declare a new type:

```
union Votable = Post | Comment
```

And write its resolver:

```
const resolverMap = {
  Votable: {
    __resolveType(obj, context, info){
      if(obj.title){
        return 'Post';
      }

      if(obj.postId){
        return 'Comment';
      }

      return null;
    },
  },
};
```

Here's the [relevant Telescope commit if you're curious](https://github.com/TelescopeJS/Telescope/commit/38de1805308584cb395a4413ca518f89fcb6a805).

**Comment by stubailo** [comment]
Alright! Sounds like it was something with GraphQL itself, and not Apollo. Thanks for posting the resolution.

**Comment by stubailo** [comment]
It's documented here, by the way: http://graphql.org/learn/schema/#interfaces

I'd suggest reading all of the GraphQL documentation there before using GraphQL for something complex.

**Comment by SachaG** [comment]
I did read the documentation, but I didn't realized the interfaces section also applied to unions, so for some reason it didn't really click until I found an issue thread somewhere explaining the problem.
