### ISSUE TITLE
fragment causes client data to be empty object when network tab retrieves expected data

### ISSUE THREAD

**Issue by ODreelist** [apollographql/apollo-client#11505]
### Issue Description

Random fragment usage causes client data query response var to be empty object while network tab shows the same request  retrieves expected data. The solution is to either remove the fragment in the client query (can replace it with just id or the exact fragment attributes, doesn't matter). There are no raised errors but I can reliably reproduce within my own environment. 

linking as relevant: https://github.com/apollographql/apollo-client/issues/10786

recommended solution: __typname needs to be included on the fragment using query as such: 
```js
export const tableOptionsByThing = gql`
  ${CORE_TABLE_FIELDS}
  query TableOptionsByThing($thingPublicId: String!) {
    tableOptionsByThing(thingPublicId: $thingPublicId) {
      ...CoreTableFields
      __typename
    }
  }
`;
```
my opinion: this should not be happening, including __typename on the fragment itself results in the same issue as not including __typename on the query. Only including __typename on the query using the fragment solves the issue.

Feels like a bug but a fun one! let me know if I can help.

**Comment by phryneas** [comment]
Hmm, interesting. 
We do not read any of the fragment fields because we don't know the typename - and we won't know the typename because it's part of the part we don't read.

I agree that this might be annoying, but at the same time it's not really a bug.

If I might ask, Is there a specific reason why you have disabled `addTypename`?

**Comment by ODreelist** [comment]
that's the odd part, addTypename is not disabled, it's included in all the affected queries if you inspect it in the network tab, just doesn't show up in the query result in the component.

**Comment by jerelmiller** [comment]
@ODreelist at this point, a reproduction would be super helpful! We use fragments all over our [showcase app](https://github.com/apollographql/spotify-showcase) with no issue, so being able to see what might be happening in your case would be helpful! You can use our [reproduction template](https://github.com/apollographql/react-apollo-error-template) or [CodeSandbox](https://codesandbox.io/s/github/apollographql/react-apollo-error-template) as a means to get started if need be.

Can you also provide the client version you're using here?
