### ISSUE TITLE
It's unclear that headers prop only works when there is no link prop

### ISSUE THREAD

**Issue by Milesyan** [apollographql/apollo-client#11506]
https://github.com/apollographql/apollo-client/blob/046296ac2285b20fbd43a621395fc4158cfbd073/src/core/ApolloClient.ts#L208-L211

**Comment by Milesyan** [comment]
ts docs should be updated, as well as the docs here https://www.apollographql.com/docs/react/api/core/ApolloClient/#ApolloClientOptions

**Comment by jerelmiller** [comment]
Hey @Milesyan 👋 

Thanks for reporting this! We are in the midst of moving more of our documentation to code and it looks like [`headers`](https://github.com/apollographql/apollo-client/blob/cfe6b782fe3012495e76d08c38e31e8649f51445/src/core/ApolloClient.ts#L54) was missed! We'll make sure to get this updated to add a note that this is used when passing `link`. Thanks for the heads up!

**Comment by jerelmiller** [comment]
Hey @Milesyan 👋 

I've opened https://github.com/apollographql/apollo-client/pull/11508 which will give some additional documentation on this stating that this property is ignored when using `link`. This will be released along with our 3.9 changes which should be within the next week or so. Thanks for again for reporting!

**Comment by jerelmiller** [comment]
Hey @Milesyan 👋 

We've just released v3.9.0 and the change to document the [`headers` option](https://www.apollographql.com/docs/react/api/core/ApolloClient#apolloclientoptions-headers) is live. As such, I'm going to go ahead and close this out. Thanks!
