### ISSUE TITLE
Sub-nested fields or subfields on Apollo Client Type Policies

### ISSUE THREAD

**Issue by tylerruss** [apollographql/apollo-client#11528]
I am trying to use pagination on a field that is 3 levels deep: Query > BusinessProfile > CustomerProfile > paginatedCustomerActivities and I am unable to. 

If I moved up the paginated data one level in the graph, it works just fine.

How would I go about using a merge, read function on sub-nested field?

![Screenshot 2024-01-26 at 11 05 59 AM](https://github.com/apollographql/apollo-client/assets/131697802/04236bc2-c1e5-46dd-9816-4579a9959107)

**Comment by phryneas** [comment]
Since the same question has also been asked in the [community forum](https://community.apollographql.com/t/sub-nested-fields-or-subfields-on-apollo-client-type-policies/7166/2), I'm taking up the conversation there and closing this issue here.
