### ISSUE TITLE
Proposal for an Option to Enable Infinite Reuse of Mocks

### ISSUE THREAD

**Issue by 2012160085** [apollographql/apollo-client#11556]
I think it would be great to add a clear option for continuous reuse of mocks

I saw that the maxUsageCount option was added for mock reuse in #11178. 
I've been using mockLink with MockedResponses defined with a reasonably large number for maxUsageCount for development mock APIs, but I would love to see an option added for infinite reuse.
I read the comment in #9738 about the introduction of a new testing method using schemaLink. However, I think it would be great to add a clear option for continuous reuse of mocks in the existing MockedProvider method before that.
For example, while maintaining the current behavior when no maxUsageCount is provided, we could change the type of maxUsageCount to number | 'infinite' to allow specifying infinite explicitly for infinite reuse of mocks.
Would this approach be acceptable?

```js
import { MockedResponse } from "@apollo/client/testing";

const dogMock: MockedResponse<Data, Variables> = {
  request: {
    query: GET_DOG_QUERY
  },
  variableMatcher: (variables) => true,
  //maxUsageCount: 9999, 
  maxUsageCount: 'infinite',
  result: {
    data: { dog: { id: 1, name: 'Buck', breed: 'poodle' } },
  },
};
```

**Comment by jerelmiller** [comment]
Hey @2012160085 👋 

`maxUsageCount` already handles `Number.POSITIVE_INFINITY` as a valid value. Per our [docs](https://www.apollographql.com/docs/react/development-testing/testing/#reusing-mocks)

> Passing `Number.POSITIVE_INFINITY` will cause the mock to be reused indefinitely.

In fact, we have a [test case](https://github.com/apollographql/apollo-client/blob/e1794c4c1e7b9f90bdf855f1cce75031d2d7fcec/src/testing/react/__tests__/MockedProvider.test.tsx#L678-L727) for this to prove this works.

Does this address what you're looking for?

**Comment by 2012160085** [comment]
Thanks for fast response. I didnt think of Number.POSITIVE_INFINITY.

**Comment by jerelmiller** [comment]
You're welcome! Glad that works for you!
