### ISSUE TITLE
Apollo Client has null values filtered in queries since v3.9.0 when using a type policy

### ISSUE THREAD

**Issue by bengry** [apollographql/apollo-client#11560]
### Issue Description

We have a type policy for handling Relay-like [connection fields](https://www.apollographql.com/docs/technotes/TN0029-relay-style-connections) which broke in Apollo 3.9.0. Works fine in previous versions. See the attached repro for more information, and the behavior in `~3.8.0` vs `>= v3.9.0`.

The difference is that in v3.9.0 onwards, when we get `nodes: null` back from the server, this key gets removed after going through our type policy.

This breaks some of the stuff we rely on, since we look at the shape of the response in some hooks, which checks if `nodes` exists on `data`, which it doesn't in `>= v3.9.0`.

This happens for example in this scenario (see the CSB link to see it live):

For a query that contains a nullable field, such as this:
```gql
extend type Query {
  dogs(after: String, first: Int): DogConnection!
}

type DogConnection {
  edges: [DogEdge!]
  nodes: [Dog!]
  pageInfo: PageInfo!
  totalCount: Int!
}

type PageInfo {
  totalCount: Int!
  hasNextPage: Boolean!
  endCursor: String
}

type DogEdge {
  node: Dog!
  cursor: String!
}

type Dog {
  id: ID!
  name: String!
  ...
}
```

If the backend returns:
```json
{
    "data": {
        "dogs": {
            "nodes": null,
            "pageInfo": {
                "hasNextPage": false,
                "endCursor": null,
                "__typename": "PageInfo"
            },
            "totalCount": 0,
            "__typename": "DogConnection"
        }
    }
}
```

for the following code:
```tsx
function MyComponent() {
  const { data } = useDogsQuery({ ... });
}

gql`
	query Dogs($first: Int!, $after: String!) {
	  dogs(first: $first, after: $after) {
	    nodes {
	      id
	    }
	    pageInfo {
          hasNextPage
	      cursor
	    }
	    totalCount
	  }
	}
```

in Apollo Client 3.8.x, `data` is:
```ts
const data = {
    "nodes": null, // ❗ Notice that `nodes` is kept in the object, just as `null`
    "pageInfo": {
        "hasNextPage": false,
        "endCursor": null,
        "__typename": "PageInfo"
    },
    "totalCount": 0,
    "__typename": "DogConnection"
}
```

While in 3.9.x, `data` is:
```ts
const data = {
    // ❗ Notice that the `nodes` key is removed from the object entirely
    "pageInfo": {
        "hasNextPage": false,
        "endCursor": null,
        "__typename": "PageInfo"
    },
    "totalCount": 0,
    "__typename": "DogConnection"
}
```

### Link to Reproduction

[https://codesandbox.io/p/devbox/peaceful-chihiro-p75rds](https://codesandbox.io/p/devbox/peaceful-chihiro-p75rds?file=%2Fsrc%2Findex.jsx)

### `@apollo/client` version

3.9.0

**Comment by alessbell** [comment]
Hi @bengry 👋 Thanks for providing the reproduction - unfortunately I'm not able to access it:

![CleanShot 2024-02-01 at 15 25 25](https://github.com/apollographql/apollo-client/assets/5139846/2e604886-7b6a-4bf1-97c8-6a128ed3d806)

Would you mind checking that it's shared publicly (assuming that was your intent)? Thanks!

**Comment by bengry** [comment]
> Hi @bengry 👋 Thanks for providing the reproduction - unfortunately I'm not able to access it:
> 
> ![CleanShot 2024-02-01 at 15 25 25](https://private-user-images.githubusercontent.com/5139846/301636806-2e604886-7b6a-4bf1-97c8-6a128ed3d806.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MTk1NTgsIm5iZiI6MTcwNjgxOTI1OCwicGF0aCI6Ii81MTM5ODQ2LzMwMTYzNjgwNi0yZTYwNDg4Ni03YjZhLTRiZjEtOTdjOC02YTEyOGVkM2Q4MDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMjAyNzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjVmN2RkOTg0YTg4NjI5YWYzN2M2ZThkNjc0ZjRmOTI2YmI0Y2MxNTQ0YmYxMTU1YTAzOTAxY2VlNTJkODc4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.o9pOGUGKgzJZlFCi8xrLtxNzz-jan0Y2Rh326uonXqQ)
> 
> Would you mind checking that it's shared publicly (assuming that was your intent)? Thanks!

Woops, try again now please

**Comment by alessbell** [comment]
@bengry yes, I can view it now. I'll need to dig into this a bit more and I'm nearing the end of my day, but will take a look as soon as I can. Thanks!

**Comment by varbrad** [comment]
Just adding a comment here to say we're experiencing the same issue, it appears our defined `typePolicies` are being ignored and certain types we do not wish to normalise are being erroneously included in the cache, which then breaks several things across our tests and application 👍🏻

**Comment by eltonio450** [comment]
I think the same happens with empty lists

**Comment by alessbell** [comment]
Hi all 👋 This regression is related to the bug fix in https://github.com/apollographql/apollo-client/pull/11202. We're looking into it and should have an update soon, thanks for your patience.

**Comment by alessbell** [comment]
The fix will go out in a next patch release in the next day or two - I've tested snapshot release `0.0.0-pr-11576-20240206204955` with your sandbox @bengry and the bug no longer occurs. Thank you for reporting this issue!
