### ISSUE TITLE
`ERR_UNSUPPORTED_DIR_IMPORT` when importing `@apollo/client/core`

### ISSUE THREAD

**Issue by andreialecu** [apollographql/apollo-client#11569]
### Issue Description

I was migrating a test suite from `jest` to `vitest`, which seems to be stricter about how imports are handled, and ran into an issue where `apollo-angular` imports from `@apollo/client/core`, but this results in this error:

```
Error: Directory import '/home/projects/vitest-dev-vitest-7x42dr/node_modules/@apollo/client/core' is not supported resolving ES modules imported from /home/projects/vitest-dev-vitest-7x42dr/node_modules/apollo-angular/fesm2022/ngApollo.mjs
Did you mean to import @apollo/client/core/core.cjs?
```

The documentation mentions that imports from `@apollo/client/core` are recommended in: https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/#using-apollo-client-without-react

I initially created a bug report in Vite here: https://github.com/vitejs/vite/issues/15795

A contributor there pointed out that this also fails with pure Node, which is true.

This was previously mentioned in the issue https://github.com/apollographql/apollo-client/issues/9925 but was closed without being looked at.

I suspect this may become much more visible shortly because Angular is migrating to Vite for its build system, so it may uncover this issue for users of `apollo-angular` at least.

Related issues: 
https://github.com/apollographql/apollo-client/issues/9925
https://github.com/vitejs/vite/issues/15795
https://github.com/kamilkisiela/apollo-angular/issues/2172

### Link to Reproduction

https://stackblitz.com/~/edit/vitest-dev-vitest-smbxnz?file=repro.mjs

### `@apollo/client` version

3.9.2

**Comment by andreialecu** [comment]
The correct solution could be to implement export maps. Here's some inspiration from `@angular/core`:

https://yarnpkg.com/package?q=%40angular%2Fcore&name=%40angular%2Fcore&file=%2Fpackage.json

**Comment by andreialecu** [comment]
I opened PR #11570 with a change to build the export maps.

**Comment by alessbell** [comment]
Hi @andreialecu 👋 The discussion related to this issue occurred over on your PR https://github.com/apollographql/apollo-client/pull/11570 but I wanted to close the loop here: given https://github.com/kamilkisiela/apollo-angular/issues/2172, and since we already have a tracking issue for adding `exports` in package.json https://github.com/apollographql/apollo-client/issues/9976, I'm going to go ahead and close this issue. Thanks!
