### ISSUE TITLE
improperly escaped error arguments for go.apollo.dev links

### ISSUE THREAD

**Issue by david-morris** [apollographql/apollo-client#11572]
### Issue Description

Error links are not formatting correctly for me.

When I follow links from files which have had console output written to them, it looks like this:
![image](https://github.com/apollographql/apollo-client/assets/5530960/b05d2336-8fba-4d90-aca7-6343bf7bdda5)

When I follow the link directly on the command line, there appear to be arguments missing: 
![image](https://github.com/apollographql/apollo-client/assets/5530960/41d1d0c8-a79b-492b-b74d-d3e76f4d405f)

Here's how it looks in browser:
![image](https://github.com/apollographql/apollo-client/assets/5530960/1ca36034-8044-48e7-9bc8-41541b752dcc)

### Link to Reproduction

https://go.apollo.dev/c/err#%7B%22version%22%3A%223.8.1%22%2C%22message%22%3A10%2C%22args%22%3A%5B%5D%7D, towerClusters, {"__typename":"WindTurbine","id":"turb-20002","capacity":1000,"defaultHubHeight":70,"defaultTowerType":"STEEL","defaultFoundationType":1,"defaultGearType":1,"pk":"20002","name":"AK-12","rotorDiameter":91,"manufacturer":{"id":"Manu-1","name":"Nordex","__typename":"WindTurbineManufacturer"}}

### Reproduction Steps

check out this apollo go address:
```
https://go.apollo.dev/c/err#%7B%22version%22%3A%223.8.1%22%2C%22message%22%3A10%2C%22args%22%3A%5B%5D%7D, towerClusters, {"__typename":"WindTurbine","id":"turb-20002","capacity":1000,"defaultHubHeight":70,"defaultTowerType":"STEEL","defaultFoundationType":1,"defaultGearType":1,"pk":"20002","name":"AK-12","rotorDiameter":91,"manufacturer":{"id":"Manu-1","name":"Nordex","__typename":"WindTurbineManufacturer"}}
```

https://go.apollo.dev/c/err#%7B%22version%22%3A%223.8.1%22%2C%22message%22%3A10%2C%22args%22%3A%5B%5D%7D, towerClusters, {"__typename":"WindTurbine","id":"turb-20002","capacity":1000,"defaultHubHeight":70,"defaultTowerType":"STEEL","defaultFoundationType":1,"defaultGearType":1,"pk":"20002","name":"AK-12","rotorDiameter":91,"manufacturer":{"id":"Manu-1","name":"Nordex","__typename":"WindTurbineManufacturer"}}

Clearly there's something that's not escaped properly, potentially a space.

### `@apollo/client` version

3.8.1

**Comment by jerelmiller** [comment]
Hey @david-morris 👋 

Would you try upgrading to version >= [3.8.4](https://github.com/apollographql/apollo-client/releases/tag/v3.8.4)? That release contained https://github.com/apollographql/apollo-client/pull/11195 which fixed some serialization issues with errors that may also fix this one. Thanks!

**Comment by david-morris** [comment]
> Hey @david-morris 👋
> 
> Would you try upgrading to version >= [3.8.4](https://github.com/apollographql/apollo-client/releases/tag/v3.8.4)? That release contained #11195 which fixed some serialization issues with errors that may also fix this one. Thanks!

Thanks for that info! We have a PR already to update to 3.8.10 and I can confirm that this is fixed by then.
