### ISSUE TITLE
Java ApolloClient SocketTimeoutException, how to fix

### ISSUE THREAD

**Issue by AerialSky93** [apollographql/apollo-client#11573]
We are using ApolloClient in Java and receiving this error. How can it be fixed? What timeout config parameters should be added to request headers?

**Code:**

```
apolloClient
    .query(query)
    .toBuilder()
    .requestHeaders(headersData)
    .build()
    .enqueue(new ApolloCall.Callback<>() {
```

**Error:**

`message=com.apollographql.apollo.exception.ApolloNetworkException: Caused by: java.net.SocketTimeoutException: timeout
`

This stacklink is not Apollo specific rather OkHttp library, [java.net.SocketTimeoutException: timeout](https://stackoverflow.com/questions/36455656/java-net-sockettimeoutexception-timeout)

**Comment by jerelmiller** [comment]
Hey @AerialSky93 👋 

I think you're meaning to open this in the [Apollo Kotlin](https://github.com/apollographql/apollo-kotlin) repo 🙂 . This repo contains all the JavaScript/TypeScript client code and doesn't handle Java. Feel free to open this issue over there and I'm sure you'll get the help you need!
