### ISSUE TITLE
Apollo client initiated requests since apollo client v3.9.2 in Nextjs sometimes render as undefined data

### ISSUE THREAD

**Issue by pmualaba** [apollographql/apollo-client#11578]
### Issue Description

Since v3.9.2 of Apollo client we experience unpredictable failed requests which then render undefined data in the UI. It is really hard to reproduce, since refreshing the web page either introduces the issue or remediates the same issue. But what we know for sure is that reverting @apollo/client back to 3.8.10 solves this issue completely.

### Link to Reproduction

https://github.com/apollographql/apollo-client/assets/1754718/3815339e-8fa6-44e8-853a-ed0eba02ed21

### Reproduction Steps

![image](https://github.com/apollographql/apollo-client/assets/1754718/3815339e-8fa6-44e8-853a-ed0eba02ed21)

### `@apollo/client` version

^3.9.2

**Comment by phryneas** [comment]
Could you please validate if this error still persists in `3.9.3`? We reverted a commit there that might have caused an issue like this.

**Comment by pmualaba** [comment]
> Could you please validate if this error still persists in `3.9.3`? We reverted a commit there that might have caused an issue like this.

We use renovate to update our dependencies to the latest version, so indeed we hoped that v3.9.3 would have fixed it, but the issue still remains with v3.9.3. So we reverted back to v3.8.10 which works flawless.

**Comment by Slessi** [comment]
I'm seeing (I assume) the same issue on `3.9.*` but not on `3.8.10`.

We have a lazy query which we fire in a useEffect, flow something like this

- First render, undefined data (no effect run yet)
- Effect runs, query fires
- Second render, we have data now
- Third render (??) now data is gone

<img width="326" alt="image" src="https://github.com/apollographql/apollo-client/assets/3223500/e3ee59fb-e6f4-4907-b32c-1cbcb5061c9e">

I don't know why the third render occurs, but what is interesting to me is I see in the network log a second network call of my lazy query, but there was no second call from my `useEffect` - not sure what told Apollo to re-query it.

**Comment by jerelmiller** [comment]
@Slessi, @pmualaba actually that change just released on [`3.9.4`](https://github.com/apollographql/apollo-client/releases/tag/v3.9.4), not on 3.9.3 😆. Would you mind trying `3.9.4` now that its out?

**Comment by jerelmiller** [comment]
> I see in the network log a second network call of my lazy query

@Slessi I _think_ that might be a different issue than what is originally reported in this issue, but 3.9.4 also contained a [fix](https://github.com/apollographql/apollo-client/pull/11403) for a double network call in some cases. I'd love to know if this addresses that issue.

**Comment by Slessi** [comment]
Yea, 3.9.4 fixes both problems for me

**Comment by alessbell** [comment]
Thanks for confirming, @Slessi. I'm going to go ahead and close this out.
