### ISSUE TITLE
Better types MockedResponse.newData

### ISSUE THREAD

**Issue by Stephen2** [apollographql/apollo-client#11584]
Sorry for the blank issue & run, but I don't have time to make this a PR for next couple of weeks, but didn't want it to get forgotten:

https://github.com/apollographql/apollo-client/blob/65ab695470741e8dcaef1ebd7742c3c397526354/src/testing/core/mocking/mockLink.ts#L38C28-L38C39

should be: `newData?: ResultFunction<FetchResult<TData>, TVariables>;` 

So the `newData` function is properly typed 🙏

**Comment by jerelmiller** [comment]
Good catch! Feel free to submit a PR when you have time!
