### ISSUE TITLE
graphql union type extraction fragment doesn't get mapping field values

### ISSUE THREAD

**Issue by krrrr38** [apollographql/apollo-client#11588]
### Issue Description

When defining union type and getting these fields from fragment, apollo-client doesn't get these values.

### Link to Reproduction

https://github.com/krrrr38/react-apollo-error-template/pull/1

### Reproduction Steps

See the reproduction PR. In this pr, graphql defines `PetData` union data.

```js
union PetData = DogData | CatData

type DogData {
  dogData: String!
}

type CatData {
  dogData: String!
}
```

When accessing data using fragment `AllPetData`, apollo-client doesn't get `dogData` and `catData`.

<img width="674" alt="貼り付けた画像_2024_02_11_22_17" src="https://github.com/krrrr38/react-apollo-error-template/assets/915731/be026a46-5243-4c66-8c7d-45dfc0c084c0">

```graphql
  fragment AllPetData on PetData {
    ... on DogData {
      dogData
    }
    ... on CatData {
      catData
    }
  }
  query AllPeople {
    people {
      id
      name
      pet
      data {
        ...AllPetData
      }
    }
  }
```

For workaround, we should remove fragment.

```graphql
  query AllPeople {
    people {
      id
      name
      pet
      data {
        ... on DogData {
          dogData
        }
        ... on CatData {
          catData
        }
      }
    }
  }
```

### `@apollo/client` version

3.9.4

**Comment by phryneas** [comment]
Hi!

Have you made sure to specify [possibleTypes](https://www.apollographql.com/docs/react/data/fragments/#using-fragments-with-unions-and-interfaces) in your cache configuration?

**Comment by krrrr38** [comment]
wow, it resolves the issue. Thank you so much for the information!

```ts
  cache: new InMemoryCache({
    possibleTypes: {
      PetData: ["CatData", "DogData"],
    }
  }),
```

<img width="613" alt="image" src="https://github.com/apollographql/apollo-client/assets/915731/54fd29e9-0fdf-487c-a2bb-15baf2481445">
