### ISSUE TITLE
Undefined Unable to resolve module ../version.js from ...\node_modules\@apollo\client\core\ApolloClient.js

### ISSUE THREAD

**Issue by arthy89** [apollographql/apollo-client#11629]
I'm having trouble importing Apollo Client into my React Native project.
`import { ApolloClient, InMemoryCache, ApolloProvider } from "@apollo/client";`

This is the error it shows me in the console:

`Unable to resolve "../version.js" from "node_modules\@apollo\client\core\ApolloClient.js" ERROR  [Error: undefined Unable to resolve module ../version.js from ***\node_modules\@apollo\client\core\ApolloClient.js:`

```
None of these files exist:
  * node_modules\@apollo\client\version.js(.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.mjs|.native.mjs|.mjs|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs|.android.scss|.native.scss|.scss|.android.sass|.native.sass|.sass|.android.css|.native.css|.css)
  * node_modules\@apollo\client\version.js\index(.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.mjs|.native.mjs|.mjs|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs|.android.scss|.native.scss|.scss|.android.sass|.native.sass|.sass|.android.css|.native.css|.css)
  2 | import { invariant, newInvariantError } from "../utilities/globals/index.js";
  3 | import { ApolloLink, execute } from "../link/core/index.js";
> 4 | import { version } from "../version.js";
    |                          ^
  5 | import { HttpLink } from "../link/http/index.js";
  6 | import { QueryManager } from "./QueryManager.js";
  7 | import { LocalState } from "./LocalState.js";]
```
In the ApolloClient.js file when searching for the file import { version } from "../version.js"; redirects to "version.d.ts": 

```
export declare const version = "local";
//# sourceMappingURL=version.d.ts.map
```

But if the "version.js" file exists:
```
export var version = "3.9.5";
//# sourceMappingURL=version.js.map
```

I appreciate the help and time to resolve this error.

**Comment by phryneas** [comment]
It seems like your bundler is looking for a `version.js.js` by appending another level of `.js` there. 
We have not encountered anything like this with React Native before - did you change your bundler configuration in your project in any way?

**Comment by arthy89** [comment]
@phryneas I was installing React Navigation and Nativewind dependencies for the latter to install Apollo Client. I think the problem was in the order of the installation, I started again from the beginning installing Apollo and the following ones and now it no longer shows me any errors. Thanks for help and time.

**Comment by phryneas** [comment]
That's great to hear! :)

I'm going to close this issue now - have a great day!
