### ISSUE TITLE
EAS-CLI@7.5.0

### ISSUE THREAD

**Issue by pulse-lrodge** [apollographql/apollo-client#11661]
Hey all,

Has anyone encountered an issue when building on `eas-cli 7.5.0`?

<img width="1294" alt="Screenshot 2024-03-12 at 20 00 44" src="https://github.com/apollographql/apollo-client/assets/151665344/c8f6f9a2-7afb-4b0d-93aa-c6cb58cf4eae">

This was working fine on **7.4.0** but am unable to force the version to **7.4.0** on bitrise?

Any ideas of how we could fix this?

**Comment by jerelmiller** [comment]
Hey @pulse-lrodge 👋 

I'm not quite sure how this fits into Apollo Client or where its being used here. Are you sure you opened the issue in the right repo?

**Comment by pulse-lrodge** [comment]
Looked further into this, and was originally thought to be related to our` apollo/client` imports but seems it's not,

Apologies 🤕

**Comment by jerelmiller** [comment]
No problem! Thanks for confirming. Having a great day!
