### ISSUE TITLE
Cannot bail out of an optimistic update

### ISSUE THREAD

**Issue by TrevPennington** [apollographql/apollo-client#11662]
I am trying to bail out of an optimistic update using `IGNORE` as stated in [the docs](https://www.apollographql.com/docs/react/performance/optimistic-ui/#bailing-out-of-an-optimistic-update)

However, the mutation doesn't even fire because apollo client does not recognize the args. Errors with message: `[TypeError: Cannot read property 'IGNORE' of undefined]`

Does anyone have success with bailing out of an optimistic update?
apollo-client version `3.8.7`

**Comment by alessbell** [comment]
Hi there @TrevPennington 👋 

Thanks for opening this issue! Bailing out of an optimistic update landed in [v3.9.0](https://github.com/apollographql/apollo-client/releases/tag/v3.9.0). That all important context was missing from the docs so I've just opened https://github.com/apollographql/apollo-client/pull/11663 with the fix. Sorry about the confusion - I'll close this issue out, but if you run into any other issues let us know :)
