### ISSUE TITLE
Any callback function on a global level or in a mutation to collect optimistic response failures?

### ISSUE THREAD

**Issue by karan2227** [apollographql/apollo-client#11715]

**Comment by jerelmiller** [comment]
Hey @karan2227 👋 

Would you mind providing a bit more context on what you're looking for? I'm not sure I have enough to go on with just the title alone.

**Comment by karan2227** [comment]
We are using functions like writeFragment, writeQuery etc to update the cache. Now if in case there is some variable mismatch with the underlying mutation/query then cache write fails. This used to give a warning but now the new version of apollo package we are seeing these errors.

Question:  we want to know if we can programmatically apply a common wrapper function to capture all such errors while using the functions writeFragment, writeQuery, `cache.modify`.

**Comment by karan2227** [comment]
any other way apart from console error, to catch these cache write failures of optimistic response object.

**Comment by jerelmiller** [comment]
Unfortunately no we don't have any kind of universal or global handler that you can use when using these APIs directly. `try`/`catch` is your best best for error cases. 

If this is something of interest, do you mind filing a [feature request](https://github.com/apollographql/apollo-feature-requests) with some more detail on what you're looking for?

**Comment by jerelmiller** [comment]
I'm going to go ahead and close this. Again, feel free to open up a [feature request](https://github.com/apollographql/apollo-feature-requests) if you're interested in seeing something like this. Thanks!
