### ISSUE TITLE
is there is any library in react-native that will work like if api post request fails so it will save in own cache and when it will get internet then it will post it

### ISSUE THREAD

**Issue by ramanguptazelhus** [apollographql/apollo-client#11746]
Need help or want to talk all things Apollo Client? Issues here are reserved for bugs, but one of the following resources should help:

* Apollo Discord server: https://discord.gg/graphos
* Apollo GraphQL community forums: https://community.apollographql.com
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests

**Comment by phryneas** [comment]
Hi Raman,

as you can pretty much read in the default issue template that you posted here, the Apollo Client issues are the wrong place to ask usage questions like this.

As a result, I'm going to close this issue.
