### ISSUE TITLE
useApolloClient hook return type

### ISSUE THREAD

**Issue by farmstrong8** [apollographql/apollo-client#11747]
Hello,

I was wondering why the return type of the `useApolloClient` hook is `ApolloClient<object>` ? I'd assume that it would have the same type as when you instantiate a client which is `ApolloClient<NormalizedCacheObject>` . I came across this when i was using the `@dev-plugins/apollo-client` from expo where they are expecting the type to be `ApolloClientType = ApolloClient<NormalizedCacheObject>;` but im getting the client via the hook so there is a type error.

**Comment by phryneas** [comment]
TypeScript unfortunately cannot make a connection between the place where you create your `ApolloClient` instance and the place where you call `useApolloClient` - so that hook has to fall back to some kind of "default" value.

I think that being `object` is not optimal, but it has been that for a very long time, and changing it now might break a few things for very little gain. We might consider it in a future major, but I'd honestly rather not touch it right now.

=> You'll probably have to do something like 

```js
useApolloClientDevTools(useApolloClient() as ApolloClient<any>)
```

**Comment by farmstrong8** [comment]
@phryneas ya i see what you mean i currently use a type assertion to get around it, but im saying the actual return type from the hook is `ApolloClient<object>` when i'd expect it to be `ApolloClient<NormalizedObject>` since that is the return type when you say  `const client = new ApolloClient`

```
import { invariant } from "../../utilities/globals/index.js";
import * as React from "rehackt";
import type { ApolloClient } from "../../core/index.js";
import { getApolloContext } from "../context/index.js";

/**
 * @example
 * ```jsx
 * import { useApolloClient } from '@apollo/client';
 *
 * function SomeComponent() {
 *   const client = useApolloClient();
 *   // `client` is now set to the `ApolloClient` instance being used by the
 *   // application (that was configured using something like `ApolloProvider`)
 * }
 * ```
 *
 * @since 3.0.0
 * @returns The `ApolloClient` instance being used by the application.
 */
export function useApolloClient(
  override?: ApolloClient<object>
): ApolloClient<object> {
  const context = React.useContext(getApolloContext());
  const client = override || context.client;
  invariant(
    !!client,
    'Could not find "client" in the context or passed in as an option. ' +
      "Wrap the root component in an <ApolloProvider>, or pass an ApolloClient " +
      "instance in via options."
  );

  return client;
}
```
