### ISSUE TITLE
`useFragment` doesn't respect the `@nonreactive` directive

### ISSUE THREAD

**Issue by broyde** [apollographql/apollo-client#11785]
### Issue Description

1. Create a fragment with `@nonreactive` field, write some data into the cache.
2. Use this fragment in `useFragment`.
3. Update the value of `@nonreactive` field.

Expected behavior: `useFragment` does not react to such changes.
Actual behavior: `useFragment` triggers update in the same way as it does without `@nonreactive` directive.
Test example: https://github.com/broyde/apollo-use-fragment-nonreactive/blob/main/test.js

FYI: I've noticed the same behavior of `useQuery`, but only in test environment (see test: https://github.com/broyde/apollo-query-nonreactive/blob/main/test.js). In real browser `useQuery` does not react to such changes, but `useFragment` does.

### Link to Reproduction

https://github.com/broyde/apollo-use-fragment-nonreactive

### `@apollo/client` version

3.9.11

**Comment by jerelmiller** [comment]
Hey @broyde 👋 

Thanks for the report! Initially the `@nonreactive` directive was meant for use with queries, not fragments, but we talked about this more as a team and think this change makes sense. We re-read through our docs and realized that its a bit ambiguous on the original intention so we plan to make a temporary docs update until we can get this functionality in place.

We are releasing 3.10 this week and will try and target this change for one of the 3.10.x patch releases.
