### ISSUE TITLE
useQuery fails to resolve ssr renderPromise due to JSON.stringify reordering

### ISSUE THREAD

**Issue by cclp94** [apollographql/apollo-client#11798]
### Issue Description

We found a bug in production where the [`lookupQueryInfo()`](https://github.com/apollographql/apollo-client/blob/main/src/react/ssr/RenderPromises.ts#L140) method would consistently not render a SSR component after calling `renderToStringWithData`. 

Upon investigation, we found that the query was being executed and the result should have been available. However, a second `QueryInfo` would be registered instead of recovering the resolved one. This is due to the `JSON.stringify` method switching the order of attributes when looking up the Map (Check screenshots).

---
<img width="1032" alt="Screenshot 2024-04-19 at 4 27 10 PM" src="https://github.com/apollographql/apollo-client/assets/11381625/ecbd4f7c-c2ec-46e5-85ef-8243105a3e1d">

<img width="1189" alt="Screenshot 2024-04-19 at 4 28 15 PM" src="https://github.com/apollographql/apollo-client/assets/11381625/d4813464-8c28-4d83-bda4-9be0faa58145">

---
I noticed the utilities package already provides a [`canonicalStringify`](https://github.com/apollographql/apollo-client/blob/main/src/utilities/common/canonicalStringify.ts) which would fix this issue.

### Link to Reproduction

https://github.com/apollographql/apollo-client/blob/main/src/react/ssr/RenderPromises.ts#L140

### `@apollo/client` version

3.8.3

**Comment by phryneas** [comment]
That's interesting - are you passing different variables in different situations here?    
I don't think that Apollo Client ever touches variables in a writing manner, and JSON.stringify would always stringify things in the object order.

That said, using `canonicalStringify` absolutely makes sense here. I'll prepare a fix.

**Comment by cclp94** [comment]
Amazing, @phryneas. Thank you for the fast response. 

That's exactly what I found weird about it. We don't pass different variables to it (although I guess the react re-rendering recreates the objects/variables that are passed when the functional component gets re-executed). I tried getting `JSON.stringify` to reproduce the issue in isolation but couldn't.

**Comment by cclp94** [comment]
I am also willing to make the contribution if you are short on time. Let me know.

**Comment by cclp94** [comment]
I just tested it and it seems to fix our issue. Thank you for the help.
