### ISSUE TITLE
[Docs] Anchor links seem to be stripped

### ISSUE THREAD

**Issue by swrobel** [apollographql/apollo-client#11819]
### Issue Description

The Docs website generation seems to be stripping out anchors from links, or something of that sort, as I can see that the [source](https://github.com/apollographql/apollo-client/blob/main/src/react/types/types.documentation.ts) contains the proper anchor links for "GraphQL error policies" and "Setting a fetch policy" but the [Docs page](https://www.apollographql.com/docs/react/data/queries/#options) does not include those anchors in those links.

### Link to Reproduction

https://www.apollographql.com/docs/react/data/queries/#options

### Reproduction Steps

1. Visit `useQuery` [options docs](https://www.apollographql.com/docs/react/data/queries/#options)
2. Follow a link that should resolve to an anchor on another docs page, such as "GraphQL error policies" or "Setting a fetch policy"
3. Note that you are just taken to the page that contains that anchor, not to the anchor itself

### `@apollo/client` version

n/a

**Comment by bignimbus** [comment]
Thanks @swrobel for reporting this!  We'll take a look 👀

**Comment by phryneas** [comment]
This should be fixed soon with https://github.com/apollographql/docs/pull/847

**Comment by phryneas** [comment]
The fix is live - thank you for the report!
