### ISSUE TITLE
Feedback for schema-driven testing utilities

### ISSUE THREAD

**Issue by alessbell** [apollographql/apollo-client#11817]
### Issue Description

Starting with Apollo Client [3.10.0](https://github.com/apollographql/apollo-client/releases/tag/v3.10.0), we introduced new schema-driven testing APIs.

These utilities allow you to create a test schema with scalar mocks that can be used to mock fetch or used in combination with MSW to write integration- or E2E-style tests that also test the [link chain](https://www.apollographql.com/docs/react/api/link/introduction). [See the documentation for details.](https://www.apollographql.com/docs/react/development-testing/schema-driven-testing) We've marked these APIs as experimental for this release to allow room for feedback and changes before we stabilize this API in 3.11.0.

If you would like to provide feedback or suggestions for improvement, please drop a comment below!

### Link to Reproduction

N/A

### `@apollo/client` version

N/A

**Comment by alessbell** [comment]
One piece of feedback from @yaboi:

> Is there a way to access a schema not available locally? Maybe with codegen or something?

**Comment by jerelmiller** [comment]
Closing as this was released and moved over to GraphQL testing library
