### ISSUE TITLE
Add `subscribeToMore` functionality to `useQueryRefHandlers`, `useBackgroundQuery`

### ISSUE THREAD

**Issue by bignimbus** [apollographql/apollo-client#11818]
Context: https://community.apollographql.com/t/how-to-use-subscriptions-together-with-preloadquery/7434/3

Some of our hooks include `subscribeToMore` in the results object.  We want to ensure that all relevant hooks include `subscribeToMore`, including `useQueryRefHandlers` and `useBackgroundQuery`.

**Comment by jerelmiller** [comment]
Finished with #11923 and will be released in 3.11
