### ISSUE TITLE
BatchHTTPLink is not monitoring friendly

### ISSUE THREAD

**Issue by dbasilio** [apollographql/apollo-client#11849]
### Issue Description

We're trying to integrate Datadog RUM, which attaches headers to outgoing requests if they match certain patterns. When using HTTPLink, the headers are always correctly attached. When using BatchHTTPLink, the headers are not attached. This was previously not working for HTTPLink but was fixed in https://github.com/apollographql/apollo-client/pull/8603, but that same fix was not applied to BatchHTTPLink.

BatchHTTPLink is maintaining a local reference to fetch that monitoring tools cannot inject headers into.

### Link to Reproduction

https://github.com/dbasilio/apollo-dd-rum-repro

### Reproduction Steps

See the readme in the repro repo

### `@apollo/client` version

3.8.10

**Comment by dbasilio** [comment]
Related Issues:
- https://github.com/apollographql/apollo-client/issues/7130
- https://github.com/apollographql/apollo-client/issues/7832

**Comment by alessbell** [comment]
Hi @dbasilio 👋 Thanks for opening this issue - the reproduction and linked issues are helpful :) I'll get this on our team agenda, thanks!

**Comment by alessbell** [comment]
Quick update, I have a PR open here: https://github.com/apollographql/apollo-client/pull/11860

**Comment by alessbell** [comment]
The fix be included in the next patch release, v3.10.5, which will go out later this week 🚀
