### ISSUE TITLE
clearStore causes a crash when there is an active query

### ISSUE THREAD

**Issue by ach5910** [apollographql/apollo-client#11846]
### Issue Description

If `client.clearStore` is called while a query response is pending, it's causing a crashing at this location https://github.com/apollographql/apollo-client/blob/main/src/react/hooks/useQuery.ts#L635. 

<img width="415" alt="Screenshot 2024-05-15 at 9 05 37 AM" src="https://github.com/apollographql/apollo-client/assets/15445630/6e40076b-29bd-45d2-b278-2382290302ea">

I am using
- `apollo3-cache-persist@0.14.1`
- `apollo-link-token-refresh@0.6.1`
- `@muchobien/apollo-persistence-mapper@npm:^1.0.0`
- `apollo-link-sentry@3.3.0` 

and here's how I am initializing my client
```ts
persistCacheSync({
  cache,
  storage: new MMKVWrapper(mmkvStorage),
  persistenceMapper,
  trigger: "write",
  debug: __DEV__,
});

const persistLink = createPersistLink();

const client = new ApolloClient({
  cache,
  link: from([
    persistLink,
    sentryBreadcrumbsLink,
    retryLink,
    authLink,
    tokenRefreshLink,
    errorLink,
    httpLink,
  ]),
});
```

I've also tried using `resetStore`, but I get the same error. Any feedback regarding a potential cause is greatly appreciated.

### Link to Reproduction

N/A

### `@apollo/client` version

3.9.11

**Comment by bignimbus** [comment]
Hi @ach5910 👋🏻 thanks for letting us know!  I'll chat with the team soon to see if there's anything that immediately jumps out as a bug in Apollo Client.  Are you able to reproduce this issue in a clean app (e.g. without the other libraries)?

**Comment by Nehal-Zeller** [comment]
Facing the same error, is there any way we can kill all pending active queries?

**Comment by ach5910** [comment]
@bignimbus Unfortunately I couldn't reproduce the bug in a sandboxed app due to the complexity of mirroring our production app's infrastructure. I know that not much help in diagnosing the problem, but I was really hoping I was missing something basic and I'd get a "RTFD" response.

@Nehal-Zeller I found a solution by calling `client.cache.reset()` instead of `client.clearStore()` or `client.resetStore()`. I believe any active requests will update the cache if returned after resetting, but it beats having the app crash. Hope this helps!

**Comment by mikolajadamowicz** [comment]
I am facing the same issue. I believe that `client.cache.reset()` is not killing the pending query thus it will be written to cache once the response is returned.

**Comment by DerekWang98** [comment]
Am also facing this issue for a while now. Upgraded to `@apollo/client@3.11.1` and am still able to reproduce this error by running a query and then calling `client.clearStores()`.

**Comment by jerelmiller** [comment]
@DerekWang98 are you seeing the same stack trace and error as above (unexpected), or are you seeing an error with a message of `Store reset while query was in flight (not completed in link chain)`. If the latter, this is expected behavior, but if the former, then a reproduction of the issue would be greatly appreciated.

**Comment by DerekWang98** [comment]
Hey @jerelmiller, I get the same error stack trace error in `node_modules/@apollo/client/react/hooks/useQuery.js`

To reproduce the issue, go to search in the sandbox preview and press "OK" to reproduce the bug. I ran a lazy query and then quickly performed `clearStore()` in `/src/components/Search.js` to simulate it.

[CodeSandbox](https://codesandbox.io/p/sandbox/dazzling-dream-d2cx8n?layout=%257B%2522sidebarPanel%2522%253A%2522SEARCH%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzggx01600063b6j7rmyduiw%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzggx01600023b6jknkb40rl%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzggx01600033b6jc12aj3lo%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzggx01600053b6jc74oabe9%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzggx01600023b6jknkb40rl%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzggx01500013b6jh9q4c62y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzgiomnw00023b6jibkoun1t%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FSearch.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clzggx01600023b6jknkb40rl%2522%252C%2522activeTabId%2522%253A%2522clzgiomnw00023b6jibkoun1t%2522%257D%252C%2522clzggx01600053b6jc74oabe9%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzggx01600043b6j1zcd0yns%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%255D%252C%2522id%2522%253A%2522clzggx01600053b6jc74oabe9%2522%252C%2522activeTabId%2522%253A%2522clzggx01600043b6j1zcd0yns%2522%257D%252C%2522clzggx01600033b6jc12aj3lo%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzggx01600033b6jc12aj3lo%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Thanks for looking into it!

**Comment by phryneas** [comment]
@DerekWang98 I can reproduce your situation, but it's a different bug. 

Your codepath comes from `complete` while the original issue comes from `notifySubscription`. I'll move this over to a new issue :)
