### ISSUE TITLE
Getting A on the result.data

### ISSUE THREAD

**Issue by puneetkansal04** [apollographql/apollo-client#11847]
### Issue Description

var data = result.data; result.partial; var resultWithoutPartial = tslib.__rest(result, ["data", "partial"]);
        this.toQueryResultCache.set(result, (queryResult = tslib.__assign(tslib.__assign(tslib.__assign({ data: data }, resultWithoutPartial), this.obsQueryFields), { client: this.client, obser

vable: this.observable, variables: this.observable.variables, called: !this.queryHookOptions.skip, previousData: this.previousData })));
        

        
<img width="322" alt="Screenshot 2024-05-16 at 11 10 20 AM" src="https://github.com/apollographql/apollo-client/assets/48505993/b5981ee1-9692-43f9-856f-c2da5c9e0c72">

### Link to Reproduction

@apollo/client

### Reproduction Steps

Getting this issue if I fired an api with the expired token and it throws a error of unauthorised.

### `@apollo/client` version

3.10.4

**Comment by jerelmiller** [comment]
Possibly related https://github.com/apollographql/apollo-client/issues/11846
