### ISSUE TITLE
Support extensions in useSubscription

### ISSUE THREAD

**Issue by jcostello-atlassian** [apollographql/apollo-client#11856]
The graphql-ws spec lists an optional extensions object on subscribe messages

https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md

**Comment by alessbell** [comment]
Hi @jcostello-atlassian 👋 I'll echo what @phryneas said over on your PR - thanks for opening it and we'll review it as soon as we're able to :)

**Comment by phryneas** [comment]
[Version 3.11](https://github.com/apollographql/apollo-client/releases/tag/v3.11.0) has been released with this feature.
