### ISSUE TITLE
NextJS with "useSuspenseQuery" not passing headers to request

### ISSUE THREAD

**Issue by EfstathiadisD** [apollographql/apollo-client#11868]
### Issue Description

I have a NextJS 14 Application on Pages Router. I have a Query run with `useSuspendQuery`, which doesn't pass the `headers: { Cookie: "" }` from the context. Both SSR and CSR Queries and Mutations work like a charm. How is Suspended Query different?

To verify the issue, I passed the Cookie as a hardcoded value to `context: { headers: { Cookie: "VALID_VALUE" } }` and it worked, but according to the docs it should read the default context. I guess that's the real culprit here.

### Link to Reproduction

[Codesanbox](https://codesandbox.io/p/devbox/spring-wood-7kwl2q?file=%2Fsrc%2Flink.js%3A3%2C22-3%2C32&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwlx0oxn00073b6e3mpo70nq%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwlx0oxm00023b6e5rm5l1g7%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwlx0oxm00043b6eawohn4mj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwlx0oxm00063b6ea7di0vsq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwlx0oxm00023b6e5rm5l1g7%2522%253A%257B%2522id%2522%253A%2522clwlx0oxm00023b6e5rm5l1g7%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwlx183l004t3b6ezlgytdg0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A2%252C%2522startColumn%2522%253A13%252C%2522endLineNumber%2522%253A2%252C%2522endColumn%2522%253A13%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clwozu46t00023b6f9e74zerh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A3%252C%2522startColumn%2522%253A22%252C%2522endLineNumber%2522%253A3%252C%2522endColumn%2522%253A32%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Flink.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clwozu46t00023b6f9e74zerh%2522%257D%252C%2522clwlx0oxm00063b6ea7di0vsq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwlx0oxm00053b6e48yambe5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwlx0oxm00063b6ea7di0vsq%2522%252C%2522activeTabId%2522%253A%2522clwlx0oxm00053b6e48yambe5%2522%257D%252C%2522clwlx0oxm00043b6eawohn4mj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwlx0oxm00033b6e7voe5a5x%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522id%2522%253A%2522clwlx0oxm00043b6eawohn4mj%2522%252C%2522activeTabId%2522%253A%2522clwlx0oxm00033b6e7voe5a5x%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Reproduction Steps

FYI: The reproduction isn't representable cause no requests are made. But my setup is pretty simple and aside from the suspenseQuery everything else work like a charm.

Here is some code I have for reference:
```ts
import type { NormalizedCacheObject, QueryOptions } from "@apollo/client";
import { ApolloClient, HttpLink, InMemoryCache, from } from "@apollo/client";
import { setContext } from "@apollo/client/link/context";
import { onError } from "@apollo/client/link/error";
import type { Context, Middleware } from "@workspace/types";

import { isNotNull } from "@workspace/utils";

const isBrowser = typeof window !== "undefined";

type GraphQLClient = typeof apolloClient;
let apolloClient: ApolloClient<NormalizedCacheObject> | null = null;

const API_URI = isBrowser
  ? process.env["NEXT_PUBLIC_API_HOST"]
  : process.env["NEXT_INTERNAL_API_HOST"];

/* eslint-disable no-console */
function createLink(props: { context?: QueryOptions["context"] }) {
  const httpLink = new HttpLink({ uri: API_URI, credentials: "include" });

  const authLink = props.context
    ? setContext((_, { headers }) => ({
        headers: {
          ...headers,
          ...props.context?.headers,
        },
      }))
    : null;

  const errorLink = onError(({ graphQLErrors, networkError }) => {
    if (graphQLErrors) {
      graphQLErrors.forEach(({ message, path, extensions }) => {
        if (extensions?.code === "UNAUTHENTICATED") {
          return;
        }

        console.error("[GraphQL error]:", { message, path });
      });
    }

    if (networkError) {
      console.log("[Network error]:", networkError);
    }
  });

  const links = [errorLink, authLink, httpLink].filter(isNotNull);

  return from(links);
}

type CreateClientProps = {
  context?: QueryOptions["context"];
};

function createClient(props: CreateClientProps) {
  const link = createLink({
    context: props.context,
  });

  return new ApolloClient({
    link,
    ssrMode: !isBrowser,
    cache: new InMemoryCache(),
  });
}

function initApollo(props: Omit<CreateClientProps, "uri"> = {}) {
  if (!isBrowser) {
    return createClient({ ...props });
  }

  if (!apolloClient) {
    apolloClient = createClient({ ...props });
    return apolloClient;
  }

  return apolloClient;
}

function withApollo<T extends Context>(
  fn: Middleware<T, { graphql: ReturnType<typeof initApollo> }>,
) {
  return (ctx: T) => {
    const graphql = initApollo({
      context: {
        headers: {
          Cookie: ctx.req.headers.cookie,
        },
      },
    });

    return fn({ ...ctx, graphql });
  };
}

export type { GraphQLClient };
export { initApollo, withApollo };
```
I use the above to init the client with the provider and using the withApollo for SSR requests. But the suspense one doesn't work. it doesn't pass the headers. The setup is identical to what I have in the repro just with actual calls..

### `@apollo/client` version

3.10.4

### UPDATE

I checked with the latest versions as well as 3.8.10 which was the previous one i was using in another repo and still doesn't work. The issue seems to be present in the App Dir as well, but I don't think it has anything to do with NextJS tbh, but could be wrong.

**Comment by phryneas** [comment]
Hi Efstathiadis,

the CodeSandbox is set to private, could you please make it public?

**Comment by EfstathiadisD** [comment]
> Hi Efstathiadis,
> 
> 
> 
> the CodeSandbox is set to private, could you please make it public?

Sorry for that. I think it should be public now..

**Comment by phryneas** [comment]
I have to admit that I'm a bit confused what the Codesandbox is showing. 
It doesn't seem like you're setting any headers anywhere in the CodeSandbox.

Could you explain a bit what I should look for here to see this reproduced?
