### ISSUE TITLE
Can you use `useFragment` with a type that doesn't have an id?

### ISSUE THREAD

**Issue by patrick91** [apollographql/apollo-client#11875]
Hi, I'm trying `useFragment` with a query that looks like this:

```graphql
{
  flyers {
    edges { ... }   
    someStats { ... }
  }
}
```

I'd like to split the query this way:

```graphql
{
  flyers {
    ...FlyersEdgesFragment
    ...FlyersEdgesStats
  }
}
```

but it doesn't seem to work 😊 Is my understanding correct that `useFragment` "only" works with types that have an ID?

**Comment by bignimbus** [comment]
Hi @patrick91 👋 miss you! A way to identify the entity object in the cache is needed for `useFragment`. See https://www.apollographql.com/docs/react/api/react/hooks#usefragment, specifically, the `from` attribute. So if you can identify a fragment by its type and an `id`, that's probably the most straightforward way. But if there are other valid identifiers that could be used (in combination with `keyFields`) then that should work too. Hope that helps!

**Comment by patrick91** [comment]
@bignimbus I was pretty tired when I was trying the `useFragment` hook, and I was expecting something more magic.

I've ended up using fragments, but passing the data down directly to the component using the fragment, since I don't have a unique identifier for the flyers field 😊
