### ISSUE TITLE
Adding graphql-tag-swc-plugin to performance docs for apollo client

### ISSUE THREAD

**Issue by rishabh3112** [apollographql/apollo-client#11872]
Hi there,
I am author of [`graphql-tag-swc-plugin`](https://github.com/rishabh3112/graphql-tag-swc-plugin) which is essentially swc port for [`babel-plugin-graphql-tag`](https://www.npmjs.com/package/babel-plugin-graphql-tag).

I am proposing to add this to Performance docs of Apollo Client here: https://www.apollographql.com/docs/react/performance/babel . If this is a welcoming addition,  I happy to raise PR for the same.

For context, This is being used on a large enterprise project ( ~20k entry point ) for past 5 - 6 months w/o issues.

Thanks!

**Comment by jerelmiller** [comment]
Hey @rishabh3112 👋 

Let me take this to the team to chat about it and I'll get back to you. Thanks for letting us know about it!

**Comment by jerelmiller** [comment]
@rishabh3112 we've discussed as a team and have no issues introducing this to our docs. If you'd like to open a PR, we'd welcome it. Thanks so much!

**Comment by rishabh3112** [comment]
@jerelmiller created PR, please check : https://github.com/apollographql/apollo-client/pull/11884
