### ISSUE TITLE
Typeguard for useQuery fails when the queryOptions passed using spread operator

### ISSUE THREAD

**Issue by ashishbairwa** [apollographql/apollo-client#11874]
### Issue Description

When we pass query options in spread operator, it escapes type checking which results in unexpected issues and behaviour

Sample query use which fails typechecking:
```
const {
  loading: getUserInfoLoading,
  error: getUserInfoError,
  data: getUserInfoData,
} = useQuery(GET_USER_INFO, {
  variables: { uuid: memberId },
  skip: validUrlParams === false,
  errorPolicy: 'all',
  fetchPolicy: 'network-only',
  notifyOnNetworkStatusChange: false,
});
```

### Link to Reproduction

https://stackblitz.com/edit/react-apollo-client-demo-oldapm?file=src%2FCountryDetail.js

### Reproduction Steps

1. Import useQuery
2. Prepare options and pass them via spread operator
3. Observe apollo-client working without throwing any error

### `@apollo/client` version

3.6.6

**Comment by bignimbus** [comment]
Hi @ashishbairwa 👋🏻  I'm a middling TypeScript practitioner at best, but I think you're seeing a default behavior of TypeScript.  Here's a TS Playground demonstrating the same behavior without Apollo Client:

https://www.typescriptlang.org/play/?#code/C4TwDgpgBAYg9nKBeKBvAUFKAzBAuKAZWACcBLAOwHMBuTKAIwEMSDjzq6BfddAYzgUAzsBz5YCZGnq44BAOSz5AGnrNWUeepX0AdPtSMmALwXNj8qF1Vc6-QULgAbCLqdwqAClkBKGkA

<img width="1013" alt="Screenshot 2024-05-31 at 2 09 27 PM" src="https://github.com/apollographql/apollo-client/assets/3976692/9fe1a235-90d4-4dae-85ab-458748ddf90f">
<img width="1013" alt="Screenshot 2024-05-31 at 2 08 43 PM" src="https://github.com/apollographql/apollo-client/assets/3976692/d0a8d3f4-b5cf-4e3b-9980-8a9860c33a9d">

That said, I'll check with the team to see if it's possible/advisable to implement some kind of utility type for this use case and get back to you!

**Comment by bignimbus** [comment]
Also, I'm not certain your stackblitz or code snippet is entirely illustrative of the issue - the former is in JavaScript and the latter doesn't use a spread operator, so I tried to recreate this in our [Spotify Showcase](https://github.com/apollographql/spotify-showcase) from your description.

**Comment by bignimbus** [comment]
Hi @ashishbairwa - we've discussed some pros and cons and won't be moving forward with attempting to narrow the types in this way.  Doing so could be backwards-incompatible for some users, and we don't see a straightforward way to implement such an abstraction without a considerable amount of work.  In the interim I recommend adding the relevant type annotations to the objects that you spread into `useQuery`.  Thanks!
