### ISSUE TITLE
PossibleTypes not working as intended

### ISSUE THREAD

**Issue by Gowthaman-Opti-Twin** [apollographql/apollo-client#11878]
I have a query that uses union types inside it. 

*sample query*
```
person {
      ... on jedi{
        id
        lightsaber
      }
      ... on mandalorian{
        id
        beskar
      }
    }
```

when I try to use ```useQuery``` from apolloClient it is returning the person object with empty brackets ```[{},{}]``` but when using `fetch()` it is returning ```[{id:232, lightsaber:green},{id:242, beskar: old}]```

I tried specifying the union type in the apollo client

```
const client = new ApolloClient({
  link: concat(authMiddleware, httpLink),
  cache: new InMemoryCache({
    addTypename: false,
    possibleTypes:{Person:['jedi','mandalorian']}
  }),
})
```

it is not returning the any properties inside the object just an empty object `{}`

here is the useQuery

```const {data:QueryData} = useQuery<PersonQuery>(GET_PERSON)```

**Comment by dylanwulf** [comment]
```
addTypename: false,
```

This part is likely your problem. Apollo client needs to have the `__typename` field available for this functionality to work correctly

**Comment by alessbell** [comment]
Yes, thanks @dylanwulf!

@Gowthaman-Opti-Twin can you confirm this solved your issue?

**Comment by Gowthaman-Opti-Twin** [comment]
Yep, that's the issue. It is working fine now. Thanks
