### ISSUE TITLE
Refetch query with new variables at runtime when using skip

### ISSUE THREAD

**Issue by mskec** [apollographql/apollo-client#1189]
Hey,

I encountered this problem https://github.com/apollostack/apollo-client/issues/131#issuecomment-265002530 with my query. This is query config:
```javascript
{
    skip: ({ code }) => !code,
    options: ({ code }) => ({ variables: { code } }),
}
```

This is how my data changes:
Initially `code` is `undefined`, query is not executed.
`code` changes to some string and query is correctly executed.
`code` is again changed to `undefined`.
`code` is changed to some string and new query is **not** executed.

This is console log output which might clarify this a bit more:
```
get.shouldSkip: true code: undefined

get.shouldSkip: false code: 'some code'
get.options code: 'some code'

get.shouldSkip: true code: undefined

get.shouldSkip: false code: 'new code'
get.options code: 'new code'
```

If I remove `skip` option, query will correctly execute on every `code` prop change, but will also execute when it is `undefined` which I kinda want to avoid.

**Comment by calebmer** [comment]
Hi @mskec, could you submit a PR with a failing test? It will help us prioritize your issue and fix it quickly 😊

**Comment by mskec** [comment]
@calebmer Now I see this option is defined in [react-apollo](https://github.com/apollographql/react-apollo) and not here, should I open issue there?
I updated to latest `react-apollo` version and now query is being executed correctly on skip changes. But there is new problem where the same query is being executed twice at the same time.

**Comment by calebmer** [comment]
Yes, if you could open an issue on `react-apollo` that would be ideal.
