### ISSUE TITLE
useFragment throws an error when a fragment has the @include directive

### ISSUE THREAD

**Issue by dragozin** [apollographql/apollo-client#11924]
### Issue Description

If I use a fragment with the `@include` directive `useFragment` react hook throws an error `Invalid variable referenced in @include directive.`

### Link to Reproduction

https://codesandbox.io/p/sandbox/apollo-client-bug-5xym9k

### `@apollo/client` version

3.10.8

**Comment by phryneas** [comment]
Thank you for the report - I've opened a PR with (hopefully) a fix. 
Could you please give this release a try and report back if it solves your problem?

```sh
npm i @apollo/client@0.0.0-pr-11926-20240704151615
```

**Comment by dragozin** [comment]
> Could you please give this build a try and report back if it solves your problem?

Hello! Thank you for the quick fix! Yes, it helps!
