### ISSUE TITLE
createFragment() still documented even though deprecated (and no longer existent)

### ISSUE THREAD

**Issue by greduan** [apollographql/apollo-client#1193]
http://dev.apollodata.com/core/fragments.html#createFragment

**Comment by stubailo** [comment]
I think the underlying issue here is that we don't have an automated way of updating the API docs for a new release. If we could somehow do it over greenkeeper that would be awesome...

**Comment by okbel** [comment]
Also there are several tests that include createFragment i.e with react-apollo [https://github.com/apollostack/react-apollo/blob/master/test/react-web/client/graphql/fragments.test.tsx](https://github.com/apollostack/react-apollo/blob/master/test/react-web/client/graphql/fragments.test.tsx)

**Comment by abhiaiyer91** [comment]
@stubailo, maybe something like documentationjs ?

**Comment by calebmer** [comment]
Or we move everything into a monorepo with Lerna and enforce docs change with code changes in the PR process. Move in `react-apollo`, docs, the whole 9 yards 😊

(just sayin’, I know @stubailo has strong feelings lol 😉)

**Comment by abhiaiyer91** [comment]
@calebmer maybe we should start a thread for that.

**Comment by GregYeo** [comment]
thanks @calebmer 

I recently did version up.

"apollo-client": "^0.5.25" to  "apollo-client": "^0.8.1",
 "react-apollo": "^0.7.1" to "react-apollo": "^0.9.0"

 Then, createFragment occurs problem because it is missing from apollo-client. 

The document is making me confused. because API not exists and typings and source file doesn't have the API but still document is saying.

If somebody is having trouble with it.
Please check this document (A) instead of (B)

(A) New, Maybe replaced(I'm not sure)
http://dev.apollodata.com/react/fragments.html

(B) Old, deprecated API 
http://dev.apollodata.com/core/fragments.html

**Comment by abhiaiyer91** [comment]
@GregYeo `createFragment` was deprecated from Apollo Client in favor of handling this interface in `graphql-tag`

The documentation needs to be updated.

**Comment by helfer** [comment]
@greduan thanks for pointing it out, I've removed it from the docs!

**Comment by rogchap** [comment]
@helfer Still see this here: http://dev.apollodata.com/core/fragments.html

**Comment by helfer** [comment]
Thanks for pointing it out @rogchap. It seems our automatic build and deploy process broke at some point. Going to fix it now.

**Comment by helfer** [comment]
I fixed the build, updated the API docs to the most recent version and removed links to fragments. I think I'd have to go to S3 and remove the file manually if I wanted to delete it for good, but I don't believe that's necessary as long as there are no more links to it from the docs themselves.

@stubailo I think we could automatically update the API docs with greenkeeper if we released an apollo-client-source package or included the uncompiled source in the current package. Without that, it's not currently possible.

**Comment by calebmer** [comment]
@helfer we should include the uncompiled source in the current package. I think that’s just good practice anyway for people who want their own custom builds. I’d like to take a look at the build process as we get closer to 1.0 because there’s a lot of things that could be improved there 👍
