### ISSUE TITLE
Type error returning `IGNORE` object when using a generic `TypedDocumentNode` mutation

### ISSUE THREAD

**Issue by sneyderdev** [apollographql/apollo-client#11945]
### Issue Description

There's a type error when returning the `IGNORE` sentinel object from `optimisticResponse` that is inferring from a `TypedDocumentNode<>`.

Given the following document:
![image](https://github.com/apollographql/apollo-client/assets/48073625/a74f9993-a2a8-4356-bfcc-e48fafe3f259)

We get the following type error:
![image](https://github.com/apollographql/apollo-client/assets/48073625/04ab406e-5c01-4dce-86bc-5bbf026a0845)

I've checked the type definitions and it's fixed if we explicitly return an union type instead of only returning the inferred type. I created a PR #11944 changing this.

### Link to Reproduction

https://codesandbox.io/p/sandbox/optimisticresponse-apollo-ts-error-mv34ws

### `@apollo/client` version

3.10.8

**Comment by phryneas** [comment]
Good catch - answering in the PR :)
