### ISSUE TITLE
@apollo/client reactive var state changes are not reflecting across libraries

### ISSUE THREAD

**Issue by gayathrirajendran** [apollographql/apollo-client#11953]
### Issue Description

Changes that happen to the state of a reactive var does not reflect in a library where the var is used, but reflects in the place where the trigger exists to update the state.

I have a library **lib-a** which creates a reactive var using @apollo/client makeVar. Also it has a component which can update the state of the reactive var. Both the reactive var and the component to update it are exported from lib-a. Another library "lib-b", has lib-a in its dependencies and imports the exported reactive var from lib-a. It exports a component which displays the state of the reactive var imported from lib-a. In another react application, both lib-a and lib-b are dependencies. It imports  the component to update the state of reactive var from lib-a and imports the component which shows it from lib-b. Now when the update on state is triggered from component from lib-a, the component from lib-b is not able to show the updates on the reactive state.

### Link to Reproduction

https://stackblitz.com/~/github.com/gayathrirajendran/sample-spa

### Reproduction Steps

1. Click button "Update access token"
2. See change only in spa and notice that the same reactive var used in lib-b is not showing updates
3. lib-b reactive var is not showing any updates.

Is there a way for even lib-b to show the updated state by listening to all updates that happen to a reactive var created with makeVar?

Link for lib-a: https://github.com/gayathrirajendran/lib-a
for lib-b: https://github.com/gayathrirajendran/lib-b
Link for sample-spa:
https://stackblitz.com/~/github.com/gayathrirajendran/sample-spa
https://github.com/gayathrirajendran/sample-spa

### `@apollo/client` version

3.8.10

**Comment by gayathrirajendran** [comment]
@phryneas its packaged as peerDependencies / devDependencies only, can you suggest how else to package it as external deps ?

**Comment by gayathrirajendran** [comment]
@phryneas @apollo/client is already a peer dependency / dev dependency only. Also in vite config build options, they are externalized. Is there any other way to externalize it ?

**Comment by gayathrirajendran** [comment]
yes @phryneas, even after externalizing it still appears, I had externalized in my work app, just forgot to do that in this minimal repro. You can see the issue happening after externalizing too. Please suggest if there is a better way to externalize

**Comment by phryneas** [comment]
In the repro, it seems to update the lib b token, or am I missing something here?

![image](https://github.com/user-attachments/assets/daf7f1ec-41b5-49d3-ad5e-b75310da2bc5)

**Comment by gayathrirajendran** [comment]
cool, had been checking in a heavily cached place, works now, thanks a lot @phryneas !
