### ISSUE TITLE
Documentataion: mutaitonHookOptions.ignoreResults requires additional clarification

### ISSUE THREAD

**Issue by ksdc-grantw** [apollographql/apollo-client#11950]
The documentation for the UseMutation Option `ignoreResults` ([see here](https://www.apollographql.com/docs/react/data/mutations/#mutationhookoptions-interface-ignoreresults)) only states that the "_data property is not updated with the mutation's result_".

It does not indicate that the `loading` state of the requests is also not updated. Please can you update the docs to include this clarification.

Thanks,
Grant

**Comment by phryneas** [comment]
That's a good callout - in fact, `ignoreResults` will cause the hook to ignore all information about the running mutation. Do you want to open a PR against our documentation? It would be greatly appreciated.
