### ISSUE TITLE
3.11.8版本依然存在 Cannot read properties of undefined (reading 'data')问题

### ISSUE THREAD

**Issue by ztwang-sequoiacap** [apollographql/apollo-client#12065]
### Issue Description

![QQ_1726190311182](https://github.com/user-attachments/assets/4d1c75fd-9709-46e8-b657-a7d4b6a57f9a)

### Link to Reproduction

![QQ_1726190311182](https://github.com/user-attachments/assets/4d1c75fd-9709-46e8-b657-a7d4b6a57f9a)

### Reproduction Steps

Sentry 报出的，暂无法重现，result 为 undefined 了

### `@apollo/client` version

3.11.8

**Comment by phryneas** [comment]
Hi, thank you for the report.

From what I can see, this should only happen if you have a `Link` that calls `completed` without ever calling `next` with a result - and even then, only in combination with `useLazyQuery`.

Could you take a look at your custom link implementations please?
