### ISSUE TITLE
`fetchMore` overrides the variables without respecting nested items

### ISSUE THREAD

**Issue by ps173** [apollographql/apollo-client#12079]
### Issue Description

variables with nested items are overriden when `fetchMore` is performed. I am not sure whether this issue has already been reported or not but I couldn't find it anywhere in repo so far.  

for example
```js
  const { data, fetchMore } = useQuery(MY_QUERY, {
    variables: {
      parentVariable: {
        a: "some_value",
      },
    },
  });

  // in fetch more
  async function fetchMoreItems() {
    await fetchMore({
      variables: {
        parentVariable: {
          // here instead of `a` some other value is passed. 
          // so new value of parentVariable will be 
          // { b : "some_value" } rather than { a: "some_value", b: "some_value" }
          b: "some_value"
        }
      },

      // concat items, can be ignored
      updateQuery: (previousResult, { fetchMoreResult }) => {
        const newEdges = fetchMoreResult?.people ?? [];
        const oldEdges = previousResult?.people ?? [];

        return {
          people: [...oldEdges, ...newEdges],
        };
      },
    });
  }
}
```

Although the doc says merged but docs don't really say that nested objects will be overriden with new value. 
This might be intended and does make sense but should be documented

### Link to Reproduction

https://codesandbox.io/p/devbox/practical-wozniak-d6mxd4?workspaceId=b0cc520f-8431-4414-9657-24f9bb60a21b

### `@apollo/client` version

3.5.6

**Comment by jerelmiller** [comment]
Hey @ps173 👋 

Thats a good callout about the docs. The merge that happens is a [shallow merge](https://github.com/apollographql/apollo-client/blob/aba626e28563498d1c4e69b9629f18193d74c145/src/core/ObservableQuery.ts#L448-L451) so what you're seeing is expected. I've opened https://github.com/apollographql/apollo-client/pull/12080 to make it a bit clearer in the docs that variable merging is a shallow merge.
