### ISSUE TITLE
ChatGPT can't help me, need a human! TypePolicy being ignored... why?

### ISSUE THREAD

**Issue by bandinopla** [apollographql/apollo-client#12094]
### Issue Description

Why the type policy in this example is being ignored? the Person.name is not shown in uppercase...
See link...

### Link to Reproduction

https://codesandbox.io/p/sandbox/priceless-rgb-w9g2ny

### `@apollo/client` version

3.11.4

**Comment by dylanwulf** [comment]
type policies are a configuration option for `InMemoryCache`, not `ApolloClient`

**Comment by jerelmiller** [comment]
Hey @bandinopla 👋 

@dylanwulf is correct, you need to pass `typePolicies` to `InMemoryCache` and that should fix your issue. Hope this helps!

**Comment by bandinopla** [comment]
thanks, guys!
