### ISSUE TITLE
Am not seeing optimisticResponse happen

### ISSUE THREAD

**Issue by booboothefool** [apollographql/apollo-client#1209]
```
const SET_MY_PHOTOS_MUTATION = gql`
mutation SetMyPhotos($itemOrder: [InputItemOrderPhotos]) {
  setMyPhotos(itemOrder: $itemOrder) {
    public_id
    secure_url
    order
  }
}
`;

const EditPhotosWithMutate = compose(
  graphql(SET_MY_PHOTOS_MUTATION, {
    props: ({ ownProps, mutate }) => ({
      set: itemOrder => mutate({
        variables: { itemOrder },
        optimisticResponse: {
          __typename: 'Mutation',
          SetMyPhotos: _.sortBy(itemOrder.filter(item => _.isNumber(item.order)).map(item => ({
            __typename: 'Photo',
            public_id: item.key,
            secure_url: item.ref.secure_url,
            order: item.order,
          })), 'order'),
        },
        updateQueries: {
          MyPhotos: (prev, { mutationResult }) => {
            return update(prev, {
              userPhotos: {
                $set: mutationResult.data.setMyPhotos,
              },
            });
          },
        },
      }),
    }),
  }),
)(EditPhotos);
```

I also tried:
```
          SetMyPhotos: [],
```
expecting to see a blank array for a sec, but it's not doing anything. 

Am I doing something wrong?

**Comment by helfer** [comment]
@booboothefool it looks fine to me. OptimisticResponse can be a bit finicky though. A frequent problem is that the shape of the optimistic response doesn't match what the query expect.

We should definitely make this easier to debug (along with updateQueries). In the meantime it might help if you use the [Apollo Client Developer Tools](https://chrome.google.com/webstore/detail/apollo-client-developer-t/jdkknkkbebbapilgoeccciglkfbmbnfm) to look at it?

**Comment by booboothefool** [comment]
@helfer Yeah there are a few throughout my app and those seem to work, however I've never done it with an array like the one I'm trying to do now (basically rearranging/adding/delete a bunch of photos).

Woah since when did we have Apollo Client Developer Tools!!!?? 🎉  I've been under a rock for a while. This is gonna be life changing! I'll check it out, thanks!

**Comment by calebmer** [comment]
@booboothefool let us know if you fix this or if it still doesn’t work. If there’s a bug then we definitely want to know about it 😊

**Comment by calebmer** [comment]
Please let us know if you have any more issues 👍
