### ISSUE TITLE
Polling when server is down clears out results

### ISSUE THREAD

**Issue by SachaG** [apollographql/apollo-client#1210]
With polling enabled, I've noticed that if I shut down my dev server the next time polling triggers (and errors out), my query container doesn't return any results and all my data disappears. Is this the intended behavior? I'd have thought the old data would remain there?

**Comment by helfer** [comment]
@SachaG Thanks for pointing it out! That's probably never what the user wants, so we should change it. Luckily this shouldn't be hard to fix, all we need to do is ignore the result of a polling query if there is an error.

**Comment by nandito** [comment]
@SachaG could you be a bit more specific? I tried to reproduce the issue but it works for me. When I stopped the GraphQL server, I got the `OPTIONS http://example.com/graphql net::ERR_CONNECTION_REFUSED` console error but my sample app kept the previously fetched data in the store.

**Comment by SachaG** [comment]
It might be an issue with my app then… I'll close this until I can confirm this or give you more information.

**Comment by SachaG** [comment]
I had more time to look into this. I tried triggering an error on the server, and got this response:

![https://d3vv6lp55qjaqc.cloudfront.net/items/3r2a3a3d1Q0N0F3j220l/Screen%20Shot%202017-02-23%20at%2012.09.55.png?X-CloudApp-Visitor-Id=cebf9777be46527f7e0ca9fdd95dd995&v=3ff704aa](https://d3vv6lp55qjaqc.cloudfront.net/items/3r2a3a3d1Q0N0F3j220l/Screen%20Shot%202017-02-23%20at%2012.09.55.png?X-CloudApp-Visitor-Id=cebf9777be46527f7e0ca9fdd95dd995&v=3ff704aa)

But weirdly enough, the status code still shows 200:

![https://d3vv6lp55qjaqc.cloudfront.net/items/2o2k2E1i121h1V1C1E3m/Screen%20Shot%202017-02-23%20at%2012.09.30.png?X-CloudApp-Visitor-Id=d40749865873d7b5ab32c80852150f74&v=3bf1797c](https://d3vv6lp55qjaqc.cloudfront.net/items/2o2k2E1i121h1V1C1E3m/Screen%20Shot%202017-02-23%20at%2012.09.30.png?X-CloudApp-Visitor-Id=d40749865873d7b5ab32c80852150f74&v=3bf1797c)

Could that be why the container stops returning data?

**Comment by calebmer** [comment]
Would it be possible for you to reproduce this error with [`react-apollo-error-template`](https://github.com/apollographql/react-apollo-error-template)? It would go a long way in helping us solve this issue because we could see exactly what’s happening 😊

**Comment by SachaG** [comment]
Sure, I'll see what I can do.

**Comment by helfer** [comment]
It should no longer clear out results in react-apollo with https://github.com/apollographql/react-apollo/pull/548. For other integrations I think they should do a similar thing.
