### ISSUE TITLE
Invariant violation upgrading from 3.11.0 to 3.11.8

### ISSUE THREAD

**Issue by tomymehdi** [apollographql/apollo-client#12108]
### Issue Description

Invariant violation upgrading from 3.11.0 to 3.11.8

### Link to Reproduction

emporix.com

### Reproduction Steps

Minor version impacting on normal functioning

### `@apollo/client` version

3.11.8

**Comment by phryneas** [comment]
I'm sure, but without additional information we won't be able to help you.

Neither do you specify any information which invariant violation (there are dozens) nor can I observe that behaviour on the page that you linked as reproduction.
