### ISSUE TITLE
Apollo Client 3.11.8: Performance Degradation with Array-Returning Queries and Cache Updates

### ISSUE THREAD

**Issue by ariel-upstream** [apollographql/apollo-client#12118]
### Issue Description

I'm experiencing a significant performance regression with Apollo Client 3.11.8. When fetching an array of objects, the initial page load is delayed by 10-20 seconds. Setting the fetchPolicy to 'no-cache' resolves the issue, but disables caching

### Reproduction Steps

The data object type:
```ts
export type NamesItemQuery = {
  __typename?: "Query"
  namesItem: Array<{
    __typename?: "NamesItem"
    name: boolean
    description: string
    displayName: string
    name: { __typename?: "InnerName"; name: string }
  }>
}
```

call the data with the default fetchPolicy - the UI freeze 
call the data with the default fetchPolicy: no-cache - the UI renders fast 

### `@apollo/client` version

3.8.11

**Comment by jerelmiller** [comment]
@ariel-upstream can I also ask, what version are you upgrading from?

If its anything before 3.9, its very possible you're hitting a limit on one of our internal caches which you can adjust to fit the needs of your app. See https://www.apollographql.com/docs/react/caching/memory-management for more information on how to check if you're running into those limits and how to adjust them. 

Many times its a matter of increasing the cache size to adjust for your app. `inMemoryCache.executeSelectionSet` and `inMemoryCache.executeSubSelectedArray` are typically what we see maxed out first and these have a tendency to show some performance regressions once they hit their limits.
