### ISSUE TITLE
Duplicate @wry/trie in dependency tree

### ISSUE THREAD

**Issue by KuSh** [apollographql/apollo-client#12144]
### Issue Description

Since commit 9ee6f957a3f2471594e9662663185fc41efa410a the @wry/trie dependency is duplicated in Apollo's dependency tree.
Unfortunately there's currently no update to optimism to get rid of this duplication.
A downgrade of Apollo Client dependency to @wry/trie@^0.4.3 would fix the duplication.

### Link to Reproduction

https://github.com/apollographql/apollo-client/blob/main/package-lock.json

### Reproduction Steps

Check package-lock.json

### `@apollo/client` version

3.11.10

**Comment by phryneas** [comment]
I would want to avoid a downgrade here - I'll ping @benjamn if he can release a new version of `optimism`.

**Comment by phryneas** [comment]
Ben has released a new version of `optimism`, so if you update your `optimism` to `0.18.1`, you should end up with a single copy of `@wry/trie` in your dependency tree.

**Comment by phryneas** [comment]
I'm going to close this as it seems resolved
