### ISSUE TITLE
Dependency `@wry/caches`  / other `@wry` packages 404 now on NPM

### ISSUE THREAD

**Issue by camsjams** [apollographql/apollo-client#12197]
### Issue Description

It looks like the [package @wry/caches](https://www.npmjs.com/package/@wry/caches) was removed or made private.

Same is true for the other `@wry` packages it seems:
- https://www.npmjs.com/package/@wry/trie
- https://www.npmjs.com/package/@wry/caches
- https://www.npmjs.com/package/@wry/equality

```
error An unexpected error occurred: "https://registry.npmjs.org/@wry/caches/-/caches-1.0.1.tgz: 
Request failed \"404 Not Found\"".
```

I'm not familiar with the [owners of this package](https://github.com/benjamn/wryware), but it is currently breaking builds:
![image](https://github.com/user-attachments/assets/7d022963-510a-4dda-ad8c-1882938a6b34)

### Link to Reproduction

npm install apollo client

### Reproduction Steps

1. Install apollo client
2. `npm install @apollo/client`
3. `yard add @apollo/client`

### `@apollo/client` version

3.9.7+, really all versions with `@wry/caches` as a dependency

**Comment by phryneas** [comment]
Npm had a planned outage yesterday: https://status.npmjs.org/incidents/px35z3dmcjgm, that probably explains it.

Please always check the [npm status page](https://status.npmjs.org)
