### ISSUE TITLE
Devtools is always enabled regardless if devtools.enabled is false

### ISSUE THREAD

**Issue by codedepot-jhoncel** [apollographql/apollo-client#12198]
### Issue Description

The new config `devtools.enabled` from `ApolloClient` doesn't seem to work. Devtools is always enabled even when you set the value to false or when running in production environments. On the contrary, using the now deprecated `connectToDevTools` works just fine.

### Link to Reproduction

https://codesandbox.io/p/sandbox/cool-firefly-5lcwkm

### Reproduction Steps

1. Visit the codesandbox preview URL in a separate tab.
2. Open the Apollo devtools extension (I use Chrome).
3. Notice that the extension is still enabled even when configured to be disabled.

**Expected result:**
Disabling the devtools should show the following prompt.
![image](https://github.com/user-attachments/assets/4e0aedf3-7ef2-4c9c-a5cc-847e086dc8a7)

**Actual result:**
The extension was able to log the queries and display the cached contents.
![image](https://github.com/user-attachments/assets/c2c062ea-1b41-492a-82d9-560ea4c241a3)
![image](https://github.com/user-attachments/assets/55f145d9-4fdb-43c4-b6d3-c36d6ee4a5af)

### `@apollo/client` version

3.11.4

**Comment by jerelmiller** [comment]
Hey @codedepot-jhoncel 👋 

This should have been fixed with version [3.11.10](https://github.com/apollographql/apollo-client/releases/tag/v3.11.10) via #12093. Can you upgrade to at least that version and see if it helps?

**Comment by codedepot-jhoncel** [comment]
Hey @jerelmiller, thanks for the quick reply. I confirm updating to the latest version (`v3.12.2`) fixed the issue. Thanks again.
