### ISSUE TITLE
Deepfreeze not used on watchQuery result in development

### ISSUE THREAD

**Issue by daniel-nagy** [apollographql/apollo-client#1219]
Adding `deepFreeze` in development is a breaking change and should be labeled as such in the change log.

In development the results from `watchQuery`, at least the results from `observable.refetch`, are not frozen but the results from `query` are frozen.

version: `>= 0.7.x`
framework: React Native

#### Expected outcome
All results should be either frozen or not frozen.

#### Actual outcome
Results from `observable.refetch` are not frozen.

**Comment by helfer** [comment]
@daniel-nagy Thanks for reporting the issue. Would you like to make a PR to fix it? It should be relatively easy.

**Comment by alejandronanez** [comment]
I'll go and take this one!

**Comment by helfer** [comment]
@alejandronanez sorry, I actually just fixed that a few days ago! I just didn't remember to close this issue. Thanks for the interest though! Would you be interested in working on some other small bug/ feature? 🙂
