### ISSUE TITLE
Wrong fields returned for arrays within fragments

### ISSUE THREAD

**Issue by jesenko** [apollographql/apollo-client#1231]
Query with fragments on different types returns wrong fields for arrays in fragment.

E.g. running
```
{
  ... on Object1 {
    nestedObj {
      innerArray { id otherField }
    }
  }
  ... on Object2 {
    nestedObj {
      innerArray { id someField }
    }
  }
}
```
on object of type `Object2` will return only `{ nestedObj { innerArray{ id } } }`.
It should return `{ nestedObj { innerArray { id someField } } }`.

Selection set for first fragment specified in query is used to determine returned fields, ignoring actual `__typename` of resulting object.

Corresponding PR with failing test: #1230

**Comment by jesenko** [comment]
I traced this issue back to behaviour of merge function in graphql-anywhere, where arrays are not deep-merged. PR for graphql-anywhere referenced above fixes failing test in this PR.

**Comment by helfer** [comment]
@jesenko Thanks, I've commented on the PR 🙂

**Comment by helfer** [comment]
Apparently fixed now, thanks @jesenko !
