### ISSUE TITLE
Regression(?); client raises network error on duplicate fragment

### ISSUE THREAD

**Issue by koenpunt** [apollographql/apollo-client#1238]
**With `apollo-client` 0.8.0 I got the following error:**

<img src="https://cloud.githubusercontent.com/assets/351038/22396264/dac07482-e554-11e6-99a6-cb66166e4fae.png" width="300"/>

**With 0.8.1 I get:**

<img src="https://cloud.githubusercontent.com/assets/351038/22396265/dce82606-e554-11e6-967a-75ea3ed4f4fe.png" width="300"/>

**Comment by calebmer** [comment]
Interesting. So this is the same error except in `0.8.0` we throw an error that is easier to understand.

**Comment by helfer** [comment]
Yeah, this is definitely a regression that we should fix!

**Comment by calebmer** [comment]
Related: https://github.com/apollographql/react-apollo/issues/433#issuecomment-277176460
Explanation: https://github.com/apollographql/react-apollo/issues/433#issuecomment-277302892
