### ISSUE TITLE
Dealing with Large Amounts of Data

### ISSUE THREAD

**Issue by bradabelgit** [apollographql/apollo-client#1240]
I have noticed a significant slowdown in page load times when there is a larger amount of data in the cache. In this case there are 5000 data points being loaded from a single query from the cache. I'll post some code, but before I do i'd just like to ask a general question. Should I be trying to load this much data at once? Basically I am trying to get something up and running as quickly as possible and the simplest way seems to be to load all the data at once, cache it, and manipulate it from there.

To give a little more perspective, this is for a table that lists all the data and allows to filter through it, sort it, etc. Once loaded everything loads nicely, but it takes about 2-3 seconds to do so.

**Comment by calebmer** [comment]
Is this with one query or with many queries? Also, do you have any `updateQueries`? It is a known issue that writes to the store are generally slow and that reads could be faster. We are currently working on a faster store implementation, so stay tuned for that.

Could you provide a simple app which loads a lot of data? It would be great to see the actual use case where the slow down occurs for you.

**Comment by bradabelgit** [comment]
In this case it is just a single, simple query to get data, no updateQueries involved.

'''
const gql = require("graphql-tag");
const { graphql } = require("react-apollo");

const { contactInfo } = require("../fragments");

const query = gql`
  query contacts {
    contacts {
      ...contactInfo
    }
  }
  ${ contactInfo }
`;

const apolloQuery = graphql(query, { name: "contacts" })

module.exports = {
  query,
  apolloQuery,
  apolloQueryWithOptions(options = {}) {
    return graphql(query, {
      name: "contacts",
      options
    });
  }
};
'''

In this case I am calling the apolloQueryWithOptions sending the noFetch option because I know that the data is already pre-loaded in the cache.

'''
const { compose } = require("react-apollo");

const Component = require("./component.jsx");
const { account, contact } = require("app/graphql/types");

module.exports = compose(
  contact.queries.contacts.apolloQueryWithOptions({ noFetch: true }),
  account.queries.accounts.apolloQuery
)(Component);
'''

In this case the accounts query is returning just a few records so it is negligible. I will test things with just the contacts query to make sure and let you know if it is the use of multiple query's that makes the difference.

In the meantime it isn't foreseeable that our users will have insane amounts of data in the immediate future, however, we would like to prepare for the future.

I'll see if I can find some time to mock something up over the next week or so!

**Comment by Poincare** [comment]
This should not be the case. The benchmarks show that the read time for a single item out of the cache is constant with respect to the number of items in the cache so the number of items in the cache is unlikely to be the culprit.

The issue is likely the number of items being read from the cache. Some other users have run into this issue and it seems that its impact can be lessened by turning off referential equality checking (which is currently not exposed). Could you post a Chrome CPU trace of the page running your code? That would help us figure out if there's some other kind of issue.

**Comment by mdebbar** [comment]
> We are currently working on a faster store implementation, so stay tuned for that.

@calebmer that's awesome! Do you have any details about this? Or maybe an issue/PR that I can follow?

**Comment by calebmer** [comment]
@mdebbar There is some preview of what we are working on in https://github.com/apollographql/apollo-client/pull/1258, but that specific PR is currently paused as we evaluate ways to tackle the issue.

**Comment by helfer** [comment]
Let's track this under #1409
