### ISSUE TITLE
Add support for observables in NetworkInterface::query

### ISSUE THREAD

**Issue by mpowaga** [apollographql/apollo-client#1241]
At the moment NetworkInterface::query must return a promise. That means that query result can't change in time. [GraphiQL](https://github.com/graphql/graphiql) has `fetcher` prop which is a function that can return either a promise or observable. If latter is returned then query result can change in time thus it's possible to implement "live queries" like Meteor does with it's pub-sub system.

I think this could be a great addition to apollo-client. I already started working on Meteor package that utilises [cursor::observeChanges](http://docs.meteor.com/api/collections.html#Mongo-Cursor-observeChanges) to transmit GraphQL query changes to the client through websocket protocol. It works similarly to [https://github.com/englue/meteor-publish-composite](https://github.com/englue/meteor-publish-composite) but in my opinion it's more powerful and simpler to use.

Recently I heard about [Apollo Contributor Week](https://dev-blog.apollodata.com/save-the-date-apollo-contributor-week-eef66d09f0e6#.dhdqzegvm) and I'm willing to work on this feature if it's seen as valuable by other contributors.

**Comment by calebmer** [comment]
This is a good idea that the core team has talked about before. We would happily merge a PR implementing this feature 😊

**Comment by helfer** [comment]
cc @DxCx who might also be interested in this.

**Comment by helfer** [comment]
Closing up old issues. This is still on our radar and we're planning to implement it shortly. 🚪
