### ISSUE TITLE
Cannot find name 'IResponse'.

### ISSUE THREAD

**Issue by drejohnson** [apollographql/apollo-client#1243]
When using `"@types/isomorphic-fetch": "^0.0.32",` I get error. Version `^0.0.31` works fine.
```
ERROR in [at-loader] node_modules/apollo-client/transport/afterware.d.ts:3:15
    Cannot find name 'IResponse'.

ERROR in [at-loader] node_modules/apollo-client/transport/networkInterface.d.ts:44:15
    Cannot find name 'IResponse'.

ERROR in [at-loader] node_modules/apollo-client/transport/networkInterface.d.ts:56:77
    Cannot find name 'IResponse'.
```

**Comment by calebmer** [comment]
Thanks for the report. It looks like we are currently pinned to version `0.0.30`. So if anyone wants to upgrade our types to support the latest version that would be appreciated 👍

**Comment by helfer** [comment]
@drejohnson would be great if you could try making a PR 🙂
