### ISSUE TITLE
Tactic for filtering '__typename' when sending back data

### ISSUE THREAD

**Issue by rovansteen** [apollographql/apollo-client#1246]
Hey all, do you have any ideas or tactics about how to filter `__typename` from the results when using in your application and sending the data back to the user? I used to recursive iterate through the result & remove them but after upgrading this no longer works, I'm guessing you started using some kind of immutability. It didn't felt like a good way to handle this so I've no problem implementing a different solution but so far unable to find any.

This is mostly an issue on 'edit' pages where I pass the results from GraphQL to my form (with redux-form) and use that data to update again. Then my server complains about `__typename` being included in the query. I can of course accept the `__typename` on the server, but that doesn't make much sense to me. I'm hoping there's a better solution for this.

**Comment by calebmer** [comment]
The best case here is probably to clone the object you want to send to your server but omit `__typename`. A helper like [Lodash’s `omit`](https://lodash.com/docs#omit) could help with this.

I’m going to close. If this doesn’t help let me know and we can try to find a better solution 👍

**Comment by doomsower** [comment]
I faced similar issue as @rovansteen yesterday - forms with some deep non-scalar fields.
At first, a was looking for recursive omit solution, but all npm solutions I found had some drawbacks.
So now I'm using `filter` from `graphql-anywhere` - it takes care of __typename deeply. Here is how I pass props to my react view:

```js
props: ({data: {region, loading}}) => {
 if (region) {
    console.log('Original', JSON.stringify(region, null, 2));
    console.log('Filtered', JSON.stringify(filter(regionDetailsFragment, region), null, 2));
  }
  return {initialData: region && filter(regionDetailsFragment, region), ready: !loading}
},
```
As you can see from the output, all `__typename`s are gone:

```json
Original {
  "_id": "vnDyacC42f4uMs78r",
  "name": "Brazil",
  "description": null,
  "season": "spring",
  "pois": [
    {
      "_id": "zvjXKJFyhecDtEMSL",
      "name": "Some point",
      "description": null,
      "coordinates": [33, 22],
      "altitude": 3,
      "kind": "bridge",
      "__typename": "Point"
    }
  ],
  "__typename": "Region"
}
Filtered {
  "_id": "vnDyacC42f4uMs78r",
  "name": "Brazil",
  "description": null,
  "season": "spring",
  "pois": [
    {
      "_id": "zvjXKJFyhecDtEMSL",
      "name": "Some point",
      "description": null,
      "coordinates": [33, 22],
      "altitude": 3,
      "kind": "bridge"
    }
  ]
}
```

**Comment by superandrew213** [comment]
@calebmer can't we just omit `__typename` from the results? I understand that it's need for fragment matching but it doesn't have to be included in the results.

**Comment by helfer** [comment]
@superandrew213 you are definitely right about that, but we haven't had time to implement it and try it out. Depending on how it's implemented it might adversely affect performance.

If you have time and are willing to make a PR, we'd do our best to get it merged!

**Comment by superandrew213** [comment]
@helfer I will take a look at it. What ways did you have in mind?
