### ISSUE TITLE
Add user comments to docs

### ISSUE THREAD

**Issue by brunoreis** [apollographql/apollo-client#1251]
I've being following some open source projects for some years and I have noticed how useful are user comments on the documentation projects. They give a broader understanding of the documented topic and also give very good real world and usage examples. 

I would guess they are the real strength behind some fast growing and large adoption technologies. 

So, I have this suggestion to this excellent project: please add user comments to docs.

**Comment by calebmer** [comment]
Thanks for the suggestion! Could you give an example of a project that you admire which has user comments in the docs 😊

**Comment by brunoreis** [comment]
PHP is good one. Take a look at this (randomly chosen) page: 
http://php.net/manual/pt_BR/function.strval.php

and this one:
http://php.net/manual/pt_BR/function.file-get-contents.php 

How much do you get from the oficial docs? And how much from users? 

* If I was an academic, I would make a thesis stating that one of the big reasons php grew so much is because of user comments. Since I'm not. I'm making only this suggestion. ;-)

* My suggestion is because I was looking for the .catch(error) on mutations and thinking that the discussion I'd like to see would be on user comments. In case they were there, of course.

**Comment by brunoreis** [comment]
Another one grabbed my attention years ago. I thought it was rails, but is not. If I remember, I'll put it here.

**Comment by stubailo** [comment]
The only issue with comments is the need for moderation etc. maybe we can use some off the shelf platform like disqus?

**Comment by helfer** [comment]
@brunoreis that's an interesting suggestion, thanks! Since anyone can make a PR to our docs I feel the need is less strong than it was for PHP, but I can definitely see the usefulness. The main problem as @stubailo pointed out is moderation, so we would have to figure out what to do about that before we try it out.

**Comment by brunoreis** [comment]
@helfer, I feel that user comments are not the same thing as the "official documentation". I would gladly use a user comment to paste a way I was able to accomplish a task related to that topic, or even to paste a doubt I have. But, I would probably fear adding the same thing to docs, since I'm still learning and could say something wrong.

Besides, usability adds a lot to conversion. Editing a page is not as easy as clicking on a big CTA. :-)

I also feel that docs should not elaborate so much. They need to say the essentials. While comments can accommodate a lot of other related subjects and helpful hints.  

I definitely agree about moderation. Of course you can use user input to help with votes, thumbs up, down, abuse reporting and things like that. 

I'm glad you liked the suggestion. Of course this suggestion is not only to the "Vanilla" docs/repo, but extensible to all apollo stack. I'm really interested in using it and seeing the results of the community interaction. I feel like a lot of value will be added to docs.  I hope you are able to figure out good moderation rules.

**Comment by helfer** [comment]
@brunoreis I agree, so I think we should definitely try it.

**Comment by helfer** [comment]
Closing old issues 🏁
