### ISSUE TITLE
Tests in test/client.ts are silently failing

### ISSUE THREAD

**Issue by benbeadle** [apollographql/apollo-client#1252]
**Intended Outcome**

Tests that call a promise should return the promise so Mocha knows to fail the test if the Promise is rejected.

**Actual Outcome**

Tests are failing silently.

**How to Reproduce the Issue**

Run `npm test`

**Comment by helfer** [comment]
@benbeadle Thanks for filing the issue! Can you refer to the specific tests where you found this to be the case?

**Comment by benbeadle** [comment]
@helfer The specific tests I'm talking about are the ones that call `clientRoundrip`. The tests should be returning the promise returned from that function call.

These call a Promise without wrapping it:
[L201](https://github.com/apollographql/apollo-client/blob/63ede5a377350460691e4ebb7ff377ae242da8e8/test/client.ts#L201)
[L281](https://github.com/apollographql/apollo-client/blob/63ede5a377350460691e4ebb7ff377ae242da8e8/test/client.ts#L281)

This one doesn't return the promise and if the Promise is rejected won't be caught:
[L996](https://github.com/apollographql/apollo-client/blob/63ede5a377350460691e4ebb7ff377ae242da8e8/test/client.ts#L996)

Also, using arrow functions in mocha tests is [discouraged](https://mochajs.org/#arrow-functions). Doesn't look like you're using `this` in any of the tests so you should be okay, but I like make a habit of just always using `function(){}`.

**Comment by helfer** [comment]
@benbeadle I think you're right about the first two, but that last one uses `done()`, so it should time out rather than fail silently. 

Who wants to make a PR to fix the tests? For the first two, just return the promise, for the last one actually call done with a failure, or remove `done` and return the promise.

**Comment by HMAN1911** [comment]
@helfer working on a PR now.

**Comment by alejandronanez** [comment]
Hey @helfer. I want to start contributing back to OSS and this seems like a good start for me.

**Comment by calebmer** [comment]
Hey @alejandronanez! I’m excited to here you want to contribute 😊

This issue may be a little difficult to fix without understanding the test suite, how about looking at some of the other issues labeled [easy](https://github.com/apollographql/apollo-client/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy)? (easy implies help wanted 😉) https://github.com/apollographql/apollo-client/issues/1219 and https://github.com/apollographql/apollo-client/issues/1195 should be two issues that are good to get started with. Please feel free to ping me on the Apollo [Slack](http://www.apollodata.com/#slack) if you need any help 👍
