### ISSUE TITLE
how to override the uri of the apollo client's network interface?

### ISSUE THREAD

**Issue by gex** [apollographql/apollo-client#1267]
long story short: i'd like to override the uri of the apollo client's network interface without creating a new one.
i share the initial client with the combined redux reducer so it's mandatory to use the same instance. i tried to override the networkInterface property of the client but it doesn't work and maybe it should not and i tried to override the uri with a middleware but it's not clear what property of the request object should i set in there.

0. is it possbile to create a network interface without setting the uri? i couldn't do that so i use a dummy uri at the moment
1. is it possible to override the uri of the apollo client at all?
2. what is the preferred way to do that?

**Comment by stevewillard** [comment]
I'm also interested in this. I tried a few methods of trying to set the client's uri in context for the rest of the tree, but ultimately I had to create new clients.

**Comment by calebmer** [comment]
If you want to do this, you should write your own network interface! 😊

It’s not that bad, you can even extend `HTTPFetchNetworkInterface` if you would like: https://github.com/apollographql/apollo-client/blob/master/src/transport/networkInterface.ts

**Comment by gex** [comment]
```
import { HTTPFetchNetworkInterface } from 'apollo-client'

class NetworkInterface extends HTTPFetchNetworkInterface {
  setUri(uri) {
    this._uri = uri
  }
}

const networkInterface = new NetworkInterface('/grapqlendpoint1')
networkInterface.setUri('/graphqlendpoint2')
```

thanks @calebmer !

**Comment by stubailo** [comment]
Great! Looks like we can close this, thanks for the tip @calebmer
