### ISSUE TITLE
Network interface for websockets

### ISSUE THREAD

**Issue by mistic** [apollographql/apollo-client#1268]
Hi guys,

Do you have any already implemented network interface to use with web sockets?

Regards

**Comment by calebmer** [comment]
Do you mean for subscriptions or queries/mutations? For subscriptions yes, for queries/mutations you will need to write your own 😣

**Comment by helfer** [comment]
@mistic I think @DxCx was thinking about implementing one.

**Comment by mistic** [comment]
@calebmer and @helfer thank you for your answers. We're designing our api to be a graphql api over websockets, so we need a network interface for query / mutations with support to sending an authoroziation token. We also need websocket subscritions to receive real time updates. @DxCx any news on this?

**Comment by calebmer** [comment]
@mistic it sounds like you’re doing something really awesome! I think you’re probably going to want to implement your own network interface. It really isn’t that hard though as you basically just need to implement a single `query` function.

**Comment by mistic** [comment]
@calebmer thank you for your answer. Yeah we're creating an awesome product!

Do you know if there are any kind of examples of already implemented custom network interfaces to look for? 

Isn't already implemented by someone?

**Comment by smolinari** [comment]
Is this what you are looking for? https://github.com/apollographql/graphql-server/pull/308#issuecomment-281758673

Scott

**Comment by calebmer** [comment]
@mistic yep. You can check out our default `HTTPFetchNetworkInterface`. There’s a lot of code in there concerning middleware that really isn’t necessary. The most important method is simply `query`: https://github.com/apollographql/apollo-client/blob/6274c98bb0925f0936d19fb9227bc58b1a558db9/src/transport/networkInterface.ts#L174-L206

We also have a mock network interface in tests you could look at for another example: https://github.com/apollographql/apollo-client/blob/6274c98bb0925f0936d19fb9227bc58b1a558db9/test/mocks/mockNetworkInterface.ts#L62-L110

**Comment by mistic** [comment]
@smolinari No :( This is an implementation for the graphql-server. What I need is an implementation for the Apollo-client be able to connect to a graphql-server over websockets instead of http and make the requests to for example ws://localhost:8080/graphql. So I'll be able to send graphql queries to this ws address and also send subscriptions to the same websocket address.

**Comment by smolinari** [comment]
@mistic - ah yes. Sorry. Not sure what I was thinking. 

Maybe this might give you some ideas. https://github.com/rgraphql/soyuz

Scott

**Comment by helfer** [comment]
I see you've already been making good progress on subscriptions-transport-ws. Closing this issue here 🙂
