### ISSUE TITLE
Trouble understanding the request being sent to GraphQL server

### ISSUE THREAD

**Issue by bwbarron** [apollographql/apollo-client#1281]
As per [GraphQL documentation](http://graphql.org/learn/serving-over-http/#post-request), the POST request to a GraphQL server should look like
```
{
  "query": "...",
  "operationName": "...",
  "variables": { "myVariable": "someValue", ... }
}
```
if using `application/json` as the content type. Note the query being a string value. But I added some middleware to the networkInterface to inspect the request and it's actually an object (see below). I'm having trouble understanding how I should get the query to be sent as a string.

![screen shot 2017-02-09 at 1 42 58 pm](https://cloud.githubusercontent.com/assets/9869886/22804431/e40d79ea-eecd-11e6-9308-4fb362db462e.png)

**Comment by helfer** [comment]
In the middleware the query is a graphql document so it's easier for you to modify the AST (if you so wished). Before the request gets sent to the server, the query is printed [here](https://github.com/apollographql/apollo-client/blob/f8e4d1e78a5991d83fee723c32a4d9efe869b549/src/transport/networkInterface.ts#L79). I hope that answers your question! 🙂

**Comment by bwbarron** [comment]
That clears that up, thanks! I was getting a HTTP 415 Unsupported Media Type so I thought it might be related to this but I guess not. I'll have to dive into our server code to figure it out.
