### ISSUE TITLE
`whatwg-fetch` causing an error?

### ISSUE THREAD

**Issue by GRardB** [apollographql/apollo-client#1283]
Hey!

I'm running into a problem with a side project of mine. I'm using Apollo Client to built a universal React app. This is the second time I've used it. The first time, I had no issues, but I'm running into an issue this time...

When I used `apollo-client` on the client-side, everything was fine. However, when I started implementing the SSR part, I get this error when running the code on the server:

```
TypeError: Cannot read property 'fetch' of undefined
```

I did some digging, and I figured out that it comes from the `whatwg-fetch` package (imported by `transport/networkInterface.js`):

```
(function(self) {
  'use strict';

  if (self.fetch) { // <-------- right here!
    return
  }
  . . .
})(typeof self !== 'undefined' ? self : this);
```

I went into the bundle and put a `console.log(self)` in both my first project and my second. In the first (working) project, it output `{}`. In the second one, however, it output `undefined`.

There are two main differences between the two projects:

1. The first is written in TypeScript, and the second is in ES6 (babel).
2. The first one uses webpack 1, and the second uses webpack 2.

Other than that, I can't think of anything that would cause this. I originally thought it might be a tree shaking thing since `whatwg-fetch` isn't a module, but it gets bundled just fine, so I don't think that's the issue. I'm still not convinced that webpack 2 isn't what's causing the problem, though.

Has anyone else run into this? If not, is anyone else using babel and webpack 2? I'm wondering if there's a way that we can narrow down the issue.

I understand that this isn't strictly an `apollo-client` issue, but I'm not sure where else to look, given everything I [don't] know.

As a [temporary?] workaround, I'm aliasing the `whatwg-fetch` package to a dummy module in my code where I'm just exporting `true`.

**Comment by calebmer** [comment]
If somewhere in your build chain this:

```js
(function(self) {
  'use strict';

  if (self.fetch) {
    return
  }
  ...
})(typeof self !== 'undefined' ? self : this);
```

Turns into this:

```js
'use strict';

(function(self) {
  'use strict';

  if (self.fetch) {
    return
  }
  ...
})(typeof self !== 'undefined' ? self : this);
```

That’s what is causing the problem (note the `'use strict';` in the global scope). You should either make sure the `whatwg-fetch` module is not running in strict mode, or submit a PR to `whatwg-fetch` to use the `global` or `window` variables if `this` or `self` is not available globally.

Let me know if this works for you, and if you are able to fix it 😊
