### ISSUE TITLE
Refetching an unmounted query results in stale data after remount.

### ISSUE THREAD

**Issue by pleunv** [apollographql/apollo-client#1290]
Hi guys!

I'm running into an issue with a mutation that should cause a refetch of a component that's currently unmounted. Brief scenario:

Lets say I've got 2 components, `ListComponent` and `FormComponent`. `ListComponent` is mapped to a list of items through `MyListQuery`, `FormComponent` has a `createItem` mutation that has `MyListQuery` added to its refetch list. When the form is displayed, the list component is unmounted. When the form is published and the mutation promise has been resolved, we redirect back to `ListComponent`. The code looks something like this:

```javascript
// ListComponent.jsx

export default graphql(MyListQuery)(ListComponent);

// CreateFormComponent.jsx

const mutationOpts = ({ mutate }) => ({
  createItem: (item) => mutate({
    variables: { item },
    refetchQueries: ['MyListQuery']
  })
});

export default graphql(CREATE_MUTATION, mutationOpts)(CreateFormComponent);
```

After the form is submitted, the mutation has been performed and we redirect back to the list, I'm expecting the list to either contain the new item, or to show a loader when the query is still being refetched. However, it looks like `MyListQuery` gets removed from `QueryManager.observableQueries[]` since its component is unmounted. Because of this the QueryManager can't find a match when looking up the queries that need to be refetched. As a result `ListComponent` just fetches its result from cache as it is unaware of the fact that its query result is now stale.

Is there any way to solve this behavior without doing a `forceFetch`? Would it be a possibility to keep tracking queries even when they are unmounted, but flagging them as stale so that their refetch can be delayed until remount?

**Intended outcome:**

When a refetch happens on a unmounted component's query, the component should be aware of the stale query after remounting and refetch accordingly.

**Actual outcome:**

Currently queries stop being observed after being unmounted so this behavior does not work.

**Comment by calebmer** [comment]
This is a known issue that has had much prior discussion (see https://github.com/apollographql/apollo-client/issues/1129 and https://github.com/apollographql/apollo-client/issues/1224). In the meantime, we recommend not unmounting components whose data you want to stay fresh. Let me know if you have any more questions 👍

**Comment by pleunv** [comment]
I just tried out the new version of react-apollo and got rid of the `forceFetch`es, however I'm still not getting the desired result with the aforementioned scenario. Should the recycling be compatible with refetchQueries (query names), or could it be something else I'm missing?

**Comment by calebmer** [comment]
Yeah, it should be compatible with `refetchQueries`…

Could you reproduce this error by forking [`react-apollo-error-template`](https://github.com/apollographql/react-apollo-error-template)? It would go a long way in helping us debug the issue.

**Comment by pleunv** [comment]
My [first attempt](https://github.com/pleunv/react-apollo-error-template/commit/0c4cfab6860ddd98e06c7368be536de804a9e45c) of reproducing it with a fairly similar approach actually works correctly... I must be overlooking something, will try to investigate a bit further.
