### ISSUE TITLE
Browser Freeze - Slow performance on many consecutive mutations 

### ISSUE THREAD

**Issue by manuelfink** [apollographql/apollo-client#1294]
I'm having performance issues with BatchingNetworkInterface with the latest client version. I'm using it to update a category tree structure on moving three elements. this results into 40-250 mutations batched into on request, since also children are updated.

### Timings

preparing changed elements and firing apollo mutations: <10ms
**apollo client** processing mutation till querying graph endpoint: **10-15s**
apollo server processing: 2-6s
**apollo client** processing results from returned response till ng2 rerendering: **30-110s;**

```
const networkInterface = createBatchingNetworkInterface({
  uri: '/graphql',
  batchInterval: 10
});
```

Mutation is s simple category with id, parent, order, label and level fields, so not a lot of payload. Each mutation returns the updated category element.

Has anyone similar issues?

apollo-client 0.8.5

**Comment by helfer** [comment]
@manuelfink It's very hard to diagnose this from afar. The most useful thing for us to have would be some profiling information (traces) from Chrome. First I have one question though: What does it look like when you don't use batching?

**Comment by manuelfink** [comment]
@helfer same problem without batching interface. Cannot tell if it is better or worse though. You can find a heap timeline here: https://drive.google.com/open?id=0BwfEGzY_g_hIZFZsOXlfaktQTGM

Do you think using one mutation instead of many would resolve the issue, eg implementing:

```
categorySort([{id:1, order:1}]) {...FragmentCategory }
```

**Comment by manuelfink** [comment]
What you looking out for in the timeline? I'd love to get an deeper understanding into the insights.

**Comment by manuelfink** [comment]
@helfer: 

Firing mutations increase time till graphql hits networkDid some further analytics.

**Comment by manuelfink** [comment]
Some further tests show the processing of the response takes (almost exponentially) longer for a larger amount of responses. Problematic is that it fully freezes the browser that it can not even be closed or reloaded.

@helfer have you ever considered using service workers?

**Comment by stubailo** [comment]
I don't think service workers would help here, sounds just like something that can be solved. Could you post a screenshot of the CPU flame graph from Chrome?

**Comment by manuelfink** [comment]
@stubailo see CPU Profile and screenshots of it shared in google drive https://drive.google.com/open?id=0BwfEGzY_g_hIaE1vT2MyS255d00

I removed the updateQueries statement for now, since running it pushes the processing of the result over 2 minutes.  Instead I use a refetch as a temporary fix for now. 

Taking a look at the updateQueries statement in the flame chart, the time of getCategoriesOfPublication looks ok. However it seems to me that a lot happens around updateQueries pushing the time into length, if any updateQuerie is present.

```
/*
updateQueries: {
  getCategoriesOfPublication: (prev: any, res: any ) => {
    const item = res.mutationResult.data.categorySave;
    let items = prev..categories;
    let orgItem = _.find(items, {"id":item.id});
    if (orgItem) {
      _.merge(orgItem, item)
    } else {
      items.push(item);
    }
    return prev;
  }
}
*/
/*
updateQueries: {
  getCategoriesOfPublication: (prev: any, res: any ) => {
    return prev;
  }
}
*/
```

While apollo-client is running the whole browser is frozen and not even the waiting spinner is turning any more. I guess this is due to js in browser is executed by only one event loop like node, if I'm not mistaken? 

I guess web/service workers may improve this, since 
 
* services running async independent from the browser js
* services could be "multi" threaded.

**Comment by stubailo** [comment]
Yeah but I think it's a far easier solution for now to simply fix the CPU usage than make the whole architecture go over a bridge to another thread, although that is something we are interested in working on long-term!

**Comment by calebmer** [comment]
I’m really not sure there is much we can do short of re-architecting most of the current codebase to support 40-250 _batched_ mutations efficiently. I’m not even sure if taking it to a service worker would do more then free the main thread for the seconds that it takes 😣

My recommendation is instead of sending 40-250 mutations you instead find a way to combine those all into a single mutation request. There are two options for doing this:

The first is you could put all the mutations into a single GraphQL document:

```graphql
mutation myMutations($input1: Input1!, $input2: Input2!, $input3: Input3!) {
  mutation1(input1: $input1) { ... }
  mutation2(input2: $input2) { ... }
  mutation3(input3: $input3) { ... }
  ...
}
```

Or write a batch mutation on your server that takes an array:

```graphql
mutation myMutations($inputs: [Input1!]!) {
  myBatchMutation1(inputs: $inputs) { ... }
}
```

Or some combination of both:

```graphql
mutation myMutations($inputs1: [Inputs1!]!, $inputs2: [Inputs2!]!, $inputs3: [Inputs3!]!) {
  mutation1(inputs1: $inputs1) { ... }
  mutation2(inputs2: $inputs2) { ... }
  mutation3(inputs3: $inputs3) { ... }
  ...
}
```

This should _greatly_ reduce the time you spend in `apollo-client` and rerendering with Angular. For every mutation `apollo-client` reads from the store, runs `updateQueries`, writes that back to the store, triggers a Redux state subscriber, and tries to rerender your application with the changed data.

**Comment by stubailo** [comment]
Yeah I've been thinking having a way to deliver many results to the store in one batch could be useful to avoid this kind of thing.

**Comment by calebmer** [comment]
@stubailo that could help as we wouldn’t be rerendering 40–250 times, but we would still be reading, writing, and running `updateQueries` 40–250 times. Although that is likely much less severe then re-rendering.

**Comment by manuelfink** [comment]
Thx @calebmer, gonna give it a try within the next week. 

Did not new about input types. Was searching for graphql mutation array but did not came across input types. This would also allow me to do a batch update to database and improve performance on server a lot too. 

Regarding performance would it not make sense to batch process all mutations and than trigger redux state subscriber?

In apollo for angular 2 it seems to me that I only get one rendering at the end though. At least the subscriber to apollo watchQuery is only fired once.

**Comment by calebmer** [comment]
I’m going to close. We definitely want a faster implementation, but optimizing the execution of 40–250 GraphQL requests at once isn’t at the top of our priority list. It makes much more sense to combine those GraphQL requests into 1 which Apollo Client handles efficiently today 😊
