### ISSUE TITLE
Performance implications for using Redux

### ISSUE THREAD

**Issue by ncthis** [apollographql/apollo-client#1296]
I've been working a lot with react-native and apollo client and have a few grievances related to performance.

Imagine I'm doing a `<BookList />` of component `<BookListItem />`. 

Query co-location means that my `BookList` will know which list item ids to get and how to sort them. But the name, author and everything else will be retrieved by `BookListItem`.

Which means, I will connect the following queries to my components:

```js
// on BookList
{
  books {
    id
    publishedOn
  }
```

```js
// on BookListItem
{
  book (id: $id) {
    author {
      id
    }
    name
    ...whatevs
  }
}
```

So, this will fetch the first query on `BookList` to get the ids (along with 2 redux actions, `APOLLO_QUERY_INIT` and `APOLLO_QUERY_RESULT`), and two actions to get each book data on `BookListItem`.

Now, imaging that query batching is turned on, and network querying is a non-issue. Still, I'd be firing 2 + 200 redux actions for this component. (200 actions for 100 `BookListItem` instances)

The problem is quickly escalated when I have an `<Author id={book.author.id} />` inside of my `BookListItem`, and if author needs `{ author (id: $id) { name } }`. In this instance, we'd be doing another 200 actions for 100 distinct authors.

Now the solution would be to get whatever I need on `BookList` and pass down through props - thereby minimizing subscriptions and fired actions. But as a result, benefits of query-colocation get negated.

This is more of a problem in react-native where animation is mostly done on the javascript thread - where firing a lot of redux actions/subsequent reductions will bring everything to a halt. And if a user navigates away from the component while the data is loading, there will be an additional n amount of `APOLLO_QUERY_STOP` actions.

To mitigate some of these, I've invented my own `delayedGraphqlConnector`, `renderAfterTransitions` decorators. And they've been successful in solving the problem to a certain degree.

So, I'm asking, is this the intended behavior, or am I overlooking something significant? In either case, is redux the best way to go on about this?

**Comment by calebmer** [comment]
Is there any way to reduce the number of queries you are sending? For instance, change your colocated queries to fragments and then add a field on the GraphQL server: `books(id: [ID])` which will get all of the books in one query, or combine your two queries together. It is ideal whenever possible to group all of your data into a single request (whether you use the batched network interface or not). We encourage collocating _fragments_ with components and not collocating actual GraphQL queries with their individual components, so with this assumption we generally don’t optimize for the 200 query case 😣

I agree that there are some problems that come from us using Redux, but I don’t think that this specific case is one of them.

Is there any reason why your two queries can’t just be:

```graphql
{
  books {
    id
    publishedOn
    ...BookListItem
  }
}

fragment BookListItem on Book {
  author {
      id
    }
    name
    ...whatevs
}
```

Where the fragment `BookListItem` lives in the `BookListItem` component file? That is the case where GraphQL was designed to play best.

**Comment by ncthis** [comment]
Thanks @calebmer I understand that this is the best way to solve this and intended usage. I was thinking of a lower degree of coupling, where props never flow through parents that don't need them. In component hierarchy A -> B -> C, A would query and flow the subset of props through B to C, even though ideally B does not need to know about it.

A could get the fragments from C, but then A is concerned about an ancestral data-requirement. Which leads us to create a wrapping fragment on B, which adds boilerplate. Latter is not a huge problem, but far from ideal IMHO.

My initial grievance for performance degradation by using redux here still stands though. I think it's what stops this client from doing more queries (even if they are 100% cache hits), while still being performant. Though it is elegant, it's easy to run into problems in resource sensitive environments such as mobile devices.

I will close this since you've answered my question.
