### ISSUE TITLE
apollo-client makes the same graphql request after page load (SSR) even if store is rehydrated.

### ISSUE THREAD

**Issue by alex-kon** [apollographql/apollo-client#1297]
We are using apollo-client with React and wepback to create an isomorphic application. We are rendering the page server side and adding the initial store on the initial HTML payload as described here. 

http://dev.apollodata.com/react/server-side-rendering.html

On the client we serve the bundled queries along with the apollo client so any future requests will be only client side.

However we've noticed that the same graphql request is made on the client after the page loads. So for each full page refresh it is making two identical graphql requests, one on the server for SSR and an identical one when the bundles are loaded in the front end. 

My understanding is the if apollo client finds a store when it is initialised it should not do another graphql query. Is this expected behaviour?

**Comment by calebmer** [comment]
Yes, you are right that we should not send another query 😣

Could you put together a small case reproducing this error? It would go a long way in helping us debug this issue. You could use [`react-apollo-error-template`](https://github.com/apollographql/react-apollo-error-template) even though it is not server-side-rendered by passing a manually exported object into `initialState`.

**Comment by helfer** [comment]
@alex-kon are you using `ssrForceFetch` delay as described in the docs?

**Comment by alex-kon** [comment]
I created the `react-apollo-error-template` example but I couldn't replicate it there.
We are setting the `ssrMode` to true on the server and false on the client, but we are not setting `ssrForceFetch` at all. I believe that is used only when `ssrMode` is true. 

I narrowed it down to a specific query we are using. Removing specific fields from the query fixes the problem. In theory it shouldn't make any difference, that field is an array of objects. I will try to replicate the response in a github example similar to `react-apollo-error-template`.

**Comment by alex-kon** [comment]
We have figured out where the problem is. I haven’t found time to recreate it in a repo but will do soon. 

Consider a union type. i.e.

`union Content = TypeOne | TypeTwo | TypeThree`

If in our query we ask for only some of all the types, and not all of them, then the response for the types that are not requested is an empty object. i.e. 

` query {
	someField {
		… on TypeOne {
			id
		}
		… on TypeTwo {
			id
		}
	}
}  `

`someField: [
	{
		id: ‘someiD’
	},
	{
		id: ‘someiD’
	},
        {} // this is the response for TypeThree
]`


Even though the type TypeThree of the union has data, because we didn’t specify it in the query it returns an empty object literal. This seems to be causing apollo-client to make another request. Not sure if this is the expected behaviour due the strict type system enforced by GraphQl.
If we correctly request all the types i.e. 

`query {
	someField {
		… on TypeOne {
			id
		}
		… on TypeTwo {
			id
		}
		… on TypeThree {
			id
		}
	}
} `

Then the response has the data for the third type as well, and apollo-client doesn’t make a new request.

`someField: [
	{
		id: ‘someiD’
	},
	{
		id: ‘someiD’
	},
        {
		id: ‘someiD’
        }
]`

Hope that makes sense.

**Comment by calebmer** [comment]
Yep this makes sense. There are some subtle bugs with our handling of inline types on unions or fragments. As we refactor our store implementation we hope to eliminate many of these bugs.

**Comment by fubhy** [comment]
I am discussing the same issue here: https://github.com/apollographql/apollo-client/issues/1337

**Comment by alex-kon-turner** [comment]
Great, will follow it there.

**Comment by alex-kon** [comment]
Great, will follow it there.

**Comment by helfer** [comment]
Should be fixed with #1487! 🙂
