### ISSUE TITLE
Apollo Client Removes Data from other Queries

### ISSUE THREAD

**Issue by patrickml** [apollographql/apollo-client#1298]
We have two queries that pull content from the same resource. Once pulls basic information like name and createdAt, then when a user navigates to another part of that resource we pull the data required. 

**Intended outcome:**
Query 1 pulls data and it should exist on the record
Query 2 pulls data and appends/updates the new data
Each query then filters out the unneeded data from the document when passed to its component
When a query is mutated the document is mutated and the filtering takes place

**Actual outcome:**
When updating a query it seems to reduce the document to only the mutation for all queries that pull the same document

**How to reproduce the issue:**
Query 1
```
const fetchSegmentGQL = gql`
  query SegmentGeneral( $botId: ID!, $segmentId: ID! ) {
    segment(botId: $botId, id: $segmentId) {
      __typename
      id
      botId
      name
      goal
    }
  }
`;
```

Query 2
```
const fetchSegmentGQL = gql`
  query SegmentTargets( $botId: ID!, $segmentId: ID! ) {
    segment(botId: $botId, id: $segmentId) {
      __typename
      id
      botId
      targets {
        filter
        score
      }
    }
  }
`;
```

![image](https://d3uepj124s5rcx.cloudfront.net/items/1a2c1r1m2N1Q141r300J/Screen%20Recording%202017-02-15%20at%2003.39%20PM.gif?v=568c13cf)

**Comment by calebmer** [comment]
This is definitely the intended behavior. Does the id returned by `dataIdFromObject` change between requests? This is generally a symptom for that issue.

If not then could you reproduce this error using [`react-apollo-error-template`](http://github.com/apollographql/react-apollo-error-template)? It would go a long way in helping us debug the issue and get you a fix in a timely manner.

**Comment by patrickml** [comment]
@calebmer i don't think so its just the document id from our database

```
export default new ApolloClient({
  networkInterface,
  dataIdFromObject: (o) => o.id,
});
```

**Comment by calebmer** [comment]
Try adding the `__typename` as well. So something like:

```js
function dataIdFromObject (o) {
  if (o.__typename && o.id) {
    return `${o.__typename}:${o.id}`.
  }
}
```

There may be another object with the same `id`, but a different `__typename` that is messing up the cache?

**Comment by patrickml** [comment]
we are using uuid v4 so i doubt its the id, i just tried to implement the function you just provided but it didn't seem to make a diff. 

I am currently working on the error template, but since its using plain gql its a little bit of a learning curve xD im using to the apollo flavor of everything.

**Comment by calebmer** [comment]
Hypothetically it shouldn’t be too hard to use `graphql-tools` with the error template if you are more comfortable with that 😊

**Comment by wmertens** [comment]
@patrickml you can also inspect the graphql network requests to see if they errored, and your server logs of course.

**Comment by patrickml** [comment]
@wmertens there are no errors :/ everything works and things are saved, the problem is that my other queries are updating.

**Comment by patrickml** [comment]
@calebmer here is the example repo https://github.com/patrickml/react-apollo-error-two-queries-one-document/tree/master/src

**Comment by calebmer** [comment]
It looks like there are two things going on here. Firstly, you are not returning the `name` field for the person in your mutation: https://github.com/patrickml/react-apollo-error-two-queries-one-document/blob/f330fa5189ed81f6d8b97989842f24e6ec0fc16b/src/graphql/schema.js#L59-L62

This means your mutation which has a selection set of:

```graphql
{
  person {
    id
    name
    age
  }
}
```

Will return:

```json
{
  "person": {
    "id": 2,
    "name": null,
    "age": 42
  }
}
```

Note how there is a `null` there. So `apollo-client` dropping the `name` field makes sense. It is just doing what the server told it to do. If you want to prevent null fields on the server then you could use `new GraphQLNonNull(GraphQLString)` here: https://github.com/patrickml/react-apollo-error-two-queries-one-document/blob/f330fa5189ed81f6d8b97989842f24e6ec0fc16b/src/graphql/schema.js#L15

Secondly, you are not providing the `name` with your mutation optimistic response (here: https://github.com/patrickml/react-apollo-error-two-queries-one-document/blob/f330fa5189ed81f6d8b97989842f24e6ec0fc16b/src/upsertAge.js#L38) even though you request the name (here: https://github.com/patrickml/react-apollo-error-two-queries-one-document/blob/f330fa5189ed81f6d8b97989842f24e6ec0fc16b/src/upsertAge.js#L21).

You should provide `name` _wherever_ it is asked for in your queries. That’s the main issue here. If you wanted a really quick fix you could just stop querying the `name` field here: https://github.com/patrickml/react-apollo-error-two-queries-one-document/blob/f330fa5189ed81f6d8b97989842f24e6ec0fc16b/src/upsertAge.js#L21

However, that does not fix the root problem. So maybe this is a server side error for you?

**Comment by patrickml** [comment]
@calebmer not sure if you read the little bit of notes I had in the main screen when the app runs, but basically I have one upsert HOC in my real app so i don't need to replicate any code. So it returns all fields possible for in my case a "segment"

```
const upsertSegment = gql`
  mutation upsertSegment( $segment: SegmentInput! ) {
    upsertSegment(segment: $segment) {
      __typename
      id
      botId
      organizationId
      name
      goal
      targets {
       filter
       score
      }
      suppressions {
        filter
      }
      createdAt
    }
  }
`;

export default graphql(upsertSegment, {
  props: ({ mutate, ownProps: { botId } }) => {
    const upsertSegment = (data) => {
      const segment = omit(data.toJS(), '__typename', 'createdAt');

      mutate({
        variables: { segment, botId },
        optimisticResponse: {
          __typename: 'Mutation',
          upsertSegment: {
            __typename: 'Segment',
            ...segment,
          },
        },
        updateQueries: {
          SegmentList: (previousResult, { mutationResult }) => (
            update(previousResult, {
              segments: {
                $unshift: [mutationResult.data.upsertSegment],
              },
            })
          ),
        },
      });
    };
    return {
      upsertSegment,
    };
  },
});
```

This is so that I can just do something like

```
import upsertSegmentHOC from 'mypath.js';

export const formHOC = compose(
  injectIntl,
  upsertSegmentHOC,
  fetchSegmentHOC,
  reduxForm({
    // a unique identifier for this form
    form: 'segmentTargetForm',
    // our validation function
    validate,
    // Allow apollo to update form while open
    enableReinitialize: true,
    // Keep changed fields if updated
    keepDirtyOnReinitialize: true,
  })
);

export default formHOC(SegmentTargets);
```

and i can use `upsertSegmentHOC` over and over again in many places. 

I'd expect that if one query says it needs a value and it has one then receiving null shouldn't wipe it clear since there is an active query looking at that bit of information.

**Comment by patrickml** [comment]
@calebmer to solve this issue im just going to pass in the fields i need per instance of the upsertSegment mutation

```js
const query = (fields) => gql`
  mutation upsertSegment( $segment: SegmentInput! ) {
    upsertSegment(segment: $segment) {
      __typename
      id
      ${fields}
    }
  }
`;

export default (fields) => graphql(query(fields), {
  /* code */
}
```

**Comment by calebmer** [comment]
That’s probably correct. Think about it this way:

If Apollo Client didn’t get `null` for a given field, say it got a new name like `"John Smith 2"` it would then update that field in the cache with the new value. This is the expected behavior. So, if Apollo Client gets `null` it would also update the name to `null`. There is no extra information, in this case, to tell Apollo Client that `null` _actually_ means ignore. Instead, Apollo Client just sees that the GraphQL server returned a `null` and updates the cache appropriately. If semantically the server does not mean “wipe this field” when returning `null` then the server should return some other value.

I’m going to close. Please let us know if we have misinterpreted your issue or if you have other questions 😊

**Comment by patrickml** [comment]
Sounds good.
