### ISSUE TITLE
cache redirects with customResolvers on nested objects

### ISSUE THREAD

**Issue by petergarnaes** [apollographql/apollo-client#1301]
So I am experimenting with Apollo by making a webpage where groups of people can arrange events together. I am following along with the guide on cache [redirects and `customResolvers`](http://dev.apollodata.com/react/cache-updates.html#cacheRedirect) and I have a query that looks like this:
```
{
  group {
    events(range: {start: "ISOdate",end: "ISOdate"}){
      id
      ...otherFields
    }
  }
}
```

Which returns a list of events. When looking at the details of of one of these events, I want to fetch that event from cache, and so my component showing details run the query:
```
{
  group {
    event(id: $id){
      id
      ...otherFields
    }
  }
}
```

and my network interface has the following `customResolvers`:

```
customResolvers: {
  Query: {
    event: (_, args) => {
      return toIdValue(dataIdFromObject({ __typename: 'Event', id: args['id'] }))
    },
  },
},
```

However, it is not fetching it from cache. Is this a problem with my implementation, or does `apollo-client` not work like this? 

Is this because the `Query { event }` is not the same as `Query { group { event } }`? Is there any way to specify this to the `customResolvers` or do I have to write something completely different?

**Comment by calebmer** [comment]
What is the `__typename` for `group`? Or: `{ group { __typename } }`.

Try using that name instead of `Query` with your `customResolvers`.

**Comment by petergarnaes** [comment]
@calebmer It worked! Thanks a lot! It might be worth explaining in a small paragraph in the documentation on [`customResolvers`](http://dev.apollodata.com/react/cache-updates.html#cacheRedirect).

**Comment by ali** [comment]
@petergarnaes OOC, what was the working solution?

something like this? 👇🏽

```js
customResolvers: {
  group: {
    event: (_, args) => {
      return toIdValue(dataIdFromObject({ __typename: 'Event', id: args['id'] }))
    },
  },
},
```

**Comment by calebmer** [comment]
@ali if `group` is the name of the type you are targeting then yes 😊. If the name of the type you are targeting is `Group` then you should use that instead 👍

**Comment by stubailo** [comment]
BTW PRs to the docs are always appreciated to make things clearer!

**Comment by maxsalven** [comment]
@calebmer @stubailo 
Sorry to bother you guys on this, but I'm still not clear on how I should be naming things in `customResolvers`.

I have one component that loads a user and their results:
```javascript
const UserQuery = gql`
  query getUser($id: ID!) {
    user(id: $id) { 
      id, 
      name, 
      results {
        id, description, details
      } 
    }
  }
`;
const UserWithData = graphql(UserQuery)(User);
```

I then have another self-contained component that renders an individual result and some info about its user. I'm using the following query, which will be fully cached already by the previous one, and these components only load once the UserWithData component renders, so we shouldn't need a network hit:

```javascript
const ResultQuery = gql`
  query getResult($id: ID!) {
    result(id: $id) { 
      id, 
      description, 
      user {
        id, 
        name
      } 
    }
  }
`;
const ResultWithData = graphql(ResultQuery)(Result);
```

However I'm not sure how to set up `customResolvers` so that I can avoid the unnecessary network query? Especially seeing as I have a list of 100s of `ResultWithData` components.

```javascript
const dataIdFromObject = ({ __typename, id }) => __typename + ":" + id;

...

customResolvers: {
    Query: {
      user: (_, args) =>
        toIdValue(dataIdFromObject({ __typename: "User", id: args["id"] })),
      result: (_, args) =>
        toIdValue(dataIdFromObject({ __typename: "Result", id: args["id"] })),
    },
  },
```

The above does not work. Thanks!

**Comment by zunder** [comment]
@maxsalven did you find the answer to your question? I am having the same issue.

**Comment by maxsalven** [comment]
@zunder Unfortunately I haven't looked in to it all since posting that message, so no progress on this end.

**Comment by helfer** [comment]
@zunder It looks right to me. Have you tried logging the output or stepping through with the debugger?
