### ISSUE TITLE
Afterware no longer called with bad HTTP status codes

### ISSUE THREAD

**Issue by NeoPhi** [apollographql/apollo-client#1303]
I'm noticing a regression in apollo-client.

Afterware no longer seems to be called with the batchedNetworkInterface if the fetch results in an HTTP status code of 401.

So the pattern here http://dev.apollodata.com/core/network.html#networkInterfaceAfterware no longer seems to work

Problem seems to be related to: https://github.com/apollographql/apollo-client/blob/master/src/transport/batchedNetworkInterface.ts#L69

**Comment by calebmer** [comment]
Hmm, perhaps adding that error throw was a mistake…

We added it to provide better information when the JSON parse failed. Could we add afterware calling at that point even though an error was thrown?

**Comment by pseudoramble** [comment]
In the case you get a 401 from a service, trying to parse the JSON response would fail and reject the promise with a string value like `Uncaught (in promise) SyntaxError: Unexpected token U in JSON at position 0`. So would this pattern have worked prior to this change?

It does seem like it could be modified to catch this and apply the afterware with the one response to make this pattern work though.

**Comment by calebmer** [comment]
This response was undesirable to most users: `Uncaught (in promise) SyntaxError: Unexpected token U in JSON at position 0`. That’s why we made the change.

**Comment by majodev** [comment]
As far as i can tell, the client instance no longer exposes a way to globally handle special error codes. :(

Currently thinking about proxying the `client.query` and other methods or subclassing the ApolloClient to supply a single catch handler that just rethrows finally. Anyways, would be fairly ugly. Is this use case still on the radar (as https://github.com/apollographql/apollo-client/pull/1316 is now closed)?

**Comment by pseudoramble** [comment]
Would a way to resolve this be to invoke the afterwares in both the case when a response is not OK and when the responses are OK? Something like:

```
// When the response is not OK
const httpResponse = result as Response;

if (!httpResponse.ok) {
  this.executeAfterware([httpResponse], requestsAndOptions);
  // Perform error handling as it is
}
```

```
// When the responses are OK
if (typeof responses.map !== 'function') {
  throw new Error('BatchingNetworkInterface: server response is not an array');
}

const afterwaresPromises = this.executeAfterware(responses, requestsAndOptions);
// Perform normal Promise.all(afterwarePromises) handling
```

**Comment by helfer** [comment]
@pseudoramble I think that's a reasonable approach, so if you make a PR we can work together to get it merged.

One question I have is whether it should be possible for the afterware to modify the response in such a way that it no longer throws. If that's desirable, the afterware should be called even before the if (assuming that the response is modifiable).

**Comment by pseudoramble** [comment]
That's a good point @helfer. I don't think there is much that can be modified on a Response object itself. It does look lie you can return different kinds of Response's from it (like a redirect) but that creates a new Response object. 

The other case I could think of is if the user throws an error that they want to use instead of the `batchedNetworkInterface` error with the response that gets thrown. But that should still work with this setup.

**Comment by petejkim** [comment]
> This response was undesirable to most users: Uncaught (in promise) SyntaxError: Unexpected token U in JSON at position 0. That’s why we made the change.

Right now this bug is preventing afterware from getting invoked even if there is no JSON parse error. I am correctly returning `[{"data":{},"errors":[{"message":"jwt expired"}]}]` with 401 status code.

**Comment by helfer** [comment]
@petejkim I've merged the PR, and the fix will be shipped when the first RC is released early next week!
