### ISSUE TITLE
Using master branch

### ISSUE THREAD

**Issue by joshg111** [apollographql/apollo-client#1308]
I just want to use the apollo-client master branch since there is some fix there i would like to use now. 

In my package.json file I give the following:
"apollo-client": "https://github.com/apollographql/apollo-client.git#master"
Then I run npm update apollo-client. 
Then i get an error:
$ npm update apollo-client
cars@0.0.1 /home/joshg111/Projects/cars
└── UNMET PEER DEPENDENCY apollo-client@0.8.6 (git+https://github.com/apollographql/apollo-client.git#9740a71998727fd8f01381cd3a92981963bf42e7)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN react-apollo@0.8.3 requires a peer of apollo-client@^0.6.0 but none was installed.
npm ERR! code 1

Then when i start the app I get an error saying that it's unable to resolve the apollo client module. 

If I use any tag eg. 0.8.6 it works fine, just when i use the url it fails. 

Sorry this is a basic question and is prolly not an issue with this repo, but anyone willing to shout out some recommendations would be very appreciated.

**Comment by calebmer** [comment]
You are going to need to build the library with `npm run compile` before you can use it. The best way to use the master branch is to clone it, then install _all_ dependencies (including dev dependencies), then running `npm run deploy` (the last publish step should fail, that is ok) and `npm install`ing or `npm link`ing the `./npm` folder that gets created by `npm run deploy`.

Unfortunately, it is not that easy, but if you wanted to submit a PR to make the process easier that would be awesome 😊
