### ISSUE TITLE
Specify better type of client.reducer()

### ISSUE THREAD

**Issue by ligaz** [apollographql/apollo-client#1312]
Currently the type of `ApolloClient.reducer()` is just `Function` which is not compatible with the one expected from Redux `combineReducers` function: `<A extends Action>(state: S, action: A) => S`. Ideally those should be compatible out of the box. 

[Here](https://github.com/apollographql/apollo-client/blob/8fb44ef7a66f4d411519f0378b121ba3cc145dd7/src/store.ts#L179) is a reference in the codebase as well.

**Comment by calebmer** [comment]
Is this just a bug report for TypeScript users? If so I completely agree that we should provide a better type in this scenario. Would you be willing to submit a PR to fix the type?

**Comment by helfer** [comment]
@ligaz do you have time to make a small PR that fixes this?

**Comment by ligaz** [comment]
Thanks!
