### ISSUE TITLE
Question: Is there a way to pass custom options to network interface?

### ISSUE THREAD

**Issue by michalkvasnicak** [apollographql/apollo-client#1317]
### Question

Is there a way how to pass a custom query option to network interface? My specific use case is that I want to determine which requests to batch and which don't.

I have simple network interface which determines which network interface (normal, batching) it should use based on the custom option available. 

As a workaround I am using `variables` on request.

### Example

```js
// @flow

type NetworkInterfaceOptions = {
  [key: string]: any,
}

type RequestInterface = {
  debugName?: string;
  query?: any;
  variables?: Object;
  operationName?: string;
  noBatch?: boolean, // I would like this to be passed to query()
  [additionalKey: string]: any;
}

export interface NetworkInterface {
  query(request: RequestInterface): Promise<any>,
}

type NetworkInterfaceCreator = (options?: ?NetworkInterfaceOptions) => NetworkInterface;

export default function customNetworkInteface(
  normalInterface: NetworkInterfaceCreator,
  batchedInterface: NetworkInterfaceCreator,
  options?: ?NetworkInterfaceOptions
): NetworkInterface {
  const normal = normalInterface(options);
  const batched = batchedInterface(options);

  return {
    query(request) {
      if (request.variables != null && request.variables.__noBatch === true) {
        return normal.query(request);
      }

      return batched.query(request);
    },
  };
}
```

**Comment by calebmer** [comment]
I thought there was, but after a quick look at the code it looks like there is not. If you’re interested this is something you could add. By passing in a `requestMetadata` object or similar to watch query options you could add extra values.

**Comment by helfer** [comment]
@calebmer I was under the impression that since a fairly recent PR you could pass whatever request options you want to the network interface, but that the network interface would only send query, operationName and variables. Is not actually the case?

**Comment by calebmer** [comment]
@helfer tracing the execution of requests. Let me know if I’m missing anything:

1. `Request` objects are used to send requests (https://github.com/apollographql/apollo-client/blob/d10a1eeeee97eedf0c7c3138e264ae9d01ab1f9b/src/transport/networkInterface.ts#L174)
2. `Request` will take any number of additional keys (https://github.com/apollographql/apollo-client/blob/d10a1eeeee97eedf0c7c3138e264ae9d01ab1f9b/src/transport/networkInterface.ts#L30)
3. A `Request` object is created in `QueryManager` twice which gets sent to `NetworkInterface#query`.
4. The first time is in `QueryManager#mutate` and we don’t add any extra keys. (https://github.com/apollographql/apollo-client/blob/d10a1eeeee97eedf0c7c3138e264ae9d01ab1f9b/src/core/QueryManager.ts#L244-L248)
5. The second time is in `QueryManager#fetchRequest` where all queries get sent to. (https://github.com/apollographql/apollo-client/blob/d10a1eeeee97eedf0c7c3138e264ae9d01ab1f9b/src/core/QueryManager.ts#L932-L936)
6. It’s worth noting that in `fetchRequest` we send the query to a `Deduplicator` instance which does not add any additional keys (https://github.com/apollographql/apollo-client/blob/d10a1eeeee97eedf0c7c3138e264ae9d01ab1f9b/src/transport/Deduplicator.ts#L20-L36)
7. We also create a `Request` for subscriptions, but that’s irrelevant. Also note there is no space to add additional keys. (https://github.com/apollographql/apollo-client/blob/d10a1eeeee97eedf0c7c3138e264ae9d01ab1f9b/src/core/QueryManager.ts#L716-L720)

**Comment by helfer** [comment]
@calebmer That looks about right. So anything that gets added to request should stay there throughout the middlewares.

**Comment by calebmer** [comment]
Yeah, but you can only add metadata in middlewares and you can’t pass in any metadata from top of the funnel methods like `client.query`, `client.watchQuery`, `client.mutate`, etc. which would solve this issue 😣

**Comment by helfer** [comment]
Closing up some old issues. Let's make sure to take this into consideration when implementing the next client and network interface API.

**Comment by joelmukuthu** [comment]
Hi @helfer, is there an issue where we can track issues that are up for/passed consideration into future releases?

**Comment by helfer** [comment]
@joelmukuthu Funny that you ask, I'm updating the roadmap this week, which we hadn't updated since 1.0 🙂 I'll also open a discussion issue about the roadmap, because I think that makes sense.

**Comment by joelmukuthu** [comment]
nice! thank you for the great work you guys are doing btw :)
