### ISSUE TITLE
Generate schemas when queries and fragments are specified in-line

### ISSUE THREAD

**Issue by Waitak** [apollographql/apollo-client#1323]
With the removal of `createFragment`, it is no longer clear what the best practice is for specifying a large set of queries and fragments in such a way that a client-side (Typescript, in my particular case) schema can be generated with apollo-codegen. An example of best practice would be very helpful.

The best I've been able to come up with is something like:

    const CodeSetFragmentNode: DocumentNode = require('graphql-tag/loader!../../graphql/CodeSetFragment.gql');
    const CodePairFragmentNode: DocumentNode = require('graphql-tag/loader!../../graphql/CodePairFragment.gql');
    const _CodeSetQueryNode: DocumentNode = require('graphql-tag/loader!../../graphql/CodeSet.gql');
    const _CodeSetsQueryNode: DocumentNode = require('graphql-tag/loader!../../graphql/CodeSets.gql');

    const CodeSetQueryNode: DocumentNode = gql `
    ${_CodeSetQueryNode}
    ${CodeSetFragmentNode}
    ${CodePairFragmentNode}
    `
    const CodeSetsQueryNode: DocumentNode = gql `
    ${_CodeSetsQueryNode}
    ${CodeSetFragmentNode}
    ${CodePairFragmentNode}
    `

**Intended outcome:**

1. Follow current guidelines for specifying queries with the `gql` tag.
2. Generate Typescript schemas with apollo-codegen

**Actual outcome:**

Specifying queries in-line precludes specifying queries and fragments in `.gql`/`.graphql` files.

**Comment by helfer** [comment]
Hi @Waitak. Thanks for filing an issue. I don't think this is the right repo though. Could you open it again on graphql-tag or apollo-codegen? Thanks 🙂
