### ISSUE TITLE
Update @types/isomorphic-fetch optional dependency for typescript 2.2

### ISSUE THREAD

**Issue by davidye** [apollographql/apollo-client#1324]
In typescript 2.2 fetch definitions are now included in the dom lib. In apollo-client, there is a dependency on an older version of @types/isomorphic-fetch and that is causing duplicate type definition errors. Updating that dependency should fix the issue.

**Comment by stubailo** [comment]
Will removing it break things for people using typescript older than 2.2?

**Comment by davidye** [comment]
Yes it should be backwards compatible: see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14796

**Comment by stubailo** [comment]
Ah! @davidye want to send a PR updating to the correct version?

**Comment by davidye** [comment]
@stubailo Hmm a simple version bump didn't work as there have been some changes between @types/isomorphic-fetch versions 0.0.30 => 0.0.33.

For example IResponse => Response in the latest version. And updating seems to cause conflicts with: https://github.com/apollographql/apollo-client/blob/c93b4cc56a9e30f8062a1d3501b7ee811f7a9edd/fetch-mock.typings.d.ts#L9

**Comment by helfer** [comment]
@davidye have you tried setting `skipLibCheck`? That should work around the lodash thing. The other things will have to be changed in the Apollo Client source code.

**Comment by davidye** [comment]
@helfer I just want to fix this specific issue since it's preventing us from upgrading typescript.

Updating apollo-client to typescript 2.2 is a separate issue which I didn't really dig into.

**Comment by helfer** [comment]
@davidye I see. In that case I'll try to make time to fix it over the weekend and release a new patch version for you.

**Comment by agonbina** [comment]
@helfer it would be great to release a patch with the fix from @davidye soon as I struggled with this issue after updating all my dependencies 🥇

**Comment by helfer** [comment]
Fixed and released 🙂

**Comment by lionhive** [comment]
Having same problem with typescript 2.2.1 and @types/graphql.

> $ tsc -v
> Version 2.2.1

> /Users/tomasvykruta/Documents/playground/pollo_starter/apolloclient
> ├── @types/graphql@0.8.6 
> └─┬ apollo-client@0.8.7
>   ├── @types/async@2.0.39 
>   ├── @types/graphql@0.8.6  deduped
>   └── @types/isomorphic-fetch@0.0.30 

Many errors due to conflict (showing only few here)

> $ tsc
> node_modules/@types/isomorphic-fetch/index.d.ts(23,14): error TS2300: Duplicate identifier 'BodyInit'.
> node_modules/@types/isomorphic-fetch/index.d.ts(24,14): error TS2300: Duplicate identifier 'RequestInfo'.

**Comment by sheeldotme** [comment]
@helfer @stubailo, I'm not sure this issue has been fixed adequately.

For the use case where one is using lerna (I couldn't see a way to prevent optional dependencies from being installed), or, the use case where one does want to take advantage of most of the optional dependencies, one wouldn't want to `npm install --no-optional`, because this would affect all project dependencies not just react-apollo.

Changing @types/isomorphic-fetch from an optional dependency to a dev dependency seems to resolve the issue as its scope is then limited to the package in question.  Are there any potential issues you see with my solution?

**Comment by agonbina** [comment]
I am also running into the same issue as @lionhive. Did you find a fix/workaround by any chance?

**Comment by reverie** [comment]
I'm hitting this same problem. It's frustrating because my project was working fine before, but now there's this broken dependencies. What is the right version of apollo-client that doesn't rely on the broken isomorphic-fetch 0.0.33, but that *also* does not force me to upgrade from React 15 to 16?
