### ISSUE TITLE
Reducer not working

### ISSUE THREAD

**Issue by elie222** [apollographql/apollo-client#1330]
The example listed here doesn't work:
http://dev.apollodata.com/react/cache-updates.html#resultReducers

I created an Apollo provider gave it a store, dispatched an action to the store, but the callback in the example is never called.

**Comment by helfer** [comment]
Hi @elie222 could you reproduce the error using the [error template](https://github.com/apollographql/react-apollo-error-template). That would help us a lot in solving this issue quickly. Thanks!

**Comment by helfer** [comment]
The example comes from GitHunt. If it's really broken, please open an issue there so we can fix it!
