### ISSUE TITLE
Unhandled promise rejection when error in polling query on SSR

### ISSUE THREAD

**Issue by DimitryDushkin** [apollographql/apollo-client#1334]
**How to reproduce the issue:**
1. Setup SSR
2. Setup query polling:
```js

export default graphql('query Samples { ... }', {
    options: {
        pollInterval: 5000,
        forceFetch: true,
        notifyOnNetworkStatusChange: true
    }
})(PageLabSamples);
```
3. Throw error in `Samples` query's resolver.

**Intended outcome:**
Error thrown once.

**Actual outcome:**
Error thrown twice: one for SSR and another after polling interval. The problem is second throw is not catchable so it shuts down whole server.

apollo-client 0.9.0

**Comment by DimitryDushkin** [comment]
The only "fix" for this I've found is to turn off polling on SSR:
```js
const isBrowser = typeof window !== 'undefined';

export default graphql(SamplesQuery, {
    options: function() {
        return isBrowser
            ? {
                pollInterval: 5000,
                forceFetch: true,
                notifyOnNetworkStatusChange: true
            }
            : {};
    }
})(PageLabSamples);
```

**Comment by calebmer** [comment]
We should not be polling when server-side rendering, especially considering that the React components don’t even mount.

See https://github.com/apollographql/react-apollo/pull/493 which should fix the issue. Tell me if that change solves it for you.

**Comment by helfer** [comment]
@DimitryDushkin Could you make a PR that checks the `ssrMode` flag before starting to poll, and just not poll when it's `true`? That way this problem could be solved internally to Apollo Client.

**Comment by DimitryDushkin** [comment]
@helfer Sure, I'll try to make PR on this week.
