### ISSUE TITLE
Apollo stringifies error objects when console logging.

### ISSUE THREAD

**Issue by thomassuckow** [apollographql/apollo-client#1335]
It becomes difficult to interpret errors from Apollo because stack traces are strings and thus source-maps don't get applied.

**Intended outcome:**
Stack traces reference the file they came from

**Actual outcome:**
Stack traces are strings and show minified file names and line numbers.

**How to reproduce the issue:**
Cause apollo to output a console.error message that uses `e.stack`

It would be better to instead simply log the original error:

Dont: `console.error("My message " + e.stack)`

Do: `console.error("My message", e)`

**Comment by calebmer** [comment]
Could you link us to specific places in the code where this happens? Also, does https://github.com/apollographql/apollo-client/pull/1340 change this at all?

**Comment by thomassuckow** [comment]
https://github.com/apollographql/apollo-client/blob/9061b62c27395c06fa3262916cc11ff5ba1fc932/src/core/QueryManager.ts

`${e.stack}`

**Comment by calebmer** [comment]
Ok, I addressed the two in that file: https://github.com/apollographql/apollo-client/pull/1347

Let me know if you find any more 👍

**Comment by helfer** [comment]
Just merged the PR, should be fixed in the next release!
