### ISSUE TITLE
Unhandled error Network error: Cannot read property 'data' of undefined, 0.9.0

### ISSUE THREAD

**Issue by xiaohanzhang** [apollographql/apollo-client#1336]
this error start shows up after upgrade to 0.9.0.
`Unhandled error Network error: Cannot read property 'data' of undefined` 

**How to reproduce the issue:**
It is cause by: [this line](https://github.com/apollographql/apollo-client/blob/master/src/core/QueryManager.ts#L403)
I think we should change `data: lastResult.data` to `data: lastResult && lastResult.data`

**Comment by helfer** [comment]
@xiaohanzhang yeah, looks like you're right. Would you mind making a quick PR?

**Comment by xiaohanzhang** [comment]
@helfer PR created. But I am not sure how to test this kind bug fix.
