### ISSUE TITLE
BatchedNetworkInterface hangs on Jest tests

### ISSUE THREAD

**Issue by mat1h** [apollographql/apollo-client#1343]
**Intended outcome:**
The following test should pass

ApolloClientProvider:
```
import ApolloClient, { createBatchingNetworkInterface } from 'apollo-client'

class ApolloClientProvider {

  client: ApolloClient

  constructor() {
    const batchingNetworkInterface = createBatchingNetworkInterface({
      uri: 'http://www.example.com',
      batchInterval: 10,
      opts: { }
    })

    this.client = new ApolloClient({
      networkInterface: batchingNetworkInterface
    })
  }
}

export default new ApolloClientProvider()
```

Tests:
```
import ApolloClientProvider from 'utils/ApolloClientProvider'

describe('ApolloClientProvider tests', () => {
  it('should pass test', () => {
    expect(ApolloClientProvider.client).not.toBeNull()
  })
})
```

**Actual outcome:**
The test passes, except that Jest doesn't quit. Seems like the `BatchedNetworkInterface` is holding on to a resource.

**How to reproduce the issue:**
Changing the `createBatchingNetworkInterface` to `createNetworkInterface` and would quit Jest just fine.

**Comment by helfer** [comment]
@mat1h thanks for filing an issue. Can you help us figure out what resource it could be holding on to? The code of the batched network interface is pretty simple, and it doesn't require understanding the rest of Apollo Client, so it would be great if you could give it a shot! 🙂

**Comment by lewisf** [comment]
@mat1h what version of jest? i tried to reproduce it here but I couldn't: https://github.com/lewisf/apollo-network-test

**Comment by calebmer** [comment]
It looks like [someone](https://github.com/apollographql/apollo-client/blob/f9e92d19fd9a8279cda77e3b15b6d77a0a56bece/src/transport/batchedNetworkInterface.ts#L62) predicted this would happen 😊

Try adding:

```js
afterAll(() => {
  batchedNetworkInterface.batcher.stop();
});
```

Which calls this [`stop`](https://github.com/apollographql/apollo-client/blob/f9e92d19fd9a8279cda77e3b15b6d77a0a56bece/src/transport/batching.ts#L102-L106) method which clears an interval that is created in [`start`](https://github.com/apollographql/apollo-client/blob/f9e92d19fd9a8279cda77e3b15b6d77a0a56bece/src/transport/batching.ts#L90-L100) which gets called in the [`BatchedNetworkInterface`](https://github.com/apollographql/apollo-client/blob/f9e92d19fd9a8279cda77e3b15b6d77a0a56bece/src/transport/batchedNetworkInterface.ts#L61) constructor.

The correct way to implement batching would probably be to only set a timer after `query` had been called. Scheduling a batch vs. constantly trying to consume a queue of batches which would create a resource that could not be correctly cleaned up.

The method I mentioned above should work as a workaround, however.

**Comment by calebmer** [comment]
Let us know if this does not fix your issue 👍

**Comment by calebmer** [comment]
Another option is to use the `--forceExit` flag: https://github.com/facebook/jest/issues/1456
