### ISSUE TITLE
[Question] Will Apollo Client Support React Router 4 ever?

### ISSUE THREAD

**Issue by OllieJennings** [apollographql/apollo-client#1346]
I have started to transition quite a few of my projects to React Router 4 as it just feels nicer and easier to work with.

Has the Apollo Client team ever thought about supporting it?

Apologies if this has been asked before.

**Comment by calebmer** [comment]
The great thing about React Router 4 is that it is basically just React! Apollo Client integrates cleanly with React and therefore with the rest of the React ecosystem, including React Router v4 which we are very excited about 😊

Please let us know if there are specific integrations you would like to see!

**Comment by OllieJennings** [comment]
@calebmer Thanks for the response, just a quick query.

Currently in the Apollo Client SSR examples, you make use of `match` which is available in react-router 3.

In react-router 4, it appears like match no longer exists (from what l have seen), and instead you must use `StaticRouter`.

How would you implement the Apollo Client with the StaticRouter?

is it simply:

```
<ApolloProvider client={client}?
    <StaticRouter><App /></StaticRouter>
</ApolloProvider>
```

If so, how do you perform the fetching of the data?

**Comment by calebmer** [comment]
You use `renderToStringWithData` instead of `renderToString` from `react-dom/server` 😊

**Comment by OllieJennings** [comment]
@calebmer thank you so much, l feel like an idiot now!
