### ISSUE TITLE
Reset store by dispatching action (e.g. in Saga)

### ISSUE THREAD

**Issue by colophonemes** [apollographql/apollo-client#1349]
Is it possible to trigger the equivalent of `client.resetStore()` by dispatching an action to the store? E.g. from a [saga](https://redux-saga.github.io/redux-saga/docs/api/index.html)?

For example:

```js
// rootSagas.js
export function* watchLogout () {
  yield takeEvery(LOGOUT, function* () {
    cookie.remove('token')
    yield put({type: 'APOLLO_STORE_RESET' /* observableQueryIds here maybe??? */})
    yield put(push('/'))
  })
}
```

Dispatching the action in this way currently doesn't do anything (presumably because it needs `observableQueryIds` to be set), and I'd be missing the things that [`QueryManager.resetStore()`](https://github.com/apollographql/apollo-client/blob/d11a4b4b673698e70bdaaaed404e88734d137562/src/core/QueryManager.ts#L680) runs before dispatching the query.

**Comment by helfer** [comment]
@pseudoramble currently this is not possible because some Apollo internal state needs to be updated as well. There's no fundamental reason why it couldn't be done, we just didn't implement Apollo Client in a way that makes this particular thing easy.

**Comment by colophonemes** [comment]
No problems, thanks for the info (I realise now that I probably should have asked this on [react-apollo](/apollographql/react-apollo) — I'll close this and reopen an issue there).

For anyone else attempting a similar thing, my interim solution is to use a dummy route that resets the store before the component mounts. Not super clean, but gets the job done:

```js
import React from 'react'
import {withApollo} from 'react-apollo'
import { Link } from 'react-router'
import { replace } from 'react-router-redux'
import { connect } from 'react-redux'

class ResetStore extends React.PureComponent {

  componentWillMount () {
    const { client, dispatch, params } = this.props
    client.resetStore()
    dispatch(replace(`/${params.splat || ''}`))
  }

  render () {
    const {params} = this.props
    return (<div>
      <p>If you're not redirected within 3 seconds, click <Link to={`/${params.splat || ''}`}>here</Link>.</p>
    </div>)
  }
}

function mapDispatchToProps (dispatch) {
  return {
    dispatch
  }
}

export default connect(mapDispatchToProps)(withApollo(ResetStore))
```

```js
// routes.js
{
  ...
  path: '/reset-store(/*)'
  ...
}
```
