### ISSUE TITLE
Handling events from a SSR Generated view

### ISSUE THREAD

**Issue by dbrrt** [apollographql/apollo-client#1353]
Hello,

I don't if that's an intentionally missing feature but when I render (following this guide : http://dev.apollodata.com/react/server-side-rendering.html#local-queries, ) my React components on the server, I lose onClick attributes. Maybe that's totally acceptable and normal?

``` javascript
        const html = <Html content={content} state={initialState} />;

        res.status(200);
        res.send(`<!doctype html>\n${ReactDOMServer.renderToString(html)}`);
```

Is that possible to overcome that with a specific configuration or I should continue rendering my views Client-Side to support user event ?

**Comment by helfer** [comment]
@dbrrt That's somewhat surprising. Unless it's a limitation of React SSR (which I find hard to believe) it should still work.

**Comment by dbrrt** [comment]
I found the answer there : http://stackoverflow.com/questions/36323336/onclick-handler-not-registering-with-reactdomserver-rendertostring
It needs to be rendered client side also.
