### ISSUE TITLE
Error after update apollo-client to 0.10.0

### ISSUE THREAD

**Issue by n0ne** [apollographql/apollo-client#1354]
Hi.
Today I updated apollo-client in my test Meteor app from 0.9.0 to 0.10.0.
And now in my Chrome console:

Uncaught Error: Batch middleware must implement the applyBatchMiddleware function
Meteor apollo ver. 0.4.1
apollo-client ver. 0.10.0
react-apollo ver. 0.13.0

And only one row:

const client = new ApolloClient(meteorClientConfig())
What I have to change?

GraphiQL is normally working...
Downgraded to 0.9.0 now...

**Comment by Siyfion** [comment]
@n0ne I think the issue stems from the `meteor-integration` package, specifically these bits: https://github.com/apollographql/meteor-integration/blob/8fbbc84c8d289101e00c19358086bd0e457001ba/main-client.js#L67-L71

**Comment by xavcz** [comment]
Actually these bits are here for handle that if you are using a batching or a network interface :)

The batching interface expects a `applyBatchMiddleware` function.
The network interface expects a `applyMiddleware` function.

See https://github.com/apollographql/apollo-client/pull/1285/files 👍 

To discuss the way `meteor/apollo` handles that, let's move the discussion in the [meteor-integration repo](https://github.com/apollographql/meteor-integration/) 😌

**Comment by helfer** [comment]
Closing here, since it should go on the meteor-integration repo.
