### ISSUE TITLE
Expose connectionParams of subscriptions-transport-ws to subscribeToMore

### ISSUE THREAD

**Issue by timsuchanek** [apollographql/apollo-client#1355]
The `connectionParams` that you can specify in the [subscriptions-transport-ws#connectionParams](https://github.com/apollographql/subscriptions-transport-ws#constructorurl-options-connectioncallback), are essential if you want to have Authorization with subscriptions.
If I see it right, currently you can't pass them in into `subscribeToMore`.

Is that something on the roadmap? Otherwise I might do a PR to add that.
Thanks!

**Comment by Urigo** [comment]
@timsuchanek is it possible that your scenario is being handled [here](https://github.com/apollographql/subscriptions-transport-ws/pull/78#issuecomment-285071402)?

**Comment by calebmer** [comment]
I’m going to close because it looks like @Urigo has a solution. Let us know @timsuchanek if that’s not enough!
