### ISSUE TITLE
apollo-client with mobx store

### ISSUE THREAD

**Issue by mistic** [apollographql/apollo-client#1359]
Hi guys,

It's possible to use apollo-client with an app currently using mobx store?
What's the problems and difficulties that can/will appear in the future?

Regards

**Comment by helfer** [comment]
Apollo Client will work just fine with your mobx application, even if the GraphQL data isn't stored in Mobx but in Apollo's own Redux store. Redux is a very small library, so the additional dependency shouldn't matter. No matter which kind of state management solution you're using, you don't have to care about what type of store Apollo Client uses, unless you want to manipulate it directly (which we don't recommend anyway).

If you don't have complex dependencies between the data in your Mobx store and the data in your apollo store, I don't anticipate any difficulties. For example, if Mobx handles your application's client  / local state and Apollo handles all the server state, you will be just fine and don't need to worry.

Does that answer your question?

**Comment by calebmer** [comment]
I’m going to close this because Apollo Client does work great in your mobx applications today! In the future we may also have a pluggable store architecture. Follow this issue for more information https://github.com/apollographql/apollo-client/issues/1432
