### ISSUE TITLE
Partial Data/Error Responses

### ISSUE THREAD

**Issue by timsuchanek** [apollographql/apollo-client#1374]
Currently, if the result payload of a query contains errors, the whole result is rejected ([here](https://github.com/apollographql/apollo-client/blob/0d4fe2c850ee86f260ec30f9f68b866f5d6ba797/src/core/QueryManager.ts#L961) and then [there](https://github.com/apollographql/apollo-client/blob/0d4fe2c850ee86f260ec30f9f68b866f5d6ba797/src/core/QueryManager.ts#L999)).

At Graphcool, we often times need a hybrid solution where we send an error and the data.
That is especially the case when some part of the query can't be accessed due to missing permissions, but we still want to send back the rest of the query result.

I guess the current behavior has good reasons and changing to these partial responses would result in a major change, the actions would need to be adjusted etc.

What do you think about it? Should that kind of behavior be supported?
Thanks!

**Comment by helfer** [comment]
Hey @timsuchanek ! This is definitely on our radar. We already have a couple of issues on this, one of which is here: https://github.com/apollographql/apollo-client/issues/51

It's something we'd like to do, but it's not on the top of our list of priorities right now. We'd be happy to accept a PR though that makes the result and errors available without messing up the store. I think error paths might be one part of a good solution.
