### ISSUE TITLE
feature idea: send "operationName" only

### ISSUE THREAD

**Issue by rmosolgo** [apollographql/apollo-client#1375]
I've been experimenting with [an approach to static queries](http://rmosolgo.github.io/blog/2017/03/07/persisted-graphql-queries-with-ruby/) based around a _single_ server-side document whose operations are invoked by name from clients.  In this approach, the client doesn't even have access to the query string, _only_ the operation name! 

I'd like try supporting this with Apollo Client but I didn't see a straightforward entry point for this. Is there a good approach I could take here? 

I see that persistgraphql uses a custom network interface, but I'm not sure that will work in my case, since `Request` requires a query ... which I don't have 😆 Do you have any other suggestion for implementing this?

**Comment by rmosolgo** [comment]
Just while I was writing that up, I realized, what if I send an `operationName` with a _blank_ query ... let me give that a try!

**Comment by rmosolgo** [comment]
Oops, it was kind of a dead end. I assumed that `operationName` was accepted by `Client.query`, but  [it's not actually there](http://dev.apollodata.com/core/apollo-client-api.html#ApolloClient\.query) 😬 

Sure enough, passing an operation name: 

![image](https://cloud.githubusercontent.com/assets/2231765/23662328/3358b83a-031d-11e7-9b0a-f2845dda2c31.png)

Doesn't get forwarded to the server: 

![image](https://cloud.githubusercontent.com/assets/2231765/23662363/4cf38248-031d-11e7-8c82-0d4dbcbbe7f3.png)

What do you think, is it feasible to support this use case in Apollo Client, or is it not a good fit?

----------

Btw, I also tried reverse-engineering `persistgraphql` output, but I realized that it was not a very stable approach. Since the query string is used as the lookup key, any deviation between a Ruby printer and a JavaScript printer would result in a lookup miss 😿 . 

I considered another approach as well: splitting the single, large document into smaller `.graphql` files (one per named operation) and passing them through `persistgraphql`, but that's still not quite the right fit, because a repository advertises _name_ based fetching, but that approach would still use the literal query string, so even non-breaking changes to the query would cause lookup misses. 

Is there another way I could accomplish compatibility via `persistgraphl`? I'm out of ideas 😆

**Comment by helfer** [comment]
@rmosolgo Apollo Client still needs the query to read from the cache, but I think it should be possible to build a middleware that strips out the query and only sends operationName and variables. Have you tried that? If there's something blocking that, there's probably a minor change we could do in the network interface to enable that 🙂

**Comment by stubailo** [comment]
Why send an operation name instead of an ID? I feel like you need to be able to change a query over time, while keeping the same operation name.

**Comment by rmosolgo** [comment]
> change a query over time, while keeping the same operation name

That's just it! I think using operation name supports that nicely. 

Let's say you design the `ItemsList` component and the `GetItems` query, then you deploy.

People load your page and store the component & query in JavaScript memory. 

Now, you want to improve the UI and your improvement will need more data. How can you support the new-and-improved UI _and_ the already-deployed UI? (Same question as https://github.com/apollographql/persistgraphql/issues/10).

### By Operation Name 

Your UI needs new data, so you add it: 

```diff 
  query GetItems {
    # ...
+   moreData { 
+     stuff
+   }
  }
```

And redeploy. Already-deployed clients will be overfetching, which is too bad, but not the end of the world. (That is, it's not _breaking_!) 

### By ID 

If the operation identifier is opaque, it's a bit harder to predict how changing the server-side queries will affect already-deployed clients. 

If the identifier is derived from the literal query string, then previously-deployed documents can _never_ be modified, right? Fields can't be reordered, variables can't be renamed,  (Until you decide to stop supporting those clients.) Similarly, fragments cannot be modified, since they may appear in the query strings. 

So, to support a new UI, you must copy-paste a query into a new file and work with that. New fragments should also be copy-pasted, but may extend previous fragments.

I really appreciate GraphQL's approach to API growth (namely, that there's always room for _adding_) and this approach didn't seem to take full advantage of that. 

Another possible snafu is tooling. Some tooling may (someday) modify documents programatically. Maybe a linter will sort fields alphabetically, or maybe an analyzer will read and re-dump a query. If your clients depend on _exact_ matching query strings, you have to be sure that no tooling touches previously-written files, even if its changes would be generally non-breaking. This seemed particularly salient in my case, since there's no guarantee that any tooling written in Ruby would match the output of the equivalent JavaScript tooling, and that could be the source of an identifier mismatch. 

Ok, last thing: as a specific implementation of client IDs, I consider `persistgraphql`'s dependence on the filesystem present be maintenance challenge. Let's say my UI depends on two queries, and I generate some query IDs for them:

```
$ echo "query test1 { test1 }" > documents/test1.graphql
$ echo "query test2 { test2 }" > documents/test2.graphql
$ persistgraphql documents/
Crawling documents/...
Wrote output file to extracted_queries.json.
$ cat extracted_queries.json
{"query test1 {\n  test1\n}\n":1,"query test2 {\n  test2\n}\n":2}
```

Then, I add a new feature which requires a new document. By coincidence, this new document comes alphabetically before the previous ones:


```
$ echo "query new_test { new_test }" > documents/new_test.graphql
```

Before deploying I generate new IDs:

```
$ persistgraphql documents/
Crawling documents/...
Wrote output file to extracted_queries.json.
```

But unbeknownst to me, the previous IDs now point to different documents entirely:

```
$ cat extracted_queries.json
{"query new_test {\n  new_test\n}\n":1,"query test1 {\n  test1\n}\n":2,"query test2 {\n  test2\n}\n":3}
```

As it turns out, not only must _documents_ remain unchanged, but the _entire collection_ must remain unchanged!

Are there other solutions to those issues that I have overlooked? I think operation name works around some of these maintenance challenges because the identifiers are stable and meaningful, and leave room for non-breaking changes on the server-side. 

@helfer Thanks for that suggestion of middleware. I was looking at making a networkInterface and didn't quite see a way, but I haven't tried middleware, I'll give it shot!

**Comment by stubailo** [comment]
> So, to support a new UI, you must copy-paste a query into a new file and work with that. New fragments should also be copy-pasted, but may extend previous fragments.

I don't think so - the idea is that you would store all current and past queries in a database. So every time you modify the query, you save it to your database again, and generate a new unique ID. There is never any chance of a breaking change since you simply never modify the queries.

The extracted queries JSON is not meant to be the only thing you use - it's simply the output of the tool. The IDs in there are meant to be prepended with some unique identifier, and stored in a database, rather than being read from the file directly.

We intentionally didn't ship a middleware that depends on the file system because we were expecting people to implement their own query storage mechanism.

**Comment by Poincare** [comment]
@stubailo ++.

It doesn't make any sense for anyone to use the JSON output in production usage because you'd have to load the entire set of queries into your server response process in order to do a lookup. Most people will probably place their queries into a database/KV-store and be much better off.

**Comment by rmosolgo** [comment]
Thanks for clarifying that usage info! I saw the example under ["Server-side"](https://github.com/apollographql/persistgraphql/blob/31fbbb88eb681ecafbeda7f1d1ab7f2c294272c5/README.md#server-side) and thought that it was suggested suggested usage. Are there any examples of a database-backed setup like that? Obviously I have some more reading to do!
 
And thanks again for pointer towards middleware. I'm going to take a shot at it!

**Comment by stubailo** [comment]
@rmosolgo let me know if you want to jump on a call or something and work through it! I think having support for this in graphql-ruby would be awesome.
