### ISSUE TITLE
When a mutation's promise resolves, how can I get the http status of the response?

### ISSUE THREAD

**Issue by abcd-ca** [apollographql/apollo-client#1376]
Is there a way to get the http status code of a graphql mutation? I need to handle 401s and other error codes.

**Comment by helfer** [comment]
@abcd-ca The most common way to get http status codes on the response is to use an [afterware](http://dev.apollodata.com/core/network.html#networkInterfaceAfterware). Would that work for your use-case?

**Comment by calebmer** [comment]
When your mutation errors you may also get to the status through the `error.response` property. `error.response` will be the response returned by `fetch`.
