### ISSUE TITLE
How to make apolloclient request withCredentials?

### ISSUE THREAD

**Issue by manuelfink** [apollographql/apollo-client#1381]
I'm having issues that cookies are not updated with the graphql request having hard times authenticating and saving the token in a cookie. 

Is it anyhow possible to tell apollo-client to request withCredentials? Or is it doing this by default and the problem lies anywhere else?

The following seems not to work?
```
networkInterface.use([{
    applyMiddleware(req, next) {
        req.options["withCredentials"] = true;
        console.log(req.options);
        next();
    }
}]);
```

**Comment by stubailo** [comment]
Pass it as an option to "createNetworkInterface" next to "uri".

**Comment by manuelfink** [comment]
Just realized console.log(req.options); shows that withCredentials is already set to true without applying it in middleware.

Passing it in createNetworkInferface / createBatchingNetworkInterface  as withCredentials: true results in an typescript error. credentials also seems not work:

```
const networkInterface = createBatchingNetworkInterface({
  uri: '/graphql',
  withCredentials: true,
  batchInterval: 10
});
```

Argument of type '{ uri: '/graphql',  withCredentials: true,  batchInterval: 10 }' ist not assignable to parameter of type 'BatchingNetworkInterfaceOptions'.

**Comment by stubailo** [comment]
My mistake - was on mobile: https://github.com/apollographql/apollo-client/blob/9e8662ca0684bd04541d2e9b5bc896c9ecb3cba5/src/transport/batchedNetworkInterface.ts#L221

```ts
export interface BatchingNetworkInterfaceOptions {
  uri: string;
  batchInterval: number;
  opts?: RequestInit;
}
```

Looks like it would be:

```ts
const networkInterface = createBatchingNetworkInterface({
  uri: '/graphql',
  opts: { /* fetch options */ },
  batchInterval: 10
});
```

So, looking up at https://developers.google.com/web/updates/2015/03/introduction-to-fetch#sending_credentials_with_a_fetch_request

Looks like it's documented here btw: http://dev.apollodata.com/core/network.html#createNetworkInterface

```js
const networkInterface = createBatchingNetworkInterface({ 
  uri: 'https://example.com/graphql',
  opts: {
    // Additional fetch options like `credentials` or `headers`
    credentials: 'same-origin',
  }
});
```

**Comment by abumalick** [comment]
Now it is in Apollo-link-http:
https://www.apollographql.com/docs/link/links/http/#options
