### ISSUE TITLE
fetchMoreResult shouldn't have data property

### ISSUE THREAD

**Issue by helfer** [apollographql/apollo-client#1384]
In the  `updateQueries` function of `fetchMore`, `fetchMoreResults` has a `data` property, but `previousResult` doesn't. We should hoist the properties in `fetchMoreResults`.

**Comment by nandito** [comment]
I'm not sure if I understand it properly, but it seems to me that the `updateQuery`'s `previousResult` is basically the same as `fetchMoreResult.data`. The additional elements in the `fetchMoreResult` object are the `loading` and the `networkStatus`.

Here is an example from an implemented pagination:
```js
const paginationOption = {
  options: { /* ... */ },
  props({ data }) {
    return {
      data,
      changePage(page) {
        return data.fetchMore({
          variables: { /* ... */ },
          updateQuery: (previousResult, { fetchMoreResult }) => {
            console.log('previousResult: ', previousResult)
            console.log('fetchMoreResult: ', fetchMoreResult)
            if (fetchMoreResult.data) {
              /* ... */
              return fetchMoreResult.data
            }
            else {
              return previousResult
            }
          }
        })
      }
    }
  }
}
```

This shows the following log:

previousResult:
```
{
  user_list: {
    __typeName: "UserList",
    users: Array[100],
    metadata: Object
  }
}
```

fetchMoreResult:
```
{
  data: {
    user_list: {
      __typeName: "UserList",
      users: Array[100],
      metadata: Object
    }
  },
  loading: false,
  networkStatus: 7
}
```

So the goal here is to wrap the `previousResult` object's current content with `data`?

**Comment by helfer** [comment]
> So the goal here is to wrap the previousResult object's current content with data?

@nandito Yes, I think that would be best.

If you (or someone else) want to make a quick PR, it would be very much appreciated! :)
