### ISSUE TITLE
`fetchDataFromTree` can fail if using apollo afterware to clone response stream on large responses

### ISSUE THREAD

**Issue by thebigredgeek** [apollographql/apollo-client#1385]
From https://github.com/bitinn/node-fetch/issues/151

This isn't a bug with apollo per se, but it is probably something worth at least mentioning in the docs as a combination of large responses, gzip, and `response.clone` in afterware seems to cause a really difficult-to-track-down bug if the graphql response size is larger than a platform-specific limit (NodeJS's default buffer size is smaller than Chrome's default buffer size, for example) and the response stream is cloned.

The API's direction with afterware will likely steer users into encountering this bug.  I spent 8+ hours trying to figure out why `fetchDataFromTree` was hanging only to discover that `node-fetch` (which you are probably using for SSR via `isomorphic-fetch` polyfill) can apply backpressure for large requests where the response is cloned, causing the response stream to pause and ultimately causing the promise returned by fetch to never resolve or reject... locking `getDataFromTree` in a limbo state and render into a waiting state until the SSR request for the page times out.

I can see this becoming a huge headache for users who are using afterware with  either queries with large responses or batched queries that add up to single large response.  

I was forced to switch to afterware about a week ago after I noticed that `APOLLO_MUTATION_ERROR` was no longer firing in redux when mutations sent back error objects after upgrading from apollo-client `0.6.x`. 

Any ideas on how we can address this with either docs or some sort of hack atop the coupling with `whatwg-fetch`?

**Comment by thebigredgeek** [comment]
Here is the afterware:

```
import { trace } from 'io/logger';
import { add as addAlert } from 'state/redux/actions/app/alerts';

export default ({ store }) => [{ applyAfterware: ({ response }, next) => {
  if (!__CLIENT__) return next();

  const clonedResponse = response.clone();

  clonedResponse.json().then(json => {
    const { errors = [] } = json;

    errors.forEach((error) => {
      store.dispatch(addAlert({
        text: error.message
      }));
      trace(error);
    });
    next();
  });
}}];
```

I suppose it could be that either `response.clone().json()` is not resolving, or that the original response that apollo-client hooks into is not resolving.

**Comment by helfer** [comment]
Thanks for the careful writeup @thebigredgeek. I don't think there's anything we can do from the Apollo Client side, but it's useful to have this documented in the issues! 👍

**Comment by thebigredgeek** [comment]
@helfer couldn't we parse the response stream before passing it into afterware?  That way there is no need to clone the response etc
