### ISSUE TITLE
How to rollback optimisticResponse after mutation return a rejected promise

### ISSUE THREAD

**Issue by cncolder** [apollographql/apollo-client#1386]
**Intended outcome:**

Drop optimistic response if error.

**Actual outcome:**

Apollo only dispatch `APOLLO_MUTATION_INIT` but not `APOLLO_MUTATION_RESULT` and leave optimistic response there.

**How to reproduce the issue:**

```js
// In GraphQL server resolvers. Simple throw an error.
check.assert.like(ctx.state.user, { id: '' }, 'unauthorized')
  Mutation: {
    async addPost (_, { title, content }, ctx) {
      if (!ctx.state.user) throw new Error('unauthorized')

      const user = await User.get(ctx.state.user.id)

      return user.submitPost(title, content)
    }
  }
```

**Comment by cncolder** [comment]
After half day to search in codes. I have a question about `QueryManager.mutate`

[https://github.com/apollographql/apollo-client/blob/v1.0.0-rc.0/src/core/QueryManager.ts#L279](https://github.com/apollographql/apollo-client/blob/v1.0.0-rc.0/src/core/QueryManager.ts#L279)

```js
    return new Promise((resolve, reject) => {
      this.networkInterface.query(request)
        .then((result) => {
          if (result.errors) {
            reject(new ApolloError({ // <-- This reject outside Promise. But who catch this ApolloError?
              graphQLErrors: result.errors,
            }));
            return;
          }

          this.store.dispatch({
            type: 'APOLLO_MUTATION_RESULT',
            /* ... */
          });

          // If there was an error in our reducers, reject this promise!
          const { reducerError } = this.getApolloState();
          if (reducerError) {
            reject(reducerError);  // <-- This reject same as above.
            return;
          }

          /* ... */

          resolve(this.transformResult(<ApolloQueryResult<T>>result));
        })
        .catch((err) => { // <-- This catch networkInterface.query error. So we reject a networkError below.
          this.store.dispatch({
            type: 'APOLLO_MUTATION_ERROR', // <-- I find dispatch APOLLO_MUTATION_ERROR is the only way to trigger optimistic rollback.
            error: err,
            mutationId,
          });

          delete this.queryDocuments[mutationId];
          reject(new ApolloError({
            networkError: err,
          }));
        });
    }); // <-- Do we need a catch here? The error is log to console.
```

**Comment by helfer** [comment]
@cncolder The code looks correct to me. Are you sure `APOLLO_MUTATION_ERROR` is not dispatched?

**Comment by cncolder** [comment]
APOLLO_MUTATION_ERROR only dispatched when network error (fetch error). If server throw a business logic error. It's not dispatch.

**Comment by cncolder** [comment]
In `networkInterface.query`. There are two condition to reject.

1. `!httpResponse.ok`
2. `!payload.hasOwnProperty('data') && !payload.hasOwnProperty('errors')`

I throw TypeError in `graphql-server-koa` resolvers. But the server still return

```js
// Status Code: 200
{"data":{"myMutate":null},"errors":[{"message":"unauthorized","locations":[{"line":2,"column":3}],"path":["myMutate"]}]}
```

So now If I must find a way to return a 4XX to trigger APOLLO_MUTATION_ERROR action.

**Comment by helfer** [comment]
@cncolder oh, I think I see what you're saying. The code above rejects the promise directly without going through the catch block that dispatches a MUTATION_ERROR, right?

Could you make a PR to fix this? We would really appreciate it! You can just dispatch the action before the promise is rejected, so it shouldn't be complicated.

**Comment by cncolder** [comment]
@helfer Ok fork now. But I still confused. I'm not sure if dispatch APOLLO_MUTATION_ERROR before `reducerError`

**Comment by helfer** [comment]
Try dispatching the action where you wrote this: `/** I'm not sure why not rollback optimistic here. Is this the role of specs? Or forgot? **/`

**Comment by thebigredgeek** [comment]
I can also confirm that `APOLLO_MUTATION_ERROR` is no longer dispatched.  This was why I switched to afterware for error alerting and how I discovered [this](https://github.com/apollographql/apollo-client/issues/1389)

**Comment by helfer** [comment]
Should be fixed in `master` now.
