### ISSUE TITLE
QueryObservable `currentResult` behavior seems to be buggy

### ISSUE THREAD

**Issue by thebigredgeek** [apollographql/apollo-client#1389]
QueryObservable returned from `client.subscribe` seems to assign the immediate query result (from `APOLLO_QUERY_RESULT` to `lastResult` and returns an empty object from `currentResult` immediately following.  

This seems to break [react-apollo here](https://github.com/apollographql/react-apollo/blob/master/src/graphql.tsx#L533).  

This bug appears to express itself only in areas of our app where we are rendering a list server-side and then clicking a link on that list to navigate to a "more details" view for the list item.  

*  If I set `ssr` to false for the list view, the bug does not occur.  
*  If the user navigates to the list and the data is fetched from the client, this bug doesn't present itself.  
*  If I click the back button from the details view and select the same, or a different, list item the bug doesn't present itself a second time without a browser refresh.

It seems to be some sort of bug with state somewhere in either apollo-client or react-apollo.  The bug causes the details view to remain in "loading state" forever because the query result is never passed into the view via `@graphql#props` callback even when `loading` becomes false and the query result has been digested into redux. 

#### Screenshots 

*Query result during breakpoints*
![screen shot 2017-03-09 at 10 01 00 am](https://cloud.githubusercontent.com/assets/2799276/23764086/1ad97ebc-04b1-11e7-8cb9-78f4203311f3.png)

*`QueryObservable#lastResult` contains the query result and `QueryResult#currentResult()` returns an empty object*
![screen shot 2017-03-09 at 10 14 32 am](https://cloud.githubusercontent.com/assets/2799276/23764122/360494f6-04b1-11e7-83c6-c5d336ce2ee6.png)

*`props` callback in `@graphql` does not contain `user`*
![screen shot 2017-03-09 at 10 18 14 am](https://cloud.githubusercontent.com/assets/2799276/23764251/bcf92ca6-04b1-11e7-920e-e2727526b858.png)
![screen shot 2017-03-09 at 10 16 41 am](https://cloud.githubusercontent.com/assets/2799276/23764219/a11f2cec-04b1-11e7-9b4d-08dced8dc288.png)

**Comment by alfonsoperez** [comment]
I am seeing the same behaviour: https://gist.github.com/alfonsoperez/2b44155bf5da6834e739e441a212a45e

**Comment by thebigredgeek** [comment]
Will try to create a test case for this.

**Comment by calebmer** [comment]
If you could create a reproduction using [`react-apollo-error-template`](https://github.com/apollographql/react-apollo-error-template) it would go a long way in helping us debug this issue! Thank you so much for reporting 😊

**Comment by thebigredgeek** [comment]
@calebmer I plan to implement an integration test in `react-apollo`, which is where this should be moved once we have verified it to be the problem.  I just haven't had time yet.  Already paired with @helfer on it for a bit last friday.  Sorry!

**Comment by derek-duncan** [comment]
I've been trying to debug this as well. Any updates on a solution or ways we can help out?

**Comment by stubailo** [comment]
> ways we can help out

I think we still don't have a reliable reproduction, which would make it much easier to work on a fix.

**Comment by thebigredgeek** [comment]
FWIW, we discovered today that running the graphql HoC twice on a single component with two different queries caused this to happen.  By merging both queries together, the bug went away.  I've been planning on implementing a test case to reproduce, and will hopefully have time to do so pater this week

**Comment by derek-duncan** [comment]
Some more debugging... FWIW when a `refetchQueries: myQuery` is called for an unmounted `graphql(myQuery)`, this bug seems to occur when it is mounted again. Trying to repo in the error template repo...

**Comment by thebigredgeek** [comment]
@derek-duncan @alfonsoperez could either of you find time to try to reproduce this with an integration test in `react-apollo`?  I was planning on doing this like a week ago but I've been so slammed at work that I haven't had time.  We should try to get this ironed out before 1.0.

**Comment by helfer** [comment]
A reliable reproduction with https://github.com/apollographql/react-apollo-error-template would be great! Once we have that, it shouldn't be too hard to pinpoint the issue.

**Comment by thebigredgeek** [comment]
@helfer could I just add you as read-only to our app?  I have 3 or 4 examples :D

**Comment by derek-duncan** [comment]
@helfer I've been working on reproducing in `react-apollo-error-template` for a bit and having a difficult time pinpointing. I can continue to debug, but @thebigredgeek's repo might be the clearest way for you to see the issue right now.

**Comment by helfer** [comment]
@thebigredgeek is it easy to run? The main reason we have an error template is because it's relatively easy to run and thus reproduce the error without a lot of unrelated code getting in the way.

**Comment by thebigredgeek** [comment]
Yeah it's easy to run.  You just need docker and direnv.  With those, you can pull down prod data spin up then entire project with 3 or 4 commands

**Comment by thebigredgeek** [comment]
Or I can just come over again haha

**Comment by alfonsoperez** [comment]
I can try to do it this week, but I suspect my issue was related to what @derek-duncan said. Been pretty tough on deadlines too myself :D
