### ISSUE TITLE
Querying transient (and offline) items (via cache resolution/custom resolvers).

### ISSUE THREAD

**Issue by richburdon** [apollographql/apollo-client#1403]
I would like to query and mutate certain types that are transient and only exist on the client (and later for offline operation). I thought customResolvers would be a good place to start, but that looks like a dead-end...

1). According to the docs Apollo can't tell that Item X was already retrieved, but given that ID is resolved by dataIdFromObject and __typename is included in all results via addTypename, then isn't that a solved problem without custom resolvers? I.e., any fields in query that are of type ID could be resolved.

We know that the data is most likely already in the client cache, but because it’s requested with a different query, Apollo Client doesn’t know that. In order to tell Apollo Client where to look for the data, we can define custom resolvers:
Perhaps, my use case is too narrow for this to be generally applied?

2). For my purpose above, I would like to extend HTTPNetworkInterface but how can I reference this from another node module? I could monkey-patch createNetworkInterface but that doesn't feel right. Alternatively, I could try to work with middleware to extract and omit queries of my type? What do you think?

**Comment by helfer** [comment]
@richburdon can you give a more concrete description of your use-case? What's the app /view you're trying to build?

**Comment by richburdon** [comment]
I have several use cases:

1). I have a Chrome Extension where the Content Script needs to proxy GQL requests to a Background Page (same story for service workers). So in this case, I've created a simple ChromeNetworkInterface that relays messages via chrome.runtime.connect ports. The background page implements the regular HttpNetworkInterface. 

This all works, but it would be cleaner if I could extend NetworkInterface (i.e., if that class was exported).

2). I have an app that works offline. Basically all queries and mutations can be resolved using cross-platform code, so I want to wire-up the network interface to pass through a local query processor that can resolve queries before passing them on to the server.

I have this working also by monkey-patching the regular HttpNetworkInterface returned via createNetworkInterface.

NOTE: it seems that exceptions that occur while processing NetworkInterface.query are swallowed (nothing in the console and the query just hangs).

**Comment by calebmer** [comment]
@richburdon make sure to check out the new read and write APIs! They should allow you to do what you want: https://dev-blog.apollodata.com/apollo-clients-new-imperative-store-api-6cb69318a1e3#.n14q2wv4m

We also export `HTTPFetchNetworkInterface` so you can import that into your application from `apollo-client` and extend it.
