### ISSUE TITLE
only last reducerError get logged, previous reducerError been overrided. 

### ISSUE THREAD

**Issue by xiaohanzhang** [apollographql/apollo-client#1404]
Is it possbile to keep a reducerError array or simply log all error if debug is true?
Currently previous reducerError will been overridden by later reducerError, and only the last error got logged [soure code](https://github.com/apollographql/apollo-client/blob/master/src/store.ts#L122)

**How to reproduce the issue:**
I have an error during APOLLO_MUTATION_INIT: `TypeError: Cannot read property '_id' of undefined`
But it been overridden by another error from APOLLO_MUTATION_RESULT:  `TypeError: Cannot read property 'variables' of undefined`

**Intended outcome:**
It should display both Error, or stop at first error.

**Actual outcome:**
Only the last error `TypeError: Cannot read property 'variables' of undefined` got displayed, which is a very confusing.

**Comment by BlooJeans** [comment]
This might be of interest to you - https://github.com/apollographql/apollo-client/pull/1383

**Comment by xiaohanzhang** [comment]
@BlooJeans Thanks, I believe your PR will solve my problems. I will close this issue once your PR got merged

**Comment by calebmer** [comment]
It looks like https://github.com/apollographql/apollo-client/pull/1383 is ready to merge. Thanks for your report @xiaohanzhang 👍
