### ISSUE TITLE
How to pass variables to query when using in Root level component

### ISSUE THREAD

**Issue by yash0087** [apollographql/apollo-client#1405]
Hi, I have a scenario where I am using 'graphql' from 'react-apollo' and want to make a query which has dynamic fields in it. In my component which is the Root/Main/Entry component, how can i pass the variables to the query if it needs to be decided based on component's state?

```javascript
class Root extends Component {
    componentDidMount() {
       //fetchs data and get a field called 'ID' which is required for the graphql query.
       // store the ID in state.
    }
}

export default graphql(QUERY_WITH_VARIABLES, {})(Root)
```

So how do I pass the variable in this case?

**Comment by helfer** [comment]
@yash0087 this is a question that's specific to react-apollo, so it's better to open an issue on that repository. Thanks!
