### ISSUE TITLE
Errors from polling query escape to the browser console

### ISSUE THREAD

**Issue by csillag** [apollographql/apollo-client#1406]
**Intended outcome:**

I have a query, for which the resolver throws an error.
The query is configured to be executed in every few seconds, using `pollInterval`.

``` JS
apollo.query({
    query: operations.getItem.doc, // This is the GraphQL query
    variables: { itemId: "xxx" },
    pollInterval: 10000,
}).then(
    result => console.log("Item loaded", result),
    error => console.log("Failed to load item", error.message),
)
```

I would expect any errors received from the server to be intercepted by the function I pass in to the `then` call.

**Actual outcome:**

When the query is first executed, the error is correctly handled to the error handler.
However, all subsequent executions (triggered by the polling) drop a stack trace on the console, saying:

```
Uncaught (in promise) Error: GraphQL error: <Message coming from server>
    at new ApolloError (modules.js?hash=87d421f…:214661)
    at modules.js?hash=87d421f…:215773
    at meteor.js?hash=27829e9…:1105
```

The console is littered by these messages. How do I catch these?

   * * *

This might be related to #1334, but no SSR is involved in this case.

**Comment by calebmer** [comment]
The first problem here is on our side. We shouldn’t allow `pollInterval` in `query` 😊. `query` returns a promise so you will only ever get the first rejection. I opened a PR to make sure people can’t use `pollInterval` with `query`: https://github.com/apollographql/apollo-client/pull/1433

Well then, what should you use? You should use `watchQuery` instead. Your above example would then become:

```js
apollo.watchQuery({
    query: operations.getItem.doc, // This is the GraphQL query
    variables: { itemId: "xxx" },
    pollInterval: 10000,
}).subscribe({
    next: result => console.log("Item loaded", result),
    error: error => console.log("Failed to load item", error.message),
});
```

This will allow you to get all of the results and errors as they come in 😊
