### ISSUE TITLE
Improve README description of project

### ISSUE THREAD

**Issue by Poincare** [apollographql/apollo-client#1407]
Right now, the README.md describes Apollo Client as:

> The apollo-client package is the core of the Apollo frontend toolchain. It allows you to interact with your GraphQL data in smart and reactive ways.

I'm not sure if we what we have is really a "toolchain" (i.e. something like `binutils`). More importantly, I don't think the above sentences communicate what exactly Apollo Client is unless you have a pretty clear idea of the GraphQL ecosystem already. 

Maybe we could have something like this instead:

> Apollo Client is a full-featured, spec-compliant GraphQL caching client with bindings for React, Angular, etc. At its core, It allows you to build UIs that reactively fetch data from a GraphQL backend.

This serves two goals: 
1. The first sentence gives you an idea of the scope and focus of Apollo Client 
2. The second sentence gives you a decent idea of what Apollo Client does even if you're very new to GraphQL

**Comment by helfer** [comment]
@Poincare I agree 100%. I think I made a comment about this in the PR, but I must have missed it the second time. Can you make a quick PR and merge it? :)

**Comment by Poincare** [comment]
See above :)
