### ISSUE TITLE
ReduxDataProxy isn't forwarding ApolloReducerConfig

### ISSUE THREAD

**Issue by ksmth** [apollographql/apollo-client#1412]
**Intended outcome:**
When calling `client.readQuery()`, I expect it to use `customResolvers` provided when initializing the client.

**Actual outcome:**
It's not using the `customResolvers`

**How to reproduce the issue:**
Follow http://dev.apollodata.com/react/cache-updates.html#cacheRedirect and try reading from the cache with `client.readQuery()`

**Comment by helfer** [comment]
@ksmth It seems likely that we simply overlooked this. Would you like to make a quick PR to fix this?
