### ISSUE TITLE
Ability to create custom cache-keys

### ISSUE THREAD

**Issue by chriscartlidge** [apollographql/apollo-client#1420]
Hi,

Our GraphQL server currently uses the accept-language header to determine what locale the content should be returned in.

We pass the header down by using the applyMiddleware function like so:
https://github.com/opentable/oc-graphql-client/blob/master/index.js#L29

However, it seems that the cache key does not take the header into consideration e.g.

````js
//accept-language: en-GB
const result = client.query({restaurant(id: 4) { name } });
```` 

````js
//accept-language: ja-JP
const result = client.query({restaurant(id: 4) { name } });
```` 

The second call returns the result of the first, even though the content is different (English vs Japanese). We can get around this by doing a ````forceFetch=true```` but we forfeit the advantage of the cache.

If possible a strategy of providing a cache-key function like what the dataloader would be a great addition.

**Comment by thebigredgeek** [comment]
@chriscartlidge Apollo caches queries by combining variables with the query string into a sort of hash.  Combining headers into this hash is not likely something desirable from an API design standpoint.  Is there any way you could include the language as a query variable as well as in the header?  If so, this should resolve your problem, as apollo will attempt to query again because the language variable has changed.  You could even make this variable a no-op and simply discard it on the server.

**Comment by stubailo** [comment]
@chriscartlidge is it important for the same page to be able to display multiple locales at once, or is switching locales a global operation? If it's global, I think the best approach is probably to reset the whole store when locales are switched.

Like @thebigredgeek mentioned, Apollo is currently based on the premise that the query and variables contain enough information to figure out what data we're going to get - you can read more about that here: https://dev-blog.apollodata.com/the-concepts-of-graphql-bc68bd819be3#.rnwl3sjln

**Comment by calebmer** [comment]
An alternative to resetting the store would be to use multiple client instances.

**Comment by stubailo** [comment]
@chriscartlidge any updates - would one of the solutions proposed work for you?

**Comment by chriscartlidge** [comment]
@stubailo Apologies I've been I'll the past few days. I'll update you with our use case soon.

**Comment by chriscartlidge** [comment]
@stubailo Our microsites which server side render contain a long-lived instance of the apollo-client, so resetting the store is probably not the option for us or using multiple client instances. 

I think the simplest approach is probably to pass in the language as a parameter like @thebigredgeek  says and just discharge it in the backend (still read from the header though). 

Cheers guys 👍

**Comment by helfer** [comment]
Closing this since the question seems to have been answered 🙂
