### ISSUE TITLE
cache always missed when querying inline fragments of concrete types

### ISSUE THREAD

**Issue by borisnieuwenhuis** [apollographql/apollo-client#1421]
Hi,
it looks like the apollo client always returns that there is a missing field when using queries on an interface and then specifying the fields of the concrete type.
For instance, running a query like:

extras {
       __typename
       id
       name
       subTitle
       scope
       mandatory
       price {
         __typename
         amount
       }
       ... on OptionRange {
         rangeMin
         rangeMax
       }
       ... on OptionChoiceList {
         choices {
           id
           name
           price {
             __typename
             amount
           }
         }
       }
     }

will always return a cache miss because the field choices is missing on the data it thinks, even if the result data contained an OptionRange only.
context.hasMissingField = true will always be hit there.
This results in duplicate queries of course, cause it will refetch.

**Comment by borisnieuwenhuis** [comment]
sorry for the formatting I will make it better soon

**Comment by borisnieuwenhuis** [comment]
hmm, might relate to https://github.com/apollographql/apollo-client/issues/1363

**Comment by stubailo** [comment]
I think this is more related to: https://github.com/apollographql/apollo-client/issues/1337

This is something we're going to solve before the 1.0 release, and there are ideas about the solution there if you have time to contribute the feature!

(Going to close this issue since I'm pretty sure it's a duplicate, let me know if you disagree)

**Comment by borisnieuwenhuis** [comment]
Yes you are right this is definitely a duplicate of that one.
I will dive a bit deeper see if I can get somewhere with it, but I am just starting with graphql so it will take some time to sink in probably.
