### ISSUE TITLE
BREAKING: Parse response before passing it to afterware

### ISSUE THREAD

**Issue by thebigredgeek** [apollographql/apollo-client#1424]
Making this change should (mostly) resolve https://github.com/apollographql/apollo-client/issues/1385 by ensuring that the response is parsed before it is ever passed into afterware.  This removes the necessity of cloning the response stream and, thus, the reduces the probability that the above bug will present itself.  It also provides a simpler API for writing afterware, as most afterware cases can now be handled without writing async code to clone and parse the response stream.

**Comment by thebigredgeek** [comment]
@helfer per slack

**Comment by thebigredgeek** [comment]
https://github.com/apollographql/core-docs/pull/261

**Comment by helfer** [comment]
Let's just track this in #1425, there's no need to have a separate issue open.

**Comment by stubailo** [comment]
Here's the first part of the new network interface!

https://github.com/apollographql/apollo-fetch

It does indeed provide parsed results to afterware, maybe someone can give it a try.
