### ISSUE TITLE
Dummy Network Interface fails on refetch.

### ISSUE THREAD

**Issue by dfee** [apollographql/apollo-client#1426]
**Intended outcome:**
`refetch` runs without error when using a custom networkInterface on client

**Actual outcome:**
`refetch` returns:
```
Uncaught (in promise) Error
    at new ApolloError (apollo.umd.js:1803)
    at apollo.umd.js:2922
```

**How to reproduce the issue:**
Use this as your client's networkInterface:
```
function DummyNetworkInterface() {
    this.query = (request) => {
        return new Promise((resolve, reject) => {
          resolve({data: {hello: 'world'}, errors: []});
        });
    };
}
```
for query:
```
const MyQuery = gql`query demoQuery { hello }`;
```

**Comment by dfee** [comment]
I should note, I'm using this for a WebsocketNetworkInterface I have implemented. Upon refetch, the server's data is returning updated data, but I'm still getting the error.

**Comment by stubailo** [comment]
Weird, is that the only stack trace you get? Would it be possible for you to send a PR with a failing test using the reproduction above? At first glance it doesn't seem like this should fail.

**Comment by dfee** [comment]
That is the only stack trace I'm receiving. I'd like to send a PR, but unfortunately I'm not sure where to begin on writing a test to demonstrate what _should_ happen.

**Comment by helfer** [comment]
@dfee I'm not sure if that's the issue, but your dummy response is not spec-compliant, because it contains an `errors` field with an empty array. Please see here for details: https://facebook.github.io/graphql/#sec-Errors

Feel free to reopen if removing `errors` doesn't solve the issue.

**Comment by dfee** [comment]
@helfer thanks, that solved the problem!

I didn't dig into the spec when implementing that method. Do you think that should be documented [here](http://dev.apollodata.com/core/network.html#GraphQLResult)?
