### ISSUE TITLE
IMPROVEMENT: Default selector for `dataIdFromObject`

### ISSUE THREAD

**Issue by thebigredgeek** [apollographql/apollo-client#1427]
Per my conversation with @stubailo on slack, I think it would be a good idea to default `dataIdFromObject` to a function that selects the two most common primary key fields: `id`, falling back to `_id`.  This would drastically reduce the amount of configuration required in most use cases, which would mean one less thing to learn to be productive with `apollo-client`.

**Comment by thebigredgeek** [comment]
https://github.com/apollographql/core-docs/pull/262

**Comment by stubailo** [comment]
I know I suggested opening an issue about it, but I actually think the PR is a good enough place for discussion since this is a relatively small change!
