### ISSUE TITLE
Possible SSR issue

### ISSUE THREAD

**Issue by stubailo** [apollographql/apollo-client#1429]
Sorry for poorly formatted issue, just something to look at: https://github.com/apollographql/GitHunt-React/issues/218

**Comment by helfer** [comment]
Basically it's this:
> client.store.getState().apollo.data is empty after updating apollo-client to 1.0.0-rc.1 or 1.0.0-rc.2
with 1.0.0-rc.0 works fine

This may be related to the change from `reduxRootKey` to `reduxRootSelector`, but GitHunt doesn't seem to be using that.

Can anyone reproduce this issue?

**Comment by calebmer** [comment]
I’m debugging right now. The first issue is that GitHunt uses `forceFetch`.

**Comment by calebmer** [comment]
This PR upgrades GitHunt to 1.0.0 and fixes SSR: https://github.com/apollographql/GitHunt-React/pull/220
