### ISSUE TITLE
Decouple GraphQL store with a generic API

### ISSUE THREAD

**Issue by thebigredgeek** [apollographql/apollo-client#1432]
I think it might be kinda cool to provide some sort of interface similarly to how we do it with `NetworkInterface`.

Redux could be the “default” but excludable, and users could plug in mobx or reflux or whatever.

If the interface implements async functions, the store could even be run in something like redis (for server side caching, for instance, for inter-service RPC) or a web worker to reduce the number of state change cycles on the main thread.

I think it might be worth exploring.  Doesn’t seem like it would add much cost other than initial dev time to establish an interface.  After that it would likely result in better code even within the internal lib, since there would be a well-enforced contract with how apollo-client couples itself to the implemented caching mechanism.

Wondering what other people think about this idea @stubailo @helfer

**Comment by thebigredgeek** [comment]
Can we get discussion going on this?  I'd love to drill down to design details once everyone is on board with it.

**Comment by helfer** [comment]
@thebigredgeek We've been planning this for a while and we think the interface should be quite similar to how the data proxy works.

Making the store reading asynchronous and Redux optional is going to be a pretty large breaking change. Our priority at the moment is 1.0, so this will have to wait until after that.

**Comment by thinkpadder1** [comment]
@helfer I see that 1.1.1 is out. Is this RFC still being considered? Thank you.

**Comment by smolinari** [comment]
I'm also interested in this!

Scott

**Comment by helfer** [comment]
Yes, this is still on our radar. We're also trying to make sure it's aligned with iOS and Android, so it's probably going to take another week or two until we put a more complete draft out there. Our latest blog post contains a very high-level overview though.

**Comment by emcpadden** [comment]
Looking forward to an integration with ngRX. I am using ngRX already and really love it, it feels like the right redux-style store for Angular apps.  I am just starting to look at graphQL/apollo and would love to have a clean integration between the two.  It would be a great bridge for adoption for Angular users that want to stay close to Angular projects like ngRX.

**Comment by jamiter** [comment]
It would also help Meteor developers move over if minimongo could be used as the store. This way the rest of stack (like Tracker and Blaze) will keep their reactivity like before!

And personally I would like to experiment with MobX as well.

**Comment by petercn** [comment]
@helfer Any recent updates on this?

**Comment by sammkj** [comment]
I recently made a comment [on another issue](https://github.com/apollographql/apollo-client/issues/128#issuecomment-310089445) regarding Apollo and web worker implementation. Please feel free to give feedback on that

**Comment by stubailo** [comment]
@shadaj can you provide a longer update on what you're working on?

The first few PRs in this direction are #1845 and https://github.com/apollographql/apollo-client/pull/1846 and https://github.com/apollographql/apollo-client/pull/1859

**Comment by shadaj** [comment]
Sure, I'm going to be working on implementing a new store API that will make it possible to plug in different backing store implementations into Apollo. The first step of this is to extract out the Redux implementation of the Apollo store into a separate module, where we can place it under a more general API. The new Store API will make it possible to provide custom implementations of Apollo stores with custom caching logic, and we are also exploring the possibility of simply plugging in a key-value backing store and layering existing Apollo store logic on top of that.

Right now, I'm working on migrating some state (such as query and mutation status) from Redux into their own state trackers, which will make it easier later on to extract out the entire Apollo store implementation into a separate module.

**Comment by avatsaev** [comment]
I wanted to use apollo in our newest angular project, but not being able to use it with ngrx/store, ngrx/effects is kind of a deal breaker.

**Comment by stubailo** [comment]
First steps here: #1921

**Comment by amitport** [comment]
(https://github.com/apollographql/apollo-client/pull/1921 is merged)

**Comment by avatsaev** [comment]
Will there of an official doc with angular ngrx integration or maybe update the current tutorial to use ngrx by default instead of redux?

**Comment by cport1** [comment]
You can use ngrx alongside apollo-client just fine .. there are a dozen other conversations about turning off the cache .. there's also apollo fetch and apollo link

https://github.com/apollographql/apollo-fetch

**Comment by val-samonte** [comment]
Sorry for the annoyance, but is this something that will be out on the next major release?

**Comment by hccampos** [comment]
Any news on this? Marked as stale but I can't find more info regarding a solution/etc.

**Comment by stubailo** [comment]
Yep, this is part of the Apollo Client 2.0 work!

Here's the cache API to implement: https://github.com/apollographql/apollo-client/blob/14a7bc4ff7e87c3f99844a79538029939c9cd0cf/packages/apollo-cache/src/cache.ts#L8

Here are two implementations:

1. In memory cache similar to Apollo Client 1.0: https://github.com/apollographql/apollo-client/tree/14a7bc4ff7e87c3f99844a79538029939c9cd0cf/packages/apollo-cache-inmemory
2. Hermes, written by some people from Convoy: https://github.com/convoyinc/apollo-cache-hermes

It's still early days but AC 2.0 just entered beta, so we're going to be working on a lot of documentation for all of this stuff.

You can read more about it in this post as well: https://dev-blog.apollodata.com/whats-coming-in-apollo-client-2-0-bcd8ea64acbd

**Comment by tlvenn** [comment]
Is there any collaboration with Relay team regarding the cache API ? At some point if it becomes pluggable in Relay Modern as well, it would be neat if implementations could work in both libs.

Just pondering...

**Comment by nevir** [comment]
Hermes is built in a way that it could be pretty easily adapted for other clients - but, honestly, given how tightly coupled Relay's API is with its cache, it would be unlikely that Relay could support alternate cache implementations

**Comment by stubailo** [comment]
Yeah it could be a cool hackathon project to try to jam together the Relay cache with Apollo's API/networking. Although I hope that this new feature enables people to innovate quickly on new cache implementations, so we have enough options to choose from even without that!

**Comment by changalberto** [comment]
Not stale you salty bot! =)

**Comment by jbaxleyiii** [comment]
This is done the 2.0 🎉

**Comment by fxck** [comment]
Are there any examples?

**Comment by BhaskaranR** [comment]
@fxck i was able to make it work with this ngrx branch, not sure why this is not released yet.
https://github.com/apollographql/apollo-angular/tree/1.0-ngrx

**Comment by Timopheym** [comment]
And what about Mobx store? Is there some example too? Pleas!

**Comment by jeremyputeaux** [comment]
@kamilkisiela just released https://github.com/apollographql/apollo-angular/tree/1.0-ngrx/packages/apollo-angular-cache-ngrx

**Comment by simonpeters** [comment]
@jeremyputeaux cool! nice work.

How would you combine state data with an apollo query? With a filter for example.
