### ISSUE TITLE
Wrongly compiled files in the package on npm (RC.3)

### ISSUE THREAD

**Issue by kamilkisiela** [apollographql/apollo-client#1440]
@helfer @stubailo  straight to the point.

RC.2 and previous releases:
https://unpkg.com/apollo-client@1.0.0-rc.2/transport/networkInterface.js

RC.3:
https://unpkg.com/apollo-client@1.0.0-rc.3/transport/networkInterface.js

I guess it was published [incorrectly](https://unpkg.com/apollo-client@1.0.0-rc.3/lib/src/transport/networkInterface.js) or there's something I don't know that has changed?

It breaks apollo-test-utils and anything that uses inner modules.

**Comment by helfer** [comment]
crap, I think I ran `npm publish` :/. Thanks for reporting, will be fixed in ~5 mins.

**Comment by helfer** [comment]
I'm going to write a little script on Monday to make sure this never happens again. 😕
