### ISSUE TITLE
Inconsistent "batched" and "batching" naming

### ISSUE THREAD

**Issue by jaydenseric** [apollographql/apollo-client#1448]
Bit of a nitpick, but shouldn't `createBatchingNetworkInterface` be called `createBatchedNetworkInterface`, since it returns a new `HTTPBatchedNetworkInterface`?

Most of the filenames, functions and classes about batching go by "batched", with the exception of `BatchingNetworkInterfaceOptions`, which should also probably be renamed `BatchedNetworkInterfaceOptions`.

Ideally this would happen prior to v1.0.

**Comment by helfer** [comment]
@jaydenseric Good point, I think it would be reasonable to make that change. If you make a PR, we might be able to include it in `1.0.0`.

**Comment by stubailo** [comment]
Ping, this would be a good change to have!

**Comment by jaydenseric** [comment]
Or maybe even just use `Batch` everywhere: `createBatchNetworkInterface`.

**Comment by stubailo** [comment]
Sounds good to me!

**Comment by helfer** [comment]
We could do this in a 2.0 API as a breaking change, but not before that. Since the PR is closed, I'll close the issue as well.
