### ISSUE TITLE
Feature idea: Allow functions in refetchQueries

### ISSUE THREAD

**Issue by leoselig** [apollographql/apollo-client#1450]
**Goal:**
Allow the mutation `options.refetchQueries` to receive an array of `function`s (besides `string` and `PureQueryOptions`. These functions would receive the mutation result.

**Use Case:**
In some situations, the result of the mutation contains data that serves as arguments for query that should be refetched. In certain situations, `updateQueries` poses as a good alternative, but this is only if the mutation result already contains the data that should populate the "old"queries.

A good example of this is the `viewer(token)`-approach where, for authentication, where an auth token is passed on the top-level `viewer()`-field. This `Viewer`-type that contains all the sub-queries and mutations that differ depending on what user is requesting.

Slice of my code that hit this need:
```javascript
const CurrentUserQuery = gql`
  query CurrentUserEmailQuery($token: String) {
    viewer(token: $token){
      currentUser {
        id,
        email
      }
    }
  }
`;

const CreateAuthTokenMutation = gql`
  mutation createAuthToken($email: String!, $password: String!) {
    createAuthToken(email: $email, password: $password) {
      token
    }
  }
`;

const withMutation = graphql(CreateAuthTokenMutation, {
  props: ({ mutate }: Object) => ({
    login: async ({ email, password }: Object) => {
      const { data } = await mutate({
        variables: {
          email,
          password
        },
        refetchQueries: [{
          query: CurrentUserQuery,
          variables: { token: 'no way to populate this' } // this is the problem, a function could use the `data` from above
        }]
      });

      setToken(data.createAuthToken.token);
    }
  })
});

const withQuery = graphql(CurrentUserQuery);

export default withMutation(
  withQuery(
    App
  )
);
```
**Could this be a plugin?**
I don't think so. After taking a look at the source code, it seems to be pretty much baked into the `QueryManager`-implementation.
Prove me wrong :)

**Is there a workaround?**
The probably is one that I still need to find. With some ideas I had my structure would have had to change significantly and would have become quite complicated.

**Note** I already got a working test case for this, PR is incoming. I know you recommend not starting to early on implementation, but I'm fine with seeing this proposal fail if there is good reasoning. At least I got to take a look the the code of this awesome package!

**Comment by stubailo** [comment]
If you added `withApollo` to pass in the client as a prop, you could do:

```
mutate(...).then((result) => {
   client.query(THE_QUERY, { variables: { ... }});
});
```

This seems like a case of just wanting to do arbitrary things in the result of a mutation, and I think we should make that simpler rather than adding more special-case APIs.

Would the above solution work in your case?

**Comment by leoselig** [comment]
That sounds like a perfect workaround
I still feel like the idea of `refetchQueries` seems a little incomplete without the ability to use the mutation result within it
Just my 2 cents

**Comment by helfer** [comment]
Closing this since it's an old idea and has a workaround. Thanks for the suggestion though!
