### ISSUE TITLE
Refetching after update a query

### ISSUE THREAD

**Issue by flodlc** [apollographql/apollo-client#1458]
**Intended outcome:**
I'm trying to update the store with "update" after a mutation.
The query i'm updating is not watched during the mutation, this is why I do it with "update".

This is how I'm calling the mutation:

```
this.props.addMusiquesPlaylistMutation({
            variables: {playlist: playlistId, musiquesId: musiquesId},
            update: (proxy, {data: {addMusiquesPlaylistMutation}}) => {

                const data = proxy.readQuery({
                    query: musiquesPlaylistQuery,
                    variables: {categorie: null, playlist: playlistId}
                });

                addMusiquesPlaylistMutation.forEach(function (musique) {
                    data.musiquesPlaylist.push(musique);
                });
                
                proxy.writeQuery({
                    query: musiquesPlaylistQuery,
                    variables: {categorie: null, playlist: playlistId},
                    data
                });
            }
        });
```

This is my mutation and my query:

```
const musiquesPlaylistQuery = gql`
query musiquesPlaylistQuery ($categorie: String, $playlist: String) {
    musiquesPlaylist(categorie: $categorie, playlist: $playlist) { 
        artiste, titre, remixeur, id, info{nbEcoute, likes, nbLikes, note, liked, user}, categorie
    }
}`;

const addMusiquesPlaylistMutation = gql`
  mutation addMusiquesPlaylistMutation($playlist: String, $musiquesId: [String]) {
    addMusiquesPlaylistMutation(playlist: $playlist, musiquesId: $musiquesId) {
        artiste, titre, remixeur, id, info{nbEcoute, likes, nbLikes, note, liked, user}, categorie
    }
  }
`;
```

**Actual outcome:**
After calling proxy.writequery(...), everything seems good, the devtool shows me the store as expected.
But when I'm trying to display the component, the query is refetched once though the store is already exactly as expected.

Am I the only one with this behaviour ?
Should I do something more to avoid the query refetching after an update in a mutation?
I'm working with the last version of apollo-client and react-apollo.

Thanks!

**Comment by flodlc** [comment]
I've finally found the solution.
I set the __typename of each object  I add in the store by "update" before use writeQuery(...) to be sure the store keep the same Syntax than the one I've choose for "dataIdFromObject". 
In my case __typename + id.
Without the _typename, the symbol(id) of the object in the store wouldn't be as expected, I guess.

        ```
this.props.addMusiquesPlaylistMutation({
            variables: {playlist: playlistId, musiquesId: musiquesId},
            update: (proxy, {data: {addMusiquesPlaylistMutation}}) => {

                const data = proxy.readQuery({
                    query: musiquesPlaylistQuery,
                    variables: {categorie: null, playlist: playlistId}
                });

                addMusiquesPlaylistMutation.forEach(function (musique) {
                    data.musiquesPlaylist.push(musique);
                });

                data.musiquesPlaylist.forEach(function (musique) {
                    musique.__typename = "Musique";
                    musique.info.__typename = "Info";
                });

                proxy.writeQuery({
                    query: musiquesPlaylistQuery,
                    variables: {categorie: null, playlist: playlistId},
                    data
                });
            }
        })
```

And now it work perfectly without refetching, and the others mutation based on the "Symbol(id)" are still working.

Could anyone confirm ?

**Comment by helfer** [comment]
@flodlc I think your solution is right. The problem is with not writing the exact data into the store that you need. This kind of problem should become much easier to debug with #1638.
