### ISSUE TITLE
Apollo Client / Relay cache and node refetch

### ISSUE THREAD

**Issue by tlvenn** [apollographql/apollo-client#1460]
Apollo Client and Relay caches are pretty similar. They both normalize records using a flattened approach and can leverage a unique ID for given node to further help with deduplication of cache entries.

Relay however mandate the implementation of the `Node` interface which provides an ID lookup for any given node essentially providing refetch capability. This should give Relay cache implementation an additional tool to minimize the payload of a root query when some elements are not in the cache anymore for example. There are probably other cache use cases that could leverage node refetch.

I was wondering what is the current thinking of Relay node refetch capability and if it's something that could potentially help with the cache ?

**Comment by stubailo** [comment]
Apollo and the new experimental unreleased versions of Relay both do what some have referred to as "boolean query diffing" - for every given query, either the entire query is in the cache or the entire thing is refetched. So this seems to be where the state of the art of GraphQL clients is moving.

You can definitely use the Node interface manually with Apollo, and even use the `customResolvers` feature to resolve those from the cache directly, but we think the benefits of statically analyzable and predictable queries outweigh the benefits of dynamically generating smaller queries.

**Comment by tlvenn** [comment]
Ha interesting to see that Relay 2 is moving toward the same approach as in Apollo Client. Thanks for the feedback @stubailo.

**Comment by stubailo** [comment]
Cool - would be happy to have an issue to discuss different ways we could leverage the `node` API otherwise!
