### ISSUE TITLE
The "install dev tools" console message appears even when I have them installed already

### ISSUE THREAD

**Issue by ryancole** [apollographql/apollo-client#1470]
I'm on Windows 10 64-bit, using Chrome and the latest Apollo dev tools. Even with the dev tools installed, I still see the console log telling me to install them.

I see that the code attempts to check if the tools are installed before printing the message, so I figure there's a bug there and wanted to open this issue.

**Comment by ryancole** [comment]
I put some console logging in the `ApolloClient.js` file. I can see that, at run time, the check for `window.__APOLLO_DEVTOOLS_GLOBAL_HOOK__` is `undefined`, despite having the tools installed. This is triggering the notice.

**Comment by helfer** [comment]
@ryancole that's interesting. Which version of the devtools are you on? We recently updated them to include that hook.

I have the opposite problem: it doesn't print the message, even when I'm incognito mode, so I assumed it didn't work 😬

**Comment by ryancole** [comment]
@helfer here's the version info from the plugin page, via chrome ..

```
Additional Information
Version: 1.0.6
Updated: March 17, 2017
```

I just installed it about an hour ago, after seeing the console message.

**Comment by helfer** [comment]
Hm, that's the same one I have, and for me `window.__APOLLO_DEVTOOLS_GLOBAL_HOOK__` is not undefined. Are you sure you're not in incognito mode or something?

**Comment by jvbianchi** [comment]
I have the same problem

**Comment by ryancole** [comment]
@helfer Nope, not in incognito mode. Here's a screenshot of my browser. In the top right you can see the Apollo extension icon. In the dev console, you can see the Apollo tab's text. I've typed out `window._` and you can see what appears in the auto-complete dropdown.

![untitled](https://cloud.githubusercontent.com/assets/484801/24210003/c36bd1da-0ef5-11e7-96fb-18f197834949.png)

**Comment by helfer** [comment]
@ryancole @jvbianchi Hm, that's strange. Can you tell me what running `navigator.userAgent` in the console prints for you?

**Comment by helfer** [comment]
cc @daniman do you think it's possible the hook doesn't get added in all versions of Chrome for some reason?

**Comment by ryancole** [comment]
@helfer `"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"`

**Comment by jvbianchi** [comment]
@helfer "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"

**Comment by ryancole** [comment]
Also, just updated Chrome, and here's the new `userAgent`. The dev tools console message still appearing. `"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36"`

**Comment by jvbianchi** [comment]
Here is the plugin info:
Version: 1.0.7
Updated:  March 22, 2017

**Comment by helfer** [comment]
@jvbianchi I have the exact same user agent, so I'm surprised it's not working. Do you have an example app that I could run to see if it prints the notification for me as well? It may have to do with how the bundle is created.

I'm also curious to know: what is the output of just `__APOLLO_DEVTOOLS_GLOBAL_HOOK__` without the `window` before it? Is that also undefined? If it is, I'm almost certain the hook just isn't registered, so we'll have to look into that.

**Comment by jvbianchi** [comment]
The project I'm working in It's closed source. I'm using   apollo-angular v0.12.0 and apollo-client 1.0.0-rc.6.

`window.__APOLLO_DEVTOOLS_GLOBAL_HOOK__` => undefined

`__APOLLO_DEVTOOLS_GLOBAL_HOOK__` => VM2566:1 Uncaught ReferenceError: __APOLLO_DEVTOOLS_GLOBAL_HOOK__ is not defined  at <anonymous>:1:1

**Comment by ryancole** [comment]
For me, when I freshly open a tab, and try to check for `__APOLLO_DEVTOOLS_GLOBAL_HOOK__`, it does indeed exist without `window` before it. But, when I refresh the same page, within the same tab, the variable no longer seems to exist.

Here is what it looks like upon that initial load, though ...

![untitled](https://cloud.githubusercontent.com/assets/484801/24213422/60952326-0f00-11e7-86c2-a85e28c0d34a.png)

**Comment by stubailo** [comment]
> But, when I refresh the same page, within the same tab, the variable no longer seems to exist.

Ooh, I think this is the key. I think we only add that variable when the dev tools load, but don't add it when the page refreshes.

**Comment by ryancole** [comment]
@stubailo To clarify though, the dev tools console notification still appears on that first load, even with that variable existing. The variable does indeed go away after refreshing, though. So that's something!

**Comment by helfer** [comment]
Ok, I think this might be due to the timing. It could well be that the code that checks for the extension runs before the code that adds the hook to the window. Maybe we can solve this by using `chrome.runtime.sendMessage` instead, but it'll probably involve some experimentation.

**Comment by stubailo** [comment]
I think we should just add a delay before printing the message, and make sure the devtools add it to the page on refresh.

**Comment by ryancole** [comment]
[React also displays a similar notice](https://github.com/facebook/react/blob/master/src/renderers/dom/ReactDOM.js#L72-L92). Whatever they're doing seems to work as expected.

[And here](https://github.com/facebook/react-devtools/blob/5fedf871df064bbde429c27eddead08cabe72168/shells/chrome/src/GlobalHook.js) is where their dev tools appears to install the global hook.

**Comment by helfer** [comment]
We figured it out. Content script is the way to go. Could you try again with the newest version of apollo devtools (1.0.8) @ryancole @jvbianchi ?

**Comment by ryancole** [comment]
@helfer that fixes it! 👍
