### ISSUE TITLE
Cannot call "query" with "notifyOnNetworkStatusChange = true"

### ISSUE THREAD

**Issue by kenshero** [apollographql/apollo-client#1473]
![notifyonnetworkstatuschange](https://cloud.githubusercontent.com/assets/8245757/24217792/9f58185c-0f73-11e7-8ec6-34c3f3c77d1f.png)

my document query 

export const getPostQuery = {
  query : gql`
    query {
      getPosts {
        _id
        topic
        description
      }
    }
  `
}

i am not put notifyOnNetworkStatusChange. Why many time error but sometime works. Can you help me ? 
i have a picture error code.

**Comment by helfer** [comment]
@kenshero How are you running the GraphQL query? Are you calling `ApolloClient.query` or are you using an integration library like react-apollo?

**Comment by kenshero** [comment]
I use vanilaJs ApolloClient.query .

**Comment by helfer** [comment]
In that case you cannot use the `notifyOnNetworkStatusChange` option. Just don't pass it, or set it to false explicitly. This came up in another issue recently, and the explanation is there as well.
