### ISSUE TITLE
Create and export fetchPolicy constants

### ISSUE THREAD

**Issue by NeoPhi** [apollographql/apollo-client#1474]
Would like to see the various fetchPolicy options exported as constants instead of having to relay to magic strings (this could support moving to Symbols in the future).

This is in reference to: http://dev.apollodata.com/react/api.html#graphql-query-options\.fetchPolicy

**Comment by helfer** [comment]
@NeoPhi Yeah, that's a good idea. A PR would be very welcome!

PS: I use VScode and actually see all the options as suggestions since it's defined as a union in the TypeScript source.
