### ISSUE TITLE
Batching boundaries (feature idea)

### ISSUE THREAD

**Issue by langpavel** [apollographql/apollo-client#1477]
Hi

There is batching client for Apollo. **But Is there a _manual callback_ which can be used instead of waiting for timeout?**

You should be able to tell batching interface to not wait anymore because you know that **all code paths which can trigger new requests are finished**.. This is typically happens after you get callback from your top level router, `ReactDOM.render` or own logic..

This is especially useful on client. But it can be very useful when you SSR too!
You can reevaluate component tree again because there are some deeply nested component scenarios which you can interrupt at right time.
You should also know if there are new requests, say after 200ms after first SSR iteration (or more after when you detect search bot).

I know, there is server side helper, I'm using it, you can look at code. I'm coauthor of [kriasoft/react-starter-kit](https://github.com/kriasoft/react-starter-kit) and author of [feature/apollo](https://github.com/kriasoft/react-starter-kit/pull/1147) and other branches which teach people how to opt-in all these great features (not all are perfect I know, but hey, nobody is :smiling_imp:)

**Comment by helfer** [comment]
Hi @langpavel! I think it's a pretty good idea, and I'd be open to a PR! 🙂

**Comment by helfer** [comment]
Closing this since it's been a while, but still interested in an eventual PR, if someone wants to give it a try.
