### ISSUE TITLE
RFC: Root Query TTL

### ISSUE THREAD

**Issue by thebigredgeek** [apollographql/apollo-client#1480]
Hey guys,
I was thinking that perhaps a decent solution for the "ever expanding cache" problem might be to allow for a configurable TTL on root queries.  This TTL value could reset whenever the query is updated.  Whenever the query goes stagnant beyond a certain period, it could simply be purged out of the store once it's subscriber count reaches zero.  Any store entries that are orphaned (you can no longer traverse references from the entry to a root query) would also be purged.  Thoughts?

**Comment by stubailo** [comment]
Sounds like: #41 

I think this would be really cool to have after 1.0, we probably don't want to do it before then because it will require some store changes. But we could start working on designs now!

**Comment by thebigredgeek** [comment]
Yeah agreed.  I think we should take https://github.com/apollographql/apollo-client/issues/1432 into account when talking about this, though, as there would likely need to be some sort of function on the storage interface that `apollo-client` would call to trigger the removal of a root query and orphaned entry cleanup

**Comment by kouak** [comment]
My use case involves a complex SPA, running full screen for long periods of time (multiple days).

To prevent the store from ballooning, I've implemented a simple renderless component which will call `client.resetStore()` every now and then.

Ugly, but it does the job : https://gist.github.com/kouak/18910729ecfda906eadbd6084793f5eb

**Comment by cesarsolorzano** [comment]
I'm closing this, please refer to #621 for updates on this topic
