### ISSUE TITLE
Explicitly allow partial results, data is undefined as result of intentional partial results

### ISSUE THREAD

**Issue by greduan** [apollographql/apollo-client#1490]
**Intended outcome:**

The `.query(...).then` handler receives an object with a `data` key with server value. Example:

```js
client.query({ query, variables }).then(console.log.bind(console))
// {"data":{...},"loading":false,"networkStatus":7,"stale":false}
```

**Actual outcome:**

The `.query(...).then` handler receives an object with a `data` key of value `undefined`. Example:

```js
client.query({ query, variables }).then(console.log.bind(console))
// {"loading":false,"networkStatus":7,"stale":true}
```

**How to reproduce the issue:**

Make query to GraphQL server which returns partial result by design and make the client try to query the different possible results.

For example (client query):
```
query getListItems($url: String!){
  getListItems(url: $url) {
    __typename # KnownListItems OR UnknownListItems

    ... on KnownListItems {
      listItems {
        id
        content
      }
    }

    ... on UnknownListItems {
      message
    }
  }
}
```

Based on `payload.data.getListItems.__typename` the client would make an educated decision of what logic to follow next.

As far as I can tell this is because of checking against partial payloads, because if I remove the fragment for the result type that is being returned by the particular query, the data is returned, otherwise it isn't.

I'd like to be able to allow partial queries for particular queries. I tried Google'ing but my Google-fu was weak apparently. Also tried reading code but I am not familiar with the codebase so I didn't get very far..

Thanks for the help :grin:

**Comment by helfer** [comment]
@greduan I think this is the same issue as #1337, so I'll close it. We'll have a fix out shortly!

**Comment by greduan** [comment]
@helfer Thank you! :smile:

**Comment by greduan** [comment]
Just to confirm:

v1.0.0-rc.7 fixed the problem by using `fragmentMatcher: new IntrospectionFragmentMatcher()` as a property of `new ApolloClient()`.

Thank you for your time and effort :grin:
