### ISSUE TITLE
How to update props after this.props.client.query via 'withApollo' HOC ? 

### ISSUE THREAD

**Issue by smilexu** [apollographql/apollo-client#1493]
My use case is that I do not want to do the initial query for search component, instead of that,  I will trigger query after button click, seems like the only choice is withApollo HOC. 

Here is my code fragment.

```
    this.props.client.query({
      query: doc,
      variables: variant,
      reducer: (previousResult, action, variables) => {
        console.log('reducer!!!!!', previousResult, action, variables);
      }
    }).then((data) => {
      console.log('then', data, this.props)
    }).catch((err) => {
      console.log('catch', err)
    });
```
Fetching data is fine, I can get data in promise then, but how I can update it into props ? As the document http://dev.apollodata.com/core/apollo-client-api.html#ApolloClient\.query , reducer function should do that, but unfortenately it never be triggered in my sample code.

Did I do anything wrong? Or there is the other solution to solve that?

PS: version react-apollo@1.0.0-rc.2

**Comment by helfer** [comment]
@smilexu Reducer is not the right choice for this. You should be able to use `client.writeQuery` or `client.writeFragment` to update the cache.

Maybe a cleaner way to do this in React would be to have a Search component with a text field, then a searchResult component that's nested inside it. The searchResult component gets the search text as a prop. That way you could directly attach the query to the searchResult component.

**Comment by sherinmarlabs** [comment]
I've been trying this and couldn't find a proper solution.
I've have a login screen in which I call the client.query. I'm till not sure how to pass the error to the form when client.query fails when invalid credentials are passed.

I can handle the error and dispatch another action to my redux. I feel there will be a better way to do this.

**Comment by Elliryanna** [comment]
I do here an push.

I've nearly the same problem, is there a kind of solution already? I also want to use withApollo() instead of graphql()
I know there is a data.refetch within graphql()

**Comment by sherinmarlabs** [comment]
I'm using redux-form and withApollo. I was able to throw SubmissionError from the submit method when an error occurs. Sample code given below.

`try {
      const { data } = await client.query({
        query: query,
        variables: { username, password }
      })
      if (data.user) {
        document.location.href = redirectToHomePage
      }
    } catch (error) {
      throw new SubmissionError({
        _error: 'Unable to login'
      })
    }
`

Once the error is thrown, the props.error will have the error message 'Unable to login'.

**Comment by Elliryanna** [comment]
have you already tried to reset the store?
`this.props.client.resetStore();`
maybe it helps, its for me a kind of solution, but not in every case i have

**Comment by liuuu** [comment]
@smilexu have you solve the problem? I met it as well.

**Comment by mrdulin** [comment]
https://www.apollographql.com/docs/react/essentials/queries.html#manual-query

Is this what you want?

**Comment by smilexu** [comment]
yeah, withApollo is the solution, and in latest version, you can use ApolloConsumer instead of hoc.
