### ISSUE TITLE
Apollo client stops sending requests

### ISSUE THREAD

**Issue by mdebbar** [apollographql/apollo-client#1495]
I'm developing a web application that uses ApolloClient and ReactApollo to communicate with a qraphql api. On some pages, the apollo client works fine and sends the requests as expected. But on some pages, the client just stops sending requests and the `loading` flag is always true. I can see there are no requests in the Network tab in Chrome devtools.

So I started investigating the cause. I kept commenting out different parts of the code until I found the culprit. It's the jwplayer. If I just comment out the line that initializes the jwplayer, everything works fine.

The jwplayer code is minified so I couldn't figure out what was going on. Any advice on how to debug this? I'm surprised that external code can affect the way Apollo Client works and prevent it from sending requests.

**Comment by mdebbar** [comment]
The link to the jwplayer code: http://content.jwplatform.com/libraries/lkoR1NDI.js

I'll try to setup a minimal repro today or tomorrow. In the mean time, if anyone has theories on why this happens, I appreciate it.

**Comment by stubailo** [comment]
Yeah - if you could put together a small app that has AC, jwplayer, and does like one query that fails, that would help a ton!

So you don't get any errors or anything anywhere?

Sounds like it might be an issue with `fetch` or similar.

**Comment by mdebbar** [comment]
No errors. I tried using `fetch` from the console, it works fine. And I tried using the ApolloClient from the console but it didn't send any requests.

I'll try maybe creating a new ApolloClient instance after jwplayer is initialized?

**Comment by mdebbar** [comment]
My guess was right. I created a new apollo client and it worked fine. Does apollo client put or use anything in the global scope?

**Comment by stubailo** [comment]
Very little - just a few things so that the devtools can find your client. Nothing that would stop the client from working. Might be a good use case for a debugger - set a breakpoint right before firing the query, and then trace it through until something unexpected happens.

**Comment by mdebbar** [comment]
Ok, more findings: this issue only happens with `BatchedNetworkInterface`. I tried switching back to the default network interface and things worked as expected.

I'll debug what's going on in the `BatchedNetworkInterface` that's causing it to not send requests.

**Comment by mdebbar** [comment]
The requests are being enqueued in the `QueryBatcher` but they never get consumed. Looking now at how the query batcher works.

**Comment by mdebbar** [comment]
This is extremely weird. I've never seen something like this before. The `QueryBatcher` uses `setInterval` to watch to queue of requests (which is not ideal, but that's another topic).

I set a spy on `window.setInterval` and `window.clearInterval` to see what's going on. Everything seemed fine, the query batcher is calling `setInterval` and the callback starts getting called every 10ms (or whatever is configured in the batched network interface). The `clearInterval` never gets called, but for some reason the query batcher's callback stops being invoked after the jwplayer is loaded.

So I tried doing my own `setInterval` in addition to the query batcher. Now my callback stops being invoked and the query batcher works fine!

Question for experts in JS internals: how can a `setInterval` callback stop being invoked if `clearInterval` was never called??

**Comment by mdebbar** [comment]
Created a repro here: https://github.com/apollographql/react-apollo-error-template/pull/3

**Comment by mdebbar** [comment]
Here's a PR that removes the need for continuous polling of the request queue. That also seems to fix my issue because there's no more `setInterval`s going on.

https://github.com/apollographql/apollo-client/pull/1498

**Comment by helfer** [comment]
Thanks @mdebbar. The PR has been merged and will be released shortly!
