### ISSUE TITLE
Trigger Mutation on Redux state update

### ISSUE THREAD

**Issue by payner35** [apollographql/apollo-client#1508]
is it possible to have a mutation trigger after a redux state has changed?

I have a reducer changing state and setting a _tokenId_. I'd like to trigger a mutation to use the tokenId.

Should I call the GraphQL mutation in my action (which feels wrong)?

Can the mutation be auto-triggered once the state object is updated

my mutation looks like this...

```
const USER_LOGIN =  gql`
    mutation Login($token:LoginUserWithAuth0Input) {
      loginUserWithAuth0(input:$token) {
        user {
          id
          username
          createdAt
        }
      }
    }
`;

const USER_LOGIN_PROPS = graphql(USER_LOGIN, {
    props: ({ mutate }) => ({
        loginUserWithAuth0: (params) => mutate({
            variables: {token: {
              idToken: params.tokenId, 
            }}
        }),
    })
});
```

I can call the mutation _loginUserWithAuth0_ in my component..  but I want it to call once the token is received in the action..

```
function loginSuccess(authResult) {
  //we have loged in..
   console.log(authResult);
  return {
    type: LOGIN_SUCCESS,
    authToken: authResult.idToken
  };
}

export function login() {
  return (dispatch, getState) => {
    const lock = new Auth0Lock("XXXXX", 'XXXXX.XX.auth0.com', {
      auth: {
        redirect: false,
        responseType: 'token'
      }
    });
  lock.show();
  lock.on("authenticated", function(authResult) {
       localStorage.setItem('id_token', authResult.idToken);
      return dispatch(loginSuccess(authResult));
    });
  };
}

```

**Comment by baptistemanson** [comment]
If I understand correctly, you are trying to resolve a mutation after an action coming from a side-effect is resolved. I would do with redux-thunk or redux-saga.

**Comment by helfer** [comment]
@payner35 Not sure if this is still relevant to you, but you can definitely just call `client.mutate` in an action, if you want to. There's nothing stopping you from doing so 🙂
