### ISSUE TITLE
Query never receives result (stuck in loading state) when id is not specified on nested type three-levels deep

### ISSUE THREAD

**Issue by derek-duncan** [apollographql/apollo-client#1518]
[See reproduction for example](https://github.com/apollographql/react-apollo-error-template/pull/4)

**Intended outcome:**
When querying similar data throughout an app, it should be possible to exclude the `id` field on nested queries. E.g. (`{ people { id, name, pets { name } }`).

**Actual outcome:**
However, if you have two similar queries in your app, one that includes the nested `id` and the other that excludes it, the mounting either component leaves it stuck in the `loading` state. 

See these two components:
```
const ConnectedComponentOnPage1 = graphql(gql`{
  people {
    id,
    name,
    pets {
      id,
      name,
      belonging {
        id, # id is queried
        name,
      }
   }
 }
}`,
{ options: { fetchPolicy: 'cache-and-network' }))(ComponentOnPage1); // the cache-and-network policy is allow essential to reproduce

// Notice the component is on a different page. The important aspect is that is is unmounted. It seems that the error is only triggered when mounting/unmounting components.
const ConnectedComponentOnPage2 = graphql(gql`{
  people {
    id,
    name,
    pets {
      id,
      name,
      belonging {
        name, # no id queried here fails
      }
   }
 }
}`,
{ options: { fetchPolicy: 'cache-and-network' })(ComponentOnPage2);
```

The second components, when mounted, never gets refreshed with the data from the server, even if it completes successfully. It looks like this could be a similar issue to #1389, #1186, and other issues in react-apollo like [this one](https://github.com/apollographql/react-apollo/issues/563).  Included/excluding the id in both places fixes the issue. Seems like the cache is having a problem looking up the nested object when there are queries with an id and without an id.

**How to reproduce the issue:**
[Handy dandy reproduction in error template](https://github.com/apollographql/react-apollo-error-template/pull/4)

Thanks all! Let me know how I can help.

**Comment by cesarsolorzano** [comment]
An error message is thrown in [createApolloReducer](https://github.com/apollographql/apollo-client/blob/b69401085d50df1a51a47bcf6b04d40302ae7fdd/src/store.ts#L123) because it attempted to write an object with no id but the store already contained an id, therefore the [state](https://github.com/apollographql/apollo-client/blob/b69401085d50df1a51a47bcf6b04d40302ae7fdd/src/store.ts#L88-L89) is never updated (the loading flag is never set to `false`) and and no warning is emitted.

**Comment by derek-duncan** [comment]
thanks @cesarsolorzano. are you working on a solution to this? just checking to see if someone still needs to pick this up (I'm up for helping out as well).

**Comment by cesarsolorzano** [comment]
@derek-duncan yes, I'm working on it! 🙂

**Comment by cesarsolorzano** [comment]
@derek-duncan so, just to be clear, at the moment, we are talking here about a lack of warning.

The error thrown is from [`writeToStore`](https://github.com/apollographql/apollo-client/blob/54f7b9880023158fa2f9f142f2e1c2f32e724ab2/src/data/writeToStore.ts#L307) and it's swallowed  in [`fetchRequest`](https://github.com/apollographql/apollo-client/blob/4f626207da5cd2258c56d617647a2b08196142ec/src/core/QueryManager.ts#L1076) from QueryManager.

**Comment by derek-duncan** [comment]
@cesarsolorzano yep looks like it – I've never seen that error because it's being swallowed.
