### ISSUE TITLE
Question/Feature Idea - Dynamically uri for network interface

### ISSUE THREAD

**Issue by JMGonzalezR** [apollographql/apollo-client#1521]
Hi Apollo Team

There is a way to set or change the Uri of network interface after set it the first time? I have an app that the user can change the host to point, so i want to change the BaseUri when the user change it. 

Something like `gql(
{
    uri:baseuri+'graphql',
    query:'foo{id}'
}
)`

Thanks

**Comment by fc** [comment]
You could achieve this by creating a custom network interface:
http://dev.apollodata.com/core/network.html#custom-network-interface

Every time you query, you could re-calculate the URI to what you want.

In your case you may actually want to wrap their existing interface and just reload their network interface with whatever URI you want to use.

**Comment by helfer** [comment]
I agree with @fc, I think the best way to go is to create a custom network interface that allows changing of the URI.

**Comment by ravihugo** [comment]
this was my implementation of that
```
const httpLink = createHttpLink({
    fetch: (_uri, options) => {
        return fetch(getGraphQLBaseUrl(), options);
    }
});
```
if it helps anyone

**Comment by patels95** [comment]
@ravihugo How do you pass in options from client.query or client.mutate to that?

**Comment by kavinithiy** [comment]
> this was my implementation of that
> 
> ```
> const httpLink = createHttpLink({
>     fetch: (_uri, options) => {
>         return fetch(getGraphQLBaseUrl(), options);
>     }
> });
> ```
> 
> if it helps anyone

Did You identified any solution ?

**Comment by kavinithiy** [comment]
> @ravihugo How do you pass in options from client.query or client.mutate to that?

Did you identified any solution ?
