### ISSUE TITLE
Union types & fetchMore not working together

### ISSUE THREAD

**Issue by rovansteen** [apollographql/apollo-client#1523]
When fetching more of a query that has union types the results come back undefined or without data.

**initialQuery**
Not using `IntrospectionFragmentMatcher`: works fine.
Using `IntrospectionFragmentMatcher` with schema: works fine.

**fetchMore**
Not using `IntrospectionFragmentMatcher`: `fetchMoreResult` is undefined.
Using `IntrospectionFragmentMatcher` with schema: `fetchMoreResult` is undefined.

**How to reproduce the issue:**
I've created a simple repository to illustrate this issue.
https://github.com/rovansteen/react-apollo-union-fetchMore-issues
As you can see, the first result comes in fine. But when clicking the load more button it throws an error `Cannot read property 'people' of undefined` because `fetchMoreResult` is undefined.

I'm using version 1.0.

**Comment by helfer** [comment]
@rovansteen thanks for filing an issue and providing a reproduction! This might be fixed in 1.0.1 by #1527. Could you give it another try and report back?

**Comment by rovansteen** [comment]
@helfer thanks! Unfortunately after updating to `1.0.1` the issue is not resolved yet, and `fetchMoreResult` returns still undefined.
I've updated the repository: https://github.com/rovansteen/react-apollo-union-fetchMore-issues

**Comment by msimulcik** [comment]
@rovansteen I've just tried your repo with reproduced problem and fetchMore is working fine with 1.0.1

**Comment by rovansteen** [comment]
@msimulcik removing my `node_modules` and running a fresh `yarn` did the trick, not sure why that was causing an issue. Anyways thanks for checking it out, great work on the 1.0 release, running smooth now!
