### ISSUE TITLE
Question/Feature Request Partial Query Result for Data already in store

### ISSUE THREAD

**Issue by n1ru4l** [apollographql/apollo-client#1525]
Lets say I have the following schema:
```graphql
type Arc {
  id: Int!
  title: String!
  cover: String!
}

type Series {
  id: Int!
  title: String!
  arcs: [Arc]!
  cover: String!
}

type Query {
  series: [Series]!
  oneSeries(id: Int!): Series

  arcs(seriesId: Int!): [Arc]!
}
```
In my first View I am fetching an overview of all series with the following query:
```graphql
query allSeries {
  series {    
    id
    cover
    title
  }
}
```

Then somewhere else I have a second View in which I am fetching details for a specific series

```graphql
query oneSeries($seriesId: Int!) {
  oneSeries(id: $seriesId) {
    id
    title
    cover
    arcs {
      id
      title
      cover
    }
  }
}
```

Altough parts of the data for the second query already exist in my store, I will have to wait until the query is executed to access the query result. I think it would be awesome to get a partial result first (which can be shown to the user already) , which is updated when the query was executed against the server - Maybe this could be implemented as a new `fetchPolicy` option.

At the moment I am doing a workaround by splitting the second query into two queries:
```graphql
query oneSeries($seriesId: Int!) {
  oneSeries(id: $seriesId) {
    id
    title
  }
}
```

```graphql
query seriesArcs($seriesId: Int!) {
  arcs(seriesId: $seriesId) {
    id
    title
    cover
  }
}
```

The `oneSeries` query is resolved trough a custom resolver, which makes the data available instantly.
It could also be done by preloading more data, but I don't really want to load all arcs of a series in the `allSeries` query.

I did not find anything related to partial query results, except (#51). I wanted to ask if that is something that is planned and if so its priority.

**Comment by Mike-Dax** [comment]
It appears this functionality used to be available, but it was considered bad practice.

Take a look at this PR: https://github.com/apollographql/apollo-client/pull/1370

> To replace current usage of returnPartialData, specify a query with the data that you know / expect to be in the store at that moment. If for instance you want to provide a preview, then write a query that requests a subset of the data you know to be available. Render the component with that query while the larger query is loading.

**Comment by n1ru4l** [comment]
Ok thanks for the information, looks like I was heading into the right direction. I think this should get documented!  I think the recipe section would be the correct place to add this? I could do a PR for this.

**Comment by n1ru4l** [comment]
I am working on it here: https://github.com/n1ru4l/react-docs/blob/master/source/partial-data.md

**Comment by cesarsolorzano** [comment]
@n1ru4l great! I'm going to close this now, but feel free to re-open this issue in [apollographql/react-docs](https://github.com/apollographql/react-docs/issues) so it can be discussed there.
