### ISSUE TITLE
reducer and updateQueries not called after mutation if query contains union type

### ISSUE THREAD

**Issue by msimulcik** [apollographql/apollo-client#1526]
**Intended outcome:**
I have query with union type field and I want to update cache with mutation result. I expect reducer or updateQueries to be called after mutation. I use IntrospectionFragmentMatcher with exported schema.

**Actual outcome:**
Neither reducer nor updateQueries are fired after mutation. If I remove union type field from query, it works.

**How to reproduce the issue:**
Here is repo containing reproduced problem: https://github.com/msimulcik/react-apollo-error-template. Clicking on "Do Nothing!" button executes dummy mutation and should log messages from reducer and updateQueries to console. `master` branch contains non-working version and `working-no_union_in_query` branch contains working version. Difference is only in omitted union type [(diff)](https://github.com/msimulcik/react-apollo-error-template/compare/master...msimulcik:working-no_union_in_query?expand=1)

**Comment by msimulcik** [comment]
Can it be that `diffQueryAgainstStore` is missing `fragmentMatcherFunction` [here](https://github.com/apollographql/apollo-client/blob/648b8e1c6a401c2b1c8bb1891104e2419c1c47c1/src/data/store.ts#L161) and thus `graphqlAnywhere` is using default fragment matcher?

**Comment by helfer** [comment]
@msimulcik That could indeed be the reason, thanks for the PR! 👍

**Comment by msimulcik** [comment]
I'm gonna add tests tomorrow. Would it be enough to cover only the case when I call mutation and expect updateQueries and reducer on query with union type to be called? I'm thinking about adding it to [test/client.ts](https://github.com/apollographql/apollo-client/blob/master/test/client.ts)
