### ISSUE TITLE
Apollo query using "... on MyNode" returns undefined.

### ISSUE THREAD

**Issue by krailler** [apollographql/apollo-client#1531]
**Intended outcome:**
{ data: { ... }, ... }

**Actual outcome:**
{ data: undefined, ... }

**How to reproduce the issue:**
If "... on UserNode" is set, client.query(...) returns { data: undefined, ... }
Example of query:
```
query ($id: ID!) {
  tournament(id: $id) {
    id
    matches {
      edges {
        node {
          id
          player {
            displayName
            ... on UserNode {
              nick
            }
          }
        }
      }
    }
  }
}
```

**Comment by helfer** [comment]
Thanks @krailler! Could you perhaps provide a small reproduction using [react-apollo-error-template](https://github.com/apollographql/react-apollo-error-template)?

**Comment by krailler** [comment]
@helfer I solve this using custom IntrospectionFragmentMatcher , see: https://github.com/apollographql/apollo-client/issues/1363#issuecomment-291332651, why do I have to use this to work?
