### ISSUE TITLE
(Reopen) Uncaught (in promise) Error: Must contain a query definition. #1536

### ISSUE THREAD

**Issue by TheoMer** [apollographql/apollo-client#1537]
As a continuation to [#1536](https://github.com/apollographql/apollo-client/issues/1536#issuecomment-291333049), the suggested change to the mutation was made, but this did not resolve the issue:

```
        mutation incrementPostLikes ($id: ID!, $count: Int) {
          updatePosts (id: $id, likes: $count) {
            id
            likes
          }
        }
```

P.S. I'm not sure whether I'm following proper protocol by opening up this 'continued' issue here, as I was unable to re-open the previous issue.

**Comment by helfer** [comment]
Hi @TheoMer. It seems like there were two problems in your original mutation. The error message indicated that you used `client.query` instead of `client.mutate`. You should try it like that.
