### ISSUE TITLE
(Reopen) Uncaught (in promise) Error: Must contain a query definition. #1536

### ISSUE THREAD

**Issue by TheoMer** [apollographql/apollo-client#1539]
As a continuation to [#1536](https://github.com/apollographql/apollo-client/issues/1536#issuecomment-291333049), the suggested change to the code was made,

`client.mutate`

but now throws an `Uncaught TypeError: Cannot read property 'kind' of undefined` error, as shown in the attached image.

![error](https://cloud.githubusercontent.com/assets/15969262/24643948/be2d2634-1908-11e7-93a7-55f0b571c8c1.jpg)

**Comment by helfer** [comment]
I'm sorry @TheoMer, but I can't help any further without a reproduction. Could you please provide one with [react-apollo-error-template](https://github.com/apollographql/react-apollo-error-template)?

**Comment by TheoMer** [comment]
@helfer You can find my fork of the error-template [here](https://github.com/TheoMer/react-apollo-error-template)

`Yarn install` away

**Comment by greduan** [comment]
Can confirm I also get this error.

**Comment by greduan** [comment]
This error is caused because `apollo.mutate` expects `mutation` to exist as a property of its first argument, rather than `query`.

**Comment by TheoMer** [comment]
@greduan Thank you. But first allow me to, 'ahhhhhhhhh!!!'. Ok, I feel better now.

So. data.updatePosts. likes throws an `Cannot read property 'likes' of undefined` on handleSubmitSuccess. Any ideas?

```
  mutation: gql`
        mutation incrementPostLikes ($id: ID!, $count: Int) {
          updatePosts (id: $id, likes: $count) {
            id
            likes
          }
        }
      `,
      variables: {
        "id": idVal,
        "count": incVal
       },
      // forceFetch: true,
    })
    .then(this.handleSubmitSuccess)
    .catch(this.handleSubmitError);
  },
  handleSubmitError(err) {
    console.error(err.message);
  },
  handleSubmitSuccess(data) {
    console.log(data.updatePosts.likes);
  } 
```

**Comment by greduan** [comment]
Wouldn't it be `res.data` or `{ data }` as argument to `handleSubmitSuccess`?

**Comment by zutshisunakshi** [comment]
![relaymutationerror](https://user-images.githubusercontent.com/18541122/33294403-43f6e6ec-d385-11e7-9c43-53596c9329f5.PNG)


The auth.js code where the error hits 
`
		createUser = (authFields) => {
				return new Promise( (resolve, reject) => {
					Relay.Store.commitUpdate(
						new CreateUser({
							email: authFields.email,
							idToken: authFields.idToken
						}), {
							onSuccess: (response) => {
								this.signinUser(authFields)
								resolve(response)
							},
							onFailure: (response) => {
								console.log('CreateUser error', response)
								response.getError().source
								reject(response)
							}
						}
					)
				})
			}`

I am getting this error while creating user once it gets authenticated. I am using Auth0 to authenticate which works fine only when using relay and GraphQL API to insert/fetch the user details this error comes up as uncaught in promise. I did set the GraphQL endpoint for relay.

I am just getting started with these frameworks, please provide any pointers in direction to debug this.


Thanks!
