### ISSUE TITLE
Full error data not returned

### ISSUE THREAD

**Issue by alekbarszczewski** [apollographql/apollo-client#1550]
**How to reproduce the issue:**

Here is a mutation

```
      apollo.mutate({
        mutation: gql`
          mutation ($input: UserCreateData!) {
            createUser(input: $input) {
              id
              email
              created_at
              access_token
              refresh_token
            }
          }
        `,
        variables: { input },
      })
      .then(result => {
      })
      .catch(err => {
        console.log(err);
      });
```

And here is a response received by client:

![screen shot 2017-04-05 at 13 23 31](https://cloud.githubusercontent.com/assets/2742373/24703331/1bfb5088-1a03-11e7-8918-69a1e0045f5b.png)

**Intended outcome:**

It should be possible to access original error & error data after "catching" rejected query promise.

**Actual outcome:**

```
Error: GraphQL error: Validation error <-- only message in returned here
    at new ApolloError (eval at <anonymous> (client.js:851), <anonymous>:34:28)
    at eval (eval at <anonymous> (client.js:1189), <anonymous>:126:33)
```

**Comment by cesarsolorzano** [comment]
@alekbarszczewski isn't this related to #1496?

**Comment by thebigredgeek** [comment]
Yeah, I think this was a breaking change at some point.  I know that, before, I was able to access the raw error in the `.catch` clause.  But I don't really deal with error handling at the request location... I deal with it globally... so I can't really relate to the pain haha

**Comment by alekbarszczewski** [comment]
Hmm, I am not sure if it's related but in fact I found some solution: actually ApolloError does have public property `graphQLError` which is an array of errors. Not sure if it's documented: https://github.com/apollographql/apollo-client/blob/master/src/errors/ApolloError.ts#L35.
Closing this because err.graphQLErrors it's exactly what I was looking for. Thanks.
