### ISSUE TITLE
Feature request: createLocalInterface

### ISSUE THREAD

**Issue by raix** [apollographql/apollo-client#1553]
Would it be beneficial to have a `createLocalInterface` when you initially are trying out apollo-client / graphql in an existing stack?

The apollo-client and graphql can be a good alternative to all the redux boilerplating when it comes to maintaining a client cache/pagination/optimistic updates etc.

For now I basically just set up graphql schemas on the client and connected it directly to the `ApolloClient` via a basic interface. The interface it not much code but it might not be the first thing newcommers would figure out.

The apollo client dev tools seem to be working out of the box with the client-side only interface. *except it needs to be closed on hmr - it's not reconnecting/reloading when in graphiql*

I propose something like:

```js
import { ApolloClient, createLocalInterface } from 'react-apollo';
import schema from './schema';

const localInterface = createLocalInterface(schema);

const client = new ApolloClient({
  networkInterface: localInterface
});
```
*`networkInterface` doesn't feel like the best name match for this case though*

If needed I can do a pr with code and examples

Kind regards Morten

**Comment by Poincare** [comment]
Are you suggesting that a new user would be able to run the the GraphQL schema on the client with a bunch of mocked data in order to get up and running with Apollo Client?

**Comment by raix** [comment]
The graphql schema resolveres could use rest endpoints or mock data.

It could be new users, or like in my case we dont have a graphql server yet - but I still want to leverage the Apollo client (I'm not keen on writing redux boilerplate code for defining a client cache for server data)

**Comment by helfer** [comment]
@raix are you aware of the two following patterns/solutions?

1. [mock network interface](https://github.com/apollographql/apollo-test-utils)
2. [a network interface that calls graphql execution](https://github.com/apollographql/react-apollo-error-template/blob/master/src/graphql/networkInterface.js)

**Comment by raix** [comment]
@helfer well I just did:
```js
import ApolloClient from 'apollo-client';
import { print } from 'graphql/language/printer';
import { graphql } from 'graphql';
import schema from './schema';

const client = new ApolloClient({
  networkInterface: {
    query({ query, rootValue, contextValue, variables, operationName }) {
      return graphql(schema, print(query), rootValue, contextValue, variables, operationName);
    },
  },
});
```

**Comment by helfer** [comment]
Ah, I see. Basically like option 2 above. Since it's almost no code, I'd actually be in favor of including this in apollo-client. Can you make a PR for it!? 😃

**Comment by raix** [comment]
@helfer sure I can do a pr, something like:
```js
const client = new ApolloClient({
  networkInterface: new GraphQLInterface(schema),
  // or
  executor: new GraphQLExecutor(schema),
});
```

**Comment by raix** [comment]
I think I'll name it `createSchemaInterface` for now. I'll have a pr ready tomorrow

**Comment by raix** [comment]
Since this would add more dependencies to the core apollo client we shouldn't add it in the main bundle.

Options:
* Move it to a separate package *costly in maintenance*
* Settle with documentation of the pattern
* Create general executor interface leaving it up to the user to supply an executor

```js
const client = new ApolloClient({
  networkInterface: new ExecutorInterface(graphql, { schema?, context? }),
});
```

**Comment by abhiaiyer91** [comment]
Do you want to use this interface in production?

**Comment by abhiaiyer91** [comment]
Can't we bundle this in `apollo-test-utils`?

**Comment by raix** [comment]
@abhiaiyer91 if you don't have a graphql server and want to evaluate graphql and a store maintainer like apollo client what are your choices?

We might use apollo-client in prod - but we still have to evaluate and have some concerns to iron out.

--

From my point of view we can close this ticket - my point was to help newcomers that didn't have a graphql server in their stack

--

Further references:
* https://github.com/apollographql/apollo-client/issues/1272#issuecomment-278827278
