### ISSUE TITLE
__typename field prevents updates

### ISSUE THREAD

**Issue by sarora2073** [apollographql/apollo-client#1564]
Hi,

High-level issue: appended __typename field causes errors when updating. 

Details:
When retrieving data for a custom address type, it appears that (by design) __typename field is added to the type e.g. I have an Address type on the server, and on the client this is fetched as shown below:
```
,"homeAddress":{"street":"1 John Doe St","line2":"","city":"Doe City","state":"California","zip":"91111","**__typename":"Address"**},
```
The UI permits changes to this address data, and then when I take this data object (generated by a watchQuery), and pass the same (user modified) object back as a mutation variable, the mutation fails with the error below.
```
{"errors":[{"message":"Variable \"$homeAddress\" got invalid value {\"street\":\"1 John Doe St\",\"line2\":\"\",\"city\":\"Doe City\",\"state\":\"California\",\"zip\":\"91111\",\"__typename\":\"Address\"}.\n**In field \"__typename\": Unknown field."**
```
As I understand it, the problem is introduced because __typename is created by the graphql server, but not considered valid when resubmitted back. Not sure if this would be considered a valid "bug" or if i just need to follow another approach. 

Here are the options I can think of:

1. Disable adding typenames (I saw some hints that this was an option). I guess the main impact here would be that I can't use fragments? If so, I could live with that.

2. Cleanse the _typename field manually on the client (ugh). Would this have the same impact -- fragments won't work. 

3. Wait for a bug fix. I don't know enough about how / why __typenames are added to know if there is a potential fix that address the update scenario I described without breaking other scenarios. If it's considered a valid bug and fixable long-term then that would be good to know. Perhaps one option is to disable the validation that occurs on mutations to always allow the __typename field to be submitted?

4. Change my schema to explicitly add __typename as a data field for each type. Not sure if this would create unwanted side-effects. I'm thinking of this as a workaround, not necessarily a fix for root cause.

Please advise if I've missed anything. 

Thank you,

S. Arora

p.s. i'm using apollo-angular 0.13.0 with apollo-client 1.0.2

**Comment by saudpunjwani101** [comment]
What args type have u defined in the server mutation?

**Comment by sarora2073** [comment]
I have a customer type which has an embedded address input type. Note: create, read and delete operations are successful against this schema, and *even updates work in the Graphiql UI* using the schema, resolver function, so i'm confident the code is fine. Updates only fail on the client side, and the error message explicitly says it doesn't like the __typename field on the embedded Address (input) type.

**Comment by sarora2073** [comment]
update: i was able to resolve this in a way that makes any "root cause" fix unnecessary, at least from the use case i'm dealing with which is a typical edit form in an angular app. It turns out that when I subscribe to the results of apollo-angular query, and bind those to the editForm, the object I bind to is immutable by design, so I can't just rely on it to store form edits as I was trying to do i.e. I have to do something like clone that object (that contains the unwanted __typename) anyway, and merge the form edits, before passing it back in the mutation as the newly edited object. So one approach could be to use Object.assign as follows to clone the immutable customer Object, and overlay the form edits:

updateCustomer() {
let newCustomer = Object.assign({},this.customer,this.editForm.value);
this.dataService.updateContactBy(newCustomer);
..
}

The Object.assign is doing a shallow copy and appears to strip away the pesky __typename field that was causing issues on the mutation. Problem solved.

**Comment by mmahalwy** [comment]
@sarora2073 having the same problem as you, except I cannot get rid of the `__typename` with `Object.assign`. What'd you do to get around this now?

**Comment by sarora2073** [comment]
I haven't changed the approach. If you provide the version of the relevant libraries and code snippets etc. I'd be glad to compare what you're doing vs whats working for me.

**Comment by Billy-** [comment]
Can this issue please be re-opened? I believe it is a valid issue for discussion.

**Comment by herlon214** [comment]
I agree with @Billy-, it's a valid issue for discussion.

**Comment by sarora2073** [comment]
Update: I was mistaken about how I resolved the issue for my purposes and have updated my comments above to be clear. 

I concur that generally speaking the __typename field is a nuisance and that Object.assign does NOT remove it. An enhancement that sanitizes it on the query side and/or mutation would be helpful imho.

Workarounds for now:
1.  Manually remove __typename from the cloned object
2. Follow a different pattern. If i'm creating a form, I might bind the graphql result data to the form first, then use the form model to do the update.

**Comment by jbaxleyiii** [comment]
@sarora2073 you can disable adding `__typename` on when creating a cache, though I don't recommend it as it makes the cache less reactive and fragments are much harder.

One option would be to use an `omit` function like the one [lodash provides](https://lodash.com/docs#omit) to `const data = omit(changed, ['__typename'])` to clean the fields

**Comment by sarora2073** [comment]
Thanks @jbaxleyiii. Did a quick search and am guessing the way to do this is by modifying the dataIdFromObject constructor perhaps?

Found some general docs here but nothing specific to how:
https://www.apollographql.com/docs/angular/cache-updates.html

Anyhow, I'll defer to the others on this thread that wanted to revive the matter to dive further as it's not a burning issue for me personally at the moment. Thanks.

**Comment by Billy-** [comment]
@jbaxleyiii note that omit is not deep, and also that lodash intends to remove omit from the library entirely  [[sic](https://github.com/lodash/lodash/issues/723#issuecomment-340779022)]. This is what I am using at the moment to strip the `__typename` field deeply: https://gist.github.com/Billy-/d94b65998501736bfe6521eadc1ab538

**Comment by rasdaniil** [comment]
Thanks @Billy- , I've incorporated your function like this to filter out __typename once and for all:

```
  return graphqlExpress({
    schema,
    context,
    formatParams: params => {
      const { variables, ...rest } = params;
      return {
        variables: omitDeep(variables, '__typename'),
        ...rest
      };
    }
  });
```

**Comment by argallo** [comment]
@rasdaniil I tried this but got `Cannot delete property '__typename' of #<Object>`

`products: {
                            basketProducts: omitDeep(Object.assign({}, this.props.basketProducts), '__typename')
                        }`

**Comment by Trellian** [comment]
Hi @Billy- and @rasdaniil ,

I'm getting this same problem, but not on mutation (haven't even got there yet).  This is happening on a simple query. The __typename is being passed through to my SQL backend as a column request.  Of course the SQL server rejects the query.

I implemented the 'omitDeep' option as described above, but it is not helping.  Do you perhaps have some thoughts or advice on this issue?

TIA
Adrian

**Comment by Trellian** [comment]
Not to worry, problem solved, my objection-graphql middleware just needed to filter out the __typename 'column'

**Comment by cdelgadob** [comment]
Well I honestly think that if GraphQL injects the "__typename" field to make caching better, it should handle it as an input, and not throwing an error and leaving that for us to handle.

It's GraphQL internals at the end of the day.

So from my point of view, options are:

1. Filter the __typename column when Apollo receives the results, after using it in the cache and before passing it over the app. This would leave the implementation and handling up to the client, so I wouldn't vote for it since it's not universal.
2. The GraphQL server should accept the __typename column as an extra optional input, not included in the schema, as an internal mechanism. It can just discard it or use it for other purposes.

For the moment, I'll strip it manually.

Happy graphql'ing! ;)

Carlos

**Comment by lobosan** [comment]
Same issue here, and it seems that there's only two options to handle this: 1. Clone the object or 2. Do a deep cleaning which isn't ideal. Hopefully the tooling will improve overtime.

**Comment by cdelgadob** [comment]
So I ended up creating an ApolloLink to clean the "__typename" field before sending the object to the server. Here it is in case you want to use it:

https://gist.github.com/cdelgadob/4041818430bc5802016332dbe5611570

Hope it helps!

**Comment by pedall** [comment]
somehow the object gets not cleaned for me. @cdelgadob can you show how you connected it to the ApolloClient? maybe I am doing something wrong.

**Comment by cdelgadob** [comment]
Hi @pedall,

In the init component I concatenate the Apollo links used in the app and composed them like this:

```
const myAppLink = ApolloLink.from ([
      cleanTypenameLink,
      resetTokenLink,
      addTokenLink,
      httpLink
    ])

    this.apollo.create({
      link: myAppLink,
      cache: cache
    })
```

Please let me know if this helps!

Carlos

**Comment by bjunc** [comment]
Another option is to set `addTypename` to `false` in your cache config (used to be in [ApolloClient config](https://github.com/apollographql/apollo-client/blob/master/Upgrade.md)).  

```js
new InMemoryCache({ addTypename: false })
```

Caveat, is that you'd no longer get typenames across the board; which may not be an issue.

**Comment by stalniy** [comment]
@cdelgadob this version of `ApolloLink` is simpler and probably faster ([it uses `reviver` parameter of `JSON.parse`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse)):

```js
function createOmitTypenameLink() {
  return new ApolloLink((operation, forward) => {
    if (operation.variables) {
      operation.variables = JSON.parse(JSON.stringify(operation.variables), omitTypename)
    }

    return forward(operation)
  })
}

function omitTypename(key, value) {
  return key === '__typename' ? undefined : value
}
```

**Comment by VladShcherbin** [comment]
Maybe it'll be possible to add an `option` in config per operation to prevent adding `__typename`. Something like this one: 

```js
graphql(singleUserQuery, {
  options: props => ({
    variables: { id: props.match.params.id },
    fetchPolicy: 'network-only',
    removeTypename: true
  })
})
```

**Comment by sakhmedbayev** [comment]
Agree with @VladShcherbin! Remove `__typename` per operation has a lot of sense!

**Comment by 4F2E4A2E** [comment]
Is there any improvement on this?
We are getting this error after setting the option `new InMemoryCache({ addTypename: false })`
```
writeToStore.js:139 WARNING: heuristic fragment matching going on!
```

**Comment by plck** [comment]
@cdelgadob Thanks! The solution in your gist worked for me mostly, I had to remove the `.map()` in `forward.map()` to make it work with `apollo-link: ^1.1.0`.
Here's my gist: https://gist.github.com/plck/6dbf7ba856dd2b80335520f8f348a108

**Comment by stalniy** [comment]
The best solution is to introspect graphQL inputs and do recursive `pick` before each mutation. This is how I ended up

Eventually you will have issues not only with `__typename`

**Comment by 4F2E4A2E** [comment]
It is also about the queries, why enforce typename in the first place? It should be optional, it must be, I hope this is a bug.

**Comment by lukeify** [comment]
I've got to say for newcomers to GraphQL like myself, it's issues such as these which really make me go 'wtf' and question why I decided to implement GraphQL for a project over just some REST.

**Comment by sarora2073** [comment]
@stainiy - I recommend a new case on the query front. I agree that sounds like a blocker for sql backends, but best way to get to the bottom of it is to detail what’s going on with that specific scenario as it’s slightly off-topic for this one imho. The update scenario has been discussed at length and there are options to address it.

**Comment by 4F2E4A2E** [comment]
> Is there any improvement on this?
> We are getting this error after setting the option `new InMemoryCache({ addTypename: false })`
> ```
> writeToStore.js:139 WARNING: heuristic fragment matching going on!
> ```
but @sarora2073, what about the error? It's a bug right?

**Comment by DenisNeustroev** [comment]
https://github.com/apollographql/apollo-client/issues/1564#issuecomment-357492659 this is the best solution

**Comment by danderson00** [comment]
There are lots of people hitting this issue. This issue should definitely not be closed without explanation.

It is a cardinal sin for a library to modify incoming objects and expect developers to implement hacky, manual workarounds to deal with the modification.

Is there any intent for the maintainers to improve the situation?

**Comment by zimme** [comment]
Isn't it possible to apollo client to strip away `__typename` automatically before returning the result in the `Query` component? Then what you get is what you expected. But internally apollo-client still have `__typename` on the objects in the cache and can use them.

**Comment by gopidon** [comment]
I had to manually strip the **__typename_** key.

**Comment by webberwang** [comment]
I agree that the __typename field should be an internal abstraction with Apollo, having the client strip it away manually just creates extra confusion for beginners, & extra unnecessary code. 

I'm hesitant to set typename to false in config because I may need those extra performance benefits down the line.

**Comment by rplute** [comment]
Reading all the comments above, it appears like the community wants this handled internally versus manually stripping the `__typename` key. Is there any traction on this?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=__typename%20field%20prevents%20updates&body=Migrated%20from:%20apollographql/apollo-client%231564) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
