### ISSUE TITLE
Deleting data with `writeFragment`

### ISSUE THREAD

**Issue by dahjelle** [apollographql/apollo-client#1570]
**Intended outcome:** I'd like to be able to selectively remove data from the query store via the imperative API (i.e. `client.writeFragment` and `client.writeQuery`). Something like:

```
client.writeFragment({
  fragment,
  id,
  data: null
});
```

or

```
client.writeFragment({
  fragment,
  id,
  data: {}
});
```

Is there a way to accomplish this?

**Actual outcome:** If I try either of the two above constructions, the data still exists and can be read back out. You can see this in [this example](https://runkit.com/dahjelle/58ebac433425bc0014c8ec55).

**How to reproduce the issue:** Here's a complete code example:

```
import ApolloClient from 'apollo-client';
import gql from 'graphql-tag';

const client = new ApolloClient.ApolloClient({
  dataIdFromObject(obj) { return obj.id; },
  addTypeName: true
});
const fragment = gql`fragment update on person{ 
  id
  __typename
}`;
const id = 'person-01';
const __typename = '__typename';

client.writeFragment({
  fragment,
  id,
  data: {
    id,
    __typename
  }
});
client.readFragment({
  fragment,
  id
}); // should get { __typename: '__typename', id: 'person-1' }

client.writeFragment({
  fragment,
  id,
  data: null
});
client.readFragment({
  fragment,
  id
}); // fragment is still there; I'd expect `null`
```

Perhaps there is just some syntax that I'm missing?

What I've done currently—and am *really* not a fan of—is take the [old mutation delete reducers code](https://github.com/apollographql/apollo-client/commit/4437d9758058817c9a21728c6ed88148ae0bdbf3#diff-dc40890f4da12424669a670eb4fde0ad) and stick it in my code base as follows:

```
    const state = client.store.getState().apollo;
    state.data = mutationResultDeleteReducer(state.data, {
      behavior: {
        dataId: action.id
      }
    });
```

That seems to work, but is obviously quite fragile in terms of the store format, etc.

**Comment by helfer** [comment]
@dahjelle: this is indeed not something that's easy to do at the moment. What is your concrete use-case? Is it to invalidate the data or to purge it from the store? Depending on what people actually want to do, it might make sense to implement an invalidation mechanism or a way to delete objects from the store.

As an experiment, I'd be more than happy to accept a PR that implements `deleteFragment` and `deleteQuery`. One thing to be aware of is that this might lead to other queries suddenly erroring or becoming stale because part of the data that they were watching in the store has now disappeared.

**Comment by dahjelle** [comment]
>  What is your concrete use-case? Is it to invalidate the data or to purge it from the store?

I guess I'd say invalidate the data. Purging it from the store isn't really necessary in my case, though that would be fine, too.

A little more background: my storage back-end is in CouchDB, with CouchDB documents being served up via GraphQL. To keep the front-end up-to-date, I'm using the `_changes` feed to catch changes in documents, and then updating the store as appropriate. This includes documents that have been deleted by the user.

> As an experiment, I'd be more than happy to accept a PR that implements `deleteFragment` and `deleteQuery`.

If I get a chance to work on it, I'll post back here when I start. :-D

**Comment by helfer** [comment]
Maybe worth knowing: When you write `{}` to the store that gets merged with the object that was previously there, so nothing changes. Have you tried writing `null` or `undefined` and seeing what happens? Maybe it'll throw an error, but maybe it'll actually do something close to what you want.

**Comment by dahjelle** [comment]
@helfer I did try `null` and `undefined` as the `data` to `writeFragment` and got back the same result as writing `{}`.

**Comment by skosch** [comment]
Would it be an option (among others) to provide a simple way to delete by object id? That would probably cover the most common use case.

**Comment by helfer** [comment]
@skosch it isn't possible right now, but we're thinking of adding an API for doing invalidations and deleting data in the store. Let's continue all discussions related to that on #621
