### ISSUE TITLE
Apollo plugin missing from Chrome

### ISSUE THREAD

**Issue by TheoMer** [apollographql/apollo-client#1586]
OS; Windows 10 Pro
Browser: Chrome Version 56.0.2924.87 (64-bit)
Apollo Client Developer Tools 1.0.8.1
apollo-client: "^1.0.2",
react-apollo: "^1.0.0-rc.3",

So, I have the plugin installed in chrome, as can be seen in the top right hand corner of the attached image, but it no longer appears in devTools.

I have uninstalled, and reinstalled the plugin, but still the issue remains the same.

What is the issue here?

![missing apollo](https://cloud.githubusercontent.com/assets/15969262/25003730/c3f3ec5a-2048-11e7-9d7f-457e303410f9.jpg)

**Comment by intellix** [comment]
If you're lazily-loading the client, then this is related: https://github.com/apollographql/apollo-client-devtools/issues/26

**Comment by cesarsolorzano** [comment]
@TheoMer you should discuss this in [apollographql/apollo-client-devtools](https://github.com/apollographql/apollo-client-devtools/issues/) 🙂 

Closing since this isn't a bug or a problem with Apollo Client.
