### ISSUE TITLE
Optimistic Response Malformed Data Causes List Response to Empty Out

### ISSUE THREAD

**Issue by ztratar** [apollographql/apollo-client#1588]
We're building a chat app, and are using optimisticResponse combined with updateQueries.

The following code (screenshot) works well. The optimisticResponse is combined with our other message data, and the messages array is 1 greater than before.

![image](https://cloud.githubusercontent.com/assets/955182/25023880/7ec03c58-2050-11e7-879b-9414ac9edba1.png)

The following code, however (screenshot), does not work. Instead of saying there was a malformed optimisticResponse or ignoring the missing fields, the entire messages list is emptied out.

![image](https://cloud.githubusercontent.com/assets/955182/25023888/8c2bb426-2050-11e7-9482-f454601a584f.png)

**Comment by cesarsolorzano** [comment]
closing in favor of #1273

**Comment by ztratar** [comment]
Thanks!
