### ISSUE TITLE
What's the best way to refetch queries when using batching?

### ISSUE THREAD

**Issue by tscanlin** [apollographql/apollo-client#1589]
I was able to get refetch working with simple queries in this PR:
https://github.com/apollographql/apollo-client/pull/1274

However, now we are switching to batched queries and need to essentially retry the request after refreshing an auth token.

Currently this is the flow:
1. Initial request is made and responds with a 401
2. Request is made to refresh the token (endpoint not part of graphql) responds with new token
3. Reset the query manager store.
4. Query all the requests again with the new token.

Relevant code from our afterware:
```js
// Reset the store so Apollo doesn't hold on to the errors from before.
client.queryManager.resetStore()

let doneCount = 0
res.options.options._requests.forEach((request, i) => {
    networkInterface.query(request).then((d) => {
        doneCount++
        if (doneCount === res.options.options._requests.length - 1) {
            next()
        }
    })
})
```

If we don't do `client.queryManager.resetStore()` then the error from the initial 401 query comes through and our UI doesn't get updated by the second request.

My question is essentially: "Is this the right way to do this?"

Thanks in advance! Apollo day yesterday was awesome :)

**Comment by Poincare** [comment]
Is the second authed query a force fetch (i.e. a "network only" query)?

**Comment by tscanlin** [comment]
Yes it is

**Comment by tscanlin** [comment]
We ended up just using `refetch` from `applyBatchAfterware`.

```js
// Refetch observed queries.
Object.keys(client.queryManager.observableQueries).forEach((q) => {
    const query = client.queryManager.observableQueries[q].observableQuery
    query.refetch(query.variables);
})
```
