### ISSUE TITLE
Best way to store only specific queries / results in localstorage?

### ISSUE THREAD

**Issue by neilff** [apollographql/apollo-client#1600]
I'm using `redux-persist` alongside Apollo, I've been able to cache the entire store quite easily by pushing all of the data inside `store.apollo` into localstorage. This results in faster startups for my app which is great. 

My problem with doing this however is that by caching the entire Apollo reducer state, I am potentially caching a lot of data (e.g. 5-10+ megabytes of data). I wanted to know if there is a way to store only a specific query, and the data that query responded with into localstorage.

Redux persist provides unlimited customization through their [custom transforms](https://github.com/rt2zz/redux-persist#transforms) which would allow me to filter out any unwanted data. However, I cannot figure out which pieces of the reducer state are required by Apollo in order to cache the data correctly.

Is what I am trying to do possible?

Thanks

**Comment by helfer** [comment]
Hey @neilff! Apollo client only needs the 'data' part, so you can safely discard everything else. However, I don't think that will help all that much, because that's probably where most of the store size comes from anyway. Are there specific queries that you want to keep?

**Comment by neilff** [comment]
Thanks for responding @helfer, I want to store only a specific `__typename`. If all I need is the `data` portion of the store, would filtering the store on `__typename === 'DesiredType'` and pushing that into `localstorage` work?

**Comment by helfer** [comment]
Yes, that would work, but you'll have to preserve the path from the root to those objects to make sure that the query that the objects were fetched with can be successfully run against the store again. What does your query look like?

**Comment by neilff** [comment]
@helfer it is fairly simple, something like...
```
  query UsersQuery {
    users {
      name
      id
      firstName
      lastName
      ...
    }
  }
```

This ends up returning ~700 items and is a heavy query, so caching it for faster startup would be nice.

**Comment by helfer** [comment]
Cool, in that case you should be able to filter out just the `ROOT_QUERY` field and all the `user` objects.

**Comment by helfer** [comment]
Going to close this since it seems the question was answered.
