### ISSUE TITLE
Discussion: read/write methods

### ISSUE THREAD

**Issue by abhiaiyer91** [apollographql/apollo-client#1606]
Hey all! This isn't a bug per say, but something I'd like to hash out.

When using `readQuery` `writeQuery`, I often forget the same variables used between readQuery, writeQuery.

```
proxy.readyQuery({ 
  query: Foo,
  variables: { bar: 'zoo' }
});
```

and then with writeQuery:

```
proxy.writeQuery({ 
  query: Foo,
  variables: { bar: 'zoo', baz: 'someOtherVar' }
});
```

I don't know how many times I've messed this up and spent debugging why I was getting unexpected results!

I know I know, i can just create a common variable to share between my methods but I was thinking...

What if proxy took `variables` and `query` like this:

`proxy({ variables, query })`

and then we have methods like `readQuery`, `writeQuery`

`proxy.readQuery()` and `proxy.writeQuery(data)`

Please let me know if I'm completely crazy!

**Comment by helfer** [comment]
Seems like that would mean you can only read and write a single query, which would severely restrict the usefulness of that API.

**Comment by helfer** [comment]
I think you'll find this kind of thing much easier to debug with #1638, so I don't think we should add the ability to somehow store the variables. It would make the logic less transparent and more complicated.
