### ISSUE TITLE
Query fails with fragments on interfaces, works without

### ISSUE THREAD

**Issue by ndarilek** [apollographql/apollo-client#1608]
**Intended outcome:**

I have a schema like so:

```
enum CurrencyCode {
  USD
}

type Currency {
  code: CurrencyCode!
  amount: Float!
}

input CurrencyInput {
  code: CurrencyCode!
  amount: Float!
}

interface LineItem {
  item: String!
  notes: String!
  total: Currency!
}

type FixedLineItem implements LineItem {
  item: String!
  notes: String!
  total: Currency!
}

type TimeLineItem implements LineItem {
  item: String!
  notes: String!
  hours: Int!
  rate: Currency!
  total: Currency!
}

input LineItemInput {
  item: String!
  notes: String!
  hours: Int
  rate: CurrencyInput
  total: CurrencyInput
}

type Invoice {
  id: String!
  lineItems: [LineItem]
}

input InvoiceInput {
  lineItems: [LineItemInput]
}

type Query {
  invoice(id: String!): Invoice
}
```

In my Vuex store, I implement the query like so:

```
const invoiceFragment = gql`fragment invoice on Invoice {
  id
  lineItems {
    item
    notes
    total {
      code
      amount
    }
    ...on TimeLineItem {
      hours
      rate {
        code
        amount
      }
    }
  }
}`

...
      const {data} = await apolloClient.query({
        query: gql`
          query($id: String!) {
            invoice(id: $id) {
              ...invoice
            }
          }
          ${invoiceFragment}
        `,
        variables: {
          id
        },
        fetchPolicy: "network-only"
      })
```

I expect this will return an invoice, getting the common items from my LineItem type, as well as the specific data on both FixedLineItem and TimeLineItem. The main difference between these is that TimeLineItem has `hours` and `rate` fields, and its `total` is a resolver that multiplies `hours` by rate`, whereas FixedLineItem has `total` directly set.

**Actual outcome:**

I get an error stating that `data` is undefined, but I don't get a query error. This indicates that my query isn't returning anything, which it should since the data does exist.

Interestingly enough, invoices containing TimeLineItems work. If I add a FixedLineItem, this error starts. Likewise, if I remove the fragment from the `lineItems` field query, everything works. Unfortunately, then I don't get specific fields from TimeLineItem which I need.

It would be helpful to get an actual schema error if I'm doing something incorrectly. But in the absence of that, I assume I'm doing things correctly but Apollo is silently failing.

To be clear, I understand the specific `data is not defined` error. What I *don't* understand is why this query fails when an invoice with line items of a certain type enters the system.

**How to reproduce the issue:**

Clone https://github.com/ndarilek/graphql-fragments-error.
```
cd graphql-fragments-error
yarn install
yarn dev
```

First, open http://localhost:8000/invoices/Hqqcg8Dtybdu23ZA which only includes a TimeLineItem. Notice how it works. http://localhost:8000/invoices/5AA7ZwqC49eDPiao on the other hand includes a FixedLineItem, which doesn't. Likewise, http://localhost:8000/ fails while the FixedLineItem invoice exists.

Most of the code of interest should be in server.js, where the back-end lives, and store/invoices.js, where the invoice query logic lives. The rest should just be setup/display code. Sorry I couldn't pair things down further or use the React template with Vue. Happy to provide any additional details if needed.

Thanks!

**Comment by helfer** [comment]
Hey @ndarilek. I think using the new fragment matcher will solve this problem for you (see #1483).

Here's how to use it:

```const fm = new IntrospectionFragmentMatcher({
 introspectionQueryResultData: {
  __schema: {
    types: [{
      kind: 'UNION',
      name: 'Item',
      possibleTypes: [{ name: 'GreenItem' }, { name: 'RedItem }]
    }]
  }
});
```

and then pass it to Apollo Client in the constructor: `const client = new ApolloClient({ fragmentMatcher: fm });`

To figure out the exact introspectionQueryResultData to pass, you can run this query against your server:
```{
  __schema {
    types {
      kind
      name
      possibleTypes {
        name
      }
    }
  }
}```

It's a bit of manual work at the moment, but it should solve your problem, and we're going to add docs for how to run a build step that does this automatically for you.

**Comment by helfer** [comment]
Closing this in favor of #1555

**Comment by cesarsolorzano** [comment]
@ndarilek hey there! `ApolloClient` takes a `fragmentMatcher` option which should be a function.

You are initializing the `ApolloClient` with the wrong options (using an object instead of a function and with the name of `introspectionQueryResultData` rather than `fragmentMatcher`). There's more information available [here](http://dev.apollodata.com/react/initialization.html#fragment-matcher). Let me know if that solves the problem 🙂

**Comment by richburdon** [comment]
@cesarsolorzano by "function" you mean an instance of `IntrospectionFragmentMatcher` correct? I have the same issue despite supplying this. https://github.com/apollographql/apollo-client/issues/1741. Note also, this isn't documented in the `ApolloClient` ref docs: http://dev.apollodata.com/core/apollo-client-api.html#apollo-client
