### ISSUE TITLE
Discussion: Delete mutations & entire cache removal

### ISSUE THREAD

**Issue by Siyfion** [apollographql/apollo-client#1616]
This post is just to bring the discussion on entire-cache updates to the forefront so that people can voice their opinions on how best to tackle the issue longer-term.

## The Issue
A delete mutation may be triggered that deletes a data object from the underlying DB. This data object may be referenced in many queries, in particular, nested data in seemingly un-related queries. For example:

```
type Category {
  id: String!
  name: String!
  todos: [Todo]
}

type Todo {
  id: String!
  name: String!
  description: String
}

type Query {
  category(id: String!): Category
}
```

- A Todo item may be removed using a mutation
- The `id` of the removed Todo could be returned (optional)
- The todo could exist in _any_ `Category` `todos` array (ie. belong to more than one category)
- Thus, a number of queries eg. `category({ id: 'xxx' })`, `category({ id: 'yyy' })`, etc. may reference the deleted `Todo` item.

In this scenario how would you update the cache, using the `update` method, to remove the deleted Todo item from the various queries that might reference it?

One strategy would be to implement a "destroyAll" method for the cache, whereby **_any_** stored Todo type with the deleted Todo's `id` is removed from the cache.

This is similar to this: https://github.com/apollographql/apollo-client/blob/37e8de86de2cb534275c0f89992ee5de55999b5c/src/data/mutationResults.ts#L171-L188 

After a discussion with @stubailo, we thought it best to open the discussion to the community, to see what people have done to get around the issue and/or thoughts on how to resolve it.

**Comment by Siyfion** [comment]
As a response to my own question, I guess one simple answer would be "don't do it with the `update` method", as this situation is possibly much easier to resolve with a `reducer` method on the query itself instead.

As an example, for the `category(id: String)` query you could add:
```javascript
      reducer: (previousResult, action) => {
        if (action.type === 'APOLLO_MUTATION_RESULT' && action.operationName === 'removeTodo') {
          const removedTodoId = action.result.data.removeTodo;

          const todos = _.cloneDeep(previousResult.category.todos);
          _.remove(todos, todo => todo.id === removedTodoId);

          return update(previousResult, {
            category: {
              todos: {
                $set: todos,
              },
            },
          });
        }
        return previousResult;
      },
```

**Comment by helfer** [comment]
Let's keep track of deleting under the invalidation umbrella issue as well #621
