### ISSUE TITLE
feature suggestion: operationName included in redux actions whenever possible

### ISSUE THREAD

**Issue by AdamYee** [apollographql/apollo-client#1619]
Hello!

In the process of incorporating apollo-client in my app that heavily uses its own redux store, I find myself wanting `operationName` to be found in all Apollo dispatched actions where available (if the query/mutation name exists). For example, a component's initial query dispatches an `APOLLO_QUERY_RESULT` whose payload contains `operationName`, but subsequent cached queries dispatch `APOLLO_QUERY_RESULT_CLIENT` whose payload doesn't have `operationName`. Is it feasible to provide `operationName` everywhere it can apply? My workaround right now is to look into the `action.document` for the query name (which I assume is how operationName is determined).

I'm watching these action types in order to keep my original redux store in sync with the apollo-client store. I can't quite fully rely on the apollo-client store right now because:

1. I've built a lot of convenience around reselect and redux's `connect` that has me quite reliant on the way I grab props. With apollo-client, I lose the dependency injection and instead have to manually pass down props.
2. My client side models carry extra properties for UX needs. I'd have to perform some hefty refactoring to decouple client only properties in a way that compliments react-apollo's ability to automatically update UI based on server (cache) changes.

I'm new at GraphQL and Apollo so this has been my approach without much guidance. Anyone go through a similar experience?

Thanks 😃

**Comment by helfer** [comment]
@AdamYee I think it would be useful, but I'm a bit worried about cluttering the actions even more. You're right that we get the operation name from the document, so it's probably easiest if you do the same. If you make a PR to export `getOperationName` from the client and make it available, I'd be happy to merge it!

**Comment by MichaelDeBoey** [comment]
Don't know if this is all that needed to be done, but tried to help with this one in #1676 🙂
