### ISSUE TITLE
Undefined data when subscribing nested union types query

### ISSUE THREAD

**Issue by luiscvalmeida** [apollographql/apollo-client#1625]
**Intended outcome:**
I'm trying to get data after subscribing a watchQuery, given a query that has nested union types.

```
const DEAL_QUERY: DocumentNode = gql`
  query Deal($id: Int!) {
    deal(id: $id) {
      ... on PropertyAsset {
        id
        name
        class
        description
        instrument {
          __typename
          ... on DebtInstrument {
            debtType
          }
          ... on EquityInstrument {
            votingRights
          }
        }
      }
    }
  }`;

const deal$ = this.apollo.watchQuery({
      query: DEAL_QUERY,
      variables: { id: 1 }
});

deal$.subscribe(({ data }) => { 
    console.log(data); // undefined
});
```

**Actual outcome:**
The actual outcome is that the data returned inside the subscribe result is undefined.
If I remove the `instrument` field from the query, everything works fine.

**How to reproduce the issue:**
I would add a plunkr to this but I don't know any public graph api that supports union types.

**Comment by luiscvalmeida** [comment]
Sorry for this, my mistake, the resolver of the graph was returning data different from the query, that's why it returns undefined. But some error throwing would be helpful tho.

**Comment by helfer** [comment]
Hey @luiscvalmeida, thanks for filing an issue!

I think this could be a duplicate. Have you tried the solution outlined in #1555 using `IntrospectionFragmentMatcher`?

**Comment by helfer** [comment]
@luiscvalmeida I'm going to close this as a likely duplicate. If you think it isn't, please let me know.
