### ISSUE TITLE
Refetch issue with 1.1.1

### ISSUE THREAD

**Issue by harmon25** [apollographql/apollo-client#1633]
**Intended outcome:**
Being able to refetch on a query without fetchPolicy defined.

Apollo-Client - 1.1.1
React-Apollo -  1.1.1

**How to reproduce the issue:**
Try to refetch a simple query.
Am getting the following error:
![image](https://cloud.githubusercontent.com/assets/6964054/25549360/5989cf94-2c3f-11e7-8c5c-269da77d5245.png)

If I use 1.1.0 of Apollo Client - the refetch works as intended.
Appears this fix - Fix: Remove ability to set default fetchPolicy, which broke polling queries PR #1630
Has broken the ability to refetch a simple query. 

Thanks for the help!

**Comment by helfer** [comment]
@harmon25 Thanks for reporting the issue, it's very odd. Reverting that PR should not break anything that wasn't broken before. In addition, we have tests for refetch. I would think it much more likely that 1.1.0 has broken refetch. Are you sure about the version that you're running? Sometimes there can be multiple versions installed, for example one directly, and one through react-apollo. 

In any case, would you be able to put together a quick reproduction using the [error template](https://github.com/apollographql/react-apollo-error-template) if the error persists? That way I can debug it.

**Comment by harmon25** [comment]
Hm OK does appear having both `apollo-client` and `react-apollo` as dependencies is unnecessary and possibly causes some weird behaviour.

This is related to the following react-apollo issue:
https://github.com/apollographql/react-apollo/issues/622

Going to close for now, move any input/discussion there.
