### ISSUE TITLE
How does cache trimming/invalidation work with apollo?

### ISSUE THREAD

**Issue by tnrich** [apollographql/apollo-client#1640]
Hi there,

I couldn't find a description of how cache invalidation/trimming works with apollo-client anywhere in the documentation (sorry if it is there I must have missed it). 

I'm using react-apollo in particular and am curious if the cache gets trimmed after a particular event or maybe after the total data store size grows above a certain limit (assuming the component(s) relying on the queries aren't still being rendered).

Thanks!

**Comment by cesarsolorzano** [comment]
@tnrich I think there's no implementation on this at the moment, however, there has been some discussions (that you may find useful) in #825 and #621

**Comment by tnrich** [comment]
@cesarsolorzano thanks for the info!

**Comment by cesarsolorzano** [comment]
I'm closing this, please refer to #621 for updates
