### ISSUE TITLE
batchInterval is in Milliseconds [Add to docs]

### ISSUE THREAD

**Issue by gaston23** [apollographql/apollo-client#1641]
^ :)

**Comment by cesarsolorzano** [comment]
@gaston23 thank you for pointing it out! Would you like to make a PR to help clarify this?

**Comment by helfer** [comment]
I'm going to close it here since it's a docs issue, and the docs have a separate repo (react-docs or core-docs). Please consider opening a PR @gaston23!

**Comment by bryanyee** [comment]
Created a PR in core-docs: https://github.com/apollographql/core-docs/pull/315
