### ISSUE TITLE
Network error, how to return data from cache

### ISSUE THREAD

**Issue by reut-co** [apollographql/apollo-client#1653]
when having a network error I would like to show the previous cached data (since we're using polling so there might be moments without network connection)
how can I do it?

**Comment by helfer** [comment]
@reut-co are you using react-apollo? If so, the component will now keep the data that was previously returned.

As for having a fetch policy that is essentially fetch-from-network-but-use-cache-if-necessary, we don't have that ready quite yet, but it's something we've been thinking about in the context of having much more flexible fetch policies.

**Comment by Strayer** [comment]
@helfer I have a slightly related question about this… I'm using fetchPolicy cache-and-network, but I only want to show an error message to the user if both fail. Meaning ignore network errors as long as there is something in the cache.

By just checking data.error the network request failure will cause an error to pop up even if the cache was able to return data. What is the correct approach here? Ignore data.error if there is still query data available? I'm also always getting "Unhandled (in react-apollo) Error: Network error: undefined" messages – am I doing something wrong? I don't see how I could handle the errors in graphql-wrapped React components.
