### ISSUE TITLE
Feature request: BatchMaxQueries

### ISSUE THREAD

**Issue by happylinks** [apollographql/apollo-client#1654]
I just set up the batching queries with Apollo, which are great!
One thing I found was that when you execute a lot of mutations at the same time (let's say I want to save 100 images with a mutation for each), it will put all these queries in one batch.

This makes sense of course, because they are within the batch time limit. But a call with 100 mutations is probably slower then 10 calls with 10 queries.

My request would be to set a max for the amount of queries that are put into a batch. And if the batch is bigger then the max, start a new HTTP request.
This max could be set the same way as the batchInterval.

Would love to hear your thoughts :)

**Comment by helfer** [comment]
@happylinks I like the idea, it seems pretty reasonable to me! If you make a PR, I'd be happy to review it. 🙂

**Comment by happylinks** [comment]
Cool, I'll take a stab at it :)
