### ISSUE TITLE
How to pass metadata per request/mutation

### ISSUE THREAD

**Issue by tnrich** [apollographql/apollo-client#1656]
Hi there,

I have a question about how to pass metadata on an apollo request. In my case, I am going to be making multiple create/update mutations in a row, and want to be able to wrap the creates/updates in a single transaction on the backend. To do that, I need to be able to pass a "transaction id" from the front end, as well as whether or not a given request is the last request in the series. 

Does anyone know if this can be done?

I found this: https://github.com/apollographql/apollo-client/issues/1066 
But it wasn't clear to me if it was addressing my issue.

Thanks so much!

**Comment by helfer** [comment]
@tnrich I think #1066 is essentially asking for the same thing. At the moment it's not possible. You might be able to hack something by giving your mutations a name that carries some meaning, and then sticking extra information into the request headers in your middleware.

However, even if you can transmit the intent of a transaction, it might still be a bit hacky on the backend to keep everything in one transaction if it's not a single request. Is there any way you could put all the modifications in a single mutation? That way it would be one operation, and the order of execution would be guaranteed (which is not the case if you send them separately, unless you write some extra logic to make it happen).

**Comment by helfer** [comment]
I'll close the issue in favor of #1066, let's continue the discussion there! I'm definitely interested in seeing the solution you come up with, if you don't mind sharing it!

**Comment by tnrich** [comment]
@helfer , thanks for the quick response! 

That is a bummer there is no way to do this yet. I'll check over at #1066 to see if I can help something get implemented on this front.

In my case actually, they would be guaranteed to run serially because I would be doing something like:

mutation1.then(()=>{
  mutation2.then()...etc
})

I think the backend transaction would be okay as well...
