### ISSUE TITLE
Cache, and hence UI not updating after calling mutation that changes the __typename.

### ISSUE THREAD

**Issue by Florentijn** [apollographql/apollo-client#1677]
In our relay compliant GraphQL schema, we have defined an interface, lets say `Policy`, and a couple of types that implement the interface, lets say `PendingPolicy` and `ActivePolicy`. In one of our mutations, we change the underlying type of the object, while keeping the same id. We could for example have a mutation that mutates the PendingPolicy to an ActivePolicy type. The mutation returns the mutated policy object. In this case, the `id` field remains the same during the transition, while the `__typename` field changes. We are making sure that we are retrieving the id of the mutated policy in our GraphQL mutation string.

We would like to update the UI for some queries in our React app after calling this mutation, but for some reason, the UI does not update automatically when we are calling the above mutation. Adding options for RefetchQueries did also not have effect.

Our apollo client uses only the id for caching:

```
const networkInterfaceUser = createNetworkInterface({ uri: XXX });
export const apolloClient = new ApolloClient({
  networkInterface: networkInterfaceUser,
  dataIdFromObject: o => o.id
});
```

What can I do to update the UI for the query that queries a policy? It seems Apollo still uses the __typename internally for its cache.

Thank you in advance 😃 
Florentijn

**Comment by Florentijn** [comment]
We did find it in the end! The problem was that you need to pass the necessary schema knowledge to Apollo Client so unions and interfaces can be accurately matched and results validated before writing them into the store. See [http://dev.apollodata.com/react/initialization.html#fragment-matcher](http://dev.apollodata.com/react/initialization.html#fragment-matcher)

One note, the documentation mentions the following snippet:

```
import { IntrospectionFragmentMatcher } from 'react-apollo';
const myFragmentMatcher = new IntrospectionFragmentMatcher({
  introspectionQueryResultData: {
    __schema: {
      types: [
        {
          kind: "INTERFACE",
          name: "Character",
          possibleTypes: [
            { name: "Jedi" },
            { name: "Droid" },
          ],
        }, // this is just an example, put your own INTERFACE and UNION types here!
      ],
    },
  }
})
```

However, import { IntrospectionFragmentMatcher } from 'react-apollo'; should be import { IntrospectionFragmentMatcher } from 'apollo-client'; Since otherwise we get the following error:
<img width="1278" alt="screen shot 2017-05-08 at 15 41 53" src="https://cloud.githubusercontent.com/assets/5784217/25807215/4ea22256-3406-11e7-9896-3b8e3874518d.png">


Thanks @excitement-engineer for finding the documentation improvement.

**Comment by helfer** [comment]
Thanks @Florentijn! Can you check if you still need to import from `apollo-client` with the newest `react-apollo`? If so, please file an issue!

**Comment by excitement-engineer** [comment]
I can confirm that this is not an issue in the newest version (1.2.0) of `react-apollo`! I tested it out. This was an issue in version 1.0.1 of `react-apollo`.
