### ISSUE TITLE
Change Traking on Datacontext To create mutation 

### ISSUE THREAD

**Issue by badre429** [apollographql/apollo-client#1678]
Is there any way to implement change traking on data context like we see on ORM framework where we have datacontext (dc ) and we have datasets (dc.products) 
and all mutation happen after calling (dc.savechanges())

**Comment by stubailo** [comment]
No - GraphQL mutations are more like an RPC than an ORM. There is no concept of "saving" an object in a GraphQL API, you need to create specific mutations in your API, and then construct arguments to those.
