### ISSUE TITLE
updateQueries does not return store(cache) data on second attempt

### ISSUE THREAD

**Issue by waleedarshad** [apollographql/apollo-client#1679]
I have a secnario where i upload document to property. on very first page load when i upload document i received property in *prev* object and it show correctly on UI. When i upload another document on store, it does not return any property object in previous. why?

      (graphql(MUTATION, {
	    props: ({ mutate, ownProps: { id, onSuccess, onError } }) => ({
		onUploadError(err) { onError(err); },
		onUploadSuccess(blobs) {
			const category = CATEGORY;
			const type = DOC_TYPE;
			let msg = 'SUCCESS!';

			if (blobs.length > 1) {
				msg = `${msg} ${blobs.length} files were uploaded`;
			} else {
				msg = `${msg} '${blobs[0].filename}' was uploaded`;
			}

			onSuccess(msg);

			blobs.forEach((blob) => {
				try {
					filepicker.convert(blob, {
					    width: 340,
					    height: 440,
							format: 'png',
					  }, {
							location: 'S3',
							path: `thumbs/${id}/comps/`,
							storeContainer: `roipgm-platform-${process.env.NODE_ENV}`,
						},
					  (thumbnail) => {
							mutate({
								variables: { id, category, type, blob, thumbnail },
								updateQueries: {
									getProperty: (prev, { mutationResult: { data } }) => (
										update(prev, {
											property: { documents: { $push: [data.insertDocument] } },
										})
									),
								},
								optimisticResponse: {
									__typename: 'Mutation',
									insertDocument: {
										__typename: 'Document',
										category,
										type,
										id,
										url: blob.url,
										filename: blob.filename,
										thumbnail: thumbnail.url,
										uploadedAt: new Date(),
										uploadedBy: 'You',
									},
								},
							})
							
					  },
						
					);
				} catch (e) {

				}
			});
		},
	}),
      })(UploadPropertyComps))
 
**Why**

Store is getting empty on uploading document again?
Does it the problem of updating store with optimistic response again and again without waiting to be replaced by actual response from server

**Comment by waleedarshad** [comment]
![screenshot from 2017-05-08 13-47-10](https://cloud.githubusercontent.com/assets/5329697/25797023/123f04f2-33f5-11e7-84d6-9395a25bbe75.png)

**Comment by helfer** [comment]
Hi @waleedarshad, thanks for filing an issue. It's really hard for us to tell if this is a problem with apollo-client or with your app. Could you put together a minimal reproduction with the most recent version of react-apollo and apollo-client using [react-apollo-error-template](https://github.com/apollographql/react-apollo-error-template).

**Comment by waleedarshad** [comment]
Hi @helfer, when i used this line into the after mutation then it work fine

refetchQueries: ['getProperty']
so it mean refetching worked but not without. 

Current version
Meteor 1.4.2.7
 apollo-client: "^0.8.1",
 apollo-server: "^0.3.3",
 react-apollo: "^0.9.0",
 graphql: "^0.7.2",

Will try to reproduce

Thanks

**Comment by helfer** [comment]
@waleedarshad I'm glad it works now! I think the reason it probably didn't work is because the optimistic response didn't contain all the data that was required for the old query.
