### ISSUE TITLE
'coverage/coveralls' integration is stuck

### ISSUE THREAD

**Issue by MichaelDeBoey** [apollographql/apollo-client#1684]
All new commits to a PR stay orange because of the `coverage/coveralls` integration 😕

CC: @helfer

**Comment by helfer** [comment]
http://status.coveralls.io/

**Comment by MichaelDeBoey** [comment]
@helfer Still some problems according to the status page, but the PR's aren't orange anymore 🙂

**Comment by MichaelDeBoey** [comment]
@helfer Everything is operational again on coveralls 🙂
