### ISSUE TITLE
Writing partial objects to store with writeQuery

### ISSUE THREAD

**Issue by sondremare** [apollographql/apollo-client#1691]
Hi! This is more of a question than an issue. I am using apollo-client v1.2.2 and I have a list of files displayed in our app. 

Example query:
```
files {
   id
   name
   type
}
```

Lets say another users sends/inserts a new file from another instance of the app. But we only have the id to work with. 

I am trying to writeQuery with that id, thus inserting a partial file into the store. However, this results in the entire list disappearing. This is because apollo-client sets the property "isMissing" for this query.

This worked in the pre 1.x versions of apollo-client. Should I instead fetch the entire file from the backend and insert it into the store with a writeQuery, or is there a key option/configuration I a missing to make this work?

**Comment by helfer** [comment]
You can either refetch the entire file and insert it, or set the missing fields to `null` explicitly: `{ id: 123, name: null, type: null}`
