### ISSUE TITLE
Warn `writeFragment` should not be used to modify array fields

### ISSUE THREAD

**Issue by Dattaya** [apollographql/apollo-client#1695]
Right now if you try to add, remove, or rearrange items in an array field with `writeFragment`, for example:

```graphql
type Message {
  body: String
}

type Response {
  id: ID!
  code: Int!
  messages: [Message]  
}
```

```js
  addNewMessage() {
    const { sample: oldSample } = this.props.data;
    const messages = [...oldSample.messages, { body: 'Test', __typename: 'Message' }];    
    this.props.client.writeFragment({
      id: this.props.client.dataId(oldSample),
      fragment,
      data: { messages, __typename: 'Response' }
    });
  }
```

**Actual outcome:**
`this.props.data.sample` becomes undefined.

**Intended outcome:**
Apollo prints a warning in the console and recommends to use `writeQuery`?

**How to reproduce the issue:**
https://www.webpackbin.com/bins/-KjwIl8lUONyYfuGthTX

**Comment by cesarsolorzano** [comment]
@Dattaya  I think `messages` should have a selection of subfields in the fragment.

**Comment by Dattaya** [comment]
@cesarsolorzano, you're completely right, sorry for this useless issue.
