### ISSUE TITLE
Error - "Must provide document"

### ISSUE THREAD

**Issue by Siyfion** [apollographql/apollo-client#1696]
I have a mutation that when I fire with a small mutation, works perfectly fine. Once the size of the object being modified gets to a certain (unknown) size, it starts throwing `network errors` into the console and requests start failing with `400` codes.

The response given by the server is `{errors: [{message: "Must provide document"}]}`.

I'm pretty sure that this relates to the size of the data being sent/received with the mutation as here is an example of a successful request:

![screen shot 2017-05-12 at 13 05 14](https://cloud.githubusercontent.com/assets/338488/25997373/a8e50390-3713-11e7-90ed-36749460c5db.png)

And an unsuccessful request:

![screen shot 2017-05-12 at 13 05 17](https://cloud.githubusercontent.com/assets/338488/25997385/b129b1ea-3713-11e7-9a62-6de77cf3e5c3.png)

**Notice:** The sudden inclusion of the `content-length` header in the response of the failed request.

**Comment by helfer** [comment]
Hey @Siyfion I'm almost certain that you're getting this error because you're hitting some kind of request size limit on your server or proxy. Can you successfully send the same request with a client like curl or from GraphiQL?

**Comment by Siyfion** [comment]
It's a production server running on Galaxy, so the environment should be easy to replicate @helfer!

**Comment by Siyfion** [comment]
@helfer I've tried reproducing the issue locally with a development server, but when running GraphiQL the moment I paste in the Query Variables, it throws an error, after which I can no longer query anything at all... 😕 

![screen shot 2017-05-18 at 10 41 12](https://cloud.githubusercontent.com/assets/338488/26196386/b950e170-3bb6-11e7-912d-60470eb725f5.png)
![screen shot 2017-05-18 at 10 41 18](https://cloud.githubusercontent.com/assets/338488/26196387/ba9f7708-3bb6-11e7-9350-c43831eab615.png)

**Comment by Poincare** [comment]
This seems like it might be due to the fact that `GraphiQL` is trying to put the whole variables object in the URL and the variables object contains a large JSON object. Could you just `curl` your development server with a POST request?

**Comment by Siyfion** [comment]
@Poincare I get exactly the same issue with Postman (effectively curl):

<img width="1516" alt="screen shot 2017-05-24 at 15 47 26" src="https://cloud.githubusercontent.com/assets/338488/26409416/7050a7ee-4098-11e7-8631-7055f68f6f24.png">
<img width="1516" alt="screen shot 2017-05-24 at 15 48 08" src="https://cloud.githubusercontent.com/assets/338488/26409421/71ac9918-4098-11e7-97f6-66e8c2b8c57f.png">

When sending the following: https://gist.github.com/Siyfion/38bca3586b3745b93f1a5367a723caea

**Comment by helfer** [comment]
Hi @Siyfion, I'm going to close this because I'm 99% sure that it's not a client issue. Maybe the answer is the same as for #1233. If not, please file an issue on the server implementation that you use.

**Comment by Siyfion** [comment]
I've tried all of the CORS additions talked about in #1233, but none of them have worked for me at all. The server implementation is `graphql-server`, via `meteor-integration`.
