### ISSUE TITLE
infinite scrolling and updateQuery

### ISSUE THREAD

**Issue by ablbol** [apollographql/apollo-client#1698]
I am using "react-apollo": "^1.0.0".  I am experimenting with infinite scrolling.  So I have a query that is supposed to load the first 20 users and when I scroll down to the bottom of the page, I get the next 20 users. Every things works great.  But then I turn the network off, I log the error and networkStatus.  I get:
```
Network error: Failed to fetch
networkStatus 8
```
Seem fine so far but when I turn the network on again, I log the following:
```
Network error: Failed to fetch
networkStatus 7
```
That does not look right.  Also, after turning the network on, I run into an infinite loop and the component never gets updated.  
Any idea why I am getting this behavior?
Thanks

**Comment by ablbol** [comment]
I should have created this issue in  @react-apollo.  I am sorry, I don't know how to move the issue there.

**Comment by n1ru4l** [comment]
You will have to close this issue and open a new one in the react-apollo repo
