### ISSUE TITLE
A way to catch GraphQL Server errors?

### ISSUE THREAD

**Issue by Narzerus** [apollographql/apollo-client#1700]
I've looked everywhere for this but didn't manage to find an answer:

How are validation errors currently handled by the apollo-client? My graphql server sends a response to the client like this (on validation errors):

```js
{
  data: { userSignup: null },
  errors: [...]
}
```

I'm using an afterware to handle things like logging out when doing a request with an invalid/expired session token. But the errors get thrown as I don't see any place where I can catch them. 

It seems to me like there should be a way to catch validation errors coming from the server.

Even if I catch errors after a `mutate` call they still get thrown. (Even if I add a `.catch`)

<img width="722" alt="screen shot 2017-05-13 at 10 47 41 pm" src="https://cloud.githubusercontent.com/assets/1808674/26030614/36fc00fa-382e-11e7-8acf-36380df75d59.png">

**Comment by helfer** [comment]
Hi @Narzerus I'm not sure what you mean by catching the errors. You should be able handle it by adding a `catch` to your `mutate` call. If that doesn't work, could you provide a reproduction using react-apollo-error-template? That would help us figure out what's going on.

**Comment by Narzerus** [comment]
@helfer roger, I'll work on a repro case thanks!

**Comment by Narzerus** [comment]
So, I tested my app again today and it now catches errors. before I was somehow in a state in which catching errors would not prevent them from being thrown, but cannot repro now and everything works.

Sorry for the noise, closing this unless I can reproduce again.
