### ISSUE TITLE
Question: Is it possible to find object in the store by a non-id key

### ISSUE THREAD

**Issue by MichaelDeBoey** [apollographql/apollo-client#1705]
I know how to get the (default) value from `dataIdFromObject` (#1657), but I was wondering if it's possible to do something like this:
```js
const person = {
  __typename: 'Person',
  id: '1234',
};

client.dataIdFromObject(person); // 'Student:1234'
```

when my store has (their ID is unique in the union)
```js
Instructor:5678
Student:1234
```

with the following schema:
```js
union Person = Instructor | Student

type Instructor {
  id: Int
  name: String
  salary: Float
}

type Student {
  id: Int
  name: String
  major: String
}
```

It's again for using it for a `readFragment`, where I only have the id of the object.

CC: @helfer

**Comment by helfer** [comment]
Hey @MichaelDeBoey. Since you made that PR it should definitely be possible 😉 

The union is a concept in the schema. On the client you always have a specific instance, so either a Student or an Instructor. If that object has all the fields that your `dataIdFromObject` function needs, then you can indeed just run it through `client.dataIdFromObject` and get the id. Let me know if that somehow doesn't work.

**Comment by MichaelDeBoey** [comment]
@helfer I think you don't understand me that clear 😕
In my example I only have `1234` and I know I have a store with `Person`s (`Instructor`s or `Students`s), but I don't know the type of `1234`.
So what I was asking was if it's possible to just ask for a `Person` in `dataIdFromObject` instead of specifying the specific type (which I don't know)?

**Comment by MichaelDeBoey** [comment]
@helfer Any idea how I can do something like this?

**Comment by MichaelDeBoey** [comment]
@helfer Any idea how I can do something like this?

**Comment by stubailo** [comment]
```
const id = client.dataIdFromObject({
  __typename: 'Person',
  id: 1234,
});
const person = client.readFragment({
  id,
  fragment: personFragment,
});
```

Doesn't this "just work" right now? What's stopping this code from working?

**Comment by MichaelDeBoey** [comment]
@stubailo The problem is I don't have `Person`s in my store, I only have `Instructor`s and `Student`s.

**Comment by stubailo** [comment]
Have you tried passing "Instructor" as the __typename in the above code? Or are you saying you have the Id but don't know what type it is?

**Comment by MichaelDeBoey** [comment]
@stubailo Yeah that's indeed what I'm saying: I know `1234`, but I don't know if it's an `Instructor` or a `Student`, I only know it's a `Person`.

**Comment by stubailo** [comment]
That's interesting, I think the easiest solution would be to use an ID that doesn't have the type in it. Another solution is to scan the store for a matching ID but that would be linear in the number of objects. Haha maybe one day we will have an index for arbitrary lookups by fields other than the generated ID!

**Comment by MichaelDeBoey** [comment]
I'm now manually checking if it's an `Instructor` and if the result is `null` I try if it's a `Student`, but that's a bit cumbersome I think. 😕
Especially when you have a type that has like 7 subtypes for instance.

```js
const possiblePersonTypes = [
  "Instructor",
  "Student",
];
let personIsFound = false;

possiblePersonTypes.forEach(possiblePersonType => {
  if(!personIsFound) {
    const id = client.dataIdFromObject({
      __typename: possiblePersonType,
      id: 1234,
    });
    const person = client.readFragment({
      id,
      fragment: personFragment,
    });
    
    personIsFound = person !== null;
  }
});
```
And because we _know_ the scheme, we _could_ know the possible subtype I think?

Or is there another best practice for this?

**Comment by stubailo** [comment]
> And because we know the schema, we could know the possible subtype I think?

Unfortunately I don't think anything will help you determine the type from an ID without actually looking at the data.

I think the easiest thing to do is to check the store, but that will be linear in the size of the store:

```
const state = client.store.getState();

const theId = '1234';
let desiredId;
for (key in state.apollo) {
  if (state.apollo[key].id === theId) {
    desiredId = client.dataIdFromObject(state.apollo[key]);
    break;
  }
}

// Now we have desiredId or it's undefined
```

Basically the fundamental limitation is that the ID generated from `dataIdFromObject` is the only way to access a particular object without accessing the store. Allowing something more complex would turn the store into a database essentially.

I agree that iterating over possible types will also work, which might be easy if you're using an `IntrospectionFragmentMatcher`.

But if you want to access objects by ID directly and the IDs are unique, I think not adding the `__typename` to the ID is probably the best option, unless some of your IDs are not unique. Are they?

**Comment by MichaelDeBoey** [comment]
The IDs are (mostly, but unfortunately not always 😕) unique in `Person`, but they're not in the whole store.

I'm using an `IntrospectionFragmentMatcher`, so the `apollo-client` knows the whole schema, that's why I was thinking there should be some way to do what I want and not needing to make the iteration myself for every Union type I'd like to do this for.

**Comment by stubailo** [comment]
Can you show me the snippet of how you're using the `IntrospectionFragmentMatcher`?

**Comment by MichaelDeBoey** [comment]
@stubailo I just queried the server like explained in [the docs](http://dev.apollodata.com/react/initialization.html#fragment-matcher).

**Comment by MichaelDeBoey** [comment]
@stubailo You have any idea yet?

**Comment by MasonD** [comment]
I feel bad commenting on a stale issue, but this never received a satisfying solution and yet the solution is actually rather simple. 

You can solve this issue by providing your own dataIdFromObject, which for types in unions replaces `__typename` with the union's name. In the example provided above, this could be something like:
```js
function dataIdFromObject(o) {
  if (o.__typename === 'Instructor' || o.__typename === 'Student') {
    return defaultDataObjectByID({ ...o, __typename: 'Person' });
  }
  return defaultDataObjectByID(o);
}
```
As such, the example student with id `1234` would have cache key `Person:1234` and can be easily found via `client.readFragment(dataIdFromObject({ __typename: 'Person', id: 1234 })` without needing to know whether it's a Student or an Instructor.

This `dataIdFromObject` function could obviously be built automatically from a description of the union types, but that exercise is left to the reader.

**Comment by anlauren** [comment]
I see how it is a bit of a problem for a Union, the actual type inside can be completely different.
There's no guarantee that `Student` or `Instructor` are actually going to have any valid sub-selection of fields

But it should be easy to add somehow to apollo the possibility of querying on `Interface` the fields that are in this interface. 

For unions, it would require the `fragment` to change depending on the type we want to query, but _in theory_ it should be doable to parse the graphql `fragment` and try for the different options asked

I don't really know the inside of Apollo but i feel the pieces are around to do a even easier cache management

here is what i've quickly coded:

```js
import introspectionQueryResultData from "../../fragmentTypes.json";

const introspectionMap = introspectionQueryResultData.__schema.types.reduce((results, type) => {
    if (type.kind === "INTERFACE") {
        results[type.name] = type.possibleTypes;
    }
    return results;
}, {});

// works with Interface fragments!
export default function customReadFragment(client, fragment, id) {
    const baseName = fragment.definitions[0].typeCondition.name.value;
    const possibleTypes = introspectionMap[baseName];
    if (possibleTypes) {
        for (const possibleType of possibleTypes) {
            const mixedId = `${possibleType.name}:${id}`;
            const result = client.readFragment({
                id: mixedId,
                fragment,
            });
            if (result !== null) {
                return result;
            }
        }
        return null;
    }
    return client.readFragment({
        id: `${baseName}:${id}`,
        fragment,
    });
}

```
It is then quite straight forward to use:
```js
const fragment = gql`
   fragment MyPerson on PersonInterface {
      id
      name
      __typename
   }
`;
const previous = customReadFragment(
     client,
     fragment,
     personId,
);
console.log(previous);
// {id: 1, name: "roger",  __typename: "Student"}
```

Obviously we could extend that function way further by using a custom function to get the id of the object, etc but there might be something to explore
