### ISSUE TITLE
Mutation after being offline

### ISSUE THREAD

**Issue by konstantin-hatvan** [apollographql/apollo-client#1707]
**Intended outcome:**
When initiating a refetch offline and failing, I expect other mutations to work after going online again even if i do not refetch the failed query.

**Actual outcome:**
When offline and failing to refetch, if you go online and try to call another mutation without having refetched the failed query apollo fails producing network error "Network request failed".

**How to reproduce the issue:**
Refetch while being offline. Then call other mutation without refetching the failed query.

**A little bit more detail**
I am developing a react native application. I use a tab navigation. When I refetch while being offline, the query fails (as expected) and an error screen is shown. Then I switch to another tab. Now, when I call any other mutation the network error occurs. Interestingly, the mutation still executes.

**Comment by Poincare** [comment]
If I'm understanding correctly, this is the sequence of events:

* Go offline
* Attempt to refetch a query
* Receive failed refetch from the network layer
* Go online
* Attempt to fire a mutation
* Receive network failure from network layer

I don't believe this is intended behavior. Could you produce the error that Apollo Client produces when this happens?

**Comment by TheInquisitiveNerd** [comment]
That is the exact scenario.

Here is the error screen:

![screenshot_20170521-085301](https://cloud.githubusercontent.com/assets/16699575/26281831/46110eac-3e03-11e7-848a-ecf1059b5ff5.png)

**Comment by TheInquisitiveNerd** [comment]
Maybe it is also important to note that as long as I do not refetch the query successfully all mutations result in this error. When I refetch the query successfully everything works just fine.

Another observation is that the mutations are still executed. Nevertheless the error is shown.

**Comment by jurajkrivda** [comment]
@TheInquisitiveNerd  try to use { queryDeduplication: false } in ApolloClient constructor.

**Comment by helfer** [comment]
Hi @TheInquisitiveNerd, would you be able to provide a reproduction for this using the [error template](https://github.com/apollographql/react-apollo-error-template)?
