### ISSUE TITLE
Question: readQuery when query root is a parameterised function 

### ISSUE THREAD

**Issue by serle** [apollographql/apollo-client#1709]
I have query root that is parameterized by an input object, with quite a few properties. It would seem that this is converted into the property name string in the client side cache. As a result, I am struggling to compose a valid query for my readQuery function as I can't get the root field name to conform to the gql query syntax. Is there an alias that can be used for the root object in the local cache or what other approach should be used?

**Comment by fc** [comment]
If I'm understanding you correctly, ran into a similar issue.

Ended up setting a unique id to be returned from the query since apollo will use the id to map to the cache.

You may also need to use a custom resolver to make sure those ids are mapped correctly:
http://dev.apollodata.com/react/cache-updates.html#cacheRedirect

**Comment by serle** [comment]
Thanks @fc.

Yes that would be my next option to create an artificial ID and use the readFragment function instead. 

I do somehow feel that the root cause of all this is that in the Apollo client is ignoring the fact that I put a field alias on the original root field, when constructing its local cache root key. For a bit more background, the original query is pulling out a tree from a much larger server graph, in a way that is user/context specific. This client-side tree (query result) represents a filtered view of the world from the client perspective. From that point on I would prefer to hide all traces of the root query input parameters from local interactions with the client side cache.
