### ISSUE TITLE
Queries are not cleared in resetStore

### ISSUE THREAD

**Issue by 20matan** [apollographql/apollo-client#1710]
Hey
when i use client.resetStore(), then the queries in the state of the store are not cleared
The problem it's creating, is after a user is logging out and then log with another user,  the queries are not re-fetched so no data is fetched from the server for the new user...
adding an image from debug
![pasted image at 2017_05_18 08_37 pm](https://cloud.githubusercontent.com/assets/10909504/26216525/1e882d7c-3c0d-11e7-8c4e-fb6fe95c1a55.png)

**Comment by cesarsolorzano** [comment]
Could this be related to #1552? (not an issue, but a confusion about what `resetStore` does)

**Comment by 20matan** [comment]
@cesarsolorzano  I dont think so, because the problem they described there is that resetStore re-fetched queries. 
I dont have a problem with the re-fetch on calling resetStore, I have a problem that it doesnt clear the queries object (after the refetch), so if user is logged out and then log in with another user data (other id), it doesnt fetch the new data, because those queries are cached, but with the old user id.

**Comment by Poincare** [comment]
When `resetStore` is run, the queries will refetch out of the cache, they will not be emptied out of the cache. This is to make sure that the cache doesn't end up in an inconsistent state.

When your new user logs in, do you still have active queries on your page from the older user with the old user's user id or equivalent? If that's the case, then `resetStore` will not get rid of that information, only refetch it into the store.

**Comment by jurajkrivda** [comment]
Hi you should use redux to keep the user id and when user will log off destroy this information and show login page to the user. Then you can reset the store but you should avoid making secured queries again using skip function.

**Comment by jinxac** [comment]
@jurajkrivda would this scale for a scenario where you have list of items specific to a user and a detail view which each item?
