### ISSUE TITLE
Feature: Apollo Fuse

### ISSUE THREAD

**Issue by changalberto** [apollographql/apollo-client#1713]
Are there any plans to create a fuse package integration?
https://www.fusetools.com/

**Comment by smolinari** [comment]
The way I see it, that would be something the fuse team would need to do. 

Scott

**Comment by changalberto** [comment]
@smolinari I think that Apollo team should take the initiative to collaborate with the fuse team to make this happen since all of their other framework integration libraries are somewhat Apollo "offical" libraries. But I made a request to the fuse team [here](https://www.fusetools.com/community/forums/general/graph_ql_support?page=1&highlight=dd45c804-48ed-4d40-bbfb-d24a11062e0b#post-dd45c804-48ed-4d40-bbfb-d24a11062e0b) anyway. Let's see what they say.

**Comment by helfer** [comment]
Hey @changalberto, that's a great idea! However, as @smolinari pointed out, this is something the Fuse team should look into. We're definitely happy to help if there's anything that needs to be done on our end.

**Comment by stubailo** [comment]
Yeah actually all of the framework integrations are primarily community maintained, so it's always up to someone to take the first step for a new integration!
