### ISSUE TITLE
Question: optimistic UI with subscriptions.

### ISSUE THREAD

**Issue by duvet86** [apollographql/apollo-client#1716]
Does optimistic UI make sense with subscriptions?
I'm calling a mutation with a optimistic response that adds an item to the list. The optimistic update gets handled by the update option but it gets also triggered by the subscribeToMore function resulting in a duplicate key exception.
The workaround that I'm currently using is to filter the item list in the update function in order to avoid updating the store if the element already exists.
Am I doing it right or there is a better solution?

Cheers

**Comment by smolinari** [comment]
Interesting problem. I can't help you, but I'd like to know the answer, thus my comment. 😄 

Scott

**Comment by abhiaiyer91** [comment]
@duvet86 I think it depends on your UI and the latency from the sub. But i do think it makes sense :)

**Comment by helfer** [comment]
Hi @duvet86 I think that's the best solution we have at the moment. We actually do the same thing for the comments subscription in GitHunt.

**Comment by ins429** [comment]
Well I was hoping if there's a new technique around this, please share if anyone found another neat way to solve this issue.

**Comment by smolinari** [comment]
I believe with the upcoming Apollo-Client 2.5 and the introduction of [**link-state**](https://www.apollographql.com/docs/link/links/state.html) into [**the core of Apollo Client**](https://github.com/apollographql/apollo-client/pull/4155) the need for Optimistic updates will be fulfilled. Updates to your state via mutations will also reactively update the usage of that state in other parts of your application. At least, that is the expectation I would have on this new and very major change. There is, however, a bug currently with "refetchQuery" on mutations, which negates the updating from working properly. I hope they get it fixed soon and 2.5 will be released officially. 😃 

Scott
