### ISSUE TITLE
Remove the isomorphic-fetch dependency

### ISSUE THREAD

**Issue by gajus** [apollographql/apollo-client#1718]
It is not the responsibility of a library to polyfill browser features.

`isomorphic-fetch` is now being pulled into a bundle for no good reason.

Remove the `isomorphic-fetch` dependency and document that user needs to polyfill Fetch if the target environment does not support Fetch API (or recommend to use https://polyfill.io/v2/docs/).

**Comment by cesarsolorzano** [comment]
@gajus Isn't this the same issue you described in #645?

**Comment by gajus** [comment]
oh, lol. I forgot about it by now.

Yes it is.

**Comment by pckhoi** [comment]
`isomorphic-fetch` is still being required for no good reason. I see that recent releases of `apollo-client` no longer require `isomorphic-fetch`, yet it require `apollo-link` which require `apollo-fetch` which require `isomorphic-fetch`. Ultimately `apollo-client` still depend on `isomorphic-fetch`. I still can't get this to work in React Native running into `Can't find variable: self` error.

**Comment by gajus** [comment]
Patience.
