### ISSUE TITLE
new data from network dont update the props.data

### ISSUE THREAD

**Issue by GalFriD** [apollographql/apollo-client#1728]
I have a container which wrapped in graphql 

```
import { graphql } from 'react-apollo';
const someQuery="....some query here'

class SomeContainer extends React.Component{
//....some code here
componentDidMount(){
    this.props.data.refetch();
  }
//....some more code
}

const options = {
   fetchPolicy: 'network-only'
};

graphql(someQuery, options)(SomeContainer)
```

and when I invkoe did mount function i watch the network in chrome dev tool and i see that i got new data,  but when i watch the props.data, i see the old data i had before, and the page did not refreshed.

any ideas?
thanks

**Comment by helfer** [comment]
Hi @GalFriD if fetchPolicy is `network-only`, you should not have to refetch manually. Please try it without that, and if it still doesn't work, please open a new issue and provide a reproduction. Thanks!
