### ISSUE TITLE
writeFragment: Missing field __typename

### ISSUE THREAD

**Issue by SachaG** [apollographql/apollo-client#1733]
I'm trying to use `writeFragment` but running into the following issues: 

![https://d3vv6lp55qjaqc.cloudfront.net/items/2f1l0M0s3x2c3u270W0a/Screen%20Shot%202017-05-24%20at%2014.28.35.png?X-CloudApp-Visitor-Id=4c115ae96a1293116cf3f7a8f20e2c24&v=827959ce](https://d3vv6lp55qjaqc.cloudfront.net/items/2f1l0M0s3x2c3u270W0a/Screen%20Shot%202017-05-24%20at%2014.28.35.png?X-CloudApp-Visitor-Id=4c115ae96a1293116cf3f7a8f20e2c24&v=827959ce)

My fragment does have `__typename` though:

```js
client.writeFragment({
        id: job._id,
        fragment: gql`
          fragment JobsStatusUpdate on Job {
            __typename
            status
          }
        `,
        data: {
          status: 2
        },
      });
```

And I also have `addTypename: true` in my ApolloClient options. Any idea what's going on?

**Comment by helfer** [comment]
The data you're writing is missing `__typename`. Just change it to this:

```
client.writeFragment({
        id: job._id,
        fragment: gql`
          fragment JobsStatusUpdate on Job {
            __typename
            status
          }
        `,
        data: {
          status: 2,
          __typename: 'Job',
        },
      });
```

**Comment by SachaG** [comment]
Oh of course. For some reason I didn't realize you had to specify `__typename` in the `data`, that seems obvious in retrospect. Thanks!

**Comment by omonk** [comment]
Can this be added to the docs example?

https://www.apollographql.com/docs/react/advanced/caching.html#writequery-and-writefragment

**Comment by zenVentzi** [comment]
In case somebody comes here and has nested fragments, make sure you have the corresponding nested __typename fields inside the data field.
