### ISSUE TITLE
writeResultToStore cannot create error when using graphql-tag webpack loader

### ISSUE THREAD

**Issue by jacobk** [apollographql/apollo-client#1735]
**Intended outcome:**

Errors thrown in `writeResultToStore` should be propagated with relevant information added

**Actual outcome:**

`Cannot ready property 'body' of undefined` error is thrown instead

![screen shot 2017-05-24 at 10 29 45](https://cloud.githubusercontent.com/assets/497477/26394130/3b0c0bae-406c-11e7-9aa3-00808ed15013.png)

**How to reproduce the issue:**

Trigger writeResultToStore error when using graphql-tag webpack loaded queries.

Root cause:
![screen shot 2017-05-24 at 10 29 11](https://cloud.githubusercontent.com/assets/497477/26394366/06fceabc-406d-11e7-8ccb-78428232d6f5.png)

Actual error thrown:
![pasted image at 2017_05_24 10_31 am](https://cloud.githubusercontent.com/assets/497477/26394382/1258f3b0-406d-11e7-846f-917a0ff6f81c.png)

**Comment by helfer** [comment]
Hi @jacobk can you send a PR to fix this? I think all you'd have to do is make sure we don't access an undefined field when putting together the error message.

**Comment by jacobk** [comment]
@helfer the issue is fixed by https://github.com/apollographql/graphql-tag/pull/65 
I tried with `graphql-tag@2.1.0` and it works like expected.

What's the formal constraints on what the query documents passed to apollo-client should look like?

I'll be happy to open a PR to simply not concat the source when not present if you think it makes sense.

**Comment by helfer** [comment]
Hi @jacobk thanks for helping with this! We fixed it in #1738 🙂
