### ISSUE TITLE
Enhancement: Expose BaseNetworkInterface

### ISSUE THREAD

**Issue by gauravmk** [apollographql/apollo-client#1736]
"You would need a custom networkInterface" is a phrase I've seen a bunch in the `react-apollo` channel. To be able to properly do that you'd want to create 

`MyCustomNetworkInterface extends BaseNetworkInterface`

but apollo-client doesn't export BaseNetworkInterface. Exposing that means that it's a lot easier for people to write custom networkInterfaces for their specific networking needs.

**Comment by Poincare** [comment]
This seems like a fine thing to do but out of curiosity: why not just implement the `NetworkInteface` interface? What benefit does the `BaseNetworkInterface` currently provide?

**Comment by gauravmk** [comment]
Oh good call, didn't realize there were both of those and was just looking at `HTTPBatchedNetworkInterface extends BaseNetworkInterface`. This probably handles what I want to do, I'll give it a try
