### ISSUE TITLE
[Error] Mutation : the application attempted to write an object with no provided id but the store already contains an id

### ISSUE THREAD

**Issue by xavierlefevre** [apollographql/apollo-client#1737]
Hello guys,

Sorry it might be a trivial problem but I'm stuck, in my Apollo testing and learning process, by an error my mutation generates and I'm coming down to you to help me.

**Intended outcome:**

Mutating by adding a new friend to a user and updating the state with the newly added friend.

```
import { graphql, compose } from 'react-apollo';
import { connect } from 'react-redux';
import update from 'immutability-helper';

...

const addFriend = graphql(ADD_FRIEND_MUTATION, {
  props: ({ mutate }) => ({
    addFriend: username =>
      mutate({
        variables: { username },
        updateQueries: {
          user: (previousResult, { mutationResult }) => {
            const newFriend = mutationResult.data.addFriend;
            return update(previousResult, {
              user: {
                friends: {
                  $push: [newFriend],
                },
              },
            });
          },
        },
      }),
  }),
});

...

export default compose(connect(mapStateToProps, mapDispatchToProps), userQuery, addFriend)(People);
```

**Actual outcome:**

The mutation works db-wise, but the client does not want to update the app/redux state.

Weirdly the `updateQueries` is called twice. The first time with the "right" previousResult object, the second time with a much smaller object without `id`. Then the error pops. After refresh of the app, the friend is well added.

Here is the error : `the application attempted to write an object with no provided id but the store already contains an id of User:18 for this object.`

<img width="631" alt="screen shot 2017-05-24 at 23 09 40" src="https://cloud.githubusercontent.com/assets/14938214/26425697/15a148a6-40d6-11e7-8afe-5a6929bee3a4.png">

**How to reproduce the issue:**

Directly from my little test project repo : https://github.com/xavierlefevre/chat

Here is the react container with the front mutation : https://github.com/xavierlefevre/chat/blob/master/client/src/pages/people/people.container.js

In order to install the project :
- Back
  - cd chat/server
  - yarn install
  - yarn start
- Front
  - cd chat/client
  - yarn install
  - react-native run-ios
  - login with a user logged by the express server in your terminal
  - go to the tab "people"
  - click on the top right "plus"
  - add a user, once again output by the express server in your terminal
  - witness the error

Hope my issue is filled correctly, and thanks a bunch for the help.

**Comment by helfer** [comment]
Hi @xavierlefevre. The error message indicates that there's no id generated for the new user. I'm not sure why there are two users, but it would be really helpful to have a simpler reproduction using the [error template](https://github.com/apollographql/react-apollo-error-template). A minimal reproduction helps us isolate the problem faster, and it would help you figure out if you were doing something wrong.

**Comment by xavierlefevre** [comment]
@helfer I'll try and spend some time this beg of week to find a way to reproduce this, hoping it is easily reproducible. I'll get back at you fast. And thanks for the fast answer.

**Comment by xavierlefevre** [comment]
@helfer I did not have time yet to reproduce the issue on a simpler example.

However I have a question, how does `updateQueries` work exactly ? Because I do not understand why after **1** mutation, the function is called several times, where one time a previous result misses properties, among which the `id`. See the attached screenshot :

<img width="1118" alt="screen shot 2017-05-30 at 14 27 50" src="https://cloud.githubusercontent.com/assets/14938214/26583360/350db5f8-4545-11e7-9e73-3fefcf46ea98.png">

Do I have any saying in the object sent back by `updateQueries` `previousResult` ? It also looks like my normal query for getting the data in the page in the first placed, is also invoked right at the beggining of the mutation.

**Comment by xavierlefevre** [comment]
@helfer 

I fixed the issue. Here is my commit : https://github.com/xavierlefevre/chat/commit/11c84529c5fc16168470109f07ab83cbe15ca181

The thing I understood :
- I query `USER_QUERY` when arriving on the app, retrieving many information for this user as id, username, friends, groups etc.
- In the page of this issue, I then make a `FRIEND_QUERY` that only retrieves the friends of this same user
- Once the mutation to add a friend to the user completes, I don't know why, but it triggers twice, once with a full user in `previousResult` (id, username, etc.), and a second time with a user only matching the `FRIEND_QUERY` (only friends).

So I decided to re-query `USER_QUERY` for this page as well, in order to make sure it has the same object shape. But I am not sure why yet, I needed to do that.

If things are clear and you would have a hint for me, it would be amazing.

Thanks anyhow !

**Comment by helfer** [comment]
Ah, I think I see the problem now. Your FRIENDS_QUERY doesn't ask for the user's id. That way Apollo Client cannot calculate a unique id for the object, and you get the error message that you saw. I'm glad you figured out a solution on your own though! 🙂

**Comment by developdeez** [comment]
I've got the same error but it seems apollo is trying to make it's own id. It also calls it again. I'm not sure what to do... :(

```
$ROOT_QUERY.getNotifications({"limit":5}):
notifications: Array(2)
0:
generated: false
id: "NotificationType:5c1c5ff2ca6bab5d585dccd4"
type: "id"
typename: "NotificationType"
__proto__: Object
1: {type: "id", generated: true, id: "$ROOT_QUERY.getNotifications({"limit":5}).notifications.1", typename: undefined}
length: 2
__proto__: Array(0)
total: 2
unseen: 1
__typename: "NotficationListType"
__proto__: Object
$ROOT_QUERY.getNotifications({"limit":5}).notifications.1:
read: true
__proto__: Object
```
