### ISSUE TITLE
Error 400 - Must provide document - when fetching

### ISSUE THREAD

**Issue by WaSa42** [apollographql/apollo-client#1740]
**Intended outcome:**

I'm trying to fetch data with a simple query in a React component wrapper:
``` javascript
import React from 'react';
import { gql, graphql } from 'react-apollo';

const TeamsDashboardComponent = () => ( ... );

const query = gql`query teamsDashboard {teams {name logo}}`;
const TeamsDashboard = graphql(query)(TeamsDashboardComponent);

export default TeamsDashboard;
```

```javascript
import { ApolloClient, createNetworkInterface } from 'react-apollo';
import settings from './settings';

const networkInterface = createNetworkInterface({
    uri: settings.server + '/graphql',
    opts: { mode: 'no-cors' }
});

networkInterface.use([{
    applyMiddleware(req, next) {
        if (!req.options.headers) {
            req.options.headers = {};  // Create the header object if needed.
        }
        // get the authentication token from local storage if it exists
        const token = localStorage.getItem('reduxPersist:authentication').token;
        req.options.headers.authorization = token ? `Bearer ${token}` : null;
        next();
    }
}]);

export const client = new ApolloClient({
    networkInterface,
});
```

And here are my resolvers, types etc., on an Express server:
``` javascript
export const team = (root, {_id}) => {};
export const teams = () =>  {};
``` 

``` javascript
export default `
    type Team {
        _id: ID!
        name: String!
        logo: String
    }
`;
``` 

``` javascript
import {makeExecutableSchema} from 'graphql-tools'
import resolvers from './resolvers';
import typeDefs from './typeDefs';

export default makeExecutableSchema({
    printErrors: true,
    resolvers,
    typeDefs
});
``` 

``` javascript
import schema from './graphql/schema';
app.use('/graphql', graphqlExpress({ schema }));
``` 

So, when I enter `http://localhost:5076/graphql?query={teams}`, the result must be `{"data":{"teams":null}}`.

**Actual outcome:**

This GET request is working but when Apollo try to fetch with a POST request, the response is a `400 Bad Request` error with the message `Must provide document`.

So I tried to reproduce the POST request on Postman and it works:
![Postman](http://i.imgur.com/BkaAiQ2.png)

Did I make something wrong on the client ? I don't understand the message and the only thing I found on google was to disable CORS, wich I did.

**Comment by WaSa42** [comment]
This is basicaly the issue here: Error - "Must provide document" #1696 

But I did reproduce with Postman and it works fine. I hope getting more informations about the size limit you thought it might be the problem.

Thank you

**Comment by cesarsolorzano** [comment]
This is an error on the server and isn't related apollo-client - for a solution see: #1233
