### ISSUE TITLE
Fragments don't seem to work for interfaces (despite IntrospectionFragmentMatcher)

### ISSUE THREAD

**Issue by richburdon** [apollographql/apollo-client#1741]
**Intended outcome:**

Apollo Client 1.3.0

I have a simple schema (to test this issue):
~~~~
interface Item { id title }
type Task implements Item { id title status }
~~~~

And a simple query using fragments:
~~~~
query SearchQuery($type: String!) {
  search(type: $type) {
    items {
      ...TaskFragment
    }
  }
}

fragment TaskFragment on Task {
  ...ItemFragment
  status
}

fragment ItemFragment on Item {  
  id
  title
}
~~~~
In GraphiQL the correct list of Task objects are returned with each of the `{ __typename id title status}` fields.

NOTE: the following works (so it seems to be related to defining fragments on the interface itself, not implementing types).
~~~~
query SearchQuery($type: String!) {
  search(type: $type) {
    items {
      ...TaskFragment
    }
  }
}

fragment TaskFragment on Task {
  id
  title
  status
}
~~~~

**Actual outcome:**
In my stripped down Apollo unit test the exact same query returns items with only the `{ __typename status }` fields.

I have my `IntrospectionFragmentMatcher` set-up correctly.

**How to reproduce the issue:**

Call the query above.
````
client.query({
  query: SearchQuery,
  variables: {
     type: 'Task'
  }
});
````

@cesarsolorzano, @helfer I think this relates the the bug I filed a couple of days ago (https://github.com/apollographql/apollo-client/issues/1708); I've spent some time trying to strip this down to a small test (although different errors here).

**Comment by richburdon** [comment]
Related to https://github.com/apollographql/apollo-client/issues/1719

However I am defining a  `IntrospectionFragmentMatcher` and still have the problem.

~~~~
  return new IntrospectionFragmentMatcher({
    introspectionQueryResultData: {
      __schema: {
        types: [
          {
            kind: 'INTERFACE',
            name: 'Item',
            possibleTypes: _.map(itemTypes, type => ({ name: type }))
          }
        ]
      }
    }
  });
~~~~

**Comment by cesarsolorzano** [comment]
@richburdon I think I know what's going here. Could you change your `TaskFragment` to:
```
fragment TaskFragment on Task {
  status
  ...ItemFragment
}
```

**Comment by richburdon** [comment]
Thanks for the suggestions.

I think I've been hitting a perfect storm of issues: I have a monorepo with multiple GQL dependent modules. I have things working now, so the problem has been some combination of:

- different graphql versions used across pacakges
- `jest` and `babel-node` caching `.graphql` files (so updates to my schema defs were being ignored).

And, I think these issues may have obfuscated the main culprit: i.e., in my snippet above I'm generating the `IntrospectionFragmentMatcher` from the schema via.

````
    possibleTypes = possibleTypes: _.map(_.get(schema, '_implementations.Item'), type => ({ name: type }))
````
Which should be:
````
    possibleTypes = possibleTypes: _.map(_.get(schema, '_implementations.Item'), type => ({ name: String(type) }))
````
Since the the array is a list of objects (which look like strings when logged to console).

Thanks again!
