### ISSUE TITLE
How to increase timeout from 2 minutes to N Minutes?

### ISSUE THREAD

**Issue by tomitrescak** [apollographql/apollo-client#1751]
In my application I make queries to 3rd party server that can last more then 2 minutes.
Currently, after 2 minutes Apollo closes connection and throws "Request failed to fetch".
Is there any way for me to increase this timeout to N minutes?

It seems that node has [this timeout by default](https://github.com/nodejs/node-v0.x-archive/issues/3460), I'm just not sure where can I set this for the client?

**Comment by tomitrescak** [comment]
Ok, I managed to solve it in express configuration:

```js
const app = express();
...
const server = app.listen(expressPort, () => {
...
});
server(10 * 60 * 1000); // 10 * 60 seconds * 1000 msecs = 10 minutes
```

**Comment by erwinwahyura** [comment]
@tomitrescak do i need to add settimeout in nodejs rather than in api call ? or if the api call the server just allow 2 minutes fetching times ? just need a clarity

**Comment by naishe** [comment]
> @tomitrescak do i need to add settimeout in nodejs rather than in api call ? or if the api call the server just allow 2 minutes fetching times ? just need a clarity

yes, this need to be set on the server side if your client is getting timeout.

**Comment by dharkness** [comment]
I've verified that my server allows queries to run for 10 minutes by using `set_time_limit(10 * 60)` in PHP when I send queries directly from the browser, but the Apollo Boost client still times out after 2 minutes. Is there really no timeout in Apollo or Fetch? Where else should I look to solve this?

**Comment by sanketCactus** [comment]
> Ok, I managed to solve it in express configuration:
> 
> ```js
> const app = express();
> ...
> const server = app.listen(expressPort, () => {
> ...
> });
> server.setTimeout(10 * 60 * 1000); // 10 * 60 seconds * 1000 msecs = 10 minutes
> ```

Any idea how to achieve the same thing  with apollo-server-lambda setup? to increase or decrease the timeout ?
