### ISSUE TITLE
HTTPFetchNetworkInterface afterwares are not called on exception

### ISSUE THREAD

**Issue by buholzer** [apollographql/apollo-client#1761]
**Intended outcome:**
A registered afterware should be called even doe the query execution had an error.

When calling a graphql server, the request gets a cors error (No 'Access-Control-Allow-Origin' header is present) due to an authentication failure. The browser throws an error that can be catched in the promise chain and the afterware should be executed. 

**Actual outcome:**
The afterware is not executed since the promise chain is not catching the error.
https://github.com/apollographql/apollo-client/blob/master/src/transport/networkInterface.ts#L219

**Comment by helfer** [comment]
Hi @buholzer. Thanks for filing an issue. It should be pretty easy to fix this by adding a `catch` right after it and calling the afterware there as well. Could you make a PR please? 🙏
