### ISSUE TITLE
Improving the documentation mutation update option

### ISSUE THREAD

**Issue by developersoul** [apollographql/apollo-client#1767]
Hi everyone, firsts thanks for the amazing client. Second after half of a day trying to update the cache after a mutation and seeing the examples, I can say the more examples are needed, in the documentation. Like the next one with variables...

**Example:**

```javascript
const getTodosQuery = gql`
query getTodos($userId: Int!) {
  todos(user_id: $userId) {
    id
    title
    content
  }
}
`;
```

```javascript
const createTodoMutation = gql`
mutation createTodo($title: String!, $content: String!) {
  createTodo(title: $title, content: $content) {
    id
    title
   content
  }
}
`;
```

And to make works readQuery function we need to pass the variables. That is something that is not mention on the docs and get me confuse and get me and error that isn't so clear... so to make works the query, getTodosQuery in the example below we need to pass the variables with the userId. 

```javascript
client.mutate({
  mutation: createTodoMutation,
  variables: {
    title: "todo title",
   content: "todo content"
  },
  update: (proxy, { data: { createTodo } }) => {
    //we need to use the same variables that the query...
    const data = proxy.readQuery({ query: TodoAppQuery, variables: {userId: 1} });
    const todos = [...data.todos, createTodo];
    proxy.writeQuery({ query: getTodosQuery, variables: {userId: 1} data: todos });
  },
});
```

I hope make me understand and in the future this help someone, I lose something find a solution.

**Comment by helfer** [comment]
Hi @developersoul. I think you're right, we definitely need more examples there. I think this is an issue with the docs though, so can you make a PR there? Here's the link to the repo: https://github.com/apollographql/react-docs
