### ISSUE TITLE
proxy.readFragment with missing fragment option fails with "Cannot read property 'definitions' of undefined"

### ISSUE THREAD

**Issue by baerrach** [apollographql/apollo-client#1771]
**Intended outcome:**

I was fiddling with options.update to update the cache after a mutation.
Initially I tried readQuery, but the bit of data I needed to modify is not at the root node.
So after reading more I tried readFragment.
However I neglected to change the option name from **query** to **fragment**, and instead of getting an error indicating the fragment was missing I essentially get a null pointer exception.

**Actual outcome:**

An error is thrown with the message 'Cannot read property \'definitions\' of undefined'

**How to reproduce the issue:**
```
  graphql(someMutatingQuery, {
    options: {
      update: (proxy, { data: { result} }) => {
        const options = {
          id: `<Type>:${result.parent.id}`,
          // Note query below should be fragment
          query: fragmentToUseAsQuery,
        };
        const data = proxy.readFragment(options);
      },
    },
  }),
```

**Comment by helfer** [comment]
Hi @baerrach, thanks for filing an issue! Is that a complete code sample? Because I don't see any `readQuery` or `readFragment` in there.

That said, I wouldn't be surprised if this was an issue, but it should be very easy to fix. Do you want to make a PR for that? We would really appreciate it! 🙂

**Comment by baerrach** [comment]
Sure its PR #1772

**Comment by baerrach** [comment]
I've updated the code example, that will teach me to create an issue when its bed time :P
