### ISSUE TITLE
Easy example for custom network interface?

### ISSUE THREAD

**Issue by kbrandwijk** [apollographql/apollo-client#1774]
I'm looking at a way to modify a query or mutation in the networkinterface. It doesn't seem possible in midleware functions, and the documentation describes it as a use case for a custom network interface. Are there any easy examples available for creating a custom network interface to do this?

**Comment by n1ru4l** [comment]
I did this the other day https://gist.github.com/n1ru4l/cb24401592417bda7fad989d416f0b9f
I hope it helps you :)

**Comment by helfer** [comment]
@kbrandwijk we don't have any special documentation for that, but we're working on a new fetcher for Apollo that is more composable. We'll have docs on that kind of thing there. In the meantime, I think you can use @n1ru4l 's Gist as a template! 🙂
