### ISSUE TITLE
createBatchingNetworkInterface causing issues with client.resetStore()

### ISSUE THREAD

**Issue by srtucker22** [apollographql/apollo-client#1780]
When using regular `createNetworkInterface`, if I `skip` all my active queries (I'm using `react-apollo`) and run `client.resetStore()`, everything works fine.

Switching over to `createBatchingNetworkInterface`, running the same code causes:

```
Unhandled Promise Rejection (id: 0):
Error: Network error: Store reset while query was in flight.
```

If I stick `client.resetStore()` inside a timeout, this issue goes away, which leads me to believe it's some sort of timing issue for stopping queries. That said, redux devtools shows all the queries stop (`APOLLO_QUERY_STOP`) before `APOLLO_STORE_RESET` executes.

Small issue because it goes away with a quick fix, but not intended behavior

**Comment by jaydenseric** [comment]
Keep in mind that `client.resetStore()` is async, and returns a promise. So you might get issues if you don't await and immediately follow it by a redirect to a page with queries on it.

**Comment by emmenko** [comment]
This might be related to #1945
