### ISSUE TITLE
Give batchInterval a default value

### ISSUE THREAD

**Issue by jaydenseric** [apollographql/apollo-client#1781]
Lets give the `batchInterval` option for `batchingNetworkInterface` a default value to make batching setup easier. Most people just want to use a recommended value. Those who understand the pros and cons of adjustment will still be able to set their own value for the option.

Perhaps default it to `10` because that is what everyone is using from [the example](http://dev.apollodata.com/core/network.html#BatchingExample).

**Comment by helfer** [comment]
Works for me! Can you make a PR @jaydenseric? 🙂
