### ISSUE TITLE
Question: How to ignore ssl check in networkinterface options

### ISSUE THREAD

**Issue by palmtale** [apollographql/apollo-client#1782]
As the question content
I've got error of UNABLE_TO_VERIFY_LEAF_SIGNATURE
But just a test I was trying for connecting my owner server side.
I'd like to know how to ignore TLS verification, no promotion in error message, no method on official doc http://dev.apollodata.com/core/network.html.

It would better to provide way for adding self-issued cert.

**Comment by stubailo** [comment]
You can pass any options you can pass to `fetch` in the `opts` field. See the docs for `fetch` here: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch

If you need any extra control, create your own network interface, which is just an object that has a `query` method on it: http://dev.apollodata.com/core/network.html#custom-network-interface

Let me know if that works for you!
