### ISSUE TITLE
@types/node 7.0.30 (latest version) breaks build

### ISSUE THREAD

**Issue by ramyanaga** [apollographql/apollo-client#1785]
The latest version of @types/node directory, which is version 7.0.30, breaks the build. Throws this error message: 
test/client.ts(651,27): error TS2345: Argument of type '"uncaughtException"' is not assignable to parameter of type 'Signals'.
test/client.ts(705,27): error TS2345: Argument of type '"uncaughtException"' is not assignable to parameter of type 'Signals'.

**Comment by glasser** [comment]
We looked at it together and learned that 7.0.30 added rules for `process.addListener`. Specifically it seems to really want "uncaughtException" handlers to take an error argument.

Arguably the bug in @types/node is that if they're going to add these detailed types for `process.addListener("uncaughtException") and friends, they should also add matching detailed types for `process.listeners("uncaughtException")` etc.

**Comment by glasser** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16705#issuecomment-308272510

**Comment by helfer** [comment]
Thanks @ramyanaga and @glasser! I'm going to patch this by pinning the version to 7.0.29 temporarily.

**Comment by glasser** [comment]
FYI, https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17150 if merged and released should resolve this issue and allow you to upgrade and unpin.

**Comment by helfer** [comment]
Thanks @glasser, I'll keep an eye on it! 🙂
