### ISSUE TITLE
Question: How to run a container query only on component mount, without using withApollo?

### ISSUE THREAD

**Issue by Bertrand31** [apollographql/apollo-client#1786]
Currently when I'm using a normal container query, every change of props (like a sub-route change) triggers the query again.
Is there a way to specify that this query should only run on component mount?

I know I could theoretically use `withApollo` and `queryData`, but it doesn't suit my needs as I'd like to keep the container/component dichotomy clean and do some complex stuff in the container, like pagination.

**Comment by helfer** [comment]
@Bertrand31 by "running the query" do you mean sending it to the server, or just executing it against the store? If the server query is what you want to avoid, you should be able to just set the right `cachePolicy`, for example `cache-first`.

**Comment by Bertrand31** [comment]
Ah, the problem was actually that I was handling auth in a middleware, so my query had `''` as `token`, and the token was fetched from indexedDB and added to the query in the middleware, overriding `''`.
So the query result stored in Apollo store (with the proper token as a param) was never matching the query with `''` as token.
Thanks anyway!
