### ISSUE TITLE
Apollo should raise exception for a Query response with `errors`

### ISSUE THREAD

**Issue by simpletrontdip** [apollographql/apollo-client#1788]
Sometimes, having exception return in `result.errors` is better than return `null` in `result.data`

This will unify the way we handle the exception, error in **Query**, say you are in `then` mean you have nothing to worry about the data back, cause all of them are in `catch`

For some case raise `Not found` is better than return `null`, but currently apollo just raise error when query has **Network error**

Please check and raise `ApolloError` when `result.errors` is present in **Query**, just like you did with **Mutation** such as

```js
    if (shouldFetch) {
      const networkResult = this.fetchRequest({
        requestId,
        queryId,
        document: queryDoc,
        options,
        fetchMoreForQueryId,
      })
     .then( result => {
       if(result.errors) {
         throw new ApolloError(...)
       }
       ...
     })
     .catch( error => {
      ...
    }
```

Thankyou

**Comment by helfer** [comment]
@simpletrontdip I think this already happens. If there's a GraphQL error, Apollo will throw an `ApolloError`. If you find an instance where that's not the case, please open an issue and tell us how to reproduce it. Thanks! 🙂

**Comment by simpletrontdip** [comment]
@helfer Correct me if I'm wrong, but here is the code you handle the `query` (the query not the mutation)

https://github.com/apollographql/apollo-client/blob/v1.4.2/src/core/QueryManager.ts#L460

This function only called when the exception occurred (I suppose they are network error, cause nothing can raise error there) mean if the server side return the result with `errors`, they will not be raised

For the `mutation`, you have handled this case
  + For the result with `errors`: https://github.com/apollographql/apollo-client/blob/v1.4.2/src/core/QueryManager.ts#L300
  + For the network error case:  https://github.com/apollographql/apollo-client/blob/v1.4.2/src/core/QueryManager.ts#L351

**Comment by helfer** [comment]
@simpletrontdip For queries, the error gets thrown here (due to legacy reasons): https://github.com/apollographql/apollo-client/blob/e4410c41438344d9e58849ce07f06fcc590fd0c7/src/core/QueryManager.ts#L1092

We know that the logic is not very clear around this, which is why we're working on refactoring it soon.
