### ISSUE TITLE
[FEATURE IDEA] Make `setStore` public

### ISSUE THREAD

**Issue by sammkj** [apollographql/apollo-client#1794]
`setStore` is particularly useful when implementing Redux in Web Worker / Redux in Chrome Extension (see [this thread](https://github.com/tshaddix/react-chrome-redux/issues/37#issuecomment-263360896)).

**Comment by helfer** [comment]
Hi @sammkj I'm not sure if making `setStore` public would help that much. Once Apollo Client is initialized, I don't think the store can simply be swapped out, because there's some state in Apollo Client. Rather than swapping the store, could you just initialize a new client instance?

**Comment by sammkj** [comment]
@helfer, currently I'm moving Redux into Web Workers. For that to work, I have to create a Redux store proxy on the main thread and a real Redux store in Web Worker. So I need a way (setStore) to tell Apollo to use the Redux store proxy instead of the real Redux store. I hope what I said makes sense. =D

**Comment by helfer** [comment]
Ok 🙂 Is there a reason why you can't use the proxy directly when you're initializing Apollo Client?

**Comment by sammkj** [comment]
Is there an option to specify the store when initializing ApolloClient? If I removed `apolloClient.setStore(reduxProxyStore)`, Apollo Client doesn't dispatch any actions to update the store

**Comment by helfer** [comment]
@sammkj here are some instructions for using a custom store: http://dev.apollodata.com/react/redux.html#creating-a-store

**Comment by sammkj** [comment]
@helfer that's what we already have.

We had an older version of `apollo-client` that needed `setStore` to make it work. So everything is fine! Thank you!
