### ISSUE TITLE
[Feature Request] Add store read access to optimisticResponse functions

### ISSUE THREAD

**Issue by n1ru4l** [apollographql/apollo-client#1802]
**Use case:**

This is helpful when you update some type that is already in the store.
```graphql
input AnswerUpdateInput {
  color: String 
  description: String
  sort: Int
}

type Answer {
  id: Int!
  color: String!
  description: String!
  sort: Int!
}

type Query {
  updateAnswer(
    answerId: Int!
    data: AnswerUpdateInput!
  ): Answer
}
```

```javascript
const UpdateAnswerMutation = gql`
  mutation updateAnswer(
    $answerId: Int!
    $data: AnswerUpdateInput!
  ) {
    id
    color
    description
    sort
  }
`

const withUpdateAnswerMutation = graphql(UpdateAnswerMutation, {
  props: ({ ownProps, mutate }) => ({
    updateAnswer:  ({ answerId, changedFields }) => mutate({
      variables: { answerId, changedFields },
      optimisticResponse: ({ answerId, changedFields }) => ({
        __typename: `Mutation`,
        updateAnswer: {
          __typename: `Answer`,
          id: answerId,
          ...changedFields,
        },
      }),
    })
  }),
})
```

Lets say you call updateAnswer the following way `updateAnswer(1, { color: 'red' })` (because you only want to update the color field). In the optimisticResponse function you can only access the variables which got passed to the mutate function, so you cannot perform a "valid" optimistic response because there is information missing that you have to get from the store by using readFragment (or readQuery; depending on the use case).

Therefore I would suggest some kind of a store proxy like used in the `update` function.

**Comment by helfer** [comment]
@n1ru4l I think you should be able to provide those variables using a closure. Or maybe I'm missing something? `optimisticResponse` should definitely not have anything special to access the store. If there are any extra variables you need, you should be able to provide them by creating a closure around `mutate`.

**Comment by n1ru4l** [comment]
@helfer This is what I am doing at the moment. IMHO this forces me to pass props to the HoC that are only needed for the optimistic ui, which in my case can be reduced by attaching the mutation HoC to a component higher in the hierarchy and passing the mutate function down. But I can life with that. I am going to close this issue

**Comment by stubailo** [comment]
What if we added `store` as one of the arguments to `props`, just like `mutate`?

**Comment by n1ru4l** [comment]
@stubailo That would also be a nice solution for me!
