### ISSUE TITLE
Stop retrying queries if there's been a network error

### ISSUE THREAD

**Issue by phyrog** [apollographql/apollo-client#1811]
Is it possible to stop Apollo from retrying the queries, if there has been a network error (e.g. the server is not reachable)? It currently just throws the error and retries over and over, crashing the browser if the console is opened for too long.

I've tried setting `pollInterval` to `0`, but it has no effect.

```
OPTIONS http://localhost:3000/graphql net::ERR_CONNECTION_REFUSED

Uncaught (in promise) Error: Network error: Failed to fetch
    at new ApolloError (ApolloError.js:32)
    at QueryManager.js:235
    at QueryManager.js:680
```

Gradually increasing the timeout between retries would be fine for us too.

**Comment by helfer** [comment]
Hi @phyrog, thanks for filing an issue. Apollo Client doesn't currently retry on error. Maybe you're using some custom logic to retry requests, retry queries or re-render components on error?

**Comment by phyrog** [comment]
Yep you're right. It has to do with performing a `client.resetStore()` if an error occured in the `props` function, which triggered the query to be re-performed and the same network error to retrigger the reset, and so on.

Closing this. Thanks!
