### ISSUE TITLE
Feature idea: Possibility to handle network errors in a centralized way.

### ISSUE THREAD

**Issue by tillkolter** [apollographql/apollo-client#1813]
In case the server is not reachable or the connectivity is broken, the Apollo client rejects the promise with an ApolloError classified as a network error. Though it might be better to catch various errors on a per query/mutation basis, I think it is reasonable, that an application should be able to handle network errors in a centralized way as it seems inappropriate to add the same network error handling boilerplate for every single call of any query/mutation method.

I think just like the `useAfterware` method gives us a way to handle server responses like authentication errors, there should also be a way to add an observer for other ApolloErrors especially network errors. Or maybe there is a possibility to observe the store instance for the dispatched errors, that I am not aware of? 

My apologies if the request has been answered before, I only could find references to error handling questions concerning promise rejection on the query level.

**Comment by helfer** [comment]
Hey @tillkolter, we're actually working on exactly that kind of thing [over here](https://github.com/apollographql/apollo-link/pull/6). I'm going to close the issue here and suggest you add your comments and input on the other repo, it would be much appreciated!
