### ISSUE TITLE
Electron: "cache-only fetchPolicy option should not be used together with query refetch"

### ISSUE THREAD

**Issue by saadbinsaeed** [apollographql/apollo-client#1814]
I am using refetchQueries option in my code and it works very well in my web app. But when i converted my application to electron app, the page where the refetchQueries are used dispatching the error 

`Uncaught (in promise) Error: cache-only fetchPolicy option should not be used together with query refetch. at ObservableQuery.module.exports../node_modules/apollo-client/core/ObservableQuery.js.ObservableQuery.refetch`

While all queries, mutations, subscriptions, refetch etc are working perfect so refetchQueries should also work in my electron app.

Here is the snippet of my code where refetchQueries are used

```
export default geolocated({
  positionOptions: {
    enableHighAccuracy: true,
    maximumAge: 0,
    timeout: Infinity,
  },
  userDecisionTimeout: null,
})(
  graphql(SiteSaveMutation, {
    options: {
      refetchQueries: [
        'SitesFetchQuery',
      ]
    }
  })(
    graphql(SiteTypeQuery)(
      (SiteForm)
    )
  )
);
```

Apollo-Client: 1.0.4
React-Apollo: 1.1.1

**Comment by helfer** [comment]
Hi @saadbinsaeed, this error indicates that one of the queries that you're trying to refetch has the cache-only policy set. Refetching such a query doesn't make sense, because it didn't go to the server in the first place.

Also, it's worth noting that we no longer recommend using refetchQueries with named queries. instead, we recommend providing the full query document and variables to reduce dependencies.

**Comment by saadbinsaeed** [comment]
Hi @helfer happy to see you. As i already mentioned that refetch query is working well in web project but it is not working in desktop ( electron ) app. I have also tried all the documented fetch policies `cache-first" | "cache-and-network" | "network-only" | "cache-only" | "standby` but it didn't work for electron app. 

How can i set the fetch policy of queries called by the name in refetchQueries array?

**Comment by saadbinsaeed** [comment]
I have even tried this with and without the option of **fetchPolicy**
```
graphql(SiteSaveMutation, {
    options: { fetchPolicy: 'network-only' },
    query: gql`query SitesFetchQuery {
        viewer {
            sites(where:{active: true}) {
                edges {
                    node {
                        id
                        name
                        image
                        siteType {
                            id
                            name
                            icon
                        }
                    }
                }
            }
        }
    }`
  })
```
but still the same error :(:(:(

**Comment by helfer** [comment]
@saadbinsaeed hm, that's really strange. So you're saying code that works perfectly on react native or the web doesn't work in electron? Would you be able to put together a reproduction so someone can look into it?

**Comment by saadbinsaeed** [comment]
Solved it. I was setting the `fetchPolicy` to the query whose default policy was `cache-first`. I attached `"cache-and-network"` policy to the both original query and with the refetchQuery. First i am only setting the fetchPolicy with the refetchQuery. But still wondering that how it is working and web app :P
