### ISSUE TITLE
Include afterware in batching network interface

### ISSUE THREAD

**Issue by skosch** [apollographql/apollo-client#1815]
**Intended outcome:** To be able to easily use the batching network interface with a server that supports it (in our case, Absinthe; see absinthe-graphql/absinthe_plug#89)

**Actual outcome:** The requests are batched into an array as advertised, but when the results come back in the shape of a corresponding array, Apollo fails to pull that apart into the individual result objects and throws an error. Currently, an afterWare function (see [here](https://github.com/absinthe-graphql/absinthe_plug/issues/89#issuecomment-307845018)) is needed to do this manually.

It would be nice if Apollo took care of this automatically, or at least documented the need for including this function.

**Comment by helfer** [comment]
@skosch Apollo does indeed automatically do it, if your response is in the format specified by Apollo and supported by graphql-server, Graphene and others. The only reason you need an afterware with Absinthe is because they decided to send the responses in a different shape. I think it would be worth getting everyone in the community together and agreeing on a standard.

**Comment by skosch** [comment]
@helfer Thanks! The referenced issue wasn't my own but I actually wrote a substantial chunk of Absinthe's batching code, so you have my full attention :stuck_out_tongue: We tried to make it compatible with both Relay-React-Network-Layer and Apollo by sending back an array of responses, each in the shape of `{payload: {data: {...}}}`, in the same order as the requests. I was under the assumption that this is how Apollo handles it as well (minus RRNL's `id` field) – but if it's not, please enlighten me!

(I shall ruefully retract any and all insinuations that this is Apollo's problem! And yeah we should decide on a standard for sure)

**Comment by benwilson512** [comment]
> I think it would be worth getting everyone in the community together and agreeing on a standard.

I definitely agree with this. There seems to be a dearth of documentation WRT the formats expected by different clients at this time.
