### ISSUE TITLE
when add options `mode: "no-cors"` it break the request and Apollo Server fail, 500 error

### ISSUE THREAD

**Issue by nisimjoseph** [apollographql/apollo-client#1817]
**Intended outcome:**
GraphQL call execute without CORS

**Actual outcome:**
server response 500 error

**How to reproduce the issue:**
use this code in the client, occur all the time.
```
const apolloClient = new ApolloClient({
	networkInterface: createNetworkInterface(
		{
			uri: "http://domain.com/graphql?",
			opts: {
				mode: "no-cors",
			},
		}),
	dataIdFromObject: (value:any) => value.id,
	initialState: {},
});
```

**Comment by helfer** [comment]
I'm pretty sure this has nothing to do with apollo-client because it just passes the option to the underlying `fetch` library. I suggest you open the issue there, or on the server library if you think the server is at fault.

**Comment by pencilcheck** [comment]
It's weird how it breaks only when it is fetched in the browser not in the server though

**Comment by kulikovviktor** [comment]
When network Interface configured as `no-corse`, all requests has content-type: `plain/text` instead `application/json`. I'm not sure thats problem is Apollo or native fetch implementation, but with `cors` all headers are correct

**Comment by prakasa1904** [comment]
same problem, request header content-types is changes to Content-Type:text/plain;charset=UTF-8
but the response 500 and body response is errors `POST body missing. Did you forget use body-parser middleware?`

how to handle this ?

**Comment by rohmanhm** [comment]
Got the same issue like @prakasa1904 had.
Anyone have a solution for this one?

**Comment by ssuvorov** [comment]
I don't use `createNetworkInterface`. My working setup. ("react-apollo": "^2.2.4")
```js
export const graphQLClient = new ApolloClient({
  link,
  fetchOptions: {
    mode: 'no-cors',
  },
  cache: new InMemoryCache()
});
```
