### ISSUE TITLE
Usage of Object in Typescript files too restrictive?

### ISSUE THREAD

**Issue by erkieh** [apollographql/apollo-client#1818]
**Intended outcome:**
Compilable Typescript code

**Actual outcome:**
TS2459:Type 'Object' has no property 'data' and no string index signature.
TS2339:Property 'data' does not exist on type 'Object'.

I am new to Typescript, so bear with me. Isn't the use of Object in many of the typescript files too restrictive?

for example
https://github.com/apollographql/apollo-client/blob/master/src/data/mutationResults.ts

```
import { ApolloAction } from '../actions';
export declare type MutationQueryReducer = (previousResult: Object, options: {
    mutationResult: Object;
    queryName: string | null;
    queryVariables: Object;
}) => Object;
```

Shouldn't it be any instead?
The TS documentation says:

> Don’t ever use the types Number, String, Boolean, or Object. These types refer to non-primitive boxed objects that are almost never used appropriately in JavaScript code.
> Instead of Object, use the non-primitive object type (added in TypeScript 2.2).

https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html

**Comment by rrdelaney** [comment]
I'm also having this problem

**Comment by helfer** [comment]
Hey @erkieh, I think you're right. In most cases here `object` should have been used, or a more appropriate `{ [key: string]: any}`. If you make a PR I'll be happy to fast-track it! 🙂

**Comment by jbaxleyiii** [comment]
@erkieh or @rrdelaney would you be able to PR this? I'd be happy to merge it!

**Comment by rrdelaney** [comment]
PR sent to use `Record<string, any>` 😄
