### ISSUE TITLE
Fragment merging results in corrupt cache

### ISSUE THREAD

**Issue by bessey** [apollographql/apollo-client#1824]
**Intended outcome:**

(I am running the latest version of react-apollo + apollo-client as of time of submission.

These two queries should give identical results:

```graphql
query {
...
      localResourceLeads {
        id
        localResource {
          ...SearchResultDetails
        }
        ...SavedLeads # this contains the fragment `localResource { otherStuff }`
        ...LeadActions
      }
...
}
```
and reordered, but otherwise identical.

```graphql
query {
...
      localResourceLeads {
        id
        localResource {
          ...SearchResultDetails
        }
        ...SavedLeads
        ...LeadActions
      }
...
}
```

**Actual outcome:**
While the Apollo devtools gives the same return value when the "from cache" block is unchecked, when checked, the `otherStuff` value is missing. `graphql-anywhere`'s `check()` itself caught this in my case. It seems like Apollo has messed up merging the fragments that produce overlapping graphs.

**How to reproduce the issue:**

I will have to come back to this another day. Making a note before signing off for the evening.

**Comment by helfer** [comment]
Hi @bessey, thanks a lot for the bug report. If you would be able to provide us with a reproduction using react-apollo-error-template, that would be really great!

**Comment by bessey** [comment]
Hey helfer, my graph's shape has changed since i reported and I can no longer repro this bug, so closing for now.
