### ISSUE TITLE
Provide a way to override the HTTP client that the network interface is using

### ISSUE THREAD

**Issue by gajus** [apollographql/apollo-client#1827]
I am referring to this segment in the code:

```js
return fetch(this._uri, {
  ...this._opts,
  body: JSON.stringify(printRequest(request)),
  method: 'POST',
  ...options,
  headers: {
    Accept: '*/*',
    'Content-Type': 'application/json',
    ...(options.headers as { [headerName: string]: string }),
  },
});

```

https://github.com/apollographql/apollo-client/blob/94d8d200d727337f265a10472723b0af0fd59d7e/src/transport/networkInterface.ts#L180-L190

There are multiple reasons why I do not want to use `fetch`, esp. on server side. The primary reason is that I want to proxy all the requests.

What you could do is simple provide HTTP client as an option to the network interface factory. The client would need to comply to whatever API that the apollo-client is using, e.g.

```js
httpClient(URL, postBody, headers);

```

As far as I can tell, these are the properties required by `apollo-client` internally.

**Comment by helfer** [comment]
Hi @gajus, thanks for filing this issue. @evanshauser is working on exactly that over in https://github.com/apollographql/apollo-link/pull/6 and https://github.com/apollographql/apollo-fetch. I'm going to close the issue here, but we'd love to have your input over there so we can make sure it works for your use-case.

**Comment by evanshauser** [comment]
@gajus We just published the initial release of [apollo-fetch](https://github.com/apollographql/apollo-fetch). It has an example of using a custom fetch function. Please open an issue or let me know if apollo-fetch doesn't hit your use-case or can be improved.
