### ISSUE TITLE
Fragment on `refetch()` causes query to be fetched twice

### ISSUE THREAD

**Issue by khankuan** [apollographql/apollo-client#1829]
**Intended outcome:**
`refetch({ overrideArg })` triggers a single query call to refetch data.

**Actual outcome:**
2 graphql queries are sent at the same time. (fetchQuery is called twice)
First query has args that are overridden.
Second query has args that were default and not overridden.

**How to reproduce the issue:**
Other info:
- Using IntrospectionFragmentMatcher with the latest schema
- Correct behavior achieved when HeuristicFragmentMatcher is used instead
- Correct behavior achieved when setting `returnPartialData` to true with a custom IntrospectionFragmentMatcher.

**Comment by helfer** [comment]
Hi @khankuan, thanks for the report. Would you be able to build a quick reproduction with react-apollo-error-template? That would help a lot! 🙂

**Comment by khankuan** [comment]
Did not manage to build a reproduction yet. But it seems like nested fragment caused the bug:
```
query {
  getY(id: "yid") {
    fieldZ {
      fieldB
    }
    ...X
  }
}
fragment X on Y {
  fieldZ {
    fieldA
  }
}
```

**Comment by jbaxleyiii** [comment]
@khankuan this is very interesting! For reproductions with custom schemas, using [Launchpad](https://launchpad.graphql.com/) can be really helpful!

**Comment by khankuan** [comment]
Can't seem to reproduce. Closing for now.
