### ISSUE TITLE
Refetch all queries

### ISSUE THREAD

**Issue by kennethlynne** [apollographql/apollo-client#1831]
We have a chat application that might lose its real-time connection from time to time, and when the real-time session is re-established it might have lost some events. It would be sweet to be able to tell apollo to refetch all known queries, but I can not find this documented anywhere. Is there any solution to this? I can only find documentation on how to do this refetch per component.

**Comment by helfer** [comment]
@kennethlynne there's no function built for the explicit purpose of just refetching active queries, but `resetStore` actually does that as a side-effect (it also removes currently unused data from the store). Maybe give that a try and report back if it worked?

**Comment by kennethlynne** [comment]
We're currently using that to reset the store when logging the user out, but I will give it a try and see if this very interesting side-effect solves it for us and report back yeah :D

**Comment by kennethlynne** [comment]
It worked like a charm!

**Comment by amannn** [comment]
If anyone comes across this, a [`reFetchObservableQueries` method was added to Apollo Client](https://github.com/apollographql/apollo-client/pull/2625) a bit later which does this.

**Comment by ibash** [comment]
For future travelers, one gotcha with `reFetchObservableQueries` is that it respects the `queryDeduplication` flag on the client.

So if you're not getting new data like you expect, try setting `queryDeduplication: false` to see if the bug goes away.

If you want to have both `queryDeduplication` normally, but every once in a while do a full data refresh, reach into the internals:

```
client.queryManager.queryDeduplication = false
client.reFetchObservableQueries()
client.queryManager.queryDeduplication = true
```
