### ISSUE TITLE
Select fragment as observable from the store

### ISSUE THREAD

**Issue by altschuler** [apollographql/apollo-client#1836]
Using Apollo for Angular 2, I'm trying to find a way to reactively select entities from the cache/store. It's basically `readFragment` but as an observable (`watchFragment` maybe?). `watchQuery` will not work as I don't want to watch an actual query.

As far as I could tell `readFragment` only enables a single immediate lookup into the store, not an observable result. I tried looking into the ApolloStore, but could only find the `getState` and `dispatch`, no `select` or similar.

Am I missing something? :-)

Edit: I'm certain this would be possible by using my own NgRedux store and just select data from that, but I'm wondering whether there's a way to select directly through Apollo (internally it must happen somehow).

Edit 2: I've achieved this with a "custom" NgRedux store and it works perfectly. However, I still think `watchFragment` would be a valid addition to Apollo :-)

Edit 3: So, it actually does not work perfectly like this, because I'm only getting the entity itself from the store, not any related entities that might exist on the fragment.

**Comment by helfer** [comment]
Hey @altschuler, that's an interesting idea. Can you tell me what your use-case is?

You're right that currently there's no function that lets you do this directly, but if you want to make a PR to add a `watchFragment` function, we'd definitely be open to that.

Right now, I think you can get exactly what you want by using a [custom resolver](http://dev.apollodata.com/react/cache-updates.html#cacheRedirect). You can make the custom resolver take one argument (the store key) and simply return the reference object, below which you can select the fragment. Here's an example:

```
const client = new ApolloClient({
  customResolvers: {
    Query: {
      readFragment(_, args) {
        return toIdValue(args.id);
      },
    },
  },
});

const QUERY = gql`
query {
  readFragment(id: "myId") {
    name
    id
    age
  }
}`;
```

Let me know if it works!

**Comment by altschuler** [comment]
Cool, thanks a lot, that might work. I went for NgRedux to get notified when a change has occured and the readFragment to get the actual full fragment. It might be quite a performance overhead so will have to measure. Using the technique you mention, would you say that, performance-wise, it's something that's suitable for having potentially hundreds or `watchQuery` going at a time?

Use case is that I've got a document from the apollo server which I need to manipulate (it's an editor thing). This document contains references to a lot of other entities which I don't want to be part of the editing process, so I'm just using their IDs to fetch the fragments since I know they're in the store. I also need to have these fragments up to date with the store because they can be updated via mutations from anywhere. It's a bit complicated to explain and there might be a cleaner solution, but the gist is that I've got ID's of entities that I need the fragments of and I need to "watch" them, not one-off read.

As for the PR, I would like to have a stab at it. Any pointers? I've had a look around but there's a decent amount of code to digest. My hunch is that it would need to be implemented in the DataProxy?

**Comment by jbaxleyiii** [comment]
@helfer would you be able to help point @altschuler in the right direction here?

**Comment by altschuler** [comment]
@helfer No worries! I'm still quite interested, I think it'd be a nice addition, I can image a few use cases if it can be done in an efficient way. Regarding the performance of watchQuery I never measured it since I never went with that solution, but it somehow feels like the wrong approach to "wrap" simple fragment lookups with proper query bells and whistles

**Comment by helfer** [comment]
Ok, great! I'm not sure what the latest state is of the new store API that you'd have to write against, but maybe @jbaxleyiii can fill us in!

**Comment by ntziolis** [comment]
Is this possible by now?
