### ISSUE TITLE
Sub queries returning the same data when they should be different

### ISSUE THREAD

**Issue by rblalock** [apollographql/apollo-client#1837]
I'm running in to an issue only in the Apollo client that I'm troubleshooting.  If you could point me how I could best debug this I'd be very happy.

**Intended & outcome:**
Below is the sample query, the GraphiQL results (which is the expected results), the apollo results (the actual outcome of the Apollo client, which is incorrect), and my node unit test as well.  This exact query works fine in GraphiQL but is incorrect in Apollo.  

You'll notice the "sum" amount, with the Apollo results, is the same for all sub queries.  Contrast that with the GraphiQL results (expected results) and you'll notice they are all different.  It seems like Apollo is getting the last sub query results for user.* and populating all of them with those last values.

I've verified this happens in the Apollo client in our Node app and in our React app.  I've also verified that the GraphQL server is indeed returning the correct raw results.

Another interesting data point:  If I set `client.addTypename = false;`, then it will __properly__ return the results.  Obviously I don't want to do that as it will throw all sorts of warnings such as:

`You're using fragments in your queries, but either don't have the addTypename:
  true option set in Apollo Client, or you are trying to write a fragment to the store without the __typename.
   Please turn on the addTypename option and include __typename when writing fragments so that Apollo Client
   can accurately match fragments.
Could not find __typename on Fragment  ContributionData`

and `DEPRECATION WARNING: using fragments without __typename is unsupported behavior and will be removed in future versions of Apollo client. You should fix this and set addTypename to true now.`

https://gist.github.com/rblalock/e012a6a2096ead584f396bcf36584fdc

**Comment by rblalock** [comment]
Using the networkInterface directly, e.g. `client.networkInterface.query`, works btw.

**Comment by helfer** [comment]
Hi @rblalock, is there any chance that all of these items have the same id? If so, the behavior is completely expected, because Apollo will merge items with the same id together in the store during normalizing. I think this is corroborated by the fact that setting `addTypename: false` makes the problem go away. In that case Apollo will assign a store key based on the object path from the root of the query. You can force this behavior for certain types by providing a custom `dataIdFromObject` function that returns `undefined` when Apollo Client should generate an id based on the path.

Let me know if that helps!

**Comment by rblalock** [comment]
@helfer Yes they do have the same ID since they're the same user.  However, in the data structure in the gist, the user will have different data associated with it depending on it's parent object.

**Comment by rblalock** [comment]
Just put this in the client options:  `dataIdFromObject: () => undefined,`.  Getting bad results again.

**Comment by helfer** [comment]
You can inspect the store with the Apollo Client developer tools, or you can use the Redux devtools to look at the content, which I think should help you debug this.

**Comment by rblalock** [comment]
Yeh I have.  The store just has the last data in for the `user {}` fields, which, as you say, is expected since the ID is the same.  Setting `dataIdFromObject` fn that returns `undefined` still results in using the ID as the key.  It seems like it should use the full path to the sub query, not just the top most parent as part of the key.  For example, the key ends up being `ContributionUser:userId123456789` which isn't deep enough.  The key should probably go all the way to the top level to ensure its not duplicated elsewhere.

**Comment by helfer** [comment]
I may be wrong and you have to return `null` or something from `dataIdFromObject`. There's definitely a way to make the key use the path all the way from the root.

**Comment by rblalock** [comment]
Yeh tried null too.

**Comment by rblalock** [comment]
Ok my apologies, I had the option in the wrong spot (under the networkInterface options).  `dataIdFromObject: () => undefined,` does indeed work under the top level options for the apollo client.  Thanks for helping me with this.

**Comment by helfer** [comment]
Ok, glad you figured it out! 🙂
