### ISSUE TITLE
Client-side cache enhancement: Is it possible to add additional client-side properties to query data?

### ISSUE THREAD

**Issue by serle** [apollographql/apollo-client#1851]
I am building a tree control. I would like to be able to add some additional client-side properties to each  query data object, before it gets written into the cache. e.g. isExpanded property which is not a server-side concern, but belongs with the underlying object. I would also like to be able to retrieve the underlying object from the Apollo cache by id/typename and then be able to imperatively update these client-side properties. I would prefer not to have to keep a separate map between these properties and the apollo objects in the cache as both server-side and client-side properties are used to render a give row.

**Comment by jbaxleyiii** [comment]
@serle we are actively working on something that would allow something like this! We are working on making the store pluggable (so you could setup your own) and making the request chain open to the application developer to be able to add custom things to it

cc @shadaj and @evanshauser for another use case
