### ISSUE TITLE
Feature idea: Combining middleware and afterware

### ISSUE THREAD

**Issue by andreasgruenh** [apollographql/apollo-client#1852]
Hello everyone, I have been replacing Relay with Apollo in my SPA and I'm really liking it so far! One problem I encountered is refering to the middlewares.
In the past I had a logging middleware in my fetchWrapper, that logs the path, the response, and the time to completion. With the current setup I have to add an id to the request options, to connect requests with responses.
Other middleware frameworks (like koa) combine those steps.
The next() function in the middleware could return the promise of the next middleware, so that you can have request specific state before and after the request.

With async/await:

```js
import _ from 'lodash';


async function logging(request, next) {
  const start = _.now();
  await next();
  const end = _.now();
  console.log(`Request took ${end - start}ms to complete`);
}
```

**Comment by helfer** [comment]
Hey @andreasgruenh, if I understand correctly you mainly want to time how long the request takes, right? @evanshauser is currently working on a new fetch architecture for Apollo which should be able to support that use-case really easily. You can check out the progress over on the [apollo-link](https://github.com/apollographql/apollo-link/pull/5) and [apollo-fetch](https://github.com/apollographql/apollo-fetch) repositories. These already work with Apollo Client, if I'm not mistaken. I encourage you to add your use-case to the discussion over on apollo-link!

**Comment by stubailo** [comment]
For now, one easy way to do timing would be to wrap the method on the network interface itself:

```js
const ni = createNetworkInterface(...);

const oldQuery = ni.query.bind(ni);
ni.query = (...args) => {
  console.log('start request');
  const result = oldQuery(...args);
  return result.then((x) => {
    console.log('end request');
    return x;
  });
}
```

You'd also need to handle the error case, but the above could work as a hack until `apollo-link` is ready!

**Comment by andreasgruenh** [comment]
As far as I can see apollo-fetch is using the same separation between middlewares and afterwares. Could maybe explain the benefits of this separation to me? Because in my opinion this concept would be much simpler if there were only one kind of middleware which can do both. 
Another use case that could be made with this is repetition of requests. A middleware could store the current request and resend it on timeouts.

**Comment by stubailo** [comment]
I think it's best to move this conversation over to `apollo-fetch` - I don't think we're going to change the API on the current network interface, but there's some opportunity to release breaking changes on `apollo-fetch` while not too many people are using it yet.

**Comment by evanshauser** [comment]
@andreasgruenh To help segue the conversation over to `apollo-fetch` or `apollo-link`, `apollo-fetch` is designed to make the separation of functionality distinct and simple, so middleware and aftweware are two different concepts.

`apollo-link` is based on similar ideas to what you have in mind, where each link has access to the request (called an Operation) and the response in the form of an observable. The links form a chain that is connected with a `next:  (Operation) => Observable` callback, which sends the operation to the next link and returns the link's result. The last link in a chain doesn't have the callback.

Your logging would probably be done in a link, so I think you're feedback would make the most impact on this [PR](https://github.com/apollographql/apollo-link/pull/6).

Please feel free to open another issue on either [apollo-fetch](https://github.com/apollographql/apollo-fetch) or [apollo-link](https://github.com/apollographql/apollo-link) if that works better for you.
