### ISSUE TITLE
POST  500 (Internal Server Error) Wrong format

### ISSUE THREAD

**Issue by azotklas** [apollographql/apollo-client#1853]
Help me to understand.
I just started learning angular 4 and immediately decided to connect to the server graphql.

I have a string :
{ **NAME** : jobs(limit: 100, filter: "{\"and\":[{\"or\":[{\"flow\":{\"is\":\" **FLOW_NAME** \"}},{\"stage\":{\"is\":\" **STAGE_NAME** \"}}]}, {\"user\":{\"is\":\" **USER_NAME** \"}}]}") { count jobs { id name flow stage user } } }

**Parameters that change:**
-NAME
-FLOW_NAME
-STAGE_NAME
-USER_NAME

that works in the "Postman" program (you can see it in the screenshots).
i setting Content-Type :"application/graphql" and  value 'raw'
![default](https://user-images.githubusercontent.com/12971978/27806042-f22235d6-6040-11e7-9c1c-9a3599ea0063.PNG)

How to convert this string. To send requests in this form: (for example)

```
const newQuery = gql`
  mutation Column0($title: String!, $duration: Int!, $watched: Boolean!){
    createVideo(video: { title: $title, duration: $duration, watched: $watched }){
      id,
      title
    }
  }
`;


const query = gql`
    {
        videos {
            id,
            title
        }
    }
`;

  createCall() {
    this.apollo.mutate({
      mutation: newQuery,
      variables: {
        'flow': 'bertelsmann [main]',
        'stage': '123213',
        'user': 'true'
      }
    }).subscribe((afterMutation) => {
      this.apollo.query({query: query, fetchPolicy: 'network-only'})
        .subscribe((data) => {
          console.log(data);
        });
    }, (err) => alert(err));
  };

```
Really need your help

Now I have a error 500
![default](https://user-images.githubusercontent.com/12971978/27808945-3da046fc-6054-11e7-83ea-4ea93a3f08a5.PNG)

**Comment by jbaxleyiii** [comment]
@azotklas I'm having a hard time following here? Would you be able to setup a reproduction for us to look at or maybe more information like the response data? Looking at the last screenshot, everything is being sent over as expected

**Comment by ramirobg94** [comment]
I hace the dame issue, the reason is the content-type request heladera, ir should be aplication/json.

I cant be able to change this heladera so i still have the error :s
