### ISSUE TITLE
Impossible to use await in update method

### ISSUE THREAD

**Issue by seb-saletes** [apollographql/apollo-client#1854]
I have a mutation that create a new album in my db. Once the album is created I call an async method to upload the pictures in this album. However, I need the result to update my apollo store using readQuery and writeQuery. Using await in the update method seems to give me the following error:

> Uncaught (in promise) Error: Cannot call transaction methods after the transaction has finished.
    at TransactionDataProxy.assertNotFinished (http://localhost:9000/_next/1499188588067/commons.js:80064:19)
    at TransactionDataProxy.writeQuery (http://localhost:9000/_next/1499188588067/commons.js:80032:14)

Here is a simplified version of my code:

    const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
    
    export default compose(
      graphql(mutationQuery, {
        props({ mutate }) {
          return {
            createAlbum: (values, ownProps) => new Promise((resolve, reject) => {
              mutate({
                variables: {
                  title: values.title,
                  authorId: ownProps.target.authorId,
                  authorType: ownProps.target.authorType
                },
                update: async (store, res) => {
                  if (res) {
                    const variables = {
                      authorType: ownProps.target.albumableType,
                      authorId: ownProps.target.albumableId,
                      after: null
                    }
                    const data = store.readQuery({ query: routeQuery, variables })
                    await sleep(5000) // I ususually upload the picture here and use the result to add it into in my album
                    store.writeQuery({ query: routeQuery, variables, data })
                    resolve()
                  } else if (!res) {
                    reject('Album creation failed with error')
                  }
                }
              })
            })
          }
        }
      }),
      reduxForm({
        form: 'create-album',
        onSubmit: (values, dispatch, ownProps) => ownProps.createAlbum(values, ownProps)
      })
    )(CreateAlbumComponent)

**Comment by jbaxleyiii** [comment]
@seb-saletes this is an interesting use case for sure! I'm not opposed to it, but it will require some inner reworking around [how update](https://github.com/apollographql/apollo-client/blob/3b5045dfe74183fe060d2027e31317d890755b99/src/data/store.ts#L165-L171) is executed.

**Comment by rnenjoy** [comment]
Same here

**Comment by kaid** [comment]
Is it possible to make data() an async function, so that we could somehow await the update() invocation?

**Comment by johhansantana** [comment]
has anyone figured this out yet? The error seems to not be there anymore, the cache updates correctly but it doesn't trigger a UI rerender if you use async/await
