### ISSUE TITLE
Missing field <field name> in <result> message should have more information

### ISSUE THREAD

**Issue by stubailo** [apollographql/apollo-client#1858]
**Intended outcome:**
When you are writing an `updateQuery` function, and you forget to specify a field on the query, it should tell you how to resolve your problem rather than just saying "missing field".

**Actual outcome:**
Apollo Client throws an error like:

```
Missing field _id in {
  "activeVersion": {
    "_id": "tcaRcBnXZtxYcjgun-23",
    "version": 23,
    "appId": "tcaRcBnXZ
```

Which doesn't help you fix the problem. It's not clear that this actually prevents the write to the store (should it?) and it doesn't tell you that it's about missing an _id field on the data you're writing in `writeQuery` or `updateQuery`.

**How to reproduce the issue:**
@klairetan ran into this in Galaxy, but it's basically just a case of the error message not being that helpful here: https://github.com/apollographql/apollo-client/blob/94d8d200d727337f265a10472723b0af0fd59d7e/test/writeToStore.ts#L1237

**Comment by jbaxleyiii** [comment]
If anyone is interested in improving this, I would be happy to help out! Just comment here or open a failing PR!

**Comment by ramyanaga** [comment]
@stubailo Can you check if this error still occurs and/or check if thats the error message you're getting? I get a more useful error message when I try replicating the error. 
![screen shot 2017-07-18 at 5 27 09 pm](https://user-images.githubusercontent.com/9134031/28345316-5d6e61cc-6bde-11e7-80d5-19e490f7516b.png)

**Comment by stubailo** [comment]
That's a different error, I need to create a better repro. I think you can get it by calling:

```js
client.writeQuery({
  query: gql`
{
  currentUser {
    login
    avatar_url
    __typename
  }
}`
data: { currentUser: { login: 'asdf' } },
});
```

I think it will tell you missing field `avatar_url` like the above.
