### ISSUE TITLE
Remove package-lock.json from repo?

### ISSUE THREAD

**Issue by stubailo** [apollographql/apollo-client#1864]
This is currently making it harder to reproduce incompatibility issues with new packages. Also, doesn't work with Greenkeeper.

**Comment by yordis** [comment]
@stubailo  just remove it.
At the end of the day it's helpful when you really want to force people to work with the exact versioning but we have versioning anyway in `package.json` so.

**Comment by stubailo** [comment]
Mind sending a PR? I'm not near a CLI right now.

**Comment by stubailo** [comment]
Need to add to `.gitignore` as well.
