### ISSUE TITLE
Enhancement request: better imperative api

### ISSUE THREAD

**Issue by serle** [apollographql/apollo-client#1872]
The current writeFragment method seems to be overly complicated for local cache updates. Given that Apollo managers a normalized cache of objects i.e. separate arrays of objects of a give __typename (after having performed a query) it would be much easier to allow something standard like array.filter() to query a subset of objects in the cache; and subsequently allow bulk mutations to that set of objects before reducing them back into the underlying cache. Ideally this API should also give the developer access to the apollo object id function so that user id comparisons can be converted consistently into cache id comparisons. 

Also it would be great to able to place mutations (and a mutation policy) at the __typename level so that when mutations are made to a given normalized cache, the corresponding graphql mutations can be automatically invoked behind the scenes thereby abstracting away much of the scattered boilerplate CUD concerns.

**Comment by stubailo** [comment]
If you could split the different features into separate issues and provide some code examples of what you're looking for, that would be awesome! These seem like cool ideas for sure, but I want to make sure we can keep the discussion focused and specific.

**Comment by serle** [comment]
see #1876 + will log another one on server synchronization ideas later
