### ISSUE TITLE
Custom resolvers for pagination results

### ISSUE THREAD

**Issue by scf4** [apollographql/apollo-client#1873]
Let's say I have the following results cached:

```graphql
Thread { 
  posts (offset: 0 limit: 10) { ... }
}
```

How can I access something like 

```graphql
Thread { 
  posts (offset: 0 limit: 1) { ... }
}
```

and pull the first post from the cache?

I'm about to try something like this inside a custom resolver, but I don't know if it will work/scale well, and it seems super hacky:

```js
const customResolvers = {
  Thread: {
    posts: (thread, { offset, limit }) => {
      const data = client.store.getState().apollo.data;
      const keys = Object.keys(data);
      const posts = keys
        .filter(key => key.startsWith('Post:'))
        .map(key => data[key])
        .filter(post =>
          post.thread.id === thread.id &&
          post.threadIndex >= offset &&
          post.threadIndex < (offset + limit),
        );
      return posts.map(post => `Post:${post.id}`);
    },
  },
};
```

Is there some super-simple Apollo way to do this?

**Comment by stubailo** [comment]
The `@connection` approach should work well if what you want to do is simply ignore the `limit` argument on the client. Surprising that it's not working.

I think the custom resolver approach is the best you can do at the moment, but it might be nice to add some more metadata to the store to make it easier to find the relevant fields on the object. For example something like `client.getAllArguments(dataId, fieldName)`, which could return something like `[{ offset: 0, limit: 10 }, { offset: 0, limit: 1 }]` or similar. I think this would also be super useful for people writing mutation `update` functions.

**Comment by scf4** [comment]
@stubailo I didn't realize I needed to define`@connection` on the server. That works now.

The only problem is it seems like `fetchMore` isn't playing very nicely with it. In apollo dev tools, it looks like `thread.posts` isn't keeping all of the posts there.

This is my loadMore function:

```js
async loadMorePosts({ offset, limit }) {
      const result = await fetchMore({
        query: fetchMoreThreadPostsQuery,
        variables: {
          id: thread.id,
          offset,
          limit,
        },
        updateQuery: (prev, { fetchMoreResult }) =>
          update(prev, {
            thread: {
              posts: {
                $push: fetchMoreResult.thread.posts,
              },
            },
          }),
      });
```

**Comment by scf4** [comment]
I think `prev` isn't actually returning the current state of `thread.posts` (by accounting for the `@connection` stuff) is this intended behaviour?

**Comment by stubailo** [comment]
> I didn't realize I needed to define`@connection` on the server.

You shouldn't have to. You also don't need to update anything about `fetchMore`. Maybe there's something surprising or a bug going on!

Any chance you could submit a complete reproduction with an app we can run? In our internal tests/apps this stuff is working with no extra configuration.

**Comment by jonmanzo** [comment]
@stubailo from what I saw I'm not sure the existing test cases cover connections and fetchMore.

**Comment by jbaxleyiii** [comment]
@jonmanzo would you be able to open a failing test for connections and fetchMore? We would love to improve this!

**Comment by jonmanzo** [comment]
@jbaxleyiii That should work (well technically it shouldn't)...  LMK if you need anything else
