### ISSUE TITLE
Feature request: expose action types for redux-saga/redux-observable

### ISSUE THREAD

**Issue by rsimp** [apollographql/apollo-client#1877]
**Intended outcome:**
Expose the apollo-client redux action types officially as part of the api. Exposing them would be quite simple and would immediately make apollo compatible with libraries like redux-saga or redux-observable which have better support for long lived complex async workflows. This is specifically needed for for redux-saga's take/takeEvery and redux-observables' actions.ofType.

**Actual outcome:**
Cannot access apollo-client redux action types without looking them up in source with is inherently dangerous. Because they are not officially apart of the api they are subject to change even for minor patch changes.

**Comment by rsimp** [comment]
However it may make more sense to only use custom action types for saga/epic control mechanisms, and just give the epic/saga a client instance to manually run queries/mutations on. Just store the graphql separately so that the epics/sagas also have access to them.

**Comment by jbaxleyiii** [comment]
@rsimp we are actually in the process of removing the hard dep on redux and allowing for pluggable store implementations. When this is done, something like this can be written as part of the store API.

Thank you for your feature request!
