### ISSUE TITLE
apollo-codegen version issue

### ISSUE THREAD

**Issue by alvinvgeorge** [apollographql/apollo-client#1884]
I installed npm, added Apollo framework, generated schema. Whenever I try to run the project, it throws the following error.

Showing Recent Issues
error: The version of Apollo.framework in your project requires the use of version 0.10 of apollo-codegen, but 0.14.3 seems to be installed.

**Comment by jbaxleyiii** [comment]
@alvinvgeorge could you open an issue on codegen for this? I'm not sure of what changes would have been made to log this error?

**Comment by AnandWalvekar** [comment]
Hi @martijnwalraven @alvinvgeorge 
On building Xcode project I got error
"The version of Apollo.framework in your project requires the use of version 0.10 of apollo-codegen, but 0.16.5 seems to be installed"
Downgrading to 0.10 has solved the problem but going back shouldn't be a solution. Please let me know if we can expect the fix in future versions

**Comment by martijnwalraven** [comment]
@AnandWalvekar: This repository is for the JavaScript client, but I see you've also commented on https://github.com/apollographql/apollo-codegen/issues/48#issuecomment-325662665.
