### ISSUE TITLE
feature idea: optimistic response with debounced server-calls mutation

### ISSUE THREAD

**Issue by msand** [apollographql/apollo-client#1886]
Would it be possible to have the optimistic response update immediately, while the actual request to the graphql server would be debounced?

Such that, if the first debounced mutation sends its request and the user makes another change, then when the response from the first mutation arrives it still uses the newer optimistic response, until the second mutation response resolves the end result.

I have simple debounce working, but the optimistic response isn't used until the debounce expires, and if i remove the debounce then it makes a mutation per input event.

```js
import React from 'react';
import debounce from 'lodash/debounce';
import { gql, graphql } from 'react-apollo';
import { View, TextInput } from 'react-native';

const Note = ({ content, updateDailynote }) =>
  <View>
    <TextInput
      value={content}
      onChangeText={updateDailynote}
    />
  </View>;

const updateDailynote = graphql(
  gql`
    mutation updateDailynote($input: UpdateDailynoteInput!) {
      updateDailynote(input: $input) {
        __typename
        dailynote {
          __typename
          nodeId
          content
          dailynoteId
        }
      }
    }
  `,
  { name: 'updateDailynote' },
);

export default updateDailynote(
  ({ nodeId, content, dailynoteId, updateDailynote }) =>
    <Note
      key={nodeId}
      content={content}
      updateDailynote={debounce(
        content =>
          updateDailynote({
            variables: {
              input: {
                nodeId,
                dailynotePatch: { content },
              },
            },
            optimisticResponse: {
              __typename: 'Mutation',
              updateDailynote: {
                __typename: 'UpdateDailynotePayload',
                dailynote: {
                  __typename: 'Dailynote',
                  nodeId,
                  content,
                  dailynoteId,
                },
              },
            },
          }),
        500,
      )}
    />,
);

```

**Comment by jbaxleyiii** [comment]
@msand I wonder if this is the best approach? Since you are binding direct user interaction, it seems to me using a combination of local component state + a delayed mutation would be the better option? It will be more performant as it doesn't go through any Apollo store actions, nor would rerender the graphql wrapper.

When possible, I'd like to steer clear of debouncing in library code since it is pretty much always tied to direct UI piping which is the better place to implement the delay

**Comment by msand** [comment]
Yeah, I'm wondering the same thing as well, before I simply used a stateful component like this:
```js
export default class Note extends Component {
  state = {};
  componentWillReceiveProps() {
    this.setState({});
  }
  onChangeText = text => {
    this.setState({ text });
    this.props.updateDailyNote(text);
  };
  render() {
    return (
      <Box>
        <TextInput
          multiline
          numberOfLines={3}
          onChangeText={this.onChangeText}
          placeholder={'Tyhjä muistiinpano'}
          value={this.state.text || this.props.content}
        />
      </Box>
    );
  }
}
```

Where the this.props.updateDailyNote is already debounced.

Somehow it feels unnecessary to have a stateful component, when the needed data / structure already exists in redux, and optimistic updates can achieve the same thing. If redux didn't already have the right data and structure, it would seem like the obvious choice to make the component stateful. Seems mostly like a tradeoff of duplication, computation and conciseness of code.

**Comment by msand** [comment]
At least in this case, the data is only used in one place, and thus is fine to keep only in local encapsulated state of one component.

The principle of "When possible, I'd like to steer clear of debouncing in library code" seems sound and doesn't cause any unwanted computation or library code. It merely requires having one component be stateful instead of pure. As such, this is not an actual issue for going forwards. Feel free to close this and reject the pull request, unless something new comes to mind.

**Comment by jbaxleyiii** [comment]
@msand thank you for the great responses! I really appreciate the thoroughness of them. I will close this issue, but as a heads up, we are working on a new way to compose a client which would make this possible on the client level if desired. I'll ping you when it is ready if you want to take a stab at writing a package for debouncing!

**Comment by lambert-velir** [comment]
@jbaxleyiii @msand I'm struggling with this right now.  I've typed up my problem on Stacked Overflow. 

https://stackoverflow.com/questions/45683687/apollo-mutation-debounce-and-race-conditions

Any ideas?

**Comment by grimunit** [comment]
I'm struggling with this exact same issue. I've tried a lot of different approaches such as setting local state, using every different component lifecycle method, using the apollo update method and even using `react-debounce-input` component. However they all end up with the same result. 

Basically if I add a debounce to anything that calls an apollo mutation, the component that called the debounce method gets re-rendered with the old value before immediately re-rendering with the new value that comes from the network. As an example, I change an input value from `Foo` to `Bar`. The debounce waits 2 seconds before firing the mutation, after it fires the mutation the component immediately re-renders with the input saying `Foo` for like under 100ms. Then the network returns the mutation result and immediately switches it back to `Bar`. 

I'm not saying this is a problem with Apollo, but have been unsuccessful in finding any resolution and wanted to also give my feedback. Any more insights from anyone?

**Comment by grimunit** [comment]
Actually it turns out that I was calling another redux action creator within the same function that does the mutation which would cause the extra re-render. After removing the other action call it no longer does the extra re-render.

**Comment by renatorib** [comment]
Same use case here. 👍

**Comment by msand** [comment]
@renatorib You can just make a stateful component, which keeps the latest input value as long as there are any outstanding debounced mutations, just store the promises until they reject or resolve. If another mutation happens while an earlier one is still in flight, it'll behave the same way as when there's only a single mutation. When all promises have finished you can just use the latest response and clear the state. 
I think Apollo client v2 should actually do this correctly anyway, at least from a quick reading of the source:
https://github.com/apollographql/apollo-client/blob/2818c29f95ea54a4ed316787ec2577c0978c84d6/packages/apollo-client/src/data/store.ts#L74-L208
https://github.com/apollographql/apollo-client/blob/master/packages/apollo-cache-inmemory/src/inMemoryCache.ts#L149-L204
Seems if a mutation resolves and another optimistic response exists, it will apply the optimistic response on top, until the they've all resolved. What versions are you  using?

**Comment by renatorib** [comment]
I'm doing something like this. I'm saving in a local state and cleaning it by `componentWillReceiveProps`
