### ISSUE TITLE
Merging incomplete mutation causes data loss

### ISSUE THREAD

**Issue by CodogoFreddie** [apollographql/apollo-client#1888]
Performing a mutation that adds an object to a collection will cause a watched query to fail, if the mutation does not return all the fields included in the  original query

**Intended outcome:**

Performing a mutation that does not return all the data needed to fully update any relevant queries should either provide as much data as possible, or display a warning by default.

**Actual outcome:**
Performing the `Original Mutation`  bellow caused the `getListing` property returned from `Original Query` to be deleted; not `undefined`, the property was not present on the object returned from  the `watchQuery`.

Changing to the `Working Mutation` caused the query  to update correctly.

A warning message was generated  after I gave the `Original Query` a custom `reducer`, but this warning should have been present from the start.

This mutation failing silently and with no information has cost us 2 days of development time.

**How to reproduce the issue:**
`Orignal Query`:

```
query getListing($id: ID!) {
	getListing(id: $id) {
		id
		locations { edges { node {
			id
			name
			active
			googlePlaceID
			address
			types
		} } }
	}
}
```

`Original Mutation`:

```
mutation CreateLocation($location: CreateLocationInput!) {
	createLocation(input: $location) {
		clientMutationId
		changedLocation {
			id
			name
		}
	}
}
```

`Working Mutation`:

```
mutation CreateLocation($location: CreateLocationInput!) {
	createLocation(input: $location) {
		clientMutationId
		changedLocation {
			id
			name
			oldID
			active
			googlePlaceID
			address
			types
		}
	}
}
```

I can provide more  information, examples, or access to our servers if this would be helpful.

**Comment by CodogoFreddie** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10216404-256758121_2-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by harunsmrkovic** [comment]
The same thing is happening for me... identical reproduction steps, Apollo version 1.4.10

**Comment by CodogoFreddie** [comment]
Please reopen this issue, It's still a problem
