### ISSUE TITLE
APOLLO_MUTATION_ERROR action not processed correctly

### ISSUE THREAD

**Issue by igo** [apollographql/apollo-client#1893]
APOLLO_MUTATION_ERROR action is not processed correctly and therefore state is not changed (eg. mutation loading state). This issue can be observed also in demo implementation on http://demo.learnapollo.com/ with redux dev tools. APOLLO_MUTATION_INIT and APOLLO_MUTATION_RESULT seems to work correctly.

UPDATE: https://github.com/apollographql/apollo-client/blob/master/src/mutations/store.ts#L56 seems `return newState;` is missing. Unfortunately after adding this line another bug appeared.

**Comment by jbaxleyiii** [comment]
@igo would you be able to open a PR with a failing test or perhaps a reproduction?

**Comment by igo** [comment]
Unfortunately no 😞, I dont do typescript.
