### ISSUE TITLE
Adding AuthMiddleware after client creation

### ISSUE THREAD

**Issue by pfrendo** [apollographql/apollo-client#1894]
Is there I way I can add middleware after the ApolloClient has been initialized? As I need the token to be injected as it's constantly changing. Thanks !

**Comment by lobnico** [comment]
Middleware allows to access to context object where you would put
your request object.
It is largely described in documentation and starter kits

```
//
// Register API middleware
// -----------------------------------------------------------------------------
const graphqlMiddleware = graphqlExpress(
  req => ({
    schema,
    context: { request: req },
  })
);

```
this context is now attached to your client resolver functions

userQueryResolver = async (source, variables, context, info) => { 
  console.info({ requestObj: context.request })
}

**Comment by jurajkrivda** [comment]
```
export const addTokenInMiddleware = (client, token) => {
  if (typeof client.networkInterface.use === 'function') {
    client.networkInterface.use([
      {
        applyMiddleware(req, next) {
          req.options.headers = {
            ...req.options.headers,
            authorization: token ? `Bearer ${token}` : null,
          };
          next();
        },
      },
    ]);
  } else {
    // mock interface
    client.networkInterface.__accessToken = token;
  }
};
```

**Comment by pfrendo** [comment]
@lobnico @jurajkrivda

I think it's best I open this issue on the angular client as it has to do with module loading... My bad for not opening it there actually as my description didn't quite go into detail about the problem.

Thanks for the info tho !
