### ISSUE TITLE
Do the caching features works great with Ionic 2/3 in Android and iOS devices?

### ISSUE THREAD

**Issue by yuricamara** [apollographql/apollo-client#1895]
Hi folks,

Since I don't know how the caching mechanism of Apollo Client works, I feel a little bit insecure in using this feature inside these environments.

**Comment by stubailo** [comment]
Yeah it works just fine in any JavaScript environment!

**Comment by yuricamara** [comment]
Where data is cached by Apollo Client?

**Comment by yuricamara** [comment]
> Where data is cached by Apollo Client?

From [Facebook Group:](https://www.facebook.com/groups/graphql.community/permalink/1180951188677465/)
> Where does Apollo Client store data from queries to make its caching system works?
> Currently all data is stored in Redux, and you can look at Redux devtools or Apollo devtools to see what data is in the cache. (by @stubailo )

Ok. Thank you folks!

Congratulations for the nice job! ;-)

**Comment by stubailo** [comment]
Thanks!
