### ISSUE TITLE
Misleading Redux Actions in Regards to Query Deduplication

### ISSUE THREAD

**Issue by enjoitheburger** [apollographql/apollo-client#1896]
**Intended outcome:**
Unable to tell if queryDeduplication is actually working from inspecting the list of redux actions in a tool such as redux-devtools. One might expect that `APOLLO_QUERY_INIT` and `APOLLO_QUERY_RESULT` would actually initialize and resolve a network call.

**Actual outcome:**
`APOLLO_QUERY_INIT` and `APOLLO_QUERY_RESULT` are called for every possible query regardless of whether they actually hit the network layer.

Is this behavior intended?

**Comment by jbaxleyiii** [comment]
@enjoitheburger what version are you using? I believe this is the expected behavior since the client will need to update every observer for each query even if it is deduped. Are you seeing a bug related to deduplication?

**Comment by enjoitheburger** [comment]
De-duplication seems to work fine as far as I can tell from the logs in our backend. My concern was that the `APOLLO_QUERY_RESULT` actions fired for each one to be a little misleading. It would be cool if only one of them fired `APOLLO_QUERY_RESULT` and the rest fired off an `APOLLO_QUERY_RESULT_CLIENT`. 

This would have also prevented a bug where we have some middleware that performs decryption on the `action.result.data`. We were starved for something like `APOLLO_QUERY_DEDUPED_RESULT` to hook our decryption on (Although I think the solution above is much better).
