### ISSUE TITLE
refetchQueries after mutation

### ISSUE THREAD

**Issue by tokenvolt** [apollographql/apollo-client#1900]
**Intended outcome:**

I'm trying to refetch some queries after the mutation and I expect them to be executed.

**Actual outcome:**

refetchQueries are not working as they are described [in the docs](http://dev.apollodata.com/core/apollo-client-api.html#ApolloClient.mutate)

**How to reproduce the issue:**

```js
mutate({
  mutation: LOGIN_MUTATION,
  variables: {
    ...values
  },
  refetchQueries: [USER_QUERY]
})
```
LOGIN_MUTATION and USER_QUERY are strings in graphql syntax. I don't see USER_QUERY gets executed after the mutation.

**Comment by n1ru4l** [comment]
From the documentation:

> **A list of query names** which will be refetched once this mutation has

Also you will have to convert your `LOGIN_MUTATION ` graphql strings to a GraphQL AST by using  [graphql-tag](https://github.com/apollographql/graphql-tag)

It should look like this:

```javascript
import gql from 'graphql-tag'

const USER_QUERY = gql`
  query currentUser {
    id
    login
  }
`

const LOGIN_MUTATION = gql`
  mutation login {
    login(login: "foobars")
  }
`
[...]

mutate({
  mutation: LOGIN_MUTATION,
  variables: {
    ...values
  },
  refetchQueries: [`currentUser`]
})


```

**Comment by tokenvolt** [comment]
I'm using graphql-loader and writing mutations and queries in separate graphql files. How should I approach this way? BTW I've tried to use gql and use the name of the query, but it doesn't work as well.

**Comment by n1ru4l** [comment]
then you should probably create a reproduction with https://github.com/apollographql/react-apollo-error-template . I never user refetchQueries so my knowledge is limited to the documentation 😞

**Comment by lucfranken** [comment]
See also: https://github.com/apollographql/apollo-client/issues/1697 where I tried to figure out the same problem. Did not find a really good solution yet but it may give you some insight in the options.

**Comment by jbaxleyiii** [comment]
@tokenvolt I think this may be a shape issue within refetchQueries. Can you try

```
refetchQueries: [
{ query: USER_QUERY }
]
```

The object is needed in order to support things [like variable changes](http://dev.apollodata.com/react/cache-updates.html#refetchQueries)

**Comment by tokenvolt** [comment]
@jbaxleyiii still no luck

**Comment by jbaxleyiii** [comment]
@tokenvolt do you think you could create a simple reproduction for this? We have an error template and code sandbox listed in the issue template (try to create a new issue and it should be there) or a failing test?

**Comment by tokenvolt** [comment]
@jbaxleyiii I'll try to reproduce

**Comment by ctavan** [comment]
@tokenvolt FYI I was also not lucky with using the query-name based variant of `refetchQueries`. While it _should_ work as expected there currently seems to be a race-condition which effectively prevents it from working, see https://github.com/apollographql/apollo-client/issues/1821

In principle though, the query-name based `refetchQueries` is an expected feature, here's the implementation:
* https://github.com/apollographql/apollo-client/blob/3b5045dfe74183fe060d2027e31317d890755b99/src/core/QueryManager.ts#L351-L355
* https://github.com/apollographql/apollo-client/blob/3b5045dfe74183fe060d2027e31317d890755b99/src/core/QueryManager.ts#L1305-L1322

**Comment by tokenvolt** [comment]
Hey, guys, I figured out that it was an issue in my application. Sorry for bothering, as it was just a stupid mistake on my side. `refetchQueries` works as it was mentioned in https://github.com/apollographql/apollo-client/issues/1900#issuecomment-315765415

**Comment by abraga** [comment]
For those who are still having this problem, try putting `refetchQueries` inside `options`: 

```
name: '...',
options: {
  refetchQueries: [USER_QUERY]
}
```

**Comment by tsvetann** [comment]
@abraga still doesn't work for me

**Comment by SebastianMuniz** [comment]
Hey I'm experiencing same problme, any solutions?? none of the things mentioned above solved the issue. Everything is working fine, but refetchQueries

**Comment by wesbos** [comment]
Same issue here - I can manually call `.refetch()`, but this doesn't seem to trigger

**Comment by SebastianMuniz** [comment]
@wesbos Hi Wes how you doing? I had to use a workaround here, I imagine you are using a state container(Redux, Mobx), so you have the records collection in your store and every time you make a mutation, select all the objects fields, once the response comeback you can use that data to merge it into your existing records collection. Do you catch the idea?

**Comment by wesbos** [comment]
I'm not using any sort of state container outside of Apollo - so I'm not sure this applies

**Comment by yellowspaceboots** [comment]
I was having a similar issue trying to refetch a query after my login mutation. But I placed some console.logs and it looks like in my issue it may just be an async issue. My mutation is firing first but the query is firing before my result gets back so it makes the query i am firing appear to have no change in my UI. I tried simply wrapping my resolver in async/await but of course it was not that easy :P

**Comment by wesbos** [comment]
So did you figure it out?

**Comment by yellowspaceboots** [comment]
@wesbos My query is taking my userId through apollo's context object. I believe that the query is firing before I can set the context so it still sees context.userId as undefined and so my query appears to be the same as when my user was logged out. If I run the query again it updates as it is supposed to because now that my user is logged in the context is set. I am in the middle of trying to figure it out but I believe [apollo-link-context](https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-context) is what I am looking for but no I have not solved it yet.

**Comment by yellowspaceboots** [comment]
So I ended up solving my issue for the most part. I needed to wrap my login resolver to return a Promise. What was happening is my context was being updated before I received my login token. If your refetch queries is firing before your login process is finished than the query will appear to not change. I am not sure if this helps but I wanted to share what I found.

**Comment by markzrt** [comment]
works well when you use optimisticResponse :(

**Comment by Cabezaa** [comment]
after a while, i used the reply of @abraga like a started point, and search in other issiues and found that, the way that i be able to solve this problem was


the code that @abraga supply was

```
name: '...',
options: {
   refetchQueries: [USER_QUERY]
}
```

Instead, I used:

```
name: '...',
options: {
   refetchQueries: [{query: USER_QUERY}]
}

```

I'm using "withApollo" HOC and graphql as an decorator.

**Comment by mariomelo** [comment]
Guys, just a heads-up:

When using React, if you call `this.props.mutate({ options: {refetchQueries: [ 'queryToRefetch']}})` it doesn't work. However, if you pass the `options` parameter to the `graphql` function it works.

```javascript
...

export default graphql( my_mutation, { name: 'my_mutation', options: {refetchQueries: [ 'queryToRefetch']} } ) ( MyComponent)

```

**Comment by Aetherall** [comment]
Use a Map to pass the limitation

https://github.com/apollographql/react-apollo/blob/4285679f59af2c5b9e6ba0076c9aaabe30f50a2f/src/Mutation.tsx#L196

```js
mutate({
  .........,
  refetchQueries: new Map([[0,'todolist'],[1, 'todogroups']])
})

function bypass(...queryNames){
  return new Map(queryNames.map((name, i) => [i, name])
}

mutate({
  .........,
  refetchQueries: bypass('todolist', 'todogroups')
})

```

**Comment by waclock** [comment]
I'm having an issue re-rendering the component.

1- I have an index showing basically all my bank accounts (it uses bank account query)
2- I have a modal, which is a form and adds a new bank account. When the modal is open, the index is in the back.
3. When the mutation adding a new bank account is done, refetchQueries is called (I can see in the network tab the query is done) and also the store is updated (I can see so looking at the apollo devtools)
4. Even though the store is updated and the query is executed, the "index" of bank accounts is not updated. I'm not sure what could be the problem.

**Comment by wzup** [comment]
Same error
https://github.com/apollographql/graphql-tutorial/issues/46

**Comment by wzup** [comment]
@abraga 
> try putting refetchQueries inside options:

What `options` are you talking about? The options you provide are the only options. You can't have `options.options`. 
Read https://www.apollographql.com/docs/react/api/apollo-client.html#ApolloClient.mutate

How can you specify `options` here?
```
    this.props.client.mutate({
      mutation: CreatePatientMutation,
      refetchQueries: ['getPatientDetailsQuery'],
      options: ???? // HOW?
      variables: {
        foo: 'bar'
      }})
        .then(res => {
        })
        .catch(err => {
        });
```

**Comment by smeijer** [comment]
Experiencing a similar situation as @waclock. I see that new data is being fetched, but the component depending on that query doesn't update.

**Comment by slorenzo** [comment]
Hi guys!
I solved this problem with the following code:
```
<Mutation
  mutation={REMOVE_USER}
  variables={{ userId: user.id }}
  refetchQueries={[{ query: GET_USERS }]}  // <--- HERE
>
  {removeUser => (
    <button onClick={removeUser}>Remove User</button>
  )}
</Mutation>
```

Hope it helps.

**Comment by borisyordanov** [comment]
@slorenzo I have the same setup, the queries and run, but none of the components update. Any idea why?

**Comment by MitchEff** [comment]
How on earth is this SO complicated? I've seen about 7 or 8 totally different "solutions" so far (none of which work for me, because reasons), and the documentation sucks. 

Does it keep changing, or does nobody know how this works, or are there several ways to achieve this?

**Comment by cihadturhan** [comment]
This is complete nonsense and yes @MitchEff 's solution works:
```js
await client.mutate({
        mutation: COMPLETE_CHALLENGE,
        variables: data,
        refetchQueries: () => [{query: UNCOMPLETED_CHALLENGES}]
})
```

**Comment by joseffb-mla** [comment]
I get error back of You must wrap the query string in a "gql" tag. when I add the query name.

``` refreshQuer = [{
        query: ['GetCollectionByUserId'],
        variables: { userId : userId, first : 100, last : 0, cursor : "" },
    }] ```

adding the query itself does nothing.

**Comment by joseffb-mla** [comment]
ok so  passing the entire query seems to be accepted (no error) but also my data is still old. is there another promise I need to process on to wait for the second query to process before I pass to he result to the calling method?

```
query: gql`${CollectionsByUserID}`,
```

right now I do mutate {blah blah).then(stuff) is there now a new var passed to then to tell me when the refresh has occurred or will it only pass me stuff for the then after it's mutated AND refreshed the cache. Thanks for any help.

**Comment by joseffb-mla** [comment]
Solved: had to add awaitRefetchQueries = true to my options array.

**Comment by tahmidrahman-dsi** [comment]
This worked for me. Thanks to @slorenzo 's [solution](https://github.com/apollographql/apollo-client/issues/1900#issuecomment-429509025)

`client.mutate({
              mutation,
              variables,
              refetchQueries: [
                { query: ...name, variables: {  ...queryVariables  } }
              ]
            })
`

**Comment by roelzkie15** [comment]
Any idea how do we get the response data from `refetchQueries`? I got the query response data from mutation.

##### Mutation
```
import { gql } from 'apollo-boost';

export const DONE_TASK = gql`
    mutation DoneTask($taskId: ID!) {
        doneTask(input: {
            taskId: $taskId
        }) {
            task {
                id
                status
            }
        }
    }
`;
```
 
##### Query
```
import { gql } from 'apollo-boost';

export const GET_TASKS_BY_STATUS = gql`
    query GetTasksByStatus($status: String!) {
        getTasksByStatus(status: $status) {
            edges {
                node {
                    id
                    status
                    description
                }
            }
        }
    }
`;
```

##### Usage

```
const response = await client.mutate({
    mutation: DONE_TASK,
    variables: {
        taskId: 1
    },
    refetchQueries: () => [{
        query: GET_TASKS_BY_STATUS,
        variables: { 
            status: "OPEN"
        },
    }]
});

console.log(response);
```

##### Output

```
data: {
    doneTask: {
        task { id:  1, status: 'DONE'}
    }
}
```

But I expect a response data from `GET_TASKS_BY_STATUS`. 🤔 😕

**Comment by tayloraucoin** [comment]
Still experiencing this issue.  I've tried the solutions listed with no success.  Will be diving into the race issue listed as I have yet to explore that potential.

Here is where I'm at with no luck:

```
// NOTHING UPDATES on session update
function App({ apolloClient }) {
    const { loading, error, data } = useQuery(GET_CURRENT_SESSION);

    if (loading) return null;
    if (error) console.log('error', error);
    const { session } = data;
    console.log('app session', session);  // NO UPDATE

    return (
        <Router history={history}>
            ...
            <Authentication/>
            ...
        </Router>
    );
}

// UPDATES on session.isLoading update
function Authentication(props) {
    ....
    updateSessionLoading({ 
        variables: { loading: true },
        options: {
            refetchQueries: () => [{ query: GET_CURRENT_SESSION }],
            awaitRefetchQueries: true
         }
    });
    ....
    return (
        ...
    )
}
```

**Comment by jwld** [comment]
This library is so broken...

**Comment by nik-lampe** [comment]
Maybe this helps:

When I'm loading the query from a .graphql file via graphql.macro the refetch doesn't work.
But when I'm declaring it with gql, it works just fine. 

```

const [mutate] = useMutation(ASSIGN_QUESTIONNAIRE_FOR_USER, {
    variables: { userId: clientId },
    refetchQueries: ['questionnaires'],
    awaitRefetchQueries: true,
})

await mutate({
    variables: { templateId: id },
})
```

I wanted to recreate it with codesandbox but I can't find any public graphQL API, where I can write data.

**Comment by hbw3** [comment]
> This is complete nonsense and yes @MitchEff 's solution works:
> 
> ```js
> await client.mutate({
>         mutation: COMPLETE_CHALLENGE,
>         variables: data,
>         refetchQueries: () => [{query: UNCOMPLETED_CHALLENGES}]
> })
> ```

How did you get "refetchQueries" response

**Comment by wosephjeber** [comment]
I've been wrestling with getting the Apollo client to wait for the queries specified in `refetchQueries` to resolve before resolving the mutation promise and wanted to chip in with something I just learned in case it helps anyone still struggling with this.

For one, you need the `awaitRefetchQueries` option to be set to `true` on the mutation. But even with that set, it seems that the `fetchPolicy` of the watched query that you're refetching makes a difference if you're specifying those `refetchQueries` by strings.

For example, given a mutation a call like this:

```js
await client.mutate({
  mutation: MUTATION,
  variables: data,
  refetchQueries: ['QueryName'],
  awaitRefetchQueries: true
})
```

The `client.mutate` promise will resolve too soon if that query was called with the `cache-and-network` fetch policy. But if that query uses `cache-first` or `network-only`, I'm seeing that the mutation promise waits until the refetch query resolves, as expected.

**Comment by MAzeem6778** [comment]
> @tokenvolt I think this may be a shape issue within refetchQueries. Can you try
> 
> ```
> refetchQueries: [
> { query: USER_QUERY }
> ]
> ```
> 
> The object is needed in order to support things [like variable changes](http://dev.apollodata.com/react/cache-updates.html#refetchQueries)

worked.

**Comment by Sphinxs** [comment]
My solution to refetch using variables:

```
import { gql, useApolloClient } from "@apollo/client";

const client = useApolloClient();

const SEARCH_PROJECTS = gql``

await client.query({
          query: SEARCH_PROJECTS,
          variables: { page: 1, limit: 1 },
          notifyOnNetworkStatusChange: true,
          fetchPolicy: "network-only"
})
```

See more about the fetch policy [here](https://medium.com/@galen.corey/understanding-apollo-fetch-policies-705b5ad71980).

**Comment by Cabezaa** [comment]
> > This is complete nonsense and yes @MitchEff 's solution works:
> > ```js
> > await client.mutate({
> >         mutation: COMPLETE_CHALLENGE,
> >         variables: data,
> >         refetchQueries: () => [{query: UNCOMPLETED_CHALLENGES}]
> > })
> > ```
> 
> How did you get "refetchQueries" response

Hi @hbw3 , sorry for the big delay, but i hope this post helps other people that have the same question as you.

All refetch queries are managed as normal queries, so we have access to all methods as if we are calling a individual one. You can check this in the [documetation](https://www.apollographql.com/docs/react/caching/advanced-topics/#updating-after-a-mutation).

So, a example for this is:

```
useMutation(MUTATION_GQL, {
    variables: {
        id: variable_mutation,
    },
    refetchQueries: [
        {
            query: QUERY_1,
            variables: {
                id: variable1,
                some: variable2,
                fetchPolicy: 'network-only',
                onCompleted: data => {
                    console.log(data)
                },
                onError: data => {
                    console.error(data)
                },
            },
        },
        {
            query: QUERY_2,
            variables: {
                id: variable3,
            },
        },
    ],
    
});
```
As u can see, in onCompleted we have access to the result of refetchQuery and we can use this to do whatever we want. Same with the onError function.
For more information about the accepted params you can check this [section](https://www.apollographql.com/docs/react/data/mutations/#options)

**Comment by andefred** [comment]
If anyone runs into this same issue, what fixed it for me since I've never had any issues with refetchQueries before, was this:

I had a loop over a child collection, and was then fetching the parent in a refetchQueries when a child was deleted. Setting the id or the child as key somehow made a difference... `rule.id` below

```javascript
{data.rules_RuleSet &&
        data.rules_RuleSet.rules.map((rule, i) => <Rule rule={rule} key={rule.id} ruleSetId={ruleSetId} />)}

**Comment by jordiup** [comment]
The thing that fixed it for me was changing the `fetchPolicy` on the awaiting component. So that it didn't default to using the cache

const { data, error } = useGetProductsQuery({
    fetchPolicy: 'cache-and-network'
  });

**Comment by deepakbhattmits** [comment]
Hi @tokenvolt ,

I wanted to ask one question if we have fire any useMutation after that refetchQueries I want to display that data into the UI how to do that.

```
  const[signup,{loading,data,error}]=useMutation(SIGN_UP,{
    refetchQueries: [
      { query: CURRENT_USER }
    ]})
```

I want to print current User in the screen

**Comment by tufail** [comment]
I am still having the issue, I am getting null value in data result but the same query is returning value in POSTMAN app. Is anyone faced the same issue 
```
const [addItem, { loading, data, error }] = useMutation(ADD_ITEM, {
    refetchQueries: () => [{ query: GET_ITEMS }],
    awaitRefetchQueries: true,
  });
````

Response:
`{"data":{"items":null}}`
