### ISSUE TITLE
@connection (w key & filter) fetchMore bug

### ISSUE THREAD

**Issue by jonmanzo** [apollographql/apollo-client#1906]
This is related to #1873 as I believe it likely explains the fetchMore issue, though opening a new bug as it does not reference customResolvers.

**Intended outcome:**
Paginated fetchMore utilizing connection w/ key and filter should result in data of [0,1,2,...,24,25,26,...,48,49]

**Actual outcome:**
The updated store result looks like this... [0,1,2,...,24,0,1,...,23,24]

**Version**
- apollo-client@1.9.0-0 was present on 1.8.x as well

**What I Found**
Seems that when running a fetch more using a connection, [APOLLO_QUERY_RESULT](https://github.com/apollographql/apollo-client/blob/master/src/core/QueryManager.ts#L1221) is dispatched upon receiving the fetchMore response, before updateQuery runs.  This effectively resets the store for the query to the new response data. Execution then reaches updateQuery and completes as expected, and the end result is 2 copies of each fetchMore result. So to explain as per below outcomes:

**Query Store at point in time**
1. When fetchMore is executed: [0,1,2,...,23,24] (populated by initial query response)
2. After APOLLO_QUERY_RESULT is dispatched: [25,26,...,48,49]
3. After updateQuery and APOLLO_UPDATE_QUERY_RESULT is dispatched: [25,26,...,48,49,25,26,...,48,49]  

All that said, I dug and stepped through everything and believe I have it all squared away, though only within the distribution code, but I will outline and hopefully it helps...

## Local code updates
Remember this is the distribution code...
QueryManager.js 

added  -- `&& !fetchMoreForQueryId` --  [here](https://github.com/apollographql/apollo-client/blob/master/src/core/QueryManager.ts#L1217) as to prevent the dispatch in a fetchMore flow preferring to wait for the UPDATE dispatch post updateQuery
```javascript
if (requestId >= (_this.lastRequestId[queryId] || 1) && !fetchMoreForQueryId) {
    _this.disableBroadcasting = true;
    _this.store.dispatch({
        type: 'APOLLO_QUERY_RESULT',
        document: document,
        variables: variables ? variables : {},
        operationName: getOperationName(document),
        result: result,
        queryId: queryId,
        requestId: requestId,
        fetchMoreForQueryId: fetchMoreForQueryId,
        extraReducers: extraReducers,
    });
    _this.disableBroadcasting = false;
    var reducerError = _this.getApolloState().reducerError;
    if (!reducerError || reducerError.queryId !== queryId) {
        _this.queryStore.markQueryResult(queryId, result, fetchMoreForQueryId);
        _this.broadcastQueries();
    }
}
```

Added queryId as to return the requesting queryId to ObservableQuery
 [here](https://github.com/apollographql/apollo-client/blob/master/src/core/QueryManager.ts#L1289)
```javascript
resolve({ queryId: queryId, data: resultFromStore, loading: false, networkStatus: NetworkStatus.ready, stale: false });
```
and  [here](https://github.com/apollographql/apollo-client/blob/master/src/core/QueryManager.ts#L534)
```javascript
return Promise.resolve({ queryId: queryId, data: storeResult });
```

ObservableQuery.js - [here](https://github.com/apollographql/apollo-client/blob/162e5cc9597d77f98c84ac507d8ef7417121870c/src/core/ObservableQuery.ts#L294) Made below changes to update network status etc
Changed from this (ts):
```javascript
this.updateQuery(mapFn);
return fetchMoreResult as ApolloQueryResult<T>;
```
to this (distributed)
```javascript
var newResult = _this.updateQuery(mapFn);
_this.queryManager.queryStore.markQueryResult(fetchMoreResult.queryId, newResult, _this.queryId)
_this.queryManager.broadcastQueries()
return fetchMoreResult;
```

## Project Query Code

**ALL_ITEMS_QUERY**
```graphql
#import "../fragments/_CoreItem.graphql"

query AllItems($aspect: AspectRatio, $width: Int, $devicePixelRatio: Int, $sortAttribute: SortBy!, $order: SortOrder!, $cursor: String, $limit: Int, $query: String) {
  items(sort:[{attribute:$sortAttribute, order:$order}],  cursor: $cursor, limit: $limit, query: $query) @connection(key: "AllItemsQuery" filter:["query"]) {
    count
    cursor
    has_next
    has_prior
    data{
      ...CoreItem
    }
  }
}
```
**Query options**
```javascript
const QUERY_OPTIONS = {
  options: props => {
    return {
      variables: {
        ...itemBaseVariables(),
        limit: 25,
        query: allItemsQueryString({
          searchText: props.searchText,
          limit: 25,
          sort: (props.sortField && props.sortOrder) ? [{ [props.sortField]: props.sortOrder }] : []
        })
      },
      notifyOnNetworkStatusChange: true,
      fetchPolicy: (props.forceReFetch) ? 'cache-and-network' : 'cache-first'
    }
  },
  props: ({ ownProps, data: { refetch, fetchMore, networkStatus, error, items = {} } }) => {
    return {
      error,
      loading: networkStatus < 6,
      refetch,
      items: items.data,
      count: items.count,
      cursor: items.cursor,
      hasNext: items.has_next,
      loadMoreItems: () => {
        return fetchMore({
          query: All_ITEMS_QUERY,
          variables: {
            ...itemBaseVariables(),
            cursor: items.cursor,
            limit: 25,
            query: allItemsQueryString({
              searchText: ownProps.searchText,
              limit: 25,
              sort: (ownProps.sortField && ownProps.sortOrder) ? [{ [ownProps.sortField]: ownProps.sortOrder }] : []
            })
          },
          updateQuery: (prev, { fetchMoreResult }) => {
            const newItems = _.get(fetchMoreResult, 'items.data');
            if (!newItems || !_.get(prev, 'items.data') return
            const result = update(prev, {
              items: {
                cursor: { $set: fetchMoreResult.items.cursor },
                has_next: { $set: fetchMoreResult.items.has_next },
                has_prior: { $set: fetchMoreResult.items.has_prior },
                data: {
                  $push: newItems,
                },
              },
            });
            return result
          },
        });
      },
    };
  },
};
```

**Comment by jbaxleyiii** [comment]
@shadaj can you take a look at this?

**Comment by jbaxleyiii** [comment]
fixed in the next release! Thank you!
