### ISSUE TITLE
Skipping query causes errors if trying to access undefined properties in a function assigned to options property

### ISSUE THREAD

**Issue by lauriii** [apollographql/apollo-client#1912]
**Intended outcome:**
According to the [documentation](http://dev.apollodata.com/react/queries.html#graphql-ski), I would expect to skip property to prevent function assigned to options property from being run, and not cause errors in case the function tries to access properties that do not exist if the skip property is true.

**Actual outcome:**
If trying to access properties that do not exist in the function assigned the options property, I would not expect it to throw errors if skip property has been set true.

**How to reproduce the issue:**
https://codesandbox.io/s/76rwzN0oB

**Version**
- apollo-client@1.8.1

**Comment by jbaxleyiii** [comment]
@lauriii sorry about this! It came with a bug introduced in react-apollo 1.4.3. Can you confirm what version of the react integration you are using?

https://github.com/apollographql/react-apollo/issues/830 is the current issue tracking this bug. If this is a different case, could you open an issue on react-apollo? `skip` is only an option from that integration
