### ISSUE TITLE
__typename in query response

### ISSUE THREAD

**Issue by seeden** [apollographql/apollo-client#1913]
When I use next query

```
videoQuiz(slug: $slug) {
      id
      slug
      title
    }
```

I get next response:
```
{
   id: ...
   slug: ...
   title: ...
   __typename: ...
}
```

I know and understand that apollo-client will add __typename automatically into the query. But my question is if it is all right that I will get it in my response. Currently I am using this object as input for mutation which is defined as

```
 myMutation(input: MyInput): MyPayload

input MyInput {
  id
  slug
  title
}
```

And therefore I need to remove __typename for each mutation. 
I do not want to complain. I am just asking if it is feature or bug.

**Comment by jbaxleyiii** [comment]
@seeden it is the intended default behavior. Apollo Client uses  `__typename` in order to determine a data id when handling cache updates (https://github.com/apollographql/apollo-client/blob/master/src/ApolloClient.ts#L85-L95). It also is helpful to not strip them to the end result for doing optimistic updates based on previous data since `__typename` is part of that response data!

I hope this was helpful! If not, please feel free to reopen the issue and we can keep discussing it 👍

**Comment by mhlavacka** [comment]
Sorry for reopening, but it doesn't make sense to me. You can't mutate with `__typename` key name otherwise you need to include it inside of your schema on each nested object.

**Comment by jjant** [comment]
@jbaxleyiii Agreed with @mhlavacka, this field breaks my mutations.

**Comment by Dishant15** [comment]
I am having same problem. I am parsing long list of data and at the end i have to test for __typename and remove it manually every time. That is huge waste of time... any solutions to remove this from query ?

**Comment by mhlavacka** [comment]
You can remove it by adding `addTypename: false` in your Apolloclient init:
```js
const client = new ApolloClient({
  networkInterface,
  addTypename: false
});
```

**Comment by danderson00** [comment]
@jbaxleyiii It would be useful to know exactly the consequences of turning this off. I can't quite piece it together from the various issues on the topic. I'm assuming turning this off will break caching in some way?

**Comment by wawhal** [comment]
`addTypename` field must be set to ``false`` in the `InMemoryCache` constructor

```javascript
const client = new ApolloClient({
  link: new HttpLink({uri: MY_URL}),
  cache: new InMemoryCache({
    addTypename: false
  })
});
```

**Comment by Access2emma** [comment]
Does anybody have a script to remove __typename from nested object of Query response?

**Comment by danderson00** [comment]
I'd recommend against introducing a dependency just to do this:

```Javascript
const omitTypename = (key, value) => (key === '__typename' ? undefined : value)
const newPayload = JSON.parse(JSON.stringify(payload), omitTypename)
```

As far as setting the `addTypename` option in the `InMemoryCache` to false, my understanding is that this will negatively affect cache performance, but I haven't dug in deep enough to know the consequences.

Can anyone from the apollo team chime in here, either by explaining the consequences, or linking some documentation? The [readme](https://github.com/apollographql/apollo-client/tree/master/packages/apollo-cache-inmemory) states:

> If id and _id are not specified, or if __typename is not specified, InMemoryCache will fall back to the path to the object in the query, such as ROOT_QUERY.allPeople.0 for the first record returned on the allPeople root query.

It's not really clear what the performace impact is here.

**Comment by mnpenner** [comment]
If you're using `apollo-boost`, then it looks like this...

```js
import ApolloClient from "apollo-boost";
import { InMemoryCache } from 'apollo-cache-inmemory';

export default new ApolloClient({
    uri: "http://localhost:8030/graphql",
    cache: new InMemoryCache({
        addTypename: false
    })
});
```

**Comment by ikatun** [comment]
If you're using `graphql` HOC/decorator from `react-apollo` and  want to avoid having to manually remove __typename from every response, you can just require this module https://www.npmjs.com/package/typename-monkey-patch somewhere near the entry point of your app.
It monkey patches the graphql HOC from react-apollo so that __typename is filtered out before sending data to your wrapped component.

**Comment by michaelbromley** [comment]
Just a note on using the `JSON.stringify()` solution from @danderson00 - if you want to do file uploads and you use something like [apollo-upload-client](https://github.com/jaydenseric/apollo-upload-client) then the serialization-parse step will destroy your reference to the `File` object and the upload will not work.

**Comment by arist0tl3** [comment]
Combining solutions from a few places (including @danderson00 and [this readme](https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-http/README.md#middleware)):

```
import { ApolloClient } from 'apollo-client';
import { ApolloLink, from } from 'apollo-link';
import link from './link';

// Strip __typename from variables
const middleWareLink = new ApolloLink((operation, forward) => {
  if (operation.variables) {
    const omitTypename = (key, value) => (key === '__typename' ? undefined : value);
    // eslint-disable-next-line no-param-reassign
    operation.variables = JSON.parse(JSON.stringify(operation.variables), omitTypename);
  }
  return forward(operation);
});

export default new ApolloClient({
  link: from([
    middleWareLink,
    link,
  ]),
});
```

**Comment by Nitishreddy787** [comment]
in Angular JS
import ApolloClient from "apollo-boost";
import { InMemoryCache } from 'apollo-cache-inmemory';

export default new ApolloClient({
    uri: "http://localhost:8030/graphql",
    cache: new InMemoryCache({
        addTypename: false
    })
});

how to do in androdi please help...

**Comment by tahoemph** [comment]
It would make sense to have __typename be a Symbol.  That way you expose metadata without doing it inband and confusing code which just wants to deal in data.

**Comment by spondbob** [comment]
Setting `addTypename: false` does screw up my schema, is it worth it to instead just remove `__typename`  from `data` props as results of `<Query>`?

**Comment by simkessy** [comment]
Man, this is a dumb problem to be dealing with.

**Comment by riginoommen** [comment]
> Man, this is a dumb problem to be dealing with.

Then please suggest the optimal solution.

**Comment by benjamn** [comment]
The reason `__typename` is included in response objects is that folks frequently update those objects and write them back into the store, and the cache would behave differently if it could not rely on receiving the same `__typename` that it previously saw. Specifically, `__typename` information is crucial for computing an ID for the object, so that the cache knows you're referring to the same entity as before, rather than some new, unidentifiable entity.

I have tried multiple times to exclude unwanted `__typename` fields from result objects (#5311, #5154), but I have since become convinced that they are necessary: #5320. This position is not likely to change unless someone who fully understands the problem comes up with a better solution than I have been able to find.

Making `__typename` non-enumerable is possible, but the mere presence of non-enumerable properties slows down all operations on the object (thanks JavaScript!). Otherwise, I would be happy to hide this behavior just so people would stop complaining.

**Comment by vlindhol** [comment]
> Specifically, `__typename` information is crucial for computing an ID for the object, so that the cache knows you're referring to the same entity as before, rather than some new, unidentifiable entity.

Perhaps a silly question, but if all id fields in the schema are UUIDs, does that make `__typename` unnecessary? Could this property be used somehow?

**Comment by vanoMekantsishvili** [comment]
What about this case: I am trying to set initial data in local cache, sth like this:

`client.cache.writeData({
  data: {
    isLoggedIn: !!window.localStorage.getItem('token'),
    cartItems: [],
    params: { name: 'test' }
  }
})`

And I've got warning that `__typename` is missing from params and when I add it then warning disappears and I've got correct response. But my question would be: Should I assign value(something unique) by myself? sth like this :

`client.cache.writeData({
  data: {
    isLoggedIn: !!window.localStorage.getItem('token'),
    cartItems: [],
    params: { name: 'test', __typename: 'params_unique_test' }
  }
})`

**Comment by ljmerza** [comment]
> > Specifically, `__typename` information is crucial for computing an ID for the object, so that the cache knows you're referring to the same entity as before, rather than some new, unidentifiable entity.
> 
> Perhaps a silly question, but if all id fields in the schema are UUIDs, does that make `__typename` unnecessary? Could this property be used somehow?

The ID doesn't not need to be a uuid. It just needs to be unique to the type of object. You can technically have a user object with ID 1, another with ID 2, and also have a list object with ID 1, another with ID 2.

**Comment by vjdw** [comment]
> 
> 
> > > Specifically, `__typename` information is crucial for computing an ID for the object, so that the cache knows you're referring to the same entity as before, rather than some new, unidentifiable entity.
> > 
> > 
> > Perhaps a silly question, but if all id fields in the schema are UUIDs, does that make `__typename` unnecessary? Could this property be used somehow?
> 
> The ID doesn't need to be a uuid. It just needs to be unique to the type of object. You can technically have a user object with ID 1, another with ID 2, and also have a list object with ID 1, another with ID 2.

Yes, the ID doesn't _have_ to be a UUID, but I think what @vlindhol is getting at is _if_ all your ID are UUIDs then maybe we don't need `__typename` for the cache to work correctly.

**Comment by bashkos** [comment]
Thank you for shedding light on the problem @benjamn. Please tell me, does the solution proposed by @arist0tl3 have any negative effects or can it be used?

**Comment by guilhermeKodama** [comment]
> I'd recommend against introducing a dependency just to do this:
> 
> ```js
> const omitTypename = (key, value) => (key === '__typename' ? undefined : value)
> const newPayload = JSON.parse(JSON.stringify(payload), omitTypename)
> ```
> 
> As far as setting the `addTypename` option in the `InMemoryCache` to false, my understanding is that this will negatively affect cache performance, but I haven't dug in deep enough to know the consequences.
> 
> Can anyone from the apollo team chime in here, either by explaining the consequences, or linking some documentation? The [readme](https://github.com/apollographql/apollo-client/tree/master/packages/apollo-cache-inmemory) states:
> 
> > If id and _id are not specified, or if __typename is not specified, InMemoryCache will fall back to the path to the object in the query, such as ROOT_QUERY.allPeople.0 for the first record returned on the allPeople root query.
> 
> It's not really clear what the performace impact is here.

The only problem with this approach is that it will break file uploads. Because we need the `File` type and when you stringify we will lose information for the upload

**Comment by luizcarlos1405** [comment]
If only the mutations would accept the `__typename` field or automatically strip it for us instead of complaining that it's there...

**Comment by AWolf81** [comment]
I've tried the `omitDeep` that was mentioned in a comment here. 
But I'm getting `TypeError: Cannot delete property '__typename' of #<Object>` if I'm trying to delete it from the response.

Not sure what is the easiest way to remove the `__typename` from the response but with
```js
const responseObj = {
    ...omitDeep(JSON.parse(JSON.stringify(data)), '__typename'),
};
```

I could remove it from my response without the error. I think `lodash.clonedeep` is an alternative to `JSON.parse/stringify` (shallow copy) .

It's related to `InMemoryCache({ freezeResult: true })` and `assumeImmutableResults: true`. Looks like the query results are immutable by default and it's not possible to disable the freeze of results. (related issue [#5987](https://github.com/apollographql/apollo-client/issues/5987))

So IMO the only option is to clone the object and return the mutated response.

Or what is the best practice here? Is it safe to disable the `addTypeName` or is it recommended to keep the `__typename` in the JSON response?
I just wanted to have a clean JSON response without `__typename` but maybe it's also no problem to keep that information.

**Comment by moderatemisbehaviour** [comment]
I can see an explanation for why typename exists but no solution for the actual issue of it breaking mutations so I don't understand why the issue has been closed.

I agree with @luizcarlos1405 that having the server ignore the field would be a good solution. Could even take it further and have it ignore everything that beings with an underscore.

**Comment by blackge** [comment]
For anyone using Typescript, you can define a Type for your mutation using the  using `Omit<Type, "__typename">` based on the response. This is probably simpler than some of the other solutions and means you can reuse the type wherever you need it.

[Typescript Utility Types](https://www.typescriptlang.org/docs/handbook/utility-types.html)
