### ISSUE TITLE
Apollo-client throws error in NuxtJs: Cannot set property '__APOLLO_CLIENT__' of undefined

### ISSUE THREAD

**Issue by jarnojellesma** [apollographql/apollo-client#1919]
**Intended outcome:**
I am trying to implement the Apollo-Client with my NuxtJs application. 

**Actual outcome:**
![screenshot at 2017-07-18 14 37 07](https://user-images.githubusercontent.com/27930147/28317295-a4deb6dc-6bc6-11e7-8049-594da498ef4d.png)

**How to reproduce the issue:**
I created a minimal app to reproduce the error in my repository:
https://github.com/jarnojellesma/apollo-nuxt

**Version**
- apollo-client@1.8.1

**Comment by jbaxleyiii** [comment]
@jarnojellesma this is most likely from tyring to attach to the window (for the dev tools) while on the server. Can you confirm that this code is not being executed on the server?

**Comment by jarnojellesma** [comment]
I just found a working example at: https://github.com/nuxt/nuxt.js/tree/dev/examples/with-apollo

I have to go now. Will implement it in my own application tomorrow and will post what I did wrong.
