### ISSUE TITLE
Broken link in README's "Important discussions" section

### ISSUE THREAD

**Issue by tohjustin** [apollographql/apollo-client#1922]
**Intended outcome:**

Clicking on the link labelled as **[Long conversation about different client options, before this repo existed](https://github.com/apollographql/apollo/issues/1)** under the **Important discussions** section should bring the user to a valid webpage.

**Actual outcome:**

Clicking on the link brings the user to a Github 404 webpage (https://github.com/apollographql/apollo/issues/1).

**How to reproduce the issue:**

1. Go to https://github.com/apollographql/apollo-client
2. Click on the link at the 4th link labelled as **"[Long conversation about different client options, before this repo existed](https://github.com/apollographql/apollo/issues/1)"** under the **"Important discussions"** section (located near the bottom of the page)
3. Browser is directed to https://github.com/apollographql/apollo/issues/1 with a Github 404 message

**Version**
- apollo-client@1.9.0

**Comment by jbaxleyiii** [comment]
@tohjustin would you be able to open a PR for this fix?

**Comment by tohjustin** [comment]
@jbaxleyiii I would love to make a PR to fix this 😄  

The only blocker I have right now is that I'm not too sure what link to use for the fix (I'm guessing the current link we have in the README broke when issue tracking in https://github.com/apollographql/apollo have been disabled)

**Comment by jbaxleyiii** [comment]
haha oh! Sorry I misread! I'll get that for you!

**Comment by jbaxleyiii** [comment]
ah, this was my fault. I closed issues on the Apollo project for clarity. A lot of people opened AC issues on that repo. Hmmm, I'll think through an option, maybe I'll move it here and close it so it an be linked
