### ISSUE TITLE
TS compilation fails Class 'RxObservableQuery<T>' incorrectly extends base class 'Observable<ApolloQueryResult<T>>'

### ISSUE THREAD

**Issue by Isigiel** [apollographql/apollo-client#1929]
**Intended outcome:**
Compilation works with the latest typescript version.

**Actual outcome:**
Compilation fails with typescript newer then 2.4.0.   
I'd guess this is related to https://github.com/ReactiveX/rxjs/issues/2539, or even to their fix of it.

**How to reproduce the issue:**
Right now it seems, just update angular, ts, rxjs ... to the latest version and try to compile.
Using typescript 2.3.4 worked for rxjs and seems to be preventing this issue as well.
I'm getting this error
`node_modules/apollo-client-rxjs/build/src/RxObservableQuery.d.ts (7,22): Class 'RxObservableQuery<T>' incorrectly extends base class 'Observable<ApolloQueryResult<T>>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<ApolloQueryResult<T>, ApolloQueryResult<R>>) => Observable<ApolloQueryResu...' is not assignable to type '<R>(operator: Operator<ApolloQueryResult<T>, R>) => Observable<R>'.
      Types of parameters 'operator' and 'operator' are incompatible.
        Type 'Operator<ApolloQueryResult<T>, R>' is not assignable to type 'Operator<ApolloQueryResult<T>, ApolloQueryResult<{}>>'.
          Type 'R' is not assignable to type 'ApolloQueryResult<{}>'.`

I'm of course happy to provide more info
**Version**
- apollo-client@1.9.0-1

**Comment by kamilkisiela** [comment]
Please, post an issue here: [apollo-client-rxjs](https://github.com/kamilkisiela/apollo-client-rxjs/issues)
