### ISSUE TITLE
Cursor-based pagination issues

### ISSUE THREAD

**Issue by hmontes** [apollographql/apollo-client#1930]
Hi

I don't understand cursor-based pagination in your docs. I have a few questions . http://dev.apollodata.com/react/pagination.html

1. I need TWO queries for implementing this? query comments and query moreComments? I ask because this line is confusing.

Line 13, official docs
```
const CommentsWithData = graphql(Comment, {
```

Where is the Comment variable? It's the "MoreCommentsQuery" variable?

2. Can you make an example in apollo-server?

Thank you

**Comment by hmontes** [comment]
The docs are deprecated.
```
const MoreCommentsQuery = gql`
  query MoreComments($cursor: String) {
    moreComments(cursor: $cursor) {
      cursor
      comments {
        author
        text
      }
    }
  }
`;
```

```
props({ data: { loading, cursor, comments, fetchMore } }) {
    return {
      loading,
      comments,
      loadMoreEntries: () => {
        return fetchMore({
          query: MoreCommentsQuery,
          variables: {
            cursor: cursor,
          },
          updateQuery: (previousResult, { fetchMoreResult }) => {
            const previousEntry = previousResult.entry;
            const newComments = fetchMoreResult.moreComments.comments;
            return {
              // By returning `cursor` here, we update the `loadMore` function
              // to the new cursor.
              cursor: fetchMoreResult.cursor,
              entry: {
                // Put the new comments in the front of the list
                comments: [...newComments, ...previousEntry.entry.comments],
              },
            };
          },
        });
      },
    };
  },
})(Feed);
```

1. graphql(Comment.. = graphql(MoreComments ...
2. The cursor prop don't load in that location. Props load in the query name (props.moreComments.cursor).
3. Most of the variables are wrong. comments = moreComments (lowercase) because the data is load in the queryname.
4. const previousEntry = previousResult.entry; This produces an error. entry don't exists in querys.
....

I'm trying to fix this. But. Can you, PLEASE, update the docs for a functional Cursor-Based pagination?

Thank you

**Comment by hmontes** [comment]
Temp. Fix

```const GetBlogPosts = gql`query GetBlogPosts($cursor: String) {
  getBlogPosts(cursor: $cursor) {
    cursor
    blogPosts {
      id
      title
      ...moreFields
    }
  }
}`

export default graphql(GetBlogPosts, {
  props({ data: { loading, getBlogPosts, fetchMore } }) {
    return {
      loading,
      getBlogPosts,
      loadMoreEntries: () => {
        return fetchMore({
          query: GetBlogPosts,
          variables: {
            cursor: getBlogPosts.cursor
          },
          updateQuery: (previousResult, { fetchMoreResult }) => {
            const newCursor = fetchMoreResult.getBlogPosts.cursor
            const previous = previousResult.getBlogPosts.blogPosts
            const next = fetchMoreResult.getBlogPosts.blogPosts

            return {
              getBlogPosts: {
                cursor: newCursor,
                blogPosts: [...next, ...previous]
              }
            }
          }
        })
      }
    }
  }
})(Blog)
```

The problem? I obtain this in the console.

```
Missing field __typename in {
  "cursor": "NTk3MTFlODE4Y2VkOTA4NDFlODViMGJk",
  "blogPosts": [
    {
      "id": "59711e3f8ced90
```

What is the problem?

**Comment by pak11273** [comment]
@hmontes A year later and I have this very issue.  My code is almost verbatim to what you posted.  Did you find a solution to this?  I can't believe no one else has run into this issue.  Pagination should not be this difficult.
