### ISSUE TITLE
Export default dataIdFromObject

### ISSUE THREAD

**Issue by mxstbr** [apollographql/apollo-client#1936]
To override the default `dataIdFromObject` I pass the `dataIdFromObject` key to my client constructor:

```JS
const client = new ApolloClient({
  dataIdFromObject: (result) => {/*...*/}
})
```

In many cases I only want to add a special case for a specific resource though. (see #1934 for an example use case) Right now I have to dig through the source code in this repo, find the `defaultDataIdFromObject` function, copy-and-paste it and then add my custom stuff at the top.

That's a) ugly but b) means that it'll likely go out of data with the upstream version which might introduce subtle bugs when I copy and paste stuff from the docs but am using old code in my `dataIdFromObject`.

What about exporting `defaultDataIdFromObject`? That would allow me to introduce a special case for specific resources without going out of data later:

```JS
import ApolloClient, { defaultDataIdFromObject } from 'apollo-client';

const client = new ApolloClient({
  dataIdFromObject: (result) => {
    // Key users by username instead of ID
    if (result.__typename === 'User') {
      return `${result.__typename}:${result.username}`;
    }

    // Not a user? Fallback to the default
    return defaultDataIdFromObject(result);
  }
})
```

**Comment by abhiaiyer91** [comment]
Yeah! I think this sounds like a good idea. We should allow users to build on top of the functionality in a streamlined way. I think the example you illustrated is a good way to do so!

**Comment by jbaxleyiii** [comment]
@mxstbr I'd be happy to accept that PR and release it! Would you have some time (or @abhiaiyer91) to open and write a simple test to make sure it is exported correctly?

**Comment by mxstbr** [comment]
This isn't really stale since it's just an enhancement suggestion, so I'll comment again to remove that stale label! Would somebody mind adding a label to the issue so it doesn't get marked as stale again?

**Comment by jbaxleyiii** [comment]
@mxstbr done and this will be part of the 2.0 🎉
