### ISSUE TITLE
UpdateQuery affecting queries in root query with multiple sub queries that are not related

### ISSUE THREAD

**Issue by khankuan** [apollographql/apollo-client#1942]
Hi, I have 2 components that are both lists, one showing name, another showing email. When I'm doing `fetchMore` and then `updateQuery` on the first list, the second list gets updated as well. It seems like both list are using the same key in the redux store ROOT_QUERY.

Reproduction: https://github.com/khankuan/react-apollo-error-template/tree/bugs/update-query-concat
Reproduce at: https://khankuan.github.io/react-apollo-error-template/bugs/update-query-concat/

To reproduce: Click on the first fetch more button. Notice that the second list gets updated as well.

**Comment by khankuan** [comment]
It seems like the bug has changed with the latest version. It is now showing the same error as https://github.com/apollographql/apollo-client/issues/2049

**Comment by khankuan** [comment]
@jbaxleyiii Any hints on where to get started? I would love to help fix it.

**Comment by jbaxleyiii** [comment]
closing for #2049 which we will work to improve! Sorry for the lack of response on this one!
