### ISSUE TITLE
Unhandled error: Store reset while query was in flight.

### ISSUE THREAD

**Issue by damarna85** [apollographql/apollo-client#1945]
Hi all,
We have a question regarding how to properly handle the `Store reset while query was in flight.` error. In our `applyAfterware` method we are handling 401 errors, logging out the user and calling the `client.resetStore` method. It can happen that some of the queries are in flight at this point so we are getting that error because of this code in the Apollo Client resetStore method:
```js
// Before we have sent the reset action to the store,
// we can no longer rely on the results returned by in-flight
// requests since these may depend on values that previously existed
// in the data portion of the store. So, we cancel the promises and observers
// that we have issued so far and not yet resolved (in the case of
// queries).
Object.keys(this.fetchQueryPromises).forEach(key => {
  const { reject } = this.fetchQueryPromises[key];
  reject(new Error('Store reset while query was in flight.'));
});
```
Is there a proper way to catch this rejection somewhere in our code in order to handle this error?

Thanks!

**Version**
- apollo-client@<1.8.0>

**Comment by Cito** [comment]
After logout I simply call `initStore()` instead of `resetStore()` to get rid of the cached data without refetching it when there are still pending subscriptions.

**Comment by dotansimha** [comment]
Same here. any idea?

**Comment by seeden** [comment]
any advance?

**Comment by ComicScrip** [comment]
Anyone ?

**Comment by adambom** [comment]
Happening here too. Really problematic. Anybody looking into this?

**Comment by brentjanderson** [comment]
I've wrapped my `client.resetStore` call in a setTimeout with a delay of zero (running v2.0 apollo-client in react native on Expo). I'm not an expert on Apollo's internals, but by delaying the store reset until the next tick in execution, the queries/mutations seem to move to a state of resolution sufficient to avoid this error from happening. Feedback would be appreciated on this approach if anyone has any.

**Comment by oduncan** [comment]
I'd like to reset the store in my index after checking whether the token is expired when apollo-link is re instantiated, I have access to the client via: 

`const client = new ApolloClient({
  link: httpLinkWithAuthToken,
  cache: new InMemoryCache()
})
`

but I got the in flight error because my function that calls client reset store is invoked in the: 
`
 new ApolloLink((operation, forward) => {
//check token
//set headers
return forward(operation)
}
`

Is there a proper way to reset the store when initializing the network/link or should I defer that responsibility to the app by passing down some param into the <App /> component

**Comment by jarnojellesma** [comment]
Anyone?

**Comment by brentjanderson** [comment]
@jarnojellesma I've been using the following approach for about a month in a production app with no hiccups.

```javascript
// Instead of calling just client.resetStore() -
setTimeout(() => { client.resetStore(); }, 0);
```

This seems to defer the store reset to the next tick of Javascript execution, letting in-flight queries reach enough resolution to reset correctly. It feels like a stable workaround to me.

**Comment by jarnojellesma** [comment]
@brentjanderson Hey man thanks for the tip, unfortunately it isn't working for me:

```
sync logout(store) {
    console.log('logging out..')
    await feathersClient.logout();
    
    store.commit('SET_VIEWER', null);
    console.log('logged out')
    setTimeout(() => this.app.apolloProvider.defaultClient.resetStore(), 0);
  },
```
Also tried it with 1 and 10 ms.
