### ISSUE TITLE
fetchMore example with API as data source

### ISSUE THREAD

**Issue by vtahlani** [apollographql/apollo-client#1948]
Sorry for asking sample code here, i am not sure if it is right place...

I want to consume responses from server which sends multiple chunks as a response for a request. I thought, I should be able to do it through fetchMore with graphql client. Can you please provide me a example for same.

**Comment by michieldewilde** [comment]
You can find the needed information on the [pagination section](http://dev.apollodata.com/react/pagination.html`) of the documentation.
