### ISSUE TITLE
Make a guide for new contributors

### ISSUE THREAD

**Issue by stubailo** [apollographql/apollo-client#195]
We want to make it as easy as possible to contribute!
- [ ] Roadmap
- [ ] Where to start

Add more ideas in the comments!

**Comment by abhiaiyer91** [comment]
- [ ] How Apollo works

**Comment by dcworldwide** [comment]
In terms of a roadmap, you could possible use the Projects feature of github to define near term goals as issues/prs. I think this would be a neat idea for passive observers and helpful for would be contributors.

I've been watching the pulse / issues of this repo every few days to try and understand the teams near term goals. I still don't know the answer.

**Comment by helfer** [comment]
@dcworldwide we actually have a document like that, I just need to add it to the repo! I will do so shortly, thanks for the reminder!

**Comment by dcworldwide** [comment]
@helfer ok cool. Thanks guys

**Comment by helfer** [comment]
Closing up old issues. Let's track this in a community repo.
