### ISSUE TITLE
remove optional dependency @types/isomorphic-fetch

### ISSUE THREAD

**Issue by kikar** [apollographql/apollo-client#1959]
This dependency breaks compilation of typescsript apps with `apollo-client` dependency because is looking for the fetch object, without having it.
Please either move `@types/isomorphic-fetch` to `devDependencies` or move `isomorphic-fetch` to `optionalDependencies`

**Comment by breathe** [comment]
I'm hitting this also -- the serverless project requires apollo-client which pulls in isomorphic-fetch and causes this error in node app ...

```node_modules/@types/isomorphic-fetch/index.d.ts(8,30): error TS2552: Cannot find name 'fetch'. Did you mean '_fetch'?```

**Comment by kikar** [comment]
@stubailo @jbaxleyiii Any ETA for when this fix merged in #1960 is gonna be published to NPM?
