### ISSUE TITLE
Infinite loop when selecting multiple fragments with the same fields

### ISSUE THREAD

**Issue by altschuler** [apollographql/apollo-client#1987]
Using apollo-angular, given something to the effect of the following schema, `watchQuery` will trigger infinitely. I'm guessing the cause is something like the `PartOne` fragment being updated which triggers a change in the store that triggers the `PartTwo` which triggers `PartOne` and so on. Or something similar. It might be an issue with apollo-angular, sorry if it's the wrong repo to report.

```
type Foobar {
    foo: String
    bar: String
}

type World {
    something: Foobar
}

fragment PartOne on World {
    something { foo }
}

fragment PartTwo on World {
    something { bar }
}

fragment Full on World {
    ...PartOne
    ...PartTwo
}

type Query {
  world(id: Int!) {
    ...Full
  }
}

// in some .ts file
this.apollo.watchQuery({
    query: `
        # fragments omitted
        query Foobar($id: Int!) {
            world(id: $id) {
                ...Full
           }
       }
    }`,
    variables: { id: 1 },
});
```

**Intended outcome:**
`watchQuery` should only trigger only once

**Actual outcome:**
`watchQuery` triggers continuously without any actual changes to the data.

**Version**
apollo-angular: 0.13.0
apollo-client: 1.9.0-1

**Comment by mringer** [comment]
I see also see this behavior

"apollo-angular": "^1.0.0",
"apollo-client": "^2.0.1",
