### ISSUE TITLE
Be able to unset content-type with middle-ware on network interface

### ISSUE THREAD

**Issue by asafigan** [apollographql/apollo-client#2011]
There is a problem with the Fetch API where setting the content-type header to undefined while using cors mode sends a header of "undefined" rather than the default header. The default header is needed for sending form data. 

I am trying to use middleware to unset the content-type sent by the network interface, so that I can send form data as the body. I am doing this so that I can send files to the server as part of my request.

Right now there is no why to do this with middleware, because of the fetch bug. 

**Intended outcome:**
sends request with content-type multipart formdata

**Actual outcome:**
sends request with content-type undefined

**How to reproduce the issue:**
Example:
```
import { printAST } from 'apollo-client'
import { createNetworkInterface } from 'react-apollo'
const networkInterface =  createUploadNetworkInterface({
    uri: process.env.REACT_APP_GRAPHQL_URL,
    opts: {
        mode: 'cors',
    }
})

// send as multipart formdata
networkInterface.use([{
    applyMiddleware(req, next) {
        const formData  = new FormData();

        formData.append('query', printAST(request.query));
        formData.append('variables', JSON.stringify(request.variables || {}));
        req.options.body = formData
        if (!req.options.headers) {
            req.options.headers = {}
        }

        req.options.headers['Content-Type'] = undefined
        next()
    }
}])
```

**Version**
- apollo-client@latest

**Comment by cajames** [comment]
Hey there, faced this issue.

For some reason noticed that the CORS pre flight failed when content-type was set to `application/json`.

Setting it to `text/plain;charset=UTF-8` did the trick. Also, using opts `credentials`.


```javascript
const networkInterface =  createUploadNetworkInterface({
    uri: process.env.REACT_APP_GRAPHQL_URL,
    opts: {
        credentials: 'include',
    }
})

networkInterface.use([{
// ...
    if (!req.options.headers) {
        req.options.headers = {
            'Content-Type': 'text/plain;charset=UTF-8',
        };
    }
// ...
}]);
```
