### ISSUE TITLE
networkInterface.use is not a function

### ISSUE THREAD

**Issue by groundmuffin** [apollographql/apollo-client#2013]
**Intended outcome:**
When using ApolloClient on full WebSocket transport, the `subscriptions-transport-ws\SubscriptionClient` instance is used as client's networkInterface.
Trying to use Apollo Client with middleware and networkInterface.use()
Followed instructions from http://dev.apollodata.com/core/network.html#networkInterfaceMiddleware

**Actual outcome:**
The problem is when AppolloClient constructor applies networkInterface config to 'this' instance, it assigns config properties to some empty object, but prototype properties are ignored.
It results, for example, to networkInterface "use" method is not applied to client's networkInterface.

So, we got 
Warning: ApolloClient.js:106 The Observable Network interface will be deprecated
Error: networkInterface.use is not a function

**How to reproduce the issue:**
- use full Websocket transport with apollo client (SubscriptionClient from subscriptions-transport-ws)
- configure some middleware with networkInterface.use method.

**Version**
- apollo-client@1.9.0
- react-apollo@1.4.11

**Comment by danieljvdm** [comment]
Is this live in any version? It's still happening with the latest `react-apollo`.
