### ISSUE TITLE
Getting SCRIPT1014: Invalid character in IE and Safari while handling GraphQL operations

### ISSUE THREAD

**Issue by Saidalavi** [apollographql/apollo-client#2020]
**Intended outcome:**
We are using Apollo client in angular 1.x to connect with GraphQL. All browsers working fine except IE and Safari. 

**Actual outcome:**
Getting a `SCRIPT1014: Invalid character` in IE and Safari

**How to reproduce the issue:**
The issue is due to back quote ( `) character present in GraphQL queries (gql`${query}`, gql`${mutation}`).

**Version**
- apollo-client@0.8.0

**Comment by Saidalavi** [comment]
We didn't get any solution for this so far. We are still waiting for some solution on this.

**Comment by dhiaEvodeck** [comment]
Got the same issue with apollo-client@3.1.3 version.

**Comment by sushruth** [comment]
Adding to it - got the same here.
