### ISSUE TITLE
 _this.networkInterface.subscribe is not a function

### ISSUE THREAD

**Issue by muaaz-vf** [apollographql/apollo-client#2022]
![screenshot from 2017-08-09 14-58-26](https://user-images.githubusercontent.com/5028648/29116174-770f320a-7d13-11e7-8c11-bc2dfeda420c.png)

**Comment by waleedarshad-vf** [comment]
+1

**Comment by DxCx** [comment]
There is already bug fix pending (#1992)

**Comment by waleedarshad-vf** [comment]
can do patch or something for the time begin to run it

   
      import {SubscriptionClient, addGraphQLSubscriptions} from 'subscriptions-transport-ws';
      import ApolloClient, {createNetworkInterface} from 'apollo-client';

      import { meteorClientConfig } from 'meteor/apollo';

      const isLocalhost = process.env.ROOT_URL === 'http://localhost:3000/' || !process.env.ROOT_URL;



     const GRAPHQL_ENDPOINT = 'ws://localhost:5000';







      // Create regular NetworkInterface by using apollo-client's API:
      const networkInterface = createNetworkInterface({
        uri: 'http://localhost:3000/graphql' // Your GraphQL endpoint
      });

      // Create WebSocket client
       const wsClient = new SubscriptionClient(GRAPHQL_ENDPOINT, {
       reconnect: true,
      });

     // Extend the network interface with the WebSocket
     const networkInterfaceWithSubscriptions = addGraphQLSubscriptions(
       networkInterface,
       wsClient
    );






     export const client = new ApolloClient({
	networkInterface: networkInterfaceWithSubscriptions
      });

     export default client;

**Comment by waleedarshad-vf** [comment]
How to merge that pull request or the way we can use it?

**Comment by waleedarshad-vf** [comment]
Problem exists here when i run subscribe to more
    componentWillReceiveProps(nextProps) {
	  // we don't resubscribe on changed props, because it never happens in our app
	  if (!this.subscription && !nextProps.data.loading) {
	    let { subscribeToMore } = this.props.data
	    
	    this.subscription = subscribeToMore(
	      {
	        document: postUpdated,
	        updateQuery: (previousResult, { subscriptionData }) => {
	        	// debugger
	          // previousResult.posts.push(subscriptionData.data.postInserted)
	          // return previousResult
	        },
	      }
	    )
	  }
	}
