### ISSUE TITLE
proxy.readQuery throws an error on not executed queries

### ISSUE THREAD

**Issue by zunder** [apollographql/apollo-client#2024]
I am having a structure which looks like the following:

```
type Person {
  id: string
  friends: [Friend]
  addresses: [Address]
}
```

At one point in time I am fetching one persons addresses, which is being cached in the store while using the id field.

At a later point in time, I am doing a mutation on the object and add a new friend. Please note, that at this point in time the user did not request to fetch the list of friends for now. In order to keep the friends list up to date, I am still doing a `proxy.readQuery` operation on the query which is responsible for fetching all friends of a user and pushing the new friend into it. For now I don't keep track if the user already executed this query at some point in the past. If the user did so, everything is alright. If however he did not fetch the list of friends and I am trying to execute the `proxy.readQuery` on that query, I will get an exception like that:

```
Error: Can't find field PersonFriends on object (Person:UGVyc29uOjE=) {
  "id": "UGVyc29uOjE=",
  "Viewer_addresses": {
    "type": "id",
    "id": "$Person:UGVyc29uOjE=.Viewer_addresses",
    "generated": true
  },
  "__typename": "Person"
}
``` 

I would like to prevent catching this exception. Is there any way from Apollo's side to know if a certain query was executed in the past and don't execute the `proxy.readQuery` in that case?

**Comment by janaleible** [comment]
See also issue #2007

**Comment by zunder** [comment]
@janaleible did you manage to come up with a workaround on this issue?

I noticed that `readFragment` supposed to return either the FragmentType or null. This might be a solution for this issue, but I didn't try it out yet.

**Comment by janaleible** [comment]
Not exactly a workaround, unfortunately. I ended up avoiding the isssue altogether by using a network-only fetchPolicy for this particular query.

**Comment by zunder** [comment]
This issue is not solved, no need for closing.

**Comment by jbaxleyiii** [comment]
@zunder do you have a reproduction app for this? I'd be happy to take a look!
