### ISSUE TITLE
Cannot add Authorization header

### ISSUE THREAD

**Issue by timur560** [apollographql/apollo-client#2047]
I was trying to add Authorization header to apollo GraphQL request, but it was not added
My code:
```javascript
const networkInterface = createNetworkInterface({
  uri: 'http://my.core.local/api/v1/graphql',
  opts: {
    headers: {
      "Authorization": "Bearer 6LF8GTTI0DC2gPyfgVikNWhRXDJmrvSf",
    }
  }
});

export const apolloClient = new ApolloClient({
  networkInterface,
});
```

As a result, I don't see this header in my request
Request headers:
```
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8,uk;q=0.6,ru;q=0.4,ja;q=0.2
Access-Control-Request-Headers:authorization,content-type
Access-Control-Request-Method:POST
Cache-Control:no-cache
Connection:keep-alive
Host:buurb.core.local
Origin:http://localhost:3000
Pragma:no-cache
Referer:http://localhost:3000/
User-Agent:Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36
```
Response headers:
```
Access-Control-Allow-Headers:Content-Type, Authorization
Access-Control-Allow-Methods:PUT, GET, POST, DELETE, OPTIONS
Access-Control-Allow-Origin:*
Access-Control-Request-Headers:true
Connection:Keep-Alive
Content-Length:236
Content-Type:application/json; charset=UTF-8
Date:Tue, 15 Aug 2017 10:47:05 GMT
Keep-Alive:timeout=10, max=100
Server:Apache
Www-Authenticate:Bearer realm="api"
```

**Although** when I use Modify Headers chrome extention to add custom headers, all works fine.

**Comment by intellix** [comment]
We're achieving this in ng2 using a factory/middleware:

```ts
export function apolloClientFactory(sessionService: SessionService, environment: any): Apollo {
  const uri = `${environment.apiEndpoint}/graphql`;
  const networkInterface = createNetworkInterface({ uri });

  networkInterface.use([{
    applyMiddleware(req, next) {
      if (!req.options.headers) {
        req.options.headers = {
          authorization: `Bearer ${sessionService.getToken()}`,
        };
      }

      next();
    },
  }]);

  return new Apollo({
    default: new ApolloClient({ networkInterface }),
  });
}
```

Hope it helps

**Comment by timur560** [comment]
Thank you, @intellix, but unfortunately, with `applyMiddleware` the result is the same. If it helps, I use apollo with polymer, but it is not the issue, I think.

**Comment by timur560** [comment]
The reason was that OPTIONS should always return 200 without authorization. The issue was fixed by server updating.

**Comment by ahmadalli** [comment]
I'm getting typescript error saying that `Type '{}' is not assignable to type 'Headers | string[][]'.
  Type '{}' is not assignable to type 'string[][]'.`

**Comment by lucas-bremond** [comment]
> The reason was that OPTIONS should always return 200 without authorization. The issue was fixed by server updating.

Could you please elaborate on this?

I am using a server protected by an auth wall that does not let requests through if the `Authorization` is not set... even the `OPTIONS` one.

Is there a way to configure Apollo to attach custom headers to `OPTIONS`?
