### ISSUE TITLE
Partial fragment matching causes data disappear due to hidden error in apollo-client

### ISSUE THREAD

**Issue by khankuan** [apollographql/apollo-client#2049]
Hi, I have a use case where I'm doing a mutation that creates a new object. I then nest the fields that would be changed in the mutation query and expect that the ui gets updated correctly.

**Actual outcome:**
The data in the `data` object is gone, primarily due to an error in https://github.com/apollographql/apollo-client/blob/master/src/data/readFromStore.ts#L149

Reproduce at https://khankuan.github.io/react-apollo-error-template/bugs-partial-fragment/
Source code at https://github.com/khankuan/react-apollo-error-template/tree/bugs-partial-fragment

**Version**
- apollo-client@1.8.1

Thanks!

**Comment by khankuan** [comment]
@jbaxleyiii Any hints on where to get started? I would love to help fix it.

**Comment by khankuan** [comment]
Hi, I've encounter this bug again yesterday. I'm wondering if the least we could do might be to a warning message in dev mode that fragment has missing data. Any thoughts?

**Comment by jbaxleyiii** [comment]
@khankuan I think we should change the hiddenness of store issues by changing how the 2.0 handles store errors! I'm adding this to the 2.0 milestone because its caused a lot of problems for cache implementers with the new API.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Partial%20fragment%20matching%20causes%20data%20disappear%20due%20to%20hidden%20error%20in%20apollo-client&body=Migrated%20from:%20apollographql/apollo-client%232049) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
