### ISSUE TITLE
RFC: Rename customResolvers to cacheResolvers

### ISSUE THREAD

**Issue by mxstbr** [apollographql/apollo-client#2057]
When skimming the Apollo Client docs I was confused what `customResolvers` were about. My first thought were that they are sent to the server and replace the resolver that's running there or something like that. (which doesn't make any sense in hindsight, but whatever)

I feel like `cacheResolvers` would be a much more descriptive and easy to understand name, since that's really what the option is about: controlling how Apollo Client resolves things from the cache.

----

This could be done in a backwards compatible manner where the next major version supports `cacheResolvers` and the docs show `cacheResolvers` but users can still supplement `customResolvers` it'll just log a warning in development. (one could even whip up a quick codemod to make this happen, even though it's only a find and replace) The major version after that support for `customResolvers` is dropped and only `cacheResolvers` works.

**Comment by mxstbr** [comment]
Nooo stale bot please don't!

**Comment by mxstbr** [comment]
Arggg please can somebody mark this as a discussion? My lordey this stalebot is going on my nerves :D

**Comment by jbaxleyiii** [comment]
@mxstbr sorry about the bot and missing this! Btw if you add `discussion` as a label it will leave it alone!

I think this is a GREAT idea and will make it a non-breaking change with the 2.0 and remove the original name at some point in the future!

**Comment by mxstbr** [comment]
Awesome. Unfortunately only maintainers/folks with write access can add labels, otherwise I would've done so :blush:

**Comment by jbaxleyiii** [comment]
oh no! I should just give you write access ;)

**Comment by jbaxleyiii** [comment]
@mxstbr renamed with backwards compat [here](https://github.com/apollographql/apollo-client/pull/2281/commits/0a99d01e6f566127f3c76843003f117c6ee811f7) 

And you should have commit access now for labels!
