### ISSUE TITLE
Mutation time is O(n) with store size n

### ISSUE THREAD

**Issue by jmoore315** [apollographql/apollo-client#2084]
**Intended outcome:**
Mutation time should not increase with store size

**Actual outcome:**
When running a simple mutation, even one that does not impact store data (e.g. returns a scalar response), processing time decays as store size grows. I hit this issue when working on a project with ~8000 fairly flat records loaded in the apollo store. A mutation with a 20ms network response time ends up taking 2.5 seconds to process. This strikes me as a pretty big implementation flaw and restricts the types of applications that apollo-client can be used for. 

**How to reproduce the issue:**
I reproduced the issue using the apollo issue template here https://github.com/jmoore315/apollo-mutation-time-issue. 

Mutation times are logged to the console. With 10,000 records the mutation time is around 2.5 seconds for me. By changing `STORE_SIZE` in `/src/graphql/schema.js` to a smaller value you can see how mutation time is impacted by store size. To be clear, the code here runs a mutation that doesn't actually do anything and does not even touch the store data - it just returns a hardcoded value so it *should* be O(1). 

Based a bit of profiling I did, it looks like the main culprit is the store `dispatch()` method called before & after mutations, but I did not dig much further than this as my knowledge of redux & javascript is quite limited

**Version**
- tested with all versions up to 1.9

**Comment by jmoore315** [comment]
Bot - please do not close this issue

**Comment by jbaxleyiii** [comment]
@jmoore315 I'll take a look but I think this should be better with the 2.0. Thanks for the reproduction!

**Comment by jbaxleyiii** [comment]
@jmoore315 some updates for this problem!

## Version `1.*`
<img width="130" alt="v1" src="https://user-images.githubusercontent.com/4967600/31424778-279104a4-ae2a-11e7-9c6d-f6a8aa14088f.PNG">

## Version `2.0-beta.6`
<img width="117" alt="v2" src="https://user-images.githubusercontent.com/4967600/31424783-33886d60-ae2a-11e7-8fa2-f091717b6e81.PNG">

That shaves over a full second off the result cost. With the mutation having a [500ms delay](https://github.com/jmoore315/apollo-mutation-time-issue/blob/master/src/graphql/networkInterface.js#L18) it is taking around 900ms to parse the result and save it to the store when the cache size is 10,000 records

Now the better news:

## Version `2.0-beta.7`
<img width="120" alt="v2next" src="https://user-images.githubusercontent.com/4967600/31427007-bd67ee6c-ae33-11e7-81be-2d7ad2f0392b.PNG">

The next version shaves another ~450 ms on average. With the `500 ms` delay, this means that the InMemoryCache is taking ~450 ms to evaluate and update a 10,000 record list. This is still slower than I want it to be but it is a roughly 5x performance gain on normal mutation usage

**Comment by jbaxleyiii** [comment]
I'm going to mark this as closed for now, but know that post 2.0 I'm going to be taking a hard look at some possible performance gains so this number will hopefully continue to improve

**Comment by jbaxleyiii** [comment]
for more info on what was changed for these improvements, check out [this commit](https://github.com/apollographql/apollo-client/pull/2281/commits/5c5c24f8665e23157ecbf8847e17cc559da3338f)

**Comment by jmoore315** [comment]
Cool - thanks James!

On Oct 11, 2017 12:33 AM, "James Baxley" <notifications@github.com> wrote:

Closed #2084 <https://github.com/apollographql/apollo-client/issues/2084>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/apollographql/apollo-client/issues/2084#event-1287547528>,
or mute the thread
