### ISSUE TITLE
Add possibility to change prefix for apollo errors

### ISSUE THREAD

**Issue by VladShcherbin** [apollographql/apollo-client#2096]
Currently, apollo-client adds prefix for error messages [here](https://github.com/apollographql/apollo-client/blob/master/src/errors/ApolloError.ts#L20-L25):

- `GraphQL error:` for graphql errors
- `Network error:` for network errors

It would be great to have a possibility to turn off this message changes or to be able to set custom prefix. It is useful when you send good errors from server and want to have their messages unchanged, for example:

`Invalid credentials` instead of `GraphQL error: Invalid credentials`

**Comment by richardgirges** [comment]
Was just looking for a way to do this! This would be beneficial for cases where the server is returning user-facing-friendly error messages (which happens to be the case for me as well).

**Comment by townmulti** [comment]
+1

**Comment by VladShcherbin** [comment]
What a useless bot, wow. What activity do you expect, it's an issue tracker, not a chat room.

**Comment by jbaxleyiii** [comment]
@VladShcherbin the error should contain the raw error response message. Can you access that directly?

**Comment by VladShcherbin** [comment]
@jbaxleyiii here is the error object contents:

```json
{
  "graphQLErrors": [
    {
      "name": "AccessForbiddenError",
      "message": "Access forbidden"
    }
  ],
  "networkError": null,
  "message": "GraphQL error: Access forbidden"
}
```

In order to get normal raw message I need to use `graphQLErrors[0].message`. I would like to use just `message` property.
