### ISSUE TITLE
Show store write errors in Console

### ISSUE THREAD

**Issue by maxsalven** [apollographql/apollo-client#2097]
**How to reproduce the issue:**
I had two components both querying data under a `currentUser` root key, e.g.
`currentUser {id, name}` and `currentUser { email }`

Note that the second query did not have an `id` in it.

**Intended outcome:**
An error message should be shown in the console.

**Actual outcome:**
[Note, the issue was due to the second query not having the `id` field].

I'd like to see an error message in a console alert. I discovered later that the `data.error` field is correctly populated, but I think an error involving writing to the store is worthy of console level attention. 

I tried to write an afterware to log these types of errors, but it didn't seem to surface in the afterware stage (presumably because the query itself runs fine, it just fails to write to the store).

**Version**
- apollo-client@1.9.1

**Comment by TinkGu** [comment]
same issue

**Comment by jbaxleyiii** [comment]
@maxsalven I agree this should be better! I'll add it to the post 2.0 when we work on better dev time warnings / issues!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Show%20store%20write%20errors%20in%20Console&body=Migrated%20from:%20apollographql/apollo-client%232097) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
