### ISSUE TITLE
isEqual: unable to compare objects created with Object.create(null)

### ISSUE THREAD

**Issue by slorber** [apollographql/apollo-client#2132]
Hi,

I want to report an exception thrown in `setVariables` I got, due to `isEqual` util. This affects latest client.

![image](https://user-images.githubusercontent.com/749374/30222884-ca1fbfce-94c8-11e7-87c6-c809b0171f42.png)

Most of the time this code path works fine, but I've found a case where it fails to compare 2 objects.

It is notably the case when one of them is created with `Object.create(null)` and does not have an object prototype and is a pure simple map of properties, thus no `hasOwnProperty` method.

Why would I want to create an object this way? Actually it's not me, it's the `query-string` npm package that, when parsing a string, returned me such object. 

I don't understand exactly the reasons but here's the line and there's an associated issue:
https://github.com/sindresorhus/query-string/blob/master/index.js#L127

Obviously there's a workaround: post-process all the objects I get from this lib (`return {...obj};` is enough), yet fixing this `isEqual` issue may save some time for other devs after me :)

**Comment by nevir** [comment]
👍 that should totally be doing `Object.prototype.hasOwnProperty.call(object, key)` (generally faster, too)

**Comment by slorber** [comment]
Thanks that seems like a good solution, I'll make a PR unless someone else wants to

**Comment by slorber** [comment]
done: https://github.com/apollographql/apollo-client/pull/2138
