### ISSUE TITLE
[2.0-alpha] published packages include babelrc (and a buch more)

### ISSUE THREAD

**Issue by nevir** [apollographql/apollo-client#2133]
apollo-client@2.0.0-alpha [includes `.babelrc`](https://unpkg.com/apollo-client@2.0.0-alpha.4/) and most of the original source.  

`.babelrc` is problematic for react native builds, at least, as babel consumes it and ends up not processing the built `apollo.umd.js` (because it's ignored by `.babelrc`)

**Comment by jbaxleyiii** [comment]
Fixed 🌮
