### ISSUE TITLE
Cannot access HTTP Reponse (response headers, status, etc) when using batchNetworkInterface in afterware

### ISSUE THREAD

**Issue by alexd16** [apollographql/apollo-client#2135]
**Intended outcome:**
When I setup the apollo client to use the batchNetworkInterface and I add an afterware It should allow me to inspect the HTTP Response. 
This is already the case when I add an afterware when using the simple networkInterface.

**Actual outcome:**
The middleware only gets called with the array of responses, without any of the HTTP Response information like headers or status information.

**How to reproduce the issue:**
I don't have a reproduction, but looking at the batchedNetworkInterface.ts at https://github.com/apollographql/apollo-client/blob/master/src/transport/batchedNetworkInterface.ts#L111 it looks like the HTTP response is discarded in case of success and only the query result data gets through.

Not sure if this should be listed as a feature request of a bug.

Thank you

**Version**
- apollo-client@1.9.1

**Comment by successkrisz** [comment]
We're experiencing the same issue as well, response headers are always empty, so can't extract tokens from it.

Are there any solution for this?

**Comment by jbaxleyiii** [comment]
@successkrisz @alexd16 the new apollo-link-batch-http should have this working for the 2.0! Can you verify it works that way? I'd be happy to accept a PR for the `latest` branch if you want to fix this for the 1.0 line!
