### ISSUE TITLE
Update Apollo Project Email Links

### ISSUE THREAD

**Issue by EmpireWorld** [apollographql/apollo-client#2136]
Hi.

I have starred this project and then i received an email titled: **Welcome to the Apollo project!**

And the email contains a link to Apollo Project, here is the link: http://em.meteor.com/O0C0YdcJ0200mR5F0I0D0t/

While it should go to the new Apollo GraphQL organization page, but it sends me to the old one.

Also most of the links in the email is old, please update them for new comers.

Hope this helps.

Thanks.

**Comment by jbaxleyiii** [comment]
cc @stubailo for the new site!
