### ISSUE TITLE
[Feature] Add possibility to subscribe to tearDown logic of ObservableQuery

### ISSUE THREAD

**Issue by stalniy** [apollographql/apollo-client#2141]
**Intended outcome:**

As a developer I want to be able to know when `ObservableQuery` is tear down. This will allow me to add extra cleanup logic.

**Motivation**:

I don't like the idea (because of coupling) that mutation should know which queries depends on it and update that queries in `update` method of mutation. That's why I want to fire an event  in `update` function of mutation and during query creation (I have a wrapper around Apollo's `watchQuery`) subscribe to events triggered by mutation. 

Afterwards when `ObservableQuery` is tear down I'd like to cleanup my extra subscriptions as well

**Possible solution**:

In rxjs there `Observer` interface has `complete` hook, so it'd be good to add something similar here as well

**Version**
- apollo-client@1.9.2

**P.S.**: thanks for your job guys, the project is awesome!

**Comment by jbaxleyiii** [comment]
@stalniy good news! The ObservableQuery in `2.0` uses a more robust Observable implementation so this is possible via `complete` now! Thanks for the issue!

**Comment by stalniy** [comment]
Cool! Thanks!

**Comment by sebastienbarre** [comment]
Could you guys check if this is working correctly with 3.2.4. My subscription's to `watchQuery()` never completes. Per the zen-observable doc, the third argument to `observable.subscribe(nextCallback[, errorCallback, completeCallback])` should be called when the query has completed.
