### ISSUE TITLE
Refetch remembers options.skip:true

### ISSUE THREAD

**Issue by robmoorman** [apollographql/apollo-client#2142]
**Intended outcome:**
Refetching data after an event (a transition has ended in my case) while skipping the initial fetch with `option.skip` set to `true`.

See also the source code: https://github.com/apollographql/apollo-client/blob/a70d45847492f12059460f7fcece5627da914c30/src/core/ObservableQuery.ts#L226-L230 (this is were I expect I can override options, e.g. skip).

**Actual outcome:**
Calling `refetch` doesn't do anything.

**How to reproduce the issue:**
```javascript
const MyComponentWithData = graphql(MY_QUERY, {
  options: (props) => ({
    fetchPolicy: 'network-only',
    skip: true,
  }),
  },
})(MyComponent)

class MyComponent extends Component {
  constructor () {
    super()

    this.handleRouteEntered = this.handleRouteEntered.bind(this)
  }

  componentDidMount () {
    this.props.events.addListener('routeEntered', this.handleRouteEntered)
  }

  componentWillUnmount () {
    this.props.events.removeListener('routeEntered', this.handleRouteEntered)
  }

  render () {
    return (
      <div />
    )
  }

  handleRouteEntered () {
    // This handler is called, but doesn't refetch data.
    // Setting options.skip back to false actually works (see data fetching
    // twice; on initial mount and in this handler).
    this.props.data.refetch()
  }
}

```
**Version**
- apollo-client@1.9.2
- react-apollo@1.4.14

**Comment by wmcbain** [comment]
@robmoorman Did you ever have a solution for this? Running into this problem as well

**Comment by jbaxleyiii** [comment]
@robmoorman @wmcbain can you try using the top level `skip` option on `react-apollo`? That is why we moved to recommending it!

**Comment by robmoorman** [comment]
He @jbaxleyiii what do you mean with top level? The issue is about missing these top level options within the `prefetch` method.

**Comment by wmcbain** [comment]
@jbaxleyiii Tried using the top level api like so:

```javascript
graphql(query, {
  options: ({ id, size, last }) => ({
    ...
  }),
  skip: ({ isAuthed }) => !isAuthed,
  props: ({ data, ownProps }) => {
    ...
```

Calling refetch still does not execute the query is the skip condition has changed.
