### ISSUE TITLE
Update to graphql@0.11.3

### ISSUE THREAD

**Issue by wzrdzl** [apollographql/apollo-client#2150]
[graphql@0.11.3](https://github.com/graphql/graphql-js/releases/tag/v0.11.3) fixes flow errors introduced by flow@0.54.x

The list of changes can be found here https://github.com/graphql/graphql-js/releases

Looks like the only breaking change is: 

> The subscribe() function now returns a Promise of either an AsyncIterator or ExecutionResult to better distinguish between initialization errors and publish errors; previously it just returned an AsyncIterator (#918).

**Comment by wzrdzl** [comment]
@stubailo Do you know if this breaking change affects us?

**Comment by jbaxleyiii** [comment]
@wzrdzl hmm I'll need to see if that does or not! My bet is that it will but with the 2.0 this logic is moved to the subscription transport link. Thanks for the info! This should allow us to upgrade the flow support as well 🎉
