### ISSUE TITLE
Cache doesn't update when object ID === 0

### ISSUE THREAD

**Issue by RedShift1** [apollographql/apollo-client#2164]
JSFiddle: https://jsfiddle.net/s7zgfsL7/2/

**Intended outcome:**
When an object is mutated, the cache is updated with the new values even if the object's ID === 0.

**Actual outcome:**
The cache is updated, but not when the object ID === 0. Cache update works successfully if object ID > 0.

**How to reproduce the issue:**
See https://jsfiddle.net/s7zgfsL7/2/ Clicking the "update" button should update that record. Only works for the 2nd instance.

![apollo_cache_bug_0](https://user-images.githubusercontent.com/3098010/30513280-f4238e3e-9b00-11e7-97da-acd20690a6ec.gif)

**Version**
- apollo-client@2.1.0-beta.19 (happens on 1.9.2 too)

**Comment by RedShift1** [comment]
Ping...

**Comment by RedShift1** [comment]
Ping

**Comment by RedShift1** [comment]
Ping

**Comment by RedShift1** [comment]
Ping

**Comment by hwillson** [comment]
Thanks for pointing this out @RedShift1 (and sorry about the delay in responding)! This is happening [here](https://github.com/apollographql/apollo-client/blob/90581787250bca8618aacd3795053b17944142d5/packages/apollo-cache-inmemory/src/writeToStore.ts#L379-L405):

```js
...
if (dataIdFromObject) {
  const semanticId = dataIdFromObject(value);
  ...
  if (semanticId) {
    valueDataId = semanticId;
    generated = false;
  }
}

if (!isDataProcessed(valueDataId, field, context.processedData)) {
  writeSelectionSetToStore({
    dataId: valueDataId,
    result: value,
    selectionSet: field.selectionSet,
    context,
  });
}
...
```

`dataIdFromObject` returns 0, which means `valueDataId` doesn't get set, leading to `writeSelectionSetToStore` not updating the store. Pull requests encouraged!
