### ISSUE TITLE
Installing apollo-client-preset has an incorrect version of apollo-utilities

### ISSUE THREAD

**Issue by stevewillard** [apollographql/apollo-client#2166]
When you run
```
yarn add apollo-client-preset
```

The version specified for `apollo-utilities` is '*' , so you get prompted to install a version:
```
Couldn't find any versions for "apollo-utilities" that matches "*"
? Please choose a version of "apollo-utilities" from this list: (Use arrow keys)
❯ 0.2.0-beta.0 
  0.2.0-alpha.6 
  0.2.0-alpha.5 
  0.2.0-alpha.4 
  0.2.0-alpha.3 
  0.2.0-alpha.2 
  0.1.1-1 
  0.1.1-0 
```
Even explicitly installing `0.2.0-beta.0` of apollo-utilities, I always get prompted on subsequent installs through yarn. Would it be possible to change the apollo-utilities from '*' to a more concrete version?

**Comment by jbaxleyiii** [comment]
This is fixed in the latest beta!
