### ISSUE TITLE
empty headers object in afterware response

### ISSUE THREAD

**Issue by Artem-Schander** [apollographql/apollo-client#2167]
Hi,

I have a similar issue to #1156. But in my case the response is completely empty.
Here is my afterware:
```javascript
apolloClient.networkInterface.useAfter([{
    applyAfterware({ response }, next) {
        if (process.env.NODE_ENV === 'development') {
            console.log('got new response', response);
        }
        next();
    }
}]);
```
Here is the real response:
![response screenshot](https://i.stack.imgur.com/ZdhEZ.png)

Here is the console log:
![console log screenshot](https://i.stack.imgur.com/uI9io.png)

BTW. I've already asked at [StackOverflow](https://stackoverflow.com/questions/46257557/apollo-client-has-no-headers-in-response)

**Comment by Artem-Schander** [comment]
is there anybody out there?

**Comment by bmeyers22** [comment]
I am also having this issue, headers are completely empty.

**Comment by jbaxleyiii** [comment]
@Artem-Schander did you create any headers on the initial request? This should be fixed by using `apollo-link` with the 2.0. Here is an upgrade guide if you are interested in the migration to links https://github.com/apollographql/apollo-client/blob/master/Upgrade.md#upgrading-from-custom-networkinteface-with-middleware--afterware

**Comment by bmeyers22** [comment]
Additional comment here, the headers object in Chrome is actually of the type Headers. To get the values you actually need to do `response.headers.get(key)` . This fixed the issue for me

**Comment by Artem-Schander** [comment]
Thanks to both of you, but update the apollo-client to v2 is in my case not an option. I'm using vue-apollo so the dependency is ^1.0

**Comment by martis347** [comment]
To receive headers, you need to expose them first on the server-side.  You can read more on `Access-Control-Expose-Headers`. If you're using `cors`, you may use:
```
app.use(cors({
  exposedHeaders: 'custom-header'
}));
```
I've found this information in this issue: https://github.com/apollographql/apollo-client/issues/1156
