### ISSUE TITLE
How to do authentication with ApolloClient 2.0?

### ISSUE THREAD

**Issue by nikolasburk** [apollographql/apollo-client#2168]
**Intended outcome:**

I'm trying to provide an authentication token to `ApolloClient` so that the requests it sends to the server are authenticated. I'm using the following versions of the npm packages:

```js
"dependencies": {
  "apollo-cache-inmemory": "beta",
  "apollo-client": "beta",
  "apollo-link": "^0.5.4",
  "apollo-link-http": "beta",
  "react-apollo": "^1.4.15",
  ...
},
```

Here's the code I'm using to setup my `ApolloClient` instance:

```js
import ApolloClient from 'apollo-client'
import Link from 'apollo-link-http'
import {ApolloLink, SetContextLink} from 'apollo-link'
import Cache from 'apollo-cache-inmemory'
import { ApolloProvider, gql } from 'react-apollo'

const setContext = (context) => ({
  ...context,
  headers: {
    ...context.headers,
    auth: localStorage.graphcoolToken,
  },
})

const link = ApolloLink.from([
  new SetContextLink(setContext),
  new Link({ uri: 'https://api.graph.cool/simple/v1/cj7m3k9nm047b012989jm6y9f' }),
])

const client = new ApolloClient({
  link,
  cache: new Cache(window.__APOLLO_STATE__),
})

client.initStore = () => {}
```

**Actual outcome:**

I'm getting the following runtime error:

```
Error: Link does not extend ApolloLink and implement request
```

**How to reproduce the issue:**

Create new project `with create-react-app`. Install the above listed dependencies and put the setup code into `index.js`, then run the app.

**Version**
- apollo-client@beta

**Comment by mech** [comment]
I have same problem also only my error is:

`SetContextLink is not a constructor`

**Comment by altschuler** [comment]
Just a guess, but I think you need to import the `HttpLink` like this:

`import { HttpLink } from 'apollo-link-http'`

And then obviously use `new HttpLink(...)` instead of just `Link`.

**Comment by JerryAWalker** [comment]
SetContextLink class extends ApolloLink from "apollo-link-core" that's where the issue is;
I didn't look too deep into it but  here
create your own SetContextLink, something like this
//
import { ApolloLink } from 'apollo-link';

class SetContextLink extends ApolloLink {

  constructor(setContext) {
    super();
    this.setContext= setContext;
  }

  request(operation,forward) {
    if (!operation.context) {
      operation.context = {};
    }
    operation.context = this.setContext(operation.context);
    return forward(operation);
  }
}

**Comment by n1ru4l** [comment]
I solved this issue by upgrading my dependencies:

```json
{
  "apollo-link": "0.6.1-beta.5",
  "apollo-link-http": "0.6.1-beta.5",
  "apollo-link-set-context": "0.6.1-beta.1"
}
```

**Comment by mech** [comment]
I am still seeing no headers so far :(

```js
import { ApolloClient } from 'apollo-client'
import HttpLink from 'apollo-link-http'
import Cache from 'apollo-cache-inmemory'
import { ApolloProvider } from 'react-apollo'
import SetContextLink from 'apollo-link-set-context'
import { ApolloLink } from 'apollo-link'

const setContext = context => ({
  ...context,
  headers: {
    ...context.headers,
    authorization: localStorage.getItem('token')
  }
})

// Somehow, the SetContextLink will not include the headers
const httpLink = ApolloLink.from([
  new SetContextLink(setContext),
  new HttpLink({ uri: 'http://localhost:3001/graphql' })
])

const client = new ApolloClient({
  link: httpLink,
  cache: new Cache()
})

class App extends Component {
  render() {
    return (
      <ApolloProvider client={client}>
        <Workspace />
      </ApolloProvider>
    )
  }
}
```

**Comment by n1ru4l** [comment]
@mech It only solved the errors for me. The headers are still missing. 😥

**Comment by samus42** [comment]
I've also been trying to solve this, when debugging the code I see the following:
in HttpLink.prototype.request at the line var headers = operation.getContext().headers;  If you look at the operations object, you can see operation.context.headers with your headers, however what gets returned will not have it.  When you step into operation.getContext(), you'll see your headers on the 'this.context' object, but the context object in there that gets returned does not have it.  Not sure if this is a scoping issue or not.  Still digging.

**Comment by samus42** [comment]
So when debugging this, I found the following
In HttpLink.prototype.request, line 40, the line var headers = operation.getContext().headers;
When inspecting operation, I could see operation.context.headers with my value.  

However, when stepping into operation.getContext() I could see this.context with my headers, however the context object used via var getContext = function () { return (__assign({}, context)); }; did NOT have those headers.  It's a completely different object.  I'm not sure if you're having some scoping issues or something here.

**Comment by jbaxleyiii** [comment]
@samus42 I'll take a look! Thanks!

**Comment by dacz** [comment]
any ideas when it could be solved? May I help somehow? Thanks!

**Comment by joarwilk** [comment]
This is how I do my auth headers, works just fine:

```
const AuthLink = (operation, forward) => {
  const token = store.getState().authToken;

  operation.setContext(context => ({
    ...context,
    headers: {
      ...context.headers,
      authorization: `Bearer ${token}`,
    },
  }));

  return forward(operation);
};

// ... and then in your link
const link = ApolloLink.from([
    AuthLink,
    new HttpLink({
      uri: `https://myendpoint.com/`,
    }),
]);
```

**Comment by seeden** [comment]
@joarwilk do you have problem with https://github.com/apollographql/react-apollo/issues/1192 as well? I am just curious

**Comment by joarwilk** [comment]
@seeden Not as far as I know. Not running 2.0 however

**Comment by jbaxleyiii** [comment]
@nikolasburk here is an upgrade guide! https://github.com/apollographql/apollo-client/blob/master/Upgrade.md#upgrading-from-custom-networkinteface-with-middleware--afterware

Auth should work easy and `graphcool` may even be able to ship an `apollo-link-graphcool` which would make this automatic for users!

**Comment by joarwilk** [comment]
@jbaxleyiii Great guide, thanks. I would add a note regarding which beta version the guide was written for. There is already a lot of conflicting tutorials for apollo link out there and since most people are using @beta its very hard to know if the code is relevant today or not.

**Comment by jbaxleyiii** [comment]
@joarwilk noted! You shouldn't need to use @beta for the links! I'll update the guide to make that clear!

**Comment by samus42** [comment]
that worked!  Thanks!

**Comment by mech** [comment]
Following the upgrade guide, I am getting: `'apollo-link-http' does not contain an export named 'createHttpLink'`

**Comment by dacz** [comment]
@mech This is moving target :) See https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-http ... this should work `import HttpLink from "apollo-link-http";` but it doesn't seem so, as one can see in the code.

Yesterday I spent an hour debugging `InMemoryCache` after upgrading from beta to rc and removed default export in favor of named export - in release notes (buried in latest branch) mentioned as "according to whole Apollo ecosystem".

The examples in the link mentioned here shows the default exports but they do not work.

Please, Apollo - tell us which exports will you use and stick with it. Your tools are great, but this back-and-forth with exports doesn't do any good.

**Comment by mech** [comment]
Sorry my fault, should have try the newer RC instead of Beta.

**Comment by swennemans** [comment]
For other impatient people like me, you could try it with:

```
import ApolloClient from 'apollo-client';
import { HttpLink } from 'apollo-link-http';
import { ApolloLink } from 'apollo-link';
import { InMemoryCache as Cache } from 'apollo-cache-inmemory';

const AuthLink = (operation, next) => {
  const token = localStorage.getItem('graphcoolToken');

  operation.setContext(context => ({
    ...context,
    headers: {
      ...context.headers,
      Authorization: `Bearer ${token}`,
    },
  }));

  return next(operation);
};

const link = ApolloLink.from([
  AuthLink,
  new HttpLink({ uri: 'API_UR' }),
]);

return new ApolloClient({
  link,
  cache: new Cache().restore(initialState || {}),
});
```

Happy coding!

**Comment by Yamilquery** [comment]
I've try everything but this don't work.

**Comment by miyi** [comment]
the documentation is so inconsistent. Official doc between Apollographql.com and their github README are all so different. Really wish someone can show me a working example.

**Comment by miyi** [comment]
this is doc for the presently functioning auth process, note that it uses setContext from 'apollo-link-context', the returned header has a spread operator on the requested header. 

https://github.com/apollographql/apollo-client/blob/master/docs/source/recipes/authentication.md

**Comment by vctormb** [comment]
@rmosolgo I guess they should put an example on how to use with apollo-boost too.

**Comment by jocoders** [comment]
Can you answer please for my question. When the Apollo setContext is working? In the app's initialization moment or later? Because in my case i need to save token to setContext, but when the app's initializated my local storage does not have any tokens, because the user has not looggedIn yet. He gets tokens only after signIn. And when he loggedOut the tokens are erasing. But i thing setContext is start to work in the beginning. Is it right?
