### ISSUE TITLE
Setting the redux store [Apollo Vanilla JS]

### ISSUE THREAD

**Issue by Parakoopa** [apollographql/apollo-client#2177]
This isn't really a bug, so I hope it's okay I don't use the issue template...

I'm currently trying to set the redux store of ApolloClient manually, in order to add Redux Offline support.
I know that in Apollo for React the Provider has an argument to take a custom store. However there doesn't seem to be a way to set the store using vanilla JS. 

The only issue here I could find (#1794) said that setStore shouldn't be used because it will propably not work correctly and that the store prop of ApolloProvider should be used.

Is there any way to achieve this without React? Currently I'm doing this, and it SEEMS to work without any issues:
```js
const apolloClient = new ApolloClient({
  /* ... */
})

const store = createStore(
   /* ... */
);
apolloClient.setStore(store);
```

**Comment by bskern** [comment]
I would be interested in this too. I couldn't quite figure out how the client received the store from the Provider in react-apollo so I could mimic that in my project that uses vanilla apollo.

**Comment by jbaxleyiii** [comment]
@Parakoopa the 2.0 actually doesn't use redux anymore and it has an API for rehydrating / setting the data in the cache 👍
