### ISSUE TITLE
Query variable from Redux props fails with error

### ISSUE THREAD

**Issue by aprofromindia** [apollographql/apollo-client#2179]
After much reading Apollo React documentation I am unable to create a GraphQL query using a Redux provided props variable `displayLocation` of the `DiscoveryList` component. Flow type of `displayLocation` given below: -

    type DisplayLocation = {
      lat: number,
      lng: number,
    };

My package.json includes only the following apollo entry

"react-apollo": "^1.4.15",

I am getting the following error: - `Variable lat of type Float! was provided invalid value`, surprisingly the provided value to the float variable is `37.33233141`. Redux and Apollo component integration code given below.

    export default compose(
      connect(({ displayLocation }) => ({ displayLocation }), {
        updateDisplayLocation,
      }),
      graphql(
        gql`
        query DiscoveryList($lat: Float!, $lng: Float!) {
          destinations(radius: {
            latitude: $lat,
            longitude: $lng,
            distance: ${RADIUS_IN_MTRS}})
            { name
              id
              country_code
            }
          }`,
        {
          options: ({ displayLocation }) => ({
            variables: {
              lat: displayLocation.lat,
              lng: displayLocation.lng,
            },
          }),
        },
      ),
    )(DiscoverList);

Many thanks for your help. 

I was also wondering to feed redux props into the Apollo GraphQL query, should we `connect()` redux first and then Apollo `graphql()` or the other way around before exporting the component please?

**Comment by jbaxleyiii** [comment]
@aprofromindia can you verify the variables being sent to apollo exist and if you run the same query in graphiql it works?
