### ISSUE TITLE
Rerun apollo queries that fail

### ISSUE THREAD

**Issue by jasonhero** [apollographql/apollo-client#2182]
Hey, I'm trying to implement a auth/refresh token flow into my apollo app.

What I’m trying to do:
- App makes a request, but auth token is invalid and server returns a 401.
- App realizes the 401, and makes a request for a new auth token.
- App receives the new auth token and retries the original request.

I’ve gotten the first 2 steps to work with afterMiddleware, but I can’t figure out a good way to make any query in my app to retry after it gets a new token.

**Comment by lukecwilliams** [comment]
Here's how we solved this issue (we're using Auth0).  Any fetch makes an async call to get an auth token first.  It tries to grab from, in this order:

1. In memory
2. Local storage
3. Refresh server (if we have token but it's expired)
4. Web authentication (if no token or token is for some reason invalid)

Helpfully, getAuthToken can be called by many fetches in parallel since it just returns a single promise that they can all `await`.

```
export default class Authentication {
  public static async getAuthToken(): Promise<string> {
    if (!this.tokenPromise || await hasExpired(this.tokenPromise)) {
      // Either we've never fetched, or memory was cleared, or expired

      this.tokenPromise = getUpdatedTokenPromise();
    }

    return (await this.tokenPromise).idToken;
  }

  public static async logOut(): Promise<void> {
    this.tokenPromise = null;
    await LocalStorage.clearAuthCredentials();
  }

  // Only the functions that need to mutate tokenPromise are in this class
  private static tokenPromise: Promise<IAuthToken> | null;
}

async function getUpdatedTokenPromise(): Promise<IAuthToken> {
  const { idToken, tokenExpiryDate } = await LocalStorage.getIdTokenOrNull();

  if (!idToken || !tokenExpiryDate || DBG_SHOULD_ALWAYS_LOG_IN === 'true') {

    return await doWebAuth();
  } else if (dateHasExpired(tokenExpiryDate)
    || DBG_SHOULD_ALWAYS_REFRESH_TOKEN === 'true'
  ) {
    return await refreshIdToken();
  } else {
    return { idToken, tokenExpiryDate };
  }
}

```

**Comment by jbaxleyiii** [comment]
@jasonhero @lukecwilliams this would actually be a perfect use case for an `apollo-link`!! Would either of you want to try writing that and I can help guide?

**Comment by lukecwilliams** [comment]
@jbaxleyiii We're actually really new here and just migrating over from Relay Modern - we'll take a look though.

**Comment by Bessonov** [comment]
@jasonhero see also https://github.com/apollographql/apollo-link/issues/297

**Comment by techyrajeev** [comment]
I found this example 

`
import ApolloClient from 'apollo-boost';

const client = new ApolloClient({
  uri: '<your graphql endpoint>',
  // Apollo Boost allows you to specify a custom error link for your client
  onError: ({ graphQLErrors, networkError, operation, forward }) => {
    if (graphQLErrors) {
      for (let err of graphQLErrors) {
        // handle errors differently based on its error code
        switch (err.extensions.code) {
          case 'UNAUTHENTICATED':
            // old token has expired throwing AuthenticationError,
            // one way to handle is to obtain a new token and 
            // add it to the operation context
            const headers = operation.getContext().headers
            operation.setContext({
              headers: {
                ...headers,
                authorization: getNewToken(),
              },
            });
            // Now, pass the modified operation to the next link
            // in the chain. This effectively intercepts the old
            // failed request, and retries it with a new token
            return forward(operation);
          
          // handle other errors
          case 'ANOTHER_ERROR_CODE':
            // ...
        }
      }
    }
  },
});

`
I already have apis ready to getNewToken but
I don't know how to implement getNewToken using graphql mutation.
Please provide some documentation or code snippet.
