### ISSUE TITLE
Default `errorPolicy` of `ignore` on mutations is a breaking change

### ISSUE THREAD

**Issue by jamesreggio** [apollographql/apollo-client#2190]
The title says it all.

Took a little while to track this one down.

**Comment by jamesreggio** [comment]
While we're at it, `none` feels like a bit of a misnomer, since `none` results in an exception being thrown. (`throw` would've felt a bit better to me.)

**Comment by leoasis** [comment]
Here's a PR that addresses this https://github.com/apollographql/apollo-client/pull/2194
