### ISSUE TITLE
Object not found in cache on followup query

### ISSUE THREAD

**Issue by tremby** [apollographql/apollo-client#2191]
I'm not sure this is a bug or not so will not go into a huge amount of detail just yet.

**Overview**

I have an initial large query which fetches an object of type `Thread` and various fields on it, including objects of type `Comment`. Some of these objects are several levels deep in the query.

If the user takes a particular action, I then query for a particular `Comment` object which was definitely returned in the original large query's result set. I'm not asking for any fields which were not already loaded, and IDs are included on every queried object in both queries. (I have a `dataIdFromObject` method set up, since my ID fields are called `hashid`, in case this is relevant.)

I expect the second small query to return the result set from cache, and not need to touch the network. The `fetchPolicy` is set to the default, `cache-first`.

**Intended outcome**

The data loads from cache.

**Actual outcome**

The data is not found in the cache, and is loaded instead (successfully) from the network.

I added some debug traces to `core/QueryManager.js` and `data/readFromStore.js` in an attempt to find out what it thinks is missing. I watched for where `hasMissingField` was switched to `true`, and added a trace (with the string borrowed from the `throw new Error` line), around `data/readFromStore.js:39`. This is giving me

```
Can't find field comment({"hashid":"mqG94gZwLdrW1OjM"}) on object (ROOT_QUERY) {
  "thread({\"hashid\":\"AdDVXdQY6lkn\"})": {
    "type": "id",
    "id": "AdDVXdQY6lkn",
    "generated": false
  }
}.
```

As said above, this object (an object of type `Comment` with `hashid` `mqG94gZwLdrW1OjM`) was definitely in the result set from the original query, with the ID (`hashid`) attached.

**How to reproduce the issue**

If this sounds like a bug, and the explanation above isn't enough, I'll come up with some example code.

**Version**

- apollo-client@1.4.0

**Thoughts**

As I said above, I'm not sure this is a bug or not. I wonder if I am missing some configuration value, or if I'm expected to manually add particular objects to the cache somehow.

It occurs to me that Apollo doesn't know from the query alone what type the result should be (or does it? how?), so could this be why it can't find the result in its cache? How would I tell it to expect a `Comment` type?

**Comment by jbaxleyiii** [comment]
@tremby if I understand this correctly, you are doing a mutation which results in a new `Comment` which you write to the store? Then you try to run a new query which would pull the comment out but wasn't the query you used to write it to the store?

Can you share the actual operations (graphql) that you are using?

Apollo has no way to know what type a root field will return so trying to pull the comment with a variable of the id can't resolve to it in the cache if Apollo doesn't know that is what the query is supposed to return. Does that make sense?
