### ISSUE TITLE
Can't pass and edit data from response

### ISSUE THREAD

**Issue by dusanmarsa** [apollographql/apollo-client#2195]
I'm using MobX and I need to pass data to MobX store. 

`store.rooms = data.rooms` not working

I also tryied `Object.assign` to lose apollo flag.. 

I need to get data from database and then edit them how i need.. Not only fetch. Can I do that? How?

**Comment by jbaxleyiii** [comment]
@dusanmarsa can you provide more information? A reproduction or code sample is needed for me to understand and help out more!
