### ISSUE TITLE
Allow for specifying variables as a generics argument in graphql TypeScript declaration for react

### ISSUE THREAD

**Issue by dyst5422** [apollographql/apollo-client#2198]
There are times when a query requires variables that are not useful to the underlying component. Currently, if I specify variables as part of the props the graphql function will receive, my component must also accept those variables.

This should be a relatively simple addition to the declaration to have an extra generic that is variables types defaulted to `{}` that gets merged into the returned react component type. Though as we all know, a seemingly simple change to types often causes a litany of other type headaches.

**Comment by jbaxleyiii** [comment]
@dyst5422 do you have any interesting in adding this?

**Comment by dyst5422** [comment]
I'll take a stab this week after I fix this one bug....

**Comment by dyst5422** [comment]
Would still like to see this get merged in.

**Comment by jbaxleyiii** [comment]
@dyst5422 I'll reopen and see if anyone can help add this!

**Comment by dyst5422** [comment]
I already opened a pull request for this one. I'm not sure if it's still compatible with V2

**Comment by jbaxleyiii** [comment]
@dyst5422 I'm not sure if it is either! I'm going to create an umbrella issue for typescript / type improvements to see about organizing towards a shared goal of better types (flow, improved depth of typings, etc)

**Comment by dyst5422** [comment]
Thats a good idea. I'll look into whether my PR on V1 is compatible with V2 (just upgraded yesterday, and I didn't have to touch my HOC's at all, so that's good news).

**Comment by hwillson** [comment]
This was addressed in https://github.com/apollographql/react-apollo/pull/1365. Closing - thanks!
