### ISSUE TITLE
Object has no __typename or id Available When Attempting to Specify IDs in ApolloClient dataIdFromObject in Angular (4); Webpack Fails to Compile

### ISSUE THREAD

**Issue by maplion** [apollographql/apollo-client#2201]
**Intended outcome:**
Specify IDs in Apollo configuration to tell queries about updates when new information becomes available for an Angular project, as per http://dev.apollodata.com/angular2/cache-updates.html

**Actual outcome:**
`Property '__typename' does not exist on type 'Object'.` and `Property 'id' does not exist on type 'Object'.` When angular-cli webpack attempts to compile.

**How to reproduce the issue:**
Create An Apollo client.ts with the following:
```typescript
import { ApolloClient, createNetworkInterface } from 'apollo-client';

const client = new ApolloClient({
    networkInterface: createNetworkInterface({
        uri: '/graphql',
        opts: {
            credentials: 'same-origin',
        },
    }),
    dataIdFromObject: o => `${o.__typename}-${o.id},`  // this object does not have __typename or id available and webpack fails to compile
});

export function getClient(): ApolloClient {
    return client;
}
```

It should be noted that in a similar React-based project, the following works fine:
```javascript
import ApolloClient from 'apollo-client';
const client = new ApolloClient({
    dataIdFromObject: o => `${o.__typename}-${o.id},` 
});
```

**Version**
- apollo-client@^1.9.2

Am I missing something on the Angular side or are others experiencing this issue?  Anyone know of a fix or workaround?  Thank you.

**Comment by ssatir** [comment]
I have a very similar issue.
When i try to create a client with:

```
import {createNetworkInterface} from "apollo-client";
import ApolloClient from "apollo-client/ApolloClient";

const client = new ApolloClient({
   networkInterface: createNetworkInterface({
      uri: 'http://localhost:8080/graphql'
      }),
   dataIdFromObject: o => o.id)
   });

export function provideClient(): ApolloClient {
  return client;
}
```

i get the error

> Property 'id' does not exist on type 'Object'.

Either the documentation is outdated or this is a bug. :(

I'm using `"apollo-client": "^1.9.3"`

Any hint is much appreciated.

**Comment by Nyaruiru** [comment]
The issue stems from type definition of 'IdGetter' function in Apollo client source code. 'dataIdFromObject' is of type 'IdGetter' which takes one argument of type 'Object' but the Object interface in the es5 library does note define '__typename' and 'id'. This makes that code fail the type check.
You can find type IdGetter in the last line of apollo-client's 'types.d.ts' file. Path to the file is 'node_modules>apollo-client>core>types.d.ts
FIX:
Find this line.
`export declare type IdGetter = (value: Object) => string | null | undefined;`

On top of it define an interface 'IdGetterObj' that extends interface Object and include '__typename' and 'id' as optionals as follows.
`
export interface IdGetterObj extends Object {
    /**dataIdFromObject typename and id definitions */
    __typename?: string;
    id?: number;
}
` 
Finally, change the type of the value in the original line to 'IdGetterObj' as follows.
`export declare type IdGetter = (value: IdGetterObj) => string | null | undefined;`

You should be good to go!

**Comment by maplion** [comment]
@Nyaruiru Thank you!  That seems to have fixed the issue for me.  It makes sense that it was a simple typing issue.  Just for clarification for others, the file you need to edit is `apollo-client/core/types.d.ts` and then just follow @Nyaruiru's comment above and you should be golden.

**Comment by Nyaruiru** [comment]
@maplion Im not very conversant with github. If you could make a pull request for the sake of the community, that would be good.

**Comment by maplion** [comment]
@Nyaruiru Will do, thanks again for your assistance.

**Comment by maplion** [comment]
Just FYI, I discovered from tests that the id type needs to be a string:  `export interface IdGetterObj extends Object { __typename?: string; id?: string; }`
