### ISSUE TITLE
Undefined values in variable get converted to `null` preventing GraphQL default values

### ISSUE THREAD

**Issue by migueloller** [apollographql/apollo-client#2205]
Moving from https://github.com/apollographql/react-apollo/issues/1038.

**Comment by migueloller** [comment]
Cant somebody (@jbaxleyiii?) look at this?

**Comment by jbaxleyiii** [comment]
@migueloller we are looking into this in another issue / PR! Hope to have a resolution for it soon!

**Comment by migueloller** [comment]
@jbaxleyiii, thank you so much!

**Comment by clschnei** [comment]
@jbaxleyiii This is still an issue over a year later.

Can we get links to issues/PR's related to this?

**Comment by seeden** [comment]
same here. please fix it and reopen

**Comment by ShepelievD** [comment]
the same with `"react-apollo": "^2.5.4"` & `"apollo-client": "^2.3.7",`

**Comment by iki** [comment]
Seems related to https://github.com/graphql/graphql-js/issues/1298
