### ISSUE TITLE
broadcastWatches called too many times by InMemoryCache

### ISSUE THREAD

**Issue by jay1337** [apollographql/apollo-client#2221]
InMemoryCache calls broadcastWatches many times during a mutation:

1. After writing the optimisticResponse to the cache
2. After each writeQuery/writeFragment in the update function of the mutation options called with the optimisticResponse
3. After processing the optimisticResponse
4. After writing the server response to the cache
5. After each writeQuery/writeFragment in the update function of the mutation options called with the server response
6. After processing the server response

Calls 1, 2, 4 and 5 are useless and cost a lot of time. With big (or many) observed query, it makes mutations very very slow...

**Comment by stubailo** [comment]
I fixed this in #2358!
