### ISSUE TITLE
readQuery and readFragment do (can) not return optimistic data

### ISSUE THREAD

**Issue by jay1337** [apollographql/apollo-client#2222]
After processing an optimistic response and before receiving the response from the server, if readQuery or readFragment is called from ApolloClient, it returns data ignoring the optimistic update.
I think the optimistic data should be returned instead. It would be coherent with the data available through observable queries.
At least, there should be an option ("optimistic:: true" ?) to let the user decide which version of the data return.

**Comment by jbaxleyiii** [comment]
@jay1337 I think there is a way to do this actually, you should be able to specify the optimistic nature of the response:

https://github.com/apollographql/apollo-client/blob/master/packages/apollo-cache/src/cache.ts#L69-L72

**Comment by jay1337** [comment]
@jbaxleyiii You can access to optimistic from the `Cache` object but not from the `ApolloClient` object.

You can have a look at the `ApolloClient` code : https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/ApolloClient.ts

To get an optimistic response from the `Cache` you have to provide a second argument being `true` to the `readQuery` or `readFragment` functions. But `ApolloClient`'s functions `readQuery` or `readFragment` never set this second argument when calling the `Cache`'s functions...

**Comment by jay1337** [comment]
Hey !

**Comment by jbaxleyiii** [comment]
@jay1337 heads up that I'm going to be turning off stalebot next week (getting ready to have Thanksgiving holidays in the US)

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=readQuery%20and%20readFragment%20do%20(can)%20not%20return%20optimistic%20data&body=Migrated%20from:%20apollographql/apollo-client%232222) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
