### ISSUE TITLE
addTypenameToSelectionSet do not add __typename to root query

### ISSUE THREAD

**Issue by jay1337** [apollographql/apollo-client#2224]
The function `addTypenameToSelectionSet` in `tranform.ts` from `apollo-utilities` do not add `__typename` field to the root query.
But the `match` function of `HeuristicFragmentMatcher` expects cached root query objects cached to have the `__typename` field (when it's called by `graphql-anywhere` in function `executeSelectionSet` through `execContext.fragmentMatcher`).

**Comment by valerybugakov** [comment]
Bumbed into the same issue, if I comment `if (!isRoot)` condition everything works fine, otherwise apollo throws an error in `executeSelectionSet`

**Comment by jbaxleyiii** [comment]
@jay1337 @valerybugakov do either of you have a reproduction for this issue?

**Comment by jay1337** [comment]
@jbaxleyiii I think the issue is clear enough, no ?

This function expect a `__typename` : https://github.com/apollographql/apollo-client/blob/master/packages/apollo-cache-inmemory/src/fragmentMatcher.ts#L28-L86

It is called at root level here : https://github.com/apollographql/apollo-client/blob/master/packages/graphql-anywhere/src/graphql.ts#L149

But the function that add `__typename` does not add it at the root level : https://github.com/apollographql/apollo-client/blob/master/packages/apollo-utilities/src/transform.ts#L22-L56

**Comment by jbaxleyiii** [comment]
@jay1337 I'm more interested in how you are getting errors in your app for this?

**Comment by pissarro** [comment]
Apollo Client CCTV app stopped working after the IOS11 download.
Anyone have a recommendation of a compatible app or solution?

**Comment by jay1337** [comment]
@jbaxleyiii Try running this code in any app with `apolloClient` being created with `addTypename` activated:

```apolloClient.writeFragment({
	fragment: gql`fragment aFragment on query {
		getSomething {
			id
		}
	}`,
	data: {
		'__typename': 'query',
		getSomething: { id: '123', '__typename': 'Something' }
	}
});
apolloClient.readFragment({
	fragment: gql`fragment aFragment on query {
		getSomething {
			id
		}
	}`
});
```

You should get theses warnings:

```
You're using fragments in your queries, but either don't have the addTypename:
  true option set in Apollo Client, or you are trying to write a fragment to the store without the __typename.
   Please turn on the addTypename option and include __typename when writing fragments so that Apollo Client
   can accurately match fragments.
'Could not find __typename on Fragment ', 'query', { 'getAnotherQueryAlreadyCalledInTheApp({"input":{}})':
...
DEPRECATION WARNING: using fragments without __typename is unsupported behavior and will be removed in future versions of Apollo client. You should fix this and set addTypename to true now.
```

It seems to raise warnings on previously cached queries. Maybe the problem is more complicated that what I thought...

**Comment by jbaxleyiii** [comment]
awesome! I'll take a look! Thanks for the info!

**Comment by jbaxleyiii** [comment]
@jay1337 The example code you have here is missing the id key for [reading](http://dev.apollodata.com/core/read-and-write.html#readfragment) and [writing](http://dev.apollodata.com/core/read-and-write.html#writequery-and-writefragment)

**Comment by jay1337** [comment]
You are right, the following code runs without warnings;

```
apolloClient.writeFragment({
	fragment: gql`fragment aFragment on query {
		getSomething {
			id
		}
	}`,
	data: {
		'__typename': 'query',
		getSomething: { id: '123', '__typename': 'Something' }
	},
	id: defaultDataIdFromObject({
		'__typename': 'query',
		getSomething: { id: '123', '__typename': 'Something' }
	}),
});
console.log(apolloClient.readFragment({
	fragment: gql`fragment aFragment on query {
		getSomething {
			id
		}
	}`,
	id: defaultDataIdFromObject({
		'__typename': 'query',
		getSomething: { id: '123', '__typename': 'Something' }
	}),
}));
```

Maybe you could improve the warning but I close this issue.
