### ISSUE TITLE
Subscriptions as a first-class citizen

### ISSUE THREAD

**Issue by dfee** [apollographql/apollo-client#2228]
[originally posted on /apollo](https://github.com/apollographql/apollo/issues/107) but reposted here as this seems like a more active(?) repo.

I'm not sure this is the right place to post this, so if not, please redirect me.

I'm not very interested in using `subscriptions-transport-ws` for my subscription transport. It's fine enough if you're using NodeJS on the backend, as you get the server side for free.

But for those of us who aren't using NodeJS on the backend, we need to either constantly update our code base to match changes to `subscriptions-transport-ws`, or roll our own subscription network interface.

I believe that is largely just writing a few function on a custom NetworkInterface object. But I don't see that documented anywhere – it doesn't appear to have a public facing interface. I think that oughta be documented [here](http://dev.apollodata.com/core/network.html#NetworkInterface).

Looking at the [client source](https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/client.ts) of `subscriptions-transport-ws`, it looks like the functions needed for implementation are:
1) [`status`](https://github.com/apollographql/subscriptions-transport-ws/blob/v0.9.0/src/client.ts#L133)
2) [`close`](https://github.com/apollographql/subscriptions-transport-ws/blob/v0.9.0/src/client.ts#L141)
3) [`request`](https://github.com/apollographql/subscriptions-transport-ws/blob/v0.9.0/src/client.ts#L163)
4) [`unsubscribe`](https://github.com/apollographql/subscriptions-transport-ws/blob/v0.9.0/src/client.ts#L237)

I believe this used to be simpler... but alas, it's been a couple months since looking at this.

For additional background, I've figured out how to use socket.io for queries and mutations, but i'd like to go ahead and add subscriptions.

**Comment by jbaxleyiii** [comment]
@dfee the 2.0 now uses `apollo-link` for the network interface so setting up your own subscription transport should be way easier!
