### ISSUE TITLE
graphql as peerDependency

### ISSUE THREAD

**Issue by bkniffler** [apollographql/apollo-client#2235]
Hey, 
I see that Apollo-client and apollo-link depend on different versions of graphql (0.10 vs 0.11). Wouldn't it make sense, since lots of your packages depend on graphql, to add it as a peer dependency to not run into issues with these version differences?

**Comment by jbaxleyiii** [comment]
@bkniffler I think that's a great idea!

**Comment by jbaxleyiii** [comment]
@bkniffler the only project using it directly in this repo was apollo-client and it didn't even need it! I've removed it [here](https://github.com/apollographql/apollo-client/pull/2281/commits/7d06fa6fdf909c2a45aef213a14160ae5900b844) and will make it peer in the Apollo Link project as well!

Thanks again!

**Comment by jbaxleyiii** [comment]
Actually it did need it haha. Made it to a peerDep
