### ISSUE TITLE
Query results are ignored when finished due to mismatching request ids

### ISSUE THREAD

**Issue by joarwilk** [apollographql/apollo-client#2256]
**Intended outcome:**
I make a lot of requests in parallel (without batching). One request is a lot slower than the others and may take some time to finish. When this request is finished the client ignores it completely and ends up in a permanent loading state. I have narrowed the issue down to this line:

https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/QueryManager.ts#L990

In my case the requestId is lower than lastRequestId.

Note: I am using apollo-link.

**Actual outcome:**
The result of the query should be saved to the store.

**Version**
- apollo-client@2.0.0-beta.4

**Comment by jbaxleyiii** [comment]
@joarwilk oh wow! Do you have a reproduction for this? I'd love to investigate and get it fixed!

**Comment by jbaxleyiii** [comment]
@joarwilk are you turning of deduplication? Are any of the request repeats?

**Comment by jbaxleyiii** [comment]
I tried to write a test based on the issue [here](https://github.com/apollographql/apollo-client/pull/2281/commits/69d4275856f53cba6c2db186049a92ed23772ab2) but its passing so I don't think I fully understand whats happening in your app

**Comment by joarwilk** [comment]
@jbaxleyiii I can't set up a repro case right now, sorry. For now I get around it by modifying the source in node modules directly via a small hook to remove the if statement. 

Is there any information I can extract from the cache / network when this happens that would help?

**Comment by jbaxleyiii** [comment]
hmm, maybe if you can send over the queries + variables (or obfuscated), how long the typically take, the order they are fired in, and which one hangs? That way I could write a test case for it?

**Comment by jbaxleyiii** [comment]
@joarwilk can you try the newest rc (`rc.4`?)
