### ISSUE TITLE
Entire application slows down after performing resetStore

### ISSUE THREAD

**Issue by scheiblr** [apollographql/apollo-client#2260]
**Intended outcome:**
I tried to implement a logout routine which refers back to the login page. I'm using session cookies which are cleared successfully. 
So I tried two versions to clean the apollo store according to http://dev.apollodata.com/react/auth.html#login-logout:
1. calling ` props.client.resetStore();` instantly **after logging in**
2. calling ` props.client.resetStore();` **after loggout**

**Actual outcome:**
The logout worked in both cases and the store seems to be emptied. BUT, when I login again without closing or completely refreshing the window, the client is terribly slow and sometimes I need to click the links twice in order to see data in the UI, otherwise it doesn't stop showing the loading screen.

This gets worse the more often I perform login/logout. There is no difference if I always login with the same user (so probably the store is really cleared). 

**Version**
- apollo-client@1.9.3

**Comment by jbaxleyiii** [comment]
@scheiblr do you have a reproduction showing this? And have you tried the 2.0?

**Comment by scheiblr** [comment]
@jbaxleyiii sorry, but as we use it in a bigger application stack I do not have a reproduction showing this.
Do you expect 2.0 to solve that issue? If so, I'd give it a shot (this will take some time to adopt the application).
