### ISSUE TITLE
Add a way to easily select data from apollo + redux store.

### ISSUE THREAD

**Issue by jjant** [apollographql/apollo-client#2261]
I'm finding it hard to select data from my redux store that depends on both, current redux state and data fetched by Apollo.

An example is the following: I have an `options` model, which has `id, name` properties. These `options` are fetched by apollo from the server. In a form, I have a select field, in which I store a selected option ID (which I use in a mutation, to change the currently selected option).

Now, sometimes I need to pass the currently selected option (stored in redux) name, to another component, for this, I have to do something a bit ugly like the following:

```jsx
const optionNameSelector = ({ options, optionId }) => options.find(option => option.id === optionId);

// And in the component I want:
// ...
const optionName = optionNameSelector({ options: data.options, optionId: state.optionId });
<MyComponent optionName={optionName} />
```

So my component has to know where to get the `options` from, instead of being able to just pass the whole state or something like that.

What's a better solution for this?

**I think having a denormalized apollo state in the redux store would be nice.**

**Comment by zapkub** [comment]
You can mutate Apollo store locally by using `apolloClient.writeQuery`, I suggest to use with redux-saga if you want to mutate Apollo data in Form 😀

**Comment by jjant** [comment]
@zapkub I'm not sure I follow how that helps with my use case, I'm not trying to mutate state, just access it as a regular js object.

**Comment by zapkub** [comment]
@jjant yes, because Apollo has it own way to store data.
So access it directly in Redux store is quite too difficult

 you can check `readQuery` for directly access to ApolloStore locally.

**Comment by jbaxleyiii** [comment]
@jjant the 2.0 actually detaches apollo from redux entirely. The `readQuery` method is the best way to read directly from the store
