### ISSUE TITLE
Add helper methods to read Apollo data from store directly

### ISSUE THREAD

**Issue by stubailo** [apollographql/apollo-client#227]
This probably just means nicely packaging the following:
- readQueryFromApolloState
- readFragmentFromApolloState

One question is, where do we get the config from? Since the configuration is currently passed into `new ApolloClient()`, we could do it like:

``` js
const client = new ApolloClient(...);

// somewhere else...

client.readQueryFromApolloState(state.apollo, gql`... query ...`, options);
```

`options` would be stuff like whether to return partial results, I guess.

Fun fact - with just a little bit of massaging these methods could eventually be modified to let you use GraphQL queries to access your client-side state as well, as long as it fits the correct normalized form!

**Comment by nevir** [comment]
https://github.com/facebook/relay/issues/114 might have some relevant insights here, too

**Comment by jbaxleyiii** [comment]
@stubailo is this still planned?

**Comment by Poincare** [comment]
@jbaxleyiii Sort of, although the `readObjectById` that is currently a PR is similar to but not exactly the same as `readFragmentFromApolloState`. The `readQueryFromApolloState` seems to be the same thing as the `noFetch` option that was added.

**Comment by SachaG** [comment]
I just ran into a use case for this, where I have to access the Apollo data from outside the React component tree. I actually managed to do it with the `noFetch` option, but my problem is that even with `noFetch`, `query` still returns a Promise, whereas I'm trying to get the results returned as a plain JS object.

In other words, I'm trying to replicate the behavior of Meteor's `Collection.find().fetch()` and I'm almost there but I'm just not sure what to do with that Promise object…

**Comment by SachaG** [comment]
FYI I ended up accessing `client.store.getState().apollo.data` directly, which works better for my purposes.

**Comment by stubailo** [comment]
There is .watchQuery(...).currentResult() now, which runs synchronously. Would that be better? Curious what the use case is.

**Comment by SachaG** [comment]
Oh maybe, I'd have to try it out. And the use case is getting a list of categories from the store to populate a `<select>` form element (in Telescope's Autoform-like form module): 

https://github.com/TelescopeJS/Telescope/blob/apollo/packages/nova-categories/lib/custom_fields.js#L31-L45

**Comment by helfer** [comment]
Done :tada:
