### ISSUE TITLE
Is it Google Closure compliant? 

### ISSUE THREAD

**Issue by uyouthe** [apollographql/apollo-client#2270]
Hello! 

I'm looking for graphql client library for Clojurescript application, and it seems like there's no graphql client libraries for clojurescript and I have to use some JS library. 

In order to use some js library in clojurescript app, I have to be sure that it wouldn't break after Google Clojure Compiler optimizations. 

Can Apollo graphql client be used with that optimizations?

**Comment by jbaxleyiii** [comment]
@uyouthe I'm not sure! Have you tried it?

**Comment by uyouthe** [comment]
Not yet. I'll reply there when I do
