### ISSUE TITLE
QueryScheduler causing unhandled promise rejection when using polling

### ISSUE THREAD

**Issue by dotansimha** [apollographql/apollo-client#2271]
Originally from here: https://github.com/apollographql/react-apollo/issues/1216

The actual code the does not handle the rejection is here:
https://github.com/apollographql/apollo-client/blob/a1217fbd1ebe8b56ff96dcb077430720dd0b381c/src/scheduler/scheduler.ts#L127

**Intended outcome:**
Should catch the error and trigger `error` of the `QueryObservable`.

**Actual outcome:**
If the server throws an error and fails the query, and the query is executed using polling mechanism, the error is thrown, caught on a higher level of Promise, but then it been thrown again and there is not `catch` that handles it.

**How to reproduce the issue:**
To see a running example with the error, clone this: https://github.com/dotansimha/apollo-client-unhandled-expection , under the `polling` directory.

Use pollInterval, cause the server to throw an error.
The stack trace is:
```
ExceptionsManager.js:73 Unhandled promise rejection Error: GraphQL error: ops
    at new ApolloError (apollo.umd.js:1981)
    at apollo.umd.js:3517
    at run (es6.promise.js:66)
    at es6.promise.js:79
    at flush (_microtask.js:18)
    at tryCallOne (core.js:37)
    at core.js:123
    at JSTimers.js:295
    at _callTimer (JSTimers.js:148)
    at _callImmediatesPass (JSTimers.js:196)
```

**Version**
- apollo-client@1.9.3

**Comment by jbaxleyiii** [comment]
Fixed via https://github.com/apollographql/apollo-client/pull/2281 and going out as `beta.7`. Thanks again for the reproduction! 🎉 couldn't have done it without you!

**Comment by dotansimha** [comment]
Thank you @jbaxleyiii ! :)
