### ISSUE TITLE
dataIdFromObject ignored when updating cache store

### ISSUE THREAD

**Issue by corvana-nbaker** [apollographql/apollo-client#2275]
**Problem:**
The same entity (identified by the same 'id) is retrieved as two different GraphQL types by two different queries.  One of the types is generic and the other specific (e.g. Animal -> Dog). When the generic query executes after the specific, the __typeName of the specific query is overridden with "Animal" despite "dataIdFromObject" on ApolloClient being defined as:

dataIdFromObject: o => o.__typeName + o.id

This results in a forced update of the component bound to the specific query.

**Version**
- apollo-client@1.8.1

**Comment by jbaxleyiii** [comment]
@corvana-nbaker can you create a small reproduction for this issue?

**Comment by corvana-nbaker** [comment]
I'll try to work on that later this week. We're in startup-mode, aka Crazy busy
