### ISSUE TITLE
client_1.createFragment is not a function

### ISSUE THREAD

**Issue by Gabriel-AL** [apollographql/apollo-client#2277]
Hi there, and thank you for all your work, it is amazing !

I am actually using Apollo while learning to use ReactJS & GraphQL. So I may be quite a newbie, I apologize about that.

To test if everything was working, I wanted to only list all the users of my database.  So I created a component:

```
import React from 'react';
import {graphql} from 'react-apollo';
import gql from 'graphql-tag';
import PropTypes from 'prop-types';


class ListOfUsers extends React.Component{
  static propTypes = {
    data: PropTypes.shape({
      loading: PropTypes.bool,
      error: PropTypes.object,
      users: PropTypes.object,
    }).isRequired
  }

  render () {
    if (this.props.data.loading) {
      return (<div>Loading</div>)
    }

    if(this.props.data.error){
      console.log(this.props.data.error);
      return (<div>Error</div>);
    }
    console.log(this.props.data);
    return (
      <div>this.props.data.users</div>
    )
  }
}

const queryTest = gql` query RootQuery {
    users {
      login
    }
  }
`


const usersWithLogin = graphql(queryTest)(ListOfUsers);
export default usersWithLogin;
```

I linked it in my main app, created the provider in my index.js (entry of the app)
```
import ApolloClient, {createNetworkInterface} from 'apollo-client';
import {ApolloProvider} from 'react-apollo';

const networkInterface = createNetworkInterface({uri: 'http://localhost:9000'});
const client = new ApolloClient({networkInterface});

ReactDOM.render((<ApolloProvider client={client}><App /></ApolloProvider>),
```
When I try to run the app (with my server running too), I get this error:
```TypeError: apollo_client_1.createFragment is not a function```

To me it looks like it comes from the "const usersWithLogin = graphql(queryTest)(ListOfUsers);" line, but I don't know how to do it in another way (it seems ok to me, according to all the tutorials I read).
Could you please tell me what I should do ?
I join to this post the details I have about the error.
Thank you again !
!

[capture du 2017-10-09 19-00-10](https://user-images.githubusercontent.com/11959730/31349692-87b4b4a4-ad24-11e7-9647-a073127f48dc.png)

**Comment by jbaxleyiii** [comment]
@Gabriel-AL sorry you ran into this issue! Would you be able to create a reproduction? And what versions of apollo-client and react-apollo?

**Comment by Gabriel-AL** [comment]
Hi back, and sorry for my answer's delay !

While trying to create a reproduction, I discovered that I did not have the latest version of apollo-client. Correcting it corrected the above error !

But I have a new problem now, and I don't get the cause.
- I have first set my server to return a response, and console.log the request. In Firefox, I can see that the client sent a POST request with parameters, and got an error in response. In my console.log, I can see that the server didn't get the parameters, nor the queries, in the request.
- I have set my server to not return a response if req.params.query didn't exist. Now the client seems to send a POST request without parameters at all...

I don't know what to do. May I open a new issue for that ? Do you think it may come from the server instead of the client ?

Thank you again for your time and patience,

**Comment by Gabriel-AL** [comment]
Hi back, and sorry for my answer's delay !

While trying to create a reproduction, I discovered that I did not have the latest version of apollo-client. Correcting it corrected the above error !

But I have a new problem now, and I don't get the cause.
- I have first set my server to return a response, and console.log the request. In Firefox, I can see that the client sent a POST request with parameters, and got an error in response. In my console.log, I can see that the server didn't get the parameters, nor the queries, in the request.
- I have set my server to not return a response if req.params.query didn't exist. Now the client seems to send a POST request without parameters at all...

I don't know what to do. May I open a new issue for that ? Do you think it may come from the server instead of the client ?

Thank you again for your time and patience,

(I made a reproduction ! https://github.com/Gabriel-AL/apollo-error )
