### ISSUE TITLE
New ApolloClient 2 "Link" No 'Access-Control-Allow-Origin' header is present on the requested

### ISSUE THREAD

**Issue by PtwHub** [apollographql/apollo-client#2279]
Just porting to ApolloClient 2. Everything seems to work except for replacing the "networkInterface" with the new "Link" breaks the CORS header: the Access-Control-Allow-Origin is simply missing now. My server has not changed. Any ideas/tips?

**Version**
    "apollo-cache-inmemory": "^0.2.0-beta.4",
    "apollo-client": "^2.0.0-beta.4",
    "apollo-link-http": "^0.6.1-beta.6",
    "false": "0.0.4",
    "graphql-tag": "^2.4.2",
    "graphql-tools": "^2.1.0",
    "polished": "^1.7.0",
    "react": "^16.0.0",
    "react-apollo": "^2.0.0-beta.0",
    "react-dom": "^16.0.0",
    "react-scripts": "1.0.14",
    "material-ui": "next",
    "material-ui-icons": "^1.0.0-beta.10"

**Comment by jbaxleyiii** [comment]
@PtwHub sounds like its missing the `credentials` part of the `fetch` request. I'm going toad that as the default in an upcoming release but for now you should be able to add them with a link that modifies the context (https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-http#context). The updated package should be about this week. You should also be able to use not the beta's for apollo-link, instead us the `latest` builds!

**Comment by PtwHub** [comment]
Thanks, got it. Now, I have the apollo-client and apollo-link directly from the #latest repo, but I can't seem to find a way to get the apollo-link-http "latest" in the same manner. What's the scoop here?

"dependencies": {
    "apollo-cache-inmemory": "^0.1.0-0",
    "apollo-client": "git+https://github.com/apollographql/apollo-client.git#latest",
    "apollo-link": "git+https://github.com/apollographql/apollo-link.git#latest",
    "apollo-link-http": "^0.7.0",
    "graphql-tag": "^2.4.2",
    "graphql-tools": "^2.1.0",
    "material-ui": "next",
    "material-ui-icons": "^1.0.0-beta.10",
    "react": "^16.0.0",
    "react-apollo": "^2.0.0-beta.0",
    "react-dom": "^16.0.0",
    "react-scripts": "1.0.14"
  },
