### ISSUE TITLE
@connection directive not being stripped before hitting server

### ISSUE THREAD

**Issue by bennyhobart** [apollographql/apollo-client#2282]
**Intended outcome:**
Have `@connection` directive stripped in apollo link

**Actual outcome:**
Connection directive is not stripped leading to error from my GraphQL
 server
![screen shot 2017-10-11 at 3 31 48 pm](https://user-images.githubusercontent.com/3694930/31422447-621f896e-ae99-11e7-8c60-f257e2171967.png)

**How to reproduce the issue:**
```
const link = new HttpLink({
  fetch: async (_, args) => {
       // My Fetch implementation
  },
});

const client = new ApolloClient({
  link,
  cache,
});

client.query({ ...query using connection directive });
```

**Version**
- apollo-client@2.0.0-beta.5

**Comment by jbaxleyiii** [comment]
well that's no go! I'll take a look! Thanks for the report!

**Comment by jbaxleyiii** [comment]
@bennyhobart this is fixed via [this commit](https://github.com/apollographql/apollo-client/pull/2281/commits/7d06fa6fdf909c2a45aef213a14160ae5900b844) and is on npm under `apollo-client@2.0-beta.6`!

Thanks again for the bug report!

**Comment by jbaxleyiii** [comment]
Fixed on https://github.com/apollographql/apollo-client/pull/2281

**Comment by bennyhobart** [comment]
thanks so much for the quick response love you guys
