### ISSUE TITLE
Export DocumentNode Type

### ISSUE THREAD

**Issue by Ayc0** [apollographql/apollo-client#2287]
Currently, if you want to you flow in react with apollo, you have to use the type `DocumentNode`. But this type is only available in the `graphql` package. So the issue is that the only variable that is imported from `graphql` in the the `DocumentNode` type, and so the graphql package is just imported for one optional var and we have to ensure that the version of `graphql` is the same that the one used by `apollo`.

As `react-apollo` export everything from `apollo-client`, the type should be exported here, in the file `apollo-client/src/core/types.ts`

**Comment by jbaxleyiii** [comment]
@Ayc0 with the 2.0 we no longer export everything all together. We will be working on adding back flow type support for the 2.0 soon and will make sure it is as good of an experience as we can!

**Comment by ammanvedi** [comment]
update on this?
