### ISSUE TITLE
Consistency across packages with named exports

### ISSUE THREAD

**Issue by peggyrayzis** [apollographql/apollo-client#2288]
Across our packages, especially in Apollo Link, we should be more consistent with suggesting to use named vs. default exports.

I ran into a issue today where `ApolloLink.from([])` was causing an error because I was using the default vs. the named `ApolloLink` export. Some of our links vary too (HttpLink uses a named export, WSLink uses the default).

@jbaxleyiii and I discussed earlier that we should use named exports for all of our packages. We need to:

- [ ] Make sure the packages themselves are using named exports
- [ ] Change examples in the docs / READMEs to use named exports
- [ ] Change CodeSandbox & any other examples

**Comment by jbaxleyiii** [comment]
Done via https://github.com/apollographql/apollo-client/pull/2281 and the links PR 🌮
