### ISSUE TITLE
Many sequential subscription events cause long JS block

### ISSUE THREAD

**Issue by Rusfighter** [apollographql/apollo-client#2290]
Hey folks,

I am currently developing a chat part in ours react native like whatsapp. Currently, I am focusing on the offline part of the application. When the user resubscribes, all the events that the user missed are pushed through the subscriptions (websocket). This cause a lot of subscribeToMore.updateQuery  calls in a very short period of time. The updateQuery method is not a heavy operation, but returning the new state the apollo client blocks the JS thread updating and diffing the store, I guess.

```
document: MESSAGE_MUTATION,
  updateQuery: (previousResult, { subscriptionData }) => {
    let result = previousResult;

    const { messageMutation } = subscriptionData.data;
    // check what kind of mutation
    if (messageMutation.type === 'CREATED') {
      const newMessage = messageMutation.message;

      previousResult.me.channels.forEach((channel, i) => {
        if (channel.id === newMessage.channelId) {
          if (!find(channel.messages, { id: newMessage.id })) {
            result = update(previousResult, {
              me: {
                channels: {
                  [i]: {
                    messages: { $unshift: [newMessage] },
                  },
                },
              },
            });
          }
        }
      });
    }
return result;
```

Even if I comment out the whole channel checking and message being added to the channel and just return the previousResult, the JS gets blocked for a while making the app not responsive. I guess this happens because of the store diffing?

Could it be a suggestion to make the updateQuery a async function so it can be used with requestAnimationFrame or packages such as https://www.npmjs.com/package/next-frame.

Also should I migrate to the apollo-client 2.0 to solve this kind of problems?

**Comment by jbaxleyiii** [comment]
@Rusfighter the 2.0 should help as it has a much more performant store, but I think there are still changes we can make to improve this!

Can you update and see how it performs?

**Comment by Rusfighter** [comment]
I didn't test it yet with 2.0. However I implemented a function that write to the store only once x seconds on new sub event.

```
 let dataState;

  // debounce
  const writeToStore = debounce(async () => {
    if (dataState) {
      await new Promise(InteractionManager.runAfterInteractions);
      client.writeQuery({
        query: GET_CHANNELS_QUERY,
        variables: {
          limit: 1,
        },
        data: dataState,
      });
      dataState = undefined;
    }
  }, 300);


  const onNewEvent = (state, { channelMutation }) => {
    // find channel
    const { channelId } = channelMutation;

    const channel = find(state.chat.private, { id: channelId })
      || find(state.chat.group, { id: channelId })
      || find(state.chat.broadcast, { id: channelId });

    if (channel) {
      channel.events = unionBy([channelMutation], channel.events, 'id');
    }

    console.log('channelMutation', state);
    // dispatch(onNewChatEvent(messageMutation.cursor));
    return state;
  };

  return subscribeToMore({
    document: CHANNEL_MUTATION,
    updateQuery: (pResult, { subscriptionData }) => {
      if (!dataState) {
        dataState = cloneDeep(pResult);
      }
      dataState = onNewEvent(dataState, subscriptionData.data);

      writeToStore();
    },
  });
```

One thing to mention, i think the performance is really depended on the deep of the nested object you update.

**Comment by Rusfighter** [comment]
@jbaxleyiii The above solution I gave only works for inmemory cache which is not very large. The main problem is that every incoming subscription (even if it is new) is going through the cache diffing process. However I wonder if this could be easily be disabled for some subscriptions/queries?

**Comment by hwillson** [comment]
@Rusfighter If you haven't already, please try updating to a 2.x version, and post back if you're still running into issues. As mentioned in https://github.com/apollographql/apollo-client/issues/2290#issuecomment-342166544, 2.x is much more performant and should help with your issue. Thanks!

**Comment by rostislav-simonik** [comment]
Same problem at me,  I'm using
 - apollo-cache-inmemory@1.1.10
 - apollo-client@2.2.6

Problem is when I have multiple registrations and I trigger query with complex projection, then internal diff and broadcast logic takes time. Maybe good approach is to that stuff partially through async calls so other logic in app takes place, especially navigation. At this moment app completely freezes, for that period. 


See performance output:


![image](https://user-images.githubusercontent.com/25525736/44788727-12e3ce00-ab9b-11e8-8ae7-a8be5f78a5ad.png)
