### ISSUE TITLE
Apollo-client 2, graphql body content contains empty object, causes server parser error.

### ISSUE THREAD

**Issue by PtwHub** [apollographql/apollo-client#2291]
Hi,

I'm using the newest packages (I think, see below). When I send of this query:
`const channelsListQuery = gql`
{
  hero {
    name
    friends {
      id
      name
    }
  }
}
`;`

I get a POST body like this, which causes my server to "internal server error status 500".

`{"operationName":null,"variables":{},"query":"{\n  hero {\n    name\n    friends {\n      id\n      name\n}\n}\n}\n"}`

When I change the "variables":{} to "{}" or "null" or null, it works fine as follows:

`{"operationName":null,"variables":"{}","query":"{\n  hero {\n    name\n    friends {\n      id\n      name\n}\n}\n}\n"}`

I'm getting the feeling that this may be a client bug, since the query is itself quoted, why shouldn't the variables be quoted as well? I didn't find clarity in the spec [here](http://graphql.org/learn/queries/) for empty variables.

**Version**
    "apollo-cache-inmemory": "beta",
    "apollo-client": "beta",
    "apollo-link": "^0.7.0",
    "apollo-link-http": "^0.7.0",
    "graphql-tag": "^2.4.2",
    "graphql-tools": "^2.1.0",
    "material-ui": "next",
    "material-ui-icons": "^1.0.0-beta.10",
    "react": "^16.0.0",
    "react-apollo": "beta",
    "react-dom": "^16.0.0",
    "react-scripts": "1.0.14"
  },

**Comment by jbaxleyiii** [comment]
@PtwHub that sounds like the variables aren't being stringified correctly for you? Can you create a reproduction for me to take a look at?

**Comment by PtwHub** [comment]
Thanks. I could pack the client up for you, but the server is already available [here](https://github.com/JacekKosciesza/StarWars) and then all I used to narrow down the problem the  apollo-client tutorial ["graphql-tutorial-t1-end"](https://dev-blog.apollodata.com/full-stack-react-graphql-tutorial-582ac8d24e3b), ported it to the current 2.0 drop (dependencies above) and then pointed it at a non-Javascript [GraphQL-Server ](https://github.com/JacekKosciesza/StarWars) which works fine with various other scenarios. Should I pack up just the client for you?

**Comment by jbaxleyiii** [comment]
@PtwHub we are stringifying the operation to send to the server [here](https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-http/src/httpLink.ts#L117-L126). I'm not sure why your server would be parsing it like that?

**Comment by PtwHub** [comment]
Yes, I saw. Yes, our server can handle it (after patch) but it still boils down to a weird/confusing discrepancy in the http-body format: using two different JSON representations in one message? Why should the variables be the only thing that is not quoted in the JSON representation? As above, I haven't found an explanation in the spec for this... Thanks for the input -- and for the great apollo-client of course!

**Comment by PtwHub** [comment]
OK, closing. May be an unnecessary complication in the graphQL spec if it allowing a mixture of valid representations. Better would be to permit one universally valid representation, but not a mixture as follows:

{
  "operationName": null,
  "variables": "{}",
  "query": "{\n hero {\n name\n friends {\n id\n name\n}\n}\n}\n"
}
