### ISSUE TITLE
Proposal: opening up the cache-inmemory implementation [apollo-client@2.0]

### ISSUE THREAD

**Issue by niieani** [apollographql/apollo-client#2293]
Hi apollo-client devs! Such an _amazing_ job with the 2.0 release so far, kudos. 💥 

We've decided to port our setup over to Apollo 💛, but our needs are such that we want to integrate it with our custom `Observable` cache for storing the normalized objects. 

The main problem is the way those normalized objects are currently stored and modified. Our implementation requires us to dispatch events whenever any object changes in the store, however that's currently impossible without actually forking the whole package.

The way objects are updated now is by modifying the `data` object directly -- and there is no way to hook into the `set` or `delete` events (without resolving to hacks like ES6 Proxies, which aren't supported everywhere yet).

The simplest solution to this is adding a Map-like API/abstraction over the [`data` property](https://github.com/apollographql/apollo-client/blob/489e4b74ea74f7d0884aaa049c909fb267086e20/packages/apollo-cache-inmemory/src/inMemoryCache.ts#L38), so that instead of working with a pure object, it would work with an API, like this:
- `this.data[dataId] = x` => `this.data.set(dataId, x)`
- `this.data[dataId]` => `this.data.get(dataId)`
- `delete this.data[dataId]` => `this.data.delete(dataId)`
- `this.data = {}` => `this.data.clear()`
- `this.data` => `this.data.toObject()` (extra method that flattens the contents to a plain object)

This way `data` can be a single instance throughout the whole life of the `InMemoryCache` and its underlying implementation can vary -- i.e. it can be an `Object`, as it is now, or a native `Map` (which is generally faster than `object[key]` operations).

A similar abstraction could be put in place of the `optimistic` property, currently an `Array` instance, but it could have a simple, `Set`-like interface.

I have the first change ready in a fork (it's a simple change, though in many places), with all the tests passing, and I've also added some extra ones for the added abstraction. This feature would greatly simplify our setup, since we would not need to fork the whole package, but only provide a custom implementation of the Cache when it is constructed.

If you are happy with this proposal, I'll refactor my fork, cleanup the commits and open a PR 🥇.

Also, we'd be happy to share our Observable-based implementation of the cache with the Apollo OSS community, once it's ready.

**Intended outcome:**
Able to hook the changes to cache, while re-using 99% of the `apollo-cache-inmemory` without creating a fork.

This requires adding two simple abstractions:
1. over the `data` property [defined here](https://github.com/apollographql/apollo-client/blob/489e4b74ea74f7d0884aaa049c909fb267086e20/packages/apollo-cache-inmemory/src/inMemoryCache.ts#L38)
2. over the `optimistic` property [defined here](https://github.com/apollographql/apollo-client/blob/489e4b74ea74f7d0884aaa049c909fb267086e20/packages/apollo-cache-inmemory/src/inMemoryCache.ts#L40)

**Actual outcome:**

Fork was required. :)

**Version**
- apollo-cache-inmemory@0.2.0-beta.4

**Comment by jbaxleyiii** [comment]
I'm all for this! The external API provided by Apollo Cache should be able to stay the same and the internals change as needed! Let's try it out!

**Comment by kamilkisiela** [comment]
@niieani @jbaxleyiii If we would abstract data's setter and getter it would be super easy to use normalized cache in `@ngrx/store` :ng: :+1: . 
I forked Apollo's `InMemoryCache` few days ago and created a working prototype based on it.

Would be awesome to make it till the official release :heart:

**Comment by kamilkisiela** [comment]
@niieani any progress on that?
