### ISSUE TITLE
Stale-but closes issues with no way for users to re-open them

### ISSUE THREAD

**Issue by ghostganz** [apollographql/apollo-client#2307]
I keep seeing important issues being closed by "stale" just because no one has commented in them for a few days.

The message says "_If you belive this issue is still a problem or should be reopened, please reopen it!_", but **there is no way for me to re-open** them, is there?

For example https://github.com/apollographql/apollo-client/issues/51 that has 14 thumbs-down on the bot's closing message. This is causing unneccessary frustration.

**Comment by jbaxleyiii** [comment]
@ghostganz I'm sorry that its causing frustration for you! I'd like to open up the ability for users to add labels which will prevent stale bot from closing issues. I'm surprised you can't reopen them as well? I'll look into that!
