### ISSUE TITLE
InMemoryCache.readQuery returns the result directly

### ISSUE THREAD

**Issue by kamilkisiela** [apollographql/apollo-client#2308]
Here's the line that is responsible for that:
https://github.com/apollographql/apollo-client/blob/91f5116ce830151e6bedf92e10550c607984e11c/packages/apollo-cache-inmemory/src/readFromStore.ts#L52-L55

**Intended outcome:**
`InMemoryCache.readQuery()` should return `Cache.DiffResult`

**Actual outcome:**
It returns query's results directly instead of keeping it under `result` property.

**How to reproduce the issue:**
Check the code I provided in description above.

**Version**
- apollo-client@^2.0.0-rc.0

**This will be a breaking change**
In ApolloClient 1.0: `proxy.readQuery()` returns results directly
In ApolloClient 2.0: `proxy.readQuery()` returns results under `result` property (`Cache.DiffResult`)

```ts
apollo.mutate({
  /* ... */
  update(proxy, result) {
    const data = proxy.readQuery(/* ... */); <--- to .result, or not to .result that is the question
    
    proxy.writeQuery({
      /* ... */
      data: update(data, result.data),
    });
  }
})
```

**Comment by jbaxleyiii** [comment]
@kamilkisiela hmm I think the safest solution would be to change the type signature of readQuery and return the results directly as to not break a ton of application code. Do you have a usecase for having the `DiffResult` or were the typings just wrong messing with your application?

**Comment by kamilkisiela** [comment]
@jbaxleyiii I updated one of available examples to new `apollo-angular` API.

First, TypeScript threw an error about a mismatch in typing between ApolloClient and what my app expected.
Second, after fixing it my app broke.

I'll create a PR to make `readQuery` returns just results.

**Comment by jbaxleyiii** [comment]
@kamilkisiela awesome thank you!
