### ISSUE TITLE
Subscription results have extra(?) data key in 2.0.0-rc3

### ISSUE THREAD

**Issue by MattCain** [apollographql/apollo-client#2329]
After upgrading to `apollo-client@2.0.0-rc.3` the shape of the `data` prop my React component is receiving has changed.

I'm doing this: 

```
export default graphql(
	gql`
		subscription priceSub {
			Price {
				bid
				ask
			}
		}
	`
)(MyComponent);
```

**Intended outcome:**

Previously inside `MyComponent` I could access the `bid` value with `this.props.data.Price.bid`.

**Actual outcome:**

Now it's `this.props.data.data.Price.bid`. Note the extra `data`.

This is the case using both `react-apollo@1.4` and `2.0.0-beta.0` which is why i'm thinking that `apollo-client` is responsible.

**How to reproduce the issue:**

Use a subscription as above. I tried to put together a repro but codesandbox couldn't find the release candidate of `apollo-client` 😕  Sorry if this isn't much to go on.

**Version**
- apollo-client@2.0.0-rc.3

**Other dependency versions**
- apollo-link-ws@0.6.0
- apollo-cache-inmemory@0.2.0-rc.1
- react-apollo@2.0.0-beta.0

Not sure if it's intended or a bug but thought i'd report it anyway just in case. Thanks.

**Comment by jbaxleyiii** [comment]
@MattCain ah! Yes apollo-link returns the full execution result! Fixed via https://github.com/apollographql/apollo-client/pull/2342/commits/f8990960468a13e87e514c1a2b985e03069fa9ab
