### ISSUE TITLE
optimisticResponse is very slow

### ISSUE THREAD

**Issue by xavimb** [apollographql/apollo-client#2338]
After upgrading to 2.0.0-beta.3 in our React Native app, optimistic responses are very slow and make the app almost unusable.

**Intended outcome:**

After making a mutation with `optimisticResponse`, the `update` function is called immediately with the data from the optimistic response object.

**Actual outcome:**

After making a mutation with `optimisticResponse`, the `update` function takes a lot of time (from 300ms to several seconds) to get executed.

**How to reproduce the issue:**

I find this issue in all the optimistic updates in the app. This is an example code of a mutation that leads to this result:

    await mutate({
        variables: {
            input: {
                voucherKey
            }
        },
        optimisticResponse: {
            __typename: "Mutation",
            deleteUserDiscount: {
                voucherKey,
                __typename: "UserDiscount"
            }
        },
        update: (store, { data: { deleteUserDiscount } }) => {
            const data = store.readQuery({ query: CART_ITEMS });
            data.cartWithDeliveryBundles.voucher = null;
            store.writeQuery({ query: CART_ITEMS, data });
       }
    });

**Version**
- apollo-client@2.0.0-beta.3

**Comment by jbaxleyiii** [comment]
@xavimb a couple questions for you!

1. can you verify update is being run for the optimistic response AND the result from the server?
2. how long does it take for your server response to come back?
3. Do you have any kind of reproduction I could take a look at?

**Comment by jay1337** [comment]
@xavimb Same observation on my side. I bet you have a lot or big queries being watched, or that were watched or fetched in the past. Or you may have a lot of React components that rerender although they should not.

Cf :
https://github.com/apollographql/apollo-client/issues/2221
https://github.com/apollographql/react-apollo/issues/1258
https://github.com/apollographql/apollo-client/issues/2340
https://github.com/apollographql/apollo-client/issues/2344

**Comment by jbaxleyiii** [comment]
@jay1337 @xavimb can you also try the newest rc (`rc.4`?)

**Comment by xavimb** [comment]
@jbaxleyiii @jay1337 it's fixed in rc.4. Thanks a lot guys!
