### ISSUE TITLE
query remains watched in cache after apolloClient.query(...)

### ISSUE THREAD

**Issue by jay1337** [apollographql/apollo-client#2340]
After calling `apolloClient.query(...)` the query remains watched in `InMemoryCache`. It leads to a major performance issue since writing to the cache (and so broadcasting watches) takes more and more time after each `apolloClient.query(...)` call.

To reproduce this you can just call many times `apolloClient.query(...)` with any query and look at `this.watches.length` in `InMemoryCache` object.

Version : `2.0.0-rc.3`

**Comment by jbaxleyiii** [comment]
@jay1337 oh dang! Thank you so much for the info! It will be fixed with the next release!

**Comment by jay1337** [comment]
@jbaxleyiii If you like this one, maybe you will like this other issue : https://github.com/apollographql/react-apollo/issues/1258

And don't forget that there are still 4 useless broadcastings for each mutation with optimistic response: https://github.com/apollographql/apollo-client/issues/2221
