### ISSUE TITLE
Apollo 2.0: subscribe disappeared, subscribeToMore ... what does it do?

### ISSUE THREAD

**Issue by tomitrescak** [apollographql/apollo-client#2343]
Hi, what is the substitution to subscribe ?
There is now subscribe toMore but that is related to subscriptions rather then to watched queries

How can I now observe a query?

Thanks

**Version**
- apollo-client@2.0-rc-2

**Comment by jbaxleyiii** [comment]
@tomitrescak I'm confused? No subscribe API has been changed?
