### ISSUE TITLE
new data prop sub content with same content

### ISSUE THREAD

**Issue by jay1337** [apollographql/apollo-client#2344]
I have a React component wrapped with a query. When a mutation result changes the query result, the component is updated but with a totally new `props.data`, even if some of the sub content was not changed by the mutation. It makes children components that compare (with `===`) previous and new sub content rerender although they should not.

The problem comes from here: https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/ObservableQuery.ts#L176

After a mutation, there is a forced update of QraphQL wrapping component. But since `this.variables` may be different from `this.lastVariables` (`setVariables` that manages their values is not called in case of a mutation...), the data is read from cache instead of looking at `lastResult` which contains the right data.

**Version**
- apollo-client@2.0.0-rc.3

**Comment by jbaxleyiii** [comment]
@jay1337 would you be able to share some sample code for this for me please?

**Comment by jbaxleyiii** [comment]
@jay1337 can you also try the newest rc (`rc.4`?)

**Comment by jay1337** [comment]
@jbaxleyiii Issue still there with `rc.4`

**Comment by jay1337** [comment]
@jbaxleyiii To reproduce I think you can do nearly the following.

```
// put data in the store
apolloClient.writeQuery({
  fragment: gql`
    query {
      user {
        id
        name
        friend {
          id
          name
        }
      }
    }
  `,
  data: {
    user {
      __typename: 'User',
      id: 1,
      name: 'bob',
      friend: {
        __typename: 'User',
        id: 2,
        name: 'john',
       },
    },
  },
});
// then load a component wrapped with a request containing this fragment
...
// update some of the data (name of user) but do not change some sub content (friend object)
apolloClient.writeQuery({
  fragment: gql`
    query {
      user {
        id
        name
        friend {
          id
          name
        }
      }
    }
  `,
  data: {
    user {
      __typename: 'User',
      id: 1,
      name: 'eva',
      friend: {
        __typename: 'User',
        id: 2,
        name: 'john',
       },
    },
  },
});
// then you will have a componentWillReceiveProps(nextProps) with nextProps.data.user.friend !== this.props.data.user.friend


```

**Comment by jbaxleyiii** [comment]
@jay1337 I'm confused, isn't that the desired behavior? Of the data changes you want to rerender?

**Comment by stubailo** [comment]
So Apollo Client only returns the same object reference if all of the fields on that object and all of its children are identical.

In this case, `data.user.friend` before the update is `{ id, name }`, and after the update is `{ id, name, age }`. The only way to maintain the same object reference would be to mutate the original result.

There might still be an issue here with a different set of queries and fields, but I don't think this particular example reproduces it.

**Comment by stubailo** [comment]
(Going to close the issue, let's reopen if we have a confirmed reproduction)

**Comment by jay1337** [comment]
@stubailo Your first sentence is true, and also Apollo MUST return the same object reference if all of the fields on that object and all of its children are identical. But this is not the case here. The watched query only asks for `id` and `name`, and since these 2 fields do not change, the "sub object" must be the same. 

To maintain the same object reference you don't need to mutate the original result saved in the store, just to reuse the previous result of the query read from the store when your read the store again. That's exactly what is correctly done by `InMemoryCache` here : https://github.com/apollographql/apollo-client/blob/2d54014c755818ab8d2961e04ec40d49a1ac2838/packages/apollo-cache-inmemory/src/readFromStore.ts#L268

The "broadcast watch" new data is well computed using previous result. But it's not this data that is passed to the wrapped React component The `lastResult` saved during the broadcast is not used by Apollo, instead the cache is read again without using a previous result, so it wastes CPU to recompute something already available and it does the new computation badly.

@jbaxleyiii I expect `this.props.data !== nextProps.data && this.props.data.user !== nextProps.data.user && this.props.data.user.friend === nextProps.data.user.friend` so that the wrapped component is updated but so that a child Pure Component using only `this.props.data.user.friend' will not be updated.

@stubailo You should reopen this issue...

**Comment by jay1337** [comment]
@stubailo @jbaxleyiii Don't you agree with my last comment ?
