### ISSUE TITLE
Avoid reduce for better perf

### ISSUE THREAD

**Issue by jay1337** [apollographql/apollo-client#2350]
Prefer `array.some()` or `array.every()` instead of `array.reduce()` in order to stop iterating as soon as you know that it's no more useful to iterate.

I've found  it here:

- https://github.com/apollographql/apollo-client/blob/6ba4b3bf06aad67b2edd5a5ce7c23defd1dfa185/packages/apollo-cache-inmemory/src/readFromStore.ts#L284
- https://github.com/apollographql/apollo-client/blob/6ba4b3bf06aad67b2edd5a5ce7c23defd1dfa185/packages/apollo-cache-inmemory/src/readFromStore.ts#L334

**Comment by jbaxleyiii** [comment]
@jay1337 would you be open to making these changes? I think it would be a great change!

**Comment by jay1337** [comment]
@jbaxleyiii You can merge this PR : https://github.com/apollographql/apollo-client/pull/2356
