### ISSUE TITLE
broadcastWatches called 2 times by InMemoryCache when an optimisticResponse is used

### ISSUE THREAD

**Issue by jay1337** [apollographql/apollo-client#2359]
When a mutation happens with an `optimisticResponse` provided, `InMemoryCache`'s function `broadcastWatches` is called 2 times after successfully receiving data from server:

1. When writing the data from the server: https://github.com/apollographql/apollo-client/blob/2cd695fda1085aa957dde1d632bf3b08738b5036/packages/apollo-client/src/core/QueryManager.ts#L201
2. When removing optimistic response from cache: https://github.com/apollographql/apollo-client/blob/2cd695fda1085aa957dde1d632bf3b08738b5036/packages/apollo-client/src/core/QueryManager.ts#L231

It costs CPU time...

**Version**
- apollo-client@2.0.0-rc.5

This issue has the same consequence than the following (which is solved) but it is different: https://github.com/apollographql/apollo-client/issues/2221

**Comment by jay1337** [comment]
Hey !

**Comment by jbaxleyiii** [comment]
@jay1337 sorry about that! I took a week off and missed keeping this issue going along. I'm going to remove stalebot too now that I have the bandwidth to better take care off issues.

**Comment by jay1337** [comment]
@jbaxleyiii Welcome back :)

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=broadcastWatches%20called%202%20times%20by%20InMemoryCache%20when%20an%20optimisticResponse%20is%20used&body=Migrated%20from:%20apollographql/apollo-client%232359) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by jay1337** [comment]
Same code run twice is not a feature request, it's a bug !

**Comment by hwillson** [comment]
@jay1337 This isn't a bug - it's by design. The design might be problematic, and might need to be re-visisted, but the functionality is definitely working as designed. That's why this issue was labelled with a `discussion` tag - the best way forward here hasn't been decided. That's why this issue needs to be moved into the FR repo. Thanks!

**Comment by hwillson** [comment]
> Apollo is designed to do things twice ?

In this case, yes! `markMutationResult` and `markMutationComplete` serve similar purposes, but they are slightly different. They line up with the [`zen-observable` API](https://github.com/zenparsing/zen-observable#api), where `markMutationResult` is called when the mutation's `apollo-link` Observable receives data via `next`, and `markMutationComplete` is called when the mutation's `apollo-link` Observable has fully completed. In a lot of applications when a mutation is run and the `markMutationResult` and `markMutationComplete` methods are called, the chances of there being any data differences in the cache between these calls is slim, so calling `broadcastWatches` twice seems like overkill. But the `markMutationResult` / `markMutationComplete` API was designed to make sure cache changes could be broadcast whenever the Observable received new data via `next`, would could happen multiple times in a row, then again when everything finished. It sounds like this might not be the best approach, and that some of this should be re-considered, but for now this is all working as designed.

**Comment by jay1337** [comment]
Ok, it's great you've taken the time to explain that. I better understand the current implementation.

But the issue still remains and, since `broadcastWatches` can be very time consuming in some cases (app with React components relying on a lot of data), the `broadcastWatches` of the last `next` event should really be mutualized with the `broadcastWatches` of the `complete` event.

The best solution I see would be to add a flag with the GraphQL result `ExecutionResult` of the `next` event to tag the last `next` event (and remove optimistic response from cache in this event).

For me it's still more a bug than a feature but I will migrate this issue to the new repository.
