### ISSUE TITLE
lastVariables behavior is incomplete

### ISSUE THREAD

**Issue by jamesreggio** [apollographql/apollo-client#2360]
The introduction of `lastVariables` caused a major referential equality regression.

By requiring `lastVariables` to equal the current `variables` in order to avoid recalculation of the current resultset ([here](https://github.com/apollographql/apollo-client/pull/2281/files#diff-55239150ee8aa0aab3b1143fd04e998bR176)), you're effectively forcing the regeneration of the resultset upon every read for components that never update their variables.

I'm not entirely sure what scenario you're attempting to accommodate with `lastVariables`, but I suspect that you need to write `this.lastVariables = this.variables` in more places than just when the variables have changed. (Perhaps they need to be stored upon construction, as well as when the observer receives results?)

**Version**
- apollo-client@2.0.0-rc.5

**Comment by jbaxleyiii** [comment]
@jamesreggio I'm going to see if I can get rid of `lastVariables` 👍

**Comment by jamesreggio** [comment]
Perfect. Would very much appreciate that.

**Comment by jbaxleyiii** [comment]
Removed on master!
