### ISSUE TITLE
optimisticResponse does not get overridden when result comes back form the server

### ISSUE THREAD

**Issue by mitjade** [apollographql/apollo-client#2368]
**Intended outcome:**
You submit an add mutation with `optimisticResponse` and then when you get the result from the server, it should get replaced with actual data.

**Actual outcome:**
When you get the result from the server, both `optimisticResponse` and result remain in cache.

**How to reproduce the issue:**
You can reproduce this in `apollographql/GitHunt-React` example by adding a comment.

**Version**
```
    "apollo-cache-inmemory": "^1.0.0",
    "apollo-client": "2.0.1",
    "apollo-link": "^1.0.0",
    "apollo-link-http": "^1.0.0",
    "apollo-link-ws": "^1.0.0",
```

**Comment by mitjade** [comment]
Still the case with the latest packages in `apollographql/GitHunt-React`. Made a PR there so this can be seen when inserting a new comment.

**Comment by mitjade** [comment]
Here is a video demonstrating this: https://youtu.be/ij10JZ1_uSY

**Comment by andy-mcdonald** [comment]
I was seeing the happen intermittently (within the same session) and thought it may be some sort of race condition, so I added a delay to the resolver and now the optimistic entry is failing to clear every time.

@mitjade - did you manage to resolve the issue?

**Comment by mitjade** [comment]
@andy-mcdonald No still facing this issue. The problem for me is, that I am doing `updateQueries` on the mutation and `updateQuery` on the `subscribeToMore`, similarly as it is done in `apollographql/GitHunt-React` example. If `updateQuery` is triggered before mutation `updateQueries`, this problem occurs, otherwise if `updateQueries` on the mutation gets called first all is ok.

I got no response on this here or on `apollographql/GitHunt-React` repo?

**Comment by andy-mcdonald** [comment]
@mitjade - So I'm using `update` on the mutation instead of ([the soon to be deprecated](https://www.apollographql.com/docs/react/features/cache-updates.html#updateQueries)) `updateQueries` but I'm seeing the exact same behavior as you described.

I'm surprised this hasn't had a response given how detailed your initial description was so thorough.

**Comment by mitjade** [comment]
@andy-mcdonald I tried `update` as well. Same result. I am using `updateQueries`, because I can reuse the `add` logic for both `updateQueries` and `updateQuery` in `subscribeToMore`, since they do not offer `update` functionality on subscriptions.

**Comment by psierks** [comment]
Seeing similair behavior. Doing a `mutate` with `optimisticResponse` and `update`. I'm using the query with a react-native `FlatList` which calls `fetchMore` via `onEndReached`, and it's called right after the first update which then returns the current result. Though I'm not (yet?) using subscriptions and this would only happen when the items in the list are few, still figured I'd chime in.

**Comment by psierks** [comment]
Putting this here in the event others find this as I did. I suppose in my somewhat different case, I can and probably should update the `onEndReached` function to check wether or not there's more data avail by adding `isLastItem` or `hasMore` etc to the data response and only call `fetchMore` if needed.

**Comment by hwillson** [comment]
This should no longer be a problem with modern versions of `react-apollo` (2.1.4) and `apollo-client` (2.3.2). Please post back if you're still seeing this happen. Thanks!
