### ISSUE TITLE
Is order of calling resolvers deterministic?

### ISSUE THREAD

**Issue by sheerun** [apollographql/apollo-client#2369]
If one doesn't use any promises as resolver implementations, is calling order of them guaranteed deterministic in apollo-client? (it's only obvious for mutations as that's what the spec says).

I need this functionality as I'd like the resolving process to build a promise that resolver all queries in order: i.e. in my case you could think of queries (even nested) as mutations/commands.

**Comment by sheerun** [comment]
Also relevant: is order of batched queries guaranteed sequential?

**Comment by sheerun** [comment]
@apollographql Could you please configure your bot so it doesn't close issues when it's you who didn't answer, not the creator of the issue?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Is%20order%20of%20calling%20resolvers%20deterministic%3F&body=Migrated%20from:%20apollographql/apollo-client%232369) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
