### ISSUE TITLE
How do I set up InstrospectionFragmentMatcher with Apollo 1.4 (React)?

### ISSUE THREAD

**Issue by tremby** [apollographql/apollo-client#2380]
My GraphQL endpoint has just had a UnionType added. Apollo gives an error during a query for one such field: 

> You are using the simple (heuristic) fragment matcher, but your queries contain union or interface types.
>
> Apollo Client will not be able to able to accurately map fragments.To make this error go away, use the IntrospectionFragmentMatcher as described in the docs: http://dev.apollodata.com/react/initialization.html#fragment-matcher

There are then a lot of "missing field" warnings.

I read the documentation linked to, but it appears to be for apollo-client 2 rather than 1, and so when it says "You’ll want to do this in the same file where you initialize the cache for Apollo Client" I say "what cache?"

My Apollo configuration before wanting to use the IntrospectionFragmentMatcher looked like this:

```js
import {ApolloClient, createNetworkInterface} from 'react-apollo';

const networkInterface = createNetworkInterface({
  uri: process.env.API_URL + '/graphql',
});

networkInterface.use([{
  applyMiddleware: (req, next) => {
    // ...
  },
}]);

const graphqlClient = new ApolloClient({
  dataIdFromObject: o => o.hashid,
  networkInterface: networkInterface,
});

export default graphqlClient;
```

After attempting to blunder through the instructions anyway (and installing `apollo-cache-inmemory`, which I did not already have) I end up with this:

```js
import {ApolloClient, createNetworkInterface} from 'react-apollo';
import Cache, {IntrospectionFragmentMatcher} from 'apollo-cache-inmemory';

const PARTIAL_SCHEMA = {
  __schema: {
    // ... (I'm hardcoding this for now)
  },
};

const networkInterface = createNetworkInterface({
  uri: process.env.API_URL + '/graphql',
});

networkInterface.use([{
  applyMiddleware: (req, next) => {
    // ...
  },
}]);

const fragmentMatcher = new IntrospectionFragmentMatcher({
  introspectionQueryResultData: PARTIAL_SCHEMA,
});

const cache = new Cache({fragmentMatcher});

const graphqlClient = new ApolloClient({
  cache: cache,
  dataIdFromObject: o => o.hashid,
  networkInterface: networkInterface,
});

export default graphqlClient;
```

Which gives me

> TypeError: _apolloCacheInmemory2.default is not a constructor

I looked at the [docs for apollo-cache-inmemory](https://www.npmjs.com/package/apollo-cache-inmemory) and it describes the setup procedure differently. After trying to shoehorn that into my configuration I have ended up with this:

```js
import {ApolloClient, createNetworkInterface} from 'react-apollo';
import {InMemoryCache, IntrospectionFragmentMatcher} from 'apollo-cache-inmemory';

const PARTIAL_SCHEMA = {
  __schema: {
    // ...
  },
};

const networkInterface = createNetworkInterface({
  uri: process.env.API_URL + '/graphql',
});

networkInterface.use([{
  applyMiddleware: (req, next) => {
    // ...
  },
}]);

const fragmentMatcher = new IntrospectionFragmentMatcher({
  introspectionQueryResultData: PARTIAL_SCHEMA,
});

const cache = new InMemoryCache({
  dataIdFromObject: o => o.hashid,
  fragmentMatcher: fragmentMatcher,
});

const graphqlClient = new ApolloClient({
  cache: cache,
  networkInterface: networkInterface,
});

export default graphqlClient;
```

This compiles and the site looks OK and queries run, but I'm back to exactly the same errors I started with.

How do I set this up?

Versions:

- apollo-client@1.4.0
- react-apollo@1.4.16

**Comment by tremby** [comment]
Alternatively, if upgrading to version 2 is easier, I could do that, if you can point me to a migration guide. (I have some precarious logic updating the cache manually so a major version change did not seem appealing.)

**Comment by peggyrayzis** [comment]
Hi @tremby! Apologies for the bad link, we were in the middle of upgrading our docs site.

[This page](https://www.apollographql.com/docs/react/recipes/fragment-matching.html) should tell you everything you need to know about setting up the fragment matcher for unions & interfaces. This guide is for 2.0, but it looks like your [upgrade to 2.0](https://www.apollographql.com/docs/react/2.0-migration.html#basic) should only be a couple lines of code.

Would you like to try adding a PR to switch out the link in the error message with the updated fragment matcher guide link? I can walk you through it if you need help! 😀

**Comment by tremby** [comment]
It sounds from your answer that it is not possible to use the introspection fragment matcher with 1.4.0, or at least no working documentation exists for it.

It wasn't clear I even could upgrade to version 2, using react-apollo, since its releases page on Github shows the latest as 1.4.x.

But I now see there is a 2.x on NPM, and so I upgraded.

Upgrading is *not* just a few lines, or at least was not for my project. Imports changed throughout the entire project, middleware had to be rewritten, and more. The thing which took longest was getting the new version of the middleware working. The upgrade guide shows only instructions which work for a synchronous middleware while mine needs to be asynchronous. I eventually found [this documentation](https://github.com/apollographql/apollo-link/blob/0f230046c8d81675befa5d27dee7888b0718a79e/packages/apollo-link-context/README.md#usage). This usage for an async middleware is totally different from the example in the upgrade guide, which made things confusing. But I got it working.

Please consider improving the upgrade guide documentation with an asynchronous middleware example.

> Would you like to try adding a PR to switch out the link in the error message with the updated fragment matcher guide link?

I don't have time, sorry. This upgrade already ate time I didn't have.

**Comment by peggyrayzis** [comment]
It is possible to use the fragment matcher with 1.4. The build step process is the same, but you specify the fragment matcher [on the constructor of Apollo Client](https://www.apollographql.com/docs/react/2.0-migration.html#full) instead of the cache like in 2.0.

Apollo Link is our new network stack that is responsible for processing data (middleware, afterware, etc) and retrieving data (HttpLink, WebSocketLink). You can find an example of async middleware (as well as many other examples) on the [Link docs](https://www.apollographql.com/docs/link/links/context.html#Usage).

I'm going to close this issue since your question has already been answered. If you have any other questions about middleware, please open them on the `apollo-link` repo. 😀

**Comment by tremby** [comment]
> It is possible to use the fragment matcher with 1.4. The build step process is the same, but you specify the fragment matcher on the constructor of Apollo Client instead of the cache like in 2.0.

I detailed what I tried and what happened with 1.4 above.

> Apollo Link is our new network stack that is responsible for processing data (middleware, afterware, etc) and retrieving data (HttpLink, WebSocketLink). You can find an example of async middleware (as well as many other examples) on the Link docs.

Yes, I already said above that I found documentation. I am pointing out that it was difficult to find and that the migration documentation is lacking. I'm not sure you're actually reading what I'm saying.

**Comment by dpaola2** [comment]
@tremby did you ever get fragment caching working? I'm having the same issues you've outlined here and don't have time to upgrade to 2.0.

**Comment by tremby** [comment]
As I said earlier in the thread, I had lots of problems trying with 1.4 and so I upgraded to version 2. So no, I did not get it working with 1.4.

**Comment by cknabe** [comment]
For 1.4 react-apollo:
1. You MUST pull IntrospectionFragmentMatcher from 'react-apollo' not from apollo-cache-inmemory
2. As stated above, you MUST pass the fragment matcher directly to ApolloClient. 

**DO NOT USE apollo-cache-inmemory AT ALL for react-apollo 1.4**


```
import { ApolloClient, IntrospectionFragmentMatcher } from 'react-apollo';

import introspectionQueryResultData from './fragmentTypes.json';

const fragmentMatcher = new IntrospectionFragmentMatcher({
  introspectionQueryResultData,
});

export default options => {
  return new ApolloClient(
      { fragmentMatcher },
    ),
  );
};
```

I lost a lot of time to this. 
Upgrading to 2/3 is not considered a priority, and thus there are no cycles to devote to it.
Posting here, as I stumbled upon this issue over and over while searching for help.
