### ISSUE TITLE
Unable to reuse Fragments

### ISSUE THREAD

**Issue by gijo-varghese** [apollographql/apollo-client#2390]
I have a query like this:
```
query customer($id: ID!) {
  user (id: $id) {
    id
    last_message {
      id
      message
    }
    messages {
      id
      message
    }
  }
}
```
Since `id` & `message` are used many times, I created a fragment for this:
```
fragment message on Message {
  id
  message
}
```

And final query as:
```
query customer($id: ID!) {
  user (id: $id) {
    id
    last_message {
      ...message
    }
    messages {
      ...message
    }
  }
}
```
But I'm getting an error:
` "Fragment "message" cannot be spread here as object…ype "LastMessage" can never be of type "Message"."`

What did I do wrong? I thought fragments are somethings that I can reuse! What does this '**on Message**' in fragment really mean? Because when I create another fragment with '**on LastMessage**' and use ...lastmessage it works

**Comment by jbaxleyiii** [comment]
@gijo-varghese can you run this same query using GraphiQL on your graphql app? That message appears to be a server error of type mismstach where `last_message` is returning a type of `LastMessage` but `messages` return a type of `Message`. If these two fields return different types, the fragment cannot be applied

**Comment by gijo-varghese** [comment]
Got it
