### ISSUE TITLE
Update README for 2.0

### ISSUE THREAD

**Issue by csillag** [apollographql/apollo-client#2392]
As of [now](https://github.com/apollographql/apollo-client/blob/402754ababba656ec89a5e6671e5c48d423e21b8/README.md), the README says:

> The master branch is the beta version of Apollo Client 2.0. To find the current @latest, take a look at the latest branch. For update information, check out the upgrade guide.
>
> The documentation site still reference the 1.0 API until we are out of beta for 2.0.

However, now we *are* out of beta for 2.0.

(2.0.1 has been released yesterday.)

So, as of now, the README on the master branch is documenting the 1.0 API, which is now considered obsolete...

**Comment by jbaxleyiii** [comment]
@csillag I kept the PR so I could merge it on stage at GraphQLSummit, this is all fixed now 🎉
