### ISSUE TITLE
ApolloQueryResult type definition mistake ?

### ISSUE THREAD

**Issue by kamek-pf** [apollographql/apollo-client#2399]
Hey !

So, the `ApolloQueryResult` is defined as :
```typescript
export declare type ApolloQueryResult<T> = {
    data: T;
    loading: boolean;
    networkStatus: NetworkStatus;
    stale: boolean;
};
```

I'm using react-apollo, and I see that the `loading`, `networkStatus`, and `stale` flags are actually under `data`, not on the same level, so `data.loading` is actually undefined.

Looking at [the docs](http://dev.apollodata.com/react/queries.html) and a [Medium post](https://dev-blog.apollodata.com/simplify-your-react-components-with-apollo-and-recompose-8b9e302dea51) from @stubailo, it seems correct to access these properties from `data`.

Is this a mistake, or am I missing something ?
Maybe I'm not supposed to use this interface ?

**Comment by jbaxleyiii** [comment]
@kamek-pf react-apollo attaches the `ApolloQueryResult` to `props.data` by default, but it takes the resulting data and includes it alongside things like `loading` and `networkStatus` that way you don't have to access your data at `props.data.data.myField`
