### ISSUE TITLE
Clean up old docs site

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-client#2402]
Current AC 2.0 docs are at https://www.apollographql.com/docs/ and AC 1.0 at http://dev.apollodata.com/core/.  Neither of these sites clearly states which version they are for (though they do each have "upgrading to X.0 articles".

We should take down the old docs, redirect to the new site, and add a single article on the new site that documents using the 1.0 API for folks still on it (perhaps with a link to an old directory on GitHub with the Markdown for more details).

**Comment by glasser** [comment]
Somebody set up https://s3.amazonaws.com/apollo-docs-1.x/index.html which is awesome!

**Comment by jbaxleyiii** [comment]
@glasser @stubailo thoughts on what we should do with the 1.0 docs? Should we link to ^^ or set it up ourselves? Where should we show that?

**Comment by EclipticWld** [comment]
I had experience when I need references to Apollo 1.0 docs but I didn't find it so I was forced to move to 2.0 to be able to use API properly :)

**Comment by stubailo** [comment]
Hehehehe. Anyway, old docs are gone now, so this can be closed!
