### ISSUE TITLE
ApolloClient from 'apollo-client-preset' expects an ApolloClientOptions parameter

### ISSUE THREAD

**Issue by darkbasic** [apollographql/apollo-client#2403]
**Intended outcome:**
```
import ApolloClient from 'apollo-client-preset';

const client = new ApolloClient();
```

I expect the tooling (Webstorm's editor) to not complain about missing parameters.

**Actual outcome:**
`Supplied parameters do not match any signature of call target`.

**How to reproduce the issue:**
`npm install apollo-client graphql-tag apollo-client-preset`
```
import ApolloClient from 'apollo-client-preset';

const client = new ApolloClient();
```

**Version**
- apollo-client@2.0.1

**Comment by darkbasic** [comment]
I know this is probably because of apollo-client-preset expects apollo-client@^1.0.0, but I expect it to stay in sync with apollo-client and there is also no warning about wrong peer dependencies in npm.

**Comment by jbaxleyiii** [comment]
@darkbasic it looks like the documentation (readme) is out of date for this package. Just a heads up that it is a new package so it will be behind Apollo Client my a major version

**Comment by hwillson** [comment]
This is no longer an issue (the docs were updated). Thanks!
