### ISSUE TITLE
Multiple 2.0 upgrade guides

### ISSUE THREAD

**Issue by tsnieman** [apollographql/apollo-client#2406]
**Intended outcome:**
There should probably only be a singular 1.x -> 2.0 upgrade guide.

**Actual outcome:**
There are two, and they are both different.
https://github.com/apollographql/apollo-client/blob/master/docs/source/2.0-migration.md
https://github.com/apollographql/apollo-client/blob/master/Upgrade.md

One mentions removal of things like `reduxRootSelector`, the other doesn't. There are more differences than that too.

**How to reproduce the issue:**
Click the links above.

**Version**
- apollo-client@2

**Comment by jbaxleyiii** [comment]
The Upgrade.md file has been removed in favor of the docs site! Thanks!
