### ISSUE TITLE
False claim: "InMemoryCache is a normalized data store that supports all of Apollo Client 1.0's features without the dependency on Redux."

### ISSUE THREAD

**Issue by tsnieman** [apollographql/apollo-client#2407]
**Intended outcome:**
While I was trying to upgrade to 2.0, I noticed that `reduxRootSelector` functionality was entirely removed, so I went hunting for the replacement since `InMemoryCache` claims `"InMemoryCache is a normalized data store that supports all of Apollo Client 1.0's features without the dependency on Redux."`

**Actual outcome:**
There is no replacement for the `reduxRootSelector` functionality directly and the documentation claims that ALL of 1.0's features were covered.

Doc links claiming this:

1. https://github.com/apollographql/apollo-client/blob/e261f052d4c432479f5cd02a7bde006449efae5f/docs/source/basics/caching.md#L9

2. https://github.com/apollographql/apollo-client/blob/2cd695fda1085aa957dde1d632bf3b08738b5036/packages/apollo-cache-inmemory/README.md#L6

**How to reproduce the issue:**
Look at the documentation; confirm that the claim is untrue.

**Version**
- apollo-client@2

:warning:  **SPECIAL NOTE**
Since `.readQuery` is effectively broken (https://github.com/apollographql/apollo-client/issues/2051), this effectively breaks Redux + Apollo integrating together.

**Comment by jbaxleyiii** [comment]
@tsnieman I disagree considering `reduxRootSelector` was a function of the redux integration with Apollo Client 1.0. I don't think it is misleading in this manner.

I'm happy to accept a PR on the migration guide if you want to make this more explicit

**Comment by ianrtracey** [comment]
This should definitely be more explicit. It took my team and I awhile to find out that it was unsupported and while the docs mention "reduxRootSelector has been removed" it doesn't point the reader to a place where they can go to start looking for how to upgrade despite it being removed.
