### ISSUE TITLE
Repo links to the old docs

### ISSUE THREAD

**Issue by dcposch** [apollographql/apollo-client#2408]
![image](https://user-images.githubusercontent.com/169280/32074446-4759f5a4-ba4e-11e7-97b2-880804ca3e2d.png)

**Intended outcome:**
I visited https://github.com/apollographql/apollo-client looking for the docs.

I clicked the link right at the top and it took me to the wrong docs--the old 1.0 docs.

The repo is at 2.0, so the link should point to the new docs: 

https://www.apollographql.com/docs/

**Version**
- apollo-client@2.0

**Comment by dcposch** [comment]
FYI googling "apollo 2 docs" takes you directly to the old, wrong docs :(

**Comment by jbaxleyiii** [comment]
@dcposch we are still working on all of the redirects being in place! Thanks for the heads up!
