### ISSUE TITLE
`NetworkStatus.loading` available globally on `ApolloClient`?

### ISSUE THREAD

**Issue by KeithGillette** [apollographql/apollo-client#2413]
Is there any way to determine whether `NetworkStatus.loading` is true for any currently executing `ApolloClient` operation?

I'd like to create an application-wide network activity indicator component in an Apollo-Angular project without having each Apollo client `.query`/`.watchQuery`/`.mutate` call report its `NetworkStatus.loading`. I thought of using middleware/afterware hooks in `ApolloClientConfig.networkInterface`, but since the Apollo client is configured in the `AppModule` decorator, it's not easy to construct a hook that would report Apollo network activity in a way that would be available to an Angular component via an injected service.

**Comment by jbaxleyiii** [comment]
@KeithGillette you can do this with the 2.0 and writing a custom link. I think it would be a great link for others to use as well!

If anyone is interested in writing this, I'm happy to give guidance

**Comment by KeithGillette** [comment]
Thanks for the fast & helpful response, @jbaxleyiii! That's great news.

As soon as [`apollo-angular@1.0`](https://github.com/apollographql/apollo-angular/pull/377) is released to support `apollo-client@2.0`, I'll [migrate](https://github.com/apollographql/apollo-angular/blob/1.0/Migration.md) our project to both and attempt to use `apollo-link` to create an application-wide network activity indicator. Any guidance you can provide on creating that a custom link to do so would be greatly appreciated. (Some of the links on the [`apollo-link` documentation](https://github.com/apollographql/apollo-link/blob/master/docs/source/index.md) are broken, so I didn't get very far in understanding what would be involved.)

**Comment by kamilkisiela** [comment]
@KeithGillette You can already use [`apollo-angular@1.0.0-beta.1`](https://unpkg.com/apollo-angular@1.0.0-beta.1/). I know it's beta but there should be no changes. It all works fine, pretty much all the issues are now fixed.

In the PR you mentioned, there are 3 examples (simple one on StackBlitz two other on github - SSR and NativeScript) which I'm keeping up to date with releasing process.

**Comment by KeithGillette** [comment]
Thanks for the helpful reply, @kamilkisiela. So if I use `apollo-angular-link-http`, it seems to me that for my use case, the problem reduces to determining whether Angular's HTTP service is active, which would cover Apollo as well as other Angular application HTTP network activity. In that case, I wouldn't need to write a custom `apollo-link` and could use [existing package](https://github.com/mpalourdio/ng-http-loader) that already does that.

Now to figure out the new Apollo-Angular query/mutation typings…

**Comment by kamilkisiela** [comment]
@KeithGillette that's great! Thanks to using `HttpClient` we gain so many things like NativeScript support, SSR, features like that one you mentioned! If you have any questions feel free to message me on slack (same user handle)

**Comment by KeithGillette** [comment]
Thanks so much! With the help of the `apollo-client` and `angular-apollo` migration guides, the `howtographql/angular-apollo` example, and @kamilkisiela's expert guidance, I got our project upgraded to ApolloClient 2.0.1 + Angular-Apollo 1.0.0 with `apollo-angular-link-http`. I successfully tested a third-party Angular network activity/loading component that intercepts Angular `HttpClient` used by `apollo-angular-link-http`, so for now I'll leave my custom link writing to the  one I needed for Meteor authentication with `apollo-angular-link-http`:
```
const meteorAuthenticationMiddleWareLink = new ApolloLink((operation: Operation, forward: NextLink): Observable<FetchResult> => {
	const meteorAuthenticationToken = Accounts._storedLoginToken();
	if (meteorAuthenticationToken) {
		const headers = new HttpHeaders({'meteor-login-token': Accounts._storedLoginToken()});
		operation.setContext({headers});
	}
	return forward(operation);
});
```
