### ISSUE TITLE
/n instead of \n in enhancedError

### ISSUE THREAD

**Issue by gforge** [apollographql/apollo-client#2414]
Thank you for this awesome software! Your error was actually helpful, although I think I found a typo, `/n` should probably be `\n` in `enhancedError`:

https://github.com/apollographql/apollo-client/blob/2cd695fda1085aa957dde1d632bf3b08738b5036/packages/apollo-cache-inmemory/src/writeToStore.ts#L47

**Comment by jbaxleyiii** [comment]
@gforge ah for sure! would you open a PR to change that?

**Comment by gforge** [comment]
Ok, will try to fix tomorrow

**Comment by jbaxleyiii** [comment]
Thanks! This is fixed now!
