### ISSUE TITLE
writeFragment requires explicit type in the `id` param? 

### ISSUE THREAD

**Issue by dotansimha** [apollographql/apollo-client#2417]
I am using `writeFragment`, and trying to update a specific object, for example `User`, with a specific id. The code examples in the docs is as follow:

```
const todo = client.readFragment({
  id: '5',
  fragment: gql`
    fragment myTodo on Todo {
      id
      text
      completed
    }
  `,
});
```

But with latest versions of Apollo, this example above won't work, because is requires to specify the type of the fragment we want to update. So we need to add `Todo:` in the `id`:

```
const todo = client.writeFragment({
  id: 'Todo:5',
  fragment: gql`
    fragment myTodo on Todo {
      id
      text
      completed
    }
  `,
   data: { ... },
});
```

It seems like the API expects the data id to be the cache key. 

I did some debugging and it seems like in the end, the following code:
https://github.com/apollographql/apollo-client/blob/master/packages/apollo-cache-inmemory/src/writeToStore.ts#L437
is trying to access `store['5']` instead of `store['Todo:5']`.

**Intended outcome:**

API should expect only the id, and not the cache key. 

**Actual outcome:**

Data does not change, and it works only after adding the `Type:` to the `id`.

**How to reproduce the issue:**

Reproduction available here: https://github.com/dotansimha/apollo-client-unhandled-expection , under the `write-fragment` directory. 
See the comment in line 131.

**Version**
```
    "apollo-cache": "^1.0.0",
    "apollo-cache-inmemory": "^1.0.0",
    "apollo-client": "^2.0.1",
    "apollo-link": "^1.0.0",
    "apollo-link-http": "^1.0.0",
    "graphql-anywhere": "^4.0.0",
    "graphql-tag": "^2.5.0",
    "react-apollo": "^2.0.0",
```

**Comment by jbaxleyiii** [comment]
@dotansimha I believe this is how the last version worked as well for fragments? I do think we could potentially try to calculate the id but I don't think we could do it very reliably.

Are you saying this worked on the 1.0 but does not on the 2.0?

**Comment by dotansimha** [comment]
Actually I didn't use it in 1.0, that's why I didn't mention the 1.0/2.0 releases for this issue...

Why calculating the type could make an issue with reliability? The type is always the type of the fragment, isn't it? 

And I think that if it's problem to calculate it, then we need to update the docs

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=writeFragment%20requires%20explicit%20type%20in%20the%20%60id%60%20param%3F%20&body=Migrated%20from:%20apollographql/apollo-client%232417) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by reduxdj** [comment]
I agree with the comments, please update the docs.
