### ISSUE TITLE
New Feature - two urls or option to switch between URLs (React-Apollo/Apollo-Client) 

### ISSUE THREAD

**Issue by atalebagha** [apollographql/apollo-client#2418]
How can I have two URLs or change URLs based on application state with Apollo Client?  Or would I have to use two separate clients ?  How would that work with React-Apollo ?

What I want to do is I want to have a method to change the URL from a production server to a staging/QA server for testing. I want to avoid making separate builds for QA and Production (backend)

If the feature is not available, I would like to suggest this feature to be added.

Thanks

**Comment by jbaxleyiii** [comment]
@atalebagha though it is not currently possible, a small PR to [apollo-link-http](https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-http/src/httpLink.ts#L114-L118) could allow you to set the `uri` based on the context of the request. With that change, you could do something like this:

```js
graphql(QUERY, {
  options: ({ uri }) => ({
    context: { uri  }
  })
)
```

**Comment by bishalshr** [comment]
@jbaxleyiii 
`graphql(QUERY, {
  options: ({ uri }) => ({
    context: { uri  }
  })
)`
This isn't working anymore after I upgraded react-apollo to v2.1.0

**Comment by n1ru4l** [comment]
@bishalshr For the meantime you could use https://www.apollographql.com/docs/link/composition.html#directional as a workaround

**Comment by bishalshr** [comment]
@n1ru4l So from now it won't work?

**Comment by n1ru4l** [comment]
I dont know. I never used that feature, but I solved the same problem by composing links. So maybe this could be a possible workaround for you. In the meantime you could help out by creating a failing test case for this (either in the codebase or on https://codesandbox.io/).

**Comment by bishalshr** [comment]
it gets fixed when I add {context: props.context} to  Query.prototype.extractOptsFromProps function in Query.js.

`Query.prototype.extractOptsFromProps = function (props) {
        var variables = props.variables, pollInterval = props.pollInterval, fetchPolicy = props.fetchPolicy, errorPolicy = props.errorPolicy, notifyOnNetworkStatusChange = props.notifyOnNetworkStatusChange, query = props.query, _a = props.displayName, displayName = _a === void 0 ? 'Query' : _a;
        this.operation = parser_1.parser(query);
        invariant(this.operation.type === parser_1.DocumentType.Query, "The <Query /> component requires a graphql query, but got a " + (this.operation.type === parser_1.DocumentType.Mutation ? 'mutation' : 'subscription') + ".");
        return {
            variables: variables,
            pollInterval: pollInterval,
            query: query,
            fetchPolicy: fetchPolicy,
            context: props.context,
            errorPolicy: errorPolicy,
            notifyOnNetworkStatusChange: notifyOnNetworkStatusChange,
            metadata: { reactComponent: { displayName: displayName } },
        };
    };`

**Comment by n1ru4l** [comment]
I am not sure if this is intended behaviour because one should handle this kind of stuff on the link layer. However it makes sense for me to allow the Query Component to pass in the context for analytics data etc.

@bishalshr It would be awesome if you could send a PR (with a Test to avoid regressions) for this feature.

**Comment by raeesaa** [comment]
Any updates on this? Setting `options.context` is no longer working for me as well after upgrading to `react-apollo 2.1.0`.

**Comment by james-ff** [comment]
https://github.com/apollographql/apollo-link/issues/305

**Comment by amadeu01** [comment]
Is it possible to get the local state from middleware and then change the URI of the `http-link`?

```
import { ApolloLink } from "apollo-link";
import { createHttpLink } from "apollo-link-http";

const httpLink = createHttpLink({ uri: "/graphql" });
const middlewareLink = new ApolloLink((operation, forward) => {
  operation.setContext({
    uri: { localStorage.uri }
  });
  return forward(operation);
});

// use with apollo-client
const link = middlewareLink.concat(httpLink);

```
