### ISSUE TITLE
[Cache API] Allow addtional type parameter to Apollo Cache to specify

### ISSUE THREAD

**Issue by yuit** [apollographql/apollo-client#2422]
Currently `ApolloCache` restore signature is `restore(serializedState: TSerialized): ApolloCache<TSerialized>` In the case of InMemoryCache, this works great as the `data` is already [serializable](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-cache-inmemory/src/inMemoryCache.ts#L38).

However, for other cache implementation such as Hermes. the `data` is not necessary ready to be serialized (e.g it can contains circular references etc.) Our `extract` method will do the serialization process and return something that is serializable. 

I would like to propose an additional to type parameter of `ApolloCache` abstract class : one is the cache type, another is the type of serialized cache (which is by default the cache type). Another alternative is to make `extract` and `restore` a generic method.

Here is the proposed change look like (https://github.com/apollographql/apollo-client/pull/2421)

cc @nevir  @jbaxleyiii

**Comment by jbaxleyiii** [comment]
I think better type defs would work great here!

**Comment by yuit** [comment]
Let me know what you think about the PR... .still more test to do but any feedbacks are welcome!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=%5BCache%20API%5D%20Allow%20addtional%20type%20parameter%20to%20Apollo%20Cache%20to%20specify&body=Migrated%20from:%20apollographql/apollo-client%232422) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
