### ISSUE TITLE
Feature request: partial data

### ISSUE THREAD

**Issue by rafales** [apollographql/apollo-client#2425]
Sometimes it's useful to display partially loaded data (from cache) while waiting for the server to respond.

## Previous solution

As far as I know there was a solution for this up until 1.0 version - `returnPartialData`. It was removed in PR #1370 for good reasons - it was impossible to control and some data could be missing that child components or other code did not expect to be missing.

## Current workaround

Currently it's possible to work around this problem to some extent - by using two queries, one with `"cache-only"` policy: https://gist.github.com/rafales/8112efdb5228065fce56266ad6c66386

It's problematic when you want to make more fields optional, as it requires more queries (let's say - in the above example - that we want to also display avatar field but it's not guaranteed that it's always in the cache - we'd have to add another query).

## Proposed solution

A good alternative to `returnPartialData` would be something you could control. My proposal is to add `@optional` directive, which would tell a query that component knows how to display itself if that field is missing.

Here's the previous example, with added avatar field, refactored to use `@optional`:

```javascript
function UserPage({ user, loading }) {
  // ...
}


const QUERY = gql`
    query getUserPage($userId: ID!) {
        accountById(id: $userId) {
            id
            name
            avatar @optional
            postFeed @optional {
                nextCursor
                posts {
                    id
                    resources {
                        width
                        src
                    }
                }
            }
        }
    }
`;

export default compose(
    graphql(QUERY, {
        props({ data: { loading, accountById: user } }) {
            return { loading, user };
        },
        options: ({ id }) => ({
            variables: { userId: id },
            fetchPolicy: 'cache-and-network',
        }),
    })
)(UserPage);
```

`@optional` directive would affect different fetching policies:

- `cache-only` - component will be rendered even if the optional data is missing from the cache
- `cache-and-network` - component will be rendered if the optional data is missing, but it will also make request to the network to fetch missing data
- `cache-first` - component will be rendered from cache if optional data is missing, but if something is missing - it will still hit the network to fetch everything

I did not look much into error handling but this solution makes it possible to render components with missing optional data if an error occurred.

**Comment by jbaxleyiii** [comment]
@rafales this is a really interesting idea! Another way it can be done today is to use `readQuery` or `readFragment` within a component to find the first set of data while the full query is fetched from the server. I think that pattern would also work well and is worth documenting.

Would you be up for trying that out? I think they should be able to use the same query, one would return partial data while the other would make the network request

**Comment by joelgriffith** [comment]
I'm curious if there's a way to opt-out of apollo's behavior where no data is returned when the server responds with errors. Most GraphQL servers don't prescribe how to handle mixed results, and I see the reasoning why you would want to error entirely by default, but there's cases where there's enough data in the response that consumers could theoretically recover.

I'm definitely open to other approaches or thoughts on this as I'm facing this right now in both apollo 1 and 2, and would prefer not doing two queries as one of the core values of graphql is issuing only one.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Feature%20request%3A%20partial%20data&body=Migrated%20from:%20apollographql/apollo-client%232425) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
