### ISSUE TITLE
Multiple docs with different version docs 

### ISSUE THREAD

**Issue by kavink** [apollographql/apollo-client#2431]
Looks like there are 2 document sites, which 

http://dev.apollodata.com/react/. <- This one seems to be for 1.X docs.

https://www.apollographql.com/docs/react/. <- This one is for 2.X docs.

Based on link on sidebar , "migrating to 1.0" and "migrating from 1.0"

Which one is the latest doc and official ?

**Comment by shtse8** [comment]
i have the same problem. i want to migrate apollo client from 1.0. but the official document is hard to be found. how can i modify the header before send ing the request in the latest version?

**Comment by jbaxleyiii** [comment]
Hey @kavink! The new docs is the second link, we are working to redirect the old sites
