### ISSUE TITLE
docs Calling mutations in 2.0 use gql from react-apollo from v1.0

### ISSUE THREAD

**Issue by kavink** [apollographql/apollo-client#2432]
This doc still seems to refer to 1.0 version, instead of 2.0 docs example.

https://github.com/apollographql/apollo-client/blob/master/docs/source/basics/mutations.md#calling-mutations

**Comment by jbaxleyiii** [comment]
Good catch! Would you be able to PR that change?

**Comment by lukecwilliams** [comment]
FYI - I've searched all files under `documents` and submitted pull requests for the erroneous gql imports.
