### ISSUE TITLE
default docs example for 2.0 is not working

### ISSUE THREAD

**Issue by sneerin** [apollographql/apollo-client#2434]
I copy pasted this code: 

```
import { ApolloClient, HttpLink } from 'apollo-client-preset';

const client = new ApolloClient({
  link: new HttpLink({
    uri: 'https://graphql.example.com',
  }),
});
```

and this is not working: 
Error: 
        In order to initialize Apollo Client, you must specify link & cache properties on the config object.
        This is part of the required upgrade when migrating from Apollo Client 1.0 to Apollo Client 2.0.
        For more information, please visit:
          https://apollographql.com/docs/react/setup
        to help you get started.

**Comment by sneerin** [comment]
Link is broken btw, just adding cache doesn't help at all.

**Comment by shahzeb1** [comment]
Try seeing of you find the docs here helpful: https://www.apollographql.com/docs/react/basics/setup.html

**Comment by joshuataylor** [comment]
Docs should link there ^.

**Comment by peggyrayzis** [comment]
Hi @sneerin! Would you like to try creating a pull request to fix the broken link in the error message? If you need help, I can walk you through it. 😀

**Comment by jbaxleyiii** [comment]
@sneerin @peggyrayzis that example is also missing using an apollo cache! Which is why it showed the error message. This is a great first PR if anyone wants it!

**Comment by misoguy** [comment]
I'd like to try creating a PR if no one is on it yet :)

**Comment by HamidReazaNikoonia** [comment]
hi  i am new in apollo ,

i have also this issue 

my code is same as this example 
https://www.apollographql.com/docs/react/basics/setup.html

first import 
      import { ApolloClient } from 'apollo-client';
      import { ApolloProvider } from 'react-apollo';
      import gql from 'graphql-tag';

create client
     const client = new ApolloClient({
           uri: `https://w5xlvm3vzz.lp.gql.zone/graphql`
      });

and at the end return

     return (
             <ApolloProvider client={client}>
                 <RootStack/>
             </ApolloProvider>
        );

**Comment by jordanmauricio** [comment]
@HamidReazaNikoonia It appears you're importing the ApolloClient as a named export, but you should be importing it directly. This means just removing the curly brackets ( { } ) around your ApolloClient import.
More information on named vs default imports here: https://stackoverflow.com/questions/36795819/when-should-i-use-curly-braces-for-es6-import/36796281

**Comment by wzup** [comment]
My five cents 
Same here. Package doesn't work as docs write

https://github.com/apollographql/apollo-client/issues/3639
