### ISSUE TITLE
Fragment on Query not working

### ISSUE THREAD

**Issue by veekungx** [apollographql/apollo-client#2438]
**Intended outcome:**
I want to get data from query on fragment like this

```
const query = gql`
query {
   ...myself
}
fragment myself on Query{
   me {
      id
   }
}
`

const TestComponent = graphql(query)(TestComponent);

```

expected
```
{
   data : {
      me : {
         id: "1234"
      }
   }
}
```
**Actual outcome:**
Don't get any result loaded to React Component. It looks like it doesn't make graphql request from Chrome Debugger network tab too.

**How to reproduce the issue:**

**Version**
- apollo-client@2.0.1
- graphql-tag@2.5.0
- react-apollo@2.0.0

**Comment by jbaxleyiii** [comment]
@veekungx that's no good to hear! Would you be able to reproduce using our [error template](https://github.com/apollographql/react-apollo-error-template)?

Thanks!

**Comment by esseswann** [comment]
I kind reproducing this bug right now but if you add some requests to query which are not fragment it works

**Comment by vnenkpet** [comment]
Was this resolved?? I have the exact same problem...
