### ISSUE TITLE
Apollo client 2.0 redux React-Native

### ISSUE THREAD

**Issue by ramirobg94** [apollographql/apollo-client#2444]
**Intended outcome:**

**Actual outcome:**

**How to reproduce the issue:**

**Version**
- apollo-client@2.0
I am working in a mobile App with react-native, Redux and Apollo-client and when I updated the dependencies the App is absolutly broken..

I read that:

"Ultimately we think the move off Redux will open the door for more powerful cache implementations and further performance gains. If you were using the Redux integration for other uses, please reach out or open an issue so we can help find a solution with the 2.0!

If you were using Redux for other purposes in your app with an older version of Apollo, you may have been relying on the fact that the <ApolloProvider store=store> component did double duty as a react-redux <Provider>. In react-apollo 2.0, <ApolloProvider> no longer has <Provider> semantics; you’ll have to use <Provider> yourself."

could you find a solution?

I use redux because there are parts that are not in GraphQl like navigation state, authetication ...

**Comment by lancygoyal** [comment]
I also have similar situation do i downgrade to 1.0 or is there is any way to use redux and apollo client together?

**Comment by nenti** [comment]
``` js
import { Provider } from 'react-redux'
return (<ApolloProvider client={apolloClient}>
      <Provider store={store}>
        <AppNavigator />
      </Provider>
    </ApolloProvider>)
```

**Comment by xcv58** [comment]
I also have the similar issue.

My app needs some global states shared by multiple components. I can treat Apollo client itself as a key in my Redux store previously. I have no idea how to do the similar trick in 2.0.

**Comment by nenti** [comment]
Can you give an example for how you used the apollo state in your components? Because normally you don't access apollo state directly but through binding a query to it. This is still possible.

**Comment by xcv58** [comment]
Thanks @nenti 

We used to query all data of one type and it needs to be accessible across different components, i.e. autocomplete component, search component, select target component. It's fine because this data wouldn't change often (at most once per day) and relatively small (less than 2kb).

So previously we can directly access the data in all components by `connect`, `mapStateToProps` of `react-redux`.

I can wrap all component needs this data with `graphql` HOC. But it will fetch the server for every component. It seems no way to use cache to avoid extra network request because it queries all data for this type. Please correct me if my understanding is wrong. Thanks!

**Comment by nenti** [comment]
I had the same issue. But don't pattern of saving the data into a separate redux store. You can add cacheResolvers in your InMemoryCache like the following:
``` js
import { toIdValue } from 'apollo-utilities'
const client = new ApolloClient({
  link: httpLink,
  cache: new InMemoryCache({
    cacheResolvers: {
      Query: {
        product: (_, args) => toIdValue(args.id),
      },
    },
  }),
})
```

And that's it. Now you access cache directly. It's ofc also possible to configure your query to request cache only to optimise network traffic.

**Comment by xcv58** [comment]
@nenti I understand that your cacheResolvers would resolve a product from cache. But could you confirm that it would also cache for products query without args.

In other words, if I need to query a query like this:
```
const productsQuery = gql`
{ products { id name type } }
`
```

Is this possible by using any apollo utilities helpers? Thank you so much!

**Comment by nenti** [comment]
Where does the data come from? If you request once it is automatically cached, even without cacheResolvers. So you would just integrate the HOC where you need the data and if it is a cachehit you will get the data immediately.

**Comment by xcv58** [comment]
Let me double check and get back to you.

**Comment by xcv58** [comment]
I have codes like this:

### Apollo client
```
import { ApolloClient } from 'apollo-client'
import { HttpLink } from 'apollo-link-http'
import { InMemoryCache } from 'apollo-cache-inmemory'

const link = new HttpLink({
  uri: 'https://api.graph.cool/simple/v1/ciyz901en4j590185wkmexyex',
  fetchOptions: {
    credentials: 'include'
  }
})

const cache = new InMemoryCache()

const apolloClient = new ApolloClient({
  link, cache
})

export default apolloClient
```

### Components
```
import { graphql } from 'react-apollo'
import gql from 'graphql-tag'

const query = gql`{ allPosts { title id } }`

class Test extends Component {
  render () {
    console.log(this.props)
    return (
      <div>123</div>
    )
  }
}

const GraphQLTest = graphql(query)(Test)
// render in a parent component
...
              <GraphQLTest />
              <GraphQLTest />
...
```

But there are still two fetch connections:

![image](https://user-images.githubusercontent.com/503123/32416331-77ca41ca-c1fc-11e7-820f-0a7e131542c8.png)

**Comment by nenti** [comment]
Hmmm. Can you check your fetchPolicy please: https://www.apollographql.com/docs/react/basics/queries.html#graphql-config-options-fetchPolicy

Try setting cache-only on your 2nd request:
``` js
{
  options: { fetchPolicy: 'cache-only' },
}
```

See if there is still a 2nd fetch. I suppose you see this behavior in your test setup because the first query has no result yet when the 2nd is started so there is no cache hit. To cover this usecase you need to enable deduplication: https://www.apollographql.com/docs/react/basics/network-layer.html#query-deduplication.

**Comment by xcv58** [comment]
I move the second `<GraphQLTest />` to another lazy load component and get no 2nd request. It works without configuring `fetchPolicy` or `queryDeduplication`

But sometimes I have to render something at the same level:
```
return (
  <App>
    <Search />
    <ProductList />
  </App>
)
```

Both `Search` and `ProjectList` needs the products query.

I did try use `queryDeduplication: true|flase` and `fetchPolicy: 'cache-only'`. It does have 2nd request regardless how I config those two options.

I can fix this by:
1. Attach the query to `App`,
2. Refactor `Search` to a lazy load Component, i.e. click to render a low-level Component which has real GraqhQL attached

But all above solutions have their weakness. Do you have any suggestions?

**Comment by nenti** [comment]
No sorry. Regarding to the docs queryDeduplication works by default. Should open another bug ticket after searching for others having this problem.

**Comment by xcv58** [comment]
Thank you very much @nenti

**Comment by lancygoyal** [comment]
Folks, i am using redux persist package to save store data in react native AsyncStorage. Hows i do this now? Any idea?

**Comment by hwillson** [comment]
As mentioned in the [docs](https://www.apollographql.com/docs/react/recipes/2.0-migration.html#redux), Apollo Client 2.x has moved away from Redux for various reasons. You can still use Redux, but you'll have to take care of wiring it in yourself (e.g. using your own `<Provider />`). An example of this can be found in https://github.com/apollographql/apollo-client/issues/2444#issuecomment-341784573. There aren't currently any future Redux related Apollo Client changes planned, so closing for now. Thanks!
