### ISSUE TITLE
graphql and/or gql functions broken in React Native

### ISSUE THREAD

**Issue by bdombro** [apollographql/apollo-client#2457]
Am getting this error _reactApollo.gql is not a function.

![image](https://user-images.githubusercontent.com/3165897/32316105-2deeb780-bf85-11e7-9477-9fddb041f849.png)

**Intended outcome:**
Try apollo with react native.

**Actual outcome:**
Example not working.

**How to reproduce the issue:**
Add imports and this snippet to app.js. [Here](https://gist.github.com/bdombro/d3e62e4d8e7ef0898c099acdda966408) is the entire app.js

app.js
```javascript
const FeedWithData = graphql(gql`
  {
    feed (type: TOP, limit: 5) {
      repository {
        owner { login }
        name
      }
  
      postedBy { login }
    }
  }
`)
```

package.json
```json
{
  "name": "AwesomeProject",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "1.6.0",
    "jest-expo": "^22.0.0",
    "react-test-renderer": "16.0.0-beta.5"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "apollo-client": "^2.0.1",
    "expo": "^22.0.0",
    "graphql": "^0.11.7",
    "react": "^16.0.0",
    "react-apollo": "^2.0.0",
    "react-native": "^0.49.5"
  }
}
```

**Version**
- apollo-client@2.0.0

**Comment by bnovf** [comment]
You should import `gql from 'graphql-tag'`
Check the migration docs https://www.apollographql.com/docs/react/2.0-migration.html

**Comment by peggyrayzis** [comment]
Thanks @bnovf! I'm going to close this.

**Comment by bdombro** [comment]
Got it working, thanks for the help. I had a hell of a time trying to get the Expo Snack working locally, especially since I could not extract or locate a working package.json. Maybe we should add an example with complete source? Here is mine fyi: https://github.com/benevolenttech/react-apollo2-examples/tree/Native
