### ISSUE TITLE
Where did createNetworkInterface go?

### ISSUE THREAD

**Issue by joshhunt** [apollographql/apollo-client#2458]
[react-apollo docs](http://dev.apollodata.com/react/initialization.html) mentions I import `createNetworkInterface` from `react-apollo`:

```
import { ApolloClient, createNetworkInterface } from 'react-apollo';
const networkInterface = createNetworkInterface({
  uri: 'http://api.example.com/graphql'
});
const client = new ApolloClient({
  networkInterface: networkInterface
});
```

However that wasn't working, as I'm getting `Uncaught TypeError: (0 , _reactApollo.createNetworkInterface) is not a function. [After a bit of reading](https://github.com/apollographql/apollo-client/issues/108), it appears the docs is incorrect or out of date, and instead I should try importing it from `apollo-client`

[Then apollo-client docs mention](http://dev.apollodata.com/core/network.html):

```
import ApolloClient, { createNetworkInterface } from 'apollo-client';
const networkInterface = createNetworkInterface({ uri: 'https://example.com/graphql' });
const client = new ApolloClient({
  networkInterface,
});
```

That also doesn't work, failing with the same 'not a function' error as before. Grepping through the apollo-code i have in node_modules, I can't find any mention of `createNetworkInterface`.

I have `apollo-client@2.0.1` and `react-apollo@2.0.0 installed.

Where am I supposed to get it from? What am I doing wrong?

**Comment by qswitcher** [comment]
createNetworkInterface was removed in 2.x. Refer to the upgrade docs and new documentation
https://github.com/apollographql/apollo-client/blob/master/Upgrade.md

docs: https://www.apollographql.com/docs/react/  (linked on project README)

**Comment by joshhunt** [comment]
Ahhh right hmm okay. I was reading the docs at dev.apollodata.com, which is confusing to say the least.

Thanks for the help.

**Comment by kvreem** [comment]
@joshhunt do you know how you got your local host working on https?

**Comment by onurarpapay** [comment]
> createNetworkInterface was removed in 2.x. Refer to the upgrade docs and new documentation
> https://github.com/apollographql/apollo-client/blob/master/Upgrade.md
> 
> docs: https://www.apollographql.com/docs/react/ (linked on project README)

well the first link no longer works and I am wondering what I have to do in order to upgrade....

**Comment by qswitcher** [comment]
Docs are now here
https://www.apollographql.com/docs/react/recipes/2.0-migration.html

**Comment by willrogers** [comment]
That link is also broken now.

**Comment by lethak** [comment]
Use links instead,
https://www.apollographql.com/docs/link/links/http/#upgrade-apollo-client-10
