### ISSUE TITLE
Where did createNetworkInterface go?

### ISSUE THREAD

**Issue by joshhunt** [apollographql/apollo-client#2459]
[react-apollo docs](http://dev.apollodata.com/react/initialization.html) mentions I import `createNetworkInterface` from `react-apollo`:

```
import { ApolloClient, createNetworkInterface } from 'react-apollo';
const networkInterface = createNetworkInterface({
  uri: 'http://api.example.com/graphql'
});
const client = new ApolloClient({
  networkInterface: networkInterface
});
```

However that doesn't work as it's no longer included in `react-apollo`.

[Then apollo-client docs mention](http://dev.apollodata.com/core/network.html) I can import it from `apollo-client`:

```
import ApolloClient, { createNetworkInterface } from 'apollo-client';
const networkInterface = createNetworkInterface({ uri: 'https://example.com/graphql' });
const client = new ApolloClient({
  networkInterface,
});
```

That also doesn't work.  `createNetworkInterface` doesnt appear to be included in `apollo-client` 2.0.1 either. Both code snippets result in “createNetworkInterface is not a function”

Where am I supposed to get it from? What am I doing wrong?

**Comment by sparshgr8** [comment]
m facing the same problem, how did you solve it ?

**Comment by fc** [comment]
@sparshgr8 `apollo-client` and `react-apollo` 2.x use `apollo-link`... https://www.apollographql.com/docs/link/index.html
