### ISSUE TITLE
Offline Support for Version 2?

### ISSUE THREAD

**Issue by ralphchristianeclipse** [apollographql/apollo-client#2460]
Based on the apollo client v2 redux has been deprecated as the default store

any ideas how to do offline support for apollo client?

**Comment by lancygoyal** [comment]
Is there is any way to configure apollo client with redux ?

**Comment by 2WheelCoder** [comment]
This has been discussed across a couple of other issues here and in apollo-link, notably https://github.com/apollographql/apollo-link/issues/125. I think there's some good momentum to get an offline cache solution going for Apollo 2 and I believe @danieljvdm may be opening a PR. I think other features like queueing requests are probably more suited to an apollo-link alternative or middleware/afterware.

@stubailo @helfer Would a PR adding offline cacheing with something like LocalForage to apollo-cache-inmemory be a welcome feature?

**Comment by jbaxleyiii** [comment]
@ralphchristianeclipse we definitely want to have great offline support! Its one of the big reasons for the new architecture of the 2.0 🎉 

That issue that @2WheelCoder is a great starting point, but we can also have a discussion around features here for everyone to chime in (this repo has higher traffic)

@2WheelCoder I'd prefer that any offline tooling work across cache implementations so maybe it is a wrapper around the Cache API so that other implementations can benefit from it?

**Comment by danieljvdm** [comment]
@jbaxleyiii I think in order for offline to work across cache implementations we need a cache listener (to know when the store updates, in order to persist) on the top level api. Do you agree with this? If so I can probably get started on a PR for that.

**Comment by franceindia** [comment]
👍+1 on this.

**Comment by sscaff1** [comment]
This is stopping me from migrating my app to use GraphQL on the client. I still rely heavily on Redux Persist to ensure I have access to my data offline. +1 for this.

**Comment by clem109** [comment]
👍 +1

**Comment by stubailo** [comment]
We're working on it here, please join in! https://github.com/apollographql/apollo-cache-asyncstorage/issues/6

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Offline%20Support%20for%20Version%202%3F&body=Migrated%20from:%20apollographql/apollo-client%232460) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
