### ISSUE TITLE
v2 is sending an array

### ISSUE THREAD

**Issue by makamekm** [apollographql/apollo-client#2461]
Is it normal with the library? It sends an array instead of object to /graphql after upgrading v2.
I can't use it with Java, ... graphql servers.

```
[{"variables":{"sortBy":"MARKET_CAP","isAsc":true},"extensions":{},"operationName":null,"query":"query ($sortBy: SortByInput, $isAsc: Boolean) {\n  allCoins(sortBy: $sortBy, isAsc: $isAsc)\n}\n"}]
```

**Comment by jbaxleyiii** [comment]
@makamekm what link are you using? What versions?

**Comment by makamekm** [comment]
"apollo-link": "1.0.0"

**Comment by hwillson** [comment]
This should no longer be an issue using a current day version of Apollo Client. Let us know if you're still encountering this problem. Thanks!
