### ISSUE TITLE
Network error: Network request failed with status 200 - "OK"

### ISSUE THREAD

**Issue by gonardfreeman** [apollographql/apollo-client#2467]
Hello, I'm not sure is this issue or what, but it realy strange.
Why it think that 200 is error? 
```
loadData({ data: {loading, error, allChoices }}){
        console.dir(allChoices)
        if (loading) {
            return <p>Loading ...</p>;
        }
        if (error) {
            return <p>{error.message}</p>;
        }
        return <ul>
                { allChoices.map( ch => <li key={ch.id}>{ch.name}</li> ) }
            </ul>;
    }
```
and why provider do not see answer from api?
![selection_005](https://user-images.githubusercontent.com/16113714/32372853-48493eaa-c09f-11e7-901a-e3b9455f6d6a.png)
![selection_006](https://user-images.githubusercontent.com/16113714/32372854-486a0400-c09f-11e7-8122-3e74b4dd2094.png)
and last, how can I see recived data?

**Comment by gonardfreeman** [comment]
You can close, problem was at api endpoint

**Comment by slorber** [comment]
@gonardfreeman can you explain how you got a failure with res 200?

**Comment by gonardfreeman** [comment]
My server has answered with 200, but it make call to other server who got failure, so the answer was 200 and it was failure

**Comment by slorber** [comment]
ok I see.

I've read other issues and it seems common that graphql errors are returned with a 200 status code
