### ISSUE TITLE
Please update package.json / npm update

### ISSUE THREAD

**Issue by MrCheater** [apollographql/apollo-client#2468]

**Comment by jbaxleyiii** [comment]
@MrCheater what do you mean?

**Comment by MrCheater** [comment]
@jbaxleyiii 
- https://github.com/apollographql/apollo-client/blob/master/packages/apollo-cache-inmemory/package.json#L37-L59
- https://github.com/apollographql/apollo-client/blob/master/packages/apollo-cache/package.json#L38-L53
- https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client-preset/package.json#L37-L56
- https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/package.json#L51-L93
- https://github.com/apollographql/apollo-client/blob/master/packages/apollo-utilities/package.json#L37-L53
- https://github.com/apollographql/apollo-client/blob/master/packages/graphql-anywhere/package.json#L35-L56

**Comment by jbaxleyiii** [comment]
@MrCheater are you referring to the locked dependencies? I've been thinking about unlocking them for the libraries so its not so limiting for users.

Going to mark this as a post 2.0 feature to address asap
