### ISSUE TITLE
<query>.loading will not change to true

### ISSUE THREAD

**Issue by zach-is-my-name** [apollographql/apollo-client#2469]
**Intended outcome:**
Want stepQuery.loading === false
```

  graphql(_stepQuery, {
    name: 'stepQuery',
    options: ({goalDocId}) => ({
      fetchPolicy: 'network-only',
      notifyOnNetworkStatusChange: true,
      variables: {
        goalDocId
      }
    })
  }
)

componentWillReceiveProps(nextProps) {
    let stepIdsFromServer
    if (nextProps.currentGoalSteps.length > this.props.currentGoalSteps.length)   {
      console.log('called')
      this.props.stepQuery.refetch()
      console.log('this.props', this.props)
      console.log('nextProps',nextProps)
      if (!nextProps.stepQuery.loading) {
      // console.log('nextProps.stepQuery.allSteps', nextProps.stepQuery.allSteps)
          console.log('called2')
}
```
**Actual outcome:**
console.log 'called' is displayed
console.log 'called2' is never displayed

**Version**
- apollo-client@1.4.15

**Comment by jbaxleyiii** [comment]
@zach-is-my-name can you try updating to the 2.0 and seeing if this is still a bug? We fixed a couple of causes of this

**Comment by makamekm** [comment]
I use v2. And I have the same issue.

**Comment by javascriptlove** [comment]
Doesn't this evaluation return false when loading == false?

```
if (nextProps.currentGoalSteps.length > this.props.currentGoalSteps.length) 
```

**Comment by zach-is-my-name** [comment]
@javascriptlove Those are values from my Redux store...
@makamekm 
@jbaxleyiii  thank you, apparently i was stuck in a loop of my own creation... 
I resolved by checking query loading state **before** comparing props
...appologies, closing

https://stackoverflow.com/questions/47101258/query-loading-will-not-change-to-true
