### ISSUE TITLE
Tutorial docs and 2.0 announcement on Medium do not show full 2.0 import changes

### ISSUE THREAD

**Issue by lukecwilliams** [apollographql/apollo-client#2477]
While going through Tutorial information I was confused on why gql import was not working, having just installed 2.0 on a new project.  I finally realized that many of the most prominent articles online are not correct or complete.

I'd strongly suggest either updating the Tutorials with the new imports and client construction (which may be all that's necessary), or point at the top of each to the 2.0 docs.  (Note that these are at the top of Google for multiple queries on "How To Apollo" and I expect are getting a lot of traffic and teaching 1.0 information.)  E.g. E.g.: https://dev-blog.apollodata.com/react-graphql-tutorial-mutations-764d7ec23c15

Additionally, I was confused by this (otherwise awesome) article which only references a subset of the import changes required.  gql import must also change in 2.0, not only ApolloClient and createNetworkInterface.  https://dev-blog.apollodata.com/whats-coming-in-apollo-client-2-0-bcd8ea64acbd

Thanks!

**Comment by jbaxleyiii** [comment]
@lukecwilliams I see that you fixed a number of these in the docs 👏 thanks so much! I'll update the article as well!
