### ISSUE TITLE
docs: Migrating from 1.0 > Installation > Custom configuration > after

### ISSUE THREAD

**Issue by e346m** [apollographql/apollo-client#2483]
This doc seems to have an unnecessary line because example code doesn't use ApolloLink.

https://github.com/apollographql/apollo-client/blame/c500fcd83b357165872a3761e894624877b89708/docs/source/2.0-migration.md#L136

https://www.apollographql.com/docs/react/2.0-migration.html#full

**Comment by jbaxleyiii** [comment]
@e346m would you be able to open a PR removing it?

**Comment by e346m** [comment]
@jbaxleyiii Sure 👍
