### ISSUE TITLE
Unify error returning naming

### ISSUE THREAD

**Issue by jbaxleyiii** [apollographql/apollo-client#2492]
Currently we use `graphQLErrors` and `networkError` in things like apollo-link-error and internally, however we return them both as `error` on things like `currentResult()`

I think we should start to return these errors as separate keys from the currentResult call and can make it backwards compat by keeping the current `error`. Long term I'm not sure if we should remove `error` as it is a way of representing both network + execution errors.

Thoughts?
cc @peggyrayzis

**Comment by peggyrayzis** [comment]
This makes a lot of sense! I'm all for it 😀

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Unify%20error%20returning%20naming&body=Migrated%20from:%20apollographql/apollo-client%232492) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
