### ISSUE TITLE
Package Apollo-Client-Preset has missing dependencies

### ISSUE THREAD

**Issue by hillct** [apollographql/apollo-client#2493]
When attempting to setup an initial apollo-client and react application using apollo-client-preset, I followed documentation found in README.md from the NPM as published in the npmjs.com repository https://www.npmjs.com/package/apollo-client-preset currently at v1.0.1
 which states in part:

Use create-react-app then yarn add apollo-client-preset and replace below code for index.js

then provides sample code which I copied and pasted as-is.

This code apparently depends upon the packages graphql and react-apollo which inexplicably were not installed as dependencies of Apollo-Client-Preset, yielding errors:

Module not found: Can't resolve 'graphql/language/parser'

and one about missing react-apollo.

The solution was to add the missing dependencies via yarn:

yarn add graphql
yarn add react-apollo

These two modules are not listed as dependencies of apollo-client-preset so the simplest solution would be to add them to that package's package.json dependencies however, if the expectation is they'd be required as upstream dependencies, then there may be an upstream module where those dependencies should be inserted.

**Version**
- apollo-client@2.0.1 (via yarn)

**Comment by peggyrayzis** [comment]
Hi! We mention the extra dependencies in the README for `apollo-client` [here](https://github.com/apollographql/apollo-client#installation). Would you like to send a PR to add additional installation information for the README of `apollo-client-preset`? I can walk you through it if you need help. 😀

**Comment by hillct** [comment]
For what it's worth, I'd advise you to rethink your approach of adjusting documentation to explain a flaw in a meta-package, which flies in direct opposition to the stated purpose of the meta-package. Either way, it's your project and you can engineer it as you see fit.
   To your other point - while a generous offer - I don't require instruction in the use if Git. Thanks.
