### ISSUE TITLE
Mocking with 2.0

### ISSUE THREAD

**Issue by liz-mars** [apollographql/apollo-client#2497]
Hi all,

First of all, I love Apollo Client; big thanks to the dev team.

Form responses:

Intended outcome: upgrade from react-apollo 1.2 to 2.0
Actual outcome: I have no idea how to mock anything anymore
How to reproduce the issue: Attempt to find information about mocking with 2.0
Versions: as above
 
Discursive account:

I've had to upgrade to 2.0 (react-apollo) by the lack of (remaining) documentation on how to silence the heuristic fragment matcher warning. (The documentation I can find concerns 2.0). 

After having carefully rewritten my initialization code to allow use createHttpLink and friends, I am mystified (and cannot find documentation) on how to do mocking. I have several hundred lines of code specifying a mock NetworkInterface, as per the old docs.

What's the new equivalent to `mockNetworkInterfaceSchema` and friends? Is this documented anywhere?

Anyway, grateful for all your hard work and look forward to learning how I can unfsck my codebase, even as I sit anxiously by :)

**Comment by n1ru4l** [comment]
Does this help you? https://github.com/apollographql/react-apollo-error-template/tree/b1c8e690ddec5d6a0f2723c2a705ff6913566ee4/src/graphql

**Comment by liz-mars** [comment]
Yes, that helps enormously. Looking forward to the docs still, though :) ...and of course the update from Storybook. I'll send this their way.

**Comment by jbaxleyiii** [comment]
@liz-mars we will definitely work to update the docs! Also, I'd love to feature a recipe on integration with Storybook. Do you know who would be the best to help me with that? @abhiaiyer91 ?

**Comment by liz-mars** [comment]
@jbaxleyiii  I'm afraid I don't, but please keep me in the loop! It's the one thing missing for me now :)

**Comment by abhiaiyer91** [comment]
@jbaxleyiii lets chat about this! I'll try to get this done as soon as i can

**Comment by liz-mars** [comment]
@abhiaiyer91 @jbaxleyiii  PR for Storybook decorator https://github.com/abhiaiyer91/apollo-storybook-decorator/pull/7

**Comment by luisgrases** [comment]
You can Mock using: https://www.apollographql.com/docs/graphql-tools/mocking.html

You can use this to create a HOC that passes the response a Component through the data prop.

Something like: 
`import React from 'react'
import schema from 'gql-schema.js'
import { graphql } from 'graphql';
import { makeExecutableSchema, addMockFunctionsToSchema } from 'graphql-tools';

const executableSchema = makeExecutableSchema({ typeDefs: schema });
addMockFunctionsToSchema({ schema: executableSchema });

const GQLMockHOC = (query) => (Component) => 
  class GQLMock extends React.Component {

    constructor(props) {
      super(props);
      this.state = { data: null}
    }

    async componentWillMount() {
      const response = await graphql(executableSchema, query)
      this.setState({ data: response.data })
    }

    render() {
      const { data } = this.state
      return (data) ? <Component data={data} {...this.props} /> : <div>Loading</div>
  }

}


export default  GQLMockHOC`

Take in account that you need to change the schema import to actually import your own schema.

Then you can use it like:

`const ComponentWithData = GQLMockHOC(query)(MyComponent)`
ComponentWithData will have a data property with the fake response.
