### ISSUE TITLE
The cache doesn't work if multiple GraphQL components rendered in the same level.

### ISSUE THREAD

**Issue by xcv58** [apollographql/apollo-client#2500]
The cache doesn't work if multiple GraphQL components rendered in the same level.

**Intended outcome:**
If you have components using the same query, there should be only one request.
```jsx
import { graphql } from 'react-apollo'
import gql from 'graphql-tag'

const query = gql`{ allPosts { title id } }`

class Test extends Component {
  render () {
    console.log(this.props)
    return (
      <div>123</div>
    )
  }
}

const GraphQLTest = graphql(query)(Test)
// render in a parent component
...
              <GraphQLTest />
              <GraphQLTest />
...
```

**Actual outcome:**
It actually fires multiple requests. 

**How to reproduce the issue:**
I create a repo to reproduce this:
https://build-nhpmxggvzn.now.sh/
![image](https://user-images.githubusercontent.com/503123/32467758-99b0c3c2-c300-11e7-88a3-527c106a7b14.png)

https://build-nhpmxggvzn.now.sh/lazy
![image](https://user-images.githubusercontent.com/503123/32467790-a8740c98-c300-11e7-92b2-d596016ca7b0.png)

PS: `cixmkt2ul01q00122mksg82pn` are the GraphQL requests.

**Versions**
- apollo-client@2.0.2
- apollo-cache-inmemory:@1.0.0
- apollo-link@1.0.0
- apollo-link-http@1.1.0
- apollo-client-preset@1.0.2
- graphql@0.11.7
- graphql-tag@2.5.0
- react-apollo@2.0.0

This is also discussed in #2444

**Comment by JakeDawkins** [comment]
@xcv58 Have you checked out the dedup link? I think it solves what you're asking. Two identical requests happening at the same time? https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-dedup

**Comment by jbaxleyiii** [comment]
@xcv58 I've heard from a few people that this is an issue. My hunch is a bug in deduplication and I'll be taking a look at it ASAP!

**Comment by xcv58** [comment]
Thanks @jbaxleyiii 
I guess this may be related to another issue: https://github.com/apollographql/apollo-link/issues/225

**Comment by xcv58** [comment]
Hi @jbaxleyiii 

I did verify your latest publish fix the problem.
https://github.com/xcv58/apollo-client-cache-same-query/commit/bea448e4ae21d8b2607192cdb5c19b90342200ca
https://github.com/apollographql/apollo-link/commit/685b07dd024b2e97a0929ac841ba5e1d19aa042a

Thank you very much!
