### ISSUE TITLE
Documentation for v1?

### ISSUE THREAD

**Issue by timscott** [apollographql/apollo-client#2505]
Where can I find the documentation for version 1.x.x?

**Comment by hwillson** [comment]
@timscott Try: https://s3.amazonaws.com/apollo-docs-1.x/index.html

**Comment by sharonswli** [comment]
@hwillson Thanks for the link. Although it appears only the React-Apollo section is working and all other sections just link me back to the 2.0 docs. 

Releasing the full v1 docs would be much appreciated, considering many of us are stuck in 1.0 for the time being.

**Comment by ibigpapa** [comment]
They should totally provide the 1.0 docs as well.  Due to the redux removal i can't move out yet as the libraries i need for similar states are not production ready.  

- https://github.com/nikolasburk/client-side-state-with-apollo 
- https://github.com/apollographql/apollo-link-state

**Comment by peterp** [comment]
@sharonswli I took a closer look at the repo and it seems like some of the 1.0 documentation had been [updated to 2.0](https://github.com/apollographql/react-docs/commits/master/source/initialization.md) accidently, just check the commit history.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Documentation%20for%20v1%3F&body=Migrated%20from:%20apollographql/apollo-client%232505) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
