### ISSUE TITLE
How pass a field from one request's response to another in Compose 

### ISSUE THREAD

**Issue by kavink** [apollographql/apollo-client#2511]
Looking at docs  seems like I should be able to use```options.context``` to pass information in the chain of Compose requests. But I am unable to find example on how to do it for chaining queries. I can see how we can do it in chaining links: https://www.apollographql.com/docs/link/overview.html#context
 but not how to do it in queries.

from: https://www.apollographql.com/docs/react/basics/queries.html
```
With the flexiblity and power of Apollo Link being part of Apollo Client, you may want to send information from your operation straight to a link in your network chain! This can be used to do things like set headers on HTTP requests from props, control which endpoint you send a query to, and so much more depending on what links your app is using. Everything under the context object gets passed directly to your network chain
```

Would be great if I can see an example code somewhere on how its passed along and how to use it down the chain of compose after response is obtained. this is a very cool feature I just discovered reading the doc for Nth time.

**Comment by jbaxleyiii** [comment]
@kavink what do you mean by chaining queries?

**Comment by hwillson** [comment]
We haven't heard back regarding the additional details requested in https://github.com/apollographql/apollo-client/issues/2511#issuecomment-343956809, so closing for now. Thanks!
