### ISSUE TITLE
apollo-cache-inmemory v1 -> v1.1 breaks interfaces

### ISSUE THREAD

**Issue by jaydenseric** [apollographql/apollo-client#2512]
After updating, interface fragments do not appear in data.

**Comment by corydeppen** [comment]
The return type of the `read` method in [`InMemoryCache`](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-cache-inmemory/src/inMemoryCache.ts#L76) (`T | null`) doesn't match the signature in [ApolloCache](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-cache/src/cache.ts#L11) (`T`). If `null` is truly a valid return type for this method, it looks like the signature should be updated in `ApolloCache`.

**Comment by corydeppen** [comment]
Actually, this appears to be a duplicate of #2503.

**Comment by jaydenseric** [comment]
To be clear, by interfaces I mean actual GraphQL interfaces, not TypeScript interfaces. I don't use TypeScript. This bug completely breaks apps.

**Comment by jaydenseric** [comment]
This is not stale! I have had to pin `apollo-cache-inmemory` to v1, and every version since is broken.

**Comment by hwillson** [comment]
This issue was resolved by https://github.com/apollographql/apollo-client/pull/2572. If anyone is still encountering this problem, please let us know (ideally with a small runnable reproduction). Thanks!
