### ISSUE TITLE
empty headers in in afterware link

### ISSUE THREAD

**Issue by ecerroni** [apollographql/apollo-client#2514]
**Intended outcome:**

I'm setting a custom header on the response I'm supposed being able to access in the afterware link

**Actual outcome:**

The headers object is empty

**How to reproduce the issue:**

Some context:
I have a custom header in response visible in network tab but not in the response object.

I know that the custom header is stripped away by the browser as this is a CORS request so I put it into Access-Control-Expose-Headers.

Now the browser exposes the custom header just fine as you may see in the screenshot and I should be able to access it within the afterwareLink.  Though that's not the case.

![headers](https://user-images.githubusercontent.com/11174327/32542881-46c3059c-c474-11e7-8a6c-e9e577b6444a.png)

The headers object is always empty though getContext yields `forceFetch` and `cache` fields 

![console](https://user-images.githubusercontent.com/11174327/32542901-58935a9c-c474-11e7-8cd5-5357e818126e.png)

I'm using:
CLIENT:
    "apollo": "0.2.2",
    "apollo-cache-inmemory": "1.1.0",
    "apollo-client": "2.0.2",
    "apollo-link": "1.0.0",
    "apollo-link-context": "1.0.0",
    "apollo-link-error": "1.0.0",
    "apollo-link-http": "1.1.0",
    "graphql": "0.11.7",
    "graphql-tag": "2.5.0",
    "vue": "2.5.3",
    "vue-apollo": "3.0.0-alpha.2",

SERVER:
    "apollo-server-express": "1.2.0",
    "body-parser": "^1.17.1",
    "cors": "^2.8.3",
    "express": "^4.15.2",
    "graphql-tools": "^1.2.3",

Afterware code:
```
const afterwareLink = new ApolloLink((operation, forward) => {
  const { headers } = operation.getContext();
  console.log(operation.getContext());
  if (headers) {
    const refreshToken = headers.get('x-refresh-token');
    console.log('refreshToken', refreshToken);
  }
  return forward(operation);
}
```

**Version**
- apollo-client@2.0.2

**Comment by Thr1ve** [comment]
I ran into this issue as well and found that I had to get the context after `forward(operation).map` in order for the correct response object with headers to be available.

Afterware code:
```
const afterwareLink = new ApolloLink((operation, forward) => {
  return forward(operation).map(response => {
    const context = operation.getContext();
    const { response: { headers } } = context;

    if (headers) {
      const refreshToken = headers.get('x-refresh-token');

      if (refreshToken) {
        localStorage.setItem('refreshToken', refreshToken);
      }
    }

    return response;
  });
});
```

**Comment by ecerroni** [comment]
@Thr1ve You save my day! Although I was looking in that direction I wasn't able to get it right.

Thanks a lot :+1: 

Now I'm just wondering if that's the way it was supposed to be. In the Context section of the readme it's written:
```
This link also attaches the response from the fetch operation on the context as response so you can access it...
```
Now that you've post it I have to say that it reassembles your code example although it wasn't so obvious to me.

**Comment by jbaxleyiii** [comment]
@ecerroni we should def improve that portion of the docs! It is on the ApolloLink repo, would you be up for improving that?

@Thr1ve thanks for the assist here!

**Comment by Knaackee** [comment]
After trying to get it to work for several hours, i have to ask here.
I have the exact same problem and tried what @Thr1ve  suggested. 

I use the same dependencies and versions as @ecerroni 

I tried using "Access-Control-Expose-Headers: *" and "Access-Control-Expose-Headers: x-refresh-token".

heres is what i see in the chrome network tab 

![screen shot 2017-11-16 at 11 26 41 1](https://user-images.githubusercontent.com/880759/32886503-21f005a0-cac1-11e7-990a-7e46743a139e.png)

and the console.log of the response.

![screen shot 2017-11-16 at 11 29 14](https://user-images.githubusercontent.com/880759/32886586-72f43ca0-cac1-11e7-8b60-bdfcbc8f838d.png)

What i am missing here ? 

Thanks a lot @jbaxleyiii and the whole apollo team!

**Comment by ecerroni** [comment]
That's ok I guess as it is the same thing I see in mine.

However `headers.get('x-refresh-token')` correctly retrieves the token and I can both console.log it and set it in the localStorage in the afterware code.

Do you mean it is not working for you? I mean retrieving the header using `headers.get('x-refresh-token')`

A complete example:
```
import { ApolloLink } from 'apollo-link';
import { createHttpLink } from 'apollo-link-http';

const httpLink = createHttpLink({ uri: 'http://localhost:3001/graphql' });

const afterwareLink = new ApolloLink((operation, forward) => {
  return forward(operation).map(response => {
    const context = operation.getContext();
    const { response: { headers } } = context;

    if (headers) {
      const token = headers.get("x-refresh-token");
      
      if (token) {
        localStorage.setItem("token", token);
      }

    }
    return response;
  });
});

// use with apollo-client
const link = afterwareLink.concat(httpLink);
```

**Comment by Knaackee** [comment]
@ecerroni 

Sorry i missed that. Now its working as expected. Thank you!

In addition i had to change `Access-Control-Expose-Headers: *` to `Access-Control-Expose-Headers: x-refresh-token`  to make it work. 

Thanks a lot!

**Comment by viiiprock** [comment]
Hi, sorry @ecerroni , I got same issue with Express but not solve it out yet, would you please take a look me?

1. I've set the response headers in resolver like this
<img width="1066" alt="screen shot 2017-11-30 at 6 32 03 pm" src="https://user-images.githubusercontent.com/14918259/33429401-496dd4e2-d5ff-11e7-841a-507c23aee2b2.png">
 2. Response headers at client did not get it 
<img width="1095" alt="screen shot 2017-11-30 at 6 33 12 pm" src="https://user-images.githubusercontent.com/14918259/33429453-78a7aa08-d5ff-11e7-8fa2-6a326234f222.png">
3. I tried to retrieve it (but sure I couldn't get it):

```js
const authLink = new ApolloLink((operation, forward) => {
  const token = localStorage.getItem(AUTH_TOKEN)
  const refresh_token = localStorage.getItem(REFRESH_TOKEN)
  if (token) {
    operation.setContext({
      headers: {
        'x-token': token,
        'x-refresh-token': refresh_token
      }
    })
  }
  return forward(operation).map(response => {
    const context = operation.getContext()
    const { response: { headers } } = context
    if (headers) {
      const token = headers.get("x-token")
      const refresh_token = headers.get("x-refresh-token")
      if (token) {
        localStorage.setItem(AUTH_TOKEN, token)
        localStorage.setItem(REFRESH_TOKEN, refresh_token)
      }
    }
    return response
  })
})
```

**Comment by viiiprock** [comment]
nvm, I got this, pass the token to headers on the auth user context, not on the resolver

**Comment by drcallaway** [comment]
I've been unable to access the response headers from my afterware. The code essentially looks like this:

```
export default class Afterware extends ApolloLink {
  request(operation, forward) {
    const context = operation.getContext();
    const requestHeaders = context.headers;

    log(requestHeaders);

    return forward(operation).map(result => {
      const responseContext = operation.getContext(); // RETURNS EXACT SAME CONTEXT AS ABOVE
      const response = responseContext.response; // RESPONSE IS UNDEFINED
      log(response.headers);
      return result;
    });
  }
}
```

The problem is that the call to `operation.getContext()` returns the exact same object both before and after the `forward()` call. It looks like this in both places:

```
{
  cache: ...,
  forceFetch: false,
  getCacheKey: f (obj),
}

**Comment by bugstamp** [comment]
res.set('Access-Control-Expose-Headers', '*')  working for me

**Comment by kafkahw** [comment]
Just in case someone wants to know more about [`Access-Control-Expose-Headers`](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Access-Control-Expose-Headers): it's usefully when making cors request because by default server only expose [`CORS-safelisted request-header`](https://fetch.spec.whatwg.org/#cors-safelisted-request-header). Adding this header will allow you to expose any http headers (including custom headers) to client.

**Comment by alamothe** [comment]
Wasted a couple of hours too :) 

Looks like if you `console.log` headers, it will appear as empty. Iterating over it doesn't work either. 

Whereas getting the header by name: `context.response.headers.get('...')` magically works. Now only to find the Chrome engineer who is responsible for this behavior...

**Comment by alan345** [comment]
I read carefully all of your posts, but I'am still having null.
Here you have my code :

```
const middlewareAuthLink = new ApolloLink((operation, forward) => {
  const token = localStorage.getItem(AUTH_TOKEN)
  const testModeHeader = localStorage.getItem(TEST_MODE)
  const spoofeduserheader = localStorage.getItem(SPOOFED_USER_ID) ? localStorage.getItem(SPOOFED_USER_ID) : ''
  const authorizationHeader = token ? `Bearer ${token}` : null
  operation.setContext({
    headers: {
      authorization: authorizationHeader,
      testMode: testModeHeader,
      spoofeduserheader: spoofeduserheader
    }
  })
  return forward(operation).map(response => {
    const context = operation.getContext()
    const {
      response: { headers }
    } = context
    if (headers) {
      const refresh_token = headers.get('x-token')
      console.log(refresh_token) // line index.js:37
    }
    return response
  })
})
```

The response:
![image](https://user-images.githubusercontent.com/15246526/67610528-4c38af00-f748-11e9-87ca-cec960e625dd.png)


and the console:
![image](https://user-images.githubusercontent.com/15246526/67610547-62df0600-f748-11e9-928b-679deedcbe52.png)

What am I missing?

**Comment by alan345** [comment]
I got it

> @ecerroni
> 
> Sorry i missed that. Now its working as expected. Thank you!
> 
> In addition i had to change `Access-Control-Expose-Headers: *` to `Access-Control-Expose-Headers: x-refresh-token` to make it work.
> 
> Thanks a lot!

Must be set in the backend! (express).
 then the frontend can acces to it!
Not it works!
