### ISSUE TITLE
is it possible to force querying of id field?

### ISSUE THREAD

**Issue by helios1138** [apollographql/apollo-client#2517]
is it possible to force apollo to query `id` field for all objects?
e.g. I almost never want `id` in components, but it is necessary for denormalization and caching so I have to manually add it everywhere

**Comment by jbaxleyiii** [comment]
@helios1138 unfortunately, this is not something that we want to do with Apollo Client as it would enforce a schema requirement for usage.

That being said, I think there are a couple places where this *could* be done.
1. a helper function that wraps `gql` calls when creating the AST could add `id`
2. a fork of the InMemoryCache that adds it to all operations using the `transformDocument` method on the cache

Long term, my plan is to continue refactoring the core classes to be used in an `ApolloLink` chain which would potentially allow for links prior to the cache read. This would make it easy for such a feature
