### ISSUE TITLE
Form submit button in sibling component

### ISSUE THREAD

**Issue by evangow** [apollographql/apollo-client#2520]
It's unclear how to insert data into the local cache then send that data with a mutation from another component in Apollo Client 2

Use case: I have a "submit" button in the navbar and a form for creating an item (let's call it ItemCreate). The navbar and form are rendered by react-router v4 with Route components and the ItemCreate is wrapped by a PrivateRoute component to handle authorization.

What I would do with Redux is update the store with onChange events from the form, then when the "submit" button is pressed in the navbar, I would send that data from the store to the server. The docs aren't clear on how to insert data into the cache if you're not updating the cache for an existing query.

App component
```javascript
class App extends Component {
  render() {
    return (
      <div>
        <Switch>
          <Route path='/item/new' component={NavBarItemCreate} />
          <Route path='/' component={NavBarDefault} />
        </Switch>
        <Switch>
          <Route path='/books/new' component={PrivateRoute(ItemCreate)} />
        </Switch>
      </div>
    );
  }
}
```

Navbar component (using Semantic-UI-React below)
```javascript
class NavBarBookCreate extends Component {
  render() {
    return(
        <Menu>
            <Menu.Item>
              Save
            </Menu.Item>
        </Menu>
    );
  }
}
```

ItemCreate component (using Semantic-UI-React below)
```javascript
class ItemCreate extends Component {
  state = {
    itemData: '',
  }

  render() {
    return(
      <Form>
        <Form.Input
          value={this.state.itemData}
          onChange={(e, data) => this.setState({ itemData: data.value })}
        />
      </Form>
    );
  }
}
```

**Comment by jbaxleyiii** [comment]
@evangow if you are wanting to store data in redux to use it within an operation, then create a reducer / action / dispatcher for redux to save the form data into the redux store, then use something like `react-redux` to pull it out of the store for use in a mutation.

Apollo no longer uses redux under the hood. If you are wanting to manage all state in apollo, checkout [apollo-link-state](https://github.com/apollographql/apollo-link-state)
