### ISSUE TITLE
docs: broken links, missing info in mutation update docs

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-client#2522]
A few issues with https://www.apollographql.com/docs/react/basics/mutations.html#graphql-mutation-options-update (options.update section):

- [ ] All DataProxy links are broken
- [x] The "Apollo Client technical documentation on the subject" link is broken
- [ ] I believe the semantics of this function is that it is called twice if optimisticResponse is provided and once otherwise, but the docs don't say that explicitly.
- [ ] It doesn't really explicitly say other than in the example what the second argument looks like (ie that it has a property named `data`).
- [ ] Does this function get told that it is being called optimistically? I thought so but I don't see where it says that. (edit: it doesn't, see https://github.com/apollographql/apollo-client/issues/2523)

**Comment by glasser** [comment]
Also scrolling up a bit "be sure to read the recipe on Optimistic UI" is also a broken link.

**Comment by glasser** [comment]
Also another thing that's not clear to me: is it the case that any changes written during an optimistic call to `update` are automatically reverted when the mutation is done? (I think that's true and if so then that's good.) If so that should be explicit.

**Comment by glasser** [comment]
Also it might be nice to document that if you want to do custom writes optimistically that aren't part of the data returned by the mutation (eg, if you want to set some apollo-link-state state) then you can pass `optimisticResponse: {}` to trigger the optimistic writing stage without otherwise messing anything up.

**Comment by msmfsd** [comment]
Another link that appears to be broken is the `cache docs` link: https://www.apollographql.com/docs/react/basics/basics/cache.html

The link comes from `https://www.apollographql.com/docs/react/basics/setup.html#ApolloClient`

**Comment by glasser** [comment]
A couple of these have been fixed but not all of them.

**Comment by 0xcaff** [comment]
The links to source code on the following page don't work.

https://www.apollographql.com/docs/react/reference/index.html

For example, the [constructor] links here: (https://github.com/apollostack/apollo-client/blob/master/ApolloClient.ts#L78

[constructor]: https://www.apollographql.com/docs/react/reference/index.html#ApolloClient.constructor

**Comment by hwillson** [comment]
All doc issues outlined here should now be fixed. A quick summary:

> All DataProxy links are broken

**Fixed.**

> Also scrolling up a bit "be sure to read the recipe on Optimistic UI" is also a broken link.

**Fixed.**

> is it the case that any changes written during an optimistic call to update are automatically reverted when the mutation is done?

**Fixed.** Now explained in the [mutate API docs](https://www.apollographql.com/docs/react/api/apollo-client.html#ApolloClient.mutate).

> Another link that appears to be broken is the cache docs link

**Fixed.**

> The links to source code on the following page don't work.

**Fixed.**

> I believe the semantics of this function is that it is called twice if optimisticResponse is provided and once otherwise, but the docs don't say that explicitly.

**Fixed.** Now explained in the [mutate API docs](https://www.apollographql.com/docs/react/api/apollo-client.html#ApolloClient.mutate).

> It doesn't really explicitly say other than in the example what the second argument looks like (ie that it has a property named data).

**Fixed.** I've added a link to the mutation result docs.
