### ISSUE TITLE
Allow mutation update callback to know that it's being called optimistically

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-client#2523]
The mutation `update` callback can be called twice: once with optimistic data, once with the actual mutation result.

You should be able to tell the difference. Perhaps just add a bool `isOptimistic` next to `data` in the second argument.

One use case is to add an in-flight indicator to the cache while the mutation is in flight.

**Comment by glasser** [comment]
I don't believe this has been fixed.

**Comment by huangbong** [comment]
+1 for this.

**Comment by johnunclesam** [comment]
It would be awesome to have an indicator like the one proposed by @glasser.

I agree.

**Comment by gastonmorixe** [comment]
@glasser you can achieve this by using `apollo-link-state` and adding a `isOptimistic` field.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Allow%20mutation%20update%20callback%20to%20know%20that%20it's%20being%20called%20optimistically&body=Migrated%20from:%20apollographql/apollo-client%232523) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
