### ISSUE TITLE
docs: 'props' option to queries not documented

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-client#2524]
I don't see explicit documentation of `props` in https://www.apollographql.com/docs/react/basics/queries.html

**Comment by glasser** [comment]
Oh I see it's in https://www.apollographql.com/docs/react/basics/queries.html#graphql-props-option but not in the API section. Still confusing.

**Comment by glasser** [comment]
(Specifically, I got confused that the props callback has ownProps but other things like options or skip just get the props directly.)

**Comment by glasser** [comment]
I think this is still not done. I also think the `name` option is not documented in the API section?  It's also a little confusing that the API section documents the *output* from the API (the stuff on `data`) before the *input* to the API (options etc).

Honestly in general I find the API section confusing, especially around the fact that there is an option called options. Might be good to be super clear somewhere that `options` are the options for AC?

**Comment by jthegedus** [comment]
@glasser It's being tracked in a milestone for the docs so this should get updated in due time.

Now my 2c:
I think the docs need to be more clear that the props of the HOC get passed to through to the Component. For those who are missing HOC knowledge, it's not immediately clear that this happens. It would be great if the docs explored more than one example of utilising options, with a more comprehensive example (multiple props, using some props in the computed option and the rest in the component, etc)
