### ISSUE TITLE
can't find variable self when using apollo 2.0 with react-native

### ISSUE THREAD

**Issue by michaelknoch** [apollographql/apollo-client#2542]
I tried to upgrade apollo inside a react native project from 1.x to 2.0 but i ran into a redbox error.

**Intended outcome:**
The app should normally render

**Actual outcome:**
The app breaks with a redbox which says: `"cant find variable self" in fetch-npm-browserify.js`

<img width="432" alt="screen shot 2017-11-10 at 17 26 07" src="https://user-images.githubusercontent.com/5617793/32667868-45129c70-c63c-11e7-95a1-6eb0abd22de7.png">

**How to reproduce the issue:**
install apollo 2.0 in a react-native project

**Version**
```js
{
 "apollo-cache-inmemory": "1.0.0",
 "apollo-client": "2.0.1",
 "apollo-link-batch-http": "^1.0.0",
 "apollo-link-error": "^1.0.0",
 "apollo-link-http": "^1.1.0",
 "react-apollo": "^1.4.16",
}
```

thanks guys for your awesome work!!

**Comment by peggyrayzis** [comment]
Hi! Can you please post the code where you're initializing the client & your link chain?

**Comment by michaelknoch** [comment]
hey @peggyrayzis 
thanks for your reply

```js
const cache = new InMemoryCache({
    dataIdFromObject: (result) => {
        if (result._id && result.__typename) {
            return result.__typename + result._id;
        }
        return null;
    },
    addTypename: true,
});

const link = new BatchHttpLink({ uri: GRAPHQL_ENDPOINT, batchInterval: 10 }),
const apolloClient = new ApolloClient({ link, cache });
```

Passing fetch explicitly into BatchHttpLink constructor does not solve the problem.
Window.fetch is available throughout the whole project, it seems that accessing `self` here is the problem. Something like `if (typeof self === 'undefined') { self = window; }` silences the error, but its kind of weird, i guess.

**Comment by michaelknoch** [comment]
I think this issue is related to `apollo-link-batch-http`.  It seems this error does not appear when using `apollo-link`

**Comment by n1ru4l** [comment]
@michaelknoch This is most likely related to https://github.com/matthew-andrews/isomorphic-fetch/issues/125

`apollo-link-batch-http` is still using `apollo-fetch` which depends on `isomorphic-fetch`.

There is also hint in the readme of `apollo-link-batch-http`: **Note: This package will be updated to remove the dependency on apollo-fetch an use the same options / API as the http-link**

If there is no PR for this I could make one, since I am going to upgrade a project to 2.0 in the next few weeks.

**Comment by peggyrayzis** [comment]
Hi @n1ru4l! We would love if you could send a PR to upgrade `apollo-link-batch-http` to use global fetch & give the user the ability to pass in a fetcher if they would prefer. You can look at the `apollo-link-http` [source code](https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-http/src/httpLink.ts#L110) for an example.

**Comment by hwillson** [comment]
`apollo-link-batch-http` no longer uses `apollo-fetch`, so this issue should now be resolved. Please post back if you notice otherwise. Thanks!
