### ISSUE TITLE
Using SSR + setContext + createHttpLink results in empty initialState

### ISSUE THREAD

**Issue by human-a** [apollographql/apollo-client#2550]
**Intended outcome:**
I am using Apollo with NextJS to get SSR on my app. I followed the instructions on this [example](https://github.com/zeit/next.js/tree/canary/examples/with-apollo) and this [example](https://github.com/zeit/next.js/tree/canary/examples/with-apollo-auth) to add Apollo to Next.js

Everything was working fine until I upgraded to Apollo Data 2.x following the instructions found on [this page](https://www.apollographql.com/docs/react/2.0-migration.html)
 
**Actual outcome:**
Now, when I use SSR + setContext + createHttpLink together, the initial state is Empty. The following code is how I have implemented it:

```javascript
const cache = new InMemoryCache({
  dataIdFromObject: (o) => o._id,
  addTypename: true,
});

const httpLink = createHttpLink({
  fetch,
  uri: 'http://localhost:3333/graphql',
  credentials: 'same-origin'
});

const authLink = setContext((_, { headers }) => {
  // get the authentication token from local storage if it exists
  const token = localStorage.getItem('token');
  // return the headers to the context so httpLink can read them
  return {
    headers: {
      ...headers,
      authorization: token || null,
    }
  };
});

return new ApolloClient({
  link: authLink.concat(httpLink)
  queryDeduplication: true,
  ssrMode: !process.browser,
  cache: cache.restore(initialState || {}),
});
```

While this code works, and I see no errors, the initialState is empty and therefore the SSR is not working for my async requested data coming from the Database.

**How to reproduce the issue:**

if you change the code to be like the following, it works, but now I don't have my token inside my header:

```javascript
const cache = new InMemoryCache({
  dataIdFromObject: (o) => o._id,
  addTypename: true,
});

const httpLink = createHttpLink({
  fetch,
  uri: 'http://localhost:3333/graphql',
  credentials: 'same-origin'
});

// I have to ignore the context, since using the concat method will break the initialState

return new ApolloClient({
  link: httpLink
  queryDeduplication: true,
  ssrMode: !process.browser,
  cache: cache.restore(initialState || {}),
});
```

**Version**
I am using the following versions:

```json
"apollo-cache-inmemory": "^1.1.0",
"apollo-client": "^2.0.2",
"apollo-engine": "^0.5.4",
"apollo-link": "^1.0.0",
"apollo-link-context": "^1.0.0",
"apollo-link-http": "^1.1.0",
"apollo-link-set-context": "^0.5.4",
"apollo-server-express": "^1.2.0",
"apollo-utilities": "^1.0.1",
"react": "^16.0.0",
"react-apollo": "^2.0.1",
"react-dom": "^16.0.0",
"next": "^4.1.4",
```

**Comment by jbaxleyiii** [comment]
@human-a where is initial state coming from? Is there a chance that your setContextLink is throwing? Could you create a reproduction for me to test and verify the bug?

**Comment by human-a** [comment]
The initialState is followed based on the Next.js instructions. If you take a look at [this file](https://github.com/zeit/next.js/blob/canary/examples/with-apollo/lib/initApollo.js) and [this file](https://github.com/zeit/next.js/blob/canary/examples/with-apollo/lib/withData.js) You can see that the later creates a wrapper component containing the initalState (comes from getInitialProps static method, which is a next.js thing)

The problem started when I moved to version 2.0 of Apollo client, and it works if I avoid using ```link: authLink.concat(httpLink)```, but then again I lose my token which I need to get from localStorage.

If there is another way to set the authorization token in the header from the localStorage I am okay with that, but so far I have not found a way.

**Comment by human-a** [comment]
If you can not get it from the links I sent you, let me know and I will create a repo, but most of my code regarding graphql, is identical to the links I sent you, all I am adding to it is ```const authLink = setContext((_, { headers }) => {``` part

**Comment by hwillson** [comment]
This should no longer be an issue with modern day `apollo-client` (2.3.2) and `react-apollo` (2.1.4). Please post back if you notice otherwise. Thanks!
