### ISSUE TITLE
pollInterval keeps NgZone occupied and hangs e2e tests

### ISSUE THREAD

**Issue by gviligvili** [apollographql/apollo-client#2559]
I use protractor to test my project.
If setTimeout / setInterval is used the ngZone is occupied, and the app won't stablize therefore the protractor will throw Timeout Error accours : 
`
Timed out waiting for asynchronous Angular tasks to finish after 11 seconds.
`

When I use pollInterval option, protractor keep throwing this error.
when I remove pollInterval, e2e tests runs perfectly fine.

**Intended outcome:**
pollInterval should not occupie ngzone and e2e tests should run.

**Actual outcome:**
pollInterval holds ngZone and protractor fails to start.
(I don't want to use the "don't wait for angular" flag).

**How to reproduce the issue:**
Use watchQuery with pollInterval option and try to run protractor.

**Version**
- apollo-client@1.9.1
- apollo-angular@0.13.0
- angular 4.

**Comment by hwillson** [comment]
If this is still a problem, would you mind reporting this over in the https://github.com/apollographql/apollo-angular repo? Issues here are reserved for problems with the `apollo-client` project specifically. Thanks!
