### ISSUE TITLE
Auto-injected '__typename' throwing ER_BAD_FIELD_ERROR: unknown column in fieldlist

### ISSUE THREAD

**Issue by Trellian** [apollographql/apollo-client#2560]
**Intended outcome:**

The simple query:
```
query {
        iwRegions {
          country_id
          name
        }
      }
```
succeeds...

**Actual outcome:**

The backend MySQL server is throwing the following error:
```sql
"select `iw_region`.`country_id`, `iw_region`.`name`, `__typename` from `iw_region` - ER_BAD_FIELD_ERROR: Unknown column '__typename' in 'field list'"
```
and the GraphQLExpress server is throwing the following error:
```
Error: ER_BAD_FIELD_ERROR: Unknown column '__typename' in 'field list'
    at Query.Sequence._packetToError (C:\xampp\htdocs\iwallq\api\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (C:\xampp\htdocs\iwallq\api\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (C:\xampp\htdocs\iwallq\api\node_modules\mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (C:\xampp\htdocs\iwallq\api\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (C:\xampp\htdocs\iwallq\api\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\xampp\htdocs\iwallq\api\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)
```
**How to reproduce the issue:**

My server code looks like this:

```js
var graphQLServer = express();

graphQLServer.use(cors());

graphQLServer.use(bodyParser.urlencoded({ 
  extended: true 
}));

graphQLServer.use(bodyParser.json());  

graphQLServer.use('/graphql', graphqlExpress({
  schema: graphQlSchema
}));

```
and in the Vue client component I have :
```js
  apollo: {
    rows: {
      query: gql`query {
        iwRegions {
          country_id
          name
        }
      }`
    }
```
The exact same query:
```
query {
        iwRegions {
          country_id
          name
        }
```
succeeds in the GraphiQL client, and returns
```
{
  "data": {
    "iwRegions": [
      {
        "country_id": 1,
        "name": "Limpopo"
      },
      {
        "country_id": 1,
        "name": "Gauteng"
      },
      {
        "country_id": 1,
        "name": "Western Cape"
      },
      {
        "country_id": 1,
        "name": "Northwest Province"
      },
      {
        "country_id": 1,
        "name": "Mpumulanga"
      },
      {
        "country_id": 1,
        "name": "Northern Cape"
      },
      {
        "country_id": 1,
        "name": "Kwazulu Natal"
      },
      {
        "country_id": 1,
        "name": "Garden Route"
      },
      {
        "country_id": 1,
        "name": "Eastern Cape"
      }
    ]
  }
}
```
**Version**

On the server:
- apollo-server-express@<^1.2.0>

On the client:

- apollo-cache-inmemory": "^0.2.0-rc.4",
- apollo-client": "^2.0.2",
- apollo-link": "^1.0.2",
- apollo-link-http": "^1.1.0",
- apollo-link-ws": "^1.0.0",
- apollo-utilities": "^1.0.1",
 
**comments**

I have tried adding the following to try and remove the __typename, as per @rasdaniil in [#1564](https://github.com/apollographql/apollo-client/issues/1564#issuecomment-342528469) but it doesn't help, the error is the same:

```js
graphQLServer.use('/graphql', graphqlExpress({
  schema: graphQlSchema,
  formatParams: (params) => {
    const { variables, ...rest } = params;
    return {
      variables: omitDeep(variables, '__typename'),
      ...rest
    }
  }
}));

```
What am I doing wrong? Id appreciate any pointers!

Thanks
Adrian

**Comment by jbaxleyiii** [comment]
@Trellian it looks like you are sending the query to MySQL somehow? What does your resolver look like?

**Comment by Trellian** [comment]
@jbaxleyiii Hi, thanks for getting back to me. The problem is solved, my backware, objection-graphql just needed to filter out the __typename pseudocolumn that was being passed to it. However, should the __typename be passed to the backware in the first place? I would have thought that it would stop with the graphql layer?

**Comment by danderson00** [comment]
There are lots of people hitting this issue.

It is a cardinal sin for a library to modify incoming objects and expect developers to implement hacky, manual workarounds to deal with the modification.

Is there any intent for the maintainers to improve the situation?

**Comment by danderson00** [comment]
I've been thinking a bit more about this. After throwing out the idea of dynamically creating types to represent each GraphQL type (would prevent the need for the __typename field altogether), it would seem attaching metadata to each object is the simplest approach.

Given there fields other than the __typename field being attached, I suggest storing all the metadata as an object on a single property (following in webpack's footsteps, something like `__APOLLO__METADATA__`). It would be fairly trivial to strip this property from outgoing objects and should reduce complexity in the Apollo client codebase.

**Comment by hwillson** [comment]
The original issue here has been resolved.

@danderson00 Would you mind opening a new issue with your ideas so we can mark it as a feature request? Thanks!
