### ISSUE TITLE
Why doesn't .query() return a Promise?

### ISSUE THREAD

**Issue by kroeder** [apollographql/apollo-client#2561]
Just wanted to ask for the reasen why .query() does not return a Promise

I always end up calling .toPromise() because I don't want to unsubscribe something that is executed once anyway.

And if there's a good reason for it, does this mean, calling toPromise() is bad practice?

**Comment by jbaxleyiii** [comment]
@kroeder `.query` should return a promise? Are you seeing where its not?

**Comment by kroeder** [comment]
https://www.apollographql.com/docs/angular/basics/queries.html#queryref

"As you know, Apollo.query method returns an Observable that emits a result, just once, but Apollo.watchQuery also does the same except it passes multiple results."

Snippets from Apollo-angular source 
``` 
public watchQuery<T, V = R>(
    options: WatchQueryOptions & TypedVariables<V>,
  ): QueryRef<T> {
    return new QueryRef<T>(this.client.watchQuery<T>({...options}));
  }

  public query<T, V = R>(
    options: WatchQueryOptions & TypedVariables<V>,
  ): Observable<ApolloQueryResult<T>> {
    return fromPromise<ApolloQueryResult<T>>(() =>
      this.client.query<T>({...options}),
    );
  }
```
See https://github.com/apollographql/apollo-angular/blob/master/packages/apollo-angular/src/Apollo.ts

**Comment by jbaxleyiii** [comment]
@kroeder that sounds like an issue to bring up on the angular project. The core apollo-client returns a promise

**Comment by kamilkisiela** [comment]
@jbaxleyiii it completes after the first result. It's an Observable like everything in Angular. This way all can be easily chained etc.
