### ISSUE TITLE
Cache API Solidification and Adjustements

### ISSUE THREAD

**Issue by jbaxleyiii** [apollographql/apollo-client#2562]
Now that 2.0 has shipped, I think there is some important work to be done around the `Cache` interface, and potentially around the `cache` usage API with Apollo Client. I'd love for this issue to serve as a discussion point for listing what needs to be done, and what possible improvements can be made!

@nevir @yuit for your work with Hermes
@rportugal @kamilkisiela @niieani for custom cache integrations (ngrx / redux)
@peggyrayzis for react-native cache ideas
@shadaj for the initial abstraction and work 

Please comment with ideas / features you would love to see solidified + any use cases you are considering!

**Comment by tlvenn** [comment]
I have recently opened an issue(https://github.com/apollographql/apollo-client/issues/2558) regarding Apollo Cache and Relay Modern. It would be great if future work on the cache API could have in mind what Relay Modern cache interface is expecting and how this could be fulfilled.

I would love to see Apollo Cache being promoted outside of Apollo Client and provides integration with Relay Modern, similarly to Apollo Link.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Cache%20API%20Solidification%20and%20Adjustements&body=Migrated%20from:%20apollographql/apollo-client%232562) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
