### ISSUE TITLE
www.apollographql.com down

### ISSUE THREAD

**Issue by jschlieber** [apollographql/apollo-client#2564]
The docs are down...

**Comment by effektsvk** [comment]
It looks like it is back up and running, but if it's down again, check [this](https://www.howtographql.com) site. It isn't same as the docs but it is a pretty good tutorial.

**Comment by bristoljon** [comment]
Is it just me or is anyone else finding they appear briefly and then disappear now:

https://www.apollographql.com/docs/react/advanced/fragments

Chrome Mac

<img width="728" alt="Screen Shot 2019-05-29 at 11 43 03" src="https://user-images.githubusercontent.com/13088751/58551021-01e9eb00-8207-11e9-96ac-767cf1726027.png">

**Comment by Numbers88s** [comment]
docs are down again?

**Comment by Numbers88s** [comment]
Nvm. It loaded the next day. it was timing out on the request before. weird.
