### ISSUE TITLE
client.writeFragment doesn't update components

### ISSUE THREAD

**Issue by wailorman** [apollographql/apollo-client#2570]
I've encountered a problem with notifying react components about store changes when I making it through `client.writeFragment` or `client.writeQuery`. The store is updating, but components are not.

I've created a repo for reproducing this bug: https://github.com/wailorman/write-fragment-error
gh-pages: https://wailorman.github.io/write-fragment-error/

What I want:
When I'm filling login input I want to see real-time updates in UserForm & SideMenu components. I [wrote](https://github.com/wailorman/write-fragment-error/blob/master/src/UserForm.js#L22) some `writeFragment()`s to make it. I also tried [`writeQuery`](https://github.com/wailorman/write-fragment-error/blob/master/src/UserForm.js#L49) function, but it doesn't help. The store is updating, but components are rerendering only after mutation is complete.

To confirm that components are really not reacting to store writes I wrote [the function](https://github.com/wailorman/write-fragment-error/blob/master/src/index.js#L27) that updates the store every 2s with random login. 
And found smth interesting. After you click Submit, mutation writes new login to the store & successfully notifying all components. But components are updating twice: first — with login from randomizer, second — with login from mutation. You can see it in logs:
```
UserForm.shouldComponentUpdate / user login:  wailo9     <- from randomizer
SideMenu.shouldComponentUpdate / user login:  wailo9
UserForm.shouldComponentUpdate / user login:  xzcvxvxzvx   <- from mutation
SideMenu.shouldComponentUpdate / user login:  xzcvxvxzvx
```

I think I'm using writeFragment correctly, exactly as it described in [docs](https://www.apollographql.com/docs/react/features/caching.html#writequery-and-writefragment)

**Version**
- apollo-cache-inmemory@1.0.0
- apollo-client@2.0.1
- apollo-link@1.0.0
- react-apollo@2.0.0

**Comment by jbaxleyiii** [comment]
@wailorman yep! This is a confirmed bug and I've got a reproduction for it! Should have this fixed asap!
