### ISSUE TITLE
Need the documentation for v1.0

### ISSUE THREAD

**Issue by treecy** [apollographql/apollo-client#2577]
Hi there! 👋

I was wondering if there is a way to get the documentation for Apollo 1.0+?

I really like the new features of Apollo 2.0, and the migrating has been in our schedule already.
But we still need to work on Apollo 1.9 for some time before migrating. 
So it will be very nice if you can give us a way to check the documentation for Apollo 1.9.

Thank you very much.😁

**Comment by stubailo** [comment]
You can find the markdown content here: https://github.com/apollographql/react-docs

Hope that's a good solution, it is a good amount of work for us to build a version selector right now for the site.

**Comment by treecy** [comment]
@stubailo This is helpful enough for now! 😁

Thank you very much!!

**Comment by andrewpeterprifer** [comment]
I think an okay temporary solution would be if for now (until the version selector is done) the dev.apollodata.com URL wouldn't redirect to the new site. I can see why redirecting might seem necessary to help avoid confusion for newcomers, but I think a bigass red banner (like [this one](http://webpack.github.io/docs/)) would do the job just as well. Suddenly removing the (easily accessible) documentation -- especially for a stable, production-ready version -- is in my opinion really bad idea.
