### ISSUE TITLE
Send Accept application/json in HTTP request

### ISSUE THREAD

**Issue by danielstahl** [apollographql/apollo-client#2579]
**Intended outcome:**
Include Accept header with only application/json in all HTTP requests.

**Actual outcome:**
The apollo client includes a Accept header today with "`*/*, application/json`". This may make the server prefer some other format over json. 

**How to reproduce the issue:**
Make a Apollo client and make a query request.

**Version**
- apollo-client@2.0.2

**Comment by lujakob** [comment]
Can you set the "headers" explicitly with Network layer Middleware as described in the [docs](https://www.apollographql.com/docs/react/basics/network-layer.html#linkMiddleware) for the "authorization headers". For example:

`
const authMiddleware = new ApolloLink((operation, forward) => {
  // add the authorization to the headers
  operation.setContext(() => {
    const token = localStorage.getItem(GC_AUTH_TOKEN)
    return {
      headers: {
        accept: 'application/json'
      }
    }
  })

  return forward(operation);
})
`

**Comment by danielstahl** [comment]
Thanks for the tip. That could work. I think it would be a good idea though to have the default set to "application/json" just to avoid these kinds of situations.
