### ISSUE TITLE
Chore: straighten out dependencies upon `graphql`

### ISSUE THREAD

**Issue by jamesreggio** [apollographql/apollo-client#2580]
Nearly all of the packages in this project utilize AST types from the FB-owned `graphql` library.

However, the way that each package declares its dependency is inconsistent, and potentially problematic.

* `apollo-cache` utilizes `graphql` but doesn't list it as a dependency.
* `apollo-cache-inmemory` utilizes `graphql`, but lists it as a `devDependency` and omits any instructions about needing to explicitly install it.
* `apollo-link-batch-http` utilizes `graphql` and lists it as a proper `dependency`, but (having only spotchecked) it appears that no other link packages explicitly depend upon `graphql`.

Much like how `graphql-utilities` is an explicit `dependency` for most of these packages, I think `graphql` should also be listed as an explicit `dependency` (and then effort should be taken to lock to the same version of `graphql`, to prevent multiple versions from being pulled in).

**Comment by jamesreggio** [comment]
Probably should still take a look at this.

**Comment by jbaxleyiii** [comment]
This should be sorted out now!
