### ISSUE TITLE
[2.0] subscribeToMore unsubscribe after first data | bug

### ISSUE THREAD

**Issue by seeden** [apollographql/apollo-client#2581]
I have simple react component with graphql decorator. When component was mounted I am doing subscribeToMore. I will receive first data but immediately after that subscription it stoped working. Component was not unmounted. Am I doing something wrong @jbaxleyiii ? Thank you

```js
@graphql(gql`
  query getUserQuestions($username: String!) {
    user(username: $username) {
      id
      questions {
        edges {
          node {
            id
            question
          }
        }
      }
    }
  }
`, {
  options: ({ match: { params: { username } } }) => ({
    variables: {
      username,
    },
  }),
})
class Test extends Component {
  componentWillMount() {
    const { subscribeToMore, user } = this.props.data;

    this.subscription = subscribeToMore({
      document: SubscribeQuestionAddedQuery,
      variables: {
        username: user.username,
      },
      updateQuery: (prev, { subscriptionData }) => {
        const { data } = subscriptionData;
        if (data && data.questionAdded) {
          this.questionAdded(data.questionAdded);
        }
        return prev;
      },
    });

    console.log(this.subscription);
  }
  ...
}
```

Here you can see frames from websocket:
![websocket](https://i.imgur.com/6RA0w3B.png)

As you can see command "stop" is send after first data. Component was not unmount.

```js
    "apollo-cache-inmemory": "^1.1.1",
    "apollo-client": "^2.0.3",
    "apollo-link": "^1.0.3",
    "apollo-link-http": "^1.2.0",
    "apollo-link-batch-http": "^1.0.1",
    "apollo-link-retry": "^1.0.1",
    "apollo-link-dedup": "^1.0.2",
    "apollo-link-ws": "^1.0.1",
    "apollo-utilities": "^1.0.2",
```

**Comment by seeden** [comment]
It will subscribe again when I call subscribeToMore again but you know it is buggy :(

**Comment by seeden** [comment]
Subscribe is automatically unsubscribed with client.subscribe as well after first data.

```js
this.subscriptionObserver = this.props.client.subscribe({
      query: gql`
         subscription questionAdded($userId: ID) {
           questionAdded(userId: $userId) {
             id
             question
          }
       }
      `,
      variables: {
        userId: user.id,
      },
    }).subscribe({
      next(data) {
        console.log(data);
      },
      error(err) { console.error('err', err); },
    });

**Comment by seeden** [comment]
I did some research. The problem is in the apollo-link-dedup 
https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-dedup/src/dedupLink.ts#L73

**Comment by andershammar1** [comment]
Has there been any updates to this issue? We are seeing exactly the same problem in our codebase when introducing apollo-link-state to our link chain. If there is any know workaround, then please share it. Reverting apollo-link-dedup to 1.0.0 did not solve it for us.

**Comment by seeden** [comment]
any update ?

**Comment by hwillson** [comment]
Since this is an `apollo-link-dedup` issue, and is being tracked in https://github.com/apollographql/apollo-link/issues/259, I'll close it here. Thanks!
