### ISSUE TITLE
Class 'InMemoryCache' incorrectly extends base class 'ApolloCache<NormalizedCacheObject>'.

### ISSUE THREAD

**Issue by boomyao** [apollographql/apollo-client#2589]
**Intended outcome:**
const client = new ApolloClient({
  link: new HttpLink({ uri: 'https://api.example.com/graphql' }),
  cache: new InMemoryCache()
});

**Actual outcome:**
error TS2415: Class 'InMemoryCache' incorrectly extends base class 'ApolloCache<NormalizedCacheObject>'.  Types of property 'read' are incompatible.    Type '<T>(query: ReadOptions) => T | null' is not assignable to type '<T>(query: ReadOptions) => T'.
      Type 'T | null' is not assignable to type 'T'.        Type 'null' is not assignable to type'T'.

**How to reproduce the issue:**
create-react-app my-app --scripts-version=react-scripts-ts

**Version**
- apollo-client@2.0.3
- apollo-cache-inmemory@1.1.1
- react-apollo@2.0.1
- apollo-link-http@1.2.0

**Comment by adnsio** [comment]
#2592

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-client/issues/2589#issuecomment-345695096, this was resolved by https://github.com/apollographql/apollo-client/pull/2592. Closing - thanks!
