### ISSUE TITLE
Data Persistance

### ISSUE THREAD

**Issue by IronCoderXYZ** [apollographql/apollo-client#2600]
First off, I'd like to congratulate the Apollo team on the amazing job they have done so far, I've watched most of your presentations etc. and I'm excited to start using Apollo - but, I cannot.

I need data persistence, for which I was using Redux Persist, but I cannot find a way to integrate redux along with Apollo.

Has anybody found a workaround?

**Comment by n1ru4l** [comment]
@IronCoderXYZ Someone is working an a apollo-cache-redux implementation: https://github.com/rportugal/apollo-cache-redux

Also there will be meeting about `apollo-cache-asyncstorage` which lists localstorage on the agenda. (https://github.com/apollographql/apollo-cache-asyncstorage/blob/master/designs/meetings/11-17-17.md)
