### ISSUE TITLE
Unable to connect to local GraphQL Server running at localhost:PORT

### ISSUE THREAD

**Issue by akashbdj** [apollographql/apollo-client#2603]
I'm trying to connect to GraphQL server running at **http://MY_MACHINE_IP:PORT** using **apollo-client** and **react-apollo**.
I'm using **expo** to create React Native application and trying to run it on my **real device(iOS)**
It's working on iOS Simulator, though!

**Intended outcome:**
It should return proper response I was expecting. 

**Actual outcome:**
Network Error: Network Request Failed.

**Version**
- react-apollo: "^2.0.1",
- graphql: "^0.11.7",
- graphql-tag: "^2.5.0",
- apollo-client: "^2.0.3",
- expo: "^23.0.0",

**Screenshots:**

What I'm trying to do:

<img width="643" alt="screen shot 2017-11-19 at 11 16 09 pm" src="https://user-images.githubusercontent.com/7085282/33001368-7587010e-cdd3-11e7-974c-fcf7560564c6.png">

Error Screenshot:

<img width="570" alt="screen shot 2017-11-19 at 11 17 46 pm" src="https://user-images.githubusercontent.com/7085282/33001377-7ec89804-cdd3-11e7-91ed-75d60e046c95.png">

Please let me know if you need any more information.

Thanks

**Comment by michaelknoch** [comment]
Have you tried setting Uri to your local Network ip? E.g 192.168....

**Comment by akashbdj** [comment]
Yes! I already did -- still not working.

**Comment by jbaxleyiii** [comment]
@akashbdj can you open the network panel and see where the request is trying to go to?

**Comment by akashbdj** [comment]
Okay. This is completely weird. 😖

When both of my devices(laptop and mobile) are connected to our home wifi, I couldn't even remote debug my application. It keeps on saying, "It is taking too much time than it should". 😣

After a couple of try, I turned off my wifi and started using phone network(4G) and connected my laptop to it through hotspot.

Now, I can remote debug! Network request were also getting resolved. I was able to see the proper response. 🙄

May I know why is it happening with my WiFi? Anybody else facing the same issue?

**Comment by akashbdj** [comment]
I ended up using ngrok for development!

**Comment by RobertWSaunders** [comment]
@akashbdj I too was having this same issue on my home wifi, using ngrok solved it for me! Does anyone have the answer to this though? Seems weird...

**Comment by Kisepro** [comment]
Same for me.
It's working well on a browser but not on the app

**Comment by CasperCX** [comment]
Try adding cors on the graphql server:
add this before the graphql endpoints

`app.use(cors())`

**Comment by dadyl11** [comment]
Ss someone able to share the code after usage of Ngrok? I am not sure what I exactly have to do to make my client App (Apollo) working with the server that is running on the other laptop (Linux).

**Comment by kinxiel** [comment]
Issue already closed, but just encountered the same issue using Prisma. What resolved it on my side was to use the host machine's IP address : port on the server (Prisma) in the cors settings and also use the host machine IP : port (front) on the client.

**Comment by vprahaladhan** [comment]
> Same here. Using the latest apollo client 2.1
> 
> The only result I get is the Network Error:
> 
> import ApolloClient from "apollo-boost";
> const client = new ApolloClient({
> uri: "http://localhost:4000/graphql"
> });
> import gql from "graphql-tag";
> client
> .query({
> query: gql`{ user{ id name } }`
> })
> .then(result => console.log(result));

you don't need the '/graphql' in the uri; it has to be "http://localhost:4000"

**Comment by gpbaculio** [comment]
what worked for me is doing michaelknoch's suggestion, if you are on port 4000, e.g.: http://192.168.56.1:4000/

**Comment by bonovski** [comment]
I have similar issues with my containerized nextjs and strapi apps.

I can't connect if  I use` http://localhost:XXXX/graphql` or `http://127.0.0.1:XXXX/graphql`
`Error: request to http://localhost:3001/graphql failed, reason: connect ECONNREFUSED 127.0.0.1:3001`

If I use the local IP address of my PC  it works, but that is hardly practical.

Is apollo-client really unable to deal with localhost?

**Comment by omar-dulaimi** [comment]
For me neither local IP address nor ngrok worked. So instead of generating an ngrok for the frontend, I generated it for the backend so that it becomes https. Then connected to frontend through local IP. Now everything works well. Hope this helps someone, or me in the near future!

**Comment by GoldenMaximo** [comment]
In my case, I was using the Brave browser.

"Brave does not support network requests from Studio on HTTPS to your local HTTP endpoint, so we cannot introspect your endpoint.

There are a few solutions:
Turn Shields down in your Brave settings for https://studio.apollographql.com
Visit this page from a browser that supports HTTPS requests to local HTTP endpoints, like Chrome or Firefox.
Set up an SSL certificate for your local endpoint."

**Comment by ViktorCoder** [comment]
> In my case, I was using the Brave browser.
> 
> "Brave does not support network requests from Studio on HTTPS to your local HTTP endpoint, so we cannot introspect your endpoint.
> 
> There are a few solutions: Turn Shields down in your Brave settings for https://studio.apollographql.com Visit this page from a browser that supports HTTPS requests to local HTTP endpoints, like Chrome or Firefox. Set up an SSL certificate for your local endpoint."

Thanks)
