### ISSUE TITLE
writeQuery on object in store with missing property generates `errorHandling.js:7 Error: Can't find field <fieldname> on object (<$objectId>)`

### ISSUE THREAD

**Issue by KeithGillette** [apollographql/apollo-client#2606]
**Intended outcome:**

In a `DataProxy.writeQuery(…)` call within a function passed to the `update` property in `ApolloClient.mutate({…})`: Update a query that updates a property in an object already in the Apollo in-memory cache from a _different_ query  which did *not* include the given property.

**Actual outcome:**

Receive error of the form:
```
errorHandling.js:7 Error: Can't find field <fieldname> on object (<objectId>)`
```

**How to reproduce the issue:**

Given GraphQL types of the form:
```graphql
type ParentEntity {
	_id: ID!
	childList: [ChildEntity!]
}
type ChildEntity {
	_id: ID!
}
```
And queries of the form:
```graphql
query parentRead($parentId: ID!)  {
	ParentRead(parentId: $parentId) {
 		_id
	}
}
query childListRead($parentId: ID!)  {
	ParentRead(parentId: $parentId) {
		_id
		childList {
			_id
		}
	}
}
```
And a mutation update method of the form:
```typescript
…
this.apollo.mutate({
	mutation: childCreateMutation,
	variables: {parentId: someParentId, childId: someChildId},
	update: (apolloClientDataProxy: DataProxy, {data: {ChildCreate}}: ApolloQueryResult<IChildCreateResponseData>): void => {
	const childListReadQueryData = apolloClientDataProxy.readQuery<IChildListReadQueryResponseData>({query: childListReadQuery, variables: {parentId: someParentId}});
	childListReadQueryData.ParentRead.childList = childListReadQueryData.ParentRead.childList ? [...childListReadQueryData.ParentRead.childList, ProcedureCreate] : [ProcedureCreate];
	apolloClientDataProxy.writeQuery({
		query: childListReadQuery,
		variables: {parentId: someParentId},
		data: childListReadQueryData
		});
	}
});
…
```
Given that an object with id _$parentId = someParentId_ exists in the cache from `parentRead` (which does not contain the `childList` property), the attempt to execute the `writeQuery` on `childListReadQuery` produces an error of the form:
```
errorHandling.js:7 Error: Can't find field childList on object (someParentId) {
   "_id": "someParentId"
}
 at readStoreResolver (readFromStore.js:39)
    at executeField (graphql.js:70)
    at eval (graphql.js:27)
    at eval (meteor-client.js:9182)
    at Array.forEach (meteor-client.js:9136)
    at executeSelectionSet (graphql.js:22)
    at executeField (graphql.js:80)
    at eval (graphql.js:27)
    at eval (meteor-client.js:9182)
    at Array.forEach (meteor-client.js:9136)
```

**Version**
- apollo-client@2.0.3
- apollo-cache-inmemory@1.1.1

**Comment by jay1337** [comment]
Same issue here with a React Component wrapped with a query. When some data is written into the store, if a field is missing an error occurs when `readQuery` function of Apollo Client is called (when Apollo check if component data has changed).

**Comment by hwillson** [comment]
Any chance you can put together a small runnable reproduction that shows this happening? Thanks!

**Comment by hwillson** [comment]
We haven't heard back regarding a reproduction, so closing for now. Thanks!

**Comment by jay1337** [comment]
Everything is explained to reproduce the issue !

**Comment by hwillson** [comment]
@jay1337 Explaining how to reproduce an issue is not the same as providing a runnable reproduction for an issue. I know it's a pain, but providing a small runnable reproduction helps issue triagers pinpoint the exact problem faster. Not to mention that whoever uncovers a bug is already in the middle of it, and usually has a better understanding of how to reproduce it. Describing a problem then hoping that an issue trigger understands it enough to 1) build a reproduction that clearly shows the problem, then 2) work on a fix, is not ideal. Long story short - if you want an issue reported here resolved in a timely manner, by an issue trigger or community contributor, then providing a small runnable reproduction is your best chance at making that happen. If you or anyone else is able to provide a repro, we'll re-open this issue. Thanks!

**Comment by KeithGillette** [comment]
@hwillson, is there a StackBlitz-able base project with a basic working ApolloClient setup on which such reproductions could be easily based?

**Comment by hwillson** [comment]
@KeithGillette We provide a few options:

1. Use the `apollo-client` / `react-apollo` error template: https://github.com/apollographql/react-apollo-error-template. This option doesn't require a GraphQL endpoint (you can mock out your schema in the app - details in the repo).
2. Use this codesanbox, which is connected to a default [Apollo Launchpad](
https://launchpad.graphql.com) instance: https://codesandbox.io/s/7361K9q6w

**Comment by jay1337** [comment]
@hwillson I agree that an issue that can't be reproduced should be closed, but an issue that nobody has time to reproduce it's something else. Feedback from users is invaluable. And it's not always straightforward to make a repro from a code that raises an issue. Sometimes you have a really big project (with several applications, private code, data, ...) and you can't just remove 2 or 3 things and upload it has a repro. And quite often you can find a bug really quickly just by having a look at a code that you know very well, without any repro.

**Comment by hwillson** [comment]
All valid points @jay1337. Unfortunately, nothing has jumped out at anyone who has seen this issue since last November, so the chances of any further progress being made here without a reproduction, are quite slim. That's why I've closed it. If anyone comes across this and the issue jumps out at them though, great! For now though we're kicking our issue triage process into high gear, and starting to clamp down on issues that have sat open for a while, and have little chance of being addressed without additional details. This is all part of making sure that the issues that remain open are ready to be worked on, both by the Apollo team and community.
