### ISSUE TITLE
Document how to do side-effects after a mutation

### ISSUE THREAD

**Issue by entropitor** [apollographql/apollo-client#2609]
The docs clearly mention that `update` should not be used for side-effects (https://www.apollographql.com/docs/react/features/caching.html#updating-the-cache-after-a-mutation), however it's lacking what should be used instead. 

Is it a good idea to handle the side-effects when the promise resolves/rejects?

**Version**
- apollo-client@2.0.0

**Comment by jbaxleyiii** [comment]
@entropitor what kind of side effects are you wanting to do? Generally yes the promise resolution is the best place to do it as `update` is called multiple times

**Comment by entropitor** [comment]
Examples could include:
- loading other stuff
- saving some things to AsyncStorage
- Dispatching a redux action

**Comment by entropitor** [comment]
(I've updated the issue title as I think it's clear to me now, but I think it should be included in the docs for other people. Or it should include why it's a bad idea to have side-effects anyway)

**Comment by jbaxleyiii** [comment]
@entropitor there is nothing wrong with side-effects for sure! Yeah we could stand to improve the docs around how to do this. Would you be up to contribute those if I help?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Document%20how%20to%20do%20side-effects%20after%20a%20mutation&body=Migrated%20from:%20apollographql/apollo-client%232609) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
