### ISSUE TITLE
Teething issues with getting started instructions

### ISSUE THREAD

**Issue by M-Zuber** [apollographql/apollo-client#2610]
When trying to get started contributing, I ran `npm install` and `npm test` per the instructions in the README

The tests failed due to Jest being a peerDependancy of ts-jest and thus needing manual installation.

Additionally `npm run build` has to be run before the test will work properly

Should the README be updated with commands to install jest and run the build, or should a script be added to the `package.json` that will take care of these?

**Comment by jbaxleyiii** [comment]
@M-Zuber I'm so glad you brought this up! There is a TON to be done to make it easy to contribute! It is actually the goal of my current sprint that just started! I'll be working to make this much better and would love feedback as it comes down the pipe!

**Comment by M-Zuber** [comment]
I'm happy to try and help
In this case, what direction would you prefer, only changing the docs, or also adding a script?

**Comment by hwillson** [comment]
Thanks for reporting this. The [Contributing](https://github.com/apollographql/apollo-client/blob/6344cd86fe25a325fb376cbb8f2bd93d3098dfa8/README.md#contributing) section of the `README.md` has been updated to list all of the steps needed to get the tests running:

```
npm install
npm run build
npm test
```

We're working on a new `apollo-client` developer guide, that will help new contributors get up and running quickly. Thanks!
