### ISSUE TITLE
React Native + Hot Reload (HMR) results in red screen after request with error

### ISSUE THREAD

**Issue by monotv** [apollographql/apollo-client#2612]
**Intended outcome:**
Hot Reload working the same as manual reload (no red screen with handled error prop).

**Actual outcome:**

![Red screen](https://i.imgur.com/S5c4FLE.png)

Hot Reload producing red screen even though the error prop is handled.

**How to reproduce the issue:**
Implement GraphQL query that results in an error (for example 401), load app in iOS simulator, make sure manual reload works, trigger Hot Reload.

**Version**
- "apollo-client": "^2.0.3"
- "react-apollo": "^2.0.1"
- "react-native": "0.49.3"

**Comment by hwillson** [comment]
If this is still a problem, would you mind reporting this over in the https://github.com/apollographql/react-apollo repo? Issues here are reserved for problems with the `apollo-client` project specifically. Thanks!
