### ISSUE TITLE
MockNetworkInterface in v2

### ISSUE THREAD

**Issue by TimoGlastra** [apollographql/apollo-client#2623]
Hi,

How would one go about mocking a networkinterface in v2 of apollo? In v1 it was documented, but i haven't found anything for v2. apollo-test-utils also isn't updated for v2. What is the best way to do this in v2?

ATM i'm bypassing apollo by, using the component without the 'graphql' HOC, manually passing props but this isn't ideal. 
I also tried it with a graphql endpoint on a server with mock data (addMockFunctionsToSchema) but react-test-renderer wouldn't wait till the data was loaded, so every component will have the 'loading' parameter to true, without data.

**Version**
- apollo-client@2.0.3

**Comment by jpabbuehl** [comment]
same issue
the new v2 ApolloClient doesn't accept anymore networkInterface: mockNetworkInterface

**Comment by n1ru4l** [comment]
Apollo V2 uses links instead of networkInterfaces. You can create a link  that executes against a local graphql schema. The apollo-error-template is a good example: https://github.com/apollographql/react-apollo-error-template/blob/master/src/graphql/link.js

**Comment by TimoGlastra** [comment]
Than you for the answer! this is really helpful. Sorry about the duplicate, will close this now.
