### ISSUE TITLE
Adding a logger in dev mode

### ISSUE THREAD

**Issue by abhiaiyer91** [apollographql/apollo-client#2624]
Would we be interested in a logger in the new cache for tracking cache updates?

**Comment by abhiaiyer91** [comment]
Also I'm willing to do the work for this feature! If @jbaxleyiii could give me a spec or direction, I can execute that vision!

**Comment by jbaxleyiii** [comment]
@abhiaiyer91 can you outline some of what you would like to log, and what you would want to do with the log? I'm all for it (even beyond dev mode potentially!)

**Comment by abhiaiyer91** [comment]
Sure thing:

I'd like to log:

1. Query
* Query, Operation Name, variables
* Query Results
2. Mutation
* Mutation, Operation Name, variables
* Mutation Results
3. Cache Writes/Reads
* Query, Operation Name, variables
* data being set
4. Time between Init to Result

**Comment by 0xcaff** [comment]
What do you think about adding this information to the apollo dev tools instead of just logging it to the console?

**Comment by abhiaiyer91** [comment]
Sure why not both though?

**Comment by brunoreis** [comment]
Errors are very important also. I think you could have a generic logger object and this could be sent to dev tools if needed. I started something similar to that and created a UI for that because I'm using React Native and dev tools do not work remotely yet.

**Comment by vlasenko** [comment]
Hi Guys, I have put together initial Apollo Cache logger implementation with error logging and customizable  `logger` and `formatter` here, in case someone wants to log Apollo Cache access now:
https://github.com/sysgears/apollo-cache-logger

You might also check
https://github.com/sysgears/apollo-cache-router
which lets you split your Apollo Cache into multiple caches, for example to store all server state in one Apollo Cache and all client-side `apollo-link-state` state into another cache and reset them separately.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Adding%20a%20logger%20in%20dev%20mode&body=Migrated%20from:%20apollographql/apollo-client%232624) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
