### ISSUE TITLE
QUESTION: Custom Scalar Support in Apollo 2.0

### ISSUE THREAD

**Issue by serle** [apollographql/apollo-client#2626]
Currently, what is the recommended approach to handling custom scalars in Apollo 2 OR Is it possible to instruct apollo-client to apply a particular conversion on a given query field. I know this question has been asked in the past, but has there been any movement on this now that Apollo 2.0 is here. Is there any best practice OR can we get some heads up on what is coming in this regard.

**Comment by ste93cry** [comment]
I would like to know the answer too, for example I have a custom GraphQL type that represents date/time and is formatted in ISO8601. Obviously over the wire this is transferred as a string, but in the client it would be nice to have it converted automatically to a Javascript Date object from the query results.

**Comment by jamiewinder** [comment]
I've just been looking into how to do exactly this. I'd add, it'd be nice to be able to handle things like dates through a library rather than using JavaScript's own `Date` (e.g. parse with moment / luxon / js-joda).

Would it need to handle conversions in the opposite direction (e.g. for mutations)?

**Comment by jonaskello** [comment]
This [blog post](https://dev-blog.apollodata.com/whats-coming-in-apollo-client-2-0-bcd8ea64acbd) is the only mention of custom scalars for 2.0 that I can find. It says:

> When combined, links and custom stores can be used for incredible new features. 
> * Parsing of custom scalars like Dates

**Comment by rlech** [comment]
Custom Scalars are very important and usefull for Mutations where the input can be a custom InputType

**Comment by rikas** [comment]
+1 in desperate need of scalars support!

**Comment by ThisIsMissEm** [comment]
@peggyrayzis looks like this is a duplicate issue of #585

**Comment by hwillson** [comment]
Now being tracked in https://github.com/apollographql/apollo-feature-requests/issues/2. Thanks!
