### ISSUE TITLE
Feature request: Objects in the cache

### ISSUE THREAD

**Issue by pcafstockf** [apollographql/apollo-client#2627]
Sometimes it is useful to have objects as opposed to just data (calculated fields for example).

Allowing for config of the resultMapper function in the apollo-cache-inmemory package (similar to defaultDataIdFromObject) would allow an override of the resultMapper to do something like this:
```
defaultConfig: ApolloReducerConfig = {
    resultMapper: function (values, rootValue) {
        if (values.__typename === 'Foo')
            values = Object.assign(new Foo(), values);
        defaultResultMapper(values, rootValue);
    }
}
```

**Comment by nevir** [comment]
@pcafstockf while it's a bit early (and not well documented yet), you might want to take a look at https://github.com/convoyinc/apollo-cache-hermes which can do this for ya

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-client/issues/2627#issuecomment-349813354, please see one of the alternative third party `apollo-cache` implementations. Supporting this use case is not currently planned for `apollo-client`. Thanks!
