### ISSUE TITLE
Subscribe to Same Subscription with Multiple ids?

### ISSUE THREAD

**Issue by gijo-varghese** [apollographql/apollo-client#2633]
I have a subscription like this:

```
$subscribe: {
      newMessage: {
        query: NEW_MESSAGE,
        variables() {
          return {
            page_id: this.page[0].id
          };
        }
      },
}
```
Basically it subscribes to new message in a 'page'. Is it possible to add multiple subscription? The subscription will be same, but I want to subscribe to page[1].id, page[2].id etc (every pages inside the page's array)

Note: I'm using vue-apllo

**Comment by n1ru4l** [comment]
Couldn't you just send an array of ids instead of a single id?

Could you please provide some more info about the schema and what those pages represent?

**Comment by gijo-varghese** [comment]
@n1mmy yup! array of ids is what I was looking for! https://github.com/Akryum/vue-apollo/issues/156
