### ISSUE TITLE
Feature idea: normalize and reuse cache

### ISSUE THREAD

**Issue by bondz** [apollographql/apollo-client#2646]
I have the schema

```graphql
type Query {
  allBooks: [Book]
  book(id: String!): Book
}

type Book {
  id: String!
  bookName: String
  authorName: String
}
```

On the client I have two components on a MasterDetail like page
```jsx
const AllBooksContainer = ({ allBooks }) => (
  <>   
    <BookList onClick={changeBookID} />
    <Book bookID={currentlySelectedBookID} />
  </>
);
```

That fetches data using the query

```graphql
{
  query AllBooks {
    allBooks {
      id
      ...BookComponent
    }
  }
  ${BookComponent.fragments.book}
}
```

The component `Book` is a container that fetches data using the query 

```graphql
{
  query Book($bookID: String!) {
    book(id: $bookID) {
      ...BookComponent
    }
  }
  ${BookComponent.fragments.book}
}
```

This is like a lazy prefetch, I assume that the user would click on a book, so instead, fetch all the data the `Book` component needs from the `allBooks` component.

**Currect Behaviour**
Two requests are sent to the server when the bookID changes though the `allBooks` component should have primed the cache with all the data the `Book` component needs.

**Expected behaviour**
Only one request should be sent to the server, the remaining data should be fetched from cache under the fetchPolicy `cache-first` and `cache-only`

**Version**
- apollo-client@2.0.3

**Comment by brunoreis** [comment]
take a look at this: https://www.apollographql.com/docs/react/features/cache-updates.html#cacheRedirect

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-client/issues/2646#issuecomment-370542954, leveraging [`cacheResolvers`](https://www.apollographql.com/docs/react/advanced/caching.html#cacheRedirect) should help with this. Closing - thanks!
