### ISSUE TITLE
No error and no result

### ISSUE THREAD

**Issue by mloureiro** [apollographql/apollo-client#2647]
### Intended outcome:

There are 2 possible options here, when there's an issue with a property from the server GraphQL makes an error for it, although it still returns the document as expected. 
So Apollo should return the document and network status 7 (ready), or fail with network status 8 (error).

### Actual outcome:

It fails silently. Basically, it says network status 7, but query results are not there.

### How to reproduce the issue:

Couldn't manage to reproduce it in launchpad.
But got this query: 

```gql
query ($id: Int!) {
  service_request(id: $id) {
    id,
    details {
      answer
    }
}
```

and I get this response in another client:

```json
{
  "errors": [
    {
      "message": "An error occurred, please retry later or contact us!",
      "locations": [
        {
          "line": 5,
          "column": 6
        }
      ],
      "path": [
        "service_request",
        "details",
        6,
        "answer"
      ]
    }
  ],
  "data": {
    "service_request": {
      "id": 100,
      "details": [
        {
          "answer": "Somewhere"
        },
        {
          "answer": null
        }
      ]
    }
  }
}
```

The error happens on the backend an exception trying to convert an object answer to string, so it fails but still outputs the result.

### Version

- apollo-client@2.0.1
- apollo-link-http@1.0.0,
- react-apollo@2.0.0

**Comment by hwillson** [comment]
This sounds like an [error policy](https://www.apollographql.com/docs/react/features/error-handling.html#policies) issue. Without a reproduction though, this will be difficult to help troubleshoot further. If you're able to put together a small runnable reproduction that shows this happening (you can use this [error template](https://github.com/apollographql/react-apollo-error-template) as a starting point), that would be great! Closing for now - thanks!
