### ISSUE TITLE
QUESTION: Concurrent queries in same ApolloProvider?

### ISSUE THREAD

**Issue by petergarnaes** [apollographql/apollo-client#2662]
**Short version** 

see title.

**Long version**

So I am making a typical web app, with a navigation bar and a page with some content. The page have one query pulling a lot of user related data, and the navigation bar have a query pulling username and some other stuff to find out what navigation items should be visible. These queries are concurrent within the same ApolloProvider, but share the same root and a few fields, so the store has to merge these queries.

My issue is that I run into bizzare errors where networkStatus = 7 but my data is undefined, or the app deadlocks when processing a network request.

In my attempt to hunt down the bug, I was wondering if concurrency could be the cause? Cannot find anything in documentation either endorsing or prohibiting this...

**Version**
- apollo-client@2.0.1

**Comment by rushproject** [comment]
Very similar case here - two queries (user info for app bar, model entity for page content), if executed concurrently (e.g. opening deep link or browser page reload) I see extra call to render() method with networkStatus =1 and no network activity. The behavior is greatly affected by timing - injecting extra console.log calls into render() might fix the problem. Sounds like racing condition.

apollo-client 2.1.0
react-apollo 2.0.1

**Comment by n1ru4l** [comment]
A minimal reproduction example would be helpful. 

You cloud use https://github.com/apollographql/react-apollo-error-template to provide one.

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-client/issues/2662#issuecomment-349269309, a reproduction here would definitely be helpful. That being said, if this is still a problem, would you mind reporting this over in the https://github.com/apollographql/react-apollo repo? Thanks!
