### ISSUE TITLE
Apollo-Client 2.1.0 @live directive failed.

### ISSUE THREAD

**Issue by shtse8** [apollographql/apollo-client#2663]
I am using `@live` directive in my site. It works well in 2.0.1 and 2.0.2 but failed in 2.1.0 and 2.0.3.
the client will not wait for next data and send a stop command to the server even there is a `@live` directive.

**Comment by shtse8** [comment]
I believe this commit break the @live directive support.
https://github.com/apollographql/apollo-client/commit/b15c103f0b203fccbfd0c75a2446092177b43f8c

**Comment by hwillson** [comment]
This doesn't seem to be a common problem @shtse8 - is this still an issue for you? Let us know if so, and if you can provide a small runnable reproduction that shows how this is a problem (using version >= 2.3.2 of `apollo-client`), that would be awesome. Closing for now - thanks!
