### ISSUE TITLE
Mocking fetch requests (fetch-mock)

### ISSUE THREAD

**Issue by ianrtracey** [apollographql/apollo-client#2671]
Hey Team!

Awesome job on 2.0!

I am amidst the upgrade process from 1.x -> 2.0 and am running into some issues with mocking fetch requests in my resolvers.

I am using apollo-client to execute queries locally using a custom LocalLink (almost identical to this: https://github.com/nick/boulder-vote/blob/master/src/ApolloLinkLocal.js) and am trying to use fetch-mock to mock fetch requests in my resolvers.

My testing configuration with fetch-mock worked for Apollo Client 1.x and I am lost as to why it doesnt work anymore and what the best solution is moving for mock fetch requests. My suspicion is the migration from networkInterface in my apollo client to a link affects how fetch-mock is able to access fetch requests.

Any insight anyone might have would be greatly appreciated.

**Comment by jabberfest** [comment]
@ianrtracey did you ever find a solution? I'm running into the same issue.
