### ISSUE TITLE
Cache matching 'many of X' query result with individual 'X' result

### ISSUE THREAD

**Issue by jamiewinder** [apollographql/apollo-client#2686]
I'm new to Apollo and GraphQL and trying to figure out how to get caching working effectively. I'm using this with a PostGraphQL server.

If I've got a table of 'Account' in my database (`id int PK, name text`), PostGraphQL gives me 'account(nodeId)', 'allAccounts', and 'accountById(id)' to query. 

If run the `allAccounts` query...
```
{
    allAccounts {
        nodes { id, name }
    }
}
```
... then I'll get back all of the accounts.

However, if I then run an `accountById` query...
```
    query ($id: BigInt!) {
        accountById(id: $id) {
            id, name
        }
    }
```
... with an ID I got back from the first then it queries the server again for the same object. 

My expectation (correct me if I'm wrong) is that Apollo should be able to recognise that my first 'all accounts' query already retrieved this data and so there is no need to request it. This seems to be the case for the same query (if I run either of these queries again, the result comes from the cache). 

That said, it occurs to me that this isn't possible unless Apollo knows that `allAccounts` returns a set of 'Account' and `accountById` returns a singular account (and that the `id` field is the identifier, though I gather this is the default on the in-memory cache). 

So do I need to tell Apollo my schema in order for this to work, or is this scenario not supported anyway?

Thanks.

**Comment by jamiewinder** [comment]
As usual, the answer seems to find me after I ask the question. The answer seems to be to use a cacheResolver...
```
        cacheResolvers: {
            Query: {
                accountById: (_, args) => toIdValue(cache.config.dataIdFromObject({
                    __typename: "Account",
                    id: args.id
                }))
            }
        }
```

**Comment by stubailo** [comment]
Yep, that's the answer! It's not possible to automatically determine the above without making an assumption about the underlying API. Please feel free to send any PRs to the docs that would help!
