### ISSUE TITLE
Why say using HOC's otpions in the recompose pattern is not very reusable?

### ISSUE THREAD

**Issue by goldenbearkin** [apollographql/apollo-client#2707]
From the docs https://www.apollographql.com/docs/react/recipes/recompose.html#other, it says

> Normaly if you need to add sideffect to mutate function, you would manage it in HOC’s options
> ->props part by doing something like { mutate: () => mutate().then(sideEffectHandler) }. But that is not very reusable. Using recompose’s withHandlers() you can compose same prop manipulation in any count of components.

then i follow the given link to a blog post, it demonstrates the use case when dealing with mutation.
```js
export default compose(
  injectIntl,
  graphql(mutation),
  withHandlers({
    toggleMutation: ({ mutate, _id, intl }: { mutate: Function, _id: string, intl: Object }): Function => {
      return (): Promise<any> => {
        return mutate({
            variables: {
              someId: _id,
            },
          }).then((data: string) => {
          console.log(data, 'Return value');
        }).catch((e: Object) => {
          console.error(e, 'Error');
        });
      };
    }
  })
)(MutationButton);
```

and i found the syntax is quite cumbersome. Why don't just 
```js
export default compose(
  injectIntl,
  graphql(mutation, {
    props: ({ mutate }) => ({
      toggleMutation: (_id: string, intl: Object) => mutate!({
        variables: { id, provider },
      }).then((data: string) => {
        console.log(data, 'Return value');
      }).catch((e: Object) => {
        console.error(e, 'Error');
      });
    }),
  }),

)(MutationButton);
```

Could the docs elaborate more on the benefit of using withHandlers()?

**Comment by abhiaiyer91** [comment]
From the post and recompose docs:

```
withHandlers takes a map of Higher Order Functions that accept props and return function handlers. Handlers are passed as immutable props and are preserved across renders. Thus, we avoid the pitfall of React components creating new handlers on every render. Furthermore, if you are trying to do any type of prop equality, these new renders will screw up your assumptions.
```

**Comment by abhiaiyer91** [comment]
Though my blog post was just exploring how I write my mutation UI. I dont think the docs are demonstrating `reusability` by mentioning the post

**Comment by goldenbearkin** [comment]
Thanks @abhiaiyer91 

I am new to recompose pattern. Could you explain more about the different between options props from graphql and withHandler? are you saying with graphql options props, the mutation function is not passed as immutable props and are not preserved across renders? I just wonder why introduce withHandler if we have a shorter and cleaner syntax (option props) which we have been using?

**Comment by ShockiTV** [comment]
I wrote it that way, cause by hardcoding it in graphql HoC you are coupling your `withSomeMutation` HoC with the side effect itself.
When I do separate `graphql` and `withSideEffect` HoCs, I can run the mutation without the side effect by just not composing the `withSideEffect` HoC in some places.

**Comment by goldenbearkin** [comment]
Thanks @ShockiTV 

If I haven't got wrong, are you saying that there are some cases that only run the graphql(mutation) HoC without use its handler to do some side effect? or you just want to a align with the graphql(query) HoC?

could you give some examples of running mutation without the side effect?

**Comment by ShockiTV** [comment]
Yes, just decoupling.
Examples, well, there could be 2 UI components calling same mutation, but you want to track 2 different Google Analytics actions. So you reuse the graphql mutation (it could have options other than props so you dont wanna copypaste 20 lines of vaariables and other computation parts raw into compose, but prepare some `withClickMutation` HoC) and you can prepare separate HoC which you use like this withGASideffect("clicked first button"). And for 2nd component you can still use `withClickMutation` HoC, but this time compose it with withGASideffect("clicked second button")

**Comment by goldenbearkin** [comment]
awesome! thanks @ShockiTV
