### ISSUE TITLE
apollo client 2.0.4, how get the store, from new onError , apollo-link-error

### ISSUE THREAD

**Issue by webmobiles** [apollographql/apollo-client#2708]
I'have migrated from apollo 1, all it's working well , but just errors, with apollo 1 I used to catch the errors on my mutate action,  and inside I had props, to  call translate, redux saga and another   states to show errors and change the behaviour  accord errors. with apollo2 looks different.

 my problem is get the state from my redux inside the new 
onError ;, that is imported with  : import { onError } from 'apollo-link-error';

```
const errorLink = onError((Error) => {
  console.log('store',store.getState());  // does not work
  (..)
}
```

on my app.js

```
      <ErrorBoundary>
        <Provider store={store} >
          <ApolloProvider client={client}>
            <BrowserRouter>
              <Switch>
```

i'm doing well have apolloprovider inside Provider(redux) ?  this the only thing to send my new project in new version 2 that looks fantastic. 

**Version**
    "react-apollo": "2.0.4",

**Comment by ahmad2smile** [comment]
I just feel like someone got to say this. So @eliasturbay "Are you retarded?". You really thought his problem was exporting store object and then importing it?

**Comment by ahmad2smile** [comment]
@apollographql guys are just pretending in their every answer like @redux doesn't even exist. It frustrating.

**Comment by webmobiles** [comment]
@ahmad2smile  thanks i could not really to follow the elias solution.... yes, very frustating, apollo and cache with 4000 record got very crazy, finally I think i'm going to build my own apollo cliente and my own cache .... there are plenty of problems and scenarys, i don't think apollo team could really all solve

**Comment by ahmad2smile** [comment]
All I'm asking of apollo team that they would be open about things. If they wanna kill the redux sure just mention it in the docs. If they provide some sort of integration just let us know how. Rather they are saying you don't need redux. My whole project is done with redux. There isn't a single bit that moves in my code without redux store. How would I just won't need redux. Thats insane.

**Comment by ahmad2smile** [comment]
@webmobiles you don't need to build a client just use axios to send post request on /graphql end point and put your queries as data for the post request.

**Comment by ahmad2smile** [comment]
The cacheing thing is tricky. I'm thinking about doing a cache implementation with reselect lib and some calculations on my part to detect the diff b/w requests

**Comment by hwillson** [comment]
This is a React Apollo issue, and is being tracked here: https://github.com/apollographql/react-apollo/issues/1360 (see workaround in https://github.com/apollographql/react-apollo/issues/1360#issuecomment-347556125). Since this is already being tracked in the React Apollo repo, I'll close it here. Thanks!
