### ISSUE TITLE
fetchMore lack of generic type support

### ISSUE THREAD

**Issue by ianrtracey** [apollographql/apollo-client#2714]
During the upgrade of Apollo Client 2.0, I ran into the issue of a typed updateQuery in a fetchMore function not passing type checking anymore.

Assume a type MemberQuery exists:
```typescript
export type MemberQuery {
  organisation: { ... } 
  ...
}
```

And in the `props` function of the component:
```typescript
loadMore async (page: number) => fetchMore({
  ...
  updateQuery: (previousResult: MemberQuery, { fetchMoreResult }: { fetchMoreResult: MemberQuery }) => { .. }
})
```
I get the following error `organisations can not be found in {[key: string]:  any}`

Not sure what would have changed in the new version that would cause this to not pass type checking. My assumption is that fetchMoreOptions's signature is causing the inflexibility because a type of `{[key: string]:  any}` can't be declared as a type where the keys could deviate from that type.
```typescript
export interface FetchMoreOptions {
    updateQuery: (previousQueryResult: {
        [key: string]: any;
    }, options: {
        fetchMoreResult?: {
            [key: string]: any;
        };
        variables: {
            [key: string]: any;
        };
    }) => Object;
```
If I un-type the param variables and cast them using `const fetchMoreResultMemberQuery = fetchMoreResult as MemberQuery` then it works because its being cast to that type.

Is there a reason that the signature for FetchMoreOptions doesnt support generics? (I am willing to submit a PR for the generic support if its a matter of a lack of dev resources).

**Comment by hwillson** [comment]
Generics have been added to `FetchMoreOptions` since this issue was created, so we should be all set here. Thanks!
