### ISSUE TITLE
Fails to return result when using only fragment spreads in query operation

### ISSUE THREAD

**Issue by jonaskello** [apollographql/apollo-client#2720]
**Issue description**

I'm trying to run [this query](http://graphql.org/swapi-graphql/?query=query%20MyQuery%20%7B%0A%20%20...TheFilms%0A%20%20...ThePeople%0A%7D%0A%0Afragment%20TheFilms%20on%20Root%20%7B%0A%20%20allFilms%20%7B%0A%20%20%20%20films%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20title%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0Afragment%20ThePeople%20on%20Root%20%7B%0A%20%20allPeople%20%7B%0A%20%20%20%20people%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=MyQuery) against the swapi demo server with apollo-client:

```
query MyQuery {
  ...TheFilms
  ...ThePeople
}

fragment TheFilms on Root {
  allFilms {
    films {
      id
      title
    }
  }
}

fragment ThePeople on Root {
  allPeople {
    people {
      name
    }
  }
}
```

**Intended outcome:**

I expect apollo-client to return the same result as GraphiQL:

```
{
  "data": {
    "allFilms": {
      "films": [
        {
          "id": "ZmlsbXM6MQ==",
          "title": "A New Hope"
        },
        {
          "id": "ZmlsbXM6Mg==",
          "title": "The Empire Strikes Back"
        },
        ...
      ]
    },
    "allPeople": {
      "people": [
        {
          "name": "Luke Skywalker"
        },
        {
          "name": "C-3PO"
        },
        ...
      ]
    }
  }
}
```

**Actual outcome:**

apollo-client returns this:
```
{ data: {}, loading: false, networkStatus: 7, stale: false }
```

**How to reproduce the issue:**

[Here]() is a repo with code that reproduces the issue.

Here is the code to reproduce:

```js
async function main() {
  const ApolloClient = require("apollo-client").ApolloClient;
  const HttpLink = require("apollo-link-http").HttpLink;
  const InMemoryCache = require("apollo-cache-inmemory").InMemoryCache;
  const fetch = require("node-fetch");
  const gql = require("graphql-tag");

  const client = new ApolloClient({
    link: new HttpLink({
      uri: "http://graphql.org/swapi-graphql",
      fetch: fetch
    }),
    cache: new InMemoryCache()
  });

  const query = gql`
    query MyQuery {
      ...TheFilms
      ...ThePeople
    }

    fragment TheFilms on Root {
      allFilms {
        films {
          id
          title
        }
      }
    }

    fragment ThePeople on Root {
      allPeople {
        people {
          name
        }
      }
    }
  `;

  const result = await client.query({ query });
  console.log("result", result);
}

main();
```

**Version**
- apollo-client@2.0.4

**Comment by jaydenseric** [comment]
Duplicates https://github.com/apollographql/apollo-client/issues/2512?

**Comment by jonaskello** [comment]
I found today that this only happens when you have a query operation that only has fragment spreads and nothing else. If I add something more then it works and the spreads are also resolved.

**Comment by hwillson** [comment]
This should have been fixed by https://github.com/apollographql/apollo-client/pull/3507. Let us know if this is still a problem. Thanks!
