### ISSUE TITLE
Add warning message when a component can't render

### ISSUE THREAD

**Issue by gaetansnl** [apollographql/apollo-client#2721]
If I have this query on `MyComponent`
````
objectA(id:$id){
 id,
 subobject{
    id,
    somefield
 }
}
````
And if I do a mutation and my mutation result look like this
````
objectA{
 id,
 subobject{
    id
 }
}
````

If the `subobject` id is updated during the mutation, `MyComponent` can't render because I don't fetch `somefield`.

**Intended outcome:**
Something to tell me why the component doesn't render anymore

**Actual outcome:**
The exception is ingnored in `QueryManager.prototype.getCurrentQueryResult`

````javascript
 try {
                var data = this.dataStore.getCache().read({
                    query: query,
                    variables: variables,
                    previousResult: lastResult ? lastResult.data : undefined,
                    optimistic: true,
                });
                return apolloUtilities.maybeDeepFreeze({ data: data, partial: false });
            }
            catch (e) {
                return apolloUtilities.maybeDeepFreeze({ data: {}, partial: true });
            }
````

**Version**
- apollo-client@<2.0.3

PS: I agree this error should not happen if I don't forget my fields, but sometimes it happens.

**Comment by hwillson** [comment]
This has been addressed by https://github.com/apollographql/apollo-client/pull/4743, and will be coming in Apollo Client 2.6. You can set `returnPartialData` to `true` to have previous partial cache results used, instead of having the returned data set to an empty object.
