### ISSUE TITLE
How to declare fragment in functional component in Typescript?

### ISSUE THREAD

**Issue by goldenbearkin** [apollographql/apollo-client#2722]
I can easily declare a fragment in a class component by adding a static method.

```js
export default class PokemonCard extends React.Component {

  static fragments = {
    pokemon: gql`
      fragment PokemonCardPokemon on Pokemon {
        url
        name
      }
    `
  }
  // ...
}
```

What is the best way to do the same in functional component in Typescript and pass the type checking?

```js
PokemonCard.fragments = {
  pokemon: gql`
    fragment PokemonCardPokemon on Pokemon {
      url
      name
    }
  `,
};
```

<img width="422" alt="screen shot 2017-12-13 at 11 00 24 pm" src="https://user-images.githubusercontent.com/11225712/33945257-7b5976b4-e059-11e7-8071-3b3c6d880c4f.png">

// error: 'fragments' does not exist on type 'typeof PokemonCard'

**Comment by danielrasmuson** [comment]
My understanding (feedback welcome) is that doing `ReactComponent.fragments` is [just a convention](https://www.apollographql.com/docs/react/features/fragments.html).

```
We put the fragment on CommentsPage.fragments.comment by convention, and use the familiar gql helper to create it.
```

I'm using typescript and I've decided to opt out of using fragments this way for exactly the reason you detailed above.

Instead I have a file devoted to a fragment...

file: `queries/pokemon-card.fragment.tsx`

```typescript
export const PokemonCardFragment = gql`
    fragment PokemonCardPokemon on Pokemon {
      id
      url
      name
    }
`
```

Then in your query...

```typescript
const getPokemonCardQuery = gql`
  query getPokemonCard($id:ID!){
     ...PokemonCardPokemon
  }
  ${PokemonCardFragment}
`
```

Lastly pro tip! Include id in your fragment query and anytime that fragment is fetched [it will reload all components](https://www.apollographql.com/docs/react/features/cache-updates.html#automatic-updates) that use that fragment data.

I.E. if you have some mutation
```
mutation addCard($name: String!){
   addPokemonCard(name: $name){
      ... PokemonCardPokemon
   },
   ${PokemonCardFragment}
}
```

And as long as your mutation returns `PokemonCardPokemon` it will reload all components using that information.

**Comment by hwillson** [comment]
@danielrasmuson's answer in https://github.com/apollographql/apollo-client/issues/2722#issuecomment-353887088 is great! Closing - thanks!

**Comment by astorije** [comment]
Yeah, we ended up doing pretty much what @danielrasmuson described, except we colocate the fragment with the component, and use default and non-default exports to use this pattern:

```tsx
// In PokemonCard.tsx:

const PokemonCard: SFC = () => <span />;

export default PokemonCard;

export const PokemonCardFragment = gql`
  fragment PokemonCardPokemon on Pokemon {
    id
    url
    name
  }
`;

// In the caller file:

import PokemonCard, { PokemonCardFragment } from './PokemonCard'; // <-- This is the main difference in usage

const GET_POKEMON_CARD_QUERY = gql`
  query getPokemonCard($id: ID!) {
    ...PokemonCardPokemon
  }
  ${PokemonCardFragment}
`;
```

**Comment by fabientownsend** [comment]
I came across the same issue, one approach is to extend the interface `FunctionComponent` provided by React, for example:

``` javascript
import { FunctionComponent } from 'react'

interface FCWithFragment<E> extends FunctionComponent<E> {
  fragment(): string
}

type YourComponentProps = {}
export const YourComponent: FCWithFragment<YourComponentProps> = (props) => {
  return ... 
}

YourComponent.fragment = gql`
...
`
```

**Comment by goughjo03** [comment]
> I came across the same issue, one approach is to extend the interface `FunctionComponent` provided by React, for example:
> 
> ```js
> import { FunctionComponent } from 'react'
> 
> interface FCWithFragment<E> extends FunctionComponent<E> {
>   fragment: string
> }
> 
> type YourComponentProps = {}
> export const YourComponent: FCWithFragment<YourComponentProps> = (props) => {
>   return ... 
> }
> 
> YourComponent.fragment = gql`
> ...
> `
> ```

Is this really necessary? Apollo client hasn't thought of this already?

**Comment by josecolella** [comment]
@goughjo03 has there been any updates to this. Running across this in my project and wondering if there's a solution

**Comment by goughjo03** [comment]
@josecolella they are planning to develop a `useFragment` hook and there is an issue to track it here https://github.com/apollographql/apollo-client/issues/8236
