### ISSUE TITLE
Feature request : support @argumentDefinitions directive

### ISSUE THREAD

**Issue by pulse14** [apollographql/apollo-client#2723]
Could you add the very useful @argumentDefinitions directive ?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Feature%20request%20%3A%20support%20%40argumentDefinitions%20directive&body=Migrated%20from:%20apollographql/apollo-client%232723) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
