### ISSUE TITLE
apollo 2 client is very unstable

### ISSUE THREAD

**Issue by webmobiles** [apollographql/apollo-client#2725]
Hi,
I was running apollo 1 for some months, now i've upgraded to new apollo 2 in 2 days, but almost one week and I'm trying to path erros , different behaviours with the new apollo cath error,  when the server goes offline , and come back online , apollo2 don"t care about fetchpolicy 'networking only' 
it's just a randon behavoiur , when read the network, when update the queries,  loading value, and error value got crazy.

I can't back to version 1 because i've already a lot advanced in the new version. I hope don't be like angular 2 lol

I can give access to my large app if someone is interested and to analyze the problem... I have a lot of ideas how to write a guide, documentation is very simple, but before i need to solve all the problems that I'm having with the version 2

thanks

**Comment by macrozone** [comment]
i also have  a downgrade to version 1. After network error, apollo client renders the app in a unpredictable state. With all these packages and modules (apollo-client, apollo-link, apollo-client-preset, react-apollo) its also really hard to track down this issue. I am very sorry, but this is a mess.

**Comment by sw-yx** [comment]
this is not a good issue. please file if you have a specific question or constructive criticism.

**Comment by macrozone** [comment]
@sw-yx you are right, there are already plenty of open issues with specific problems for version 2. 

Bottom line here is, that version 2 might be considered as unstable and shouldn't be recommended for the moment for production apps at the moment.

**Comment by webmobiles** [comment]
there are a lot of issues to solve, the list of long, by example one of them:

you visite a page with network error, then network comes, then you visite another page, all is working, again you visite the page that had error, and you have loading infinite .. has no refetch.

about cache:
you set all cache to 'network-only' , you login wiht a user, ok you can list by example 'credit cards' that you can only too see.   you close the session, another user logged in, and the user can see for some seconds your old query 'credit cards' but with the card that he did not must see ...  I mean the cache does not work always like that. No way to turn off completly sometimes.. I think in version 1 was not like that. 
I version 1 the  errors was on the redux state, now all go with global apollo error...

The problem is a lot of issues are closed or never answer it, the documentation is poor; so you never know if still bugs from v1 are present.

I like apollo, but people must know that v2 is not stable and completed for production.

**Comment by juank11memphis** [comment]
+1 on v2 being very unstable, I am downgrading to 1.8.1 and hoping bugs will get fixed soon.

**Comment by hwillson** [comment]
Hi all - this issue is much too broad to effectively act on. If anyone here is still having issues with `apollo-client` 2.x, please open an issue for each specific problem, providing as many details as possible, ideally alongside some form of reproduction. The more specific and detailed the issue, the better the chance it will be resolved quickly. Thanks!
