### ISSUE TITLE
IE 11 compatibility Promise is undefined

### ISSUE THREAD

**Issue by hlehmann** [apollographql/apollo-client#2726]
`Reference error: Promise is undefined`
in: QueryManager.prototype.fetchRequest

is it possible to transpile it ?

**Comment by skywinston** [comment]
I am getting a similar error as well in IE 11:
```
'Promise' is undefined
```

**Comment by n1ru4l** [comment]
The Promise Object can only be polyfilled.

If you are already using babel-polyfill you could use https://babeljs.io/docs/plugins/preset-env/#usebuiltins

There are also many other polyfills (which could possible be much more lightweight than babel-polyfill.) One of those is: https://www.npmjs.com/package/promise-polyfill

**Comment by hwillson** [comment]
If one of the options listed in https://github.com/apollographql/apollo-client/issues/2726#issuecomment-370582263 doesn't help, please try searching the interwebs for countless other `Promise` polyfill approaches. Thanks!
