### ISSUE TITLE
apollo-utilities package

### ISSUE THREAD

**Issue by kivutar** [apollographql/apollo-client#2733]
I have installed `"apollo-utilities": "1.0.3"` from npm, and I am getting this error:

    Unable to resolve path to module 'apollo-utilities'

If I check the package in my node_modules folder, I can see a

    "jsnext:main": "/lib/index.js",

That should be

    "jsnext:main": "./lib/index.js",

As it is already the case in master.

So I think that the version 1.0.3 released on npm is a little old, you might want to update it and bump the version number.

**Comment by hwillson** [comment]
This was resolved - thanks!
