### ISSUE TITLE
[Feature idea] Models

### ISSUE THREAD

**Issue by lorensr** [apollographql/apollo-client#2735]
I'd like to be able to attach methods to objects of a certain type, like [dburles:collection-helpers](https://github.com/dburles/meteor-collection-helpers). So that eg all objects of `type User` had an `isAdmin()` method:

```js
isAdmin() {
  return this.groups.contains('admin');
}
```

I know I could add `isAdmin` as a schema field with a resolver for it on the server, but I don't want to clutter the schema with helpers, or add load to the server and add size to the response body. In this case it would be a small addition, but methods could have larger values, and you could be fetching a lot of those objects. There are also cases in which the methods couldn't be resolvers on the server, eg if they have side effects, or in the below case, the value would become out-of-date:

```js
age() {
  return Date.now() - this.createdAt;
}
```

When I try to add a property to an object I get from `react-apollo` `graphql()`, I get `TypeError: Cannot add property isAdmin, object is not extensible`. 

> Could this be a plugin? In many cases, a feature might be too niche to be included in the core of a library, and is better implemented as a companion package. If there isn’t a way to extend the library to do what you want, could we add additional plugin APIs? It’s important to make the case for why a feature should be part of the core functionality of the library.

I don't know!

> Is there a workaround? Is this a more convenient way to do something that is already possible, or is there some blocker that makes a workaround unfeasible?

The workaround—helper functions like `isAdmin(user)`—don't read as well, and are less naturally organized compared to methods on the `user` object.

**Comment by lorensr** [comment]
Here's a similar derived property use case from https://www.lauramedalia.com/blog/5-Graphql-design-patterns-I-follow

![image](https://user-images.githubusercontent.com/251288/39074809-e30604f0-44c0-11e8-8233-126bd3f91389.png)

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=%5BFeature%20idea%5D%20Models&body=Migrated%20from:%20apollographql/apollo-client%232735) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
