### ISSUE TITLE
Documentation: Proper types not shown in API Reference

### ISSUE THREAD

**Issue by Cito** [apollographql/apollo-client#2739]
On the [API reference documentation page for the watchQuery method](https://www.apollographql.com/docs/react/reference/#ApolloClient\.watchQuery), the `fetchResults` and `notifyOnNetworkStatusChange` options are shown as having type `any` instead of their proper type `boolean`.

In [the TypeScript source file](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/watchQueryOptions.ts) the types are set correctly. I assume the reference documentation is automatically created from that source, but it seems this does not work properly.

**Comment by jbaxleyiii** [comment]
Thanks for reporting this. There hasn't been any activity here in quite some time, so we'll close this issue for now. If this is still a problem (using a modern version of Apollo Client), please let us know. Thanks!
