### ISSUE TITLE
Unexpected token N in JSON at position 0

### ISSUE THREAD

**Issue by peter-mouland** [apollographql/apollo-client#2741]
https://github.com/apollographql/apollo-client/blob/26bc85923962ffa5fac53a674df58acacd66949f/packages/apollo-client/src/core/QueryManager.ts#L353-L378

Hi,

I have trying out this client for the first time so please forgive any ignorance or I have messed up somewhere else!

I was receiving the error `Unexpected token N in JSON at position 0` when trying to follow the [SSR docs](https://github.com/apollographql/apollo-client/blob/master/docs/source/recipes/server-side-rendering.md).  In the end I found this was due to `link` url was incorrect.

My url was returning a 404 and it seems like the apollo-client is trying to parse the response as JSON and failing.  I tried to do a PR to check for 404's but my server couldn't handle it properly (i must have messed up somewhere else too!)

This is what I was going to suggest within a QueryManager.js catch statement
```js
                } else if (error && error.statusCode && error.statusCode === 404) {
                    throw new ApolloError({ networkError: error });
                } else {
```

Do you think this would help solve the cryptic error or would something else be more appropriate?

**Comment by zcei** [comment]
The `QueryManager` should only do what the name implies: managing the query. If API specifics get handled there (e.g. `4xx` is failure) then the compose-ability suffers.

I think this would be better handled in a link, similar to [`apollo-retry-link`](https://github.com/apollographql/apollo-link/tree/a1d382f0bbc245ba92cfc5bd6f30947fa33f0e4a/packages/apollo-link-retry), which inspects the error's `statusCode` and acts upon it. 

For example you could say to use the retry link on `5xx` error (might be a short server outage, so retry for a bit) but fail immediately on `4xx` (user-land error, won't get valid by simple retry) with a more human-friendly error.

**Comment by hwillson** [comment]
I agree with https://github.com/apollographql/apollo-client/issues/2741#issuecomment-355815518 - this situation would be better handled another way, such as using an [`apollo-link`](https://www.apollographql.com/docs/link/). Thanks!
