### ISSUE TITLE
apollo-client@2.0.4 released instead of @2.1.1?

### ISSUE THREAD

**Issue by amitport** [apollographql/apollo-client#2742]
latest on npm:
```
December 8, 2017  = 2.0.4
November 30, 2017 = 2.1.0
November 16, 2017 = 2.0.3
```

8-Dec is the date `2.1.1` release was added to the changelog
https://github.com/apollographql/apollo-client/commit/5c1ce828ac7853532b749af286d0dd43fbc7db81#diff-827262e41bf556496dd6f68688f30d44R6

**Comment by Kivutar** [comment]
Maybe this bug is related https://github.com/apollographql/apollo-client/issues/2733

**Comment by hwillson** [comment]
Sorry for the delay - this issue was resolved, thanks for letting us know!
