### ISSUE TITLE
SSR Rending (with apollo-link-state and w/o a graphQL back-end) 

### ISSUE THREAD

**Issue by peter-mouland** [apollographql/apollo-client#2745]
**Intended outcome:**

To fetch data on the server using apollo-link-state and no graphQL back-end.  Here is the guide I was _attempting_ to follow:
https://github.com/apollographql/apollo-client/blob/master/docs/source/recipes/server-side-rendering.md

**Actual outcome:**

When trying to create a `new ApolloClient` on the server, the link option seems to be giving me problems.  I have read about 3 different methods and each one returns an error:
 * `link: new SchemaLink({ schema }),`: `Schema must be an instance of GraphQLSchema`
 * `link: withClientState({ schema }),`: `TypeError: Cannot read property 'getGame' of undefined`
 * `link: createHttpLink({ ... })`: `Network error: Unexpected token N in JSON at position 0 ` (this is actually a 404)

I have checked and only have one version of graphql installed:
```
yarn list graphql*
├─ graphql-anywhere@4.1.0
├─ graphql-tag@2.6.0
└─ graphql@0.11.7
```

**How to reproduce the issue:**

I was originally adding this to an existing app, using the following additions:
 * add Apollo Link State (working client side): 
https://github.com/peter-mouland/react-lego/commit/58c920ed10d97e7c4e0a5c8e70f1580b3ce30e06
 *  trying to get SSR w/ data fetching working:
https://github.com/peter-mouland/react-lego/commit/ee32909164d661aa0bdaf26e5feca1cc1fc5a96a

Here is a reduced test case (which includes a readme highlighting important files):
https://github.com/peter-mouland/react-lego/tree/apollo-ssr-error

**Version**
- apollo-client@2.0.4

**Linked Issue within apollo-link-state**
Sorry, I'm not sure which repo is best suited for this issue, so i've created 2. Feel free to close if this is best answered elsewhere!
https://github.com/apollographql/apollo-link-state/issues/125

**Comment by hwillson** [comment]
This should be working with current day versions of `apollo-client`, `apollo-link-state` and `apollo-link` (this has been reported to be working by others since this issue was opened). I'll close this for now, but if you're still encountering this issue, let us know. Thanks!
