### ISSUE TITLE
Update NPM version to 2.1.1, document split in apollo-client

### ISSUE THREAD

**Issue by liywjl** [apollographql/apollo-client#2752]
Currently NPM shows that the latest version of the Apollo Client is 2.0.4, however v2.1.1 is already out. It would be good to keep this up to date.

Please document `split` in 'apollo-link', it is really handy to combine all the links in a nicer way.

**Comment by amitport** [comment]
same as https://github.com/apollographql/apollo-client/issues/2742

**Comment by hwillson** [comment]
Closing as a duplicate of https://github.com/apollographql/apollo-client/issues/2742 (which was resolved). Thanks!

P.S. > `split` is now documented here: https://www.apollographql.com/docs/link/composition.html#directional
