### ISSUE TITLE
apolloClient.mutate variables not working

### ISSUE THREAD

**Issue by jarnojellesma** [apollographql/apollo-client#2762]
**Intended outcome:**
Variable merged into the mutation

**Actual outcome:**
Status: 400 error with variable, and the mutation works when hard-coding the value in the mutation:

```
 sendMsgNotWork() {
      apolloClient.mutate({
        variables: { text: "hello" },
        mutation: gql`
          mutation {
            addComment(text: $text) {
              id
              text
            }
          }
        `,
        
      })
      .then(result => { console.log(result) })
      .catch(error => { console.log(error) });
    },

    sendMsgWorks() {
      apolloClient.mutate({
        variables: { text: "hello" },
        mutation: gql`
          mutation {
            addComment(text: "Hello") {
              id
              text
            }
          }
        `,
        
      })
      .then(result => { console.log(result) })
      .catch(error => { console.log(error) });
    }
```

**How to reproduce the issue:**
https://github.com/jarnojellesma/graphql-experiment

**Version**
- apollo-client@2.0.4

**Comment by jdmunro** [comment]
I tried your example project, this seems to work fine:

```gql
apolloClient.mutate({
  variables: { text: "hello" },
  mutation: gql`
    mutation AddComment($text: String!){
      addComment(text: $text) {
        id
        text
      }
    }
  `,
  
})
.then(result => { console.log(result) })
.catch(error => { console.log(error) });
```

**Comment by NicholasGWK** [comment]
@jarnojellesma Any insight on the cause of this? Seems to be happening to me right now :(

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-client/issues/2762#issuecomment-353953788, the reproduction seems to work properly when tested. If this continues to be a problem, please post back with an updated reproduction that shows the issue happening. Thanks!

**Comment by viniciusthamor** [comment]
How can I do it when the variable has a custom type? Like a InputObjectType defined on the server?
`apolloClient.mutate({
  variables: { text: "hello" },
  mutation: gql`
    mutation AddComment($text: CustomType!){
      addComment(text: $text) {
        id
        text
      }
    }
  `,
  
})
.then(result => { console.log(result) })
.catch(error => { console.log(error) });`

If I do like the above code it returns me the HTTP code 400 (Bad Request).

**Comment by masiamj** [comment]
@jarnojellesma I'm running into the same issue. Did you ever resolve this?

**Comment by songoten28** [comment]
Same issue. my mutation is

```
client.mutate({mutaion: gql`
  mutation createFeedback($feedback: Feedback) {
    createFeedback(feedback: $feedback)
  }
`, variables: obj})
```

```
enum FeedbackType{
  PRICE
  APP_EXPERIENCE
  AUDIO_GUIDE_CONTENT
  MAP
  OTHER
}

input Feedback{
  categories : [FeedbackType]
  comment: String
  deviceInfo: String
  scannedVoucher: Boolean
  appleReceipt: String
}

type Mutation{
  createFeedback(feedback: Feedback): Int
}
```
I feeling if we pass obj for param. we will got this problem

**Comment by shkrt** [comment]
This is because variables need to be handled on the server side. Nothing to do with client, same as https://github.com/apollographql/react-apollo/issues/164

**Comment by osamaabid03** [comment]
Thankx @vigoss6666

**Comment by nicreichert** [comment]
I'm having this issue both on `mutate` and `query`.

the code I use is: 
```ts
loadUsers = (variables?: GetUsersVariables['input']) =>
   client
      .query<GetUsers>({
        variables,
        query: getUsersQuery,
        fetchPolicy: 'network-only',
      })
      .then(response => this.setState({ loading: false, users: response.data.users }))
      .catch(err => console.error(err))
```

I log the `variables` parameter and the method is properly receiving the variables, however, all the requests I make have empty object on `variables`, like so: 
![Screenshot 2022-08-02 at 11 11 10](https://user-images.githubusercontent.com/4841711/182350366-ad15824b-71a0-438c-9b52-7603361f1f1d.png)

Could it be my `client` setup?

Here's how I'm setting it up:

```ts
import { ApolloClient, HttpLink, InMemoryCache } from '@apollo/client'

const link = new HttpLink({ uri: 'http://localhost:4000/graphql' })

export const client = new ApolloClient({
  link,
  cache: new InMemoryCache(),
  defaultOptions: {
    query: {
      fetchPolicy: 'network-only',
      notifyOnNetworkStatusChange: true,
    },
  },
})
```

**Comment by victors1681** [comment]
late response, but that happens when the variables in the client `variables: { .... }` do not match with the variables with the `query/mutation` ... also are case sensitive. 



> I'm having this issue both on `mutate` and `query`.
> 
> the code I use is:
> 
> ```ts
> loadUsers = (variables?: GetUsersVariables['input']) =>
>    client
>       .query<GetUsers>({
>         variables,
>         query: getUsersQuery,
>         fetchPolicy: 'network-only',
>       })
>       .then(response => this.setState({ loading: false, users: response.data.users }))
>       .catch(err => console.error(err))
> ```
> 
> and
> 
> ```ts
>   createUser = (variables: CreateUserVariables['input']) =>
>     client
>       .mutate<CreateUser>({
>         variables,
>         mutation: createUserMutation,
>       })
>       .then(response => this.setState({ userLogin: response.data.createUser }))
> ```
> 
> I log the `variables` parameter and the method is properly receiving the variables, however, all the requests I make have empty object on `variables`, like so: ![Screenshot 2022-08-02 at 11 11 10](https://user-images.githubusercontent.com/4841711/182350366-ad15824b-71a0-438c-9b52-7603361f1f1d.png)
> 
> Could it be my `client` setup?
> 
> Here's how I'm setting it up:
> 
> ```ts
> import { ApolloClient, HttpLink, InMemoryCache } from '@apollo/client'
> 
> const link = new HttpLink({ uri: 'http://localhost:4000/graphql' })
> 
> export const client = new ApolloClient({
>   link,
>   cache: new InMemoryCache(),
>   defaultOptions: {
>     query: {
>       fetchPolicy: 'network-only',
>       notifyOnNetworkStatusChange: true,
>     },
>   },
> })
> ```
