### ISSUE TITLE
Cannot read property 'query' of undefined

### ISSUE THREAD

**Issue by matteodem** [apollographql/apollo-client#2775]
For some reason webpack transpiles the instance of my apollo client into undefined. https://github.com/matteodem/sounds-social

**Intended outcome:**

That the [apollo client instance](https://github.com/matteodem/sounds-social/blob/master/code/web/src/api/graphql/client.js#L7) is not undefined Currently only works in Chrome, but not in the incognito mode.

**Actual outcome:**

Following error in the console when opening the app in the chrome incognito mode or other browsers:

```
StartupUserLanguage.js?a155:13 Uncaught TypeError: Cannot read property 'query' of undefined
    at eval (StartupUserLanguage.js?a155:13)
    at Object.<anonymous> (app.js:1056)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at eval (404:6)
    at Object.<anonymous> (app.js:3318)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at eval (client.js?ac70:1)
    at Object.<anonymous> (app.js:853)
```

**How to reproduce the issue:**

Install node `v8.9.1`, npm `5.5.1` and meteor

* Clone https://github.com/matteodem/sounds-social
* cd into project directory
* `sh scripts/install.sh && sh scripts/run.sh`
* Open site in firefox or chrome incognito mode

**Version**
- apollo-client@^2.0.1

**Comment by matteodem** [comment]
Any update on this? Should be reproduceable

**Comment by n1ru4l** [comment]
https://github.com/matteodem/sounds-social/blob/master/code/web/src/api/graphql/client.js#L2

The 'apollo-client-preset' package has no default export 'ApolloClient'. The following should work.

```js
import { ApolloClient } from 'apollo-client-preset'
```

The README (https://github.com/apollographql/apollo-client#usage) is outdated.

**Comment by matteodem** [comment]
Thanks a lot for digging into this issue. I'll check later if that's the problem

**Comment by matteodem** [comment]
Okay so that was actually the problem. Still weird that webpack doesn't recognize the circular dependency or throws some other kind of error. Thanks for helping out!
