### ISSUE TITLE
watchQuery(...).map fails

### ISSUE THREAD

**Issue by kamranayub** [apollographql/apollo-client#2788]
**Intended outcome:**

Trying to map/transform results before subscribing to ObservableQuery.

**Actual outcome:**

Error in zen-observable `map` function, 

    TypeError: Cannot read property 'variables' of undefined
    at new ObservableQuery 

I believe because it's trying to do `new ObservableQuery({ next, error, complete })` which is not how the ObservableQuery works.

**How to reproduce the issue:**

https://codesandbox.io/s/72j58qln6x

**Version**
- apollo-client@2.0.4

**Comment by compwright** [comment]
Have you tried wrapping with `Rx.Observable`?

```javascript
const Observable = require('rxjs').Observable;
const query = client.watchQuery({ query: MY_QUERY });
const query$ = Observable.from(query).map(...).subscribe(...);
```

**Comment by kamranayub** [comment]
I haven't, I was trying the Apollo RxJS module though without luck as well.
I can try it with raw Rx.

**Comment by kamranayub** [comment]
IT TOTALLY WORKS @compwright! That should be okay for my purposes 👍

**Comment by jclangst** [comment]
Same exact issue in Apollo 2.3.5. Possible regression?

Example code:

```javascript
        this.infoQuery = client.watchQuery({
            query,
            variables: {userID},
        });
        this.infoQuery
            .map((res) => {
                console.log("res", res);
                return res;
            })
            .subscribe({
                next: (x) => this.setState({}),
            });
```
