### ISSUE TITLE
Unhandled error on location change with React Router

### ISSUE THREAD

**Issue by bora89** [apollographql/apollo-client#2797]
Hi guys, we are doing some access restrictions to our system. A graphql server returns an error - saying that particular user is not able to access some resources etc, and when a user goes to another page (even with zero graphql presence) - apollo-client throws an unhandled error.

**How to reproduce the issue:**

https://codesandbox.io/s/github/pashist/react-apollo-error-template

1) open the provided demo app
2) open a console log
3) go to see ErrorPage (wait for an error)
4) go back to Home
5) see unhandled error in the console log

**Version**
- apollo-client@2.0.4

**Comment by yocal** [comment]
I have the exact same issue. Were you able to solve it?

**Comment by bora89** [comment]
No, still there

**Comment by Gregoirevda** [comment]
I had to go back to `withApollo`... Is there a way to prevent this @jbaxleyiii ?

**Comment by n1ru4l** [comment]
might be duplicate of #2258

**Comment by n1ru4l** [comment]
This should be fixed in [2.1.0-beta.3](https://github.com/apollographql/react-apollo/releases/tag/v2.1.0-beta.3)

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-client/issues/2797#issuecomment-368629080, this issue should now be resolved. If anyone is still encountering this problem, definitely let us know. Thanks!
