### ISSUE TITLE
Question - apollo data returned into a Vue data property is not extensible?

### ISSUE THREAD

**Issue by Trellian** [apollographql/apollo-client#2799]
**Intended outcome:**

It should be allowed to inject properties into data returned from an apollo query

**Actual outcome:**

My framework (Quasar Framework - built on Vue.js) tries to inject an `__index = i` into the rows , and fails, with an error: `vue.runtime.esm.js?ff9b:574 [Vue warn]: Error in render: "TypeError: Cannot add property __index, object is not extensible"`

**How to reproduce the issue:**

In my Vue single-file component, I have:
```js
  data: function () {
    return {
      rows: [],
    }
  },
  apollo: {
    rows: {
      query: PUBLISHERS_ALL_QUERY
    }
  },
```
and in the framework component that is bound to `rows[]` via the props.data:

```js
  props: {
    data: {
      type: Array,
      default: () => []
    },

  computed: {
    computedRows () {
      let rows = this.data.slice().map((row, i) => {
        row.__index = i
        return row
      })

      if (rows.length === 0) {
        return []
      }
      if (this.isServerSide) {
        return rows
      }
```
**Version**
- apollo-cache-inmemory: ^1.1.4
- apollo-client: ^2.1.0
- apollo-link: ^1.0.7
- apollo-link-http: ^1.3.2
- apollo-link-ws: ^1.0.4
- apollo-utilities: ^1.0.3

**Comment by ShockiTV** [comment]
And what is the problem with it?
Just dont mutate source data
```
let rows = this.data.slice().map((row, i) => ({
    ...row,
    __index: 1,
}))
```

**Comment by Trellian** [comment]
Maybe, but why does Apollo make it non-extensible in the first place? By the time that Apollo has returned the data (like any other backend), it's now my data, not Apollo's. 

I don't think that Apollo should care about the data after that point. Apollo has nothing whatsoever to do with the data after returning it. I can understand about the data in the Query Cache not being extensible, but the data returned from a query into a HOC?

So now it is required to do a map on the results of every single query returned, when it should not be necessary, IMHO. I have a lot of queries :)

**Comment by vizo** [comment]
@Trellian I guess it is non-extensible because of subscriptions ... so yes, it's still Apollo's data, but you can make a copy of state ;)

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Question%20-%20apollo%20data%20returned%20into%20a%20Vue%20data%20property%20is%20not%20extensible%3F&body=Migrated%20from:%20apollographql/apollo-client%232799) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
