### ISSUE TITLE
[apollo-cache-inmemory] use Map<id, item> instead of Array<item> in the cache storage

### ISSUE THREAD

**Issue by caub** [apollographql/apollo-client#2817]
Maps are iterable like arrays, and it becomes much easier to update the cache, and merge new entries

or ImmutableJS Map

or a similar wrapping structure like: 

```js
class SortableMap {
  constructor(data) {
    this.m = new Map(Array.isArray(data) ? data : Object.entries(data));
  }
  set(k, v) {
    this.m.set(k, v);
    return this;
  }
  get(k) {
    return this.m.get(k);
  }
  forEach(fn) {
    this.m.forEach(fn);
  }
  map(fn) {
    return Array.from(this.m, fn);
  }
  sort(fn) {
    const a = [...this.m].sort((x, y) => fn(x[1], y[1])); // sort with values

    this.m = new SortableMap(a);
    return this;
  }
  *[Symbol.iterator]() {
    yield* this.m;
  }
}
const m = new SortableMap([["lol", "far"], ["ok", "boo"]]);
m.sort((a, b) => a.localeCompare(b));
console.log(1, m);
// 1 SortableMap { m: SortableMap { m: Map { 'ok' => 'boo', 'lol' => 'far'
m.set("bip", "cri");
console.log(2, m.map());
// 2 [ [ 'ok', 'boo' ], [ 'lol', 'far' ], [ 'bip', 'cri' ] ]
m.sort((a, b) => a.localeCompare(b));
console.log(3, m.map(([k, v]) => [k, v + "!"]));
// 3 [ [ 'ok', 'boo!' ], [ 'bip', 'cri!' ], [ 'lol', 'far!' ] ]
```
  
to allow similar iteration, sort and a fast access by id

And possibly allow indexable fields of choice, ike for example `name` if they are unique and often accessed

**Comment by hwillson** [comment]
As of `apollo-cache-inmemory` 1.1.0, the cache implementation can be adjusted as needed. From the 1.1.0 change log:

> - make it possible to swap the cache implementation. For example, you might want to use a `Map` to store the normalized objects, which can be faster than writing by keys to an `Object`. This also allows for custom use cases, such as emitting events on `.set()` or `.delete()` (think Observables), which was otherwise impossible without the use of Proxies, that are only available in some browsers. Unless you passed in the `store` to one of the `apollo-cache-inmemory` functions, such as: `writeQueryToStore` or `writeResultToStore`, no changes to your code are necessary. If you did access the cache's functions directly, all you need to do is add a `.toObject()` call on the cache — review the changes to the tests for [an example](https://github.com/apollographql/apollo-client/blob/cd563bcd1c2c15b973d0cdfd63332f5ee82da309/packages/apollo-cache-inmemory/src/__tests__/writeToStore.ts#L258). For reasoning behind this change and more information, see [Issue #2293](https://github.com/apollographql/apollo-client/issues/2293).

For the nitty gritty details, see PR https://github.com/apollographql/apollo-client/pull/2362. Thanks!
