### ISSUE TITLE
Document release process/roadmap

### ISSUE THREAD

**Issue by joearasin** [apollographql/apollo-client#2821]
Per discussion with @jbaxleyiii on slack.

**Intended outcome:**

As a user of Apollo libraries, I would like to know when I can plan to take advantage of bugfixes and features that have been merged into master.

**Actual outcome:**

As a user of Apollo libraries, I run into a bug, find it fixed (and merged into master), and need to ask in the Slack channel for information as to when it will be part of a release.

**How to reproduce the issue:**

Run into a closed/merged issue, i.e. pretty much anything to do with typescript-modern in apollo-codegen at the moment, or assorted typescript situations in react-apollo.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Document%20release%20process%2Froadmap&body=Migrated%20from:%20apollographql/apollo-client%232821) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
