### ISSUE TITLE
Why store cache key is different for same query?

### ISSUE THREAD

**Issue by ahalimkara** [apollographql/apollo-client#2822]
**Intended outcome:**
Store cache key for same query must be same for both

```js
apolloClient.query({ query })
```
and 
```js
graphql(query, {
  props: ({ data: { user } }) => ({ user })
})(Component)
```

Store Cache key should be same in both case:
```
user({"id":null})
```

**Actual outcome:**
Store Cache key for `apolloClient.query`:
![image](https://user-images.githubusercontent.com/455458/34637126-ede11ee4-f2bf-11e7-8e50-1354b387a6c5.png)

Store Cache key when using `graphql(query, { ... })`:
![image](https://user-images.githubusercontent.com/455458/34637133-16630d28-f2c0-11e7-9a71-5a7b54a8bde0.png)

**Version**
- apollo-client@2.0.4

query:
```graphql
gql`
    query user($id: ID) {
        user(id: $id) {
            id
            name
            email
        }
    }
`
```

**Comment by Poincare** [comment]
@ahalimkara Could you write a test that elicits this behavior? Intuitively, it doesn't make sense that this would be expected behavior in this case.

**Comment by ahalimkara** [comment]
Ok i will, but I thought it was clear and easily testable with any query which has optional variables. The problem `apolloClient.query` and `graphql` is work different for optional query variables.

**Comment by hwillson** [comment]
There have been several new versions of Apollo Client and React Apollo since this issue was created, and we haven't heard back regarding a reproduction. Closing for now (but if this is still happening with modern versions, please let us know). Thanks!
