### ISSUE TITLE
fetchMore with notifyOnNetworkStatusChange cause unexpected results

### ISSUE THREAD

**Issue by FahdW** [apollographql/apollo-client#2826]
**Intended outcome:**
Using notifyOnNetworkStatusChange on my fetchMore query, I am trying to detect when the component would switch the flag from loading to true to false in my componentWillReceiveProps method, and then dispatching an action to load all my data into state. This works for my initial query but any fetchMore queries causes an issue.

```  graphql(userQuery, {
    props: ({ ownProps, data: { users, loading, networkStatus, fetchMore } }) => ({
      ...ownProps,
      users,
      usersLoading: loading,
      networkStatus,
      loadMoreUsers: cursor => () => fetchMore({
        query: moreUsersQuery,
        variables: { cursor },
        updateQuery: (previousResult, { fetchMoreResult }) => ({
          users: {
            ...fetchMoreResult.moreUsers,
            items: [...fetchMoreResult.moreUsers.items],
          },
        }),
      }),
     notifyOnNetworkStatusChange: true,
    }),

    ComponentWillReceiveProps(nextProps) {
    if (this.props.usersLoading && !nextProps.usersLoading) {
      getAllUsers(nextProps.users.items);
    }}
```

**Actual outcome:**
When the fetchMore data sets loading to false the data result is not updated yet in next set of props. It requires one more update of Props instead of being on the update in which the loading flag is set to false. networkStatus is also set to 7 and the data is yet to exist. 

**How to reproduce the issue:**
Reproduction is pretty much any fetchMore is not detecting loading correctly and instead falsely setting loading to false when the data has not updated yet.

**Version**
- apollo-client@2.0.4

**Comment by hwillson** [comment]
Any chance you could put together a small runnable reproduction that shows this happening? Providing a runnable reproduction will greatly help with troubleshooting. Thanks!

**Comment by hwillson** [comment]
We haven't heard back regarding a reproduction, so closing for now. Happy to re-open if anyone can provide a repro. Thanks!

**Comment by pencilcheck** [comment]
Having similar issues, where fetchMore renders first before the new query is being merged, and after merging there is no more re-rendering, so the old results are shown instead.

Version apollo-client: 2.6.3
