### ISSUE TITLE
Setting authentication headers

### ISSUE THREAD

**Issue by crustyratfink** [apollographql/apollo-client#2827]
**Intended outcome:**
Add JWT to request header, precisely as described in the docs

**Actual outcome:**
Header not present

**How to reproduce the issue:**
Following the documentation at:
https://www.apollographql.com/docs/react/recipes/authentication.html#Header
to the letter. Won't reproduce here as I've simply cut and pasted that code and verified that the token is in local storage. No other errors. Code works when authentication is disabled.

**Version**
- apollo-client@2.2.0

Chrome Version 63.0.3239.84

Looks just like #2168. Happy to provide more information, but I'm not clear what might be useful.

Wondering if there's been subsequent changes that haven't made it into the docs?

**Comment by triedal** [comment]
I'm seeing this as well. I used that same chunk of code and am unable to provide my network requests with a bearer token.

**Comment by crustyratfink** [comment]
Follow up: My issue's resolved, but I'm not able to nail it down to a particular cause. I updated all the relevant packages to the latest and abandoned the specific implementation from the docs above. 

Switched to this:
```  
    getClient = () => {
    const access_token = localStorage.getItem('access_token');
    const headers = {
      authorization: access_token ? `Bearer ${access_token}` : null
    };
    const httpLink = new createHttpLink({
      uri: GRAPHQL_URL,
      headers: headers
    });
    return new ApolloClient({
      link: httpLink,
      cache: new InMemoryCache().restore(window.__APOLLO_STATE__)
    });
  };
```
and `<ApolloProvider client={this.getClient()}>`

and now, the header is showing up. So, not a clear cause/effect solution, but at least something to try for googlers from the future.

**Comment by janschmutz** [comment]
jesus thanks! took me ages to find .... the syntax is awful .....

**Comment by Arseniy-II** [comment]
For newcommers: you don't need to add that code.

Only add what [docs said](https://www.apollographql.com/docs/react/recipes/authentication.html):
```
const authLink = setContext(( _, { headers } ) => {
    // get the authentication token from local storage if it exists
    const token = localStorage.getItem('token');
    // return the headers to the context so httpLink can read them
    console.log('IT UPDATES HEADERS ON EACH REQUEST ALREADY');
    return token ? {
        headers: {
            ...headers,
            authorization: `${token}`,
        }
    } : { headers };
});
```
And it will update headers after each request (just add `console.log()` to verify it)

**Comment by suranyami** [comment]
@Arseniy-II But it just doesn't work!
