### ISSUE TITLE
Name the next release after John Young

### ISSUE THREAD

**Issue by jameslporter** [apollographql/apollo-client#2828]
Just a thought when I heard the news and then started back on my work with apollo.

**Comment by lorensr** [comment]
https://en.wikipedia.org/wiki/John_Young_(astronaut)

John Watts Young was an American astronaut, naval officer and aviator, test pilot, and aeronautical engineer. He became the ninth person to walk on the Moon as Commander of the Apollo 16 mission in 1972

**Comment by hwillson** [comment]
We don't currently name releases, but thanks for the idea! 👍 Closing for now to help clear out the issue backlog, but this is definitely (space) food for thought. Thanks!
