### ISSUE TITLE
Improve error message when query receives a gql string

### ISSUE THREAD

**Issue by jlevycpa** [apollographql/apollo-client#283]
When first trying apollo client I tried to call `client.query` like this:

```
client.query(gql`
{
  myQuery {...}
}
`);
```

Instead of the correct way, which is to pass an object with a `query:` key containing the gql string. The error I received in the console was:

```
Uncaught TypeError: Cannot read property 'kind' of undefined (getFromAST.js:21)
checkDocument @ getFromAST.js:21
getQueryDefinition @ getFromAST.js:47
QueryManager.watchQuery @ QueryManager.js:107
QueryManager.query @ QueryManager.js:173
ApolloClient.query @ index.js:22
(anonymous function) @ app.js:27__webpack_require__ @ bootstrap 4bdb119…:555
fn @ bootstrap 4bdb119…:86
(anonymous function) @ bootstrap 4bdb119…:578
__webpack_require__ @ bootstrap 4bdb119…:555
(anonymous function) @ bootstrap 4bdb119…:578
(anonymous function) @ bootstrap 4bdb119…:578
```

@helfer suggested I file an issue so that this error can be improved. Here you go!

**Comment by helfer** [comment]
@jlevycpa haha, I just found this issue again. It seems to have gotten buried. If you want, you could make a PR that checks the arguments and returns a throws a useful error message if they are not present. Error messages are currently not that great for many of our APIs, so it would definitely be very appreciated.

**Comment by helfer** [comment]
If anyone wants to give this a shot, a PR would be more than welcome!

**Comment by heymartinadams** [comment]
Receiving same error, though this may be unrelated?

```
Uncaught TypeError: Cannot read property 'kind' of undefined
    at Object.parser (parser.js:11)
    at graphql (graphql.js:67)
    at Object.<anonymous> (Register.js:73)
    at __webpack_require__ (bootstrap 165d82b…:555)
    at fn (bootstrap 165d82b…:86)
    at Object.<anonymous> (index.js:4)
    at __webpack_require__ (bootstrap 165d82b…:555)
    at fn (bootstrap 165d82b…:86)
    at Object.<anonymous> (index.js:6)
    at __webpack_require__ (bootstrap 165d82b…:555)
```

In `parser.js`:
```
function parser(document) {
    var variables, type, name;
    invariant((!!document || !!document.kind), "Argument of " + document + " passed to parser was not a valid GraphQL DocumentNode. You may need to use 'graphql-tag' or another method to convert your operation into a document");
...
```

I’m new to GraphQL and Apollo, so please forgive my ignorance in this matter. Attempting to replicate the [React-Apollo-Email example](https://github.com/graphcool-examples/react-apollo-email-example).
