### ISSUE TITLE
Changelist for 2.1.0?

### ISSUE THREAD

**Issue by lukewlms** [apollographql/apollo-client#2834]
There's nothing on the main page for "history," "change," "log"... and there's no description under the Release tab.  There's also no update on the Apollo blog.

Those are all the usual places to find what's been updated.  Would love to know what's in this release and whether we should upgrade, where would I look?

Thank you!

**Comment by OneCyrus** [comment]
it's a monorepo with multiple packages. there are changelogs for each package. e.g. here: https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/CHANGELOG.md

**Comment by lukewlms** [comment]
@OneCyrus Ah I see - thank you for the info!
