### ISSUE TITLE
TS compiler error when instantiating ApolloClient from apollo-client-preset

### ISSUE THREAD

**Issue by ssalka** [apollographql/apollo-client#2855]
**Intended outcome:**

Want to create an instance of `ApolloClient` with the usual defaults - using `apollo-client-preset` seems to be the recommended way of doing so. Expecting some `.d.ts` file to override the original type definition of `ApolloClient`.

**Actual outcome:**

See below for a bare-bones reduction of my application code - note that I am using TypeScript for my project. At compile time, I get the following error:
```
ERROR in ./index.tsx
(6,16): error TS2554: Expected 1 arguments, but got 0.
```
From the looks of it, `apollo-client-preset` doesn't export any type definitions - perhaps it is implicitly using `apollo-client` types?

**How to reproduce the issue:**

I'm able to reproduce the error by running `tsc -p tsconfig.json` in a directory containing the following two files

**index.tsx**
```jsx
import * as React from 'react';
import { render } from 'react-dom';
import { ApolloClient } from 'apollo-client-preset';
import { ApolloProvider } from 'react-apollo';

const client = new ApolloClient();

render(
  <ApolloProvider client={client}>
    <div />
  </ApolloProvider>,
  document.getElementById('root')
);
```

**tsconfig.json**
```json
{
  "compilerOptions": {
    "alwaysStrict": true,
    "experimentalDecorators": true,
    "jsx": "react",
    "module": "commonjs",
    "noImplicitAny": false,
    "sourceMap": true,
    "target": "es5",
    "jsx": "react",
    "types": [
      "apollo-client",
      "apollo-client-preset",
      "react",
      "react-dom"
    ],
    "lib": [
      "DOM",
      "DOM.Iterable",
      "ES2016",
      "ScriptHost"
    ]
  }
}
```

**Version**
- apollo-client@2.2.0
- apollo-client-preset@1.0.6

**Comment by hwillson** [comment]
Instead of `apollo-client-preset`, please use [Apollo Boost](https://www.apollographql.com/docs/react/essentials/get-started.html#apollo-boost). Thanks!
