### ISSUE TITLE
propType utility: test and give examples

### ISSUE THREAD

**Issue by lorensr** [apollographql/apollo-client#2860]
`{ propType } from 'graphql-anywhere'`

`propType()`: https://github.com/apollographql/apollo-client/blob/master/packages/graphql-anywhere/src/utilities.ts#L102

Test: https://github.com/apollographql/apollo-client/blob/master/packages/graphql-anywhere/src/__tests__/utilities.ts

Add example query and fragment `doc`s: https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere#utilities

For example, something like this:

```js
const USER_QUERY = gql`
  query UserQuery {
    currentUser {
      firstName
      lastName
    }
  }  
`

Profile.propTypes = {
  currentUser: propType(USER_QUERY),
  loading: PropTypes.bool.isRequired
}
```

(but this isn't the right way)

**Comment by hwillson** [comment]
This was added to the [Utilities](https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere#utilities) docs. Thanks!

**Comment by lorensr** [comment]
The current Utilities docs are the same as when I opened the issue—tests and example query and fragment are still lacking.

**Comment by hwillson** [comment]
Hi @lorensr! 👋 I see the following example:

```js
import { propType } from 'graphql-anywhere'

X.propTypes = {
  foo: propType(doc),
  bar: propType(doc).isRequired,
}
```

I agree, it could be better though! I closed this because there was at least something, but re-reading your original post, I see what you mean. I'll get something in place. Thanks!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=propType%20utility%3A%20test%20and%20give%20examples&body=Migrated%20from:%20apollographql/apollo-client%232860) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
