### ISSUE TITLE
updateOrCreate not possible with apollo-client

### ISSUE THREAD

**Issue by danielrasmuson** [apollographql/apollo-client#2861]
Graphcool added an updateOrCreate method https://www.graph.cool/forum/t/input-type-mutations-in-graphcool/726/4. The `$id` is not provided if its a new record. However, I'm not able to provide an optional `$id` because I get an error `ID` and `ID!` are not compatible. 

**Intended outcome:**
```
mutation UpdateItem(
  $id: ID,
  $name: String!,
){
  updateOrCreateItem(
    update: {
      id: $id,
      name: $name
    }
    create: {
      name: $name
    }
  ){
    id
  }
}
```

**Actual outcome:**

```
Save Options Error: GraphQL error: Variable '$id' expected value of type 'ID!' but value is undefined...
```

**Version**
"apollo-client-preset": "^1.0.5",
"apollo-codegen": "^0.18.3",
"apollo-link-context": "^1.0.3",
"react-apollo": "^2.0.4",

**Comment by n1ru4l** [comment]
This error is an GraphQL error and not an apollo-client error. The graphql backend requires a `ID!` type for the `$id` param.

**Comment by danielrasmuson** [comment]
If I provide `$id: ID!` then it errors because I passed in `undefined` or `null` to the `updateOrCreate` query.

**Comment by n1ru4l** [comment]
That is right because apollo-client checks if a param that is marked as required is provided.

**Comment by danielrasmuson** [comment]
Yea it make sense, but it does mean I can't use `updateOrCreate` because the required typed would be 

```
mutation UpdateItem(
  $id: ID | undefined,
  $name: String!,
){
  updateOrCreateItem(
    update: {
      id: $id,
      name: $name
    }
    create: {
      name: $name
    }
  ){
    id
  }
}
```

**Comment by n1ru4l** [comment]
But there is no thing like an union input type for graphql therefore the endpoint should IMHO have the param id typed as `ID` instead of `ID!` 🤔 

Other idea:

Maybe the `@skip` or `@include` directives might work here?

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-client/issues/2861#issuecomment-357179901, this is not an `apollo-client` error. Thanks!
