### ISSUE TITLE
Feature request: Plz add a field to expose response.headers for each request

### ISSUE THREAD

**Issue by ash0080** [apollographql/apollo-client#2868]
To fill the gap browser -> server -> graphql  Indirect communication scenario
[more details](https://github.com/apollographql/apollo-link/issues/413)

now the design only applies the end-to-end situation

For many practical scenario, we can only host a RESTful layer for users, for example oAuth,
sure, it could may be implemented in frontend, but who want to expose appID or privateKey in frontend codes? 
or you say, you can do that in graphql layer.  but what about you still have 10 micro services don't need the oAuth? Really need I mess the business code into this layer?

I don't know why the response headers should be stripped away, 
but I have to say It's really a bad idea

#2534

**Comment by hwillson** [comment]
If I'm understanding the issue correctly, you should be able to handle this with [`apollo-link-http`](https://www.apollographql.com/docs/link/links/http.html). Closing for now, but please post back if this is not the case. Thanks!
