### ISSUE TITLE
v2 Migration Docs: InMemory vs v1 Redux Cache performance benchmarks?

### ISSUE THREAD

**Issue by kevinzwhuang** [apollographql/apollo-client#2873]
My team has been using Apollo since `apollo-client@0.4.15` and one of the biggest draws to Apollo vs Relay was Apollo's use of Redux as a cache, instead of a custom cache.
For us, being able to use the dev tooling around redux we had **already been using for redux** to support graphql development was a huge boon to our adoption of graphql.

We're still on v1.x and looking over the v2 migration docs to figure out an upgrade strategy. Now that V2 has moved away from using redux as its default cache, I'm trying to learn about the performance improvements the InMemory cache has over the old redux cache implementation.

I think that if we provided Apollo users with more performance metrics on how the InMemory cache has improved vs the old Redux cache - this would help users understand more thoroughly why the switch was made.

**Comment by fc** [comment]
Redux is not gone as a store option, check here:

https://github.com/rportugal/apollo-cache-redux

**Comment by Poincare** [comment]
Thank you for the very thorough answer, @fc. I'll go ahead and close this, but if any other questions persist on this, please reopen.
