### ISSUE TITLE
How to pass graphQLErrors to component?

### ISSUE THREAD

**Issue by gilbert** [apollographql/apollo-client#2880]
I'm trying to set up apollo to handle 401 errors in my apollo react component. Here's what I have so far.

My setup looks something like the following. On a 401, `graphQLErrors` is populated within the `onError` link. Good so far.

```js
var link = ApolloLink.from([
  onError(({networkError, graphQLErrors}) => {
    graphQLErrors //=> Populated! This is good.
  }),
  new HttpLink({...})
])
```

However, when I receive the error in a react component, `graphQLErrors` is empty! Like so:

```js
export const USER_QUERY = gql`query {
  signed_in_user { id, name }
}`

const withUserData = graphql(USER_QUERY, {
  options: {
    errorPolicy: 'all'
  }
})

export default Component => withUserData( props => {
  var { data: { loading, error, self } } = props

  if (loading) return <div>Loading...</div>
  if (error) {
    error.graphQLErrors //=> Empty! :(
  }
  return <div>Loaded.</div>
})
```

Is there a way to pass the populated `graphQLErrors` array to the component? Thanks.

**Version**
- apollo-client-preset@1.0.6

**Comment by gilbert** [comment]
Any ideas on this? I spent the time updating to apollo 2.0, and this is the last missing piece. I hope I don't have to revert to 1.x =/

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=How%20to%20pass%20graphQLErrors%20to%20component%3F&body=Migrated%20from:%20apollographql/apollo-client%232880) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
