### ISSUE TITLE
this.props.navigation conflict with this.props.data in Apollo

### ISSUE THREAD

**Issue by robinia1200** [apollographql/apollo-client#2893]
I am using react-native-navigation for navigation in my app and also I use Apollo to connect to my server and get query, as you know I have to use:
<pre>const { navigate } = this.props.navigation; 
navigate("NewScreen");</pre>
Also when I want to set query data I have to use:  
<pre>
render() {     
const {data} = this.props     
const {loading, allData} = data</pre>
but I get this error: " Cannot read property 'navigate' of undefined." However, 
if I remove this line:
<pre>const { navigate } = this.props.navigation</pre>
there is no problem. How should I use these two together?

  Thanks for filing an issue on Apollo Client!

  Please make sure that you include the following 
-- | --

**Intended outcome:**

**Actual outcome:**

**How to reproduce the issue:**

**Version**
- apollo-client@<version number>

**Comment by vphong** [comment]
I would like to know as well. My use case is a `FlatList` populated by a GraphQL query, where I'd like to navigate to a `DetailsScreen` if I press on a list item. I cannot use `navigate('DetailsScreen')` from within `renderItems` of `FlatList`, with the same error as OP.

**Comment by vphong** [comment]
I fixed my issue by passing down `navigation` from the main screen as a prop of the Apollo component, ie: 

```js
export default class BrowseScreen extends React.Component {

  render() {

    return (
          <View>
            <MediaList navigation={this.props.navigation}/>
          </View>

    );
  }
}
```

And `MediaList.js` is approximately: 

```js
function MediaList({ data, navigation }) {

...

  render() {
    return(
        <Button onPress={() => navigation.push('Details')} title="Get details">
     )
  }

...

export default graphql(YOUR_QUERY, {
  props: ({ ownProps, data }) => ({
    'data': data,
    'navigation': ownProps.navigation
  })
})(MediaList);
```

**Comment by n1ru4l** [comment]
You could also utilize the object spread operator:

```js
export default graphql(YOUR_QUERY, {
  props: ({ ownProps, data }) => ({
    ...ownProps,
    data,
  })
})(MediaList);
```

**Comment by hwillson** [comment]
As demonstrated in https://github.com/apollographql/apollo-client/issues/2893#issuecomment-366531392 and https://github.com/apollographql/apollo-client/issues/2893#issuecomment-366532346, this isn't an Apollo Client issue. Closing - thanks!
