### ISSUE TITLE
Cache with date range variables

### ISSUE THREAD

**Issue by leosurwiki** [apollographql/apollo-client#2904]
**Intended outcome:**
Just wonder whether we can have this feature:
A customized way to determine whether a query is fully covered by cache we already have(based on variables).
```
query Logs($from_date: String!, $to_date: String!) {
     logs(from_date: $from_date, to_date: $to_date) {
     ...some projection
     }
}
```
If we already have cache of logs in date range [A-1.day, B+1.day]. We won't need to make request for logs in date range [A, B], instead, we only need a filter that describes which logs should be chosen.

**Comment by Poincare** [comment]
This seems like that something that would be difficult to accomplish in a generalizable way due to the way the cache is indexed. The cache doesn't have a notion of the semantics of your data types for good reason, e.g. if the variables were `$first_name` and `$last_name`, implementing range-based diffing wouldn't make any sense.

This might be possible if you could "preprocess" queries before they hit the cache. I'm not familiar enough with the current cache design to comment much more; @jbaxleyiii , what are your thoughts?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Cache%20with%20date%20range%20variables&body=Migrated%20from:%20apollographql/apollo-client%232904) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by gablabelle** [comment]
> **Intended outcome:**
> Just wonder whether we can have this feature:
> A customized way to determine whether a query is fully covered by cache we already have(based on variables).
> 
> ```
> query Logs($from_date: String!, $to_date: String!) {
>      logs(from_date: $from_date, to_date: $to_date) {
>      ...some projection
>      }
> }
> ```
> 
> If we already have cache of logs in date range [A-1.day, B+1.day]. We won't need to make request for logs in date range [A, B], instead, we only need a filter that describes which logs should be chosen.

@leosurwiki how did you implement this in the end?
