### ISSUE TITLE
subscribeToMore() doesn't get updated on calling the refetch with updated variables

### ISSUE THREAD

**Issue by gauravmakkar** [apollographql/apollo-client#2910]
Subscribing the data 

```   
componentWillReceiveProps(nextProps) {
      if ((!this.subscription && !nextProps.data.loading)) {
            this.updateSubscription(nextProps.location.query)
        }

}

updateSubscription(variables){
        this.subscription = this.props.data.subscribeToMore({
            variables:variables ,
            document: SUBSCRIPTION_QUERY,
            updateQuery: (previousResult, newResult) => {

                return Object.assign({},{__typename: previousResult.Users.__typename,Users:{users:newResult.subscriptionData.data.userListUpdated.users}})
            },
        });
}
```

Querying the Data:

```
const withQuery = graphql(USERS_QUERY, {
    props: (data) => (data),
});

export default withQuery(connect(mapStateToProps, mapDispatchToProps)(UsersTab));
```

When I call `refetch` again, `Subscription` remains same.

```
this.props.data.refetch({username:<Username>})
```

Issues:
1. Is there another way to update subscription(need to call `subscribeToMore()` again?)? 
2. Also, If I navigate away from the page, the subscription doesn't end.

**Comment by Poincare** [comment]
Could you detail a bit more as to what you mean by "subscription remains the same"? As described [here](https://www.apollographql.com/docs/react/features/subscriptions.html#subscribe-to-more), your `updateQuery` callback should be called when you receive a push update from the server. Is this happening correctly?

**Comment by hwillson** [comment]
We haven't heard back regarding the additional information requested in https://github.com/apollographql/apollo-client/issues/2910#issuecomment-360742377, so I'll close this off. Happy to re-open if this is still an issue and you're able to provide the requested info. Thanks!
