### ISSUE TITLE
No 'Access-Control-Allow-Origin' header problem

### ISSUE THREAD

**Issue by EugeneDraitsev** [apollographql/apollo-client#2911]
**Intended outcome:**
Hi, I trying to execute simple apollo query 
```
{
    reportsMetadata {
      description,
      reports {
        name,
        description,
        data {
          date,
          url,
          graphs{
            url,
            type,
            title,
            description,
            columns {
              name,
              description,
              aggregation
            }
          }
        }
      }
    }
```

And i get nice response with code 200 and data in chrome inspector (for OPTIONS and for POST)
![image](https://user-images.githubusercontent.com/16540432/35382725-67180f0c-01c0-11e8-9f9f-d83d8c3b8343.png)

![image](https://user-images.githubusercontent.com/16540432/35382732-6f31fdf6-01c0-11e8-8b00-a75241c748ac.png)

**Actual outcome:**

But for some reasons i get ` No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.` error in console 
![image](https://user-images.githubusercontent.com/16540432/35382791-9ebd19d4-01c0-11e8-8c6d-206ba913f4df.png)

And I have no any loaded data in component that connected to Apollo. What the reason of this very strange behavior. Why I can see loaded data without errors in devTools, but get error from Apollo client? Probably i missed something?

**Version**
    "apollo-cache-inmemory": "^1.1.5",
    "apollo-client": "^2.2.0",
    "apollo-link-context": "^1.0.3",
    "apollo-link-http": "^1.3.2",
    "apollo-utilities": "^1.0.4",

**Comment by EugeneDraitsev** [comment]
Oh, sorry. It was issue with GQL service. It returned cors header on OPTION request, but missed cors headers on POST, so in this situation you will able to see response in devTools, but it will be 'cors failed' request

**Comment by IsiomaOgbuehi** [comment]
Hi @EugeneDraitsev, can you give details on how you solved it? I'm having same issue.

**Comment by EugeneDraitsev** [comment]
@IsiomaOgbuehi It was server configuration error that wasn't related to apollo at all

**Comment by IsiomaOgbuehi** [comment]
Thanks @EugeneDraitsev . Figured out my docker image for backend wasn't updating as expected. Had to create a new image tag to get it working.
