### ISSUE TITLE
Manual subscriptions, problems with multiplexing

### ISSUE THREAD

**Issue by kinke** [apollographql/apollo-client#2915]
**Summary**: When 2 components subscribe to the same subscription, with identical parameters, a single subscription is sent to the server, and both components get notified - fine. But when one of those components unsubscribes, the unsubscribe is sent to the server, and the other component won't get notified anymore.

I use a HOC to refetch a GraphQL query as soon as the backend publishes a notification. It looks like this:
```js
export const withRefetchOnNotification = WrappedComponent => withApollo(class extends React.Component {
  subscription = null;

  componentDidMount = () => this.subscribe(this.props);

  componentWillReceiveProps = (nextProps) => {
    if (nextProps.userID !== this.props.userID) {
      this.unsubscribe();
      this.subscribe(nextProps);
    }
  }

  componentWillUnmount = () => this.unsubscribe();

  subscribe = (props) => {
    const { client, userID } = props;
    if (isNil(userID))
      return;

    this.subscription = client.subscribe({
      query: gql`subscription($userID: Int!) { userDataChanged(userID: $userID) { id } }`,
      variables: { userID }
    }).subscribe(
      response => this.props.data.refetch()
    );
  }

  unsubscribe = () => {
    if (this.subscription) {
      this.subscription.unsubscribe();
      this.subscription = null;
    }
  }

  render = () => {
    const { client, ...rest } = this.props;
    return <WrappedComponent {...rest} />;
  }
});
```

It's then used for two components like this:
```js
const ComponentA = compose(
  graphql(...),
  withRefetchOnNotification
)(ViewA);

const ComponentB = compose(
  graphql(...),
  R.ifElse(
    props => props.data.loading,
    () => <div>Loading data...</div>
  ),
  withRefetchOnNotification
)(ViewB);

const Page = ({ userID }) => (
  <div>
    <ComponentA userID={userID} />
    <ComponentB userID={userID} />
  </div>
);
```

So at the beginning, both components mount & subscribe. Only a single shared subscription is sent to the server over the WebSocket. Upon a server publish, both components are notified and their data is refetched. The update leads to `withRefetchOnNotification(ViewB)` being unmounted, as a div placeholder is rendered instead while `props.data.loading` is truthy. So ComponentB unsubscribes (and will re-subscribe when the data has been loaded and it is mounted again). The unsubscription is sent to the server, and consequently, ComponentA is never notified again, relying on a zombie subscription.

**Comment by lnikkila** [comment]
We can also reproduce this through React Navigation, and it seems to be consistent with the behaviour described.

Replacing the route stack with another causes all screen components to lose their subscriptions if the components are present in both stacks. Based on the original issue I’m guessing that it mounts the new component first before unmounting the old one, and the client reuses the subscription and then unsubscribes from it.

**Comment by mpoeter** [comment]
We found that in our case this issue is actually not related to the apollo-client, but to the ApolloLink implementation we use: absinthe-graphql/absinthe-socket#15

**Comment by hwillson** [comment]
Sounds like this issue has been resolved. If anyone is encountering this issue with Apollo Client specifically, let us know. Thanks!
