### ISSUE TITLE
Feature idea - make implicit store updates more verbose in case data is missing

### ISSUE THREAD

**Issue by sebastian-schlecht** [apollographql/apollo-client#2918]
Hey,

I'm not sure whether I just missed something in apollo or wasn't properly using it but I'd like to outline our case briefly to make the point:

We do have a list view where data is fetched using a specific query. One of our features is to update single items in our list via a mutation. Now we missed to specify a specific field in some nested property of the return spec of that very mutation which was needed by the list view. This resulted in apollo doing a store update, apparently realising that data from the mutation was missing since the list rendered empty.

The attribute missing in that case was a nested property, e.g. assigning a specific person to an item, that person had it's own id etc. 

I would argue that it would be helpful in such a case for apollo to throw at least a warning that data was missing instead of silently updating the store, yielding an empty list of items in our view.

Relevant part of the list-view's query 
`
tickets(params: $ticketParams) {
      id
      name
      createdAt
      updatedAt
      statusId
      categoryId
      deadline
      responsible {
        fullName
        firstName
        id
      }
    }
`

Update mutation
`
updateTicket(input: $input) {
    id
    name
    description
    categoryId
    statusId
    createdAt
    updatedAt
    deadline
    responsible {
      firstName
      id
    }
  }
`

Note that we missed the "fullName" property of "responsible" here, causing the problem described above.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Feature%20idea%20-%20make%20implicit%20store%20updates%20more%20verbose%20in%20case%20data%20is%20missing&body=Migrated%20from:%20apollographql/apollo-client%232918) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
