### ISSUE TITLE
Loading state stuck at true without any errors (data NEVER shows up)

### ISSUE THREAD

**Issue by shantsimonian** [apollographql/apollo-client#2952]
I know this seems like a repost of existing issues (it's not exactly a repost), but I've been dealing with this issue for about a week now, looked at just about every post I could find to no avail!

I have a graphql query that is being run using the graphql() function in one of my components:
```
const LOGIN_QUERY = gql `
  query LoginQuery($username: String!, $password: String!) {
    login(username: $username, password: $password)
  }
`;

const loginFormWithGraphQL = graphql(TEST_QUERY, {
  options: {
    variables: {
      username: "test",
      password: "test"
    },
    fetchPolicy: 'cache-and-network'
  }
})(withRouter(withCookies(LoginForm)));

export default loginFormWithGraphQL;
```

I expect to receive the data in the component's props after the component mounts.

**Actual outcome:**
The data is not available in the props, loading state is stuck at true and network status is 1; however, I checked the response tab in the chrome devtools network monitor, **and the response is correctly being received by chrome!**

**TWO NOTES:**
1. This occurs WITHOUT any errors occurring prior; so this issue is happening no matter what. Apollo Client never acquires the data that's received by my browser.

2. I'm able to receive the data by using the client.query() function.

**Version**
- apollo-client@2.2.0

Thank you,
Shant

**Comment by dzucconi** [comment]
Just wondering what happened with this issue @shantsimonian — as I'm currently noticing the `withCookies` HOC from `react-cookies` appears to hinder Apollo's ability to extract the query/data from the component tree.
