### ISSUE TITLE
[Feature Idea] 'QueryRef` for React Apollo?

### ISSUE THREAD

**Issue by loganpowell** [apollographql/apollo-client#2954]
**Intended outcome:**

I'm super stoked about using Apollo Client for its `link-state` and am also excited about the prospect of leveraging observables in my code (with RxJS in my case). 

**Actual outcome:**

However, though there seems to be first-class support for `RxJS` for [Angular](https://www.apollographql.com/docs/angular/basics/queries.html#queryref), that seems to be missing for React.

Are there any plans for supporting `QueryRef` in `react-apollo`?

**Comment by hwillson** [comment]
There aren't currently any plans to integrate `RxJS` further with `apollo-client` / `react-apollo`. `apollo-client` already leverages Observables (using [`zen-observable`](https://www.npmjs.com/package/zen-observable)), and if you want to use `RxJS` the `apollo-client` API should allow you to do so. Thanks!
