### ISSUE TITLE
GraphQL mutation, parameters / variables objects (with dot notation)

### ISSUE THREAD

**Issue by ghost** [apollographql/apollo-client#2955]
I have a Graphql Mutation like this:

gql query:

```
mutation UpdateMother($mother_id: ID!, $child_name: String!) {
  updateMother(
    mother: {
      id: $id
      child: {
        name: $child_name
      }
    }
  )
}
```

It works good, but I need to use `$child.name` instead of `$child_name`. Is this possible?

**Comment by jkao1** [comment]
Could you specify your use case and current variables?

I assume `child` is an object you're passing in as a variable. In your variables:
```js
variables: {
  // don't do this
  child_name: child

  // do this intead
  child_name: child.name
}
```

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=GraphQL%20mutation%2C%20parameters%20%2F%20variables%20objects%20(with%20dot%20notation)&body=Migrated%20from:%20apollographql/apollo-client%232955) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
