### ISSUE TITLE
Flow definitions for apollo-client?

### ISSUE THREAD

**Issue by FezVrasta** [apollographql/apollo-client#2963]
Sorry if I'm not following the template but it's not a bug report.

I'm trying to figure out where are the apollo-client Flow type definitions exposed in the npm package, I could find `index.js.flow` for other Apollo packages, but I can't find it for `apollo-client`.

Is it not yet supported or I'm looking in the wrong place?

**Comment by Poincare** [comment]
The state of the Flow typings as well as how to use what's available for 2.0+ is described [here](https://www.apollographql.com/docs/react/features/static-typing.html)

I will go ahead and close this - please feel free to reopen if there any more questions.

**Comment by wzrdzl** [comment]
Could you please elaborate on the maintainers position regarding the flow types for `apollo-client` and `react-apollo`. In case I would like to contribute them, what should be the solution: keep the flow typings in the `apollo-client` or in the `flow-typed` repo?

**Comment by wzrdzl** [comment]
@Poincare ^^^

**Comment by FezVrasta** [comment]
Honestly it sucks that apollo-client is the only package that doesn't ship with Flow types, it's the home of most of the most complex types and it would be so useful to have them available.

It would be good enough to just export the most commonly used types if supporting the whole library is too complex 🤷‍♂️

**Comment by NameFILIP** [comment]
Would it make sense to re-consider adding types? Looks like a lot of people would like to have them.
