### ISSUE TITLE
basic operations example returns 403 error

### ISSUE THREAD

**Issue by kurt-o-sys** [apollographql/apollo-client#2982]
**Intended outcome:**

I'm trying to make the apollo-client work. On the simplest query, it fails:
```
client.query({ query: gql`{ hello }` }).then(console.log);
```

No error, but json object:
```
{ hello }
```

**Actual outcome:**

From the browser console:

`403 (Forbidden)` and 
`Uncaught (in promise) Error: Network error: Unexpected token < in JSON at position 0`

**How to reproduce the issue:**

Follow the guide: https://www.apollographql.com/docs/react/basics/setup.html#basic-operations

```
import { ApolloClient } from 'apollo-client';
import { HttpLink } from 'apollo-link-http';
import { InMemoryCache } from 'apollo-cache-inmemory';
import gql from 'graphql-tag';

const client = new ApolloClient({
  link: new HttpLink({ uri: <graphQL uri> }),
  cache: new InMemoryCache()
});

client.query({ query: gql`{ hello }` }).then(console.log);
```

with `<graphQL uri>` the uri to a graphQL db api (in this case, unprotected "https://api.graph.cool/simple/v1/cj0wajpkpe8qh0102aoy5wed0")

**Version**
- apollo-client@5.6.0

**Comment by RxAssim** [comment]
Hi ! Made a sandbox example to make sure that the operation is working: https://codesandbox.io/s/88kqv7rk9l

I've changed the query because the `{ hello }` query is not supported by the link you stated.

**Comment by kurt-o-sys** [comment]
right, thx... got it working!
