### ISSUE TITLE
[Feature idea] Remove __typename requirement from writeFragment

### ISSUE THREAD

**Issue by lorensr** [apollographql/apollo-client#2987]
```js
client.writeFragment({
  id: '5',
  fragment: gql`
    fragment myTodo on Todo {
      completed
      __typename
    }
  `,
  data: {
    completed: true,
    __typename: 'Todo'
  },
});
```

It would be nice if I didn't have to include `__typename` in the fragment and `__typename: 'Todo'` in the data. Could it default to not writing `__typename`, or using the existing `__typename`?

**Comment by Poincare** [comment]
I guess we could just `addTypename` the fragment to get rid of the first part of the issue. This sounds like a good idea to me. @jbaxleyiii , thoughts?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=%5BFeature%20idea%5D%20Remove%20__typename%20requirement%20from%20writeFragment&body=Migrated%20from:%20apollographql/apollo-client%232987) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
