### ISSUE TITLE
Wrong query sent to server when modifying AST

### ISSUE THREAD

**Issue by mauritsl** [apollographql/apollo-client#2990]
Sometimes a different query is sent to server than was provided to `client.query`. This happens if the same query is used before, and the query AST is modified after first use.

**How to reproduce the issue:**

Here is a minimal testcase:

```javascript
client.query({
  query: gql`{ item(a: $a, b: $b) { id } }`,
  variables: {a: 'a', b: 'b'}
}).catch(() => {
  // Ignore error because the server cannot handle the test query.
}).then(() => {
  const query = gql`{ item(a: $a, b: $b) { id } }`;
  // Remove argument $b from the query.
  query.definitions[0].selectionSet.selections[0].arguments.pop();
  return client.query({query, variables: {a: 'a'}});
});
```

**Intended outcome:**

The second query should send the following request:

```json
{"operationName":null,"variables":{"a":"a"},"query":"{\n  item(a: $a) {\n    id\n    __typename\n  }\n}\n"}
```

**Actual outcome:**

The second query sends the following data to the server:

```json
{"operationName":null,"variables":{"a":"a"},"query":"{\n  item(a: $a, b: $b) {\n    id\n    __typename\n  }\n}\n"}
```

The argument removal was not reflected in this request. This is not an error in this testcase, the query runs fine if you do not execute the first query.

It gets the query from the cache in the transform utility:
https://github.com/apollographql/apollo-client/blob/master/packages/apollo-utilities/src/transform.ts#L171

A Map is used to keep the cache (line 168), which seems convenient because it can handle objects directly. But it should be used with great care because it does not check if the object is identical, but it only checks if it is a reference to the same object. It might not be clear in the testcase at first glance, but both queries are referencing the same object, because the graphql-tag gives back a reference to his internal cache.

You can easily workaround this issue by cloning the query in the call to `client.query` or `client.mutate`, which is ok if you know it, but otherwise takes some hours debugging.

There are a few possible solutions:

* Clone the inputted query in the query/mutate function. This will render the cache useless since it will not match by reference anymore. It will also pollute the cache since it will store all executed queries, even if identical.
* Use a serialized (JSON) version to store in the map. This is a small performance trade-off, which may also render the caching useless since it's not caching a heavy process anyway.
* Remove this cache, if the serialization trade-off is bigger. This also fixes the possible cache pollution.

**Used version**
2.2.2

**Comment by jbaxleyiii** [comment]
Thanks for reporting this. There hasn't been any activity here in quite some time, so we'll close this issue for now. If this is still a problem (using a modern version of Apollo Client), please let us know. Thanks!
