### ISSUE TITLE
How to know when cache match the query ?

### ISSUE THREAD

**Issue by Aetherall** [apollographql/apollo-client#2997]
Hi, dev!

I would like to know when rendering if the cache did match the query,
so I can render a different component when the cache did not match and a query is on the fly.

Actually, when a query is successfully executed, and I want to refetch with different variables, the data[queryName] prop show the old values. 

If I want to display a LoaderComponent, I can use the data.loading prop.

But **data.loading equals true even if the cache did match the query** and data[queryName] contains the correct values...

Thanks for enlighting me on this situation!

**Comment by pthrasher** [comment]
I am also interested in this information. I'm currently tying an apollo app into a redux app and we don't have any mutations yet... So any time changes happen in redux, I need to know to refetch certain queries.

**Comment by hwillson** [comment]
> I would like to know when rendering if the cache did match the query,
> so I can render a different component when the cache did not match and a query is on the fly.

You've more than likely already found a workaround for this, but one option could be to query the cache yourself first, to see if a match exists. Based on the result of this query, you could decide which component to render. So something like:

```js
try {
  const cachedResult = client.readQuery({ query: someGqlQuery });
  // Cached result found - render appropriate component
} catch (error) {
  // No cache hit, render appropriate component and do a full 
  // query / network request
  client.query({ query: someGqlQuery }).then((result) => {
    // Do something with the fetched result
  });
}
```

Given the age of this issue though, I'll close it off for now. Thanks!
