### ISSUE TITLE
Hosted documentation doesn't match github (minor issue)

### ISSUE THREAD

**Issue by Amit-A** [apollographql/apollo-client#2999]
Tiny issue here - the documentation that's hosted [here](https://www.apollographql.com/docs/react/recipes/fragment-matching.html) doesn't seem to match the documentation on github [here](https://github.com/apollographql/apollo-client/blob/master/docs/source/recipes/fragment-matching.md).

E.g. notice how the numbered list is correct on Github (steps 1, 2, and 3) and incorrect on the hosted site (steps 1, 1, and 1!) - see screenshots below.

Incorrect on hosted site:

<img width="941" alt="screen shot 2018-02-13 at 8 36 48 pm" src="https://user-images.githubusercontent.com/7987238/36183772-e5f5abe4-10fd-11e8-97cd-069dc8a2866c.png">

Correct on github:

<img width="1107" alt="screen shot 2018-02-13 at 8 36 59 pm" src="https://user-images.githubusercontent.com/7987238/36183778-ee1b66c4-10fd-11e8-9bd8-a07f0a1f7d99.png">

**Comment by hwillson** [comment]
This issue has been resolved. Thanks!
