### ISSUE TITLE
[Docs] What is the best practice to get "connection" data from cache? 

### ISSUE THREAD

**Issue by Altiano** [apollographql/apollo-client#3005]
I'm using relay style pagination

I am wondering what is the best way to get the old result from the cache given the client is not on online state anymore.

Problem I'm trying to solve is to displayed already fetched `usersConnection` to the client and showing a message "new data failed to load on offline network".

I kinda aware of `@connection` directive for pagination solution by apollo-client. The only thing I'm not sure is the `key` parameter.
My query look like this: 
````
usersConnection(pagination: $pagination) @connection(key: "usersConnection") {
..
}
````

`$pagination` is just object with fields:
````
{
  after
  first
}
````

**Comment by leosurwiki** [comment]
Currently,  I also have a similar issue:
I want to load first:
```
usersConnection(pagination: 1) @connection(key: "usersConnection") {
..
}
```
and then when I want to load:
```
usersConnection(pagination: 14) @connection(key: "usersConnection") {
..
}
```
This query won't be made if the `fetchPolicy` is default(`cache-first`).

The hack I've done is adding another field to inform  `Apollo-Cache` this query is not covered by previous one like:
```
usersConnection(pagination: 14) @connection(key: "usersConnection") {
..
}
fetchMoreSignature
```
This will work but pretty hacky, anyone has other ideas?

**Comment by n1ru4l** [comment]
I think this could be a nice feature request.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=%5BDocs%5D%20What%20is%20the%20best%20practice%20to%20get%20%22connection%22%20data%20from%20cache%3F%20&body=Migrated%20from:%20apollographql/apollo-client%233005) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
