### ISSUE TITLE
Apollo Client Prop Undefined

### ISSUE THREAD

**Issue by developer239** [apollographql/apollo-client#3009]
**Intended outcome:**
In component wrapped in withApollo HOC (from this [example](https://github.com/zeit/next.js/blob/canary/examples/with-apollo-and-redux/lib/withApollo.js)) I should be able to use Apollo client so that I could use custom queries: `this.props.client.query`

**Actual outcome:**
`console.log(this.props.client)` returns `undefined`

**How to reproduce the issue:**
Call `console.log(this.props.client)` [here](https://github.com/zeit/next.js/blob/canary/examples/with-apollo-and-redux/pages/apollo.js)

**Comment by fc** [comment]
The reproduction you linked to is not using the `withApollo` provided by the `apollo-client`.. it has a function called `withApollo` but it's not the same at all.  Looks to be an unfortunate coincidence that they named their component withApollo.

To use the `apollo-client`'s`withApollo`, check the doc example here:
https://www.apollographql.com/docs/react/basics/setup.html#withApollo

**Comment by developer239** [comment]
Thank you for your help. It was a actually a good thing that I didn't have access to Apollo client because I realized that the way I was going to query items was not the correct one.

However, there are some serious issues with the `withApollo` HOC. For example, using it in nested components (outside of the page folder) is problematic. I will gonna play a little bit more with nextjs maybe I will find some solution to these problems. :)

**Comment by fc** [comment]
We create a singleton of the apollo-client in our app.  That may work for you.  We've never used withApollo.

**Comment by developer239** [comment]
I am so sorry I posted this into a wrong repository. I wanted to post it [here](https://github.com/zeit/next.js/)
