### ISSUE TITLE
Pagination issue with Dynamic Data

### ISSUE THREAD

**Issue by jrvaja** [apollographql/apollo-client#3021]
We are making social media application.

Here, user can write post just like other social media.

We have below details:

Let,
total posts: 100
limit: 10 (default)
Offset: 0 (default)
page: 1 (default)

**Intended outcome:**
Once I am on the page#3 after two-times scroll. Now if I write a new post, I get the new data in GraphQL API response but it does note reflect in query cache. 
Here, it should bring up new post inserted as well. But it does not visible as cache is not updated.

**Create post Mutation**
```
const response = await this.$apollo.mutate({
  mutation: CREATE_POST_MUTATION,
  variables,
  refetchQueries: [{
    query: POSTS_QUERY,
    fetchPolicy: 'network-only',
    variables: {
      offset: 0,
      limit: this.pagination.offset + this.pagination.limit
    }
  }]
})
```

**Fetch post Query**
```
const variables = {
  offset: 0,
  limit: 10
}

if (newMessage) {
  variables.offset = 0
  variables.limit = this.pagination.offset + this.pagination.limit
}

const result = await this.$apollo.query({
  query: POSTS_QUERY,
  variables,
  fetchPolicy: 'network-only'
})
```

**Fetch More (On Scroll)**
```
this.$apollo.queries.posts.fetchMore({
  variables,
  fetchPolicy: 'network-only',
  updateQuery: (previousResult, { fetchMoreResult }) => {
    const posts = [...previousResult.posts, ...fetchMoreResult.posts]
    return {
      posts: [...posts]
    }
  }
})
```
**Version**
- apollo-client@1.9.2

**Comment by Rahulkukadiya** [comment]
I also face same issue

**Comment by Poincare** [comment]
Are you able to see that the server correctly sends the valid GraphQL response when the mutation for new post creation is fired? If so, is the current query then refetched? Does that receive the expected response? What happens to the cache state in this circumstance?

**Comment by hwillson** [comment]
We haven't heard back regarding the additional information requested in https://github.com/apollographql/apollo-client/issues/3021#issuecomment-366582026, so closing for now. Thanks!
