### ISSUE TITLE
[apollo-cache-inmemory] Documentation improvements : Change cacheResolvers to cacheRedirects

### ISSUE THREAD

**Issue by padupuy** [apollographql/apollo-client#3022]
**Intended outcome:**

According to this PR #3001 ,  `cacheResolvers` is now `cacheRedirects`

**Actual outcome:**

Several occurences of `cacheResolvers` (instead of `cacheRedirects`) still exist in the repo.

**How to reproduce the issue:**

Could you fix `cacheResolvers` occurences in the doc :
- https://github.com/apollographql/apollo-client/blob/master/Upgrade.md
- https://github.com/apollographql/apollo-client/blob/master/docs/source/2.0-migration.md
- https://github.com/apollographql/apollo-client/blob/master/docs/source/basics/caching.md
- https://github.com/apollographql/apollo-client/blob/master/docs/source/features/cache-updates.md#cache-redirects-with-cacheresolvers
- https://github.com/apollographql/apollo-client/blob/master/docs/source/recipes/query-splitting.md

Could you fix `cacheResolvers` occurences in the code :
- https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/__tests__/QueryManager/links.ts#L349
- https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/QueryManager.ts#L1206

**Version**
- apollo-client@2.2.5
- apollo-cache-inmemory@1.1.9

**Comment by padupuy** [comment]
As I can see in the [newest apollo-boost package](https://github.com/apollographql/apollo-client/tree/master/packages/apollo-boost), there is also an interesting third parameter called `getCacheKey`.
Now the `import { toIdValue } from 'apollo-utilities';` is no more required.
The example code is
```js
cacheRedirects: {
    Query: {
      movie: (_, { id }, { getCacheKey }) =>
        getCacheKey({ __typename: 'Movie', id });
    }
  }
```
Be careful with the `id` field if you had previously declared a specific `dataIdFromObject` configuration.

**Comment by padupuy** [comment]
Maybe you could add a version select in the documentation as can be seen in [the lodash documentation](https://lodash.com/docs)

**Comment by jbaxleyiii** [comment]
Thanks for reporting this. There hasn't been any activity here in quite some time, so we'll close this issue for now. If this is still a problem (using a modern version of Apollo Client), please let us know. Thanks!
