### ISSUE TITLE
Feature Idea: Support subscriptions in Apollo-boost

### ISSUE THREAD

**Issue by Akryum** [apollographql/apollo-client#3024]
Proposed API:

```js
const client = new ApolloClient({
  uri: 'https://nx9zvp49q7.lp.gql.zone/graphql',
  subscriptionsUri: 'https://nx9zvp49q7.lp.gql.zone/subs',
})
```

**Comment by littletower** [comment]
yes please!

**Comment by lfades** [comment]
Here's another proposed API:
```js
const client = new ApolloClient({
  ws: new WebSocketLink({
    uri: 'ws://...',
    options: {
      reconnect: true
    }
  })
})
```
This way configs for `WebSocketLink` are handled outside of apollo-boost and no more dependencies are needed, when doing SSR (or using something like Next.js) the above will fail cause WebSocketLink will throw an error, so it may also take a function that returns the link and is only called client side
```js
const client = new ApolloClient({
  ws: () => new WebSocketLink({ ... })
})
```

**Comment by nimerfarahty** [comment]
waiting updates ......

**Comment by smithaitufe** [comment]
What is the state with subscription at the moment? How is it done with apollo boost?

**Comment by lfades** [comment]
Currently `apollo-boost` doesn't has subscriptions

**Comment by smithaitufe** [comment]
I decided to go with apollo-client, apollo-link-ws

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Feature%20Idea%3A%20Support%20subscriptions%20in%20Apollo-boost&body=Migrated%20from:%20apollographql/apollo-client%233024) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
