### ISSUE TITLE
Manually subscribed ObservableQuery gets unsubscribed on internet connection loss

### ISSUE THREAD

**Issue by XenorPLxx** [apollographql/apollo-client#3041]
**Intended outcome:**
In my application I prefetch all data on first start to have it all available offline and then use smaller queries with root in the same place for each container. I didn't like that default behaviour is for apollo to watch ALL fired queries and diff them, which caused performance problems so I've created HOC for automatically subscribing/unsubscribing to Observable. Basically what it does is adding sub/unsub by using `client.watchQuery` provided by `withApollo` from `react-apollo`.

```      
      componentDidMount() {
        console.log('sub');
        this.subscribeToQuery();
      }

      componentWillUnmount() {
        console.log('unsub');
        this.unsubscriveFromQuery();
      }
```

I'm controlling which queries I am subscribed to at the moment in `render` function using the same `client` and simple `console.log`.

```
console.log(this.props.client.queryManager && this.props.client.queryManager.queryIdsByName);
```

Everything works okay, I see Observables being subscribed to and unsubscribed from as I expected. 

**Actual outcome:**
It works fine till I turn off Wi-Fi on my test device. After turning off Wi-Fi I see my queries pop up like usual in logs, but next component re-render (for example due to some local state change) shows, that `client.queryManager.queryIdsByName` is emptied out. I still can use component, for example I can send mutations - I'm using `redux-offline` library to persist mutations, so when I turn back Wi-Fi mutations get sent. The problem is that since I'm not watching query anymore I don't get updated data on screen until I re-mount whole component (for example by navigating to some other part of application and back).

It's even worse, because I am watching mutations closely and before they get correctly send the data on screen is optimistically updated and then after sending mutation it gets back to state before mutation was requested, because `ObservableQuery` should update that data correctly now.

**How to reproduce the issue:**
Subscribe to some `ObservableQuery` (watchQuery) on component mounting and log `client.queryManager.queryIdsByName` few times (for example using button), then turn off internet connection on test device and log it again - it should show that your query is no longer observed.

Is this expected behaviour? If yes, then how I can force query to stay observed when there's no internet connection or at least get observed again after connection is restored?

I've tried resubscribing like that:
```
        if (this.state.watchQuerySubscription.closed) {
          this.subscribeToQuery();
        }
```
This results in ObservableQuery being subscribed to and unsubscribed from over and over again.

Also, you can see that state of my ObservableQuery on screen below. First state is when there is internet connection, second state after connection is turned off - as you can see there is no more observers placed on that query.
![screen shot 2018-02-19 at 17 28 12](https://user-images.githubusercontent.com/6712823/36387892-7d5ad0ea-159a-11e8-99e6-694f9f83d894.png)

**Version**
- "apollo-client": "2.1.0"
- "react-apollo": "2.0.0"
- "react-native": "0.52.2"

EDIT: TL;DR As stated in the post below, I've found partial solution and now main issue is somewhat different and occurs as well in graphql HOC provided by react-apollo - SubscriptionObservable doesn't get triggered as it should:
1. subscribscribe to query
1. turn off network connectivity
1. refetch query
1. turn on network connectivity
1. send some mutation to update data watched by watchquery
1. see that SubscriptionObservable doesnt get called, even if you do more mutations online (despite it can be seen in queryManager)
1. refetch data again - now SubscriptionObservable started to be called on next mutation

**Comment by XenorPLxx** [comment]
I've went further with my implementation and did similar thing as react-apollo does in https://github.com/apollographql/react-apollo/blob/1426447c527cbf5f2b9e58986f6805a07c94b636/src/graphql.tsx#L533 and I'm resubscribing to my query now and I see my SubscriptionObserver present.

Still - it seems that SubscriptionObserver is ignored as sending mutations with Wi-Fi on doesn't trigger subscription's `next` method. Only after refetching query manually next mutation result starts to trigger subscription's `next` method as it should, despite SubscriptionObserver is there at all times.

**Comment by n1ru4l** [comment]
This might be related to https://github.com/apollographql/apollo-client/issues/2258

**Comment by XenorPLxx** [comment]
Well the thing is I am actually catching network errors for refetch function and I am not unmounting component.

In the context of the same component and the same ObservableQuery only SubcriptionObserver changes as it's automatically removed after network error and I need to create new one (same as apollo-react does). I expect that new changes in the local store provided by mutation results when the network connection is back on would be distributed to that new SubcriptionObserver, but they are not.

**Comment by hwillson** [comment]
Thanks for reporting this. There hasn't been any activity here in quite some time, so we'll close this issue for now. If this is still a problem (using a modern version of Apollo Client), please let us know. Thanks!
