### ISSUE TITLE
Unable to set authorization header using apollo-boost

### ISSUE THREAD

**Issue by kriswep** [apollographql/apollo-client#3044]
**Intended outcome:**
I tried to set an authentication token following the [Quickstart documentation](https://www.apollographql.com/docs/react/quick-start.html#options) using `apollo-boost`. Therefore I set the request property and tried to set the header via operation.setContext function.

```JavaScript
import ApolloClient from "apollo-boost";
// ...
const client = new ApolloClient({
  request: async operation => {
    operation.setContext({
      headers: {
        authorization: "randomToken"
      }
    });
  },
});
//...
```

**Actual outcome:**
All further queries fail, with the error message `[Network error]: TypeError: operation.setContext is not a function`.

**How to reproduce the issue:**
I  [forked](https://codesandbox.io/s/pplzj24xvx) your pretty Pupstagram demo showcasing the problem. Please note the added request property in the ApolloClient instantiation in index.js and see the devtools for the error message.

**Version**
- apollo-boost@0.1.1

**Comment by maartenvanvliet** [comment]
I am seeing the same

**Comment by kriswep** [comment]
Just submitted PR #3056 which fixes this problem.

**Comment by usama-asfar** [comment]
What I did to set header with apollo-boost

```
import React from "react";
import ReactDOM from "react-dom";
import App from "./App";
import ApolloClient from "apollo-boost";
import { ApolloProvider } from "@apollo/react-hooks";

const client = new ApolloClient({
  uri: "http://localhost:5000/graphql",
  request: (operation) => {
    const token = localStorage.getItem('token');
    console.log(token)
    operation.setContext({
      headers: {
        token
      }
    });
  }
});

ReactDOM.render(
  <ApolloProvider client={client}>
    <App />
  </ApolloProvider>,
  document.getElementById("root")
);
```
