### ISSUE TITLE
Feature Idea: Generate .d.ts typings preserving documentation comments

### ISSUE THREAD

**Issue by fbartho** [apollographql/apollo-client#3050]
**Intended outcome:**

⌘+click on a given method on the ApolloClient interface jumps to the appropriate `.d.ts` file in the node_modules directory.

Expectation: you would see code-comments describing how to use the method in question.

**Actual outcome:**

Unfortunately, this file and all others I checked have had their jsdoc-code-comments stripped, so the comments do not appear as a tooltip, nor when clicking through to the file.

**How to reproduce the issue:**

A. Using your favorite IDE, hover or ⌘+click on `new ApolloClient …`
B. (or) Go look at ApolloClient.d.ts in the node_module package. 

Either way: notice that there are absolutely no comments & thus no doc-hints.

**Version**
- apollo-client@<= 2.2.5 (noticed this since 2.0 came out).

**Comment by fbartho** [comment]
I'm tempted to rename this issue as a bug, as it's an explicit option in tsconfig.base.json: https://github.com/apollographql/apollo-client/blob/a32f31d79806a29cd2a9f6211d64c92997d5408a/tsconfig.base.json#L8

Can we flip this bit?

**Comment by fbartho** [comment]
I don't remember closing this. Reopening, what the heck??

**Comment by hwillson** [comment]
Thanks for reporting this @fbartho. This has been fixed in newer `apollo-client` versions (verified with 2.3.1).
