### ISSUE TITLE
graphql-anywere feature idea: allow to specify operationName

### ISSUE THREAD

**Issue by SevInf** [apollographql/apollo-client#3055]
GraphQL spec allows to have multiple operations in a single document. In that case, it would require to specify operation name before the execution.

We would like to have a support for this feature in `graphql-anywhere`. Backward-compatible way of adding the support would be adding `operationName` parameter to `execParams`:

```js
graphql(
    resolver,
    gql`
        query A {
            thingA
        }
        query B {
            thingB
        }
    `,
    root,
    context,
    variables,
    { operationName: 'A'}
);
```

If you agree with API proposal I would happily provide a pull request for it.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=graphql-anywere%20feature%20idea%3A%20allow%20to%20specify%20operationName&body=Migrated%20from:%20apollographql/apollo-client%233055) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
