### ISSUE TITLE
dependency on @types/graphql messing with my typescript project build

### ISSUE THREAD

**Issue by twhitbeck** [apollographql/apollo-client#3059]
I want to install `serverless` which depends on `apollo-client@^1.9.2` which currently resolves to `apollo-client@1.9.3` which has an optionalDependency on `@types/graphql` (rather than a devDependency?). This is causing errors in my project build because `@types/graphql` references `AsyncIterator` which is not available unless I specify `esnext.asynciterable` in my lib options, which I don't want to do.

**Intended outcome:**
No errors in my typescript build

**Actual outcome:**
Errors in my typescript build

**How to reproduce the issue:**
```sh
npm i typescript apollo-client@^1.9.2
touch index.ts
./node_modules/.bin/tsc index.ts
```

**Version**
- apollo-client@1.9.3

Please cut a new version of apollo-client (1.9.4) which does _not_ have `@types/graphql` as an optionalDependency, but rather a **devDependency**

**Comment by hwillson** [comment]
This is no longer an issue with newer versions of `apollo-client` (verified with 2.3.1). `@types/graphql` is now a `devDependency`. Thanks!
