### ISSUE TITLE
Variable "$userId" of required type "String!" was not provided.

### ISSUE THREAD

**Issue by Neklan** [apollographql/apollo-client#3060]
Hi, I`m trying to call a query with variables, but getting this GraphQL error...

`Variable "$userId" of required type "String!" was not provided.`

this is my query: 

```javascript
                .query({
                    query: gql`
                        query getUser($userId: String!) {
                            getUser(userId: $userId) {
                                _id
                                email
                                firstName
                                lastName
                                fullName
                            }
                        }
                    `,
                    fetchPolicy: 'network-only',
                    variables: {
                        userId: variables.userId
                    }
                })
```

I use nuxt.js with "nuxtjs/apollo": "3.0.4". This error occurs only when I query with WebSocket link. With HTTP link calling is ok.

**Version**
- apollo-client@2.2.5

**Comment by Hurtak** [comment]
I have encountered the same type of error. :)

**Comment by Vitiell0** [comment]
@Neklan I would guess that in

```                    
variables: {
                        userId: variables.userId
                    }
```
Your `variables.userId` is probably a type of ID. So either change `query getUser($userId: String!)` to `query getUser($userId: ID!)` or you could try `userId: str(variables.userId)`

**Comment by Hurtak** [comment]
I encountered this error again but it is probably related to nuxt apllo client since it only happens when request is made on the client side, server side request is fine.

**Comment by Neklan** [comment]
We had a problem with our backend implementation of a socket. problem solved

**Comment by zhaoxiaohui03** [comment]
I have encountered the same type of error. :)

**Comment by minamme** [comment]
Same issue withe me in May 2022

**Comment by Houssineyahia** [comment]
same here

**Comment by abdelrany** [comment]
did you solve this problem ?
i have the same now
