### ISSUE TITLE
Can't create ApolloClient: Incompatible interfaces at compilation time

### ISSUE THREAD

**Issue by cdelgadob** [apollographql/apollo-client#3061]
**Intended outcome:**
Successful compilation and creation af ApolloClient

**Actual outcome:**
Typescript error:
```
typescript: src/providers/apollo-client/apollo-client.ts, line: 101
           Argument of type '{ link: ApolloLink; cache: InMemoryCache; }'
           is not assignable to parameter of type
           'ApolloClientOptions<NormalizedCache>'. Types of property
           'cache' are incompatible. Type 'InMemoryCache' is not
           assignable to type 'ApolloCache<NormalizedCache>'. Types of
           property 'restore' are incompatible. Type '(data:
           NormalizedCacheObject) => InMemoryCache' is not assignable to
           type '(serializedState: NormalizedCache) =>
           ApolloCache<NormalizedCache>'. Types of parameters 'data' and
           'serializedState' are incompatible. Type 'NormalizedCache' is
           not assignable to type 'NormalizedCacheObject'. Index
           signature is missing in type 'NormalizedCache'.
```

**How to reproduce the issue:**
Create a new project with 
`npm install apollo-client-preset graphql-tag graphql --save`

Then import the libraries: 
```
import {
  ApolloClient,
  HttpLink,
  InMemoryCache,
  NormalizedCache,
} from 'apollo-client-preset';
```

And try to create an ApolloClient: 
```
this.apollo = new ApolloClient<NormalizedCache> ({
      link: new HttpLink ({ uri: 'https://api.cheftonic.com/dev/chftqry' }),
      cache: new InMemoryCache()
    });
```

**Version**
- apollo-client@2.2.5

**Comment by peggyrayzis** [comment]
Hi! Apollo Boost is the new recommended way to use the preset.

1. Install `apollo-boost`, remove `apollo-client` and `graphql-tag` from your `package.json` (Apollo Boost installs them for you)
`npm i apollo-boost -S`

2. Create your client
```js
import ApolloClient from 'apollo-boost'

this.apollo = new ApolloClient({ uri: 'https://api.cheftonic.com/dev/chftqry' })
```

**Comment by alexisargyris** [comment]
How to pass a fetch implementation using the above call?

**Comment by Sikian** [comment]
The problem with using apollo-boost is that, when using it from node, you'll have to polyfill the fetcher. Do you think a change of the ApolloLink typing may work?

Thanks!

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-client/issues/3061#issuecomment-371402427, `apollo-client-preset` is no longer supported (use Apollo Boost or Apollo Client instead). Thanks!
