### ISSUE TITLE
Duplicate entries with optimistic mutations and subscriptions

### ISSUE THREAD

**Issue by bendenoz** [apollographql/apollo-client#3062]
We have been trying to replicate the behaviour of the githunt sample implementing both optimistic updates and websocket subscriptions.

On some occasions, ie with a slow network, the order of the update changes and  the store becomes corrupted and show duplicate entries. I could repro on githunt

**Intended outcome:**

No duplicate comments

**Actual outcome:**

Duplicate comments

**How to reproduce the issue:**

Go to http://www.githunt.com/, open chrome inspector and throttle network to Slow 3G  
Submit a comment

![repro_subscription3](https://user-images.githubusercontent.com/3428395/36570444-5b659a70-1832-11e8-9072-a24fb695b80a.gif)

In normal operations, the order of updates is _optimistic mutation_, _real mutation_, _subscription_.
The problem happens when the subscription is triggered before the real mutation, ie: _optimistic mutation_, _subscription_, _real mutation_.

From what I can see, it's related to the fact that `subscribeToMore`'s `updateQuery` is being passed the optimistic version of the query data, not the original.

Is there any reason for this? Retrieving the non optimistic with query solves the problem but I was not able to find a clean workaround.

**Version**
- apollo-client@2.2.5

**Comment by bendenoz** [comment]
My understanding of the issue is that subscribeToMore will read from optimistic but then writes to non-optimistic.

**Comment by ducarroz** [comment]
I am experiencing the same issue with apollo-client@2.0.2

**Comment by alamothe** [comment]
I tested with 2.0.3 - looks like all 2.x is affected. Works fine in 1.x

**Comment by M1chaelTran** [comment]
I'm getting the same issue in 2.0.4 and it doesn't just happen for Subscription.
For a split second, I see duplicate entry but then it corrects itself to only showing one.

**Comment by lorensr** [comment]
I was still getting duplicates in the store in `v2.4.8`. It was not fixed by `subscribeToMore`'s `updateQuery` having:

```js
const alreadyHaveNewItem =
  some(prev.items, { id: newItem.id }) ||
  some(prev.items, { id: null })
if (alreadyHaveNewItem) {
  return prev
}
```

It was fixed by the mutation `update` having:

```js
const alreadyHaveNewItem = some(data.items, { id: newItem.id })
if (!alreadyHaveNewItem) {
  data.items.unshift(newItem)
  store.writeQuery({ ...query, data })
}
```

**Comment by mikeRChambers610** [comment]
So the issue is closed now... what was the solution??
