### ISSUE TITLE
Ability to generate multiple API files

### ISSUE THREAD

**Issue by hazzaldo** [apollographql/apollo-client#3063]
Hi,

This is not so much an issue as it's a suggestion. I was wondering, from an architectural point of view, and especially for large scale apps, it's ideal to be able split the auto-generated API.swift file into smaller Swift files, say based on different scenes or domain logic/business logic (such as with clean architecture). Otherwise you would have one gigantic API file. Is it possible to customise the creation of different API files?

Many thanks in advance

**Comment by flowchip** [comment]
@Trancever @hwillson this feature has been implemented?
Right now I have an API.swift that is large **36000 lines**

**Comment by designatednerd** [comment]
Yes - this is documented [in the iOS docs](https://www.apollographql.com/docs/ios/installation/#generate-multiple-files-in-a-folder-instead-of-one-giant-file).

**Comment by flowchip** [comment]
Awesome, thank you very much!!
The swift file with the page queries is still pretty big, what do you suggest to fix it?
