### ISSUE TITLE
TS error in Observable.d.ts

### ISSUE THREAD

**Issue by danieljvdm** [apollographql/apollo-client#3066]
I get the following typescript error in `util/Observable.d.ts' (line 5):

`Type 'typeof Observable' is not a constructor function type.`

- apollo-client@2.2.5

**Comment by magicmaaaaan** [comment]
I'm also seeing this error when I enable `esModuleInterop` for `tsc`. It should be noted that this flag [is recommended by the TypeScript devs](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-form-commonjs-modules-with---esmoduleinterop): "We highly recommend applying it both to new and existing projects."

**Comment by dobesv** [comment]
I created a PR to fix this: https://github.com/apollographql/apollo-link/pull/623

**Comment by hwillson** [comment]
This should no longer be a problem - closing for now. Thanks!
