### ISSUE TITLE
Why are new variables being spread into old variables in ObservableQuery > setVariables ?

### ISSUE THREAD

**Issue by tnrich** [apollographql/apollo-client#3077]
Hey there, 

I've tracked this line of code down to some strange issues we'd been seeing: 

https://github.com/apollographql/apollo-client/blob/d4dc034f1a74a177a9187870b96ac6d397064774/packages/apollo-client/src/core/ObservableQuery.ts#L431

```js
public setVariables(
    variables: any,
    tryFetch: boolean = false,
    fetchResults = true,
  ): Promise<ApolloQueryResult<T>> {
    // since setVariables restarts the subscription, we reset the tornDown status
    this.isTornDown = false;

    const newVariables = {
      ...this.variables,
      ...variables,
    };

    if (isEqual(newVariables, this.variables) && !tryFetch) {
      // If we have no observers, then we don't actually want to make a network
      // request. As soon as someone observes the query, the request will kick
      // off. For now, we just store any changes. (See #1077)
      if (this.observers.length === 0 || !fetchResults) {
        return new Promise(resolve => resolve());
      }
      return this.result();
    } else {
      this.lastVariables = this.variables;
      this.variables = newVariables;
      this.options.variables = newVariables;

      // See comment above
      if (this.observers.length === 0) {
        return new Promise(resolve => resolve());
      }

      // Use the same options as before, but with new variables
      return this.queryManager
        .fetchQuery(this.queryId, {
          ...this.options,
          variables: this.variables,
        } as WatchQueryOptions)
        .then(result => maybeDeepFreeze(result));
    }
  }

```

In my case, my old variables object has fewer fields than this.variables: 
```
const newVariables = {
      ...this.variables,
      ...variables,
    };
```

![image](https://user-images.githubusercontent.com/2730609/36689861-87a654ac-1ae5-11e8-8555-b8fb7f9985ec.png)

as you can see, variables does not have the "sort" field! 

But a sort field is being put on the variables anyways by the spread!

This is causing a strange result where we're not getting the results we expect. Is it documented somewhere that any variables should be changed to `null` instead of just omitting them?

I believe this could also be behind various issues other people are seeing like: 
https://github.com/apollographql/react-apollo/issues/1314

**Comment by tnrich** [comment]
Also note, I've manually changed the code to this: 

```
const newVariables = variables 
```

And my issues have gone away and my app functions just fine. Why have that spread at all? There is no code comment explaining it. 

I'll make a PR for this just to see if all the tests still pass. If they do I would be in favor of merging it in because all sorts of weird things can happen when merging old and new variables..

Thanks!

**Comment by tnrich** [comment]
Hmm because the tests are breaking due to this change :

https://travis-ci.org/apollographql/apollo-client/jobs/346444129

ObservableQuery › setOptions › does a network request if fetchPolicy is cache-only then store is reset then fetchPolicy becomes not cache-only

**Comment by hwillson** [comment]
This issue was resolved by https://github.com/apollographql/apollo-client/pull/3081. Closing - thanks @tnrich!

**Comment by tnrich** [comment]
Awesome thanks @hwillson and @jbaxleyiii !
