### ISSUE TITLE
Recommended way to use Apollo Client with Redux?

### ISSUE THREAD

**Issue by gauravmakkar** [apollographql/apollo-client#3083]
I didn't find any recommended way to use Apollo Client with Redux. However I found somewhere that  Apollo Client replaces Redux, but didn't describe the way to use apollo client to internal state management. Please share the example/code snippet if possible

**Comment by PascalSenn** [comment]
Internal State Management:
https://dev-blog.apollodata.com/the-future-of-state-management-dd410864cae2
Some Examples:
https://github.com/Urigo/apollo-local-state-examples

**Comment by hwillson** [comment]
Please refer to the great examples listed in https://github.com/apollographql/apollo-client/issues/3083#issuecomment-368818759. Closing - thanks!

**Comment by rwieruch** [comment]
Perhaps [this article](https://www.robinwieruch.de/react-redux-apollo-client-state-management-tutorial/) is helpful for anyone stumbling across this issue.

**Comment by XiaoXing44** [comment]
Can anyone provide the example react  + redux + apollo for bebiner like I am with redux?
