### ISSUE TITLE
Typescript: Argument of type '(ApolloLink | RestLink)[]' is not assignable to parameter of type 'ApolloLink[]'.   Type 'ApolloLink | RestLink' is not assignable to type 'ApolloLink'.

### ISSUE THREAD

**Issue by andkhong** [apollographql/apollo-client#3084]
The project was working just fine until recent got this error out of nowhere. Can't figure out why.

<img width="397" alt="screen shot 2018-02-26 at 10 36 11 pm" src="https://user-images.githubusercontent.com/10818651/36714101-9bd14b52-1b45-11e8-9898-a057b885107d.png">
<img width="878" alt="screen shot 2018-02-26 at 10 36 04 pm" src="https://user-images.githubusercontent.com/10818651/36714102-9c08e49a-1b45-11e8-8947-f54c918ea2f1.png">

**Comment by stipsan** [comment]
I'm seeing the same error, although I use this:
```typescript
  const link = graphqlHost
    ? new HttpLink({
        uri: graphqlHost,
        fetch,
      })
    : new SchemaLink({ schema, context: createContext(req, apiHost) })

  const client = new ApolloClient({ ssrMode: true, link, cache })
```

**Comment by stipsan** [comment]
In my case I was using yarn and some sub dependency was not using the latest apollo-link version.

Forcing my project to use the latest apollo-link resolved it.

**Comment by kachkaev** [comment]
Similar thing here:

<img width="698" alt="screen shot 2018-03-08 at 09 04 31" src="https://user-images.githubusercontent.com/608862/37142404-ea0ed94e-22af-11e8-8b61-21d0a801d101.png">

```
lib/initApollo.ts(16,27): error TS2345: Argument of type '{ connectToDevTools: boolean; ssrMode: boolean; link: HttpLink; cache: InMemoryCache; }' is not assignable to parameter of type 'ApolloClientOptions<NormalizedCacheObject>'.
  Types of property 'link' are incompatible.
    Type 'HttpLink' is not assignable to type 'ApolloLink'.
      Types of property 'split' are incompatible.
        Type '(test: (op: Operation) => boolean, left: ApolloLink | RequestHandler, right?: ApolloLink | Reques...' is not assignable to type '(test: (op: Operation) => boolean, left: ApolloLink | RequestHandler, right?: ApolloLink | Reques...'. Two different types with this name exist, but they are unrelated.
          Types of parameters 'left' and 'left' are incompatible.
            Type 'ApolloLink | RequestHandler' is not assignable to type 'ApolloLink | RequestHandler'. Two different types with this name exist, but they are unrelated.
              Type 'ApolloLink' is not assignable to type 'ApolloLink | RequestHandler'.
                Type 'ApolloLink' is not assignable to type 'RequestHandler'.
                  Type 'ApolloLink' provides no match for the signature '(operation: Operation, forward?: NextLink): Observable<any>'.
```

Temp fix:

<img width="701" alt="screen shot 2018-03-08 at 09 04 45" src="https://user-images.githubusercontent.com/608862/37142412-ee747962-22af-11e8-8eea-9a297bc51497.png">

**Comment by gauntface** [comment]
Just wanted say I managed to fix this by installing `apollo-link`. Seems the other modules used this new module (perhaps as a peer-dependency).

**Comment by hwillson** [comment]
Sounds like this has been fixed - closing, thanks!

**Comment by tdowgiel** [comment]
If you are using apollo v3 import onError as
`import { onError } from '@apollo/client/link/error';`
