### ISSUE TITLE
fetchMore: updateQuery not updating cache 

### ISSUE THREAD

**Issue by magnudae** [apollographql/apollo-client#3088]
Problem: updateQuery does not fire a cache update when altering existing objects from the cache. 
**Intended outcome:**

Our data in the cache looks like this:
```
{
  installations: [
    {
       uuid,
       <id_for_february>: { <data>},
    }
  ]
}
```
We use pagination to fetch monthly data about energy consumption. 
We fetch data for another month and the new object which updateQuery returns looks like this: 
```
{
  installations: [
    {
       uuid,
       <id_for_february>: { <data>},
       <id_for_january>: { <data>},
    }
  ]
}
```

Expected outcome is that the cache should index the new data incoming and a rerender should be triggered. 
Our updateQuery function:
```
updateQuery: (previousResult, { fetchMoreResult }) => {
    return Object.assign({}, previousResult, {
                    installations: [
                        {
                          ...previousResult.installations[0],
                          ...fetchMoreResult.installations[0],
                        },
                      ],
     });
}
```
A fetchMore query looks like this: 
```
"query ($uuid: String!) {
  installations(uuid: $uuid) {
    uuid
    month_0_2018: energy(resolution: "DAY", startTime: "2018-01-01T00:00:00+01:00", endTime: "2018-01-31T23:59:59+01:00") {
      values {
        timestamp
        value
        __typename
      }
      __typename
    }
    __typename
  }
}
"
```
**Actual outcome:**

What actually happens is that updateQuery returns the wanted data, but nothing in the cache is triggered. None of the instances of the new data are passed into the cache for normalization. 
Will the cache recognise the change if the change is in an object inside an array?

**Version**
- apollo-client@2.2.3
- apollo-cache-inmemory*1.1.7

**Comment by mefjuu** [comment]
How did you managed the problem?

**Comment by magnudae** [comment]
We managed this yes. 
Found that updating the cache is done very simple in the basic use case of Apollo. 
If I understand correctly one could alter the caching-refresh-alogorithm in a resolver,  but we went for another solution. 
We altered the architecture to utilize refetch and just regular query-fetching, which still uses the cache efficiently
