### ISSUE TITLE
Issue with optimistic response and subscriptions

### ISSUE THREAD

**Issue by alamothe** [apollographql/apollo-client#3092]
Hi,

I have followed the tutorial at: https://dev-blog.apollodata.com/full-stack-react-graphql-tutorial-582ac8d24e3b

I have an issue with subscriptions and optimistic response.

The behavior I'm observing is:
- Subscription is received first. I don't see any rollback happening with the list of messages. As a result, the list will contain both optimistic response and data from subscription after updating
- Mutation response is received. Because the message is in the list (due to the check to avoid double messages), it is not added

So the problem is that the list ends up with both optimistic response and subscription data. I can see how this works if mutation response is received first (the list will be rolled back first)

- Why is this not happening for subscription? Is this expected behavior or is it a bug? (it seems GitHunt example will have the same issue)
- How to deal with this issue in general? It seems to me that subscription should roll back optimistic updates first

Thanks!

- apollo-client@2.2.5

**Comment by alamothe** [comment]
...I checked out official repo:

```
git clone https://github.com/apollographql/graphql-tutorial.git
cd graphql-tutorial
git checkout t7-end
```

It seems to be working there - before `updateQuery` from subscription is called, the optimistic response is removed! I will try to debug, maybe this is a regression?

**Comment by bendenoz** [comment]
Hi, sounds like the problem I'm seeing too, see #3062. I have an open PR trying to address the issue

**Comment by alamothe** [comment]
Right, thanks for flagging!
