### ISSUE TITLE
Cannot read property `currentResult` of undefined. React 16

### ISSUE THREAD

**Issue by Necromant1k** [apollographql/apollo-client#3101]
**Intended outcome:**
Just updated my project to React@16.3.0-alpha.1 and got many warnings about deprecation. 
So i started on fixing it and one of the features of new React that `componentWillReceiveProps` gets removed. So this method was replaced by static one - `getDerivedStateFromProps` which is called both on initial mounting and on re-rendering of the component. 

**Actual outcome:**
After `componentWillReceiveProps` replace with `getDerivedStateFromProps` i got error. (Attached)
![image uploaded from ios 2](https://user-images.githubusercontent.com/7595812/36860492-75ea17ee-1d92-11e8-9c9d-1890c7200311.png)

**How to reproduce the issue:**
Simply upgrade to React@16.3.0-alpha.1 and replace `componentWillReceiveProps` with `getDerivedStateFromProps`. 
You will get an error 

**Version**
- react-native@<0.54.0-rc.4>
- react@<16.3.0-alpha.1>
- apollo-client@<2.2.2>

**Comment by hwillson** [comment]
If this is still a problem, would you mind reporting this over in the https://github.com/apollographql/react-apollo repo? Issues here are reserved for problems with the `apollo-client` project specifically. Thanks!
