### ISSUE TITLE
Query with cache hit fails silently if object id is invalid or missing

### ISSUE THREAD

**Issue by sohymg** [apollographql/apollo-client#3108]
**Intended outcome:**

I am not sure if this is by design but I think if an object id is invalid or not unique or missing, the QueryManager should surface the error instead of failing silently and returning null as data to the container.

**Actual outcome:**

My GraphQL server had a bug where it returns the same id for multiple objects. On first load (no cache hit), the data loads correctly as props to my container. On second load (cache hit) (twice in one page load), because of the invalid id, the QueryManager throws an error [here](https://github.com/apollographql/apollo-client/blob/6eec674f206cda11cf667a89022354b1476f5503/packages/apollo-client/src/core/QueryManager.ts#L969), catches it and fails silently with no data [here](https://github.com/apollographql/apollo-client/blob/6eec674f206cda11cf667a89022354b1476f5503/packages/apollo-client/src/core/QueryManager.ts#L978). The result is that null data gets passed to my container.

On a separate but related issue, my query is set with `network-only` fetchPolicy and it seems the code path that threw the error in QueryManager was the result of trying to read it from the store. Shouldn't the fetchPolicy cause it to return the data directly instead of trying to read from the store?

```
# error thrown
"Can't find field id on object (XXX:someid"
```

**How to reproduce the issue:**

- have a graphql response that returns 2 objects with the same id
- set fetchPolicy to `network-only`
- have a page that makes the same query twice
- observe that on the second query, the data is null

**Version**
- apollo-client@2.2.5

**Comment by sohymg** [comment]
The offending line is here https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/QueryManager.ts#L993

Why does the QueryManager return an empty `data` instead of returning an `error`?

**Comment by jbaxleyiii** [comment]
Thanks for reporting this. There hasn't been any activity here in quite some time, so we'll close this issue for now. If this is still a problem (using a modern version of Apollo Client), please let us know. Thanks!
