### ISSUE TITLE
ApolloClient with full WebSocketLink won't connect

### ISSUE THREAD

**Issue by alexander-ossur** [apollographql/apollo-client#3109]
**Intended outcome:**
Hi,
I am trying to work only with WebSocket connections. Here is what I am doing with the server part:
```javascript
import Koa from "koa";
import koaRouter from "koa-router";
import { graphqlKoa, graphiqlKoa } from "apollo-server-koa";
import { makeExecutableSchema } from "graphql-tools";
import { SubscriptionServer } from "subscriptions-transport-ws";
import { execute, subscribe } from "graphql";

// Some fake data
const books = [
	{
		title: "Harry Potter and the Sorcerer's stone",
		author: "J.K. Rowling",
	},
	{
		title: "Jurassic Park",
		author: "Michael Crichton",
	},
];

// The GraphQL schema in string form
const typeDefs = `
	type Query { books: [Book] }
	type Book { title: String, author: String }
`;

// The resolvers
const resolvers = {
	Query: { books: () => books },
};

// Put together a schema
const schema__ = makeExecutableSchema ({
	typeDefs,
	resolvers,
});

const port__ = 4000;
const koa__ = new Koa ();
const routerHttp__ = new koaRouter ();

// Setup the /graphiql route to show the GraphiQL UI
routerHttp__.get ("/graphiql", graphiqlKoa ({
	endpointURL: `ws://localhost:${port__}/graphql`,
	subscriptionsEndpoint: `ws://localhost:${port__}/graphql`
}));

koa__.use (routerHttp__.routes ());
koa__.use (routerHttp__.allowedMethods ());

// Start the server
const server__ = koa__.listen (port__, () => {
	console.log (`Go to http://localhost:${port__}/graphiql to run queries!`);

	// Setup the subscription server
	const subscriptionServer__ = new SubscriptionServer (
		{
			schema: schema__,
			execute: execute,
			subscribe: subscribe
		},
		{
			server: server__,
			path: "/graphql"
		}
	);
});
```

If I hit http://localhost:4000/graphiql is works as intended with ONLY websockets. Although my hand written client "rejects" work in that way

```javascript
import { InMemoryCache } from "apollo-cache-inmemory";
import { SubscriptionClient } from "subscriptions-transport-ws";
import { WebSocketLink } from "apollo-link-ws";
import { ApolloClient } from "apollo-client";

import gql from "graphql-tag";

const subscriptionClient__ = new SubscriptionClient ("ws://localhost:4000/graphql", {
	reconnect: true,
});

const webSocketLink__ = new WebSocketLink (subscriptionClient__);

const apolloClient__ = new ApolloClient ({
	link: webSocketLink__,
	cache: new InMemoryCache ()
});

apolloClient__.query ({
	query: gql`query { books }`
});
```

**Actual outcome:**
1. If server is down then Chrome returns  (Opcode -1) [https://ibb.co/fLV2Lx](https://ibb.co/fLV2Lx)
2. In case if server is up and running it returns nothing, and SubscriptionClient says "connecting". 
	a. In addition SubscriptionServer of the server part will say onDisconnect () (twice actually), if I close browser tab

3. In comparison to http://localhost:4000/graphiql approach, Chrome returns a list of "requests" in the Network/Frames tab [https://ibb.co/g9TQ7c](https://ibb.co/g9TQ7c)

**Version**
- apollo-client@2.2.5
- apollo-cache-inmemory@1.1.9
- subscriptions-transport-ws@0.9.6
- apollo-link-ws@1.0.7
- graphql-tag@2.8.0
- koa@2.5.0
- koa-router@7.4.0
- apollo-server-koa@1.3.2
- graphql-tools@2.21.0
- graphql@0.12.3

**Comment by alexander-ossur** [comment]
Okay found the problem. I have a package installed named "pace". Somehow it conflicting with websockets.

**Comment by rafaelsales** [comment]
Had the same issue, also caused by pace lib. Thanks!

**Comment by dpollastrini** [comment]
Using the "starter-kit" branch of ngx-admin (which includes pace-js) resulted in a bunch of errors in the network console related to ws connection failures--and the apollo-client just didn't work. Disabled pace on a whim and everything started working again. Pace is apparently a very intrusive lib that does some evil stuff. Similar issue with ngx-uploader: https://github.com/HubSpot/pace/issues/261.

**Comment by gmwill934** [comment]
using ApolloServer and getting the same error, only on the client (react), I tried searching for the 'pace' lib but did not found it. Anything else I might be missing?
