### ISSUE TITLE
Fragment Error 

### ISSUE THREAD

**Issue by dennislaupman** [apollographql/apollo-client#3110]
```
import gql from 'graphql-tag'

export const NotificationsViewQuery = gql`
 query queryRootScope {
	notifications {
    _id
    title
    datetime
    	type {
      ... on cast {
        title
        thumb
      }
      ... on author {
        name
        thumb
      }
  }
  }
}`;
```

Results in

![simulator screen shot - iphone 6 - 2018-03-02 at 17 30 12](https://user-images.githubusercontent.com/1274858/36909881-87475daa-1e3f-11e8-9f99-465588460814.png)

Weird? Its valid QraphQL Is there  a good example to fix this? Docs are in complete

Thanks!

**Comment by pulse14** [comment]
If you follow the procedure here https://github.com/apollographql/apollo-client/blob/master/docs/source/recipes/fragment-matching.md it should work

Just create a script to download possible types for each interface/union and add the fragmentMatcher to the cache

**Comment by dennislaupman** [comment]
Yes saw that one! Can you tell me what the fragmentTypes.json looks like?
