### ISSUE TITLE
Serialize Query variable passed via Props

### ISSUE THREAD

**Issue by vapstor** [apollographql/apollo-client#3111]
**Intended outcome:**
Return the specific object from server with a `@rest` call
![captura de tela 2018-03-02 as 15 44 31](https://user-images.githubusercontent.com/15200187/36915780-a6e3f434-1e30-11e8-9965-576de9d07170.png)

**Actual outcome:**
![captura de tela 2018-03-02 as 15 45 28](https://user-images.githubusercontent.com/15200187/36915808-c0f80d56-1e30-11e8-8476-d653d0ab8f1c.png)

**Description**
From different ways i tried to access the object, passing an variable via props to the query.
The request was successful only without the param 'localid', which has the following format:
`BRA:00529474000125`
Only when i noticed that the gql might be not reading the ':' i tried to copy the browser url:
`BRA%3A03757876000175`

...it works...

It seems the gql do not serialize the strings passed by variables

![captura de tela 2018-03-02 as 15 56 08](https://user-images.githubusercontent.com/15200187/36916294-49a6a760-1e32-11e8-95d3-33900461958a.png)

![captura de tela 2018-03-02 as 15 57 04](https://user-images.githubusercontent.com/15200187/36916338-62cf2d20-1e32-11e8-830b-caa41af01f71.png)

**Version**
- apollo-client@2.2.5

**Comment by maisumbruno** [comment]
+1

**Comment by hwillson** [comment]
This isn't an Apollo Client issue - it's a [GraphiQL](https://github.com/graphql/graphiql) issue. Closing - thanks!
