### ISSUE TITLE
Support of websocket link in apollo-boost

### ISSUE THREAD

**Issue by canercandan** [apollographql/apollo-client#3117]
Is there any plan to support `apollo-link-ws` in `apollo-boost` since the API doesnot offer a way to add additionnal links (see [here](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-boost/src/index.ts#L80-L85))

**Comment by nilshartmann** [comment]
Hi @canercandan! 

May I ask you how do you solve this problem currently? Did you skip apollo boost?

**Comment by hwillson** [comment]
No, there aren't currently any plans to include `apollo-link-ws` in `apollo-boost`. The plan is to keep `apollo-boost` intentionally focused on covering a lot of use cases, with sensible defaults. It isn't intended to cover every use case. For details outlining how to move away from `apollo-boost`, see the [Apollo Boost migration](https://www.apollographql.com/docs/react/advanced/boost-migration.html) section of the docs. Thanks!
