### ISSUE TITLE
[Feature idea] proxy.hasQuery()

### ISSUE THREAD

**Issue by lorensr** [apollographql/apollo-client#3128]
Currently `proxy.readQuery()` throws an error if the query is not present in the cache. There are cases in which you want to update something in the cache that may or may not be there.

## Current

```js
const withDeleteMutation = graphql(DELETE_REVIEW_MUTATION, {
  props: ({ mutate }) => ({
    delete: id =>
      mutate({
        update: store => {
          const query = {
            query: REVIEWS_QUERY,
            variables: { limit: 10, orderBy: 'createdAt_DESC' }
          }

          let data = store.readQuery(query)
          remove(data.reviews, { id })
          store.writeQuery({ ...query, data })

          query.variables.orderBy = 'createdAt_ASC'

          try {
            data = store.readQuery(query)
            remove(data.reviews, { id })
            store.writeQuery({ ...query, data })
          } catch (e) { }
          ...
```

## Desired

I'd prefer to avoid the try/catch:

```js
          if (store.hasQuery(query)) {
            data = store.readQuery(query)
            remove(data.reviews, { id })
            store.writeQuery({ ...query, data })
          }
```

Or alternatively, have `readQuery` not return an error:

```js
          data = store.readQuery(query)
          if (data) {
            remove(data.reviews, { id })
            store.writeQuery({ ...query, data })
          }
```

**Version**
- apollo-client@2.0.4

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=%5BFeature%20idea%5D%20proxy.hasQuery()&body=Migrated%20from:%20apollographql/apollo-client%233128) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
