### ISSUE TITLE
cacheRedirects: Strange behavior when fetching new data that had previously been redirected

### ISSUE THREAD

**Issue by dallonf** [apollographql/apollo-client#3131]
**Intended outcome:**

Just to put this up front: What I was trying to do turned out to not be possible in Apollo. I might make a feature request related to this. This bug report is about the extremely strange behavior that made this issue very difficult to debug.

Let's say I had this schema:

```
type Person {
  id: ID
  name: String

  activity(timeRange: String!): PersonActivityReport

  # sugar for activity(timeRange: "today")
  activityToday: PersonActivityReport
  # sugar for activity(timeRange: "yesterday")
  activityYesterday: PersonActivityReport
}
```

The `activityToday` and `activityYesterday` fields are synonymous with `activity(timeRange: "today")` and `activity(timeRange: "yesterday")`, respectively. I'd like for the cache to reflect that. 

(note: in this example, the problems I'm demonstrating could be worked around quite easily with existing Apollo features. The example is a simplification designed to show the bug with as few moving pieces as possible, it's missing a lot of the reasons why the "normal" way of doing this wasn't an option.)

So I wrote this `cacheRedirects` function locally:

```js
const cacheRedirects = {
  // ... others ...
  Person: {
      activity: (person, args) => {
        const { timeRange } = args;
        if (timeRange === 'today') {
          return person.activityToday;
        }
      },
    },
};
```

On the page, I have three queries. One wraps the whole page:

```
query ErrorTemplate {
  people {
    id
    name
    # Prefetch data for PageVisited
    activityToday {
      pagesVisited { total }
    }
  }
}
```

I intentionally prefetch some data so that the next query can resolve from the cache:

```
query PagesVisited {
  personById(id: "1") {
    id
    activity(timeRange: "today") {
      pagesVisited { total }
    }
  }
}
```

The final query executes later, when the user explicitly requests it:

```
query TimeSpent {
  personById(id: "1") {
    id
    activity(timeRange: "today") {
      timeSpent { total }
    }
  }
}
```

**Actual outcome:**

After the third query executes, the component populated by the second query suddenly loses all of its `data`! 

The `data` before:
```json
{
  "variables": {},
  "loading": false,
  "networkStatus": 7,
  "personById": {
    "id": "1",
    "activity": {
      "pagesVisited": {
        "total": 42,
        "__typename": "PersonActivityReportStat"
      },
      "__typename": "PersonActivityReport"
    },
    "__typename": "Person"
  }
}
```

The `data` after rendering the component that makes the third query:

```json
{
  "variables": {},
  "loading": false,
  "networkStatus": 7
}
```

**Expected result:**

Investigating this issue led me to believe that what I'm trying to do (alias one field in the cache to another, relative to its ancestors) is not possible in Apollo Client right now. My "workaround" of simply returning the object worked for the preload, but when another query actually resolved `activity(timeRange: "today")`, the second query tried to fulfill its data from there, except that the cached fields were now spread across `activity(timeRange: "today")` and `activityToday`. I'm going to work around it now by removing the alias fields from the schema.

However, I would _never_ expect rendering a component to have the side effect of erasing data from another unrelated component on the page.

Here are some ways Apollo could have handled this that would have been better:

* The query detects that the cache no longer resolves its query and automatically refetches. (possibly with a warning in the console)
* The query continues following the original cache redirect so that its data is still coming from the same place
* The query detects that actual data is pointing to a different place in the cache (or in this case, isn't redirecting at all) than a previous cache redirect and logs a warning to the console that the cache has become denormalized, similar to how it logs a warning when a normalized object is queried without an id.

**How to reproduce the issue:**

I've created a repro project here: https://github.com/dallonf/react-apollo-bug-sync-remount/tree/bug-cache-denormalization (this branch specifically, I've used this repo before to reproduce another bug)

All of the examples in this issue comes from that project. Load up the page and click the "Load Time Spent" button to remove the "Pages Visited" data.

**Version**
- apollo-client@2.2.6

**Comment by jbaxleyiii** [comment]
Thanks for reporting this. There hasn't been any activity here in quite some time, so we'll close this issue for now. If this is still a problem (using a modern version of Apollo Client), please let us know. Thanks!
