### ISSUE TITLE
Error occurs but result.error undefined

### ISSUE THREAD

**Issue by wroughtec** [apollographql/apollo-client#3136]
**Intended outcome:**
Expected `result.error` to have an error or Network status = 8

**Actual outcome:**
An error occurs but does not trigger queries error handling, ie the result.error is undefined and network status - 7
![screen shot 2018-03-09 at 10 02 08](https://user-images.githubusercontent.com/74549/37202468-77d323f2-2382-11e8-8ac4-5b4585adc5f2.png)
The `apollo-link-error` seems to pick it up just not the actual query

**How to reproduce the issue:**
Add a none existent field to the query

**Version**
- apollo-client@2.2.6
- react-apollo @2.1-Beta3
I am using the new ```<Query />``` component

Seems to be similar to (?regression):
https://github.com/apollographql/react-apollo/issues/1320

**Comment by andiwinata** [comment]
seems similar with:
#1546 
https://github.com/apollographql/react-apollo/issues/1314

**Comment by hwillson** [comment]
Since this is already being tracked in the React Apollo repo (see https://github.com/apollographql/apollo-client/issues/3136#issuecomment-389752156), I'll close it here. Thanks!

**Comment by sinclairnick** [comment]
I managed to fix this by setting `ssrMode: true` in the client options, as I am using NextJs. Hope this helps
