### ISSUE TITLE
Navigator on React Native is undefined

### ISSUE THREAD

**Issue by gastonmorixe** [apollographql/apollo-client#3137]
```
          if (navigator && navigator.userAgent.indexOf('Chrome') > -1) {
            // tslint:disable-next-line
            console.debug(
              'Download the Apollo DevTools ' +
                'for a better development experience: ' +
                'https://chrome.google.com/webstore/detail/apollo-client-developer-t/jdkknkkbebbapilgoeccciglkfbmbnfm',
            );
          }
```

**Comment by gastonmorixe** [comment]
@n1ru4l thanks but I don't understand. I am saying that the lib is throwing this error.

**Comment by n1ru4l** [comment]
@gastonmorixe This is an issue in https://github.com/apollographql/apollo-client/blob/546d23631c78c11cf06af2c6ab577c8a5d61604f/packages/apollo-client/src/ApolloClient.ts#L170 that has to be fixed.

The link I shared provides an example that could be used.

**Comment by gastonmorixe** [comment]
Not solved guys. 

Should be

```if (window && 
window.navigator && 
window.navigator.userAgent && 
window.navigator.userAgent.indexOf('Chrome') > -1)```

**Comment by benjamn** [comment]
Right, React Native has `window.navigator.product === "ReactNative"`, but apparently does not have a `userAgent` property.
