### ISSUE TITLE
Add favicon to all docs pages

### ISSUE THREAD

**Issue by lorensr** [apollographql/apollo-client#3139]
https://www.apollographql.com/docs/react/index.html

![image](https://user-images.githubusercontent.com/251288/37244723-3e0069c6-245b-11e8-9e68-07f1053648ef.png)

https://www.apollographql.com/docs/react/basics/setup.html

![image](https://user-images.githubusercontent.com/251288/37244724-4470b77a-245b-11e8-870f-2680681b735d.png)

The first few pages have it, but nothing below BASICS.

![image](https://user-images.githubusercontent.com/251288/37244742-67eb1222-245b-11e8-8153-8282e7a4bd9d.png)

**Comment by hwillson** [comment]
This was resolved - thanks @lorensr!
