### ISSUE TITLE
upgrade from t 2.2.0 to 2.2.6 warnings, pollInterval does not work

### ISSUE THREAD

**Issue by webmobiles** [apollographql/apollo-client#3141]
I' ve got warnings, upgrading apollo client 2.2.0 to last (2.2.6)

$  yarn upgrade apollo-client apollo-cache-inmemory apollo-link-http react-apollo graphql-tag graphql --save
$ yarn upgrade apollo-test-utils

it's ok anyway ? it's the right way to upgrade?

```
warning " > apollo-cache-inmemory@1.1.10" has unmet peer dependency "graphql@0.11.7 || ^0.12.0 || ^0.13.0".
warning " > apollo-client@2.2.6" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0".
warning "apollo-client > apollo-link@1.2.1" has unmet peer dependency "graphql@^0.11.3 || ^0.12.3 || ^0.13.0".
warning "apollo-link-error > apollo-link@1.0.7" has unmet peer dependency "graphql@^0.11.3 || ^0.12.3".
warning " > apollo-link-http@1.5.3" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0".
warning "apollo-link-http > apollo-link-http-common@0.2.3" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0".
warning " > graphql-tag@2.8.0" has unmet peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning " > graphql-tools@1.2.3" has unmet peer dependency "graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0".
warning " > apollo-test-utils@0.3.2" has incorrect peer dependency "apollo-client@^1.0.0".

```
I' ve just upgraded because pollInterval was not working, and don't work neither with 2.2.6
here the code, what is happening ? pollInterval use to work with apollo v1. what am I doing wrong ?
 thanks for your help

```
const withGraphqlandRouter = compose(

  graphql(defQls.customer.ListPage, {
    name: 'crud_list_customer',
    options: props => {
      let table = Tables[tableCrud];
      optionsValues.fetchPolicy =  'network-only'; 
      let  optionsValues = { pollInterval: 2000} 
      return optionsValues;
    },
    skip: props => {
           return !(props.myState
             && props.myState.form

         }
  }),
```

**Comment by hwillson** [comment]
Your upgrade process looks okay. Looking at the warnings, you'll likely want to check which version of `graphql` you have installed (and update as necessary to meet the dependency requirements). [`pollInterval`](https://www.apollographql.com/docs/react/api/react-apollo.html#graphql-config-options-pollInterval) should be working properly. If it isn't, please consider opening a new request over in the https://github.com/apollographql/react-apollo repo. Thanks!

Side note - your code sample doesn't quite look right. You're attempting to set `optionsValues.fetchPolicy` before you've defined the `optionsValues` variable.
