### ISSUE TITLE
Is it possible to get Request object for fetch API?

### ISSUE THREAD

**Issue by ildar-icoosoft** [apollographql/apollo-client#3143]
Is it possible to get request (not to send it) object? I need to modify request before send it. So I want to get the request object (maybe [Request from Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Request))

**Comment by ildar-icoosoft** [comment]
https://www.apollographql.com/docs/react/reference/index.html#ApolloClient\.readQuery

**Comment by hwillson** [comment]
Yes this is possible. Please refer to the [Custom fetching](https://www.apollographql.com/docs/link/links/http.html#custom) section of the [`apollo-link-http`](https://www.apollographql.com/docs/link/links/http.html) docs. Thanks!
