### ISSUE TITLE
[Question] How is the better way to refetch a Query on click ?

### ISSUE THREAD

**Issue by washingtonsoares** [apollographql/apollo-client#3146]
Guys,

Suppose i have a `UserList `component that has the query `getUsers`.
How to refetch the query `getUsers `from another component isolated from the context of the `Userlist `component?

Thanks!

**Comment by deadcoder0904** [comment]
Check [this](https://stackoverflow.com/a/39815267/6141587) if it helps

**Comment by hwillson** [comment]
The link in https://github.com/apollographql/apollo-client/issues/3146#issuecomment-372818941 should help. Closing - thanks!
