### ISSUE TITLE
Redirect after not found

### ISSUE THREAD

**Issue by adostal** [apollographql/apollo-client#3151]
Hello,
I'm work with react-client in React and Next.js.
I have problem with check, when data is received after loading.
For example:
First page (/users) - table of users
Second page (/users/1234) - user detail

I like check, that user is exist in backend. When user id with 1234 not exist, I like redirect to table of users.

I use only stateless (function) components without state.

Thanx for help

**Comment by hwillson** [comment]
This isn't really an `apollo-client` (or Apollo project of any kind) issue. This is a routing issue. Depending on how you're handling routing in your application, when your query brings back 0 results, you would redirect to wherever you want to go. If you're using React and React Router for example, you could render React Router's [`<Redirect />`](https://reacttraining.com/react-router/web/api/Redirect) component when your query has no results. Closing here - thanks!
