### ISSUE TITLE
Wrong syntax in Docs

### ISSUE THREAD

**Issue by deadcoder0904** [apollographql/apollo-client#3154]
Find `#import "./UserInfoFragment.graphql"` on [Docs Page](https://github.com/apollographql/apollo-client/blob/master/docs/source/recipes/webpack.md) at the very end.

I think it must be `import "./UserInfoFragment.graphql"` without the `#`

Opening an issue because not sure if its correct

**Comment by quirm** [comment]
It works as expected, webpack's `graphql-tag/loader` is resolving imports with `#` prefix.

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-client/issues/3154#issuecomment-376336281, this is functioning as intended. Thanks!
