### ISSUE TITLE
Support of file uploads in apollo-boost

### ISSUE THREAD

**Issue by pyros2097** [apollographql/apollo-client#3161]
We all need to be able to upload files to our to our api's and this will always be required. Why not include this link in boost package so that file uploads become seamless.
https://github.com/jaydenseric/apollo-upload-client

Also if this is not possible can you suggest any alternative way we can do it in apollo boost?

- [ ] has-reproduction
- [x] feature
- [ ] docs
- [ ] blocking
- [ ] good first issue

**Comment by Slessi** [comment]
From what I am understanding, wouldn't it simply be a matter of editing the `apollo-boost` `DefaultClient` constructor and adding the following to add any links we may want?

```diff
 export interface PresetConfig {
   request?: (operation: Operation) => Promise<void>;
   uri?: string;
   fetchOptions?: HttpLink.Options;
   clientState?: ClientStateConfig;
   onError?: ErrorLink.ErrorHandler;
   cacheRedirects?: CacheResolverMap;
+  links?: ApolloLink[];
 }

export default class DefaultClient<TCache> extends ApolloClient<TCache> {
  constructor(config: PresetConfig) {
    // bla

    const link = ApolloLink.from([
        errorLink,
        requestHandler,
        stateLink,
        httpLink,
+       ...config.links,
    ].filter(x => !!x) as ApolloLink[]);

    // bla bla
  }
}
```

**Comment by pyros2097** [comment]
True. But what if the order matters?

**Comment by Slessi** [comment]
Well, it so happened to not matter in this case :p

> Initialize Apollo Client with this *terminating* link

But yes, I suppose it would be better to cater for order off the bat

**Comment by pyros2097** [comment]
Anyways. I have recently digressed away from using the upload client as I need download progress and resumeable downloads right now which seems hard to get from apollo. So just doing a plain axios upload request seems the best option for me now.
But I would still like the links feature so that I can add my own custom link. Ex: I want websockets support or add apollo logger and don't want to install all the packages.
So it would be nice to have this option.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Support%20of%20file%20uploads%20in%20apollo-boost&body=Migrated%20from:%20apollographql/apollo-client%233161) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
