### ISSUE TITLE
Wrong link for Expo Snack & its using Apollo version 1

### ISSUE THREAD

**Issue by deadcoder0904** [apollographql/apollo-client#3168]
Find `Expo Snack` on https://www.apollographql.com/docs/react & the link is pointing to wrong location. 

It is pointing to `sketch.expo.io` but `Expo Sketch` is renamed to `Expo Snack`. So it must be pointing to `snack.expo.io`.

I was going to open a pull request but again Apollo is using version 1 in the Snack so its better to point it to version 2.

**Comment by hwillson** [comment]
The proper `snack.expo.io` address is being used in the most recent docs. Thanks for pointing this out!
