### ISSUE TITLE
When will two queries share the same query id?

### ISSUE THREAD

**Issue by leosurwiki** [apollographql/apollo-client#3170]
I am using react-apollo, suppose I use the same graphql HOC connects to two different component, will they share the same queryId, thus share the same network status?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=When%20will%20two%20queries%20share%20the%20same%20query%20id%3F&body=Migrated%20from:%20apollographql/apollo-client%233170) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
