### ISSUE TITLE
ApolloClient: (hexo) Docs Rendering Issue

### ISSUE THREAD

**Issue by fbartho** [apollographql/apollo-client#3173]
Screenshot: 
<img width="873" alt="screen shot 2018-03-19 at 2 22 52 pm" src="https://user-images.githubusercontent.com/209712/37623191-0bb6d50e-2b81-11e8-85f5-59ad1b1e2bed.png">

When viewing the [apollo-client docs](https://www.apollographql.com/docs/react/basics/setup.html#ApolloClient) in Safari, there is a corruption in the layout.

This looks like it's a bug in hexo because the docs have two headings next to each other: 

[docs/source/basics/setup.md#L170-L172](https://github.com/apollographql/apollo-client/blame/master/docs/source/basics/setup.md#L170-L172)

**Comment by mbj36** [comment]
Seeing the same error in Chrome too

**Comment by hwillson** [comment]
No longer an issue - thanks for reporting this originally!
