### ISSUE TITLE
Using apollo-link-http with ApolloLink from apollo-boost

### ISSUE THREAD

**Issue by Knaackee** [apollographql/apollo-client#3174]
**First, Apollo is really awesome! Thanks a lot to all contributors.** 

I've updated directly using the `apollo-client` package to `apollo-boost`.
Now I cant use `ApolloLink` anymore. I am getting...

`const httpLink = new HttpLink({ uri });`
`...`
`const httpLinkWithMiddleware = ApolloLink.from([afterwareLink, authMiddleware, httpLink]);`

> Type 'ApolloLink' provides no match for the signature '(operation: Operation, forward?: NextLink): Observable<any>'.

Versions: 

> "apollo-boost": "^0.1.3",
> "apollo-link-http": "^1.5.3",

What i am missing here ?

Thanks in advance!

**Comment by hwillson** [comment]
From the error message it sounds like one or more of your links (`afterwareLink` or `authMiddleware`) isn't following the `ApolloLink` API. `operation` and `forward` are parameters for a link's [`request` method](https://www.apollographql.com/docs/link/overview.html#request). Please consult the [`apollo-link`](https://www.apollographql.com/docs/link/) docs for more info. Thanks!
