### ISSUE TITLE
Credential problem

### ISSUE THREAD

**Issue by zoelner** [apollographql/apollo-client#3176]
Hello, I'm having trouble with the `credentials` option. I'm running [Tutorial](https://github.com/apollographql/apollo-client/tree/master/packages/apollo-boost#apollo-boost-options), tried setting it up to `'include'`, but when I run it, it's always set to `'same-origin'`. Am I doing something wrong?

[Error ](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-boost/src/index.ts#L77)

**Comment by natorojr** [comment]
Same issue here. This effectively renders Apollo Boost unusable if you're using cookie-based authentication.

**Comment by cmatheson** [comment]
I'm seeing the same problem with everything in fetchOptions (the headers I pass are ignored and some default value is used).

**Comment by 10thfloor** [comment]
Looks like the problem could be this?
https://github.com/apollographql/apollo-client/blob/master/packages/apollo-boost/src/index.ts#L76

```credentials: 'same-origin'``` is not being overridden by the ```fetchOptions``` object.

**Comment by abhiaiyer91** [comment]
Made a PR for this here: https://github.com/apollographql/apollo-client/pull/3464

**Comment by hwillson** [comment]
Addressed in https://github.com/apollographql/apollo-client/pull/3098. Thanks!
