### ISSUE TITLE
Subscription updates with changing query variables

### ISSUE THREAD

**Issue by pdeszynski** [apollographql/apollo-client#3178]
**Version**
- apollo-client@2.2.7

I'm trying to correctly update a collection using `subscribeToMore` but I just cannot figure it out if it works or it is possible to be done. Let's assume there's a prop that changes for e.g. a `date` and a some kind of daily created todos query:

```js
compose(
  connect((state) => ({date: state.date})), // <--- date is changed somewhere in an 'external' form
  graphql(
    gql`query todos($date: String!) { todos(date: $date) { id, date, todo } }`,
    props: props => ({
      ...props,
      subscribeToNewTodos: () => {
        return props.data.subscribeToMore({
          document: gql`subscription todoCreated($date: String!) { subscriptionCreated(date:$date) { id, date, todo} }`,
          variables: { date: props.date },
          updateQuery: (prev, { subscriptionData }) => {
             console.log(props.date) // this will correctly print out date for which subscription listening
             return {
               ...prev, // <--- prev always points to last results returned by this graphql with matching filters?
               todos: [ ...prev.todos, subscriptionData.data.todoCreated ],
          }
        })
      }
    })
  )
)(SomeComponent)
```

this code works the way that every time user changes a value in some field, state is automatically updated and because `date` props is used as a variable it automatically performs query for new date. 

Also `subscribeToMore` is called every time date changes so it binds to a newly selected date.

Everything's ok, until I add a new TODO for a different date than currently viewed one. For e.g. I'm looking onto TODOs from 01.01.2018 but I'm adding new todo to 02.01.2018. In update query `prev` will point to last loaded query result, not the query result with filters when `subscribeToMore ` was called. 

Is there any way to update cache from different set of variables, or is it possible to do such updates using `apollo-client` directly? I was thinking that might be that each call of `subscribeToMore` in the same query will override previous call, but looking that logging out props in `updateQuery` shows that it is probably not as they are the same as subscription variables.

Best

**Comment by hwillson** [comment]
Thanks for reporting this. Would you be able to provide a small runnable reproduction that demonstrates this problem?

**Comment by jbaxleyiii** [comment]
Thanks for reporting this. There hasn't been any activity here in quite some time, so we'll close this issue for now. If this is still a problem (using a modern version of Apollo Client), please let us know. Thanks!

**Comment by hyperh** [comment]
Running into something similar. Looking at this code: https://github.com/apollographql/apollo-client/blob/c44e8211268e808106e81da7665f65f81fac2baf/packages/apollo-client/src/core/ObservableQuery.ts#L387

Seems like you need to unsubscribe then restart the subscription. I believe `subscribeToMore` returns the unsubscription function.
