### ISSUE TITLE
How to query by use state ?

### ISSUE THREAD

**Issue by vistriter** [apollographql/apollo-client#3181]
It's can't read state. I want to result to this page and add a user to an array of this page. So I can't separate this searchQuery to another component.

If I separate search component I must use redux to get user result value when selected user to the main component.

![screen shot 2561-03-21 at 14 41 20](https://user-images.githubusercontent.com/24702575/37698562-0de7efc0-2d16-11e8-9a0b-c41e4e5f27ec.png)

**Comment by hwillson** [comment]
In this case (if I understand your question correctly), you'll want to find a way to pass your `username` into the component created from the `graphql(USER_SEARCH_QUERY...` call, via `props`. Have you considered using something like Recompose's [`withState`](https://github.com/acdlite/recompose/blob/master/docs/API.md#withstate)? Check out the [Simplify your React components with Apollo and Recompose](https://dev-blog.apollodata.com/simplify-your-react-components-with-apollo-and-recompose-8b9e302dea51) blog post for examples that leverage `withState` to pass props into `graphql` created HOC's.
