### ISSUE TITLE
apollo-boost with next.js

### ISSUE THREAD

**Issue by lifeiscontent** [apollographql/apollo-client#3190]
Hello! I just tried using apollo-bost with this next.js example:

https://github.com/zeit/next.js/tree/canary/examples/with-apollo

swapping out only the client causes errors. Any ideas why?

Thanks!

**Comment by peggyrayzis** [comment]
With Next, I would recommend creating the client manually instead of using `apollo-boost`. Not sure why that example is using `apollo-boost`, I'll have to get in touch with the maintainers to fix it.

**Comment by lifeiscontent** [comment]
@peggyrayzis they aren't. I was just trying to use it swapping out the example code for apollo-boost as I said above.

**Comment by ooade** [comment]
@peggyrayzis the way they're using it is quite weird but still okay. They decided to use it as a preset instead of just adding them individually.

**Comment by hwillson** [comment]
The [next.js Apollo Example](https://github.com/zeit/next.js/tree/canary/examples/with-apollo) has been recently updated, so closing this for now. Thanks!
