### ISSUE TITLE
Migrating from 1.0 page looks weird on the site

### ISSUE THREAD

**Issue by deadcoder0904** [apollographql/apollo-client#3194]
Checkout [Migrating from 1.0](https://www.apollographql.com/docs/react/2.0-migration.html), its weirdly printed on the website but on [Github](https://github.com/apollographql/apollo-client/tree/master/docs/source/2.0-migration.md) it looks good. 

I was just looking how the old one compares with the new one, not migrating myself so not a problem for me.

**Comment by peggyrayzis** [comment]
Sorry about that! We recently switched over our docs site: https://www.apollographql.com/docs/react/recipes/2.0-migration.html

**Comment by deadcoder0904** [comment]
Hey Peggy, it still looks broken though at a lot of places. Not that I care of that page, but for some folks it might be unreadable.

<img width="1025" alt="apollo" src="https://user-images.githubusercontent.com/16436270/37816573-95062e2a-2e99-11e8-85a8-3e4785d6b078.png">
