### ISSUE TITLE
MaybeDeepFreeze - TypeError: Cannot freeze array buffer views with elements

### ISSUE THREAD

**Issue by k4r1** [apollographql/apollo-client#3195]
When trying to perform a query with a particular field included, I am getting the error from Apollo: 
`TypeError: Cannot freeze array buffer views with elements`

I have tested the query on GraphiQL and it returns fine, and omitting the problem-field fixes the issue.

The field in question needs to return an array of arbitrary objects. 

I have created a new `GraphQLScalarType` called `ObjectType` as suggested [here](https://stackoverflow.com/questions/33819658/dynamic-unique-objects-in-graphql), and my field has `{type: [ObjectType]}`.

So far, I have been able to work around the issue by not setting my `NODE_ENV` to `development`, although this is far from ideal. 

Any idea what I can do to get around this? Is there some extra check that needs to be done in `maybeDeepFreeze`, or a better way to suppress/ignore this error? 

**Version**
- apollo-client@2.2.7

**Comment by hwillson** [comment]
Hi @k4r1 - is this still happening with a more current version of `apollo-client` (e.g. 2.3.1)? If so, any chance you could put together a small runnable reproduction that shows this happening?
