### ISSUE TITLE
WebSocket connection closing occasionally

### ISSUE THREAD

**Issue by gijo-varghese** [apollographql/apollo-client#3196]
After building a VueJS app with Apollo Server graphql and vue-apollo for the client, the socket is occasionally disconnected on the first load itself. (It won't happen every time, maybe once in every 5-10 loads). Whats the reason for this?

![152173961846741591](https://user-images.githubusercontent.com/23092846/37788250-ee626470-2e26-11e8-94bd-389fbdfdbd39.gif)
![screenshot from 2018-03-22 21-24-13](https://user-images.githubusercontent.com/23092846/37788252-ee9814d0-2e26-11e8-84cd-09f4f409313b.png)

**Comment by hwillson** [comment]
Hi @gijo-varghese - is this problem still happening with a recent version of `apollo-client` (e.g. 2.3.1)? If so, would you be able to supply a small runnable reproduction that demonstrates this? Thanks!

**Comment by hwillson** [comment]
We haven't heard back regarding a reproduction, so closing for now. Thanks!
