### ISSUE TITLE
offline resolver?

### ISSUE THREAD

**Issue by yorrd** [apollographql/apollo-client#3198]
My background is in the meteor/DDP world where databases pretty much exist on the client and the server as long as you subscribe to them. That also means, you can subscribe to raw data and then fetch different arrangements of that data without having to contact the server again at all. 

As far as I understand, this is not something you would do with Apollo client, but rather fetch a query for every arrangement of the same data from the server. Am I missing something here? Is the overhead so small that your can basically ignore this issue? Can this be done with an Apollo link (applying common practices of Apollo and in a day's work or so)?

I would love a pointer in the right direction. Thanks!

**Comment by hwillson** [comment]
Check out the [Caching data](https://www.apollographql.com/docs/react/advanced/caching.html) section of the Apollo Client docs, in particular the [Direct Cache access](https://www.apollographql.com/docs/react/advanced/caching.html#direct) sub-section. Apollo Client provides a way to query (and update) directly against content stored in a cache. You could preload the cache once, then have all future queries run against the cache only.
