### ISSUE TITLE
why cant i set errorPolicy on mutation ?

### ISSUE THREAD

**Issue by testbuddy** [apollographql/apollo-client#3208]
**Intended outcome:**

on Query Component and on Mutation Component i can set errorPolicy

**Actual outcome:**

i can only set errorPolicy on query, but cant do it on the new Mutation Components
is there a reason why someone cant do this anymore ?

**Version**
- apollo-client@<2.2.7>

/label question

**Comment by testbuddy** [comment]
okay i find out u can still set it in the options maybe someone should update the docs

**Comment by TihomirIvanov** [comment]
It is strange that it still works as a default option for ApolloClient and as an option when calling the mutate, but not as option of the graphql HOC. Is there a reason for that?
