### ISSUE TITLE
Having different headers for different requests?

### ISSUE THREAD

**Issue by wawhal** [apollographql/apollo-client#3216]
The docs talk about adding headers to the client while instantiating it. But what if I want to have different headers for different requests?

One hacky way is to instantiate the client every time I wish to make a request.

But what is the right way to do this?

**Comment by apehead** [comment]
You can check the [passing context per query](https://www.apollographql.com/docs/link/links/http.html#passing-context) section in the docs. Also the [apollo-link-context](https://www.apollographql.com/docs/link/links/context.html) could help you with this.

Probably the easiest way to achieve this is by setting the context in the query/mutation itself:
```
<Query
  query={MY_QUERY}
  context={{ headers: { 'my-header': 'header content' }}}
>
```
Use the approach that best fits you.

**Comment by hwillson** [comment]
Great answers in https://github.com/apollographql/apollo-client/issues/3216#issuecomment-383495405 - closing. Thanks!
