### ISSUE TITLE
Access to HTTP status code in global error handling using apollo-client 2

### ISSUE THREAD

**Issue by bellianth** [apollographql/apollo-client#3226]
Im trying to get HTTP error status code or anything that identifies the complete cause of the network error when i encounter it using [react-apollo][1].

It seems that we previously could use `afterware` and `createNetworkInterface` by setting `networkInterface.useAfter([{ applyAfterware: handleErrors, }])` according to [this comment][2] and [this conclusion][3] in the version 1.x releases.

After `createNetworkInterface` has been gone since version 2 was released and according to the [Apollo graphql official document on network layers][4], we should use afterwares In the specified syntax like this.

	const logoutLink = onError(({ networkError }) => {
	  if (networkError.statusCode === 401) logout();
	})

this problem is the `networkError` has `Error` typeface and of curse We will encounter `property 'statusCode' does not exist on type 'Error'` error.
<img width="464" alt="screen shot 2018-03-28 at 18 55 47" src="https://user-images.githubusercontent.com/37875457/38038565-7d77eaac-32c0-11e8-85fd-3839c4e1d978.png">

 Here is the declares typefaces for onError parameters:

	interface Error {
	    name: string;
	    message: string;
	    stack?: string;
	}

	export interface ErrorResponse {
	  graphQLErrors?: GraphQLError[];
	  networkError?: Error;
	  response?: ExecutionResult;
	  operation: Operation;
	}

Here is my apollo configurations:

	import {ApolloLink, from} from 'apollo-link';
	import {application} from '../../constants/application';
	import {ApolloClient} from 'apollo-client';
	import {InMemoryCache} from 'apollo-cache-inmemory';
	import {BatchHttpLink} from 'apollo-link-batch-http';
	import {tokenStorage} from '../middleware';
	import {debugHelper} from '../helpers';
	import {onError} from 'apollo-link-error';

	const API = new BatchHttpLink({
	    uri: application.API.URL
	});

	const cache = new InMemoryCache({
	});

	const afterWareLink = onError(({operation, response, graphQLErrors, networkError}) => {
	    debugHelper.error('apolloError', {
	        operation: operation,
	        response: response,
	        graphQLErrors: graphQLErrors,
	        networkError: networkError
	    });
	});

	const middleWareLink = new ApolloLink((operation, forward) => {
	    const token = tokenStorage.get();
	    operation.setContext(context => ({
	        ...context,
	        headers: {
	            ...context.headers,
	            token: token ? token.token : '',
	        },
	    }));

	    return forward(operation);
	});

	export const apolloClient = new ApolloClient({
	    link: from([
	        middleWareLink,
	        afterWareLink,
	        API
	    ]),
	    cache: cache,
	});

And here is the `networkError` content on a sample **403** error page.
<img width="743" alt="screen shot 2018-03-28 at 18 24 12" src="https://user-images.githubusercontent.com/37875457/38038546-70de4cd2-32c0-11e8-8d54-15d57ec2bfc4.png">

	{
		graphQLErrors: undefined,
		networkError: TypeError: Failed to fetch,
		operation: {variables: {…}, extensions: {…}, operationName: null, query: {…}, setContext: ƒ, …}
		response: undefined
	}

My react version is 16.2.0 and my apollo package version is:

	 {
	    "apollo-boost": "^0.1.4",
	    "apollo-cache-inmemory": "^1.1.12",
	    "apollo-client": "^2.2.8",
	    "apollo-client-preset": "^1.0.8",
	    "apollo-link-batch-http": "^1.2.1",
	    "apollo-link-error": "^1.0.7",
	    "apollo-link-http": "1.4.0",
	    "react-apollo": "^2.1.1",
	    // ...
	}

As you can see there is no clear reason that what is the cause of this error. So I'm looking for another way to get access to the HTTP status codes in **Unhandled Network Error**.

Thanks for your helps 🌹.

  [1]: https://github.com/apollographql/react-apollo
  [2]: https://github.com/apollographql/apollo-client/issues/1692#issuecomment-324702528
  [3]: https://github.com/apollographql/react-apollo/issues/604#issuecomment-355648596
  [4]: https://www.apollographql.com/docs/react/advanced/network-layer.html#linkAfterware
  [5]: https://i.stack.imgur.com/T5evW.png
  [6]: https://i.stack.imgur.com/Ij8EB.png

**Comment by jwb** [comment]
It's important to note that when the error is triggered by a the status of the HTTP response, the response body may be needed to properly recover from the error.

**Comment by mtoso** [comment]
I also have the same issue. Is this working on any previous version of the library?

**Comment by mhaagens** [comment]
Same issue here.

**Comment by lvlohammadi** [comment]
#https://github.com/apollographql/apollo-link/issues/300#issuecomment-387120102

**Comment by mhaagens** [comment]
I found a fix for this if you're using a node server, see my comment here;
https://github.com/apollographql/apollo-link/issues/300#issuecomment-387171702

**Comment by hwillson** [comment]
This is an `apollo-link-error` issue, and is being tracked in https://github.com/apollographql/apollo-link/issues/300. Closing here - thanks!
