### ISSUE TITLE
Incorrect Documentation for compose function

### ISSUE THREAD

**Issue by jfhoran** [apollographql/apollo-client#3227]
The documentation for the compose function at https://www.apollographql.com/docs/react/api/react-apollo.html#compose states that the enhancers are executed with the last one being first and then in reverse order from that. 

However I am seeing the opposite behavior in our app, with the props for example from an redux connect not being available to the graphql props function unless the connect is places _before_ the graphql function. Is this the intended functionality?

I'd be happy to put in a PR for the documentation I jus first want to ensure I am not way off base here :)

**Comment by hwillson** [comment]
The following section from [the docs](https://www.apollographql.com/docs/react/api/react-apollo.html#compose) should be accurate:

> An important note is that `compose()` executes the last enhancer first and works its way backwards through the list of enhancers. To illustrate calling three functions like this: `funcC(funcB(funcA(component)))` is equivalent to calling `compose()` like this: `compose(funcC, funcB, funcA)(component)`.

The example is the important part (which helps clarify the "last enhancer first" sentence). If you're noticing something different, definitely let us know. Thanks!
