### ISSUE TITLE
perf benchmark vs. immutable+redux+reselect

### ISSUE THREAD

**Issue by anthonychung14** [apollographql/apollo-client#3229]
**Intended outcome:**
We are debating moving from React/Immutable/Redux/Reselect towards depending on Apollo's in-memory cache. 

In order to be convinced, I think it'd be necessary to create benchmarks for my team to demonstrate the following.

1. reads are faster for user
2. logic is easier to write for devs
3. not too much storage overhead 
4. writes/updates happen faster
5. state management comparison of containers with selectors (via redux) vs. `Query` components with queries.
6. large query payload requests and processing is faster

I understand that Apollo's datastore will naturally be leaner than an immutable one (since it's just a plain object with denormalized keys), but will it/can it really outperform a data store with an immutable API that makes use of structural sharing?

**Actual outcome:**
A short explanation of how Apollo can be a viable/scalable alternative for large data stores compared to the overhead that Immutable might have would be greatly appreciated!

**How to reproduce the issue:**
- N/A

**Version**
- apollo-client@2.2.5

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=perf%20benchmark%20vs.%20immutable%2Bredux%2Breselect&body=Migrated%20from:%20apollographql/apollo-client%233229) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
