### ISSUE TITLE
Could not find __typename__ on Fragment

### ISSUE THREAD

**Issue by MJones180** [apollographql/apollo-client#3249]
Throughout my code I use fragments to break up the data requirements. However, in the header I have a simple query:

```
query: gql`
  query HeaderUser {
    me {
      nameFirst
      nameLast
    }
  }
`
```
Sometimes this Query returns null (`{ me: null }`) and Apollo Client raises a really annoying error each time: `You're using fragments in your queries, but either don't have the addTypename: true option set in Apollo Client, or you are trying to write a fragment to the store without the __typename. Please turn on the addTypename option and include __typename when writing fragments so that Apollo Client can accurately match fragments.` and `Could not find __typename on Fragment  Query {me: null}`. This is really weird because I am not even using fragments in this case. Is there a way to remove this error?

**Version**
- apollo-client@2.2.8

**EDIT**
I would also like to add that the error comes up on some responses that even do contain the `__fragment` field.

**Comment by hwillson** [comment]
The explanation outlined in https://github.com/apollographql/apollo-client/issues/3249#issuecomment-408583967 sounds quite reasonable. If that doesn't help, please provide a small runnable reproduction that clearly demonstrates this issue. Thanks!
