### ISSUE TITLE
Accept a callback for link property

### ISSUE THREAD

**Issue by caub** [apollographql/apollo-client#3250]
When reading https://www.apollographql.com/docs/react/advanced/subscriptions.html#subscriptions-client

I think the API using apollo-link's `split`:
```js
const link = split(
  // split based on operation type
  ({ query }) => {
    const { kind, operation } = getMainDefinition(query);
    return kind === 'OperationDefinition' && operation === 'subscription';
  },
  wsLink,
  httpLink,
);
const client = new ApolloClient({
  link,
  cache: new InMemoryCache(),
});
```
could be simplified with an alternative way:
```js
const client = new ApolloClient({
  link: ({ query }) => {
    const { kind, operation } = getMainDefinition(query);
    return kind === 'OperationDefinition' && operation === 'subscription' ? wsLink : httpLink;
  },
  cache: new InMemoryCache(),
});
```
Just a proposition, it's maybe less efficient in performance though

There's this other way though
https://github.com/apollographql/graphql-tutorial/blob/b8cbd97d9aea4d3da54d2a3ad657af9653e49930/client/src/App.js#L16-L39

**Comment by hwillson** [comment]
Thanks for the suggestion @caub. Yes, in this case the example would work as you've identified. That being said, the `split` approach in the example might be trivial, but it does show how `split` can be used (which can then be applied to more sophisticated code). The `split` approach is more declarative (similar in concept to Recompose's [`branch`](https://github.com/acdlite/recompose/blob/master/docs/API.md#branch) function), which is something that Apollo/GraphQL ecosystem users are likely familiar with. Thanks!
