### ISSUE TITLE
Data returned from queries is read-only

### ISSUE THREAD

**Issue by jaredloomis** [apollographql/apollo-client#3255]
**Intended outcome:**

```javascript
client.query({
    query: gql`query {people {id name}}`
}).then(ret => {
    const people = ret.data.people
    const person = people[0]
    person.id = "sdfgsdfg"
})
```
This code should not produce an error. I would expect a normal JavaScript object to be returned.

**Actual outcome:**

Console error: `Cannot assign to read only property '_id' of object '#<Object>'`.

**How to reproduce the issue:**

Open https://l732o78pq7.codesandbox.io/ in browser.
View console.
Should see `Cannot assign to read only property '_id' of object '#<Object>'`.

Code at https://codesandbox.io/s/l732o78pq7

**Version**
- apollo-client@2.2.4

**Comment by plck** [comment]
Probably the same as https://github.com/apollographql/apollo-angular/issues/306
Lots of people pointed out this problem in different issues, no official solution so far.

**Comment by sunheartGH** [comment]
I get same problem, there is a lot cases to modify query data, but get read only error.
I have use `Object.assign({}, data)`, this not work for deep field,
for now I just use `JSON.parse(JSON.stringify(data))` to process query data.
hopeful official can give some better solution.

**Comment by hmeerlo** [comment]
You can't even do simple things like client side sorting of the data. That can not be the intention I guess.

**Comment by felixus95** [comment]
Really annoying! We need to reverse(), but data doesn't allow to do so.

**Comment by stonecold123** [comment]
No problem in reactJs, but I am getting this error in local resolvers for react native.

**Comment by arshbhatti8** [comment]
I have the same issue. I'm trying to sort the returning data and then display it as a list. I thought I could use `Lodash's Deep Copy` but that breaks the subscribe function and needs me to then refresh the page to get new data (In the age of AJAX...).

The issue is also discussed here : https://github.com/apollographql/apollo-angular/issues/306

**Comment by hwillson** [comment]
Just a quick FYI; this is currently intentional, but we're re-considering it in https://github.com/apollographql/apollo-client/issues/1909.

**Comment by jbaxleyiii** [comment]
Thanks for reporting this. There hasn't been any activity here in quite some time, so we'll close this issue for now. If this is still a problem (using a modern version of Apollo Client), please let us know. Thanks!
