### ISSUE TITLE
Allow a type of dummy query so it can be filled by a subscription

### ISSUE THREAD

**Issue by theodorDiaconu** [apollographql/apollo-client#3259]
We want to have a query which has the state fully managed by a subscription. Including the initial adds and subsequent changes.

We could keep the same API, but allow a `dummy={true}` to the <Query /> component, and then also have a sort of way to mark the Query as ready, when all the data from the subscription has been filled out.

Is there a current way to achieve this ? 

- [ ] has-reproduction
- [x] feature
- [ ] docs
- [ ] blocking
- [ ] good first issue

**Comment by theodorDiaconu** [comment]
I see that we have this:
`If delay is true, the Query component will not fetch the query on mount although its children will still render. Use delay with load in the render prop function to manually fire the query.`

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Allow%20a%20type%20of%20dummy%20query%20so%20it%20can%20be%20filled%20by%20a%20subscription&body=Migrated%20from:%20apollographql/apollo-client%233259) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
