### ISSUE TITLE
Why is `isCurrentlyPolling` private?

### ISSUE THREAD

**Issue by whtsky** [apollographql/apollo-client#3260]
I'm implementing data polling w/ apollo and find it a bit strange for apollo making `isCurrentlyPolling` private.
https://github.com/apollographql/apollo-client/blob/1c9cd5da282211d333fd7c8bfca2d984964987a4/packages/apollo-client/src/core/ObservableQuery.ts#L69

Right now I have to maintain a local `isCurrentPolling` variable in my application code which might not be always accurate. And react-apollo's test is using a local variable to track polling state too: 
https://github.com/apollographql/react-apollo/blob/884d81f349455924b88052559a9e006b2bb8e2f3/test/client/Query.test.tsx#L374

I'm just wondering why `isCurrentlyPolling` is private, IMO it just make life harder for users :(

**Comment by hwillson** [comment]
Good point @whtsky - we should be able to open this up a bit. Thanks!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Why%20is%20%60isCurrentlyPolling%60%20private%3F&body=Migrated%20from:%20apollographql/apollo-client%233260) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
