### ISSUE TITLE
Release v1.9.4 from latest branch

### ISSUE THREAD

**Issue by ThomWright** [apollographql/apollo-client#3261]
**Version**
- apollo-client@1.9.3

- [ ] has-reproduction
- [ ] feature
- [ ] docs
- [x] blocking
- [ ] good first issue

This contains an important fix from #3157

**Comment by ThomWright** [comment]
@jbaxleyiii ? Anyone?

**Comment by ThomWright** [comment]
srsly tho

**Comment by ThomWright** [comment]
```sh
git checkout latest
npm version patch
npm run deploy
```

**Comment by tomhicks** [comment]
This is affecting me, too.

**Comment by hwillson** [comment]
@ThomWright @tomhicks is this still an issue? I'd like to avoid pushing out 1.x patches unless it's absolutely necessary. If this is still holding you guys up, please let me know. Thanks!

**Comment by hwillson** [comment]
Closing for now (let us know if this is still an issue - see https://github.com/apollographql/apollo-client/issues/3261#issuecomment-408517859). Thanks!
