### ISSUE TITLE
ApolloError `message` is empty and `.toString()` returns "Error"

### ISSUE THREAD

**Issue by kronick** [apollographql/apollo-client#3263]
**Intended outcome:**
Assuming I already have an Apollo Client object `client` set up, and a "bad" GraphQL query (that the server won't understand) `mutationQuery`:

```
client.mutate({mutation: mutationQuery})
  .catch(error => console.log(error))
```

I want the error be printed as `Bad Request` or get some additional info about what caused the error. This is especially important in a chain of promises when I can't be sure that the caught error is an `ApolloError` object without inspecting it.

**Actual outcome:**
`console.log(error)` prints "`Error`" with no additional information. `error.toString()` returns `"Error"`.

Debugging the `error` object, I see it looks like:
```
{
  graphQLErrors: "Bad Request",
  networkError: null,
  message: "",
  ...
}
```
**How to reproduce the issue:**
Code sample above.

It looks like `ApolloError` does some [checking to try and avoid creating an empty `message` property](https://github.com/apollographql/apollo-client/blob/5eba9b555bbce73cc4beb666ded755705879721b/packages/apollo-client/src/errors/ApolloError.ts#L60-L63), but it only checks if `message` is undefined, not if it is an empty string. Additionally, it doesn't look like `.toString()` returns the `message`.

**Version**
- apollo-client@2.2.8

**Comment by hwillson** [comment]
This should no longer be an issue with modern day versions of Apollo Client. If you're still encountering this issue after updating, please post back. Thanks!
