### ISSUE TITLE
is it possible to call mutation graphql request through simple plain okhttp request ?because when i use query insted of mutatuion it is all ok,but when i use mutation ,many different response get like syntex or document need error 400.

### ISSUE THREAD

**Issue by Ali-zain-javed** [apollographql/apollo-client#3268]
**Intended outcome:**

**Actual outcome:**

**How to reproduce the issue:**

**Version**
- apollo-client@<version number>

**Comment by hwillson** [comment]
If you're able to provide an example of what you're attempting to do, that would greatly help with troubleshooting. Closing for now - thanks!
