### ISSUE TITLE
Documentation for typesafe named mutation queries is inadequate

### ISSUE THREAD

**Issue by koblas** [apollographql/apollo-client#3271]
**Intended outcome:**
I'm trying to port code from react-apollo 2.0 to 2.1, with named mutations. Expect to be able to write code that will compile.

https://www.apollographql.com/docs/react/recipes/static-typing.html

**Actual outcome:**
At the moment there are enough issues in the documentation that it's not possible to do this.

**How to reproduce the issue:**

1. Reading the example code fragments shows many errors that are not valid code (missing > and double >>)
2. The ```Request``` and ```Args``` values are interchanged to type definitions
3. No examples of mutations

**Version**
- react-apollo@2.1.3
- apollo-client@2.2.8
- graphql@0.13.2

**Issue Labels**

- [ ] has-reproduction
- [ ] feature
- [x] docs
- [ ] blocking
- [ ] good first issue

**Example code**

This is the code that I'm trying to port from 2.0 to 2.1 for reference.

    const MUTATION = gql`
      mutation ($input: UserUpdateInput!) {
        user_update(input: $input) {
          validationErrors {
            field
            message
          }
          user {
            id
            email
            name
            avatarUrl
          }
        }
      }
    `;
  
    export interface Response {
      data: {
        user_update: {
          user?: UserQuery.UserType;
          validationErrors?: ValidationError[];
        };
      };
    }
  
    export interface Args {
      input: {
        email?: string;
        name?: string;
        newpass?: string;
        password?: string;
      }
    }
  
    export const mutation = graphql<Response, Args>(MUTATION, {
      props: ({ mutate }: any) => ({
        userUpdate: (input: Args) => mutate({ variables: { input } }),
      }),
    });

**Comment by lstanden** [comment]
I'm sorry, it was months ago I was looking at this, and don't have the specific example code I was using to refer to.  I was literally working through the examples in the documentation above, so starting there would be a good place.

**Comment by hwillson** [comment]
Thanks @lstanden - the docs have changed quite a bit since then, so it's possible this issue has been fixed. I'll close this for now, but will happily re-open this issue if anyone runs into this and can provide more details. Thanks!

**Comment by reverie** [comment]
@hwillson Here are a few questions :)

If I use `withApollo` on a component, 'client' is a required parameter. How do I pass in client when I'm rendering that component from a parent?

Where is the documentation for the type parameters to `graphql`?

What are `ChildProps` and `ChildDataProps`? There are some unexplained examples, but I can't find any docs.
