### ISSUE TITLE
Error in getting started example

### ISSUE THREAD

**Issue by mixolydian251** [apollographql/apollo-client#3273]
**Intended outcome:**
The following code in the first getting started react example should display currencies.

```
const ExchangeRates = () => (
  <Query
    query={gql'
      {
        rates(currency: "USD") {
          currency
          rate
        }
      }
    '}
  >
    {({ loading, error, data }) => {
      if (loading) return <p>Loading...</p>;
      if (error) return <p>Error :(</p>;

      return data.rates.map(({ currency, rate }) => (
        <div key={currency}>
          <p>{`${currency}: ${rate}`}</p>
        </div>
      ));
    }}
  </Query>
);
```

**Actual outcome:**
This code produces this error

`Uncaught Error: Query.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.`

**How to reproduce the issue:**

This happens every time. In the documentation, the child function returns an array instead a component.

**Version**
- apollo-client@<2.1.2>

**Comment by Wizyma** [comment]
Hi ! 
I'm gonna check that if nobody is in it !

**Comment by Wizyma** [comment]
I just tried you exact code it has no error, you probably have one because you use singlequotes instead of backquotes

**Comment by rafaelrene** [comment]
I have the same issue and I definitely us back quotes instead of single quotes. Also when I just try to render one element it works, but when it's an array of elements I get an error.

**Comment by mixolydian251** [comment]
Which version of React are you using? In version 16+ you can render arrays. Once I upgraded, the original example worked for me.

**Comment by mixolydian251** [comment]
Which version of React are you using? In version 16+ you can render arrays. Try upgrading to the latest version, and let me know if you still have an issue. If that fixes the problem, I will go ahead and close this issue.

**Comment by rafaelrene** [comment]
@Wizyma Example code is the same as @mixolydian251 showed. When I was trying without array, I simply picked first thing in the array instead of mapping over the array.

@mixolydian251 I am indeed using this with react 15. React 16 seems to work well.

**Comment by Wizyma** [comment]
@rafaelrene  thats probably why i didn't had the issue i was on react 16
