### ISSUE TITLE
Element type error in the Query component

### ISSUE THREAD

**Issue by diegomr86** [apollographql/apollo-client#3286]
**Intended outcome:**
List of Dogs
**Actual outcome:**
Getting this error:
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Dogs`.

**How to reproduce the issue:**

This is my code:

`
import React, { Component } from 'react'
import gql from "graphql-tag";
import { Query } from "react-apollo";

const GET_DOGS = gql`
  {
    dogs {
      id
      breed
    }
  }
`;

export default Dogs = ({ onDogSelected }) => (
  <Query query={GET_DOGS}>
    {({ loading, error, data }) => {
      if (loading) return "Loading...";
      if (error) return `Error! ${error.message}`;

      return (
        <select name="dog" onChange={onDogSelected}>
          {data.dogs.map(dog => (
            <option key={dog.id} value={dog.breed}>
              {dog.breed}
            </option>
          ))}
        </select>
      );
    }}
  </Query>
);

`

**Version**
- apollo-client@2.2.8

**Comment by zpeterg** [comment]
I'm having a similar problem.

**Comment by zpeterg** [comment]
I'm not sure this is the same problem... but mine was related to "Query" being null when imported from react-apollo. It seems that over the last few months the package changed and I had to update to the more recent packages.

**Comment by harlandduman** [comment]
I'm having the same issue @zpeterg. It seems like my Query component isn't being properly imported from react-apollo. I tried updating react-apollo and apollo-client to the latest version but still can't get it to work. Did you get it to work for you?

**Comment by zpeterg** [comment]
I believe I solved it by making sure that all my dependencies and client
connection followed this guide:

https://www.apollographql.com/docs/react/advanced/boost-migration.html

And I also updated all to the latest packages and installed them fresh with
yarn.  Then it worked fine. Hope that helps!

**Comment by abinoda** [comment]
@diegomr86 @zpeterg @harlandduman I am having the exact same issue. I just tried the boost migration but that didn't resolve my issue. Any other tips?

**Comment by abinoda** [comment]
@diegomr86 @zpeterg @harlandduman Just resolved it by running `npm install react-apollo@latest`. Seems like it may have been a versioning issue.

**Comment by hwillson** [comment]
Sounds like this has been resolved - closing, thanks!
