### ISSUE TITLE
writeQuery doesn't update/rerender/refetch the component(s) 

### ISSUE THREAD

**Issue by dennislaupman** [apollographql/apollo-client#3301]
Hello,

writeQuery doesn't update/rerender/refetch the component(s) connected to the submitResponse query.

```
update: (proxy, { data: { submitResponse } }) => {
          const data = proxy.readQuery({
            query: ResponsesViewQuery,
            variables: { 
              id: params.castId,
            }            
          });
         data.responses.push(data.responses[
         
         console.log(data.responses);
   
         proxy.writeQuery({ query: ResponsesViewQuery, data });
}
```

Grtz Dennis

**Comment by mkrn** [comment]
I think what seem to happen here, and what is not covered in documentation is use of variables with readQuery / writeQuery.
I've just had a similar situation, and it did not work until I got rid of variables.
Additionally, should you try to add same variables to writeQuery?

**Comment by hwillson** [comment]
Any chance you could provide a small runnable reproduction that demonstrates this issue? Thanks!

**Comment by rosskevin** [comment]
Duplicate of #2415

**Comment by danilobuerger** [comment]
Closing as no reproduction was provided in one week. Feel free to reopen if you have a minimal reproduction.
