### ISSUE TITLE
Custom Request Header

### ISSUE THREAD

**Issue by marshallharry** [apollographql/apollo-client#3302]
Hi, this is not an issue actually.
I want to ask, could I add custom header (e.g. 'my-header': "hello") in apollo-client?
Because I try to add but it seems not working, the request is not sent.
Thanks.

**Comment by PascalSenn** [comment]
Try this:
https://www.apollographql.com/docs/react/recipes/authentication.html#Header

**Comment by marshallharry** [comment]
hi @PascalSenn 
thank you for the answer.
but, it only accept headers that are listed at here: https://en.wikipedia.org/wiki/List_of_HTTP_header_fields

I want a header that looked exactly like this:
my-header: hello

**Comment by PascalSenn** [comment]
did you try something like
` 'my-header': 'hello', `

**Comment by marshallharry** [comment]
yes, here's the code :

import fetch from 'isomorphic-fetch';
import { ApolloClient } from 'apollo-client';
import { from } from 'apollo-link';
import { onError } from 'apollo-link-error';
import { HttpLink } from 'apollo-link-http';
import apolloLogger from 'apollo-link-logger';
import createCache from './createCache';
import { setContext } from 'apollo-link-context';

const customFetch = (uri, options) => {
  const opts = {
    ...options,
  };

  return fetch(uri, opts);
};

const authLink = setContext((_, { headers }) => {
  return {
    headers: {
      ...headers,
      'my-header': "hello",
    }
  }
});

const httpLink = from([
  onError(({ graphQLErrors, networkError }) => {
    if (graphQLErrors)
      graphQLErrors.map(({ message, locations, path }) =>
        console.warn(
          `[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`,
        ),
      );
    if (networkError) console.warn(`[Network error]: ${networkError}`);
  }),
  ...(__DEV__ ? [apolloLogger] : []),
  new HttpLink({
    uri: 'http://localhost:9000/',
    credentials: 'include',
    fetch: customFetch,
  }),
]);

const cache = createCache();

export default function createApolloClient() {
  return new ApolloClient({
    link: authLink.concat(httpLink),
    cache: cache.restore(window.App.apolloState),
    queryDeduplication: true,
    connectToDevTools: true,
  });
}

**Comment by marshallharry** [comment]
if I change it to something like:
`authorization: "hello",`

its working

**Comment by Imagica** [comment]
Anyone have an answer for this? I have the same issue

**Comment by hwillson** [comment]
Setting custom headers should work properly. If anyone is still encountering this issue, please provide a small runnable reproduction. Thanks!

**Comment by arianofaoms** [comment]
@hwillson  I'm having the same issue using custom header but I get the error: data:  Error: Network error: Failed to construct 'Headers': Invalid value

I used the example provided in the documentation and got the following:
![image](https://user-images.githubusercontent.com/52330044/64446311-7c4bc600-d0a6-11e9-879b-56f0db0a9b9d.png)

When I comment out "Company" key it works but I won't be able to login obviously. Any ideas?

**Comment by arianofaoms** [comment]
@hwillson  MY MISTAKE! I'm sorry. I was setting the header to a function instead of its string value. Totally unrelated. That's what happens when you code for 10 hours lol.

**Comment by kieraneglin** [comment]
For future Googlers:

In my case this was caused by not setting up `Access-Control-Allow-Headers` correctly on my server, causing a CORS issue

**Comment by rajanbharti** [comment]
I am having same issue. Here is my GraphQLModule file
```import {NgModule} from '@angular/core';
import {ApolloModule, APOLLO_OPTIONS} from 'apollo-angular';
import {HttpLinkModule, HttpLink} from 'apollo-angular-link-http';
import {environment} from '../environments/environment';
import {ApolloLink, concat} from 'apollo-link';

const storeUrl = environment.storeUrl;

export function createApollo(httpLink: HttpLink) {


  const http = httpLink.create({uri: storeUrl});

  const authLink = new ApolloLink(((operation, forward) => {
    operation.setContext(({ headers = {} }) => ({
      ...headers,
      headers: {
        'X-Shopify-Storefront-Access-Token': environment.storeToken
      }
    }));
    return forward(operation);
  }));

  return {
    link: concat(http, authLink)
  };
}

@NgModule({
  exports: [ApolloModule, HttpLinkModule],
  providers: [
    {
      provide: APOLLO_OPTIONS,
      useFactory: createApollo,
      deps: [HttpLink],
    },
  ],
})
export class GraphQLModule {
}
```

here is my component file

```import {Component, OnInit} from '@angular/core';
import {Subscription} from 'rxjs';
import {Apollo} from 'apollo-angular';
import gql from 'graphql-tag';

const productQuery = gql`
query getProducts {
  products(first:10) {
    edges {
      node {
        id
        title
        }
      }
    }
  }
  `;

@Component({
  selector: 'app-product',
  templateUrl: './product.component.html',
  styleUrls: ['./product.component.scss']
})
export class ProductComponent implements OnInit {

  private querySubscription: Subscription;

  private data;

  constructor(private  apollo: Apollo) {
  }

  ngOnInit(): void {
    this.querySubscription = this.apollo.watchQuery<any>({query: productQuery})
      .valueChanges.subscribe(({data, loading}) => {
        this.data = data;
        console.log(this.data);
      });
  }

}
```

I am not getting that Shopify token, in my request headers.
I am getting it only when I explicitly pass in  query context.

**Comment by caribouflex** [comment]
@rajanbharti Did you found a solution, I have the exact same issue ?
