### ISSUE TITLE
Cant pass in BatchHttpLink to apollo-bost ApolloClient

### ISSUE THREAD

**Issue by karlAlnebratt** [apollographql/apollo-client#3304]
Hi
I'm trying to set up batch queries with apollo-bost.
But there is no setting for passing in a link instance.

```
export interface PresetConfig {
  request?: (operation: Operation) => Promise<void>;
  uri?: string;
  fetchOptions?: HttpLink.Options;
  clientState?: ClientStateConfig;
  onError?: ErrorLink.ErrorHandler;
  cacheRedirects?: CacheResolverMap;
}
```

Could we add a link config option? 

```
const httpLink = config && config.link ? config.link : new HttpLink({
```

https://github.com/apollographql/apollo-client/blob/a52e8e8317a30550177dca708103694725e5daa3/packages/apollo-boost/src/index.ts#L74

**Comment by hwillson** [comment]
Thanks for this suggestion. We're going to close this for now though since we are no longer accepting new feature requests for Apollo Boost. For a more detailed explanation of why, please see https://github.com/apollographql/apollo-client/pull/3720#issuecomment-410487476. Thanks again!
