### ISSUE TITLE
Step by Step guide to migrate from  apollo-client-preset@1.0.8 to apollo-boost

### ISSUE THREAD

**Issue by saostad** [apollographql/apollo-client#3310]
I got this message after npm i:

> npm WARN deprecated apollo-client-preset@1.0.8: for the best quick start with Apollo Client, please use apollo-boost instead
 
I went to documents but I couldn't find any guide for migration.
can anybody provide a step by step guide please?

**Comment by hwillson** [comment]
Removing `apollo-client-preset` then following the [Apollo Boost getting started docs](https://www.apollographql.com/docs/react/essentials/get-started.html#apollo-boost), should be all that is needed. Thanks!
