### ISSUE TITLE
Network error: Can't find field on object (ROOT_QUERY) undefined.

### ISSUE THREAD

**Issue by ColinRyan** [apollographql/apollo-client#3311]
Hi guys,

I have a query being ran as so
```
client.query({
    query: gql`
        query ListEvents {
             listEvents {
                 items {
                     id
                 }
            }
       }
    `
}).then(...)
```
and it keeps giving me a network error saying 

```
Error: Network error: Can't find field listEvents on object (ROOT_QUERY) undefined.
```

I'm able to send queries via postman fine so I've messed something up on the frontend but I'm not sure what. Any ideas?

**Intended outcome:**
get data from graphql

**Actual outcome:**
```
Error: Network error: Can't find field listEvents on object (ROOT_QUERY) undefined.
```

**Version**
- apollo-client@2.2.8

**Comment by mjasnikovs** [comment]
Try, pleas let me know if this fixed for you. It worked for me.

```JavaScript
npm install --save apollo-cache-inmemory@1.1.11
```

**Comment by hwillson** [comment]
There isn't much here to work with in terms of helping guide you towards a solution. If you're able to share your code, we can definitely take a quick look and help out. Closing for now - thanks!
