### ISSUE TITLE
Using Query and Mutation together

### ISSUE THREAD

**Issue by paschaldev** [apollographql/apollo-client#3326]
I need help urgently because I could't find any docs online on how to solve this problem. 

I have a component that uses `Query`, I would like to also run a mutation and after that mutation is complete, refresh my `Query`.

Use case scenario: I have a list of users that was fetched via `<Query /> component with checkbox beside each, after selection and clicking a delete button, I want to run a mutation and after that is complet, refresh my initial query so the component can be updated

`/label help`

**Comment by Wizyma** [comment]
Did you try using a subscription ?

**Comment by paschaldev** [comment]
I ended up using `apollo-link`. Solves the problem exactly how I want it. now I use both Apollo Client and Apollo Link in same component. I don't know if I'm doing it the wrong way.

**Comment by paschaldev** [comment]
Thanks @ahujaavi13 but that doesn't look like it could solve my problems. I need to trigger a refresh in one of the component methods bounded to `this`.

**Comment by hwillson** [comment]
Based on https://github.com/apollographql/apollo-client/issues/3326#issuecomment-381741727, it sounds like you've found a solution @paschaldev. Closing - thanks!
