### ISSUE TITLE
Apollo-boost: "Cannot set property 'defaultOptions' of undefined"

### ISSUE THREAD

**Issue by gihrig** [apollographql/apollo-client#3327]
/label Tips

**Intended outcome:**
Update existing app to use `gql` from `apollo-boost` in place of `graphql-tag`

**Actual outcome:**
Accessing a page so modified produces an error "Cannot set property 'defaultOptions' of undefined" in apollo-client

**How to reproduce the issue:**
Because the error is not helpful, and a Google search on the error turns up nothing, I'm posting the solution in hopes of saving someone else the pain I went through to figure it out.

The correct import from graphql-tag is:
```javascript
import gql from 'graphql-tag'
```
The correct import from apollo-boost is:
```javascript
import { gql } from 'apollo-boost'
```

It's easy to make the mistake of only replacing 'graphql-tag' with 'apollo-boost', leaving off the `{}`

**Version**
- apollo-boost@0.1.4

**Comment by nghiepit** [comment]
Hey, @gihrig I have the same issue. Can you help me fix this issue?

**Comment by murtukov** [comment]
This is gold!
