### ISSUE TITLE
Passing second argument to onCompleted callback on Mutation

### ISSUE THREAD

**Issue by schingeldi** [apollographql/apollo-client#3329]
Hi,

I would like to pass my react-router "history" to the onCompleted function of a Mutation. Is this possible and if so, how? So basically can I pass a second argument to that function some how?

Thanks a lot for help

**Version**
- apollo-client@2.1

- [ ] has-reproduction
- [ ] feature
- [x] docs
- [ ] blocking
- [ ] good first issue

**Comment by silvestrevivo** [comment]
I think that this works:

```
<Mutation mutation={SEND_MUTATION} onError={this.error} onCompleted={this.completed(this.props.history)}>
//....
</Mutation>

**Comment by hwillson** [comment]
You shouldn't need to pass in a second argument in this case. You can just do something like:

```jsx
<Mutation 
  mutation={SEND_MUTATION} 
  onError={this.error} 
  onCompleted={(data) => {
    const { history } = this.props.history;
    ... do something ...
  }}
>
  ...  
</Mutation>
```

**Comment by RIP21** [comment]
@hwillson what if you use HOC? How can you access ownProps to call, some binded to the parent component function to change its state?
