### ISSUE TITLE
vanilla js link dead in npm docs

### ISSUE THREAD

**Issue by cdaringe** [apollographql/apollo-client#3330]
**Intended outcome:**

- find usage docs for vanilla js

**Actual outcome:**

user sent to: https://www.apollographql.com/docs/react/reference

which is a `404`

**How to reproduce the issue:**

1. visit https://www.npmjs.com/package/apollo-client
1. click vanillajs link

**Version**
n/a

**Comment by FredericLatour** [comment]
Hi,
Is the apollo team reluctant to see apollo client being used directly?
I mean, as far as I can tell, even the code example on the readme is outdated - the uri property does not seem to exist anymore:

```javascript
import ApolloClient from 'apollo-boost';
const client = new ApolloClient({
  uri: 'https://graphql.example.com'
});
```
Of course, I understand this is open source and all ... but that's quite frustrating that it seems so difficult to find an updated example.

**Comment by FredericLatour** [comment]
Just in case, for those who may be struggling as well finding a working piece of code:

```javascript
import { ApolloClient, HttpLink, InMemoryCache } from 'apollo-boost'

export const apolloClient = new ApolloClient({
  link: new HttpLink({
    uri: 'http://localhost:3300/graphql'
  }),
  cache: new InMemoryCache()
})
```

**Comment by cdaringe** [comment]
my code looks similar.  the docs definitively used to have this great stuff!

**Comment by hwillson** [comment]
Thanks for reporting this! I'll fix the broken link in the README. It should be pointing directly to the [Apollo Client API](https://www.apollographql.com/docs/react/api/apollo-client.html) section of the docs. As for the other content in the README, it is accurate. `uri` is still a valid option when using `apollo-boost`. 

> Is the apollo team reluctant to see apollo client being used directly?

Not at all! If that's your preference, please by all means do so. Apollo Client was designed to be used independently, so it should be completely flexible in that regard. There just isn't that much else to document when it comes to using Apollo Client directly, without a view layer. You just have to instantiate it and then start making API calls.

**Comment by chgibb** [comment]
That link is also broken.
