### ISSUE TITLE
Polling breaks props change

### ISSUE THREAD

**Issue by steventebrinke** [apollographql/apollo-client#3333]
**Intended outcome:**
When query props are changed from `path: ["P1"]` to `path: ["P2"]`, I expect that the query is executed with `path: ["P2"]` and the results from this query are returned, also when `pollInterval` is set.

**Actual outcome:**
When `pollInterval` is not set, all works as expected. However, when `pollInterval` is set and the prop `path` changes from `["P1"]` to `["P2"]`, the following happens:
1. The query reruns with `path: ["P2"]` (as can be seen from the Chrome network console).
2. The results given to the `props` callback are from the query with `path: ["P1"]`, but `ownProps.path == ["P2"]`.
3. Every 30s the query reruns with `path: ["P1"]` (visible in the Chrome network console) and when there are updates, the `props` callback is called with the results from this query, but `ownProps.path == ["P2"]`.

**How to reproduce the issue:**
We are executing our queries within a large application, but the query looks as follows:
```gql
query TreeQuery($path: [String!]!) {
	tree(path: $path) {
		__typename
		_id
		name
	}
}
```
```js
graphql(TreeQuery, {
	options: {pollInterval: 30000},
	props: ({ownProps, data}) => {
		const {error, tree, refetch} = data;
		console.log(ownProps, tree);
		return {error, tree, refetch};
	},
})
```

**Version**
- apollo-client@2.2.8

**Comment by hwillson** [comment]
This should be fixed in modern day versions of Apollo Client. Please post back If you're still encountering this issue (and can provide a small runnable that demonstrates this problem). Thanks!
