### ISSUE TITLE
ssrMode in apollo-boost

### ISSUE THREAD

**Issue by herrstucki** [apollographql/apollo-client#3335]
**Intended outcome:**
I wanted to use `ssrMode` with `apollo-boost`.

Actually, I think it would be great if the `apollo-boost` client supported the same configuration options as the vanilla ApolloClient, so it would work more like a good set of defaults instead of limiting the user's options.

Or would it be possible for the client to infer `ssrMode` automatically based on environment detection? It's also not super-clear from the docs if `ssrMode` is _really_ necessary 🤔 

I'd be happy to help out with a PR if desired!

**Actual outcome:**
`ssrMode` is not in apollo-boost client's constructor types and also doesn't get passed to `super()`:

https://github.com/apollographql/apollo-client/blob/9d9dd5cb4b917644dc578b29c31878e41e35f899/packages/apollo-boost/src/index.ts#L88

**Version**
- apollo-boost@0.1.4

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=ssrMode%20in%20apollo-boost&body=Migrated%20from:%20apollographql/apollo-client%233335) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
