### ISSUE TITLE
initialState support in apollo-boost

### ISSUE THREAD

**Issue by gfpacheco** [apollographql/apollo-client#3340]
**Intended outcome:**

I wanted to pass a ssr-generated initial state to `InMemoryCache`. Something like this:

```
new ApolloClient({
  uri: '...',
  initialState: window.__APOLLO_STATE__,
});
```

**Actual outcome:**
The current apollo-boost client only accepts the `cacheRedirects` option for the `InMemoryCache`

**Version**
- apollo-client@0.1.4

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=initialState%20support%20in%20apollo-boost&body=Migrated%20from:%20apollographql/apollo-client%233340) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
