### ISSUE TITLE
cache-only fetchPolicy: error not passed to Query component if query cannot be resolved from cache

### ISSUE THREAD

**Issue by WickyNilliams** [apollographql/apollo-client#3343]
**Intended outcome:**

When using a `Query` component with a fetchPolicy of `cache-only`, if the query cannot be resolved from cache, I would expect `error` to be passed to the render prop:

```js
<Query
  query={queryThatCantBeResolvedFromCache}
  fetchPolicy="cache-only"
>
  {({ loading, data, error }) => {
    // expect `error` to be populated here
  }}
</Query>;
```

**Actual outcome:**

Would expect an error to be passed to render prop.

**How to reproduce the issue:**

https://codesandbox.io/s/p7vrkmlkmj

**Version**
- apollo-client@2.2.8

**Comment by jbaxleyiii** [comment]
Thanks for reporting this. There hasn't been any activity here in quite some time, so we'll close this issue for now. If this is still a problem (using a modern version of Apollo Client), please let us know. Thanks!
