### ISSUE TITLE
Documentation requires to be an experienced programmer. As a beginner, how can I tell you where I had problems ?

### ISSUE THREAD

**Issue by comteharbour** [apollographql/apollo-client#3349]
**Intended outcome:**
I'd like to be able to use Apollo Client 2 to query and mutate data from the server as well as local data.

**Actual outcome:**
It seems that, even if the concepts are powerful and elegant, the documentation is often unclear and requires to be an experienced programmer in many fields. Since Apollo 2 wants to make graphQL accessible to beginners, this could be a major issue.

**How to reproduce the issue:**
eg: https://www.apollographql.com/docs/react/essentials/local-state.html

example code:
```
const FilterLink = ({ filter, children }) => (
  <ApolloConsumer>
    {cache => (
      <Link
        onClick={() => cache.writeData({ data: { visibilityFilter: filter } })}
      >
        {children}
      </Link>
    )}
  </ApolloConsumer>
```
explanation:
"The ApolloConsumer render prop function is called with a single value, the Apollo Client instance."

problem:
In this example, the code seems to call the render prop function with the cache, but the explanation says this parameter is the client. It's confusing and makes you believe the cache and the client are the same thing. Plus, if you dive into the client and the cache code, they both have a writeData method. I was able to understand that the client and not the cache was used there thanks to the ApolloConsumer API.

solution:
use **client** instead of **cache** in the code

This kind of problems happen really all the time. And developping ready-to-use libraries like apollo-boost will be useless if beginners can't understand the documentation.

So, how can I alert you when I encounter such problems ?

**Version**
- apollo-client@2.any

/label docs
/label question

**Comment by hwillson** [comment]
Thanks for pointing this out @comteharbour. This will be fixed in the next `apollo-client` release. If you notice any other confusing items like this in the docs, please open new issues. Thanks!
