### ISSUE TITLE
apollo link middleware does not add custom headers to requests

### ISSUE THREAD

**Issue by mrdulin** [apollographql/apollo-client#3357]
**Intended outcome:**

I use `ApolloClient` imported from `apollo-boost`.

It should be add custom field to request headers when use middleware. 

**Actual outcome:**

It did't. 
I found this https://stackoverflow.com/questions/49805432/apollo-link-middleware-is-not-adding-custom-headers-to-requests
So, I replace `apollo-boost` with `apollo-client`. it works fine.

So, I think the problem is `apollo-boost`.

**How to reproduce the issue:**

```js
import { ApolloClient } from 'apollo-client';
import { HttpLink, concat, ApolloLink, InMemoryCache } from 'apollo-boost';
import { ApolloProvider } from 'react-apollo';

import App from './containers/app';
import Home from './containers/home';
import About from './containers/about';
import BookList from './containers/bookList';

const httpLink = new HttpLink({ uri: '/graphql' });
const authMiddleware = new ApolloLink((operation, forward) => {
  operation.setContext({
    headers: {
      authorization: localStorage.getItem('token') || 'default token'
    }
  });

  return forward(operation);
});
const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: concat(authMiddleware, httpLink)
});
```

**Version**
- apollo-boost@^0.1.4

**Comment by tngmichael** [comment]
See Advanced migration next to before https://www.apollographql.com/docs/react/advanced/boost-migration.html

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-client/issues/3357#issuecomment-383926573, please see the [Apollo Boost migration](https://www.apollographql.com/docs/react/advanced/boost-migration.html) section of the docs for an example. Thanks!

**Comment by alan345** [comment]
Here you have the answer: https://stackoverflow.com/questions/47443858/apollo-link-response-headers/58986484#58986484
