### ISSUE TITLE
How do I cancel a fetchMore?

### ISSUE THREAD

**Issue by panigrah** [apollographql/apollo-client#3360]
I have a `<Query>` component with a `fetchMore`. I need to cancel the fetchMore if it has been initiated when the Query is restarted in my component. How can I do this?

thanks

**Comment by cronello** [comment]
I have a query getting data by category (`categoryId` as a param in `options.variables`)
- each category can have many items so I need `fetchMore` for "infinit" scroll

Problem is when changing category while fetching more at the last category
- `updateQuery` at `fetchMore` parameters gives items for the last category (but I get next/changed `categoryId` at `variables` params)
- so I get items from next category but also mixed with items from last category (when the fetchMore resolves)

If I can stop/cancel the `fetchMore` request there will be just the items for the next categoryId

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=How%20do%20I%20cancel%20a%20fetchMore%3F&body=Migrated%20from:%20apollographql/apollo-client%233360) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
