### ISSUE TITLE
Documentation broken linke

### ISSUE THREAD

**Issue by justinlevi** [apollographql/apollo-client#3364]
The link under NetworkStatus (core/networkStatus.ts, line4) on the following page is broken

https://www.apollographql.com/docs/react/api/apollo-client.html#NetworkStatus

The link created is for the following URL
https://github.com/apollostack/apollo-client/blob/master/core/networkStatus.ts#L4

which does not exist

**Intended outcome:**
review the docs

**Actual outcome:**
404

**How to reproduce the issue:**
to to the page above and click on the gray text link below NetworkStatus

**Version**
- apollo-client@<version number>

**Comment by hwillson** [comment]
Thanks @justinlevi - this is currently an issue with all source code links. We're working on a fix.

**Comment by hwillson** [comment]
Actually, let's track this work in https://github.com/apollographql/apollo-client/issues/3266. Closing here - thanks!
