### ISSUE TITLE
When mixing server and @client queries in the same call fragments don't work in the @client tagged query

### ISSUE THREAD

**Issue by trescenzi** [apollographql/apollo-client#3371]
**Intended outcome:**

Fragments work as expected for both the @client tagged query and the non tagged query.

**Actual outcome:**

The fragment for the `@client` query will throw an error as it's "defined but not used" even though it's both defined and used. If instead of using a fragment you hardcode the contents of the `@client` query it behaves as expected.

**How to reproduce the issue:**

The [branch `client-fragments` on my fork of the reproducer](https://github.com/trescenzi/react-apollo-error-template/tree/client-fragments) has 4 different commits showing how this issue behaves in different situations. Checking out each commit and running it should show the behavior in each situation.

- [The first](https://github.com/trescenzi/react-apollo-error-template/tree/669b0574b42bd34665538fdc396a8c3ece60ec5a) reproduces the bug. When checked out and ran the expected result is for an error saying "fragment pets was defined but not used" to be displayed. 
- [The second](https://github.com/trescenzi/react-apollo-error-template/tree/1b129e6059672805d55c25b56f9bfbaa678e2ef0) shows how when not mixed, as in there is no `@client` directive being used, everything behaves as expected. When checked out and run you see the server data in the list.
- [The third](https://github.com/trescenzi/react-apollo-error-template/tree/54eba0b7002576642bbb46597def8dd104652e3b) shows how when there is just an `@client` tagged query being used fragments also work just fine. When checked out and run you see only the client side data in the list.
- [The fourth](https://github.com/trescenzi/react-apollo-error-template/tree/61508d3590d6653d3a366125b0e3fafcdfefdfe7) shows how when not using fragments behavior is as expected. When checked out and run you see a mix of server data, the people, and client data, the pets, in the list.

**Version**
- apollo-client@2.2.8
- apollo-cache-inmemory@1.1.12
- apollo-link-state@0.4.1

**Comment by trescenzi** [comment]
Would this be a better fit for an issue in `state-link`? If so I can move this issue there. Thanks!

**Comment by jtag05** [comment]
Is there any information regarding this? It seems like a serious shortcoming and there hasn't been an update in 5 months.

**Comment by hwillson** [comment]
We have changes coming shortly (hopefully within the next week) that will address this.

**Comment by shkleinik** [comment]
Please, tell me that the changes are already out and you just forgot to update this issue status...

**Comment by nomadoda** [comment]
I'm pretty sure this is fixed in 2.5, but I can't confirm

**Comment by trescenzi** [comment]
@nomadoda looks like you're correct. I've added a [new commit](https://github.com/trescenzi/react-apollo-error-template/commit/2536f4e37a0fb2410b95d699861fca5be9275d8d) that upgrades apollo and the mixed fragments work. I'm going to leave this open for a bit to see if anyone from Apollo team will confirm but it looks like this isn't reproducible anymore.

**Comment by jbaxleyiii** [comment]
Thanks for reporting this. There hasn't been any activity here in quite some time, so we'll close this issue for now. If this is still a problem (using a modern version of Apollo Client), please let us know. Thanks!
