### ISSUE TITLE
../../tsconfig.base does not exist

### ISSUE THREAD

**Issue by chj-damon** [apollographql/apollo-client#3374]
there is a `tsconfig.json` file in `apollo-cache` dependency, which looks like this:
```json
{
  "extends": "../../tsconfig.base",
  "compilerOptions": {
    "rootDir": "./src",
    "outDir": "lib",
    "lib": ["es6", "dom", "es2017.object"]
  },
  "include": ["src/**/*.ts"],
  "exclude": ["src/**/__tests__/*.ts"]
}
```
But `tsconfig.base` does not exist in my project. So What `tsconfig.base` should be?

**Comment by malimichael** [comment]
Having the same issue here from `apollo-cache-inmemory`

**Comment by hwillson** [comment]
`"../../tsconfig.base"` points to the [`tsconfig.base.json`](https://github.com/apollographql/apollo-client/blob/493d9a787011b7e5524edafa97422144ad8d64d1/tsconfig.base.json) file in the root of the `apollo-client` project (the `.json` extension is optional when using `extends`). Thanks!

**Comment by Slessi** [comment]
@hwillson That much is clear, but the actual file does *not* exist when the library is included inside `node_modules/`

**Comment by hwillson** [comment]
Thanks for the clarification @Slessi. The file isn't included when bundling intentionally. Is this causing a problem somewhere/somehow?

**Comment by Slessi** [comment]
@hwillson to be honest for a while VS Code kept annoyingly pointing it out to me as an error but now that I want to show it to you, it seems to not care anymore ¯\_(ツ)_/¯

**Comment by xuo** [comment]
Same issue here, attached a screenshot. Prevented it from showing up by adding file excludes in VSCode.

![tsconfig base does not exist-vscode](https://user-images.githubusercontent.com/6968409/40583012-877ff334-6185-11e8-8310-e9683bf5d603.PNG)

**Comment by bharathkuppala** [comment]
how can we overcome this error.Please do provide your solutions or suggestions

**Comment by larsfoll** [comment]
Same issue with multiple apollo packages
> apollo-link-context, apollo-link-error, apollo-link-http and apollo-link-http-common

**Comment by snnsnn** [comment]
In VS Code, If you are getting the error after any setting changes, closing and reopening the project might get rid of the error. At least that worked for me.

**Comment by saostad** [comment]
Same Error Here:
```
    "apollo-cache-inmemory": "^1.2.6",
    "apollo-client": "^2.3.7",
    "apollo-link": "^1.2.2",
    "apollo-link-context": "^1.0.8",
    "apollo-link-error": "^1.1.0",
    "apollo-link-http": "^1.5.4",
    "apollo-link-state": "^0.4.1",
    "apollo-upload-client": "^8.1.0",
    "typescript": "^3.0.1"
```

**Comment by hwillson** [comment]
Let's just get the `tsconfig.json`'s out of those published packages altogether. They shouldn't be there. https://github.com/apollographql/apollo-client/pull/3828 will address this. Thanks!

**Comment by HansHammel** [comment]
still an issue
