### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'watch' of object '#<InMemoryCache>'

### ISSUE THREAD

**Issue by manpenaloza** [apollographql/apollo-client#3376]
Having apollo-client implemented in an application, after building the javascript files using Webpack for bundling and Babel for transpiling, I receive this *Uncaught TypeError* in the browser console.

![image](https://user-images.githubusercontent.com/4241744/39378726-8313c1ec-4a59-11e8-87c8-1d71885df52a.png)
 
When I run the application with webpack dev mode, it says that the error occurs in the inMemoryCache.js File. More specific it's this part of the code:

![image](https://user-images.githubusercontent.com/4241744/39378837-c9f34e0c-4a59-11e8-9928-3232ddb8c618.png)

Do you have any idea what can cause this?

In case this is of help, here's my *.babelrc* configuration webpack uses/considers when bundling.

```javascript
{
  "presets": [
    ["es2015", { "modules": false }],
    "react"
  ],
  "plugins": [
    "transform-object-rest-spread",
    ["transform-regenerator", { "asyncGenerators": true, "generators": true, "async": true}]
  ]
}
```

Thx a lot!

**Comment by OutThisLife** [comment]
@manpenaloza Did you ever figure this out?

**Comment by SilvanCodes** [comment]
Does this issue still occur in the recent versions of apollo-client and apollo-cache-inmemory?
Could you provide the versions in which the error occurred as well as your execution environment?

**Comment by jtomaszewski** [comment]
It just started appearing in our app.

Versions:
```
    "apollo-cache-inmemory": "1.6.0",
    "apollo-client": "2.6.0",
    "apollo-link": "1.2.11",
    "apollo-link-rest": "0.7.3",
```

I'll let you know once I manage to debug this problem a bit more.

**Comment by jbaxleyiii** [comment]
Thanks for reporting this. There hasn't been any activity here in quite some time, so we'll close this issue for now. If this is still a problem (using a modern version of Apollo Client), please let us know. Thanks!
