### ISSUE TITLE
`networkError` overloaded, hard to identify source of problem

### ISSUE THREAD

**Issue by dallonf** [apollographql/apollo-client#3386]
I'd like to display different error messages to the end user depending on the type of error that's occurred; I've split them into these general categories:

* Communication Failure (can't talk to the server at all)
* Outage (The server is responding with something like a 504)
* Exception (The server responds with 500, or a 400 we don't know how to handle, or parsing the results raises an error, etc - basically, it's a bug, there's no actionable steps for the user, and we need to fix it)

Apollo's `networkError` / `graphQLErrors` distinction is really throwing a wrench in this because I've seen `networkError` used to handle any of the following cases:

* Fetch's painfully generic `TypeError: Failed to fetch` (I would classify this as a "Communication Failure")
* Query is rejected by the server with a 400 because the query has unsupported fields (I would classify this as an "Exception")
* "the application attempted to write an object with no provided id but the store already contains an id of [ID] for this object" (basically I forgot to query an object's unique ID and the cache doesn't know what to do with that - I would classify this as an "Exception")

There's really not a way I can single out the "communication failures" because, at least coming from Fetch, they're too generic, and I want "generic" and unexpected errors to be classified as Exceptions.

**Suggested resolution:**

If possible, I would like `networkError` to be used exclusively for _network_ errors, as the name suggests - other kinds of errors could go into `linkError` or something like that.

**Version**
- apollo-client@2.2.8

**Perhaps also relevant**

- #2492

**Comment by tomasikp** [comment]
Opened an issue that is very much on this same topic.  #3441

**Comment by clayne11** [comment]
This is super confusing. I'm getting back network errors with a `400` status code and if I inspect `err.networkError.result.errors` I get what looks like GraphQL errors. The default message that's printed on catch is also completely useless when I log it (`Network error: Response not successful: Received status code 400`). I have these errors all over my production logs. It's onerous to have to put special catch handling for GraphQL errors. The default errors message should at least print out the operation name of the failed call.

**Comment by tomasikp** [comment]
@clayne11 I posted about this on stack https://stackoverflow.com/questions/50289878/graphql-error-handling-with-apolloclient-and-apollo-server-express/50291479#50291479

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=%60networkError%60%20overloaded%2C%20hard%20to%20identify%20source%20of%20problem&body=Migrated%20from:%20apollographql/apollo-client%233386) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
