### ISSUE TITLE
Cannot set property 'networkStatus' of undefined

### ISSUE THREAD

**Issue by maxsalven** [apollographql/apollo-client#3388]
apollo-client 2.2.8
react-apollos 2.1.3

I'm frequently getting an error in our production logs: `Cannot set property 'networkStatus' of undefined`, specifically from line 95 of `apollo-client/data/queries.js`: `this.store[fetchMoreForQueryId].networkStatus = NetworkStatus.ready;`

In context:

```
     this.store[queryId].networkStatus = NetworkStatus.ready;
        // If we have a `fetchMoreForQueryId` then we need to update the network
        // status for that query. See the branch for query initialization for more
        // explanation about this process.
        if (typeof fetchMoreForQueryId === 'string') {
            this.store[fetchMoreForQueryId].networkStatus = NetworkStatus.ready;
        }
    };
```

Unfortunately I can't reliably replicate this issue. Has anyone had a similar problem?

**Comment by maxsalven** [comment]
Duplicate issue, sorry. Closing.

**Comment by CodySwannGT** [comment]
Duplicate of what issue? We're seeing this also

**Comment by maxsalven** [comment]
https://github.com/apollographql/apollo-client/issues/3345

It has now been fixed.
