### ISSUE TITLE
Adding extra fields via `@include` leads to "Network error: Cannot add property ..., object is not extensible"

### ISSUE THREAD

**Issue by tmeasday** [apollographql/apollo-client#3390]
Triggering a change in variables that results in an `@include` adding fields to a query leads to "Network error: Cannot add property membership, object is not extensible".

The problem is due to the fact that the cache tries to extend a frozen object inside `diffQueryAgainstStore`. I suppose the object is frozen because it is the previous result of a query? I'm not quite sure.

**Intended outcome:**
Changing the query should return the results of the second query

**Actual outcome:**
An error is logged and the container returns:

```js
// Not loading or erroring, yet `me` is null
data: { loading: false, me: null, errors: null }
```

**How to reproduce the issue:**
https://github.com/tmeasday/react-apollo-error-template <- click the button, see the result.

**Version**
- apollo-client@2.2.8
- react-apollo@2.1.3 [I'm fairly sure this is a pure AC issue however].

**Comment by tmeasday** [comment]
Note that it's not always obvious even that there is an error. In my app (for whatever reason) the error is never logged to the console, it took a fair bit of work to figure out that it was even the reason for the `null` query result.

**Comment by jbaxleyiii** [comment]
Thanks for reporting this. There hasn't been any activity here in quite some time, so we'll close this issue for now. If this is still a problem (using a modern version of Apollo Client), please let us know. Thanks!
