### ISSUE TITLE
Cannot Convert undefined or null to value when querying and field is null (but schema is valid)

### ISSUE THREAD

**Issue by Negan1911** [apollographql/apollo-client#3393]
**Intended outcome:**
I was running a query, expecting it to get the data via props.

**Actual outcome:**
The data never came, instead i got an error as you can see in the screenshot:

File: `node_modules/graphql-anywhere/lib/graphql.js` Line: 123
![image](https://user-images.githubusercontent.com/3399236/39552804-385108b8-4e41-11e8-8ca1-50bb8d76c4c3.png)

File: `node_modules/graphql-anywhere/lib/graphql.js` Line: 123
![image](https://user-images.githubusercontent.com/3399236/39552827-5843eac8-4e41-11e8-8485-53ad9ebca2a9.png)

![image](https://user-images.githubusercontent.com/3399236/39552834-64c5cb5e-4e41-11e8-982e-76b794fa83e0.png)

![image](https://user-images.githubusercontent.com/3399236/39552861-834884c2-4e41-11e8-958e-6564db384a6c.png)

**How to reproduce the issue:**
Run a query with an non-required field and with `null` as value, at least that's the apparent reason

As you might see, is allowed to be `null`:
![image](https://user-images.githubusercontent.com/3399236/39553338-903b573e-4e43-11e8-995d-0f0ad22fdabe.png)

The same query was working before (because we had an production version that's still working), but i wasn't able to track which version made this break, please, let me know if we need more info or something else

**Version**
- apollo-client@2.3.0
- graphql@0.13.2
- graphql-anywhere@4.1.9
- graphql-tag@2.9.2
- react-apollo@2.1.3
- apollo-cache-inmemory@1.2.0
- apollo-fetch@0.7.0
- apollo-link@1.2.2
- apollo-link-http@1.5.4

EDIT:
After doing a lot of checking, `graphql-anywhere` was the dependency that's breaking my code, if i use an `npm-shrinkwrap.json` to pin the version to 4.1.8 everything works correctly again (had to do this because `apollo-cache-inmemory` will install 4.1.9 instead). So this issue came from the release 4.1.9 as far as i can see

**Comment by HoangPaul** [comment]
I believe the issue was introduced in commit https://github.com/apollographql/apollo-client/commit/6abcd727818398bff53bcd73e09a29b902557cc2#diff-59e1428b6685d109077bc48ba0452c38R233

The `merge` function no longer checks if `src` is type `object`.

**Comment by benjamn** [comment]
Try `graphql-anywhere@4.1.10`?

**Comment by Negan1911** [comment]
Yup, it's working again, thanks!
