### ISSUE TITLE
pollInterval option only supported on watchQuery error

### ISSUE THREAD

**Issue by jema-turner** [apollographql/apollo-client#3395]
**Intended outcome:**

Fired a query using ApolloClient.query(options) as described in https://www.apollographql.com/docs/react/api/apollo-client.html#ApolloClient.query. I get the error "pollInterval option only supported on watchQuery". If i use watchQuery, adding pollInterval works, but not sure if I need observable queries, plus watchQuery is not well documented (subscribing to observable queries).

**Actual outcome:**

I get the error "pollInterval option only supported on watchQuery".

**How to reproduce the issue:**

Query using ApolloClient.query(options) as described in https://www.apollographql.com/docs/react/api/apollo-client.html#ApolloClient.query.

**Version**
- apollo-client@<version number>
"apollo-client": "2.2.2"

**Comment by hwillson** [comment]
Setting a polling interval is not supported when using [`ApolloClient.query`](https://www.apollographql.com/docs/react/api/apollo-client.html#ApolloClient.query). It only works with [`ApolloClient.watchQuery`](https://www.apollographql.com/docs/react/api/apollo-client.html#ApolloClient.watchQuery). The docs for this definitely need to be updated. Thanks for pointing this out!

**Comment by Yatekii** [comment]
https://github.com/apollographql/apollo-client/blob/main/src/core/watchQueryOptions.ts#L86

This is still wrong. Also, setting a polling interval on `watchQuery` is completely useless as it will just poll the cache?!

**Comment by ArjunMudhaliyar** [comment]
Is there a technical reason why polling isn't supported in `client.query`? As pointed out by others, polling using `watchQuery` will not be of much use.

**Comment by SiddHyper** [comment]
It's still a bug in V3 also
https://www.apollographql.com/docs/react/api/core/ApolloClient#ApolloClient.query
