### ISSUE TITLE
Don't read from cache when fetchPolicy = 'no-cache'

### ISSUE THREAD

**Issue by gaberudy** [apollographql/apollo-client#3396]
I have a lot of large read-only queries that I am using fetchPolicy='no-cache', but through the vue-apollo bindings the getCurrentQueryResult function is used in certain contexts that do a lot of unnecessary work / exceptions being thrown and caught that show up in my profiling analysis.

At this line, it should be safe to no execute this.dataStore.getCache().read(...) if `observableQuery.options.fetchPolicy = 'no-cache'` since our store will never contain this query.

Probably short-circuiting the function and returning: ` return maybeDeepFreeze({ data: {}, partial: true });` would be best.

https://github.com/apollographql/apollo-client/blob/9ac90e0c1729d11a41663c9a7032200369f3305d/packages/apollo-client/src/core/QueryManager.ts#L976

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Don't%20read%20from%20cache%20when%20fetchPolicy%20%3D%20'no-cache'&body=Migrated%20from:%20apollographql/apollo-client%233396) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
