### ISSUE TITLE
Read variables from QueryRef?

### ISSUE THREAD

**Issue by darkbasic** [apollographql/apollo-client#3406]
**Intended outcome:**
```ts
moreMessages(query: QueryRef<GetChat.Query>, chatId: string) {
  const {data: {chat: {messageFeed}}} = query.getLastResult();
  if (messageFeed.hasNextPage) {
    query.fetchMore({
      query: moreMessagesQuery,
      variables: {
        chatId,
        amount: this.chatMessagesAmount,
        before: messageFeed.cursor,
      },
      updateQuery: (previousResult: GetChat.Query, { fetchMoreResult }) => {
        return {
          chat: {
            ...previousResult.chat,
            messageFeed: {
              ...fetchMoreResult.chat.messageFeed,
              messages: [
                ...fetchMoreResult.chat.messageFeed.messages,
                ...previousResult.chat.messageFeed.messages,
              ],
            },
          },
        };
      },
    });
  }
}
```

I have a function called `moreMessages` which accepts a `QueryRef` as input and calls `fetchMore` in order to retrieve more results. Unfortunately the user has also to provide the `chatId`, which could theoretically be extracted by the `QueryRef` through the `obsQuery` property.

**Actual outcome:**
Unfortunately the `obsQuery` property is private, so it is not designed to be accessed.

**Version**
- apollo-client@2.2.5

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Read%20variables%20from%20QueryRef%3F&body=Migrated%20from:%20apollographql/apollo-client%233406) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
