### ISSUE TITLE
error connection refused when connecting to my localhost

### ISSUE THREAD

**Issue by GWSzeto** [apollographql/apollo-client#3408]
**Intended outcome:**
The intended outcome would be to see the exchange rates as listed in the tutorial

**Actual outcome:**
The actual outcome I see is the error state that I logged

The code that I have right now is this

```javascript
import React from "react"
import ReactDOM from "react-dom"
import "./index.css"
import App from "./App"
import registerServiceWorker from "./registerServiceWorker"
import { ApolloProvider } from "react-apollo"
import ApolloClient from 'apollo-client'
import { HttpLink } from "apollo-link-http"
import { InMemoryCache } from "apollo-cache-inmemory"
import { graphql } from 'react-apollo'

const httpLink = new HttpLink({uri: "http://localhost:4000/graphql"})

const client = new ApolloClient({
    link: httpLink,
    cache: new InMemoryCache()
})

ReactDOM.render(
    <ApolloProvider client={client}>
        <App />
    </ApolloProvider>
  , document.getElementById('root')
)
registerServiceWorker()
```

**How to reproduce the issue:**

**Version**
- apollo-client@2.3.0

**Comment by hwillson** [comment]
Hi @GWSzeto - the source snippet you've provided doesn't seem to line up with your textual description of the problem. Did you mean to include more code? If you can link to small runnable reproduction showing the problem, that would be ideal. Thanks!

**Comment by hwillson** [comment]
We haven't heard back regarding the additional information requested in https://github.com/apollographql/apollo-client/issues/3408#issuecomment-391075574, so closing for now. Thanks!
