### ISSUE TITLE
ApolloQueryResult is not described in the Apollo Client documentation

### ISSUE THREAD

**Issue by skeithtan** [apollographql/apollo-client#3412]
- [ ] has-reproduction
- [ ] feature
- [x] docs
- [ ] blocking
- [ ] good first issue

References to ApolloQueryResult [was made](https://www.apollographql.com/docs/react/api/apollo-client.html#ApolloClient.query) a lot, but has no actual description of its properties and functions.

**Comment by hwillson** [comment]
`ApolloQueryResult` (and `ApolloCurrentResult`) have been added. Thanks for pointing this out!

**Comment by skeithtan** [comment]
@hwillson I saw the updated documentations. I think there should be a description of the individual fields under `ApolloQueryResult`. `stale` is not exactly self explanatory.

**Comment by taylorgoolsby** [comment]
Where do I got to see this doc for ApolloQueryResult? All I see is template variables here: https://github.com/apollographql/apollo-client/blob/567220004108e03a799d99b19c379574f8a07617/docs/source/api/apollo-client.md#types

And a google search `site:www.apollographql.com "ApolloQueryResult"` yeilds nothing.

**Comment by PaulRBerg** [comment]
I would assume that `stale` refers to whether the request has been timed out, but I'm not sure. I'd love the docs to be a bit more descriptive.
