### ISSUE TITLE
The "uri" option does not work in HttpLink

### ISSUE THREAD

**Issue by lukejagodzinski** [apollographql/apollo-client#3421]
I didn't know if I should add this issue to this repo or the `apollo-link-http` repo because I actually don't know which one causes problem.

I have the following chunk of code from the example [app](https://www.apollographql.com/docs/react/recipes/simple-example.html):

```js
const client = new ApolloClient({
  link: createHttpLink({ uri: "http://api.githunt.com/graphql" }),
  cache: new InMemoryCache()
});
```

And when I try to fetch anything from the GraphQL endpoint I see that browser is making request to different endpoint: `http://localhost:3001/graphql` and of course it fails.

When I provide `uri` directly to the `ApolloClient` constructor, then it works:

```js
const client = new ApolloClient({
  link: "http://api.githunt.com/graphql",
  cache: new InMemoryCache()
});
```

However, I have to use `HttpLink` as I want to attach some custom headers to the request.

Here is the reproduction repository: https://github.com/lukejagodzinski/apollo-client-error
1. Clone
2. Run `npm install`
3. Run `npm run start`
4. Open browser console and see something like this

<img width="1920" alt="screen shot 2018-05-07 at 8 04 25 pm" src="https://user-images.githubusercontent.com/1051229/39716878-deb0b458-5231-11e8-8221-a6716f063a4f.png">

**Comment by jmay4826** [comment]
I came across this as I was having a similar problem and finally figured it out. ApolloClient from `apollo-boost` only supports a smaller subset of [configuration options](https://www.apollographql.com/docs/react/essentials/get-started.html#configuration). 

ApolloClient from `apollo-client` gives you all the configuration options. 
So you'll just want to change your import statement to `import { ApolloClient } from 'apollo-client';`
Check out the [Apollo Boost migration page](https://www.apollographql.com/docs/react/advanced/boost-migration.html).

**Comment by lukejagodzinski** [comment]
Actually I was using `apollo-client` and not `apollo-boost` and had this problem. Then I've switched to `apollo-boost` and got rid of `apollo-link-http` and now everything works properly. There problem is that when you read documentation, then you don't know which is true. Examples are not working. Probably docs are not up to date but not sure about that.

**Comment by lukejagodzinski** [comment]
Thanks! It helped me solve the problem. I didn't even notice that there is some difference between both because names (`ApolloClient`) are the same. Unfortunately, I didn't dig documentation thoroughly and was just following tutorials.

**Comment by tmfprlt1234** [comment]
@jmay4826 thanks@~$@!$!@$~
