### ISSUE TITLE
Meteor apollo client 2.0 update roadmap

### ISSUE THREAD

**Issue by Paddy-Hamilton** [apollographql/apollo-client#3424]
/label RoadMap, docs, question

I want to use Meteor and Apollo for a new project. I noticed that the [doc's](https://www.apollographql.com/docs/react/recipes/meteor#meteorClientConfig) say meteor is being updated to use 2.0 client. I just wondered if there was a roadmap, release date for this?

If the update was going well and due to be released soon (next month) then I may hold of on using 1.0.

Cheers

**Comment by hwillson** [comment]
The Meteor [apollo](https://github.com/apollostack/meteor-integration/) package the docs refer to has been updated to work with Apollo Client 2. You can see how to use it in the [`apollo`](https://github.com/apollostack/meteor-integration/) repo itself. It's just the [Integrating with Meteor](https://www.apollographql.com/docs/react/recipes/meteor) docs that are lagging behind. We'll get them updated soon!

Just to add - another great alternative to `apollo` is the [`swydo:ddp-apollo`](https://github.com/Swydo/ddp-apollo) package.

**Comment by hwillson** [comment]
@Paddy-Hamilton If you're still interested in the best way forward (for now) with regards to integrating Meteor with Apollo, we recommend using the [`swydo:ddp-apollo`](https://github.com/Swydo/ddp-apollo) package. It works really well and is actively maintained. The `apollo` package (that the Apollo Meteor docs cover) is not currently maintained, and unless it finds a new maintainer, will be removed from the Apollo docs. Thanks!

**Comment by aadamsx** [comment]
@hwillson, any hope to get the Integrating with Meteor documents updated soon (not interested in 3rd party packages like swydo:ddp-apollo) so I can add [Apollo Server/Client to my Meteor app](https://forums.meteor.com/t/meteor1-7-apollo2-server-client-integration/45165/6)?
