### ISSUE TITLE
Documentation: Apollo Client Javascript Docs lead to the wrong place.

### ISSUE THREAD

**Issue by the-simian** [apollographql/apollo-client#3434]
Instead of leading to the native js implementation, they instead lead to the react.js documentation

![image](https://user-images.githubusercontent.com/954596/39851426-530a36a2-53dc-11e8-8658-99b83211a2b6.png)

Expected behavior: Leads to the non-react examples where you can use apollo-client directly:
(like this sort of thing)
![image](https://user-images.githubusercontent.com/954596/39851588-51730b88-53dd-11e8-9bf9-3ffa1d5a61a5.png)

from: https://github.com/apollographql/apollo-client#usage

**Comment by hwillson** [comment]
This issue has been resolved - thanks!
