### ISSUE TITLE
Unified callback signature in the Query and Mutation components

### ISSUE THREAD

**Issue by akoenig** [apollographql/apollo-client#3436]
Having the same callback signature in the render prop of `<Query />` and `<Mutation />` would lead to a simpler approach of creating abstractions that handle the `loading` and `error` state when it comes to establishing own `Query` and `Mutation` components.

At the moment, the `Query` component looks like:

```jsx
<Query query={}>
  {({loading, data, error}) => {...}}
</Query>
```

whereas `Mutation` has the actual _mutate_ function as the first parameter:

```jsx
<Mutation mutation={}>
  {(mutate, {loading, data, error}) => {...}}
</Mutation>
```

I would like to propose a unified callback signature, like `{loading, data, error}` for queries and `{mutate: myMutationName, loading, data, error}` for mutations.

With that in place, it would be possible to implement simpler abstractions for handling `loading` and `error` states:

```js

import { Mutation as ApolloMutation } from "react-apollo";

const handleLoadingAndError = callback => ({loading, error, ...rest}) => {
    if (loading) {
      // TASK: Handle loading
    }

    if (error) {
        // TASK: Handle error
    }

    return callback({loading, error, ...rest});
};

const MyMutation = ({children, ...props}) =>
  <ApolloMutation {...props}>
    {handleLoadingAndError(({data}) => {...})}
  </ApolloMutation>;
```

- [ ] has-reproduction
- [x] feature
- [ ] docs
- [ ] blocking
- [ ] good first issue

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Unified%20callback%20signature%20in%20the%20Query%20and%20Mutation%20components&body=Migrated%20from:%20apollographql/apollo-client%233436) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
