### ISSUE TITLE
Proposal: automatic cache updates for reverse direction of associations

### ISSUE THREAD

**Issue by jedwards1211** [apollographql/apollo-client#3450]
I was thinking last night...in a way GraphQL is not as ideal as it seems for transferring relational data, because it only gives information about one direction of an association, so there's no way to automatically store the other direction of the association in the cache.  The more complicated the associations get, the more potential for bugs.

But I think this is something we could solve with a custom cache updater that knows about our associations.

For example, let's say I have the following database schema (defined with Sequelize):
```js
const Organization = sequelize.define('Organization', {...})
const User = sequelize.define('User', {...})
const OrganizationMember = sequelize.define('OrganizationMember', {...})
User.belongsToMany(Organization, {through: OrganizationMember})
Organization.belongsToMany(User, {through: OrganizationMember})
```

Now imagine if I run the following query:
```graphql
query {
  Organizations {
    id
    name
    Users {
      id
      username
    }
  }
}
```

And we get back
```json
{
  "data": {
    "Organizations": [
      {
        "id": 1,
        "name": "jcore.io",
        "Users": [
          {
            "id": 3,
            "username": "andy"
          }
        ]
      }
    ]
  }
}
```

This is enough information to know that `jcore.io`'s users includes `andy`, and store that relationship in the cache automatically.  However, it doesn't indicate for certain that `andy`'s organizations includes `jcore.io`.

An updater could assume that if the `User` graphql type has an `Organizations` field that's a list, then it's the other direction of this association and it should add `jcore.io` to `andy`'s organizations in the cache.  But this could also be wrong if the associations are defined in sequelize in a different way (for instance, a `User` has both `publicOrganizations` and `privateOrganizations` associations).

One solution would be to provide a GraphQL query that returns information about the associations that an updater doesn't have to make risky assumptions.  The following is still maybe a bit Sequelize-specific but maybe we could come up with something generic enough to represent any kind of associations.  For instance:
```graphql
query {
  associations {
    # the __typename of the source type
    source
    # the name of the id field in the source type
    sourceId
    # the __typename of the target type
    target
    # the name of the id field in the target type
    targetId
    # the name of the query for getting a single source item by id
    sourceQuery
    # belongsTo, hasOne, hasMany, belongsToMany
    associationType
    # the name of the field in the source type that contains the associated targets
    as
  }
}
```
```json
{
  "data": {
    "associations": [
      {
        "source": "Organization",
        "sourceId": "id",
        "target": "User",
        "targetId": "id",
        "sourceQuery": "Organization",
        "associationType": "belongsToMany",
        "as": "Users"
      },
      {
        "source": "User",
        "sourceId": "id",
        "target": "Organization",
        "targetId": "id",
        "sourceQuery": "User",
        "associationType": "belongsToMany",
        "as": "Organizations"
      }
    ]
  }
}
```

This would be enough information for an updater (also to be provided by this package) to create references in the reverse direction in the cache if it gets back data showing what users belong to an organization (or vice versa).

For instance, if we get back
```json
{
  "data": {
    "Organizations": [
      {
        "id": 1,
        "name": "jcore.io",
        "Users": [
          {
            "id": 3,
            "username": "andy"
          }
        ]
      }
    ]
  }
}
```
Then we can also essentially do the following automatically to cache the reverse direction of the association:
```js
const UserOrganizations = gql`
query ($userId: Int!) {
  User(id: $userId) {
    id
    Organizations {
      id
    }
  }
}`
const {data: {User}} = cache.readQuery({query: UserOrganizations, variables: {userId: 3}})

cache.writeQuery({
  query: UserOrganizations,
  variables: {userId: 3},
  data: {
    User: {
      ...User,
      Organizations: [
        ...User.Organizations,
        {__typename: 'Organization', id: 1}
      ]
    }
  }
})
```

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Proposal%3A%20automatic%20cache%20updates%20for%20reverse%20direction%20of%20associations&body=Migrated%20from:%20apollographql/apollo-client%233450) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
