### ISSUE TITLE
Broken link in docs for "Using Apollo Client directly" on Apollo Client > Getting Started page

### ISSUE THREAD

**Issue by brennancheung** [apollographql/apollo-client#3455]
**Intended outcome:**
Trying to read docs on using the client directly (last link on the page here: https://github.com/apollographql/apollo-client/blob/master/docs/source/essentials/get-started.md).

**Additional Background:**
I need a React component that does multiple mutations and the `Mutation` HOC only supports one.

**Actual outcome:**
Link is broken

**How to reproduce the issue:**
Navigate to https://github.com/apollographql/apollo-client/blob/master/docs/source/essentials/get-started.md and click the link "Using Apollo Client directly"

**Version**
- apollo-client@<version number>

**Comment by alex996** [comment]
I was glossing over the docs, and it seems the broken link needs to be updated to [https://www.apollographql.com/docs/react/essentials/queries.html#manual-query](https://www.apollographql.com/docs/react/essentials/queries.html#manual-query).

**Comment by abhiaiyer91** [comment]
Edited in https://github.com/apollographql/apollo-client/pull/3463

**Comment by hwillson** [comment]
No longer an issue - thanks!
