### ISSUE TITLE
Mutation updating the component: "Can't call setState..."

### ISSUE THREAD

**Issue by Almaju** [apollographql/apollo-client#3460]
**Intended outcome:**
When a Query re-run after a Mutation, setState should not trigger an error if the component is removed.

**Actual outcome:**
```
ExceptionsManager.js:71 Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Mutation (at Screen.js:39)
[...]
Mutation._this.onCompletedMutation | @ | Mutation.js:80
```

**How to reproduce the issue:**
Something like that:
```jsx
const Button = ({ active }) => {
  if(active) { 
    return <Mutation mutation={SET_INACTIVE}>(...)</Mutation>;
  }
  return <Mutation mutation={SET_ACTIVE}>(...)</Mutation>;
};

const Item = () => (
  <Query query={GET_ITEM}>
    {data => <Button active={data.active} />
  </Query>
);
```

**Version**
- apollo-client@2.3.1

**Comment by jeffbernst** [comment]
Did you ever figure out what the problem was with this? I'm running into a similar problem when a user clicks a link to load a component with a query in it.

**Comment by alamothe** [comment]
This happens for me if the user navigates away from a page with `Mutation` component inside it, and then `mutate` is called.

The reason I call `mutate` later (after timeout) is debouncing.

It would be great if `Mutation` component would allow this use case.

**Comment by charlie632** [comment]
Having the same issue. 
I think this is what's triggering the warnings.
`const QueryUserComposed = props => (
  <Mutation mutation={updateUserMutation}>
    {mutation => (
      <Query query={GET_INITIAL} variables={{ uid: props.user.uid }}>
        {({ data, loading, error }) => {
          if (loading) return null;
          if (error) return null;
          let SAS = data.initial.SAS;
          let userData = data.initial.user;
          mutation({ variables: { userData: userData, token: SAS } });
          return null;
        }}
      </Query>
    )}
  </Mutation>
);
`

**Comment by charlie632** [comment]
Hi, I'm still having this problem. Is there any updates?

**Comment by eelkeh** [comment]
Running into the same issue

**Comment by jbaxleyiii** [comment]
Thanks for reporting this. There hasn't been any activity here in quite some time, so we'll close this issue for now. If this is still a problem (using a modern version of Apollo Client), please let us know. Thanks!

**Comment by ahmedbrandver** [comment]
Still having that issue can any one found a solution for it?
