### ISSUE TITLE
Error when unmounting query while fetchMore is in flight

### ISSUE THREAD

**Issue by doomsower** [apollographql/apollo-client#3466]
**Intended outcome:**

No errors are thrown.

**Actual outcome:**

Apollo-client throws error:
```
Cannot set property 'networkStatus' of undefined
QueryStore.markQueryResult
    bundle.umd.js:835:16
```

**How to reproduce the issue:**

For me it's possible to get stable reproduction in my app by following this steps:
- Mount component with query, run `fetchMore`
- While `fetchMore` is in flight, unmount component with query
- Error is thrown

When looking at code that throws, I can see that there's no safeguard [on this line](https://github.com/apollographql/apollo-client/blob/6abcd727818398bff53bcd73e09a29b902557cc2/packages/apollo-client/src/data/queries.ts#L129):

```ts
    if (typeof fetchMoreForQueryId === 'string') {
      this.store[fetchMoreForQueryId].networkStatus = NetworkStatus.ready;
}
```

 However, a few lines above there's a safeguard:

```ts
if (!this.store[queryId]) return;
```

Is it safe to just add another safeguard for fetchMore? If so, I can submit simple PR. However, I don't have enough knowledge to write test for it, if they're required.

**Version**
- apollo-client@2.3.1

**Comment by hwillson** [comment]
PR https://github.com/apollographql/apollo-client/pull/3469 has been merged, so this fix will be coming in the next `apollo-client` release (scheduled for this upcoming Tuesday, 2018-05-29). Thanks!

**Comment by FezVrasta** [comment]
For what is worth, I'm getting this error on apollo-client@2.6.0
