### ISSUE TITLE
Deprecated? 

### ISSUE THREAD

**Issue by shinzui** [apollographql/apollo-client#3473]
This [tweet](https://twitter.com/ken_wheeler/status/996473657571663873) mentions that apollo-client is going to be deprecated and replaced by urql. Is that accurate?

**Comment by stubailo** [comment]
@shinzui @hwillson Hi! I'm the engineering manager of the open source team at Apollo.

That tweet is a joke from a community member that works on urql, and is completely unaffiliated with the Apollo open source project. We are fully committed to developing Apollo Client -- building awesome new features, fixing bugs, and getting new contributors -- and have no intention to change that at all.

It's unfortunate that this tweet has caused some legitimate confusion, but I'm here to 100% unequivocally say that it is _not_ factual.

**Comment by shinzui** [comment]
@stubailo Apollo team members are in the tweet's picture and in the conversation. @jbaxleyiii who is part of the Apollo team event [tweeted](https://twitter.com/jbaxleyiii/status/997180259400343552) this issue to make fun of it. That is so unprofessional.

**Comment by hwillson** [comment]
Sorry @shinzui! Honestly, we didn't mean to come across as unprofessional. This was just a case of having a bit of lighthearted fun. Sorry for any confusion! As @sashko mentioned, the Apollo team is hard at work on some really awesome new stuff that we can't wait to show everyone. Thanks for being an Apollo user and community member! :heart:

**Comment by jbaxleyiii** [comment]
@shinzui my intention with that tweet (which I've deleted now) was not to make fun of this issue at all but to call attention to the confusion caused by the original tweet!

I'm really sorry if you felt attacked! Apollo Client has and always will be one of the most important things I've ever worked on and the Apollo team is 1,000% focused on our community and making applications better and better

**Comment by shinzui** [comment]
@jbaxleyiii No worries. I love Apollo and it's been one of the best additions to our stack. I was just taken aback when you tweeted instead of answering the issue to let me know that the original tweet was a joke.
