### ISSUE TITLE
graphql-anywhere filter function doesn't work with arrays

### ISSUE THREAD

**Issue by dquang-tran** [apollographql/apollo-client#3483]
The filter function invalidates a field if that field is an array instead of an object
```
import { filter } from 'graphql-anywhere';
import gql from 'graphql-tag';

const peopleFragment = gql`
  {
    alias
    height(unit: METERS)
  }
`;
const people = [{
  alias: 'Bob',
  height: 1.89,,
}];
```

**Intended outcome:**
```
console.log(filter(peopleFragment, people))
// Output
[{
  alias: 'Bob',
  height: 1.89,
}];

```
**Actual outcome:**
```
console.log(filter(peopleFragment, people))
// Output
// {};
```

The unit test doesn't cover this case: https://github.com/apollographql/apollo-client/blob/master/packages/graphql-anywhere/src/__tests__/utilities.ts

Is this function not expected to work on arrays? 
**Version**
- apollo-client@1.4.0

**Comment by hwillson** [comment]
Arrays aren't currently supported, but I think this functionality would make sense to add. Pull requests encouraged - thanks!

**Comment by dquang-tran** [comment]
Also, keep in mind that the `propType` function of 'graphql-anywhere' library will also need to be updated along with this change. Since the fragment can now represent both an object and an array, propTypes will also need to do `either .. or ..` type

**Comment by JSweet314** [comment]
is [this](https://github.com/JSweet314/apollo-client/blob/ec657bd68ce432fbadd65460c3533826905b206f/packages/graphql-anywhere/src/utilities.ts#L104) the function you are referring to?

**Comment by dquang-tran** [comment]
@JSweet314 Yeah

**Comment by hwillson** [comment]
Addressed in https://github.com/apollographql/apollo-client/pull/3591. Thanks!
