### ISSUE TITLE
How to use <Query> component and <Mutation> component together, and pick which Lifecycle method?

### ISSUE THREAD

**Issue by hazzard17** [apollographql/apollo-client#3494]
I have a problem for implementing a page called Settings.
In this page, query the user preferences at first, then current user can update the preferences settings. With order version, I use graphql wrapper for HOC and ComponentWillReceiveProps to query and setState for inputs' value. 
Any suggestions? Really need help...

**Comment by checkmatez** [comment]
Render <SomeChecker data={data} /> which checks for data changes in ComponentWillReceiveProps.

**Comment by hazzard17** [comment]
thanks for replying, these days I find a way using ApolloConsumer and <Mutation/> Component to solve my problem.

**Comment by mefjuu** [comment]
@checkmatez Don't promote deprecated React's methods. https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

**Comment by hwillson** [comment]
Sounds like this can be closed - thanks!
