### ISSUE TITLE
Add #3082 to apollo-client v1

### ISSUE THREAD

**Issue by Saifadin** [apollographql/apollo-client#3506]
Hi,

I have been following https://github.com/apollographql/apollo-client/issues/3043 for a while now and finally a solution has been found (#3082) and boy is it a weird one.  🎉

Now the Fix will probably be released in v2 of apollo client, but i wanted to check if it is possible to add it to v1 also. We are currently having this issue, but the upgrade to v2 is not planned for a while and it is necessary to fix this asap on our side for IE 11.

Is it possible to make a new release vor v1 with this fix or will i need to fork the library and fix it that way?

Cheers
Osamah

**Comment by hwillson** [comment]
Sorry, there are no plans to backport the fix to `apollo-client` 1.x. Thanks!
