### ISSUE TITLE
Arrays dont set in the In Memory Cache correctly if the element has no typename

### ISSUE THREAD

**Issue by ofersadgat** [apollographql/apollo-client#3517]
**Intended outcome:**
GraphQL queries can correctly retrieve array data

**Actual outcome:**
Weird intermediary data is returned instead. The format of the returned object is `{type: "id", generated: true, id: "$ROOT_QUERY.currentData.query.0", typename: undefined}` instead of the data that was inserted as a default which was: `{name: 'test',children:[]}`. If requesting the property (and not subproperties) is an error, this should instead return nothing or throw. But seeing as how other queries work with this pattern it seems inconsistent to error here.

**How to reproduce the issue:**
https://github.com/ofersadgat/react-apollo-error-template

Even shorter version:
```js
import { InMemoryCache } from "apollo-cache-inmemory";
import gql from "graphql-tag";

const cache = new InMemoryCache();


const data = {
	data: {
		currentQuery: {
			__typename: 'CurrentQuery',
			query: [{name: 'foo',children:[]}],
		}
	}
};

cache.writeData(data);


var result = cache.readQuery({
	query: gql`
	    query GetMyData {
	      currentQuery {
	        query
	      }
	    }
	  `
});

console.log(result.currentQuery.query[0].name, ' should equal ', data.data.currentQuery.query[0].name);
```

**Version**
- apollo-client@2.0.0

- [x] has-reproduction

**Comment by peterallanmdavid** [comment]
I stumbled across this issue as well, it turns out, its a mistake on my part, you have to get the values of the array in a graphql way,

```js
query: gql`
	    query GetMyData {
	      currentQuery {
	        query{
                       name
                       children
                 }
	      }
	    }
	  `
```

you must specify the properties the you will get from the array e.g. name , childern

**Comment by hwillson** [comment]
See https://github.com/apollographql/apollo-client/issues/3517#issuecomment-425075108 for the likely solution. Closing - thanks!
