### ISSUE TITLE
Question : How to combine multiple middlewares in apollo-angular-link

### ISSUE THREAD

**Issue by danilohgds** [apollographql/apollo-client#3525]
I removed most of the template out, since this is just a question.

In some react recipes, the operator "from" is used to combine multiple middlewares, is there anything similar in the angular version of the libraries?

I did multiple concat of my Links but i'm not sure if it is the best approach.

Thanks in advance.

- [x] question

**Comment by hwillson** [comment]
Please re-open this question over in the http://github.com/apollographql/apollo-angular repo. Thanks!
