### ISSUE TITLE
Query component, if there is graphql error, data is totally empty, even if http request returns some valid data

### ISSUE THREAD

**Issue by nicolasxu-bg** [apollographql/apollo-client#3529]
**Intended outcome:**

Use Query component to get data

**Actual outcome:**
data in callback child render function is empty when there is graphql error for one key, but not all. If you inspect the http request, there are some valid data in 'data' field. 

**How to reproduce the issue:**
Use Query component, to query several data fields, throw one error in one resolver, and keep other fields return valid data.  

**Versions**

"react-apollo": "^2.1.3",

blocking

**Comment by jasonrhodes** [comment]
(This issue can probably be closed.)

**Comment by hwillson** [comment]
See the solution mentioned in https://github.com/apollographql/apollo-client/issues/3529#issuecomment-393389772 (thanks @jasonrhodes!).
