### ISSUE TITLE
npm install is broken due to 404 on @types/graphql@0.12.6

### ISSUE THREAD

**Issue by hailwood** [apollographql/apollo-client#3530]
**Intended outcome:**
npm install of any apollo packages

**Actual outcome:**
![image](https://user-images.githubusercontent.com/709773/40756857-b770ab86-64d9-11e8-843e-c83e4f569b23.png)

**How to reproduce the issue:**
`npm install apollo-client`

**Versions**

  System:
    OS: Linux 4.15 Ubuntu 18.04 LTS (Bionic Beaver)
  Binaries:
    Node: 9.11.1 - /usr/bin/node
    npm: 6.1.0 - ~/.npm-packages/bin/npm
  Browsers:
    Chrome: 67.0.3396.62
    Firefox: 60.0.1

**Other Info**
This seems to be a requirement of 
* graphql-anywhere
* apollo-cache-inmemory
* apollo-client
* apollo-utilities
* apollo-boost
* apollo-cache

**Comment by NickTomlin** [comment]
I am now able to install `apollo-client` whereas I had previously seen the same 404. I wonder if this is some holdover from the recent [npm incident](https://status.npmjs.org/incidents/238t55n6f03f) that caused published to fail installing or viewing

**Comment by hailwood** [comment]
@NickTomlin interesting, this still fails for me.

**Comment by jasonrhodes** [comment]
I am able to `npm install apollo-client` fine as of just a minute ago, FWIW.

**Comment by hailwood** [comment]
Yep working again for me now :)

Assuming this issue is going to be fixed for everyone so closing.
