### ISSUE TITLE
fetchPolicy no-cache for subscriptions

### ISSUE THREAD

**Issue by Oudmane** [apollographql/apollo-client#3532]
I have I case using apollo-client where I don't need caching at all, I set 
```js
defaultOptions = {
    query: {
        fetchPolicy: 'no-cache'
    },
        mutate: {
        fetchPolicy: 'no-cache'
    }
} 
```

I notice .subscribe({query}) doesn't support fetchPolicy option, also tries to cache the result.

I forked and edited apollo-client, I wrapped this
https://github.com/apollographql/apollo-client/blob/9bcdafefe1bde7d5bb0aab5c242345a2137c9f42/packages/apollo-client/src/core/QueryManager.ts#L918-L920
inside
```js
if (options.fetchPolicy && options.fetchPolicy !== 'no-cache') {
    ...
}
```

I don't know why is this.dataStore.markSubscriptionResult() is enforced (I can't think of cases this maybe useful), and why isn't there a fetchPolicy for subscriptions.

I'll work on a PR to add fetchPolicy to subscription, please let me know if this isn't needed

Thanks

**Comment by hwillson** [comment]
This has been addressed in https://github.com/apollographql/apollo-client/pull/3773. Thanks for pointing this out!
