### ISSUE TITLE
Mutation component rendering

### ISSUE THREAD

**Issue by chris-verclytte** [apollographql/apollo-client#3537]
/label question

Hi guys, 

I am a little disturbed with the new way of handling mutation through components regarding re-rendering performances. 
IMO, the new way of doing it encourages declaration of arrow function in the JSX which I was avoiding until now in order to avoid unnecessary rendering.
Giving the example from [the docs](https://www.apollographql.com/docs/react/essentials/mutations.html#basic), we declare it this way:
```js 
 return (
    <Mutation mutation={ADD_TODO}>
      {(addTodo, { data }) => (
        <div>
          <form
            onSubmit={e => {
              e.preventDefault();
              addTodo({ variables: { type: input.value } });
              input.value = "";
            }}
          >
            <input
              ref={node => {
                input = node;
              }}
            />
            <button type="submit">Add Todo</button>
          </form>
        </div>
      )}
    </Mutation>
  );
```
But it seems to me that this is triggering a lot of unnecessary rendering on `input` and `button` since each time the component is rendered a new arrow function is created for onSubmit, then the refs are not equal involving rerendering of the children. While it is not really important in this use case it could become when there is a lot of children.
How do you use to handle this ? 

At the moment, I am memoizing the function passed to the child in order to avoid those rendering but I am curious how you are addressing the problem and if it has been taken into consideration ?

My solution at the moment:
```js 
 handleSubmit = mutation => e => {
   e.preventDefault();
   addTodo({ variables: { type: input.value } });
   input.value = "";
 }

 memoizedHandleSubmit = memoize(this.handleSubmit)

 return (
    <Mutation mutation={ADD_TODO}>
      {(addTodo, { data }) => (
        <div>
          <form
            onSubmit={this.memoizedHandleSubmit(addTodo)}
          >
            <input
              ref={node => {
                input = node;
              }}
            />
            <button type="submit">Add Todo</button>
          </form>
        </div>
      )}
    </Mutation>
  );
```

**Comment by thomasdavis** [comment]
I'd also love to see solutions to this problem. Currently just using arrow functions.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Mutation%20component%20rendering&body=Migrated%20from:%20apollographql/apollo-client%233537) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
