### ISSUE TITLE
[BUG] FetchMore() trigger QueryRef value changes before it's over

### ISSUE THREAD

**Issue by OwlLaboratory** [apollographql/apollo-client#3546]
Hi everyone !

**Intended outcome:**

Since a few weeks I try to implement a very simple workflow with the fetchMore() function.

I retrieve information from a campaign object: id, name, start_time, end_time.
When the user clicks a button, new data for the campaign is retrieved via fetchMore().

**Actual outcome:**
Whenever I click on the button, the observable valueChanges of the queryRef detects a new value even before fetchMore () has finished its work.
So I never have my object updated in valueChanges.

![apollo_issue](https://user-images.githubusercontent.com/28731923/41027483-73be715a-6977-11e8-9844-ce29321ef03a.png)

**How to reproduce the issue:**

Here is a stackblitz that reproduces the problem:
The logic is in **report.service.ts** & **app.component.ts**
You can see debug information in the console
https://stackblitz.com/github/OwlLaboratory/apollo_angular_issue

**Versions**

  System:
    OS: Linux 4.16 Fedora 28 (Workstation Edition) 28 (Workstation Edition)
  Binaries:
    Node: 8.11.2 - /usr/bin/node
    npm: 5.6.0 - /usr/bin/npm
  Browsers:
    Chrome: 67.0.3396.62
    Firefox: 60.0.1
  npmPackages:
    apollo-angular: ^1.1.0 => 1.1.0 
    apollo-angular-link-http: ^1.1.0 => 1.1.0 
    apollo-cache-inmemory: ^1.2.2 => 1.2.2 
    apollo-client: ^2.3.2 => 2.3.2 
    apollo-link: ^1.2.2 => 1.2.2 

I would be infinitely grateful to the person who can explain to me where the problem comes from or if it is a bug?

Good day everyone and thanks in advance (sorry for my poor english)

**Comment by hwillson** [comment]
Thanks for reporting this @OwlLaboratory - this question would be much better asked over in the http://github.com/apollographql/apollo-angular repo however.

**Comment by OwlLaboratory** [comment]
Hi hwillson ! Thanks for you response ! :)

At first, I had posted on apollo angular, kamilkisiela told me that it was here that I had to talk about this problem:

![apolloangular](https://user-images.githubusercontent.com/28731923/41468189-6aa36d80-70a9-11e8-9b81-3dde55395c4a.png)

The topic is here: https://github.com/apollographql/apollo-angular/issues/648

Have a good day !
