### ISSUE TITLE
perfomance issue on android

### ISSUE THREAD

**Issue by EJohnF** [apollographql/apollo-client#3547]
**Intended outcome:**
Around the same performance on android and ios

**Actual outcome:**

Slow performance and blocking JS thread on android

**How to reproduce the issue:**

For me, it seems that in react-apollo has some performance issues on Android For example, I have a FlatList of elements, each of which has

```
<Query
        query={cardUniversalQuery}
        variables={{
          date: date.format(innerDateFormat)
        }}
        delay>
        {({ data }) => (
          <FlatList
            data={data && data.userDayActivities ? data.userDayActivities : []}
            renderItem={({ item }) => <ListItem {...item} />}
            keyExtractor={(item, index) => ((index).toString())} />)}
      </Query>
```

if remove Query - android and ios version works with roundly the same speed, while go through a list.

But if return that section back - it blocks JS thread until all queries in {windowSize} items are finished - so that UI is still response on scroll but their proper handlers can’t be fired. Ios work fine - just show empty space in place of query, and don't block JS/UI thread (perf monitor shows just reducing fps to the range of 30-50 on ios)

tested on android phone - Samsung Galaxy Grand Prime Pro, 7.1.1 

**Versions**

  System:
    OS: macOS High Sierra 10.13.5
  Binaries:
    Node: 6.2.2 - ~/.nvm/versions/node/v6.2.2/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 5.0.0 - ~/.nvm/versions/node/v6.2.2/bin/npm
  Browsers:
    Chrome: 66.0.3359.181
    Safari: 11.1.1
  npmPackages:
    apollo-boost: 0.1.5 => 0.1.5 
    react-apollo: 2.1.3 => 2.1.3 

/label android_perfomance

**Comment by hwillson** [comment]
I'd love to know if the new `apollo-cache-inmemory` beta helps with this. See https://github.com/apollographql/apollo-client/pull/3394#issuecomment-396666027 for instructions outlining how to try the beta.

**Comment by EJohnF** [comment]
Yes, it helps! Now it works much smoother, thank you!

**Comment by hwillson** [comment]
Great news @EJohnF - thanks for trying it out and the feedback! Those changes will be released shortly.

cc @benjamn

**Comment by hwillson** [comment]
This issue has been resolved. Thanks!
