### ISSUE TITLE
Partial cache reset

### ISSUE THREAD

**Issue by BananaBobby** [apollographql/apollo-client#3564]
I've got stuck with a rather common situation with mutations and cache.
In my case I have a query `tasks(filters: $filters)`. It gets fetched and cached several times with different filters. Then I run a mutation `createTask(input: $input)`. It looks like I can't update my cache manually in this case because I don't know for which filters I should update the cache unless I implement all task filtering logic inside of the update function. Additionally I've got another query that fetches the number of tasks opened which should also be updated.

I've seen some issues in the repo and stackoverflow regarding the problem, but no solution found except for running `client.resetStore()`. Still it clears all the data and makes the app fetch it all right after. Possible solution that I see is providing a method for partial cache clear based on query names (may become a more abstract one keeping the idea), so that clearing `tasks` would clear all the tasks cache variants.

If you have any other thoughts on possible workaround - please share.

**Comment by BananaBobby** [comment]
I can also contribute by working on this feature if the idea gets accepted

**Comment by BananaBobby** [comment]
@hwillson Probably another approach can be by assigning id to a query and providing a way to refetch the query by that id in other component / action/ whatever. I would say it sounds even better to me.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Partial%20cache%20reset&body=Migrated%20from:%20apollographql/apollo-client%233564) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by htulipe** [comment]
@BananaBobby I allowed myself to create the feature request: https://github.com/apollographql/apollo-feature-requests/issues/29
