### ISSUE TITLE
Don't require an unnecessary id on write

### ISSUE THREAD

**Issue by lorensr** [apollographql/apollo-client#3565]
My `currentUser` root query field is a single `User`, which has an id and is normalized. I'm unable to `writeQuery` `currentUser` without an id. I would like to be able to.

A related but separate issue is printing a warning instead of throwing an error: #2510

**Code**

```js
const READ_USER_FAVORITES = gql`
  query ReadUserFavorites {
    currentUser {
      favoriteReviews {
        id
      }
    }
  }
`
```

```js
      mutate({
        variables: { id, favorite },
        optimisticResponse: {
          favoriteReview: {
            __typename: 'Review',
            id,
            favorited: favorite
          }
        },
        update: store => {
          const data = store.readQuery({ query: READ_USER_FAVORITES })

          if (favorite) {
            data.currentUser.favoriteReviews.push({ id, __typename: 'Review' })
          } else {
            remove(data.currentUser.favoriteReviews, { id })
          }

          store.writeQuery({ query: READ_USER_FAVORITES, data })
        }
      })
```

**Outcome**

```
index.js:2178 Error: Error writing result to store for query:
 query ReadUserFavorites {
  currentUser {
    favoriteReviews {
      id
      __typename
    }
    __typename
  }
}

Store error: the application attempted to write an object with no provided id but the store already contains an id of User:5a3cd78368e9c40096ab5e3f for this object. The selectionSet that was trying to be written is:
currentUser {
  favoriteReviews {
    id
    __typename
  }
  __typename
}
    at writeFieldToStore (writeToStore.js:296)
    at writeToStore.js:120
```

**Intended outcome**

Successfully writes. Currently, in order to get that to happen, you need to add `currentUser.id` to the query:

```js
const READ_USER_FAVORITES = gql`
  query ReadUserFavorites {
    currentUser {
      id
      favoriteReviews {
        id
      }
    }
  }
`
```

**Versions**

```
  System:
    OS: macOS High Sierra 10.13.4
  Binaries:
    Node: 8.11.2 - ~/.nvm/versions/node/v8.11.2/bin/node
    npm: 6.1.0 - ~/.nvm/versions/node/v8.11.2/bin/npm
  Browsers:
    Chrome: 67.0.3396.79
    Firefox: 47.0.1
    Safari: 11.1
  npmPackages:
    apollo-cache-inmemory: ^1.0.0 => 1.1.12 
    apollo-client: ^2.2.7 => 2.2.8 
    apollo-link: ^1.0.7 => 1.2.1 
    apollo-link-context: ^1.0.3 => 1.0.7 
    apollo-link-error: ^1.0.5 => 1.0.7 
    apollo-link-http: ^1.0.0 => 1.5.3 
    apollo-link-state: ^0.4.0 => 0.4.1 
    apollo-link-ws: ^1.0.1 => 1.0.7 
    apollo-utilities: ^1.0.3 => 1.0.11 
    react-apollo: ^2.1.3 => 2.1.3 
```

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Don't%20require%20an%20unnecessary%20id%20on%20write&body=Migrated%20from:%20apollographql/apollo-client%233565) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
