### ISSUE TITLE
Please merge the info on mutations.md to the Apollo Client docs.

### ISSUE THREAD

**Issue by eliecerthoms** [apollographql/apollo-client#3566]
**Docs modification request**

I believe it will be useful for users to see all the ways to do mutations more clearly in the docs. 

There is crucial information like _how to trigger multiple mutations from the UI, code examples and how to update the cache_ located in the `mutation.md` file in this repo that would be more accesible in the website. 

Assuming there are not plans or techniques to make mutations triggerable from the UI using the `Mutation` component, that is.

Thank you 😄

**Comment by hwillson** [comment]
Documentation in this repo is available at https://www.apollographql.com/. Everything you've suggested should be in the [Mutations](https://www.apollographql.com/docs/react/essentials/mutations.html) section. If you're seeing something in the repo that isn't published, please post back with direct links. Thanks!

**Comment by eliecerthoms** [comment]
@hwillson 
[This information](https://github.com/apollographql/apollo-client/blob/master/docs/source/basics/mutations.md), which I think is vital for non-UI-triggered mutations is nowhere to be found in the [Mutations](https://www.apollographql.com/docs/react/essentials/mutations.html) section, and it is a pain having to remember its location everytime I want to have a refresher on how things work.  

Are these methods going to be deprecated or something? The closest thing you can find on the site is [this](https://www.apollographql.com/docs/react/api/react-apollo.html#graphql-mutation-options), and unless you know what you're doing, you'll probably not look for it there. Also, the examples are more thorough in the first link I referenced. 

I'm asking at least for a link to it from the main site. It will surely benefit new users, too.
