### ISSUE TITLE
apollo-boost's master branch was fixed credentials config bug, but npm package's code is old(0.1.7)

### ISSUE THREAD

**Issue by h1bomb** [apollographql/apollo-client#3575]
https://github.com/apollographql/apollo-client/blob/0bdf5871c7305e8df02cc48168176a3532275fb6/packages/apollo-boost/src/index.ts#L80

npm code like this
```typescript
    const httpLink = new HttpLink({
      uri: (config && config.uri) || '/graphql',
      fetchOptions: (config && config.fetchOptions) || {},
      credentials: 'same-origin',
    });

```

please update apollo-boost npm version to the least version，thanks~

**Comment by hwillson** [comment]
The fix should be available now @h1bomb (0.1.8 was deployed this morning). You can see the full details in the [CHANGELOG](https://github.com/apollographql/apollo-client/blob/master/CHANGELOG.md). Thanks!
