### ISSUE TITLE
Accessing an unfetched or unimplemented field in a query result gives no warning or error

### ISSUE THREAD

**Issue by bessey** [apollographql/apollo-client#3577]
**Intended outcome:**

Given a schema with a type `User`, who has two fields, `id` and `email`, and a query which fetches `query { user { id } }`, and a component which accesses from the `data` object `data.user.email`, I would expect a warning / error that an unfetched field has been accessed.

Similarly, if I were to access a field which _doesn't_ exist on `User`, I would expect a warning / error that the field does not exist.

This is the behaviour [Github's Ruby graphql-client exhibits](https://github.com/github/graphql-client/blob/master/guides/unfetched-field-error.md), and it is tremendously useful for catching cases where a query / fragment and its matching component have drifted. This is the kind of amazing thing you can only do with a client side understanding of the schema.

**Actual outcome:**

No warning or error occurs, the view happily returns `undefined` for both cases.

**How to reproduce the issue:**
Example sandbox
https://codesandbox.io/s/l46l3j1ypl

**Versions**
All versions that I am aware of, but in this sandbox:
```
    "apollo-client": "1.7.0",
    "react": "15.6.1",
    "react-apollo": "1.4.3",
    "react-dom": "15.6.1"
```

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Accessing%20an%20unfetched%20or%20unimplemented%20field%20in%20a%20query%20result%20gives%20no%20warning%20or%20error&body=Migrated%20from:%20apollographql/apollo-client%233577) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
