### ISSUE TITLE
refetchQueries not working when using string array

### ISSUE THREAD

**Issue by washingtonsoares** [apollographql/apollo-client#3582]
**Intended outcome:**
Refetch queries  in a string array after Mutation.

**Actual outcome:**
 
in the version of Apollo 1.9.3 when I pass `refetchQueries` as an array of strings it works perfectly. In Apollo 2.x it "converts" the array of strings to an array of objects and somehow loses the variables that would be used in `refetchQueries` and therefore `refetchQueries` does not work as expected.

*`refetchQueries` in Apollo 1.9.3*
![image](https://user-images.githubusercontent.com/5726140/41357905-9262a1ae-6efd-11e8-9991-065c86d3ee15.png)

*The same `refetchQueries` in Apollo 2.x*
![image](https://user-images.githubusercontent.com/5726140/41358260-60898246-6efe-11e8-9a53-a38ecdafc10f.png)

 

**Versions**
System:
    OS: Linux 4.15 Ubuntu 18.04 LTS (Bionic Beaver)
  Binaries:
    Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
    Yarn: 1.7.0 - /usr/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
  Browsers:
    Chrome: 67.0.3396.79
    Firefox: 60.0.1
  npmPackages:
    apollo-cache-inmemory: ^1.1.12 => 1.1.12 
    apollo-client: 2.3.3 => 2.3.3 
    apollo-link: ^1.2.1 => 1.2.1 
    apollo-link-context: ^1.0.7 => 1.0.7 
    apollo-link-http: ^1.5.3 => 1.5.3 
    apollo-link-set-context: ^0.5.4 => 0.5.4 
    apollo-upload-client: ^5.1.1 => 5.1.1 
    react-apollo: 2.1.0-beta.3 => 2.1.0-beta.3

**Comment by NiklasBeierl** [comment]
Thank you for pointing this out, I was facing the same problem today.

Would you like to share how you worked around it?

**Comment by rmalca** [comment]
Same problem here, ¿any progress?

**Comment by washingtonsoares** [comment]
@rmalca 
I figured out that apparently this bug is actually in the react-apollo. But I don't know how to solve this or any workaround.

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
