### ISSUE TITLE
Bad Performance with large number of watchers

### ISSUE THREAD

**Issue by thomassuckow** [apollographql/apollo-client#3589]
**Intended outcome:**
Having a large number of queries should not block the the javascript runtime

**Actual outcome:**
Processing a graphql response takes > 300ms

**How to reproduce the issue:**
* Have a large number (~26) of React components be mounted with the same graphql query.

**Versions**
System:
    OS: macOS High Sierra 10.13.5
  Binaries:
    Node: 10.0.0 - /usr/local/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.87
    Firefox: 59.0.2
    Safari: 11.1.1
  npmPackages:
    apollo-cache-inmemory: ^1.1.12 => 1.2.1
    apollo-client: ^2.2.8 => 2.3.1
    react-apollo: ^2.1.3 => 2.1.4

apollo-client/react-apollo perform a large amount of work when there is multiple listeners to a query.

<img width="925" alt="screen shot 2018-06-14 at 17 19 17" src="https://user-images.githubusercontent.com/3100037/41444638-2d2788de-6ff9-11e8-979a-dd9497342277.png">

This causes significant performance implications as the page appears "laggy" when being interacted with. This cost could be hidden behind the loading time and the actual page update is cheap. Normally I would batch the updates in a requestAnimationFrame (and in fact do that in a custom apollo-link). However there is no well documented place to hook into where this is happening. It appears the cache.write method is being invoked each time and that could be made asynchronous but there is no documentation about the assumptions of a cache provider and whether hacking a custom cache in front of the inmemory cache would be safe.

<img width="334" alt="screen shot 2018-06-14 at 17 22 29" src="https://user-images.githubusercontent.com/3100037/41444723-ad8163d8-6ff9-11e8-8a15-07b3bb3ae398.png">

**Comment by thomassuckow** [comment]
Here is a contrived demo

https://codesandbox.io/s/ozpqoyw46

I had to increase the number of components with the same query to 100, my guess is performance is also a function of how many queries you've already have loaded and since this example doesn't have much it takes more to make the problem as problematic.

<img width="1662" alt="screen shot 2018-06-15 at 07 22 03" src="https://user-images.githubusercontent.com/3100037/41473000-e0da39b2-706c-11e8-8e50-bf6ac01a4097.png">

**Comment by benjamn** [comment]
Would you mind trying out a beta version of `apollo-cache-inmemory`?
```sh
npm install apollo-cache-inmemory@beta
```
See here for more details: https://github.com/apollographql/apollo-client/pull/3394

**Comment by thomassuckow** [comment]
I am seeing a noticeable 2x improvement in performance. It is much more tolerable.

I am seeing an unusual warning though:

```
../node_modules/optimism/lib/local.js
15:14-32 Critical dependency: the request of a dependency is an expression
warnings @ index.js
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
../node_modules/optimism/lib/local.js
Module not found: Error: Can't resolve 'fibers' in 'node_modules/optimism/lib'
warnings @ index.js
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
```
My guess is that is expected... with the hack in the optimism library to try and load fibers.
I think there probably still should be a way to break up the execution of BroadcastWrites but maybe that is what you are trying to achieve with the fibers?



For the sake of completeness I include performance information for my trials

apollo-cache-inmemory@1.3.0-beta.2, development build
--

Total 410ms
Broadcast Writes: 6-10ms
Broadcast occurances ~42

<img width="1298" alt="screen shot 2018-06-18 at 07 51 48" src="https://user-images.githubusercontent.com/3100037/41544440-9be98fc0-72cd-11e8-94c0-dc0bd9912565.png">
<img width="556" alt="screen shot 2018-06-18 at 07 53 23" src="https://user-images.githubusercontent.com/3100037/41544444-a08f0c94-72cd-11e8-94af-1df8420b7be1.png">


apollo-cache-inmemory@1.3.0-beta.2, production build
--

Total: 360ms
Broadcast Writes: 6-8ms
Broadcast occurances ~43

<img width="1175" alt="screen shot 2018-06-18 at 08 05 25" src="https://user-images.githubusercontent.com/3100037/41544838-983fba42-72ce-11e8-9777-d39bfb34a8a2.png">
Note: Flamegraph is "sampled" and some methods occur more than once despite only being invoked once (i.e. _processCallbacks).


apollo-cache-inmemory@1.2.1, development build
--

Total: 837ms
Broadcast Writes: 16-22ms
Broadcast Occurances: ~43

<img width="1050" alt="screen shot 2018-06-18 at 08 25 40" src="https://user-images.githubusercontent.com/3100037/41546138-b487d06a-72d1-11e8-85f3-7bb96b6ebfbc.png">

<img width="1336" alt="screen shot 2018-06-18 at 08 26 40" src="https://user-images.githubusercontent.com/3100037/41546146-ba19274a-72d1-11e8-8405-719456bb48a4.png">


apollo-cache-inmemory@1.2.1, production build
--

Total: 624ms
Broadcast Writes: 13-15ms
Broadcast Occurances: ~41

<img width="1371" alt="screen shot 2018-06-18 at 08 20 37" src="https://user-images.githubusercontent.com/3100037/41545751-c574be0c-72d0-11e8-9d4c-4d2cfa1c005c.png">

**Comment by benjamn** [comment]
@thomassuckow What bundling tool is giving you those warnings?

**Comment by thomassuckow** [comment]
Webpack 3.12.0

**Comment by benjamn** [comment]
While you can safely ignore those warnings, I think I have a plan to silence them.

**Comment by goldo** [comment]
Thx a lot, looking forward to this release ! We have the same problem !

**Comment by thomassuckow** [comment]
@benjamn Would simply installing the fibers library alter the behaviour of the library or is that something that should only be enabled when react has fibers? And if so, why is it not just a dependency?

**Comment by goldo** [comment]
Any news on this ? :) I also have the warnings

**Comment by goldo** [comment]
We tried this PR in our app, in production, we got some navigator crashes :( We rolled back to `1.1.9`

**Comment by nevir** [comment]
@thomassuckow I'd be curious to see how https://github.com/convoyinc/apollo-cache-hermes stacks up for your case (assuming it supports all the functionality you rely on)

**Comment by thomassuckow** [comment]
@nevir When I tried appllo-cache-hermes before posting this, it just crashed in a ball of flames.

I in my testing I believe I only had basic queries. Though we do use a custom apollo-link without subscription support.

**Comment by nevir** [comment]
Damn! I'd be curious what errors you ran into—or I can attempt to
reproduce: were you doing this in your code sandbox example (
https://codesandbox.io/s/ozpqoyw46), or something else?

**Comment by thomassuckow** [comment]
https://codesandbox.io/s/k0mj92nx9o has my sandbox attempt with hermes.

**Comment by nevir** [comment]
Interesting thing about this example: apollo-client is triggering a cache write for every observer (even though only a single request is made)

**Comment by thomassuckow** [comment]
0.5.28-alpha was the hermes version I had tried before and it didn't work. The current 0.6.2 version seems to work well with the exception of convoyinc/apollo-cache-hermes#208.

Much less scientific than before as data has changed so the graphql queries are different and hermes appears to cause my animation frame hack to not behave as ideally.

But still, it appears to be faster with react being the bigger bottleneck overall in development mode, though still room for improvement:

apollo-cache-hermes@0.6.2, development build
Total time: 190ms

<img width="836" alt="screen shot 2018-07-09 at 09 53 21" src="https://user-images.githubusercontent.com/3100037/42464526-2499121e-835e-11e8-9d3f-70d3797509f6.png">

apollo-cache-hermes@0.6.2, production build
Total time: 80ms

<img width="1223" alt="screen shot 2018-07-09 at 10 04 47" src="https://user-images.githubusercontent.com/3100037/42464975-926c84fa-835f-11e8-8751-dd0d2714a860.png">

I'd probably switch to hermes today if not for the devtools not working. That would be the death of my other developers.

**Comment by nevir** [comment]
Re: dev tools; that's unfortunately probably going to be a fair bit of work :(

The "quick 'n dirty" approach is likely to have Hermes emit events that make it appear like apollo-cache-inmemory to the dev tools. Long term is probably to spec out some cache-agnostic way of describing cache state w/o exposing internals

**Comment by thomassuckow** [comment]
Streamlining cache updating when there is a single request and many observers would help apollo regardless of the cache mechanism and make how long processing a response takes much more predictable.

I'm actually kinda surprised the devtools reach so deep into the cache implementation.

**Comment by nevir** [comment]
> I'm actually kinda surprised the devtools reach so deep into the cache implementation. One of these days I need to build the devtools from scratch. They are buggy as hell anyway.

Last time I looked at them, they were directly consuming the serialized form of inmemory's state

**Comment by thomassuckow** [comment]
Not knowing a lot about making a custom apollo-cache. One would think it would contain simply the queries and variables of all current queries that shouldn't be evicted (ie. are in use on the page). and then a graph representing data loaded from the server so it can avoid making requests for data already retrieved but with a different query. The api to traverse the graph for the devtools might be interesting. but if you assume a user will traverse it one level at a time you could just have an api that traverses it one level at a time and be oblivious to the cycles issue.

**Comment by nevir** [comment]
Yeah, it'd be ideal; I think the [current approach](https://github.com/apollographql/apollo-client-devtools/blob/903e8111a706923b53f0a5de742265f93edf9b7d/src/backend/broadcastQueries.js#L22) was made for pragmatic reasons (also, back when the dev tools were originally built, there was no notion of pluggable caches).  Needs some love, 'tis all :)

**Comment by hwillson** [comment]
I believe everything directly actionable has been addressed in this thread, so I'll close this off. Let us know otherwise - thanks!
