### ISSUE TITLE
Authentication middleware not invoked on client.mutate from a redux saga

### ISSUE THREAD

**Issue by dimitar-nikovski** [apollographql/apollo-client#3597]
I am using the recommended way from the documentation to attach an authorization header to graphql requests:

**myApolloClient.ts**
```
// Create an http link:
const httpLink = new HttpLink({
    uri: `${location.protocol}//${REMOTE_HOST}:${GRAPHQL_PORT}/graphql`
});

const authMiddleware = new ApolloLink((operation, forward) => {
    // add the authorization to the headers
    operation.setContext({
        headers: {
            Authorization: localStorage.getItem('token') || null,
        }
    });
    return forward(operation);
});

const link = split(
    // split based on operation type
    ({ query }) => {
        let definition = getMainDefinition(query);
        return definition.kind === 'OperationDefinition' && definition.operation === 'subscription';
    },
    wsLink,
    concat(authMiddleware, httpLink)
);

export const myClient = new ApolloClient({
    link: link,
    cache: new InMemoryCache()
});
```
**Intended outcome:**

Import the client into my sagas.js and: 

```
import { myClient  } from './myApolloClient';
import gql from 'graphql-tag';

const MY_MUTATION = gql`mutation myMutation($Value: MyType) {
     myMutation(Value: $Value)
}`;

function* myApiMutator(action) {
    // omitted for convenience

    let result = yield myClient.mutate({
                mutation: MY_MUTATION,
                variables: {
                    Value: myValue
                }
            });

    // rest of saga and putting actions back to the store here...
}
```
Expected outcome is for the mutation to be sent to the server together with the authorization header being attached by the middleware passed to the client intitialization in myApolloClient.ts

**Actual outcome:**
The authorization header is not set and when putting a breakpoint inside authMiddeware, I can catch that it is invoked in all graphql operations called from the UI components, either by the graphql HOC or by using the Query, Mutation components from react-apollo.

The middleware, however, is not invoked when calling operations from the exported myClient.

**Versions**
System:
    OS: Windows 10
  Binaries:
    Yarn: 1.5.1
    npm: 6.0.0
  npmPackages:
    apollo-cache-inmemory: ^1.2.4 => 1.2.3
    apollo-client: ^2.3.4 => 2.3.3
    apollo-link: ^1.2.2 => 1.2.2
    apollo-link-context: ^1.0.8 => 1.0.8
    apollo-link-error: ^1.0.9 => 1.1.0
    apollo-link-http: ^1.5.4 => 1.5.4
    apollo-link-ws: ^1.0.8 => 1.0.8
    apollo-upload-client: ^8.0.0 => 8.0.0
    apollo-utilities: ^1.0.15 => 1.0.14
    react-apollo: ^2.1.5 => 2.1.5

**Comment by dimitar-nikovski** [comment]
Interestingly calling client.query from a generator saga using the same setup does attach the token and invokes the middleware.

**Comment by hwillson** [comment]
Any chance you can provide a small runnable reproduction that demonstrates this? Thanks!

**Comment by hwillson** [comment]
We haven't heard back regarding a reproduction, so closing for now. Happy to re-open if anyone can provide a repro. Thanks!
