### ISSUE TITLE
passing headers with each request

### ISSUE THREAD

**Issue by farahamawi** [apollographql/apollo-client#3602]
Hello apollo team
I'm using apollo client with my react app, and trying to pass my token with every request to the server, her is my code to connect to the server uri

const networkInterface = createNetworkInterface({
  uri: `http://${process.env.REACT_APP_BACKEND_IP}:${process.env.REACT_APP_BACKEND_PORT}/graphql`,
});
networkInterface.use([{
  applyMiddleware(req, next) {
    if (!req.options.headers) {
      req.options.headers = {}; // Create the header object if needed.
    }
    // get the authentication token from local storage if it exists
    const token = localStorage.getItem('token');
    req.options.headers.authorization = token || null;
    next();
  },
}]);
export const apolloClient = new ApolloClient({
  networkInterface,
});

my issue is that from the backend side the authorization inside req.headers does not exist(undefined) on the first 2-3 requests after that it's exists(I can see the token in req.headers.authorization).

I wonder if apollo client tries to connect to my server before applying the middleware that I created!!

How to get the token in every request form apollo client to the server

**Comment by hwillson** [comment]
Any chance you can provide a small runnable reproduction that demonstrates this? Thanks!

**Comment by hwillson** [comment]
We haven't heard back regarding a reproduction, so closing for now. Happy to re-open if anyone can provide a repro. Thanks!
