### ISSUE TITLE
API doc issues

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-client#3603]
Reported via [Slack](https://apollographql.slack.com/archives/C0Z9ZBDF0/p1529603348000724?thread_ts=1529601260.000613&cid=C0Z9ZBDF0):

- It would be nice to provide some additional context in the [`watchQuery`](https://www.apollographql.com/docs/react/api/apollo-client.html#ApolloClient.watchQuery) API section that helps explain what the `errorPolicy` and `fetchPolicy` options do. As a start, making sure the `ErrorPolicy` and `FetchPolicy` interface links work should help.
- We should mention that [`ObservableQuery`](https://www.apollographql.com/docs/react/api/apollo-client.html#ObservableQuery) uses `zen-observable`, and link to the `zen-observable` documentation somewhere (to help expose the additional `zen-observable` API options that we're not documenting in the Apollo Client API docs).

**Comment by MikaelCarpenter** [comment]
Any feedback on that one is appreciated! ☝️
