### ISSUE TITLE
OptimisitcResponse creation order miss-match when back online.

### ISSUE THREAD

**Issue by bamne123** [apollographql/apollo-client#3607]
Hi Team, 

I am working on chat feature implementation in my app, where I am trying to achieve offline feature using Optimistic UI of Apollo Client.
I am facing 2 Issues as of now,

When I am offline, I send some messages to goes in queue and when I get back online, it goes to the server in Batch query but the time of creation of all the offline messages are same.
To solve this issue I have introduce another column of localCreation time, but when the query Again hits the **update** it does not keep order.

Code :
```js
this.props.client.mutate({
  mutation: CreateMessage,
  variables: {
    message: text,
    userId: userId,
    creationDate: new Date()
  },
  optimisticResponse: {
    __typename: "Mutation",
    createMessage: {
      __typename: "Message",
      createdAt: message.createdAt,
      system: false,
      text: message.text,
      creationDate: new Date(),
      user: {
        __typename: "Users",
        _id: userId
      },
      _id: message._id
    }
  },
  update: (store, { data: { createMessage } }) => {
    console.log(createMessage);
    const data = store.readQuery({
      query: GetAllMessages,
      variables: {
        startFrom: 0
      }
    });

    data.allMessages.unshift(createMessage);

    try {
      store.writeQuery({
        query: GetAllMessages,
        variables: {
          startFrom: 0
        },
        data
      });
    } catch (e) {
      console.log(e);
    }
  }
});

const GetAllMessages = gql`
  query GetAllMessages($startFrom: Int!) {
    allMessages(first: 100, skip: $startFrom, orderBy: creationDate_DESC) {
      _id: id
      text
      createdAt
      creationDate
      system: isSystem
      user: sentBy {
        _id: id
        name: username
      }
    }
  }
`;

```
**Intended outcome:**
I am looking for the solution, When the app comes online either it should fire update again or It should keep the values in order at time of writing back to the Cache.
 

**Actual outcome:**
When the app comes back online, the values shown using Optimistic Response, does not keep track of the time of creation of messages.

**How to reproduce the issue:**

**Versions**

  System:
    OS: macOS Sierra 10.12.6
  Binaries:
    Node: 9.4.0 - /usr/local/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.87
    Safari: 11.1.1
  npmPackages:
    apollo-cache-inmemory: ^1.2.4 => 1.2.4 
    apollo-cache-persist: ^0.1.1 => 0.1.1 
    apollo-client: ^2.3.5 => 2.3.5 
    apollo-link: ^1.2.2 => 1.2.2 
    apollo-link-context: ^1.0.8 => 1.0.8 
    apollo-link-http: ^1.5.4 => 1.5.4 
    apollo-link-queue: ^2.0.1 => 2.0.1 
    apollo-link-retry: ^2.2.4 => 2.2.4 
    apollo-link-state: ^0.4.1 => 0.4.1 
    apollo-link-ws: ^1.0.8 => 1.0.8 
    apollo-utilities: ^1.0.15 => 1.0.15 
    react-apollo: ^2.1.5 => 2.1.5

**Comment by hwillson** [comment]
Could you please provide a small runnable reproduction that demonstrates this issue? Thanks!

**Comment by hwillson** [comment]
We haven't heard back regarding a reproduction, so closing for now. Happy to re-open if anyone can provide a repro. Thanks!
