### ISSUE TITLE
apollo-link-batch-http not sending uncached persisted queries

### ISSUE THREAD

**Issue by NGPixel** [apollographql/apollo-client#3610]
**Problem:**
When using persisted queries with `apollo-link-batch-http`, the first request returns a `PersistedQueryNotFound` error _(expected)_ but doesn't follow with the full query back to the server.

Switching from `apollo-link-batch-http` to `apollo-link-http` temporarily fix the issue as queries are now cached by the server. Going back to `apollo-link-batch-http` then works as expected, until the server persisted queries cache is cleared.

**Versions:**
- apollo-client: 2.3.5
- apollo-link-batch-http: 1.2.2
- apollo-link-persisted-queries: 0.2.1

**Sample Client Code:**
```js
const graphQLLink = createPersistedQueryLink().concat(new BatchHttpLink({
  includeExtensions: true,
  uri: '/graphql',
  credentials: 'include'
}))

window.graphQL = new ApolloClient({
  link: graphQLLink,
  cache: new InMemoryCache()
})
```

**Comment by hwillson** [comment]
Would you mind re-opening this over in the http://github.com/apollographql/apollo-link repo? Thanks!
