### ISSUE TITLE
Pass `extensions` to the client

### ISSUE THREAD

**Issue by djyde** [apollographql/apollo-client#3613]
Need the `extensions` object in the query result. Same as https://github.com/apollographql/react-apollo/issues/2059

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Pass%20%60extensions%60%20to%20the%20client&body=Migrated%20from:%20apollographql/apollo-client%233613) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
