### ISSUE TITLE
Adds __typename to queries but complains that __typename hasn't been added.

### ISSUE THREAD

**Issue by kayalukenvolatile** [apollographql/apollo-client#3616]
Despite using Apollo boost, with default behaviour that __typename field is automatically added to queries like so;
```
mutation ($name: String!)  { 
  createFoo(input: {foo: {name: $name}}){
    foo { 
        name 
        __typename
   } 
    __typename }
 }
```
when trying to implement updates, I still get
`You're using fragments in your queries, but either don't have the addTypename:
  true option set in Apollo Client, or you are trying to write a fragment to the store without the __typename.
   Please turn on the addTypename option and include __typename when writing fragments so that Apollo Client
   can accurately match fragments.`

With further error
```
writeToStore.js:137 Missing field __typename in {
  "allFoos": {
    "__typename": "FoosConnection",
    "nodes": [
      {
        "__typename"
```

Although __typename field appears present.

I have also manually added __typename to fragments

`fragment Bar on Foo{
    __typename
   fooField
   barField
}`

but still get error.

`Could not find __typename on Fragment  Bar`

Possibly related is I have queries with unions and interfaces and apparently Apollo Boost doesnt support fragments on such.

**Versions**

  System:
    OS: macOS High Sierra 10.13.4
  Binaries:
    Node: 9.8.0 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.87
    Firefox: 59.0.1
    Safari: 11.1

**Comment by vnenkpet** [comment]
I have the exact same problem. I'm not using unions at all. Interfaces yes, but in a completely unrelated query.

**Comment by hwillson** [comment]
This should no longer be an issue with modern versions of `apollo-client`. Thanks!
