### ISSUE TITLE
Explain in the documentation that we can also refetchQueries without providing variables

### ISSUE THREAD

**Issue by googol7** [apollographql/apollo-client#3617]
I consider this sentence in the [API documentation](https://www.apollographql.com/docs/react/api/react-apollo.html#graphql-mutation-options-refetchQueries
) as very important:

> If options.refetchQueries is an array of strings then Apollo Client will look for any queries with the same names as the provided strings and will refetch those queries with their current variables. 

I suggest that it should be included in the [docs](https://www.apollographql.com/docs/react/advanced/caching.html#after-mutations) as well because there you don’t talk about this possibility and the user (beginner) is left with the impression that he always has to provide the variables - which is not true.

- [x] docs

**Comment by hwillson** [comment]
This has been addressed in https://github.com/apollographql/apollo-client/pull/3764. Thanks for the suggestion!

**Comment by googol7** [comment]
@hwillson thanks for including this hint. React users will appreciate it. For the other clients this hint is missing - e.g. Angular: https://www.apollographql.com/docs/angular/features/cache-updates.html#refetchQueries

**Comment by hwillson** [comment]
Thanks @googol7 - this repo is just associated with the core Apollo Client / React Apollo docs. There are separate repos for the other docs, with different maintainers. Any chance you could open a new issue for this in the https://github.com/apollographql/apollo-angular repo for example? Thanks!
