### ISSUE TITLE
Bad performance with windowed (offset-based) pagination

### ISSUE THREAD

**Issue by csnover** [apollographql/apollo-client#3632]
**Intended outcome:** Consistent good performance.
**Actual outcome:** Bad performance with lots of jank.
**How to reproduce the issue:**

1. Visit https://pqz544ml0.codesandbox.io/
2. Scroll list labelled “Apollo”. Performance problems increase with number of times the list is scrolled.
3. Scroll list labelled “Vanilla”. Performance is consistent.

I saw some comments about improvements to the in-memory cache in other issues so this test case *is* using the latest published beta tag; problems persist.

**Versions**
See the dependency list on CodeSandbox. https://codesandbox.io/s/pqz544ml0

As far as I know I am correctly following the [pagination documentation](https://www.apollographql.com/docs/react/features/pagination.html) for offset-based pagination, but since this is a very common use case I wouldn’t expect to run into this problem if I were doing everything correctly, so please let me know if there is a mistake in the test case.

This could be exposing the same bug as #3589 since the `Query` HOC is creating a new watcher in the cache every time `fetchMore` is called, so the number of watchers grows quickly.

I don’t know enough about how Apollo Client works at this point to give any other good analysis.

Thanks for your hard work on this library!

**Comment by Dattaya** [comment]
`InfiniteLoader.loadMoreRows` is better suited for this purpose, but if you want to use `onRowsRendered` (it's called frequently), better to check if the rows were previously loaded, for a list, this should probably work (at the beginning of `fetchRows`):

```js
    const {
      data: { allFoos: oldFoos }
    } = this.props; 
    if (oldFoos && oldFoos.nodes && oldFoos.nodes[toIndex]) {
      return;
    }
```

**Comment by hwillson** [comment]
Please try out the latest version of `apollo-client` (there have been numerous performance improvements made over the past while), and post back if you're still encountering issues. Thanks!
