### ISSUE TITLE
Add another example to static typing docs

### ISSUE THREAD

**Issue by jeffwillette** [apollographql/apollo-client#3638]
The docs here (https://www.apollographql.com/docs/react/recipes/static-typing.html) have a great example of how to get started with static typing the Apollo components, but I am getting confused about how to go about modifying them more. 

it gives the initial example and says...

```
Since we are not mapping any props coming into our component, nor are we rewriting the props passed down, we only need to provide the shape of our data and the variables requried for it to work
```

and then the document goes on to explain in more detail how to handle the HOC's but it only gives this very simplistic example of how to handle the components

Is it possible to add a more detailed example of how to accomplish the same things with the components that is provided in the example with the HOCs?

**Comment by deltaskelta** [comment]
I did find this other issue which is the only info I can find on the subject, But I cannot get this solution to work for me ATM
