### ISSUE TITLE
Early return prevents optimisticResponse to happen when network error

### ISSUE THREAD

**Issue by gastonmorixe** [apollographql/apollo-client#3643]
https://github.com/apollographql/apollo-client/blob/ba97741c4fa20a0a1415c9fc85f99902ebb20fbc/packages/apollo-client/src/core/QueryManager.ts#L522

Is this early return right? Optimistic updates when network is offline is not working for me. 

After half a day tracing it line by line, I see when `queryStoreValue.networkError` is true it is impossible to reach `observer.next(maybeDeepFreeze(resultFromStore));` therefore optimistic update won't work, they remain queued.

Am I right? how should we fix this?

Thank you

**Comment by hwillson** [comment]
This should no longer be an issue in Apollo Client 2.6.3. Thanks!
