### ISSUE TITLE
ApolloProvider client prop change does not update withApollo consumers

### ISSUE THREAD

**Issue by awwong1** [apollographql/apollo-client#3648]
**Intended outcome:**
When the `client` prop in `ApolloProvider` changes, consuming components using `withApollo` should use this new client.

Only other issue I found was https://github.com/apollographql/apollo-client/issues/2897 which seems to be closed without resolution. I am updating my apollo client instance when the user logs in, or logs out. I put a JWT in the HTTP header `authentication`.

```tsx
// sample init client function
function initApolloClient(token: string | null) {
  const link = new ApolloLink((operation, forward) => {
    const authorizationHeader = token ? `Bearer ${token}` : undefined;
    operation.setContext({
      headers: {
        authorization: authorizationHeader
      }
    });
    return forward!(operation); // not sure when this is undefined
  });

  return new ApolloClient({
    link,
    cache: new InMemoryCache(),
  });
}

// some provider HOC stub, WrappedComponent being App or something
class ApolloProviderRefresher extends Component {
  public constructor() {
    this.state = {
      client: initApolloClient(null)
    }
  }
  // on some change, state is updated with auth parameters, eg:
  // this.setState({ client: initApolloClient(token) })
  public render() {
    const { client } = this.state;
    return <ApolloProvider client={client} children={WrappedComponent} />;
  }
}

// consuming components
// withApollo(SampleConsumerOne);
```

**Actual outcome:**

Components using `withApollo` continue to use the old ApolloClient. Request headers do not show an updated authentication header.

My current workaround is to update the render method such that there is a brief period where the ApolloProvider is not rendered, then render it again with the new client.

```tsx
// updated provider HOC stub
class ApolloProviderRefresher extends Component {
  public constructor() {
    this.state = {
      client: initApolloClient(null),
      loading: false
    }
  }
  
  // example
  public handleNewClient = () => {
    this.setState({ loading: true });
    const client = initApolloClient("new token");
    this.setState({ loading: false, client });
  }

  public render() {
    const { loading, client } = this.state;
    if (!loading) {
      return <ApolloProvider client={client} children={WrappedComponent} />;
    } else {
      return <span>Loading...</span>
    }
  }
}
```

This isn't ideal as there is now a brief flicker whenever I update my client.

**How to reproduce the issue:**
I have sample foss code that shows this issue, as well as the workaround:
* [ApolloClient init func](https://github.com/udia-software/udia-client/blob/eb92499e17e4a20c2d1d0c27428e92b3d9a47b21/src/Modules/InitApolloClient.ts)
* [ApolloProviderHOC](https://github.com/udia-software/udia-client/blob/eb92499e17e4a20c2d1d0c27428e92b3d9a47b21/src/Components/Wrapper/RefreshingApolloProvider.tsx#L36)

**Versions**
```bash
$ yarn list | grep apollo
├─ apollo-cache-inmemory@1.2.5
│  ├─ apollo-cache@^1.1.12
│  ├─ apollo-utilities@^1.0.16
├─ apollo-cache@1.1.12
│  └─ apollo-utilities@^1.0.16
├─ apollo-client@2.3.5
│  ├─ apollo-cache@^1.1.12
│  ├─ apollo-link-dedup@^1.0.0
│  ├─ apollo-link@^1.0.0
│  ├─ apollo-utilities@^1.0.16
├─ apollo-link-dedup@1.0.9
│  └─ apollo-link@^1.2.2
├─ apollo-link-http-common@0.2.4
│  └─ apollo-link@^1.2.2
├─ apollo-link-http@1.5.4
│  ├─ apollo-link-http-common@^0.2.4
│  └─ apollo-link@^1.2.2
├─ apollo-link-ws@1.0.8
│  └─ apollo-link@^1.2.2
├─ apollo-link@1.2.2
│  ├─ apollo-utilities@^1.0.0
├─ apollo-utilities@1.0.16
│  └─ apollo-utilities@^1.0.16
├─ react-apollo@2.1.6
```

**Comment by SirJalias** [comment]
I had the same issue, when I make a query with HOC graphql if it returns an error because I sent an invalid token, when I changed the header with a valid token the 401 error was there always.

So I did a workaround, I don't like it but it works, I wrapped the component with the HOC withApollo that propagates the prop client and if I had an error of invalid token I reset the store of the Apollo Client this way:

```
client.resetStore()
```

I hope this helps a bit!

**Comment by kwbskf** [comment]
Wait, if you expect all components to stop using their existing apollo client and start using the new one, then how can you have an application with multiple components using different apollo clients?  Maybe I'm just misunderstanding the issue.

**Comment by MichaelHuy** [comment]
Got same Error

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
