### ISSUE TITLE
Query Deduplication on Cached Object

### ISSUE THREAD

**Issue by leontaolong** [apollographql/apollo-client#3663]
I recently read an article about Apollo Client Caching on the [official blog](https://blog.apollographql.com/the-concepts-of-graphql-bc68bd819be3), with a screenshot here:

 <img width="7600" alt="screen shot 2018-07-05 at 11 27 08 pm" src="https://user-images.githubusercontent.com/22493572/42397787-21899d1c-811c-11e8-870f-6eaa7bcbf422.png"> According to the article, if the current query contains a cached object, along with other objects, the query will be deduplicated to only query the rest of the objects.

However, I did some testing by logging out queries on the server, which suggested that the query had not been partially deduplicated. Instead, the entire query got sent to the server. To investigate this, I read the `readFromStore.ts` and `inMemoryCache.ts` source code in the Apollo Client Repo. It turns out that it determines if the query `shouldFetch` by `diff()`ing the cache and the query, which works like this:  `Given a store and a query, return as much of the result as possible and identify if any data was missing from the store.`  

According to the source code, the second query that queries more objects will be determined as `missing`, and the entire query gets sent to the server without modification.

Can anyone provide any insight on this. Thanks very much. Any input would be greatly appreciated!

Test: 

First query:
```
{
   post(_id: 1) {
      _id
      title
   }
}
```

Second query:
```
{
   post(_id: 1) {
      _id
      title
   }
   author(_id: 1) {
      _id
      firstName
   }
}
```

**Intended outcome:**

The secomd query received by the server only contains 
```
author(_id: 1) {
      _id
      firstName
   }
```
since `post(_id: 1)` has been cached after the first query is sent. 

**Actual outcome:**

Server log: (the second query has **NOT** been deduplicated)
```
{
   "operationName": null,
   "variables": {},
   "query": "{\n  post(_id: 1) {\n    _id\n    title\n    __typename\n  }\n}\n"
} /graphql 200 81 - 0.520 ms

{
   "operationName": null,
   "variables": {},
   "query": "{\n  post(_id: 1) {\n    _id\n    title\n    __typename\n  }\n  author(_id: 1) {\n    _id\n    firstName\n    __typename\n  }\n}\n"
} /graphql 200 140 - 0.726 ms
```

**How to reproduce the issue:**

Send two queries to the server, where the second query contains the same object in the first query, along with other objects. See above query example. 

**Versions**

```
  System:
    OS: macOS High Sierra 10.13.5
  Binaries:
    Node: 8.11.2 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 60.0.2
    Safari: 11.1.1
  npmPackages:
    apollo-cache-inmemory: ^1.2.5 => 1.2.5
    apollo-client: ^2.3.5 => 2.3.5
    apollo-link-http: ^1.5.4 => 1.5.4
```

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Query%20Deduplication%20on%20Cached%20Object&body=Migrated%20from:%20apollographql/apollo-client%233663) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
