### ISSUE TITLE
Different inline arguments on same fields across different queries screws up cache

### ISSUE THREAD

**Issue by erickreutz** [apollographql/apollo-client#3676]
It seems as though when I set the arguments explicitly inline in different fragments on the same types and then use those fragments through my application it screws up the cache. Example below.

### This DOES NOT work.
If I'm viewing the list - navigating to the new screen and request the details for a single product with different explcit arguments it seems to blow the cache up.

```
// Query One
fragment ProductListItem on Product {
  id
  name
  images {
   id
   url(density: 3, width: 100, height: 200)
  }
}

query ProductListView {
  products {
    ...ProductListItem
  }
}

// Query Two
fragment ProductDetail on Product {
  id
  name
  description
  price
  images {
   id
   url(density: 3, width: 400, height: 400)
  }
}

query ProductDetailView {
  products {
    ...ProductDetail
  }
}
```

### This DOES work
The cache is maintained but I'm not very fond of it.

```
// Query One
fragment ProductListItem on Product {
  id
  name
  images {
   id
   url(density: $density, width: $width, height: $height)
  }
}

query ProductList($density: Int!, $width: Int!, $height: Int!) {
  products {
    ...ProductListItem
  }
}

// Query Two
fragment ProductDetail on Product {
  id
  name
  description
  price
  images {
   id
   url(density: $density, width: $width, height: $height)
  }
}

query ProductDetailView($density: Int!, $width: Int!, $height: Int!) {
  products {
    ...ProductDetail
  }
}
```

I'm wondering if this expected behavior? If what you are reading doesn't make much sense I'm happy to shed some additional light and an example. Any help would be appreciated. Thanks!

**Comment by hwillson** [comment]
A small runnable reproduction here would definitely help. In particular, when you say

> it seems to blow the cache up.

what do you mean?

**Comment by hwillson** [comment]
We haven't heard back regarding a reproduction, so closing for now. Happy to re-open if anyone can provide a repro. Thanks!
