### ISSUE TITLE
Docs: Essentials: Mutations -- codesandbox gives undefined error for { data } in render prop function

### ISSUE THREAD

**Issue by drrckln** [apollographql/apollo-client#3678]
**Intended outcome:**
Attempting to follow the docs for Mutation components, using the starter project.

**Actual outcome:**
Upon trying to use the Mutation component, I receive: TypeError Cannot read property 'data' of undefined. If you continue on, other uses of a 2nd argument (for example, { loading, error}) for the render prop function of a Mutation component similarly error.

**How to reproduce the issue:**
Use the linked starter project on the Mutations page. Import the Mutation component, then follow along by adding ADD_TODO and changing AddTodo to return a Mutation component.

**Versions**
Almost certainly has to do with the version of react-apollo used, as the completed version codesandbox works fine. I will submit a pull request.

- [ ] has-reproduction
- [ ] feature
- [x] docs
- [ ] blocking
- [ ] good first issue

**Comment by drrckln** [comment]
Submitted PR.

**Comment by hwillson** [comment]
https://github.com/apollographql/apollo-client/pull/3679 has been merged - thanks @drrckln!
