### ISSUE TITLE
Better support for processing non-rendered polling results

### ISSUE THREAD

**Issue by serle** [apollographql/apollo-client#3684]
I need use a polling query to regularly fetch updates from the server, The polling query returns the delta's from the server after a given timestamp. The results of the polling query need to be integrated into my Apollo cache using a conflict resolution algorithm. 

If I attempt to use the <Query/> component the result data is not needed directly for child rendering but it is needed to update the Apollo cache i.e. make a change during the render. I therefore need some callback after each polling cycle and a version of the Query component that does not re-render its child.

So I have reverted to using withApollo and calling query on the client directly, but again I need to process each query result before starting the next polling cycle. Eventually I manually constructed a polling loop with a await on the query result.

I think this use-case should supported more directly by the API

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Better%20support%20for%20processing%20non-rendered%20polling%20results&body=Migrated%20from:%20apollographql/apollo-client%233684) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
