### ISSUE TITLE
Documentation shows "queryVariables", should be "variables"

### ISSUE THREAD

**Issue by Billy-** [apollographql/apollo-client#3694]
Documentation for `updateQuery` notes that the second parameter is an object with two properties; `fetchMoreResult` and `queryVariables`. I am using the latest `apollo-client` and it seems to just be `variables`, not `queryVariables`.

**Comment by hwillson** [comment]
Thanks for pointing this out @Billy-. This has been addressed in https://github.com/apollographql/apollo-client/pull/3762.
