### ISSUE TITLE
`fetchMore` erroneously calls `updateQuery` in race conditions

### ISSUE THREAD

**Issue by dallonf** [apollographql/apollo-client#3695]
**Intended outcome:**

A list where the user can either load more items (via `fetchMore`) or change the parameters of the list (filter, sorting, etc., by changing the `variables` prop on a `Query).

**Actual outcome:**

Two fetches, one from `fetchMore` and one from `setVariables`, can be happening simultaneously. Depending on the order of the results, this can cause the `updateQuery` function provided to `fetchMore` to be called with an empty `prev` value.

**How to reproduce the issue:**

1. Open this sandbox: https://codesandbox.io/s/ow71r90xz
2. Click "Load more..."
3. While it's loading, choose another sort option
4. Watch the console

You will see that `updateQuery` (which logs every time it's called) has been called with the results of the `fetchMore`, but an empty `prev` value. The function assumes that `prev` will always be a valid query and fails with an error. (If I were to try to detect this situation and `return prev`, Apollo would warn that the result is "Missing field people in {}".)

The expected behavior to me is that `updateQuery` should not even have been called here; the request is longer relevant because the user has changed the query's variables since then.

**Versions**

In the repro Code Sandbox:

* `apollo-boost` v0.1.10
* `graphql` v0.13.2
* `react` v16.4.1
* `react-apollo` v2.1.9
* `react-dom` v16.4.1

In the real-world project where I observed this issue:

```
  System:
    OS: macOS Sierra 10.12.6
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 58.0.1
    Safari: 11.1.2
  npmPackages:
    apollo-cache-inmemory: ^1.1.5 => 1.2.1 
    apollo-client: ^2.3.5 => 2.3.5 
    apollo-link-context: ^1.0.3 => 1.0.8 
    apollo-link-http: ^1.3.2 => 1.5.4 
    apollo-utilities: ^1.0.4 => 1.0.12 
    react-apollo: ^2.1.9 => 2.1.9 
```

**Comment by jakwuh** [comment]
Have exactly the same issue with exactly the same reproduce steps.
It was sad to realize that canonical pagination example does not handle race conditions.

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
