### ISSUE TITLE
React: having a mutation and query accessing the same data on the same component throws error

### ISSUE THREAD

**Issue by mllrmat** [apollographql/apollo-client#3697]
Hi, 

I have one component, which has two queries and one mutation. One of the queries fetches the same Data as the mutation modifies. The third query fetches different data and always works. I bound the queries to the component using the compose() function. 

If I use the component just with the queries it works, and if I use the component with just the mutation it works perfectly. But if I use the component with both the queries and the mutation it fails with an obscure "GraphQL error: Variable 'user_uuid' has coerced Null value for NonNull type 'ID!'" error. It only happens after the network call, so it seams that the query is refetching (from cache?) and fails during this operation. 

**Intended outcome:**
Having a query and mutation on the same component, bound by compose(). 

**Actual outcome:**
Fails with "GraphQL error: Variable 'user_uuid' has coerced Null value for NonNull type 'ID!'" If I put the query to another component it works perfectly, and updates the values as set by the mutation. 

**How to reproduce the issue:**

This is how I compose the queries: 

```
export default compose(
  withNavigation,
  connect(
    mapStateToProps,
    mapDispatchToProps
  ),
  graphql(userHasOpenOrders, {
    options: (props: any) => {
      return {
        variables: {
          user_uuid: props.user_uuid,
          app_user_uuid: props.app_user_uuid
        }
      }
    },
    name: 'usersOpenOrders'
  }),
  graphql(getTables, {
    options: (props: any) => {
      return {
        variables: {
          user_uuid: props.user_uuid
        }
      };
    },
    name: 'getTables'
  }),
  graphql(addOrderCollection, {
    options: (props: any) => {
      return {
        variables: props.orderObject,
        onError: (error) => console.log('apollo error', error),
      };
    },
    name: 'addOrder'
  }),
)(CartModal)
```

The addOrderCollection mutation modifies data that the userHasOpenOrders query fetches. 

```
**Versions**
  System:
    OS: macOS High Sierra 10.13.5
  Binaries:
    Node: 10.3.0 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.2.0 - ~/Development/getsby/getsby-react-native/node_modules/.bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 57.0.4
    Safari: 11.1.1
  npmPackages:
    react-apollo: ^2.1.9 => 2.1.9 
```

        "aws-amplify": "^0.4.8",
        "aws-appsync": "^1.2.1",
        "aws-appsync-react": "^1.0.21",
        "aws-sdk": "^2.275.1",
        "graphql-tag": "^2.9.2",
        "npm": "^6.2.0",
        "react": "^16.3.1",
        "react-apollo": "^2.1.9",

**Comment by hwillson** [comment]
Would you be able to provide a small runnable reproduction that demonstrates this issue? Thanks!

**Comment by hwillson** [comment]
We haven't heard back regarding a reproduction, so closing for now. Happy to re-open if anyone can provide a repro. Thanks!
