### ISSUE TITLE
Documentation on Query component seems to be out of date

### ISSUE THREAD

**Issue by Lukas-Kullmann** [apollographql/apollo-client#3698]
The [Documentation on the Query component](https://www.apollographql.com/docs/react/essentials/queries.html#props) says, that the Query component has a property called delay, but it actually does not exist according to the [React Apollo API documentation](https://www.apollographql.com/docs/react/api/react-apollo.html#query-props).

So I wonder which documentation is correct.

**Comment by hwillson** [comment]
Addressed by https://github.com/apollographql/apollo-client/pull/3806. Thanks!
