### ISSUE TITLE
Source maps point to non existent files

### ISSUE THREAD

**Issue by biels** [apollographql/apollo-client#3699]
**Intended outcome:**

Sourcemaps are detected and used correctly.
**Actual outcome:**
When building a typescript project that uses apollo with source maps, webpack produces the following outpùt: 
```
WARNING in ./node_modules/apollo-client/util/Observable.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../../src/util/Observable.ts': Error: Can't resolve '../../src/util/Observable.ts' in 'C:\Users\biel\projects\MS\Inv\invoices\invoices-app\node_modules\apollo-client\util'
 @ ./node_modules/apollo-client/core/ObservableQuery.js 21:0-48 419:2-12
 @ ./node_modules/apollo-client/index.js
 @ ./src/core/data/client.ts
 @ ./src/index.tsx
 @ multi ./src/index.tsx webpack-hot-middleware/client

WARNING in ./node_modules/apollo-client/ApolloClient.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../src/ApolloClient.ts': Error: Can't resolve '../src/ApolloClient.ts' in 'C:\Users\biel\projects\MS\Inv\invoices\invoices-app\node_modules\apollo-client'
 @ ./node_modules/apollo-client/index.js 6:0-42 8:0-24 9:15-27
 @ ./src/core/data/client.ts
 @ ./src/index.tsx
 @ multi ./src/index.tsx webpack-hot-middleware/client

(and many more)
```

**How to reproduce the issue:**
Download the package from npm and check that index.js.map has the following content: 
`{"version":3,"file":"index.js","sourceRoot":"","sources":["../src/index.ts"],"names":[],"mappings":"AAAA,OAAO,EAAE,KAAK,IAAI,QAAQ,EAAE,MAAM,0BAA0B,CAAC;AAE7D,OAAO,EACL,eAAe,GAIhB,MAAM,wBAAwB,CAAC;AAahC,OAAO,EAAE,aAAa,EAAE,MAAM,sBAAsB,CAAC;AACrD,cAAc,cAAc,CAAC;AAE7B,OAAO,EAAE,WAAW,EAAE,MAAM,sBAAsB,CAAC;AAEnD,OAAO,YAAqC,MAAM,gBAAgB,CAAC;AAInE,8CAA8C;AAC9C,OAAO,EAAE,YAAY,EAAE,CAAC;AACxB,eAAe,YAAY,CAAC"}`
Note the `../src/index.ts` which ipoints to a file that doesn't exist. The package does not contain an src directory at all. My guess is that sourcemaps should either be self-contained or the src folder should be included to the npm package.

**Versions**

```
  System:
    OS: Windows 10
  Binaries:
    Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    apollo-cache-inmemory: ^1.2.5 => 1.2.5
    apollo-client: ^2.3.5 => 2.3.5
    apollo-link: ^1.2.2 => 1.2.2
    apollo-link-error: ^1.1.0 => 1.1.0
    apollo-link-http: ^1.5.4 => 1.5.4
    react-apollo: ^2.1.9 => 2.1.9
```

**Comment by maapteh** [comment]
@hwillson is it possible to distribute your packages without sourcemaps since the reference is false anyway.

**Comment by sturoid** [comment]
Same issue as @viridia  with apollo-client 2.4.12 and newest version of parcel-bundler 1.11.0.

**Comment by klemenoslaj** [comment]
I have the same issues with Angular CLI, or even with a clean webpack/typescript project.
Is there any plan to fix that?

**Comment by maapteh** [comment]
@klemenoslaj i dont think so, i made the PR https://github.com/apollographql/apollo-client/pull/4185 and asked the team which route to take since the current one is simply wrong. But no answer...

**Comment by maapteh** [comment]
In version 3 this will be solved

**Comment by maclockard** [comment]
Source maps still point to non existent files as of @apollo/client 3.1.0

**Comment by maclockard** [comment]
looks like there are two issues:
1. `prepareDist.js` does not copy over the relevant source files to each package
2. `prepareDist.js` also needs to walk every sourcemap and fix the path so that it points to the copied file

Honestly, this feels like a pretty error prone packaging process. I would be curious why `apollo-client` doesn't just use a monorepo like `apollo-server`. If it did, there wouldn't be any need for path rewriting, which doesn't even fully work on the `package.json`s since it only rewrites values and not keys (this misses the `react-native` key).

**Comment by prograhammer** [comment]
I'm seeing the same problem in v3.1.3. I'm noticing that `sourcesContent` is not in the map files, which is very useful for browsers. Perhaps the build process (UglifyJs) or something is broken?

**Comment by prograhammer** [comment]
Here's what I did for a dirty quick work-around to fix those sourcemaps:

Drop this file in your project root, or linked package, where apollo is.
In my case `path.resolve('./node_modules/@apollo/client')`:

**fix-maps.js**
```js
/* eslint-disable */
const fs = require('fs');
const path = require('path');
async function* walk(dir) {
    for await (const d of await fs.promises.opendir(dir)) {
        const entry = path.join(dir, d.name);
        if (d.isDirectory()) yield* walk(entry);
        else if (d.isFile()) yield entry;
    }
}
async function main() {
    let counter;
    for await (const p of walk(path.resolve('./node_modules/@apollo/client'))) {
      counter++;
      if (p.indexOf('.js.map') !== -1) {
        const mappath = p;
        const jspath = p.replace('.map', '');
        // @TODO: Make these async for more perf.
        const js = fs.readFileSync(jspath, {encoding:'utf8', flag:'r'});
        const map = JSON.parse(fs.readFileSync(mappath, {encoding:'utf8', flag:'r'}));
        // Add missing source content to the .map files.
        map.sourcesContent = js;
        fs.writeFileSync(mappath, JSON.stringify(map));
      }
    }
    console.log(`Updated ${parseInt(counter)} files`);
}
main();
```
Then just run it with `node fix-maps.js`.

**Comment by mkaraula** [comment]
We are experiencing the same Issue with `"@apollo/client": "3.2.2"`

**Comment by mkaraula** [comment]
When changing `sources":["../src/index.ts"]` to `sources":["./src/index.ts"]`in `node_modules/@apollo/client/index.js.map` the warnings go away. 

I dont really know how the build of this project works, otherwise I would contribute a fix by myself.  But maybe my finding helps someone who knows the project better than me.

**Comment by hwillson** [comment]
Can someone confirm if this is still an issue with `@apollo/client@latest`? I'll close this for now, but happy to re-open if this is still happening. Thanks!

**Comment by maclockard** [comment]
@hwillson just tried with `@apollo/client@latest`, which resolves to `3.3.15` for me. It appears to be working, I no longer get any warnings from webpack's `source-map-loader` indicating missing source maps.

**Comment by hwillson** [comment]
Yay! Thanks for confirming @maclockard!

**Comment by Pika-Pool** [comment]
Getting this issue when using vite:

deps versions:
- "@apollo/client": "^3.4.15"
- "vite": "^2.6.7"

package manager: tried both pnpm and yarn

is there any fix for this?

**Comment by TheHussein** [comment]
Why is this issue closed?

**Comment by andrewmtam** [comment]
Hey @TheHussein , curious if you ever resolved this error or found a workaround -- I'm running into the exact same thing

**Comment by SimonStiph** [comment]
How has this bug gone unresolved for so long, and why was was marked closed? Can someone re-open this, as the issue most definitely has no resolution.
