### ISSUE TITLE
Data reducer requires queries and mutations to be passed in

### ISSUE THREAD

**Issue by Slava** [apollographql/apollo-client#370]
Right now the `data` reducer requires `mutations` and `queries` to be passed in because the information in the `APOLLO_MUTATION/QUERY_RESULT` action is not enough to apply a change.

Instead, we should make actions fatter and pass in all the necessary info. After that we should stop passing in mutations and queries into the data reducer.

**Comment by abhiaiyer91** [comment]
I agree actions should hold more info, which is a very redux like approach. It'll also be more flexible.

**Comment by stubailo** [comment]
Yep, I now realized that relying on all of that stuff already being in the store was a mistake.

**Comment by stubailo** [comment]
If anyone is interested, this could be a relatively simple refactor to tackle.

**Comment by abhiaiyer91** [comment]
Alright I'll make the changes

**Comment by stubailo** [comment]
Amanda's on it now.
