### ISSUE TITLE
cacheRedirects does not get called after a mutation

### ISSUE THREAD

**Issue by alamothe** [apollographql/apollo-client#3702]
I have the following schema:

```graphql
type User {
  email: String!
  firstName: String!
  id: ID!
  lastName: String!
}

type Mutation {
  login(email: String!, password: String!): User
}

type Query {
  me: User!
}
```

The idea is that after `login` I could just use the returned `User` and avoid an additional roundtrip. To accomplish this, I make use of `cacheRedirects` like this:

```javascript
const cache = new InMemoryCache({
	cacheRedirects: {
		Query: {
			me: (_, args) => {
				const token = decodeToken()
				return toIdValue(defaultDataIdFromObject({ __typename: 'User', id: token.userId })!)
			},
		},
	},
})
```

**Intended outcome:**

I expect that `me` query will be served from cache (after `login` mutation)

**Actual outcome:**

`cacheRedirects` does not get called at all. It does get called in a different circumstance (for example, if I point my browser in a new tab to already logged in page), but not after the mutation.

**How to reproduce the issue:**

**Versions**

```
  System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 10.6.0 - /usr/local/bin/node
    npm: 6.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 61.0.1
    Safari: 11.1.2
  npmPackages:
    apollo-cache-inmemory: ^1.2.5 => 1.2.5 
    apollo-client: ^2.3.5 => 2.3.5 
    apollo-link-context: ^1.0.8 => 1.0.8 
    apollo-link-http: ^1.5.4 => 1.5.4 
    apollo-link-schema: ^1.1.0 => 1.1.0 
    react-apollo: ^2.1.9 => 2.1.9 
```

**Comment by hwillson** [comment]
Thanks for reporting this. Would you be able to provide a small runnable reproduction that demonstrates this problem?

**Comment by hwillson** [comment]
We haven’t heard back regarding a reproduction, so we’ll close this off for now. Thanks!
