### ISSUE TITLE
Re-use refs on mutation

### ISSUE THREAD

**Issue by Elijen** [apollographql/apollo-client#3708]
I am experiencing a similar problem to #2489

Having a query:
```gql
query {
  todos() {
     id
     isDone
     subItems {
        id
        name
     }
   }
}
```

When a mutation updates `isDone` of a todo:
```gql
mutation {
   updateTodo() {
      id
      isDone
   }
}
```

`todo.subItems` ref changes which causes re-render of all subItems even though only `isDone` has actually changed and got refetched. `subItems` are still re-used from cache.

**Intended outcome:**
subItems ref should not change if none of the subItems actually changed

**Actual outcome:**
subItems ref changes even though only a sibling prop `isDone` has actually changed

**Versions**
System:
    OS: macOS 10.14
  Binaries:
    Node: 10.1.0 - ~/.nvm/versions/node/v10.1.0/bin/node
    npm: 5.6.0 - ~/.nvm/versions/node/v10.1.0/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 60.0.2
    Safari: 12.0
  npmPackages:
    apollo-client-preset: ^1.0.8 => 1.0.8 
    apollo-link-error: 1.1.0 => 1.1.0 
    react-apollo: ^2.1.6 => 2.1.6

**Comment by hwillson** [comment]
Any chance you could provide a small runnable reproduction that demonstrates this? Thanks!

**Comment by Elijen** [comment]
@hwillson Do you know if there is a sample project with a similar (mocked) schema I could use?

**Comment by hwillson** [comment]
For repros, we usually recommend starting from the https://github.com/apollographql/react-apollo-error-template (or its https://codesandbox.io/s/7361K9q6w equivalent). Thanks!

**Comment by hwillson** [comment]
We haven't heard back regarding a reproduction, so closing for now. Happy to re-open if anyone can provide a repro. Thanks!
