### ISSUE TITLE
Can't transform/normalize/modify response of GraphQL query

### ISSUE THREAD

**Issue by rafaelsales** [apollographql/apollo-client#3710]
```js
  const networkLink = split(
    ({ query }) => {
      const { kind, operation } = getMainDefinition(query);
      return kind === 'OperationDefinition' && operation === 'subscription';
    },
    webSocketLink,
    httpLink,
  )

  const parseResponse = new ApolloLink((operation, forward) => {
    return forward(operation).map((response) => {
      response.data.parsed = transformData(response.data)
      return response
    })
  })

  const link = parseResponse.concat(networkLink)

  return new ApolloClient({
    link: link,
    cache: new InMemoryCache({ addTypename: true }),
    defaultOptions: {
      query: {
        fetchPolicy: 'no-cache', // This was an attempt to fix this issue, but it didn't work
        errorPolicy: 'all',
      },
    },
  })

```

This works great with subscriptions (websockets events) - the data is transformed, added to the `parsed` field in the `data`, but on a regular `<Query.../>` request, the `parsed` field disappears, so the component can't read it. I've confirmed that this method is called correctly in query requests and that the `parsed` field is added to `response.data`, but somewhere between the _afterware_ and the component the `parsed` field is removed

**Comment by ecrofeg** [comment]
It is truly frustrating :( 
#2534

**Comment by ecrofeg** [comment]
@rafaelsales Did you find any solution?

**Comment by dandv** [comment]
Saw the question on SO and I've posted an [answer over there](https://stackoverflow.com/questions/51429840/cant-transform-normalize-modify-response-of-graphql-query-apollo-client/62419143#62419143).

**Comment by hwillson** [comment]
See solution in https://github.com/apollographql/apollo-client/issues/3710#issuecomment-645062588 - thanks!
