### ISSUE TITLE
Cleanup optimistic update tests

### ISSUE THREAD

**Issue by joshribakoff** [apollographql/apollo-client#3712]
I'm a new potential contributor. Id like to work on this issue

https://github.com/apollographql/apollo-client/issues/3691

I notice these tests are quite involved and I feel like I should simplify them before adding more test code. I would flatten these with async await and extract some test helpers to cut down on boilerplate. From there it would be easier to add more tests and easier to maintain going forward.

https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/__tests__/optimistic.ts

Please let me know if this sounds good and Ill get started on cleaning up these tests. Then once that is done I could look into adding new tests to expose the race conditions with the concurrent updates clobbering state.

**Comment by hwillson** [comment]
Hi @joshribakoff - new contributions are always welcome! We're definitely open to code changes that help make the codebase more manageable. Cleaning up the tests sounds great. Thanks!

**Comment by hwillson** [comment]
We'll close this for now due to low activity, but if anyone is interested in working on this, definitely let us know. Thanks!
