### ISSUE TITLE
Mutations do not execute serially

### ISSUE THREAD

**Issue by joshribakoff** [apollographql/apollo-client#3715]
**Intended outcome:**

Mutations should execute serially, they should either be batched into one http request to where a compliant server will execute serially, or the client should queue new mutations if some are already in flight

**Actual outcome:**

Mutations execute in parallel and race, completing in non deterministic order.

**How to reproduce the issue:**

Create a mutation & create a random delay on the server. Rapidly trigger mutations. 

- [x] has-reproduction
- [x] feature
- [x] docs
- [ ] blocking
- [ ] good first issue

https://github.com/helfer/apollo-link-serialize solves the issue. We could add a note to the docs explaining the current behavior & how this link solves it if order matters.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Mutations%20do%20not%20execute%20serially&body=Migrated%20from:%20apollographql/apollo-client%233715) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
