### ISSUE TITLE
afteware with promise generates an error when running a mutation

### ISSUE THREAD

**Issue by rares-lupascu** [apollographql/apollo-client#3716]
**Intended outcome:**
I want to inspect the headers of every request and store the ones i need

**Actual outcome:**
![image](https://user-images.githubusercontent.com/3641866/43036605-a73a52e2-8d0d-11e8-9860-8d1a18a7965b.png)

**How to reproduce the issue:**
```js
const afterwareLink = new ApolloLink((operation, forward) => {
    const store = async response => {
        await somePromise;
        return response;
    }
    return forward(operation).map(response => {
        const { response: { headers } } = operation.getContext();
        if (headers) {
            return store(response);
        } else {
            return response;
        }
    });
});

const client = new ApolloClient({
    cache,
    link: ApolloLink.from([errorLink, stateLink, afterwareLink.concat(authLink.concat(httpLink)) ])
});
```

**Versions**
System:
    OS: Windows 10
  Binaries:
    npm: 6.1.0 - C:\Users\Rarutu\AppData\Roaming\npm\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    apollo-cache-inmemory: ^1.2.5 => 1.2.5
    apollo-client: ^2.3.5 => 2.3.5
    apollo-link: ^1.2.2 => 1.2.2
    apollo-link-context: ^1.0.8 => 1.0.8
    apollo-link-error: ^1.1.0 => 1.1.0
    apollo-link-http: ^1.5.4 => 1.5.4
    apollo-link-state: ^0.4.1 => 0.4.1
    react-apollo: ^2.1.9 => 2.1.9

(node:158824) UnhandledPromiseRejectionWarning: Error: The system cannot find the path specified.

    at Function.e.exports.sync (C:\Users\Rarutu\AppData\Roaming\npm-cache\_npx\158824\node_modules\envinfo\dist\cli.js:2:7690)
    at Object.copySync (C:\Users\Rarutu\AppData\Roaming\npm-cache\_npx\158824\node_modules\envinfo\dist\cli.js:2:104342)
    at Object.t.writeSync.e [as writeSync] (C:\Users\Rarutu\AppData\Roaming\npm-cache\_npx\158824\node_modules\envinfo\dist\cli.js:2:122592)
    at C:\Users\Rarutu\AppData\Roaming\npm-cache\_npx\158824\node_modules\envinfo\dist\cli.js:2:123354
    at Promise.all.then.e (C:\Users\Rarutu\AppData\Roaming\npm-cache\_npx\158824\node_modules\envinfo\dist\cli.js:2:123369)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:158824) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:158824) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated.
In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

- [x] has-reproduction
- [ ] feature
- [ ] docs
- [x] blocking
- [ ] good first issue

**Comment by natterstefan** [comment]
Hi @rareslupascu, where you able to resolve this? If yes, how? Can you share it with me, please?

**Comment by hwillson** [comment]
Please try a recent version of @apollo/client and let us know if this issue is still happening. Thanks!
