### ISSUE TITLE
Docs: add lit-apollo integration (LitElement - Polymer)

### ISSUE THREAD

**Issue by LasaleFamine** [apollographql/apollo-client#3722]
I have recently found this awesome implementation ApolloClient-LitElement that is missing in the docs. Maybe is worth to add:

https://github.com/bennypowers/lit-apollo

**Comment by bennypowers** [comment]
See also https://github.com/apollographql/apollo-client/pull/3668 ;)

**Comment by TimPietrusky** [comment]
@hwillson Sorry to ask this, but where is the link in the README? I only seem to find the Polymer one, but not the lit-apollo one.

**Comment by hwillson** [comment]
@TimPietrusky looks like @bennypowers has addressed this in https://github.com/apollographql/apollo-client/pull/4397. We'll get that merged soon - thanks!
