### ISSUE TITLE
race conditions between mutations, optimistic responses, and watchQuery

### ISSUE THREAD

**Issue by joshribakoff** [apollographql/apollo-client#3723]
If I create a watchQuery, then wait 1 tick of the event loop, then fire a mutation with an optimistic response... The `QueryObservable` returned by `watchQuery` immediately observes the optimistic response :tada: 

```
2 watchQuery created
40 Hello world,Second task,Do other stuff 
67 fire mutations
81 Optimistically generated,Hello world,Second task,Do other stuff
87 Optimistically generated 2,Optimistically generated,Hello world,Second task,Do other stuff
1090 Optimistically generated 2,This one was created witha mutation.,Hello world,Second task,Do other stuff
2095 Second mutation.,This one was created with a mutation.,Hello world,Second task,Do other stuff
```

If I create a watchQuery and in the same tick of the event loop I fire a mutation with an optimistic response... The `QueryObservable` returned by `watchQuery` then observes the previous state without the optimistic responses. I would expect it to include the optimistic responses from the mutations because they have fired already [albeit in the same tick]. :-1: 

```
1 watchQuery created
28 fire mutations
55 Hello world,Second task,Do other stuff
1060 Optimistically generated 2,This one was created witha mutation.,Hello world,Second task,Do other stuff
2058 Second mutation.,This one was created with a mutation.,Hello world,Second task,Do other stuff
```

If I first fire the mutations, then run a watchQuery, I expect to see the optimistic response already in there but its not :-1: 

```
1 fire mutations
35 watchQuery created 
76 Hello world,Second task,Do other stuff
1034 This one was created with a mutation.,Hello world,Second task,Do other stuff
2035 Second mutation.,This one was created with a mutation.,Hello world,Second task,Do other stuff
```

The reason this is important is it makes the library unpredictable and harder to test, and creates surface areas for race conditions.

**Comment by hwillson** [comment]
This should no longer be an issue in `apollo-client` 2.6.3. Thanks!
