### ISSUE TITLE
Provide update to fetchMore instead of updateQueries

### ISSUE THREAD

**Issue by ojczeo** [apollographql/apollo-client#3728]
Probably related to:
https://github.com/apollographql/apollo-client/issues/2499
also mentioned here https://github.com/Akryum/vue-apollo/issues/336

After many approaches and test I've found that, when I update query cache using `update` method results are updating fine. Problem happen when I'm trying to update same query cache using `updateQueries` calling `fetchMore` for that query. Query updates well, but after that, when I want to make any action on update array (remove item with mutations) placed in that query problems happens. 

**Intended outcome:**
Should update (remove) results without problems.

**Actual outcome:**
Instead of that:

![zrzut ekranu 2018-07-19 o 13 59 27](https://user-images.githubusercontent.com/1917131/42941115-ff5cc26a-8b5b-11e8-8b40-05991039395e.png)

**How to reproduce the issue:**
1. Provide query with nested array of Objects. For example
```graphql
type Directory {
    id:ID!
    # Directory name
    name: String!
    # Date of creation
    createdAt: Date!
    # Date of last update
    updatedAt: Date
    # nested files
    files(limit: Int=10, offset: Int=0): [File]
}

type Query {
    # .....
    getDirById( dirId: ID!, limit: Int, offset: Int ) : Directory
    # .....
}
```
2. Call query
3.  Call fetch more with proper params (`offset: 10`)
4. Update query (in this case using `vue-apollo`)
```js
export const omit = function (obj, omitKeys) {
  return Object.keys(obj).reduce((result, key) => {
    if (!omitKeys.find((omitKey) => { return key === omitKey; })) {
      result[key] = obj[key];
    }
    return result;
  }, {});
};

this.$apollo.queries.directory.fetchMore({
        variables,
        updateQuery: (previousResult, { fetchMoreResult: { getDirById: { files } } }) => {
          const udpatedResult = {
            getDirById: omit(previousResult.getDirById, ['files'])
          };
          udpatedResult.getDirById.files = [...previousResult.getDirById.files, ...files];
          return udpatedResult;
        }
      });
```
5. Try to call remove fetched item and update store using `update` param:
```js
this.$apollo.mutate({
            mutation: removeFileMutation,
            variables: {
              input: {
                id: fileId
              }
            },
            update(store, { data: { removeFile }}) {
              try {
                const storeData = store.readQuery(parentDirQuery);
                const index = storeData.getDirById.files.findIndex(file => file.id === removeFile.id);
                if (index > -1) {
                  storeData.getDirById.files.splice(index, 1);
                }
                storeData.getDirById.files;
                parentDirQuery.data = storeData;
                store.writeQuery(parentDirQuery);
              } catch (err) {
                console.log('err', err);
              }
           },
          }).then((response) => {
            if (response.data.removeFile.id !== fileId) {
              this.hide = false;
              throw new Error('file not removed');
            }
          }).catch((error) => {
            console.error(error, 'error');
          });
```
6. Array of `files` inside update `getDirById` query would contain index with assigned `empy` row:
![zrzut ekranu 2018-07-24 o 21 22 48](https://user-images.githubusercontent.com/1917131/43161265-e6f8455c-8f87-11e8-89d3-270e7b036a81.png)

When I try to make `fetchMore` feature as `mutation` everything works well. I think this could be related to `updateQueries` implementation. Also I'm able to operate over cache data in `update` inside mutation directly, in `fetchMore` I need to rewrite arrays, due to 
```RangeError: invalid array length ```

**Versions**
```
  System:
    OS: macOS High Sierra 10.13.4
  Binaries:
    Node: 10.3.0 - /usr/local/bin/node
    npm: 6.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 61.0
    Safari: 11.1
```

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
