### ISSUE TITLE
apollo-client/core/QueryManager.d.ts is broken

### ISSUE THREAD

**Issue by ZenSoftware** [apollographql/apollo-client#3729]
**Broken TypeScript definition in:** apollo-client@2.3.6

@hwillson I believe that TSC is producing a broken type definition file using your local machine's file system for: [apollo-client/src/core/QueryManager.ts#L1006](https://github.com/apollographql/apollo-client/blob/b9fb72f252a6c13f430d26acb8bab6ce44ae89ce/packages/apollo-client/src/core/QueryManager.ts#L1006)

`ERROR in node_modules/apollo-client/core/QueryManager.d.ts(70,26): error TS1005: ';' expected.`

This is the code producing the error:
```
getQueryWithPreviousResult<T>(queryIdOrObservable: string | ObservableQuery<T>): {
        previousResult: any;
        variables: import("../../../../../../../../../../Users/hwillson/Documents/git/apollo/apollo-client/packages/apollo-client/src/core/types").OperationVariables | undefined;
        document: DocumentNode;
    };
```

**Comment by arteforme** [comment]
Just updated and I'm also seeing this error

**Comment by kaelig** [comment]
+1

**Comment by hwillson** [comment]
`apollo-client` 2.3.7 has been published and should fix this. Let me know if you're still encountering any issues. Thanks!
