### ISSUE TITLE
watchQuery.currentResult() not returning data despite the data being in the cache

### ISSUE THREAD

**Issue by jclangst** [apollographql/apollo-client#3732]
**Intended outcome:**
Originally this started as: "Cache redirects to objects already in the cache should return partial responses when using `watchQuery.currentReult()` as per the docs (https://www.apollographql.com/docs/react/api/apollo-client.html#ObservableQuery.currentResult)." However, I now think that ``watchQuery.currentResult()`` has some undocumented race conditions. See the edits below.

**Actual outcome:**
**How to reproduce the issue:**
I have set up my cache as below. The query I am trying to redirect is just a pretty standard lookup by id query. Almost identical to what is in the docs right now.

```javascript
const cache: InMemoryCache = new InMemoryCache({
    cacheRedirects: {
        Query: {
            productById: (_, args, { getCacheKey }) => {
                console.log("Redirect activated");
                console.log(getCacheKey({ __typename: 'Product', id: args.id }))
                return getCacheKey({ __typename: 'Product', id: args.id })
            }
        },
    },
});
```

I have done the following:
(1) confirmed the redirects are firing
(2) that they generate the ids of objects that are in the cache as confirmed via cache introspection in apollo dev tools. This is what ``getCacheKey`` returns: ``{type: "id", generated: false, id: "Product:b5396d61-e8fe-483b-9771-48632b76c5b5", typename: "Product"}``
(3) subsequently called ``watchQuery.currentResult()`` and it returns empty data even though the ``partial`` flag is set to true.

EDIT:
When using `cache-only` as the fetch policy, I correctly get the correct data in the subscriber to the ``watchQuery`` observable; however, I still get empty data for ``watchQuery.currentResult()``.

EDIT 2:
Even when ``wacthQuery.currentResult()`` is called after ``watchQuery.result()`` has resolved, it still returns empty data. However, if you wait long enough, it eventually returns the proper data. Very odd. Definitely not what the documentation would lead me to believe.

**Versions**

  System:
    OS: Linux 4.15 Ubuntu 18.04 LTS (Bionic Beaver)
  Binaries:
    Node: 10.6.0 - ~/.nvm/versions/node/v10.6.0/bin/node
    Yarn: 1.7.0 - /usr/bin/yarn
    npm: 6.2.0 - ~/.nvm/versions/node/v10.6.0/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 61.0.1
  npmPackages:
    apollo: ^1.4.0 => 1.5.0 
    apollo-boost: ^0.1.10 => 0.1.10 
    apollo-cache-inmemory: ^1.2.2 => 1.2.6 
    apollo-client: ^2.3.2 => 2.3.7 
    apollo-link: ^1.2.2 => 1.2.2 
    apollo-link-context: ^1.0.8 => 1.0.8 
    apollo-link-error: ^1.0.9 => 1.1.0 
    apollo-link-http: ^1.5.4 => 1.5.4 
    apollo-link-state: ^0.4.1 => 0.4.1 
    apollo-server-express: ^1.3.6 => 1.4.0 
    apollo-upload-client: ^8.1.0 => 8.1.0 
    apollo-upload-server: ^6.0.0-alpha.1 => 6.0.0-alpha.1 
    react-apollo: ^2.1.4 => 2.1.9

**Comment by jclangst** [comment]
For anyone stumbling upon this. My current solution is to have two different queries:
(1) watchQuery with default fetch policy
(2) query with `cache-only` fetch policy (note: unlike what it says in the docs, `cache-only` does not throw an error on partial data in the cache)

**Comment by hwillson** [comment]
This should no longer be an issue with `apollo-client` 2.6.3. Thanks!
