### ISSUE TITLE
Duplicate fields in same query causes cache to work incorrectly

### ISSUE THREAD

**Issue by mbrowne** [apollographql/apollo-client#3735]
**Intended outcome:**
For a query like the following (let's call it query 1):
```
  query {
    people {
      id
      name
      friends {
        id
      }
      friends {
        name
      }
    }
  }
```
...apollo-client's caching logic should work the same way as if you wrote (query 2):
```
  query {
    people {
      id
      name
      friends {
        id
        name
      }
    }
  }
```

Alternatively, since this a query written this way was probably a mistake, there could be a warning or error message saying that these kinds of queries may cause the cache to misbehave.

**Actual outcome:**
It's probably easiest to see this in action:
https://github.com/mbrowne/react-apollo-error-template/blob/duplicate-fields-issue/src/App.js

If you have two React components that both query `people`, Apollo always thinks query 1 above has changed data even if the other query is totally unrelated. This causes double-rendering issues. If you remove the `friends` field or consolidate it (as in query 2 above), it fixes the double-rendering.

**How to reproduce the issue:**
Check out the `duplicate-fields-issue` branch of this repo:
https://github.com/mbrowne/react-apollo-error-template/tree/duplicate-fields-issue

**Versions**

  System:
    OS: macOS High Sierra 10.13.4
  Binaries:
    Node: 10.4.0 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 60.0.2
    Safari: 11.1
  npmPackages:
    apollo-cache-inmemory: ^1.2.2 => 1.2.6
    apollo-client: ^2.3.2 => 2.3.7
    apollo-link: ^1.2.2 => 1.2.2
    react-apollo: 2.1.4 => 2.1.4

**Debugging info**

I debugged this a bit and found that the cache issue was a result of this line evaluating to false:
https://github.com/apollographql/apollo-client/blob/e1f3a04c473ed004319ffb430ed3071773f19f27/packages/apollo-client/src/core/QueryManager.ts#L615

I didn't get as far as determining why that happened though.

**Comment by valignatev** [comment]
@mbrowne It's not necessarily a mistake. You can end up in such a situation by expanding a fragment selection for example. For example, 
```javascript
const MY_FRAGMENT = gql`
  fragment myFragment on myType {
    field1
    field2
    somethingElse { field3 }
  }
`;

const MY_QUERY = gql`
  query myQuery {
    myType {
      ...${MY_FRAGMENT}
      somethingElse { someOtherFieldnotInFragment }
    }
  }
`;
```
Hope the snippet makes sense :)

The correct behavior is defined in the spec under the Value Completion: https://facebook.github.io/graphql/draft/#sec-Value-Completion

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
