### ISSUE TITLE
error when install project with dependences include apollo 

### ISSUE THREAD

**Issue by skogerinfest** [apollographql/apollo-client#3743]
Error when install project with dependences include apollo

**Intended outcome:**
When execute npm install a project with dependencies include apollo ocurres an error references in this capture 
<img width="1680" alt="captura de pantalla 2018-07-26 a las 2 04 56 a m" src="https://user-images.githubusercontent.com/14006185/43269321-960b67ac-90c0-11e8-8185-52836c7cb581.png">
this error in line 70 of QueryManager.d.ts u have a import a archive local at HWilson this is a error
<img width="1680" alt="captura de pantalla 2018-07-26 a las 2 02 22 a m" src="https://user-images.githubusercontent.com/14006185/43269665-55b502c0-90c1-11e8-92c4-eab7206286f3.png">

**Actual outcome:**
U can fix this error with this in line 70 of QueryManager.d.ts 
<img width="1680" alt="captura de pantalla 2018-07-26 a las 2 04 38 a m" src="https://user-images.githubusercontent.com/14006185/43269476-e88aafd8-90c0-11e8-82d9-7e01d6d9734c.png">

and this in line 11 of of QueryManager.d.ts 

<img width="1680" alt="captura de pantalla 2018-07-26 a las 11 05 26 a m" src="https://user-images.githubusercontent.com/14006185/43270764-dd49be5e-90c3-11e8-8162-c31c3a1c8ebd.png">
use declarations OperationVariables are defined in types.js 
<img width="790" alt="captura de pantalla 2018-07-26 a las 2 04 47 a m" src="https://user-images.githubusercontent.com/14006185/43270156-5fd254f0-90c2-11e8-9fc9-98e1bcee0d8f.png">

**How to reproduce the issue:**

git clone https://github.com/itgroupsystems/carsclienteangular.git

npm install

u can see this error after execute npm install

**Versions**
3pas:carsclienteangular skogerInfest$ npx envinfo@latest --preset apollo --clipboard
npx: installed 1 in 2.364s

  System:
    OS: OS X El Capitan 10.11.6
  Binaries:
    Node: 10.4.0 - /usr/local/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 6.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 61.0
    Safari: 11.0.2
  npmPackages:
    apollo-angular: ^1.1.2 => 1.1.2 
    apollo-angular-link-http: ^1.1.1 => 1.1.1 
    apollo-boost: ^0.1.11 => 0.1.11 
    apollo-cache-inmemory: ^1.2.6 => 1.2.6 
    apollo-client: ^2.3.6 => 2.3.6 
    apollo-link-context: ^1.0.8 => 1.0.8 
    apollo-link-http: ^1.5.4 => 1.5.4

**Comment by hwillson** [comment]
This issue was resolved in `apollo-client` 2.3.7. Thanks!
