### ISSUE TITLE
Apollo Cache Inmemory Can't resolve 'fibers' in optimism lib

### ISSUE THREAD

**Issue by ralphchristianeclipse** [apollographql/apollo-client#3763]
versions
    "apollo-cache-inmemory": "^1.3.0-beta.6",
    "apollo-cache-persist": "^0.1.1",
    "apollo-client": "^2.3.7",
    "apollo-link-state": "^0.4.1",

any ideas?

**Comment by SleepyHarry** [comment]
I'm having what might be a related issue - `tuple` (from `immutable-tuple`) appears to be `undefined` while being used in the optimism lib. Also 1.3.0-beta.6

**Comment by Conturbo** [comment]
uh oh! im having the same issue! :D

**Comment by ramsaylanier** [comment]
More on this issue here: https://github.com/benjamn/optimism/issues/6

**Comment by ralphchristianeclipse** [comment]
@SleepyHarry solved by downgrading :D but will wait for the fix on optimism library.
