### ISSUE TITLE
Optimistic UI should work even when using a subscription

### ISSUE THREAD

**Issue by cedvdb** [apollographql/apollo-client#3771]
## Optimistic UI should work with subscription

Currently you have to use watchQuery to be able to use optimistic UI. Having optimistic UI to work with subscription would be nice. However the watchQuery function doesn't accept a subscription (only query). The subscribe method doesn't listen to cache changes.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Optimistic%20UI%20should%20work%20even%20when%20using%20a%20subscription&body=Migrated%20from:%20apollographql/apollo-client%233771) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
