### ISSUE TITLE
Error when using pollInterval with fetchPolicy cache-and-network 

### ISSUE THREAD

**Issue by Alivejke** [apollographql/apollo-client#3775]
When I'm trying to use fetchPolicy cache-and-network with pollInterval I have next error:
```Uncaught Error: Queries that specify the cache-first and cache-only fetchPolicies cannot also be polling queries.```
Could be related to this fix: https://github.com/apollographql/apollo-client/pull/3372 Since now we reset fetchPolicy to cache-first internally when using cache-and-network.
Would be nice to fix this issue or at least update error message.

Workaround that I use for now:
```
  ...
  componentDidMount() {
    setTimeout(() => {
      this.props.data.startPolling(1000);
    }, 0)
  }
  ...
```

**Comment by vladshcherbin** [comment]
Can confirm this issue, tried adding `pollInterval` when using `cache-and-network` and saw this error in console.

I can probably create a reproduction, maybe there is some kind of sandbox/example repo for that?

**Comment by OHUSAR** [comment]
Hello.

I was also under the impression `fetchPolicy: 'cache-and-network'` doesn't work with `pollInterval: ...`. However it is working fine, when I try to replicate the bug.

See: https://github.com/OHUSAR/react-apollo-error-template

I don't know what is your case, but in my case I had several nested `Query` components in my app and changing their policy from the default one (`cache-first`) to `cache-and-network` did the trick. Sadly, also modified demo with netsted Query components is working.

So the root of the problem probably lies somewhere else.

Modified demo such as this is working:
```tsx
          <Query
            query={gql(`
              query ErrorTemplate {
                people {
                  id
                  name
                }
              }`)}
              pollInterval={300}
              fetchPolicy='cache-and-network'
              notifyOnNetworkStatusChange={true}
            >
            {(result) => {
              if (result.loading) return <p>Loading...</p>;
              if (result.error) return <p>ERROR: {result.error}</p>;
              return (
                <Query
                    query={gql(`
                    query ErrorTemplate {
                      people {
                        id
                        name
                      }
                    }`)}
                    fetchPolicy='cache-only'
                    >
                    {({error, data, loading}) => {
                      const {people} = data;
                      if (loading) return <p>Loading...</p>;
                      if (error) return <p>ERROR: {error}</p>;
                      return (
                        <ul>
                          {people.map(person => <li key={person.id}>{person.name}</li>)}
                        </ul>
                      );
                    }}
                  </Query>
                );
            }}
          </Query>
```

**Comment by danilobuerger** [comment]
Closing as no reproduction was provided in one week. Feel free to reopen if you have a minimal reproduction.

**Comment by natterstefan** [comment]
Hi @danilobuerger,

> Closing as no reproduction was provided in one week.

Sorry, but @OHUSAR did provid a Demo: https://github.com/OHUSAR/react-apollo-error-template. And the demo still shows what's going wrong.

![image](https://user-images.githubusercontent.com/1043668/59839096-656fc000-9350-11e9-87d3-e2a806f259a7.png)

We are still having this issue. Can you take a look at the issue again, please?

**Comment by natterstefan** [comment]
Hello @danilobuerger 👋,

I just wanted to ask, if you've seen the comment above in the meantime.

**Comment by timbset** [comment]
I faced with the same problem. Tried to specify both default options and fetchPolicy on query to 'cache-and-network' and even to 'network-only', and I'm still having an issue.

**Comment by kirkchris** [comment]
This is definitely still an issue in `"@apollo/react-hooks": "3.1.3"`. It'd be great to have it fixed in the library.

In the interim there are two work-arounds:

1. Set `ssr: false` in your query options and polling will work just fine. The downside here is that this query won't be run or hydrated during your SSR, so that may not be acceptable for all use cases.

2. Implement your own polling as the `useQuery` return value provides a `refetch` function. This worked for us:
```
const { refetch, data, ... } = useQuery(QUERY);
  useEffect(() => {
    const intervalId = setInterval(() => {
      refetch();
    }, INTERVAL_TIME);
    return () => {
      clearInterval(intervalId);
    }
  }, [refetch]);
```

**Comment by zacksinclair** [comment]
@danilobuerger This is still an issue and the reproduction case provided in this thread illustrates it.  Can you please re-open this issue?

This link https://github.com/apollographql/apollo-client/issues/3775#issuecomment-440266949 has a very clear reproduction and documentation of the issue.

**Comment by eddivalen** [comment]
Hey guys, this worked for me:
```
mounted(){
      this.$apollo.queries.products.setOptions({
        pollInterval: 60000,
        fetchPolicy: 'no-cache'
      })
},
apollo:{
    repNotifications:{
      query: GET_PRODUCTS,
      loadingKey: 'loading',
      errorPolicy: 'all',
      fetchPolicy: 'no-cache',
      watchLoading(isLoading){
        this.loading = isLoading
      },
      variables(){
        return {
          product: this.product,
        }
      },
      pollInterval: 60000,
    },
},
```
