### ISSUE TITLE
setting newData to null in case of errors

### ISSUE THREAD

**Issue by gandhiamarnadh** [apollographql/apollo-client#3780]
**Intended outcome:**
1. query + variables A --> networkstatus - 2 --> networkstatus: 7 + graphql error
2. query + variables B -->  networkstatus - 2 -->networkstatus: 7 + data

**Actual outcome:**
1. query + variables A --> networkstatus - 2 --> networkstatus: 7 + graphql error
2. query + variables B -->  networkstatus - 2 --> missing call!

Possible cause:
upon receiving response  from 1 newData for query is supposed set to null  [here](https://github.com/apollographql/apollo-client/blob/f4dcbda93feb7aea353cb1d7f5fa0c7dd5d9dc82/packages/apollo-client/src/core/QueryManager.ts#L558)  because query has an error function is exited from [here](https://github.com/apollographql/apollo-client/blob/f4dcbda93feb7aea353cb1d7f5fa0c7dd5d9dc82/packages/apollo-client/src/core/QueryManager.ts#L544) missing setting newData to null. Subsequent query 2 is not registered with observer as it is failing this [condition](https://github.com/apollographql/apollo-client/blob/f4dcbda93feb7aea353cb1d7f5fa0c7dd5d9dc82/packages/apollo-client/src/core/QueryManager.ts#L503) there by missing data and network status updates.

I was able resolve my problem my issue by duplicating newData null condition inside error block.  anyone please comment your opinions on this I'm happy to make a PR.

**How to reproduce the issue:**

**Versions**
npmPackages:
apollo-boost: 0.1.4 => 0.1.4
apollo-cache-inmemory: 1.2.5 => 1.2.5
apollo-client: 2.3.7 => 2.3.7
apollo-link: 1.2.2 => 1.2.2
apollo-link-batch-http: 1.2.2 => 1.2.2
apollo-link-error: 1.1.0 => 1.1.0
apollo-link-state: 0.4.1 => 0.4.1
react-apollo: 2.1.9 => 2.1.9

**Comment by hwillson** [comment]
We'd definitely be open to a PR for this @gandhiamarnadh - thanks very much!

**Comment by hwillson** [comment]
Closing for now due to inactivity. Thanks!
