### ISSUE TITLE
Codesandbox in issue template is outdated

### ISSUE THREAD

**Issue by Skaronator** [apollographql/apollo-client#3788]
I've noticed that the codesandbox link in this issue template is outdated. It still use apollo-client v1.7 with react-apollo 1.4 and React 15.6. Would be cool if someone could update it.

**How to reproduce the issue:**

If possible, please create a reproduction using https://github.com/apollographql/react-apollo-error-template and link to it here. If you prefer an in-browser way to create reproduction, try https://codesandbox.io/s/7361K9q6w

Instructions for how the issue can be reproduced by a maintainer or contributor. Be as specific as possible, and only mention what is necessary to reproduce the bug. If possible, try to isolate the exact circumstances in which the bug occurs and avoid speculation over what the cause might be.

**Comment by JacksonKearl** [comment]
Thanks for pointing this out! We've updated it to https://codesandbox.io/s/github/apollographql/react-apollo-error-template, which should track the latest `react-apollo-error-template`.
