### ISSUE TITLE
What is the difference between ApolloProvider and using ApolloClient directly

### ISSUE THREAD

**Issue by mxrguspxrt** [apollographql/apollo-client#3789]
`ApolloProvider` will enable `Query` and `Mutation` components.

`ApolloClient` is the client, that is used to commit those operations.

Why one would prefer using Query and Mutation components, instead of using:

`action dispatch -> apolloClient.query -> next action dispatch depending of result?`

I am not a big fan of DSL in components - I would rather like to hide this logic into actions.

**Comment by hwillson** [comment]
`ApolloProvider` is intended to make using Apollo Client with https://github.com/apollographql/react-apollo easier. That being said, Apollo Client was designed to be usable by itself, so if you prefer to use it another way, please by all means do so! 

Just a quick note - issues here are reserved for Apollo Client bugs. You’ll have a much better chance of getting answers to questions like this in the [Apollo Slack](https://www.apollographql.com/slack) group. Thanks!
