### ISSUE TITLE
graphql queries with type condition on nested fields: Network error cannot read property of undefined

### ISSUE THREAD

**Issue by yoduoy** [apollographql/apollo-client#3802]
I am working on the following types, where the "content" of a "Comment" is a union type:

```
type TextContent {
  text: String
}

type RichContent {
  participants: [String]
  startTime: String
}

union Content = TextContent | RichContent

type Comment {
  id: ID
  sender: String
  content: Content
}

type Review {
  id: ID
  title: String
  lastComment: Comment
}
```
In my query, I was trying to use conditional fragments on the two Content types:

```
query listOfReviews {
  reviews {
    ...reviewFields
  }
}

fragment reviewFields on Review {
  id
  title
  lastComment {
    content {
      ... on TextContent {
        text
      }
      ... on RichContent {
        participants
        startTime
      }
    }
  }
}
```
I received a runtime error where the graphql engine (we are using Apollo) seems trying to access "participants" field of "undefined", where the actual content object is:

```
{
  __typename: "TextContent:,
  text: "abc"
}
```

```
"Error: Network error: Cannot read property 'participants' of undefined
    at new ApolloError (http://dev.local/client/main-fa60928e7fee1f870d4b.js:142438:28)
    at ObservableQuery.../../../node_modules/apollo-client/core/ObservableQuery.js.ObservableQuery.currentResult (http://dev.local/client/main-fa60928e7fee1f870d4b.js:140664:24)
    at Query._this.getQueryResult (http://dev.local/client/main-fa60928e7fee1f870d4b.js:277591:59)
    at Query.../../../node_modules/react-apollo/react-apollo.browser.umd.js.Query.render (http://dev.local/client/main-fa60928e7fee1f870d4b.js:277693:36)
    at finishClassComponent (http://dev.local/client/main-fa60928e7fee1f870d4b.js:288075:33)
    at updateClassComponent (http://dev.local/client/main-fa60928e7fee1f870d4b.js:288043:12)
    at beginWork (http://dev.local/client/main-fa60928e7fee1f870d4b.js:288668:16)
    at performUnitOfWork (http://dev.local/client/main-fa60928e7fee1f870d4b.js:291500:16)
    at workLoop (http://dev.local/client/main-fa60928e7fee1f870d4b.js:291529:26)
    at renderRoot (http://dev.local/client/main-fa60928e7fee1f870d4b.js:291560:9)"
```

It looks the two types of the union Content are merged together.

My question is: is it allowed to use type conditions on nested fields in Apollo queries? Or type conditions have to be used on the top level types returned by the queries? If it's allowed, how should I fix my types/queries?

Thanks!

**Comment by yoduoy** [comment]
A little bit more details:

The "cannot read property of undefined" error was thrown at the following places in apollo-link-state/lib/index.js:

```
43                var resolverMap = resolvers[rootValue.__typename || type];
44                var resolve = resolverMap[fieldName];
```

Where rootValue.__typename is "TextContent" and fieldName is "participants". Since resolvers does not contain "TextContent" (because even if we want to define the __resolveType function in the resolvers, it should be defined for the union Content not specific types TextContent/RichContent), resolverMap is undefined, thus causing the "cannot read property participants of undefined" error.

To check why Apollo tried to access the "participant" field of type "TextContent", I debugged into the fragment matching process stopped at the following lines in graphql-anywhere/lib/async.js:

```
117  if (!execContext.fragmentMatcher(rootValue, typeCondition, contextValue)) return [3, 4];
118  	return [4, executeSelectionSet$1(fragment.selectionSet, rootValue, execContext)];
```

When debugging into fragmentMatcher, we see the following (line 64):

```
58 function graphql$1(resolver, document, rootValue, contextValue, variableValues, execOptions) {
59     if (execOptions === void 0) { execOptions = {}; }
60     var mainDefinition = apolloUtilities.getMainDefinition(document);
61     var fragments = apolloUtilities.getFragmentDefinitions(document);
62     var fragmentMap = apolloUtilities.createFragmentMap(fragments);
63     var resultMapper = execOptions.resultMapper;
64     var fragmentMatcher = execOptions.fragmentMatcher || (function () { return true; });
```

We can check that graphql is initialized from graphql-link-state/lib/index.js without passing fragmentMatcher, so the default matcher always returns true, which means the fragmentMatcher check passed and executeSelectionSet will be called recursively.

So it looks to me Apollo was not able to match the fragment for nested union types. Is this a known issue or it is because my usage is incorrect somewhere?

Advice is appreciated!

**Comment by yoduoy** [comment]
@const86 helped point out that this is due to this bug: https://github.com/apollographql/apollo-link-state/pull/258. Thanks everyone for helping!

**Comment by hwillson** [comment]
Closing as this isn't an Apollo Client issue. Thanks!
