### ISSUE TITLE
FetchMoreQueryOptions typescript definition variables?: Pick<TVariables, K>

### ISSUE THREAD

**Issue by Aron4u** [apollographql/apollo-client#3809]
I have a problem with the typescript definition for FetchMoreQueryOptions

**Intended outcome:**

It should work with optional query parameters.

**Actual outcome:**

It complains that 

```
error TS2345: Argument of type '{ variables: Variables | Variables; updateQuery: (prev: Query & Query, { fetchMoreResult }: { fet...' is not assignable to parameter of type 'FetchMoreQueryOptions<Record<string, any>, "month" | "limit" | "cursor" | "id" | "types"> & Fetch...'.
  Type '{ variables: Variables | Variables; updateQuery: (prev: Query & Query, { fetchMoreResult }: { fet...' is not assignable to type 'FetchMoreQueryOptions<Record<string, any>, "month" | "limit" | "cursor" | "id" | "types">'.
    Types of property 'variables' are incompatible.
      Type 'Variables | Variables' is not assignable to type 'Pick<Record<string, any>, "month" | "limit" | "cursor" | "id" | "types">'.
        Type 'Variables' is not assignable to type 'Pick<Record<string, any>, "month" | "limit" | "cursor" | "id" | "types">'.
          Property 'month' is optional in type 'Variables' but required in type 'Pick<Record<string, any>, "month" | "limit" | "cursor" | "id" | "types">'.
```

**How to reproduce the issue:**

Typescript defintion for the query ( generated with codegen ... all good) : 
export type Variables = {
    id: string;
    cursor?: string | null;
    limit?: number | null;
    types?: (EventType | null)[] | null;
    month?: string | null;
  };

gql defintion:
=>
 ```
query myQuery($id: ID!, $cursor: ID, $limit: Int, $types: [EventType], $month: String) {

}
```

```

getvariablesObject(params: any /* normaly some params */ ) : Variables {
      return {} as any // any so your test ...
}

fetchMoreStuff(params) {
    return this.stuffQuery.fetchMore({      
      variables: this.getvariablesObject(params),  // this should complain
 })
}
```
when I remove the variable definition ... it will work ... but
What I would like to avoid (by using the Variables definition) is, that by mistake I add a property that I don't want to add, or missspell a property ... like

```
{
      cursor: this.nextCursor,
      id: targetId,
      limit: 10,
      types,
      month,
      asd : 'asd' // this would be wrong of course
    }
```
which is one of the big points for typescript, right?

So I think the Pick<> definition is wrong. It should be optional, no?

**Versions**

// this function throws an unhandled execption .. I just copied what I got in the output ..
npx: installed 1 in 2.138s

  System:
    OS: Windows 7
  Binaries:
    Yarn: 1.9.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    apollo-angular: 1.1.2 => 1.1.2
    apollo-angular-link-http-batch: 1.1.2 => 1.1.2
    apollo-cache-inmemory: 1.2.7 => 1.2.7
    apollo-client: 2.3.8 => 2.3.8
    apollo-link: 1.2.2 => 1.2.2
    apollo-link-context: 1.0.8 => 1.0.8
    apollo-link-error: 1.1.0 => 1.1.0
    apollo-link-ws: 1.0.8 => 1.0.8
    apollo-utilities: 1.0.18 => 1.0.18

**Comment by hwillson** [comment]
This should no longer be an issue with modern versions of `apollo-client`. Thanks!
