### ISSUE TITLE
React Native - sometimes network errors are not handled which crashes the app

### ISSUE THREAD

**Issue by adamivancza** [apollographql/apollo-client#3810]
**Intended outcome:**
Network errors should always pop up on error link.

**Actual outcome:**
Network errors sometimes popping up as unhandled promise rejections even though I have set up an error link. 

![debugger](https://user-images.githubusercontent.com/19835917/44088226-acab1b36-9fc2-11e8-91a0-9609cf022306.png)

Here is my error link (I'm using apollo-boost)

`onError: ({
    graphQLErrors,
    networkError,
    response,
    operation
  }) => {
    if (__DEV__) {
      console.log('operation', operation);
    }
    const statusCode = networkError && networkError.statusCode ? networkError.statusCode : null;
    if (statusCode === 403) {
      logout();
      return;
    }
    if (networkError && __DEV__) console.log('[Network error]: ${networkError}');`

I've also catched quite a few errors by now on Bugsnag so I can pinpoint the exact location of the error:

![bugsnag](https://user-images.githubusercontent.com/19835917/44088335-066c01ee-9fc3-11e8-9fb3-08c9c9cef044.png)

**How to reproduce the issue:**
I'm not exactly sure how to reproduce this - my guess is that it is connected to refetch, but I'm not 100% sure.

**Versions**

  System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 8.9.0 - /usr/local/bin/node
    npm: 6.3.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 55.0.3
    Safari: 11.1.2
  npmPackages:
    apollo-boost: 0.1.12 => 0.1.12 
    apollo-cache-inmemory: 1.3.0-beta.6 => 1.3.0-beta.6 
    apollo-cache-persist: 0.1.1 => 0.1.1 
    react-apollo: 2.1.3 => 2.1.3

**Comment by adamivancza** [comment]
Just saw this for other errors, like when API returns error code 500:

![error_500](https://user-images.githubusercontent.com/19835917/44144013-35f148d4-a086-11e8-9458-f43981c36818.png)

**Comment by hwillson** [comment]
This should no longer be an issue with modern versions of `apollo-client`. Thanks!
