### ISSUE TITLE
Is client.cache.reset() a public function?

### ISSUE THREAD

**Issue by anthonator** [apollographql/apollo-client#3813]
Is `client.cache.reset()` part of the public API? I've seen people suggesting this as an alternative to `client.resetStore()`. I haven't seen this in any official Apollo documentation. Feel free to point me in the right direction if I missed it.

Issues mentioning `client.cache.reset()`:

https://github.com/apollographql/apollo-client/issues/2919#issuecomment-406311579
https://github.com/apollographql/apollo-client/issues/2411#issuecomment-377614576
https://github.com/apollographql/apollo-client/issues/1849#issuecomment-377614638
https://github.com/apollographql/apollo-client/issues/1552#issuecomment-377613915
https://github.com/apollographql/apollo-client/issues/1419#issuecomment-352923470
https://github.com/apollographql/apollo-client/issues/1364#issuecomment-377614098
https://github.com/apollographql/apollo-client/issues/621#issuecomment-368237337

**Comment by hwillson** [comment]
https://github.com/apollographql/apollo-client/pull/3885 adds a new `client.clearStore()` method to the public API, that will clear the store without refetching active queries. Please use this new method instead of `client.cache.reset()`. Thanks!

**Comment by anthonator** [comment]
Will this trigger the `onResetStore`?

**Comment by hwillson** [comment]
@anthonator No, as of right now it's completely separate.

**Comment by makmm** [comment]
does it refresh all components, or does the library that interacts with components have to change something for that?
