### ISSUE TITLE
the value of stale of queryResult which from cache should be true

### ISSUE THREAD

**Issue by Brooooooklyn** [apollographql/apollo-client#3815]
**How to reproduce the issue:**
```ts
const query = () => client.query({
  query, variables,
})

query().then(response => {
  console.log(response.stale) // false as expected
  return query()
})
.then(({ stale }) => {
  console.log(stale) // still false here     <--------------
})
```

**Versions**
v2.3.8

**Comment by hwillson** [comment]
Why should it be `true`? I can't see anything in your code sample that shows why the result should be considered stale. Please provide a runnable reproduction that demonstrates your concern, and I'll re-open/investigate. Thanks!
