### ISSUE TITLE
read a none existed cache via client#readQuery should return null but not throw an Error

### ISSUE THREAD

**Issue by Brooooooklyn** [apollographql/apollo-client#3816]
**How to reproduce the issue:**
```ts
client.readQuery({
  query, variables,
})
// throw error xxx is not existed in cache xxxxxx
```

**Versions**

  System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 8.11.3 - /usr/local/opt/node@8/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/opt/node@8/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Safari: 11.1.2
  npmPackages:
    apollo-cache-inmemory: ^1.2.7 => 1.2.7 
    apollo-client: ^2.3.8 => 2.3.8 
    apollo-link: ^1.2.2 => 1.2.2 
    apollo-link-http: ^1.5.4 => 1.5.4 
    apollo-link-state: ^0.4.1 => 0.4.1 
    react-apollo: ^2.1.11 => 2.1.11

**Comment by hwillson** [comment]
This is by design; if you would like to see this changed, please open a feature request over in http://github.com/apollographql/apollo-feature-requests/issues with full details explaining why you would like to see this changed. Thanks!

**Comment by Brooooooklyn** [comment]
so , how could I know whether a query is existed in cache?
if I use `client.query`, the `stale` field would be always false
if I use `client.readQuery`, it would throw an error.
