### ISSUE TITLE
[apollo-cache-inmemory] Option to "opt out" from normalization?

### ISSUE THREAD

**Issue by adjourn** [apollographql/apollo-client#3822]
Im playing around with Apollo, doing everything with it (server and local data) and it got me thinking because of all the extra work I had/have to do with local data compared to just using context.

```graphql
# this "problem" mostly applies to big objects, Im using theme and intl as an example
# note that can't use arrays because keys are important to find correct values
query ClientQuery {
    client @client {
       theme {
          # lots of nested values
          # example -> header7: { background: '#ccc', color: '#000' }
          # yeah.. I would not want to add every changeable component and CSS property to schema
       }
       intl {
          locale
          messages {
              # lots of messages, >50 for sure
              # example -> loadMore: 'Load More'
          }
       }
    }
}
```

Would it make sense to add an option to "opt out" from normalization?

E.g `theme` object gets dumped as regular JS object and query `client { theme }` would return whole object? `JSON.stringify/JSON.parse` is absolutely out of question due to performance reasons.

Few ideas how it might work:

```js
cache.writeQuery({query: CHANGELOCALE_QUERY, data, denormalized: true});
```

```graphql
query Example {
    something {
        lotsOfValues @denormalized
    }
}
```

I haven't tried it yet but one very ugly solution might be to modify cache directly.

### Why it sucks?

A lot more GraphQL code due to added fields: bigger bundle and more stuff to maintain.

If e.g locale is changed, I need to provide query to resolver with every single field, each field not included doesn't get updated. This is a maintenance and dev hell, another file to remember to update.

```graphql
query ChangeLocale {
  client @client {
    locale {
      locale
      messages {
          loadMore
          hello
          # e.g 100 more

          # oopsie, forgot to add 'checkOut', it will remain to previous locale
      }
    }
  }
}
```

```js
cache.writeQuery({query: CHANGELOCALE_QUERY, data});
```

Theme would be even worse.

---

Unrelated question: if someone used this solution, would it make sense to use fragment including every single intl message field everywhere? It would be great for developer but how's performance?

If I query `{ messages { ...AllMessages } }`, does cache take messages object and remove values not queried (good in this case) or start building a new object from 0?

**Comment by samkelleher** [comment]
Why did you close this @adjourn  - did you come up with another solution?  I've opened a ticket in feature requests that outlines the issue, I to also need to disable normalsiation.
