### ISSUE TITLE
The Default fetch policy for queries `cache-first` seems to be broken

### ISSUE THREAD

**Issue by AdelBachene** [apollographql/apollo-client#3830]
**Intended outcome:**
My code is working on apollo-client "^2.2.5" But after updating to "^2.4.0" Im having this issue.
I Was Trying to execute a graphql Query where my apollo client code looks like this

>            lHttpLink=new HttpLink({ uri: this.mAuthServerUrl } as any);
>             if (lAuthLink){
>                 lLink= lAuthLink.concat(lHttpLink);
>             }else{  
>                 lLink=lHttpLink
>             }
>             this.mAuthClient=new ApolloClient({
>                 link: lLink,
>                 cache: new InMemoryCache(),
>             });

and my query code is :

>        var queryObj:any = {
>             query : SmalaBackCom.QUERY_ACCOUNT
>         };
>         queryObj.context = this.getContext();
>         this.graphqlClient.authClient.query(
>             queryObj
>         ).then(data => {
>           console.log(data)});

QUERY_ACCOUNT = 

> query me{
>   me{
>     id, email
>   }
> }

**Actual outcome:**
data is always null eventhough I could see the result in the network tab of my browser console.
But If I change the fetch policy in my client to "no-cache" it works fine

>             this.mAuthClient=new ApolloClient({
>                 link: lLink,
>                 cache: new InMemoryCache(),
>                 defaultOptions: {
>                     query: {
>                         fetchPolicy: "no-cache"
>                     }
>                 }
>             });

**Versions**

>         "apollo-cache-inmemory": "^1.2.7",
>         "apollo-client": "^2.4.0",
>         "apollo-client-preset": "^1.0.8",
>         "apollo-link-context": "^1.0.8",
>         "apollo-link-error": "^1.1.0",
>         "apollo-link-http": "^1.5.4",

Previous working versions:

>        "apollo-cache-inmemory": "^1.1.9",
>         "apollo-client": "^2.2.5",
>         "apollo-client-preset": "^1.0.8",
>         "apollo-link-context": "^1.0.8",
>         "apollo-link-http": "^1.3.3",

**Comment by hwillson** [comment]
Any chance you put together a small runnable reproduction that shows this happening?

**Comment by AdelBachene** [comment]
@hwillson Sorry for the late reply, Actually I couldn't reproduce this in a separate project so I was running the app with `no-cache` for a while until performance became a challenge for us where this issue has been fixed after flushing my package-lock.json by accident which was committed to our repo.

I hope that sharing my old  `package-lock.json` would help so here you are some code snippets from it:

> "@types/graphql": {
            "version": "0.12.6",
            "resolved": "https://registry.npmjs.org/@types/graphql/-/graphql-0.12.6.tgz",
            "integrity": "sha512-wXAVyLfkG1UMkKOdMijVWFky39+OD/41KftzqfX1Oejd0Gm6dOIKjCihSVECg6X7PHjftxXmfOKA/d1H79ZfvQ=="
        },
        "apollo-cache": {
            "version": "1.1.15",
            "resolved": "https://registry.npmjs.org/apollo-cache/-/apollo-cache-1.1.15.tgz",
            "integrity": "sha512-sbFln2YZOuJNryMMLdmQzFN70GdEPeQqekCTwFFrNi1mYrrNdI3++mFGmDs7ecIRexZ2yrgNHlAQYCO5cuROMg==",
            "requires": {
                "apollo-utilities": "^1.0.19"
            },
            "dependencies": {
                "apollo-utilities": {
                    "version": "1.0.19",
                    "resolved": "https://registry.npmjs.org/apollo-utilities/-/apollo-utilities-1.0.19.tgz",
                    "integrity": "sha512-pyVxizjIevHFfKhtc9FLEsGHmqiK0kHx1aBdJRUXDt+X+yjoVa/fVeCEo9t0NddGximemxxrQnq6lSkbIQvDlA==",
                    "requires": {
                        "fast-json-stable-stringify": "^2.0.0"
                    }
                }
            }
        },
        "apollo-cache-inmemory": {
            "version": "1.2.8",
            "resolved": "https://registry.npmjs.org/apollo-cache-inmemory/-/apollo-cache-inmemory-1.2.8.tgz",
            "integrity": "sha512-IlzG/A8NzSGn+7R05UJO/YdOlygA06V+qlTKrmMVPLrX2usaN7b9G65LHDePaVLM4GrOctFKJ9bfdeubNZcAVQ==",
            "requires": {
                "apollo-cache": "^1.1.15",
                "apollo-utilities": "^1.0.19",
                "graphql-anywhere": "^4.1.17"
            },
            "dependencies": {
                "apollo-utilities": {
                    "version": "1.0.19",
                    "resolved": "https://registry.npmjs.org/apollo-utilities/-/apollo-utilities-1.0.19.tgz",
                    "integrity": "sha512-pyVxizjIevHFfKhtc9FLEsGHmqiK0kHx1aBdJRUXDt+X+yjoVa/fVeCEo9t0NddGximemxxrQnq6lSkbIQvDlA==",
                    "requires": {
                        "fast-json-stable-stringify": "^2.0.0"
                    }
                }
            }
        },
        "apollo-client": {
            "version": "2.4.5",
            "resolved": "https://registry.npmjs.org/apollo-client/-/apollo-client-2.4.5.tgz",
            "integrity": "sha512-nUm06EGa4TP/IY68OzmC3lTD32TqkjLOQdb69uYo+lHl8NnwebtrAw3qFtsQtTEz6ueBp/Z/HasNZng4jwafVQ==",
            "requires": {
                "@types/async": "2.0.50",
                "@types/zen-observable": "^0.8.0",
                "apollo-cache": "1.1.20",
                "apollo-link": "^1.0.0",
                "apollo-link-dedup": "^1.0.0",
                "apollo-utilities": "1.0.25",
                "symbol-observable": "^1.0.2",
                "zen-observable": "^0.8.0"
            },
            "dependencies": {
                "apollo-cache": {
                    "version": "1.1.20",
                    "resolved": "https://registry.npmjs.org/apollo-cache/-/apollo-cache-1.1.20.tgz",
                    "integrity": "sha512-+Du0/4kUSuf5PjPx0+pvgMGV12ezbHA8/hubYuqRQoy/4AWb4faa61CgJNI6cKz2mhDd9m94VTNKTX11NntwkQ==",
                    "requires": {
                        "apollo-utilities": "^1.0.25"
                    }
                },
                "apollo-utilities": {
                    "version": "1.0.25",
                    "resolved": "https://registry.npmjs.org/apollo-utilities/-/apollo-utilities-1.0.25.tgz",
                    "integrity": "sha512-AXvqkhni3Ir1ffm4SA1QzXn8k8I5BBl4PVKEyak734i4jFdp+xgfUyi2VCqF64TJlFTA/B73TRDUvO2D+tKtZg==",
                    "requires": {
                        "fast-json-stable-stringify": "^2.0.0"
                    }
                },
                "zen-observable": {
                    "version": "0.8.11",
                    "resolved": "https://registry.npmjs.org/zen-observable/-/zen-observable-0.8.11.tgz",
                    "integrity": "sha512-N3xXQVr4L61rZvGMpWe8XoCGX8vhU35dPyQ4fm5CY/KDlG0F75un14hjbckPXTDuKUY6V0dqR2giT6xN8Y4GEQ=="
                }
            }
        },
        "apollo-client-preset": {
            "version": "1.0.8",
            "resolved": "https://registry.npmjs.org/apollo-client-preset/-/apollo-client-preset-1.0.8.tgz",
            "integrity": "sha512-vRrdBfoOBkSboUmkec/zDWK9dT22GoZ2NgTKxfPXaTRh82HGDejDAblMr7BuDtZQ6zxMUiD9kghmO+3HXsHKdQ==",
            "requires": {
                "apollo-cache-inmemory": "^1.1.7",
                "apollo-client": "^2.2.2",
                "apollo-link": "^1.0.6",
                "apollo-link-http": "^1.3.1",
                "graphql-tag": "^2.4.2"
            },
            "dependencies": {
                "@types/async": {
                    "version": "2.0.47",
                    "resolved": "https://registry.npmjs.org/@types/async/-/async-2.0.47.tgz",
                    "integrity": "sha512-/mQMARXVSuGbwOFFBKA4s0qRKtOaaTgnllp3qU4sMzDVGGAroPblyd529yBALnK/WEY8nHyRGx0/RFUDmhpVmQ==",
                    "optional": true
                },
                "@types/zen-observable": {
                    "version": "0.5.4",
                    "resolved": "https://registry.npmjs.org/@types/zen-observable/-/zen-observable-0.5.4.tgz",
                    "integrity": "sha512-sW6xN96wUak4tgc89d0tbTg7QDGYhGv5hvQIS6h4mRCd8h2btiZ80loPU8cyLwsBbA4ZeQt0FjvUhJ4rNhdsGg=="
                },
                "apollo-cache-inmemory": {
                    "version": "1.1.10",
                    "resolved": "https://registry.npmjs.org/apollo-cache-inmemory/-/apollo-cache-inmemory-1.1.10.tgz",
                    "integrity": "sha512-fGwP/wn9Y0DG942FmEX2Z58f5dquqb9ERpFGhjijSt92vHudDxgoHgNbng2H7Y/pqsOo8ixgL8t8d4+uItIyVg==",
                    "requires": {
                        "apollo-cache": "^1.1.5",
                        "apollo-utilities": "^1.0.9",
                        "graphql-anywhere": "^4.1.6"
                    }
                },
                "apollo-client": {
                    "version": "2.2.6",
                    "resolved": "https://registry.npmjs.org/apollo-client/-/apollo-client-2.2.6.tgz",
                    "integrity": "sha512-yymgriabsyWmjhQDeSbFMG9+rieiUinR2uWuoCKJAm4ot6phlwioEvhTYiVJ/HLx9j+AbbQ4rKQiV5t971Yrag==",
                    "requires": {
                        "@types/async": "2.0.47",
                        "@types/zen-observable": "^0.5.3",
                        "apollo-cache": "^1.1.5",
                        "apollo-link": "^1.0.0",
                        "apollo-link-dedup": "^1.0.0",
                        "apollo-utilities": "^1.0.9",
                        "symbol-observable": "^1.0.2",
                        "zen-observable": "^0.7.0"
                    }
                },
                "apollo-link-http": {
                    "version": "1.5.3",
                    "resolved": "https://registry.npmjs.org/apollo-link-http/-/apollo-link-http-1.5.3.tgz",
                    "integrity": "sha512-t49wBXzdXpVdiqr82Lj0x6hORVVtIQQ5hLfVKjmQXiA/uv0o0Np8mAcOBZRYJvpVRHkaLvv5w/4MRbc8h5UGuQ==",
                    "requires": {
                        "apollo-link": "^1.2.1",
                        "apollo-link-http-common": "^0.2.3"
                    }
                }
            }
        },
        "apollo-link": {
            "version": "1.2.1",
            "resolved": "https://registry.npmjs.org/apollo-link/-/apollo-link-1.2.1.tgz",
            "integrity": "sha512-6Ghf+j3cQLCIvjXd2dJrLw+16HZbWbwmB1qlTc41BviB2hv+rK1nJr17Y9dWK0UD4p3i9Hfddx3tthpMKrueHg==",
            "requires": {
                "@types/node": "^9.4.6",
                "apollo-utilities": "^1.0.0",
                "zen-observable-ts": "^0.8.6"
            },
            "dependencies": {
                "@types/node": {
                    "version": "9.4.6",
                    "resolved": "https://registry.npmjs.org/@types/node/-/node-9.4.6.tgz",
                    "integrity": "sha512-CTUtLb6WqCCgp6P59QintjHWqzf4VL1uPA27bipLAPxFqrtK1gEYllePzTICGqQ8rYsCbpnsNypXjjDzGAAjEQ=="
                }
            }
        },
        "apollo-link-context": {
            "version": "1.0.8",
            "resolved": "https://registry.npmjs.org/apollo-link-context/-/apollo-link-context-1.0.8.tgz",
            "integrity": "sha512-wgDwBbWqHblf7W0DD2b80kXLtSAfvbXnsxSrli0GuF77VwxjLChijiHinW5bjurzZvP8YRMNhitmrrF5ia7NsA==",
            "requires": {
                "apollo-link": "^1.2.2"
            },
            "dependencies": {
                "apollo-link": {
                    "version": "1.2.2",
                    "resolved": "https://registry.npmjs.org/apollo-link/-/apollo-link-1.2.2.tgz",
                    "integrity": "sha512-Uk/BC09dm61DZRDSu52nGq0nFhq7mcBPTjy5EEH1eunJndtCaNXQhQz/BjkI2NdrfGI+B+i5he6YSoRBhYizdw==",
                    "requires": {
                        "@types/graphql": "0.12.6",
                        "apollo-utilities": "^1.0.0",
                        "zen-observable-ts": "^0.8.9"
                    }
                },
                "zen-observable": {
                    "version": "0.8.8",
                    "resolved": "https://registry.npmjs.org/zen-observable/-/zen-observable-0.8.8.tgz",
                    "integrity": "sha512-HnhhyNnwTFzS48nihkCZIJGsWGFcYUz+XPDlPK5W84Ifji8SksC6m7sQWOf8zdCGhzQ4tDYuMYGu5B0N1dXTtg=="
                },
                "zen-observable-ts": {
                    "version": "0.8.9",
                    "resolved": "https://registry.npmjs.org/zen-observable-ts/-/zen-observable-ts-0.8.9.tgz",
                    "integrity": "sha512-KJz2O8FxbAdAU5CSc8qZ1K2WYEJb1HxS6XDRF+hOJ1rOYcg6eTMmS9xYHCXzqZZzKw6BbXWyF4UpwSsBQnHJeA==",
                    "requires": {
                        "zen-observable": "^0.8.0"
                    }
                }
            }
        },
        "apollo-link-dedup": {
            "version": "1.0.9",
            "resolved": "https://registry.npmjs.org/apollo-link-dedup/-/apollo-link-dedup-1.0.9.tgz",
            "integrity": "sha512-RbuEKpmSHVMtoREMPh2wUFTeh65q+0XPVeqgaOP/rGEAfvLyOMvX0vT2nVaejMohoMxuUnfZwpldXaDFWnlVbg==",
            "requires": {
                "apollo-link": "^1.2.2"
            },
            "dependencies": {
                "apollo-link": {
                    "version": "1.2.2",
                    "resolved": "https://registry.npmjs.org/apollo-link/-/apollo-link-1.2.2.tgz",
                    "integrity": "sha512-Uk/BC09dm61DZRDSu52nGq0nFhq7mcBPTjy5EEH1eunJndtCaNXQhQz/BjkI2NdrfGI+B+i5he6YSoRBhYizdw==",
                    "requires": {
                        "@types/graphql": "0.12.6",
                        "apollo-utilities": "^1.0.0",
                        "zen-observable-ts": "^0.8.9"
                    }
                },
                "zen-observable": {
                    "version": "0.8.9",
                    "resolved": "https://registry.npmjs.org/zen-observable/-/zen-observable-0.8.9.tgz",
                    "integrity": "sha512-Y9kPzjGvIZ5jchSlqlCpBW3I82zBBL4z+ulXDRVA1NwsKzjt5kwAi+gOYIy0htNkfuehGZZtP5mRXHRV6TjDWw=="
                },
                "zen-observable-ts": {
                    "version": "0.8.9",
                    "resolved": "https://registry.npmjs.org/zen-observable-ts/-/zen-observable-ts-0.8.9.tgz",
                    "integrity": "sha512-KJz2O8FxbAdAU5CSc8qZ1K2WYEJb1HxS6XDRF+hOJ1rOYcg6eTMmS9xYHCXzqZZzKw6BbXWyF4UpwSsBQnHJeA==",
                    "requires": {
                        "zen-observable": "^0.8.0"
                    }
                }
            }
        },
        "apollo-link-error": {
            "version": "1.1.0",
            "resolved": "https://registry.npmjs.org/apollo-link-error/-/apollo-link-error-1.1.0.tgz",
            "integrity": "sha512-4Vu/IUn6Kn6+Fthym4iuqypCKcLdwTg3MaCvtLdaLbt9X2hNCq3y8mv6vuWIlAY51X8wKhCgYghQSOs5R/embQ==",
            "requires": {
                "apollo-link": "^1.2.2"
            },
            "dependencies": {
                "apollo-link": {
                    "version": "1.2.2",
                    "resolved": "https://registry.npmjs.org/apollo-link/-/apollo-link-1.2.2.tgz",
                    "integrity": "sha512-Uk/BC09dm61DZRDSu52nGq0nFhq7mcBPTjy5EEH1eunJndtCaNXQhQz/BjkI2NdrfGI+B+i5he6YSoRBhYizdw==",
                    "requires": {
                        "@types/graphql": "0.12.6",
                        "apollo-utilities": "^1.0.0",
                        "zen-observable-ts": "^0.8.9"
                    }
                },
                "zen-observable": {
                    "version": "0.8.9",
                    "resolved": "https://registry.npmjs.org/zen-observable/-/zen-observable-0.8.9.tgz",
                    "integrity": "sha512-Y9kPzjGvIZ5jchSlqlCpBW3I82zBBL4z+ulXDRVA1NwsKzjt5kwAi+gOYIy0htNkfuehGZZtP5mRXHRV6TjDWw=="
                },
                "zen-observable-ts": {
                    "version": "0.8.9",
                    "resolved": "https://registry.npmjs.org/zen-observable-ts/-/zen-observable-ts-0.8.9.tgz",
                    "integrity": "sha512-KJz2O8FxbAdAU5CSc8qZ1K2WYEJb1HxS6XDRF+hOJ1rOYcg6eTMmS9xYHCXzqZZzKw6BbXWyF4UpwSsBQnHJeA==",
                    "requires": {
                        "zen-observable": "^0.8.0"
                    }
                }
            }
        },
        "apollo-link-http": {
            "version": "1.5.4",
            "resolved": "https://registry.npmjs.org/apollo-link-http/-/apollo-link-http-1.5.4.tgz",
            "integrity": "sha512-e9Ng3HfnW00Mh3TI6DhNRfozmzQOtKgdi+qUAsHBOEcTP0PTAmb+9XpeyEEOueLyO0GXhB92HUCIhzrWMXgwyg==",
            "requires": {
                "apollo-link": "^1.2.2",
                "apollo-link-http-common": "^0.2.4"
            },
            "dependencies": {
                "apollo-link": {
                    "version": "1.2.2",
                    "resolved": "https://registry.npmjs.org/apollo-link/-/apollo-link-1.2.2.tgz",
                    "integrity": "sha512-Uk/BC09dm61DZRDSu52nGq0nFhq7mcBPTjy5EEH1eunJndtCaNXQhQz/BjkI2NdrfGI+B+i5he6YSoRBhYizdw==",
                    "requires": {
                        "@types/graphql": "0.12.6",
                        "apollo-utilities": "^1.0.0",
                        "zen-observable-ts": "^0.8.9"
                    }
                },
                "zen-observable": {
                    "version": "0.8.9",
                    "resolved": "https://registry.npmjs.org/zen-observable/-/zen-observable-0.8.9.tgz",
                    "integrity": "sha512-Y9kPzjGvIZ5jchSlqlCpBW3I82zBBL4z+ulXDRVA1NwsKzjt5kwAi+gOYIy0htNkfuehGZZtP5mRXHRV6TjDWw=="
                },
                "zen-observable-ts": {
                    "version": "0.8.9",
                    "resolved": "https://registry.npmjs.org/zen-observable-ts/-/zen-observable-ts-0.8.9.tgz",
                    "integrity": "sha512-KJz2O8FxbAdAU5CSc8qZ1K2WYEJb1HxS6XDRF+hOJ1rOYcg6eTMmS9xYHCXzqZZzKw6BbXWyF4UpwSsBQnHJeA==",
                    "requires": {
                        "zen-observable": "^0.8.0"
                    }
                }
            }
        },
        "apollo-link-http-common": {
            "version": "0.2.4",
            "resolved": "https://registry.npmjs.org/apollo-link-http-common/-/apollo-link-http-common-0.2.4.tgz",
            "integrity": "sha512-4j6o6WoXuSPen9xh4NBaX8/vL98X1xY2cYzUEK1F8SzvHe2oFONfxJBTekwU8hnvapcuq8Qh9Uct+gelu8T10g==",
            "requires": {
                "apollo-link": "^1.2.2"
            },
            "dependencies": {
                "apollo-link": {
                    "version": "1.2.2",
                    "resolved": "https://registry.npmjs.org/apollo-link/-/apollo-link-1.2.2.tgz",
                    "integrity": "sha512-Uk/BC09dm61DZRDSu52nGq0nFhq7mcBPTjy5EEH1eunJndtCaNXQhQz/BjkI2NdrfGI+B+i5he6YSoRBhYizdw==",
                    "requires": {
                        "@types/graphql": "0.12.6",
                        "apollo-utilities": "^1.0.0",
                        "zen-observable-ts": "^0.8.9"
                    }
                },
                "zen-observable": {
                    "version": "0.8.9",
                    "resolved": "https://registry.npmjs.org/zen-observable/-/zen-observable-0.8.9.tgz",
                    "integrity": "sha512-Y9kPzjGvIZ5jchSlqlCpBW3I82zBBL4z+ulXDRVA1NwsKzjt5kwAi+gOYIy0htNkfuehGZZtP5mRXHRV6TjDWw=="
                },
                "zen-observable-ts": {
                    "version": "0.8.9",
                    "resolved": "https://registry.npmjs.org/zen-observable-ts/-/zen-observable-ts-0.8.9.tgz",
                    "integrity": "sha512-KJz2O8FxbAdAU5CSc8qZ1K2WYEJb1HxS6XDRF+hOJ1rOYcg6eTMmS9xYHCXzqZZzKw6BbXWyF4UpwSsBQnHJeA==",
                    "requires": {
                        "zen-observable": "^0.8.0"
                    }
                }
            }
        },
        "apollo-utilities": {
            "version": "1.0.9",
            "resolved": "https://registry.npmjs.org/apollo-utilities/-/apollo-utilities-1.0.9.tgz",
            "integrity": "sha512-6j04GLQr5EM76uzLrGWehXc/uKvvKaFMDD4ru7FzlfKjNAf+g399TRneF/LMyQzkwRaM4atYyPIhIJOruNDV/A=="
        },
"graphql-anywhere": {
            "version": "4.1.17",
            "resolved": "https://registry.npmjs.org/graphql-anywhere/-/graphql-anywhere-4.1.17.tgz",
            "integrity": "sha512-g+6qc83IK+YluKLkdvyp2TymdG3eaIyhLU9a+u7qDN02O6aANELrTd0J+yq/exqDjYEm4ANN38BbO6RxS8fJ3Q==",
            "requires": {
                "apollo-utilities": "^1.0.19"
            },
            "dependencies": {
                "apollo-utilities": {
                    "version": "1.0.19",
                    "resolved": "https://registry.npmjs.org/apollo-utilities/-/apollo-utilities-1.0.19.tgz",
                    "integrity": "sha512-pyVxizjIevHFfKhtc9FLEsGHmqiK0kHx1aBdJRUXDt+X+yjoVa/fVeCEo9t0NddGximemxxrQnq6lSkbIQvDlA==",
                    "requires": {
                        "fast-json-stable-stringify": "^2.0.0"
                    }
                }
            }
        },

**Comment by danilobuerger** [comment]
Closing as no reproduction was provided in one week. Feel free to reopen if you have a minimal reproduction.
