### ISSUE TITLE
Mutation onCompleted not triggered

### ISSUE THREAD

**Issue by n3vrax** [apollographql/apollo-client#3845]
I have a Query component and nested Mutations inside
Wanted to use the onCompleted props on the mutation but it doesn't seem to trigger in this particular case.
onError and update are triggering on the mutation though.

Is anyone experiencing this?

**Comment by Orozco1993** [comment]
Need more information, please provide the code or the repo to see the problem.

**Comment by tafelito** [comment]
not sure if related to the original issue posted, but I found that the onCompleted is only triggered if is pass as a prop to the Mutation component but it can't be set as a prop to the mutation render prop. is that by design?

**Comment by abernix** [comment]
I realize it's been quite some time since you opened this, but if you haven't already figured this out, I'd recommend taking this question to the [Apollo community on Spectrum.chat](https://spectrum.chat/apollo) to discuss it further.  Thanks!
