### ISSUE TITLE
onCompleted, onError do not work

### ISSUE THREAD

**Issue by wzup** [apollographql/apollo-client#3857]
WHY do these methods exist here https://www.apollographql.com/docs/react/essentials/mutations.html#props, 
but they are absent here https://www.apollographql.com/docs/react/api/apollo-client.html#ApolloClient.mutate ??

**Intended outcome:**

Both methods get called when needed

**Actual outcome:**

None of them work.

**How to reproduce the issue:**

```javascript
this.props.client.mutate({
  mutation: Mutation,
  query: Mutation,
  refetchQueries: [{ query: Query }],
  errorPolicy: 'all',
  
  // DOESN"T WORK, NEVER GETS CALLED
  onCompleted: (res) => {
    console.log(res);
  },
  
  // DOESN"T WORK, NEVER GETS CALLED
  onError: (err) => {
    console.log(err);
  },
  optimisticResponse: (res) => {
    return {
      Foo: {
        ...res
      }
    }
  },
  update: (store, data) => {
    console.log(store, data);
  },
  variables: {
    ...variables
  }
})
    .then(res => {
      console.log(res);
    })
    .catch(err => {
      console.error(err);
    });
```

**Versions**

```
  System:
    OS: macOS High Sierra 10.13.4
  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Safari: 11.1
  npmPackages:
    apollo-boost: ^0.1.4 => 0.1.10 
    apollo-cache-inmemory: ^1.1.0 => 1.2.5 
    apollo-client: ^2.0.3 => 2.3.5 
    apollo-link: ^1.0.3 => 1.2.2 
    apollo-link-http: ^1.2.0 => 1.5.4 
    react-apollo: ^2.1.1 => 2.1.9
```

**Comment by hwillson** [comment]
The `onComplete` and `onError` props are specific to the React Apollo `<Query />` and `<Mutation />` components. They are not part of Apollo Client, which is why they aren't available when calling `client.mutate` directly. If you're interested in seeing this changed, please consider opening a feature request over in http://github.com/apollographql/apollo-feature-requests/issues. Thanks!
