### ISSUE TITLE
Rename all use-cases of apollo-boost's "ApolloClient".

### ISSUE THREAD

**Issue by Pokute** [apollographql/apollo-client#3861]
**Expected outcome:**
`import { ApolloClient } from 'apollo-boost';` works exactly the same as `import ApolloClient from 'apollo-boost'`

**Actual outcome:**
importing either `{ ApolloClient }` or `ApolloClient` as default return different classes with widely different behaviour, constructor parameters, etc.

This could be fixed by changing all documentation, tests and examples from `import ApolloClient from 'apollo-boost'` to `import ApolloBoostClient from 'apollo-boost'` and wouldn't break any existing applications.

I see no valid reason why the two instances should be named the same due to the amount of confusion it results in. As the documentation and examples are currently, many others will stumble upon this accidentally and like me can manage to waste several hours to this issue.

**Comment by hwillson** [comment]
@Pokute This was done for backwards compatibility reasons. The good news is that this will be addressed in Apollo Client 3 (we're getting rid of Apollo Boost completely, and instead providing boost like defaults with Apollo Client out of the box). This work is already underway, so I'll close this off. Thanks!

**Comment by Pokute** [comment]
I'm not sure if you understood my point since you raise backwards compability reasons. The point is that the current examples and documentation are assigning a name to the default import that clashes with an existing, different API.

The name assigned to default import is completely up to whoever uses the library so changing the assinged name for all the examples and documentation would not break any existing code. Worst case is that examples would not work straight when copypasted to existing codebases, but should still be pretty easy to catch. Since the only place where the "ApolloClient" is typically used is with a constructor, the chance of this happening for existing codebases is very slim and easy to recognise. It's not an API issue, but documentation issue.

Sure enough, cases like mine, where I just changed `import { ApolloClient } from 'apollo-client'` to `import { ApolloClient } from 'apollo-boost` and got throughly confused are not very common. Additionally the users searching for documentation on ApolloClient will mainly find documentation on 'apollo-client' -version.

**Comment by hwillson** [comment]
Yes, I completely understood it. I mentioned backwards compatibility as when Apollo Boost was built, it was decided that the default export would be for the new "boosted" Apollo Client subclass, but that a named `ApolloClient` export would still be available from the `apollo-boost` package, so anyone who installed `apollo-boost` could still get to the full-fledged version of `apollo-client`. I agree that it's confusing, and while we could go through and update the docs to use a different default export variable name when referring to boost's `ApolloClient` instance, we're going to instead go one step further and get rid of Apollo Boost completely. Thanks for the suggestion though!
