### ISSUE TITLE
subscribeToMore > updateQuery: 'previousState' is sometimes empty

### ISSUE THREAD

**Issue by kamilregulski** [apollographql/apollo-client#3864]
**Intended outcome:**
previousState should always return proper state

**Actual outcome:**
Subscription works properly few times in a row, and next time it can return empty previousState (without any error) so I see 'red screen' (React Native / Expo app) and cannot update proper node

**How to reproduce the issue:**
It is a standard subscription which most of the time works properly, but every few subscriptions not work as expected.

**Versions**
  System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 10.0.0 - /usr/local/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 6.0.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Safari: 11.1.2
  npmPackages:
    apollo-cache-inmemory: ^1.2.9 => 1.2.9
    apollo-cache-persist: ^0.1.1 => 0.1.1
    apollo-client: ^2.4.1 => 2.4.1
    apollo-link: ^1.2.2 => 1.2.2
    apollo-link-error: ^1.1.0 => 1.1.0
    apollo-link-http: ^1.5.4 => 1.5.4
    apollo-link-logger: ^1.2.3 => 1.2.3
    apollo-link-state: ^0.4.1 => 0.4.1
    apollo-link-ws: ^1.0.8 => 1.0.8
    apollo-utilities: ^1.0.20 => 1.0.20
    react-apollo: ^2.1.11 => 2.1.11

**Comment by adampilks** [comment]
Seeing this myself as well.

A sure fire way to replicate it is to create a simple component that has a `Query` component inside and uses `subscribeToMore` to update the cache.  Then replicate this component twice on a view.  1 instance of the component will correctly receive the `previousState` in the `updateQuery` callback, whereas the other one will receive an empty object for the previous state.

The error always seems to affect the first component in the render tree and the second works as expected.

**Comment by rafaelsales** [comment]
Happening here whenever I use `no-cache`

**Comment by ganeshpms** [comment]
I also facing this issue. I feel this might be because of the race condition of `watchQuery` and `subscribeToMore`.   UpdateQuery called as it received the new value before the watch query.

**Comment by intellix** [comment]
Yep, also experiencing this race condition. I'm doing something like the following:
```ts
set game(value: CrashGame) {
  this._game = value;

  if (this.queryRef) {
    this.queryRef.setVariables({ gameId: value.id });
  }
}
```

And then a subscribeToMore that looks like:
```ts
this.subscriptions.add(
  this.queryRef.subscribeToMore({
    document: createSubscription,
    updateQuery: (prev, { subscriptionData }) => {
      if (!subscriptionData.data) {
        return prev;
      }

      const node = subscriptionData.data.createBet;
      if (node.gameId !== this.game.id) {
        return prev;
      }

      const edge = {
        __typename: 'BetConnectionEdge',
        node,
      };

      return Object.assign({}, prev, {
        Bets: {
          ...prev.Bets,
          edges: [edge, ...prev.Bets.edges],
        },
      });
    },
  }),
);
```

I'm subscribing to getting more games and I pass in the top game into this component. That triggers the `set game()` so that I can have a fresh empty list of bets.

Doing a setVariables(...) triggers a HTTP call to fetch bets for this game, which is obviously empty at this point. 

If the HTTP call triggered by setVariables is slower than the Socket to receive the new bet then I'm getting the above error

**Comment by adampilks** [comment]
One quick work around is to use https://www.apollographql.com/docs/react/advanced/caching.html#readquery to reread the query to fetch the previous results instead of relying on the correct data to be passed to `updateQuery`.

**Comment by StefanFeederle** [comment]
Ran into the same issue and I think I found what's happening:
`fetchPolicy: 'no-cache'` will hit the network but wont set the cache with the queries result. When the subscription runs, previousData is then empty.
Try running you inital queries with `fetchPolicy: 'network-only'` to hit the network and then write the result to the cache.

**Comment by slikts** [comment]
I've possibly encountered this issue when trying to use `MockedProvider` with subscriptions; the `prev` argument to `updateQuery` is empty, even though it shouldn't be.

**Comment by developdeez** [comment]
any fix?

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!

**Comment by ShannonLCapper** [comment]
We are still seeing this issue on @apollo/client version 3.3.14. We're seeing it on a `subscribeToMore` for a query with the default fetch policy (`cache-first`)
