### ISSUE TITLE
GraphQLUpload support

### ISSUE THREAD

**Issue by indieocean** [apollographql/apollo-client#3879]
For people using this package and trying to upload there is no clear docs on how to do it. I spent a lot of time figuring out that this package does not support right out of the box or could not find how to enable it. I suggest adding something easy to find that explains this. I ended up setting up the client myself and adding the upload link to it to make it work. Perhaps I missed something but thats what I ended up doing after hours of debugging.

**Comment by hwillson** [comment]
@indieocean Did the [File uploads](https://www.apollographql.com/docs/guides/file-uploads.html) section of the docs not help? If there's anything specific missing there, definitely let us know.

**Comment by indieocean** [comment]
Yes they did but since apollo-boost is missing the apollo-server-upload link when you try uploading thru the upload mutation it fails. So I had to drop apollo-boost in favor of setting the client myself and adding the link explicitly. 

import { createUploadLink } from 'apollo-upload-client'

**Comment by hwillson** [comment]
Thanks for the feedback - we have a PR open that addresses this: https://github.com/apollographql/apollo/pull/206
