### ISSUE TITLE
Error: cache-and-network fetchPolicy can only be used with watchQuery

### ISSUE THREAD

**Issue by wzup** [apollographql/apollo-client#3880]
Any update on that?
https://github.com/apollographql/apollo-client/issues/3130

> Error: cache-and-network fetchPolicy can only be used with watchQuery

**Comment by roisafirorichard** [comment]
having same issue with `this.props.client.query`

**Comment by joelgetaction** [comment]
Bump.  This is a serious issue for us and is preventing us from using Apollo properly ... Can somebody on the Apollo team please take a look at this?

Your documentation for `query` clearly states that `cache-and-network` ***is*** a valid value for this method, as per https://www.apollographql.com/docs/react/api/react-apollo.html#graphql-config-options-fetchPolicy and https://www.apollographql.com/docs/react/api/apollo-client.html#ApolloClient.query .  However, your master source is clearly throwing an error here https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/ApolloClient.ts#L283

Hey @hwillson any chance we can get some help with this?  Or @peggyrayzis ?  This is pretty urgent ... :-)

Thanks!

**Comment by oxbits** [comment]
i am also having this issue, has anything changed?  is there a work around?

**Comment by zhangjing28** [comment]
same issue +1

**Comment by EwanValentine** [comment]
Same issue also +1.

**Comment by maziarz** [comment]
Same here. `network-only` is really bad for optimistic UI.

**Comment by HummingBird24** [comment]
Same issue +1

**Comment by ZikDead** [comment]
Same issue +1

**Comment by mythfish** [comment]
Same issue +1

**Comment by alexandrecanuto** [comment]
Same issue +1

**Comment by yadianf** [comment]
same issue +1 :(

**Comment by EwanValentine** [comment]
I found you can use `watchQuery`, like the error suggests. Which works similarly to `query` anyway. But it'll let you do `cache-and-network` too.

**Comment by bahaa-al-deen** [comment]
same issue

**Comment by dustinbrink** [comment]
same issue +1

**Comment by rares-lupascu** [comment]
same issue 👍  ... wtf :/

**Comment by Guiradi** [comment]
Same issue +1

**Comment by PowerKiKi** [comment]
@wzup please close this issue as it is an exact duplicate of #3130, which you mentioned yourself. The discussion should not be spread across different threads.

**Comment by kismib** [comment]
using this work for me
options: () => ({
   fetchPolicy: 'cache-and-network'
 })

**Comment by igorthurow** [comment]
Thanks @kismib! Better than use `watchQuery` for my scenario.

**Comment by tarasov-gk** [comment]
+ 1

**Comment by zhuhang-jasper** [comment]
The reason why `cache-and-network` is not accepted for `query` is explained here:
https://github.com/apollographql/apollo-client/issues/3130#issuecomment-478409066
