### ISSUE TITLE
ApolloBoost doesn't support defaultOptions

### ISSUE THREAD

**Issue by silverlight513** [apollographql/apollo-client#3900]
**Intended outcome:**
Set up default options to use for apollo-boost.

**Actual outcome:**
Warning appears indicating no support for defaultOptions.
![image](https://user-images.githubusercontent.com/4225358/45311586-7a960380-b521-11e8-89be-37b31ad86cb2.png)

**How to reproduce the issue:**
https://codesandbox.io/s/4r3x3lm9z7

Set up a basic apollo app using apollo-boost and add the default options which are documented here - https://www.apollographql.com/docs/react/api/apollo-client.html#apollo-client

**Versions**

  System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 10.8.0 - /usr/local/bin/node
    Yarn: 1.9.2 - ~/.npm-global/bin/yarn
    npm: 5.8.0 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0
    Safari: 11.1.2
  npmPackages:
    apollo-boost: ^0.1.15 => 0.1.15 
    apollo-client: ^2.3.5 => 2.4.1 
    apollo-link-schema: ^1.1.0 => 1.1.0 
    apollo-server-express: ^2.0.0 => 2.0.4 
    react-apollo: ^2.1.9 => 2.1.11

**Comment by silverlight513** [comment]
Thanks, the warning is gone with this approach. If I get some time I'd like to open a PR to fix this problem but I'm not sure when that would be.

**Comment by JoviDeCroock** [comment]
Is this feature needed? I wouldn't mind implementing it.

**Comment by robsdedude** [comment]
I wanted to change the default caching behavior as it didn't fit my needs. Thus, I needed this feature. Since my needs further evolved, I eventually switched to using the Apollo client directly.

**Comment by treyreynolds** [comment]
Can this be merged? We ran into this issue and would also like to be able to provide defaultOptions on the `ApolloClient` instance.

**Comment by dmce** [comment]
The comments above suggest you can define errorPolicy and fetchPolicy on client options for Apollo Boost, but [Configuration Options](https://www.apollographql.com/docs/react/essentials/get-started.html#configuration) doesnt suggest this is so

**Comment by robsdedude** [comment]
As far as I remember, Apollo Boost returns the fully fledged Apollo Client. Thus the attribute `client.defaultOptions = {…}` will be set on the actual Apollo Client.

**Comment by JoviDeCroock** [comment]
What is being meant is that there is no way of doing a small customization to it without doing a full transition to the `apollo-client` itself.

**Comment by dmce** [comment]
I tried the example presented by robsdedude `client.defaultOptions` which didnt seem to allow me to change errorPolicy or fetchPolicy. The docs suggest you cant change these anyway with apollo-boost.

I am confused from my own lack of understanding. This change will introduce the ability to make those small changes to errorPolicy for example without migrating to apollo-client? If that is the case doesnt robsdedude suggestion suggest it can be done now in a slightly different way?

**Comment by willisplummer** [comment]
I just ran into this issue. The work around fixed for me but I wish it were more clearly documented

**Comment by mrsimb** [comment]
Same here, this must be supported by apollo-boost

**Comment by pietmichal** [comment]
Why #3934 has been closed?

**Comment by dylanwulf** [comment]
Once apollo-client v3 is released, the apollo-boost package will go away.

**Comment by CyxouD** [comment]
It isn't available in constructor, but is available as prop:
`client.defaultOptions = {}`

**Comment by hwillson** [comment]
Apollo Boost is no longer supported. Please refer to the [Apollo Client 3.0 migration guide](https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/) for details. Thanks!
