### ISSUE TITLE
What does dollar sign $ mean in Apollo cache names?

### ISSUE THREAD

**Issue by wzup** [apollographql/apollo-client#3902]
Apollo creates some cryptic cache names which are not consistent. From where does it take dollar sign `$` in names? Here is an real live example of my Apollo cache names. 

Here there is `User:12345`. And suddenly there is a dollar signed user `$User:12345`.
Here there is `ROOT_QUERY`. And suddenly there is a dollar signed `$$ROOT_QUERY`.
What is that?

```
{
  "data": {
    "User:be2ae9d718c9": {}
  },
  "$User:be2ae9d718c9.personal": {},
  "ROOT_QUERY": {
    "Me": {
      "type": "id",
      "generated": false,
      "id": "User:be2ae9d718c9",
      "typename": "User"
    },
    "ListLanguages({\"next_token\":null})": {
      "type": "id",
      "generated": true,
      "id": "$ROOT_QUERY.ListLanguages({\"next_token\":null})",
      "typename": "_RESPONSE_ListLanguages"
    }
  },
  "$ROOT_QUERY.ListLanguages({\"next_token\":null}).items.0": {
    "lang": "en",
    "label": "bar",
    "value": "bar.",
    "__typename": "Lang"
  },
  "$ROOT_QUERY.ListLanguages({\"next_token\":null}).items.1": {
    "lang": "en",
    "label": "foo",
    "value": "foo.",
    "__typename": "Lang"
  },
  ....
}
```

**Comment by hwillson** [comment]
@wzup The `$` is an implementation detail that Apollo Client (Apollo In-Memory Cache specifically) uses internally. If you're wondering why the cache is broken out like this, the following should help:

https://blog.apollographql.com/the-concepts-of-graphql-bc68bd819be3
