### ISSUE TITLE
Apollo Javascript Client is replacing Objects' values

### ISSUE THREAD

**Issue by yeminnhtut** [apollographql/apollo-client#3903]
I was just playing around with GraphQL and I found this strange behavior. 

I have a field _id_ in my schema which is a type of _Int!_ but it is not a unique value. 

My Object in Schema

```
type Obj {
    id: Int!
    name: String!
    type: String!
}
```

And my query returns a list of objects which might have the same _id_ with different _type_. It looks something like this

`
[
  {
    id: 1, 
    name: "11", 
    type: "type_1"
  }, 
  {
    id: 1, 
    name: "22", 
    type: "type_2"
  }
]
`

But when I fetch the query with apollo-client for javascript, it returns like this

`
[
  {
    id: 1, 
    name: "22", 
    type: "type_2"
  }, 
  {
    id: 1, 
    name: "22", 
    type: "type_2"
  }
]
`

**Intended outcome:**

I believe apollo-client should return the same result as the response from GraphQL API.

**Actual outcome:**

Apollo-client replaces previous values of objects with values of latest object which has the same id as previous ones.

**How to reproduce the issue:**

CodeSandBox Link - https://codesandbox.io/s/nk824m40np

**Versions**

The version that I used in CodeSandBox is 1.7.0
The bug happens on version 2.3.5 as well

**Comment by lulzmachine** [comment]
I wouldn't be surprised if Apollo-client uses the "id" field to distinguish identity, since it's almost guaranteed to be unique.

**Comment by JacksonKearl** [comment]
Hey there, 
Sorry we haven't been able to get to this in a while. We're revamping the cache and I can't seem to get the codesandbox link to load on firefox or chrome. If this is still a problem could you resubmit an issue with an updated demo? Thanks!
