### ISSUE TITLE
client.clearStore is not a function?? How?

### ISSUE THREAD

**Issue by wzup** [apollographql/apollo-client#3904]
First, read your own docs https://www.apollographql.com/docs/react/advanced/caching.html#reset-store

> If you want to clear the store but don’t want to refetch active queries, use client.clearStore() instead of client.resetStore().

**Intended outcome:**

Clear cache

**Actual outcome:**

> this.props.client.clearStore is not a function

![screen shot 2018-09-11 at 1 15 51 pm](https://user-images.githubusercontent.com/3880497/45353929-02811980-b5c5-11e8-8562-9d9b8b09ac99.png)

**How to reproduce the issue:**

```
    this.props.client.clearStore().then( res => {
      console.log('[res]', res);
    } )
        .catch( err => {
          console.log('[err]', err);
        })
```

**Versions**
```
  System:
    OS: macOS High Sierra 10.13.4
  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Safari: 11.1
  npmPackages:
    apollo-boost: ^0.1.4 => 0.1.10 
    apollo-cache-inmemory: ^1.1.0 => 1.2.5 
    apollo-client: ^2.0.3 => 2.3.5 
    apollo-link: ^1.0.3 => 1.2.2 
    apollo-link-http: ^1.2.0 => 1.5.4 
    react-apollo: ^2.1.1 => 2.1.9 
```

**Comment by Amandeepsinghghai** [comment]
@wzup AFAICT these changes have not been pushed to npm - [apollo-client](https://www.npmjs.com/package/apollo-client) yet.

**Comment by hwillson** [comment]
@Amandeepsinghghai is correct - they haven't been deployed yet. I'm pushing a new Apollo Client version right now, so 2.4.2 will be available in a few minutes with these changes. Thanks!

**Comment by zplawecki** [comment]
it's been some time since those changes and I'm also having that problem: 
![zrzut ekranu 2019-02-19 o 13 00 29](https://user-images.githubusercontent.com/17323278/53013602-77932d80-3446-11e9-8141-0b81e93c7536.png)
react-native in ver. 0.58.3 and react-apollo 2.4.1

**Comment by hwillson** [comment]
@zplawecki it looks like you're attempting to call `resetStore` on the cache. `resetStore` is an `ApolloClient` method, not an Apollo Cache method.

**Comment by zplawecki** [comment]
@hwillson that worked, thanks!

**Comment by btroop** [comment]
@hwillson - running into the same issue with `clearStore()` not being a method on the Apollo client in 2.4.13. Was scanning source code in the source file:

https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/ApolloClient.ts

and noticed that the `resetStore` method has this binding:
```
    this.watchQuery = this.watchQuery.bind(this);
    this.query = this.query.bind(this);
    this.mutate = this.mutate.bind(this);
    this.resetStore = this.resetStore.bind(this);
    this.reFetchObservableQueries = this.reFetchObservableQueries.bind(this);
```
The `clearStore` method does not have a similar binding, so I added the `clearStore` binding to the `ApolloClient.js` file in the apollo-client package on my machine. That exposed the `clearStore` method as a prop in my Apollo Client.

**Comment by btroop** [comment]
> @hwillson - running into the same issue with `clearStore()` not being a method on the Apollo client in 2.4.13. Was scanning source code in the source file:
> 
> https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/ApolloClient.ts
> 
> and noticed that the `resetStore` method has this binding:
> 
> ```
>     this.watchQuery = this.watchQuery.bind(this);
>     this.query = this.query.bind(this);
>     this.mutate = this.mutate.bind(this);
>     this.resetStore = this.resetStore.bind(this);
>     this.reFetchObservableQueries = this.reFetchObservableQueries.bind(this);
> ```
> The `clearStore` method does not have a similar binding, so I added the `clearStore` binding to the `ApolloClient.js` file in the apollo-client package on my machine. That exposed the `clearStore` method as a prop in my Apollo Client.

Did some more digging; the `clearStore` method wasn't showing up because i was destructuring the Client object when sending in props to a react component 

```
<Apollo Consumer>
{client => ChildComponent({...props, ...client})}
</Apollo Consumer>
```

changing it to the following and I was able to call `clearStore()` without the binding.
```
<Apollo Consumer>
{client => ChildComponent({...props, client})}
</Apollo Consumer>
```
