### ISSUE TITLE
In need of a removeFragment(): to remove an item with a specific id from the cache

### ISSUE THREAD

**Issue by serle** [apollographql/apollo-client#3913]
The readFragment() and writeFragment() allows one to read and write an element to the cache. If the id is new a new item could be written into the cache. There is also a clearStore() method that clears the whole store. However there is currently no way to remove an item with a specific id. 

I need this functionality as I have an undo manager that creates and inverse operation for every UI operation. Operations modify the Apollo cache. I am currently unable to create a clean inverse as there is no way to remove a specific item form the cache

**Comment by Pruxis** [comment]
It's relatively easy to write delete with `writeQuery`.
Example:
``` js
const { todos } = cache.readQuery({ query: GET_TODOS });
cache.writeQuery({ 
   query: GET_TODOS,
   data: {
      todos: todos.filter((todo, index) => index % 2), // replace with a filter where you remove by id, ...
   }
```

**Comment by hwillson** [comment]
See also: https://www.apollographql.com/docs/react/api/cache/InMemoryCache/#evict
