### ISSUE TITLE
`readQuery`: Possible inconsistancy with documentation

### ISSUE THREAD

**Issue by jstoebel** [apollographql/apollo-client#3926]
**Intended outcome:**

Read some data from the in memory cache using `readQuery`. The snippet I used was 

```
const { allTasks } = cache.readQuery<AllTasksI>({ query: ALL_TASKS });
```

**Actual outcome:**

Got the compile error `Object is possibly 'null'.` I'm a little confused as to why `null` would ever need to be returned since, according to [this tutorial](https://www.apollographql.com/docs/react/advanced/caching.html#readquery) `readQuery` either returns the requested data or throws an error.

**How to reproduce the issue:**

call `readQuery` and attempt to read a property from the return value.
```
const { allTasks } = cache.readQuery<AllTasksI>({ query: ALL_TASKS });
```

**Versions**

```

  System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 8.9.3 - ~/.nvm/versions/node/v8.9.3/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 5.8.0 - ~/.nvm/versions/node/v8.9.3/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 62.0
    Safari: 11.1.2
  npmPackages:
    apollo-boost: ^0.1.15 => 0.1.15 
    apollo-link-context: ^1.0.8 => 1.0.8 
    react-apollo: ^2.1.11 => 2.1.11 

```

**Comment by hwillson** [comment]
This should no longer be an issue with modern versions of `apollo-client`. Thanks!
