### ISSUE TITLE
Wrong types ApolloClient#query(fetchPolicy)

### ISSUE THREAD

**Issue by bradleyayers** [apollographql/apollo-client#3933]
**Intended outcome:**

When passing`fetchPolicy="cache-and-network"` with `ApolloClient#query`, violate type check, rather than having a run-time error.

**Actual outcome:**

i.e. the follow passes type checks, but causes a run-time error 

```ts
apolloClient.query({
  query: MyQuery,
  fetchPolicy: "cache-and-network"
})
```

The error is:

> Error: cache-and-network fetchPolicy can only be used with watchQuery at ApolloClient.

**How to reproduce the issue:**

See above.

**Versions**

```
  System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 10.3.0 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.2.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Safari: 12.0
  npmPackages:
    apollo: ^1.9.2 => 1.9.2
    apollo-cache-inmemory: ^1.2.10 => 1.2.10
    apollo-client: ^2.4.2 => 2.4.2
    apollo-codegen: ^0.20.2 => 0.20.2
    apollo-link-http: ^1.5.5 => 1.5.5
    react-apollo: ^2.1.11 => 2.1.11
```

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
