### ISSUE TITLE
In this environment the sources for assign MUST be an object. This error is a performance optimization and not spec compliant.

### ISSUE THREAD

**Issue by wzup** [apollographql/apollo-client#3944]
What does this error mean?

**Intended outcome:**

I can understand and track error or warning.

**Actual outcome:**

`TypeError` with cryptic error message
```
TypeError: In this environment the sources for assign MUST be an object. This error is a performance optimization and not spec compliant.
  at Object.assign (Object.es6.js:40)
at QueryManager.fetchRequest (bundle.umd.js:1341)
at QueryManager.fetchQuery (bundle.umd.js:886)
at QueryManager.startQuery (bundle.umd.js:1231)
at ObservableQuery.setUpQuery (bundle.umd.js:420)
at ObservableQuery.onSubscribe (bundle.umd.js:389)
at bundle.umd.js:128
at new Subscription (Observable.js:179)
at ObservableQuery.subscribe (Observable.js:258)
at bundle.umd.js:160
```

**How to reproduce the issue:**

```
const observ = props.client.watchQuery({
  context: '',
  errorPolicy: 'all',
  fetchPolicy: 'network-only',
  fetchResults: true,
  metadata: '==METADATA==',
  notifyOnNetworkStatusChange: true,
  // pollInterval: null,
  query: Q_FULLNAME,
  variables: {}
});

observ.result()
      .then( res => {
        console.log('[ObservableQuery.result] res', res);
      } )
      .catch( err => {
        // ERROR is thrown here
        console.log('[ObservableQuery.result] err', err);
      } );
```

**Versions**
```

  System:
    OS: macOS High Sierra 10.13.4
  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Safari: 11.1
  npmPackages:
    apollo-boost: ^0.1.4 => 0.1.10 
    apollo-cache-inmemory: ^1.1.0 => 1.2.5 
    apollo-client: ^2.0.3 => 2.3.5 
    apollo-link: ^1.0.3 => 1.2.2 
    apollo-link-http: ^1.2.0 => 1.5.4 
    react-apollo: ^2.1.1 => 2.1.9 

```

**Comment by pl12133** [comment]
The generic error is that you have passed a non-object to your `Object.assign` polyfill and it cannot process non-objects. This error comes from an [old polyfill in `react-native`](https://github.com/facebook/react-native/commit/966bb63a80750757dc7a78d7d1f8960a2d8e25e0#diff-cb5173a6f8d88f7801f5127b94bfc330).

I speculate that your specific error is that you have passed a string value for `context`.

https://github.com/apollographql/apollo-client/blob/a42884a7dedca68a76604cd1e6cdae04f96b061b/packages/apollo-client/src/core/QueryManager.ts#L1104-L1110

You can try changing `context: ''` to `context: {}` in your options; or update `react-native` to the latest version where the polyfill is made spec compliant and passing an empty string is insignificant.

**Comment by hwillson** [comment]
https://github.com/apollographql/apollo-client/issues/3944#issuecomment-424068122 explains this well. Closing - thanks!
