### ISSUE TITLE
"Can't find field" error after mutation with `refetchQuery`

### ISSUE THREAD

**Issue by herclogon** [apollographql/apollo-client#3953]
**Intended outcome**

I'am using Angular Apollo-client, but I think it's not framework dependent issue. I have three components with `watchQuery`. The first one (C1) with `watchQuery`:
```
query blocks {
  blocks { 
    uid
    ports {
      uid
      name
    }
  }
}
```
another one (C2) with `watchQuery`:
```
query blocks {
  blocks(hidden: false) { 
    uid
    ports {
      uid
      path
    }
  }
}
```
and third one (C3) with `watchQuery`:
```
query blocks {
  blocks(hidden: true) { 
    uid
    ports {
      uid
      path
    }
  }
}
```
Each `watchQuery` in components has `fetchPolicy`:`"cache-and-network"`.
I'am using `InMemoryCache`, and put `Block` and `Port` objects in cache with custom id using `dataIdFromObject`:
```
(object) => {
  switch (object.__typename) {
    case "Block":
    case "Port":
      return `${object.__typename}:${object.uid}`;
    default:
      return defaultDataIdFromObject(object);
}
```
as a result objects in cache have ids:
```
Block:c3c789df-d799-4f29-aa0e-8b4645ae465e
Port:5f52034b-661c-42c3-9acb-fb02c75a23ff
```
After user action component 3 (C3) executes mutation which changes port list in block:
```
 this.apollo.mutate({
      mutation: gql`
        mutation portAdd() {
          portAdd() {
            // QUERY FROM COMPONENT 3
            blocks(hidden: true) { 
              uid
              ports {
                uid
                path
              }
            }
          }
        }        
      }`,
      refetchQueries: [{
        // QUERY FROM COMPONENT 2
        query:  gql`
          query blocks {
            blocks(hidden: false) { 
              uid
              ports {
                uid
                path
              }
            }
          }
        },
      }],
    }).subscribe();
```
As mentioned in documentation I'am using `refetchQueries` to update queries which I want to update, in my synthetic case it is query from component 2 (C2). I do not need to update each query cause it extremely increase code viscosity. I expect that after mutation C3 should update apollo cache and re-fetch query for C2... C1 keeps as is? It is not important about C1, in my requirement only C2 must be updated for sure.

**Actual outcome**

```
Error: Can't find field 'name' on object (Port:5f52034b-661c-42c3-9acb-fb02c75a23ff) {
  "uid": "5f52034b-661c-42c3-9acb-fb02c75a23ff",
  "path": "/tmp/port_1",
  "__typename": "Port"
```
I think it happens cause `watchQuery` from C1 track changes in Block object from cache (port was added), but mutation selection-set from C3 and `refetchQueries` selection-set for C2 do not contain field `name`. As for me I suppose if `fetchPolicy` set to `cache-and-network` C1 `watchQuery` should understand that necessary fields are missing in cache and fetch these fields from network.

**Versions**
```
npx: installed 1 in 2.62s

  System:
    OS: Linux 4.15 Ubuntu 16.04.5 LTS (Xenial Xerus)
  Binaries:
    Node: 8.11.3 - ~/project/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.9.4 - ~/.nvm/versions/node/v8.11.3/bin/yarn
    npm: 6.4.1 - ~/project/node_modules/.bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 62.0
  npmPackages:
    apollo-angular: ^1.1.0 => 1.1.0 
    apollo-angular-link-http: ^1.1.0 => 1.1.0 
    apollo-cache-inmemory: ^1.2.10 => 1.2.10 
    apollo-client: ^2.4.2 => 2.4.2 
    apollo-client-preset: ^1.0.8 => 1.0.8 
    apollo-link: ^1.2.2 => 1.2.2 
    apollo-link-error: ^1.0.9 => 1.0.9 
    apollo-link-http: ^1.5.5 => 1.5.5 
    apollo-link-schema: ^1.1.0 => 1.1.0 
    apollo-link-ws: ^1.0.8 => 1.0.8 
```

**Comment by hwillson** [comment]
This should no longer be an issue with modern versions of `apollo-client`. Thanks!
