### ISSUE TITLE
forwardRef prevent data to be load server side in child component

### ISSUE THREAD

**Issue by seb-saletes** [apollographql/apollo-client#3955]
**Intended outcome:**

Create custom HOC with React.forwardRef and load data server side using NextJs + Apollo.

**Actual outcome:**

Data are not loaded server side.

**How to reproduce the issue:**

I created a repo where I reproduced my use case: https://github.com/seb-saletes/next-apollo-forwardRef-issue
Go to pages/index.js and comment in and out the different version of the same HOC and disable javascript from your browser

I also posted the issue on NextJs repo: https://github.com/zeit/next.js/issues/5299 

**Versions**

System:
    OS: macOS 10.14
  Binaries:
    Node: 10.11.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 61.0.2
    Safari: 12.0
  npmPackages:
    apollo-boost: ^0.1.16 => 0.1.16 
    react-apollo: ^2.1.11 => 2.2.0

**Comment by michrob** [comment]
I have experienced this as well after upgrading react-cookie to >=3.0.0, as their new withCookies HOC includes forwardRef

https://github.com/reactivestack/cookies/commit/f28e0cf860486fd9a22a232936efd20767d423ed

**Comment by iquabius** [comment]
This is fixed by apollographql/react-apollo#2533. You should try upgrading react-apollo to version 2.3.1.

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-client/issues/3955#issuecomment-440436490, this issue has been resolved. Thanks!
