### ISSUE TITLE
[apollo-cache-inmemory] 1.2.x -> 1.3.x can't perform introspection queries

### ISSUE THREAD

**Issue by gpoitch** [apollographql/apollo-client#3970]
Running introspection queries like this no longer work after upgrading apollo-cache-inmemory to 1.3.x.  The queries succeed over the network but no data accessible after it runs through apollo.

```gql
{
  fooTypes: __type(name: "Foo") {
    enumValues {
      name
    }
  }
}
```
**Intended outcome:**

Data is accessible at `data.fooTypes`

**Actual outcome:**

Query data is undefined

**How to reproduce the issue:**

**Versions**

apollo-cache-inmemory 1.3.0+

**Comment by gpoitch** [comment]
Looks like 1.3.x was unpublished as the `latest` version

**Comment by benjamn** [comment]
Thanks for reporting this. Can you put together a small runnable reproduction in the form of a GitHub repository that I can clone?

**Comment by benjamn** [comment]
Please try the latest version of `apollo-cache-inmemory` (1.3.3) when you have a chance, since I believe 9d6995e407f9b8cc0fc6edbf7ea8d57af9b128ba will help with this issue:
```bash
npm install apollo-cache-inmemory@next
```

**Comment by gpoitch** [comment]
@benjamn that fixed it.
