### ISSUE TITLE
why cant i set errorPolicy on mutation ? #1847

### ISSUE THREAD

**Issue by wzup** [apollographql/apollo-client#3974]
Any answer for this?
#1847

Intended outcome:

I receive GraphQL errors

Actual outcome:

Apollo eats errors silently.

How to reproduce the issue:

I can easily see errors in AWS AppSync Queries GUI, but not in Apollo in my app.

Version

```
System:
    OS: macOS High Sierra 10.13.4
  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Safari: 11.1
  npmPackages:
    apollo-boost: ^0.1.4 => 0.1.10 
    apollo-cache-inmemory: ^1.1.0 => 1.2.5 
    apollo-client: ^2.0.3 => 2.3.5 
    apollo-link: ^1.0.3 => 1.2.2 
    apollo-link-http: ^1.2.0 => 1.5.4 
    react-apollo: ^2.1.1 => 2.1.9
```

**Comment by hwillson** [comment]
`mutate` supports [setting an `errorPolicy`](https://www.apollographql.com/docs/react/api/apollo-client/#ApolloClient.mutate). If you're still encountering issues here, please post back with a small runnable reproduction that clearly demonstrates your issue. Thanks!
