### ISSUE TITLE
cache.readQuery not working offline

### ISSUE THREAD

**Issue by dpogoda** [apollographql/apollo-client#3981]
Hello,
I get an error when I try to use cache.readQuery when I'm offline.
According to the Apollo Dev Tools the data I read previously from the server is cached successfully. 
When I'm online cache.readQuery also returns the correct result from the cache.
But when I'm offline I get the following error: 
**Can't find field <field> on object (ROOT_QUERY) undefined**

Did I miss some information that the cache cannot be read offline?
Maybe it's good to know that I'm also using apollo-cache-persist.

Thanks a lot

**Comment by stephankaag** [comment]
I ran into the same issue. I'm not using apollo-cache-persist.

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
