### ISSUE TITLE
ApolloLink related Memory Leak

### ISSUE THREAD

**Issue by ebenoist** [apollographql/apollo-client#3982]
**Intended outcome:**
Flat memory usage when using Apollo Client in a server rendered node/react application. I had originally suspected the cause was https://github.com/apollographql/apollo-client/pull/3444, but I'm still experiencing the leak after upgrading.

**Actual outcome:**
Linear increase in memory due to unfreeable instances of ApolloLink.

**How to reproduce the issue:**
```JS
export default class AppProvider extends React.Component {
  constructor(props) {
    super();

    const client = new ApolloClient({ cache: new InMemoryCache().restore(props.bootstrap) });

    this.state = {
      client,
    };
  }

  render() {
    return (
      <ApolloProvider client={this.state.client}>
        {this.props.children}
      </ApolloProvider>
    );
  }
}
```

![screen shot 2018-10-08 at 10 42 53 am](https://user-images.githubusercontent.com/1656713/46619133-f2d2f300-cae6-11e8-96e0-e97a63aa3142.png)

**Versions**
```
  System:
    OS: macOS Sierra 10.12.6
  Binaries:
    Node: 8.11.3 - ~/.nodenv/versions/8.11.3/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nodenv/versions/8.11.3/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 62.0.2
    Safari: 12.0
  npmPackages:
    react-apollo: 2.1.11 => 2.1.11
```

**Comment by mike-marcacci** [comment]
Possibly related to #2126

**Comment by mike-marcacci** [comment]
Possibly related to https://github.com/apollographql/react-apollo/issues/2126

**Comment by ebenoist** [comment]
Agreed. That seems likely.

**Comment by hwillson** [comment]
Let's track this in https://github.com/apollographql/react-apollo/issues/2126. Thanks!
