### ISSUE TITLE
httpLink.js:126 OPTIONS http://localhost:4444/graphql net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by axe-z** [apollographql/apollo-client#4004]
For some unknown reason , for every change I make in my script , the 
  "dev": "concurrently --names \"server,client\" \"npm run server --silent\" \"npm run client --silent\""

that reloads on changes, gives me the error, if I reload manually after, all is ok. 
I have a very basic setup, mostly boilerplate of the apollo getting started site. 
any idea ?

 
```
> (anonymous) | @ | httpLink.js:126
> -- | -- | --
>   | Subscription | @ | Observable.js:209
>   | subscribe | @ | Observable.js:287
>   | (anonymous) | @ | index.js:37
>   | Subscription | @ | Observable.js:209
>   | subscribe | @ | Observable.js:287
>   | (anonymous) | @ | dedupLink.js:86
>   | Subscription | @ | Observable.js:209
>   | subscribe | @ | Observable.js:287
>   | (anonymous) | @ | QueryManager.js:1044
>   | QueryManager.fetchRequest | @ | QueryManager.js:1041
>   | QueryManager.fetchQuery | @ | QueryManager.js:469
>   | QueryManager.startQuery | @ | QueryManager.js:844
>   | ObservableQuery.setUpQuery | @ | ObservableQuery.js:429
>   | ObservableQuery.onSubscribe | @ | ObservableQuery.js:385
>   | (anonymous) | @ | ObservableQuery.js:66
>   | Subscription | @ | Observable.js:209
>   | subscribe | @ | Observable.js:287
```
> 
 

<img width="461" alt="capture d ecran le 2018-10-13 a 15 55 54" src="https://user-images.githubusercontent.com/27289270/46909444-7c782b80-cf00-11e8-8e86-5a643f9b5ee1.png">

**Comment by fuchenxu2008** [comment]
I have the same issue!

**Comment by JoviDeCroock** [comment]
Isn't this because your subscription initializes quicker than your backend can restart, try implementing a `wait-port` on your frontend so your front only reloads after the backend port is available? :)

**Comment by fuchenxu2008** [comment]
> Isn't this because your subscription initializes quicker than your backend can restart, try implementing a `wait-port` on your frontend so your front only reloads after the backend port is available? :)

Thanks for answering, but why would the backend restart? It's just a apollo server waiting for query from apollo client in my react app, isn't it?

**Comment by JoviDeCroock** [comment]
Well before we investigate that, could you first check if it reloads or not?
Could be an issue that your `nodemon` is looking a level higher than supposed to or something.

**Comment by fuchenxu2008** [comment]
Wow, genius! The backend did reload on my frontend script change, why would that happen?👀

**Comment by JoviDeCroock** [comment]
Hmm, so i assume `concurrently` is used so you can use 1 docker container to spin up two instances. This means that they are in the same volume, if your nodemon is watching `/` it would reload on frontend changes. This implies you should look at your backend start script. 

Vice versa, you could try checking if frontend reloads on backend change, if not then the above will be your solution.

**Comment by fuchenxu2008** [comment]
Sorry for troubling you, I'm so stupid, I put the frontend folder inside server folder, so nodemon reloads every time my frontend change, thanks so much for answering!🤪

**Comment by hwillson** [comment]
Sounds like this has been resolved. Closing - thanks!
