### ISSUE TITLE
Can't update cache after mutate - Missing field allPost in...

### ISSUE THREAD

**Issue by rweller59** [apollographql/apollo-client#4006]
cache updated after mutation

 cache not updated. network shows mutation result

I am using AWS AppSync reading/writing server database without issues. However, I've spent many hours trying various ways to get cache updated after DB update. I've updated all packages and tried to follow apollo docs, using new mutation component.

I've also tried various configurations using the mutation function

```

export const AllPostsQuery = gql`
query AllPosts {
    allPost {
        posts {
            __typename
            id
            title
            author
            version
        }
    }
}`;
export const NewPostMutation = gql`
mutation AddPostMutation($id: ID!, $author: String!, $title: String!) {
    addPost(
        id: $id
        author: $author
        title: $title
        content: " "
        url: " "
    ) {
        __typename
        id
        author
        title
        version
    }
}`;

<Mutation mutation={NewPostMutation} 
                variables = {{ id: props.id, title: props.title, author: props.author, __typename: 'Post', version: 1 }}
                update = {(cache, { data: { addPost } }) => {
                  const { allPost } = cache.readQuery({ query: AllPostsQuery });

                  cache.writeQuery({ 
                    query: AllPostsQuery, 
                    data: { posts: allPost.posts.concat([addPost]) }
                  });
                }}
      >
        {addClick => <AddPostView onAdd={addClick} />}
      </Mutation>
```
I'm getting the following error in console. I see the updates in Apollo console cache list. The Root.Query object never gets updated until I clear cache and refresh from DB

```
Missing field allPost in {
  "posts": [
    {
      "__typename": "Post",
      "id": "2",
      "title": "A series of posts,
```

all packages updated today
  "dependencies": {
    "aws-appsync": "^1.3.5-link-effect.2",
    "aws-appsync-react": "^1.1.4",
    "aws-sdk": "^2.334.0",
    "graphql-tag": "^2.10.0",
    "react": "^16.2.0",
    "react-apollo": "^2.2.4",
    "react-dom": "^16.2.0",
    "react-scripts": "1.1.0",
    "react-table": "^6.8.6"
  },

**Comment by hwillson** [comment]
If this is still happening with a modern version of `apollo-client`, please post back with a small runnable reproduction that demonstrates the problem. Thanks!

**Comment by sebastianpatten** [comment]
I'm getting this too. Thought I followed this example https://www.apollographql.com/docs/react/essentials/mutations/#updating-the-cache pretty closely

**Comment by gevorg94** [comment]
@rweller59  I had the same issue. The way to prevent it from not updating the cache is to specify the same variables when writing to cache as when making the query.
for example when you make a query with the following params 
```
query: AllProductsQuery,
  variables: {
    limit: LIMIT,
 },
```

then in writeQuery you need to add the same variables
```
  variables: {
    limit: LIMIT,
 },
```
along with query and data.

My thoughts are that root query caches to result with the variables. So we need to specify the same variables to make it update the root query
