### ISSUE TITLE
How to log HTTP request and response with ApolloClient

### ISSUE THREAD

**Issue by onmyway133** [apollographql/apollo-client#4017]
This seems like a very simple task but I've spent quite some time searching without any mentions about this.

I want to see the outgoing request headers and params, and the responses headers and status code

I tried both ApolloClient from 'apollo-client' and 'apollo-boost' libraries, like

```js
 const client = new ApolloClient({
  uri: 'https://www.myapp.no/api/',
  request: async (operation) => {

    console.log(operation)

    operation.setContext({
      headers: {
        authorization: tokenHeader,
        'Content-Type': 'application/json'
      }
    })
  },
  onError: (error) => {
    if (error.graphQLErrors) {
      console.log('ApolloClient graphQLErrors')
      console.log(graphQLErrors)
    }
    if (error.networkError) {
      console.log('ApolloClient networkError')
      console.log(graphQLErrors)
    }
  }
})
```

The operation object only show variables and query information. How to log the actual HTTP requests and response under the hood?

By HTTP request, I want to log status code, header, body

**Versions**
npx: installed 1 in 2.09s

  System:
    OS: macOS 10.14
  Binaries:
    Node: 8.11.4 - ~/.nodenv/versions/8.11.4/bin/node
    npm: 6.4.1 - ~/.nodenv/versions/8.11.4/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 62.0.3
    Safari: 12.0
  npmPackages:
    apollo-boost: ^0.1.16 => 0.1.16

**Comment by rosskevin** [comment]
I'm also interested - trying to debug app latency and logging query response timing vs render would be helpful.

**Comment by mkovrigovich** [comment]
struggled with the same issue, especially due debug of server-side-rendering + 3rd party api,
ended up by inserting  
`console.log(chosenURI, options)`
into node_modules/apollo-link-http/lib/httpLink.js near the `fetcher(chosenURI, options)` call
and now it provided method/headers/body

thats was match better than simple errors like
`Error: Network error: Response not successful: Received status code 500
    at new ApolloError (webpack-internal:///./node_modules/apollo-client/errors/ApolloError.js:46:28)`

would be better to have something more clear

**Comment by onmyway133** [comment]
I use ApolloClient mostly for its caching, which does not work either. I stop using this library.

**Comment by musemind** [comment]
I ended up tuning the `fetch` method to log at least the requests:
```
const DEBUG = true

const httpLink = new HttpLink({
  uri: GRAPHQL_URL,
  fetch: (...pl) => {
    if (!DEBUG) return fetch(...pl)
    const [_, options] = pl
    const body = JSON.parse(options.body)
    console.log(`📡${body.operationName || ''}\n${body.query}`, body.variables)
    return fetch(...pl)
  }
})```

**Comment by lasseborly** [comment]
To anyone else ending up here on this issue wanting to log the response.

```javascript
  const responseLogger = new ApolloLink((operation, forward) => {
    return forward(operation).map(result => {
      console.info(operation.getContext().response.headers)
      return result
    })
  })
```

Then insert the `responseLogger` in your `ApolloLink.from` chain.

```javascript
new ApolloClient({
  ...
  link: ApolloLink.from([
    responseLogger,
    ...
  ])
})
```

**Comment by flieks** [comment]
@lasseborly this only logs the response and not the request body.
I think @musemind way is the only way. I just wonder which fetch function to use

**Comment by HaNdTriX** [comment]
I just created a custom middleware for that:

```js
import { ApolloLink } from 'apollo-link';

const logLink = new ApolloLink((operation, forward) => {
  console.time(operation.operationName);
  return forward(operation).map(result => {
    console.timeEnd(operation.operationName);
    return result;
  });
});

export default logLink;
```

**Comment by mliq** [comment]
For those who want all the info and not just the time, slight modification to @HaNdTriX post:

```
import { ApolloLink } from '@apollo/client';

const logLink = new ApolloLink((operation, forward) => {
    console.info('request', operation.getContext());
    return forward(operation).map((result) => {
        console.info('response', operation.getContext());
        return result;
    });
});

export default logLink;
```

Also, in Apollo client init:

```
const linkConfig = [];

linkConfig.push(logLink);

return new ApolloClient({
        ...cache, etc.
        link: ApolloLink.from(linkConfig),
    });
```

**Comment by Axiol** [comment]
@mliq Could you elaborate? I tried to implement it like that

```
export const client = new ApolloClient({
  link: ApolloLink.from(linkConfig),
  uri: urls[process.env.NODE_ENV],
  request: (op) => {
    let accessToken = "";
    if (process.browser) accessToken = localStorage.accessToken || "";

    op.setContext({
      headers: {
        authorization: accessToken,
      },
    });
  },
  onError: ({ graphQLErrors, networkError }) => {
    if (graphQLErrors)
      graphQLErrors.map(({ message, locations, path, extensions }) => {
        console.log('*** ERROR GraphQL START ***');
        //...
      });

    if (networkError) {
      console.log('*** ERROR GraphQL (networkError) START ***');
      //...
    }
  },
});
```

But when I load a page I have this log `ApolloBoost was initialized with unsupported options: link` and no other log. Did I miss something?

**Comment by nareshopoyi** [comment]
const httpLink = new HttpLink({
  uri: Constants.manifest.extra.BACKEND_GRAPHQL,
  fetch: async (...pl) => {
    const [_, options] = pl;
    const body = JSON.parse(options.body);
    console.log(`📡${body.operationName || ""}\n${body.query}`, body.variables);
    const res = await fetch(...pl);
    console.log("apollo client res: ", await res.json());
    return fetch(...pl);
  },
});

**Comment by wizofaus** [comment]
> ```js
> link: ApolloLink.from([
>     responseLogger,
>     ...
>   ])
> ```

I found you had to use `result.data` if you wanted to log out the actual body of the response.

**Comment by LinusU** [comment]
If someone wants something that's easy to copy and paste in when debugging, this is what I used:

```typescript
async function loggingFetch (input: RequestInfo, init?: RequestInit): Promise<Response> {
  const body = JSON.parse(init?.body ?? '{}')

  const start = Date.now()
  console.log(`${new Date().toISOString().slice(-13)} 📡 Sending ${body.operationName} request`)
  const response = await fetch(input, init)
  console.log(`${new Date().toISOString().slice(-13)} 📡 Received ${body.operationName} response in ${Date.now() - start}ms`)

  return {
    ...response,

    async text () {
      const start = Date.now()
      const result = await response.text()
      console.log(`${new Date().toISOString().slice(-13)} ⚙️  Read ${body.operationName} response body in ${Date.now() - start}ms (${result.length} bytes)`)
      return result
    }
  }
}

// ...

new HttpLink({ fetch: loggingFetch, uri: GRAPHQL_API_ENDPOINT })
```

**Comment by dep** [comment]
My amendments to also log the request and response objects themselves

```javascript
async function loggingFetch(
  input: RequestInfo,
  init?: RequestInit
): Promise<Response> {
  const body = JSON.parse(init?.body ?? "{}");

  const start = Date.now();
  console.log(
    `${new Date().toISOString().slice(-13)} 📡 Sending ${
      body.operationName
    }\nrequest: ${body.query}\nWith variables: ${JSON.stringify(
      body.variables
    )}`
  );
  const response = await fetch(input, init);
  console.log(
    `${new Date().toISOString().slice(-13)} 📡 Received ${
      body.operationName
    } response in ${Date.now() - start}ms`
  );

  return {
    ...response,

    async text() {
      const start = Date.now();
      const result = await response.text();
      console.log(JSON.parse(result));
      console.log(
        `${new Date().toISOString().slice(-13)} ⚙️ in ${
          Date.now() - start
        }ms (${result.length} bytes)`
      );
      return result;
    },
  };
}
```
