### ISSUE TITLE
Apollo-boost configuration does not store/persist the cookies

### ISSUE THREAD

**Issue by wooolfgang** [apollographql/apollo-client#4018]
Using apollo-boost my cookies are not stored/persisted, currently using apollo-link as instead. The code below does not save cookies

```
import ApolloBoostClient from "apollo-boost";
const client = new ApolloBoostClient({
  fetchOptions: {
    credentials: 'include',
  },
  uri: "http://localhost:4000/"
});
```

While these do.

```
import { ApolloClient } from 'apollo-client'
const client = new ApolloClient({
  link: createHttpLink({
    uri: "http://localhost:4000",
    credentials: "include"
  }),
  cache: new InMemoryCache()
})
```

Versions used:

```
"apollo-boost": "^0.1.16",
"apollo-cache-inmemory": "^1.3.5",
"apollo-client": "^2.4.2",
"apollo-link-http": "^1.5.5",
```

**Comment by pl12133** [comment]
It appears you are experiencing https://github.com/apollographql/apollo-client/issues/3265.

Please upgrade to [`apollo-boost@0.1.8`](https://github.com/apollographql/apollo-client/blob/master/CHANGELOG.md#apollo-boost-018) and see if that resolves your issue.

**Comment by wooolfgang** [comment]
That's strange, I tested it now with apollo-boost@0.1.16 and it's working. Don't know the variables that changed, but I spent a whole afternoon debugging this days ago. Closing this issue, thanks 👍

**Comment by captDaylight** [comment]
I'm on apollo-boost@0.1.20 and having the original problem above. The only way I found around this was from switching from:
```
const client = new ApolloBoostClient({
  fetchOptions: { credentials: 'include' },
  uri: 'http://localhost:4000',
});
```
to 
```
const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: new HttpLink({
    credentials: 'include',
    uri: 'http://localhost:4000',
  }),
});
```
Everything else about my setup remained the same and it immediately worked with this one change. I grabbed the second snippet from #3265
