### ISSUE TITLE
How Apollo store cache exactly works?

### ISSUE THREAD

**Issue by mxrguspxrt** [apollographql/apollo-client#4023]
We have query 

```
  userData {
    id
    profileData {
      id
      name
    }
    moneyData {
      id
      currency
      amount
    }
  }
```

If profileData is loaded by component1 and moneyData is loaded by component2 with following queries:

First component1 loads:

```
  userData {
    id
    profileData {
      id
      name
    }
  }
```

Then a second component2 loads:

```
  userData {
    id
    moneyData {
      id
      currency
      amount
    }
  }
```

Expected result 
----------------

Both components have their data.

Real result
-----------

profileData for component1 will be null.

Is this normal behaviour? What I am doing wrong?

**Comment by hwillson** [comment]
Yes this is normal behavior, but it's definitely unfortunate. `apollo-client` 2.6.0 helps address this with the help of the `returnPartialData` option, and PR https://github.com/apollographql/apollo-client/pull/4743 helps explain the issue (and fix). We'll be revisiting this in a future (breaking) version of Apollo Client.
