### ISSUE TITLE
An error occurs when you do multiple queries and in subsequent queries use the value from the first query.

### ISSUE THREAD

**Issue by Erbolking** [apollographql/apollo-client#4040]
**Intended outcome:**

Hi there,
I'm using apollo-client alongside with vue-apollo.

An error occurs when you do multiple queries and in subsequent queries (in variables) use the value from the first query.

Step to reproduce:

1. Do a query with a variable
2. Change the variable value to something
3. Return the variable value to the initial value

You will see an error like:
`"TypeError: Invalid property descriptor. Cannot both specify accessors and a value or writable attribute, #<Object>"`

This error only appers in "**apollo-utilities": "1.0.16**",

https://codesandbox.io/s/436n4pnow7

**Actual outcome:**

There shouldn't be any errors

**How to reproduce the issue:**

Please open following link:
https://codesandbox.io/s/436n4pnow7

enter "3" into text box,
then type "2" (the first value)
and you will see an error in the console

**Versions**

 System:
    OS: macOS High Sierra 10.13.4
  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.67
    Safari: 11.1
  npmPackages:
    apollo-cache-inmemory: 1.3.6 => 1.3.6 
    apollo-client: 2.4.3 - latest => 2.4.3 
    apollo-link: 1.2.3 => 1.2.3 
    apollo-link-http: 1.5.5 => 1.5.5 
    apollo-utilities: 1.0.16 => 1.0.16 
    vue-apollo: 3.0.0-beta.25 => 3.0.0-beta.25

**Comment by GlennMatthys** [comment]
#4034

**Comment by francoisromain** [comment]
Same thing here. I've seen #4034, updated apollo utilities to 1.0.23, but still have this error.

**Comment by mpecro** [comment]
Same

**Comment by AlexanderYW** [comment]
Same as well, tried forcing it to a lower version, but with no luck, anyone knows how to do this?, just as a temporary workaround for this

**Comment by JasonLi914** [comment]
For me, I was able to put in a resolution for `apollo-utilities` version 1.0.21 to get it working. I believe https://github.com/apollographql/apollo-client/pull/4052 addresses this issue?

**Comment by ankit1412** [comment]
Unfortunately, downgrading the package version doesn't help me. Still the same error. I've tried all the versions from 1.0.17 to 1.0.23

**Comment by francoisromain** [comment]
rolling back to apollo-cache-inmemory: 1.3.5  and apollo-client 2.4.2 don't fix the problem. @benjamn do you know how to fix temporary? Thank you

**Comment by NicoAiko** [comment]
@francoisromain Try `npm i apollo-utilities@latest`
It should overwrite the version that was installed by apollo-client.

**Comment by francoisromain** [comment]
@NicoAiko I tried taht [already](https://github.com/apollographql/apollo-client/issues/4040#issuecomment-432707521), but it didn't fix the bug.

**Comment by Akryum** [comment]
For vue-cli, setting a yarn resolution `"apollo-utilities": "1.0.21"` worked. Version `1.0.23` still has the issue.

**Comment by cotillion** [comment]
With NPM I got a downgrade to work after installing:
apollo-client@2.4.2
apollo-cache@1.1.17
apollo-cache-inmemory@1.3.5
apollo-utilities@1.0.21

**Comment by ankit1412** [comment]
Thanks @cotillion. This works as a quick fix.

**Comment by mpecro** [comment]
@cotillion you save my life

**Comment by benjamn** [comment]
I believe this is fixed by `apollo-utilities@1.0.24` (which corresponds to `apollo-client@2.4.4`), as demonstrated by this updated CodeSandbox repro: https://codesandbox.io/s/71xnmqok51
