### ISSUE TITLE
Type definition of networkError aren't engouh

### ISSUE THREAD

**Issue by vwxyutarooo** [apollographql/apollo-client#4057]
**Intended outcome:**

With TypeScript and in SSR, Reference `networkError.statusCode` should be acceptable. Currently, Include these interfaces is actually intended.

- [ServerError](https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-http-common/src/index.ts#L14)
- [ServerParseError](https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-http-common/src/index.ts#L21)
- [ClientParseError](https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-http-common/src/index.ts#L27)

**Actual outcome:**

If I try to reference statusCode like this `error.networkError.statusCode`, This type error will appeared `2339: Property 'statuscode' does not exist on type Error` because expected type definitions are missing [here](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/errors/ApolloError.ts#L35).

**How to reproduce the issue:**

 My use case is like this.

```ts
import * as React from 'react';
import { GraphqlQueryControls } from 'react-apollo';

interface Props {
  ...
  error: GraphqlQueryControls['error'] // Same as ApolloError https://github.com/apollographql/react-apollo/blob/219b002fc1c7a7cd90179d263e4f5a64c8d1d3eb/src/types.ts#L51;
}

const SampleComponent: React.SFC<Props> = ({
  error,
}) => {
  if (error) {
    return <ErrorComponent code={error.networkError.statusCode} />;
  }

  return(<div />); // Component fro case in success
}
```

Or like these issues

- https://github.com/apollographql/apollo-link/issues/300
- https://github.com/apollographql/apollo-link/issues/536

**Versions**

```
  System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 61.0.2
    Safari: 12.0
  npmPackages:
    apollo-boost: 0.1.17 => 0.1.17 
    react-apollo: 2.2.4 => 2.2.4 
```

**Comment by derekstavis** [comment]
Bumping this. I have tried to override but it's not possible:

```ts
declare module "apollo-client" {
  class NetworkError implements Error {
    name: "NetworkError";
    message: string;
    response: Response;
    result: Object;
    statusCode:
      | 400
      | 401
      | 402
      | 403
      | 404
      | 405
      | 406
      | 407
      | 408
      | 409
      | 410
      | 411
      | 412
      | 413
      | 414
      | 415
      | 416
      | 417
      | 500
      | 501
      | 502
      | 503
      | 504
      | 505;
  }

  export class ApolloError extends Error {
    public networkError: NetworkError | null;
  }
```

This  gives the error `Subsequent property declarations must have the same type. Property 'networkError' must be of type 'Error', but here has type 'NetworkError'`.

**Comment by mrkrlli** [comment]
For anyone still looking to access `statusCode` in `networkError`: https://github.com/apollographql/apollo-link/issues/300#issuecomment-518445337

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
