### ISSUE TITLE
How to retrive or recursevely get all records usign cursor-based pagination?

### ISSUE THREAD

**Issue by desmond-phonegap** [apollographql/apollo-client#4075]
My dashboard application is having 55,000 records. I user AWS Appsync to query from dynamoDB. I use cursor-base pagination since dynamodb cant retrive all records at once due to data size for all 55k records.

I have implemented PaginatedQuery correctly in my react client using batches of 1000 records. Initally when i querey I do get the items and nextToken. But when loading my data in the dashboard i should show
all 55k records.

**How to retrive or recursevely get all records usign cursor-based pagination?**

bellow is the cord.
```
graphql(VehicleListPaginatedQuery, {
    options: {
      fetchPolicy: 'cache-and-network',
      variables: {
        nextToken: null
      }
    },
    props: ({ data: { error, loading, ListPaginatedVehicles, fetchMore } }) => {
      console.log('data in props ', error, loading, ListPaginatedVehicles, fetchMore);
      if (loading) return { isLoading: true };
      if (error) return { hasErrors: true };
      this.FetchMore = fetchMore;
      return {
        vehicles: ListPaginatedVehicles && ListPaginatedVehicles.items,
        nextToken: ListPaginatedVehicles && ListPaginatedVehicles.nextToken,
        isLoading: loading,
        fetchMore: (nextToken) => {
          console.log('next token before fetch more ', nextToken);
          return fetchMore({
            query: paginatedQuery,
            variables: {
              nextToken
            },
            updateQuery: (prev, { fetchMoreResult }) => {
              console.log('update query ', prev, fetchMoreResult)
              const newVehicles = fetchMoreResult.ListPaginatedVehicles.items;
              const oldVehicles = prev.ListPaginatedVehicles.items;
              return {
                ListPaginatedVehicles: {
                  items: [...oldVehicles, ...newVehicles],
                  nextToken: fetchMoreResult.ListPaginatedVehicles.nextToken
                }
              }
            }
          });
        }
      }
    }      
  })
```

Now I need to call the fetchMore method which is attached to the props. I am not sure how to call this fetchMore as long as there is no value for nextToken. The final record from the query result will have null value.?

Please help me . The system is in production without dashboard.

**Comment by danilobuerger** [comment]
Issues here are reserved for bugs, but one of the following resources should help:

* Apollo's Slack: https://www.apollographql.com/slack
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests
