### ISSUE TITLE
the refetch situation 

### ISSUE THREAD

**Issue by axe-z** [apollographql/apollo-client#4088]
I do like apollo client , used it in my last 3 projects, 
yet the refetching part of it is a little insane. 

The cache handling should be alot easier, less code
I tend to skip the cache, it's that bad...   fetchPolicy="network-only"

so much extra work when it should be the best asset , it's not. 
we should be able to 
refetchImportedQueries={true}

**Comment by danilobuerger** [comment]
Closing as:
> Feature requests and non-bug related discussions are no longer managed in this repo. Feature requests should be opened in https://github.com/apollographql/apollo-feature-requests.
