### ISSUE TITLE
Use of Subscriptions with Apollo Boost

### ISSUE THREAD

**Issue by developdeez** [apollographql/apollo-client#4093]
Hi I would like to use Subscriptions with Apollo Boost. Currently there seems to be no way to do this.

**Comment by joe-re** [comment]
@developdeez 
Hi, it seems like they don't have any plans to include apollo-link-ws in Apollo Boost.
ref: https://github.com/apollographql/apollo-client/issues/3117

So at least for now, you should setup ApolloClient manually without Apollo Boost.
ref: https://www.apollographql.com/docs/react/advanced/boost-migration.html

@hwillson 
Development plan is still not changed, right?
In my opinition, I feel it's very usefull if we can setup websocket via ApolloBoost..

**Comment by developdeez** [comment]
@joe-re I saw that tutorial. Trouble is when I switch to this method I get cors errors (even though I dont have cors on my test server). 
Boost must have been doing something for me on the backend.

**Comment by joe-re** [comment]
@developdeez 
If you wanna send request different origin server on your client, you set to allow that origin on server side. That is not client side.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin

If it's same origin and you use some cookies, you probably missed to set credentials to `same-origin`.
ref: https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials

ApolloBoost set `same-origin` as default.
https://github.com/apollographql/apollo-client/blob/master/packages/apollo-boost/src/index.ts#L147

**Comment by danilobuerger** [comment]
Closing as
> Feature requests and non-bug related discussions are no longer managed in this repo. Feature requests should be opened in https://github.com/apollographql/apollo-feature-requests.
