### ISSUE TITLE
ApolloProvider store

### ISSUE THREAD

**Issue by developdeez** [apollographql/apollo-client#4094]
There doesn't appear to be a built in way to have store in ApolloProvider.

I've had to use React-redux to compensate.
https://github.com/apollographql/react-apollo/issues/1360

**Comment by CarloPalinckx** [comment]
The newer versions of apollo-client no longer use redux as the caching layer. Are you by change migrating from a 1.x version? If so, have a look [here](https://www.apollographql.com/docs/react/recipes/2.0-migration.html#redux)

Apollo does have a "built-in" solution comparable to redux which is called [apollo-link-state](https://www.apollographql.com/docs/link/links/state.html)

**Comment by developdeez** [comment]
Im using 2.0. I'll give apollo link state a try. Thanks

**Comment by CarloPalinckx** [comment]
Hey @developdeez, if this is no longer an issue. Would you be so kind to close this issue? :)

**Comment by danilobuerger** [comment]
Closing since there is nothing to be done here.
