### ISSUE TITLE
cloneDeep is slow with lots of data

### ISSUE THREAD

**Issue by fnberta** [apollographql/apollo-client#4097]
Starting with `apollo-client:2.4.3` (which includes `apollo-utilities:1.0.22`), I noticed a severe downgrade in performance in applications that deal with a lot of data. Profiling them showed that a lot of time is spent in the cloneDeep function. Reverting to `apollo-client:2.4.2` and `apollo-utilities:1.0.21` solves the problem, so it seems like the implementation of cloneDeep introduced in #4032 is less efficient than the previous one.

**Comment by benjamn** [comment]
You’re right about #4032, but this has been fixed since `apollo-utilities@1.0.24`: https://github.com/apollographql/apollo-client/pull/4052

**Comment by fnberta** [comment]
Well I tried 1.0.24 as well. While the experience was better, it is still way slower than 1.0.22. The applications I tested with and run with 1.0.22 perform sluggish with 1.0.24. I'm happy to provide you with some profiling numbers if needed.

**Comment by fnberta** [comment]
As promised, some not very scientific data. I just used an application of mine that consumes a quite big amount of data and triggered constants re-reads from the cache for 10 seconds. First image is with react-client 2.4.2 and apollo-utilities 1.0.21 and the second with the latest react-client 2.4.5 and apollo-utilities 1.0.25.
![1 0 21](https://user-images.githubusercontent.com/9258694/48186401-2d26ee80-e338-11e8-87a0-7d0ac707476f.png)
![1 0 25](https://user-images.githubusercontent.com/9258694/48186405-2ef0b200-e338-11e8-92ea-ed074150a1f5.png)
As you can see, in the first one, cloneDeep doesn't even show up in the the top time consuming functions when profiling. In the second though, it's at the very top.

Hence, I would suggest to re-open this issue.

**Comment by fnberta** [comment]
@benjamn any chance you would consider re-opening this issue? If yes, I will try provide a re-producable example project.

**Comment by abenhamdine** [comment]
@fnberta I suggest you to open a new issue
