### ISSUE TITLE
I've got 3392 users that I get back as a result of a mutation and my browser hangs up for couple of minutes

### ISSUE THREAD

**Issue by capaj** [apollographql/apollo-client#4108]
so I am doing a mutation and getting back 3392 object types in the response.

![image](https://user-images.githubusercontent.com/1305378/48131921-feeed380-e291-11e8-806a-bf41e7deb197.png)

Apolloc in memory cache is doing some nasty stuff, because my browser hangs up for couple of minutes and eats ton of memory.
I was able to profile it-here's the result:

[Profile-20181107T130658.zip](https://github.com/apollographql/apollo-client/files/2557370/Profile-20181107T130658.zip)

Most of the work seems to be happening in 
![image](https://user-images.githubusercontent.com/1305378/48132028-69a00f00-e292-11e8-8523-3691d4222fd1.png)

If I you'd like I can provide you a sample repo with a GQL server and a client. It will take me like an hour to set up, but if it's going to help you I would do it.

My deps:
```
    "apollo-cache-inmemory": "^1.3.8",
    "apollo-client": "^2.4.5",
    "apollo-link": "^1.2.3",
    "apollo-link-batch-http": "^1.2.3",
    "apollo-link-context": "^1.0.9",
    "apollo-link-error": "^1.1.1",
    "apollo-link-http": "^1.5.5",
```

the query I am doing:
```ts
const importUsersMutation = gql`
  mutation importUsers(
    $usersToImport: [UserModelImportInput!]!
    $overwriteFields: Boolean!
    $group: String
  ) {
    organisation {
      importUsers(
        usersToImport: $usersToImport
        overwriteFields: $overwriteFields
        group: $group
      ) {
        existingUsers {
          email
        }
        createdUsers {
          email
        }
      }
    }
  }
`
```

**Comment by capaj** [comment]
@n1ru4l I know this is not going to be easy to hunt down, but IMHO I've provided enough clues to start digging.

**Comment by hwillson** [comment]
This should no longer be an issue with current versions of `apollo-client`. Thanks!

**Comment by capaj** [comment]
@hwillson will try that out again in our app with apollo-client 2.6.3 or later. Thanks for the info.
