### ISSUE TITLE
Data is Null in query

### ISSUE THREAD

**Issue by japrogramer** [apollographql/apollo-client#4111]
**Intended outcome:**
I expected data to be something even if loading or an error occoured

**Actual outcome:**
data seems to be null

**How to reproduce the issue:**
```
<Query
query={EmailFromTokenQuery}
variables={{ token: context.token }}
skip={ready}
>
{({ data }) => {
  if (data == null) return null;
  if (data.loading) return null;
  if (data.error) return `Error!: ${data.error}`;
  if (data.invitationByToken && !ready){
    const set_email = context.Change('email');
    this.setState({ready: true},
    () => set_email({target: {value: data.invitationByToken.invitee}})
    );
  }
  return null;
}}
</Query>


```

**Versions**

  System:
    OS: Linux 4.18 Arch Linux undefined
  Binaries:
    Node: 8.11.2 - ~/.nvm/versions/node/v8.11.2/bin/node
    Yarn: 1.7.0 - ~/.nvm/versions/node/v8.11.2/bin/yarn
    npm: 3.10.10 - ~/Code/work/sixnexus/frontclient/node_modules/.bin/npm
  Browsers:
    Firefox: 63.0.1
  npmPackages:
    apollo-boost: ^0.1.10 => 0.1.20 
    apollo-link-ws: ^1.0.8 => 1.0.9 
    react-apollo: ^2.1.9 => 2.2.4

**Comment by OurMajesty** [comment]
It was fixed in `react-apollo`, but was reverted because of Typescript issues.  
https://github.com/apollographql/react-apollo/pull/1983

**Comment by hwillson** [comment]
This should no longer be an issue using current versions of `apollo-client` / `react-apollo`. Thanks!
