### ISSUE TITLE
Webpack issue when using apollo-boost:  

### ISSUE THREAD

**Issue by ahsanshah** [apollographql/apollo-client#4113]
**Intended outcome:**

Expected to be able to use apollo-boost with webpack 
**Actual outcome:**

Webpack build fails with following:

ERROR in ./node_modules/apollo-link-http-common/lib/index.js
Module not found: Error: Can't resolve 'imports' in '/flask/node_modules/apollo-link-http-common/lib'
@ ./node_modules/apollo-link-http-common/lib/index.js 1:0-65
@ ./node_modules/apollo-link-http/lib/httpLink.js
@ ./node_modules/apollo-link-http/lib/index.js
@ ./node_modules/apollo-boost/lib/index.js
@ ./frontend/app/components/SidebySideMultiSelect/index.js
@ ./frontend/app/components/TabPage/index.js
@ ./frontend/app/site/pages/Demand/Demand.js
@ ./frontend/app/site/pages/Demand/index.js
@ ./frontend/app/site/pages/index.js
@ ./frontend/app/routes.js
@ ./frontend/app/components/App.js
@ ./frontend/app/index.js

**How to reproduce the issue:**

**Versions**
    "apollo-boost": "^0.1.20",
    "graphql": "^0.11.7",
    "graphql-tag": "^2.5.0",
    "react-apollo": "^2.0.0"

**Comment by hwillson** [comment]
This should no longer be an issue with current versions of `apollo-boost`. Thanks!
