### ISSUE TITLE
related guides docs return 404

### ISSUE THREAD

**Issue by paradite** [apollographql/apollo-client#4133]
**Intended outcome:**

Links on docs page do not return 404.

**Actual outcome:**

Links on docs page return 404:

https://www.apollographql.com/docs/react/

Under the `RELATED GUIDES` section, the following lines return 404:

- State Management
- Testing React Components
- Schema Design

**How to reproduce the issue:**

- Visit https://www.apollographql.com/docs/react/
- Click on one of the links in `RELATED GUIDES` :
  - State Management
  - Testing React Components
  - Schema Design

**Versions**

N.A.

**Bonus**

source where urls are defined:
https://github.com/apollographql/apollo-client/blob/45deadb726a1294422f844d984589d6d5968e992/docs/_config.yml#L60

**Comment by danilobuerger** [comment]
Closing, since the related guides have been removed from the sidebar.
