### ISSUE TITLE
Recommend building introspectionQueryResultData in memory on server startup instead of writing to file?

### ISSUE THREAD

**Issue by jedwards1211** [apollographql/apollo-client#4148]
It seems to me that writing the introspection query result data to a file at build time is more cumbersome than necessary for most users.

Furthermore, `apollo-server` 2 disallows introspection queries by default (the docs for using fragments are old and don't warn about this) and my approach below works around this problem.

So do you guys think it's better to do something like this?  If so I can make a PR to the docs.

```js
import { once } from 'lodash'
import { execute } from 'graphql'
import gql from 'graphql-tag'

const documentAST = gql`
{
  __schema {
    types {
      kind
      name
      possibleTypes {
        name
      }
    }
  }
}
`

const getFragmentTypes = once(async (schema) => {
  const {data} = await execute(
    schema,
    documentAST,
  )
  return data
})

app.get('/fragmentTypes.json', async (req, res) => {
  try {
    const data = await getFragmentTypes(ApolloServer.schema)
    res.status(200).json(data)
  } catch (error) {
    res.status(500).json({ error: error.message })
  }
})
```

**Comment by danilobuerger** [comment]
Closing as has nothing to do with apollo-client.
