### ISSUE TITLE
Typescript: ApolloClient.mutate<D,V>: how to retrieve a D object from returned result? 

### ISSUE THREAD

**Issue by slorber** [apollographql/apollo-client#4153]
When using ApolloClient.mutate, we should be able to handle the result in a typed way. 
Surprisingly I don't find documentation on how to do this on typescript and I can't make it work fine without resorting to casting.

Note the TS types I use here are generated by apollo codegen and not really relevant, they are correct.

**Intended outcome:**

This should not compile imho, but it does:

```ts
export const deleteOrderMutation = async (orderId: Id): Promise<Id> => {
  const result = await AppApolloClient.mutate<
    DeleteOrderMutation,
    DeleteOrderMutationVariables
  >({
    mutation: gql`
      mutation DeleteOrderMutation($orderId: ID!) {
        deleteOrder(orderId: $orderId) { id }
      }
    `,
    variables: {
      orderId,
    },
  })
  return result.data!.ICANPUTWHATEVERIWANTHERE
}
```

**Actual outcome:**

It compiles for weird reasons

**How to reproduce the issue:**

Try to mutate with generic TS data/variable params and use the result of the mutation

**Versions**

latest

**Comment by hwillson** [comment]
This should be fixed in current versions of `apollo-client` / `react-apollo`. Thanks!
