### ISSUE TITLE
How can I do it when the variable has a custom type? Like a InputObjectType defined on the server? You can see what I mean on the bellow code.

### ISSUE THREAD

**Issue by if1999615** [apollographql/apollo-client#4162]
` mutation AddComment($object: CustomType!)`

_Originally posted by @viniciusthamor in https://github.com/apollographql/apollo-client/issues/2762#issuecomment-413556019_

**Comment by danilobuerger** [comment]
Issues here are reserved for bugs, but one of the following resources should help:

* Apollo's Slack: https://www.apollographql.com/slack
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests
