### ISSUE TITLE
has been blocked by CORS policy: Request header field apollographql-client-version is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by Danjavia** [apollographql/apollo-client#4164]
**Actual outcome:**

the request headers preflight is broke with the follow answer *has been blocked by CORS policy: Request header field apollographql-client-version is not allowed by Access-Control-Allow-Headers in preflight response*.

**How to reproduce the issue:**

Installing dependencies via yarn install

**Versions**

react-apollo: "^2.2.2

**Comment by danieldunderfelt** [comment]
I have also gotten caught by this after I updated my dependencies (apollo-client from 2.4.5 to 2.4.7) just now. How do I turn off requesting these headers?

**Comment by MFCo** [comment]
Same issue here, I've tried downgrading but it didn't fix anything. Maybe an internal dependency?

**Comment by lmatheus** [comment]
This is happening to me as well, this is very recent

**Comment by Danjavia** [comment]
I have 4 projects using apollo-client and the issue began yesterday, I saw it using CI and in the building process, all my projects has crashed. luckily I was able to reconstruct some, doing the build from my local machine. But is impossible to deploy right now. I consider it's a critical issue.

**Comment by Danjavia** [comment]
> Same issue here, I've tried downgrading but it didn't fix anything. Maybe an internal dependency?

I believe it is the issue

**Comment by hwillson** [comment]
The `apollographql-client-version` header was added in a recent `apollo-link-http` update (https://github.com/apollographql/apollo-link/pull/872). I see the issue, and am working on a fix. It will be ready in a few minutes, at which point updating your version of `apollo-link-http` should fix the issue.

**Comment by hwillson** [comment]
Updating to `apollo-link-http` 1.5.7 should fix this issue. Let me know if it doesn't - thanks!

**Comment by Emiliano-Bucci** [comment]
Hi, i'm experiencing the same error with version 1.5.9 of `apollo-link-http`

**Comment by guimochila** [comment]
@hwillson I'm also experiencing the same issue with the following versions: 

`"apollo-client": "^2.4.12",  "apollo-link-http": "^1.5.9",`

I have tried to downgrade to 1.5.7 but no luck. 😞

**Comment by guimochila** [comment]
I have fixed it. The issue was the Apollo-server was overriding the cors settings I had. Thanks!

**Comment by Emiliano-Bucci** [comment]
I'm only using Next.js with express, and have the same error :/

**Comment by romfrolov** [comment]
Experiencing the same issue.

**apollo-client**: ^2.6.8
**apollo-link-http**: ^1.5.16

**Comment by cdelgadob** [comment]
The package **apollo-link-batch-http: 1.2.13** has the same issue

**Comment by YuliyaNovik** [comment]
hey everyone!
if you face the issue, you can check apollo-server as @guimochila suggested.
In my case I needed to add apollographql-client-version and apollographql-client-name headers to allowedHeaders
```
const server = new ApolloServer({
  cors: {
    // other cors options
    allowedHeaders: [...yourAllowedHeaders, 'apollographql-client-version', 'apollographql-client-name'],
  },
  // other apollo config
 });
```
These headers, apollographql-client-version and apollographql-client-name, are added to your requests automatically if you specify name and version in ApolloClient options as a part of [client awareness feature](https://master--apollo-server-docs.netlify.app/docs/apollo-server/monitoring/metrics/#identifying-distinct-clients):

_If you're using Apollo Client, you can set default values for client name and version in the_ [ApolloClient constructor](https://www.apollographql.com/docs/react/api/apollo-client/#the-apolloclient-constructor). _All requests to Apollo Server will automatically include these values in the appropriate headers._
