### ISSUE TITLE
Can't use compose() in CRA-TS

### ISSUE THREAD

**Issue by borisyordanov** [apollographql/apollo-client#4186]
**Intended outcome:**

I'm trying to include multiple mutations in one component. I read in [the docs](https://www.apollographql.com/docs/react/api/react-apollo.html#compose) `compose` would be a good solution for this. 

**Actual outcome:**

I tried to use `compose` [as specified in the docs](https://www.apollographql.com/docs/react/api/react-apollo.html#compose), but when i tried using it i got a `TypeError: Object(...) is not a function` on the line with `compose()`

**How to reproduce the issue:**

If you add this code (with proper mutations) to a CRA-TS app you should get the same error.
```
export default compose(
    graphql(gql`
        mutation ...
    `),
    graphql(gql`
        mutation  ...
    `)
)(Component);
```
**Versions**

```
  System:
    OS: Windows 10
  Binaries:
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    apollo-boost: ^0.1.16 => 0.1.16
    react-apollo: ^2.2.4 => 2.2.4
```

**Comment by CarloPalinckx** [comment]
I doubt this is an apollo specific bug, but I wouldn't mind having a look if you can produce a minimal reproduction repo :)

**Comment by borisyordanov** [comment]
@CarloPalinckx I tried setting up [a repo](https://github.com/borisyordanov/apollo-ts-client), but i keep getting this error `Argument of type '"query { ... }"' is not assignable to parameter of type 'DocumentNode'.` when i try to use `compose`

**Comment by CarloPalinckx** [comment]
Your example repo uses raw strings as queries instead of an AST, you have to use the gql template literal (https://github.com/apollographql/graphql-tag) to create queries :)

**Comment by borisyordanov** [comment]
@CarloPalinckx That makes sense. Not sure why [the docs](https://www.apollographql.com/docs/react/api/react-apollo.html#compose) don't mention that though.

I'm having trouble reproducing this. I'll close this for now until i can provide a repo.
