### ISSUE TITLE
Missing types for ApolloError

### ISSUE THREAD

**Issue by timhwang21** [apollographql/apollo-client#4203]
Hi, pretty simple issue. If needed I can file a PR, just looking for guidance on which files I should change, etc. Thanks!

**Intended outcome:** Given `error: ApolloError`, `error.networkError`, `error.statusCode` etc. shouldn't cause type errors.

**Actual outcome:** There are type errors. Looking at the generated declaration file, `ApolloError` simply extends `Error`. [https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-http-common/src/index.ts#L14](The missing types seem to be handled in `apollo-link-http-common`).

**How to reproduce the issue:** 

```typescript
import { ApolloError } from 'apollo-client'
handleError = (e: ApolloError) => {
  const { statusCode, result } = error.networkError
  // gives type error
}
```

**Versions**

```
  System:
    OS: macOS 10.14.1
  Binaries:
    Node: 10.12.0 - /usr/local/bin/node
    Yarn: 1.12.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.110
    Firefox: 63.0.3
    Safari: 12.0.1
  npmPackages:
    apollo-cache-inmemory: 1.3.11 => 1.3.11
    apollo-client: 2.4.7 => 2.4.7
    apollo-link: 1.2.4 => 1.2.4
    apollo-link-error: 1.1.2 => 1.1.2
    apollo-link-http: 1.5.7 => 1.5.7
    apollo-link-rest: 0.6.0 => 0.6.0
    apollo-link-state: 0.4.2 => 0.4.2
    react-apollo: 2.3.1 => 2.3.1
```

**Comment by JacksonKearl** [comment]
Hey there, this seems to be resolved by now, the current type is:
```ts
export declare function isApolloError(err: Error): err is ApolloError;
export declare class ApolloError extends Error {
    message: string;
    graphQLErrors: ReadonlyArray<GraphQLError>;
    networkError: Error | null;
    extraInfo: any;
    constructor({ graphQLErrors, networkError, errorMessage, extraInfo, }: {
        graphQLErrors?: ReadonlyArray<GraphQLError>;
        networkError?: Error | null;
        errorMessage?: string;
        extraInfo?: any;
    });
}
```

Closing for now, if I have misunderstood the issue please let me know!

**Comment by nathanmarks** [comment]
@JacksonKearl 

at least with `apollo-link-http`, `graphQLErrors` is **not** `GraphQLError[]`.

This tripped me up, I opened an issue here: https://github.com/apollographql/apollo-link/issues/1116

Could we possibly use a type that accurately represents the object we're dealing with on the client?

**Comment by JacksonKearl** [comment]
Pinging @hwillson for Apollo Client knowledge. :)

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!

**Comment by papermana** [comment]
@hwillson We're using a recent version of @apollo/client (3.3.3), and have the same issue as @nathanmarks does. `graphQLErrors` is an array of objects that match the interface `GraphQLError`, but they are _not_ instances of it. It would be nice if Apollo either instantiated `GraphQLError` or provided a function similar to `isApolloError`.
