### ISSUE TITLE
pollInterval with fetchPolicy of 'cache-first'

### ISSUE THREAD

**Issue by tafelito** [apollographql/apollo-client#4204]
I wanted to re iterate on the issue #1706 but because that one is closed I'm opening a new one.

I just started a new project using apollo-boost. One requirement I have is to be able to query some data from the cache if available, if not query from the server. Data does not update very often but I do need to update it at least once a day. I was looking for a way to expire the data on the cache but that doesn't seem to be an option (I did see that the server has a cache maxAge) so I used the `pollInterval` prop instead. While reading the docs I found that polling and cache-first policy can't be used together, as the issue I pointed out shows. 

The weird thing is, this is kind of working even tho it says it doesn't, in some cases. The default fetchPolicy as I understand, is 'cache-first'. If I set a `pollInterval`, this seems to be working fine. Now if I manually set the fetchPolicy to 'cache-first' then I do get the error https://github.com/apollographql/apollo-client/blob/905001e40cfadf841aa5a78aa428ab09f8cdf108/packages/apollo-client/src/core/ObservableQuery.ts#L536

So I'm not sure if this is an actual issue or maybe I'm missing something. 

**How to reproduce the issue:**

just create a new react-app using apollo-boost and set a pollingInterval to a Query. Then manually set the fetchPolicy to 'cache-first'

**Versions**

```
  System:
    OS: macOS 10.14.1
  Binaries:
    Node: 11.2.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.110
    Safari: 12.0.1
  npmPackages:
    apollo-boost: ^0.1.22 => 0.1.22
    react-apollo: ^2.3.2 => 2.3.2
```

**Comment by hwillson** [comment]
While it may work in some cases, using polling with `cache-first` / `cache-only` is not fully supported, so it's best to avoid it. The error message returned is correct and should be heeded. Thanks!

**Comment by HugoLiconV** [comment]
I'm having a similar issue where I set the fetch policy to `no-cache` and set a polling interval, the first time it fetches the query it doesn't store it in the caché, but when it fetches using the polling it does store the data in caché and it is causing a weird behavior

**Comment by luciob** [comment]
This issue should be reopened, it is causing major bug in production code.
My situation is totally similar to @HugoLiconV.

```
const { data, error, loading, refetch, startPolling, stopPolling } = useQuery<
  IData,
  IVariables
>(GET_DATA, {
  fetchPolicy: "no-cache",
  variables: { paging: LIST_DEFAULT_PAGING, query },
});

useEffect(() => {
  startPolling(DEFAULT_POLLING_INTERVAL_MILLIS);
  return () => stopPolling();
}, [startPolling, stopPolling]);
```

`GET_DATA` returns an array of objects, where each object contains a list of dictionary data.
Assume the following as response example from GQL server:
```
[
    {
      id: 1,
      label: "ABC",
      values: [
        { id: 1, value: 123, __typename: "Value" },
        { id: 2, value: 456, __typename: "Value" },
      ],
      __typename: "Main"
    },
    {
      id: 2,
      label: "DEF",
      values: [
        { id: 1, value: 789, __typename: "Value" },
        { id: 2, value: 012, __typename: "Value" },
      ],
      __typename: "Main"
    },
  ];
```

I only see correct data for `Main` with `id = 2` in the first render. Following paints are displaying cached values for `id = 1`.
Can you please tell me how to fix this issue without code changes on the server part?

**Comment by eddivalen** [comment]
Hey guys, this worked for me:
```
mounted(){
      this.$apollo.queries.products.setOptions({
        pollInterval: 60000,
        fetchPolicy: 'no-cache'
      })
},
apollo:{
    repNotifications:{
      query: GET_PRODUCTS,
      loadingKey: 'loading',
      errorPolicy: 'all',
      fetchPolicy: 'no-cache',
      watchLoading(isLoading){
        this.loading = isLoading
      },
      variables(){
        return {
          product: this.product,
        }
      },
      pollInterval: 60000,
    },
},
```
