### ISSUE TITLE
Type error: Cannot find name 'Map' when importing apollo-boost 

### ISSUE THREAD

**Issue by cpackingham** [apollographql/apollo-client#4205]
Hello! I am trying to set up apollo boost with create-react-app & typescript. When I import apollo-boost, I get the following error:
```bash
node_modules/apollo-cache-inmemory/lib/fixPolyfills.d.ts
Type error: Cannot find name 'Map'. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.  TS2583

  > 1 | declare const testMap: Map<any, any>;
      |                        ^
    2 | declare const testSet: Set<any>;
    3 | declare const frozen: {};
    4 | //# sourceMappingURL=fixPolyfills.d.ts.map
```
I have attempted adding the "lib" option to the tsconfig, targeting esnext, as suggested by the error, but this doesn't help. 

To reproduce the issue, follow these steps:
1. `create-react-app someApp`
2. `yarn add typescript @types/node @types/react @types/react-dom @types/jest`
3. `yarn add apollo-boost react-apollo graphql`
4. Change `App.js` to `App.tsx`, delete the logo import and jsx element
5. `yarn start`
--- Should still work at this point ---
6. In `App.tsx`, `import ApolloClient from 'apollo-boost';` (note, this will auto generate a tsconfig.json, maybe that is where the problem is?)
7. Save, should produce the error.

(My versions, if they may be of use)
  System:
    OS: macOS 10.14.1
  Binaries:
    Node: 11.3.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.110
    Safari: 12.0.1
  npmPackages:
    apollo-boost: ^0.1.22 => 0.1.22
    react-apollo: ^2.3.2 => 2.3.2

Many thanks!

**Comment by luoto** [comment]
@cpackingham, I had a similar issue. Try changing the target in your `tsconfig.json` so that the compiler uses `esnext`, ex:
```
{
  "compilerOptions": {
    "target": "esnext",
    ...
```

**Comment by benjamn** [comment]
I wouldn't change your `compilerOptions.target`, since that affects how your code is compiled, and may break your application in older browsers. Instead, try including `"lib": ["es2015"]` in your `tsconfig.json` file, so TypeScript knows you're using an environment that has `Map`, `Set`, etc. You may also need to provide a polyfill for older browsers, but how you do that is up to you.
