### ISSUE TITLE
Same entity always returned by readFragment

### ISSUE THREAD

**Issue by lindekaer** [apollographql/apollo-client#4211]
**Intended outcome:**
Read fragment from Apollo cache for several **different** objects 

**Actual outcome:**
The `readFragment` method returns the same object despite calling `readFragment` with **different IDs**. The objects returned is the first in the collection of objects - very close the description from incache memory:

(from docs)

*If id and _id are not specified, or if __typename is not specified, InMemoryCache will fall back to the path to the object in the query, such as ROOT_QUERY.allPeople.0 for the first record returned on the allPeople root query.*

**How to reproduce the issue:**
Our setup is as follows:

**Client setup**
```
const client = new ApolloClient({
  ...,
  cache: new InMemoryCache({
    dataIdFromObject: object => object.id,
  }),
})
```

**Example of cache content**
Notice how the **meal** has just the UUID as its cache key. The fragment being read is of the **nutrients field** with an ID of `$ce3a0464-4fc3-11e8-918d-2bb2c301f254.nutrients`. This is also present in the cache. 

![image](https://user-images.githubusercontent.com/4806217/49449440-2a0a0b80-f7db-11e8-90e4-443dab6b772a.png)

We try to read the fragment as follows:

```
client.readFragment({
  id: meal.id
  fragment: gql`
    fragment MealNutrients on Meal {
      id
      name
      nutrients {
        omega3Sum
        omega6Sum
      }  
    }
`
})
```

No matter which `meal.id` is passed, the same meal is always returned.

**Versions**
```
apollo-cache-inmemory: 1.3.0 => 1.3.0
apollo-client: 2.4.6 => 2.4.6
apollo-link: 1.2.3 => 1.2.3
apollo-link-batch-http: 1.2.4 => 1.2.4
apollo-server: 2.0.4 => 2.0.4
apollo-server-express: 2.1.0 => 2.1.0
apollo-upload-client: 8.1.0 => 8.1.0
react-apollo: 2.3.1 => 2.3.1
```

**Comment by benjamn** [comment]
Please upgrade `apollo-cache-inmemory` to the latest version, which is currently 1.3.11. A *lot* has changed since 1.3.0.

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-client/issues/4211#issuecomment-445051168, this should now be fixed. Thanks!
