### ISSUE TITLE
Cannot Find Name Exclude

### ISSUE THREAD

**Issue by ziagit** [apollographql/apollo-client#4225]
I have install apollo on ionic 3
I want to fetch data from Shopify server, but I'm getting an error

**Intended outcome:**

I want to log data from Shopify server into my console

**Actual outcome:**
`
[app-scripts] [12:25:44]  typescript: ...ers/developer.web/Desktop/New folder/test/node_modules/apollo-angular/types.d.ts, line: 9
[app-scripts]             Cannot find name 'Exclude'.
[app-scripts]        L9:  export declare type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
[app-scripts]       L10:  export interface WatchQueryOptions<V> extends Omit<CoreWatchQueryOptions<V>, 'query' | 'variables'> {
`

**How to reproduce the issue:**

in a fresh ionic app install apollo and configure as below link
https://www.apollographql.com/docs/angular/basics/setup.html

when I run ionic serve   the error shows in my console

**Versions**
Ionic:

   ionic (Ionic CLI)  : 4.2.1 (C:\Users\developer.web\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

result of  `npx envinfo@latest --preset apollo --clipboard`
  System:
    OS: Windows 10
  Binaries:
    Node: 8.11.2 - C:\Program Files\nodejs\node.EXE
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    apollo-angular: ^1.5.0 => 1.5.0
    apollo-angular-link-http: ^1.4.0 => 1.4.0
    apollo-cache-inmemory: ^1.3.11 => 1.3.11
    apollo-client: ^2.4.7 => 2.4.7
    apollo-link: ^1.2.4 => 1.2.4

**Comment by pl12133** [comment]
Sounds like https://github.com/apollographql/apollo-angular/issues/770

You might want to try upgrading `typescript` (see https://github.com/apollographql/apollo-angular/issues/770#issuecomment-415448967).

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-client/issues/4225#issuecomment-446053476, this isn't an Apollo Client issue. Thanks!
