### ISSUE TITLE
Data is not coming in apollo client 

### ISSUE THREAD

**Issue by AnkurSaini07** [apollographql/apollo-client#4227]
Server Side
Schema File
   ```
type User {
        _id: ID
        firstName: String!
        lastName: String!
        type: String!
        email : String!
        timeStamp: Date!
        clusters: JSON!
    }
    type Query {
        user: User!
    }

```
Apollo Server

```
const formatResponse = (response, {context}) => {
    const {user} = context;
    if (response.data) {
        response.data.token = createToken({...context}, !!(user && user.forever));
    }
    return response;
};

const server = new ApolloServer({
    formatError,
    formatResponse,
    typeDefs,
    resolvers,
    subscriptions,
    context,
    introspection: true,
    playground: true
});
```
so from server side i am sending token in every request in format response.
its working in playground and Apollo client as well but if i change my schema like

   ```
    type Query {
        user: JSON!
    }

```

i did not get token in Apollo client but i get token in playground. 

**Intended outcome:**
  the outcome should be 
```

{
  "data": {
    "user": {
      "_id": "5b018069d60c9f540868dbcf",
      "email": "info@senraco.com",
      "firstName": "Senra",
      "lastName": "Demo",
    },
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXIiOnsiX2lkIjoiNWIwMTgwNjlkNjBjOWY1NDA4NjhkYmNmIiwiZW1haWwiOiJpbmZvQHNlbnJhY28uY29tIiwiZmlyc3ROYW1lIjoiU2VucmEiLCJsYXN0TmFtZSI6IkRlbW8iLCJ0eXBlIjoi......."
  }
}
```

**Actual outcome:**
```
{
  "data": {
    "user": {
      "_id": "5b018069d60c9f540868dbcf",
      "email": "info@senraco.com",
      "firstName": "Senra",
      "lastName": "Demo",
    }
  }
}
```

**How to reproduce the issue:**

**Versions**

```
"apollo-cache-inmemory": "^1.3.11",
    "apollo-client": "^2.4.7",
    "apollo-link": "^1.2.4",
    "apollo-link-error": "^1.1.2",
    "apollo-link-http": "^1.5.7",
    "apollo-link-ws": "^1.0.10",
    "apollo-utilities": "^1.0.26",
    "graphql": "^14.0.2",
    "graphql-tag": "^2.10.0",
    "subscriptions-transport-ws": "^0.9.15"
```

**Comment by AnkurSaini07** [comment]
I guess if there are no selectable fields in the query then Apollo client does not set the token in response.

**Comment by JoviDeCroock** [comment]
What's your query?

**Comment by AnkurSaini07** [comment]
@JoviDeCroock 
Query
```
query{
    user
}
```

**Comment by JoviDeCroock** [comment]
Well you are querying your user object only while on the same level you have token, this implies that `query { user, token }` would reliably return the data if your query is structured like `user: User, token: String`.

**Comment by AnkurSaini07** [comment]
@JoviDeCroock 
On server side, I am sending token in  formatResponse method, if I execute the same query in the playground I get response {user, token} but when I execute the same query using Apollo client I only get {user}.

if i create a User Type in my schema
```

type User {
     _id: ID
     firstName: String!
     lastName: String!
     type: String!
     email : String!
     timeStamp: Date!
     clusters: JSON!
 }
 type Query {
     user: User!
 }
```

and then execute the query

```
query{
    user{
        firstName
    }
}
```

then I get {user ,token} as  response in both playground and Apollo client.

**Comment by hwillson** [comment]
If this is still a problem with a current version of `apollo-client`, please post a small runnable reproduction and we'll take a look. Thanks!
