### ISSUE TITLE
Push() method causing component to unmount on optimisticResponse update in Mutation

### ISSUE THREAD

**Issue by TheoMer** [apollographql/apollo-client#4229]
**Intended outcome:**

Cache to be updated with new item and for UI to reflect this change

**Actual outcome:**

An iten is added to cache but the component un-mounts (UI re-renders)

**How to reproduce the issue:**
1. Go to https://flamingo-next-production.herokuapp.com.
2. login using, Username: `testing123@123.com`, Password:` testing123`.
3. click 'My cart' link and delete any items in there. Leave cart window open.
4. click `Shop` link and add an item. Observe the open cart window/UI after you have clicked add (You may have to wait a few moments before observing change).

The update section of the following code, at the point where the push method is called, is where the component is caused to un-mount as shown im the link above:

```
const CURRENT_USER_QUERY = gql`
  query {
    me {
      id
      email
      name
      permissions
      orders {
        id
      }
      cart {
        id
        quantity
        item {
          id
          price
          image
          title
          description
          mainDescription
          quantity
        }
      }
    }
  }
`;

const ADD_TO_CART_MUTATION = gql`
  mutation addToCart($id: ID!) {
    addToCart(id: $id) {
      id
      quantity
    }
  }
`;

class AddToCart extends React.Component {
  update = (cache, { data: { addToCart } }) => {
    const data = cache.readQuery({ query: CURRENT_USER_QUERY });
    data.me.cart.push(addToCart);
    cache.writeQuery({ 
      query: CURRENT_USER_QUERY, 
      data
    });
  };
  
  render() {
    const { id, quantity, title, image, price } = this.props;
    return (
      <Mutation
        mutation={ADD_TO_CART_MUTATION}
        variables={{
          id,
        }}
        optimisticResponse={{
          __typename: 'Mutation',
          addToCart: {
            __typename: 'CartItem',
            id: '-1',
            quantity: 1,
            item: {
              __typename: 'Item',
              id,
              price,
              image,
              title,
              description: 'test',
              mainDescription: 'test',
              quantity,
            }
          }
        }}
        update={this.update}
        refetchQueries={[{ query: CURRENT_USER_QUERY }, { query: ALL_ITEMS_QUERY }]}
      >
        {(addToCart, { loading }) => {
          // Determine whether the item quantity is still in stock. 
          if (quantity >= 1) {
            return (<button disabled={loading} onClick={() => {
              addToCart().catch(err => alert(err.message));
            }}>
              Add{loading && 'ing'} To Cart 🛒
            </button>)
          } else {
            return (<button>
              Out of Stock 🛒
            </button>)
          }
        }}
      </Mutation>
    );
  }
}

export default AddToCart;
```

**Versions**
OS: Windows 10 Pro
apollo-boost": "^0.1.16"
apollo-client": "^2.4.2"
react-apollo": "^2.2.1"

**Additional Info**
If you comment out `data.me.cart.push(addToCart);` and do:

```
    cache.writeQuery({ 
      query: CURRENT_USER_QUERY, 
      data: {
        addToCart
      }
    });
```
then addToCart is written to cache without the side effect of the component being un-mounted (re-rendered), but the UI is not immediately updated with the newly added item.

**Comment by JoviDeCroock** [comment]
Pushing to that array is a Mutation (a mutation makes your properties non equal), the correct way of going about this is to do `const newCart = [...data.me.cart, addToCart]`

**Comment by TheoMer** [comment]
@JoviDeCroock Many thanks for the reply. Unfortunately doing:

```
    const newCart = [...data.me.cart, addToCart];
    cache.writeQuery({ 
      query: CURRENT_USER_QUERY, 
      data: {
        newCart,
      }
    });
```
does not update the UI immediately with a new item, there is a noticeable delay.
