### ISSUE TITLE
Subscribing to mutate returns data from a different query and throws error

### ISSUE THREAD

**Issue by Igneous01** [apollographql/apollo-client#4235]
I am experiencing a very bizarre error. 

I have 2 operations - a query called 'environments' to get a list of environments, and a mutation 'createEnvironment' to create a new environment. Both of these operations work correctly on their own.

The problem I am running into is that when calling the mutation I get an error saying that 'createEnvironment' is a field that is missing in query 'environments' which does not make any sense.  If I comment or remove the watchQuery on 'environments', then the createEnvironment mutation is sent to the graphQL server and works correctly.

Below is my component code - ngOnInit contains the watchQuery, and the mutation is in the openCreateForm.

```
import { Component, OnInit } from '@angular/core';
import {EnvironmentFormModalComponent} from "../environment-form-modal/environment-form-modal.component";
import {NgbModal} from "@ng-bootstrap/ng-bootstrap";
import {MatSnackBar} from "@angular/material";
import {Schema} from "../../../reactive-mat-table/domain/schema";
import {Apollo} from "apollo-angular";
import {CREATE_ENVIRONMENT, GET_ENVIRONMENTS} from "../../../../graphql/queries/query";
import {map, tap} from "rxjs/operators";
import {Environment, Query} from "../../../../graphql/schema/parsed";
import gql from "graphql-tag";
import {Observable} from "rxjs/internal/Observable";

@Component({
  selector: 'app-list-environment',
  templateUrl: './list-environment.component.html',
  styleUrls: ['./list-environment.component.css']
})
export class ListEnvironmentComponent implements OnInit {

  environments: Observable<Environment[]>;
  columns: Schema[];

  constructor(private apollo: Apollo, private modalService: NgbModal, public snackBar: MatSnackBar) {
    this.columns = [
      { columnDef: 'name', header: 'Name', cell: (element: any) => `${element.name}` },
      { columnDef: 'code', header: 'Code', cell: (element: any) => `${element.code}` },
      { columnDef: 'keywords', header: 'Keywords', cell: (element: any) => `${element.keywords}` },
    ];
  }

  ngOnInit() {
    this.environments = this.apollo.watchQuery<Query>({
      query: gql`  
	  {
		environments {
		  identification
		  name
		  code
		  description
		  keywords
		}
	  }
	`,
      pollInterval: 250
    })
      .valueChanges
      .pipe(tap(result => {
        console.log("DATA RECEIVED");
        console.log(result);
      }), map(result => result.data.environments));
  }

  openCreateForm(event: any) {
    const modalRef = this.modalService.open(EnvironmentFormModalComponent);
    const environment: Environment = {
      code: "",
      description: "",
      keywords: [],
      name: "",
      createdDate: null,
      lastModifiedDate: null,
      identification: null
    };
    modalRef.componentInstance.title = "Create";
    modalRef.componentInstance.environment = environment;
    modalRef.componentInstance.onSubmitCallback = (env: Environment) => {
      this.apollo.mutate({
        mutation: gql`
		  mutation createEnvironment($data: EnvironmentCreateInput) {
			createEnvironment(data: $data){
			  identification
			}
		  }
		`,
        variables: {
          data: {
            code: env.code,
            keywords: env.keywords,
            description: env.description,
            name: env.name
          }
        }
      }).subscribe(({data}) => {
        console.log('CreateEnvironment - got data: ', data);
        this.openSnackBar('Created environment with id: ' + data.createEnvironment.identification, 'Saved');
        modalRef.componentInstance.close(true);
      },(error) => {
        this.openSnackBar('Error: ' + error, 'Error');
      });
    };
  }

  openSnackBar(message: string, action: string) {
    this.snackBar.open(message, action, {
      duration: 2000,
    });
  }

}
```

**Intended outcome:**
The response data to be for the correct mutation.

**Actual outcome:**
This warning is logged in the console

Missing field createEnvironment in {
  "environments": [
    {
      "identification": "46494403-7fe7-4c17-9d48-561194fa6729",
      "n

![image](https://user-images.githubusercontent.com/5571589/49955858-dc278e80-fed1-11e8-939f-4c17639e23a3.png)

The data returned in the mutation is the result set from the query 'environments', instead of the result of the mutation. The mutation is never sent over to the graphQL server.

**Versions**
  System:
    OS: Windows 7
  Binaries:
    Node: 10.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    apollo-angular: ^1.5.0 => 1.5.0
    apollo-angular-link-http: ^1.3.1 => 1.4.0
    apollo-cache-inmemory: ^1.3.2 => 1.3.11
    apollo-client: ^2.4.0 => 2.4.7
    apollo-link: ^1.2.0 => 1.2.4

**Comment by Igneous01** [comment]
Some more information.

If I change the watchQuery to just a query, then I get different behaviour.

When navigating to the page, the list will load initially. Then when I try to create a new environment for the first time, I get the same error as above. However, sometimes on the second or third attempt, the mutation will be successful and I will see apollo send the mutation request to the backend server.

**Comment by benjamn** [comment]
Any chance you could put this together into a CodeSandbox reproduction. We'd be happy to dig into it.

**Comment by Igneous01** [comment]
I haven't had any success reproducing it in a separate project using the same dependencies and versions in my package.json, I'm not sure if it's another package that's interfering with apollo at this point. I'm still looking into what's causing this to happen in our main project. Hopefully should have more info soon.

**Comment by Igneous01** [comment]
After 4 days of investigation I have uncovered the issue - a custom HttpInterceptor that we were using in our project was interfering with the requests that Apollo was making.

The issue would go away when removing the HttpInterceptor from our app.module.

app.module.ts
```{ provide: HTTP_INTERCEPTORS, useClass: CachingInterceptor, multi: true },````

caching-interceptor.ts
```
@Injectable()
export class CachingInterceptor implements HttpInterceptor {
  constructor(private cache: RequestCache) {}

  intercept(req: HttpRequest<any>, next: HttpHandler) {
    const cachedResponse = this.cache.get(req);
    return cachedResponse ? of(cachedResponse) : this.sendRequest(req, next, this.cache);
  }

  sendRequest(
    req: HttpRequest<any>,
    next: HttpHandler,
    cache: RequestCache): Observable<HttpEvent<any>> {
    return next.handle(req).pipe(
      tap(event => {
        if (event instanceof HttpResponse) {
          cache.put(req, event);
        }
      })
    );
  }
}
```

The interceptor seems to work fine for other libraries such as StompJs, HttpClient when we make requests with them, but it appears to interfere with Apollos Caching mechanism.

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
