### ISSUE TITLE
Undefined values reset local state to default values

### ISSUE THREAD

**Issue by chuntley** [apollographql/apollo-client#4238]
I ended up hitting this bug when React was unexpectedly trying to set a value in apollo-link-state to undefined. There were no errors being thrown or any indication as to why all values were being reset back to default values, which ended up taking hours to track down. The only thing I ended up seeing was a warning in the console about a missing value.

**Intended outcome:**
When a value is set to undefined when writing a mutation to the apollo cache, an error should be thrown in the promise chain saying that the value is invalid.

**Actual outcome:**
When a value is set to undefined the apollo cache resets itself back to default values, only showing a warning in the console.

**How to reproduce the issue:**
https://codesandbox.io/s/8lrpr29wql

As you can see in the output, the state is reset back to default values with no error being caught in the promise chain of the mutation. Try uncommenting line 36 and removing line 37 to see it behave properly.

**Versions**

```
    "apollo-cache-inmemory": "1.1.11",
    "apollo-client": "2.2.7",
    "apollo-link": "1.2.1",
    "apollo-link-http": "1.5.3",
    "apollo-link-state": "0.4.1",
    "graphql": "0.13.1",
    "graphql-tag": "2.8.0"
```

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client`, and let us know if this issue is still happening. Thanks!

**Comment by chuntley** [comment]
I updated the dependencies in the CodeSandbox and verified the issue was still present. If I mark one of the fields as undefined it returns the warning:

```
Missing field email in {
  "__typename": "User",
  "id": "some-id",
  "name": "some-name",
  "level": "some-level"
} 
```

Then resets all fields to default values. Look at the comments on line 36 and 37 on this: https://codesandbox.io/s/apollo-client-queriesmutations-forked-31vmp?file=/src/index.js

**Comment by hwillson** [comment]
@chuntley This issue was fixed in `@apollo/client` (Apollo Client 3), whereas your reproduction is using `apollo-client` (Apollo Client 2).
