### ISSUE TITLE
GraphQL subscribe:  getting a null response before publish is called

### ISSUE THREAD

**Issue by JeffML** [apollographql/apollo-client#4244]
**Intended outcome:**
When I subscribe via apollo-link, the handler function gets a response before pubsub.publish() is called.  The response is null.

**Actual outcome:**
I expect the first client subscription response to come after the publish() is called on the server

**How to reproduce the issue:**
I'll summarize it here; there is a complete project with a test that can be executed if requested.

### Mocha test:
```
import { execute, makePromise } from 'apollo-link';

const uri = 'http://localhost:3001/graphql';
const link = new HttpLink({ uri, fetch });

const subscribe = (query, handlers) => {
  const operation = {
    query: gql`${query}`,
  };

  return execute(link, operation).subscribe(handlers);
};


  const handlers = {
    next: (data) => {
      console.log(`received data: ${Date.now()}, ${JSON.stringify(data, null, 2)}`);
    },
    error: error => console.log(`received error ${error}`),
    complete: () => console.log('complete'),
  };

  it('subscribe', async () => {
    const query = `subscription {
      info
    }`;
    subscribe(query, handlers);
  });
```
Server code:
```
try {
  console.log('subscription =>| ', Date.now(), '|', line);
  worker.pubsub.publish('infoTopic', { info: line });
} catch (e) {
  console.error(e);
}
```
The client log:

> received data: 1545013826838, { "errors": [ { "message": "Cannot return null for non-nullable field Subscription.info.",...

The server log:

> subscription =>| 1545013826887 | info depth 1 seldepth 1 ...

Subscriber is receiving at 826**838**, but publisher is sending at 826**887**

**Versions**
		"apollo-link": "^1.2.4",
		"apollo-link-http": "^1.5.7",
		"apollo-link-ws": "^1.0.10",
		"apollo-server-express": "^2.2.5",
		"babel-cli": "^6.26.0",
		"babel-preset-env": "^1.7.0",
		"body-parser": "^1.18.3",
		"eslint": "^5.9.0",
		"eslint-config-airbnb-base": "^13.1.0",
		"eslint-plugin-import": "^2.14.0",
		"express": "^4.16.4",
		"fen-validator": "^1.1.0",
		"graphql": "^0.13.2",
		"graphql-subscriptions": "^0.5.8",
		"graphql-tag": "^2.10.0",
		"graphql-tools": "^3.1.1",
		"lodash": "^4.17.11",
		"node-fetch": "^2.3.0",
		"stockfish": "^8.0.0",
		"subscriptions-transport-ws": "^0.9.15"

**Comment by ssalka** [comment]
Hey Jeff, I also ran into an issue like this while setting up my react client - the reason was that I wasn't using a websocket link (you've got `apollo-link-ws` installed, but are not using it).

With the HTTP link, subcriptions seem to be treated like queries/mutations and are requested immediately, rather than when subscribed to. Using `WebSocketLink` as described [here](https://www.apollographql.com/docs/react/advanced/subscriptions.html#subscriptions-client) fixed my problem.

Hope this helps!

**Comment by JeffML** [comment]
Thanks! I did finally get it working awhile ago...
https://hackernoon.com/graphql-subscriptions-using-apollo-2-3eb3184768c4
