### ISSUE TITLE
writeFragment updates behave differently when offline vs online. 

### ISSUE THREAD

**Issue by carllippert** [apollographql/apollo-client#4248]
**Intended outcome:**
When using writeFragment in update function the UI gets updated for queries including that object.

**Actual outcome:**
writeFragment will update object in query when online but when offline the ui does not update the data. Found specifically in query with "cache-and-network" fetch-policy. If a user manually hits the query, for instance by a pull to refresh on said query, the ui will update. That is the only way to get the ui to update offline in this scenario. 

**How to reproduce the issue:**
Use writeFragment in update function in airplane mode or similar no network situation updating an object that exists in a cache-and-network query. 

I found this in react-native application on android. 

**Versions**
 "apollo-cache-inmemory": "^1.3.11",
 "apollo-client": "^2.4.7",
 "apollo-link-state": "^0.4.2",

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
