### ISSUE TITLE
[apollo-cache-inmemory] inMemoryCache fails to store object that has multiple interface implementations

### ISSUE THREAD

**Issue by edmundas-ramanauskas** [apollographql/apollo-client#4249]
I have following situation
I have a query, which returns a different implementation of the same interface. and query works just fine in graphql playground. but when executed with apollo-client it fails with error `Missing field ...` (field is present in one implementation, but not in the other).

**Intended outcome:**
query should work and data should be stored in cache

**Actual outcome:**
query fails

**How to reproduce the issue:**

here's my schema:
```
interface Model {
  id: String!
}

type BasicModel implements Model {
  id: String!
}

type SuperModel implements Model {
  id: String!
  name: String
}

type Query {
  """Dummy query to prevent error with extend"""
  model(id: String!): Model
}
```

my query that I execute:
```
query {
  model(id:"1") {
    id
    ...on SuperModel {
      name
    }
  }
}
```

query resolver:
```
export default (root, {id}) => {
  if (id === '1') {
    return {id};
  }
  return {id, name: 'test'};
};
```

my object resolver:
```
export default {
  __resolveType: ({name}) => (name ? 'SuperModel' : 'BasicModel'),
};
```

the result I get in graphql playground:
```
{
  "data": {
    "model": {
      "id": "1"
    }
  }
}
```

error I get:
```
Missing field name in {
  "id": "1",
  "__typename": "BasicModel"
}
writeToStore.js:107 
```

**Versions**

"apollo-cache-inmemory": "^1.3.11",
"apollo-client": "^2.4.7",
"apollo-link-batch-http": "^1.2.4",
"apollo-link-error": "^1.1.2",
"apollo-link-http": "^1.5.7",
"apollo-link-schema": "^1.1.2",
"apollo-link-ws": "^1.0.10",
"apollo-utilities": "^1.0.26",

**Comment by edmundas-ramanauskas** [comment]
I think this is the solution for my problem:
https://www.apollographql.com/docs/react/advanced/fragments.html#fragment-matcher
can someone confirm? is there simpler solution?

**Comment by Pruxis** [comment]
Yes that is the solution to your problem edmund.
