### ISSUE TITLE
Writing items to cache very slow with heuristic fragment matching inside create-react-app

### ISSUE THREAD

**Issue by steabert** [apollographql/apollo-client#4254]
**Intended outcome:**

No error log each time a heuristic match is taking place. Even though it's maybe create-react-app to blame that console.error is extremely slow for some reason, I'm wondering if you could avoid logging this for every fragment? This would at least mitigate any performance problems caused by other packages.

**Actual outcome:**

An error is logged each time a heuristic match is taking place, which can lead to extremely slow loading in e.g. create-react-app, where console.error is somehow overwritten with something else.

**How to reproduce the issue:**

Any query which leads to a large amount of items being written to the cache using heuristic fragment matching in create-react-app.

**Versions**

  System:
    OS: Linux 4.17 Debian GNU/Linux buster/sid undefined
  Binaries:
    Node: 10.14.2 - /usr/bin/node
    Yarn: 1.12.3 - /usr/bin/yarn
    npm: 6.4.1 - /usr/bin/npm
  Browsers:
    Chrome: 70.0.3538.67
    Firefox: 60.3.0
  npmPackages:
    apollo-boost: ^0.1.22 => 0.1.22 
    react-apollo: ^2.3.2 => 2.3.3

**Comment by steabert** [comment]
Related issue: https://github.com/facebook/create-react-app/issues/6078

**Comment by danilobuerger** [comment]
This should only occur in development mode. The warning is not shown in production. If this is not the case, feel free to reopen.

Other than that, it feels like a feature request and those should be opened in https://github.com/apollographql/apollo-feature-requests.
