### ISSUE TITLE
react-native-web example not working

### ISSUE THREAD

**Issue by axhamre** [apollographql/apollo-client#4263]
**Intended outcome:**
Followed the link [in the docs](https://github.com/apollographql/apollo-client/blob/master/docs/source/essentials/get-started.md) to the React native web example: https://codesandbox.io/s/xk7zw3n4

**Actual outcome:**
The fetch in the app errored out.

**How to reproduce the issue:**
Follow the above links.

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
