### ISSUE TITLE
Probably error on trying to access client cache while being updated

### ISSUE THREAD

**Issue by lukejagodzinski** [apollographql/apollo-client#4265]
I think I found some bug in the library but I want to make sure that I understand everything properly. I have a React component with the `Query` element being used:

```jsx
<Query query={/* ... */}>{ /* conditionally render some stuff */ }</Query>
```

which uses the following query:
```gql
query organizationSelect {
  session @client {
    organizationId
  }
  organizations {
    id
    name
  }
}
```

As you can see, I the `session.organizationId` part is client side only. On initial run its value is `null`. I take initial value for this field by executing query at the application start:

```js
(async () => {
  if (app.isSignedIn()) {
    try {
      const { data } = await client.query({
        query: SESSION_ORGANIZATION_QUERY,
      });
      if (!data.session.organizationId) {
        const { data } = await client.query({
          query: USER_ORGANIZATION_QUERY,
        });
        await client.mutate({
          mutation: SELECT_ORGANIZATION_MUTATION,
          variables: {
            organizationId: data.user.organization.id,
          },
        });
      }
    } catch (error) {
      console.log("error", error);
    }
  }
})();
```
The code above is run in the `main.js` file - in app starting point. What this code does is just check if the `session.organizationId` is set. If it's not then, just pick organizationId from the server and set it into local cache. This part of the app works properly and there are no problems with that.

The problem is actually displaying stuff using the `organizationSelect` query. When having both client and server query in one place it fails to render. It just renders nothing without any error. I solved this problem by separating queries into two parts: one containing client query and the second one containing server query:

first part:
```gql
query organizations {
  organizations {
    id
    name
  }
}
```

second part:
```gql
query sessionOrganization {
  session @client {
    organizationId
  }
}
```

But that forces me to use two nested `<Query>` components which is not ideal.

However, when I try to access other client only session property it works without the problem. It only doesn't work when a given client only field is being kinda access/computed by some other part of application.

Any idea why is this happening and possible solution? Am I doing something wrong?

**Comment by hwillson** [comment]
Please try a recent version of @apollo/client and let us know if this issue is still happening. Thanks!
