### ISSUE TITLE
@connection with variable causes variable not used error

### ISSUE THREAD

**Issue by matthewdias** [apollographql/apollo-client#4277]
**Intended outcome:**
When running a query using a variable that is only used for the `@connection` argument, the variable should be stripped out.

**Actual outcome:**
The directive is stripped out by apollo-client, but the variable definition is left in, causing an error when it reaches the http link.

```
Variable $key is declared by PaginatedQuery but not used
```

**How to reproduce the issue:**
Write a query with a variable that is only used for a `@connection` argument.
```
  const query = gql`
    query PaginatedQuery(
      $key: String!
      $pageAmount: Int
      $endCursor: String
    ) {
      paginatedCollection(first: $pageAmount, after: $endCursor)
		@connection(key: $key) {
        ...fields
      }
    }
    ${fields}
  `;
```
Full example:
[![Edit apollo-client-error-template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yxrnrlmyv?module=%2Fsrc%2FApp.js)

**Versions**
```
  System:
    OS: macOS 10.14
  Binaries:
    Node: 10.14.1 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Firefox: 63.0.3
    Safari: 12.0
  npmPackages:
    apollo-boost: ^0.1.22 => 0.1.23
    react-apollo: ^2.3.2 => 2.3.3
    react-apollo-hooks: ^0.2.1 => 0.2.1
  npmGlobalPackages:
    apollo: 2.1.8
```

**Comment by CarloPalinckx** [comment]
I'm pretty sure you are not supposed to use a variable as key for a connection. You have to a string literal here :)

**Comment by matthewdias** [comment]
Okay, fair enough.
