### ISSUE TITLE
MockedProvider - mutation errors are not passed to the component

### ISSUE THREAD

**Issue by albertortizn26** [apollographql/apollo-client#4283]
Hi,
I have been facing a problem mocking data with MockedProvider.
With queries all works as expected, when I mock success and errors, the problem comes with mutations, success are ok but when I try to mock an error it is not passed to my component in the render function, instead an Error is thrown.

Test:
```javascript
 const mocks = [
        {
            request: {
                query: MY_MUTATION,
                variables: {
                    userId: 'error'
                },
            },
            error: new Error('boom!')
        }
];

it('my test that should pass', () => {

        const wrapper = mount(
            <MockedProvider mocks={mocks}>
                <MyComponent ... />
            </MockedProvider>
        );
...
```
Component:
```javascript
 <Mutation mutation={MY_MUTATION} >
                {(cancelMandate, {loading, error}) => (
...
```
When I run the test it just throw the exception but in a live environment it is passed to the component!

**Comment by CarloPalinckx** [comment]
What versions are you using?

**Comment by royderks** [comment]
Having the same problem, with "apollo-boost": "0.1.7",

**Comment by mintyfloss** [comment]
Same with version 2.5.1

**Comment by veddermatic** [comment]
I see the same, but in queries as well. Both of these:
```
{
  request: {
    query: MY_QUERY,
    variables: myVars
  },
  result: {
     errors: [new GraphQLError("Error!")],
  }
};
```
and 
```
{
    request: {
      query: MY_QUERY,
      variables: myVars,
    },
    error: new Error('aw shucks'),
  };
```

Simply throw an error in Jest and fail the test. Using:
```
"@apollo/react-testing": "3.0.1",
"apollo-boost": "0.4.4",
"react-apollo": "3.0.1",
```

**Comment by svalchinov** [comment]
I'm experiencing the same, what's the workaround if a fix is missing?

**Comment by svalchinov** [comment]
We managed to get around using errorPolicy if anyone else gets stuck:


```javascript
<MockedProvider mocks={[mocks]} addTypename={false} defaultOptions={{
    mutate: {
        errorPolicy: "all"
    }
}}>
    <Component />
</MockedProvider>
```

**Comment by MitchK** [comment]
We ran into the same issue and the error is no longer thrown if we handle the error using an `onError` handler:
```
const [mutate, {loading, error}] = useMutation(
  MY_GQL_MUTATION,
  {
    variables: ...
  },
  onError: ...
);
```

**Comment by hwillson** [comment]
We are planning a significant `MockedProvider` overhaul in the not too distant future. In the meantime, there are several workarounds listed in this issue, so I'll close it for now. Thanks!
