### ISSUE TITLE
[Official Tutorial] client action-button can't TOGGLE_CART  

### ISSUE THREAD

**Issue by cqby** [apollographql/apollo-client#4284]
Hi, I am following the official tutorial, but get stuck on Update local data:

**Intended outcome:**

1. go to a launch page and add it to cart
2. try remove from cart
3. should be removed

**Actual outcome:**

1. go to a launch page and add it to cart
2. try remove from cart
3. removed in cart, but the launch page remains the remove button,

**How to reproduce the issue:**

clone the official tutorial and launch the app.

**Versions**

```json
  "dependencies": {
    "@reach/router": "^1.2.1",
    "apollo-cache-inmemory": "alpha",
    "apollo-client": "alpha",
    "apollo-link-http": "^1.5.5",
    "emotion": "^9.2.12",
    "graphql": "^14.0.2",
    "graphql-tag": "^2.10.0",
    "polished": "^2.3.0",
    "react": "^16.5.2",
    "react-apollo": "alpha",
    "react-dom": "^16.5.2",
    "react-emotion": "^9.2.12",
    "react-scripts": "2.0.4"
  }
```

**My debug Result**
It seems like 
```js
    isInCart: (launch, _, { cache }) => {
      const { cartItems } = cache.readQuery({ query: GET_CART_ITEMS });
      return cartItems.includes(launch.id);
    },
```
returned false, which is what we expected, but the `resolver()` function in LocalState.js has such logic:
```js
     if (!result) {
        if (normalNode !== undefined || aliasedNode !== undefined) {
          result = aliasedNode || normalNode;
        }
      }
```
seems like used the cached data.

**Comment by mwindson** [comment]
It has been fixed in this commit [eb808196dc6e2bce92b46cc0161c425d0055f40f](https://github.com/apollographql/apollo-client/commit/eb808196dc6e2bce92b46cc0161c425d0055f40f)

**Comment by smolinari** [comment]
Does anyone know when that fix will be in alpha? It isn't in alpha2. I just checked.

Scott

**Comment by hwillson** [comment]
Please try a recent version of @apollo/client and let us know if this issue is still happening. Thanks!
