### ISSUE TITLE
Non-idempotent fragments clobber each other in the cache, even with alias

### ISSUE THREAD

**Issue by timbotnik** [apollographql/apollo-client#4292]
**Intended outcome:**
The intention is to use 2 "non-idempotent" but similar fragments in a single query and get 2 different results.  By non-idempotent, I mean that running the same query again will yield different results, since assumably the "current version" has changed.  (inspired by reproduction in https://github.com/apollographql/apollo-client/issues/3972)

For example:
```
query DocumentQuery1 {
    document {
      id
      currentVersion {
        name
      }
      currentVersion2: currentVersion {
        name
      }
    }
  }
```

**Actual outcome:**
Over the network, we see 2 different results come back.  However in the response served up by `ApolloClient` in the app, we see the same result repeated for `currentVersion.name` and `currentVersion2.name` (last result wins and clobbers the previous result).  
IF we set `fetchPolicy='no-cache'` then we actually do see 2 different results.

![screen shot 2019-01-08 at 5 42 39 pm](https://user-images.githubusercontent.com/1831709/50814678-97770200-136e-11e9-800b-5dc086afaaf2.png)

In addition, adding a `dataIdFromObject` to return a cache key based on `name` doesn't seem to have any effect.

**How to reproduce the issue:**
Client: https://codesandbox.io/s/lxxnr8y4m9
Server: https://codesandbox.io/s/ovo7rrr1yz

**Versions**
Viewable from codesandbox.

![screen shot 2019-01-08 at 5 54 26 pm](https://user-images.githubusercontent.com/1831709/50814638-829a6e80-136e-11e9-8311-478bf7cb18b8.png)
![screen shot 2019-01-08 at 5 54 35 pm](https://user-images.githubusercontent.com/1831709/50814639-829a6e80-136e-11e9-96f8-4db5f6ede258.png)

**Comment by KevinDanikowski** [comment]
+1
I have the same issue however I would like to extend it to say that if I have two separate cache key identifiers with the same beginning string pattern, i.e. 'App' __typename and 'AppKey' __typename that this will occur to the first result of 'AppKey' from the 'App' __typename. 

Not found a way around it except to remove one of the __typenames from the `dataIdFromObject`, to change the name to not have a similar string pattern, or to remove the call from checking the cache.

**Comment by hwillson** [comment]
👋 @timbotnik any idea if this is still an issue? We're cleaning up the backlog, so I'll close it for now, but let me know if this is still happening. Thanks!
