### ISSUE TITLE
Client failure in browser due to 'response.body.emit is not a function'

### ISSUE THREAD

**Issue by qcortex** [apollographql/apollo-client#4301]
**Intended outcome:**

I have written a Graphql client that is working fine in playground and also from unit tests.  The client is configured as per instructions, it uses the split feature to route dispatch over http/ws comms channel as appropriate.  

**Actual outcome:**

However in a browser the response.body appears to be set to 'Object [object]' rather than the expected (JSON) result.  The following console error is reported:

```
Uncaught TypeError: response.body.emit is not a function
    at abort (index.js:1407)
    at AbortSignal.abortAndFinalize (index.js:1416)
    at httpLink.ts:190
    at cleanupSubscription (Observable.js:90)
    at notifySubscription (Observable.js:145)
    at onNotify (Observable.js:165)
    at SubscriptionObserver.error (Observable.js:224)
    at httpLink.ts:184
```

**Versions**

apollo-client: 2.4.8

**Comment by hwillson** [comment]
Please try a recent version of @apollo/client and let us know if this issue is still happening. Thanks!
