### ISSUE TITLE
Apollo client typings.

### ISSUE THREAD

**Issue by pavel1992** [apollographql/apollo-client#4310]
**Intended outcome:**

When i tried to disable cors for request, initialising my client as `const client = new ApolloClient({
    uri: process.env.BACKEND_URL,
    fetchOptions: {
        mode: 'no-cors',
    },
});`
i have an error `  TS2322: Type '{ mode: string; }' is not assignable to type 'Options'.
`

It looks like an interface error, because passing mode to fetchOptions works properly. 

**How to reproduce the issue:**

Just initialise apollo client using TypeScript, as i show.

**Versions**

npx: installed 1 in 1.785s

  System:
    OS: macOS 10.14.2
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Safari: 12.0.2
  npmPackages:
    apollo-boost: ^0.1.23 => 0.1.23 
    apollo-client: ^2.4.8 => 2.4.8 
    apollo-link-http: ^1.5.9 => 1.5.9 
    react-apollo: ^2.3.3 => 2.3.3

**Comment by JoviDeCroock** [comment]
As far as I see mode does not belong to the options, https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-http-common/src/index.ts#L55. If this functionality is supported it should be extended here.

**Comment by danilobuerger** [comment]
Closing since this is not documented as being possible. So this is a feature request.

Feature requests and non-bug related discussions are no longer managed in this repo. Feature requests should be opened in https://github.com/apollographql/apollo-feature-requests.
