### ISSUE TITLE
Mutation element curly brace position

### ISSUE THREAD

**Issue by JeffML** [apollographql/apollo-client#4312]
**Intended outcome:**

On a Mutation component, it seems that the block must begin on a new line after the start tag:
```const Submit = props => <Mutation mutation={DELETE}>
  {mDelete => (
    <Mutation mutation={UPSERT}>
      {mUpsert => (
        <input type="submit" value="Submit Changes" style={{ float: 'right' }}
          onClick={evt => submitAction({
            evt, returnTo: props.setPage, mDelete, mUpsert, refetch: props.refetch,
          })} />
      )}
    </Mutation>
  )}
</Mutation>;
```

**Actual outcome:**

if the curly brace is placed immediately after the start tag, then a runtime error occurs:
    `<Mutation mutation={UPSERT}> {mUpsert => (...`

Error:

> index.js:1446 Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `Mutation`, expected `function`.
    in Mutation (at SubmitCancel.js:82)

**Versions**

  System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 10.12.0 - /usr/local/bin/node
    npm: 6.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Safari: 12.0.2
  npmPackages:
    apollo-boost: ^0.1.22 => 0.1.22
    react-apollo: ^2.3.2 => 2.3.2
```

**Comment by JoviDeCroock** [comment]
I don't think this has anything to do with apollo, because we are expecting a render function. This has to do with how react-jsx transpiles this. Because jsx now supports passing a function, array, null and a string.

**Comment by JeffML** [comment]
Okay, but perhaps the error message could be better?  In any case, I'll post this on react-jsx and see where it goes.
