### ISSUE TITLE
apollo-cache-inmemory v1.2 -> v1.3 breaks IE11

### ISSUE THREAD

**Issue by alexnez96** [apollographql/apollo-client#4314]
**Description**
When updating dependencies, I encountered an issue in IE11 where a blank page is displayed on load. I was able to pin it down and found that it occurs after upgrading `apollo-cache-inmemory` from `^1.2.10` to `^1.3.12`. The bug is only observed in IE11 and not in Chrome. `^1.2.10` works like charm across browsers. Could it be that `v1.3.12` defines a reserved `for` property on an object internally?

**Intended outcome:**
It should work in IE11.

**Actual outcome:**
The page loads blank in IE11 only. The console error is `"Possible Unhandled Promise Rejection: TypeError: Object doesn't support property or method 'for'"`.

**How to reproduce the issue:**
Use `apollo-cache-inmemory: ^1.3.12` in IE11

![screen shot 2019-01-15 at 5 38 02 pm](https://user-images.githubusercontent.com/32908329/51215308-78d4b600-18ee-11e9-8bda-ea4503264185.png)

**Versions**
```json
"apollo-cache-inmemory": "^1.3.12",
"apollo-client": "^2.4.8",
```

**Comment by benjamn** [comment]
Any idea where in the code the error about the `for` method is coming from?

**Comment by alexnez96** [comment]
It's hard to say. The stack has very little details in IE.

**Comment by alexnez96** [comment]
It seems to be originating from `Symbol.for`. Here's a sample from the bundle (prettified)

```js
var n = "function" == typeof Symbol ? Symbol.for("nodejs.util.inspect.custom") : void 0;
```

Not sure where exactly it's coming from though.

**Comment by benjamn** [comment]
@alexnez96 I recently added a guard to ensure `Symbol.for` is a function in one of the dependencies of `apollo-cache-inmemory` [here](https://github.com/benjamn/immutable-tuple/commit/dff1503ba07e4f879efaeb6c0e3b2c95ddf87ddc). I have no idea if that was the source of this error, but you might want to try using `immutable-tuple@0.4.10`.

**Comment by alexnez96** [comment]
Thanks for your swift response, @benjamn. Apparently, `immutable-tuple` wasn't (the only) culprit, so in the end, I had to polyfill `Symbol` manually with `core-js`. That should take care of both `Symbol` and `Symbol.for`.
