### ISSUE TITLE
Connect to multiple graphql API's

### ISSUE THREAD

**Issue by sandeepkumardev** [apollographql/apollo-client#4330]
I have an existing Graphql API endpoint working fine. I have a 3rd party service provider from whom I need to consume using graphql. I don't see a way add multiple clients. I know the whole purpose of graphql is to have only one endpoint, but still this exceptional case can't be neglected.

**Comment by danilobuerger** [comment]
Issues here are reserved for bugs, but one of the following resources should help:

* Apollo's Slack: https://www.apollographql.com/slack
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests
