### ISSUE TITLE
Apollo Utilities Update to 1.1.0 seems to break some Subscriptions.  Cannot read property 'some' of undefined.

### ISSUE THREAD

**Issue by djizco** [apollographql/apollo-client#4333]
** Intended Outcome **

Queries and Subscriptions return data without an Error

** Actual Outcome **

Runtime Error occurs and no data is returned

** Description of Problem **

When making a Query/Subscription with React-Apollo I get an error "Network Error: Cannot read property 'some' of undefined".  Exact code was working perfectly fine on 1/14/19, and a package update seemed to produce this error after a clean npm install.  After investigation, it seems that "apollo-utilities" was internally updated from 1.0.27 to 1.1.1, even though we never updated our Apollo Versions.  I have not been able to determine if the issue is specifically tied to our use of subscriptions, but I will provide a list of packages we are using along with a screen shot of the error.

** Screenshot **

<img width="566" alt="screen shot 2019-01-18 at 2 52 09 pm" src="https://user-images.githubusercontent.com/14986071/51413037-26d0a200-1b33-11e9-8b14-2e4f59395fcb.png">

** Versions **

Bug is reproducible with these package versions.

   OS: macOS 10.14.2
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 63.0.1
    Safari: 12.0.2
  npmPackages:
    apollo-cache-inmemory: 1.4.1 => 1.4.1 
    apollo-client: 2.4.10 => 2.4.10 
    apollo-link: 1.2.6 => 1.2.6 
    apollo-link-error: 1.1.5 => 1.1.5 
    apollo-link-http: 1.5.9 => 1.5.9 
    apollo-link-state: 0.4.2 => 0.4.2 
    react-apollo: 2.3.3 => 2.3.3

Other Relevant Packages we are using:

@absinthe/socket-apollo-link: "0.2.0"
graphql-tag: "2.10.1"

** Solution **

I am pretty sure the bug is within apollo-utilities because we were able to resolve the issue by manually installing "apollo-utilities@1.0.27" as a dependency, and it fixed the problem.

**Comment by benjamn** [comment]
Is this possibly related to https://github.com/apollographql/apollo-client/pull/4329?

**Comment by djizco** [comment]
It very well could be related, but It's hard to tell since it just says "throwing errors".  I didn't see any issue for this specific error.  It may also have something to do with absinthe, but I'm not sure.

**Comment by benjamn** [comment]
@djizco We released a fix for #4329 in `apollo-utilities@1.1.2` just now, if you want to give that a try.

**Comment by djizco** [comment]
Issue seems to be resolved now. Thanks!
