### ISSUE TITLE
Second argument of update function in mutation returns null

### ISSUE THREAD

**Issue by Firebrand** [apollographql/apollo-client#4341]
The documentation [here](https://www.apollographql.com/docs/react/essentials/mutations.html#basic) under "Updating the cache" mentions "The second argument to the update function is an object with a data property containing your mutation result."

It gives the following example, however, that second argument to the update function ({ data: { addTodo } }) **is always null** and causes the whole example to error out:

```
<Mutation
      mutation={ADD_TODO}
      update={(cache, { data: { addTodo } }) => {
        const { todos } = cache.readQuery({ query: GET_TODOS });
        cache.writeQuery({
          query: GET_TODOS,
          data: { todos: todos.concat([addTodo]) }
        });
      }}
    >
```

**Comment by danilobuerger** [comment]
Closing, please follow the issue template and provide a reproducible sample.
