### ISSUE TITLE
Updating the cache doesn't work

### ISSUE THREAD

**Issue by Firebrand** [apollographql/apollo-client#4351]
**Intended outcome:**
Second argument to the update function on a mutation should be an object with a data property containing the mutation result.

**Actual outcome:**
Second argument is always returning a null object instead

**How to reproduce the issue:**
Run this code from the [Apollo Client documentation page](https://www.apollographql.com/docs/react/essentials/mutations.html#basic):

```
const GET_TODOS = gql`
  query GetTodos {
    todos
  }
`;

const AddTodo = () => {
  let input;

  return (
    <Mutation
      mutation={ADD_TODO}
      update={(cache, { data: { addTodo } }) => {
        const { todos } = cache.readQuery({ query: GET_TODOS });
        cache.writeQuery({
          query: GET_TODOS,
          data: { todos: todos.concat([addTodo]) },
        });
      }}
    >
      {addTodo => (
        <div>
          <form
            onSubmit={e => {
              e.preventDefault();
              addTodo({ variables: { type: input.value } });
              input.value = "";
            }}
          >
            <input
              ref={node => {
                input = node;
              }}
            />
            <button type="submit">Add Todo</button>
          </form>
        </div>
      )}
    </Mutation>
  );
};
```

**Versions**
2.1.9 to 2.4.0

**Comment by danilobuerger** [comment]
Just checked, this works on my machine and all the test cases. If you still think that its a bug in apollo-client please provide a fully working, minimal, reproducible sample and reopen.

**Comment by Firebrand** [comment]
@danilobuerger     

Here you go:  https://codesandbox.io/s/6x33348nrw

That's the complete sample ToDo app from the Apollo Client - Mutations doc here:  https://www.apollographql.com/docs/react/essentials/mutations.html

**Comment by danilobuerger** [comment]
Thats because your graphql endpoint `https://codikon.com/graphql` returns `null` instead of the todo, so `addTodo` in the `update` function is `null` as that is what is returned from the endpoint.
