### ISSUE TITLE
Refetch queries with any parameter

### ISSUE THREAD

**Issue by ilyes-garifullin** [apollographql/apollo-client#4357]
I have faced with a problem when refetching queries after mutation. If query has no parameters thats ok, but if query has several parameters, and different pages uses different of them. For example, GET_ITEMS query accepts parameters: userId, companyId, categoryId. And we did not know what combination of parameters user selects. How can I say to Apollo to refetch all this queries with any combination of parameters?

**Comment by danilobuerger** [comment]
Issues here are reserved for bugs, but one of the following resources should help:

* Apollo's Slack: https://www.apollographql.com/slack
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests
