### ISSUE TITLE
Can we have the ability to being able to do cache-and-redirect prefetches on SSR

### ISSUE THREAD

**Issue by yangning10000** [apollographql/apollo-client#4358]
**Intended outcome:**
I am currently running a SSR app written in vue. Every time a request hit my server, I prefetched some apollo queries and use renderToString to render the app with apollo data already inside. I would like to use single apollo client(not calling createProvider every time and starts with an empty cache because my SSR server don't contain any user specific information) to serve every request comes to the server and do 'cache-and-network' fetch policy on those prefetched queries so no one got high server response latency.

**Actual outcome:**
client.query may only be used with fetch policy other than 'cache-and-network', and it throws error every time I try to do client.query for my prefetch process.

**Comment by danilobuerger** [comment]
Thanks for your interest in helping make Apollo Client better!

Feature requests and non-bug related discussions are no longer managed in this repo. Feature requests should be opened in https://github.com/apollographql/apollo-feature-requests.
