### ISSUE TITLE
Intercepting cookie from response

### ISSUE THREAD

**Issue by pawelkrystkiewicz** [apollographql/apollo-client#4360]
It is possible to get full response object from ApolloClient, not just the data?
I need to extract the session cookie to manually set it on my client side.
I am currently using Heroku to deploy my two apps, frontend, and backend.

I can see in DevTools ```Set-Cookie``` header and cookie itself in ```Application(Storage)->Cookie``` but browser doesn't set my cookie and it is not accessible to my SSR while trying to authenticate routes for the user. Cookie had domain ```myherokuapp.herokuapp.com```
Oddly enough ApolloClient on the rendered client side is able to access cookie and send it with ```credentials: "include"```

**Comment by danilobuerger** [comment]
Issues here are reserved for bugs, but one of the following resources should help:

* Apollo's Slack: https://www.apollographql.com/slack
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests

**Comment by peterbabic** [comment]
@pawelkrystkiewicz  I am facing the same issue. Did you solve it somehow, any links? Thank You

**Comment by pawelkrystkiewicz** [comment]
@peterbabic no I didn't. There is an [example using getInitialProps](https://github.com/zeit/next.js/tree/canary/examples/with-apollo-auth). But from what I recall it is discouraged to you use getInitialProps as it was invented as a hack for passing props before client render.
I know that there is some way to pass the response with the session cookie to the server and use the server's logic for routing. That would be ideal but the author never wanted to share it.
