### ISSUE TITLE
createHttpLink performance concerns in Firefox

### ISSUE THREAD

**Issue by BarthesSimpson** [apollographql/apollo-client#4371]
We are using an http link to connect to a backend server. In Chrome, everything works fine. In Firefox, however, establishing the link takes up to 5 seconds and blocks the rendering of the page. Inside firebug, I can see that the call to `createHttpLink` is triggering a cascade of garbage collection calls.

**How to reproduce the issue:**
There is nothing special about our set up. In the `index.js` for our application, we just do  

```
import { ApolloClient } from "apollo-client";
import { createHttpLink } from "apollo-link-http";
import { InMemoryCache } from "apollo-cache-inmemory";

const httpLink = createHttpLink({
  uri: <our endpoint>,
  headers: <some custom headers>
});
```

and then 

```
const apolloClient = new ApolloClient({
  link: httpLink,
  cache: new InMemoryCache()
});

```
**Versions**
  System:
    OS: macOS Sierra 10.12.6
  Binaries:
    Node: 10.4.0 - /usr/local/bin/node
    npm: 6.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 60.4.0
    Safari: 12.0.3
  npmPackages:
    apollo-boost: ^0.1.22 => 0.1.23
    react-apollo: ^2.0.0 => 2.3.3

<img width="706" alt="screen shot 2019-01-24 at 1 49 38 pm" src="https://user-images.githubusercontent.com/6706880/51710773-01361380-1fdf-11e9-8658-5de7e22b899c.png">

**Comment by danilobuerger** [comment]
Could you please provide a minimal reproducible sample?

**Comment by hwillson** [comment]
We haven’t heard back regarding a reproduction, so we’ll close this off for now. Thanks!
