### ISSUE TITLE
Caling writeQuery doesn't update Query until I click on the screen

### ISSUE THREAD

**Issue by developdeez** [apollographql/apollo-client#4379]
Calling a simple update query:
```
 cache.writeQuery({
      query: SEARCH_PROFILES,
      variables: { long, lat, limit: LIMIT },
      data: {
        searchProfiles: {
          ...searchProfiles,
          profiles: data.data.newSearch.profiles
        }
      }
    });
```

But for some reason it will only update if I click randomly on the screen. It's really weird. I dont want to do reset Store since it'll break other parts of the page. Why is this working so badly?

**Comment by danilobuerger** [comment]
Issues here are reserved for bugs, but one of the following resources should help:

* Apollo's Slack: https://www.apollographql.com/slack
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests
