### ISSUE TITLE
How can I show the data.errors[].message returned from server when using the <Mutation>  tag on client﻿

### ISSUE THREAD

**Issue by AviIhej** [apollographql/apollo-client#4380]
Hey, I'm running into an issue where I cannot see the error that is thrown by my server. When a user fills out the form and leaves a required field empty, my server throws an error. 

But the only error data that is returned is not coming from my server.
The actual error I throw on the server looks like this:

`{
  "data": null,
  "errors": [
    {
      "message": "Please enter a Job Title",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createJob"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}`

In my react client, I am using ApolloClient, ReactApollo,
and the mutation component. I am trying to console.log the error thrown by the server.

When I say:
`   if(error){
               console.log(error)
                 console.log(error.networkError)
                console.log(error.networkError.result.errors)
 }`

I get this:
![screen shot 2019-01-28 at 1 37 55 am](https://user-images.githubusercontent.com/15176473/51818543-5f901a00-229d-11e9-8d7d-323c5b9ed8da.png)

This error looks absolutely nothing like the error that was thrown from the server.

Any Idea what might be going on?

![screen shot 2019-01-28 at 1 41 47 am](https://user-images.githubusercontent.com/15176473/51818724-ee049b80-229d-11e9-9c95-0b1995d289e2.png)

![screen shot 2019-01-28 at 1 03 00 am](https://user-images.githubusercontent.com/15176473/51817375-7e3fe200-2298-11e9-9580-964848e6d18f.png)
Some help would be really great!

**Comment by danilobuerger** [comment]
Issues here are reserved for bugs, but one of the following resources should help:

* Apollo's Slack: https://www.apollographql.com/slack
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests
