### ISSUE TITLE
Question about sharing an ApolloCache between native and JS code (cross-platform)

### ISSUE THREAD

**Issue by patgoley** [apollographql/apollo-client#4387]
Hey there,

First of all, thanks for a sweet library! I am attempting to write a cross-platform iOS application and would like both Swift and JS code to share the same Apollo Client and local cache. Both JS and Swift code will be running queries and mutations offline, and I need changes to be reflected in both environments. I don't think I'm the  first person to think of this based on this article from the Apollo Medium page:

https://blog.apollographql.com/one-graphql-client-for-javascript-ios-and-android-64993c1b7991 

I'm thinking one possible solution is to use separate ApolloClients, one native (apollo-ios) and one JavaScript (apollo-client). The JS client will be injected with a custom cache object that defers to the native cache. I have no problem providing the native cache to JS, but it's not clear on initial investigation if the native and JS store/cache implement the exact same interface, so I'm not sure if these are easily interchangeable. Perhaps it's close enough that with a little glue code I can make it work. 

I know the Apollo team has thought about this based on the article above. Is there an official way to do this, or should I plan on doing one of the options above? Thank you so much for your time! 

Patrick

**Comment by danilobuerger** [comment]
Issues here are reserved for bugs, but one of the following resources should help:

* Apollo's Slack: https://www.apollographql.com/slack
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests

**Comment by div-dog** [comment]
@patgoley It doesn't look like the ambitions mentioned in the article you posted have come to fruition. My team is looking for a similar solution. We are moving more of our views and logic to native from react-native. We are hoping to share the same cache between native and js. Have you successfully implemented your shared cache or learned anything from attempting? I am about to go down the same path.

**Comment by patgoley** [comment]
@div-dog It's been a while but we weren't able to implement a shared cache without making changes to the Apollo client API, so we abandoned our use of Apollo all together. The problem is that the native client only accepts statically typed Query objects that are internally converted to a gql query string. It would've been much easier if the client API accepted a raw query string as that could be easily generated in JS and passed across the native bridge. This isn't the case, however, or it least it wasn't at the time of my investigation. Hopefully that gives you a starting point. Good luck!

**Comment by div-dog** [comment]
Thank you @patgoley for the insights and your quick response!
