### ISSUE TITLE
[security] Server-side rendering docs allow XSS attack

### ISSUE THREAD

**Issue by danilobuerger** [apollographql/apollo-client#4394]
https://www.apollographql.com/docs/react/features/server-side-rendering.html#store-rehydration

<details>
<summary>Don't use this technique!</summary>

```html
<script>
  window.__APOLLO_STATE__ = client.extract();
</script>
```

</details>

allows for XSS as potential user input is not sanitised. See for example:
https://redux.js.org/recipes/server-rendering#security-considerations

**Comment by abernix** [comment]
The example in the documentation has been updated to include `JSON.stringify` after https://github.com/apollographql/apollo-client/pull/4287, and I've updated the original comment here to ensure that this technique is not used.
