### ISSUE TITLE
Exception thrown from interceptor does not get passed to com.apollographql.apollo.ApolloCall.Callback#onFailure

### ISSUE THREAD

**Issue by adrian-baker** [apollographql/apollo-client#4395]
If an interceptor is added to the OkHttpClient via `okhttp3.OkHttpClient.Builder#addInterceptor` (eg authentication), and this interceptor throws an exception, the apollo client request never completes, neither success or failure methods are ever called.

**Comment by hwillson** [comment]
Apollo Android issues can be reported in https://github.com/apollographql/apollo-android. Thanks!
