### ISSUE TITLE
Optimistic update data missing from readFragment

### ISSUE THREAD

**Issue by tomjamesallen** [apollographql/apollo-client#4402]
**Intended outcome:**

On reading from the cache using cache.readFragment(options, optimistic = true) I would expect the method to return matching entries found under `cache.optimisticData`.

**Actual outcome:**

Instead the method is returning null.

On debugging I found that the problem seemed to be that the [read method of inMemoryCache](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-cache-inmemory/src/inMemoryCache.ts#L174) returns early if it doesn’t find a match for the rootId in the main cache.

If I remove the early return, the readFragment method returns the expected data.

**How to reproduce the issue:**

I have managed to (mostly) reproduce the issue in the following create-react-app project. I have explained the subtle different in behaviour between this and my actual app below.
https://github.com/tomjamesallen/apollo-cache-inmemory-bug-repro

Just clone and run `npm i && npm start`.

The project uses a <Query/> component in the TodoList component to render all of the todos from the server. It maps over the todos and renders a Todo component for each one. The Todo component uses `readFragment` rather than using a <Query/> component - as this is a close match to the logic I have in my actual app.

You can add a new Todo with the `Create Todo` button at the bottom of the screen. This logic lives in the AddTodo component. On clicking the button it runs a mutation with an optimistic response and an `update` handler. The update handler will insert the new todo into the `allTodoes` query results. I have set up an Apollo link that fakes the application being offline at the point that this mutation is called - it will just return an observable that will never “next” if the operationName is `createTodo`.

When this mutation has run you should see the new Todo appear in the list. However, you should see Todo is null, rather than the Todo text.

If you put a breakpoint in `src/Todo.js:42` and hit reload on that ToDo you should be able to debug.

Note. you should see the full todo under the `optimisticData` key in `client.cache`. So I believe it should be possible to retrieve this data with the given fragment.

When you get to `node_modules/apollo-cache-inmemory/lib/inMemoryCache.js:117` you should see that it returns early as `typeof this.data.get(options.rootId) === "undefined”` is true.

If you follow the logic right the way through, you should see that the todo returns null.

If you remove the early return in the node module you should see it return an object instead of null. In my actual app it returns the correct data here, however, in this example project, for some reason it is returning an empty object - I have not got the bottom of this yet.

**Versions**

  System:
    OS: macOS 10.14
  Binaries:
    Node: 8.11.2 - ~/.nvm/versions/node/v8.11.2/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.2/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 64.0.2
    Safari: 12.0
  npmPackages:
    apollo-cache-inmemory: ^1.4.2 => 1.4.2 
    apollo-client: ^2.4.12 => 2.4.12 
    apollo-link: ^1.2.6 => 1.2.6 
    apollo-link-http: ^1.5.10 => 1.5.10 
    react-apollo: ^2.4.1 => 2.4.1

**Comment by flip-it** [comment]
Any thoughts on this yet? I have the same problem.

This makes readFragment to not find the data when a mutation adds a new cache entry. Only when updating.

**Comment by ababushkin** [comment]
This seems to be working for me? Are you having issues still?

BTW thanks for posting this issue because I wasn't even aware that `readFragment` had this hidden argument (it's not documented anywhere)

**Comment by benjamn** [comment]
A lot has changed since this issue was opened, including the transition from `apollo-client` and `apollo-cache-inmemory` to `@apollo/client`, but this bug-fix PR seems relevant, based on the original description of the problem: https://github.com/apollographql/apollo-client/pull/5829

**Comment by hwillson** [comment]
See https://github.com/apollographql/apollo-client/issues/4402#issuecomment-577782718 - closing, thanks!
