### ISSUE TITLE
self.fetch.bind(self) not defined in the browserified js file

### ISSUE THREAD

**Issue by strotech** [apollographql/apollo-client#4408]
I created a node.js file called fetch.js having graphQL call using apollo-fetch. When i run it without browserifying, like, node fetch.js , i get the intended outcome as 

> returned from custom test function

 After i browserified it and created bundle.js and when i try to run the browserified file , i am getting the error

> fetch not defined

Then i included es6-promise and isomorphic-fetch, after looking at the related bugs, and now i am getting the error

> self.fetch.bind(self) not defined

Please find below my  fetch.js, schema and resolver files

`
require('es6-promise').polyfill();
var fetch=require('isomorphic-fetch').fetch;

const { createApolloFetch } = require('apollo-fetch');
const fetchQL = createApolloFetch({
uri: 'http://localhost:4000/graphql',
});

fetchQL({
query: '{testFunction}',
}).then(res => {
console.log(res.data.testFunction);
});
`

with schema as
type myQuery { testFunction: String! }

and resolver as
myQuery:{ testFunction(){ return "returned from custom test function"; }

**Comment by strotech** [comment]
Tried with webpack also, but still getting the error as 

> self not defined

**Comment by danilobuerger** [comment]
`apollo-fetch` is deprecated, please use links.
