### ISSUE TITLE
Type of Data is not propagated down to the refetchQueries callback type

### ISSUE THREAD

**Issue by emattias** [apollographql/apollo-client#4410]
I belive this is a bug: 

https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/watchQueryOptions.ts#L185-L187

It should propagate down the `T` variable. Like so:

```
refetchQueries?:
    | ((result: ExecutionResult<T>) => RefetchQueryDescription)
    | RefetchQueryDescription;
```

**Intended outcome:**
Keep type of execution result in the refetchqueries callback

**Actual outcome:**
The type of the executionresult falls back to `ExecutionResultDataDefault`

**How to reproduce the issue:**

Do a mutation and define a refetchQueries callback function. Something like this:

```js
      const response = client.mutate<SheetDataManagerCreateSheetMutation>({
        awaitRefetchQueries: true,
        mutation: gql`
          mutation SheetDataManagerCreateSheetMutation($sheetInput: SheetInput!) {
            createSheet(sheetInput: $sheetInput) {
              id
              name
            }
          }
        `,
        variables: { sheetInput },
        refetchQueries: (response) => {
			// The type of `response` should be SheetDataManagerCreateSheetMutation but is ExecutionResultDataDefault
		}
      })
```

**Comment by danilobuerger** [comment]
Thanks for the report. Do you want to create a PR for it?
