### ISSUE TITLE
apollo-cache-inmemory's fixPolyfills declares block-scoped variables that can cause duplicate types

### ISSUE THREAD

**Issue by astorije** [apollographql/apollo-client#4417]
If `apollo-cache-inmemory` is used in a project that has a dependency on another project that uses `apollo-cache-inmemory` as well, it leads to type duplicates when building the project with TypeScript, such as:

```
ERROR in [at-loader] ./node_modules/some-library/node_modules/apollo-cache-inmemory/lib/fixPolyfills.d.ts:1:15
    TS2451: Cannot redeclare block-scoped variable 'testMap'.

ERROR in [at-loader] ./node_modules/some-library/node_modules/apollo-cache-inmemory/lib/fixPolyfills.d.ts:2:15
    TS2451: Cannot redeclare block-scoped variable 'testSet'.

ERROR in [at-loader] ./node_modules/some-library/node_modules/apollo-cache-inmemory/lib/fixPolyfills.d.ts:3:15
    TS2451: Cannot redeclare block-scoped variable 'frozen'.

ERROR in [at-loader] ./node_modules/apollo-cache-inmemory/lib/fixPolyfills.d.ts:1:15
    TS2451: Cannot redeclare block-scoped variable 'testMap'.

ERROR in [at-loader] ./node_modules/apollo-cache-inmemory/lib/fixPolyfills.d.ts:2:15
    TS2451: Cannot redeclare block-scoped variable 'testSet'.

ERROR in [at-loader] ./node_modules/apollo-cache-inmemory/lib/fixPolyfills.d.ts:3:15
    TS2451: Cannot redeclare block-scoped variable 'frozen'.
```

This is because of [those variables in `fixPolyfills.ts`](https://github.com/apollographql/apollo-client/blob/5bbeabb3f62053f60dfd3d38fe0ce3b33dc9c648/packages/apollo-cache-inmemory/src/fixPolyfills.ts#L1-L25) which [get declared at the top-level in the type definitions](https://unpkg.com/apollo-cache-inmemory@1.4.2/lib/fixPolyfills.d.ts).

So if both versions of `apollo-cache-inmemory` in the project and its dependency do not match, it causes these duplicates. This for example happens when dependencies are pinned.
One could potentially fix that by removing the pinning in either the project or the dependency, or messing with `tsconfig.json` to pick up the correct dependency, or making the library define it as a `peerDependency` only, but these are not always practical or doable.
Besides, my understanding is that these 3 variables should not even be exposed in the type definitions, they are just local variables that get accidentally exposed in the types, and that it would be better to try not to expose these rather than leaving it out to the consumers.

Is that a correct assessment? What would be an acceptable way to address this? I feel like wrapping this whole file in an [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE) would do the job just fine, but I am open to suggestions.

**Comment by benjamn** [comment]
These variables are local/private within the `fixPolyfills.ts` module, and `apollo-cache-inmemory/lib/fixPolyfills.d.ts` should also be a "module" from the perspective of TypeScript (and it doesn't even export the declarations), so I really do not understand why this would be a problem at all. Wrapping module code in an IIFE should not be necessary, given that module scope is already a very well-defined concept.

Can you put together a reproduction so we can get to the bottom of what's happening here?

**Comment by astorije** [comment]
@benjamn, I can't explain this either.

It took long enough, but I made a reproduction repo at https://github.com/astorije/repro-apollo-cache-inmemory-type-issue. Follow the few lines of setup, and the typing error should just show up.

Let me know if there is anything I can help with.

**Comment by astorije** [comment]
Hey @benjamn, were you able to take a look at my reproduction repo? Thanks! 🙏
