### ISSUE TITLE
How to add Authentication Basic header to query request? 

### ISSUE THREAD

**Issue by gyerts** [apollographql/apollo-client#4420]
I need to work with Graphql development server which requires from user Basic authentication.
![image](https://user-images.githubusercontent.com/10667958/52401458-59cedb80-2aca-11e9-925e-f313bea0d358.png)
On frontend side to make requests to protected graphql service I wrote next code
```
const authLink = setContext((_, { headers }) => {
   return {
      headers: {
         ...headers,
         Authorization: 'Basic ' + btoa('<login>:<pass>'),
      }
   }
});

const httpLink = new HttpLink({
   uri: process.env.REACT_APP_GQL_SERVER,
   fetchOptions: {
      mode: 'no-cors'
   }
});

const client = new ApolloClient({
   link: authLink.concat(httpLink),
   cache: new InMemoryCache(),
});
```
But I can't see "Authorization" header in the browser while request 
![image](https://user-images.githubusercontent.com/10667958/52401501-7834d700-2aca-11e9-8437-cb5642c404ad.png)
Could you please support me to paste Authorization header to the request or understand another way to work with Default Browser Authentication Prompt.

using: "apollo-boost": "^0.1.22", "apollo-link-context": "^1.0.12",

original question here: https://stackoverflow.com/questions/54568174/graphql-apollo-client-cant-see-authorization-header

**Comment by danilobuerger** [comment]
Issues here are reserved for bugs, but one of the following resources should help:

* Apollo's Slack: https://www.apollographql.com/slack
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests
