### ISSUE TITLE
cache-and-network fetchPolicy update cache

### ISSUE THREAD

**Issue by Emiliano-Bucci** [apollographql/apollo-client#4425]
Hi to all, i'm encountering what i think is a weird issue with the fetch policy cache-and-network. Maybe i misunderstood the docs/behavior, but shortly, with this policy, Apollo should first looks in the cache and load data (if there's anyone) and then hits the network looking for data. Then, if data on server (theoretically fresh data) is different from cache, then update the cache. Is this the intended behavior? Or Apollo should update anyway the cache, regardless the fact that there's (or not) data in the cache?

I'm using Next.JS with Apollo: 

> "apollo": "^2.4.4"
  "apollo-cache-inmemory": "^1.4.2"
  "apollo-client": "^2.5.0-beta.1"
  "apollo-link-http": "^1.5.11"

and i'm experiencing this: On first mount Apollo hits the cache and loads all the data correctly; having cache-and-network, Apollo then hits che server (i would like to do this way to check if there's fresh data or not) and then he always updates the cache, causing an unmounting and remounting of the components (so the user see the data, then see the data dissapearing, and then see the data again).

Thanks to all!

**Comment by JoviDeCroock** [comment]
I think this is an issue (as mentioned in the previous issue) of missing the REFETCHING status. 

Since then you can keep your data on screen while the refetch happens. The unmounting of your component is an implementation detail of your codebase and can be caught with the aforementioned status.

**Comment by danilobuerger** [comment]
Issues here are reserved for bugs, but one of the following resources should help:

* Apollo's Slack: https://www.apollographql.com/slack
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests
