### ISSUE TITLE
How to use client.query without JSX components? 

### ISSUE THREAD

**Issue by ClementeSerrano** [apollographql/apollo-client#4427]
Hi guys!

I'm trying to make a query without returning a JSX component, just an object (the `data` object that is received when making a common query to Apollo Server).

I tried using `<Query />` component, but it returns me a React Node and I only need an object. The documentation only explain methods that return JSX components at some point, when all that I'm looking to do is send a request and process the response in a callback.

Any suggestion?

**Comment by JoviDeCroock** [comment]
As stated in the docs to do a one time fetch you can use: https://www.apollographql.com/docs/react/api/apollo-client.html#ApolloClient.query

This will be invoked with `client.query({ query: yourQuery })`, if you need a continuous query you'll need to make an observableQuery.

**Comment by ClementeSerrano** [comment]
Hi @JoviDeCroock ! Thanks for your answer.

I'm using `withApollo` decorator to get the `client`. In the wrapped method I make the `query` and put the data into an object arr. 

The code looks like this:

```
import { withApollo } from 'react-apollo';
import gql from 'graphql-tag';

const MY_QUERY = gql`
  query MY_QUERY {
    myQuery {
      id
      location
      name
      url
    }
  }
`;

const the_query = ({ client }: { client: any }) => {
  const res = client.query({ query: MY_QUERY });
  const { data } = res;

  return data.myQuery.reduce(
    (acc: [Object], { id, name }: { id: string; name: string }, i: number) => {
      acc[i] = { id, name };
      return acc;
    },
    []
  );
};

const the_query_call = withApollo(the_query);

console.log(the_query_call);
```

When I try to log the query, the browser show me the following:

```
ƒ WithApollo(props) {
        var _this = _super.call(this, props) || this;

        _this.setWrappedInstance = _this.setWrappedInstance.bind(_this);
        return _this;
      }
```

And what I'm expecting is just the arr of objects that I construct in the `reduce()` method inside the `the_quey` const.

Do you know how can I get the arr that I'm looking for?

Thanks in advance!!!

**Comment by JoviDeCroock** [comment]
Your query is working but you aren't taking your load time in account, log your res instead of anything else since that is all that matters.

**Comment by ClementeSerrano** [comment]
I've just include the statement `if (data.loading) return null;` and got the same results 😰 

```
const the_query = ({ client }: { client: any }) => {
  const res = client.query({ query: MY_QUERY });
  const { data } = res;
  
  if (data.loading) return null;

  return data.myQuery.reduce(
    (acc: [Object], { id, name }: { id: string; name: string }, i: number) => {
      acc[i] = { id, name };
      return acc;
    },
    []
  );
};
```

**Comment by danilobuerger** [comment]
Issues here are reserved for bugs, but one of the following resources should help:

* Apollo's Slack: https://www.apollographql.com/slack
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests

**Comment by ClementeSerrano** [comment]
Ok! Just moved my question to Slack. Thanks to all!

**Comment by tomas-petrovcin** [comment]
> I've just include the statement `if (data.loading) return null;` and got the same results 😰
> 
I think it should be `const { data, loading } = res;`

**Comment by klendi** [comment]
What about variables ? How to pass variables values like in jsx component with the `variables` attribute ?
