### ISSUE TITLE
Missing field createdAt in object

### ISSUE THREAD

**Issue by mohamadrezamosalli** [apollographql/apollo-client#4435]
hi
When I send the information to the server, these alerts are displayed in the console:
`
writeToStore.js?fa16:83 Missing field createdAt in {
  "__typename": "Todo",
  "_id": -1,
  "content": "fdsfsdf",
  "status": false,
  "user": "5c61af5
(anonymous) @ writeToStore.js?fa16:83
StoreWriter.writeSelectionSetToStore @ writeToStore.js?fa16:62
StoreWriter.writeFieldToStore @ writeToStore.js?fa16:161
(anonymous) @ writeToStore.js?fa16:70
StoreWriter.writeSelectionSetToStore @ writeToStore.js?fa16:62
StoreWriter.writeResultToStore @ writeToStore.js?fa16:40
InMemoryCache.write @ inMemoryCache.js?71f3:119
(anonymous) @ store.js?c582:108
(anonymous) @ store.js?c582:108
InMemoryCache.performTransaction @ inMemoryCache.js?71f3:185
DataStore.markMutationResult @ store.js?c582:107
changeFn_1 @ store.js?c582:45
(anonymous) @ store.js?c582:58
InMemoryCache.performTransaction @ inMemoryCache.js?71f3:185
InMemoryCache.recordOptimisticTransaction @ inMemoryCache.js?71f3:194
DataStore.markMutationInit @ store.js?c582:54
QueryManager.mutate @ QueryManager.js?96af:67
ApolloClient.mutate @ ApolloClient.js?27b0:109
addTodo @ todo.js?b26b:33
wrappedActionHandler @ vuex.esm.js?2f62:721
dispatch @ vuex.esm.js?2f62:428
boundDispatch @ vuex.esm.js?2f62:322
handleAddTodo @ Add.vue?5f53:61
submit @ Add.vue?050c:24
invoker @ vue.runtime.esm.js?2b0e:2132
Vue.$emit @ vue.runtime.esm.js?2b0e:2652
submit @ VForm.js?4bd4:131
invoker @ vue.runtime.esm.js?2b0e:2132
fn._withTask.fn._withTask @ vue.runtime.esm.js?2b0e:1917
writeToStore.js?fa16:83 Missing field _id in "5c61af544cc9be321870874e"
(anonymous) @ writeToStore.js?fa16:83
StoreWriter.writeSelectionSetToStore @ writeToStore.js?fa16:62
StoreWriter.writeFieldToStore @ writeToStore.js?fa16:161
(anonymous) @ writeToStore.js?fa16:70
StoreWriter.writeSelectionSetToStore @ writeToStore.js?fa16:62
StoreWriter.writeFieldToStore @ writeToStore.js?fa16:161
(anonymous) @ writeToStore.js?fa16:70
StoreWriter.writeSelectionSetToStore @ writeToStore.js?fa16:62
StoreWriter.writeResultToStore @ writeToStore.js?fa16:40
InMemoryCache.write @ inMemoryCache.js?71f3:119
(anonymous) @ store.js?c582:108
(anonymous) @ store.js?c582:108
InMemoryCache.performTransaction @ inMemoryCache.js?71f3:185
DataStore.markMutationResult @ store.js?c582:107
changeFn_1 @ store.js?c582:45
(anonymous) @ store.js?c582:58
InMemoryCache.performTransaction @ inMemoryCache.js?71f3:185
InMemoryCache.recordOptimisticTransaction @ inMemoryCache.js?71f3:194
DataStore.markMutationInit @ store.js?c582:54
QueryManager.mutate @ QueryManager.js?96af:67
ApolloClient.mutate @ ApolloClient.js?27b0:109
addTodo @ todo.js?b26b:33
wrappedActionHandler @ vuex.esm.js?2f62:721
dispatch @ vuex.esm.js?2f62:428
boundDispatch @ vuex.esm.js?2f62:322
handleAddTodo @ Add.vue?5f53:61
submit @ Add.vue?050c:24
invoker @ vue.runtime.esm.js?2b0e:2132
Vue.$emit @ vue.runtime.esm.js?2b0e:2652
submit @ VForm.js?4bd4:131
invoker @ vue.runtime.esm.js?2b0e:2132
fn._withTask.fn._withTask @ vue.runtime.esm.js?2b0e:1917
writeToStore.js?fa16:83 Missing field __typename in "5c61af544cc9be321870874e"
(anonymous) @ writeToStore.js?fa16:83
StoreWriter.writeSelectionSetToStore @ writeToStore.js?fa16:62
StoreWriter.writeFieldToStore @ writeToStore.js?fa16:161
(anonymous) @ writeToStore.js?fa16:70
StoreWriter.writeSelectionSetToStore @ writeToStore.js?fa16:62
StoreWriter.writeFieldToStore @ writeToStore.js?fa16:161
(anonymous) @ writeToStore.js?fa16:70
StoreWriter.writeSelectionSetToStore @ writeToStore.js?fa16:62
StoreWriter.writeResultToStore @ writeToStore.js?fa16:40
InMemoryCache.write @ inMemoryCache.js?71f3:119
(anonymous) @ store.js?c582:108
(anonymous) @ store.js?c582:108
InMemoryCache.performTransaction @ inMemoryCache.js?71f3:185
DataStore.markMutationResult @ store.js?c582:107
changeFn_1 @ store.js?c582:45
(anonymous) @ store.js?c582:58
InMemoryCache.performTransaction @ inMemoryCache.js?71f3:185
InMemoryCache.recordOptimisticTransaction @ inMemoryCache.js?71f3:194
DataStore.markMutationInit @ store.js?c582:54
QueryManager.mutate @ QueryManager.js?96af:67
ApolloClient.mutate @ ApolloClient.js?27b0:109
addTodo @ todo.js?b26b:33
wrappedActionHandler @ vuex.esm.js?2f62:721
dispatch @ vuex.esm.js?2f62:428
boundDispatch @ vuex.esm.js?2f62:322
handleAddTodo @ Add.vue?5f53:61
submit @ Add.vue?050c:24
invoker @ vue.runtime.esm.js?2b0e:2132
Vue.$emit @ vue.runtime.esm.js?2b0e:2652
submit @ VForm.js?4bd4:131
invoker @ vue.runtime.esm.js?2b0e:2132
fn._withTask.fn._withTask @ vue.runtime.esm.js?2b0e:1917
writeToStore.js?fa16:83 Missing field createdAt in {
  "__typename": "Todo",
  "_id": -1,
  "content": "fdsfsdf",
  "status": false,
  "user": "5c61af5
(anonymous) @ writeToStore.js?fa16:83
StoreWriter.writeSelectionSetToStore @ writeToStore.js?fa16:62
(anonymous) @ writeToStore.js?fa16:224
StoreWriter.processArrayValue @ writeToStore.js?fa16:207
StoreWriter.writeFieldToStore @ writeToStore.js?fa16:141
(anonymous) @ writeToStore.js?fa16:70
StoreWriter.writeSelectionSetToStore @ writeToStore.js?fa16:62
StoreWriter.writeResultToStore @ writeToStore.js?fa16:40
InMemoryCache.write @ inMemoryCache.js?71f3:119
ApolloCache.writeQuery @ cache.js?10fe:30
update @ todo.js?b26b:44
(anonymous) @ store.js?c582:113
tryFunctionOrLogError @ errorHandling.js?c95d:3
(anonymous) @ store.js?c582:113
InMemoryCache.performTransaction @ inMemoryCache.js?71f3:185
DataStore.markMutationResult @ store.js?c582:112
changeFn_1 @ store.js?c582:45
(anonymous) @ store.js?c582:58
InMemoryCache.performTransaction @ inMemoryCache.js?71f3:185
InMemoryCache.recordOptimisticTransaction @ inMemoryCache.js?71f3:194
DataStore.markMutationInit @ store.js?c582:54
QueryManager.mutate @ QueryManager.js?96af:67
ApolloClient.mutate @ ApolloClient.js?27b0:109
addTodo @ todo.js?b26b:33
wrappedActionHandler @ vuex.esm.js?2f62:721
dispatch @ vuex.esm.js?2f62:428
boundDispatch @ vuex.esm.js?2f62:322
handleAddTodo @ Add.vue?5f53:61
submit @ Add.vue?050c:24
invoker @ vue.runtime.esm.js?2b0e:2132
Vue.$emit @ vue.runtime.esm.js?2b0e:2652
submit @ VForm.js?4bd4:131
invoker @ vue.runtime.esm.js?2b0e:2132
fn._withTask.fn._withTask @ vue.runtime.esm.js?2b0e:1917
writeToStore.js?fa16:83 Missing field _id in "5c61af544cc9be321870874e"
(anonymous) @ writeToStore.js?fa16:83
StoreWriter.writeSelectionSetToStore @ writeToStore.js?fa16:62
StoreWriter.writeFieldToStore @ writeToStore.js?fa16:161
(anonymous) @ writeToStore.js?fa16:70
StoreWriter.writeSelectionSetToStore @ writeToStore.js?fa16:62
(anonymous) @ writeToStore.js?fa16:224
StoreWriter.processArrayValue @ writeToStore.js?fa16:207
StoreWriter.writeFieldToStore @ writeToStore.js?fa16:141
(anonymous) @ writeToStore.js?fa16:70
StoreWriter.writeSelectionSetToStore @ writeToStore.js?fa16:62
StoreWriter.writeResultToStore @ writeToStore.js?fa16:40
InMemoryCache.write @ inMemoryCache.js?71f3:119
ApolloCache.writeQuery @ cache.js?10fe:30
update @ todo.js?b26b:44
(anonymous) @ store.js?c582:113
tryFunctionOrLogError @ errorHandling.js?c95d:3
(anonymous) @ store.js?c582:113
InMemoryCache.performTransaction @ inMemoryCache.js?71f3:185
DataStore.markMutationResult @ store.js?c582:112
changeFn_1 @ store.js?c582:45
(anonymous) @ store.js?c582:58
InMemoryCache.performTransaction @ inMemoryCache.js?71f3:185
InMemoryCache.recordOptimisticTransaction @ inMemoryCache.js?71f3:194
DataStore.markMutationInit @ store.js?c582:54
QueryManager.mutate @ QueryManager.js?96af:67
ApolloClient.mutate @ ApolloClient.js?27b0:109
addTodo @ todo.js?b26b:33
wrappedActionHandler @ vuex.esm.js?2f62:721
dispatch @ vuex.esm.js?2f62:428
boundDispatch @ vuex.esm.js?2f62:322
handleAddTodo @ Add.vue?5f53:61
submit @ Add.vue?050c:24
invoker @ vue.runtime.esm.js?2b0e:2132
Vue.$emit @ vue.runtime.esm.js?2b0e:2652
submit @ VForm.js?4bd4:131
invoker @ vue.runtime.esm.js?2b0e:2132
fn._withTask.fn._withTask @ vue.runtime.esm.js?2b0e:1917
writeToStore.js?fa16:83 Missing field __typename in "5c61af544cc9be321870874e"
(anonymous) @ writeToStore.js?fa16:83
StoreWriter.writeSelectionSetToStore @ writeToStore.js?fa16:62
StoreWriter.writeFieldToStore @ writeToStore.js?fa16:161
(anonymous) @ writeToStore.js?fa16:70
StoreWriter.writeSelectionSetToStore @ writeToStore.js?fa16:62
(anonymous) @ writeToStore.js?fa16:224
StoreWriter.processArrayValue @ writeToStore.js?fa16:207
StoreWriter.writeFieldToStore @ writeToStore.js?fa16:141
(anonymous) @ writeToStore.js?fa16:70
StoreWriter.writeSelectionSetToStore @ writeToStore.js?fa16:62
StoreWriter.writeResultToStore @ writeToStore.js?fa16:40
InMemoryCache.write @ inMemoryCache.js?71f3:119
ApolloCache.writeQuery @ cache.js?10fe:30
update @ todo.js?b26b:44
(anonymous) @ store.js?c582:113
tryFunctionOrLogError @ errorHandling.js?c95d:3
(anonymous) @ store.js?c582:113
InMemoryCache.performTransaction @ inMemoryCache.js?71f3:185
DataStore.markMutationResult @ store.js?c582:112
changeFn_1 @ store.js?c582:45
(anonymous) @ store.js?c582:58
InMemoryCache.performTransaction @ inMemoryCache.js?71f3:185
InMemoryCache.recordOptimisticTransaction @ inMemoryCache.js?71f3:194
DataStore.markMutationInit @ store.js?c582:54
QueryManager.mutate @ QueryManager.js?96af:67
ApolloClient.mutate @ ApolloClient.js?27b0:109
addTodo @ todo.js?b26b:33
wrappedActionHandler @ vuex.esm.js?2f62:721
dispatch @ vuex.esm.js?2f62:428
boundDispatch @ vuex.esm.js?2f62:322
handleAddTodo @ Add.vue?5f53:61
submit @ Add.vue?050c:24
invoker @ vue.runtime.esm.js?2b0e:2132
Vue.$emit @ vue.runtime.esm.js?2b0e:2652
submit @ VForm.js?4bd4:131
invoker @ vue.runtime.esm.js?2b0e:2132
fn._withTask.fn._withTask @ vue.runtime.esm.js?2b0e:1917
writeToStore.js?fa16:83 Missing field _id in {
  "content": "fdsfsdf",
  "status": false,
  "createdAt": "1549983263371",
  "user": {
    "_id": 
`

this is my code:  

```
export const addTodo = ({ commit }, payload) => {
    commit('clearError');
    commit('setLoading', true);

    apolloClient.mutate({ 
        mutation: ADD_TODO,
        variables: payload,
        update: (cache, { data: { addTodo } }) => {
            const data = cache.readQuery({ query: GET_TODOS });
            data.getTodos.unshift(addTodo);
            cache.writeQuery({
                query: GET_TODOS,
                data
            });
        },
        optimisticResponse: {
            __typename: 'Mutation',
            addTodo: {
                __typename: 'Todo',
                _id: -1,
                ...payload
            }
        }
    })
    .then(() => {
        commit('setLoading', false);
        router.push('/todos');
    })
    .catch(err => {
        commit('setError', err);
        commit('setLoading', false);
    });
};
```

Please help me

**Comment by danilobuerger** [comment]
Issues here are reserved for bugs, but one of the following resources should help:

* Apollo Spectrum community: https://spectrum.chat/apollo
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests
