### ISSUE TITLE
startPolling behavior

### ISSUE THREAD

**Issue by doomsower** [apollographql/apollo-client#4439]
It took me some time to figure out that `ObservableQuery.startPolling()` doesn't fetch query right away. It uses `setInterval` internally, and it doesn't call function immediately, it only does so after first delay.

Currently I work around this issue using `result()`:
```ts
this._pollQuery = client.watchQuery({
  query: POLL_REGION_MEASUREMENTS,
  variables: { regionId: region.node.id },
  pollInterval,
  fetchPolicy: 'network-only',
});
// startPolling uses setInterval internally, therefore query is not fetched immediately
await this._pollQuery.result();
await this._pollQuery.startPolling(pollInterval);
```

I suppose I'm not the only person to be confused by this behavior. I'd like to add second optional parameter to `startPolling`, called `immediate` (or maybe `leading`, lodash.debounce-style). If this is desired feature, I can submit PR. If not, then maybe at least I can submit a docs PR with clarification.

**Comment by danilobuerger** [comment]
Per docs:
> This function sets up an interval in ms and fetches the query each time the specified interval passes.
https://www.apollographql.com/docs/react/essentials/queries.html

Personally, I think thats pretty clear its not immediate. But if you want to make it clearer or add a `immediate` (or similar) option, a PR is always welcome. Closing the issue here though, as its more a feature request.

**Comment by Sagaryalioe** [comment]
> It took me some time to figure out that `ObservableQuery.startPolling()` doesn't fetch query right away. It uses `setInterval` internally, and it doesn't call function immediately, it only does so after first delay.
> 
> Currently I work around this issue using `result()`:
> 
> ```ts
> this._pollQuery = client.watchQuery({
>   query: POLL_REGION_MEASUREMENTS,
>   variables: { regionId: region.node.id },
>   pollInterval,
>   fetchPolicy: 'network-only',
> });
> // startPolling uses setInterval internally, therefore query is not fetched immediately
> await this._pollQuery.result();
> await this._pollQuery.startPolling(pollInterval);
> ```
> 
> I suppose I'm not the only person to be confused by this behavior. I'd like to add second optional parameter to `startPolling`, called `immediate` (or maybe `leading`, lodash.debounce-style). If this is desired feature, I can submit PR. If not, then maybe at least I can submit a docs PR with clarification.

Sir where did you put your watchQuery? I put it in componentDidMount(). Will it not work?
