### ISSUE TITLE
InMemoryCache: Performance issue due to generated error message in diffQueryAgainstStore

### ISSUE THREAD

**Issue by mpoeter** [apollographql/apollo-client#4441]
`readQueryFromStore` calls `diffQueryAgainstStore`with `returnPartialData` set to false.
If the cache does not contain a result for the query, this results in an Error:
https://github.com/apollographql/apollo-client/blob/3530378496ca6ef01240cdc31df888c88c85bd92/packages/apollo-cache-inmemory/src/readFromStore.ts#L224-L232

This error is actually used to steer the control flow - e.g., `QueryManager.getCurrentQueryResult` relies on `read` to throw an error if no results are available yet. Am generally not a fan of exceptions being used for control flow, but the real problem is that the error message contains a stringified JSON of the _complete store_. In our case some queries can return rather big results. The effect is that the generated error message contains many thousand lines, causing a significant delay of up to a few seconds!

**Versions**
System: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)

npmPackages:
 * apollo-cache: ^1.1.25 => 1.1.25 
 * apollo-cache-inmemory: ^1.4.2 => 1.4.2 
 * apollo-client: ^2.4.12 => 2.4.12 
 * apollo-utilities: ^1.1.2 => 1.1.2

**Comment by benjamn** [comment]
In `apollo-cache-inmemory@1.5.x`, this exception [has become an `InvariantError`](https://github.com/apollographql/apollo-client/blob/fda77c22a43a472843954903b43bf875b2ed9d60/packages/apollo-cache-inmemory/src/readFromStore.ts#L229), which allows us to strip the message string in production, which should eliminate the runtime cost of the JSON serialization.

**Comment by mpoeter** [comment]
Thanks - I will give it a try and report back.

**Comment by mpoeter** [comment]
I can confirm that a production build with apollo-cache-inmemory 1.5.1 does not show this performance issue. :+1:
