### ISSUE TITLE
TypeError: Cannot set property 'defaultOptions' of undefined

### ISSUE THREAD

**Issue by BaoPham92** [apollographql/apollo-client#4442]
<img width="1045" alt="screen shot 2019-02-14 at 1 52 33 pm" src="https://user-images.githubusercontent.com/26471655/52810294-3b378a00-3060-11e9-8cf8-7ebea91f725e.png">

Following the guide from: https://www.howtographql.com/react-apollo/2-queries-loading-links/

Only completed the "Getting Started" up to "queries-loading-links" asking me to run the client side of that App for localhost:3000.

No adjustments made from the guide.

I searched and read the fixes to earlier related issues: https://github.com/apollographql/apollo-client/issues/4288

Everything is in correct order from there.

**Comment by vncastanheira** [comment]
I'm having the same problem, used the exact code from the docs: https://www.apollographql.com/docs/react/api/core/ApolloClient/#example-constructor-call

Tried reinstalling but didn't fixed the issue.
