### ISSUE TITLE
Cannot pass DateTime_gte variable to <Query />

### ISSUE THREAD

**Issue by ScottAgirs** [apollographql/apollo-client#4443]
**Describe the bug**
The component which contains `<Query />` keeps re-rendering when the `variables` are provided with `new Date().toISOString()` to myTime_gte field.

My <Query /> looks like this (sanitized for demo purposes)
```
<Query
          query={MY_TIME_QUERY}
          variables={{     
                      myTimeAt_gte: myTimeAt_gte          
           }}  
/ >
```

Currently tried:
_Case 1_ **[ FAILS ]** 
const myTimeAt_gte = new Date().toISOString()

_Case 2_ **[ FAILS ]** 
const timeNow = new Date()
const myTimeAt_gte = timeNow.toISOString()

_Case 3_ **[ WORKS FINE ]** 
const myTimeAt_gte = "2019-02-14T23:17:16.435Z"

Not sure if this is Prisma or Apollo Client related, really, though, it seemed to work all the while (even with simple `new Date()` function) and this just started happening recently.

In the database all is saved in this format: `2019-04-18T08:00:00.000Z`

**Intended outcome:**
To return data and render component

**Actual outcome:**
Infinite loop and doesn't really render the <Query /> itself (I'm assuming it stops at the "variables" part of <Query /> and re-render the wrapping component.

This is the browser console:
![image](https://user-images.githubusercontent.com/11737572/52824707-a5175a00-3087-11e9-93bc-2ff1da11908e.png)

This is the backend console:
![image](https://user-images.githubusercontent.com/11737572/52824712-ad6f9500-3087-11e9-8024-23667fb90b53.png)

**How to reproduce the issue:**

1. Create an Apollo Client  <Query /> and pass in a variable with new Date().toISOString()
2. Do initial load of the page
3. Navigate to another page with that <Query />

```
**Versions:**
 - Connector: [`MySQL`]
 - Prisma Server: [`1.27-beta-8` - eu1]
 - `prisma` CLI: [e.g. `prisma/1.25.0 (darwin-x64) node-v8.4.0`]
 - OS: [`OS X mojave`] 
 - other dependencies:  `prisma-binding` - ` "version": "2.1.6"`
```

`npx envinfo@latest --preset apollo --clipboard`
```
 System:
    OS: macOS 10.14
  Binaries:
    Node: 8.4.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.8.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Safari: 12.0
  npmPackages:
    apollo-boost: ^0.1.16 => 0.1.28
    apollo-client: ^2.4.2 => 2.4.13
    next-with-apollo: ^3.1.3 => 3.3.2
    react-apollo: ^2.2.1 => 2.4.1
```
-->

**Comment by ScottAgirs** [comment]
Can't believe that after all these months of learning, such a basic thing could have caused so much pain.

**### The solution:**
```
  constructor(props) {
    super(props);
    this.state = {
      startsAt_gte: new Date().toISOString(),
      images: [],
      largeImages: []
    };
  }
```

the new Date() is a function, which, if inside render() will trigger the component to re-render, lol

**Comment by ScottAgirs** [comment]
Unfortunately, this was not the solution.

While it worked for one component, in another one even putting the new Date().toISOString() into constructor(), still produces the same loop and prevents the page from loading.

Here is the full code (sanitised from the irrelevant):

```javascript
import React from 'react';

import gql from 'graphql-tag';
import { Query } from 'react-apollo';

import Loading from 'loading';
import Error from 'error';

const CLASSES_QUERY = gql`
  query CLASSES_QUERY($startsAt_gte: DateTime) {
    classes(where: { active: true }) {
      id 
      }
      sessions(where: { startsAt_gte: $startsAt_gte }) {
        id
        startsAt
      }
    }
  }
`;
class ClassList extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      startsAt_gte: new Date().toISOString()
    };
  }

  render() {
    const { startsAt_gte } = this.state;

    return (
      <>
        <Query
          query={CLASSES_QUERY}
          variables={{ startsAt_gte: startsAt_gte }}
        >
          {({ data, loading, error }) => {
            if (loading) return <Loading />;
            if (error) return <Error />;

            return (
              <div>
                <div>
                  {data.classes.map(cls => {
                    return (
                      <div>
                        <h2>{cls.title}</h2>
                        {cls.sessions.map(ses => {
                          return <div>{ses.startsAt}</div>;
                        })}
                      </div>
                    );
                  })}
                </div>
              </div>
            );
          }}
        </Query>
      </>
    );
  }
}

export default ClassList;
```

**Comment by danilobuerger** [comment]
Please provide a fully reproducible sample repos.

**Comment by shih-js** [comment]
Any update on this? I am running into the same issue on production. Works fine in development on localhost.

**Comment by hwillson** [comment]
We haven’t heard back regarding a reproduction, so we’ll close this off for now. Thanks!
