### ISSUE TITLE
[apollo-cache-inmemory] Cannot update stored File object value

### ISSUE THREAD

**Issue by jhpedemonte** [apollographql/apollo-client#4445]
We're storing a native `File` object client-side-only (with apollo-link-state):

```javascript
const FILE_INFO_TYPEDEFS = [
  `scalar File

  input FileInfo {
    file: File!
    private: Boolean!
  }`,
];

export const FILE_INFO_QUERY = gql`
  query fileInfos {
    fileInfos @client {
      file
      private
    }
  }
`;

export const FILE_INFO_MUTATION = gql`
  mutation setFileInfo($fileInfos: [FileInfo]) {
    setFileInfo(fileInfos: $fileInfos) @client
  }
`;
```

To set or update, we call:

```javascript
  cache.writeQuery({
    query: FILE_INFO_QUERY,
    data,
  });
```

This was all working fine until we recently updated our Apollo dependencies. Then, setting a 2nd file would no longer work.

I was able to trace it to the [`isEqual`](https://github.com/apollographql/apollo-client/blob/4ef46332871be10b386a77ba6ac1217d64af1cf9/packages/apollo-utilities/src/util/isEqual.ts) function in `apollo-utilities`. For `File` objects, the `hasOwnProperties` calls return false, so `isEqual` will determine that _any_ two `File` objects are identical.

Our code broke because of the following change from [Sept 27](https://github.com/apollographql/apollo-client/commit/6809e3d3672bb7c4715801770519e24146ab4709#diff-031bdcf5e26921003e73f56f47c61bc7):

```diff
-    if (!storeObject || storeValue !== storeObject[storeFieldName]) {
+    if (!storeObject || !isEqual(storeValue, storeObject[storeFieldName])) {
```

**Intended outcome:**

I can store native `File` objects client-side using `apollo-link-state` and `apollo-cache-inmemory`.

**Actual outcome:**

Can only store first `File` object. Afterwards, no additional `File` objects are stored, since they are considered equal.

**How to reproduce the issue:**

See above.

**Versions**

```
  System:
    OS: macOS 10.14.3
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.13.0 - ~/.nvm/versions/node/v10.15.0/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Browsers:
    Chrome: 72.0.3626.109
    Safari: 12.0.3
  npmPackages:
    apollo-storybook-react: 0.1.8 => 0.1.8 
    apollo-utilities: 1.1.2 => 1.1.2 
    react-apollo: 2.4.1 => 2.4.1 
```

also:

```
    apollo-cache-inmemory: 1.4.2
    apollo-client: 2.4.12
```

**Comment by jhpedemonte** [comment]
A workaround is to set an own-prop on the `File` object, such that the `isEqual` call will return false. For example:

```javascript
file._timestamp = Date.now();
```

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
