### ISSUE TITLE
Apollo client angular - InMemoryCache,

### ISSUE THREAD

**Issue by nikjeni** [apollographql/apollo-client#4454]
Hi guys,
I am using Apollo client with graphQl as the backend for my angular  project.

i have following data in my cache
1) screenshot 1
![screen shot 1](https://user-images.githubusercontent.com/35194097/52900953-fad43980-3222-11e9-9b87-d6ba871170a1.png)

2) when I use the below query to read cached data then it is showing an error

ngOnInit() {
    const todo = this.apollo.getClient().readQuery({
      query: gql`
        query getArticleById($id: String!) {
          article(id: $id) {
            id
            title
            content
            published
          }
        }
      `,
      variables: {
        id: "2"
      }
    });
    console.log(todo);
  }

![screen shot 2](https://user-images.githubusercontent.com/35194097/52901015-9665aa00-3223-11e9-93f7-0de8d6bc2162.png)

3) i also configured app.module like below
export class AppModule {
  constructor(apollo: Apollo, httpLink: HttpLink) {
    apollo.create({
      link: httpLink.create({ uri: "http://localhost:3000/graphql" }),
      cache: new InMemoryCache({
        cacheRedirects: {
          Query: {
            article: (_, { id }, { getCacheKey }) =>
              console.log(id, getCacheKey),
             getCacheKey({ __typename: "article", id: id })
          }
        }
      })
    });
  }
}

4) It is hitting to app.module where I mentioned console log but not returning requested value back with read query method.

Thanks in advance.. please provide me solution

**Comment by danilobuerger** [comment]
Issues here are reserved for bugs, but one of the following resources should help:

* Apollo Spectrum community: https://spectrum.chat/apollo
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests
