### ISSUE TITLE
Arrays keep previous items after refetch when a client property is included

### ISSUE THREAD

**Issue by NickClark** [apollographql/apollo-client#4474]
**Intended outcome:**
I expect, when refetching, to get the latest data as it comes from the server, but with my added client attributes

**Actual outcome:**
Currently, with the latest beta, this is broken. When loading data with new elements, they tend to be persisted.

**How to reproduce the issue:**
I've made a simple server and client here:

Server: 
[![Edit Apollo Beta broken client state](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l3n7rk552z)

Client:
[![Edit Apollo Beta broken client state](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l3n7rk552z)

**Versions**
Apollo Client 2.5.0-beta.1

**Comment by NickClark** [comment]
As a side note. I would expect this to be a blocker for 2.5 release, since this is just basic usage and a regression from previous versions

**Comment by hwillson** [comment]
Thanks for reporting this @NickClark. We've noticed this as well, and will have it fixed before 2.5 is released.

**Comment by hwillson** [comment]
@NickClark This should now be fixed using the latest Apollo Client / React Apollo RC's (`apollo-client@next` and `react-apollo@next`). Thanks!
