### ISSUE TITLE
No way to write custom links for resolving @client selections

### ISSUE THREAD

**Issue by mbrowne** [apollographql/apollo-client#4476]
I was trying to write a custom link that could be used in combination with the `@client` directive using apollo-client 2.5 beta and discovered that it seems to be impossible due to the way the `@client` directive is now handled internally.

**Intended outcome:**

I was trying to create a custom directive `@persistAcrossSessions` that I could use to indicate certain selection sets that should be persisted in localStorage and restored when the app is reopened. I'd like my custom directive to work with both `@client` queries/selection sets and server queries.

**Actual outcome:**

When I write a custom link for that, it works for server queries but not for `@client` queries. By the time my link is called, apollo-client has already stripped out the `@client` part and resolved it.

I realize this behavior is by design, and I'm glad that local state has been integrated into the core of apollo-client, but it seems like it would be good to have some sort of hook to handle scenarios like this.

**How to reproduce the issue:**

```js
const cache = new InMemoryCache()

// Never called
const link = new ApolloLink((operation, forward) => {
    console.log(`starting request for ${operation.operationName}`)
    return forward(operation).map(data => {
        console.log(`ending request for ${operation.operationName}`)
        return data
    })
})

const client = new ApolloClient({
    cache,
    link,
})

cache.writeData({
    foo: {
        __typename: 'foo',
        name: 'foo'
    },
})

client.query({
    query: gql`
        {
            foo @client @testCustomDirective {
                name
            }
        }
    `
})
```

**Versions**

```
  System:
    OS: macOS 10.14.2
  Binaries:
    Node: 10.10.0 - /usr/local/bin/node
    Yarn: 1.12.1 - ~/.yarn/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 72.0.3626.109
    Firefox: 64.0.2
    Safari: 12.0.2
  npmPackages:
    apollo-cache-inmemory: ^1.4.2 => 1.4.3
    apollo-cache-persist: ^0.1.1 => 0.1.1
    apollo-client: 2.5.0-beta.1 => 2.5.0-beta.1
    apollo-link: ^1.2.6 => 1.2.8
    apollo-link-http: ^1.5.11 => 1.5.11
    react-apollo: ^2.4.0 => 2.4.1
```

**Related**

I was thinking that a `@persistAcrossSessions` custom directive might be an alternative (and possibly better) way to handle my use case than what I described in #4469.

**Comment by mbrowne** [comment]
After thinking about this a bit more, I realized that a better place to specify which objects/fields should be persisted would be in the schema (if there were a feature to do that). Otherwise it could get a little ambiguous with some queries/mutations including the directive and others not. But writing custom links that resolve `@client` selections still seems like it could be useful for other reasons. The plugin system @hwillson mentioned at https://github.com/apollographql/apollo-client/pull/4361#issuecomment-466115568 sounds like it could be a great solution for this longer-term.

**Comment by Aleksion** [comment]
I would like to add to that. I was trying to implement a solution for handling side effects for both local and external mutations, but can't seem to figure out a good way to do that due to the limitation of local mutations not passing through the link chain.

**Comment by hwillson** [comment]
We no longer recommend/support using `@client` in links. Please refer to our updated [local state](https://www.apollographql.com/docs/react/local-state/local-state-management/) docs for new ways of handling similar functionality. Thanks!
