### ISSUE TITLE
Apollo Client reports "Number expected" and stops running in IE11

### ISSUE THREAD

**Issue by tamouse** [apollographql/apollo-client#4478]
**Intended outcome:**

Use of Apollo React client in our app, running on IE11.

I've created a minimal repository that demonstrates the problem:

https://github.com/tamouse/apollo-coinbase-client-showing-ie11-error

There is no special code, particularly. The app pulls in polyfills for IE11 from https://polyfill.io, which is in the `public/index.html` file in the repo.

**Actual outcome:**

The console reports the error "Number expected":

![console-showing-error](https://user-images.githubusercontent.com/363583/53143659-997fd380-355e-11e9-999d-31e36a5daa0f.jpg)

The debugger reports the following line as the source of the error:

![debug-showing-error-reporting-line](https://user-images.githubusercontent.com/363583/53143678-ad2b3a00-355e-11e9-866e-d90bf88ad43f.jpg)

**How to reproduce the issue:**

See demo repo at https://github.com/tamouse/apollo-coinbase-client-showing-ie11-error

**Versions**

```
$ npx envinfo@latest --preset apollo --clipboard
npx: installed 1 in 0.888s

  System:
    OS: macOS 10.14.3
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 72.0.3626.109
    Firefox: 63.0.3
    Safari: 12.0.3
  npmPackages:
    apollo-boost: ^0.1.28 => 0.1.28 
    react-apollo: ^2.4.1 => 2.4.1 
```

**Comment by tamouse** [comment]
A running demo is at http://confused-cap.surge.sh/

**Comment by samboylett** [comment]
Are you using any polyfills for IE11? I had this issue but fixed it by disabling the polyfill.io `Map` polyfill.

**Comment by tamouse** [comment]
@samboylett this is my polyfill line: https://github.com/tamouse/apollo-coinbase-client-showing-ie11-error/blob/master/public/index.html#L40 using this link:

    https://polyfill.io/v3/polyfill.js?features=es5,es6,es7,fetch,promise,Symbol&flags=gated

Should I add `Map` after `Symbol`?

**Comment by samboylett** [comment]
Yeah. Basically the Map.prototype.set polyfill is doing 1/key, and if the key is Object.create(null) it will throw "Number expected" in IE11. 

```			// 6. If key is -0, let key be +0.
			if (1/key === -Infinity) {
				key = 0;
			}```

It looks like this is fixed in the latest version of polyfill-library, but it's yet to be pushed to polyfill.io

My temporary solution was to only polyfill exactly what I needed: `https://polyfill.io/v3/polyfill.min.js?flags=gated&features=Object.entries,Object.assign`. Luckily IE11 supports Map anyway

**Comment by tamouse** [comment]
thank you, @samboylett , I think this closes the issue
