### ISSUE TITLE
Reading array of objects from local state returns empty array

### ISSUE THREAD

**Issue by booboothefool** [apollographql/apollo-client#4486]
Am using `"apollo-client": "^2.4.13"`.

I noticed I cannot read objects from the local state.

For example If I did:
```
await this.props.client.mutate({
            mutation: gql`
mutation UpdateFilterMutation($input: NotUsed) {
        updateFilter(input: $input) @client
    }
`,
            variables: {
                input: {
                    someInt: 1,
                    someString: 'hello',
                    someArrayOfInts: [1,2,3],
                    someArrayOfObjects: [{ id: 1 }, { id: 2 }],
                },
            },
        });
```

and I read it back:
```
await this.props.client.query({
            query: gql`
 query FilterQuery {
        filter @client {
            someInt
            someString
            someArrayOfInts
            someArrayOfObjects { id }
        }
}
`,
        });
```
Everything returns correctly besides `someArrayOfObjects` which ends up empty `[]`.

I have been using a workaround where I store it as a JSON string and then parse it back into an object where needed, but was wondering if I'm just missing something and there is support for this.

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
