### ISSUE TITLE
changing variables doesn't trigger query refetch, after SSR

### ISSUE THREAD

**Issue by lotsoftick** [apollographql/apollo-client#4489]
here is the code example:
button clicking supposed to fetch new data with the changed variables, but it does't refetch anything (page has been rendered by server). Isn't this an issue ?

```
...
render() {
...
return (
  <button type="button" onClick={() => this.setState({ filter: Math.random() })}{this.state.filter}</button>
  <Query query={query} variables={{ filter: this.state.filter }}>
    {({ loading, error, data }) => { ... }}
  </Query>
)
...
}
```

client:
```
const client = new ApolloClient({
  cache: new InMemoryCache().restore(window.__APOLLO_STATE__),
  link: createHttpLink({
    uri: 'https://countries.trevorblades.com/',
  }),
  defaultOptions: {
    query: {
      fetchPolicy: 'network-only',
      errorPolicy: 'all',
    },
  },
  ssrForceFetchDelay: 200,
});
```

**Comment by pl12133** [comment]
It looks like your client is using `cache-first` network policy and that would not result in a network request happening here.

The `<Query>` component uses `watchQuery`, see the NOTE in this section https://www.apollographql.com/docs/react/api/apollo-client.html#apollo-client:

> Note: The React Apollo <Query /> component uses Apollo Client’s watchQuery functionality, so if you would like to set defaultOptions when using <Query />, be sure to set them under the defaultOptions.watchQuery property.

So try using `defaultOptions.watchQuery` instead of `defaultOptions.query`:

```js
  defaultOptions: {
    watchQuery: {
      fetchPolicy: 'network-only',
      errorPolicy: 'all',
    },
  },
```

**Comment by lotsoftick** [comment]
@pl12133 thanks, but it didn't help.
```
defaultOptions: {
    watchQuery: {
      fetchPolicy: 'network-only',
      errorPolicy: 'all',
    },
    query: {
      fetchPolicy: 'network-only',
      errorPolicy: 'all',
    },
  }
```

it works when the value of ssrForceFetchDelay is 0  or less than 50. But this is not an option due to request is sent both on the server and on client

**Comment by lterfloth** [comment]
Having the same issue. Setting ssrForceFetchDelay to 50 or lower makes everything work, but is not really an option.

**Comment by its-wufu** [comment]
Having the same issue. Also posted that on stackoverflow, but this seems to be a bug then ( https://stackoverflow.com/questions/57148364/apollo-refetch-query-component-with-new-variables )

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
