### ISSUE TITLE
A tuple type element list cannot be empty , apollo-utilities error

### ISSUE THREAD

**Issue by chennas** [apollographql/apollo-client#4501]
Hello Team

We are getting the build issue in Jenkins, please see the screen shot below.

![image](https://user-images.githubusercontent.com/8044128/53445961-6793c480-39d7-11e9-998d-4535906ba490.png)

We are using the following apollo utilities as shown below.
![image](https://user-images.githubusercontent.com/8044128/53446101-b7728b80-39d7-11e9-8488-19593f20567c.png)

**Comment by benjamn** [comment]
Out of curiosity, what version of the `typescript` npm package are you using? It's surprising that this got past our type-checking, since `mergeDeep` has [a bunch of tests](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-utilities/src/util/__tests__/mergeDeep.ts).

**Comment by chennas** [comment]
Hi Benjamn

we are using 2.8.4 

Please see the below screen shot

![image](https://user-images.githubusercontent.com/8044128/53448728-b9d7e400-39dd-11e9-92ec-a6a0d78cf7b9.png)

![image](https://user-images.githubusercontent.com/8044128/53448805-e8ee5580-39dd-11e9-9113-6a07fe158ddf.png)

**Comment by chennas** [comment]
Hello Team,

Now we are getting this error.

![image](https://user-images.githubusercontent.com/8044128/53516680-78554080-3a92-11e9-9af8-8bb45ee905eb.png)

**Comment by benjamn** [comment]
Do you have the ability to update to `typescript@3.x`? Support for tuple-typed rest parameters was added in TypeScript 3.0: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#rest-elements-in-tuple-types

**Comment by benjamn** [comment]
You might also try updating the Angular CLI, since they updated to TypeScript 3.0.1 in version 7.0.0: https://github.com/angular/angular-cli/commit/88804b63dc4380be087b2b41c3372f69075640a6

**Comment by chennas** [comment]
Hello Benjamn,

I got fixed by upgrading the below.

*Typescript* upgraded to  3.1.1 and *angular-compiler-cli* upgraded to 7.2.7

Thanks for the help

**Comment by benjamn** [comment]
@chennas Awesome, I'm very glad to hear you had the option to upgrade, and that it solved the problem!
