### ISSUE TITLE
Update docs regarding Mutation component update

### ISSUE THREAD

**Issue by chrisdrackett** [apollographql/apollo-client#4505]
The docs here:

https://www.apollographql.com/docs/react/essentials/mutations.html#update

specify `{data: { addTodo }}` but my understanding is that data can also be undefined so this is incorrect. I'm not 100% sure what the correct usage should be (this is actually what I was looking for in the docs!)

Sorry if this isn't where docs update requests should go, but I wasn't sure the best place to put this.

**Comment by hwillson** [comment]
The docs have been updated - thanks!
