### ISSUE TITLE
Error: "Apollo has been already created."

### ISSUE THREAD

**Issue by vlad57** [apollographql/apollo-client#4542]
Hi guys, 

I'm working with Angular 7 and Apollo. But I have a problem when I'm trying to set a token in the header. Error: "Apollo has been already created."

I followed instruction as it said in this link: https://www.apollographql.com/docs/angular/recipes/authentication.html#Header

This is my file : **app.module.ts** :

`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import {ApolloModule, APOLLO_OPTIONS, Apollo} from 'apollo-angular';
import { HttpLinkModule, HttpLink } from 'apollo-angular-link-http';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { setContext } from 'apollo-link-context';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { ConnexionComponent } from './login/connexion/connexion.component';
import { GraphQLModule } from './graphql.module';
import { HttpClientModule } from '@angular/common/http';

@NgModule({
  declarations: [
    AppComponent,
    ConnexionComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    GraphQLModule,
    HttpClientModule,
    ApolloModule,
    HttpLinkModule
  ],
  providers: [{
    provide: APOLLO_OPTIONS,
    useFactory(httpLink: HttpLink) {
      return {
        cache: new InMemoryCache(),
        link: httpLink.create({
          uri: 'http://localhost:4000'
        })
      };
    },
    deps: [HttpLink]
  }],
  bootstrap: [AppComponent]
})
export class AppModule {
  constructor(
    apollo: Apollo,
    httpLink: HttpLink
  ) {
    const http = httpLink.create({uri: 'http://localhost:4000'});

    const auth = setContext((_, { headers }) => {
      // get the authentication token from local storage if it exists
      //const token = localStorage.getItem('token');
      const token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjanN3NjNzb28wMDNmMDcyNmMydjFjcDdlIiwiaWF0IjoxNTUxODE0MTk1fQ.x1cnqBeWDazmWAZXWhXr2GGJgbYRETzlsEy-QzS5DsY';
      // return the headers to the context so httpLink can read them
      // in this example we assume headers property exists
      // and it is an instance of HttpHeaders
      if (!token) {
        return {};
      } else {
        return {
          headers: headers.append('Authorization', `Bearer ${token}`)
        };
      }
    });

    apollo.create({
      link: auth.concat(http),
      cache: new InMemoryCache()
    });
  }
}`

This is my file **connexion.component.ts**
`
const amIAuth = gql`
  query amIAuth{
    amIAuth {
      isAuth
    }
  }
`;

@Component({
  selector: 'app-connexion',
  templateUrl: './connexion.component.html',
  styleUrls: ['./connexion.component.css']
})

export class ConnexionComponent implements OnInit {
  loading: boolean;
  allFilms: [];
  amIAuthRes;

  private querySubscription: Subscription;
  constructor(private apollo: Apollo) { }

  ngOnInit() {
    // @ts-ignore
    this.querySubscription = this.apollo.watchQuery<any>({
      query: amIAuth
    })
      .valueChanges
      .subscribe(({ data, loading }) => {
        this.loading = loading;
        this.amIAuthRes = data.amIAuth.isAuth;
      });
  }

}
`
PS: I put my valid token to try if it works or not.

Thank you,

Regards

**Comment by benjamn** [comment]
Please don't include personal tokens in public GitHub issues! I'm going to delete this issue because that's the only way to remove the token from the edit history, but feel free to open another issue without sensitive information.

When you create a new issue, instead of copy/pasting your code into the issue description, please create a runnable reproduction based on this [template](https://github.com/apollographql/react-apollo-error-template).

See https://github.com/apollographql/apollo-client/blob/master/CONTRIBUTING.md#reporting-bugs for more information about reporting issues.
