### ISSUE TITLE
Error: "Apollo has been already created."

### ISSUE THREAD

**Issue by vlad57** [apollographql/apollo-client#4545]
Hi Guys, 

I'm working with Angular 7 and Apollo. I have un problem with the implementation of the token with the header. It says : Error: "Apollo has been already created."

I followed this link : https://www.apollographql.com/docs/angular/recipes/authentication.html#Header

This is my file **app.module.ts** 

`@NgModule({
  declarations: [
    AppComponent,
    ConnexionComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    GraphQLModule,
    HttpClientModule,
    ApolloModule,
    HttpLinkModule,
  ],
  providers: [{
    provide: APOLLO_OPTIONS,
    useFactory(httpLink: HttpLink) {
      return {
        cache: new InMemoryCache(),
        link: httpLink.create({
          uri: 'http://localhost:4000'
        })
      };
    },
    deps: [HttpLink]
  }],
  bootstrap: [AppComponent]
})
export class AppModule {
  constructor(
    apollo: Apollo,
    httpLink: HttpLink
  ) {
    const http = httpLink.create({uri: 'http://localhost:4000'});

    const auth = setContext((_, { headers }) => {
      // get the authentication token from local storage if it exists
      //const token = localStorage.getItem('token');
      const token = 'my_token';
      // return the headers to the context so httpLink can read them
      // in this example we assume headers property exists
      // and it is an instance of HttpHeaders
      if (!token) {
        return {};
      } else {
        return {
          headers: headers.append('Authorization', `Bearer ${token}`)
        };
      }
    });

    apollo.create({
      link: auth.concat(http),
      cache: new InMemoryCache()
    });
  }
}
`
And this is connexion.component.ts

`const amIAuth = gql`
  query amIAuth{
    amIAuth {
      isAuth
    }
  }
`;

@Component({
  selector: 'app-connexion',
  templateUrl: './connexion.component.html',
  styleUrls: ['./connexion.component.css']
})

export class ConnexionComponent implements OnInit {
  loading: boolean;
  amIAuthRes;

  private querySubscription: Subscription;
  constructor(private apollo: Apollo) { }

  ngOnInit() {
    // @ts-ignore
    this.querySubscription = this.apollo.watchQuery<any>({
      query: amIAuth
    })
      .valueChanges
      .subscribe(({ data, loading }) => {
        this.loading = loading;
        this.amIAuthRes = data.amIAuth.isAuth;
      });
  }

}`

Thanks,

**Comment by benjamn** [comment]
Do you have a stack trace for the error?

**Comment by vlad57** [comment]
I solved the problem thanks to this link : 

https://stackblitz.com/edit/simple-apollo-angular-example-headers

Very usefull !

Instead of place setContext in app.module.ts, place it in graphql.module.ts like in the example of the link.
