### ISSUE TITLE
Fragment objects can't be null in 2.5?

### ISSUE THREAD

**Issue by anazar** [apollographql/apollo-client#4546]
Previously using apollo-link-state we were able to do:

```
user {
  address {
    ...addressFields
  }
}
```

We are passing a null address from the server into a client currentUser object and then doing readQuery on currentUser.

However, now if we do readQuery and address is null we get the following error: 
`Invariant Violation: Can't find field __typename on object undefined`

It seems to be requiring address to be an object of `__typename: Address` now instead of allowing address to be null.

I have also tried specifically setting the typeDef like so:

```
const typeDefs = gql`
  extend type User {
    address: Address
  }
`
```

Which didn't work either.

Is this a bug in 2.5 or is there a workaround or other solution that I'm not aware of?

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
