### ISSUE TITLE
ApolloError adds object to error string making "GraphQL error: [object Object]"

### ISSUE THREAD

**Issue by kylepaulsen** [apollographql/apollo-client#4547]
Related code: https://github.com/apollographql/apollo-client/blob/12bd15ffcee0ec672e7ec8461eaa90466e2d5971/packages/apollo-client/src/errors/ApolloError.ts#L19

**Intended outcome:**
It's not very useful to have [object Object] come back as an error string. Maybe check to see if you can JSON.stringify it first and return that string instead.

**Actual outcome:**
Errors that have objects as messages come back as "GraphQL error: [object Object]"

**How to reproduce the issue:**
Have a graphql server return an error message as an object. If this is not a good pattern, how else can we supply object shaped data as an error? Sure, we could stringify it, but then to do something with it, we would need to parse it after we remove that "GraphQL error:" part.

**Versions**
latest,
2.4.6

**Comment by OurMajesty** [comment]
There is PR, which scheduled for Apollo 3.0, if I'm right:
#3892

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
