### ISSUE TITLE
Updating link after queryManager is created doesn't work.

### ISSUE THREAD

**Issue by Waitak** [apollographql/apollo-client#4555]
**Intended outcome:**
I'm attempting to add middleware/afterware to an existing client, by doing something like:

    const client = apollo.getClient();
    client.link = newLink.concat(client.link);

The intended outcome is that the new middleware/afterware be added to the chain, and fire when a query is executed.

**Actual outcome:**
Changing `ApolloClient.link` works, but has no effect once a query has fired. My guess is that this is because the `QueryManager.link` created when `ApolloClient.initQueryManager` is called, is not updated. 

**How to reproduce the issue:**

Here is an [illustrative (non-functional) minimal example](https://jsfiddle.net/u6nbx02k/ ) using an Angular module. The output to the console here would be:

- Fired middleware first
- Fired afterware second

The desired and expected output would be:

- Fired middleware first
- Fired middleware third
- FIred afterware fourth
- Fired afterware second

**Versions**

```
npx: installed 1 in 1.451s

  System:
    OS: Linux 4.4 Ubuntu 16.04.6 LTS (Xenial Xerus)
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.13.0 - ~/Projects/doozee-dev/frontend/doozee-frontend/node_modules/.bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: 65.0.1
  npmPackages:
    apollo: ^2.5.3 => 2.5.3 
    apollo-angular: ^1.5.0 => 1.5.0 
    apollo-cache-inmemory: ^1.5.1 => 1.5.1 
    apollo-client: ^2.5.1 => 2.5.1 
    apollo-codegen: ^0.20.2 => 0.20.2 
    apollo-link: ^1.2.8 => 1.2.8 
    apollo-link-context: ^1.0.14 => 1.0.14 
    apollo-link-error: ^1.1.7 => 1.1.7 
    apollo-link-http: ^1.5.11 => 1.5.11

```

**Comment by eric-burel** [comment]
Hi, this feature is useful to create package oriented app where all links may not be known during app creation.

**Comment by hwillson** [comment]
`@apollo/client` now supports this. See https://github.com/apollographql/apollo-client/pull/6193 for details. Thanks!
