### ISSUE TITLE
www.apollographql.com not resolved from Russia

### ISSUE THREAD

**Issue by Fi1osof** [apollographql/apollo-client#4556]
IP 206.51.242.1 blocked from Russia.
Check: http://blocklist.rkn.gov.ru/#anchor

**Comment by jasonpaulos** [comment]
Hi @Fi1osof, thanks for reporting this! I believe this has now been fixed, but please let us know if there are any other issues.

**Comment by Fi1osof** [comment]
@jasonpaulos, thanks!
