### ISSUE TITLE
[Cache] all fragments in objects after the first adopt the typename of the first object's fragment

### ISSUE THREAD

**Issue by timmywil** [apollographql/apollo-client#4566]
**Intended outcome:**

The intended outcome is a successful write to the cache without errors/warnings.

**Actual outcome:**

I'm using a union type and fragments. Writing the list with one object is fine, even when the resolved type varies. But as soon as I add a second object with a different type for the fragment, it blows up. The write is unsuccessful with the message "Missing field [fieldName] in [fragment]", but that fieldName does not apply to the second object's fragment, only the first. Writing objects with fragments seems to only be an issue when writing to the cache.

**How to reproduce the issue:**

Open https://codesandbox.io/s/00n3l30zzp and see console.

**Versions**

```
  System:
    OS: macOS 10.14.3
  Binaries:
    Node: 8.14.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 72.0.3626.119
    Firefox: 65.0.1
    Safari: 12.0.3
  npmPackages:
    apollo-cache-inmemory: ^1.5.1 => 1.5.1
    apollo-client: ^2.5.1 => 2.5.1
    apollo-link: ^1.2.9 => 1.2.9
    apollo-link-error: ^1.1.8 => 1.1.8
    apollo-link-http: ^1.5.12 => 1.5.12
    react-apollo: ^2.4.1 => 2.5.2
```

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
