### ISSUE TITLE
Apollo Client Field Resolution

### ISSUE THREAD

**Issue by tylerbuchea** [apollographql/apollo-client#4567]
I am using Apollo Client 2.5 with local state and trying to return a class from the resolvers but it appears that Apollo Client doesn't resolve the returned fields if they are methods/functions. I've demonstrated below what I'm talking about.

This same schema and resolver setup works fine in Apollo Server and I'm curious if this will be supported in Apollo Client local state? Or maybe it does work and there is something I'm doing wrong with the setup?

Here is a link to the same code in a Codesandbox [https://codesandbox.io/s/n4rom4jkpp](https://codesandbox.io/s/n4rom4jkpp)

This code should output `{"user":{"name":"Tyler","nameLength":5,"__typename":"User"}}`
But instead it is outputing: `{"user":{"name":"Tyler","__typename":"User"}}`

You'll see it is missing the nameLength field as that field is a method on the User class and not a static value.

```js
import React from "react";
import ReactDOM from "react-dom";
import { ApolloClient } from "apollo-client";
import { InMemoryCache } from "apollo-cache-inmemory";
import { ApolloProvider, Query } from "react-apollo";
import gql from "graphql-tag";

function App() {
  const GET_USER = gql`
    query getUser {
      user @client {
        name
        nameLength
      }
    }
  `;

  const render = ({ loading, error, data }) => {
    if (loading) return <h4>Loading...</h4>;
    if (error) return <h4>Error...</h4>;
    return <div className="App">{JSON.stringify(data)}</div>;
  };

  return <Query query={GET_USER}>{render}</Query>;
}

class User {
  constructor({ name }) {
    this.__typename = "User";
    this.name = name;
  }

  nameLength() {
    return this.name.length;
  }
}

const client = new ApolloClient({
  cache: new InMemoryCache(),
  resolvers: {
    Query: {
      user: () => new User({ name: "Tyler" })
    }
  },
  typeDefs: gql`
    type Query {
      user: User
    }
    type User {
      name: String
      nameLength: Int
    }
  `
});

ReactDOM.render(
  <ApolloProvider client={client}>
    <App />
  </ApolloProvider>,
  document.getElementById("root")
);
```

**Comment by volkanunsal** [comment]
I managed to reproduce this as well. The only way to make the resolvers work is by removing the `typeDef`.

**Comment by benjamn** [comment]
@tylerbuchea I think it might be possible for the cache to detect this use case and do something more reasonable.

When a resolver returns a class instance, the cache could easily detect that the object has a custom prototype (not `Object.prototype` or `null`). If the cache treated such custom-prototype objects as opaque values, and did not attempt to normalize them, then we wouldn't lose the custom prototype during normalization.

If custom-prototype objects are treated as opaque data, then they lose the benefits of normalization, so (for example) you could end up with multiple `User` instances in the cache that represent the same user.

Perhaps that tradeoff would be acceptable?

**Comment by benjamn** [comment]
On second thought, I'm not sure I understand how the `nameLength` method of the `User` class is supposed to get called in this example. Did you mean for it to be a getter?

Also, in your example, `JSON.stringify(data)` would strip all method properties from `data` even if Apollo Client/Cache managed to preserve them.

In short, despite my earlier enthusiasm, I don't think treating `User` objects as opaque data in the cache would make your example work.

Instead of a `nameLength` method, perhaps you could define a `User.nameLength` resolver function, implemented in terms of the `data` parameter (the first resolver parameter, which in this case represents the user object, even if it doesn't currently inherit from `User.prototype`).

**Comment by tylerbuchea** [comment]
Hey, benjamn thanks for the replies. I think I already ended up doing what you suggested in your last paragraph:

```jsx
resolvers: {
    User: {
        nameLength: parent => parent.name.length
    },
    Query: {
      user: () => new User({ name: "Tyler" })
    }
  },
```

You can try my original code with `nameLength` as a getter but that breaks it even more.

This is no longer an issue for me, but I guess my original point was it's strange that my class resolver methods work in apollo-server but not with Apollo Local State. If that provides any value for you or the team then great if not then feel free to close the issue.

**Comment by hwillson** [comment]
Sounds like this was resolved - closing, thanks!
