### ISSUE TITLE
fetchMore, no data while loading

### ISSUE THREAD

**Issue by Zik42** [apollographql/apollo-client#4574]
**Intended outcome:**
I have component like this
```
        <Query query={getQuery} notifyOnNetworkStatusChange variables={{ limit: 10 }} forceFetch>
          {args => {
            const { data, loading, error,  fetchMore, networkStatus } = args;
           return (
              <div style={{ height: 'calc(100vh - 136px)', overflow: 'auto' }}>
                 <InfiniteScroll
                  loadMore={page => {
                    fetchMore({
{
              variables: {
                offset: data.cableSegments.edges.length,
              },
              updateQuery: (prev, { fetchMoreResult }) => {
                if (!fetchMoreResult || !fetchMoreResult.cableSegments.edges) return  prev;
                return Object.assign({}, prev, {
                  cableSegments: {
                    ...fetchMoreResult.cableSegments,
                    edges: [...prev.cableSegments.edges, ...fetchMoreResult.cableSegments.edges],
                  },
                });
              },
            }})
                  }}
                  hasMore={networkStatus === 7 && getHasMore(data)}}> 
              
                    <ListTable
                      data={getDataForTable(data)}
                      loading={loading}
                      columns={getTableColumns({ data })}/>
       
                </InfiniteScroll> 
              </div>
            );
          }}
        </Query>
```

**Actual outcome:**
This is output of console. When I trigger once fetchMore, fist - netWorkStatus, last - loading status.
![image](https://user-images.githubusercontent.com/20891802/54287096-b59af180-45ad-11e9-89a3-0471eee92a18.png). 

It triggers  2 times ready status and data actually arrives at second. Actually it works without 
 notifyOnNetworkStatusChange. But I need to be able catch refetch status.

Here in my case, hasMore returns true while data has not come, that`s next fetchMore goes with wrong variable

**Versions**

  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
  Binaries:
    Node: 10.5.0 - ~/.nvm/versions/node/v10.5.0/bin/node
    Yarn: 1.7.0 - ~/.nvm/versions/node/v10.5.0/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v10.5.0/bin/npm
  Browsers:
    Chrome: 70.0.3538.77
    Firefox: 65.0.1
  npmPackages:
    apollo-cache-inmemory: ^1.5.1 => 1.5.1
    apollo-client: ^2.5.1 => 2.5.1
    apollo-link: ^1.2.9 => 1.2.9
    apollo-link-batch-http: ^1.2.9 => 1.2.9
    apollo-link-error: ^1.1.8 => 1.1.8
    apollo-link-http: ^1.5.12 => 1.5.12
    apollo-link-ws: ^1.0.15 => 1.0.15
    react-apollo: ^2.5.2 => 2.5.2

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
