### ISSUE TITLE
onResetStore(stateLink.writeDefaults) doesn't restore defaults to cache

### ISSUE THREAD

**Issue by brandonferrer** [apollographql/apollo-client#4603]
**Intended outcome:**
Calling client.resetStore() anywhere in app should clear cache, and restore default values in cache due to client.onResetStore(stateLink.writeDefaults).

**Actual outcome:**
Existing cache values are still persisted, and neither cleared or reset to default values. 

**How to reproduce the issue:**
- cache defaults: foo: 'bar'
- calling client mutation to update foo:  foo: 'baz'
- call client.resetStore()
- foo value in cache remains 'baz' 

```
import { ApolloClient } from 'apollo-client';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { HttpLink } from 'apollo-link-http';
import { createUploadLink } from 'apollo-upload-client';
import { withClientState } from 'apollo-link-state';
import { ApolloLink } from 'apollo-link';
import defaults from './defaults';
import resolvers from './resolvers';
import config from '../../config';

const GRAPHQL_URI = config.REACT_APP_GRAPHQL_URI;

const httpOptions = { uri: GRAPHQL_URI, credentials: 'include' };
const uploadLink = createUploadLink(httpOptions);
const httpLink = new HttpLink(httpOptions);

const cache = new InMemoryCache();

const stateLink = withClientState({
  cache,
  resolvers,
  defaults,
  schema: '../../local.graphql',
});

const createApolloClient = () =>
  new ApolloClient({
    ssrMode: typeof window !== 'undefined',
    link: ApolloLink.from([stateLink, uploadLink, httpLink]),
    cache,
  });

const apolloClient = createApolloClient();

apolloClient.onResetStore(stateLink.writeDefaults);

export default apolloClient;
```

**Versions**
  System:
    OS: macOS 10.14.3
  Binaries:
    Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
    Yarn: 1.6.0 - ~/.nvm/versions/node/v8.9.4/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.9.4/bin/npm
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: 64.0
    Safari: 12.0.3
  npmPackages:
    apollo-boost: ^0.1.16 => 0.1.28
    apollo-cache-inmemory: ^1.5.1 => 1.5.1
    apollo-client: ^2.5.1 => 2.5.1
    apollo-link: ^1.2.9 => 1.2.10
    apollo-link-dedup: ^1.0.18 => 1.0.18
    apollo-link-http: ^1.5.12 => 1.5.13
    apollo-link-state: ^0.4.2 => 0.4.2
    apollo-upload-client: ^9.1.0 => 9.1.0
    react-apollo: ^2.5.2 => 2.5.2
  npmGlobalPackages:
    apollo-codegen: 0.20.2
    apollo: 2.1.9

Thanks!

**Comment by kidequinox** [comment]
Same but using apollo-client 2.5.1
In 2.5+ link state is now baked in.

Initially, to set defaults in 2.5 the docs say do a direct `cache.writeData({})`, how do we implement this with `onResetStore` ?

Also how about re-resetting the headers.authorization ?

I'm trying to properly reset important values after user has logged in or out.

**Comment by kidequinox** [comment]
not using link-state anymore. using built-in link methods with [version 2.5.1](https://www.apollographql.com/docs/react/essentials/local-state#migrating)
something like,
```
client.onResetStore( () => {
    cache.writeData({
      data: {
        localAuth: {
          __typename: 'Auth',
          status: !err && result ? 'loggedIn' : 'anon' // processing, anon, authorized
        }
      }
    })
})
```

**Comment by hwillson** [comment]
Apollo Client 2.5 includes newer local state management features that replace the need for `apollo-link-state`, and functionality like `stateLink.writeDefaults`. You can read more about this in the [Local state management](https://www.apollographql.com/docs/react/essentials/local-state) section of the docs. If you're interested in getting help with `apollo-link-state` specifically, please re-open this issue over in http://github.com/apollographql/apollo-link-state.

**Comment by kidequinox** [comment]
hey @hwillson any ideas on how to reset headers with 2.5 ?
During the `onResetStore` process, I want to refresh `headers.authentication` as well.
