### ISSUE TITLE
Incorrectly generated cache key for @connection directive with object arguments

### ISSUE THREAD

**Issue by jpikora** [apollographql/apollo-client#4607]
**Intended outcome:**

Utility function `getStoreKeyName` should return consistent cache key for queries using `@connection` directive even in case when arguments are of object type.

```
const POSTS_QUERY = gql`
  query Posts ($filter: PostsFilter!, $offset: Int, $limit: Int) {
    posts (filter: $filter, offset: $offset, limit: $limit) @connection(key: "posts", filter: ["filter"]) {
      id
      # ...
    }
  }
`

// variables for query
const variables = {
  filter: {
    unread: true
    project_id: 123
  },
  ...
}
```

Cache key for such query/variables should be consistently:

`posts({"filter":{"project_id":"123","unread":true}})`

**Actual outcome:**

However, the implementation of `getStoreKeyName` is currently serializing `@connection` args using non-deterministic `JSON.stringify` this leads to error, when sometimes the cache key is generated with different order of arguments, e.g.:

`posts({"filter":{"unread":true,"project_id":"123"}})`

When using such key it produces error `Invariant Violation: Can't find ... `, because it won't find it in the cache, assuming the former key was used before.

**How to reproduce the issue:**

It's hard to reproduce the issue, since it will work based on the order how object properties are iterated at the time of arguments serializations.

**Proposed solution:**

`getStoreKeyName` is already using `fast-json-stable-stringify` for deterministic serialization of query arguments. It should be also used when serializing filtered arguments in case of `@connection` directive.

Here: https://github.com/apollographql/apollo-client/blob/master/packages/apollo-utilities/src/storeUtils.ts#L213

**Versions:**
apollo-cache-inmemory: ^1.5.1 => 1.5.1 
apollo-client: ^2.5.1 => 2.5.1 
apollo-link: ^1.2.11 => 1.2.11 
apollo-link-error: ^1.1.10 => 1.1.10 
apollo-link-http: ^1.5.14 => 1.5.14 
apollo-link-ws: ^1.0.17 => 1.0.17 
apollo-utilities: ^1.2.1 => 1.2.1

**Comment by joebernard** [comment]
Is there any update on this one? I'm seeing it with these packages.

```
"apollo-cache": "^1.3.4",
"apollo-cache-inmemory": "^1.6.5",
"apollo-client": "2.6.8",
"apollo-link": "^1.2.13",
"apollo-link-http": "^1.5.16",
"apollo-utilities": "^1.3.3",
```

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
