### ISSUE TITLE
ApolloClient  @client field in a Query that is undefined causes entire data result to be undefined

### ISSUE THREAD

**Issue by DonaldWebb** [apollographql/apollo-client#4609]
**Intended outcome:**
Perhaps a documentation or by design issue.
An Optional @client field in a Query that is undefined should not cause the entire query result to be undefined. No error result, no exceptions.

An undefined @client field appears to act like a !required field, or errors out in ApolloClient.
If the field is undefined it will return null for the whole query as per the !required field logic.
This (to me at least) appears to go against the all fields are optional unless specifically required.

Adding an @client field will cause all launches to be empty even though starred is optional and the remaining data is available. This happens for remote calls as well. My expectations from the documentation would be for it to try get the field from the object in cache, not find one and return the launch object with starred undefined.

**Actual outcome:**
launch object is an empty {} object instead of the launch data with starred as undefined.
```json
{
  "loading": false,
  "networkStatus": 7,
  "stale": true
}
```

**How to reproduce the issue:**
Using the Space Tutorial: https://github.com/apollographql/fullstack-tutorial/commit/014d900d62265a1c69825cb82367b2e838e05f2a
Run the query in graphiql
or
Update Launcher.js GET_LAUNCHES and add matching typedef in resolvers.js
```GraphQL

  query GetLaunchList($after: String) {
    launches(after: $after) {
      cursor
      hasMore
      launches {
        __typename
    id
    isBooked
    starred @client
      }
    }
  }
```
resolvers.js
```GraphQL
extend type Launch {
    isInCart: Boolean!
    starred: Boolean
  }
```

Adding a localResolver fixes it:
```typescript
export const resolvers = {
  Launch: {
    isInCart: (launch, _, { cache }) => {
      const { cartItems } = cache.readQuery({
        query: GET_CART_ITEMS,
      });
      return cartItems.includes(launch.id);
    },
    starred: (launch, _, { cache }) => {
      return launch.starred|| false;
    },
  },
};
```

This means that every localstate field will require a resolver as on first load it will be undefined and cause the entire result set to be undefined. Data gets into cache but not returned to caller.

**Versions**
  System:
    OS: Windows 10
  Binaries:
    Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\projects\fullstack-tutorial\final\client\node_modules\.bin\yarn.CMD
    npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    apollo: ^2.5.3 => 2.5.3
    apollo-cache-inmemory: ^1.5.1 => 1.5.1
    apollo-client: ^2.5.1 => 2.5.1
    apollo-link-http: ^1.5.9 => 1.5.9
    react-apollo: ^2.5.1 => 2.5.1

**Comment by hwillson** [comment]
@DonaldWebb The [Initializing the cache](https://www.apollographql.com/docs/react/essentials/local-state#cache-initialization) section of the docs should help with this. Unfortunately, you can't query the cache using fields that don't yet exist as otherwise there would be no way to report on when this happens intentionally, or when it was an accident. We want this to error out by default, so developers are made aware of it being an issue up-front. To work around this, you can prep the cache ahead of time so it knows to expect queries with a `starred` field (even though it might not have a value yet) using `client.writeData`.
