### ISSUE TITLE
Calling client.mutate within error link results in 400 response

### ISSUE THREAD

**Issue by StupidSexyJake** [apollographql/apollo-client#4611]
**Intended outcome:**

I've created an Apollo Client like so:

```
const client = new ApolloClient({
    connectToDevTools: process.browser,
    ssrMode: !process.browser,
    link: ApolloLink.from([
        errorLink,
        authLink,
        terminatingLink,
    ]),
    cache: new InMemoryCache().restore(initialState || {}),
})
```

errorLink is equal to the following (copied from [official Apollo documentation](https://www.apollographql.com/docs/link/links/error.html#retry-request)):

```
const errorLink = onError(({ graphQLErrors, networkError, operation, forward }) => {
    console.log('error')
    if (graphQLErrors) {
        for (let err of graphQLErrors) {
            switch (err.extensions.code) {
                case 'UNAUTHENTICATED':
                    const headers = operation.getContext().headers
                    operation.setContext({
                        headers: {
                            ...headers,
                            'x-token': refreshAuthToken(),
                        },
                    })
                    return forward(operation)
            }
        }
    }
})
```

To obtain the new auth token, I need to run a mutation like so:

```
const refreshAuthToken = () => {
    // Get refresh token from cookies
    const refreshToken = getTokens()['x-token-refresh']
    // Get new auth token from server
    client.mutate({
        mutation: REFRESH_AUTH_TOKEN,
        variables: {
            refreshToken
        }
    })
        .then(data => {
            document.cookie = cookie.serialize('x-token', data.data.refreshAuthToken.token, {})
            return data.data.refreshAuthToken.token
        })
        .catch(error => {
            console.log(error)
            return
        })
}
```

I know the mutation is correctly formatted as I've tested that a) the schema is correct using GraphQL Playground, and b) the refreshToken variable is correct.

I also have the following set as authLink in case it matters:

```
const authLink = setContext((_, { headers }) => {
    const tokens = getTokens()
    return {
        headers: {
            ...headers,
            'x-token': tokens['x-token'] ? tokens['x-token'] : '',
            'x-token-refresh': tokens['x-token-refresh'] ? tokens['x-token-refresh'] : ''
        }
    }
})
```

What SHOULD happen, is that whenever I receive an UNAUTHENTICATED error code response, the mutation fetches the new auth token. This is working correctly in the server when using GraphQL Playground. It should NOT hit the catch().

**Actual outcome:**
The error is correctly hit but when the refreshAuthToken() function is called, client.mutate() hits the catch() and returns an error 400 response in console.

**How to reproduce the issue:**

Try the code above.

**Versions**

  System:
    OS: Windows 10
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    apollo-boost: ^0.3.1 => 0.3.1
    apollo-cache-inmemory: ^1.5.1 => 1.5.1
    apollo-client: ^2.5.1 => 2.5.1
    apollo-link: ^1.2.9 => 1.2.9
    apollo-link-batch-http: ^1.2.9 => 1.2.9
    apollo-link-context: ^1.0.17 => 1.0.17
    apollo-link-error: ^1.1.8 => 1.1.8
    apollo-link-ws: ^1.0.15 => 1.0.15
    react-apollo: ^2.5.1 => 2.5.1

**Comment by JoviDeCroock** [comment]
Could you share the error please? This in all honesty is quite vague since this could have multiple causes

**Comment by StupidSexyJake** [comment]
Sure, the error received is:

```
{ Error: Network error: Response not successful: Received status code 400
    at new ApolloError (/root/admin_portal/node_modules/apollo-client/bundle.umd.js:59:32)
    at Object.error (/root/admin_portal/node_modules/apollo-client/bundle.umd.js:1031:52)
    at notifySubscription (/root/admin_portal/node_modules/zen-observable/lib/Observable.js:134:18)
    at onNotify (/root/admin_portal/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.error (/root/admin_portal/node_modules/zen-observable/lib/Observable.js:224:7)
    at notifySubscription (/root/admin_portal/node_modules/zen-observable/lib/Observable.js:134:18)
    at onNotify (/root/admin_portal/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.error (/root/admin_portal/node_modules/zen-observable/lib/Observable.js:224:7)
    at notifySubscription (/root/admin_portal/node_modules/zen-observable/lib/Observable.js:134:18)
    at onNotify (/root/admin_portal/node_modules/zen-observable/lib/Observable.js:165:3)
  graphQLErrors: [],
  networkError:
   { ServerError: Response not successful: Received status code 400
       at Object.exports.throwServerError (/root/admin_portal/node_modules/apollo-link-batch-http/node_modules/apollo-link-http-common/lib/index.js:23:17)
       at /root/admin_portal/node_modules/apollo-link-batch-http/node_modules/apollo-link-http-common/lib/index.js:48:21
       at process._tickCallback (internal/process/next_tick.js:68:7)
     name: 'ServerError',
     response:
      Response {
        size: 0,
        timeout: 0,
        [Symbol(Body internals)]: [Object],
        [Symbol(Response internals)]: [Object] },
     statusCode: 400,
     result: { errors: [Array] } },
  message:
   'Network error: Response not successful: Received status code 400',
  extraInfo: undefined }
```

**Comment by StupidSexyJake** [comment]
And the output of networkError.result.errors is:

```
{ message:
   'Context creation failed: Your session expired. Sign in again.',
  extensions:
   { code: 'UNAUTHENTICATED', exception: { stacktrace: [Array] } } }
```

I have a feeling the authLink is attempting to authenticate the request before the mutation is allowed to run, so it ends up in a loop (the error message loops until I force close the server/client).

On the server side I have the following code (code provided from [this repo](https://github.com/the-road-to-graphql/fullstack-apollo-express-postgresql-boilerplate/blob/master/src/index.js)):

```
const getMe = async req => {
    const token = req.headers['x-token']
    if (token) {
        try {
            return await jwt.verify(token, process.env.SECRET)
        } catch (e) {
            throw new AuthenticationError(
                'Your session expired. Sign in again.',
            )
        }
    }
}

const server = new ApolloServer({
    introspection: true,
    playground: true,
    typeDefs: schema,
    resolvers,
    formatError: error => {
        // leave only the important validation error
        const message = error.message
            .replace('SequelizeValidationError: ', '')
            .replace('Validation error: ', '')

        return {
            ...error,
            message,
        }
    },
    context: async ({ req, connection, res }) => {
        if (connection) {
            return {
                models,
            }
        }
        if (req) {
            const me = await getMe(req)
            return {
                models,
                me,
                secret: process.env.SECRET,
                res
            }
        }
    },
})
```

What I expect to happen is:

- Client sends a request to the server with an auth token in the header
- Server attempts to verify the auth token. If it fails, it returns an UNAUTHENTICATED response back.
- Client receives the response and if a refresh token is available, it sends a mutation request to update the auth token.
- Server updates the auth token from the mutation and sends it back to the client
- Client receives the new auth token then tries the last operation again with the new auth token in the header.

Instead what seems to be happening is:

- Client sends a request to the server with an auth token in the header
- Server attempts to verify the auth token. If it fails, it returns an UNAUTHENTICATED response back.
- Client receives the response and if a refresh token is available, it sends a mutation request to update the auth token.
- Server receives the mutation request but before it processes it, it attempts to verify the existing auth token again. It fails and sends back another UNAUTHENTICATED response without running the mutation.
- Client receives the error response. This creates an error loop as it tries to send another mutation request.

I can't remove the authLink from the client as it's needed to define the signed-in user for many other requests.

**Comment by luciannojunior** [comment]
Won't `refreshAuthToken()` run just as a normal mutation (and fail on the server)? And also, Apollo will accept an Observable as one of its headers? Is it working (setting the header and running the retry)?

This doesn't seem like a problem with Apollo, anyway. You will be better suited posting this on SOF.

**Comment by StupidSexyJake** [comment]
So I figured it out...

I was following [another example](https://github.com/the-road-to-graphql/fullstack-apollo-express-postgresql-boilerplate) to setup the server and as you can see in my last comment, it sets a 'me' context equal to the result of the getMe() function.

The issue with this is that it's returning an authentication error if the auth token isn't verified **in the context**. So when I send the mutation to refresh the tokens, it's hitting that getMe() function and returning **another** authentication error. This causes the mutation to fail and for the error message to loop (as the authentication error triggers another refreshAuthToken() attempt).

I removed the authentication error from the catch hook and moved it to the resolvers instead. Now it works :)
