### ISSUE TITLE
readFragment causing IntrospectionFragmentMatcher error

### ISSUE THREAD

**Issue by sattaman** [apollographql/apollo-client#4618]
**Intended outcome:**

Querying a fragment of a cached query using the following code should not cause error message to show. (I am not using a union or interface)

```
const sourceData = cache.readFragment({
        id: `Series:my-id`,
        fragment: gql`
            fragment series on PriceSeries {
                id
                title
            }
        `,
      });
```

Where I can see Series:my-id in the apollo cache

My apolloClient is set up as follows:

```
const client = new ApolloClient({
      cache: new InMemoryCache(),
      link: createLink(graphQL),
    });
```

**Actual outcome:**

The `readFragment` call causes a `console.error` to be called with

> "You are using the simple (heuristic) fragment matcher, but your queries contain union or interface types. Apollo Client will not be able to accurately map fragments. To make this error go away, use the IntrospectionFragmentMatcher as described in the docs: https://www.apollographql.com/docs/react/recipes/fragment-matching.html"

The code works fine but I don't understand why this error is showing. The docs seem to indicate do not need to use `IntrospectionFragmentMatcher` unless I am doing unions or interfaces which I am not.

**How to reproduce the issue:**

I'm happy to create the template if confirmed this sounds like a bug, and not that I am misunderstanding something.

**Versions**

System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 8.11.3 - /usr/local/opt/node@8/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/opt/node@8/bin/npm
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: 65.0
    Safari: 12.0.3
  npmPackages:
    apollo-boost: ^0.1.6 => 0.1.16 
    apollo-cache-inmemory: ^1.2.5 => 1.2.10 
    apollo-client: ^2.3.5 => 2.4.2 
    apollo-client-preset: ^1.0.8 => 1.0.8 
    apollo-link: ^1.2.2 => 1.2.3 
    apollo-link-context: ^1.0.8 => 1.0.9 
    apollo-link-error: 1.1.0 => 1.1.0 
    apollo-link-http: ^1.5.4 => 1.5.5 
    apollo-link-retry: ^2.2.4 => 2.2.5 
    apollo-link-timeout: ^1.1.10 => 1.1.10 
    react-apollo: ^2.1.4 => 2.2.4

**Comment by hwillson** [comment]
@sattaman When you write your fragment to the cache, are you including a `__typename`? See https://github.com/apollographql/apollo-client/issues/1865#issuecomment-450941442.
