### ISSUE TITLE
resolver dependency injection best practice

### ISSUE THREAD

**Issue by plummer-flex** [apollographql/apollo-client#4627]
We're working on replacing Redux with the Apollo Client for state management.  In Redux we used thunks and various middleware to inject dependencies into reducers. In other gql Schemas, we've used context to achieve the same goal.  However, with the Apollo Client, we're having an issue getting any dependencies to show up through context.

The client doesn't take a `schema` or `context` option; just `typeDefs` and `resolvers` and seems to hijack the context by passing in cache and client.  

We've attempted to use `apollo-link-context` and `ApolloLink` but did not see anything set in the client resolver arguments.

Our current solution is to set the dependency direction on the client, which is then passed to the resolver.

```
export const client = new ApolloClient({
  name: "my-client",
  link: new HttpLink(...),
  cache,
  resolvers,
  typeDefs
});

client.test = { foo: "bar" };
```
This seems a bit hacky, but works.  Are there any other methods to passing context into the ApolloClient?

**Comment by OurMajesty** [comment]
not better, but I tried and it worked.   
anything you send to options object of InMemoryCache constructor, ends in third argument of resolvers:

![изображение](https://user-images.githubusercontent.com/44201792/55009224-df5f0a00-4fea-11e9-9870-450b99e06206.png)

![изображение](https://user-images.githubusercontent.com/44201792/55009199-d8d09280-4fea-11e9-898b-a88d9aef9f4f.png)

**Comment by plummer-flex** [comment]
@OurMajesty I think I figured it out.  It needs to be passed in `defaultOptions` and then the context for any `watchQuery`, `query`, or `mutate` where you want to inject a context.

```
const context = { test: { foo: "bar" } };

const defaultOptions = {
  mutate: {
    context
  },
  query: {
    context
  }
};

export const client = new ApolloClient({
  ...
  defaultOptions
});
```

I was missing this because the definition of what each method expects is not associated with the `defaultOptions` but with those method calls themselves.
