### ISSUE TITLE
Cannot use custom directive that conditionally omits response data 

### ISSUE THREAD

**Issue by tall-dan** [apollographql/apollo-client#4628]
### Use Case 
We have a graphql API that supports both mobile and web. We also support custom translations via a DB on the backend. 

In consuming a translated field, there are two cases - one for mobile, and one for web
#### Mobile  

For mobile, we want to be able to switch languages without a network request - imagine switching languages at a crowded kiosk where the internet may be spotty. For this reason, we want to fetch all translations at once. A graphql query might look like this:

```
 fragment languages on TranslatableField {
    cs
    de
    en
    es
    fr
    hu
    it
    ja
    ko
    nl
    nn
    pl
    pt
    sv
    zhTw
 }

query Events {
  events { 
    name { ... languages }
    location { ...languages }
    ...
  }
}
```

#### Web  

For web, we feel confident that our users don't switch languages often. We don't have any concept of a web-based kiosk that multiple users are using. For this reason, we only need to fetch values in the user's current language. A graphql query might look like this:

```
 fragment languages on TranslatableField {
    en
 }

query Events {
  events { 
    name { ... languages }
    location { ...languages }
    ...
  }
}
```

#### Attempted solution
In order to accommodate for these two separate use cases, I wrote a directive, `@includeTranslation` that reduces the queries above to the following:

```
fragment languages on TranslatableField{
    cs @includeTranslation(ifElement: "cs", inArray: $languages)
    de @includeTranslation(ifElement: "de", inArray: $languages)
    en @includeTranslation(ifElement: "en", inArray: $languages)
    es @includeTranslation(ifElement: "es", inArray: $languages)
    fr @includeTranslation(ifElement: "fr", inArray: $languages)
    hu @includeTranslation(ifElement: "hu", inArray: $languages)
    it @includeTranslation(ifElement: "it", inArray: $languages)
    ja @includeTranslation(ifElement: "ja", inArray: $languages)
    ko @includeTranslation(ifElement: "ko", inArray: $languages)
    nl @includeTranslation(ifElement: "nl", inArray: $languages)
    nn @includeTranslation(ifElement: "nn", inArray: $languages)
    pl @includeTranslation(ifElement: "pl", inArray: $languages)
    pt @includeTranslation(ifElement: "pt", inArray: $languages)
    sv @includeTranslation(ifElement: "sv", inArray: $languages)
    zhTw @includeTranslation(ifElement: "zhTw", inArray: $languages)
}

query Events($languages: [String!] = ["en"]) {
  events { 
    name { ... languages }
    location { ...languages }
    ...
  }
}
```
When I tested the above in GraphiQL or postman, everything worked great. However, when I got around to implementing it using ApolloClient, it did not work

**Intended outcome:**
Data propagating through the client

**Actual outcome:**
Lots of these warnings: 
![image](https://user-images.githubusercontent.com/1512489/55013456-26330c80-4fb7-11e9-995b-932c1b83ff81.png)

No data propagates to the react components

**How to reproduce the issue:**
If necessary, I can create a repo with my RoR server serving up a graphql API (and my custom directive). However, I feel relatively confident I know _where_ the issue comes from, I'd like the community's input & help on how to address it.

If you take a look at the [`shouldInclude function`](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-utilities/src/directives.ts#L39-L97), we see a block that `return`s if "we don't understand" a directive. I thought about renaming my directive to `@include`, but there's plenty of logic in the function that checks about the arguments given to these directives. 

So my question is, can we (and how can we) extend this include / skip logic to consumers' custom directives?

Thank you!

**Versions**
```
  System:
    OS: macOS 10.14.3
  Binaries:
    Node: 9.5.0 - ~/.nvm/versions/node/v9.5.0/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 5.10.0 - ~/.nvm/versions/node/v9.5.0/bin/npm
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 64.0
    Safari: 12.0.3
  npmPackages:
    apollo-boost: ^0.1.16 => 0.1.16 
    apollo-link-context: ^1.0.12 => 1.0.12 
    react-apollo: ^2.2.1 => 2.2.1 
  npmGlobalPackages:
    apollo: 2.1.9
```

**Comment by veeramarni** [comment]
@tall-dan were able to find an alternate solution?

**Comment by dylanwulf** [comment]
Is `@includeTranslation` implemented on the server-side or the client-side?

**Comment by tall-dan** [comment]
@veeramarni no, I was not. 

@dylanwulf `includeTranslation` is implemented on the server side.

[this repo](https://github.com/tall-dan/apollo_directive_demo) demonstrates the issue. I haven't had time yet to deploy it to heroku

**Comment by tall-dan** [comment]
@veeramarni @dylanwulf I was able to deploy to heroku: https://apollo-directives-demo.herokuapp.com/

**Comment by dylanwulf** [comment]
Would it be possible to have the server return `null` instead of `undefined` for fields that you don't want included?

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
