### ISSUE TITLE
Unhandled Apollo Error | When there is NO INTERNET

### ISSUE THREAD

**Issue by deepak28** [apollographql/apollo-client#4645]
**Intended outcome:**

I just turned off my Internet to see how it behaves.

**Actual outcome:**

![Simulator Screen Shot - iPhone X - 2019-03-30 at 10 13 35](https://user-images.githubusercontent.com/4962749/55271584-0e1ffd80-52d5-11e9-9c20-32dac4e9d8d9.png)

**How to reproduce the issue:**

Turn off the Internet and call any API.

**Versions**

    "apollo-cache-inmemory": "^0.2.0-rc.4",
    "apollo-client": "^2.0.1",
    "apollo-client-preset": "^1.0.1",
    "apollo-link-context": "^1.0.1",
    "apollo-link-error": "^1.0.3",
    "apollo-link-http": "^1.1.0",
    "react-apollo": "^1.4.16",

**Comment by brandondoran** [comment]
This seems related to #3034

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-client/issues/4645#issuecomment-478297431, this issue is already being tracked in https://github.com/apollographql/apollo-client/issues/3034/. Closing here - thanks!
