### ISSUE TITLE
Apollo's InMemoryCache does not conform to type definition of cache.read() method

### ISSUE THREAD

**Issue by andrew-humu** [apollographql/apollo-client#4654]
**Intended outcome:**

When using ApolloClient with an InMemoryCache instance, I tried to read a fragment, as follows:

```
  const data = client.readFragment<myFragment>({
    id: 'ROOT_QUERY',
    fragment: myFragment,
  });
```

At that point, I tried to defend against the no-data case, in accordance with the included type definition, like so:

```
if (data == null) {
  throw new InvariantViolation();
}
```

This, I expected to throw an InvariantViolation error when the cache did not contain the data we were looking for.

**Actual outcome:**

In reality, readFragment returned an empty object (`{}`) when no data was available in my store, which meant that even though typescript was satisfied that my data was handled correctly, the Invariant check is never triggered.

**How to reproduce the issue:**

https://codesandbox.io/s/03rloorl4v

**Versions**

```
  System:
    OS: macOS 10.14.4
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: 1.15.2 - ~/Projects/humu/node_modules/.bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 65.0.1
    Safari: 12.1
  npmPackages:
    apollo-cache-inmemory: 1.5.1 => 1.5.1 
    apollo-client: 2.5.1 => 2.5.1 
    apollo-link-schema: 1.2.2 => 1.2.2 
    react-apollo-hooks: 0.4.3 => 0.4.3 
```

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
