### ISSUE TITLE
Don't want to pass optional parameters in Query

### ISSUE THREAD

**Issue by bpollock-vida** [apollographql/apollo-client#4660]
**Intended outcome:**

Given:
```
Query {
   fooQuery(argOne: String, argTwo: String) {
      bar
   }
}
```
I want to only pass the arguments I have values for:
`FooQuery(argTwo: "someString")`

**Actual outcome:**
Swift compiler will complain with 'missing argument for parameter argOne in call'

The Apollo-client generated constructor is 
`public init(argOne: String?, argTwo: String?)`

**How to reproduce the issue:**
1. Create a query with two optional arguments
2. Include Apollo-client and type generation in an iOS Xcode project
3. Try to pass one argument into the query in Xcode

**Versions**
  System:
    OS: macOS 10.14.2
  Binaries:
    Node: 11.9.0 - ~/.nvm/versions/node/v11.9.0/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - ~/.nvm/versions/node/v11.9.0/bin/npm
  Browsers:
    Chrome: 73.0.3683.86
    Safari: 12.0.2
  npmGlobalPackages:
    apollo-codegen: 0.20.2
    apollo: 2.4.4

Don't think these are relevant ^

Xcode: 10.1
Swift: 4.2
pod 'Apollo', '= 0.9.0'

I think these are relevant ^

**Comment by hwillson** [comment]
Please ask this over in https://github.com/apollographql/apollo-ios. Thanks!
