### ISSUE TITLE
apollo-client does require process.env to be set since 2.4

### ISSUE THREAD

**Issue by 000panther** [apollographql/apollo-client#4665]
**Intended outcome:**
I wanted to use the apollo-client library for grapqhl requests in my nativescript application.

**Actual outcome:**
The code failed, since no apollo-client was instanciated. After debugging, we found out that the code references the non existing variable process.env.NODE_ENV multiple times.

**How to reproduce the issue:**
Create a nativescript app and add the apollo client with version 2.5 and up.

**Versions**

**Comment by hwillson** [comment]
Thanks for reporting this @000panther. This is likely being caused by Apollo Client's use of [`ts-invariant`](https://github.com/apollographql/invariant-packages), which leverages `process.env.NODE_ENV` to help minifiers prune unreached code branches (to reduce bundle sizes). This isn't something we're likely going to change anytime soon, but are you using `webpack` for your builds? If so, maybe you could use [`DefinePlugin`](https://webpack.js.org/plugins/define-plugin/) to create a `process.env.NODE_ENV` environment variable?

```js
new webpack.DefinePlugin({
  'process.env': {
    'NODE_ENV': 'production'
  }
});
```

**Comment by 000panther** [comment]
We are using webpack, I will check if this workaround does the trick and report back on monday.

**Comment by benjamn** [comment]
I believe this is something we can fix by polyfilling `process` in the `ts-invariant` package. It's definitely not a concern that anyone using the Apollo Client libraries should have to worry about.

**Comment by 000panther** [comment]
O.K we got it working. The snipped posted above did not work, I think because it used the wrong quotes and webpack inserted production without quotes in the packed code, and we got 'production not defined' errors.

working snippet:

```
            new webpack.DefinePlugin({
                'process.env': {
                  'NODE_ENV': JSON.stringify('production')
                },
            }),
```

A colleague of mine (on iOS) also had some successes by installing the node-process npm package, but I could not reproduce this under android.

I think it would be great if apollo-client could work without such workarounds in browsers and environments like nativescript, and hope you can find a solution so that apollo-client works transparently for users in that environments.

**Comment by hwillson** [comment]
Great, thanks for the follow up @000panther! We'll find a way to improve this.

**Comment by uhoh-itsmaciek** [comment]
Hi, I'm trying to switch from webpack to vite/rollup and seem to be hitting this error. I'm on 3.4.15 so as I understand it, this shouldn't be an issue. I'm using hooks, and when I try to issue a query, it's actually called successfully and the server returns a response (looking in the network tab in dev tools), but I get an error from the hook: "Error: process is not defined".

Any ideas what's going on?

**Comment by brainkim** [comment]
@uhoh-itsmaciek I’m happy to help. Can you open another issue and ping me so this doesn’t get lost in the weeds? Also if you have a screenshot of the stack trace that would be incredibly helpful.
