### ISSUE TITLE
Performance Improvement for new doc site

### ISSUE THREAD

**Issue by tanaypratap** [apollographql/apollo-client#4666]
The new doc site is built on Gatsby. In my experience working with Gatsby, websites score a perfect 100 on performance. There are areas of improvements which are laid out by the audit.

**Intended outcome:**

The performance audit should result in a score of 100.

**Actual outcome:**

Score is 87. There are areas of improvement
![image](https://user-images.githubusercontent.com/10216863/55578445-8c482e00-5733-11e9-89d2-00c200ad2cfb.png)

**How to reproduce the issue:**
Use Google Chrome's inbuilt performance audit tool as shown below:
![image](https://user-images.githubusercontent.com/10216863/55578492-b39efb00-5733-11e9-8361-317f253a6c3c.png)

**Comment by tanaypratap** [comment]
@trevorblades @hwillson I'm looking to help in making the docs site faster and better. I would like to send PRs for these if these are not already being worked on by someone.

Also, need to know how to run the Gatsby site on my local machine.

**Comment by tanaypratap** [comment]
The score for mobile audit is even lower.
![image](https://user-images.githubusercontent.com/10216863/55578854-8868db80-5734-11e9-907e-83d81087284d.png)

**Comment by trevorblades** [comment]
@tanaypratap thanks for bringing this to our attention! To run the docs site locally, just clone a repo (like this one) `cd docs`, `npm install`, and then `npm start`. We're using a Gatsby theme to build our docs websites, so any changes to the way we're building should take place in the theme repo: https://github.com/apollographql/gatsby-theme-apollo

**Comment by abernix** [comment]
It ranks as a 91 now, which is at least _green_.  It may not be 100, but if there are any contributions to be made here, it's on the https://github.com/apollographql/gatsby-theme-apollo theme which powers it all.
