### ISSUE TITLE
how to use createPersistedQueryLink in apollo-boost for Automatic Persisted Queries

### ISSUE THREAD

**Issue by fangjj** [apollographql/apollo-client#4674]
Need help or want to talk all things Apollo Client? Issues here are reserved for bugs, but one of the following resources should help:

* Apollo Spectrum community: https://spectrum.chat/apollo
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests

In apollo-boost, how to use createPersistedQueryLink  for Automatic Persisted Queries? thank you!

**Comment by hwillson** [comment]
@fangjj You can't use `apollo-boost` to do this, since it (intentionally) won't let you modify your Link  chain. Please use `apollo-client` instead (see the [Apollo Boost migration](https://www.apollographql.com/docs/react/advanced/boost-migration) section of the docs for help ejecting).
