### ISSUE TITLE
Caching issue when updating a <Query /> variable

### ISSUE THREAD

**Issue by jpetitcolas** [apollographql/apollo-client#4676]
I'm currently experimenting either a caching issue, or at least a misunderstanding on my side (which may be solved by a doc update). :)

**Intended outcome:**

I got a datagrid page, containing a `<Filters />` block and another `<List />` page, with something like (simplified not working code, but you get the main idea):

```js
<div>
    <Filters onChange={name => this.setState({ name }) />
    <Query query={MY_QUERY} variables={{
        name: this.state.name,
        sort: this.state.sort
    }}>
        {({ data }) => (
            <List
                data={data}
                onSortChange={sort => this.setState({ sort })}
            />
        }
    </Query>
</div>
```

When updating the `name` filter, it doesn't fetch the query result again (neither UI update, nor network request shown in the developer tools). Updating the order of records in the list through the `onSortChange` prop works fine.

If I add a `fetchPolicy="network-only"` prop, I don't get the issue. But UX is not as good.

**Actual outcome:**

I would expect the list to be updated according to the server request results.

**How to reproduce the issue:**

Here is a code sandbox with a simplified version of the issue: https://codesandbox.io/s/vx9l4zk6l

The input allows to filter by user ID. But it does nothing. If I add the `fetchPolicy` prop, it displays a loading message (even if it doesn't filter correctly, but that's probably another code issue: I didn't dive deeper). 

**Versions**

```
  System:
    OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
  Binaries:
    Node: 11.2.0 - ~/.nvm/versions/node/v11.2.0/bin/node
    Yarn: 1.12.3 - ~/.nvm/versions/node/v11.2.0/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v11.2.0/bin/npm
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 66.0.1
  npmPackages:
    apollo-boost: ^0.3.1 => 0.3.1 
    react-apollo: ^2.5.3 => 2.5.3 
```

**Comment by MGrin** [comment]
In you sandbox query, you do not use any variables:
```
query AllPeople {
    people {
      id
      name
    }
  }
```

So even if you update `this.state.name`, Query will not be fired because nothing changed in the query that should be sent to graphql backend.

If you change your query to be something like
```
query AllPeople($id: ID) {
    people(id: $id) {
      id
      name
    }
  }
```
everything should work as expected

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-client/issues/4676#issuecomment-480504201, this is not an Apollo Client issue. Thanks!
