### ISSUE TITLE
Apollo-cache-persist appears to not be maintained, there are many issues and open PRs

### ISSUE THREAD

**Issue by ajhool** [apollographql/apollo-client#4677]
**Intended outcome:**

Apollo client suggests using apollo-cache-persist as a package. However, there are several bugs in the apollo-cache-persist package and the repository no longer seems to be maintained. Please see the apollo-cache-persist repo for more information.

https://github.com/apollographql/apollo-cache-persist

**Actual outcome:**

Please go to the apollo-cache-persist repo. The repository is not maintained and there are several bugs (and also PR's for those bugs).

An issue has been posted there with more detail: https://github.com/apollographql/apollo-cache-persist/issues/86

**How to reproduce the issue:**

Please go to the apollo-cache-persist repo.

**Versions**

2.5.1

**Comment by wtrocki** [comment]
We can land some of the PR's into The fork here: https://github.com/graphql-heroes/apollo-cache-persist
Happy to add some collaborators etc. and release it with some temporary name once this repository will get some owners willing to accept changes.

**Comment by ajhool** [comment]
@wtrocki appears to have taken the torch and updated the repo!
