### ISSUE TITLE
Cache should not add __typename to @export-ed input variables

### ISSUE THREAD

**Issue by OurMajesty** [apollographql/apollo-client#4691]
**Intended outcome:**
Non-scalar `@export`-ed variables should be send to the server without adding a `__typename` field, because input types do not have a `__typename` field.

**Actual outcome:**
Server responds with `Field "__typename" is not defined by type LessonFilter.` because the `$where` variable has an extra `__typename` field added.

**How to reproduce the issue:**
https://codesandbox.io/s/n58767y81p

The query:
``` graphql
  query GetListItems($where: LessonFilter) {
    currentFilter @client @export(as: "where") {
      title_contains
      enabled
    }
    lessonCollection(where: $where) {
      items {
        title
        slug
      }
    }
  }
```
`currentFilter` in cache is like this:
``` javascript
{
      __typename: "LessonFilter",
      title_contains: "SDK",
      enabled: true
}
```

**Versions**
apollo-client@2.5.1 and apollo-client@2.6.0-beta.4

Workaround for me right now is to have client resolved extra field, which is `@export`-ed instead of the original `currentFilter` and clears the extra `__typename`.

**Comment by supercranky** [comment]
I'm having the same problem.

**Comment by OurMajesty** [comment]
According to (updated) reproduction, the error is still there with latest apollo-client 🤔

**Comment by OurMajesty** [comment]
@benjamn 2.6.2 - same error in reproduction, where's the problem? Should I recreate issue?

**Comment by Crysp** [comment]
theirs fixes just remove `__typename` from query. but you should to remove `__typename` from resolver by yourself.

it works for me.

**resolvers.js** - remove from response
```js
export const filter = (root, variables, { cache }, { field }) => {
    const data = cache.readQuery({ query: filterQuery });
    if (field.directives.some(({ name }) => name.value === 'export')) {
        delete data.filter.__typename;
    }
    return data.filter;
};
```

**cache.js** - add when writing cache
```js
const cache = new InMemoryCache({
    dataIdFromObject: (object) => {
        // check some unique field for filter object
        if ('contractual' in object) {
            object.__typename = 'filter';
        }
        return defaultDataIdFromObject(object);
    },
});
```

**Comment by Jayphen** [comment]
Do we really have to manually delete the __typename from the response as above? This seems rather hacky. I don't quite understand how this PR resolved the issue.

Here is a reproduction:
https://codesandbox.io/s/using-local-state-with-gql-server-response-ouqlu
