### ISSUE TITLE
Detecting cache-and-network refetch via networkStatus

### ISSUE THREAD

**Issue by codepunkt** [apollographql/apollo-client#4693]
When fetching a query using fetchPolicy `cache-and-network`, refetching it after the first fetch sets `loading` as if it was the initial fetch, so i'm trying to use `networkStatus` to detect a difference between initial fetch and background refetch.

**Intended outcome:**

`networkState` is set to different values while request is inflight for initial and background cache updating requests.

**Actual outcome:**

`networkState` is `1` while fetching and `7` or `8` when finished - regardless of initial fetch or later background refetch.

**How to reproduce the issue:**

Simple example at https://codesandbox.io/s/24nkjm76q0

If `networkStatus` is not used for this, how do i detect the difference?

**Comment by timhwang21** [comment]
This has been an annoyance for me as well, I've gotten around it by checking to see if `data` is not empty as well.

**Comment by pl12133** [comment]
Looks like https://github.com/apollographql/apollo-client/issues/3660

**Comment by benjamn** [comment]
Closing since we just published the final version of `apollo-client@2.6.0` to npm, including the fix for this issue! See [`CHANGELOG.md`](https://github.com/apollographql/apollo-client/blob/master/CHANGELOG.md#apollo-client-260) if you're curious about the other changes in this release.
