### ISSUE TITLE
Images are not rendering in new doc site

### ISSUE THREAD

**Issue by tanaypratap** [apollographql/apollo-client#4706]
**Intended outcome:**
Image should show up
**Actual outcome:**
![image](https://user-images.githubusercontent.com/10216863/56093211-58af9580-5ee3-11e9-87fc-36a32cf33673.png)
**How to reproduce the issue:**
https://www.apollographql.com/docs/link/overview
Go the link above.

**Comment by tanaypratap** [comment]
you can tag it as `docs` and assign it to me. I will send a PR in this week to fix this. Opening this issue for everyone's reference.

**Comment by abernix** [comment]
This is resolved!

![image](https://user-images.githubusercontent.com/841294/61146397-c8a3cc80-a48e-11e9-85b6-0d1b91c30a65.png)
