### ISSUE TITLE
Query re-fetched before onResetStore callback is run

### ISSUE THREAD

**Issue by bostrom** [apollographql/apollo-client#4712]
I've got an onResetStore callback function that resets the default values to the Apollo local state (i.e. the cache). It seems, however, that when I call client.resetStore() the Query that reads the local state fires (and errors) before the cache-resetting callback has been fired.

```
Found @client directives in query but no client resolvers were specified. You can now pass apollo-link-state resolvers to the ApolloClient constructor. 
```

This makes the component end up in a dead end where the cache doesn't contain the values expected by the query.

Runnable demo of the bug: https://lr3y97kkzq.codesandbox.io/

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
