### ISSUE TITLE
"Timeout reached" calling mutation

### ISSUE THREAD

**Issue by bezugen** [apollographql/apollo-client#4725]
**Intended outcome:**
I called a mutation and sometimes returns an graphql error Timeout reached.

**Actual outcome:**
{"errors":[{"message":"Timeout reached","locations":[{"line":2,"column":3}],"path":["addPost"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["Error: Timeout reached"," at ClientRequest.req.setTimeout (/app/node_modules/centra/model/CentraRequest.js:142:14)"," at Object.onceWrapper (events.js:313:30)"," at emitNone (events.js:106:13)"," at ClientRequest.emit (events.js:208:7)"," at TLSSocket.emitTimeout (_http_client.js:711:34)"," at Object.onceWrapper (events.js:313:30)"," at emitNone (events.js:106:13)"," at TLSSocket.emit (events.js:208:7)"," at TLSSocket.Socket._onTimeout (net.js:420:8)"," at ontimeout (timers.js:482:11)"," at tryOnTimeout (timers.js:317:5)"," at Timer.listOnTimeout (timers.js:277:5)"]}}}],"data":null}

**How to reproduce the issue:**
I'm using apollo server with express on heroku and if I try to run the mutation again sometimes returns success, other returns the same error.
Only happens on heroku not on the localhost.

**Versions**
System:
    OS: macOS Mojave 10.14.3
  Binaries:
    Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 66.0.2
    Safari: 12.0.3
  npmPackages:
    apollo-cache-inmemory: ^1.5.1 => 1.5.1
    apollo-client: ^2.5.1 => 2.5.1
    apollo-link: ^1.2.11 => 1.2.11
    apollo-link-context: ^1.0.17 => 1.0.17
    apollo-link-http: ^1.5.14 => 1.5.14
    react-apollo: ^2.5.4 => 2.5.4
    apollo-server: "^2.4.8",
    apollo-server-express: "^2.4.8",

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
