### ISSUE TITLE
Receive data success but loading still TRUE

### ISSUE THREAD

**Issue by huynguyen2903** [apollographql/apollo-client#4730]
![image](https://user-images.githubusercontent.com/40721082/56437287-f9012200-6308-11e9-9983-d537022599a5.png)
I received data from sever with no error but loading status still return true and never change to false. How I can fix it?
I'm using  `fetchPolicy="cache-and-network"`

**Comment by OurMajesty** [comment]
probably duplicate of https://github.com/apollographql/react-apollo/issues/2899  
did you try react-apollo@2.4.1 ?

**Comment by mikevercoelen** [comment]
Confirmed, we can't easily downgrade since most of our app components are built with `@apollo/react-hooks` which requires at least `2.6.2`

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
