### ISSUE TITLE
No way to add virtual fields to client side data

### ISSUE THREAD

**Issue by gregkerzhner** [apollographql/apollo-client#4731]
Is it possible add virtual fields like this https://www.apollographql.com/docs/tutorial/local-state#virtual-fields to client side queries, just like server side ones?  For example, the ability query 
`query {
    userData @client {
       firstName
       lastName
       fullName
    }
  }`

and add a resolver `{User: {fullName: () => {return firstName + lastName }}}`?  If not, is this something I can contribute?  This type of functionality seems essential for a state management system.

**Comment by OurMajesty** [comment]
https://www.apollographql.com/docs/react/essentials/local-state#querying-local-state

**Comment by OurMajesty** [comment]
remember, there's some problems right now, some are fixed in latest beta, but not all of them

**Comment by jide** [comment]
Is there a list of these known problems ? I know about @export, but would be great to know about other issues. Upgrading from apollo-link-state to 2.6.0-beta.7 breaks my app using local state, and I have no clues what are the issues preventing it to work (Mostly updating cache does not trigger rerender).

**Comment by benjamn** [comment]
@gregkerzhner Have a look at the test I just added in a87d28b44f2d4d4320a08d74daddb905b600aa10. I think the only piece you're missing is the `data` parameter passed to the `fullName` resolver function.

Please feel free to reopen this issue if this test doesn't fully capture your use case!
