### ISSUE TITLE
Apollo isn't obeying exipry of S3

### ISSUE THREAD

**Issue by developdeez** [apollographql/apollo-client#4733]
Apollo is requesting an image from the host on loading a new page rather than obeying the cache-control header when it initially downloads the image.

*I'm using AWS S3 with a 30 second expiry.

**Comment by developdeez** [comment]
bump

**Comment by benjamn** [comment]
As a GraphQL client, Apollo Client generally makes GraphQL requests, not requests for images. It's not clear from the information you provided how to reproduce the problem, or even how it's related to Apollo Client. When you open an issue, please try to read your description from perspective of the maintainers, and provide the kind of information you would find helpful for resolving the problem.
