### ISSUE TITLE
in react-native & apollo-boost client & android, network request fail in builded apk

### ISSUE THREAD

**Issue by devdany** [apollographql/apollo-client#4740]
when i try request to apiserver, it is not problem in android just running by react-native(script: react-native run-android)

but, in builded apk, i got a error 

Network error: Network request failed]

only in apk.

i guessed that the reason is http/https. but, in https same.
runned by react-native => ok, but apk => fail.
 

ApolloClient.js
```
export default new ApolloClient({
    uri: 'https://domain',
    cache: new InMemoryCache(),

    clientState: {
        defaults: defaults,
        resolvers: resolvers
    }
})
```

let me know the reason and solution please.

**Comment by benjamn** [comment]
In order to help you diagnose the problem, we need more information than you've provided here, especially the versions of any Apollo packages you're using, and ideally a runnable reproduction, or at least some idea about the application code that was involved. See [`CONTRIBUTING.md`](https://github.com/apollographql/apollo-client/blob/master/CONTRIBUTING.md#reporting-bugs) for more information about reporting bugs effectively.

Please reopen this issue when you have more information!

**Comment by shahmirn-gcc** [comment]
Running into the same issue. Using React-native 0.59.5, react-apollo 2.5.5, apollo-boost 0.3.1, and apollo-client 2.5.1

Running the app in dev mode, my GQL mutation works fine. Running it in prod mode, I just get:

Network request failed.

**Comment by shahmirn-gcc** [comment]
@benjamn

**Comment by andru1989** [comment]
@shahmirn-gcc @devdany  I'm having the same problem just in builded apk, I just get `Network request failed`, and in graphql server I can't find any new error log, then, react-native application is not reaching the server, have you found a solution for this ? I really appreciate if any of you can help me

**Comment by khalidos32** [comment]
i have the same problem, any solution please 🍡

**Comment by hunght** [comment]
i have same issue, happen on stack     
"apollo-cache-inmemory": "^1.6.3",
    "apollo-client": "^2.6.4",
    "apollo-link": "^1.2.13",
    "apollo-link-context": "^1.0.19",
    "apollo-link-http": "^1.5.16",
    "apollo-link-rest": "^0.7.3",
 "react-apollo": "^3.1.2",

**Comment by ALIKIN6** [comment]
I have the same issue in build
iOS version works fine
even the android version works fine in some older devices but in new devices like Samsung S10, there is an error.
Network error: Network request failed
Weird thing is that debug mode works fine.

**Comment by Ebeldev** [comment]
I do have the same issue. 
I tried different options, apollo-boost, apollo-client-preset. I used graphql query hook and query component. 

In debug moode, the app works perfectly. In release mode, it crashes. 

I use RN 0.61.5, "react-apollo": "^3.1.3".

**Comment by vidyasagarmetta** [comment]
If your link is having http then add the following line in your android manifest file
android:usesCleartextTraffic="true"

**Comment by vidyasagarmetta** [comment]
If your link is having http then add the following line in your android manifest file
android:usesCleartextTraffic="true"

**Comment by LauraBeatris** [comment]
@valentijnnieman Isn't it just related to URis using ``http`` protocol?

**Comment by johnneuland** [comment]
I am getting the same error. My queries work in iOS but give me a network request failed error in Android. Some other solutions suggested that I shouldn't be using ```localhost``` for my ```uri``` and should use my computer's IP address. But I am already not using localhost. 
```
const httpLink = createHttpLink({
    uri: 'https://gateway_dev.companyName.en/v1/graphql',
  });

  const authLink = setContext(async (_, { headers }) => {
    const token = await auth().currentUser?.getIdToken();
    return {
      headers: {
        ...headers,
        authorization: token ? `Bearer ${token}` : '',
      },
    };
  });

  const client = new ApolloClient({
    link: authLink.concat(httpLink),
    cache: new InMemoryCache({}),
  });

  return (
    <Provider store={store}>
        <ApolloProvider client={client}>
...
```
The uri I am using is the Graphql Endpoint POST url from my Hasura console. I am testing by using an Android emulator from the Android Studio and not on a real device. What else could I try?

I also tried adding this ```android:usesCleartextTraffic="true"``` to **AndroidManifest.xml** file but it doesn't make a difference.

**Comment by marf** [comment]
Hello, we have the same problems. Has someone solved it?

**Comment by ghyath5** [comment]
Any solution here !??? 
I'm facing same issue on some of android devices.
