### ISSUE TITLE
Using a refetch query that has references @client fields will set those fields to blank

### ISSUE THREAD

**Issue by jdalegonzalez** [apollographql/apollo-client#4741]
**Intended outcome:**
Define a query that includes both server side fields and client side fields.  Use that query to initially populate values but also re-populate them as needed
 like...
```
FETCH_INITIAL_DATA = gql`
  query FetchInitialData {
    serverData {
      id
      title
    }
    selectedItemId @client
  }
`;
```
.
.
.
```
  client.mutate({
    mutation: DO_SOMETHING,
    variables: {
      var1,
      var2,
    },
    refetchQueries: [
      'FetchInitialData'
    ]
  });
```
**Actual outcome:**
Any @client fields associated with a query will be set to empty string when the refetch is called.
This is because of line 169 in apollo-client/core/QueryManager.js
```
        if (fetchType !== FetchType.refetch &&
```
Likely, the intent here was to be sure that refetch queries always went and got server data no matter what the fetch policy was.  However, in the case of @client, the data should likely always be pulled from cache.

**How to reproduce the issue:**
1. Define a query with @client directives.
2. Use writeQuery to write a value to one of the @client fields
3. Add the query to the refetchQueries block of a mutation
4. Trigger the mutation.

**Versions**
  System:
    OS: macOS Mojave 10.14.4
  Binaries:
    Node: 11.9.0 - /usr/local/bin/node
    Yarn: 1.15.2 - ~/axiodev/axio360/client/node_modules/.bin/yarn
    npm: 6.9.0 - ~/axiodev/axio360/client/node_modules/.bin/npm
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 65.0.1
    Safari: 12.1

apollo@2.8.3

**Comment by benjamn** [comment]
@jdalegonzalez Thanks for going the extra mile to identify the source of the problem! When you have a chance, could you verify that the test included in https://github.com/apollographql/apollo-client/commit/82e75305010fa1dc34d0e68b3ae402670fee2e5c accurately represents your use case? This change will be available in the next beta version of `apollo-client@2.6.0`.

**Comment by jdalegonzalez** [comment]
@benjamn It is almost representative, perhaps close enough?  The test fixture only has client fields, no server ones.  As a result, this test could pass and a test of refetch that only had server fields could pass and a yet a refetch query that contains a mix of server and client fields (which is what we have) could still fail - depending on how the fix is implemented.

Thanks for looking at this.
