### ISSUE TITLE
client.query() with fetchPolicy `cache-only` returns partial result, cache-first does not

### ISSUE THREAD

**Issue by Narretz** [apollographql/apollo-client#4750]
**Intended outcome:**
- I have a two different queries that both return the same entity
- query 1 returns field a
- query 2 returns field a + b
- I run query 1 with default fetchPolicy, then later query 2 with `cache-only`
- according to https://github.com/apollographql/apollo-client/issues/2977, apollo-client should not return data when the cache match is partial
- if I use `cache-only`, query 2 should therefore return no data

**Actual outcome:**
- query 2 with `cache-only`, returns the partial data from query 1

For the sake of consistency, apollo-client should either never return partial data, or always - or make it configurable. For example, if I use fetchPolicy cache-first, I currently do not get the partial match first, it immediately goes to the server.

**How to reproduce the issue:**

You can see a repro here: https://codesandbox.io/s/2w2zljk0k0?fontsize=14

(Look into the console)

The weird thing is that the react implementation does not return a partial cache match,

**Versions**
apollo-client@2.5.1
apollo-cache-inmemory@1.5.1

**Comment by riccoski** [comment]
I'm getting the same... however I like it. I don't have to do multiple cache only queries :D

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
