### ISSUE TITLE
Resolvers required for @client is a lot more strict than apollo-link-schema

### ISSUE THREAD

**Issue by randing89** [apollographql/apollo-client#4751]
Resolvers required for `@client` is a lot more strict than `apollo-link-schema`.
I noticed the resolvers for `@client` have to return `__typename` for every no-scalar fields.  Also missing a field value will result the whole object to be empty. 

**Intended outcome:**
`@client` directive maintains backward compatibility with `apollo-link-schema`

**Actual outcome:**
`@client` requires `__typename` defined in the result of every no-scalar fields. Also requires every fields to be appeared in the result from a resolver.

**How to reproduce the issue:**
https://codesandbox.io/s/vjz7qr19xy

Two clients were setup using the same schema. Both return correct data when the resolver is providing `__typename` and all the fields.
```
export const resolvers = {
  Query: {
    apollo: () => {
      return {
        cool: true,
        bug: true,
        __typename: 'Apollo',
      };
    },
  },
};
```

Removing one field from the resolver will result the client using `@client` to return an empty object.
```
export const resolvers = {
  Query: {
    apollo: () => {
      return {
        cool: true,
        __typename: 'Apollo',
      };
    },
  },
};
```

**Comment by sdebaun** [comment]
+1 "why do I have to define __ypename now"?

I used apollo-link-state &c on a small project middle of 2018 and it was drop dead easy.  Using the new features built in to apollo-client, I now have to specify __typename on every object I return?  Why?

**Comment by JoviDeCroock** [comment]
I think we'll need a way for allowing partial results, at this point it's not possible.

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
