### ISSUE TITLE
@client does not handle promise rejection in resolver

### ISSUE THREAD

**Issue by randing89** [apollographql/apollo-client#4757]
Promise rejection for error thrown from the resolvers of @client field are not getting populated to the graphQLErrors field. The error is ignored.

**Intended outcome:**
Error being put into `graphQLErrors`

**Actual outcome:**
Error is being ignored

**How to reproduce the issue:**
https://codesandbox.io/s/vq4nqmll87

**Comment by benjamn** [comment]
Thanks for reporting this issue, and for providing a reproduction! Would it be fair to say this is a duplicate of #4575? Since I suspect it is a duplicate, I'm going to close this issue now, but please feel free to reopen this issue if you think it's different.

**Comment by randing89** [comment]
Thanks. I will watch #4575
