### ISSUE TITLE
Change autorization header of current instance

### ISSUE THREAD

**Issue by l1zard** [apollographql/apollo-client#4775]
Hello,
I have problem with changing the link in apollo client.

**Example:**
I have a single instance in apollo and on Auth Screen just adding the token after user login. After logout and login different user i want to  change user token (with same flow of auth screen) but the header keep the same value as before. Some advice?

**Comment by OurMajesty** [comment]
https://www.apollographql.com/docs/react/recipes/authentication/

**Comment by hwillson** [comment]
See https://github.com/apollographql/apollo-client/issues/4775#issuecomment-499818542 for the answer. Thanks!
