### ISSUE TITLE
Allow option for partial results for cache.readQuery

### ISSUE THREAD

**Issue by fzxt** [apollographql/apollo-client#4779]
**Intended outcome:**
Trying to read data from the cache, but I'm asking for an additional field. I don't know what's in the cache. I just want to read whatever is already there, for the cached item.

Suppose the cache (key, value) looks like:
```js
Todo-id:  {
   content: "Cool stuff"
}
```

I called and expected (assume query is well formed, haven't double checked my syntax here)
```js
const data = cache.readQuery({
   query: gql`query { 
          todo {
               name, 
               description
         } 
     }`
);

// Expect data == { todo: { content: 'Cool stuff' }};
```

**Actual outcome:**
Instead, I get an error about a missing field, coming from [readFromStore](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-cache-inmemory/src/readFromStore.ts#L239). 

**How to reproduce the issue:**
Try to call cache.readQuery with a query that has missing fields, based on the data that's in the cache.

**Versions**
```
  System:
    OS: macOS Mojave 10.14
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    Yarn: 1.10.1 - ~/.yarn/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 64.0
    Safari: 12.0
  npmPackages:
    apollo-angular: ^1.5.0 => 1.5.0
    apollo-angular-link-http: ^1.3.1 => 1.5.0
    apollo-cache-inmemory: ^1.3.2 => 1.5.1
    apollo-cache-logger: ^1.1.1 => 1.1.1
    apollo-client: ^2.4.0 => 2.5.1
    apollo-link: ^1.2.0 => 1.2.11
    apollo-link-error: ^1.1.10 => 1.1.10
    apollo-link-rest: ^0.7.0 => 0.7.0
    apollo-link-schema: ^1.2.2 => 1.2.2
```

**Suggested fix**
It's interesting because there is an option for `partialResults`, however, `DataProxy` has no way to ever set it to `true`, since it's been [hardcoded to false](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-cache-inmemory/src/readFromStore.ts#L182-L187)

I'm happy to submit a PR to fix this upstream.

**Workaround**
My workaround for this issue is to completely override the readQuery method so that it doesnt call `storeReader.readQueryFromStore`

```typescript
    // This method has to be overriden due to a hardcoded value
    // The workaround is to bypass the storeReader.readQueryFromStore
    // @see https://github.com/apollographql/apollo-client/blob/master/packages/apollo-cache-inmemory/src/readFromStore.ts#L239
    // @see https://github.com/apollographql/apollo-client/issues/4779
    readQuery(options, optimistic?: boolean) {
        if (typeof options.rootId === 'string' &&
            // @ts-ignore
            typeof this.data.get(options.rootId) === 'undefined') {
            return null;
        }

        const config = {
            // @ts-ignore
            store: options.optimistic ? this.optimisticData : this.data,
            query: this.transformDocument(options.query),
            variables: options.variables,
            rootId: options.rootId,
            fragmentMatcherFunction: this.config.fragmentMatcher.match,
            previousResult: options.previousResult,
            config: this.config,
        };

        // @ts-ignore
        return this.storeReader.diffQueryAgainstStore(config).result;
    }
```

Obviously, this is less than ideal.

**Comment by benjamn** [comment]
Why not use `cache.diffQuery({ ..., returnPartialData: true })`?

**Comment by fzxt** [comment]
@benjamn Never quite occurred to me to just use `.diff`. :) 

Closing this issue, thank you.

**Comment by MrLoh** [comment]
@benjamn I am also looking for a wary to read and write partial queries from the store, I have no idea what `cache.diff` is and it doesn't seem documented anywhere. Is there any way to do this? I am not even finding proper API documentation for `cache.readQuery` arguments

**Comment by MrLoh** [comment]
To answer my own question `client.writeData` or `client.cache.write` should do the trick
