### ISSUE TITLE
CodeSandbox for "Queries" is broken

### ISSUE THREAD

**Issue by brunocrosier** [apollographql/apollo-client#4780]
On the page: https://www.apollographql.com/docs/react/essentials/queries

The [CodeSandbox](https://codesandbox.io/s/n3jykqpxwm) is broken due to the GraphQL server being down

`
const client = new ApolloClient({
  uri: `https://nx9zvp49q7.lp.gql.zone/graphql`
});`

the [endpoint](https://nx9zvp49q7.lp.gql.zone/graphql) does not work

**Comment by brunocrosier** [comment]
It seems that if you switch the client uri for "https://dog-graphql-api.glitch.me/graphql" then it will work correctly

**Comment by hwillson** [comment]
Refer to the most recent [docs](https://www.apollographql.com/docs/react/data) for supported examples. Thanks!
