### ISSUE TITLE
Mutation onCompleted not running when set to the render prop

### ISSUE THREAD

**Issue by tafelito** [apollographql/apollo-client#4782]
I run into an issue where I need to navigate to a new screen when a mutation is completed. Debugging the code I can see that the OnCompleted callback is only being fired if is passed as a prop to the mutation, but it does not if is passed as a prop of the render prop. Pretty much what I need to do is the same as with the variables prop. 

**Intended outcome:**
this is an example of what I'm trying to do
```
<Mutation mutation={mut}>
            {updateMutation => {
              return (
                <Component {...{ updateMutation }} />
              );
            }}
</Mutation>
```
Then, within the component 
```
function Component({updateMutation}) {
    return (
        <Button onPress={()=> {
                updateMutation({
                    variables: {...},
                    onCompleted: ()=> {...}
                })
        } />
    )
}
```

**Actual outcome:**
The onCompleted callback not being fired. The onCompleted has to be assigned to the Mutation component, but I can't do that because I need some values for the child component.

**Versions**
```
  System:
    OS: macOS Mojave 10.14.4
  Binaries:
    Node: 11.11.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 73.0.3683.103
    Safari: 12.1
  npmPackages:
    apollo-link-state: ^0.4.2 => 0.4.2 
    react-apollo: ^2.5.5 => 2.5.5 
```
-->

**Comment by frederikhors** [comment]
@tafelito I have the same problem. Why did you close it?

**Comment by tafelito** [comment]
Because you don't need to do that. You can just await the mutation
