### ISSUE TITLE
Typings for apollo-boost ApolloClient do not align with documentation

### ISSUE THREAD

**Issue by jamesism** [apollographql/apollo-client#4795]
**Intended outcome:**
`apollo-boost` should export accurate typescript typings for the [diverging options](https://www.apollographql.com/docs/react/essentials/get-started#configuration) to ApolloClient.

**Actual outcome:**

`apollo-boost` seems to export the typings for the [existing options](https://www.apollographql.com/docs/react/api/apollo-client) that one can pass to `ApolloClient` from the `apollo-client` package.
 
**How to reproduce the issue:**

Use `apollo-boost` and attempt to pass the `headers` option that is exclusive to `apollo-boost`.

**Versions**
```
  System:
    OS: macOS 10.14.3
  Binaries:
    Node: 10.14.0 - ~/.nvm/versions/node/v10.14.0/bin/node
    Yarn: 1.10.1 - ~/.dev/yarn/1.10.1/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.0/bin/npm
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 64.0
    Safari: 12.0.3
  npmPackages:
    apollo-boost: ^0.3.1 => 0.3.1 
    apollo-link: ^1.2.11 => 1.2.11 
    apollo-upload-client: ^10.0.0 => 10.0.0 
    react-apollo: ^2.5.4 => 2.5.4 
```

**Comment by johny** [comment]
Any updates on this issue? 

The type definition for the `ApolloClient` from `apollo-boost` are not matching the documentation in https://www.apollographql.com/docs/react/essentials/get-started/#configuration-options

**Comment by hwillson** [comment]
Apollo Boost is no longer supported, since `@apollo/client` provides most of the same functionality. Thanks!
