### ISSUE TITLE
Invariant Violation: 1 in IE11

### ISSUE THREAD

**Issue by rico345100** [apollographql/apollo-client#4802]
**Intended outcome:**
Work with IE11. Note that using core-js as polyfill ES6 features.

**Actual outcome:**
It saids

> SCRIPT5022: Invariant Violation: 1 (see: https://github.com/apollographql/invariant-packages)

What is that mean, especially "1", is there an any reference about that error message?

**Versions**
```
  System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 66.0.2
    Safari: 12.1
  npmPackages:
    apollo-cache-inmemory: ^1.2.8 => 1.3.12 
    apollo-client: ^2.4.0 => 2.4.12 
    apollo-link: ^1.2.6 => 1.2.6 
    apollo-link-error: ^1.1.5 => 1.1.5 
    apollo-link-http: ^1.5.4 => 1.5.9 
    apollo-link-ws: ^1.0.8 => 1.0.12 
    react-apollo: ^2.1.11 => 2.4.0 
```

**Comment by akbarik** [comment]
Also have this error

**Comment by hwillson** [comment]
See https://github.com/apollographql/apollo-client/issues/4802#issuecomment-499063598 for the solution. Thanks!
