### ISSUE TITLE
React Native: Data in local state is being deleted 

### ISSUE THREAD

**Issue by schmitzl** [apollographql/apollo-client#4803]
I am using apollo client in a react native app. I want to store some information locally in the cache. I write the following data into the cache, after I initialized the apollo client:

```
cache.writeData({
  data: {
    todos: [
      {
        title: 'My first todo',
        __typename: 'Todo',
      }
    ]
  },
})
```

Then I have a query component, that uses this data: 
```
const GET_TODOS = gql`
  {
    todos @client {
      title
    }
  }
`
```

```
<Query query={GET_TODOS}>
  { ({ loading, error, data }) => {
    if (loading) return <Text>Loading...<Text>Loading..."</Text></Text>
    if (error) return <Text>Error!</Text>

    return (
      <View>
        { data.todos && data.todos.map( todo => <Text>{todo.title}</Text>)
        }
      </View>
    )
  }}
</Query>
```
Now I run the app on the iPhone simulator. 

**Intended outcome:**
I expect that the data, that I initially wrote into the store is displayed. I also expect, that the data in the store stays there unchanged until I call a mutation, that manipulates it.

**Actual outcome:**
At first, it looks like the cache does what is expected and shows the correct content. However, if I open another view, that also queries the todos, suddenly no data is returned. The answer to the query is only an empty object. Where did the data go? Why did it get deleted from the store, just by being queried?

**Versions**
_System:_
    OS: macOS 10.14.4

  _Binaries:_
    Node: 11.14.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm

  _Browsers:_
    Chrome: 74.0.3729.131
    Firefox: 66.0.5
    Safari: 12.1

  _npmPackages:_
    apollo-cache-inmemory: ^1.5.1 => 1.5.1 
    apollo-cache-persist: ^0.1.1 => 0.1.1 
    apollo-client: ^2.5.1 => 2.5.1 
    apollo-link-context: ^1.0.17 => 1.0.17 
    apollo-link-http: ^1.5.14 => 1.5.14 
    react-apollo: ^2.5.4 => 2.5.5

**Comment by schmitzl** [comment]
Upon looking further into it, it seems that the actual problem, that causes the loss of data, is a server query. So first, the query to the cache is successful and the todos data is still there. Then a server query (with completely different fields) is sent and overwrites the entire cache data with the result. It seems to be a similar issue as here: https://github.com/apollographql/apollo-link-state/issues/236
However, I am even using a newer version than apollo client 2.5, where this is supposed to be fixed.

**Comment by schmitzl** [comment]
The persistCache function seemed to have been the problem. I wrote the default todos data into the cache, before the persistCache function was finished successfully. I guess that at some point in this function, my local default state got overwritten. I now await the persistCache function and only after that do I call cache.writeData. This seems to have fixed the problem.

**Comment by adam-vermes** [comment]
I had a similar problem with the cache resetting after each refresh. 

According to the apollo3-cache-persist docs: 
```
// await before instantiating ApolloClient, else queries might run before the cache is persisted
await persistCache({
  cache,
  storage: new AsyncStorageWrapper(AsyncStorage),
});
```

As it turns out I needed to resolve the persistCache before setting the ApolloClient and the cache was restored after each refresh.
