### ISSUE TITLE
refetchQueries as string array, not using current variables

### ISSUE THREAD

**Issue by shrestaz** [apollographql/apollo-client#4805]
**Intended outcome:**
After a mutation my goal is to refetch queries with the current variables. This is described [here](https://www.apollographql.com/docs/react/advanced/caching): 

> Please note that if you call refetchQueries with an array of strings, then Apollo Client will look for any previously called queries that have the same names as the provided strings. It will then refetch those queries with their current variables.

**Actual outcome:**
The query _is_ called, but **not** with the current variables. (it's called with the initial variables).

**How to reproduce the issue:**
1. Run the server first from [codesandbox](https://codesandbox.io/embed/52337pvl8x).
2. Visit [stackblitz](https://angular-uqdm6d.stackblitz.io), with developer console open. Use the pagination to go the the second page, and click on the button to add new todo. Inspect the graphql requests made to `52337pvl8x.sse.codesandbox.io` on the network tab of the developer console with mutataion `createTodo`.

**Versions**
Apollo client: `2.5.1`
Apollo server:  `2.1.0`

As this screenshot indicates, the variables are always the initial variables after mutation. 
![Screenshot_20190513_153737](https://user-images.githubusercontent.com/9460504/57625892-0d95aa80-7595-11e9-9b6b-f6d457ac5a62.png)

Expected variables should be like the following:
![Screenshot_20190513_153912](https://user-images.githubusercontent.com/9460504/57626064-6a916080-7595-11e9-80aa-78754faf64ec.png)

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
