### ISSUE TITLE
Apollo isn't caching errors

### ISSUE THREAD

**Issue by KevinHewson** [apollographql/apollo-client#4806]
After navigating in my React app, I'm noticing that the errors that occurred after a successful query are not getting cached. 

I'm using `errorPolicy: "all"`.  According to the documentation [here](https://www.apollographql.com/docs/react/features/error-handling), I would expect that it `"saves both data and errors into the Apollo Cache"`

**Intended outcome**
When GraphQL returns
```
{
  data: { ... },
  errors: [...]
}
```
I would expect Apollo to cache both data and errors.

**Actual outcome**
Apollo will pull `data` from the cache, but not errors. `error` ends up being undefined.

**How to reproduce the issue**
Create a query that results in an error and data.  Navigate away from component and then back and notice that the data will get pulled from cache, but errors will not.

**Version**
`apollo-client` version `2.5.1`
`react-apollo` version `2.5.2`

**Comment by KevinHewson** [comment]
I did some more digging through the reported issues, and I think I have found a related issue [#4644](https://github.com/apollographql/apollo-client/issues/4644).  This appears to be a pretty critical bug, especially since the documentation specifically states that it should be caching both data and errors.

**Comment by hwillson** [comment]
Please open a feature request for this in https://github.com/apollographql/apollo-feature-requests. Thanks!

**Comment by KevinHewson** [comment]
I just want to make sure I understand this correctly.  Are you saying the documentation is incorrect when it says 

> `all`: Using the `all` policy is the best way to notify your users of potential issues while still showing as much data as possible from your server. **It saves both data and errors into the Apollo Cache so your UI can use them.**

If that's true, then I guess I agree that this should be a feature request.  But if not, this is clearly a bug that should be fixed because the errors are **not** saved to the cache.

**Comment by hwillson** [comment]
> It saves both data and errors into the Apollo Cache so your UI can use them.

@KevinHewson the above used to be technically accurate, but is unfortunately a bit misleading. When people read this they think that errors are saved into the in-memory based normalized cache itself, as in what you see if you dump out `window.__APOLLO_CLIENT__.cache.data.data` in your browser console. This doesn't happen. Instead, the previous error is saved in memory, so it can be sent back to the UI. The saving of this error in memory used to be part of the Apollo Cache codebase, which is where the wording of the above came from. Apollo Cache is being used here to represent all of the Apollo Cache functionality, not just the actual data store. A lot of this has changed in Apollo Client 3, but errors are still not stored in the cache itself. This is something we would like to consider doing though, so a feature request to track this would be great. I'll also update the docs to be more clear. Thanks!
