### ISSUE TITLE
Lock the cache, during cache updates

### ISSUE THREAD

**Issue by Jaikant** [apollographql/apollo-client#4819]
I have a page with multiple buttons which trigger a mutation, which does an `optimisticResponse` and an `update` to the cache. 

I am hitting a race condition which causes cache inconsistency when a user does multiple mutations in quick succession. I think the inconsistency happens because in the `update` function I do a `readQuery` followed by a `writeQuery`. As the `readQuery` is an async operation, in that duration the cache could be modified by another user event.

There should be a way to lock the cache during `updates` so we can avoid any such issues.

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
