### ISSUE TITLE
Apollo-client 2.5 state management resolvers not firing correctly

### ISSUE THREAD

**Issue by alex-hioperator** [apollographql/apollo-client#4841]
**Intended outcome:**
I am working towards replacing our app's state management with  apollo-client 2.5's local state management (because graphql is awesome). 

I have the following query

```
query GetClient {
  client(id: "0y9FVRmIiDIIhjr1czVi", live: true) @client {
    id
    name
    queueCount
    updated
    tickets @client {
      id
      deleted
      comments @client {
        id
	author_email
	public
      }
    }
  }
}
```

Here is what my resolver looks like:
```
Query: {
	client: async (parent, { id, live }, context, info) => {
                // DO SOME STUFF
                var data = {} // DATA is actually returned after some stuff is done
		return data;
	}
},
Client: {
	tickets: async (client, { live }, context, info) => {
	        // DO SOME STUFF
                var data = {} // DATA is actually returned after some stuff is done
		return data;
	}
},
Ticket: {
	comments: async (parent, { live }, context, info) => {
		// DO SOME STUFF
                var data = {} // DATA is actually returned after some stuff is done
		return data;
	}
}
```

What I expect for the query to do is to start in the Query --> client section, and then after I return the data from there, to go to the Client --> tickets section of the resolver to run the logic there, and once each ticket is retrieved, it goes down to the Ticket --> comments section.

**Actual outcome:**

The Query --> client section fires, but neither the Client --> tickets nor Ticket --> comments section fire :(. I have tried removing the @clients decorators on the tickets and comments parts of the query, still no luck.

**How to reproduce the issue:**
See above code

**Versions**
System:
    OS: macOS 10.14.4
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 74.0.3729.157
    Firefox: 62.0
    Safari: 12.1
  npmPackages:
    apollo-boost: ^0.3.1 => 0.3.1 
    apollo-client: ^2.5.1 => 2.5.1 
    react-apollo: ^2.5.5 => 2.5.5

**Comment by benjamn** [comment]
@alex-hioperator I tried adding a regression test to reproduce this problem (see https://github.com/apollographql/apollo-client/commit/b78bb8808813091f1fa91bd29551eeb1b92dc31a), but it doesn't seem to fail on either the `release-2.6.0` or the `master` branch. Is it possible that the problem has something to do with the `tickets` and `comments` fields not accepting a `live` argument in the query? If so, something like this might work:
```gql
query GetClient {
  client(id: "0y9FVRmIiDIIhjr1czVi", live: true) @client {
    id
    name
    queueCount
    updated
    tickets(live: true) @client {
      id
      deleted
      comments(live: true) @client {
        id
        author_email
        public
      }
    }
  }
}
```

**Comment by alex-hioperator** [comment]
Hey Ben,

Thanks for looking into this for me! Fascinating that its working fine for you. 

Just to idiot check it, would you mind seeing if you replicate it if you use 2.5? Or even 2.6.0-beta.7?

I've tried removing the live argument and it doesnt work :(. Including it also doesn't work for me :(. 

I do wonder if its something thats resolved and is just in pre-release.

**Comment by alex-hioperator** [comment]
Hey Ben,

Progress! It seems that they key is declaring a __typename. So if I set the __typename on the return of the query, then it triggers everything correctly.

**Comment by alex-hioperator** [comment]
In reading the docs some more, it appears I did this to myself by having a custom dataIdFromObject property. Which disables the auto __typename-ing. So I think this all does work as intended!

**Comment by benjamn** [comment]
Ok, that is great to hear! Thank you so much for continuing to dig into this, especially as we're hoping to release 2.6.0 soon. I did try it with 2.5.1, which is why I thought there must be something else going on. I wonder if we could provide better warnings when `dataIdFromObject` is inconsistent with other behaviors like `__typename` injection, though I'm not entirely sure how to detect that programmatically. Something to keep thinking about!
