### ISSUE TITLE
Cannot set property default of #<Object> which has only a getter

### ISSUE THREAD

**Issue by hmmhmmhm** [apollographql/apollo-client#4843]
**Intended outcome:**

I just tried to import the apolo boost in a node js environment that uses typescript.
```ts
import {ApolloClient} from 'apollo-boost'
```

**Actual outcome:**

```bash
TypeError: Cannot set property default of #<Object> which has only a getter
    at Object.<anonymous> (h:\Private#2019\Project\_local\article-glow\core\node_modules\apollo-boost\lib\bundle.cjs.js:158:17)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (h:\Private#2019\Project\_local\article-glow\core\src\Backend\Sequence\After.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
```

**How to reproduce the issue:**

install `apollo-boost` and trying import
```bash
npm install --save apollo-boost
```

**Versions**

```bash
  System:
    OS: Windows 10
  Binaries:
    Node: 11.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.12.3 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 41.16299.15.0
  npmPackages:
    apollo-boost: ^0.4.0 => 0.4.0
    apollo-cache-inmemory: ^1.6.0 => 1.6.0
    apollo-link-http: ^1.5.14 => 1.5.14
    apollo-server: ^2.4.8 => 2.5.0
    apollo-server-express: ^2.4.8 => 2.5.0
```

**Comment by gridviewdesign** [comment]
I am having this issue as well using 0.4.0.  Reverting back to 0.1.16 resolved my issue for the time being.

**Comment by lastnamearya** [comment]
I'm having a similiar issue with Next.js & Apollo Client configuration, reverting back to old versions solved my issues for now.

**Comment by musemind** [comment]
Also having this issue with `new ApolloClient()` an TypeScript + ReactNative + Expo setup:
![File](https://user-images.githubusercontent.com/11320794/58166146-7d88ec80-7c89-11e9-846b-5e7648d90ed2.jpg)
The import `import ApolloClient from 'apollo-boost'` alone does not cause any error.

**Comment by gavrichards** [comment]
Also having this issue when updating:

- apollo-boost to 0.4.0
- apollo-client to 2.6.0
- react-apollo to 2.5.6

**Comment by drewbietron** [comment]
Had the issue with `apollo-boost -> 0.4.0` and went back to `0.3.1` per @musemind's post and it fixed the issue.  I tried multiple config options, and even no config at all and the issue still remained.

**Comment by StefKors** [comment]
I have a similar issue after updating to 0.4.0

**Comment by kingRayhan** [comment]
I had the exact same issue with `0.4.0`, then I downgraded to `0.3.1` then everything worked fine

**Comment by MMT-LD** [comment]
Same for me. Downgrading fixed it.

**Comment by vomchik** [comment]
Temporary workaround `import ApolloClient from "apollo-boost/lib/index";`

**Comment by yofr4nk** [comment]
If downgrade it, we'd lose the basic configuration that apollo-boost bring with 0.4.0. The exporting of DefaultClient is wrong in bundle file, The @vomchik workaround could work for now.

**Comment by benjamn** [comment]
This appears to be a bug in the Rollup CommonJS output for `apollo-boost/lib/bundle.cjs.js`.

In order to compile
```js
export * from "apollo-client"
export default class DefaultClient { ... }
```
Rollup generates the following code:
```js
var ApolloClient__default = require('apollo-client');

Object.keys(ApolloClient__default).forEach(function (key) {
    Object.defineProperty(exports, key, {
        enumerable: true,
        get: function () {
            return ApolloClient__default[key];
        }
    });
});

exports.default = DefaultClient;
```
However, because `apollo-client` also has a `default` export, that `default` export is mistakenly defined on `exports` in the `forEach` loop by `Object.defineProperty` in a way that cannot simply be overridden by the `exports.default = DefaultClient` assignment. That's why you're seeing the error
```
Cannot set property default of #<Object> which has only a getter
```

According to the ECMAScript specification, the `default` export should actually be excluded when doing `export * from "apollo-client"`. When I first learned about this gotcha, [it surprised me too](https://github.com/tc39/ecma262/issues/948), but the TC39 committee (including myself) have reached a firm consensus on this behavior, and Rollup is violating the specification by copying over all exported properties of `apollo-client`.

I will open other issues in the appropriate places, but I wanted to give everyone an update here first.

**Comment by benjamn** [comment]
For reference, here's how Babel compiles the code above:
```js
"use strict";

exports.__esModule = true;
var _exportNames = {};
exports.default = void 0;

var _apolloClient = require("apollo-client");

Object.keys(_apolloClient).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  if (Object.prototype.hasOwnProperty.call(_exportNames, key)) return;
  exports[key] = _apolloClient[key];
});

var DefaultClient = function DefaultClient() {};

exports.default = DefaultClient;
```
[Here](https://babeljs.io/repl#?babili=false&browsers=IE%2011&build=&builtIns=false&spec=false&loose=true&code_lz=KYDwDg9gTgLgBAKjgMyhAtnARAQ0gG3wgFoBjfAS2ADsYsAoUSWOAE2GRwFd95ycAzgLgARDt14BhSjXgBvOAF8gA&debug=true&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.4.5&externalPlugins=%40babel%2Fplugin-transform-runtime%407.4.4)'s a link to a REPL you can play with.

**Comment by benjamn** [comment]
This should be fixed in `apollo-boost@0.4.1` (just released).

**Comment by DarkSmile92** [comment]
> This should be fixed in `apollo-boost@0.4.1` (just released).

I just installed `0.4.1` and it fixed the issue (Y)

**Comment by mattschoch** [comment]
FYI, this issue happened to me because I had `apollo-boost: 0.3.1` as a dependency, but `apollo-boost` has `apollo-client: ^2.5.1` as it's dependency, so it pulled in `apollo-client@2.6.1` which breaks. Upgrading boost to `0.4.1` fixed it for me, but it might be a good idea to not use carats in the dependencies in order to avoid this.

**Comment by benjamn** [comment]
Just to expand on what @mattschoch suggested above, it might be a good idea to use `~` instead of `^`, since `^2.5.1` matches `2.6.1`, but `~2.5.1` only matches `2.5.x` versions.

**Comment by vfonic** [comment]
> Just to expand on what @mattschoch suggested above, it might be a good idea to use `~` instead of `^`, since `^2.5.1` matches `2.6.1`, but `~2.5.1` only matches `2.5.x` versions.

Just to expand on this, coming from ruby community, using `~` is the most common way...although, if you're using semantic versioning, minor and patch version bumps _should not_ break anything, so `^` seems to make more sense...
