### ISSUE TITLE
Loading is resolved twice (except for cache-first)

### ISSUE THREAD

**Issue by antiold** [apollographql/apollo-client#4844]
Given the following code:
```javascript
<Query query={query} fetchPolicy={fp}>
  {({ loading, data }) => {
    console.log(loading, data);
    return "look at the console!";
  }}
</Query>
```
`fp` can be `network-only`, `cache-and-network`, `no-cache`.

Apollo client [version 2.6.3](https://codesandbox.io/s/apollo-iqvy4) outputs:
```
true Object {  }
true Object {  }
false Object { result: […] }
```

Apollo client [version 2.3.2](https://codesandbox.io/s/apollo-zkxnq) outputs:
```
true Object {  }
false Object { result: […] }
```
Only `cache-first` in `2.6.3` will output this.

Why?

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
