### ISSUE TITLE
Initial loading state is never resolved

### ISSUE THREAD

**Issue by OurMajesty** [apollographql/apollo-client#4846]
**Intended outcome:**
After component is mounted, loading should be true and eventually would become false, when query is resolved.

**Actual outcome:**
Initial loading is true and never changes until variables are changed

**How to reproduce the issue:**
https://codesandbox.io/s/8znyn79n80

**Versions**
apollo-client@2.6.0
react-apollo@2.5.5

**Comment by OurMajesty** [comment]
apollo-client@2.5.1 doesn't have the error

**Comment by antiold** [comment]
Should probably revert [this](https://github.com/apollographql/apollo-client/commit/9e618f2eaf52d0817ed7f120932b4c1fea084134).
Aaaaaand review some apollo tests files.

**Comment by OurMajesty** [comment]
The error is because of  `fetchPolicy="network-only"` of Query component (Items.jsx, line 60), if I remove it, loading is resolving fine.

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
