### ISSUE TITLE
Since 2.6.0, FetchPolicy and react-apollo types that depend on it are broken

### ISSUE THREAD

**Issue by adrienharnay** [apollographql/apollo-client#4847]
**Intended outcome:**
`<Query fetchPolicy="cache-and-network" />` should be valid.

**Actual outcome:**

This change: https://github.com/apollographql/apollo-client/commit/cf069bc7ee6577092234b0eb0ac32e05d50f5a1c#diff-88b34d7add139a9c0e7d4c2b1944a8dc

broke all external types that depend on FetchPolicy, e.g.
```
export interface QueryOpts<TGraphQLVariables = OperationVariables> {
    ssr?: boolean;
    variables?: TGraphQLVariables;
    fetchPolicy?: FetchPolicy;
    ...
```
used by the `Query` class.

**How to reproduce the issue:**
Update apollo-client and write `<Query fetchPolicy="cache-and-network" />` in a typescript project.

**Versions**

```
System:
    OS: macOS 10.14.4
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.16.0 - ~/Documents/GitHub/brigad/front-end/node_modules/.bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.157
    Firefox: 65.0
    Safari: 12.1
  npmPackages:
    apollo: 2.12.2 => 2.12.2 
```

**Comment by alamothe** [comment]
Same issue. Does this mean `cache-and-network` is broken in `2.6.0`?

**Comment by adrienharnay** [comment]
It does work, only the types are mistaken 🙂

**Comment by benjamn** [comment]
Thanks for reporting this issue, as we certainly did not intend this to be as surprising as it must have been. That said, this type change is meaningful, and adjusting your code to accommodate the new types is a good idea.

I've just released `react-apollo@2.5.6` which correctly uses `WatchQueryFetchPolicy`, and added a [note](https://github.com/apollographql/apollo-client/commit/57dab1e5ac77789b2866126e54216ae3154d0cd5) to `CHANGELOG.md` about this change.

Please feel free to reopen this issue (or open a new issue) if the problem persists after updating to `react-apollo@latest`.

**Comment by benjamn** [comment]
Here's the note from `CHANGELOG.md`:

- The `FetchPolicy` type has been split into two types, so that passing `cache-and-network` to `ApolloClient#query` is now forbidden at the type level, whereas previously it was forbidden by a runtime `invariant` assertion:
  ```ts
  export type FetchPolicy =
    | 'cache-first'
    | 'network-only'
    | 'cache-only'
    | 'no-cache'
    | 'standby';

  export type WatchQueryFetchPolicy =
    | FetchPolicy
    | 'cache-and-network';
  ```
  The exception thrown if you ignore the type error has also been improved to explain the motivation behind this restriction. <br/>
  [Issue #3130 (comment)](https://github.com/apollographql/apollo-client/issues/3130#issuecomment-478409066) and commit [cf069bc7](github.com/apollographql/apollo-client/commit/cf069bc7ee6577092234b0eb0ac32e05d50f5a1c)

**Comment by adrienharnay** [comment]
Thanks that is perfect! Just wanted to make sure no other third parties I'm not aware of (react-apollo or others) made use of this as well 🙂

Have a great day!

**Comment by alamothe** [comment]
Should we then file an issue against `react-apollo`? 

The issue is that `Query` component does not allow to pass `cache-and-network` anymore. Basically, the change in type here broke `react-apollo` (it needs to switch to `WatchQueryFetchPolicy` at appropriate places).

**Comment by adrienharnay** [comment]
@alamothe a new version of react-apollo has been released, you should be able to update and the problem will be gone
