### ISSUE TITLE
Query containing "fragment X on Query { __type ..." causes unexpected behaviour / error

### ISSUE THREAD

**Issue by bessey** [apollographql/apollo-client#4848]
**Intended outcome:**
When running a query of the format 
```gql
  query AllPeople {
    people {
      id
      name
    }
    ...PeopleTypes
  }
  fragment PeopleTypes on Query {
    __type(name: "Person") {
      name
      kind
    }
  }
```
The query executes and writes its contents to the internal cache, as it does for the same query with the `fragment X on Query` inlined into the actual `query { }`

**Actual outcome:**
Error `Cannot match fragment because __typename property is missing:` occurs

**How to reproduce the issue:**
I have a minimal reproduction case:
https://codesandbox.io/s/apolloclienterrortemplate-uoiq6
In the minimal case, manually adding `__typename` to the `fragment on Query` resolves the problem, however this is not the case in my application. I have not worked out why there is a difference here. 

You'll note from playing around that the problem is specifically from fetching `__type`, or `__schema` in the Query fragment. If you instead fetch an aliased `people` field the problem goes away.

In my App's case, I am pulling multiple EnumTypes by alias:
```gql
fragment MyFragment on Query {
    movingOpennessOption: __type(name: "CareRecipientMoving") {
      ...enumValues
    }
    movingReasonOption: __type(name: "CareRecipientMovingReason") {
      ...enumValues
    }
}
fragment enumValues on __Type {
    enumValues {
      name
      description
    }
  }
```

**Versions**

```
    "apollo-cache-inmemory": "^1.6.0",
    "apollo-client": "^2.6.0",
    "apollo-link": "^1.2.11",
    "graphql": "^14.2.0",
    "graphql-tag": "^2.10.1",
    "react": "^16.8.6",
    "react-apollo": "2.5.3",
    "react-dom": "^16.8.6"
```

**Comment by bessey** [comment]
Note this occurs with `apollo-cache-inmemory` 2.5.0 and the newly released `2.6.0`

**Comment by benjamn** [comment]
Just a quick note that this can be manually fixed by adding `__typename` _either_ to the `AllPeople` query _or_ to the `PeopleTypes` fragment. I'm still investigating a proper (non-manual) fix, but my hunch is that [`addTypenameToDocument`](https://github.com/apollographql/apollo-client/blob/57dab1e5ac77789b2866126e54216ae3154d0cd5/packages/apollo-utilities/src/transform.ts#L210) should be adding `__typename` to the `AllPeople` query rather than adding it to the fragment.

**Comment by lukemarsh** [comment]
@benjamn Have some breaking changes been released in the last 48 hours? I'm seeing the issue you've mentioned but adding `__typename` to the fragments doesn't make any difference

**Comment by antiold** [comment]
[duplicated](https://github.com/apollographql/apollo-client/issues/4488ac)
