### ISSUE TITLE
Tests/mocks omitted from tsconfig allowing errors and potential downstream type problems

### ISSUE THREAD

**Issue by rosskevin** [apollographql/apollo-client#4850]
**Intended outcome:**

Test code is representative of downstream use, both with and without types.

**Actual outcome:**

Test code is run, but never type checked because tests and mocks are excluded in the tsconfig.
https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/tsconfig.json#L13

**How to reproduce the issue:**

Remove the `exclude` from the tsconfig

**Versions**

2.6.0 apollo-client

## More info
In the PR #4261 I originally set forth, which was rather large and unwieldy and had to be separated (build changes vs test changes) my goals were:
1. type checking all code
2. incremental builds (tsc -b from the root)

Both of these are better dev experiences and reduce potential errors with releases by downstream typescript users:
1. `tsc -b` from root makes it easier to work with a monorepo from vscode/webstorm by providing unified errors in a performant way
2. ^^ with no excluded code allows for easier test writing, easier type checking our code, and more reliable releases (types break here with our tests instead of out in the wild)

I am encountering a downstream type issue now with:
`apollo-cache-inmemory/lib/readFromStore.d.ts:19:20 - error TS2709: Cannot use namespace 'KeyTrie' as a type.`

And went to the `master` here to see how it was successfully built/tested (and hopefully correct my local) but the excludes are in place preventing use of tests as a means to exercise types.  Removing excludes on the repo now result in a huge amount of errors again, ones that could have been maintained incrementally but are not because they are not being raised.

I'm a bit sad to see that my work was lost, but it is very easy to overlook the importance of _not_ excluding these files (as well as getting back to incremental builds/project references).

What is the interest level in getting this back in shape @benjamn?  Do you want me to take another shot at this?

**Comment by benjamn** [comment]
I fully support getting the tests to type-check again, but (as I said in https://github.com/apollographql/apollo-client/pull/4852#issuecomment-494973434) I would prefer a standalone PR that reenables type-checking.

**Comment by rosskevin** [comment]
https://github.com/apollographql/apollo-client/pull/4852#issuecomment-495204441
Please see this commentary in the draft pr.

Without big changes, this isn't going to happen.  It's still a problem but I don't want to put this effort in a second time to have my PR not fully accepted due to the number of files changed.  Please unassign me until we can agree on a path forward that will get merged.

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
