### ISSUE TITLE
loading or called booleans never become true when ignoreResults is set on Mutation/Query components

### ISSUE THREAD

**Issue by Rennzie** [apollographql/apollo-client#4861]
**Intended outcome:**

To set a spinner running while the query/mutation is running even if the results are being ignored.

**Actual outcome:**

No error messages or tags. The `loading` or `called` booleans never update to `true` when the the `ignoreResults` prop is set on the components

**How to reproduce the issue:**

Run any component with the `ignoreResult` 

**Versions**

  System:
    OS: macOS 10.14.5
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    Yarn: 1.16.0 - ~/Development/STOCKMAN/stockman-client/node_modules/.bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
  Browsers:
    Chrome: 74.0.3729.169
    Safari: 12.1.1
  npmPackages:
    apollo: ^2.12.0 => 2.12.0 
    apollo-boost: ^0.3.1 => 0.3.1 
    apollo-client: ^2.5.1 => 2.5.1 
    react-apollo: ^2.5.5 => 2.5.5

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
