### ISSUE TITLE
getCacheKey undefined when using  @client(always: true)

### ISSUE THREAD

**Issue by veeramarni** [apollographql/apollo-client#4862]
**Intended outcome:**

`getCacheKey` should be available in the context.
**Actual outcome:**

`getCacheKey`  = `undefined`
**How to reproduce the issue:**

```
query LowState ($resource: String!,) {
  lowState(resource: $resource) @client(always: true) {
      ...LowerState
  }
}
```
**Versions**

```
  System:
    OS: OS X El Capitan 10.11.6
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.16.0 - ~/Documents/eclipse/workspace/phoneapps/development/projects/IDE/files-stack/node_modules/.bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 67.0
    Safari: 11.0.2
  npmPackages:
    apollo: ^2.9.0 => 2.12.0 
    apollo-server-testing: ^2.4.8 => 2.5.0 
```

**Comment by wtrocki** [comment]
Never got why this is even there. 
When we look into code we see that under the hood this method is just wrapper for `toIdValue`: 

https://github.com/apollographql/apollo-client/blob/7eaf4132cd2cd6244260777799406aaa03fcf377/packages/apollo-cache-inmemory/src/readFromStore.ts#L605-L609

**Comment by impaler** [comment]
I also ran into this, @wtrocki not sure what you mean by "intension".

I can't see in the docs about using getCacheKey here https://www.apollographql.com/docs/react/essentials/local-state for any case of `@client(always: true)`.

I guess something like this can be used based on this as well?

https://github.com/peggyrayzis/apollo-client/blob/master/packages/apollo-client/src/core/QueryManager.ts#L1207

```
export const getCacheKey = (cache) =>
  (obj) => cache.config.dataIdFromObject(obj);
```

**Comment by wtrocki** [comment]
It is always best to use it and this method can be accessed from client.config object

**Comment by impaler** [comment]
@wtrocki thanks mate, I guess for this issue to be closed, we still need someone to verify if `getCacheKey = undefined` is the expected behaviour when using `@client(always: true)` directive

**Comment by ksrb** [comment]
Stumbled into this issue for those using Typescript you can do something like this if you don't want to use `@ts-ignore`:

```tsx
function someResolver(parent, args, { cache }) {
  (cache as any).config.dataIdFromObject(id: "...", fragment: "...")
};
```

Unfortunately it's pretty much equally as hacky :(.

Related links:
- https://ryanelainska.com/blog/apollo-getcachekey-with-typescript
- https://github.com/apollographql/apollo-client-devtools/issues/136

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
