### ISSUE TITLE
Polling/refetching - pass value via header to inform server if initial fetch or poll/refetch

### ISSUE THREAD

**Issue by U-4-E-A** [apollographql/apollo-client#4880]
I don't think there is functionality like this already available.

Let's say I have a page where a user can view another user's profile and the page uses Query to fetch a user's details, with a poll interval of X minutes. I would like to be able to log in my database how often a certain user's profile is viewed. If I am not polling and simply using a single query to return the data, this is not an issue as I can just have my resolver log in my database that the profile was viewed. However, the same resolver would also be being called every time the query polls/refetches, which would give me false hits. Can Apollo attach a header to the request to let the server know if the incoming request is the initial fetch from the query component or a poll/refetch?

**Comment by hwillson** [comment]
Please open a feature request for this in https://github.com/apollographql/apollo-feature-requests. Thanks!
