### ISSUE TITLE
Issue with Apollo Client not sending headers  

### ISSUE THREAD

**Issue by redhouse877** [apollographql/apollo-client#4883]
I am using Apollo Client with Next JS

**Intended outcome:**

I am able to send cookies with requests with Apollo Client both client side and during server side rendering.

**Actual outcome:**

The headers are sometimes not defined in Apollo Client causing the server side rendering to fail.

**How to reproduce the issue:**

To reproduce the issue you need to have the `with-data` file setup like so:

```
import withApollo from 'next-with-apollo';
import { endpoint, prodEndpoint } from '../config';
import ApolloClient from "apollo-boost";

function createClient({ headers }) {
  return new ApolloClient({
    credentials: 'include',
    uri: process.env.NODE_ENV === 'development' ? endpoint : prodEndpoint,
    request: operation => {
      operation.setContext({
        fetchOptions: {
          credentials: 'include',
        },
        headers,
      });
    }
  });
}

export default withApollo(createClient);
```

The App component should also look something like this:

```
import App, { Container } from 'next/app';
import { ApolloProvider } from 'react-apollo';
import withData from '../lib/with-data';

class AppComponent extends App {
  static async getInitialProps({ Component, ctx }) {
    let pageProps = {};
    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx)
    }
    return { pageProps };
  }
  render() {
    const { Component, apollo, pageProps } = this.props;

    return (
      <Container>
        <ApolloProvider client={apollo}>        
          <Component {...pageProps} />
        </ApolloProvider>
      </Container>
    );
  }
}

export default withData(AppComponent);
```

**Notes:**

If you change the following block in `with-data`:
```
    request: operation => {
      operation.setContext({
        fetchOptions: {
          credentials: 'include',
        },
        headers,
      });
```

To:

```
    request: operation => {
      operation.setContext({
        fetchOptions: {
          credentials: 'include',
        },
        headers: {
          cookie: headers && headers.cookie
        }
      });
```

It will fix the server side rendering, however the cookie will not be remembered/ passed when the user re-visits the site. In my case, I use an http only cookie so I can't fetch it from browser cookies if the headers are not defined. 

I have also tried migrating away from Apollo Boost and having a custom config but it was the exact same result.

**Versions**

  System:
    OS: macOS 10.14

  Binaries:
    Node: 8.9.0 - ~/.nvm/versions/node/v8.9.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 5.5.1 - ~/.nvm/versions/node/v8.9.0/bin/npm

  Browsers:
    Chrome: 74.0.3729.169
    Safari: 12.0

  npmPackages:
    apollo-boost: ^0.4.0 => 0.4.0 
    apollo-cache-inmemory: ^1.6.0 => 1.6.0 
    apollo-client: ^2.6.0 => 2.6.0 
    apollo-link: ^1.2.11 => 1.2.11 
    apollo-link-batch-http: ^1.2.11 => 1.2.11 
    apollo-link-error: ^1.1.10 => 1.1.10 
    apollo-link-http: ^1.5.14 => 1.5.14 
    apollo-link-persisted-queries: ^0.2.2 => 0.2.2 
    apollo-link-state: ^0.4.2 => 0.4.2 
    apollo-link-ws: ^1.0.17 => 1.0.17 
    next-with-apollo: ^3.4.0 => 3.4.0 
    react-apollo: ^2.5.6 => 2.5.6

**Comment by wanzulfikri** [comment]
This seems similar to issue #4109 and that one is still open too.

I have the same issue as you and I was thinking of using the client from apollo-client instead of apollo-boost. I’ll see if the header-passing behaviour after the change is the same as yours.

**Comment by JaKXz** [comment]
My Apollo Client from apollo-boost looks very similar and I'm definitely seeing the same thing. My requests are sent with the `Content-Type:text/plain` header, despite the following. Digging into index.ts from apollo-boost and at first glance, it seems to be correct...

```js
import ApolloClient from "apollo-boost";
import fetch from "isomorphic-fetch";

export default new ApolloClient({
  uri: process.env.REACT_APP_API_URL,
  fetch,
  onError: errorObj => {
    console.info({ errorObj });
  },
  headers: {
    "Content-Type": "application/graphql",
  },
  request: operation => {
    operation.setContext({
      headers: {
        "Content-Type": "application/json",
      },
    });
  },
});
```

**Comment by JaKXz** [comment]
I have tried both apollo-boost v0.4.3 (latest at time of writing) and v0.3.1

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
