### ISSUE TITLE
Create new Mutation type to be bound to local client function instead of GraphQL resolver

### ISSUE THREAD

**Issue by uri3000** [apollographql/apollo-client#4888]
The way its built today, `<Mutation>` is necessarily bound to a server api GraphQL schema, meaning - if you use `<Mutation>` it necessarily runs single unit of logic IN THE SERVER.

My problems with this is that in client side code, sometimes I want to run multiple different updates / creates in a single unit of logic IN THE  CLIENT and bind my `<Mutation>` to that.

For example, lets examine the following facebook connect flow and load facebook pages:
1. User is redirected to facebook connect
2. After logging in, user redirected back to the app (React based website), and the state of the page turns to Loading
3. Then, an API call to facebook/me/accounts is made in order to load the pages from Facebook
4. Then, a call to save all pages in the database is called
5. Then, another 3rd party API is called;
6. Then, the state of the page turns to ready and the User's facebook pages are loaded from the server API and displayed on the pages using `<Query>`.

In this case, steps 3, 4, 5 are not changing the client app state, however, if Implemented using `<Mutation>` it requires me to create a different state in the UI in order to execute each step separately.

If I could connect Mutation object to a local API or a local function, this would have definitely solved it for me since I would have been able to run 3,4,5 steps sequentially together without changing client state.

**Comment by hwillson** [comment]
Please open a feature request for this in https://github.com/apollographql/apollo-feature-requests. Thanks!
