### ISSUE TITLE
The docs on error handling specify arguments that don't match what's actually passed.

### ISSUE THREAD

**Issue by jdalegonzalez** [apollographql/apollo-client#4890]
At: https://www.apollographql.com/docs/react/features/error-handling/ the onError function is described as being passed arguments like so...
```
Options
Error Link takes a function that is called in the event of an error. This function is called with an object containing the following keys:

operation: The Operation that errored
response: The response from the server
graphQLErrors: An array of errors from the GraphQL endpoint
networkError: any error during the link execution or server response
```

In fact, you get:
```
forward: A function that who knows what it's supposed to do.
graphQLErrors: Or undefined if it's a network error.
networkError
operation
```

The documentation also says that you can set response.error to null to suppress handling, but since there is no response object passed to the onError function, this isn't possible.

**Comment by Pokerkoffer** [comment]
Same for me.  For instance networkError is defined as follows:

```typescript
export interface ErrorResponse {
  // ...
  networkError?: Error | ServerError | ServerParseError;
  // ...
}

export declare type ServerError = Error & {
    response: Response;
    result: Record<string, any>;
    statusCode: number; // notice this property
};

export declare type ServerParseError = Error & {
    response: Response;
    statusCode: number; // notice this property
    bodyText: string;
};
```

This is what is returned on a 403 Forbidden error: 
![Bildschirmfoto 2019-08-03 um 18 50](https://user-images.githubusercontent.com/770369/62414715-974a9680-b61f-11e9-94f2-764a99f2fcdf.png)

The object is totally different, e.g. `status: 403` vs `statusCode: 403`

**Comment by Pokerkoffer** [comment]
Any update on this?
