### ISSUE TITLE
Query request is sent to server even when the cache is available for the request.

### ISSUE THREAD

**Issue by PavanBahuguni** [apollographql/apollo-client#4910]
```
System:
    OS: macOS 10.14.4
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: 1.12.3 - ~/.nvm/versions/node/v8.12.0/bin/yarn
    npm: 6.8.0 - ~/.nvm/versions/node/v8.12.0/bin/npm
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 67.0
    Safari: 12.1
  npmPackages:
    apollo-boost: ^0.3.1 => 0.3.1 
    react-apollo: ^2.5.4 => 2.5.5 
```

In one of my react components i executed a query as so using Query component.
```
query sampleQuery {
    getUser(id: '123) {
       id
      name
   }
}
```
after loading this page navigated to a different page, which also has a similar data requirement but needs some extra data and i executed a query like so.

```
query sampleQuery2 {
    getUser(id: '123) {
       id
      name
   }
  getExtraData {
     field1
     field2
  }
}
```
In this case i was expecting Apollo to make a single query that is for getExtraData as the data for getUser(id: '123) is already available in the cache.

However when I open the second component first and then the initial component Apollo doesn't make a getUser query which is expected behavior.

Is this an intended behaviour?

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
