### ISSUE TITLE
ES Bundle of Apollo Boost doesn't work

### ISSUE THREAD

**Issue by kevinsimper** [apollographql/apollo-client#4912]
Here is a example:
https://codepen.io/anon/pen/XwGMxr

Code:
```
<script type="module" src="https://unpkg.com/apollo-boost?module"></script>
```

```
XwGMxr:1 Uncaught SyntaxError: The requested module 'https://unpkg.com/graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0/language/visitor?module' does not provide an export named 'visit'
```

This is the error you get. This make it difficult to build a app with LitElement and Apollo Elements without bundling.

**Comment by benjamn** [comment]
This seems like an unpkg bug more than an Apollo Client bug. Specifically, if you look at the response for [the `graphql` bundle](https://unpkg.com/graphql@14.3.1/language/visitor?module), you can see that it's CommonJS instead of ESM, and it definitely exports a `visit` method:
```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true });

exports.visit = visit;
exports.visitInParallel = visitInParallel;
exports.visitWithTypeInfo = visitWithTypeInfo;
...
```

**Comment by kevinsimper** [comment]
@benjamn Thanks for the answer, I really appreciate it.

I also tried with the polymer-cli and that didn't work either.

With ES Modules you have to include the full URL to the resource, and you can see here that `apollo-link` links directly into the graphql bundle to a file that exist as a .js file. 

https://cdn.jsdelivr.net/npm/apollo-link@1.2.11/lib/bundle.esm.js

I don't want to argue who is right and wrong, but the two ways I know to native ES modules in the browser doesn't work with Apollo sadly, I and I really want beginners to get started with graphql and apollo.

Here is the example with polymer-cli that doesn't work either
https://github.com/kevinsimper/broken-native-es-module-apollo-boost

So I think this should be reopened :)

**Comment by kevinsimper** [comment]
I solve it by bundling apolloboost and graphql into a bundle with browserify and the loading it by itself as a non native module.
