### ISSUE TITLE
<Query fetchPolicy="cache-and-network" onCompleted={...}> doesn't fire

### ISSUE THREAD

**Issue by sfcgeorge** [apollographql/apollo-client#4921]
**Intended outcome:**

onCompleted callback should be run when a query completes.

**Actual outcome:**

The callback doesn't fire when using `fetchPolicy="cache-and-network"`.

**How to reproduce the issue:**

```
<Query 
  query={someQuery}
  fetchPolicy="cache-and-network"
  onCompleted={data => console.log("you won't see this")}
>
```

^ Removing the fetch policy it fires correctly.

**Versions**

```
├─ apollo-cache-inmemory@1.6.1
├─ apollo-cache-persist@0.1.1
├─ apollo-cache@1.3.1
├─ apollo-client@2.6.1
├─ apollo-link-batch-http@1.2.11
├─ apollo-link-batch@1.1.12
├─ apollo-link-http-common@0.2.13
├─ apollo-link-http@1.5.14
├─ apollo-link@1.2.11
├─ apollo-utilities@1.3.1
├─ react-apollo@2.5.6
```

**Comment by jasonpaulos** [comment]
@sfcgeorge Can you provide a small runnable reproduction that shows this issue? I'm not seeing the problem on my end.

**Comment by maapteh** [comment]
When using latest i get an TS error, it says: `Type '"cache-and-network"' is not assignable to type '"cache-first" | "network-only" | "cache-only" | "no-cache" | "standby" | undefined'.ts(2345)`

```
        "apollo-cache-inmemory": "^1.5.1",
        "apollo-client": "^2.5.1",
        "apollo-link": "^1.2.11",
        "apollo-link-batch-http": "^1.2.11",
        "apollo-link-error": "^1.1.10",
        "apollo-link-http": "^1.5.14",
        "apollo-link-logger": "^1.2.3",
        "apollo-link-schema": "^1.2.2",
        "apollo-link-state": "^0.4.2",
        "graphql": "^14.3.0",
        "react-apollo": "2.5.5",
```
I have to check which lib i upgraded last.

**Comment by jasonpaulos** [comment]
@maapteh There is no mistake with the code. The commit you are referencing contains [a link to this issue thread](https://github.com/apollographql/apollo-client/issues/3130#issuecomment-478409066) explaining why the changes were made. In short, the `cache-and-network` policy cannot be used for a one-off `query` call since that method can only return a single result. Instead, the `watchQuery` method should be used, which returns a stream of results. Hope this helps!

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
