### ISSUE TITLE
refetchQueries doesn't update loading

### ISSUE THREAD

**Issue by sfcgeorge** [apollographql/apollo-client#4922]
**Intended outcome:**

If `refetchQueries` causes a `<Query>` be refetched, the `loading` render-prop argument should be true while it is refetching.

**Actual outcome:**

The `loading` render-prop argument remains false, but eventually the correct data does load.

This seemingly makes it impossible to change the UI state while the data is stale. For example I want to grey out an "Add" button after a mutation while the query is still reloading so people can't double click and cause duplicates. 

**Versions**

```
├─ apollo-cache-inmemory@1.6.1
├─ apollo-cache-persist@0.1.1
├─ apollo-cache@1.3.1
├─ apollo-client@2.6.1
├─ apollo-link-batch-http@1.2.11
├─ apollo-link-batch@1.1.12
├─ apollo-link-http-common@0.2.13
├─ apollo-link-http@1.5.14
├─ apollo-link@1.2.11
├─ apollo-utilities@1.3.1
├─ react-apollo@2.5.6
```

**Comment by OurMajesty** [comment]
Did you try adding `notifyOnNetworkStatusChange: true`?

**Comment by OurMajesty** [comment]
Also, there's `awaitRefetchQueries` option, which doen't resolve mutation promise, until all refetching queries are resolved.

**Comment by sfcgeorge** [comment]
I did try `notifyOnNetworkStatusChange` but it didn't help unfortunately.

**Comment by michaelcheng924** [comment]
> Also, there's `awaitRefetchQueries` option, which doen't resolve mutation promise, until all refetching queries are resolved.

Perfect, thanks!

**Comment by danielo515** [comment]
> Also, there's `awaitRefetchQueries` option, which doen't resolve mutation promise, until all refetching queries are resolved.

It does not resolve the mutation, but doesn't update the loading state of the fetched queries either, so it is useless on this context

**Comment by hwillson** [comment]
This should no longer be an issue in `@apollo/client@latest` - let us know otherwise, thanks!
