### ISSUE TITLE
readQuery doesn't work with @client @export

### ISSUE THREAD

**Issue by sfcgeorge** [apollographql/apollo-client#4923]
**Intended outcome:**

`cache.readQuery` should work the same as `<Query>` when using `@client @export` variables.

**Actual outcome:**

`<Query>` will correctly resolve `@client @export`s, fetch data from the server, and populate its cache. But then trying to use `readQuery` with the same query to fetch from the cache fails, with an error like:

```
Invariant Violation: Can't find field resourceRequirements({}) on object {
  "offerSlug": "powerboating-level-1-course",
  "outletSlug": "london-adventure-centre",
  "resourceRequirements({\"offerSlug\":\"powerboating-level-1-course\"})": [
    {
      "type": "id",
      "generated": false,
      "id": "ResourceRequirement:cc260827-070b-4d8f-9a89-ead1663a8807",
      "typename": "ResourceRequirement"
    }
  ],
  "resourceTypes({\"outletSlug\":\"london-adventure-centre\"})": [
    {
      "type": "id",
      "generated": false,
      "id": "ResourceType:2bd123a0-e6f6-468a-b0ce-7cbb1c45b85f",
      "typename": "ResourceType"
    }
  ]
}.
```

**How to reproduce the issue:**

Use @client @export in a `query = gql...` query, run it with `<Query query={query}>`, then try to read it with `client.readQuery({ query: query })`

I can't see any tests for readQuery so I assume it's just not implemented. https://github.com/apollographql/apollo-client/blob/7eaf4132cd2cd6244260777799406aaa03fcf377/packages/apollo-client/src/__tests__/local-state/export.ts

**Versions**

```
├─ apollo-cache-inmemory@1.6.1
├─ apollo-cache-persist@0.1.1
├─ apollo-cache@1.3.1
├─ apollo-client@2.6.1
├─ apollo-link-batch-http@1.2.11
├─ apollo-link-batch@1.1.12
├─ apollo-link-http-common@0.2.13
├─ apollo-link-http@1.5.14
├─ apollo-link@1.2.11
├─ apollo-utilities@1.3.1
├─ react-apollo@2.5.6
```

**Comment by nenjamin2405** [comment]
I have the same issue, it should return the same data, just like what I get back in <Query /> component.

**Comment by bennypowers** [comment]
this makes it impossible to write apps which mutate the graph based on local data

**Comment by mxhold** [comment]
I also ran into this and found it confusing. Is this working as expected? If not, could this limitation be called out in the [documentation](https://www.apollographql.com/docs/react/essentials/local-state/#using-client-fields-as-variables)?

**Comment by sfcgeorge** [comment]
Just ran into this again trying to do a [mutation with update as per the docs](https://www.apollographql.com/docs/react/essentials/mutations/#updating-the-cache). 

It's very frustrating that client state launched with [lots of fanfare](https://blog.apollographql.com/announcing-apollo-client-2-5-c12230cabbb7) but at that point was [unusable for read queries](https://github.com/apollographql/apollo-client/issues/4530), and it's currently unusable with mutations. There are very few specs around it so who knows what else it doesn't work with. It's a shame as it's potentially such a nice feature but it seems nobody on the Apollo core team actually uses client state in a real world app.

@hwillson

**Comment by miwialex** [comment]
I just ran into the same issue as @sfcgeorge. I am trying to do a mutation with update, and have a value I use in local state that I need in the query. However, using @client @export doesn't work at all. This would be super helpful

**Comment by NinjaOnRails** [comment]
I thought I was the only one having this problem. Any updates?

**Comment by emuvente** [comment]
We're having the same issue. We use `readQuery` to synchronously get prefetched data form the cache upon component creation, but that is currently failing for any components that use `@client @export`. It's essential for `readQuery` to support `@export` for us to be able to use that feature at all.

**Comment by Janmajayamall** [comment]
@miwialex  were you able to solve the problem using @client @export? I am facing the same issue right now. For now I have switched to querying local data using ApolloConsumer and then carry on with Mutation as usual, but was looking forward to one request solution.

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
