### ISSUE TITLE
Variables should not pass default null

### ISSUE THREAD

**Issue by Fi1osof** [apollographql/apollo-client#4929]
Related to: https://github.com/apollographql/apollo-client/issues/947

Apollo-client sets all non-passed variables to null. Example query: 
```

query users (
  $first: Int = 10
  $includeTopics: Boolean = true
){
  users (
    first:$first
  ){
    id
    username
    Resources @include (if: $includeTopics){
      id
      contentText
      uri
    }
  }
}
```

On execute query without passed **first** and **includeTopics** options apollo-client sends request with null-variables.
```
variables: {
    first: null,
    includeTopics: null,
}
```

This is wrong. And apollo-client should not set default variables from schema, so we should not send in request ```
variables: {
    first: 10,
    includeTopics: true,
}
```

Result: 
1. got error message: "Null value was provided for the NotNull Type 'Boolean!' at path 'if'."
2. If send with variable includeTopics: true, got all records instead first 10.

It should be 
```
variables: {
}
```

Default values will got on graphql-side. 



**Versions**
apollo-client@2.6.0
```
 System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
  Binaries:
    Node: 10.16.0 - /usr/bin/node
    Yarn: 1.16.0 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/bin/npm
  Browsers:
    Chrome: 70.0.3538.110
    Firefox: 67.0
  npmPackages:
    apollo-cache-inmemory: ^1.3.7 => 1.6.0 
    apollo-client: ^2.4.4 => 2.6.0 
    apollo-link-dedup: 1.0.15 => 1.0.15 
    apollo-link-http: 1.5.5 => 1.5.5 
    react-apollo: ^2.2.3 => 2.5.6 
  npmGlobalPackages:
    apollo: 1.9.2

```

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
