### ISSUE TITLE
Less data clobbers more data in cache

### ISSUE THREAD

**Issue by sfcgeorge** [apollographql/apollo-client#4931]
If you have two queries in your app that happen around the same time and request the same types but different fields (AKA query B is a subset of query A), then if B completes after A the the extra data from A disappears.

If the smaller query loads 2nd then data is removed from cache (and your app's UI). This means you have to always use full / the same queries to request "the same" data even if you're using it in different places for different purposes.

[This comment from Ben](https://github.com/apollographql/apollo-client/issues/4920#issuecomment-499531688) made me wonder if it is a bug or not. It kinda makes sense that since the ID is the same, the subset of the data would wipe out the full data because it's newer. But I feel it would make more sense if the result had come back with null fields not missing fields. AKA If a field is missing that doesn't necessarily mean it's gone.

I spent hours trying to track down why data would appear in my UI then disappear again. If it is expected behaviour it would be super useful if in dev mode a warning is logged. Something like "Cache entry ID xxxxxxxxxxx was replaced by a newer version with fewer fields. If this is not what you intended make sure to query the same fields in each query. See apollo.io/help/bla" 

**How to reproduce the issue:**

Have 2 queries where 1 is a subset of the other (in real world usually part of bigger queries in separate components). Have them both load around the same time (the effect is intermittent) or have B (the subset) load after A.

```js
const query1 = gql`
  query {
    allFilms {
      id
      title
    }
  }
`;

const query2 = gql`
  query {
    allFilms {
      id
    }
  }
`;
```

**Versions**

```
├─ apollo-cache-inmemory@1.6.1
├─ apollo-cache-persist@0.1.1
├─ apollo-cache@1.3.1
├─ apollo-client@2.6.1
├─ apollo-link-batch-http@1.2.11
├─ apollo-link-batch@1.1.12
├─ apollo-link-http-common@0.2.13
├─ apollo-link-http@1.5.14
├─ apollo-link@1.2.11
├─ apollo-utilities@1.3.1
├─ react-apollo@2.5.6
```

**Comment by benjamn** [comment]
The fields of `Film` objects with the same `id` should get merged together in the cache, regardless of the order in which they're written, so what you're describing sounds like a bug. Any chance of a runnable reproduction?

**Comment by sfcgeorge** [comment]
Oh okay, thank you Ben. 

Tried to repro but seems fine: https://codesandbox.io/s/apollo-query-deduplication-bil60?fontsize=14

Can't repro locally any more so perhaps it was one of my other bugs contributing. I have had to stop using `@client @export` perhaps that was interfering. 

Closing for now

**Comment by benjamn** [comment]
cc @hwillson in case he has ideas
