### ISSUE TITLE
Update store on mutation get an undefined element on top of the query

### ISSUE THREAD

**Issue by louishugens** [apollographql/apollo-client#4933]
Hello guys,

I have a list of element and I try to update the cache when adding a new one. The update code in the Mutation:
`            update={(store, { data: { article } }) => {
              const first = ITEMS_PER_PAGE
              const skip = 0
              const orderBy = 'createdAt_DESC'
              const data = store.readQuery({ 
                query: ARTICLES_QUERY,
                variables: { first, skip, orderBy },
              })
              console.log('data', data)
              data.articles.articles.shift()
              console.log('data', data)
              data.articles.articles.unshift(article)
              console.log('data', data)
              store.writeQuery({
                query: ARTICLES_QUERY,
                data,
                variables: { first, skip, orderBy },
              })
            }}`

the query works fine in the list:
data : {articles: {…}}articles: articles: Array(10)0: {id: "cjwkz1mv6002t07714dhb0sfv", nom: "papapdo", code: "p00939", prix: 2334, __typename: "Article"}1: {id: "cjwkyjxt4002a07718cafquvg", nom: "papa", code: "p00", prix: 876, __typename: "Article"}2: {id: "cjwkyjxn50025077181yogqtz", nom: "papa", code: "p00", prix: 876, __typename: "Article"}3: {id: "cjwkyed3t001q0771x4ftqazb", nom: "popo", code: "po", prix: 976, __typename: "Article"}4: {id: "cjwkybrnf001h07714ls9jj07", nom: "keke", code: "ki", prix: 988, __typename: "Article"}5: {id: "cjwky2rx9001a0771vh8uy9x7", nom: "kuku", code: "k", prix: 655, __typename: "Article"}6: {id: "cjwkxxqjz00130771e7s687nf", nom: "kiki", code: "ki", prix: 9494, __typename: "Article"}7: {id: "cjwkxs4av000w0771yuvdasd5", nom: "Pipi", code: "P-006", prix: 87, __typename: "Article"}8: {id: "cjwkx74ae000n0771sr280t7d", nom: "popo", code: "doe00 ", prix: 98899, __typename: "Article"}9: {id: "cjwkx31u3000e0771q9iphok3", nom: "Bal", code: "l00", prix: 45, __typename: "Article"}length: 10__proto__: Array(0)count: 66__typename: "Articles"__proto__: Object

But after the Mutation fires, an undefined item is added. 

data:
articles:
articles: Array(10)
0: undefined
1: {id: "cjwkzm2xa003t0771f8mce1js", nom: "Papillon", code: "P-003", prix: 984, __typename: "Article"}
2: {id: "cjwkzkkmz003o0771hjsop9i2", nom: "llsl", code: "oro", prix: 9394, __typename: "Article"}
3: {id: "cjwkzc035003d077135colzcs", nom: "kdlkd", code: "oeodk", prix: 94945, __typename: "Article"}
4: {id: "cjwkz95vx00340771tfnr0p5j", nom: "kdkqo", code: "oo", prix: 484, __typename: "Article"}
5: {id: "cjwkz1mv6002t07714dhb0sfv", nom: "papapdo", code: "p00939", prix: 2334, __typename: "Article"}
6: {id: "cjwkyjxt4002a07718cafquvg", nom: "papa", code: "p00", prix: 876, __typename: "Article"}
7: {id: "cjwkyjxn50025077181yogqtz", nom: "papa", code: "p00", prix: 876, __typename: "Article"}
8: {id: "cjwkyed3t001q0771x4ftqazb", nom: "popo", code: "po", prix: 976, __typename: "Article"}
9: {id: "cjwkybrnf001h07714ls9jj07", nom: "keke", code: "ki", prix: 988, __typename: "Article"}

Please help.

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
