### ISSUE TITLE
Problems using InMemoryCache with TypeScript

### ISSUE THREAD

**Issue by joemckie** [apollographql/apollo-client#4939]
**Versions**

```
System:
    OS: macOS 10.14.5
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 75.0.3770.80
    Firefox: 65.0.1
    Safari: 12.1.1
```

When using `InMemoryCache` with TypeScript, the the following error is given:

`Type 'InMemoryCache' is missing the following properties from type 'KeyValueCache<string>': get, set, delete`.

```js
const cache = new InMemoryCache();
const server = new ApolloServer({
  cache,
  schema,
});
```

**Comment by benjamn** [comment]
Thanks for reporting this issue, but there's not much we can do without more information, such as the versions of the packages involved, and any relevant details about the build tools or frameworks you're using. The text you see when you open a new issue explains most of this—please read it!

In a quick grep of our codebase(s), I don't see any mention of `KeyValueCache`, so there's a good chance the problem has something to do with your usage of the libraries.
