### ISSUE TITLE
toggling polling several times sends extra requests

### ISSUE THREAD

**Issue by healqq** [apollographql/apollo-client#4948]
**Intended outcome:**
stop polling stops polling even after several stop/startPolling calls

**Actual outcome:**
Previous startPolling requests are still resolved if calls to start/stopPolling happen more often then polling interval

**How to reproduce the issue:**

If you call .startPolling -> .stopPolling -> startPolling within polling interval, requests from both first startPolling call and second startPolling call will be sent. This happens because interval is not cleared when query manager [removes pollingInfo](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/QueryManager.ts#L1405) and new pollRequest sets ```this.pollingInfoByQueryId``` value again and then [maybeFetch](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/QueryManager.ts#L1373) finds info from new startPolling call and makes a call.
I wrote a test to demonstrate the issue:
```
it('should cancel polling request on stopPolling', () => {
      const query = gql`
        query fetchLeia($id: String) {
          people_one(id: $id) {
            name
          }
        }
      `;

      const variables = {
        id: '2',
      };

      const data1 = {
        people_one: {
          name: 'Leia Skywalker',
        },
      };

      const queryManager = mockQueryManager(
        {
          request: { query, variables },
          result: { data: data1 },
        },
      );
      const observable = queryManager.watchQuery({
        query,
        variables,
        pollInterval: 50,
      });

      return observableToPromise(
       // use value between timeout(20) + polling interval(50) and polling interval
       // nothing should happen during this time
       //
        { observable, wait: 60 },
        result => {
          expect(stripSymbols(result.data)).toEqual(data1);
          observable.stopPolling();
          observable.startPolling(50);
          setTimeout(() => {
            observable.stopPolling();
            observable.startPolling(50);
            // interval is less then polling interval
          }, 20);
        },
      );
    });
```
**Versions**

System:
    OS: macOS 10.14.4
  Binaries:
    Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 5.10.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
  Browsers:
    Chrome: 75.0.3770.80
    Safari: 12.1
  npmPackages:
    apollo-boost: file:packages/apollo-boost => 0.4.2 
    apollo-cache: file:packages/apollo-cache => 1.3.2 
    apollo-cache-inmemory: file:packages/apollo-cache-inmemory => 1.6.2 
    apollo-client: file:packages/apollo-client => 2.6.2 
    apollo-utilities: file:packages/apollo-utilities => 1.3.2 

**P.S.** 
I can send a pull request to fix this issue, seems pretty quick fix

**Comment by normanzb** [comment]
we encounter this issue as well on 2.6.8. Should `clearTimeout` at https://github.com/apollographql/apollo-client/blob/v2.6.8/packages/apollo-client/src/core/QueryManager.ts#L1405

**Comment by drkibitz** [comment]
Would this sound like the same issue?

I have a lazy query configured with a pollInternval of 5 seconds. When initially invoked, it polls at 5 seconds, everything seems fine. Then after some time, and after a particular response, I call stopPolling, then after some more time I invoke the lazy query again with different variables and expect the polling to start again. It does start again, but at this point it seems to poll very fast, around 0.5 seconds or less. This is obviously dreadful behavior, as it can result in a thundering herd to the server. 

As you can guess, I've tried to play legos with the API, and this reproduces with many different variations of this flow; such as useQuery with the startPolling function, toggling pollInterval in the options, etc., etc.. It all seems to be fine first time around, and then comes an extreme interval the second time around.

**Comment by drkibitz** [comment]
I should mention that the issue goes away if I ensure that the component that maintains the polling query is unmourned before I try to start polling for a second time. So with that, was considering a workaround using some component wrapper to unmount when polling is complete and remount when I want to start again.

**Comment by healqq** [comment]
@drkibitz the issue on top seems to be fixed by #6438 what you describing seems to a different issue :) I recommend you to open a separate issue with a way to reproduce it.

**Comment by benjamn** [comment]
I know this isn't the most helpful answer, but the way polling works has changed substantially in AC3, in case you were looking for more reasons to try upgrading. Specifically, all polling logic is now controlled by the [`Reobserver#updatePolling`](https://github.com/apollographql/apollo-client/blob/e30f12221928a380b435c7ddf00a304753ac03cb/src/core/Reobserver.ts#L94) method.

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
