### ISSUE TITLE
Java client generated by ApolloGraphQL capitalizes variable keys

### ISSUE THREAD

**Issue by rishikeshtm** [apollographql/apollo-client#4949]
If the operation has a capital cased vairable key, the generated client code has cpital casing in the query but has camelCase in variables. Due to which, I see this error from the 
Error: GraphQL error: Variable 'PersonId' has coerced Null value for NonNull type 'PersonDetailsRequest!'.

Example:

If this is the query:

```
query Hello($PersonId: PersonDetailsRequest!) {
  PersonDetails(input: $PersonId) {
  firstName
  lastName
  phoneNumber
  }
}

```
This is the generated request from the java client:

```
{  
   "operationName":"Hello",
   "variables":{  
      "personId":{   <<<---- camelCased from PersonId
         "PersonId":"123"
      }
   },
   "query":"query Hello($PersonId: PersonDetailsRequest!) {  PersonDetails(input: $PersonDetailsRequest) {     
  firstName 
  lastName 
  phoneNumber  }}"
}
```

I could avoid this issue by modifying the operation in the schema to have the camelCase itself.

**Comment by jkodroff** [comment]
How are you generating this Java code?  I don't see Java as a supported language in the codegen docs: https://github.com/apollographql/apollo-tooling#apollo-clientcodegen-output (`--target` option).

Are you maybe using this instead?  https://github.com/apollographql/apollo-android

**Comment by hwillson** [comment]
This functionality isn't provided by this repo. Thanks!
