### ISSUE TITLE
Apollo Client 2.6 makes the networkStatus for fetchMore disappear

### ISSUE THREAD

**Issue by nenjamin2405** [apollographql/apollo-client#4952]
**Intended outcome:**
Previously I used apollo-client 2.5, and I use networkStatus as:
` <Query
        query={apolloQuery}
        variables={variables}
        notifyOnNetworkStatusChange
      >
        {({ data, fetchMore: fetchMoreMutation, networkStatus }) => {`
If networkStatus === 3 then I display the loading icon, and it worked. So I expect it to work also in version 2.6

**Actual outcome:**
When I upgrade to Apollo Client 2.6 and I cannot see the loading icon when it is fetching more. I tried to log the networkStatus when it is fetching more but the outcome was only 7 (when the fetchMore completed)

**How to reproduce the issue:**

**Versions**
apollo-boost: ^0.4.2 => 0.4.2 
apollo-link-context: ^1.0.15 => 1.0.15 
apollo-link-rest: ^0.7.0 => 0.7.0 
apollo-link-retry: ^2.2.13 => 2.2.13 
react-apollo: ^2.5.6 => 2.5.6

**Comment by rlansky** [comment]
I am experiencing the same issue after upgrading from 2.5.4 to 2.5.6. I've tried upgrading to the latest version (currently 2.5.8), but I still experience this issue.

**Comment by TheHacker66** [comment]
Why did you close this @nenjamin2405 ? networkStatus is still not correctly set to 3 when fetchMore is called.
