### ISSUE TITLE
QueryManager schedulePoll sets lastPollTimeMs after query is done

### ISSUE THREAD

**Issue by Ashenbacken** [apollographql/apollo-client#4965]
**Intended outcome:**
The query should be fetched every 30 seconds.

**Actual outcome:**
The query is fetched every 60 seconds.

**How to reproduce the issue:**
Setup a watchQuery with 30 seconds pollInterval.
Watch the network log in chrome dev tools for the query.
It will fetch the query every 60 seconds.

The issue could be that the updateLastPollTime (in QueryManager.schedulePoll) function is called after the query is done, and the next time the timeout callback is called and compares with Date.now() it will be off by the time spent on the fetching of the query.
So the next time the schedulePoll is called the check (Date.now() - info.lastPollTimeMs >= info.interval) will not be true as it will still be the amount of time it took to do the last query left, and due to this it will wait another 30 seconds to call the timeout and by then the check will be true, but close to 30 seconds (30s - time spent on last query) past due.

**Versions**
  System:
    OS: macOS 10.14.5
  Binaries:
    Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
    Yarn: 1.16.0 - ~/.yarn/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.1/bin/npm
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 66.0.5
    Safari: 12.1.1

**Comment by benjamn** [comment]
What version of `apollo-client` are you using? Better yet, could you run
```sh
npx envinfo@latest --preset apollo --clipboard
```
to copy/paste all of your package versions?

**Comment by Ashenbacken** [comment]
Sorry for the late response.

Tried it a few times and I still get the same result as the original post.
Here is the package.json part instead.
`
    "apollo-cache-inmemory": "^1.6.2",
    "apollo-client": "^2.6.2",
    "apollo-link": "^1.2.11",
    "apollo-link-error": "^1.1.10",
    "apollo-link-http": "^1.5.14",
    "apollo-link-persisted-queries": "^0.2.2",
    "graphql-tag": "^2.10.1",
    "react-apollo": "^2.5.6"
`

**Comment by Ashenbacken** [comment]
We can close this issue, my colleague had updated to 2.6.2 from 2.5.1, and it works now.
