### ISSUE TITLE
Broken link in GitHub description

### ISSUE THREAD

**Issue by ryaninvents** [apollographql/apollo-client#4966]
Minor issue, but the link at the top of the GitHub repo points to a page that no longer exists. The link in the README header, <https://www.apollographql.com/client/>, is correct.

![image](https://user-images.githubusercontent.com/8356669/59516381-3b6d5800-8e8f-11e9-812c-7afe5f2b56f5.png)

**Comment by jasonpaulos** [comment]
Thanks @ryaninvents! This has been fixed.
