### ISSUE TITLE
npm i apollo-client fails on MacOS

### ISSUE THREAD

**Issue by jklepatch** [apollographql/apollo-client#4967]
**Intended outcome:**
`npm i apollo-client` should work

**Actual outcome:**

```
npm ERR! Unexpected end of JSON input while parsing near '...":"^1.0.6","apollo-li'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/[my_user]/.npm/_logs/2019-06-15T05_29_38_605Z-debug.log
```

**How to reproduce the issue:**
Run `npm i apollo-client` on a new npm project on macos

**Versions**

node v10.15.3
npm v6.4.1
MacOS Mojave 10.14

Note: This also happen with `npm i react-apollo`, for a similar reason:

```
npm ERR! Unexpected end of JSON input while parsing near '...2.0","chai-enzyme":"^'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/[my_user].npm/_logs/2019-06-15T05_32_49_572Z-debug.log
```

**Comment by benjamn** [comment]
Installing is working for me. If it's still not working for you, can you share the `/Users/[my_user].npm/_logs/2019-06-15T05_32_49_572Z-debug.log` file?

**Comment by benjamn** [comment]
Seems like an npm issue, hopefully temporary. Please feel free to reopen this issue if it happens again!
