### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by maamounapprise** [apollographql/apollo-client#4971]
Those two pages are not consistent in the naming of **cacheRedirects**

https://www.apollographql.com/docs/angular/basics/caching/#normalization ( This calls it cacheResolves )

https://www.apollographql.com/docs/react/advanced/caching/#configuration ( This calls it cacheRedirects )

**Comment by jasonpaulos** [comment]
Thanks @maamounapprise! I'll make this change to the apollo-angular docs.
