### ISSUE TITLE
fetchMore, bug with loading status

### ISSUE THREAD

**Issue by onemorekiril** [apollographql/apollo-client#4986]
The bug is related to the issue #4574.
I have also noticed fetchMore acting strange, exactly as @ZikDead mentioned.

You can reproduce it in the [demo](https://codesandbox.io/s/apollo-client-error-template-657in) by clicking on the "Add Person" button.
In the console you will see that updateQuery invokes after we already got loading with status false, and after that being done, we're getting loading status false again, but now with updated query result.

![fetchmore](https://user-images.githubusercontent.com/23583235/59863214-ee0c5180-938c-11e9-9602-abcc608dd2a1.png)

I guess we should get loading status false with updated query just once.

**Comment by svegan** [comment]
Have same. v 2.6.0

**Comment by VictorGaiva** [comment]
At first I expected FetchMore to update the `loading` value to true, but from tests I ran it seems not to be the case. Is it possible to know if more data is being fetched ?

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
