### ISSUE TITLE
Query component does not clear error after success

### ISSUE THREAD

**Issue by joepuzzo** [apollographql/apollo-client#4988]
This still seems to be an issue https://github.com/apollographql/react-apollo/issues/2658 Using `"apollo-client": "^2.6.3",` and `"react-apollo": "^2.5.5"`

**Comment by joepuzzo** [comment]
I have tried executing client.watchQuery manually as well to see what `next()` gets called with and even when chromes network tab clearly shows that the new request had no errors `next()` gets called with a `result` that contains the old errors.

**Comment by wangsongiam** [comment]
I ran into the same issue from `apollo-client@2.5.8`. I also noticed the error got cleared once and then came back.

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
