### ISSUE TITLE
Poor Query Scalability for "Large" Queries

### ISSUE THREAD

**Issue by ohnnyj** [apollographql/apollo-client#4991]
**Intended outcome:**
Reasonably scaled performance with the number of models and fields per model.

**Actual outcome:**
Increasing the number of models / fields returned in a query has a significant impact on load time. Unions add addition time.

**How to reproduce the issue:**
Created a sandbox repo for profiling query performance.

https://github.com/ohnnyj/apollo

This repo contains two tests, one which compares a query with 26 fields vs 1 field while returning 1, 10, and 100 models. The second adds unions to the first test.

All tests were run on a Google Pixel 1.

The time to resolve a query increases with the number of models and fields per model. Introducing unions adds more time.

A colleague pointed out that this likely has a root in the way apollo resolves fields. Correct me if I am wrong but it seems as though each field returns a promise and all promises must resolve before returning the final composed result. This would explain why the client scales poorly.

**Versions**
* System:
  * OS: macOS 10.14.5
* Binaries:
  * Node: 10.15.1
  * npm: 6.4.1
* Android:
  * Google Pixel 1
  * OS 9
  * Android Studio 3.4.1
* from `package.json:`
```
    "apollo-cache-inmemory": "^1.6.2",
    "apollo-client": "^2.6.3",
    "graphql": "^14.3.1",
    "graphql-tag": "^2.10.1",
    "react": "16.8.3",
    "react-apollo": "^2.5.6",
    "react-native": "0.59.9"
```

**Comment by jhampton** [comment]
@benjamn - Have you all seen similar reports about performance related to query sizes?  It would be good to know if you've seen this before, and @ohnnyj has an excellent breakdown and examples linked here.

Thanks!

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
