### ISSUE TITLE
question: why doesn't Javascript have optional static typing ?

### ISSUE THREAD

**Issue by catastrop** [apollographql/apollo-client#4999]
tc39 is adding new things to JS. But why not optional static typing ?

If they do it, we don't have to use Typescript anymore and being able to pass type information to the engine.

We will have less dev dependency.

**Comment by hwillson** [comment]
Interesting question @catastrop, but asking this in the `apollo-client` repo is like asking someone who makes shoes why we still have feet. A shoemaker will likely have a lot to say about feet, and they might even have opinions about what feet will look like in the future. But at the end of the day, they're a current day shoemaker who's focused on making awesome shoes for current day feet. 

If you think rockets attached to our legs would be better then feet, er, I mean javascript should have optional static typing, then please consider working on a [TC39 proposal](https://tc39.es/process-document/).
