### ISSUE TITLE
Network fetch error react apollo 

### ISSUE THREAD

**Issue by CarlFMateus** [apollographql/apollo-client#5014]
Good evening, I do not speak English well, I wanted to ask for help. It is that the network search error occurs. Sometimes it is good to consume services by react apollo with graphql () but it happens a short time and the services fall, this error appears.

Network Error: fetch

Please I need help. Thank you

**Comment by CarlFMateus** [comment]
We are getting these Network error: Failed to fetch errors from Apollo randomly. We don't have any related errors in the API. It seems to be when the user leaves the app open for a while; does Apollo have any bugs related to this when the user leaves an app open for a while?

This error occurs 

Error: Network error: Failed to fetch
    at new ApolloError (bundle.esm.js:76)
    at bundle.esm.js:1556
    at bundle.esm.js:1977
    at Set.forEach (<anonymous>)
    at bundle.esm.js:1975
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (bundle.esm.js:1973)
    at bundle.esm.js:1451

I would really appreciate it if you help me find the solution

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
