### ISSUE TITLE
API is called even when cache-first is selected and the data is in the cache

### ISSUE THREAD

**Issue by developdeez** [apollographql/apollo-client#5048]
API is called even when cache-first is selected and the data is in the cache.
I'm using the <Query> with fetchPolicy cache-first and have noticed that it always calls the api. is this correct behavior?

**Comment by Sulokit** [comment]
Even I'm facing the same issue since two days. We have local resolver with apollo-link-state, that call is also going to network.

**Comment by Thommas** [comment]
I've just updated my package.json to the latest version of all apollo angular packages, and my app sends server queries for all watchQueries no matter what.

InMemoryCache looks completely broken.
However I do see the cache correctly populated in Apollo Dev Tools.

My service:
```
@Injectable()
export class ApolloService {
  /**
   * Constructor
   */
  constructor(
    private apollo: Apollo,
    private httpLink: HttpLink,
    private authService: AuthService
  ) {
    const authLink = new ApolloLink((operation: any, forward: any): any => {
      return this.authService.idToken$.pipe(flatMap((token: string) => {
        operation.setContext({
          headers: new HttpHeaders().set('Authorization', `Bearer ${token}`)
        });
        return forward(operation);
      }));
    });
    this.apollo.create({
      link: concat(
        authLink,
        this.httpLink.create({ uri: environment.apollo.url }),
      ),
      cache: new InMemoryCache()
    });
    console.log('apollo create');
  }

  /**
   * Returns a valid apollo client
   */
  get apolloClient(): Apollo {
    console.log(this.apollo);
    return this.apollo;
  }
}

```

**Comment by developdeez** [comment]
I've laso noticed this in my Network calls. A 204 Response.

Not sure if this helps:
![image](https://user-images.githubusercontent.com/13059525/61115044-70e17300-a446-11e9-8906-a5b884ed9366.png)

**Comment by leanne1** [comment]
FWIW I have the same issue, an application that has fetchPolicy set to "cache-first" and i can see when i re-run the query the cached results load immediately as expected, but the network request still fires, loading state is rendered, and remote data then comes in and overwrites cached data. I have set my fetch policy to "network-only" as a workaround to prevent a buggy UX which is not what I would like to do. I have current latest Apollo packages as at time of writing.

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
