### ISSUE TITLE
Refetching error after resetStore()

### ISSUE THREAD

**Issue by ghost** [apollographql/apollo-client#5049]
If user sign in, user is redirected to main page (route="/") this behavior is intended
When user sign out(sign out always trigger resetStore) from no main page and then re-sign in cause error

my code is something like this

```
App.js
<Query >
  if (loading) return <div />
  return (
    <Header>
    <main>
       <Route exact path="/" components={Homepage} />
       <Route exact path="/others" components={Others} />
  );
```

```
HomePage.js
<Query >
  if (loading) return <div />
  return (
    <div>
       {data.something.map()}  // this occur errors that cannot read property of undefined
    </div>
  )

```
I thought when Query component mount after resetStore, Query component fetch data from a server, but not happen. Am I missing something?

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
