### ISSUE TITLE
Network error is causing an unhandled exception

### ISSUE THREAD

**Issue by adamivancza** [apollographql/apollo-client#5058]
**Intended outcome:**
Network errors should always pop up on error link.

**Actual outcome:**
An exception that was raised by fetch is causing an unhandled exception.

**How to reproduce the issue:**
Use apollo-boost and set [axios-fetch](https://github.com/lifeomic/axios-fetch) as fetch. Set some timeout to axios-fetch and when timeout occurs it's crashing the app.

Stack trace from bugsnag:
n Network error: timeout of 10000ms exceeded 
    node_modules/apollo-client/bundle.umd.js:92:30 ApolloError
    node_modules/apollo-client/bundle.umd.js:1581:37 
    node_modules/apollo-client/bundle.umd.js:2001:23 
    [native code] forEach
    node_modules/apollo-client/bundle.umd.js:1999:33 
    [native code] forEach
    node_modules/apollo-client/bundle.umd.js:1997:27 broadcastQueries
    node_modules/apollo-client/bundle.umd.js:1476:28 
    node_modules/promise/setimmediate/core.js:37:14 tryCallOne
    node_modules/promise/setimmediate/core.js:123:25 
    node_modules/react-native/Libraries/Core/Timers/JSTimers.js:152:6 _callTimer
    node_modules/react-native/Libraries/Core/Timers/JSTimers.js:200:17 _callImmediatesPass
    node_modules/react-native/Libraries/Core/Timers/JSTimers.js:473:11 callImmediates
    [native code] callImmediates
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:337:11 value
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:11 
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:314:8 value
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:17 value
    [native code] value
    [native code] value

it's crashing on this line: `var _this = _super.call(this, errorMessage) || this;`

**Versions**
System:
    OS: macOS 10.14.5
  Binaries:
    Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v11.15.0/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 55.0.3
    Safari: 12.1.1

**Comment by dhavaljardosh** [comment]
any resolution?

**Comment by jaynetics** [comment]
We are also seeing `Network error: undefined` in our error tracker coming from this same line. 

We are using the latest apollo-client, apollo-link-error, apollo-link-retry, and no custom fetch.

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
