### ISSUE TITLE
How to refetch query in a component located on another page, after some operation, but only when you go to this page?

### ISSUE THREAD

**Issue by juicylevel** [apollographql/apollo-client#5062]
There is a component `ComponentAContainer` on the page `/page1` that requests some data by `graphql(QUERY)` HOC. When requested, a cache is used.

```
// ComponentAContainer.js on /page1

import { graphql } from 'react-apollo';
import ComponentA from './ComponentA';
import { GET_DATA1_QUERY } from './queries';

export default graphql(GET_DATA1_QUERY)(ComponentA);
```

On another page `/page2` there is a button, when clicking on which a mutation is performed, after which the command should be sent to execute the request to the component on the page `/page1`, but not immediately, but only when going to this page.

```
// ComponentBContainer.js on /page2

import React from 'react';
import { graphql } from 'react-apollo';
import ComponentB from './ComponentB';
import { MUTATION_DATA2 } from './queries';

const ComponentBConatiner = ({ mutationData2 }) => (
 <ComponentB onButtonClick={
   mutationData2({
     variables: {
       input: { foo: 'bar' }
     }
   }).then(() => {
     // ????????????
     // What do need to do to the ComponentAConatiner to
     // execute the query GET_DATA1_QUERY, but only when you go 
     // to the page /page1?
     // ????????????
   });
 } />
);

export default graphql(MUTATION_DATA2, { name: 'mutationData2' })(ComponentBConatiner);
```
The component `ComponentBContainer` in which the mutation occurs does not know anything about the component `ComponentAContainer` in which to refetch the data.
The `refetchQueries` function is not appropriate, since the data is immediately requested. 
The `writeQuery` function is not appropriate, since the mutation does not return data that could be written to the `writeQuery`. 
Using the `network-only` fetch policy is not appropriate, since I want to use the cache if the data has not changed.

**Comment by cy6eria** [comment]
@juicylevel Hi. It's only a guess, I haven't checked it. Try to use a local state ([you can read about it here](https://www.apollographql.com/docs/react/essentials/local-state/)) or another way to store data locally. Store the latest update date there and use it in your query as a variable. The query should refetch data if some variables changed and don't if it's not.

**Comment by bigDado** [comment]
could've been so simple... but it isn't

**Comment by checkmatez** [comment]
Use React state:
```
const [needToRefetch, setNeedToRefetch] = React.useState(false)
const {} = Apollo.useQuery(..., { fetchPolicy: needToRefetch ? 'network-only' : 'cache-first' })
```
and setNeedToRefetch on mutationComplete. If it is hard to pass setNeedToRefetch around, you can wrap it in React.Context.

**Comment by hwillson** [comment]
Closing as this isn't an Apollo Client bug (see https://github.com/apollographql/apollo-client/issues/5062#issuecomment-524238783 for one approach to handling this). Thanks!
