### ISSUE TITLE
getDirectiveInfoFromField can return null even if type prohibits it

### ISSUE THREAD

**Issue by Tigge** [apollographql/apollo-client#5063]
**Intended outcome:**

The DirectiveInfo type is declared as:

```typescript
export type DirectiveInfo = {
  [fieldName: string]: { [argName: string]: any };
};
```

The `getDirectiveInfoFromField` that is using this type as a return value should not return `null`.

**Actual outcome:**

However, `getDirectiveInfoFromField` is returning null on this line:

https://github.com/apollographql/apollo-client/blob/master/packages/apollo-utilities/src/directives.ts#L38

Which should not be allowed. 

**How to reproduce the issue:**

We are probably using a bit more strict error and type checking in our project, so I'm getting tslint error https://palantir.github.io/tslint/rules/strict-type-predicates/ when trying to compare the info.directive field in a apollo link resolver.

**Versions**

```
  System:
    OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
  Binaries:
    Node: 11.5.0 - /usr/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.4.1 - /usr/bin/npm
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 60.8.0
```

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
