### ISSUE TITLE
graphql query returning null with client.query(i.e apollo client) while returning data on playground.

### ISSUE THREAD

**Issue by prabhat04011998** [apollographql/apollo-client#5065]
when trying to get data with graphql then returning response but when trying client.query({}) then 
res.data.XYZ is null.
showing this in console.

```
{
data: Object { xyz: null }
loading: false
networkStatus: 7
stale: false
}
```

**Comment by temitopeadesoji** [comment]
please any solve for this

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
