### ISSUE TITLE
getting Object doesn't support property or method 'of' IE <= 10

### ISSUE THREAD

**Issue by batusai513** [apollographql/apollo-client#5066]
**Expected Behavior**
fetch data via @client queries should bring data from the server on IE <= 10

**Actual Behavior**
When trying to fetch @client queries on IE 10 and below I get a client side error `getting Object doesn't support property or method 'of'`, this only happens with client queries, the error is not visible on the developer console unless you explicitly log the error inside the Query render method (it's been swallowed)

https://github.com/apollographql/apollo-client/blob/7eaf4132cd2cd6244260777799406aaa03fcf377/packages/apollo-client/src/core/QueryManager.ts#L1163
when debugging I can follow the trace to this method:
```js
    QueryManager.prototype.getObservableFromLink = function (query, context, variables, deduplication) {
        var _this = this;
        if (deduplication === void 0) { deduplication = this.queryDeduplication; }
        var observable;
        var serverQuery = this.transform(query).serverQuery;
        if (serverQuery) {
           // not related
        else {
            // This one throws the error!!!
            observable = Observable.of({ data: {} });
            context = this.prepareContext(context);
        }
        var clientQuery = this.transform(query).clientQuery;
        if (clientQuery) {
            observable = asyncMap(observable, function (result) {
                return _this.localState.runResolvers({
                    document: clientQuery,
                    remoteResult: result,
                    context: context,
                    variables: variables,
                });
            });
        }
        return observable;
    };
```
<img width="604" alt="Screenshot 2019-07-16 at 16 51 15" src="https://user-images.githubusercontent.com/996671/61305075-780fd480-a7ea-11e9-95e7-609ef916dfc4.png">

**Versions**
```
  System:
    OS: macOS 10.14.5
  Binaries:
    Node: 12.3.1 - ~/.nvm/versions/node/v12.3.1/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.3.1/bin/npm
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 67.0.4
    Safari: 12.1.1
  npmPackages:
    apollo-cache-inmemory: ^1.6.0 => 1.6.0 
    apollo-client: ^2.6.0 => 2.6.0 
    apollo-link: ^1.2.11 => 1.2.11 
    apollo-link-error: ^1.1.10 => 1.1.10 
    apollo-link-http: ^1.5.14 => 1.5.14 
    apollo-link-retry: ^2.2.13 => 2.2.13 
    react-apollo: ^2.5.6 => 2.5.6 
```

**Comment by jm-chong** [comment]
Any updates for this issue? I have same problem.

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
