### ISSUE TITLE
Should we still get data if an error is returned?

### ISSUE THREAD

**Issue by mchong-teal** [apollographql/apollo-client#5069]
**Intended outcome:**

Displaying results when both data and error are returned by apollo server (e.g. error occurs when resolving field on a result.  Apollo server returns a response with both data and error fields, with partially populated data.   Would like to access that data in my component to display partial results alongside my err message.
**Actual outcome:**

data is null in my Query component, despite being there in the response from apollo-server :(.
**How to reproduce the issue:**

Created a basic reproduction here.
https://codesandbox.io/s/apollo-client-error-template-drmup

Not super familiar with apollo-link, so may not be returning the result correctly, but the intention is to return partial results in data, with an Error.
**Versions**

npx: installed 1 in 1.473s

  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
  Binaries:
    Node: 8.10.0 - /usr/bin/node
    npm: 6.10.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0.4
  npmPackages:
    apollo-cache-inmemory: ^1.6.0 => 1.6.0 
    apollo-client: ^2.5.1 => 2.5.1 
    apollo-link-context: ^1.0.17 => 1.0.17 
    apollo-link-error: ^1.1.11 => 1.1.11 
    apollo-link-http: ^1.5.14 => 1.5.14 
    react-apollo: ^2.5.5 => 2.5.5

**Comment by mchong-teal** [comment]
Hey, that does sound like it would solve my use case, but it doesn't seem to have the behaviour I would expect.  It also doesn't seem to fix the issue in the reproduction I provided (not quite the same behaviour I'm seeing though:
- If I load a component (succesfully) with a variable for id=person a, and then change the props to change the person who is loaded (id=person b) to a failing query, the partial data I get is not from the response (partial person b data as I would expect), it is from person a (incorrect data and not the behaviour I would expect).  I guess it's showing me cached data from the query, and not cached data on the object.
- Examining the network response from the apollo-server, I can see that the json in the response includes the data I would want to see.  Is there a way to have the query component use that data?

**Comment by jrose-carecloud** [comment]
@mchong-teal  I added `errorPolicy="ignore"` to your example and the data was then available

**Comment by hwillson** [comment]
See the solution in https://github.com/apollographql/apollo-client/issues/5069#issuecomment-516581746. Thanks!
