### ISSUE TITLE
Potential Memory leak with Apollo client and pollInterval

### ISSUE THREAD

**Issue by tlupo** [apollographql/apollo-client#5072]
**Intended outcome:**

Stable memory usage when using Apollo Client (react-apollo & apollo-boost) in a React Native application. 

**Actual outcome:**

Linear increase of memory usage (« JavaScript Allocations » in « Timelines » tab of Safari « Web Inspector » tool) when using Apollo Client query and pollInterval to keep mobile app data up to date.

**How to reproduce the issue:**

I work on a React Native mobile application which has to do recurrent API calls and I have some memory issues which lead to an app crash after few hours of use. I’ve made some research about memory leaks in React Native and I found a lot of information in this post : https://blog.swmansion.com/hunting-js-memory-leaks-in-react-native-apps-bd73807d0fde 

I have followed the steps of the section « Inspecting JS memory with Safari » and I think there is maybe an issue with my integration of Apollo Client.

Using one query with pollInterval option activated, I can see an increase of « Retained Size » (when I compare snapshots) between different snapshots. 

**Snapshot 1 vs Snapshot 2 (around 5 min between snapshots) with pollInterval activated**

![1](https://user-images.githubusercontent.com/2486493/61481425-8c91cf80-a998-11e9-929a-90b83ff2e896.png)

**Snapshot 2 vs Snapshot 3 (around 5 min between snapshots) with pollInterval activated**

![2](https://user-images.githubusercontent.com/2486493/61481431-91ef1a00-a998-11e9-8954-db4a90286791.png)

If I comment the pollInterval option of my query, this increase of « Retained  Size « » no longer exists.

**Snapshot 1 vs Snapshot 2 (around 5 min between snapshots) with pollInterval deactivated**

![3](https://user-images.githubusercontent.com/2486493/61481448-97e4fb00-a998-11e9-9678-7e3fe63ed25b.png)

**Snapshot 2 vs Snapshot 3 (around 5 min between snapshots) with pollInterval deactivated**

![4](https://user-images.githubusercontent.com/2486493/61481458-9ddadc00-a998-11e9-83ef-a784ddb9b779.png)

**A sample of one of the « retained » object which shows an accumulation of query related data**

![5](https://user-images.githubusercontent.com/2486493/61481471-a501ea00-a998-11e9-8eab-9bec62f7f2e1.png)

This issue occurs on an iPad Air 2 simulator in Release configuration.

My query is initialized via :

```
this.query = this.props.client.watchQuery({
            query: MY_QUERY,
            fetchPolicy: 'cache-and-network',
            pollInterval: 3000,
            variables
        })

this.querySubscription = this.query.subscribe({
            next: ({data,loading}) => {
	    },
            error: (error) => {
	    }
})
```

On my componentWillUnmount :

```
this.query.stopPolling()
this.querySubscription.unsubscribe()
```

I also tried with the `<Query></Query>` top component and it produced the same issue.

**Versions**

```
 System:
    OS: macOS 10.14.5
  Binaries:
    Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
  Browsers:
    Chrome: 75.0.3770.142
    Safari: 12.1.1
  npmPackages:
    apollo-boost: ^0.1.10 => 0.1.10 
    apollo-cache-persist: ^0.1.1 => 0.1.1 
    apollo-link: ^1.2.2 => 1.2.2 
    apollo-link-context: ^1.0.8 => 1.0.8 
    apollo-upload-client: ^8.1.0 => 8.1.0 
    react-apollo: ^2.1.9 => 2.1.9
```

The same issue occurs if I try to upgrade these packages (apollo-boost@0.4.3 and react-apollo@2.5.8). 

It’s a working hypothesis for now and if somebody had a similar issue or has a suggestion, I would be very grateful !

**Comment by tlupo** [comment]
I have created this repo to reproduce the issue : https://github.com/tlupo/apollo-client-test-memory-leak

After cloning the project and run `npm install`, if you have an error when running `react-native run-ios` -> `cd ios && pod install` seems to fix the issue

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
