### ISSUE TITLE
src/util/Observable.ts observable declaration conflicts with rxjs

### ISSUE THREAD

**Issue by vCillusion** [apollographql/apollo-client#5074]
I'm seeing this error when Apollo Client is used with RxJs:

ERROR in node_modules/@types/zen-observable/index.d.ts(10,18): error TS2687: All declarations of 'observable' must have identical modifiers.
node_modules/rxjs/internal/symbol/observable.d.ts(4,9): error TS2687: All declarations of 'observable' must have identical modifiers.

See also angular/angular#24245 and stackoverflow.com/q/50639530.

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
