### ISSUE TITLE
Cannot read property `serverMutation` from null when response data is null

### ISSUE THREAD

**Issue by ViacheslavNikolaienkoDevPro** [apollographql/apollo-client#5075]
**Intended outcome:**
I can get origin error from server mutation

**Actual outcome:**
I get network error with the message: `Can not read property serverMutation from null`.

**How to reproduce the issue:**
I am trying to execute a query like:
```
gql`
  mutation MyMutation(...args) {
    serverMutation(...args) {
      ...serverFields
    }

    localMutation @client
`
```

typeDefs:
```
gql`
  extend type Mutation {
    localMutation: Type
  }
`
```

Client config:
```
const client = new ApolloClient({
  uri,
  clientState: {
    typeDefs,
    defaults: { ...propreties },
    resolvers: {
      Mutation: {
        localMutation: (root, _, { client }) => {
          // It is not called
          return doSomething();
        }
      }
    }
  }
});
```

serverResponse for mutation:
```
{
  data: null,
  errors: [ ...errors ]
}
```

**Notes**
I was debugging the issue and seems like the problem is in Apollo Client because the network error comes to `react-apollo` error handler after the mutation was executed by Apollo Client.

**Versions**
```
System:
    OS: macOS 10.14.5
  Binaries:
    Node: 8.11.4
    npm: 6.5.0
  Browsers:
    Chrome: 75.0.3770.142
  npmPackages:
    apollo-boost: ^0.3.1 => 0.3.1 
    apollo-client: ^2.5.1 => 2.6.3 
    react-apollo: ^2.5.3 => 2.5.8 
```

Thank you.

**Comment by ezhuikova** [comment]
Hi! Did you solve this problem?

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
