### ISSUE TITLE
When using Jest, pollInterval leads to open handles

### ISSUE THREAD

**Issue by thabemmz** [apollographql/apollo-client#5088]
**Intended outcome:**
When running a Jest test on a React Native project, with the following (simplified) component:
```
const Component = () => <Query query={...} pollInterval={20000}>{(result) => this.renderSomething(result)}</Query>
```

And the following Jest test:
```
  const component = renderer.create(<MockedProvider mocks={...}><Component /></MockedProvider>)
  await wait(0)
  expect(component.toJSON()).toMatchSnapshot()
```

I would expect Jest to succeed without any errors.

**Actual outcome:**
The Jest test succeeds, but Jest exits with the following error:
```
Jest did not exit one second after the test run has completed.
This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

This looks a lot like an issue that was fixed in [this issue](https://github.com/apollographql/react-apollo/pull/2151). This issue introduces clearing the scheduler on `componentDidUnmount` on the `MockedProvider` component. Since this is old, this has already been rewritten to one `client.stop()` method, which does all of this stuff internally.

However, when looking at the `Querymanager.ts` code [at the `stopPollingQuery` function](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/QueryManager.ts#L1405) I see that the polling query reference is deleted, but the `clearTimeout` of the polling query is never called. This leads Jest to wait for the last open timeout function to complete. Is there any intention to not call the `clearTimeout` here? Because as far as I can see, it can lead to memory leaks as well, but I might not see the big picture here.

**How to reproduce the issue:**
See **intended outcome**

**Versions**
`apollo-client` 2.6.3
`react-apollo` 2.5.8
`jest` 24.8.0

**Current Workaround**
When using `jest.useFakeTimers()` before your test, this issue disappears (since no actual time was harmed during testing). While this might be a good option in general while testing with `pollInterval`, the issues I ran into were very unexpected.

**Notes**
My example is simplified a lot. Please let me know if you need a more detailed example to reproduce this. I left this for now, as my actual question was about the `clearTimeout` method.

**Comment by stevehanson** [comment]
I'm facing this issue as well, using:

```
apollo-boost: 0.4.7
apollo-client 2.6.7
```

`jest.useFakeTimers()` didn't work in my case. What I ended up doing is extracting the polling interval out into a constant and then mocking that constant to be `0` in my tests (the Apollo docs mention that a timeout of `0` means no polling).

Specifically, I added the following to my `jest.setup.js` to ensure that the constant is always mocked in my tests:

```js
const mockApolloPolling = () => {
  const constants = jest.requireActual('./src/lib/constants');
  return {
    ...constants,
    POLL_INTERVAL: 0,
  };
};

jest.mock('./src/lib/constants', () => mockApolloPolling());
```

**Comment by TSMMark** [comment]
Good idea @stevehanson, I'm already mocking fetchPolicy in tests, might as well mock pollInterval too. Thanks!

**Comment by hwillson** [comment]
Sounds like https://github.com/apollographql/apollo-client/issues/5088#issuecomment-618654490 helped - closing, thanks!
