### ISSUE TITLE
2 http requests in server for each request from client

### ISSUE THREAD

**Issue by saostad** [apollographql/apollo-client#5093]
does anybody know why I am getting 2 HTTP requests in my graphql server for each request from client?
it is causing error for me because first one doesn't have authorization token on it.

**Comment by chaunceyau** [comment]
Can you provide more context?

**Comment by dylanwulf** [comment]
Check the HTTP method. Is the first one OPTIONS, and the second one POST? If so, this is completely normal behavior enforced by the browser. I don't think apollo-client has any control over this. You should configure your server to allow OPTIONS requests.

**Comment by saostad** [comment]
Sorry, it was a CROS problem after I configured the server correctly it worked.
