### ISSUE TITLE
Use directive on client query

### ISSUE THREAD

**Issue by max10rogerio** [apollographql/apollo-client#5094]
It's possible use directives in client query on Apollo?
Example:
I have a directive `@Upper`

> Upper.js
```javascript
import { SchemaDirectiveVisitor } from 'graphql-tools'
import { defaultFieldResolver } from 'graphql'

class Upper extends SchemaDirectiveVisitor {
  visitFieldDefinition(field) {
    const { resolve = defaultFieldResolver } = field
    field.resolve = async (...args) => {
      const result = await resolve.apply(this, args)
      if (typeof result === 'string') {
        return result.toUpperCase()
      }

      return result
    }
  }
}

export default Upper
```
> Directives.gql

`directive @Upper on FIELD`

> PlayGround

```
query LIST_USERS {
  users {
    id
    name @Upper
  }
}
```

In playground the directives are:
![show](https://user-images.githubusercontent.com/21085292/61902289-16412000-aef8-11e9-9f47-29999444c873.jpg)

**Comment by chaunceyau** [comment]
Is this what you are talking about?
https://www.apollographql.com/docs/graphql-tools/schema-directives/#examples
