### ISSUE TITLE
Put operationName to GET parameter of the actual URI used for request

### ISSUE THREAD

**Issue by extempl** [apollographql/apollo-client#5100]
Is it possible?

It would be even handier to be able to seacrch&filter in the log or just visually determine request between tens of the same URI.
May be optional for dev state only if may influence something like performance or cache.

So it could look like `../master?operation1` instead of series of `../master` requests.

Related to https://github.com/apollographql/apollo-client/issues/259

**Comment by hwillson** [comment]
I'm not sure how this relates to Apollo Client, so closing for now. Thanks!
