### ISSUE TITLE
Component is not consistent with state after mutation

### ISSUE THREAD

**Issue by gaetansnl** [apollographql/apollo-client#5102]
If I have this query on a component `ComponentA`
````
objectA(id:$id){
 id,
 subobject{
    id, # Id here is 12345
    somefield
 }
}
````
And if I do a mutation and my mutation result look like this
````
objectA{
 id,
 subobject{
    id #Id here is 6789
 }
}
````
**Actual outcome:**

The store will stay consistent, so `somefield` disappear. No problem here

But now `ComponentA` can't render correctly. But nothing happens. And I see no errors.

So `ComponentA` is inconsistent with `objectA`

**Intended outcome:**

Since I don't want partial data, I was expecting a refetch from `ComponentA`. Exactly like when a component is loaded for the first time: data is missing from the cache, so we fetch it.

**Versions**
```
        "apollo-cache-inmemory": "^1.6.2",
        "apollo-client": "^2.6.3",
        "apollo-link": "^1.2.12",
        "apollo-link-batch-http": "^1.2.12",
        "apollo-link-context": "^1.0.18",
        "apollo-link-error": "^1.0.10",
        "apollo-utilities": "^1.2.0",
```

**Comment by chaunceyau** [comment]
What is the reasoning you don't want to use _returnPartialData_ or _partialRefetch_?

**Comment by gaetansnl** [comment]
I don't use `returnPartialData` because I don't want partial data. But even if I use it with `partialRefetch` it is not working according to the docs : 

> and the returned data is reset to an empty Object by the Apollo Client QueryManager

The returned object isn't empty for me.

But maybe I'm missing something

**Comment by camfletch** [comment]
I think this is related to https://github.com/apollographql/apollo-client/issues/5341

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
