### ISSUE TITLE
warning when using deprecated queries with apollo client

### ISSUE THREAD

**Issue by dude-awesome** [apollographql/apollo-client#5125]
When I use the `@deprecated` directive on my graphql server to flag queries or fields as deprecated it would be awesome to get a warning (in the developer console) and the reason that I have used a deprecated field with the apollo client.

**Comment by smeijer** [comment]
This would be so helpful. How are you handling this now? Are there manageable workarounds?

**Comment by dylanwulf** [comment]
Apollo-client itself cannot do this because it has no knowledge of the server-side schema. But what you can do is use the graphql eslint plugin: https://github.com/apollographql/eslint-plugin-graphql

**Comment by smeijer** [comment]
We already feed it the fragment matcher info. I think it would be fine to feed it "depreciation info" for usage in develop mode.
