### ISSUE TITLE
Crashing react-native application  java.lang.NullPointerException while calling query 

### ISSUE THREAD

**Issue by shreyansh2495** [apollographql/apollo-client#5126]
Getting following exception while making any query in android using apollo-client.
Tried apollo-client and apollo-boost but still getting same error for all the api.
Each query return loading: true and then crashes.
- React-native version : 0.60.4
- Apollo Client Config
```
export default client = () => {
    return new ApolloClient({
        uri: Config.APOLLO_GRAPHQL_SERVER_URL,
        request: async (operation) => {
            let accessToken = await _getToken()
            accessToken = accessToken ? JSON.parse(accessToken) : null;
            console.log("token", accessToken)
            operation.setContext({ headers: { authorization: accessToken } });
        },
        onError: ({ graphQLErrors, networkError }) => {
            if (graphQLErrors) {
                console.log("GraphqlError", graphQLErrors)
            }
            if (networkError) {
                console.log("neworkerro", networkError)
            }
        },
        fetch
    });
}
```

```
Exception in native call
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.facebook.react.bridge.ReadableMap.getString(java.lang.String)' on a null object reference
        at com.facebook.react.modules.blob.FileReaderModule.readAsText(FileReaderModule.java:43)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by jasonpaulos** [comment]
@shreyansh2495 what is `fetch`?

**Comment by shreyansh2495** [comment]
> @shreyansh2495 what is `fetch`?

its a fetch client, i tried without fetch also but having the same error

**Comment by shreyansh2495** [comment]
Found the exact issue, its not because of apollo client but in turn its because of fetch used by apollo client, the solution to this is to replace the built in fetch with rn-fetch-blob. Insert the below code at index.js of react-native application.

`
const Fetch = RNFetchBlob.polyfill.Fetch
// replace built-in fetch
window.fetch = new Fetch({
    // enable this option so that the response data conversion handled automatically
    auto : true,
    // when receiving response data, the module will match its Content-Type header
    // with strings in this array. If it contains any one of string in this array, 
    // the response body will be considered as binary data and the data will be stored
    // in file system instead of in memory.
    // By default, it only store response data to file system when Content-Type 
    // contains string `application/octet`.
    binaryContentTypes : [
        'image/',
        'video/',
        'audio/',
        'foo/',
    ]
}).build()
`
