### ISSUE TITLE
useLazyQuery polling?

### ISSUE THREAD

**Issue by zebbedi** [apollographql/apollo-client#5140]
Just trying out the new useLazyQuery hook and the documentation and the TS seem to suggest that it supports polling, however I can't seem to make it work. 

Can someone confirm if it does indeed support polling?

**Comment by hwillson** [comment]
@zebbedi Polling should work; it doesn't start until after your first call to the execute function. If it isn't working, then that's a bug. Any chance you could put together a small reproduction that shows the issue?

**Comment by zebbedi** [comment]
Apologies i think we may have jumped the gun. 

I think the thing that tripped us up was that we replaced a useQuery which had a 'skip: true' for initial load. With this the startPolling function is available immediately. When we swapped it out for a useLazyQuery the startPolling function is undefined and then becomes available only after the first execution. 

Not sure if that's still a consistency issue or expected?

**Comment by hwillson** [comment]
Interesting @zebbedi - that does't sound intended. I'll take a look - thanks!

**Comment by masad-frost** [comment]
I have a PR here since October https://github.com/apollographql/react-apollo/pull/3645, I can move it to https://github.com/apollographql/apollo-client/ if there's interest.

**Comment by sanpablomarket** [comment]
this appears to still be broken. `startPolling` and `stopPolling` are undefined when returned from the lazy hook.

**Comment by Badbreaddead** [comment]
Anyway to get around this problem?

**Comment by Badbreaddead** [comment]
If anybody stumbles upon this: you can call initialQuery and then call startPolling

**Comment by arieller** [comment]
so basically subscribeToMore and polling is broken? :( :((((((((((((

**Comment by bcheidemann** [comment]
Which version do I need to upgrade to in order to get the fix for this?

**Comment by simoleone** [comment]
@bcheidemann `v3.5.0` and up, which was released in November 2021

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/150510/200807818-c2180e01-3336-4591-a82f-3ad591fbd1cf.png">
