### ISSUE TITLE
Adding User-Agent header doesnt work

### ISSUE THREAD

**Issue by subashsurendrank** [apollographql/apollo-client#5142]
Hi Team,

When I tried to add a custom User-Agent in the request header, I dont see them in the browser request. 

User-Agent is not in Mozilla's list of [forbidden headers:](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name)

Below is the code snippet,

_const client: ApolloClient<{}> = new ApolloClient({
  uri: '/graphql',
  headers: {
    'User-Agent': 'Custom_AGent'
  }
});
client.defaultOptions = {
  watchQuery: {
    fetchPolicy: 'no-cache',
    errorPolicy: 'all'
  },
  query: {
    fetchPolicy: 'no-cache',
    errorPolicy: 'all'
  }
};_

**Comment by andrewfluck** [comment]
in most browsers, they disallow this (UA spoofing) anyway because of security reasons.

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!

**Comment by toini** [comment]
I'm trying to set user agent for websocket using @apollo/client version 3.5.10 but it seems to fail. No headers appear at the server side.

```
const webSocketClient = createClient({
      url: liveSubscriptionUrl,
      connectionParams: {
        token: this.#token,
      },      
      webSocketImpl: ws,
});
   
const apolloClient = new ApolloClient({
  link: wsLink,
  headers: { 'User-Agent': 'Homey/7.3.0 com.app/1.5.14' }, 
  cache: new InMemoryCache() as any
});

return apolloClient.subscribe({  
  query: xxx,
  variables: {}, 
});
```

Is there a way to do that?

**Comment by toini** [comment]
Tagging @hwillson here. Is this a know thing or am I doing something wrong (see above).
