### ISSUE TITLE
useLazyQuery not working for me

### ISSUE THREAD

**Issue by Firebrand** [apollographql/apollo-client#5143]
I copied the code sample from the documentation almost line for line. Made sure my API successfully returns this exact data I'm requesting here etc. useLazyQuery just always returns null.

See it here:  https://codesandbox.io/s/sharp-keller-fpt0x

**Comment by hwillson** [comment]
@Firebrand Can you update your CS to log `error` somewhere? E.g.:

```js
const [getUser, { called, loading, error, data }] = useLazyQuery(GET_USER);
console.log('error', error);
```

Or better yet; could you disable the `fpt0x.csb.app` CORS `Access-Control-Allow-Origin` set on your Heroku endpoint, so I can test things locally?

> Access to fetch at 'https://codikon-back.herokuapp.com/graphql' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'https://fpt0x.csb.app' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by Firebrand** [comment]
@hwillson   Thanks so much man, I disabled all the CORS stuff and worked my way back from there. Turns out I needed "credentials: true" on the CORS setting on the server to use "credentials: include" on the client.
