### ISSUE TITLE
useSubscription: No writeCache method exposed onSubscriptionData: ({ client }).

### ISSUE THREAD

**Issue by TheoMer** [apollographql/apollo-client#5144]
**Intended outcome:**
Upon issuing a subscription I was hoping that I would be able to access `writeCache` from `onSubscriptionData: ({ client }) `

**Actual outcome:**

console logging the client reveals `cache -> readQuery` but no `writeQuery`.

What am I overlooking here?

**How to reproduce the issue:**
```
  const unsubscribe = useSubscription(
    ALL_ITEMS_SUBSCRIPTION,
    { 
      variables: {},
      onSubscriptionData: ({ subscriptionData, client }) => {
        if (!subscriptionData.data) return null;

        const prev = client.cache.readQuery({ query: ALL_ITEMS_QUERY, varaiables: {} });

        console.log("client  = ", client);
      },         
    }
  );

  useEffect(() => {
    let isSubscribed = true;
    if(isSubscribed) {
      unsubscribe;
    }
    return () => {
      isSubscribed = false
    };
  },[props.urlReferer]);
```

**Versions**

"@apollo/react-hooks": "^3.0.0"
"apollo-boost": "^0.1.28"

**Comment by TheoMer** [comment]
So whether I obtain an ApolloClient from `apollo-boost 0.1.28` or `apollo-client 2.6.3`, the result is the same, no writeQuery to be seen anywhere:

![ApolloClient](https://user-images.githubusercontent.com/15969262/62665853-aa8b9800-b978-11e9-8ec0-35a0261d6bd8.jpg)

**Comment by RxAssim** [comment]
Just checked in Apollo-client and the `writeQuery`you mentioned in `onSubscriptionData` seems to be working fine. (v2.6.4).

Which apollo-client version are you using ?

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
