### ISSUE TITLE
Android Cannot read property 'data' of null

### ISSUE THREAD

**Issue by ramosquito5** [apollographql/apollo-client#5150]
Libraries:
    "react-native": "0.59.1",
    "apollo-cache-persist": "^0.1.1",
    "apollo-link-context": "^1.0.17",
    "apollo-link-error": "^1.1.11",
    "apollo-link-http": "^1.5.15",
    "react": "16.8.3",
    "react-apollo": "^2.4.13",

I have a local server that has an API that allows me to test an app and its behaviour. When I turn of the server or when the server returns for example a 413 Request Entity Too Large error which does not pass through the apollo-server application I get the following error. 

![image](https://user-images.githubusercontent.com/11376153/62740339-321aea80-b9fd-11e9-94dc-1a1da6e2d82b.png)

I would like to be able to catch the error and present the issue to the end-user but as it is, the app only crashes and no message can be displayed. 

Any help will be most appreciated

**Comment by ramosquito5** [comment]
Android compile version 
compileSdkVersion = 28
gradle:3.3.1

**Comment by Ramesh-Chathuranga** [comment]
Did you resolve this issue?

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
