### ISSUE TITLE
writeQuery After clearStore doesn't broadcast changes

### ISSUE THREAD

**Issue by dsanders11** [apollographql/apollo-client#5155]
**Intended outcome:**

User logs out, so `clearStore` is called to clear the cache. User then logs in again, and the `update` function for the login mutation updates the store using `writeQuery`, which should broadcast the change and update the UI.

**Actual outcome:**

Cache is updated, but changes are no broadcasted, so UI doesn't update.

**How to reproduce the issue:**

Reproduce case: https://codesandbox.io/s/apollo-client-error-template-un36k

1. Click 'Log Out'
2. Click 'Log In'

Refresh page

1. Click 'Log In'

In the first case, nothing changes. In the second case, the name changes to 'Other Guy'

**More Info**

Manually refetching a query after clearing the store will put it back into broadcast mode. The issue seems to be that `QueryStore.reset` will delete the query entirely, making it not visible for broadcasts. Refetching will put it back in there. Using `writeQuery` does not re-initialize the query in `QueryStore`, so no broadcasts occur.

**Versions**

2.6.3

**Comment by martdavidson** [comment]
I'm having this exact issue. @dsanders11 did you come up with a workaround?

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
