### ISSUE TITLE
Variables not updated when reconnecting

### ISSUE THREAD

**Issue by AlexCppns** [apollographql/apollo-client#5166]
**Intended outcome:**

`cursor` passed in variables should update when the client disconnects for X reason.

**Actual outcome:**

Variables are static so the subscription restarts from initial cursor on disconnection.

**How to reproduce the issue:**

- Implement a subscription with a `cursor` saved locally. 
- Force a disconnection
- When the client automatically reconnects, check that the cursor passed in variables is not updated.

**Versions**

System:
    OS: macOS 10.14.5
  Binaries:
    Node: 10.7.0 - ~/.nvm/versions/node/v10.7.0/bin/node
    Yarn: 1.15.2 - ~/.nvm/versions/node/v10.7.0/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v10.7.0/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 67.0.2
    Safari: 12.1.1
  npmPackages:
    apollo-boost: ^0.3.1 => 0.3.1 
    apollo-client: ^2.5.1 => 2.5.1 
    apollo-link-ws: ^1.0.17 => 1.0.17 
  npmGlobalPackages:
    apollo-codegen: 0.20.2
    apollo: 2.8.3

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
