### ISSUE TITLE
After using useLazyQuery hook, "called" parameter remains "true" when the component re-renders

### ISSUE THREAD

**Issue by alexandra-c** [apollographql/apollo-client#5179]
I'm trying to use useLazyQuery hook, in a function component, and execute the query on button click. So, i'm using the "called" parameter  alongside "loading" to check if my "Navigate to Google" button was pressed and the query was executed successfully to continue executing my desired action (in this case navigate to www.google.com).

On the first execution everything works as expected but when i'm executing another action in the same screen that triggers a re-render, the "called" parameter from the previous action is still "true" so my previous action is executed again even though i didn't pressed the "Navigate to Google" button again.

Here is my TestFunctionComponent. To reproduce the issue first press the "Navigate to Google" button and then press "Force re-render" button.

In my application i use the query to retrieve the link to navigate on button click. 

```
const useForceUpdate = () => useState()[1];

const TestFunctionComponent = () => {
    
    const forceUpdate = useForceUpdate()
    const [executeQuery, { called, loading, data }] = useLazyQuery(MY_QUERY);

    if (called && !loading) {
        window.open(data .navigationLink, '_blank')
    }

    const handleOpenAnalysisFormPdf = () => {
        return executeQuery({
            variables: {
                medicalDocumentId: 6089249
            },
        });
    }

    return (
        <Fragment>
            <Button variant="outlined" onClick={handleOpenAnalysisFormPdf}>
                {"Navigate to Google"}
            </Button>
            <Button variant="outlined" onClick={forceUpdate}>
                {"Force re-render"}
            </Button>
        </Fragment>
    )
}

export default TestFunctionComponent;
```

Thank you!

**Comment by pontusab** [comment]
I have a similar issue:
 
```
const [getSimilarProjects, { loading, data }] = useLazyQuery(SIMILAR_PROJECTS_QUERY, {
    variables: {
      id: project.id,
    },
  })
```

This one works:
```
 const handleSimilarProjects = useCallback(() => {
    getSimilarProjects()
  }, [getSimilarProjects])
```

This one dosen't:
```
 const handletoggleFollow = useCallback(() => {
    getSimilarProjects()

    toggleFollow({
      variables: {
        id: 123,
      },
      optimisticResponse: {
        __typename: 'Mutation',
        followProject: {
          id,
          ...project,
          followers: {
            ...project.followers,
            totalCount,
          },
          permissions: {
            ...project.permissions,
            isFollower,
          },
          __typename: 'Project',
        },
      },
    })
  }, [getSimilarProjects, toggleFollow, project])
```

but if I use each mutation separate they work.

**Comment by alexandra1331** [comment]
@pontusab This is not really my case, my problem is that after the first execution of the query was done successfully and this line `window.open(data .navigationLink, '_blank')` is executed, on any other action executed on this screen that triggers a re-render, that `windows.open` command is triggered again and again because `called ` parameter from my if statement is never false.

**Comment by kgregory** [comment]
>So, i'm using the "called" parameter alongside "loading" to check if my "Navigate to Google" button was pressed and the query was executed successfully to continue executing my desired action (in this case navigate to www.google.com).

If you provide an `onCompleted` callback to `useLazyQuery` if will be executed once your query completes successfully.  See docs for [options](https://www.apollographql.com/docs/react/api/react-hooks/#options-1).

**Comment by watchinharrison** [comment]
> > So, i'm using the "called" parameter alongside "loading" to check if my "Navigate to Google" button was pressed and the query was executed successfully to continue executing my desired action (in this case navigate to [www.google.com](http://www.google.com)).
> 
> If you provide an `onCompleted` callback to `useLazyQuery` if will be executed once your query completes successfully. See docs for [options](https://www.apollographql.com/docs/react/api/react-hooks/#options-1).

I don't think this fixes the underlying issue. Unless the `called` can be reset to false via an exposed method or setter, it's set once a single query is made, regardless of it's response.

My use case is to authenticate an input against a graphql endpoint, on "Submit" I invoke the query via `useLazyQuery`, check if the response is successful and then navigate away or show an error. It would be good to be able to set `called` to false until it's next called via `useLazyQuery`.

**Comment by edufschmidt** [comment]
I too have encountered this very same issue. The `called` attribute is not reset on re-render. A workaround I've found that might be useful considering your scenario is to use `useQuery` with the `skip` parameter set to `true`, in conjunction with the `useEffect` hook to control what to do on a re-render. This way you can still call the `refetch()` method, and the behavior will be similar to the one expected from a lazy query.

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!

**Comment by dragos-rosca** [comment]
I still get a query call on re-render if I use `useLazyQuery` and the callback function has been called at least once.
I'm using Apollo client "3.3.15" and I have a query that is triggered on a button press. After the button press I get the query in my network log every time I get a re-render.
For a quick fix until this works properly I made a custom hook (that I didn't test thoroughly):
``` javascript
import { useApolloClient } from '@apollo/client'
import { ApolloError } from '@apollo/client/errors'
import { isNil } from 'ramda'
import { useCallback, useState } from 'react'

export const useQueryOnDemand = (query, options = {}) => {
  if (isNil(query)) throw new ApolloError('Missing Query')
  const [queryResult, setQueryResult] = useState()
  const client = useApolloClient()

  const triggerCall = useCallback(
    (overrideOptions = {}) => {
      client
        .query({ query, ...options, ...overrideOptions })
        .then(result => {
          const onCompleted = overrideOptions.onCompleted ?? options.onCompleted
          if (onCompleted) onCompleted(result?.data)

          setQueryResult(result)
        })
        .catch(err => {
          const onError = overrideOptions.onError ?? options.onError
          if (onError) onError(err)

          setQueryResult(err)
        })
    },
    [client, options, query]
  )

  return [triggerCall, queryResult]
}
```

**Comment by alexandra-c** [comment]
Any news about this? It still doesn't work as expected...

**Comment by Zernach** [comment]
> I too have encountered this very same issue. The `called` attribute is not reset on re-render. A workaround I've found that might be useful considering your scenario is to use `useQuery` with the `skip` parameter set to `true`, in conjunction with the `useEffect` hook to control what to do on a re-render. This way you can still call the `refetch()` method, and the behavior will be similar to the one expected from a lazy query.

Thanks for the idea @edufschmidt —> 🚀🔥
I was successful with the workaround by using `useState` to flicker the `skip` variable on/off for the `lazyQuery`, per your suggestion. I've included my code below:
`"@apollo/client": "^3.6.9"`

```
import { useQuery } from "@apollo/client"
import { useEffect, useState } from "react"

const [isSkip, setIsSkip] = useState(true)
const [hasBeenCalledOnce, setHasBeenCalledOnce] = useState(false)

const {
    loading: feedPostsLoading,
    error: feedPostsError,
    data: feedPostsData,
    refetch: refetchPosts,
    called: feedPostsCalled
} = useQuery(FETCH_FEED_POSTS_QUERY(), {
    skip: isSkip,
})

 const fetchFeedPosts = () => {
    setIsSkip(false)
    hasBeenCalledOnce && refetchPosts()
    setTimeout(() => {
      setIsSkip(true)
      setHasBeenCalledOnce(true)
    }, 1000);
}

useEffect(() => {
    console.log('first time load posts on startup app')
    fetchFeedPosts()
}, [])

const onPressRefreshPosts = () => {
    console.log('refreshing posts!')
    fetchFeedPosts()
}
```
