### ISSUE TITLE
@client fields get blasted if the query fetch policy is cache-and-network

### ISSUE THREAD

**Issue by jdalegonzalez** [apollographql/apollo-client#5184]
**Intended outcome:**

Intent was to have a single query that returned some data from the server and some data that was only in the cache in a single fetch and would return cached data first and then network data.
**Actual outcome:**

The first fetch (the one from cache) would contain network and cached values.  The result from the network would have the cache only values reset to their defaults.
**How to reproduce the issue:**

```
QUERY = gql`
  query MyQuery($id: ID!) {
    serverInfo(id: $id) {
      id
      title
    }
    localData @client
  }
`;
export const Component = (props: IProps) => (
      <Query
        displayName="MyQuery"
        query={QUERY}
        variables={{ id: props.id }}
        fetchPolicy={'cache-and-network'}
      >
    {({ error, loading, data, client, subscribeToMore }) => {
      console.log(data.localData);
      return (
          <div>
          {JSON.stringify(data)}
          </div>
      );
    }}          
</Query>

);

```
**Versions**

**Comment by rdsedmundo** [comment]
I couldn't quite get the "actual outcome" part of your report in `The result from the network would have the cache only values reset to their defaults.`, nor what you meant by "get blasted".

**Comment by jdalegonzalez** [comment]
Sorry about that.  Here's what I mean. 

Imagine that your apolloClient is initialized with something like...

```
...snip
      withClientState({
        defaults: {localData: 'apple'},
        resolvers,
        cache
      }),
```

Now, imagine that at some point later in the code, something like this happens...

```
client.writeData({
      data: { localData: 'pear' }
    });
```

When this component is re-rendered...
```
export const Component = (props: IProps) => (
      <Query
        displayName="MyQuery"
        query={QUERY}
        variables={{ id: props.id }}
        fetchPolicy={'cache-and-network'}
      >
    {({ error, loading, data, client, subscribeToMore }) => {
      console.log(data.localData);
      return (
          <div>
          {JSON.stringify(data)}
          </div>
      );
    }}          
</Query>
);
```

I would expect "localData" to be `pear`.    In fact, it's `apple`  if and only if the fetchPolicy is `cache-and-network`.  Other fetch policies return `pear` as expected.  This appears to be happening because the "forgetChildren" call does not ignore @client data values.

**Comment by hwillson** [comment]
Please open a feature request for this in https://github.com/apollographql/apollo-feature-requests. Thanks!
