### ISSUE TITLE
Apollo hooks package and server endpoint out of date in docs?

### ISSUE THREAD

**Issue by MaxwellGover** [apollographql/apollo-client#5187]
It seems like the codesandbox (https://codesandbox.io/s/n3jykqpxwm) for the query section of the docs is using the hooks beta-11 package. Also the endpoint for the server seems to be wrong. I was able to update it and get it to work but might be worth updating. Thanks!

**Comment by rdsedmundo** [comment]
If the plan is to really maintain those sandboxes always working and up-to-date (which may be a little difficult), I believe it would be better if we used a well-known public GraphQL API, e.g https://graphql.org/swapi-graphql/.

This sandbox is using https://nx9zvp49q7.lp.gql.zone/graphql which seemed to be a wrapper around the Dog CEO API, but this deployment looks very localized at first by looking to its domain.

**Comment by hwillson** [comment]
Please refer to the updated [docs](https://www.apollographql.com/docs/react) for supported examples. Thanks!
