### ISSUE TITLE
Nested fragment spreads with `@client` directive is not removed from query

### ISSUE THREAD

**Issue by adwd** [apollographql/apollo-client#5192]
**Intended outcome:**

Nested fragment spreads with `@client` directive which is not used in query is removed from query.

**Actual outcome:**

Fragment spreads with `@client` directive remains on query.
This violates GraphQL Spec.
https://graphql.github.io/graphql-spec/June2018/#sec-Fragments-Must-Be-Used
> Defined fragments must be used within a document.

As an actual problem, GraphQL server returns 422 error because of this.

**How to reproduce the issue:**

I think this problem is caused by `removeDirectivesFromDocument` function in `apollo-utilities`. Add below test case to `packages/apollo-utilities/src/__tests__/transform.ts` and it fails.
``` js
  it('should remove nested fragment spreads and definitions associated with the removed directive', () => {
    const query = gql`
      query Simple {
        networkField
        field @client {
          ...ClientFragment
        }
      }

      fragment ClientFragment on Thing {
        ...NestedFragment
      }

      fragment NestedFragment on Thing {
        otherField
        bar
      }
    `;

    const expected = gql`
      query Simple {
        networkField
      }
    `;

    const doc = removeDirectivesFromDocument(
      [{ name: 'client', remove: true }],
      query,
    );
    expect(print(doc)).toBe(print(expected));
  });
```

test result
```sh
Summary of all failing tests
 FAIL  packages/apollo-utilities/src/__tests__/transform.ts
  ● removeDirectivesFromDocument › should remove nested fragment spreads and definitions associated with the removed directive

    expect(received).toBe(expected) // Object.is equality

    - Expected
    + Received

      query Simple {
        networkField
      }

    + fragment NestedFragment on Thing {
    +   otherField
    +   bar
    + }
    +

      222 |       query,
      223 |     );
    > 224 |     expect(print(doc)).toBe(print(expected));
          |                        ^
      225 |   });
      226 |
      227 |   it('should not remove fragment spreads and definitions used without the removed directive', () => {

      at Object.<anonymous> (src/__tests__/transform.ts:224:24)
```
**Versions**

  System:
    OS: macOS 10.14.6
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 63.0.1
    Safari: 12.1.2
  npmPackages:
    apollo-boost: file:packages/apollo-boost => 0.4.4
    apollo-cache: file:packages/apollo-cache => 1.3.2
    apollo-cache-inmemory: file:packages/apollo-cache-inmemory => 1.6.3
    apollo-client: file:packages/apollo-client => 2.6.4
    apollo-utilities: file:packages/apollo-utilities => 1.3.2

**Comment by tpham** [comment]
When will the fix for this issue be ready? It's painful to work around the use of nested fragments with @client directive by placing actual content of those fragments in place. Thanks!

**Comment by dylanwulf** [comment]
For anyone who still needs a fix, I came up with an ApolloLink which should fix the problem:

```js
import { ApolloLink } from 'apollo-link';
import { visit } from 'graphql/language';

const removeUnusedFragmentsLink = new ApolloLink((operation, forward) => {
	const usedFragmentsSet = new Set();
	visit(operation.query, {
		enter: {
			FragmentSpread(node) {
				usedFragmentsSet.add(node.name.value);
			},
		},
	});

	const transformedQuery = visit(operation.query, {
		enter: {
			FragmentDefinition(node) {
				if (!usedFragmentsSet.has(node.name.value)) {
					return null;
				}
				return undefined;
			},
		},
	});

	operation.query = transformedQuery;
	return forward(operation);
});
```
