### ISSUE TITLE
apollo-boost mostly missing from CHANGELOG

### ISSUE THREAD

**Issue by lorensr** [apollographql/apollo-client#5193]
When trying to determine whether it's safe to update the `apollo-boost` package (eg from `0.3.*` to current `0.4.4`), I check this doc, but don't find anything recent about `apollo-boost`:

https://github.com/apollographql/apollo-client/blob/master/CHANGELOG.md

*Note: the below directs to the above*

https://github.com/apollographql/apollo-client/blob/master/packages/apollo-boost/CHANGELOG.md

**Comment by Zhouzi** [comment]
I just identified a bug that was introduced by upgrading apollo-boost from 0.1.22 to 0.1.28 in a web app I am working on. Without a changelog, I can hardly tell what went wrong 😕

**Comment by hwillson** [comment]
Apollo Boost has been removed in `@apollo/client`. For more information see: https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/#apollo-boost
