### ISSUE TITLE
Quick question regarding new hooks

### ISSUE THREAD

**Issue by Firebrand** [apollographql/apollo-client#5194]
Hi guys,

I have a simple question. I need to put the result of useQuery (the contents of "data" once it gets populated) inside of a State var (I'm using React Hooks). How do I do that without getting stuck in an infinite re-render loop?

Cheers.

**Comment by rdsedmundo** [comment]
Something like this should work:
```
... {
   const { data } = useQuery(...);
   const [state, setState] = useState();
  
   useEffect(() => {
     if (data) {
       setState(data);
     }
   }, [data]);
}
```

The second `[data]` argument on the `useEffect` hook ensures that the effect is only going to re-execute if the `data` variable changes.

Even though, honestly I don't see the use case on why you couldn't just use the `data` variable directly.

**Comment by Firebrand** [comment]
@rdsedmundo   Many thanks, man... Using the data variable directly is only useful if you just want to display that data (read-only). The app I'm working on uses a lot of fields, so I need to fetch data from the db and populate those fields. But the **value** for each of those fields is a state var that gets updated whenever the onChange for that field in triggered. Thus, to set the default value of a field, I need to set that state var once the data var is ready.

**Comment by chaunceyau** [comment]
@Firebrand Glad you got this resolved! Feel free to close this issue to clean up the issues log.

**Comment by dylanwulf** [comment]
You should be able to use the `onCompleted` callback function for this
https://www.apollographql.com/docs/react/essentials/queries/#options

**Comment by hwillson** [comment]
Looks like this was answered - thanks!
