### ISSUE TITLE
@apollo/react-testing MockedProvider typescript error

### ISSUE THREAD

**Issue by linchen2chris** [apollographql/apollo-client#5208]
![image](https://user-images.githubusercontent.com/3970087/63318314-b0a25100-c348-11e9-891d-2b83e2ea1915.png)

**Comment by linchen2chris** [comment]
Error:(12, 4) TS2605: JSX element type 'MockedProvider' is not a constructor function for JSX elements.
  Type 'MockedProvider' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.
Error:(12, 4) TS2607: JSX element class does not support attributes because it does not have a 'props' property.

**Comment by matthxc** [comment]
I have the same issue

**Comment by ruranek** [comment]
Same here

**Comment by stjepangolemac** [comment]
Same here. Until this is resolved I'm using it like this `const MockedProviderAny = MockedProvider as any;`, then rendering this any version.

**Comment by linchen2chris** [comment]
after upgrade to 3.1.0, I don't have this error any more. probably I can close this issue, if any of you still have it, you can open a new issue.
