### ISSUE TITLE
Filter-like with json schema

### ISSUE THREAD

**Issue by asfernandes** [apollographql/apollo-client#5228]
graphql-anywhere's `filter` is great when we want to filter based on a fragment, but it would be very valuable to have a filter where we can pass the query, the variables and a json representation of the schema (generated with `apollo client:download-schema`).

Then we can filter excess properties of the variables that are not necessary related to types, but to input types instead.

**Comment by hwillson** [comment]
Please open a feature request for this in https://github.com/apollographql/apollo-feature-requests. Thanks!
