### ISSUE TITLE
Support some form of "local fragments"

### ISSUE THREAD

**Issue by asfernandes** [apollographql/apollo-client#5230]
When fragments are used in a query, codegen writes the TypeScript types for them in they own files.

Sometimes that is not what we want. Sometimes fragments are just local pieces to not repeat code inside the query, but not to be reused external.

It would be good to not write these fragments with they name globally, but just as it were theirs fields directly embedded in the query/mutation.

**Comment by dylanwulf** [comment]
Feature requests should go in the [Feature requests repo](https://github.com/apollographql/apollo-feature-requests).

Alternatively, take a look at the GraphQL Code Generator project: https://graphql-code-generator.com/docs/getting-started/

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-client/issues/5230#issuecomment-524348757, please open a feature request in https://github.com/apollographql/apollo-feature-requests. Thanks!
