### ISSUE TITLE
Network-only query is reading data from cache

### ISSUE THREAD

**Issue by dylanwulf** [apollographql/apollo-client#5232]
**Intended outcome:**
Network-only query should not read its initial data from the cache

**Actual outcome:**
Network-only query (which has not gotten any data yet) is reading data from the cache after a separate query is refetched

**How to reproduce the issue:**
https://codesandbox.io/s/network-only-query-is-reading-from-cache-mo0hl

**Versions**
@apollo/react-components: 3.0.1
@apollo/react-hooks: 3.0.1
apollo-client: 2.6.4
apollo-cache-inmemory: 1.6.3
apollo-link-http: 1.5.15

**Comment by chaunceyau** [comment]
Is there any reason you are querying this "nonexistentField"? I did notice some jumpy behavior when including the nonexistentField (i.e. sometimes an error displayed, sometimes the default cache results). Here's a couple things to note in the mean time.

A. Try using Apollo Dev Tools cache inspection may help better understand what is going. Note that the allFilms and allFilms(is_in: [../]) result in different cache objects.

B. Network-only doesn't mean never hit cache. Rather this is the process =>
1. Start with empty cache
2. Defaults you added with client.writeQuery are added.
3. Query is executed
4. Result is obtained
5. Result written back to cache
6. Return updated data

If you'd like to ignore step 5, in writing the returned data back to the cache, you can consider using no-cache, which will do this exactly.

**Comment by dylanwulf** [comment]
@chaunceyau The only reason I included "nonexistentField" was to force an error on the second query. This problem only happens when there's an error. 
I understand that "network-only" does not mean "never hit cache". My problem is that I fetch a query which results in an error, and then that error is replaced with results even though the query with the error hasn't been refetched.

**Comment by hwillson** [comment]
@dylanwulf I don't think this is still an issue in `@apollo/client`, but let us know otherwise (and sorry for the long delay here, we're cleaning up old issues).
