### ISSUE TITLE
Error: Network error: Invariant Violation: 10 (see https://github.com/apollographql/invariant-packages)

### ISSUE THREAD

**Issue by TheoMer** [apollographql/apollo-client#5236]
**Intended outcome:**
Expected my heroku (production) app to launch, as it has been doing within the last 24 hours, without issue.

**Actual outcome:**
The above mentioned error is issued, but only on my production build. Going to the site address provided in the error does not reveal anything about the issue. How do I address this?

**How to reproduce the issue:**
I have no idea how to reproduce this issue as it just started today, with no major code updates being made on my part in the last 24 hours. There appears to be some relation to the following issue: https://github.com/apollographql/apollo-client/issues/4519

**Versions**
apollo-client: 2.6.3

**Comment by TheoMer** [comment]
Closing as the issue has been resolved.

**Comment by ralphchristianeclipse** [comment]
@TheoMer how did you resolve the issue what is the main cause?

**Comment by djmaze** [comment]
Same problem here. @TheoMer What did you do to resolve this?

**Comment by TheoMer** [comment]
@ralphchristianeclipse @djmaze Working from memory, I think I first did an `npm run build`  and then did an Apollo Invariant command check, running a combination of the following commands (point to the root of your directory), to ascertain what issues the errors were pointing to;

```
1. grep -r InvariantError node_modules/**/bundle.cjs.js   
2. grep -r invariant node_modules/**/bundle.cjs.j
```

**Comment by seniv** [comment]
You can also search "17) :" to find exact error what you need. 17 - number of your error
