### ISSUE TITLE
subscribeToMore return type is Unsubscribe function but is documented as void

### ISSUE THREAD

**Issue by simPod** [apollographql/apollo-client#5245]
From docs:

> subscribeToMore: (options: { document: DocumentNode, variables?: TVariables, updateQuery?: Function, onError?: Function}) => () => void
> A function that sets up a subscription. subscribeToMore returns a function that you can use to unsubscribe.

subscribeToMore returned a function is not documented

**Comment by hwillson** [comment]
This has been fixed in the docs. Thanks!
