### ISSUE TITLE
The cache is not updated correctly for mutation responses using default variables.

### ISSUE THREAD

**Issue by joaquindk** [apollographql/apollo-client#5251]
**Intended outcome:**
I've got a query that reads a list of pages inside a conference from my API and a mutation that adds a page to that list. Given that the list is implemented in my API as a connection, I want to use default variables for the `first` parameter in order to control the size of the lists being returned both in the query and the mutation response. 

So my query and mutation will look as so:

```
query Pages($id: String!, $first: Int = 30) {
  conference(id: $id) {
    id
    pages(first: $first) {
      nodes {
        id
        name
      }
    }
  }
}

```

```
mutation CreatePage($input: CreatePageInput!, $first: Int = 30) {
  createPage(
    input: $input
  ) {
    id
    conference {
      id
      pages(first: $first) {
        nodes {
          id
          name
        }
      }
    }
  }
}
```

Since I'm using this with React, the intended outcome for my application would be for the list of pages to automatically be refreshed on my pages list once the CreatePage mutation fires, and consequently for the Apollo cache to be consistent with this change.

**Actual outcome:**

Both the query and mutation are executed correctly by the server, returning back only the number of elements specified by the `first` default variable, ie. 20, however the Apollo cache isn't updated correctly when the mutation fires. 

After inspecting the cache using the Apollo GraphQl dev tools I noticed that when the query fires, I correctly get a pages entry inside the conference, where the default value for `first` is set: 

![image](https://user-images.githubusercontent.com/6567408/63997060-aaa53080-cafd-11e9-8410-566f38eddaa4.png)

However executing the mutation doesn't update this list in the cache, instead if creates a new list under the same conference entity, where the `first` variable is not defined:

![image](https://user-images.githubusercontent.com/6567408/63997122-db856580-cafd-11e9-9fab-897a981c32b6.png)

As a consequence of this the list of pages connected to the query doesn't get updated on screen.

Naturally this works perfectly if I don't use default variables and either pass in the value explicitly or hardcode it in the mutation.

**Versions**

```
 System:
    OS: macOS 10.14.6
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0.2
    Safari: 12.1.2
  npmPackages:
    apollo-cache-inmemory: ^1.5.1 => 1.5.1 

```

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
