### ISSUE TITLE
React Hooks local resolver ran multiple times when using @client @export

### ISSUE THREAD

**Issue by amosyuen** [apollographql/apollo-client#5262]
**Intended outcome:**
Expect local resolver to be ran once for a single change.

**Actual outcome:**
Local resolver is run multiple times for a change.

**How to reproduce the issue:**
Created example at https://codesandbox.io/embed/react-hooks-playground-ktfcx
If you change the query text box, it will make calls to the local resolver to update the values. Count1 does NOT use @client @export, whereas Count2 is called using @client @export. The count2 resolver is ran 5 times, whereas count1 resolver is ran once on each change.

**Versions**

  System:
    OS: Windows 10
  Binaries:
    Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.267.0

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
