### ISSUE TITLE
@client query still querying server

### ISSUE THREAD

**Issue by olalonde** [apollographql/apollo-client#5264]
I have a simple component like this:

```javascript
import React from 'react';
import { useQuery } from 'react-apollo';
const Footer = () => {
  const res = useQuery(
    gql`
      {
        isLoggedIn @client
      }
    `
  );
  return null;
}
```

For some reason, Apollo seems to hit my GraphQL server with this query despite my `@client` annotation. Is this intended behavior? If so, the documentation might be a bit confusing.

I didn't setup any resolver but I instantiated the client with `cache: new InMemoryCache()`.

**Comment by olalonde** [comment]
Oh, looks like I had to initialize the client state:

```javascript
  const initLocalState = {
    isLoggedIn: false
  };

  client.writeData({ data: initLocalState });
```

Still seems like a bug.

**Comment by dmitry** [comment]
I had similar issue. Without any data inside the cache it always tried to fetch data through the server. Also I found that `null` value doesn't work on the objects, which has nested structure, like:

```
    viewer: {
      __typename: 'User',
    }
```

So if I use an initial value as `viewer: null` it won't work, but with `__typename` it works.

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
