### ISSUE TITLE
How to get a promise from the useQuery hook ?

### ISSUE THREAD

**Issue by gregorybellencontre** [apollographql/apollo-client#5268]
Hello
I am trying to use the `useQuery` hook with `react-select` : `AsyncSelect`, and I need a promise to load options asynchronously.
Is it possible to get a promise with this hook ? 
The only way I found is to trigger a refetch and use the promise, but it's not really good because it doesn't use the cache...

**Comment by chaunceyau** [comment]
If by options, you mean an input similar to the react-select: AsyncSelect documentation.. perhaps useLazyQuery would fit your use case perfect.

useLazyQuery doesn't execute when the component is first rendered as it does with useQuery. useLazyQuery provides a function to execute the query a later time.

Input with Search
```
const LOAD_OPTIONS = gql`
  query ($searchTerm: String!) {
    options (title: $searchTerm) {
      id
      title
    }
  }
`

function OptionsInput() {
  const [ loadOptions, { loading, error, data } ] = useLazyQuery(LOAD_OPTIONS)

  return (
    <input
      placeholder='Search for option'
      onChange={e => loadOptions({ variables: { searchTerm: e.target.value } }) }
      results={data} // find a way to render results
    />
  )

}
```

**Comment by gregorybellencontre** [comment]
Thanks for this, it seems a lot better. I'll try it :)

**Comment by gregorybellencontre** [comment]
I just made a try and it doesn't help for my case actually.

The `AsyncSelect` component is waiting for a promise in the `loadOptions` prop.
When I make a change in the input, this function is triggered and it takes the query data at that time. But it's not accurate because it's the previous data, as request didn't finished running.

It seems I can't wait for the request to end before returning the promise to the `AsyncSelect` component.

My current solution is to use the default `Select` component and handle the async manually.

**Comment by chaunceyau** [comment]
I through together an example on CodeSandbox, take a look and let me know if it fits your use case:

https://codesandbox.io/s/tender-aryabhata-n55q7?fontsize=14

**Comment by gregorybellencontre** [comment]
Yes, that's what I was saying in my comment, I did this finally.
But it doesn't use the `AsyncSelect` component but the default `Select` component.

**Comment by chaunceyau** [comment]
Do you wish to use the async select for a specific reason? I can throw an example using it as well. You'd probably have to use the useLazyQuery hook as the useQuery hook is automatically fired on render, and would not therefor be callable from the async props. Perhaps you could use the async part for mutations to update something in the database when selected.

**Comment by caderitter** [comment]
You could probably make this work using the `onCompleted` option callback that you can provide to `useQuery`, which fires when the query is complete.

**Comment by vamshi9666** [comment]
@caderitter `onCompleetd` is available in `useLazyQuery` ?

**Comment by alexhawkins** [comment]
> @caderitter `onCompleetd` is available in `useLazyQuery` ?

Yes, it works. Here is an example.

```
export default function BuildYourOwnPage() {
  const [ products, setProducts] = useState([]);
  
  const [
    getProducts,
    { called, data, loading, error },
  ] = useLazyQuery(PRODUCT_CATALOG_QUERY, {
    variables: {
      category: 'wine',
    },
    fetchPolicy: 'network-only',
    onCompleted: () => setProducts(get(data?.viewer?.user, 'products.edges'))
  });


  useEffect(() => {
    getProducts();
  }, []);

  return (
      <Container>
        <BreadCrumbs />
        <BuildYourOwnTopNavContainer >
          <BuildYourOwnHeaderTextContainer>
            <BuildYourOwnHeaderText>Build your own 6-Pack</BuildYourOwnHeaderText>
            <ProductResultsCount>{products.length} Results</ProductResultsCount>
          </BuildYourOwnHeaderTextContainer>
          <CategoryTabs getProducts={getProducts}/>
          <Spacer/>
        </BuildYourOwnTopNavContainer>
        {called && loading && <Loading />}
        {!loading && get(data?.viewer?.user, 'products') &&
          <ProductCatalog products={products}/>}
    </Container>
  );
}
```

**Comment by lifeiscontent** [comment]
@hwillson adding the same API interface that `useMutation` has to useLazyQuery might be a nice win for 3.0

**Comment by webdeb** [comment]
Just came across that issue, and just wanted to add my 2ç. it would be really handy to get a promise from the lazyquery call.

**Comment by webdeb** [comment]
`onCompleted` can not solve different scenarios if you have for examples two functions, which are calling different the query

```
const callOne = () => loadData().then(// do this)
const callTwo = () => loadData().then(// do that)
```

It makes sense to use the same query, but you probably want to execute different tasks in every scenario.

**Comment by Jakobo** [comment]
For folks coming across this later who need async/await on `useLazyQuery` you can just use the apollo client directly with the `useApolloClient` hook. The client's `query` method returns a promise per [the docs](https://www.apollographql.com/docs/react/api/apollo-client/). You can then save whatever is needed from the query via react's `useState` hooks.

```js
import { useApolloClient } from "@apollo/client";
import react, {useState} from "react";

const LOAD_OPTIONS = gql`
  query($searchTerm: String!) {
    options(title: $searchTerm) {
      id
      title
    }
  }
`;

function OptionsInput () {
  const client = useApolloClient();
  const [results, setResults] = useState([]);

  return (
    <input
      placeholder="Search for option"
      onChange={async (e) => {
        const { data } = await client.query({
          query: LOAD_OPTIONS,
          variables: { searchTerm: e.target.value },
        });
        setResults(data.options);
      }}
      results={results} // find a way to render results
    />
  );
}
```

**Comment by tyankatsu0105** [comment]
@Jakobo 
Your solution is good for me!!
Thanks for the sharing your knowledge :)

But I don't know why `useLazyQuery` does not support async await.

@hwillson 
Is there plan for supporting async await at `useLazyQuery`?

**Comment by gregorybellencontre** [comment]
Thank you all for these great solutions !

**Comment by emersonhsieh** [comment]
For those using apollo-boost, I had to import `useApolloClient` from `@apollo/react-hooks` for Jakobo's solution to work. Otherwise, great work!

**Comment by Zikoel** [comment]
Any news on that? The solution from @Jakobo can be useful but break a little the code base cleaning and to use the correct function provided by Apollo is more correct in my opinion! Why not provide a returned promise? This is also perfectly compatible with the actual functionality and all scenarios are covered without workaround, more of this Mutation lazy query already provide this feature.

**Comment by martinezguillaume** [comment]
You can follow [this](https://github.com/apollographql/react-apollo/issues/3499#issuecomment-586039082)

For some reason, refetch function return a promise, so the think is to use `const query = useQuery({ skip: true })` (enable `skip` to not call it immediately) and after you can call `const result = await query.refetch()`

Why refetch returns a promise and lazy query doesn't ? Mystery

**Comment by pseuyi** [comment]
in case anyone is looking, here is what is looks like using the `useApolloClient` hook with `AsyncSelect`:
`import React from 'react';
import AsyncSelect from 'react-select/AsyncSelect';

const AsyncSelectInput = () => {
  const fetchOptions = async () => {
    const { data } = await client.query({
      query: QUERY
    });

    return data ? data.map(d => ({value: d, label: d})) : [];
  }

  return (
    <AsyncSelect
      cacheOptions
      defaultOptions
      loadOptions={fetchOptions}
    />
  )
};`

**Comment by luatnd** [comment]
> For folks coming across this later who need async/await on `useLazyQuery` you can just use the apollo client directly with the `useApolloClient` hook. The client's `query` method returns a promise per [the docs](https://www.apollographql.com/docs/react/api/apollo-client/). You can then save whatever is needed from the query via react's `useState` hooks.
> 
> ```js
> import { useApolloClient } from "@apollo/client";
> import react, {useState} from "react";
> 
> const LOAD_OPTIONS = gql`
>   query($searchTerm: String!) {
>     options(title: $searchTerm) {
>       id
>       title
>     }
>   }
> `;
> 
> function OptionsInput () {
>   const client = useApolloClient();
>   const [results, setResults] = useState([]);
> 
>   return (
>     <input
>       placeholder="Search for option"
>       onChange={async (e) => {
>         const { data } = await client.query({
>           query: LOAD_OPTIONS,
>           variables: { searchTerm: e.target.value },
>         });
>         setResults(data.options);
>       }}
>       results={results} // find a way to render results
>     />
>   );
> }
> ```

How can I get error.`extension.code` of this query style?

**Comment by doflo-dfa** [comment]
@luatnd, will the client direct method above interact with the cache or does the user have to make sure they connect this new apollo client to the same cache (ie inMemoryCache ) used elsewhere by the hooks.

**Comment by narayandreamer** [comment]
I saw network tab and it seems to use Cache as defined in Apollo Config

**Comment by ricardo-rp** [comment]
I am honestly very confused as to why `useLazyQuery`'s handler doesn't return a promise. It leads to weird patterns

**Comment by KevinDangVN** [comment]
> I am honestly very confused as to why `useLazyQuery`'s handler doesn't return a promise. It leads to weird patterns

In Ubuntu, `useLazyQuery` return Promise but not in Mac, don't know why we have this magic here

**Comment by martinezguillaume** [comment]
> > I am honestly very confused as to why `useLazyQuery`'s handler doesn't return a promise. It leads to weird patterns
> 
> In Ubuntu, `useLazyQuery` return Promise but not in Mac, don't know why we have this magic here

What ? That doesn’t make any sens

**Comment by andreataglia** [comment]
As a Vue3 user I've created this little composable function in order to have a promisified version of the apollo APIs.

    import { ApolloQueryResult, OperationVariables } from '@apollo/client';
    import { useQuery } from '@vue/apollo-composable';
    import { DocumentParameter, VariablesParameter } from '@vue/apollo-composable/dist/useQuery';
    import { ref } from 'vue';


    // promisification of the apollo query
    export function useApolloQuery<TResult = any, TVariables extends OperationVariables = OperationVariables>(document: DocumentParameter<TResult, TVariables>, variables: () => VariablesParameter<TVariables>) {
      const enableLoginQuery = ref(false);
      const { onResult, loading: queryLoading, onError } = useQuery(
        document, 
        variables,
        () => ({
          enabled: enableLoginQuery.value,
          notifyOnNetworkStatusChange: false
        }));
    
      const apolloQuery = () => new Promise<ApolloQueryResult<TResult>>((resolve, reject) => {
        console.log('calling query apollo');
        enableLoginQuery.value = true;
        onResult(res => {
          if (!res.loading) {
            enableLoginQuery.value = false;
            
            if (!res.data) {
              reject('no data');
            }
            resolve(res);
          }
        });
        onError(err => {
          enableLoginQuery.value = false;
          console.error(err)
          reject(err);
        });
      });
    
      return {
        apolloQuery,
        queryLoading
      };
    }


On a sample query you would use it like this:

    import {useApolloQuery} from '... wherever that is';

    const { apolloQuery } = useApolloQuery(UserQueryDoc, () => ({
      username: form.value.username,
      otherVars: 'other sample var'
    }));
    const res = await apolloQuery();

All fully typed. I use graphql-tools to generate the types.

**Comment by brainkim** [comment]
> In Ubuntu, useLazyQuery return Promise but not in Mac, don't know why we have this magic here


I am mildly certain that this has to do with stale `node_modules` dependencies. If not, I may need to take another day off.

**Comment by hwillson** [comment]
`useLazyQuery` now [returns a promise with the result](https://github.com/apollographql/apollo-client/pull/8875), which should address this issue.

**Comment by jackykwandesign** [comment]
> `useLazyQuery` now [returns a promise with the result](https://github.com/apollographql/apollo-client/pull/8875), which should address this issue.

thanks lord, async/ await Promise is the way how we make our product, not some weird pattern rely on callback
I have been using this wrap for a while, but giveaway the cache ability

```
import { DocumentNode, OperationVariables, useApolloClient } from '@apollo/client';
import { useCallback } from 'react';

  
export function useCustomLazyQuery<TData = any, TVariables = OperationVariables>(query: DocumentNode) {
    const client = useApolloClient();
    return useCallback(
        (variables: TVariables) =>
            client.query<TData, TVariables>({
                query: query,
                variables: variables,
                fetchPolicy:'network-only',
            }),
        [client]
    );
}
```

**Comment by xorinzor** [comment]
@hwillson `useLazyQuery` still seems to work differently from `useMutation`, it's not clear to me how I'd get a promise from it

**Comment by ezeikel** [comment]
@hwillson @xorinzor Yeah, I can't see how to get the Promise from the hook either and the documentation makes no reference to a Promise - https://www.apollographql.com/docs/react/data/queries/#manual-execution-with-uselazyquery

**Comment by ezeikel** [comment]
Actually, ignore me. The function that the hook returns, returns a Promise when called. it's just not stated in the docs.
