### ISSUE TITLE
Possible memory leak in readFragment - InMemoryCache

### ISSUE THREAD

**Issue by n0p8** [apollographql/apollo-client#5269]
**Intended outcome:**
Reading the same fragment multiple times should not increase JS heap memory usage

**Actual outcome:**
JS heap memory keeps increasing and is not released even when Collect garbage is initiated from Chrome dev-tools.

<img width="676" alt="Screenshot 2019-09-03 at 2 41 29 PM" src="https://user-images.githubusercontent.com/2400175/64161809-e15fab80-ce5b-11e9-9f48-65a6bb367911.png">

**How to reproduce the issue:**
Do readFragment in a loop and observe memory. Here is a codesandbox link -
https://codesandbox.io/s/runtime-firefly-gzkfn

**Versions:**
"@apollo/react-hooks": "3.0.1",
    "apollo-boost": "0.4.4",
    "graphql": "14.5.4",
    "graphql-tag": "2.10.1",
    "react": "16.8.6",
    "react-dom": "16.8.6",
    "react-scripts": "3.0.1"

**Comment by carinakoo** [comment]
We are also experiencing this issue, an apparent memory leak when calling `readFragment` repeatedly and observed in memory profiling.

@n0p8 Did you find a workaround or solution?

**Comment by visopsys** [comment]
I think the issue is the `typenameDocumentCache` cache

https://github.com/apollographql/apollo-client/blob/7eaf4132cd2cd6244260777799406aaa03fcf377/packages/apollo-cache-inmemory/src/inMemoryCache.ts#L89

This is a global variable and it does not have any cache eviction function call. No wonder the mem keeps increasing after a while. 

It should be replaced with LRU caching.

**Comment by atondelier** [comment]
Hey,

I've just encountered this issue, starting by digging into a leak in the cached objects by apollo-cache-inmemory.

If you are actually having a leak while you are always fetching the same objects, the issue you have may be a little different than just the fact it's not an LRU cache.

Digging more, I've seen the [`optimism` library in use is expecting stable object references to get values from the `Weakmap`s it uses](https://github.com/benjamn/optimism/blob/6c7f6fae863b4cc73342f096603cd0eb2ff1d4c8/src/key-trie.ts#L35),
while the [`query` objects passed by apollo-client `readFragment` to `read` function are always recreated by calling `getFragmentDoc`](https://github.com/apollographql/apollo-client/blob/f26b98cc8ad859bef4ec74d77fd4245b022cc60d/src/cache/core/cache.ts#L117).

So, my 2 cents: 2 issues
 - LRU cache needed
 - wrong behavior with query objects which are clones but not same references

Corroborating fact: we have this leak only with queries using `readFragment`.

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
