### ISSUE TITLE
Move mockNetworkInterface to separate package

### ISSUE THREAD

**Issue by kamilkisiela** [apollographql/apollo-client#527]
Both UI integration, `react-apollo` and `angular2-apollo`, use [`mockNetworkInterface.ts`](https://github.com/apollostack/apollo-client/blob/master/test/mocks/mockNetworkInterface.ts).

I think there's no point of creating copies of it. Also if there are any changes in `apollo-client` that require to change the mock, our (angular2-apollo) copy stops being up to date and we need to get the new one.

**Comment by kamilkisiela** [comment]
@jbaxleyiii what's your point of view on this? :)

**Comment by jbaxleyiii** [comment]
@kamilkisiela :tada: I'd love that! It could be cool to make n apollo-test-utils for packages and projects using Apollo

**Comment by stubailo** [comment]
Hmm, how will this work with TypeScript? Because that is going to depend on the `NetworkInterface` declaration.

Perhaps this means we should just split the whole network interface into a package, and apollo client can just depend on it?

**Comment by kamilkisiela** [comment]
I sad "create a package" which I would prefer but we can also expose it in ApolloClient like this `import { mockNetworkInterface } from 'apollo-client/test'`

**Comment by jbaxleyiii** [comment]
@stubailo I think one of the possible solutions would be to create a project with a peerDep on apollo-client. This is how react Apollo can use the definitions of the client without directly depending on it

**Comment by stubailo** [comment]
I'd really really like to move away from importing from `apollo-client/*` because that just causes a ton of problems with publishing, npm link, etc.

So perhaps we can make a package `apollo-mock-network-interface` with a peer dep on `apollo-client`?

**Comment by jbaxleyiii** [comment]
@stubailo can we do a generic `apollo-test-utils`?

**Comment by stubailo** [comment]
What else would we put in there? Like general stuff about testing GraphQL clients? I guess since it's a testing package it doesn't matter if it has a ton of junk in it.

**Comment by kamilkisiela** [comment]
@stubailo By `apollo-client/test` I meant the file `src/test.ts` or `src/test/index.ts`.
@jbaxleyiii Yes, we could use `peerDeps`.

I'm not the fan of creating a package that holds only the mocked networkInterface. In my way of thinking it should be something that holds lots of helper functions, mocks etc, even if it would have just one feature for now.

About `apollo-test-utils`, maybe we should keep things specific for client and server separated in two different packages?

Or maybe `apollo-client-tools`? It would contain utils for testing and things that might be helpful in using `ApolloClient`.

**Comment by kamilkisiela** [comment]
Related #917

**Comment by helfer** [comment]
This is now in `apollo-test-utils`
