### ISSUE TITLE
Error Handling docs omits code to set errorPolicy

### ISSUE THREAD

**Issue by aej11a** [apollographql/apollo-client#5272]
The first code sample in the doc here https://www.apollographql.com/docs/react/features/error-handling/ says "You can set errorPolicy on each request like so:", but doesn't actually include code to set the errorPolicy in the hooks example. If the answer is that you don't need errorPolicy with the `error` object, then that intro line should be changed to clarify you only need to set `errorPolicy` without hooks

Document file here https://github.com/apollographql/apollo-client/blob/master/docs/source/features/error-handling.mdx

I would update it myself, but I don't know how to set the errorPolicy, which is what led me to notice this omission 😳

**Comment by chaunceyau** [comment]
I'll go ahead an update this in the docs, but for your purposes I'll give you a brief overview:

The error object is part of the query **result**,  along with the data/error states, etc. The errorPolicy is part of the query **options**, similar to variables/fetchPolicy, etc.

If we don't specify an errorPolicy, Apollo uses the default which is "none". We can either set a errorPolicy on a specific query by defining it in the options object in our hook.

```
const { loading, error, data } = useQuery(
    QUERY_ITEM,
    {
        variables: { id: "randomitemid1" },
        errorPolicy: "ignore"
    }
)
```

or we can set a global default that will override the normal "none" default as so:

const client = new ApolloClient({
  uri: '...graphqlbackendurl',
  defaultOptions: {
    watchQuery: {
      fetchPolicy: 'cache-and-network',
      errorPolicy: 'ignore',
    },
    query: {
      fetchPolicy: 'network-only',
      errorPolicy: 'all',
    }
  }
})

**Comment by aej11a** [comment]
@chaunceyau Thank you for the detailed answered! Really appreciate it.

**Comment by hwillson** [comment]
This has been fixed - thanks!
