### ISSUE TITLE
Nested Query w/ pollInterval doesn't always poll

### ISSUE THREAD

**Issue by rothfels** [apollographql/apollo-client#5281]
**Intended outcome:**

A `Query` component with a `pollInterval` of X seconds renders a child `Query` component with a `pollInterval` of Y seconds, Y > X.

The child should poll every Y seconds.

**Actual outcome:**

The parent component polls every X seconds.

The child component does an initial fetch, but does not poll.

Each time the child `Query` receives new props, `Query.ts#updateQuery` will call `ObservableQuery.ts#startPolling`. This will `clearTimeout` and re-`setTimeout` with Y seconds in `QueryManager.ts#startPollingQuery`. Since X < Y, `clearTimeout` will happen before the inner `Query` can refetch.

**How to reproduce the issue:**

```
<Query pollInterval={6000}>
  <Query {...props} pollInterval={10000}>
    {...}
  </Query>
</Query>
```

**Versions**

```
  System:
    OS: macOS 10.14.6
  Binaries:
    Node: 9.11.1 - ~/.nvm/versions/node/v9.11.1/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v9.11.1/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0.2
    Safari: 12.1.2
  npmPackages:
    apollo-cache-inmemory: ^1.6.2 => 1.6.2 
    apollo-client: ^2.6.4 => 2.6.4 
    apollo-codegen: ^0.20.2 => 0.20.2 
    apollo-link: ^1.2.11 => 1.2.11 
    apollo-link-context: ^1.0.17 => 1.0.17 
    apollo-link-error: ^1.1.10 => 1.1.10 
    apollo-link-http: ^1.5.14 => 1.5.14 
    react-apollo: ^2.5.6 => 2.5.6 
```

**Comment by vilvaathibanpb** [comment]
Can I pick up this issue?

**Comment by rothfels** [comment]
@vilvaathibanpb I'm not touching it

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
