### ISSUE TITLE
Using Subscription as a query with multiple responses (aka a stream response)

### ISSUE THREAD

**Issue by dko-slapdash** [apollographql/apollo-client#5288]
Hi.

Sometimes subscription is used not to run some continuous operations (lasting for seconds or minutes), but to express a concept of "run a query - read its response as a stream". It's like [@defer and @stream](https://blog.apollographql.com/new-features-in-graphql-batch-defer-stream-live-and-subscribe-7585d0c28b07) directives which are not yet implemented.

My questions here are:
1. Is there a way for such "query-like" subscription to use cache at first? I experimented with fetchPolicy, but looks like it cannot force the cache to be used (it can only disable caching).
2. The same question as (1), but in case when the subscription emits multiple results; is there a way to read all those results from the cache instead of doing network operations?

E.g. I may have a subscription endpoint which represents a search operation:
```gql
type Subscription {
  search(q: String!, limit: Int): [Item]!
}
```

When I run this subscription:
```gql
subscription {
  search(q: "something", 50) {  ... }
}
```

I expect it to return the first N items very quickly (e.g. fulltext search), and then, in addition to the returned items, more items may be emitted (like M prefix-search items and K trigram-search items).

In this example, the subscription acts like a query, and the response to this query acts like a stream. Since from apollo-server's point of view, subscription is just an AsyncIterable, it perfectly fits the server-side code (which yields N quick results and then M slower + K slowest results).

What I would ideally want to have is the following hook:
```ts
const { allResponses, loading } = useCachedSubscription(
  'subscription { search(q: "something") {...} }',
);
```

- Here `allResponses` is an array of all responses the subscription emitted since it was started (cumulative); e.g. for search, it would contain 1 element after the fast full-text results arrived, then 2 elements when the slower prefix-based results arrived, and, at last, 3 elements when the slowest trigram-based results arrived.
- Also, if such subscription was already executed before, it could immediately return allResponses with 3 elements from the cache.

**Comment by geekox86** [comment]
Greetings all,

Anybody from Apollo team can answer this question please? Thank you.
