### ISSUE TITLE
Invariant Violation 17

### ISSUE THREAD

**Issue by RIP21** [apollographql/apollo-client#5291]
We have this issue that we detect only on Sentry side. Hence I never encountered it myself during development so I have no idea how to reproduce but here is the error message:

```
Invariant Violation: Invariant Violation: 17 (see https://github.com/apollographql/invariant-packages)
  at new t (/static/js/20.3c6f5529.chunk.js:1:129014)
  at s (/static/js/20.3c6f5529.chunk.js:1:129219)
  at e.getQueryWithPreviousResult (/static/js/20.3c6f5529.chunk.js:1:525535)
  at t.updateQuery (/static/js/20.3c6f5529.chunk.js:1:502730)
  at None (/static/js/20.3c6f5529.chunk.js:1:501301)
```
Additional data that sentry provides are:
```
{
framesToPop: 1
}
```

Any googling around that didn't help me find what can be the cause of that, but I'll be happy if anyone can give me any idea about this one.

The only clue is that it happens when the user leaves the page with one particular Query out to any different route that unmounts component that uses such query. And it always the same one.

**Comment by benjamn** [comment]
What exact versions of the `apollo-*` packages are you using? It's relatively straightforward to track the invariant number given the published bundle, as explained in the [README](https://github.com/apollographql/invariant-packages#error-codes) mentioned in the error message you pasted above.

**Comment by RIP21** [comment]
@benjamn 
```
    "react-apollo": "^3.0.1",
    "@apollo/react-common": "^3.0.1",
    "@apollo/react-components": "^3.0.1",
    "@apollo/react-hoc": "^3.0.1",
    "@apollo/react-hooks": "^3.0.1",
    "@apollo/react-testing": "^3.0.1",
```

This error persists for 2-3 months, so it's there since day 1 we started using Apollo for the piece that causes this Invariant to happen once unmounted.

It's not that straightforward for me to understand what kind of invariant it's (TBH not 100% understand the meaning of the term "invariant") 
I can get it from `bundle.js` that is got generated from Webpack or what?

**Comment by Enigma10** [comment]
@benjamn We are also getting the same sentry

**Comment by Enigma10** [comment]
@benjamn we are also getting the same issue on sentry. 
Apollo client version:
```    "apollo-client": "^2.6.4"  ```

**Comment by yassinebridi** [comment]
this happened to me today, only in production:
"apollo-client": "^2.6.4"

**Comment by OscarYuen** [comment]
Yes, I got those error from sentry that those users are using latest iphone with iOS13

**Comment by shockdesign** [comment]
Hitting the same issue for our iOS users, error reported in Sentry as `Invariant violation: 17` and we're using `"apollo-client": "2.6.4"` as well.

**Comment by MrWook** [comment]
Same problem on multiple devices. The violation 17 means: "ObservableQuery with this id doesn't exist:"

What i found out is that fetchMore queries won't be cancelled and will throw this error.
Ressources
https://github.com/apollographql/apollo-client/issues/4114
https://github.com/apollographql/apollo-feature-requests/issues/107

If you are using fetch more you can catch it with try/catch https://github.com/apollographql/apollo-client/issues/4114#issuecomment-502111099

**Comment by RIP21** [comment]
@MrWook thanks for giving a guess. I think right now I know how it happens and will try to repro and fix this one. It's so annoying it spams a lot of events :(

**Comment by hwillson** [comment]
https://github.com/apollographql/apollo-client/pull/6665 was merged and released to help make tracing errors like this easier. Please try out a more modern version of `@apollo/client`, and let us know if you're still encountering issues. Thanks!

**Comment by jaedb** [comment]
This is relieving to see other users experiencing the same bug. Can anyone calm my nerves on this by confirming whether it crashes the app/component or is it a silent error that does not affect the user? I have had zero luck replicating the issue but it definitely occurs ~daily (reported by Sentry).

**Comment by sandorvasas** [comment]
where the **FUCK** is that file? why do you make it so hard to decipher an error message? it's not even in the repo anymore.
