### ISSUE TITLE
Document apollo-boost limitations

### ISSUE THREAD

**Issue by Toub** [apollographql/apollo-client#5296]
**Actual outcome:**

Current [documentation](https://github.com/apollographql/apollo-client/tree/master/packages/apollo-boost) suggest to choose `apollo-boost` by default:

> The fastest, easiest way to get started with Apollo Client!
> Apollo Boost is a zero-config way to start using Apollo Client. It includes some sensible defaults, such as our recommended InMemoryCache and HttpLink, which come configured for you with our recommended settings.

However, using `apollo-boost` as limitations, like the impossibility to use [hasura](https://github.com/hasura/) subscriptions, due to the lack of websocket support: [Support of websocket link in apollo-boost #3117](https://github.com/apollographql/apollo-client/issues/3117).

Here is the last comment of the issue above : https://github.com/apollographql/apollo-client/issues/3117#issuecomment-389144941

> No, there aren't currently any plans to include apollo-link-ws in apollo-boost. The plan is to keep apollo-boost intentionally focused on covering a lot of use cases, with sensible defaults. It isn't intended to cover every use case. For details outlining how to move away from apollo-boost, see the Apollo Boost migration section of the docs. Thanks!

**Intended outcome:**

What about adding a small section in main README and/or `apollo-boost` README file to help one choosing to use or not to use `apollo-boost` depending of the project requirements.

**Versions**

```bash
npx envinfo@latest --preset apollo --clipboard
```
> npx: installed 1 in 3.41s
> 
>   System:
>     OS: Linux 4.19 Debian GNU/Linux 9 (stretch) 9 (stretch)
>   Binaries:
>     Node: 10.15.3 - /usr/local/bin/node
>     Yarn: 1.13.0 - /usr/local/bin/yarn
>     npm: 6.4.1 - /usr/local/bin/npm
>   npmPackages:
>     apollo-boost: ^0.4.3 => 0.4.4 
>     apollo-link-context: ^1.0.18 => 1.0.18 
>     react-apollo: ^2.5.8 => 2.5.8

**Comment by rsslldnphy** [comment]
Related, but I think it would be really helpful for the docs for `apollo-client` to tell you how to install and use `apollo-client` by itself, and the docs for `apollo-boost` to tell you how to install and use `apollo-boost`. At the moment I haven't found any docs for using`apollo-client` without `apollo-boost`.

**Comment by oscar-corredor** [comment]
> Related, but I think it would be really helpful for the docs for `apollo-client` to tell you how to install and use `apollo-client` by itself, and the docs for `apollo-boost` to tell you how to install and use `apollo-boost`. At the moment I haven't found any docs for using`apollo-client` without `apollo-boost`.

Absolutely, the current state of the apollo documentation is a complete mess. It mixes both apollo-client only concepts with apollo-boost only concepts. For someone new to Apollo who took their advice of using apollo-boost is very frustating to find examples in the documentation that do not work when using apollo-boost. This needs attention.

**Comment by hwillson** [comment]
@oscar-corredor The soon to be launched v3 of Apollo Client removes `apollo-boost` completely, as everything Boost did can now be done with the default `ApolloClient` class. The AC3 docs will no longer mention Boost anywhere, so this will help.
