### ISSUE TITLE
resetStore() doesn't properly resolve a query with both @client and server

### ISSUE THREAD

**Issue by amosyuen** [apollographql/apollo-client#5297]
Intended outcome:
Expect after running `client.resetStore()` that the queries would resolve fine.

Actual outcome:
For queries that mix `@client` and server requests, the server request loads the result correctly at first, but is then replaced by an empty value.

How to reproduce the issue:
Created example at https://codesandbox.io/embed/apollo-server-01fw0?fontsize=14

There is a component `ItemsList` which fetches a simple list of items from the server. Two variants are rendered which use different queries. One with just a server query and one with a client and server query mixed. When you click the button **Reset Store** button, the store will reset. The `SERVER_QUERY` items is always populated. However, the `CLIENT_AND_SERVER_QUERY` will flash briefly to have items populated, but then will flash to an empty array.

Versions

System:
OS: Windows 10
Binaries:
Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
Browsers:
Edge: 44.18362.267.0

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
