### ISSUE TITLE
Subscriptions do not work in client schema

### ISSUE THREAD

**Issue by const86** [apollographql/apollo-client#5322]
I do not know whether subscriptions are actually meant to work on the client at all. Docs do not mention that either way. I can see how subscriptions may be deemed not useful on client.

- Server needs a subscription channel to announce to the client about changes to the data originated from anywhere else but that one client.
- For the client state, nobody outside the client knows about that state. All changes are made to the cache from the client itself and updates are broadcasted over watched queries.
- Now, the same subscriptions transport and language can be used by the server to send transient events that do not immediately sink into the cached state. In a ToDo app, 'todo added' and 'todo edited' are clearly the former sort of subscription. The later would be something like 'todos replicated into the cloud', if for some reason client is interested in that kind of events. So far it works.
- Now we are only one step from pure client side transient events. It can be something like 'scroll todos list to todo:42`. Such event may originate from a client mutation resolver as a part of larger operation on client state and be handled in a UI component. Except it does not work.

**Intended outcome:**
Have a schema:
```graphql
extend type Subscription {
  bar: Int!
}
```
And resolvers:
```typescript
const resolvers = {
  Subscription: {
    bar: {
      async *subscribe() {
        yield { bar: 17 };
        yield { bar: 42 };
      }
    }
  }
};
```
Then use them:
```typescript
const client = new ApolloClient({ link, cache, typeDefs, resolvers });
client.subscribe({
    query: gql`
      subscription bar {
        bar @client
      }
    `
  }).subscribe(console.log);
```
I expect `{ data: { bar: 17 } }` and `{ data: { bar: 42 } }` to be logged.

**Actual outcome:**

Instead I get error like:
```
TypeError: resolve is not a function
    at LocalState.<anonymous> (.../node_modules/apollo-client/bundle.umd.js:1028:49)
    at step (.../node_modules/tslib/tslib.js:133:27)
    at Object.next (.../node_modules/tslib/tslib.js:114:57)
    at .../node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at __awaiter (.../node_modules/tslib/tslib.js:103:16)
    at LocalState.resolveField (.../node_modules/apollo-client/bundle.umd.js:1007:35)
    at LocalState.<anonymous> (.../node_modules/apollo-client/bundle.umd.js:968:35)
    at step (.../node_modules/tslib/tslib.js:133:27)
    at Object.next (.../node_modules/tslib/tslib.js:114:57)
```

**How to reproduce the issue:**

No specific tricks required to reproduce the issue.

**Versions**

```
  System:
    OS: macOS 10.14.6
  Binaries:
    Node: 8.16.0 - /usr/local/opt/node@8/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Safari: 12.1.2
  npmPackages:
    apollo-cache-inmemory: ^1.6.3 => 1.6.3 
    apollo-client: ^2.6.4 => 2.6.4 
    apollo-link: ^1.2.13 => 1.2.13 
```

**Comment by kennethlynne** [comment]
Did you ever figure this out? I'm having the same problem now

**Comment by MrDoomBringer** [comment]
Hey guys,

We currently don't plan to support this behavior, primarily due to performance concerns. It could be a possibility in the future if we ever support passing resolvers to the link chain. I'll take a look into clarifying the documentation on this in https://github.com/apollographql/apollo-client/pull/9944, and for now will be closing this issue. 

Thanks!
Emmanuel, Intern :-)
