### ISSUE TITLE
Update types regarding QueryResult

### ISSUE THREAD

**Issue by amansahil** [apollographql/apollo-client#5327]
**Intended outcome:** No type errors regarding the possible deconstructed value of  data from useQuery

**Actual outcome:**  Deconstructed value of data from useQuery throws type error, even though it exists on the specified type

**How to reproduce the issue:**

Below is a sample of how my code looks like :
```
const GET_USERS = gql`
  query GET_USERS($userid: [String]!) {
    getUsers(userid: $userid) {
      ...possibleFields
    }
  }
`

....

  const {
    data: { getUsers },
    loading,
    error
  } = useQuery<GetUsersData, { userid: [string] }>(GET_USERS, {
    variables: { userid: [userid] }
  })
```

What the type looks like

```
export interface GetUsersData {
  getUsers: GetUsers[]
}
```
Typescript gives me an error of: `Property 'getUsers' does not exist on type 'GetUsersData | undefined'`.

**Versions**

```
  System:
    OS: macOS 10.14.4

  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm

  Browsers:
    Chrome: 76.0.3809.132
    Safari: 12.1

  npmPackages:
    apollo-cache-inmemory: ^1.6.2 => 1.6.3 
    apollo-cache-persist: ^0.1.1 => 0.1.1 
    apollo-client: ^2.6.3 => 2.6.4 
    apollo-link-context: ^1.0.18 => 1.0.18 
    apollo-link-http: ^1.5.15 => 1.5.15 
```

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
