### ISSUE TITLE
Client resolvers IE10 break app: Uncaught (in promise)Error: Network error: Object doesn't support property or method 'of'

### ISSUE THREAD

**Issue by Rachnerd** [apollographql/apollo-client#5329]
**Intended outcome:**
Manage local state with client directives and local resolvers.

**Actual outcome:**
IE10 throws an error that seems unrelated to the usual polyfill related errors.

`Uncaught (in promise)Error: Network error: Object doesn't support property or method 'of'`

**How to reproduce the issue:**
The following steps are taken in: https://github.com/Rachnerd/apollo-client-ie10-issue
- `npx create-react-app apollo-client-ie10-issue`
- Configure react app so it supports IE10 by adding IE10 + IE11 to browserlist in `package.json` and add a polyfill cdn.
- Follow getting started chapter of Apollo client to setup the dependencies: `npm install apollo-boost @apollo/react-hooks graphql`
- Perform the query from the Apollo docs (IE10 still works)
- Add a query annotated with `@client` and write a corresponding client resolver. (IE10 breaks)
- Test app in browsers via Browserstack

Chrome: Works as expected
IE11: Works as expected
IE10: Throws an error.

**Versions**
Project that reproduces the issue:
```
  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
  Binaries:
    Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
  Browsers:
    Chrome: 75.0.3770.80
    Firefox: 68.0.1
  npmPackages:
    apollo-boost: ^0.4.4 => 0.4.4 
```

Actual project with the same issue:
```

  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
  Binaries:
    Node: 10.8.0 - ~/.nvm/versions/node/v10.8.0/bin/node
    Yarn: 1.9.4 - ~/.nvm/versions/node/v10.8.0/bin/yarn
    npm: 6.2.0 - ~/.nvm/versions/node/v10.8.0/bin/npm
  Browsers:
    Chrome: 75.0.3770.80
    Firefox: 68.0.1
  npmPackages:
    apollo-cache-inmemory: ~1.6.3 => 1.6.3 
    apollo-client: ~2.6.4 => 2.6.4 
    apollo-link-http: ~1.5.15 => 1.5.16 
    apollo-server: ~2.9.3 => 2.9.3 
    apollo-server-express: ~2.9.3 => 2.9.3 
    react-apollo: ~3.1.0 => 3.1.0 
  npmGlobalPackages:
    apollo: 1.9.2

```

All pages of our company's application work fine except for the one that uses local state as described above. We want to go to production next month, but we can't without a working IE10 version. Before we hack around a key feature of Apollo we would like to validate if this is fixable :).

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
