### ISSUE TITLE
Documentation Error: The URI for the codesandbox in essentials/queries is invalid

### ISSUE THREAD

**Issue by mvorisek7** [apollographql/apollo-client#5330]
Path: docs/source/essentials/queries.mdx

As I was going through this part of the queries documentation, I used the sandbox provided to follow along and noticed that the URI for the api doesn't seem to be valid anymore as I see an error stating, "Network error: Failed to fetch". Issue applies to both the initial sandbox and the completed as well. ([Initial Sandbox](https://codesandbox.io/s/j2ly83749w) & [Completed Sandbox](https://codesandbox.io/s/n3jykqpxwm))

I was able to fix it for myself by opening the [database sandbox](https://codesandbox.io/s/32ypr38l61) and using the API URI there.

**Comment by hwillson** [comment]
This was fixed - thanks!
