### ISSUE TITLE
Apollo client does not handle cookies in nodejs for both HTTP and Websocket connection

### ISSUE THREAD

**Issue by logeekal** [apollographql/apollo-client#5346]
Before I explain my issue, I would like see if my assumption for creating this issues is correct. I have been researching for 2-3 days but I am not able to get a clear answer.

**Intended outcome:**

I almost done with my graphql server and would like to preform automated tests on server itself  for queries, mutations and subscriptions. For testing queries I was able to use supertest  and it work absolutely fine for that. but since It does not have Websockets functionality I turned to Apollo client ot do my testing in nodejs and not in BROWSER :

I had 2 expectations from Apollo Client on nodejs.

1. It can retain cookies so I can login and logout test clients if include credentials: include

2. It can automatically upgrade connection to Websocket for subscriptions and can passing headers with cookies to websocket request.

Please note that my app's auth is based on cookies session and not on auth tokens.

To achieve that I created a composite link 
```

const wsEndpoint = 'ws://localhost:3001/graphql';

const httpEndPoint = 'http://localhost:3001/gql'

const subClient = new SubscriptionClient(wsEndpoint,{
    timeout: 20000,
    lazy: true,
    reconnect: true
},ws)

let wsLink = new WebSocketLink({
    uri: wsEndpoint,
    options: {
        reconnect: true,
        connectionCallback: (err, result) => {
            if(err){
                console.log(`Error connecting to Websocket ${JSON.stringify(err)}`);
            }else{
                console.log(`Connected to WebSocket :  ${result}`);
            }
        }
    },
    webSocketImpl: ws,
    
});

wsLink = new WebSocketLink(subClient);

const httpLink = new HttpLink({
    uri: httpEndPoint,
    credentials: 'include',
    fetch: fetch,
    fetchOptions: {
        credentials: 'include'
    },
});



const link = split(
    ({ query }) => {
        const def = getMainDefinition(query);
        return (def.kind === 'OperationDefinition' && def.operation == 'subscription');
    },
    wsLink,
    httpLink
);

let token = '';




const AuthLink = new ApolloLink((operation, forward) => {
    console.log(`Starting with Operations ${operation.operationName}`);
    console.log(JSON.stringify(operation));
   
    console.log(wsLink.request(operation))

    operation.setContext((context)=>{
        console.log(context);
        return {
                    headers: {
                        ...context.headers,
                        Cookie: token,
                    }
                }
    });
    const subscription =  forward(operation)
    console.log(`subscription is :  ${JSON.stringify(subscription)}`);
    subscription.subscribe({
        next: (result) => {
            console.log('In next');
            console.log(result);
            console.log(operation)
            let context = operation.getContext();
            if(context.response.headers){
                let headers = context.response.headers;
                if(headers.get('set-cookie')){
                    let token1 = headers.get("set-cookie").split(',')[0].split(';')[0]
                    let token2 = headers.get("set-cookie").split(',')[1].split(';')[0]
                    token = `${token1}; ${token2}`;
                    console.log(token);
                }
                
            }
            
        },
        error: err =>  console.error(err),
        complete: ()=> console.log(`Operation completed`)
    });
    return subscription;
});

const client = AuthLink.concat(link);

module.exports = client;
```
**Actual outcome:**

I am not successful in any of the 2 expectation above. Please allow me to explain for each point:

1. It can retain cookies so I can login and logout test clients if include credentials: include

* It is not retaining cookies just by credentials include. That I wrote middleware link called AuthLink to manipulate response header and extract set-cookie and put that back in request headers. So that problem has been resolved by this dirty trick but Apollo Client should work just fine.

* Server CORS setup is correct as I testing login/logout and other auth queries and mutation with supertest and they are working just fine with cookies.

2. It can automatically upgrade connection to Websocket for subscriptions and can passing headers with cookies to websocket request.

* Now this is a problem I am not able to solve. My auth Link is not modified the headers of websocket request. I think Apollo client should transfer the modified http headers to websocket headers during upgrade request.

**How to reproduce the issue:**

If we make any execute request of subscription using above Websocket header will not have cookie.

**Versions**

  System:
    OS: Windows 10
  Binaries:
    Node: 10.15.1 - C:\Jatin\Softwares\node\node.EXE
    Yarn: 1.17.3 - C:\Jatin\Softwares\node\yarn.CMD
    npm: 6.4.1 - C:\Jatin\Softwares\node\npm.CMD
  Browsers:
    Edge: 41.16299.1004.0
  npmPackages:
    apollo-cache-inmemory: ^1.6.3 => 1.6.3
    apollo-client: ^2.6.4 => 2.6.4
    apollo-datasource: ^0.6.1 => 0.6.1
    apollo-link-context: ^1.0.19 => 1.0.19
    apollo-link-http: ^1.5.16 => 1.5.16
    apollo-link-ws: ^1.0.19 => 1.0.19
    apollo-server: ^2.9.0 => 2.9.0
    apollo-server-express: ^2.9.0 => 2.9.0
    apollo-utilities: ^1.3.2 => 1.3.2

**Comment by remoove** [comment]
Try to create new  websocket implementation class, like this:
```
 class WebSocketImplementation extends WebSocket{
      constructor(address, protocols, options = {}) {
        options.headers = { cookie: `cookie`}
        super(address, protocols, options);
      }
    }
```
Then pass this class to WsLink constructor as webSocketImpl option.

**Comment by hwillson** [comment]
https://github.com/apollographql/apollo-client/issues/5346#issuecomment-726742623 should help - thanks!
