### ISSUE TITLE
Preventing client.link from being publicly mutatable 

### ISSUE THREAD

**Issue by ismail-syed** [apollographql/apollo-client#5347]
### Context

We built some [abstractions](https://github.com/Shopify/quilt/blob/master/packages/react-graphql-universal-provider/src/GraphQLUniversalProvider.tsx#L24) on top of apollo links and noticed that mutating `client.link` property on an instance of `ApolloClient`  does not actually propagate the link changes properly to the  [queryManager](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/ApolloClient.ts#L223). 

If this isn't how the `client.links` API is meant to be used, should we consider updating the `client.link` property to be a read-only property similar to the [queryManager](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/ApolloClient.ts#L68). This would help prevent folks from incorrectly using the API. Happy to PR if this is something you're interested in!

**Intended outcome:**

* If mutating `client.link` the new links added should work. 

**Actual outcome:**

* If mutating `client.link` the new links added do not work. 

**How to reproduce the issue:**

* https://github.com/ismail-syed/react-apollo-error-template/commit/b6d1101061e561c4c06e07f5bc9c0cd8c726e615

**Versions**

```
$ npx envinfo@latest --preset apollo --clipboard                                                                                                                                                                                      130 ↵
npx: installed 1 in 1.705s

  System:
    OS: macOS 10.14.4
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 66.0.5
    Safari: 12.1
  npmPackages:
    apollo-cache-inmemory: ^1.6.3 => 1.6.3
    apollo-client: ^2.6.4 => 2.6.4
    apollo-link: ^1.2.12 => 1.2.12
```

**Comment by hwillson** [comment]
Changes to allow this were introduced in https://github.com/apollographql/apollo-client/pull/6193 - thanks!
