### ISSUE TITLE
InMemoryCache  Shows String of JSON

### ISSUE THREAD

**Issue by josnin** [apollographql/apollo-client#5358]
Need help or want to talk all things Apollo Client? Issues here are reserved for bugs, but one of the following resources should help:

* Apollo Spectrum community: https://spectrum.chat/apollo
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests

![image](https://user-images.githubusercontent.com/3206118/65438601-540ae800-de58-11e9-8c5c-ffc855bc2b93.png)

**Comment by benjamn** [comment]
The handling of scalar JSON values is changing in Apollo Client 3.0, but this screenshot is working as designed for Apollo Client 2.x.

**Comment by josnin** [comment]
Thanks @benjamn
