### ISSUE TITLE
Documentation error: React docs for Graphql-query-data-error crashes

### ISSUE THREAD

**Issue by Siggnja** [apollographql/apollo-client#5361]
**Intended outcome:**
When opening this url: https://www.apollographql.com/docs/react/api/react-apollo/#graphql-query-data-error I expect the site to be rendered so that I can view the documentation.

**Actual outcome:**
When opening: https://www.apollographql.com/docs/react/api/react-apollo/#graphql-query-data-error I get a white screen with this error in the console:
![image](https://user-images.githubusercontent.com/16036230/65496742-8d6b4400-dea8-11e9-9f62-d4a9a771b421.png)

**How to reproduce the issue:**
Open the url.
Tested on macOs Mojave 10.14.5
Chrome version 77
Safari version 12.1.1
It looks like this section does not exist anymore. Nevertheless, the site should not crash when trying to access a section that does not exist.

**Versions**
Not applicable

**Comment by IanVS** [comment]
This seems to be resolved, at least for me.  The page opens to the top of the react-apollo docs.

**Comment by Siggnja** [comment]
I'll close this, this just returns 404..
