### ISSUE TITLE
Apollo Boost incompatible with TypeScript 3.6

### ISSUE THREAD

**Issue by hippostar** [apollographql/apollo-client#5367]
TypeScript 3.6 removed the GlobalFetch object definition which is still used in packages/apollo-boost/src/index.ts

Observed behavior: Compiling prints this error: **TS2304: Cannot find name 'GlobalFetch'**
Excepted behavior: No compilation errors.

Someone had a pull request but it didn't get merged, this should be easy to fix.
https://github.com/apollographql/apollo-client/pull/5359

Other related issues https://github.com/apollographql/apollo-link/issues/1094

**Comment by abdonrd** [comment]
Ops! Reopened at https://github.com/apollographql/apollo-client/pull/5373!
