### ISSUE TITLE
Errors thrown from 'update' callback of useMutation doesn't handle by 'onError' callback

### ISSUE THREAD

**Issue by ouyuran** [apollographql/apollo-client#5378]
Here is my code:
```
...
const [person] = useMutation(
  UPDATE_PERSON,
  {
    onError: err => {
      //should goes here
    },
    onCompleted: data => {
      //goes here now
    },
    update: (cache) => {
      throw new Error("error");
    }
  }
)
```

**Actual outcome:**
When there is an error thrown in 'update', I think it should goes to 'onError' while currently it goes to 'onCompleted'.

**How to reproduce the issue:**
Check the code.

**Versions**

System:
    OS: Linux 4.15 Debian GNU/Linux 9 (stretch) 9 (stretch)
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  npmPackages:
    apollo-cache-inmemory: ^1.6.3 => 1.6.3
    apollo-client: ^2.6.4 => 2.6.4
    apollo-link-http: ^1.5.16 => 1.5.16
    react-apollo: ^3.1.1 => 3.1.1

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
