### ISSUE TITLE
Mixing Cache Redirects with @client(always: true)

### ISSUE THREAD

**Issue by zcramos** [apollographql/apollo-client#5389]
I spent most of a day scratching my head over this, and I'm beginning to think that what I'm asking for isn't possible. I fetch and cache a set of data when my app first loads, and a few screens later that same data is re-used. Cache redirects seemed like the perfect way to handle that scenario because the data is practically guaranteed to exist locally. Now I have some local-only data that is queried for within the query that goes through my cacheRedirects, but needs a local resolver because it the actual data exists elsewhere in the cache. I've added some queries and configuration options below that exemplify the use case. Is this actually possible? 

### Packages/Environment:
* `react-native`: 0.59.x
* `apollo-client`: 2.6.4
* `apollo-cache`: 1.3.2
* `react-apollo`: 2.5.8

#### Initial Fetch from server
```graphql
query FetchFoosForIds($ids: ids) {
  service {
    fetchFoosForIds(ids: $ids) {
      foos {
        ...fooFields
      }
    }
  }
}

fragment fooFields on Foo {
  id
  bars {
    ...barFields
  }
}

fragment barFields on Bar {
  id
  bazzes @client {                // this data is local-only
    ...bazFields
  }
}

fragment bazFields on Baz {
  id
  data @client(always: true) {    // needs a custom local resolver to fetch from elsewhere in cache
    id
  }
}
```
#### Fetched via cacheRedirect
```graphql
query FoosForId($id: id) {
  foos(id: $id) {
    ...fooFields
  }
}
```
#### Apollo Config
```typescript
const inMemoryCacheConfig = {
  cacheRedirects: {
    Query: {
      foos: (_, { id }, { getCacheKey }) => 
        getCacheKey({ __typename: 'Foo', id}),      // this is consistently called
    }
  }
}

const resolvers = {
  Query: {
    data = (parent, args, ctx, info) => null;       // this is never called
  }
}

**Comment by josnin** [comment]
try below
````javascript
const resolvers = {
  Query: {
    data: () => {
            console.log('test?')
     };     
  }
}````

also i think u need to provide typeDefs

**Comment by zcramos** [comment]
That console log is never executed in my example. I've just been sticking `debugger;` in to check that.

What's the purpose of including typedefs? The [documentation examples](https://www.apollographql.com/docs/react/data/local-state/#handling-client-fields-with-resolvers) describing how to use local resolvers don't include typedefs. The documentation implies that typedefs are only necessary if you want a more pleasant Apoll Dev Tools experience.

**Comment by josnin** [comment]
You are right about the typeDefs

I tried local resolver below and it can trigger the data . i think apollo client need
to know the __typename in order to do the matching w. individual field

Hope this helps

````javascript
      Baz: {
         data: baz  => {
                console.log(baz, "trigger?")
                return false
        }
      },
      Query: {
        baz: () => {
            return {
                id: 2,
                __typename: "Baz"
                }
        },

````
![image](https://user-images.githubusercontent.com/3206118/65960963-2e996200-e488-11e9-9707-042145862dc1.png)

**Comment by zcramos** [comment]
@josnin To make your example reflect my use case, `Baz` should not be a locally resolved value - it is accessed via a `cacheRedirect`. A `Baz` is queried as nested data from a service and stored, normalized, in the apollo cache. Then a cacheRedirect instructs apollo to check the cache for a `Baz` with the cache key `Baz:2`. The fetched `Baz` does not have a field `data`, but with the `@client(always: true)` annotation, I would expect the Baz to be returned and for Apollo to subsequently attempt to fetch the `data` field of `Baz` using the local resolver.

I've reworked my data model to avoid nesting an `@client`-resolved field inside a `cacheRedirect`-resolved field, so this isn't blocking my work anymore. However, it seems like a valid use case that should be supported if possible.
