### ISSUE TITLE
`previousQueryResult` optional typing

### ISSUE THREAD

**Issue by WillSquire** [apollographql/apollo-client#5393]
`previousQueryResult` can return undefined in `fetchMore`'s `updateQuery`, but the typing is non-optional. The current typing is:
```
updateQuery: (previousQueryResult: TData, options: {
        fetchMoreResult?: TData;
        variables?: TVariables;
    }) => TData;
```

However, `previousQueryResult?: TData` might be more appropriate?

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
