### ISSUE TITLE
All @export directives should be run first

### ISSUE THREAD

**Issue by KamranAsif** [apollographql/apollo-client#5394]
**Intended outcome:**

For the given query: 
```
query reviewerPostCount($reviewerId: Int!, $fullName: String!) {
  primaryReviewerId @client @export(as: "reviewerId")
  reviewerFullName($reviewerId) @client @export(as: "fullName")
  postCount(fullName: $fullName)
}
```
Assume `primaryReviewerId` and `reviewerFullName` are both implemented using local resolvers.

I expect `primaryReviewerId` to be called and resolved, then `reviewerFullName` to be called and resolved, and then postCount to be called with the fullName value.

**Actual outcome:**

`primaryReviewerId` is called and resolved
`reviewerFullName` is called with undefined value
The query is sent to the backend with undefined value.

**Comment by huynhtastic** [comment]
If I'm reading this page correctly, fields are resolved in whatever order seems optimal, so these fields must not affect each other, which may be why you are getting an `undefined` for reviewerFullName:

>... the resolution of fields other than top‐level mutation fields must always be side effect‐free and idempotent, the execution order must not affect the result, and hence the server has the freedom to execute the field entries in whatever order it deems optimal.

https://www.apollographql.com/docs/react/data/local-state/

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
