### ISSUE TITLE
Apollo-Boost README: Broken link to "Configuration Options"

### ISSUE THREAD

**Issue by ecbrodie** [apollographql/apollo-client#5395]
There is a broken link in the [README for apollo-boost](https://github.com/apollographql/apollo-client/tree/master/packages/apollo-boost#whats-in-apollo-boost). The link to "Configuration Options" points to https://www.apollographql.com/docs/react/essentials/get-started.html#configuration-options, but this is a 404. I would normally just fix this myself and submit a PR, but unfortunately I do not know what the correct link is.

Thank you for fixing.

**Comment by anachronic** [comment]
Could [this](https://www.apollographql.com/docs/react/get-started/#configuration-options) be what we're looking for?

**Comment by hwillson** [comment]
The docs have been updated - thanks!
