### ISSUE TITLE
useMutation update，the cache changed，but UI not change

### ISSUE THREAD

**Issue by onek12** [apollographql/apollo-client#5402]
I useMutation to send message ,but the message list  in chat window not change. I found that the cache has changed . Please help , I can't understand.

![image](https://user-images.githubusercontent.com/50606975/66089083-5683e500-e5b0-11e9-9cd5-4cc50dd8a094.png)

and  the cache has changed
![image](https://user-images.githubusercontent.com/50606975/66087764-330a6b80-e5ab-11e9-84c8-115811199374.png)

The useQuery  not work .   UI  have no  change :（

But~! When I  put them in one  js file. it works.... why???

**Comment by aryzing** [comment]
From the [docs](https://www.apollographql.com/docs/react/caching/cache-interaction/#gatsby-focus-wrapper),

> Important: You should call these methods on your app's ApolloClient object, not directly on the cache. By doing so, the ApolloClient object broadcasts cache changes to your entire app, which enables automatic UI updates. If you call these methods directly on the cache instead, changes are not broadcast.

In any case, this seems like a question and should probably go to Stackoverflow.

**Comment by onek12** [comment]
> 从[文档中](https://www.apollographql.com/docs/react/caching/cache-interaction/#gatsby-focus-wrapper)，
> 
> > 重要提示：您应该在应用程序的ApolloClient对象上而不是直接在缓存上调用这些方法。这样，ApolloClient对象会将缓存更改广播到整个应用程序，从而启用自动UI更新。如果直接在缓存上调用这些方法，则不会广播更改。
> 
> 无论如何，这似乎是一个问题，可能应该转到Stackoverflow。

I tried use apollo client , but result is the same ,  message list not change.. cache changed .

![bug](https://user-images.githubusercontent.com/50606975/66213249-f006e000-e6f1-11e9-9dc6-691a5764a929.png)

What makes me wonder is why the components don't work.It works just fine in one file? (Machine translated ：）

**Comment by onek12** [comment]
![lastmesassg](https://user-images.githubusercontent.com/50606975/66213512-8804c980-e6f2-11e9-9bf1-d363e4cf8bce.png)

**Comment by cbergmiller** [comment]
The problem  most likely is the state mutation:
```javascript
chat.messages.push(addMessage)
```
Should rather use `concat` or `[...chat, addMessage]`

**Comment by hwillson** [comment]
https://github.com/apollographql/apollo-client/issues/5402#issuecomment-567560035 sounds likely - thanks!
