### ISSUE TITLE
Resolving response data into Sanctuary.js Maybe Type

### ISSUE THREAD

**Issue by abdul-takt** [apollographql/apollo-client#5408]
I have built a custom resolver that uses the graphql.js `visit` and `TypeInfo` utilities to create resolvers that resolve nullable types into Maybe types using [Sanctuary.js](https://sanctuary.js.org/#maybe-type)

What's happening is that when I run the resolver function the output works as expected within the ApolloLink afterware, but when observing the output of `client.query (...)` data is always `null`

Example:
```graphql
type User {
  id: ID!
  email: String!
  name: String!
  image: String
}

type Query {
  me: User
}

# client query
query {
  me {
    id
    email
    image
  }
}
```
The network response can be the following:
```JSON
{
  "data": {
     "me": {
       "id": "1234abcd",
       "email": "test@test.com",
       "image": "https://www.placholder.com/100x100"
     }
  }
}
```
or
```JSON
{
  "data": {
     "me": {
       "id": "1234abcd",
       "email": "test@test.com",
       "image": null
     }
  }
}
```
resolver output using ApolloLink Afterware would be the following:
```javascript
const resolveToSanctuary = new ApolloLink((operation, forward) => {
  return forward(operation).map(response => {
    if (response.data.me) {
      response.data.me = resolverFunction (response.data.me) // output below
    }
    return response;
  });
});

// resolver turns
{
  data: {
    id: "1234abcd",
    email: "test@test.com",
    image: "http://www.placeholder.com/100x100"
  }
}

// INTO

{
  data: {
    me: S.Just ({ id: "1234abcd", email: "test@test.com", image: S.Just ("http://placeholder.com/100x100") })
  }
}

// OR

{
  data: {
    id: "1234abcd",
    email: "test@test.com",
    image: null
  }
}

// INTO

{
  data: {
    me: S.Just ({ id: "1234abcd", email: "test@test.com", image: S.Nothing })
  }
}
```
note: both `me` and `image` return nullable types

When logging `response` inside the custom `ApolloLink afterware` the data looks great, but the problem is when logging the value of `data` after invoking the query or mutation, data is null.  I also get these warnings:

<img width="358" alt="Screen Shot 2019-10-03 at 3 12 55 PM" src="https://user-images.githubusercontent.com/35937223/66167872-50adf400-e5f0-11e9-93ae-b797b6598cdf.png">

The `Maybe` type in `Sanctuary.js` is actually a Javascript Object with a `MaybeType` constructor.

See:

https://github.com/sanctuary-js/sanctuary-def#unarytype--foldablef--string---string---arraytype---any-boolean---ta-fa---type---type

If I were to console.log it or serialize the data use JSON.stringify and then parse it back to JS it would lose access to the original prototypes and look something like this:

```javascript
{
  data: {
    me: {
     value: {
        id: '1234abdc'
        email: 'test@test.com'
        image: {  value: 'http://placeholder.com/100x100' }
    }
  }
}
```

So it seems that the JSON output of the response after passing it through the resolver doesn't match the query structure defined in GraphQL and therefore Apollo-client returns null.  Is there a way to override this or bypass this functionality in Apollo client?  Am I doing something incorrectly with the afterware defined above (of course my resolver function is more complex and can handle any query/mutation)?

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
