### ISSUE TITLE
Doc "useLazyQuery" example cause un-limited loop

### ISSUE THREAD

**Issue by maxyou** [apollographql/apollo-client#5410]
**Document:**
https://www.apollographql.com/docs/react/data/queries/

    function DelayedQuery() {
      const [dog, setDog] = useState(null);
      const [getDog, { loading, data }] = useLazyQuery(GET_DOG_PHOTO);
    
      if (loading) return <p>Loading ...</p>;
    
      if (data && data.dog) {
        setDog(data.dog);
      }
    
      return (
        <div>
          {dog && <img src={dog.displayImage} />}
          <button onClick={() => getDog({ variables: { breed: 'bulldog' } })}>
            Click me!
          </button>
        </div>
      );
    }

**Outcome:**
un-limited loop

**Suggestion**

      useEffect(() => {
        if (data && data.hello) {
          setDog(data.hello);
        }
      }, [data]);

not guarantee.

**Comment by DRL9** [comment]
Why not use as follow: 
```jsx
function DelayedDog({ breed }) {
    const [getDog, { data, error, loading }] = useLazyQuery(GET_DOG);
    if (loading) return <p>loading...</p>;
    if (error) return <p>error: {error.message}</p>;
    return (
        <div>
            {data && (
                <img
                    src={data.dog.displayImage}
                    alt={data.dog.breed}
                    style={{ height: 100, width: 100 }}
                />
            )}
            <button onClick={() => getDog({ variables: { breed } })}>
                get
            </button>
        </div>
    );
}
```
Remove other hook (`useState`).

**Comment by hwillson** [comment]
This doesn't sound like an Apollo Client issue, but if anyone thinks it is and can provide a small runnable reproduction using `@apollo/client@latest`, we'll take a look. Thanks!
