### ISSUE TITLE
Caching bug with queries returning subsets of children

### ISSUE THREAD

**Issue by jongold** [apollographql/apollo-client#5413]
Y'all, I'm stumped on this one.

Here's a truncated version of our schema. [Less-truncated version](https://gist.github.com/jongold/fc6af6094622bf6d6d17b246fe7681c3)

```graphql
type Query {
  lastSegment: SegmentType
  curriculum(id: Int): CurriculumType
}

type SegmentType {
  createdAt: DateTime!
  id: ID!
  curriculum: CurriculumType
}

type CurriculumType {
  id: ID!
  title: String!
  exercises: [ExerciseType]
}

type ExerciseType {
  id: ID!
  url: String!
}
```

The app has a couple of `Curriculums` each with a bunch of `Exercises`. There's a `curriculum(id)` query to display a `Curriculum` with every object it contains.

Every day, we also generate a `Segment` for each user, containing the next `Exercises` from their queue. Simplistically, consider the `curriculum(id)` query returns _everything_, and `lastSegment->curriculum` returns the curriculum just with the next `n` incomplete `Exercises` scoped to the user.

The queries work great, other than there's some weird caching stuff going on - for both queries, the `Curriculum` is cached as `CurriculumType:1`. This is, technically, correct - the `Curriculum` is essentially fixed (i.e. we only generate new curriculums as admins - the IDs don't shift per user etc). But this also means that the queries overwrite each other's caches.

```
query CurriculumBrowser {
  curriculum(id: 1) {
    id
    exercises {
      ...Exercise
    }
  }
}

~=

{
  curriculum: {
    id: 1,
    exercises: [
      { id: 1, url: '' },
      { id: 2, url: '' },
      // …
      { id: 998, url: '' },
      { id: 999, url: '' },
    ]
  }
}

=> cached as CurriculumType:1

query Today {
  lastSegment {
    id
    createdAt
    curriculum {
      id
      exercises {
        ...Exercise
      }
    }
  }
}

~=

{
  lastSegment: {
    id: 55
    createdAt: // DateTime
    curriculum: {
      id: 1,
      exercises: [
        { id: 1, url: '' },
        { id: 2, url: '' },
        // filtered list
      ]
    }
  }
}
=> cached as CurriculumType:1
```

so the last-run query overwrites the cache for `CurriculumType:1`, even though they're returning different data. This ends up, e.g. with the `lastSegment` query displaying the _full_ exercise list, unless you rerun the query every time the route is re-entered (using `react-navigation` in an Expo app), or you just don't cache _anything_. which seems silly.

Caching the `Exercises` is fine - there's no user-to-user interaction.

My hunch is that changing the schema like so could fix it, but I don't want to change the schema unless that's definitely the case.

```diff
 type Query {
   lastSegment: SegmentType
   curriculum(id: Int): CurriculumType
 }

 type SegmentType {
   createdAt: DateTime!
   id: ID!
-  curriculum: CurriculumType
+  exercises: [ExerciseType]
 }

 type CurriculumType {
   id: ID!
   title: String!
   exercises: [ExerciseType]
 }
```

I spent the whole day trying to figure out if I could use `dataIdFromObject` or `cacheRedirects` in `InMemoryCache` to create different IDs for the canonical `Curriculums` returned from `curriculum(id)` vs the filtered ones retured for `lastSegment` - something like `Segment-$segmentId/Curriculum-$curriculumId`, but I couldn't figure out how to do it with `dataIdFromObject`

Any other insight before I just disable the cache?

**Versions**
```
  System:
    OS: macOS High Sierra 10.13.4
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.44
    Firefox: 58.0.2
    Safari: 11.1
  npmPackages:
    @apollo/react-hooks: ^3.1.1 => 3.1.1 
    apollo-cache-inmemory: ^1.6.3 => 1.6.3 
    apollo-client: ^2.6.4 => 2.6.4 
    apollo-link-context: ^1.0.19 => 1.0.19 
    apollo-link-error: ^1.1.12 => 1.1.12 
    apollo-link-http: ^1.5.16 => 1.5.16 
  npmGlobalPackages:
    apollo: 2.18.3
```

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
