### ISSUE TITLE
Can't resolve 'react-dom/server' in @apollo/react-ssr

### ISSUE THREAD

**Issue by pbassut** [apollographql/apollo-client#5415]
**Intended outcome:**
I'm trying to use react-server with react-apollo to do SSR.

**Actual outcome:**
I get an error on startup saying ` @apollo/react-ssr` can't resolve `react-dom/server` package. Here's the full stack trace:
```
ERROR in ./node_modules/@apollo/react-ssr/lib/react-ssr.esm.js
Module not found: Error: Can't resolve 'react-dom/server' in '/Users/patrickbassut/Programming/website-ssr/node_modules/@apollo/react-ssr/lib'
 @ ./node_modules/@apollo/react-ssr/lib/react-ssr.esm.js 11:24-51 15:133-160 30:24-51
 @ ./node_modules/react-apollo/lib/react-apollo.esm.js
 @ ./src/client/index.tsx
 @ multi webpack-hot-middleware/client?path=http://localhost:8501/__webpack_hmr ./node_modules/core-js/stable/index.js ./node_modules/regenerator-runtime/runtime.js ./src/client
```

**How to reproduce the issue:**
I think that by only using react-server with apollo on the backend(SSR) would do it. Thought I don't think this is an issue with react-server cause I also tried with other packages and got the exact same error.

I already have `"react-dom": "^16.9.0",` in my package.json `dependencies` section

**Versions**
`npx envinfo@latest --preset apollo --clipboard`
```
npx: installed 1 in 1.69s

  System:
    OS: macOS Mojave 10.14.5
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.44
    Safari: 12.1.1
  npmPackages:
    @apollo/react-ssr: ^3.1.2 => 3.1.2
    apollo-client: ^2.6.4 => 2.6.4
    react-apollo: ^3.1.2 => 3.1.2
```

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
