### ISSUE TITLE
Why we're using ReadOnlyArray here ? It's causing some type casting problems. Can we change to normal Array?

### ISSUE THREAD

**Issue by ozanmanav** [apollographql/apollo-client#5420]
Hi,

Why we're using ReadOnlyArray here ? It's causing some type casting problems. Can we change to normal Array?

It's happening only query not in the mutate.

**How to reproduce the issue:**
 
![image](https://user-images.githubusercontent.com/19241756/66416435-7a0ebb80-ea06-11e9-9426-6295356db405.png)

**Versions**
2.5.1

**Comment by aryzing** [comment]
Why would you mutate the error object?

**Comment by ozanmanav** [comment]
I'm trying to handle in the error helper, like handleGraphqlErrors(errors). How can i do this ?
