### ISSUE TITLE
refetchQueries design error

### ISSUE THREAD

**Issue by hmeerlo** [apollographql/apollo-client#5422]
In my opinion there is an architectural problem with the way refetchQueries works. Let's say I have a component called BookList which shows me a list of books with all their details. And I can add a book to that list on that page. And I have another page where I can select a book from a dropdown. But because this is a dropdown it only needs a few fields. Enter the beauty of GraphQL, I define another query that only fetches the needed fields (booksWithoutDetail).
If I now add abook using a mutation on the first page and set refetchQueries to ["booksWithoutDetail"] then the book is added on the backend, but the query is never refetched because it wasn't being used on the page (i.e. it was not an ObservableQuery). So when I enter another page with a dropdown of books, the new book is not in that list.
refetchQueries has a semantic meaning which is: "I'm executing a mutation and whatever data you have on this given query is not valid anymore, please refetch it when needed". So if it will not refetch the data because it isn't used on that page, it should at least invalidate the cached data.

**Comment by pedro-lb** [comment]
I agree. For now, a possible solution is to simply use `fetchPolicy: 'network-only'` to guarantee that different page queries will be updated, but that's not a great solution since it bypasses the cache.

**Comment by hmeerlo** [comment]
Yes then I might as well disable the cache completely. But considering the way it works now, that might be the best option. It is just too unpredictable right now.

**Comment by dylanwulf** [comment]
The Apollo team is planning on adding the ability to invalidate/garbage collect the cache in apollo-client v3. Hopefully that will help with this issue.
They are planning on having a v3 release candidate ready by the end of October.

**Comment by reykjavikingur** [comment]
This is a bit disappointing, but ultimately not surprising, considering how tricky cache invalidation is in general. The solution may be to allow custom `fetchPolicy` settings as part of the queries listed under `refetchQueries`, for example (hypothetically):
```
client.mutate({
  mutation: UPDATE_THING,
  refetchQueries: [{query: THING, fetchPolicy: "network-only"}]
}
```

**Comment by simplecommerce** [comment]
I assume there is no update on this issue yet? I am facing the same problem on my end, I am passing query names as string and only the current mounted component queries are executed but not the unmounted ones.

**Comment by hwillson** [comment]
Regarding https://github.com/apollographql/apollo-client/issues/5422#issuecomment-542283373, we did - see https://www.apollographql.com/docs/react/caching/garbage-collection/ for details. Thanks!
