### ISSUE TITLE
client.resetStore() never ends because observable during refetch

### ISSUE THREAD

**Issue by seeden** [apollographql/apollo-client#5435]
I am doing await client.resetStore() after logout.
This function never ends.
It will clear cache and after that it call refetchQueries which is all right.
It will download data from server without error but few observers never ends.

https://github.com/apollographql/apollo-client/blob/65eef3730e8b3d2b66ca0fe6d88d0b579a4d31ea/packages/apollo-client/src/core/QueryManager.ts#L1219

observable.map will never execute body of the function
and error/complete are not executed as well. (https://github.com/apollographql/apollo-client/blob/65eef3730e8b3d2b66ca0fe6d88d0b579a4d31ea/packages/apollo-client/src/core/QueryManager.ts#L1267)

I see this issue in latest version but it is in apollo for more than half of the year.

**Comment by seeden** [comment]
This issue is related to react-apollo-hooks. I have started to use @apollo/react-hooks and everything is working fine now

**Comment by macrozone** [comment]
@seeden actually this happens also on @apollo/react-hooks

be careful, resetStore is really broken in apollo < 3.0.0
