### ISSUE TITLE
Link of the final app in the docs

### ISSUE THREAD

**Issue by nemanjam** [apollographql/apollo-client#5439]
**Intended outcome:**

>  If you'd like to skip ahead and see the app we're about to build, you can view it on [CodeSandbox](https://codesandbox.io/s/nn9y2wzyw4).

The link in the docs should link to codesandbox or github repo of the completed app. Docs page is [this](https://www.apollographql.com/docs/react/get-started/).

**Actual outcome:**

Current link links to the empty app boilerplate.

**How to reproduce the issue:**

Look at the docs.

**Versions**

v2.6

**Comment by IanVS** [comment]
I think this must be fixed.  I tried it out, and the codesandbox is a built-out app, not just boilerplate.

**Comment by hwillson** [comment]
This was fixed - thanks!
