### ISSUE TITLE
Apollo Memory Update Error When Using Upload

### ISSUE THREAD

**Issue by Quadriphobs1** [apollographql/apollo-client#5440]
When uploading file to a server the request of the upload was completed, however, the mutation keet throwing error when updating the cache, by inspecting the network tab I can see the request was completed successfully, from each request all other hooks is currently not called since it throws the error, `onCompleted` or `update` is not called at all.

<img width="435" alt="Screenshot 2019-10-11 at 19 26 53" src="https://user-images.githubusercontent.com/20229808/66675399-2944d000-ec5d-11e9-8448-724793a7b6ca.png">
<img width="610" alt="Screenshot 2019-10-11 at 19 26 37" src="https://user-images.githubusercontent.com/20229808/66675404-2d70ed80-ec5d-11e9-9b79-6a14e9d0ab76.png">

**Versions**
```
...
 "apollo-boost": "^0.4.4",
    "apollo-cache-inmemory": "^1.6.3",
    "apollo-cache-persist": "^0.1.1",
    "apollo-client": "^2.6.4",
    "apollo-link": "^1.2.13",
    "apollo-link-error": "^1.1.12",
    "apollo-link-http": "^1.5.16",
    "apollo-link-state": "^0.4.2",
    "apollo-upload-client": "^11.0.0",
...

```

**Comment by hwillson** [comment]
We'll need a reproduction (using `@apollo/client@latest`) to be able to troubleshoot this further. Thanks!
