### ISSUE TITLE
Stop & start polling doesn't reset poll interval

### ISSUE THREAD

**Issue by mymywang** [apollographql/apollo-client#5444]
**Intended outcome:**
I'm trying to refetch the query results and restart poll interval. The query polls every 1 min, and when the button is clicked, refetch data, and reset interval so it starts another 1 min poll cycle.
```
const MyComponent: React.FunctionComponent = () => {
    const { data, loading, error, fetchMore, refetch, stopPolling, startPolling } = useQuery(
        query,
        { pollInterval: 60000 },
    );

    const handleClick = () => {
        stopPolling();
        refetch();
        startPolling(60000);
    };

    return (
        <MyDataList data={data.list} onClick={handleClick} />
    )
}
```

**Actual outcome:**
I can see that when the button is clicked, new list is refetched. However, the poll interval is not reset. In more details, I load the page, after 20 seconds, I click the button. I expect polling happens 1 min after I click the button. However, polling actually happens 40 seconds after the click.

**Versions**
```
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 12.8.1 - ~/.nvm/versions/node/v12.8.1/bin/node
    npm: 6.10.2 - ~/.nvm/versions/node/v12.8.1/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 68.0.1
    Safari: 13.0.2
```

**Comment by agileurbanite** [comment]
Bump? 👍

**Comment by SteffenHummel** [comment]
This happens because of rendering of the component. If you delete the timeout in the options object (line 4) the polls should only start when the button is clicked.

**Comment by reesscot** [comment]
Any update on this issue?

**Comment by normanzb** [comment]
possible duplication of #4948 https://github.com/apollographql/apollo-client/issues/4948

**Comment by hwillson** [comment]
Fixed in https://github.com/apollographql/apollo-client/pull/6438 - thanks!
