### ISSUE TITLE
Strange issue with useQuery not respecting query arguments (variables)

### ISSUE THREAD

**Issue by amitschandillia** [apollographql/apollo-client#5446]
**Intended outcome:**
I have a React component that receives a string (`authorSlug`) via props and uses it as a variable parameter in a parameterized query. The query then uses the string in a `where` clause to return matching results from the server. The intended outcome is results that match the `where` parameter.

The component looks like this:

```
// components/blog/SingleAuthor.jsx

import { useQuery } from '@apollo/react-hooks';
import gql from 'graphql-tag';

import getUserQuery from '../../apollo/schemas/getUserQuery.graphql';
import Loading from './Loading';

export const GET_USER = gql`${getUserQuery}`;

const SingleAuthor = (props) => {
  const { authorSlug } = props;

  console.log('USERNAME', authorSlug);

  const {
    loading,
    error,
    data,
  } = useQuery(
    GET_USER,
    {
      variables: { username: authorSlug },
      // Setting this value to true will make the component rerender when
      // the "networkStatus" changes, so we'd know if it is fetching
      // more data
      notifyOnNetworkStatusChange: true,
    },
  );

  if (error) return <div>There was an error!</div>;
  if (loading) return <Loading />;

  const { users } = data;
  console.log('USERS', users);
  const [user] = users;
  const {
    firstName,
    lastName,
  } = user;

  return (
    <>
      {firstName}
      {' '}
      {lastName}
    </>
  );
};

export default SingleAuthor;
```

The database is a collection of following `users`:
```
"users": [
      {
        "username": "negger",
        "firstName": "Arnold",
        "lastName": "Schwarzenegger"
      },
      {
        "username": "jonsnow",
        "firstName": "Jon",
        "lastName": "Snow"
      },
      {
        "username": "tonystark",
        "firstName": "Tony",
        "lastName": "Stark"
      }
    ]
  }
```

And the query being run is:
```
# apollo/schemas/getUserQuery.graphql

query users($username: String!) {
  users(where: { username: $username }) {
    _id
    username
    firstName
    lastName
  }
}
```

The `where` clause is meant to match the value passed to it (`authorSlug`) against the `username` field in this collection.

**Actual outcome:**
Now, although this should work (it does when I run the query in my graphql playground at https://dev.schandillia.com/graphql), the code runs as if the `where` clause didn't exist! It just returns all results as if the query being run were:
```
users {
  _id
  username
  firstName
  lastName
}
```

Instead of returning matching document(s), the query returns all documents as if the `where` clause didn't exist. There's no error log, just incorrect results.

**How to reproduce the issue:**
In order to reproduce the issue, visit https://www.schandillia.com/blog/authors/johnshow. The slug **jonsnow** is supposed to return the name **Jon Snow** but it returns **Arnold Schwarzenegger**. Now, run the same query with **jonsnow** as a `where` parameter in https://dev.schandillia.com/graphql:

```
{
  users(limit: 1, where: { username: "jonsnow" }) {
    _id
    username
    firstName
    lastName
  }
}
```
And the results would be exactly as expected:

```
{
  "data": {
    "users": [
      {
        "_id": "5d9f261678a32159e61018fc",
        "username": "jonsnow",
        "firstName": "Jon",
        "lastName": "Snow"
      }
    ]
  }
}
```

The repo is up for reference at https://github.com/amitschandillia/proost/tree/master/web-beta. This is where I have configured the Apollo Client HOC: https://github.com/amitschandillia/proost/blob/master/web-beta/apollo/index.jsx, and this is how I have used it in my page: https://github.com/amitschandillia/proost/blob/master/web-beta/pages/blog/authors/index.jsx.

**Versions**
System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  npmPackages:
    @apollo/react-hooks: ^3.1.1 => 3.1.1
    @apollo/react-ssr: ^3.1.1 => 3.1.1
    apollo-cache-inmemory: ^1.6.3 => 1.6.3
    apollo-client: ^2.6.4 => 2.6.4
    apollo-link-http: ^1.5.16 => 1.5.16

**Comment by belikovdev** [comment]
I have the same issue

**Comment by Dakuan** [comment]
ditto, seems to be the cache trying to be 'helpful'

**Comment by Dakuan** [comment]
I fixed this by adding the query params to the keyargs section of the type policy:
```
const cache = new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        birds: {
          keyArgs: ["type"],
          merge(existing, incoming, { args }) {
            if (!existing) {
              return incoming;
            }
            if (args && args.search) {
              return incoming;
            }
            const edges = unionBy("node.__ref", existing.edges, incoming.edges);
            return { ...incoming, edges };
          },
        },
        sightings: {
          keyArgs: ["userId"],          
          merge(existing, incoming, { args }) {
            if (args && !args.after) {
              return incoming;
            }
            if (!existing) {
              return incoming;
            }
            const edges = unionBy("node.__ref", existing.edges, incoming.edges);
            return { ...incoming, edges };
          },
        },
      },
    },
  },
});
```
that `userId` bit fixed it for me

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-client/issues/5446#issuecomment-789094556, `keyArgs` should help here. For more details see: https://www.apollographql.com/docs/react/pagination/key-args/ - thanks!
