### ISSUE TITLE
Why on QueryManager::startPollingQuery() overrides fetchPolicy?

### ISSUE THREAD

**Issue by Cifixie** [apollographql/apollo-client#5450]
On Documentation The WatchQueryOptions allows all kind of fetch policies but it seems it get's ignored by override. Is this expected behaviour, as the Typing + documentation is then misleading quite a lot.

After a while of investigating the issue: found a this: https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/QueryManager.ts#L1370

My best guess it that the poll expects the lastResult to be available, but then again, shouldn't need as the initial fetch works as fine.

Can anyone elaborate this a bit. #bit_confused

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
