### ISSUE TITLE
broken links & missing docs for DataProxy / cache

### ISSUE THREAD

**Issue by danprince** [apollographql/apollo-client#5453]
I've been looking for the `DataProxy` API reference and hit some broken links:

* https://www.apollographql.com/docs/react/api/apollo-client/ links to https://www.apollographql.com/docs/react/api/apollo-client/#DataProxy which doesn't exist
* https://github.com/apollographql/apollo-client/blob/master/docs/source/features/caching.md All the links are broken

Where can I find the signature (and calling examples) for `DataProxy#writeData`?

**Comment by shidianxia** [comment]
Same problem here.

**Comment by hwillson** [comment]
Doc links have been fixed - thanks!
