### ISSUE TITLE
How to combine restful api with an existing graphql api?

### ISSUE THREAD

**Issue by dpyzo0o** [apollographql/apollo-client#5473]
Hello everyone.

I want to build an website which relies on data from an existing graphql server and a restful api. I suppose I need to build my own apollo-server layer which connects these two datasources. For restful api I know I can use `RESTDataSource` to do that. However, how can I hook up the existing graphql datasource?

I would appreciate it if someone could help me!

**Comment by dpyzo0o** [comment]
Anyone can help?

**Comment by dpyzo0o** [comment]
Seems like no one has looked at this question?

**Comment by dylanwulf** [comment]
Github issues on this repo are reserved for bugs only. Try posting in [Spectrum](https://spectrum.chat/apollo?tab=posts) or [StackOverflow](https://stackoverflow.com/questions/tagged/apollo-client)
