### ISSUE TITLE
Broken link: Fragment Matcher

### ISSUE THREAD

**Issue by prvnbist** [apollographql/apollo-client#5477]
Broken [link](https://www.apollographql.com/docs/react/advanced/fragments.html#fragment-matcher) in the error message - 
```
You are using the simple (heuristic) fragment matcher, but your queries contain union or interface types. Apollo Client will not be able to accurately map fragments. 
To make this error go away, use the `IntrospectionFragmentMatcher` as described in the docs: https://www.apollographql.com/docs/react/advanced/fragments.html#fragment-matcher
```

**Comment by prvnbist** [comment]
Found the new link - https://www.apollographql.com/docs/react/v2.5/advanced/fragments/#fragments-on-unions-and-interfaces

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
