### ISSUE TITLE
MockedProvider makes a query return an error immediatelly after the initial render when an empty array of mocks is provided.

### ISSUE THREAD

**Issue by pietmichal** [apollographql/apollo-client#5478]
**Intended outcome:**
Component is not re-rendered with an error.

**Actual outcome:**
Component is re-rendered with an error:
> Network error: No more mocked responses for the query: (...)

**How to reproduce the issue:**
```
function Example() {
  const { loading, error } = useQuery(gql`
    query test {
       test {
         example
       }
     }
  `);
   return <>{loading} {error && error.message}</>;
}

function App() {
  return <MockedProvider mocks={[]}><Example /></MockedProvider>;
}

ReactDOM.render(<App />, document.querySelector("#app"));
```

And observe the output of the `Example` component.

**Versions**
```
  System:
    OS: macOS Mojave 10.14.5
  Binaries:
    Node: 12.6.0 - ~/.nvs/default/bin/node
    Yarn: 1.17.3 - ~/.nvs/default/bin/yarn
    npm: 6.9.0 - ~/.nvs/default/bin/npm
  npmPackages:
    @apollo/react-common: ^3.1.2 => 3.1.2 
    @apollo/react-hooks: ^3.1.2 => 3.1.2 
    @apollo/react-testing: ^3.1.2 => 3.1.2 
    apollo-boost: ^0.4.4 => 0.4.4 
    apollo-link-context: ^1.0.19 => 1.0.19 

```

**Comment by pietmichal** [comment]
This method of testing loading states is suggested by the docs: https://www.apollographql.com/docs/react/development-testing/testing/#testing-loading-states

Returning an error causes issues when a component's logic relies on error information.

For example, some of my component's are throwing an error when the actual error object is defined. This causes loading state tests to throw errors after running assertions.

**Comment by brandon-pereira** [comment]
I'm running into this too. My implicit error and result states are working, but passing an empty array to mocks is resulting in the error state (when I want the loading state).

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
