### ISSUE TITLE
Query will fall into a loop if the query resolver reject()

### ISSUE THREAD

**Issue by Octavianus** [apollographql/apollo-client#5485]
**Intended outcome:**
Query will stopped and render should continue with the default props passed to the next component

**Actual outcome:**
Query will be run over and over gain ONLY inside the query body.

**How to reproduce the issue:**
For client side query resolver. Return a asynchronous promise, reject('some reason').
And consume this query.

                return( <Query
                  query={myQuery}
                  variables={variables}
                >
                  {({ data }) => {
                    const prop = data && data.myData;
                    const ComponentProps = {
                      ...rest,
                      prop
                    };

                    return (
                      <Component
                        {...ComponentProps}
                      />
                    );
                  }}
                </Query>
              );

I tried to change between different errorPolicy and fetchPolicy, no luck.
I tried to use an equivalent <ApolloConsumer>, it will not loop but it is not what I'm looking for.

Feel free to reach out to me for more information.

**Versions**
  System:
    OS: Windows 10
  Binaries:
    Node: 8.11.3 - C:\Program Files\nodejs\node.EXE    Yarn: 1.5.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 3.10.10 - C:\Program Files\nodejs\npm.CMD 
  Browsers:
    Edge: 44.18362.329.0
  npmPackages:
    apollo-codegen: ^0.18.8 => 0.18.8

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
