### ISSUE TITLE
Apollo Client 3.0 vue/angular/etc...

### ISSUE THREAD

**Issue by ksmithut** [apollographql/apollo-client#5486]
Based on the ROADMAP.md, [this draft PR](https://github.com/apollographql/apollo-client/pull/5116) and [this comment](https://github.com/apollographql/react-apollo/issues/3505#issuecomment-542168159), it's not super clear how/if the apollo vue/angular/etc. clients will be supported. There are mentions of merging react-hooks directly into into Apollo Client 3.0, but no mention of other libraries. Are there plans to support other frameworks/libraries besides react?

**Comment by hwillson** [comment]
@ksmithut Yes, non-React view layers will be supported. `ApolloClient` can still be used by itself, and integrated with other libraries/frameworks. Apollo's React integration is merging into the core, but `@apollo/client` is fully tree-shakable. If you're using a modern build/bundling tool like Webpack, Rollup, etc. and aren't importing any of the React elements of `@apollo/client`, they'll all be removed from your final bundle. You can see some of this in action [here](https://github.com/apollographql/apollo-client/blob/a48dfa9f46ad4a46bfa7edff3945e14898e8f997/examples/bundling/README.md), but we'll have docs that explain all of this in more detail. Thanks!
