### ISSUE TITLE
Warning on graphql lib upgrade to latest version in some apollo packages

### ISSUE THREAD

**Issue by sashberd** [apollographql/apollo-client#5494]
Hi
I am upgrading now my db libs to latest versions. All upgrades of apollo-client were good, but after I upgraded graphql lib to version 14.5.8 from version 0.11.0, I started to get next warnings on all apollo packages:
warning "apollo-client > apollo-link@1.2.2" has incorrect peer dependency "graphql@^0.11.3 || ^0.12.3 || ^0.13.0".

My package json is:

> "apollo-cache-inmemory": "^1.6.3",
>  "apollo-client": "^2.6.4",
>  "apollo-link": "^1.2.13",
>     "apollo-link-error": "^1.1.12",
>     "apollo-link-http": "^1.5.16",
>     "apollo-link-persisted-queries": "^0.2.2",
>     "apollo-utilities": "^1.3.2",
> "graphql": "^14.5.8",

I saw that in dependencies of apollo-cache-redux there is an old version of apollo-cache-inmemory@1.2.10 same in apollo-client> apollo-link lib
May be you can update it in order to remove such warning from build?

**Comment by sashberd** [comment]
@dylanwulf You are right the issue is updated

**Comment by dylanwulf** [comment]
@sashberd The `apollo-cache-redux` package is not owned by the Apollo team. Unfortunately nobody here can help.
The github repo for `apollo-cache-redux` is located here: https://github.com/rportugal/apollo-cache-redux

If you need the package to be updated, you'll have to fork it and update it yourself.
