### ISSUE TITLE
Server-side rendering: OK to share client among requests?

### ISSUE THREAD

**Issue by mbrowne** [apollographql/apollo-client#5529]
I was wondering if it's OK to use apollo-client on a node server for SSR in this way:

```js
const defaultQueryOptions = {
    fetchPolicy: 'cache-and-network'
}

const client = new ApolloClient({
    ssrMode: true,
    link: createHttpLink({
        uri: 'http://localhost:3010',
        credentials: 'same-origin',
        headers: {
            cookie: req.header('Cookie'),
        },
    }),
    cache: new InMemoryCache(),
    defaultOptions: {
        watchQuery: defaultQueryOptions,
        query: defaultQueryOptions,
    },
})

// `app` is an Express server instance
app.use('*', (req, res) => {
    const app = (
        <ApolloProvider client={client}>
            <StaticRouter location={req.url} context={context}>
                <Layout />
            </StaticRouter>
        </ApolloProvider>
    )
    
    // rendering code...
})
```

Note how `client` is defined outside of the Express handler, and shared between all requests.

We are currently troubleshooting an issue with our app intermittently rendering the wrong data (e.g. returning values from entities other than the entity ID that was requested). We're not sure yet, but we think it might have something to do with SSR, since we are using the above approach and I noticed that the [official example](https://www.apollographql.com/docs/react/performance/server-side-rendering/#server-initialization) instantiates a new `client` for every request. We changed the Apollo fetch policy to `no-cache` and are still seeing the issue.

When I wrote our server using the above approach, I was thinking that sharing the `client` would be more efficient, and I didn't see a reason for each request to have its own Apollo client, especially now that we've set it to `no-cache`. But now I'm wondering if this is the source of the issue, and in any case I'd like to know if the Apollo team considers this a bad or unsupported practice.

Also, if sharing an Apollo client instance in this way is unsupported and not recommended, then I would suggest adding something to the docs to mention this. I know that I'm not the only one to use a shared Apollo client instance because I just found this article on Medium recommending the same thing:
https://medium.com/tokopedia-engineering/my-story-how-i-learnt-server-side-rendering-with-react-redux-routing-and-apollo-client-914b3d5ce748#4989

**Comment by benjamn** [comment]
Creating a new client for each request is definitely the official recommendation, and rendering the wrong data is a typical symptom of reusing an old client.

[Here](https://www.apollographql.com/docs/react/performance/server-side-rendering/#server-initialization)'s where we explicitly make this recommendation in the docs:
* You need to ensure that you create a new client or store instance for each request, rather than re-using the same client for multiple requests. Otherwise the UI will be getting stale data and you'll have problems with authentication.

**Comment by mbrowne** [comment]
Ah, sorry I missed that (I was probably reading too quickly and only remember seeing the mention about authentication, and was seeing this issue with a public endpoint). Thank you.
