### ISSUE TITLE
@apollo/client v3.0.0-beta.1 `partialRefetch: true` not working

### ISSUE THREAD

**Issue by migueloller** [apollographql/apollo-client#5535]
**Intended outcome:**

I'm attempting to use `partialRefetch` to refetch a partial array item that was add as a result of an "add" mutation.

**Actual outcome:**

Instead of an empty data object, the returned array is simply missing the partial objects.

**How to reproduce the issue:**

Client: https://codesandbox.io/s/apollo-empty-data-bug-client-ycntj
Server: https://codesandbox.io/s/apollo-empty-data-bug-server-8ncuk

Line 43 can be uncommented to see the behavior when there is no partial data (i.e., the title is returned by the mutation). When that line is commented, the missing title causes the workspaces' todos to come back as partial data and even though `partialRefetch` is specified, there is no refetch.

**Versions**

@apollo/client: 3.0.0-beta.1

**Comment by hwillson** [comment]
@migueloller This appears to be working with `@apollo/client@3.0.0-beta.22`. If you still think this is an issue, let us know. Thanks!

**Comment by migueloller** [comment]
@hwillson, it is not working for `@apollo/client@3.0.0-beta.22`. A simple look at the reproduction sandboxes shows that while data is coming back as partial, there's no refetch happening. One could argue this is even worse since now the shape of the data returned does not follow the GraphQL schema.

Note that `returnPartialData` is `false`, so for the reproduction one would expect a refetch, not partial data. So in this case neither `returnPartialData` or `partialRefetch` work as expected.

I don't understand why the issue was closed.

**Comment by hwillson** [comment]
Ahh, I misinterpreted your explanation @migueloller, sorry about that! Re-opening.

**Comment by benjamn** [comment]
@migueloller This should now be fixed if you update to `@apollo/client@3.0.0-beta.23`, judging from your reproduction (thanks for that!).

**Comment by hwillson** [comment]
@migueloller `@apollo/client@3.0.0-beta.23` appears to be working properly with your reproduction, so I'll close this off. Let us know otherwise. Thanks!

**Comment by migueloller** [comment]
@benjamn and @hwillson, it seems to be working now!

I do have a question, though. When refetching, `data` is set to `undefined` while `loading` is `true`. Would it make sense to keep `data` as the last fetched value while the refetch is happening?
