### ISSUE TITLE
[v3] getMainDefinition is not exposed

### ISSUE THREAD

**Issue by Grmiade** [apollographql/apollo-client#5536]
`getMainDefinition` utility function is not exposed from `@apollo/client`.
As a result, the examples on your doc are inaccurate :/
https://www.apollographql.com/docs/react/data/subscriptions/#client-setup

**Intended outcome:**
`import { getMainDefinition } from '@apollo/client';` should work

**Actual outcome:**
But `import { getMainDefinition } from '@apollo/client';` throw this error `Module ... has no exported member 'getMainDefinition'.`

**Version**
3.0.0-beta.1

**Comment by benjamn** [comment]
@hwillson This looks like something that could be enabled by exposing the `@apollo/client/utilities` entry point we talked about, right?

**Comment by alexraginskiy** [comment]
This is also present in 2.6.8

**Comment by hwillson** [comment]
This was fixed a few `beta` releases ago; `import { getMainDefinition } from '@apollo/client`;` should now work properly. Thanks!

**Comment by dunatron** [comment]
```
import { getMainDefinition } from '@apollo/client/utilities';
```

**Comment by Motoxpro** [comment]
> ```
> import { getMainDefinition } from '@apollo/client/utilities';
> ```

Had to use this as
`import { getMainDefinition } from '@apollo/client;` is not exposed
