### ISSUE TITLE
Apollo beta 3.0 not working with nextJS

### ISSUE THREAD

**Issue by addamove** [apollographql/apollo-client#5540]
**Intended outcome:**
Build my project

**Actual outcome:**
Failed to compile.

./node_modules/@apollo/react-hooks/lib/react-hooks.esm.js
Module not found: Can't resolve 'apollo-client' in '/tmp/build_dbd3be9a5f3729e0b64c9e04d0ded04e/node_modules/@apollo/react-hooks/lib'

**How to reproduce the issue:**
Just next JS app with @apollo/client 3.0 beta

**Versions**
  System:
    OS: Windows 10
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0
  npmPackages:
    apollo-cache-inmemory: ^1.6.3 => 1.6.3
    apollo-link-http: ^1.5.16 => 1.5.16
    next-with-apollo: ^4.3.0 => 4.3.0

**Comment by addamove** [comment]
Turns out this is next-with-apollo issue

**Comment by aurnik** [comment]
> Turns out this is next-with-apollo issue

What was the issue?

**Comment by JClackett** [comment]
@addamove What did you do to fix this?

**Comment by hjchan** [comment]
Upgrading `@apollo/react-ssr` to version `4.0.0-beta.1` solved my problem.
