### ISSUE TITLE
Running docs locally by following instructions results in error finding docs.json

### ISSUE THREAD

**Issue by zachlendon** [apollographql/apollo-client#5547]
**Intended outcome:**
Run docs locally

**Actual outcome:**
`npm start` results in:

 ERROR #10123  CONFIG

We encountered an error while trying to load your site's gatsby-config. Please fix the error and try again.

  Error: Cannot find module './docs.json'

  - loader.js:668 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:668:15

  - loader.js:591 Function.Module._load
    internal/modules/cjs/loader.js:591:27

  - loader.js:723 Module.require
    internal/modules/cjs/loader.js:723:19

  - v8-compile-cache.js:159 require
    [docs]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - gatsby-config.js:29 Object.<anonymous>
    [DIRECTORY SUBSTITUTED]/apollo-client/docs/gatsby-config.js:29:17

  - v8-compile-cache.js:178 Module._compile
    [docs]/[v8-compile-cache]/v8-compile-cache.js:178:30

  - loader.js:827 Object.Module._extensions..js
    internal/modules/cjs/loader.js:827:10

  - loader.js:685 Module.load
    internal/modules/cjs/loader.js:685:32

  - loader.js:620 Function.Module._load
    internal/modules/cjs/loader.js:620:12

  - loader.js:723 Module.require
    internal/modules/cjs/loader.js:723:19

  - v8-compile-cache.js:159 require
    [docs]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - get-config-file.js:24 getConfigFile
    [docs]/[gatsby]/dist/bootstrap/get-config-file.js:24:20

  - index.js:124 module.exports
    [docs]/[gatsby]/dist/bootstrap/index.js:124:36

  - build.js:72 build
    [docs]/[gatsby]/dist/commands/build.js:72:13

  - create-cli.js:161 cli.command.handler.getCommandHandler
    [docs]/[gatsby]/[gatsby-cli]/lib/create-cli.js:161:14

  - create-cli.js:96 argv
    [docs]/[gatsby]/[gatsby-cli]/lib/create-cli.js:96:24

  - create-cli.js:31 Object.args [as handler]
    [docs]/[gatsby]/[gatsby-cli]/lib/create-cli.js:31:19

  - command.js:238 Object.runCommand
    [docs]/[gatsby]/[yargs]/lib/command.js:238:44

  - yargs.js:1063 Object.parseArgs [as _parseArgs]
    [docs]/[gatsby]/[yargs]/yargs.js:1063:30

  - yargs.js:566 Object.parse
    [docs]/[gatsby]/[yargs]/yargs.js:566:25

  - create-cli.js:366 module.exports.argv
    [docs]/[gatsby]/[gatsby-cli]/lib/create-cli.js:366:6

  - index.js:117 Object.<anonymous>
    [docs]/[gatsby]/[gatsby-cli]/lib/index.js:117:1

**How to reproduce the issue:**
Follow instructions for running docs locally - `npm install` then `npm start`

**Versions**
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v11.15.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.87
    Safari: 13.0.2
  npmPackages:
    gatsby-theme-apollo-docs: 2.3.14 => 2.3.14

**Comment by SleamJ** [comment]
have same problem :( how to solve it ?

**Comment by dankoknad** [comment]
Not really a fix, but will let you compile docs and preview it on `http://localhost:8000/`:

1. create `docs.json` file in the root of the `docs` directory
2. content could be any valid json, I've used this `{ "a": "b" }`
3. run `npm start`

**Comment by alivenotions** [comment]
It's not easy to do much even with an empty `docs.json` file as many pages refer that file for content.
What is the reason for it to be git ignored? 🤔

**Comment by hwillson** [comment]
This was fixed - thanks!

**Comment by hankthemason** [comment]
how did you fix it?
