### ISSUE TITLE
Infinite loop when using defaulted variable in @skip/@include

### ISSUE THREAD

**Issue by dylanwulf** [apollographql/apollo-client#5556]
**Intended outcome:**
Non-polling queries should not repeatedly make network requests

**Actual outcome:**
Query is repeatedly re-querying even though I am not polling. This only happens if I am using `@skip` or `@include`, and the `if` argument is using an unspecified defaulted variable. It stops happening if I remove the `onCompleted` function.

**How to reproduce the issue:**
Open one of the following codesandboxes and watch the console:
apollo-client v2.6.4: https://codesandbox.io/s/reproducing-infinite-loop-acv2-8zytf
apollo-client v3 beta: https://codesandbox.io/s/reproducing-infinite-loop-acv3-tfmre

**Versions**
@apollo/react-hooks: 3.1.3
@apollo/client: 3.0.0-beta.4
apollo-cache-inmemory: 1.6.3
apollo-client: 2.6.4
graphql-tag: 2.10.1

**Comment by brainkim** [comment]
@dylanwulf I tried updating your reproduction but ended up in dependency hell. This is about as close as I could reproduce your example against the modern error template and all in one file, but was unable to produce the bug. Maybe it’s fixed, or has something to do with the schema link stuff you were using?

```tsx
/*** SCHEMA ***/
import {
  GraphQLSchema,
  GraphQLObjectType,
  GraphQLString,
  GraphQLList,
} from 'graphql';

const ThingsResultType = new GraphQLObjectType({
  name: 'ThingsResult',
  fields: {
    things: {
      type: new GraphQLList(GraphQLString),
      resolve: () => (['result A', 'result B']),
    },
  },
});

const QueryType = new GraphQLObjectType({
  name: 'Query',
  fields: {
    thingsList: {
      type: ThingsResultType,
      resolve: async () => {
        await new Promise(resolve => setTimeout(resolve, 500));
        return {thingsList: {}};
      },
    },
  },
});

const schema = new GraphQLSchema({ query: QueryType });

/*** LINK ***/
import { graphql, print } from "graphql";
import { ApolloLink, Observable } from "@apollo/client";
function delay(wait) {
  return new Promise(resolve => setTimeout(resolve, wait));
}

const link = new ApolloLink(operation => {
  return new Observable(async observer => {
    console.log("REQUESTING");
    const {query, operationName, variables} = operation;
    await delay(300);
    try {
      const result = await graphql(
        schema,
        print(query),
        null,
        null,
        variables,
        operationName,
      );
      observer.next(result);
      observer.complete();
    } catch (err) {
      observer.error(err);
    }
  });
});

/*** APP ***/
import React, { useState } from "react";
import { render } from "react-dom";
import {
  ApolloClient,
  ApolloProvider,
  gql,
  InMemoryCache,
  useQuery,
} from "@apollo/client";
import "./index.css";

const client = new ApolloClient({link, cache: new InMemoryCache()});

const QUERY = gql`
  query GetThings($test: Boolean = false) {
    thingsList {
      things @skip(if: $test)
    }
  }
`;

function ThingsList() {
  const { data, loading, error } = useQuery(QUERY, {
    fetchPolicy: 'network-only',
    notifyOnNetworkStatusChange: true,
    variables: {}, // problem does not happen if `variables` is undefined
    onCompleted: () => {}, // problem does not happen if `onCompleted` is undefined
  });

  return (
    <div>
      <div>Loading: {String(loading)}</div>
      {error && <div>{error.message}</div>}
      <div>Results:</div>
      {data &&
        data.thingsList &&
        data.thingsList.things &&
        data.thingsList.things.map(thing => <div key={thing}>{thing}</div>)}
    </div>
  );
}

function App() {
  const [queryMounted, setQueryMounted] = useState(true);
  return (
    <ApolloProvider client={client}>
      <button onClick={() => setQueryMounted(true)} disabled={queryMounted}>
        Mount Query
      </button>
      <button onClick={() => setQueryMounted(false)} disabled={!queryMounted}>
        Unmount Query
      </button>
      {queryMounted && <ThingsList />}
    </ApolloProvider>
  );
}

render(
  <App />,
  document.getElementById("root"),
);
```

**Comment by dylanwulf** [comment]
@brainkim Thank you for looking into this old issue! I updated my reproduction: https://codesandbox.io/s/lc7wy?file=/src/index.js

It does appear to be fixed as you said, so I believe it's time to close this!

**Comment by dylanwulf** [comment]
P.S. I don't believe the SchemaLink in my repro was related to the problem since I was also seeing this in my app with HttpLink. My SchemaLink setup should theoretically be doing the same thing as what you posted, just with some slightly more readable syntax. I use this approach in my unit tests as well. In case you're curios, I got the idea from this article: https://www.freecodecamp.org/news/a-new-approach-to-mocking-graphql-data-1ef49de3d491/
Personally I find this approach to testing much nicer than MockProvider since every field is mocked automatically.
