### ISSUE TITLE
Invariant Violation when combining hooks from new beta with query components

### ISSUE THREAD

**Issue by davismariotti** [apollographql/apollo-client#5558]
**Intended outcome:**
During our migration from react apollo query components to hooks, we'd like to be able to use both at the same time.

**Actual outcome:**
When using query components with the new `@apollo/client` and `@apollo/react-components`, I get the following error: 

> Invariant Violation
Could not find "client" in the context or passed in as an option. Wrap the root component in an &lt;ApolloProvider&gt;, or pass an ApolloClient instance in via options.

**How to reproduce the issue:**
I've created a codepen [here](https://codesandbox.io/s/react-example-9p9ym?fontsize=14).
If you comment out the `ComponentVersion` and uncomment `HooksVersion`, it works fine.

I think the reason for the error is because of the package `ApolloProvider` comes from not being the required one to use with the components. Is this something that can be done with the new beta? Or do I still need to use `ApolloProvider` from `react-apollo`?

**Versions**
<pre>
System:
  OS: macOS Mojave 10.14.6
Binaries:
  Node: 8.6.0 - /usr/local/bin/node
  npm: 6.13.0 - ~/.npm-global/bin/npm
Browsers:
  Chrome: 78.0.3904.97
  Firefox: 69.0.2
  Safari: 13.0.3
npmPackages:
  @apollo/client: 3.0.0-beta.4
  @apollo/react-components: 3.1.3
  apollo-client: 2.6.4
  graphql: 14.5.8
</pre>

**Comment by benjamn** [comment]
There's a new beta version of https://www.npmjs.com/package/@apollo/react-components (`3.2.0-beta.0`) that works with the latest `@apollo/client`:
```sh
npm i @apollo/react-components@beta
```
Try that?

**Comment by davismariotti** [comment]
This question was answered here: https://stackoverflow.com/questions/58771868/invariant-violation-when-using-react-apollo-hooks-alongside-query-components

@benjamn Thanks for your answer, that also works, and I will be using that instead, thanks!
