### ISSUE TITLE
Server-side rendering docs still allow XSS attacks

### ISSUE THREAD

**Issue by mikaelgramont** [apollographql/apollo-client#5567]
Hello,

This may seem like a duplicate of closed issue #4394, but I'm creating a new one because I believe the changes to [the server-side rendering doc](https://www.apollographql.com/docs/react/performance/server-side-rendering/#store-rehydration) are not sufficient.

The doc states this as the suggested way to pass state from server to client:
```
<script>
  window.__APOLLO_STATE__ = JSON.stringify(client.extract());
</script>
```
However, it's still vulnerable to data containing a payload of the type:
```
{"content": "</script><script>alert('xss')</script>"}
```

As it was mentioned, [the best practice indicated on the Redux site](https://redux.js.org/recipes/server-rendering#security-considerations) makes this problem go away, and should be integrated in the Apollo Client doc:

```
<script>
  window.__APOLLO_STATE__ = JSON.stringify(client.extract()).replace(/</g, '\\u003c');
</script>
```

**Comment by hwillson** [comment]
This was fixed - thanks!
