### ISSUE TITLE
assumeImmutableResults type missing from PresetConfig interface in Apollo Boost client types

### ISSUE THREAD

**Issue by bencoullie** [apollographql/apollo-client#5570]
**Intended outcome:**
No Typescript linting/compiling errors occur after the user adds `assumeImmutableResults: true` to the base `ApolloClient` config.

**Actual outcome:**
Compilation error:
```
Failed to compile.

.../src/common/data/apollo/index.ts
TypeScript error in .../src/common/data/apollo/index.ts(36,3):
Argument of type '{ cache: InMemoryCache; onError: ({ graphQLErrors, networkError, response }: ErrorResponse) => void; uri: string; fetchOptions: { credentials: string; }; headers: { 'x-xsrf-token': string | null; }; clientState: { defaults: { isConnected: boolean; }; resolvers: { ...; }; }; assumeImmutableResults: boolean; }' is not assignable to parameter of type 'PresetConfig'.
  Object literal may only specify known properties, and 'assumeImmutableResults' does not exist in type 'PresetConfig'.
```
I had a look in the `/node_modules/apollo-boost/lib/index.d.ts` and it looks like we're missing a `assumeImmutableResults: boolean` property.

**How to reproduce the issue:**
`1`: `git clone git@github.com:bencoullie/apollo-boost-error-replication.git`
`2`: `nvm use`
`3`: `yarn`
`4`: `yarn start`

You should see the compilation error. 

**Versions**
```
System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.11.2 - ~/.config/yarn/global/node_modules/.bin/npm
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 70.0
    Safari: 13.0.3
  npmPackages:
    apollo-boost: ^0.4.4 => 0.4.4 
    react-apollo: ^3.1.3 => 3.1.3
```

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!

**Comment by hwillson** [comment]
Ah - just saw this was fixed by https://github.com/apollographql/apollo-client/pull/5571 - even better! 🙇‍♂️
