### ISSUE TITLE
useQuery result is not updated when `errorPolicy: all` and errors are present

### ISSUE THREAD

**Issue by mridder2** [apollographql/apollo-client#5576]
**Intended outcome:**

Data returned from useQuery should be updated when refetched. 

**Actual outcome:**

Data returned from useQuery is not updated after a refetch.
Furthermore, an uncaught error is thrown from apollo client: 
![Screenshot 2019-11-13 at 15 48 39](https://user-images.githubusercontent.com/50366801/68774243-142cd980-062d-11ea-8b25-350a4fd0b391.png)

**How to reproduce the issue:**

This bug is reproduced in this repo: [https://github.com/mridder2/apollo-client-refetch-issue](https://github.com/mridder2/apollo-client-refetch-issue)
1. useQuery returns both data and errors (because of `errorPolicy: "all"`). 
2. Refetch the data (by using `refetchQueries`) after mutating this data
3. The data is not updated in the UI, even though the network tab shows that it is different

**Versions**

  System:
    OS: macOS 10.15.1
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 70.0.1
    Safari: 13.0.3
  npmPackages:
    @apollo/react-hooks: ^3.1.3 => 3.1.3
    apollo-cache-inmemory: ^1.6.3 => 1.6.3
    apollo-client: ^2.6.4 => 2.6.4
    apollo-link-http: ^1.5.16 => 1.5.16
    apollo-server: ^2.9.8 => 2.9.8
    react-apollo: ^3.1.3 => 3.1.3

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
