### ISSUE TITLE
Multiple polling queries incorrectly flash previously fetched data when fetchPolicy is 'no-cache'

### ISSUE THREAD

**Issue by volkan-anchor** [apollographql/apollo-client#5584]
**Intended outcome:**

On a cursor-based paginated API, I want to correctly paginate through multiple pages of data, regardless of what other queries are on the page.

**Actual outcome:**

When there are two queries that both use polling and the fetch policy is set to `no-cache`, pagination on one of the queries briefly shows the new page's data, then the previous page's data, then the new page's data.

It doesn't matter what the other query is, just that there is another query, and that they both use polling.

**How to reproduce the issue:**

https://codesandbox.io/s/apollo-client-error-template-634bb

There are 2 queries, Q1 and Q2, both polling at 2000ms intervals (still broken with 1000 and 2000ms). Q2 can be paginated by clicking on `next` button, which fetches a new page of data. When user tries to paginate Q2 **just before** Q1 is in `poll` state Q2's data gets mixed up and Q2 table briefly displays previously fetched data. The issue is inconsistent, you might need to try couple times before you can see it.

For example, say Q2 has pages A and B of data. We are showing page A for Q2's results. When we click on `next` to fetch page B, Q2 will show B, then flash to A, then flash back to B. If we hold state based on what "page" we are on currently, this is messed up by Q2 showing A when it should be showing B. It is also very visually disruptive.

This issue can be solved by setting the query's `fetchPolicy` to `network-only` instead of `no-cache`. 

[codesandbox](https://codesandbox.io/s/apollo-client-error-template-634bb)
[graphqlhub](https://www.graphqlhub.com/playground?query=%23%20Welcome%20to%20GraphQLHub!%20Type%20your%20GraphQL%20query%20here%2C%20or%0A%23%20explore%20the%20%22Docs%22%20to%20the%20right%0A%0A%7B%0A%20%20hn2%20%7B%0A%20%20%20%20nodeFromHnId(id%3A%22clayallsopp%22%2C%20isUserId%3Atrue)%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20...%20on%20HackerNewsV2User%20%7B%0A%20%20%20%20%20%20%20%20hnId%0A%20%20%20%20%20%20%20%20submitted(first%3A%205)%20%7B%0A%20%20%20%20%20%20%20%20%20%20pageInfo%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20hasNextPage%0A%20%20%20%20%20%20%20%20%20%20%20%20endCursor%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20cursor%0A%20%20%20%20%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20...%20on%20HackerNewsV2Story%20%7B%0A%09%09%09%09%09%09%09%09score%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20url%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20...%20on%20HackerNewsV2Comment%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20text%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)

**Versions**

![Screenshot 2019-11-14 at 3 44 13 PM](https://user-images.githubusercontent.com/54550437/68907106-663c3080-06fb-11ea-882b-13ceaca8b599.png)

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
