### ISSUE TITLE
Support return raw JSON

### ISSUE THREAD

**Issue by oNguyenThanhMinhB** [apollographql/apollo-client#5585]
Apollo Android Client returns classes that are auto-generated by apollo. This is weird because after query I have to map the auto-generated classes (Ex: GetUserQuery.Data) to the data model (Ex: UserData). What can I do to the query return raw JSON instead of auto-generated classes? With JSON, I can parse it to the data model easier.

**Comment by hwillson** [comment]
This question is better asked in the https://github.com/apollographql/apollo-android repo - thanks!
