### ISSUE TITLE
Fragment with only @client fields throw an error

### ISSUE THREAD

**Issue by paulrberg** [apollographql/apollo-client#5586]
**Intended outcome:**

Fragments which contain only fields with @client directives should work fine.

```javascript
STREAM.fragments.timeLabels = gql`
  fragment TimeLabels on Stream {
    timeLabels @client {
      depositTime
      passed
      remaining
      startTime
      stopTime
    }
  }
```

**Actual outcome:**

The fragment above causes this error:

> Error: Network error: Cannot read property 'args' of undefined

Here's a [gist](https://gist.github.com/PaulRBerg/bbee9e67b2ef0a7c6c21c1a3f142957c) with the full error log.

**How to reproduce the issue:**

1. Open this CodeSandbox: https://codesandbox.io/s/ubiquitous-confetti-m2abfe-x9z06
2. Select the `App.js` file
3. Uncomment line 9 so that the only field in the `LocalPerson` fragment is `foo`, which has the `@client` directive
4. Comment the line again to see the error go away

**Versions**

- apollo-cache-inmemory@^1.6.3
- apollo-client@^2.6.4
- apollo-link-http@^1.5.16
- graphql@^14.5.8
- graphql-tag@^2.10.1
- react@16.11.0
- react-dom@16.11.0

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
