### ISSUE TITLE
Cached fragment gets orphaned from root query

### ISSUE THREAD

**Issue by ScottRobbins** [apollographql/apollo-client#5587]
**Intended outcome:**

The crux of it is that we have a query where we are getting an array of union types. Different parts of the app care about different union types so different queries specify just the ones they care about (using the `... on MyUnionType` in the query. 

For example, you first request: 

```graphql
query booksWithDocument {
    books {
      ... on Fantasy {
        id
        book {
          title
          author
        }
      }

      ... on SciFi {
        id
        book {
          title
          author
        }
      }

      ... on Documentary {
        id
        book {
          title
          author
        }
      }
    }
  }
```

That gets cached, and then you request (without documentary option)

```graphql
query booksWithoutDocumentary {
    books {
      ... on Fantasy {
        id
        book {
          title
          author
        }
      }

      ... on SciFi {
        id
        book {
          title
          author
        }
      }
    }
  }
```

The intent is that when you request the documentary again if it has been previously cached it can be pulled from cache. 

**Actual outcome:**

It fails to pull the documentary from the cache. The documentary appears to be in the apollo cache, but no longer associated to the root query. 

**How to reproduce the issue:**

I made a test server/react native client demonstrating the issue: https://github.com/ScottRobbins/ApolloCachingIssue 

**Version**

2.6.4

**Other Information**

I'm not completely sure if this is a bug or not, but the behavior surprised me.

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
