### ISSUE TITLE
WriteFragment does not update when adding item to empty list

### ISSUE THREAD

**Issue by emrosenf** [apollographql/apollo-client#5592]
I have an Apollo mutation with cache update

```jsx
const [mutate, mutationProps] = useMutation(WRITE_COMMENT_MUTATION, {
  update: (cache, { data }) => {
    const current = cache.readFragment({
      id: `${props.data.__typename}:${props.data.id}`,
      fragmentName: 'TopicCommentsFragment',
      fragment: ADD_COMMENT_FRAGMENT,
    })
    const allComments = [
      ...props.data.comments,
      data.addComment
    ];
    cache.writeFragment({
      id: `${props.data.__typename}:${props.data.id}`,
      fragmentName: 'TopicCommentsFragment',
      fragment: ADD_COMMENT_FRAGMENT,
      data: {
        __typename: props.data.__typename,
        comments: allComments
      }
    });
  }
});
```

and gql

```jsx
const ADD_COMMENT_MUTATION = gql`
  mutation AddCommentMutation(
    $toTopic: ID
    $toOrganization: ID
  ) {
    addComment(
      content: $content
      toTopic: $toTopic
    ) {
      ...CommentFragment
    }
  }
  ${COMMENT_FRAGMENT}
`;

const ADD_COMMENT_FRAGMENT = gql`
  fragment TopicCommentsFragment on Topic {
    comments {
      ...CommentFragment
    }
  }
  ${COMMENT_FRAGMENT}
`;
```

**Intended outcome:**
The React component should update with the results of the mutation (the added comment)

**Actual outcome:**
If the comment array is empty and you are adding the first comment, no UI update occurs. You can refresh the page to see the comment correctly displayed.

If there were already one or more comments, the UI update occurs as expected.

I have tried using `client.writeFragment` instead of `cache.writeFragment`. I have played around with deep cloning the results, but so far no success.

Any ideas?

**Comment by JimmyMultani** [comment]
Having this exact same issue. Any help would be greatly appreciated.

**Comment by JimmyMultani** [comment]
Seems like using nullish coalescing for defining subfields within arrays inside my Fragments fixed it.

**Comment by Gazler** [comment]
Adding `returnPartialData: true` to the query options worked for me.

e.g.

```javascript
const response = useGetUsersWithLocationsQuery({returnPartialData: true});
```

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
