### ISSUE TITLE
useQuery doesn't notify for invalid queries on local state management

### ISSUE THREAD

**Issue by zaguiini** [apollographql/apollo-client#5596]
**Intended outcome:**
The Apollo client warns me that I'm using an invalid query/field while using the `useQuery` hook while dealing with local state

**Actual outcome:**
It doesn't display valuable information about the error. In fact, it displays nothing.

**How to reproduce the issue:**
[There's a Sandbox for it](https://codesandbox.io/s/solitary-voice-x78cp). You can alternate between the working and broken version by toggling commented lines on the `App` component. Check the queries on `queries.js`... the field `name` doesn't exist -- the correct field is `text`, but I get no warning about that.

**Versions**
```
@apollo/react-hooks - 3.1.3
apollo-boost - 0.4.4
graphql - 14.5.8
```

**Additional information**

In the [docs](https://www.apollographql.com/docs/react/data/local-state/), it says:

“Client-side schema

You can optionally set a client-side schema to be used with Apollo Client, through either the ApolloClient constructor typeDefs parameter, or the local state API setTypeDefs method. Your schema should be written in Schema Definition Language. This schema is not used for validation like it is on the server because the graphql-js modules for schema validation would dramatically increase your bundle size. Instead, your client-side schema is used for introspection in Apollo Client Devtools, where you can explore your schema in GraphiQL.”

Which I think it kinda invalidates this issue report? The suggestion of a friend of mine would be to include `graphql-js` in development mode to notify the user and strip it out when bundling for production.

**Comment by breathe** [comment]
i've run into what I believe is the exact same issue -- its a real bad problem!

In my case -- I'm wanting to use apollo local state.  I modify an existing query adding a @client field to it.

If you don't do anything else that's enough to get invisible errors.

Suppose you attempt to fix by stabbing in the dark at whatever black hole has sucked away all useful feedback about your issue.

You create typedefs, and resolvers, and add them to new ApolloClient({}) appropriately.

But there's a bug in your resolver -- and you are not returning a value for one of the @client properties.  You get an error with no information to help debug.

Even if the value is nullable.

Please please please, figure out how to provide useful information about this category of errors!

This makes client side apollo state borderline unuseable.

**Comment by brentguistwite** [comment]
I just ran into and lost an hour debugging it. I had a query that looked something like this
```
query Foo {
  bar @client {
    a
    b
    c
    d
    e
    f
    g
  }
}
```
However, when I was writing the default data to the store I wasn't writing the `g` field. useQuery returned undefined for data and undefined for error as well. Literally anything would be helpful, returning all the data and having `g` be undefined or throwing an error about a key not existing.

**Comment by yss14** [comment]
I just ran into the same issue, which cost me about 2 hours of debugging.
If you try to query a not-existing key on your local schema, there is NO error, `useQuery` just returns `undefined` for `data` and `error`.

**Comment by kevinjcoleman** [comment]
@yss14 I set `errorPolicy` to `all` and I was able to access the error object.
```
  const { error, data } = useQuery(
    GET_STUFF,
    { errorPolicy: 'all' }
  )
    
  if (error) {
    console.log("error", error)
  }
```

**Comment by ericf89** [comment]
Adjusting the `errorPolicy` didn't actually make any difference in my testing. 🤔  Still undefined data & error fields.  On @apollo/client 3.1.2.

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
