### ISSUE TITLE
No warning if Interface doesn't exist using IntrospectionFragmentMatcher

### ISSUE THREAD

**Issue by Akryum** [apollographql/apollo-client#5600]
**Intended outcome:**

A warning is thrown because the `Being` interface is not referenced in `introspectionQueryResultData`.  For example, if the result `__typename` is different from the fragment, check if a corresponding interface or union is referenced in `introspectionQueryResultData` and print a warning similar to:

```
Unable to resolve possible types for interface or union 'Being'.
Please check that 'introspectionQueryResultData' contains this type.
Did you mean 'NotBeing'?
```

**Actual outcome:**

No warning and strange caching errors.

**How to reproduce the issue:**

https://codesandbox.io/s/apollo-client-error-template-8gmmi

**Versions**

On codesandbox:

```
  "dependencies": {
    "@apollo/react-hooks": "^3.0.0",
    "apollo-cache-inmemory": "^1.6.3",
    "apollo-client": "^2.6.4",
    "apollo-link": "^1.2.12",
    "graphql": "^14.4.2",
    "graphql-tag": "^2.10.1",
    "react": "^16.9.0",
    "react-dom": "^16.9.0"
  },
```

**Comment by benjamn** [comment]
We are removing the fragment matcher abstraction in Apollo Client 3.0, in favor of a much simpler [`possibleTypes` API](https://github.com/apollographql/apollo-client/blob/release-3.0/docs/source/data/fragments.md#using-fragments-with-unions-and-interfaces).

However, I think your suggestion still applies: if we know that a fragment type condition is a supertype, then we should be able to warn if the observed subtype is unknown. If we don't know anything about the supertype status of the type condition, we can't give a warning, but I think we can safely assume that any explicitly provided `possibleTypes` information is complete.

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!

**Comment by Akryum** [comment]
Will check
