### ISSUE TITLE
cacheRedirects don't work without queried before

### ISSUE THREAD

**Issue by maykonmichel** [apollographql/apollo-client#5604]
**Intended outcome:**

I was trying to redirect the data cached of my login mutation to a query of the same data.

###### Mutation on my login file
```graphql
mutation($input: AuthInputType) {
  login(input: $input) {
    token
    user {
      id
      name
    }
  }
}
```
###### Query on my header component (I want to show the name)
```graphql
query($id: ID) {
  user(id: $id) {
    id
    name
  }
}
```
###### My InMemoryCache config
```javascript
const cache = new InMemoryCache({
  cacheRedirects: {
    Query: {
      user: (_, { id }, { getCacheKey }) => {
        console.log("this log isn't triggered");
        return getCacheKey({ id, __typename: 'UserType' });
      },
    },
  },
});
```
So, I expected just one connection with my API on login. 

**Actual outcome:**

Although everything looks like in [docs,](https://www.apollographql.com/docs/react/caching/cache-interaction/#cache-redirects-with-cacheredirects) this **don't work** as intended. There is two call to my API: one for login and one for get the user name from header component. 

**How to reproduce the issue:**

Try to do a client that cashes the returned user data and use on a query using cacheRedirects. A possible workaround is do any query before login mutation.

**Versions**

System:
    OS: Linux 4.15 Deepin 15 15.11
  Binaries:
    Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
    Yarn: 1.19.1 - ~/.nvm/versions/node/v10.17.0/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
  Browsers:
    Chrome: 73.0.3683.86
  npmPackages:
    @apollo/react-hooks: ^3.1.3 => 3.1.3 
    apollo-cache-inmemory: ^1.6.3 => 1.6.3 
    apollo-cache-persist: ^0.1.1 => 0.1.1 
    apollo-client: ^2.6.4 => 2.6.4 
    apollo-link: ^1.2.13 => 1.2.13 
    apollo-link-context: ^1.0.19 => 1.0.19 
    apollo-link-http: ^1.5.16 => 1.5.16 
    apollo-link-retry: ^2.2.15 => 2.2.15 
    apollo-link-ws: ^1.0.19 => 1.0.19 
    apollo-utilities: ^1.3.2 => 1.3.2

**Comment by pschlette** [comment]
Just came upon what looks like this same issue! `apollo-client@2.5.1`, `apollo-cache-inmemory@1.5.1`. Expected data from a mutation to be cached, but a subsequent query that should take data from the cache via a cache redirect makes a request instead.

**Comment by juicylevel** [comment]
When will this fix be in release?

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
