### ISSUE TITLE
Local State API method "setTypeDefs" Not Found

### ISSUE THREAD

**Issue by mikepricedev** [apollographql/apollo-client#5612]
The "setTypeDefs" method document [here](https://www.apollographql.com/docs/react/data/local-state/#client-side-schema) is NOT located on `InMemoryCache` or `ApolloClient` instances.

Furthermore, I searched the entire install folder for "setTypeDefs" without success.  Via google search, I did find it on `ApolloClient` class def in a pull request diff-view [here](https://github.com/apollographql/apollo-client/pull/4338/files/2db5dbe0b476fbc28f504ce6c122da6eba71c7d3) in "packages/apollo-client/src/ApolloClient.ts".  However, in the current version of this file it is not there.

Has it been deprecated, moved, or am I looking completely in the wrong place?

Respectfully,
MP

**Comment by Hydraz320** [comment]
Want an "addTypeDefs", too. Just like "addResolvers" to deal with code split.

**Comment by GeKorm** [comment]
In case someone stumbles upon this. `setTypeDefs` was removed in commit d3931b8347c76c961ae24da68ef108576e67ff0d on Feb 1, 2019 with the following explanation:

>We're going to avoid getters/setters for `typeDefs` for now,
and instead recommend `typeDefs` are set via the `ApolloClient`
constructor. We were originally exposing getters/setters for
integrations like Apollo Client Devtools, but we'll adjust
devtools to access the `typeDefs` in a different way. We will
likely want to revisit this decision in the future, to
accommodate the possibility that people want to add to their
local schema at different points in their application, but
we'll cross that bridge when we get there. For now keeping the
changes to the public `ApolloClient` API minimal, is the goal.

**Comment by hwillson** [comment]
https://github.com/apollographql/apollo-client/issues/5612#issuecomment-587758426 answers this - thanks!
