### ISSUE TITLE
@export is broken by __typename

### ISSUE THREAD

**Issue by mikepricedev** [apollographql/apollo-client#5613]
```
{
   query Pages {
       # Local State Pagination arguments
        inputTypeArg(id:1) @client @export(as:"inputArg") {
           skip
           limit
       }
       # Remote Graphql Server
       pages(inputArg:$inputArg) {
         ...
       }
   }
}
```

The above will return an Error ~ `Variable "$arg" got invalid value { __typename: ... Field "__typename" is not defined by type...`.

`new InMemoryCache({addTypename: false})` has no effect.

Update:  The `@export` local state query is fed raw into the remote queries arg.  The exported local query will NOT respect any data shaping written into the local export results.  In additional,  the `__typename` param will either be in EVERY local result or NO local results.  Due to the "addTypename" option in the `InMemoryCache`.  You can not use your query to request or not request `__typename`.  If you set `{addTypename:true}` and exclude `__typename` from your query, it will be in your result.  If you set `{addTypename:false}` and request  `__typename` in your query, you will get an error.

Proposal:  `@export` SHOULD respect the data shaping of its query BEFORE it is feed into a query as an `input` arg.  It is almost certainly  necessary to the SDL of the `input` arg.  `__typename` should NOT be returned when it is NOT requested or be returned when it is requested and `{addTypename:false}`.

**Comment by bretthadley** [comment]
Hi @mikepricedev 

I got a similar issue to you except I used the skip directive to remove  the typename.

e.g. 
```
{
   query Pages {
       # Local State Pagination arguments
        inputTypeArg(id:1) @client @export(as:"inputArg") {
           skip
           limit
           __typename @skip(if: true)
       }
       # Remote Graphql Server
       pages(inputArg:$inputArg) {
         ...
       }
   }
}
```

However I now get errors like

```
Missing field q in {
  "__typename": "ActiveSearchState"
}
Missing field limit in {
  "__typename": "ActiveSearchState"
}
Missing field offset in {
  "__typename": "ActiveSearchState"
}
Missing field order in {
  "__typename": "ActiveSearchState"
}

Invariant Violation: Store error: the application attempted to write an object with no provided typename but the store already contains an object with typename of ActiveSearchState for the object of id $ROOT_QUERY.activeSearchState.
```

How are you supposed to use the export directive and handle the removal of typenames for the input. I could just add a optional __typename on my mutation input type but that seems hacky?

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
