### ISSUE TITLE
Apollo Client caches entire remote and local schema definition

### ISSUE THREAD

**Issue by akaNightmare** [apollographql/apollo-client#5615]
I am wondering when _typeDefs_ option is set in
```
apollo.create({
  typeDefs: gql`type Query { isLoggerIn: Boolean! }`,
  // ... other options
})
```
full schema definition appears in apollo cache and it includes remote and local schema:
![image](https://user-images.githubusercontent.com/4151616/69525391-ae1b4d00-0f70-11ea-9382-caeaf81fd5d5.png)
without `typeDefs` no schema definition in cache is stored.

**Comment by benjamn** [comment]
What is this `apollo.create` function? It's not an API that we use in the Apollo Client libraries, as far as I know.

**Comment by benjamn** [comment]
Apart from that, it looks like someone is performing a schema introspection query at runtime, and storing the results in the cache. That's typically a mistake, because most production GraphQL servers disable introspection queries in production, so obtaining this information won't be possible in production. Instead, any work involving a schema introspection query should probably be done at build time.

**Comment by akaNightmare** [comment]
@benjamn I'm using apollo-angular and codegen and 
```
fragmentMatcher: new IntrospectionFragmentMatcher({
  introspectionQueryResultData: introspectionResult
}),
```
probably this code is storing full schema in a cache. But I found that schema appears only when using local resolvers and local typeDefs.

**Comment by dylanwulf** [comment]
I've seen this before too. I believe the introspection query is done by GraphiQL in the devtools, and that shows up when inspecting the cache.

**Comment by dylanwulf** [comment]
Update: it looks like the schema only shows up in the dev tool if I have a query that uses the `@connection` directive

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-client/issues/5615#issuecomment-558330893, this sounds like the results of using AC Devtools. Thanks!
