### ISSUE TITLE
Apollo causes an extreme lag time after fetchMore

### ISSUE THREAD

**Issue by michaloslav** [apollographql/apollo-client#5620]
Take a look at [this screenshot](https://snipboard.io/hAyuaE.jpg). At around 13000 ms, fetchMore was called. That requested about 0.5 MB from the server which was downloaded in less than a second. After that though, there were about 14 seconds when Apollo was doing God knows what on the main thread. The app stayed frozen the whole time.

Here's the code:
```
dataFetch.fetchMore({
      variables: {
            sector: JSON.stringify([sectorX, sectorY])
      },
       updateQuery: (prev, { fetchMoreResult }) => {
             const result = { ...prev };

             Object.entries(fetchMoreResult)
                 .forEach(([key, values]) => {
                    result[key] = [...result[key], ...values];
                 });
        
            return result;
      }
});
```

(I timed the forEach loop with `console.time`, it takes a fraction of a millisecond to execute.)

[Here's the Chrome profile](https://www15.zippyshare.com/v/eeLX0A4i/file.html).

**Versions**
System:
    OS: Linux 5.3 Manjaro Linux
  Binaries:
    Node: 12.13.0 - /usr/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.12.1 - /usr/bin/npm
  Browsers:
    Firefox: 70.0.1
  npmPackages:
    @apollo/react-hooks: ^3.1.3 => 3.1.3 
    apollo-boost: ^0.4.4 => 0.4.4 
    apollo-cache-inmemory: ^1.6.3 => 1.6.3

Is there any other information that could be useful to you?

**Comment by benjamn** [comment]
Do you think you could put together some sort of a [reproduction](https://github.com/apollographql/apollo-client/blob/release-3.0/CONTRIBUTING.md#reporting-bugs), without using real data?

I would note that only the first ~10 seconds of the magenta part of the screenshot seem to be attributable to Apollo Client code. The link to the Chrome profile goes to a strange spammy download site, so I have to admit I haven't looked at that.

**Comment by fpirsch** [comment]
Probable explanation : https://github.com/convoyinc/apollo-cache-hermes/blob/master/docs/Motivation.md

**Comment by dylanwulf** [comment]
I wonder if it would be possible to write the cache normalization routines in a faster language than javascript and then compile them into a webassembly module for better cache performance

**Comment by fpirsch** [comment]
Or :
- don't overuse resolvers, stick to flat objects as long as possible
- use apollo-cache-hermes or wait for Apollo 3 which allows you to NOT normalize everything

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
