### ISSUE TITLE
Apollo Cache Chrome extension hangs after fetching large schema under ROOT_QUERY

### ISSUE THREAD

**Issue by ankitjaincst** [apollographql/apollo-client#5627]
Observation:
When Apollo Cache is loaded initially ROOT_QUERY does not contain schema (See image below), but once I fire a client side query/mutation whole schema appears under ROOT_QUERY and since our schema is very large, the extension hangs . The apollo extension hangs thus . Switching between Cache, Query, Graphiql, Mutation in the extension becomes very very slow , sometimes it takes more than 1 minute for the tab to be switched after clicking . This is really hampering our developer experience . We are now only relying on Graphiql for developer tooling . The cache tab int he extension is really becoming difficult to use . Why does it even need to show the whole schema under root query ? I tried the Space Launch Apollo Tutorial app but since the schema in that is not huge so the lag is not visible but once your schema really grows in size, the tab will definitely hang . This surely needs optimization or we need some config so that we can opt out of some features from extension what we feel is the cause of making it slow .

All details have also been listed here by me :
https://spectrum.chat/apollo/apollo-client/apollo-cache-chrome-extension-hangs-after-fetching-schema-under-root-query~9f52b3eb-c64f-419c-b217-c67b855859cb

On page load this is the cache shape (ROOT_QUERY does not include schema)

<img width="1678" alt="Screenshot 2019-11-28 at 9 50 54 AM" src="https://user-images.githubusercontent.com/1904936/69777576-f16ef900-11c6-11ea-8058-e841bd35035a.png">

After performing the client side mutation the schema was loaded under ROOT_QUERY and the extension hangs every time for a minute or two ->
<img width="1676" alt="Screenshot 2019-11-28 at 9 56 25 AM" src="https://user-images.githubusercontent.com/1904936/69777621-211e0100-11c7-11ea-9b6a-6a8994a63990.png">

**Intended outcome:**

Apollo Cache chrome extension should be able to handle large schemas

**Actual outcome:**

**How to reproduce the issue:**

Use apollo client with a very very large schema, and make client side mutaion , the cache tab will show a lag .

-->

**Versions**

apollo client version -> "apollo-client": "^2.6.4",
-->

**Comment by ankitjaincst** [comment]
Any update on this ? What could be the reason for slow cache ?

**Comment by hwillson** [comment]
This issue is better asked in the https://github.com/apollographql/apollo-client-devtools repo. Thanks!
