### ISSUE TITLE
GraphQl Errors not being thrown in mutate call

### ISSUE THREAD

**Issue by kanishktokopedia** [apollographql/apollo-client#5629]
**Intended outcome:**
Ideally, when a GraphQL errror comes in mutation it should be thrown.

**Actual outcome:**
The call to apolloClient.mutate is never resolved.

**How to reproduce the issue:**
The lines here: 
 https://github.com/apollographql/apollo-client/blob/65eef3730e8b3d2b66ca0fe6d88d0b579a4d31ea/packages/apollo-client/src/core/QueryManager.ts#L225

It creates an error but never rejects it as can be seen in the code written above. Although, adding the following line just below the tagged line works:
reject(error)

**Versions**
2.6.4

**Comment by Gallevy** [comment]
Same issue, did it get changed recently because i don't remember this behavior being problematic

**Comment by willipreuk** [comment]
Currently I have the problem, that an error is thrown. In my opinion it would be better to just populate the error response, returned from `useMutation`. With this approach the user can easily choose how to handle the error. I mean even the docs are describing it like this.

**Comment by mccraveiro** [comment]
@willipreuk yours seems to be another issue. Check #6070

**Comment by alessbell** [comment]
Hi @kanishktokopedia 👋  v3.x.x was released in mid-2020, and so, while I can't comment on whether this was ever resolved in v2, this seems to be fixed now (here's the relevant test case): https://github.com/apollographql/apollo-client/blob/main/src/react/hooks/__tests__/useMutation.test.tsx#L332:L373

I hope this is helpful, thanks 😊
