### ISSUE TITLE
AdBlock blocks websocket

### ISSUE THREAD

**Issue by fabicsp** [apollographql/apollo-client#5630]
1, I have created a node server, hosted on AWS what provides **GraphQL** endpoint.
2, Serving the endpoints over **https**.
3, Deployed the client to **heroku**, and trying to use the Graphql endpoint. 
 - Having queries, mutations, and **subscriptions**
 - Queries, and mutations works fine, but the **subscriptions** are blocked by adblock, but only on mac. On linux, and windows it works fine(also with adblock), and also in all other main browser.  

<img width="637" alt="Screenshot 2019-11-28 at 13 01 18" src="https://user-images.githubusercontent.com/18398619/69805004-073ce800-11e0-11ea-8a3b-c230921b8cd8.png">

**Comment by MaximeAubanel** [comment]
Loooooog shot but have you found a solution ?

**Comment by jamalavedra** [comment]
Experiencing something similar here. Regardless of the platform tho, it only works when I disable Adblock. Any workarounds?

**Comment by scorpionknifes** [comment]
Having the same issue, I'm using "AdBlock". I'm getting the same thing in Windows, Linux, mac. The same thing also occurs with firefox and chrome.

**Comment by MaximeAubanel** [comment]
Yeah it seems to be coming from AdBlock.

https://stackoverflow.com/questions/57974214/how-to-debug-websocket-connection-error-with-unknown-reason/63679166#63679166

**Comment by hwillson** [comment]
This doesn't sound like an Apollo Client issue, but if anyone thinks it is and can provide a small runnable reproduction using `@apollo/client@latest`, we'll take a look. Thanks!
