### ISSUE TITLE
Poll interval is ignored on initial load of the app

### ISSUE THREAD

**Issue by 100phel** [apollographql/apollo-client#5637]
I use apollo-client version 2.6.3 with react native. The cache policy is the default one - cache first.
I use the pollInterval option, it is equal to 8 minutes. When I close the app and open it again in, say, in 2 days, the data is stale. It is only refreshed if I stay in the app for 8 minutes.

**Intended outcome:**
On first load of the app the apollo client should understand that the data is stale and should refetch it without having to wait for poll interval. Otherwise I see the data which is 2 days old. What if I open the app again in a month? I see data which is one month old, though my poll interval is equal to 8 minutes.

**Actual outcome:**
The apollo client does not recognize that the data is stale and I have to wait for the poll interval (8 minutes) for data to be refetched.

**How to reproduce the issue:**
Use pollInterval option with useQuery hook:
```
const {
        loading: loadingStations,
        networkStatus: networkStatusStations,
        data: stationsData,
        refetch: refetchMapData
    } = useQuery(GET_ALL_STATIONS_WITH_CURRENT_OBSERVATION, {
        notifyOnNetworkStatusChange: true,
        partialRefetch: true,
        pollInterval: 1000 * 60 * 8, // 8 minutes
    });
```

**Versions**
  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
  Binaries:
    Node: 8.16.0 - /usr/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.4.1 - /usr/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 70.0.1
  npmPackages:
    apollo-cache-inmemory: ^1.6.2 => 1.6.2 
    apollo-cache-persist: ^0.1.1 => 0.1.1 
    apollo-client: ^2.6.3 => 2.6.3 
    apollo-link: ^1.2.12 => 1.2.12 
    apollo-link-error: ^1.1.11 => 1.1.11 
    apollo-link-http: ^1.5.15 => 1.5.15 
    apollo-link-state: ^0.4.2 => 0.4.2 
    react-apollo: ^3.0.1 => 3.0.1

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
