### ISSUE TITLE
Examples of cache updating conflict "Important" note

### ISSUE THREAD

**Issue by bkoltai** [apollographql/apollo-client#5650]
On the [cache interaction page of the docs](https://www.apollographql.com/docs/react/caching/cache-interaction/), there is a note about using the client to call the functions available. 

However, the [update after a mutation recipe](https://www.apollographql.com/docs/react/caching/cache-interaction/#updating-after-a-mutation) shows those functions being called on the `DataProxy` provided to the `update` method. This seems conflicting to me. If the example headed the "Important" message at the top of the doc, shouldn't the calls be something like `client.readQuery`.

Why the deviation?

**Comment by hwillson** [comment]
The cache docs have changed quite a bit since this issue was opened. Let us know if you still think there is an issue with them. Thanks!
