### ISSUE TITLE
Local resolver code errors when graphql call has errors and response code is 200

### ISSUE THREAD

**Issue by CamBurris** [apollographql/apollo-client#5656]
It seems the Apollo local resolver code is erroring out when getting graphql errors from the graph endpoint. I see the issue when I use a local (client) resolver in a query that errors out and the graph endpoint returns a 200 status code instead of a 400 status code.

**Intended outcome:**
The intended outcome should be that the error output that useQuery() returns should have the proper grpahqlErrors and networkErrors from the graph endpoint. Here is what I see in error when the status code is 400.

`{"graphQLErrors":[],"networkError":{"name":"ServerError","response":{},"statusCode":400,"result":{"errors":[{"message":"Cannot query field \"countrya\" on type \"Query\". Did you mean \"country\" or \"countries\"?","locations":[{"line":2,"column":3}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}]}},"message":"Network error: Response not successful: Received status code 400"}`

**Actual outcome:**
Here is what I see in error when the status code is 200.

`{"graphQLErrors":[],"networkError":{},"message":"Network error: Cannot read property 'countrya' of undefined"}`

**How to reproduce the issue:**
Here is a codesandbox that shows what the error is like when the response is 400.
https://codesandbox.io/s/heuristic-shadow-uw25f?fontsize=14&hidenavigation=1&theme=dark

The graph endpoint that I am using that returns a 200 status code for errors is not available to the public. Instead I have setup the sandbox with another graph endpoint that is returning 400 for the status code. To get the issue to occur, I have used a proxy to rewrite the status code to 200. In my case, I used Charles proxy on OSX. You could use Fiddler on Windows or some other proxy application.

**Versions:**
apollo-client: 2.6.4

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
