### ISSUE TITLE
`mutate<MyType>()` data should never be `undefined` in case of success

### ISSUE THREAD

**Issue by PowerKiKi** [apollographql/apollo-client#5662]
**Intended outcome:**

I want to use `client.mutate<MyType>()` in a strongly typed manner in combination with Typescript's `strictNullChecks`. I expect that in case of success the `result.data` is never `undefined` and I can access `MyType` properties without any extra checks.

**Actual outcome:**

Instead `result.data` is typed as `MyType | undefined` and Typescript compilation fails. This force me to either cast my value as `MyType`, or to specifically guard against undefined cases. Both workarounds are extra-steps that should not be necessary and defeat the purpose of typing the mutation in the first place.

The incorrect typing of `result.data` is because of it indirectly use `ExecutionResult` from `graphql`, which [defines `data` as optional](https://github.com/APIs-guru/graphql-js/blob/917921dfa7c06c7a63cd5b89ae21afe7a7966959/src/execution/execute.js#L116).

This is correct for `graphql` package, in order to differentiate between success and error. However in Apollo world the difference between success and error is not decided by the presence or absence of properties, but instead by the resolved/rejected mechanism of a promise. This is [clearly documented in Apollo source](https://github.com/apollographql/apollo-client/blob/35e405ab9154028754ed4f4d85eaddf4287f4da3/packages/apollo-client/src/ApolloClient.ts#L331-L338).

As such, in Apollo world, a success **always** have a result of `MyType`. And thus the typing as it exists today is incorrect.

We can draw a direct parallel with `client.query()`, which correctly [always have a result](https://github.com/apollographql/apollo-client/blob/35e405ab9154028754ed4f4d85eaddf4287f4da3/packages/apollo-client/src/core/types.ts#L23) in case of success.

I think a similar technique of redefining types according to Apollo needs, instead of using types of another package, should be applied for `mutate()` and possibly `subscribe()`.

**How to reproduce the issue:**

A complete reproduction case is available in https://github.com/PowerKiKi/apollo-client-issues-5662. The short version is:

```ts
const mutation = gql`
    mutation Foo {
        foo {
            bar
        }
    }
`;

client.mutate<{ foo: { bar: string; }; }>({
    mutation: mutation,
}).then(result => {
    console.log(result.data.foo.bar); // <==== Compilation will fail here
});
```

The compilation error is something similar to:

```
ERROR in src/app/app.component.ts(33,19): error TS2533: Object is possibly 'null' or 'undefined'.
```

**Versions**

```
  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
  Binaries:
    Node: 12.13.1 - /usr/bin/node
    Yarn: 1.19.2 - /usr/bin/yarn
    npm: 6.12.1 - /usr/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 70.0.1
  npmPackages:
    apollo-angular: ^1.8.0 => 1.8.0 
    apollo-cache-inmemory: ^1.6.3 => 1.6.3 
    apollo-client: ^2.6.4 => 2.6.4 
    apollo-link: ^1.2.13 => 1.2.13 
    apollo-link-schema: ^1.2.4 => 1.2.4 
```

**Comment by PowerKiKi** [comment]
A complete reproduction case is available in https://github.com/PowerKiKi/apollo-client-issues-5662

**Comment by ostrebler** [comment]
Same problem here.

**Comment by PowerKiKi** [comment]
@hwillson I would like to add this bug in the [3.0 milestone](https://github.com/apollographql/apollo-client/milestone/14), because it will probably break some typings, so it would be best to break them before 3.0 is actually released.

I will create a PR to solve this issue in the coming days.

**Comment by PowerKiKi** [comment]
When attempting to create a PR for this, I found out that `data` can legitimately be `undefined` in some cases. Thus existing typing is correct. The only improvement we can make is to mention that in documentation.

For end-user, going forward, the proper way to deal with this would be to use the [non-null assertion operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator) introduced in TypesScript 2.0, like so:


```diff
 client.mutate<{ foo: { bar: string; }; }>({
     mutation: mutation,
 }).then(result => {
-    console.log(result.data.foo.bar);
+    console.log(result.data!.foo.bar);
 });
```
