### ISSUE TITLE
Is it really necessary to pass addTypename={false} to MockedProvider?

### ISSUE THREAD

**Issue by shibayu36** [apollographql/apollo-client#5663]
[Testing React components](https://www.apollographql.com/docs/react/development-testing/testing/) document says

> You may notice the prop being passed to the MockedProvider called addTypename. The reason this is here is because of how Apollo Client normally works. When a request is made with Apollo Client normally, it adds a __typename field to every object type requested. This is to make sure that Apollo Client's cache knows how to normalize and store the response. When we're making our mocks, though, we're importing the raw queries without typenames from the component files.

> If we don't disable the adding of typenames to queries, the imported query won't match the query actually being run by the component during our tests.

but I think we don't need to pass `addTypename={false}` to MockedProvider, because [mockLink](https://github.com/apollographql/react-apollo/blob/79a2bab6501d81aca8e766824b7d2ab9186a4edc/packages/testing/src/mocks/mockLink.ts) adds `__typename` to both [mocked query](https://github.com/apollographql/react-apollo/blob/79a2bab6501d81aca8e766824b7d2ab9186a4edc/packages/testing/src/mocks/mockLink.ts#L48-L51) and [actual query](https://github.com/apollographql/react-apollo/blob/79a2bab6501d81aca8e766824b7d2ab9186a4edc/packages/testing/src/mocks/mockLink.ts#L61).  What do you think?

**Comment by hwillson** [comment]
The docs have been updated quite a bit since this issue was opened. Let us know if you still think this is an issue. Thanks!
