### ISSUE TITLE
Unhandled Rejection (Error): Network error: Response not successful: Received status code 400

### ISSUE THREAD

**Issue by alakdam07** [apollographql/apollo-client#5664]
This is my App.js 

import React from "react";
import { ApolloClient, HttpLink, InMemoryCache } from "apollo-boost";
import { ApolloProvider } from "react-apollo";
import "./App.css";
import Post from "./components/Post";
import Addpost from "./components/Addpost";

const client = new ApolloClient({
  link: new HttpLink({
    uri: "http://localhost:5000/graphql"
  }),
  cache: new InMemoryCache()
});
function App() {
  return (
    <ApolloProvider client={client}>
      <div className="App">
        <Addpost />
      </div>
    </ApolloProvider>
  );
}

export default App;

This is Addpost.js
import React, { Component } from "react";
import { gql } from "apollo-boost";
import { graphql } from "react-apollo";
import { flowRight as compose } from "lodash";

const getPerson = gql`
  {
    person {
      firstname
      lastname
      email
    }
  }
`;

const addPostMutation = gql`
  mutation {
    addpost(title: "", content: "", personid: "") {
      title
      id
    }
  }
`;

export class Addpost extends Component {
  state = {
    title: " ",
    content: " ",
    personid: " "
  };

  handleChange = e => {
    //console.log(e.target.value);
    this.setState({ [e.target.id]: e.target.value });
  };
  handleSubmit = e => {
    e.preventDefault();
    //console.log(this.state);
    this.props.addPostMutation(); 
  };
  render() {
    //console.log(this.props);
    //const{data}= this.props //this one fetch the data
    const { getPerson } = this.props; 

    return (
      <div>
        <form id="addPost" onSubmit={this.handleSubmit}>
          <div className="field">
            <label> Post name </label>
            <input type=" text" id="title" onChange={this.handleChange} />
          </div>
          <div className="field">
            <label> Content </label>
            <input type="text" id="content" onChange={this.handleChange} />
          </div>
          <div className="field">
            <label> Person: </label>
            <select id="personid" onChange={this.handleChange}>
              <option>select person</option>
              {getPerson.loading ? (
                <option disabled>getPerson loading...</option>
              ) : (
                getPerson.person.map(person => {
                  return (
                    <option key={person.id} value={person.id}>
                      {" "}
                      {person.firstname} {person.lastname}{" "}
                    </option>
                  );
                })
              )}
            </select>
          </div>
          <button>+</button>
        </form>
      </div>
    );
  }
}

export default compose(
  graphql(getPerson, { name: "getPerson" }),
  graphql(addPostMutation, { name: "addPostMutation" })
)(Addpost);

# Its run fine when I fetch the data but when I add new post it gives me error. What I am doing wrong?

**Comment by akhilvc10** [comment]
How did you fix ?

**Comment by alakdam07** [comment]
I forget it, What was the problem and how did I fixed it?

**Comment by sathishlakshs** [comment]
can you check your resolver name for that exact query?


<----backend---->
export const resolvers = {
    Query: {
        **list**: ()=> List.find()
    }
}
<-----frontend------>
client
  .query({
    query: gql`
    query {
      **list** {
          id
          name
      }
    }
    `
  })
  .then(result => console.log(result));

resolver name must be same.
this works for me

**Comment by Ezra-Siton-UIX** [comment]
I got this error for this scenario.

The schema excepted `speakerId`  Arguments.

![image](https://user-images.githubusercontent.com/16711871/95887521-9d421880-0d88-11eb-9bf4-5592d2ea1b35.png)

But I created  `helloError` instead (In the "real world" it could be `speakerid` or `speaker_Id` instead of `speakerId`:

```
const FEATURED_SPEAKER = gql`
  mutation markFeatured($speakerId: ID!, $featured: Boolean!){
    markFeatured(helloError: $speakerId , featured: $featured){
      id
      featured
    }
  }
```
Under The playground this is the error:
![image](https://user-images.githubusercontent.com/16711871/95888158-68829100-0d89-11eb-8417-d212fb1b0c3e.png)

I run the mutation on click (But the call to the mutation with `Unknown argument`):
```
const [ markFeatured ] = useMutation(FEATURED_SPEAKER);

onClick={ async() => {
  await markFeatured({ variables: {
  speakerId: id, featured: true
   }})
 }}	
```
