### ISSUE TITLE
Polling not working in background in React Native

### ISSUE THREAD

**Issue by HugoLiconV** [apollographql/apollo-client#5666]
**Intended outcome:**
Execute the query every 30 seconds even if the device is locked or if the app is in the background

**Actual outcome:**
I want to execute a query every 30 seconds so I'm using `pollInterval`. Everything works fine, except when the application goes to the background because it stops from executing the query.

This is my query: 
```javascript
	const {
		loading,
		error,
		refetch,
		data
	} = useQuery(UNDELIVERED_ORDERS, {
		variables: {
			courier: userId
		},
		pollInterval: 30000,
		fetchPolicy: "network-only"
	})
```

**How to reproduce the issue:**
Just use poll interval in React Native and press home or block the device

**Versions**

  System:
    OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.19.2 - /usr/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.4.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 70.0.1
  npmPackages:
    @apollo/react-hooks: ^3.0.1 => 3.0.1 
    apollo-boost: ^0.4.4 => 0.4.4 
    apollo-link-context: ^1.0.18 => 1.0.18 
  npmGlobalPackages:
    apollo: 2.18.3

**Comment by benjamn** [comment]
Are you saying the polling stops working even after you open the app again, or just that the polling is disabled when the app is in the background?

**Comment by HugoLiconV** [comment]
> Are you saying the polling stops working even after you open the app again, or just that the polling is disabled when the app is in the background?

The polling stop working when the app is in the background. When I open the app starts working again. I'm not sure if that's the correct behavior

**Comment by tsvetann** [comment]
For me `pollInterval` doesn't work at all. What's the best way to debug why?

**Comment by iwakoscott** [comment]
So does a `useQuery` with a `pollInterval` set run in the background if the user were to navigate to the home screen of the device? Or would it only run if the app is opened?

**Comment by HugoLiconV** [comment]
> So does a `useQuery` with a `pollInterval` set run in the background if the user were to navigate to the home screen of the device? Or would it only run if the app is opened?

For me, it's only running when I had the app opened

**Comment by EhsanSarshar** [comment]
it's not because of apollo-client. it's because your app is in background and not just apollo-client but all of codes stop running. you should find a way to run background task

**Comment by hwillson** [comment]
This doesn't sound like an Apollo Client issue, but if anyone thinks it is and can provide a small runnable reproduction using `@apollo/client@latest`, we'll take a look. Thanks!
