### ISSUE TITLE
Failing to run node server after installing SSR.

### ISSUE THREAD

**Issue by mmiedzianyy** [apollographql/apollo-client#5682]
Hello!

**Intended outcome:**

My project uses Apollo Graphql for Angular. I've installed @ng-toolkit/universal@8.03 to create SSR. After adjusting all the files in the project and finally runing express server `npm run server` but with no luck in running the application.

**Actual outcome:**
 Express server starts without any issues but I've encountered this error after opening my browser on localhost:4000:

`Error: Network error: 
    at new ApolloError (project-dir\dist\server.js:136103:26)
    at project-dir\dist\server.js:137598:34
    at project-dir\dist\server.js:138018:15
    at Set.forEach (<anonymous>)
    at project-dir\dist\server.js:138016:26
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (project-dir\dist\server.js:138014:20)
    at project-dir\dist\server.js:137493:29
    at ZoneDelegate.module.exports.ZoneDelegate.invoke (project-dir\dist\server.js:540:26)
    at Object.onInvoke (project-dir\dist\server.js:101586:33)`

**How to reproduce the issue:**
Install latest angular cli ( i.e. locally)
"@angular/core": "~8.2.14"
After creating basic app with graphql installed use latest @ng-toolkit/universal
"@ng-toolkit/universal": "^8.0.3"

run comands `npm run build:ssr && npm run server`.

**Versions**
`System:
    OS: Windows 10 10.0.18362
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    apollo-angular: ^1.6.0 => 1.8.0
    apollo-angular-link-http: ^1.8.0 => 1.9.0
    apollo-cache-inmemory: ^1.6.2 => 1.6.3
    apollo-client: ^2.6.3 => 2.6.4
    apollo-link: ^1.2.12 => 1.2.13
    apollo-link-error: ^1.1.11 => 1.1.12`

ng related versions: 
`@angular-devkit/architect                  0.803.20
@angular-devkit/build-angular              0.803.20
@angular-devkit/build-ng-packagr           0.803.20
@angular-devkit/build-optimizer            0.803.20
@angular-devkit/build-webpack              0.803.20
@angular-devkit/core                       8.3.20
@angular-devkit/schematics                 8.3.20
@angular/cli                               8.3.20
@angular/pwa                               0.803.20
@angular/service-worker                    8.0.3
@ngtools/webpack                           8.3.20
@nguniversal/common                        8.1.0
@nguniversal/express-engine                8.2.6
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        8.3.20
@schematics/update                         0.803.20
ng-packagr                                 5.7.1
rxjs                                       6.4.0
typescript                                 3.5.3
webpack                                    4.39.2`

I hope this issue fails under apollo graphql coverage.
I sought help on ng-toolkit related topics but with no solutions so far.

Cheers!

**Comment by hwillson** [comment]
This issue is better raised in the https://github.com/kamilkisiela/apollo-angular repo - thanks!
