### ISSUE TITLE
(apollo-boost) Broken link in documentation

### ISSUE THREAD

**Issue by FMGordillo** [apollographql/apollo-client#5685]
**Intended outcome:**
Click the link and go to the desired place

**Actual outcome:**
404 not found.

**How to reproduce the issue:**
At the end of [*this document*](https://github.com/apollographql/apollo-client/tree/master/packages/apollo-boost) you can see a link pointing [*here*](https://www.apollographql.com/docs/react/essentials/get-started.html#configuration-options) but it does not exist.

**Versions**
N/A

**Comment by FMGordillo** [comment]
Proposal: It should point [*here*](https://www.apollographql.com/docs/react/get-started/#configuration-options)

**Comment by abrahamcuenca** [comment]
commit looks good in #5756 but the Contributor License Agreement (CLA) has to be accepted. You can accept it here: https://contribute.apollographql.com/

**Comment by the-bionic** [comment]
HI @abrahamcuenca, I accepted that already. Please confirm.

**Comment by hwillson** [comment]
The docs have been updated quite a bit since this issue was opened. Let us know if you still think this is an issue. Thanks!
