### ISSUE TITLE
Angular client in docs

### ISSUE THREAD

**Issue by Eraldo** [apollographql/apollo-client#5691]
Why is the angular client no longer linked as a main client choice in the main docs?

The `APOLLO PLATFORM` dropdown shows me a react option but no angular option.

<img width="714" alt="Screenshot 2019-12-14 at 20 27 25" src="https://user-images.githubusercontent.com/73378/70854181-2f02a000-1eb0-11ea-9bab-275c1e86a25b.png">

Would you please be so kind as to inform me what is going on?

**Comment by tnishimura** [comment]
I'd like to know this as well.  Are we to understand that this means the apollo angular client is being deprecated or something? graphql-tools is not in the list either and it is very confusing.

**Comment by abdonrd** [comment]
I would also like there to be some generic documentation, and not so coupled to React. Thanks!

**Comment by 1thrasher** [comment]
I asked this question at the 2020 GraphQL Summit, and received this reply from from @hwillson:

> The Angular project is community maintained and was fully transferred to Kamil a little while back, but he's definitely still supporting it. While the project was originally part of the apollographql org, we're unfortunately way too understaffed to keep maintaining everything we would like to. Kamil has done an amazing job with that project, so it's definitely still a great way to integrate Apollo with Angular!

> We've decided to focus on React as the main view layer we support out of the box (since that's what we use the most ourselves), but we'll continue to make sure Apollo Client works well with other view layers as well. If there were more hours in the day, we'd love to have official out of the box support for Angular, Vue, and Svelte to name a few - fortunately the community has been creating and maintaining amazing Apollo integrations!

The Angular docs are found here: https://github.com/kamilkisiela/apollo-angular

**Comment by Eraldo** [comment]
Thank you for the update. 👍🏽

Kamil links to the documentation: https://www.apollographql.com/docs/angular/
![Screenshot_20200731-120805~3](https://user-images.githubusercontent.com/73378/89030559-9fb7d900-d328-11ea-9933-7be6f2776206.png)

And there it looks like the main menu has Angular as an option:
![Screenshot_20200731-120815~3](https://user-images.githubusercontent.com/73378/89030580-ac3c3180-d328-11ea-9e9b-a24a58007d74.png)

But when I open up the menu there is no such option:
![Screenshot_20200731-120820~2](https://user-images.githubusercontent.com/73378/89030613-b78f5d00-d328-11ea-9b8a-8d5e7887585e.png)

I think this is confusing from an ui/ux standpoint. 😞 

I would wish for the angular client option to be listed, so I can go back and forth as I am used to from a menu.
Thanks! 👍

**Comment by hwillson** [comment]
Here are the official docs: https://apollo-angular.com/docs/
