### ISSUE TITLE
Better handling of readQuery not found

### ISSUE THREAD

**Issue by developdeez** [apollographql/apollo-client#5695]
It returns "Invariant Violation: Can't find field...." but should return null or anything more useful than a crash because the data isnt there yet.

**Comment by eduplus** [comment]
My workaround for this was to try catch it, but agree - returning null would be better.

**Comment by dylanwulf** [comment]
Duplicate of https://github.com/apollographql/apollo-feature-requests/issues/1

**Comment by hwillson** [comment]
Closing as a dupe (details in https://github.com/apollographql/apollo-client/issues/5695#issuecomment-571644605). Thanks!
