### ISSUE TITLE
updateQuery previousResult may be undefined

### ISSUE THREAD

**Issue by bradleyayers** [apollographql/apollo-client#5703]
**Intended outcome:**

The type for the `updateQuery` function in `subscribeToMore` options claims that the first parameter (`previousResult`) is `TData | undefined`, or it stays as `TData` but `updateQuery` isn't called if the previous result is `undefined`.

This also affects `updateQuery` from `fetchMore`.

**Actual outcome:**

`updateQuery` can be called with `previousResult` of `undefined`. This means we see runtime exceptions due to not handling the undefined case.

- [`QueryManager#updateQuery()`](https://github.com/apollographql/apollo-client/blob/c44e8211268e808106e81da7665f65f81fac2baf/packages/apollo-client/src/core/ObservableQuery.ts#L539) (calls ↓)
- [`QueryManager#getQueryWithPreviousResult()`](https://github.com/apollographql/apollo-client/blob/65eef3730e8b3d2b66ca0fe6d88d0b579a4d31ea/packages/apollo-client/src/core/QueryManager.ts#L1077) **Bug:** return type for [`previousResult` is `any`](https://github.com/apollographql/apollo-client/blob/65eef3730e8b3d2b66ca0fe6d88d0b579a4d31ea/packages/apollo-client/src/core/QueryManager.ts#L1057). This is where type safety is lost. (calls ↓)
- [`QueryManager#getCurrentQueryResult`](https://github.com/apollographql/apollo-client/blob/65eef3730e8b3d2b66ca0fe6d88d0b579a4d31ea/packages/apollo-client/src/core/QueryManager.ts#L1021) correctly returns `TData | undefined`.

**How to reproduce the issue:**

This happens when an event from `subscribeToMore` is received before the first query result has returned. In this case `updateQuery` is called, but there is no previous result, so `undefined` is passed in.

**Versions**

apollo-client 2.6.4

**Comment by richardscarrott** [comment]
I've experienced this same issue using `fetchMore` when the query variables change before the request has completed, e.g. the user changes a date range for the query. Additionally the network status get's set to 'ready' even though the newer request is still pending.

**Comment by FedeBev** [comment]
I'm facing the same issue.

Is there a workaround waiting for the fix?

Thanks

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
