### ISSUE TITLE
Correct type for ApolloError.graphqlErrors

### ISSUE THREAD

**Issue by keesvanlierop** [apollographql/apollo-client#5704]
Currently the type for ApolloError.graphqlErrors is:

```public graphQLErrors: ReadonlyArray<GraphQLError>```

**Intended outcome:**

**Actual outcome:**

I would expect it to be

```public graphQLErrors: ReadonlyArray<GraphQLFormattedError>```

Additionally, GraphQLFormattedError is a generic type, which allows to pass the `.extensions` record type

**Versions**

version 2.6.4, but also >3

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
