### ISSUE TITLE
Leak in OptimisticCacheLayer on mutations

### ISSUE THREAD

**Issue by francisu** [apollographql/apollo-client#5706]
**Intended outcome:**

Performance does not slow down when doing hundreds of mutations.

**Actual outcome:**

Performance slows down dramatically after many mutations due to many layers of nested OptimisticCacheLayer objects.

**How to reproduce the issue:**

I have a test case that makes this happen. I will look at your tests to see if I can easily add this. 

A PR is forthcoming, as the fix is simple. inMemoryCache.performTransaction, in the finally block, it needs to say "this.data = this.optimisticData = data" instead of "this.data = data". This makes sure the optimisticData field is correctly in sync.

In the current code, it's not reset, so when creating a new OptimisticCacheLayer, it winds up being nested against the previously discarded layer (because is chains it with a stale value of this.optimisticData). This just accumulates until the performance is unmanagable.

**Versions**

 System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v8.15.0/bin/npm
  Browsers:
    Chrome: 79.0.3945.79
    Firefox: 71.0
    Safari: 13.0.4
  npmPackages:
    apollo-cache: ^1.3.4 => 1.3.4 
    apollo-cache-inmemory: ^1.6.5 => 1.6.5 
    apollo-client: ^2.6.8 => 2.6.8 
    apollo-link: ^1.2.13 => 1.2.13 
    apollo-link-context: ^1.0.19 => 1.0.19 
    apollo-link-http: ^1.5.16 => 1.5.16 
    apollo-link-retry: ^2.2.15 => 2.2.15 
    apollo-server: ^2.9.14 => 2.9.14 
    apollo-server-lambda: ^2.9.14 => 2.9.14 
    apollo-tracing: ^0.8.9 => 0.8.9 
    apollo-utilities: ^1.3.3 => 1.3.3

**Comment by benjamn** [comment]
Is `cache.removeOptimistic` ever getting called in your use case? I ask because `performTransaction` is not intended to discard the optimistic layer when the transaction is finished. Optimistic layers are supposed to stack up (until you remove them), because you can have multiple mutations with optimistic updates pending at the same time.

I should also mention that this code has change dramatically in [Apollo Client 3.0 (beta)](#5116), available via the `@apollo/client` package, in case you have a chance to try that.

**Comment by francisu** [comment]
Thanks for your fast response. I see that my proposed fix is incorrect. `cache.removeOptimistic` is indeed being called as expected. The problem is that is calls `performTransaction` passing the `optmisticId`, which causes a new `OptimisticCacheLayer` to be created. If I remove the `optimisticId` parameter from the `performTransaction` call, then the problem appears to be fixed.

I'm happy to make a PR and see if I can make a test case for this, however, I'm having a build problem that I need help with:

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
