### ISSUE TITLE
Warnings about heuristics fragment matching when no-cache is set for requests

### ISSUE THREAD

**Issue by avkonst** [apollographql/apollo-client#5707]
**Intended outcome:** and **Actual outcome:**

- I have got Apollo client setup with caching disabled:
```
defaultOptions: {
                watchQuery: {
                    fetchPolicy: 'no-cache'
                },
                query: {
                    fetchPolicy: 'no-cache'
                },
                mutate: {
                    fetchPolicy: 'no-cache'
                }
            }
```

- None of my queries/mutations/subscriptions enable it per query. 

- `InMemoryCache` is setup with `addTypename: false`.

One of my queries returns union type.

**Actual behaviour**: Apollo client warns about heuristics on fragments matching.

I followed the suggestion and documentation and setup `IntrospectionFragmentMatcher`, which required to turn on `addTypename`, which is breaking change for my app. So, I postponed this fix for a moment.

After debugging a bit the source of the warning about heuristics on fragment matching, I was surprised to find out that they are coming from `InMemoryCache`.

**Expected behaviour**: I expect the cache should NOT interfere with the request/response data, if it is disabled with `no-cache` option. So, there should not be warning coming from `InMemoryCache` if the cache is disabled.

**How to reproduce the issue:**
- Set `InMemoryCache` with `addTypename: false`
- Do not setup `IntrospectionFragmentMatcher`
- execute a query which returns union type
- observe warnings in the console

**Versions**
```
  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
  Binaries:
    Node: 10.16.3 - /usr/bin/node
    Yarn: 1.19.1 - ~/Projects/opensource/nfl/nf-frontend/node_modules/.bin/yarn
    npm: 6.9.0 - /usr/bin/npm
  Browsers:
    Chrome: 78.0.3904.70
    Firefox: 71.0
  npmPackages:
    @apollo/react-common: 3.1.3 => 3.1.3 
    @apollo/react-hooks: 3.1.3 => 3.1.3 
    apollo: 2.21.0 => 2.21.0 
    apollo-cache-inmemory: 1.6.3 => 1.6.3 
    apollo-client: 2.6.4 => 2.6.4 
    apollo-link: 1.2.13 => 1.2.13 
    apollo-link-error: 1.1.12 => 1.1.12 
    apollo-link-ws: 1.0.19 => 1.0.19 
    apollo-upload-client: 11.0.0 => 11.0.0
```

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
