### ISSUE TITLE
@skip and @include lead to "field not found" error if skipped or not included field is not present

### ISSUE THREAD

**Issue by barbalex** [apollographql/apollo-client#5710]
I have this simplified query:

```
query Test($isGardener: Boolean!) {
  herkunft {
    id
    nr
    lokalname @skip(if: $isGardener)
  }
}
```

The backend is a hasura instance where users with role `gardener` are only permitted to access `id` and `nr`. Other users can access all fields.

**Intended outcome:**
When `$isGardener` is true the query should return the data for fields `id` and `nr` regardless whether `lokalname` exists.

As explained in https://www.apollographql.com/docs/apollo-server/schema/directives/#default-directives I would expect apollo to ignore the skipped fields.

**Actual outcome:**
This error is logged:
```
GraphQL error: field "lokalname" not found in type: 'herkunft'
```
and the query returns `undefined`.

The exact same happens if `@include` is used.

**How to reproduce the issue:**
I am not sure what the consequences of not permitting a role to access a field in hasura are. So I am not sure if this is an appropriate representation but it is the best I managed: https://codesandbox.io/s/apollo-client-error-template-7oy9t

That may also explain why in the codesandbox example above error does not seem to appear. But the data returned is `undefined`.

I noticed that when the skipped field is added to the graphql schema data is returned.

**Versions**
System:
  OS: Windows 10 10.0.18363
Binaries:
  Node: 13.2.0 - C:\Program Files\nodejs\node.EXE
  Yarn: 1.19.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Edge: 44.18362.449.0
npmPackages:
  apollo-cache-inmemory: 1.6.5 => 1.6.5
  apollo-client: 2.6.8 => 2.6.8
  apollo-link: 1.2.13 => 1.2.13
  apollo-link-context: 1.0.19 => 1.0.19
  apollo-link-http: 1.5.16 => 1.5.16

**Comment by goktugerce** [comment]
I experience the exact same problem. Were you able to fix it or find a workaround, @barbalex?

I want to skip some fields for specific roles because they do not have select permissions for the said fields. I do not want to create multiple queries and calling them based on role, but if this is a bug I will have to do that.

**Comment by barbalex** [comment]
@goktugerce 

> I do not want to create multiple queries and calling them based on role, but if this is a bug I will have to do that

That is what I had to do

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
