### ISSUE TITLE
Where does the setContext import come from?

### ISSUE THREAD

**Issue by saschametz** [apollographql/apollo-client#5716]
I want to test the V3 client and on [this page](https://www.apollographql.com/docs/react/v3.0-beta/networking/authentication/#header) there is no hint where `setContext` import comes from. I thought it comes from the `@apollo/client` library but it doesn't.

**Comment by snazzypants** [comment]
I was just looking for this took. It looks like the update to the docs are in an open PR, I used the example code in "Customizing request logic" and it worked with 3.0.0-beta.14

https://github.com/apollographql/apollo-client/pull/5480/files#diff-f0650f292f209edfff0b1e1aafe8b850

**Comment by jthistle** [comment]
I had the same problem, and ended up using the `setContext` from [`apollo-link-context`](https://www.npmjs.com/package/apollo-link-context) with `3.0.0-beta.4`. This worked fine.

**Comment by saschametz** [comment]
Thanks @snazzypants 
Docs are fixed in #5480

**Comment by cryptedx** [comment]
I have imported it from @apollo/link-context (@apollo/link-context@2.0.0-beta.3)
