### ISSUE TITLE
connectToDevTools not in PresetConfig type definition

### ISSUE THREAD

**Issue by MitchK** [apollographql/apollo-client#5720]
I was following this guide to use the Apollo Tools of React Native Debugger: https://www.apollographql.com/docs/react/development-testing/developer-tooling/#configuration

However, it seems that ```connectToDevTools``` is no defined in the ```PresetConfig``` type definition.

**Intended outcome:**
My TypeScript code using ```connectToDevTools``` should compile correctly.

**Actual outcome:**
My TypeScript code using ```connectToDevTools``` does not compile correctly:
```
Argument of type '{ uri: string; connectToDevTools: boolean; request: (operation: Operation) => Promise<void>; }' is not assignable to parameter of type 'PresetConfig'.
  Object literal may only specify known properties, and 'connectToDevTools' does not exist in type 'PresetConfig'.ts(2345)
```

**How to reproduce the issue:**
Initialize ApolloClient using:
```
...
const client = new ApolloClient({
  uri: endpoints.GRAPHQL,
  connectToDevTools: true,
});
```

**Versions**
```
npx: installed 1 in 1.785s

  System:
    OS: macOS 10.15.1
  Binaries:
    Node: 13.3.0 - ~/brew/bin/node
    Yarn: 1.19.2 - ~/***/node_modules/.bin/yarn
    npm: 6.13.4 - ~/brew/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 70.0.1
    Safari: 13.0.3
  npmPackages:
    @apollo/react-hooks: ^3.1.1 => 3.1.3 
    @apollo/react-testing: ^3.1.1 => 3.1.3 
    apollo: ^2.21.2 => 2.21.2 
    apollo-boost: ^0.4.7 => 0.4.7 
    react-apollo: ^3.1.1 => 3.1.3 
```

**Comment by MitchK** [comment]
I just noticed that ApolloClient (from apollo-boost) is different than the ApolloClient from apollo-client.

I did https://www.apollographql.com/docs/react/migrating/boost-migration/

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
