### ISSUE TITLE
[v3.0.0-beta.16] cache.clearStore() is not working

### ISSUE THREAD

**Issue by numToStr** [apollographql/apollo-client#5725]
`clearStore()` from the `useApolloContext()` is not clearing the store.

### Example
I am using a similar setup like the below code.

```tsx
const Logout = () => {
     const client = useApolloClient();

    const handleLogout = () => {
        // This is not working
        client.clearStore();
    }

    return (
        <Button onClick={handleLogout}>Logout</Button>
    )
}
```

**Comment by dmitry** [comment]
Do you have:

```
      <ApolloProvider client={client}>
        <App />
      </ApolloProvider>
```
?

**Comment by numToStr** [comment]
> Do you have:
> 
> ```
>       <ApolloProvider client={client}>
>         <App />
>       </ApolloProvider>
> ```
> 
> ?

Yes.

**Comment by hwillson** [comment]
@numToStr - I've verified `clearStore` is working properly with `@apollo/client@3.0.0-beta.22`. Please note that `clearStore` returns a `Promise`, so maybe double check that you're waiting for the Promise to resolve before verifying the cache has been emptied. Thanks!
