### ISSUE TITLE
SSR rehydration docs are unsafe and slow

### ISSUE THREAD

**Issue by zsolt-dev** [apollographql/apollo-client#5727]
The docs shows this as an example:

```
<script>
  window.__APOLLO_STATE__ = JSON.stringify(client.extract());
</script>
```

This approach is:
1. unsafe -> allows for XSS, like injection </script tag etc
2. slow. Using JS literals for parsing JSON is expensive.  Almost 2x faster approach is using JSON.parse(jsonAsString), as shown here: https://v8.dev/blog/cost-of-javascript-2019#json

Proposed update for the docs:

```
function stringifyToScriptTag(str) {
  const stringyfied = JSON.stringify(str)
    .replace(/</g, '\\u003c') // to remove <scripts
    .replace(/\\/g, '\\\\') // to escape \
    .replace(/\'/g, "\\'"); // to escape single quotes
  return `'${stringyfied}'`;
}

<script dangerouslySetInnerHTML={{
  __html: `window.__APOLLO_STATE__=JSON.parse(${stringifyToScriptTag(client.extract())});`,
}}
/>
```

**Comment by hwillson** [comment]
The docs have been updated quite a bit since this issue was opened. Let us know if you still think this is an issue. Thanks!
