### ISSUE TITLE
Save an interest list - pass an array parameter to a mutation 

### ISSUE THREAD

**Issue by Pablo14697** [apollographql/apollo-client#5728]
Hello everyone! 
I just wanna know how to pass an array to a mutation.
In my app I have an interest list that I want to save it, then I don't know how to define the type of parameter

The next code is the mutation: 
```export const mutation = gql`
  mutation saveP($input: [inputProject]) {
    saveProject(
      input: $input
    )
  }
`;```

The "saveP($input: [inputProject])"  text is the problem. I don't know how to say to the mutation that the paremeter is an array like  **[{ name: "Policies", id: "1" }, { name: "Food", id: "2" }]**

**Comment by dylanwulf** [comment]
Issues on this GitHub repo are reserved for bug reports only. If you have questions about how to use Apollo Client, please ask on [Spectrum](https://spectrum.chat/apollo/apollo-client?tab=posts) or StackOverflow.
