### ISSUE TITLE
Invariant Violation: 16

### ISSUE THREAD

**Issue by developdeez** [apollographql/apollo-client#5730]
Not much data on these types of error. Not sure why they keep happening.

**Comment by brentguistwite** [comment]
@developdeez I'm assuming you're using react hooks(useQuery, useMutation)? I've run into this before and it was due to having conflicting versions of react and/or react-dom. I was important a component which used `useQuery` from a library but the package I was working in had a different version of React. Pinning the versions fixed it for me.

**Comment by IAmBrandonMcGregor** [comment]
I'm seeing this error reported via through our Sentry instance. We're not using React. Instead, we're using the Apollo Client directly.  Our versions are…
```
"apollo-cache-inmemory": "^1.6.3",
"apollo-client": "^2.6.4",
"apollo-link": "^1.2.13",
"apollo-link-context": "^1.0.19",
"apollo-link-error": "^1.1.12",
"apollo-link-http": "^1.5.16",
"apollo-link-ws": "^1.0.19",
"apollo-utilities": "^1.3.2",
```

**Comment by IAmBrandonMcGregor** [comment]
Bumped our libs and still seeing this issue.

**From our package.json**
```
"apollo-cache-inmemory": "^1.6.5",
"apollo-client": "^2.6.8",
"apollo-link": "^1.2.13",
"apollo-link-context": "^1.0.19",
"apollo-link-error": "^1.1.12",
"apollo-link-http": "^1.5.16",
"apollo-link-ws": "^1.0.19",
"apollo-utilities": "^1.3.3",
```

**Error Details**
```
Invariant Violation: Invariant Violation: 16 (see https://github.com/apollographql/invariant-packages)
  at new n(../../node_modules/ts-invariant/lib/invariant.esm.js:12:28)
  at ? (../../node_modules/apollo-client/bundle.esm.js:1420:60)
  at Map.forEach(<anonymous>)
  at clearStore(../../node_modules/apollo-client/bundle.esm.js:1419:34)
  at ? (../../node_modules/apollo-client/bundle.esm.js:2058:59)
```

**Comment by mcclowes** [comment]
Also seeing this. Not using `apollo-client`, and have checked the versions of `react`/`react-dom` are consistent

**Comment by ivan-kleshnin** [comment]
Invariant Violation: 47 rarely but systematically occurs since update to the latest apollo (3.1.0)
😞

**Comment by punksta** [comment]
having `Invariant Violation: 20 (see https://github.com/apollographql/invariant-packages)` in clearStore.

`@apollo/client:3.1.3`

**Comment by hwillson** [comment]
https://github.com/apollographql/apollo-client/pull/6665 was merged to help with troubleshooting errors like this. Thanks!
