### ISSUE TITLE
Store reset while query was in flight (not completed in link chain)

### ISSUE THREAD

**Issue by developdeez** [apollographql/apollo-client#5731]
I get this randomly in my Apollo Client code. I'm using the anti-pattern of surrounding all setState with an isMounted flag to prevent attempts to set the state when a component is unmounted or a user is leaving a page. But I still get this

Store reset while query was in flight (not completed in link chain)
What gives?

https://stackoverflow.com/questions/59497574/preventing-store-reset-while-query-was-in-flight-not-completed-in-link-chain

**Comment by lurifaxel** [comment]
Same for me. Sure would like to know how to get rid of it...

**Comment by hwillson** [comment]
This should no longer be an issue in `@apollo/client@latest` - let us know otherwise, thanks!
