### ISSUE TITLE
DataProxy types improvement for required variables

### ISSUE THREAD

**Issue by quentinus95** [apollographql/apollo-client#5735]
Hi,

The current implementation of `Query` in `DataProxy` is as follow:

```ts
interface Query<TVariables> {
  query: DocumentNode;
  variables?: TVariables;
}
```

This creates many difficulties to keep applications type safe when there are variables that are actually required. Even if some types are passed to `TVariables`, it will still be optional due to the `?`, while the developer expects that variables are not optional (otherwise he would not pass a value for `TVariables`, or would use `TVariables | undefined`).

I suggest to change those types to the following:

```ts
type QueryBase = {
  query: DocumentNode;
}

type Query<TVariables = undefined> = TVariables extends undefined
    ? QueryBase
    : QueryBase & { variables: TVariables; }
```

This example would prevent variables to be omitted when they are required.

As I'm not a TypeScript expert, I would appreciate some feedback, and if this change seems relevant I will be happy to open a pull request.

Thanks!

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
