### ISSUE TITLE
Querying for the same resource twice while one request is not yet finished

### ISSUE THREAD

**Issue by omerman** [apollographql/apollo-client#5739]
First things first - Thanks for this amazing library, I love it. love the entire apollo products and architectures!

Now to the matter in hand, 
Regarding issue #956 - "Don't request the same query twice while in flight"
So I've seen that it is closed and a PR was made, thats great! The way I see it, apollo dedups queries to the server(!)

But I can confirm that after building an async resolver on the client(!) (for a schema type that lives only in the client side), the resolver was called twice for the same query and not waiting for the first to finish, I believe it should not happen and that it is a bug, since #956 is pretty much the same thing just for resources in the client.

Looking forward for your response, Thanks

**Comment by chughes87** [comment]
@omerman why was this closed?

**Comment by omerman** [comment]
To tell you the truth, I cant remember, sorry 😐
