### ISSUE TITLE
v3.0.0-beta.16 ApolloLink does not support Promises function?

### ISSUE THREAD

**Issue by simoneTheNewBlack** [apollographql/apollo-client#5740]
Just wondering what is the alternative way to get result from promise function in ApolloLink, since both **.then()** & **async wait** does not work in **ApolloLink**

```
const authLink = new ApolloLink((operation, forward) => {
    operation.setContext(({ headers = {} }) => {
        AsyncStorage.getItem("token").then(token => {
            return {
                headers: {
                    ...headers,
                    token,
                }
            }
        })
    });
    return forward(operation);
});
```

```
const authLink = new ApolloLink((operation, forward) => {
    operation.setContext(async ({ headers = {} }) => {
        const token = await AsyncStorage.getItem("token");
        return {
            headers: {
                ...headers,
                token,
            }
        }
    });
    return forward(operation);
});
```

**Comment by dylanwulf** [comment]
I don't think this was supported in v2 either. If you need help creating a custom Apollo Link, please refer to the [Documentation](https://www.apollographql.com/docs/link/overview/), or ask the [Spectrum Community](https://spectrum.chat/apollo/apollo-client?tab=posts)

**Comment by vincentbello** [comment]
@simoneTheNewBlack Did you end up figuring this out?

**Comment by simoneTheNewBlack** [comment]
@vincentbello 

yea man, by using **setContext** from **apollo-link-context**
