### ISSUE TITLE
refetch() doesn't update loading

### ISSUE THREAD

**Issue by StefanYohansson** [apollographql/apollo-client#5743]
**Intended outcome:**

I am using `refetch` from `useQuery` hook in order to retry if something fails or timeout (remote graphql taking too long).

**Actual outcome:**

`refetch` triggers the new request but didn't update the loading state variable. If I put the option `notifyOnNetworkStatusChange` to true, it will update the loading state variable.

Is it the correct behavior? if yes, why?

**How to reproduce the issue:**

```
import React from 'react';
import { useQuery } from '@apollo/react-hooks';

const MyDummyComponent = () => {
    const { loading, error, refetch, data } = useQuery(/* ... */);
    if (loading) return (<Loading />);
    if (error && !data) return (<LoadingError onRetry={refetch} />);
    return null;
}

```

**Versions**

```
  System:
    OS: Linux 5.0 KDE neon 5.17
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.21.0 - ~/.nvm/versions/node/v12.13.1/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Browsers:
    Chrome: 78.0.3904.70
    Firefox: 70.0
```

**Comment by StefanYohansson** [comment]
For now, creating a file to wrap those apollo/react-hooks functions and inject that option is the way to go for me (only find/replace imports across the project). But I really want to understand if it is the expected behavior and why

```
import {
	useQuery as runQuery,
	useLazyQuery as runLazyQuery,
} from '@apollo/react-hooks';

export * from '@apollo/react-hooks';

export const useQuery = (query, options = {}) => {
	const patchedOptions = {
		notifyOnNetworkStatusChange: true,
		...options,
	};
	return runQuery.apply(null, [query, patchedOptions]);
}

export const useLazyQuery = (query, options) => {
	const patchedOptions = {
		notifyOnNetworkStatusChange: true,
		...options,
	};
	return runLazyQuery.apply(null, [query, patchedOptions]);
};
```

**Comment by migueloller** [comment]
I believe this is by design as one might want to show a different UI depending on whether it's the first load or if it's a refetch. If you read the `networkStatus` property from the object returned by `useQuery` you can use the different values.

See [this file](https://github.com/apollographql/apollo-client/blob/450b05ed6d4a1836289f1e5868812ea2f6cccbb1/src/core/networkStatus.ts) for an explanation of each value.

**Comment by mschipperheyn** [comment]
@migueloller That has not been working for us for a while now on 3.0.0. refetching seems to be broken. refetchQueries also doesn't work reliably

**Comment by migueloller** [comment]
@mschipperheyn, perhaps what you're seeing is related to https://github.com/apollographql/apollo-client/issues/5916?

**Comment by mschipperheyn** [comment]
@migueloller we see this also if we don't use `partialRefetch`

**Comment by migueloller** [comment]
Hmm, so I believe that `loading` doesn't change by design. But are you not seeing `networkStatus` change? You might have to provide the `notifyOnNetworkStatusChange` option. More info [here](https://www.apollographql.com/docs/react/data/queries/#inspecting-loading-states).

**Comment by mschipperheyn** [comment]
@miguelocarvajal that's right, no `networkStatus` change, even with `notifyOnNetworkStatusChange: true`.
More importantly, no rerender with updated data, even though the network query does execute and return correctly.

**Comment by hwillson** [comment]
This should no longer be an issue in `@apollo/client@latest` - let us know otherwise, thanks!
