### ISSUE TITLE
Updating "apollo-client" to 2.6.8 from 2.6.4

### ISSUE THREAD

**Issue by SanthoshBanavath** [apollographql/apollo-client#5745]
I am getting this error while updating the versions of apollo-client from 2.6.4 to 2.6.8.
![apollo-client](https://user-images.githubusercontent.com/30873933/71721705-17359080-2e4c-11ea-89fb-643c4b0368a1.PNG)
These are versions I am at:
    "apollo-cache-inmemory": 1.6.5,
    "apollo-client": 2.6.8,
    "apollo-link-error": 1.1.11,
    "apollo-link-http": 1.5.16

What are the possible reasons for this?

**Comment by hwillson** [comment]
This doesn't sound like an Apollo Client issue, but if anyone thinks it is and can provide a small runnable reproduction using `@apollo/client@latest`, we'll take a look. Thanks!
