### ISSUE TITLE
delete cache by operation name?

### ISSUE THREAD

**Issue by x-wk** [apollographql/apollo-client#5760]
`query pageQueryProducts($page: Int, $perPage: Int, $filter: ProductFilter) {
   products(page: $page, perPage: $perPage, filter: $filter) {
      count
      items {
         id
         productName
      }
      pageInfo {
         perPage
         currentPage
      }
   }
}`
Is there any way to delete cache by "pageQueryProducts"?

**Comment by benjamn** [comment]
Assuming you're using `@apollo/client@3.0.0-beta.19`, you should be able to do this:
```ts
cache.evict("ROOT_QUERY", "products")
```
If the `pageQueryProducts` query had more than one root field, you could call `cache.evict` for each field. Does that help?

**Comment by x-wk** [comment]
Nice, it works for me. I will upgrade to 3.x

**Comment by ArnaudBarre** [comment]
This works but does not trigger a re-render if the query is displayed. Any idea how to do it?

**Comment by hwillson** [comment]
This should no longer be an issue in `@apollo/client@latest` - let us know otherwise, thanks!
