### ISSUE TITLE
Generic type 'FetchResult' requires between 0 and 2 type arguments.

### ISSUE THREAD

**Issue by mrdulin** [apollographql/apollo-client#5774]
**Intended outcome:**

Should not throw a type error

**Actual outcome:**

> ERROR in ../node_modules/apollo-client/core/QueryManager.d.ts:73:117 - error TS2707: Generic type 'FetchResult' requires between 0 and 2 type arguments.
 73     observeQuery<T>(queryId: string, options: WatchQueryOptions, observer: Observer<ApolloQueryResult<T>>): Promise<FetchResult<T, Record<string, any>, Record<string, any>>>;
     

**How to reproduce the issue:**

When compiling the code, the `tsc` will throw this error. Here is the minimal reproduce code repo: https://github.com/mrdulin/angular-apollo-starter

**Versions**

```bash
☁  angular-apollo-starter [master] ⚡  npx envinfo@latest --preset apollo --clipboard
npx: installed 1 in 3.423s

  System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 73.0.3683.103
    Safari: 12.1
  npmPackages:
    apollo-angular: ^1.8.0 => 1.8.0 
    apollo-angular-link-http: ^1.9.0 => 1.9.0 
    apollo-cache-inmemory: ^1.6.5 => 1.6.5 
    apollo-client: ^2.6.8 => 2.6.8 
    apollo-link-context: ^1.0.19 => 1.0.19 
    apollo-link-error: ^1.1.12 => 1.1.12 
    apollo-link-ws: ^1.0.19 => 1.0.19 
    apollo-upload-client: ^12.1.0 => 12.1.0 
```

**Comment by bocong** [comment]
@mrdulin did you find a workaround to this? running into the same issue.

**Comment by ChrisKaun** [comment]
Got the exact same issue, anyone found a solution?
```
    "@angular/common": "^8.2.14",
    "apollo-angular": "^1.8.0",
    "apollo-angular-link-http": "^1.8.0",
    "apollo-cache-inmemory": "^1.3",
    "apollo-client": "^2.6.8",
    "apollo-link": "^1.2.13",
    "apollo-link-context": "^1.0",
    "apollo-link-error": "^1.1",
```

**Comment by tobmatth** [comment]
@bocong @ChrisKaun See this issue on apollo-link: https://github.com/apollographql/apollo-link/issues/616
