### ISSUE TITLE
Apollo useSubscription behaviour on error

### ISSUE THREAD

**Issue by hmeerlo** [apollographql/apollo-client#5775]
I have a useSubscription hook which works correctly but after 60 seconds the server decides to terminate the subscription (reason is not important, this is something that might just happen). How can I now resubscribe again? I know the error is set in the return value of the useSubscription call, but I have no clue how to resubscribe.

It is a simple component which shows logging of a Kubernetes pod:

```javascript
const Logs: React.FunctionComponent<Props> = props => {
  const { data, error } = useInstanceLogsSubscription({
    variables: { runid: props.namespace, pod: props.pod },
  });

  //WHAT TO DO WHEN ERROR IS SET??

  const logRef = useRef('');

  useMemo(() => {
    if (data) logRef.current += data.instanceLogs + '\r\n';
    if (error) logRef.current += error.message + '\r\n';
  }, [data, error, logRef]);

  return (
    <div className="sciui-card sciui-m-l sciui-p-l sciui-bg-p-5">
      <Log>{logRef.current}</Log>
    </div>
  );
};
```

**Comment by sshkalikov** [comment]
Same question.
Is there a way to tell a subscription that it should resubscribe on error?

**Comment by plus-** [comment]
Anyone has a workaround for this?

**Comment by goldo** [comment]
same question here!  have you found anything @hmeerlo @sshkalikov  ?

**Comment by sshkalikov** [comment]
not quite what i wanted to achieve initially, but i ended up handling errors on the top level, using apollo-link-retry (https://www.apollographql.com/docs/link/links/retry/) and apollo-link-error (https://www.apollographql.com/docs/link/links/error/) 
would still be happy to find a way to handle subsription errors individually
