### ISSUE TITLE
ApolloGraphQL Documentation Website: Apollo React Client V3 Documentation has dissapeared

### ISSUE THREAD

**Issue by ahrnee** [apollographql/apollo-client#5776]
The most recent deployment of the website apollographql.com seems to have omitted the Apollo React Client V3 preview documentation, and have 2 links to version 2.6 instead (see screenshot)

![image](https://user-images.githubusercontent.com/39815557/72147265-0b8b2200-3396-11ea-91bf-6ff9bf4cfaba.png)

**Comment by hwillson** [comment]
@ahrnee this is temporarily intentional. We're working on re-writing the docs a bit now that the `release-3.0` branch has been merged into `master`. It will be back to normal momentarily. Thanks for the heads up!

**Comment by jthistle** [comment]
How long is momentarily @hwillson ? :)

**Comment by jthistle** [comment]
Nevermind, I guess I can just [use the raw markdown files](https://github.com/apollographql/apollo-client/blob/master/docs/source) instead.

**Comment by benjamn** [comment]
To make matters (temporarily 🤞) worse, the whole website is currently [down](https://downforeveryoneorjustme.com/apollographql.com) because of a [fly.io](https://status.fly.io/) outage. Those raw markdown files are looking more and more reliable!

**Comment by hwillson** [comment]
Right - momentarily was supposed to be within 30 minutes of my comment, but we've hit a few snags along the way. Long story short our docs infrastructure can't currently handle the idea of having docs merged into `master` that we don't want to be deployed as the "current version". The 3.0 docs are now in master, but we want the 2.6 docs to stay as the current version when auto-published. Our docs team is working on adjustments to let this happen, so🤞we'll have this resolved "shortly" (which is slightly longer than "momentarily", but still shorter than "hopefully soon" 🙂).

**Comment by hwillson** [comment]
All fixed (thanks to @trevorblades in https://github.com/apollographql/apollo-client/pull/5780).
