### ISSUE TITLE
useQuery with `@client` is no longer instant

### ISSUE THREAD

**Issue by jthistle** [apollographql/apollo-client#5779]
**Intended outcome:**
- When I set up an `@client` query, with `3.0.0-beta.4`, I would get an instant response from `useQuery`
- This meant I was able to dereference stuff like this:
```js
const { data: { userData } } = useQuery(USER_DATA_QUERY);
```
- This made my code a lot cleaner and easier to read

**Actual outcome:**
- With `3.0.0-beta.20`, this is no longer the case. The `data` object initially has no value. This makes updating my code a massive pain, and breaks every usage of `useQuery` with an `@client` directive

**How to reproduce the issue:**
- Try querying the cache with `@client` with `3.0.0-beta.4` and `-beta.20` respectively, and you'll see that if you log the data object, it will be empty initially in the later version, but won't be in the earlier

**Versions**
`@apollo/client @ 3.0.0-beta.4`
`@apollo/client @ 3.0.0-beta.20`

**Comment by benjamn** [comment]
That style of code will not correctly handle loading states. You may think it's easier to read, but unfortunately almost any React hook like `useQuery` may return a useless initial result, so destructuring `data` is not safe.

I suspect #5565 is to blame for exposing the problem in your application, though ignoring loading states has always been risky.

**Comment by jthistle** [comment]
Right, guess I'm updating my code then. Thanks for the quick response.

**Comment by jthistle** [comment]
Closing as working as intended.
