### ISSUE TITLE
ApolloClient will throw a error when ssrMode and pollInterval is setting

### ISSUE THREAD

**Issue by gaoyuan123** [apollographql/apollo-client#5784]
The error: "Queries that specify the cache-first and cache-only fetchPolicies cannot also be polling queries." will throw up when ssrMode and pollInterval is setting,even if in the client.

**Comment by zacksinclair** [comment]
This is probably the same issue as: https://github.com/apollographql/apollo-client/issues/3775
which the Apollo team has errantly closed. This remains a bug in the library with a reproduction case in the linked issue.

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
