### ISSUE TITLE
Is possible create new local query which Select all records of specific __typename?

### ISSUE THREAD

**Issue by mastrayer** [apollographql/apollo-client#5788]
I try to write local query that select all ```Group``` type in ```Team``` object.
but Apollo cache(in-memory-cache) has only 2 types of cache reading API (readQuery / readFragment) and they need ID option too.

How can i query all about Group type?

```graphql
# server schema
type Team {
  id: ID!
  groups: [Group!]!
}

type Group {
  id: ID!
  name: String!
}

type Query {
  team: Team!
}
```

```graphql
# client schema
extend type Query {
  groups: [Group!]!
}
```

It's same below SQL
```mysql
SELECT * FROM cache WHERE __typename = 'Group'
```

**Comment by dylanwulf** [comment]
Issues in this repository are reserved for bug reports only. If you have questions, please ask on [Spectrum](https://spectrum.chat/apollo) or [StackOverflow](https://stackoverflow.com/questions/tagged/apollo-client). If you would like to request a new feature, please open a new issue in this repo: https://github.com/apollographql/apollo-feature-requests
