### ISSUE TITLE
Latest stable version of Apollo Client (v2.6.8) not published to npm

### ISSUE THREAD

**Issue by funkybunky** [apollographql/apollo-client#5789]
Listing the published version via `npm view @apollo/client versions` shows only v3.0.0-alphas and -betas.

I have an issue when using Apollo with Gatsby and would like to use the latest stable release of Apollo Client to work around. Could you please publish the latest v2 release on npm?

Will file an issue on the https://github.com/apollographql/gatsby-theme-apollo/ repo with the exact reproduction.

**Comment by chemicalkosek** [comment]
npm i apollo-client

**Comment by funkybunky** [comment]
Haha, I didn't see there are two different packages published. That explains it, of course.
Thanks a lot for the heads-up! :)
