### ISSUE TITLE
[3.0] EntityStore error after calling cache.evict

### ISSUE THREAD

**Issue by ahrnee** [apollographql/apollo-client#5793]
**Scenario**
Executing the following line of code:
```
  apolloClient.cache.evict(defaultDataIdFromObject(user));
```

**Intended outcome:**
Evict succeeds, with no subsequent error

**Actual outcome:**
An error is thrown with the following message: _TypeError: Cannot convert undefined or null to object_

The following further info is shown in the error details:
```
TypeError: Cannot convert undefined or null to object
Layer.EntityStore.get
entityStore.js:28
  25 |     var storeObject = this.data[dataId];
  26 |     if (!fieldName)
  27 |         return storeObject;
  28 |     if (hasOwn.call(storeObject, fieldName)) {
  29 |         return storeObject[fieldName];
  30 |     }
  31 | }
```

**How to reproduce the issue:**
This error started just by adding cache.evict. I am not entirely sure of the prerequisite conditions. I will spend time reproducing in the apollo error template if the cause of this issue is not obvious to the apollo team

**Versions**
System:
    OS: macOS 10.15.2
  Binaries:
    Node: 13.6.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.117
    Safari: 13.0.4
  npmPackages:
    @apollo/client: v3.0.0-beta.23  => 3.0.0-beta.23 
    @apollo/react-hooks: ^3.2.0-beta.0 => 3.2.0-beta.0 
    apollo-link-debounce: ^2.1.0 => 2.1.0

**Comment by benjamn** [comment]
Ahh, this looks like a missing `storeObject` truthiness check introduced in #5772. Dangling references are supposed to be handled gracefully.

**Comment by benjamn** [comment]
Also, there's a new `cache.identify` method that allows you to write
```ts
 apolloClient.cache.evict(apolloClient.cache.identify(user));
```
which respects `keyFields`, whereas `defaultDataIdFromObject` is only good for IDs computed by `dataIdFromObject`.
