### ISSUE TITLE
Documentation for the Imperative Implementation

### ISSUE THREAD

**Issue by daaashleywch** [apollographql/apollo-client#5798]
Hello,

I've been using your client implementation for some time now, but always in the imperative implementation. I see your docs only provide examples of the declarative form using components. I'm not sure if this has been discussed/asked yet, but would you consider providing imperative documentation to your website/repository? Or if extensive documentation already exists, do you know where I can find it? I just felt like I should ask because I feel this could be of use to the community at large.

Specifically, docs for code like the below would be nice. 

`const withAuctionBids = graphql(QUERY_AUCTION_BIDS, {
    name: "auctionBids",
    options: ({ auctionData: { id } }) => ({
        variables: {
            input: {
                auctionId: id
            }
        },
        fetchPolicy: "network-only"
    })
});`

`const withData = compose(
    graphql(ACTIVE_USERS_QUERY, {
        options: { fetchPolicy: "network-only" },
        props: ({ ownProps, data }) => {
            return {
                data,
                subscribeToNewData: (onAddedUsers, onRemovedUsers) => {
                    return data.subscribeToMore({
                        document: ACTIVE_USERS_SUBSCRIPTION,
                        updateQuery: (prev, { subscriptionData }) => {
                            const {
                                totalUsers,
                                addedUsers,
                                removedUserIds
                            } = subscriptionData.data;
                            if (addedUsers) {
                                onAddedUsers && onAddedUsers(addedUsers);
                            }
                            if (removedUserIds) {
                                onRemovedUsers &&
                                    onRemovedUsers(removedUserIds);
                            }
                            if (
                                totalUsers !== undefined &&
                                prev !== undefined
                            ) {
                                return Object.assign({}, prev, {
                                    activeUsers: Object.assign(
                                        {},
                                        prev.activeUsers,
                                        {
                                            totalUsers: totalUsers
                                        }
                                    )
                                });
                            }
                            return null;
                        }
                    });
                }
            };
        }
    }),
    getUserData({ name: "userData", options: { fetchPolicy: "network-only" } })
)(ActiveUsers);`

I've sort of been forced to learn this convention by asking other developers in person, and copying the convention from other places in the repo I've been working on. This can be pretty difficult to get the hang of.

Thanks,

David

**Comment by hwillson** [comment]
The docs have been updated quite a bit since this issue was opened. Let us know if you still think this is an issue. Thanks!
