### ISSUE TITLE
Automatic Cache Update Not Working

### ISSUE THREAD

**Issue by danReynolds** [apollographql/apollo-client#5803]
Hello! I am trying to take advantage of the Apollo automatic cache updates as described [here](https://www.apollographql.com/docs/react/data/mutations/#updating-a-single-existing-entity), but when I try to update my single entity, the cache remains the same:

Here I make the mutation:
<img width="914" alt="Screen Shot 2020-01-10 at 1 31 25 PM" src="https://user-images.githubusercontent.com/2192930/72621814-fb33f380-390f-11ea-9e9d-b4c166cdb500.png">

and here I check the cache afterwards to see if it has changed:
<img width="899" alt="Screen Shot 2020-01-10 at 1 32 37 PM" src="https://user-images.githubusercontent.com/2192930/72621863-0edf5a00-3910-11ea-992b-e92793cd5781.png">

Despite the `isHidden` flag being set by the mutation, it is not updated. Is there something I'm missing for automatic cache updates besides single entity, and request the ID and modified fields back in the mutation?

Here are my system facts:
<img width="906" alt="Screen Shot 2020-01-17 at 9 59 54 AM" src="https://user-images.githubusercontent.com/2192930/72621949-2fa7af80-3910-11ea-8506-a7855ba3314f.png">

**Comment by dylanwulf** [comment]
From what I can see it looks like the cache should be updating. Could you provide a runnable reproduction, preferably using codesandbox? It's difficult to see what's going on without being able to run the code. Issues in this repo are much more likely to be looked at if they have a runnable reproduction

**Comment by danReynolds** [comment]
Normally that's what I'd do but for an issue like this with something as complicated as apollo client, I don't have a great way of demoing our running setup and schema etc especially without giving away closed-source code. Are there any gotchas with the automatic cache updates I could be missing or could you point me to where in the code it compares the result of the mutation with what's in the cache to determine if it should update? I'd even be up for pairing if someone has time today.

**Comment by dylanwulf** [comment]
I can't really think of any gotchas. If you re-query that data after the mutation is finished, does that update the cache properly?

**Comment by danReynolds** [comment]
Yep! If I immediately query for that entity after the mutation then it updates in the cache. Do you know where the code lives for comparing the result of the mutation with what's in the cache to determine if it should update? I can take a look

**Comment by dylanwulf** [comment]
Interesting. I'm not 100% sure, but I think it doesn't do any comparing. It just merges the new data into the cache no matter what.
If you watch the network tab in the devtools when you do the mutation, is the mutation the only thing that gets sent to the server? Are you using the `update` function to manually update the cache after the mutation?
Usually at this point I would just start tearing the app apart until the problem stops happening. Sorry I can't really help more than this!

**Comment by danReynolds** [comment]
I dug into the code and *think* I might have found the problem, take a look and let me know if you think that my reasoning makes sense: https://github.com/apollographql/apollo-client/pull/5805

**Comment by dylanwulf** [comment]
Oh, you didn't mention you were using optimisticResponse. This issue might be related: https://github.com/apollographql/react-apollo/issues/3532

**Comment by danReynolds** [comment]
Might be, but even without `optimisticResponse` the cache wasn't getting updated so I think it's because of that issue I've documented in the PR: https://github.com/apollographql/apollo-client/pull/5805. @jbaxleyiii any thoughts on this one?

**Comment by bstro** [comment]
I'm not sure if related, but I am running into an issue where I am using `optimisticResponse` and can confirm that it is updating my cache correctly, but my components don't re-render until the client receives the response from the server (hence defeating the purpose of using `optimisticResponse`).

**Comment by danReynolds** [comment]
After looking into it some more, it looks like we hit this issue because our apollo client config specified:

const apolloClient = new ApolloClient({
  defaultOptions: {
    watchQuery: {
      fetchPolicy: APOLLO_FETCH_POLICY.CACHE_AND_NETWORK,
    },
    mutate: {
      fetchPolicy: APOLLO_FETCH_POLICY.NO_CACHE,
    },
  },
});
Which for mutate we had thought meant always hit the network similarly to what it means for a query as mentioned here:

no-cache: This fetch policy will never return your initial data from the cache. Instead it will always make a request using your network interface to the server. Unlike the network-only policy, it also will not write any data to the cache after the query completes.

But in the context of a mutation it seems to mean do not cache the mutation result. If that's the intended meaning then I think it could just use some better documentation. It also means that the result of the mutation is not written to the apollo cache and the update handler provided to the mutation is also not run when the server response comes back so maybe that's still not intended? What is the use-case for a no-cache option for mutations?
