### ISSUE TITLE
[3.0] justTypenameQuery negatively affects consumer's bundle size

### ISSUE THREAD

**Issue by henryqdineen** [apollographql/apollo-client#5806]
https://github.com/apollographql/apollo-client/blob/2e3e0a86659956fc579b0c2580f2d01675693d5f/src/cache/core/cache.ts#L8-L9

This might have negative consequences for users that are relying on `babel-plugin-graphql-tag` or a similar transform to remove `graphql/language/parser` from their app bundles.

Thanks. Great work on 3.0!

**Comment by vishwam** [comment]
+1 I’m using graphql-tag/loader to precompile my queries and to reduce the runtime load latency; pulling in 50+KB just to parse the typename query seems wildly inefficient. Please consider reverting back to the object schema instead.
