### ISSUE TITLE
useLazyQuery call onComplited even there is error

### ISSUE THREAD

**Issue by frenzymind** [apollographql/apollo-client#5812]
Hello!
I have this query in code:
`  const [logIn, { loading, data, error }] = useLazyQuery(LOGIN, {
    onError: errorLoginHandler,
    onCompleted: compliteLoginHandler,
    fetchPolicy: 'network-only',
    notifyOnNetworkStatusChange: true
  });`

and I call _logIn_ returned function for onClick button event. My backend is down, so this query can't be successfull and I expect alway execute onError handler. Here they are:
`const errorLoginHandler = () => {
    console.log('errorLoginHandler:', error.networkError.message);
  };

  const compliteLoginHandler = () => {
    console.log('compliteLoginHandler', error.networkError.message);
    if (error) {
      return;
    }
  };`

But when I clicking the button, I see error and complited log messages:
![image](https://user-images.githubusercontent.com/33678873/72696234-71399400-3b76-11ea-82fe-af72370d4a73.png)
I have to check error in compliteLoginHandler to prevent unexpected executing. Why complite handler is called from time to time ?
Thanks!

**Comment by wgottschalk** [comment]
ran into the same issue
https://github.com/apollographql/apollo-client/issues/6105

**Comment by riccoski** [comment]
Same here. I noticed if you used:
`   fetchPolicy: 'network-only',
`

then it will work as expected. Of course if you don't need the cache

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
