### ISSUE TITLE
clearStore is not resetting the cache immediately  

### ISSUE THREAD

**Issue by tafelito** [apollographql/apollo-client#5814]
**Intended outcome:**

I have a react-native app that shows some data. The data could be loaded for users and non logged users. If I user is logged in, when I logged out I'm clearing the store. I use clear store since I don't want to refetch the queries since some of them could be user specific. 

**Actual outcome:**

The issue is that after calling clearStore, if I inspect the cache in the dev tools, the cache is not cleared, all data is still there. Then, if I navigate to a new screens where it queries some data, then the cache is cleared and then filled with the new data. But this is causing me more issues

So I have 2 tabs, 1 is Home, and 2 is Profile. Home has a list of data, and when you click on some data, you go to the details.

Having a user logged in, when the app starts, it loads some data in Home. Then I go to Profile, I logout. After logout, I go to home. All data is still there. Then I go to the Details screen that calls a new query. Since react-navigation does not unmount the Home screen, the query inside Home is triggered, but is not completed. I can see this because the loading is true, but it stays in true, it never brings the data back. So then, if I go back from Details to Home, because loading is true, no data is shown.

The query in Home uses fetchPolicy cache-and-network, but if I use the default, this doesn't happen, since the query in Home is not triggered.

This is how I call the clearStore
```js
export default function Profile({ navigation }) {
  const client = useApolloClient();
  const userId = getUserId();
  const { data, loading, error } = useQuery(meQuery, {
    variables: { id: userId },
  });

  const onLogout = async () => {
    try {
      await logout();
      await client.clearStore();
      navigation.navigate('Home');
    } catch (err) {
      ...
    }
  };

  ...
}

```

**Versions**

```
  System:
    OS: macOS 10.15.2
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.117
    Safari: 13.0.4
  npmPackages:
    @apollo/react-hooks: ^3.1.3 => 3.1.3
    apollo-boost: ^0.4.7 => 0.4.7
    apollo-link-context: ^1.0.19 => 1.0.19
    apollo-link-error: ^1.1.12 => 1.1.12
    apollo-link-token-refresh: ^0.2.7 => 0.2.7
    apollo-link-ws: ^1.0.19 => 1.0.19
```

**Comment by kostiantyn-solianyk** [comment]
same here

**Comment by tafelito** [comment]
I don't think this issue is relevant anymore since AC v3x, I'm gonna close it for now

**Comment by kockok** [comment]
> I don't think this issue is relevant anymore since AC v3x, I'm gonna close it for now

I use `"@apollo/client": "^3.2.1",` and my logout function is:

```
      <Button
        children={'logout'}
        onPress={() =>
          signOut()
            .then(() => client.clearStore())
            .catch((err) => Alert.alert('Login Error', err))
        }
      />
```
And that won't clear the cache.
So, how did you solve yours?
