### ISSUE TITLE
Values returned by `useQuery` are mixed up

### ISSUE THREAD

**Issue by co-l** [apollographql/apollo-client#5817]
**Intended outcome:**
Display the values contained in an array for an object fetched through ```useQuery```.
The only thing peculiar about the query is that it contains a cyclical type : a `Product` can contain several other `Product` in its ```variations``` property. (I've made another sandbox without the cyclical type, same issue)

**Actual outcome:**
The values displayed are not the ones expected.

![image](https://user-images.githubusercontent.com/11582947/72807741-58091400-3c58-11ea-8005-079a4ecc931a.png) ![image](https://user-images.githubusercontent.com/11582947/72807787-6fe09800-3c58-11ea-9ded-d8e03ebf03fd.png) ![image](https://user-images.githubusercontent.com/11582947/72807822-7bcc5a00-3c58-11ea-9512-4368733eaeb6.png)

**How to reproduce the issue:**
[https://codesandbox.io/s/stoic-fog-5b24k?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/stoic-fog-5b24k?fontsize=14&hidenavigation=1&theme=dark
)without cyclical type: [https://codesandbox.io/s/nervous-mayer-johfj?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/nervous-mayer-johfj?fontsize=14&hidenavigation=1&theme=dark)

**Versions**

  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
  Binaries:
    Node: 12.13.1 - /usr/bin/node
    npm: 6.13.4 - /usr/bin/npm
  Browsers:
    Chrome: 79.0.3945.79
    Firefox: 71.0
  npmPackages:
    @apollo/client: ^3.0.0-beta.24 => 3.0.0-beta.24 
    apollo-upload-client: ^12.1.0 => 12.1.0

**Comment by hwillson** [comment]
This should no longer be an issue in `@apollo/client@latest` - let us know otherwise, thanks!
