### ISSUE TITLE
@apollo/link-schema is missing on npm for beta 3.0 client

### ISSUE THREAD

**Issue by ReTWi** [apollographql/apollo-client#5820]
In Apollo docs ([client react 3.0 beta](https://www.apollographql.com/docs/react/v3.0-beta/api/link/apollo-link-schema/#installation)) sad:

```
Installation
npm install @apollo/link-schema --save
```

But there is no such package on npm.

**Comment by hwillson** [comment]
Thanks for pointing this out @ReTWi! Those docs changes were published before we've had a chance to publish the `@apollo/link-X` betas. I'll get those published today.

**Comment by hwillson** [comment]
@ReTWi - the `@apollo/link-X` beta packages are now available: [`@apollo/link-schema`](https://www.npmjs.com/package/@apollo/link-schema)
