### ISSUE TITLE
[3.0] Local reducers fail when data: null and hide the server-side errors

### ISSUE THREAD

**Issue by jcane86** [apollographql/apollo-client#5824]
When ApolloClient is configured with client-side fields and resolvers for them, any time the server sends back an error response with no data, LocalState will error out trying to run the resolvers on null data, and that error covers up the underlying server error.

This is easier to reproduce if the client fields are nested, and not just in the topmost returned entity

Also, the generated error is called NetworkError, which is a bit misleading.

**Intended outcome:**
Local resolvers should only run when there is data to run on.

**Actual outcome:**
QueryManager calls LocalState to run local resolvers, with null data, and at some point in the chain, that errors out when looking for the field or entity containing the client fields.

QueryManager call is here: https://github.com/apollographql/apollo-client/blob/e85486def59a0b0c8e079e1d3e2e9114760b61f1/src/core/QueryManager.ts#L1204
and the actual fail is here when trying to access field on null: https://github.com/apollographql/apollo-client/blob/e85486def59a0b0c8e079e1d3e2e9114760b61f1/src/core/LocalState.ts#L373

**How to reproduce the issue:**
codesandbox here: https://codesandbox.io/s/gql-error-swallowed-by-network-error-obxh5

**Versions**
    "@apollo/client": "3.0.0-beta.24",
    "graphql": "14.5.8",
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "react-scripts": "3.0.1"

**Comment by jcane86** [comment]
BTW, I tried to implement local fields using fieldPolicies, but I found the policy does not get executed after the data returns from the server (as local reducers do).

Is this by design? Should I be able to replace local reducers (for computed data kind of fields) with type/fieldPolicies?

**Comment by fossamagna** [comment]
I have the same issue.

**Comment by andreialecu** [comment]
Indeed it seems that for a gql query like:

```gql
query GetCurrentUser {
  currentUserId @client
  currentUser: getUser {
    ...SecureUserData
  }
}
```

If `getUser` returns an error, even if `errorPolicy` is all, the result is simply unusable.

```
Error: Network error: null is not an object (evaluating 'rootValue[aliasedFieldName]')
```

`data` will be undefined in the response.

**Comment by jcane86** [comment]
@benjamn @hwillson any chance we can add this to the 3.0 milestone? it seems to have gone under the radar

**Comment by sirugh** [comment]
I'm seeing a similar behavior with a query using `fetchPolicy: "cache-and-network"`. Even if the cache has values in it the query results in an error:

```
[GraphQL error]: Message: Variable "$cartId" is not defined by operation "getItemCount"., Location: [object Object],[object Object], Path: undefined
```

```
query getItemCount {
        cartId @client @export(as: "cartId")
        cart(cart_id: $cartId) @connection(key: "Cart") {
            id
            total_quantity
        }
    }
```

```
const { data } = useQuery(getItemCountQuery, {
        fetchPolicy: 'cache-and-network',
        skip: !cartId
});
```

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
