### ISSUE TITLE
Module not found: Can't resolve '@apollo/link-context'

### ISSUE THREAD

**Issue by TheoMer** [apollographql/apollo-client#5827]
**Intended outcome:**
As per the documentation [Context Link](https://www.apollographql.com/docs/react/v3.0-beta/api/link/apollo-link-context/) I expected the package to exist. What is the issue here?

**Actual outcome:**
![setContextError](https://user-images.githubusercontent.com/15969262/72936275-c2a47780-3d5e-11ea-9842-92ae60a63e27.jpg)

**How to reproduce the issue:**
NPM installed the latest version of apollo/client and then `npm run dev`

**Versions**
OS: Windows 10 Pro   
apollo/client: 3.0.0-beta.24   
apollo/graphql; 14.5.0
react-apollo: 2.5.8

**Code**
```
import { setContext } from "@apollo/link-context";
```

**Comment by henryqdineen** [comment]
You should try `npm install @apollo/link-context --save`
