### ISSUE TITLE
Preventing the single-entity-auto-cache-update while allowing the manual update function

### ISSUE THREAD

**Issue by jamshally** [apollographql/apollo-client#5837]
**Scenario**
I have a scenario where would like to _manually_ update the InMemoryCache after the successful completion of a mutation (with the update function), but prevent the InMemoryCache single-entity-auto-update. Apologies if I am missing something obvious, but I have not been able to make this work

**Setup**
Submit mutation with:
- FetchPolicy of 'no-cache'
- update function supplied

```
const [updateTodo] = apolloClient.mutate({
  mutation:    UPDATE_TODO,
  fetchPolicy:'no-cache'
  update(cache, { data: { updatedTodo } }) {
     cache.writeData({
       // Some custom cache update code
     });
  }
})

updateTodo({ variables: { id, type } });

```

**Intended outcome:**
Custom cache update logic runs _without_ the single-entity automatic cache update (and thus without te watched queries subsequently being triggered)

**Actual outcome:**
Either:
1. **Update function is not called**  (when 'no-cache' FetchPolicy is set)
OR
2. Update function is called BUT the the single-entity automatic cache update also runs (when 'no-cache' FetchPolicy set)

**Versions**
  System:
    OS: macOS 10.15.2
  Binaries:
    Node: 13.6.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Safari: 13.0.4

**Comment by akkhil7** [comment]
Did you find a work around for this?

**Comment by jamshally** [comment]
@akkhil7 - yes, I just used no-chache, and then use the apolloClient.Cache methods to manually update the cache

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
