### ISSUE TITLE
Fields defined in a fragment are lost and not merged in final result

### ISSUE THREAD

**Issue by zicodeng** [apollographql/apollo-client#5859]
Consider the following query and fragment:

```
// Post implements Likable interface
const LikableFields = gql`
  fragment LikableFields on Likable {
    total_likes
  }
`;

const SharedPostFields = gql`
  fragment SharedPostFields on Post {
    id
    title
    ...LikableFields
  }
  ${LikableFields}
`;

export const POST = gql`
  query Post($id: ID!) {
    post(id: $id) {
      description
      ...SharedPostFields
    }
  }
  ${SharedPostFields}
`;
```

Here is the post type definition from Apollo server:

```
interface Likable {
  total_likes: Int!
}

type Post implements Likable {
  id: ID!
  title: String!
  description: String!
  total_likes: Int!
}
```

**Intended outcome:**

When the query is executed, and then we log the data, it should contain the following fields:

```
{
  id: "xxx",
  title: "xxx",
  description: "xxx",
  total_likes: 666
}
```

**Actual outcome:**

However, when we log the data, it is missing `total_likes` field, which is from `LikableFields` fragment.

Note: if we inspect the **network response**, we can see that `total_likes` field is **fetched**, meaning query is sent to server and returned from server correctly, but for some reasons, it is not merged to the final data result, maybe during caching??? I believe this bug is introduced in recent release. It hasn't occurred before

```
{
  id: "xxx",
  title: "xxx",
  description: "xxx",
}
```

**How to reproduce the issue:**

**Versions**

```
"@apollo/client": "^3.0.0-beta.26"
```

**Comment by benjamn** [comment]
Are you providing [`new InMemoryCache({ possibleTypes })`](https://www.apollographql.com/docs/react/v3.0-beta/data/fragments/#using-fragments-with-unions-and-interfaces) to specify the relationships between supertypes (`Likable`) and subtypes (`Post`) in your schema?

**Comment by zicodeng** [comment]
@benjamn Good catch, thanks a ton!!!

**Comment by oeed** [comment]
`possibleTypes` also solved my issue – thanks!

It is a rather confusing bug to try and track down though, I actually ended up upgrading to Apollo V3 to try and fix as I thought it was an older bug that might've been since fixed.

I'm not sure how possible it is to detect, but can I suggest providing a warning like some other mistakes give informing of the simple fix @benjamn ?
