### ISSUE TITLE
Broken URL link in Readme.md

### ISSUE THREAD

**Issue by jakebman-charter** [apollographql/apollo-client#5867]
Visiting the link at https://www.apollographql.com/docs/react/api/apollo-client/ leads to 404.

Has this link been moved?

**Comment by dylanwulf** [comment]
Strangely, manually navigating to this page works fine but as soon as you try to manually enter the URL it 404s. 
(Manual navigation: https://www.apollographql.com/docs/react/ -> API Reference -> class ApolloClient)

**Comment by jakebman-charter** [comment]
That's very neat. Even simply refreshing that same page gives the issue.

This no longer feels like a bug against the apollo-client repo, and is significantly more a bug against the https://www.apollographql.com/docs/react/ documentation.

**Comment by jakebman-charter** [comment]
https://github.com/apollographql/apollo-client/blob/master/docs/source/api/core/ApolloClient.mdx is the canonical source for that documentation, so it's weird that the link points to `docs/source/docs/source/`, duplicating `doc/source`

**Comment by jennygrahamjones** [comment]
The `gatsby-config.json` that generates the sidebar on https://www.apollographql.com/docs/react/ doesn't appear to handle routing in the same way (when you click it, it's not making a `GET` for a new route, just replacing the contents of the panel to the right), so it's possible to navigate to the API reference docs that way.

The [_redirects](https://github.com/apollographql/apollo-client/blob/master/docs/static/_redirects) file specifies a redirect from `/docs/react/api/apollo-client` to `/docs/react/api/core` - and no file to represent `core` seems to exist?

**Comment by hwillson** [comment]
The docs have been updated quite a bit since this issue was opened. Let us know if you still think this is an issue. Thanks!
