### ISSUE TITLE
3.0 Release Date

### ISSUE THREAD

**Issue by panrafal** [apollographql/apollo-client#5873]
Could you please provide guidance on when the 3.0 is expected to be released?

Specifically, are there any major API/behavior changes planned before the release, or is it mostly polishing, bug fixing and the like?

**Comment by hwillson** [comment]
@panrafal There are no further major API/behavior changes planned for the 3.0 release. We're in polish/bug fix/documentation mode, with a planned release date of Feb. 11th (🤞).
