### ISSUE TITLE
Docs point to wrong URL for networkStatus 

### ISSUE THREAD

**Issue by sbays** [apollographql/apollo-client#5874]
**Intended outcome:**
Tried to view the full list of all the possible loading states

**Actual outcome:**
Hit a dead URL

**How to reproduce the issue:**
go to https://www.apollographql.com/docs/react/data/queries/#inspecting-loading-states and try to view the full list of networkStatus values

**Comment by trdaya** [comment]
> **Intended outcome:**
> Tried to view the full list of all the possible loading states
> 
> **Actual outcome:**
> Hit a dead URL
> 
> **How to reproduce the issue:**
> go to https://www.apollographql.com/docs/react/data/queries/#inspecting-loading-states and try to view the full list of networkStatus values

[Link](https://github.com/apollographql/apollo-client/blob/master/src/core/networkStatus.ts) as per today
