### ISSUE TITLE
Apollo Cache V3: References instead of items within merge

### ISSUE THREAD

**Issue by 3nvi** [apollographql/apollo-client#5876]
Hey there, I'm currently trying out the latest `@apollo/client` and I'm having some trouble using the `merge` functionality, when specifying `keyFields`.

Specifically I have the following schema:

```graphql
Query {
  item: ItemDetails
}

type ItemDetails {
    itemId
    name
}
```

and I'm using an `apollo-inmemory-cache` from `@apollo/client` with the following configuration:

```js
new InMemoryCache({
      typePolicies: {
        ItemDetails: {
          keyFields: ['itemId'],
        },
        Query: {
          fields: {
            item: {
              merge(existing, incoming) {
                return incoming;
              },
            },
          },
        },
      },
    })
```

The issue that I'm having is that `incoming` is always a reference instead of being the actual serialized `item` that the graphql server returned. 

This means that `incoming` has the value of ` {__ref: "ItemDetails:{"itemId":"something"}"}` , instead of having the value of `{ __typename: "ItemDetails", "itemId": "something", "name": "something else" }`.

Now, if I remove the `keyFields` declaration (which essentially "breaks" the app since there is no `id` or `_id` present in the response), then the `incoming` **does** actually gets populated with the correct value and not just a reference.

What I want to know is whether this could possibly be a bug, since the only way to get the full object from just the `__ref`, is to do an "expensive" `cache.read` or `client.read`. Am I missing something?

**Intended outcome:**
The item should have been returned as `{ __typename: "ItemDetails", "itemId": "something", "name": "something else }`

**Actual outcome:**
The item gets  its reference returned ` {__ref: "ItemDetails:{"itemId":"something"}"}`

**How to reproduce the issue:**
Create a schema (like the one attached above), create a cache with a configuration like the one above. Attempt to execute the one and only query and inspect the values of `existing` and `incoming` in the `merge` function.

**Versions**

```
  System:
    OS: macOS 10.15.2
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.2
    Safari: 13.0.4
  npmPackages:
    @apollo/client: ^3.0.0-beta.29 => 3.0.0-beta.29
    apollo-link-error: ^1.1.12 => 1.1.12
```

**Comment by benjamn** [comment]
Not a bug!

References indicate that you're dealing with an object that was normalized (has an ID), which is good for cache consistency, and should be the common case (though it's not always possible to give an ID to everything). You should definitely keep using `keyFields` wherever possible.

The piece you're missing is that both `read` and `merge` functions take an `options` object as their final argument, which contains a few helper functions that are designed for this case:
```ts
new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        item: {
          merge(existing, incoming, {
            // Can be used to test whether an object is a { __ref }:
            isReference,
            // Gives you a Reference in exchange for an object with a __typename
            // and the necessary key fields:
            toReference,
            // Reads fields by name from any object, including References:
            readField,
          }) {...},
        },
      },
    },
  },
})
```
The same options are passed to both `merge` and `read` functions, though some may be used more often in one case than the other.

For example, in `merge` functions, `readField(fieldName, objOrRef)` is generally used to deduplicate objects, whereas in `read` functions, `readField(fieldName)` (with no object) can be used to read other fields from the same object.

As you correctly anticipated/guessed, `readField` will be much faster than calling `cache.readQuery`.

**Comment by 3nvi** [comment]
Gotcha! Thanks for the detailed response. I did know about the options, but for some reason I thought it wasn't the correct way to approach the issue.

So, in terms of performance, is it quicker to rename "itemId" to just "id" in order to avoid calling "readField" or is "readField" already called when there are no "key Fields" and thus it wouldn't make much of a difference?

**Comment by johanjq** [comment]
Hi! Currently having a similar issue. Basically what we want to do is when we receive the data from the server, requested using the useQuery hook. We want to store this in a Reactive variable so it can be available globally and be able to use it in other components without the need to prop drilling and stuff like that. 
```javascript
  const apolloClient = new ApolloClient({
    credentials: 'same-origin',
    cache: new InMemoryCache({
      addTypename: true,
      typePolicies: {
        Query: {
          fields: {
            getProfessionalServices: {
              read(data) {
                return professionalServicesVar(data);
              },
            },
          },
        },
      },

This returns only __ref and not the actual data. Another thing we could do is to use readQuery in the client but the issue with this is that it requires the variables as well but are these variables necessary even if the data is already stored in the cache? 
Do you know what's the best thing to do in this case? thanks a lot.

**Comment by oseisaac** [comment]
> Hi! Currently having a similar issue. Basically what we want to do is when we receive the data from the server, requested using the useQuery hook. We want to store this in a Reactive variable so it can be available globally and be able to use it in other components without the need to prop drilling and stuff like that.
> 
> ```js
>   const apolloClient = new ApolloClient({
>     credentials: 'same-origin',
>     cache: new InMemoryCache({
>       addTypename: true,
>       typePolicies: {
>         Query: {
>           fields: {
>             getProfessionalServices: {
>               read(data) {
>                 return professionalServicesVar(data);
>               },
>             },
>           },
>         },
>       },
> ```
> 
> This returns only __ref and not the actual data. Another thing we could do is to use readQuery in the client but the issue with this is that it requires the variables as well but are these variables necessary even if the data is already stored in the cache? Do you know what's the best thing to do in this case? thanks a lot.

Hi did you find a solution to this ?
