### ISSUE TITLE
[3.0] - pagination example does not work as intended

### ISSUE THREAD

**Issue by tafelito** [apollographql/apollo-client#5881]
**Intended outcome:**

I'm trying to implement the pagination example with the new cache implementation 

**Actual outcome:**

Using pagination example based n #5677 doesn't work as expected

```js
merge(existing: any[], incoming: any[], { args }) {
  const merged = existing ? existing.slice(0) : [];
  // Insert the incoming elements in the right places, according to args.
  for (let i = args.offset; i < args.offset + args.limit; ++i) {
    merged[i] = incoming[i - args.offset];
  }
  return merged;
},
read(existing: any[], { args }) {
  // If we read the field before any data has been written to the
  // cache, this function will return undefined, which correctly
  // indicates that the field is missing.
  return existing && existing.slice(
    args.offset,
    args.offset + args.limit,
  );
},
```

In the merge function, instead of doing 

```js
for (let i = args.offset; i < args.offset + args.limit; ++i) 
```

I had to do 

```js 
for (let i = args.offset; i < Math.min(args.offset + incoming.length, args.offset + args.limit) ; ++i)
``` 

since the incoming length could be less than the offset, so it will add undefined items to the array

In the read function, if the existing arg has data, and we slice to a bigger offset, it return an empty array, not undefined, so the query is not passed to the server

insetad of doing 

```js
return existing && existing.slice(
  args.offset,
  args.offset + args.limit,
);
```

I did 

```js
const data =
  existing && existing.slice(args.offset, args.offset + args.limit);
return data && data.length === 0 ? undefined : data;
```

Also the types of the example fails as they are

intead of

```js
merge(existing: any[], incoming: any[], { args }) {
...
}
read(existing: any[], { args }) {
...
}
```

I replaced with

```js
merge(existing: any, incoming: any, { args }: { args: any }) {
...
}
read(existing: any, { args }: { args: any }) {
....
}
```

**Versions**

```
 System:
    OS: macOS 10.15.2
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Safari: 13.0.4
  npmPackages:
    @apollo/client: ^3.0.0-beta.30 => 3.0.0-beta.30
    @apollo/link-context: ^2.0.0-beta.3 => 2.0.0-beta.3
    @apollo/link-error: ^2.0.0-beta.3 => 2.0.0-beta.3
```

**Comment by benjamn** [comment]
Out of curiosity, what sort of type error are you seeing that required weakening the parameter types to `any`?

**Comment by tafelito** [comment]
the error is

```
Types of parameters 'existing' and 'existing' are incompatible.
                          Type 'string | number | void | Readonly<Object> | readonly string[] | Readonly<Reference> | readonly Reference[] | null | undefined' is not assignable to type 'any[] | undefined'.
                            Type 'null' is not assignable to type 'any[] | undefined'.ts(2345)
```

**Comment by tafelito** [comment]
Another thing I tried to do is this

having the typePolicies

```js
Query: {
      fields: {
        areas: {
          keyArgs: ['where'],
          ...offsetLimitPaginatedField<Areas>(),
        },
      },
    },
```

I have this in the cache

![image](https://user-images.githubusercontent.com/5973652/73414161-f5f58200-42db-11ea-8969-8427134dfbc4.png)

then after a delete mutation, I'm trying to update the cache in the update function like this

```js
await deleteAreas({
      variables: {
        ids: selected,
      },
      update: cache => {
        const query = gql`
          query areas($where: areas_bool_exp) {
            areas(where: $where) {
              ...Area
            }
          }
        `;
        const areas = cache.readQuery({
          query,
          variables: { where: { client_id: { _eq: clientId } } },
        });
      },
    });
```

But I get this error

`Invariant Violation: Can't find field areas on ROOT_QUERY object`

The read function is called, but since I don't set any limit or offset, it returns undefined

**Comment by benjamn** [comment]
@tafelito It's perfectly fine to have a `read` function that handles a variety of argument styles, including `args.{offset,limit}` pagination and `args.where` filtering, but I'm guessing your `offsetLimitPaginatedField` helper only handles pagination? If you want to combine different capabilities into one `FieldPolicy`, I think you need to use a different helper function to generate the policy. Ideally it could reuse `offsetLimitPaginatedField` internally.

Returning undefined is how `read` functions express that the field they're computing is missing, so throwing a missing field error is the intended behavior. That said, if it's a `@client` field that's not meant to be sent to the server, we might want to throw the exception anyway, rather than sending a query to the server that doesn't have the relevant field in it.

**Comment by wesbos** [comment]
I'm also having issues with Pagination - I've detailed them here: https://spectrum.chat/apollo/apollo-client/apollo-client-3-evict-api~cd289ed2-92e7-4281-8f73-ddfebb8ad09d

Are these related or should I make a new issue?

**Comment by benjamn** [comment]
@wesbos Your issues have more to do with reactive updates as a result of cache modifications, I think, whereas this issue is more about writing appropriately defensive `read` and `merge` functions to handle different pagination use cases. Those feel like separate (but both important) topics to me.

**Comment by tafelito** [comment]
@benjamn yes you're right, I only wanted to handle the pagination in the read function. What I was trying to point out is that the difference in the read function btw doing `client.query` and `client.cache.query` , is that, when doing `client.query`, if you return undefined (assuming the fetchPolicy is `cache-and-network`) then the query is requested to the server. In case of doing `cache.query`, if you return undefined, it throws an exception. (I'm pretty sure actually this was the same behavior  as in 2.x ). The error just thrown me off (it'd be nice to instead of an error to just return undefined imho)

**Comment by tafelito** [comment]
@benjamn I think I found a new edge case. 

I have a list that shows 5 items per page. I go to the second page and I have only 1 item. I remove the item by doing cache.writeQuery with the new data array without the last item.  
When the `read` function is executed, the `existing` array has 5 items, that's correct. Because now the page is an empty array, it returns undefined.

The problem is, when you do client.query you want the results to be undefined in order to pass the request to the server. But after the cache.writeQuery (I can't just evict the item since I' can actually remove a list of items), if the `read` fn returns undefined, the query hooks returns the previous data, including deleted item, even tho in the cache was already deleted. 
In that case it will have to return an empty array instead. But it can't return an empty array if we want to pass the request to the server. 

Btw this only happens if there are only 6 items (2 pages) in a list of 5 items per page. If there are 7 items it works fine because the `read` fn return an array with 1 item

I hope I was clear enough or I'm missing something

**Comment by benjamn** [comment]
> if the `read` fn returns undefined, the query hooks returns the previous data, including deleted item, even tho in the cache was already deleted

This sounds like a bug related to [this code](https://github.com/apollographql/apollo-client/blob/c5d5d27aa5b2d37dea9ddc85bebc1916ea9c2668/src/core/QueryManager.ts#L666), which has been a source of frustration for some time now. Could you try putting together a [reproduction](https://github.com/apollographql/react-apollo-error-template) so that we can confirm the diagnosis?

As for the second case, the behavior you're describing actually sounds reasonable to me, though you do have the option of implementing your `read` function so that it returns undefined if it can't return a full page of results. Also, if you're removing elements from a list (rather than just replacing them with `null`), you're probably going to have problems with `offset`/`limit`-based pagination, since the offsets are sensitive to the original list ordering. I would suggest not actually deleting items from the list in the cache, but instead filter them out in your UI code somehow… or try a different pagination strategy that's less sensitive to positional changes.

**Comment by tafelito** [comment]
@benjamn you can see the repro of the 1 issue https://codesandbox.io/s/nostalgic-pike-94wxh

**Comment by tafelito** [comment]
@benjamn when you call the `cache.writeQuery`, aside of the issue mentioned above, does the evict still need to be called for the individual items to be removed from the cache, even tho they are deleted from the ROOT_QUERY? Isn't `cache.gc()` supposed to take care of it?  

Same otherwise, if you evict an item by id, shouldn't it also be removed from the root queries? If not, what's the purpose of evicting an item by id if the item will stay in the query? 

Also I was thinking about the second case I mentioned above and your suggestion for that.  

If I delete the item 5, read the cache, filter the deleted item, write the new data to the cache. After writing the new data, in the read function, if you return undefined as you suggested (in case the page doesn't have enough items), it won't pass the request to the server. I'm not sure where you meant to return undefined for that case.

A numbered page style pagination like the one in the sandbox I put together before does seem a very common use case, and I don't see how not deleting the items will help there, 
unless we can do some sort of conditionally refetchQuery (only refetch if the .  
For data that does not change very often, the offset/limit solution should work fine, unlike an infinite list for a feed or any other list that do change data often

**Comment by tafelito** [comment]
@benjamn I know you guys are busy with the release of the upcoming v3 but can we get back to this at some point, at least on the docs?. We use a lot of tables in a admin dashboard where we can edit/remove/add rows and we still have to refetch after any crud operation. I thought with the new AC cache the pagination was gonna be fixed but this still happening. 
i think is a really common use case and It would be great to include a best way to implement this sort of pagination in the docs

Tanks for the great work!

**Comment by tafelito** [comment]
with the latest updates of AC, this seems to be working fine now. I just wanted to leave a working example on how to handle a numbered pagination, where you can delete and insert items to the list without having to refetch queries from the server in it's not necessary. Of course this works in hand with the `cache.modify` and `cache.evict` functions when doing an insert and a delete mutation

```js
const cache = new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        users: offsetLimitPaginatedField(),
        user(existing, { args, toReference }) {
          return existing || toReference({ __typename: "users", id: args?.id });
        },
      },
    },
  },
});
```

_pagination.ts_
```js

type Items = {
  nodes: any[];
  totalCount: number
}

export function offsetLimitPaginatedField() {
  return {
    keyArgs: ["where"],
    merge(
      existing: Items,
      incoming: Items,
      { args, canRead, readField }: FieldFunctionOptions
    ) {
      const offset = args?.offset ?? -1;
      const limit = args?.limit ?? -1;

      // Insert the incoming elements in the right places, according to args.
      if (offset >= 0 && limit > 0) {
        // filter dangling references from the existing items
        const merged = existing?.nodes.length
          ? existing.slice(0).filter(canRead)
          : [];
        const end = offset + Math.min(limit, incoming.nodes.length);
        for (let i = offset; i < end; ++i) {
          const node = incoming.nodes[i - offset];

          // find if the node is already present in the array
          // this could happen when new  obj is added at the top of the list, and when
          // requesting a new page to the server, the server sends the same id back in the new page
          const existing = merged.find(
            (m: any) => readField("id", m) === readField("id", node)
          );

          if (!existing) {
            merged[i] = node;
          }
        }
        return {
          ...incoming,
          nodes: merged,
        };
      }
      return incoming;
    },
    read(existing: any, { args, canRead }: FieldFunctionOptions) {
      const offset = args?.offset ?? -1;
      const limit = args?.limit ?? -1;

      if (offset < 0 && limit < 0) {
        return existing;
      }

      // If we read the field before any data has been written to the
      // cache, this function will return undefined, which correctly
      // indicates that the field is missing.
      const nodes =
        existing?.length && offset >= 0 && limit > 0
          ? existing.nodes
              // we filter for empty spots because its likely we have padded spots with nothing in them.
              // also filter obj that are not valid references (removed from the cache)
              .filter(canRead)
              // we have to filter first in order to slice only valid references and prevent a
              // server roundtrip if length doesn't cover the items per page
              .slice(offset, offset + limit)
          : existing;
      // if the total items read from the cache is less than the number requested,
      // but the total items is greater, it means that we don't have enough items cached,
      // so in order to request the items from the server instead, we return undefined
      // for this to work we need to know the total count of all items
      const itemsPerPage = args?.offset + args?.limit || 0;
      if (nodes?.length < itemsPerPage && itemsPerPage < existing?.totalCount) {
        return undefined;
      }

      if (nodes?.length) {
        return {
          ...existing,
          nodes,
        };
      }
    },
  };
```

**Comment by benjamn** [comment]
I agree this is an area that we need to handle better in the documentation. Let us know if the updates in #6429 do not answer your questions (or the questions you think other developers might have). Thanks again for pointing out the issues with the original pagination examples!

**Comment by faerylay** [comment]
i have same issue or i don't know how to do it.
<img width="733" alt="Screen Shot 2022-03-21 at 20 10 06" src="https://user-images.githubusercontent.com/36163143/159251206-255337e3-e9d3-4d89-99b4-69826aeeb2c5.png">
when i was use relaystylepagination , fetchmore infinite scroll is fine but scrolling error occur and then i changed it to offsetlimitpagination . scrolling error disable but like and  delete post mutation are  doesn't work  until refresh page .
<img width="801" alt="Screen Shot 2022-03-21 at 20 12 49" src="https://user-images.githubusercontent.com/36163143/159253052-1c168785-4ee1-49a1-9908-24e07bf71739.png">

how to do it pls help me....
 (sry for my english.. )
