### ISSUE TITLE
cache-and-network not returning the result from network

### ISSUE THREAD

**Issue by jatinjain155** [apollographql/apollo-client#5887]
I am using cache-and-network fetch-policy. 

As per the documentation _"this fetch policy will have Apollo first trying to read data from your cache. If all the data needed to fulfill your query is in the cache then that data will be returned. However, regardless of whether or not the full data is in your cache this fetchPolicy *will always execute query with the network interface* unlike cache-first which will only execute your query if the query data is not in your cache. This fetch policy optimizes for users getting a quick response while also trying to keep cached data consistent with your server data at the cost of extra network requests."_

So as per my understanding, I will first receive data from the cache. Then apollo will make a network call and will return me the fresh data.

However, in a few cases I am still getting data from the cache only, instead of network the second time.

**Comment by alexpermyakov** [comment]
Could you provide a codesandbox.io example? The case is not clear for now.

**Comment by jatinjain155** [comment]
I am using AWS AppSync which is wrapper over apollographql and hence cannot share code. What I want to understand is - are there any conditions under which apollographql while using a fetch policy of cache-and-network will return the data from cache instead of network interface.

As per the documentation "this fetch policy will have Apollo first trying to read data from your cache. If all the data needed to fulfill your query is in the cache then that data will be returned. However, regardless of whether or not the full data is in your cache this **fetchPolicy will always execute query with the network interface** unlike cache-first which will only execute your query if the query data is not in your cache. This fetch policy optimizes for users getting a quick response while also trying to keep cached data consistent with your server data at the cost of extra network requests."

**Comment by benjamn** [comment]
It's hard to offer any help if we don't even know what version of `@apollo/client` (or `apollo-client`) you're using. The request for a reproduction stands.

**Comment by gsqrt2** [comment]
I just  happen to notice the same behavior.
I can see the correct data being returned in the network response, but apollo client just returns the cached data twice.
I will try to isolate & reproduce, but it seems like it only happens on specific randomly 'selected' queries.

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
