### ISSUE TITLE
Export fromPromise in core/index.js

### ISSUE THREAD

**Issue by ottoo** [apollographql/apollo-client#5889]
I can access `fromPromise` in code via importing directly `import { fromPromise } from "@apollo/client/link/utils/fromPromise";`, but jest fails when testing

```
node_modules/@apollo/client/link/utils/fromPromise.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { Observable } from '../../utilities/observables/Observable';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

I can go around this by ignoring the `@apollo/client` in my package.json jest config, but if you could add `export { fromPromise } from '../link/utils/fromPromise.js';` to core index.js

**Comment by henryqdineen** [comment]
👍We would probably use this if it was exported. I'm also ok if it's not exported but maybe get rid of `toPromise()` for consistency

**Comment by dai-shi** [comment]
FWIW, my my lib is using to/fromPromise: https://github.com/dai-shi/apollo-link-lazy
It's for apollo-client 2.6 now, but will later be updated for 3.
