### ISSUE TITLE
Refetch returns Unhandled Promise Rejection after turning off and turning on network connection

### ISSUE THREAD

**Issue by miguelacio** [apollographql/apollo-client#5908]
Hello there, I'm facing this weird bug(?) where the refetch function that comes with the <Query/> component always returns Unhandled Promise Rejection after turning off and turning on network connection. In every <Query/> I use a <ErrorContainer/> which has a button that triggers my refetch function, but this time, when I turn the network connection off it lands on my error  (as it should) but when I turn the network connection back on it __always__ returns what I've mentioned. The only way to make it work its to go back to previuos screen and return to the screen which triggers the query component in my render (qu 

**Intended outcome:**

That refetch function actually made the query again, in this issue it is always skipped.

**Actual outcome:**

Unhandled Promise Rejection in every refetch request

**How to reproduce the issue:**

I think I already explained how to reproduce this, the following is the a sample of what I'm using:

index.js

```
        <Query query={ASSESSORS_QUERY} fetchPolicy={'cache-and-network'}>
          {({ networkStatus, error, data, refetch }) => {
            if (
              networkStatus === 1 ||
              networkStatus === 4 ||
              networkStatus === 2
            ) {
              return (
                <LoadingContainer />
              )
            }

            if (error) {
              return (
                <ErrorContainer
                  onPressRetry={refetch}
                />
              )
            }

            const {
              assessorsList: { assessors },
            } = data
            return (
              <Mylist
             ...
              />
            )
          }}
        </Query>
```

ErrorContainer.js

```
const TemplateError = ({ onPressRetry,}) => {
  return (
    <Container >
      <Button
        onPress={onPressRetry}
      />
    </Container>
  )
}
```

**Versions**

```
  System:
    OS: macOS 10.15.2
  Binaries:
    Node: 8.16.2 - ~/.nvm/versions/node/v8.16.2/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.16.2/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Safari: 13.0.4
  npmPackages:
    apollo-cache-inmemory: 1.3.9 => 1.3.9
    apollo-client: 2.4.5 => 2.4.5
    apollo-link: ^1.2.12 => 1.2.12
    apollo-link-context: 1.0.9 => 1.0.9
    apollo-link-error: ^1.1.11 => 1.1.11
    apollo-link-http: 1.5.5 => 1.5.5
    apollo-link-retry: ^2.2.14 => 2.2.14
      apollo-link-ws: ^1.0.14 => 1.0.14
    react-apollo: 2.2.4 => 2.2.4
```

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
