### ISSUE TITLE
Recursive readField

### ISSUE THREAD

**Issue by ashubham** [apollographql/apollo-client#5911]
This is how my schema looks like:
```gql
type Photo {
  id: ID!
  title: String!
  server: String!
}

type Tile {
  id: ID
  photo: Photo!
  size: string!
}
```

Now, on my client I have a cache `typePolicy`.
```js
typePolicies: {
      Tile: {
        fields: {
          imageUrl: {
            read(url, {args, readField}) {
              const server = readField('server', readField('photo')) // <--- Avoid this ?
              return `http://${server}.png`;
            }
          }
        }
      }
    }
```

As we can see above, I want to avoid nested calls to readField, maybe it should support path. Something like `readField('photo.server')`. Also, is there a way to strongly type the `readField` so that it can only accept valid field name ?

*Apollo-client:* 3.0-beta

**Comment by ashubham** [comment]
While we are at it, is it possible to add these `field customizations` lazily, just like `client.addResolver` ? I am trying to use this in a pretty big application and want to code split these custom getters, more or less moving away from `resolvers` for local state as access to `cache` in those is very clunky.

**Comment by benjamn** [comment]
You can call `cache.policies.addTypePolicies({ TypeName: { ... }, ... })` at any time to add new type policies. Note that the policies are not retroactive, so make sure you add the policies before you use the types they govern.

**Comment by benjamn** [comment]
Your aversion to nesting calls to `readField` seems pretty subjective. The `readField` function is designed for reading individual field values, and it also works for reading fields from foreign objects or references, though that's less common. In this particular case, I would just use `readField("photo").server`, unless you have a custom `read` function for the `server` field.

Regarding strongly typing strings, I'm not interested in introducing a special format for these strings, and strings are generally an area where even the strongest static type systems admit dynamic values. TypeScript certainly does not have the power to express static constraints on string literal formats, and these strings are not always string literals, anyway.

**Comment by ashubham** [comment]
Thanks @benjamn for your response. 

Since `photo` is a reference. `readField('photo').server` returns `undefined`.

**Comment by benjamn** [comment]
Ah, then you were right to do `readField("server", readField("photo"))`.

You are absolutely encouraged to use `read` functions for local state management. In fact, we are planning to deprecate and remove the old `resolvers`-based local state functionality in the next major version, so you're ahead of the curve here. Please let us know if you encounter any limitations in the new system. One known limitation (compared to `resolvers`) is that `read` functions can't return a `Promise`, because that just doesn't make sense with our synchronous cache API. However, you can update cache data asynchronously using the new `cache.makeLocalVar` API, which reduces/eliminates the need for reading and writing local state using `cache.readQuery` and `cache.writeQuery`: #5799

**Comment by ashubham** [comment]
@benjamn Is there a plan to introduce convenience methods like `readField(<name>, <refName>, <booleanToIndicateWhetherToResolveReference>)` or something similar. That could alleviate the need to do `readField` twice as that seems more boilerplate.

**Comment by Banou26** [comment]
> However, you can update cache data asynchronously using the new `cache.makeLocalVar` API

Is there a way to lock the `loading` of `useQuery` via this system ?
Or should you just return an undefined value while waiting for the async to get a result and then set the new value, which will cause a re-render.
This would basically render the `loading` property useless when using async TypePolicies.
Do you guys have any workaround to this problem ?
