### ISSUE TITLE
@apollo/client v3.0.0-beta.33 `partialRefetch: true` unexpected network status

### ISSUE THREAD

**Issue by migueloller** [apollographql/apollo-client#5916]
**Intended outcome:**

Partial refetch results in a network status change of `4` (refetching) followed by `7` (ready). This would be consistent with calling `refetch`.

**Actual outcome:**

Partial refetch results in a network status change of `1` (loading), followed by `4` (refetching), followed by `7` (ready).

**How to reproduce the issue:**

Client: https://codesandbox.io/s/apollo-refetch-bug-client-snbos
Server: https://codesandbox.io/s/apollo-refetch-bug-server-7j3cl

There is code that can be uncommented to see the behavior of `refetch` (i.e., going from `4` to `7`). If todos are added by submitting the form one can see the current behavior of partial refetch (i.e., going from `1` to `4` to `7`).

**Versions**

@apollo/client: 3.0.0-beta.33

**Comment by darkbasic** [comment]
My current workaround for this is to compute a custom loading state based on the properties I am supposed to have before the refetch, but this is quite annoying :(

**Comment by migueloller** [comment]
I will also add to this that `data` goes to `undefined` when `networkStatus` is `1`. The behavior I would expect would be for `data` to never go back to `undefined` once data was successfully fetched. Again, this is `refetch`'s behavior.

It would seem that if `networkStatus` just goes to `4` and then `7`, `data` being `undefined` would stop being an issue.

**Comment by hwillson** [comment]
This should now be fixed in the latest version of `@apollo/client`. Please let us know if you notice any issues. Thanks!

**Comment by migueloller** [comment]
@hwillson, the issue doesn't seem to be fixed. I changed the version to `3.0.0-rc.12` in the front-end repro sandbox and what happens now is that instead of the network status going from `1` to `4` to `7` it goes from `1` to `7`. This can be seen by the flash of "Loading..." when adding a new todo item.

**Comment by migueloller** [comment]
Also, it sees that this issue (https://github.com/apollographql/apollo-client/issues/5535#issuecomment-574740008) is still there. `data` is undefined, as opposed to the last valid value, while refetching partial data.
