### ISSUE TITLE
Data is undefined on cold cache start

### ISSUE THREAD

**Issue by dilame** [apollographql/apollo-client#5924]
My setup

```ts
const graphqlDefaultOptions: DefaultOptions = {
  watchQuery: {
    fetchPolicy: 'cache-and-network'
  }
};
```

**Intended outcome:**

I don't want to recieve undefined data. It breaks the whole application and violates your type definitions.
Your types declares that data will always be defined
https://github.com/apollographql/apollo-client/blob/master/src/core/types.ts#L23
so i cant even check the data without `@ts-ignore`.
It's a pain to check it everywhere

**Actual outcome:**

I recieve undefined data and a lot of errors in console like `ERROR TypeError: Cannot read property 'account' of undefined`

![image](https://user-images.githubusercontent.com/9336742/74078748-21484180-4a3f-11ea-8ab7-cdf10dd5c90d.png)

**How to reproduce the issue:**

Just set `fetchPolicy: 'cache-and-network'` and query smth.

**Versions**

```
  System:
    OS: macOS 10.15.2
  Binaries:
    Node: 13.6.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.87
    Firefox: 65.0
    Safari: 13.0.4
  npmPackages:
    apollo-angular: ^1.8.0 => 1.8.0 
    apollo-angular-link-http: ^1.9.0 => 1.9.0 
    apollo-cache-inmemory: ^1.6.0 => 1.6.5 
    apollo-cache-persist: ^0.1.1 => 0.1.1 
    apollo-client: ^2.6.0 => 2.6.8 
    apollo-link: ^1.2.11 => 1.2.13 
    apollo-link-http: ^1.5.16 => 1.5.16 
  npmGlobalPackages:
    apollo: 2.16.1
```

**Comment by benjamn** [comment]
@dilame Just to be sure I'm understanding, are you calling `client.query` (which returns a single `Promise`), as opposed to using `client.watchQuery` or `useQuery` or something that can receive multiple results? If so, then this is definitely a bug.

**Comment by dilame** [comment]
I'm using client.watchQuery, because `cache-and-network` works only with it.

**Comment by dilame** [comment]
Soory, what type of response are you waiting for? My message is the last one in this thread

**Comment by dilame** [comment]
I'm sorry, i will use this issue for another one bug report because i have the same setup, dont want to duplicate it.

I've found one more bug.

Even if i subscribe to `watchQuery` second time (cache is hot at this moment) i have 2 emits, first with `loading: true`, second is `false`

<img width="478" alt="Снимок экрана 2020-02-22 в 14 23 20" src="https://user-images.githubusercontent.com/9336742/75091491-e38b0300-557e-11ea-8ac0-965db5d2946e.png">

But actually there is NO REQUESTS. I can tell it because i look at `Network` tab of my developer console. So, first, why i have 2 emits even if data is presented in cache? Second - why it shows me loading state when actually it's not?

**Comment by bwhitty** [comment]
@dilame @benjamn I believe this is the exact same thing as https://github.com/apollographql/apollo-client/issues/5947 (just adding another data point to connect dots)

**Comment by hwillson** [comment]
`data` being undefined on a cold cache start is intentional (e.g. https://github.com/apollographql/react-apollo/pull/3388 helps explains some of the reasoning for this). Thanks!
