### ISSUE TITLE
docs website client-side URL routing is broken?

### ISSUE THREAD

**Issue by axelnormand** [apollographql/apollo-client#5927]
I think the client-side URL routing on your docs website is broken?

Reproduction:
1. Go to https://www.apollographql.com/docs/react/
2. In left hand menu click "Api Reference" then "class ApolloClient"
3. client-side JS pushes the URL "https://www.apollographql.com/docs/react/api/apollo-client/"
4. reload page
5. get a page not found error

I think the URL should be something like: "https://www.apollographql.com/docs/react/v2.5/api/apollo-client/"

Thanks, and thank you for a wonderful library btw

**Comment by hwillson** [comment]
The docs have been updated quite a bit since this issue was opened. Let us know if you still think this is an issue. Thanks!
