### ISSUE TITLE
[3.0-beta.33] Properties in updateQuery's prev object are read-only

### ISSUE THREAD

**Issue by gopeter** [apollographql/apollo-client#5932]
**Intended outcome:**
`prev` object in `updateQuery` should be writeable ...

**Actual outcome:**
... but it isn't: 
```
backend.js:6 TypeError: Cannot assign to read only property 'edges' of object '#<Object>'
    at updateQuery (index.tsx:296)
    at ObservableQuery.js:186
    at ObservableQuery.js:242
    at tryFunctionOrLogError (errorHandling.js:3)
    at ObservableQuery../node_modules/@apollo/client/core/ObservableQuery.js.ObservableQuery.updateQuery (ObservableQuery.js:241)
    at Object.next (ObservableQuery.js:184)
    at notifySubscription (Observable.js:135)
    at onNotify (Observable.js:179)
    at SubscriptionObserver.next (Observable.js:235)
    at Object.next (Observable.js:327)
```

**How to reproduce the issue:**
That's the line from the error message: `result.issue.comments.edges = prev.issue.comments.edges.concat([{ node: issueCommentUpsert, __typename: 'IssueCommentEdge' }])` and here's the full example:
```typescript
updateQuery: (prev, { subscriptionData }): GetIssueCommentsQuery => {
  if (!subscriptionData.data) return prev
  const { issueCommentUpsert } = subscriptionData.data

  if (issueCommentUpsert) {
    const result = Object.assign({}, prev)

    // check if issue was updated (and therefore has the same ID)
    const length = prev?.issue?.comments.edges.length ?? 0
    for (let i = 0; i < length; i++) {
      if (result.issue?.comments.edges[i].node.id === issueCommentUpsert.id) {
        result.issue.comments.edges[i].node = issueCommentUpsert

        // return early, since it's not possible to update multiple issues at once
        return result
      }
    }

    // make sure that we have new comments as well as an arry of old ones to merge with
    if (result.issue?.comments?.edges && prev.issue?.comments.edges) {

      // I can't assign to `edges` since it's read-only
      result.issue.comments.edges = prev.issue.comments.edges.concat([{ node: issueCommentUpsert, __typename: 'IssueCommentEdge' }])
      result.issue.comments.count++
    }

    return result
  }

  return prev
}
```

I looked through the repository, issues and current source code/typings and found some cache configurations like `freezeResults` for `InMemoryCache`, but it seems that this options isn't available anymore in 3.0?

**Versions**
I'm using the 3.0-beta:

```
"@apollo/client": "^3.0.0-beta.33",
"@apollo/link-batch-http": "^2.0.0-beta.3",
"@apollo/link-context": "^2.0.0-beta.3",
"@apollo/link-error": "^2.0.0-beta.3",
"@apollo/react-components": "beta",
"@apollo/react-common": "beta",
"@apollo/react-hooks": "beta",
```

**Comment by benjamn** [comment]
Please see the Apollo Client 2.6 blog post for an explanation of our roadmap around immutability: https://blog.apollographql.com/whats-new-in-apollo-client-2-6-b3acf28ecad1. Here's the PR where the `freezeResults` option was deliberately removed, in keeping with this plan: #5153.

One of the reasons destructive updates are temping in `updateQuery` functions is that you're receiving the whole query result, but usually you only want to modify a small part of it.

In AC3, you can define [field-level policies with `merge` functions](https://www.apollographql.com/docs/react/v3.0-beta/caching/cache-field-behavior/) that allow you to skip this unnecessary query processing (and in most cases avoid writing an `updateQuery` function), and focus instead on maintaining individual field values. Once you're no longer having to clone several layers of parent objects just to append an item to a nested array, I don't think you'll miss destructive modification as much.

**Comment by gopeter** [comment]
Thank you very much for the detailed explanation. Going to try this out :)
