### ISSUE TITLE
update a specific property inside object which is stored inside cache

### ISSUE THREAD

**Issue by unutoiul** [apollographql/apollo-client#5940]
How to update a specific object inside object which is stored in the cache apolo client v3.0

the object will look like this:
```
  {
            data: [
                {
                    people: [
                        {
                            id: 1,
                            name: 'lucas',
                        }, {
                            id: 2,
                            name: 'lucas',
                        },
                    ],
                },
            ];
        }
```

let's say I wanna update only the name of the people id 2 and I don't want to write the whole object again in cache, I just want to update the name of people id 2.

how can I do that, is that possible?

**Comment by benjamn** [comment]
See #5909, though you will probably need the objects in `data.people` to have `__typename: "Person"` so that an ID can be computed for them.

**Comment by toddtarsi** [comment]
@unutoiul - I was hitting this issue as well. Using typePolicies to affect the merging logic helped my issue this morning.

https://github.com/apollographql/apollo-client/blob/master/docs/source/caching/cache-field-behavior.md

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
