### ISSUE TITLE
client.clearStore() does not work

### ISSUE THREAD

**Issue by NekitCorp** [apollographql/apollo-client#5941]
Following the documentation https://www.apollographql.com/docs/react/networking/authentication/#reset-store-on-logout trying to clear store after logout.

**Intended outcome:**

Store will be cleaned.

**Actual outcome:**

Nothing happens. Store also filled both in the application and in Apollo Client Developer Tools.

**How to reproduce the issue:**

https://codesandbox.io/s/crazy-bouman-xgdqs

**Versions**

- "@apollo/react-hooks": "3.1.3"
- "apollo-boost": "0.4.7"
- "graphql": "14.6.0"
- "react": "16.12.0"
- "react-dom": "16.12.0"
- "react-scripts": "3.0.1"

**Comment by jorgebaralt** [comment]
I have the same issue, has anything worked for you?

**Comment by NekitCorp** [comment]
> I have the same issue, has anything worked for you?

My temporary solution is to clear the account query and not the entire store. This is not a completely correct solution, but it works in my case.

```ts
App.logout().then(() => client.writeQuery<GetMyAccountQuery, GetMyAccountQueryVariables>({
    query: GetMyAccountDocument,
    data: {
        myAccount: null,
    },
})
```

**Comment by karltaylor** [comment]
> > I have the same issue, has anything worked for you?
> 
> My temporary solution is to clear the account query and not the entire store. This is not a completely correct solution, but it works in my case.
> 
> ```ts
> App.logout().then(() => client.writeQuery<GetMyAccountQuery, GetMyAccountQueryVariables>({
>     query: GetMyAccountDocument,
>     data: {
>         myAccount: null,
>     },
> })
> ```

@NekitCorp Thank you so much for this solution I was going insane trying to get my app to work after user logout after facing a [similar issue](https://stackoverflow.com/questions/64553236/apollos-usequery-data-does-not-update-after-client-resetstore)

**Comment by coelhucas** [comment]
Hey, we've been facing this issue with `3.6.8`.
After a `client.clearStore()`/`client.resetStore()` should we expect an existing `data` object to be invalidated as well or just if I explicitly perform a `readQuery` manually?

I'm unsure either what is happening here refers to this issue or it is an expected behaviour.
