### ISSUE TITLE
@apollo/client@3.0.0-beta.24: SSR: useQuery returns loading and data, then runs a second time

### ISSUE THREAD

**Issue by bwhitty** [apollographql/apollo-client#5947]
**Intended outcome:**
Upon initial `reactDOM.hydrate()` of SSR'd components, **I do not expect `useQuery()` to run twice**. 

Currently it runs once returning
```
{ loading: true, data: { some: 'data' } }
``` 
and then a second time returning
```
{ loading: false, data: { some 'data' } }
```

I would expect an Apollo Client cache which has data via `cache.restore()` already to only run once during SSR hydration, returning
```
{ loading: false, data: { some 'data' } }
```

**Actual outcome:**
During initial "React hydration" of SSR'd components, I am seeing both `loading: true` and `data` present from `useQuery()`, and then the query is immediately re-ran again, and `loading: false` and `data` is the next state:
![Screen Shot 2020-02-14 at 12 51 50 PM](https://user-images.githubusercontent.com/1571966/74566784-21f24380-4f29-11ea-9185-0999815f044c.png)

**How to reproduce the issue:**
1. Load https://codesandbox.io/s/apollo-client-3-ssr-hydration-mismatch-x51p3
2. Look at the console
3. (if you don't see any logs in the console, hard-refresh the codesandbox)

Also posted on Spectrum chat https://spectrum.chat/apollo/apollo-client/loading-true-and-data-during-initial-ssr-re-hydration-3-0-beta~0fca008b-1954-4003-9132-66a0e84ac3f3

**Versions**
```
@apollo/client@3.0.0-beta.24
@apollo/react-ssr@4.0.0-beta.1
```

**Comment by vishwam** [comment]
This is the same issue as #5869

**Comment by hwillson** [comment]
I've verified this is no longer an issue with @apollo/client@3.1.2. Thanks!
