### ISSUE TITLE
Prevent mutation from caching

### ISSUE THREAD

**Issue by alfechner** [apollographql/apollo-client#5950]
I have an `editable` element. On every change I send the serialized content to my server using a mutation, so one mutation per change.

Now cache entries in `ROOT_MUTATION` pile up. The serialized string can be quite long. Is there any way to prevent a mutation from caching the result?

I use version `^3.0.0-beta.23`.

**Comment by cloudratha** [comment]
I had the same issue, and kinda thought it would be a configuration in the cache to mark a mutation as not cacheable.
But it's on the mutation level.

```tsx
const result = useMutation(SOME_MUTATION, {
    fetchPolicy: 'no-cache',
});
```

`no-cache` does not read or write to the cache.

The docs for useMutation don't show the fetchPolicy but it's there.

**Comment by benjamn** [comment]
Using `fetchPolicy: 'no-cache'` is the right solution here, as @cloudratha suggested.

**Comment by benjamn** [comment]
And if you're concerned about the contents of `ROOT_MUTATION` specifically, as opposed to the results of the mutation, it should be safe to do `cache.evict({ id: "ROOT_MUTATION" })`, since that root isn't used to read from the cache (like `ROOT_QUERY` is).

**Comment by benjamn** [comment]
On second though, I'll keep this open in case @alfechner has further questions.

**Comment by henryqdineen** [comment]
Might be slightly related but what's the best practice for making a `'no-cache'` mutation where you still want to update something in the cache after the mutation completes? I noticed that `update()` is not called when `'no-cache'` is enabled. I definitely understand why it works the way it does and our scenario might be super niche.

**Comment by cloudratha** [comment]
@henryqdineen you can use the `onComplete` handler and use the client to write to the cache.
```js
export default function Login() {
  const client: ApolloClient<any> = useApolloClient();
  const [login, { loading, error }] = useMutation<LoginTypes.login, LoginTypes.loginVariables>(
    LOGIN_USER,
    {
      onCompleted({ login }) {
        client.writeQuery({
          query: gql`
             query GetIsLoggedIn {
                isLoggedIn
             }
          `,
          data: {
            isLoggedIn: true
          }
        });
        // client.writeData({ data: { isLoggedIn: true } });
      }
    }
  );

  if (loading) return <Loading />;
  if (error) return <p>An error occurred</p>;

  return <LoginForm login={login} />;
}
```
Taken from the docs: https://www.apollographql.com/docs/tutorial/mutations/#expose-apollo-client-with-useapolloclient
But I hastily updated the example to use the `writeQuery`, as `writeData` is deprecated and removed in v3.

**Comment by kainosnoema** [comment]
Also ran into a fairly major issue today where mutations were piling up in `ROOT_MUTATION` preventing `gc()` from properly removing objects after eviction—they were still reachable from `ROOT_MUTATION`. Assumed that using `no-cache` would do what we want, but not only does it prevent `update()` from being called, but it also literally skips updating the cache with the result of the mutation.

This does make sense in most use cases, but there should really be a way to update objects without caching the mutation itself in `ROOT_MUTATION` as the default behavior causes serious memory leak issues and inability to properly clean up. 🤦

**Comment by hwillson** [comment]
Since the original issue here was answered (https://github.com/apollographql/apollo-client/issues/5950#issuecomment-663540717), I'll close this off. Further issues should be opened separately. Thanks!
