### ISSUE TITLE
[Draft] Subscriptions not triggering watchQuery next handlers

### ISSUE THREAD

**Issue by Akryum** [apollographql/apollo-client#5955]
There is a regression in Apollo Client 3 where the watched queries are not updated if a fragment is updated (for example from a subscription).

Note that I'm using Vue and `@vue/apollo-composable` but I've been able to reproduce using simple `apolloClient.watchQuery` and `apolloClient.writeFragment` calls, so I don't think it's related to either Vue or `@vue/apollo-composable`.

This issue wasn't present in Apollo Client 2.

Example subscription:

```gql
subscription npmScriptUpdated {
  npmScriptUpdated {
    id
    status
  }
}
```

**Intended outcome:**

The watched query is updated (automatic cache update) and the next handler is called (re-rendering the components).

**Actual outcome:**

Nothing happens. Destroying and re-creating the watched query (i.e. switching the virtual route in Vue) forces a read from the cache and the new data is correctly rendered.

**How to reproduce the issue:**

Either sending an update from the server with the subscription or manually modifying the data:

```js
apolloClient.writeFragment({
  id: client.cache.identify({ __typename: 'NpmScript', id }),
  fragment: scriptFragment,
  data: { status: 'running' },
})
```

(todo: reproduction in codesandbox)

I don't really have time to create a full reproduction now with Vue Amsterdam rapidly approaching, but if there is an example application with an object being updated by a subscription with Apollo Client 3, would be happy to fork it. I will have to revert back to Apollo Client 2 for now. :smile_cat: 

**Versions**

  System:
    OS: Linux 5.5 elementary OS 5.1.2 Hera
  Binaries:
    Node: 12.11.0 - ~/.nvm/versions/node/v12.11.0/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.11.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.106
    Firefox: 73.0

I'm not sure if the command is supposed to gather the package versions :smile_cat: so leaving them here from my `package.json`:

    "@apollo/client": "^3.0.0-beta.34",
    "@apollo/link-context": "^2.0.0-beta.3",
    "@apollo/link-error": "^2.0.0-beta.3",
    "@apollo/link-ws": "^2.0.0-beta.3",

**Comment by sgentry** [comment]
I stumbled upon this issue trying to get writeFragment to work as well. This issue clued me in to using

`id: client.cache.identify({ __typename: 'NpmScript', id })`

I was previously just setting the id equal to a string variable. After changing to use `client.cache.identify...` my cache & UI is updated. The example in the docs does not do it this way so it was not clear this is required.

**Comment by hwillson** [comment]
This should be fixed in the latest version of `@apollo/client`. Let us know if it isn't. Thanks!
