### ISSUE TITLE
Timer on polling, reset polling 

### ISSUE THREAD

**Issue by sneznaovca** [apollographql/apollo-client#5960]
Hello,
Is there any way how create countdown or timer for polling?
There is problem with `onCompleted` function #5531.

Second problem is that refetch don't reset polling inverval, I have code
```
const handleButton = () => {
  stopPolling();
  refetch();
  startPolling(POLL_INTERVAL);
}
```
but after call handleButton in half of polling interval it continues. I think that expected behaviour is reset polling interval. Is it bug or feature? :)

**Comment by rgazelot** [comment]
@sneznaovca `startPolling()` will refetch your data. Why did you called `refetch()` just before?

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-client/issues/5960#issuecomment-601636440, it doesn't sound like there is an outstanding issue here, so closing. Thanks!
