### ISSUE TITLE
Tutorial link throws 404

### ISSUE THREAD

**Issue by DarkEye123** [apollographql/apollo-client#5969]
**Intended outcome:**
click on link in the tutorial for 3.0 beta about  inspecting loading states (https://www.apollographql.com/docs/react/v3.0-beta/data/queries/#inspecting-loading-states) redirects to https://github.com/apollographql/apollo-client/blob/master/src/core/networkStatus.ts

**Actual outcome:**
404 -- broken link

**How to reproduce the issue:**
Go to https://www.apollographql.com/docs/react/v3.0-beta/data/queries/#inspecting-loading-states 
Find sentece 'For a full list of all the possible loading states, check out the source.' and lick on the __source__ word.

**Versions**
bug is present also in 2.6 ... 2.5  has different page linked and therefore works.

**Comment by metalcamp** [comment]
https://github.com/apollographql/apollo-client/pull/5813
https://github.com/apollographql/apollo-client/pull/5767
