### ISSUE TITLE
Invariant violations are not searchable using previous methods.

### ISSUE THREAD

**Issue by toddtarsi** [apollographql/apollo-client#5975]
**Intended outcome:**
Invariant violations need to be consistent and be able to be looked up by the same code in development or staging or production or wherever.

**Actual outcome:**
Invariant violations don't match across environments. Invariant violations aren't able to be looked up using [previously described techniques](https://github.com/apollographql/apollo-client/pull/4521#issuecomment-517415011).

Error code from staging:

<img width="764" alt="Screen Shot 2020-02-20 at 6 16 32 PM" src="https://user-images.githubusercontent.com/4707505/74992265-317ff980-540d-11ea-921d-327d38a40686.png">

After reproduction in development environment:

<img width="1125" alt="Screen Shot 2020-02-20 at 11 34 49 PM" src="https://user-images.githubusercontent.com/4707505/75007090-ae28cd00-5439-11ea-9653-5eda3bf61edc.png">

Searching this error code in my development environment: 

<img width="1276" alt="Screen Shot 2020-02-20 at 11 39 50 PM" src="https://user-images.githubusercontent.com/4707505/75007305-4cb52e00-543a-11ea-838c-82f20289b181.png">

Sorry about how small these images are, but basically one environment gives me an invariant violation error code of 53, and the other environment gives me an invariant violation error code of 8 for the same error. That's not good, and everything about how to decode these errors kinda falls apart when this occurs! 😱 

**How to reproduce the issue:**

Perhaps this is something about how I'm building. I'm using Webpack + React-Loadables and perhaps something in the tree-shaking / chunking logic is throwing everything off. If that is the case, I'm not sure how to put together a minimum reproduction.

**Versions**

<img width="500" alt="Screen Shot 2020-02-20 at 6 56 31 PM" src="https://user-images.githubusercontent.com/4707505/74994092-b7eb0a00-5412-11ea-8c99-1e562fb62565.png">

**Comment by hwillson** [comment]
https://github.com/apollographql/apollo-client/pull/6665 was merged to help with this. Thanks!
