### ISSUE TITLE
Destructuring with defaults breaks due to conversion of `undefined` -> `null`

### ISSUE THREAD

**Issue by justinmchase** [apollographql/apollo-client#5977]
**Overview**
I would like to be able to use javascript destructuring on my GQL response objects. However due to the way that GQL always converts `undefined` into `null`, setting default values via destructuring fails.

For example if I did:
```js
const { data: { example: { message = 'No mesage' } = {} } = {} } = useQuery(`
  query Example {
    example {
      message
    }
  }
`, {})

console.log(message)
```

Where `message` is a nullable field, this will fail to set the default value correctly and will print either the message from the server or `null`. I expect destructuring to work here.

I understand why this is the way it is right now, it was [described fairly clearly here](https://github.com/graphql/graphql-js/issues/1298#issuecomment-377365916) by @leebyron. I don't _like_ it but I understand that because JSON itself does not support undefined and it will drop the fields if the values are undefined rather than leave them with in an `undefined` value.

I personally think that this shouldn't matter and this should be the default behavior of gql; it _should_ drop the fields rather than return null value fields. But alas it does not.

But despite this limitation I should be able to, at the very least, _opt-in_ to setting undefined values to fields rather than nulls which would allow me to use javascript destructuring as it is intended.

So I made a custom apollo-link which does this; replaces all `null` values in the response data with `undefined` but further down the stack `apollo-client` experiences a number of hard to debug issues where it makes assumptions about nulls specifically and also fails to distinguish between a property with an `undefined` value and an object which does not have a property defined at all. These are two different states in javascript.

**Intended outcome:** 
I would like to be able to convert all `null` values to `undefined` values in my result objects, via a custom apollo-link.

**Actual outcome:**
Warnings are produced saying "Field Missing" even though the field actually exists (with an undefined value) and an error occurs. Locally fixing that one issue results in similar issues throughout the codebase.

**How to reproduce the issue:**
Here is my CleanLink code:
```js
import { ApolloLink } from 'apollo-link';
import Observable from 'zen-observable'

function cleanObject(value) {
  return Object
    .entries(value)
    .reduce((obj, [k, v]) => Object.assign(obj, { [k]: clean(v) }), {})
}

function clean(value) {
  if (value == null) return undefined;
  if (Array.isArray(value)) return value.map(v => clean(v))
  if (value instanceof Date) return value;
  if (typeof value === "object") return cleanObject(value);
  return value;
}

class CleanLink extends ApolloLink {
  request(operation, forward) {
    const operationObserver = forward(operation);
    return new Observable(observer => {
      const subscription = operationObserver.subscribe({
        next: (result) => {
          const { data, ...rest } = result;
          const cleanedData = clean(data);
          observer.next({ data: cleanedData, ...rest });
        },
        error: error => {
          observer.error(error);
        },
        complete: observer.complete.bind(observer),
      });

      return () => {
        if (subscription) subscription.unsubscribe();
      };
    });
  }
}

export function createCleanLink() {
  return new CleanLink();
}
```

I am then attaching it to my apollo client as the first link:
```js
import { createCleanLink } from "./link"

const cleanLink = createCleanLink()
const client = new ApolloClient({
  ...other,
  link: cleanLink.concat(authLink).concat(httpLink),
})
```

Then make any GQL request with a non-nullable response field. The GQL server will return an object where the field is null and this will convert the null value to an undefined value.

**Versions**
```
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 10.18.1 - ~/.nvm/versions/node/v10.18.1/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v10.18.1/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Safari: 13.0.5
  npmPackages:
    @apollo/react-hooks: ^3.1.3 => 3.1.3 
    @apollo/react-testing: ^3.0.0 => 3.1.3 
    apollo-cache: ^1.3.2 => 1.3.2 
    apollo-cache-inmemory: ^1.6.0 => 1.6.5 
    apollo-client: ^2.6.3 => 2.6.4 
    apollo-link-context: ^1.0.17 => 1.0.19 
    apollo-link-error: ^1.1.10 => 1.1.12 
    apollo-link-http: ^1.5.14 => 1.5.16 
    apollo-utilities: ^1.3.2 => 1.3.2 
    react-apollo: ^3.0.0 => 3.1.3 
  npmGlobalPackages:
    apollo-cache-inmemory: 1.6.5
    apollo-link: 1.2.13
```

**More Info**
Most of the errors appear to be coming from code related to caching (I'm using the inmemory cache), such as this line:
https://github.com/apollographql/apollo-client/blob/ed66999bac40226abfeada8d6c83b454636bb4b0/packages/apollo-cache-inmemory/src/writeToStore.ts#L174

Which should be doing something more like:
```js
if (result.hasOwnProperty(resultFieldKey)) {
```

And this line [apollo-cache-inmemory]:
https://github.com/apollographql/apollo-client/blob/ed66999bac40226abfeada8d6c83b454636bb4b0/packages/apollo-cache-inmemory/src/writeToStore.ts#L285

Which should be using `== null` instead of `=== null`.

**Comment by benjamn** [comment]
It's fine to experiment with deviations from the GraphQL specification to see what works, but you really need to be working with the latest code (`@apollo/client`, not `apollo-client`) if you want us to consider any changes to accommodate nonstandard usage.

I would also encourage you to find independent reasons why those changes should be made, so we can skip the whole discussion of whether your likes and dislikes regarding the GraphQL spec are worth entertaining.

> and also fails to distinguish between a property with an `undefined` value and an object which does not have a property defined at all. These are two different states in javascript.

The `null` and `undefined` values are also different! You're assuming you can just replace any `null` you get with `undefined`, without knowing whether that means an `undefined` value or the absence of a value. How is that safe, exactly?
