### ISSUE TITLE
Docs: 404 link to Network Status documentation

### ISSUE THREAD

**Issue by bstro** [apollographql/apollo-client#5994]
On the v2.6 docs, the last sentence of [Inspecting loading states](https://www.apollographql.com/docs/react/data/queries/#inspecting-loading-states) documentation refers users to [this url](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/networkStatus.ts) for documentation on loading states, which 404s.

**Comment by kinow** [comment]
PR merged, this issue can be closed :+1:

**Comment by hwillson** [comment]
Sounds like this was resolved - thanks!
