### ISSUE TITLE
UseSubscription does not subscribe to subscription

### ISSUE THREAD

**Issue by Antoine-C** [apollographql/apollo-client#5996]
**Intended outcome:**

I'm trying to setup subscription with react hooks and apollo-client. I'm using **apollo-server-hapi** in the backend to handle GraphQL with Hapi. I'm pretty confident my backend is setup correctly given I can see when a new client subscribe and furthermore I can get subscription to work with graphiql.

### Client setup

<details>
<summary>index.js</summary>

```javascript
import { ApolloClient } from "apollo-client";
import { InMemoryCache } from "apollo-cache-inmemory";
import { ApolloProvider } from "@apollo/react-hooks";
import { WebSocketLink } from "apollo-link-ws";
import { getMainDefinition } from "apollo-utilities";
import { split } from "apollo-link";
import { HttpLink } from "apollo-link-http";

const httpLink = new HttpLink({
    uri: "http://localhost:3000/graphql"
});

const wsLink = new WebSocketLink({
    uri: `ws://localhost:3000/graphql`,
    options: {
      reconnect: true,
      connectionParams: async () => {
        return "hello world";
      }
    }
});

const link = split(
    // split based on operation type
    ({ query }) => {
      const { kind, operation } = getMainDefinition(query);
      return kind === "OperationDefinitions" && operation === "subscription";
    },
    wsLink,
    httpLink
);

const client = new ApolloClient({
    cache: new InMemoryCache(),
    link
});


 ReactDOM.render(
      <Provider store={store}>
        <BrowserRouter>
            <ApolloProvider client={client}>
              <MyAppContent />
            </ApolloProvider>
        </BrowserRouter>
      </Provider>,
      document.getElementById("root")
);
```
</details>

<details>
<summary>In my component</summary>

```javascript
import { useSubscription } from "@apollo/react-hooks";
import gql from "graphql-tag";

const COMMENTS_SUBSCRIPTION = gql`
  subscription somethingChanged {
    somethingChanged {
      id
    }
  }
`;

const UsersList = () => {
   const { data, loading } = useSubscription(COMMENTS_SUBSCRIPTION, {
    shouldResubscribe: true
  });

  console.log("data", data, "loading", loading);

return <p>My component</p>
}
```
</details>

### Server setup

<details>
<summary>index.ts</summary>

```javascript
import { PubSub } from "graphql-subscriptions";
import { ApolloServer, gql } from "apollo-server-hapi";

setTimeout(() => {
  console.log("pubsub trigger");
  pubsub.publish("somethingChanged", {
    somethingChanged: { id: 1, content: "Hello!" }
  });
}, 20 * 1000);

const typeDefs = gql`
  type Query {
    dummy: String
  }

  type Subscription {
    somethingChanged: Result
  }

  type Result {
    id: String
  }
`;

const resolvers = {
  Subscription: {
    somethingChanged: {
      subscribe: () => {
        console.log("Someone subscribed to this event");
        return pubsub.asyncIterator("somethingChanged");
      }
    }
  }
};

const serverGQL = new ApolloServer({
    typeDefs,
    resolvers,
    subscriptions: {
      onConnect: connectionParams =>
        console.log("CLIENT CONNECTED", connectionParams)
    }
  });

// Non relevant Hapi code
```
</details>

### More infos

I can see the webscoket connecting to my API in chrome devtools and as I said earlier when I use GraphiQL I can see the log in my server _"Someone subscribed to this event"_.
To finish I can see in XHR that a POST request is made to my API with the subscription content (I guess it's to tell Apollo server someone want to subscribe to this subscription ?)

<details>
<summary>Chrome devtools</summary>

<img width="909" alt="Capture d’écran 2020-02-23 à 15 14 49" src="https://user-images.githubusercontent.com/3541876/75113565-5794dc00-564f-11ea-8b8f-b85bf9d0a991.png">

<img width="922" alt="Capture d’écran 2020-02-23 à 15 18 57" src="https://user-images.githubusercontent.com/3541876/75114111-975dc280-5653-11ea-89b2-e686d182041c.png">
</details>

**Actual outcome:**

I can't get the frontend to subscribe to the **somethingChanged** subscription however we I open graphiql at http://localhost/graphql and I put the exact same content as in _COMMENTS_SUBSCRIPTION_ I can see that everything is working as expected.

**How to reproduce the issue:**

I've put as much code as I can to be as thorough as possible to explain my problem.

**Version**
<details>
<summary>Infos</summary>

```
 System:
    OS: macOS Mojave 10.14.5
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.2 - ~/Documents/development/GQLProject/node_modules/.bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Safari: 12.1.1
  npmPackages:
    @apollo/react-hooks: ^3.1.3 => 3.1.3
    apollo-boost: ^0.4.7 => 0.4.7
    apollo-link-ws: ^1.0.19 => 1.0.19
```
</details>

**Comment by martimalek** [comment]
@Antoine-C did you manage to fix this?

**Comment by Antoine-C** [comment]
@martimalek I gave up for the moment and used socket.io for the subscription
Maybe I'll try with the new version of graphql from Apollo

**Comment by martimalek** [comment]
Thanks for the quick answer, sadly I'm on the verge of also giving up...

**Comment by martimalek** [comment]
Maybe it is the same as [this issue](https://github.com/apollographql/apollo-client/issues/6520)

**Comment by NeverovN** [comment]
hello there. I have similar issue. I use pure Apollo Server on back. and when I subscribe to events in playground, everything work fine and I have correct responses when events happen. however if I try to use useSubscription hook (to be precise I use gel generated types, so this is useNewPostSubscription instead of useMutation), I have no response at all. the parameter loading is always true and I never get into subscription section (I know t since I have several console logs in there). can you please help me with my issue

**Comment by NeverovN** [comment]
actually I tried to replace useNewPost with useSubscription and got exactly the same situation as before

**Comment by NeverovN** [comment]
worth to mention. I have loading === true only if I manually start subscription out of playground. otherwise there is no response at all
