### ISSUE TITLE
unexpected behavior of apollo link retry on 400 error

### ISSUE THREAD

**Issue by SanthoshBanavath** [apollographql/apollo-client#6001]
`apollo-link-retry description: Attempt an operation multiple times if it fails due to network or server errors.
`
I have used apollo-link-retry to retry calls on the occurrence of server errors(5xx). But when 400 error(bad request) is occurring it is considering it as 5xx error and keep retrying.
Why this is happening?
Which error codes are actually considered as a network error?

**Comment by dylanwulf** [comment]
Network error is anything that's not in the range of 200-299
