### ISSUE TITLE
How to upload a file in V3

### ISSUE THREAD

**Issue by outerlook** [apollographql/apollo-client#6010]
Hi! I used to solve file uploads with [apollo-upload-client](https://github.com/jaydenseric/apollo-upload-client) on apollo-client.
As V3 changed some things about links, is there any examples on how could I send file uploads?

**Comment by jguffey** [comment]
This isn't an issue with apollo-client, you should ask the maintainer of [apollo-upload-client](https://github.com/jaydenseric/apollo-upload-client) if they have plans to support v3 of apollo-client. It looks like someone has already asked about v.3 support [here](https://github.com/jaydenseric/apollo-upload-client/issues/174).

**Comment by dohomi** [comment]
Isn't file upload part of the core of `apollo-client` v3 somehow? I mean for me that would make sense if something that crucial as file uploads would be part of the the core functionality.

**Comment by dylanwulf** [comment]
@dohomi Unfortunately file uploads are not part of the core `apollo-client`. File uploads are actually not even a part of the official GraphQL specification document.

**Comment by dohomi** [comment]
@dylanwulf ok I am bit confused because other GQL clients support it by default. I'll move to a different library for now thanks for the clarification.

**Comment by jaydenseric** [comment]
@dylanwulf 

> File uploads are actually not even a part of the official GraphQL specification document.

The [GraphQL foundation](https://foundation.graphql.org) doesn't have a spec ready yet for any form of requests, including the most commonly used POST requests. A working draft of a "GraphQL over HTTP" specification is being worked on by the GraphQL over HTTP working group (I'm an active member) here:

https://github.com/APIs-guru/graphql-over-http

We are standardizing GET and basic POST requests first, and will later look at things like multipart requests and maybe subscriptions. At that time I will strongly advocate for adoption of the [GraphQL multipart request spec](https://github.com/jaydenseric/graphql-multipart-request-spec).

**Comment by dohomi** [comment]
For me the biggest question is, why ApolloServer supports file upload but ApolloClient doesn't which is a little bit unexpected if in my opinion. Because both are run under the same organisation

**Comment by PhilippS93** [comment]
Is the upload feature on the roadmap of this library? It is very crucial for most mobile apps..
