### ISSUE TITLE
Pass query variable to sub query only

### ISSUE THREAD

**Issue by ujwaldhakal** [apollographql/apollo-client#6018]
query: gql`
          {
            me{
              products(page:$currentPage){
              data{
                id,
                name,
                slug
              },
              paginatorInfo{
                total,
                perPage,
                currentPage,
                lastPage
              }
            }
            }
          }
        `,
        variables: {
          currentPage: 1
        }
      });

This is my developed api now i want to pass ariable to logged in users me  to products only. Whenever i use this syntax i am getting error on apolloclient

**Comment by cristiandley** [comment]
You should add details to this issue.
 
Not sure what you want but I think you should define your query as:

```
const GET_ALL_BY_PAGE = gql`
  query($currentPage: Int!) {
    data(page: $currentPage) {
      id
      name
      slug
    }
    ...
  }
`;
```

You cant wrap the query on an new element `me` remember is a graph.

**Comment by ujwaldhakal** [comment]
Thanks
