### ISSUE TITLE
[3.0.0-beta.38] Cannot find module: 'graphql/language/printer'

### ISSUE THREAD

**Issue by schematis** [apollographql/apollo-client#6019]
**Description**
Trying to build React 16.13 with typescript results in the following:
```
$ react-scripts build
Creating an optimized production build...
Failed to compile.

./node_modules/@apollo/client/link/http/selectHttpOptionsAndBody.js
Cannot find module: 'graphql/language/printer'. Make sure this package is installed.

You can install this package by running: yarn add graphql/language/printer.
```
Looking at past issues this seems to be a regression or at least that this was omitted from the project's package.json.

**Versions**
  System:
    OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
  Binaries:
    Node: 12.15.0 - ~/.nvm/versions/node/v12.15.0/bin/node
    Yarn: 1.22.0 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.15.0/bin/npm
  npmPackages:
    @apollo/client: ^3.0.0-beta.38 => 3.0.0-beta.38

**Comment by hwillson** [comment]
@schematis do you have the `graphql` package installed?

**Comment by schematis** [comment]
I do now and it's working. The issue seems to be that this used to pull from graphql-tag instead of graphql and nowhere does it say you need to install grapqhql alongside of apollo/client (it's not even a peer dependency).

**Comment by henryqdineen** [comment]
Seems like `graphql` is a peer dep now.

https://github.com/apollographql/apollo-client/blob/23b17fa7283b21966d1c633c52b848f12b4a211e/package.json#L57-L60

**Comment by schematis** [comment]
Ok cool. However since the system errors out without graphql installed, shouldn't it be a direct dependency?

**Comment by Jonathannsegal** [comment]
@schematis, this should be something that is added to the docs even if it is added as a direct dependency.

**Comment by bryancuster** [comment]
I have the following (the only three apollo/graphql dependencies) and still receive this error.
```json
...
    "@apollo/client": "^3.1.3",
    "babel-plugin-graphql-tag": "^3.0.0",
    "graphql": "^15.3.0",
...
```


```
 WARNING  Compiled with 10 warnings                                                                                      9:22:25 AM
 warning  in ./node_modules/@apollo/client/core/LocalState.js
"export 'BREAK' was not found in 'graphql/language/visitor'
 warning  in ./node_modules/@apollo/client/link/http/selectHttpOptionsAndBody.js
"export 'print' was not found in 'graphql/language/printer'
 warning  in ./node_modules/@apollo/client/utilities/graphql/directives.js
"export 'visit' was not found in 'graphql/language/visitor'
```

**Comment by jslau** [comment]
@bryancuster were you ever able to get this working? i'm running into the same issue

**Comment by bryancuster** [comment]
@jslau I have not been able to fix it, though it has been some time since I tried last. Our projects are still using `0.13.0` for `graphql`.

**Comment by miqdadfwz** [comment]
@bryancuster @jslau my application runs with SSR support and the error only happens only for the server. I managed to fix this by put `graphql` module as `externals` option in webpack.

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!

**Comment by neutraali** [comment]
@hwillson This issue is still very much alive, it seems. Installed and reinstalled the following packages several times:
 
 ```
 "@apollo/client": "^3.4.17"
"graphql": "^15.7.2"
"graphql-tag": "^2.12.6"
```

Experiencing the same `export X was not found in 'graphql'` -warnings as the others have mentioned, where X is something like `visit`, `print`, `parse` and/or `BREAK`.
