### ISSUE TITLE
onCompleted is not called in some cases

### ISSUE THREAD

**Issue by ms** [apollographql/apollo-client#6021]
**Intended outcome:**
`onCompleted` is called in all cases if the query resolves with data (after `loading` becomes false)

**Actual outcome:**
In some cases, `onCompleted` is never called.

**How to reproduce the issue:**
https://github.com/apollographql/apollo-client/pull/6020

**Versions**
3.0.0-beta38 (although it's likely it's present in other versions)

**Comment by hwillson** [comment]
Closing for the reasons outlined in https://github.com/apollographql/apollo-client/pull/6020#issuecomment-597775686 - thanks!
