### ISSUE TITLE
[3.0.0-beta.38] Mocking server data via @client directive

### ISSUE THREAD

**Issue by nodkz** [apollographql/apollo-client#6022]
I tried Mocking according to https://www.apollographql.com/docs/react/v3.0-beta/development-testing/client-schema-mocking/

Here is an example code: https://github.com/nodkz/example-apollo3/blob/master/src/pages/mock.tsx

For data:
```js
const authors = [
  { id: 1, firstName: 'Tom', lastName: 'Coleman' },
  { id: 2, firstName: 'Sashko', lastName: 'Stubailo' },
  { id: 3, firstName: 'Mikhail', lastName: 'Novikov' },
];

const posts = [
  { id: 1, authorId: 1, title: 'Introduction to GraphQL', votes: 2 },
  { id: 2, authorId: 2, title: 'Welcome to Meteor', votes: 3 },
  { id: 3, authorId: 2, title: 'Advanced GraphQL', votes: 1 },
  { id: 4, authorId: 3, title: 'Launchpad is Cool', votes: 7 },
];
```

For query:
```graphql
query MockQuery {
  posts @client {
    title
    authorId
    author { firstName }
  }
}
```

With ApolloClient 3 I got such an uninformative error: 
<img width="968" alt="Screen Shot 2020-03-05 at 17 56 59" src="https://user-images.githubusercontent.com/1946920/75979844-90646900-5f0b-11ea-97ce-1e1d7f754f97.png">

With ApolloClient 2 I got a more informative warning:
<img width="509" alt="Screen Shot 2020-03-05 at 18 07 18" src="https://user-images.githubusercontent.com/1946920/75980201-33b57e00-5f0c-11ea-88a6-999d4813a3cd.png">

### A-ha moment (need add `__typename` to data-set)

Change data to
```js
const authors = [
  { id: 1, firstName: 'Tom', lastName: 'Coleman', __typename: 'Author' },
  { id: 2, firstName: 'Sashko', lastName: 'Stubailo', __typename: 'Author' },
  { id: 3, firstName: 'Mikhail', lastName: 'Novikov', __typename: 'Author' },
];

const posts = [
  { id: 1, authorId: 1, title: 'Introduction to GraphQL', votes: 2, __typename: 'Post' },
  { id: 2, authorId: 2, title: 'Welcome to Meteor', votes: 3, __typename: 'Post' },
  { id: 3, authorId: 2, title: 'Advanced GraphQL', votes: 1, __typename: 'Post' },
  { id: 4, authorId: 3, title: 'Launchpad is Cool', votes: 7, __typename: 'Post' },
];
```

And nested @client queries work as expected in AC2 and AC3:

<img width="640" alt="Screen Shot 2020-03-05 at 18 10 02" src="https://user-images.githubusercontent.com/1946920/75980395-91e26100-5f0c-11ea-94d1-214ac060d54d.png">

## Needs to

1) Provide better error if possible (@benjamn)
2) Improve documentation with `__typename` property for supporting mocking with nested queries (@hwillson)

**Comment by mocantimoteidavid** [comment]
Hey there, I really don't understand how you were able to successfully mock a query that has the `@client` directive.
I'm guess some things got fixed maybe in the newer apollo-client versions, since I'm using the 2.6.8, and I cannot seem to find a solution for the problem very well explained in this issue here: https://github.com/apollographql/apollo-client/issues/4532

**Comment by nodkz** [comment]
@mocantimoteidavid I'm mocking server responses that are not ready yet. And when they are done by backenders I just remove `@client` directive and all data fetched from server.

It works with AC3 https://github.com/nodkz/example-apollo3/blob/master/src/pages/mock.tsx
And it works with AC2 https://github.com/nodkz/example-apollo2/blob/master/src/pages/mock/index.tsx
