### ISSUE TITLE
Feature request: register fragment data change callbacks to automatically writeQuery etc. for a given fragment

### ISSUE THREAD

**Issue by jedwards1211** [apollographql/apollo-client#6029]
Let's say we have the following schema

```graphql
scalar DateTime

type Post = {
  id: Int!
  content: String!
}

type User = {
  id: Int!
  name: String!
  posts(from: DateTime, to: DateTime): [Post!]!
}

query {
  Post(id: Int!): Post!
  User(id: Int!): User!
}
```
If I fetch
```graphql
query example($userId: Int!) {
  User(id: $userId) {
    id
    name
    Posts {
      id
      content
    }
  }
}
```
I wish I could tell `ApolloClient` to automatically `writeQuery` for `Post(id: Int!)` for each of those posts it receives in the response, or for any other posts received in other responses, so that `Post(id: $id)` queries will be cached.

This is a super common thing; object types with an id field usually have a corresponding query to find by that id.  It's arguably a mistake that GraphQL doesn't provide a standard form for such queries, and ApolloClient can't make any assumptions.  But, it would be great if we could tell it in one single place to do things like this, instead of having a bunch of `writeQuery` calls scattered everywhere (this leads to a lot of spaghetti code).

```js
const autoPostQuery = gql`
fragment PostFragment on Post {
  id
  name
}
query postById($id: Int!) {
  Post(id: $id) {
     ...PostFragment
  }
}
`

apolloClient.onFragmentChange({
  fragment: autoPostQuery,
  fragmentName: 'PostFragment',
}, (fragmentData) => apolloClient.writeQuery({
  query: autoPostQuery,
  variables: {id: fragmentData.id},
  data: fragmentData,
})
```

**Comment by jedwards1211** [comment]
Okay, I see that there's a `cacheRedirects` feature in `InMemoryCache`, very elegant.  We need to raise awareness of it...everyone should know about it, I shouldn't just be finding out after years of using Apollo.

It's possible that the API I propose here would be able to accomplish some things that `cacheRedirects` can't.  But I'll close this for now

**Comment by chemicalkosek** [comment]
AFAIK cacheRedirects have been removed in 3.0. You need to use fieldPolicy: [https://deploy-preview-5677--apollo-client-docs.netlify.com/docs/react/v3.0-beta/caching/cache-field-behavior/](https://deploy-preview-5677--apollo-client-docs.netlify.com/docs/react/v3.0-beta/caching/cache-field-behavior/)

**Comment by jedwards1211** [comment]
@chemicalkosek  Thanks for the tip!

**Comment by chemicalkosek** [comment]
@jedwards1211 [https://github.com/apollographql/apollo-client/issues/5983](https://github.com/apollographql/apollo-client/issues/5983)
