### ISSUE TITLE
[3.0-beta] Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by ashubham** [apollographql/apollo-client#6035]
Trying to use `apollo-client` with react using rollup.

**Intended outcome:**
Apollo client should bundle and load.

**Actual outcome:**

The loading fails at runtime with `Uncaught ReferenceError: require is not defined`.

This is due to https://github.com/apollographql/apollo-client/blob/23b17fa7283b21966d1c633c52b848f12b4a211e/src/react/react.ts#L8

<img width="525" alt="image" src="https://user-images.githubusercontent.com/6115911/76217108-d127ef00-6237-11ea-9271-99f92a20c801.png">

It might be better to use `import` instead of `require`.

**How to reproduce the issue:**

Use rollup for building the app (using apollo-client/react).
PS: Set the output format to `es`. (Fails with 'cjs' too)

**Versions**

Apollo-client: 3.0-beta.38 (React)

**Comment by ashubham** [comment]
@benjamn @hwillson Any guidance here ?

**Comment by hwillson** [comment]
@ashubham can you provide a small runnable reproduction that demonstrates the issue you're seeing with Rollup? We have an AC3 non-React Rollup based example [here](https://github.com/apollographql/apollo-client/tree/master/examples/bundling/no-tree-shaking/rollup-ac3-no-react) that demonstrates how this can be achieved with Rollup.
