### ISSUE TITLE
[Documentation] recommend using typePolicies instead of writeQuery/writeFragment whenever possible

### ISSUE THREAD

**Issue by jedwards1211** [apollographql/apollo-client#6036]
I'm happy to make a PR for this eventually, just bringing this up because I don't have time atm...

I went years without knowing about `cacheRedirects` and thinking `writeQuery`/`writeFragment` was the only way to accomplish what I needed.  The docs don't raise enough awareness of this feature.

This is still a problem in v3 since the Local State Management docs don't mention `typePolicies`.  We should add a note **above** the **Updating local state** section, something like

> In many cases, [using `typePolicies` to customize cache reads](https://deploy-preview-5677--apollo-client-docs.netlify.com/docs/react/v3.0-beta/caching/cache-field-behavior/) is easier and more maintainable than manually reading or writing local state.  For example, after querying a list of users, if you want a query for one of those users by id to be served from the cache, this is much easier to accomplish using `typePolicies` than by doing `writeQuery` for each user in the list.

**Comment by hwillson** [comment]
Thanks @jedwards1211 - we're currently working on overhauling all docs sections for the upcoming AC3 launch. These changes should start to appear in PR's later this week.

**Comment by hwillson** [comment]
Docs changes are happening in https://github.com/apollographql/apollo-client/pull/6429 and can be tracked there, so I'll close this off. Thanks!
