### ISSUE TITLE
Infinitely Loading Query with useQuery and client

### ISSUE THREAD

**Issue by bbrinx** [apollographql/apollo-client#6038]
It seems that when calling `useQuery` while passing through a client the query always returns loading true and reruns infinitely. This doesn't happen when using the client from the context. This error sounds very similar to https://github.com/apollographql/react-apollo/issues/3270 and https://github.com/apollographql/react-apollo/issues/3774 and a few more. 

**How to reproduce the issue:**
```
const publicHttpSettings = 'http://localhost:3000/public_api'

httpLink = new HttpLink(publicHttpSettings);

const publicClient = new ApolloClient<any>({
  connectToDevTools: true,
  link: httpLink,
  cache: new InMemoryCache(),
});

const { loading, error, data } = useQuery(query, {
  variables: vars,
  skip: skip,
  displayName: displayName,
  client: publicClient,
});

console.log(data) // undefined
console.log(error) // undefined
console.log(loading) // true
```

**Versions**
```
"@apollo/client": "^3.0.0-beta.23",
"@apollo/link-batch-http": "^2.0.0-beta.3",
"@apollo/link-context": "^2.0.0-beta.3",
"@apollo/link-error": "^2.0.0-beta.3",
```

**Comment by dylanwulf** [comment]
In your example, you're re-creating the client on every re-render, which is why you see infinite rerunning. Make sure that you're using the same client instance between re-renders.

**Comment by bbrinx** [comment]
@dylanwulf thanks! Totally missed that
