### ISSUE TITLE
README points to broken link

### ISSUE THREAD

**Issue by sw-yx** [apollographql/apollo-client#6042]
**Intended outcome:**
readme links to https://www.apollographql.com/docs/react/api/core, which should be the library's docs

**Actual outcome:**
404
![image](https://user-images.githubusercontent.com/6764957/76375258-bf1f7c80-631b-11ea-86ba-26040b4c7685.png)

**How to reproduce the issue:**
https://www.apollographql.com/docs/react/api/core

**Comment by hwillson** [comment]
Fixed - thanks @sw-yx!

**Comment by bbrinx** [comment]
@hwillson still getting a 404
