### ISSUE TITLE
Apollo client v3 beta huge bundle size

### ISSUE THREAD

**Issue by brielov** [apollographql/apollo-client#6043]
Hi, I wanted to test the new v3 client with an empty react project and I noticed a very large bundle size.

Production build with `parcel`:

* 336.2 KB total 
* 114.3 KB `react-dom`
* 133.9 KB `@apollo/client`

```javascript
import React from "react";
import { render } from "react-dom";
import { ApolloProvider, ApolloClient, InMemoryCache } from "@apollo/client";

const client = new ApolloClient({
  cache: new InMemoryCache(),
  uri: "http://localhost:4000/graphql"
});

const App = () => {
  return <div />;
};

render(
  <ApolloProvider client={client}>
    <App />
  </ApolloProvider>,
  document.getElementById("root")
);

```

![_Users_brielov_Code_micro-react_dist_report html (2)](https://user-images.githubusercontent.com/42145089/76411649-fd935680-6370-11ea-94ed-aa02be80f5ae.png)

I mean, +330 KB just for a hello world app seems a little to much. So my question is, am I doing something wrong? Or is this just the way it is?

**Comment by benjamn** [comment]
Something definitely seems to be configured incorrectly!

The full minified bundle (`@apollo/client/apollo-client.cjs.min.js`) is only 89.4 minified (23.6KB after gzip) without any tree shaking or other optimizations, so I wonder if you're somehow including `@apollo/client` more than once, or the tree map visualization is counting things more than once?

[Here](https://github.com/apollographql/apollo-client/blob/809cd84b5b909d6835b7faae13105d7d887e8364/config/rollup.config.js#L77-L89) are the `terser` minifier options we use when measuring bundle sizes. Note especially the removal of `process.env.NODE_ENV` checks (which is something you have to do for React as well).

@hwillson Maybe we should add an example of recommended Parcel bundling to https://github.com/apollographql/apollo-client/tree/master/examples/bundling ?

**Comment by brielov** [comment]
@benjamn I don't really know, the app that I posted here is really just all there is.

Parcel output without `@apollo/client`:
```
dist/src.a52afb2a.js.map    262.95 KB    111ms
dist/src.a52afb2a.js        128.64 KB    625ms
dist/index.html                 140 B     21ms
```

And here is the code:
```

**Comment by 3nvi** [comment]
I've verified that apollo is indeed < 30KB when gzipped. I think this is not an error on the client's side, but some configuration with your project.

I'm using ` "@apollo/client": "^3.0.0-beta.39"`

<img width="516" alt="Screen Shot 2020-03-12 at 11 34 23 AM" src="https://user-images.githubusercontent.com/10436045/76507450-7ec41980-6455-11ea-9352-d45ac739aeb1.png">

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-client/issues/6043#issuecomment-598092211, something seems to be up with your bundling configuration. Closing for now - thanks!
