### ISSUE TITLE
useQuery returning old data after resetStore or clearStore in beta

### ISSUE THREAD

**Issue by zsolt-dev** [apollographql/apollo-client#6044]
**Intended outcome:**

Rerender components with correct empty state after clearStore or resetStore

**Actual outcome:**

apollo-client supplies old data

**How to reproduce the issue:**

Click on the clear store button.. you can try to replace clearStore with ResetStore
https://codesandbox.io/s/xenodochial-hooks-p0i15

My actual use case is calling logout mutation and then clearing / reseting the store. And since the useQuery return the old data after store reset, it does not redirects to login page.

**Versions**
```
  System:
    OS: macOS 10.15.3
  Binaries:
    Node: 13.3.0 - ~/.nvm/versions/node/v13.3.0/bin/node
    npm: 6.13.1 - ~/.nvm/versions/node/v13.3.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 71.0
    Safari: 13.0.5
  npmPackages:
    @apollo/client: ^3.0.0-beta.39 => 3.0.0-beta.39
    apollo-link-error: ^1.1.12 => 1.1.12
    apollo-server-express: ^2.9.16 => 2.9.16
    apollo-upload-client: ^12.1.0 => 12.1.0
```

**Comment by zsolt-dev** [comment]
It looks like I fixed it with providing this as an option to useQuery:

```
partialRefetch: true,
```

**Comment by ryanwiesjahn** [comment]
I'm also having this issue. `partialRefetch` does not seem to help, both in my application as well as your example codesandbox.

**Comment by dminkovsky** [comment]
Yeah what are you supposed to do if you use `clearStore()`? How do you re-subscribe to queries that `useQuery` subscribed to before?

**Comment by dminkovsky** [comment]
Seems to be discussed here? https://github.com/apollographql/apollo-client/issues/6359

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
