### ISSUE TITLE
v3 beta: useMutation doesn't return mocked result while testing

### ISSUE THREAD

**Issue by onemorekiril** [apollographql/apollo-client#6048]
I've reproduced the issue using v3 beta (check the following link). [Codesandbox](https://codesandbox.io/s/test-free-graphql-api-northwind-bymmv).
Also I've checked it with v2.6 stable, and it works as expected. [Codesandbox](https://codesandbox.io/s/test-free-graphql-api-northwind-v26-zn0f0)

In this small app, you can get a product from free api and update its name. Once you're done this, you will see the "Updated" status, which is determined after the mutation returns the result data. 
Having updated, I also cleared the input value by calling the setState inside the onCompleted callback.

I provided the tests to check it all.
Although onCompleted callback successfully called mocked setState with empty string, mutation doesn't return a result and status string is still empty.

**Comment by hwillson** [comment]
This should no longer be an issue in `@apollo/client@latest` - let us know otherwise, thanks!
