### ISSUE TITLE
TypeScript erroneously requires all or no variables in refetch()

### ISSUE THREAD

**Issue by amourzenkov** [apollographql/apollo-client#6066]
**Intended outcome:**

```javascript
const { refetch } = useQuery<GetQuery, GetQueryVariables>(myQuery, {
  // all variables are required.
  variables: { search, offset, limit },
})
```
TypeScript should not complain when I call `refetch` with missing variables

```javascript
refetch({ search: 'new search string' })
```

**Actual outcome:**

TypeScript gives the following error:

```
Type '{ search: string; }' is missing the following properties from
type 'GetQueryVariables': offset, limit
```

**The reason for the bug:**

Wrong TypeScript signature for `ObservableQuery.refetch()` public method in _src/core/ObservableQuery.ts_

```javascript
/**
 * @param variables: The new set of variables. If there are missing variables,
 * the previous values of those variables will be used.
 */
public refetch(variables?: TVariables): Promise<ApolloQueryResult<TData>> {
  ...
}
```

**Versions**

System:
- OS: Linux 4.19 Gentoo/Linux

Binaries:
- Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
- Yarn: 1.22.0 - /usr/bin/yarn
- npm: 6.13.6 - ~/tooling-ui/tooling-ui/node_modules/.bin/npm

Browsers:
- Firefox: 68.4.2esr

npmPackages:
- @apollo/client: 3.0.0-beta.41 => 3.0.0-beta.41 
- @apollo/link-context: 2.0.0-beta.3 => 2.0.0-beta.3 
- @apollo/link-schema: 2.0.0-beta.3 => 2.0.0-beta.3

**Comment by hwillson** [comment]
This should no longer be an issue in `@apollo/client@latest` - let us know otherwise, thanks!
