### ISSUE TITLE
Argument of type 'IdGetterObj' is not assignable to parameter of type 'StoreObject'.

### ISSUE THREAD

**Issue by ricokahler** [apollographql/apollo-client#6083]
Seems like there is type error in the apollo-client beta 41.

**Intended outcome:**

[From the docs](https://www.apollographql.com/docs/react/v3.0-beta/caching/cache-configuration/), there are examples that do this: 

![image](https://user-images.githubusercontent.com/10551026/77470331-e16acd00-6de6-11ea-9e3d-be0937a7edb5.png)

**Actual outcome:**

However when you try it out, it gives the following error message.

![image](https://user-images.githubusercontent.com/10551026/77470166-9c469b00-6de6-11ea-8790-89956465f49d.png)

```
Argument of type 'IdGetterObj' is not assignable to parameter of type 'StoreObject'.
  Index signature is missing in type 'IdGetterObj'.
```

**How to reproduce the issue:**

This is a type error so just copying this…

```ts
new InMemoryCache({
    dataIdFromObject: (object) => {
      return defaultDataIdFromObject(object);
    },
  })
```

… should repro it.

I'm not sure if this is an actual error or just a types issue but I thought I'd throw this up here.

Thanks for any support and I apologize if I missed anything!

**Versions**

```
System:
    OS: macOS 10.15.1
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 74.0
    Safari: 13.0.3
  npmPackages:
    @apollo/client: ^3.0.0-beta.41 => 3.0.0-beta.41
```

**Comment by travigd** [comment]
I'm also having this issue. :^)

`dataIdFromObject` is of type `IdGetter` which is declared as `(value: IdGetterObj) => string | undefined`. Seems like that should just be updated to be 
```ts
type IdGetter = (value: StoreObject) => string | undefined;
```

I'm not sure why `IdGetterObj` is a thing to begin with, truthfully. If it's for autocomplete, it could be fixed like
```ts
interface IdGetterObj extends StoreObject { /* ... */ }
```

Currently, `IdGetterObj` is declared as extending `Object`, so maybe that was the intention?
https://github.com/apollographql/apollo-client/blob/faf3ed7142b83c25c7604d6ab4f70752e5a073f6/src/cache/inmemory/types.ts#L10-L14

**Comment by benjamn** [comment]
I believe these typings were improved in #6080. Feel free to continue the discussion if you're still having this issue!
