### ISSUE TITLE
useMutation.mutate() returns Promise<FetchResult>, but useLazyQuery.query() returns void

### ISSUE THREAD

**Issue by eyalw** [apollographql/apollo-client#6085]
**Intended outcome:**
```javascript
render() {
   const [mutate, ...] = useMutation(...);
   const [query, ...] = useLazyQuery(...);
    ...
   onClick() { 
      mutate();  // returns Promise<FetchResult>  ✅
      query();     //  returns void  instead Promise<FetchResult> ❌ 😭
   }
}
```

**Actual outcome:**
query() returns void instead of a promise I can await on, and use its results in an async way.

**How to reproduce the issue:**
follow my snippet.

**Versions**
2.6 and v3.0

**Comment by hwillson** [comment]
This should no longer be an issue in `@apollo/client@latest` - let us know otherwise, thanks!
