### ISSUE TITLE
useLazyQuery returns old data

### ISSUE THREAD

**Issue by wisekaa03** [apollographql/apollo-client#6086]
Why that code is working improperly ? I change profileId and nothing happened, useLazyQuery is still returns the old data.

```
const [profile, setProfile] = useState<Profile>(null);
    const [getProfile, { loading, error, data }] = useLazyQuery<Data<'profile', Profile>, { id: string }>(PROFILE, {
      ssr: false,
    });

    useEffect(() => {
      getProfile({
        variables: { id: profileId },
      });
    }, [getProfile, profileId]);

    useEffect(() => {
      if (!loading && !error && data) {
        setProfile(data.profile);
      }
    }, [setProfile, data, loading, error]);
```
I am using:
```
    "@apollo/react-hooks": "^3.1.3",
    "apollo-client": "^2.6.8",
```

**Comment by manuFL** [comment]
Same issue here... useLazyQuery is not usable like this... any news?

**Comment by nrowley** [comment]
I have the same issue, it will return the result for the previous variables as if the request is lagging behind by one request.

**Comment by hwillson** [comment]
This should no longer be an issue in `@apollo/client@latest` - let us know otherwise, thanks!

**Comment by Zhdanown** [comment]
The same problem with version
`"@apollo/client": "3.5.5"`

Using a callback'ed function instead of the lazy does the trick for now

**Comment by danlin604** [comment]
Isn't this a major bug if we have to use a callback?

```JavaScript
  const [
    fn,
    {
      data, // A
      loading,
      error,
    },
  ] = useLazyQuery(QUERY, {
    onCompleted: (data: any) => {
      console.log('completed ->', data); // B
    },
  });
```

The return value is mismatched. onCompleted has the latest result and the data is the previous.

**Comment by Zhdanown** [comment]
@danlin604 I meant with the use of the client
```js
const client = useApolloClient();

const lazyQuery = useCallback(
  (id: number) =>
    client.query({
      query: QUERY,
      variables: { id },
    }),
  [client]
);

```

**Comment by sergtl** [comment]
Came across the same problem. I can get the up-to-date data/result using onCompleted callback, but lazyQuery will always return the previous result and not the new one.

**Comment by OneTuskedMario** [comment]
Same problem here, shouldn't this be an open issue?

**Comment by mkumaran1** [comment]
I faced the same problem... updating to latest version resolved the issue.
