### ISSUE TITLE
[3.0-beta41] adding onCompleted prop to useQuery breaks it if query uses @export directive

### ISSUE THREAD

**Issue by markwain** [apollographql/apollo-client#6092]
In client 3-beta41 adding `onCompleted` prop to `useQuery` breaks it, but only if query uses `@export `directive

Real Code example:
```
GET_POTENTIAL_SUBSCRIPTION = gql`
  query GET_POTENTIAL_SUBSCRIPTION(
    $currentPracticeId: Long!
    $offeringId: Long!
    $quantity: Int!
    $period: Int!
    $type: String!
  ) {
    currentPracticeId @client @export(as: "currentPracticeId")
    organization {
      offering {
        potentialSubscription(
          organizationId: $currentPracticeId
          entry: { offeringId: $offeringId, quantity: $quantity, type: $type, period: $period }
        ) {
          totalPaymentPrice
          pricePerUnit
          monthlyPaymentPrice
          pricePerUnitPerMarkupTier {
            volume
            pricePerUnit
          }
        }
      }
    }
  }
`

const { data, loading, error } = useQuery(GET_POTENTIAL_SUBSCRIPTION, {
    variables: {
      offeringId,
      quantity,
      period,
      type: paymentTypeSelected,
    },
    onCompleted: data => {
      onGetTotalPaymentPrice(get(data, 'organization.offering.potentialSubscription.totalPaymentPrice') / 100)
    },
  })

```

Removing @export directive and passing `currentPracticeId` as variable fixes it
Also, removing onCompleted prop fixes it.

**Comment by elvenking** [comment]
I have the same issue with 3.0-beta.44

**Comment by leapworkcto** [comment]
Same problem in 3.0.0-beta50, also without using onCompleted.

I can see the graphql call returns the right data in chrome devtools, but the data object returned from useQuery is undefined. Removing the use of `@export(as: "somevar")` solves the issue.

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
