### ISSUE TITLE
client.readQuery throws null field error in some circumstances

### ISSUE THREAD

**Issue by jamshally** [apollographql/apollo-client#6094]
**Intended outcome:**
Whenever client.readQuery had no results, null should be returned

**Actual outcome:**
In some circumstances client.readQuery returns null when no results are available, and in others a null field error is thrown

**How to reproduce the issue:**
When client.readQuery({ query: ALL_PEOPLE }) is run prior to client.query({ query: ALL_PEOPLE }) but AFTER any other client.query, a null field exception is thrown.

A recreation of this issue can be viewed in the [react-apollo-error-template here](https://github.com/ahrnee/react-apollo-error-template/tree/read-query-null-error-issue)

Steps to recreate :
1. Click button 4
2. Click button 1
3. Click button 4

More detailed notes and repo steps embedded in Issue notes embedded in the [react-apollo-error-template](https://github.com/ahrnee/react-apollo-error-template/tree/read-query-null-error-issue)

**Versions**
  System:
    OS: macOS 10.15.3
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Safari: 13.0.5
  npmPackages:
    @apollo/client: 3.0.0-beta.41 => 3.0.0-beta.41 

**Notes**
It is not clear if this is expected behavior or not. However, I assume not, as there seems to be no clear way to guard against missing fields on ROOT_QUERY when working with InMemory cache directly (using client.readQuery and client.cache.readQuery). In addition, the behavior seems inconsistent. In some circumstances an error is thrown and in others null is returned

**Comment by jsbrain** [comment]
I'm having the same issue. For me in one component it just works totally fine, in the other one (with copied code) it throws the respective error.

**Comment by jamshally** [comment]
This issue was resolved by release 3.3

> Prior to Apollo Client 3.3, readFragment would throw MissingFieldError exceptions to report missing fields, and return null only when reading a fragment from a nonexistent ID. Beginning with Apollo Client 3.3, readFragment always returns null to indicate insufficient data (missing ID or missing fields), instead of throwing a MissingFieldError.
