### ISSUE TITLE
Broken links on apollo-client-3-migration doc

### ISSUE THREAD

**Issue by chanonroy** [apollographql/apollo-client#6102]
**Intended outcome:** 

Clicking on internal doc links in the [apollo-client-3-migration.md](https://github.com/apollographql/apollo-client/blob/master/docs/source/migrating/apollo-client-3-migration.md#cache-improvements) redirects us to the correct markdown document.

Example: Clicking on `Configuring the cache` should redirect us [here](https://github.com/apollographql/apollo-client/blob/master/docs/source/caching/cache-configuration.md).

**Actual outcome:**

A 404 page due to a missing `.md` on the end of the url.

**How to reproduce the issue:**

Visit [apollo-client-3-migration.md](https://github.com/apollographql/apollo-client/blob/master/docs/source/migrating/apollo-client-3-migration.md#cache-improvements), and click on `Configuring the cache`.

Likely has to due with the way that we are using relative links on markdown 🤔

**Versions**

**Comment by chanonroy** [comment]
Ah, gotcha! 👍

**Comment by hwillson** [comment]
Answered in https://github.com/apollographql/apollo-client/issues/6102#issuecomment-610016212 - thanks!
