### ISSUE TITLE
default fetchPolicy not having effect in SSR

### ISSUE THREAD

**Issue by srolel** [apollographql/apollo-client#6103]
**Intended outcome:**

Setting a default fetchPolicy should determine default caching behavior.

**Actual outcome:**

Queries are cached when using `network-only` and `no-cache` in SSR.

**How to reproduce the issue:**

**Versions**

2.5.1, 2.6.8

**Comment by hwillson** [comment]
Can you please provide a small runnable reproduction that demonstrates the issue you're seeing? Thanks!

**Comment by srolel** [comment]
@hwillson I've hunted down the issue, it's react-apollo sending an options object with a `fetchPolicy` property that is `undefined`. This commit fixes that: https://github.com/srolel/react-apollo/commit/9c4805cb0675e7d6fcf18cdcc2297d7e50b5d758.

Since it is for an older version, not sure what the procedure would be to submit a PR but let me know what you think.

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
