### ISSUE TITLE
Query Stuck Loading When the Newly-Resolved Value Is Deeply Equivalent

### ISSUE THREAD

**Issue by huchenme** [apollographql/apollo-client#6106]
**Intended outcome:**

When the variables to a given `Query` change, the query should be re-run with the new variables, and when the response is received, it should trigger a re-render of the `Query` component with the new `data` (and not remain in a `loading` state).

**Actual outcome:**

When the variables of a given `Query` change, and the received response happens to be exactly the same (at least in terms of a deep equality check), the `Query` component is stuck in a `loading` state.

**How to reproduce the issue:**

The issue we're seeing seems to happen specifically when two network response values are deeply equivalent. Additionally, it seems to only be an issue when the query is simultaneously going from `skip={false}` to `skip={true}`.

Here is an example: https://codesandbox.io/s/client-3-hook-0r52i

This was also reported in `react-apollo`: https://github.com/apollographql/react-apollo/issues/3425

**Versions**

it is reproducible in this codesandbox: https://codesandbox.io/s/client-3-hook-0r52i

![image](https://user-images.githubusercontent.com/2078389/78351245-13471500-75d9-11ea-98ab-fd18237333d9.png)

**Comment by benjamn** [comment]
@huchenme I believe this is fixed in `@apollo/client@3.0.0-beta.43`. Thanks for the reproduction!
