### ISSUE TITLE
Try avoiding coupling the client with React in Apollo

### ISSUE THREAD

**Issue by tvvignesh** [apollographql/apollo-client#6110]
Hi. With version 3 of apollo-client it seems more friendly to the react community but that's creating some problems.

For instance, earlier things were smooth when you want to install apollo-link apollo-link-http and so on in the server side. But, now that it comes bundled with `@apollo/client`, I was trying to get it setup which gave me React specific errors on the server side like so:

![Screenshot from 2020-04-04 15-38-52](https://user-images.githubusercontent.com/1165845/78424322-675e0200-768a-11ea-9541-6d90a8fba3bc.png)

Even when I don't have anything related to React in my project, react definitions and functions are shipped with apollo-client.

It would be great to have an approach like what you took for apollo-server.

You have `apollo-server-core` package which has the core functionalities and then also for individual frameworks which extend it like `apollo-server-express` rather than putting express related functions also in core.

Wouldn't a similar approach be possible with `apollo-client` as well given the lot of frameworks which exists, it would be easier. Thanks.

**Comment by hwillson** [comment]
@tvvignesh there is a similar approach in place with Apollo Client 3. If you use `@apollo/client/core` instead of `@apollo/client`, you won't bring in any of the React bits.

**Comment by tvvignesh** [comment]
@hwillson My bad. Didn't see that. Thanks. Btw, wouldn't it make sense in the future to publish it as a separate package altogether considering it still gets installed in my node_modules. Just curious.
