### ISSUE TITLE
typePolicies merge errors get swallowed

### ISSUE THREAD

**Issue by Klemensas** [apollographql/apollo-client#6116]
**Intended outcome:**  `typePolicies` `merge` errors get propagated

**Actual outcome:** `typePolicies` `merge` errors get swallowed and there's no warning about them. They become apparent only when trying to use the fields

**How to reproduce the issue:** Add `typePolicies` with a `merge` function that's erroneous. Here's a sandbox https://codesandbox.io/s/gracious-elion-y2odj

**Versions**

`"@apollo/client": "3.0.0-beta.42"`

**Comment by hwillson** [comment]
@Klemensas this has been fixed in the latest version of the beta (`3.0.0-beta.50`). Thanks!
