### ISSUE TITLE
InMemoryCache  not restoring from initial state in apollo-client 3.0

### ISSUE THREAD

**Issue by aiyer07** [apollographql/apollo-client#6124]
**UPDATE:** 
1. The issue seems to be related to customer identifiers using typePolicies
2. Solved, the keyfields of the typePolicies required me to directly access the primary key from the store object (more in comments). Not exactly the behavior I expected based on the docs though

Been really excited about the new developments in apollo client 3.0 and have begun setting up my next app to use it (especially looking forward to those reactive local vars!) But I've hit a snag early on with cache rehydration

**Intended outcome:**

I am trying to rehydrate the cache on the client by calling `InMemoryCache.restore(initialState || {}) ` where initialState is passed from withApollo (next-with-apollo) HOC in the client. 

**Actual outcome:**
While the initialState is correctly generated and passed to the client, the subsequent `InMemoryCache.restore(initialState)` does not apply it to the cache. Here's the code for the HoC

``` javascript
import withApollo, { InitApolloOptions } from 'next-with-apollo';
import { onError } from '@apollo/link-error';
import merge from 'lodash/merge';
import {
  ApolloClient,
  ApolloLink,
  HttpLink,
  InMemoryCache,
  gql,
  NormalizedCacheObject,
} from '@apollo/client';

// JUST FOR TESTING
const USER_FRAG = gql`
  fragment user on user {
    userId
    roleName
  }`;

export default withApollo(({initialState}: InitApolloOptions<NormalizedCacheObject>): any => {

  // TEST TO SEE INITIAL STATE ON CLIENT & SERVER BEFORE RESTORE
  console.log("withApollo -> initialState", initialState)
  // SERVERSIDE: ✅RETURNS NULL
  // CLIENTSIDE: ✅RETURNS USER OBJECT AND ROOT QUERY
  const cache = new InMemoryCache({
    typePolicies: {
      user: {
        keyFields: ['userId'],
      },
    },
  }).restore(initialState || {});
   // THIS IS WHERE I ATTEMPT TO RESTORE THE CACHE BUT IT DOESN'T SEEM TO WORK^ 👎🏾

  // TEST TO SEE THAT CACHE CONTAINS DATA
  let data = cache.readFragment({
    id: '286',
    fragment: USER_FRAG,
  })

  // TEST TO SEE INITIAL STATE ON CLIENT & SERVER AFTER RESTORE
  console.log("withApollo -> cache", data)
  //  ✅ SERVERSIDE: RETURNS null
 // ❌ CLIENTSIDE: RETURNS null <--- this is what I don't understand

  const isBrowser = typeof window !== 'undefined';

  // set api to self on server and loadbalancer if on browser
  const apiUri = isBrowser ? '/v1/graphql' : 'http://localhost/v1/graphql';

  // create http link
  const link = ApolloLink.from([
    onError(e => {
      console.log('graphQLErrors', e);
    }),
    new HttpLink({
      uri: apiUri,
    }),
  ]);

  const client = new ApolloClient({
    ssrMode: true,
    link: link,
    cache
  });

  return client;
});
```
And in my wrapped App Component, I am attempting to initialize the cache on the server

``` javascript
import * as React from 'react';
import App from 'next/app';
import Head from 'next/head';
import withApollo from '../apollo/withApollo';
import { ApolloProvider } from '@apollo/client';
import { theme } from '@everydae/components-lib/Theme';
import { GlobalStyle } from '@everydae/components-lib/';
import { NavBar } from '@everydae/components-lib';
import { ThemeProvider } from 'emotion-theming';
import { gql } from '@apollo/client';

const INIT_USER = gql`
  query initUser($userId: Int!) {
  user: user_by_pk(userId: $userId) {
    userId
    roleName
  }
}`

class TestApp extends App {
  static async getInitialProps({  Component, ctx }: any) {
    const { apolloClient } = ctx
    let pageProps = {};
   // THIS IS WHERE THE INITIAL STATE GETS LOADED 👍🏾
  const data = await apolloClient.query({
      query: INIT_USER,
      variables: { userId: 286 }
    });
    console.log("getInitialProps -> cache", 
      cache.readFragment({
         id: '286',
         fragment: USER_FRAG,
       }))
    // SERVER SIDE ✅ RETURNS USER OBJECT + Root Query
    // CLIENT SIDE  ❌RETURNS null
    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx);
    }
    return { pageProps };
  }

  componentDidMount() {}

  render() {
    const { Component, pageProps, apollo } = this.props as any;
    return (
      <ApolloProvider client={apollo}>
        <ThemeProvider theme={theme}>
          <Head>
            <title>Test</title>
            <meta
              name="description"
              content="Testing rehydration."
            />
          </Head>
          <GlobalStyle />
          <NavBar/>
          {/* <Component {...pageProps} /> */}
        </ThemeProvider>
      </ApolloProvider>
    );
  }
}

export default withApollo(TestApp);
```

Here are some screenshots of those console logs showing what the initialState & results of the cache reads look like (chrome console is client, vscode console is server)

![image](https://user-images.githubusercontent.com/3598276/78746633-3f85cd00-791c-11ea-9374-446c55d9a00b.png)
client ^

![image](https://user-images.githubusercontent.com/3598276/78746669-53c9ca00-791c-11ea-9e6d-4044dba2fa4f.png)
server ^

**How to reproduce the issue:**
I am using "apollo/client": "3.0.0-beta.41" and  "next-with-apollo": "^4.3.0"  I've found that no matter what i enter, even manually into the `restore()`function, it is not represented in the cache by logs or in the Apollo Dev tools cache panel.

**Versions**
 System:
    OS: macOS 10.15.1
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 72.0.2
    Safari: 13.0.3

I am not sure if this is an incompatability issue with next-with-apollo and apollo client 3.0 or if my implementation is incorrect. I noticed the documents mentioned using a `window.__APOLLO_STATE__`  which I don't fully understand where one would do that or even why that would work over my approach above, given that the initialState variable contains all the correct data.

**Comment by aiyer07** [comment]
Upon further investigation, I'm finding the issue to be specifically with the custom id on user using `typePolicies` instead of the now deprecated `dataIdFromObject` When I replace the inMemory cache code above with the following, everything seems to work as expected:

``` javascript
  const cache = new InMemoryCache({
     dataIdFromObject: object => {
       switch (object.__typename) {
         case 'user':
           return object['userId'];
       }
     }
  }).restore(initialState || {});
``` 

Is there something wrong with my implementation of the user typepolicy?

**Comment by aiyer07** [comment]
Solved since my last comment. The following code worked: 

``` javascript
const cache = new InMemoryCache({
    typePolicies: {
      user: {
        keyFields: (obj: any) => {
        console.log("obj", obj)
          return obj['userId']
        },
      },
    },
  }).restore(initialState || {});
```

The documentation seems to suggest that simply referring to the column likeso: `['userId']` would work but I didn't find that to be the case

**Comment by daryn-k** [comment]
What was the problem? I have the same issue after migrating to version 3. InMemoryCache doesn't restore from the preloaded state.

**Comment by daryn-k** [comment]
Well, `inMemoryCache()` from `apollo-client` and `@apollo/client` generates JSON in **different** formats. Did you have this problem? And how did you solve it?
