### ISSUE TITLE
The clinet.writeQuery not update all relative queries and not re-render components that use relative queries when changed a nested field

### ISSUE THREAD

**Issue by masihjahangiri** [apollographql/apollo-client#6130]
**Intended outcome:**
I want to use apollo state managemant instead of redux. I write a simple schema for my local state to handle user loggedIn. Below is `LOCAL_SCHEMA`:
```
type QueryLocalStateUser {
  isLoggedIn: Boolean!
  usernames: [String]!
}

type QueryLocalState {
  user: QueryLocalStateUser!
}

extend type Query {
  localState: QueryLocalState!
}
```
And I initialize cache:
```typescript
const client = new ApolloClient<NormalizedCacheObject>({
  cache: new InMemoryCache(),
  connectToDevTools: true,
  link: new HttpLink({
    uri: process.env.GRAPHQL_API,
  }),
  headers: {
    authorization: localStorage.getItem('token') || '',
  },
  queryDeduplication: true,
  typeDefs: LOCAL_SCHEMA,
});

const LocalStateDocument = gql`
  query LocalState {
    localState @client {
      user {
        isLoggedIn
        usernames
      }
    }
  }
`;
const initLocalState = (): Promise<void> => {
  return new Promise(resolve => {
    client.cache.writeQuery<LocalStateQuery>({
      query: LocalStateDocument,
      data: {
        localState: {
          user: {
            isLoggedIn: !!localStorage.getItem('token'),
            usernames: JSON.parse(localStorage.getItem('uname') || '[]'),
          },
        },
      },
    });
    resolve();
  });
};
```
And in my component want to update `localState.user.isLoggedIn` so I query isLoggedIn:
```
query LocalStateIsLoggedIn {
  localState @client {
    user {
      isLoggedIn
    }
  }
}
```
And and after login mutation I call clinet.writeQuery to change state:
```typescript
const LocalStateIsLoggedInDocument = gql`
  query LocalStateIsLoggedIn {
    localState @client {
      user {
        isLoggedIn
      }
    }
  }
`;
client.writeQuery<LocalStateIsLoggedInQuery>({
  query: LocalStateIsLoggedInDocument,
    data: {
      localState: {
        user: {
          isLoggedIn: true,
        },
      },
  },
});

```
**Actual outcome:**
I expect apollo cache all queries that contains `localState.user.isLoggedIn` and re-render all UI component that use this state.
But apollo client not update all queries! apollo cache update only `LocalStateIsLoggedInDocument` query!

I want apollo cache re-render all queries that use `localState.user.isLoggedIn`. I don't know how to achieve this goal apollo cache system? which is best solution?

**Versions**
- System:
    - OS: Windows 10 10.0.18363
  - Binaries:
    - Node: 13.10.1
    - npm: 6.13.7
- packages:
  - "react": "^16.13.1"
  - "react-dom": "^16.13.1"
  - "@apollo/client": "^3.0.0-beta.41"

**Comment by freshollie** [comment]
You should provide `__typename` fields to all of your write queries, otherwise Apollo can't know how to merge your cache. I use [graphql-code-generator](https://github.com/dotansimha/graphql-code-generator) to enforce this in made code bases.

```typescript
const initLocalState = (): Promise<void> => {
  return new Promise(resolve => {
    client.cache.writeQuery<LocalStateQuery>({
      query: LocalStateDocument,
      data: {
        __typename: "Query",
        localState: {
          __typename: "QueryLocalState", 
          user: {
            __typename: "QueryLocalStateUser",
            isLoggedIn: !!localStorage.getItem('token'),
            usernames: JSON.parse(localStorage.getItem('uname') || '[]'),
          },
        },
      },
    });
    resolve();
  });
};
```

```typescript
client.writeQuery<LocalStateIsLoggedInQuery>({
  query: LocalStateIsLoggedInDocument,
    data: {
      localState: {
        __typename: "QueryLocalState",
        user: {
          __typename: "QueryLocalStateUser",
          isLoggedIn: true,
        },
      },
  },
});
```

Can you try this? I know it's frustrating. Otherwise, I would switch to [`@apollo/client`](https://www.npmjs.com/package/@apollo/client) which allows you to make a local variable, which will update all queries which use it when it's changed. You can see an example of that here: https://github.com/freshollie/fresh-configurator/blob/c3e1846f71edf31a694b5a9a4a02b47a3157f6c5/packages/configurator/src/gql/client.ts#L36 (I can't find any docs on it yet, it's still in beta)

**Comment by masihjahangiri** [comment]
@freshollie  Thanks for your answer.I test @freshollie code but apollo cache not update queries and not re-render UIs. 
I solved it by adding a `id` to any nested object (always id is "0"). And according to @freshollie answer I add `__typename` [also `id`] when I want to change any cache.
Therefor change local schema to:
(I use [graphql-code-generator](https://github.com/dotansimha/graphql-code-generator) like @freshollie.)
```
type QueryLocalStateUser {
  id: ID!
  isLoggedIn: Boolean!
  hostelUsernames: [String]!
}

type QueryLocalState {
  id: ID!
  user: QueryLocalStateUser!
}

extend type Query {
  localState: QueryLocalState!
}
```
And in initLocalState added `id`, `__typename`:
```typescript
const id = '0';
const initLocalState = (): Promise<void> => {
  return new Promise(resolve => {
    client.cache.writeQuery<LocalStateQuery>({
      query: LocalStateDocument,
      data: {
        __typename: 'Query',
        localState: {
          __typename: 'QueryLocalState',
          id,
          user: {
            __typename: 'QueryLocalStateUser',
            id,
            isLoggedIn: !!localStorage.getItem('token'),
            hostelUsernames: JSON.parse(localStorage.getItem('uname') || '[]'),
          },
        },
      },
    });
    resolve();
  });
};
```
And also in client.writeQuery I added `id`, `__typename`:
```typescript
client.writeQuery<LocalStateIsLoggedInQuery>({
  query: LocalStateIsLoggedInDocument,
  data: {
    localState: {
      __typename: 'QueryLocalState',
      id: '0',
      user: {
        __typename: 'QueryLocalStateUser',
        id: '0',
        isLoggedIn: true,
      },
    },
  },
});
```
