### ISSUE TITLE
ApolloClient3: TypePolicy merge readField function always requires a foreignObjOrRef

### ISSUE THREAD

**Issue by Banou26** [apollographql/apollo-client#6142]
*https://spectrum.chat/apollo/apollo-client/apolloclient3-typepolicies-contexts~0ed2649c-ad4c-4e8a-9a53-9ae52f865e7b*

**Intended outcome:**
Be able to use `readField` in `merge` functions just like when using it in a `read` function

**Actual outcome:**
When trying to use it without `foreignObjOrRef` parameter, the function will always throw
```diff
- Network error: Must provide an object or Reference when calling Policies#readField
```

**How to reproduce the issue:**
Just use the `readField` function in a `merge` TypePolicy field

**Versions**
`^3.0.0-beta.43`

**Comment by ashubham** [comment]
This happens to me too:
`Uncaught Invariant Violation: Must provide an object or Reference when calling Policies#readField`

FWIW, inside the merge function you have access to the `existing` and `field` which could be passed as the second args

**Comment by ashubham** [comment]
@Banou26 You may want to look at this comment in the code though:

https://github.com/apollographql/apollo-client/blob/master/src/cache/inmemory/policies.ts#L549

**Comment by Banou26** [comment]
If you took a look a look at the reference i gave in my post: *https://spectrum.chat/apollo/apollo-client/apolloclient3-typepolicies-contexts~0ed2649c-ad4c-4e8a-9a53-9ae52f865e7b*.

You'd see that there is a design problem with this, because they say that `readField` is useful for merge functions, but the thing is **you cannot use readField at all** because you cannot query the object of the merge since the only thing you can rely on are variables, but variable names aren't unique to every query and can have collision.

e.g
```ts
cache.readQuery({
  query: gql`
  {
    account(id: "foo") {
      user {
        settings {
          public
        }
      }
    }
  }
  `
})
cache.readQuery({
  query: gql`
  {
    user(id: "bar") {
      settings {
        public
      }
    }
  }
  `
})
```

In this case, `id` is used both by the `user` query and the `account` query, so you cannot use readField to fetch any related parent.

**Comment by benjamn** [comment]
@Banou26 You need to be using the `options.args` object rather than the `options.variables` object in your `merge` functions. Arguments are specific to the field, whereas variables are global to the query. Once you get comfortable with this distinction, I think/hope your issues with variable name uniqueness will resolve themselves.

**Comment by bennypowers** [comment]
What's the blessed path for persisting fields in some storage scheme, then?

consider

```ts
export const Analysis: TypePolicy = {
  fields: {
    sectionsOpen: {
      merge(prev: SectionsOpen, next: SectionsOpen, { readField }: FieldFunctionOptions): SectionsOpen {
        const id = readField('id') // womp womp, `undefined`
        localStorage.setItem(`sections-open-${id}`, JSON.stringify(next ?? null));
        return next;
      },
      read(prev: SectionsOpen, { readField }: FieldFunctionOptions): SectionsOpen {
        const id = readField('id'); // parent id! yay!
        return (
          prev ??
          JSON.parse(localStorage.getItem(`sections-open-${id}`)) ??
          { /* ...some defaults */ }
        );
      },
    },
  },
};
```
