### ISSUE TITLE
Calling map of QueryObservable throws an error

### ISSUE THREAD

**Issue by geekox86** [apollographql/apollo-client#6144]
**Intended outcome:**
I am trying to map the result of QueryObservable.

**Actual outcome:**
TypeError: Cannot read property 'generateQueryId' of undefined

**How to reproduce the issue:**
```ts
apolloClient
  .watchQuery({ query })
  .map(result => result.data)
```

**Versions**
3.0.0-beta.43

**Comment by jeddeloh** [comment]
This is still an issue in 3.0.1

**Comment by elm-suf** [comment]
i'm having the same problem using "@apollo/client": "^3.0.2"

**Comment by dminkovsky** [comment]
Looking at the code, you need put the queryManager property from the observable you're mapping onto the callback function you pass to map. Kind of weird! Maybe there is a better way to do this?

**Comment by lennyburdette** [comment]
Workaround:
```ts
import Observable from 'zen-observable';

return Observable.from(apolloClient.watchQuery({ query }))
  .map(result => result.data);
```

**Comment by daniel-pelando** [comment]
i'm having the same problem using "@apollo/client": "^3.1.3"
