### ISSUE TITLE
James version causes renovate bot issue

### ISSUE THREAD

**Issue by ricokahler** [apollographql/apollo-client#6146]
So this one is kind of interesting…

For some quick context, we installed renovate bot in our repo which contains the apollo client beta and we saw this upgrade from it:

![image](https://user-images.githubusercontent.com/10551026/79150448-cc0a1280-7d96-11ea-8c8f-8155beedacec.png)

It wants to upgrade to the james version!

**Intended outcome:**

It should match the latest tag on npm which is `3.0.0-beta.43` at the time of this writing.

**Actual outcome:**

![image](https://user-images.githubusercontent.com/10551026/79150748-46d32d80-7d97-11ea-9948-237d945b48ac.png)

My guess is the renovate uses the semver package and according to that, the `james` version is the latest!

---

I don't really know how to go about this. I see that this repo also uses renovate bot so maybe you know a solution. Maybe a possible approach is to unpublish or deprecate that version?? 😅

Thanks a bunch! ❤️

**Comment by CarsonF** [comment]
I can second this with Yarn v2

**Comment by dc-pm** [comment]
We're also seeing this problem - is super annoying as we can't close the issue (renovate reopens it immediatly as immoral)

Any ideas on a fix? My only idea is to disable renovate for apollo until v3 ships?

**Comment by hwillson** [comment]
This is definitely annoying 🙁. The good news is we're publishing the AC3 RC sometime between tomorrow and Sunday, so at least switching to the RC will get past this. Instead of figuring out a way around this (since we can't unpublish the infamous `James` package), and since the RC is imminent, we're probably going to leave this as is.

**Comment by hwillson** [comment]
This is definitely becoming more annoying: https://github.com/apollographql/apollo-client/pull/6350#issuecomment-635871472. I've added a deprecation notice so hopefully that helps, until we're past this.

**Comment by hwillson** [comment]
This issue was resolved - thanks!
