### ISSUE TITLE
Stale property, docs missing

### ISSUE THREAD

**Issue by frederikhors** [apollographql/apollo-client#6151]
I read all this page: https://www.apollographql.com/docs/react/api/apollo-client/

but I can't find any docs about `stale` property in my query result:

`{data: {…}, loading: true, networkStatus: 1, stale: false}`

What does it mean?

And why it is `false` now if my query is called with `fetchPolicy: 'cache-and-network'` and that debug text is when it first rendered from the cache?

**Comment by hwillson** [comment]
The `stale` property has been removed. Thanks!
