### ISSUE TITLE
Network request always fails on production build

### ISSUE THREAD

**Issue by wolftic** [apollographql/apollo-client#6157]
**Intended outcome:**
Doing a query shouldn't result in a network error, because when developing same URL works.

**Actual outcome:**
Always throws a `[Network error]: TypeError: Network request failed` whenever I try to do a mutation or query.
When JSON.stringify results into `{"line":109,"column":7285,"sourceURL":"index.android.bundle"}`

**How to reproduce the issue:**
`
new HttpLink({
    uri: 'http://api.####.com:3000/graphql',
    credentials: 'same-origin',
});
`

**Versions**
  System:
    OS: Windows 10 10.0.18362
  Binaries:
    Node: 12.10.0 - C:\Program Files\nodejs\node.EXE      
    npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    apollo-boost: ^0.4.7 => 0.4.7
    apollo-cache-inmemory: ^1.6.5 => 1.6.5
    apollo-client: ^2.6.8 => 2.6.8
    apollo-link: ^1.2.14 => 1.2.14
    apollo-link-error: ^1.1.13 => 1.1.13
    apollo-link-http: ^1.5.17 => 1.5.17

**Comment by hwillson** [comment]
There is much here for us to go on. Can you provide a small runnable reproduction that demonstrates this?

**Comment by marf** [comment]
Same issue here. We cannot create a reproduction demo since it happens randomly to lots of our productions users but we can confirm there is this issue with lots of our users.
