### ISSUE TITLE
useQuery and useLazyQuery memory leaks when component unmout 

### ISSUE THREAD

**Issue by luckskywalker** [apollographql/apollo-client#6158]
Hi,

Since I upgraded apollo-hooks, when I use the hooks "useQuery" and "useLazyQuery", an error is fired. It happens when the same gql has already launched in an other functionnal component.

 
**Actual outcome:**
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in Header (at Templates/index.js:13)
    in section (created by Context.Consumer)
    in BasicLayout (created by Context.Consumer)
    in Layout (at Templates/index.js:12)
    in section (created by Context.Consumer)
    in BasicLayout (created by Context.Consumer)
    in Layout (at Templates/index.js:10)
    in PrimaryLayout (at Login.js:8)
    in Landing (created by Context.Consumer) index.js:1
    e index.js:1
    printWarning React
    error 0.chunk.js:240197
    warnAboutUpdateOnUnmountedFiberInDEV 0.chunk.js:263147
    scheduleUpdateOnFiber 0.chunk.js:261159
    dispatchAction 0.chunk.js:255769
    onNewData 0.chunk.js:72404
    next 0.chunk.js:72224
    notifySubscription 0.chunk.js:280693
    onNotify 0.chunk.js:280737
    next 0.chunk.js:280789
    iterateObserversSafely 0.chunk.js:122046
    iterateObserversSafely 0.chunk.js:122045
    next 0.chunk.js:122012
    invoke 0.chunk.js:123038
    queryListenerForObserver 0.chunk.js:123124
    broadcastQueries 0.chunk.js:123492
    broadcastQueries 0.chunk.js:123490
    broadcastQueries 0.chunk.js:123488
    subscription 0.chunk.js:123615
    next 0.chunk.js:280874
    notifySubscription 0.chunk.js:280693
    onNotify 0.chunk.js:280737
    next 0.chunk.js:280789
    next 0.chunk.js:122585
    next 0.chunk.js:122584
    notifySubscription 0.chunk.js:280693
    onNotify 0.chunk.js:280737
    next 0.chunk.js:280789
    next 0.chunk.js:124264
    notifySubscription 0.chunk.js:280693
    onNotify 0.chunk.js:280737
    next 0.chunk.js:280789
    notifySubscription 0.chunk.js:280693
    onNotify 0.chunk.js:280737
    next 0.chunk.js:280789
    createHttpLink 0.chunk.js:124615
    (Asynchrone : promise callback)
    createHttpLink 0.chunk.js:124614
    Subscription 0.chunk.js:280753
    subscribe 0.chunk.js:280831
    requestHandler 0.chunk.js:119930
    (Asynchrone : promise callback)
    requestHandler 0.chunk.js:119929
    Subscription 0.chunk.js:280753
    subscribe 0.chunk.js:280831
    onError 0.chunk.js:124244
    Subscription 0.chunk.js:280753
    subscribe 0.chunk.js:280831
    multiplex 0.chunk.js:122582
    Subscription 0.chunk.js:280753
    subscribe 0.chunk.js:280831
    getObservableFromLink 0.chunk.js:123543
    fetchRequest 0.chunk.js:123590
    fetchRequest 0.chunk.js:123589
    fetchQuery 0.chunk.js:122949
    step 0.chunk.js:279134
    verb 0.chunk.js:279065
    __awaiter 0.chunk.js:279038
    __awaiter 0.chunk.js:279017
    fetchQuery 0.chunk.js:122887
    observeQuery 0.chunk.js:123346
    setUpQuery 0.chunk.js:121990
    onSubscribe 0.chunk.js:121954
    _this 0.chunk.js:121620
    Subscription 0.chunk.js:280753
    subscribe 0.chunk.js:280831
    startQuerySubscription 0.chunk.js:72213
    getExecuteResult 0.chunk.js:72020
    execute 0.chunk.js:72067
    result 0.chunk.js:72426
    useDeepMemo 0.chunk.js:72373
    useBaseQuery 0.chunk.js:72425
    useQuery 0.chunk.js:72447
    useQuery main.chunk.js:266
    RouterPages main.chunk.js:10148
    renderWithHooks 0.chunk.js:254932
    mountIndeterminateComponent 0.chunk.js:257544
    beginWork 0.chunk.js:258622
    beginWork$1 0.chunk.js:263164
    performUnitOfWork 0.chunk.js:262155
    workLoopSync 0.chunk.js:262128
    performSyncWorkOnRoot 0.chunk.js:261746
    scheduleUpdateOnFiber 0.chunk.js:261178
    updateContainer 0.chunk.js:264327
    legacyRenderSubtreeIntoContainer 0.chunk.js:264710
    unbatchedUpdates 0.chunk.js:261896
    legacyRenderSubtreeIntoContainer 0.chunk.js:264709
    render 0.chunk.js:264792
    js main.chunk.js:11065
    __webpack_require__ bundle.js:785
    fn bundle.js:151
    1 main.chunk.js:11205
    __webpack_require__ bundle.js:785
    checkDeferredModules bundle.js:46
    webpackJsonpCallback bundle.js:33
    <anonyme> main.chunk.js:1

**Versions**
  System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
  Binaries:
    Node: 8.10.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.2 - /usr/local/bin/npm
  npmPackages:
    apollo-boost: ^0.4.7 => 0.4.7 
    react-apollo: ^3.1.5 => 3.1.5

**Comment by hwillson** [comment]
This should be fixed in the latest `@apollo/client@beta`. Thanks!

**Comment by teenkevo** [comment]
> Hi,
> 
> Since I upgraded apollo-hooks, when I use the hooks "useQuery" and "useLazyQuery", an error is fired. It happens when the same gql has already launched in an other functionnal component.
> 
> **Actual outcome:**
> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
> in Header (at Templates/index.js:13)
> in section (created by Context.Consumer)
> in BasicLayout (created by Context.Consumer)
> in Layout (at Templates/index.js:12)
> in section (created by Context.Consumer)
> in BasicLayout (created by Context.Consumer)
> in Layout (at Templates/index.js:10)
> in PrimaryLayout (at Login.js:8)
> in Landing (created by Context.Consumer) index.js:1
> e index.js:1
> printWarning React
> error 0.chunk.js:240197
> warnAboutUpdateOnUnmountedFiberInDEV 0.chunk.js:263147
> scheduleUpdateOnFiber 0.chunk.js:261159
> dispatchAction 0.chunk.js:255769
> onNewData 0.chunk.js:72404
> next 0.chunk.js:72224
> notifySubscription 0.chunk.js:280693
> onNotify 0.chunk.js:280737
> next 0.chunk.js:280789
> iterateObserversSafely 0.chunk.js:122046
> iterateObserversSafely 0.chunk.js:122045
> next 0.chunk.js:122012
> invoke 0.chunk.js:123038
> queryListenerForObserver 0.chunk.js:123124
> broadcastQueries 0.chunk.js:123492
> broadcastQueries 0.chunk.js:123490
> broadcastQueries 0.chunk.js:123488
> subscription 0.chunk.js:123615
> next 0.chunk.js:280874
> notifySubscription 0.chunk.js:280693
> onNotify 0.chunk.js:280737
> next 0.chunk.js:280789
> next 0.chunk.js:122585
> next 0.chunk.js:122584
> notifySubscription 0.chunk.js:280693
> onNotify 0.chunk.js:280737
> next 0.chunk.js:280789
> next 0.chunk.js:124264
> notifySubscription 0.chunk.js:280693
> onNotify 0.chunk.js:280737
> next 0.chunk.js:280789
> notifySubscription 0.chunk.js:280693
> onNotify 0.chunk.js:280737
> next 0.chunk.js:280789
> createHttpLink 0.chunk.js:124615
> (Asynchrone : promise callback)
> createHttpLink 0.chunk.js:124614
> Subscription 0.chunk.js:280753
> subscribe 0.chunk.js:280831
> requestHandler 0.chunk.js:119930
> (Asynchrone : promise callback)
> requestHandler 0.chunk.js:119929
> Subscription 0.chunk.js:280753
> subscribe 0.chunk.js:280831
> onError 0.chunk.js:124244
> Subscription 0.chunk.js:280753
> subscribe 0.chunk.js:280831
> multiplex 0.chunk.js:122582
> Subscription 0.chunk.js:280753
> subscribe 0.chunk.js:280831
> getObservableFromLink 0.chunk.js:123543
> fetchRequest 0.chunk.js:123590
> fetchRequest 0.chunk.js:123589
> fetchQuery 0.chunk.js:122949
> step 0.chunk.js:279134
> verb 0.chunk.js:279065
> __awaiter 0.chunk.js:279038
> __awaiter 0.chunk.js:279017
> fetchQuery 0.chunk.js:122887
> observeQuery 0.chunk.js:123346
> setUpQuery 0.chunk.js:121990
> onSubscribe 0.chunk.js:121954
> _this 0.chunk.js:121620
> Subscription 0.chunk.js:280753
> subscribe 0.chunk.js:280831
> startQuerySubscription 0.chunk.js:72213
> getExecuteResult 0.chunk.js:72020
> execute 0.chunk.js:72067
> result 0.chunk.js:72426
> useDeepMemo 0.chunk.js:72373
> useBaseQuery 0.chunk.js:72425
> useQuery 0.chunk.js:72447
> useQuery main.chunk.js:266
> RouterPages main.chunk.js:10148
> renderWithHooks 0.chunk.js:254932
> mountIndeterminateComponent 0.chunk.js:257544
> beginWork 0.chunk.js:258622
> beginWork$1 0.chunk.js:263164
> performUnitOfWork 0.chunk.js:262155
> workLoopSync 0.chunk.js:262128
> performSyncWorkOnRoot 0.chunk.js:261746
> scheduleUpdateOnFiber 0.chunk.js:261178
> updateContainer 0.chunk.js:264327
> legacyRenderSubtreeIntoContainer 0.chunk.js:264710
> unbatchedUpdates 0.chunk.js:261896
> legacyRenderSubtreeIntoContainer 0.chunk.js:264709
> render 0.chunk.js:264792
> js main.chunk.js:11065
> **webpack_require** bundle.js:785
> fn bundle.js:151
> 1 main.chunk.js:11205
> **webpack_require** bundle.js:785
> checkDeferredModules bundle.js:46
> webpackJsonpCallback bundle.js:33
> main.chunk.js:1
> 
> **Versions**
> System:
> OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
> Binaries:
> Node: 8.10.0 - /usr/bin/node
> Yarn: 1.22.4 - /usr/local/bin/yarn
> npm: 6.14.2 - /usr/local/bin/npm
> npmPackages:
> apollo-boost: ^0.4.7 => 0.4.7
> react-apollo: ^3.1.5 => 3.1.5

Hi, how did you solve this?
