### ISSUE TITLE
Refetching queries based on variables

### ISSUE THREAD

**Issue by Vincz** [apollographql/apollo-client#6159]
Hi ! I have a use case where people can retrieve a list elements with an optional filter "favorites only" (to get only items with the state "favorite"), and of course they can add/remove item to their favorites.
When someone toggle a favorite state (with a mutation), I'd like to be able to refresh the query listing the elements, only if the "favorite" filter has been used. 
I can't find a way of doing this, neither with the upcoming v3. We should be able to add tags or something to queries (or be able to specify the cache key for the query ourselves) to be able to clear the cache later.
Is there anything planned about this ? 
Thanks!

**Comment by freshollie** [comment]
Possible workarounds for now, depend on how expensive your data fetches are:

```typescript
client.cache.evict('mykey')
client.reFetchObservableQueries();
```

Though I really want this feature too, and I think this workaround is a waste.
