### ISSUE TITLE
`useLazyQuery` not calling `onError` for network errors

### ISSUE THREAD

**Issue by aryzing** [apollographql/apollo-client#6165]
**Intended outcome:**

Errors should be caught and handled by `useLazyQuery`'s `onError` function,

```js
const [query, { loading, error, data }] = useLazyQuery(QUERY, {
  onError(error) {
    console.error(error)
  },
  pollInterval: 5000,
});
```

**Actual outcome:**

The `onError` function is not called. With the above `pollInterval` setting the behaviour I'm seeing is:

* If errors are reported after successful queries (ie, network disconnects) the `onError` function will not be called. However, the console will show:

![image](https://user-images.githubusercontent.com/4924405/79671199-4ee50000-81d1-11ea-835e-c3654b97a524.png)

* If when the query is executed for the very first time it fails, the `onError` function is called once. All subsequent calls produced by the poll interval will report the errors above, but will not call the `onError` function.

**How to reproduce the issue:**

With `useLazyQuery`, set up the scenario described in "Actual outcome" section above.

**Versions**

```
  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
  Binaries:
    Node: 13.12.0 - ~/.nvm/versions/node/v13.12.0/bin/node
    Yarn: 1.22.4 - ~/workspace/project/node_modules/.bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v13.12.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.92
    Firefox: 75.0
  npmPackages:
    @apollo/react-components: ^3.1.5 => 3.1.5 
    @apollo/react-hoc: ^3.1.5 => 3.1.5 
    @apollo/react-hooks: ^3.1.5 => 3.1.5 
    @apollo/react-testing: ^3.1.4 => 3.1.4 
    apollo: ^2.27.0 => 2.27.0 
    apollo-boost: ^0.4.7 => 0.4.7 
    apollo-cache: ^1.3.4 => 1.3.4 
    apollo-cache-inmemory: ^1.6.5 => 1.6.5 
    apollo-client: ^2.6.8 => 2.6.8 
    apollo-link: ^1.2.14 => 1.2.14 
    apollo-utilities: ^1.3.3 => 1.3.3 
```

**Comment by KamauIan** [comment]
Hey, you could try `errorPolicy: 'all'`

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!

**Comment by gursahibsahni** [comment]
@aryzing not sure if you were able to solve the problem. I am facing the same problem. Why is the issue closed?

**Comment by gursahibsahni** [comment]
For me `notifyOnNetworkStatusChange: true` worked pretty well.

`    getServicingBankAccountsQuery,
    {
      fetchPolicy: "no-cache",
      onCompleted: (data) => {
        dispatch(fetchServicingBankAccounts(data));
        goTo(page.index + 1);
      },
      notifyOnNetworkStatusChange: true,
      onError: (error) => {
        setServicingBankAccountApiError(error);
      },
    }
  );`
