### ISSUE TITLE
APC 2: Local state query with argument not updating

### ISSUE THREAD

**Issue by wittydeveloper** [apollographql/apollo-client#6169]
Hi team 👋 

I am trying to use Apollo local state for a flash notice solution, the design is the following:

- `flashNotices` filed at the root query, initialised at application load
- a `flashNoticesByKey(key: $key)` query, built upon the `flashNotices @client` with filtering in the resolver
- a `removeFlash(key: $key)` mutation, that updates the `flashNotices @client` query

The main component is relying on `flashNoticesByKey(key: $key)` and `removeFlash(key: $key)`.

➡️ **Not sure if it's a bug or a bad implementation of the resolvers.**

**Intended outcome:**
I expect that calling `removeFlash(key: $key)`  updates the `useQuery` watching `flashNoticesByKey(key: $key)`.

**Actual outcome:**
Calling `removeFlash(key: $key)` does updates `flashNotices`, but not `flashNoticesByKey(key: $key)`

**How to reproduce the issue:**

https://codesandbox.io/s/apollo-local-query-with-args-2kfk6

**Versions**
```
"@apollo/react-hooks": "3.1.5",
"apollo-cache": "1.3.4",
"apollo-cache-inmemory": "1.6.5",
"apollo-client": "2.6.8",
```

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
