### ISSUE TITLE
client.watchQuery does not start polling when `pollInterval` given

### ISSUE THREAD

**Issue by aryzing** [apollographql/apollo-client#6172]
**Intended outcome:**

When calling `client.watchQuery` with the `pollInterval` set, the query should be run periodically with the provided interval.

Eg, given

```js
const observableQuery = client.watchQuery({
  query: MY_QUERY,
  pollInterval: 1000,
});
```

The `MY_QUERY` query should run every second.

**Actual outcome:**

The query does not run at the specified polling intervals after calling `watchQuery` with a `pollInterval` set. In order to trigger the polling behavior, I'm faced with choosing one of the two below approaches, which feel wrong.

**Approach 1** I was able to get it polling by calling `observableQuery.startPolling(1000)`. I had to pass the interval argument, which is required, despite it already being set in the `watchQuery` options above. Why do I need to specify this argument again?

**Approach 2** Alternatively, I was also able to get it to start polling by calling the `.subscribe()` method,

```js
observableQuery.subscribe({
  next(x) {
    console.log('Next:', x);
  },
  error(err) {
    console.log(`Finished with error: ${err}`);
  },
  complete() {
    console.log('Finished');
  },
});
```

This way of triggering the polling behavior seems like overkill since I don't need to read the value.

**How to reproduce the issue:**

Follow steps in "Actual outcome" section.

**Versions**

```
  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
  Binaries:
    Node: 13.12.0 - ~/.nvm/versions/node/v13.12.0/bin/node
    Yarn: 1.22.4 - ~/workspace/project/node_modules/.bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v13.12.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.92
    Firefox: 75.0
  npmPackages:
    @apollo/react-components: ^3.1.5 => 3.1.5 
    @apollo/react-hoc: ^3.1.5 => 3.1.5 
    @apollo/react-hooks: ^3.1.5 => 3.1.5 
    @apollo/react-testing: ^3.1.4 => 3.1.4 
    apollo: ^2.27.0 => 2.27.0 
    apollo-boost: ^0.4.7 => 0.4.7 
    apollo-cache: ^1.3.4 => 1.3.4 
    apollo-cache-inmemory: ^1.6.5 => 1.6.5 
    apollo-client: ^2.6.8 => 2.6.8 
    apollo-link: ^1.2.14 => 1.2.14 
    apollo-utilities: ^1.3.3 => 1.3.3 
```

**Comment by hwillson** [comment]
@aryzing would you be able to provide a small runnable reproduction that demonstrates this? Thanks!

**Comment by hwillson** [comment]
We'll need a reproduction (using `@apollo/client@latest`) to be able to troubleshoot this further. Thanks!
