### ISSUE TITLE
InMemoryCache | IE Issue | Object does not support property or method 'values' 

### ISSUE THREAD

**Issue by GoPro16** [apollographql/apollo-client#6173]
**Intended outcome:**
We are using `ApolloClient` and the `InMemoryCache` in our applications and were assuming that the package runs in IE 11 as well.

**Actual outcome:**
One of the paths during a query hit [this line of code](https://github.com/apollographql/apollo-client/blob/master/src/cache/inmemory/entityStore.ts#L292) which is not an available method in IE.

```
Object does not support property or method 'values'
```

**How to reproduce the issue:**
I don't know the internals of this but I am assuming if an object returned from graphql has children or nested objects that are traversable then that conditional check will fire.

**Versions**
```
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    Yarn: 1.19.1 - ~/Workspaces/availity/dashboard-workspace/dashboard/node_modules/.bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 75.0
    Safari: 13.1
  npmPackages:
    @apollo/react-hooks: ^3.1.2 => 3.1.2
    @apollo/react-testing: ^3.1.3 => 3.1.3
    apollo: ^2.20.0 => 2.20.0
    apollo-boost: ^0.4.4 => 0.4.4
    apollo-cache-inmemory: ^1.6.3 => 1.6.3

```

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
