### ISSUE TITLE
@client directive breaks fragments

### ISSUE THREAD

**Issue by Banou26** [apollographql/apollo-client#6175]
**Intended outcome:**
Trying to use a fragment in a query with @client directive

```js
export const GET_APPS = gql`
  fragment AppFragment on App {
    id
    name
  }
  query GetApps {
    apps @client {
      ...AppFragment
      # id
      # name
    }
  }
`
```

Returns the apps with their `id` and `name` fields(it works if i uncomment the two fields)

**Actual outcome:**
The apps are returned with no fields at all

**How to reproduce the issue:**
I'm just using a TypePolicies Query that returns an array of object with the `id` and `name` fields

**Versions**
`"@apollo/client": "^3.0.0-beta.43"`

**Comment by ElForastero** [comment]
I have encountered the same issue.

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!

**Comment by Banou26** [comment]
Still an issue under ^3.3.16 which is current latest

Repro here with the code example i gave: https://github.com/Banou26/apollo-client-bug-6175

**Comment by brainkim** [comment]
@Banou26 You’re a champ! Thank you so much!
