### ISSUE TITLE
Apollo Client 3: defaultOptions type does not contain partialRefetch

### ISSUE THREAD

**Issue by kvnkusch** [apollographql/apollo-client#6177]
**Intended outcome:**
Setting the defaultOptions on an ApolloClient instance to include partialRefetch: true.

```
const client = new ApolloClient({
  link,
  cache,
  defaultOptions: {
    query: {
      partialRefetch: true
    }
  }
});
```

According to this issue this should be possible:
https://github.com/apollographql/apollo-feature-requests/issues/172

**Actual outcome:**
The above failed typechecks, the relevant types are:
```
export interface DefaultOptions {
    watchQuery?: Partial<WatchQueryOptions>;
    query?: Partial<QueryOptions>;
    mutate?: Partial<MutationOptions>;
}

export interface QueryOptions<TVariables = OperationVariables> extends QueryBaseOptions<TVariables> {
    fetchPolicy?: FetchPolicy;
}

export interface ModifiableWatchQueryOptions<TVariables = OperationVariables> extends QueryBaseOptions<TVariables> {
    pollInterval?: number;
    notifyOnNetworkStatusChange?: boolean;
    returnPartialData?: boolean;
    partialRefetch?: boolean;
}
```

partialRefetch is included in `ModifiableWatchQueryOptions` but not `QueryOptions`, which `DefaultOptions` references. Is this intentional, and is it actually possible to default partialRefetch to true for all queries?

**Versions**
@apollo/client@3.0.0-beta.43

**Comment by Jonathannsegal** [comment]
From what I see it seems like the reason that this is not passing typeschecks is because it is now a default behavior and shouldent need to be defined in default options. It is still interesting that its failing, will keep looking into this.

**Comment by DCtheTall** [comment]
@hwillson I'd like to write a PR for this if it's available

**Comment by DCtheTall** [comment]
I think a pretty simple solution is to merge the `ModifiableWatchQueryOptions`, `QueryBaseOptions` and `QueryActions` types into one? I don't think this would have any consequences outside of `src/core/watchQueryOptions.ts`

**Comment by hwillson** [comment]
This was addressed in https://github.com/apollographql/apollo-client/pull/7136 - thanks!
