### ISSUE TITLE
onError either has wrong type or returns unexpected value

### ISSUE THREAD

**Issue by lifeiscontent** [apollographql/apollo-client#6179]
**Intended outcome:**
`onError` apollo-link-error says it returns a list of `GraphQLError` in typescript but if that was true, it wouldn't be an array of plain objects, but an array of `Error` objects. Which it is not, and now I have to wrap the errors in a custom error class for my error reporting service to classify it as an error when this seems like an issue from apollo.

**Actual outcome:**

The list of GraphQLErrors is a list of objects, not instances of `Error`

**How to reproduce the issue:**

setup a server that returns a GraphQL Error, inspect the data that comes back via the onError link

**Versions**

  System:
    OS: macOS 10.15.4
  Binaries:
    Node: 12.16.1 - ~/n/bin/node
    Yarn: 1.22.4 - ~/Source/trusted-web/node_modules/.bin/yarn
    npm: 6.13.4 - ~/n/bin/npm
  Browsers:
    Firefox: 70.0
    Safari: 13.1
  npmPackages:
    @apollo/react-common: 3.1.4 => 3.1.4 
    @apollo/react-components: 3.1.4 => 3.1.4 
    @apollo/react-hoc: 3.1.4 => 3.1.4 
    @apollo/react-hooks: 3.1.4 => 3.1.4 
    @apollo/react-ssr: 3.1.4 => 3.1.4 
    @apollo/react-testing: 3.1.4 => 3.1.4 
    apollo: 2.27.0 => 2.27.0 
    apollo-cache-inmemory: 1.6.5 => 1.6.5 
    apollo-client: 2.6.8 => 2.6.8 
    apollo-link: 1.2.14 => 1.2.14 
    apollo-link-context: 1.0.20 => 1.0.20 
    apollo-link-error: 1.1.13 => 1.1.13 
    apollo-link-http: 1.5.17 => 1.5.17 
    storybook-addon-apollo-client: 1.0.1 => 1.0.1

**Comment by hwillson** [comment]
@lifeiscontent where are you seeing that `onError` returns a list of `GraphQLError`'s? It should be [returning an `ApolloLink`](https://github.com/apollographql/apollo-link/blob/55d55d0a28e1844a3a92c11fe68e242d0fe730c2/packages/apollo-link-error/src/index.ts#L34).

**Comment by jcreighton** [comment]
Closing this issue as we never received a response. If you're still experiencing the issue, happy to re-open!
