### ISSUE TITLE
Endless rerender when useQuery used with useTranslation from react-i18next in suspense mode

### ISSUE THREAD

**Issue by two-legs** [apollographql/apollo-client#6184]
**Actual outcome:**

When I use hook `useTranslation` in Suspense mode (default) I'm getting endless rerender of the component:
```
const { data } = useQuery(GET_ITEM, {
    variables: {
      id: 'itemId',
    },
  });

  const { t } = useTranslation('common');
```

When I pass `{ useSuspense: false }` to the `useTranslation` the page loads correctly. 
With apollo-client 2.6 suspense mode works.

**How to reproduce the issue:**

Add `useQuery` and `useTranslation` to the one component. 

**Versions**

"@apollo/client": "^3.0.0-beta.43",
"react-i18next": "^11.3.3",

 System:
    OS: macOS 10.15.3
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Browsers:
    Chrome: 81.0.4044.113
    Firefox: 73.0.1
    Safari: 13.0.5

**Comment by hwillson** [comment]
@two-legs we haven't added official React Suspense support to Apollo Client. This is on our list to do after we launch Apollo Client 3.0.

**Comment by lorensr** [comment]
@two-legs you can track this issue for suspense support: https://github.com/apollographql/apollo-feature-requests/issues/162
