### ISSUE TITLE
Mocking new schema with @client mutation results in error

### ISSUE THREAD

**Issue by solugebefola** [apollographql/apollo-client#6185]
**Intended outcome:**
I was trying to mock new schema capabilites, per: https://www.apollographql.com/docs/react/development-testing/client-schema-mocking/, but I am running into an issue with a new mutation that is the only mutation in the call to the remote endpoint.  My extended schema:
```
extend type Mutation {
  deletePaymentMethod(data: DeletePaymentInput!): PaymentMethod!
}

type DeletePaymentInput {
  billingAccountId: ID!
  paymentMethodId: ID!
}
```
My mutation:
```
mutation DeletePaymentMethod(
        $billingAccountId: ID!
        $paymentMethodId: ID!
    ) {
        deletePaymentMethod @client (
            data: {
              billingAccountId: $billingAccountId
              paymentMethodId: $paymentMethodId
            }
        ) {
            paymentMethod {
              id
            }
        }
    }
```

**Actual outcome:**
The API call does not go through and I receive this error
> Error: Network error: (destructured parameter) is null

I suspect it's because the @client mutation is the only mutation/query on the call to the remote API and since Apollo strips it out and handles it locally, the remote call has no parameters.  This is just a guess though.  This is something that would be hard to reproduce without a working endpoint.  It seems though that if this _is_ the case, there should be some check for null parameters in the API call and some way to call off the remote call and just return the local results.

**How to reproduce the issue:**

**Versions**
  System:
    OS: macOS 10.15.4
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.122
    Safari: 13.1
  npmPackages:
    @apollo/react-hooks: ^3.1.3 => 3.1.3 
    apollo-boost: ^0.4.7 => 0.4.7 
    apollo-cache-inmemory: ^1.6.5 => 1.6.5 
    apollo-link-context: ^1.0.19 => 1.0.19 
    apollo-link-error: ^1.1.12 => 1.1.12 
    apollo-link-http: ^1.5.16 => 1.5.16 
    react-apollo: ^2.5.8 => 2.5.8

**Comment by hwillson** [comment]
@solugebefola Any chance you could test things out using `@apollo/client@beta` instead? A small runnable reproduction would definitely help us troubleshoot.

**Comment by solugebefola** [comment]
I used the error reproduction repo to create a small runnable repro.  Sorry if this is some simple thing that I'm overlooking, but I'm getting a similar Network error
> Network error: Cannot read property 'id' of null
Here is the link: https://github.com/solugebefola/react-apollo-error-template

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
