### ISSUE TITLE
watchQuery with pollInterval ignores no-cache fetchPolicy

### ISSUE THREAD

**Issue by timkendrick** [apollographql/apollo-client#6187]
Currently, when executing a `watchQuery` with a `pollInterval` and the `fetchPolicy: 'no-cache'` option, the caching option [is overridden](https://github.com/apollographql/apollo-client/blob/master/src/core/QueryManager.ts#L1235-L1238) internally within Apollo to `network-only`, causing data to be written to the cache despite the `no-cache` fetch policy.

**Intended outcome:**
```js
client.watchQuery({
  query,
  pollInterval: 1000,
  fetchPolicy: 'no-cache', // No objects should be written to the cache
}).valueChanges.subscribe(...);

```

**Actual outcome:**
The cache `.write()` method is called with the results of the query

**How to reproduce the issue:**
See 'Intended outcome' section

**Versions**
```
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 12.14.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.113
    Firefox: 61.0.2
    Safari: 13.1
  npmPackages:
    @apollo/client: 3.0.0-beta.44 => 3.0.0-beta.44
```

**Comment by hwillson** [comment]
@timkendrick can you re-rest with `@apollo/client@3.0.0-beta.50` and let us know if this is still an issue?

**Comment by VasiliKubarka** [comment]
Have the same bug for apollo-client v 2.6.10

**Comment by mutefiRe** [comment]
same bug here with @apollo/client@3.1.3

**Comment by jcreighton** [comment]
Marking this is as `needs-reproduction` since I see this might still be an issue. If so, a runnable reproduction will go a long away in helping us resolve this. You can use either [this repo](https://github.com/apollographql/react-apollo-error-template) or [this CodeSandbox](https://codesandbox.io/s/github/apollographql/react-apollo-error-template/tree/master/) to reproduce the issue.

**Comment by Wozniaxos** [comment]
Have the same issue with apollo 3.3.8 - on every poll interval with "no-cache" policy query enters cache read/merge functions.  https://codesandbox.io/s/stoic-star-0g4ms?file=/src/App.js

**Comment by amitgoldarb** [comment]
This still happens in apollo/client v3.5.8

**Comment by EllaSharakanski** [comment]
@jcreighton I think this might be the problematic line in the code: https://github.com/apollographql/apollo-client/blob/main/src/core/ObservableQuery.ts#L637
It always uses `network-only` for polling

**Comment by jpvajda** [comment]
This issue might be related to what was reported in #9691

**Comment by MrDoomBringer** [comment]
Commenting to say this should be resolved in https://github.com/apollographql/apollo-client/pull/10020! Please let us know if this issue is still cropping up after our next release.

All the best,
Emmanuel, Intern :-)
