### ISSUE TITLE
Wrong results received from useQuery

### ISSUE THREAD

**Issue by kozborn** [apollographql/apollo-client#6203]
**Intended outcome:**
I'm trying to fetch rather simple object from by backend, I see in Network tab correct response
with correct data (payee name in main object == 'Allegro')
```
{
  "payee": {
    "id": "6",
    "name": "Allegro",
    "entries": [
      {
        "payee": {
          "id": "6",
          "name": "Allegro",
        },
        "category": {
          "id": "3",
          "name": "Dom",
        },
      },
      {
        "payee": {
          "id": "6",
          "name": "Allegro",
          "__typename": "Payee"
        },
        "category": {
          "id": "2",
          "name": "Mieszkanie",
        },
      },
      {
        "payee": {
          "id": "6",
          "name": "Allegro",
          "__typename": "Payee"
        },
        "category": {
          "id": "6",
          "name": "Dzieci",
        },
      }
    ],
  }
}
```

**Actual outcome:**

But when I log it in app I receive this (payee name in main object == 'Dzieci', which comes from `category` with the same id = 6)
```
{
  "payee": {
    "id": "6",
    "name": "Dzieci",
    "entries": [
      {
        "payee": {
          "id": "6",
          "name": "Dzieci",
        },
        "category": {
          "id": "3",
          "name": "Dom",
        },
      },
      {
        "payee": {
          "id": "6",
          "name": "Dzieci",
        },
        "category": {
          "id": "2",
          "name": "Mieszkanie",
        },
      },
      {
        "payee": {
          "id": "6",
          "name": "Dzieci",
        },
        "category": {
          "id": "6",
          "name": "Dzieci",
        },
      }
    ],
  }
}
```

And sometimes (not every time) I see this in console
```
VM7095 main.js:6059 You are using the simple (heuristic) fragment matcher, but your queries contain union or interface types. Apollo Client will not be able to accurately map fragments. To make this error go away, use the `IntrospectionFragmentMatcher` as described in the docs: https://www.apollographql.com/docs/react/advanced/fragments.html#fragment-matcher
```
But this link is broken

**How to reproduce the issue:**
Not really sure, as I said, I see correct data in response and wrong data in app.

Here is my useQuery
```
  const { loading, error, data } = useQuery(PAYEE, {
    variables: {
      payeeId,
    },
    fetchPolicy: "network-only",
  });

  console.log(data);
```

```
const PAYEE = gql`
  query Payee($payeeId: ID!) {
    payee(id: $payeeId) {
      id
      name
      entries {
        ...entryFragment
      }
    }
  }
  ${entryFragment}
`;
```

```
export default gql`
  fragment entryFragment on Entry {
    id
    payee {
      id
      name
    }
    category {
      id
      name
    }

  }
`;
```

But it doesn't matter if I use fragment here or not, it still gives me wrong data

**Versions**

  System:
    OS: Linux 5.3 Linux Mint 19.3 (Tricia)
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.113
    Firefox: 75.0

**Comment by kozborn** [comment]
I'll answer my own question, it started to work correctly when I added aliases
```
payeeId: id
```
and
```
categoryId: id
```

in fragment

But still, I don't think it is desired behaviour.

**Comment by hwillson** [comment]
We've moved away from the heuristic fragment matcher in `@apollo/client`, to an easier to use feature called [`possibleTypes`](https://www.apollographql.com/docs/react/v3.0-beta/data/fragments/#defining-possibletypes-manually). If you're able to use the `@apollo/client@beta`, `possibleTypes` are the recommended approach moving forward.
