### ISSUE TITLE
[3.0.0-beta.44] cache.modify function

### ISSUE THREAD

**Issue by nratter** [apollographql/apollo-client#6205]
According to https://www.apollographql.com/docs/react/v3.0-beta/migrating/apollo-client-3-migration/#breaking-cache-changes, there is a new cache.modify function that can be used to update the cache. I haven't seen any documentation for how to use this, however. Can someone point me in the right direction or do the docs still need to be updated for this?

**Comment by hwillson** [comment]
@nratter `cache.modify` was recently removed. See https://github.com/apollographql/apollo-client/pull/6289 for the full details.

**Comment by mrflip** [comment]
... and it was un-removed! in #6350. See there.
