### ISSUE TITLE
"Missing cache result fields" on queries, when using cache-and-network fetch policy (but not cache-first)

### ISSUE THREAD

**Issue by xxx** [apollographql/apollo-client#6211]
**Intended outcome:**
I am running a single query with `useLazyQuery`'s returned function multiple times, with different arguments. I expect all results to be written to Apollo's cache in a way that allows subsequent use of that data in later queries, without any warnings in my console.

**Actual outcome:**

The first query runs, and populates the cache as expected. When I run the query a second time, with a different ID/params, I get the warning, but the query runs, and the cache is populated with fetched data as I expect. If I use the *same* params as the first query, there is no warning. We're using `cache-and-network` as the fetch policy for this case, because this data needs to stay relatively fresh.

If I instead use the default `cache-first` fetch policy, *both* queries fetch and populate without any warnings at all (and subsequent uses pull only from the cache, as expected). This specifically is why I'm pretty sure the warning is invalid for my case. I would expect the warning to either always pop on the second query, or never, regardless of fetch policy, because the second query is still being fetched from the server, and populating the cache.

[Here](https://gist.github.com/xxx/9f408a34b8d1907bc7ace6a00a72c47c) are a couple of dumps of the Apollo cache, after two queries have run, for both cache-and-network, and cache-first policies. They are byte-for-byte identical.

The actual warning I receive, along with a breakdown of the JSON object contained in it, are [here](https://gist.github.com/xxx/7927782ed13528471daa3d06d13f83c3).

**How to reproduce the issue:**

I've spent a couple of hours trying to recreate this issue ([repo is here](https://github.com/xxx/apollo-cache-warning)), but have so far been unable to do so, and I don't understand what I'm doing differently, if anything. Any pointers to help replicate the issue are welcome.

The warning really does seem to be incorrect in this case, but I'm trying to figure out if there's anything non-intuitive that I am missing.

**Versions**

  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 80.0.3987.87
    Firefox: 75.0
  npmPackages:
    @apollo/client: ^3.0.0-beta.44 => 3.0.0-beta.44 
    @apollo/link-error: ^2.0.0-beta.3 => 2.0.0-beta.3 
    @apollo/react-testing: ^4.0.0-beta.1 => 4.0.0-beta.1 
    react-apollo: ^3.1.5 => 3.1.5

**Comment by joshjg** [comment]
Similarly, I'm getting this warning when variables to a query change, causing a new network request. The warning occurs before the network request has finished. Here's a simplified example of the query:
```
query getUser($id: ID!, $activityType: ActivityType) {
    user(id: $id) {
        id
        activities(type: $activityType) {
            nodes {
                id
            }
        }
    }
}
```
So when the `activityType` variable changes from A to B, I get the warning, even though it's totally expected that the cache result would not be populated yet (this is the FIRST time we have asked for `activities(type: B)` for this user).

However I should note that in my case I'm using the default fetch policy.

**Comment by joshjg** [comment]
After reading @benjamn 's comment here: https://github.com/apollographql/apollo-client/issues/6136#issuecomment-663637207 I understand this is just an overly noisy warning and does not indicate an actual issue in my case.

> In your example of a list/detail view, it should be fine to fetch just the id first, and then the rest of the fields later. You may be getting a warning in that case, but that doesn't mean anything bad is happening—unless you consider triggering a network request bad, which it can be, of course, when you don't expect it to happen… and in those cases it's convenient to have some sort of warnings that can help diagnose why the result from the cache wasn't good enough.

**Comment by hwillson** [comment]
https://github.com/apollographql/apollo-client/issues/6211#issuecomment-696853529 nails it - thanks!
