### ISSUE TITLE
MockedProvider doesn't work as expected when passing a client with options to useQuery

### ISSUE THREAD

**Issue by francylang** [apollographql/apollo-client#6217]
**Intended outcome:**

I have been trying to use `<MockedProvider />` to  test a component that utilizes the `useQuery` hook, but because I am passing a different client via options, I am getting `undefined` returned for the data.

Query: 
```javascript
export const getByUuid = gql`
  query getByUuid($uuid: [String!]!) {
    users(uuid: $uuid) {
      firstName
      lastName
    }
  }
`;
```

Component:
```javascript
export const Comment = ({ uuid }) => {
 const { data, loading } = useQuery(getByUuid, {
  variables: {
    uuid
  },
  client: upsPlatformClient
 })

 return (
  <div>{`${data.users.firstName} ${data.users.lastName}`}</div>
 )
}
```
Test:
```javascript 
describe('Comment component', () => {
  const mock = {
    request: {
      query: getByUuid,
      variables: {
        id: '82nbdu-4729',
      },
    },
    result: {
      data: {
        users: {
          firstName: 'Sam',
          lastName: 'Lopez',
        },
      },
    },
  };

  const TestComponent = (props) => {
    return render(
      <MockedProvider mocks={[mock]} addTypename={false}>
        <Comment />
      </MockedProvider>
    );
  };

  it('renders with data', async () => {
    const { findByText } = TestComponent();

    expect(await findByText('Sam Lopez'));
  });
 });
```

**Actual outcome:**

![image](https://user-images.githubusercontent.com/24443103/80635785-9eb99780-8a19-11ea-97bb-855a56971348.png)

However, if I comment out the client option in the `useQuery` hook, the mock data is returned as expected.
```javascript
 const { data, loading } = useQuery(getByUuid, {
  variables: {
    uuid
  },
//  client: upsPlatformClient
})
```
![image](https://user-images.githubusercontent.com/24443103/80635977-f48e3f80-8a19-11ea-841f-deb13f3daab4.png)

**Versions**

  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 9.11.1 - ~/.nvm/versions/node/v9.11.1/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v9.11.1/bin/npm
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 71.0
    Safari: 13.1
  npmPackages:
    @apollo/react-hooks: ^3.1.1 => 3.1.4
    @apollo/react-testing: ^3.1.3 => 3.1.4
    apollo-boost: ^0.4.7 => 0.4.7
    apollo-cache-inmemory: ^1.6.5 => 1.6.5
    apollo-client: ^2.6.8 => 2.6.8
    apollo-link: ^1.2.13 => 1.2.14
    apollo-utilities: ^1.3.3 => 1.3.3

**Comment by hwillson** [comment]
@francylang yes, this is a current limitation of `MockedProvider`. `MockedProvider` is intended to replicate the behavior of `ApolloProvider`, which means it creates its own client instance to use with the provided mock data. It does not touch any `ApolloClient` instances passed into your hooks, via options. If you would like to see this handled differently, please consider opening a feature request for this over in https://github.com/apollographql/apollo-feature-requests. Thanks!

**Comment by Shelagh-Lewins** [comment]
If you provide 'undefined' as the client in testing, MockedProvider seems to work as usual.

```
export const Comment = ({ uuid }) => {
 const { data, loading } = useQuery(getByUuid, {
  variables: {
    uuid
  },
  client: getUpsPlatformClient()
 })
```

Use a helper function from another module:

`getUpsPlatformClient = () => upsPlatformClient;`

Mock the helper to return undefined as part of test setup:

```
jest.mock('../path/to/module/getUpsPlatformClient.js', () => ({
  __esModule: true,
  default: jest.fn(() => undefined),
}));
```

**Comment by jitendra-gosavi** [comment]
@Shelagh-Lewins Thanks for the solution. It at least led me somewhere. However, I am getting an error as follows if I make the client undefined.

![image](https://user-images.githubusercontent.com/78083947/171202756-07c9438c-6e46-4a45-abd6-d765e43ab1bf.png)
