### ISSUE TITLE
Broken Pupstagram Demo

### ISSUE THREAD

**Issue by moritzWa** [apollographql/apollo-client#6226]
**Intended outcome:**
I was clicking on [this link](https://codesandbox.io/s/r5qp83z0yq) to view learn more about the [Zero-config caching ](https://www.apollographql.com/docs/react/why-apollo/#zero-config-caching)

**Actual outcome:**
Code-Sandbox-app did not work
![Screenshot 2020-05-01 at 20 20 35](https://user-images.githubusercontent.com/42035131/80830466-4c2ed580-8be9-11ea-96ea-bcca382a6617.png)

![Screenshot 2020-05-01 at 20 21 29](https://user-images.githubusercontent.com/42035131/80830498-59e45b00-8be9-11ea-994e-74c03c042600.png)

**How to reproduce the issue:**
go to https://codesandbox.io/s/r5qp83z0yq

**Versions**
@apollo/react-hooks  0.1.0-beta.11 
apollo-boost               0.4.3

**Comment by hwillson** [comment]
Thanks @moritzWa - we're no longer maintaining this demo app, and it's being removed from the Apollo Client 3 documentation (which will be updated shortly). For a more up to date example app, see: https://github.com/apollographql/fullstack-tutorial
