### ISSUE TITLE
Import setContext in 3.0 authorization doc

### ISSUE THREAD

**Issue by dandv** [apollographql/apollo-client#6231]
https://github.com/apollographql/apollo-client/blob/release-3.0/docs/source/networking/authentication.mdx doesn't import `setContext` from anywhere.

**Comment by dandv** [comment]
Also, I get this TypeScript error from [that code sample](https://www.apollographql.com/docs/react/v3.0-beta/networking/authentication/#header):

![image](https://user-images.githubusercontent.com/33569/80860022-2a048880-8cb9-11ea-913c-49c35e9495f0.png)

**Comment by dandv** [comment]
Also, there's a TypeScript error in that sample - https://github.com/apollographql/apollo-link/issues/1273.

**Comment by juancarlosqr** [comment]
@dandv @Jonathannsegal @hwillson this can be closed. Now the documentation reflects the import:

https://github.com/apollographql/apollo-client/blob/main/docs/source/networking/authentication.mdx

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-client/issues/6231#issuecomment-680756615, this has been resolved. Thanks!
