### ISSUE TITLE
Need to skip in useQuery to cached query with initial state works in SSR

### ISSUE THREAD

**Issue by NiestrojMateusz** [apollographql/apollo-client#6236]
Hello, I have a case where I try to use `useQuery` hooks with SSR. The case is that I need to  `useQuery` in parent component to get config. That query is saved to apollo client cache with initial state when I invoke the ApolloClient. Config includes variables for nested queries in child components. The issue is that `getDataFromTree` from `@apollo/react-ssr` seems to invoke all queries at once (even cached queries) so variables that comes from parent query are undefined for nested queries so `getDataFromTree` throw error and everything is fetched client side instead server side;
Only solutions that I found is to use `skip` property for `useQuery` options or to use `useLazyQuery` instead and manually call query after check if variables are defined.
The config variables are pass to every query in app so the both of that solutions are cumbersome.

**Intended outcome:**
When I use `getDataFromTree` the `@client` queries with data saved in cache during Apollo client initialization should be available without delay, and I can use the result as variables in nested queries and everything is fetched SSR correctly.

**Actual outcome:**
When I use `getDataFromTree` the `@client` queries with data saved in cache during Apollo client initialization are treated as asynchronous and result of that query needed in nested children queries are `undefined` and queries are correctly fetched only client side

**How to reproduce the issue:**
https://codesandbox.io/s/broken-sea-s7rfs?file=/components/PostsProvider.js
Here I create some reproduction example. The Config query is fetched in `components/ConfigProvider.js`. Config provider is used in `pages/_app.js`, and results are passed to `components/PostProvider.js` which has my nested `useQuery` that use variables based on above ConfigQuery results.

In `components/PostProvider.js` I also leave commented solutions that I mention above in introduction. If that is no bug and that is correct and intended behavior, and my solutions/workarounds are correct please let me know.

**Versions**
 "@apollo/react-hooks": "3.1.3",
 "@apollo/react-ssr": "3.1.3",
 "apollo-cache-inmemory": "1.6.5",
 "apollo-client": "2.6.8",
 "apollo-link-http": "1.5.16",
 "graphql": "^14.0.2",
 "graphql-tag": "2.10.3",
 "isomorphic-unfetch": "^3.0.0",
  "next": "latest",
  "prop-types": "^15.6.2",
  "react": "16.13.1",
  "react-dom": "16.13.1"

**Comment by wwwebman** [comment]
Is there any update on this?

**Comment by nathanschwarz** [comment]
Does your `@client` directives (fields or queries) are initialized server-side ?
Did you try to fetch the `@client` with the `cache-only` directive server side ? (and not the default `cache-and-network` which resolves into a Promise).

**Comment by NiestrojMateusz** [comment]
@nathanschwarz thanks for answering. 
> Does your @client directives (fields or queries) are initialized server-side ?

Yes, sure. It is initialized when ApolloClient is initialized

> Did you try to fetch the @client queries with the cache-only directive server side ? (and not the default cache-and-network which resolves into a Promise).

Unfortunately it doesn't solve the issue. Nothing change

**Comment by nathanschwarz** [comment]
@NiestrojMateusz I faced the same issue with SSR.

To solve this issue you need to check for an `undefined` value of data in your `ConfigProvider` and do `if (data === undefined) {
    return null;
}`.

This is the "normal" behavior of `getDataFromTree ` (even thought it's very confusing) :

mainly, `getDataFromTree` is derived of React `renderToString`, it browse all your tree for every queries / subscriptions and fetch these in the same order. it fills the cache with the data asynchronously **but it does not act as a renderer** (all the queries are fetched correctly and in the correct order, but its react which crashes here).

That's why there's a `ReactDOM.renderToString` after `getDataFromTree` in the documentation.

if you `console.log(apolloClient.cache.extract())` you'll see that all the data is there.

**Comment by hwillson** [comment]
Solution in https://github.com/apollographql/apollo-client/issues/6236#issuecomment-633614770 - thanks!
