### ISSUE TITLE
cache is required in `ApolloClientOptions` even if `no-cache` set globally

### ISSUE THREAD

**Issue by machi1990** [apollographql/apollo-client#6237]
**Intended outcome:**

The cache  https://github.com/apollographql/apollo-client/blob/8ee7648371fb3bac621af5c38fd98afb1f0bd7d7/src/ApolloClient.ts#L42 field to be optional.

Further down the line, cache seems to be always required - https://github.com/apollographql/apollo-client/blob/8ee7648371fb3bac621af5c38fd98afb1f0bd7d7/src/ApolloClient.ts#L140-L143

even if an app does not need one by setting global defaultOptions.

**Actual outcome:**

cache field is required 

**How to reproduce the issue:**

try to create a client with the following content:

```typescript
const noCache = 'no-cache';

const defaultOptions: DefaultOptions = {
  watchQuery: {
    fetchPolicy: noCache,
  },
  query: {
    fetchPolicy: noCache,
  },
  mutate: {
    fetchPolicy: noCache
  }
};

const clientConfig = {
  defaultOptions,
  link: authLink.concat(splitLink)
};

const apolloClient = new ApolloClient(clientConfig);
```

The above code would neither compile unless a cache field is supplied in `clientConfig`.

**Versions**
N/A

**Comment by machi1990** [comment]
If it makes sense to make the `cache` field optional, I can provide a PR.

**Comment by hwillson** [comment]
@machi1990 Supplying `ApolloClient` with a `cache` instance is currently required, even when using the `no-cache` fetch policy exclusively. This isn't something we're going to change anytime soon, as we're planning on leveraging the cache more extensively for internal operations, in the future. E.g. our React hooks are going to interact with the cache much more directly, to track application changes.
