### ISSUE TITLE
Is it possible to pass the mutator function input or other context variables to the onCompleted/onError handlers?

### ISSUE THREAD

**Issue by LeeKevin** [apollographql/apollo-client#6239]
I have a PR at https://github.com/apollographql/apollo-client/pull/6238/files. 

It's not well-typed, but I wanted it to serve as a foundation for what I think is an important feature for Apollo Client.

Within the `onCompleted`/`onError` handlers, I would like to have access to the input data or other context variables which are available in the context where the mutator function is called.

Ideas?

**Comment by LeeKevin** [comment]
Requested a few times. One other instance: https://spectrum.chat/apollo/react-apollo/how-do-you-access-a-mutations-variables-after-invoked~98e6c8ac-119a-4815-973f-ed539a6c03c9

**Comment by SHND** [comment]
Any updates on this?
