### ISSUE TITLE
Polling starts when variables change for a skipped query

### ISSUE THREAD

**Issue by roninjin10** [apollographql/apollo-client#6240]
**Intended outcome:**
Expected query that is skipped to not start polling when query is skipped.

**Actual outcome:**
At first the polling does not happen.  But if the variables change the polling is started.

**How to reproduce the issue:**
Wrote a failing jest test reproducing the issue here https://github.com/roninjin10/ApolloPollingBug

In summary, to reproduce this do a useQuery and pass in a pollingInterval and skip: true.   Polling will not happen.  But then if you change the variables a polling interval will get kicked off.

**Versions**
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 12.10.0 - ~/Projects/spark/.buildenv/bin/node
    Yarn: 1.13.0 - ~/Projects/spark/.buildenv/bin/yarn
    npm: 6.10.3 - ~/Projects/spark/.buildenv/bin/npm
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 72.0.2
    Safari: 13.1
  npmPackages:
    @apollo/react-testing: ^3.1.4 => 3.1.4 
    apollo-cache-inmemory: ^1.6.5 => 1.6.5 
    apollo-client: ^2.6.8 => 2.6.8 
    react-apollo: ^3.1.5 => 3.1.5

**Comment by benjamn** [comment]
Try `beta.46` (just released), which includes PR #6221, which changes/improves some things about how polling works?

**Comment by roninjin10** [comment]
Seeing same issue on @apollo/client@3.0.0-beta.46

**Comment by benjamn** [comment]
@roninjin10 Can you push those changes to your reproduction repo, so I can see exactly what you mean?

**Comment by roninjin10** [comment]
So I tested this out on our app and it didn't work.  But just now when I updated packages in my reproduction repo the tests pass so I think this issue is resolved and I on our app it was just user error by me failing to correctly update the packages.   I'll try upgrading them again later today on our actual app and expect that the issue will be resolved.  I'll close this issue then.

**Comment by hwillson** [comment]
Great news @roninjin10 - we'll close this for now, but definitely let us know if you're still encountering this issue. Thanks!
