### ISSUE TITLE
Fix types: `prev` in `fetchMore`'s `updateQuery` may be undefined

### ISSUE THREAD

**Issue by aryzing** [apollographql/apollo-client#6242]
**Intended outcome:**

The type of `prev` in `updateQuery` in `fetchMore` should have an `| undefined` added to its type.

**Actual outcome:**

The type for the previous data of a query may be undefined if `fetchMore`'s `updateQuery` runs after an initially failed query.

Eg.

1. `useQuery` fails with error for whatever reason. 
2. After the failed query has run, `fetchMore` is called to fetch more data
3. The first argument of the `updateQuery` method, typically called `prev` will be undefined. However, the type of `prev` does not include an `| undefined` type, causing confusion and leaving open the potential for bugs.

**How to reproduce the issue:**

Execute `fetchMore` after a failed query.

**Versions**

```
  System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
  Binaries:
    Node: 13.7.0 - ~/.nvm/versions/node/v13.7.0/bin/node
    Yarn: 1.22.4 - ~/workspace/oos-notifications-only/node_modules/.bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v13.7.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.113
    Firefox: 75.0
  npmPackages:
    @apollo/react-components: ^3.1.5 => 3.1.5 
    @apollo/react-hoc: ^3.1.5 => 3.1.5 
    @apollo/react-hooks: ^3.1.5 => 3.1.5 
    @apollo/react-testing: ^3.1.4 => 3.1.4 
    apollo: ^2.27.0 => 2.27.0 
    apollo-boost: ^0.4.7 => 0.4.7 
    apollo-cache: ^1.3.4 => 1.3.4 
    apollo-cache-inmemory: ^1.6.5 => 1.6.5 
    apollo-client: ^2.6.8 => 2.6.8 
    apollo-link: ^1.2.14 => 1.2.14 
    apollo-link-ws: ^1.0.20 => 1.0.20 
    apollo-utilities: ^1.3.3 => 1.3.3
```

**Comment by 3nvi** [comment]
I think that fetchMore was not intended to be used that way, since it's counting on the fact that the initial query brought something back.

If I were you, I'd try and locally shim that (through a definition file), since it looks like you have a very particular scenario (or business requirement).

**Comment by aryzing** [comment]
Thanks for the suggestion @3nvi. I agree with you: this way of using `fetchMore` is probably a little outside the norm. It seems though that types are a description of the data more so than the conventions we agree on for how the data is used. In other words, while this may not be the intended usage, it is a possible usage, and the types should take this case into account to be considered accurate.

**Comment by hwillson** [comment]
Thanks for reporting this. Would you mind trying Apollo Client 3 (`@apollo/client`) out? We've changed some of the `fetchMore` behavior and would love feedback. Thanks!

**Comment by hwillson** [comment]
Closing for now - please try `@apollo/client` if you get a chance, as there's a good chance this is is now resolved. Thanks!
