### ISSUE TITLE
Error: GraphQL error: Validation Error "source" is not allowed

### ISSUE THREAD

**Issue by omar-dulaimi** [apollographql/apollo-client#6243]
**Intended outcome:**
I added a field called source to schema, having one of two string values. When I to try to include it in new creations/updates (mutations), the error below gets triggered.

**Actual outcome:**
```
Error: GraphQL error: Validation Error "source" is not allowed
    at new ApolloError (bundle.esm.js:63)
    at Object.next (bundle.esm.js:1004)
    at notifySubscription (Observable.js:135)
    at onNotify (Observable.js:179)
    at SubscriptionObserver.next (Observable.js:235)
    at bundle.esm.js:866
    at Set.forEach (<anonymous>)
    at Object.next (bundle.esm.js:866)
    at notifySubscription (Observable.js:135)
    at onNotify (Observable.js:179)
    at SubscriptionObserver.next (Observable.js:235)
    at bundle.esm.js:76
```

**How to reproduce the issue:**
In any existing schema just add the following:
```
type TypeName {
  source: TypeCreateSource
}

```
```
enum TypeCreateSource {
  STR1
  STR2
}

```
Now try creating/updating a new item of type TypeName while giving source a value from the two above. it should fail.

**Versions**
```
  System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
  Binaries:
    Node: 12.16.2 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.4 - /usr/bin/npm
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 75.0
  npmPackages:
    apollo-boost: ^0.4.7 => 0.4.7 
    apollo-cache-inmemory: ^1.6.5 => 1.6.5 
    apollo-client: ^2.6.8 => 2.6.8 
    apollo-link-http: ^1.5.16 => 1.5.16
```

**Comment by omar-dulaimi** [comment]
Is source a reserved word or something?

**Comment by 3nvi** [comment]
Can you post some more information? You mentioned queries and mutations, so can we please see your full schema along with a query and/or mutation that fails?

**Comment by 3nvi** [comment]
Normally these sort of errors are not related to Apollo, but to GraphQL in general. It can either be triggered by `graphql-js` or even your backend.

**Comment by omar-dulaimi** [comment]
Well, after cloning and inspecting Apollo client, graphql-js, graphql-request and finally prisma, I finally started checking the backend as you mentioned. Turns out the culprit was Joi validation library!
Thank you for pointing me in the right direction, and this little experience showed me great code in those aforementioned libraries.
