### ISSUE TITLE
useBaseQuery - non-reactive useEffect  dependencies?

### ISSUE THREAD

**Issue by AjaxSolutions** [apollographql/apollo-client#6246]
https://github.com/apollographql/apollo-client/blob/master/src/react/hooks/utils/useBaseQuery.ts#L89

Is this dep list correct?

```
  useEffect(() => queryData.afterExecute({ lazy }), [
    queryResult.loading,
    queryResult.networkStatus,
    queryResult.error,
    queryResult.data,
  ]);

```
https://github.com/facebook/react/issues/16121

"Dependencies should only include values that participate in top-down React data flow. Such as props, state, and what you calculate from them. "

**Comment by AjaxSolutions** [comment]
I'm looking at React code checking deps in `areHookInputsEqual`. I don't see anything here that would favor React state or props. They just use `Object.is` polyfill to compare deps.

https://github.com/facebook/react/blob/e71f5df9c32b3b486bf4efce861834389c395d47/packages/react-dom/src/server/ReactPartialRendererHooks.js#L124

**Comment by hwillson** [comment]
The dependency tracking we have in place is intentional and we would like to keep it as is for now. If you notice any issues caused because of this, definitely let us know. Thanks!
