### ISSUE TITLE
resetStore with predefined value generate a temporary memory leak 

### ISSUE THREAD

**Issue by mortifia** [apollographql/apollo-client#6252]
Does someone knows how to do a resetStore() while keeping a value to avoid this concern when someone logs out ?

logout
``` javascript
  const client = useApolloClient();

  client.onResetStore(()=>{
    client.cache.writeData({ data: { token: "" }  });
  });
  client.resetStore();
  localStorage.removeItem("token");
  return (
    <Redirect to="/sign-in"/>
  );
```
component example
``` javascript
  const {data: {token}} =useQuery(gql`query{token @client}`);
  let home = ""
  if (!token) {
    home = "/sign-in"
  }; 
  return (
    <div id="header">
      <Link to={home} className="hide_a">
        <img src={navlogo} alt="xxxxxx" id="logo"/>
      </Link>
      <Nav1/>
    </div>
  );
```

the error 
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

**Comment by hwillson** [comment]
This doesn't sound like a bug with Apollo Client - would you mind moving this discussion over to [Spectrum](https://spectrum.chat/apollo)? Thanks!

**Comment by mortifia** [comment]
it's moved to spectrum
