### ISSUE TITLE
refetch with same variables but returning different data does return new data, but doesn't update cache

### ISSUE THREAD

**Issue by mschipperheyn** [apollographql/apollo-client#6254]
**Intended outcome:**
I'm refetching data with useQuery using the same variables but the server returning a different (data) data result. The front end is supposed to update the frontend. 

**Actual outcome:**
The new data is correctly retrieved and visible in the network debugger. The refetch also triggers a rerender. However, the data output in the console shows the old data result. This suggests that the cache is not being updated.

**How to reproduce the issue:**
I will create a reproduction scenario soon

**Versions**
@apollo/client: ^3.0.0-beta.45
@apollo/link-batch-http: ^2.0.0-beta.3
@apollo/link-context: ^2.0.0-beta.3
@apollo/link-error: ^2.0.0-beta.3
@apollo/link-retry: ^2.0.0-beta.3
@apollo/link-ws: ^2.0.0-beta.3
@apollo/react-components: ^3.1.5

  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.1/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 81.0.4044.129
    Safari: 13.1

**Comment by hwillson** [comment]
Would you mind trying the latest `@apollo/client` beta? (`3.0.0-beta.46`) A small runnable reproduction would also be great. Thanks!

**Comment by mschipperheyn** [comment]
I have tried it with 46 and it still fails. I will try to focus on a reproduction scenario bc refetch seems to be failing all over the place. I've replaced it with refetchQueries where I could, which works. But any refetch executes the refetch but doesn't seem to update the cache correctly.

**Comment by mschipperheyn** [comment]
@hwillson do you guys have a code sandbox with a basically setup server and client? It would help to do this quickly.

**Comment by dylanwulf** [comment]
I think there's a link to an error template in the [Contributor Guide](https://github.com/apollographql/apollo-client/blob/master/CONTRIBUTING.md#reporting-bugs) (Under `Issues > Reporting Bugs > 3`). I don't know if there's a codesandbox template though.

**Comment by mschipperheyn** [comment]
@hwillson we're still seeing this. One thing we have identified is that if you have an array of multiple queries this issue occurs, but if it's just a single query, it works correctly.

**Comment by mschipperheyn** [comment]
On our side I can report this issue doesn't occur anymore. It was in fact caused by the pagination handler not resetting the array.

**Comment by jcreighton** [comment]
Closing as this appears to be resolved (but if not, happy to re-open!)
