### ISSUE TITLE
useQuery/useLazyQuery data and error are undefined

### ISSUE THREAD

**Issue by samrith-s** [apollographql/apollo-client#6256]
Error returned:
![image](https://user-images.githubusercontent.com/9032162/81393936-73256400-9121-11ea-891f-0f848d0d2e47.png)

Data returned:
![image](https://user-images.githubusercontent.com/9032162/81454184-cdf3a580-918b-11ea-81fe-d2651d574ba9.png)

**Intended outcome:**

When the query returns an error or data the destructed `error` or `data` variable should contain a value.

**Actual outcome:**

The `error`/`data` variable is `undefined`.

**How to reproduce the issue:**

```ts
import { useQuery } from '@apollo/client'; // can also alternatively import useLazyQuery. Result is the same

const { data, error, loading } = useQuery(HELLO_WORLD);

// When there is an error
console.log(error); // undefined

// When there is data
console.log(data) // undefined
```

**Versions**

System:
- OS: macOS Mojave 10.14.5

Binaries:
- Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
- Yarn: 1.22.4 - ~/Work/troup/client/node_modules/.bin/yarn
- npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm

Browsers:
- Edge: 81.0.416.68
- Safari: 12.1.1

npmPackages:
- @apollo/client: ^3.0.0-beta.46 => 3.0.0-beta.46
- apollo: ^2.27.3 => 2.27.3
- apollo-client: ^2.6.8 => 2.6.8
- react-apollo: ^3.1.5 => 3.1.5

**Comment by hwillson** [comment]
Would you mind providing a small runnable reproduction that demonstrates this? Thanks!

**Comment by samrith-s** [comment]
@hwillson I figured out what was causing the issue.

I was using `formatResponse` and `formatError` on my server like so:

```ts
formatRespose: response => {
    const data = Object.values(response.data).pop();
    return {
        ...response,
        data
    }
}

formatError: response => {
    const errors = Object.values(response.errors).pop();
    return {
        ...response,
        error
    }
}
```

This caused Apollo Client to bug out as it expected `response.data.<queryName>` but didn't receive it. Similarly for errors it expected an array. I removed the weird formatters and now it works. :smile: 

Closing this issue now.
