### ISSUE TITLE
Appending Provided URI to localhost:3000

### ISSUE THREAD

**Issue by dmc2015** [apollographql/apollo-client#6266]
**Intended outcome:**
Requests should be made to `http://localhost:5000/graphql`

**Actual outcome:**
Requests are made to http://localhost:3000/localhost:5000/graphql

**How to reproduce the issue:**
https://github.com/dmc2015/graph-front3nd/tree/BadUri
git clone 
git checkout BadUri
yarn install
yarn start
navigate to localhost:3000
Open browser inspector and go to `Network` tab

**Versions**
```
npx: installed 1 in 6.032s

  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 10.15.3 - ~/.nodenv/shims/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nodenv/shims/npm
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 68.0.2
    Safari: 13.0.5
  npmPackages:
    apollo-cache-inmemory: ^1.6.5 => 1.6.6 
    apollo-client: ^2.6.8 => 2.6.9 
    apollo-link-http: ^1.5.17 => 1.5.17 
    react-apollo: ^3.1.5 => 3.1.5 
```

This seems similar to this issue, it looks like ApolloClient has changed since then.
https://github.com/apollographql/apollo-client/issues/3069

Code Snippet:

```
const link = createHttpLink({
  uri: "http:/localhost:5000/graphql"
})

const client = new ApolloClient({
  link,
  cache: new InMemoryCache()
})


ReactDOM.render(
  <ApolloProvider client={client}>
    <App />
  </ApolloProvider>,
  document.getElementById('root')
);
```

**Comment by skinnomecom** [comment]
Just stumbled upon that issue. Not sure if it's just a typo in your provided code snippet but your URI is missing a second`/` after `http:/`

**Comment by dmc2015** [comment]
I fixed the typo and it seems to stop appending the URI. My feeling is it should not append, if it had just passed what I had typed and made the request, the request would of failed and I would have noticed I was missing a `/`. It shouldn't mutate the value I give it.

**Comment by hwillson** [comment]
Thanks for reporting this, but this doesn't appear to be an issue with Apollo Client itself. If you think this is still a problem, and can provide a small runnable reproduction that shows this, we'll take an another look.
