### ISSUE TITLE
Apollo client local state doesn't trigger resolvers

### ISSUE THREAD

**Issue by velidan** [apollographql/apollo-client#6268]
Hi everyone. I'm working on the Apollo local state (frontend client. React).
I found that Apollo doesn't trigger local resolvers. They just aren't used. I read the official doc more than 4 times, asked on stack, etc. but didn't find any answer.
Maybe someone has some idea why it happens and how it can be resolved?

Apollo client Version: 2.7

Here is my setup: (The Member resolvers for **isLogged** and **name** never trigger)

Apollo client.

```
import { ApolloClient } from 'apollo-client'
import { InMemoryCache } from 'apollo-cache-inmemory'
import { HttpLink } from 'apollo-link-http'
import fetch from 'isomorphic-unfetch'

import { resolvers, typeDefs } from './resolvers';
import { initCache } from './init-cache';

export default function createApolloClient(initialState, ctx) {
  // The `ctx` (NextPageContext) will only be present on the server.
  // use it to extract auth headers (ctx.req) or similar.
  return new ApolloClient({
    ssrMode: Boolean(ctx),
    link: new HttpLink({
      uri: 'https://api.graph.cool/simple/v1/cixmkt2ul01q00122mksg82pn', // Server URL (must be absolute)
      credentials: 'include', // Additional fetch() options like `credentials` or `headers`
      fetch,
    }),
    typeDefs,
    resolvers,
    connectToDevTools: true,
    cache: initCache({
        robot: {
        __typename: 'Robot',
         name: 'Robbie',
         status: 'live',
       },

       member: {
          __typename: 'Member',
          name: 'John',
         isLogged: false
       }
     }),
  })
}

```

Resolvers:

```
import gql from 'graphql-tag';

export const typeDefs = gql`
  type Robot {
    name: String!
    status: String!
  }

  type Member {
    name: String!
    isLogged: Boolean!
  }

`;

export const resolvers = {
  Member: {
    isLogged: (...args) => {
      console.log('args', args); // NEVER TRIGGERS SOMEHOW
      return true;
    },
    name: (...args) => {
      console.log('name args', args); // NEVER TRIGGERS SOMEHOW
      return 'New John';
    },
  }
};
```

Query

```
import * as React from 'react';
import { Text, View } from 'react-native';

import { withApollo } from 'apollo';
import { useQuery } from '@apollo/react-hooks';
import gql from 'graphql-tag';

const GET_ROBOT = gql`
  query getRobot {
    robot @client {
      name
      status
    }
  }
`;

const GET_IS_MEMBER_LOGGED = gql`
  query isMemberLogged {
    member @client(always:true) {
      name
      isLogged
    }
  }
`;
const Alternate = () => { 
  const querRes = useQuery(GET_IS_MEMBER_LOGGED)

  console.log('----------- queryRes =>> ', querRes); // Triggers
  return (
  <View style={styles.container}>


  <Text>{String(querRes?.data?.member?.isLogged)}</Text>

  </View>
) };


export default withApollo()(Alternate);

```

So is it possible to use an initial Cache value and local fields resolver for this object?

Thanks for any help or suggestion, or a doc link!

**Comment by hwillson** [comment]
Would you mind creating a small runnable reproduction that demonstrates this? There are parts of your code sample that are missing, so it's difficult to fully see what's happening. Thanks!

**Comment by velidan** [comment]
Hi @hwillson. Thank you for your attention. I found a possible workaround. Here is the explanation, maybe it will be useful for others.

In short: Use  **@client(always: true)** for a field that you'd like to use resolver for.

**The *in deep* explanation**

In general, there is a problem with how the Apollo client works with Cache.
By default, it caches the response, and next time it'll fetch the cached result from the cache (eg. [optimistic UI][1]). This behavior is the same even in the case of the Client.
<br />
<br />
It means when we have the initial model in cache Apollo will fetch in from the cache and ignores the resolvers, even if we pass the @client directive.
To solve this problem and let Apollo know that we need to use Local resolvers EVEN if we have a cached object, we need to use **@client(always: true)** for the preferred field or the whole object. I made an example below.
<br />
<br />
P.S. Unfortunately I didn't find how to force Apollo to work with non-existing field so if we want to have some resolver for a specific field, we still need to define the initial field value it the initial Cached Model to let the Apollo know about this field. After that, Apollo will use resolver for it to generate some high-calculated output for this particular field, thanks to **@client(always: true)**. <br />
In general, it's ok, because we should know what kind of dynamic field we'll have in our model.


Apollo client

```
    import { ApolloClient } from 'apollo-client'
    import { InMemoryCache } from 'apollo-cache-inmemory'
    import { HttpLink } from 'apollo-link-http'
    import fetch from 'isomorphic-unfetch'
    
    import { resolvers, typeDefs } from './resolvers';
    import { initCache } from './init-cache';
    
    export default function createApolloClient(initialState, ctx) {
      // The `ctx` (NextPageContext) will only be present on the server.
      // use it to extract auth headers (ctx.req) or similar.
      return new ApolloClient({
        ssrMode: Boolean(ctx),
        link: new HttpLink({
          uri: 'https://api.graph.cool/simple/v1/cixmkt2ul01q00122mksg82pn', // Server URL (must be absolute)
          credentials: 'include', // Additional fetch() options like `credentials` or `headers`
          fetch,
        }),
        typeDefs,
        resolvers,
        connectToDevTools: true,
        cache: initCache({
                         author: {
                         __typename: 'Author',
                         posts: 0,
                         name: '' // NEED TO SET AN INITIAL VALUE
                         }
         })
      }
```

Types & resolvers (resolvers.js)

```
    import gql from 'graphql-tag';
    import { print  } from 'graphql';
    
    export const typeDefs = gql`
      type Author {
        posts: Int!
        name: String
      }
    
    `;
    
    
    export const resolvers = {
      Author: {
        name(author) {
          console.log('Author name resolver', author). // WORKS
          return 'NAME';
        },
      },
    
    };

```

Query

```
    const GET_AUTHOR = gql`
      query getAuthor {
        author {
          posts
          name @client(always: true)
        }
      }
    `;

```

  [1]: https://www.apollographql.com/docs/react/performance/optimistic-ui/
