### ISSUE TITLE
Will not update graphql to 15 in apollo-client 3 RC？

### ISSUE THREAD

**Issue by zwl1619** [apollographql/apollo-client#6269]
Now graphql is 14.6.0 .
Will not update graphql to 15 in apollo-client 3 RC？

**Comment by GuptaSiddhant** [comment]
So will v3 have graphql 15 or not?

**Comment by hwillson** [comment]
@GuptaSiddhant it will! If someone wants to submit a PR to update it, that would really help speed things up.
