### ISSUE TITLE
[apollo-client] 2.6.9 different bundle

### ISSUE THREAD

**Issue by morrys** [apollographql/apollo-client#6272]
Hi all,
I wanted to report that with version 2.6.9 a different bundle structure was released on npm.

This results in a breaking change when internal APIs are used.

| bundle 2.6.9  | bundle 2.6.8 | 
| ------------- | ------------- |
![immagine](https://user-images.githubusercontent.com/2670647/81808246-b9af0000-951f-11ea-891e-6cfb91b92966.png) | ![immagine](https://user-images.githubusercontent.com/2670647/81808332-d814fb80-951f-11ea-8358-74a3b46b86da.png)

**Comment by benjamn** [comment]
@hwillson Any idea what might be up with this?

**Comment by KristenLeach** [comment]
I'm experiencing the same breaking change with this update, following here for more info.

**Comment by hwillson** [comment]
Interesting - it looks like the `apollo-client` prep script (`./scripts/deploy.sh`) didn't fire as part of the Lerna deploy process. I'll dig in - thanks!

**Comment by morrys** [comment]
@hwillson I think the cause is the absence of the property "private": true,
in the [package.json of apollo-client](https://github.com/apollographql/apollo-client/blob/release-2.x/packages/apollo-client/package.json) 

This avoids running the lerna publish and allows the [deploy.sh script to run correctly](https://github.com/apollographql/apollo-client/blob/release-2.x/package.json#L19)

**Comment by hwillson** [comment]
Ahhh great catch @morrys - that makes sense! We removed it in https://github.com/apollographql/apollo-client/commit/b73b380655d8118f91596e15e11361781a834a5e#diff-ba5107ed2a3d01d496471a867baf8207 to fix Github's "Used by" counter. Fix coming momentarily - thanks!

**Comment by hwillson** [comment]
This should now be fixed in `apollo-client@2.6.10` (and I'm really glad we've moved away from AC 2.x's build/deploy approach in `@apollo/client`).
