### ISSUE TITLE
SSR: Missing cache result fields for fields with @client directives

### ISSUE THREAD

**Issue by nathanschwarz** [apollographql/apollo-client#6273]
Hello there,

since `@apollo/client@3.0.0-beta.44` all the `@client` directives on fields throw a `MissingFieldError` when trying to render on the server (using `@apollo/react-ssr@4.0.0-beta.1`)

When downgrading to `@apollo/client@3.0.0-beta.41` it works as usual.

Does `@apollo/client@3.0.0-beta.44` introduced a breaking change on the way it handles `@client ` directives ?

**Comment by vincicat** [comment]
After some digging, I found the source: devs removed `@client` directive without saying it in migration guide.

See PR #5982 for detail.

**Comment by hwillson** [comment]
We did remove the option to pass `@client` directives into the link chain, which is documented in the [link section of the Migration Guide](https://www.apollographql.com/docs/react/v3.0-beta/migrating/apollo-client-3-migration/#apollo-link-). It isn't clear though if that is the issue being originally reported here? @nathanschwarz if this isn't your problem, could you provide more details, such as a small runnable reproduction? Closing for now, but happy to re-open if this issue isn't resolved.

**Comment by nathanschwarz** [comment]
It seems that the bug was removed with `@apollo/client@3.0.0-beta.50`.

Anyway, I wasn't using the old `apollo-link-state` API, but the one in the core (just to clarify, I can guess that `apollo-link-state` is still implemented in the core). It seems that `@client` directives were sent to server anyway even with local resolvers setup.

Thanks anyway !
