### ISSUE TITLE
ExecutionResult Type Error still on Tag 3.0.0-beta.48

### ISSUE THREAD

**Issue by BrickCarvingArtist** [apollographql/apollo-client#6277]
On tag 3.0.0-beta.48
Would you please change code in file `/src/core/QueryInfo.ts` to code below?

on line 2 to change
```typescript
import { DocumentNode, GraphQLError } from 'graphql';
```

line 10 to add
```typescript
import { FetchResult } from '../../client/link/core/types';
```

and `function markResult()` to change to like
```typescript
function markResult<T>(result: FetchResult<T>, ...) {}
```

**Intended outcome:**
Do not throw type error.

**Actual outcome:**
Throw type error.

**How to reproduce the issue:**
Just compiled by typescript.

**Versions**
System:
    OS: macOS 10.15.4
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4143.2
    Safari: 13.1
  npmPackages:
    @apollo/client: ^3.0.0-beta.48 => 3.0.0-beta.48 

@benjamn

**Comment by benjamn** [comment]
@BrickCarvingArtist Any chance you might have time to submit a pull request? 🙏

**Comment by durchanek** [comment]
Ran into this as well after upgrading to graphql@15.0.0
