### ISSUE TITLE
client.stop is not the way to prevent "reset store when query is in flight error"

### ISSUE THREAD

**Issue by mschipperheyn** [apollographql/apollo-client#6281]
This is probably a documentation issue or might be considered an edge case.
When you reset the cache, you often get the error: 
```
Store reset while query was in flight (not completed in link chain)
```
My solution was to call `client.stop()` before resetting the store. However, after that, the local cache doesn't work anymore. It probably requires a full client recreation? Or is this considered a bug. 

**Intended outcome:**

The pattern to correctly reset the store should be clear.

**Actual outcome:**

It's not clear how to reset the store and avoid the error. 

**How to reproduce the issue:**

I've created an example that reproduces the various cases.

https://codesandbox.io/s/quirky-haslett-db3vj?file=/src/index.js

**Versions**
@apollo/client 3.0.0-beta.48

  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.1/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Safari: 13.1

**Comment by hwillson** [comment]
Thanks for the reproduction @mschipperheyn. `ApolloClient.stop()` is intended to be called just before destroying the client instance, which explains why the cache stops working. Although this method is public, you shouldn't really ever have to call it yourself (it's more for libraries that integrate with Apollo Client that need a way to ensure the `QueryManager` has been stopped). If you're using `stop` then yes you'll likely have to reinstantiate the client instance.

That being said, the `Store reset while query was in flight (not completed in link chain)` can definitely be annoying to deal with. We'll put some thought into a way to improve this.

**Comment by hinok** [comment]
It's especially problematic in case when you want to log out users and clear cache but at the same time redirect them to a page that run some queries.

I made also very simple demo: https://codesandbox.io/s/react-apollo-with-hooks-n6nby?file=/src/index.js (Click `Log out John`).

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!

**Comment by hinok** [comment]
@hwillson 
I upgraded to latest packages and use only hooks and it seems that it works fine 🥳

https://codesandbox.io/s/react-apollo-with-hooks-forked-jmdlt?file=/src/index.js

**Comment by brainkim** [comment]
@hinok glad to hear!

**Comment by thomasttvo** [comment]
Found this thread after spending so many hours digging. The error message in the title wasn't correct, so google couldn't pick up. The actual error is "Store reset when query is in flight". Therefore, I'm adding this comment in hope of making this thread SEO friendly.
