### ISSUE TITLE
Documentation Structure

### ISSUE THREAD

**Issue by samirelanduk** [apollographql/apollo-client#6292]
I think some of the text on the [main page of the documentation](https://www.apollographql.com/docs/react/#explore-apollo-client) is out of date. It says that the documentation is split into five sections (Essentials, Features, Advanced, Recipes, API), but this does not seem to be the case at all.

Related to this, the [last section of the tutorial (section 9)](https://www.apollographql.com/docs/tutorial/local-state/) says 'In the final section, we're going to recap what we just learned and give you guidance on what you should learn next' - but then there's no final section - the tutorial ends there.

Seems like the documentation structure got updated at some point in the past, but one or two references to the old structure slipped through the update.

**Comment by hwillson** [comment]
Thanks @samirelanduk - the docs are definitely out to date in parts. We're working on the Apollo Client 3 docs right now, and are combing through every page of the docs carefully. We'll have the new docs up shortly.
