### ISSUE TITLE
Improving the local state management: @export directive on server side fields or accessing grandparent values in local resolvers

### ISSUE THREAD

**Issue by darkbasic** [apollographql/apollo-client#6293]
**Disclaimer**: this is against the GraphQL specification, but since it's going to be used in client resolvers it shouldn't be a big deal, especially when coupled with `always: true` which forces local resolvers to re-run on every request.

First, let me illustrate my use case:

```gql
{
  query match(matchId: $matchId) {
    id
    chat {
      id @export(as: "chatId")
      members {
        id
      }
      messages {
        id
        sender {
          id
        }
        color(chatId: $chatId) @client
      }
    }
  }
}
```

```gql
{
  query messages(chatId: $chatId) {
  id
  sender {
    id
  }
  color(chatId: $chatId) @client
}
```

For both queries I want to assign a fixed color to each chat member, so that I can use it when I display the message's sender in the UI.

Basically for each chat the color is something like this:
```ts
const memberIndex = chat.members.findIndex(member => member.id === message.sender.id);
return colors[memberIndex % colors.length];
```

Doing so for the second query is quite simple, because I can use the `chatId` arg to read a `Chat` fragment and retrieve everything I need.

The first query is more difficult, because I cannot really use the `@export` directive on a server side field to retrieve the `chatId` argument, so `color(chatId: $chatId) @client` gets no args.

**Is it something we want to implement?** When applied to server side fields the `@export` directive will have to be stripped out of course, then the execution of `color(chatId: $chatId) @client` will have to be delayed until the server returns.

Another solution would be to access the color field grandparent: `Chat`. This is currently not possible and goes against the specs, but shouldn't be a big deal for a client side resolver.

**Is it something we want to implement?** Accessing the whole query hierarchy would be very usefeul for client side resolvers. Basically something like the `info` parameter, but including the values the fields got resolved to.

Back with my feets on the ground, I started to think about an easier solution which would allow me to achieve this functionality without having to wait for those features to be implemented. I could add a `chat: Chat!` field to `Message` in order to retrieve the `chatId`. This is suboptimal because it increases the bandwidth consumption, but it's just an id and it could be useful to have it in the cache anyway:

```gql
{
  query match(matchId: $matchId) {
    id
    chat {
      id
      members {
        id
      }
      messages {
        id
        sender {
          id
        }
        chat {
          id
        }
        color @client
      }
    }
  }
}
```

Now in the local resolver it should be just a matter of retrieving a `Chat` fragment with all the members, right?

```ts
const chat = cache.readFragment({
  id: message.chat.id,
  fragment: gql`
    fragment ChatWithMembers on Chat {
      id
      members {
        id
      }
    }`,
});
```

Unfortunately not, because when the local resolver gets executed the chat has still not be written to the cache and so `undefined` gets returned. It would be really nice to have a way to delay the execution of specific local resolvers, something like `@client(afterCaching: true)`.

**Is it something we want to implement?** In alternative, another way to query soon-to-be-cached fragments.

So how to actually implement this with the tools we have right now? I don't like the answer:

```gql
{
  query match(matchId: $matchId) {
    id
    chat {
      id
      members {
        id
      }
      messages {
        id
        sender {
          id
        }
        chat {
          id
          members {
            id
          }
        }
        color @client
      }
    }
  }
}
```

The only solution I've came up with is adding yet-another-field to each of my messages, but this time is an array: `members`. This allows me to directly access the chat members without having to query the cache, but it adds a **lot** of weight to the network for no reason at all.

I would like to use this issue to think of ways to improve the local state management to a point where it's actually desirable to use it compared to third party solutions. Maybe I'm doing something wrong or I didn't think of some trivial solution, but currently it feels quite cumbersome.

**Comment by hwillson** [comment]
Thanks for the feature request @darkbasic. I'm going to convert this to a discussion (we're trialing GH's beta discussions feature).
