### ISSUE TITLE
Error while testing with @apollo/client/testing

### ISSUE THREAD

**Issue by timosg** [apollographql/apollo-client#6299]
After upgrading my Project from apollo-client to @apollo/client my tests aren't working.
the first error `SyntaxError: Unexpected token 'export'` seems to be a babel problem, but if i add `@apollo/client` to my transformIgnorePatterns, i get a TypeError (see Actual outcome).

**Intended outcome:**

Test Success

**Actual outcome:**

```
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { ApolloProvider } from './context/ApolloProvider';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token 'export'
```
or
```
    TypeError: Object prototype may only be an Object or null: undefined
        at setPrototypeOf (<anonymous>)
```

**How to reproduce the issue:**

Updating from 2.x to 3 - But it seems to be a individual case for me
**Versions**

    "@apollo/client": "^3.0.0-beta.48",
    "@apollo/link-context": "^2.0.0-beta.3",
    "@apollo/link-ws": "^2.0.0-beta.3",

**Comment by hwillson** [comment]
@TimoGruber any chance you could share a small runnable reproduction that demonstrates this?

**Comment by nikitalarionov** [comment]
> After upgrading my Project from apollo-client to @apollo/client my tests aren't working.
> the first error `SyntaxError: Unexpected token 'export'` seems to be a babel problem, but if i add `@apollo/client` to my transformIgnorePatterns, i get a TypeError (see Actual outcome).
> 
> **Intended outcome:**
> 
> Test Success
> 
> **Actual outcome:**
> 
> ```
>     ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { ApolloProvider } from './context/ApolloProvider';
>                                                                                              ^^^^^^
> 
>     SyntaxError: Unexpected token 'export'
> ```
> 
> or
> 
> ```
>     TypeError: Object prototype may only be an Object or null: undefined
>         at setPrototypeOf (<anonymous>)
> ```
> 
> **How to reproduce the issue:**
> 
> Updating from 2.x to 3 - But it seems to be a individual case for me
> **Versions**
> 
> ```
> "@apollo/client": "^3.0.0-beta.48",
> "@apollo/link-context": "^2.0.0-beta.3",
> "@apollo/link-ws": "^2.0.0-beta.3",
> ```

Have this problem too, do you solved it?

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
