### ISSUE TITLE
useQuery returns incorrect data after variables change

### ISSUE THREAD

**Issue by vishwam** [apollographql/apollo-client#6300]
**Intended outcome:**

When the variable of a query changes and the client doesn't have the new results already cached (i.e., while the request is loading), the data field should not be populated with the previous variable's results.

**Actual outcome:**

When the variable changes, useQuery initially returns `loading: true` with the previous variable's data. Once the network call finishes, it returns with `loading: false` and the correct data.

**How to reproduce the issue:**

See [example codesandbox based on the bug template here](https://codesandbox.io/s/boring-hooks-zzjt3?file=/src/App.js): when the page initially loads, I exclude the name field from the people list and the component is rendered with `{showName: false, loading: false, data: {...}}` (see console log.)

When the button is clicked, I change the query variables to include the name field. At this point, the component is re-rendered with `showName: true, loading: true` **and the old data** (even though I've set `returnPartialData: false`).

In a more real-world example, I have a page that shows an item list and a detail view side-by-side. When I switch from one item to another, the list re-renders with the new selection but the details page still shows the old item, which is a bad user experience.

**Versions**

@apollo/client 3.0.0-beta.48

**Comment by benjamn** [comment]
This problem was recently fixed by #6566 (`rc.12`). Totally agree with your assessment, by the way!

**Comment by macrozone** [comment]
@benjamn is ist possible to somehow restore the old behaviour? AC2 behaved like that, but this is now a breaking change, but is not documented as such
