### ISSUE TITLE
Fields are not nullable in local state (or the query will return undefined)

### ISSUE THREAD

**Issue by olivierpascal** [apollographql/apollo-client#6308]
Version: ac@3 (but it was the same with ac@2)

Reproductible example: https://github.com/apollographql/ac3-state-management-examples/tree/master/apollo-local-state/

This example works well.
Now, edit: `/src/operations/queries/getAllTodos.tsx`

```js
export const GET_ALL_TODOS = gql`
  query GetAllTodos {
    todos @client {
      id
      text
      completed
      nonExistingField # < add this
    }
  }
`;
```

Now the query return undefined. It means that the query should *exactly* match the underlying data. No field is nullable. Which makes using local state in real life very hard.

**Comment by olivierpascal** [comment]
Same that https://github.com/apollographql/apollo-client/issues/5253

**Comment by hwillson** [comment]
@olivierpascal The issue is you're asking for a field that doesn't exist in your schema. This usually points to an error in your code, so it's an error as far as Apollo Client is concerned (by default). If you want to work around this though, `useQuery` supports an option called `returnPartialData` that will let you ignore this problem. You would call it like:

```js
const todosQueryResult = useQuery(GET_ALL_TODOS, { returnPartialData: true });
```

**Comment by olivierpascal** [comment]
So, the "schema" is, in fact, the initial data format provided to the cache.

I would have expected that the `typeDefs` property of the `ApolloClient` constructor was the local schema definition. The following definition does not allow the query to run, even if `nonExistingField` exists in the schema (and is nullable).

Also, in any case, the returned data is just `undefined` and no error is reported by `useQuery`.

```js
export const client = new ApolloClient({
  cache,
  connectToDevTools: true,
  typeDefs: gql`
    type Todo {
      id: String
      text: String
      completed: Boolean
      nonExistingField: String
    }

    type Query {
      todos: [Todo!]
    }
  `,
});
```
