### ISSUE TITLE
[AC3] Apollo client immutability is inconsistent with Redux like immutability

### ISSUE THREAD

**Issue by ashubham** [apollographql/apollo-client#6310]
**Intended outcome:**

Suppose Cache contains:
```
"Typename:<id>": {
   key1: { ...some nested object1 },
   key2: { ...some nested objec2 }
}
```

If a mutation occurs and changes something inside `key2`, a redux like immutability will gurarantee:

```
"Typename:<id>": {
   key1: { ...same obect reference as before }, // This is still the same reference.
   key2: { ...some nested objec3 } // Only this will be recreated.
}
```

**Actual outcome:**

The thing is that it still might be the case for the storage layer on Apollo cache, but when we retrieve this data using `useQuery` it returns a new copy of results, because the `selectionSets` are re-executed.

```
"Typename:<id>": {
   key1: { ...copy of object1 }, // This is a new reference. (unexpected)
   key2: { ...some nested objec3 } // This will be recreated (expected)
}
```

**Versions**

Apollo Client: 3.0.0-beta.48

**Comment by benjamn** [comment]
Can we keep this discussion in #6249? I know I owe you an answer over there, but I'm also pretty sure the answer will cover this issue as well.
