### ISSUE TITLE
fragment which has `__typename` only is removed by `removeClientSetsFromDocument`

### ISSUE THREAD

**Issue by mtsmfm** [apollographql/apollo-client#6311]
**Intended outcome:**

The following code which works in v2 should not throw an error in v3:

```type
client.query({
  query: gql`
    query {
      gameStatus(gameId: "gcn811f") {
        maze {
          cells {
            ...CellFragment
          }
        }
      }
    }

    fragment CellFragment on Cell {
      __typename
    }
  `
});
```

**Actual outcome:**

The above code throws an error `Validation error of type UndefinedFragment: Undefined fragment CellFragment @ 'gameStatus/maze/cells'` because the CellFragment only contains __typename

https://github.com/apollographql/apollo-client/blob/61a799b2cd5e1657eab4ea97485828671ce35286/src/utilities/graphql/transform.ts#L503

**How to reproduce the issue:**

https://codesandbox.io/s/apollo-3-fragment-bug-yf8f7?file=/src/index.ts
https://codesandbox.io/s/apollo-2-with-fragment-lfe8e?file=/src/index.ts

**Versions**

@apollo/client 3.0.0-beta.49

**Comment by LaureRC** [comment]
@hwillson any updates on this?

**Comment by chris110408** [comment]
I will take a look at it

**Comment by Emmanuel-Melon** [comment]
@chris110408 any updates?

**Comment by kevinbgreene** [comment]
@hwillson did this get lost or a "won't fix"? No movement here or PR.

**Comment by chris110408** [comment]
Sorry I was totally forget this. any one please feel free to take over this ticket

**Comment by kevinbgreene** [comment]
Thanks for the quick reply @chris110408. We'll get something together.
