### ISSUE TITLE
MockedProvider does not populate fields if a fragment is being used

### ISSUE THREAD

**Issue by strongpauly** [apollographql/apollo-client#6318]
**Intended outcome:**

Mocking a result for a query which contains a fragment should pass through the values defined in the mock result.

**Actual outcome:**

The query is successfully mocked, but each of the objects returned by the hook is empty.

**How to reproduce the issue:**

See example in: [https://github.com/strongpauly/apollo-bug](https://github.com/strongpauly/apollo-bug)

Running the below will show a broken test:

`yarn && yarn test`

(Apologies for not using the template, only found it after I had created my own repo).

**Versions**

```
  System:
    OS: macOS 10.15.3
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Edge: 81.0.416.77
    Firefox: 72.0.2
    Safari: 13.0.5
  npmPackages:
    @apollo/client: ^3.0.0-beta.49 => 3.0.0-beta.49
    @apollo/react-testing: ^3.1.4 => 3.1.4
```

**Comment by hwillson** [comment]
@strongpauly Thanks for providing a reproduction! The problem is that your mocked data uses a `__typename` of `Rate`, but your fragment is defined on `Rates`. If you change your fragment to

```graphql
fragment someFields on Rate {
  currency
  rate
}
```

everything will work properly.

**Comment by strongpauly** [comment]
This works!  Thank you!
