### ISSUE TITLE
Dead link in documentation

### ISSUE THREAD

**Issue by SuliacLEGUILLOU** [apollographql/apollo-client#6321]
I am not going to follow the template as my issue seems pretty simple:

On the [react-native integration documentation page](https://www.apollographql.com/docs/react/integrations/react-native/), the two application examples provided are dead link

**Comment by kingisaac95** [comment]
@hwillson this looks like a quick fix.

The links `"Hello World" example` and `GitHub API Example` are currently pointing to 404 pages.

Can I take this as my first issue?

**Comment by vinhnglx** [comment]
So, is there any react-native example?

**Comment by SuliacLEGUILLOU** [comment]
Well, links are gonne now, so it's technically solved
