### ISSUE TITLE
useQuery() swallows last error in error-success-error sequence since previousData.error is not reset on a success

### ISSUE THREAD

**Issue by dko-slapdash** [apollographql/apollo-client#6330]
Hi.

I noticed that useQuery() hook sometimes swallows error if this error is **exactly equal** to the error happened somewhere in the past, even though there were successful responses in between.

TL;DR: in the sequence of (A) failure + (B) success + (C) failure, step B doesn't reset error state in previousData.error. So step (C) becomes a no-op and doesn't trigger a hook re-render.

Imagine the follow sequence:
1. useQuery(SOME_QUERY), and it fails (e.g. "user is not authenticated" error);
2. the user logs in (for instance, just as an illustration of an error example);
3. we call reFetchObservableQueries();
4. useQuery(SOME_QUERY) succeeds; 
5. the user logs OUT;
6. we call reFetchObservableQueries() again;
7. useQuery(SOME_QUERY) expects to fail at this point (i.e. return error), but it SUCCEEDS - this is unexpected.

The cause of this is following: (3+4) do not reset previousData.error, although it's a successful response. I looked at this code:

https://github.com/apollographql/apollo-client/blob/19b7ad5245f9011b05509d4b8ad9423f378915ac/src/react/data/QueryData.ts#L295-L306

and noticed that L305 is basically the only place when previousData.error is reassigned. There is no reassignment in the success branch. And thus, next time an error happens, we have BOTH previousData.error and previousData.result set (although we should've had only previousData.result set and previousData.error being empty).

![image](https://user-images.githubusercontent.com/46383452/82608213-17ba9380-9b6f-11ea-924d-929aed59ce1c.png)

**Comment by hwillson** [comment]
@dko-slapdash any chance you could put together a small runnable reproduction for this?

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
