### ISSUE TITLE
AC3: Behavior differences between ApolloClient.write* and ApolloCache.write* (Seen in Apollo Client Dev Tools)

### ISSUE THREAD

**Issue by jamshally** [apollographql/apollo-client#6331]
**Context**
When viewing cache items using [Apollo Client Dev Tools](https://chrome.google.com/webstore/detail/apollo-client-developer-t/jdkknkkbebbapilgoeccciglkfbmbnfm): 

- **ApolloClient**.writeFragment updates are immediately reflected in Apollo Client Dev Tools
- **ApolloCache**.writeFragment updates are not immediately reflected in Apollo Client Dev Tools

**Intended outcome:**
- Primarily: for ApolloCache.write* and the ApolloClient.write* to behave the same (or to understand when/why they don't)
- Ideally: for ApolloCache.write updates to be reflected in Apollo Client Dev Tools

**How to reproduce the issue:**
A recreation of the described behavior can be seen in this [react-apollo-error-template](https://github.com/ahrnee/react-apollo-error-template/tree/client_cache_write_differences)

![ApolloDevToolsIssueB](https://user-images.githubusercontent.com/39815557/82617618-81b35700-9bc8-11ea-8843-a8db537b5000.gif)

**Notes**
This is less about the Apollo Chrome Dev Tools, and more about having confidence in the cache update mechanism, and knowing how to use it. That being said, it would be nice if the Cache.write* method updates were visible in the Dev Tooling

**Versions**
  System:
    OS: macOS 10.15.4
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Safari: 13.1
  npmPackages:
    @apollo/client: 3.0.0-beta.50 => 3.0.0-beta.50

**Comment by benjamn** [comment]
Thanks for surfacing this issue. In AC3, both client and cache update methods will broadcast by default, but the cache APIs all support silencing the broadcast if that's the preferred behavior: #6288. Although that's not exactly the same as the old behavior, hopefully it addresses your needs?

Closing since this change was intentional, but happy to continue the discussion.
