### ISSUE TITLE
type WebSocketLink is invalid on split() junction

### ISSUE THREAD

**Issue by IljaDaderko** [apollographql/apollo-client#6333]
**Intended outcome:**

Per documentation, we need to use `splitLink` approach in order to have http and websocket links: https://www.apollographql.com/docs/react/v3.0-beta/data/subscriptions/#3-use-different-transports-for-different-operations 

In following setup, when passing `wsLink` to `split` function a type error is thrown

> Argument of type 'WebSocketLink' is not assignable to parameter of type 'ApolloLink | RequestHandler'.
>   Type 'WebSocketLink' is not assignable to type 'ApolloLink'.
>     Types of property 'split' are incompatible.

```ts
import { ApolloClient, HttpLink, InMemoryCache, split } from '@apollo/client';
import { getMainDefinition } from '@apollo/client/utilities';
import { WebSocketLink } from '@apollo/link-ws';

const GRAPHQL_URL = 'myApp.dev/v1/graphql';

const httpLink = new HttpLink({
  uri: `https://${GRAPHQL_URL}`
});

const wsLink = new WebSocketLink({
  uri: `ws://${GRAPHQL_URL}`
});

const splitLink = split(
  ({ query }) => {
    const definition = getMainDefinition(query);

    return (
      definition.kind === 'OperationDefinition' && definition.operation === 'subscription'
    );
  },
  wsLink, // Invalid type
  httpLink
);

const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: splitLink
});
```

**How to reproduce the issue:**

Follow set up instructions here https://www.apollographql.com/docs/react/v3.0-beta/data/subscriptions/#3-use-different-transports-for-different-operations

**Versions**

```
System:
    OS: macOS 10.15.4
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Safari: 13.1

```

```json
{
    "@apollo/client": "3.0.0-beta.49",
    "@apollo/link-ws": "2.0.0-beta.3",
    "subscriptions-transport-ws": "0.9.16",
    "graphql": "15.0.0",
}
```

**Comment by tsaiDavid** [comment]
@hwillson @IljaDaderko - we were seeing this with `@apollo/client` on `3.0.0-beta.50`, after upgrading to `3.0.0-rc.0` we still saw the same error upon building for production, but were able to "fix" the issue by adding the following to our `package.json` as a hopefully temporary fix (@dmi3y):

```
  "resolutions": {
    "@apollo/client": "3.0.0-rc.0"
  },
```

**Comment by eDubrovsky** [comment]
I have the same error with `"@apollo/client": "3.0.0-rc.2"`

**Comment by kale5in** [comment]
`"@apollo/client": "^3.0.0-rc.5",` - Fixed this error.

**Comment by IljaDaderko** [comment]
@kale5in I still see this error while using `concat` and `from` methods on rc5

<img width="790" alt="Screenshot 2020-06-17 at 12 57 13" src="https://user-images.githubusercontent.com/3154053/84884212-190dac00-b09a-11ea-884a-f0e11d5badd6.png">

**Comment by hwillson** [comment]
We're just waiting until https://github.com/apollographql/apollo-client/pull/6577 is in place, before looking into this further.

**Comment by YvanGuidoin** [comment]
Not doing it anymore if you take the Link from the `@apollo/client` package directly.

```
import { WebSocketLink } from "@apollo/client/link/ws";
```

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!

**Comment by anh-tuan98** [comment]
Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at MutationData.push../node_modules/@apollo/client/react/data/MutationData.js.MutationData.onMutationCompleted @@ pls suport

**Comment by brainkim** [comment]
@anh-tuan98 If you open an issue with a reproduction I’m always happy to look at it!

**Comment by anh-tuan98** [comment]
> @anh-tuan98 If you open an issue with a reproduction I’m always happy to look at it!

import {
  ApolloClient,
  HttpLink,
  from,
  split,
  InMemoryCache,
  NormalizedCacheObject,
} from '@apollo/client';
import { getMainDefinition } from '@apollo/client/utilities';
import { RetryLink } from '@apollo/client/link/retry';
import { message, notification } from 'antd';
import { onError } from '@apollo/client/link/error';
import { asyncAuthLink } from './AccountsLink';

interface definition {
  kind: string;
  operation?: string;
}

export const makeApolloClient = () => {
  const httpLink = new HttpLink({
    uri: `https://staging-gateway/graphql`,
    credentials: 'same-origin',
  });

  const retryLink = new RetryLink();

  const link = from([
    asyncAuthLink,
    retryLink,
    split(({ query }) => {
      const { kind, operation }: definition = getMainDefinition(query);
      return kind === 'OperationDefinition' && operation === 'subscription';
    }, httpLink),
  ]);

  const openNotificationWithIcon = (type, title) => {
    notification[type]({
      message: '',
      description: `${title}`,
    });
  };

  const errorLink = onError(({ graphQLErrors, networkError }) => {
    if (graphQLErrors) {
      graphQLErrors.forEach((item: any) =>
        openNotificationWithIcon('error', item.message),
      );
    }
    if (networkError) {
      openNotificationWithIcon('warning', `${networkError}`);
    }
  });

  const cache = new InMemoryCache();

  const client = new ApolloClient({
    link: errorLink.concat(
      link,

    ),
    cache,
  });
  console.log('client', client);
  return client;
};

**Comment by anh-tuan98** [comment]
> @anh-tuan98 If you open an issue with a reproduction I’m always happy to look at it!

sorry bro, my code sitl error when call api
