### ISSUE TITLE
Apollo Client Queries documentation on Inspecting error states appears inaccurate

### ISSUE THREAD

**Issue by jaytula** [apollographql/apollo-client#6343]
**Intended outcome:**

The Apollo Client documentation section on Queries *Inspecting error states*  appears to be inaccurate.

https://github.com/apollographql/apollo-client/blob/version-2.6/docs/source/data/queries.mdx#inspecting-error-states

In particular,  the following sentence:

> In this case, Apollo Client discards any query response data returned by the server and sets the `error` property in the `useQuery` result object to `true`.

The `error` property from `useQuery` is not exactly `true` but a truthy *object*.

```javascript
const { error } = useQuery(SOME_QUERY);
// 'error' is an object
```
**Actual outcome:**

The documentation pictured below appears inaccurate

https://www.apollographql.com/docs/react/data/queries/#inspecting-error-states

![image](https://user-images.githubusercontent.com/75389/82845881-210f6d00-9e9b-11ea-9932-271c4c59ad01.png)

**How to reproduce the issue:**

Just visit the documentation: https://www.apollographql.com/docs/react/data/queries/#inspecting-error-states

**Comment by kingisaac95** [comment]
@hwillson what would we want to have here instead?

I'd love to discuss this and push a fix if possible

**Comment by dexterpuru** [comment]
Hey @jaytula @hwillson, i just made a PR (https://github.com/apollographql/apollo-client/pull/7051), please review it.

**Comment by jpvajda** [comment]
Based on my response to #7051, I'm closing this issue as this page has been updated since this issue was reported.
