### ISSUE TITLE
Error returned by useQuery is `undefined` if server returns `data` as `null`

### ISSUE THREAD

**Issue by samrith-s** [apollographql/apollo-client#6347]
**Intended outcome:**

When the server returns an object like so:
```js
{
  data: null,
  errors: [ /* error data */ ]
}
```
The `error` property returned by `useQuery` should contain the error.

**Actual outcome:**

The `error` property is `undefined`.

**How to reproduce the issue:**

Test with any GraphQL API endpoint that returns an object as described above.

**Versions**

```bash
  System:
    OS: macOS Mojave 10.14.5
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Browsers:
    Edge: 83.0.478.37
    Safari: 12.1.1
  npmPackages:
    apollo-server-express: ^2.12.0 => 2.12.0
```

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
