### ISSUE TITLE
Issue with passing variables in a gql query in angular using apollo-client: Syntax Error: Expected Name, found $

### ISSUE THREAD

**Issue by matthewleonard** [apollographql/apollo-client#6351]
**Intended outcome:**
Use the apollo client in Angular to run a graphQL query while passing in a variable and receive data from the graphQL server.

**Actual outcome:**
The apollo-client throws an error when running a query that passes a variable:

**Query:**
```
const CompanyQuery = gql`
query {
  findCompanyByCocode($cocode: Int!) {
    cocode
    longName
    shortName
    activeStatus
    businessTypeId
    group {
      groupCodeId
      groupName
      status
    }
  }
}
`
```

**Error:**
```
"GraphQLError: Syntax Error: Expected Name, found $
    at syntaxError (http://localhost:4200/vendor.js:105142:10)
    at Parser.expectToken (http://localhost:4200/vendor.js:110124:81)
    at Parser.parseName (http://localhost:4200/vendor.js:108814:22)
    at Parser.parseArgument (http://localhost:4200/vendor.js:109048:21)
    at Parser.optionalMany (http://localhost:4200/vendor.js:110217:28)
    at Parser.parseArguments (http://localhost:4200/vendor.js:109039:17)
    at Parser.parseField (http://localhost:4200/vendor.js:109026:23)
    at Parser.parseSelection (http://localhost:4200/vendor.js:109000:113)
    at Parser.many (http://localhost:4200/vendor.js:110238:26)
    at Parser.parseSelectionSet (http://localhost:4200/vendor.js:108987:24)"
```

**However, I am able to get results without issue when hardcoding the variable like: **

```
const CompanyQuery = gql`
query {
  findCompanyByCocode(cocode: 11111) {
    cocode
    longName
    shortName
    activeStatus
    businessTypeId
    group {
      groupCodeId
      groupName
      status
    }
  }
}
`
```

I have tried a multitude of tutorials and different ways of assigning the variables in Angular with the same issue.

**How to reproduce the issue:**

On a graphQL server define the following in the .graphqls file:

```
type Company {
    cocode: Int!
    longName: String!
    shortName: String!
    activeStatus: String!
    businessTypeId: Int!
    group: Group
}
type Query {
    findCompanyByCocode(cocode: Int!): Company
}
```

On the angular client, declare the gql query and variable assignment in this way:

```
import gql from 'graphql-tag';
import {Apollo} from "apollo-angular";
import {Subscription} from "rxjs";
@Component({
  selector: 'app-report-header',
  templateUrl: './report-header.component.html',
  styleUrls: ['./report-header.component.css']
})
export class ReportHeaderComponent implements OnInit {
  @Input() cocode: number;
  @Input() year: number;
  @Input() statementType: string;
  @Input() period: string;
  shortCompanyName: string;
  fein: string;
  status: string;
  groupCode: number;
  groupName: string;
  date: Date = new Date();
  domicile: string;
  nationallySignificant: string;
  rbcRatio: string;
  rbcYear: number = 2018;
  loading: boolean;
  company: any[];

  private querySubscription: Subscription;
  constructor(private apollo: Apollo) { }

  ngOnInit() {
    const variables = {cocode: this.cocode};
    this.querySubscription = this.apollo.watchQuery<any>({
      query: CompanyQuery,
      variables,
    })
      .valueChanges
      .subscribe(({ data, loading }) => {
        this.loading = loading;
        this.status = data.findCompanyByCocode.activeStatus;
        this.groupName = data.findCompanyByCocode.group.groupName;
        this.groupCode = data.findCompanyByCocode.group.groupCodeId;
        this.shortCompanyName = data.findCompanyByCocode.shortName
        console.log(this.company);
      });
  }
}

const CompanyQuery = gql`
query {
  findCompanyByCocode($cocode: Int!) {
    cocode
    longName
    shortName
    activeStatus
    businessTypeId
    group {
      groupCodeId
      groupName
      status
    }
  }
}
`;
```

**Note that when trying to pass the variable as $cocode: Int! that an error is thrown**
**Note that when passing the variable explicitly as cocode: 11111 that an error is not thrown and data is returned as expected**

**Versions**
System:
    OS: Windows 10 10.0.15063
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Google Chrome: 83.0.4103.61

package.json:
    "apollo-angular": "^1.8.0",
    "apollo-angular-link-http": "^1.9.0",
    "apollo-cache-inmemory": "^1.6.5",
    "apollo-client": "^2.6.8",
    "apollo-link": "^1.2.13",
    "graphql": "^14.6.0",
    "graphql-tag": "^2.10.3",

**Comment by benjamn** [comment]
In your example, `$cocode` is used as an _argument_ for the `findCompanyByCocode` field. Arguments are specific to a certain field, whereas variables are global to an entire query. Arguments 

You probably want something like this instead:
```ts
const CompanyQuery = gql`
  query FindCompany($cocode: Int!) {
    findCompanyByCocode(cocode: $cocode) {
      cocode
      ...
    }
  }
`;
```
To be clear: this is standard GraphQL syntax, not related to Apollo Client specifically. Take some time to understand the difference between [arguments](https://graphql.org/learn/queries/#arguments) and [variables](https://graphql.org/learn/queries/#variables), and I think you'll be a lot less confused, regardless of which GraphQL tools you're using.

**Comment by matthewleonard** [comment]
@benjamn You are correct, that is what I wanted and that resolved the issue. Thank you for your time and sorry that I reported this as an issue instead of realizing it was an ID10T problem. Cheers!
