### ISSUE TITLE
[AC3] useQuery does not respect keyArgs, and returns a deep cloned copy if non-key variables are changed.

### ISSUE THREAD

**Issue by ashubham** [apollographql/apollo-client#6355]
**Intended outcome:**

Multiple calls to `useQuery` for the same Query document should return the same result object if the given `keyArgs` for the query are same.

**Actual outcome:**

Everytime a component calls `useQuery` as a result of a rerender (with different variables but the same `keyArgs` for the Query), it returns a fresh clone of the data.

**How to reproduce the issue:**

Here is a codeSandbox:
https://codesandbox.io/s/usequery-example-apollo-client3-d8sgi

Everytime you click on `Rerender` button, you can see a `changed` log in the console. This is because the `useEffect` reruns.

Type policies are:
```
typePolicies: {
      Query: {
        fields: {
          videos: {
            keyArgs: ["id"]
          }
        }
      }
    }
```

And the useQuery:
```
const { data } = useQuery(GET_VIDEOS, {
    variables: {
      id: 123, // This is fixed
      random: Math.round(Math.random() * 100)
    }
  });
```

**Versions**

Apollo Client: 3.0.0-beta.52

**Comment by benjamn** [comment]
Variables are currently included in the cache keys used by the result caching system, so this is working as expected.

**Comment by hwillson** [comment]
Working as designed (see https://github.com/apollographql/apollo-client/issues/6355#issuecomment-636012209) - thanks!
