### ISSUE TITLE
Observable queries indefinitely stop updating after cache.clearStore()

### ISSUE THREAD

**Issue by emiloberg** [apollographql/apollo-client#6359]
**Intended outcome:**

1. Create an observable query with a `@client` directive which depends on a reactive variable to resolve.
2. Run `client.clearStore()`
3. Update the reactive variable from step 1
4. The observable query should now be re-run and its returning data reflecting what's set in step 3.

Or in other words:

I'm assuming that the `client.clearStore()` call will not broadcast any changes _for the period of the actual clearStore_, but that the observable status of the queries will be resumed once the store is cleared.

I'm unsure if this is a bug or intended behavior.

My use case is that I have a query for if the user is logged in or not, backed by a reactive variable. When the user logs out, I want to clear the entire store (but not make any requests for the active observable queries) and then, after the store is cleared, set the logged in variable to false and that way trigger a React re-render for a top level observable query looking something like `query { isLoggedIn @client }`

**Actual outcome:**

Step 4 will never happen as the `clearStore()` call will indefinitely stop all previously made observable queries from updating.

**How to reproduce the issue:**

An error template is available here:  https://github.com/emiloberg/react-apollo-error-template/tree/master/src

It implements both `clearStore()` and `resetStore()` where the latter will work as intended.

**Versions**

```
  System:
    OS: macOS 10.15.3
  Binaries:
    Node: 12.1.0 - ~/.nvm/versions/node/v12.1.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.1.0/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 60.0.2
    Safari: 13.0.5
  npmPackages:
    @apollo/client: ^3.0.0-beta.50 => 3.0.0-beta.50
```

**Comment by benjamn** [comment]
This is the difference between `clearStore` (which does not rerun queries or reestablish watches) and `resetStore` (which does):
```ts
  public resetStore(): Promise<ApolloQueryResult<any>[] | null> {
    return Promise.resolve()
      .then(() => this.queryManager.clearStore())
      .then(() => Promise.all(this.resetStoreCallbacks.map(fn => fn())))
      .then(() => this.reFetchObservableQueries());
  }

  /**
   * Remove all data from the store. Unlike `resetStore`, `clearStore` will
   * not refetch any active queries.
   */
  public clearStore(): Promise<any[]> {
    return Promise.resolve()
      .then(() => this.queryManager.clearStore())
      .then(() => Promise.all(this.clearStoreCallbacks.map(fn => fn())));
  }
```
If you don't refetch, there won't be anything "listening" to changes in reactive variables.

**Comment by davidohlin** [comment]
@emiloberg I have the exact same use case, except `resetStore`  doesn't clear the cache at all. I don't really understand the response from @benjamn above. 

Did you solve it for your use case, and if so, do you mind sharing how?
