### ISSUE TITLE
AC3 Breaks Apollo Client DevTools Query Tab

### ISSUE THREAD

**Issue by ahrnee** [apollographql/apollo-client#6367]
**Intended outcome:**
Apollo DevTools client, Query Tab, works

**Actual outcome:**
Apollo DevTools client, Query Tab, is broken (as of AC3 v3.0.0-beta.40)

**Note**
Perhaps this issue should be posted/moved to the [apollo-client-devtools](https://github.com/apollographql/apollo-client-devtools) Repo. However, starting here because:
- It was an AC3 change that broke the Apollo Client DevTools
- This repo seems much more active, and Apollo Client DevTools is a very important part of the Apollo Client dev experience

**How to reproduce the issue:**
See this [react-apollo-error-template](https://github.com/ahrnee/react-apollo-error-template/tree/ac3_breaking_apollo_dev_tools) for a recreation.
1. Open Apollo Dev Tools
2. View Query Tab
3. Click 'Create New Person' button, to initiate query
4. Observe the entire Apollo Dev Tools tab (disappear)

**Demo**
![ApolloDevToolsIssue2](https://user-images.githubusercontent.com/39815557/83323868-6e079080-a259-11ea-8c9f-a86227c41934.gif)

**Versions**
_Apollo Client DevTools Version_
2.3.0

_AC3 Versions_
- Works in AC3 v3.0.0-beta.39
- Breaks as of AC3 v3.0.0-beta.40 + 
- Latest version tested in: AC3 v3.0.0-beta.53 (still breaks)
------------------
  System:
    OS: macOS 10.15.5
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Safari: 13.1.1
  npmPackages:
    @apollo/client: 3.0.0-beta.40 => 3.0.0-beta.40

**Comment by hwillson** [comment]
@ahrnee See https://github.com/apollographql/apollo-client-devtools/issues/231 - this should now be fixed in devtools 2.3.1. Thanks!
