### ISSUE TITLE
MockedProvider throws an error in a subsequent test when a mock is missing

### ISSUE THREAD

**Issue by BenoitHiller** [apollographql/apollo-client#6378]
I attempted to perform the following two tests of a component in order using MockedProvider:

1. Test that the component shows a loading state when a the query is still loading by passing in `mocks={[]}`
2. Test that the component shows a result when the same query is done loading

**Intended outcome:**
Either both tests pass or only the first test passes.

**Actual outcome:**
The second test fails unless the tests are performed in the opposite order

**How to reproduce the issue:**
1. Use the `MockedProvider` with an empty `mocks` list.
2. Allow the event loop to move forward such as with a `setTimeout` promise.

```javascript.jsx
it('succeeds', () => {
  const component = renderer.create(
    <MockedProvider mocks={[]}>
      <App />
    </MockedProvider>
  );
});

it('fails', async () => {
  await new Promise((resolve) => setTimeout(resolve, 0));
});
```

You can see a longer reproduction closer to the actual code as well as a runnable version of the above in [this fork of the error reproduction repository](https://github.com/BenoitHiller/react-apollo-error-template/commit/b8dab10f6c02cfa95482140157a8a9556f52f81e).

**Versions**
```
  System:
    OS: macOS 10.15.4
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.21.1 - ~/.nvm/versions/node/v12.13.1/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 72.0.2
    Safari: 13.1
  npmPackages:
    @apollo/client: ^3.0.0-rc.0 => 3.0.0-rc.0
```

**Comment by hwillson** [comment]
https://github.com/apollographql/apollo-client/pull/7108 should have fixed this - let us know if not - thanks!
