### ISSUE TITLE
Using @client fields as variables does not work

### ISSUE THREAD

**Issue by leapworkcto** [apollographql/apollo-client#6379]
**Intended outcome:**
Use `@client @export(as: "fieldName")` in a remote query and get data back.

**Actual outcome:**
Data is undefined as query result, but Chrome DevTools shows the correct query was sent and the correct data was returned from the server.

`query GetBooks($fco: Int, $filterText: String!) {
            filterCount @client @export(as: "fco")
            getBooks(count: $fco, filter: $filterText) {
                title, author, id
            }
        }
`

If the `@fco` variable is passed into the query directly, everything works as expected.

Up to this point, everything works (the result object contains the data object with the correct data retrieved from the GraphQL endpoint):

![image](https://user-images.githubusercontent.com/64967175/83759236-8e798580-a673-11ea-9e90-e8ab55a774c1.png)

But the returned object is undefined:

![image](https://user-images.githubusercontent.com/64967175/83759529-f6c86700-a673-11ea-875e-61c4ab44a782.png)

**How to reproduce the issue:**
I have seen this issue been described in comments, will link when I find again. So I can't be the only one who have seen this.

**Versions**
  System:
    OS: macOS 10.15.4
  Binaries:
    Node: 14.1.0 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Safari: 13.1
  npmPackages:
    @apollo/client: ^3.0.0-rc.0 => 3.0.0-rc.0

**Comment by alexanderchan** [comment]
appears to be happening for me on `3.0.0-rc.6` also

**Comment by vukers** [comment]
I'm facing a possibly related issue. It seems that when using a `@client` field as a variable to a remote query, changes to that `@client` field is not causing the remote query to fetch again. The result of this is a call to the GraphQL server with an empty value in the variables object, and no further calls/re-renders.

For example, when I use (similar to documentation example):
```
  query GetCurrentUser($userId: String) {
    currentUserId @client @export(as: "userId")

    User(userId: $userId) {
      Profile {
        email
        firstName
        lastName
      }
    }
  }
```

I see only _one_ GraphQL call in the browser's network tab with an empty `$userId` value. If I were to subsequently use Apollo Chrome DevTools to run the same query, it properly executes with a populated value. 

To fix this manually, I am splitting this up to 2 separate queries (which according to the documentation, was what the `@export` feature was trying to solve):

```
const GET_USERID_QUERY = gql`
  query GetCurrentUserId {
    currentUserId @client
  }
`;

const GET_USER_QUERY = gql`
  query GetCurrentUser($userId: String) {
    User(userId: $userId) {
      Profile {
        email
        firstName
        lastName
      }
    }
  }
`;
```

and then later:

```
  const { data: { currentUserId } } = useQuery(GET_USERID_QUERY);

  const { loading, data, error } = useQuery(GET_USER_QUERY, {
    variables: {
      userId: currentUserId
    },
    skip: !currentUserId
  });
```

Note: I saw the same behaviour on `3.0.0-rc.4` and `3.0.0-rc.9`.

**Comment by willingram** [comment]
I'm experiencing the same issue as @leapworkcto on rc-10.
The cache _does_ appear to be correctly populated with the result of the query.

**Comment by wonjerry** [comment]
+1

**Comment by sam-coxon** [comment]
+1

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
