### ISSUE TITLE
A mutation call can return `undefined` if `onError` has been defined

### ISSUE THREAD

**Issue by antoinelyset** [apollographql/apollo-client#6380]
If `onError` has been defined in `useMutation`, the client doesn't throw an actual error (in case of a server-side error) see :

https://github.com/apollographql/apollo-client/blob/379bbb024a0909714e949d76584a3b76067649cb/src/react/data/MutationData.ts#L74-L77

It means that calling `mutation()` will return `undefined`. This is problematic since TypeScript does not force us to handle this case.

**Intended outcome:**
I wish TypeScript typing would help me by forcing me to handle the case where a mutation returns `undefined`.

**Actual outcome:**
TypeScript let us continue without handling the `undefined` case.

**How to reproduce the issue:**
I don't really know how to reproduce it with the sandbox.

But it can be reproduced by having :

```typescript
const [createSomething] = useCreateSometingMutation({
  onError(error) {
    console.log('Error')
  },
})

const something = createSomething()
```
`something` here can be `undefined` if an error has been raised. Which not what you would expect from TypeScript typing.

**Versions**

  System:
    OS: macOS 10.15.2
  Binaries:
    Node: 12.15.0 - /usr/local/opt/node@12/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/opt/node@12/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Safari: 13.0.4
  npmPackages:
    @apollo/react-hoc: ^3.1.5 => 3.1.5
    @apollo/react-hooks: ^3.1.5 => 3.1.5
    apollo-boost: ^0.4.7 => 0.4.9
    apollo-link: ^1.2.8 => 1.2.14
    apollo-link-batch-http: ^1.2.2 => 1.2.14
    apollo-link-context: latest => 1.0.20
    apollo-link-http: ^1.5.15 => 1.5.17
    apollo-link-ws: ^1.0.14 => 1.0.20
    apollo-utilities: ^1.2.1 => 1.3.4

Do not hesitate to ping to provide more information if I'm not clear enough.

**Comment by EllaSharakanski** [comment]
Any updates on this?

**Comment by gino8080** [comment]
up

**Comment by matheuss-leonel** [comment]
up

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
