### ISSUE TITLE
`useQuery` doesn't expect a link to return data synchronously

### ISSUE THREAD

**Issue by duarten** [apollographql/apollo-client#6384]
I have a custom link that maps a query to another, potentially cached query[1]. If the query isn't cached, everything works fine. However, if the query is cached and we return synchronously from the Link, then no data is returned and the query stays in the loading state.

Following the code:
1. In `QueryData::execute()`, `if (this.isMounted) this.startQuerySubscription();` doesn't happen;
2. Then, in `getExecuteResult()`, `this.startQuerySubscription();` happens unconditionally;
3. Subscribing goes to `newReobserver()`, then `fetchQueryByPolicy()`, then `fromVariables()`, then `fetchQueryByPolicy()`;
4. This calls into my Link, which returns immediately and `next()` is called; however: `if (this.isMounted) onNewData();`. The call to `onNewData()` is ignored, and the data I returned from the Link is lost.
5. `afterExecute` is called, which sets `isMounted` to `true`.

The `isMounted` logic seems broken; I don't know what its exact semantics should be, so I can't offer a solution.

[1]: the use case is querying for an object using a changeable domain name instead of the fixed ID, which requires a translation in the server; however, that mapping will usually be present in the cache as it's contained in the result of other queries, so we help the server by doing the translation in the Link.

**Intended outcome:**
The data returned from my Link to be returned from the query.

**Actual outcome:**

The data is lost.

**How to reproduce the issue:**

Create a link that returns data synchronously.

**Versions**

```
  System:
    OS: macOS 10.15.4
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.97
    Firefox: 76.0.1
    Safari: 13.1
  npmPackages:
    @apollo/client: 3.0.0-rc.0 => 3.0.0-rc.0
```

**Comment by duarten** [comment]
Symptoms seem similar to #2669 and others.

**Comment by sarakusha** [comment]
I have a similar problem.
When I use useQuery with SSR,
`getMarkupFromTree => renderPromises.consumeAndAwaitPromises()` <- it will never resolved
because `QueryData::isMounted === false` and see above
> This calls into my Link, which returns immediately and next() is called; however: if (this.isMounted) onNewData();. The call to onNewData() is ignored, and the data I returned from the Link is lost.

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
