### ISSUE TITLE
rc0 breaks our nextjs site

### ISSUE THREAD

**Issue by reggaemuffin** [apollographql/apollo-client#6385]
**Intended outcome:**
We were updating our apollo-client version to v3.0.0-rc.0 and expected it to work

**Actual outcome:**
Any call that used the apollo client timed out, which for us was server side rendered pages. We did not find any errors or log messages.

**How to reproduce the issue:**
We are currently in the process of investigation, but wanted to already alert the apollo-client team of this rc possibly silently breaking sites. I will update this issue if I figure out a way to reproduce this.

Our unit tests using a mocked schema did **not** break and were all green but when used against a real endpoint timeouts happen. There were no actual requests going out, as even if the graphql endpoint was not running it still timed out.

**Versions**
The issue was irrespective of os or browser and timed out in ssr rendered pages in nextjs
  npmPackages:
    @apollo/client: ^3.0.0-rc.0 => 3.0.0-rc.0 
    @apollo/link-schema: ^2.0.0-beta.3 => 2.0.0-beta.3 
    @apollo/react-common: ^3.1.4 => 3.1.4 
    @apollo/react-testing: ^3.1.3 => 3.1.4 
    apollo: 2.28.0 => 2.28.0 
    apollo-cache-inmemory: ^1.6.6 => 1.6.6 
    apollo-client: ^2.6.10 => 2.6.10 
    apollo-link-context: ^1.0.20 => 1.0.20 
    apollo-link-persisted-queries: ^0.2.2 => 0.2.2 
    apollo-link-schema: ^1.2.5 => 1.2.5 
    apollo-storybook-react: ^0.2.4 => 0.2.4 
    react-apollo: ^4.0.0-beta.1 => 4.0.0-beta.1

**Comment by gtwright** [comment]
Looks like this ssr issue is reported on the Next repo, too: https://github.com/vercel/next.js/issues/13702

**Comment by benjamn** [comment]
What version were you upgrading from? If you were previously using `apollo-client` (AC2), the new `@apollo/client` (AC3) package is a major update, with a number of absolutely necessary [migration steps](https://www.apollographql.com/docs/react/v3.0-beta/migrating/apollo-client-3-migration/). Hopefully you already know this, but I honestly cannot guess this information from your description.

**Comment by reggaemuffin** [comment]
> What version were you upgrading from? If you were previously using `apollo-client` (AC2), the new `@apollo/client` (AC3) package is a major update, with a number of absolutely necessary [migration steps](https://www.apollographql.com/docs/react/v3.0-beta/migrating/apollo-client-3-migration/). Hopefully you already know this, but I honestly cannot guess this information from your description.

I was upgrading from beta.50 which was I believe a few days ago.

**Comment by benjamn** [comment]
@reggaemuffin If the problem has to do with SSR, then I believe #6388 may help (published in `@apollo/client@3.0.0-rc.1` just now). Let us know!

**Comment by hwillson** [comment]
This should be fixed in more recent versions of `@apollo/client`. Thanks!

**Comment by reggaemuffin** [comment]
I can confirm this, we updated to I believe rc30 and are on a working version that has this bug fixed :)
