### ISSUE TITLE
Apollo 3.0.0-rc.1 stuck on loading after cache redirects (type policies)

### ISSUE THREAD

**Issue by darkbasic** [apollographql/apollo-client#6392]
Latest working version was 3.0.0-beta.54. Since 3.0.0-rc.0 the loading state remains on `true` forever after a cache redirect. This obviously breaks my whole application, but if I omit the checks on the loading state everything seems to work normally from what I can see.

**Comment by fwojciec** [comment]
Confirmed here -- I'm experiencing the exact same problem after updating from 3.0.0-beta.43 to 3.0.0-rc.1.

**Comment by benjamn** [comment]
Not to be a broken record, but a reproduction or failing test case would be a big help here!

**Comment by darkbasic** [comment]
@benjamn I think we won't need a repro because it has been fixed by rc2.

Not sure if it was intentional or not so I won't open a separate bug report, but I also noticed that since rc0 you cannot import `Modifier` from `@apollo/client` anymore, instead you have to import it from `@apollo/client/cache/core/types/common`
