### ISSUE TITLE
How to improve performance?

### ISSUE THREAD

**Issue by Ed-Ed** [apollographql/apollo-client#6396]
I've identified a performance issue and I'm not sure what's causing it.

Currently my homepage has no queries on it:

The `getDataFromTree` method takes 101ms. 
The `renderToNodeStream` method takes 172ms.

If I add a query to the homepage, the methods take longer, as expected, but it's taking much longer than expected:

The `getDataFromTree` method takes 426ms. 
The `renderToNodeStream` method takes 311ms.

Out of these 426ms, it resolves the request to the API in 49ms, which means the problem is not there as there is still an extra 276ms looming.

The data I'm retrieving is category tree data, like so:

```
{
  "categoryId": "0",
  "name": "All Categories",
  "slug": "",
  "path": [],
  "__typename": "Category",
  "children": [
    {
      "categoryId": "537",
      "name": "Baby & Toddler",
      "slug": "baby-and-toddler",
      "path": [],
      "__typename": "Category",
      "children": [
        {
          "categoryId": "4678",
          "name": "Baby Bathing",
          "slug": "baby-and-toddler/baby-bathing",
          "path": [
            {
              "categoryId": "537",
              "name": "Baby & Toddler",
              "slug": "baby-and-toddler",
              "__typename": "CategoryTreePath"
            }
          ],
          "__typename": "Category",
          "children": []
        },
```

The main categoryId (categoryId: 0) has 5 children, each of those have 5 children, but those children don't have children, as you can see, which means I essentially have "3 layers" of JSON data.

NOTE: I use categoryId rather than id because I didn't want it normalising the data, since I might request id 537 later, but this time I want the children whereas in this request, I don't.

This data is sent in the initial HTML payload for store rehydration.

NOTE: I used `graphql-codegen`

In the frontend, I do the following:

```
  const { data } = useGetCategoryQuery({
    variables: {
      categoryId: '0'
    }
  });

  console.log(data);
```

If I comment out this hook, I go back to 101ms. If I include it, it rockets to 426ms. This could be of many reasons:

- Am I structuring my data in a good way?
- Maybe not normalising it is slower to process?
- Are there any methods I should be following - maybe something to do with caching client side?

**Comment by benjamn** [comment]
Can you show how you're calling `getDataFromTree`? There's another function called `getMarkupFromTree` that returns a promise for the generated HTML, so you shouldn't have to do an extra render to get the HTML. Perhaps that could help? Also happy to do some performance profiling, given some example code.

**Comment by Ed-Ed** [comment]
Hi Benjamn, thanks for the reply.

The reason I use `getDataFromTree` rather than `getMarkupFromTree` is because I also use Emotion. Here's an example of how I call `getDataFromTree`:

```
const link = ApolloLink.from([errorLink, injectedHeaders, persistedQueryLink, httpLink]);
const cache = new InMemoryCache();

const apolloClient = new ApolloClient({
  ssrMode: true,
  cache,
  link,
  resolvers
})

getDataFromTree(<App />).then(() => {
  const apolloData = apolloClient.extract();
  const stream = renderToNodeStream(<App />).pipe(renderStylesToNodeStream());

  res.set("content-type", "text/html");
  res.write(header());

  stream.pipe(res, { end: false });

  stream.on('end', () => {
    res.write(
      footer({
        apolloData,
      })
    );

    return res.end();
  });
})
```

I'll try and provide a repo example tomorrow.

**Comment by Ed-Ed** [comment]
Performance problem was resolved by upgrading to Apollo 3.

**Comment by dmngu9** [comment]
do you have stats after upgrading?
