### ISSUE TITLE
Apollo Local State - local child resolver not firing since beta

### ISSUE THREAD

**Issue by tilersmyth** [apollographql/apollo-client#6397]
Since upgrading from `2.6.10` to `3.0.0-rc.0` (also tried `v3.0.0-beta.54`) local child resolvers are not executing. 

**the code** 

graphql: 
```
query GetAppState {
  appState @client {
    company
  }
}
```

typeDef:

```
type AppState {
  company: Boolean!
}

extend type Query {
  appState: AppState!
}
```

resolver:
```
Query: {
  appState: () => ({ __typename: "AppState" }),
},
AppState: {
  company: () => {
    console.log("Child resolver called");
    return true;
  },
},
```

Calling resolver:
```
export const Entry: React.FunctionComponent = () => {
  const { loading, data, error } = useQuery<
    GetAppStateQuery,
    GetAppStateQueryVariables
  >(GetAppStateDocument);

  console.log("APP STATE", loading, data, error);

  if (loading) {
    return <AppLoading />;
  }

  return (
    <PaperProvider theme={theme}>
      <NavigationContainer>
        <RootNavigator />
      </NavigationContainer>
    </PaperProvider>
  );
};
```

**Intended outcome:**

In `2.6.10` this will log:
```
[LOG] APP STATE true undefined undefined
[LOG] Child resolver called
[LOG] APP STATE false Object {
  "appState": Object {
    "__typename": "AppState",
    "company": true,
  },
} undefined
```

**Actual outcome:**

In `3.0.0-rc.0` (and `v3.0.0-beta.54`) this will log:
```
[LOG] APP STATE true undefined undefined
[LOG] APP STATE false undefined undefined
```

**How to reproduce the issue:**
Running the above code in `2.6.10` vs `3.0.0-rc.0`

**Versions**
```
System:
    OS: macOS 10.15.4
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Safari: 13.1
  npmPackages:
    @apollo/react-components: ^4.0.0-beta.1 => 4.0.0-beta.1
```

`npx envinfo@latest --preset apollo --clipboard` is not capturing `@apollo/client` for some reason but I can confirm I am running `"@apollo/client": "3.0.0-rc.0`

**Comment by benjamn** [comment]
Can you try again with `-rc.2` (just published)?

**Comment by tilersmyth** [comment]
Just tried with `-rc.2` - child resolver still not executing

**Comment by benjamn** [comment]
Ok good to know. If you can put together a runnable reproduction, I'm happy to do the bisecting myself, but I'm curious if there were any beta versions (0-54) that worked.

**Comment by tilersmyth** [comment]
Ugh.. this is totally fine.. and embarrassing. 
In the course of creating the repro I realized when toggling between versions my typeDefs and resolvers were not referenced properly on the beta version.
