### ISSUE TITLE
apollo link context: Type 'ApolloLink' is not assignable to type 'ApolloLink | RequestHandler'.

### ISSUE THREAD

**Issue by IljaDaderko** [apollographql/apollo-client#6403]
**Intended outcome:**
Using `@apollo/link-context` alongside `@apollo/client` should result in no type errors.

**Actual outcome:**
`concat` method of `@apollo/link-context` throws an error

> Type 'ApolloLink' is not assignable to type 'ApolloLink | RequestHandler'.

**How to reproduce the issue:**
```ts
import { ApolloClient, ApolloProvider, HttpLink, InMemoryCache } from '@apollo/client';
import { setContext } from '@apollo/link-context';

const GRAPHQL_URL = 'myAPi.dev/v1/graphql';

const httpLink = new HttpLink({
  uri: `https://${GRAPHQL_URL}`
});

const authLink = setContext(async (_, { headers }) => {
  return {
    headers
  };
});

const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: authLink.concat(httpLink) // Type Error Thrown Here
});
```

**Versions**
```json
{
  "dependencies": {
      "@apollo/client": "3.0.0-rc.2",
      "@apollo/link-context": "2.0.0-beta.3"
  }
}
```

```
  System:
    OS: macOS 10.15.5
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.97
    Safari: 13.1.1
```

**Comment by strongpauly** [comment]
I get the same error with `@apollo/link-error` version `2.0.0-beta.3`.  Issue seems to have been introduced after upgrading from `@apollo/client` `^3.0.0-beta.49` -> `^3.0.0-rc.2`.

Workaround was to cast to `unknown` before casting to `ApolloLink`

**Comment by IljaDaderko** [comment]
A work around, and probably more readable solution to this problem is to use `from`. I think bigger issue here is documentation showing too many ways to achieve one thing

```ts
import { /* other imports */ from } from '@apollo/client';

const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: from([authLink, httpLink])
});
```

**Comment by duro** [comment]
If you are using yarn, there is an even cleaner workaround. Add this to your package.json:

```
"resolutions": {
    "@apollo/link-context/@apollo/client": "3.0.0-rc.2"
  },
```

This will overwrite the conflicting dep that @apollo/link-context is pulling in.

**Comment by schematis** [comment]
I'm having this same issue with `ApolloLink.from()` and `createPersistedQueryLink()`. Comparing the types they look exactly the same, so I have no idea what the issue is.

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
