### ISSUE TITLE
Subscription prematurely closed w/ useSubscription + webpack + react-fast-refresh (plus possible simple fix)

### ISSUE THREAD

**Issue by papercuptech** [apollographql/apollo-client#6405]
**Intended outcome:**
When changing JSX of func component that uses `useSubscription`, while webpack-dev-server --hot is running, underlying subscription should not be lost; i.e. source pushes should still result in `useSubscription` causing re-render.

**Actual outcome:**
After first change to func component, source changes pushed no longer cause `useSubscription` to cause re-render.

**How to reproduce the issue:**
Minimal setup of webpack, @pmmmwh/react-refresh-webpack-plugin, react-refresh

**Possible fix**
I changed this:
https://github.com/apollographql/apollo-client/blob/0340c48429b20f621d552af748527798bf6f26c5/src/react/data/SubscriptionData.ts#L145

to this (quick hack in node_modules/@apollo... to see if would work)
```javascript
    if (this.currentObservable.subscription && !this.isMounted) {
```

Simple breakpoint testing for a component fast-refreshed vs. one that has been unmounted appears to indicate adding `&& !this.isMounted` solves the problem;i.e. `this.isMounted === true` when `endSubscription` called as part of fast-refresh processing, and `this.isMounted === false` when `endSubsctiption` called for a component no longer in (i.e. unmounting /ed or 'leaving') render tree.

**Versions**
  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 14.2.0 - ~\AppData\Local\nvs\default\node.EXE
    npm: 6.14.4 - ~\AppData\Local\nvs\default\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @apollo/client: ^3.0.0-rc.2 => 3.0.0-rc.2
    @apollo/link-ws: ^2.0.0-beta.3 => 2.0.0-beta.3

**Comment by nodabladam** [comment]
On my apollo client 2.6 dev machine when I am doing development unrelated to apollo (css/jsx changes), I seem to occasionally get some errors about subscribeToMore being undefined.  It would certainly be nice for this to be fixed in 3.

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
