### ISSUE TITLE
Can't find field __typename on object

### ISSUE THREAD

**Issue by bizready** [apollographql/apollo-client#6409]
I am creating 1 record and add to the cache so that data gets quickly in the UI. It works as expected. I have a scenario in which I need to add many records (meaning the user can create a set of records) to cache so that it will reflect in UI quickly. Record counts maybe 2-4. When I am trying to add 2nd record, it fails with error - `Error: Can't find field __typename on object {
  "id": "7571ef50-f621-4c68-88d8-d86fb0dc5938",` here `7571ef50-f621-4c68-88d8-d86fb0dc5938` is `id` of 1st object created.

The error happens while reading cache with `store.readQuery`

**Actual outcome:**
I am able to add 1 record. when I second record, it fails with error `Error: Can't find field __typename on object `

**Expected outcome:**
I am able to add 1 record. when I second record, it should not fail as I am trying to add a similar object as the first one. All objects do not have `__typename` as it is created by the framework. I can not add `__typename` as it fails with schema validation saying that `Error: GraphQL error: The variables input contains a field name '__typename' that is not defined for input object type 'CreateSessionInput'`

Please help me with any possible solution.

**Comment by enrilchow** [comment]
When you write cache directly you should explicitly include  __typename in the object to be cached (cuz 
if there is a union type the __typename can't be auto resolved).

**Comment by bizready** [comment]
Thanks for your response @enrilchow. As documented in the above 'Expected Outcome' section, I have tried by setting `__typename' before saving the object to the cache. Because input schema validation, it does not allow manually setting `__typename`. it is a catch-22 situation. Input schema validation does not allow set `__typename', and adding 2nd record to cache expects `__typename` on existing objects in the cache. 1st record exists in the cache without `__typename`, but while adding 2nd record, it errors by saying record should have `__typename' - the error pointing to 1st record in the cache before even adding 2nd record to the cache.

Below are my steps.
create object1 (without `typename`) - OK
add to cache - OK
create object2 (without `typename`) - OK
add to cache - fails while reading the cache (not writing), it points object1 in cache saying that it needs to have `__typename`

**Comment by enrilchow** [comment]
@bizready Can you paste your code on the writing cache step here? There was something misplaced.

**Comment by enrilchow** [comment]
can you try add __typename then use console to print _data_ just before #line 123

**Comment by hwillson** [comment]
This doesn't sound like an Apollo Client issue, but if anyone thinks it is and can provide a small runnable reproduction using `@apollo/client@latest`, we'll take a look. Thanks!
