### ISSUE TITLE
Cannot read property 'hasOwnProperty' of undefined, from QueryManager

### ISSUE THREAD

**Issue by dandv** [apollographql/apollo-client#6414]
**Intended outcome:**
I'm trying to auto-retry queries in case of UNAUTHENTICATED errors where the JWT is expired, based on [this code](https://github.com/apollographql/apollo-link/pull/825/files).

**Actual outcome:**
I'm getting a `TypeError: Cannot read property 'hasOwnProperty' of undefined` that seems to come from [these lines](https://github.com/apollographql/apollo-client/blob/7f2b1b0c07a94e5f78cb7fcbc104e7f9633e7df9/src/core/QueryManager.ts#L804-L805).

![image](https://user-images.githubusercontent.com/33569/84091193-935a7400-a9a8-11ea-8846-37fd22b8732e.png)

**How to reproduce the issue:**
Unfortunately it's difficult to create a minimal repro, so I'm hoping that someone familiar with Apollo Client could easily spot the cause of the error. If you do need a repro, please let me know and I'll see what I can do.

My code that I think is triggering this edge case is like this:

```ts
const errorLink = onError(({ graphQLErrors, operation, forward }) => {
  for (const error of graphQLErrors || [])
    if (error?.extensions?.code === 'UNAUTHENTICATED' && error?.message.includes('jwt expire')) {
      const oldHeaders = operation.getContext().headers;
      const promise = AuthService.checkSession();  // <-- this rejects without a return value
      return promiseToObservable(promise).flatMap((authResult) => {
        if (authResult?.['idToken']) {
          localStorage.setItem('idToken', authResult['idToken']);
          operation.setContext({
            headers: {
              ...oldHeaders,
              authorization: `Bearer ${authResult['idToken']}`,
            },
          });
        } else {
          localStorage.removeItem('idToken');
          delete oldHeaders.authorization;
          operation.setContext({
            headers: oldHeaders,
          });
        }
        return forward(operation);
      });
    }
});
```

If I monkeypatch the AuthService library to `reject(err)` (not sure about `reject(null)`), the error doesn't occur and the code works as intended.

**Versions**

```
  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
  Binaries:
    Node: 13.14.0 - /usr/bin/node
    npm: 6.14.5 - ~/.local/bin/npm
  Browsers:
    Firefox: 77.0.1
  npmPackages:
    @apollo/client: ^3.0.0-rc.2 => 3.0.0-rc.2 
    apollo-link-context: ^1.0.20 => 1.0.20 
    apollo-link-error: ^1.1.13 => 1.1.13 
```

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
