### ISSUE TITLE
[3.0.rc2] cache.evict without id is not working correctly

### ISSUE THREAD

**Issue by tafelito** [apollographql/apollo-client#6418]
Base on #6364 doing this

`cache.evict({ id: "ROOT_QUERY", fieldName });`
or
`cache.evict({ fieldName });`
 should be the same but actually doing the latter doesn't seem to be working. The data from the cache is not evicted.

if you console out the result from the first one is returns true where the second one returns false and the data still present in the cache

**Comment by benjamn** [comment]
Since these usages are both pretty well tested by our test suite, I would ask you to set a breakpoint before the `cache.evict` call that doesn't seem to be doing anything, and step into it to get some insight into what might (not) be happening.

**Comment by tafelito** [comment]
the difference seems to be here
```js
EntityStore.prototype.evict = function (options) {
  var evicted = false;
  if (hasOwn.call(this.data, options.id)) { `--> 1st option never enters here, while 2nd does` 
      evicted = this.delete(options.id, options.fieldName, options.args);
  }
  if (this instanceof Layer) {
      evicted = this.parent.evict(options) || evicted;
  }
  this.group.dirty(options.id, options.fieldName || "__exists");
  return evicted;
};
```

**Comment by tafelito** [comment]
@benjamn while I was trying to figure this out, I also found the when you evict an item by id, the reference is in fact removed, but it is not being removed from the ROOT_QUERY.

So after doing this

```js
cache.evict({
  id: cache.identify({
    __typename: "profiles",
    id,
  }),
});
```

this is how the cache looks like

![image](https://user-images.githubusercontent.com/5973652/84199524-58714280-aa73-11ea-9ab0-b990f5748a67.png)

so then the query returns the incorrect data

**Comment by benjamn** [comment]
@tafelito Please take a look at #6412. Leaving references in place after eviction is expected behavior, but you can override that behavior by defining a field `read` function.

**Comment by benjamn** [comment]
Also, what version of `@apollo/client` are you using?

**Comment by tafelito** [comment]
yes I was actually looking at it right now but since I'm using the merge/read functions to handle pagination, I'm not sure how to that would work together. Do I need to check every reference from the existing array in the read function?

```js 
read(existing: any[], { args }) {
  // Check every item in exiting to see if is a valid reference?

  const page = existing && existing.slice(
    args.offset,
    args.offset + args.limit,
  );
  if (page && page.length > 0) {
    return page;
  }
},
```

> Also, what version of @apollo/client are you using?
I'm on 3.0.0.rc-2

**Comment by tafelito** [comment]
maybe doing something like this would be the correct way?

```js
read(existing: any[], { args }) {
  const page = existing && existing.slice(
    args.offset,
    args.offset + args.limit,
  ).filter(item => item && readField("id", item));
  if (page && page.length > 0) {
    return page;
  }
},
```

**Comment by benjamn** [comment]
Yes, that's the general idea. PR #6413 added support for `isReference(item, true)` to detect if a reference is readable, so you could do that instead of `item && readField("id", item)`. However, this example makes me think it might be better to have a separate function called `options.isReadable` that would return `true` for non-reference objects as well (anything you can pass as the second argument to `readField`).

**Comment by tafelito** [comment]
@benjamn I just updated to `rc.4` and tried to use the new `canRead` function instead of `readField` in the merge function but it throws an error saying canRead is not a function

**Comment by benjamn** [comment]
Did you ever get `cache.evict` to work against the `ROOT_QUERY` by omitting the `id`?

**Comment by tafelito** [comment]
yes, it's working ok now!
