### ISSUE TITLE
TypeScript fetchMore with query option

### ISSUE THREAD

**Issue by johnnyBira** [apollographql/apollo-client#6420]
When using `fetchMore` which is returned form `useQuery` to fetch more data, it seams the query from the initial query is inferred by TypeScript.

This is all well and good as long as you don't passa a different query with different response data compared to the the initial query.
I'm running into some issues which I thing stems from typecasting `fetchMoreResult` to the expected result of the new query:

![image](https://user-images.githubusercontent.com/23634023/84209740-31d4fb00-aab7-11ea-9701-361aeb5b2737.png)

How can we properly type `fetchMore` when using the query options?

Best,
/John

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
