### ISSUE TITLE
Subscription not working in React Native?

### ISSUE THREAD

**Issue by PritishSawant** [apollographql/apollo-client#6423]
I am trying out subscription in my app but it doesn't seem to work. There is no issue from backend side as the subscription work in Graphiql interface 

Here is my code 

```
const httpLink = createHttpLink({
  uri: 'http://localhost:5000',
});

const wsLink = new WebSocketLink({
  uri: `ws://localhost:5000`,
  options: {
    reconnect: true,
    connectionParams: {
      // headers: {
      //   Authorization: `Bearer ${token}`,
      // },
    },
  },
});

const authLink = setContext(async (req, {headers}) => {
  try {
    const token = await AsyncStorage.getItem('token');
    return {
      headers: {
        ...headers,
        authorization: token ? `Bearer ${token}` : '',
      },
    };
  } catch (e) {
    console.log(e);
  }
});

const link = split(
  ({query}) => {
    const {kind, operation} = getMainDefinition(query);
    return kind === 'OperationDefinition' && operation === 'subscription';
  },
  wsLink,
  authLink.concat(httpLink),
);

const client = new ApolloClient({
  link: link,
  cache: new InMemoryCache(),
});
```

Subscription hook
const {data, error, loading} = useSubscription(
    HEALTH_CONSULTATION_SUBSCRIPTION,
  );

I am neither getting error nor data.

**Comment by martimalek** [comment]
@PritishSawant did you find a fix / workaround for this?

**Comment by PritishSawant** [comment]
@martimalek  yes the issue was web socket are not supported on free tier of Heroku if you use apollo Graphql as far as I am aware. I replaced it with Hasura and used in on free tier of Heroku , then it worked. Check this https://stackoverflow.com/questions/62304652/subscription-not-working-in-react-native

**Comment by martimalek** [comment]
Thanks!
