### ISSUE TITLE
How to update the cache when using recursive queries with a variable depth?

### ISSUE THREAD

**Issue by Ed-Ed** [apollographql/apollo-client#6427]
In this example, I want to make a request for a category with an id of 1. I want to get the category's data and it's children's data, but I don't want the children's children. So I'll make a query with a depth variable like the following:

```
category(id: "1", depth: "1") {
  ...CategoryWithChildren
}

fragment Category on Category {
  id
  name
}

  fragment CategoryWithChildren on Category {
    ...Category
    children {
      ...Category
      children {
        ...Category
        children {
          ...Category
        }
      }
    }
  }
```

It'll return data like the following:

```
{
  id: 1,
  name: 'animals',
  children: [
    {
      id: 2,
      name: 'something 1',
      children: []
    },
    {
      id: 3,
      name: 'something 2',
      children: []
    }
  ]
}
```

Later on, I want to request the same category, but this time I want the children's children. So I'll make a query with a depth variable like the following:

```
category(id: "1", depth: "2") {
  ...CategoryWithChildren
}
```

The problem I have is in the cache, the children's children will be an empty array because of the first query, but Apollo will still return this cached data because children is stored as an array and can be null. Please see the category type:

```
type Category {
  categoryId: ID!
  path: [CategoryTreePath!]!
  slug: String!
  level: Int
  name: String!
  children: [Category!]
}
```

What is the proper way to update the cache when using recursive queries like this with a variable depth?

**Comment by PatrykWalach** [comment]
either fetch without children field
```gql
query {
  tag(id: 1) {
    id
    name
    children {
      id
      name
    }
  }
}
```
or also fetch ids
```gql
query {
  tag(id: 1) {
    id
    name
    children {
      id
      name
      children {
        id
      }
    }
  }
}

```

**Comment by Ed-Ed** [comment]
I've updated my question to include the queries that I use.

@PatrykWalach It sounds like you're suggesting that I use different fragments to define how deep the category tree is. What I do is query with a depth variable to define how deep the category tree will be.
