### ISSUE TITLE
Broken link when navigating from apollo client page to react docs

### ISSUE THREAD

**Issue by Ariefbustillo** [apollographql/apollo-client#6430]
**Intended outcome:**
I expect to correctly be redirected to the https://www.apollographql.com/docs/react/ page. 

![image](https://user-images.githubusercontent.com/44046931/84450717-08cf7a00-ac1f-11ea-9322-0af9d81ac01c.png)

**Actual outcome:**
I get the following page when clicking on "Get Started"
![image](https://user-images.githubusercontent.com/44046931/84450677-e8072480-ac1e-11ea-97c0-9eccc3be3c9b.png)

**How to reproduce the issue:**
Go to https://www.apollographql.com/client/ and click on "Get Started" 

![image](https://user-images.githubusercontent.com/44046931/84450790-43391700-ac1f-11ea-818c-c04a2dc34799.png)

**Versions**
N/A

**Comment by hwillson** [comment]
The docs have been updated quite a bit since this issue was opened. Let us know if you still think this is an issue. Thanks!
