### ISSUE TITLE
useSubscription not working in Popup window

### ISSUE THREAD

**Issue by developdeez** [apollographql/apollo-client#6431]
I'm popping up a new page using window.open. The new window is supposed to subscribe to updates but nothing happens.

**Comment by etc-tiago** [comment]
You can share more details or steps to reproduce the issue?

**Comment by hwillson** [comment]
This doesn't sound like an Apollo Client issue, but if anyone thinks it is and can provide a small runnable reproduction using `@apollo/client@latest`, we'll take a look. Thanks!
