### ISSUE TITLE
local state queries and mutations don't throw error if you call it with the wrong variables

### ISSUE THREAD

**Issue by mschipperheyn** [apollographql/apollo-client#6445]
**Intended outcome:**
Local state queries and mutations should be validated just like remote graphql queries and mutations. If you call it with a wrong variable, it should throw an error.

**Actual outcome:**
It accepts illegal input. Leaving you blissfully unaware something is broken.

**How to reproduce the issue:**
Call any local state mutation with a non existing variable.

In my case, I should be calling this
```
_client
    .mutate({
        mutation: MUTATION_SET_STATUS,
        variables: {
            input: {
                type: VALIDATIONERROR,
                message: Object.keys(validationError).reduce(
                    (acc, key) => `${acc} ${key}: ${validationError[key]}`,
                    '',
                ),
            },
        },
    })
    .catch(console.log);
```
but I called this:
```
_client
    .mutate({
        mutation: MUTATION_SET_STATUS,
        variables: {
                type: VALIDATIONERROR,
                message: Object.keys(validationError).reduce(
                    (acc, key) => `${acc} ${key}: ${validationError[key]}`,
                    '',
                ),
        },
    })
    .catch(console.log);
```
**Versions**
3.0.0-rc.4

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
