### ISSUE TITLE
Testing Mutation - Waiting for Mutation to Complete

### ISSUE THREAD

**Issue by sgentile** [apollographql/apollo-client#6452]
The documentation shows this line of code 

```
await wait(0);
```

This throws an error:

TypeError: callback is not a function

What is the proper way to wait for a mutation to complete in a react library test/jest scenario ?

**Comment by dylanwulf** [comment]
The point of `await wait()` is just to wait for the next iteration of the event loop so that the promise can resolve. This should work just as well:
```js
await new Promise(resolve => setTimeout(resolve, 0));
```

Or if you're using `@testing-library/react` you can do this:
```js
await act(async () => {
    // perform some action that would cause the mutation to fire
});
```

Hope this helps!

**Comment by sgentile** [comment]
I was able to get past this.  My issue now is on queries.   I see the loading go from true to false however I get null data and no errors.

Unlike a mutation I do not see what could help in terms of validation it's called - the code is using a useQuery

**Comment by WojciechMatuszewski** [comment]
Is you query using the `cache-only` fetch policy?

**Comment by sgentile** [comment]
I'm not setting that specifically anywhere ?
