### ISSUE TITLE
Trouble paginating programatically

### ISSUE THREAD

**Issue by tdmartino** [apollographql/apollo-client#6453]
Hello,
I am using React-apollo-client and, in order to improve the experience of the user, I want to use pagination to request chunks of data, and I want to loadMore as soon as the previous chunk has been received. Unfortunately, as the data object returned by useQuery is reused for the first request and subsequent ones, I am finding it troublesome to write a useEffect function that does the trick. Something simple like 
```
const {
    data,
    loading,
    error,
    loadMore,
  } = useQuery(
    QUERY,
  );

useEffect((
  if(data.something.pageInfo.hasNextPage) {
     loadMore();
   }
) => {}, [data.something.pageInfo.endCursor, data.something.pageInfo.hasNextPage]);
```

finds loadMore called multiple times, because on loadMore data.something.pageInfo.endCursor is reset to undefined and some other updates I am unsure about. Is there a recommended way to do what I need to do with this library? 
Thank you very much in advance.

**Comment by benjamn** [comment]
The function is called `fetchMore`, not `loadMore`. TypeScript should warn you about things like this.

If that doesn't solve the problem, please let us know what version of Apollo Client you're using.

**Comment by tdmartino** [comment]
Thank you @benjamn  - I am able to paginate well when the fetchMore is invoked by a user, my issue is start getting the next page once the first page is done. loadMore there us just a typo. I am using v 2.6.8

**Comment by tdmartino** [comment]
I guess I can rephrase my question as: is there something in the object returned by react apollo client hooks that changes deterministically _only_ when a specific request is done fetching data, so I can condition my useEffect function on?
