### ISSUE TITLE
QueryResult.loading not updated when fetchMore is called from 3.0.0-beta.46

### ISSUE THREAD

**Issue by dosatross** [apollographql/apollo-client#6459]
`loading` variable of useQuery result remains false while `fetchMore` call is pending network request. I have `notifyOnNetworkStatusChange: true` in useQuery options.
This seems to have been introduced in 3.0.0-beta.46 as it does not occur in 3.0.0-beta.45

**Intended outcome:**
expect `loading` variable to be true after fetchMore is called

**Actual outcome:**
`loading` remains false after `fetchMore` is called

**How to reproduce the issue:**
query with useQuery and paginate with `fetchMore`
notice `loading` remains false after `fetchMore` is called
revert back to version 3.0.0-beta.45 and do the same
notice `loading` is true after `fetchMore` is called

**Versions**
System:
    OS: macOS Sierra 10.12.6
  Binaries:
    Node: 13.1.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Firefox: 59.0.1
    Safari: 12.1.2
  npmPackages:
    @apollo/client: 3.0.0-beta.46 => 3.0.0-beta.46

**Comment by mschipperheyn** [comment]
See also https://github.com/apollographql/apollo-client/issues/6354

**Comment by benjamn** [comment]
Yep, that's the same problem. Let's close this in favor of #6354. Thanks!
