### ISSUE TITLE
refetchQuery on a mutation causing CORS error

### ISSUE THREAD

**Issue by brahmaforces** [apollographql/apollo-client#6462]
**Intended outcome:**

I was trying to refetch a query after a mutation was run. However it is causing a CORS error. Whenever I run any queries or mutations otherwise, I never have any CORS issues. This issue only happens when I refetchQueries (while passing a variable as below, when a variable is not passed, again it works) So I dont think it is a CORS issue per se, otherwise I would have encountered it in other situations. 

`const id="1";
      
      //Mutation runs on submit to  signup user
      const [addleo, { loading, error }] = useMutation
      (
          ADDLEO,
      
          {
            **refetchQueries: [{query: LISTLEOS, variables: { id } }],**
            onError: (err) => {console.log("Leodeo Messaging: " + err)},
              
          } 
      )
  `

My Server file CORS configuration is:

`
//Allow cross-origin
app.use(
    cors({
      origin: 'http://localhost:3001',
      credentials: true
    })
  );

Client side configuration is:
`import {  ApolloProvider , ApolloClient, HttpLink, InMemoryCache } from '@apollo/client';

const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: new HttpLink({
    uri: 'http://localhost:5000/graphql',
    credentials: 'include'
  })
});
`

`
**Actual outcome:**

![image](https://user-images.githubusercontent.com/19621618/85132764-0f7d7300-b257-11ea-9a29-eaa75ed66329.png)

**How to reproduce the issue:**

**Versions**

npx envinfo@latest --preset apollo --clipboard
npx: installed 1 in 1.211s

  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Chrome: 83.0.4103.61

**Comment by brahmaforces** [comment]
It has taken me 2 weeks to sort this issue out, and I have finally found the solution. I am posting it here for others who might have this issue. 

I got the following the following 2 errors in my firefox console:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:5000/graphql. (Reason: CORS request did not succeed).
Uncaught (in promise) Error: Network error: NetworkError when attempting to fetch resource.

In my Chrome console I got the following errors:

httpLink.ts:134 POST http://localhost:5000/graphql net::ERR_CONNECTION_REFUSED
[Network error]: TypeError: Failed to fetch
ApolloError.ts:46 Uncaught (in promise) Error: Network error: Failed to fetch

I spent 2 weeks exploring CORS ,  Apollo Client  and Json-server CORS approaches to solving these issues. However to no avail. 

Finally I came upon this thread [](https://github.com/apollographql/apollo-client/issues/4004)

`Isn't this because your subscription initializes quicker than your backend can restart, try implementing a wait-port on your frontend so your front only reloads after the backend port is available? :)

Thanks for answering, but why would the backend restart? It's just a apollo server waiting for query from apollo client in my react app, isn't it?`

It turned out that the issue was a timing issue caused by Nodemon restarting the server everytime i made a client request. Dont ask me why it does that. 

In my package.json I had:

  "scripts": {
    "dev:server": "nodemon server.js",
    "json:server": "json-server --watch data.json --port 4000"
  },

I changed it to the following

  "scripts": {
    "dev:server": "node server.js",
    "json:server": "json-server --watch data.json --port 4000"
  },

essentially I got rid of nodemon and my Apollo-client refetchQueries works perfectly now!!

` //Mutation runs on submit to  signup user
      const [addleo, { loading, error}] = useMutation
      (
          ADDLEO,
          {
            refetchQueries: [{ query: ListLeos}],
            onError: (err) => {console.log("Leodeo Messaging: " + err)}
          } 
      )`


For anyone having issues with refetchQueries not working in Apollo-client, please ensure that you are not using nodemon to start your server, it totally messes up the refetchQueries functionality in Apollo-client!

Phew!!!Thank god almighty, it was a mighty small bug, that brought everything to a standstill for 2 weeks!

**Comment by deepakbhattmits** [comment]
Hi @brahmaforces 
I have followed the same approach but sometimes refetchQueries wroks well but some time this give me error like 

[Network error]: TypeError: Failed to fetch

could you please help me out on this.

**Comment by brahmaforces** [comment]
@deepakbhattmits , have you removed nodemon. That caused this error for me. Use node. Otherwise please share your CORs middleware setup, maybe it is misconfigured.

**Comment by hdngr** [comment]
Can confirm this is an issue with `apollo-lambda-server` when implementing `refetch` after a `mutation`
