### ISSUE TITLE
How i can CATCH any error (network and graphql), and prevent promise.reject() ?

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [apollographql/apollo-client#6469]
"apollo-client": "^2.6.10",
    "apollo-link": "^1.2.14",
    "apollo-link-error": "^1.1.13",

![image](https://user-images.githubusercontent.com/60403187/85216242-d1816b80-b38a-11ea-8e6e-5383e39e2cd7.png)

i Already can get Apollo Client errors:

```javascript
import {onError} from 'apollo-link-error'

function createLink() {
  return ApolloLink.from([
    createErrorLink(),
    createHttpLink(),
  ])
}

function createErrorLink() {
  return onError(function ({graphQLErrors, networkError}) {

    if (graphQLErrors) {
      graphQLErrors.map(({message}) => {
        console.log(`[GraphQL error]`, message)
      })
    }

    if (networkError) {
      console.log(`[Network error]`, networkError)
    }
    
  })
}
```

Yes, error handlers works, but how i can PREVENT promise rejection? 

The documentation says: 

```javascript
onError(function ({response}) {

  response.errors = null;

})
```

But it not prevent promise rejection, responseis undefined actually,  is a bug?

**Comment by gino8080** [comment]
please can you share your ApolloClient code?

I can't understand how to use onError link

`
import { ApolloClient, InMemoryCache, ApolloLink, HttpLink } from "@apollo/client";
import { onError, } from "@apollo/client/link/error";
const cache = new InMemoryCache();


const link = onError(({ graphQLErrors, networkError }) => {
  if (graphQLErrors)
    graphQLErrors.map(({ message, locations, path }) =>
      console.log(
        `[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`
      )
    );
  if (networkError) console.log(`[Network error]: ${networkError}`);
});

const url = `${process.env.REACT_APP_BACKEND_URL}/graphql`;
console.log("url", url)
const client = new ApolloClient({
  cache,
  link: new HttpLink({
    uri: url,

  })
});

export default client;

`
