### ISSUE TITLE
relayStylePagination creates totalCount MissingFieldError warning

### ISSUE THREAD

**Issue by mschipperheyn** [apollographql/apollo-client#6477]
**Intended outcome:**
I've been playing around with RC.7 and I'm getting a MissingFieldError for the `totalCount` key that we return on our connection queries. The reason is that totalCount is missing from the type definition. They keys for relay style pagination are 
```
edges
paginInfo
totalCount
```
totalCount is missing from the type.

**Actual outcome:**
Missing cache result fields: posts.totalCount [MissingFieldError]

The data is in fact successfully returned.

**How to reproduce the issue:**

create a type 
```
query (
    $before: String
    $after: String
) {
    posts(
        after: $after
        before: $before
    ) {
        edges {
            node {
                ...postFragment
            }
        }
        pageInfo {
            ... on Page {
                hasNextPage
                hasPreviousPage
                pageSize
            }
            ... on PageInfoInt {
                page
            }
            ... on PageInfoCursor {
                startCursor
                endCursor
            }
        }
        totalCount
    }
}
```

and query for totalCount.

**Versions**
RC.7

**Comment by benjamn** [comment]
Ahh, I was going off of https://relay.dev/graphql/connections.htm, which makes no mention of `totalCount`. Do you have a link to more recent documentation/spec?

**Comment by benjamn** [comment]
Hmm, it looks like they intentionally left it out of the spec, since not every collection can easily provide a `totalCount`: https://github.com/graphql/graphql-relay-js/pull/109#issuecomment-267734541

**Comment by benjamn** [comment]
I would also have thought that [this code](https://github.com/apollographql/apollo-client/blob/b9b04c20896b94bcac726b208444b58f841c2e5c/src/utilities/policies/pagination.ts#L122-L127) would end up storing any `incoming.totalCount` that comes back from the server. If you're trying to query the cache without having written any server data, there's no way for the cache to give you a useful `totalCount` (and so the `MissingFieldError` seems appropriate).

**Comment by benjamn** [comment]
Turns out I forgot to return the extra fields from the `read` function: #6479

Thanks for helping test this new functionality @mschipperheyn!
