### ISSUE TITLE
Apollo Client V3 Delete cache items after period of time

### ISSUE THREAD

**Issue by hwhh** [apollographql/apollo-client#6484]
Is there is a way to expire cached items after a certain time period, e.g., 24 hours.

I know that Apollo Client v3 provides methods such as cache.evict and cache.gc which are a good start and I am already using; however, I want a way to delete cache items after a given time period.

What I am doing at the minute is adding a TimeToLive field to every object in my Apollo schema, and when the backend returns an object, the field is populated with the current time + 24 hours (i.e. the time in 24 hours time). Then when I query the data in the front end, I check the to see if the TimeToLive field of the returned data is in the future (if not that means the data was definitely retrieved from the cache and in which case I call the re-fetch function, which forces the query to fetch the data from the server. However, this doesn't seem like the best way to do things, mainly because I have to iterate over every result in the returned data and check if any of the returned objects are expired; and if so, everything is re-fetched.

Another solution I thought of was to use something like React Native Queue and have a background task that periodically checks the cache and deletes items that have expired. But again, I am not totally sold on this solution.

For a little bit of context here: I am building a cooking/recipes app - and recipes/posts are cached on the device; however, my concern is that a user could delete a post, but everyone else who has that post cached would still be able to see it, and hence by expiring the cached item at least they would only be able to see for a number of hours before it is removed. However they might be a better way to do this all together, i.e. have the sever contact clients with the cached item (though I couldn't think of any low lift solutions at the time of writing this)

As a side note are there cache replacement strategies one can use, i.e least recently used?

**Comment by benjamn** [comment]
Are you persisting the cache to longer-term local storage (e.g. using https://github.com/apollographql/apollo-cache-persist, `localStorage`, `IndexedDB`, `asyncStorage`)? Maybe that layer could take some responsibility for expiration?

On the `InMemoryCache` side, I definitely think there's room for the `cache.gc` method to take additional parameters, enabling more aggressive pruning based on criteria other than reachability.

**Comment by hwhh** [comment]
Hi @benjamn, 

I persisting the cache to asyncStorage using apollo-cache-persist, have commented on an old issue in that repo too but definitely agree it would be great to provide additional parameters to the `cache.gc` method!

**Comment by JesseZomer** [comment]
Also interested in this feature

**Comment by xplatsolutions** [comment]
I was looking at how to do this since many times you have data you don't control or know when to evict and found this [article](https://www.assurantlabs.com/blog/2020/07/20/cache-expiration-in-apollo-graphql-using-react-hooks/), I hope it is useful to others here.
