### ISSUE TITLE
useQuery and useMutation onError callback acts differently with errorPolicy set to 'all' 

### ISSUE THREAD

**Issue by tomerzcod7** [apollographql/apollo-client#6492]
**Intended outcome:**
From my understanding, when errorPolicy is set to 'all', GraphQL errors shouldn't throw rejections on Apollo-client (and thus triggering the onError callback). The result object should include partial data and GraphQL error data. Only Network Error should actually reject on call the onError.
  
**Actual outcome:**
This is working properly for useMutation. However, useQuery with errorPolicy set to 'all' still fires the onError callback when a GraphQL error occurs, making it extremely hard to handle errors properly.

**How to reproduce the issue:**
useMutation which behaves as expected (not firing onError on GraphQL errors):
```js
const [requestResetPassword, { loading }] = useMutation(
    REQUEST_RESET_PASSWORD,
    {
      client: usersClient,
      onCompleted: (data) =>
        data
          ? dispatch({ type: 'REQUEST_SUCCESS' })
          : dispatch({ type: 'INCORRECT_EMAIL' }),
      onError: setNetworkError,
      errorPolicy: 'all',
    },
);
```

useQuery which fires onError for all errors even tho errorPolicy is set to 'all':
```js
const { loading } = useQuery(VALIDATE_RESET_PASSWORD_TOKEN, {
    variables: { userId, token },
    client: usersClient,
    onCompleted: (data) => {
      console.log(data);

      (!data || !data.validateResetPasswordToken) &&
        history.replace('/forgot-password', {
          tokenInvalid: true,
        });
    },
    errorPolicy: 'all',
    onError: setNetworkError,
  });
```

**Versions**
System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
  Binaries:
    Node: 14.4.0 - /usr/bin/node
    npm: 6.14.5 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 83.0.4103.106
    Firefox: 77.0.1
  npmPackages:
    @apollo/client: ^3.0.0-beta.43 => 3.0.0-beta.43 
    @apollo/link-error: ^2.0.0-beta.3 => 2.0.0-beta.3 
    apollo-link-schema: ^1.2.5 => 1.2.5 
  npmGlobalPackages:
    apollo: 2.27.0

**Comment by alex20465** [comment]
I use `ApolloReactHoc.withMutation`, the HOC still ignores the options:
```
    withUpdateProduct({
        options: (props: OuterProps) => ({
            errorPolicy: "all",
            refetchQueries: [
                {
                    query: GetProductDocument,
                    variables: {
                        id: props.id
                    }
                }
            ]
        })
    })
```

![image](https://user-images.githubusercontent.com/4742067/86133931-a7018200-baf1-11ea-96ec-ecbaf6e97ab3.png)

The HOC have in general continuously configuration issues and misbehaviours, like for example the refetchQueries also don't trigger the `data.refetch`, its hard to work with it.

**Comment by hwillson** [comment]
This should no longer be an issue in `@apollo/client@latest` - let us know otherwise, thanks!

**Comment by soumithrib** [comment]
This is still an issue in latest @hwillson

**Comment by alessbell** [comment]
Hi @soumithrib 👋 Would you be able to share a runnable reproduction I can take a look at?
