### ISSUE TITLE
Support concat loading on relayStylePagination

### ISSUE THREAD

**Issue by mschipperheyn** [apollographql/apollo-client#6494]
relayStylePagination currently (rc.9) only supports replace style more loading. 
I would argue that cursor based more loading lends itself better to endless list style loading. 

Perhaps it would be possible add a `concat = true` as an option to `relayStylePagination`? and concat or replace the resulting edges accordingly?

I was thinking something like this:

```
export function relayStylePagination(
	keyArgs,
	opts = {
		concat: true,
		reverse: false,
	},
) {
[...]
    let edges;
    if (opts.concat) {
        edges = opts.reverse
            ? [...prefix, ...incomingEdges, ...existing.edges, ...suffix]
            : [...prefix, ...existing.edges, ...incomingEdges, ...suffix];
    } else {
        edges = [...prefix, ...incomingEdges, ...suffix];
    }

    const pageInfo = {
        ...incoming.pageInfo,
        ...existing.pageInfo,
        startCursor: opts.reverse
            ? edges[edges.length - 1]?.cursor
            : edges[0]?.cursor,
        endCursor: opts.reverse
            ? edges[0]?.cursor
            : edges[edges.length - 1]?.cursor,
    };
```

**Comment by benjamn** [comment]
What sort of query and variables/arguments would you use for concat/endless-list loading? I would have thought that you would just load each additional page using the `pageInfo.endCursor` from the previous result. Do you want to avoid having to pass the cursor, or something?

**Comment by mschipperheyn** [comment]
Hi, I think I might have misunderstood how prefixes and suffixes work. Still playing around with it ;-). But what I essentially want to be able to do is deal with all our load more / infinite list scenarios. This is what the concat is about.
 
Our default is latest first, but some lists are latest last (e.g. chat). And in case of latest last, the resulting "load more" will be loaded either at the top, in case you're scrolling to the past or at the bottom, when new messages come in

**Comment by benjamn** [comment]
I think the `relayStylePagination` helper will concatenate new results in most cases, so it shouldn't be necessary to have a special concat mode. Please feel free to reopen this issue or continue the discussion as you find out more.

**Comment by sebastienbarre** [comment]
@benjamn I'm experiencing that too. 

One small issue is with the documentation itself: https://www.apollographql.com/docs/react/pagination/cursor-based/#relay-style-cursor-pagination. 

It is unclear what the example produces, it probably should be stated explicitly. The code has:
```
  const nodes = data.comments.edges.map((edge) => edge.node);
  const pageInfo = data.comments.pageInfo;
```
Does it mean that after triggering `onLoadMore()` then `nodes` contains the *next* page only (after `pageInfo.endCursor`), or does it contain *all the previously fetched data* AND the next page.

The doc later says "Note that the relayStylePagination function generates a field policy with a read function that simply returns all available data, ignoring args", which would hint at the latter situation... but it doesn't seem to be the case.
