### ISSUE TITLE
How to get request body onError for Sentry

### ISSUE THREAD

**Issue by shinaBR2** [apollographql/apollo-client#6500]
Hi everyone,
I'm using Apollo-client and has integrated [Sentry](https://sentry.io/) into `onError` of Apollo-client.
![image](https://user-images.githubusercontent.com/8222892/85925033-30317280-b8c0-11ea-9629-d14c98a6d988.png)
This is example for an error Query with `graphQLErrors` only give me short message.
How can I get the exactly Query string to be shown in Sentry? It does not make sense if I just only know the message but totally don't have any idea about "what query cause this error".
Thanks for keep moving up for this awesome library.

**Comment by dusty** [comment]
Something like this should work.

```
const errorHandler = onError(({ graphQLErrors, networkError }) => {
  if (graphQLErrors) {
    graphQLErrors.forEach(err => {
      console.error(err.message)
      Sentry.captureException(err)
      Sentry.addBreadcrumb({
        category: 'graphQLError',
        message: err.message,
        level: Sentry.Severity.Warning
      })
    })
  }
  if (networkError) {
    console.error(networkError.message)
    Sentry.captureException(networkError)
    Sentry.addBreadcrumb({
      category: 'networkError',
      message: networkError.message,
      level: Sentry.Severity.Error
    })
  }
})
```

**Comment by dusty** [comment]
apollo-link-error gives you the operation which you could pass to Sentry.

```
const errorHandler = onError(({ operation, graphQLErrors, networkError }) => {
  console.log(operation)
  // send to sentry
})

https://www.apollographql.com/docs/link/links/error/

**Comment by dusty** [comment]
ie: you could use `operation.query.loc.source.body` to get the full query string that was sent.

**Comment by dusty** [comment]
I also found print from graphql lib

```
import { print } from 'graphql/language/printer'

const errorHandler = onError(({ operation, graphQLErrors, networkError }) => {
  const query = print(operation.query)
  console.log(query)
  // send to sentry
})
```

**Comment by shinaBR2** [comment]
@dusty thanks, `print` looks can help.
I saw that we can get query from `operation.query.loc.source.body` but not sure if it safe or not. Of course we can check to make sure no `can not read property loc of undefined`  or so, but somehow very verbose.

**Comment by dusty** [comment]
Ya, I hear you on that.  If you have support for optional chaining, you could use that `operation?.query?.loc?.source?.body`.  Or there are other helpers out their like dlv https://github.com/developit/dlv or lodash's get method https://lodash.com/docs/4.17.15#get.   But, print seems nice for this problem.

**Comment by shinaBR2** [comment]
@dusty thanks for your help.

The `print` method will give us an result like below (actually the query)

```
{
  meme(where: {id: "cjke2xlf9nhd90953khilyzja"}) {
    photo {
      url(transformation: {image: {resize: {width: 600, height: 600, fit: crop}}})
      __typename
    }
    __typename
  }
}
```

For who has same problem, just `JSON.stringify` and send to Sentry. I close this issue now.
