### ISSUE TITLE
typePolicy relayStylePagination allows (illegal) undefined startCursor and endCursor

### ISSUE THREAD

**Issue by mschipperheyn** [apollographql/apollo-client#6501]
The relay style pagination specifies an `undefined` `pageInfo.startCursor` or `pageInfo.endCursor` as an empty string. It's a required field. However, if your edges are empty
https://github.com/apollographql/apollo-client/blob/master/src/utilities/policies/pagination.ts#L74
will result in it being `undefined`.

I haven't fully traced the root, but when I change to
```
          startCursor: edges[0]?.cursor || '',
          endCursor: edges[edges.length - 1]?.cursor || '',
```
the problem goes away.

**Intended outcome:**
`undefined` `startCursor` and `endCursor` should be an empty string.

**Actual outcome:**
it's `undefined`. 
This results in a `MissingField` warning and in my case to a recursive loop (prob specific to my env).

**How to reproduce the issue:**
read a pageInfo with `startCursor` and `endCursor`
return a result with 
```
   edges: []
   pageInfo: {
       startCursor: '',
       hasNextPage: false,
       hasPreviousPage: false,
       pageSize: 12,
       endCursor: ''
   }
```

**Versions**
rc.9

**Comment by benjamn** [comment]
Thanks @mschipperheyn! This will be fixed in the next RC.
