### ISSUE TITLE
How to disable cache normalized v3.0beta?

### ISSUE THREAD

**Issue by ITSWYoo** [apollographql/apollo-client#6509]
I want to all disable cache
at v2.x -> dataIdFromObject(obj) => null
but 3.0 
```js
typePolicies: {
    Product: {
      keyFields:false,
    },
    Person: {
      keyFields: false,
    },
    Book: {
      keyFields: false,
    },
  },
```
can i disable all keyFields ?

**Comment by benjamn** [comment]
You can still pass your own `dataIdFromObject` to the `InMemoryCache` constructor, as a catch-all for any types not mentioned in your `typePolicies`.

Now might be a good time to revisit why you think you want to disable normalization, though. Data duplication is the enemy of a coherent client-side data graph.

**Comment by cglacet** [comment]
> Now might be a good time to revisit why you think you want to disable normalization

@benjamn Not sure it's a good reason, but some server side tools already append `__typename` on their `id` field. I don't know the relay standard  well so I have no idea who is responsible for this, but as a novice, having this on the server side or the client side doesn't make a lot of difference to me. (note that having ID's of the form "User:User:xxx" would just bring confusion)

Any advice concerning this question (server vs. client)?
