### ISSUE TITLE
Is there a way to configure an afterware with apollo-boost?

### ISSUE THREAD

**Issue by jplindgren** [apollographql/apollo-client#6513]
I am a little confused by the apollo docs, but looking for help on SO and here if I understood correctly the apollo-boost changed the way we can provide a middleware to apply auth token to apollo-client from:

```
const authMiddleware = new ApolloLink((operation, forward) => {
  // add the authorization to the headers
  operation.setContext({
    headers: {
      authorization: localStorage.getItem('token') || null,
    }
  });

  return forward(operation);
});

const client = new ApolloClient({
  link: concat(authMiddleware, httpLink),
});   
```

to something like

```
const apolloClient = new ApolloClient({
  uri: 'https://mysite/graphql',
  request: (operation) => {
    const token = localStorage.getItem('token')
    operation.setContext({
      headers: {
        authorization: token ? `Bearer ${token}` : ''
      }
    })
  }
})
```

I was able to implement my feature doing this way. 
But now, I need to implement some custom behavior in the response. I did not find an option to create a function to customize the response (or add an "afterware") on ApolloClient. Does this feature not exists on Apollo-Boost or am I missing something?
Thank you.

**Comment by dpacmittal** [comment]
I just tried this and it works:

```javascript
import ApolloClient, { InMemoryCache } from 'apollo-boost';
import fetch from 'isomorphic-unfetch';
const fakeFetch = async (input, init) => {
  const promise = fetch(input, init);
  promise.then(data => {
    // Process response here...
  });
  return promise;
};

export const graphqlClient = new ApolloClient({
  uri: 'https://example.com/graphql',
  cache: new InMemoryCache(),
  fetch: fakeFetch,
});
```

**Comment by hwillson** [comment]
Please refer to the [Advanced HTTP networking](https://www.apollographql.com/docs/react/networking/advanced-http-networking/) section of the docs. Thanks!
