### ISSUE TITLE
Slow performace

### ISSUE THREAD

**Issue by vikas115m** [apollographql/apollo-client#6523]
Hi Team,

We are invoking the below code from spring batch which uses executor service

                         testQuery testQuery = testQueryQuery
				.builder()
				.requestData(testQuery)
				.build();

		Response<Optional<Data>> response = Rx2Apollo.from(apolloClient.query(testQuery)
				
				.blockingFirst();`

The seems to be very slow where the I tried to call the same service from HttpClient and it was very fast

Apolloclient and OkHttp instances are singleton as suggested in the docs

Could some one please help me on this ?

**Comment by hwillson** [comment]
This question is better asked in the https://github.com/apollographql/apollo-android repo. Thanks!
