### ISSUE TITLE
When execute useQuery several times same schema with different fields at the same page occurs infinite request loop 

### ISSUE THREAD

**Issue by reumia** [apollographql/apollo-client#6529]
**Intended outcome:**
```tsx
const StoreNameQuery = gql`
  store {
    storeName
  }
`

const StoreProductsQuery = gql`
  store {
    products {
      id
    }
  }
`
```

```tsx
const Parent = () => {
  const {data, error} = useQuery(StoreNameQuery)
  if (!data || error) return null
  return (
    <div>
      <h1>{data.store.storeName}</h1>
      <Child />
    </div>
  )
}

const Child = () => {
  const {data, error} = useQuery(StoreProductsQuery)
  if (!data || error) return null
  return (
    // do something with data
  )
}
```

I'm not sure that it could be a bug, and it's provably because of my misunderstood but anyway, 
I expected work properly because any queries could be request several times in a single page with different fileds.

**Actual outcome:**

This occurs infinite request loop.

![image](https://user-images.githubusercontent.com/5867454/86318733-b7d70280-bc6d-11ea-8f80-8a55fbe404b1.png)

**How to reproduce the issue:**

Wrote in a previous section.

**Versions**

```shell
  System:
    OS: macOS 10.15.5
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.1/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 74.0
    Safari: 13.1.1
  npmPackages:
    @apollo/client: ^3.0.0-rc.4 => 3.0.0-rc.4 
    @apollo/link-context: ^2.0.0-beta.3 => 2.0.0-beta.3 
    @apollo/link-error: ^2.0.0-beta.3 => 2.0.0-beta.3 
  npmGlobalPackages:
    apollo: 2.28.3
```

**Comment by reumia** [comment]
https://github.com/reumia/react-apollo-error-template/tree/feature/reumia/request-with-different-field-infinite-loop-test

I tested this problem with `react-apollo-error-templae` repository and it doen't happen.
It seems to be because of environment of my project.

**Comment by ivands** [comment]
Why did it happen tho? I have the same problem
