### ISSUE TITLE
Cache not notifying query on change

### ISSUE THREAD

**Issue by donkeyDau** [apollographql/apollo-client#6531]
Hi,

I'm trying to write a generic local state resolver for creating different entities with different fields e.g. a (hydro/thermal/... plant).

My client definition looks like this:
```
const client = new ApolloClient({
  uri: `https://graphql.anilist.co`,
  cache,
  resolvers: {
    Query: {
      getEntity(
        parent,
        {
          input: { entityType }
        },
        { cache },
        info
      ) {
        const query = getQuery(info, entityType);

        const cachedEntities = cache.readQuery({
          query
        });

        return cachedEntities[entityType];
      }
    },

    Mutation: {
      createEntity: (
        _,
        { entityType, scenarioId, details },
        { cache, client: apolloClient },
        info
      ) => {
        const query = getQuery(info, entityType, true);

        const cachedEntities = cache.readQuery({
          query
        });

        const newEntities = [...cachedEntities[entityType]];
        const newEntity = {
          ...details,
          scenarioId,
          [`${entityType}Id`]: cuid(),
          __typename: typenames[entityType]
        };

        newEntities.push(newEntity);

        cache.writeData({
          data: { [entityType]: newEntities }
        });
        console.log("Done");
        return null;
      }
    }
  }
});
```
When adding a new entity to the cache I end up with this:
![grafik](https://user-images.githubusercontent.com/17231336/86365047-47ce7980-bc79-11ea-9442-ac8c8fdd22cf.png)

Data is in the cache. On the left: Two Hydro entities. On the right (in the ROOT_QUERY) you can see the generic hydro query/cache and the `getEntities` query. But the `getEntities` query is not updated. If I trigger a manual `refetch` on the query it'll work. But the main advantage of the cache is not played: triggering a re-render on the component with an active query on `getEntities` ...

I'm using the following setup:

```
"apollo-cache-inmemory": "^1.6.6",
"react-apollo": "^2.5.8",
"apollo-boost": "^0.4.9"
```

A sandbox is created at https://codesandbox.io/s/interesting-newton-pl05c?file=/src/App.js

**Comment by tpoppen** [comment]
I am also experiencing this issue in `"@apollo/client": "3.0.0-beta.45"` using both hooks and components from `"@apollo/react-components": "^4.0.0-beta.1"`.

**Comment by tpoppen** [comment]
@benjamn Is there a milestone for the `@apollo/client`'s next release that this could make it into as well?

**Comment by hwillson** [comment]
This should no longer be an issue in `@apollo/client@latest` - let us know otherwise, thanks!
