### ISSUE TITLE
remove React as peer dependency

### ISSUE THREAD

**Issue by finsec-dz** [apollographql/apollo-client#6532]
**Intended outcome:**
Installing `@apollo/client` should not not display warnings of missing dependencies.

**Actual outcome:**
```bash
npm WARN @apollo/client@3.0.0-rc.10 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
```

As per the [migrating to v3 docs](https://www.apollographql.com/docs/react/v3.0-beta/migrating/apollo-client-3-migration/#using-apollo-client-without-react), `@apollo/client` can be used without `React` by importing from `@apollo/client/core`.

For projects NOT using `React` it should not be a required dependency. 
I'm currently using it in an `Angular` project and the warnings should not be displayed. 

**How to reproduce the issue:**

1. Init a new project: `npm init`
2. Install `@apollo/client`: `npm i @apollo/client`

**Versions**

@apollo/client@3.0.0-rc.10

**Comment by jonathonadams** [comment]
Any word from the Apollo team on this?

**Comment by Ksan8** [comment]
Related to this, I'm having trouble using `useReactiveVar` in Apollo Angular, as it gives missing React peer dependency warnings when imported from `@apollo/client`. If I try to import it from `@apollo/client/core`, as is recommended for other imports such as `ApolloQueryResult`, it cannot be found in that module. Is it just not available for non-React projects?

```
// this results in compiler warnings about missing React dependencies
import { ApolloQueryResult, useReactiveVar } from '@apollo/client';

// this gets rid of the compiler warnings, but useReactiveVar cannot be found
import { ApolloQueryResult, useReactiveVar } from '@apollo/client/core';
```

**Versions**

```
"@angular/[multiple packages]": "~10.2.0"
"@apollo/client": "^3.2.5",
"apollo-angular": "^2.0.4",
```

**Comment by alessbell** [comment]
@finsec-dz you should no longer see the peer dependency warning for `react` when installing `@apollo/client@^3.0.0` with npm v7/v8, yarn v1/v2 or pnpm v6/7 (and likely earlier versions, but docs only exist for the last two major versions of pnpm). 

Given the date of this issue's creation, I'm wondering if you were using npm@v6 at the time which does not support `peerDependenciesMeta` in `package.json` which we use to identify the `react` peer dependency as optional.

Here are some screenshots of the terminal output of `npm`/`yarn`/`pnpm install` running node v16.15.0:

### npm v8.10.0
No complaints
<img width="941" alt="Screen Shot 2022-06-21 at 3 48 04 PM" src="https://user-images.githubusercontent.com/5139846/175063102-090ca975-29cf-42c0-bfa5-f2dcee691963.png">

### yarn v1.22.19
Some warnings about react-scripts peer dependencies but nothing from @apollo/client
<img width="945" alt="Screen Shot 2022-06-21 at 3 47 43 PM" src="https://user-images.githubusercontent.com/5139846/175063172-7a318380-8660-4405-8f95-5823c67f7dbe.png">

### pnpm v7.3.0
Note warnings for missing peer deps of two packages (`react-app-rewired` and `stats-webpack-plugin` but not `@apollo/client`
<img width="901" alt="Screen Shot 2022-06-21 at 3 56 03 PM" src="https://user-images.githubusercontent.com/5139846/175063225-6ce9e9af-6672-4468-99e9-9b1cf893dab4.png">

I'm going to close this issue for now, but please don't hesitate to re-open or create a new issue if you observe behavior that is not described above. Thanks!
