### ISSUE TITLE
Embedded types do not appear in mock responses to client

### ISSUE THREAD

**Issue by solidprinciples** [apollographql/apollo-client#6533]
Upon mocking queries, I noticed some information is not coming through in the query (these are not reserved words/otherwise). I am including __typename within each type - but the other properties in the underlying embedded types are not present when the mock is resolved. The general schema structure is as below:

**Intended outcome:**
```
data: {
  fooBarBaz: [
    {
      __typename: 'Foo',
      id: 'FooBaz1',
      barBaz: { __typename: 'FooBaz', baz: 'Foo' }
    },
    {
      __typename: 'Foo',
      id: 'FooBar1',
      barBaz: { __typename: 'FooBar', bar: 'Foo' }
    }
  ]
}
```

Mocking a query for testing purposes, with an embedded other GraphQL type inside of it - I only get the `__typename`, no internal properties, which breaks elements that utilize the internal elements (undefined).

**Actual outcome:**

```
data: {
  fooBarBaz: [
    {
      __typename: 'Foo',
      id: 'FooBaz1',
      barBaz: { __typename: 'FooBaz' } <-- Where is type baz
    },
    {
      __typename: 'Foo',
      id: 'FooBar1',
      barBaz: { __typename: 'FooBar' } <-- Where is type bar
    }
  ]
}
```

**How to reproduce the issue:**

Create a "Foo" type with "Bar" inside, in my case "Bar" can be of type "FooBar" or "BarBaz", for instance - each with distinct properties, i.e - fooBar or barBaz. The underlying types in my case do not show up in the mocked query. The names in the actual code differ, but the premise is the same - the underlying types only have `__typename`, no other properties that were included in the original mock...

**Versions**

  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @apollo/client: ^3.0.0-rc.10 => 3.0.0-rc.10

**Comment by solidprinciples** [comment]
I have also made an example to help

GraphQL server:
```
type Query {
  fooBarBaz: [Foo]!
}

type Foo {
    id: ID!
    barBaz: BarBaz
}

type FooBar {
    id: ID!
    bar: String
}

type FooBaz {
    id: ID!
    baz: String
}

union BarBaz = FooBar | FooBaz 
```

Client Query & Fragments:
```
fragment FooBar on FooBar {
    id
    bar
}

fragment FooBaz on FooBaz {
    id
    baz
}

fragment BarBaz on BarBaz {
    ...FooBar
    ...FooBaz
}

fragment Foo on Foo {
    id
    barBaz { ...BarBaz }
}

query FooBarBaz {
    fooBarBaz {
        ...Foo
    }
}
```

Mocked Request:
```
function mockFoo(): MockedResponse {
    return {
        request: {
            query: FooBarBazDocument
        },
        result: {
            data: {
                fooBarBaz: [
                    {
                        __typename: 'Foo',
                        id: 'FooBaz1',
                        barBaz: {
                            id: 'FooBaz1',
                            __typename: 'FooBaz',
                            baz: 'what'
                        }
                    },
                    {
                        __typename: 'Foo',
                        id: 'FooBar1',
                        barBaz: {
                            id: 'FooBar1',
                            __typename: 'FooBar',
                            baz: 'the'
                        }
                    }
                ]
            }
        }
    };
}
```

Client Received:
```
data: {
  fooBarBaz: [
    {
      __typename: 'Foo',
      id: 'FooBaz1',
      barBaz: { __typename: 'FooBaz' } <-- Where is type baz
    },
    {
      __typename: 'Foo',
      id: 'FooBar1',
      barBaz: { __typename: 'FooBar' } <-- Where is type bar
    }
  ]
}
```

**Comment by tell-y** [comment]
I was also confused by fragments with unions.
I hope this helps your problem.
https://www.apollographql.com/docs/react/data/fragments/#defining-possibletypes-manually

**Comment by hwillson** [comment]
We'll need a runnable reproduction (using `@apollo/client@latest`) to be able to troubleshoot this further. Thanks!
