### ISSUE TITLE
Local resolvers (@client fields) performance too low; browser hangs

### ISSUE THREAD

**Issue by codelizrd** [apollographql/apollo-client#6536]
Hi,

I have an extensive GraphQL schema, but I want to enrich it using data stored in the browser's window.localStorage. In more detail, I have created:

```
extend type Ticket {
    lastViewed: String
}

extend type Mutation {
    ticketSetLastViewed(ticketId: String!, lastViewed: String!): Ticket!
}
```

I create a new `ApolloClient` instance using the `resolvers`-option, something like:

```
{
        Ticket: {
            lastViewed: (ticket: { id: string }) => 'it works!'
        }
}
```

My query:

```
query TicketList {
        ticketList {
                id
                title
                lastViewed @client
        }
}
```

This works: the query result data items contain a 'lastViewed' property with the value 'it works!'.

However: the performance is terrible. The list returns 400 tickets, and after the XHR request from the server finishes the browser hangs for 5 to 8 seconds; inspecting the code within a debugger reveals it is working on resolving the `@client` field. Omitting this field in the query yields perfect response times and no browser hangs.
It should take less time; the current implementation is too slow to be usable.

As my project is based on CRA, I also checked the build-version, which has the same performance issue. 

**Versions**
```
  System:
    OS: macOS 10.15.5
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Safari: 13.1.1
  npmPackages:
    @apollo/react-testing: 3.1.4 => 3.1.4 
    apollo-cache-inmemory: 1.6.6 => 1.6.6 
    apollo-cache-persist: ^0.1.1 => 0.1.1 
    apollo-client: 2.6.10 => 2.6.10 
    apollo-link: 1.2.14 => 1.2.14 
    apollo-link-context: 1.0.20 => 1.0.20 
    apollo-link-error: 1.1.13 => 1.1.13 
    apollo-link-http: 1.5.17 => 1.5.17 
    apollo-upload-client: 13.0.0 => 13.0.0 
    apollo-utilities: 1.3.4 => 1.3.4 
    react-apollo: 3.1.5 => 3.1.5 
```

**Comment by mindnektar** [comment]
I can confirm this. I have just spent a day removing all @client directives from our code base and replacing them with a local/session storage alternative. The performance gain was tremendous (4-5x faster render times). I would suggest at the very least documenting a warning somewhere.

**Comment by benjamn** [comment]
I'm honestly surprised this hasn't been a more frequent complaint, given the architecture of local resolver functions (duplicate traversal of the query, plus extra async pauses for every resolver function). That's why we're hoping to move away from local resolver functions in Apollo Client 3.x. The new [field policy API](https://www.apollographql.com/docs/react/caching/cache-field-behavior/) do not have the same performance characteristics, and we've already seen customers report substantial performance improvements (on the order of 5x) by migrating from local resolvers to field policies.

**Comment by codelizrd** [comment]
I migrated my code to v3, and ditched the deprecated local resolver structure in favor of reactive variables; works like a charm. I guess a warning in the documentation should be fair, though people should migrate away from local resolvers.
