### ISSUE TITLE
@apollo/client/testing has no exported member 'MockedProviderProps'

### ISSUE THREAD

**Issue by WillSquire** [apollographql/apollo-client#6539]
Getting the error `@apollo/client/testing has no exported member 'MockedProviderProps'` when trying to import `MockedProviderProps` in @apollo/client 3.0.0-rc.10 like so:

```ts
import { MockedProviderProps } from '@apollo/client/testing'
```

This used to work in previous versions.

If anyone else has this problem, this is a workaround: `React.FC<React.ComponentProps<typeof MockedProvider>>`

**Comment by ecbrodie** [comment]
I also experienced this problem when upgrading my app, which was using apollo-boost, to use Apollo Client v3. My app used the `MockedProviderProps` interface for a variety of reasons (for example, to pull out the type of the `mocks` object for our own type interfaces).

The workaround I chose was to import the interface direct from the `MockedProvider` component's type definition file:

```ts
import { MockedProvider } from "@apollo/client/testing"
import { MockedProviderProps } from "@apollo/client/utilities/testing/mocking/MockedProvider"
```

This isn't a solution that I am in love with. Ideally, I can import the interface from the same location as `MockedProvider`, which I was able to do before:

```ts
import { MockedProvider, MockedProviderProps } from "@apollo/react-testing"
```
