### ISSUE TITLE
@apollo/client/testing has no exported member 'ResultFunction'

### ISSUE THREAD

**Issue by WillSquire** [apollographql/apollo-client#6540]
Getting the error `@apollo/client/testing has no exported member 'ResultFunction'` when trying to import `ResultFunction` in @apollo/client 3.0.0-rc.10 like so:

```ts
import { ResultFunction } from '@apollo/client/testing'
```

It's trivial to recreate `type ResultFunction<T> = () => T`, but it is a regression.

**Comment by hwillson** [comment]
Fixed in https://github.com/apollographql/apollo-client/pull/8315 and will be released with 3.4 shortly. Thanks!
