### ISSUE TITLE
FetchMore does not update networkStatus in Apollo client 3 (new version)

### ISSUE THREAD

**Issue by sadraromexs** [apollographql/apollo-client#6542]
Hi
Apollo client in new version has a problem
Apollo client 3 does not send initial networkStatus code. it just send only returned 7 status code.
in previous version like beta or 2.6 that was OK but in this new version this problem created.

### Expected Behavior
send networkStatus code **"3"** when clicking on fetchMore button.

### Current Behavior
when click on fetchMore button noting send at all. just return networkStatus **"7"** in the end.

### Apollo Client Version 
^3.0.0-rc.10

![image](https://user-images.githubusercontent.com/48912836/86524022-4627d000-be8a-11ea-84ea-f8fc92b0c43e.png)
 
![image](https://user-images.githubusercontent.com/48912836/86524056-d9610580-be8a-11ea-8f63-d2d3a2a72269.png)

### I Wrote SImple Code to Show Problem in Codesandbox
https://codesandbox.io/s/apolloclient-3-local-state-management-before-reactive-variables-bdpnf?file=/src/App.js

![image](https://user-images.githubusercontent.com/48912836/86524446-14196c80-be90-11ea-9510-2c480e0079e6.png)
so here when we click on fetchMore Button nothing happens

![image](https://user-images.githubusercontent.com/48912836/86524476-55118100-be90-11ea-9287-c0e45059ed93.png)
but when we click on fetchMore button to reFetch data, networkStatus working fine and sending **"4"** networkStatus code

**Comment by benjamn** [comment]
This is a known problem, originally reported in #6354. Let's keep the discussion going over there.
