### ISSUE TITLE
cache.evict not updating cache for MockedProvider

### ISSUE THREAD

**Issue by WillSquire** [apollographql/apollo-client#6547]
**Intended outcome:**
With the following update function I'd expect `MockedProvider` to update `Something` lists to remove the removed item:
```ts
{
  update: (cache, { data }) => {
    if (isNil(data)) return

    const ref = cache.identify(data.removeSomething)
    cache.evict({ id: ref })
    cache.gc()
  },
}
```

**Actual outcome:**
Whilst it removes the item outside of tests, inside of tests the query never updates to remove the item. It does return `true` for `cache.evict`, but it also returns empty for `cache.gc` (and the live version does not return empty as the query has a child object on one of the fields). Not sure if the `cache.gc` should be a separate issue or related.

**Versions**
@apollo/client: 3.0.0-rc.10

**Comment by hwillson** [comment]
This should no longer be an issue in `@apollo/client@latest` - let us know otherwise, thanks!
