### ISSUE TITLE
Initial State being set multiple times

### ISSUE THREAD

**Issue by chrisbell08** [apollographql/apollo-client#6555]
So I think this is a bug but it may be that I'm not initializing the default state correctly.

**Intended outcome:**
The values of the local state should be set on page load and then changed to new values with events that run. For example, I have a ReactPlayer component that fires a ready event when a video is loaded.

**Actual outcome:**
The initial values are set correctly, then once the ready event fires from the ReactPlayer component the values in the state are updated correctly. However, they are then reset straight back to the initial page load values.

Updating the local state via button clicks work fine it's just when it fires via an event that can be dispatched early into the page load.

**How to reproduce the issue:**
Player Component
````JS
 console.log('Duration is' + duration);
<ReactPlayer
        key={id}
        controls={false}
        onReady={ () => updatePlayer('ready', true) }
        className={styles.player}
        ref={ref => (mediaPlayer = ref)}
        width="100%"
        height="100%"
        playing={playing}
        onPlay={ () => updatePlayer('playing', true) }
        onPause={ () => updatePlayer('playing', false) }
        onDuration={ (duration) => updatePlayer('duration', duration) }
        onProgress={ ({playedSeconds}) => updatePlayer('playedSeconds', playedSeconds) }
        url={ getVideoUrl(media) }
        muted={muted}
      />
````

Apollo Config
````JS
const cache = new InMemoryCache();

const typeDefs = gql`
    type Player {
        playing: Boolean!,
        muted: Boolean!,
        duration: Float!,
        playedSeconds: Float!,
        ready: Boolean!
    }
`};

const initialState = {
player: {
    playing: false,
    muted: true,
    duration: 5,
    playedSeconds: 0,
    ready: false,
    __typename: 'Player'
  }
};

cache.writeData({data: initialState});

const client = new ApolloClient({
  link:  authLink.concat(link),
  cache,
  typeDefs
});

export default client;

export const updatePlayer = (key, value) => {
  console.log('Update Cache {' + key + " : " +value+ "}");
    const newData = {...data[name], ...{[key]: value}};
    client.writeQuery({
      data:{ [name] : newData },
      query
    });
}
````

If I console log out the ready or duration properties in the player component I can see them set to the correct values then reset back to the initial values. I can also see that the "Update Cache" only fires once so the console looks like this: 
````
duration is:  5
duration is:  5
Update Cache {duration : 10.8}
duration is:  10.8
duration is:  5
````

**Versions**
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 12.18.0 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 74.0.1
    Safari: 13.1
  npmPackages:
    @apollo/react-hooks: ^3.1.5 => 3.1.5
    apollo-cache-inmemory: ^1.6.6 => 1.6.6
    apollo-client: ^2.6.10 => 2.6.10
    apollo-link-context: ^1.0.20 => 1.0.20
    apollo-link-http: ^1.5.17 => 1.5.17
    apollo-react: ^0.7.1 => 0.7.1

**Comment by hwillson** [comment]
This doesn't sound like an Apollo Client issue, but if anyone thinks it is and can provide a small runnable reproduction using `@apollo/client@latest`, we'll take a look. Thanks!
