### ISSUE TITLE
Triggering a lot of fetchMore requests causes the application to slow down considerably

### ISSUE THREAD

**Issue by mindnektar** [apollographql/apollo-client#6557]
**Intended outcome:**
`fetchMore` requests are properly cleared.

**Actual outcome:**
`fetchMore` requests are not removed from the watch list, causing the application to slow down considerably after a lot of `fetchMore` requests.

I was able to fix this by simply calling `this.queryManager.removeObservableQuery(qid);` right before the `this.queryManager.stopQuery(qid);` call in the `fetchMore` method of `ObservableQuery`. 

**How to reproduce the issue:**
Simply start a `fetchMore` request and notice how it is still in InMemoryCache's `watches` set after it has completed. It will remain there throughout the app's lifetime and will never be cleared.

**Versions**
2.6.10
I assume it might be already fixed in version 3, since the `fetchMore` logic seems to have changed. Unfortunately I am unable to upgrade at this time, though. I would be beyond grateful if this seemingly small fix could be made for version 2 as this causes a lot of grief to our users and I can't figure out a sensible workaround.

**Comment by mindnektar** [comment]
I see it's been added to the 2.x milestone. Is there any rough estimate on when a new release can be expected? This is still a pretty big issue for me. Sorry for nagging.

**Comment by bendenoz** [comment]
We've come accross the same issue, seems to get exponentially slower as more pages are loaded.

fetchMores are hard coded to 'network-only' ([ObservableQuery.ts#L357](https://github.com/apollographql/apollo-client/blob/release-2.x/packages/apollo-client/src/core/ObservableQuery.ts#L357)) which prevent the cache watch release.

A simple fix we have tested is changing the policy to 'no-cache' in the fetchMore code, but I'm not sure if it could have side effects

**Comment by meinto** [comment]
Any Updates on this? We use `"@apollo/client": "^3.3.7"` with the same issue...

**Comment by alessbell** [comment]
Hi all 👋  It looks like this was fixed in v3 (see comment: https://github.com/apollographql/apollo-client/pull/8920#issuecomment-953122669), and as v3 was released in mid-2020, I'm going to go ahead and close this out as a "won't do" fix to v2. Thanks!
