### ISSUE TITLE
defaultOptions errorPolicy: 'all' does not take effect in useQuery

### ISSUE THREAD

**Issue by sushruth** [apollographql/apollo-client#6561]
errorPolicy when specified in defaultOptions does not seem to take effect for useQuery when the query has multiple queries within.

**Intended outcome:**
useQuery must populate `data` and `error` together if one of the multiple queries fails to resolve, when default error policy is `'all'`

**Actual outcome:**
only error is populated.

**How to reproduce the issue:**
A repo that can repro this issue - https://github.com/sushruth/apollo-client-erorrpolicy-issue 

**Versions**

```
  System:
    OS: Windows 10 10.0.19608
  Binaries:
    Node: 14.0.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    Yarn: 1.22.4 - ~\scoop\apps\yarn\current\Yarn\bin\yarn.CMD
    npm: 6.14.4 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
  Browsers:
    Edge: 44.19608.1000.0
  npmPackages:
    @apollo/client: 3.0.0-rc.10 => 3.0.0-rc.10
    @apollo/link-schema: 2.0.0-beta.3 => 2.0.0-beta.3
```

**Comment by abdullahtariq1171** [comment]
hey @sushruth the repo link you shared is not accessible.

**Comment by sushruth** [comment]
@abdullahtariq1171 sorry about that! it is public now. Thank you.

**Comment by abdullahtariq1171** [comment]
hey, I ran the attached repo locally, looks like the`errorPolicy: 'all', ` is being respected as expected. 


```
[Compo2] This is the data -   Object { dogs: "bark", cats: null } Object { error: Error }
[Compo1] This is the data -   Object { dogs: "bark", cats: null } Object { error: undefined }
```

Further dug into it and it has test which is passing https://github.com/apollographql/apollo-client/blob/3460bd3d1d898fe46c843509a9fd24b6677ceed4/src/core/__tests__/ObservableQuery.ts#L1454


If you think I'm misunderstanding the issue, please guide me as I haven't used `errorPolicy` personally and new contributor here. Thanks

**Comment by sushruth** [comment]
@abdullahtariq1171 - The current issue is about using `errorPolicy` in `defaultOptions` in `new ApolloClient()`, which is not being honored. The test you have mentioned looks like it us using the `watchQuery` hook with explicit `errorPolicy` mentioned in the props. Can you share your lock file and `npx envinfo@latest --preset apollo --clipboard` output so that I can repro it in the same setup?

On the same note, it looks like the issue is not present as described in the original description when using `3.0.0-rc.13`

![image](https://user-images.githubusercontent.com/2114206/87355473-4886cb80-c515-11ea-83ea-33e84381a2ec.png)

Although, the component `Comp1` does seem to get error and data at separate times and not together, it does not look right. It also does not signify partial error or partial success looking at individual render data.

I updated the repo with a little more cleanup. Please use it to repro once again - https://github.com/sushruth/apollo-client-erorrpolicy-issue

**Comment by Titozzz** [comment]
Related to #6677

**Comment by Titozzz** [comment]
Looks like default Options are not working properly 😢

**Comment by hwillson** [comment]
This was fixed in https://github.com/apollographql/apollo-client/pull/6715 - thanks!
