### ISSUE TITLE
Setting customer headers on Apollo Client via example not working

### ISSUE THREAD

**Issue by emhagman** [apollographql/apollo-client#6564]
**Intended outcome:**
I can set `X-Custom-Header` and have other headers remain while using CORs

**Actual outcome:**
My custom header is set but it removes all other headers from the request, causing it to fail.

**How to reproduce the issue:**
Follow the example given here: https://www.apollographql.com/docs/react/networking/authentication/#header

**Versions**
```
  System:
    OS: Linux 5.4 Manjaro Linux
  Binaries:
    Node: 14.3.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.5 - /usr/bin/npm
  Browsers:
    Firefox: 78.0
  npmPackages:
    @apollo/react-components: ^3.1.5 => 3.1.5 
    @apollo/react-hooks: ^3.1.5 => 3.1.5 
    @apollo/react-ssr: ^3.1.5 => 3.1.5 
    apollo-boost: ^0.4.9 => 0.4.9 
    apollo-client: ^2.6.10 => 2.6.10 
    apollo-link-context: ^1.0.20 => 1.0.20 
```

Using the example, I created:

```
const setAdminAuth = setContext((_request, _previousContext) => ({
  headers: { 'X-Override-Key': localStorage.getItem('useroverridekey') },
}));
```

And use it like so:

```
const httpLink = concat(setAdminAuth, createHttpLink({ uri: baseUrl + '/gql/', credentials: 'include' }));
const client = new ApolloClient({ link: httpLink, cache });
```

The header is set on my request but it removes all other headers (Cookie, CORs Headers, etc) from my request which causes it to fail. If I switch the order of the `concat`, then the custom header is not set but all the other headers are and my request succeeds (without the header included).

I also tried using a custom `fetch` like in other examples and the same thing is ocurring.

EDIT: npm didn't detect it but I am actually testing this in Chrome 83

**Comment by kusmierz** [comment]
```js
const setAdminAuth = setContext((_request, { headers }) => ({
  headers: { ...headers, 'X-Override-Key': localStorage.getItem('useroverridekey') },
}));
```
https://www.apollographql.com/docs/react/networking/authentication/#header

**Comment by emhagman** [comment]
Yeah, that does the same thing I am talking about. It removes the other headers (even with `...headers`)

**Comment by emhagman** [comment]
Anyone else? I just upgraded everything to `@apollo/client@3.x` and am still getting this issue.

```
const adminAuthLink = setContext((_, { headers }) => {
  const overrideKey = localStorage.getItem('useroverridekey');
  if (overrideKey) debug('found override key, adding for gql: ' + overrideKey);
  return {
    headers: {
      ...headers,
      'X-Drafted-Override-User-Key': overrideKey ? overrideKey : undefined,
    },
  };
});
```

```
import { ApolloClient, InMemoryCache, NormalizedCacheObject, split, concat } from '@apollo/client';
import { setContext } from '@apollo/client/link/context';
import { hasSubscription } from '@jumpn/utils-graphql';

const cache = new InMemoryCache({ possibleTypes: PossibleTypes });
    if (window.__APOLLO_STATE) cache.restore(window.__APOLLO_STATE); // restore ssr data (rehydrate)
    const httpLink = concat(adminAuthLink, createLink({ uri: baseUrl + '/gql/', credentials: 'include' }));
    if (absintheSocketLink) {
      const link = split(operation => hasSubscription(operation.query), absintheSocketLink, httpLink);
      client = new ApolloClient({ link, cache });
    } else {
      client = new ApolloClient({ link: httpLink, cache });
    }
```

When I do this, only the header I specified is set and no other headers are included.

![image](https://user-images.githubusercontent.com/1421702/88834571-0f4f8c00-d1a2-11ea-85d1-78e202042449.png)

**Comment by emhagman** [comment]
UPDATE: I figured it out. It has to do with the CORS preflight request and one of my headers not being allowed.
