### ISSUE TITLE
@apollo/client@3.0.0-rc.12: Queries (useQuery and Query Component) are refetching and loading on rerender when their cache items haven't changed

### ISSUE THREAD

**Issue by tpoppen** [apollographql/apollo-client#6571]
INFO: This is happening both with `useQuery` from @apollo/client@3.0.0-rc.10 and `<Query>` from @apollo/react-components@4.0.0-beta.1

**Intended outcome:**
Our web app has a main content area and a drawer on the side of the browser for editing records. 
This drawer opens when a user is trying to create or edit a record, and closes when the user saves or deletes the record. Opening the drawer to edit any record means we make more gql requests for new gql fields for various edit options. These new fields will land in the apollo cache ROOT_QUERY alongside the maincontent's query results, and when the drawer closes they disappear from the apollo cache ROOT_QUERY.

I would expect the maincontent to be unaffected and not refetch as the maincontent's cache results did not change or get lost from the drawer opening or closing, and I have the fetchPolicies set to "cache-first".

**Actual outcome:**
What's actually happening, when the drawer closes the drawer specific records pop off the apollo cache ROOT_QUERY, the main content queries refetch and set "loading" to true, causing my main content window to unusable for users during the reload. 
For some pages, that main page query loads a lot of data and this means any edits make the page unusable for a bit.
The cache is updating properly if the user edits a record in the drawer. The main page cache is correct. But for some reason the query still refetches even though it doesn't need the data that dropped off the cache.
An example of what I'm seeing:
I'm on the main page of our application with has a list of projects, a list of all the tasks for all the projects, statuses, and users that are needed for the main page.

You can see them in the ROOT_QUERY in the first log in the screen shot below.

In the second log, this is when a user opens up a drawer to edit a project's info. This form loads some more info, Categories, for options in the form. The form also uses the list of cached users and statuses as an option for editing as well.
You can see the updated ROOT_QUERY with categories in the second log.

When the drawer closes, Categories falls off, the main page query result wipes entirely and refetches and loads.
You can see in the 3rd log that the query results are all wiped.
In the 4th log you can see the same structure as log 1.

My expectation is that the cache would not be wiped and the query would not reload but use the existing records, keeping the main page usable for users after closing the edit drawer.

![image](https://user-images.githubusercontent.com/6015146/87159994-d5b4f080-c287-11ea-90cb-dbdcf0d635ec.png)

Additional Info: opening a drawer is done by adding url query params, we detect those query params and render a sidebar next to the maincontent. Closing a drawer is done with a history.push to remove those query params. This is resulting in a rerender of the maincontent in both cases. 

**How to reproduce the issue:**
Working on a sandbox to repro this issue, but I'm struggling to get the sandbox cache to behave how I'm seeing it behave in our code base. When I inspect the client in here, i dont see anything in the cache at all. I would be happy to keep working on this sandbox if someone could help make sense of how to get ROOT_QUERY and data to show up in the cache in here: https://codesandbox.io/s/pensive-grass-oynmq?file=/src/PersonEditor.js

It may have something to do with the ApolloLink fake gql setup? I'm not sure. But `client.cache.data.data` isn't populating in this sandbox. 

Until The sandbox is figured out, to repro the issue, have 2 queries.
The first query has 2 lists of records. 1 list is only for the main content, the other is also used in the 2nd query.
Have a second query that has 2 lists of records. 1 list that is the same results as one of the lists from the first query. The other only used in the second query.

Now have the 2nd query be used in a component that is only temporarily on screen. When this query's component unmounts the ROOT_QUERY in the apollo cache will drop it's cached query items and cause query 1 to load and refetch. 

**Versions**
@apollo/client@3.0.0-rc.12
@apollo/react-components@4.0.0-beta.1

  System:
    OS: macOS 10.15.5
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.0 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 77.0.1
    Safari: 13.1.1

**Comment by tpoppen** [comment]
I'm trying to get a sandbox to show the issue I'm experiencing, but I'm seeing different behavior in the cache in my sandbox. Maybe it's a config thing? I'm not sure, but in this sandbox when I inspect the cache on the client, I don't see anything in `data`, where are in our code base I see `client.cache.data.data.ROOT_QUERY` and i see the cached data in `client.cache.data.data`. 

Any help would be greatly appreciated: https://codesandbox.io/s/pensive-grass-oynmq?file=/src/PersonEditor.js

**Comment by benjamn** [comment]
Without a reproduction, I really can't guess what might be wrong here. Root fields are almost never lost like this, because the `ROOT_QUERY` object is a singleton that permits its fields to be merged/accumulated over time. Also, I can't tell from your screenshot what data you're logging and where it comes from (the `cacheData` and `rootQuery` identifiers do not appear anywhere in the Apollo Client codebase, for example). Please keep working towards a reproduction, or try setting breakpoints and stepping through the cache code. Good luck!

**Comment by tpoppen** [comment]
@benjamn I'm pulling `cacheData` and `rootQuery` from the `client` object that's passed back as part of `useQuery`'s response.

`client.cache.data.data.ROOT_QUERY` is where it's coming from, I just renamed it poorly in my logs. This is happening right after the `useQuery` is defined in the functional component.

However, I'm not seeing anything in `client.cache.data.data` in the sandbox at all.

**Comment by tpoppen** [comment]
After pulling apollo down and running locally, I was able to trace the issue all the way back up to where we are creating our client instance. This is indeed our code problem, and not apollo's. Closing this issue. Thanks for your patience.
