### ISSUE TITLE
Failed mutations with @client fields return rootValue is undefined instead of graphQLErrors

### ISSUE THREAD

**Issue by pix2D** [apollographql/apollo-client#6585]
If a mutation is made **and the result of the mutation is an error**, and the mutation contains `@client` fields, then instead of getting the errors from the backend the Apollo library throws `rootValue is undefined`. If I remove the `@client` fields then the proper errors show up.

**Intended outcome:**

The error should contain the actual GraphQL error(s).

**Actual outcome:**

`graphQLErrors` is an empty array and this is thrown:

```
Error: rootValue is undefined
    node_modules ApolloError.js:32
    node_modules QueryManager.js:177
    notifySubscription Observable.js:140
    onNotify Observable.js:179
    error Observable.js:240
    node_modules asyncMap.js:26
```

**How to reproduce the issue:**

The specifics of the mutation don't seem to matter, the only thing that matters is that a @client field is present. An abbreviated example:
```
mutation Login($input: LoginInput!) {
  login(input: $input) {
    id
    exampleField @client
  }
}
```

**Versions**

```
  System:
    OS: macOS 10.15.5
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Firefox: 78.0.2
    Safari: 13.1.1
  npmPackages:
    @apollo/client: 3.0.0-rc.12 => 3.0.0-rc.12
```

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
