### ISSUE TITLE
`useMutation` hook retries failed mutations

### ISSUE THREAD

**Issue by chrismin** [apollographql/apollo-client#6591]
**Intended outcome:**
- if the `useMutation` hook errors, it will not retry.

**Actual outcome:**
- if the `useMutation` hook errors, it retries the failed mutation with the same parameters.

**How to reproduce the issue:**
- use the `useMutation` hook to call a mutation that errors

**Versions**
  System:
    OS: macOS 10.15.5
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.21.1 - ~/dev/dharma/dharma-clients/mobile/node_modules/.bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 75.0
    Safari: 13.1.1
  npmPackages:
    @apollo/react-hooks: ^3.1.3 => 3.1.3
    apollo-boost: ^0.4.7 => 0.4.7
    apollo-cache-persist: ^0.1.1 => 0.1.1

I'm not sure if this is a (configurable) feature in `@apollo/react-hooks`.  I can't seem to find anything about it in the docs.

If this is a feature of `useMutation`, could we add documentation for it, and the ability to turn it off?

If not, has anyone else noticed this, and have you managed to figure out what's causing it and how to turn it off?

Thanks!

**Comment by dmaksimovic** [comment]
I'm having the same issue with the legacy (non-hook) ApolloClient.mutate... have you had any discoveries since posting this question  @chrismin ?

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!

**Comment by antoinerousseau** [comment]
It happened to me because I was using a custom `onError` link with a `return forward(operation)`, but as specified here, it means retrying the request:
https://www.apollographql.com/docs/react/api/link/apollo-link-error/

**Comment by jshamel** [comment]
Thanks @antoinerousseau for pointing me in the right direction!

Here is the change I made to the link stack to get offline support working ( offline for my needs means the Apollo client will retry failed mutations due to network issues ):

`const auth = {
	type: "AMAZON_COGNITO_USER_POOLS",
	jwtToken: async () => (await Auth.currentSession()).getIdToken().getJwtToken()
}

const retryLink = new RetryLink({
	attempts: (count, operation, error) => {
	  return !!error && operation.operationName != 'specialCase';
	},
	delay: (count, operation, error) => {
	  return count * 1000 * Math.random();
	},
  });

const link = ApolloLink.from([
	retryLink,
	createAuthLink({ url, region, auth }),
	createHttpLink({ uri: url })

]);`
