### ISSUE TITLE
relayStylePagination duplicating results after page refresh

### ISSUE THREAD

**Issue by WillSquire** [apollographql/apollo-client#6592]
**Intended outcome:**
Expect the same number of results (i.e. 1 list item) on refresh of the page containing the list.

**Actual outcome:**
Each page refresh adds the same 1 list item to the list (causing it to duplicate each time).

**How to reproduce the issue:**
`relayStylePagination` setup like so:
```ts
new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        users: relayStylePagination(['groupId']),
      },
    },
  },
})
```

When `fetchPolicy: 'cache-and-network'` is enabled it refetches the result and when the cache is persisted (i.e. using `apollo-cache-persist`) it remembers the last result. So it's concatenating the same result to the end of the array.

This issue isn't present when using this update function: 
```ts
updateQuery: (previousResult, { fetchMoreResult }) => {
  if (isUndefined(fetchMoreResult)) return previousResult

  const newTotalCount = fetchMoreResult.users.totalCount
  const newEndCursor = fetchMoreResult.users.pageInfo.endCursor
  const newHasNextPage = fetchMoreResult.users.pageInfo.hasNextPage
  const newEdges = fetchMoreResult.users.edges

  return gt(newEdges.length, 0)
    ? {
        ...previousResult,
        users: {
          ...previousResult.users,
          totalCount: newTotalCount,
          pageInfo: {
            ...previousResult.users.pageInfo,
            endCursor: newEndCursor,
            hasNextPage: newHasNextPage,
          },
          edges: [...previousResult.users.edges, ...newEdges],
        },
      }
    : previousResult
},
```

**Versions**
@apollo/client ^3.0.0-rc.10

**Comment by benjamn** [comment]
@WillSquire Thanks for this bug report, and thanks for giving `relayStylePagination` a try. I rushed through a likely fix because I wanted to get it into `@apollo/client@3.0.0`, but I would love to hear from you about whether that fixes it for you. Please feel free to reopen this issue if not!

**Comment by jfrolich** [comment]
I also ran into this. Thanks for fixing.

**Comment by WillSquire** [comment]
@benjamn Brill, and yes it's fixed now. Thank you, most appreciated :)
