### ISSUE TITLE
apollo-link-logger not transferred to @apollo-/client

### ISSUE THREAD

**Issue by timothyarmes** [apollographql/apollo-client#6627]
I've hit a slight issue migrating to Apollo 3.  All the apollo-link-* have been moved to @apollo/client with the exception of apollo-link-logger.  Can this not be included too?

**Comment by Taraluktus** [comment]
Do you mean [apollo-link-logger](https://github.com/blackxored/apollo-link-logger)?
This is a 3rd party package, not maintained by the apollographql team.

**Comment by timothyarmes** [comment]
Ah sorry, I got confused by the apollo-link- prefix.
