### ISSUE TITLE
🐛 useQuery doesn't work when there is both a @client directive and a normal query together

### ISSUE THREAD

**Issue by buzinas** [apollographql/apollo-client#6635]
**How to reproduce the issue:**

1. Create a query with both a `@client` directive (with an alias) and a normal query together, eg:

```graphql
query GroupsTableQuery($organizationId: ID!) {
  clientOrganization: organization(id: $organizationId) @client {
    planType
  }
  organization(id: $organizationId) {
    groups {
      id
      name
    }
  }
}
```

2. Use it:

```js
  const { data, loading, error } = useQuery(GroupsTableQuery, {
    variables: { organizationId },
  });
```

**Intended outcome:**

- The server correctly returns `data` with `groups`, `id` and `name`.
- Apollo resolves the `@client` directive.
- `useQuery` returns `{ data }` with both `clientOrganization` and `organization`.

**Actual outcome:**

- The server correctly returns `data` with `groups`, `id` and `name`. ✅ 
- Apollo doesn't resolve the `@client` directive. ❌ 
- `useQuery` returns `{ data }` as `undefined`. ❌ 

**Obs:**

If I have two separate queries, everything works as expected (so I *know* there is nothing wrong with my queries). Eg:

```graphql
query ClientGroupsTableQuery($organizationId: ID!) {
  clientOrganization: organization(id: $organizationId) @client {
    planType
  }
}

query GroupsTableQuery($organizationId: ID!) {
  organization(id: $organizationId) {
    groups {
      id
      name
    }
  }
}
```

PS: You might be wondering why I have an `organization` that's resolved on the client and another that's resolved on the server, and this is because we're slowly migrating our BE to GraphQL, so parts of the data is resolved on the client through our Rest API.

**Versions**

```
  System:
    OS: macOS 10.15.5
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 84.0.4147.89
    Edge: 84.0.522.40
    Firefox: 78.0.2
    Safari: 13.1.1
  npmPackages:
    @apollo/client: ^3.0.0-beta.41 => 3.0.0-beta.41
    @apollo/link-error: ^2.0.0-beta.3 => 2.0.0-beta.3
```

**Comment by zmaniacz** [comment]
Seeing the same issue on Apollo Client 3.0.2. In my case the query resolves correctly and the graphql call returns correct data when watching the Network tab in dev tools. However, 'data' is still returned as 'undefined'. Removing the field with @client fixes it and have confirmed the @client field I'm using works on it's own.

**Comment by RyotaBannai** [comment]
Having the  same issue here with a version 3.0.2

**Comment by benjamn** [comment]
@buzinas Some questions:

1. Can you share the code you're using to resolve the client field? I'm guessing it's a local resolver function?
2. Does anything change if you add the `planType` field to the non-`@client` selection set?
3. Is it possible to give your `Organization` objects an `id` field?

**Comment by buzinas** [comment]
I solved it by using `organization` in both queries – Apollo merge the results, and I wasn't aware of that.

**Comment by benjamn** [comment]
@buzinas Ok, great! Feel free to keep asking questions here if anything seems wrong/confusing.

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
