### ISSUE TITLE
@client directive causes an unexpected problem once apollo-server throws an error

### ISSUE THREAD

**Issue by atillasertkaya** [apollographql/apollo-client#6655]
Hello, 

I’m currently using `@client` directive with apollo-client on my react project. Somehow getting an error from Apollo-client which says `Cannot read property books of null` in case the Apollo server throws an error. The problem is that I can’t see Apollo-server’s error, I see Apollo-client error which is completely different.

**Possibility 1:** Our model on the server is non-nullable which might cause this problem.

**Possibility 2:** Apollo-client has a bug in this case.

I created a small playground that is similar to our implementation. https://github.com/atillasertkaya/rz12323

**client**: https://github.com/atillasertkaya/rz12323/blob/master/src/App.js

**server**: https://github.com/atillasertkaya/rz12323/blob/master/server.js

struggling with this problem for 5 days, Any idea about that? 

Thanks in advance, 

**-----EDIT-----** 

It would seem that in order for apollo-client to enrich the response with the client state, it parses the server response according to the schema from the server. This usually works fine.
But when an error is thrown on the server, the spec says that the null propagates up the schema until a nullable field is encountered and in the case there is none, the root field data is itself sent as null.

I suspect the client still tries to parse this according to the schema that says that it's not nullable and that's where the issue arises. Has anyone encountered this behavior?

**Comment by hwillson** [comment]
This should no longer be an issue in `@apollo/client@latest` - let us know otherwise, thanks!
