### ISSUE TITLE
apollo studio failed to fetch https with credentials wildcard

### ISSUE THREAD

**Issue by yleigh** [apollographql/apollo-client#6669]
When I running Postgraphile locally and register with Apollo Studio, enable CORS for localhost in my browser works fine.
But then I register Azure running version of GraphQL server with https:, got error:

_Access to fetch at 'https://engine-graphql.apollographql.com/api/graphql' from origin 'https://studio.apollographql.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
datadog-rum-us.js:1 POST https://engine-graphql.apollographql.com/api/graphql net::ERR_FAILED_

Even though I add studio.apollographql.com to enabled CORS browser extension.

Anyway to get this working?

**Comment by benjamn** [comment]
@daniman Can you help find someone who might know the answer to this? Happy to discuss on Slack.

**Comment by cheapsteak** [comment]
Hi @yleigh 

From that error message, it looks like Apollo Studio thinks your graph's endpoint is `https://engine-graphql.apollographql.com/api/graphql`, could you please open Explorer Settings and "Edit" the endpoint to point to your server's endpoint?
![image](https://user-images.githubusercontent.com/743976/88196383-1eb55f00-cc0f-11ea-9453-439d5dc1a2f2.png)

It looks like you also have Explorer's "include cookies" setting turned on

If your endpoint does not use cookies for authentication, turning off the "include cookies" setting should fix the CORS error
![image](https://user-images.githubusercontent.com/743976/88196516-486e8600-cc0f-11ea-8d89-ab0645aefbcd.png)


If your endpoint does use cookies for authentication, then your server would need to set the following response headers when it receives a request from Apollo Studio

```
Access-Control-Allow-Origin: https://studio.apollographql.com
Access-Control-Allow-Credentials: true
```

**Comment by cheapsteak** [comment]
I'm going to close this issue since this isn't specifically relevant to apollo client    

I hope the instructions above were able to help you address the CORS problem you ran into, otherwise please feel free to either continue discussion on this thread, or ask for further help via Apollo Studio's Intercom :)
