### ISSUE TITLE
Why is there a dependency on react? 

### ISSUE THREAD

**Issue by francoisromain** [apollographql/apollo-client#6672]
When I try to install apollo-client and start my app, it makes an error: 

```
This dependency was not found:

* react in ./node_modules/@apollo/client/react/context/ApolloContext.js, ./node_modules/@apollo/client/react/context/ApolloProvider.js and 6 others
```

I don't use react in this project. Why is it required to install react? 

Thank you

**Comment by benjamn** [comment]
I admit it's a little strange that `@apollo/client` exports `useQuery` and a few other React-related utilities, when you're not using React. However, we have an entry point called `@apollo/client/core` for everything except the React stuff (#5541). Try importing from there?

**Comment by francoisromain** [comment]
Ok thank you for your quick answer.
