### ISSUE TITLE
AC3 Breaks Apollo Client DevTools Query Tab after first broadcast:new message

### ISSUE THREAD

**Issue by justinmwarner** [apollographql/apollo-client#6682]
**Intended outcome:**
Apollo Client DevTools Query Tab works with all queries made on site.

**Actual outcome:**
When the first `broadcast:new` gets sent, it parses using the function `filterQueryInfo` which adds the `document` mapping properly. Later calls get routed through `QueryManager`'s `onBroadcast`, mapping the `queries` field to `getQueryStore`. Looking at `getQueryStore`, you'll see it's a bit different than `filterQueryInfo` (no document map). This causes the `document` field to be undefined when the Query is rendered, causing it to fail here: https://github.com/apollographql/apollo-client-devtools/blob/master/src/devtools/components/WatchedQueries/WatchedQueries.js#L30

**How to reproduce the issue:**
I'm not sure how to get a setup, but I can investigate if needed.

**Versions**
  System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 13.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD 
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD 
  Browsers:
    Chrome: 84.0.4147.89
    Edge: Spartan (44.19041.1.0)
  npmPackages:
    @apollo/client: ^3.0.0-beta.50 => 3.0.2       
    @apollo/link-context: ^2.0.0-beta.3 => 2.0.0-beta.3 
    @apollo/react-common: ^3.1.4 => 3.1.4         
    @apollo/react-hooks: ^4.0.0 => 4.0.0

**Comment by hwillson** [comment]
@justinmwarner would you mind re-opening this over in https://github.com/apollographql/apollo-client-devtools? Thanks!
(cc @jcreighton)

**Comment by justinmwarner** [comment]
Will do -https://github.com/apollographql/apollo-client-devtools/issues/280

Assumed with the issue seeming to be with QueryManager, thought this was best.  But thanks for the redirect!
