### ISSUE TITLE
A __typename of Query leads to incorrect caching

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [apollographql/apollo-client#6685]
**Intended outcome:**

Getting the correct results from a query

**Actual outcome:**

If using a type with `__typename` of `Query`, I get incorrect results instead. For nested references to the type, each reference is incorrectly resolved as the first instance in the result. Specifically (from the repro case):

Query:

```
  query Items {
    items {
      id
      query { id }
    }
  }
```

the data returned for the graphql operation is

```
[
 { "id": 0, "query": { "id": 0 } },
 { "id": 1, "query": { "id": 1 } },
 { "id": 2, "query": { "id": 2 } }
]
```

but the data from useQuery is:

```
{
  "items": [
    {
      "__typename": "Item",
      "id": "0",
      "query": {
        "id": "0"
      }
    },
    {
      "__typename": "Item",
      "id": "1",
      "query": {
        "id": "0"
      }
    },
    {
      "__typename": "Item",
      "id": "2",
      "query": {
        "id": "0"
      }
    }
  ]
}
```

Note how each nested `query` incorrectly has an `id` of `0` (instead of an id matching its `item`).

**How to reproduce the issue:**

See https://github.com/uhoh-itsmaciek/react-apollo-error-template -- thanks for the awesome template!

**Versions**

```
  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
  Binaries:
    Node: 13.8.0 - ~/n/bin/node
    Yarn: 1.22.4 - ~/n/bin/yarn
    npm: 6.14.4 - ~/n/bin/npm
  Browsers:
    Chrome: 84.0.4147.89
    Firefox: 78.0.2
  npmPackages:
    @apollo/client: ^3.0.0 => 3.0.2 
  npmGlobalPackages:
    apollo: 2.18.3
```

**Comment by benjamn** [comment]
Fix incoming: #6691
