### ISSUE TITLE
Query component freezing on reading from cache

### ISSUE THREAD

**Issue by sandeshnaroju** [apollographql/apollo-client#6693]
Thanks to all who contributed to this resource.

I am using apollo client for a local news feed application, news gets saved into memory cache. So,  In one of the screens of the application, I need to click a button that will open another screen. after the new screen is opened,  I need to fetch the news from the cache and perform some animations on carousal. 

Here the problem is on button click, the new screen is not opening right away it is freezing as it is fetching news from the cache. but whenever I change fetch-policy to `network-only` from `cache-and-network`,  the new screen is opening and `loading` var from the `Query` component is set to true. 

What i thought it would do, the `loading` should set true does not matter if it is loading from cache or network. As the news is loading from cache, the app is freezing to open new screen.. help me to resolve this. thank you.

**Comment by etc-tiago** [comment]
You can provide details to reproduce the issue?
