### ISSUE TITLE
V3. Broadcasting does not work for modify/created via cache.modify() method

### ISSUE THREAD

**Issue by xiaoyu-tamu** [apollographql/apollo-client#6700]
Looks like broadcasting does not work properly for entity modify/created via `cache.modify`, from the devtool screenshot(see below), I'm sure the cache is updated correctly.

context : A dashboard to manage order

 　
 　
 　
 
![image](https://user-images.githubusercontent.com/33362998/88468793-40804180-ceae-11ea-8e54-60f2d2dea8bc.png)
　
　
　
![image](https://user-images.githubusercontent.com/33362998/88468781-234b7300-ceae-11ea-9586-a89c4c50b8bc.png)
　
　
　

1. read order items, UI mounted

```
const query = usePurchaseOrderCardItemsQuery({ variables: { poId } });
```

2. add new order item, UI updated, new item appended
```
  const [create] = useCreatePurchaseOrderItemMutation({
    update: (cache, { data }) => {
      const created = data?.createPurchaseOrderItem;
      if (!created) return;
      cache.modify({
        id: cache.identify(created.order),
        fields: {
          items(refs: Reference[]) {
            return [...refs, created];
          },
        },
      });
    },
  });
```

3.  update created order item, (bug happened, UI not update, it should update created item )
```
const [receiveQuantity] = useReceivePurchaseOrderQuantityMutation();

mutation receivePurchaseOrderQuantity($poItemId: Int!, $quantityReceived: Int!) {
  updatePurchaseOrderItem(
    pk_columns: { id: $poItemId }
    _inc: { quantityReceived: $quantityReceived }
  ) {
    id
    quantityReceived
    order {
      id
      status {
        id
        value
      }
      quantityReceived
    }
  }
}
```

**Intended outcome:**
query not get notified

**Actual outcome:**
query should get be notified

**How to reproduce the issue:**
1. read list of items
2. add new item and modify cache use `cache.modify`
3. update newly inserted item

**Versions**

**Comment by dmarkow** [comment]
I ran into this today, but caught my issue in the docs: https://www.apollographql.com/docs/react/caching/cache-interaction/#example-adding-an-item-to-a-list

When adding to a list, you have to add a fragment reference to the list rather than your raw data. So in your second code block you should have something like this:

```js
```

**Comment by xiaoyu-tamu** [comment]
Thanks, I will try it

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
