### ISSUE TITLE
Unable to find native implementation, or alternative implementation for WebSocket!

### ISSUE THREAD

**Issue by sk1794** [apollographql/apollo-client#6707]
I'm getting this error while configuring the subscription in next.js
![image](https://user-images.githubusercontent.com/30054578/88519979-95d46400-d010-11ea-8c8e-78686eb0d528.png)

**Comment by jdgabriel** [comment]
Some solution for this error?

**Comment by sk1794** [comment]
```
import { WebSocketLink } from 'apollo-link-ws';
const wsLink = process.browser
  ? new WebSocketLink({
      uri: process.env.NEXT_PUBLIC_SUBSCRIPTION_URL,
      options: {
        reconnect: true,
        connectionParams: {
          authorization: token,
        },
      },
    })
  : null;


  if(wsLink) {
    console.log("connected")
  }
```

I have implemented like this

**Comment by sk1794** [comment]
> Some solution for this error?

I have implemented this and its working.

```
import { WebSocketLink } from 'apollo-link-ws';

const wsLink = process.browser
  ? new WebSocketLink({
      uri: process.env.NEXT_PUBLIC_SUBSCRIPTION_URL,
      options: {
        reconnect: true,
        connectionParams: {
          authorization: token,
        },
      },
    })
  : null;


  if(wsLink) {
    console.log("connected")
  }
```

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!

**Comment by brunorafaeI** [comment]
I have the same problem right now, someone can help me? the solution "process.browser" don't works with me, this variable don't exists, I'm trying to use apollo-link-ws to link my project in sveltekit from hasura backend (graphql).

**Comment by sk1794** [comment]
> I have the same problem right now, someone can help me? the solution "process.browser" don't works with me, this variable don't exists, I'm trying to use apollo-link-ws to link my project in sveltekit from hasura backend (graphql).
Have you tried my solution? https://github.com/apollographql/apollo-client/issues/6707#issuecomment-700833643
