### ISSUE TITLE
apollo-link-persisted-queries on v3

### ISSUE THREAD

**Issue by correttojs** [apollographql/apollo-client#6708]
hi,

is there an equivalent for the `apollo-link-persisted-queries` on v3? I see there's a typescript error due to the different Link interface when I try to include the link on v3

**Comment by benjamn** [comment]
Here's a PR tracking the necessary updates: https://github.com/apollographql/apollo-link-persisted-queries/pull/48

**Comment by correttojs** [comment]
Thanks for the fast update!

**Comment by hwillson** [comment]
https://github.com/apollographql/apollo-link-persisted-queries/pull/48 has been updated; let's track progress in that PR. Thanks!
