### ISSUE TITLE
Apollo Codegen should take into considertation local fields (@client)

### ISSUE THREAD

**Issue by MalikBagwala** [apollographql/apollo-client#6716]
![image](https://user-images.githubusercontent.com/23068029/88623894-91b54e80-d0c3-11ea-94d4-2812a98bdc5d.png)

As you can see the `@client` field throws an error

This is how my client resolvers look like

![image](https://user-images.githubusercontent.com/23068029/88623962-b7425800-d0c3-11ea-97f8-c369d9551005.png)

How do I make the apollo tooling (including the code gen) take into consideration the local schema?

**Comment by dylanwulf** [comment]
You need to create a type extension inside a gql string. Probably will look something like this:
```js
const typeDefs = gql`
extend type BookingsByTripType {
    unsettledQuantity: Int!
}
`;
```

https://www.apollographql.com/docs/react/local-state/client-side-schema/

**Comment by MalikBagwala** [comment]
> You need to create a type extension inside a gql string. Probably will look something like this:
> 
> ```js
> const typeDefs = gql`
> extend type BookingsByTripType {
>     unsettledQuantity: Int!
> }
> `;
> ```
> 
> https://www.apollographql.com/docs/react/local-state/client-side-schema/

This was a lifesaver. Than you :+1:
