### ISSUE TITLE
Firefox dev-tools support not mentioned in documentation

### ISSUE THREAD

**Issue by andoks** [apollographql/apollo-client#6717]
**Intended outcome:**
Read the [dev-tools documentation](https://github.com/apollographql/apollo-client/blob/master/docs/source/development-testing/developer-tooling.md#apollo-client-devtools), looking for information about firefox support for apollo dev-tools plugin. Documentation only mentions chrome support. However it seems like firefox has been supported since [18th of may](https://github.com/apollographql/apollo-client-devtools/issues/73#issuecomment-630328017) :tada:

**Actual outcome:**
Documentation also linking to [dev tools for firefox](https://addons.mozilla.org/en-US/firefox/addon/apollo-developer-tools/)

**How to reproduce the issue:**
N/A

**Versions**
N/A

**Comment by andoks** [comment]
Relates to https://github.com/apollographql/apollo-client/pull/6360

**Comment by benjamn** [comment]
Thanks for flagging this @andoks!
