### ISSUE TITLE
DataProxy and NormalizedCacheObject types not available from @apollo/client in 3.1 without deep import

### ISSUE THREAD

**Issue by JoshRobertson** [apollographql/apollo-client#6723]
When upgrading from 3.02 to 3.1, our type imports for `DataProxy` and `NormalizedCacheObject` no longer work unless we deep import from `@apollo/client/cache`.

I suspect it might be a result of https://github.com/apollographql/apollo-client/pull/6656 

I just can't tell if it's intended and undocumented, or unintended.

**Comment by benjamn** [comment]
Ack, sorry, this was unintentional. Fix incoming: #6725

**Comment by benjamn** [comment]
This should now be fixed in `@apollo/client@3.1.1` (just published). Thanks for reporting this @JoshRobertson!
