### ISSUE TITLE
AC3 cache lookup issue

### ISSUE THREAD

**Issue by jvvcn** [apollographql/apollo-client#6727]
Hello guys, have a question, how query knows what to return from cache?

Here are two examples:
  1. Plain query with variables
```
const { data, loading } = useQuery(gql`
    query GetCountry($code: ID!) {
      country(code: $code) {
        name
        native
        capital
      }
    }
  `, {
    variables: {
      code,
    }
  })
```
  2. Same query but with reactive variables
```
  const { data, loading } = useQuery(gql`
    query GetCountry($code: ID!) {
      code @client @export(as: "code")
      country(code: $code) {
        name
        native
        capital
      }
    }
  `)
```

If cache is available in a first case it returns correct data from the cache, but In a second case it returns me _wrong_ result (usually from previous request) from the cache. In both cases cache looks identical like this:

```
country({"code":"BR"}): {__typename: "Country", name: "Brazil", native: "Brasil", ...}
country({"code":"US"}): {__typename: "Country", name: "United States", native: "United States", ...}
```

Also while execution second query, loading is switching from `true` to `false` but data is still `undefined` 

<img width="541" alt="Screen Shot 2020-07-29 at 09 59 12" src="https://user-images.githubusercontent.com/37310604/88767342-2f6f5300-d182-11ea-8af1-0a31819173fd.png">

Btw, I cant understand why my component renders so many times, as it's the only component I have in my application. It's happening only if I use `@client` directive in a query 

Did i miss something or this is an issue with the cache lookup & reactive variables?

**Comment by rebz** [comment]
@jvvcn - Did you find a solution for this?
