### ISSUE TITLE
context in SchemaLink is not async

### ISSUE THREAD

**Issue by djflex68** [apollographql/apollo-client#6730]
**Intended outcome:**
I'm trying to have an async context for SchemaLink.
But in "src/link/schema/index.ts" at line 51 there is `this.context(operation) `instead of `await this.context(operation)`.
This is a different behavior for ApolloClient than for ApolloServer, which breaks the app in my case.

**Actual outcome:**
context does not wait until promise is resolved, and therefore the injected context in resolvers is wrong.

**How to reproduce the issue:**
Make the context return a promise instead of a sync function

**Versions**
Latest version

**Comment by benjamn** [comment]
@djflex68 Seems like a good idea! Have a look at #6735?

**Comment by djflex68** [comment]
Okay thanks, wondering nevertheless if the test about `typeof this.context === 'function' ? this.context(operation)` is valid in the case where the context function returns a promise. Shouldn't we test that typeof this.context === "Promise" or something like that ? (I Might we wrong)
