### ISSUE TITLE
Loading state on Server Side Rendering

### ISSUE THREAD

**Issue by correttojs** [apollographql/apollo-client#6733]
**Intended outcome:**
Server side rendering with extracted cache

**Actual outcome:**
The useQuery hook returns  `loading:true` state

**How to reproduce the issue:**
- create an apollo-client instance
- execute a query using `apollo.query`
- extract the cache
- create an apollo-client instance passing the extracted state
- run the same query with `useQuery`

Expected: `loading` property is `false`
Actual: `loading` property is `true`, data is populated

**Versions**
@apollo/client 3.0.2

**Comment by benjamn** [comment]
You may want to update to `@apollo/client@3.1.1`, which includes #6710.

**Comment by correttojs** [comment]
thank you, with the latest version it worked
