### ISSUE TITLE
setContext converts all headers to lower case

### ISSUE THREAD

**Issue by theLiudas** [apollographql/apollo-client#6741]
Hey folks,

I've encountered issue when setting headers with `operation.setContext`.
See code below:
```js
const authLink = new ApolloLink((operation, forward) => {
  const { tokenHeaderName, tokenHeaderValue } = JSON.parse(localStorage.getItem('auth'))

  // add the authorization to the headers
  operation.setContext({
    headers: {
      [tokenHeaderName]: tokenHeaderValue,
    },
  })

  return forward(operation)
})
```

With this peace of code I simply want to inject custom authorization header with token. My header name is, let's say: `X-CustomToken-XYZ`. Java backend token processor is ***case-sensitive*** unlike the standard web headers. 

***The problem:*** `ApolloLink` for some reason converts all headers that are passed, to lower case (I checked it by hardcoding the `X-CustomToken-XYZ` in string litterals) hence the authorization logic in our app simply doesn't work.

I've tried using either `@apollo/link-context` and `apollo-link-context` both behaves similarly.

Any suggestions on how to pass my headers to the request as is?

Thanks in advance!

**Comment by DerKO9** [comment]
I am having the same issue

**Comment by ddbhagat** [comment]
Seeing similar issue with one of the custom headers. Any solution to this?

**Comment by DerKO9** [comment]
No worries, now that I know why, it'll be easy to work around.

Thanks Emmanuel!

**Comment by MrDoomBringer** [comment]
Hey all! 

I thought support for this might still be useful, so I went ahead and got approval for supporting capitalized header names in Release 3.7 with this PR - https://github.com/apollographql/apollo-client/pull/9891. I'll be closing this issue now, let us know if you have any questions or asks for improvement! 

All the best,
Emmanuel, Intern :-)
