### ISSUE TITLE
Query Results not getting stored in the cache immediately ?

### ISSUE THREAD

**Issue by shyam2794** [apollographql/apollo-client#6750]
Hi,

I am migrating the Apollo client from 2.X to 3.X . I face an issue where i am not able to delete a user in the cache , after the mutation . This seems to work in the 2.X version . when looking at the cache , i see that after the query gets fired i don't see the result in cache reflecting immediately .

#### Example:
Say i have 2 queries , getUsers , getMachines , when i call getUsers the results are not saved in cache immediately . When i call getMachines , now the results of getUsers are added in the cache . Now if i call a third query , the getMachines results are added in the cache . This looks a bit strange to me .

#### Version 2.X - Expected Behaviour
Whenever the query is fired the results should be reflected in the cache immediately . This was the intended behaviour . In this below image when i visit the users query , i am already able to see the queryResults in the cache . 

<img width="1220" alt="Screenshot 2020-07-31 at 1 33 53 PM" src="https://user-images.githubusercontent.com/30238125/89014421-1ce84b80-d333-11ea-940b-ab77ea0ec1d6.png">

#### Version 3.X - Actual Behaviour
When the query is fired the results are not getting reflected in the cache. This Doesn't seem to work in the 3.X version . 
In this below image the query is already fired, but i am not able to see the queryResults in the cache . 

The problem with this behaviour is i can't edit or delete the user in cache after the mutation . As i get Apollo Error stating that getUserByRole field is not in ROOT_QUERY . 

<img width="1190" alt="Screenshot 2020-07-31 at 12 28 18 PM" src="https://user-images.githubusercontent.com/30238125/89014616-63d64100-d333-11ea-8e4c-f3fec3e70d1e.png">

**Versions**

System:
    OS: macOS 10.15.5
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.105
    Safari: 13.1.1
  npmPackages:
    @apollo/client: ^3.1.1 => 3.1.1

**Comment by hwillson** [comment]
We'll need a reproduction (using `@apollo/client@latest`) to be able to troubleshoot this further. Thanks!
