### ISSUE TITLE
Error prop of useQuery result is not set when an error occurs during fetchMore

### ISSUE THREAD

**Issue by GlennyDC** [apollographql/apollo-client#6751]
**Intended outcome:**
The `error` prop of `useQuery` is set when an error occurs during the execution of `fetchMore`. The `loading` prop of `useQuery` is set during the execution of `fetchMore`.

**Actual outcome:**
The `error` prop is not set. The async `fetchMore` does throw but the documentation does not specify this at all. The `loading` prop is correctly set during the execution of `fetchMore`.

**How to reproduce the issue:**
```js
const { loading, error, fetchMore } = useQuery(MY_QUERY, {
  notifyOnNetworkStatusChange: true,
  variables: {
    offset: 0,
    limit: 5,
  },
});
```
```js
const handleLoadMore = useCallback(async () => {
  try {
    await fetchMore({
      variables: { offset: data.x.length },
      updateQuery: (prev, { fetchMoreResult }) => {...},
    });
  } catch (e) {
    // This does catch
  }
}, [fetchMore, data]);
```

**Versions**
  _System:_
    OS: macOS 10.15.5
  _Binaries:_
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
  _Browsers:_
    Chrome: 84.0.4147.105
    Firefox: 78.0.1
    Safari: 13.1.1
  _npmPackages:_
    @apollo/react-hooks: ^3.1.5 => 3.1.5 
    apollo-cache-inmemory: ^1.6.5 => 1.6.5 
    apollo-client: ^2.6.8 => 2.6.8 
    apollo-link: ^1.2.14 => 1.2.14 
    apollo-link-context: ^1.0.20 => 1.0.20 
    apollo-link-error: ^1.1.13 => 1.1.13 
    apollo-link-http: ^1.5.17 => 1.5.17 
    apollo-utilities: ^1.3.4 => 1.3.4

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
