### ISSUE TITLE
onError - Not all code paths return a value (Typescript)

### ISSUE THREAD

**Issue by PetrShchukin** [apollographql/apollo-client#6767]
**Intended outcome:**
When using onError with return forward(operation); There is a TS error for other parts that "Not all code paths return a value."

**Actual outcome:**
Typescript error: "Not all code paths return a value."

**How to reproduce the issue:**
```
const link = ApolloLink.from([
  onErrorHandler,
  new HttpLink({
    uri: `${apiUrl}/graphql/`,
  }),
]);

// an example from web-site
onError(({ graphQLErrors, networkError, operation, forward }) => {
    if (graphQLErrors) {
		// retry the request, returning the new observable
		return forward(operation);
    }
   if (networkError) {
      console.log(`[Network error]: ${networkError}`);
      // if you would also like to retry automatically on
      // network errors, we recommend that you use
      // apollo-link-retry
    }
  }
);
```

**Versions**
    "apollo-client": "2.6.10",
    "apollo-link": "1.2.14",
    "apollo-link-error": "1.1.13",

**Comment by Marcohj** [comment]
Well, you only do `return forward(operation);` if `graphQLErrors ` exists.
So TypeScript is right, if `graphQLErrors` you don't do any return. So you should either ALWAYS `forward` or you need to do something else :)

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
