### ISSUE TITLE
apollo-boost no export onError

### ISSUE THREAD

**Issue by IrvinVelazco** [apollographql/apollo-client#6768]
**Intended outcome:**
use the already included module apollo-link-error from apollo-boost
```ts
import { onError } from 'apollo-boost';

```

**Actual outcome:**
Module '"../../../node_modules/apollo-boost/lib"' **has no exported member 'onError'.** Did you mean to use 'import onError from "../../../node_modules/apollo-boost/lib"' instead?ts(2614)

 apollo-link-error have to be installed from npm

**How to reproduce the issue:**
```ts
import { onError } from 'apollo-boost';

```

**Versions**
"apollo-boost": "^0.4.9",

**Comment by hwillson** [comment]
Apollo Boost is no longer supported. Please refer to the [Apollo Client 3.0 migration guide](https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/) for details. Thanks!
