### ISSUE TITLE
How does WebSocketClient pass authentication token in Apollo Client 3.0?

### ISSUE THREAD

**Issue by proIT324** [apollographql/apollo-client#6772]
By Apollo GraphQL's official doc, Apollo Client 3.0 supports authentication of WebSocket for its subscriptions. Subscriptions should be authenticated by a secure token in many cases. It was the same to me. I followed the latest doc of authentication over WebSocket of Apollo Client([here][1]). 

Doc:

[![enter image description here][2]][2]

My code:

    import { WebSocketLink } from '@apollo/client/link/ws';
    
    const wsLink = new WebSocketLink({
      uri: `${process.env.REACT_APP_WS_API}/graphql/`,
      options: {
        reconnect: true,
        connectionParams: {
          authToken: `${localStorage.getItem('access_token')}`
        }
      }
    })

Unfortunately, this authentication doesn't work at all. `graphql_jwt.exceptions.PermissionDenied` error occurred in my `Django` backend and no `authToken` value was read by the backend. I've attached a screenshot of the exception below.

[![enter image description here][3]][3]

Is there any valid solution to pass a secure token to `WebSocketLink`? 

  [1]: https://www.apollographql.com/docs/react/data/subscriptions/
  [2]: https://i.stack.imgur.com/asSbq.png
  [3]: https://i.stack.imgur.com/Iz0Od.png

Stackoverflow: https://stackoverflow.com/questions/63253201/how-does-websocketclient-pass-authentication-token-in-apollo-client-3-0

**Comment by benjamn** [comment]
See https://github.com/apollographql/apollo-client/issues/6782#issuecomment-669506300. Happy to continue discussion over there, since this seems like a duplicate issue.
