### ISSUE TITLE
 the network request failed on some phone brand and POST(MUTATION) type requests 

### ISSUE THREAD

**Issue by ththugues44** [apollographql/apollo-client#6776]
## Description
Hello

Our application is in production and has problems for POST (MUTATION) type requests. On some phone brands and all android versions (5, 6, 7,8,9,10). and on the other hand the Post type requests work very well on other phones and all android version (5,6,7,8,9,10)

The exact error produced is: Error · Error: Network error: Network request failed.

React native command result:

Different solutions already tested:

- By default, access to our backend is via https using cloudflare. I even thought that it could be an https certificate problem, I changed cloudflare to use a certificate from
 Let's Encryptletsencrypt, until then we have the same problem.

We figured this was a problem with the https protocol and decided on http and added to AndroidManifest.xml the directive:

```
<android application: usesCleartextTraffic = "true">
</application>
```

despite all this we have the same problem namely the POST (MUTATION)  type request are not functional on some brands of phone and any android version (5,6,7,8,9,10)

## React Native version:
```
System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (4) x64 Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
    Memory: 761.15 MB / 11.65 GB
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.15.2 - /usr/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.14.5 - /usr/bin/npm
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-rename: 2.4.1
```

**Versions Package Appolo**
```
  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
  Binaries:
    Node: 10.15.2 - /usr/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.14.5 - /usr/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
  npmPackages:
    @apollo/react-hooks: ^3.1.3 => 3.1.5 
    apollo-cache-inmemory: ^1.6.5 => 1.6.6 
    apollo-client: ^2.6.8 => 2.6.10 
    apollo-link-error: ^1.1.12 => 1.1.13 
    apollo-link-http: ^1.5.16 => 1.5.17 
```
*My Code*

```
import {MUTATION_USER_CREATE} from '../../api/Graphql/Mutation/Mutation';
import ApolloClient from 'apollo-client';

const client = new ApolloClient({
  link: createHttpLink({
    uri: data.endpoint_graphql_post,
    useGETForQueries: true,
    includeExtensions: true,
  }),
  cache: new InMemoryCache(),
});
class createUserScreen extends React.Component {
 constructor(props) {
    super(props);
    this.state = {
    username: this.props.route.params.username,
      email: this.props.route.params.email,
      name: this.props.route.params.name,
      prename: this.props.route.params.prename,
}
}

 _createUser() {
    const {
      username,      
      email,
      name,
      prename,
      ethnie,
    } = this.state;
    return client
      .mutate({
        mutation: MUTATION_USER_CREATE,
        variables: {
          user: {
        
            email: email,
            username: username,
            name: name,
            prename: prename,
          },
        },
        
        },
      })
      .then(value => {
        console.log(value.data);
        this.props.navigation.navigate('MainScreen');
        return true;
      })
      .catch(reason => {
        console.log(reason);
        return false;
      });
  }
  componentDidMount() {
    this._createUser();
  }
}
```
**Error Display**
`Error Error: Network error: Network request failed`

Thank you for any help in relation to this problem because at this time we already no longer block more than 1200 Registrations on our Mobile application.

**Comment by marf** [comment]
Hello @ththugues44 we have exactly the same problem. Have you found a solution?

**Comment by geroale** [comment]
Same issue here

**Comment by ththugues44** [comment]
@marf @geroale I suffered enormously from this problem for POST requests. the solution is very simple at the end of your endpoint put a / for the request post.

**Comment by marf** [comment]
Thank you so much @ththugues44 !

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
