### ISSUE TITLE
Using apollo-client without react/hooks

### ISSUE THREAD

**Issue by sneznaovca** [apollographql/apollo-client#6783]
Hello,
Is way how use apollo-client 3.0 without react/hooks? 
How I should call query or mutation without react?

**Comment by henryqdineen** [comment]
The `ApolloClient` class has `query()` and `mutate()` methods that you can use without React. https://www.apollographql.com/docs/react/api/core/ApolloClient/#apolloclient-functions

**Comment by madflow** [comment]
@sneznaovca maybe you are like me and missed:

https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/#using-apollo-client-without-react
