### ISSUE TITLE
pollInterval broken when InMemoryCache.resultCaching false

### ISSUE THREAD

**Issue by brent-williams** [apollographql/apollo-client#6785]
**Intended outcome:**
Requests sent once/second.

**Actual outcome:**
Requests sent dozens/second.

**How to reproduce the issue:**
Create any hello world-style app w/ with `pollInterval: 1000` and `InMemoryCache.resultCaching` false.

**Versions**
```
  System:
    OS: macOS 10.15.6
  Binaries:
    Node: 14.7.0 - /usr/local/bin/node
    Yarn: 1.16.0 - ~/.yarn/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 68.11.0
    Safari: 13.1.2
  npmPackages:
    @apollo/client: ^3.1.2 => 3.1.2
```

**Comment by benjamn** [comment]
The ability to disable result caching was always more of a diagnostic tool than a recommended option. We very nearly removed it in AC3, because so many of the benefits of the client/cache rely on it. It may be time to revisit the reasons you decided to disable it in the past.

**Comment by brent-williams** [comment]
@benjamn understood and thanks for quick response, will set resultCaching to true.

**Comment by benjamn** [comment]
@brent-williams We definitely want to make sure we address any hurdles to using result caching, so everyone can keep it turned on, so don't hesitate to open follow-up issues if you have any trouble!
