### ISSUE TITLE
loading remain true on second load

### ISSUE THREAD

**Issue by WajidAfridi48** [apollographql/apollo-client#6786]
**Intended outcome:**
In react hooks useQuery loading become false initially. But on return to same page loading remain true.

**Actual outcome:**
![image](https://user-images.githubusercontent.com/48506302/89512055-1d2d8e80-d7ec-11ea-8807-24ed7569c526.png)

**Versions**
"react": "^16.13.1",
"@apollo/client": "^3.0.2",

**Comment by benjamn** [comment]
Try updating to `@apollo/client@3.1.2`?

**Comment by WajidAfridi48** [comment]
Thank you, its work for me.
