### ISSUE TITLE
All Use of Fragments Fail after upgrading to v3

### ISSUE THREAD

**Issue by ashah888** [apollographql/apollo-client#6788]
**Intended outcome:**
I'm trying to upgrade my app from Apollo Client v2 to v3, but everything break.
I'm following the guide, and using @apollo/client (from apollo-client).
I'm expecting all the app the work the same as before.

**Actual outcome:**
I was able to get the app running normally. But the queries are being returned empty where the fragment is used. (essentially, the fragments are completely ignored.

**Comment by Gilbert09** [comment]
@ashah888 I'm having the same issue, were you able to solve this?

**Comment by shepitchakpavlo** [comment]
The same issue. @ashah888 How did you solve it?

**Comment by benjamn** [comment]
@ashah888 The old `FragmentMatcher` interface was removed in v3, as explained in the [migration guide](https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/#breaking-cache-changes).

When using AC v3, you likely need to pass `possibleTypes` to the `InMemoryCache` constructor, as explained in [these docs](https://www.apollographql.com/docs/react/data/fragments/#using-fragments-with-unions-and-interfaces).
