### ISSUE TITLE
relayStylePagination returns too many results

### ISSUE THREAD

**Issue by sleepycat** [apollographql/apollo-client#6792]
I'm trying to write a test that paginates using the relayStylePagination function and seeing behaviour I don't understand.

Basically imagine starting with the markup below, showing "repo one", clicking `next`, seeing "repo two" and then clicking `previous` which should display "repo one" again. 

```html
      <div>
        <ul>
          <li>
            repo one
          </li>
        </ul>
        <button>
          next
        </button>
        <button>
          previous
        </button>
      </div>
```
Clicking `next` shows both "repo two" (what I was expecting) and "repo one" (which I wasn't):

```html
      <div>
        <ul>
          <li>
            repo one
          </li>
          <li>
            repo two
          </li>
        </ul>
        <button>
          next
        </button>
        <button>
          previous
        </button>
      </div>
```

If I click `previous` "repo one" is duplicated, and "repo two" is still visible:

```html
      <div>
        <ul>
          <li>
            repo one
          </li>
          <li>
            repo one
          </li>
          <li>
            repo two
          </li>
        </ul>
        <button>
          next
        </button>
        <button>
          previous
        </button>
      </div>
```

I made a [codesandbox](https://codesandbox.io/s/apollo-mockedprovider-duplicates-p2cf2?file=/src/__tests__/pagination.test.js) demonstrating the issue with the current version (3.1.3).

**Comment by benjamn** [comment]
For your backward query, you're using the variables `{ before: "Y3Vyc29yOnYyOpHOAAfgfQ==", last: 1 }`, where the `before` cursor identifies the `repo one` result, but then the result you're returning for that fetch includes the `repo one` edge again (with the same cursor). Shouldn't the backward result either return no edges (if there's nothing before the first result), or a different edge (maybe `edge zero`), with its own distinct cursor? Given that you return `edge one` again, I think it's pretty reasonable for the client to assume you really meant to add another `repo one` edge before the original `repo one` edge.

**Comment by sleepycat** [comment]
Sorry, that was supposed to paginate back to repo one again.
I've updated the fetchMore for the BACKWARD query to the correct cursor:  `{ before: "Y3Vyc29yOnYyOpHOAA_zRw==", last: 1 }`, which points back to the original `repo one` edge. 

With that fixed, the idea is that looking at "repo one", and clicking `next` should display the result for `repo two` and only that result. The test shows that both `repo one` and `repo two` are displayed.

```html
      <div>
        <ul>
          <li>
            repo one
          </li>
          <li>
            repo two
          </li>
        </ul>
        <button>
          next
        </button>
        <button>
          previous
        </button>
      </div>
```

If you remove the ` expect(queryByText(/repo one/)).not.toBeInTheDocument();` on line 227 instead of displaying both results on page two, it displays both results after returning to page one. This is what I'm getting at with the "too many results" thing.

As soon as `next` is clicked, both results are in the cache, and both are being displayed. 
Since I'm only asking for one, I should only get one. Looking at [the implementation](https://github.com/apollographql/apollo-client/blob/d8eaa3904db8203e15f6feafc7d53b46bb902a3c/src/utilities/policies/pagination.ts#L93-L108) I was expecting to see the first/last values being used somewhere with a slice, but maybe that happens elsewhere. 

Thanks for looking at this.

**Comment by benjamn** [comment]
Ok, thanks for the update!

With that out of the way, I think the next thing to explain is that the `relayStylePagination` helper (like the other helpers in that module) chooses not to implement a custom `read` function to match the `merge` function, which means the original query will always receive the full known list, which can be sliced/paginated in application code. This matches the way `fetchMore` has traditionally worked, though I have to admit it was a surprise to me that you might not need a `read` function.

Here's another comment where I get into these details: https://github.com/apollographql/apollo-client/issues/6729#issuecomment-665695481. Specifically this bit:

> As a final note, it may be tempting to define a `read` function to go along with your `merge` function, but we've found that `read` functions are often unnecessary when using `fetchMore`, and can complicate things because you have to update the variables for the original query to match the new longer list. With no `read` function and `keyArgs: false`, the list just keeps growing, and you don't have to worry about updating the original query.

I dug up an older (untested!) [implementation](https://gist.github.com/benjamn/dc8502a9c5dd6cc4438c72bdffdad7a2) of `relayStylePagination` that did have a `read` function, if you're curious what that might look like. If you want to use that code, I _think_ you just need to make sure you update the variables of the original query (maybe in a `.then` callback after `fetchMore`) to match the list you want to slice out. But also, this has been a tricky bit of code to get right, so I can't vouch for every detail of this old code.

**Comment by jdpst** [comment]
@benjamn Is there any plan for the `relayStylePagination` helper to handle the `first` and `last` Relay parameters? It is very surprising that it does not already do so IMO. 

To make sure I am understanding, could you clarify for me that:

1. this helper always returns the full list of cached results, not the requested page using `first`/`last` (i.e. does not support actual pagination as is)

2. fixing the above bug requires a custom read function (and therefore also maintaining the duplicated merge function)

3. writing robust custom `read` functions requires specialist knowledge of how the cache works (e.g. incorporating `keyArgs`) and is error-prone

I am hoping this can be resolved in a patch sometime soon, because the `updateQuery` API (which works without fuss) is being deprecated.

**Comment by raysuelzer** [comment]
This API change seems to make a pretty big assumption that developers won't be using traditional pagination and infinite scroll for the same query.

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
