### ISSUE TITLE
In version 3, how are we suppose to handle cache dataIds?

### ISSUE THREAD

**Issue by ashah888** [apollographql/apollo-client#6794]
In version 2 apollo client, we were able to use the "dataIdFromObject()" function to assign dataIds by whatever we want, (such as id) -- but if the Type did not have an Id, Apollo was smart enough to make sure that changes were always up to date by auto-assigning the dataId based on query.

This was very useful. But in version 3, it appears very data type is forced to have a dataId of some sort because it no longer auto-assigns dataId based on query.

But not every data type has an ID. What do we do in this case?

For example, Type User will have a id (userId) so it's easy to assign a dataId, but UserProfile, which is a sub type of Type User, doesn't have an id, and imo it shouldn't need it if it's a child type of User.

What do we do in this case? Are we forced to change our GraphQL Schema to force every type to have a unique identifier?

Also, what do we do with dataIds for queries?

I've also tried defaultDataIdFromObject() but it always returns null. (Could be a bug)

What is the recommended best practice here?

It took me a while to realize my app was breaking in multiple places because of this dataId change.

**Comment by sirugh** [comment]
Have you read about, or attempted to use `keyFields`?

https://www.apollographql.com/docs/react/caching/cache-configuration/#customizing-identifier-generation-by-type

Also, if you disable normalization (ie you don't have an `id` and you don't specify `keyFields` then it will just be accessed through the parent, as in your `UserProfile` example.

> Objects that are not normalized are instead embedded within their parent object in the cache. You can't access these objects directly, but you can access them via their parent.

**Comment by amannn** [comment]
While the docs state that you can disable normalization on a case-by-case basis with `keyFields`, how would you do this globally for a large schema? I have a schema with 150+ types that is still growing. Do I have to set up `keyFields` for each individual type?

Using `dataIdFromObject: () => null` would be much easier, as it was possible with AC2.
