### ISSUE TITLE
SubscriptionResult error property is not guaranteed to be an ApolloError

### ISSUE THREAD

**Issue by jeddeloh** [apollographql/apollo-client#6801]
The `updateError` method of `SubscripitionData` class doesn't check that the incoming error is actually an `ApolloError` and instantiate one if not:
https://github.com/apollographql/apollo-client/blob/master/src/react/data/SubscriptionData.ts#L131

**Intended outcome:**
I should be able to reliably check the length of `graphQLErrors` property on a `SubscriptionResult` to determine how to deal with an error

**Actual outcome:**
Checking the length of graphQLErrors results in a type error: `cannot read property length of undefined`

**How to reproduce the issue:**
Have a subscription error with a normal error or object that is missing the `graphQLErrors` property

**Versions**
  System:
    OS: macOS 10.15.5
  Binaries:
    Node: 12.18.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.105
    Safari: 13.1.1
  npmPackages:
    @apollo/client: 3.1.3 => 3.1.3
    @apollo/link-ws: 2.0.0-beta.3 => 2.0.0-beta.3
    reason-apollo-client: 0.0.1-beta.5 => 0.0.1-beta.5

**Comment by hwillson** [comment]
Closing for the reasons outlined in https://github.com/apollographql/apollo-client/pull/6894#issuecomment-1211433611. Thanks!
