### ISSUE TITLE
add hook for reactive variable

### ISSUE THREAD

**Issue by seeden** [apollographql/apollo-client#6818]
I would like to use simple react hook for rerender my component(instead of query) when reactive variable was changed.

For example useReactiveVariable(myReactiveVariable);

**Comment by benjamn** [comment]
This would definitely be a worthwhile feature.

In terms of the implementation, I believe reactive variables would need to have a more general-purpose listener API. Right now updating a reactive variable calls `cache.broadcastWatches()` on any caches previously involved in reading the variable, but that behavior could be generalized/exposed via `myVar.listen(newValue => {...})` or something similar.

**Comment by seeden** [comment]
I am glad that you like this idea. Thank you

**Comment by seeden** [comment]
thanks @benjamn

**Comment by Dodie324** [comment]
@benjamn Are there best practices on how to use `useReactiveVar` in an application? Let's say I want to replace custom context providers with reactive variables, how would I approach that? Can you co-locate reactive variables the way you could with a provider such that they're not accessible outside of their context?
