### ISSUE TITLE
Empty Array returned when it should be populated

### ISSUE THREAD

**Issue by kokokenada** [apollographql/apollo-client#6823]
**Intended outcome:**

This query was expected to return a populated CarePlan array
````
  patientRecord(where: PatientRecordWhereUniqueInput!): PatientRecord


         query onePatient($patientId: Int!) {
            patientRecord(where: { id: $patientId }) {
              id
              createdAt
              updatedAt
              firstName
              middleName
              lastName
              gender
              insuranceId
              dob
              User {
                id
                title
                firstName
                middleName
                lastName
                email
                phone
                role
                avatarColour
                avatarLink
              }
              CarePlan {
                id
                title
                description
                startDate
                updatedAt
              }
            }
          }
````
* By looking at the Network tab in chrome, I can confirm that the data is being returned by the server.
* The exact same query does return an array as expected when issued via the sandbox

**Actual outcome:**

* The array is empty

**How to reproduce the issue:**

Relevant parts of the schema:
````
  patientRecord(where: PatientRecordWhereUniqueInput!): PatientRecord


type PatientRecord {
  avatarColour: String
  avatarLink: String
  CarePlan(after: CarePlanWhereUniqueInput, before: CarePlanWhereUniqueInput, first: Int, last: Int): [CarePlan!]!
  CircleOfCare(after: CircleOfCareWhereUniqueInput, before: CircleOfCareWhereUniqueInput, first: Int, last: Int): [CircleOfCare!]!
  createdAt: DateTime!
  dob: DateTime
  firstName: String
  FormAssignment(after: FormAssignmentWhereUniqueInput, before: FormAssignmentWhereUniqueInput, first: Int, last: Int): [FormAssignment!]!
  forUserId: String
  gender: String
  id: Int!
  insuranceId: String
  lastActive: DateTime!
  lastName: String
  middleName: String
  OnboardingInvites: [Invitation!]
  title: String
  updatedAt: DateTime!
  User: User
}
````
**Versions**
  System:
    OS: macOS 10.15.2
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - ~/apps/hrh/csa/packages/ui/node_modules/.bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Safari: 13.0.4
  npmPackages:
    @apollo/client: 3.1.3 => 3.1.3 
    @apollo/link-context: 2.0.0-beta.3 => 2.0.0-beta.3 
    @apollo/link-error: 2.0.0-beta.3 => 2.0.0-beta.3 
    apollo: 2.30.2 => 2.30.2

**Comment by benjamn** [comment]
After the data is written to the cache, can you run `client.cache.extract()` in the console, find the `PatientRecord` object (probably under a key like `PatientRecord:<id>`), and see what property name is used to store the `CarePlan` field? It seems like that field has several optional arguments (`after`, `before`, `first`, `last`), so I'm curious if it's being stored using the simple string `CarePlan`, or if it has extra stuff at the end, like `CarePlan:({...})`.

Also, I'm guessing you would have shared your `typePolicies` if they seemed relevant, but definitely let us know if there's anything you're passing to the `InMemoryCache` constructor that might be related to these types/fields.

**Comment by hwillson** [comment]
We'll need a reproduction (using `@apollo/client@latest`) to be able to troubleshoot this further. Thanks!
