### ISSUE TITLE
 Huge performance degradation after migration to v3

### ISSUE THREAD

**Issue by ladarit** [apollographql/apollo-client#6828]
**Intended outcome:**
fast update of subscribed to local query components

**Actual outcome:**
I am storing data in InMemoryCache. My components are subscribed to this data. At client v3.1.3 after executing witeQuery with a large amount of data (300-400 objects), components, that watch to this query, receive updated data with a delay of ~ 9000ms. Before upgrading to v3 it was ~ 50ms. 
There were no changes in the codebase other than those indicated in the migration guide.

**to understand the scale of the problem:**
**apollo-client: 2.6.8 performance - good result**
[chrome_performanse_snapshot_apolloclient2.6.8.json.zip](https://github.com/apollographql/apollo-client/files/5064605/chrome_performanse_snapshot_apolloclient2.6.8.json.zip)
![apolloclient2 6 8notice](https://user-images.githubusercontent.com/37782060/90046741-8b38f080-dcd9-11ea-824a-b7d8c73d968d.jpg)

**apollo-client: 3.1.3 performance - bad result**
[chrome_performanse_snapshot_apolloclient3.1.3.json.zip](https://github.com/apollographql/apollo-client/files/5064608/chrome_performanse_snapshot_apolloclient3.1.3.json.zip)
![apolloclient3 1 3notice](https://user-images.githubusercontent.com/37782060/90047457-9d675e80-dcda-11ea-8884-c6a21d1b0316.jpg)

**Versions**
 

> **work fine:**

"@apollo/react-components": "^3.1.3",
		"@apollo/react-hoc": "^3.1.3",
		"@apollo/react-hooks": "^3.1.3",
"apollo-utilities": "^1.3.3",
"graphql-tag": "^2.10.3",
"apollo": "^2.24.0",
		"apollo-cache-inmemory": "^1.6.5",
		"apollo-client": "^2.6.8",
		"apollo-link": "^1.2.13",
		"apollo-link-error": "^1.1.12",
		"apollo-link-http": "^1.5.16",
"graphql": "14.6.0",

> **work bad:**

"@apollo/client": "^3.1.3",
"apollo": "^2.30.2",
"graphql": "^15.3.0",

after migrating to v3 I see numerous method calls: resolveField, resolveSelectionSet. I assume that these methods are called when apolloclient trying to get data from the InMemoryCache to update the components. Please tell me how to solve this problem

**Comment by benjamn** [comment]
I'm not familiar with `ApolloCacheManager`, so I can't speak to whether/how that abstraction might be contributing to the problem, but I would generally recommend moving away from local resolver functions and towards [`InMemoryCache` field policies](https://www.apollographql.com/docs/react/caching/cache-field-behavior/). If you need help with that, I'd be curious to see what sort of local resolver functions you're currently using.

**Comment by ladarit** [comment]
> I'm not familiar with `ApolloCacheManager`, so I can't speak to whether/how that abstraction might be contributing to the problem, but I would generally recommend moving away from local resolver functions and towards [`InMemoryCache` field policies](https://www.apollographql.com/docs/react/caching/cache-field-behavior/). If you need help with that, I'd be curious to see what sort of local resolver functions you're currently using.

Hmm, i don't use local resolvers, i don't need them. In the apollo devtools i see correct normalized data structure.

**Comment by benjamn** [comment]
If you're not using local resolvers, Apollo Client shouldn't be spending any time in the `LocalState` code.

Generally speaking, this performance explosion doesn't sound like anything else we've encountered or heard about, so it might be worth continuing to investigate on your side. Maybe there's something weird about the interaction of Bluebird promises with Apollo Client (guessing from `_settlePromiseCtx` etc.)? I'm genuinely curious to know what's up, but I can't tell much from the information you've provided.

**Comment by ladarit** [comment]
this is a part of my shema:
`type rootQuery {cachedUnitNomenclaturesWithHash(
unitByYearEntityInput: UnitByYearEntityInput!
		# page number
		"""
		page number
		"""
		pageNumber: Int!
		# pageSize
		"""
		pageSize
		"""
		pageSize: Int!
		# sortField
		"""
		sortField
		"""
		sortField: String = null
orderOnlyByOrderIndex: Boolean = null
	): CachedUnitNomenclaturesWithHash`

**Comment by ladarit** [comment]
**this is a part of my shema:**
```graphql
schema {
  query: rootQuery
}

type rootQuery {
	cachedUnitNomenclaturesWithHash(
		unitByYearEntityInput: UnitByYearEntityInput!,
		pageNumber: Int!,
		pageSize: Int!, 
		sortField: String = null, 
		orderOnlyByOrderIndex: Boolean = null
	): CachedUnitNomenclaturesWithHash
}

type CachedUnitNomenclaturesWithHash implements Node {
	id: ID!
	cachedNomenclaturesByUnit: [CachedNomenclatureEntityModel]
	initialHash: String!
	hash: String!
	uuid: String!
}

type CachedNomenclatureEntityModel implements Node {
	model: NomenclatureByUnitsEntityModel!
	id: ID!
	initialHash: String!
	highlited: Boolean!
	selected: Boolean!
	markedAsDeleted: Boolean!
	isNew: Boolean!
}

type NomenclatureByUnitsEntityModel {
	id: ID!
	...other simple fields like strings, numbers, without objects
}
```

**my query and used by it fragments (all components that watch this query have fetchpolicy 'cache-only'):**
```graphql
const CachedNomenclaturesByUnitQuery = gql`
   query CachedNomenclaturesByUnitQuery($unitByYearEntityInput: UnitByYearEntityInput!, $pageNumber: Int!, $pageSize: Int!, $orderOnlyByOrderIndex: Boolean) {
      cachedUnitNomenclaturesWithHash(unitByYearEntityInput: $unitByYearEntityInput, pageNumber: $pageNumber, pageSize: $pageSize, orderOnlyByOrderIndex: $orderOnlyByOrderIndex) {
         ...CachedUnitNomenclaturesWithHashModel
         __typename
      }
   }
   ${CachedUnitNomenclaturesWithHashModelFragment}
`

const CachedUnitNomenclaturesWithHashModelFragment = gql`
   fragment CachedUnitNomenclaturesWithHashModel on CachedUnitNomenclaturesWithHash {
      __typename
      id
      hash
      initialHash
      uuid
      cachedNomenclaturesByUnit {
         ...CachedNomenclatureModel
            __typename
         }
      }
   ${CachedNomenclatureModelFragment}
`

const CachedNomenclatureModelFragment = gql`
   fragment CachedNomenclatureModel on CachedNomenclatureEntityModel {
      model {
         ...NomenclatureByUnitsModel
      }
      id
      initialHash
      selected
      highlited
      markedAsDeleted
      isNew
   }
   ${NomenclatureByUnitsModelFragment}
`;

const NomenclatureByUnitsModelFragment = gql`
   fragment NomenclatureByUnitsModel on NomenclatureByUnitsEntityModel {
      id
      ...other simple fields like strings, numbers, without objects
   }
`;

```

**my writeQuery function is:**

```typescript
private static UpdateNomenclaturesByUnitInCache = (client: ApolloClient<any>, settings: any, dataset: CachedNomenclatureModel[], unit: UnitByYearEntityModel, pagerData: IQueryPagerData, sortType: 'byOrg' | 'byIndex'): Promise<boolean> => {
  return new Promise((resolve, reject) => {
    try {
      unit ? unit.__typename = 'UnitByYearEntityModel' : null;		
      client.writeQuery<CachedNomenclaturesByUnitQueryType, CachedNomenclaturesByUnitQueryVariables>({
            query: CachedNomenclaturesByUnitQuery,
            variables: {
                  unitByYearEntityInput: unit,
                  pageNumber: pagerData.page,
                  pageSize: pagerData.pageSize,
                  orderOnlyByOrderIndex: sortType === 'byIndex'
            },
            data: {
                  cachedUnitNomenclaturesWithHash: {
                        id: unit.id + '_' + pagerData.page + '_' + pagerData.pageSize + '_' + sortType,
                        __typename: 'CachedUnitNomenclaturesWithHash',
                        hash: settings.newHash,
                        initialHash: settings.initialHash,
                        uuid: settings.requestUuid,
                        cachedNomenclaturesByUnit: dataset
                  }
            }
      });
      resolve(true);
    } catch (error) {
      reject(error);
    }
  });
};
```
**my function to obtain data for pass it to writeQuery function:**
```typescript
public static setSelectedNomenclatureIndex = (client: ApolloClient<object>, unit: UnitByYearEntityModel, pagerData, sortType): void => {
   const currentData = UnitNomenclaturesDAOCacheManager.getNomenclaturesFromCache(client, unit, pagerData, sortType);
   if (some(currentData)) {
      let nextSelected = cloneDeep(find(currentData, (u) => u.model.id === selectedRow.id));
      if(nextSelected) {
         //using produce from immer.js for immutability
         const newData = produce(currentData, (draft) => {
            //do some stuff with data
         });
         const settings = //create some obj with has fields
         UpdateNomenclaturesByUnitInCache(client, settings, newData, unit, pagerData, sortType);
      }
   }
};
```
all my operations with apollo client i`m doing with client instanses, passed from components. Maybe this is mistake? Maybe i must import client in file, where writeQuery function placed and not pass client to writeQuery fn from component? may be I have some mistakes im my schema?

**Comment by ladarit** [comment]
I found a problem. I used ```@client(always: true)``` in many places to force update components with fresh data. Disabling of ```(always: true)``` resolve my problem with throttling, but now component receive old data after writeQuery fn completed. Any advices?
