### ISSUE TITLE
How do I close a web socket connection?

### ISSUE THREAD

**Issue by BrendanKoral** [apollographql/apollo-client#6829]
Hello,

I'm working on a React app that allows users to visit a specific route and connect using web sockets for live updates to specific information. This feature is intended to work only on this route, so the connection is not needed after the user navigates away from the route. At that point, I would like to close the connection to save resources, both on my server and on the client's device. 

How do I close a web socket connection that I started using `new WebSocketLink()`? I'm hoping I overlooked something in the documentation, but I haven't found a solution yet. Web sockets normally have a `close()` [method](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/close) that can be called to terminate the connection. 

The code I'm using in my app to open the connection is below. It's from the Subscriptions section of the Apollo React documentation.  

Thanks in advance for your help!

```import { WebSocketLink } from '@apollo/client/link/ws';

const wsLink = new WebSocketLink({
  uri: `ws://localhost:5000/`,
  options: {
    reconnect: true
  }
});

**Comment by Gilwe** [comment]
`WebsockerLink` should have a private member called `subscriptionClient` which has the `close()` function for closing the websocket:

`wsLink.subscriptionClient.close()`

I suggest you `npm install subscriptions-transport-ws` to use and see more of this functionality

**Comment by MikaStark** [comment]
@Gilwe that's the problem : subscriptionClient is private and so cannot be accessed
