### ISSUE TITLE
client.query({query}) with fragment doesn't return fragmented fields

### ISSUE THREAD

**Issue by piglovesyou** [apollographql/apollo-client#6836]
`client.query({query})` with fragment doesn't return fragmented fields.

Because of this, currently, a code generated by [TypeScript React Apollo of GraphQL code generator](https://graphql-code-generator.com/docs/plugins/typescript-react-apollo) doesn't work.

Please correct me if I miss something. Thanks.

```javascript
const {ApolloClient, InMemoryCache, gql} = require('@apollo/client'); // v3.1.3
const {deepStrictEqual} = require('assert');

const query = gql`
    query Viewer {
        viewer {
            ...Partial
            status
        }
    }
    fragment Partial on User {
        id
        name
    } `;

const cache = new InMemoryCache()
cache.writeQuery({
    query,
    data: {
        viewer: {
            id: 'id',
            name: 'name',
            status: 'status',
        }
    }
})

const client = new ApolloClient({ cache });

async function main() {
    const {data: {viewer}} = await client.query({ query })
    deepStrictEqual(viewer, {
        id: 'id',
        name: 'name',
        status: 'status',
    })
}

main().catch(err => {throw err});
```
**Intended outcome:**

The above code runs without errors.

**Actual outcome:**

It throws the error below.

```
+ expected - actual

  {
+   id: 'id',
+   name: 'name',
    status: 'status'
  }
```

**How to reproduce the issue:**
https://codesandbox.io/s/cranky-feistel-8ei88?file=/index.js

**Versions**
```
  System:
    OS: macOS 10.15.6
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Safari: 13.1.2
  npmPackages:
    @apollo/client: ^3.1.3 => 3.1.3
```

**Comment by benjamn** [comment]
@piglovesyou I think the `viewer: {...}` object in the `data` that you're writing into the cache needs to contain `__typename: "User"`. Apollo Client requests the `__typename` field automatically in most cases, but you need to provide it explicitly when you're providing the data (rather than letting the client get the data from the network for you).

**Comment by piglovesyou** [comment]
@benjamn That is the answer... thank you! I did forget supplying `__typename` to the cache data so that's why the request didn't match the cache. An embarrassing mistake, thank you for saving my time!
