### ISSUE TITLE
Infinite loop when using a fragment that import itself

### ISSUE THREAD

**Issue by Banou26** [apollographql/apollo-client#6838]
**Intended outcome:**
Having an error thrown saying that you cannot import a fragment in itself with the name of the badly imported fragment.

**Actual outcome:**
Currently thrown error is `Uncaught Error: Maximum call stack size exceeded`

**How to reproduce the issue:**
Try to use a query with a self-importing fragment, e.g:
```ts
export const PACKAGE_BUNDLE_FRAGMENT = gql`
  fragment PackageBundleFragment on PackageBundle {
    ...PackageBundleFragment
   archive
  }
`
```

**Comment by benjamn** [comment]
That's a fair point, though I would want to avoid adding overhead to the cache reading pipeline to track/catch this problem at runtime, if possible. I think it might make more sense to check for this problem the first time we encounter the query, perhaps in [`QueryManager#transform`](https://github.com/apollographql/apollo-client/blob/a79edf96aebe0962e8ca62a9b95bc76ff7e01622/src/core/QueryManager.ts#L379). I also wonder if static analysis could catch this at build time.
