### ISSUE TITLE
[Network error]: TypeError: forward is not a function

### ISSUE THREAD

**Issue by minipai** [apollographql/apollo-client#6850]
I tried to use `Error Link` as in document's example

```
const link = onError(({ graphQLErrors, networkError }) => {
  if (graphQLErrors)
    graphQLErrors.map(({ message, locations, path }) =>
      console.log(
        `[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`
      )
    )
  if (networkError) console.log(`[Network error]: ${networkError}`)
})
const apolloClient = new ApolloClient({
  uri: '/graphql',
  cache: new InMemoryCache(),
  link: ApolloLink.from([link])
})
```
but got the following in the console.

```
[Network error]: TypeError: forward is not a function
```

After some try, I found adding HttpLink would work

```
const apolloClient = new ApolloClient({
  cache: new InMemoryCache(),
  link: ApolloLink.from([link, new HttpLink({uri: '/graphql'})])
})
```

Probably worth mention it in the doc.

**Comment by Marcohj** [comment]
Same issue here. The example in the Docs seems "unfinished" in how ApolloClient 3 expects us to handle onError.

**Comment by balazsorban44** [comment]
With the following code, I still get the error:

```js

const errorLink = onError(({ graphQLErrors, networkError, forward, operation }) => {
  if (graphQLErrors) {
    logger.error(graphQLErrors)
  }
  if (networkError) {
    logger.warn(networkError)
  }
  forward(operation)
})

function createApolloClient() {
  return new ApolloClient({
    cache: new InMemoryCache(cacheConfig),
    connectToDevTools: process.env.NODE_ENV === "development",
    link: errorLink,
    uri: process.env.NEXT_PUBLIC_CONTENT_API,
  })
}
```

```
ApolloError: forward is not a function
...
networkError: TypeError: forward is not a function
```

I am on `@apollo/client@3.1.3"`

**Comment by atstojanov** [comment]
It seems that the errorLink must not be the first link in the chain. I've moved the error link between my authentication and http link and the error disappeared.

```
  return new ApolloClient({
    link: from([authLink, errorLink, httpLink]),
    cache: new InMemoryCache(),
  });
```

Is this behavior intentional or is it a bug?

**Comment by thesimpledev** [comment]
@atstojanov Thanks for this! This worked. But, it would be helpful if the example/documentation was changed if this is intentional (which I'm assuming it's not).

Great work on everything so far. Apollo client is awesome! :)

**Comment by hwillson** [comment]
The docs have been updated quite a bit since this issue was opened. Let us know if you still think this is an issue. Thanks!

**Comment by rhayart** [comment]
For those who still encounter this issue, it was for me that i used an ApolloLink with async. Removing async or using setContext insteed solved the issue.

**Comment by justdvl** [comment]
Reordering links in apollo-client config helps.. Good order is: httpLink, authorizationLink, retryLink, errorLink, cacheLink.
