### ISSUE TITLE
useQuery skip crashes when toggled: "Expecting a parsed GraphQL document"

### ISSUE THREAD

**Issue by sfcgeorge** [apollographql/apollo-client#6853]
**Intended outcome:**

useQuery skip should continue working after being toggled. It should skip the network request when skip is true. It should re-fetch when skip is togged from true to false.

**Actual outcome:**

After toggling the boolean state of the useQuery `skip` option twice Apollo crashes with:

"Uncaught Invariant Violation: Expecting a parsed GraphQL document. Perhaps you need to wrap the query string in a "gql" tag?"
(Full trace at bottom.)

**How to reproduce the issue:**

Toggle a `useQuery` back and forth from `skip: true` to `skip: false` and vice versa. 

**Versions**

`@apollo/client` package

3.2 beta 2: Broken.
3.1.3: Broken.

In 3.1.1 this error doesn't happen but there are 2 other issues. 
* Requests are made when variables change even if skip is true (looks like that's [already been fixed](https://github.com/apollographql/apollo-client/commit/c0ec90d9f8be521e1c1cb678002ecc209381da4e#diff-fd2ae033c9b90f5e2c0f060ff67bf095R230)). 
* Toggling skip from false to true _doesn't_ re-fetch the query as it should. _Maybe_ this is to do with the changes to "cache-and-network".

This all worked fine in Apollo 2. AKA changing variables only caused queries to refetch when `skip: false`. And changing skip to true _did_ re-fetch the query. And of course nothing to do with missing gql.

```

  | InvariantError | @ | invariant.esm.js:21
-- | -- | -- | --
  | invariant | @ | invariant.esm.js:34
  | checkDocument | @ | getFromAST.js:4
  | getOperationDefinition | @ | getFromAST.js:18
  | getQueryDefinition | @ | getFromAST.js:36
  | StoreReader.diffQueryAgainstStore | @ | readFromStore.js:67
  | InMemoryCache.diff | @ | inMemoryCache.js:136
  | QueryInfo.getDiff | @ | QueryInfo.js:57
  | ObservableQuery.getCurrentResult | @ | ObservableQuery.js:108
  | QueryData._this.getQueryResult | @ | QueryData.js:43
  | QueryData.getExecuteResult | @ | QueryData.js:202
  | QueryData.execute | @ | QueryData.js:141
  | (anonymous) | @ | useBaseQuery.js:52
  | useDeepMemo | @ | useDeepMemo.js:9
  | useBaseQuery | @ | useBaseQuery.js:51
  | useQuery | @ | useQuery.js:3


```

**Comment by ryanhefner** [comment]
@sfcgeorge Were you able to find a workaround for this? I think I am running into a similar issue. Any insights you might have on this would be greatly appreciated! 🙏

**Comment by sfcgeorge** [comment]
We used the following workaround instead of skip. Pretty frustrating.

 ```typescript
import { OperationVariables } from '@apollo/client'
import { DocumentNode } from 'graphql'
import { useQuery, QueryHookOptions } from '@apollo/client'

// In Apollo v3 `skip` is quite broken so we have to remove it and replace it
// with a fetchPolicy hack.
// https://github.com/apollographql/apollo-client/issues/6853
const useSkippableQuery = <TData = any, TVariables = OperationVariables>(
  query: DocumentNode,
  options: QueryHookOptions<TData, TVariables>
) => {
  const { skip, ...rest } = options
  const opts = {
    ...rest,
    fetchPolicy: skip
      ? ('cache-only' as 'cache-only')
      : ('cache-and-network' as 'cache-and-network')
  }

  return useQuery<TData, TVariables>(query, opts)
}

export default useSkippableQuery
```

**Comment by Hianz** [comment]
We are facing the same issue. This issue still exists even in the latest v3.3.0-beta.12.

**Comment by mogzol** [comment]
Still seeing this on 3.3.1, makes the skip argument pretty useless, would be nice if it could get fixed.

@sfcgeorge's solution sort of works, but can result in MissingFieldErrors if your query arguments change or the requested fields aren't in the cache for whatever reason. I made a different workaround that just executes an empty, client-only query whenever skip is true:

```typescript
import {
  DocumentNode,
  gql,
  OperationVariables,
  QueryHookOptions,
  TypedDocumentNode,
  useQuery,
} from "@apollo/client";

const SKIP_QUERY = gql`
  query SkipQuery {
    skipped @client @skip(if: true)
  }
`;

// In Apollo v3 `skip` is broken, so replace with an empty query whenever skip is true
// https://github.com/apollographql/apollo-client/issues/6853
export function useSkippableQuery<TData = any, TVariables = OperationVariables>(
  query: DocumentNode | TypedDocumentNode<TData, TVariables>,
  options: QueryHookOptions<TData, TVariables>
) {
  const { skip, ...otherOptions } = options;
  return useQuery<TData, TVariables>(skip ? SKIP_QUERY : query, skip ? {} : otherOptions);
}
```

**Comment by hwillson** [comment]
If someone can provide a small runnable reproduction that demonstrates this happening with `@apollo/client@latest`, we'll take a closer look. Thanks!

**Comment by mogzol** [comment]
Just tried this again on 3.7.9 and it seems to work properly now, so this issue can probably be closed.

Demo:
https://codesandbox.io/s/apollo-usequery-skip-error-updated-u9r79h

**Comment by alessbell** [comment]
Thanks very much for the sandbox, @mogzol! Indeed, this appears to have been resolved. Closing for now, but for those on this thread, please feel free to open a new issue if this or any related issues persist. Thanks!
