### ISSUE TITLE
Apollo Client 3 - optimistic response with pollInterval doesnt work.

### ISSUE THREAD

**Issue by andymrussell** [apollographql/apollo-client#6858]
**Intended outcome:**

When using optimisticResponse or using cache.writeQuery as part of a mutation, components using pollInterval don't seem to update until the payload from the mutation has been successful.

I have 2 components using the same data. 1 is polling, the other fetches the data from the cache - network.
The non polling component updates correctly, however the polling component waits from the response to come back from the API before updating. 

**Actual outcome:**

Once, the response comes back from the server the polling component updates.

**How to reproduce the issue:**

Query some data using a hook:
`
const { data, refetch } = useGetChannelByIdQuery({
  skip: !activeChannel,
  variables: { id: activeChannelId! },
  fetchPolicy: 'cache-and-network',
  pollInterval: 3000,
});
`

Create a mutation and set an optimistic response:
`
    const onFavoriteChannel = (isFavorite: boolean) => {
        onFavoriteChannelMutation({
            variables: { input: { id: props.channel.id, isFavorite } },
            optimisticResponse: {
                __typename: 'Mutation',
                favoriteChannel: {
                    id: props.channel.id,
                    name: props.channel.name,
                    isFavorite,
                    __typename: 'Channel',
                },
            },
        });
    };
`

OR anything with proxy.writeQuery:

Remove the pollInterval from the query, to confirm it works.

**Versions**

  System:
    OS: macOS Mojave 10.14
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 28.0
    Safari: 12.0
  npmPackages:
    @apollo/client: ^3.1.3 => 3.1.3

**Comment by benjamn** [comment]
Can you try `@apollo/client@3.2.0-beta.3`? I have a hunch that #6854 could possibly be related to this.

**Comment by andymrussell** [comment]
Just tried it, and it looks to be the same issue.

However, it looks like if I bump the polling to 30 seconds from 3 seconds, it works as expected until its first poll response comes back. 
At that point it starts to fail as mentioned above.
Not sure if that helps in anyway?

**Comment by benjamn** [comment]
@andymrussell Ok, I have a slightly stronger hunch that `@apollo/client@3.2.0-beta.5` (which includes #6893) will help with this issue (thanks to c4d100f9f6a3ed87b33f0ef5f8945a4403c0b7b4), if you want to try that.

**Comment by gastonmorixe** [comment]
@benjamn this is still broken in v3.3.13

**Comment by gastonmorixe** [comment]
btw, tried **3.4.0-beta.19** and it's broken too

**Comment by andrujoh** [comment]
> @benjamn this is still broken in v3.3.13

Same for me. For now. I am considering setting up a graphql subscription to handle it.

**Comment by gastonmorixe** [comment]
@andrujoh good work around, I ended up going for subscriptions.

**Comment by brainkim** [comment]
Thanks for reporting!

I attempted to reproduce the issue [here](https://github.com/apollographql/react-apollo-error-template/tree/optimistic-mutation-and-polling) but could not replicate the issue you were describing. I am probably misunderstanding the exact way your queries and mutations are set up. If you can try and create a runnable reproduction, I’ll take another look!

**Comment by brainkim** [comment]
Might be related to https://github.com/apollographql/apollo-client/issues/7115

**Comment by m-lautenbach** [comment]
I had the same issue, but updating from `3.1.3` to `3.4.17` fixed it for me.

As described above, optimistic updates worked until the first polling happened. Afterwards, the cache would only update with the server response of the mutation.

**Comment by alessbell** [comment]
Thanks for the update, @m-lautenbach! I'm going to close this issue in that case, but if anyone can provide a runnable reproduction with `v3.4.17` or greater (via [CodeSandbox](https://codesandbox.io/s/github/apollographql/react-apollo-error-template) or forkable [GitHub repo](https://github.com/apollographql/react-apollo-error-template)), please drop a comment here and we will re-open. Thanks!
