### ISSUE TITLE
APC3: concatPagination and fetchMore not working for me.

### ISSUE THREAD

**Issue by TrevorNovak** [apollographql/apollo-client#6862]
First of all, thanks for all of the work you all doing, I greatly appreciate it.

I am fetching a paginated array of data using query params (e.g. page=2) and then simply need to concatenate the next page to the array of existing data. 

For instance, the schema for the data being returned looks like

```
Records {
   records: [Record]
   total: Int,
   pages: Int,
}
```

Then in `new InMemoryCache()` I have defined:
```
typePolicies: {
   Records: {
      fields: {
        records: concatPagination(),
      }
  }
}
```

I am then feeding this data into a `FlatList` in React Native, however, the `data` field is always just the first page of results and `existing` array is always `[]` even though ` incoming` appears to always contain the next page of data. I have tried using  `concatPagination()` as well as a `merge` function (which is how I was able to check what was in the `existing` array. 

Any thoughts on what I am doing wrong?

**Comment by maxgr0** [comment]
Got the same issue.
Fixed it temporarily by defining the Type Policy as presented in the docs and using
```
fetchMore({
  // updateQuery: (_previousResult, {fetchMoreResult}) => fetchMoreResult
})
```
This triggers the deprecation notice but works as a temp. fix for me.

**Comment by TrevorNovak** [comment]
> Got the same issue.
> Fixed it temporarily by defining the Type Policy as presented in the docs and using
> 
> ```
> fetchMore({
>   // updateQuery: (_previousResult, {fetchMoreResult}) => fetchMoreResult
> })
> ```
> 
> This triggers the deprecation notice but works as a temp. fix for me.

Ideally I want to leverage the type policy merge ability but I appreciate the idea.

**Comment by kluivert-queiroz** [comment]
Got the same(I think) issue. The query was made but not updating it on the UI, the `existing` array was always empty and the `incoming` arg was always the type name.
My pagination was a nested relation, just like yours. When I using `relayStylePagination` the data didn't load.
My schema:
```graphql
# schema
type{
  me: SuffixCustomer! @auth
}
type SuffixCustomer{
  # ...
  orders: [Order!]!
}
```
So my query looked like:
```graphql
query myOrders($cursor: String){
  me(cursor: $cursor){
    orders{
      # ...
    }
 }
}
```

I was trying to fill the `typePolicies` like it is in query, but it didn't work until I fill it like it is in server.
Like so:
```javascript
typePolicies: {
// instead of this,
      me: {
        fields: {
          orders: relayStylePagination(),
        },
      },
// I used this
      SuffixCustomer: {
        fields: {
          orders: relayStylePagination(),
        },
      },
    },
```
I think Apollo needs to know for what type the pagination is coming from, so pagination for orders comes from `SuffixCustomer` type.
Perhaps this can work for you too?

**Comment by TrevorNovak** [comment]
> Got the same(I think) issue. The query was made but not updating it on the UI, the `existing` array was always empty and the `incoming` arg was always the type name.
> My pagination was a nested relation, just like yours. When I using `relayStylePagination` the data didn't load.
> My schema:
> 
> ```graphql
> # schema
> type{
>   me: SuffixCustomer! @auth
> }
> type SuffixCustomer{
>   # ...
>   orders: [Order!]!
> }
> ```
> 
> So my query looked like:
> 
> ```graphql
> query myOrders($cursor: String){
>   me(cursor: $cursor){
>     orders{
>       # ...
>     }
>  }
> }
> ```
> 
> I was trying to fill the `typePolicies` like it is in query, but it didn't work until I fill it like it is in server.
> Like so:
> 
> ```js
> typePolicies: {
> // instead of this,
>       me: {
>         fields: {
>           orders: relayStylePagination(),
>         },
>       },
> // I used this
>       SuffixCustomer: {
>         fields: {
>           orders: relayStylePagination(),
>         },
>       },
>     },
> ```
> 
> I think Apollo needs to know for what type the pagination is coming from, so pagination for orders comes from `SuffixCustomer` type. Now it works like a charm.
> Perhaps this can work for you too?

Thanks for taking the time to try and help me out. I am not sure I totally understand your example but I would love for you to help out. 

On the server, my schema looks like this:

```  
type Records {
    id: ID!,
    records: [Record],
    total: Int,
    pages: Int,
  }
```

The incoming array in the typePolicy is correct (in fact, I am using the promise that fetchMore returns to extract each next page), however, the existing is always empty. I would like to fix what you think I am doing wrong so I would appreciate your help. Thanks!

**Comment by kluivert-queiroz** [comment]
@TrevorNovak what kind of pagination are you trying to use (cursor, offset, etc)? I'm not very experienced with Apollo, so I can just help with `relayStylePagination` that is cursor pagination based. There are a reason for you to use `concatPagination` instead?
When I tried to use `concatPagination` I faced the same issue, maybe there's something to make it work.

**Comment by TrevorNovak** [comment]
@kluivert-queiroz We are using params (e.g. page=2) -- the actual pagination is working in the sense that when I use fetchMore and pass in the next page number, it is retrieving and returning the next page of items (the incoming array contains the next page of items). `concatPagination` is recommended by Apollo to use in the Type Policy for merging the incoming and existing arrays together, however, I have tried defining it explicitly like so:

```
merge(existing = [], incoming: any[]) {
     return [...existing, ...incoming]
}
```
I believe `concatPagination` performs a similar task. In any event, even an explicit merge function results in an empty `existing` array (I added a console.log statement to the merge function to check).

**Comment by venancioavila** [comment]
@trevorblades  I have the same problems. I use Offset-based, I see that the data is coming, but it doesn't change in the UI. I don't think I understand how the cache works yet. Did you manage to solve it?

**Comment by trevorblades** [comment]
@venancioavila I think you meant to ping @TrevorNovak. But while I'm here, I can share how I was able to get offet/limit pagination working in my app.

In my `ApolloClient` instance:

```js
// other imports
import {offsetLimitPagination} from '@apollo/client/utilities';

const client = new ApolloClient({
  link: httpLink,
  cache: new InMemoryCache({
    typePolicies: {
      Query: {
        fields: {
          // add the type policy on the field that you're trying to paginate
          // this field must support offset and limit arguments
          packs: offsetLimitPagination()
        }
      }
    }
  })
});
```

In your list component you could try something like this:

```jsx
const {data, loading, error, fetchMore} = useQuery(PACKS_QUERY, {
  variables: {
    limit: 10,
    offset: 0
  }
});

// handle loading/error states

return (
  <>
    {/* render packs */}
    <button
      onClick={() => {
        fetchMore({
          variables: {
            offset: data.packs.length
          }
        });
      }
    >
      More
    </button>
  </>
);
```

The important part is setting `offset` and `limit` variables in the original query, and then passing a new `offset` in my `fetchMore` call.

**Comment by venancioavila** [comment]
Hello @trevorblades! All right? Many thanks for the reply. Unfortunately, this solution didn't work for me. I do the pagination on my backend with the offset and limit, the backend already returns the page data. Apparently the apollo does all this on the front (I may be wrong). Well, my backend receives limit and offset and returns the desired data.

**Comment by jwelmac** [comment]
> @kluivert-queiroz We are using params (e.g. page=2, page=3, etc.) -- the actual pagination is working in the sense that when I use `fetchMore` and pass in the next page number, it is retrieving and returning the next page of items (the incoming array contains the next page of items). `concatPagination` is recommended by Apollo to use in the Type Policy for merging the incoming and existing arrays together, however, I have tried defining it explicitly like so:
> 
> ```
> merge(existing: any[], incoming: any[]) {
>      return [...existing, ...incoming]
> }
> ```
> 
> I believe `concatPagination` performs a similar task. In any event, even an explicit merge function results in an empty or undefined `existing` array (I added a console.log statement to the merge function to check).
> 
> I am sure I just do not understand how this works.


@TrevorNovak 
I was facing a similar issue to you and solved it using the [`@connection` directive](https://www.apollographql.com/docs/react/data/pagination/#the-connection-directive).

Let me explain as I didn't get it the first couple times I read it.
Here is an example solution using your info.

Schema
```
Records {
   records: [Record]
   total: Int,
   pages: Int,
}
```

Query
```
query GetRecords($page: Int) {
    records(page: $page) @connection(key: 'records') {
      # ...
    }
 }
```
typePolicy
```
typePolicies: {
      Query: {
        fields: {
          records: concatPagination()
        }
      }
    }
```

The `@connection(key: [keyname])` is the important bit. Without it each time `GetRecords` is called the variable that is passed to records is used to create a new key in the cache with that variable value as part of the key. 
By specifying the connection key it ensure future uses of the same query use the same key for records and pass the correct existing value to your merge function or strategy.
This specified key is what in the documentation is referred to as a stable key.

Here is a visual example of the cache after requesting pages 1 and 2

Without @connection
```
records(page: 1):
0:{"__ref":"Record:1"}
1:{"__ref":"Record:2"}
2:{"__ref":"Record:3"}
3:{"__ref":"Record:4"}
4:{"__ref":"Record:5"}

records(page: 2):
0:{"__ref":"Record:6"}
1:{"__ref":"Record:7"}
2:{"__ref":"Record:8"}
3:{"__ref":"Record:9"}
4:{"__ref":"Record:10"}
```


With @connection
```
records:
0:{"__ref":"Record:1"}
1:{"__ref":"Record:2"}
2:{"__ref":"Record:3"}
3:{"__ref":"Record:4"}
4:{"__ref":"Record:5"}
0:{"__ref":"Record:6"}
1:{"__ref":"Record:7"}
2:{"__ref":"Record:8"}
3:{"__ref":"Record:9"}
4:{"__ref":"Record:10"}
```

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
