### ISSUE TITLE
Separate queries when using or not using pagination on memory cache

### ISSUE THREAD

**Issue by decosvaldo** [apollographql/apollo-client#6873]
Hi everybody. Trying to update my code to use the new pagination structure inside the MemoryCache.

I have two queries on separate pages that returns the same __typename. One of them should not use pagination, because I'm taking just a set of new results and that's it. On the user page of my application, I need to run another query, with the same __typename, but now with the possibility to return more and more results using fetchMore. I'm trying to use KeyArgs, but with no success. I believe it should be used exactly on this scenario, to differ queries with the same __typename, right?

I'm using apollo client with NexusJS framework, so my queries and pagination are working fine when I use concatPagination out of the box with no custom changes. But obviously, it affects the other query everytime I run fetchMore.

Here are my basic setup:

```
const client = new ApolloClient({
  	link: authLink.concat(httpLink),
  	cache: new InMemoryCache({
    	typePolicies: {
			Query: {
				fields: {
					albumreviews: concatPagination()
				}
			}
		}
  	})
})
```

Here are my two albumreviews queries:

The one that needs pagination:
```
query albumreviews($offset:Int,$limit:Int,$user:Int)
    {
        albumreviews(first: $limit, skip: $offset, where:{
            AND: [{
                createdBy:{
                    equals: $user
                },
                status:{
                    equals: 1
                }
            }]
        },orderBy:{
            id: asc
        })
        {  
            id
            title
        }
}
```

The one without pagination:
```
query($first:Int)
    {
        albumreviews(first:$first,orderBy:{
            createdAt: desc
        },where:{
            status:{
                equals: 1
            }
        }){
            id
            title
            createdAt
            createdBy {
                id
                name
            }
            album {
                id
                name
                year
                artist {
                    id
                    name
                    genres {
                        id
                        name
                    }
                }
                votes{
                    id
                    vote
                    createdBy {
                        id
                    }
                }
                blobCover
            }
        }
    }

```
Am I correct on thinking that KeyArgs is the way to go? How should I configure it to use the new pagination structure without affecting the other queries that requests albumreviews without pagination?

I appreciate your help. If you need any other information, please let me know.

**Comment by decosvaldo** [comment]
Thank you for your nice reply. I'm going to study the information you gave me and get back here asap.

My first goal is to try to differentiate both situations (partial data with no pagination and merge paginated data for equal __typename queries). Let's see what I will come up with.

Thanks.

**Comment by decosvaldo** [comment]
OK, let's see if my code is close to a functional and recommended scenario.

On my GraphQL implementation, offset is represented by the skip arg, and I'm using it only when pagination is needed. So I believe that this is my guy to differentiate from the other albumreviews requests.
So, I created the code bellow:

```
cache: new InMemoryCache({
    	typePolicies: {
			Query: {
				fields: {
					albumreviews: {
						keyArgs: false,
						read(existing, { args }) {
							return existing
						},
						merge(existing, incoming, { args }) {
							if(args.skip){
								const merged = existing ? existing.slice(0) : [];
								const start = args ? args.skip : merged.length;
								const end = start + incoming.length;
								for (let i = start; i < end; ++i) {
									merged[i] = incoming[i - start];
								}
								return merged
							}else{
								return incoming
							}
						}
					}
				}
			}
		}
  	})
```

I've tried and it is working, despite the return of some undefined on console.log when no data is there to be printed, which I think that it is correct.
On the merge function, if there is no skip arg, it should only return the incoming set of values from the first query and nothing more. Also, I wrote a default ready function, which I discovered that it will work without doing it. So I ended with the code bellow:

```
cache: new InMemoryCache({
    	typePolicies: {
			Query: {
				fields: {
					albumreviews: {
						keyArgs: false,
						merge(existing, incoming, { args }) {
							if(args.skip){
								const merged = existing ? existing.slice(0) : [];
								const start = args ? args.skip : merged.length;
								const end = start + incoming.length;
								for (let i = start; i < end; ++i) {
									merged[i] = incoming[i - start];
								}
								return merged
							}else{
								return incoming
							}
						}
					}
				}
			}
		}
  	})
```

This is working for me. I just need to know if with only this piece of code I will have the queries separated inside the cache, since they are using the same __typename but bringing different results.

**Comment by btroia** [comment]
@benjamn I am also running into some challenges migrating an existing `fetchMore()` to the new `merge()`/`read()` pagination structure. In my case, I have a React Native app with some chat functionality that has some `fetchMore()` logic to handle fetching older messages/infinite scroll:

Query that returns chat messages for a group:
```
export const GET_CHAT_GROUP_AND_MESSAGES = gql`
  query GET_CHAT_GROUP_AND_MESSAGES(
    $chatGroupId: Int!,
    $messageLimit: Int! = 100,
    $lastMessageId: bigint = null,
  ) {
    chat_group {
      __typename
      key
      id
      name
    }
    messages: chat_messages(
      where: { id: { _lt: $lastMessageId }}
      order_by: { id : desc }
      limit: $messageLimit
    ) {
      __typename
      key
      id
      from {
        __typename
        id
        display_name
        profile_image_url
      }
      to_group_id
      text
      created_at
      updated_at
    }
  }
`;
```

Original function that calls `fetchMore()` to load previous messages/infinite scroll:

```
const loadEarlierMessages = () => {
    const messages = chatGroup?.messages;
    if (!messages) return;

    setIsLoadingMoreResults(true); // show loading indicator

    chatGroupQuery.fetchMore({
      variables: {
        chatGroupId,
        messageLimit: globalThis.app.messageLimit,
        lastMessageId: messages[messages.length - 1].id,
      },
      updateQuery: (currentData: { chatGroup: object }, { fetchMoreResult: newData }) => {
        const currentChatGroup = currentData?.chatGroup?.[0];
        const newChatGroup = newData?.chatGroup?.[0];

        let result = currentData;
        if (!newChatGroup?.messages?.length) {
          hasMoreResults.current = false; // disable infinite scroll
        } else {
          result = {
            chatGroup: [
              {
                ...currentChatGroup,
                messages: [...currentChatGroup?.messages, ...newChatGroup?.messages],
              },
            ],
          };
        }

        setIsLoadingMoreResults(false); // hide loading indicator
        return result;
      },
    });
  };
```

The above all works as expected.

I then updated my `loadEarlierMessages()` function to remove `fetchMore()` and instead call a lazy query hook:

```
const [
  chatGroupFetchMoreQuery,
  { called, loading: moreLoading, data: moreData, error },
] = useLazyQuery(GET_CHAT_GROUP_AND_MESSAGES);

const loadEarlierMessages = () => {
    const messages = chatGroup?.messages; // existing messages
    if (!messages) return;
    setIsLoadingMoreResults(true);

    // call lazy query hook, which triggers merge in typePolicy
    const newMessages = chatGroupFetchMoreQuery({
      variables: {
        chatGroupId,
        messageLimit: globalThis.app.messageLimit,
        lastMessageId: messages[messages.length - 1].id,
      },
    });

    setIsLoadingMoreResults(false);
  };
```

Finally, I set up `typePolicies` to include a custom merge function (in this case I simply want to merge all of the existing and incoming data):

```
const cache = new InMemoryCache({
    typePolicies: {
      chat_group: {
        keyFields: ['key'], // using `key` field for cache identifier
        fields: {
          chat_messages: {
            merge(existing, incoming, { args }) {
              const merged = existing ? existing.slice(0) : [];
              if (merged.length > 0) {
                return [...merged, ...incoming]; <---- this isn't working
              }
              return incoming;
            },
          },
        },
      },
      chat_message: {
        keyFields: ['key'],
      },
    },
});
```
Everything seems to be working _except_ when the new messages are loaded, the `merge()` function isn't updating properly.

--> **side note/question**: Is the `merge()` function firing for every item in a result set intended behavior (i.e., if my `chat_messages` query returns 20 results, `merge()` is firing 20 times?

Thanks in advance! 🙏
