### ISSUE TITLE
useQuery with notifyOnNetworkStatusChange returns empty data object instead of undefined

### ISSUE THREAD

**Issue by prcdpr** [apollographql/apollo-client#6876]
**Intended outcome:**

`data` property should be either undefined or of type that is expected, not an empty object

**Actual outcome:**
![image](https://user-images.githubusercontent.com/43776797/90936069-cd161500-e404-11ea-87ee-946d5eabc8b4.png)

**How to reproduce the issue:**

https://codesandbox.io/s/confident-surf-ldjtu

**Versions**

```
  System:
    OS: Windows 10 10.0.18362
  Binaries:
    Node: 12.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.105
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @apollo/client: ^3.1.3 => 3.1.3
    apollo: ^2.30.2 => 2.30.2
```

**Comment by pepf** [comment]
@prcdpr  Think this can be closed? Upgraded your sandbox to latest stable client, and `data` is undefined as it should be :)

See: https://codesandbox.io/s/great-mestorf-pfbc1
