### ISSUE TITLE
Mutation documentation sill refers to this.props.mutation

### ISSUE THREAD

**Issue by Moataz-E** [apollographql/apollo-client#6879]
**Intended outcome:**
Follow the docs

**Actual outcome:**
Docs incorrectly referring to legacy React this.props

**How to reproduce the issue:**
Open link to documentation: [here](https://www.apollographql.com/docs/react/v2.5/essentials/mutations/)

**Versions**
N/A

**Comment by hwillson** [comment]
The docs have been updated quite a bit since this issue was opened. Let us know if you still think this is an issue. Thanks!
