### ISSUE TITLE
Why some queries as re run after a clearStore

### ISSUE THREAD

**Issue by Nikosmonaut** [apollographql/apollo-client#6882]
I struggle to understand why after a call to clearStore some queries are still called ?

It seems to be this chunk of code. Why in QueryManager observableQueries are not stopped ?

```
    this.queries.forEach(queryInfo => {
      if (queryInfo.observableQuery) {
        // Set loading to true so listeners don't trigger unless they want
        // results with partial data.
        queryInfo.networkStatus = NetworkStatus.loading;
      } else {
        queryInfo.stop();
      }
    });
```

Today I use clearStore to logout a user. So after my Authorization header is blacklisted server side I call to clearStore. And then some queries are rerun. But obviously returns an error because authorization is no more valid. Why is that ? How to prevent those queries to be called ?

**Comment by hwillson** [comment]
If someone can provide a small runnable reproduction that demonstrates this happening with `@apollo/client@latest`, we'll take a closer look. Thanks!
