### ISSUE TITLE
Warning about missing field on ROOT_QUERY when query variables change

### ISSUE THREAD

**Issue by lee-borsboom** [apollographql/apollo-client#6889]
**Intended outcome:**
Apollo should not warn about missing fields on ROOT_QUERY when query variables change

**Actual outcome:**
Under certain circumstances, when query variables change, Apollo logs a MissingFieldError warning, e.g.

> Can't find field 'people' on ROOT_QUERY object

**How to reproduce the issue:**
Reproduction here: https://github.com/lee-borsboom/react-apollo-error-template/tree/missing_field_root_query

Of course, to see this warning you must be running in development mode, you won't see it in a production build.

I was able to trigger this warning given the following:
* notifyOnNetworkStatusChange is true; AND
* the query requests data from multiple root-level fields; AND
* variables change for the query

Initial load provides no such warning, it's only when variables change for the query that a warning is displayed. Doesn't seem to matter whether `returnPartialData` is true or not.

I've spent a fair bit of time trying to track down this warning, concerned that it might indicate some error on my part with as-yet unseen consequences, but I'm starting to think this is a spurious warning and/or an issue in Apollo itself.

**Versions**

  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
  Browsers:
    Chrome: 84.0.4147.135
    Firefox: 76.0
    Safari: 12.1.2
  npmPackages:
    @apollo/client: ^3.1.3 => 3.1.3 <-- Also tried in 3.1.2

**Comment by bennypowers** [comment]
I've been getting the same.

What's worse, it's for queries that actually query for that data!

<img width="1059" alt="Screen Shot 2020-09-23 at 16 18 32" src="https://user-images.githubusercontent.com/1466420/94017739-72cbf380-fdb8-11ea-9b17-e4bc39d6a4d6.png">

setting these on the component did *not* help
```ts
  fetchPolicy: FetchPolicy = 'network-only';

  nextFetchPolicy: FetchPolicy = 'cache-first';
```

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
