### ISSUE TITLE
Getting "SCRIPT1014: Invalid character" error in IE11

### ISSUE THREAD

**Issue by dhiaEvodeck** [apollographql/apollo-client#6897]
We are using @apollo/client with next js. It works well for all browsers except IE11.

We get `SCRIPT1014: Invalid character` error in IE11, caused by the backquote ( `) character.

I tried transpiling ES6 to ES5 with Babel but no chance.

![Screenshot 2020-08-25 at 18 33 34](https://user-images.githubusercontent.com/68855749/91202040-87f22b80-e701-11ea-918d-fa7adf5d44b5.png)

**Comment by benjamn** [comment]
That's an uncompiled template string, but we compile our template strings with TypeScript. I don't see any of that text anywhere in `@apollo/client` itself or in its `node_modules`. Check any polyfill libraries you might be using?

**Comment by dhiaEvodeck** [comment]
I was checking and it was because of `proxy-polyfill`. Thank you for your help
