### ISSUE TITLE
Missing cache result fields warning for cache-only query

### ISSUE THREAD

**Issue by ertrzyiks** [apollographql/apollo-client#6928]
**Intended outcome:**

I can use cache-only policy to load data from cache. If there is no data in cache, I want no data.

**Actual outcome:**
`Missing cache result fields` warning triggered when there is no data in cache. I'm fine with this scenario, can't find any way to silent the warning though.

**How to reproduce the issue:**
```
const { data } = useQuery(query, { fetchPolicy: 'cache-only' })
```

```
**Versions**
  System:
    OS: macOS 10.15.4
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - ~/workspace/project/node_modules/.bin/yarn
    npm: 5.1.0 - ~/workspace/project/node_modules/.bin/npm
  Browsers:
    Chrome: 84.0.4147.135
    Firefox: 78.0.1
    Safari: 13.1
  npmPackages:
    @apollo/client: ^3.1.3 => 3.1.3 
    apollo: ^2.30.2 => 2.30.2 
    apollo-upload-client: ^14.1.1 => 14.1.1 
```

**Comment by ertrzyiks** [comment]
may be related to #6211

**Comment by hwillson** [comment]
> I'm fine with this scenario, can't find any way to silent the warning though.

You can adjust all AC warnings using `setLogVerbosity`. Details here: https://github.com/apollographql/apollo-client/pull/7226. Thanks!
