### ISSUE TITLE
useLazyQuery not returing function 

### ISSUE THREAD

**Issue by RitikDua** [apollographql/apollo-client#6940]
I have implemented a useLazyQuery hook but it is not returning function . 
```
const USER=gql`query user{
   user{
      name
      email
  }
}`
```
```
const profile=()=>{
   const [getUser,{data,loading}]=useLazyQuery(USER);

	useEffect(() => {
		async function fetchData(){
			if(getUser) 
                             getUser({})
                 else
                           console.log(getUser)
		}
		fetchData();
	}, [getUser,data,loading]);
```
Here,I only get **udefined** on console.

P.S. I am little new to Apollo .

**Comment by Zikoel** [comment]
Hi, I suppose that the function returned is only a trigger, you can use that function to fire the query, after that the result come appear on `data` variable on next react rendering (automatically) if you use the hook paradigm this is very useful!

What is not useful of this behaviour is the fact that in certain circumstances you want to wait the response directly on waiting the query function! This is a missing feature in my opinion
