### ISSUE TITLE
Having multiple watchQuery observables on the page causes an inifite number of rapid requests

### ISSUE THREAD

**Issue by wassim-k** [apollographql/apollo-client#6943]
v3.1.x of apollo client introduced an odd issue in our software where having multiple `watchQuery` observables on the page causes it to make 10s of http requests per second an infinite number of times.

**Intended outcome:**
To make a single http request per `watchQuery` observable.

**Actual outcome:**
10s of requests are made to the server per second infinitely.

**How to reproduce the issue:**
I've created a minimal reporoduction of the issue, note I've mocked the http request but the original issue was happenning with a real backend.
https://stackblitz.com/edit/apollo-watch-query-infinite

**Versions**
  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 81.0.4044.92
    Edge: Spartan (44.18362.449.0)

**Comment by dvakatsiienko** [comment]
Yes, I can confirm this issue but in a little bit different condition: using pollInterval, in case if multiple queries (pollInterval applied) are used on the same page. 
I have 8 queries (pollInterval applied) on the same page which gives me an infinite querying loop very quickly.

**Comment by JesseZomer** [comment]
https://github.com/apollographql/apollo-client/issues/6760#issuecomment-668188727 Here is some more info on something they changed in 3.1. If you set `nextFetchPolicy: 'cache-first'` it will stop.

I really think they should have communicated this a bit better, seeing the impact this can have on some servers

**Comment by wassim-k** [comment]
@JesseZomer Thanks for shedding some more light on the problem.
Setting `nextFetchPolicy` seems to work for the initial request, but I've updated my reporoduction to contain a `pollInterval` which is used in our production app and that seems to trigger the infinite loop again.

**Comment by hubertlepicki** [comment]
Same issue. According to our tests, this has been introduced to our code base when we did upgrade from 3.1.3 to 3.1.4. The issue seems still present on 3.1.5, hasn't tested 3.2.0 yet.

**Comment by wassim-k** [comment]
I've created a new reporduction with **3.2.0** https://stackblitz.com/edit/apollo-watch-query-infinite-3-2
It works `nextFetchPolicy` set to `cache-first`, even with `pollInterval` present.

I'm leaving this issue open because, imho, a configuration where the front-end fires an infinite number of requests rendering the backend irresponsive should not be possible under any circumstances, because the results are too severe in a production environment and is not always detectable in development.
