### ISSUE TITLE
`tryFetch` removed, but still documented

### ISSUE THREAD

**Issue by bennypowers** [apollographql/apollo-client#6947]
Hey!

the `tryFetch` parameter to https://github.com/apollographql/apollo-client/blob/d470c964db46728d8a5dfc63990859c550fa1656/src/core/ObservableQuery.ts#L433-L439 was removed, but it's still documented.

I realize this is a private method that shouldn't be used, but I noticed it was out of place.

See also eabf3e916bbd967e0f129f296c8681bef5ffed4f

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
