### ISSUE TITLE
Running AC3 in Cypress 4 environment might lead to invalid results because of custom Promise 

### ISSUE THREAD

**Issue by dotansimha** [apollographql/apollo-client#6951]
Hi ! 

While migrating a large-scale project to AC3 (testing `beta-6`), we noticed a regression with some direct usages of `client.query()`.
The outcome of `client.query()` was `Promise<undefined>`:

```ts
const client = new ApolloClient();
const result = await client.query({ ... });
// result is undefined
```

This was happening only in our e2e environment, that running Cypress 4.4.1. We did some investigation, and noticed that the following piece of code:  https://github.com/apollographql/apollo-client/blob/main/src/core/QueryManager.ts#L489-L492 is using `.finally()` and it causes the resolve values of the `Promise` to be `undefined`. 

I know this is a bug with Cypress / Bluebird Promise, opened this so it will be easier to track here as well if someone encounters this - the `finally` statement usages breaks Cypress 4 e2e tests. Not sure how Cypress v5 handles that, but I assume it's similar. 

@benjamn maybe it's possible to avoid using `finally` and use `then(r).catch(e)` instead?

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
