### ISSUE TITLE
Cannot provide array of objects in GraphQL mutation through Apollo

### ISSUE THREAD

**Issue by jack0wsky** [apollographql/apollo-client#6955]
**Intended outcome:**

I'm building app in Gatsby using Apollo to fetch and send data to CMS via GraphQL. All variables declared as String work as expected but when I try to send an array of 5 objects, in console it gets empty array. What's interesting, when I try to do the same operation through Insomnia, GraphiQL app or even Apollo DevTools, all variables work.

Here's my query

```
const ADD_REVIEW = gql`
  mutation AddReview(
    $name: String!
    $caption: String!
    $shopifyId: String!
    $rate: [Json!]
  ) {
    createReview(
      data: {
        author: $name
        caption: $caption
        shopifyId: $shopifyId
        rate: $rate
      }
    ) {
      id
      author
      caption
      rate
      shopifyId
    }
  }
`
```

here's array of objects I want to send through mutation

```
const [stars, setStars] = useState([
    {
      key: 1,
      checked: true,
    },
    {
      key: 2,
      checked: true,
    },
    {
      key: 3,
      checked: true,
    },
    {
      key: 4,
      checked: false,
    },
    {
      key: 5,
      checked: false,
    },
  ])
```
and here's submit function
```
const [addReview, { data }] = useMutation(ADD_REVIEW)

.
.
.

const handleSubmit = (e) => {
    e.preventDefault()
    let shopifyId = 'new id'
    addReview({
      variables: { name, caption, shopifyId, stars },
    }).then((res) => console.log(res, data))
  }
```

**Actual outcome:**
Result in console is empty array. Other properties like author or caption work fine.

**How to reproduce the issue:**

**Versions**

 System:
    OS: macOS 10.15.6
  Binaries:
    Node: 12.14.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.83
    Firefox: 79.0
    Safari: 13.1.2
  npmPackages:
    @apollo/client: ^3.1.4 => 3.1.4 
    @apollo/react-hooks: ^4.0.0 => 4.0.0 
    apollo-boost: ^0.4.9 => 0.4.9 
    apollo-link: ^1.2.14 => 1.2.14 
    gatsby-plugin-apollo: ^3.0.1 => 3.0.1 
    react-apollo: ^3.1.5 => 3.1.5

**Comment by knedev42** [comment]
You have a mismatch between your variable definitions and what you actually pass to variables.
Your variable definitions use `$rate`, but you're passing in `stars` when you're executing the mutation.

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
