### ISSUE TITLE
Executing query fires another query inadvertently when latter uses pollInterval

### ISSUE THREAD

**Issue by codelizrd** [apollographql/apollo-client#6957]
I have two components: a ObjectList and an ObjectView shown next to each other. Clicking on an item in ObjectList will show the corresponding item in the ObjectView.

```
const listQuery = gql`
query ObjectListQuery {
   getList {
      id
      title
   }
}
`;

const ObjectList = (onClick: (id: string) => void) => {
   const { loading, error, data } = useQuery(listQuery, pollInterval: 30_000);
   
   if (loading) return (<p>Loading..</p>);
   if (error) return (<p>Error!</p>);
   return (
      <ul>
         {data.getList.map(item => <li key={item.id} onClick={() => onClick(item.id}>{item.title}</li>)}
      </ul>
   )
}


const viewQuery = gql`
query ObjectViewQuery($id: String!) {
   getObject(id: $id) {
      id
      title
      details
   }
}
`;

const ObjectView.tsx = (props: {id: string}) => {
   const { loading, error, data } = useQuery(viewQuery, {variables: {id}});

   if (loading) return (<p>Loading..</p>);
   if (error) return (<p>Error!</p>);
   return (<p>{data.getObject.details}</p>);
}
```

Everything runs fine: upon load the list is shown, clicking on an item will load and print its details. 

But: after 30 seconds (the pollInterval) the list query is re-executed and after that each viewQuery execution also yields an additional unwanted listQuery, next to the queries fired due to the pollInterval. Clicking 5 items sequentially fires an equal amount of additional listQueries.

I already tried changing the fetchPolicy and nextFetchPolicies on the listQuery (cache-first / cache-only) but I cannot get rid of the unwanted listQueries.

Is this intended behavior? I want the list to be only refetched every 30 seconds.

```
  System:
    OS: macOS 10.15.6
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.83
    Firefox: 80.0
    Safari: 13.1.2
  npmPackages:
    @apollo/client: 3.1.4 => 3.1.4 
    @apollo/react-testing: 4.0.0 => 4.0.0 
    apollo-cache-persist: ^0.1.1 => 0.1.1 
    apollo-upload-client: 14.1.1 => 14.1.1 
    apollo-utilities: 1.3.4 => 1.3.4 
    react-apollo: 3.1.5 => 3.1.5 
```

**Comment by hwillson** [comment]
We'll need a reproduction (using `@apollo/client@latest`) to be able to troubleshoot this further. Thanks!

**Comment by eltonio450** [comment]
Ahhh nice that you commented, I couldn't find this issue and it popped in my email

@codelizrd I think it is related to : https://github.com/apollographql/apollo-client/issues/7938#issuecomment-823555426

I think there might be is underlying bug with
- fetch-policy: cache-and-network
- pollIntervall set to smthg
- overlapping queries

there is a workaround using nextFetchPolicy: cache-first

hope it helps
