### ISSUE TITLE
keyArgs not properly saving the correct keys

### ISSUE THREAD

**Issue by tafelito** [apollographql/apollo-client#6961]
**Intended outcome:**

I have a page where I call the same query twice, but with different arguments for one of the fields. 

This is the query 

```gql
query activityDocsCompaniesWithDocTypes(
    $where: activities_docs_x_companies_bool_exp
    $activityDocsWhere: activities_docs_x_companies_x_document_types_bool_exp
  ) {
    activities_docs_x_companies(where: $where) {
      nodes {
        ...ActivityDocsCompany
        activityDocsCompanyDocTypes(where: $activityDocsWhere) {
          ...ActivityDocsCompanyDocType
        }
      }
    }
  }
```

The  `activityDocsWhere` variable could be undefined or have some arguments. The problem I'm having is that the field activityDocsCompanyDocTypes is only being cached with and empty obj.

I tried setting ['where'] as the keyArgs and also a custom fn that checks whether the args are empty or not  

This is the typePolicy for the activities_docs_x_companies field

```js
activities_docs_x_companies: {
      fields: {
        activityDocsCompanyDocTypes: {
          keyArgs: (args) => {
            console.log('args', args);
            const noArgs = isEmpty(args?.where);
            console.log('noArgs', noArgs);
            return noArgs ? '' : ['where'];
          },
          // keyArgs: ['where'], // this doesn't work either
        },
      },
    },
```

**Actual outcome:**

this is the actual log and how the field is stored in the cache

![image](https://user-images.githubusercontent.com/5973652/92035242-6960e580-ed3c-11ea-8b98-247918d2fc1f.png)

as you can see, firs the query runs with an empty where arg and then with some values, but the in the cache it's not using the args as keys 

if then I navigate to a different page where I use the same query but with different arguments, this is how the cache looks after the query is run

![image](https://user-images.githubusercontent.com/5973652/92035740-281d0580-ed3d-11ea-85f6-1cd2e9902efd.png)

**How to reproduce the issue:**

I'm not sure how easy would be create a repro for this but I'll try if necessary

**Versions**

```
System:
    OS: macOS 10.15.6
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.83
    Safari: 13.1.2
  npmPackages:
    @apollo/client: 3.1.2 => 3.1.2 
    @apollo/link-context: ^2.0.0-beta.3 => 2.0.0-beta.3 
    @apollo/link-error: ^2.0.0-beta.3 => 2.0.0-beta.3 
    apollo-upload-client: ^13.0.0 => 13.0.0 
  npmGlobalPackages:
    apollo-codegen: 0.20.2
```

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
