### ISSUE TITLE
useSubscription getting old data back after variable changed and loading has happened

### ISSUE THREAD

**Issue by christophediprima** [apollographql/apollo-client#6970]
Hi

I am having issues understanding what I am doing wrong with `useSubscription`.
When changing a subscription variable, data doesn't change state as I would expect.

Here is my react code:

```javascript
const [myVariable, setMyVariable] = useState('initValue');
const {data, loading} = useSubscription(
   MY_SUBSCRIPTION,
   {
    variables: {
       myVariable
    },
    onSubscriptionData: ({subscriptionData}) => {console.log({subscriptionData})}
   }
console.log({data, loading, myVariable});
```

When changing `myVariable` using `setMyVariable` I have following output:

1. `{data: undefined, loading: true}`
2. `{subscriptionData: newData}`
3. `{data: oldData, loading: false}`
4. `{data: oldData, loading: false}`
5. `{data: newData, loading: false}`

**Versions**
@apollo/client: 3.1.4

**Comment by christophediprima** [comment]
Am I the only one having this behaviour?

**Comment by christophediprima** [comment]
https://github.com/apollographql/apollo-client/issues/7198#issuecomment-714532335

**Comment by hwillson** [comment]
If someone can provide a small runnable reproduction that demonstrates this happening with `@apollo/client@latest`, we'll take a closer look. Thanks!

**Comment by wmwart** [comment]
No, it’s not the only one. I already broke my whole head to debug this. This bug only appears in production and does not appear in development.
