### ISSUE TITLE
Resetting the store with cache-and-network leads to empty query data

### ISSUE THREAD

**Issue by milamer** [apollographql/apollo-client#6986]
Having queries with fetch policy set to 'cache-and-network' and then resetting the store via `client.resetStore` will lead to empty query data.

**Intended outcome:**

Resetting the store should refetch all queries even if they have the fetch policy set to 'cache-and-network'.

**Actual outcome:**

After resetting the store queries are fetched, but instead of the actual results, `undefined` will be returned by `useQuery`.

**How to reproduce the issue:**

[Sandbox link](https://codesandbox.io/s/apollo-refetch-xmslf?file=/src/App.tsx)

You just have to click the reset store button to see the bug.  
Commenting in the `nextFetchPolicy: 'network-only',` line will "fix" the issue.

**Versions**

@apollo/client = 3.1.4

**Comment by hwillson** [comment]
Confirmed fixed in `@apollo/client@3.3.19`. Thanks!
