### ISSUE TITLE
Suggested SSR Restore leads to TS error

### ISSUE THREAD

**Issue by stolinski** [apollographql/apollo-client#6996]
**Intended outcome:**

I'm restoring the cache using `const cache = new InMemoryCache().restore(window['__APOLLO_STATE__'])` as documented here: https://www.apollographql.com/docs/react/performance/server-side-rendering/#store-rehydration

**Actual outcome:**

Typescript error saying `Argument of type 'string' is not assignable to parameter of type 'NormalizedCacheObject'.ts(2345)`

**How to reproduce the issue:**

**Versions**

```
  System:
    OS: macOS 11.0
  Binaries:
    Node: 14.6.0 - /usr/local/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.83
    Firefox: 68.0.2
    Safari: 14.0
  npmPackages:
    @apollo/client: ^3.1.4 => 3.1.4
    @apollo/link-schema: ^2.0.0-beta.3 => 2.0.0-beta.3
    apollo-server-express: ^2.17.0 => 2.17.0
  npmGlobalPackages:
    apollo: 2.21.1
```

**Comment by stolinski** [comment]
If you ignore the ts error, the code is working fine. What's the best way out of a type error in a suggested snippet like this?

**Comment by hwillson** [comment]
@stolinski `InMemoryCache`'s `restore` doesn't accept a string, so doing the following should work:

```js
const cache = new InMemoryCache().restore(JSON.parse(window['__APOLLO_STATE__']));
```

We'll either get this adjusted in the docs or tweak the `restore` code a bit. Thanks!

**Comment by hwillson** [comment]
@stolinski we're going to update the docs accordingly.

**Comment by stolinski** [comment]
Thank you!

**Comment by stolinski** [comment]
Just a heads up JSON.parse() around window.__APOLLO_STATE__ throws because Apollo State is already an object, so might have to revert those docs. I think window.__APOLLO_STATE__ was getting the wrong type somehow.
