### ISSUE TITLE
Cache with {addTypename:false} causes query to return empty data when fragments are used

### ISSUE THREAD

**Issue by l-abels** [apollographql/apollo-client#7006]
I have a simple query described in a `.gql` file:
```
fragment thingBody on Thing {
    id
    name
    description
}

query things {
    things {
        ...thingBody
    }
}
```

I have a client with this configuration:
```
const client = new ApolloClient ({
  new InMemoryCache({ addTypename: false}),
  new HttpLink({ uri: myURI}),
});
```

**Intended outcome:**

This query should return this data, which is identical to what's returned when using the `no-cache` policy:
```
{
    things: [
      {
        id: '001',
        name: 'Thing1',
        description: 'This is a standard thing',
      },
      {
        id: '002',
        name: 'Thing2',
        description: 'This is a standard thing',
      },
      {
        id: '003',
        name: 'Thing3',
        description: 'This is a standard thing',
      },
    ]
}
```

**Actual outcome:**

{ things: [ {}, {}, {} ] }

**How to reproduce the issue:**

Configure a cache and client as above and use any query with a fragment.

**Versions**

  Binaries:
    Node: 14.6.0 - /usr/local/bin/node
    npm: 6.14.7 - /usr/local/bin/npm
  npmPackages:
    @apollo/client: 3.1.4 => 3.1.4

**Comment by benjamn** [comment]
Yep, fragment matching requires the `__typename` field, even if it's always matching the `__typename` exactly.

Generally speaking, a lot depends on `__typename` within the cache (fragment matching being just one example), so we do not recommend using `addTypename: false`, unless you are adding the `__typename` fields some other way (manually, or in a build step), or you're sure you're not using fragments.

**Comment by l-abels** [comment]
If I use the `no-cache` option or the old `apollo-fetch` module, the query "just works".  I was a little surprised that adding a cache could cause incorrect query results, I assumed it could be implemented in such a way that it did no harm.  Thanks for the info, adapting to having `__typename` injected into everything won't be a major issue for me.

**Comment by Ellosaur** [comment]
> Yep, fragment matching requires the `__typename` field, even if it's always matching the `__typename` exactly.
> 
> Generally speaking, a lot depends on `__typename` within the cache (fragment matching being just one example), so we do not recommend using `addTypename: false`, unless you are adding the `__typename` fields some other way (manually, or in a build step), or you're sure you're not using fragments.

Isn't this advice at odds with [Apollo's recomendation](https://www.apollographql.com/blog/graphql/security/why-you-should-disable-graphql-introspection-in-production/) to shut off introspection in production envrionments? `addTypename: true` results in `"message": "Introspection is not allowed.",` on a server where this is the case

**Comment by Ellosaur** [comment]
@benjamn Thanks perhaps its just an issue between the chair and the keyboard then :) Can you help at all?
I'm using an ApolloClient with an InMemoryCache with `addTypename: false` as the server it talks to has introspection disabled. Queries we send work fine until fragments are used:
```
query ArticleContentQuery($id: String!) {
    ${article.type}(where: { id: $id }) {
        audience {
            audienceType
        }
        author {
            ... on Person {
                name
            }
        }
    }
}
```
Even then, those queries still seem to return the required data from the server:
```
  "data": {
    "medicalArticle": [
      {
        "audience": {
          "audienceType": "patient"
        },
        "author": [
          {
            "name": "Julius Hibbert"
          }
        ]
...
```
But the client returns the data lacking just the fragment-driven elements:
```
medicalArticle: Array(1)
  0:
    audience: {audienceType: 'patient'}
    author: Array(1)
      0: {}
      length: 1
      [[Prototype]]: Array(0)
```
Unlike when running the same query through [graphql-request](https://github.com/prisma-labs/graphql-request):
```
medicalArticle: Array(1)
  0:
    audience: {audienceType: 'patient'}
    author: Array(1)
      0: {name: 'Julius Hibbert'}
      length: 1
      [[Prototype]]: Array(0)
```

**Comment by Ellosaur** [comment]
FYI for anyone finding the same issue disabling the cache is the only solution I've found. See [this answer](https://stackoverflow.com/questions/47879016/how-to-disable-cache-in-apollo-link-or-apollo-client) and dont forget to add back in `{ addTypename: false }` to the "diasbled" InMemoryCache in order to avoid the error `Introspection is not allowed.` from the server.
