### ISSUE TITLE
Possible memory leak with useQuery 

### ISSUE THREAD

**Issue by hlandao** [apollographql/apollo-client#7013]
**Intended outcome:**
Running the same query many times in React-Native shouldn't make the JS heap to grow

**Actual outcome:**
Running the same query many times causing JS heap to grow meaning there is a memory leak.

**How to reproduce the issue:**
Run the same query many times, even with fetchPolicy=network-only

This is the diff of snapshots of the heap (before and after running the same query 5 times). As you dan see objects are being retained and not cleaning up.
![image](https://user-images.githubusercontent.com/1934229/93030433-19620880-f5f1-11ea-8149-5faa25372ce4.png)

This is the tree of objects
![image](https://user-images.githubusercontent.com/1934229/93030488-6cd45680-f5f1-11ea-9ae1-4b30ac722963.png)

I think it has to do something with `maybeBroadcastWatch` from `inMemoryCache.ts`

Does anyone experienced anything like that?
**Versions**
  System:
    OS: macOS 10.15.6
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Safari: 13.1.2
  npmPackages:
    @apollo/client: ^3.1.5 => 3.1.4 
    apollo-cache-persist: git@github.com:apollographql/apollo-cache-persist.git#0.2.0 => 0.1.1

**Comment by NathanSaunders01** [comment]
I'm having a similar issue with useQuery in React Native. The issue in my case seems to be when I add `fetchPolicy: 'network-only'` to it.

The initial load is fine but any updates to data in that query using cache.writeQuery will cause an infinite loop of reloading the component over and over again. If I then move to another screen which queries the same data again, it will cause an infinite loop of querying the same data over and over again.

In my case, I think it could be to do with the way React Navigation works with screens? When I move from the first screen to the next, the initial screen is still mounted with that first query so when I make the second query on the next page, I wonder if they re-trigger each-other over and over? 

I didn't have this issue with apollo-client@2.6.10

**Comment by hlandao** [comment]
@NathanSaunders01 I think in my case it happens with the default `fetchPolicy` as well as with `network-only`. However, with `cache-only` it does not happen.

**Comment by patsplat** [comment]
Have also observed this leak in a production server-side-rendering deployment.

**Comment by phryneas** [comment]
Hi everyone!

We recently released the Apollo Client 3.9 beta, which should resolve quite a lot of memory leaks like this.

Could you please give it a test and report back? For more information, please see the [announcement blog post](https://www.apollographql.com/blog/apollo-3-9-beta-feature-spotlight-the-memory-story).

**Comment by phryneas** [comment]
Apollo Client 3.9 has been released finally, and I believe this issue should have been solved with it.

If you still see this happening with Apollo Client >=3.9, please open a new issue :)
