### ISSUE TITLE
Shortened links in client pointing to preview documentation.

### ISSUE THREAD

**Issue by ngbrown** [apollographql/apollo-client#7016]
**Intended outcome:**

Link to released documentation at:

- https://www.apollographql.com/docs/react/caching/cache-configuration/#generating-unique-identifiers
- https://www.apollographql.com/docs/react/caching/cache-field-behavior/#merging-non-normalized-objects

**Actual outcome:**

Currently links to outdated documentation at:

-  https://deploy-preview-5677--apollo-client-docs.netlify.app/docs/react/v3.0-beta/caching/cache-configuration/#generating-unique-identifiers
- https://deploy-preview-5677--apollo-client-docs.netlify.app/docs/react/v3.0-beta/caching/cache-field-behavior/#merging-non-normalized-objects

**How to reproduce the issue:**

Use link: https://go.apollo.dev/c/generating-unique-identifiers or https://go.apollo.dev/c/merging-non-normalized-objects, which are embedded in the Apollo client for certain errors/warnings.

**Versions**

v3.0

**Comment by benjamn** [comment]
@ngbrown Thanks for catching this! We'll have it fixed soon (just waiting on a PR to be approved in an internal repo).
