### ISSUE TITLE
awaitRefetchQueries is not working

### ISSUE THREAD

**Issue by eranimo** [apollographql/apollo-client#7017]
Continuation of https://github.com/apollographql/react-apollo/issues/3797

**Intended outcome:**
`awaitRefetchQueries` should perform as intended for queries that have cache-policy set to cache-and-network.

**Actual outcome:**
Queries that run after mutations are not awaited within the mutation's promise.

**How to reproduce the issue:**
- Create a query with a cache policy of `cache-and-network`
- Create a mutation with `refetchQueries` including the above query and set `awaitRefetchQueries` to true.
- Run mutation and notice that promise is resolved after mutation, not the queries that run after it. Chance the cache policy to network-only and it performs as intended.

**Versions**
```
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 8.17.0 - ~/.nvm/versions/node/v8.17.0/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v8.17.0/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 78.0.2
    Safari: 13.1.2
  npmPackages:
    apollo-cache-inmemory: ^1.3.0 => 1.3.0
    apollo-client: ^2.4.3 => 2.6.8
    apollo-link: ^1.2.2 => 1.2.2
    apollo-link-http: ^1.5.4 => 1.5.4
    apollo-link-logger: ^1.2.3 => 1.2.3
    apollo-link-rest: ^0.7.3 => 0.7.3
    apollo-link-retry: ^2.2.4 => 2.2.4
    apollo-server-express: ~2.4.0 => 2.4.8
```
and `react-apollo@3.0.0`

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
