### ISSUE TITLE
Querying for relayStylePagination edges with an id returns an empty array of edges

### ISSUE THREAD

**Issue by anark** [apollographql/apollo-client#7026]
**Intended outcome:**
Edges are correctly populated in Apollo cache

**Actual outcome:**
Edges array in apollo cache is always an empty array

**How to reproduce the issue:**
Add an ```id``` field on your edge object and query for it after querying for only metadata on the connection.  For example first query
```
        query TodoQuery {
          todos {
            totalCount
          }
        }
```
And then query
```
        query TodoQuery {
          todos(after: $after, first: $first) {
            pageInfo {
              __typename
              hasNextPage
              endCursor
            }
            totalCount
            edges {
              __typename
              id
              node {
                __typename
                id
                title
              }
            }
          }
        }
```

The todos.edges will always be an empty array when reading from the apollo cache.

I have a test that fails on https://github.com/apollographql/apollo-client/pull/7023/files and was able to fix this by removing the ```canRead(edge)```  check in the read function, however I do not think this is an appropriate fix.

**Versions**

```
npx: installed 1 in 0.939s

  System:
    OS: macOS 10.15.6
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.5 - ~/Development/sky-pilot/node_modules/.bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Safari: 13.1.2
  npmPackages:
    @apollo/client: ^3.2.0 => 3.2.0
    @apollo/react-testing: ^4.0.0-beta.1 => 4.0.0
```

**Comment by benjamn** [comment]
@anark Thanks for this! I think the issue is that when edges are normalized (because they have a `__typename` and `id`), they appear to the `read` function as `Reference` objects, so the `edge.node` needs to be `readField("node", edge)` instead (which works when `edge` is a not a reference, too).

**Comment by anark** [comment]
Thanks @benjamn,
Tried out your change and it works great for me!

Thanks for the quick fix.

**Comment by benjamn** [comment]
@anark just to reiterate https://github.com/apollographql/apollo-client/pull/7023#issuecomment-694336974 in case other folks see this first: we plan to release this fix in `@apollo/client@3.2.1`, but for now it's available for testing in `@apollo/client@3.3.0-beta.1`.

**Comment by anark** [comment]
Great!  Thanks so much.

**Comment by CodySwannGT** [comment]
Experiencing the same issue in 3.6.9 except we don't have an "id" on our edges
