### ISSUE TITLE
reFetchObservableQueries ignores @client directive for local-only fields

### ISSUE THREAD

**Issue by dalmo3** [apollographql/apollo-client#7027]
Apparently `reFetchObservableQueries` runs all queries against the server, ignoring `@client` directives. 

That means all queries with local-only fields fail with:
```
{message: "Cannot query field "LocalUser" on type "Query".", status: 400,…}
```
Because those fields don't exist on the server.

**Intended outcome:**

`reFetchObservableQueries` should rerun the queries as they are intended.

**How to reproduce the issue:**
1. Open [sandbox](https://codesandbox.io/s/apollo-refetchobservablequeries-issue-6weox?file=/src/index.js)
2. Inspect network requests. At startup only one query will be requested. (Correct behaviour). 
3. Click the button and inspect requests again. There's an additional request (which fails). 

**Versions**

This below is my system, but the sandbox is running @3.2.0
```
  System:
    OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
  Binaries:
    Node: 14.9.0 - /usr/bin/node
    npm: 6.14.8 - /usr/bin/npm
  npmPackages:
    @apollo/client: ^3.1.3 => 3.1.3 
    apollo-cache-persist: ^0.1.1 => 0.1.1 
```

**Comment by hwillson** [comment]
This isn't an issue with `reFetchObservableQueries` - your `GetLocalUser` query isn't fully local. You're using `@client` directives with the `name` and `age` fields so those are local, but you're not using `@client` with the `LocalUser` field. This means that field is still sent to the server. If you change:

```js
const GetLocalUser = gql`
  query localUser {
    LocalUser {
      name @client
      age @client
    }
  }
`;
```

to 

```js
const GetLocalUser = gql`
  query localUser {
    LocalUser @client {
      name
      age
    }
  }
`;
```

everything will work properly.
