### ISSUE TITLE
refetch - Apollo Client in Next.js - not re-rendering after refetch

### ISSUE THREAD

**Issue by codelover2k** [apollographql/apollo-client#7029]
I was able to integrate Apollo Client in my Next.js server.
When I go to my users route, Apollo Client fetches the data at server-side.

Now I would like to be able to refetch data at the client side, to not re-download the page again.
now I am using refetch from useQuery, but the problem is that it does not re-renders the page.

The refetch works and if I console.log the data, it contains the new and correct data, but still the component is not re-rendered.

Hope someone can help
thanks in advanced!

**Comment by vipul0092** [comment]
Difficult to find the issue without looking at the code.
Can you share your code where you are seeing the issue?

**Comment by hwillson** [comment]
We'll need a reproduction (using `@apollo/client@latest`) to be able to troubleshoot this further. Thanks!
