### ISSUE TITLE
Make MockedProvider return better errors

### ISSUE THREAD

**Issue by danfernand** [apollographql/apollo-client#7030]
After upgrading to Apollo client 3, mocked provider seems to fail with a non-descriptive error. 

https://codesandbox.io/s/goofy-lalande-ig5en

Here is an example where a nullable value passed as undefined or omitted the whole mocked query fails without mention of the issue with the data.

I looked at the types and do not see a way to not fail gracefully.

**Comment by pleunv** [comment]
I honestly tried to understand why it failed but I couldn't, which is also the core of the issue. Based on your description I'm guessing it might be related to #6771 . I do hope this gets picked up, it is extremely annoying.

**Comment by gat-bryszard** [comment]
We've got a similar problem and #6771 did not fix it (I used the 3.3.0-beta.10 version). Test was working with Apollo 2 and stopped working in Apollo 3, with this error.

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
