### ISSUE TITLE
apollo client:extract isn't compatible with persisted queries link

### ISSUE THREAD

**Issue by angry-dan** [apollographql/apollo-client#7032]
**Intended outcome:**

Apollo's persisted queries link generates hashes for queries differently to the extract cli tool. These hashes should ideally be the same so that a query being executed on a client could be matched to a query in the generated manifest file stored on the server. 

I'm using PHP for my GraphQL server. I'd like to give my PHP server access to the generated manifest file created with `apollo client:extract` so that I'm only sending query ID's over the wire. I'm running the Apollo client in a Node environment if that's relevant. 

When you run `apollo client:extract`, a manifest file is generated which includes a copy of each query in the project along with a signature which looks like sha256 to me. I've checked the CLI code and confirmed that the hash generated directly from the string in the `document` key of the JSON file. That string is created by passing the query object through a chain of processors: `dropUnusedDefinitions`, `hideStringAndNumericLiterals`, `sortAST` and `printWithReducedWhitespace`.

On the client side, I took a look at the default `getQueryHash` from the persisted-queries link and it's using the `print` function from `graphql/language/printer`

**Actual outcome:**

The extracted manifest ends up looking like this
```
{
  "version": 2,
  "operations": [
    {
      "signature": "ba4cc55a3fef8c0f163dce6d45ec3a16a009b1f22ef0662d30942977101f7784",
      "document": "…",
      "metadata": {
        "engineSignature": ""
      }
    },
…
```

Wheras the `generateHash` function of `createPersistedQueryLink` gets given a completely different signature for the same query.

**How to reproduce the issue:**

Run apollo client:extract mainfest.json

Add the persisted-queries link to your client with a custom generateHash function (using sha256 exhibts the same problem), observe that the document string passed to this function doesn't match any of the document strings in the manifest file because of the various processing that's been done on the manifest. Therefore note that there's no way to generate a matching hash.

**Versions**

```
  System:
    OS: macOS 10.15.6
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/Sites/southbank-centre/node_modules/.bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Safari: 13.1.2
  npmPackages:
    @apollo/client: ^3.1.5 => 3.2.0
    apollo: ^2.30.3 => 2.30.3
```

**Comment by hwillson** [comment]
`@apollo/link/persisted-queries` was not designed in conjunction with the `client:extract` capabilities of the `apollo` CLI, so the pre-hashed CLI content is slightly different. The CLI adjusts the AST before hashing it to:

- Remove extra whitespace
- Sort the AST in a deterministic manner
- Optionally hide string and numeric literals
- Remove unused definitions

`@apollo/link/persisted-queries` does not do this by default (intentionally), but it does allow you to override how the hash is generated. You can provide your own `generateHash` function that adjusts the AST by performing the same CLI `client:extract` modifications listed above, before hashing it.

Since this isn't a bug, I'll close this off. Thanks!

**Comment by Cerberus** [comment]
For anyone who looking for a simple solution. I recommend this : )

```ts
import { defaultOperationRegistrySignature, operationHash } from 'apollo-graphql/lib/operationId'

const persistedLink = createPersistedQueryLink({
	generateHash: (document) => {
		const operationName = document.definitions.find(
			(definition) => definition.kind === 'OperationDefinition',
			// @ts-ignore
		)!.name.value
		const printed = defaultOperationRegistrySignature(document, operationName)
		return operationHash(printed)
	},
})
```

Ref: https://gist.github.com/Cerberus/a06ab5389f032508b96955fd20de5ef3
