### ISSUE TITLE
404 (Not Found) on client side when use HttpLink

### ISSUE THREAD

**Issue by roshan-p** [apollographql/apollo-client#7033]
My react app always send post request to http://localhost:3000 and it's throw error like this :
![01](https://user-images.githubusercontent.com/26238949/93464866-1da16500-f914-11ea-8cd3-e18f607cea14.png)

It is happen when I try to pass my uri to HttpLink but it's working fine when I directly pass my uri to ApolloClient
How can I solve this problem.

Here is my code.

**Client side**
`
import React from 'react'
import { ApolloClient, InMemoryCache,ApolloProvider as Provider,split,HttpLink } from '@apollo/client';
import { WebSocketLink } from '@apollo/client/link/ws';
import { getMainDefinition } from '@apollo/client/utilities';

const httpLink = new HttpLink({
  uri: "http://localhost:4000/graphql",
  credentials: "include"
});
const wsLink = new WebSocketLink({
  uri: `ws://localhost:4000/graphql`,
  options: {
    reconnect: true
  }
});

const splitLink = split(
  ({ query }) => {
    const definition = getMainDefinition(query)
    return (
      definition.kind === 'OperationDefinition' &&
      definition.operation === 'subscription'
    )
  },
  wsLink,
  httpLink
)
const client = new ApolloClient({
  uri: splitLink,
  cache: new InMemoryCache(),
  onError: ({ graphQLErrors, networkError, operation, forward }) => {
    if (graphQLErrors)
    graphQLErrors.map(({ message, locations, path }) =>
      console.log(
        `[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`,
      ),
    );

  if (networkError) console.log(`[Network error]: ${networkError}`);
  }

});

export default function ApolloProvider(props){
    return <Provider client={client }{...props}/>
}
`

**Server Side**
`
import { ApolloServer, gql, PubSub } from 'apollo-server-express';
import { typeDefs } from './graphql/typedefs';
import { resolvers } from './graphql/resolvers';
import express from 'express';
import http from 'http';
import mongoose from 'mongoose';
import cors from 'cors';

const SERVER_PORT = 4000;
const DB_URI = "xxxxxxxxxxxxxxx";
const app = express();
const pubsub = new PubSub();

app.use(cors())

const apolloServer = new ApolloServer({
  typeDefs: gql`
    ${typeDefs}
  `,
  resolvers,
  context: ({ req }) => ({ req, pubsub })
});

const db = async () => {
  try {
    const success = await mongoose.connect(DB_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
      useCreateIndex: true,
    });
    console.log('DB Connected');
  } catch (error) {
    console.log('DB Connection Error', error);
  }
};
db();

apolloServer.applyMiddleware({ app });

const httpserver = http.createServer(app);

apolloServer.installSubscriptionHandlers(httpserver);

app.get('/', function (req, res) {
  res.json({
    data: 'BLANK PAGE !'
  });
});

app.get('/rest', function (req, res) {
  res.json({
    data: 'Hit rest end point!'
  });
});

httpserver.listen({ port: SERVER_PORT }, () => {
  console.log(`🚀 Server ready at http://localhost:${SERVER_PORT} let's start!`)
  console.log(`🚀 Apollo is ready at http://localhost:${SERVER_PORT}${apolloServer.graphqlPath} let's start!`)
  console.log(`🚀 Subscription is ready at http://localhost:${SERVER_PORT}${apolloServer.subscriptionsPath} let's start!`)
})

`

**Comment by overhead525** [comment]
I checked the docs on this, and the devs suggest using ```createHttpLink()``` instead of ```new HttpLink()```

![image](https://user-images.githubusercontent.com/60552944/93510913-f2a51a00-f8ef-11ea-96f3-51b195db45c2.png)

The parameters will be the same, so just do two things:
1. change import statement to:
```import { ..., createHttpLink } from @apollo/client```

2. change httpLink creation to:
```
const httpLink = createHttpLink({
    uri: '/graphql'  // I don't think you need to include localhost:4000,
    credentials: 'include'
})
```

Hope this helps.

**Comment by roshan-p** [comment]
I solve it buy change
from
import { ApolloClient } from '@apollo/client';
to
import { ApolloClient } from 'apollo-client';

**Comment by taven-liu** [comment]
save issue
