### ISSUE TITLE
 Unable to use more than one subscribeToMore in a page

### ISSUE THREAD

**Issue by mhuconcern** [apollographql/apollo-client#7037]
**Intended outcome:**

subscribeToMore hydrates appropriate queries.

**Actual outcome:**

I have two subscribeToMore with the same subscribe query, but only the one hits the updateQuery portion, if I comment out one of them the other one works. If this is not supposed to work by design, the build should probably error out

**How to reproduce the issue:**

**Versions**

  System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 12.9.1 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 87.0.4263.3
    Firefox: 80.0
    Safari: 13.1.2
  npmPackages:
    @apollo/client: 3.0.0-beta.45 => 3.0.0-beta.45
    @apollo/link-error: ^2.0.0-beta.3 => 2.0.0-beta.3
    @apollo/link-schema: ^2.0.0-beta.3 => 2.0.0-beta.3
    @apollo/link-ws: ^2.0.0-beta.3 => 2.0.0-beta.3
    @apollo/react-common: ^4.0.0-beta.1 => 4.0.0-beta.1
    @apollo/react-components: 4.0.0-beta.1 => 4.0.0-beta.1

**Comment by hwillson** [comment]
Can you share code that shows how the 2 `subscribeToMore`'s are defined?

**Comment by mhuconcern** [comment]
This is the subscription: 
```
subscription SubscribeToEvents() {
     events {
         id
         name
         details
         status
     }
}
```
This is the query for React Component 1 : 
```
query GetEvents() {
     events {
         id
         name
         status
     }
}
```
This is the first react component that gets the subscription and the one that is relatively rendered first: 
```
const ReactComponent1 = ({}) => {
  const { data, error, loading, subscribeToMore } = useGetEvents();
  React.useEffect(() => {
    subscribeToMore({
     document: SubscribeToEventsDocument
     updateQuery: (prev, {subscriptionData}) => {
         if (!subscriptionData.data) return prev;
         const newEvent = subscriptionData.data;
         const oldEvent = prev.events.findIndex((e) => e.id === newEvent.id);
         const formattedResponse = {
          id: newEvent.id,
          name: newEvent.name,
          status: newEvent.status,
         };
         const newEvents = [...prev.events]
         const newEvents[oldEvent] = formattedResponse;
          return {
             events: newEvents,
             __typename: prev.typename
          }
      }
  })
}
```
This is the query for React Component 2 : 
```
query GetEventsDetails() {
     events {
         id
         name
         details
     }
}
```
This is the second react component that gets the subscription and the one that is rendered second: 
```
const ReactComponent1 = ({}) => {
  const { data, error, loading, subscribeToMore } = useGetEventsDetails();
  React.useEffect(() => {
    subscribeToMore({
     document: SubscribeToEventsDocument
     updateQuery: (prev, {subscriptionData}) => {
         if (!subscriptionData.data) return prev;
         const newEvent = subscriptionData.data;
         const oldEvent = prev.events.findIndex((e) => e.id === newEvent.id);
         const newEvents = [...prev.events]
         const formattedResponse = {
          id: newEvent.id,
          name: newEvent.name,
          details: newEvent.details,
         };
         const newEvents[oldEvent] = formattedResponse;
          return {
             events: newEvents,
             __typename: prev.typename
          }
      }
  })
}
```

**Comment by hwillson** [comment]
We'll need a reproduction (using `@apollo/client@latest`) to be able to troubleshoot this further. Thanks!
