### ISSUE TITLE
useQuery results gets out of sync after a network error

### ISSUE THREAD

**Issue by magicmark** [apollographql/apollo-client#7045]
I'm having trouble nailing down exactly what's going or how to describe it, but here goes:

Whenever there's a network error, the `data` attribute returned from `useQuery` "remembers" the previous result. And then things get a little weird, and `useQuery` *appears* to return the results from the previous network request?

This sounds a little crazy, and maybe this isn't accurately describing what's actually happening - repros are worth a 10000 words, so here's something I threw together to demonstrate the issue:

**Runnable Codesandbox link**: https://codesandbox.io/s/silly-jones-tcpez?file=/components/MakeQuery.js

<details>
<summary>Code</summary>

<p>

```js
import { gql, useQuery, useApolloClient } from "@apollo/client";
import { useState, useEffect } from "react";

const GET_GREETING = gql`
  query {
    greeting
  }
`;

export default function MakeQuery() {
  const [networkError, setNetworkError] = useState(false);
  const [manualQueryResult, setManualQueryResult] = useState();
  const apolloClient = useApolloClient();

  const queryOptions = {
    fetchPolicy: "no-cache",
    context: {
      headers: {
        "x-network-error": networkError === true ? "1" : "0"
      }
    }
  };

  const { data, error, loading } = useQuery(GET_GREETING, queryOptions);
  useEffect(() => {
    apolloClient
      .query({
        ...queryOptions,
        query: GET_GREETING
      })
      .then((...results) => {
        setManualQueryResult(results);
      })
      .catch((...results) => {
        setManualQueryResult(results);
      });
  }, [apolloClient, networkError, queryOptions]);

  return (
    <div>
      <label htmlFor="errorToggle">Toggle network error</label>
      <input
        id="errorToggle"
        type="checkbox"
        name="errorToggle"
        checked={networkError}
        onChange={(event) => {
          setNetworkError(event.target.checked);
        }}
      />

      <h2>useQuery results:</h2>
      <pre>{JSON.stringify({ data, error, loading }, null, 2)}</pre>

      <h2>apolloClient.query results:</h2>
      <pre>{JSON.stringify(manualQueryResult, null, 2)}</pre>
    </div>
  );
}
```
</p>
</details>

My repro shows a component using both `useQuery` and the raw `apolloClient.query` method on the client instance. (The `apolloClient.query` result appears to show the truth, and what I'd expect `useQuery` to also show.

1. Here what the page looks like to start with - so far so good, both versions show a successful query response

   <img width="350" alt="Screen Shot 2020-09-19 at 11 37 40 PM" src="https://user-images.githubusercontent.com/1590756/93705339-40c54380-fad1-11ea-8eb8-ce7b724f7fb9.png">

2. Let's click the 'toggle network error' option to trigger a state change and re-render the component, and have the server return a 500:

   <img width="557" alt="Screen Shot 2020-09-19 at 11 39 43 PM" src="https://user-images.githubusercontent.com/1590756/93705358-6a7e6a80-fad1-11ea-9bef-d250b790d243.png">

   The manual query approach appears to show the right thing. `useQuery` shows some....accidentally cached data?
  
3. Now let's untoggle the network error...

   We should go back to the state shown in (1), but....

   <img width="548" alt="Screen Shot 2020-09-19 at 11 42 23 PM" src="https://user-images.githubusercontent.com/1590756/93705398-ccd76b00-fad1-11ea-8564-b06592e46d07.png">

   🤔 🤔 🤔  looks like useQuery is now showing what it should've shown before? We're now in a state where useQuery is one step behind what it should actually be displaying. You can keep clicking the toggle - `useQuery` and `apolloClient.query` are now permanently out of sync.

It's very possible I'm misunderstanding how state is working here, and I'm doing something dumb - fwiw this came up trying to build https://apollo-visualizer.vercel.app/, in case anyone is interested in the use case. More generally though, I could imagine this causing problems when a network comes back online, or for retries or something.

Is this a bug? Or am I being dumb? Thanks!

**Versions**
```
  "dependencies": {
    "@apollo/client": "3.2.0",
    "@graphql-tools/schema": "6.2.3",
    "graphql": "15.3.0",
    "json-stringify-safe": "5.0.1",
    "next": "latest",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  },
```

```
sandbox@sse-sandbox-tcpez:/sandbox$ npx envinfo@latest --preset apollo
npx: installed 1 in 0.682s

  System:
    OS: Linux 5.4 Debian GNU/Linux 10 (buster) 10 (buster)
  Binaries:
    Node: 10.21.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  npmPackages:
    @apollo/client: 3.2.0 => 3.2.0
```

**Comment by magicmark** [comment]
FWIW [I'm working around this for now by recreating the apollo client instance on each re-rerender, to throw away all state](https://github.com/magicmark/apollo-error-handling-visualizer/blob/625947018027d60effb238fd4a992cb3352f6d96/src/components/MakeQuery.js#L61-L71)

Here's a version of the minimal repro to show this: https://codesandbox.io/s/peaceful-lovelace-bfdgj?file=/components/MakeQuery.js - the UI displays what is expected, the two results stay in sync.

**Comment by hwillson** [comment]
@magicmark Can you double check your repro? It's working for me in each case:

Initial:

![Image 2020-09-20 at 6 35 45 AM png](https://user-images.githubusercontent.com/137740/93709321-8b63b180-fb0b-11ea-934c-0e7b3b9c30e1.png)

Toggle 1:

![Image 2020-09-20 at 6 36 14 AM png](https://user-images.githubusercontent.com/137740/93709328-974f7380-fb0b-11ea-9163-fb2b68442a45.png)

Toggle 2:

![Image 2020-09-20 at 6 36 32 AM png](https://user-images.githubusercontent.com/137740/93709335-a2a29f00-fb0b-11ea-87e6-f6f577fdd96b.png)

**Comment by magicmark** [comment]
> @magicmark Can you double check your repro? It's working for me in each case:
> 
> Initial:
> 
> ![Image 2020-09-20 at 6 35 45 AM png](https://user-images.githubusercontent.com/137740/93709321-8b63b180-fb0b-11ea-934c-0e7b3b9c30e1.png)
> 
> Toggle 1:
> 
> ![Image 2020-09-20 at 6 36 14 AM png](https://user-images.githubusercontent.com/137740/93709328-974f7380-fb0b-11ea-9163-fb2b68442a45.png)
> 
> Toggle 2:
> 
> ![Image 2020-09-20 at 6 36 32 AM png](https://user-images.githubusercontent.com/137740/93709335-a2a29f00-fb0b-11ea-87e6-f6f577fdd96b.png)

@hwillson I think you might be viewing the second link I posted (which demonstrates my workaround) - check out the first link, in my initial message, which demonstrates the issue described - https://codesandbox.io/s/silly-jones-tcpez?file=/components/MakeQuery.js

**Comment by hwillson** [comment]
Oops! Sorry, I looked before coffee - I'll take a closer look.

**Comment by hwillson** [comment]
@magicmark If you drop in a quick `console.log('render');` at the top of your `MakeQuery` component, and watch your browser console, I think you'll see the issue. Your component is trapped in an infinite re-render loop. This is happening because of the `queryOptions` object you're creating on each render, and setting this as a dependency on the `useEffect` hook that triggers the `apolloClient.query` call. Since the `queryOptions` object is new on each render, the query `useEffect` hook is called on each render, which is causing the results to be messed up. If you remove `queryOptions` from your `useEffect` deps array, or look into using something like `useMemo` with your `queryOptions` creation, this problem should go away.

**Comment by magicmark** [comment]
@hwillson Ah, good catch! Yes, this is a problem with my repro :( By removing `queryOptions` from the `useEffect` deps list, we get the two versions back "in sync".

However.....this brings me back to the original eyebrow-raiser that I started creating the repro for:

Here's a version that avoids the infinite rerender loop https://codesandbox.io/s/staging-sun-9ij4e?file=/components/MakeQuery.js

<img width="655" alt="Screen Shot 2020-09-20 at 1 57 09 PM" src="https://user-images.githubusercontent.com/1590756/93722141-7279f100-fb49-11ea-9037-1306dcdc60fe.png">

Why does `useQuery` return "data" from a network error result? Notice the explicit "no-cache" policy.

Is this expected?

**Comment by hwillson** [comment]
Sorry for the delay here @magicmark - the issue you've outlined in https://github.com/apollographql/apollo-client/issues/7045#issuecomment-695835804 is being tracked in https://github.com/apollographql/apollo-client/issues/6905. Thanks!
