### ISSUE TITLE
Using `optimisticResponse` with `cache.modify` in mutation `update` method generates `undefined` `data` property on affected `watchQuery`

### ISSUE THREAD

**Issue by KeithGillette** [apollographql/apollo-client#7049]
**Intended outcome:**
I am attempting to add a newly-created child object to a list property on a parent object using `cache.modify` in the `update` method on the create mutation for the child object. The new object appears in the affected `watchQuery` if an `optimisticResponse` is not provided, but the `data` property is `undefined` if an `optimisticResponse` is provided.

_Triggering Mutation:_
```typescript
…
	public create(mutationVariables: IProcedureCreate_RequestVariables): Observable<FetchResult<IProcedureCreate_ResponseData>> {
		const procedure = new Procedure();
		populate(procedure, mutationVariables);
		procedure._id = mutationVariables.procedureId;

		return this.apollo.mutate<IProcedureCreate_ResponseData>({
			mutation: ProcedureCreate_Mutation,
			variables: mutationVariables,
			update: (apolloClientDataProxy: DataProxy, {data: {ProcedureCreate}}: ApolloQueryResult<IProcedureCreate_ResponseData>): void => {
				const newProcedureReference = this.apollo.client.cache.writeFragment({
					data: ProcedureCreate,
					fragment: gql`fragment ProcedureReference on Procedure {
						_id
					}`
				});
				this.apollo.client.cache.modify({
					id: `${DomainEntityType.ManualSection}:${mutationVariables.manualSectionId}`,
					fields: {
						procedureList(cachedProcedureReferenceList: Reference[]): Reference[] {
							const procedureReferenceList = [...cachedProcedureReferenceList];
							procedureReferenceList.splice(mutationVariables.procedureIndex, 0, newProcedureReference);
							return procedureReferenceList;
						}
					}
				});
			},
			optimisticResponse: {           // No error if omitted
				ProcedureCreate: procedure
			}
		});
	}
…
```

_Affected WatchQuery:_
```typescript
…
this.apollo.watchQuery<IManualSectionRead$ProcedureList_ResponseData, IManualSectionRead$ProcedureList_RequestVariables>({
					query: ManualSectionRead$ProcedureList_Query,
					variables: {manualSectionId: manualSectionId, procedureStatusList: filterQueryParameters.procedureStatusList},
				}).valueChanges.pipe(
			map(({data}: ApolloQueryResult<IManualSectionRead$ProcedureList_ResponseData>) => {
				return data.ManualSectionRead.procedureList;  // `data` is `undefined` if `optimisticResponse` provided
			}),
)
…
```

**Actual outcome:**
`TypeError: Cannot read property 'ManualSectionRead' of undefined` is passed to the subscription error handler

**How to reproduce the issue:**
Use `optimisticUpdate` in conjunction with `cache.modify` as in excerpted code.

**Versions**
```
  System:
    OS: macOS 10.15.6
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 77.0
    Safari: 14.0
  npmPackages:
    @apollo/client: 3.2.0 => 3.2.0 
    apollo-angular: 2.0.4 => 2.0.4 
    apollo-server-express: 2.10.1 => 2.10.1 
```

**Comment by mikevercoelen** [comment]
Same problem here

**Comment by mikevercoelen** [comment]
Anyone? It's pretty crucial we figure 9it out

**Comment by phryneas** [comment]
After a lot of digging in a similar situation: if that optimistic response is in any way incomplete, the query just gets `undefined`, without any further logs informing about that.

See 
https://github.com/apollographql/apollo-client/blob/cbcf951256b22553bdb065dfa0d32c0a4ca804d3/src/core/ObservableQuery.ts#L165-L168

You might get around this by setting `returnPartialData: true` in the query options. To find out which data is missing, the only way to get that seems to be using the browser devtools to add a logpoint for `diff.missing` on the line after `var diff = ...`

**Comment by khayong** [comment]
The error gone on my side when I defined possibleTypes option to the InMemoryCache.

https://www.apollographql.com/docs/react/data/fragments/#defining-possibletypes-manually

**Comment by chriswetterman** [comment]
I've been having this issue for way too long as well. My usage is similar, I have a `useQuery` and `useMutation` hook that work in tandem and as soon as I provide an `optimizedResponse` my query does not run again. My components are controlled and therefore do not update because of this.

I added `returnPartialData` to the query as @phryneas suggested, my UI updates, awesome; but the query still does not run again. My expectation is that the watched query would run again so any other component could take advantage of the update, but that's not happening.

I looked further using `cache.diff` and saw some missing fields which I resolved. Still, do not understand why `useQuery` is not running on update.

**Comment by alessbell** [comment]
Hi @KeithGillette @chriswetterman 👋 Would either of you be able to share a runnable reproduction here if this is an issue you're still facing?

We have a [CodeSandbox](https://codesandbox.io/s/github/apollographql/react-apollo-error-template) and forkable [GitHub repo](https://github.com/apollographql/react-apollo-error-template) with a `subscriptions.tsx` already configured. Thanks!

**Comment by KeithGillette** [comment]
No longer affecting our project with to reproduce with `@apollo/client@3.6.8`.
