### ISSUE TITLE
Nested Fragment on Union type field removes data from response

### ISSUE THREAD

**Issue by ivome** [apollographql/apollo-client#7050]
When using nested fragments on a union type, the properties from the subfragments are removed from the response without warning or error, even though it is returned from the server. 

**Intended outcome:**
Nested fragments on union types should return the data as requested in the GraphQL query. 

**Actual outcome:**
Currently, the data objects in the response are replaced with an object that removes all properties but the `__typename`:

```json
{"__typename": "Subtype"}
```

**How to reproduce the issue:**

Run a query against any GraphQL API that returns a union type with something like the following: 

Partial Schema:
```graphql
union UnionType = Subtype

type Subtype {
  id
  text
}

type Query {
  getUnion: UnionType
}
```

```typescript
import {ApolloClient, gql, HttpLink, InMemoryCache} from '@apollo/client';
import fetch from "cross-fetch";

(async () => {
	const client = new ApolloClient({
		ssrMode: typeof window === 'undefined',
		link: new HttpLink({
			fetch,
			uri: 'https://graphqlapi-with-union-type.com/graphql', // Server URL (must be absolute)
			credentials: 'same-origin', // Additional fetch() options like `credentials` or `headers`
		}),
		cache: new InMemoryCache(),
	});

  const result = await client.query({
    query: gql`
      query Q {
        getUnion {
            __typename
            ...UnionFragment
            # If we add the SubtypeFragment here too, it returns the correct data, but not without that fragment:
            # ...SubtypeFragment
        }
      }

      fragment UnionFragment on UnionType {
          __typename
          ...SubtypeFragment
      }

      fragment SubtypeFragment on Subtype {
        __typename
        id
        text
      }
		`,
  });
	console.log(JSON.stringify(result.data, null, 2));
})();
```

When the fragment of the subtype is added to the root field, the correct data is returned, but this should work without explicitly adding all subfragments IMO. 

**Versions**
  Binaries:
    Node: 10.22.0 - ~/.nvm/versions/node/v10.22.0/bin/node
    npm: 6.14.6 - ~/.nvm/versions/node/v10.22.0/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 80.0.1
    Safari: 13.1.2
  npmPackages:
    @apollo/client: ^3.2.0 => 3.2.0 
    apollo: ^2.27.0 => 2.27.0

**Comment by benjamn** [comment]
@ivome Are you providing [`possibleTypes`](https://www.apollographql.com/docs/react/data/fragments/#using-fragments-with-unions-and-interfaces) to the `InMemoryCache` constructor?

**Comment by ivome** [comment]
@benjamn That does the trick, thank you! 

Would be great to get some kind of error message though when apollo client removes data from the response in such a case.

**Comment by benjamn** [comment]
Interesting idea!

Since the structure of the query is what drives the result-writing process, it's expected that any extra keys in a result object will be discarded. However, if the query has unmatched fragments in it, and some of those fragments contain fields that might be responsible for the extra keys, then I agree we could give a high-value warning about the likelihood that `possibleTypes` is missing or incomplete. 🤔

**Comment by vtereshyn** [comment]
I have a similar problem, but I have `possibleTypes` specified in my codebase. But, I put `addTypename: false` there, and then I got an issue with a response from the backend:
I receive a response, but then I have an array with empty objects in there. When `addTypename: true` the issue disappears. From my understanding I need to add `typename` manually to the cache, right?

**Comment by jaredh159** [comment]
@benjamn fwiw, i just lost a couple hours debugging this exact problem, I had no idea even what to google, just couldn't figure out why apollo client was discarding data coming back from the server. i didn't realize it had to do with nested fragments on a union type. some sort of runtime warning or error would be **super** useful, if this condition could be detected. 🙏
