### ISSUE TITLE
Apollo Error: request entity too large

### ISSUE THREAD

**Issue by yunhanw5** [apollographql/apollo-client#7063]
Hi there! I'm using apollo client in a chrome extension, and when the request is too large, I get the Apollo Error: request entity too large. Is there any way I can increase the request size limit for apollo client? Thanks!

**Comment by hwillson** [comment]
@yunhanw5 This sounds like a limitation on your server side. You'll likely want to look into increasing allowed request sizes through your server config (e.g. if you're using express with Apollo Server, by tweaking your body parser `limit`: http://expressjs.com/en/5x/api.html#express.json).
