### ISSUE TITLE
Localstorage and Authentication Tokens

### ISSUE THREAD

**Issue by n614cd** [apollographql/apollo-client#7064]
I need to include a JWT in the authorization header. Our token is short lived at five minutes and therefore we renew it on a regular basis. Therefore the token value changes often. 
All the examples online utilize localStorage which is I think is still on the OWASP XSS list of vulnerabilities

At a minimum, the docs should use sessionStorage or even better access a token which is stored in a memory variable only. 

Has anyone managed to make Apollo work with a memory variable holding the access token?

**Comment by esseswann** [comment]
https://hasura.io/blog/best-practices-of-using-jwt-with-graphql/

**Comment by samirelanduk** [comment]
I've spent a few days grappling with this, but I think I have now got Apollo working with the access token in a variable. The access token gets stored in the apollo cache, and the refresh token in a httponly cookie.

Essentially when the app loads the app immediately requests an access token with an `{ accessToken }` query and, assuming a refresh token had previously been set, it will get one. Whenever a query or mutation is sent after that, the access token is pulled out of the cache. The initial `{ accessToken }` query is given a pollInterval of 120 seconds, so the cache gets updated with a new token every 2 minutes.

**Comment by dusty** [comment]
You can make a middleware with setContext.  Below is an example, `getValidToken` is something you can define based on whatever you need.

eg:

```
import { setContext } from '@apollo/client/link/context'
import { ApolloClient, ApolloLink, HttpLink, InMemoryCache } from '@apollo/client'

const withToken = setContext(async () => {
  const token = await getValidToken()
  return { headers: { Authorization: `Bearer ${token}` } }
})

const link = ApolloLink.from([withToken, errorHandler, httpLink])

export const client = new ApolloClient({ link, cache }})
```

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
