### ISSUE TITLE
useQuery and useReactiveVar Hooks invalid variant issue when used with Expo Electron Adapter

### ISSUE THREAD

**Issue by darcstar-solutions** [apollographql/apollo-client#7066]
**Intended outcome:**

Trying to use Expo's Electron Adapter to create an Electron App. The dev tools console reports errors about improper use of hooks in a non-functional component.

**Actual outcome:**

**How to reproduce the issue:**

here is a link to the public repo: https://github.com/DarcStar-Solutions-Tech/expo-electron-graphql-template

run yarn expo-electron start

works fine in both web browser and android mobile app generated with expo.

Other Hooks work fine as well. useTheme hook from react-native-paper in ./src/components/App/App.tsx will work correctly if the @apollo/client hooks are commented out and user prop is left undefined when called from ./src/components/App/App.container.tsx.

I tried using yarn's nohoist option in package.json which didn't work. running `npm ls react` only shows react@16.13.1

Any help would be appreciated

**Versions**

npx: installed 1 in 0.831s

  System:
    OS: Linux 5.4 Pop!_OS 20.04 LTS
  Binaries:
    Node: 14.9.0 - ~/n/bin/node
    Yarn: 1.22.5 - ~/n/bin/yarn
    npm: 6.14.8 - ~/n/bin/npm
  Browsers:
    Chrome: 85.0.4183.121
    Firefox: 80.0.1
  npmPackages:
    @apollo/client: 3.2.1 => 3.2.1 
    apollo-cache-persist-dev: ^0.2.1 => 0.2.1

**Comment by darcstar-solutions** [comment]
Update,

I was able to work around the issue by modifying the electron-webpack.js file.

here is it's modified contents:

`const {withExpoAdapter} = require('@expo/electron-adapter');

module.exports = withExpoAdapter({
  projectRoot: __dirname,
  whiteListedModules:["@apollo/client"]
  // Provide any overrides for electron-webpack: https://github.com/electron-userland/electron-webpack/blob/master/docs/en/configuration.md
});
`

electron-webpack sets all modules as external and this apparently causes the issue with the @apollo/client library. I believe that this related to an earlier issue opened against the react-apollo library that was determined to be caused by it having a peer dependency on react 16.8.0

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
