### ISSUE TITLE
watchQuery subscriber receives stale data, despite cache.extract showing fresh data

### ISSUE THREAD

**Issue by ericksonc** [apollographql/apollo-client#7067]
I'm running into an issue where updating elements in the cache isn't being reflected in the subscribe callbacks of watchQueries. Despite that I can see the new data when I inspect the cache directly, the subscribe callback is receiving stale data. FetchPolicy is the default `cache-first`.

I have a mutation that moves items that have a position from 0-5. If the user moves an item from position "5" up to position "2", the `update` function uses `writeFragment` to push the other items down one; position 2 becomes 3, 3 becomes 4 etc.

After the mutation, the subscribe callback function fires for my watchQuery, the "other" items still show their old positions. However, it does include the update for what was moved. So in this example, I now have two items at "position 2."

I've inspected the cache via `cache.extract()` after the update function finishes, as well as at the beginning of the subscribe callback function. Inspecting the cache in this way correctly shows the "moved" positions, despite that the callback is receiving items with the "old" positions.

**Intended outcome:**
The watchQuery's subscriber function should be called with freshly updated data from the cache.

**Actual outcome:**
The watchQuery's subscriber function returns stale data, despite `cache.extract()` showing correct fresh data both before and after the subscriber function fires. 

**Versions**
  System:
    OS: macOS 10.15.5
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.121
    Firefox: 80.0.1
    Safari: 13.1.1
  npmPackages:
    @apollo/client: ^3.2.0 => 3.2.0 
    @apollo/link-context: ^2.0.0-beta.3 => 2.0.0-beta.3 
    vue-apollo: ^3.0.3 => 3.0.3

**Comment by ericksonc** [comment]
After performing the mutation, if I do `client.query(options)` I get the stale data. However, if I do `client.readQuery(options)` I get the fresh data.

It seems that the query just always uses `lastResult` which never picked up on the updates to the cache using writeFragment. Is there anything I can do to make queries / watchQueries notice changes to the cache rather than just always returning lastResult?

**Comment by benjamn** [comment]
@ericksonc Could I trouble you for a [reproduction](https://github.com/apollographql/react-apollo-error-template)? The discrepancy seems worth investigating, but I think I need more concrete details.

**Comment by hwillson** [comment]
If someone can provide a small runnable reproduction that demonstrates this happening with `@apollo/client@latest`, we'll take a closer look. Thanks!

**Comment by f16r** [comment]
Hey,
I had the same/similar problem.
After the variables changed the subscribe function was called twice. On the first call data was containing the right information. On the second call data contained stale cache results.
It seems that I have overcome this issue by unsubscribing before setting the new variables for the next call.

![image](https://user-images.githubusercontent.com/37051913/133161873-b11e6be8-2424-45d2-bf8e-551280dc1ed9.png)
