### ISSUE TITLE
Github Dependency graph - Wrong reposiory

### ISSUE THREAD

**Issue by anup-a** [apollographql/apollo-client#7069]
Dependency graph in Github showing wrong repository for react-apollo . Not sure where to report this > 

![image](https://user-images.githubusercontent.com/29516633/94192322-68028300-fecc-11ea-9405-3e1a0452ca0c.png)

**Comment by raratiru** [comment]
Although this is not the case anymore for this repository, this seems to be a github presentation issue:

It grubs a package name from a "requirements" file and it shows a random fork instead of the repository that is actually related with the package name registered in the package manager.
