### ISSUE TITLE
Update doc for Pagination on fetchMore deprecation

### ISSUE THREAD

**Issue by amaljosea** [apollographql/apollo-client#7073]
Seems like now there is a lot of confusion regarding the docs of pagination due to the warning.

https://spectrum.chat/apollo/apollo-client/the-updatequery-callback-for-fetchmore-is-deprecated~748d6a7c-148c-4ef4-9180-f0f00dbe536e

Thanks for the new `@apollo/client/utilities` which works nicely for me. If it is acceptable I would like to raise a PR with the updated docs with some examples.

**Comment by hwillson** [comment]
The docs have been updated quite a bit since this issue was opened. Let us know if you still think this is an issue. Thanks!
