### ISSUE TITLE
Updating documentation for "deprecated" features in v3

### ISSUE THREAD

**Issue by theaupoulat** [apollographql/apollo-client#7074]
Should we updates, for example, imports for [HOC](https://www.apollographql.com/docs/react/api/react/hoc/#withapollocomponent) or [components](https://www.apollographql.com/docs/react/api/react/components/) , in the v3 docs? 

I am in the middle of migrating my codebase and old code relies on these APIs and I am sure other companies still use to some extent these features.

If yes, I am willing to do it :)

**Comment by hwillson** [comment]
We're planning on removing HOC and Apollo Component support in `@apollo/client@4`, so I'll close this off. Thanks though!
