### ISSUE TITLE
Query on Condition

### ISSUE THREAD

**Issue by codelover2k** [apollographql/apollo-client#7083]
I am using @apollo/react-hooks and I wanted to know if there is a way to conditionally trigger or prevent a query?

There are many use cases I have, one of it is server sider rendering, where I can set my props on the server with, but even if I redirect before, the component is rendered and the query hook is called.

It would be nice to have a flag that tells the hook to not fetch data.

**Comment by rarenatoe** [comment]
https://www.apollographql.com/docs/react/data/queries/#executing-queries-manually

**Comment by dmt0** [comment]
Also `skip` [option](https://www.apollographql.com/docs/react/data/queries/#options)

**Comment by MichaelBurgess** [comment]
Agree with @dmt0 - I make extensive use of the `skip` option to conditionally fire queries using apollo hooks. Great for waiting until other things are loaded etc to prevent wasteful queries that may fail.

**Comment by JayMGurav** [comment]
@michael-watson @dmt0 there is a problems with using `skip` though that queries actually takes place but are later nullified at the client, so one only "pretends " not to query [Here are the details](https://github.com/apollographql/apollo-client/issues/6190)

**Comment by dmt0** [comment]
@JayMGurav works perfectly well in V2. I gave up trying to update to V3 - too many really basic things not working.

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
