### ISSUE TITLE
apollo-client@2.6 testing tools not working with yarn@berry

### ISSUE THREAD

**Issue by Levino** [apollographql/apollo-client#7085]
I created a [demo repo.](https://github.com/Levino/apollo-client-2-yarn-berry). In [master](https://github.com/Levino/apollo-client-2-yarn-berry/tree/master) I am using `apollo-client@2.6` and `yarn@1` which builds fine. When I try to use[ `yarn@2` with `apollo-client@2.6`](https://github.com/Levino/apollo-client-2-yarn-berry/pull/1) the `useQuery` from `react-apollo` does not find the client in the context. When I use [`apollo@3` and `yarn@2`](https://github.com/Levino/apollo-client-2-yarn-berry/pull/2) all works fine again.

I think even though `apollo-client@2.6` is deprecated this should anyhow be fixed. It is not so easy to upgrade a large project from `2.6` to `3.x`...

**Comment by hwillson** [comment]
This doesn't sound like a very common issue, and at this point we're not planning on making any further changes to `2.6` (we're actively working on 4.0 right now). Thanks!
