### ISSUE TITLE
"message": "Network error: fetcher is not a function",

### ISSUE THREAD

**Issue by nikhilkumar24dev** [apollographql/apollo-client#7092]
I am getting above mentioned error I am using below code snippet:

const gql = require("graphql-tag");
const {ApolloClient} = require("apollo-client");
const fetch = require("node-fetch");
const{createHttpLink} = require("apollo-link-http");
const {InMemoryCache} = require("apollo-cache-inmemory");

const httpLink = createHttpLink({
    uri: 'http://localhost:3001/graphql',
    fetch: fetch,
});

const client = new ApolloClient({
    link: httpLink,
    cache: new InMemoryCache(),
});

 var queryField = `query {
        countries {
            id
            available_regions {
                name
                code
            }
        }
    }
    
    `;
    
    const query = gql(queryField);
    var variables = {};

    const result = client.query({
        query,
        variables
      });

**Comment by hwillson** [comment]
If someone can provide a small runnable reproduction that demonstrates this happening with `@apollo/client@latest`, we'll take a closer look. Thanks!
