### ISSUE TITLE
Proposition Use of core-js esnext.observable.js instead of zen-observable

### ISSUE THREAD

**Issue by simonjoom** [apollographql/apollo-client#7096]
Well, like lot of repo use core-js, i decided to try esnext.observable.js with apollo
I'm not sure if it's correct (it's working for me with subscription subscribeToMore (using Map) 
 i can share what i did here.
I use the apollo v2 but i don't think apollo v3 will change something in that
If somebody can test and decide what is the best. 
```
//for apollo2 in 
// instead these import  
// import Observable from 'zen-observable-ts'; 
//add below
import "core-js/modules/esnext.observable.js" 
import "core-js/modules/esnext.symbol.observable.js"  
var redefineAll = require('core-js/internals/redefine-all');

const Observable=global.Observable; 
 redefineAll(Observable.prototype, {
  map:function map(fn) {	
  if (typeof fn !== 'function')
      throw new TypeError(fn + ' is ndot a function');

  //   let C = getSpecies(this);
 let C = this.constructor[Symbol.species];
    return new C(observer => this.subscribe({
      next(value) {
        try { value = fn(value) }
        catch (e) { return observer.error(e) }
        observer.next(value);
      },
      error(e) { observer.error(e) },
      complete() { observer.complete() },
    }));
  }})
 export { Observable }
```

**Comment by benjamn** [comment]
We are much more likely to switch to RxJS—see #5749 for initial exploration/discussion of that.

**Comment by simonjoom** [comment]
yeah i saw it, for me i use core-js as i want a bundle very small and do not need more feature.
core-js allow to avoid symbol-observable dependencies i think too .. but to confirm
