### ISSUE TITLE
Apollo link subscription never stops => Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by Torsten85** [apollographql/apollo-client#7101]
Currently the subscription inside ApolloLink does not stop on unmounting a React Component or unsubscribing to a "watchQuery" subscription. (see https://github.com/apollographql/apollo-client/issues/6985 for a more detailed explanation whats happening)

This also results in the warning `Can't perform a React state update on an unmounted component`.

**Intended outcome:**

The `QueryManager` should stop the subscription from `ApolloLink`

**Actual outcome:**

Subscription never gets stopped

**How to reproduce the issue:**

https://codesandbox.io/s/apollo-client-321-state-unmounted-7mhi8

**Versions**

@apollo/client: ^3.2.1 => 3.2.1

**Comment by jerelmiller** [comment]
Hey @Torsten85! Thanks for the reproduction! Can you try this with the latest version (as of now its `3.7.1`)? Using your codesandbox reproduction, I was able to update to the latest client version and no longer saw this issue.

**Comment by jerelmiller** [comment]
Seeing as it seems to be working with the latest version, I'm going to go ahead and close this issue as I'm also trying to do a bit of housekeeping. If you have further questions or are still seeing issues after updating, please open this issue back up and we'd be happy to help!
