### ISSUE TITLE
Unable to use client with ApolloProvider

### ISSUE THREAD

**Issue by johnneuland** [apollographql/apollo-client#7112]
**Intended outcome:**

I should be able to use my client in the ApolloProvider component without an error. 

**Actual outcome:**

Currently, I get this error. Even though I am simply following the Apollo docs. 
```
Type 'ApolloClient<NormalizedCacheObject>' is missing the following properties from type 'ApolloClient<any>': store, writeData, initQueryManager
```
**How to reproduce the issue:**
```
import { ApolloClient, createHttpLink, InMemoryCache } from '@apollo/client';
import { setContext } from '@apollo/client/link/context';
import { NormalizedCacheObject } from 'apollo-cache-inmemory';
import { ApolloProvider } from '@apollo/react-hooks';
...
const httpLink = createHttpLink({
  uri: 'https://graphql',
});

const authLink = setContext((_, { headers }) => {
  const token = 'XX';
  return {
    headers: {
      ...headers,
      authorization: token ? `Bearer ${token}` : "",
    }
  }
});

const client = new ApolloClient({
  link: authLink.concat(httpLink),
  cache: new InMemoryCache()
});
...

  <ApolloProvider client={client}>
      <BrowserRouter>
        <App />
      </BrowserRouter>
    </ApolloProvider>
```

**Versions**

  System:
    OS: macOS 10.15.5
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Safari: 13.1.1
  npmPackages:
    @apollo/client: ^3.2.1 => 3.2.1 
    @apollo/link-context: ^2.0.0-beta.3 => 2.0.0-beta.3 
    @apollo/react-hooks: ^4.0.0 => 3.1.5 
    apollo-boost: ^0.4.9 => 0.4.9 
    react-apollo: ^3.1.5 => 3.1.5

**Comment by benjamn** [comment]
@johnneuland Have you tried importing `ApolloProvider` from `@apollo/client` instead of `@apollo/react-hooks`?

**Comment by johnneuland** [comment]
I just tried it and although it removes this particular error, it gives me this: https://github.com/apollographql/apollo-client/issues/2042 and now again, I have no idea how to fix this

**Comment by johnneuland** [comment]
I just tried this and although it fixes this problem, now it gives me this error and again, idk how to fix this.
https://github.com/apollographql/apollo-client/issues/2042

**Comment by johnneuland** [comment]
×
Could not find "client" in the context or passed in as an option. Wrap the root component in an <ApolloProvider>, or pass an ApolloClient instance in via options.

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding bug here. For help using Apollo Client, please visit our community forums: https://community.apollographql.com

**Comment by KennedyKeinstein** [comment]
> @johnneuland Have you tried importing `ApolloProvider` from `@apollo/client` instead of `@apollo/react-hooks`?

Thanks @johnneuland worked for me!
