### ISSUE TITLE
Broken resetStore for queries with skip

### ISSUE THREAD

**Issue by MellowoO** [apollographql/apollo-client#7113]
Hi all! I updated from apollo-client 2.6 to @apollo/client 3.2.2 and had some unexpected behavior. 

**Intended outcome:**
Query with flag `skip=true` on call `client.resetStore()` shouldn't be refetched

**Actual outcome:**
Query with flag `skip=true` on call `client.resetStore()` refetches

**How to reproduce the issue:**
1) create query, set flag `skip=true`
2) call client.resetStore()

**Versions**
  System:
    OS: macOS 10.15.5
  Binaries:
    Node: 14.11.0 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.121
    Firefox: 80.0.1
    Safari: 13.1.1
  npmPackages:
    @apollo/client: ^3.2.2 => 3.2.2 
  npmGlobalPackages:
    apollo: 2.30.3

**Comment by joncursi** [comment]
I am getting the same error. Has anyone found a solution to this one?

**Comment by joshjg** [comment]
Appears to have been caused by #6999

**Comment by benjamn** [comment]
This should be fixed in `@apollo/client@3.2.4`, thanks to #7146 by @joshjg.
