### ISSUE TITLE
resetStore causes queries with notifyOnNetworkStatusChange to return undefined

### ISSUE THREAD

**Issue by joshjg** [apollographql/apollo-client#7138]
**Intended outcome:**
Calling `client.resetStore` should properly update all watched queries, even if they have `notifyOnNetworkStatusChange: true`

**Actual outcome:**
`result.data` is undefined for queries that set `notifyOnNetworkStatusChange: true` after calling `client.resetStore`

**How to reproduce the issue:**
- Go here: https://codesandbox.io/s/condescending-rhodes-rot9y?file=/src/index.js
- Click the `resetStore()` button
- Notice the `useQuery` `result.data` is undefined.
- Repeat with `notifyOnNetworkStatusChange: false`, and notice the query updates as expected.

**Versions**
@apollo/client - 3.2.2
graphql - 14.7.0

Also tried with `3.3.0-beta.10` - same issue.

**Comment by lucas-calzolari-toptal** [comment]
I am having a hard time with the same issue.

**Comment by lucas-calzolari-toptal** [comment]
Adding some info from my specific case, it seems like for the issue to happen, besides having notifyOnNetworkStatusChange = true, you also need the query before and after reset store to return the same value.

If I reset store adding an authentication and get a different result, it works correctly even with notifyOnNetworkStatusChange as true.

**Comment by joshjg** [comment]
Looking back through the version history for v3, it looks like it broke between 3.0.0-rc.4 and 3.0.0-rc5. And combined with @lucas-calzolari-toptal 's observation above it looks like this is probably the culprit: https://github.com/apollographql/apollo-client/commit/0962d259207034233a17fdcc872e16068cdbeb42

**Comment by benjamn** [comment]
This should be fixed in `@apollo/client@3.2.4`, thanks to #7150.
