### ISSUE TITLE
Optimistic queries or how can I hydrate Apollo store from local storage

### ISSUE THREAD

**Issue by tomitrescak** [apollographql/apollo-client#714]
Hi, you have a pretty wicked mechanism for optimistic response to mutations. Can something similar be achieved with queries? I searched your docs but I can't find it.

The idea is to store query results in the local storage and then either:
1. Use directly Redux store initialisation with data from local storage (this I think can mess up the caching mechanism and you wouldn't get fresh data from the serve)

Or
1. Have a query return data from the local cache and update once the response comes from the server. This would be gold!

I'm pretty sure you guys already have this I just can't find it.

**Comment by smolinari** [comment]
There was a good bit of discussion about it here: https://github.com/apollostack/apollo-client/issues/424

Currently, there is no local storage support (if I understand your concerns correctly).

Scott

**Comment by helfer** [comment]
@tomitrescak We're going to do a refactor soon, which should make many of the things you mentioned possible.

**Comment by tomitrescak** [comment]
Good news! Am working on the server part now, so I can wait. What would be the ETA for this? Just informative, I know you guys don't like deadlines ;)

**Comment by funkyeah** [comment]
@calebmer is this still in progress, done, or dead?

**Comment by helfer** [comment]
I'm not sure why an `in progress` label was added to this issue, but I'm going to close it, because I believe what was originally asked for can now be done with the `cache-and-network` fetch policy (see the [docs](http://dev.apollodata.com/react/api-queries.html#graphql-config-options-fetchPolicy)).
