### ISSUE TITLE
`resetStore` fetches `watchQuery` that has never been subscribed to

### ISSUE THREAD

**Issue by KeithGillette** [apollographql/apollo-client#7145]
**Intended outcome:**
Calling ApolloClient.resetStore() should not execute queries that are not actively subscribed to.

**Actual outcome:**
Calling ApolloClient.resetStore() causes a `watchQuery` that has been assigned to a variable but _never subscribed to_ to fetch data.

**How to reproduce the issue:**
Follow instructions on [my Apollo-Angular StackBlitz reproduction](https://stackblitz.com/edit/apollo-client-3-reset-store?file=app/list.component.ts).

**Versions**
```
  System:
    OS: macOS 10.15.6
  Binaries:
    Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
    Yarn: 1.22.5 - ~/.nvm/versions/node/v12.18.4/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.18.4/bin/npm
  Browsers:
    Chrome: 86.0.4240.75
    Firefox: 81.0.1
    Safari: 14.0
  npmPackages:
    @apollo/client: 3.2.2 => 3.2.2 
    apollo-angular: 2.0.4 => 2.0.4 
    apollo-server-express: 2.18.1 => 2.18.1 
```

**Comment by benjamn** [comment]
This should be fixed in `@apollo/client@3.2.4`, thanks to #7146 by @joshjg.
