### ISSUE TITLE
AC3: Memory leak in `watchQuery` retains `context` object in memory even after `unsubscribe`

### ISSUE THREAD

**Issue by dotansimha** [apollographql/apollo-client#7149]
**Intended outcome:**

Object passed as `context` to `watchQuery` method should be released when `unsubscribe` is called, instead of being retrained in memory.

I'm opening this because this seems like another symptom of a related issue, but with a testable reproduction, and including the heap snapshots files.

I believe this is very related to what @Torsten85 posted here: https://github.com/apollographql/apollo-client/issues/6985#issuecomment-701240849

**Actual outcome:**
`context` object are retained in memory by AC3:
![image](https://user-images.githubusercontent.com/3680083/95685129-a606e300-0bfe-11eb-9e64-aab7a8a608f9.png)

**How to reproduce the issue:**
Use `watchQuery` with `context` set. Apollo keeps reference to that object even if query has done, and `unsubscribe` has been called (and all references has been destructed).

You can find a complete reproduction (as a Jest test + instructions) here:
 https://github.com/dotansimha/apollo-very-pessimism

**Versions**
`>=3`

**Comment by dotansimha** [comment]
Updated the reproduction with the heap snapshot file (https://github.com/dotansimha/apollo-very-pessimism#heap-snapshot)

**Comment by kamilkisiela** [comment]
We managed to fix the leak by patching `optimism` and `@apollo/client` packages ([patches](https://github.com/dotansimha/apollo-very-pessimism/tree/073950d7a78c7e876d30dc3e107e3222a93b2e71/patches)).

In `optimism`:

```diff
diff --git a/node_modules/optimism/lib/bundle.esm.js b/node_modules/optimism/lib/bundle.esm.js
index 99c5962..546fa35 100644
--- a/node_modules/optimism/lib/bundle.esm.js
+++ b/node_modules/optimism/lib/bundle.esm.js
@@ -510,6 +510,10 @@ function wrap(originalFunction, options) {
             return entry.peek();
         }
     };
+    optimistic.delete = function (key) {
+        const k = makeCacheKey(key);
+        cache.delete(k)
+    }
     return optimistic;
 }
```

In `@apollo/client`:

```diff
diff --git a/node_modules/@apollo/client/cache/inmemory/inMemoryCache.js b/node_modules/@apollo/client/cache/inmemory/inMemoryCache.js
index b421d3a..6618215 100644
--- a/node_modules/@apollo/client/cache/inmemory/inMemoryCache.js
+++ b/node_modules/@apollo/client/cache/inmemory/inMemoryCache.js
@@ -129,6 +129,8 @@ var InMemoryCache = (function (_super) {
             this.maybeBroadcastWatch(watch);
         }
         return function () {
+            _this.watchDep.dirty(watch);
+            _this.maybeBroadcastWatch.delete(watch);
             _this.watches.delete(watch);
         };
     };
```

Above changes are related to #7086. Cleaning up the records in `dep` and `wrap` functions of `optimism` when `watch` is completed makes sure it doesn't hold a reference to `QueryInfo => ObservableQuery => ObservableQuery.options => options.context` anymore.

But there's more...

Testing the same scenario but with Apollo Client v2.6 gives a successful and expected result but we noticed something very weird. The reference to an object in context is gone after ~15s but in Apollo Client v3.0 it is ~20s.

**Comment by benjamn** [comment]
Thanks to @dotansimha's reproduction and @kamilkisiela's proposed solution, I'm confident this leak is fixed in `@apollo/client@3.2.4` and `@apollo/client@3.3.0-beta.12`. Thanks a ton!

**Comment by benjamn** [comment]
@dotansimha As a side note, the weak reference approach you used in your reproduction (using [`weak-napi`](https://www.npmjs.com/package/weak-napi)) is 🤯 —definitely using that the next time I need to write a memory leak regression test that runs in Node!

**Comment by dotansimha** [comment]
Thank you @benjamn ! 
Btw, you can take a look at the rest of the branches in my reproduction, we added more use cases (`watchQuery` + `mutation` that effects it, `subscription` and some more). 

@kamilkisiela you found something else with mutations that throws error, right? 

Maybe these tests can be wrapped and move to this repo? just to make sure CI does that as well and we are not experiencing any regression.

**Comment by kamilkisiela** [comment]
@dotansimha yes, quick LARGE coffee and then I'm going to create a reproduction with a fix.
