### ISSUE TITLE
How to catch errors on ApolloProvider globally

### ISSUE THREAD

**Issue by ariel-upstream** [apollographql/apollo-client#7152]
I'm trying to catch all my graphQLErrors with the onError method from apollo client. 
My goal is to have only one catch block for all of my API calls.

I'm using the onError method from the "@apollo/client/link/error"

```
const errorLink = onError(({ graphQLErrors, networkError ,operation}) => {
   if (graphQLErrors && graphQLErrors?.length > 0) {
     catchError((e) => handleError(e))
   } else if (networkError) {
     console.log(`[Network error]: ${networkError}`)
   }
})
```

The current behavior is: 
If I do not catch each error inside the component that made the API call the default error page appears with the error and my app crashed

The desired behavior:
The default error page will never appear (the error will be handled inside the onError method)

I tried also to change the apolloClient:

`` const apolloClient = new ApolloClient({
    ...
    defaultOptions: {
      mutate: { errorPolicy: "ignore" },
    },
  })``

The app did not crash if I'm not catching the error inside each component,
but the issue now is that the onCompleted method of my useMutation calls triggered even if an error occurred

Thanks.

**Comment by cmnstmntmn** [comment]
@ariel-upstream this is not possible with apollo;
there are plenty of unresolved issues on this subject.

you better switch to plain queries/mutations and use *fetch()*

**Comment by hwillson** [comment]
If someone can provide a small runnable reproduction that demonstrates this happening with `@apollo/client@latest`, we'll take a closer look. Thanks!
