### ISSUE TITLE
graphql HOC not updating component props properly after an error was received

### ISSUE THREAD

**Issue by Mrtblg** [apollographql/apollo-client#7154]
When using the graphql HOC, after an API error, the child component does not receive the expected props values

**Intended outcome:**
When I have a query with variables and I produce theses steps I expect :
* send a query with `id=1` => success data={object1}
* send the query with `id=-1` => error1
* send back the query with `id=1` => I expect to read  success data={object1} from the cache BUT I receive error1 from the cache

**How to reproduce the issue:**
Here is a sandbox to reproduce the issue : https://codesandbox.io/s/restless-cookies-f8v1w?fontsize=14&hidenavigation=1&theme=dark

Click `set id to -1 (error)` then click back `set id to 1 (Cowboy Bebop)` you will see that you get an error and that it does not update to a success.

**A second issue probably linked to this one:**
I witness an other bug which I assume is linked to this one. I didn't procude a sandbox because it would require a more complex public API that I don't have.

If one of the query variables (ex: `filters`) is an array of strings. And if you reproduce the following steps.
* first call with `filters=['en']` => 404
* second call with `filters=['fr']` => I'm suck with `Error` during the loading phase I never receive `loading = true`
* then the request completes, i get the result and the component updates

I witness the bug in my project, but i don't witness it in my sandbox. I suspect it might come from the fact that my variable is an array and it is harder to watch for changes.

**Versions**
```
"@apollo/client": "3.2.3",
"graphql": "15.3.0",
```

```
"react": "16.13.1",
"react-dom": "16.13.1",
"react-scripts": "3.4.3"
```

**Comment by Mrtblg** [comment]
Any news on this ?
Did anyone have a chance to test the sandbox ?

blocking issue here

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
