### ISSUE TITLE
Optimistic response not working when there is a @client(always: true) in the query

### ISSUE THREAD

**Issue by JesseZomer** [apollographql/apollo-client#7155]
**Intended outcome:**

Doing a mutation with an update function that does a read/write query doesn't update the query with optimistic response data when the query has an @client(always: true) in it, but it should. Removing the '(always: true)' fixes it.

**Actual outcome:**

It goes through the update function twice, but the optimistic response data from the writeQuery is never shown in the component.

**How to reproduce the issue:**

I've made a reproduction stackblitz: https://stackblitz.com/edit/simple-apollo-angular-example-ljqtvr?file=app%2Flist.component.ts
Just upvote a post and see there is no extra post being added until after the real request returns. Remove the `(always: true) from the query and the optimistic response works again.
**Versions**

    "@apollo/client": "^3.0.0",
    "apollo-angular": "^2.0.4",

I know the https://www.apollographql.com/docs/react/local-state/local-resolvers/#forcing-resolvers-with-clientalways-true part of the documentation is now deprecated, but this should still work right? We had these query's with v2 and this (silently) broke when going to v3. Is it even still relevant with the new typePolicies? I haven't read anything about having to remove the (always: true) part, did I miss something?

**Comment by hwillson** [comment]
This will be better answered in the https://github.com/kamilkisiela/apollo-angular repo. Thanks!
