### ISSUE TITLE
 Cannot assign to read only property 'orderStatusCode' of object '#<Object>'

### ISSUE THREAD

**Issue by Pep6** [apollographql/apollo-client#7172]
Hi, 

I'm trying to migrate from AC2 version: '2.6.8' to AC3 (version "^3.2.3"), but I have one issue in one query, below the details and screenshot:

![image](https://user-images.githubusercontent.com/72994570/96295860-576d9600-0fbc-11eb-9594-4854d099c81d.png)

# Code:
  ```
import { select } from 'redux-saga/effects';
import {
  ApolloClient,
  HttpLink,
  ApolloLink,
  InMemoryCache,
  fromPromise,
  gql,
  from,
} from '@apollo/client';
import { onError } from '@apollo/client/link/error';

export function* getDetailsRequest() {
const userId = yield select(makeSelectUserId());
  return yield apolloClient
    .query({
      query: gql`
      query GeDetailsRequest{
       geDetailsRequest(
        criteria: {
          userId :"${userId}"
          statuses: ["ACTIVE","CANCELED"]
        }
        sortDirection: "DESC"
        sortProperty: "creationDateTime"
      ){
        content{
            orderStatusCode
            reservationId
            reservationStatus
        }
      }
    }
    `,
    })
    .then(response => {
      let responseData =  Object.assign({}, response)
      console.log('responseData', responseData)
      //check for order status code is empty
      if (responseData.data.geDetailsRequest.content.length !== 0) {
        if (responseData.data.geDetailsRequest.content.length > 1) {
          for (let i = 0; i < responseData.data.geDetailsRequest.content.length; i++) {
            console.log('i', i)
            if (responseData.data.geDetailsRequest.content[i].orderStatusCode === null || responseData.data.geDetailsRequest.content[i].orderStatusCode === '') {
// ##This assignment is the one that is failing, I tried to create a copy of the response object but did not work.##
              responseData.data.geDetailsRequest.content[i].orderStatusCode = responseData.data.geDetailsRequest.content[i].reservationAdminStatus;
            }
          }
        } else if (responseData.data.geDetailsRequest.content[0].orderStatusCode === null || responseData.data.geDetailsRequest.content[0].orderStatusCode === '') {
          responseData.data.geDetailsRequest.content[0].orderStatusCode = responseData.data.geDetailsRequest.content[0].reservationAdminStatus;
        }
        debugger;
        return responseData.data;
      } else {
        return null;
      }
    })
    .catch(error => {
      console.log('Error inside gql request______________________________', error)
      throw error;
    });
}
```

**Intended outcome:**

I should receive the returnData object without errors, 

**Actual outcome:**

TypeError: Cannot assign to read only property 'orderStatusCode' of object #< Object >

![image](https://user-images.githubusercontent.com/72994570/96294586-9a2e6e80-0fba-11eb-8b19-98ce258b52a4.png)

**How to reproduce the issue:**

**Versions**
My package.json looks like this:

"dependencies": {
    "@apollo/client": "^3.2.3",
    "graphql": "^14.7.0",
    "redux": "^4.0.5",
    "redux-saga": "1.0.2",
    "react-redux": "^7.2.1",
    "react-router-dom": "5.0.0",
    "webpack": "^4.41.2",
    "webpack-cli": "^3.3.11",
    "webpack-dev-middleware": "3.6.2",
    "webpack-hot-middleware": "2.24.3",
    "webpack-pwa-manifest": "^4.2.0",
    "whatwg-fetch": "3.0.0"
}
-->

**Comment by benjamn** [comment]
@Andreshm94 AC3 cache results are immutable, so you need to update them non-destructively. See [this blog post](https://www.apollographql.com/blog/whats-new-in-apollo-client-2-6-b3acf28ecad1/) for the original motivation behind this policy, or https://github.com/apollographql/apollo-client/pull/4543 for a more technical explanation of the benefits.
