### ISSUE TITLE
how to add custom headers with query 

### ISSUE THREAD

**Issue by lifeeric** [apollographql/apollo-client#7176]
Hi,

I'd like to ask you, is there any possibility to add custom header with `query` hook. something like this 
```js
  const [loadData, { loading, data }] = useLazyQuery(Query, {
    headers: {
          ......
    }
})
```

I don't want to use the default header with this query of the `setContext`. I'm wondering how can I add another header with the above query.

Thanks, Apollo!

**Comment by dusty** [comment]
It goes inside context prop

```
const [loadData, { loading, data }] = useLazyQuery(Query, {
    context: { headers: { authorization: `Bearer ${token}` } }
})
```

**Comment by lifeeric** [comment]
Hi, @dusty I already did that. how can I pass the header from the hooks as in the above example!

**Comment by electrovir** [comment]
This does not work if the header is dynamic, the headers will get stuck on the first used value. Disabling the cache makes no difference.
