### ISSUE TITLE
`option.query` property is ignored in `useQuery` hook (bug or doc is not clear) 

### ISSUE THREAD

**Issue by euvs** [apollographql/apollo-client#7194]
This is either a bug, or the documentation needs clarification.

According to the documentation for the `useQuery` hook, `options.query` property is optional. 

OPTION | TYPE | DESCRIPTION
-- | -- | --
query | DocumentNode | A GraphQL query document parsed into an AST by graphql-tag. **Optional for the useQuery Hook since the query can be passed in as the first parameter to the Hook**. Required for the Query component.
--|--|--

What will happen if the hook is call this way?

```js
const ql1 = gql`...`
const ql2 = gql`...`
const res = useQuery(ql1, {query: ql2}); 
```

One would assume that the `ql2` will be take precedence in this case. The doc does not clarify this. 

However, looking at the source code, the `ql1` takes priority, no matter what is provided in `options`.

```js
updatedOptions = options ? { ...options, query } : { query }; 
```

https://github.com/apollographql/apollo-client/blob/a975320528d314a1b7eba131b97d045d940596d7/src/react/hooks/utils/useBaseQuery.ts#L23

**Why this is important**

Here is my usage scenario

```js
// use-query-foo.ts

// default GQL query
const defaultQL = gql``

// Create custom Hook
export const useQueryFoo = (id, options) => {
    const variables = {
        id: id
    }
    
    return useQuery(defaultQL, {
        variables: variables, 
        ...options
    })
}

```

```js
// componentA.ts

import {useQueryFoo} from './use-query-foo'

// use hook with the default query
const r1 = useQueryFoo(1)

// use hook with a custom query
const r2 = useQueryFoo(2, {query: customQL}) // <== This does not work. Custom query will be ignored. 
```

This does not work. Custom query is ignored.

**Comment by Experiment8** [comment]
Having the same exact issue. We're using useQuery hook in many places, and we usually add the query option to narrow down the model of the results tailored on what we need.

Just noticed today while mocking the tests, that it does not really use the passed query and just requests the entire model, completely ignoring the passed query.

**Comment by hwillson** [comment]
We'll need a runnable reproduction (using `@apollo/client@latest`) to be able to troubleshoot this further. Thanks!

**Comment by aplum** [comment]
@hwillson Here's a reproduction for this: https://github.com/aplum/react-apollo-error-template-7194

**Comment by bignimbus** [comment]
Hi all 👋🏻  in short, please do use the first argument to pass a query document to `useQuery` and not `options.query`.  Release 3.8 will include a change that prevents TypeScript users from inadvertently using `options.query`.  See https://github.com/apollographql/apollo-client/pull/10527 for more details!

I'll close this as completed for now.  Thanks all for your patience!
