### ISSUE TITLE
setMutation ?

### ISSUE THREAD

**Issue by japrogramer** [apollographql/apollo-client#7203]
```
const [ChgDocument, { data : mutresult, loading : mutloading, error : muterror }] = useMutation( id ? UpdateLocation : CreateLocation);
```
As you can see the initial state for useMutation is determined by id but there is no way to `setMutation`
so that I can update the mutation that should be used.

I would like to update the mutation that is used.

**Comment by hwillson** [comment]
We'll need a runnable reproduction (using `@apollo/client@latest`) to be able to troubleshoot this further. Thanks!
