### ISSUE TITLE
Unknown GET request from react-native in heroku router

### ISSUE THREAD

**Issue by rvieceli** [apollographql/apollo-client#7204]
When I open our app, all normal, but when I close, I got a unknown GET request to `/graphql`, but we don't use GET request.

When I close the app, I got the following log on heroku. Each time that I close the app, I got the same result.
```
2020-10-20T06:54:56.761829+00:00 heroku[router]: at=info method=GET path="/graphql" host=api.ourapp.com r dyno=web.2 connect=0ms service=89345ms status=101 bytes=165 protocol=https
```

How I can identify this request?

```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Browsers:
    Chrome: 85.0.4183.83
    Firefox: 81.0.2
    Safari: 14.0
  npmPackages:
    apollo-server-express: ^2.2.3 => 2.9.16 

  Browsers:
    Chrome: 85.0.4183.83
    Firefox: 81.0.2
    Safari: 14.0
  npmPackages:
    @apollo/client: ^3.2.4 => 3.2.4 
```

**Comment by rvieceli** [comment]
I discovered the is request is from web socket. 

is it right? or How to disconnect web socket when closing the app?

**Comment by hwillson** [comment]
This doesn't sound like an Apollo Client issue, but if anyone thinks it is and can provide a small runnable reproduction using `@apollo/client@latest`, we'll take a look. Thanks!
