### ISSUE TITLE
Is relaypagination() appending new collection to existing collection?

### ISSUE THREAD

**Issue by albuen03** [apollographql/apollo-client#7207]
I am working using relay pagination. I want to append incoming edges to the existing edges but relay pagination keeps on overriding existing edges. Is this a normal behavior?

**Comment by benjamn** [comment]
Are you providing an `args.after` cursor, either from the `edge.cursor` of the last edge or from `pageInfo.endCursor`?

**Comment by albuen03** [comment]
Yes, I'm providing `args.after` in the query based on `endCursor`, I created my own merge functionality based on `relayStylePagination` `merge` to achieve the desired behavior.

**Comment by tsnieman** [comment]
@albuen03 Would you mind sharing your solution? I am facing similar issues and it seems like we have a similar approach to our pagination variables.

**Comment by firmanjml** [comment]
I am having the same behavior and I don't this is normal. Shouldn't it append new data with old?
Here's my code snippet, and I'm not sure if I'm doing this right.

```
const client = new ApolloClient({
  cache: new InMemoryCache({
    typePolicies: {
      Query: {
        fields: {
          getMessages: relayStylePagination()
        }
      }
    }
  }),
  link
});
```

```
if (data.getMessages.pageInfo.hasNextPage) {
    fetchMore({
        variables: {
            before: data.getMessages.pageInfo.endCursor
        }
   });
}
```

```
query getMessages($id: Int!, $before: String) {
  getMessages(offerId: $id, before: $before) {
    pageInfo {
      endCursor
      hasNextPage
    }
    edges {
      node {
        _id: id
        text
        user: sender {
          _id: id
        }
      }
      cursor
    }
  }
}
````

**Comment by albuen03** [comment]
@tsnieman @firmanjml  I created somewhat like `merge(existing, incoming) {
            return {
              ...existing,
              ...incoming,
              edges: compact(
                uniqBy(
                  'node.__ref',
                  concat(get('edges', existing), get('edges', incoming))
                )
              )
            };
          }` . I lacks the data updating part but you can start from here.

**Comment by albuen03** [comment]
@tsnieman @firmanjml I created somewhat like 
```
merge(existing, incoming) {
            return {
              ...existing,
              ...incoming,
              edges: compact(
                uniqBy(
                  'node.__ref',
                  concat(get('edges', existing), get('edges', incoming))
                )
              )
            };
          }
```

It appends the data to the existing collection.

**Comment by ruipneves** [comment]
I am having a strange behavior using `relayStylePagination` and `optimisticResponse`.
For some reason, the `optimisticResponse` seems to be working just fine as it is immediately shown in the UI and updated when the response comes from the server but, the entire list gets re-rendered on both situations. It seems that the node references are constantly changing.

I have tried to modify the `relayStylePagination` merge function and apparently something before the merge function is modifying the array references.

If I don't try to modify the cache in the mutation and let the subscription handle the merge with `updateQuery` the references are not modified.

Can anyone help me?

@benjamn

**Comment by Flusinerd** [comment]
@firmanjml 
Did you manage to find a solution?
I am running into the same issue, with ``after`` set and ``pageInfo.endCursor`` and ``edges[].cursor`` also queried

**Comment by alimoli** [comment]
Any news?

**Comment by bignimbus** [comment]
Hi folks, this issue is a bit stale and it appears that this may have been resolved in https://github.com/apollographql/apollo-client/issues/4141.  If folks are still experiencing similar issues in the latest client version please do feel free to open a new issue or ping this one and we can consider re-opening depending on the details.  Thanks so much all!
