### ISSUE TITLE
Cannot Assign value from 'watchQuery' to a type of Observable as indicated in documentation

### ISSUE THREAD

**Issue by krejko** [apollographql/apollo-client#7210]
Hello, 

I was following the instructions under the 'Using with AsyicPipe' section of this documentation: https://www.apollographql.com/docs/angular/basics/queries/ 

`data: Observable<any>;`

`ngOnInit() {`
`    this.data = this.apollo.watchQuery({query: FeedQuery}).valueChanges;`
` }`

However, when I try to assign the `this.data` I get the following error: 

`Type 'Observable<ApolloQueryResult<unknown>>' is missing the following properties from type 'Observable<any>': [Symbol.observable], map, filter, reduce, and 2 more.ts(2740)`

Angular suggests casting to unknown then the type Observable<any> to hide the error message, but this doesn't seem like it should be necessary. If it is necessary, it should be included in the instructions. 

**Intended outcome:**
I expected following the instructions exactly would not generate an error. 

**Actual outcome:**
I am unable to continue with the example provided. Deviation from these instructions is needed for the app to compile.   

**How to reproduce the issue:**
Follow the instructions on the page listed above to observe that you cannot assign the observable. 

**Versions**
This affects apollo-client "^2.6.10"

**Comment by teebszet** [comment]
I just stumbled upon this, but @krejko you might be looking at documentation for apollo-angular 1.0. the versioned documentation is here: https://apollo-angular.com/docs 

It's a bit hard to find, since google prefers the apollographql.com docs

**Comment by hwillson** [comment]
Answered in https://github.com/apollographql/apollo-client/issues/7210#issuecomment-717735868 - thanks!
