### ISSUE TITLE
Received error "The pipe 'select' could not be found" when following tutorial instructions

### ISSUE THREAD

**Issue by krejko** [apollographql/apollo-client#7211]
Hello, 

I was following the instructions under the 'Using with AsyicPipe' section of this documentation: https://www.apollographql.com/docs/angular/basics/queries/ 

After setting up my template according to the instruction, I had the following:
`<ul *ngFor="let entry of data | async | select: 'feed'">`
`      Score: {{entry.score}}`
`</ul>`

However, when I navigate to the page I get the following error in the browser's console: 

`core.js:4197 ERROR Error: Uncaught (in promise): Error: The pipe 'select' could not be found!
Error: The pipe 'select' could not be found!`

**Intended outcome:**
I expected following the instructions exactly would not generate an error. If this pipe needs to be explicitly added for these instructions to work, it should be included in the instructions. 

**Actual outcome:**
The template fails to display the content in the template

**How to reproduce the issue:**
Follow the instructions on the page listed above to observe that you cannot use the provided template. 

**Versions**
- apollo-client "^2.6.10"
- apollo-angular "^2.0.4"
- Angular 10

**Comment by hwillson** [comment]
This is best asked over in https://github.com/kamilkisiela/apollo-angular. Thanks!
