### ISSUE TITLE
Cannot import ApolloModule according to instructions

### ISSUE THREAD

**Issue by krejko** [apollographql/apollo-client#7212]
Hello, 

I was following the instructions under the 'Installation without Angular Schematics' section of this documentation: https://www.apollographql.com/docs/angular/basics/setup/

After importing ApolloModule according to the instruction, I had the following:
`import { ApolloModule, APOLLO_OPTIONS } from "apollo-angular";`

However, when I save the file I get a compiler error: 

`error TS2305: Module '"../../../../node_modules/apollo-angular/ngApollo"' has no exported member 'ApolloModule'.`

`2 import { ApolloModule, APOLLO_OPTIONS } from 'apollo-angular';`

**Intended outcome:**
I expected following the instructions exactly would not generate an error. If there is a different way to import the module for these instructions to work, it should be included in the instructions. 

**Actual outcome:**
The app fails to compile

**How to reproduce the issue:**
Follow the instructions on the page listed above to observe that you cannot import the required module. 

**Versions**
This affects 

- apollo-client "^2.6.10"
- apollo-angular "^2.0.4"
- Angular 10

**Comment by krejko** [comment]
This may be a duplicate of the following ticket. 
- https://github.com/kamilkisiela/apollo-angular/issues/1576

**However**, If the documentation page linked in the issue above will not be kept up-to-date, this ticket should be to consider removing it from the site and instead linking to the updated instructions.

**Comment by fetis** [comment]
Hello @krejko 
Please use https://apollo-angular.com/docs/get-started for documentation.

See https://github.com/kamilkisiela/apollo-angular/issues/1587 for more details

**Comment by DDoerner** [comment]
@fetis The v2 documentation you linked still uses ApolloModule once. I've followed the page and had the same issue. 

It's not mentioned in the text, but still used in a code block:
>```
> @NgModule({
>  imports: [BrowserModule, ApolloModule, HttpClientModule],
>  ...
>```

**Comment by semcold** [comment]
> @fetis The v2 documentation you linked still uses ApolloModule once. I've followed the page and had the same issue.
> 
> It's not mentioned in the text, but still used in a code block:
> 
> > ```
> > @NgModule({
> >  imports: [BrowserModule, ApolloModule, HttpClientModule],
> >  ...
> > ```

so, how to resolve this problem?

**Comment by fetis** [comment]
@DDoerner  @semcold don't use `ApolloModule` it was removed from the package. Code without it works just fine. I'll update the doc

**Comment by kodeine** [comment]
same problem!

**Comment by DDoerner** [comment]
For anyone finding this thread after reading outdated documentation (e.g. @kodeine):
The code is correct, except for `ApolloModule`, which is no longer used. Follow the code, but don't import or use `ApolloModule`. No need to replace it with anything else and everything should work.

**Comment by aandr075** [comment]
https://apollo-angular.com/docs/1.0/basics/network-layer

this documentation still uses ApolloModule
