### ISSUE TITLE
Local / client side field type validation broken / missing

### ISSUE THREAD

**Issue by BerndWessels** [apollographql/apollo-client#7218]
**Intended outcome:**

Write Query to Cache - expecting an error or warning indicating that the `age` field type doesn't match the query.

```js
const client = new ApolloClient({
  // Provide required constructor fields
  cache,
  link,
  // Provide some optional constructor fields
  name: "client-web-api",
  version: "1.0",
  queryDeduplication: false,
  defaultOptions: {
    watchQuery: {
      fetchPolicy: "cache-and-network",
    },
  },
  typeDefs: gql`
    type Client {
      name: String!
      age: Int!
    }
    extend type Query {
      client: Client @client
    }
  `,
});
```

```js
      client.writeQuery({
        query: gql`
          query setMe {
            client @client {
              name
              age
            }
          }
        `,
        data: {
          client: {
            name: "Tom",
            age: "29",
          },
        },
      });
```

**Actual outcome:**

No error, no warning, `age` field is set to string `"29"` even though the type is `Int!`.

**Versions**

```json
    "@apollo/client": "^3.2.2",
    "graphql": "^15.3.0"
```

**Comments**

Since local resolvers are deprecated it seems that either some features like local field schema validation haven't made it into the local `typeDefs` feature or the documentation isn't complete.

A much better documentation with proper examples is needed for how to properly define and use local / client only fields and schemas.

**Comment by benjamn** [comment]
@BerndWessels I can understand your surprise, but the client does not currently validate or enforce result types at runtime. Instead, we recommend more static techniques like TypeScript code generation for query types. The `typeDefs` option for `ApolloClient` is for consumption by tools like the [VSCode Apollo plugin](https://marketplace.visualstudio.com/items?itemName=apollographql.vscode-apollo), not for dynamic type checking.

**Comment by BerndWessels** [comment]
@benjamn Thank you. Maybe that can be made a bit clearer in the documentation. And if possible it would be great if the local/client side schema would act exactly like the remote schema in the future. Ideally even with federation in mind.

**Comment by hwillson** [comment]
The docs have been updated quite a bit since this issue was opened. Let us know if you still think this is an issue. Thanks!
