### ISSUE TITLE
Use thunk or some other kind of redux middleware to dispatch requests

### ISSUE THREAD

**Issue by tmeasday** [apollographql/apollo-client#722]
It seems more idiomatic Redux, and thus better supported by 3rd party redux tools which operate at the level of middleware/dispatched actions, to dispatch network requests in a middleware.

Discussions:
- [Will avoid problems with time-travelling in future versions of redux dev tools](https://github.com/apollostack/apollo-client/issues/701#issuecomment-249829507)
- [Will allow `redux-action-buffer` to buffer initial events while restoring the store](https://github.com/apollostack/apollo-client/issues/604#issuecomment-249783589)

The basic proposal is rather than 
1. `client.watchQuery().subscribe()` calling
   
   a. `QueryManager#fetchRequestOverInterface`, which
   
     i. Dispatches `APOLLO_QUERY_INIT`, then
     ii. Fires a network request, which after returning
     iii. Dispatches `APOLLO_QUERY_RESULTS`

We should try
1. `client.watchQuery().subscribe()` calls
   
   a. `QueryManager#fetchRequestOverInterface`, which
   
     i. Dispatches a thunk, which does i-iii. above.

Alternatively some other mechanism could be used to fire the request, via the client's middleware.

**Comment by helfer** [comment]
cc @calebmer Let's keep this in mind while we rethink the store architecture. If possible, it would be nice if our Redux integration could provide this.

**Comment by helfer** [comment]
Closing this up since it's pretty old and just an idea, not an issue.
