### ISSUE TITLE
Missing ID on an object causes silent bugs

### ISSUE THREAD

**Issue by Elijen** [apollographql/apollo-client#7222]
Sometimes objects returned by GraphQL don't have unique IDs. Sometimes we just forget to fetch the id in the query. This has been source of countless issues and bugs. Sometimes data just disappears from Apollo Cache, sometimes data of one object is overwritten by another. This all is happening silently and quite randomly (e.g. depending on query/mutation server response order) so it's impossible to catch by common diagnostics and is only found by users on production.

**Intended outcome:**
Apollo should recognize situations where an object with a missing ID is being written in cache and throw a warning where this could result in undefined behaviour.

**Actual outcome:**
Apollo just overwrites cache data silently.

**Comment by benjamn** [comment]
@Elijen Are you using AC3? Have you seen the warnings we print about losing non-normalized data (#6372)? They are extremely detailed and link to the relevant documentation.

**Comment by Elijen** [comment]
@benjamn 3.0.0 release flew past me and there seem to be tons of changes. I'll check it out. Thanks
