### ISSUE TITLE
Pass context to useSubscription()

### ISSUE THREAD

**Issue by vendramini** [apollographql/apollo-client#7223]
Hey, guys.

I've some different links in my client and I decide which one to use based on some information passed on `context`. It's possible to pass `context` from `useQuery`, `useMutation` and `subscribeToMore`'s function returned by `useQuery`.

But when I try to pass `context` using `useSubscription` it doesn't works. Is this intentional?

Cheers!

**Versions**

```
  System:
    OS: Linux 5.0 Linux Mint 19.1 (Tessa)
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Browsers:
    Chrome: 86.0.4240.111
    Firefox: 82.0
  npmPackages:
    @apollo/client: ^3.2.5 => 3.2.5 
    apollo-upload-client: ^14.1.2 => 14.1.2 
    next-with-apollo: ^5.1.0 => 5.1.0 
```

**Comment by toxeus** [comment]
This has been fixed in https://github.com/apollographql/apollo-client/pull/7860 and can be closed.
