### ISSUE TITLE
TypeError: Cannot set property 'defaultOptions' of undefined

### ISSUE THREAD

**Issue by vncastanheira** [apollographql/apollo-client#7238]
**Intended outcome:**
Start apollo client.

**Actual outcome:**
![brave_KNmAFeF7nj](https://user-images.githubusercontent.com/1210284/97099465-20f0e480-1668-11eb-90e7-9597753cb55a.jpg)

**How to reproduce the issue:**
Used the sample cdode from this link: https://www.apollographql.com/docs/react/api/core/ApolloClient/#example-constructor-call
```
import { ApolloClient, InMemoryCache, createHttpLink } from '@apollo/client';
import App from './App'

// Instantiate required constructor fields
const cache = new InMemoryCache();
const link = createHttpLink({
  uri: 'http://localhost:5000/',
});
const defaultOptions = {
  watchQuery: {
    fetchPolicy: 'cache-and-network',
    errorPolicy: 'ignore',
  },
  query: {
    fetchPolicy: 'network-only',
    errorPolicy: 'all',
  },
  mutate: {
    errorPolicy: 'all',
  },
};


const client = new ApolloClient({
  // Provide required constructor fields
  cache: cache,
  link: link,

  // Provide some optional constructor fields
  name: 'react-web-client',
  version: '1.3',
  queryDeduplication: false,
  defaultOptions
});

export default (
    <ApolloClient client={client}>
        <App/>
    </ApolloClient>
)
```

**Versions**
  ### System:
    OS: Windows 10 10.0.17763
###   Binaries:
    Node: 14.14.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    Yarn: 1.22.5 - ~\scoop\apps\yarn\current\Yarn\bin\yarn.CMD
    npm: 6.14.8 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
    Browsers: {}
###   npmPackages:
    @apollo/client: ^3.2.5 => 3.2.5

**Comment by benjamn** [comment]
@vncastanheira I think you have a typo in your JSX. `ApolloProvider` is the component that provides the `client` instance through React context (not `ApolloClient`):
```jsx
export default (
    <ApolloProvider client={client}>
        <App/>
    </ApolloProvider>
)
```

**Comment by vncastanheira** [comment]
> @vncastanheira I think you have a typo in your JSX. `ApolloProvider` is the component that provides the `client` instance through React context (not `ApolloClient`):
> 
> ```js-jsx
> export default (
>     <ApolloProvider client={client}>
>         <App/>
>     </ApolloProvider>
> )
> ```

It's true, it was a typo!
I'm sorry for the mistake, the code is working now.

**Comment by jon617** [comment]
> > @vncastanheira I think you have a typo in your JSX. `ApolloProvider` is the component that provides the `client` instance through React context (not `ApolloClient`):
> > ```
> > export default (
> >     <ApolloProvider client={client}>
> >         <App/>
> >     </ApolloProvider>
> > )
> > ```
> 
> It's true, it was a typo! I'm sorry for the mistake, the code is working now.

Same just happened to me, this helped realize my typo.  `<ApolloProvider>` is the tag, `new ApolloClient()` is the function.  I too mistakenly had `<ApolloClient>`  (facepalm)
