### ISSUE TITLE
Can't capture the server json response even if i can see it in the Network tab

### ISSUE THREAD

**Issue by cmnstmntmn** [apollographql/apollo-client#7244]
Latest version of apollo-client `3.2.5`

i'm trying to run

```js
    apolloClient
      .mutate({
        mutation: SAVE_TICKET,
        variables: input,
      })
      .then((res) => {
         // all ok
      })
      .catch((err) => {
        // i expect to get the json response error 
      });
```

hoever i can't capture the server json response that is containing the error.
any ideea how i can achieve this.

ty.

**Comment by benjamn** [comment]
@cmnstmntmn If you pass `errorPolicy: "all"` to `client.mutate`, you'll get back a `{ data, errors }` result object with a non-empty `errors` array when there's an error. Is that the kind of solution you're looking for?

**Comment by cmnstmntmn** [comment]
yeah but this is not working :(

**Comment by cmnstmntmn** [comment]
```js    
apolloClient
      .mutate({
        mutation: SAVE_TICKET,
        variables: input,
        errorPolicy: "all",
      })
      .then((res) => {
        // -- whatever
      })
      .catch((error) => {
        console.log("====> error:", error);
```
<img width="947" alt="Screen Shot 2020-10-27 at 11 56 26 PM" src="https://user-images.githubusercontent.com/2312755/97366558-31939b80-18b0-11eb-9b74-b73701e7ad4d.png">

**Comment by cmnstmntmn** [comment]
server errors:

```json
{"errors":[{"message":"Ticket needs at least one Product Type quantity","path":["SaveTicket"],"extensions":{"field":"Status"}},{"message":"One or more invalid fields","path":["SaveTicket"]}],"data":null}
```

**Comment by cmnstmntmn** [comment]
seems it was "fixed" by archiving the repo https://github.com/apollographql/apollo-link/issues/1022 :(

**Comment by benjamn** [comment]
I meant that the error will be returned in `res.errors` in the `res` object passed to your `.then` callback when you use `errorPolicy: "all"`, so you can handle the error(s) as data.

On a more human note, is everything okay? Something about this issue, possibly my response, seems to have made you _angry_ at Apollo—like, beyond the point of productive frustration. There's no need for passive-aggressive PRs like #7245, or off-topic comments like https://github.com/apollographql/apollo-client/issues/7247#issuecomment-717592642. Could you possibly dial it down a bit, so we can get back to finding a good solution here? If you'd rather be angry, please take it somewhere else.

**Comment by cmnstmntmn** [comment]
@benjamn is not working. belive me i tried all responses from here and stackoverflow

```js
      .then((response) => {
        if (response.errors) {
          // do something with the errors
          console.log(response.errors);
        } else {
          // there wasn't an error
          console.log("successs");
        }
      })
      .catch((e) => {
        if (e.graphQLErrors) {
          console.log("--->", e.graphQLErrors);
        }
```
<img width="911" alt="Screen Shot 2020-10-28 at 12 52 39 PM" src="https://user-images.githubusercontent.com/2312755/97426687-7f45ed80-191c-11eb-8130-3946c9f1a23e.png">

**Comment by hwillson** [comment]
@cmnstmntmn There is a lot we can't see from your code snippets, that will greatly impact error reporting. Please provide a small runnable reproduction that clearly demonstrates the issue, and we'll take a further look. But please also note that while we've tried to be accommodating and help you through things, you have in turn opened multiple PR's labelling Apollo Client as not being production ready, and turned to Twitter to broadcast this. Open source communities thrive when members are respectful to each other, and we take our [Code of Conduct](https://github.com/apollographql/apollo/blob/master/CODE-OF-CONDUCT.md) very seriously. We're happy to help community members who are being respectful, so please keep this in mind during your follow up comments. And please try to keep your comments / complaints in this issue thread, so we can address them in one place. Sprinkling derogatory comments throughout various GitHub issues is not helpful.

**Comment by cmnstmntmn** [comment]
@hwillson please understand my frustration.
this lib is used by many, and there are vital issues (like this one), that are left unresolved/unanswered.

to me, it's important to say out-loud that things are not working (as part of Code of Conduct), for whatever the reason may be.

and to be honest .. have a look over [all these](https://github.com/apollographql/apollo-client/search?q=no+data+errors&type=issues) related issues regarding errors.

i'll try to came back with a playground

**Comment by hwillson** [comment]
@cmnstmntmn We definitely understand frustration, and we're trying to help. A reproduction would help with this greatly.

**Comment by cmnstmntmn** [comment]
@hwillson i can't reproduce it .. but as far as i see there are [many other issues addressing the same issue](https://github.com/apollographql/apollo-client/issues?q=server+errors)

**Comment by cmnstmntmn** [comment]
@hwillson i thing i found out what is causing this issue;
It relates to `@client` mutation response fields. I opened this [issue](https://github.com/apollographql/apollo-client/issues/7565)

**Comment by hwillson** [comment]
Closing as this is now being tracked in https://github.com/apollographql/apollo-client/issues/7565.

**Comment by kaykhancheckpoint** [comment]
I have a similar issue exept with .query, im unable to log the errors i see in the network tab
