### ISSUE TITLE
Cache not respecting key defined in @connection directive

### ISSUE THREAD

**Issue by emilnordh** [apollographql/apollo-client#7247]
**Intended outcome:**

We have two queries that include the same fields. We want the cache to treat the fields as the same even though they are requested with different arguments.

**Actual outcome:**

The two fields are cached with different keys because one field is requested without arguments. 

**How to reproduce the issue:**
Query 1
```graphql
query checkout($companyId: UUID!) {
  company(id: $companyId) {
    id
    # Using @connection without any field-arguments results in Apollo not respecting the cache key.
    plans @connection(key: "activeCompanyPlans") {
      id
    }
  }
}
```

Query 2
```graphql
query pollCheckout($companyId: UUID!, $planId: UUID!) {
  company(id: $companyId) {
    id
    plans(where: { id: { _eq: $planId } }) @connection(key: "activeCompanyPlans") {
      id
    }
  }
}
```

The second query correctly caches the field `plans` on `Company` with the storeFieldName: `plans:activeCompanyPlans` while the first query incorrectly caches with the key `plans`. It seems like the `key` argument sent to the `@connection` directive is not respected when there are no arguments.

One workaround is to change the first query to include field-arguments.
```graphql
query checkout($companyId: UUID!) {
  company(id: $companyId) {
    id
    plans(where: { id: { _is_null: false }  }) @connection(key: "activeCompanyPlans") {
      id
    }
  }
}
```

**Versions**
```
  System:
    OS: macOS 10.15.2
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Browsers:
    Chrome: 86.0.4240.111
    Edge: 86.0.622.51
    Safari: 13.0.4
  npmPackages:
    @apollo/client: ^3.2.5 => 3.2.5
    @apollo/react-testing: ^3.1.4 => 3.1.4
```

**Comment by emilnordh** [comment]
Fantastic @benjamn, thank you! Growing to like the new cache config API.

Out of curiosity is this the expected behaviour for the `@connect` directive?

**Comment by cmnstmntmn** [comment]
@emilnordh try to handle the server errors. 
you my need to switch from apollo to another lib, because apollo is not returning the errors.

you can catch but you can't read them, so is kind of useless if you ask me.

**Comment by hwillson** [comment]
Answered in https://github.com/apollographql/apollo-client/issues/7247#issuecomment-717359241 - thanks!
