### ISSUE TITLE
useQuery hook returns stale data on the _first_ rerender after cache.writeFragment and a mutation

### ISSUE THREAD

**Issue by akallem** [apollographql/apollo-client#7261]
**Intended outcome:**

Create a component using `useQuery` to fetch some objects (with the default `cache-first` fetch policy) and `useMutation` to update a single field on one object. Create a handler that calls `cache.writeFragment` to update an object in the cache, then invokes the mutation. Because the cache has been updated, I would expect in _all_ subsequent rerenders that `useQuery` would return `data` that reflects the cache update.

**Actual outcome:**

On the _first_ rerender, `useQuery` returns `data` that does not reflect the cache update, even though `cache.extract()` shows the update.

**How to reproduce the issue:**

Here's an example reproduction. See the commit message for details. https://github.com/akallem/react-apollo-error-template/commit/2b0951601a6523eb048452ad881bf35925c25ecd

This may be related to https://github.com/apollographql/apollo-client/issues/7067 and https://github.com/trojanowski/react-apollo-hooks/issues/175.

**Versions**

  System:
    OS: Linux 4.15 Ubuntu 16.04.7 LTS (Xenial Xerus)
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Browsers:
    Chrome: 86.0.4240.111
    Firefox: 81.0.2
  npmPackages:
    @apollo/client: ^3.2.5 => 3.2.5

**Comment by akallem** [comment]
@benjamn Just wanted to check if there's anything I can do to help move this issue along.

Also, I realize that the pattern I show in the bug reproduction is a bit contrived, in that a better approach for immediately updating the cache after changing a single object field would be to use optimisticResponse. But my intention was to isolate the bug as much as possible with a simple example.

My _actual_ use case involves other cache updates where optimisticResponse would not be sufficient.

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
