### ISSUE TITLE
@client objects are not testable/mockable, but their fields are

### ISSUE THREAD

**Issue by exapsy** [apollographql/apollo-client#7272]
**Intended outcome:**
Trying to mock-test `@client` queries. This is the query

```tsx
export const query = gql`
  query {
    dogBreed @client {
      name
    }
  }
`
const useDogBreed = () => useQuery(query)
```

And this is how I test it, I expect the test to be successful. 

```tsx
it("should return Shiba Inu with object as client", async () => {
  const DogBreed = () => {
    const { data, loading, error } = useDogBreed();
    if (loading) return <p>Loading</p>;
    if (error) return <p>{error.message}</p>;
    return <p>{`Dog breed: ${data?.dogBreed.name}`}</p>;
  };
  const data = { dogBreed: { name: "shiba inu" } };
  const mockedResponse = {
    request: { query },
    result: { data }
  };
  const component = TestRenderer.create(
    <MockedProvider mocks={[mockedResponse]} addTypename={false}>
      <DogBreed />
    </MockedProvider>
  );

  await waitForResponse();

  const expected = `Dog breed: ${data.dogBreed.name}`;
  const result = component.root.findByType("p").children[0];
  expect(result).toEqual(expected);
});
```

**Actual outcome:**
The test fails, but if you place the `@client` on the object's fields instead of the object itself, the test is successful.

```tsx
export const DOG_BREED = gql`
  query {
    dogBreed {
      name @client // Placed on the field
    }
  }
`;

```

Which re-assures me in some way that this shouldn't be the intended outcome and this is kinda a bug.

**How to reproduce the issue:**

Here's a codesandbox with 2 tests

https://codesandbox.io/s/divine-bush-k11vb

One which tests a query with `@client` on the object itself -- **fails**
And one with `@client` on the fields themselves -- **successful**

**Versions**

  System:
    OS: Linux 5.7 Manjaro Linux
  Binaries:
    Node: 14.13.1 - ~/.nvm/versions/node/v14.13.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.13.1/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.13.1/bin/npm
  Browsers:
    Firefox: 82.0.2
  npmPackages:
    @apollo/client: ^3.1.1 => 3.1.1 
    apollo-link-context: ^1.0.20 => 1.0.20 
    apollo-link-http: ^1.5.17 => 1.5.17

**Comment by donedgardo** [comment]
Check out the resolver property. https://github.com/apollographql/apollo-client/blob/version-2.6/docs/source/api/react-testing.md

**Comment by exapsy** [comment]
@donedgardo Many thanks! But the report is for the bug as this shouldn't normally happen, it should normally work right away when you put @client on the object like it does with the object's field, at least that's what the library's user would expect. 
I already have a workaround for this as demonstrated in the tests, since it works when you got @client on each field.

**Comment by hwillson** [comment]
@exapsy we're working on changes to our testing utilities, but for now this is working as designed. `MockedProvider` creates its own `ApolloClient` instance behind the scenes, which means it doesn't know about your `@client` based local resolvers unless you tell it about them. You can do this by passing your resolvers object into `MockedProvider` using the `resolvers` prop:

```js
<MockedProvider mocks={[mockedResponse]} addTypename={false} resolvers={yourResolvers}>
  ...
</MockedProvider>
```
