### ISSUE TITLE
[3.2.5][SSR][useQuery][@client directive]: loading is true and data is undefined even if the cache has been restored

### ISSUE THREAD

**Issue by nathanschwarz** [apollographql/apollo-client#7277]
The data sent by the server is correct.
The data is restored correctly, but the components are first showing in their loading state, then an update is triggered.

I've tried to set : 
- `fetchPolicy` to `cache-only`, `cache-first`, `cache-and-network`.
- `ssrForceFetchDelay` to different values (from 100ms to 10000ms).

**Intended outcome:**

The cache is restored, the query result should be : `loading: false, data: [CachedData]`

**Actual outcome:**

The cache is restored, the query result is : `loading: false, data: undefined`

**update**

After some inquiries, it seems that all queries including `@client` directives are affected.
I've tried to read the cache directly with `results.client.cache.readQuery({ query, variables })` and it throws a `missing fields` error on the fields marked as `@client`. Removing these fields in the query solved the issue.

Is this the desired outcome ?

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
