### ISSUE TITLE
fetchMore doesn't set networkStatus to NetworkStatus.fetchMore in apollo-client 3

### ISSUE THREAD

**Issue by Badbreaddead** [apollographql/apollo-client#7282]
Why fetchMore now sets networkStatus to `NetworkStatus.loading` not `NetworkStatus.fetchMore` as in apollo-client 2? Is it a bug or a feature?

**Comment by benjamn** [comment]
@Badbreaddead Have you tried passing [`notifyOnNetworkStatusChange: true`](https://www.apollographql.com/docs/react/data/queries/#inspecting-loading-states), either when configuring the original query (in the options passed to `client.watchQuery`, `client.query`, `useQuery`) or when calling `fetchMore`?

**Comment by Badbreaddead** [comment]
@benjamn yeah, sure. I pass it

**Comment by younes200** [comment]
same behavior, query's networkStatus never changed to `NetworkStatus.fetchMore` after a fetchMore call.

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
