### ISSUE TITLE
query gets replaced in the cache when calling the same query with different args

### ISSUE THREAD

**Issue by tafelito** [apollographql/apollo-client#7292]
**Intended outcome:**

I want to refetch a query that has been called multiple times but with different variables after a mutation 
So basically, I have a page where I query a list of items with some variables. Then I go to a different page and now I use the same query but with different variables. 

**Actual outcome:**
When I go to the apollo devtools, I can see both queries there, but the first one gets replaced with the most recent one. 
So later on, when I use a mutation and I try to refetch the query by it's name, it refetches only the most recent one   

I can't use the refetchQuery with the variables since at the moment I do the refetch, I don't have the original arguments that the query was called  

**Versions**
```
System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.183
    Safari: 14.0
  npmPackages:
    @apollo/client: 3.2.5 => 3.2.5 
    @apollo/link-context: ^2.0.0-beta.3 => 2.0.0-beta.3 
    @apollo/link-error: ^2.0.0-beta.3 => 2.0.0-beta.3 
    apollo-upload-client: ^14.1.2 => 14.1.2 
  npmGlobalPackages:
    apollo-codegen: 0.20.2
```

**Comment by azterizm** [comment]
I would suggest to create a global state (redux) that keeps record of those variables then call the query or you may store the responses for their respective pages. Problem is you are using only one query to do the job.

**Comment by tafelito** [comment]
why would I use a global state for this, specially redux, when the queries are already stored in AC? AC is the global state

**Comment by azterizm** [comment]
Redux will keep record of the queries. In this case, it can be an array that you push queries to after making a query. When you need the old query for mutation, get it from the Redux (by its name). 
This works for me because AC doesn't work this way, it replaces one query with one data that comes with the recent query. It doesn't give you access to the old query data.

**Comment by jgan42** [comment]
Hi,

Without any code it is hard to understand clearly your problem. You can take a look the [documentation](https://www.apollographql.com/docs/react/pagination/core-api/) for pagination (read it completely, it may solve your issue).

However, the "cache" situation for lists seems solved in this [medium article](https://medium.com/@martinseanhunt/how-to-invalidate-cached-data-in-apollo-and-handle-updating-paginated-queries-379e4b9e4698) posted by @martinseanhunt

Hope it helps.

**Comment by tafelito** [comment]
@jgan42 even tho that post is an old post, and since ac v3 a lot of things has changed, is still a good reference, but the issue I reported is not about how to update the cache. 

Updating the cache since v3 became easier but there are times that it can still be cumbersome or add a lot of boilerplate. For those use cases, you may want to use `refetchQueries`. 
`refetchQueries` as you may know, has 2 forms, a string based queries, or the obj type. 
When using the query as an obj, in order to refetch all queries, you have to know all the variables. as @azterizm mentioned, you could keep track of all the queries in some global state, using react vars if you wish. Now if you use refetchQueries passing the query as a string, AC will fetch all the queries with that name.

My issue is with the latest. 
Let's say you have a query named `listItems`. Now let's say you call that query 2 times, each time with different variables. Now when you use `refetchQueries(['listItems'])` you would expect  `listItems` to be called twice, one for each set of variables. And that's the issue I'm reporting. Only 1 request is made to the server instead of 2 using the latest variables.  

I understand if if this is not the intended way for AC to to work, but right now, having the option of passing a string variable it makes it to be confusing at the very least

I hope now is clear enough

**Comment by Findiglay** [comment]
@tafelito You could try calling the same query multiple times in refetchQueries, with the variables passed for each previous call. In order to do this, I would write the variables used in each query to apollo client state. Perhaps you could wrap it in `useEffect` like this:

```
useEffect(() => {
  const data = client.readQuery({
    query: gql`
      {
        myQueryVars @client
      }
    `
  })
  client.writeData({ myQueryVars: [...data?.myQueryVars, variables] })
}, [variables])
```

Then simply query `myQueryVars` alongside your mutation.

**Comment by tafelito** [comment]
thanks @Findiglay I know I can do that, but my whole point is why do I need to do that when AC already has all the queries. At least that was what I though by looking at the Apollo devtools, where you can see al the queries that has been executed. I guess that does not apply to AC.

**Comment by hwillson** [comment]
[Key arguments](https://www.apollographql.com/docs/react/caching/cache-field-behavior/#specifying-key-arguments) should help with this. Let us know if this is still a concern with `@apollo/client@latest` - thanks!

**Comment by tafelito** [comment]
@hwillson As far as I know, keyargs won't help in this case

**Comment by hwillson** [comment]
@tafelito any chance you can put together a small runnable reproduction that shows the issue?
