### ISSUE TITLE
networkError does not return statusCode

### ISSUE THREAD

**Issue by mazraara** [apollographql/apollo-client#7293]
I am trying to capture a 401 error but unfortunately, it seems like still not possible. I could not find any information about it in the doc as well

My implementation example looks like below

const errorLink = onError( ({ networkError }: ErrorResponse) => {
    if (networkError && 'statusCode' in networkError &&
        networkError.statusCode === 401
    ) {
        // perform logout stuff
    }
})

**Comment by devkot** [comment]
Hi @mazraara,

This is what I've used to get around that:

```
  const errorLink = onError((({ networkError }) => {
    if (networkError && (networkError as ServerError).statusCode === 401) {
      // Your logic here
    }
  }) as ErrorLink.ErrorHandler);
```

**Comment by devivekw** [comment]
> Hi @mazraara,
> 
> This is what I've used to get around that:
> 
> ```
>   const errorLink = onError((({ networkError }) => {
>     if (networkError && (networkError as ServerError).statusCode === 401) {
>       // Your logic here
>     }
>   }) as ErrorLink.ErrorHandler);
> ```

`networkError as ServerError`, I may be wrong. But I believe that `as` is an invalid syntax in TypeScript

**Comment by devivekw** [comment]
> Hi @mazraara,
> 
> This is what I've used to get around that:
> 
> ```
>   const errorLink = onError((({ networkError }) => {
>     if (networkError && (networkError as ServerError).statusCode === 401) {
>       // Your logic here
>     }
>   }) as ErrorLink.ErrorHandler);
> ```

Thanks @devkot , it worked as a charm. I am just wondering do you have any doc's I can refer to about the `as` syntax? 

Btw this confused me because the Apollo Docs on [Customizing response logic](https://www.apollographql.com/docs/react/networking/advanced-http-networking/#customizing-request-logic) don't talk about this in TypeScript.

**Comment by devkot** [comment]
@devivekw the `as` keyword is called a TypeScript Type Assertion which works like casting.
https://www.typescriptlang.org/docs/handbook/basic-types.html#type-assertions

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
