### ISSUE TITLE
query hooks not udated when the query evicted from ROOT_QUERY using broadcast:true

### ISSUE THREAD

**Issue by killjoy2013** [apollographql/apollo-client#7300]
**Intended outcome:**

My query is like below;
```
  const COUNTRIES = gql`
    query countries($arg: CountryFilterInput) {
      countries(filter: $arg) {
        code
        name
        emoji
      }
    }
`;
```
and the lazy query hook is;
```
  const [countriesLazy, { data, loading, error }] = useLazyQuery(COUNTRIES);
```

I'd like to clear the query result as below so that when `Query` button clicked, query is supposed to run again.
```
  cache.evict({
      id: "ROOT_QUERY",
      fieldName: 'countries({"filter":{"code":{"regex":""}}})',
      broadcast: true
  });
  cache.gc();
```

`broadcast: true` is used to update the relevant hooks AFAIK

**Actual outcome:**

I put a debbuger after `cache.gc();`  `__APOLLO_CLIENT__.cache.data` is cleared, `countries` query and its entities gone. So, cache evicted successfully. However if we check `__APOLLO_CLIENT__.cache.data`  after code finishes, `countries` query and the entities are back again. Apparently, broadcast is not happened and the  query hook is not updated by the evicted cache. 

**How to reproduce the issue:**

Here is the sandbox to reproduce [sandbox](https://codesandbox.io/s/apollo-client3-evict-query-result-qfrpr?file=/src/App.tsx)

```
 System:
    OS: Windows 10 10.0.14393
  Binaries:
    Node: 12.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (38.14393.2068.0)
  npmPackages:
    @apollo/client: ^3.2.5 => 3.2.5
```

**Comment by benjamn** [comment]
@killjoy2013 In your reproduction, the `countries` data comes back because a follow-up network request happens automatically (see the Network tab), due to the default `fetchPolicy` of `cache-first`. To me, this sounds like everything is working as you intended, unless I'm misunderstanding something.

As a side note, you can just use `fieldName: 'countries'`, passing `args` separately, instead of manually constructing the `storeFieldName` string:
```diff
diff --git a/src/App.tsx b/src/App.tsx
index 21144b5..5ddb1f3 100644
--- a/src/App.tsx
+++ b/src/App.tsx
@@ -42,8 +42,12 @@ export default function App() {
         <Button
           onClick={() => {
             cache.evict({
-              id: "ROOT_QUERY",
-              fieldName: 'countries({"filter":{"code":{"regex":""}}})',
+              // The id option can be omitted when you're modifying the
+              // ROOT_QUERY object, and it's simpler to pass args as a
+              // separate option, so you don't have to compute the
+              // storeFieldName string manually:
+              fieldName: "countries",
+              args: { filter: { code: { regex: "" } } },
               broadcast: true
             });
             cache.gc();
```
This change doesn't seem to affect the behavior of the code, to be clear. It's just easier to write.

**Comment by benjamn** [comment]
Ok, I see now that the component does not rerender after the second fetch, but that's because the results are identical to the previously rendered results.

If you sign up for a `loading: true` result using `notifyOnNetworkStatusChange: true`, then this `debugger` statement will be hit twice after eviction, because the previously rendered result is now the `loading: true` result (without data), so the final `loading: false` result (with data) is different from the previous result, so it needs to be rendered:
```diff
diff --git a/src/App.tsx b/src/App.tsx
index 5ddb1f3..fe5bb1e 100644
--- a/src/App.tsx
+++ b/src/App.tsx
@@ -21,7 +21,12 @@ type CountryType = {
 };
 
 export default function App() {
-  const [countriesLazy, { data, loading, error }] = useLazyQuery(COUNTRIES);
+  const [countriesLazy, { data, loading, error }] =
+    useLazyQuery(COUNTRIES, {
+      notifyOnNetworkStatusChange: true,
+    });
+
+  debugger;
 
   return (
     <div className="App">
```

**Comment by killjoy2013** [comment]
@benjamn purpose of the `cache-first` policy is to manage the query flow the way I'd like in this scenario. Mostly, reading data from the cache perfectly fine. 
However, I may need to clear the page, then query again from remote imperatively. To achieve this, cache eviction seemed a perfect way to go...  If some other policies are more suitable, I can try them gladly.
I tried `notifyOnNetworkStatusChange:true` as you suggested. You're right, component has been rendered twice due to this network status change. However, the resulting data is the same, loading displays then the query result is back.  `__APOLLO_CLIENT__.cache.data` is filled with data again. Nothing is evicted at that point...

**Comment by killjoy2013** [comment]
@benjamn purpose of the `cache-first` policy is to manage the query flow the way I'd like in this scenario. Mostly, reading data from the cache perfectly fine. 
However, I may need to clear the page, then query again from remote imperatively. To achieve this, cache eviction seemed a perfect way to go...  If some other policies are more suitable, I can try them gladly.
I tried `notifyOnNetworkStatusChange:true` as you suggested. You're right, component has been rendered twice due to this network status change. 
Now,  `useLazyQuery` queried the same data back again. I just need to clear the page when I hit `Clear`,  then query again hitting `Query`.

**Comment by killjoy2013** [comment]
Hey @benjamn looking forward to hear your suggestions to try.
Thanks in advance

**Comment by killjoy2013** [comment]
@benjamn let me put it like that, I just want to go back to a state when I did not yet run the query.

**Comment by killjoy2013** [comment]
@benjamn if we can create a flow like below, we can achieve our goal;
* our query hook is of `cache-first` originally. Change the fetch-policy temporarily and make it `cache-only` (can we do this? How?)
* do the cache evit, broadcast to notify the query hooks 
```
         cache.evict({
             fieldName: "countries",
             args: { filter: { code: { regex: "" } } },
             broadcast: true
          });
          cache.gc();
```
since we've changed the fetch-policy to `cache-only`, query hook won't get data from network.
* change the fetch-policy back to `cache-first` again
