### ISSUE TITLE
Help : InMemoryCache merge and read when using fetchMore, useLazyQuery and refetch

### ISSUE THREAD

**Issue by qmauret** [apollographql/apollo-client#7302]
**Context**
Hi, I'm pretty new to apollo. I started a new project and discovered that there is a great way to centralize pagination logic with caching configuration. I have a page which list training exercises, a "load more" button and a search input. The load more button should load next exercises (by fetchMore) and the search input should launch a new query (by useLazyQuery hook) and then replace the actual results with those found.

**My problem**
I managed to make the pagination work with cache configuration and a custom merge function. But I can't make the search work. I tried so many things, I think there is something i did not understand correctly, or maybe what i'm trying to do is not possible this way. That's why i need some help to explain me what is the best/proper way to handle that.

**Experiments**
If i use useLazyQuery hook with its default fetchPolicy nothing happens (no query is fired).
If i use useLazyQuery hook with network-only fetchPolicy, query is fired, i have my results but if i reset search i would like to use refetch function from my initial query to get initial results from cache. However, in this case refetch function does nothing (it did not fire an http request nor pass through cache merge function)

Here's some portion of my code, related to my problem : 

**Query**
```javascript
import { gql } from '@apollo/client';

const GET_EXERCISES = gql`
  query exercises($page: Int, $searchString: String, $orderBy: String, $orderWay: String) {
    exercises(page: $page, filters: { name: $searchString, orderBy: $orderBy, orderWay: $orderWay }) {
      nodes {
        id_exercise
        name
        is_active
        created_at
        created_by
      }
      total
      page
      has_next_page
    }
  }
`;
```

**App.js**
```javascript
const client = new ApolloClient({
  uri: process.env.REACT_APP_CMS_API_URL,
  cache: new InMemoryCache({
    typePolicies: {
      Query: {
        fields: {
          exercises: {
            keyArgs: false,
            merge(existing, incoming, { args }) {
              // this is to find if there is filters args in query, if so, return incoming results
              if (args.filters && Object.entries(args.filters).find(([key, value]) => value !== null && value !== undefined)) {
                return incoming;
              }
              if (!existing) {
                return incoming;
              }
              const existingNodes = existing.nodes || [];
              const incomingNodes = incoming.nodes || [];
              const nodes = [...existingNodes, ...incomingNodes];
              return { ...incoming, nodes };
            },
          },
        },
      },
    },
  }),
});
```

**Component**
```javascript
import { useQuery, useMutation, useLazyQuery } from '@apollo/client';
import React from 'react';
import exerciseService from '../../services/exercise.service';

...

const ExercisesPage = () => {
  const { loading, error, data, fetchMore, refetch } = useQuery(exerciseService.GET_EXERCISES);
  const [searchExercises, { data: searchResults }] = useLazyQuery(exerciseService.GET_EXERCISES, { fetchPolicy: 'network-only' });

  const handleLoadMore = () => {
    fetchMore({
      variables: {
        page: data.exercises.page + 1,
      },
    });
  };

  const handleSearch = searchString => {
    searchExercises({ variables: { searchString: `%${searchString}%` } });
  };

  const handleSearchReset = () => {
    refetch();
  };

  const exercisesList = () => {
    if (loading && !data) return <Loader />;
    if (error) return <p>Error...</p>;
    return (
      <>
        <ListSearch onSearch={searchString => handleSearch(searchString)} onSearchReset={() => handleSearchReset()} />
        <Grid>
          {data.exercises.nodes.map(exercise => (
            ...
          ))}
        </Grid>
        <ListProgression currentLength={data.exercises.nodes.length} max={data.exercises.total} />
        {data.exercises.has_next_page && <LoadMoreButton onLoadMore={() => handleLoadMore()} />}
      </>
    );
  };

  return (
    <>
      {exercisesList()}
    </>
  );
};
```

**Comment by qmauret** [comment]
I forgot to specify my environment. Here it is : 

**react** : 16.3.1
**@apollo/client** : 3.1.1
**node** : 12.18.3
**npm** : 6.14.6

**Comment by jgan42** [comment]
Hi,
I may try setting keyArgs with any variables which have no matters with pagination.

`keyArgs: ['searchString', 'orderBy', 'orderWay'];`

That way maybe you won't have to check "filters" in the merge function.

**Comment by qmauret** [comment]
Hi @jgan42 ,

Thank's, that solved my problem !  Ok i take note of your remark, i just thought here was the best place to get advises from apollo experts.
