### ISSUE TITLE
await useMutation resolves before the cache is updated

### ISSUE THREAD

**Issue by anark** [apollographql/apollo-client#7308]
When querying directly after updating an item via useMutation with await I expect the query to fetch the updated item directly from the cache

```
const UPDATE_TODO = gql`
  mutation updateTodo(id: $id, title: $title) {
    todo{
      id
      title
    }
  }
`

const GET_TODO = gql`
  query todo(id: $id) {
    todo{
      id
      title
    }
  }
`

const [loadTodo, {data}] = useLazyQuery(GET_TODO, {
  variables: { id: 1 }
})

const [handleChange] = useMutation(MY_MUTATION)
await handleChange({variables: {id: 1, title: 'new title'}})
loadTodo()
expect(data.todo.title).toBe('new title')
```
**Intended outcome:**

the query for todo fetched the todo and new title from the cache

**Actual outcome:**

The query is made before the cache updates and it fetches the data from the server again.  If you change the query to `fetchPolicy: 'cache-only'` it fetches the old title or nothing from the cache

**How to reproduce the issue:**

**Versions**

  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.10 - ~/Development/sky-pilot/node_modules/.bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Browsers:
    Chrome: 86.0.4240.183
    Firefox: 81.0
    Safari: 14.0
  npmPackages:
    @apollo/client: ^3.3.0-beta.8 => 3.3.0-rc.0
    @apollo/react-testing: ^4.0.0-beta.1 => 4.0.0

**Comment by jgan42** [comment]
Hi,

Maybe you can try cache.writeQuery

A very similar example is provided in the [sandbox](https://codesandbox.io/s/github/apollographql/react-apollo-error-template) you can find in the [new issue template](https://github.com/apollographql/apollo-client/issues/new?template=bug.md)

**Comment by anark** [comment]
There shouldn't be an need to use writeQuery as the graphql response includes the id and new title which does update the cache.  It just isn't updated until later.  I would expect the cache to be updated before the await resolves

**Comment by anark** [comment]
I've added a sandbox example you can view at https://codesandbox.io/s/hungry-cache-tci56

**Comment by anark** [comment]
Nevermind,
I was wrong.  I was expecting the query to get the cached reference object, forgetting that if the query had not yet been called it would not know which cached ref to resolve to.  This could probably be solved with a resolver but it is not an apollo issue.
