### ISSUE TITLE
Property 'setLink' is missing in type 'DefaultClient<InMemoryCache>' but required in type 'ApolloClient<any>'.

### ISSUE THREAD

**Issue by baeharam** [apollographql/apollo-client#7309]
When I make `client` using `ApolloClient` class, there was no error, but it causes error after updating packages.

- `ApolloClient` from `apollo-boost` (I have to use this, not from `@apollo/client`)
- `ApolloProvider` from `@apollo/client`

```typescript
import { ApolloProvider } from '@apollo/client';
import ApolloClient, { InMemoryCache } from 'apollo-boost';

const client = new ApolloClient<InMemoryCache>({
  uri: ...,
  cache: ...,
  request: (operation): void => {...},
});

const App = (): React.ReactElement => {
  return (
    // error is occurred at here
    <ApolloProvider client={client}>
      ...
    </ApolloProvider>
  );
}
```

**Intended outcome:**

NO ERROR

**Actual outcome:**

Type compatibility error!!

```
Property 'setLink' is missing in type 'DefaultClient<InMemoryCache>' but required in type 'ApolloClient<any>'.
```

**How to reproduce the issue:**

I think, it could be solved with above example code

**Versions**

- `@apollo/client` : ^3.2.5
- `apollo-boost` : ^0.4.9

**Comment by benjamn** [comment]
@baeharam The `apollo-boost` package was [removed](https://github.com/apollographql/apollo-client/pull/5217) in AC3, and is not intended to be used with `@apollo/client`.

**Comment by baeharam** [comment]
@benjamn Then how can I move `request` property to new `ApolloClient` from `@apollo/client`? This property isn't exist in `ApolloClient` of `@apollo/client`

**Comment by baeharam** [comment]
I used `header` property of new `ApolloClient` from `@apollo/client`.
