### ISSUE TITLE
<MockedProvider /> Infinite Render with UseSubscription and onSubscriptionData

### ISSUE THREAD

**Issue by Mathdrquinn** [apollographql/apollo-client#7313]
**Intended outcome:**
Intend to trigger one call of `onSubscriptionData` for a component utilizing a subscription to fetch via `useLazyQuery`.

**Actual outcome:**
An infinite loop of re-renders results in a test that never completes.

**How to reproduce the issue:**
Example project can be found [here](https://github.com/Mathdrquinn/apollo-sub-testing-bug).  Run `npm i` and `npm run test` to reproduce.

The basics of the code are:

```typescript
// component.tsx
import React from "react";
import { useLazyQuery, useSubscription } from "@apollo/client";
import { GET_USER } from "./queries";
import { SUBSCRIBE_TO_PURCHASE_UPDATES } from "./subscriptions";

type Purchase = { id: string; price: number };
type User = { id: string; purchases: Purchase[] };
type TheComponentProps = { user: User };

export const TheComponent = ({ user: propsUser }: TheComponentProps) => {
  const [user, setUser] = React.useState(propsUser);
  const userId = user.id;
  const [getUser, { data: latestUserData }] = useLazyQuery<{ user: User }>(
    GET_USER,
    {
      variables: { userId },
      fetchPolicy: "network-only",
    }
  );

  React.useEffect(() => {
    setUser(latestUserData?.user || propsUser);
  }, [latestUserData, propsUser]);

  const total = React.useMemo(() => {
    return user.purchases
      .map((p) => p.price)
      .reduce((runningTotal, price) => runningTotal + price, 0);
  }, [user]);

  useSubscription(SUBSCRIBE_TO_PURCHASE_UPDATES, {
    variables: { userId },
    shouldResubscribe: false,
    onSubscriptionData: async () => {
      getUser(); // N.B. if getUser() call is removed, tests run (though failing since query isn't fetched) 
    },
  });
  console.log("render");
  console.log(user);
  return <pre>total: ${total}</pre>;
};
```

```typescript
// component.test.tsx
import React from "react";
import { act } from "react-dom/test-utils";
import { MockedProvider } from "@apollo/client/testing";
import { mount, ReactWrapper } from "enzyme";
import { TheComponent } from "./component";
import { mockUserId, getUserMock, subscribetoUserMock } from "./mocks";

describe("thing", () => {
  const userId = mockUserId;
  const initialUser = { id: userId, purchases: [] };
  const mocks = [subscribetoUserMock.success.mock, getUserMock.success.mock];
  let wrapper: ReactWrapper;

  beforeAll(() => {
    wrapper = mount(
      <MockedProvider mocks={mocks} addTypename={false}>
        <TheComponent user={initialUser} />
      </MockedProvider>
    );
  });
  test("should not loop", () => {
    expect(wrapper.text()).toBe("total: $0");
  });

  describe("after a tick", () => {
    beforeAll(async () => {
      await act(async () => {
        await new Promise((res) => setTimeout(res, 0));
        wrapper.update();
      });
    });

    test("should show the updated purchase total", () => {
      expect(wrapper.text()).toBe("total: $1"); // <---------- never executes
    });
  });
});

```

**Versions**
System:
    OS: macOS 10.15.7
  Binaries:
    Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.2/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
  Browsers:
    Chrome: 86.0.4240.193
    Firefox: 79.0
    Safari: 14.0
  npmPackages:
    @apollo/client: ^3.2.5 => 3.2.5 
  npmGlobalPackages:
    apollo: 2.30.3

Let me know what other information I can provide to help.  I really appreciate all of the power of this library.

**Comment by Mathdrquinn** [comment]
@benjamn Is there any more information I can provide to help this along?

**Comment by selasdev** [comment]
I have a similar issue, the onSubscriptionData it's also triggering infinite renders on my tests.

**Comment by Mathdrquinn** [comment]
@benjamn and team, happy 2021!  New year, new issue?

**Comment by benjamn** [comment]
@Mathdrquinn Just tried out your reproduction and it does appear to show the problem, so I think we have enough info to take it from here.

On a personal note, I recently declared bankruptcy on my GitHub notifications in order to get them back under control, so thanks for the ping.

**Comment by Mathdrquinn** [comment]
Now worries @benjamn .  Thanks for the eyes.  Anything more I can do to help?

> I recently declared bankruptcy on my GitHub notifications

![bankruptcyuy](https://user-images.githubusercontent.com/6947446/105070370-072d2680-5a38-11eb-9fd7-fe1623333dea.gif)

**Comment by brainkim** [comment]
Should be fixed by #7917. Wasn’t able to get your tests to pass, but it doesn’t hang anymore. Ping me if you have questions or concerns :)

**Comment by Mathdrquinn** [comment]
> Wasn’t able to get your tests to pass

Thanks for taking a look!  I'll give it another run!

**Comment by brainkim** [comment]
@Mathdrquinn Should be shipped in the patch release for today (or tomorrow)! Feel free to reopen if there are still issues. I’m just trying to keep track of everything is all :heart:
