### ISSUE TITLE
Mutation results not updating after a subsequent cache write

### ISSUE THREAD

**Issue by knedev42** [apollographql/apollo-client#7316]
Let's say that we execute a mutation that creates a bunch of entities of type `A`. The `data` property of the `useMutation` hook contains an array of the created entities. The mutation result under `ROOT_MUTATION` looks like this
```
"create_entities_of_type_A(variables)": [{ __ref: "A:1" }, { __ref: "A:2" }, { __ref: "A:3" }, ...]
```
So we basically have an array of references to the entities that were returned by the mutation and they're available through the `data` property of the `useMutation` hook.

The problem I'm facing is that any subsequent mutation that updates any of the entities that we previously created, do not trigger an update and the `data` property of the `useMutation` hook represents the old value of the entity, even though the cache has been successfully updated (i.e. a subsequent mutation `update_entity_of_type_A` that updates entity "A:1" successfully and updates the cache, doesn't re-render, so the `useMutation` hook still returns the old state of entity "A:1"). I'm not using `broadcast: false` when the subsequent cache update occurs and it works properly in other scenarios that modify the same data, but it has been retrieved with `useQuery` instead (for example in views that display already existing entities, based on some criteria and allows edits on them).

A concrete use-case: I have a workflow that allows users to create a bunch of things at once and after they're created, they're presented with a view that shows them the stuff that was created. In that same view, they also have the option to further modify these things (in case they made a mistake they want to amend or forgot to do something during the initial creation process). So basically the data for that view is the result of the mutation and users can further modify each entity through subsequent mutations.

**Intended outcome:**

A cache update should trigger a re-render of the `useMutation` hook, if one of the references returned by the `useMutation` hook is updated.

**Actual outcome:**

The `useMutation` hook returns the old data (doesn't update) when a cache update modifies an entity it returns.

**Versions**

npmPackages:
@apollo/client: ^3.1.3 => 3.1.3

**Comment by benjamn** [comment]
@knedev42 Mutations don't automatically re-run the way queries do, though their results are written into the cache (as you observed), where they can be read by queries. Maybe you could set up a `useQuery` that queries the data returned by the mutation, and display those results instead?

Since you can't read directly from the `ROOT_MUTATION` object using `useQuery`, you could perhaps create root query field that reads from the `ROOT_MUTATION` object:
```ts
new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        query_entities_of_type_A(_, { readField, toReference, variables }) {
          return readField({
            fieldName: "create_entities_of_type_A",
            from: toReference("ROOT_MUTATION"),
            variables,
          }) || []; // Always return at least an empty list.
        },
      },
    },
  },
})
```
Then this query
```ts
const ENTITIES_QUERY = gql`
  query EntitiesQuery ($var: type, ...) {
    query_entities_of_type_A(arg: $var, ...) @client {
      # ...fields...
    }
  }
`; 
```
should become usable as follows:
```ts
useQuery(ENTITIES_QUERY, {
  variables: { var: value, ... },
  // Never go to the network for this query.
  fetchPolicy: "cache-only",
});
```
I don't love this workaround at all, but it should work. Let me know if you hit any snags!

**Comment by knedev42** [comment]
Hmm, yeah I also thought of that workaround, but I'm not really a fan of it, so I'm not going to use it. Instead I'll probably end up with manual state management in this case 🤷‍♂️ 

I'm not sure what's the reasoning behind the mutations not getting notified of cache updates, so that they can supply the new `data` prop? It seems very counter intuitive and kinda makes the `data` prop of the `useMutation` hook pointless, because you can't rely on it being up-to-date with the cache. The use case above is basically the only one I've ever had a need for the `data` prop of the `useMutation` hook, out of dozens (close to a hundred) other mutations. I really wonder what's the point of the mutation hook even exposing the data to components if it's not going to be reliably kept in sync with the cache?

**Comment by knedev42** [comment]
@benjamn, please let me know if I should close this, if the current behavior is indeed the desired one and nothing will be done in the future to change it. Thank you for your time!
