### ISSUE TITLE
NPM 7 Failure When adding Apollo Persisted Queries (NPM 6 and yarn work)

### ISSUE THREAD

**Issue by pkellner** [apollographql/apollo-client#7317]
# Bug report

## Describe the bug

When trying to install Apollo Presisted Queries in the with-apollo example in the nextjs repo, npm install fails and yarn works.  This does not fail when building with create-react-app.  When I back down from the latest graphql to 14.4.2, node works again.

Issue posted in NextJS first, closed by @timneutkens
https://github.com/vercel/next.js/issues/19060

## To Reproduce

Repo Location: https://github.com/vercel/next.js/tree/canary/examples/with-apollo

1. copy with-apollo example from nextjs repo
2. npm install
3. npm install apollo-link-persisted-queries

Get Error below (yarn works with no error).  See apollo example page:

https://www.apollographql.com/docs/apollo-server/performance/apq/

```
 with-apollo % npm install apollo-link-persisted-queries
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: with-apollo@1.0.0
npm ERR! Found: graphql@15.4.0
npm ERR! node_modules/graphql
npm ERR!   graphql@"^15.3.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0" from apollo-link-persisted-queries@0.2.2
npm ERR! node_modules/apollo-link-persisted-queries
npm ERR!   apollo-link-persisted-queries@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/peterkellneradmin/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/peterkellneradmin/.npm/_logs/2020-11-11T15_18_10_976Z-debug.log

```

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
