### ISSUE TITLE
apollo-client require `react` ??

### ISSUE THREAD

**Issue by yaquawa** [apollographql/apollo-client#7318]
I got this error when compiling with WebPack 5.
I'm using vue, does this mean the apollo-client require `react` as a dependency?

```
 error  in ./node_modules/@apollo/client/react/context/ApolloConsumer.js

Module not found: Error: Can't resolve 'react' in '/Users/x/node_modules/@apollo/client/react/context'

 error  in ./node_modules/@apollo/client/react/hooks/useApolloClient.js

Module not found: Error: Can't resolve 'react' in '/Users/x/node_modules/@apollo/client/react/hooks'

 error  in ./node_modules/@apollo/client/react/hooks/utils/useBaseQuery.js

Module not found: Error: Can't resolve 'react' in '/Users/x/node_modules/@apollo/client/react/hooks/utils'
```

**Comment by baruchvlz** [comment]
It's a [peer dependency](https://github.com/apollographql/apollo-client/blob/main/package.json#L61).

**Comment by skourismanolis** [comment]
@yaquawa did you find a way to fix this without adding react as an (unnecessary) dependency?

**Comment by yaquawa** [comment]
@skourismanolis No, it requires react even if you don't need it...

**Comment by baruchvlz** [comment]
Have you tried using [VueApollo](https://apollo.vuejs.org/) ?

**Comment by yaquawa** [comment]
@baruchvlz I'm using it now. it require apollo-client.

**Comment by victorgarciaesgi** [comment]
Is there a way to remove react from the dependencies if we are not using it?

**Comment by skourismanolis** [comment]
@victorgarciaesgi I suppose you could fork the repo and remove the dependency from package.json but that's now a good long-term solution

What really must happen is since the `apollo-client` package is not supposed to be react-specific, any such functionality should be moved to a new package as a breaking change of a major update. But that's up to the apollo team and how they want to handle it.

**Comment by yaquawa** [comment]
This takes extra 298 kB if you don't use react. which is nonsense for non-react users.

**Comment by victorgarciaesgi** [comment]
@yaquawa I completly agree. I use Vue and I just updated to v3 and I want to switch back. Even for Node users this is nonsense

**Comment by cmd-johnson** [comment]
I just stumbled across that same problem, but I got the client to work without having to install react as well.
Just import everything you need from `@apollo/client/core` instead of `@apollo/client` and you'll be good to go.

**Comment by victorgarciaesgi** [comment]
@cmd-johnson I followed the [docs](https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/#using-apollo-client-without-react) here and imported everything from `@apollo/client/core` too and I still got the `missing react` error.

```ts
import { ApolloClient, InMemoryCache, ApolloLink } from '@apollo/client/core';
import { setContext } from '@apollo/client/link/context';
import apolloLogger from 'apollo-link-logger';
import { onError } from '@apollo/client/link/error';
import { createUploadLink } from 'apollo-upload-client';
```

Is there something i'm missing?

**Comment by victorgarciaesgi** [comment]
Ok I found it. For anyone having this issue the error comes from `apollo-link-logger` which required the entire `@apollo/client`

```js
// node_modules/apollo-link-logger/es/index.js
var _client = require('@apollo/client');
```

I will open a PR

**Comment by yaquawa** [comment]
@victorgarciaesgi Thanks that helps!

**Comment by ryrych** [comment]
These changes made it run:

```
-import ApolloClient from 'apollo-client'
-import { ApolloLink, concat } from 'apollo-link'
-import { HttpLink } from 'apollo-link-http'
-import { split } from 'apollo-link'
-import { onError } from 'apollo-link-error'
-import { InMemoryCache, defaultDataIdFromObject } from 'apollo-cache-inmemory'
+import { ApolloClient } from '@apollo/client/core'
+import { ApolloLink, HttpLink, split, concat } from '@apollo/client/core'
+import { onError } from '@apollo/client/link/error'
+import { InMemoryCache, defaultDataIdFromObject } from '@apollo/client/cache'
```

-import gql from "graphql-tag"
+import { gql } from "@apollo/client/core"
```

_package.json_

```
-"apollo-boost": "^0.4.9",
-"apollo-cache-inmemory": "^1.6.6",
-"apollo-client": "^2.6.10",
-"apollo-link": "^1.2.14",
-"apollo-link-context": "^1.0.20",
-"apollo-link-http": "^1.5.17",
-"apollo-link-ws": "^1.0.20",
-"apollo-utilities": "^1.3.4",
-"graphql": "^15.3.0",
-"graphql-tag": "^2.11.0",
+"@apollo/client": "^3.3.2",
+"graphql": "^15.4.0",
```

**Comment by Yohandah** [comment]
I'm having this issue as well using @apollo/client in my Angular project. 

Importing from @apollo/client/core fixes the problem but I'm unsure why ... I think Apollo shouldn't rely on react ....

**Comment by GustavoFenilli** [comment]
The problem is that @apollo/client exports from ./react and ./core.

It makes sense if the package is react friendly and as bonus works for other frameworks, but if the package intentions are to be framework free, it should only export from ./core and make react users import from @apollo/client/react instead.

**Comment by GustavoFenilli** [comment]
> The problem is that @apollo/client exports from ./react and ./core.
> 
> It makes sense if the package is react friendly and as bonus works for other frameworks, but if the package intentions are to be framework free, it should only export from ./core and make react users import from @apollo/client/react instead.

After trying to find how to run a query and mutation using the docs, I found out that everything is based on react, so probably this package is meant to be used only with react, and as bonus it works for other frameworks too.

Sadly the docs are lacking on how to use the ApolloClient without using react hooks, also lacking in how to use the package without react at all ( where you get that you need to use @apollo/client/core is in the migration from 2.x, that makes no sense ).

So I would suggest to improve the documentation a little bit with a section on how to use this package without react and also on how to use queries, mutations and so on ( doesn't need to be focused on frontend frameworks, just on which method to use and its properties ).

**Comment by hwillson** [comment]
Apollo Client 4 is going to remove React from the default `@apollo/client` entry point. We're tracking this here: https://github.com/apollographql/apollo-client/issues/8190 - thanks!
