### ISSUE TITLE
Restore API does not retain ROOT_QUERY, ROOT_MUTATION

### ISSUE THREAD

**Issue by danReynolds** [apollographql/apollo-client#7323]
**Intended outcome:**

Calling `cache.gc()` after the cache is restored using a tool like https://github.com/apollographql/apollo-cache-persist should not remove all entities in the cache and only remove unreachable entities.

**Actual outcome:**

Calling `cache.gc()` after the cache is restored using a tool like https://github.com/apollographql/apollo-cache-persist removes all entities in the cache.

**Explanation**

It looks like this happens because when you call `cache.restore(data)` as defined here: https://github.com/apollographql/apollo-client/blob/master/src/cache/inmemory/inMemoryCache.ts#L99

and subsequently call EntityStore replace: https://github.com/apollographql/apollo-client/blob/master/src/cache/inmemory/entityStore.ts#L238

it hydrates the cache, but never calls `retain` on any ID. Normally, the `ROOT_QUERY` is retained by a write to the store: https://github.com/apollographql/apollo-client/blob/master/src/cache/inmemory/writeToStore.ts#L114:L114

but if nothing has been written to the store yet, and `gc` is called immediately after a `cache.restore` using a tool like cache-persist, then there are no `rootIds` retained and the entire cache will get garbage collected.

I think the solution would be to either:

1. Default the rootIds to include `ROOT_QUERY` and `ROOT_MUTATION` on cache instantiation so that they are not lazily retained on a call to `writeToStore` but assumed to be desired to be retained by default
2. Retain `ROOT_QUERY` and `ROOT_MUTATION` if a call to `cache.restore` includes those keys at the time restore is called
3. Have downstream tools like cache-persist know that after doing a restore, they will need to retain IDs they care about like `ROOT_QUERY` and `ROOT_MUTATION`. I think this is a riskier approach, because as a user I would assume that ROOT_QUERY should be retained by default based on the documentation of `cache.gc()`:

<img width="664" alt="Screen Shot 2020-11-13 at 11 26 21 AM" src="https://user-images.githubusercontent.com/2192930/99095386-10ff5d00-25a3-11eb-92ee-32f36ec35446.png">

I think `rootIds` is not a familiar term to most folks in these docs and they'd assume that unreachable would mean that there are things like dangling normalized entities, not potentially the ROOT_QUERY itself.

Let me know what your thoughts are, thanks!

**Comment by benjamn** [comment]
@danReynolds Thanks for flagging this serious problem! I've released a partial fix (#7333) in `@apollo/client@3.2.6`, with a more complete fix coming soon in v3.3 (#7334). The full fix seemed a little too risky for a patch release, but the v3.3 release is coming any day now. Please let me know if you have any questions or feedback on either part of this solution.

**Comment by loteoo** [comment]
Is this still an issue in 3.3.0 ? An app I'm working on has an empty SSR initial cache (`client.cache.extract()` ) when upgrading from 3.2.5 to any more recent version. We're sticking to 3.2.5 for now, I think there are still issues related to this in 3.3.0.

**Comment by benjamn** [comment]
@loteoo Are you saying SSR sends down non-empty data that you restore with `client.cache.restore(data)`, but `client.cache.extract()` later gives you an empty object, or do you mean SSR isn't generating any data?

**Comment by loteoo** [comment]
@benjamn I think SSR isn't generating data? Or maybe that data can't be extracted via `client.cache.extract()` anymore 🤔 . Sorry I'm not sure, but here's an example with more details:

```
let state = null;
try {
    await getDataFromTree(
        <ApolloProvider client={client}>
            <App {...props} />
        </ApolloProvider>
    );
    state = client.cache.extract();
} catch (error) {
    console.error('Error while running `getDataFromTree`', error);
}

console.log(state);
// In 3.2.5, state is populated with data from queries
// In 3.2.6 and above, it's an empty object

```

Sorry if I'm not sure which is the culprit here (`cache.gc()` or `client.cache.extract()` or something else ) 🙏 .

I am fairly certain it has to do with `@apollo/client@3.2.6` and above tho 🤔 .

**Comment by benjamn** [comment]
@loteoo If you're not calling `cache.gc()` in that code, this issue (#7323) probably isn't the cause of your problems, but getting an empty object is definitely strange/worrisome!

A couple more questions:
1. Are you importing `getDataFromTree` from `@apollo/client/react/ssr`?
2. Are you importing `ApolloProvider` from `@apollo/client` (or `@apollo/client/react/context`)?

The older `@apollo/react-*` packages should no longer be used.

**Comment by loteoo** [comment]
@benjamn You're a genius, I was indeed importing `getDataFromTree` from `@apollo/react-ssr`. I switched the import to `'@apollo/client/react/ssr` and it's working properly with `3.3.0`.

Thanks so much and sorry for the distraction!
