### ISSUE TITLE
<Query /> Watch Returns Older Version of Optimisitic Data

### ISSUE THREAD

**Issue by dairyisscary** [apollographql/apollo-client#7329]
**Intended outcome:**
Bear with me, I'll do my best to explain the strange observed behavior. I'm attempting to upgrade a 2.x to 3.x codebase and ran into what i believe is a bug with optimistic data. Essentially I have some code that basically does the following:

- I have a `<Query />` component at the root of the page watching some cache data, using inmemorycache.
- I make a standard mutation call, with an optimistic response. This modifies the cache once for the optimistic response and once for the real server response. This cache update is done through mutation's `update(cacheProxy)` function using a standard pair of `cacheProxy.readQuery`/`cacheProxy.writeQuery` calls.
- At some later time, I do a cache write via a `client.cache.readQuery`/`client.cache.writeQuery` _without a mutation_. This cache update is done in response to a socket event I receive without some associated mutation. At this point everything in the UI seems correct; the `<Query />` is pushing me up to date data from all the cache modifications thus far.
- I make another standard mutation, same as the one above with an optimistic response and a standard `update(cacheProxy)`/`cacheProxy.readQuery`/`cacheProxy.writeQuery`. However, when this transaction is outstanding the UI and the `<Query />` seem to missing the cache modifications from the `writeQuery` I did in response to the socket event. Eventually the real server response comes back and the transaction commits and then `<Query />` gets the expected data from all three cache modifications. To be clear, its appears only the second `writeQuery`, the one that occurred without a mutation and without a transaction is not observed, and _only_ while the final mutation is outstanding and I am subscribed to the optimistic version of the data.

I did some debugging by shoving some console.logs/debuggers into apollo client source. i noticed that the writeQuery that occurs without a transaction/mutation just goes through `inmemorycache.write()` and seems to _only_ modify `inmemorycache.data` and _not_ `inmemorycache.optimisticData`. Just for fun and testing my hypothosis, I added a line like this at the bottom of `write()` around https://github.com/apollographql/apollo-client/blob/main/src/cache/inmemory/inMemoryCache.ts#L133

```ts
        finally {
            if (!--this.txCount && options.broadcast !== false)  {
                this.optimisticData = this.data; // <-- added this line
                this.broadcastWatches();
            }
       }
```

This made my bug go away, so i suspect that `this.optimisticData` is just not written when doing non-standard cache write. I, of course, have no idea if this change is appropriate in general but it did (I think) confirm my suspicions about stale optimistic data. In other words, it appears my cache modification in the socket event only changed the "real" data, not the optimistic copy too.

Hopefully this is enough information to reproduce the bug.

**Versions**
@apollo/client version 3.2.5

**Comment by KennyHammerlund** [comment]
I have something similar. I don't want to hijack your post but it may be related. 

In my case I have 2 mutation that modify a single field on a type we can call `cart`;  `addEggs` & `addButter`
so the `cart` type  looks like `{ eggs: 0, butter: 0 }` and the mutations add to that. Both mutations use Optimistic UI

If I call `addEggs` 3 times the field increments on screen and then call `addButter` twice  the butter will increment to 2 like it should. Somewhere along the line one of the mutations will return (most likely `addEggs`) and set butter to 1 in the optimistic cache and then when something else returns it will go back to 2.

this 1 value is not represented in the update function in the data response when this "flashback" happens . I have to log out the `cache.extract(true)[id]` on the display component to see it.  

I have not found a root in the source but it feels like the above case where a transaction is missed writing what should be the correct optimistic value.

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
