### ISSUE TITLE
Error: Cannot use e "__Schema" from another module or realm. After updated to version 3.2.5

### ISSUE THREAD

**Issue by alesak** [apollographql/apollo-client#7331]
We are experiencing this issue after recent update to 3.2.5 (3.2.4 works fine) and only if result JS code is minified. Non minified code works OK.

Error: Cannot use e "__Schema" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.

**Comment by benjamn** [comment]
@alesak Can you share a [reproduction](https://github.com/apollographql/react-apollo-error-template) that includes any relevant dependencies and/or devDependencies from your `package.json`?

Also, any Apollo-related dependencies should have package names that start with `@apollo/` rather than `apollo-`, assuming you're using AC3.

**Comment by mkaraula** [comment]
We are experiencing the same Issue. I'll omit some of the packages for brevity: 

```json
"dependencies": {
    "@apollo/client": "^3.2.3",
    "graphql": "^15.4.0",
    "react": "^16.13.1",
    "react-dom": "^16.12.0",
  },
  "devDependencies": {
    "@graphql-codegen/add": "^1.12.1",
    "@graphql-codegen/cli": "^1.12.1",
    "@graphql-codegen/introspection": "1.12.1",
    "@graphql-codegen/near-operation-file-preset": "^1.12.1",
    "@graphql-codegen/typescript": "1.12.1",
    "@graphql-codegen/typescript-operations": "1.12.1",
    "@graphql-codegen/typescript-react-apollo": "1.12.1",
    "@types/react": "^16.9.2",
    "@types/react-dom": "^16.8.4",
    "parcel-bundler": "^1.12.4",
    "typescript": "^3.9.2"
  }
```

**Comment by IsaaX** [comment]
I ran into this issue as well and spent a lot of time trying to figure it out with no avail. I did most of the standard suggestions when looking for a solution.

Ended up with disabling mangle to get this issue to work. 
```
minifierConfig: {
      mangle: {
        keep_classnames: true, 
        keep_fnames: true, 
      },
    },
```

**Comment by hwillson** [comment]
We'll need a runnable reproduction (using `@apollo/client@latest`) to be able to troubleshoot this further. Thanks!
