### ISSUE TITLE
v3.2.6 is a breaking change

### ISSUE THREAD

**Issue by moon-chilled** [apollographql/apollo-client#7335]
I think perhaps it was accidentally tagged from the main branch?

In any case, it depends on a newer version of @types/node than the old version (14 instead of 12), which breaks code that was depending on 12.

**Comment by benjamn** [comment]
@moon-chilled Thanks for flagging this, but the `@types/node` package is a dev dependency of `@apollo/client`. Can you explain why your application/framework would care about the version of a dev dependency of one of its dependencies? Doesn't that seem a bit strange to you?

**Comment by Yohandah** [comment]
I have this issue as well lost a lot of time this morning. Downgrading to 3.2.5 works.

**Comment by benjamn** [comment]
Closing in favor of #7337, which appears to be the same issue.

**Comment by benjamn** [comment]
This should now be fixed in `@apollo/client@3.2.7`: https://github.com/apollographql/apollo-client/issues/7337#issuecomment-729000224
