### ISSUE TITLE
Context link is not capturing reactive var changes 

### ISSUE THREAD

**Issue by sergio-bravo** [apollographql/apollo-client#7338]
I created a language link:

```javascript
const languageLink = setContext((request, previousContext) => ({
  ...previousContext,
  headers: {
    ...previousContext.headers,
    "Accept-Language": getLanguage(),
  },
}));
```

```javascript
export const getLanguage = (defaultLanguage?: string): string => {
  return languageVar() || defaultLanguage || "en";
};
```
It basically works and I can see the header is added to the request.

Problem: I expect cached queries to update automatically because the context has changed, but the new queries do not fire.

**Comment by hwillson** [comment]
Addressed by https://github.com/apollographql/apollo-client/pull/7350 - thanks!
