### ISSUE TITLE
Facing migration issue with apollo-client@2.6.8 to @apollo/client@3.2.7

### ISSUE THREAD

**Issue by sami-cipher** [apollographql/apollo-client#7343]
**Intended outcome:**

it could be run as of migration guide said.

**Actual outcome:**

I don't get is that have peer dependancy with `apollo-client`. I followed migration steps from official documentation

```
ERROR in /node_modules/@apollo/react-common/lib/context/ApolloConsumer.d.ts(2,26):
TS2307: Cannot find module 'apollo-client'.
ERROR in /node_modules/@apollo/react-common/lib/context/ApolloContext.d.ts(2,26):
TS2307: Cannot find module 'apollo-client'.
ERROR in /node_modules/@apollo/react-common/lib/context/ApolloProvider.d.ts(2,26):
TS2307: Cannot find module 'apollo-client'.
ERROR in /node_modules/@apollo/react-common/lib/types/types.d.ts(1,221):
TS2307: Cannot find module 'apollo-client'.
ERROR in /node_modules/@apollo/react-hoc/lib/types.d.ts(1,147):
TS2307: Cannot find module 'apollo-client'.
ERROR in /node_modules/@apollo/react-hooks/lib/data/OperationData.d.ts(1,30):
TS2307: Cannot find module 'apollo-client'.
ERROR in /node_modules/@apollo/react-hooks/lib/data/QueryData.d.ts(1,35):
TS2307: Cannot find module 'apollo-client'.
ERROR in /node_modules/@apollo/react-hooks/lib/ssr/RenderPromises.d.ts(2,33):
TS2307: Cannot find module 'apollo-client'.
ERROR in /node_modules/@apollo/react-hooks/lib/types.d.ts(3,60):
TS2307: Cannot find module 'apollo-client'.
ERROR in /node_modules/@apollo/react-hooks/lib/useApolloClient.d.ts(1,26):
TS2307: Cannot find module 'apollo-client'.
ERROR in /node_modules/@apollo/react-hooks/lib/useSubscription.d.ts(8,20):
TS2307: Cannot find module 'apollo-client'.
ERROR in /node_modules/@apollo/client/core/ObservableQuery.d.ts(22,9):
TS1086: An accessor cannot be declared in an ambient context.
```

**How to reproduce the issue:**

while I migrated from apollo-client@2.6.8 to @apollo/client@3.2.7

**Versions**

  System:
    OS: macOS 10.15.6
  Binaries:
    Node: 12.7.0 - ~/.nvm/versions/node/v12.7.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.7.0/bin/npm
  Browsers:
    Chrome: 86.0.4240.198
    Safari: 14.0

**Comment by benjamn** [comment]
@sami-cipher Instead of importing from `@apollo/react-hooks`, you should now be importing from `@apollo/client/react/hooks` (or directly from `@apollo/client`, for imports like `useQuery`).

I believe this was covered in the migration guide [here](https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/#updating-imports), but before you go to the trouble of migrating those imports manually, I would recommend running our [codemod](https://github.com/apollographql/apollo-client/tree/main/codemods/ac2-to-ac3) for converting imports from AC2 to AC3. It's not perfect, so definitely check the results, but it's a good way to catch any imports you might have forgotten to migrate, in addition to speeding up an otherwise manual process.

**Comment by sami-cipher** [comment]
yes @benjamn

 following packages I've removed completely. and all the modules I have imported from `@apollo/client` itself.
```
"@apollo/react-hooks": "^3.1.3",
"apollo-boost": "^0.4.7",
"apollo-cache-inmemory": "^1.6.5",
"apollo-client": "^2.6.8",
"apollo-link-http": "^1.5.16",
"graphql-tag": "^2.10.1",
```
and `react-apollo` package also I wish to remove. but unfortunately `getDataFromTree` modules is not available on `@apollo/client`

I have imported manually only from migration guide. while I tried CODEMOD I faced some error
```
~> npx jscodeshift \
   -t apollo-client/codemods/ac2-to-ac3/imports.js \
   --extensions tsx --parser tsx \
   source-directory
ERROR Transform file /***/monorepo/packages/***/apollo-client/codemods/ac2-to-ac3/imports.js does not exist 
```
FI: we using monorepo, and the I've followed same migration steps for other monorepo's packages also

and then manually ive removed all the node_modules, yet it doesn't helped

is that any peer dependancy issue..?

**Comment by benjamn** [comment]
For `getDataFromTree`, you can do
```ts
import { getDataFromTree } from "@apollo/client/react/ssr"
```
As for the `jscodeshift` error, you need to temporarily clone [this repository](https://github.com/apollographql/apollo-client) into the directory where you're running the `npx jscodeshift` command, or clone it somewhere else and adjust the path to refer to that directory. The [`README.md`](https://github.com/apollographql/apollo-client/tree/main/codemods/ac2-to-ac3#running-the-transform) for the codemod covers this step ("Note that the `apollo-client` directory…").

**Comment by sami-cipher** [comment]
thanks @benjamn after removing `react-apollo`, we reduced error.

but not completely. following error still there


```
✔ success client compiled in 1m 19s 319ms
ERROR in /monorepo/node_modules/@apollo/client/core/ObservableQuery.d.ts(22,9):
TS1086: An accessor cannot be declared in an ambient context.
ERROR in /monorepo/node_modules/@apollo/client/node_modules/ts-invariant/lib/invariant.d.ts(7,79):
TS2304: Cannot find name 'asserts'.
ERROR in /monorepo/node_modules/@apollo/client/node_modules/ts-invariant/lib/invariant.d.ts(7,87):
TS2304: Cannot find name 'condition'.
No lint errors found
Version: typescript 3.5.1, tslint 5.20.1
Time: 79249ms
✔ success server compiled in 1m 18s 637ms

/monorepo/packages/portal/build/server.js:2021
/*! exports provided: default */function(e,t,n){"use strict";n.r(t),t.default=function(e,t){if(e instanceof t)return!0;if(e){var n=e.constructor,r=t.name;if(r&&n&&n.name===r)throw new Error("Cannot use ".concat(r,' "').concat(e,'" from another module or realm.\n\nEnsure that there is only one instance of "graphql" in the node_modules\ndirectory. If different versions of "graphql" are the dependencies of other\nrelied on modules, use "resolutions" to ensure only one version is installed.\n\nhttps://yarnpkg.com/en/docs/selective-version-resolutions\n\nDuplicate "graphql" modules cannot be used at the same time since different\nversions may have different capabilities and behavior. The data from one\nversion used in the function from another could produce confusing and\nspurious results.'))}return!1}},"../../node_modules/graphql/jsutils/invariant.mjs":
                                                                                                                                                                                    ^
Cannot use e "__Schema" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
```

FI: other package from monorepo we used some packages for Apollo server. I believe its not the reason for the broke.
please have a look on the packages what we used
```
"dependencies": {
    "@graphql-codegen/cli": "^1.7.0",
    "@graphql-codegen/introspection": "^1.7.0",
    "@graphql-codegen/typescript": "^1.7.0",
    "@graphql-codegen/typescript-resolvers": "^1.7.0",
    "apollo-server-cache-redis": "^1.1.6",
    "apollo-server-express": "^2.13.1",
    "apollo-server-plugin-response-cache": "^0.4.1",
    "graphql": "^14.3.1",
    "graphql-tools": "^4.0.5",
    "graphql-type-json": "^0.3.0",
    "merge-graphql-schemas": "^1.5.8"
}
```
note: I have listed apollo and graphQL packages only.

**Comment by mkaraula** [comment]
I guess its related to https://github.com/apollographql/apollo-client/issues/7331

**Comment by sami-cipher** [comment]
yes I agree @mkaraula . but asserts and condition issue is seems to be a new.

**Comment by sami-cipher** [comment]
> thanks @benjamn after removing `react-apollo`, and using
> 
> ```
> import { getDataFromTree } from "@apollo/client/react/ssr"
> ```
> 
> we reduced error. but not completely. following error still there
> 
> ```
> ✔ success client compiled in 1m 19s 319ms
> ERROR in /monorepo/node_modules/@apollo/client/core/ObservableQuery.d.ts(22,9):
> TS1086: An accessor cannot be declared in an ambient context.
> ERROR in /monorepo/node_modules/@apollo/client/node_modules/ts-invariant/lib/invariant.d.ts(7,79):
> TS2304: Cannot find name 'asserts'.
> ERROR in /monorepo/node_modules/@apollo/client/node_modules/ts-invariant/lib/invariant.d.ts(7,87):
> TS2304: Cannot find name 'condition'.
> No lint errors found
> Version: typescript 3.5.1, tslint 5.20.1
> Time: 79249ms
> ✔ success server compiled in 1m 18s 637ms
> 
> /monorepo/packages/portal/build/server.js:2021
> /*! exports provided: default */function(e,t,n){"use strict";n.r(t),t.default=function(e,t){if(e instanceof t)return!0;if(e){var n=e.constructor,r=t.name;if(r&&n&&n.name===r)throw new Error("Cannot use ".concat(r,' "').concat(e,'" from another module or realm.\n\nEnsure that there is only one instance of "graphql" in the node_modules\ndirectory. If different versions of "graphql" are the dependencies of other\nrelied on modules, use "resolutions" to ensure only one version is installed.\n\nhttps://yarnpkg.com/en/docs/selective-version-resolutions\n\nDuplicate "graphql" modules cannot be used at the same time since different\nversions may have different capabilities and behavior. The data from one\nversion used in the function from another could produce confusing and\nspurious results.'))}return!1}},"../../node_modules/graphql/jsutils/invariant.mjs":
>                                                                                                                                                                                     ^
> Cannot use e "__Schema" from another module or realm.
> 
> Ensure that there is only one instance of "graphql" in the node_modules
> directory. If different versions of "graphql" are the dependencies of other
> relied on modules, use "resolutions" to ensure only one version is installed.
> 
> https://yarnpkg.com/en/docs/selective-version-resolutions
> 
> Duplicate "graphql" modules cannot be used at the same time since different
> versions may have different capabilities and behavior. The data from one
> version used in the function from another could produce confusing and
> spurious results.
> ```
> 
> FI: other package from monorepo we used some packages for Apollo server. I believe its not the reason for the broke.
> please have a look on the packages what we used
> 
> ```
> "dependencies": {
>     "@graphql-codegen/cli": "^1.7.0",
>     "@graphql-codegen/introspection": "^1.7.0",
>     "@graphql-codegen/typescript": "^1.7.0",
>     "@graphql-codegen/typescript-resolvers": "^1.7.0",
>     "apollo-server-cache-redis": "^1.1.6",
>     "apollo-server-express": "^2.13.1",
>     "apollo-server-plugin-response-cache": "^0.4.1",
>     "graphql": "^14.3.1",
>     "graphql-tools": "^4.0.5",
>     "graphql-type-json": "^0.3.0",
>     "merge-graphql-schemas": "^1.5.8"
> }
> ```
> 
> note: I have listed apollo and graphQL related packages only.

hi @benjamn , can I get any help to resolve this

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
