### ISSUE TITLE
How can I change `offset` field name into `start` when using offsetLimitPagination()?

### ISSUE THREAD

**Issue by darron1217** [apollographql/apollo-client#7344]
How can I change `offset` field name into `start` when using offsetLimitPagination()?

**Comment by benjamn** [comment]
@darron1217 Don't overthink it! Those [helpers](https://github.com/apollographql/apollo-client/blob/f93673c452e94074627fbaa893c1bf4d5fd6ffce/src/utilities/policies/pagination.ts#L24-L51) are just examples, intended for inspiration as much as for direct usage. You should feel free to copy/paste the code and modify it to suit your needs. The current implementation doesn't allow you to reconfigure the `offset` argument name, but you can change it to anything you want in your own copy of the code.

**Comment by darron1217** [comment]
@benjamn I found that helper is really simple code.
I modified it and resolved issue 👍 
Thank you!
