### ISSUE TITLE
addTypename set to true does not add __typename to root selection set

### ISSUE THREAD

**Issue by dminkovsky** [apollographql/apollo-client#7363]
**Intended outcome:**

I am using `InMemoryCache` with `addTypename` set to `true` (the default). I expected `__typename` to be added to all selection sets in my query, including the root selection set.

**Actual outcome:**

`__typename` is added to all selection sets, but **not** the root object.

Because of this, the store defaults to "Query" as __typename for the root query object. My root query object is actually called "query_root", and thus my type policy field settings for that object are not found during cache reads, even though I set `queryType: true` on the "query_root" definition.

Adding `__typename` explicitly to the root selection set of my queries works around this issue, but doesn't it make sense for it to be added automatically when addTypenames is enabled?

**How to reproduce the issue:**

Create a client with an InMemoryCache that has `addTypename` set to `true`. Observe that `__typename` is not added to root selection sets.

**Versions**

@apollo/client@3.3.0-rc.0

  System:
    OS: macOS 10.15.4
  Binaries:
    Node: 15.1.0 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/dev/pony/src/front/node_modules/.bin/yarn
    npm: 7.0.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.198
    Firefox: 81.0
    Safari: 13.1

**Comment by dminkovsky** [comment]
Looks like this is intentional:

https://github.com/apollographql/apollo-client/blob/114b91643a77f49f3aa1ff151cc8a9920e8c8422/src/utilities/graphql/transform.ts#L212-L222

But why?

As mentioned above, if `__typename` is not fetched, but query type is not "Query", then field type policies for root fields are not found.

**Comment by benjamn** [comment]
@dminkovsky The `queryType: true` configuration is supposed to make this work, so I agree there must be a bug if you're ending up with `__typename: "Query"` even when using `queryType: true` for your `query_root` type.

The problem with adding `__typename` to the root query selection set is not just that it's unnecessary extra information in most cases, but that we sometimes need to know the `__typename` of the root query object before the first cache write happens. The `queryRoot: true` configuration avoids that problem by specifying the root `__typename` statically (without waiting for any dynamic data).

**Comment by dminkovsky** [comment]
Ah thanks @benjamn. 

> if you're ending up with `__typename: "Query"` even when using `queryType: true` for your `query_root` type.

Yep, just double checked and that's the case. `query_root` btw is the default query type name used by Hasura. I would offer to write a failing testing, and I tried, but I wasn't sure where it would go.

Thanks for explaining the reason. Yes, that makes sense.

**Comment by benjamn** [comment]
@dminkovsky Here's an existing test of `queryType: true`, for inspiration: https://github.com/apollographql/apollo-client/blob/main/src/cache/inmemory/__tests__/policies.ts#L4361

**Comment by dminkovsky** [comment]
Thank you @benjamn. I search the codebase and somehow missed that.

Time is suddenly not on my side, but I will keep this in mind. Should be a fun exercise. Thanks again.

**Comment by benjamn** [comment]
@dminkovsky The problem with `queryType: true` may be fixed by #7463, coming soon in `@apollo/client@3.3.6`, jfyi.

**Comment by dminkovsky** [comment]
Thanks a lot Ben I will check it out.

пт, 11 дек. 2020 г. в 5:14 PM, Ben Newman <notifications@github.com>:

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
