### ISSUE TITLE
pageInfo custom properties are not merged when using relayStylePagination

### ISSUE THREAD

**Issue by IcanDivideBy0** [apollographql/apollo-client#7367]
**Intended outcome:**
When using `relayStylePagination`, adding a `count` field to `pageInfo`, then updating the cache with `writeFragment`, the incoming count property should update the pageInfo

**Actual outcome:**
Existing count property is kept. I strongly suspect [this part of the code](https://github.com/apollographql/apollo-client/blob/e8567a2b85fb05acb10940aa23b25811a03a7bf4/src/utilities/policies/pagination.ts#L201-L209)

**How to reproduce the issue:**
```js
new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        articles: relayStylePagination(),
      },
    },
  },
})

// Not sure this example would really works as is, but you get the idea:
// updating `pageInfo.count` when a new article is created
client.writeFragment({
  id: "articles",
  fragment: gql`
    fragment on Query {
      articles {
        pageInfo {
          count
        }
      }
    }
  `,
  data: {
    articles: {
      pageInfo: {
        count: 100
      }
    }
  },
});
```

**Versions**
```
  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.66
    Firefox: 78.4.1esr
  npmPackages:
    @apollo/client: ^3.2.7 => 3.2.7 
```

**Comment by IcanDivideBy0** [comment]
Using this in place of `relayStylePagination` works as expected
```js

function relayStylePaginationWithCount(keys) {
  const base = relayStylePagination(keys);

  return {
    ...base,
    merge(existing, incoming, ...rest) {
      // return base.merge(existing, incoming);
      const result = base.merge(existing, incoming, ...rest);
      result.pageInfo.count = incoming.pageInfo.count;
      return result;
    },
  };
}
```

**Comment by benjamn** [comment]
@IcanDivideBy0 Is `incoming.pageInfo.count` supposed to be a total count, or just the size of the current page? If it's a total count, most implementations would put that information in the connection object (alongside `edges` and/or `pageInfo`), rather than putting it in the `PageInfo` object.

**Comment by benjamn** [comment]
What do you think of https://github.com/apollographql/apollo-client/pull/7369?

**Comment by IcanDivideBy0** [comment]
@benjamn yes, it's supposed to be total count. I didn't even thought of putting the count property at the connection level, I'll change that on my server.
Anyways, #7369 definitely solves this, thanks!
