### ISSUE TITLE
Latest version(3.3.0) not tagged latest on NPM

### ISSUE THREAD

**Issue by klarstrup** [apollographql/apollo-client#7374]
I'm guessing this was a mishap publishing the 3.2.9 patch after publishing 3.3.0

![image](https://user-images.githubusercontent.com/1567633/100244336-195a7f00-2f37-11eb-884e-f211ef6c65fe.png)

**Comment by benjamn** [comment]
@klarstrup This was intentional! Just finishing some internal testing before opening the floodgates. As you might guess from the immediate v3.1.1 release, that testing has been productive. 😬

**Comment by klarstrup** [comment]
Haha well then 😂
