### ISSUE TITLE
Apollo server cache not updating when you update a field resolver

### ISSUE THREAD

**Issue by Pixelatex** [apollographql/apollo-client#7377]
**Intended outcome:**
When I update a field resolver, it should clear those related entries from the cache.
**Actual outcome:**
If you have a field 'books' on 'author' that returns all books with the parentId that is the same as the one from author and you add a book. Then the cached response for author will still return the same books as before. You need to wait for the cache to invalidate before you see a result.

**How to reproduce the issue:**
Cache the response for a schema that uses field resolvers, update these field resolvers separately and see that the cache remains.

**Versions**
```
 System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
  Browsers:
    Chrome: 86.0.4240.198
    Safari: 14.0
  npmPackages:
    apollo-datasource-rest: ^0.9.0 => 0.9.4 
    apollo-server: ^2.5.0 => 2.18.1 
    apollo-server-cache-memcached: ^0.6.6 => 0.6.6 
    apollo-server-cache-redis: ^1.2.2 => 1.2.2 
    apollo-server-plugin-response-cache: ^0.5.6 => 0.5.6 
```

**Comment by benjamn** [comment]
@Pixelatex How does Apollo Client fit into this scenario? Apollo Server issues can be filed over at https://github.com/apollographql/apollo-server, if that's what you intended.

**Comment by Pixelatex** [comment]
Apologies, this was indeed not meant for client!
