### ISSUE TITLE
[3.3.1] Observable  '@@observable' field is not set in SSR

### ISSUE THREAD

**Issue by Luminqi** [apollographql/apollo-client#7381]
In SSR, '@@observable' is not set correctly. This cause rxjs report error. I am not sure what happens. But I can not see corresponding code  in utilities.cjs.js.

The version of @apollo/client is 3.3.1

**Comment by benjamn** [comment]
@Luminqi I believe we will switch to RxJS at some point before Apollo Client 4 (see #5749 for some initial work), which would fix problems like this in a general way, but it looks like `zen-observable` does try to set `Symbol.observable` [here](https://github.com/zenparsing/zen-observable/blob/328fb66a99242900c0fd4a330e9ff66ecfa3a887/src/Observable.js#L396), so I'm curious if you have any insights about why that's not working?

**Comment by Luminqi** [comment]
@benjamn The problem is that `rxjs` does not polyfill [Symbol.observable](https://github.com/ReactiveX/rxjs/pull/3387) anymore. And as you mentioned, `zen-observable` polyfill it. So the behavior of program depends on which package loads first. And in my case, rxjs loads first, so its inner identifier for Observable becomes a string `@@observalbe`. So the mismatch of identifier cause this bug. 

I sovled this by polyfill `Symbol.observable` at the vey beginning of app.
