### ISSUE TITLE
Optimistic updates not working for mutations with nested models even when id and __typename are present

### ISSUE THREAD

**Issue by CaptainChemist** [apollographql/apollo-client#7391]
**Intended outcome:**
I expect that when I run an optimistic update that has nested models, I should be able to update both the parent and the child model at the same time. This happens with the "update" functionality perfectly.

**Actual outcome:**

The outcome that I see is that when I run a "create mutation", I initially get the optimistic update for the parent item "feed" but my nested "feedTag" item initially renders blank until the update function gets called once I get the data back. In this video below you'll be able to see that the data I'm writing using `writeQuery` is the same both for the optimistic and the update stage of the process.

[Here is a video showing the behavior](https://imgur.com/a/s5vx3tG). 

Note that my nested items have both an `id` and a `__typename` so that shouldn't be the problem here. Here are some code snippets I'm using, I have a function `genUpdates` that I use for `createUpdate` function and it gets called both during the update and the optimistic update step:

```
const genUpdates = (store, item, isFeed) => {
  const id = _.get(item, 'id');
  try {
    const { feeds, bundles } = store.readQuery({ query: isFeed ? FEEDS_QUERY : BUNDLES_QUERY });
    const currentItems = isFeed ? feeds : bundles;
    const currentItem = currentItems.filter(o => o.id !== item.id)[0] || {};

    if (id) {
      console.log('about to write a feed/bundle query update');
      console.log({
        query: isFeed ? FEED_QUERY : BUNDLE_QUERY,
        variables: { data: { id } },
        data: { [isFeed ? 'feed' : 'bundle']: { ...currentItem, ...item } },
      });
      const result = store.writeQuery({
        query: isFeed ? FEED_QUERY : BUNDLE_QUERY,
        variables: { data: { id } },
        data: { [isFeed ? 'feed' : 'bundle']: { ...currentItem, ...item } },
      });
      console.log(result);
    }
  } catch (e) {
    console.log('An error occurred');
    console.log(e);
  }

  try {
    const { feeds, bundles } = store.readQuery({ query: isFeed ? FEEDS_QUERY : BUNDLES_QUERY });
    const currentItems = isFeed ? feeds : bundles;
    if (id) {
      console.log('about to write feeds/bundles query update');
      console.log({
        query: isFeed ? FEEDS_QUERY : BUNDLES_QUERY,
        variables: {},
        data: { [isFeed ? 'feeds' : 'bundles']: [...currentItems.filter(o => o.id !== item.id), item] },
      });
      const result = store.writeQuery({
        query: isFeed ? FEEDS_QUERY : BUNDLES_QUERY,
        variables: {},
        data: { [isFeed ? 'feeds' : 'bundles']: [...currentItems.filter(o => o.id !== item.id), item] },
      });
      console.log(result);
    }
  } catch (e) {
    console.log('An error occurred');
    console.log(e);
  }
};

export const createUpdate = isFeed => (store, { data: { createFeed, createBundle } }) => {
  const item = isFeed ? createFeed : createBundle;
  genUpdates(store, item, isFeed);
};
```

Here is what the optimistic create function looks like:
```
export const optimisticCreate = (isFeed, data, currentItem, meData) => {
  const { id } = data;
  const __typename = isFeed ? 'Feed' : 'Bundle';
  const { me } = meData;

  const response = {
    id,
    ...currentItem,
    likes: [],
    [isFeed ? 'bundles' : 'feeds']: [],
    tags: [
      ...currentItem.tags.filter(tag => _.has(tag, 'id')),
      ...data.tags.create.map(tag => ({
        __typeName: isFeed ? 'FeedTag' : 'BundleTag',
        ...tag,
      })),
    ],
    ...(isFeed
      ? {}
      : {
          feeds: currentItem.feeds,
        }),
    author: me,
  };

  return {
    __typename: 'Mutation',
    ['create' + __typename]: {
      __typename,
      ...response,
    },
  };
};
```

How I call the mutation is:

```
  const [createItemMutation, { loading: createLoading, error: createError }] = useMutation(
    isFeed ? CREATE_FEED_MUTATION : CREATE_BUNDLE_MUTATION
  );
createItemMutation({
                variables: { data },
                optimisticResponse: optimisticCreate(isFeed, data, currentItem, meData),
                update: createUpdate(isFeed),
              });
```

My graphQL mutations have all the pieces split into fragments to streamline the return:

```
export const FEED_TAG_FRAGMENT = gql`
  fragment FeedTagFragment on FeedTag {
    id
    name
  }
`;

export const BUNDLE_TAG_FRAGMENT = gql`
  fragment BundleTagFragment on BundleTag {
    id
    name
  }
`;

export const AUTHOR_FRAGMENT = gql`
  fragment AuthorFragment on User {
    id
    auth0
    picture
    nickname
  }
`;

export const LIKE_FRAGMENT = gql`
  fragment LikeFragment on Like {
    id
    name
  }
`;

export const FEED_FRAGMENT = gql`
  fragment FeedFragment on Feed {
    id
    name
    url
    likes {
      ...AuthorFragment
    }
    tags {
      ...FeedTagFragment
    }
    author {
      ...AuthorFragment
    }
  }
  ${FEED_TAG_FRAGMENT}
  ${AUTHOR_FRAGMENT}
`;

export const BUNDLE_FRAGMENT = gql`
  fragment BundleFragment on Bundle {
    id
    name
    description
    tags {
      ...BundleTagFragment
    }
    author {
      ...AuthorFragment
    }
    likes {
      ...AuthorFragment
    }
  }
  ${BUNDLE_TAG_FRAGMENT}
  ${AUTHOR_FRAGMENT}
`;

export const CREATE_FEED_MUTATION = gql`
  mutation createFeedMutation($data: FeedCreateInput) {
    createFeed(data: $data) {
      ...FeedFragment
      bundles {
        ...BundleFragment
        feeds {
          ...FeedFragment
        }
      }
    }
  }
  ${FEED_FRAGMENT}
  ${BUNDLE_FRAGMENT}
`;
```

**How to reproduce the issue:**

Here is a link to the repo that is giving me problems:
https://github.com/CaptainChemist/prisma-2-rss-tracker/tree/apollo-optimistic

Check out the `components/newEditItem.tsx`component and then the corresponding `utils/optimisticResponse.ts` and `utils/update.ts` files.

To reproduce locally there are a few steps- you'd have to create a `.env` where you create an auth0 account and have a postgres database. Message me and I'm happy to provide a test set of .envs to use but I'm hesitant to post them online.
```
DATABASE_URL=postgresql://user:password@database.us-east-1.rds.amazonaws.com:5432/database-name
AUTH0_CLIENTID=yyy
AUTH0_DOMAIN=yyy.auth0.com
AUTH0_CLIENT_SECRET=yyy
AUTH0_SCOPE='openid profile'
AUTH0_COOKIE_SECRET='super-long-secret-cookie-super-long-secret-cookie'
BACKEND_ADDRESS=http://localhost:3000
```
Then run `npm install`, `npm run generate`, `npm run migrate:save`, `npm run migrate:up`. 

Thanks so much for looking into this- I apologize that this is not a minimal example but reach out if you have any troubles setting it up and I'm happy to help.

**Versions**

  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v10.15.3/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 87.0.4280.67
    Firefox: 72.0.1
    Safari: 14.0
  npmPackages:
    @apollo/client: ^3.3.0 => 3.3.1 
    apollo-server-micro: ^2.18.2 => 2.18.2

**Comment by benjamn** [comment]
@CaptainChemist Though I think I was able to set up most of the requirements for your local reproduction, I got stuck on the Auth0 integration, since the callback URL seems like it has to be HTTPS, and I'm not sure how to make this application serve HTTPS from `localhost:3000`. If you want to email me an example `.env` file, feel free to use ben@eloper.dev (my public GitHub email address).

Without a running reproduction, I can only guess what the problem might be, but this code looks a little :suspect: to me:
```ts
  useEffect(() => {
    (async () => {
      if (item && selected.editMode) {
        const { __typename, likes, author, ...cleanedItem } = item;
        setItem({ ...cleanedItem });
      } else {
        setItem(initialState);
      }
    })();
  }, [itemQueryData]);
```
The destructuring line seems to be the only place in the `NewEditItem` component where the `item` variable is consumed, which is important because `item` is the `data` from the `useQuery(isFeed ? FEED_QUERY : BUNDLE_QUERY)` result. By my reading of the code, `selected.editMode` is `false` by default, so `item` is never passed to `setItem`, so the `currentItem` state never gets updated with actual `item` data (only `initialState`). Since `currentItem` is what ultimately gets rendered, it seems like you need to find a way to call `setItem` with data from the query? Maybe try removing the `&& selected.editMode` part of the `if` condition?

**Comment by CaptainChemist** [comment]
@benjamn - thanks so much for responding. I emailed you last night with a sample env so hopefully, that helps things on your end. 

I appreciate you flagging a piece of code that you find suspect. To test this, I just commented that block out entirely because it is only used for resetting the field contents if someone switches from creating a new item to editing an existing item, so it is not needed for the purposes of this test. I unfortunately still get the same behavior.

To address the concern of yours a different way, I tried a test to verify that this is a problem at the Apollo cache level:
1) I tried putting chrome into low end mobile mode to simulate a slow internet speed. 
2) I then used the Apollo plugin for chrome to look at the state of the cache. It's initially empty before I press submit.
3) I press submit and a new Feed is immediately created and cached.
4) The FeedTag item in the cache *only* shows up after several seconds which is when the update step comes. 

This means that the FeedTag is not getting created in the cache until the update happens even though my update function gets called twice once for the optimistic and once for the update _and_ critically the structure of both the simulated mutation and the actual mutation response match which you can tell based on the console.log on line 13 in `utils/update.ts` file.

**Comment by CaptainChemist** [comment]
I'm still struggling with this issue. The craziest thing of it all is that the optimistic object and the update object match except it appears in the console.log that the order of the keys are not exactly the same. Does apollo-client are about ordering at all of keys within an object? 

Could that be why from a cache standpoint I'm not seeing it get written to until the update step?

**Comment by CaptainChemist** [comment]
Ooh I got it! The problem was that one of my optimistic updates had a key of `__typeName` instead of `__typename`. I think what prolonged identifying the issue was that I had two optimistic updates (feed(id) and feeds queries) happening with a single mutation and it appears that neither one updated the cache when the second one had the error. In any case, I hope this helps someone- details matter! :) Thanks so much for the assistance @benjamn!
