### ISSUE TITLE
notifyOnNetworkStatusChange makes query infinite reload

### ISSUE THREAD

**Issue by Nolat** [apollographql/apollo-client#7397]
**Intended outcome:**
I query a list of categories to display.
So I get data, loading, networkStatus & refetch.
I also switch to notifyOnNetworkStatusChange option for a better display (ex: an ActivityIndicator when loading and networkStatus is not a refetch).

So I expect to recover to display an ActivityIndicator, then to display a FlatList containing my data (when loading is false).

Then I can refetch my query with the onRefresh function of the FlatList.

**Actual outcome:**
In practice, when notifyOnNetworkStatusChange is set to true, the query is restarted infinitely. 

![IMG_0603](https://user-images.githubusercontent.com/22156783/100724419-25c15a80-33c3-11eb-83f2-19badf4d7d48.GIF)

And there is no issue when I enable the production mode of Expo. Might be linked to fast-refresh.
I've searched in some open issues about fast-refresh in @apollo/client^3 but I've not found any the talk about notifyOnNetworkStatusChange.

**Code**
```typescript
const { data, loading, networkStatus, refetch } = useCategoriesQuery({
    fetchPolicy: "network-only",
    notifyOnNetworkStatusChange: true
  });
```

(I'm using @graphql-codegen to generate my hooks)

```typescript
export function useCategoriesQuery(
  baseOptions?: Apollo.QueryHookOptions<
    CategoriesQuery,
    CategoriesQueryVariables
  >
) {
  return Apollo.useQuery<CategoriesQuery, CategoriesQueryVariables>(
    CategoriesDocument,
    baseOptions
  );
}
```
**Versions**
```
System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0)
  npmPackages:
    @apollo/client: ^3.2.9 => 3.2.9
    expo: ~39.0.2
```

**Comment by benjamn** [comment]
@Nolat Are there any other queries in your app that request the same fields as `CategoriesDocument`?

**Comment by Nolat** [comment]
@benjamn No, it's the only place where it's used.

**Comment by Nolat** [comment]
@benjamn After some other tests, on other query, I've found that it's not the only query reloading infinitely.

This one is not even using notifyOnNetworkStatus.
```typescript
const { data, loading } = useMeQuery();
console.log({ data, loading });
```

Which is giving me this logs in console :
```
Object {
  "data": undefined,
  "loading": true,
}
Object {
  "data": undefined,
  "loading": false,
}
Object {
  "data": undefined,
  "loading": false,
}
Object {
  "data": undefined,
  "loading": false,
}
Object {
  "data": undefined,
  "loading": false,
}
Object {
  "data": undefined,
  "loading": false,
}
Object {
  "data": undefined,
  "loading": false,
}
Object {
  "data": undefined,
  "loading": false,
}
Object {
  "data": undefined,
  "loading": false,
}
```

And it only does that in development mode in Expo.

**Comment by Nolat** [comment]
@benjamn I'm closing this issue. After some more test, I've found that it was coming from a component wrapping my application, that was reseting the cache everytime.

So just my mistake 😅
