### ISSUE TITLE
nextFetchPolicy with SSR

### ISSUE THREAD

**Issue by Godsenal** [apollographql/apollo-client#7398]
Hi. I'm trying to delete item from list by `cache.evict`.

Because my list query uses 'network-only' as fetchPolicy, i set 'cache-first' as nextFetchPolicy to prevent list query refetching whole query on network. (#6746, i followed comment on this issue)

It works well when list query called on client side, but when list query called on SSR mode, it still refetching list query on network.

If i evict item again after refetching, it works well. It looks like nextFetchPolicy doesn't check SSR request.

In [nextFetchPolicy document](https://www.apollographql.com/docs/react/api/react/hooks/),
> Optional FetchPolicy to begin enforcing after the current request. Useful for switching back to cache-first after cache-and-network or network-only.

But it looks like `nextFetchPolicy` doesn't care about request in SSR mode.

**Intended outcome:**

`nextFetchPolicy` should check request in SSR mode.

**Actual outcome:**

`nextFetchPolicy` should check request in SSR mode.
So after request, `cache.evict` should not trigger refetching query on network.

**How to reproduce the issue:**

test repository: https://github.com/Godsenal/apollo-ssr-test

You can check evict force refetch query on network in SSR mode, but not in CSR mode.

**Versions**

  System:
    OS: macOS 10.15.5
  Binaries:
    Node: 12.19.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.198
    Safari: 13.1.1
  npmPackages:
    @apollo/client: ^3.2.4 => 3.2.4
    apollo-datasource-rest: ^0.9.4 => 0.9.4
    apollo-server-express: ^2.17.0 => 2.17.0

**Comment by Godsenal** [comment]
My current workaround is using `cache.modify` with `DELETE` option.

```ts
// using evcit
cache.evict({id: cache.identify(Post)});
cache.gc();

// using modify
cache.modify({
  id: cache.identify(Post),
  fields(_, {DELETE}) {
    return DELETE;
  }
});
```

looks like modifier doesn't trigger network refetch. It just delete target from cache only.

**Comment by Godsenal** [comment]
After implementing the above comment, i wonder the difference between cache.evict and cache.modify with DELETE 🤔.

I also posted this question on the [spectrum](https://spectrum.chat/apollo/apollo-client/difference-between-cache-modify-with-delete-and-cache-evict~123e9e8c-d654-4014-8f30-7344a28cee1e).

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
