### ISSUE TITLE
Can we expose a `client.refetchQueries` option?

### ISSUE THREAD

**Issue by dannycochran** [apollographql/apollo-client#7410]
We have a use case where we need to refetch a number of queries following a mutation. Sometimes the mutation will fail, in which case we still want to refetch the queries. Looking at the [query manager source code](https://github.com/apollographql/apollo-client/blob/29d41eb590157777f8a65554698fcef4d757a691/src/core/QueryManager.ts#L271-L278), this seems perfectly doable, but the properties we need to access are marked as private.

So, I end up doing this:

```typescript
  const updateDeps = [...];
  const [doMutation] = useMyMutation({
    refetchQueries: updateDeps,
    onError: error => {
      const queriesToRefetch = new Set(updateDeps);
      ((client as any).queryManager.queries as Map<string, QueryInfo>).forEach(({ observableQuery }) => {
        if (observableQuery?.queryName && queriesToRefetch.has(observableQuery.queryName)) {
          observableQuery.refetch();
        }
      });
    },
  });
```

Could we instead just expose this as a function or make this functionality easier to access for imperative use cases where we want to trigger a refetch of some queries? Alternatively, we could update `reFetchObservableQueries` to take an array of named operations?

**Comment by benjamn** [comment]
@dannycochran This does seem doable, and I agree it would be useful to be able to force refetching when a mutation errors. Do you have time to put together a PR?

**Comment by dannycochran** [comment]
@benjamn that sounds fun, I can give it a shot. Here's what I'm thinking but I'm open to suggestions:

```typescript
 export declare class ApolloClient<TCacheShape> implements DataProxy {
   ...
   reFetchQueries: (queries: RefetchQueryDescription) => Promise<void>;
 }
```

The promise should probably not throw but should always resolve? In theory we could return back an array of StoreResults for each query you pass in?

It's also a little weird to have this function + "reFetchObservableQueries", but "reFetchObservableQueries" has a function signature that would be hard to augment at the moment, so if we changed the signature it'd be a breaking change.

**Comment by dannycochran** [comment]
@benjamn here's the WIP PR:
https://github.com/apollographql/apollo-client/pull/7431

I'll wait for your feedback before building out all the tests.

**Comment by hwillson** [comment]
This is coming: https://github.com/apollographql/apollo-client/pull/8000

**Comment by bignimbus** [comment]
Hi all, I'm doing some housekeeping and found this issue.  I think per the latest comment this has been resolved since that PR was merged 🙏🏻  let us know if you need more support here!
