### ISSUE TITLE
Help with modifying cache in apollo 3.2.7

### ISSUE THREAD

**Issue by UmangThapliyal** [apollographql/apollo-client#7413]
I am making a query to get a list of task which belong to a user by following query 
```javascript
{
  user {
     tasks {
         id
         name
     }
  }
}
```

When I make the update query and modify the above query using ```cac.writeQuery``` it throws error saying data.user is null

I update it as below
```javascript
cache.writeQuery({
   query: getUserTasks,
   data: {
      user: {
         tasks: [...prevTasks, ...newTask]
      }
   }
})
```

**Comment by bauwaerter** [comment]
Try adding id to your query. Apollo client uses the id field for caching by default.

`{
  user {
     id
     tasks {
         id
         name
     }
  }
}`

**Comment by UmangThapliyal** [comment]
@bauwaerter sorry for the late reply I already have id added I think i missed while positing here, although I made it work the issue was I had to add all the fileds which are present in other dict. 
Is there a wasy by which I can bypass this

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
