### ISSUE TITLE
Allow for custom field denormalization

### ISSUE THREAD

**Issue by tmeasday** [apollographql/apollo-client#742]
In particular for array fields wrt pagination, it would be useful to store more than simply the resulting array of object ids for a field, but instead some more metadata (as one example, something similar to a Relay connection).

This has implications around customizing `fetchMore`/`updateQuery` behavior.

The current model is that when you update the result of a field on a query (let's say `posts(limit: 10)` on the `ROOT_QUERY`), the results are updated in the store for _any_ query that selects that field+arguments. So if you paginate and add 10 results to the field, any other query that tries to select the first 10 posts, will see 20[1](until it goes to the server, of course).

If instead of just storing `ROOT_QUERY.posts(limit: 10): [postIds]`, we instead allowed you to store `ROOT_QUERY.posts: { nodes: [postIds], count: X, ... }` (an object which contains the information required to implement the limit client side), you could both add items to the post list via the various updating mechanisms[2], as well as maintaining the "correct" results for a different query for `posts(limit: 10)`.

It would also allow you to arbitrary field customizations (like for instance allowing client side sorting).

In order to support this properly, we'd need to allow:
1. The ability to transform queries (to add extra fields)
2. The ability to change the normalization format.
3. The ability to change the way a query is selected from the store.

A plugin (such as one that supports Relay-style connector field APIs) would then implement the behavior via all three mechanisms.

[1] The reason for the current behavior is that it's not just pagination, but also subscription and mutation results that can get appended to a field's items. We could take a conservative approach and not "cache" the updated results (or use a complex mechanism to have a special set of results for this query), but then you lose a lot of advantages of the Apollo store.

[2] Both `fetchMore` as well as subscription and mutation results, and arbitrary `updateQuery` calls.

**Comment by helfer** [comment]
cc @calebmer @martijnwalraven 

We just discussed this a bit more today, and we currently like the idea of keeping the store clean (i.e. the key actually represents the data stored under it) and having an extra ListManager (or ConnectionManager) that would piece the information together. That way the store abstraction stays pure while still providing the obvious benefits of fetchMore.

**Comment by helfer** [comment]
Closing this as an old discussion issue. Let's figure this out as part of a future normalization API.
