### ISSUE TITLE
[v3] Cache should not add __typename to @export-ed input variables 

### ISSUE THREAD

**Issue by changLiuUNSW** [apollographql/apollo-client#7421]
Intended outcome:
Non-scalar @export-ed variables should be send to the server without adding a __typename field, because input types do not have a __typename field.

Actual outcome:
Server responds with Field "__typename" is not defined.

The query:

```

mutation submitLead($input: LeadInput) {
    lead @client @export(as: "input") {
      id
      industry
      industryCategory
    }
    submitLead(input: $input) {
      id
    }
  }
```
current in the cache: 

```
{
"__typename":"Lead",
"id":"00ea1100-797a-456f-900c-61acf15f15d6",
"industry":"Health",
"industryCategory":"Other Health Services"
}
```
Error:
```
Error: Variable '$input' is invalid. Unrecognized input fields '__typename' for type 'LeadInput'.
```
Versions
"@apollo/client": "^3.3.2".

Actually I have seen a similar issue 
https://github.com/apollographql/apollo-client/issues/4691
And it has been fixed in 
https://github.com/apollographql/apollo-client/pull/4784

I am not sure why the issue comes back in Apollo client v3

**Comment by benjamn** [comment]
@hwillson @jcreighton @martijnwalraven What do you think about making `HttpLink` automatically strip `__typename` from variables, to stop this kind of problem in all cases?

**Comment by hwillson** [comment]
Sorry for the delay in responding @benjamn:

> What do you think about making `HttpLink` automatically strip `__typename` from variables, to stop this kind of problem in all cases?

I'm 👍 on this, especially knowing that if stripping `__typename` from variables is a problem for anyone, they can create a custom link that doesn't.

**Comment by phryneas** [comment]
Actually, this is a feature now - since Apollo Client 3.8 we are shipping the [removeTypeName](https://www.apollographql.com/docs/react/api/link/apollo-link-remove-typename) link.

I guess with that, we can close this issue :)
