### ISSUE TITLE
Use headline hierarchy in CHANGELOG.md

### ISSUE THREAD

**Issue by dominik-bln** [apollographql/apollo-client#7422]
The `CHANGELOG.md` file uses only level-2 markdown headlines (i. e. `##`). This doesn't convey the actual document hierarchy and looks like it's making it hard for automated tools like `renovate-bot` to understand the changelog. For us this produces more friction when updating and it would be appreciated if this style could be changed. 

**Intended outcome:**

Automated tools like `renovate-bot` can parse the changelog. Headlines like "Improvements", "Bug Fixes", "Documentation" and "Potentially breaking changes" use level-3 markdown headlines. 

**Actual outcome:**

Here is how `renovate-bot` currently parses the apollo-client changelog:

<img width="689" alt="Screenshot 2020-12-07 at 09 29 03" src="https://user-images.githubusercontent.com/855119/101327496-0d43bb00-386f-11eb-9b60-dc1049933532.png">

**How to reproduce the issue:**

-

**Versions**

-

Happy to open an MR if it would be accepted.

**Comment by benjamn** [comment]
@dominik-bln I would be happy to review a PR for this! Note: I think I'd like to maintain a distinction between major version updates (single `#`) and minor updates (double `##`), which means any nested categories (like `### Bug fixes` or `### Improvements`) should have at least a triple `###`.
