### ISSUE TITLE
Client cache is not used at all if there's two useQuery() at same component

### ISSUE THREAD

**Issue by ScripterSugar** [apollographql/apollo-client#7423]
**Intended outcome:**

Two useQuery()  hooks used simultaneously inside same functional component should work as expected being independent from each other, without affecting any behavior of the other query.

**Actual outcome:**

When useQuery() is used inside same functional component, last useQuery() always make two duplicated request, and both useQuery() function aren't using cached data at all, even with the `fetchPolicy: 'cache-first'`. they always create new network requests.

**I can confirm this behavior only occurs when the two queries use same root query field, but with different selection of subfields and/or with different query variable. See below for detail.**

Here's my query used in these two useQuery() hooks.

```javascript
import { gql } from '@apollo/client';

export const getSingleAccommodation = gql`
  query GetSingleAccommodation ($id: ID!) {
    getSingleAccommodation(id: $id) {
        id
        upcomingReservationCount
        todayReservationCount
        kiosks {
          id
          name
          type
          state
          rooms {
            id
            name
            calculatedState
            roomType {
              name
            }
            upcomingReservationCount
          }
        }
        roomTypes {
          id
          name
        }
    }
  }
`;

export const accommodationSalesQuery = gql`
  query AccommodationSales ($id: ID!, $reservationType: String) {
    getSingleAccommodation(id: $id) {
      cardSalesToday(reservationType: $reservationType)
      cashSalesToday(reservationType: $reservationType)
    }
  }
`;
```

And here's the comonent code where I use the useQuery() twice.

```javascript
const Dashboard = ({ loader }: { loader: any }) => {
  const theme = useTheme();
  const { accommodationId } = useParams();
  const [statTab, setStatTab] = useState(0);

  const { data: accommodationData, error: accommodationError } = useQuery(getSingleAccommodation, {
    variables: {
      id: accommodationId,
    },
    fetchPolicy: 'cache-first',
  });

  const { data: salesData, loading: salesLoading } = useQuery(accommodationSalesQuery, {
    variables: {
      id: accommodationId,
      reservationType: statTab || null,
    },
    fetchPolicy: 'cache-first',
  });

 ...
 // Rest codes are for rendering only. not using any graphQL related hooks / functions at all.

```

Noticeable point is that both query is using same root query getSingleAccommodation. I intentionally separated this to two different query as user could change filter variable for sales query often, and I don't want to all information about other sub-fields getting refetched when filter changes.

**How to reproduce**
 
use useQuery() twice inside same component using same root query but with different name & subfield selections.

If someone can confirm this is not known-issue and also not intended behavior, I'll try to make codesendbox repo.

**Versions**
    "@apollo/client": "^3.3.4"
    "react": "^16.13.1"
    "react-dom": "16.13.1"

**Comment by benjamn** [comment]
@ScripterSugar Have you tried adding the `id` field to the second query?
```ts
export const accommodationSalesQuery = gql`
  query AccommodationSales ($id: ID!, $reservationType: String) {
    getSingleAccommodation(id: $id) {
      id # 👈
      cardSalesToday(reservationType: $reservationType)
      cashSalesToday(reservationType: $reservationType)
    }
  }
`;
```
If the cache doesn't know the identity of the `getSingleAccommodation` result object, it can't automatically merge its fields with existing data, and the two queries may end up clobbering each other's data, requiring subsequent network fetches.

You can turn this mistake into a runtime exception by defining `keyFields` for the object type:
```ts
new InMemoryCache({
  typePolicies: {
    SingleAccommodation: {
      keyFields: ["id"],
    },
  },
})
```
This is equivalent to the default behavior, of course, but `keyFields` complains louder when the required fields are not found in the query data.

**Comment by ScripterSugar** [comment]
@benjamn Thanks for the comment. Selecting id subfield on second query solved the problem.

It looks like the cache worked as intended, thus closing the issue.
