### ISSUE TITLE
Got "No repository for ..." error after start server and load the page for the first time

### ISSUE THREAD

**Issue by adsee42** [apollographql/apollo-client#7426]
I have an express server with apollo-server for backend, and React with apollo-client as front.

There're 2 repositories, "Config" and "Routes"; they are supposed to be loaded from the server when any React page is loaded for the first time (including refresh the page), and at the same time, showing a loading icon, before rendering any meaningful content.

But after I made some changes and restart the server, and open front page, the "Routes" get loaded successfully, but the "Config" shows error message: "No repository for "Config" was found. Looks like this entity is not registered in current "default" connection?"

If I refresh the page, now both loaded successfully.

Any thoughts?

(Querying with apollo chrome dev tool fetched the "Config" successfully, so maybe I should wait some seconds before sending first query?)

**Comment by benjamn** [comment]
@adsee42 That error message isn't one that Apollo Client or Apollo Server use. Based on some quick googling, it seems related to the [TypeORM](https://github.com/typeorm/typeorm/issues/3017) project. Are you using `TypeORM`?

**Comment by adsee42** [comment]
@benjamn Thanks!
Yes I'm using `TypeORM`.
But all other queries worked fine except the first one, so I thought it was something related to the apollo server.
I'll close this if this has nothing to do with apollo.
