### ISSUE TITLE
Extend @client directive to resolve a `value`

### ISSUE THREAD

**Issue by webdeb** [apollographql/apollo-client#7429]
To delete something from a List of items and have a consistent UI with the data afterwards is a hard topic.

I just faced it, and read multiple Blogs posts and SO topics on this. The essence on this is:

A: Refetch the List
B: Update the cache manually
C: Use a `@client` directive 

The **C** options seems to me the most cool one, since we do not leave the graphql context, except we have to define a custom resolver for this.

So I thought, why not resolve a value from inside the `deleteMutation` ?

To summarise, this is my List:

```js
const { data } = useQuery(gql`
  getItems {
    items {
       id
       title
       deleted @client
    }
  }
`)

return data?.items.map(item => {
   if (item.deleted) return null 
   return <Item item={item} />
})
```

And this is my `deleteMutation` where I set the `deleted` key and expect to land in the local store.

```gql
const DELETE_ITEM = gql`
  deleteItem($id: Int!) {
    deleteItem(id: $id) {
      id
      deleted @client(value: true) // this is the resolver
    }
  }
`
```

What do you think, it seems to be a very intuitive approach, simple and flexible, you could even override the `deleted` value  with a **restore** query:

```gql
const RESTORE_ITEM = gql`
  restoreItem($id: Int!) {
    restoreItem(id: $id) {
      id
      deleted @client(value: false) // this is the resolver
    }
  }
`
```

Sure, to make this work the `items`, `deleteItem` and `restoreItem` need to return the same type "item". However, it would also be possible without the exact type, just by faking it for example:

```js
const DELETE_ITEM = gql`
 deleteItem($id: Int!) {
   deleteItem(id: $id) {
     id @client(value: $id)
     deleted @client(value: true)
     __typename @client(value: "item")
   }
}
`
```

**Comment by benjamn** [comment]
@webdeb While some feature requests are simple/obvious/actionable enough to belong in this repository, I think this one is creative enough (as in, worthy of further design discussion) that it belongs in our [feature requests](https://github.com/apollographql/apollo-feature-requests/issues) repository. Would you mind moving it there?

**Comment by webdeb** [comment]
@benjamn sure, I can move it there, but it seems that the Feature Requests other there do not get much attention, unfortunately.  I'd be happy with a simpler solution like **adding custom client side directives** and leave it here, if thats ok?
