### ISSUE TITLE
Apollo Client uses localhost instead of uri

### ISSUE THREAD

**Issue by MelMayssonOwen** [apollographql/apollo-client#7432]
I'm trying to set up an Apollo Client by following this [documentation](https://www.apollographql.com/docs/react/networking/authentication/#header)  however it always tries to use localhost instead of the specified uri

**Intended outcome:**

Have Apollo point to my server uri

**Actual outcome:**

Apollo to localhost:3000/graphql

`createHttpLink.ts:121
POST http://localhost:3000/graphql 404 (Not Found)`

**How to reproduce the issue:**

```
import { ApolloProvider, ApolloClient, InMemoryCache, createHttpLink} from '@apollo/client';
import { setContext } from '@apollo/client/link/context';


const httpLink = createHttpLink({
    uri: process.env.API_URL,
});

const authLink = setContext((_, { headers }) => {
    const token = localStorage.getItem('accessToken');
    return {
        headers: {
        ...headers,
        authorization: token ? `Bearer ${token}` : '',
      },
    };
});

const client = new ApolloClient({
    link: authLink.concat(httpLink),
    cache: new InMemoryCache(),
});
```

**Versions**

 System:
    OS: macOS 11.0.1
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 78.0.2
    Safari: 14.0.1
  npmPackages:
    @apollo/client: ^3.2.9 => 3.2.9

**Comment by benjamn** [comment]
@MelMayssonOwen If you put a `console.log(process.env.API_URL)` just before the `createHttpLink` call, what's the value you see?

**Comment by MelMayssonOwen** [comment]
You are right, it seems that the process.env randomly works.

After renaming the variable to REACT_APP_API_URL the problem seems solved.

So it’s not an Apollo issue, thanks  

>
