### ISSUE TITLE
Apollo-client doesn't catch serverErrors

### ISSUE THREAD

**Issue by ZelikSV** [apollographql/apollo-client#7433]
<img width="1237" alt="Screenshot at Dec 08 2-11-26 PM" src="https://user-images.githubusercontent.com/40599524/101534546-fd77c400-399f-11eb-9996-cd05f33694bf.png">
I try to handle errors from server by apollo/client/link/error using onError method. But i got crash my app anyway.
There is i init Apollo client:

```js
const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: from([error, auth, httpLink]),
});
```

There is links

```js
const httpLink = new HttpLink({ uri: `${process.env.REACT_APP_API_HOST}/graphql` });

const error = onError(({ graphQLErrors, networkError }) => {
  if (graphQLErrors) {
    graphQLErrors.map(({ message, locations, path }) =>
      // eslint-disable-next-line no-console
      console.log(`[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`),
    );
  }

  if (networkError) {
    if (networkError.hasOwnProperty('result')) {
      notify((networkError as ServerError).result, 'error');
    }
  }
});

const auth = new ApolloLink((operation, forward) => {
  operation.setContext(({ headers = {} }) => ({
    headers: { ...headers, Authorization: `Bearer ${JSON.parse(localStorage.getItem('token') as string)}` },
  }));

  return forward(operation);
});
```

**Comment by benjamn** [comment]
@ZelikSV Can you share your code that calls `client.mutate` (or uses `useMutation`)?

**Comment by ZelikSV** [comment]
@benjamn sure
This is hook 
const [addSignatureToNcr] = useAddSignatureToNcrMutation();

Call
addSignatureToNcr({
        variables: {
          dto: {
            approved: values.approved,
            secretCode: values.secretCode,
            signatureDate: values.signatureDate?.toISOString(),
            holderId: match.params.id,
            userProjectId: values.userProjectId.id,
          },
        },
      })

**Comment by ZelikSV** [comment]
That i got from codegen
export function useAddSignatureToNcrMutation(baseOptions?: Apollo.MutationHookOptions<AddSignatureToNcrMutation, AddSignatureToNcrMutationVariables>) {
        return Apollo.useMutation<AddSignatureToNcrMutation, AddSignatureToNcrMutationVariables>(AddSignatureToNcrDocument, baseOptions);
      }

**Comment by ZelikSV** [comment]
I try to add { errorPolicy: 'ignore' } to the useAddSignatureToNcrMutation but got the same error

**Comment by martinjlowm** [comment]
It seems the `error` observer handler is called over the `complete` handler for network errors:
https://github.com/apollographql/apollo-client/blob/23c77543f98e80d1b82baec1e91b92d5b59ac835/src/core/QueryManager.ts#L227-L241

`errorPolicy` is not used there which implies it results in an uncaught promise rejection (unless the caller is catching it).

**Comment by ali-farooq0** [comment]
@ZelikSV @martinjlowm were you guys able to fix the underlying cause here. I'm running into the exact same thing. Since the throw happens inside the QueryManager there is no way for me to catch and handle the exception, which is really frustrating. 

Any advise on this will be much appreciated.

**Comment by bignimbus** [comment]
Hi all, since this issue is getting stale and there's nothing clearly actionable for the maintainers at this time I'll close it.  For folks in this thread with more questions and/or people finding this from search, please consider posting in our [community forum](https://community.apollographql.com/)!  Thanks so much 🙏🏻
