### ISSUE TITLE
Redirect Angular documentation to apollo-angular.com

### ISSUE THREAD

**Issue by fetis** [apollographql/apollo-client#7435]
Hello there,

The Angular documentation on apollographql.com is outdated and not supported. There's a redirect to the new docs but it doesn't work for some reasons https://github.com/apollographql/apollo/blob/master/docs/static/_redirects#L41

Could you plz check what's the problem there?

**Comment by StephenBarlow** [comment]
@fetis Thanks for reporting! This issue is now resolved: https://www.apollographql.com/docs/angular

**Comment by fetis** [comment]
thank you so much ❤️
