### ISSUE TITLE
nextFetchPolicy should reset to fetchPolicy when variables changes

### ISSUE THREAD

**Issue by Titozzz** [apollographql/apollo-client#7437]
Hello,

Because of the way apollo-client 3 is designed, it will make a lot of extra request over the network if you don't set nextFetchPolicy to cache-first.
For example:
 `Query some data -> Mutate it -> Query will rerun if nextFetchPolicy isn't specified.`
Let's now imagine a more complex usecase where you can change your query variables (for example pagination).

`Query page 1 : Network fetches page 1 because of 'cache and network'`
`Query page 2 : Network fetches page 2 because of 'cache first' ( but cache is empty )`

Let's now say you come back later, data has changed and you use cache persist but your cached data is obsolete.

`Query page 1 : First displays outdated data, but Network refetches page 1 because of 'cache and network'`
`Query page 2 : Displays outdated data and doesn't fetch network because of 'cache-first'`

So I believe that when the fetch policy should be bound to the current variables to avoid theses issues

**Intended outcome:**
I should be able to use nextFetchPolicy set to cache-first to avoid extra network calls from AC3

**Actual outcome:**
Setting nextFetchPolicy to cache-first makes stale data be returned if you update variables.

**How to reproduce the issue:**
See intro 😄 

**Versions**
tested on latest at this time: 3.3.4

@benjamn This is 100% related to that thread but I felt it didn't belong there so I created that issue.
https://github.com/apollographql/apollo-client/issues/6677

I'm available to help if you need anything, but if you can point me in the right direction that would be great!

Thanks 💯

**Comment by martinjlowm** [comment]
We're experiencing the same - I was looking into the issue and it seems despite the change in variables, the cache is hit and previous data is served. Perhaps resetting fetchPolicy is a simple way of fixing it - dunno if it's the right way.

**Comment by blasterpistol** [comment]
I have been using this wrapper since migrating from v2 to v3. It would be nice to give up this dirty trick.

```ts
import { useQuery as _useQuery } from '@apollo/client'
import isEqual from 'fast-deep-equal'
import { useRef } from 'react'

export function useQuery(query, options) {
  // make a new request if variables have been changed
  // it's not the same as cache-and-network
  // since cache-and-network refetches initial request after writeQuery
  // all combinations of fetchPolicy and nextFetchPolicy also not work

  const vars = useRef(undefined)
  const fetchPolicy =
    options?.fetchPolicy ||
    (vars.current === undefined // vars.current is undefined on the first render, so make request to get fresh data
      ? 'cache-and-network'
      : isEqual(vars.current, options?.variables) // check if variables have changed, if so use network-only (it also populates the cache)
      ? 'cache-first' 
      : 'network-only')

  vars.current = options?.variables

  const { data, ...rest } = _useQuery(query, { ...options, fetchPolicy })
  return { data: data || rest.previousData, ...rest }
}
```

**Comment by Titozzz** [comment]
@blasterpistol Exactly what I'm trying to dodge :) For now I'd rather spam our back end a bit more cause we can handle it.

**Comment by benjamn** [comment]
@Titozzz @blasterpistol I'm optimistic `@apollo/client@3.4.0-rc.18` may solve this issue once and for all, thanks to #8465. Please give it a try when you have the chance!

**Comment by adrienharnay** [comment]
Hi @benjamn, I just tried @apollo/client@3.4.8 with the issue @Titozzz posted, and it is gone!

Thanks for the fix 🙏

**Comment by benjamn** [comment]
Thanks for the update @adrienharnay!

Closing now, but happy to reopen if the problem persists/reappears for anyone.
