### ISSUE TITLE
apollo-boost: graphQLErrors.forEach is not a function

### ISSUE THREAD

**Issue by pascaln** [apollographql/apollo-client#7440]
Hello,

When I call the Shopify GraphQL Api it can happen that I get errors. This leads to the following exception in Apollo-Boost (4.7.9):

TypeError: graphQLErrors.forEach is not a function
    at .../node_modules/apollo-boost/lib/bundle.cjs.js:102:23
    at Object.error (./node_modules/apollo-link-error/lib/index.js:33:41)
    at notifySubscription (./node_modules/zen-observable/lib/Observable.js:140:18)
    at onNotify (./node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.error (./node_modules/zen-observable/lib/Observable.js:240:7)
    at ./node_modules/apollo-link-http/lib/httpLink.js:87:26

It seems that the Shopify response is not an array. I think the code should check if it an array before looping over it.

Or do I need to configure something different?
Thx

**Comment by builtbylane** [comment]
I can confirm that this is an issue for Shopify. Getting the same error when shopify sends back 404.

**Comment by builtbylane** [comment]
switching to '@apollo/client' solves the issue. 'apollo-boost' is deprecated

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!

**Comment by mcjambi** [comment]
Shopify example code is too old. I have to replace all apollo-boost to @apollo/client
