### ISSUE TITLE
ignoreResults not being respected when mutation fails

### ISSUE THREAD

**Issue by msimulcik** [apollographql/apollo-client#7444]
**Intended outcome:**

`ignoreResults` being respected when mutation fails and not re-render the component.

**Actual outcome:**

`ignoreResults` is not being checked in `onMutationError` (https://github.com/apollographql/apollo-client/blob/main/src/react/data/MutationData.ts#L133) as opposed to `onMutationComplete` (https://github.com/apollographql/apollo-client/blob/main/src/react/data/MutationData.ts#L119). This causes unwanted re-render when mutation fails. In my case it leads to form being cleared.

**How to reproduce the issue:**

```js
const [mutate] = useMutation<CreateUser, CreateUserVariables>(
  CreateUserMutation,
  {
    ignoreResults: true,
  },
);
```

**Versions**

  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
    Yarn: 1.22.5 - ~/projects/1/node_modules/.bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Safari: 14.0.1
  npmPackages:
    @apollo/react-testing: ^3.1.4 => 3.1.4 
    apollo: ^2.6.0 => 2.21.0 
    apollo-cache-inmemory: ^1.1.12 => 1.6.3 
    apollo-client: ^2.0.0 => 2.6.4 
    apollo-link: ^1.2.13 => 1.2.13 
    apollo-link-context: ^1.0.7 => 1.0.19 
    apollo-link-error: ^1.1.12 => 1.1.12 
    apollo-link-http: ^1.5.16 => 1.5.16 
    react-apollo: 3.1.3 => 3.1.3

**Comment by hwillson** [comment]
If someone can provide a small runnable reproduction that demonstrates this happening with `@apollo/client@latest`, we'll take a closer look. Thanks!
