### ISSUE TITLE
How to access edges object in InMemoryCache - typePolicies

### ISSUE THREAD

**Issue by gauravverma029** [apollographql/apollo-client#7452]
**version :  "@apollo/client": "^3.3.4"**

Query 👍 

```import { gql } from "@apollo/client";

export const GET_ISSUES_OF_REPOSITORY = gql`
  query Issues(
    $repositoryOwner: String!
    $repositoryName: String!
    $issueState: IssueState!
    $cursor: String
  ) {
    repository(name: $repositoryName, owner: $repositoryOwner) {
      issues(first: 10, states: [$issueState], after: $cursor) {
        edges {
          node {
            id
            number
            state
            title
            url
            bodyHTML
          }
        }
        pageInfo {
          endCursor
          hasNextPage
        }
      }
    }
  }
`;`


cache Function
`const cache = new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        repository: {
          merge(existing = {}, incoming) {
            console.log("..", existing, incoming);
            return { ...existing, ...incoming };
          },
        },
      },
    },
  },
});
```

Getting Response inside 

```issues({"first":10,"states":["OPEN"]}):
edges: (10) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
pageInfo: {__typename: "PageInfo", endCursor: "Y3Vyc29yOnYyOpHOBLM5vw==", hasNextPage: true}
__typename: "IssueConnection"
__typename: "Repository"`
```
![Screen Shot 2020-12-10 at 20 40 36](https://user-images.githubusercontent.com/4488516/101822059-15c71a80-3b29-11eb-9255-3888ecd561a9.png)

Why key is **issues({"first":10,"states":["OPEN"]})** Not able to go inside edges becuase my key will always change when i will do pagination.

```




Component 
`import React from "react";
import { useQuery } from "@apollo/client";

import { GET_ISSUES_OF_REPOSITORY } from "../../utils/queries";

const Issues: React.FC = () => {
  const { data, loading, error, fetchMore } = useQuery(
    GET_ISSUES_OF_REPOSITORY,
    {
      variables: {
        repositoryOwner: "facebook",
        repositoryName: "react",
        issueState: "OPEN",
      },
    }
  );
  console.log(data, loading, error);
  return (
    <div>
      <div>issue</div>
      <div
        onClick={() =>
          fetchMore({
            variables: {
              cursor: data.repository.issues.pageInfo.endCursor,
            }
          })
        }
      >
        More button
      </div>
    </div>
  );
};

export default Issues;`

```

Please help me in this what i am doing wrong here

**Comment by benjamn** [comment]
@gauravverma029 Please read our documentation about Relay-style pagination: https://www.apollographql.com/docs/react/pagination/cursor-based/#relay-style-cursor-pagination

In short, your `merge` function has no chance of handling paginated data correctly as it's currently written, but we have a helper function called `relayStylePagination` that can do everything for you:
```ts
new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        repository: relayStylePagination(["name", "owner"]),
      },
    },
  },
})
```

**Comment by gauravverma029** [comment]
> @gauravverma029 Please read our documentation about Relay-style pagination: https://www.apollographql.com/docs/react/pagination/cursor-based/#relay-style-cursor-pagination
> 
> In short, your `merge` function has no chance of handling paginated data correctly as it's currently written, but we have a helper function called `relayStylePagination` that can do everything for you:
> 
> ```ts
> new InMemoryCache({
>   typePolicies: {
>     Repository: {
>       fields: {
>         issues: relayStylePagination(["states"]),
>       },
>     },
>   },
> })
> ```

Awesome it is working fine. But I can not see ["states"] anywhere in the documentation

**Comment by ruipneves** [comment]
@gauravverma029 `states` is just for the `keyArgs` field.
Underneath, `relayStylePagination` is configuring `states` as `keyArgs` in the field policy. This means that your query depends on `states` and will return a different cache entry for each different `states` value if I am not mistaken.
