### ISSUE TITLE
https://www.apollographql.com/docs/react/api/react/hoc documents the wrong module

### ISSUE THREAD

**Issue by dsilvasc** [apollographql/apollo-client#7455]
**Intended outcome:**

I was looking for documentation on how to use apollo-client with React class components (for existing code that will take a while to migrate to functional components) and landed on https://www.apollographql.com/docs/react/api/react/hoc/ 

I noticed later that the HOC functionality was migrated into apollo-client as `@apollo/client/react/hoc` with https://github.com/apollographql/apollo-client/pull/6558

It would be helpful for the doc page to mention this migration and to document api changes in `@apollo/client/react/hoc` if there are any.

**Actual outcome:**

That page documents `@apollo/react-hoc` and says that apollo-client react HOCs are deprecated in favor of apollo-client react hooks.  The issue at https://github.com/apollographql/react-apollo/issues/3959 says something similar.

It doesn't mention or document `@apollo/client/react/hoc`.

**Comment by StephenBarlow** [comment]
This change is now live in the article mentioned. Thanks for reporting!
