### ISSUE TITLE
I am trying to read the cache by "readQuery" , but it's return null

### ISSUE THREAD

**Issue by ahmedelamine** [apollographql/apollo-client#7457]
note: I have the results in the cache, but it's return null

**Comment by benjamn** [comment]
@ahmedelamine This means not all the queried fields could be supplied by the cache. I would recommend putting a `debugger` statement just before your `readQuery` call, so you can step into it in your browser debugging tools (Sources tab in Chrome). There's a `return null` statement [here](https://github.com/apollographql/apollo-client/blob/df7e5a52eeae7eebd12a47c5cd56b9ab12b11eff/src/cache/inmemory/inMemoryCache.ts#L136) that you could pause on (by setting a breakpoint there and letting the program continue until the breakpoint is hit), which would then allow you to examine the `MissingFieldError` that caused the failure, which should tell you what was missing.

See #7098 for more background on why `readQuery` swallows these `MissingFieldError` exceptions and returns `null` instead.

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
