### ISSUE TITLE
Apollo Cache V3: References instead of value within TypePolicy field read()

### ISSUE THREAD

**Issue by chriswetterman** [apollographql/apollo-client#7459]
I've created a `@client`-only field where it's value is based on another field within the same query, and have created a type policy to determine that value when the `@client` field is read. Here is a snippet of the query and the policy. 

```
query docDetails($docStr: String!) {
    docDetailsByDocString(docStr: $docStr) {
       source {
         id
         code
         desc
       }
       sourceOther
       isSourceOtherVisible @client
     }
  }
}
```
```
typePolicies: {
    DocDetails: {
      fields: {
        isSourceOtherVisible: {
          read(_, { readField, }) {
            const source = readField("source")
            return source.code.toUpperCase() === 'OTH';
          },
        },
      },
    }
  }
```
My understanding from the documentation is that `readField` will return the value even if the cache has it as a reference. What I am receiving though from `readField` is a reference.

**Intended outcome:**
I expected to receive the source object returned to from `readField` to be in the shape of 

```
{
   __typename: "Source",
   id: 0,
   code: "OTH",
   desc: "Other"
}
```

**Actual outcome:**

```
{
   __ref: "Source:0"
}
```

**How to reproduce the issue:**
Create a schema (like the one attached above), create a cache with a configuration like the one above. Attempt to execute the one and only query and inspect the result of the read function.

**Versions**
```
System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 12.19.0 - ~\DevTools\node-v12.19.0-win-x64\node.EXE
    npm: 6.14.8 - ~\DevTools\node-v12.19.0-win-x64\npm.CMD   
  Browsers:
    Chrome: 87.0.4280.88
    Edge: Spartan (44.19041.423.0), Chromium (86.0.622.63)   
  npmPackages:
    @apollo/client: 3.2.5 => 3.2.5 
    apollo-server: ^2.16.1 => 2.18.2
```

**Comment by benjamn** [comment]
@chriswetterman This is expected. The `read` and `merge` functions (and `readField`) operate on the internal representation of cache data, which includes `{ __ref: string }` objects.

In this case, you probably want
```ts
const code = readField("code", readField("source"));
```
which will still work if `readField("source")` happens to return a non-reference object.

**Comment by chriswetterman** [comment]
@benjamn Thank you for providing feedback and your solution resolved the issue in code I was having. 

Regarding the documentation, I was reading from a few places:

[FieldPolicy API](https://www.apollographql.com/docs/react/caching/cache-field-behavior/#fieldpolicy-api-reference) - I guess I misread the comment for `readField` (multiple times). But I think it's the name of the function itself that through me off as I interpreted it as "we will be reading the value of the field" and when I received a reference was thrown for a loop. 

[Cache Interaction Docs](https://www.apollographql.com/docs/react/caching/cache-interaction/#cachemodify) - The **Removing an item from a list** example states, "It also uses the `readField` utility function, which helps you read the value of any cached field". 

Lastly in [Cursor-based Pagination](https://www.apollographql.com/docs/react/pagination/cursor-based/#using-list-element-ids-as-cursors) - The code comment in the `offsetFromCursor` example function states, "Using `readField` works for both non-normalized objects (returning item.id) and normalized references (returning the id field from the referenced entity object), so it's a good idea to use `readField` when you're not sure what kind of elements you're dealing with."

After seeing 'value' mentioned in a few places committed that to memory as the expected behavior. Thanks again, and I now know that when I come across references again I need to keep on digging down with `readField`.

**Comment by ashubham** [comment]
@benjamn How do I read the whole object at the destination. 

Like in the above example is there a way to get the whole `Source` object ?

```
const source = readField("source");

// Now how can I get the whole source object ? It may not be nestedly resolved for other references.
// But, I want to read multiple fields from it.
```

**Comment by benjamn** [comment]
@ashubham There's no way to read the whole object at once, but you can read arbitrary nested fields from references:
```ts
readField("someSourceField", readField("source"))
```
When you pass only one argument (a field name), `readField` reads from the current object, but you can read from other objects by passing a reference as the second argument (as above). One nice thing about `readField` is that it works the same way if that second argument is a `{ __ref }` object or a normal (non-normalized) object, so you don't have to be careful about using it only for references. Another nice thing is that calling `readField` automatically registers a dependency on the nested field(s) that you're reading, so the current query can be invalidated in the future if that field changes value.

**Comment by ashubham** [comment]
Thanks for your response @benjamn 

In my use case the object is large and is passed to another library and I do not have a handle on the internals of which fields might be accessed within that. Is it possible to make `cache.data.data` or something like `cache.getReferencedData(ref)` public ? I am okay with the whole object being invalidated as that's mostly true in my use case.

**Comment by chriswetterman** [comment]
@ashubham Could you utilize cache.readFragment() to get what you need?

**Comment by pankucsi** [comment]
@ashubham I dont know if it is good practice or not, but seems working:

```js
const sourceListResolved = sourceList.map((s) =>
  cache.readFragment({
    id: s['__ref'],
    fragment: gql`
      fragment PartialSource on Source {
        id
        ...otherProps
      }
    `,
  }),
)
```

But I recently started using Apollo client, so maybe it is totally nonsense, and bad usage for @client-only fields. 🤔

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding bug here, so closing. Thanks!

**Comment by oseisaac** [comment]
```
subscriptions: {
          keyArgs: false,
          merge(existing = [], incoming) {
            console.log(existing, "incoming", incoming);


            // update the expiry status of each subscription option

            return updates;
          },
        },
```
This returns only __ref and not the actual data.
