### ISSUE TITLE
Query won't submit when only a fragment is provided

### ISSUE THREAD

**Issue by QiroNT** [apollographql/apollo-client#7470]
TLDR I was trying to build a query with a fragment:
```javascript
// ...
const fragment = gql`
  fragment RootFrag on QueryRoot {
    foo
  }
` // example fragment
// ...
const result = await client.query({
  query: gql`
    query rootQuery {
      ...RootFrag
    }
    ${fragment}
  `,
});
// ...
```

**Intended outcome:**

I expected the result to be something like:
```javascript
{
  data: {
    foo: "bar"
  },
  loading: false,
  networkStatus: 7
}
```

**Actual outcome:**

The client submitted no request and output no data.
```javascript
{
  data: {},
  loading: false,
  networkStatus: 7
}
```

**How to reproduce the issue:**

```javascript
client.query({
  query: gql`
    query rootQuery {
      ...RootFrag
    }

    fragment RootFrag on QueryRoot {
      foo
    }
  `,
}); // -> data: {}

client.query({
  query: gql`
    query rootQuery {
      bar
      ...RootFrag
    }

    fragment RootFrag on QueryRoot {
      foo
    }
  `,
}); // -> data: { foo: "bar", bar: "foo" }
```

**Versions**

```
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 2.2.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.88
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.60)
  npmPackages:
    @apollo/client: ^3.3.6 => 3.3.6
    apollo-link-scalars: ^2.0.3 => 2.0.3
```

**Comment by benjamn** [comment]
@QiroNT The default typename for the root query object is not `QueryRoot` but just `Query`. I believe that's why your fragment never matches. Can you try this instead?
```ts
const fragment = gql`
  fragment RootFrag on Query {
    foo
  }
`;
```

**Comment by QiroNT** [comment]
> @QiroNT The default typename for the root query object is not `QueryRoot` but just `Query`. I believe that's why your fragment never matches. Can you try this instead?
> 
> ```ts
> const fragment = gql`
>   fragment RootFrag on Query {
>     foo
>   }
> `;
> ```

Sorry for the late reply.

This code won't work because our server's query root object's `__typename` is actually `QueryRoot`.
![ROOT TYPES: query: QueryRoot](https://user-images.githubusercontent.com/31543482/102593894-6bff1380-4150-11eb-926c-cd0325e5e89c.png)

When running your code, the request will be sent, but server returns it with a error.
```json
{
  "errors": [
    {
      "message": "Unknown type \"Query\"",
      "locations": [{ "line": 5, "column": 22 }]
    }
  ]
}
```

BTW we are using actix + juniper as our server.

Some test code using `GraphiQL`:
![GraphiQL screenshot](https://user-images.githubusercontent.com/31543482/102594110-baacad80-4150-11eb-806d-a6ecbf372fc6.png)

**Comment by dernster** [comment]
I'm facing the same issue. In my case, the root query is called `AppQuery` and I've been able to use this pattern successfully before upgrading to Apollo client v3. I see some issues that were closed in the past with this exact same problem I think. Check #3402 and #3882

**Comment by benjamn** [comment]
@QiroNT @dernster Ahh, in that case, you can/should configure the cache to use your custom root query and mutation `__typename`s:
```ts
new InMemoryCache({
  typePolicies: {
    QueryRoot: { // AppQuery for @dernster
      queryType: true,
    },
    MutationRoot: { // Mutation by default
      mutationType: true,
    },
  },
})
```
You might hope the client could automatically figure out this information by requesting `query { __typename }`, but there are cases where that information is needed before any network requests have been made, so it's important to configure it explicitly, as early as possible.

**Comment by QiroNT** [comment]
Well, thanks for the solution. I [changed the root query to `Query`](https://github.com/PatchyVideo/pvgql/commit/e07d7dc023207fe6f386566d4a070fff5fac0c4b#diff-004371b340066052ff56b5dc086eab42d93093a93c10595607a4841e11a8029b) last month and it works just fine. But I also happy to see a solution for this case. Wish that this caution can result as a note or FAQ in the document.
Anyway, problem solved, closing the issue now.

**Comment by ikhsanalatsary** [comment]
> @QiroNT @dernster Ahh, in that case, you can/should configure the cache to use your custom root query and mutation `__typename`s:
> 
> ```ts
> new InMemoryCache({
>   typePolicies: {
>     QueryRoot: { // AppQuery for @dernster
>       queryType: true,
>     },
>     MutationRoot: { // Mutation by default
>       mutationType: true,
>     },
>   },
> })
> ```
> 
> You might hope the client could automatically figure out this information by requesting `query { __typename }`, but there are cases where that information is needed before any network requests have been made, so it's important to configure it explicitly, as early as possible.

Thank you. it works as expected
