### ISSUE TITLE
Apollo duplicates the last item on cache update

### ISSUE THREAD

**Issue by mannaqureshi** [apollographql/apollo-client#7477]
I was trying to update cache on data changes for subscription. it works fine if I append the item on the last index of the previous array. However if I try to add the item to the very first index, cache is somehow affected and duplicates are created at the very last index of the array.

```
const { data: messages, subscribeToMore } = useQuery(Chats.messages, {
    fetchPolicy: "cache-and-network",
    variables: {
      query: {
        chatId: props.chatId,
        pagination: {
          to: 50,
          from: 0,
        },
      },
    },
  });

  useEffect(() => {
    subscribeToMore({
      document: Chats.messageSubscription,
      variables: {
        chatId: props.chatId,
      },
      updateQuery: (prev, { subscriptionData }) => {
        if (!subscriptionData.data) return prev;
        const newMessage = subscriptionData.data.message;

        return {
          messages: [subscriptionData.data.message, ...prev.messages],
        };
      },
    });
  }, []);
```

**Intended outcome:**

{
  messages : [5,1,2,3,4]
}

**Actual outcome:**

{
  messages : [1,2,3,4,4]
}

**How to reproduce the issue:**

**Versions**

**Comment by tehpsalmist** [comment]
Any luck resolving this? I'm hitting it now, too.

**Comment by mannaqureshi** [comment]
Yeah. Originally the core problem wasn't with Apollo but It was a missing dependency in a useCallback() in my case. I used plain function handlers instead of passing them inside useCallback() and removed React.memo() from the presentational component (in my case it was the message component). That solved the issue. Hope this helps you

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
