### ISSUE TITLE
useLazyQuery change the fetchPolicy

### ISSUE THREAD

**Issue by ariel-upstream** [apollographql/apollo-client#7479]
Hi,
I'm using the useLazyQuery hook and trying to change the fetchPolicy between my API calls but it seems it always has the same fetchPolicy.

```
const [loadData, { data, fetchMore }]: any = useLazyQuery<DataRes>(DataDoc, {
    fetchPolicy: "network-only",
    variables: { limits: { limit: 30, offset: 0 } },
  })
```
And I call loadData and fetchMore in different methods, I'm trying to change the fetchPolicy and it looks like it always executes with  fetchPolicy: "network-only",

e.g:
```
 loadData({
      fetchPolicy: "cache-and-network",
      variables: {
          limits: { limit: 30, offset: 0 },
      },
    })
```

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
