### ISSUE TITLE
Calling error handler multiple times

### ISSUE THREAD

**Issue by zewa666** [apollographql/apollo-client#7483]
I've implemented the onError handler in order to perform a re-auth of my JWT flow.
Now while testing my refresh-token I've set the expiry for my access_tokens to 10s so that I can quickly try/error and see what happens.

It now turns out that the onError handler will only be called once. After reading through [the docs](https://www.apollographql.com/docs/react/api/link/apollo-link-error/) I've noticed

> One caveat is that the errors in the new response, from retrying the request, do not get passed into the error handler again. This helps avoid being trapped in an endless request loop when you call forward() in your error handler.

Ok so expected behavior. But my question is now how to do the actual re-auth multiple times since the access_tokens are going to have an expiry time between 5-15mins which means it for sure will happen at least twice in an usual session of my app.

EDIT: here is the sample code I'm using for the errorLink. Funny enough graphQLErrors is always empty for me and instead I do get a networkError with code `start-failed`.

```typescript
const errorLink = onError(
      ({ graphQLErrors, networkError, operation, forward }) => {
        console.log(graphQLErrors, networkError);
        if (networkError) {
          switch ((networkError as any).extensions.code) {
            case "start-failed": {
              const token = getToken();
              return fromPromise(
                fetch(`${environment.backend_host}/token`, {
                  method: "POST",
                  headers: {
                    "Content-Type": "application/json",
                    "Accept": "application/json"
                  },
                  body: json({ userId: token.sub }),
                  credentials: "include"
                }).then(res => res.json()).then((res) => {
                  storeToken(res.token);
                }).catch(error => {
                  // Handle token refresh errors e.g clear stored tokens, redirect to login, ...
                  return;
                })
              ).filter(value => Boolean(value))
                .flatMap(accessToken => {
                  const oldHeaders = operation.getContext().headers;
                  // modify the operation context with a new token
                  operation.setContext({
                    headers: {
                      ...oldHeaders,
                      authorization: `Bearer ${accessToken}`,
                    },
                  });

                  // retry the request, returning the new observable
                  return forward(operation);
                });
            }
          }
        }
        if (networkError) {
          console.log(`[Network error]: ${networkError}`);
          // if you would also like to retry automatically on
          // network errors, we recommend that you use
          // apollo-link-retry
        }
      }
    );
```

So as mentioned ideally I'd like to get each time the access_token expires into above errorLink handler

**Comment by omsharp** [comment]
Hi, @zewa666 
Did you find a way to solve this issue?
I have a similar issue, and I can't find a solution for it.
Regards

**Comment by zewa666** [comment]
my app is using Hasura as BaaS, so uptimately I went with the recommendations from here https://hasura.io/blog/handling-graphql-hasura-errors-with-react/

a specific `invalid-jwt` error occurs which one can listen to:

```
const errorLink = onError(
      ({ graphQLErrors, networkError, operation, forward }) => {
        if (graphQLErrors) {
          for (const err of graphQLErrors) {
            switch (err.extensions.code) {
              case "invalid-jwt": {
                const oldHeaders = operation.getContext().headers;
                operation.setContext({
                  headers: {
                    ...oldHeaders,
                    Authorization: `Bearer ${localStorage.getItem("token")}`
                  },
                });

                return forward(operation);
              }
            }
          }
        }
        if (networkError) {
          // console.log(`[Network error]: ${networkError}`);
        }
      }
    );
```

moreover this didnt work with websocket subscriptions so I worked around by forcefully closing and re-opening them to obtain the new jwt header:

```
this.refreshInterval = setInterval(() => {
      refreshAccessToken().then(token => {
        this.wsClient.close(false, false);

        setTimeout(() => {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          (this.wsClient as any).connect();
        }, 1000);
      });
    }, (1000 * 60 * (15 - 3)));
```

**Comment by omsharp** [comment]
I just figured something out for my problem.
Instead of using the onError link I just use a custom fetch function, and in is I handle the authentication error accordingly. It's working like a charm. At least for now!

`  const customFetch = async (
    uri: RequestInfo,
    options: RequestInit | undefined
  ) => {
    const response = await fetch(uri, options);
    const bodyJson = await response.json();
    if (
      bodyJson &&
      bodyJson.errors &&
      bodyJson.errors[0] &&
      bodyJson.errors[0].message === 'Unauthorized'
    ) {
      return refresh().then((userData) => {
        if (userData) {
          // success: set the access token in the current header
          if (options?.headers) {
            options.headers = {
              ...options?.headers,
              authorization: `Bearer ${userData.accessToken}`,
            };
          }
          // refetch with the new access token
          return fetch(uri, options);
        } else {
          // failed: move to login screen and logout user
          history.push('/login');
          return fetch(uri, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              query: `
                query {
                  logout
                }
              `,
              variables: {},
            }),
          });
        }
      });
    }

    // no error - repackage and return the current response
    return new Response(JSON.stringify(bodyJson), options);
  };`
