### ISSUE TITLE
[network-only] Unwanted query refetch after mutation breaks user experience

### ISSUE THREAD

**Issue by strblr** [apollographql/apollo-client#7485]
To illustrate the problem, here is a very simple example : Using the `network-only` policy, I fire a `todos` query to get a list of `Todo`s. Then, I make each item selectable via an update mutation that takes some arguments and returns the updated `Todo`.

**Intended outcome:**
When firing the update mutation on an item and getting an updated response back, it should just quietly update the corresponding `Todo` in the cache, and trigger a rerender for the `todos` query. As it did in Apollo Client 2.

**Actual outcome:**
It does rerender the list, yes. However, it **also** triggers a complete refetch of `todos`, which is totally unwanted and considerably damages the user experience.

This is actually a major issue in some of my projects that I have to update for my clients. I just cannot migrate to version 3 and after a bit of research, I found some seemingly related topics (revolving around `cache-and-network` though) but none of the proposed solutions worked in my case : 

- https://github.com/apollographql/apollo-client/issues/6760
- https://github.com/apollographql/apollo-client/issues/7068
- https://github.com/apollographql/apollo-client/issues/7105

**How to reproduce the issue:**
- **[CodeSandbox Link](https://codesandbox.io/s/youthful-dust-xe07b?file=/src/Todos.tsx)** 
Click on one of the checkboxes, and watch as the first spinner activates under the updated item. This is the loading state of the update mutation. When it finishes, the global spinner on the list activates. This is the loading state of the `todos` query. Should not happen.

**Versions**
@apollo/client: ^3.3.6 => 3.3.6

**Comment by ostrebler** [comment]
@mlarcher Exactly like `previousData` was a quick patch for a this [widely unpopular PR](https://github.com/apollographql/apollo-client/pull/6566).

**Comment by marwan38** [comment]
I was encountering this exact issue and was able to fix it by making sure that the mutation result EXACTLY matches the query. IE: If a query asked for 
```
query {
  Product {
    ID
    Title
  }
}
``` 
Which is quite annoying as mutation fields aren't always part of the complete query fields. This also affected the apollo internals on how it was storing the response of the mutation. I realised that it wasn't actually making an object in the store.

**Comment by hampusborgos** [comment]
@strblr / @mlarcher Do you know if there has been any solution to this issue? It causes significant amounts of unnecessary refetching.

**Comment by benjamn** [comment]
@strblr Thanks to your [reproduction](https://codesandbox.io/s/youthful-dust-xe07b?file=/src/Todos.tsx), I'm fairly confident this issue can be resolved by updating to `@apollo/client@3.6.0-beta.10` or later ([for example](https://codesandbox.io/s/autumn-platform-n7gckf)), thanks to PR #9504 (which applies to all results broadcast from cache updates, not just `fetchMore` results). Please try running `npm i @apollo/client@beta` when you have a chance @hampusborgos @marwan38 @mlarcher @cgorrieri! 🙏

**Comment by benjamn** [comment]
We've merged `release-3.6` into `main` and released PR #9504 in `@apollo/client@3.6.0` just now. That version is still tagged as `next` rather than `latest` on npm, but we will promote it to `latest` after some final testing. Thanks for opening this issue and for your patience waiting for the solution to land!
