### ISSUE TITLE
Pagination in apollo client 3

### ISSUE THREAD

**Issue by ravikumarjs-foyernet** [apollographql/apollo-client#7495]
can you share the infinite scroll example of apollo client 3?

**Comment by thispastwinter** [comment]
You would accomplish it with one of the three methods listed in their documenation:

**Comment by thispastwinter** [comment]
You would accomplish it via offset pagination or cursor pagination.

Offset: https://www.apollographql.com/docs/react/pagination/offset-based/
Cursor: https://www.apollographql.com/docs/react/pagination/cursor-based/

If you are using react-native and assuming the component you are using is Flatlist or a variant of, there are two key props that you'll use:  "onEndReached" and "onEndReachedThreshold." The prop "onEndReached" invokes a callback you can pass "fetchMore" to that will trigger your refetch. The latter sets the threshold for when the callback is invoked based on the scroll position of the list.

If you are using the web, you might opt for traditional pagination as it tends to suit web better.

Example: https://medium.com/@srbkrishnan/infinite-scroll-pagination-in-flatlist-with-hooks-and-function-components-c9c08bba23a8

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
