### ISSUE TITLE
useSubscription shouldResubscribe doesn't change loading state

### ISSUE THREAD

**Issue by hanrok** [apollographql/apollo-client#7511]
**Intended outcome:**
I want to resubscribe when a dependency of my component is changing (specifically the `serviceId`). 
I use `shouldResubscribe` to make it happen but when `useSubscription` is asking again to fetch data from the backend the `loading` state remains the same (`false`) and my component is rendering some old stuff.
Is it by design that `loading` is never changing after the initial data response?

The component:
```typescript
const MyComponent: React.FC<{
    serviceId?: number;
}> = ({ serviceId }) => {
    const shouldResubscribe = useShouldResubscribe([serviceId]);
    const { loading, error, data } = useSubscription(
        SERVICE_SUBSCRIPTION,
        {
            variables: { serviceId },
            shouldResubscribe: shouldResubscribe,
        }
    );

    useEffect(() => {
        console.log('shouldResubscribe', shouldResubscribe, data, loading);
    }, [distributionData]);


    return (
        <LoadingWrapper isLoading={loading}>
            <MyAnimationComponent data={data} />
        </LoadingStateWrapper>
    );
};
```

`useShouldResubscribe` is an internal hook that returns `true` when some of the dependencies has been changed.

**Actual outcome:**
Loading is still false no matter if the useSubscription is resubscribe with other variables.

Chrome console log:
```
MyComponent.tsx:507 shouldResubscribe false {mySubscrption: {data: 2, __typename: "TestData"}} false
MyComponent.tsx:507 shouldResubscribe true undefined true
MyComponent.tsx:507 shouldResubscribe false {mySubscrption: {data: 2, __typename: "TestData"}} false
MyComponent.tsx:507 shouldResubscribe false {mySubscrption: {data: 15, __typename: "TestData"}} false
```

**How to reproduce the issue:**
It's very easy to reproduce the issue. 

steps:
1. Create a subscription in server
2. Use `useSubscription` hook with `shouldResubscribe` flag
3. Make something to change `shouldResubscribe` state to `true` then to `false`
4. See that `loading` state is never changing after the first subscription

**Versions**
```
  System:
    OS: macOS 11.1
  Binaries:
    Node: 14.8.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Safari: 14.0.2
  npmPackages:
    @apollo/client: ^3.2.0 => 3.2.0
    @apollo/link-context: ^2.0.0-beta.3 => 2.0.0-beta.3
    @apollo/link-error: ^2.0.0-beta.3 => 2.0.0-beta.3
    @apollo/link-retry: ^2.0.0-beta.3 => 2.0.0-beta.3
    @apollo/link-ws: ^2.0.0-beta.3 => 2.0.0-beta.3
```

**Comment by vendramini** [comment]
@hanrok  did you find how to fix it?

**Comment by hanrok** [comment]
the docs about `shuoldResubscribe` are very poor but after taking a look at the code we found that it's always true and "resubscribe" when any of the variables is changing. `shuoldResubscribe` than need to be constant `true` or `false` - by default `true`.
The issue I encounter wasn't apollo fault so I close it.
