### ISSUE TITLE
readQuery/readFragment not adding __typename for nested fragments (with addTypename=true)

### ISSUE THREAD

**Issue by rigobauer** [apollographql/apollo-client#7513]
**Intended outcome:**
You have a query with a main fragment that has another nested fragment inside. You make the query to the server and you get the `__typename` field in the nested fragment normally. If then you do a `readQuery` of the same query or a `readFragment` of the main fragment, you should get the exact same response than from the server (with the `__typename` field in the nested fragment).

**Actual outcome:**
When you do the `readQuery` of the same query or `readFragment` of the main fragment, the nested fragment doesn't have the `__typename` field.

So a simple thing like this will break the cache...

```
const response = apolloClient.readQuery<GetUser>({ query: GET_USER });

if (response?.user) {
  apolloClient.writeQuery<GetUser>({
    query: GET_USER,
    data: {
      user: {
        ...response.user,
      },
    },
  });
}
```

...because the nested fragment is emptied (`{}`)

**How to reproduce the issue:**

```
fragment SubscriptionData on Subscription {
  id
  duration
  price
}
fragment UserData on User {
  id
  name
  email
  subscription {
    ...SubscriptionData
  }
}
query GetUser {
  getUser {
    ...UserData
  }
}
```

If you make that query to the server, you'll get something like...

```
getUser {
  id: "1234"
  name: "John Smith"
  email: "john.smith@gmail.com"
  subscription: {
    id: "sub_MMFFR_123"
    duration: "year"
    price: 50
    __typename: "Subscription"
  }
  __typename: "User"
}
```

After that, if you do the same query from the cache using `readQuery`, you'll get (notice missing `__typename` in `subscription`)...

```
getUser {
  id: "1234"
  name: "John Smith"
  email: "john.smith@gmail.com"
  subscription: {
    id: "sub_MMFFR_123"
    duration: "year"
    price: 50
  }
  __typename: "User"
}
```

**Versions**
System:
    OS: macOS 11.0.1
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    Yarn: 1.22.4 - ~/Coding/wakingup-web/node_modules/.bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 83.0
    Safari: 14.0.1
  npmPackages:
    @apollo/client: 3.3.6 => 3.3.6 
    apollo: 2.32.0 => 2.32.0 
    apollo-upload-client: 14.1.3 => 14.1.3

**Comment by hwillson** [comment]
If someone can provide a small runnable reproduction that demonstrates this happening with `@apollo/client@latest`, we'll take a closer look. Thanks!
