### ISSUE TITLE
Apollo client cannot receive responses, undescriptive callback trace

### ISSUE THREAD

**Issue by thaotnguyen** [apollographql/apollo-client#7518]
I'm working on https://github.com/taithnguyen/Patchwork, and if I run it locally in either an Android or iPhone emulator, I get "Network request failed" whenever I try to make any requests. 

If I catch the error and log it, I get a really undescriptive error trace that just says there's an error. Also nothing shows up in the iPhone emulator system log and in the network part of the emulator inspector.

 I absolutely cannot figure out how to debug this and I need to to be able to continue working on this. Any help or direction would be greatly appreciated.

**Intended outcome:**

Request either goes through successfully or errors with something in the network tab showing what the response error was.

**Actual outcome:**

https://i.imgur.com/JYV4zgE.png

**How to reproduce the issue:**

1. Clone this repo: https://github.com/taithnguyen/Patchwork
2. cd Patchwork/client && npm i
3. cd ios && pod install
4. cd .. && npm run ios
5. Try to log in with email "tester12@gmail.com" and password "Tester12", or try to sign up at all.
6. You should receive a "Connection failed" and "Network request failed" error message.

**Versions**

  System:
    OS: macOS 11.1
  Binaries:
    Node: 14.15.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.9 - /usr/local/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Safari: 14.0.2
  npmPackages:
    @apollo/client: ^3.1.4 => 3.3.6 

node: v14.15.3
npm: 6.14.9
react-native-cli: 2.0.1
react-native: 0.62.2
expo: 4.0.15
pod: 1.10.0

**Comment by hwillson** [comment]
Discussed (and resolved) in https://github.com/apollographql/apollo-client/issues/1757 - thanks!
