### ISSUE TITLE
How to camelCase my responses' fields and tables?

### ISSUE THREAD

**Issue by benams** [apollographql/apollo-client#7522]
In my frontend application, I consume data with snake_case table and field names, but I want to use camelCases keys across my application. Any known way I can convert the keys to camelCase? I can see that apollo server offers fieldResolver where it can be done(Convert snake_case to camelCase field names in apollo-server-express), but I found no similar option in ApolloClient.

**Comment by benjamn** [comment]
@benams To be honest, I don't have anything easy to suggest. However, you could theoretically write your queries with the desired camel-cased fields, and then insert a custom `ApolloLink` (before the default `HttpLink`) that transforms each server query to use underscores in field names, and then converts all incoming response data from underscores to camel-case:
```ts
new ApolloClient({
  link: new ApolloLink((operation, forward) => {
    return forward({
      ...operation,
      // Make sure this conversion is cached, so you don't have to
      // redo it every time you fetch this query:
      query: convertQueryFieldsToSnakeCase(operation.query),
    }).map(result => {
      return {
        ...result,
        data: convertResultFieldsToCamelCase(result.data),
      };
  }).concat(new HttpLink(...)),
  cache,
})
```
You'd have to implement those `convertQueryFieldsToSnakeCase` and `convertResultFieldsToCamelCase` functions to get this to work, but I think that's a simpler problem than you started with?

**Comment by fc** [comment]
Just a note that the queried fields *must* be aliased as camelcase in the query itself or the data will return `undefined` with no errors coming from Apollo.

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
