### ISSUE TITLE
Property 'statusCode' does not exist on type 'Error | ServerError | ServerParseError'.

### ISSUE THREAD

**Issue by CAIJIN1002** [apollographql/apollo-client#7524]
When I tried example code from "https://www.apollographql.com/docs/react/api/link/apollo-link-context/",
it shows `Property 'statusCode' does not exist on type 'Error | ServerError | ServerParseError'.`,

![image](https://user-images.githubusercontent.com/20751257/103197854-c7d05600-4921-11eb-84d8-06fa7930dfc6.png)

and I tried networkError type change union( | ) to the intersection( & ), that goes to successful!

![image](https://user-images.githubusercontent.com/20751257/103198188-afad0680-4922-11eb-95d1-07c77bb45fb7.png)

![image](https://user-images.githubusercontent.com/20751257/103198240-c94e4e00-4922-11eb-8f9f-97a2024de777.png)

**Comment by devivekw** [comment]
@CAIJIN1002 refer to this [issue](https://github.com/apollographql/apollo-client/issues/7293#issuecomment-731618265)

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
