### ISSUE TITLE
Type policies broken starting 3.3.0

### ISSUE THREAD

**Issue by Banou26** [apollographql/apollo-client#7535]
**Intended outcome:**
Trying to query a typePolicy field should work

**Actual outcome:**
The query is always loading

**How to reproduce the issue:**
Try to query a typePolicy field, e.g

```ts
export default new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        foo: () => 'foo'
      }
    }
  }
})


  // .... in a component
  const { data, ...rest } = useQuery(gql`query Foo { foo @client }`)
  // rest.loading is always true and data is always undefined
```

**Versions**
apollo-client ^3.3.0 / ^3.3.6 / ^3.4 beta

**Comment by pramodshri-tgsys** [comment]
@Banou26 : did you find any work arounds for this issue? until the fix come in?

**Comment by Banou26** [comment]
@pramodshri-tgsys I downgraded my ApolloClient version to 3.2.8.
If you found any real workarounds I'd like to know too :)

**Comment by pramodshri-tgsys** [comment]
In my case, there was an error in the code but no errors were reported. I didn't have a return statement at the end of the function code.

**Comment by benjamn** [comment]
@Banou26 This would be pretty worrisome if true, but it does not seem to be reproducing for me.

The symptoms are consistent with there not being a field policy defined for the `foo` field. Can you double-check that your actual field name is spelled the same everywhere, and that the `InMemoryCache` object you're configuring and exporting is the same `cache` that gets used by the `ApolloClient` behind the `useQuery` call?

Of course, a [reproduction](https://github.com/apollographql/react-apollo-error-template) would be even more useful.

**Comment by Banou26** [comment]
@benjamn Well, for for I tested, they are indeed broken, here is the smallest repro I managed to get.

```ts
import { InMemoryCache, ApolloClient, gql } from '@apollo/client'

const cache = new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        foo: () => 'foo'
      }
    }
  }
})

cache.policies.addTypePolicies({
  Query: {
    // If you uncomment those, the logs will return undefined
    // fields: {
    //   settings: () => {}
    // }
  }
})

const client = new ApolloClient({
  cache
})

console.log(client.query({ query: gql` { foo } ` }))

// results of commented typePolicies

// Promise {<pending>}
// __proto__: Promise
// [[PromiseState]]: "fulfilled"
// [[PromiseResult]]: Object
// data: {foo: "foo"}
// loading: false
// networkStatus: 7


// results of uncommented typePolicies
// Promise {<pending>}
// __proto__: Promise
// [[PromiseState]]: "fulfilled"
// [[PromiseResult]]: undefined
```

It seems like it's due to the use of `cache.policies.addTypePolicies`

**Comment by Remownz** [comment]
I can confirm. We also use multiple `cache.policies.addTypePolicies`. We also have to downgrade to 3.2.x.

**Comment by Banou26** [comment]
@benjamn Any updates on this ?
Still a bug on `3.3.15` which prevents anyone using `cache.policies.addTypePolicies` to upgrade above `3.2`.
