### ISSUE TITLE
Cannot query function with boolean optional param, passed NULL instead of boolean value

### ISSUE THREAD

**Issue by sashberd** [apollographql/apollo-client#7541]
I have function in Postgres with optional params:
```
create or replace FUNCTION public.myFunction(
   language integer, 
   app_type integer, 
   user uuid, 
   level integer default null, 
   status  integer default null,  
   is_hidden boolean default null) RETURNS SETOF json
  LANGUAGE plpgsql STABLE STRICT SECURITY DEFINER
  AS $_$
 begin
    return query 
select json_build_object(
        'rowId', p.id,
        'projectId', p.short_id, 
        'name', p.name,
        'level', pd.level, )
from public.project p join types t on p.type = t.type
join public.project_data pd on pd.project = p.id
join public. project_config cfg on cfg.project = p.id
where p.language = $1 and 
     ($5 IS NULL OR p.status = $5) and 
     p.type = $2 and 
     ($4 IS NULL OR pd.level = $4) and 
     ($6 IS NULL OR cfg.is_hidden = $6);
end;
$_$;
```

This query linked to apollo-client via next gql:
```
export default gql`
  query getDataForProjectList(
    $language: Int!
    $type: Int!
    $user: Uuid!
    $level: Int
    $isHidden: Boolean
    $status: Int
    $first: Int!
  ) {
    myQuery(
      isHidden: $isHidden
      language: $language
      type: $type
      user: $user
      level: $level
      status: $status
      first: $first
    ) {
      myQueryResponse: nodes
    }
  }
`;
```
In browser network I see that param sends like {..., "isHidden":false...},however, Boolean param does not arrives to Postgres function above , result looks like passed param is NULL.

I use apollo-client v3.2.5.

Is it bug in apollo-client or such queries with boolean values not possible via Postgres?

**Comment by benjamn** [comment]
@sashberd This sounds like a problem somewhere between the client and the server/DB, rather than in Apollo Client or your application code. My first guess is that maybe `args.isHidden` is not getting successfully mapped to the `is_hidden` function parameter, since the name is in a different format (camel case vs. underscores)? If you can track down the server-side code that's responsible for creating the Postgres query that calls `myFunction` (using arguments derived from the GraphQL query), maybe you'll notice it's doing something strange?

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!

**Comment by sashberd** [comment]
@hwillson Latest means which version in was fixed?

**Comment by hwillson** [comment]
@sashberd I meant if you're still seeing this issue with `@apollo/client@latest` (`latest` as of right now is `3.3.19`), definitely let us know!
