### ISSUE TITLE
Get networkError status code when request failed to fetch

### ISSUE THREAD

**Issue by HarrisonHenri** [apollographql/apollo-client#7542]
**Intended outcome:**

Obtain the status code when there is a network error.

**Actual outcome:**
The request is falling to fetch.

**How to reproduce the issue:**
In insomnia my graphene-flask api is returning status 422 or 502.

**Versions**
  System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.88
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.66)
  npmPackages:
    @apollo/client: ^3.0.2 => 3.0.2
    apollo-upload-client: ^14.1.2 => 14.1.2

**Comment by prinse1545** [comment]
I have a similar issue when upgrading from Apollo-client and @apollo/react-hooks to @apollo/client. The request just times out with a 502 and never reaches the server. Did you ever solve this?

**Comment by HarrisonHenri** [comment]
Hello @prinse1545 . Sorry but I did not solve this problem yet.

**Comment by hwillson** [comment]
If someone can provide a small runnable reproduction that demonstrates this happening with `@apollo/client@latest`, we'll take a closer look. Thanks!
