### ISSUE TITLE
Apollo client freezes the browser when updating the cache with JSON types

### ISSUE THREAD

**Issue by brussev** [apollographql/apollo-client#7545]
**Intended outcome:**
I am using Apollo client and in memory cache to deal with entities in my react js app. One of my entities have json field which is nullable but usually there are array in similar format: `[{ key: 'test', value: 'www.test1.com'},{ key: 'test2', value: 'www.test2.com'}]`. I use custom update function that takes the result from my Apollo gateway and do cache.writeQuery(...). Everything worked smoothly until we started to update the json column - the browser (Google Chrome Version 87.0.4280.88 (macOS). Once we add something in this column - in 90% of the cases the browser freezes, without any error or warning. I tried everything in the type policies shown in the documentation but any custom merge function or other works.. Basically all that should happen is to replace the incoming with the existing array of objects.
I am using in my app simple json objects as entity properties and there were not a single issue with the cache but I guess now when its a array of objects - something is wrong?

Sorry for not giving more code but I don't know what can be send.. its just updating an entity json object.
```
                Entity: {
                    fields: {
                        mediaUri: {
                            merge(existing, incoming, { mergeObjects }) {
                                return incoming;
                            }
                        }
                    }
                }
```

`
export const updateHook = () => {
    return useMutation(UPDATE_ENTITY_GQL);
};
`

**Actual outcome:**
Browser freezes and its impossible to even refresh - new tab is needed to be open with the same link..
No error or warning in the console.

**How to reproduce the issue:**
Try to update JSON objects in some of you entities.

**Versions**
apollo client - 3.3.2
Chrome Version 87.0.4280.88
macOS Big Sur 11.0.1

**Comment by AlexandrDubovchenko** [comment]
How did you fix it? I have the same problem
