### ISSUE TITLE
Unable to pass enum values in variables

### ISSUE THREAD

**Issue by MitchK** [apollographql/apollo-client#7562]
**Intended outcome:**

I am able to pass a TypeScript enum value to a mutation or query.

**Actual outcome:**

`apollo-client` appears to convert an enum value to a lower-case string, resulting in a type error.

> GraphQL error: Expected a value of type "CommunityType" but received: "company"

**How to reproduce the issue:**

GraphQL Schema:

```graphql
enum CommunityType {
  INTEREST
  COMPANY
  INDUSTRY
}
...
extend type Mutation {
  createCommunity(name: String!, type: CommunityType): Community
}
```

Mutation:

```graphql
mutation CreateCommunity($name: String!, $type: CommunityType) {
  createCommunity(name: $name, type: $type) {
    id
    name
    type
  }
}
```

Generated typescript types (using `apollo`)

```typescript
export interface CreateCommunity_createCommunity {
  __typename: "Community";
  id: string | null;
  name: string | null;
  type: CommunityType | null;
}

export interface CreateCommunity {
  createCommunity: CreateCommunity_createCommunity | null;
}

export interface CreateCommunityVariables {
  name: string;
  type?: CommunityType | null;
}

...

/**
 * CommunityType
 */
export enum CommunityType {
  COMPANY = "COMPANY",
  INDUSTRY = "INDUSTRY",
  INTEREST = "INTEREST"
}
```

Calling the mutation:

```typescript
 const [create, {
    loading,
    error,
  }] = useMutation<CreateCommunity, CreateCommunityVariables>(CREATE_COMMUNITY, {
    variables: {
      name: 'Test',
      type: CommunityType.COMPANY,
    },
  });
```

**Versions**

I encountered the same issue with apollo-client 2.x. I upgraded to apollo-client 3.3.6 and having the same issue.

```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 12.15.0 - ~/.nvm/versions/node/v12.15.0/bin/node
    Yarn: 1.22.10 - ~/XXX/node_modules/.bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.15.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.141
    Safari: 14.0
  npmPackages:
    @apollo/client: ^3.3.6 => 3.3.6 
    @apollo/react-testing: ^3.1.1 => 3.1.4 
    apollo: ^2.32.0 => 2.32.0
 ```

**Comment by gilnd** [comment]
+1
I'm having the same issue, is there any temporary solution ?

**Comment by bignimbus** [comment]
Hi folks, apologies for the delay on this. @MitchK I don't know if there's enough information provided to narrow down the source of the issue you experienced.  I'm closing the issue since it's pretty stale, please do feel free to post in our [community forum](https://community.apollographql.com/).  Thanks so much 🙏🏻
