### ISSUE TITLE
errorLink refresh token multiple simultaneously queries 

### ISSUE THREAD

**Issue by EhsanSarshar** [apollographql/apollo-client#7570]
when token expired I handle it inside errorLink and request for new token from a rest api and then forward new headers to httpLink again.
but as I am getting new refresh token I want to pause all other queries. until new tokens are fetched.

**Comment by Fxlr8** [comment]
Why did you close it? Have you found the solution? Could you share it?

**Comment by ricardo-rp** [comment]
@TheEhsanSarshar I'm having the same issue. Did you manage to find a good solution?

**Comment by TheEhsanSarshar** [comment]
@ricardo-rp put all the new queries inside a queue ( array ) and then execute each of them.

https://gist.github.com/Yasir5247/58866e4fc269b124bcf11c8aa3cd4921?permalink_comment_id=4288811#gistcomment-4288811

**Comment by ricardo-rp** [comment]
@TheEhsanSarshar I actually managed a very simple implementation with no queue, subscribing the `forward(operation)` to the fetch promise observable:

```
let refreshPromise: Promise<void> = Promise.resolve();

export const authErrorLink = onError(
    ({ graphQLErrors, operation, forward }) => {
        if (graphQLErrors?.some(err => err.message === "Unauthorized")) {
            if (!isRefreshing) {
                refreshPromise = getNewToken();
            }

            return fromPromise(refreshPromise).flatMap(() =>
                forward(operation)
            );
        }
    }
);
```
