### ISSUE TITLE
cache.identify : Index signature is missing in type

### ISSUE THREAD

**Issue by jimmycrequer** [apollographql/apollo-client#7577]
**related to**

#6083

**Intended outcome:**

I want to retrieve the Apollo Client cache ID for a particular object.

```ts
interface MyMapInterface {
  __typename: "Map";
  id: string;
  width: number;
  height: number;
}

const myMap: MyMapInterface = { __typename: "Map", id: "1", width: 100, height: 100 };

client.cache.identify(myMap);
```

**Actual outcome:**

I get the following TS error.

```
Argument of type 'MyInterface' is not assignable to parameter of type 'StoreObject | Reference'.
  Type 'MyInterface' is not assignable to type 'StoreObject'.
    Index signature is missing in type 'MyInterface'.
```

**How to reproduce the issue:**

[Playground](https://www.typescriptlang.org/play?#code/PTAEDMCcHsFtQM4BdqQKYFUkEsA2CA6AEwKQQFgAoEUASVHQAdcBDAYzSNAGUV0A1FrgCuaUNABGAKzRskoAO7YkAC1DskwoaCQBPRmgQRUOlWIQsA1mOjhE2WM2xtluqtgB2SNJHDsxvKhoAPLSsvIA3lSgMaAA+nF6Bh4ssGgA-ABciEiQngDmANzRsQDayEEAYthouEQAcqlo2ch5HvkAutkewrASPqAAPjlt+UOgwh5EaOCenIWgNIECQqJUAL5U7l4+fhygALK6ByyMtDu+-qBRlDEJSWgpadkARCeML8W3oNhELbkFL4xJREVTdXr9SBA0BmbD5FRIcF9HxfTaUKhsaAeZCgWDHU7ZI7vc7eS77AC813iiX0jyar3eLwAND8-qAXgBGZmKX5g0AcgAMApZsPhiP5QtA6y+W0omOx8jxoSk2WWITCclAlLx7yoQA)

**Versions**

```
  System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 15.5.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\Documents\workspace\GOunite\v3\client\node_modules\.bin\yarn.CMD
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.88
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.75)
  npmPackages:
    @apollo/client: 3.3.6 => 3.3.6
    @apollo/link-context: 2.0.0-beta.3 => 2.0.0-beta.3
    @apollo/link-error: 2.0.0-beta.3 => 2.0.0-beta.3
    @apollo/link-persisted-queries: 1.0.0-beta.0 => 1.0.0-beta.0
    @apollo/link-ws: 2.0.0-beta.3 => 2.0.0-beta.3
    @apollo/react-testing: 3.1.4 => 3.1.4
    apollo: 2.32.1 => 2.32.1
    apollo-cache-persist: 0.1.1 => 0.1.1
    apollo-upload-client: 14.1.0 => 14.1.0
```

TS 4.1

**Comment by benjamn** [comment]
@jimmycrequer Hmm, it's disappointing that TypeScript is so strict about this, since `MyMapInterface` definitely seems compatible with `StoreObject` (as far as `cache.identify` is concerned):
```ts
export interface StoreObject {
  __typename?: string;
  [storeFieldName: string]: StoreValue;
}
```
As a workaround, you might try adding a `[key: string]: any` field to `MyMapInterface`, to make it look more like `StoreObject`. I realize that's not ideal, but it could get you unstuck for now.

On the implementation side, I'm open to relaxing the `cache.identify` parameter type to something like `object`, since it can always fail (return undefined) for objects that are not identifiable.

**Comment by AdrienLemaire** [comment]
> As a workaround, you might try adding a [key: string]: any field to MyMapInterface, to make it look more like StoreObject. I realize that's not ideal, but it could get you unstuck for now.

This is a bit difficult when using auto-generated codegen types from neo4j-graphql-js.
@benjamn @johnymontana  would it be appropriate to ask neo4j-graphql-js to export types with `[storeFieldName: string]: StoreValue;` by default ?

**Comment by rylanc** [comment]
The same issue exists if the interface passed is generated by the [Apollo CLI](https://github.com/apollographql/apollo-tooling) (e.g. using an object returned in the data of a mutation). For best compatibility between Apollo created tools, it seems like changing the parameter type might be the best fix.

**Comment by jcf120** [comment]
Any updates? Would be lovely if I didn't have to cast anymore :)

**Comment by PeterDekkers** [comment]
It's possible to circumvent the issue also by using spread syntax:
```typescript
client.cache.identify({ ...myMap });
```

There is a related [issue](https://github.com/microsoft/TypeScript/issues/15300) in the Typescript repo.

**Comment by phryneas** [comment]
This is unfortunately a difference between TypeScript `type` and `interface` declarations - a `type` will always work, but an `interface` will not be accepted as it is missing that implicit index signature

Apollo Client is now exporting the `AsStoreObject` type from `@apollo/client/utilities` as a workaround:
```ts
const myMap: AsStoreObject<MyMapInterface> = ...
```

(Alternatively you could declare `MyMapInterface` as a `type`, not an `interface`.)

I believe that's all we can do on our side, so I'll close this issue :)
