### ISSUE TITLE
MockedProvider Could not find "client"

### ISSUE THREAD

**Issue by VadymBoguslavsky** [apollographql/apollo-client#7578]
Updated to @apollo/client/testing from @apollo/react-testing.
Changed import { MockedProvider } from '@apollo/client/testing';
Still we have an error while running jest tests "Invariant Violation: Could not find "client" in the context or passed in as an option. Wrap the root component in an <ApolloProvider>, or pass an ApolloClient instance in via options."

```
import React from 'react';
import TestRenderer, { act } from 'react-test-renderer';
import { MockedProvider } from '@apollo/client/testing';
import { shallow } from 'enzyme';
import { I18nextProvider } from 'react-i18next';
import listCard from '../../components';
import { MockedCard } from '../mockFn/MockData';
import { somequery } from '../../queries';
import i18n from '../mockFn/Mocki18n';

const data = { ...MockedData };

const mocks = [
  {
    request: {
      query: somequery
    },
    result: { data }
  }
];
describe('listCard', () => {
  const listCard = (
    <MockedProvider mocks={mocks} addTypename={false}>
      <I18nextProvider i18n={i18n}>
        <listCard {...MockedCard} />
      </I18nextProvider>
    </MockedProvider>
  );

  it('renders correctly', async () => {
    let wrapper;
    await act(async () => {
      wrapper = TestRenderer.create(listCard);
    });
    const tree = wrapper.toJSON();
    expect(tree).toMatchSnapshot();
  });
```

Of cource when still using @apollo/react-testing before updating to 4.0 this bug cannot be reproduced
@apollo/react-testing was removed, yarn.lock cleared like node modules.

Any help appreciated.

**Comment by jcreighton** [comment]
@VadymBoguslavsky I've been unable to reproduce the error. Could you create a runnable [reproduction](https://codesandbox.io/s/github/apollographql/react-apollo-error-template)?

**Comment by Infonautica** [comment]
Do you use GraphQL Codegen?

I had this problem last week. My problem was in graphql-codegen, which generate executable hooks and HOCs from different apollo package. Solution was to indicate in codegen config exact apollo package to extract apollo from:
```
apolloReactHocImportFrom: '@apollo/client'
apolloReactHooksImportFrom: '@apollo/client'
```

After that i search in my project for usage of different apollo packages (react-hooks, boost and other) and replace them all with '@apollo/client'

**Comment by jcreighton** [comment]
@VadymBoguslavsky Any update on this?

**Comment by VadymBoguslavsky** [comment]
@jcreighton Sorry for a late reply, found what was causing this issue, it seems that even one of @apollo/client dependencies can provide an error. I forgot to remove apollo-link-inmemorycache and already installed @apollo/client, thought we have a problems now with inmemorycache but the MockedProvider working fine now. Thank you and sorry for disturbance.
