### ISSUE TITLE
Upgrade from apollo-client 2.6.10 breaks schema link mocking

### ISSUE THREAD

**Issue by chhschou** [apollographql/apollo-client#7588]
**Intended outcome:**
Schema link resolver should be called to return data after migration.

Before: (schema.json is an introspection schema downloaded from the server)

```
import { addResolveFunctionsToSchema } from 'graphql-tools';
import { buildClientSchema } from 'graphql/utilities';
import { resolvers } from '../../mock/resolvers/resolvers';
import schema from '../../schema/schema.json';
import { SchemaLink } from 'apollo-link-schema';

export default () => {
  // @ts-ignore:
  const executableSchema = buildClientSchema(schema);

  addResolveFunctionsToSchema({
    schema: executableSchema,
    resolvers
  });

  const schemaLink = new SchemaLink({ schema: executableSchema });
  return schemaLink;
};

```

After:

```
import { addResolversToSchema } from 'graphql-tools';
import { buildClientSchema } from 'graphql';
import { resolvers } from '../../mock/resolvers/resolvers';
import schema from '../../schema/schema.json';
import { SchemaLink } from '@apollo/client/link/schema';

export default () => {
  // @ts-ignore:
  const executableSchema = buildClientSchema(schema);

  const schemaWithMocks = addResolversToSchema({
    schema: executableSchema,
    resolvers
  });

  const schemaLink = new SchemaLink({ schema: schemaWithMocks });
  return schemaLink;
};
```

resolvers:

```
Query: { ... },
Mutation: { ... }

```

**Actual outcome:**
Jest test hangs when trying to do mutations.

**How to reproduce the issue:**

**Versions**
  System:
    OS: macOS 11.1
  Binaries:
    Node: 14.15.3 - ~/.asdf/installs/nodejs/14.15.3/bin/node
    Yarn: 1.22.10 - ~/Documents/megablue-apps-meta-feature-apollo-v3/web/node_modules/.bin/yarn
    npm: 6.14.9 - ~/.asdf/installs/nodejs/14.15.3/bin/npm
  Browsers:
    Chrome: 87.0.4280.141
    Safari: 14.0.2
  npmPackages:
    @apollo/client: 3.3.6 => 3.3.6
    @apollo/react-testing: 3.1.3 => 3.1.3
    apollo: 2.31.1 => 2.31.1

**Comment by hwillson** [comment]
We'll need a runnable reproduction (using `@apollo/client@latest`) to be able to troubleshoot this further. Thanks!

**Comment by teytey12** [comment]
> We'll need a runnable reproduction (using `@apollo/client@latest`) to be able to troubleshoot this further. Thanks!
