### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

### ISSUE THREAD

**Issue by xariusdrake** [apollographql/apollo-client#7590]
**Intended outcome:**

Display Login form and insert data with Graphql on Expo

**Actual outcome:**

![Screenshot_20210118-235144](https://user-images.githubusercontent.com/22252984/104943429-53e91100-59e8-11eb-97c5-59c348b5dd8c.png)

**How to reproduce the issue:**

src/App.js
![Screen Shot 2021-01-18 at 11 54 51 PM](https://user-images.githubusercontent.com/22252984/104943676-b215f400-59e8-11eb-855a-e8d871dfa995.png)
Display Login form and insert data with Graphql on Expo React
src/ApolloClient.js
![Screen Shot 2021-01-18 at 11 55 05 PM](https://user-images.githubusercontent.com/22252984/104943685-b510e480-59e8-11eb-83d7-c38f0a7fc064.png)
src/screens/Home.js
![Screen Shot 2021-01-18 at 11 55 31 PM](https://user-images.githubusercontent.com/22252984/104943690-b7733e80-59e8-11eb-9b07-83f536b1fe76.png)
src/screens/Auth/Login.js
![Screen Shot 2021-01-18 at 11 55 40 PM](https://user-images.githubusercontent.com/22252984/104943700-b9d59880-59e8-11eb-8d5d-049a64af4eb8.png)

**Versions**

  System:
    OS: macOS 11.1
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
  Browsers:
    Chrome: 87.0.4280.141
    Firefox: 84.0.2
    Safari: 14.0.2
  npmPackages:
    @apollo/client: ^3.3.7 => 3.3.7
    @apollo/react-hooks: ^4.0.0 => 4.0.0
    apollo-boost: ^0.4.9 => 0.4.9
    apollo-cache-inmemory: ^1.6.6 => 1.6.6
    apollo-link: ^1.2.14 => 1.2.14
    apollo-link-context: ^1.0.20 => 1.0.20
    apollo-link-error: ^1.1.13 => 1.1.13
    apollo-link-http: ^1.5.17 => 1.5.17
    react-apollo: ^3.1.5 => 3.1.5

**Comment by xariusdrake** [comment]
I also use function in Login.js, but it doesn't work. But when I remove the line remove from 44 to 58. It works, don't understand why
![Uploading Screen Shot 2021-01-19 at 12.55.06 AM.png…]()

**Comment by jcreighton** [comment]
@xariusdrake The error you screenshotted refers to an issue with a React component and as the commented out lines in your second screenshot aren't Apollo Client-related, this is unlikely an issue with Apollo Client. (I could be mistaken but I think you want to import `TextInput` instead of `Input`.)
