### ISSUE TITLE
Reactive vars stop broadcasting changes to cache when query became inactive and active again (e.g. via navigation)

### ISSUE THREAD

**Issue by WojciechKulpa** [apollographql/apollo-client#7593]
**Intended outcome:**
Changes made to local state managed with reactive variables should trigger update on every active query that depends on that variable. No matter if that was previously deactivated.

**Actual outcome:**
If query was deactivated and activated again update notification is no longer triggered.

**How to reproduce the issue:**
[CodeSandbox](https://codesandbox.io/s/apollogqlstatereactivevars-3u1op?file=/src/Home.js)

1. Click button "Click to increment" several times - change notification is broadcasted and component is re-rendered with good counter.
2. navigate to "About" and go back to "Home"
3. Click button again several times - **no update**
4. If we now navigate again to "About" and back to "Home" all works good again and in fact we are back at step one.

Based on my research I see that when query is deactivated cache is detached from reactive variable (forgetCache) but when it is activated again cache is not attached again as it is done in initial render or after second navigation. 

P.S. That works good if we are using useReactiveVar hook.

**Versions**
reproduced with: 3.3.6, 3.3.7

**Comment by benjamn** [comment]
@WojciechKulpa Thanks for the reproduction. I'll take a look at this soon (this week).

**Comment by lassesteffen** [comment]
Any updates on this? We are facing the same issue and are looking forward to a fix for that! :)

**Comment by jcreighton** [comment]
@benjamn Cool if I re-assign this to myself? There's another issue related to reactive vars (#7609) that I'm going to look into, so might as well look into this too.

**Comment by benjamn** [comment]
@WojciechKulpa Thanks to your reproduction, I can confirm that this is fixed in `@apollo/client@3.3.8` (just published).
