### ISSUE TITLE
Unable to Locate Apollo V1 to V2 migration guide

### ISSUE THREAD

**Issue by javedbartlett** [apollographql/apollo-client#7594]
I'm unable to Locate Apollo V1 to V2 migration guide. I'm in the process of upgrading from V1 to V3 and it'd be really helpful, but I can't find it.

**Comment by hwillson** [comment]
We don't have a V1 to V2 migration guide active anymore unfortunately. You can probably find something in the repo history, but I would recommend starting fresh with V3 if possible.
