### ISSUE TITLE
How to useQuery with variables from inputs and button?

### ISSUE THREAD

**Issue by AAIING** [apollographql/apollo-client#7600]
I need passing variables from inputs and button to useQuery  
Formik does not acept useQuery with send method
`const MyApp = () => {

  //resultado de consulta (query) con apollo client..
  const {data, loading, error} = useQuery(OBTENER_USUARIO, {
        variables: {rut_usuario: 17445628, verificador_usuario: "3"}                
  });`

**Comment by rodgoeliz** [comment]
- If you need to call a query on bottom press you need to `useLazyQuery`
- if you need refetch on state change you can use arguent `refetch` from `useQuery`


https://www.apollographql.com/docs/react/data/queries/

**Comment by jcreighton** [comment]
Closing as @rodgoeliz answered your question!
