### ISSUE TITLE
Update in reactive vars do NOT cause expected re-renders in 3.3.7 (regression)

### ISSUE THREAD

**Issue by delyanr** [apollographql/apollo-client#7609]
**Intended outcome:**
Updates to reactive vars in one component should trigger re-renders across all other components that are listening to the said reactive vars. I've tested this using `useReactiveVar` - not sure if the issue also occurs when using `useQuery` with the `@client` directive.

**Actual outcome:**
Other components are not being re-rendered, and thus are using stale data.

**How to reproduce the issue:**
This could be related to #7593, although the issue described here occurs only in the latest v3.3.7. (So it's a regression!)

Please use the following link for reproduction: [codesandbox](https://codesandbox.io/s/apollo-client-stale-usereactivevar-qw4d7)

Refresh the page and see that the two components show different data for the reactive variable. One of the components triggers an update to the reactive var via `useEffect`, which in turn does not cause a re-render to the other component.

Change the apollo-client version back to 3.3.6, and see that this no longer happens.

**Versions**
React: v16.14.0 - v17.0.1
Apollo-client: v3.3.7

**Comment by benjamn** [comment]
@delyanr Thanks to your reproduction, I can confirm that this is fixed in `@apollo/client@3.3.8` (just published).
