### ISSUE TITLE
Apollo Client keeps the list of all executed mutations in mutationStore and never cleans it

### ISSUE THREAD

**Issue by smykhailov** [apollographql/apollo-client#7616]
Each executed mutation stays in the `mutationStore` forever, it might cause memory leaks.
Apollo needs to clean the `mutationStore` records when mutations is done.

**Comment by benjamn** [comment]
@smykhailov Starting in `@apollo/client@3.3.0`, thanks to commit ad4be6e31b24daa14d7cfa55221707af30bb0e54 in https://github.com/apollographql/apollo-client/pull/7161, we no longer create the `queryManager.mutationStore` unless it's being used by devtools, so I think this may not be a problem any longer, if you update?

**Comment by smykhailov** [comment]
Thank you @benjamn, we use it in our custom DevTools and realized this problem. Great to hear it doesn't cause any issue in production code. You can close the issue, we can manage this in our DevTools by ourselves.
