### ISSUE TITLE
Can I use 2 query at the same time in grphql with Apollo Client? 

### ISSUE THREAD

**Issue by mshshuvooo** [apollographql/apollo-client#7619]
Hello mates. Can I use 2 query at the same time in grphql? I want to store my query in two variables and I then I want to use them in grphql. How can I do this? Please give a suggestion. Here is my code:  https://pastebin.com/P2mWhPbi?fbclid=IwAR1iq7biHkmUxAh3qtlSMcDk9_zqI86UmtSryKz4ojRjkBVam0AEjRwmI_Q

**Comment by JayBee007** [comment]
The approach your using will result in an error, something like the below one:

`react-apollo only supports a query, subscription, or a mutation per HOC. [object Object] had 2 queries, 0 subscriptions and 0 mutations. You can use 'compose' to join multiple operation types to a component`

A better way, **_as far as  I understand_**, would be to just add both the queries under a single query. Please correct me, if am wrong

For ex: 

`query MyQuery1 {
  headermenu: menuItems(where: {location: HEADER}) {
    edges {
      node {
        label
      }
    }
  footermenu: menuItems(where: {location: FOOTER}) {
    edges {
      node {
        label
      }
    }
  }
  }`

**Comment by mshshuvooo** [comment]
Hello, @JayBee007 Thanks for your comment. Yes, you are right. But I want to make the query using multiple variables. I don't know is it possible or not.
