### ISSUE TITLE
Unexpected end of JSON input and 401 error with a custom provider and auth0 token 

### ISSUE THREAD

**Issue by Razi321** [apollographql/apollo-client#7625]
i created a wrapper   for apollo provider to be able to pass the token from auth0 and i tried to call a graphql api but i got 401 error , i'm sure i,m passing the token correctly ad i tried it in the backend and ut works but no clues why i got this error

**AuthorizedApolloProvider.js ( my wrapper ) :**  
```
import React from 'react';
import { ApolloClient, ApolloProvider, createHttpLink, InMemoryCache } from '@apollo/client';
import { setContext } from "apollo-link-context" ;
import { useAuth0 } from "@auth0/auth0-react";

const AuthorizedApolloProvider = ({ children }) => {
    const {  getAccessTokenSilently } = useAuth0();

  const httpLink = createHttpLink({
    uri: process.env.REACT_APP_API_BACK , 
    fetchOptions: { mode: 'no-cors', },
  });

  const authLink = setContext(async () => {
    const accessToken = await getAccessTokenSilently()
    console.log(accessToken)
    return {
      headers: {
        Authorization: `Bearer ${accessToken}`,
       
      }
    };
  });
  
  const apolloClient = new ApolloClient({
    link: authLink.concat(httpLink),
    cache: new InMemoryCache(),
    credentials: 'include',
  });

  return (
    <ApolloProvider client={apolloClient}>
      {children}
    </ApolloProvider>
  );
};

export default AuthorizedApolloProvider;
```

error in the UI : 
<img width="508" alt="Screen Shot 2021-01-28 at 18 39 28" src="https://user-images.githubusercontent.com/38192665/106119137-33fbdf00-6198-11eb-9dfd-17448c25ee0f.png">

console errors : 
<img width="1333" alt="Screen Shot 2021-01-28 at 18 41 01" src="https://user-images.githubusercontent.com/38192665/106119333-6dcce580-6198-11eb-9b7f-bc655244ae65.png">

<img width="1352" alt="Screen Shot 2021-01-28 at 18 40 39" src="https://user-images.githubusercontent.com/38192665/106119350-72919980-6198-11eb-8354-0394fe9c1b63.png">

if i delete the **fetchOptions: { mode: 'no-cors', },**. the error become **Error: Failed to fetch** and i get a cors error 
<img width="1346" alt="Screen Shot 2021-01-27 at 21 25 11" src="https://user-images.githubusercontent.com/38192665/106122895-9656de80-619c-11eb-9e98-095c0ce89935.png">

**Comment by ruban258** [comment]
i have the same problem, did you find any solution?

**Comment by ruban258** [comment]
I had the GraphQLserver and svelte running on the same URL. it fixed everything for me.  

https://github.com/ruban258/SvelteScada/blob/main/src/SvelteScada/rollup.config.js

I'm using the asp.net core app to serve the svelte app and GraphQL server.

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
