### ISSUE TITLE
`update` function of `useMutation` is not executed when the mutation results with errors.

### ISSUE THREAD

**Issue by SeungsuKim** [apollographql/apollo-client#7628]
**Intended outcome:**

I've extended a type `Message` with a local only field `status` with the following typeDef.
```
typeDefs = gql`
  extend type Message {
    status: MessageStatus!
  }
  enum MessageStatus {
    PENDING
    SENDED
    FAILED
  }

const httpLink = createHttpLink({ uri: 'http://localhost:4000/graphql' });

const authLink = setContext((_, context) => {
  const token = localStorage.getItem('token');

  return {
    ...context,
    headers: {
      ...context.headers,
      ...(token ? { authorization: `Bearer ${token}` } : {}),
    },
  };
});

const client = new ApolloClient({
  link: authLink.concat(httpLink),
  cache,
  typeDefs,
});
```

When a user sends a new message, the message data is appended to the cache with `status` of `PENDING` value. I want this `status` value in the cache to be updated depending on the success of the `sendMessageMutation` mutation. 

```
const [sendMessageMutation] = useSendMessageMutation({
    onError: errors => {
      console.error(errors);
    },
  });

 sendMessageMutation({
      variables: {
        chatId: variables.chatId,
        message: { id, content: variables.content },
      },
      update(cache, { errors }) {
        cache.modify({
          id: `Message:${id}`,
          fields: {
            status() {
              return errors ? MessageStatus.Failed : MessageStatus.Sended;
            },
          },
        });
      },
    });
```

The intended outcome is the `update` function is executed whether or not the `sendMessageMutation` fails or not and modifies the cache properly.

**Actual outcome:**

However, the `update` function is only executed when the mutation successes. When the mutation fails, the `update` function is not executed, leaving the `status` field value in the cache `PENDING`, not updating to `FAILED`

**How to reproduce the issue:**

Need a running GraphQL server to reproduce...

**Versions**

  System:
    OS: macOS 10.15.6
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Safari: 14.0
  npmPackages:
    @apollo/client: ^3.3.7 => 3.3.7

**Comment by SeungsuKim** [comment]
Related to the [issue#5882](https://github.com/apollographql/apollo-client/issues/5582)

**Comment by jcreighton** [comment]
@SeungsuKim A reproduction is needed for us to help with this issue. I've created a mutation that errors [here](https://codesandbox.io/s/dank-wave-f1vi3?file=/src/App.js). The `update` function is called but this could be missing a piece that's closer to what you're experiencing. Feel free to modify!

**Comment by hwillson** [comment]
If someone can provide a small runnable reproduction that demonstrates this happening with `@apollo/client@latest`, we'll take a closer look. Thanks!
