### ISSUE TITLE
Reactive variables only update cache when query polling is enabled

### ISSUE THREAD

**Issue by Steven-Ireland** [apollographql/apollo-client#7630]
**Intended outcome:**

Updating the value of a reactive variable should broadcast the local state change to the cache and update any dependent queries

**Actual outcome:**

Above behavior only occurs when `{pollInterval: XXX}` is passed to `useQuery`, and only after the first poll has been completed

**How to reproduce the issue:**

I have a codesandbox with the issue: https://codesandbox.io/s/apollo-reactivevars-only-work-with-polling-enabled-kk8b3. List items can be "selected" via click with the selected ids stored in a reactive variable.

In the example I've set `pollInterval` to `5000`, the following things can be observed:
1. No local state changes apply before the 5000 ms has passed
2. After the 5000ms, any local state changes are reflected in the query immediately
3. Removing the poll interval entirely causes local state changes to never update the query

**Versions**

3.3.7, see codesandbox

**Comment by jcreighton** [comment]
Looks like this was also reported in #7593.

**Comment by jcreighton** [comment]
Should be fixed with #7657.
