### ISSUE TITLE
Merge is not called for local fields

### ISSUE THREAD

**Issue by Dattaya** [apollographql/apollo-client#7632]
Probably a dup of #6987, but that one is old and to this day not labeled as a bug, so I wanted to bring more attention to this issue.

**Intended outcome:**
Merge is called (you'll see 'merge' in the console when that happens) and new items are appended to the resulting array when you press 'load more'

**Actual outcome:**
Merge is ignored

**How to reproduce the issue:**
https://codesandbox.io/s/merge-does-not-work-with-local-fields-6xtsn

**Versions**
```
    "@apollo/client": "^3.3.7",
    "graphql": "^15.5.0",
```

**Comment by Dattaya** [comment]
AFAIU, local queries are no longer stored in apollo cache, hence merge does not work by design, because it merges new items with old ones from the cache. I don't know what to think of it yet, but closing this issue, #6987 remains open anyway.

**Comment by younes0** [comment]
@Dattaya problem still exists
Which workaround did you think about ?

**Comment by Dattaya** [comment]
@younes0, I simply don't use `@client` functionality anymore and rely on other state management solutions like redux, recoil, etc.

**Comment by younes0** [comment]
@Dattaya it's a shame that this issue makes local fields useless. Most of the models in an app are subject to pagination.
cc @hwillson
