### ISSUE TITLE
Updating cache after mutation using typePolicies

### ISSUE THREAD

**Issue by hdgone** [apollographql/apollo-client#7633]
I have a cached array of objects where each object represents a playlist instance:

```
{
  id: ID!
  title: String!
  # total number of songs
  total: Int!
}
```
This array is the result of executing **ownPlaylists** query.

I have an **addSongToPlaylist** mutation with the following signature:
```
addSongToPlaylist(input: AddSongToPlaylistInput!): AddSongToPlaylistResult!

union AddSongToPlaylistResult = AddSongToPlaylistSuccess | AddSongToPlaylistError

type AddSongToPlaylistSuccess {
  playlist: Playlist!
}
  
type AddSongToPlaylistError {
  errorCodes: [AddSongToPlaylistErrorCode!]!
}
```

Whenever I add a song to a playlist, I wanna update the value of **total** field. Since I always have ID's, cache mutation works under the hood for me. However, I keep getting this annoying warning when the mutation results in an expected error:

> Cache data may be lost when replacing the addSongToPlaylist field of a Mutation object.

>To address this problem (which is not a bug in Apollo Client), either ensure all objects of type AddSongToPlaylistSuccess and AddSongToPlaylistError have IDs, or define a custom merge function for the Mutation.addSongToPlaylist field, so InMemoryCache can safely merge these objects:

 >existing: {"__typename":"AddSongToPlaylistSuccess","playlist":{"__ref":"Playlist:08c1c87c-61b1-11eb-8fe6-2740c166c4d0"}}
 >incoming: {"__typename":"AddSongToPlaylistError","errorCodes":["ALREADY_THERE"]}
  
 I decided to fix it by providing a manual cache update implementing the **update** method for this mutation. The error still persisted and I tried the suggested way using typePolicies. Unfortunately, I'm having a hard time understanding how to use them with mutations, the documentation has query examples only. I tried something like that:
 
```
    typePolicies: {
      Mutation: {
        fields: {
          addSongToPlaylist(existing, incoming) {
            console.log(existing, incoming);
          }
        }
      }
    },
```

But this console.log is never invoked. What am I missing?

**Comment by martdavidson** [comment]
You have `addSongToPlaylist` in the `fields` object but console.warn is showing `addExternalSongToPlaylist` field as the one that is the issue. Is that the issue?

**Comment by hdgone** [comment]
@martdavidson oh, my bad, sorry for the inconvenience, I've been simplifying my snippet for this issue and forgot to clean this part up. It should be `addSongToPlaylist`

**Comment by hdgone** [comment]
Seems like I've figured it out. I've messed up the syntax a little bit. Found a workaround to always accept successful result. Not sure how right it is, but it works and the warning is gone:

```
Mutation: {
        fields: {
          addSongToPlaylist: {
            merge(existing, incoming: AddSongToPlaylistResult) {
              if (incoming.__typename === 'AddSongToPlaylistSuccess') {
                return incoming;
              }
              return existing;
            },
          },
        },
      },
```
