### ISSUE TITLE
@apollo/client 3.4.0-beta.6 breaks Next.js setup with "TypeError: class constructors must be invoked with 'new'"

### ISSUE THREAD

**Issue by rriski** [apollographql/apollo-client#7635]
**Intended outcome:**
 
Upgrading to @apollo/client 3.4.0-beta.6  breaks with `TypeError: class constructors must be invoked with 'new'` using Next.js. Works fine with @apollo/client 3.4.0-beta.4. Most likely due to changes in PR https://github.com/apollographql/apollo-client/pull/7615. 

**Actual outcome:**
TypeError: class constructors must be invoked with 'new'

**How to reproduce the issue:**
Clone repo https://github.com/rriski/with-apollo. Run with `yarn dev`. Works with 3.4.0-beta.4, breaks with 3.4.0-beta.6 -> `TypeError: class constructors must be invoked with 'new'`.

**Versions**
```
npx: installed 1 in 1.208s

  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.8.0 - ~/.nvm/versions/node/v14.8.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v14.8.0/bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Safari: 14.0.2
```

**Comment by hwillson** [comment]
This should be fixed in the latest `@apollo/client@beta`. Thanks!
