### ISSUE TITLE
Unable to fetch the right data from server and the cache either 

### ISSUE THREAD

**Issue by shubhsk88** [apollographql/apollo-client#7641]
**Intended outcome:**
I have been trying to fetch the data of the user in react to get the list and in my component, it renders well when I refresh the page but when I am routing to a different place in the web app it is wiping out my data and returning empty data which seems like a bug

**Actual outcome:**

It should fetch the right data either from the server or cache below here you can see the screenshot of my apollo dev tool and the component console which should return the cache data from the apollo cache.This works fine when I refresh the page

<img width="1368" alt="Screenshot 2021-02-02 at 10 50 28 PM" src="https://user-images.githubusercontent.com/19767710/106639228-c17d6b80-65aa-11eb-8c38-0b3374d58f0d.png">
different client-side route and come back to the previous page 

**How to reproduce the issue:**

- Refresh the page in nextjs
- Data is fetching as expected 
- Go to a different route  
- Come back to the old page using the certain query
-  The data is wiped somehow

**Versions**

```System:
    OS: macOS 11.1

  Binaries:
    Node: 14.15.4 - ~/.volta/tools/image/node/14.15.4/bin/node
    Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
    npm: 6.14.10 - ~/.volta/tools/image/node/14.15.4/bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Safari: 14.0.2
  npmPackages:
    @apollo/client: ^3.2.1 => 3.3.7 
    apollo-link-context: ^1.0.20 => 1.0.20 
    graphql-codegen-apollo-next-ssr: ^1.2.2 => 1.2.2 
```

**Comment by jcreighton** [comment]
@shubhsk88 Could you provide a small, runnable reproduction? I see there are steps to reproduce but without a reproduction, we can't use those steps to validate there is an issue.

**Comment by shubhsk88** [comment]
Thanks @jcreighton  this is what I am using but I am using codegen and this hook is getting created by it and this is my query
```tsx
import {
  useCreateListMutation,
  useGetUserListsQuery,
} from "@/generated";

const { data, loading, error } = useGetUserListsQuery();
 console.log(data);
if (loading) return <div>loading</div>;
if (error) return <div>{JSON.stringify(error)}</div>;
if (!data.getList.ok) return <div>{data.getList.error}</div>;
```
 
```graphql
query getUserLists {
  getList {
    ok
    error
    lists {
      id
      name
      rooms {
        id
        photos {
          link
        }
      }
    }
  }
}
```

**Comment by jcreighton** [comment]
@shubhsk88 We need a *runnable* reproduction to look into potential issues. Try using our [error template](https://codesandbox.io/s/github/apollographql/react-apollo-error-template) to recreate the issue. Based on what you've written though, this is likely a misconfiguration or other error. In that case, we have a [community on Spectrum](https://spectrum.chat/apollo/apollo-client) that might be able to help.

**Comment by jcreighton** [comment]
Closing this issue as we haven't heard back. If you're still experiencing the issue, we can re-open!
