### ISSUE TITLE
mergeObjects with an incoming reference silently discards existing object fields from cache

### ISSUE THREAD

**Issue by bubba** [apollographql/apollo-client#7642]
I have a schema somewhat like this:

```graphql
type User {
  id: ID!
  name: String!
  email: String!
}

type Query {
  viewer: User
}
```

This viewer field on the root query should always return the same user, so I've set it to merge in the typePolicies of my cache:

```typescript
  new InMemoryCache({
    typePolicies: {
      Query: {
        fields: {
          viewer: { merge: true }
        }
      }
    }
  })
```

If I query the `viewer` field **without** an ID initially:

```graphql
{
  viewer {
    name
  }
}
```

Then the cache (cache.data.data) looks like this afterwards:

```
{
  ROOT_QUERY: [Object: null prototype] {
    __typename: 'Query',
    viewer: {
      __typename: 'User',
      name: 'Luke Lau'
    }
  }
}
```

Now if I make a query that **includes** the ID:

```graphql
{
  viewer {
    id
    email
  }
}
```

with the help of some `console.logs` I can see that the incoming object is a reference, and the result is that reference:

```typescript
merge(existing, incoming, { mergeObjects }) {
  console.log('existing:')
  console.log(existing)
  console.log('incoming:')
  console.log(incoming)
  
  const result = mergeObjects(existing, incoming)
  console.log('result:')
  console.log(result)
  
  return result
}
```

```
existing:
{
  __typename: 'User',
  name: 'Luke Lau'
}
incoming:
{ __ref: 'User:49c23d27-c188-4c38-b952-a45c734efa47' }
result:
{ __ref: 'User:49c23d27-c188-4c38-b952-a45c734efa47' }
```

However, looking at the cache reveals that the reference `User` doesn't contain the `name` field!

```
{
  ROOT_QUERY: [Object: null prototype] {
    __typename: 'Query',
    viewer: {
      __typename: 'User',
      name: 'Luke Lau'
    }
  },
  'User:49c23d27-c188-4c38-b952-a45c734efa47': [Object: null prototype] {
    id: '49c23d27-c188-4c38-b952-a45c734efa47',
    __typename: 'User',
    email: 'luke_lau@icloud.com'
  }
}
```

**Intended outcome:**

I would have expected the `User:49c23d27-c188-4c38-b952-a45c734efa47` entry in the cache to have merged over the other fields from the query that did not contain an ID. This resulted in some of our `useQuery` hooks returning null when being called a second time even with the cache, causing some problems with SSR

**Actual outcome:**

The fields weren't merged as shown above
**How to reproduce the issue:**

Checkout the repro repo at main: git@github.com:bubba/react-apollo-error-template.git

In the browser console, you should notice that the cache never ends up containing the `name` field of the user object.

**Versions**

  System:
    OS: macOS 11.1
  Binaries:
    Node: 15.5.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.3.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Firefox: 83.0
    Safari: 14.0.2
  npmPackages:
    @apollo/client: ^3.3.6 => 3.3.6 
    @apollo/react-ssr: ^4.0.0 => 4.0.0

**Comment by hwillson** [comment]
Fixed by https://github.com/apollographql/apollo-client/pull/7778 - thanks!
