### ISSUE TITLE
Apollo cache modify taking more time than usual setState, leads to glitch while modifying.

### ISSUE THREAD

**Issue by smitbarmase** [apollographql/apollo-client#7658]
I'm fetching a `query`, and modifying the order of the list in it, using `cache.modify` on the drag end.
**This does modify cache, as it should but, it takes milliseconds to do that.**

**How to reproduce the issue:**
I'm using `react beautiful dnd`, to make drag-n-drop card.
It provides onDragEnd handler, where we can specify what happens when the user stops dragging.
In this case, I want to reorder the list on the drag end.

Cache modify:
```js
  cache.modify({
        id: cache.identify(data.pod),
        fields: {
          stories(existingStoriesRefs, { readField }) {
            return reorder(existingStoriesRefs, sourceIndex, destinationIndex);
          },
        },
      });
```

Reorder logic:
```js
const reorder = (list: any[], startIndex: number, endIndex: number) => {
  const result = Array.from(list);
  const [removed] = result.splice(startIndex, 1);
  result.splice(endIndex, 0, removed);
  return result;
};
```

This is correctly working and rendering using `stories` in `setState`.
But, instead of copying Apollo data, to a new state, I think it's better to directly modify the cache.

But, using cache.modify, it works but, rendering is kind of glitchy. It seems, it first renders the existing list and then, modify cache in the next render. The glitch is around less than a second, but visible to the user.

**Versions**
 System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.4/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm

**Comment by smitbarmase** [comment]
I fixed it, using mutation and using modify in it.
```js
  moveStoryMutation({
        variables: {
          id: stories[sourceIndex].id,
          sourceIndex,
          destinationIndex,
        },
        optimisticResponse: {
          __typename: "Mutation",
          moveStory: true,
        },
        update: (proxy) => {
          proxy.modify({
            id: proxy.identify(pod),
            fields: {
              stories(existingStoryRefs) {
                return reorder(
                  existingStoryRefs,
                  sourceIndex,
                  destinationIndex
                );
              },
            },
          });
```

**Comment by yliuaaron** [comment]
@smitbarmase how does the `update` function faster than `cache.modify`? didn't `update` function just call `cache.modify` inside? I am running into this problem too.

**Comment by smitbarmase** [comment]
Nope, it's not faster. And yes, it does call `cache.modify` inside it. 

**The key here is `optimisticResponse` which is only available when you do `mutation`.** Before I was trying to call `cache.modify` directly without using any kind of mutation. It was not the correct approach.

**`optimisticResponse` responds to your mutation right away even before receiving any response from the server.**
This response gets passed to the update function after that, and now you can use your fake response to execute modification, write queries or do something else. In this case, I have modified it to the whole new ordered array.

**Comment by yliuaaron** [comment]
@smitbarmase thanks for the explanation. I understand the relationship between `mutate`, `optimisticResponse`, and `update`. 

My confusion is that in your original implementation, you didn't even call `mutate` to server and I assume `cache.modify` directly modifies the cache *right away*. In your updated implementation, with optimistic response, the `update` function should be executed *right away* too. I thought those 2 `right away`s should be at the same time. 

I changed to the mutate implementation and it did work out better than modifying the cache directly. So I am mind blown and very confused now because of the confusion above.

**Comment by smitbarmase** [comment]
I think we both now on the same page. Even, I don't know this behavior. Maybe, someone can help us out here. Should I reopen the issue?

**Comment by yliuaaron** [comment]
Yeah it would be great to reopen this and get some help from experts! Thanks so much!
