### ISSUE TITLE
Invariant Violation 17: returnPartialData option only supported on watchQuery.

### ISSUE THREAD

**Issue by sandorvasas** [apollographql/apollo-client#7659]
"apollo": "^2.31.0",
"apollo-cache-inmemory": "^1.6.6",
"apollo-client": "^2.6.10",
"apollo-link": "^1.2.14",
"apollo-link-error": "^1.1.13",
"apollo-link-http": "^1.5.17",
"apollo-link-retry": "^2.2.15",
"apollo-link-ws": "^1.0.20",

We keep getting this error on production from a specific page of the app. That's all I know, because the error description is very vague. This is the first time I see the variable name "returnPartialData" - I have never used it, so I don't know what this error is about. 

How can I track this down?

**Comment by vanoMekantsishvili** [comment]
As far as I remember same error was happening for me and case was: When request is still pending and user is changing the page, even if request arrives but user changes the page while Apollo is trying to update local cache and thats when this error was get firing.

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!

**Comment by Scong** [comment]
This is still happening for me on version "@apollo/client": "^3.3.19". Attempting to upgrade to 3.4.11. It's fairly rare for us, and vano's description sounds reasonable. 

We also do not use anything with returnPartialData as far as I can tell.

**Comment by SylvainBigonneau** [comment]
Still happening on 3.5.6 here, no idea why so far.
