### ISSUE TITLE
offsetLimitPagination fills the last page that not reached the limit with existing records

### ISSUE THREAD

**Issue by ulziibadrakh-p** [apollographql/apollo-client#7677]
**Intended outcome:**
I am trying to implement pagination using offsetLimitPagination helper.
```
const client = new ApolloClient({
  link: authLink.concat(httpLink),
  uri: "http://localhost:4000/graphql",
  cache: new InMemoryCache({
    typePolicies: {
      Query: {
        fields: {
          tn_topics: offsetLimitPagination(),
        },
      },
    },
  }),
});
```
```
 fetchMore({
                    // data.selected - current page number
                    query,
                    variables: { skip: limit * data.selected, take: limit },
                  });
```
last page query result 

```
{
  "data": {
    "tn_topics": [
      {
        "id": 88,
        "title": "title 11",
        "__typename": "Tn_topic"
      },
      {
        "id": 89,
        "title": "title 12",
        "__typename": "Tn_topic"
      }
    ],
    "total": {
      "count": {
        "_all": 12,
        "__typename": "Tn_topicCountAggregate"
      },
      "__typename": "AggregateTn_topic"
    }
  }
}
```

apollo dev tool last page result
![image](https://user-images.githubusercontent.com/169289/107484940-137f4c00-6bbe-11eb-957a-e850e9a1306b.png)

**Actual outcome:**

![image](https://user-images.githubusercontent.com/169289/107483862-9901fc80-6bbc-11eb-96bb-4eb02bd735fc.png)
![image](https://user-images.githubusercontent.com/169289/107483922-b1721700-6bbc-11eb-8a3e-8f295d33658d.png)
![image](https://user-images.githubusercontent.com/169289/107484065-de262e80-6bbc-11eb-848d-9295b31c5af4.png)

**How to reproduce the issue:**

**Versions**
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 15.8.0 - D:\NodeJS\tnet\node_modules\.bin\node.CMD
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - D:\Programs\Node\npm.CMD
  Browsers:
    Chrome: 88.0.4324.150
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.63)
  npmPackages:
    @apollo/client: ^3.3.6 => 3.3.8

**Comment by ulziibadrakh-p** [comment]
I think problem is here variables not changing on fetchmore. Why it doesnt change?
![image](https://user-images.githubusercontent.com/169289/107590808-10c73a00-6c44-11eb-919f-3ab143555d11.png)

**Comment by Powersource** [comment]
Running into the same thing, how did you fix this?

**Comment by Powersource** [comment]
Ah it seems like it was just me not doing https://www.apollographql.com/docs/react/pagination/offset-based/#setting-keyargs-with-offsetlimitpagination properly (accidentally didn't make the list of keyargs an array)
