### ISSUE TITLE
Commas removed from orginal query inside HTTP body request

### ISSUE THREAD

**Issue by dlarr** [apollographql/apollo-client#7688]
**Intended outcome:**
I am writing an Angular web app, using apollo-angular and @apollo/client libraries. I think my issue is related to @apollo/client
I also made the post within the apollo-angular github repo : https://github.com/kamilkisiela/apollo-angular/issues/1631

After migration from **"apollo-client": "^2.6.10"** to **"@apollo/client": "^3.0.0"** I have this bad behaviour :

The HTTP query have some of the commas that are put in the string original query removed

pay attention to commas here : 
**dateHistogram(
           period: "7d", 
           metricAggregation: "max", 
           timestampField: "timestamp"
 )**

The original query
```
query QualityHistoryRequest($project: String, $from: String) {
    dateHistogram(
           period: "7d", 
           metricAggregation: "max", 
           timestampField: "timestamp"
    ) { 
      qualityAnalyses(
       filter: {op: AND, criteria: [
           {field: "projectId", comparator: MATCH, value: "something(:.*)?"}
           {field: "branch", comparator: MATCH, value: "develop(/.*)?"}
           {field: "timestamp", comparator: GREATER_THAN, value: $from}]}
      ) {
        timestamp
        measures {
           critical_violations
           blocker_violations
           major_violations
           minor_violations
           info_violations
        }
      }
    }
```

It's expected that the commas in original queries are respected. Nor removed, nor added

**Actual outcome:**
Within the HTTP Body of the resulting request the dateHistogram fields have their commas removed which causes an error server side...
![image](https://user-images.githubusercontent.com/2865021/107614678-1411f400-6c4b-11eb-9b86-09d73314111f.png)

Also here is the complete result, note that filters have commas added which are not needed.

```
"query QualityHistoryRequest($project: String, $from: String) {
  dateHistogram(period: "7d", metricAggregation: "max", timestampField: "timestamp") {
    qualityAnalyses(filter: {op: AND, criteria: [{field: "projectId", comparator: MATCH, value: "something(:.*)?"}, {field: "branch", comparator: MATCH, value: "develop(/.*)?"}, {field: "timestamp", comparator: GREATER_THAN, value: $from}]}) {
      timestamp
      measures {
        critical_violations
        blocker_violations
        major_violations
        minor_violations
        info_violations
        __typename
      }
      __typename
    }
    __typename
  }
}
"
```

**How to reproduce the issue:**
I don't have a special way to reproduce this, I just wanted to know 

- if you had similar case ?
- How the http body request is formatted from the original query

**Versions**
  **System**:
    OS: Windows 10 10.0.17763
  **Binaries**:
    Node: 12.7.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
  **Browsers**:
    Chrome: 78.0.3904.108
    Edge: Spartan (44.17763.831.0)
  **npmPackages**:
    @apollo/client: ^3.0.0 => 3.3.9
    apollo-angular: ^2.2.0 => 2.2.0

I'm adding context info : i used the migration tool here ng update apollo-angular (https://apollo-angular.com/docs/migration/)
And went from 
    apollo/client: ^2.6.10 
    apollo-angular: ^1.10.0 
to 
    @apollo/client: ^3.0.0 
    apollo-angular: ^2.2.0 

And before the migration, the commas were not removed

Thank you for any feedback

**Comment by dlarr** [comment]
Ok ... this repo seems to be a dead ship

**Comment by helfer** [comment]
The queries are semantically identical according to the GraphQL spec: https://spec.graphql.org/June2018/#sec-Insignificant-Commas
What you're seeing over the network is simply the canonical representation of your query returned by the `print` function in `graphql-js`, which Apollo Client (or more precisely, apollo-link-http) calls to serialize your query.

If you're having an issue with that query server-side, it's likely because the server isn't spec-compliant.

**Comment by dlarr** [comment]
Hello Helfer and thank you very much for your answer.

Indeed i was having trouble server-side and, I updated that so I can comply. So I can close this issue because am not stuck.

Though I dont see why commas are added or removed. Query value after serialization should be the same with or without commas.
