### ISSUE TITLE
`fetchMore` causes redundant request with fetchPolicy `network-only` and `cache-and-network`

### ISSUE THREAD

**Issue by gbiryukov** [apollographql/apollo-client#7689]
**Intended outcome:**
Calling `fetchMore` causes single network request when query `fetchPolicy` is `network-only` or `cache-and-network`.

**Actual outcome:**
`fetchMore` causes two requests: one for fetching requested page and second is always refetching first page.

**How to reproduce the issue:**
1. open repro https://codesandbox.io/s/nostalgic-sammet-wlhrq?file=/src/Todos.tsx
2. open network inspector
3. click "Load more"
4. inspect requests inside `wlhrq.csb.app` frame, you will see two requests for every next page load

**Versions**
```
System:
  OS: macOS 11.1
Binaries:
  Node: 14.15.4 - /usr/local/bin/node
  Yarn: 1.12.3 - /usr/local/bin/yarn
  npm: 6.14.10 - /usr/local/bin/npm
Browsers:
  Chrome: 88.0.4324.150
  Safari: 14.0.2
```

**Comment by delucca** [comment]
I'm having the same issue (I was just about to open a bug report right now). It is also important to note that we could use `skip` option to avoid this, but this skip option does not work when the `fetchPolicy` is `network-only` or `cache-and-network`.

**Comment by gbiryukov** [comment]
dirty patch that hides the problem (does not fixes root cause) we're using right now:

`apolloFetchMorePatch.ts` - imported before app initialization
```ts
import { ObservableQuery } from '@apollo/client';
import { Reobserver } from '@apollo/client/core/Reobserver';

/**
 * This is workaround over apollo@3 issue that causes redundant network
 * request on `fetchMore` call if fetch policy of original query was
 * `network-only` or `fetch-and-network`.
 * See more here:
 * https://github.com/apollographql/apollo-client/issues/7689
 * TODO: remove this file after original issue fix
 */
const originalFetchMore = ObservableQuery.prototype.fetchMore;

ObservableQuery.prototype.fetchMore = async function patchedFetchMore(...args) {
  // @ts-ignore
  const reobserver = this.getReobserver() as Reobserver<unknown, unknown>;
  // @ts-ignore
  const originalFetchPolicy = reobserver.options.fetchPolicy;

  // this solution is race-conditions prone but can't find altarnatives
  // @ts-ignore
  reobserver.options.fetchPolicy = 'cache-first';
  try {
    return await originalFetchMore.call(this, ...args);
  } finally {
    // @ts-ignore
    reobserver.options.fetchPolicy = originalFetchPolicy;
  }
};
```

it will work okay only if your paginated query `merge` policy will replace existing data with incoming when offset is 0

**Comment by benjamn** [comment]
@gbiryukov The client is doing exactly what you've asked it to do here!

Since `fetchMore` works by updating the cache, if you want to render those updates without making an additional network request, you need a `fetchPolicy` that's allowed to read from the cache, rather than (just) `network-only`. If you stick with `fetchPolicy: "network-only"` after the first request, the client's only option for responding to cache updates from `fetchMore` is to perform an additional network request. The `cache-and-network` policy allows reading from the cache, which is a step in the right direction, but it also makes an unconditional network request, so that's not exactly what you want. Here's a summary of the history of these behaviors, in case you're curious: https://github.com/apollographql/apollo-client/issues/6760#issuecomment-668188727

Based on your description of the problem, I would guess you want the first query to be `network-only`, but you want to switch back to `cache-first` for subsequent queries. Thanks to #6712, we now have an easy way to achieve that (namely, the `nextFetchPolicy` option):
```ts
const { data, fetchMore, networkStatus } = useQuery<Todos>(TODOS_QUERY, {
  fetchPolicy: "network-only",
  nextFetchPolicy: "cache-first", // this line
  notifyOnNetworkStatusChange: true,
  variables: {
    options: {
      paginate: {
        page: 0,
        limit: 5
      }
    }
  }
});
```
_Please_ use `nextFetchPolicy` instead of monkey-patching `fetchMore`.

**Comment by delucca** [comment]
> @gbiryukov The client is doing exactly what you've asked it to do here!
> 
> Since `fetchMore` works by updating the cache, if you want to render those updates without making an additional network request, you need a `fetchPolicy` that's allowed to read from the cache, rather than (just) `network-only`. If you stick with `fetchPolicy: "network-only"` after the first request, the client's only option for responding to cache updates from `fetchMore` is to perform an additional network request. The `cache-and-network` policy allows reading from the cache, which is a step in the right direction, but it also makes an unconditional network request, so that's not exactly what you want. Here's a summary of the history of these behaviors, in case you're curious: [#6760 (comment)](https://github.com/apollographql/apollo-client/issues/6760#issuecomment-668188727)
> 
> Based on your description of the problem, I would guess you want the first query to be `network-only`, but you want to switch back to `cache-first` for subsequent queries. Thanks to #6712, we now have an easy way to achieve that (namely, the `nextFetchPolicy` option):
> 
> ```ts
> const { data, fetchMore, networkStatus } = useQuery<Todos>(TODOS_QUERY, {
>   fetchPolicy: "network-only",
>   nextFetchPolicy: "cache-first", // this line
>   notifyOnNetworkStatusChange: true,
>   variables: {
>     options: {
>       paginate: {
>         page: 0,
>         limit: 5
>       }
>     }
>   }
> });
> ```
> 
> _Please_ use `nextFetchPolicy` instead of monkey-patching `fetchMore`.

Thanks for your reply! I'm going to try that in my scenario. But, in any case, shouldn't the query be skipped at all if we set the `skip` option to `true`?

What I've found out while searching for a workaround to this question was that queries with `fetchPolicy: 'network-only` ignores the `skip: true` option.

**Comment by gbiryukov** [comment]
works like a charm in combination with proper type policy, thank you 🙏

**Comment by sepehrooo** [comment]
Any update on this?
