### ISSUE TITLE
upgrading from 3.37 to 3.39 React Native. Error TypeError: undefined is not an object (evaluating 'gql.resetCaches')

### ISSUE THREAD

**Issue by tim0git** [apollographql/apollo-client#7693]
Upgraded from 3.37 to 3.39 and following error occurred...   

**Intended outcome:**
App to launch without any errors

**Actual outcome:**
App launches with the following error in the iOS simulator. [iPhone 11 iOS 14.4]

Error TypeError: undefined is not an object (evaluating 'gql.resetCaches')

**How to reproduce the issue:**
  "dependencies": {
    "@apollo/client": "^3.3.9",
    "@react-native-async-storage/async-storage": "^1.13.4",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-firebase/app": "^10.6.3",
    "@react-native-firebase/auth": "^10.7.0",
    "@react-navigation/bottom-tabs": "^5.11.7",
    "@react-navigation/native": "^5.9.2",
    "@react-navigation/stack": "^5.14.2",
    "@twilio/conversations": "^1.1.0",
    "@types/react-native-snap-carousel": "^3.8.2",
    "graphql": "^15.5.0",
    "moment": "^2.29.1",
    "react": "16.13.1",
    "react-moment": "^1.1.1",
    "react-native": "0.63.4",
    "react-native-calendars": "^1.1249.0",
    "react-native-gesture-handler": "^1.9.0",
    "react-native-get-random-values": "^1.5.1",
    "react-native-maps": "0.27.1",
    "react-native-reanimated": "^1.13.2",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.17.1",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-vector-icons": "^8.0.0",
    "react-native-webview": "^11.2.1",
    "react-redux": "^7.2.2",
    "redux": "^4.0.5",
    "redux-saga": "^1.1.3",
    "redux-saga-firebase": "^0.15.0",
    "typescript": "^4.1.3",
    "uuid": "^8.3.2"
  },

**Versions**
Hardware: M1 Macbook Pro

System:
    OS: macOS 11.2.1
  Binaries:
    Node: 15.7.0 - /usr/local/bin/node
    npm: 7.5.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.150
    Safari: 14.0.3
  npmPackages:
    @apollo/client: ^3.3.9 => 3.3.9

**Comment by benjamn** [comment]
@tim0git Are you calling `gql.resetCaches` anywhere in your own code? If not, can you `grep -r resetCaches node_modules` to see where it might be getting called?

**Comment by tim0git** [comment]
I have checked the project and we don't call gql.resetCaches. I have run grep -r resetCaches node_modules and I have uploaded the output to an s3 bucket. https://s3-eu-west-1.amazonaws.com/node-modules-grep-3.39/resetCaches.json. Hope this helps.

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
