### ISSUE TITLE
Why function for applying query returns void instead of a promise?

### ISSUE THREAD

**Issue by illyakurochkin** [apollographql/apollo-client#7714]
When I'm using `useLazyQuery`, the function for applying query returns void instead of a promise.

```
const [fetch, {data, loading}] = useLazyQuery();
...
await fetch(); // I can't do that because `fetch` return type is void
```
Why can't it return a promise, like for mutations?

**Comment by hwillson** [comment]
Related:
- https://github.com/apollographql/apollo-feature-requests/issues/190
- https://github.com/apollographql/apollo-feature-requests/issues/174

**Comment by euphocat** [comment]
just to remember it's an old question asked already here: https://github.com/apollographql/react-apollo/issues/3499

**Comment by ofrank123** [comment]
In the meantime something like the following could be used:
```ts
export const useAsyncQuery = <TData, TVariables = OperationVariables>(
  query: DocumentNode | TypedDocumentNode
): [
  (variables: TVariables) => Promise<ApolloQueryResult<TData>>,
  { loading: boolean }
] => {
  const [loading, setLoading] = useState(false);
  const client = useApolloClient();

  const runQuery = async (variables: TVariables) => {
    setLoading(true);
    const res = await client.query<TData, TVariables>({ query, variables });
    setLoading(false);
    return res;
  };

  return [runQuery, { loading }];
};
```

**Comment by hwillson** [comment]
This was addressed in https://github.com/apollographql/apollo-client/pull/8875 - thanks
