### ISSUE TITLE
FieldPolicy API unable to set __resolveType on Union

### ISSUE THREAD

**Issue by sudollukasz** [apollographql/apollo-client#7717]
**Intended outcome:**

In Apollo Client v3 when using cache field polices I'm unable to set __resolveType on Union what probably causes that when I try to query on specific type I always don't have data (same behavior as when using resolvers and don't set __resolveType)

**Actual outcome:**

I can't use Union together with cache FieldPolicy API. It is not returning any data for Unions.

**How to reproduce the issue:**

It is impossible to implement such schema:

```
type First {
    dataFirst: String!
  }
  
  type Second {
    dataSecond: String!
  }
  
  union Test = First | Second
  
  extend type Query {
    test: Test!
  }
  
  query getData {
    test {
      ... on First {
        dataFirst
      }
      ... on Second {
        dataSecond
      }
    }
  }
```

**Versions**

```
System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 88.0.4324.150
    Edge: Spartan (44.18362.449.0)
```

**Comment by benjamn** [comment]
@sudollukasz Are you providing the necessary [`possibleTypes`](https://www.apollographql.com/docs/react/data/fragments/#using-fragments-with-unions-and-interfaces) information to the `InMemoryCache` constructor?
```ts
new InMemoryCache({
  possibleTypes: {
    Test: ["First", "Second"],
  },
})
```

**Comment by sudollukasz** [comment]
@benjamn Yes I did.

Here is example link to example with error I described:
https://codesandbox.io/s/apolloclient-3-local-state-union-mqgse

**Comment by benjamn** [comment]
@sudollukasz Thanks for the reproduction!

If you're going to be storing a whole object in a reactive variable, and you want to be able to match fragments against it, it needs a `__typename` property:
```ts
const testVar = makeVar({
  __typename: "First",
  dataFirst: "First"
});
const firstVar = makeVar({
  __typename: "First",
  dataFirst: "First"
});
const secondVar = makeVar({
  __typename: "Second",
  dataFirst: "Second"
});
```
When Apollo Client fetches queries from the server, it automatically adds the `__typename` field, which is always safe because GraphQL servers support `__typename` for any object. With a reactive variable, the `__typename` has to come from somewhere, since it isn't coming from the server.

**Comment by sudollukasz** [comment]
@benjamn Thanks for your help! Now it is all clear :)
