### ISSUE TITLE
ROOT_MUTATION keeps mutations after they're executed, even when the response is not normalized

### ISSUE THREAD

**Issue by mbman** [apollographql/apollo-client#7725]
**Intended outcome:**
When I execute an Apollo mutation, it is stored in ROOT_MUTATION in Apollo cache. I know this can be prevented by adding no-cache fetchPolicy, but even without adding that policy I don't see a reason why Apollo needs to store executed mutations who's response is not normalized after they're resolved. For instance if you have a mutation just returning a boolean value, what's the point of storing these in the cache and not removing them after the mutation has resolved?

This seems like a potential memory leak which many new (and possibly experienced) Apollo users can easily overlook. Apollo should make sure to clean those from memory and minimize the number of common pitfalls users can run into.

**Actual outcome:**
Apollo should remove mutations from ROOT_MUTATION after the mutation is resolved, regardless of cache policy applied, if the result of the mutation can't be normalized.

**How to reproduce the issue:**
https://codesandbox.io/s/unruffled-mayer-jwowq
Click on "Execute Mutation" button - it will execute a mutation who's response is just a Boolean value and show and alert with JSON stringified cache content showing the mutation to be stored in ROOT_MUTATION. 

**Versions**
Tested on Apollo v3

**Comment by hwillson** [comment]
This is being addressed by https://github.com/apollographql/apollo-client/pull/8280 (which will be merged shortly, and included in `@apollo/client@3.4`) - thanks!
