### ISSUE TITLE
`policies` Property Missing from `ApolloCache` Type

### ISSUE THREAD

**Issue by ITenthusiasm** [apollographql/apollo-client#7729]
## Intended outcome:
In TypeScript, `policies` should be acknowledged as a valid property on `ApolloCache<T>`. More specifically, something like
```typescript
client.cache.policies.addTypePolicies({ /* args */ });
```
should be viable.

## Actual outcome:
TypeScript fails to recognize the property `policies`. Error:
```
Property 'policies' does not exist on type 'ApolloCache<any>'
```

## How to reproduce the issue
1. Create an instance of `ApolloClient` with a `cache`.
2. Attempt to access `client.cache.policies` and watch TypeScript display a type error.

The easiest way to see this issue is in an IDE. I created a code sandbox [here](https://codesandbox.io/s/2cklm). You just have to navigate to `client.ts` to see the TS error.

## Versions
System:
  OS: Windows 10 10.0.18363
Binaries:
  Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
  npm: 7.5.3 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Edge: Spartan (44.18362.449.0)
npmPackages:
  @apollo/client: 3.3.8

**Comment by benjamn** [comment]
@ITenthusiasm I hear what you're saying here, but the `Policies` class is specific to `InMemoryCache`, so we are not going to make it a required property of the abstract `ApolloCache` superclass. When you know you're using an `InMemoryCache`, you can safely cast it to make TypeScript happy:
```ts
(client.cache as InMemoryCache).policies.addTypePolicies(...)
```

**Comment by ITenthusiasm** [comment]
Ah, I see. That's fair enough. Thanks for the info!

**Comment by sanbornhilland** [comment]
Would you consider reopening this issue? I don't think that casting is the most desirable solution here. Ideally we should be able to satisfy everyone here by improving the type inference for the `ApolloClient` based on what cache type is being passed. That way it's type safe when something other than an `InMemoryCache` is passed but the cache type is inferred correctly without requiring casting.

For example is something like this acceptable?

```ts
export declare class ApolloClient<TCache extends ApolloCache> implements DataProxy {
    cache: TCache;
}
```
