### ISSUE TITLE
Refresh of useQuery is not triggered after updating an item that has been added to the cache using cache.modify

### ISSUE THREAD

**Issue by oskarwrobel** [apollographql/apollo-client#7731]
**Intended outcome:**

`useQuery` hook should be automatically refreshed after mutation when the hook depends on changed data.

**Actual outcome:**

Refresh of the `useQuery` hook is not triggered when mutation updates a list item that has been added to the cache using `cache.modify()`. Data in the cache is updated correctly, however, the `useQuery` hook does not react to it.

**How to reproduce the issue:**

Here you can find a reproduction https://github.com/oskarwrobel/react-apollo-error-template.
1. Try to update one of the existing items - it works as expected. Cache and UI will be up to date.
![Feb-19-2021 18-28-49](https://user-images.githubusercontent.com/1057056/108539590-7bc9de00-72e0-11eb-9600-7ac49227769b.gif)
2. Add one more item and update it. Cache will be updated UI won't.
![Feb-19-2021 18-27-55](https://user-images.githubusercontent.com/1057056/108540183-29d58800-72e1-11eb-875e-151d072ad92d.gif)

**Versions**
```
  System:
    OS: macOS 11.2
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Browsers:
    Chrome: 88.0.4324.182
  npmPackages:
    @apollo/client: ^3.3.11 => 3.3.11
```

**Comment by jcreighton** [comment]
@oskarwrobel Thanks for the reproduction (and the GIFs)! We'll look into this.

**Comment by jcreighton** [comment]
@oskarwrobel I took a look at the reproduction and I think I see why the cache isn't updating properly. Modifier functions can return [a value or a reference](https://www.apollographql.com/docs/react/caching/cache-interaction/#values-vs-references) and in the reproduction, what's being returned is a list of references. What's being appended though is an object. So while it seems like the new person is added the list, this is what the cache now looks like:
<img width="585" alt="Screen Shot 2021-02-22 at 5 19 32 PM" src="https://user-images.githubusercontent.com/5232812/108796369-9e652c80-7556-11eb-8991-ff9d414755ca.png">

For this update to work, you'll need to use `writeFragment` to write the data and return a ref. Then you can append that ref to the list. I've created a working example using writeFragement [here](https://codesandbox.io/s/festive-ardinghelli-s0nvr?file=/src/App.js). Let me know if this helps!

**Comment by oskarwrobel** [comment]
You are right. It works fine with reference as a new value. Thanks a lot for your help and quick response.
