### ISSUE TITLE
MissingFieldError when Fetch policy is "cache-only"

### ISSUE THREAD

**Issue by i8ramin** [apollographql/apollo-client#7732]
**Intended outcome:**

I am building a Chrome extension + web app, which utilizes Apollo Client + [apollo-cache-persist](https://github.com/apollographql/apollo-cache-persist). I am noticing that my queries on do not seem to take advantage of the persisted cache and always hitting network. It seems to work within the context of my Chrome extension _popup_, but does not within the context of my web app (they share the same apollo client config and setup)

Upon further investigation and console logging, I am noticing that when the cache fails, I see the following error deep within the query info details: `MissingFieldError` and `Can't find field 'findCartByUserId' on ROOT_QUERY object`. When I look up my cache in `window.localStorage`, I do indeed see `findCartByUserId` on `ROOT_QUERY` (and like I mentioned, this exact same code works fine within my Chrome extension popup context). I know the Chrome extension popup and my webapp operate in different environments and don't share the same `localStorage`. That is not the issue, since I see the values in both.

**ERROR**

<img width="567" alt="Screen Shot 2021-02-19 at 12 34 12 PM" src="https://user-images.githubusercontent.com/49030/108541365-60df7580-72b0-11eb-9283-a47d62617038.png">

**DATA IN LOCALSTORAGE**

<img width="634" alt="Screen Shot 2021-02-19 at 12 34 29 PM" src="https://user-images.githubusercontent.com/49030/108541383-650b9300-72b0-11eb-8f4e-e111db7c204a.png">

**Actual outcome:**

The actual outcome is that when I set my fetch policy to `cache-only` and the cache values are there, apollo client fails to load my data and I get nothing back. If I set the fetch policy to the default `cache-first` (these are `watchQuery`), it always hits the network and never reads from cache (even when values are in the persisted cache)

**How to reproduce the issue:**

Unfortunately, not simple to reproduce outside of my app. More than happy to share the repo with anyone who wants to poke around and run locally

**Versions**

```
  System:
    OS: macOS 11.0.1
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    Yarn: 1.22.10 - ~/Work/personal/carrot-cart/node_modules/.bin/yarn
    npm: 7.5.3 - ~/.nvm/versions/node/v12.19.0/bin/npm
  Browsers:
    Chrome: 88.0.4324.182
    Safari: 14.0.1
  npmPackages:
    @apollo/client: ^3.3.7 => 3.3.7
    apollo3-cache-persist: ^0.9.1 => 0.9.1
    graphql-codegen-svelte-apollo: ^0.1.2 => 0.1.2
    svelte-apollo: ^0.4.0 => 0.4.0
```

**Comment by i8ramin** [comment]
Some more code snippets that may be helpful in debugging this issue. This is a Svelte app and I am using the graphql-codegen-svelte-apollo library. So here is the generated code for the issue above (again, this same exact code is shared between my webapp and also my extension, which works as expected)

```js
export const FindCartByUserId = (
  options: Omit<QueryOptions<FindCartByUserIdQueryVariables>, "query">
): Readable<
  ApolloQueryResult<FindCartByUserIdQuery> & {
    query: ObservableQuery<
      FindCartByUserIdQuery,
      FindCartByUserIdQueryVariables
    >;
  }
> => {
  const q = client.watchQuery({
    query: FindCartByUserIdDoc,
    ...options,
  });
  var result = readable<
    ApolloQueryResult<FindCartByUserIdQuery> & {
      query: ObservableQuery<
        FindCartByUserIdQuery,
        FindCartByUserIdQueryVariables
      >;
    }
  >(
    { data: null, loading: true, error: null, networkStatus: 1, query: null },
    (set) => {
      q.subscribe((v) => {
        set({ ...v, query: q });
      });
    }
  );
  return result;
};
```

**Comment by jasongaare** [comment]
@i8ramin did you find a solution? why did you close?
