### ISSUE TITLE
Packages ts-invariant and subscriptions-transport-ws both have reference to `@types/node`

### ISSUE THREAD

**Issue by jimisaacs** [apollographql/apollo-client#7734]
Please refer to this issue for context: https://github.com/microsoft/TypeScript/issues/31148#issuecomment-782321503

~~In summary, the older versions of the ts-invariant and subscriptions-transport-ws dependencies are exposing a reference to `@types/node`, which leaks and pollutes typescript codebases. They seem to have fixed their packages though in their sources.~~

After further search, the versions of the packages in question is not the issue, but the issue remains with them regarding the original typescript issue.

**Comment by benjamn** [comment]
@jimisaacs What version of `@apollo/client` are you using? The current latest version of `@apollo/client` (3.3.11) is using the latest version of `ts-invariant` (0.6.0) and `subscriptions-transport-ws` (^0.9.17, matching 0.9.18), unless I'm missing something.

**Comment by jimisaacs** [comment]
I see we have 3.3.11 installed, let me do some more digging on the other packages.

**Comment by jimisaacs** [comment]
For some reason we have ts-invariant `0.4.4`, not sure about that yet. I'm assuming something else is happening their in my monorepo. We have `subscriptions-transport-ws` 0.9.18, so I don't understand. If you download from npm, that version, and look at `dist/server.d.ts`, you should see `/// <reference types="node" />` right at the top. Though I don't see it in the source here https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/server.ts#L1 so 🤷 

I will look again at why have that version of ts-variant, though subscriptions-transport-ws has me stumped at the moment.

**Comment by jimisaacs** [comment]
So, I can't find out why 0.4.4 is installed from `ts-invariant`, but I guess it doesn't matter, as it is in the same state as the other package. The reference is there in the published declarations, but I didn't find it in the source.

**Comment by jimisaacs** [comment]
Given the versions of the packages are not the issue, but that apollo-client is the source of both of these packages in my codebase, I'm going to retitle this issue, but keep it open.

**Comment by Venryx** [comment]
I have the same issue: `NodeJS.Process` is apparently referenced as the type for `processStub` in `ts-invariant/lib/invariant.d.ts`.

And I can't get rid of `ts-invariant` as a dependency, because apparently it is a subdependency of `@apollo/client` -- which means my browser-targeted apollo library is now requiring the NodeJS types. 🤦‍♂️

Screenshot showing issue:
![](https://i.imgur.com/u8kIWYS.png)

**Comment by Venryx** [comment]
I think the reason the `processStub` variable is being resolved to `NodeJS.process` during compilation is due to this, in the `package.json`: https://github.com/apollographql/invariant-packages/blob/7813ca014a3ad5110850d8640063766fa58f24f7/tsconfig.json#L9

**Comment by jimisaacs** [comment]
@Venryx So you are saying `tsc` actually adds the `/// <reference types="node" />` to the top of the generated declarations automatically, because there is `"types": ["node"]` in the tsconfig file used to generate said declaration?

**Comment by Venryx** [comment]
> So you are saying tsc actually adds the /// <reference types="node" /> to the top of the generated declarations automatically, because there is "types": ["node"] in the tsconfig file used to generate said declaration?

I'm no expert on the details of TypeScript's compilation process, but that's what it looks like to me, yes.

**Comment by Venryx** [comment]
> So you are saying tsc actually adds the /// <reference types="node" /> to the top of the generated declarations automatically, because there is "types": ["node"] in the tsconfig file used to generate said declaration?

I'm no expert on the details of TypeScript's compilation process, but that's what it looks like to me, yes.

Well more precisely, it adds that reference line because the `processStub` variable is "resolved" to the `NodeJS.Process` type defined from the `@types/node` package -- which could only happen because of that `"types": ["node"]` line.

**Comment by benjamn** [comment]
@jimisaacs @Venryx PR #7751 should fix the `ts-invariant` part of the problem, but you can also update to `ts-invariant@0.6.1` on your own, in the meantime.

**Comment by jimisaacs** [comment]
Much appreciated @benjamn, and @Venryx for the thorough analysis.

**Comment by hwillson** [comment]
Fixed by https://github.com/apollographql/apollo-client/pull/7751 - thanks!
