### ISSUE TITLE
useQuery unexpectedly resolves with `undefined` when using typePolicies

### ISSUE THREAD

**Issue by drew-walker** [apollographql/apollo-client#7735]
**Intended outcome:**
Pre-conditions:
1. An item exists in the Apollo cache (e.g "Organization:abc123") with partial data (e.g. just an "id" cached) as a result of a previous query.

```
useQuery(gql`query ($memberID: ID!) {
    member(id: $memberID) @client {
        id
        fullName
        organization {
            id
        }
    }
}`, {
    variables: {
        "memberID": "me"
    }
});
```

2. A type policy exists for the field being requested, and that policy is returning `undefined`. This is obviously simplified for the purpose of the example.

```
export const client = new ApolloClient({
    cache: new InMemoryCache({
        typePolicies: {
            Query: {
                fields: {
                    organization: {
                        read: () => {
                            return;
                        }
                    }
                }
            }
        }
    }),
    ...
});
```

Action:
We query for the cached item using `useQuery`, but request additional fields (e.g. "id" AND "displayName"). We expect that the organization should resolve as `null` because this user doesn't have access to this organization.

```
const {data} = useQuery(gql`query ($orgID: ID!) {
    organization(id: $orgID) @client {
        id
        displayName
    }
}`, {
    variables: {
        "orgID": "abc123"
    },
    skip: loading
})
```

Expected result:
1. The query consults the type policy, and returns `undefined`.
2. The `undefined` result mean the query executes the resolver.
3. The resolver will go to the network and resolve with `{ organization: null }`.
4. The `data` variable in the component will equal `{ organization: null }` once the query is resolved.

**Actual outcome:**
1. The query consults the type policy, and returns `undefined`.
2. The `undefined` result means the query executes the resolver.
3. The resolver will go to the network and resolve with `{ organization: null }`.
4. The `data` variable in the component equals `undefined` and never reflects the `null` value returned from the resolver.

NOTE: This problem seems to only affect `useQuery`, and not `client.query`.

**How to reproduce the issue:**
Apologies, I didn't realize there was a scaffold project template, but I've created a minimal reproduction of the issue here: https://github.com/drew-walker/apollo-bug. You should be able to clone this and run `yarn && yarn start` and see the issue at `http://localhost:8080`.

**Versions**
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.19.1 - ~/.yvm/shim/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Browsers:
    Chrome: 88.0.4324.182
    Firefox: 80.0.1
    Safari: 14.0.3
  npmPackages:
    @apollo/client: 3.3.11 => 3.3.11

**Comment by jcreighton** [comment]
@drew-walker I looked into the reproduction (thank you!) and the good news is there's a fix! The read function isn't designed to work as you expect: `I would expect that returning `undefined` allows the query to continue to the resolver.` [Read functions](I would expect that returning `undefined` allows the query to continue to the resolver.) return a value in lieu of the cached value. In this case, you're returning `undefined` instead of the cached value. You'll want to return the cached value (which is provided as the first parameter to the read function) for this to work properly. I'm going to mark this as "working as designed" but happy to look into this again if there's something I've missed!

**Comment by drew-walker** [comment]
Thanks for looking into it @jcreighton. You're absolutely right. I think our lack of understanding about the order that the resolver and read function would execute was causing us to make false assumptions and then we missed something obvious. In our actual code we had something like this:

```
export const client = new ApolloClient({
    cache: new InMemoryCache({
        typePolicies: {
            Query: {
                fields: {
                    organization: {
                        read: (existing) => {
                            if (existing) {
                                return existing;
                            }
                            // DO MORE STUFF
                            return;
                        }
                    }
                }
            }
        }
    })
});
```

That meant that when we had `null` values in the cache, we ended up returning `undefined`. 🤦  The fix for us was as simple as changing the early return to this:

```
if (existing !== undefined) {
    return existing;
}
```

I think it's time for us to enable eqeqeq in ESLint. 😄
