### ISSUE TITLE
Separating networkInterface logic and implementation in favor of supporting more network interface types 

### ISSUE THREAD

**Issue by DxCx** [apollographql/apollo-client#774]
(Continuation of #749)

So Generally, my finally goal, is to be able support more then just HTTP for apollo-client,
starting with websocket in the near term and maybe HTTP2 in the future.

So, IMO we need separate networkInterface generic/common logic (such as middlewares/batching) from the implementation logic (Http fetch in that case).
to do that, the following steps should be taken:
1. Make middleware/afterware generic (GraphQL and not networkInterface)
   - Suggested interface:
     
     ``` typescript
     export interface ResponseAndOptions {
             interfaceType: string;      // string indicating which transport layer is used.
                                                     // afterware might treat response differently depends on that.
             result: GraphQLResult;  // GraphQL parsed response
             response: IResponse;    // GraphQL raw response. (Optional, depends on interfaceType)
             options: RequestInit;
     }
     ```
     
     NOTE: if the transport layer response is sent to middleware, then middlewares should be able to support errors chain as well. (next(err) should work), else, what/how would you like it to validate?
2. separate the logics (I have a draft which i still need to work on, but now i got one step back),
     which means:
   - common networkInterface logic will reside in genericNetworkInterface abstract class which will provide an abstract protected/public method to do the network specific operations.
     - for example, HTTPFetchNetworkInterface will inherint the genericNetworkInterface, and then implement just one function which will send the actual fetch.
   - batched interface will become abstract as well and will extend genericNetworkInterface to provide abstracted batching logic.  
   - Another class (HTPPFetchBatchedNetworkInterface) will inherit batchedNetworkInterface and implement the same exact fetch as above.

from this point, i believe that adding more and more networkInterfaces will be easier as it is much more generic and all that needs to be done to add an interface is to provide 1 function.
also, IMO, this approach will make it easier in the future to release networkInterfaces as different small packages.

**Comment by morgante** [comment]
I like the idea of part 1.

**Comment by DxCx** [comment]
@stubailo @helfer now that 0.5.0 is out, can you please respond :)

**Comment by helfer** [comment]
@DxCx sure! I think it's a very good idea to clean up the network interface a bit, but we definitely need to have something concrete to talk about. Could you make some specific examples for what the API would look like, and how one would add middleware/afterware to the network interfaces? I think it would be good to have an example for HTTP, HTTP with batching and one for websockets that does everything (single requests, batching and subscriptions).

**Comment by helfer** [comment]
@DxCx If you're still interested in this, make sure to touch base with us before you start 🙂

**Comment by stubailo** [comment]
BTW, the answer to this is https://github.com/apollographql/apollo-link
