### ISSUE TITLE
Expected behavior for data while loading is true with query or useQuery

### ISSUE THREAD

**Issue by skolerst** [apollographql/apollo-client#7755]
Hello!

I am working with @apollo/client v3.3.6

I forked and made some updates to a sandbox here: https://codesandbox.io/s/apollo-fetchmore-issue-forked-0o7dq?file=/src/index.js

I was under the impression that if `loading === true`, then data should be undefined. As you can see in this example, calling fetchMore doesn't revert data to undefined.

What are the circumstances that would cause data to become undefined? Different query variables/calling refetch perhaps? Is there a scenario where calling fetchMore should cause data to become undefined?

Thanks!

**Comment by jcreighton** [comment]
@skolerst Might be helpful to check out this [previous issue](https://github.com/apollographql/apollo-client/issues/7038) related to data being undefined in 3.0. That issue should also help answer your question here re: different query variables.
