### ISSUE TITLE
Apollo: Subscription & Optimistic Response not updating

### ISSUE THREAD

**Issue by BenAllenUK** [apollographql/apollo-client#7758]
I'm having a hard time getting optimistic response from a mutation.

I have a subscription query and a mutation query. The subscription is called and successfully populates with data. Sometime later, the mutation is called. I see the mutations update handler called twice. Once for the optimistic version, and once for the actual server response. Annoyingly, however, the optimistic response does not update my UI (React components) after the first call of update which is unexpected. It does so successfully on the second. 

I use the apollo chrome plugin and I can see the object update with the new optimistic response in the cached tab instantly. This makes me think it is a problem with broadcasting the change as opposed to updating the cache.

When I perform this operation using a regular query, the cache also updates instantly and these changes ARE reflected in the UI which again confirms the optimistic response is working.

Therefore I deduce it is a problem with subscription not picking up the broadcasted optimistic data.

What am I missing here?

Called on user event:
```
const { data } = await upsertArticlesMutation({
      optimisticResponse: {
        insert_articles: {
          returning: [
            {
              ...existingArticle,
              blocks: [],
            },
          ],
        },
      },
      update: (cache, { data }) => {
        cache.writeFragment({
          id: `articles:${id}`,
          fragment: ARTICLE_FRAGMENT,
          data: { ...existingArticle, position: newPosition },
        })
      },
      variables: {
        objects: {
          ...existingArticle,
          position: newPosition,
        },
      },
    })
```

Called first:
```
const { data } = useGetProjectOneSubscriptionSubscription({
      variables: {
        slug: projectSlug,
      },
    })

```

**Comment by martin-dutch** [comment]
Having the same issue right now!

**Comment by jcreighton** [comment]
@BenAllenUK Thanks for the issue! Could you create a runnable reproduction using either [this repo](https://github.com/apollographql/react-apollo-error-template) or [this CodeSandbox](https://codesandbox.io/s/condescending-fermi-07u2p)?

**Comment by hwillson** [comment]
If someone can provide a small runnable reproduction that demonstrates this happening with `@apollo/client@latest`, we'll take a closer look. Thanks!
