### ISSUE TITLE
Mutation does not trigger queries to keep this data updated after SSR

### ISSUE THREAD

**Issue by diana-safyanova** [apollographql/apollo-client#7760]
Hi!
Help me, please))

I have a user list page that comes back from the server. There is a query to get all users and they are written to the cache.

const { data, loading, error, refetch } = useQuery(ContactsQuery, { fetchPolicy: 'cache-and-network', variables, });

I use ssrMode and ssrForceFetchDelay so that the request is not called again on the client on the first render

new ApolloClient({ ...(typeof window === 'undefined' ? { ssrMode: true, } : { ssrForceFetchDelay: 100 } ), link, cache: new InMemoryCache().restore(apolloState);, });

Also I have a mutation that changes user data.
It automatically refreshes the cache for this user.
But this does not call the query to get all users, as written in the documentation

Any changes you make to cached data inside of an update function are automatically broadcast to queries that are listening for changes to that data.

If I go to this page from another without using SSR, then the mutation causes a call to a query to get all users.
I think that after SSR the requests cannot follow the data change.

`"@apollo/client": "^3.3.11",
"next": "9.5.0",
"next-with-apollo": "^5.0.0",
`

**Comment by jdmoody** [comment]
> Also I have a mutation that changes user data.

Is this mutation running during SSR? I don't think @apollo/client supports running mutations during SSR

**Comment by zenflow** [comment]
> But this does not call the query to get all users, as written in the documentation

What documentation are you referring to exactly? Closest thing I could find was the `refetchQueries` option here:
https://www.apollographql.com/docs/react/data/mutations/#options

Are you using the `refetchQueries` option?

I'm actually having the exact opposite issue 😝 .. mutations are unexpectedly triggering refetch of "cache-and-network" queries, even with `refetchQueries` set explicitly to `[]` (no queries should be refetched). Ugh. And for some reason it happens **after** the mutation request.
