### ISSUE TITLE
Error during call for mutation: Cannot set property 'status' of undefined

### ISSUE THREAD

**Issue by webjema** [apollographql/apollo-client#7770]
**Intended outcome:**
I'm trying to execute mutation. I expect an apollo client calls a server.

**Actual outcome:**
Error from client's code:
```
Cannot set property 'status' of undefined
* http://192.168.178.24:19000/app%5Cindex.ts.bundle?platform=android&dev=true&hot=false&minify=false:456794:29 in ApolloError
- node_modules\zen-observable\lib\Observable.js:134:6 in notifySubscription
* http://192.168.178.24:19000/app%5Cindex.ts.bundle?platform=android&dev=true&hot=false&minify=false:165698:22 in onNotify
- node_modules\zen-observable\lib\Observable.js:234:11 in next
* [native code]:null in forEach
- node_modules\@apollo\client\utilities\utilities.cjs.js:859:11 in makeEmptyData
- node_modules\@apollo\client\utilities\utilities.cjs.js:946:32 in observersWithMethod.forEach$argument_0
- node_modules\zen-observable\lib\Observable.js:134:6 in notifySubscription
* http://192.168.178.24:19000/app%5Cindex.ts.bundle?platform=android&dev=true&hot=false&minify=false:165698:22 in onNotify
- node_modules\zen-observable\lib\Observable.js:234:11 in next
- node_modules\@apollo\client\link\http\http.cjs.js:179:21 in createHttpLink
- node_modules\react-native\node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
- node_modules\react-native\node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:130:14 in _callTimer
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:181:14 in _callImmediatesPass
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:441:30 in callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:387:6 in __callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:135:6 in __guard$argument_0
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:134:4 in flushedQueue
* [native code]:null in flushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue
```

**How to reproduce the issue:**
To be honest, I do not know how to set up an environment to reproduce this issue (I've checked your react-apollo-error-template), but I will share with you some examples, maybe it will help.
I have a schema (used with AWS Amplify as well):
```
enum StatusesEnum {
  ACTIVE
  IN_REVIEW
  DISABLED
}

type TestType {
  id: Int
  name: String
  short_description: String
  long_description: String
  status: StatusesEnum
  comments_quantity: Int
  change_history: [String]
  proposed_versions: [String]
}

input TestTypeInput {
  id: Int
  name: String
  short_description: String
  long_description: String
  status: StatusesEnum
}

type Mutation {
  editTestType(input: TestTypeInput!): String
}
```
I prepare TestTypeInput variable and do a call:
```
this.graphqlClient().mutate<EditTestTypeMutation>({mutation:gql(mutations.editTestType), variables: { input: testTypeInput }}).then(result => { /* work with results */})
```
And my client initialization:
```
    static getClient(url: string, token: string) : ApolloClient<NormalizedCacheObject> {
        const awsGraphqlFetch = (uri:any, options:any) => {
            options.headers["Authorization"] = token;
            return fetch(uri, options);
        };
        const httpLink = createHttpLink({
            uri: url,
            fetch: awsGraphqlFetch
          });
        return new ApolloClient({
            cache: new InMemoryCache(),
            link: httpLink
        });
    }
```
Queries work fine and other mutations too, but this mutation with "id: Int" works weird. It does not accept "null" or 0 or negative value (or any strings) for id. After I assigned some positive value - no errors. But later, after I've tried to use the value "1" again, it stops accepting it again. Any other positive value works.
When I say "It does not accept", it means I see the error above and no call to a server happens.

Any ideas what may be wrong? Some cache issue? Typing issue?
As it says about "status" (one of object property), may it be an enum string issue bug? I'm lost.

Examples:
```
testTypeInput.id = 55; // works (several times now)
testTypeInput.id = 1; // error as mentioned above (but few times it worked)
testTypeInput.id = 0; // error as mentioned above
testTypeInput.id = -1; // error as mentioned above
testTypeInput.id = null; // error as mentioned above
testTypeInput.id = "1"; // string type. Variable 'id' has an invalid value. Expected type 'Int' but was 'String'.
```
The last error has a very similar stack trace.

Please let me know if more details are required. I'm blocked now with this issue and have no idea how to fix it.

**Versions**
  System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 88.0.4324.182
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.81)
  npmPackages:
    @apollo/client: ^3.3.10 => 3.3.10
    apollo-cache-inmemory: ^1.6.6 => 1.6.6
    apollo-link: ^1.2.14 => 1.2.14
    apollo-link-http: ^1.5.17 => 1.5.17

**Comment by jcreighton** [comment]
@webjema Think you could get a small, runnable reproduction working with [Snack](https://snack.expo.io/)? I know it's harder to create reproduction for React Native so maybe this could help.

**Comment by webjema** [comment]
Thank you @jcreighton !
I've tried to create a mini-project there but looks like ApolloClient does not work there at all.
No reactions, no errors on client.mutate call https://snack.expo.io/@webjema/expo-typescript

**Comment by jcreighton** [comment]
@webjema The reason that example isn't working is that it's not a truly runnable example. The `uri` is set to google.com and we do need a runnable reproduction. I did [modify the react-apollo-error-template](https://codesandbox.io/s/vigilant-frog-hlxcu?file=/src/App.js) to run a mutation with input (and modified `id` to `Int` instead of `ID`) and I'm not seeing any issues. That's _likely_ pointing to an issue with your setup (schema or otherwise).

**Comment by webjema** [comment]
Ok. I've reproduced it in codesandbox.io with React App.
The problem is on the server-side, not on the client.
Thank you for your help! :)
