### ISSUE TITLE
Ignore networkError for cancelled call 

### ISSUE THREAD

**Issue by UmangThapliyal** [apollographql/apollo-client#7771]
I am using apollo 3.3.0 in my react app and when a user comes to the page ```login``` and then immediately ```logout``` or change page the component will be unmounted in the meanwhile the calls which are fetching data will be cancelled. once they are cancelled I am getting an networkError failed to fetch. this is annyoing is there a way to avoid this issue

**Comment by jcreighton** [comment]
@UmangThapliyal Happy to help but I'm not sure what this issue is regarding: are you asking a question or reporting a bug? If you think this is a bug, a runnable reproduction using either [this repo](https://github.com/apollographql/react-apollo-error-template) or [this CodeSandbox](https://codesandbox.io/s/condescending-fermi-07u2p) would be super helpful!

**Comment by UmangThapliyal** [comment]
> @UmangThapliyal Happy to help but I'm not sure what this issue is regarding: are you asking a question or reporting a bug? If you think this is a bug, a runnable reproduction using either [this repo](https://github.com/apollographql/react-apollo-error-template) or [this CodeSandbox](https://codesandbox.io/s/condescending-fermi-07u2p) would be super helpful!

wanted to fist ask that if that is intended behaviour if not I can add codesandbox and reproduce the error. If that is something intended how can I get past that

**Comment by jcreighton** [comment]
@UmangThapliyal I can't tell from the written example what is happening, whether it's an expected error or not. A reproduction would be a good idea.

**Comment by hwillson** [comment]
If someone can provide a small runnable reproduction that demonstrates this happening with `@apollo/client@latest`, we'll take a closer look. Thanks!

**Comment by UmangThapliyal** [comment]
> If someone can provide a small runnable reproduction that demonstrates this happening with `@apollo/client@latest`, we'll take a closer look. Thanks!

Was not able to do properly in codesandbox will try to host a small app for this
