### ISSUE TITLE
Reactive Vars: Best way to show current state when debugging

### ISSUE THREAD

**Issue by chrismowbraybv** [apollographql/apollo-client#7781]
With the move from the `useQuery`/`@client` pattern to `useReactiveVar()` for accessing local state, I have lost the ability to check the current state at any point in time.

I was able to hack around it previously by doing something like this:
```
export const cache = new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        notesState: {
          read() {
            console.log(notesVar()); // FOR DEBUGGING
            return notesVar();
          }
        }
      }
    }
  }
});
```

I get that this was a bit of a hack in the first place. Is there an equivilant way I can view/debug the current state for all reactive vars? Better yet, is there plans for integrating the Apollo dev tools?

Cheers,
Chris

**Comment by chrismowbraybv** [comment]
Same sort of issue outlined [here](https://github.com/apollographql/apollo-client-devtools/discussions/391)

**Comment by benjamn** [comment]
@chrismowbraybv This is definitely an area where the new version of https://github.com/apollographql/apollo-client-devtools could help (not yet implemented, but feasible).

**Comment by hwillson** [comment]
We're targeting devtools Reactive Variable support for [May](https://github.com/apollographql/apollo-client-devtools/blob/main/ROADMAP.md#release-32-may-2021) ...🤞

**Comment by hwillson** [comment]
We're tracking this here: https://github.com/apollographql/apollo-client-devtools/discussions/391 - thanks!
