### ISSUE TITLE
HttpLink uri configuration from async-storage

### ISSUE THREAD

**Issue by rtipnis** [apollographql/apollo-client#7795]
HttpLink uri property can not be initialized with async functions, only sync. So what's the best way to dynamically assign a URI (from configuration such as storage) to this property? 

A few different solutions I've tried:
-- Use ApolloClient's uri property instead and read the uri from storage prior to new'ing ApolloClient.
-- Use split() to then choose at the query/mutation call time.

Some examples demonstrating this would've been great. This is such a common use case, yet all examples show static uris being assigned to httplink's uri property.

**Comment by benjamn** [comment]
@rtipnis This is an interesting idea!

One of my goals for the [cache persistence](https://github.com/apollographql/apollo-client/blob/main/ROADMAP.md#35) functionality that we have planned for Apollo Client v3.5 is to make it easier for any kind of async initialization work to be rolled up in a single `client.ready` promise, which I think could potentially help here, though I'm waving my hands at something we haven't implemented yet.

In the meantime, I think the simplest approach is to construct `ApolloClient` asynchronously, and pass in your own `HttpLink`:
```ts
import { ApolloClient, InMemoryCache, HttpLink } from "@apollo/client";

readUriAsync().then(uri => {
  return new ApolloClient({
    link: new HttpLink({ uri }),
    cache: new InMemoryCache(...),
  });
}).then(client => {
  // initiate application rendering
});
```
