### ISSUE TITLE
Incomplete fix: Avoid all sub-package imports from graphql npm package

### ISSUE THREAD

**Issue by xpdmk** [apollographql/apollo-client#7807]
**Intended outcome:**

In response to issue https://github.com/apollographql/apollo-client/issues/7184, pull request https://github.com/apollographql/apollo-client/pull/7185 removed all sub-package imports from graphql npm package.

**Actual outcome:**

Subdirectory import from graphql is still left:
https://github.com/apollographql/apollo-client/blob/0728754db9ae0b72ba69cbee727d53a3b732ec11/src/link/http/createHttpLink.ts#L2

visit function is exported from graphql npm package here:

https://github.com/graphql/graphql-js/blob/fe9ea6db90a12c88d6372f88b61ca68e7aa3659b/src/index.js#L191

**Versions**

@apollo/client, v3.3.0 -> v3.3.11

**Related**

Mention related to this ("Internally, Apollo Client now avoids nested imports from the graphql package") in changelog: https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#potentially-breaking-changes

**Comment by benjamn** [comment]
@xpdmk Thanks for catching this! My fix will be in the next patch release of `@apollo/client`, unless you need it sooner?

**Comment by xpdmk** [comment]
No problem. I can wait for the next patch. Thanks!
