### ISSUE TITLE
Module not found: Can't resolve 'apollo-client' in 'C:\Users\........\frontend\node_modules\@apollo\react-hoc\node_modules\@apollo\react-components\node_modules\@apollo\react-hooks\lib'

### ISSUE THREAD

**Issue by arti-makadia** [apollographql/apollo-client#7809]
I am new to reactjs, I am working on a app. everything worked.
When I am trying to connect GraphQL with ReactJS, When I type npm start, I receive below error:

 Failed to compile.

./node_modules/@apollo/react-hoc/node_modules/@apollo/react-components/node_modules/@apollo/react-hooks/lib/react-hooks.esm.js
Module not found: Can't resolve 'apollo-client' in 'C:\Users\.........\frontend\node_modules\@apollo\react-hoc\node_modules\@apollo\react-components\node_modules\@apollo\react-hooks\lib'

This is my package.json file
{
"name": "xyz",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@apollo/client": "^3.4.0-beta.12",
    "@apollo/react-components": "^4.0.0-beta.2",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "graphql": "^15.5.0",
    "react": "^17.0.1",
    "react-apollo": "^3.1.5",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.2",
    "web-vitals": "^1.0.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

**Comment by benjamn** [comment]
@arti-makadia Instead of using `@apollo/react-components`, try `@apollo/client/react/components` (which comes with `@apollo/client` now)? Also, if you can remove `react-apollo` from your dependencies, you should do so, since that package is no longer compatible with Apollo Client v3.

**Comment by arti-makadia** [comment]
Thanks, It works for me.
