### ISSUE TITLE
ApolloProvider useQuery combination does not fetch data from AWS AppSync, in React project

### ISSUE THREAD

**Issue by ohmyskyhigh** [apollographql/apollo-client#7816]
## Issue

Due to the compatible issue, I am using ApolloClient to form my AWS AppSync API client, so that I can use ApolloProvider to pass the client to different sub-component.

**Intended outcome:**
After I setup my ApolloProvider in the top level, I should be having a sweet data return from useQuery in my sub-Component
**Actual outcome:**
In the sub-component, I call useQuery to fetch data, but the problem is the output always give me default "undefined" value.

### Code in the Top Level
```
import awsconfig from '../aws-exports';
import { AUTH_TYPE } from 'aws-appsync';
import {
  ApolloProvider,
  ApolloClient,
  ApolloLink,
  HttpLink,
  InMemoryCache,
} from "@apollo/client";
import { createAuthLink } from "aws-appsync-auth-link";
import { getUserDb, listUserDbs } from '../graphql/queries';

const link = ApolloLink.from([
  createAuthLink({
    url: awsconfig.aws_appsync_graphqlEndpoint,
    region: awsconfig.aws_appsync_region,
    auth: {
      type: AUTH_TYPE.API_KEY,
      apiKey: awsconfig.aws_appsync_apiKey,
    },
  }),
  new HttpLink({ uri: awsconfig.aws_appsync_graphqlEndpoint }),
]);

const client = new ApolloClient({
  link,
  cache: new InMemoryCache(),
  credentials: 'include'
});

function WithProvider (){
  return (
    <ApolloProvider client={client}>
      <App />
    </ApolloProvider>
  )
}

export default WithProvider;
```
### Code in Sub-Component
```
import { listUserDbs } from '../graphql/queries';
const GET_USER_PROFILE = gql(listUserDbs)

function App() {
  const { loading, error, out_data, client } = useQuery(GET_USER_PROFILE);
  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error :(</p>;
  // output: out_data = undefined
```

## What test have I done?
1. when I call query straight from client, it worked
```
client
  .query({
    query: gql`
      query ListUserDbs(
        $filter: Table
      ) {
        listUserDBS(filter: $filter) {
          items {
            sub
          }
          nextToken
        }
      }
    `
  })
  .then(result => console.log(result));
```
2. when I ask useQuery to return client, it returns the same client I set up
```
const { loading, error, out_data, client } = useQuery(LIST_USER_PROFILE);
```
3. when I use useApolloClient in the same sub-somponent, is worked;
```
const client = useApolloClient();
client
  .query({
    query: gql`
      query ListUserDbs(
        $filter: Table
      ) {
        listUserDBS(filter: $filter) {
          items {
            sub
          }
          nextToken
        }
      }
    `
  })
  .then(result => console.log(result));
```

## Versions
```
  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 12.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.6.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @apollo/client: ^3.3.11 => 3.3.11
     "aws-appsync": "^4.0.3",
    "aws-appsync-auth-link": "^2.0.3",
    "aws-appsync-react": "^4.0.3",
```

## My Initial Guess 
The issue is probably coming from useQuery but I don't know how to solve it and I don't know why it has such issue

**Comment by benjamn** [comment]
@ohmyskyhigh Can you tell if the `useQuery` you're using triggers a network request? If so, does it succeed? Does this failure seem consistent with what would happen if the credentials were somehow not getting sent?

**Comment by ohmyskyhigh** [comment]
> @ohmyskyhigh Can you tell if the `useQuery` you're using triggers a network request? If so, does it succeed? Does this failure seem consistent with what would happen if the credentials were somehow not getting sent?
> 
> Ideally, a [reproduction](https://github.com/apollographql/react-apollo-error-template/) would help us diagnose the problem, but I realize it may be hard to reproduce authentication-related bugs without sharing sensitive tokens.

Using client.query triggers a fetch request
Using useQuery does not trigger anything

**Comment by tsesamson** [comment]
I have my setup similar to yours and using graphql queries from amplify codegen in graphql folder and using Apollo client 3 with appsync.

```
import { listUserDbs } from '../graphql/queries';
const GET_USER_PROFILE = gql(listUserDbs)

function App() {
  const { loading, error, out_data, client } = useQuery(GET_USER_PROFILE);
  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error :(</p>;
```

However, the error that I'm getting from useQuery hook is 

> **Unhandled Rejection (Invariant Violation): Expecting a parsed GraphQL document. Perhaps you need to wrap the query string in a "gql" tag?**

**Comment by ohmyskyhigh** [comment]
`listUserDbs` is in graphQL language. Something like this:

```
export const getUserDb = /* GraphQL */ `
  query GetUserDb($sub: String!) {
    getUserDB(sub: $sub) {
      sub
      phone_number
      username
    }
  }
`;
```
