### ISSUE TITLE
useSubscription is missing context option

### ISSUE THREAD

**Issue by toxeus** [apollographql/apollo-client#7824]
The `useSubscription` hook [lacks](https://www.apollographql.com/docs/react/api/react/hooks/#options-3) the `context` option which is useful to drive Apollo Link. This is inconsistent with all the other hooks and seems to be an oversight. Please, consider also adding the `context` option to `useSubscription`.

**Comment by benjamn** [comment]
@toxeus You're right, and this seems worthwhile to fix. We'll take a look!
