### ISSUE TITLE
Still present react-hooks.esm.js error - problem with migration to apollo 3

### ISSUE THREAD

**Issue by acidcrash2005** [apollographql/apollo-client#7829]
**Intended outcome:**
How I understand, when migrating to apollo 3 we can remove all `apollo-client` dependency. It is telling here in migrate tutorial - https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/#apollo-client. 

But it is not actually correct!

**Actual outcome:**
I'm getting this error when I remove all dependency of old `apollo-client`:
```
/node_modules/@apollo/react-hooks/lib/react-hooks.esm.js
Module not found: Can't resolve 'apollo-client' in '/Users/dusty/distant/distant-app/node_modules/@apollo/react-hooks/lib'
```
It is very strange because in this issue tells that all done. There was this problem, but everything was resolved! - https://github.com/apollographql/apollo-client/issues/6475 

But if look in the `package.json` we can see, that old `apollo-client` still in `peerDependencies`. And also needs to be installed in project like peer dependencies.

![image](https://user-images.githubusercontent.com/11617578/110895859-1d05ec00-8303-11eb-8e92-6598ab0fd3f6.png)

**How to reproduce the issue:**
To reproduce the issue, just need to install new apollo 3 with all dependency and remove the old  `apollo-client` from the project.
Because now in `@apollo/react-hooks`, `@apollo/react-common`,`@apollo/react-hoc`,`@apollo/react-components` still using old packages like peer dependencies.

![image](https://user-images.githubusercontent.com/11617578/110896936-3ad45080-8305-11eb-8e98-f43e7d7ecfda.png)
![image](https://user-images.githubusercontent.com/11617578/110896971-4758a900-8305-11eb-8e49-18583a8b177b.png)
![image](https://user-images.githubusercontent.com/11617578/110897003-52133e00-8305-11eb-9b87-fbac8acab0bc.png)

**Versions**

**System:**
  - OS: Linux 5.10 Debian GNU/Linux 10 (buster) 10 (buster)
 
**Binaries**:
  - Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
  - Yarn: 1.18.0 - /usr/bin/yarn
  - npm: 7.5.2 - ~/.nvm/versions/node/v14.15.4/bin/npm
  
**Browsers:**
   - Chrome: 89.0.4389.82
   - Firefox: 78.8.0esr
   
**npmPackages:**
   - @apollo/client: ^3.3.11 => 3.3.11 
   - apollo-client: ^2.6.10 => 2.6.10 
   - apollo-link-logger: ^1.2.3 => 1.2.3 
   - apollo-upload-client: ^14.1.3 => 14.1.3 
   - react-apollo: ^3.1.3 => 3.1.3

**Comment by benjamn** [comment]
@acidcrash2005 The `@apollo/react-*` packages are also obsolete, and should now be replaced with imports from `@apollo/client/react/*`: https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/#updating-imports

**Comment by acidcrash2005** [comment]
@benjamn I`m done with this, and in the project have all imports from `@apollo/client`. Any imports from `@apollo/react-*`
![image](https://user-images.githubusercontent.com/11617578/111026648-0095ac80-83f4-11eb-90af-f3e250d6e63f.png). But it is not help

**Comment by acidcrash2005** [comment]
And I do not understand how this explains, that in new version package has perDependancy old version of apollo-client package?

**Comment by acidcrash2005** [comment]
I fixed! Sorry,  after rebase have imports from old `apollo-client`!
