### ISSUE TITLE
Refetch query ignores recent change to local storage

### ISSUE THREAD

**Issue by newtoniumx3** [apollographql/apollo-client#7844]
**Intended outcome:**

When using useMutation we are able to manually call the mutation and execute a sychronous action right after such as a write to local storage. 

**Actual outcome:**

If a refetch query is specified, it seems that recent local storage is not up to date. The refetch query is performed on an outdated local storage not detecting the recent entry into local storage.

**How to reproduce the issue:**

# apollo setup
```
import { cache } from 'libraries/apollo/cache';
import { resolvers } from 'libraries/apollo/resolvers';
import withApollo from 'next-with-apollo';

const authLink = setContext((_, { headers }) => {
  const mytoken= localStorage.getItem('mytoken'); // // <----- this should have been set on just finished mutation but is still empty

  return {
    headers: {
      ...headers,
      Authorization: token ? `Bearer ${mytoken}` : "",
    }
  }
});


function createClient({ headers }) {
  return new ApolloClient({
    link: authLink.concat(createHttpLink({ uri: 'http://localhost:2222',  credentials: 'include' })),
    cache: cache,
    resolvers: resolvers
  })
}

export default withApollo(createClient);
```

# mutation action
```
const response = yield call(authInMutation, {
  variables: {
    username: email,
    password: password
  }
});
localStorage.setItem("mytoken", response.data.access_token) // <----- write to local storage after successful sign in
```

# queries & mutations
```
const AUTH_IN_MUTATION = gql`
  mutation AUTH_IN_MUTATION($email: String!, $password: String!) {
    auth_in(input: { email: $email, password: $password }) {
      message
    }
  }
`;

const AUTH_REFRESH_QUERY= gql`
  query AUTH_REFRESH_QUERY{
      session
  }
`;

const [authInMutation, { loading, data, error }] = useMutation(AUTH_IN_MUTATION , {
  refetchQueries: [{
    query: AUTH_REFRESH_QUERY // <--- refetch this query after successful sign in
  }]
});
```

**Versions**

```
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 15.8.0 - ~\scoop\apps\nodejs\current\node.EXE
    Yarn: 1.22.10 - ~\scoop\apps\nodejs\current\bin\yarn.CMD
    npm: 7.5.1 - ~\scoop\apps\nodejs\current\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.54)
  npmPackages:
    @apollo/client: ^3.3.11 => 3.3.11
    next-with-apollo: ^5.1.1 => 5.1.1
```

**Comment by benjamn** [comment]
@newtoniumx3 Could you wrap up these bits of code in a runnable [reproduction](https://github.com/apollographql/react-apollo-error-template/) (scrubbing any real auth tokens)?

If a reproduction isn't feasible, I would recommend adding some `debugger` statements before the `localStorage.setItem` and `localStorage.getItem` calls, then using the browser devtools to find out in what order those statements are happening. If the `setContext` callback is getting called before `setItem`, that seems like it might explain the behavior you observed. When you're paused on a `debugger`/breakpoint, you can also examine the current execution stack and local variables, to figure out how the program got to that point.

Again, a reproduction would be great, but with any luck my suggestion above will lead you to some additional clues.

**Comment by newtoniumx3** [comment]
Thanks! I'll try this right now and try to reproduce as well in a simpler environment.

**Comment by newtoniumx3** [comment]
I just did a couple more test like you suggested and yes it does seem like the fetch gets triggered post mutation which means I don't get to perform any action before the refetch happens. 

This is my latest test 
```
      const response = yield call(async () => {
          const response = await authinMutation({
            variables: {
              username: user.email,
              password: user.password
            }
          }); // <---- this calls my mutation, gets an answer but then calls my refetch
          debugger; <---- my refetch already occured by the time I get here
          return response;
        }
```

I will attempt a simpler re-production next.

**Comment by newtoniumx3** [comment]
I'm having a hard time re-creating a simpler environment as its got some complex config with nextjs, apollo and redux-saga all together. This could potentially be related to the integration with saga and the flow of execution.

Although upon closer look, isn't it normal that the refetch occurs during the mutation call? Since it's part of the mutation execution configuration? If it didn't refetch during that call, how then would you instruct it to refetch the queries at a later time?

I'm going to debug this a little more and try to make this into a separate repo, if I can't reproduce today I'll close this today until I can. Thank you for your assistance.

**Comment by newtoniumx3** [comment]
I decided to switch to cookie based for now which resolves the issue as the storing of the cookie happens behind the scenes.
