### ISSUE TITLE
Apollo Client Devtools conflicts with es6-module-loader js

### ISSUE THREAD

**Issue by kingstonfung** [apollographql/apollo-client#7845]
**Intended outcome:**
The plugin shouldn't interfere with, or blocking the site's JS

**Actual outcome:**
I see a JS error complaint saying `process.platform` is undefined, therefore `.match()` is unavailable

![Screen Shot 2021-03-15 at 10 32 34 AM](https://user-images.githubusercontent.com/10535453/111193762-251e8f80-8580-11eb-818b-bb1bf8c5a7f9.png)

**How to reproduce the issue:**
1. Include / embed the [ES6 Modules JS](https://github.com/nfl/es6-module-loader/blob/master/dist/es6-module-loader.js) to your html page (along with a sample React + Apollo project to ensure Devtools will be triggered and turned on)
2. At the end of the JS, try to render something on the DOM such as `document.body.innerHTML += "HELLO WORLD";`
3. With Apollo Client Devtools enabled, open up this project
4. Console should indicate an error saying `Cannot read property 'match' of undefined` and **you should not be able** to see HELLO WORLD.
5. If you turn off the plugin, everything works fine

**Versions**
Apollo Client Devtools 3.0.0
https://chrome.google.com/webstore/detail/apollo-client-devtools/jdkknkkbebbapilgoeccciglkfbmbnfm

Prior to Devtools 3.0.0, my project worked fine without issues with Apollo Client Devtools.

If more info are needed, or if the team decides this module is simply too old to support (understandable), please just let me know! Thanks very much.

**Comment by hwillson** [comment]
Thanks @kingstonfung - we're looking into this (and tracking things in https://github.com/apollographql/apollo-client-devtools/issues/455).
