### ISSUE TITLE
Using refetchQueries doesn't update networkStatus and loading of QueryRef

### ISSUE THREAD

**Issue by SomebodyOdd** [apollographql/apollo-client#7848]
https://stackblitz.com/edit/angular-ivy-dfykj7

**Intended outcome:**
I want to have a "loading" indicator every time refetch is in progress, including ones that arise from _refetchQueries_.
I set _notifyOnNetworkStatusChange_ to true and subscribed to status changes in order to update my _loading_ status for component. I expect _loading_ to be true every time there is a refetch.

**Actual outcome:**
While calling a _refetch_ does update _networkStatus_ and _loading_ fields (as indicated in repro), calling a mutation that has _refetchQueries_ set doesn't. So I have no way of knowing if loading is in progress, except actively waiting on a promise, returned by _mutate_ (and adding _awaitRefetchQueries_ to every mutation call, that is not in repro).

**How to reproduce the issue:**
1. Open a repro project at the link above
2. Use buttons to initiate a refetch or mutation.
3. _loading_ and _mutating_ variables are displayed, so you can make sure it doesn't work. Also, all value changes are logged to a console for convinience.

**Versions**
apollo-angular: 2.4.0
@apollo/client: 3.3.12
Check out StackBlitz dependencies tab for more.

**Comment by SomebodyOdd** [comment]
Anyone?

**Comment by andreialecu** [comment]
You should be able to use something like `loading || networkStatus === NetworkStatus.refetch` to detect both initial loading and refetches.

**Comment by SomebodyOdd** [comment]
@andreialecu except that there is no status updates whatsoever. Check out repro link and pay attention to console output. Calling _AddProduct_ mutation does not raise _valueChanges_ update until the very end of implicit reloading. So, from perspective of _valueChanges_ subscriber, there is never _networkStatus_ other than _NetworkStatus.ready_ when calling mutations! Refetch does trigger proper change to NetworkStatus.refetch, but that's not the point.

Retested right now on 3.3.15 version of @apollo/client, issue is still there.

**Comment by andreialecu** [comment]
Oh, I didn't realize this was `apollo-angular`. I think you may need to open this in https://github.com/kamilkisiela/apollo-angular instead.

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-client/issues/7848#issuecomment-826550187, this issue is better raised in the https://github.com/kamilkisiela/apollo-angular repo. Thanks!
