### ISSUE TITLE
Broken local state

### ISSUE THREAD

**Issue by ifndefdeadmau5** [apollographql/apollo-client#7853]
**Intended outcome:**

This is related to, or dupe of #7417 (and am also curious why that issue haven't addressed for that long time 🤷 )
Below query was working with apollo-client v2

```js
// Query 1
export const GET_LOCAL_STATE = gql`
  query {
    isAuthenticated @client
    user @client {
      id
    }
  }
`;
```
but in v3 it returns `{ error: undefined: data: undefined }` which makes no sense, because if data turns out empty error should be presented.

However when I remove nested field from it like below, it works

```js
// Query 2
export const GET_LOCAL_STATE = gql`
  query {
    isAuthenticated @client
  }
`;
```

**Actual outcome:**
`Query 1` should just work out of the box, and this wasn't documented as a breaking change of v3

**How to reproduce the issue:**

Fire query above with useQuery hook

**Versions**

`"@apollo/client": "^3.3.12",`

**Comment by benjamn** [comment]
@ifndefdeadmau5 Are you passing any local state `resolvers` to the `ApolloClient` constructor?

**Comment by ifndefdeadmau5** [comment]
@benjamn I'm passing an empty object to the constructor

```
const client = new ApolloClient({
  ...
  resolvers: {},
  ...
});
```

**Comment by hwillson** [comment]
If someone can provide a small runnable reproduction that demonstrates this happening with `@apollo/client@latest`, we'll take a closer look. Thanks!
