### ISSUE TITLE
Using TS number type causes Apollo Client to handle it as a string by adding quotation marks ""

### ISSUE THREAD

**Issue by SubZane** [apollographql/apollo-client#7857]
The following code will return error 500 (the lack of details in the error reporting from apollo client is an issue in itself). When inspecting using the apollo chrome extension I can see that the variable is passed as "123" instead of 123.
```javascript
type payloadType = {
  db_engine: number
}
const { loading: DataIsLoading, data: DataConnection, error: DataError } = useQuery<DataType, DataTypeVariables>(QUERY, {
	errorPolicy: 'all',
	variables: { db_engine_id: payload.db_engine },
})
```

Doing like this works, however
```javascript
type payloadType = {
  db_engine: string
}
const { loading: DataIsLoading, data: DataConnection, error: DataError } = useQuery<DataType, DataTypeVariables>(QUERY, {
	errorPolicy: 'all',
	variables: { db_engine_id: parseInt(payload.db_engine) },
})
```

**Comment by benjamn** [comment]
@SubZane How are you declaring the `$db_engine_id` variable in your `QUERY`?

**Comment by SubZane** [comment]
A very good question! which made me think!

It appears that even though it's type-scripted as `number`, it's value is a string when inspected. The Typescript really doesn't care it seems.
