### ISSUE TITLE
Docs inconsistency for `cache.modify`

### ISSUE THREAD

**Issue by vonkanehoffen** [apollographql/apollo-client#7862]
The `AddTodo` example for `cache.modify` [here](https://www.apollographql.com/docs/react/data/mutations/#making-all-other-cache-updates) should match the API spec [here](https://www.apollographql.com/docs/react/api/cache/InMemoryCache/#modify)

The example misses `id` from it's parameters despite it being marked as required:
```
update(cache, { data: { addTodo } }) {
      cache.modify({
        fields: {
          todos(existingTodos = []) {
            const newTodoRef = cache.writeFragment({
              data: addTodo,
              fragment: gql`
                fragment NewTodo on Todo {
                  id
                  type
                }
              `
            });
            return [...existingTodos, newTodoRef];
          }
        }
      });
```
...leaving me pretty confused as to how this is meant to work! Lots of places in the docs talk about the id being required, then this example doesn't show one, then the API docs say it is... and to add to the confusion, on `interface ModifyOptions` in `src/cache/core/types/Cache.ts` it's also optional. Which is it?

**How to reproduce the issue:**

Look at the docs. Note inner confusion ;)

**Versions**

  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/Code/scratch/node_modules/.bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 86.0.1
    Safari: 14.0.3

**Comment by vonkanehoffen** [comment]
...actually is it actually the API doc that's wrong here, not the example? https://www.apollographql.com/docs/react/api/cache/InMemoryCache/#modify

ID is only required if you're modifying a specific object, but can be omitted if you're modifying a query?

**Comment by benjamn** [comment]
> ID is only required if you're modifying a specific object, but can be omitted if you're modifying a query?

@vonkanehoffen That's correct. Omitting the `id` is like calling `cache.modify({ id: "ROOT_QUERY", fields })`, since `ROOT_QUERY` happens to be the hard-coded ID of the root query singleton object.
