### ISSUE TITLE
I can't disable saving data from subscription to cache

### ISSUE THREAD

**Issue by kerf007** [apollographql/apollo-client#7889]
Hello, 
I need to disable caching data in subscription because I want define custom logic for updating cache.
So I create subscription with `fetchPolicy: 'no-cache'` but it seems doesn't work because when subscription receives new data I see in apollo dev tools that cache is inserted new item and it doesn't depend which fetchPolicy I use.
My subscription looks like:

```
apiClient.subscribe({
  query: objectListScheme.listenObjectList,
  variables: {
    topic: `objects:${getTokenId()}`
  },
  fetchPolicy: 'no-cache'
})
``` 

May be I do something wrong and thanks for reply.

**Versions**
System:
    OS: macOS 10.15.7
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 80.0
    Safari: 14.0
  npmPackages:
    @apollo/client: ^3.3.12 => 3.3.12

**Comment by brainkim** [comment]
@kerf007 If you have a reproduction, that will greatly increase my ability to get to this issue :smile:. Otherwise, I will try to get to this as soon as I can. Thanks for opening this issue!

**Comment by kerf007** [comment]
@brainkim thank you for your feedback, but I recognized that it's my fault. Before getting data in my subscription I had performed mutation and the response after this one has been saved in cache and immediately after that I received the same data in my subscription. So it seemed to me that the data was already in the cache.

I'll close the issue, thank you.

**Comment by brainkim** [comment]
Ah, I see! Good to know. Thanks for reaching out anyways.
