### ISSUE TITLE
WithApolloClient types client as optional

### ISSUE THREAD

**Issue by billsaysthis** [apollographql/apollo-client#7899]
**Intended outcome:**
Trying to migrate to V3 and unlike in V2 the client prop is set as optional, this creates issues in our existing codebase because everywhere I use client is flagged as potentially undefined. I know this is deprecated but for migration purposes I need to use this for the time being.

**Actual outcome:**
This is a blocker for us, not sure what other actual outcome I can add here.

**How to reproduce the issue:**
From the types:
```
export declare type WithApolloClient<P> = P & {
    client?: ApolloClient<any>;
};
```

**Versions**
3.3.12

**Comment by brainkim** [comment]
@billsaysthis I’m sorry to hear you’re having trouble with types! I’m trying to track down why the `client` prop was marked as optional.

In the meantime, I typically try to never let anything like TypeScript get in the way of shipping. If you’re not familiar there are a couple of temporary workarounds you could use to fix this problem:
```tsx
import {ApolloClient} from "@apollo/client";
import type {WithApolloClient} from "@apollo/client/react/hoc";

declare const w: WithApolloClient<{}>;

// option 1: non-null assertion operator 
const client1: ApolloClient = w.client!;

// option 2: as operator
const client2: ApolloClient = w.client as ApolloClient; // or `any`

// option 3
// @ts-ignore: fix when this issue is resolved https://github.com/apollographql/apollo-client/issues/7899
const client3: ApolloClient = w.client;
```

I know it’s non-ideal, but if you’re just trying to upgrade, maybe you can do this for now and fix it later? 

Potentially related issues:
https://github.com/apollographql/react-apollo/issues/3392
https://github.com/apollographql/react-apollo/pull/3538/

**Comment by billsaysthis** [comment]
Thanks for the prompt response.
