### ISSUE TITLE
Merging Apollo cache correctly

### ISSUE THREAD

**Issue by kfazinic** [apollographql/apollo-client#7903]
This is an example of a query I have, where I request `people` data in the same query: once with filters and once without. 

I'm having an issue with `facets` in `data.facetsWithoutFilters`  overwriting `facets` in `data.people`. Not sure I set the `typePolicies` correctly, would appreciate help. 

```
  query People($q: String!, $filters: [String]) {
    people(q: $q, filters: $filters) {
      resources { id name city country }
      facets {
        name
        buckets {id label count}
      }
      numberOfMatches
    }
    facetsWithoutFilters: people(q: $q, filters: []) {
      facets {
        name
        buckets { id label count }
      }
      numberOfMatches
    }
  }
```

In `InMemoryCache` I set: 

```
    cache: new InMemoryCache({
      typePolicies: {
        Query: {
          fields: {
            people: {
              keyArgs: ["q", "filters"],
              merge(existing, incoming) {
                return mergeCollectionData(existing, incoming);
              }
            },
            facetsWithoutFilters: {
              keyArgs: ["q"],
              merge(existing, incoming) {
                return mergeCollectionData(existing, incoming);
              },
            }
          }
       }
    }
```

and this is the merge function: 

```
function mergeCollectionData(existing, incoming) {
  if (!existing) {
    return cloneDeep(incoming);
  }

  const merged = cloneDeep(existing);
  const existingResources = merged?.resources || [];
  const newResources = cloneDeep(incoming?.resources || []);

  merged.resources = uniqBy([...existingResources, ...newResources], "id");

  merged.facets = incoming?.facets
    ? cloneDeep(incoming.facets)
    : existing?.facets;

  return { ...incoming, ...merged };
}
```

**Intended outcome:**
`facets` in `data.people` should be a subset of `facets` in `data.facetsWithoutFilters` objects when `filters` is not an empty array.

**Actual outcome:**
`facets` in `data.people` is always the same as `facets` in  `data.facetsWithoutFilters`. 

**Versions**

  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.57)
  npmPackages:
    @apollo/client: ^3.3.11 => 3.3.11 
    apollo-server: ^2.19.0 => 2.19.0

**Comment by benjamn** [comment]
@kfazinic Field aliases like `facetsWithoutFilters: people(...)` don't make any difference for caching, since they are normalized away before data is written to the cache. In other words, there is no `Query.facetsWithoutFilters` field in your schema, only `Query.people`, so your `facetsWithoutFilters` field policy is ignored by the cache.

To achieve your desired functionality, you might want to swap things around, letting each `Query.people(q)` field hold all people data for that `q`, and then add a policy for a synthetic field like `Query.filteredPeople(q, filters)` to filter that data:
```ts
new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        // Let the Query.people field manage all the people's data, unfiltered.
        people: {
          keyArgs: ["q"],
          merge(existing, incoming) {
            return mergeCollectionData(existing, incoming);
          },
        },

        // Synthetic field, derived from the Query.people data:
        filteredPeople: {
          keyArgs: ["q", "filters"],
          read(existing, { args, readField }) {
            const allPeopleForQuery = readField("people")
            if (allPeopleForQuery) {
              // Apply args.filters to allPeopleForQuery, possibly using readField to
              // read properties from any nested objects that might be References.
              return filterPeople(allPeopleForQuery, args.filters, readField);
            }
            // If you let the read function return undefined, the filteredPeople data
            // will appear missing, which is probably what you want. Alternatively,
            // you could return some default empty people object, if you think that
            // makes more sense for consumers of Query.filteredPeople.
          },
        },
      },
    },
  },
})
```
With those field policies in place, you should be able to use the following query:
```graphql
query People($q: String!, $filters: [String]) {
  people(q: $q, filters: []) {
    resources { id name city country }
    facets {
      name
      buckets {id label count}
    }
    numberOfMatches
  }
  filteredPeople(q: $q, filters: $filters) @client {
    facets {
      name
      buckets { id label count }
    }
    numberOfMatches
  }
}
```
Note the `@client` directive, which keeps the `filteredPeople` field from getting sent to the GraphQL server.

I'm happy to answer any questions you have about that implementation sketch, since I know the devil's in the details.

**Comment by kfazinic** [comment]
Thank you for answering, @benjamn. Since your suggestion implies filtering on the client, it would beat the purpose of back-end filters (a black box which I have no access to) which I need to rely on.
