### ISSUE TITLE
readField functions first argument 

### ISSUE THREAD

**Issue by BayCo** [apollographql/apollo-client#7916]
My cached object has `data({"path":"$.caption.text"})` key with text value in it.
I can't access it using `readField('data({"path":"$.caption.text"})', item)`
The other fields like id or created_at are accessible.

**Comment by benjamn** [comment]
@BayCo I realize this API is under-documented, but `readField` can also take [`ReadFieldOptions`](https://github.com/apollographql/apollo-client/blob/76a60218b3432249a159da47cbd2934eb3e642ce/src/cache/core/types/common.ts#L44), like so:
```ts
readField({
  fieldName: "data"
  args: { path: "$.caption.text" },
  from: item,
})
```
Doing it this way will automatically reuse the same logic that originally serialized the arguments, so you don't have to worry about doing any serialization or string manipulation yourself.

**Comment by BayCo** [comment]
@benjamn it works, thank you for your explanation
