### ISSUE TITLE
Error: Circular structure in "getInitialProps" result of page : Nextjs with apollo client

### ISSUE THREAD

**Issue by joaogarin** [apollographql/apollo-client#7921]
Need help or want to talk all things Apollo Client? Issues here are reserved for bugs, but one of the following resources should help:

* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
https://stackoverflow.com/questions/66842634/error-circular-structure-in-getinitialprops-result-of-page-nextjs-with-apol?noredirect=1#comment118157132_66842634

Hello sorry for posting it here, but I did try stackoverflow (and the spectrum seems sort of broken the url is not working for me)

But any idea what the problem attached might be ? Posting it again in here : 

I am following this guide https://www.apollographql.com/blog/getting-started-with-apollo-client-in-next-js/ to try and convert an app to use nextjs getServersideProps and client side queries. The articles explains it very well how to approach each scenario but I am facing an issue with trying to pass the apolloClient to the apollo provider in _app.js. The main difference to the article is that to initialize the apollo client I need context to read req headers for authenticated state.

I get the error Error: Circular structure in "getInitialProps" result of page "/". https://err.sh/vercel/next.js/circular-structure and indeed inside apolloClient I can see circular structures which means the error makes sense..

How should I go about this? Any ideas / suggestions? 

Inside getInitialProps : 

```
 public static async getInitialProps({ Component, ctx }: any) {
    const apolloClient = createApolloClient({}, ctx);

    ...

    return {
      apolloClient,
      ...
    };
  }
```
 
where createApolloClient returns : 

```
return new ApolloClient({
    connectToDevTools: process.browser,
    ssrMode: !process.browser, // Disables forceFetch on the server (so queries are only run once)
    link: ApolloLink.from([
      authLink.concat(
        ApolloLink.split(
          ({ variables }) => hasFiles(variables),
          createUploadLink({ uri: URL }),
          link,
        ),
      ),
    ]),
    cache: new InMemoryCache({
      // possibleTypes: introspectionQueryResultData,
    }).restore(initialState || {}),
  });
```

I can see that the apolloClient is returning fine, also have used it inside a getServerSideProps and it there works just fine. Only in _app.js this is happening.

Thanks in advance

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
