### ISSUE TITLE
existing is undefined in merge function

### ISSUE THREAD

**Issue by chalupagrande** [apollographql/apollo-client#7928]
I have an application that fetches and paginates "Resources". On page load, my `useQuery` function fetches the first 10 resources. The result looks like this: 

```
{
  "data": {
    "resources": {
      "items": [... all the items...],
      "pageInfo": {
        "cursor": 894,
        "hasNextPage": true,
        "count": 13
      }
    }
  }
}
```
using `useEffect`, I set the "pagination" state of my component to the pagination object returned above. When the user clicks a button to go to the next page or resources, I use `fetchMore` and pass the cursor from the "pagination" state to get the next 10 items. 

The results from this `fetchMore` query then enter my `merge` function (below) and are merged with the items returned from the first `useQuery` call. This all works as expected. : 
```
export function mergeObjectWithItems(existing = {}, incoming = {}, { cache }) {
  const result = {
    ...existing,
    ...incoming,
    items: onlyUnique([...(existing?.items || []), ...incoming.items]),
    pageInfo: { ...existing.pageInfo, ...incoming.pageInfo },
  }
  return result
}
```

However, an issue arrises when I try and delete a resource. My `useMutation` query fires a network request to the backend, and the backend returns a `{"data":{"deleteManyResources":true}}` response. My component re-renders (or perhaps just useQuery re-fires -- I'm not certain) and attempts to fetch resources. However, the pagination details from the previous request are still saved in state, meaning this `useQuery` call now has the pagination arguments as if to get the next page of resources. This, however, should not be an issue, considering my merge function should merge all the results of all the useQuery calls into one array. This is not the case. 

Inspecting the merge function when it fires I can see that the `existing` object is empty. Furthermore, inspecting the cache at this time reveals that the resources property has been entirely deleted. (using the `cache` object passed through merge options to `readQuery` reveals that the ROOT_QUERY doesn't contain any reference to resources, and i get the following error: "Can't find field 'resources' on ROOT_QUERY object")

**Intended outcome:**
The `existing` object would contain an array of resources I had previously loaded. 

**Actual outcome:**
The `existing` object is entirely empty. 

**Further Context:**
Apollo Client Declaration:
```
function createApolloClient() {
  return new ApolloClient({
    link: authLink.concat(httpLink),
    queryDeduplication: true,
    cache: new InMemoryCache({
      typePolicies: {
        Query: {
          fields: {
            resources: {
              keyArgs: (a) => a.input.search,
              merge: mergeObjectWithItems,
            },
          // ..........
          },
        },
      },
    }),
  })
}
```
useQuery for GetResources: 
```
  const initialPageInfoState = {
    cursor: 0,
    hasNextPage: false,
    count: 0,
    page: 0,
    rowsPerPage: 10,
    highestPage: 0,
    highestNumRows: 10,
  }
  
  const [pageInfo, setPageInfo] = useState(initialPageInfoState)
  const { rowsPerPage, page, cursor, count } = pageInfo
 
  // gets the resources
  const { loading, data, error, fetchMore } = useQuery(
    GET_RESOURCES_CATEGORIES_AND_AGENCIES,
    {
      variables: {
        input: {
          search: searchTerm,
          pagination: {
            cursor: cursor, // from component state set after first 
            limit: rowsPerPage,
          },
        },
      },
    }
  )
```

Delete Resources functions: 
```
  // mutation for delete
  const [
    deleteResources,
    { loading: deleteLoading, data: deleteData, error: deleteError },
  ] = useMutation(DELETE_RESOURCES, {
    onCompleted: () => {
      setSelected([])
    },
    update(cache) {
      cache.modify({
        fields: {
          resources(existingResources, { DELETE }) {
            return DELETE
          },
        },
      })
    },
  })

  // calls delete resources and updates selected resources to be empty
  async function handleDeleteResources() {
    deleteResources({
      variables: {
        // convert the string ids into INTs
        input: { ids: selected.map((e) => parseInt(e)) },
      },
    })
  }
```

**My understanding of the possible issue:** 
- The cursor, as part of the component state, being passed to `useQuery` causes Apollo to cache those results separately (despite my merge function for some reason), and thus existing state is empty. 
- Perhaps it has something to do with the fact that my delete request is a "deleteManyResources" request. And perhaps I am deleting the entirety (rather than just 1) of the cached resources by passing the `DELETE` object. 

**Versions**
```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Edge: 89.0.774.63
    Firefox: 85.0
    Safari: 14.0.3
  npmPackages:
    @apollo/client: 3.1.1 => 3.1.1
```

**Comment by benjamn** [comment]
@chalupagrande Could you try putting these code snippets into a runnable [reproduction](https://github.com/apollographql/react-apollo-error-template/)? A reproduction would provide clarity on questions like whether/why the mutation `update` function is running before the `merge` function (which would seem to explain the undefined `existing` data, though I'm sure I'm misunderstanding something here). Thanks!

**Comment by chalupagrande** [comment]
Found the problem!
Considering the information I'm getting back from the server is a response object, and not a normalized/serializable object my cache looked something like this: 
```
ROOT_QUERY: {
  resources: {
      items: [... <array_of_resource_items>...],
      pageInfo: {
          cursor: 1023,
          count: 13,
          hasNextPage: true
    }
  }
}
```
This means that when I went to delete an item from the cache using the `update` function, I was accidentally deleting the entire list of resources... 🤦 

Old delete `update` function:
```
update(cache) {
  cache.modify({
    fields: {
      resources(existingResources, { DELETE }) {
        return DELETE
      },
    },
  })
}
```
As is apparent to me now, I was deleting the entire `resources` object in my cache. (hence why on the merge function, `existing` was empty) What I _really_ needed to do, is to modify the list of resources to eliminate the resources I no longer wanted in my cache. 
New delete `update` function:

Note: `selected` is a list of resource ids
```
    update(cache) {
      cache.modify({
        fields: {
          resources(existingResources) {
            const newItems = existingResources.items.filter(
              (r) => !selected.includes(r.__ref.split(':')[1])
            )
            const pageInfo = existingResources.pageInfo
            return {
              ...existingResources,
              items: newItems,
              pageInfo: {
                ...pageInfo,
                count: pageInfo.count - selected.length,
                cursor: parseInt(
                  newItems[newItems.length - 1].__ref.split(':')[1]
                ),
              },
            }
          },
        },
      })
      cache.gc()
    },
```

Obviously this is a little clunky, but it solves the problem and illuminates that what I needed to do was not pass the `DELETE` object but to modify the cached resources list. 

@benjamn - is there a better way to approach this. considering the structure of the response from `useQuery` (first code block in my original message). Is there a way to traverse into a `resource` (singular -- found in `resources.items`)? Can I name `resource.items` with a keyField? Any ideas on clean-up is helpful.

**Comment by jcreighton** [comment]
Closing as this was resolved.
