### ISSUE TITLE
keyArgs - right config

### ISSUE THREAD

**Issue by BayCo** [apollographql/apollo-client#7932]
I am using `['limit', 'where']` key args for my `raw_posts` field in typePolicies
And cache store object is looking like this
`raw_posts:{"limit":15,"where":{"user_id":{"_eq":26630796},"created_at":{"_gt":"1599221629"}}}`
How can i use only `user_id` argument as key but without `created_at`

**Comment by benjamn** [comment]
@BayCo Try this: `keyArgs: ["limit", "where", ["user_id"]]`

The nested array syntax applies to the previous argument value (`where`), so you could also configure
```
keyArgs: ["where", ["user_id"], "limit"]
```
though that would make the `limit` value appear after the `where` value in the serialized string.

**Comment by BayCo** [comment]
@benjamn thanks a lot
