### ISSUE TITLE
useQuery stays in loading state when testing with MockedProvider

### ISSUE THREAD

**Issue by rally25rs** [apollographql/apollo-client#7933]
Marking this as a question/discussion at the moment because i'm probably just doing something wrong or misunderstanding how this should work, but...

I'm making a test with `jest`, `react`, `enzyme`, and `apollo`.

It seems that if I have a React component that uses `useQuery` then the query is set to `loading: true` and then that is all. the component never "finishes" loading the data, and the `result` function on the mocked gql request is never called.

Here is as simple of an example as I can make:

```js
import React from 'react';
import {gql, useQuery} from '@apollo/client';
import {MockedProvider} from '@apollo/client/testing';
import {act} from 'react-dom/test-utils';
import {mount} from 'enzyme';

const testQuery = gql`
  query getDataQuery {
    testData {
      id
    }
  }
`;

// the react component under test
const TestComponent = function() {
  const {loading, error, data} = useQuery(testQuery);
  console.log('LOADING', loading, 'ERROR', error, 'DATA', data);
  return <div></div>;
};

describe('testing with MockedProvider', () => {
  it('should work', async () => {
    const mockTestQuery = {
      request: {
        query: testQuery,
      },
      result: jest.fn().mockReturnValue({data: {testData: []}}),
    };

    await act(async () => {
      mount(
        <MockedProvider mocks={[mockTestQuery]}>
          <TestComponent />
        </MockedProvider>,
      );
    });

    expect(mockTestQuery.result).toHaveBeenCalled();
  });
});
```

The test result is

```
    expect(jest.fn()).toHaveBeenCalled()

    Expected number of calls: >= 1
    Received number of calls:    0
```

and the `console.log` in the test component shows it is only rendered once with

```
  console.log
    LOADING true ERROR undefined DATA undefined
```

-----

So my question is; how would I get my test to wait until the data has actually been loaded? 🤔 

Thanks for any help!

-----

_Update 1:_

I found a way to make this work, by simply waiting 0ms after the `mount`:

```js
import React from 'react';
import {gql, useQuery} from '@apollo/client';
import {MockedProvider} from '@apollo/client/testing';
import {act} from 'react-dom/test-utils';
import {mount} from 'enzyme';

const testQuery = gql`
  query getDataQuery {
    testData {
      id
    }
  }
`;

const TestComponent = function() {
  const {loading, error, data} = useQuery(testQuery);
  console.log('LOADING', loading, 'ERROR', error, 'DATA', data);
  return <div></div>;
};

const wait = function(waitms) {
  return new Promise(resolve => {
    setTimeout(resolve, waitms);
  });
};

describe('testing with MockedProvider', () => {
  it('should work', async () => {
    const mockTestQuery = {
      request: {
        query: testQuery,
      },
      result: jest.fn().mockReturnValue({data: {testData: []}}),
    };

    await act(async () => {
      mount(
        <MockedProvider mocks={[mockTestQuery]}>
          <TestComponent />
        </MockedProvider>,
      );

      await wait(0); // <-- added this
    });

    expect(mockTestQuery.result).toHaveBeenCalled();
  });
});
```

Which seems like it should be unnecessary. I thought that is what `act()` was supposed to do for us 😕 
But I guess I found a workaround for now anyway 🤷 if anyone has a better solution that'd be great.

**Comment by dylanwulf** [comment]
If you look at the docs, you'll see that the `await wait(0)` that you came up with is actually the officially recommended approach: https://www.apollographql.com/docs/react/development-testing/testing/#testing-the-success-state

**Comment by rally25rs** [comment]
Ah, totally missed that detail in the docs. Thanks for pointing it out!
