### ISSUE TITLE
Warn when we pass a subscription to HttpLink.

### ISSUE THREAD

**Issue by brainkim** [apollographql/apollo-client#7950]
Currently, `HttpLink` will immediately close any `useSubscription` calls/queries. It would be nice to add a warning to indicate that `HttpLink` does not handle these queries correctly, and that a split or whatever should be used. (Inspired by #7780)

**Comment by jerelmiller** [comment]
With the addition of multipart subscription support in `HttpLink`, this issue seems obsolete, so I'm going to go ahead and close this. If we decide to do something similar to this in the future, we'll open a new issue. Thanks!
