### ISSUE TITLE
Circular reference in request context

### ISSUE THREAD

**Issue by mhmdbehairy** [apollographql/apollo-client#7976]
**Intended outcome:**
I was trying to store the request in the local storage in case the application was offline and the request failed so that I can try and resend it when it's back online. In the old "apollo-client" package, this worked perfectly fine.

**Actual outcome:**
What actually happens now using the "@apollo/client" package is that I get the circular reference error below:

![Untitled](https://user-images.githubusercontent.com/46031846/114459899-663aab80-9be1-11eb-9532-4d1bc335fc30.jpg)

After investigating a little bit, I found that there has been a change in the context object and it has a recursive reference to the InMemoryCache which is why I get this error and I believe it's not meant to be this way.

![2](https://user-images.githubusercontent.com/46031846/114460247-d5b09b00-9be1-11eb-96ef-23563032b79f.jpg)

**How to reproduce the issue:**
Well here's the link I was trying to implement and like I said above it used to work until I migrated to "@apollo/client" then it started throwing the error that it can't store it in the local storage because of the circular reference shown above.

```
const trackerLink = new ApolloLink((operation, forward) => {
        if (forward === undefined) return null

        const context = operation.getContext()
        const { operationName, query, variables } = operation
        const trackedQueries = JSON.parse(window.localStorage.getItem('trackedQueries') || '[]')

        console.log('context', context)

        if (context.tracked) {
            const newTrackedQuery = {
                query,
                context,
                variables,
                operationName
            }

            window.localStorage.setItem('trackedQueries', JSON.stringify([...trackedQueries, newTrackedQuery]))
        }
        // Pop last query from local storage if it was able to complete the pipeline
        return forward(operation).map((data) => {
            if (context.tracked) {
                window.localStorage.setItem('trackedQueries', JSON.stringify(trackedQueries))
            }

            return data
        })
    })
```

**Versions**
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.75)
  npmPackages:
    @apollo/client: ^3.3.11 => 3.3.14

**Comment by WJKwok** [comment]
Hi @mhmdbehairy did you manage to resolve this? I'm facing the same error :/

**Comment by benjamn** [comment]
You shouldn't be using `JSON.stringify` or `JSON.parse` to encode/decode `InMemoryCache` objects! That isn't supported and won't work, no matter what deep copying utility you use.

If you want to save cache state, use `const snapshot = cache.extract()` and later `cache.restore(snapshot)`. Those snapshots are safe to serialize with `JSON.stringify`.
