### ISSUE TITLE
Previous data returned when changing variables and fetchPolicy is network-only (Reproduction Provided)

### ISSUE THREAD

**Issue by dylanwulf** [apollographql/apollo-client#7978]
**Intended outcome:**
If I change variable values when `fetchPolicy === 'network-only'`, then `data` should immediately become `undefined` while the results are being fetched from the server. This seemed to work correctly in v3.0.0 - v3.0.2, but broke in v3.1.0.

**Actual outcome:**
When I change the variable values, `data` still holds the previous data which was associated with the previous variable values.

**How to reproduce the issue:**
https://github.com/dylanwulf/react-apollo-error-template (look at the console as you click the radio buttons)

Possibly related to #7058 and #7048

**Versions**
```
System:
    OS: Windows 10 10.0.19042
Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.75)
npmPackages:
    @apollo/client: ^3.3.11 => 3.3.11
```

**Comment by dylanwulf** [comment]
Also, if you change `notifyOnNetworkStatusChange` to `true`, then it will first return results for the previous variables, then it will return CACHED results for the current variables, and finally it will return the fetched results for the current variables. Is `network-only` supposed to return cached results when you change the variables? That seems wrong to me

**Comment by dylanwulf** [comment]
Updated reproduction to use the latest template and apollo client version (3.3.19), issue is still there

**Comment by dylanwulf** [comment]
@hwillson @jcreighton Hi, I'm sorry to bother you but I'm wondering if there are any plans to fix this issue. This is a blocker for me because of the following scenario:
I have an infinite scrolling list which uses `network-only` fetch policy and `notifyOnNetworkStatusChange: true`. When I first mount the query, I pass in variables `{ text: 'A' }` which loads the first page. Then I scroll down to load pages 2 and 3. Next I change the variables to `{ text: 'B' }`, which loads the first page of B results. Then I change the variables back to `{ text: 'A' }`, and `useQuery` will (incorrectly) return cached results for pages 1, 2, and 3. Page 1 of A is (correctly) fetched again, but `useQuery` continues to (incorrectly) return cached results for pages 1, 2, and 3. Now when I scroll down more, my component sees that we have pages 1-3 so it calls `fetchMore({ variables: { page: 4 } })`. Then in the cache merge function, `existing` only has data from page 1 and `incoming` only has data from page 4, so I actually lose pages 2 and 3. I haven't found any workarounds so far.

Again sorry to bother you, I understand if you're too busy to tackle this right now. Thank you folks for all your hard work ❤️

**Comment by hwillson** [comment]
Thanks for this @dylanwulf - we'll take a closer look.

**Comment by dylanwulf** [comment]
@hwillson thank you for the response! sorry for my previous (now deleted) comment, it turned out to be a dumb mistake unrelated to this issue and has been taken care of. The original bug reproduction still stands though.

**Comment by dylanwulf** [comment]
Confirmed that #8422 fixes this, closing! Thank you so much for your help ❤️
