### ISSUE TITLE
Subscription unsubscribing when getting a graphQLError

### ISSUE THREAD

**Issue by bauwaerter** [apollographql/apollo-client#7982]
Related issues:

- https://github.com/apollographql/apollo-client/issues/9109
- https://github.com/apollographql/apollo-client/issues/6024

Subscription unsubscribes when it gets a graphQL error and it never resubscribes.

**Intended outcome:**

The subscription should stay subscribed when it gets graphQL errors.

**Actual outcome:**

The subscription unsubscribes when it encounters a graphQL error. 

<img width="1147" alt="Screen Shot 2021-04-08 at 6 12 11 PM" src="https://user-images.githubusercontent.com/5298147/114107439-a2df6d80-9896-11eb-80e1-5d0e6fc5114e.png">

<img width="1380" alt="Screen Shot 2021-04-08 at 6 26 21 PM" src="https://user-images.githubusercontent.com/5298147/114108087-f30aff80-9897-11eb-8e24-0b2a0041c341.png">

**How to reproduce the issue:**

```
export const subscriptionLink = new WebSocketLink({
  uri: `${wsScheme}://${graphQLHost}/graphql`,
  options: {
    reconnect: true,
    lazy: true,
  },
})
```
```
export const TestComponent: React.FC = () => {
  const { data, error, loading } = useSubscription(TestDocument, { shouldResubscribe: true })
  return <div />
}
```
Setup your subscription and throw a graphQL error from the server.

I'm not sure if this is the intended behavior, but I don't see a way I can resubscribe. Once the stop command is sent it kills that subscription and it never starts back up again.

**Versions**

```
  System:
    OS: macOS 11.2.3
  Binaries:
    Node: 15.3.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /Volumes/Macintosh Case-sensitive/client/node_modules/.bin/yarn
    npm: 7.7.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 85.0
    Safari: 14.0.3
  npmPackages:
    @apollo/client: ^3.3.14 => 3.3.14 
    apollo: ^2.32.1 => 2.32.5 
    apollo-link-timeout: ^3.0.0 => 3.0.0 
```

**Comment by jpvajda** [comment]
closing. We'll work from #9109 as the main issue as this is related.
