### ISSUE TITLE
can evict() args use wildcards or partial args?

### ISSUE THREAD

**Issue by elubin** [apollographql/apollo-client#7984]
i want to evict some queries from my cache based on partial args. For example, if my cache looks below, how can i evict only USA objects.

```
{
ROOT_QUERY:
  GetSomething({"country":"usa","stateProv":"new york"}): { a:"b"}
  GetSomething({"country":"usa","stateProv":"ohio"}): { a:"b"}
  GetSomething({"country":"canada","stateProv":"ontario"}): { a:"b"}
}

cache.evict({fieldName:'GetSomething');  // this evicts all
cache.evict({fieldName:'GetSomething', args: { country: 'usa' });  // this doesn't evict anything
cache.evict({fieldName:'GetSomething', args: { country: 'usa',"stateProv":"ohio" });  // this evicts one
```

**Comment by benjamn** [comment]
@elubin This is a current limitation of `cache.evict` (the `args` have to be the same as the ones that were used to write the field in the first place).

You can also use `cache.modify` for this task:
```ts
cache.modify({
  fields: {
    GetSomething(value, { storeFieldName, DELETE }) {
      if (shouldDelete(storeFieldName)) {
        return DELETE;
      }
      return value;
    },
  },
})
```
However, you may have to `JSON.parse` the serialized arguments from `storeFieldName`, which will be a string like
```js
'GetSomething({"country":"usa","stateProv":"new york"})'
```
There's not currently a better way to get the _original_ `args` that were used to write the field during `cache.modify`.

**Comment by elubin** [comment]
Thank you. That's a huge help. However, both _evict()_ and _modify() with DELETE_ cause the query to run again immediately. I tried INVALIDATE like below, but it has no effect on the cache at all.

I am trying to invalidate/delete/remove/clear my cache objects so later pages will be forced to fetch them again. I do not want to  fetch them all after the mutation (to costly).

```
cache.modify(
  {
    fields: {
      GetSomething(value, { storeFieldName, INVALIDATE }) {
        let _params = storeFieldName.match(/^GetSomething\((.*)\)$/);
        if (_params && _params.length > 1) {
          let params = JSON.parse(_params[1]);
          if (params['country'] == 'usa') {
            return INVALIDATE;
          }
          else return value; // ignore it
        }
        else return value; // ignore it
      }
    }
  }
)
```

**Comment by benjamn** [comment]
> However, both evict() and modify() with DELETE cause the query to run again immediately

@elubin As a quick suggestion, you can prevent the immediate broadcast by passing `broadcast: false`:
```ts
cache.modify({
  broadcast: false,
  // ... other options
});
```
If another cache write happens shortly after this, causing a broadcast, the changes `cache.modify` made will be picked up in that broadcast, so you might end up seeing the query get fetched again, even with `broadcast: false`. If you run into that problem, I can tell you more about adjusting the `fetchPolicy` of those queries to avoid unwanted network requests.

**Comment by elubin** [comment]
Thanks @benjamn
