### ISSUE TITLE
writeFragmnent hangs

### ISSUE THREAD

**Issue by chriskrogh** [apollographql/apollo-client#7990]
**Intended outcome:**

The Apollo cache should update and the control flow of the application should resume as it typically would.

**Actual outcome:**

When I call `writeFragment`, the application goes into a weird state where none of the code after the call is made runs. There are no errors in the console.

**How to reproduce the issue:**

I'd love to include a fork of the error template, but I'm using TS and `@graphql-codegen/typescript` to generate `gql` tags. I think setting that up would be a bit extreme and I don't think the issue is related to those tools.

My `update` function looks like 

```
update(cache, { data }) {
        cache.modify({
          fields: {
            getCards(existingRefs: Reference[] = []) {
              if (!data) return existingRefs;
              console.log(data.createCard, existingRefs);
              const newCardRef = cache.writeFragment({
                data: data.createCard,
                fragment: FullCardFragmentDoc,
                fragmentName: 'FullCard',
              });
              console.log('here');
              return [newCardRef, ...existingRefs];
            },
          },
        });
      },
```
Where I can see the console log with the data and the existing refs (everything looks good), but I can't see the `console.log('here')`. None of the application code after this runs and there are no errors in the console.

Any digging into would be greatly appreciated.

**Versions**

```
System:
    OS: macOS 11.2.3
  Binaries:
    Node: 15.2.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.10 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.128
    Edge: 89.0.774.77
    Safari: 14.0.3
  npmPackages:
    @apollo/client: ^3.3.11 => 3.3.14
```

**Comment by benjamn** [comment]
@chrishandorf Can you check if `cache.writeFragment` might be throwing some sort of exception by wrapping it with a `try`-`catch` block, and putting a `console.log` or `debugger` statement in the `catch` block?

**Comment by chriskrogh** [comment]
> @chrishandorf Can you check if `cache.writeFragment` might be throwing some sort of exception by wrapping it with a `try`-`catch` block, and putting a `console.log` or `debugger` statement in the `catch` block?

error that was caught: 
```
Invariant Violation: Could not identify object 
    {"last4Digits":"9876","provider":"VISA","token":"OVV44XZmsM1HU6lv95OME","type":"DEBIT","__typename":"Card"}
    at new InvariantError (http://localhost:3000/static/js/vendors~main.chunk.js:170774:24)
    at StoreWriter.writeToStore (http://localhost:3000/static/js/vendors~main.chunk.js:2190:34)
    at InMemoryCache.write (http://localhost:3000/static/js/vendors~main.chunk.js:927:31)
    at InMemoryCache.ApolloCache.writeFragment (http://localhost:3000/static/js/vendors~main.chunk.js:86:17)
    at getCards (http://localhost:3000/static/js/main.chunk.js:16517:42)
    at http://localhost:3000/static/js/vendors~main.chunk.js:371:60
    .....```

I think I know what the issue is. I'm not returning the `id` field on the response object. It's weird that this exception didn't show up in the console. Anyways, thanks for your help!

**Comment by f-huang** [comment]
For whomever who's struggling with this, in my case, I had to explicitly query `__typename` in fragment to make `writeFragment` works.
