### ISSUE TITLE
batch-http useQuery in custom hook won't be called

### ISSUE THREAD

**Issue by MakhBeth** [apollographql/apollo-client#7991]
**Intended outcome:**
I wanted to put an useQuery hook inside one custom hook

**Actual outcome:**
useQuery is not called

**How to reproduce the issue:**

I have this Apollo Setup
```ts
import { ApolloClient, ApolloProvider, HttpLink, InMemoryCache, ApolloLink } from '@apollo/client'
import { BatchHttpLink } from '@apollo/client/link/batch-http'
import { setContext } from '@apollo/link-context'
import { Auth0ContextInterface, useAuth0 } from '@auth0/auth0-react'

type GetAccessTokenSilentlyType = Pick<Auth0ContextInterface, 'getAccessTokenSilently'>['getAccessTokenSilently']

const uri = `STRING`
const httpLink = new BatchHttpLink({ uri })

const asyncAuthLink = (getAccessTokenSilently: GetAccessTokenSilentlyType) =>
  setContext(async () => {
    const token = await getAccessTokenSilently()
    return {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    }
  })

const apolloClient = (getAccessTokenSilently: GetAccessTokenSilentlyType) =>
  new ApolloClient({
    link: ApolloLink.from([asyncAuthLink(getAccessTokenSilently) as any, httpLink]),
    cache: new InMemoryCache(),
    connectToDevTools: true,
  })

const AuthorizedApolloProvider: React.FunctionComponent = ({ children }) => {
  const { getAccessTokenSilently } = useAuth0()
  const authorizedApolloClient = apolloClient(getAccessTokenSilently)

  return <ApolloProvider client={authorizedApolloClient}>{children}</ApolloProvider>
}

export { AuthorizedApolloProvider }
```

And this Element:
```tsx
const useCustom = (id: string) => {
  return useQuery(AgencyDocument, {
    variables: { id: id },
  })
}

const Comp: React.FunctionComponent<CompProps> = ({ id, className }) => {
  const { data, error, loading } = useCustom(id)

  if (error) {
    return JSON.stringify(error)
  }

  if (loading) {
    return <div>Loading</div>
  }

  console.log(data)

  return null
}
```
And another similar component, with similar query on the same objects, but not callings the id of the element here.

If I use httpLink everything works fine, if I switch to BatchHttpLink, the component will not be updated
If I directly use the useQuery hook inside the component, everything works fine

**Versions**
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 12.11.0 - ~/.nodenv/versions/12.11.0/bin/node
    Yarn: 1.22.10 - ~/.nodenv/versions/12.11.0/bin/yarn
    npm: 6.11.3 - ~/.nodenv/versions/12.11.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.128
    Firefox: 86.0.1
    Safari: 14.0.3
  npmPackages:
    @apollo/client: ^3.3.15 => 3.3.15 
    @apollo/link-context: ^2.0.0-beta.3 => 2.0.0-beta.3

**Comment by benjamn** [comment]
@MakhBeth Do you think the symptoms of this problem are the same as if the `BatchHttpLink` was somehow not properly passing along your authentication headers?

That `useCustom` wrapper function should be totally fine/harmless.

**Comment by MakhBeth** [comment]
Ok, the problem was resolved by adding IDs to all the queries!
