### ISSUE TITLE
Getting unexpected result after optimisticResponse React Native

### ISSUE THREAD

**Issue by iromjkee** [apollographql/apollo-client#7995]
Not able to add normal optimisticResponse to the mutation. While I am adding data without optimisticResponse it looks like this.

https://user-images.githubusercontent.com/25479692/115023739-da1dd200-9ec7-11eb-8c6e-04f6f8cc6048.mp4

It normally adds data after mutation is executed and data comes from the server. But while trying to use same + optimisticResponse it does strange things(see actual outcome)

Here is the code of component where I get my tasks via useQuery:
![image](https://user-images.githubusercontent.com/25479692/115024079-44367700-9ec8-11eb-863d-c4957d7a62ec.png)
Here is the code of my addMutation:
![image](https://user-images.githubusercontent.com/25479692/115024041-384ab500-9ec8-11eb-810e-9b5725d1764a.png)

**Intended outcome:**
Getting updated tasks list.

**Actual outcome:**
Tasks list becomes empty for a few seconds, and then like fetches from the server(but there were data in the cache)

https://user-images.githubusercontent.com/25479692/115023413-70052d00-9ec7-11eb-92c4-2cfb5c2e357a.mp4

**How to reproduce the issue:**

**Versions**
System:
    OS: macOS 10.15.4
    iOS: 14.4
  Binaries:
    Node: 14.11.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.128
    Safari: 13.1
  npmPackages:
    @apollo/client: ^3.3.9 => 3.3.9 
    apollo-link-offline: ^1.0.1 => 1.0.1 
    apollo-link-queue: ^3.0.0 => 3.0.0 
    apollo-upload-client: ^14.1.3 => 14.1.3 
    apollo3-cache-persist: ^0.9.1 => 0.9.1

**Comment by benjamn** [comment]
@iromjkee Could you give it a try with `@apollo/client@3.4.0-beta.23`? The implementation of optimistic updates has changed/improved recently on the `release-3.4` branch. I'd love to hear if anything is different, good or bad.

**Comment by hwillson** [comment]
Let us know if this is still an issue with `@apollo/client@beta` (which is launching soon). Thanks!

**Comment by arealmaas** [comment]
Got a similar issue, fixed when upgrading to apollo client 3.4.16. 

Our issue was that several un-related queries were refetched only when specifying optimisticResponse in the mutation.
