### ISSUE TITLE
npx apollo client:codegen fail

### ISSUE THREAD

**Issue by sergio9104** [apollographql/apollo-client#7996]
I am using the `npx apollo client:codegen` command to generate the interfaces from my graphQL schema, currently I have a query like this

![image](https://user-images.githubusercontent.com/13669125/115045740-674b3180-9e9c-11eb-8189-50d5bae3154e.png)
that generates the following error 

`Error: Syntax error in file:///Users/svalencia/Documents/orkin-com-website/src/graph/queries/copyblock.js: Syntax Error: Expected Name, found "}". `

then changing it to this way

![image](https://user-images.githubusercontent.com/13669125/115045949-96fa3980-9e9c-11eb-8a0c-df2b1d4ebdfa.png)

the error is fixed, I have found that if I use variables which do not have a continuous instruction this error is generated.

**Comment by hwillson** [comment]
@sergio9104 please open this issue in the https://github.com/apollographql/apollo-tooling repo. Thanks!
