### ISSUE TITLE
watchQuery triggers network request for other watchQueries using same query document but diffrent variables

### ISSUE THREAD

**Issue by jakubnavratil** [apollographql/apollo-client#8020]
Running 2 watchQuery requests causes 3 network requests. Second query retriggers first one. Both queries are using same document but diffrent variable.

```ts
    this.apollo
      .watchQuery<Roof, RoofVariables>({
        query: roofQuery,
        variables: {
          id: '2',
        },
        fetchPolicy: 'network-only',
      })
      .valueChanges.subscribe((v) => {
        console.log(v);
      });

    this.apollo
      .watchQuery<Roof, RoofVariables>({
        query: roofQuery,
        variables: {
          id: '3',
        },
        fetchPolicy: 'network-only',
      })
      .valueChanges.subscribe((v) => {
        console.log(v);
      });
```

![image](https://user-images.githubusercontent.com/7920929/115701287-ed1d2000-a367-11eb-9dfd-c72a41f4fda3.png)

**Intended outcome:**

Just two queries run.

**Actual outcome:**

Looks like result returning for second query retriggers first one.

**How to reproduce the issue:**

https://stackblitz.com/edit/apollo-watch-query-infinite-zhiw6w?file=index.js

**Versions**

```
System:
    OS: Windows 10 10.0.18362
  Binaries:
    Node: 12.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - D:\www\animatec-ng\animatec-crm-client\node_modules\.bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @apollo/client: ^3.0.0 => 3.3.15 
    apollo: ^2.32.5 => 2.32.5 
    apollo-angular: ^2.4.0 => 2.4.0 
```

**Comment by benjamn** [comment]
@jakubnavratil Thanks to your reproduction, I can confirm this was fixed in `@apollo/client@3.4.0-beta.4`, likely by PR #7439. We're currently on `@apollo/client@3.4.0-beta.23` (release candidate soon!), if you want to try updating.

**Comment by jakubnavratil** [comment]
Wow, amazing work! Thank you very much 😄

**Comment by hwillson** [comment]
Apollo Client 3.4 is launching soon (we're in RC now). Thanks!
