### ISSUE TITLE
Configuring keyArgs for types rather than fields?

### ISSUE THREAD

**Issue by LeonardDrs** [apollographql/apollo-client#8021]
Hey, 

I've seen that we can specify `merge` function for [types rather than fields](https://www.apollographql.com/docs/react/caching/cache-field-behavior/#configuring-merge-functions-for-types-rather-than-fields). But since `typePolicies.Type.keyArgs` does not exist - which seems normal since we are talking about a type, not a query field - am I forced to use `Query.fields` for pagination?

To be more precise:
I have an album containing multiple tracks with this schema:
```gql
type Album {
  id: ID!
  tracks(first: Int = 20, after: String): AlbumTracksConnection!
}

type AlbumTracksConnection {
  edges: [AlbumTracksEdge!]!
  pageInfo: PageInfo!
}

type AlbumTracksEdge {
  cursor: String!
  node: Track
}
```

When I want to paginate, I could use the following query:

```gql
query Album($albumId: String!, $nb: Int, $after: String) {
  album(albumId: $albumId) {
    id
    tracks(first: $nb, after: $after) {
      pageInfo {
        hasNextPage
        endCursor
      }
      edges {
        cursor
        node {
          id
          title
        }
      }
    }
  }
}
```

with this `fetchMore`:
```gql
fetchMore({
  variables: {
    albumId: "13",
    nb: 3,
    after: data.album.tracks.pageInfo.endCursor,
  },
})
```
and this `typePolicies`:
```js
typePolicies: {
  Album: {
    fields: {
      tracks: relayStylePagination(),
    },
  },
}
```

Everything works perfectly.

But then, if I want to configure the `typePolicies` for type over fields, since `AlbumTracksConnection` is always paginated, I'd try:
```js
typePolicies: {
  AlbumTracksConnection: relayStylePagination(),
}
```
which does not work as the `Album.fields.tracks` policy keeps its original `keyArgs` value.

I would then need to specify `Album.fields.tracks.keyArgs` to false in the typePolicies for the pagination to work. But then I would loose the benefit of being able to target types over fields name.

So the question is:
Do we want to be able to handle pagination/keyArgs via type, like we are able to handle `merge`? It would ease the pagination for types.
Or am I doing something wrong with the pagination?

Probably related: https://github.com/apollographql/apollo-client/pull/7070#issuecomment-736799353

PS: In real life, I'd use a `Paginable` type like so:
```js
new InMemoryCache({
  typePolicies: {
    Paginable: relayStylePagination(),
  },
  possibleTypes: {
    Paginable: ["AlbumTracksConnection", "AnythingConnection", ...],
  },
});
```

**Comment by dylanwulf** [comment]
I'm not sure this would make sense outside of your use case. GraphQL allows you to return the same type from multiple different places, each with its own unique set of arguments. It would be impossible to guarantee that the type will always have the same arguments.

**Comment by LeonardDrs** [comment]
>It would be impossible to guarantee that the type will always have the same arguments.

Sure but we could always still specify a specific `keyArgs` in a different place where the type has different arguments.

>I'm not sure this would make sense outside of your use case.

I though pagination was pretty common, what is specific from my use case?

**Comment by LeonardDrs** [comment]
@benjamn Hello, sorry to bother you with this ping.
I'd be grateful if you could provide me your insight on this situation.

For now I've developed a graphql-codegen plugin to create the `typePolicies` object so I can manage, but I'm still wondering if the pagination could be handled via types instead of fields.

**Comment by sebastienbarre** [comment]
Having worked on pagination in the past few days, I'm not sure how your scenario would work.
`relayStylePagination()` needs access to `args.after` and `args.before` to work.
These are not defined at the `AlbumTracksConnection` level, they are defined at the field level, in this case, `tracks(first: $nb, after: $after)`, that's why `relayStylePagination()` is associated to the `tracks` field.
Case in point, you could have two different fields returning an `AlbumTracksConnection`, but with different arguments for each fields.

**Comment by benjamn** [comment]
@LeonardDrs I see where you're coming from, but I agree with @dylanwulf and @sebastienbarre that the details don't quite work out.

Another problematic case (simpler than pagination): what if you're replacing the value of an `Animal`-typed field that used to be `Dog` with a `Cat` object, but `Dog` and `Cat` types define different `keyArgs`? Which one should we use?

The `merge` function in type policies (#7070) is a special case where I was able to convince myself all the details would work. On the reading side, we often need to compute the field key (using `keyArgs`) _in order to find the right field value_, so we don't have the luxury of using the field's value to determine the field's key.

I'd love to see that GCG plugin if you can share it!

**Comment by Azerothian** [comment]
Atm the moment we are unable to apply type polices for pagination for the following.
```graphql
type Item {
  id: ID!
  items(first: Int = 20, after: String): ItemConnection!
}

type ItemConnection {
  edges: [ItemEdge!]!
  pageInfo: PageInfo!
}

type ItemEdge {
  cursor: String!
  node: Item
}

```

Type Policy 
```javascript
const itemTypePolices = {
  ...relayStylePagination(),
  fields: {
    edges: {
      fields: {
        node: {
          fields: {
            items: itemTypePolices,
          },
        },
      },
    },
  },
};


const memoryCacheOptions = {
  typePolicies: {
    Item: {
      fields: {
        items: itemTypePolices,
      },
    },
  },
};
```
1. Without normalisation you cant run two queries on the same object and one will override the other. But it is the only way data is store in the parent object. 
- `Item.edges.node.items(where: {active: false}).edges` will only work if one list is queried
2. With normalisation (ie. supplying keyArgs) the following will interfere with each other
- `Item(where: {active: false}).edges`
- `Item.edges.node.items(where: {active: false}).edges`

**Comment by jerelmiller** [comment]
Hey all 👋 

Appreciate the discussion here but I'm not sure there is anything more to add so I'm going to go ahead and close this issue. Thanks!
