### ISSUE TITLE
Pagination with query variables spread across different GraphQL types

### ISSUE THREAD

**Issue by kfazinic** [apollographql/apollo-client#8053]
Hi, I'm having trouble writing a type policy when query includes nested pagination and receives three variables, which get spread across two different types. . Here's a simplified query:

      query RootQuery($uri: String!, $filters: [String], $rows: Int, $offset: Int) {
        project(uri: $uri) {
          __typename
          uri
          items(filters: $filters, rows: $rows, offset: $offset) {
            __typename
            resources {
              name
            }
            countOfMatches
          }
        }
      };

Assume that the first query is called with variables `{ uri: "100", offset: 0, rows: 3, filters: [] }`. Then the object that gets cached has property named `'items({"filters:[],offset:0,rows":3})'` (I would expect to see `items`). 
On `fetchMore` with `{ offset: 3 }` another property is added, this one being named `'items({"filters:[],offset":3,"rows":3})'`. This is with `keyArgs: false`. 

How to write a custom merge function to join the `items` into a single array when query variables get serialized into property names?

**Comment by LeonardDrs** [comment]
Hello.

Indeed `keyArgs: false` should avoid this issue, care to share your `typePolicies` configuration?

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
