### ISSUE TITLE
Mutation result isn't shared among separate useMutation invocations

### ISSUE THREAD

**Issue by garrett-gottlieb** [apollographql/apollo-client#8054]
When invoking a mutation in one component, the result isn't shared with any other components.

**Intended outcome:**

The mutation result is shared among all components that use the mutation hook for that mutation.

**Actual outcome:**

The mutation result is not shared.

**How to reproduce the issue:**

https://codesandbox.io/s/objective-proskuriakova-vo8ce?file=/src/App.js:0-2071

**Versions**

  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 12.20.0 - /usr/local/bin/node
    Yarn: 1.19.0 - ~/.yarn/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.85
    Firefox: 80.0
    Safari: 14.0.3

**Comment by benjamn** [comment]
@garrett-gottlieb Each mutation result corresponds to a specific mutation invocation, so there may be multiple results over time for the _same_ `useMutation` call site. I'm not sure I see how _separate_ `useMutation` call sites (with their own potentially different options/variables, like in your reproduction) could reasonably share the same result, without some heavy assumptions about the cacheability/reusability of mutations.

**Comment by garrett-gottlieb** [comment]
@benjamn I see... so what's your recommended approach to sharing the mutation result throughout the app?
