### ISSUE TITLE
"No more mocked responses for the query..." error gets thrown to the wrong hook

### ISSUE THREAD

**Issue by insidewhy** [apollographql/apollo-client#8094]
At the company I'm working at we're seeing this problem over and over again since updating to the latest apollo client (`3.3.15`, we were previously on `2.6.4`).

We forget to configure a mock for query `A` and yet the error `No more mocked responses...` is reported by the wrong hook, one that's requesting query `B`.

We spent quite some time debugging this and at the `MockLink` layer everything is looking fine, we're assuming that the code that forwards the error to the wrong hook is in `MockedProvider`.

**Comment by benjamn** [comment]
@insidewhy Any chance of a small runnable [reproduction](https://github.com/apollographql/react-apollo-error-template/)?

To be perfectly honest with you, the mocking utilities are due for a rewrite. Sorry for the rough edges in the meantime.

**Comment by insidewhy** [comment]
@benjamn I know :( We've actually had a pretty rough time writing unit tests. We wrote our own mock link with a lot of basic features we needed, especially around mocking of subscriptions. We've narrowed the problem down to the layer above the mock link, but a simple use case evades us so far. We see the problem all the time in complicated and medium-complicated tests, but not sure how to reproduce it in a simple way. Seems to be timing dependent.

**Comment by insidewhy** [comment]
When you hit this error in a test, it reliably fails in this way 100% of the time, so not a race condition.

**Comment by insidewhy** [comment]
This only happens when the mock link somehow does `throw new Exception`. The latest mock link from apollo uses `Observable((observer) => observer.error(...))`  so it runs okay. We only hit this because we were using a different mock link in some places. I guess it's weird that the exception gets propagated to the wrong hook, but it's not an issue with the current mock link. We updated our own mock link to match the built-in mock link and no longer receive this error.
