### ISSUE TITLE
[Error: undefined is not a constructor (evaluating 'new _globalThis.TextEncoder()')] when using suggested crypto-hash in react-native 0.63.x

### ISSUE THREAD

**Issue by eliw00d** [apollographql/apollo-client#8095]
**Intended outcome:**

Follow the example and it works.

**Actual outcome:**

Follow the example and get this error:
```
[Error: undefined is not a constructor (evaluating 'new _globalThis.TextEncoder()')]
```

**How to reproduce the issue:**

Follow [this example](https://www.apollographql.com/docs/react/api/link/persisted-queries/#usage) with an Apollo Client in React Native.

So far, everything has worked in both web and mobile as far as our Apollo Client usage until this. Is there a recommended alternative or is this a bug?

**Versions**

```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.128
    Safari: 14.1
```

**Comment by benjamn** [comment]
@eliw00d Apollo Client doesn't use `TextEncoder` directly anywhere in our codebase, but perhaps you can track this down by defining a global getter function that shows the stack trace?
```ts
Object.defineProperty(globalThis, "TextEncoder", {
  get() {
    console.trace(); // Not sure if React Native supports console.trace, but you get the idea?
    console.error("See trace above to find out who tried to access globalThis.TextEncoder");
    debugger; // Another way to intercept references to TextEncoder.
    return null;
  },
})
```
I wouldn't recommend leaving this getter in your application (this is just for debugging).

**Comment by eliw00d** [comment]
Ah, that makes sense! I will give that a shot and report back. If it solves the issue, should the documentation/example be updated for React Native users?

**Comment by eliw00d** [comment]
Now I get:
```
1 [Error: JSON Parse error: Unexpected identifier "provided"]
Error: Unable to resolve module `./http://localhost:8081/index` from ``: 
```

**Comment by eliw00d** [comment]
I was able to get it to work by using react-native-sha256. 

I also tried [this](https://github.com/philikon/ReactNativify/issues/4) but was not able to get it to work (due to the reasons specified in my comment there).

**Comment by hwillson** [comment]
Sounds like this has been solved. Thanks!
