### ISSUE TITLE
`cache.modify` can never succeed based on current doc recommendations

### ISSUE THREAD

**Issue by brettins** [apollographql/apollo-client#8121]
**Intended outcome:**
I would like to add & delete an item to and from the cache and have it update my screen on the fly.  I am unable to make modifications to the cache based on the `cache.modify` documentation.  When using the code from the docs:

```

cache.modify({
  fields: {
    comments(existingCommentRefs = [], { readField }) {
      const newCommentRef = cache.writeFragment({
        data: newComment,
        fragment: gql`
          fragment NewComment on Comment {
            id
            text
          }
        `
      });

      // Quick safety check - if the new comment is already
      // present in the cache, we don't need to add it again.
      if (existingCommentRefs.some(
        ref => readField('id', ref) === newComment.id
      )) {
        return existingCommentRefs;
      }

      return [...existingCommentRefs, newCommentRef];
    }
  }
});
```

**Actual outcome:**
The cache never updates. When step-debugging through, we can see in `entityStore.js` that it is expecting fields itself to be a function, as opposed to the docs which implies that `fields` should be an object containing a function. 

In `entityStore.js`: 
https://github.com/apollographql/apollo-client/blob/90235f8f0cf6145a7da04b58c9f37760e57a99ed/src/cache/inmemory/entityStore.ts#L182

```
        const modify: Modifier<StoreValue> = typeof fields === "function"
          ? fields
          : fields[storeFieldName] || fields[fieldName];
```

This will never be true since fields is an object with a function, not a function. So the cache never gets modified. 

**Versions**
```

  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - /var/www/StoryCity/web-client/node_modules/.bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 88.0
  npmPackages:
    @apollo/client: ^3.3.12 => 3.3.16 
    vue-apollo: 3.0.7 => 3.0.7 
    vue-cli-plugin-apollo: ~0.22.2 => 0.22.2 
```

**Comment by benjamn** [comment]
@brettins Your interpretation of the implementation of this code is mistaken.

It is possible for `fields` itself to be a function, which is a shorthand for defining a modifier function that runs over all fields in the object (without having to guess their names). It is more common for `fields` to be an object containing named methods, of course, but both styles are supported.

If you want help with this problem, please put together a small runnable [reproduction](https://github.com/apollographql/react-apollo-error-template/), or keep debugging on your side until you find another explanation.

**Comment by brettins** [comment]
I've created a PR, the docs were missing the `id`.

https://github.com/apollographql/apollo-client/pull/8134
