### ISSUE TITLE
Feature: @defer support

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-client#8184]
This issue will be used to track our progress on adding `@defer` (not `@stream`) support to `@apollo/client`.

Related to:
- https://github.com/apollographql/apollo-client/issues/7691
- https://github.com/apollographql/apollo-feature-requests/issues/3

**Comment by maraisr** [comment]
> @hwillson have noticed that `@defer` support has been bouncing around release milestones and what-not.
> 
> 
> 
> Is there anything that can be done to assist with this functionality? 
> 
> 
> 
> Would really love to see this functionality, and don't want to have to use a fork to get that. 

I kicked off the implication a few months back, but was told they'd be taking it on internally. Perhaps Apollo might be back to being open to a community contribution here, as ya 😅 think y'all seeing it as a back burner task?

**Comment by DkozhevnikovConfigit** [comment]
Hi @brainkim, do you have any news about it? Are you still working on it? 
Can we have a hope to have it available in 3.6 release? We are really waiting for the @defer directive support by apollo-client :) Thanks in advance! :)

**Comment by hwillson** [comment]
@extjbhlego we'll have our `@defer` PR up for public review shortly.

**Comment by mauricedoepke** [comment]
@hwillson any updates on this?

**Comment by imranhassan87** [comment]
when can we expect this? any timeline?

**Comment by stewartmcgown** [comment]
You can follow along with their progress on this feature here: https://github.com/apollographql/apollo-client/pull/9598

**Comment by jpvajda** [comment]
👋  `@defer` support is now available as a preview feature in `Apollo Client 3.7`. We have some preliminary [documentation here. ](https://www.apollographql.com/docs/react/data/defer).
