### ISSUE TITLE
Issue with onComplete not being called when  useLazyQuery resulting function is used twice or more in fast succession.

### ISSUE THREAD

**Issue by carlos-duetto** [apollographql/apollo-client#8202]
**Intended outcome:**
On the web app I am working on there is the possibility of using the function returned by useLazyQuery concurrently twice, due to UX design, but each call with its own distinctive parameters. When this happens you can see the query request twice on network tab on dev tools and the expectation is that there should an onComplete call triggering for each request when they are completed.

**Actual outcome:**
The onComplete call is only triggered for the first query.

**How to reproduce the issue:**
If I have a lazy query such as
const [queryFn] = useLazyQuery<SomeQuery, SomeQueryParams>({variables: ...., onComplete: (data) => {...}})

Call queryFn twice in fast succession, you will see onComplete function being triggered just once.

**Versions**
"@apollo/client": "^3.1.3"

**Comment by benjamn** [comment]
@carlos-duetto Can you check whether this is still a problem with `@apollo/client@3.3.18` and/or `@apollo/client@3.4.0-beta.26`? I can't guarantee it's fixed, but a lot has changed since v3.1.3, so things might be different. Thanks!

**Comment by carlos-duetto** [comment]
> @carlos-duetto Can you check whether this is still a problem with `@apollo/client@3.3.18` and/or `@apollo/client@3.4.0-beta.26`? I can't guarantee it's fixed, but a lot has changed since v3.1.3, so things might be different. Thanks!

Hi @benjamn , thanks for the quick response. Still happens on v3.3.18. I didnt check with 3.4 since that one is on beta and we rather wait for the oficial version. We will check in future stable versions to check if the issue was resolved. We applied the workaround recommended on other issue page to use client.query directly for now.
