### ISSUE TITLE
Cannot remove nested property in cache

### ISSUE THREAD

**Issue by baeharam** [apollographql/apollo-client#8211]
**Intended outcome:**

In official doc, only single field removal is introduced like below.

```typescript
cache.evict({ id: 'some id', fieldName: 'some field' });
```

**Actual outcome:**

There is no explanation for nested property.

```typescript
ROOT_QUERY: {
  analysis: {
    receipts: {
      ...
    }
  }
}
```
I cannot remove `receipts` field by using `cache.evict()`.

**How to reproduce the issue:**

Cannot be reproduced, because I cannot implement it. I also asked in [discussion](https://github.com/apollographql/apollo-client/discussions/8193) and [SO](https://stackoverflow.com/questions/67484408/how-to-remove-nested-object-form-apollo-cache), but couldn't solve the problem.

**Versions**

@apollo/client: 3.3.9
pnpm: 6.3.0

**Comment by baeharam** [comment]
For anyone to view later, I solved it by [this answer](https://stackoverflow.com/a/67512810/11789111). But, I cannot ensure it is right solution. 🤔

**Comment by benjamn** [comment]
@baeharam Actually, `cache.modify` is what I was going to suggest here! Let us know if you have any more questions about how it works.

**Comment by baeharam** [comment]
@benjamn Got it, thanks.
