### ISSUE TITLE
Pagination with relayStylePagination - how to use ALL keyArgs? 

### ISSUE THREAD

**Issue by Lyubomyr** [apollographql/apollo-client#8212]
Hi. I have multiple queries with a long list of arguments that I am using for filtering items. 

Apollo Cache works perfectly well without pagination: each list of items cached separately to each set of arguments (filters) and on UI I can always see the proper list of items. 

When I have added ```relayStylePagination()``` to ```InMemoryCache``` this behavior was broken. If I understand the reason correctly it's because of the default ```keyArgs: false``` for ```relayStylePagination()```. 

The question: is it possible to force ```relayStylePagination()``` behave the same as it was by default without pagination? I mean that ```relayStylePagination()``` will get in count all the arguments and separate cached lists with different sets of arguments. 

Alternatively, I can path all my arguments to ```relayStylePagination()```, but this will be ugly and hard to support.

``` 
const cache = new InMemoryCache({
  typePolicies: {
    User: {
      fields: {
        models: relayStylePagination([longListOfCustomAndChangingArgumensShouldBeHere]),
        animals: relayStylePagination([longListOfCustomAndChangingArgumensShouldBeHere]),
        locations: relayStylePagination([longListOfCustomAndChangingArgumensShouldBeHere])
      }
    },
  },
})
```

**Comment by benjamn** [comment]
@Lyubomyr In case this is helpful, the [`keyArgs`](https://github.com/apollographql/apollo-client/blob/8ef9e64f6a3b069ae241b97bc25902e47dd944b1/src/cache/inmemory/policies.ts#L105-L113) configuration can also be a function:
```ts
new InMemoryCache({
  typePolicies: {
    User: {
      fields: {
        models: relayStylePagination(args => {
          // Return any string you like here, or an array of strings to simulate
          // keyArgs: [...] dynamically, without having to do your own serialization.
        }),
        ...
      },
    },
  },
})
```
If (some of) the field policies all share the same `keyArgs` function, you can define that function once and reuse it multiple times, which should reduce the amount of code and improve maintainability.

**Comment by benjamn** [comment]
One risk of just returning `JSON.stringify(args)` is that the keys might appear in different orders over time. A typical solution for this problem is to use a utility like [`fast-json-stable-stringify`](https://www.npmjs.com/package/fast-json-stable-stringify).

**Comment by Lyubomyr** [comment]
Hi @benjamn. Thank you for your help!

[keyArgs ](https://github.com/apollographql/apollo-client/blob/8ef9e64f6a3b069ae241b97bc25902e47dd944b1/src/cache/inmemory/policies.ts#L105-L113) function is really useful. And I found that it's also legit to return an array of arguments. But to make pagination work properly first I need to remove pagination arguments from it. So, I end up with something like:

```
...
  models: relayStylePagination(args => Object.keys(args || {}).filter(arg => !['first', 'after'].includes(arg))
...

```

Looks like it works properly.

**Comment by benjamn** [comment]
Yep that should work!

Another trick for excluding object properties is to use object `...rest` notation:
```ts
const { first, after, ...rest } = args || {};
return Object.keys(rest).sort();
```

**Comment by hwillson** [comment]
Sounds like this has been solved. Thanks!
