### ISSUE TITLE
Should refetch function for useLazyQuery run onCompleted callback

### ISSUE THREAD

**Issue by Lyubomyr** [apollographql/apollo-client#8220]
Hi. I am using ```useLazyQuery``` which is very good when I need to change state on some circumstances. It's working properly until I need to refetch data because some were changed. And when I called ```refetchResource``` it didn't call ```onCompleted```, so state not updated. How to handle such scenario?

```
  const [resource, changeResource] = useState()

  const [getResource, {refetch: refetchResource}] = useLazyQuery(resourceQuery, {
    onCompleted: data => {
      changeResource(data.resource)
    }
  })
```

**Comment by flashtheman** [comment]
Try adding notifyOnNetworkStatusChange: true.

```
  const [getResource, {refetch: refetchResource}] = useLazyQuery(resourceQuery, {
    notifyOnNetworkStatusChange: true,
    onCompleted: data => {
      changeResource(data.resource)
    }
  })
```

**Comment by Lyubomyr** [comment]
@flashtheman Thanks for your answer. I have changed all to `useQuery`, so can't verify your answer. `useQuery` works perfectly. Hope your answer will help future seekers.
