### ISSUE TITLE
[Subscriptions] client.subscribe "complete" method does not fire

### ISSUE THREAD

**Issue by ucallQA** [apollographql/apollo-client#8233]
**Intended outcome:**
The application needs to know when the subscription has completed (I assume this means when the websocket connection has been established), so the complete method should run once this happens

**Actual outcome:**
Nothing happens, complete never runs in the lifecycle of the websocket connection

**How to reproduce the issue:**
Try running the following code with any subscription

```
const chatActivity = client.subscribe({
	query: GraphQL.SubscribeToChat
})
this.chatActivitySubscribed = chatActivity.subscribe({
	next: ({ data }) => {
		console.log('We got some data!: ', data);
	},
	error(err) {
		console.error('SUBSCRIPTION ERROR: ', err);
	},
	complete: () => {
		console.log('SUBSCRIPTION COMPLETED!');
	}
})
```

**Versions**
```
  System:
    OS: Windows 10
  Binaries:
    Node: 14.15.4
    Yarn: 1.22.10
    npm: 6.14.10
  npmPackages:
    @apollo/client: ^3.3.18 => 3.3.18
    @apollo/react-hooks: ^4.0.0 => 4.0.0
    apollo-cache-inmemory: ^1.6.6 => 1.6.6
    apollo-link: ^1.2.14 => 1.2.14
    apollo-link-context: ^1.0.20 => 1.0.20
    apollo-link-http: ^1.5.17 => 1.5.17
    react-apollo: ^3.1.5 => 3.1.5
```

** NOTE **
If possible any help with finding documentation on these methods would be appreciated, it's extremely difficult to find any reference

**Comment by hwillson** [comment]
@ucallQA this should work properly; are you calling `unsubscribe` on `this.chatActivitySubscribed`? If you think there is an issue here and can provide a small runnable reproduction, we'll re-open this and take a look. Thanks!
