### ISSUE TITLE
SchemaLink validate option is undocumented

### ISSUE THREAD

**Issue by bradbarrow** [apollographql/apollo-client#8240]
**Intended outcome:**

Using an ApolloClient instance with either `SchemaLink` OR `HttpLink` should return the same errors if a malformed query is provided

**Actual outcome:**

Using an `HttpLink` returns the expected validation errors indicating that the query is malformed.

Using `SchemaLink` does not return the expected errors and also doesn't raise an exception.

Passing `validate: true` to SchemaLink constructor re-instates expected behaviour.

**How to reproduce the issue:**

- Create an ApolloClient instance with a `new SchemaLink({ schema })` and no other options.
- Run `apolloClient.query({ query: malformedQuery })` where the query name or a field has a syntax error.
- Note that no errors are returned or caught by the client
- Pass `validate: true` to the `SchemaLink`: `new SchemaLink({ schema, validate: true })`
- Re-run the query and note that errors are returned
- Note that `validate` is [not documented](https://www.apollographql.com/docs/react/api/link/apollo-link-schema/#options)

I didn't use the template, but reproduction codesandbox [here](https://codesandbox.io/s/node-js-forked-0locd?file=/src/index.js). Comment out `validate: true` to see the issue.

**Versions**

```
System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.16.1 - ~/n/bin/node
    Yarn: 1.22.10 - ~/n/bin/yarn
    npm: 6.14.12 - ~/n/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Safari: 14.1
  npmPackages:
    @apollo/client: ^3.3.18 => 3.3.18 
    apollo-server-micro: ^2.14.2 => 2.19.2 
```

**Comment by benjamn** [comment]
Thanks again to @xzyfer for fixing this in #8239!
