### ISSUE TITLE
useQuery and useLazyQuery hooks removing properties from response body in their data key.

### ISSUE THREAD

**Issue by honeynegi** [apollographql/apollo-client#8241]
**Intended outcome:**
const getDataQuery = gql`query{getTodos{todos{title,date,description,....}}}`; //this is just a mock up
const [getData,{data}] = useLazyQuery(getDataQuery);
when i call getData(), the response body of the network call contain all the properties described in my query, but the data key of the useLazyQuery is missing some properties.

BUT when i use useMutation HOOK to fetch the data it contains all the properties.(using the same query as used in useLazyQuery)

network call response body contains : 
{
query: "getTodos",
data:{
getTodos:{
todos:{
title: "something",
date:"date obj",
description: "long description.....",
info:[{
userId: "12scdrfdfafasf223",
userEmail: "...@xmail.com",
hobby: "none",
occupation: "none",
},{
userId: "42scdrfdfafasf823",
userEmail: "...@xmail.com",
hobby: "none",
occupation: "none",
}]
}
}
}
}

**Actual outcome:**
but the "data" key of useLazyQuery or useQuery contains:
{
getTodos:{
todos:{
title: "something",
date:"date obj",
description: "long description.....",
info:[]
}
}
}

as you can see the info key is missing data. but the response body of network call contains. What could be the issue, am I doing something wrong here.

**Versions**

  System:
    OS: macOS 11.2.3
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Safari: 14.0.3
  npmPackages:
    apollo-cache-inmemory: ^1.6.6 => 1.6.6 
    apollo-cache-persist: ^0.1.1 => 0.1.1 
    apollo-client: ^2.6.10 => 2.6.10 
    apollo-link: ^1.2.14 => 1.2.14 
    apollo-link-context: ^1.0.20 => 1.0.20 
    apollo-link-error: ^1.1.13 => 1.1.13 
    apollo-link-ws: ^1.0.20 => 1.0.20 
    apollo-upload-client: ^13.0.0 => 13.0.0 
    apollo-utilities: ^1.3.4 => 1.3.4 
    react-apollo: ^3.1.5 => 3.1.5

**Comment by hwillson** [comment]
@honeynegi it's hard to tell from your description, but this doesn't sound like an Apollo Client bug. If you think it is and can provide a small runnable reproduction that demonstrates the issue, we'll take a closer look. Otherwise please consider posting for help on our community forums: https://community.apollographql.com - thanks!
