### ISSUE TITLE
data not refreshed after second useQuery call

### ISSUE THREAD

**Issue by BoraKuldeep2** [apollographql/apollo-client#8242]
I am using useQuery like below:
```
 const [query, setQuery] = useState(GET_PRODUCTS);
 const { data, loading, error } = useQuery(query);
```
There is a search box component which takes the setQuery prop.  When user types in search box and submit, the setQuery will set the query and above component should re-render. 

**Intended outcome:**
The data should be updated with search results.

**Actual outcome:**
I can see the search graphql query is executed and gives search results (network tab) but data is still undefined in above component and it never refreshes . Loading works ok however.

**Versions**
@apollo/client: "^3.3.18"

**Comment by hwillson** [comment]
@BoraKuldeep2 this doesn't sound like a bug. If you think it is please provide a small runnable reproduction. For help using Apollo Client, please post your question over in https://community.apollographql.com. Thanks!
