### ISSUE TITLE
`relayStylePagination` `read` method clobbers `pageInfo.startCursor` and `pageInfo.endCursor`

### ISSUE THREAD

**Issue by migueloller** [apollographql/apollo-client#8267]
**Intended outcome:**
With a query as follows:

```graphql
query {
  someConnectionField {
    edges {
      node {
        id
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
```

I would expect `endCursor` to be the value returned from the API, not `""`.

**Actual outcome:**
Even though the API returns a valid cursor in `endCursor`, the `relayStylePagination` type policy attempts to read it from `edges[0].cursor` (or the last edge's cursor) and completely replaces the one in `pageInfo.

These should default to `pageInfo.{startCursor,endCursor}` and not `""`.
https://github.com/apollographql/apollo-client/blob/cefb3c32621de6973191c7abb6edd365d53cbf41/src/utilities/policies/pagination.ts#L101-L102

**How to reproduce the issue:**
Perform a query as described above while using `relayStylePagination`.

**Comment by meliborn** [comment]
Having the same issue, can't use ```relayStylePagination()``` at all. Cursors are always empty.

**Comment by meliborn** [comment]
So i just copies all implementation and replaced
https://github.com/apollographql/apollo-client/blob/54fe88a4dd7d3f0850f37a5dcf93c8404bf6e566/src/utilities/policies/pagination.ts#L101-L102
By
```javascript
let { startCursor } = existing.pageInfo;
let { endCursor } = existing.pageInfo;
```

**Comment by diracs-delta** [comment]
This is a serious issue. Relay-style pagination is one of the core features offered by all GraphQL implementations, and is included in the official GraphQL docs. Can this please receive further attention?

**Comment by benjamn** [comment]
@migueloller @diracs-delta @meliborn Please have a look at this PR and let me know if it meets your expectations: #8438

**Comment by diracs-delta** [comment]
@benjamn Gave your PR a quick glance, it looks good to me. Glad it was (relatively) easy! I was just about to submit a PR earlier, but you beat me to it 😅 . TYSM!
