### ISSUE TITLE
onCompleted option not available for refetchQueries

### ISSUE THREAD

**Issue by infinite-sahil** [apollographql/apollo-client#8275]
Hi Team,

First of all, Thank you so much for coding a wonderful library.

Now coming to my question here,
I wanna execute a query on completion of a mutation [every time an action occurs/mutation is called].
now apollo provides an option to execute a GQL query after a mutation using **refetchQueries** option.

but I am looking for, **How we can perform an action like updating the react context data [this shouldn't be async] with the re-fetched query response?**

Can you please share some examples if this is possible? if not, is there a way we can achieve this with the current version of apollo-client??

**Comment by hwillson** [comment]
@infinite-sahil would you mind asking this question over at https://community.apollographql.com? We would like to keep issues here for bugs only. Thanks!

**Comment by infinite-sahil** [comment]
@hwillson Make sense. Thank you.
