### ISSUE TITLE
Fragment fields do not work in tests with MockedProvider

### ISSUE THREAD

**Issue by richardwu** [apollographql/apollo-client#8276]
**Intended outcome:**
Queries with fragments should pass through all fragment fields in tests.

**Actual outcome:**
Queries with fragments in tests do not pass through the fields from the fragment.

**How to reproduce the issue:**
I have the following fragment + query.
```js
const FRAG= gql`
  fragment FooFields on Foo {
    id
    foobar {
      id
    }
  }
`

const QUERY = gql`
  ${FRAG}
  query fetchFoo (id: ID!) {
     fetchFoo(id: $id) {
       ...FooFields
     }
  }
`
```

where the query's schema looks like:
```js
  type Foobar {
     id: ID!
  }
  type Foo {
     id: ID!
     foobar: Foobar!
  }
  extend type Query {
    fetchFoo(id: ID!): Foo!
  }
```

Performing the query in a jest test with the following:
```js

const fragmentDefaultOptions: DefaultOptions = {
  watchQuery: { fetchPolicy: "no-cache" },
  query: { fetchPolicy: "no-cache" },
};

const mocks = [
  {
    request: {
      query: FETCH_FOO,
      variables: {
        id: "some-foo",
      },
    },
    result: {
      data: {
       fetchFoo: {
         id: "some-foo",
        foobar: {
          id: "some-foobar",
        }
      },
    },
  },
];

...  = render(
      <MockedProvider
        mocks={mocks}
        addTypename={false}
        defaultOptions={fragmentDefaultOptions}
      >
          <SomeComponent />
      </MockedProvider>
)
```
where `SomeComponent` performs the call:
```js
  const {
    data,
    error,
    refetch,
    loading,
  } = useQuery(FETCH_FOO, {
    variables: {
      id: fooId,
    },
    fetchPolicy: "cache-and-network",
  });
```

It seems like if I use `...FooFields`, then `data.fetchFoo` is an empty object in the **test only**. If I inline the fields:
```js
const QUERY = gql`
  query fetchFoo (id: ID!) {
     fetchFoo(id: $id) {
       id
       foobar {
         id
       }
     }
  }
`
```
then it works fine both in tests and in the actual app.

**Versions**
```
  System:
    OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
  Binaries:
    Node: 15.0.1 - ~/.nvm/versions/node/v15.0.1/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.0.3 - ~/.nvm/versions/node/v15.0.1/bin/npm
  Browsers:
    Firefox: 84.0
  npmPackages:
    @apollo/client: ^3.2.5 => 3.2.5
```

**Comment by zkinsk** [comment]
After spending a chunk of the morning trying to figure out why my new test was returning empty data ` data { budgets: { budgetLineItem: {} } }`  

I was just coming here to report the same issue.

**Comment by richardwu** [comment]
FWIW: it works for another query of mine where I do not have a nested type in the fragment e.g.,:
```
fragment FooFields on Foo {
  id
  string1
  string2
}
```

**Comment by benjamn** [comment]
@richardwu Your mocked result objects need `__typename` fields, so the fragment constraint `on BudgetLineItem` can match against those objects. Unless you're using interfaces or unions (which bring [`possibleTypes`](https://www.apollographql.com/docs/react/data/fragments/#using-fragments-with-unions-and-interfaces) into play), that type will most likely have the same name as the fragment constraint: `__typename: "BudgetLineItem"`. When in doubt, just ask what your server would return, and try to approximate that with your mock data.

Since Apollo Client requests the `__typename` field automatically, and every GraphQL server knows how to provide a `__typename` for any object type, it's easy to forget how important that information is when you're mocking data, but object type information has wide-reaching consequences, not just for fragment matching but many other type-driven client/cache behaviors. If `__typename` is missing from your mock data, you're not really testing the same behavior that happens outside of your tests, even if the tests are passing.

**Comment by richardwu** [comment]
@benjamn Thanks for the insight: this makes sense. I had followed the [example here](https://www.apollographql.com/docs/react/development-testing/testing/#setting-addtypename) naively, so I assumed it was some bug on the backend.

For posterity, I added the following to my mock:
```
   result: {
      data: {
         __typename: "Foo",
       fetchFoo: {
         id: "some-foo",
        foobar: {
          id: "some-foobar",
        }
      },
    }
```
and changed my MockedProvider to this:
```
      <MockedProvider
        mocks={mocks}
        addTypename={true}
      >
```

**Comment by pimmee** [comment]
I've spent countless hours struggling with this, and if anyone is running into the same issue: 
For some reason including the fragment before the query fails.

This DOES NOT work:
```js 
export const GET_PRESCRIPTIONS = gql`
  ${PrescriptionFragment}
  query GetPrescriptions($patientId: ID!) {
    prescriptions(patientId: $patientId) {
      ...PrescriptionInfo
    }
  }
`;
```
This DOES work:
```js
export const GET_PRESCRIPTIONS = gql`
  query GetPrescriptions($patientId: ID!) {`
    prescriptions(patientId: $patientId) {
      ...PrescriptionInfo
    }
  }
  ${PrescriptionFragment}
`;
```

**Comment by yardenhochman** [comment]
this is still an issue. moving the fragment to the bottom of the query works but that's a strange\random solution

**Comment by asross** [comment]
This is still an issue for me, even with a fragment at the bottom of the query and with `__typename`s everywhere in my mocked response 😭😭😭 

This should probably be reopened...

**Comment by pimmee** [comment]
Another issue with fragments with MockedProvider I've found is that if you have multiple fragments they have to be defined in the same order they're used.

This DOES NOT work:
```ts
export const GuardianFragment = gql`
  fragment GuardianInfo on Guardian {
    id
    person {
      ...PersonInfo
    }
    address {
      ...AddressInfo
    }
  }
  ${AddressFragment}
  ${PersonFragment}
`;
```

This DOES work:

```ts
export const GuardianFragment = gql`
  fragment GuardianInfo on Guardian {
    id
    person {
      ...PersonInfo
    }
    address {
      ...AddressInfo
    }
  }
  ${PersonFragment}
  ${AddressFragment}
`;
```

**Comment by robertoyoc** [comment]
Facing same problem using inline fragments. Any solution? Why is this issue closed?

**Comment by jherman4** [comment]
I am running up against this too. Can anyone give me a good reason for this "feature"? In my mind if `MockProvider` provides a mocked `ApolloClient` the `mocks` prop should specify the input and output for that mock, I shouldn't have to backward engineer the translation `ApolloClient` is already doing just to mock up certain states for `data` so I can unit test my application code! I am sure there are some people who actually need this but it seems like for most its just a non-inuitive "gotcha" that leads to a time consuming solution. There should be an option to opt out of this behavior and I think there is a great argument that it should not even be the default behavior.

**Comment by brandon-leapyear** [comment]
> If `__typename` is missing from your mock data, you're not really testing the same behavior that happens outside of your tests, even if the tests are passing.

@benjamn why do the `MockedProvider` docs say to always use `addTypename={false}` then?
https://www.apollographql.com/docs/react/development-testing/testing/#setting-addtypename

**Comment by CyCTW** [comment]
> @benjamn Thanks for the insight: this makes sense. I had followed the [example here](https://www.apollographql.com/docs/react/development-testing/testing/#setting-addtypename) naively, so I assumed it was some bug on the backend.
> 
> For posterity, I added the following to my mock:
> 
> ```
>    result: {
>       data: {
>          __typename: "Foo",
>        fetchFoo: {
>          id: "some-foo",
>         foobar: {
>           id: "some-foobar",
>         }
>       },
>     }
> ```
> 
> and changed my MockedProvider to this:
> 
> ```
>       <MockedProvider
>         mocks={mocks}
>         addTypename={true}
>       >
> ```

I have met the same issue and try this solution but not work.
However, it works for me when I put the `__typename: "Foo"` in the different position.
For example: 
```javascript=
result: {
  data: {
    fetchFoo: {
      __typename: "Foo",  // Add __typename here
      id: "some-foo",
      foobar: {
        id: "some-foobar",
      }
  },
}
 ```
