### ISSUE TITLE
Symbol-Observable ^2.0.0 crashes Apollo Client in Firefox Web Extension environments. Upgrade to 4.0.0

### ISSUE THREAD

**Issue by conoremclaughlin** [apollographql/apollo-client#8282]
**Intended outcome:**

Load Apollo Client in content scripts within a Firefox Web Extension environment.

**Actual outcome:**

While loading dependencies, symbol-observable will throw a silent exception that Symbol.for is undefined (likely Firefox's bug), and the bootstrapping of the entire app will halt. This can only be found by wrapping transpiled code in a try / catch or setting Firefox to pause on exceptions. See this issue for more information:

https://github.com/benlesh/symbol-observable/issues/53

Ben released 4.0.0 on NPM, no tag for it in his repo yet, that includes the fix for this. Currently, I use Yarn resolutions to swap apollo-client's 2.0.0 dependency for 4.0.0 and it works like a charm.

**How to reproduce the issue:**

1. Add apollo-client to a basic Firefox Web Extension and bootstrap it within a content script.

**Versions**

System:
    OS: macOS 11.3.1
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Edge: 90.0.818.66
    Firefox: 88.0.1
    Safari: 14.1
  npmPackages:
    @apollo/client: ^3.3.19 => 3.3.19 

Thanks so much! Hope this helps others down the road :)

**Comment by benjamn** [comment]
Related: #8003

**Comment by conoremclaughlin** [comment]
@benjamn my swapped resolution 4.0.0 version has been working in production. I'll test `@apollo/client@3.4.0-rc.1` today and report back! Thanks for the fast reply.

**Comment by conoremclaughlin** [comment]
@benjamn looked good during my testing. Looking through symbol-observable's commit history from March 29:
https://github.com/benlesh/symbol-observable/commits/master

It looks like there was a type def change in 3.0.0 that was reverted in 4.0.0 and the two versions otherwise only include fixes, including the one for Firefox. Good luck and thanks again!
