### ISSUE TITLE
TypeError: tsInvariant.setVerbosity is not a function

### ISSUE THREAD

**Issue by 6axter82** [apollographql/apollo-client#8284]
**Versions**
    "@apollo/client": "^3.3.19",
  "@testing-library/dom": "^7.26.0",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.0.4",
    "@testing-library/user-event": "^12.1.8",

Getting the following error in my tests (Using react testing library):

    TypeError: tsInvariant.setVerbosity is not a function

      3 | import { render, queries } from '@testing-library/react'
      4 | import userEvent from '@testing-library/user-event'
    > 5 | import { MockedProvider as ApolloProvider } from '@apollo/client/testing'
        | ^

**Comment by benjamn** [comment]
@6axter82 What version do you see in `node_modules/ts-invariant/package.json`?

**Comment by 6axter82** [comment]
Hi @benjamn,

the version is "version": "0.4.4",

**Comment by benjamn** [comment]
@benjamn Ok, the latest version is 0.7.3. Can you try running `npm i ts-invariant@latest`?

**Comment by 6axter82** [comment]
@benjamn yes, I have added `yarn add ts-invariant@latest` and the version "0.7.3" has been installed and added to my yarn.lock file.
the tests run as expected without errors.
Could you please release the new version with updated ts-invariant library?
Many thanks!

**Comment by 6axter82** [comment]
Yes, that was it. Thanks!
