### ISSUE TITLE
GraphQL Error: invalid input syntax for type uuid: "019f68a5-3f34-4ced-97a9-42f7026ff744d" ?!

### ISSUE THREAD

**Issue by archywillhe** [apollographql/apollo-client#8301]
**Intended outcome:**

It should just work.

**Actual outcome:**

This string is deemed invalid for the type uuid. This makes no sense

**How to reproduce the issue:**

Just use this string as uuid; also this string was generated by 

```
import {v4 as uuid} from 'uuid'
```

so it should be valid; ran into no problem with other uuid string generated the same way

-->

**Versions**

  System:
    OS: macOS 11.1
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/debuild-nextjs-website/node_modules/.bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0.1
    Safari: 14.0.2
  npmPackages:
    @apollo/client: ^3.2.5 => 3.3.19

**Comment by archywillhe** [comment]
This could be a hasura's graphql-engine problem; closing it and reposting to hasura https://github.com/hasura/graphql-engine/issues/6985

**Comment by benjamn** [comment]
@archywillhe We don't use or depend on (or validate the output of) the `uuid` package in this codebase, so I'm pretty sure this problem must be coming from somewhere else!

**Comment by archywillhe** [comment]
@benjamn oh i see! thanks for the clarifcation!
