### ISSUE TITLE
Refactor: calculate loading state from networkStatus

### ISSUE THREAD

**Issue by helfer** [apollographql/apollo-client#831]
`loading` is still used in a lot of places, but it could be entirely replaced with checks on `networkStatus`.

**Comment by calebmer** [comment]
We want to make sure this change fixes the following issues:

- https://github.com/apollostack/apollo-client/issues/1186
- https://github.com/apollostack/react-apollo/issues/401

Let me know if there are more that we should look at when testing this change.
