### ISSUE TITLE
Is client.query() supposed to log the query in the Chrome Extension

### ISSUE THREAD

**Issue by phbou72** [apollographql/apollo-client#8327]
Hi, so for performance reason and also because it's not a good practice with hooks to use them in a forEach I'm using `client.query` directly to query graphql and get a promise for each query I'm bundling together in a Promise.all(). It work very well, however the queries are not showing up in the Chrome Extension of Apollo. Is this a bug? There's also nothing in the cache panel!

**Comment by hwillson** [comment]
@phbou72 would you mind opening this issue in the https://github.com/apollographql/apollo-client-devtools repo instead? Thanks!
