### ISSUE TITLE
Nested array items with null id get incorrectly cloned

### ISSUE THREAD

**Issue by jodinathan** [apollographql/apollo-client#8328]
**Intended outcome:**
Fetch some array of objects in a nested fetch.

**Actual outcome:**
Fetching some array in a multilevel nested field: Appzz.allApplicationRatings.edges[0].node.owner.eduzz.qualifications.map(q => q.category.name))
A bug caused my categories to have a null id on the server resolve, but shouldn't matter.
The network is working ok and the categories are all with id null but other props are different.
However, the apollo-client somehow messes up the array collection by apparently cloning the first one.
Like it indexes the array of objects by its id. Then as the id are null, it thinks they are the same.

```gql
query AppViewRatings {
  Appzz {
    allApplicationRatings(filter: { applicationId_eq: [10009] }) {
      edges {
        node {
          id
          points
          text
          createdAt
          owner {
            id
            name
            eduzz {
              id
              qualifications {
                id
                category {
                  # if the id below is null, all categories get cloned with the first category of the list
                  id
                  points
                  name
                  params
                  group {
                    id
                    name
                    __typename
                  }
                  __typename
                }
                __typename
              }
              __typename
            }
            __typename
          }
          __typename
        }
        __typename
      }
      __typename
    }
    __typename
  }
}
```

**How to reproduce the issue:**
From my tests just have a somewhat big deep array of objects with the object id property to null.

**Versions**
yarn says it is 3.3.19

**Comment by sssmi** [comment]
By default apollo client tries to identify the object in cache by __typename and id properties, that creates cache reference someting like: `Category:{"id":null}` that is now same for every category item. You can change those fields in type policies, or for your query use different network policy to not to cache the query result.
