### ISSUE TITLE
Take over existing flutter GraphQL client

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [apollographql/apollo-client#8332]
Hello,

There is a brilliant library for graphQL: https://pub.dev/packages/graphql_flutter
However main maitainer of this library said that he is not going to maitian it anymore because he switched his focus: https://github.com/zino-app/graphql-flutter/issues/894
Also he mentioned that he will not be advocating it to nor flutter team nor apollo team. However he has mentioned that thi slibrary is almost cloned form Apollo client and that Apollo team would be perfect team to take it over.

So I would like to ask - if you guys want to take it over and start to maitain one more client?  
No need to mention that Flutter has very bright future and to have client for it would be very benefitial for you.

Thanks for sahring your insigts and thoughts.

**Comment by hwillson** [comment]
Thanks for this @vytautas-pranskunas-; this isn't something the Apollo Client team can take on at the moment unfortunately. Maybe try reaching out on https://community.apollographql.com to see if someone in the community has the bandwidth? Thanks for bringing this to our attention though!

**Comment by SanjiKir** [comment]
@hwillson Hey man, thanks for your reply. May I ask for a reason for such a decision? Flutter evolving and getting crazy adoption on the market. This is the only library accessible to work with GrapqhQL in a flutter. For me it seems like a perfect match for apollo creators.
