### ISSUE TITLE
Need to remove deprecated apollo-codegen and update with apollo in the developer tooling docs

### ISSUE THREAD

**Issue by SkrewEverything** [apollographql/apollo-client#8343]
While I was going through the documentation, I have observed that the website is still using [apollo-codegen](https://www.npmjs.com/package/apollo-codegen)(deprecated ~3 years ago) in the documentation at [Development & Testing -> Developer Tools](https://www.apollographql.com/docs/react/development-testing/developer-tooling/). Instead, the current documentation should be on [apollo](https://www.npmjs.com/package/apollo).

**Comment by jpvajda** [comment]
We've removed this recently, so I'm going to close this out. Thanks for reporting it.
