### ISSUE TITLE
Why use WebSocketLink  from '@apollo/client/link/ws'

### ISSUE THREAD

**Issue by cesarve77** [apollographql/apollo-client#8345]
1) Sorry for my english.
2) thanks for your time.

In your documentation (https://www.apollographql.com/docs/react/api/link/apollo-link-ws/) you encourage to use WebSocket which depends on subscriptions-transport-ws npm package. but apollographql/subscriptions-transport-ws repo says 

> "The subscriptions-transport-ws library is not being actively maintained. It is recommended that you use the graphql-ws library instead."

Same case here https://www.apollographql.com/docs/graphql-subscriptions/authentication/ .

By other side in the next link you implement difference approach to the same solution, will be great or unify then, or explain pros/cons, or when use what:

https://www.apollographql.com/docs/graphql-subscriptions/express/
https://www.apollographql.com/docs/apollo-server/data/subscriptions/#example-authentication-with-onconnect

Finally I would like to ask you about an example to how implement graphql-ws with apollo server.

**Comment by dondonz** [comment]
+1, I think it would be better to link to the new `graphql-ws` library which is being actively maintained.

To the maintainers: was there a particular reason for using `subscriptions-transport-ws` in the example docs? If not, happy to work on getting this updated for the replacement library

**Comment by cesarve77** [comment]
I tried to implement graphql-ws with apollo (following the example in graphql-ws documentation) but i had no success.
Will be great have a oficial documentation to how to implement.

**Comment by novym** [comment]
+1

**Comment by intellix** [comment]
Example is here: https://github.com/enisdenjo/graphql-ws#apollo-client

**Comment by hwillson** [comment]
This work was completed and will be included in the soon to be released `@apollo/client@3.6`. Thanks!
