### ISSUE TITLE
useQuery fetch data is different in network and console.log

### ISSUE THREAD

**Issue by XXuain** [apollographql/apollo-client#8359]
Hi, I have a problem is when I use ` useQuery ` to fetch a list, but it saw differences in network and console

this is network display, can see the inviteeUserIDs is ` inviteeUserIDs: [2] ` and ` inviteeUserIDs: [16, 13] `
![截圖 2021-06-08 下午5 27 27](https://user-images.githubusercontent.com/34267828/121160620-d468bb00-c87e-11eb-95e1-11e4ba48bc14.png)

but when I success fetch it and use ` console.log ` to display it, it like
all the` inviteeUserIDs ` become ` inviteeUserIDs: [2] ` !!!!
![截圖 2021-06-08 下午5 28 33](https://user-images.githubusercontent.com/34267828/121160772-f5311080-c87e-11eb-88e8-7b3d6e156ef9.png)

my code is 
```
const { data } = useQuery(apiType.LIST_MESSAGE, {
    variables: { filter: { roomID: 143 } }
  });
  console.log(data);
  ```

I don't know why QQ
i have try to add options ` fetchPolicy: 'no-cache', ` , but it seen no work

**Comment by maxdbarton97** [comment]
I am getting this also. One of the properties in all objects of an array is being set to false?

**Comment by maxdbarton97** [comment]
I'm seeing similar behaviour. The data being returned looks (generically) like this in the network tab:
`
data: {
    queryName: {
        queryItems: [{ myProp: false }]
    }
}
`

Where `myProp` is the property being set to true for all X of my items.

So in the console, (and when rendering a React component) it's seen as:
`
data: {
    queryName: {
        queryItems: [{ myProp: true }]
    }
}
`

**Comment by dylanwulf** [comment]
The problem here is that `invite.id` is `0` for both objects. Apollo client assumes that the `id` field is a unique value that is safe to use as an identifier, but here it seems that's not the case.

**Comment by dylanwulf** [comment]
See here for more info: https://www.apollographql.com/docs/react/caching/cache-configuration/#customizing-identifier-generation-by-type

If your `MsgInvite` objects do not have any globally unique identifiers, then you can pass `keyFields: []` for the `MsgInvite` type in the cache configuration

**Comment by XXuain** [comment]
Hi, @maxdbarton97  @dylanwulf  thank's a lot for your reply.

I try two ways,
one way is to delete id props, it works, but I think it's not really a good way,
another way I try :

```
const createApolloClient = ({ onError }) => {
  return new ApolloClient({
    link: from([authMiddleware, createErrorLink(onError), splitLink]),
    cache: new InMemoryCache({
      typePolicies: { MsgInvite: { keyFields: ['inviteeUserIDs'] } }
    })
  });
};
```
It works!!


But I think if it can definition when I use `useQuery` to fetch ` listMessage ` have a property like ` typePolicies `.
