### ISSUE TITLE
query issues when cntrl + click to open a new tab without visiting it until page is done loading

### ISSUE THREAD

**Issue by JimmyBlundell** [apollographql/apollo-client#8360]
I'll paraphrase this as best as I can. We have apollo graphql queries that fetch user info and permissions, but I'm running into issues with these queries actually completing when I control + click to open a new tab and wait until it is finished loading before I visit it. It seems that the query which fetches user permissions never actually returns anything.

Forcing the query's fetch policy to be network-only fixes this issue, and I have no idea why. We don't want this as a solution because:
A. It feels like a work around.
B. This is a rather intensive query. If we can cache the data we want to do that. It takes almost half a second longer when I force the query to be network-only.

For reference, the code looks like so:<br>
```js
// get some initial data about user, not including permissions
const { loading, data } = useQuery(GET_INITIAL_DATA);

// get permissions and roles for user after the initial query has ran
  const { loading: permissionsLoading, data: permissionsData } = useQuery(
    GET_PERMISSIONS_ASYNC,
    {
      skip: loading
    }
  );

// not worried about this first useEffect
  useEffect(() => {
    if (loading) {
      return;
    }
    setViewer(data.viewer);
  }, [data]);

// this useEffect doesn't make it past the early return
  useEffect(() => {
    if (permissionsLoading || !permissionsData) {
      return;
    }
    setViewer({
      ...viewer,
      ...{ permissions: permissionsData.viewer.permissions },
      ...{ roles: permissionsData.viewer.roles }
    });
  }, [permissionsData]);
  ```
  Using `fetchPolicy: network-only` resolves this, but we don't want to rely on that. It causes the query to take almost half a second longer, and seems more of a work around than anything. Is this a bug, or could there be something going on that I'm not aware of?

**Comment by bignimbus** [comment]
Hi @JimmyBlundell 👋🏻  thanks for your patience.  Have you found a way forward here?  If you're in need of support I recommend creating a runnable reproduction via [this template](https://github.com/apollographql/react-apollo-error-template/generate) so we can observe the actual behavior and compare it to what you'd expect.  I really appreciate the code snippet you provided but I don't think there's enough information to narrow down a resolution.  Thanks a bunch!
