### ISSUE TITLE
React 18 SSR Support

### ISSUE THREAD

**Issue by wintercounter** [apollographql/apollo-client#8365]
I'd like to start a discussion about React 18 and its changes to Suspense/SSR and what that means to us Apollo users. It was always a pain point for me that I couldn't do proper bundle splitting (w/o 3rd party tools) due to the lack of Suspense support during SSR.

With React 18 we get SSR Suspense support, and it seems like the new [`pipeToNodeWritable` API](https://github.com/reactwg/react-18/discussions/22) can completely eliminate `getDataFromTree` (at least in its current form).

The new API will be something like this. (https://codesandbox.io/s/github/facebook/react/tree/master/fixtures/ssr2?file=/server/render.js)

```jsx
const {startWriting, abort} = pipeToNodeWritable(
    <DataProvider data={data}>
      <App assets={assets} />
    </DataProvider>,
    res,
    {
      onReadyToStream() {
        res.statusCode = didError ? 500 : 200;
        res.setHeader('Content-type', 'text/html');
        res.write('<!DOCTYPE html>');
        startWriting();
      },
    }
  );
```

This has an interesting problem: where and how we will pass `INITIAL_APOLLO_STATE` on. The previous common practice was to simply get the data from the cache, put it on `window` in the markup, load it on the client-side during hydration.

For me, it looks like that we will be able to do this without any extra code/workaround now, and we can simply include the above process in our code. Something like:

```jsx
<html>
    <body>
        ...
        <script dangerouslySetInnerHTML={{ __html: `
            window.INITIAL_APOLLO_STATE = ${myInMemoryCacheInstance.extract()}
        ` }} />
    </body>
</html>
```

I haven't experimented with it yet, but I'll soon and get back with the results.

**Comment by brendanmoore** [comment]
```jsx
<html>
    <body>
        ...
        <script dangerouslySetInnerHTML={{ __html: `
            window.INITIAL_APOLLO_STATE = ${myInMemoryCacheInstance.extract()}
        ` }} />
    </body>
</html>
```
This is great! I was thinking about a similar solution, where and how that `<script  />` is added is up to `ApolloProvider` (or similar) and it should "just work"

**Comment by wintercounter** [comment]
Unfortunately, it's not so easy. The problem is that you'll need Suspense + React.lazy to make this work. If React won't provide any hook level API for suspense then we will still need our own wrappers. Also, this cannot work at all using streaming. The new APIs will provide `onReadyToStream` and `onCompleteAll` during SSR. `onCompleteAll` does support dynamic imports through Suspense + Lazy, but that's all, it won't wait for our queries to resolve first.

**Comment by brendanmoore** [comment]
Ah okay that is unfortunate. I guess in my head I assumed we could "throw" a suspender and the server-side suspense would wait for it to resolve, we'd add a new `<script />`, and each new one would blat the previous

**Comment by wintercounter** [comment]
Last week I decided to give another try to the topic, so I dug deep into the topic. I've made work Apollo SSR with React 18 and Suspense for lazy loading together, and actually, it's not hard at all. I decided to share my method.

1. Update React to v18.
1. Use a custom `getDataFromTree` function. Apollo uses `renderToStaticMarkup` by default. The problem is that it will strip out all the necessary markers for hydration (in case you just need this for SEO reasons, just skip this step, you won't hydrate in that case).
```
const getDataFromTree = (tree, context) => {
    return getMarkupFromTree({
        tree,
        context,
        renderFunction: require('react-dom/server').renderToString
    })
}
```
3. Add Suspense and lazy components as necessary to your codebase.
3. Use the new `hydrateRoot` method on client side.
3. Profit.

### There is one gotcha, however.

On the first render, no data/tree will be returned. Once a lazy module was loaded, it'll start working fine. So this means after page refresh it'll work correctly. To overcome this issue I simply created a separate file on server-side that will load all the available lazy modules upon initialization.

In case you have `lazy(() => import('./components/moduleA'))` somewhere in you codebase. You must have `require('./components/moduleA')` somewhere before SSR happens so the module is already in cache.

I don't know if this is a limitation of React's SSR, Apollo's `getMarkupFromTree` or it's the result of swc's transpilation to CommonJS, this should be investigated further.

Seems like returning an immediately resolved promise for the module keeps rendering "sync" somehow.

**Anyway, I have a working bundle splitting + Apollo + SSR combo finally!**

**Comment by meierchris** [comment]
@wintercounter Could you maybe share a small codesandbox for your working bundle splitting + Apollo + SSR combo? That would be great.

**Comment by wintercounter** [comment]
If you provide me a basic Apollo SSR setup, I'll adjust it, but I don't really want to set up the base for this :) I really hate Codesandbox, it's buggy, slow, and annoying to work with :D

**Comment by wintercounter** [comment]
@meierchris 

Meanwhile, I have quickly put together a demo: https://github.com/wintercounter/react18-apollo-ssr-bundle-split-demo
You can run it using GitPod or locally. I added some basic readme about the setup. Please let me know how it went.

Since I posted this solution here, I started to use it in production on a large codebase, I don't have any issues.

**Comment by jpvajda** [comment]
https://github.com/apollographql/apollo-client/issues/9627

**Comment by jerelmiller** [comment]
Hey all :wave:

Just wanted you to be aware that we’ve just opened up an RFC (#10231) where we have a much more detailed approach to React suspense and SSR. We plan to continue the conversation over there so please have a look! Thanks for all the discussion so far!
