### ISSUE TITLE
Optimistic Response Produces Different Behaviour To Actual Server Response

### ISSUE THREAD

**Issue by rossm6** [apollographql/apollo-client#8367]
**Intended outcome:**

The optimistic response should simply pass the dummy object to the update function defined in the mutation and when the server response is received this object is replaced by actual server response object.  In terms of the UI it temporarily reflects the dummy object, which is the optimisticResponse, then reflects the actual server response.

**Actual outcome:**

The optimistic response causes different behaviour - an unnecessary network request relating to a query which on the face of it is completely unrelated to the mutation the optimistic response concerns.  This can be seen by simply commenting out the optimistic response.  In my own local development I observed the extra network request by looking at the network tab in the browser but the fetch requests don't seem to show with the error template set up you guys provide (don't know why).  So what I did instead was change the resolution of the mutation so that it changes the data returned by this unrelated query.  Please follow the steps below to easily follow what I mean.

**How to reproduce the issue:**

Here is the repo which reproduces the problem - https://github.com/rossm6/react-apollo-error-template

Steps to take -

1. Load application in browser.
2. Open console in dev tools
3. Observe that the whole list - all 3 people - are logged to the console.
4. Click the button "Remove Only Payment Method"
5. Observe that the query "ALL_PEOPLE" has run again because now two people are printed to the console.
6. Comment out the optimisticResponse for the removeStripePaymentMethod mutation.
7. Reload the application and press the same button.  Notice this time only three people are printed to the console.  In other words the optimistic response causes another network request.  This is unwanted and unexpected.  It should behave the same way like when the optimistic response isn't used.

**Versions**
  System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.4 - /usr/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 89.0
  npmPackages:
    @apollo/client: ^3.3.12 => 3.3.12

**Comment by dylanwulf** [comment]
>  the fetch requests don't seem to show with the error template set up you guys provide (don't know why)

This is because the error template doesn't make network requests or connect to a server. It uses an ApolloLink to resolve all queries locally without ever sending any network requests

**Comment by rossm6** [comment]
OK.  Still the issue remains.

**Comment by rossm6** [comment]
I can confirm this issue is fixed in both the bug reproduction and the actual application I'm developing where I stumbled upon this issue.  Thanks for all your help.
