### ISSUE TITLE
https issue

### ISSUE THREAD

**Issue by JosePatricio** [apollographql/apollo-client#8368]
**Actual outcome:**
I am using @apollo/client, with React and React Native.
both work fine with HTTP endpoints, but when the service changes to HTTPS in React and React Native (IOS) it still works but in React Native (Android) there is an error [Error: Network request failed].
Any suggestion?

**Versions**
 "@apollo/client": "^3.3.20",

System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 988.48 MB / 15.89 GB
  Binaries:
    Node: 15.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.5.3 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29, 30
      Build Tools: 23.0.1, 23.0.3, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3, 29.0.2, 29.0.3
      System Images: android-24 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: 16.8.30907.101 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_221
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.1 => 17.0.2
    react-native: 0.64.2 => 0.64.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by codal-hkrishnani** [comment]
@JosePatricio What was the solution I am facing same ?
I am getting network request faild.

Error: Response not successful: Received status code 400
    at new ApolloError (errors.cjs.js:31)
    at Object.error (core.cjs.js:1084)
    at notifySubscription (Observable.js:140)
    at onNotify (Observable.js:179)
    at SubscriptionObserver.error (Observable.js:240)
    at utilities.cjs.js:946
    at Array.forEach (<anonymous>)
    at iterateObserversSafely (utilities.cjs.js:946)
    at Object.error (utilities.cjs.js:1039)
    at notifySubscription (Observable.js:140)
