### ISSUE TITLE
ApolloClient Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by technoligest** [apollographql/apollo-client#8381]
**Intended outcome:**
The app loads

**Actual outcome:**
Getting
 invariant.esm.js:9 Uncaught TypeError: Object(...) is not a function
[
<img width="465" alt="Screen Shot 2021-06-12 at 2 31 55 PM" src="https://user-images.githubusercontent.com/8812428/121789501-54e33080-cb8b-11eb-8592-482659dc9a13.png">
](url)

**How to reproduce the issue:**
Not sure how to repro. Looking for guidance on how to debug the issue. The exact project is in prod, but I'm unable to start the app locally at this point. Not sure if there's been a recent change to one of the apollo packages or what the issue is.

Any guidance on how to debug would be very much appreciated. The app loads a white screen and the screenshot above is what shows up in console.

**Versions**
  System:
    OS: macOS 11.4
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.101
    Firefox: 89.0
    Safari: 14.1.1
  npmPackages:
    @apollo/client: ~3.2.5 => 3.2.9 
    apollo-upload-client: ^13.0.0 => 13.0.0

**Comment by bignimbus** [comment]
Hi @technoligest 👋🏻  thanks for your patience!  Have you found a way forward on this?  I'm sure the community and maintainers can help out here but more information is needed.  Can you provide a runnable reproduction using [this template](https://github.com/apollographql/react-apollo-error-template/generate)?  Thanks again!
