### ISSUE TITLE
Using Reactive variables occurs a memory leak on the SSR

### ISSUE THREAD

**Issue by choijungseon** [apollographql/apollo-client#8387]
### Intended outcome
Using `Reactive variables` on the SSR shouldn't create a memory leak.

### Actual outcome
Using `Reactive variables` on the SSR creates a memory leak when i follow the example.(https://www.apollographql.com/docs/react/local-state/managing-state-with-field-policies/#example)
- Note that, we creates new apollo client, reactiveVar instances for every request

But if i try to access `Reactive variables` with `useReactiveVar`, the app doesn't create a memory leak.

### heapdump output 
![image](https://user-images.githubusercontent.com/11385170/121477137-6baa4b80-ca02-11eb-9092-1760776e4ff8.png)

### Versions
```json
{
   "next": "^10.1.2",
    "apollo/client": "3.3.19",
    "apollo-server-micro": "^2.14.2",
    ...
}
```

**Comment by funccoder** [comment]
I added discussion related this issue

https://github.com/apollographql/apollo-client/discussions/8455
Please check it when you review this issue :)

**Comment by sepehrrtl** [comment]
I also have the same issue. I upgraded apollo/client to 3.4.0-rc.20 but the issue still exists.

**Comment by phryneas** [comment]
Hi there! 
I'm doing some housekeeping right now and I believe this has been addressed in newer versions of Apollo Client, so I'm going to close this issue now. 
If this comes up again in newer versions (>=3.9.0) of Apollo Client, please open a new issue :)
