### ISSUE TITLE
Merge policy control

### ISSUE THREAD

**Issue by Illia-Linevych** [apollographql/apollo-client#8391]
Is there any way to tell apollo to call merge policy only after using fetchMore method? I'm using it to implement infinite scroll and stick existing and incoming data together which works perfectly for me. But when I'm using writeQuery method to change my cache manually, merge policy executes after that operation too and this cause duplicate data.

**Comment by sssmi** [comment]
You can use cache.modify to write data to cache directly. It circumvents the merge function.
https://www.apollographql.com/docs/react/caching/cache-interaction/#example-adding-an-item-to-a-list
