### ISSUE TITLE
v3.4.0 changes TypeScript generics without default fallback

### ISSUE THREAD

**Issue by dotansimha** [apollographql/apollo-client#8407]
**Intended outcome:**

Seems like pre-releases of v3.4.0 changes the signature of `BaseMutationOptions`. This should either have backward compatibility, or introduced as breaking changes. 

**Actual outcome:**

Bump major version / warn for breaking change / Add default types for new `BaseMutationOptions` generics.

**How to reproduce the issue:**

Any piece of code that was `BaseMutationOptions<A, B>` before is now failing.

**Versions**

```
3.4.0-rc.11
```

Related: 
https://github.com/dotansimha/graphql-code-generator/issues/6084

**Comment by brainkim** [comment]
> Seems like pre-releases of v3.4.0 changes the signature of BaseMutationOptions. This should either have backward compatibility, or introduced as breaking changes.

Agreed!
