### ISSUE TITLE
client.writeQuery after mutation making http request

### ISSUE THREAD

**Issue by kubido** [apollographql/apollo-client#8411]
Hi, 

I do a `client.writeQuery()` stuff after the component mutation. I put in `update` or `onCompleted` are the same
```js
  cache.writeQuery({
        query: FETCH_STUDENTS,
        data: {
          students: [...currentStudents, newStudent]
        }
      })
```

it fetches the `students` data to the server.  it's expected behavior?

**Comment by nguyendangdu2001** [comment]
I've fixed that by add `nextFetchPolicy: "cache-only"`  in the query

**Comment by phamhoaivu911** [comment]
Hi @kubido , did you set the `fetchPolicy` of the query `FETCH_STUDENTS` to `cache-and-network`? 

If yes, then setting the `nextFetchPolicy` to `cache-only` (or `cache-first`) will fix the issue. You can check out this https://github.com/apollographql/apollo-client/issues/6760#issuecomment-668188727 for more information.

**Comment by bignimbus** [comment]
Hi all, I'm doing some cleanup.  It looks like this is resolved so I'll close this out.  Thanks!
