### ISSUE TITLE
setContext doesn't modify the main request object

### ISSUE THREAD

**Issue by eakl** [apollographql/apollo-client#8433]
**Intended outcome:**

`setContext` in ApolloLink doesn't modify the main request object but does modify the `headers` sub-object

```javascript
import { ApolloClient, createHttpLink, ApolloLink, from, InMemoryCache } from '@apollo/client'

const httpLink = createHttpLink({
  uri: `${process.env.SERVER_URL}/graphql`,
  credentials: 'include'
})

const authMiddleware = new ApolloLink((operation, forward) => {
  operation.setContext(({ headers }) => {
    const accessToken = 'cool_access_token'
    
    return {
      key-to-include-to-request-object: 'some-value',
      headers: {
        ...headers,
        key-to-include-to-request-object: 'some-value'
      }
    }
  })
  
  return forward(operation)
})

export const apolloClient = new ApolloClient({
  uri: `${process.env.SERVER_URL}/graphql`,
  link: from([authMiddleware, httpLink]),
  cache: new InMemoryCache()
})
```

**Actual outcome:**

`key-to-include-to-request-object` appears in the `req.headers` object but not in the `req` object.

**Versions**

```
System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 61.0.1
    Safari: 11.1.2
  npmPackages:
    @apollo/client: ^3.3.11 => 3.3.11
```

**Comment by bignimbus** [comment]
Hi @eakl 👋🏻  thanks for your patience!  I recommend going over our [Apollo Link docs](https://www.apollographql.com/docs/react/api/link/introduction/#managing-context) if you haven't already.  I was curious about what you meant by the `request object`.  As I understand it, data stored via `setContext` is retrievable via `operation.getContext()`.  So in the example above, a link later in the chain should be able to access `key-to-include-to-request-object` via `operation.getContext()['key-to-include-to-request-object']`.  Does that help address your use case?
