### ISSUE TITLE
Reactive Variables don't update with useLayoutEffect

### ISSUE THREAD

**Issue by gaberogan** [apollographql/apollo-client#8436]
**Intended outcome:**
Reactive variable should update

**Actual outcome:**
Reactive variable doesn't update

**How to reproduce the issue:**

Minimum repro CodeSandbox: https://codesandbox.io/s/apollo-reactive-variables-forked-o1j4h?file=/src/App.js

```js
  // works if replaced with useEffect
  useLayoutEffect(() => {
    if (bob === "😱") {
      bobVar("😅"); // set bobVar almost immediately again
    }
  }, [bob]);

  // set bobVar somewhere down here
```

**Versions**
3.3.15 (latest)
all versions maybe?

**Note**
The obvious downside to this is you can't useLayoutEffect with reactive variables and instead have to settle for a flash of unwanted content or something.

**Comment by benjamn** [comment]
@gaberogan Try `@apollo/client@beta`? Multiple aspects of reactive variable behavior have improved in v3.4. 🤞
