### ISSUE TITLE
Request headers are duplicated if letter casing is not matched

### ISSUE THREAD

**Issue by umpox** [apollographql/apollo-client#8447]
Apollo sets default headers such as `content-type` and `accept`. It doesn't handle case insensitivity if a developer tries to override these headers.

**Intended outcome:**

Given:
```ts
const client = new ApolloClient({
    uri: GRAPHQL_URI,
    cache: new InMemoryCache(),
    link: createHttpLink({
        uri: GRAPHQL_URI,
        headers: {
            Accept: 'application/json',
            'Content-Type': 'application/json',
        },
    }),
})
```

I would expect the request headers to be set accordingly

**Actual outcome:**
Request headers are set as:

```
accept: */*, application/json
content-type: application/json, application/json
```

I believe it is related to case (in)sensitivity as It is possible to correct this by matching Apollo's default causing, e.g.:
```ts
        headers: {
            accept: 'application/json',
            'content-type': 'application/json',
        },
```
**How to reproduce the issue:**

**Versions**
```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 88.0
    Safari: 14.1.1
  npmPackages:
    @apollo/client: ^3.3.20 => 3.3.20 
```

**Comment by benjamn** [comment]
@umpox Thanks for letting us know about this problem! Is this the sort of fix you had in mind? https://github.com/apollographql/apollo-client/pull/8449

As a side note, I wasn't aware [Sourcegraph](https://github.com/sourcegraph/sourcegraph) is using Apollo Client, so that's awesome news (to me)! Please let us know if you encounter any other problems with it.

**Comment by umpox** [comment]
@benjamn Thanks for the quick fix, LGTM! We are slowly migrating 😃  will do, thank you!
