### ISSUE TITLE
WebSocketLink Does Not Include Updated Cookies

### ISSUE THREAD

**Issue by rossm6** [apollographql/apollo-client#8448]
**Intended outcome:**

I have this standard websocket link -

```
    const wsLink = new WebSocketLink({
        uri: initialAppState.websocket_graphql_url,
        options: {
            reconnect: true
        }
    });
```

And this http link -

```
    const httpLink = new HttpLink({
        uri: initialAppState.http_graphql_url,
        credentials: "same-origin"
    });
```

Let's say the page loads and the user isn't logged in.  If I then execute a graphql mutation so the user is logged in - the response contains the sessionid cookie - henceforth the http requests through apollo include this latest cookie.  The websocket link should behave the same way by default or offer the means to do so through configuration.

**Actual outcome:**

All websocket requests continue to use the cookies which are somehow defined when this link is initialised when the page first loads.  (I'm unsure how this is the case because my sessionid cookie is http only).

**How to reproduce the issue:**

Not sure it's possible to reproduce this myself with Codebox.

**Versions**

  System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.4 - /usr/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 89.0.2
  npmPackages:
    @apollo/client: ^3.4.0-rc.6 => 3.4.0-rc.6

** Workarounds **

Obviously I could get the page to reload when the user logs in although I'd prefer to not do this.  Another workaround would be to pass a new apollo client to the subscription.  Is this a good idea though?  Can you pass the same memory cache object to two different apollo clients?

**Comment by rossm6** [comment]
Does nobody really have anything to say on this issue?

**Comment by rossm6** [comment]
I opted for the second option of creating a new apollo cient and using the same cache.  All seems ok and I should have tried it first before logging this really.

**Comment by benjamn** [comment]
@rossm6 Sharing a cache between multiple clients should work AFAIK. Please let us know if you hit any problems, since this is a less common technique, so I don't know if the lack of feedback we've gotten means it works fine, or just that no one has tried it.
