### ISSUE TITLE
Workaround for Suspense?

### ISSUE THREAD

**Issue by adsee42** [apollographql/apollo-client#8456]
Since suspense won't be supported very soon (https://github.com/apollographql/apollo-client/issues/8245)

I'd love to know if there any workaround to achieve this?

**Comment by brainkim** [comment]
Thanks for the interest! We’re all agreed that it would be ideal for our React integration to support Suspense, and are working to get that done soon. The workaround would be to use the hooks as they are currently written, which return explicit `{loading, data, error}` tuples. This means you have to manually write loading states, but this is how a lot of React code, not just that of Apollo, is written today. Maybe @hwillson or @benjamn could chime in but I don’t see these APIs going away or being replaced by their Suspense equivalents anytime soon.

Again, we’ll try to have a version of Apollo Client with Suspense support out soon. Thanks for your patience!

**Comment by adsee42** [comment]
Thanks!
I've found a [repo](https://github.com/Fasosnql/use-suspense-query) implemented a `useSuspenseQuery`.
It seems a workaround though it's latest update is one year ago.
