### ISSUE TITLE
useMutation update function doesn't re-render the UI after cache mutation despite the doc stating it does

### ISSUE THREAD

**Issue by eakl** [apollographql/apollo-client#8457]
**Intended outcome:**

**Apollo documentation:**
https://www.apollographql.com/docs/react/data/mutations/
**Section:**
Making all other cache updates
**Paragraph:**
> Any changes you make to cached data inside of an update function are automatically broadcast to queries that are listening for changes to that data. Consequently, your application's UI will update to reflect newly cached values.

Here is my code
```javascript
const [mutate] = useMutation(CREATE_POST, {
    update: (cache, { data }) => {
        const { posts } = cache.readQuery({ query: GET_POSTS })
        const newPost = data.createPost
        const updatedPosts = [...posts, newPost]
        cache.writeQuery({ query: GET_POSTS, data: updatedPosts })
    }
})
```

**Actual outcome:**

The cache is updated but the change is not broadcasted, hence, the component doesn't re-render.

**Versions**

```bash
System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 61.0.1
    Safari: 11.1.2
  npmPackages:
    @apollo/client: ^3.3.11 => 3.3.11
```

**Comment by benjamn** [comment]
@eakl Please try this after updating to v3.4 with `npm i @apollo/client@beta`, if you have a chance?
