### ISSUE TITLE
No data return after set header context 

### ISSUE THREAD

**Issue by globicintbh** [apollographql/apollo-client#8463]
Hi Guys 

I have problem with my request , I didn't get data return but every thing is successful change in database, also I catch error when error present also, this is my code 

```
      const process = client.query({
                query: USERUPDATEAPI,
                fetchPolicy: 'no-cache',
                variables: {
                    id: this.state.IDUser.toString(),
                    firstname: this.state.FirstName.toString(),
                    lastname: this.state.LastName.toString(),
                    email: this.state.Email.toString()
                },
                context: {
                    headers: {
                        authorization: `Bearer ${this.state.Token}`,
                    },
                    
                }
                
            })

            process.then((value) => {
                console.log(">>>> " + JSON.stringify(value)) // here is not fired 
         

            }).catch((error) => {

                console.log("This is error : " + error) // I got error here when error present


            })
```
when I remove this , the code is running but no authorization to access 
```
      context: {
                    headers: {
                        authorization: `Bearer ${this.state.Token}`,
                    },
                    
                }
```

any help please !!

**Comment by globicintbh** [comment]
any help please ??????

**Comment by brainkim** [comment]
@globicintbh I’m sorry to hear you’re having trouble! Do you have an example repository or code sandbox so we can help investigate? The promise should resolve with the data from your API, but it’s tough figuring out what’s wrong based on your example alone.

**Comment by globicintbh** [comment]
@brainkim  thank you for response , actually I don't have repository or code sandbox but the I use this mutate query  with above mutation function to update user data

```
const USERUPDATEAPI = gql`
  mutation UpdateUser($id:ID!, $firstname:String!, $lastname:String!, $email:String!) {
    updateUser(input: {id: $id, firstName: $firstname, lastName: $lastname, email: $email}) {
        user {
            id
            name
            email
            firstName
            lastName
            nickname
            username
            jwtAuthToken
            jwtRefreshToken
            avatar {
              url
            }
        }
      }
    }`;
```

the data is sent and update on database , but not return any callback even error

**Comment by globicintbh** [comment]
I found some thing,, when I set authorization in header I don't get callback either response or error , when I remove authorization and replace with any thing like 'Content-Type' or 'Accept' it is working fine

**Comment by bignimbus** [comment]
Hi @globicintbh it looks like this thread is pretty stale - I'll close this issue for now but please feel free to let us know if you need some more support here 🙏🏻
