### ISSUE TITLE
Apollo client explodes upon receiving empty data

### ISSUE THREAD

**Issue by user1736** [apollographql/apollo-client#8470]
**Intended outcome:**
Apollo client ends request normally preserving errors as `graphQLErrors` received in the response

**Actual outcome:**
Apollo client ends request with a network error with a confusing stack trace

```
TypeError: Cannot read property 'people' of null
    at LocalState.<anonymous> (http://localhost:3000/static/js/vendors~main.chunk.js:3071:34)
    at step (http://localhost:3000/static/js/vendors~main.chunk.js:68866:17)
    at Object.next (http://localhost:3000/static/js/vendors~main.chunk.js:68797:14)
    at http://localhost:3000/static/js/vendors~main.chunk.js:68770:67
    at new Promise (<anonymous>)
    at __awaiter (http://localhost:3000/static/js/vendors~main.chunk.js:68749:10)
    at LocalState.resolveField (http://localhost:3000/static/js/vendors~main.chunk.js:3061:67)
```

**How to reproduce the issue:**
1. run https://github.com/user1736/react-apollo-error-template/tree/client-state-error
2. observe the error

**Versions**

  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 16.4.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.18.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Edge: 91.0.864.48
    Firefox: 84.0.2
    Safari: 14.1
  npmPackages:
    @apollo/client: ^3.3.21 => 3.3.21

**Comment by tjmatteo** [comment]
It's the `@client` annotation that triggers this bug. Apollo takes a different code path when one of those exists in the query, and that path is assuming data is not empty.

**Comment by ShannonLCapper** [comment]
Any update on this issue? This has been a big problem for us in terms of telling the user what's wrong when an Apollo request fails ("You don't have internet" vs "We got some specific error from the backend that we can tell you about")

**Comment by MrDoomBringer** [comment]
I believe this issue is directly related to #9870, so I plan to close this as a duplicate to try and keep discussion in a single place. If you think this issue is unrelated, please let me know and we can keep this open. Thanks a ton :)
