### ISSUE TITLE
Cache memory does not get update data.

### ISSUE THREAD

**Issue by alakdam07** [apollographql/apollo-client#8474]
I have a problem with updating cache data. I have made one condition that when user will signIn or SignUp then they can purchase the product. I made one order tab navigator where user can see their order history and also the latest order. The problem is my order history does not get the latest data, as a result when user come to the orders tab screen then they can't see the latest order. When I made scroll to top the screen then my useEffect trigger then I can get the latest order. 

For fixing this issue, I implemented  [refetchQueries](https://www.apollographql.com/docs/react/data/mutations/). When user will make create an order then it will refetchQueries the orderHistory query. I made `fetchPolicy: 'network-only'` and `nextFetchPolicy: 'network-only',`. In memory `cache` I tried to cache overwrite existing data with income data but my cache results showing the results other way. Here is image of my console.
<img width="722" alt="Screenshot 2021-07-09 at 15 08 09" src="https://user-images.githubusercontent.com/47625626/125075584-80dccd80-e0c7-11eb-93bb-a70581beb0fe.png">
.  

As a result I don't see the updated data and still showing old data. Idk is it bug or not.

**When I come order history screen and scroll to top the screen useEffect trigger then my console  look like this**

<img width="717" alt="Screenshot 2021-07-09 at 15 20 54" src="https://user-images.githubusercontent.com/47625626/125077003-483df380-e0c9-11eb-8491-b949003d64cb.png">

**This is my create order mutation**

    export const OrderCreate = gql`
      mutation CreateOrder($order: OrderInput) {
        createOrder(order: $order) {
          id
          createdAt
        }
      }
    `;

**This my order history query**

    export const GetOrderHistory = gql`
      query GetOrderHistory($brand: Brand) {
        userOrders(brand: $brand) {
          id
          createdAt
          customer {
            firstName
            lastName
          }
          storeName
          paymentMethod
          modifiedAt
          orderNumber
          orderStatus
          totalCost
          userId
        }
      }
    `;

**This is my cache settings** 

```
export const cache: InMemoryCache = new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        userOrders: {
          merge(existing, incoming) {
          console.log('cache existing', existing); 
            console.log('cache incoming', incoming);
            //return incoming
          },
        },
      },
    },
  },
});
```

**In react component I creating an order and in here I am using the [refetchQueries](https://www.apollographql.com/docs/react/data/mutations/).**

 ```
 import GetOrderHistoryDocument from './query';
  const [createOrder, { loading}] = useMutation(
    {
      onCompleted: () => {
         return ...
      },
      onError: (error) => {
      return error
      },
      refetchQueries: () => [
        {
          query: GetOrderHistoryDocument,
          variables: {
            brand: 'h&m'
          },
        },
      ],
    },
  );
  
```

**This is the React component where I want display my order status with latest order**

    const useOrderHistory = () => {
      const isLoggedIn = useReactiveVar(isLoggedInVar); 
      const [loading, setLoading] = useState(false);
      const [
        getOrderHistory,
        { data: { userOrders = [] } = {}, error, refetch },
      ] = useGetOrderHistoryLazyQuery({
        variables: { brand: 'h&m' },
         notifyOnNetworkStatusChange: true,
       fetchPolicy: 'network-only',
        nextFetchPolicy: 'network-only',
      });
    
      const fetchOrderHistory = useCallback(() => {

        getOrderHistory();
      }, [getOrderHistory]);
    
      useEffect(() => {
        if (isLoggedIn) {
          fetchOrderHistory();
        }
      }, [isLoggedIn, fetchOrderHistory]);
    
      return {
        isLoggedIn,
        loading,
        userOrders,
        error,
        fetchOrderHistory,
      };
    };

export default useOrderHistory;

**Comment by benjamn** [comment]
@alakdam07 Could you try putting these snippets of code into a runnable [reproduction](https://github.com/apollographql/react-apollo-error-template/)? In the meantime, there's always a chance the latest beta release (`npm i @apollo/client@beta`) may fix some things, so I would give that a try too.

**Comment by alakdam07** [comment]
Hi Benjamn, 
 
Our company is currently using `"@apollo/client": "^3.3.19",`. I can't update our package without consulting with them. It will take time. I am literally new in Apollo client, some how I feel like I am making some minor mistake that's why my cache is doing wrong behaviour.
