### ISSUE TITLE
Is the typing on MutationUpdaterFn correct?

### ISSUE THREAD

**Issue by dphrag** [apollographql/apollo-client#8506]
In `node_modules\@apollo\client\core\watchQueryOptions.d.ts` the MutationUpdaterFn is defined as

`export declare type MutationUpdaterFn<T = {
    [key: string]: any;
}> = (cache: ApolloCache<T>, mutationResult: FetchResult<T>) => void;`

The generic T type gets passed into ApolloCache, however this cache object doesn't have anything to do with the fetch result. To me this looks wrong, and ends up describing parts of the ApolloCache incorrectly.

**Comment by benjamn** [comment]
@dphrag You're right about this! We've rewritten these types in the upcoming Apollo Client v3.4 release (see #7902), and the `MutationUpdaterFunction` type now looks like [this](https://github.com/apollographql/apollo-client/blob/e359e973cb938a719ec3468135ac994b355ea774/src/core/types.ts#L154-L166):
```ts
export type MutationUpdaterFunction<
  TData,
  TVariables,
  TContext,
  TCache extends ApolloCache<any>
> = (
  cache: TCache,
  result: Omit<FetchResult<TData>, 'context'>,
  options: {
    context?: TContext,
    variables?: TVariables,
  },
) => void;
```
If you have a chance, try updating with `npm i @apollo/client@beta`. We're in the Release Candidate phase of testing, so the prerelease versions should be pretty stable by now.

**Comment by dphrag** [comment]
Thanks!! I was worried I had gone mad, typing can be confusing :P
