### ISSUE TITLE
Apollo Client on server side (nodejs) cache policies don't work

### ISSUE THREAD

**Issue by vany0114** [apollographql/apollo-client#8507]
Hi guys, I'm using Apollo Client on a nodejs server and it works great, however when it comes to cache it does not work as expected, it always caches the requests even though I'm using `no-cache` or `network-only`, any ideas?

Thanks in advance.

**Comment by benjamn** [comment]
@vany0114 In case this is helpful, the difference between `no-cache` and `network-only` is that `no-cache` does not write the network results to the cache, whereas `network-only` does (it just doesn't consult the cache before making a network request).

**Comment by vany0114** [comment]
@benjamn yep I noticed that in the docs, but the thing is that the client is always caching the request, so the first time it hits the server but for subsequent requests, it always gets the response from the cache even when I explicitly instruct it to not do so (using either `no-cache` or `network-only`), so do you know what I'm missing?

This is how I'm creating the apollo client instance:
```

export const graphqlClient = (uri: string): ApolloClient<NormalizedCacheObject> => {
  return new ApolloClient({
    link: ApolloLink.from([
      onError(({ graphQLErrors, networkError }) => {
        if (graphQLErrors)
          graphQLErrors.forEach(({ message, locations, path }) =>
            telemetryClient.trackException(
              new Error(
                `[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`,
              ),
            ),
          );
        if (networkError) telemetryClient.trackException(networkError);
        telemetryClient.flush();
      }),
      new HttpLink({
        uri,
        credentials: 'same-origin',
        fetch: fetch,
      }),
    ]),
    cache: new InMemoryCache(),
  });
};

```

**Comment by benjamn** [comment]
Are you creating a new `ApolloClient` instance for each request? That's what we recommend, to avoid returning stale cached data from the server, and to avoid leaking data between requests made by different clients.

**Comment by vany0114** [comment]
I'll try creating a new instance per request and I'll let you know, thanks!

**Comment by vany0114** [comment]
@benjamn I was reviewing and actually I do create a new instance per request 🤔

**Comment by hwillson** [comment]
@vany0114 a few questions:

1. Which version of Apollo Client are you using?
2. How are you setting `no-cache` - can you share the code that does this?
3. Regarding the code you've shared that shows your `ApolloClient` instantiation; is that running server side or client side? I'm guessing server side since I don't see any cache rehydration happening, but I wanted to double check as I don't see [`ssrMode`](https://www.apollographql.com/docs/react/api/core/ApolloClient/#ssrmode) being referenced.

**Comment by vany0114** [comment]
Hi @hwillson 

1. I'm using "@apollo/client": "^3.3.16"
2. This is how my query looks lie:
```
const graphqlResponse = await graphqlClient(myUrl).query({
      query: gql`
        query myQuery($foo: String!) {
          bar(id: $foo) {
            someField
          }
        }
      `,
      fetchPolicy: 'network-only', // or 'no-cache'
      variables: {
        foo: '123',
      },
    });
```
3. Correct, I'm using `ApolloClient` from server-side in the backend as my client to consume my API gateway.

**Comment by hwillson** [comment]
Thanks @vany0114 - any chance you can provide a small runnable reproduction?

**Comment by vany0114** [comment]
Sorry for the delay guys, I was working on the runnable reproduction project and I realized that actually, the client is working as expected, the issue was on my apollo server implementation. Sorry for the inconvenience.

**Comment by benjamn** [comment]
No worries, and thanks for following up @vany0114!
