### ISSUE TITLE
Invariant Violation: 12

### ISSUE THREAD

**Issue by aakashbacancy** [apollographql/apollo-client#8515]
I'm encountering an `Invariant Violation: Invariant Violation: 12` error and the console is suggesting to check out `https://github.com/apollographql/invariant-packages`. Didn't help me much.

I tried to find out the solution on the above link and on the internet and also ran `grep -r InvariantError node_modules/**/bundle.cjs.js ` on my system but I can not find this error.

I'm kinda stuck because every new apollo client version has different Invariant violation errors defined with tagging numbers and I'm not sure which error exactly is this? Also, how can I generate `invariantErrorCodes.js` for my version like this? https://github.com/apollographql/apollo-client/pull/6665

**Versions:** 
 "apollo-client": "2.6.10"

Thanks!

**Comment by benjamn** [comment]
@aakashbacancy The instructions at https://github.com/apollographql/invariant-packages only apply to versions of Apollo Client that include #6665 (`@apollo/client@3.1.0` and later), and we are not planning to port those changes back to `apollo-client@2.6.x` (note the change in package names from `apollo-client` to `@apollo/client`). Please consider [updating to AC3](https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/) when you have time!

However, it's still relatively easy to track down these error codes, once you know the trick(s). In this case, I installed your version of `apollo-client` with `npm i apollo-client@2.6.10` and then `grep`ed for `12`:
```
% grep -r 12 node_modules/apollo-client | head -n 5
node_modules/apollo-client/bundle.umd.js:      process.env.NODE_ENV === "production" ? (0, _tsInvariant.invariant)(options.query, 12) : (0, _tsInvariant.invariant)(options.query, 'query option is required. You must specify your GraphQL document ' + 'in the query option.');
node_modules/apollo-client/bundle.cjs.js:    process.env.NODE_ENV === "production" ? (0, _tsInvariant.invariant)(options.query, 12) : (0, _tsInvariant.invariant)(options.query, 'query option is required. You must specify your GraphQL document ' + 'in the query option.');
node_modules/apollo-client/package.json:  "_integrity": "sha512-jiPlMTN6/5CjZpJOkGeUV0mb4zxx33uXWdj/xQCfAMkuNAC3HN7CvYDyMHHEzmcQ5GV12LszWoQ/VlxET24CtA==",
node_modules/apollo-client/package.json:    "graphql": "^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0"
node_modules/apollo-client/bundle.esm.js:        process.env.NODE_ENV === "production" ? invariant(options.query, 12) : invariant(options.query, 'query option is required. You must specify your GraphQL document ' +
```
While there are some false positives here, all the `invariant`-related lines point to this code:
https://github.com/apollographql/apollo-client/blob/74e1f0045a24ae1a6d509425ad6fe805ad9e1571/packages/apollo-client/src/core/QueryManager.ts#L748-L753

Are you calling `client.query(options)` somewhere without including `options.query`?

**Comment by aakashbacancy** [comment]
@benjamn Thanks for a quick reply. I figured it out that when you send `undefined` in the query field, it throws the above error. 

Actually, It was a typo issue, and because of that, I imported a query that was never defined.

Thanks!
