### ISSUE TITLE
Fetch data from cross platform 

### ISSUE THREAD

**Issue by alakdam07** [apollographql/apollo-client#8517]
I am trying make one E-commerce mobile app. From my app user can make an order. I have bottom tab navigator name `Order History`, where user can see the order history with latest order. When I query my Graphql, I made fetch policies: ` fetchPolicy: 'network-only,` and  `nextFetchPolicy: 'cache-first`. From  `Order History` screen I can see my all orders and with latest order. Now I am  made an order from my web app but it does not update my mobile app's `Order History` screen. I want to see the latest order which I made from web app in my mobile app's `Order History` screen. I don't know which is the most efficient way to do that. I don't want to use the `pollInterval` because I found it's not efficient. Is [apollo-client's subscription](https://www.apollographql.com/docs/react/data/subscriptions/#usesubscription-api-reference) efficient for my case?

**Comment by hwillson** [comment]
@alakdam07 questions like this are better asked on our forums: https://community.apollographql.com
