### ISSUE TITLE
UseQuery is executing HTTP multiple times

### ISSUE THREAD

**Issue by JakubKana** [apollographql/apollo-client#8518]
**Prerequisities**
When using useQuery with options Fetch-Policy: "network-only"

**Intended outcome:**
One network request for fetch policy "network-only"

**Actual outcome:**
Module: useBaseQuery.ts within apollo-client. I downloaded code and I am running this library next to my project so I can log into it and make changes. What I am reporting here is in unchanged code so it is as I would import library from node_modules.

When I make request with useQuery hook. I end up with two network requests based on research within library with my colleague we figured out that following is happening.

When the hook is executed for the first time the useDeepMemo hook executes the function and queryData.execute() is called. Then handler function onNewData() gets called which updates the tick + 1 through call of forceUpdate(). However updating the tick also retriggers the useDeepMemo as the tick is part of the dependency object. This leads to repeated call of queryData.execute() (and possible invocation of another HTTP request). This time the handler function onNewData() is not called, tick is not updated and the result data of the query is returned only once by useQuery hook.

Console
![image](https://user-images.githubusercontent.com/6625593/126482823-c7c44cd0-e93f-42a0-a564-28b455d31488.png)

Network
![image](https://user-images.githubusercontent.com/6625593/126483176-61179543-25fd-40a9-aca7-bb245e89cf9e.png)

**How to reproduce the issue:**
Call hook useQuery with fetchPolicy: "network-only"

**Versions**
 System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\.......\client\node_modules\.bin\yarn.CMD
    npm: 6.14.13 - C:\.......\client\node_modules\.bin\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.71)
  npmPackages:
    @apollo/client: 3.3.2 => 3.3.2
    apollo: 2.31.0 => 2.31.0

**Comment by hwillson** [comment]
Thanks @JakubKana - any chance you could share a small runnable reproduction that shows this happening?

**Comment by JakubKana** [comment]
> Thanks @JakubKana - any chance you could share a small runnable reproduction that shows this happening?

I dont know if this helps but my code looks like this. 

```
const { loading, data, error } = useQuery<Query, QueryVariables>(
   QUERY, {
      variables: {
          id,
          clientId,
          productId
      },
      fetchPolicy: 'network-only'
   });
```

**Comment by gbenga504** [comment]
We have also noticed this in our apps; the same issue with 'network-only' fetch policy. Apparently, we tried downgrading but this is an issue with all the minor versions of the apollo client library since 3.0.0

**Comment by mohammadfarooqi** [comment]
I agree, i am experiencing something similar issue. 

when the fetchPolicy is the default one, then the request is duplicated and "data" is left undefined.

However, if I change the fetchPolicy to no-cache, then it makes 1 call and the data comes through.

Please advise.

Thank

**Comment by JakubKana** [comment]
> I agree, i am experiencing something similar issue.
> 
> when the fetchPolicy is the default one, then the request is duplicated and "data" is left undefined.
> 
> However, if I change the fetchPolicy to no-cache, then it makes 1 call and the data comes through.
> 
> Please advise.
> 
> Thank

I used it as a temporary solution thanks for the hint.

**Comment by JakubKana** [comment]
Do you need more code examples I noticed there is label that this needs reproduction. @hwillson

**Comment by hwillson** [comment]
@JakubKana yes, a runnable reproduction would be super helpful. Thanks!

**Comment by JakubKana** [comment]
> @JakubKana yes, a runnable reproduction would be super helpful. Thanks!

And how should I simulate backend and frontend? Like is there any playground that I can create? Use any useQuery you have with described settings and you have your error.

**Comment by hwillson** [comment]
@JakubKana see: https://github.com/apollographql/react-apollo-error-template

**Comment by JakubKana** [comment]
@hwillson thank you I will prepare it ASAP.

**Comment by JakubKana** [comment]
@hwillson Hi, unfortunately I could not reproduce an error in provided template. I prepared query (in FC) to call our backend but no duplicate queries occured. 

What could cause such an error do you have any ideas?

**Comment by bignimbus** [comment]
Hi all, thanks for the discussion here.  It's been a while but I'm doing some housekeeping and thought I'd see if anyone was able to produce a repo or codesandbox that captures the issue here.  Let us know!
