### ISSUE TITLE
keyArgs: false is not working for pagination

### ISSUE THREAD

**Issue by tar-aldev** [apollographql/apollo-client#8519]
I am trying to create pagination with apollo.
I have a Page component with the following query
```
export const HOME_PAGE_QUERY = gql`
  query HomePageQuery($count: Int!, $after: String) {
    viewer {
      id
      ...MainUserInfoFragment
      followers(first: $count, after: $after) {
        ...FollowersListFragment
      }
    }
  }
  ${MAIN_USER_INFO_FRAGMENT}
  ${FOLLOWERS_LIST_FRAGMENT}
`;
```
As you may see I have a `followers` subfield with pagination;
FollowersListFragment looks like this
```
fragment FollowersListFragment on FollowerConnection {
    totalCount
    pageInfo {
      startCursor
      endCursor
      hasNextPage
    }
    edges {
      cursor
      node {
        id
        createdAt
        ...MainUserInfoFragment
      }
    }
  }
  ${MAIN_USER_INFO_FRAGMENT}
```

Acording to docs, I should also set a merge function, so here are my Type policies
```
typePolicies: {
      FollowerConnection: { // this is the type of list
        fields: {
          edges: { // these are followers items which I want to merge
            keyArgs: false,
            merge(existing = [], incoming) {
              return [...existing, ...incoming];
            }
          }
        }
      }
    }
```
**Intended outcome:**

merge function should be called and values should be merged.
**Actual outcome:**

The merge function is called and `existing` values are `undefined` for the first time;
For the second time `existing` values array is the same as `incoming` values array;
Next `existing` array is doubled (meaning each object from previous array is presented two times)

The actual UI is not updated.

It happens unless I edit my HomePageQuery and add `@connection` directive.
```
query HomePageQuery($count: Int!, $after: String) {
    viewer {
      id
      ...MainUserInfoFragment
      followers(first: $count, after: $after) @connection(key: "followers")  {
        ...FollowersListFragment
      }
    }
  }
  ${MAIN_USER_INFO_FRAGMENT}
  ${FOLLOWERS_LIST_FRAGMENT}
```

ut according to your docs, @connection and keyArgs are interchangeable. Am doing something wrong?
**How to reproduce the issue:**

Use this repo
https://github.com/tar-aldev/trying-relay/tree/apollo-react-router-dom
Get github token;
create .env.development file and put it there as **REACT_APP_GITHUB_AUTH_TOKEN=<token>**
Go to HomePage.tsx to see the query;

run `yarn generate-typedefs:watch` in one terminal and `yarn start` in another one;
**Versions**

System:
    OS: macOS 11.2.3
  Binaries:
    Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
    Yarn: 1.22.10 - ~/projects/pet/relay-github-app/node_modules/.bin/yarn
    npm: 7.19.1 - ~/.nvm/versions/node/v14.15.5/bin/npm
  Browsers:
    Chrome: 91.0.4472.164
    Firefox: 86.0
    Safari: 14.0.3
  npmPackages:
    @apollo/client: ^3.3.21 => 3.3.21 
    apollo: ^2.33.4 => 2.33.4

**Comment by dylanwulf** [comment]
It's not working because you're passing arguments into the `followers` field, but you put the policy on the `edges` field which has no arguments.
Should probably look something like this (replace `ViewerType` which whatever type `viewer` returns)
```
typePolicies: {
      ViewerType: {
        fields: {
          followers: { // these are followers items which I want to merge
            keyArgs: false,
            merge(existing = [], incoming) {
              // do your merging here
            }
          }
        }
      }
    }
```

**Comment by dylanwulf** [comment]
Or you could try using the prebuilt relay pagination policy: https://www.apollographql.com/docs/react/pagination/cursor-based/#relay-style-cursor-pagination

**Comment by tar-aldev** [comment]
> It's not working because you're passing arguments into the `followers` field, but you put the policy on the `edges` field which has no arguments.
> Should probably look something like this (replace `ViewerType` with whatever type `viewer` returns)
> 
> ```
> typePolicies: {
>       ViewerType: {
>         fields: {
>           followers: { // these are followers items which I want to merge
>             keyArgs: false,
>            // merge, read, etc
>           }
>         }
>       }
>     }
> ```

I see your point. But the problem is that `edges` are just an array, while followers has more fields and more complex shape, meaning it will be harder to merge it. I will try if `relayStylePagination` could deal with it. THanks

**Comment by tar-aldev** [comment]
@dylanwulf Thank you so much for the help. I tried it and it worked. You saved my day)
 So, in case someone would find this issue, here is the fix.
```
// the root query
query HomePageQuery($count: Int!, $after: String) {
    viewer {
      id
      ...MainUserInfoFragment
      followers(first: $count, after: $after) {
        ...FollowersListFragment
      }
    }
  }

// typePolicies for followers field
typePolicies: {
      // viewer in query is of type User
      User: {
        fields: {
          followers: relayStylePagination()
        }
      }
}
```
