### ISSUE TITLE
Possibly null `currentObservable` type errors are ignored

### ISSUE THREAD

**Issue by FezVrasta** [apollographql/apollo-client#8523]
**Intended outcome:**

I'm trying to call `fetchMore` in an async callback.

**Actual outcome:**

```
Cannot read property `fetchMore` of undefined
```

![image](https://user-images.githubusercontent.com/5382443/126610632-7c284ac3-28a8-45d3-a59a-ce562ea83467.png)

**How to reproduce the issue:**

Not clear, it is sporadic. But the problem is that you are explicitly ignoring the TypeScript errors that warn you `this.currentObservable` could be undefined.

Relevant source code, note the `!.` usage:
https://github.com/apollographql/apollo-client/blob/cbcf951256b22553bdb065dfa0d32c0a4ca804d3/src/react/data/QueryData.ts#L494

**Versions**

Latest

**Comment by brainkim** [comment]
Fixed in https://github.com/apollographql/apollo-client/pull/7980. Thanks for the report, and sorry for your troubles!
