### ISSUE TITLE
Updating cache when return type is boolean or some other Scalar

### ISSUE THREAD

**Issue by nenadfilipovic** [apollographql/apollo-client#8542]
How should I handle updating cache when my mutation returns number of affected rows or true/false? Of course I can use refetchQueries but is there way to do it with update function? Thanks.

Need help or want to talk all things Apollo Client? Issues here are reserved for bugs, but one of the following resources should help:

* Apollo GraphQL community forums: https://community.apollographql.com
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests

**Comment by benjamn** [comment]
@nenadfilipovic We have some updated documentation about mutations and refetching coming for Apollo Client v3.4, which you can preview [here](https://deploy-preview-7399--apollo-client-docs.netlify.app/docs/react/data/mutations/#updating-the-cache-directly) in the meantime. You might also be interested in our docs about the new [`client.refetchQueries`](https://deploy-preview-7399--apollo-client-docs.netlify.app/docs/react/data/refetching/) API (which is similar to the `refetchQueries` and `update` options for a mutation, but doesn't require a mutation).

In general, it's possible your mutation result simply doesn't contain enough information to simulate the full effects of the mutation locally, so refetching is the best/only option. However, you can use the `update` function together with `onQueryUpdated` to figure out which queries were affected by cache operations performed in the `update` function, which allows you to refetch fewer queries in many cases.

**Comment by nenadfilipovic** [comment]
I will read all that, thanks :)
