### ISSUE TITLE
optimisticResponse loses data queried inside data

### ISSUE THREAD

**Issue by coolcomfort** [apollographql/apollo-client#8551]
**Intended outcome:**
I am building a nested comment system, and so far have been able to accomplish everything with refetchQueries. I tried to switchover to optimisticResponse and I noticed that anytime I made a comment, optimisticResponse would have an effect on my other comments. My other comments contain GQL queries which fetch comments to a comment. Normally, when I use refetch, no issue takes place. When I use optimisticResponse, the data fetched for these queries is instantly lost upon firing.

**Actual outcome:**
Here is an example of how my comments look
![image](https://user-images.githubusercontent.com/38641316/127148340-80ca6554-f170-40d6-9cdd-ecfa29bcd9c4.png)

Here is what happens when I post the comment
![image](https://user-images.githubusercontent.com/38641316/127148374-9be3612f-0a40-43a3-945d-383a445f7f2c.png)

All the data fetched within other comments are lost. This issue only happens with optimisticResponse. As noted above, I have used refetchQueries, cache.writeFragment, etc, and none have an affect with the queries inside my other comments. 

**How to reproduce the issue:**
Map over a todo list where you can add to the todo list at anytime. Create a sub query inside every todo list that grabs some type of data. Then implement optimisticResponse for when adding to the todo list, and notice how the sub queries are all missing upon adding to the todo list. 

**Versions**

  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.55)
  npmPackages:
    @apollo/client: ^3.4.0-rc.20 => 3.4.0-rc.20
    @apollo/link-error: ^2.0.0-beta.3 => 2.0.0-beta.3
    @apollo/react-ssr: ^4.0.0 => 4.0.0
    apollo-upload-client: ^16.0.0 => 16.0.0
    next-with-apollo: ^5.2.1 => 5.2.1

**Comment by coolcomfort** [comment]
I have found a way around this, but it is not ideal in my opinion. I have been storing all sub comments in a context, and then fetching the data based on the context instead of the fetched data directly. While this works, I try my best to not resort to using context, even though it is performing really well in this scenario. Another important thing to point out when using context, is the difficulty in getting the data from the sub comments into the context. You must use useEffect and so that it isn't constantly repopulating. Most times, people use some type of button or input box to trigger a context change. In this example, we must do it upon page load, and the only way that is possible is through useEffect. While I think this is a perfect use case for useEffect, I would prefer to do it the first way, without resorting to storing it through context. **I am not marking this resolved because I do believe optimisticResponse should function similarly to fetchQueries, without disturbing sub queries inside components.** Please let me know what you think as I welcome an open discussion.

**Comment by koenpunt** [comment]
I think with the latest version of the library this should be fixed.

**Comment by coolcomfort** [comment]
@koenpunt I haven't opened up my apollo code in several months but would be excited to attempt to upgrade + check on it in a few weeks. Is there any footnotes I can read on the latest update? I am relatively new to the coding scene, not quite sure where this information would be at.
