### ISSUE TITLE
Avoiding unnecessary renders on lists after one element updates

### ISSUE THREAD

**Issue by DrWorkhard** [apollographql/apollo-client#8556]
Dear community,

First thanks for the great library, I really enjoy working with apollo.

I currently encountered the following performance bottleneck in my app:
1. I use useQuery to fetch a list of elements and render them
2. After a click on one of the elements, there is a change in state of this element

Doing this causes a rerender of the whole list. The only workaround I came up with was a second query to fetch the individual list elements. But this this would initially cause querys to the server for each element of the list, something I would like to avoid.

Is there another way I am missing?

Best and thank you
Seb

**Comment by benjamn** [comment]
@DrWorkhard It sounds like you're looking for something like the new `useFragment` hook that we're planning for Apollo Client v3.5: https://github.com/apollographql/apollo-client/issues/8236#issuecomment-857178202

I'll be opening a draft PR for this work soon, but if you're really interested in the details, here's my working branch: https://github.com/apollographql/apollo-client/commits/wip-useFragment

**Comment by DrWorkhard** [comment]
Hi @benjamn awesome, this sounds exactly what I was looking for. So for rendering the list I would use useQuery with fetchpolicy standby and in the specific elements I would use the useFragment hook.

Looking forward to v3.5, thanks for the great work and swift response.
