### ISSUE TITLE
ApolloError: this.cache.batch is not a function

### ISSUE THREAD

**Issue by Temkit** [apollographql/apollo-client#8566]
Hi.

trying some auth mutation over the new released Apollo/client 3.4.1 and i have this error : 
```

ApolloError: this.cache.batch is not a function
    at new ApolloError (/var/task/node_modules/@apollo/client/errors/errors.cjs.js:35:28)
    at Object.error (/var/task/node_modules/@apollo/client/core/core.cjs.js:1073:90)
    at notifySubscription (/var/task/node_modules/zen-observable/lib/Observable.js:140:18)
    at onNotify (/var/task/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.error (/var/task/node_modules/zen-observable/lib/Observable.js:240:7)
    at /var/task/node_modules/@apollo/client/utilities/utilities.cjs.js:1015:40
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  graphQLErrors: [],
  clientErrors: [],
  networkError: TypeError: this.cache.batch is not a function
      at QueryManager.refetchQueries (/var/task/node_modules/@apollo/client/core/core.cjs.js:1601:24)
      at QueryManager.markMutationResult (/var/task/node_modules/@apollo/client/core/core.cjs.js:1136:18)
      at /var/task/node_modules/@apollo/client/core/core.cjs.js:1043:49
      at both (/var/task/node_modules/@apollo/client/utilities/utilities.cjs.js:1004:53)
      at /var/task/node_modules/@apollo/client/utilities/utilities.cjs.js:997:72
      at new Promise (<anonymous>)
      at Object.then (/var/task/node_modules/@apollo/client/utilities/utilities.cjs.js:997:24)
      at Object.next (/var/task/node_modules/@apollo/client/utilities/utilities.cjs.js:1005:49)
      at notifySubscription (/var/task/node_modules/zen-observable/lib/Observable.js:135:18)
      at onNotify (/var/task/node_modules/zen-observable/lib/Observable.js:179:3),
  extraInfo: undefined
}

```

**Comment by vnylbscr** [comment]
The same error on 3.3.13. Auth mutation working fine on Server but stuck on catch block.

**Comment by Temkit** [comment]
i had to go back to : 3.3.21 t make it work again. @vnylbscr  clear the cache and reinstall the 3.3.21 version.

**Comment by benjamn** [comment]
@Temkit The `batch` method is new in v3.4, but a stub implementation is provided by the `ApolloCache` base class [here](https://github.com/apollographql/apollo-client/blob/acf453f6c8f40ab853f4702b5025450e2b09091c/src/cache/core/cache.ts#L62), so it's surprising that `this.cache.batch` would be missing entirely.

Is there anything unusual about your cache setup? Are you using `InMemoryCache`? If so, how are you importing it?

**Comment by foxcode-designs** [comment]
I have the same error on our dev server with both 3.3.21 as 3.4.1. Locally everything runs fine but on the dev server when I execute the mutation, it goes straight after in the catch function (even though I get a 200 response with correct data) and outputs 'this.cache.batch is not a function'. I'm using default InMemoryCache which I cleared too.

**Comment by benjamn** [comment]
I'm going to keep asking everyone the same questions:

1. Is there anything unusual about your cache setup?
2. Are you using `InMemoryCache`?
3. If so, how are you importing it?

In addition to answering these questions, if anyone can provide a runnable [reproduction](https://github.com/apollographql/react-apollo-error-template/), that would be much appreciated!

**Comment by mfurniss** [comment]
@benjamn I am setting up my client like this...

`export const apolloClient = new ApolloClient({
  link: ApolloLink.from([retryLink, authLink, errorLink, splitLink]),
  cache: new InMemoryCache({ addTypename: true }),
});`

**Comment by carelulu-igor** [comment]
I do something similar to @mfurniss.

```js
import { ApolloClient } from '@apollo/client';
import { InMemoryCache, IntrospectionFragmentMatcher } from 'apollo-cache-inmemory';
import { createHttpLink } from 'apollo-link-http';

const fragmentMatcher = new IntrospectionFragmentMatcher({
  introspectionQueryResultData: {
    __schema: {
      types: [{
        kind: 'INTERFACE',
        name: 'xyz',
        possibleTypes: [
          { name: 'abc' },
          { name: 'def' },
        ],
      }],
    },
  },
});

const memoryCache = new InMemoryCache({ fragmentMatcher }).restore(cache);

state.client = new ApolloClient({
  ssrMode,
  cache: memoryCache,
  link: createHttpLink({
    uri: GRAPHQL_URL,
    fetch: customFetch(ssrMode, ip, memoryCache, state),
  }),
  errorPolicy: 'all',
  shouldBatch: !ssrMode,
  connectToDevTools: true,
});
```

**Comment by benjamn** [comment]
@carelulu-igor Thank you for including your imports, especially the import of `InMemoryCache`.

The reason this code is not using the latest implementation of `InMemoryCache` is that it's still importing `InMemoryCache` from the AC2 `apollo-cache-inmemory` npm package (last published more than a year ago!). You can/should import `InMemoryCache` from `@apollo/client` instead now. The older package still exists for folks also using the older `apollo-client` package, but you definitely should not be mixing `@apollo/client` and `apollo-cache-inmemory` together.

The good news: you're about to experience a ton of improvements to `InMemoryCache` all at once!

The realistic news: some of those changes will be [breaking](https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/#cache-improvements). For example, the `IntrospectionFragmentMatcher` no longer exists. Fortunately, the new way of providing `possibleTypes` is much simpler:
```ts
const memoryCache = new InMemoryCache({
  possibleTypes: {
    xyz: ["abc", "def"],
  },
}).restore(cache);
```

While you're at it, I would also suggest you stop using `apollo-link-http` and import `createHttpLink` this way instead:
```ts
import { createHttpLink } from "@apollo/client/link/http"
```

These won't be the only changes you'll have to contend with as you update, but I hope you'll find the `InMemoryCache`-related parts of the [AC3 migration guide](https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/) useful.

@mfurniss Does this explanation of @carelulu-igor's problem explain what's up in your case? I can't really tell if they're the same problem from the code you provided above.

**Comment by nuclearspike** [comment]
Thank you so much the answer @benjamn! His problem was almost identical to mine and your clear answers solved everything. Thanks!
