### ISSUE TITLE
Apollo client - incorrect response

### ISSUE THREAD

**Issue by Lukas249** [apollographql/apollo-client#8569]
Hi 
It's response if i make query to apollo server with fetch es6
![Zrzut ekranu3](https://user-images.githubusercontent.com/69908232/127783210-45790b10-312c-4ecc-9b86-bb9e9705c675.png)
That's from apollo client
![Zrzut ekranu2](https://user-images.githubusercontent.com/69908232/127783227-54c0815a-6b67-4f87-bea2-c3dae49b8f11.png)
And that's from apollo  server playground
![Zrzut ekranu1](https://user-images.githubusercontent.com/69908232/127783238-75cf0f04-004e-430b-86c1-254bb9208a6e.png)
Anyone know what can cause this?

**Comment by dylanwulf** [comment]
It's because both objects have the same `id` value

**Comment by Lukas249** [comment]
I added fetchpolicy: 'no-cache' to the query and everything works.

**Comment by dylanwulf** [comment]
@Lukas249 another option would be to configure the cache to not normalize that object: https://www.apollographql.com/docs/react/caching/cache-configuration/#disabling-normalization
