### ISSUE TITLE
MutationTuple now requires 4 arguments instead of 2

### ISSUE THREAD

**Issue by evenfrost** [apollographql/apollo-client#8572]
After upgrading to `@apollo/client` from `v3.3.x` to `v3.4.1` our codebase broke as `MutationTuple` interface now requires 4 type arguments instead of 2. `MutationTuple` is used to explicitly type our mutation functions.

Is there a reason these arguments are not made optional? I'd consider it a breaking change then, because it, literally, breaks the code.

**Comment by benjamn** [comment]
@evenfrost You're right that we could/should have provided default type parameters (in #7902). Fix incoming: #8573

**Comment by benjamn** [comment]
@evenfrost Let us know if `@apollo/client@3.4.2` solves this problem for you (or not), whenever you have a chance?

**Comment by evenfrost** [comment]
Looks good now, thanks.
