### ISSUE TITLE
Merge legacy HOC and render prop tests into modern test suite

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-client#8580]
Continues the work started in https://github.com/apollographql/apollo-client/pull/8543.

**Comment by brainkim** [comment]
Relevant history:
- https://github.com/apollographql/apollo-client/pull/6558

**Comment by alessbell** [comment]
These deprecated APIs will be removed in a future version and I don't believe the team has interest in further investing in or rewriting related tests. Closing as won't do.
