### ISSUE TITLE
Breaking change in apollo-client.cjs.js

### ISSUE THREAD

**Issue by davixyz** [apollographql/apollo-client#8592]
**Intended outcome:**

Have access to `ApolloProvider` exported from `apollo-client.cjs.js`

```
"version": "3.3.21"
```
yay provider
<img width="1423" alt="Screen Shot 2021-08-05 at 12 03 23 PM" src="https://user-images.githubusercontent.com/4756314/128406766-9928ca0f-9e67-44bc-9202-28716a555ec6.png">

**Actual outcome:**

`ApolloProvider` is no longer exported from `apollo-client.cjs.js`

```
 "version": "3.4.5",
```
no provider to be found :(
<img width="935" alt="Screen Shot 2021-08-05 at 12 10 08 PM" src="https://user-images.githubusercontent.com/4756314/128407430-6d7b868f-6bde-419e-be32-8f090e9a1582.png">

**How to reproduce the issue:**

update to latest version and try to access Provider from apollo-client.cjs

**Versions**

 "version": "3.4.5",

**Note**
For *reasons* we have to access Apollo through an entire CJS implementation; I realize that the provider is now in `react/react.cjs.js` but we were thinking that `apollo-client.cjs.js` would have the entire apollo client implementation in a single file.

**Comment by benjamn** [comment]
@davixyz Could you import `@apollo/client/main.cjs.js` instead, or do you really need one big bundle file?

The `apollo-client.cjs.js` file is a build artifact and not something we intended to be part of the public API, but I do see how changing what it exports could be a breaking change, and I'm open to restoring it in some form, if that's helpful to you (or if a lot of people have the same problem).

**Comment by davixyz** [comment]
We can adjust the imports as needed on our end; It's more of an issue in terms of NPM distributions; This might technically be a breaking change for all the clients consuming this file as the export changed and things were removed.

Maybe restoring it as the initial stable version was is the way to go for sake of correctness and calling it out as deprecated so maybe gets removed as distributable in following versions (But please do leave a single big bundle for us using some older CommonJS bundlers)

**Comment by benjamn** [comment]
@davixyz Please take a look at #8605 when you have a chance!

**Comment by aboveyunhai** [comment]
![image](https://user-images.githubusercontent.com/35160613/128574549-9f7b6a0c-18c3-4c7a-b108-8f3bc86d2741.png)

I encounter this problem when I upgrade from 3.4.4 to 3.4.5, 
I have to downgrade back to 3.4.4 as well as `discard changes` from `package-lock.json` then `npm i` to reinstall the deps,
but I am not sure if it relates to the OP.
