### ISSUE TITLE
[bug] Hooks aren't catching errors

### ISSUE THREAD

**Issue by d4nielhdz** [apollographql/apollo-client#8594]
**Intended outcome:**

When running a query/mutation from an Apollo hook, every error found will be caught and stored in the `error` attribute of the hook.

**Actual outcome:**

My app crashes and the error is shown in the browser. AFAIK this should never happen since errors are stored in the hook instead of thrown.

**How to reproduce the issue:**

I'm using a mutation hook generated with `graphql-codegen`. When triggering the mutation multiple times, the server returns an error and the app crashes.

![Screen Shot 2021-08-05 at 2 45 27 PM](https://user-images.githubusercontent.com/28610916/128411573-4764d19f-e524-4c31-b760-47b7afceb407.png)

**Versions**

```
  System:
    OS: macOS 11.1
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Firefox: 88.0
    Safari: 14.0.2
  npmPackages:
    @apollo/client: ^3.3.21 => 3.3.21
```

**Comment by benjamn** [comment]
@d4nielhdz Have you had a chance to try `@apollo/client@3.4.5` (the latest version)?

**Comment by d4nielhdz** [comment]
@benjamn thanks for the suggestion. Updated but no luck.

**Comment by d4nielhdz** [comment]
Solved by setting the `defaultOptions` attribute for `ApolloClient` to:

```
    defaultOptions: {
      watchQuery: {
        errorPolicy: "all",
      },
      query: {
        errorPolicy: "all",
      },
      mutate: {
        errorPolicy: "all",
      },
    },
```
