### ISSUE TITLE
useQuery with variable retrieved asynchronously 

### ISSUE THREAD

**Issue by eakl** [apollographql/apollo-client#8599]
How can I enforce the useQuery hook to be executed once the projectId variable is available?
`isAuthentificated` and `user` are retrieved via Context.

```javascript
export const useProjects = (projectId) => {
  const { isAuthentificated } = useAuth()

  const { data } = useQuery(
    GET_PROJECTS, {
      skip: !isAuthentificated,
      variables: {
        projectId
      }
    }
  )
  return data
}
```

The `projectId` is passed to the hook via the parent. The parent receive it from context

```javascript
const Parent = () => {
  const { user } = useAuth()
  const { projects } = useProjects(user.project._id)
  // ...
}
```

```bash
[GraphQL error]: Message: Variable "$projectId" of required type "ID!" was not provided., Location: [{"line":1,"column":26}], Path: undefined
```

**Comment by simplecommerce** [comment]
Try https://www.apollographql.com/docs/react/api/react/hooks/#skip maybe or you could do it using useLazyQuery https://www.apollographql.com/docs/react/api/react/hooks/#uselazyquery using useEffect or something similar.

**Comment by bignimbus** [comment]
Hi @eakl, thanks for your patience - I think @simplecommerce's suggestions are a great place to start.  I'll close this as resolved, let us know if you need more support 🙏🏻
