### ISSUE TITLE
Add the ability to manage client and server data together

### ISSUE THREAD

**Issue by stubailo** [apollographql/apollo-client#86]
As a special case of multiple endpoints, I think it would be really valuable to be able to use Apollo Client as a one-stop-shop for client data management.

This would be very similar to using Redux (since it is under the hood) but you would make a typed schema for your client-side data, declare relationships to server data, do client data changes via mutations, and be able to query client and server data in one GraphQL query.

I don't think this would be super hard to build, and sounds like kind of the holy grail of data management.

**Comment by marclar** [comment]
Yesss. This is what I was trying to say, @helfer

**Comment by JProgrammer** [comment]
Yes I think this will be really important so that we can have microservice style graphql servers responsible for one thing but then have app servers quering/mutating across multiple graphql servers/schemas.

It would be great to compose an app server by exposing schemas of one graphql server from another.

**Comment by stubailo** [comment]
I think this issue is about a different thing - it's more about having client-only data and server data being queried together. Perhaps you should post that somewhere else, like Apollo Server?

**Comment by stubailo** [comment]
@jbaxleyiii how do we mark an issue to not be closed? I think this one is the canonical issue for client-side data management.

**Comment by odero** [comment]
@stubailo Is there any update on this? Any light at the end of the tunnel?
