### ISSUE TITLE
Mocked query data unavailable after updating React state

### ISSUE THREAD

**Issue by jiri-matejka** [apollographql/apollo-client#8615]
**Intended outcome:**
I am trying to test a component with a mocked query. Intended outcome is to get the mocked data.

**Actual outcome:**
When I update React state, i get error in the query object: `ApolloError: Network error: No more mocked responses for the query` instead of mocked data.

**How to reproduce the issue:**
I created a Jest test for this. If needed I can create a codepen for it. I understand updating the state makes unneccesary rerendering, but our real component currently does this. However I think updating state should not interfere with using mocked queries.

```ts
import React, { useState } from 'react'
import { MockedProvider } from '@apollo/react-testing'
import { render } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import { useQuery } from '@apollo/react-hooks'
import gql from 'graphql-tag'

type myResult = {
  id: number
}

const query = gql`
  query myQuery($first: Int) {
    myResult(first: $first) {
      id
    }
  }
`

const mock = {
  request: {
    query: query,
    variables: { first: 10 }
  },
  result: {
    data: {
      myResult: {
        id: 42
      }
    }
  }
}

function MyComponent() {  
  const [value, setValue] = useState<number>(1)

  // ----------------------------------------------------------------
  // comment out this condition to make the test pass
  // ----------------------------------------------------------------
  if (value === 1) {
    console.log("Rerendering by setting value to 2")
    setValue(2)    
  }

  const myQuery = useQuery<{ myResult: myResult }>(query, {
    variables: {first: 10},    
    fetchPolicy: 'no-cache'
  })

  if (myQuery.error) {
    console.error(myQuery.error)
  }
   
  if (!myQuery.loading && !myQuery.error && myQuery.data) {
    return <p>Try to find {myQuery.data?.myResult.id} here</p>
  } else {
    return <></>
  }
}

test('mocked query should return result after updating state', async () => {
  const renderResult = render(
    <MemoryRouter>
      <MockedProvider mocks={[mock]}>
        <MyComponent />
      </MockedProvider>
    </MemoryRouter>
  )
  
  await renderResult.findByText('Try to find 42 here')
})
```

**Versions**
System:
    OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
  Binaries:
    Node: 15.11.0 - ~/.nvm/versions/node/v15.11.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v15.11.0/bin/yarn
    npm: 7.6.0 - ~/.nvm/versions/node/v15.11.0/bin/npm
  Browsers:
    Firefox: 90.0
  npmPackages:
    @apollo/client: 3.4.0 => 3.4.0 
    @apollo/react-hooks: ^3.1.5 => 3.1.5 
    @apollo/react-testing: ^3.1.4 => 3.1.4 
    apollo-absinthe-upload-link: ^1.5.0 => 1.5.0 
    apollo-cache-inmemory: ^1.6.6 => 1.6.6 
    apollo-client: ^2.6.10 => 2.6.10 
    apollo-link: ^1.2.14 => 1.2.14 
    apollo-link-error: ^1.1.13 => 1.1.13 
    apollo-link-http: ^1.5.17 => 1.5.17 
    apollo-phoenix-websocket: ^0.6.2 => 0.6.2 
    apollo-utilities: ^1.3.4 => 1.3.4 
    react-apollo: ^3.1.5 => 3.1.5

**Comment by jiri-matejka** [comment]
In a sandbox with latest package versions (https://codesandbox.io/s/apollo-mocked-data-issue-after-updating-react-state-ws30z?file=/src/MyComponent.tsx), the test is passing. Mocked query gives correct data even after state update.
So it must be something on our side, maybe old package versions or the like.

**Comment by benjamn** [comment]
@jiri-matejka The only thing that jumped out at me was that you probably should
```ts
import { useQuery } from "@apollo/client/react/hooks"
```
instead of using the older `@apollo/react-hooks` package.

Thanks for following up!
