### ISSUE TITLE
Check arguments to all public methods and provide useful error messages

### ISSUE THREAD

**Issue by helfer** [apollographql/apollo-client#862]
We don't do this right now, but we really should. It would make errors like #854 a lot easier to debug.

**Comment by tizmagik** [comment]
I wonder if there's a way to reuse the TS definitions to make these assertions? Also, I guess these checks should only happen in development (`NODE_ENV !== 'production'`) for performance reasons?

**Comment by helfer** [comment]
Let's keep this in mind for any future API we design.
