### ISSUE TITLE
Is this example on the website correct?

### ISSUE THREAD

**Issue by 1998feng** [apollographql/apollo-client#8634]
![image](https://user-images.githubusercontent.com/49889959/129160660-316908b0-d327-4ccc-923c-b0bf09966e43.png)
![image](https://user-images.githubusercontent.com/49889959/129158077-47b4a977-102c-46b6-baf9-e7aa2e532788.png)
```javascript
import React, { useState } from "react";
import { render } from "react-dom";

import ApolloClient from "apollo-boost";
import { ApolloProvider, useLazyQuery } from "@apollo/react-hooks";
import gql from "graphql-tag";

const client = new ApolloClient({
  uri: `https://71z1g.sse.codesandbox.io/`
});

const GET_DOG_PHOTO = gql`
  query Dog($breed: String!) {
    dog(breed: $breed) {
      id
      displayImage
    }
  }
`;

function DelayedQuery() {
  const [dog, setDog] = useState(null);
  const [getDog, { loading, data }] = useLazyQuery(GET_DOG_PHOTO);

  if (loading) return <p>Loading ...</p>;

  if (data && data.dog) {
    setDog(data.dog);
  }

  return (
    <div>
      {dog && <img src={dog.displayImage} />}
      <button onClick={() => getDog({ variables: { breed: 'bulldog' } })}>
        Click me!
      </button>
    </div>
  );
}

render(<ApolloProvider client={client}><DelayedQuery /></ApolloProvider>, document.getElementById("root"));

```

**Comment by benjamn** [comment]
@1998feng Are you maybe looking at an older version of the docs?

Here's [that section](https://www.apollographql.com/docs/react/data/queries/#executing-queries-manually) currently:

<img width="758" alt="Screen Shot 2021-08-12 at 9 51 36 AM" src="https://user-images.githubusercontent.com/5750/129208857-f253308a-e3ee-4f51-8833-3a21205f9696.png">

**Comment by MrDoomBringer** [comment]
It looks like the original section is from the [v2 version of our React docs](https://www.apollographql.com/docs/react/v2/data/queries#executing-queries-manually), which I believe we are no longer supporting - so I'll go ahead and close this issue. Thanks! :)
