### ISSUE TITLE
fetchMore + refetchQueries?

### ISSUE THREAD

**Issue by stephenbunch** [apollographql/apollo-client#8652]
I have a table with infinite scroll. I use `relayStylePagination` and use the `after` argument when calling `fetchMore` to fetch additional pages.

Suppose the user scrolls a bit and loads a few pages. They close their laptop for a few hours and reopen it. I want to write some code that refetches all active queries.

I tried:

```ts
client.refetchQueries({ include: 'active' });
```

But this only refetches the very first page. Is it possible to refetch all active pages?

I'm on `3.4.7`.

**Comment by benjamn** [comment]
@stephenbunch There's another shorthand for `include` that might be useful:
```ts
client.refetchQueries({ include: 'all' });
```
With `'all'` instead of `'active'`, queries with no active subscribers will be included.

[More examples of `client.refetchQueries` usage](https://www.apollographql.com/docs/react/data/refetching/#refetch-recipes).
