### ISSUE TITLE
useQuery with cache-only policy takes 1s longer than readQuery

### ISSUE THREAD

**Issue by cristobalbahe** [apollographql/apollo-client#8656]
Hello everyone!

I am having the following problem and I don't know if it's a bug or I am missing something.

I am querying my graphql API with useQuery (always same variables) within a component. At the beginning, it loads all the data and stores it in cache, which I can see in the Apollo Client developer tools. But when the component rerenders, I get immediate data from readquery, but useQuery, which has a nextFetchPolicy of cache-only returns first undefined and 1s later it returns the data. It's something like the following:
```
  const { data, loading, error } = useQuery(GET_HOME, {
      nextFetchPolicy: "cache-only", 
    });
    //This returns always undefined first and then data, with almost 1s of difference on subsequent renders.


  try {
      const cachedData = client.readQuery({
        query: GET_HOME
      });
      //This returns undefined on the first render and immediate data on subsequent renders. 
    } catch (e) {
      console.log(e);
    }
``` 

I don't understand this behaviour, since I thought that useQuery would get the data immediately from the cache, but it seems it does not.

Am i missing something? Does anyone else have this same problem?

**Comment by bignimbus** [comment]
Hi @cristobalbahe 👋🏻  thanks for opening this issue and for your patience!  I'm doing some housekeeping and wanted to see if you still needed support here.  Typically with inquiries like these the community can only offer educated guesses until we can look at a runnable reproduction scenario that captures the problem you're seeing.  We do have an [error template](https://github.com/apollographql/react-apollo-error-template/generate) that should get a lot of the boilerplate done for you.  If we don't hear from you after a while we'll close this issue, no worries either way.  Thanks a bunch 🙏🏻
