### ISSUE TITLE
refetchQueries does not update "loading" from query

### ISSUE THREAD

**Issue by dulfe** [apollographql/apollo-client#8671]
Setting ```refetchQueries``` in ```useMutation``` reloads the given query successfully, but the ```loading``` variable from that query does not get updated to ```true/false```, it stays as ```false```

Given the following:

```ts
const query = useQuery(GQL_QUERY);
const [mutation, { data: mutationData, loading: mutationLoading, error: mutationError }] = useMutation(GQL_MUTATION,
        {
            refetchQueries: [GQL_QUERY]
        });
```

On first load, ```query.loading``` is ```true``` and later changes to ```false``` after loading the data, that works great.

Later in the code, execute the mutation function ```mutation()```, after execution, GQL_QUERY gets reloaded and its results assigned to ```query.data```, but ```query.loading``` stays ```false``` thru the whole process.

That seems inconsistent.

**Comment by brainkim** [comment]
@dulfe `useQuery` doesn’t notify you if a query is refetched unless you use the option `notifyOnNetworkStatusChange`. So the line in your example would be
```ts
const query = useQuery(GQL_QUERY, {notifyOnNetworkStatusChange: true});
```

I know, it’s a mouthful. But that’s how you get notified about state changes after loading. Let me know if this isn’t satisfactory.

**Comment by dulfe** [comment]
@brainkim That worked, thank you!

But, that also means the component will re-render on all other network status changes (like ```setVariables``` or ```poll```), right?

Anyways, that worked and I can live with a few extras re-renders.

Thank you!

**Comment by brainkim** [comment]
> But, that also means the component will re-render on all other network status changes (like setVariables or poll), right?

Yes, that’s correct!
