### ISSUE TITLE
Apollo Client Merge Helper Function returning ref object but not incoming data

### ISSUE THREAD

**Issue by rjointer2** [apollographql/apollo-client#8691]
I'm trying get a new set data from a paginated-like API I created but I only receive the object with the ref property from the cache, but the data from the API. How can I return a array of the existing and incoming data?

This issue may stem from my lack of understanding the Apollo-Client Documentation or trying to use the merge helper function in a way not intended for. I have this repo's previous issues posted for reference but in implementation I haven't gotten the expected result.

![InMemoryCache Object set up](https://user-images.githubusercontent.com/63383211/130511534-77180895-33c4-45e6-99d9-02e09ecebd97.png)
![Console log's result](https://user-images.githubusercontent.com/63383211/130511598-7a47cf25-c092-4bc7-8a38-8be6dd6b2fc4.png);

![useQuery Hooks to get API Data](https://user-images.githubusercontent.com/63383211/130511660-843a1a1c-f936-4ccb-b89e-a399f29d04d3.png)

**Comment by benjamn** [comment]
Instead of `keyFields: ["start", "end"]`, I think you want `keyArgs: false` (note: `keyArgs` rather than `keyFields`), so fragments of data with different `start` and `end` arguments can be combined into a single list.

**Comment by bignimbus** [comment]
Hi all, I'm cleaning up some old issues. I'll close this as resolved for now but please feel free to let us know if you need more support here @rjointer2 🙏🏻
