### ISSUE TITLE
Processing large data set extremely slow

### ISSUE THREAD

**Issue by piers-smartwyre** [apollographql/apollo-client#8700]
We are using `@apollo/client` with `apollo-link-rest` in a react native application. When querying an endpoint of ours which supplies a fairly large response (4.4mb) using apollo, we are getting a response time from the api in about 2 seconds however the parsed data isn't available from apollo for about 30-180 seconds.

The request is as follows, I cannot share the data although we are returning about 1300 organizations and 4000 products. They each have around 5-10 keys of short strings.

    @rest(
      type: "redacted", 
      path: "redacted",
    ) {
      organizations @type(name: "Organization") {
        ...FULL_ORGANIZATION_FRAGMENT
      }
      products @type(name: "Product") {
        ...FULL_PRODUCT_FRAGMENT
      }
    }

Whilst debugging I have built a raw request workaround using `fetch` that fetches the data, adds the __typenames via looping all organizations and products and writes the data to cache. This process is resolving in around 3-4 seconds including the request.

I understand that apollo is doing much more than my raw request, although i'm sure you'll agree that 30-180 seconds more is quite a big difference. Why is apollo taking such a vast amount of time more to process this data and is there anything we can do to prevent this?

System:
    OS: macOS 11.3.1
  Binaries:
    Node: 16.5.0 - ~/.nvm/versions/node/v16.5.0/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v16.5.0/bin/yarn
    npm: 7.19.1 - ~/.nvm/versions/node/v16.5.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Safari: 14.1
  npmPackages:
    @apollo/client: ^3.4.5 => 3.4.5
    apollo-link-rest: ^0.8.0-beta.0 => 0.8.0-beta.0
    apollo-type-patcher: ^1.0.3 => 1.0.3
    apollo3-cache-persist: ^0.11.0 => 0.11.0

**Comment by benjamn** [comment]
@piers-smartwyre Are these numbers from React Native Android specifically? How does the iOS simulator/device compare?

**Comment by piers-smartwyre** [comment]
@benjamn Sorry, those numbers are from ios simulator. Although I am experiencing similar and sometimes worse numbers on an iOS build.

**Comment by phryneas** [comment]
I've recently done some testing with React Native, and the speeds were comparable to a normal Desktop at this point. 

So it seems like React Native has caught up here - as a result, I'm going to close this issue. 

If this is still a concern, please leave a comment here.
