### ISSUE TITLE
RefetchQueries not working for SSR and ssrForceFetchDelay

### ISSUE THREAD

**Issue by Mordred** [apollographql/apollo-client#8701]
**Intended outcome:**

When I use mutation with `refetchQueries`, it should refetch given queries after execute even when page was rendered with SSR.

**Actual outcome:**

RefetchQueries is ignored for queries executed during SSR when `ssrForceFetchDelay` is used, because subscriptions for these queries are not started.

**How to reproduce the issue:**

Here is demo:

https://github.com/Mordred/apollo-client-ssr-bug

When you insert new todo, it should be displayed immediatelly, but `AllTodos` query is not refetched.

**Versions**

All versions >3.4.0

**Comment by brainkim** [comment]
This is likely fixed in 3.4.10.

**Comment by Mordred** [comment]
Thanks, I just tested 3.4.10 with the demo and it works. Great job.

**Comment by brainkim** [comment]
Glad to hear and sorry about the bug!
