### ISSUE TITLE
SSR not working after 3.4.3

### ISSUE THREAD

**Issue by brdalsnes** [apollographql/apollo-client#8706]
**Intended outcome:**

We have a react app which uses Apollo Client with SSR. We expected everything to work as before after upgrading Apollo Client. 

**Actual outcome:**

We no longer got any data from our query. `loading` was always true. 

**How to reproduce the issue:**

Add the option `ssrMode: true` to the ApolloClient constructor in react-apollo-error-template. The names will no longer appear. If you downgrade to version 3.4.2 everything works as expected again.

**Versions**

=> 3.4.3

**Comment by benjamn** [comment]
@brdalsnes Judging from your reproduction steps, this appears to be fixed in `@apollo/client@3.4.10`. Thanks for bringing this to our attention!
