### ISSUE TITLE
Slow overlapping queries due to MissingFieldError invariants

### ISSUE THREAD

**Issue by bgirard** [apollographql/apollo-client#8707]
**Intended outcome:**
Concurrent queries should about as fast as separate queries.

**Actual outcome:**
I have a use case where two queries are fired on startup for the same objects but different fields. I noticed that the first one was particularly slow to receive, normalize and update the store, taking over 2.6s, while the second one is faster, taking about 400ms. When looking at the trace the majority of the time is spent building MissingFieldError invariants (https://github.com/apollographql/apollo-client/blob/b0da267d24d8713987e9ff8d2240c5c7ed94eb94/src/cache/core/types/common.ts#L21-L33).

(trace)
<img width="1551" alt="Screen Shot 2021-08-26 at 11 43 14 AM" src="https://user-images.githubusercontent.com/793565/131020490-cec6fadd-b037-45b4-b227-bae9c171d83a.png">

(zoomed in)
<img width="1315" alt="Screen Shot 2021-08-26 at 11 53 16 AM" src="https://user-images.githubusercontent.com/793565/131020511-7e299a4d-92c2-4f81-8296-9656cb9294c9.png">

(bottom up stack)
<img width="1781" alt="Screen Shot 2021-08-26 at 11 48 05 AM" src="https://user-images.githubusercontent.com/793565/131020498-e5e781d5-d09b-41cd-b706-ad5da41ff764.png">

It looks like what is happening is the first query requests one set of fields (~100 fields * 200 objects), the second requests a much larger set of fields not contained in the first query (~200 fields *200 objects). Then when the first query completes it normalizes the results and hits MissingFieldError for the missing fields from the second query which hasn’t been processed yet, causing a huge performance bottleneck due to the invariants.

When I run both queries individually they only take 300ms and 400ms respectively. If they’re fired at the same time I hit this problem.

**How to reproduce the issue:**
Send two large queries with overlapping queries. The second queries should contain a lot of fields that aren't present in the first query. The first query should be processed and normalized first.

**Versions**
```
  System:
    OS: macOS 11.4
  Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/universe/webapp/web/node_modules/.bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Firefox: 89.0
    Safari: 14.1.1
  npmPackages:
    @apollo/client: 3.4.9 => 3.4.9 
    apollo: ^2.31.1 => 2.31.2 
    apollo-link-queue: ^3.1.0 => 3.1.0 
    apollo-link-rest: 0.8.0-beta.0 => 0.8.0-beta.0 
    apollo-utilities: 1.3.2 => 1.3.2 
```

**Comment by benjamn** [comment]
@bgirard Here's what I've got so far: #8734 

A little worried about the magnitude of the breaking changes, but I'm willing to try something along these lines in a v3.5 beta release to find out how much trouble it causes.

**Comment by bgirard** [comment]
Awesome. I'll give this a spin and let you know if it resolves the issue.

**Comment by bgirard** [comment]
I'm getting an error when trying to `npm link` your branch. I pulled down your branch. Ran `build` `rollup` `postbuild`. In my linked project I'm seeing error in nested modules like `@apollo/client/core`, `@apollo/client/utilities`, `@apollo/client/react/components`. Am I missing a step?

**Comment by benjamn** [comment]
@bgirard The best way I've found to simulate installing the package from npm is to use a `.tgz` generated by `npm pack`:
```sh
cd path/to/apollo-client
git checkout -t origin/issue-8707-MissingFieldError-performance
npm i
npm run build
cd dist
npm pack
cd path/to/app
npm i ../apollo-client/dist/apollo-client-*.tgz
```

**Comment by bgirard** [comment]
I'm having a hard time upgrading from `3.4.10` -> `3.5.0 beta 11` (your branch). I'll need more time to bisect the issue. I'm getting webpack errors I can't explain.

**Comment by bgirard** [comment]
Bisected to migrating from `.cjs.js` to `.cjs` in https://github.com/apollographql/apollo-client/commit/f5a7a58bf7c054f09b02a73cab80559544e7cf07. Heads up in case others see issues while migrating.

**Comment by bgirard** [comment]
Alright I can confirm the issue is fixed for me with this branch once I modify my webpack config to handle `.cjs` files as `.cjs.js`. Goes from q1=~2600ms + q2=~450ms to q1=~700ms + q2=~500ms. Delta is probably noise so this saves about 2000s. The profiles now look like they're hitting a long tail of useful function.

Thank you for the speedy PR 🍻🍻🍻!

**Comment by conoremclaughlin** [comment]
@bgirard what modifications did you make to your webpack config to handle `.cjs` as `.cjs.js`.

**Comment by bgirard** [comment]
Appended '.cjs' to the extensions and resolver where ever .js was listed.

**Comment by bignimbus** [comment]
Hi all, I'm doing some housekeeping and found this issue.  Given the above I'm going to close this as completed, let me know if there's anything actionable here and I'm happy to re-open this.  Thanks 🙏🏻
