### ISSUE TITLE
subscribeToMore should not need a updateQuery function

### ISSUE THREAD

**Issue by Torsten85** [apollographql/apollo-client#871]
Currently the call to `subscribeToMore` has to have a `updateQuery` function. But the update query part can easy be done via a reducer in the query options. So `updateQuery` shouldn't be mandatory.

**Comment by helfer** [comment]
@Torsten85 Good point! Want to make a PR? It's in the file `watchQueryOptions.ts`.

**Comment by Torsten85** [comment]
@helfer I gave it a try and did a pull request. #879
