### ISSUE TITLE
useQuery renders component twice

### ISSUE THREAD

**Issue by alucardu** [apollographql/apollo-client#8716]
**Intended outcome:**

```
// dashboardComponent.tsx

import React from 'react';
import MovieOverview from './MovieOverview/MovieOverview';

import {useQuery} from '@apollo/client';
import resolvers from '../../resolvers';

const DashboardComponent = () => {
  const {loading, data} = useQuery(resolvers.ReturnAllMovies);
  const movies = data?.movies;
  console.log(movies);

  return (
    <React.Fragment>
      { !loading && movies.length > 0 ? <MovieOverview /> : null }
    </React.Fragment>
  );
};

export default DashboardComponent;
```
When the `dashboardComponent` is loaded I want to use a `useQuery` to get some movies. In the template I want to check if the `movies` const has any movies and if so render a component. 

**Actual outcome:**

When I run the app I get this ouput:

![image](https://user-images.githubusercontent.com/779921/131140582-5a9f1f38-3f4f-4ce4-866d-48d1c4a7efe8.png)

First time the component loads the movies const is undefined, second time the data is loaded.

The issue here is I have to do null checks `const movies = data?.movies;` or check if the component is loading ` { !loading && movies.length > 0` to make sure I don't get a error:

> Cannot read property 'length' of undefined

ps. it makes no difference if i use `import {useQuery} from '@apollo/react-hooks';` or import {useQuery} from '@apollo/client;`
ps2. also I'm not using react strict mode.

**Versions**

  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.78)
  npmPackages:
    @apollo/client: ^3.4.9 => 3.4.9
    @apollo/react-hooks: ^4.0.0 => 4.0.0
    apollo-server: ^3.2.0 => 3.2.0

**Comment by jiri-matejka** [comment]
This is correct behavior. On the first render, the query is still in progress, so you will have { loading = true, data = undefined }. Here you have chance to render a spinner to illustrate that data is loading. 
Once the data has arrived, variables changes: { loading = false, data = <your_data> } so React will rerender you component and you can render your movies.

**Comment by bignimbus** [comment]
Hi all, it appears that this is resolved per the above comment.  Closing for now, let us know if you need support 🙏🏻
