### ISSUE TITLE
How to control the cache refreshing policy

### ISSUE THREAD

**Issue by benams** [apollographql/apollo-client#8730]
When I initiate an apollo client with InMemoryCache, I can set the fetchPolicy.
Is there any way to anticipate or control the cache "refreshing"?
For example:
* query Q is executed against graphql server
* some internal service, which is not our apollo-supported web application changes the DB
* next time the application executes query Q(with the same variables) it will be executed against the cache, and return the "old" data
When will query Q will be back to server execution when no page refresh is involved? (after X minutes? some other triggers?)

**Comment by benjamn** [comment]
@benams Have you tried polling? https://www.apollographql.com/docs/react/data/queries/#polling

**Comment by bignimbus** [comment]
Hi all, given the lack of activity I'm going to close this issue for now.  Let us know if you need more support 🙏🏻
