### ISSUE TITLE
useQuery not triggered with new params using typePolicy for pagination

### ISSUE THREAD

**Issue by inbalserylevy** [apollographql/apollo-client#8735]
I have a query "GET_FINDINGS" with params.

I call it with parameter filter="all" and get result.
I change the parameter to filter="x" and the query is not triggered.

Previously, I used "fetchMore" with "updateQuery" to merge results for pagination, and it worked.
Since I changed it to "typePolicy" and used "merge" function, it stopped fetching when parameters are changed.

**Comment by aseerkt** [comment]
@inbalserylevy  You may have to specify `keyArgs` as `['filter']` in `typePolicies` for query `GET_FINDINGS`.

**Comment by bignimbus** [comment]
Hi all, I'm doing some housekeeping and it looks like this is resolved.  Closing for now, let us know if you need more support 🙏🏻
