### ISSUE TITLE
Uncaught ReferenceError: __DEV__ is not defined

### ISSUE THREAD

**Issue by Qinka** [apollographql/apollo-client#8741]
After I update to `3.4.10` (I also test with 3.5.0 beta`), 

**Intended outcome:**
After I update to `3.4.10` (I also test with `3.5.0 beta`), everything should be ok.

**Actual outcome:**
I got the error message `Uncaught ReferenceError: __DEV__ is not defined` with the file produced by `vite build`, but in `vite` everything is ok, I did not get such an error.

**How to reproduce the issue:**
This problem only happens in the built files, not in vite development server.

I use react, vite, antd, and apollo. 
My code is

```
const cache = new InMemoryCache()

const harleyRole = () => (
  new ApolloClient({
    uri: roleUrlBase + "/user",
    cache: cache
  })
)
```

The error showed in the browser:
```
vendor.cd9db646.js:47 Uncaught ReferenceError: __DEV__ is not defined
    at e.setRootTypename (vendor.cd9db646.js:47)
    at new e (vendor.cd9db646.js:47)
    at new t (vendor.cd9db646.js:47)
    at index.3e83215b.js:formatted:804
```
![image](https://user-images.githubusercontent.com/9249996/131777252-2cc0bd14-2503-4e6c-a4a6-14f30f731d75.png)

**Versions**

  System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
  Binaries:
    Node: 14.17.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Firefox: 91.0.2
  npmPackages:
    @apollo/client: ^3.4.10 => 3.4.10
    react-apollo: ^3.1.5 => 3.1.5

(the information of the system and browser are not correct. it the environment where I build docker image, and the image uses nginx to host the files generated by vite, and I test on the chrome (on windows) and safari (on macos got the same error)

**Comment by Qinka** [comment]
before I update to 3.4.10, I used 3.3.20, which is work.

**Comment by sanderdrummer** [comment]
Facing the same issue. Fixing @apollo/client to 3.4.9 solved it for me.

**Comment by Qinka** [comment]
em........ I did do something wrong. 😢  (I'm not the professional front-end developer) and forget remove `^` mark before version.

as @sanderdrummer  and #8674 mentioned, 3.4.9 works. 

I think this issues is duplicated, so I closed this issues :grimacing:
