### ISSUE TITLE
Download Scehma error

### ISSUE THREAD

**Issue by sam961** [apollographql/apollo-client#8745]
**Intended outcome:**
I was trying to install schema.json using apollo command version 2.33.6
but unfortunately i am receiving the following error

`apollo schema:download --endpoint=https://mydomain.com/graphql schema.json`

**Actual outcome:**
 Error: Cannot find module 'graphql/validation/rules/KnownArgumentNamesRule'
<img width="922" alt="Screen Shot 2021-09-02 at 9 23 25 PM" src="https://user-images.githubusercontent.com/4921874/131896708-50e7930a-21f5-4c1f-b1a2-46fe2f3422cd.png">

**Versions**

  System:
    OS: macOS 11.4
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    npm: 7.21.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Firefox: 84.0.1
    Safari: 14.1.1
  npmGlobalPackages:
    apollo: 2.33.6

**Comment by sam961** [comment]
@benjamn  could you help me in this since it is blocking my work.
Thank you and much appreciated

**Comment by benjamn** [comment]
What version of the `graphql` package are you using?

**Comment by sam961** [comment]
@benjamn  do you mean on the server?

**Comment by benjamn** [comment]
I meant the `version` line in `node_modules/graphql/package.json` (and if that file doesn't exist, try `npm i graphql`).

**Comment by sam961** [comment]
version 2.33.4

**Comment by benjamn** [comment]
I think that's the version for the `apollo` package, which you already provided above (thanks). What about the `graphql` package version?

**Comment by sam961** [comment]
graphql@15.5.3

**Comment by sam961** [comment]
@benjamn  do you have any idea regarding the issue ?

**Comment by sam961** [comment]
@designatednerd  Can you please help me with this? I think @benjamn  is busy and I appreciate it

**Comment by hwillson** [comment]
@sam961 this issue is being tracked here: https://github.com/apollographql/apollo-tooling/issues/2415
