### ISSUE TITLE
Cant make request from react native app running on a real device

### ISSUE THREAD

**Issue by japrozs** [apollographql/apollo-client#8746]
I am building an app in react native and the requests seem to be running smoothly in the emulator, but when I test them on a real device it gives me the following error
```bash
[Unhandled promise rejection: Error: Network request failed]
at node_modules/@apollo/client/errors/errors.cjs.js:34:20 in ApolloError
at node_modules/@apollo/client/core/core.cjs.js:1117:89 in utilities.asyncMap.subscribe$argument_0.error
at node_modules/zen-observable/lib/Observable.js:140:15 in notifySubscription
at node_modules/zen-observable/lib/Observable.js:179:20 in onNotify
at node_modules/zen-observable/lib/Observable.js:240:14 in error
at node_modules/zen-observable/lib/Observable.js:140:15 in notifySubscription
at node_modules/zen-observable/lib/Observable.js:179:20 in onNotify
at node_modules/zen-observable/lib/Observable.js:240:14 in error
at node_modules/@apollo/client/utilities/utilities.cjs.js:948:4 in iterateObserversSafely
at node_modules/@apollo/client/utilities/utilities.cjs.js:1041:42 in _this.handlers.error
at node_modules/zen-observable/lib/Observable.js:140:15 in notifySubscription
at node_modules/zen-observable/lib/Observable.js:179:20 in onNotify
at node_modules/zen-observable/lib/Observable.js:240:14 in error
at node_modules/@apollo/client/link/http/http.cjs.js:276:16 in currentFetch.then.then.then._catch$argument_0
```

Can somebody please explain to me why this is happening?
Here's the code : https://github.com/japrozs/axial

**Comment by benjamn** [comment]
@japrozs That generic `Network request failed` error could mean a lot of different things, unfortunately. If I am able to trigger the same error locally, using your reproduction (thanks!), I think I'll try installing https://github.com/alexbrazier/react-native-network-logger to find out how/why the network request failed. Feel free to try that yourself in the meantime, and let us know what you find out.

**Comment by japrozs** [comment]
Yeah, I figured out the issue. the thing was that I used localhost and it had some complication with the expo server also running on localhost. Once I changed localhost to my local IP address like so:
```tsx
const client = new ApolloClient({
    uri: "http://192.168.1.5:4000/graphql",
    credentials: "include",
    cache: new InMemoryCache(),
});
```
It worked as intended.

**Comment by hwillson** [comment]
Sounds like this has been resolved - thanks!
