### ISSUE TITLE
"@apollo/client": "^3.4.10" get the jsonb value "writable: false"

### ISSUE THREAD

**Issue by ncux199rus** [apollographql/apollo-client#8760]
**Intended outcome:**
I'm making a request to hasura. In response, one of the fields is of the jsonb type. In version 2, everything was fine in version 3, when editing this field, an error occurs - `TypeError: Cannot assign to read only property {} of object '#<Object>'`

**Actual outcome:**

In the apollo client version 2, a request with the jsonb field was returned. And this field was normally edited. 
After updating to version 3, when trying to update the values of this field, it returns the error"".
The reason is that Object. getOwnPropertyDescriptor shows "writable: false"

**How to reproduce the issue:**

index.js:

   ```
const link = new WebSocketLink({
  uri: 'wss://hasura.tech/v1alpha1/graphql',
  options: {
    reconnect: true,
    connectionParams: {
      headers: {
        'x-hasura-admin-secret': '',
      },
    },
  },
})
const cache = new InMemoryCache()
const client = new ApolloClient({
  link,
  cache,
})

ReactDOM.render(
  <Router history={browserHistory}>
    <Auth0ProviderWithHistory>
      <ApolloProvider client={client}>
        <App />
      </ApolloProvider>
    </Auth0ProviderWithHistory>
  </Router>,
  document.getElementById('root')
)
```
query error:
```
 // ! test jsonb
  const testJdata = gql`
    query($id: jsonb) {
      bigdata_userlog(
        where: { jdata: { _contains: $id } }
        order_by: { eventtime: desc }
      ) {
        jdata
      }
    }
  `
  useQuery(testJdata, {
    variables: { id: { objectid: 11 } },
    onCompleted: (data) => {
      const result = data['bigdata_userlog']
      console.log('result = ', result)
      console.log(
        'getOwnProperty = ',
        Object.getOwnPropertyDescriptor(result[0], 'jdata')
      )
      result[0]['jdata'].phone = '123'
    },
  })
```
![image](https://user-images.githubusercontent.com/30354456/132304890-5b729086-1f1f-4ab2-8300-3e4568f750e0.png)

**Versions**

"@apollo/client": "^3.4.10",
"apollo-link-ws": "^1.0.19",
"react": "^16.13.1",
"graphql": "^15.5.1",

**Comment by dylanwulf** [comment]
This is intentional. Data returned from `useQuery` is now always immutable in v3. This forces people to only modify data through the publicly exposed cache API which helps to reduce unexpected behavior.
Try making use of the new type policies instead; you could make a [merge function](https://www.apollographql.com/docs/react/caching/cache-field-behavior/#the-merge-function) that makes changes to the data before it gets written to the cache.

**Comment by ncux199rus** [comment]
Thanks.
I can not change the cache using merge function and writeQuery, just create a new object.

It works:
```
useQuery(testJdata, {
    variables: { id: { objectid: 11 } },
    onCompleted: (data) => {
      const result = data['bigdata_userlog'][0]
      console.log('result = ', result, result['jdata'])
      const obj = Object.assign({}, result['jdata'])
      obj.test = 123
      obj.phone = '111'
      console.log('obj = ', obj)
    },
  })
```
