### ISSUE TITLE
"query option is required. you must specify your graphql document in the query option." with useMutation

### ISSUE THREAD

**Issue by cksal0805** [apollographql/apollo-client#8777]
Hello
I'm using 'useMutation'.
I have to refresh after 'mutation'.
So I wrote it like this.

```js
export const GET_POST = gql`
  query Post($sort: String) {
    post(sort: $sort) {
      values {
        id
        title
        body
      }
    }
  }
`;

export const DELETE_POST = gql`
  mutation DeletePost($input: deletePostInput) {
    deletePost(input: $input) {
      post {
        id
      }
    }
  }
`;
 const [deletePost] = useMutation(DELETE_POST, {
    refetchQueries: [GET_POST, 'Post'],
  });

```

😿 error!
**query option is required. you must specify your graphql document in the query option**

How can I solve this problem?

**Comment by benjamn** [comment]
@cksal0805 There seems to be a missing `}` after the `value` selection set in your `GET_POST` query. Does fixing that help?

**Comment by EHRdev** [comment]
Same problem 😔

**Comment by EHRdev** [comment]
> Hello I'm using 'useMutation'. I have to refresh after 'mutation'. So I wrote it like this.
> 
> ```js
> export const GET_POST = gql`
>   query Post($sort: String) {
>     post(sort: $sort) {
>       values {
>         id
>         title
>         body
>       }
>     }
>   }
> `;
> 
> export const DELETE_POST = gql`
>   mutation DeletePost($input: deletePostInput) {
>     deletePost(input: $input) {
>       post {
>         id
>       }
>     }
>   }
> `;
>  const [deletePost] = useMutation(DELETE_POST, {
>     refetchQueries: [GET_POST, 'Post'],
>   });
> ```
> 
> 😿 error! **query option is required. you must specify your graphql document in the query option**
> 
> How can I solve this problem?

Same problem , how did you solve it bro?

**Comment by cksal0805** [comment]
@EHRdev Try updating the version!
