### ISSUE TITLE
Reactive Variable not triggering useQuery hook

### ISSUE THREAD

**Issue by DanielHuntleySBG** [apollographql/apollo-client#8787]
**Intended outcome:**
useQuery hook should refetch data when a reactive variables state is changed

**Actual outcome:**
useQuery hook does not refetch when a reactive variables state changes

**How to reproduce the issue:**

useQuery hook
```
const search = useReactiveVar(searchVar);

const PLAYLISTS = gql`
    query Playlists($filter: PlaylistFilter, $pageSize: Int, $pageNumber: Int) {
        playlists(filter: $filter, pageSize: $pageSize, pageNumber: $pageNumber) {
            edges {
                id
                name
            }
            pageInfo {
                pageSize
                pageNumber
                hasNextPage
            }
        }
    }
`;

const { loading, error, data} = useQuery<Playlists>(PLAYLISTS, {
    variables: { pageNumber: 0, pageSize: 20, filter: { name: search } }
});

const loadNextPage = () => {
    fetchMore({ variables: { pageNumber: data?.playlists?.pageInfo?.pageNumber + 1, pageSize } });
};

````

Cache
```
export const searchVar: ReactiveVar<string> = makeVar("");

const cache: InMemoryCache = new InMemoryCache({
    typePolicies: {
        Query: {
            fields: {
                playlists: {
                    keyArgs: ["name"],
                    merge(existing = { edges: [] }, incoming) {
                        return { ...incoming, edges: [...existing?.edges, ...incoming?.edges] };
                    }
                },
                search: {
                    read() {
                        return searchVar();
                    }
                }
            }
        }
    }
});

export { cache };
```

Search Component (updating reactive variable)
```
....
  const handleChange = (event: FormEvent<HTMLInputElement>) => {
      searchVar(event.currentTarget.value);
  };
```

**Versions**
3.4.11

Thank you in advance!

**Comment by benjamn** [comment]
@DanielHuntleySBG Your `keyArgs: ["name"]` configuration for the `Query.playlists` fields causes the `filter` variable/argument to be ignored, since `name` is not an argument name for the `Query.playlists` field. Instead, I think you want to make that `keyArgs: ["filter", ["name"]]`, to incorporate `filter.name` into the field key, so that changing the `filter` will cause a cache miss (and thus a network request).

**Comment by DanielHuntleySBG** [comment]
@benjamn thank you very much for the swift reply unfortunately the above did not resolve the issue. Here is the updated cache for reference.

```
const cache: InMemoryCache = new InMemoryCache({
    typePolicies: {
        Query: {
            fields: {
                playlists: {
                    keyArgs: ["filter", ["name"]],
                    merge(existing = { edges: [] }, incoming) {
                        return { ...incoming, edges: [...existing?.edges, ...incoming?.edges] };
                    }
                },
                search: {
                    read() {
                        return searchVar();
                    }
                }
            }
        }
    }
});

export { cache };
```
![cache](https://user-images.githubusercontent.com/51910014/133604197-7c777f92-67ee-4001-b857-f4dc3ad03c3c.PNG)

**Comment by benjamn** [comment]
Do you see anything different if you use `cache.policies` instead of `cache.config`?
```js
__APOLLO_CLIENT__.cache.policies.typePolicies.Query.fields.playlists
```
There should be a `playlists.keyFn` property and it should be a function.

**Comment by DanielHuntleySBG** [comment]
@benjamn Thank you very much for the help! Issue is all resolved.

The issue was caused from having multiple Apollo client instances (something I hadn't considered to be related) and I think the issue stemmed from looking at the wrong client.
