### ISSUE TITLE
Apollo fetch policy "cache-only" is ignored when using pollInterval

### ISSUE THREAD

**Issue by Giusep502** [apollographql/apollo-client#8789]
**Intended outcome:**

I used a query polling that gets always executed in my application (think about notifications). Then I need this information on another page, so I used the same query, always with pollInterval (otherwise it won't get updated), but specifying "cache-only" to avoid double polling, as I'm fine with the first one. What I expect is, if I delete the first polling, the second polling throws an error, as cache-only specifies.
![image](https://user-images.githubusercontent.com/4162365/133461376-e3fab4a8-fecc-4ffb-a852-7004238c5d3e.png)

**Actual outcome:**

The polling always does the call to the network, ignoring the 'cache-only' policy

**How to reproduce the issue:**

Do a polling with cache only without doing it in another part of the application

**Versions**

@apollo/client: ^3.1.3 => 3.1.3

**Comment by benjamn** [comment]
What problem did adding `pollInterval` seem to solve? You shouldn't need to enable polling to receive updates from the cache, if that was the goal.

Polling is a network concept in Apollo Client, so we interpret this code to mean you want the query to be `cache-only` _except_ for the polling queries (which are always `network-only`).

**Comment by Giusep502** [comment]
Ok, I see, I will check again soon and let you know, but I also tried to avoid polling on the second query and it didn't seem to receive the updates from the first polling (the query is identical). I will try again and let you know!

**Comment by Giusep502** [comment]
Yeah it works, i was confused because with polling you receive new data only when it actually updates and not every call. Thank you!
