### ISSUE TITLE
Merge function only called once for an aliased operation with two of the same query

### ISSUE THREAD

**Issue by dontsave** [apollographql/apollo-client#8799]
We have an operation that queries a set of folders in a project with two calls to the same `project` query:

```gql

query GetFolders($projectId: ID!, $page: PageInput!) {
  project(projectId: $projectId) {
    id
    rootAssetId
    folders(page: $page, parentIds: ["root"]) {
      nodes {
        ...Folder
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }

  firstDescendants: project(projectId: $projectId) {
    id
    folders(page: { first: 500 }) {
      nodes {
        ...Folder
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}

```

**Intended outcome:**

We have a merge function on `folders` which does a custom merge of the returned data. Prior to `3.4.0.rc-7` this merge function was called twice, first with the initial `folders` response in the first project query, then again with the next query. This allowed us to use one network request to get top level folder info and first descendant folder info and merge them together.

**Actual outcome:**

After `3.4.0.rc-7` the merge function is only called once, apparently only with the data for the second aliased "firstDescendants" query.

**How to reproduce the issue:**

Unfortunately not possible to provide a repro due to sensitive code

**Comment by dontsave** [comment]
@benjamn understood about not wanting to call the merge more than once for a field. we currently have `keyArgs` to `false` to keep all folders under the same entry, but we'll play with a custom function there to see if we can get the behavior we want. thanks for the response!

**Comment by hwillson** [comment]
Thanks @dontsave - we'll close this for now.
