### ISSUE TITLE
Import @apollo/client/core unnecessarily require react 

### ISSUE THREAD

**Issue by ianhe8x** [apollographql/apollo-client#8809]
**Intended outcome:**
Doesn't need to have react installed when only `@apollo/client/core` is used. It was fine at v3.4.9.

**Actual outcome:**
panic because I don't have react.

**How to reproduce the issue:**
use latest version 3.4.12 and use ApolloClient without react in package.json

**Versions**
  System:
    OS: macOS 11.5.2
  Binaries:
    Node: 14.15.2 - ~/.nvm/versions/node/v14.15.2/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.6.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 93.0.4577.63
    Edge: 93.0.961.44
    Firefox: 91.1.0
    Safari: 14.1.2

** clues **
in `@apollo/client/utilities/utilities.cjs.js`, in v3.4.12 there's `var __ = require('..');` which not exists in v3.4.9

** error stack **
```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'react'
Require stack:
- /usr/local/lib/node_modules/---/node_modules/@apollo/client/react/context/context.cjs.js
- /usr/local/lib/node_modules/---/node_modules/@apollo/client/react/react.cjs.js
- /usr/local/lib/node_modules/---/node_modules/@apollo/client/main.cjs.js
- /usr/local/lib/node_modules/---/node_modules/@apollo/client/utilities/utilities.cjs.js
- /usr/local/lib/node_modules/---/node_modules/@apollo/client/link/core/core.cjs.js
- /usr/local/lib/node_modules/---/node_modules/@apollo/client/core/core.cjs.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/---/node_modules/@apollo/client/react/context/context.cjs.js:6:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)

```

**Comment by junya100** [comment]
Same here.

**Comment by luudv** [comment]
I get the same problem.

**Comment by jonathancslynn** [comment]
I have this same issue too. Didn't have a problem 2 days ago before the new release.
Tried v3.4.11 just to double check and it seems like this was introduced with v3.4.12

**Comment by korbav** [comment]
Same from my side, I do confirm the regression's been introduced in the latest release. 
`v3.4.11` works flawlessly.

**Comment by Yohandah** [comment]
Got the same issue; no issue in v3.4.11 but error in v3.4.12 .....

Waiting for React to be removed with v4 https://github.com/apollographql/apollo-client/issues/7318

**Comment by benjamn** [comment]
Sorry for the auto-close. We'll close this after confirming the next `@apollo/client` version works for everyone.

**Comment by korbav** [comment]
> 
> 
> Sorry for the auto-close. We'll close this after confirming the next `@apollo/client` version works for everyone.

Successfully tested from me. Thanks for the reactivity!

**Comment by schw4rzlicht** [comment]
@benjamn `3.4.13` fixes the issue for me, thanks! 🎉

**Comment by benjamn** [comment]
Closing based on multiple confirmations, but of course we're happy to reopen if @ianhe8x is still having problems. Thanks everyone!
