### ISSUE TITLE
TypeError: (0 , _client.makeVar) is not a function

### ISSUE THREAD

**Issue by omjokine** [apollographql/apollo-client#8816]
**Intended outcome:**
Upgraded from 3.4.11 to 3.4.12 and tried to run tests and expected everything go smoothly because there shouldn't be any breaking changes.

**Actual outcome:**
Got this failure:
```
  ● Test suite failed to run
    TypeError: (0 , _client.makeVar) is not a function
```
when importing `makeVar` like it is suggested in the docs (https://www.apollographql.com/docs/react/local-state/reactive-variables/):
```
import { makeVar } from '@apollo/client'
```

Got it working by changing the import to:
```
import { makeVar } from '@apollo/client/cache'
```

but then I ran into different issues (https://github.com/apollographql/apollo-client/issues/8814)

**How to reproduce the issue:**
import makeVars:
```
import { makeVar } from '@apollo/client'
```

**Versions**
```
  System:
    OS: macOS 11.6
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 7.22.0 - ~/.nvm/versions/node/v14.17.6/bin/npm
  Browsers:
    Chrome: 93.0.4577.82
    Edge: 93.0.961.52
    Firefox: 91.0.2
    Safari: 14.1.2
  npmPackages:
    @apollo/client: 3.4.12 => 3.4.12
    apollo-link-logger: 2.0.0 => 2.0.0
 ```

**Comment by johgoe** [comment]
Same issue with `gql`. `gql` is undefined debugging it in our jest tests.

Sample Code

```
import { gql } from '@apollo/client';

export const whoamiQuery = gql`query Whoami {
  whoami {
    username,
    firstName,
    lastName,  
  }
}`;
```

**Comment by benjamn** [comment]
Given the narrow version range, I'm hopeful #8817 will solve this problem (new `@apollo/client` version coming shortly).

**Comment by benjamn** [comment]
@johgoe Please try `@apollo/client@3.4.13` (which includes #8817) when you have a chance!

**Comment by KeesV** [comment]
@benjamn I had the same issue as @johgoe , and can confirm that `@apollo/client@3.4.13` fixed it (at least for me).

**Comment by benjamn** [comment]
Thanks everyone! Happy to reopen if this isn't fixed for @omjokine.

**Comment by saimonmoore** [comment]
I have a clue as to what is happening in our case. We are using storybook and we have duplicated the gql queries under the storybook directory as they are needed for certain components we display in storybook. It appears that these queries under the storybook directory are being picked up during the jest test run and causing the issue mentioned by @TiredFalcon. If we remove the storybook directory the tests pass.

I tried removing the storybook directory from `testPathIgnorePatterns` but not working right now.

**Comment by saimonmoore** [comment]
```
modulePathIgnorePatterns: ['<rootDir>/.storybook'],
```

this fixed it for us.

**Comment by damiangreen** [comment]
This is an issue on 3.6.9. @[saimonmoore](https://github.com/saimonmoore) solution didnt help us

**Comment by hamza-iqbal-hi** [comment]
Still getting this issue when testing with Jest. Apollo Client Version : 3.5.10,
