### ISSUE TITLE
No access to context when specifying a WebSocketLink

### ISSUE THREAD

**Issue by Spark3000** [apollographql/apollo-client#8830]
I am storing my JWT auth token in memory and upon initialization of my app, Apollo Client and links, it's not yet available, leading to my WebSocketLink being instantiated with empty auth headers.

My first link in the Apollo link chain is a `tokenRefreshLink` which determines if the token needs to be set and if so goes and gets it and sets it memory and on operation context as headers. 

So my http terminating links work fine (communicating with Hasura) as they use the headers from this link in the chain. 

However I don't have access to the context for the WebSocket link (it seems??) and so don't have the ability to update this token? Or is there a way to recreate the whole WebSocketLink when the token becomes available?

I don't want to have to change to storing my auth tokens in localstorage. Everything else is working well in my app. It's just this bug. I don't see a way around it.

My WebSocketLink:
```typescript
  const wsLink =
    isBrowser() &&
    new WebSocketLink({
      uri: `${HASURA_URL}/v1/graphql`.replace('http', 'ws').replace('https', 'wss'),
      options: {
        reconnect: true,
        timeout: 30000,
        connectionParams: () => {
          return { headers: getHeaders() };
        },
      },
    });
```

My link for the ApolloClient. Using NextJs so checking if in browser first
```typescript
  if (isBrowser()) {
    const apolloLink = ApolloLink.from([
      tokenRefreshLink,
      ApolloLink.split(operationIsSubscription, wsLink, httpLink),
    ]);
    return apolloLink;
  }
```

**Intended outcome:**
Be able to update the token in headers for WebSocketLinks just like is possible for http links using context for once it is available on first load, and subsequently for when it expires. 

**Actual outcome:**
An empty token in headers for WebSocketLinks. 

**Versions**
"@apollo/client": "^3.4.5",
"next": "11.0.1",

Thanks.

**Comment by hwillson** [comment]
@Spark3000 regarding:

> Be able to update the token in headers for WebSocketLinks just like is possible for http links using context for once it is available on first load, and subsequently for when it expires.

You can pass a [`lazy: true`](https://github.com/apollographql/subscriptions-transport-ws#constructorurl-options-websocketimpl) option to the `WebSocketLink` to make sure socket initialization is delayed until a subscription is created, then adjust your `connectionParams` function to include an async way of fetching/using your token. Something like:

```js
const wsLink =
  isBrowser() &&
  new WebSocketLink({
    uri: `${HASURA_URL}/v1/graphql`.replace('http', 'ws').replace('https', 'wss'),
    options: {
      lazy: true,
      reconnect: true,
      timeout: 30000,
      connectionParams: async () => {
        const authToken = await loadToken();
        return {
          headers: {
            ...getHeaders(),
            Authorization: authToken ? `Bearer ${authToken}` : ''
        };
      },
    },
  });
```

This doesn't sound like a bug, so I'll close this off (and if you have more usage questions, our [community forums](https://community.apollographql.com) are a great place to ask for help). Thanks!
