### ISSUE TITLE
cache of apollo client

### ISSUE THREAD

**Issue by nicknguyen888** [apollographql/apollo-client#8836]
I have an issue:
I have 2 components and use the same api with same params. However, the first component use pagination and when I select another page, data of the first component is changed so data of the second component also is changed and I don't want it. For example:
-component 1: useQuery(GET_ALL,{variables:{page:1,limit:5}}})
-component 2: useQuery(GET_ALL,{variables:{page:1,limit:5}}})
I change page param of the first component, then I get data like [{_id:1, name:'David1},{_id:1, name:'David2}]. The second component is updated with the same data and i don't want it. How can I resolve this case, many thanks.

**Comment by hwillson** [comment]
@nicknguyen888 Apollo Client usage questions like this are better asked in our [community forums](https://community.apollographql.com). The issue tracker here is reserved for bugs. Thanks!
