### ISSUE TITLE
How to capture the error response

### ISSUE THREAD

**Issue by kaykhancheckpoint** [apollographql/apollo-client#8844]
The request i am making returns a 400 bad request and in the network tab i can see the json of the errors. 

This is what i would like to log in my code but i am uanble to.

[![enter image description here][1]][1]

```
        try {
            const response = await GraphQLClient.query({
                query: GET_PERSON,
                variables: {
                    personId: id,
                },
                errorPolicy: "all",
            });
            console.log("response", response);
        } catch (err) {
            console.log("err", err);
        }
  ```

When i execute the above it goees into the catch block and i do not have access to the errors object.

> err Error: Response not successful: Received status code 400
>     at new ApolloError (index.ts:54)
>     at QueryManager.ts:1073
>     at both (asyncMap.ts:30)
>     at asyncMap.ts:19
>     at new Promise (<anonymous>)
>     at Object.then (asyncMap.ts:19)
>     at Object.error (asyncMap.ts:31)
>     at notifySubscription (module.js:137)
>     at onNotify (module.js:176)
>     at SubscriptionObserver.error (module.js:229)
>     at iteration.ts:13
>     at Array.forEach (<anonymous>)
>     at iterateObserversSafely (iteration.ts:13)
>     at Object.error (Concast.ts:185)
>     at notifySubscription (module.js:137)
>     at onNotify (module.js:176)
>     at SubscriptionObserver.error (module.js:229)
>     at createHttpLink.ts:203

  [1]: https://i.stack.imgur.com/ZoZGc.png

graphqlservice

```
import { ApolloClient, InMemoryCache } from "@apollo/client";
import { Config } from "./../config";

const FRONTEND_API = `${Config.frontend_api}/graphql` || "";

export const GraphQLClient = new ApolloClient({
    uri: FRONTEND_API,
    cache: new InMemoryCache(),
}
```

How do i log the errors returned from a 400 response?

**Comment by hwillson** [comment]
@kaykhancheckpoint the error being caught in your `catch` has the extra details you're looking for, you're just not seeing them when you `console.log(err)` (because we're extending the `Error` class which means `console.log` won’t show the extra properties by default). If you want to see the full structure of the error object, try something like `console.log(JSON.stringify(err));`.
