### ISSUE TITLE
awaitRefetchQueries and errors

### ISSUE THREAD

**Issue by blancoal** [apollographql/apollo-client#8856]
I think I'm seeing that if I have a mutation with a refetch, and awaitRefetchQueries: true, if there is an error in the refetch that still provides partial data and a 200 response code, the mutation never completes. This seems like incorrect behavior. Is this a known issue?

**Comment by brainkim** [comment]
That definitely does seem like incorrect behavior!

I hate to sound like a broken record, but do you have a runnable reproduction that we could look at? Or some code examples?
Unfortunately, we can only be so precise with our words.
https://github.com/apollographql/react-apollo-error-template

**Comment by blancoal** [comment]
Let me try a code snippet, and I'll look at the template after.

  withMutation(MUTATION1, {
    name: "operationX",
    options: props => {
      const {
        [snip]
      } = props;

      const refetchQueries = [
              {
                query: QUERY1,
                variables: {
                  namespace,
                  id: x,
                },
              },
            ];

      return {
        onCompleted: () => {
          completionCode();
        },
        refetchQueries,
        awaitRefetchQueries: true,
      };
    },
  }),

In this case, completionCode() is never called. The response has a 200 code, and the payload had this form:
{
    "errors": [
        {
            "code": 400,
            "message": "bla."
        },
        {
            "code": 400,
            "message": "bla"
        }
    ],
    "data": {
        "query1": {
            "id": 217519115,
            "username": "x",
            "full_name": "x"
        }
    }
}

Using:
    "@apollo/react-hoc": "3.1.5",
    "@apollo/react-hooks": "3.1.5",
    "@apollo/react-testing": "3.1.4",
    "apollo-cache-inmemory": "1.6.6",
    "apollo-client": "2.6.10",
    "apollo-link": "1.2.14",
    "apollo-link-context": "1.0.20",
    "apollo-link-error": "1.1.13",
    "apollo-link-http": "1.5.17",
    "apollo-link-state": "0.4.2",
    "apollo-link-token-refresh": "0.3.2",

**Comment by blancoal** [comment]
@brainkim

**Comment by blancoal** [comment]
update?

**Comment by blancoal** [comment]
ping?

**Comment by blancoal** [comment]
any update @brainkim

**Comment by bignimbus** [comment]
Hi @blancoal, I'm doing some housekeeping and came across this issue.  I'll echo the previous request for something runnable - I'm not sure how to reproduce this issue with the code snippets given.  Thanks for your patience!
