### ISSUE TITLE
Throws and catches an exception in getDEV() on every page load

### ISSUE THREAD

**Issue by bhallstein** [apollographql/apollo-client#8865]
### Actual outcome:

Each page load, Apollo client throws and catches an exception to check for the existence of a `__DEV__` variable in the function `getDEV()`. When exceptions are enabled in web inspector, each page load this causes an annoyance to a web developer developing on the library.

_Quick discussion re certain obvious workarounds:_

- It is possible to switch the debugger to only catch uncaught exceptions, but this is not always possible/convenient/advisable while doing dev work.
- Some browsers allow you to disable breakpoints in certain files, but this depends on the dev setup / bundler; plus, Safari does not have this feature.

### Intended outcome:

It would be an absolutely fantastic quality of life improvement if Apollo could check for the existence of this variable _without_ throw/catching. I am losing many minutes per day simply clicking the 'continue script execution' button in the web inspector!

### How to reproduce the issue:

With the web inspector open and breaking on all exceptions enabled, load any app running on `@apollo/client/react`.

### Versions

- System:
  - OS: macOS 11.6
- Binaries:
  - Node: 16.9.1 - /usr/local/bin/node
  - Yarn: 1.22.10 - /usr/local/bin/yarn
  - npm: 7.21.1 - /usr/local/bin/npm
- Browsers:
  - Firefox: 92.0
  - Safari: 15.0
- npmPackages:
  - @apollo/client: ^3.4.13 => 3.4.15 
  - apollo-upload-client: ^16.0.0 => 16.0.0 

Thanks so much for reading.

![Screenshot 2021-09-29 at 15 57 40](https://user-images.githubusercontent.com/3428028/135295980-246b773b-33b5-4947-a30a-bbde927b4d64.png)

**Comment by alessbell** [comment]
Hi, @bhallstein 👋  We have an alpha release with a change that should improve things here, you can install it with `npm i @apollo/client@alpha` or the package manager of your choice :) If you have a chance to test it out, would love to know if that helps!

**Comment by bignimbus** [comment]
Hi @bhallstein 👋🏻  just wanted to follow up here - we are closing this issue as completed.  Please do feel free to open a new issue if you continue to see this happening after trying `npm i @apollo/client@alpha` 🙏🏻

**Comment by bhallstein** [comment]
Thanks for the update! Sorry for the delay replying, glad to see this improvement. 🚀
