### ISSUE TITLE
It is not possible to wait for subscription to subscribe

### ISSUE THREAD

**Issue by aleksandrlat** [apollographql/apollo-client#8886]
**Intended outcome:**
I want to implement response for mutation to come through websocket.
I.e. 
- subscribe to subscription
- call mutation to trigger some long running process on server
- receive result of long running process in subscription message

But I can call mutation only after I can confirm I subscribed to subscription

**Actual outcome:**
`loading` is true when I subscribed to subscription
```
const { loading, data } = useSubscription(subscription)
// loading is true when I subscribed to it
```

**How to reproduce the issue:**
Just subscribe to subscription

**Versions**
version 3

**Comment by rossimelthomas** [comment]
any updates?

**Comment by phryneas** [comment]
I believe you can use the `onData` callback of `useSubscription` for this.

```js
function MyComponent() {
  const calledRef = useRef(false);
  const { loading, data } = useSubscription(subscription, {
    onData({ data }) {
      if (!calledRef.current) {
        calledRef.current = true;

		console.log(data)
        // execute your mutation here
      }
    },
  });
}
```
I believe beyond that, we can't really do a lot here - React doesn't wait for something to happen before rendering, it just synchronously renders your component.

As a result I'm going to close this issue - if you have any further usage questions, please also consider joining our [Discord](https://discord.com/invite/graphos) - we try to keep the issue tracker for bug reports and usage questions more in the Discord.
