### ISSUE TITLE
Error: process is not defined when useQuery hook used with vite dev server

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [apollographql/apollo-client#8889]
**Intended outcome:**

Get the result of a successful GraphQL query from a useQuery hook

**Actual outcome:**

Query succeeds on the server (can see result in browser dev tools), but hook returns an error:

![image](https://user-images.githubusercontent.com/159100/135882743-86e61ad2-c269-4062-b700-198bbed3888e.png)

**How to reproduce the issue:**

I'm migrating from Webpack to Vite, and started seeing this error on @apollo/client 3.3.13. I tried upgrading the package, but still seeing the same error.

**Versions**

  System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
  Binaries:
    Node: 14.16.0 - ~/n/bin/node
    Yarn: 1.22.0 - ~/code/my-project/node_modules/.bin/yarn
    npm: 7.12.1 - ~/n/bin/npm
  Browsers:
    Chrome: 94.0.4606.61
    Firefox: 92.0
  npmPackages:
    @apollo/client: ^3.4.15 => 3.4.15 
    apollo: ^2.23.0 => 2.23.0 
  npmGlobalPackages:
    apollo: 2.18.3

This seems possibly related to https://github.com/apollographql/apollo-client/issues/4665

/cc @brainkim -- thanks for offering to take a look!

**Comment by benjamn** [comment]
@uhoh-itsmaciek It's especially important in this case that you finish updating to v3.4, since we stopped using `process.env` internally in that release (in favor of `__DEV__`), so this behavior is likely to be directly impacted by the update. As for why you're still seeing the error after updating, maybe try clearing any bundling/build caches and rebuilding?

**Comment by uhoh-itsmaciek** [comment]
@benjamn As far as I can tell, I'm fully on 3.4.15 now. Just in case, I tried `vite clobber` to clear vite's cache, and I tried upgrading `apollo` (which I'm pretty sure is not the issue here, but it's the only other direct apollo dependency we have, for GQL TS type codegen) to the latest. I'm still seeing the same problem.

**Comment by uhoh-itsmaciek** [comment]
I also noticed that most of the JS/TS deps were being cached by the browser, so I did a hard reload to clear the browser cache, but that didn't help either.

**Comment by uhoh-itsmaciek** [comment]
This turned out to be coming from our own code that's passed into `new ApolloClient` as a custom `link` option. Sorry for the noise, though it would be super helpful if apollo-client could identify the error as coming from the custom link in this case.
