### ISSUE TITLE
How to read response body of networkError of status code 4xx

### ISSUE THREAD

**Issue by kporaj** [apollographql/apollo-client#8905]
Hi!

- I have a query const { data, **error** } = useQuery<TestQuery>(TEST_QUERY);
- When it returns networkError of **status code 409**, I need to read an object {email: string, message: string} from it's response.body
- Using network tab in chrome inspection tools I can see the graphql response:
{"email" : "test@gmail.com", "message": "test"}, but I have problems reading it inside application.

I've tried few approaches:
- error.networkError.response.json().then((res) => console.log(res)); --> 
This result's in error: **Failed to execute 'text' on 'Response': body stream already read**

- with a reader - error.networkError.response.body.getReader(); -->
But this also results in an error: **Failed to execute 'getReader' on 'ReadableStream': ReadableStreamDefaultReader constructor can only accept readable streams that are not yet locked to a reader**

- The only way I've managed to get it is a little bit workaround'ish 
console.log(JSON.parse(JSON.stringify(error.networkError)).result.email), shows "test@gmail.com".

**Comment by bignimbus** [comment]
Hi @kporaj, thanks for your patience.  I think what you might be looking for is [Error Link](https://www.apollographql.com/docs/react/api/link/apollo-link-error/).  Let us know if those docs don't help resolve your question 🙏🏻
