### ISSUE TITLE
Intermittent test failures when upgrading from 3.3 to 3.4.16

### ISSUE THREAD

**Issue by jmclane2007** [apollographql/apollo-client#8913]
I recently updated a project from version 3.3 to 3.4.16 and I'm now seeing intermittent errors in my tests. The tests are using React and @testing-library/react with jest. The main issue is that tests occasionally get stuck in the "Loading" state. In the documentation, https://www.apollographql.com/docs/react/development-testing/testing/#testing-the-success-state, states that all I should need to do is await a 0ms timeout, but that's already being done. Is this a bug with @apollo/client or am I doing something wrong here?

An example of a test that is failing randomly.
```
test("renders control view when data exists", async () => {
  await act(async () => {
    renderControlViewForMockId(CONTROL_WITH_TESTS_AND_RELATED_CTRLS);
    await new Promise((resolve) => setTimeout(resolve, 0));
  });

  const text = screen.getAllByText("Control 1");
  expect(text.length).toBe(2);
  expect(text[0]).toBeInTheDocument();
  expect(text[1]).toBeInTheDocument();
});
```

The render method.
```
const renderControlViewForMockId = (id: string) => {
  render(
    <MockedProvider mocks={[...queryMocks, ...eventMocks]} addTypename={false}>
      <MemoryRouter initialEntries={[`/testUrl/${id}`]}>
        <Route path="/base/:baseId/sub/:subId">
          <ModalProvider>
            <ModalWrapper>
              <ControlContainer />
            </ModalWrapper>
          </ModalProvider>
        </Route>
      </MemoryRouter>
    </MockedProvider>
  );
};
```

**Comment by brainkim** [comment]
One thing you could try is to put the `expect` calls in a `waitFor` callback (https://testing-library.com/docs/dom-testing-library/api-async#waitfor). This will keep trying the callback until all the assertions succeed, and automatically squash any `act()` warnings.

Beyond that, I’m not sure what’s causing the change without more information. Which expectations fail? What environments?

**Comment by brainkim** [comment]
There is a `findAllByText` method which seems to wrap `getAllBy` in an act so that it is awaitable (https://testing-library.com/docs/dom-testing-library/cheatsheet/#queries). I think that might help your use-case?

> seems like it is covering up a symptom rather than the cause. This issue only happens when updating our apollo client version. I don't know how to reliably reproduce this since the errors are not consistent and it seems to be an issue with the timing during the test.

I appreciate the concern, but I believe your issues are with React, not Apollo Client. We don’t consider the exact timings of the hooks to be part of the public interface, and APIs like `useEffect()` and `useState()` are not guaranteed to run synchronously, even if that’s how they work today. The hooks are being heavily refactored, and the timings will change between minor versions. The fact that react-testing-library has to implement all these polling methods is more or less an admission of this lack of precision on React’s part.

I would try awaiting a `screen.findAllByText` and seeing if that helps with the flake!

**Comment by Holalko** [comment]
@jmclane2007 did you manage to solve this?.. im having similar issue to this

```tsx
// render is basically <MockedProvider mocks={props.mocks}>{children}</MockedProvider>

it('...', async () => {
    render(
      <MyComponent />,
      {
        mocks: [
          ...
          mockedGetPriceConfigQuery,
          ...,
        ],
      }
    );

    const routines = await waitFor(() => screen.queryByTestId('routines'));
    expect(routines).not.toBeInTheDocument();

    const relatedProductsWrapper = await screen.findByTestId(
      'related-products-wrapper'
    );

    await wait(5000); // imported from 'waait' as documentation stated
    const relatedProducts = await waitFor(
      () => screen.getAllByTestId('product-item'),
      { timeout: 4000 } // tried to increate timeout
    );
  })
```

probably issue is with useQuery, because one useQuery is returning undefined data, even when mock is provided

```ts
export const usePriceConfig = (): QueryResult<getPriceConfig> => {
  console.log('start usePriceConfig');
  const res = useQuery<getPriceConfig>(getPriceConfigQuery, {
    onError: (e) => {
      console.log('onError', e);
    },
    onCompleted: (data) => {
      console.log('onCompleted', data);
    },
  });


  console.log(
    'response',
    res.loading,
    res.networkStatus,
    res.data,
    res.previousData,
    res.called
  );

  return res;
};
```

and in console i see 

```
 console.log
    start usePriceConfig

  console.log
    response true 1 undefined undefined true

  console.log
    start usePriceConfig

  console.log
    response true 1 undefined undefined true

  console.log
    start usePriceConfig

  console.log
    response true 1 undefined undefined true
```

so `data` is always `undefined`, `onCompleted` and `onError` is never called..

so i tried to call refetch manually in useEffect such as

```tsx
React.useEffect(() => {
    void res
      ?.refetch()
      .then((response) => console.log('refetch-response', response));
  }, []);
```

in console i see there is a response that i passed to `mocks`

```ts
console.log
    refetch-response {
      data: {
        myMockedData: [1,2,3,4,5]
      },
      loading: false,
      networkStatus: 7
    }
```

but result of `useQuery` is still the same:

```
console.log
 response true 1 undefined undefined true
```

This happened when updated from 3.3.21 to 3.4.. i read changelog multiple times but didn't find anything. App seems to be working fine, only tests fail (around 80 tests out of 600)

versions: 
    "babel-jest": "^27.5.1",
    "jest": "^27.5.1",
    "jest-cli": "^27.5.1",
    "jest-react-hooks-shallow": "^1.5.1",
    "jest-transform-graphql": "^2.1.0",
    "ts-jest": "^27.1.3",
    "@testing-library/dom": "^8.11.3",
    "@testing-library/jest-dom": "^5.16.2",
    "@testing-library/react": "^12.1.3",
    "@testing-library/react-hooks": "^7.0.2",
    "@testing-library/user-event": "^13.5.0",
    
    
 jest config:
 ```js
 {
      displayName: 'client',
      testMatch: ['**/packages/client/**/?(*.)test.(t|j)s?(x)'],
      transform: {
        '^.+\\.(gql|graphql)$': '@jagi/jest-transform-graphql',
        '^.+\\.(j|t)s(x)?$': 'ts-jest',
        '^.+\\.svg$': 'jest-transform-stub',
      },
      moduleDirectories: ['node_modules', 'packages/client/src'],
      moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'graphql', 'gql'],
      moduleNameMapper: {
        ...clientSrcAliases,
        '.*\\.(css|less|styl|scss|sass)$':
          '<rootDir>/config/mocks/cssModule.js',
        '.*\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
          '<rootDir>/config/mocks/image.js',
      },
      setupFilesAfterEnv: ['<rootDir>/config/client-test-bundler.js'],
      testURL: 'http://localhost',
      verbose: false,
      testEnvironment: 'jsdom',
    },
```


jest environment setup:
```js
require('babel-polyfill');
require('mutationobserver-shim');
require('@testing-library/jest-dom');

const Enzyme = require('enzyme');
const Adapter = require('enzyme-adapter-react-16');

import enableHooks from 'jest-react-hooks-shallow';


enableHooks(jest);

Enzyme.configure({ adapter: new Adapter() });

Object.defineProperty(window, 'matchMedia', {
  value: () => ({
    matches: false,
    addListener: () => {},
    removeListener: () => {},
  }),
  configurable:true,
  writable:true
});
```

**Comment by jmclane2007** [comment]
@Holalko with that issue we never did figure out what was going on with 3.4.16. We are now on version 3.5.7 and have not seen the same intermittent errors.

**Comment by bignimbus** [comment]
Hi all, I'll close this issue for now since it appears to have been resolved in newer releases.  Please let us know if you need more support here 🙏🏻
