### ISSUE TITLE
Specifying onQueryUpdated breaks cache writes

### ISSUE THREAD

**Issue by dylanwulf** [apollographql/apollo-client#8919]
**Intended outcome:**
When I use `cache.writeQuery` in a `useMutation`'s `update` function, the results of that `cache.writeQuery` should be rendered on the screen, whether or not `onQueryUpdated` is specified.

**Actual outcome:**
Specifying `onQueryUpdated` will prevent `cache.writeQuery`'s changes from being rendered on the screen, no matter what gets returned from `onQueryUpdated`.

**How to reproduce the issue:**
https://codesandbox.io/s/apollo-client-onqueryupdated-obcsw?file=/src/index.js

**Versions**
```
@apollo/client: 3.4.16
graphql: 15.6.1
react: 17.0.2
```

**Comment by benjamn** [comment]
@dylanwulf Thanks for the reproduction! It definitely was my intention that adding/removing an `onQueryUpdated` callback should not immediately change the behavior of the refetching, so I consider this a bug. Still working on a full solution plus tests, but this should be fixable in a v3.4.x patch release.
