### ISSUE TITLE
Possible memory leak regression.

### ISSUE THREAD

**Issue by oferitz** [apollographql/apollo-client#8944]
A continuation of #8903.
As reported in the original issue, we are seeing a memory leak after upgrading from `3.4.10` to `^3.4.15`.
I Was asked by @brainkim to send an allocation file that demonstrate it but with un-minified code.
Also in order to nail down the problem to a specific version, I will try to isolate the exact version between `3.4.10` - `3.4.15` where we started to see the problem.

Will update here as soon as i have new findings. 

**EDIT:**
I've nailed down the exact version of this issue which is `3.4.14`. So this is something that happened between `3.4.13` and `3.4.14`.

@brainkim here is the memory allocation image. Unfortunately I can't attach the full allocation sampling file as it contains proprietary code but let me know if you need any particular function or section and I can upload a new image.

<img width="1241" alt="Screen Shot 2021-10-19 at 10 03 24" src="https://user-images.githubusercontent.com/1668687/137860497-9e0ba7bf-a221-4500-8fec-46de4e4e4057.png">

BTW, like you said Chrome 94 has a bug with the memory tools, so I had to use Chrome Beta 95.

Thanks.

**Comment by phryneas** [comment]
Hi there,
I realize this is an old issue, but we just released Apollo Client 3.9 beta this week, and it contains a ton of memory improvements - the new memoization cache limits it introduced might also be solving the issue you were seeing here.

So I'd be happy if you give it a try - you can read up on everything that's included here:
https://www.apollographql.com/blog/apollo-3-9-beta-feature-spotlight-the-memory-story

**Comment by oferitz** [comment]
Hey @phryneas, thanks for the update! Really happy to hear the good news. I also found the blog post quite interesting. By the way, do you happen to know which tool was used in the screenshots on https://github.com/apollographql/apollo-client/issues/7942?

We switched to URQL a while ago because of memory leaks and some other reasons, especially for easier testing. I won't be able to test if this issue is fixed, but I hope it helps others. Feel free to close the issue if you think it's sorted in Apollo Client 3.9. Thanks! 🚀

**Comment by phryneas** [comment]
@oferitz As for the screenshots: the second (and third, I believe) screenshots should be the chrome devtools "memory" tab - as for the first screenshot, that seems to be some kind of server monitoring tool, but I don't know which one.

I'll close this one then - have a good new year! 🎉
