### ISSUE TITLE
Parse http response

### ISSUE THREAD

**Issue by Lana11s** [apollographql/apollo-client#8945]
We run into issue that when server does not respond in JSON format, there will be a ServerParseError instead of the ServerError. This happens because JSON.parse() is done before checking the status code: 
https://github.com/apollographql/apollo-client/blob/main/src/link/http/parseAndCheckHttpResponse.ts (lines 19 and 30).

In this case, the error message of ServerParseError does not provide the information about the actual cause but only the parse error.

In some error cases, there is no guarantee that server will repsonse in JSON fromat.
For example if there is an authentication error. Or if response is an uncomplete JSON object because of 500 out of memory.

Could you please check if it is intended to be this way?
Thank you!

**Comment by dillontiner** [comment]
I noticed #8974 wasn't merged -- is there anything blocking it? I started seeing this bug, but noticed that PR should fix it

**Comment by dillontiner** [comment]
Maybe should've tagged @benjamn instead -- is there any reason not to merge the fix? Looks like a small change that just needs a rebase

**Comment by Crocsx** [comment]
I would love to have this PR merge when possible. It 's a small change, but would remove a lot of "workaround" code in my project to retrieve the proper error without using the onError link (cause has noted it doesnt work in this case)
