### ISSUE TITLE
Headers are not passed when using cross-fetch

### ISSUE THREAD

**Issue by samuela** [apollographql/apollo-client#8967]
**Intended outcome:**
Passing custom headers along with my requests when using `ApolloClient`.

**Actual outcome:**
When using cross-fetch the headers are not passed as expected.

**How to reproduce the issue:**

Consider a very simple client running on node.js:
```js
const {
  ApolloClient,
  HttpLink,
  InMemoryCache,
  gql,
} = require("@apollo/client/core");
const { fetch } = require("cross-fetch");

const client = new ApolloClient({
  link: new HttpLink({ uri: "https://hookb.in/xYjbyaxeOLh0nNxxnWpY", fetch }),
  cache: new InMemoryCache(),
  headers: { hello: "world" },
});

client
  .query({
    query: gql`
      query {
        fart
      }
    `,
  })
  .then(console.log);
```

It's set up to hit a temporary hookbin endpoint and pass along a `hello` HTTP header with value `world`. Hookbin receives the request, but there's no custom headers received at all:
<img width="1120" alt="Screen Shot 2021-10-24 at 6 17 22 PM" src="https://user-images.githubusercontent.com/226872/138621178-7605c90a-1f26-4c88-adbe-810dad0bd765.png">

**Versions**

```
  System:
    OS: macOS 11.6
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
  Browsers:
    Chrome: 95.0.4638.54
    Firefox: 93.0
    Safari: 15.0
  npmPackages:
    @apollo/client: ^3.4.16 => 3.4.16 
```

**Comment by david-keefe** [comment]
@samuela  Did you find a solution to this? I am facing the same issue.

**Comment by samuela** [comment]
no solution AFAIU

**Comment by GavanWilhite** [comment]
I encountered this issue, but it only seems to happen on Safari, not Chrome. I also switched to isomorphic-fetch, but that hasn't solved the issue either.

It works fine on first call, but when I do a `router.replace(router.asPath);`it fails to include the headers.

**Comment by jerelmiller** [comment]
@samuela I'm curious, if you move the `headers` into the `HttpLink` options, does it work? It looks like we only do something with that `headers` value passed directly to `ApolloClient` when you [provide no link](https://github.com/apollographql/apollo-client/blob/4b8823d6c9a82fe2d254215e925faf577907fa2b/src/core/ApolloClient.ts#L156). This would explain why you're not seeing headers. That `headers` value passed directly to the client is mostly a convenience if you don't pass a `link` to it.

Try this and see if you have better luck 🤞 :

```ts
const client = new ApolloClient({
  link: new HttpLink({ 
    uri: "https://hookb.in/xYjbyaxeOLh0nNxxnWpY", 
    headers: { hello: "world" },
    fetch 
  }),
  cache: new InMemoryCache(),
});
```

**Comment by david-keefe** [comment]
The above solution is what we used and it works as expected.
