### ISSUE TITLE
ios 15 xcode 13 and react native 63.4 error parse is not a function

### ISSUE THREAD

**Issue by alireza847-programmer** [apollographql/apollo-client#8971]
ERROR    TypeError: graphql.parse is not a function. (In 'graphql.parse(source, {
          experimentalFragmentVariables: experimentalFragmentVariables
        })', 'graphql.parse' is undefined)

**Comment by hwillson** [comment]
There really isn't enough info here for us to help troubleshoot. Please provide more details if you want our help.
