### ISSUE TITLE
Declaring prop with type `[String!]!` makes it also appear as `String` (possible bug?)

### ISSUE THREAD

**Issue by ItzaMi** [apollographql/apollo-client#8977]
I don't know if this is a bug or not but I would like, if possible, some clarification on why I'm having this issue.

I have an `images` that has a type `[String!]!` but when I try to map it, it appears that it can be of type `String`. On my `initialValues` I also have it as an `array` so I'm not fully understanding where this `String` comes from. If I step into the autogenerated files I can see that the typing can actually be of type `String` but why does this happen?

_Trying to map over `images` and seeing that it can be of type `String`_
<img width="611" alt="Screenshot 2021-10-28 at 10 04 00" src="https://user-images.githubusercontent.com/30603437/139252708-f1164ca0-39e1-4ae0-a554-ecefa4273226.png">

_Checking my `mutation` to confirm that I only have it as type `[String!]!`_
<img width="220" alt="Screenshot 2021-10-28 at 10 04 23" src="https://user-images.githubusercontent.com/30603437/139252715-fcdf3a1a-505d-422a-b1bf-752d873d4eab.png">

_A `useState` where the error could be coming from but I'm also declaring it as `['']`_
<img width="474" alt="Screenshot 2021-10-28 at 10 05 23" src="https://user-images.githubusercontent.com/30603437/139252718-c5498933-0862-4012-bcec-00189d4bdfca.png">

_The autogenerated variables for my mutation_
<img width="548" alt="Screenshot 2021-10-28 at 10 07 37" src="https://user-images.githubusercontent.com/30603437/139252721-8699f42a-deac-4861-87c8-6b5595db8ec5.png">

**Comment by brainkim** [comment]
@ItzaMi Yeah, this is a graphql-code-generator issue. Can you create an issue with your questions on that repository (https://github.com/dotansimha/graphql-code-generator/issues/new?assignees=&labels=&template=bug_report.md). I was going to copy it over myself, but I didn’t want to put words in your mouth.

Happy to follow along!
Brian

**Comment by ItzaMi** [comment]
@dylanwulf, thank you for the help. That made absolute sense!

@brainkim, as @dylanwulf pointed out, it seems like it's something that is already mentioned on the docs so it probably won't make much sense to create an issue for that. Anyway, thank you for the help! 🤘
