### ISSUE TITLE
Error in mounted hook: "TypeError: Cannot read properties of undefined (reading 'subscribeToMore')"

### ISSUE THREAD

**Issue by JavaScript7** [apollographql/apollo-client#9001]
Need help or want to talk all things Apollo Client? Issues here are reserved for bugs, but one of the following resources should help:

* Apollo GraphQL community forums: https://community.apollographql.com
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests

this.$apollo.queries.tags.subscribeToMore({
        document: gql`subscription{
          messages {
            data
            type
          }
        }`,
        variables: {},
        updateQuery: (previousResult, { subscriptionData }) => {
          console.log(previousResult)
        },
      })

**Comment by sapkra** [comment]
Have you found any solution for it yet? I'm having the same problem.

**Comment by bignimbus** [comment]
Hi @JavaScript7, we appreciate for your patience.  More information is needed to answer your question.  I suggest creating a reproduction using https://github.com/apollographql/react-apollo-error-template and opening a new issue if you still need support.  Our [community forum](https://community.apollographql.com/) is also a great place to ask questions and get answers from the community.  Thanks a bunch! 🙏🏻
