### ISSUE TITLE
Access to parent id in local-only fields

### ISSUE THREAD

**Issue by Notekunn** [apollographql/apollo-client#9002]
I have same problem with [Access to parent id in local-only fields](https://spectrum.chat/apollo/react-apollo/access-to-parent-id-in-local-only-fields~d71121a7-7edd-45cb-a4b0-cbfc3c8ebeaf)
I'm in the same situation but no solution found
Can anyone help me?
Thank you.

**Comment by JonathanCallewaert** [comment]
Hi, did you find a way to solve this?
