### ISSUE TITLE
ES module support for @apollo/client/utilities

### ISSUE THREAD

**Issue by tobiasdiez** [apollographql/apollo-client#9008]
**Intended outcome:**
Loading `@apollo/client/utilities` using esbuild / in a esm context works

**Actual outcome:**
The import `import { relayStylePagination } from '@apollo/client/utilities/policies/pagination'` for example leads to 
```
node:7012) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
D:\Programming\JabRefOnline\node_modules\@apollo\client\utilities\globals\maybe.js:1
export function maybe(thunk) {
^^^^^^

SyntaxError: Unexpected token 'export'
```

**How to reproduce the issue:**

**Versions**

The `envinfo` command failed with an `EWORKSPACESCONFIG` error, but I'm using the latest version of apollo client: `"@apollo/client@^3.4.16"`

**Comment by rosskevin** [comment]
May be related to https://github.com/apollographql/apollo-client/pull/9697

**Comment by alessbell** [comment]
Closing as a duplicate of https://github.com/apollographql/apollo-feature-requests/issues/287.
