### ISSUE TITLE
I am getting {"statusCode":400,"error":"Bad Request","message":"Invalid cookie value"}

### ISSUE THREAD

**Issue by bdanzer** [apollographql/apollo-client#9023]
I have all the correct things set up here is what my server looks like:

```javascript
  return apolloServer.createHandler({
    expressGetMiddlewareOptions: {
      cors: {
        origin: ['http://localhost:8080', 'https://studio.apollographql.com'],
        credentials: true,
      },
    }
  })(event, context, callback)
```

this is how I define the cookie with setting sameSite to none and secure to true
```javascript
    setCookies.push({
      name: "cookieName",
      value: "cookieContent",
      options: {
        // expires: moment().add(1, 'hours').format(),
        httpOnly: true,
        maxAge: 3600,
        path: "/",
        sameSite: 'none',
        secure: true
      }
    });
```

I also enabled cookies to be sent in studio. So when I make a request with studio apollo graphql things work as expected where the http only cookie I have is saving to chrome.

here is my reqest headers:

```http
accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Content-Length: 1523
content-type: application/json
Cookie: g_state={"i_l":0}; cookieName=cookieContent
Host: localhost:3000
Origin: http://localhost:8080
Referer: http://localhost:8080/
sec-ch-ua: "Google Chrome";v="95", "Chromium";v="95", ";Not A Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
```

For some reason in apollo client I get this response:

```javascript
{"statusCode":400,"error":"Bad Request","message":"Invalid cookie value"}
```

On the client side this is what I have:

```javascript
const link = new HttpLink({
  uri: process.env.REACT_APP_GRAPH_QL_URI,
  credentials: 'include'
});
const client = new ApolloClient({
  cache,
  link
});
```

After hours of googling I am puzzled as to why I get this error on client side but everything works as expected for the studio site.

Is it because of `g_state={"i_l":0}`? I am using the new google one tap

**Comment by bdanzer** [comment]
Ok after looking into it a bit more it looks like it was due to serverless-offline package. It uses hapi and I had to use the flag `--disableCookieValidation` like so `serverless offline --disableCookieValidation` and fixed my issue. Sort of strange to be honest that a cookie like this could cause such an error

**Comment by brainkim** [comment]
@bdanzer Sorry I didn’t get a chance to respond, and glad you figured it out!
