### ISSUE TITLE
[AC3] hard to migrate 

### ISSUE THREAD

**Issue by wanchaiS** [apollographql/apollo-client#9033]
Hi, based on this issue that was closed #6808 

I still think it would be nice if we have an option as @chenesan suggested from the first place, in our large project we have graphtypes that do not have an id as the author shown in example, even we follow the possibleTypes approach still now we have to maintain the list. Even if we have the auto generation for the list into json file the logic to determine which graphtype to merge cannot be explicit..

i think the suggestion really makes sense.

**Comment by richardscarrott** [comment]
Hi @wanchaiS I'm migrating from AC2 -> AC3 and running into some of the same concerns.

I'm currently generating a list of "mergeable" types with this logic:

```
  const response = await fetch(`${process.env.SCHEMA}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      variables: {},
      query: `
      {
        __schema {
          types {
            kind
            name
            fields {
              name
            }
          }
        }
      }      
          `
    })
  });
  const result = await response.json();
  const mergeableTypes = result.data.__schema.types
    .filter(({ kind }: any) => kind === 'OBJECT')
    .filter(
      ({ fields }: any) =>
        !fields.some(({ name }: any) => ['id', '_id'].includes(name))
    )
    .map(({ name }: any) => name);
  await fs.writeFile(DEST, JSON.stringify(mergeableTypes));
```

They're then all set to `merge: true` in the AC cache. It makes the assumption that primary keys always live under `id` or `_id` which is true for our API. However, this spits out 200+ types which I can't imagine I'd have considered had we defined these manually from the start.

For example, root types and relay-style connections:

```json
[
 // I'd have never considered these.
"Query",
 "Mutation",
 "SellersConnection",
 "SellersEdge",
 "SellersPageInfo",
 "__Schema",
 "__Type",
 "__Field",
 "__InputValue",
 "__EnumValue",
 "__Directive",
 // ...etc.
 // But these are more obvious "generic" types I was going to manually define anyway.
 "Price",
 "Image",
 "Cta",
  // ...etc.
}
```

It seems ok so far and given the fact AC3 will only attempt to merge if the value occupies "the same field of the same parent" I can't think where the above would fail.

However, I'm by no means confident my logic is correct and I'm concerned there'll be scenarios whereby this will fail 🤔

**Comment by alessbell** [comment]
Hi @wanchaiS 👋 Thanks for opening this issue, and thanks to @richardscarrott for sharing the approach you've taken here.

I'm doing some clean-up of old issues, and while I understand the pain point here, I don't think we will be putting a feature to address this on the roadmap. For that reason, I'm going to go ahead and close this issue, but would encourage you both to join our [Discord](https://discord.gg/graphos) and feel free to open a new issue for any other concerns in the future. Thanks!
