### ISSUE TITLE
@apollo/client3.4.17 : HttpLink uri does not accept  URL (Heroku) : Network request failed

### ISSUE THREAD

**Issue by nwabdou85** [apollographql/apollo-client#9047]
I tried to connect my client with server used localhost or xxxxx.herokuapp.com without success

**Intended outcome:**
the goal was to query my distant server on heroku using url , as heroku has no static adress, here code

`
const httpLink = new HttpLink({uri:DISTANT_SERVER_URL})
const authLink = new ApolloLink(async (operation, forward) => {
  const token = await getToken();
  operation.setContext(({ headers }) => ({ 
    headers: {
    authorization: token?`Bearer ${token}`:null,
    ...headers
  }}
 )
);
  return forward(operation);
});
`

**Actual outcome:**
I can't access and get as error: 
Network request failed

**Versions**

`  System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 12.1.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Safari: 13.1.2
  npmPackages:
    @apollo/client: ^3.4.17 => 3.4.17 
`

Can help on this please

**Comment by hkhawar21** [comment]
Were you able to find a workaround for this? I am also facing a similar error where network requests are failing using Apollo Client but not in Postman.

**Comment by jerelmiller** [comment]
Hey @nwabdou85 and @hkhawar21 👋 

Would you be able to provide a bit more context here? I'm afraid the above is not quite enough information to help figure out what is going on. What does your `ApolloClient` look like? Are you ordering the `httpLink` after the `authLink` in your link chain? Any more context would be super helpful to help figure out whats going on. Thanks!

**Comment by jerelmiller** [comment]
Alternatively, a reproduction would be super helpful as well!

**Comment by hkhawar21** [comment]
Its working for dev server but not for the production server. Here is the code below

function createApolloClient() {
  const localHost = process.env.API_LOCALHOST;
  const buildHost = process.env.API_HOST;

  const hostname = __DEV__ ? localHost : buildHost;

  const httpLink = new HttpLink({
    uri: `${hostname}/graphql`,
  });

  const authLink = setContext(async (_, { headers }) => {
    const token = await getTokenFromLocalStorage();
    return {
      headers: {
        ...headers,
        authorization: token ? `Bearer ${token}` : "",
      },
    };
  });

  return new ApolloClient({
    cache: new InMemoryCache(),
    link: authLink.concat(httpLink),
  });
}

**Comment by jerelmiller** [comment]
@hkhawar21 would you go into a bit more detail in what you mean by "not working"? Are the network calls not being made? Is the endpoint rejecting your request, etc?

Just to make sure this is Apollo client and not the server itself, are you able to call that endpoint using plain `fetch` with the auth token? Something like the following should see if you're able to at least query the server (add any additional headers as needed):

```js
const query = `
  query { ... }
`

getTokenFromLocalStorage()
  .then((token) => {
    return fetch(`${process.env.API_HOST}/graphl`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        authorization: token ? `Bearer ${token}` : ""
      },
      body: JSON.stringify({ query })
    })
  })
  .then((res) => res.json())
  .then((data) => console.log(data))
```

**Comment by alessbell** [comment]
Without more information it's difficult to say what the issue is here. For general troubleshooting, feel free to start a thread on our [Discord server](https://discord.gg/graphos) and/or open a new issue with reproduction steps to report a bug. Thanks!
