### ISSUE TITLE
Error: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.

### ISSUE THREAD

**Issue by Tjerk-Haaye-Henricus** [apollographql/apollo-client#9051]
Hey there :)

I'm triing to upload an image with apollo-client and apollo-upload-client.
But its not working.

`
import { ApolloClient, InMemoryCache, from, ApolloLink } from '@apollo/client';
import { onError } from "@apollo/client/link/error";

import { createUploadLink } from 'apollo-upload-client';

const errorLink = onError(({ graphQLErrors, networkError }) => {
  if (graphQLErrors)
    graphQLErrors.map(({ message, locations, path }) =>
      // eslint-disable-next-line no-console
      console.log(
        `[GraphQL error]: Message: ${message}, Location: ${JSON.stringify(locations)}, Path: ${path}`,
      ),
    );

  // eslint-disable-next-line no-console
  if (networkError) console.log(`[Network error]: ${networkError}`);
});

const link = from([
  errorLink,
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  createUploadLink(),
]);

// Create the client as outlined in the setup guide
const client = new ApolloClient({
  cache: new InMemoryCache(),
  link,
});

export default client;`

`const uploadImage = (mutation: DocumentNode) => async (file: unknown, areas?): Promise<IResource> => {
  try {
    const { data } = await client.mutate({
      mutation,
      variables: {
        file,
        areas,
      },
    });
    return data.uploadImage;
  } catch (error) {
    console.log(error);
  }
}`

**Intended outcome:**
Should upload image

**Actual outcome:**

![image](https://user-images.githubusercontent.com/44015586/141494531-7708dd72-4e59-46f3-985e-c1c2e434750c.png)

**How to reproduce the issue:**

**Versions**
  System:
    OS: macOS 11.6
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 3.0.0 - /usr/local/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Firefox: 93.0
    Safari: 15.0
  npmPackages:
    @apollo/client: ^3.4.16 => 3.5.2 
    apollo-upload-client: ^16.0.0 => 16.0.0

**Comment by Tjerk-Haaye-Henricus** [comment]
Some times this  error occoured too
`TypeError: "selectionSet" is read-only
    visit visitor.mjs:143
    node_modules vendors-node_modules_apollo-upload-client_public_createUploadLink_js-node_modules_apollo_clie-eae5ac-c5947106c0f7fb824220-bundle.js:9782
    node_modules vendors-node_modules_apollo-upload-client_public_createUploadLink_js-node_modules_apollo_clie-eae5ac-c5947106c0f7fb824220-bundle.js:3770
    node_modules vendors-node_modules_apollo-upload-client_public_createUploadLink_js-node_modules_apollo_clie-eae5ac-c5947106c0f7fb824220-bundle.js:6959
    node_modules vendors-node_modules_apollo-upload-client_public_createUploadLink_js-node_modules_apollo_clie-eae5ac-c5947106c0f7fb824220-bundle.js:6733
    step tslib.es6.js:102
    verb tslib.es6.js:83
    __awaiter tslib.es6.js:76
    __awaiter tslib.es6.js:72
    node_modules vendors-node_modules_apollo-upload-client_public_createUploadLink_js-node_modules_apollo_clie-eae5ac-c5947106c0f7fb824220-bundle.js:6723
    node_modules vendors-node_modules_apollo-upload-client_public_createUploadLink_js-node_modules_apollo_clie-eae5ac-c5947106c0f7fb824220-bundle.js:5488
    _callee$ uploadImage.ts:6
    Babel 8
    _callee$ useCreateInstitution.ts:11
    Babel 8
    onSubmit Form.js:11
    React 19`

**Comment by dmitry** [comment]
@Tjerk-Haaye-Henricus have you found an issue?

**Comment by dmitry** [comment]
Seems like this one: https://github.com/jaydenseric/apollo-upload-client/pull/274

**Comment by Tjerk-Haaye-Henricus** [comment]
Yes its the one. I think it will be merged soon :) I‘ve closed that issue :)
