### ISSUE TITLE
TypePolicy seems to be missing keyArgs

### ISSUE THREAD

**Issue by unluckynelson** [apollographql/apollo-client#9062]
https://github.com/apollographql/apollo-client/blob/febbba984d2ed0ff1945fc1f57ddf45c02ade07b/src/cache/inmemory/policies.ts#L108

According to the docs https://www.apollographql.com/docs/react/pagination/core-api/ a Query property should be available on the TypePolicy type but is not

Property 'Query' is incompatible with index signature.

**Comment by benjamn** [comment]
_Field_ policies can have `keyArgs`, but _type_ policies have [`keyFields`](https://www.apollographql.com/docs/react/caching/cache-configuration/#customizing-cache-ids).

Field policies go in the `fields` subsection of the `TypePolicy` object:
```ts
new InMemoryCache({
  typePolicies: {
    Query: { // Type policy for the Query object
      fields: {
        someField: { // Field policy for the Query.someField field
          keyArgs: [...],
        },
      },
    },
  },
})
```

More discussion in https://github.com/apollographql/apollo-client/issues/8021#issuecomment-948067340 if you're curious why it doesn't make sense to configure `keyArgs` for an object type.
