### ISSUE TITLE
Unknown arguments in Apollo/client but works fine in playground

### ISSUE THREAD

**Issue by mahady-manana** [apollographql/apollo-client#9080]
Hi everyone !

graphql @15.16.1
@apollo/client @ 3.4.17

In the client side, I have a mutation to update data like this : 

```
mutation EditCategory(
      $id: String
      $name: String
      $code: String
      $parentId: String
      $description: String
    ) {
      editCategory(
        id: $id
        name: $name
        code: $code
        parentId: $parentId
        description: $description
      ) {
       ...
      }
 }
```
In Apollo Server I have this : 

```
export const mutation = new GraphQLObjectType({
  name: "Mutation",
  fields: {
    editCategory: {
      type: CategoryType,
      args: CategoryUpdateInput,
      resolve: async (_, args) => {
        const { id, name, code, description, parentId } = args;
        try {
          const cat = await Category.findByIdAndUpdate(id, {
            name,
            code,
            description,
            parentId,
          }).exec();

          return cat;
        } catch (error) {
          return new ApolloError("UPDATE_ERROR");
        }
      },
    },
  },
});
```
Args Type of update :

```
const CategoryUpdateInput = {
  id: { type: GraphQLString! },
  name: { type: GraphQLString },
  description: { type: GraphQLString },
  parentId: { type: GraphQLString },
  code: { type: GraphQLString },
};
```
**Whenever I try to run the mutation in the Apollo  Studio Sandbox, It works fine.
But whenever I run in my App, an error occured**

``` Unknown arguments `id` on field  `Mutation.editCategory` ```

If need : 

Mongoose Schema:

```
const CategorySchema = new Schema({
  name: String,
  photo: String,
  code: String,
  description: String,
  parentId: String,
  created: Date,
});
```
Can Anyone Explain What is wrong here ?

**Comment by brainkim** [comment]
Do you have a stack trace of the error? That would help us identify where the `Unknown arguments` error is being thrown from.

**Comment by mahady-manana** [comment]
Thank  you @brainkim , 
I solved myself the error.
Possible error :  
*In my `CategoryUpdateInput` , I add _id_  but i my schema there is no attr _`id`_ , I think apollo look at the schema and if the Input prop have a name other than in the Schema, It raise an error*

Just my thought !

**Comment by brainkim** [comment]
@mahady-manana Glad to hear. Sorry I couldn’t get back to you in time. If you have any other questions, please feel free to ping me here or in another issue.

Closing for housekeeping purposes.
