### ISSUE TITLE
[Unhandled promise rejection: Error: undefined is not an object (evaluating 'this.data')]

### ISSUE THREAD

**Issue by cavishek39** [apollographql/apollo-client#9095]
**Intended outcome:**
The cache is not being updated after the mutation.

**Actual outcome:**

![image](https://user-images.githubusercontent.com/71460522/142895205-772180b8-2ba6-41e2-9284-42c95334758c.png)

**How to reproduce the issue:**

After the mutation run, when I'm trying to update the cache data and modify the object that's when I'm facing the issue, also because of this the onCompleted method didn't give any response.

**Versions**

npx: installed 1 in 2.059s

  System:
    OS: Linux 5.4 Linux Mint 20.1 (Ulyssa)
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.45
    Firefox: 94.0
  npmPackages:
    @apollo/client: 3.4.17 => 3.4.17

**Comment by bignimbus** [comment]
Hi @cavishek39 👋🏻  do you still need support here?  If so, I'm sure the community can help narrow down what might be going on.  More details will be necessary though - can you provide a runnable reproduction?  [This template](https://github.com/apollographql/react-apollo-error-template/generate) should help.  Thanks a bunch!
