### ISSUE TITLE
resetStore() doesn't work after React upgrade to 17.0.2

### ISSUE THREAD

**Issue by ageorgi87** [apollographql/apollo-client#9106]
**Intended outcome:**

I would like to upgrade react from version 16.14.0 to version 17.0.2
Since I did, the function resetStore (https://www.apollographql.com/docs/react/api/core/ApolloClient/#ApolloClient.resetStore) doesn't seems to work anymore.
More specifically, it seems to be the reFetchObservableQueries function, called by resetStore(), which seems to block.

**Actual outcome:**

When I sign out from a session on my application, the resetStore function is called. 
It used to work perfectly fine but since the react update, the code reading stops at the resetStore function.

My code : 
![Capture d’écran 2021-11-23 à 14 33 43](https://user-images.githubusercontent.com/62748924/143034368-a9956c96-0609-4c6c-b5aa-ef5593b06892.png)

My console : 
![Capture d’écran 2021-11-23 à 14 37 32](https://user-images.githubusercontent.com/62748924/143034415-dbe036e3-928d-4a4a-919a-d191f484672b.png)
![Capture d’écran 2021-11-23 à 14 38 29](https://user-images.githubusercontent.com/62748924/143034435-f43a9e97-4d42-46db-a4a5-b69389662f0f.png)

**Versions**

System:
    OS: macOS 11.6
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.19.1 - ~/.nvm/versions/node/v14.17.6/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Safari: 15.1
  npmPackages:
    @apollo/react-hooks: ^3.0.1 => 3.1.5 
    apollo-cache-inmemory: ^1.2.9 => 1.6.6 
    apollo-client: ^2.4.1 => 2.6.10 
    apollo-link-http: ^1.5.4 => 1.5.17 
    react-apollo: ^3.0.1 => 3.1.5 

Thanks for your help !

**Comment by benjamn** [comment]
@ageorgi87 It looks like you're still using Apollo Client v2 (`apollo-client` and `apollo-cache-inmemory` have been replaced by the unified `@apollo/client` package in AC3, as described in the [migration guide](https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/#updating-imports)).

To be honest with you, while we are actively chasing the React team's latest developments with AC3 (#8365, #8458, #8245, etc.), we have no plans to update the old AC2 packages to work with the latest versions of React. If you have time to dig into the problem and you can come up with a specific change you'd like to see back-ported to AC2, we might consider it, but I can't promise you I/we can spend much time on this.

**Comment by bignimbus** [comment]
Hi all, I'll close this thread for lack of actionable items for the team.  Thanks a bunch!
