### ISSUE TITLE
When does identify method on client cache returns undefined

### ISSUE THREAD

**Issue by KatFishSnake** [apollographql/apollo-client#9110]
Hi, a bit of a new Apollo user, please don't judge harshly 😃,
recently we had a bit of a discussion at work where a cache method `cache.identify` always returns a string, 
regardless what nonsense you put as an id (we are not using custom identifiers just a good old `id` field) as long as you put an `id` and a `__typename` it will create an id if it doesn't exists.

But the TS type of the return of this function is `string | undefined` [link to code](https://github.com/apollographql/apollo-client/blob/main/src/cache/core/cache.ts#L104)

Why `cache.identify` is expected to return undefined, how can it be reproducible. Is it perhaps for custom cache IDs?

Example code

```javascript
import { useApolloClient } from '@apollo/client'

const client = useApolloClient()

client.cache.identify({ __typename: 'Issue', id: 'some-random-string-or-a-valid-id' })
```

Any help would be appriciated!

**Comment by dylanwulf** [comment]
It can return undefined if either `id` or `__typename` is not present. Also, if you define a custom `keyFields` function in your type policies then `identify` will call your custom `keyFields` function which could potentially return undefined.

**Comment by benjamn** [comment]
Echoing what @dylanwulf independently said, if you pass an object to `cache.identify` that doesn't have a `__typename`, or doesn't have the expected key fields (`id` by default, or whatever you configure with [`keyFields`](https://www.apollographql.com/docs/react/caching/cache-configuration/#customizing-cache-ids), then the cache can't/won't be able to identify the object.

Thanks to the default [`dataIdFromObject`](https://www.apollographql.com/docs/react/caching/cache-configuration/#dataidfromobject) handler, pretty much any object with a `__typename` string and `id` field can be identified, but `cache.identify` can return undefined if either of those fields is missing, or we expect something other than `id` as the primary key field(s).

**Comment by KatFishSnake** [comment]
🙏 thanks @benjamn @dylanwulf, this is a great help 🙏
