### ISSUE TITLE
As of 3.5.0, useMutation onCompleted doesn't have the expected lexical scope

### ISSUE THREAD

**Issue by doytch** [apollographql/apollo-client#9111]
[I've created a repo based on the `react-apollo-error-template`](https://github.com/doytch/apollo-onCompleted-error/blob/main/src/index.jsx#L113-L156). In it, there's a snippet that looks like so:

```
function App() {
  const [name, setName] = useState("");
  const [counter, setCounter] = useState(0);
  const { loading, data } = useQuery(ALL_PEOPLE);

  const [addPerson] = useMutation(ADD_PERSON, {
    onCompleted: (data) => {
      console.log(`Mutation Completed with counter at: ${counter}`);
    },
    {...}
    },
  });

  console.log(`Counter in render() is at ${counter}`);

  return (
    <main>
       {...}
        <button
          onClick={() => {
            setCounter((counter) => counter + 1);
            setName("");
            addPerson({ variables: { name } });
          }}
        >
          Add person
        </button>
        {...}
     </main>
  );
}
```

**Intended outcome:**
Before v3.5.0 (have confirmed with 3.4.16), the value of `counter` inside the `onCompleted` callback would be the latest value. I.e., we'd see a console.log of `Mutation Completed with counter at: 3` after the third person was added.

Screenshot with 3.4.16
<img width="1439" alt="Screen Shot 2021-11-23 at 2 24 18 PM" src="https://user-images.githubusercontent.com/5324374/143090332-58fc153c-dd24-41b3-80bd-8e8f2b4cbabf.png">

**Actual outcome:**
As of v3.5.0, the value of `counter` inside the `onCompleted` callback stays at 0.

Screenshot with 3.5.4
<img width="1450" alt="Screen Shot 2021-11-23 at 2 16 42 PM" src="https://user-images.githubusercontent.com/5324374/143090281-34bd935b-ee92-4f85-9c36-71d1328989a3.png">

**How to reproduce the issue:*
See repro fork here: https://github.com/doytch/apollo-onCompleted-error/blob/main/src/index.jsx#L113-L156

Note that to test with v3.4.16, I had to drop the `graphql` dependency down to `^15.0.1`

**Versions**
  System:
    OS: macOS 11.6.1
  Binaries:
    Node: 16.7.0 - ~/.nvm/versions/node/v16.7.0/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v16.7.0/bin/yarn
    npm: 7.20.3 - ~/.nvm/versions/node/v16.7.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Firefox: 93.0
    Safari: 15.1
  npmPackages:
    @apollo/client: ^3.5.4 => 3.5.4

**Comment by julienfouilhe** [comment]
I had the same problem so I tried `3.6.0-beta.3` and it seems to be fixed in there!

**Comment by bojant987** [comment]
I have the same problem. Ie, after a refund I run cancel subscription, if checkbox "cancel subscription" is checked. However, checking or unchecking checkbox stopped making a difference, it's always default value from state.    

```
onCompleted: async () => {
	if (isSubscription) { // always false, even when we run setIsSubscription(true) beforehand
		await cancelSubscription(order);
	} else {
		toast.success(toastCopy.refund.SUCCESS);
		onRefundComplete();
	}
},
 ```

**Comment by eduleite** [comment]
I started having similar issues when I updated to 3.5. Before it seemed like with each render the onCompleted was updated internally and now it is not the case anymore. They did tell that the internal handling of onCompleted did change.

**Comment by doytch** [comment]
Seems like this has affected a few others, I'm glad I'm not the only one expecting this behaviour! 😆 Anyway yeah, it'd be nice to know whether this is viewed as a bug or a won't-fix by the Apollo team. In the short-term we can easily just pin to `3.4.x` versions but guidance for the future would be great, since the workarounds in 3.5.x for our particular scenario that I've come up with so far are pretty ugly.

**Comment by josepgomes** [comment]
@doytch with 3.4.0 i still have the same problem. I even tried with 3.0.0. I was using the old apollo-client (version 2.x). All versions in the "new" @apollo/client repo (since version 3) have this problem...

**Comment by julienfouilhe** [comment]
@josepgomes No I don't have this problem on the 3.4 branch

**Comment by josepgomes** [comment]
I tried with v3.4.16, and drop the graphql dependency down to v15.0.1. My state variable is still with the default value when the onCompleted runs. But if i check the value outside the callback is already updated. The app was working fine until i update apollo-client from version 2.

**Comment by eduleite** [comment]
@doytch as I see the current implementation is not calling the last rendered onCompleted reference. Seens like it captures the first render instance and in future renders the check in line 50 always returns true and returns the first created instance of the mutation method. Even if this is fixed, the way it it is implemented will always have the last captured state of the useState variable when the mutation is executed, and it will always stay behind by 1 in your example. The mutation should use the ref state to call the onCompleted and not "capture" the onCompleted closure and use it

**Comment by doytch** [comment]
> @doytch with 3.4.0 i still have the same problem. I even tried with 3.0.0. I was using the old apollo-client (version 2.x). All versions in the "new" @apollo/client repo (since version 3) have this problem...

Any chance it's something different? In my issue description I included a link to my forked reproduction template repo. You should be able to confirm that using 3.4x and 3.5.y versions give you different results as Julien and I have said.

**Comment by Kn3cht** [comment]
I'm facing the same problem using versions < 3.5.x:
@apollo/client v3.3.4
apollo-client v2.6.10
graphql v15.4.0

yarn v1.22.17
node v16.7.0

**Comment by mmahalwy** [comment]
Im running into the same problem with queries, where changing the variables till fire the query but with old data

**Comment by steinaragustli** [comment]
Is this really fixed in #9144 @brainkim ?

Im running into issues with onComplete. The react function which i am using a useMutation hook has a state defined with useReducer, and when onComplete is fired then inside that scope the state is stale. Im using apollo client 3.5.8.

**Comment by FahmyChaabane** [comment]
Oh god, and i thought i got crazy.. Spent almost two nights tryin'a understand the behaviour. 
YES ! i'm using useLazyQuery, and i am setting a state in onComplete callback, it def does not mutate the state.
I saved the issue with async/await approach. ther is some issue with onComplete callback.

**Comment by FahmyChaabane** [comment]
Please tell me if this is related to what i am facing.. 
I am using useLazyQuery, and i am mutating a state within onComplete callback, it does not mutate the state.
To be more precise, it does not mutate the state, when the query result is already in the cache. (it state is mutated when the data request is not yet saved in the cache).
onComplete does indeed bring the right data within the callback, but useStateAction does not mutate the state.

I solved the issue with async/await approach. there is some issue with onComplete callback.
