### ISSUE TITLE
TypeError: setValue is not a function; 

### ISSUE THREAD

**Issue by prakashseervi** [apollographql/apollo-client#9115]
**Intended outcome:**

**Actual outcome:**

**How to reproduce the issue:**

**Versions**

Description:
After updating Package getting issue of TypeError: setValue is not a function; 
We are using onComplete function in useQuery hook. This issue is generated due to onComplete call before code render. and due to this getting this issue attaching  images for more ref.
![image](https://user-images.githubusercontent.com/66736395/143227705-24f1b835-01fb-47ee-b529-bb00f76fda06.png)

Problem is in this code:

![image](https://user-images.githubusercontent.com/66736395/143227744-858bac1b-6872-430b-a49d-ce533bfd004d.png)

**Comment by julienfouilhe** [comment]
Could this be related to https://github.com/apollographql/apollo-client/issues/9111?

**Comment by prakashseervi** [comment]
> Could this be related to #9111?

Yaa..!! I am getting same issue on useQuery. I checked both code file useQuery.js and useMutation.js and code is almost similar and getting error on same code. 

`    if (result.error) {
                (_a = options.onError) === null || _a === void 0 ? void 0 : _a.call(options, result.error);
            }
            else if (result.data) {
                (_b = options.onCompleted) === null || _b === void 0 ? void 0 : _b.call(options, result.data);
            }
`

this code is problematic.

**Comment by benjamn** [comment]
@prakashseervi (and others) What version of `@apollo/client` are you using? What previous version (if any) worked before this? The changes from #9111 will be released in the next patch version of `@apollo/client`, likely v3.5.6.

**Comment by prakashseervi** [comment]
> @prakashseervi (and others) What version of `@apollo/client` are you using? What previous version (if any) worked before this? The changes from #9111 will be released in the next patch version of `@apollo/client`, likely v3.5.6.

I am using v3.2.0
