### ISSUE TITLE
Queries with array results not returning deeply nested objects 

### ISSUE THREAD

**Issue by Bariah96** [apollographql/apollo-client#9117]
Having the following InMemoryCache configuration using apollo client 3.4.8 : 

```
const cache = new InMemoryCache({
      addTypename: true,
      typePolicies: {
        Factory: {
          keyFields: ['pk', 'sk'],
        },
        Query: {
          fields: {
            ///////
            getItem: {
              read(cachedValue, { args /*as GetFactoryQueryVariables*/, toReference }) {
                  return cachedValue || toReference({ __typename: 'Factory', pk: args?.pk, sk: args?.sk });
              },
            },
            ///////
            listItems: {
              keyArgs: ['pk', 'sk', 'filter'],
              merge: mergeItems,
              read: readItems,
            },
          },
        },
      },
    });
```
```
function mergeItems(
      existing: ItemsCache,
      incoming: ModelConnection,
      { readField, args }: FieldFunctionOptions,
    ) {
      if (!incoming) return;

      const itemsMap = existing ? { ...existing.itemsMap } : {};
      incoming.items?.forEach(item => {
        if (item) {
          itemsMap[readField<string>('sk', item)!] = item;
        }
      });

      return {
        cursor: incoming.nextToken,
        itemsMap,
      };
    }
```
```
readItems function is just returning an array of references, nothing extra special ...
```

Factory object include nested types, each nested type has an id field. and so when I checked Apollo Client Devtools, indeed each object has its unique identifier inside the cache.

Now when calling the list queries (returning an array of Factory objects) i'm not getting the THIRD-LEVEL-NESTED objects within the Factory object. although when calling getItem I'm getting the whole object ...

Expected behavior: Getting the whole objects including the deeply nested ones on both queries ...

**Comment by benjamn** [comment]
@Bariah96 Can you share the query you're using to read/write these fields?

**Comment by Bariah96** [comment]
> @Bariah96 Can you share the query you're using to read/write these fields?

sorry the issue was with the queries auto-generated, the generation was stopping on a certain depth when it comes to list queries ..

It wasn't an apollo issue .. The issue can be closed :)

**Comment by benjamn** [comment]
Thanks for the update @Bariah96!
