### ISSUE TITLE
React--Native: Metro has encounter an error: While trying to resolve module

### ISSUE THREAD

**Issue by pramodpariharPK** [apollographql/apollo-client#9119]
Metro has encountered an error: While trying to resolve module **`@apollo/client`** from file `/Users/admin/Documents/MySelf/Projects/React-Native/Latest/MyProj/index.js`, the package `/Users/admin/Documents/MySelf/Projects/React-Native/Latest/MyProf/node_modules/@apollo/client/package.json` was successfully found. **However, this package itself specifies a `main` module field that could not be resolved** (`/Users/admin/Documents/MySelf/Projects/React-Native/Latest/MyProf/node_modules/@apollo/client/main.cjs`. Indeed, none of these files exist:

  * /Users/admin/Documents/MySelf/Projects/React-Native/Latest/MyProj/node_modules/@apollo/client/main.cjs(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * /Users/admin/Documents/MySelf/Projects/React-Native/Latest/MyProj/node_modules/@apollo/client/main.cjs/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
![Screen Shot 2021-11-25 at 1 48 05 PM](https://user-images.githubusercontent.com/12712340/143405166-68e56db2-5170-4e9e-8736-3cb9779f3bb0.png)

GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start

**Comment by param-finder** [comment]
Same error!
![Simulator Screen Shot - iPhone 12 - 2021-11-25 at 15 59 47](https://user-images.githubusercontent.com/92723723/143425050-0177595b-95a0-428e-bec1-b757514a4ad2.png)

**Comment by azuken** [comment]
Workaround until fix : 

Add cjs extension in metro.config.js

```js
module.exports = (() => {
  return {
    resolver: {
      sourceExts: ['cjs'],
    },
  }
})()
```

**Comment by param-finder** [comment]
Yeah, found this in changelog. 
https://github.com/apollographql/apollo-client/blob/v3.5.5/CHANGELOG.md#apollo-client-354-2021-11-19

**Comment by almsx** [comment]
The solution at the moment:

Make a forced downgrade to version 3.4.13 so that it can work correctly.

Greetings,
Alberto

**Comment by pramodpariharPK** [comment]
Thanks All:
Added metro-config.js file in the root folder with the below content, and it WORKED!!!... 

const {getDefaultConfig} = require('metro-config');
const {resolver: defaultResolver} = getDefaultConfig.getDefaultValues();
exports.resolver = {
  ...defaultResolver,
  sourceExts: [...defaultResolver.sourceExts, 'cjs'],
};
