### ISSUE TITLE
fragments which use interface are cut out

### ISSUE THREAD

**Issue by JulianZschieschang** [apollographql/apollo-client#9121]
I'm trying to use fragments to minimize code duplication, I noticed a strange behavior on apollo's side.
When I use inline fragments to distinguish between different types I use an interface which is implemented in the corresponding type. The graphql response works as expected, but apollo cuts out the fragments that use the interface.

**Intended outcome:**
_GraphQL Response_
````
{
    product: {
        name: "MainProductName"
        sku: "MainProductSKU"
        __typename:"MainProduct"
    }
}
````
_Apollo Response_
````
{
    product: {
        name: "MainProductName"
        sku: "MainProductSKU"
        __typename:"MainProduct"
    }
}
````

**Actual outcome:**
_GraphQL Response_
````
{
    product: {
        name: "MainProductName"
        sku: "MainProductSKU"
        __typename:"MainProduct"
    }
}
````
_Apollo Response_
````
{
    product: {
        name: "MainProductName"
        __typename:"MainProduct"
    }
}
````

**How to reproduce the issue:**
_schema_
````
interface ProductInterface {
    name: String
    sku: String
}

type MainProduct implements ProductInterface {
    name: String
    sku: String
}

type SecondaryProduct implements ProductInterface {
    name: String
    sku: String
}
````
_request query_
````
query getProduct {
    product {
        ... on MainProduct {
            name
            ...ProductData
        }}
}

fragment ProductData on ProductInterface {
    sku
}
````

**Versions**
  System:
    OS: Linux 4.4 CentOS Linux 8
  Binaries:
    Node: 14.17.5 - /usr/bin/node
    npm: 6.14.14 - /usr/bin/npm
  npmPackages:
    @apollo/client: ^3.4.16 => 3.4.16
    apollo-link-timeout: ^4.0.0 => 4.0.0
    apollo3-cache-persist: ^0.13.0 => 0.13.0

**Comment by benjamn** [comment]
@JulianZschieschang Are you providing [`possibleTypes`](https://www.apollographql.com/docs/react/data/fragments/#using-fragments-with-unions-and-interfaces) to your `InMemoryCache` constructor?
```ts
new InMemoryCache({
  possibleTypes: {
    ProductInterface: ["MainProduct", "SecondaryProduct"],
  },
  // ...other options...
})
```

**Comment by JulianZschieschang** [comment]
@benjamn That was the problem, now it works. Thanks for the help.
