### ISSUE TITLE
Cannot readQuery and writeQuery insite a Apollo subscription's response function

### ISSUE THREAD

**Issue by FlorianDietzDresden** [apollographql/apollo-client#9125]
Hello,
I am developing an application with apollo in react. My goal is to update some query data with data from a subscription without redoing a server request.

In my approach (see code below) I am trying to read the query data by cache.readQuery using the cache parameter provided in the subscription's response function. But the return value is always null.

What am I doing wrong?

Is it possible to update the cache this way and use cache.readQuery after a subscription?

(Hint: I know about cache.modify. However when I tried to implement that I had some problems with unintendedly updating queries. So I decided to try out cache.writeQuery.)

```
import React from 'react';
import { Query } from '@apollo/client/react/components';
import { useSubscription } from '@apollo/client';

import { buildEventsQueryFromFilters } from 'utils';
import { EVENTS } from 'graphql/queries';

// events looks like this
// const EVENTS = gql`
// 	query searchEvents($max: Int, $offset: Int, $sortings: [Sorting], $searchQuery: SearchQueryInput!, $includeEventAds: Boolean = true) {
// 		searchEventsBySearchParams(max: $max, offset: $offset, sortings: $sortings, searchQuery: $searchQuery, includeEventAds: $includeEventAds) {
// 			totalCount
// 			results {
// 				// ... some deep nesting
// 			}
// 		}
// 	}
// `;

const subscribeToEventLocking = gql`
	subscription eventsChangedByLocking {
		eventsChangedByLocking {
			eventIds
			userLock {
				isLocked
				username
			}
		}
	}
`;

const Events = ({
	max = 100,
	offset = 0,
	filters = [],
	sorting: sortings = [],
	leafletIds = [],
	children,
	...props
}) => {
	const variables = {
		max,
		sortings,
		offset,
		searchQuery: buildEventsQueryFromFilters(filters, { leafletIds }),
		includeEventAds: true,
	};

	useSubscription(subscribeToEventLocking, {
		onSubscriptionData: ({
			subscriptionData: {
				data: { eventsChangedByLocking },
			},
			client: { cache },
		}) => {
			const data = cache.readQuery({
				// variables and query are the same as handed to the component <Query ... >
				query: EVENTS,
				variables,
			});



			console.log(data); // TODO data is null !!



			

			// TODO updating data using changes from eventsChangedByLocking

			cache.writeQuery({
				query: EVENTS,
				variables,
				data,
			});
		},
	});

	return (
		<Query
			query={EVENTS}
			fetchPolicy="cache-first"
			notifyOnNetworkStatusChange={true}
			variables={variables}
			{...props}>
			{children}
		</Query>
	);
};

export default Events;
```

**Comment by ab-pm** [comment]
Subscription unfortunately do not update the cache. Unless you ran the query before, you won't get any data out of it.

You'll need to use only the `eventsChangedByLocking` data to write new things to the cache. Maybe use `writeFragment` instead of `writeQuery`?

**Comment by phryneas** [comment]
If your subscription results contain a proper `__typename` and `id` for the cache entities you want to update, they will get merged into the cache - that's probably what you were looking for.

That said, this is a very old issue and I assume you already moved on - sorry for not answering in time.
I'm mostly writing this for anyone who might find this issue coming from a google search ^^

I'll close the issue now - if anything else comes up, please open a new issue 😄
