### ISSUE TITLE
Cookie not sending with credentials: "include" in apollo client

### ISSUE THREAD

**Issue by ShourovRoy** [apollographql/apollo-client#9134]
Apollo Client not sending the cookie even after making the "include" in credentials

backend cors 

cors: {
        credentials: true,
        origin: "http://localhost:3000"
}

front end:

import '../styles/globals.css'
import type { AppProps } from 'next/app'
import {
  ApolloClient,
  InMemoryCache,
  ApolloProvider,
} from "@apollo/client";

export const client = new ApolloClient({  
  uri: 'http://localhost:8000/graphql',    
  credentials: 'include',
  cache: new InMemoryCache(),
});

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ApolloProvider client={client}>
      <Component {...pageProps} />
    </ApolloProvider>
  )
}

export default MyApp

**Comment by salman-trimulabs** [comment]
I'm also facing this this. Any updated here @benjamn ?

**Comment by ramos07** [comment]
I am facing the same issue. In my case I have a user login mutation that sets a 'Cookie'. The mutation works fine when I use Apollo Studio to test out the mutation and the 'Cookie' is set, but when I execute the same mutation from my React app (via a login form), the user details are retrieved but the 'Cookie' is not set. I did notice that the domain for Apollo Studio is `https` whereas the domain for my React app is using `http`, not sure if that could be causing the Cookie to not be set. I also followed the method outlined in the [Apollo docs](https://www.apollographql.com/docs/react/networking/authentication/) for implementing Cookie based authentication but that did not seem to work either.

## Package versions

---

### Server

-   `apollo-server-express: 3.50`
-   `express-session: 1.17.2`

### Client

-   `@apollo/client: 3.5.6`

---

## Server code

```typescript
//index.ts
app.set('trust proxy', 1)
app.use(
    session({
        secret: 'Sdafdasfjaslfdo',
        resave: false,
        saveUninitialized: false,
        cookie: {
            secure: true,
            sameSite: 'none',
            httpOnly: true,
            maxAge: 86000,
        },
    })
)

server.applyMiddleware({
    app,
    cors: {
        origin: [
            'https://studio.apollographql.com',
            'http://localhost:3000',
            'http://localhost:4000/graphql',
        ],
        credentials: true,
    },
})
```

## Client code

```javascript
// index.tsx
import {
    ApolloClient,
    InMemoryCache,
    ApolloProvider,
    createHttpLink,
} from '@apollo/client'

const link = createHttpLink({
    uri: 'http://localhost:4000/graphql',
    credentials: 'include',
})

const apolloClient = new ApolloClient({
    cache: new InMemoryCache(),
    link,
})
```

```javascript
// resolvers.ts
import { IResolvers } from 'graphql-tools'
import { User } from './entity/User'
import * as argon2 from 'argon2'

export const resolvers: IResolvers = {
    Query: {
        me: (_, __, { req }) => {
            if (!req.session.userId) {
                return null
            }
            return User.findOne(req.session.userId)
        },
    },
    Mutation: {
        register: async (_, { name, email, password }) => {
            await User.create({ name, email, password }).save()

            return true
        },
        login: async (_, { email, password }, { req }) => {
            const user = await User.findOne({ where: { email } })
            if (!user) {
                return null
            }

            const valid = await argon2.verify(user.password, password)

            if (!valid) {
                return null
            }

            req.session.userId = user.id

            return user
        },
    },
}
```

**Comment by hwillson** [comment]
I'm skeptical there is an Apollo Client bug here; if this was a wide spread issue, there would be many more bug reports about this. If you can provide a small runnable reproduction that demonstrates this issue we'll take a closer look.

**Comment by ShourovRoy** [comment]
I had fixed that Issue. I require to mention the client address into the server core. In the server cors if you are using "*" then its  not gonna work.

**Comment by xeeshan34** [comment]
Hi, @ShourovRoy. I also tried to do this way but it's not resolved
