### ISSUE TITLE
Cannot read property 'errors' of undefined

### ISSUE THREAD

**Issue by bent0b0x** [apollographql/apollo-client#9139]
**Intended outcome:**

Perform a query with `useQuery`.

**Actual outcome:**

The query results in a runtime error, as the response is `undefined`.

>Cannot read property 'errors' of undefined

https://github.com/apollographql/apollo-client/blob/24799a94a19d695dea13d7f6e88285f700ac20a0/src/core/QueryManager.ts#L1037

**How to reproduce the issue:**

Unfortunately I have not been able to identify concrete steps to reproduce this problem. But I am happy to provide any additional info as needed.

**Versions**

```
@apollo/client": "3.4.15"
```

``` 
System:
    OS: macOS 11.6
  Binaries:
    Node: 16.9.1 - /usr/local/bin/node
    npm: 7.21.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Safari: 15.0
```

**Comment by hwillson** [comment]
We won't be able to troubleshoot this without a runnable reproduction. If you can provide one we'll take a closer look.
