### ISSUE TITLE
incorrect behaviour with infinity load with fetchMore and cache from "@apollo/client": "3.5.0",

### ISSUE THREAD

**Issue by iuriifaevskii** [apollographql/apollo-client#9140]
infinity load works well just for 3.4.17, not for 3.5.0 and more with the same code

this code for cashing for pagination works different for  "@apollo/client": "3.4.17" and  (apollo/client 3.5.0 or "@apollo/client": "3.5.5")

data - array with elements
count - their count

query:
```
export const GET_PRODUCTS_PAGINATE = gql`
  query getProductsPaginate(
    $limit: Int
    $offset: Int
    $categoryIds: [Int] = []
    $sortBy: String = "id"
  ) {
    products(
      limit: $limit
      offset: $offset
      categoryIds: $categoryIds
      sortBy: $sortBy
    ) {
      count
      data {
        id
        title
        text
        categories {
          id
          name
        }
        photos {
          id
          url
          order
          description
        }
        price
        weight
        size
        isHidden
        isSoldOut
      }
    }
  }
`;

```
cache code:
```

const cache = new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        products: {
          keyArgs: ['categoryIds'],
          merge(existing, incoming) {
            const existingData = existing?.data || [];

            return {
              count: incoming.count,
              data: [...existingData, ...incoming.data],
            };
          },
        },
      },
    },
  },
});
```

**Comment by benjamn** [comment]
@iuriifaevskii What sort of difference in behavior are you seeing?

**Comment by jbcrestot** [comment]
I can't be sure what was the author's issue, but I encountered an issue with a similar data structure. I'm just sharing my experience here.

I had 2 FlatList that intend to paginate through `onEndReached`calling `fetchMore` :
- the first one worked fine and the query response data structure was 
`{
  "data": {
    "xxx": [
      {
        "id": "1",
        "attributes": {
          "name": "Farine de blé"
        }
      },
      {
        "id": "2",
        "attributes": {
          "name": "farine de chataigne"
        }
      }
    ]
  }
}`

- the second didn't worked and the query response data structure was 
`{
  "data": {
    "yyy": {
      data: [
        {
          "id": "1",
          "attributes": {
            "name": "Farine de blé"
          }
        },
        {
          "id": "2",
          "attributes": {
            "name": "farine de chataigne"
          }
        }
      ]
    }
  }
}`

In the second case, I don't know why but fetchMore was triggering the initial query (with initial variables) as you can see here  :
![image](https://user-images.githubusercontent.com/1705417/181605984-337676d1-46b3-44a0-a851-08a6bc5780fb.png)

for test purpose, useQuery() was called with `limit: 5` while fetchMore was called with `limit: 6`

PS : this was happening with useQuery() and useLazyQuery()

**Comment by bignimbus** [comment]
Hi all 👋🏻  thanks so much for your patience - it would be really helpful to have a runnable reproduction to help narrow down how to resolve this.  [This template](https://github.com/apollographql/react-apollo-error-template/generate) should help get things started 🙏🏻
