### ISSUE TITLE
ApolloLink export is undefined since 3.5

### ISSUE THREAD

**Issue by DanielFGray** [apollographql/apollo-client#9143]
**Intended outcome:**

I'm building a custom link using
```js
import { ApolloLink } from '@apollo/client'
class MyLink extends ApolloLink {}
```

**Actual outcome:**

in v3.4.17 it works fine, but in 3.5 it is undefined
```
TypeError: Class extends value undefined is not a constructor or null
```
the types are fine, but `console.log(ApolloLink)` prints `undefined`

**How to reproduce the issue:**

Downgrade to 3.4.x and it works fine
upgrade to 3.5 and it is `undefined`

**Comment by benjamn** [comment]
@DanielFGray What bundler are you using? Can you provide a small reproduction?

**Comment by hwillson** [comment]
We haven't heard back regarding our question in https://github.com/apollographql/apollo-client/issues/9143#issuecomment-983619313 so we'll close this off.

**Comment by CarsonF** [comment]
I just hit this as well. 4 days too late apparently haha. I'm still on webpack 4.46... Continuing to dig.

**Comment by inakineitor** [comment]
@CarsonF Hi! How did you configure FileLoader? I followed your suggestion by adding `cjs` to source extensions instead of asset extensions but it is not working for me.

![image](https://user-images.githubusercontent.com/7718934/211617770-cbb5b457-6eb0-4fa3-9cb5-8d32576f8b70.png)

**Comment by CarsonF** [comment]
You'll have to consult expo/metro docs. I'm not even sure that uses Webpack.
Maybe https://github.com/facebook/metro/issues/535 will help?

**Comment by inakineitor** [comment]
Thank you!
