### ISSUE TITLE
useLazyQuery loading is always false on subsequent calls since 3.5

### ISSUE THREAD

**Issue by adrienharnay** [apollographql/apollo-client#9146]
**Intended outcome:**

When calling the function provided by the lazy query again, `loading` should be set to true again.

**Actual outcome:**

`loading` is only set to true on the first call.

**How to reproduce the issue:**

Test with any lazy query. Call the function once, `loading` will be set to true, then false. Call the function again, `loading` will stay false.

**Versions**

```
 System:
    OS: macOS 11.6
  Binaries:
    Node: 16.6.1 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/Documents/GitHub/brigad/front-end/node_modules/.bin/yarn
    npm: 7.20.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Firefox: 93.0
    Safari: 15.1
  npmPackages:
    apollo: 2.33.9 => 2.33.9 
```

@apollo/client: 3.5.5

**Comment by MajidCybanor** [comment]
facing same issue
[https://github.com/apollographql/apollo-client/issues/9137](url)

**Comment by bignimbus** [comment]
Hi all, per #9137 this is the intended behavior.  See that thread for more context and some suggestions as to how to change the behavior of `loading` in `useLazyQuery`.  Thanks! 🙏🏻
