### ISSUE TITLE
Support for graphql version 16.x.x

### ISSUE THREAD

**Issue by IbtsamGujjar** [apollographql/apollo-client#9149]
Not exactly sure if this would be a feature request or an issue, based on my understanding of the docs I assume apollo-client v3 supports latest graphql version.

I am setting up a new react project with apollo client, when installing graphql dependency I am getting the latest version 16.x.x. 
**Intended outcome:**
Update graphql from version `15.7.2` to `16.0.1` and nothing should break.

**Actual outcome:**
When I update graphql to version 16.x.x I am getting the following error, because apollo-cache-inmemory is trying to import `QueryDocumentKeys` which is no longer exported from the given file.
<img width="805" alt="Screen Shot 2021-12-02 at 2 17 45 PM" src="https://user-images.githubusercontent.com/32162129/144393393-44ebd19c-8931-483d-b7f3-0b426b5cdb78.png">

**How to reproduce the issue:**

**Versions**
 System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.5/bin/yarn
    npm: 7.21.0 - ~/.nvm/versions/node/v14.17.5/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
  npmPackages:
    @apollo/client: ^3.5.5 => 3.5.5

**Comment by benjamn** [comment]
@IbtsamGujjar The `apollo-cache-inmemory` package is left over from AC2. You should `import { InMemoryCache } from "@apollo/client"` now, and probably `npm rm apollo-cache-inmemory`. More details about imports in the [migration guide](https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/#updating-imports).

**Comment by IbtsamGujjar** [comment]
Thank you for your response @benjamn 
I am not importing `InMemoryCache` anywhere in my code nor did I installed it manually. FWIW I am using `aws-appsync` with AC which might be causing this error. 
I am instantiating the client as 
```
import AWSAppSyncClient from 'aws-appsync';
client = new AWSAppSyncClient({
    url: ENV.GRAPHQL_BASE_URL,
    region: ENV.APP_SYNC_REGION,
    auth: {
      type: 'API_KEY',
      apiKey: ENV.APP_SYNC_KEY,
    },
    disableOffline: true,
  });
```
Here's my full list of dependencies and devDependencies 

```
"dependencies": {
    "@apollo/client": "^3.5.5",
    "@reduxjs/toolkit": "^1.6.2",
    "aws-appsync": "^4.1.4",
    "graphql": "^16.0.1",
    "query-string": "^7.0.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-redux": "^7.2.6",
    "react-scripts": "4.0.3",
    "redux": "^4.1.2",
    "sass": "^1.43.5",
    "typescript": "^4.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.16.0",
    "@babel/preset-react": "^7.16.0",
    "@babel/preset-typescript": "^7.16.0",
    "@testing-library/dom": "7.21.4",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@typescript-eslint/eslint-plugin": "^5.4.1-alpha.40",
    "@typescript-eslint/parser": "^5.4.0",
    "eslint": "^7.5.0",
    "eslint-plugin-react": "^7.27.1",
    "husky": "^7.0.4",
    "ts-jest": "^27.0.7"
  },
```

**Comment by benjamn** [comment]
What do you see if you run `npm ls apollo-cache-inmemory`?

**Comment by IbtsamGujjar** [comment]
I am seeing this 

<img width="420" alt="Screen Shot 2021-12-03 at 5 57 44 PM" src="https://user-images.githubusercontent.com/32162129/144645824-d89e5ef9-1ec9-44c5-8f9c-d3c3a41373d1.png">

Going through aws app-sync [github](https://github.com/awslabs/aws-mobile-appsync-sdk-js#react--react-native) again I realized I was using AC2 way(well kind of) instead of AC3 way of client instantiation.

I have changed my apollo client instantiation to following using `aws-appsync-auth-link` instead of `aws-appsync`, now I am not seeing any errors 

```
import { ApolloClient, ApolloLink, createHttpLink, InMemoryCache } from '@apollo/client';
import { createAuthLink } from 'aws-appsync-auth-link';
const link = ApolloLink.from([
  createAuthLink({
    url: ENV.GRAPHQL_BASE_URL,
    region: ENV.AWS_APPSYNC_REGION,
    auth: {
      type: 'API_KEY',
      apiKey: ENV.AWS_APPSYNC_API_KEY,
    }
  }),
  createHttpLink({ uri: ENV.GRAPHQL_BASE_URL }),
]);

client = new ApolloClient({
    link,
    cache: new InMemoryCache(),
  });
```

**Comment by madrigall** [comment]
@benjamn with graphql 16.2.0 and apollo 3.5.6 error appears Cannot read properties of undefined (reading 'QUERY') 
[codesandbox](https://codesandbox.io/s/broken-glitter-iozvd?file=/src/index.js)

**Comment by hwillson** [comment]
Closing as it sounds like this was resolved.
