### ISSUE TITLE
useLazyQuery() not merging variables from options with variables executeOptions

### ISSUE THREAD

**Issue by Titozzz** [apollographql/apollo-client#9152]
**Intended outcome:**
useLazyQuery should merge variables from options + the execute function

**Actual outcome:**
Only the execute function variables are sent

**How to reproduce the issue:**
use variables from both options and execute function

**Versions**
This is a regression from 3.5 due to the rewrite of lazyQuery

**Comment by benjamn** [comment]
@Titozzz Thanks for flagging this! We'll take a look (cc @brainkim).

**Comment by Titozzz** [comment]
Here is a repro, you can play with the package version number on the left.
Happy to help test / review or do anything you need to get this fixed.
We stay on 3.4 and graphql 15 in the meantime.

https://codesandbox.io/s/apollo-client-3-5-9-bug-on0b5z?file=/src/App.js

This bug is here since 3.5 beta 6, we might want it to be resolved before 3.6 (or at the next release)

CC: @benjamn @hwillson @brainkim

**Comment by benjamn** [comment]
@Titozzz Thanks to your reproduction, I believe this should be fixed in `@apollo/client@3.6.5` (just published to npm). Please let us know if we missed something!

**Comment by Titozzz** [comment]
@benjamn I can confirm that it's working with 3.6.5. It was already working on 3.6.4 but due to the merge of variables for all the queries. So if you didn't patch this, 3.6.5 would have been broken. Thanks for the quick fix. Happy to provide reproductions if I see things.

Have a nice day ♥️
