### ISSUE TITLE
Bug: useQuery refetches on every state change

### ISSUE THREAD

**Issue by iamclaytonray** [apollographql/apollo-client#9157]
**Intended outcome:**

I toggle color mode (light/dark). Query should not refetch because of that re-render.

**Actual outcome:**

I toggle color mode (light/dark) or type in a controlled input. Query does refetch (for input, after every onChange event).

**How to reproduce the issue:**

The current template will show this issue. Just add `console.log(data);` under the query and type in the input. Every onChange event will cause apollo to refetch the data. 

**Versions**

```
 System:
    OS: macOS 11.2.3
  Binaries:
    Node: 16.4.1 - ~/.nvm/versions/node/v16.4.1/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 7.19.1 - ~/.nvm/versions/node/v16.4.1/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Firefox: 89.0.2
    Safari: 14.0.3
  npmPackages:
    @apollo/client: ^3.5.5 => 3.5.5
```

## Extra notes
I don't imagine this is intentional and I don't think the solution would be to manage skip outside of Apollo (using `React.useState()` & `React.useEffect()`. This would make `useQuery` useless and would force me to always use `useLazyQuery`, requiring me to always manage how a query is called. I agree on a page refresh or new mount, the query should fetch as normal. Just not on every single state change in that tree

**Comment by hwillson** [comment]
@iamclaytonray this is how `useQuery` was designed which means this behaviour is intentional. If you don't want the query to run on subsequent renders, you can control that using the [`skip` option](https://www.apollographql.com/docs/react/api/react/hooks/#skip).
