### ISSUE TITLE
CQRS Backend - Ensure local cache is persisted for a specified time period

### ISSUE THREAD

**Issue by jwarykowski** [apollographql/apollo-client#9162]
## Background

Due to our CQRS backend in most cases we never get an updated entity returned, we simply get a 200 and a basic payload stating that our event has been acknowledged. Because of this our local cache contains the most recent version of our record but a subsequent request returns the stale data from the backend and overwrites our local cache 😢 

Currently we keep this updated version of our data in a reactive variable which means we have two data stores which contain the same data which is less than ideal. Please also note that our entity records don't contain any timestamp values such as updatedAt so we can't do a comparison here.

## Solution

At present I'm looking at building a solution around the apollo cache so that the local cache is persisted for a defined time period (2 mins), following this period the local cache can then be overwritten by the matching record from the backend. 

I'm thinking we could have an object which defines the cache identifier key and an associated timestamp so a lookup would be extremely quick, e.g 

```js
 {
   "Person:cGVvcGxlOjE=": 1638867005,
   "Planet:cGxhbmV0czox": 1638868005,
   ...
 }
```

We'd just need to add a hook to set the identifier and timestamp upon adding the record to the local cache, and then have a way of inspecting records from the server side, determine if the local cache is still deemed newer and return the existing over the incoming while inside the timestamp indicated for that record identifier. 

I've read the documentation around the type policies but wondered whether this would be the best place to handle this logic and if there was another approach I could use? Can you use define a top level merge function for an entity e.g. Person which could inspect and then determine whether to merge based on the identifier/timestamp above?

Any help would be appreciated.

Just to note I've posted this within the apollo community and stackoverflow - If I get an answer there I'll close this issue.

**Comment by bignimbus** [comment]
Hi @jwarykowski 👋🏻  thanks for your patience!  I see you posted [here](https://community.apollographql.com/t/cqrs-backend-ensure-local-cache-is-persisted-for-a-specified-time-period/2168) - have you settled on an approach or do you still need support here?

**Comment by jwarykowski** [comment]
Hey @bignimbus, thanks for reaching out. I didn't get round to solving this problem in the end due to other priorities, however I was investigating using the following project to help achieve my goal: https://github.com/NerdWalletOSS/apollo-cache-policies. 

It would be great your thoughts on how this could be achieved.

**Comment by bignimbus** [comment]
@jwarykowski I haven't used that library but it seems like a good solution.  I'll also borrow a code snippet from @benjamn that may be of use here:

```js
new InMemoryCache({
  typePolicies: {
    SomeType: {
      fields: {
        theField: makeTTLFieldPolicy(YOUR_DESIRED_TTL),
        anotherField: makeTTLFieldPolicy(2 * YOUR_DESIRED_TTL),
        // ... and so on ...
       },
    },
  },
})
```

That `makeTTLFieldPolicy` would look something like this:

```js
function makeTTLFieldPolicy(maxElapsedMillis) {
  return {
    read(existing) {
      if (existing && existing.storageTime) {
        const elapsedMillis = Date.now() - existing.storageTime;
        if (elapsedMillis > maxElapsedMillis) {
          return;
        }
      }
      return existing && existing.value;
    },
    merge(existing, incoming, { mergeObjects }) {
      return {
          value: existing ? mergeObjects(existing, incoming) : incoming,
          storageTime: Date.now(),
      };
    },
  };
}
```

Note that the timestamps could only be compared when `read`/`merge` are called so there's no eager eviction mechanism.  Hope that helps!

**Comment by jwarykowski** [comment]
Hey @bignimbus, thanks for the example, I'll check this out 🙇

**Comment by bignimbus** [comment]
Closing this for now but please do feel free to let us know if you need more support here 🙏🏻
