### ISSUE TITLE
Typescript build error "Generic type 'ExecutionResult<TData>' requires between 0 and 1 type arguments" with graphql@14

### ISSUE THREAD

**Issue by leereamsnyder** [apollographql/apollo-client#9167]
**Intended outcome:**

I am hitting this and just saw this [mentioned in a comment](https://github.com/apollographql/apollo-client/issues/9034#issuecomment-988355563) on another issue #9034 but I think this is a different issue.

After updating to the latest @apollo/client packages and following the migration guide (I was coming from `apollo-client@2.6.4`), my Typescript build process should still work with the same supported version of GraphQL. 

Judging from @apollo/client's peer dependencies, that should be ^14, ^15, or ^16.

**Actual outcome:**

`tsc` command fails with a Typescript error. 

Doing `tsc --check-types` gives the following error:

```
../../node_modules/@apollo/client/link/core/types.d.ts:19:134 - error TS2707: Generic type 'ExecutionResult<TData>' requires between 0 and 1 type arguments.

19 export interface FetchResult<TData = Record<string, any>, TContext = Record<string, any>, TExtensions = Record<string, any>> extends ExecutionResult<TData, TExtensions> {
```

Going into that `@apollo/client/link/core/types.d.ts` types declaration file, I see this error:

<img width="951" alt="Screen Shot 2021-12-08 at 9 03 55 PM" src="https://user-images.githubusercontent.com/870668/145321297-1f926da9-1033-411d-b792-ca3009bdcbfb.png">

And ExecutionResult appears to be coming from 'graphql', so I'm assuming that's where the type mismash is happening.

**How to reproduce the issue:**

You should be able to create a typescript project with these packages:

- typescript@4.1.3
- @apollo/client@3.5.6 (also present with 3.5.5)
- graphql@14.7.0

and `tsc` should throw that error.

**Versions**

```

  System:
    OS: macOS 11.6.1
  Binaries:
    Node: 12.22.7 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.93
    Firefox: 95.0
    Safari: 15.1

```

Thank you in advance. I wish Typescript gave literally any more information, but that's what I've got. :(

**Comment by annienero** [comment]
+1

**Comment by econtentmaps** [comment]
+1

**Comment by pawelidziak** [comment]
Hey, I have tried to install apollo with angular 13, and for the newest packages versions, I'm facing the same error. I tried both ways for install (`ng add apollo-angular` and `npm i` packages separately, how is presented in [Get started](https://apollo-angular.com/docs/get-started))

![image](https://user-images.githubusercontent.com/22195238/151661182-56fd8547-8b9d-4f14-838b-8e09b6400159.png)

Packages version:

``` 
"@angular/cli": "~13.2.0",
...
"@apollo/client": "^3.5.8",
"apollo-angular": "^2.6.0",
"graphql": "^16.3.0",
"typescript": "~4.5.2"
```

I have tried to downgrade apollo-client or graphql package but nothing works. Have you guys some advice on how to solve it?

**Comment by AlvaroGarciaNexplore** [comment]
hey, i was with the same problem.
I had graphql dependencie in version 14.
Upgrading to "graphql": "^15.5.0" solve the issue for me.

Hope it helps you.

**Comment by traviscollins** [comment]
@AlvaroGarciaNexplore That worked for me. Thanks!

**Comment by leereamsnyder** [comment]
@jpvajda it is not resolved. 

Tested again with the latest @apollo/client and the last graphql v14:

- @apollo/client@3.6.9
- typescript@4.5.2
- graphql@14.7.0

And I'm getting the same type error when running `tsc`:

```
../../node_modules/@apollo/client/link/core/types.d.ts(19,134): error TS2707: Generic type 'ExecutionResult<TData>' requires between 0 and 1 type arguments.
```

The comments suggest upgrading to GraphQL v15+, but that isn't a trivial update because I have other dependencies that are down-level some and only claim to support GraphQL up to v14.

So the issue appears to be the same: @apollo/client v3+ _appears_ to support GraphQL v14 via peer dependencies:

```json
// @apollo/client/package.json

// snip
  "peerDependencies": {
    "graphql": "^14.0.0 || ^15.0.0 || ^16.0.0",
// snip
```

But in practice that isn't true _if you use TypeScript_ because there's an incompatibility in the `ExecutionResult` types between @apollo/client v3 and graphql v14

**Comment by shaheedac** [comment]
I have tried to install apollo with angular 15, and for the newest packages versions, I'm facing a similar error.

"apollo-link": "^1.2.14",
 "apollo-angular": "^4.2.0",
"typescript": "~4.8.2"
 "graphql": "^14.6.0",

Error: node_modules/apollo-angular/types.d.ts:27:18 - error TS2430: Interface 'SubscriptionResult<T>' incorrectly extends interface 'ExecutionResult<ExecutionResultDataDefault>'.
  Types of property 'data' are incompatible.
    Type 'T | undefined' is not assignable to type 'ExecutionResultDataDefault | null | undefined'.
      Type 'T' is not assignable to type 'ExecutionResultDataDefault | null | undefined'.
        Type 'T' is not assignable to type 'ExecutionResultDataDefault'.


any solution for this ?.

**Comment by phryneas** [comment]
@shaheedac at this point, the easiest solution would probably be to upgrade to `graphql` 15 or 16 if you can - v14 is 5 years old at this point and v15 has been released 3 years ago.

If that is not possible, there is a good chance this could be resolved if you turn `skipLibCheck: true` in your `tsconfig.json` on.

I am at this point unsure if we should introduce any changes on our side to make this possible - given the age of graphql 14 it seems unlikely, but I'll put it on the agenda for one of our next team meetings.

**Comment by phryneas** [comment]
I've talked about this with the team, and we won't make a change here anymore.

While `graphql` 14 works with Apollo Client on a runtime level, unfortunately we have these type conflicts. And as we plan to drop support for graphql 14 with Apollo Client 3.9, we will not introduce any changes regarding this anymore.

@shaheedac [apollo-angular 4.2.0](https://unpkg.com/apollo-angular@4.2.0/package.json) already has a `peerDependency` on `graphql` 15 or 16, you should really not be using that one with v14.

**Comment by shaheedac** [comment]
> If that is not possible, there is a good chance this could be resolved if you turn `skipLibCheck: true` in your `tsconfig.json` on.

That worked for me. Thank you :) !
