### ISSUE TITLE
Did the modifying onCompleted in useLazyQuery and network policy?

### ISSUE THREAD

**Issue by Moonachi** [apollographql/apollo-client#9170]
Functions and Features that worked well before do not work after upgrading.
  "@apollo/client": "^3.5.5",

Example) 
- onCompleted function is not knowing state variable changed.

- onCompleted is not executed if the response value of useLazyQuery is the same. But, I can see the response on network tab of developer tools.
so, when i added fetch-policy no-cache, notifyOnNetworkStatusChange (true), it works well. 
Is this the correct way to do this?

Has anyone experienced the same phenomenon as me?

**Comment by lvauvillier** [comment]
May be related to #9175.

**Comment by Moonachi** [comment]
> 

Thank you. However, is it correct for the onCompleted function to be called once
when the response data is the same?

> May be related to #9175. Try to update to 3.5.6

**Comment by manuFL** [comment]
same here... I've also tried to use "no-cache" policy but it is not firing when the response is the same...
I need to be able to trigger onCompleted function regardless of the result, and I think most of the other users could have similar needs...

**Comment by bignimbus** [comment]
Hi all 👋🏻  thanks for your patience!  I'm doing some housekeeping and wanted to check in here.  For anyone who experienced this issue, did upgrading resolve it?  Thanks a bunch 🙏🏻

**Comment by Moonachi** [comment]
> Hi all 👋🏻 thanks for your patience! I'm doing some housekeeping and wanted to check in here. For anyone who experienced this issue, did upgrading resolve it? Thanks a bunch 🙏🏻

 "@apollo/client": "^3.6.9",
 "@apollographql/apollo-tools": "^0.5.4",
 
 I used onCompleted function in this version. 
 I think it seems to work.
