### ISSUE TITLE
"cache-and-network" fetchPolicy on useQuery does not update cache

### ISSUE THREAD

**Issue by alicerocheman** [apollographql/apollo-client#9173]
**Intended outcome:**
with fetchPolicy set with "cache-and-network", I expect the cache to be updated:
first load:
1. stale data (cache result 1)
2. up to date data (network result 1)
second load:
1. up to date data (cache result 2 === network result 1)

**Actual outcome:**
with fetchPolicy set with "cache-and-network", cache is not updated
first load:
1. stale data (cache result 1)
2. up to date data (network result 1)
second load:
1. stale data (old cache result 1)
2. up to date data (network result 2)

**How to reproduce the issue:**
with:
```
const { data } = useQuery(MyQuery, {
  fetchPolicy: 'cache-and-network'
})
```
1. load page
2. change data in backend
3. load page 
4. load page again

**Versions**
System:
    OS: macOS 11.6.1
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.93
    Firefox: 94.0.2
    Safari: 15.1
  npmPackages:
    @apollo/client: ^3.5.5 => 3.5.5

**Comment by hwillson** [comment]
Please provide a small runnable reproduction that demonstrates the issue and we'll take a closer look.
