### ISSUE TITLE
[BUG] Cache not get updated after a mutation operation?

### ISSUE THREAD

**Issue by yaquawa** [apollographql/apollo-client#9176]
Hi there,

I found that the `mutate` method is not going to update the cache automatically after mutation operation(version:"3.5.6").
I have to use `cache.modify` to update the cache manually.

I want to know if this is the intended behavior, because I think it really should automatically update the cache after  mutation operation.

Here is the example code that explain what I mean

```js
const getPostGql = /* GraphQL */ `
    query GetPost($id: ID!) {
        getPost(id: $id) {
            __typename
            id
            title
            createdAt
        }
    }
`;

const updatePostGql = /* GraphQL */ `
    mutation UpdatePost($id: ID!, $title: String!) {
        updatePost(id: $id, title: $title) {
            __typename
            id
            title
        }
    }
`;

async function getPost (id) {
  const { data } = await client.query({
    query,
    variables: {
      id
    }
  });

  return data;
}

async function updatePost (id, title) {
  return client.mutate({
    mutation,
    variables: {
      input: {
        id: id,
        title
      }
    }
  });
}

const postId = "123";

// query the post and save the result to cache.
const post = await getPost(postId);

// update the same post.
await updatePost(postId, "new title");

// query the same post again from cache.
const cached = await getPost(postId);

// I expect the cached object to be updated and the output should be "new title",
// but it was the old title.
console.log(cached.title ); 



// to update the cache I have to do this, which it should be done automatically
cache.modify({
  id: cache.identify({
    __typename: 'Post',
    id: postId,
  }),
  fields: {
    title() {
      return 'new title'
    },
  },
})
```

**Comment by hwillson** [comment]
@yaquawa this isn't a bug; drop the `input:` part as in change

```js
async function updatePost (id, title) {
  return client.mutate({
    mutation,
    variables: {
      input: {
        id: id,
        title
      }
    }
  });
}
```

to 

```js
async function updatePost (id, title) {
  return client.mutate({
    mutation,
    variables: {
      id,
      title
    }
  });
}
```

After that you shouldn't need the `cache.modify` call.

**Comment by yaquawa** [comment]
@hwillson The `input` is just a variable of `variables`, or do you mean `input` a reserved word in apollo-client?

**Comment by hwillson** [comment]
@yaquawa I mean that your mutation isn't set up to handle that `input` variable (at least not the one that you've shared). Try removing it to see if it helps.

**Comment by yaquawa** [comment]
@hwillson oh, sorry! it's my bad.. the code is wrong..
The example code is just a pseudo code, the real one don't have the `input` variable just as your code, but the cache won't get updated after a mutation operation as I mentioned.

**Comment by hwillson** [comment]
@yaquawa can you provide a small runnable reproduction? That will help us troubleshoot. You can use https://github.com/apollographql/react-apollo-error-template as a starting point.

**Comment by yaquawa** [comment]
Thanks @hwillson, but I don't have any knowledge with react. it'll take too much time for me to recreate a setup to reproduce the issue. Maybe you can just reopen this issue for someday so that you can fix it.
