### ISSUE TITLE
Importing from @apollo/client and running Jest results in TypeError

### ISSUE THREAD

**Issue by 9Lambda** [apollographql/apollo-client#9191]
I am upgrading my project from 2.6 to version 3.5.6 and I seem to run into an error when running my tests. The tests are using React and @testing-library/react with jest.  The error all seem to be related to my import with @apollo/client? For example a test case that mocks my gql query will fail to run and error with:

    TypeError: (0 , _client.gql) is not a function

I have changed what was previously `import gql from "graphql-tag"` to use @apollo/client.
My query in queries.js:
  ```
 import { gql } from "@apollo/client";

const LIST_ANIMALS= gql`
 query listAnimals($limit: Int!, $offset: Int!, $name: String) {
    listAnimals(limit: $limit, offset: $offset, name: $name) {
        list {
            id
            name
            country
        },
        count
    }
}
`;
```

An example of a test case:
```
import React 							        from "react";
import { screen, fireEvent } 				        from "@testing-library/react";
import { MockedProvider }                                      from "@apollo/client/testing";
import LIST_ANIMALS					        from "./queries";
import ListAnimals						        from "./ListAnimals";

test("renders list of animals correctly"), async () => {
	const mocks = [{
		request: {
			query: LIST_ANIMALS,
			variables : {
				limit : 5,
				offset: 0,
				name:"",
			},
		},
		result: {
			data: {
				listAnimals:
					{
						list : [{
							name: "Lucky",
							id: "animal-01",			
							country:"US",
						}],
						count:1,
					},
			},
		},
	}
	];
}

render(
	<MockedProvider addTypename={false} mocks={mocks}>
	     <ListAnimals />
	</MockedProvider>
)

	fireEvent.click(screen.getByRole("button", { name:"Search" }));
	expect(screen.getByRole("textbox", { name:"Name" })).toHaveValue("Lucky");
```

All my test cases that rely on mocking a query will error with the same error.

Similarly, when I am testing a file that uses 

`import { setContext } 				from "@apollo/client/link/context";`

it will also fail to run and error with:

    TypeError: (0 , _context.setContext) is not a function.

My package.json dependency has @apollo/client: ^3.5.6.

I have read the docs on migration, and I don't believe I am importing incorrectly both my gql query and apollo/client. Has anyone experienced something similar?

**Comment by marciok** [comment]
I was having the same issue, I believe the problemas was that when importing `import { gql, useQuery } from "@apollo/client"` you are importing a `.cjs` and my `react-scripts` version did not support that extension on jest.

If you are using `create-react-app` upgrade your scripts to the latest version: `4.0.3`

` yarn add --exact react-scripts@4.0.3`

Reference: https://github.com/facebook/create-react-app/blob/main/CHANGELOG.md

**Comment by 9Lambda** [comment]
> I was having the same issue, I believe the problemas was that when importing `import { gql, useQuery } from "@apollo/client"` you are importing a `.cjs` and my `react-scripts` version did not support that extension on jest.
> 
> If you are using `create-react-app` upgrade your scripts to the latest version: `4.0.3`
> 
> ` yarn add --exact react-scripts@4.0.3`
> 
> Reference: https://github.com/facebook/create-react-app/blob/main/CHANGELOG.md

ah cool thanks for that, I've had to downgrade to apolloClient to 3.4 rather than 3.5 which was a pain. I'll try that thanks!

**Comment by amannn** [comment]
I've got it working by adding `'^.+\\.cjs$': 'babel-jest'` to [the `transform` config of jest](https://jestjs.io/docs/configuration#transform-objectstring-pathtotransformer--pathtotransformer-object) as well as compiling `node_modules`.

**Comment by Nastoc4ka** [comment]
for me helped to install 'graphql-tag' library and import gql from  'graphql-tag'
like instead:
import { gql } from '@apollo/client';
I use import:
import gql from 'graphql-tag';

**Comment by mhmtugur** [comment]
I had the same issue but resolved it.

`jest.mock("@apollo/client", () => ({
  ...jest.requireActual("@apollo/client"),
  useApolloClient: () => null,
}));`

it works for me in the test files.

**Comment by amannn** [comment]
> @amannn what do you mean exactly by compiling `node_modules`?

https://stackoverflow.com/a/60730519/343045

**Comment by damiangreen** [comment]
thanks Would oyu mind sharing your `transformIgnorePatterns` 
Would it be something like this ?
``` transformIgnorePatterns: [
    '/node_modules/(?!intl-messageformat|konva|intl-messageformat-parser|node-fetch|d3-hierarchy|?!@apollo\\client).+\\.js$',
  ],

**Comment by damiangreen** [comment]
@trdp30 
my jest.config.js:
```
module.exports = {
  globals: {
    __DEV__: false,
    __MAINT__: false,
    'ts-jest': {
      isolatedModules: true,
    },
  },
  testEnvironment: 'jsdom',
  cacheDirectory: '.jest_cache',
  timers: 'legacy',
  bail: false,
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  moduleDirectories: ['node_modules', 'src'],
  moduleNameMapper: {
    '\\.(css|less|styl|scss|sass|sss)$': 'identity-obj-proxy',
    'isomorphic-style-loader/withStyles': '<rootDir>/tools/mocks/withStyles.js',
  },
  setupFiles: ['<rootDir>/tools/config/setup.config.jsx', 'jest-canvas-mock'],
  testRegex: '(/__tests__/.*|(\\.|/)test)\\.tsx?$',
  transform: {
    '^.+\\.[t|j]sx?$': 'ts-jest',
    '\\.(js|jsx|cjs)$': '<rootDir>/node_modules/babel-jest',
    '\\.(gql|graphql)$': '<rootDir>/node_modules/jest-transform-graphql',
    '^(?!.*\\.(js|jsx|json|css|less|styl|scss|sass|sss)$)':
      '<rootDir>/tools/lib/fileTransformer.js',
  },
  testResultsProcessor: './node_modules/jest-junit-reporter',
  transformIgnorePatterns: [
    '/node_modules/(?!intl-messageformat|konva|intl-messageformat-parser|node-fetch|d3-hierarchy|@apollo).+\\.(js|cjs)$',
  ],
  testPathIgnorePatterns: ['/routes/tests'],
  verbose: false,
  logHeapUsage: true,
  noStackTrace: true,
  setupFilesAfterEnv: ['./setupAfterEnv.ts'],
  prettierPath: './node_modules/prettier',
}

```
