### ISSUE TITLE
subscribing to ApolloLink and providing a `next` method causes the request to be sent twice.

### ISSUE THREAD

**Issue by cleversprocket** [apollographql/apollo-client#9196]
**Intended outcome:**
Subscribing to the `forward(operation)` observable in ApolloLink and providing a `next` method should not create side effects.

**Actual outcome:**
Requests are sent twice.

**How to reproduce the issue:**
This code will send the request twice.

```javascript
const myLink = new ApolloLink((operation, forward) => {
  const success = (data) => {
    console.log(data);
  };
  const observable = forward(operation);
  
  observable.subscribe({ next: success});

  return observable;
})
```
The above example is similar to the one provided in the [docs](https://www.apollographql.com/docs/react/api/link/introduction/#stateless-links) for reporting errors except the one in the docs subscribes to the `error` method. Shown below:
```javascript
import { ApolloLink } from '@apollo/client';

const reportErrors = (errorCallback) => new ApolloLink((operation, forward) => {
  const observable = forward(operation);
  // errors will be sent to the errorCallback
  observable.subscribe({ error: errorCallback })
  return observable;
});

const link = reportErrors(console.error);

```

How should the observer `next` be used?

**Versions**
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 10.23.2 - ~/.nvm/versions/node/v10.23.2/bin/node
    npm: 6.14.10 - ~/.nvm/versions/node/v10.23.2/bin/npm
  Browsers:
    Chrome: 96.0.4664.93
    Firefox: 94.0.2
    Safari: 15.1
  npmPackages:
    @apollo/client: ^3.3.12 => 3.3.12 
    apollo-link-error: ^1.1.13 => 1.1.13 
    apollo-link-sentry: ^1.3.0 => 1.3.0 
    apollo-upload-client: ^14.1.1 => 14.1.1

**Comment by hwillson** [comment]
@cleversprocket I'm not sure what you mean by `This code will send the request twice`. Are you saying that by just subscribing and adding a `next` callback your entire link based request is duplicated? That sounds very odd. If that's the case, please provide a runnable reproduction to demonstrate this and we'll take a closer look.

**Comment by cleversprocket** [comment]
Hi @hwillson yes, the link based request is duplicated. To reproduce all I have to do is add the link to the chain using Apollo.from:

```javascript
const myLink = new ApolloLink((operation, forward) => {
  const success = (data) => {
    console.log(data);
  };
  const observable = forward(operation);
  
  observable.subscribe({ next: success});

  return observable;
});

const chain = ApolloLink.from([
  myLink,
  createUploadLink({
    headers: {...},
    uri,
  })
]);

new ApolloClient({
  cache: ...,
  link: chain,
})
```
I worked around this issue by not subscribing to the Observable but by using the Observable's map method: `return forward(operation).map(data => { console.log(data); return data; })`. 

I unfortunately don't have the time to create a reproducible application.
