### ISSUE TITLE
My Pluralsight Course No Longer Builds Because of Dependency Error Introduced

### ISSUE THREAD

**Issue by pkellner** [apollographql/apollo-client#9199]
I currently have a package.json that includes graphql as a dependency among other things.  I've added the full `package.json` below.

when I do `npm install`, I get the error below which I was not getting before (and I've not made changes to this in a long time).

When I remove the dependency on `graphql`, I don't get the error and my app seems to work. I'm reluctant to do that though because in your getting started guide you explicitly say to install graphql along with the apollo client.

I'm not looking for a big fix as it would take a major update of my Pluralsight course. I'm hoping that since this worked before, there was a mistake made in one of your updates that you can fix so this error goes away.

The project that contains this issue can be found  at this github URL:
https://github.com/pkellner/pluralsight-apollo-managing-performance/tree/master/08-GraphQL-Server-Cache-High-Performance/clip04-Automatic-Persisted-Queries-GET/ApolloClientReactApp

```
code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: graphql@15.8.0
npm ERR! node_modules/graphql
npm ERR!   graphql@"^15.3.0" from the root project
npm ERR!   peer graphql@"^14.0.0 || ^15.0.0 || ^16.0.0" from @apollo/client@3.5.6
npm ERR!   node_modules/@apollo/client
npm ERR!     @apollo/client@"^3.2.5" from the root project
npm ERR!   6 more (@graphql-typed-document-node/core, apollo-link, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0" from apollo-link-persisted-queries@0.2.2
npm ERR! node_modules/apollo-link-persisted-queries
npm ERR!   apollo-link-persisted-queries@"^0.2.2" from the root project
```

Problem package.json below:

```
{
  "name": "ApolloClientReactAppFINAL",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@apollo/client": "^3.2.5",
    "apollo-link": "^1.2.14",
    "apollo-link-http": "^1.5.17",
    "apollo-link-persisted-queries": "^0.2.2",
    "bootstrap": "^4.5.2",
    "graphql": "^15.3.0",
    "next": "^9.5.5",
    "react": "^16.14.0",
    "react-dom": "^16.14.0",
    "reactstrap": "^8.6.0"
  }
}

```

**Comment by benjamn** [comment]
@pkellner Thanks for reporting this! That `package.json` reproduces the problem for me, so I think I have what I need to diagnose/fix the problem.

**Comment by benjamn** [comment]
Alright @pkellner, when I copy/paste that `package.json` and update `apollo-link-persisted-queries` to 0.2.5 (just published using the `next` tag), I no longer get the fatal `ERESOLVE` error when I try to install it. I believe this means (once I tag `apollo-link-persisted-queries@0.2.5` as `latest`) that the existing code for your course will continue to work (at least after reinstalling), but please let us know if anything else seems to be broken!

**Comment by pkellner** [comment]
Thanks @benjamn . updating `apollo-link-persisted-queries` to 0.2.5 solves it. I'm not a node expert, but I thought that there was some guarantee around things like this not happening when versions numbers are locked like I'm doing.  When I distribute my course and want the build to keep working for a very long time, should I be referencing versions differently?

**Comment by benjamn** [comment]
@pkellner Thanks for confirming! I'll go ahead and promote 0.2.5 to `latest`.

If you're not already doing so, it might make sense to check in a `package-lock.json` file for the app (for example, in the repository where `ApolloClientReactAppFINAL` lives), in addition to just `package.json`. That's currently the best way I know to freeze the versions in `node_modules` in a reproducible way.

**Comment by pkellner** [comment]
Issue resolved.
