### ISSUE TITLE
Apollo client error

### ISSUE THREAD

**Issue by mustafaefdal1** [apollographql/apollo-client#9208]
I am developing an application with react native typescript. When I try to install and use the apollo client, I get the following error.

Error: While trying to resolve module @apollo/client from file ****\src\api\queries\home.js, the package ****\node_modules\@apollo\client\package.json was successfully found. However, this package itself specifies a main module field that could not be resolved (****\node_modules\@apollo\client\main.cjs. Indeed, none of these files exist:

As a solution, I add the following lines to the metro.config.js file, but it still keeps giving the same error.

const { getDefaultConfig } = require("metro-config");
const { resolver: defaultResolver } = getDefaultConfig.getDefaultValues();
exports.resolver = {
  ...defaultResolver,
  sourceExts: [
    ...defaultResolver.sourceExts,
    "cjs",
  ],
};

how can i solve this?

**Comment by marvinklein** [comment]
update your metro config: https://github.com/apollographql/apollo-client/issues/9194#issuecomment-992769905

**Comment by hwillson** [comment]
Addressed in https://github.com/apollographql/apollo-client/issues/9194#issuecomment-992769905 - thanks!
