### ISSUE TITLE
`useLazyQuery` load function refetches from network regardless cache and variables

### ISSUE THREAD

**Issue by anfinil** [apollographql/apollo-client#9209]
According last refactoring:
https://github.com/apollographql/apollo-client/blob/bc6488c4eb02d41cd08d0f4dfaba7b45d707338e/src/react/hooks/useLazyQuery.ts#L48

https://github.com/apollographql/apollo-client/blob/6a5ae8afe38dc7f5d477020e23dee36768968b63/src/core/ObservableQuery.ts#L334

`useLazyQuery` `load` function will refetch data from network every time even with the same variables and regardless cache and `fetchPolicy`.

Desired behaviour: if `load` function results are cached (variables are the same), it shouldn't request network.

**Comment by Ccastillo06** [comment]
Having the same problem over here, was going crazy trying to find out why my cached responses did still requests to the server.

**Comment by orelHAnyvision** [comment]
same here

**Comment by mcsimps2** [comment]
I noticed the same issue when I was analyzing network requests with Chrome inspector

**Comment by LiamKlyneker** [comment]
Same problem here, I fixed it by returning to `v3.4.17`, I don't know why this feature changed in recent versions :/, maybe someone knows something about it

**Comment by sarink** [comment]
Reverting to `3.4.17` also fixed it for me, thanks @LiamKlyneker

**Comment by colinrobertbrooks** [comment]
@benjamn Can confirm I'm no longer seeing cached queries refetched with `3.6.0-beta.11`. 🎉

**Comment by anfinil** [comment]
@benjamn I can confirm that fix is working.
