### ISSUE TITLE
id field is serialized to string - don't serialize for developer

### ISSUE THREAD

**Issue by garrett-gottlieb** [apollographql/apollo-client#9211]
**Intended outcome:**

ID fields are serialized as strings when initialized as integer. Using graphql codegen, adding `ID: number` to scalars allows the types to work well with backend libraries like Sequelize. The ID on the client is expected to be read as the same to the developer.

**Actual outcome:**

The ID field is serialized as a string, breaking typing in this case and leading to type errors during runtime (integer expected instead of string).

**How to reproduce the issue:**

```gql
type AudioPost implements Model {
  id: ID!
  createdAt: Date!
  updatedAt: Date!
}

input CreateListenInput {
  audioPostId: ID!
  time: Int!
}

mutation CreateListen($input: CreateListenInput!) {
  createListen(input: $input) {
    ...Listen
  }
}
```
```ts
        createListenMutation({
          variables: {
            input: {
              audioPostId: audioPost.id,
              time: position,
            },
          },
        })
```
In order for this to work, the following change is necessary:
`              audioPostId: parseInt(audioPost.id)`

**Versions**

```
  System:
    OS: macOS 12.0.1
  Binaries:
    Node: 12.22.7 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 80.0
    Safari: 15.1
```

**Comment by hwillson** [comment]
@garrett-gottlieb Apollo Client doesn't convert ID's to strings. Please explain the issue you're seeing further, including where the `audioPost.id` value is coming from in your example.
