### ISSUE TITLE
Cache merging

### ISSUE THREAD

**Issue by Joel-Ajayi** [apollographql/apollo-client#9221]
**Intended outcome:**

I am making two queries, let's say
const [getCats] = useLazyQuery(GET_CATS) and 
const [getAdminCats] = useLazyQuery (GET_CATS)

TThe results. are similar and infact  they have the same unique  _id fileds, but I don't want to  merge the results of the queries together

**Actual outcome:**

The results of the different queries were merged together which is not what I want because even though the results of the queries have the same _id,  one query contains some fileds that  is not in the other and it  because of that overrides ther results of the other 

**How to reproduce the issue:**

**Versions**

Apollo client version : `3.3.19`

**Comment by hwillson** [comment]
@Joel-Ajayi this isn't a bug. Uniqueness in the cache is determined by `__typename` and `_id`. If you're storing data in the cache that has the same `__typename` and `_id` as previously stored data, the cache sees that data as the same entity by default. See the [Customizing cache IDs](https://www.apollographql.com/docs/react/caching/cache-configuration/#customizing-cache-ids) section of the docs for more details on how you can customize this.
