### ISSUE TITLE
useQuery not returning cache value consistently

### ISSUE THREAD

**Issue by cgorrieri** [apollographql/apollo-client#9229]
Hello, I am working on a NextJs application and I have an issue while rendering the result to send to the client.
I have a first step that uses the `getDataFromTree` to fetch all the data and then renders the app providing the apollo client that has the cache. I can see that the cache is populated properly on the server-side and hydrated on the client-side (I run extract after restore). The issue comes from the `useQuery` that doesn't seem to always be able to retrieve the data from the cache. When rendering the same page with the same parameters, it returns either `undefined` or the value from the cache when I am lucky. I don't understand why it is so flaky when it should always return the same since the parameters and data do not change.

Here is a preview of my component:
```
const MyComponent = () => {
  [...]
  const { data: devblogData, error: devblogError } = useQuery(getDevblogBySlug, {
    variables: { slug: devblogSlug },
  });
  const { data: postData, loading: postLoading } = useQuery(getPostWithDevblog, {
    variables: { id: postId },
    skip: !postSlug,
  });
  console.log('RENDER');
  console.log('devblogSlug:', devblogSlug);
  console.log('devblog:', devblogData?.getDevblogBySlug?.name);
  console.log('postSlug:', postSlug);
  console.log('post:', postData?.getPost?.title);
```

**Intended outcome:**
Hydrated cache:
```
{
    "ROOT_QUERY": { "__typename": "Query",
        "getPost({"id":"54hPIfPqz"})": { "__ref": "Post:54hPIfPqz" },
        "getMyProfile": { "__ref": "MyProfile:b89621d8-27da-4afc-b14d-e649c17c581f" },
        "getDevblogBySlug({"slug":"6-rising-at-hash"})": { "__ref": "GameDevblog:01FHTX1VRP07G4XGRENEN746WY" }
    },
    "GameDevblog:01FHTX1VRP07G4XGRENEN746WY": {
        "__typename": "GameDevblog",
        "id": "01FHTX1VRP07G4XGRENEN746WY",
        "slug": "6-rising-at-hash",
        [...]
    },
    "Post:54hPIfPqz": {
        "__typename": "Post",
        "id": "54hPIfPqz",
        [...]
        "devblog": { "__ref": "GameDevblog:01FHTX1VRP07G4XGRENEN746WY" }
    },
    [...]
}
```
Render logs:
```
RENDER
devblogSlug: 6-rising-at-hash
devblog: 6 rising @ #
postSlug: another-draft-54hPIfPqz
post: Another draft
```
The devblog and post enttities were both hydrated and retrieved from the cache.

**Actual outcome:**
```
{
    "ROOT_QUERY": {
        "__typename": "Query",
        "getDevblogBySlug({"slug":"6-rising-at-hash"})": { "__ref": "GameDevblog:01FHTX1VRP07G4XGRENEN746WY" },
        "getMyProfile": { "__ref": "MyProfile:b89621d8-27da-4afc-b14d-e649c17c581f" },
        "getPost({"id":"54hPIfPqz"})": { "__ref": "Post:54hPIfPqz" }
    },
    [...]
    "Post:54hPIfPqz": {
        "__typename": "Post",
        "id": "54hPIfPqz",
        [...]
        "devblog": { "__ref": "GameDevblog:01FHTX1VRP07G4XGRENEN746WY" }
    },
    [...]
    "GameDevblog:01FHTX1VRP07G4XGRENEN746WY": {
        "__typename": "GameDevblog",
        "id": "01FHTX1VRP07G4XGRENEN746WY",
        "slug": "6-rising-at-hash",
        [...]
    },
    [...]
}
```
Render logs:
```
RENDER
devblogSlug 6-rising-at-hash
devblog undefined
postSlug another-draft-54hPIfPqz
post Another draft
```
Here the devblog entity was not retrieved from the cache however the query is the same and the data for the devblog is in the cache.

**Versions**
```
 System:
    OS: macOS 11.6.2
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0.2
    Safari: 15.2
  npmPackages:
    @apollo/client: ^3.5.6 => 3.5.6 
```
I tried downgrading to `3.4.x` for `@apollo/client` but it is the same.

**Comment by hwillson** [comment]
@cgorrieri have you confirmed `name` is always in the cache when you expect it to be? (as in `name` from `devblogData?.getDevblogBySlug?.name`) Your cache extracts don't show `name` so I'm just confirming. If it is we'll need a small runnable reproduction to be able to help you troubleshoot further.

**Comment by cgorrieri** [comment]
Hi @hwillson, I believe I found the issue.

In my `getPostWithDevblog ` query, I fetch a subset of the data of the devblog. I think that because of that if this query's response arrives after the `getDevblogBySlug` then the devblog's data are merged and some fields are removed which triggers the reload of the `getDevblogBySlug`.

Thank you for looking into that.

Best,
Cyril
