### ISSUE TITLE
TypeError: undefined is not a constructor (evaluating 'new _client.InMemoryCache()')

### ISSUE THREAD

**Issue by camillo18tre** [apollographql/apollo-client#9242]
I am trying to use apollo client with React Native as indicated in the documentation at this link: https://www.apollographql.com/docs/react/integrations/react-native/

But i get this error:  **TypeError: undefined is not a constructor (evaluating 'new _client.InMemoryCache()')**

```
import React from 'react';
import { AppRegistry } from 'react-native';
import { ApolloClient, InMemoryCache, ApolloProvider } from '@apollo/client';

// Initialize Apollo Client
const client = new ApolloClient({
  uri: 'http://192.168.1.168:8080/v1/graphql',
  cache: new InMemoryCache(),
});

const App = () => (
  <ApolloProvider client={client}>
    <MyRootComponent />
  </ApolloProvider>
);

AppRegistry.registerComponent('MyApplication', () => App);

```
**Actual outcome:**

```
TypeError: undefined is not a constructor (evaluating 'new _client.InMemoryCache()')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:204:6 in guardedLoadModule
at http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:116853:3 in global code

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
```
![React-native](https://user-images.githubusercontent.com/38567269/147392635-d7111e36-9a50-4e3c-a714-60b90792dcf8.jpg)

**Versions**

  System:
    OS: macOS 11.6
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0
    Safari: 14.1.2
  npmPackages:
    @apollo/client: ^3.5.6 => 3.5.6

Below my package.json

```
{
  "name": "egregio-avvocato-app",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@apollo/client": "^3.5.6",
    "dotenv": "^10.0.0",
    "expo": "~44.0.0",
    "expo-status-bar": "~1.2.0",
    "graphql": "^16.2.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-web": "0.17.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}

```

I hope you can help me!

C.

**Comment by torontochen** [comment]
same issue here

**Comment by camillo18tre** [comment]
Hei guys, Nobody knows why it doesn't work?

**Comment by MahitMehta** [comment]
Hey, I'm also facing this issue. No clue what's wrong.

**Comment by torontochen** [comment]
import { inMemoryCache } from '@apollo/client/cache/inmemory/inMemoryCache' seems working, but I got another problem when customizing ApolloLink

**Comment by camillo18tre** [comment]
@torontochen now I get this back:

```
TypeError: undefined is not an object (evaluating '_zenObservableTs.Observable.prototype')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:204:6 in guardedLoadModule
at http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:141487:3 in global code

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
```
Did you get the same issue?

**Comment by MahitMehta** [comment]
@camillo18tre 
Yes, I get the same problem after changing my imports.

**Comment by torontochen** [comment]
@camillo18tre 
same, I upgrade from v2, tons of  trouble

**Comment by MahitMehta** [comment]
After a few hours of messing around with the code I realized I needed to modify my metro.config.js file.

Before it Looked Like this:
`// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require('expo/metro-config');

module.exports = getDefaultConfig(__dirname);`

Now it looks like this: 

`// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require('expo/metro-config');

const defaultConfig = getDefaultConfig(__dirname);

defaultConfig.resolver.sourceExts.push('cjs');

module.exports = defaultConfig;
`

**Comment by camillo18tre** [comment]
> After a few hours of messing around with the code I realized I needed to modify my metro.config.js file.
> 
> Before it Looked Like this:
> 
> ```
> // Learn more https://docs.expo.io/guides/customizing-metro
> 
> const { getDefaultConfig } = require('expo/metro-config');
> 
> module.exports = getDefaultConfig(__dirname);
> ```
> 
> Now it Looks Like this:
> 
> ```
> // Learn more https://docs.expo.io/guides/customizing-metro
> const { getDefaultConfig } = require('expo/metro-config');
> 
> const defaultConfig = getDefaultConfig(__dirname);
> 
> defaultConfig.resolver.sourceExts.push('cjs');
> 
> module.exports = defaultConfig;
> ```

Seems that now everything works!!! thank you so much! @MahitMehta.
@torontochen Let us know if you have solved it

**Comment by hwillson** [comment]
For more details about this issue, please see this [notice](https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#notices) in the Apollo Client 3.5.4 CHANGELOG. This is a known Metro issue but the workaround mentioned here and in that notice should help for now.

**Comment by torontochen** [comment]
@camillo18tre  here is my v3 import right now
import { ApolloClient } from "@apollo/client/core"
import { ApolloLink } from "@apollo/client"
import { onError } from '@apollo/client/link/error'
import { InMemoryCache } from '@apollo/client/cache'
import { Observable } from "@apollo/client/utilities";
import { WebSocketLink } from "@apollo/client/link/ws"
import { setContext } from "@apollo/client/link/context"
import { getMainDefinition } from "@apollo/client/utilities"

 metro.config.js is added as above posted

now  got another issue

const cache = new InMemoryCache();
cache.writeData({ data: defaultStates });

TypeError: cache.writeData is not a function
at node_modules/expo/build/logs/LogSerialization.js:155:14 in _captureConsoleStackTrace
at node_modules/expo/build/logs/LogSerialization.js:41:26 in serializeLogDataAsync
- ... 9 more stack frames from framework internals

not sure if you guys has the same problem

**Comment by brkss** [comment]
i guess @apollo/client@3.5.x have that problem, i've downgraded to 3.4.16 and everything is working just fine 👍

**Comment by benjamn** [comment]
@torontochen The `cache.writeData` method was removed in v3.0. You must be upgrading from v2. If that's right, please see the [migration guide](https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/#breaking-cache-changes) for more details.

**Comment by torontochen** [comment]
@benjamn thank you, time to go through doc again

**Comment by tetogomez** [comment]
works for me using:

`"@apollo/client": "^3.5.6"`
`"expo": "^45.0.2",`

`metro.config.js`
```
const { getDefaultConfig } = require('@expo/metro-config')
const defaultConfig = getDefaultConfig(__dirname)

defaultConfig.resolver.sourceExts.push('cjs')

module.exports = defaultConfig
```

**Comment by doug-sheridan** [comment]
> i guess @apollo/client@3.5.x have that problem, i've downgraded to 3.4.16 and everything is working just fine 👍

Downgrading to @apollo/client to v3.4.x was the only thing that worked for me. 

None of the other recommended solutions in this issue seems to have worked for me.

**Comment by FaisalSeraj-techverx** [comment]
I was facing the same issue and this https://github.com/apollographql/apollo-client/issues/9242#issuecomment-1140526469 is the best solution

**Comment by deggertsen** [comment]
Seems like this may be an issue again with 3.7.0? I downgraded to 3.6.10 and it resolved the issue.

**Comment by CharlieBreval** [comment]
In my case, indeed @hwillson said did solve my issue. Not handling cjs file from metro config look to solve the issue

**Comment by ApoloIslaio** [comment]
> After a few hours of messing around with the code I realized I needed to modify my metro.config.js file.
> 
> Before it Looked Like this:
> 
> ```
> // Learn more https://docs.expo.io/guides/customizing-metro
> 
> const { getDefaultConfig } = require('expo/metro-config');
> 
> module.exports = getDefaultConfig(__dirname);
> ```
> 
> Now it Looks Like this:
> 
> ```
> // Learn more https://docs.expo.io/guides/customizing-metro
> const { getDefaultConfig } = require('expo/metro-config');
> 
> const defaultConfig = getDefaultConfig(__dirname);
> 
> defaultConfig.resolver.sourceExts.push('cjs');
> 
> module.exports = defaultConfig;
> ```

Worked for me! thanks
