### ISSUE TITLE
RefetchQueries is not Update  Realtime Queries UI   

### ISSUE THREAD

**Issue by bobwatcherx** [apollographql/apollo-client#9243]
i work in react js , but i have problem  using **refetchQueries** 
my console is not error  , but my UI is not relatime updated ,  
i **refresh manual my browser** this. data **updated**

can you help me , for updated Realtime using refetchQueries 

my code : https://stackblitz.com/edit/react-ts-h7xn7o?file=index.tsx

Preview My Code : https://react-ts-h7xn7o.stackblitz.io

**Comment by benhamiltonpro** [comment]
The current workaround is to call `client.refetchQueries` with the query used in the include option.
Docs found here: 
https://www.apollographql.com/docs/react/data/refetching/#clientrefetchqueries

**Comment by hwillson** [comment]
Issues here are reserved for bugs. For Apollo Client usage support, please use our [community forums](https://community.apollographql.com).
