### ISSUE TITLE
How do I disable cache for a certain type?

### ISSUE THREAD

**Issue by amitozalvo** [apollographql/apollo-client#9244]
Hello,

I have the following query: 
```
query Tickets {
  id
  tickets {
    currentStatusConnection {
      edges {
        timestamp
      }
    }
    currentStatus {
      label
    }
  }
}
```

The GraphQL response (which I have no control on) is returning this:
```
"tickets": [
      {
        "__typename": "Ticket",
        "id": "some_id",
        "currentStatusConnection": {
          "__typename": "TicketCurrentStatusConnection",
          "edges": [
            {
              "__typename": "TicketCurrentStatusRelationship",
              "timestamp": "2021-12-24T13:45:06.167Z",
            }
          ]
        },
        "currentStatus": {
          "__typename": "Status",
          "label": "Resolved"
        }
      }
]
```

**There are 4 types here**
- Ticket (cached using **id**)
- Status (cached using **label**)

**And**
- TicketCurrentStatusConnection (Should not be cached!)
- TicketCurrentStatusRelationship (Should not be cached!)

I want to prevent Apollo from caching these 2 types since they are not really objects and will override eachother.

How can it be done in Apollo Client?

**Comment by hwillson** [comment]
@amitozalvo assuming not using the `currentStatusConnection` field in your selection set (to avoid pulling in `TicketCurrentStatusConnection` and `TicketCurrentStatusRelationship`) isn't an option, you might want to look into how [field policy `merge` functions](https://www.apollographql.com/docs/react/caching/cache-field-behavior/#the-merge-function) work. The `merge` API gives you fine-grained control over cache writes, meaning you can just drop the data you don't want to keep.
