### ISSUE TITLE
Apollo Plugin Issue While Fetching Status Code On ApolloInterceptor.

### ISSUE THREAD

**Issue by prabha32** [apollographql/apollo-client#9250]
I am trying to log the status code for success response from interceptAsync, 
passing the full context but unable to fetch the status code back. Can you please check this method 
 public func proceedAsync<Operation: GraphQLOperation>(
    request: HTTPRequest<Operation>,
    response: HTTPResponse<Operation>?,
    completion: @escaping (Result<GraphQLResult<Operation.Data>, Error>) -> Void) {}
Is it possible to send the success response from this method to our app.

**Comment by hwillson** [comment]
@prabha32 please re-open this issue in the https://github.com/apollographql/apollo-ios repo.
