### ISSUE TITLE
Is it a good idea to make one graphql response type for all queries and mutations?

### ISSUE THREAD

**Issue by Gentlee** [apollographql/apollo-client#9252]
What if we make one type that includes all state user can get from the backend. Lets call it `AppState`.

And there will be only one query `getAppState`, and all mutations will return `AppState` as well so that clients can access any field they need, and if you use apolloClient, clients' cache will update automatically.

We can get all state on user login without any problem.

Is it a bad idea?

Originally asked [here](https://stackoverflow.com/questions/70499663/is-it-a-good-idea-to-make-one-graphql-response-type-for-all-queries-and-mutation)

**Comment by hwillson** [comment]
Issues here are reserved for bugs. Please post this question on our [community forums](https://community.apollographql.com).
