### ISSUE TITLE
Not triggering query when landing on page after a mutation that changes data

### ISSUE THREAD

**Issue by ItzaMi** [apollographql/apollo-client#9253]
**Intended outcome:**
I have two routes: `/test/` and `/test/:id`.
On `/test/` I have a list of `events` and it's only made of events that haven't been `resolved`
On `/test/:id` I have a `mutation` to mark an `event` as `resolved`, and, on success, I'm redirecting the user back to `/test/`. This success means that the `event` should no longer appear on `/test/` and I'm expecting a new request to get the list of `events`.

```javascript
// my file with the mutation
  const [eventResolveMutation] = useEventResolveMutation({
    onCompleted: () => {
      showSuccessToast(
        `${t('form:threat-resolved')}! ${t('general:threat')} ${t(
          'form:has-been-resolved'
        )}.`
      )

      setTimeout(() => {
        navigate('/threats/live')
      }, 2000)
    },
    onError: (error: ApolloError) => {
      showErrorToast(error.message)
    },
  })

  const handleEventResolveClick = (id: string) => {
    eventResolveMutation({ variables: { id: id, isResolved: true } })
  }

return (
  <button onClick={() => handleEventResolveClick(id)}>Press</button>
)
```

```javascript
// my file with the `events` query
// the results are displayed in a table, which is way I have `currentPage` and `pageSize` in them

  const [getEvents, { loading, data }] = useEventsLazyQuery()

  useEffect(() => {
    getEvents({
      variables: {
        page: currentPage,
        pageSize: paginationSizeOptions[chosenDropdownIndex],
        isThreat: true,
        isResolved: false,
      },
    })
  }, [chosenDropdownIndex, currentPage, getEvents])
```

**Actual outcome:**
Once I press the `button` that triggers the mutation and I'm redirected to the `/tests`, I can see that I'm landing inside the `useEffect` by `logging` something. What I don't see is a request made via `getEvents`, which is expected to happen since all the functionalities with the page work

**How to reproduce the issue:**
_I'm not able to provide a working piece of code for this, I'm sorry_

```javascript
// my graphqlclient.ts

import {
  ApolloClient,
  ApolloLink,
  createHttpLink,
  InMemoryCache,
} from '@apollo/client'

const serverUrl = () => {
  switch (process.env.REACT_APP_ENVIRONMENT) {
    case 'staging':
      return 'env'

    case 'production':
      return 'env'

    default:
      return 'env'
  }
}

const cleanTypeName = new ApolloLink((operation, forward) => {
  if (operation.variables) {
    const omitTypename = (key: string, value: any) =>
      key === '__typename' ? undefined : value

    operation.variables = JSON.parse(
      JSON.stringify(operation.variables),
      omitTypename
    )
  }

  return forward(operation).map((data) => data)
})

const httpLink = createHttpLink({
  uri: serverUrl(),
  credentials: 'include',
})

const httpLinkWithTypenameHandling = ApolloLink.from([cleanTypeName, httpLink])

const client = new ApolloClient({
  link: httpLinkWithTypenameHandling,
  cache: new InMemoryCache(),
  defaultOptions: {
    watchQuery: {
      fetchPolicy: 'cache-and-network',
    },
  },
})

export default client
```

**Versions**
  System:
    OS: macOS 11.2.3
  Binaries:
    Node: 14.18.1 - /opt/homebrew/opt/node@14/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 6.14.15 - /opt/homebrew/opt/node@14/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Safari: 14.0.3
  npmPackages:
    @apollo/client: 3.5.5 => 3.5.5

**Comment by hwillson** [comment]
@ItzaMi it sounds like your mutation isn't returning enough details for Apollo Client to know how to effectively update the specific event in the cache (it's difficult to tell without seeing your GraphQL operations). You can either adjust your mutation to do this or consider using something like the `useMutation` [`update`](https://www.apollographql.com/docs/react/data/mutations/#the-update-function) function to update the cache directly yourself. The [Updating the cache directly](https://www.apollographql.com/docs/react/data/mutations/#updating-the-cache-directly) section of the docs should help here.
