### ISSUE TITLE
Next.js - Unable to handle error, error: Response not successful

### ISSUE THREAD

**Issue by SirMishaa** [apollographql/apollo-client#9258]
Well, I'm a little dumpy. I will try to explain my problem as clearly as possible.

I use Apollo client to do my GraphQL queries. I also use NextJS.
I have a page that needs to be rendered on the server side for SEO reasons. 

So I have a ``getProductFromSlug`` function that allows me to execute my request.
```ts
export const getProductFromSlug = async (slug: string) => {
  const productRequest = gql`
    query getProductBySlug($slug: String!) {
      product(slug: $slug) {
        name
      }
    }
  `
  const { data, errors } = await apolloClient.query<{
    product: Partial<Product>
  }>({
    query: productRequest,
    variables: {
      slug,
    },
  })

  if (Array.isArray(errors) && errors.length > 0) {
    return {
      errors,
    }
  }

  return {
    data,
  }
}
```
Here's ``getServerSideProps`` to pass data to page 
```ts
export const getServerSideProps = async (
  context: GetServerSidePropsContext
) => {
// ...
const requestData = await getProductFromSlug(context.params.slug as string) // The page crash here, because we don't try / catch the apollo query (but if we do, we cannot access to the errors variable
}
```
The problem is that I don't know how I should do my error handling. For example, here NextJS (typically, Apollo client) is returning an error: 
> Error: Response not successful: Received status code 500
> This error happened while generating the page. Any console logs will be displayed in the terminal window

But I can't use a try/catch because I'll lose access to variable errors (``{data, errors} = await apolloClient.query``), so I'm unable to return why error happened (besides, I don't see the point since we can use the ``errors'' variable)

**Why do I have to go through a try catch? And how can I recover the error in this case?**
I appreciate your help, thank you!

![image](https://user-images.githubusercontent.com/42717232/147864121-f2964c34-caa1-46c4-92f8-4723f4eabe6b.png)
Versions : 
- "graphql": "^16.2.0",
- "next": "12.0.2",

**Comment by SirMishaa** [comment]
I see that ``const { data, errors } = await apolloClient.query`` (can) return as errors a ``ReadonlyArray<GraphQLError>`` type.

But because it throws an exception, I'm not able to access this variable anymore since I'm leaving the try scope (to be in catch scope). 
And because of this, I can't do my error management... I can avoid the fact that apollo client throws an exception when a request fails and just deal with `{ errors }`

**Comment by hwillson** [comment]
@SirMishaa this doesn't sound like an Apollo Client bug, which issues here are reserved for. For further help with error handling, please post on our [community forums](https://community.apollographql.com).
