### ISSUE TITLE
Bug - doesn't get errors while using cache-first policy

### ISSUE THREAD

**Issue by rajeshkumaru** [apollographql/apollo-client#9260]
**Versions being used:**

apollo/client: "3.x"
apollo-angular: "2.x"
angular/core: "9.x"

**Intended outcome:**
I am using **cache-first** fetchPolicy and seems errors are not being preserved correctly

i.e. If I land on one of pages of application with `Internal server errors` , then visit another page and come back to the same page(on which i have landed initially), I should get errors from preserved state.

**Actual outcome:**

The error is not coming back from preserved state, or may be it is not being preserved.
If i replace cache-first with **no-cache**, then it will work fine as it will always return me fresh state by hitting backend call.

**Comment by hwillson** [comment]
@rajeshkumaru please provide a small runnable reproduction that demonstrates the issue you're seeing and we'll re-open this. Thanks!
