### ISSUE TITLE
the variables variable  passed read function always empty  

### ISSUE THREAD

**Issue by videni** [apollographql/apollo-client#9262]
## Define field policy

```
new InMemoryCache({
    typePolicies: {
      Customer: {
        fields: {
          imageUrl: {
            read(_, { variables }) {
              console.log(variables); //aways empty, why? 
              if (variables.email) {
                return `https://www.gravatar.com/avatar/${SparkMD5.hash(variables.email)}`
              }

              return null
            }
          }
        }
      }
    }
  }
```

## Query data
```
const GET_CUSTOMER_PROFILE = gql`
query getCustomerProfile{
  customer{
    id
    locale
    createdAt
    username
    email
    enabled
    imageUrl @client
  }
}

 const { loading, error, data } = useQuery(GET_CUSTOMER_PROFILE)

```

## the data is rendered at server side

![image](https://user-images.githubusercontent.com/4058341/148006680-c5cd9c59-8eb9-4fc8-bfe4-f24e3621d000.png)

the `variables` passed to read funtion is always empty, why please? 

## apollo/client Version

    "@apollo/client": "^3.5.6",

**Comment by hwillson** [comment]
@videni your `getCustomerProfile` query doesn't use any variables so there aren't any variables available in the `imageUrl` read function. Please use our [community forums](https://community.apollographql.com) for usage questions.

**Comment by videni** [comment]
@hwillson , do you mean this [Local-only fields in Apollo Client](https://www.apollographql.com/docs/react/local-state/managing-state-with-field-policies/#storing-local-state-in-reactive-variables)?  I read it several times, the avatar url is derived from existing data, that is why I didn't use the reactive variable. If I am right , we got two ways to use local data, one is the derived data, like the imageUrl above,  or  client local only , such as access token, we can save it into local storage , then use the reactive variable to access it in graphql query.
