### ISSUE TITLE
[useLazyQuery] it acts like useQuery after the first query initiation

### ISSUE THREAD

**Issue by rbals0445** [apollographql/apollo-client#9263]
**Intended outcome:**

when after first useLazyQuery execution, it re-execute automatically when changes variables. it acts like a useQuery.
In docs, `executing queries in response to events besides component rendering.` is it correct execution? if so docs should be updated.

When `only` we clicked `clickB Button` it calls lazyFetch. (clickC is just useState hooks)  but, when we clicked `clickB` and `clickC` in order, it called lazyQuery twice. 

**Actual outcome:**

You can check the result imgs below.

**How to reproduce the issue:**

```

const Body = () => {
    const [curpage, setPage] = useState(1);
    const [list, setList] = useState([]);
    const [hasMore, setHasMore] = useState(true);
    const [totalPage, setTotalPage] = useState(0);
    const [text, setText] = useState();

    const val = useContext(MyContext)

    const [lazyFetch, {data, fetchMore}] = useLazyQuery(BID_DATA_LIST_QUERY, {
        variables: {
            page: curpage,
            region: text,
        }, onCompleted: (data) => {
            console.log("completed")
            setList(list => [...list, ...data.getDataList.listData]) // data.getData 이거는 또 안됨

            if (totalPage === 0) {
                setTotalPage(data.getDataList.totalPage);
            }
        },
    })

    return (
        <>
            <button onClick={() => {
                lazyFetch();
                if (curpage === totalPage) {
                    setHasMore(false);
                }
            }}>clickB
            </button>

            <button onClick={() => {
                setText("서울")
            }}>clickC
            </button>
        </>)


}
const BodyContainer = styled.div`
  margin: 0 auto;
  //width: 1728px;
  width: 60vw;
`

export default Body;
```
1.  click Order  (Unexpected)
- ClickB -> ClickC
-> ClickC does not call lazyFetch(), but automatically call lazyQuery and called onCompleted callback.
![image](https://user-images.githubusercontent.com/60285506/148030211-44fbcbd1-bb83-42a1-a122-1726367efe41.png)

2. click Order (Expected)
- ClickC -> ClickB
-> when clickC there is no call lazyFetch, and when clickB it calls lazyFetch.
![image](https://user-images.githubusercontent.com/60285506/148030419-bb3300e7-eff4-49e8-890d-213bef46426c.png)

**Versions**

```
 @apollo/client : "3.5.6"
Mac Latest version
Node version : v16.13.1
npm version : v8.1.2
```

plz clarify this situation and if it is error, change the docs plz. it wastes my time....

**Comment by hwillson** [comment]
@rbals0445 this is how `useLazyQuery` was designed. See this [comment](https://github.com/apollographql/apollo-client/issues/7484#issuecomment-925314635) for more details. We'll get this updated in the docs (which is being tracked in that issue).
