### ISSUE TITLE
useLazyQuery - @apollo/client "3.3.20"

### ISSUE THREAD

**Issue by Green-Peter** [apollographql/apollo-client#9268]
Hi 

I think we have a bug in useLazyQuery: 

```js
  const [callForData, { data, error, called }] = useLazyQuery(GET_DATA_GQL, {
    variables: { userId },
    fetchPolicy: 'network-only',  // caused to infinit loop on second call 
  })
```

when calling to a call data more than one time with `network-only` it will call also all previous calls and the result updates the same effect, if I remove the policy the it works as expected. it feels like the subscription wasn't cleared in some effects inside the hook.

**Comment by bignimbus** [comment]
Hi @Green-Peter, thanks for your patience!  Could you share a runnable reproduction using [this template](https://github.com/casertap/react-apollo-error-template) so that a community member or maintainer can help narrow down a solution?  Thanks a bunch 🙏🏻

**Comment by alessbell** [comment]
Hi @Green-Peter 👋  I'll second @bignimbus here - we have tests for `useLazyQuery` combined with a `network-only` fetch policy, so without more information here it's impossible to say whether there's a bug. I'll close out this issue, but if you have a reproduction or additional information here, feel free to comment or open a new issue. Thanks!
