### ISSUE TITLE
Feature: Revamped SSR approach

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-client#9272]
Server-Side Rendering refers to the page processing technology where the HTML structure of the page is spliced on the server side.  React SSR (server-side rendering) gives better SEO (search engine optimization) and a feeling of quicker loading speeds.

This is a placeholder issue for upcoming Apollo Client SSR work to offer better support for [React 18s SSR Architecture](https://reactjs.org/blog/2022/03/29/react-v18.html)

**Comment by wintercounter** [comment]
I was wondering if we can get any details regarding the plans.

**Comment by alessbell** [comment]
The Apollo Client team, and @phryneas in particular, has been discussing SSR in the context of newer experimental React APIs, and that work will have its own tracking issue(s).

For now, I'll close this issue, but we may re-open/re-purpose as needed. Thanks!
