### ISSUE TITLE
Feature: Custom scalar enhancements

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-client#9273]
This is a placeholder issue for upcoming Apollo Client custom scalar work. This issue will be updated with more details shortly.

### Related Issue

https://github.com/apollographql/apollo-feature-requests/issues/368

**Comment by Ginhing** [comment]
Greetings, is it for #8857 ?🤩

**Comment by JeffJankowski** [comment]
Can we get an update or projected timeline on this work? The original issue is approaching it's 6-year birthday, and this seems like a pain-point for many developers with a graphql schema greater than trivial complexity.

I'd really like to avoid migrating our front-end grapqhl library, but urql has had an exchange to address this use case for years now. 
https://github.com/clentfort/urql-custom-scalars-exchange

**Comment by jpvajda** [comment]
@JeffJankowski We totally hear you on the length this had been unresolved. We are actually doing some planning for the 2nd 1/2 of 2022 at the moment and this feature is the top of our list of things we'd like to release. please stay tuned!

**Comment by alessbell** [comment]
Since we already have https://github.com/apollographql/apollo-feature-requests/issues/368 to document the underlying feature request, I'll close this issue out for now.
