### ISSUE TITLE
refetchQueries throws errors when refetching a skipped useQuery

### ISSUE THREAD

**Issue by kaldenficklin-zz** [apollographql/apollo-client#9276]
**Intended outcome:**

```js
const myData = useQuery(GET_DATA, {
    skip: !id,
    variables: { id },
});

// elsewhere in the code
client.mutate({
  mutation: ADD_DATA,
  refetchQueries: [GET_DATA]
});
```

Expected a cached / previously called version of the GET_DATA query to be refetched that had variables (id) properly set and was not skipped

**Actual outcome:**

`GET_DATA` is refetched with variables as an empty object, even though there were previous results in the cache that had `id` defined

**How to reproduce the issue:**

Use the snippet above to call `GET_DATA` once with a variable with `id` set, then a second time where `id` is not set and the query is skipped. 

Then use the snippet of code to call client.mutate with refetchQueries set.

The resulting network request will fail because it will be missing required variables.

**Versions**

```
  System:
    OS: macOS 12.0.1
  Binaries:
    Node: 16.5.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.1.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 94.0.1
    Safari: 15.1
  npmPackages:
    @apollo/client: ^3.4.10 => 3.4.17 
```

The expectation our team has is that any call to refetch queries will use the last valid / not skipped version of the query

**Comment by kaldenficklin** [comment]
cc: @cvburgess

**Comment by bignimbus** [comment]
Hi @kaldenficklin-zz 👋🏻 thanks for your patience.  The `refetchQueries` property does support using a function which could be a good fit for defining this sort of dynamic behavior:

```ts
// elsewhere in the code
client.mutate({
  mutation: ADD_DATA,
  refetchQueries: () => [{ query: GET_DATA, variables: { id }]
});
```

Though your use case seems pretty straightforward, I can imagine other cases where skipping a query doesn't necessarily mean that the query is invalid.  Eager to hear what criteria you'd propose here 🙏🏻  thanks!
