### ISSUE TITLE
Uncaught Invariant Violation: client.watchQuery cannot be called with fetchPolicy set to "standby"

### ISSUE THREAD

**Issue by ritika-wal** [apollographql/apollo-client#9279]
In windows the project is running fine but in ubuntu i am facing the above error . the packages with versions are mentioned below.
"apollo-client": "^2.6.10",
ubuntu - 22.04

Can anybody just help me out with this.
![Screenshot from 2022-01-08 16-00-26](https://user-images.githubusercontent.com/94036495/148640929-630df485-2d53-4c8c-bee8-f7ef39ca179b.png)

**Comment by shubham-developer** [comment]
I'm facing the same issue. I've tried to use apollo client latest version though but in that case there is re-rendering issue.

**Comment by hayata-yamamoto** [comment]
Also I am +1

**Comment by Akshaypal8** [comment]
I am also facing the same issue.

**Comment by WagdySamih** [comment]
I am having same issue too with @apollo/client version 3.4.0

**Comment by Amar-01** [comment]
Funnily enough, it ran for me on Windows, but while using WSL(Linux) it threw this error.  Change Apollo server version to `~3.4.0` in `package.json` and `npm install`.

**Comment by hssdiv** [comment]
had different error at first: "_undefined is not an object (evaluating 'obsQuery.reobserve.bind')_".
Somehow managed to turn it into  _"client.watchQuery cannot be called with fetchPolicy set to "standby"_.

turns out that downgrading @apollo/client to 3.4.0 fixes both errors

**Comment by hssdiv** [comment]
> I am having same issue too with @apollo/client version 3.4.0

I think it might be related to 'graphql' version from package.json
I have "graphql": "^15.8.0",

**Comment by dweep119** [comment]
Still, I am facing the same issue, Are there any steps to fix this?

**Comment by phryneas** [comment]
For some reason, you seem to have installed `apollo-client`, `@apollo/client` and `@apollo/react-hooks` installed at the same time.

Please make sure to uninstall `apollo-client` (this is Apollo Client 2, a very outdated version) and `@apollo/react-hooks` (this is not needed anymore and you should use `@apollo/client/react` instead).

**Comment by phryneas** [comment]
Since this error message is not part of Apollo Client 3 anymore, I think I can safely close this issue.

If you still encounter this, please update your dependencies.
