### ISSUE TITLE
Refetch Query only happens once despite multiple calls

### ISSUE THREAD

**Issue by dabellator** [apollographql/apollo-client#9308]
Two different mutations are called asynchronously one after the other. Both modify data that is used by the same query, so both specify `refetchQueries: [GET_MY_DATA]`. The second call starts when the first one ends, which is the same time the refetch starts. The second call ends before the refetch is done.

**Intended outcome:**
The expectation is that `GET_MY_DATA` would be refetched twice, to make sure it has the most up to date data. 

**Actual outcome:**
What actually happens is that the query is only refetched once. Since the second mutation that should trigger a refetch happens during an existing refetch, it doesn't seem like Apollo keeps a queue of all refetches.

**How to reproduce the issue:**
* Create two separate mutations and one query, and make the query take longer than the mutations
* Set each mutation to trigger a refetch of the query
* Trigger the second mutation to occur immediately after the first resolves

Thanks for the help, I really appreciate all the great work the team is doing!

```  System:
    OS: macOS 12.1
  Binaries:
    Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
    Yarn: 1.22.11 - ~/sites/plato/node_modules/.bin/yarn
    npm: 8.1.4 - ~/.nvm/versions/node/v14.18.2/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Safari: 15.2
  npmPackages:
    @apollo/client: ^3.3.15 => 3.4.9 
    apollo: ^2.33.1 => 2.33.6 ```

**Comment by SiteSeerBE** [comment]
I came upon this post researching the same problem. Ours was resolved by returning ID's in the mutation query. We don't do anything with these ID's but apparently it is mandatory to return them.

**Comment by Cnoor0171** [comment]
This issue is still there for us, even if we return IDs in the mutation. Are there any workarounds?

**Comment by bignimbus** [comment]
Hi all 👋🏻  in order to expedite a resolution, could you share a reproduction so the team can observe the actual behavior and compare against the expected behavior?  Here's a [template](https://github.com/apollographql/react-apollo-error-template/generate) that might be helpful - thanks so much!
