### ISSUE TITLE
DOCUMENTATION: Release notes 3.5.6 and 3.5.7 missing

### ISSUE THREAD

**Issue by FreTimmerman** [apollographql/apollo-client#9316]
tags for [v3.5.6](https://github.com/apollographql/apollo-client/releases/tag/v3.5.6) and [v3.5.7](https://github.com/apollographql/apollo-client/releases/tag/v3.5.7) exist, but these versions are not mentioned in the [releases](https://github.com/apollographql/apollo-client/releases)

**Comment by benjamn** [comment]
@FreTimmerman [`CHANGELOG.md`](https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md) is the canonical document, which always includes every release. Please refer to that document in the future, and sorry for the confusion!
