### ISSUE TITLE
`Network request failed` for Production endpoint on android

### ISSUE THREAD

**Issue by hexdecimal16** [apollographql/apollo-client#9342]
My production url (https://api.stacket.in:4000/graphql) works on web but when I run it on my android device i get Network request failed

**Intended outcome:**

should be able to retrieve data on web as well as android

**Actual outcome:**

Network request failed

**How to reproduce the issue:**

1. Download test.zip and try to run it on an android device

**Versions**

```
  System:
    OS: Linux 5.13 Ubuntu 20.04.3 LTS (Focal Fossa)
  Binaries:
    Node: 14.18.3 - /usr/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 6.14.15 - /usr/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 96.0
  npmPackages:
    @apollo/client: ^3.5.7 => 3.5.7
```
[test.zip](https://github.com/apollographql/apollo-client/files/7917155/test.zip)

**Comment by hexdecimal16** [comment]
fixed it!

**Comment by IrfanKhan01** [comment]
@hexdecimal16  would you like to mention how did you fix the issue? It is occurring for me in iOS
