### ISSUE TITLE
[@apollo/client/link/core] Typescript types are broken

### ISSUE THREAD

**Issue by JustFly1984** [apollographql/apollo-client#9349]
I got next error in my app:

```
node_modules/@apollo/client/link/core/types.d.ts:20:18 - error TS2430: Interface 'FetchResult<TData, C, E>' incorrectly extends interface 'ExecutionResult<ObjMap<unknown>, ObjMap<unknown>>'.
  Types of property 'data' are incompatible.
    Type 'TData | null' is not assignable to type 'ObjMap<unknown> | null'.
      Type 'TData' is not assignable to type 'ObjMap<unknown> | null'.
        Type 'TData' is not assignable to type 'ObjMap<unknown>'.

20 export interface FetchResult<TData = {
```

my tsconfig:

```json
{
  "compilerOptions": {
    "allowJs": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "preserveValueImports": false,
    "isolatedModules": true,
    "jsx": "preserve",
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitAny": true,
    "resolveJsonModule": true,
    "skipLibCheck": false,
    "strict": true,
    "alwaysStrict": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "target": "esnext",
    "noUncheckedIndexedAccess": true,
    "exactOptionalPropertyTypes": true,
    "importsNotUsedAsValues": "error",
    "noImplicitReturns": true,
    "noPropertyAccessFromIndexSignature": true,
    "incremental": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "types/*.d.ts"],
  "exclude": ["node_modules"]
}
```

**Comment by KeithGillette** [comment]
Getting same `TS2430` error on `tsc` with `skipLibCheck: false` with `@apollo/link@1.2.14` & `graphql@16.5.0`.

**Comment by phryneas** [comment]
@AndrejGajdos can you please provide a [TypeScript Playground](https://www.typescriptlang.org/play/) that shows this issue? Going by only the information we have here in the issue we will not be able to reproduce it.

**Comment by timonmasberg** [comment]
this just came up for us, using 3.10.8

**Comment by phryneas** [comment]
@timonmasberg can you please provide a [TypeScript Playground](https://www.typescriptlang.org/play/) or a minimal reproduction repo that shows this issue? Going by only the information we have here in the issue we will not be able to reproduce it.

**Comment by jerelmiller** [comment]
Hey all 👋 

I do believe this issue is now outdated. As @phryneas said, `FetchResult` is a [type](https://github.com/apollographql/apollo-client/blob/17dc2e808b53ef29d576c98cc6fdc20c33094e59/src/link/core/types.ts#L102-L108) in more modern versions of the client, not an `interface`, so I believe this specific TS bug is no longer possible. 

If you see similar issues, we'd kindly ask that you open a new issue with a reproduction so we can dig in further. I'm going to go ahead and close this issue. Thanks!
