### ISSUE TITLE
How to request same query consecutively using different arguments. 

### ISSUE THREAD

**Issue by JayKim88** [apollographql/apollo-client#9352]
Hello, Thank you all in advance :)

I want to request same query one by one to get google signed url from server.
However, i found that the only query completing is last query even though imageFiles has 2 files(Blob type).
The example is as below;
If i click the upload button, the below code will run. 
```js
  const uploadHandler = async () => {
              await Promise.all(
                imageFiles.map(async (image) => { // imageFiles = [imagefile1, imagefile2] 
                  const { data } = await getSignedUrl({
                    variables: {
                      fileName: `${String(image.name)}.png`,
                      imageUploadType: GcpUploadType,
                      sellerId: sellerId,
                    },
                  });
                  return data;
                })
              );
            };
```
```js
  const [getSignedUrl, { data, loading: signedLoading }] =
    useGetImageUploadSignedUrlLazyQuery({
      fetchPolicy: 'no-cache',
      notifyOnNetworkStatusChange: true,
    });
```
In my expectation, the result should be 2 different data but same data which is from the last query request using imagefile2..
Is there something i missed ? or Is there other way i can request same query without using Promise.all ? 
Sincerely hope to get valuable comment from you. Thank you so much~.

**Comment by ramonwenger** [comment]
What does your schema say about the ID of those two requests? Could it be possible that one query gets completed, Apollo stores it in the cache, and then completes the other one with the cached data, because they have the same ID? @JayKim88

**Comment by JayKim88** [comment]
> ```js
> useGetImageUploadSignedUrlLazyQuery
> ```

Sorry for late reply. I solved the above problem by making 2 same queries with different names. Thank you!:)
