### ISSUE TITLE
onError behavior is not working in useQuery; not consistent between useQuery and useMutation

### ISSUE THREAD

**Issue by don-hover** [apollographql/apollo-client#9357]
**Intended outcome:**
The `onError` handler is expected to fire on **any** GraphQL error.
The `onError` handler's behavior should be consistent with the `error` state returned from the hook.

**Actual outcome:**
The `onError` handler only fires for `400` or `500` status error, but doesn't fire for GraphQL responses that return with a `200` status but that are error responses that include an `errors` object.
The `error` state returned from the hook is non-null for all of the above cases, making `onError` and `error` not consistent.

This has been mentioned in previous issues here:
https://github.com/apollographql/apollo-client/issues/8313#issuecomment-880188193

**Versions**
apollo-client 3.5.6

**Comment by xbaun** [comment]
Stumbled across the same problem. The problem seems to be that only the responses with http status codes `>= 300` are treated as an error response:
https://github.com/apollographql/apollo-client/blob/8beb4820edc6352996e08f7f73bde3573f1eb666/src/link/http/parseAndCheckHttpResponse.ts#L30-L37

As a workaround, I need to set an appropriate http status code for any exception on the server side, as described here https://www.apollographql.com/docs/apollo-server/data/errors/#returning-http-status-codes
Ironically, the docs advises against changing the status code because of errors :sweat_smile:

**Comment by GabrielNastase** [comment]
Have the same problem here. onError on useQuery should be consistent with the error property returned by useQuery. 
onError only fires on networkErrors ignoring graphQL errors.

**Comment by don-hover** [comment]
> Had the same problem here. onError on useQuery was not consistent with the error property returned by useQuery. onError only fired on networkErrors ignoring graphQL errors. Then I find out that, at least for me, the default error policy was set probably to ignore. So I set the errorPolicy to 'none' that in the docs is the default, and now the onError callback fires correctly on graphQL errors
> 
> ```js
> const { data, loading , error } = useQuery(
>     gql(currentQuery),
>     {  onError, errorPolicy: 'none' }
>   );
> ```

@GabrielNastase 

We have our ApolloClient set up with
```.ts
      errorPolicy: 'all',
```

And we still have the problem that is described here.  And regardless, there's no reason, and documentation saying so, that changing the error policy should stop the error handling from working.

**Comment by don-hover** [comment]
@benjamn Has anyone on the team taken a look at this or have any suggestions for this?

Thanks.

**Comment by zenghou** [comment]
I'm experiencing a similar issue, and have to fall back on using `onComplete` to parse the errors instead of `onError`

**Comment by mbergeronupgrade** [comment]
Experiencing a similar issue, setting errorPolicy to 'all' stops calling the onError handler.

**Comment by jerelmiller** [comment]
Hey all 👋 ! Thanks for your patience on this issue.

Out of curiosity, does the result that comes back have partial data? I'm working to track this down and, from what I gather, I think this can be replicated if errors comes back with partial data. 

Can you confirm if this is the case?

**Comment by jerelmiller** [comment]
I have been able to reproduce this behavior with some failing tests. Check out [this diff](https://github.com/apollographql/apollo-client/compare/9357-onerror-behavior-is-not-working-in-usequery-not-consistent-between-usequery-and-usemutation?expand=1#diff-d2c5924a921e0cb39c6d9910863c40eaab64a7901aa9414ab702a6eda79f7e82R2019-R2146) to see if this looks like the behavior you'd expect that currently isn't happening.

I'll try and get a PR up to fix these soon. Thanks for reporting this bug!

**Comment by jerelmiller** [comment]
Hey all 👋 !

Version [v3.7.4](https://github.com/apollographql/apollo-client/releases/tag/v3.7.4) was just released which contains this fix. Thanks again for submitting the issue!
