### ISSUE TITLE
useLazyQuery's execute function rejects on failed requests as of v3.5.8

### ISSUE THREAD

**Issue by skrivle** [apollographql/apollo-client#9368]
Hi there 👋 ,

First of all, thanks for all the great work on Apollo Client 💪 ! 

I am not 100% sure this is a bug, but we ran into a failing test when trying to upgrade to v3.5.8

**Intended outcome:**

We're using `useLazyQuery()` and we think the promise returned from `execute` should be resolved even if the request fails. I believe it's also stated like that in the docs.

> Function that can be triggered to execute the suspended query. After being called, useLazyQuery behaves just like useQuery. The useLazyQuery function returns a promise that fulfills with a query result when the query succeeds or fails.

**Actual outcome:**

We noticed that the promise returned from the `execute()` function is rejected whenever the request fails. This results in unhandled rejection errors and failing tests 

**How to reproduce the issue:**

https://github.com/skrivle/lazy-query-error

**Versions**

System:
    OS: macOS 11.6.2
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Firefox: 95.0
    Safari: 15.3
  npmPackages:
    @apollo/client: 3.5.8 => 3.5.8

**Note** this does not happen on 3.5.7

Thanks 🙏

**Comment by brainkim** [comment]
🙇‍♂️🙇‍♂️🙇‍♂️ Sorry to hear that you’re having trouble with this! I was asked in another issue to “make `useLazyQuery()` reject like `useMutation()`,” but I forgot about unhandled rejections, and as the `useLazyQuery()` promise is usually floated, it probably makes sense to silently catch the promise somewhere. I’ll get a fix in soon.

**Comment by smac89** [comment]
I don't think this is fixed yet. I still get this error in version 3.6.2

**Comment by benjamn** [comment]
@smac89 Have you tried `npm i @apollo/client@next` to install 3.6.3? We are aware of some unresolved issues in that version, so we have not promoted it to `latest` on npm just yet, but it's published and installable, for diagnostic purposes.
