### ISSUE TITLE
Apollo Client cache is storing/retrieving the same data for two queries with different query variables 

### ISSUE THREAD

**Issue by TasinIshmam** [apollographql/apollo-client#9379]
**Problem Description:** Hi, I'm having an issue with the cache when implementing pagination and would really appreciate some help. I'm creating a Hackernews-clone for a GraphQL focused [front-end tutorial](https://www.howtographql.com/react-apollo/0-introduction/) using Apollo Client and React.  To implement pagination in this application, the query that fetches various links (links are the individual submissions that a user can make) has two arguments `skip` and `take`. 

However, after the first network call, when there is a cache hit, the data returned from the cache does not change, regardless of the value of `skip` and `take`. I'm not quite sure if this is a bug, it's more likely that it's something that I'm doing incorrectly. Nevertheless, would really appreciate your help on this!  

**Further Details**: 

Here is the relevant portion of my graphql schema: 

```graphql
type Query {
  feed(
    filter: String
    skip: Int
    take: Int
    orderBy: LinkOrderByInput
  ): Feed!
}

type Feed {
  id: ID!
  links: [Link!]!
  count: Int!
}

type Link {
  id: ID!
  description: String!
  url: String!
  postedBy: User  
  votes: [Vote!]!
  createdAt: DateTime!
}

# ... remaining types like User and Vote. The important part here is the Feed query, which returns an array of links. 

```

`LinkList.js` is the React component that is responsible for calling the feed query and based on the current page, passing the appropriate `skip` and `take` arguments. 

```js
// LinkList.js component 

// The GraphQL query
export const FEED_QUERY = gql`
    query FeedQuery(
        $take: Int
        $skip: Int
        $orderBy: LinkOrderByInput
    ) {
        feed(take: $take, skip: $skip, orderBy: $orderBy) {
            id
            links {
                id
                createdAt
                url
                description
                postedBy {
                    id
                    name
                }
                votes {
                    id
                    user {
                        id
                    }
                }
            }
            count
        }
    }
`;

// Calculates and returns skip, take and orderBy variables for the query. 
const getQueryVariables = (isNewPage, page) => {
  const skip = isNewPage ? (page - 1) * LINKS_PER_PAGE : 0;
  const take = isNewPage ? LINKS_PER_PAGE : 100;
  const orderBy = { createdAt: 'desc' };
  return { take, skip, orderBy };
};

const LinkList = ({client}) => {
  
 
  const {isNewPage, page} = getPage();  // irrelevant business logic to fetch the current page number

// Query in question 
  const {
    data,
    loading,
    error,
    subscribeToMore
  } = useQuery(FEED_QUERY, {
    variables: getQueryVariables(isNewPage, page),
    fetchPolicy: "cache-first"      //   the default cache policy. Right now I have to turn caching off by changing this option to "cache-and-network"  manually because of the bug in question. 
  });

  return (
  // rendering business logic. Possibly not important
  );
}
```

Full implementation of `LinkList.js` is available [here](https://github.com/howtographql/react-apollo/blob/master/src/components/LinkList.js) 

**Intended outcome:**

I data returned to the cache should be unique to not just the query, but the query variables passed when executing the query. This is not happening at the moment, something that should be further clarified by the video in the next section. 

**Actual outcome:**

I created a video of what happens in the application. I also logged the data returned from `useQuery`, the query variables it was passed, along with data fetched _directly_ from the cache using `client.readQuery()`. 

https://user-images.githubusercontent.com/29299547/151802557-cbe0b90d-9acc-4e14-8cc2-1c34b5797734.mp4

**How to reproduce the issue:**

1. Clone the repository from [here](https://github.com/howtographql/react-apollo) 
2. Go to `./src/components/LinkList.js` and comment out  the `fetchPolicy` in [line 130](https://github.com/howtographql/react-apollo/blob/085b7bba8b22056d856a0b029afb92e46eff134d/src/components/LinkList.js#L130). This is to ensure that links are fetched from the client.
3. Follow the instructions in the readme to start the backend and frontend server. 
4. Create a few more links to test out pagination by going to `localhost:4000` and creating a few links with this mutation:
```
mutation CreatePrismaLink {
  post(
    description: "foo"
    url: "bar"
  ) {
    id
    description
    url
  }
}
```
5. Go to `http://localhost:3000/new/1` and try out moving between pages 

**Versions**
```
  System:
    OS: Linux 5.13 Ubuntu 20.04.3 LTS (Focal Fossa)
  Binaries:
    Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.4/bin/yarn
    npm: 8.1.3 - ~/.nvm/versions/node/v14.17.4/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 96.0
  npmPackages:
    @apollo/client: ^3.5.7 => 3.5.7 

```

**Comment by nxdefiant** [comment]
Did you try [Version 3.5.8](https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md) of apollo client?

> Fix refetch() not being called when skip is true.

**Comment by atarek12** [comment]
Try storing the variables in a `React.useState()` hook

**Comment by TasinIshmam** [comment]
> Did you try [Version 3.5.8](https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md) of apollo client?

@nxdefiant  unfortunately did not fix the issue. 

> Try storing the variables in a React.useState() hook

@atarek12  could you kindly elaborate? I assume by "the variables" you mean the `skip` and `take` arguments. These values get calculated when the `LinkList` component is instantiated or rendered, so they are updated with every re-render. [(Code here)](https://github.com/howtographql/react-apollo/blob/085b7bba8b22056d856a0b029afb92e46eff134d/src/components/LinkList.js#L106-L131) 

 When the `Previous` and `Next` buttons are called, the router takes it to the new page and `skip` and `take` are re-calculated again. It's not clear to me where I would call `setState` if I were to store the variables in a react hook.

**Comment by Akallabet** [comment]
I can confirm this is happening for me as well.
One info that might help: this bug seems to happen only with `graphql@16` (no problems with `graphql@15`)
Hope it helps @TasinIshmam

**Comment by TasinIshmam** [comment]
Thanks @Akallabet  

Unfortunately, the problem persists with `apollo/client` version ` 3.3.14` and later as well on my end. Could you kindly provide any instructions/steps to reproduce your fix?

**Comment by adamhooper** [comment]
@TasinIshmam This is a bug in your server code: it returns the same `id` for each query response.

Try this patch and your client will behave as expected:

```
diff --git a/server/src/resolvers/Query.js b/server/src/resolvers/Query.js
index 86094b6..347b073 100644
--- a/server/src/resolvers/Query.js
+++ b/server/src/resolvers/Query.js
@@ -18,7 +18,7 @@ async function feed(parent, args, context, info) {
   const count = await context.prisma.link.count({where});

   return {
-    id: 'main-feed',
+    id: `main-feed:${JSON.stringify(args)}`,
     links,
     count
   };
```

**Comment by TasinIshmam** [comment]
@adamhooper that makes perfect sense, thank you so much! 

I can confirm the problem is fixed.
