### ISSUE TITLE
How to use readQuery.

### ISSUE THREAD

**Issue by rossedwardsus** [apollographql/apollo-client#9397]
Hello.  I am trying to understand how to use readQuery.  I have looked at the documentation quite a few times but all it provides is a basic example that i find very difficult to understand.  It seems to say that you can do any normal query against the cache and it should work.  But whatever query i used returns a null value.

I have also read that it needs to mirror the query you originally used to get the data.  Which does work, but the problem is how do i then filter on that data?  

This is the query i am currently using:
query getOfferQuery( {
    offer(where: {offer_status_id: {_eq: "accepted"}}){
      id
    }
}

This returns the whole cache.  So then for example i would i then filter on a key for example called "created_at", where created_at is a date?

Thank you.

**Comment by benjamn** [comment]
The `readQuery` method returns `null` most often when there are missing fields. You can gain insight about what's missing by passing `returnPartialData: true` in the options, as a diagnostic tool.

As for your `where` argument, the cache doesn't understand arbitrary filtering arguments by default, but you could configure a field policy for the `Query.offer` field that takes `args` into account: https://www.apollographql.com/docs/react/caching/cache-field-behavior/

**Comment by rossedwardsus** [comment]
Hello.  The only field i am attempting to return is id.  Which exists.  There are other fields that do have null values but as a test i am only trying to return "id" and that is it.

As i mentioned it works if i include the exact query used in the originally useQuery statement.  But then i cant do any filtering on it.

**Comment by bignimbus** [comment]
Hi @rossedwardsus 👋🏻  thanks for your patience.  We really appreciate you reaching out!  I'm going to close this issue since it's more of a "Q&A" item.  Our [community forum](https://community.apollographql.com) is a great place to get specific support for implementation questions like this.  Looking forward to seeing you there if you still need an extra set of eyes on this 🙏🏻
