### ISSUE TITLE
Use readField outside of typePolicies

### ISSUE THREAD

**Issue by valerii15298** [apollographql/apollo-client#9398]
I am developing a helper(small wrapper) for apollo client. And it would be very useful to use readField function. But now it is possible only in typePolicies. I tried to find a way to use it in source code but unsuccessfully. How can I use readField outside of typePolicies?

**Comment by benjamn** [comment]
This is a bit of a hack, but there's a `details.readField` function in the details object passed to `cache.modify`:
```ts
cache.modify({
  id: cache.identify(...),
  fields: {
    // Picking __typename since it's a field that's always there:
    __typename(name, { readField }) {
      // Do something with readField (for example, store it elsewhere)...
      return name; // Don't change the __typename!
   },
})
```

**Comment by valerii15298** [comment]
@benjamn thank you very much.
