### ISSUE TITLE
apollo-client transforms response

### ISSUE THREAD

**Issue by kashif-nazar** [apollographql/apollo-client#9411]
I am working on a React application and I am facing an issue with Apollo client `(@apollo/client 3.3.6)`. I am not sure if I am missing some configurations or what. 

For a query, Apollo client somehow transforms my response i.e., the response that `useLazyQuery` returns is different that what I can see in Chrome's Network tab.

Network tab is showing the following response:
![image](https://user-images.githubusercontent.com/88034257/152969169-a52f820d-5ab7-41e9-81b1-f08478e35e8d.png)

However when I print response, it is:

    {
        "getProjectSetById": {
            "data": {
                "id": "3d8f3b49-5764-4da6-a9c4-5db0f2904242",
                "name": "New Project Set Name",
                "description": "Kashif's project set",
                "projectSetType": {
                    "id": "STF",
                    "__typename": "ProjectSetType"
                },
                "companyStandardSet": false,
                "filters": {
                    "generalFilters": {
                        "endEquipmentClassification": [
                            false //==========================> This should be "SNE" as in Network tab.
                        ],
                        "projectScope": [],
                        "__typename": "GeneralFilter"
                    },
                    "companySpecificFilters": {
                        "certificationStatus": [],
                        "projectStatus": [],
                        "organizationUnits": [],
                        "__typename": "CompanySpecificFilter"
                    },
                    "tagFilters": {
                        "companyTags": [],
                        "userTags": [],
                        "__typename": "TagsFilter"
                    },
                    "advancedFilters": [],
                    "__typename": "ProjectSetFilter"
                },
                "__typename": "ProjectSetWithProjects"
            },
            "__typename": "ProjectSetResult"
        }
    }

The code is:

```
const [fetch, { data, loading }] = useLazyQuery<
            ApolloResponse<QueryResult>
        >(query, {
            variables: { ...queryVariables },
            fetchPolicy: 'no-cache'
        })

useEffect(() => {
     console.log('response', data)
},[queryData])

```

The configuration I am using with ApolloProvider is:
```
const httpLink = createHttpLink({
    uri: `${Config.API_SERVER}/graphql`
})


export const client = new ApolloClient({
    link: httpLink
    cache
})
```

What might be the reason that I am getting a transformed response? Please note that we have an ample codebase and we don't have such issues in any other query calls.

  [1]: https://i.stack.imgur.com/xTsTq.png

**Comment by sarink** [comment]
There are a lot of recent bugs around `useLazyQuery`'s `fetchPolicy`. Perhaps it's reading some old response? I had to downgrade to `3.4.17` to get `"no-cache"` to start working again.

**Comment by bignimbus** [comment]
Hi all 👋🏻  thanks for your patience on this!  I hope you've been able to make progress since opening this issue but I'd be happy to offer a second set of eyes here.

@kashif-nazar  can you show where `queryData` is declared?  Also the value of `query` could help as well.

Regarding `endEquipmentClassification`: do you have a type or field policy declared for this field?  Or a `keyFields` value?  Thanks 🙏🏻
