### ISSUE TITLE
Graphql type with id property that can have different values for same id

### ISSUE THREAD

**Issue by harm-meijer** [apollographql/apollo-client#9429]
I was wondering if an object type that has an id property has to have the same content given the same id. At the moment the same id can have different content.

The following query:

```js
const query = gql`
    query products(
       $priceSelector: PriceSelectorInput!
    ) {
    productProjectionSearch(
      priceSelector: $priceSelector
    ) {
        total
        results {
          masterVariant {
            # If you do the following it will work
            # anythingButId: id
            id
            scopedPrice {
              country
            }
          }
        }
      }
    }
`;
```

If the `PriceSelectorInput` is `{currency: "USD", country: "US"}` then the result is:

```json
{
    "productProjectionSearch": {
    "total": 2702,
    "results": [
        {
        "name": "Sweater Pinko white",
        "masterVariant": {
            "id": 1,
            "scopedPrice": {
            "country": "US",
            "__typename": "ScopedPrice"
            },
            "__typename": "ProductSearchVariant"
        },
        "__typename": "ProductProjection"
        }
    ],
    "__typename": "ProductProjectionSearchResult"
    }
}
```

If the `PriceSelectorInput` is `{currency: "EUR", country: "DE"}` then the result is:

```json
{
    "productProjectionSearch": {
    "total": 2702,
    "results": [
        {
        "name": "Sweater Pinko white",
        "masterVariant": {
            "id": 1,
            "scopedPrice": {
            "country": "DE",
            "__typename": "ScopedPrice"
            },
            "__typename": "ProductSearchVariant"
        },
        "__typename": "ProductProjection"
        }
    ],
    "__typename": "ProductProjectionSearchResult"
    }
}
```

My question is that masterVariant of type ProductSearchVariant has id of 1 in both cases but different values for scopedPrice. This breaks apollo cache defaultDataIdFromObject function as demonstrated in [this repo](https://github.com/harm-meijer/vue-apollo-issue-1322/blob/master/src/App.vue#L40-L41). My question is; is this a bug in apollo or would this be a violation in the type definition of ProductSearchVariant?

If it's not based on a graphql spec then why would defaultDataIdFromObject use the id to make a key that doesn't point to the correct result?

**Comment by bignimbus** [comment]
Hi @harm-meijer 👋🏻  thanks for your patience!  It appears that default normalization is not exactly what we need here.  Instead we'd want more fine-grained control over how we normalize `ProductSearchVariant` via its type policy.  Try the following diff in your source code:

```diff
diff --git a/src/apollo/index.js b/src/apollo/index.js
index 72bd0c3..9d234c7 100644
--- a/src/apollo/index.js
+++ b/src/apollo/index.js
@@ -20,6 +20,11 @@ export const cache = new InMemoryCache({
     }
     return defaultDataIdFromObject(responseObject);
   },
+  typePolicies: {
+    ProductSearchVariant: {
+      keyFields: ["id", "scopedPrice"]
+    }
+  }
 });
 const httpLink = createHttpLink({
   uri: 'https://api.europe-west1.gcp.commercetools.com/sunrise-spa/graphql',

```

See [these docs](https://www.apollographql.com/docs/react/caching/cache-configuration/#customizing-cache-ids) for more info - I hope that helps!
