### ISSUE TITLE
useQuery pollInterval with cache-and-network doesn't stop to make requests after unmounting a component

### ISSUE THREAD

**Issue by hsk-kr** [apollographql/apollo-client#9431]
**Intended outcome:** Make a request every  `pollInterval` ms and stop making requests after unmounting the component.

**Actual outcome:** Make two requests every `pollInterval`ms and doesn't stop and make a request every `pollInterval`ms after unmounting the component

**How to reproduce the issue:**

```javascript
const { data, error } = useQuery(ANY_QUERY, {
    fetchPolicy: "cache-and-network",
    pollInterval: 1000,
  });
```

It works with other `fetchPolicy` but it doesn't work with `cache-and-network`.

**Versions**

`^3.5.8`

**Comment by arvindell** [comment]
Have the same problem

**Comment by nikgraf** [comment]
Ran into the same issue

**Comment by AlekseyMalakhov** [comment]
Problem still exists

**Comment by MilanJimi** [comment]
Same here.

**Comment by rossvz** [comment]
Ran into this as well. In our case it was something like

```tsx
 { isEnabled ? (<ComponentA/> ) : (<ComponentB/>) }
```

and each component had a pollInterval with the `cache-and-network` policy. When `isEnabled` changes and we render a different component, the polling for the other component was still running. Changing the policy to `network-only` resolved the issue.

**Comment by jerelmiller** [comment]
Hey all 👋 

Would anybody be able to share a minimal reproduction of this issue? I've attempted to reproduce this with our tests but have been unsuccessful. Both strict mode and non-strict mode seem to stop polling as expected when the component unmounts.

Take a look at https://github.com/apollographql/apollo-client/compare/jerel/cache-and-network-polling?expand=1 for my attempt to reproduce this. Any help would be appreciated recreating the issue.

**Comment by dylanwulf** [comment]
Possibly related to my issue #11750 which does have a reproduction

**Comment by jerelmiller** [comment]
Awesome, thanks @dylanwulf!
