### ISSUE TITLE
Caching issue with nested fields with same typename on upper level

### ISSUE THREAD

**Issue by peturgeorgievv** [apollographql/apollo-client#9435]
**Intended outcome:**
I hoped to get my cached items in the position they were sent the first time. The first call of my query singleWorkoutPlanQuery is giving me the correct order of nested fields - workouts, exercises both of them by "position" (it's sorted on the BE), but when it is already cached and I go to another page and come back, it's in the wrong order. Object form is like this ->
![Screenshot 2022-02-17 at 0 36 47](https://user-images.githubusercontent.com/50354476/154369232-80286ee2-e945-4d08-9235-0ac284dce78b.png)
I also have a query calling allWorkoutPlansQuery, which actually includes this singleWorkoutPlanQuery. it's just an array of all singleWorkoutPlans.
This is in general my schema ->
![Screenshot 2022-02-17 at 0 41 16](https://user-images.githubusercontent.com/50354476/154369913-7cf572e9-9c44-455e-a2e3-0b5ebfff491a.png)

Also here are screenshot of the used types in the BE ->
![Screenshot 2022-02-17 at 0 43 19](https://user-images.githubusercontent.com/50354476/154370175-f79e6553-8f88-4ff6-aca1-851bc15fda1f.png)
![Screenshot 2022-02-17 at 0 43 30](https://user-images.githubusercontent.com/50354476/154370191-5020108b-0a1e-42bb-8157-02cf1fc0b3c4.png)
![Screenshot 2022-02-17 at 0 43 40](https://user-images.githubusercontent.com/50354476/154370199-c1052f73-7a76-49d4-8cdd-0f7a5a9a12dd.png)

**Actual outcome:**
This is the first call when i refresh the page on /workoutPlans/:id - Correct one, first is position 1, last is position 21. (It could be any number, it just needs to be sorted asc, as it is.)
![Screenshot 2022-02-17 at 0 48 29](https://user-images.githubusercontent.com/50354476/154370794-5cd77cf0-79ae-44cd-a2c8-cb50c29f37a0.png)
And when i go to /workoutPlans (where all WorkoutPlanData, plans are shown) and come back to /workoutPlans/:id it gives me wrong order of workouts & workout.exercises
![Screenshot 2022-02-17 at 0 52 01](https://user-images.githubusercontent.com/50354476/154371152-9264182c-61bf-43f3-b80c-92824ebf1f2e.png)

**How to reproduce the issue:**
I can't think how to, as it's complex already. But i could provide as much as details as possible if needed. As i am a little bit stuck here, as sorting the object again in useEffect, would reduce performance greatly.

**Versions**
  System:
    OS: macOS 11.6.3
  Binaries:
    Node: 12.22.7 - /usr/local/opt/nvm/versions/node/v12.22.7/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/opt/nvm/versions/node/v12.22.7/bin/npm
  Browsers:
    Chrome: 98.0.4758.102
    Safari: 15.3
  npmPackages:
    @apollo/client: ^3.4.17 => 3.4.17

**Comment by peturgeorgievv** [comment]
I managed to fix it for now, by sorting on the BE, also every single of allWorkoutPlans, but is this really the way it should work?

**Comment by bignimbus** [comment]
Hi @peturgeorgievv 👋🏻  thanks for your patience!  I'm not sure what might be going on here without more information.  For example, are we refetching data at any point?  Regardless, one way to get around what you're seeing is to define a `read` policy in your cache.  See [Customizing the behavior of cached fields](https://www.apollographql.com/docs/react/caching/cache-field-behavior/) for more info.  Here's an example that might address one behavior you're noticing:

```js
const typePolicies = {
  WorkoutPlanData: {
    fields: {
      workouts: {
        read(workouts) {
          return [...workouts].sort((a, b) => a.position > b.position);
        }
      }
    }
  }
};
```

I'll close this for now but please feel free to let us know if you need more support or have more info that indicates a bug with the client 🙏🏻
