### ISSUE TITLE
Calling setState after on useQuery data triggers infinite loop

### ISSUE THREAD

**Issue by jairmedeiros** [apollographql/apollo-client#9454]
I've been using apollo-hooks in my app and so far I love it except I can't get pass this issue.

I'm using useQuery to return an array of users to display in a list. However I want to store those users in local state using useState so that when I click a delete button next to the user it deletes them from the list. However whenever I call useState on data from apollo-hooks` I get this error.

Invariant Violation: Too many re-renders. React limits the number of renders to prevent an infinite loop.

I'm not sure what I'm doing wrong, any insight would be helpful. Here's some of my code.

```
const [user, setUser] = useState('');
  const [list, setList] = useState([]);

  useEffect(() => {
    if (storage.hasUser()) {
      const user = storage.getUser();
      setUser(user);
    } else {
      history.push('/login');
    }
  }, []);

  const { accessToken, organizationId } = user;

  const { data, error, loading } = useQuery(GROUPS_PAGE_QUERY, {
    variables: {
      accessToken: accessToken,
      organizationId: organizationId
    }
  });

  if (data) {
    setList(data); // this seems to be where the error is happening. 
  }

return (
    <div>
      <GroupList groups={data.userGroups} deleteGroup={deleteGroup} />
    </div>
  );
```

**Comment by RemyMachado** [comment]
You are asking for a re-render on every render, thus you have an infinite loop.

```typescript
  if (data) {
    setList(data); // this line tells to react to update the state and RE-RENDER
  }
```

I doubt it's useful, but if you really wish to duplicate the data into your `useState`, you can use a `useEffect` that triggers only when data changes.

```typescript
useEffect(() => {
   setList(data); // will only update when data changes
}, [data])
```

It's not a apollo-client bug. You can close this issue.

**Comment by bignimbus** [comment]
Closing - I think @RemyMachado's response addresses this concern.  Let us know if you need more support here 🙏🏻
