### ISSUE TITLE
in graphql I stared but its not responding in http://localhost:3005/graphql this port

### ISSUE THREAD

**Issue by Arcamit** [apollographql/apollo-client#9455]
server.js
const express = require("express");
const app = express();

var cors = require('cors')
const PORT = 3005;

const { graphqlHTTP } = require("express-graphql");

const schema = require("./schema");

app.use(cors())

app.use(
  "./graphql",
  graphqlHTTP({
    graphiql:true,
    schema
  })
);

app.listen(PORT, () => {
  console.log(`port is started at http://localhost:${PORT}`);
});

schema.js

const graphql = require("graphql");
const {
  GraphQLObjectType,
  GraphQLSchema,
  GraphQLInt,
  GraphQLString,
  GraphQLList,
} = graphql;

const userType = new GraphQLObjectType({
  name: "user",
  fields: () => ({
    id: {
      type: GraphQLInt,
    },
    name: { type: GraphQLString },
    email: { type: GraphQLString },
    phone: { type: GraphQLString },
  }),
});

const RootQuery = new GraphQLObjectType({
  name: "abc",
  fields: {
    codeImprove: {
      type: new GraphQLList(userType),
      resolve(parent, args) {
        let data = [
          {
            id: 123,
            name: "Amit",
            email: "abc@gmail.com",
            phone: "7488174817",
          },
          {
            id: 121,
            name: "Amit kumar",
            email: "abcd@gmail.com",
            phone: "748885127",
          },
        ];
        return data;
      },
    },
  },
});

module.export = new GraphQLSchema({ query: RootQuery });

**Comment by bignimbus** [comment]
Hi @Arcamit 👋🏻  thanks for your patience!  This looks like a question for the [`express-graphql`](https://github.com/graphql/express-graphql) community, I don't see any Apollo Client code here.  Let us know if you need more support 🙏🏻
