### ISSUE TITLE
Apollo + Webpack : Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by lolo-io** [apollographql/apollo-client#9458]
I am trying to add Web support to my React Native Application, but whenever I try to import from @apollo/client, i have this error in the console of my browser, and the page is blank :
`Uncaught ReferenceError: require is not defined`

My tsx file : 
```
import * as client from '@apollo/client';
import React from 'react';
import {Text, View} from 'react-native';

const App = () => {
  return (
    <View>
      <Text>Hello</Text>
    </View>
  );
};

export default App;
```

Is there something special I should do ?

**Comment by lolo-io** [comment]
I found a workaround thanks to this stackoverflow post :  https://stackoverflow.com/a/46887516.

I added those two lines in the `<head>` section of my `index.html` file and now it works : 

```
<script>var exports = {};</script>
<script>var require = () => {};</script>
```

**Comment by HugoGomezSalas** [comment]
Same error here

**Comment by Saikedo** [comment]
Any news on this issue, for me the minimal example crashes saying `Uncaught ReferenceError: exports is not defined`

**Comment by nelsonchen5** [comment]
+1 on this issue

**Comment by alessbell** [comment]
Hi all 👋  Can anyone share a runnable reproduction here?

With the Metro bundler, additional configuration is required to implicitly resolve files with `.cjs`/`.mjs` extensions (see https://github.com/apollographql/apollo-client/issues/10719). I see Webpack is mentioned in the original issue, and I'd be happy to help resolve this with some more info. Thanks!
