### ISSUE TITLE
network request duplicated with v >= 3.4.0

### ISSUE THREAD

**Issue by FedeBev** [apollographql/apollo-client#9468]
**Intended outcome:**
One network request after component mount performing query with `useQuery` hook, `fetchPolicy: "cache-and-network"` and `nextFetchPolicy: "cache-only" | "cache-first"` 

**Actual outcome:**
Duplicated network request with `"@apollo/client": ">=3.4.0"`. Behaves as expected with `"@apollo/client": "3.3.21"`

**How to reproduce the issue:**

Client configuration:
```tsx
const webLink = new HttpLink({
  uri: window.config?.gateway?.url || "http://example.com",
});

const cache = new InMemoryCache();

const apolloClient = new ApolloClient({
  cache,
  connectToDevTools: true,
  link: webLink,
  defaultOptions: {
    watchQuery: {
      fetchPolicy: "cache-and-network",
      nextFetchPolicy: "cache-only",
    },
  },
});
```

Then simply perform a query with `useQuery` hook providing the above client.

**Versions**
```
npx envinfo@latest --preset apollo --clipboard
  System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 98.0.4758.102
  npmPackages:
    @apollo/client: 3.5.9 => 3.5.9 
```

**Comment by FedeBev** [comment]
Removing  `defaultOptions.watchQuery.fetchPolicy` "resolved" the issue.

**Comment by benjamn** [comment]
@FedeBev can you try `npm i @apollo/client@latest` to update to v3.6.1?

**Comment by FedeBev** [comment]
@benjamn I'm using v3.6.1 in a newer project with react v18 and I'm facing a different issue, always related to `defaultOptions.watchQuery`.
I'm facing #9635, see [this](https://github.com/apollographql/apollo-client/issues/9635#issuecomment-1113511509) in particular

**Comment by drewlustro** [comment]
I'm experiencing this too.

> Removing `defaultOptions.watchQuery.fetchPolicy` "resolved" the issue.

@FedeBev – What do you mean by "removing" `defaultOptions.watchQuery.fetchPolicy` ?

If you remove `fetchPolicy` from the ApolloClient constructor, wouldn't it fallback on the default` defaultOptions` ?

```tsx
// default that ships with apollo client
const defaultOptions = {
  watchQuery: {
    fetchPolicy: 'cache-and-network',
    errorPolicy: 'ignore',
  },
  query: {
    fetchPolicy: 'network-only',
    errorPolicy: 'all',
  },
  mutate: {
    errorPolicy: 'all',
  },
};
```

**Comment by bignimbus** [comment]
Hi all 👋🏻  per https://github.com/apollographql/apollo-client/issues/9635#issuecomment-1119098652 it appears this may be resolved by upgrading.  Can someone from the thread confirm?
