### ISSUE TITLE
How to force websocket transaction instead of xhr

### ISSUE THREAD

**Issue by JaLe29** [apollographql/apollo-client#9469]
Hello apollo team,

is there any way how to perform standard query/mutations over websocket instead of classic "xhr" http request?

Thank you.

**Comment by bignimbus** [comment]
Hi @JaLe29 👋🏻  thanks for your patience!  Per the [Subscriptions docs](https://www.apollographql.com/docs/react/api/link/apollo-link-subscriptions) (emphasis added):

> The GraphQLWsLink is a [terminating link](https://www.apollographql.com/docs/react/api/link/introduction/#the-terminating-link) that's used most commonly with GraphQL [subscriptions](https://www.apollographql.com/docs/react/data/subscriptions) (which usually communicate over WebSocket), although **you can send queries and mutations over WebSocket as well**.

I haven't tried this myself in an application.  But I think you'd need to ensure your terminating link is a `GraphQLWsLink` instance:

```js
new ApolloClient({
  link: new GraphQLWsLink(
    createClient({
      url: "ws://my-graphql-server",
    }),
  ),
});
```

This will ensure that all your Apollo Client network requests, including those with queries and mutations, are made to that websockets server.  I hope that helps!
