### ISSUE TITLE
Add support for GraphQL variables default values

### ISSUE THREAD

**Issue by iki** [apollographql/apollo-client#947]
Spec: https://facebook.github.io/graphql/#sec-Language.Variables
More info: https://medium.com/the-graphqlhub/graphql-tour-variables-58c6abd10f56

**Comment by helfer** [comment]
@iki sure, we'll implement it some time. I would give this relatively low priority at the moment though, because I think default values for variables are most useful on the server. On the client, I think it's just as convenient to provide that default value yourself in the component that issues the query. But maybe you have a compelling use-case?

**Comment by srtucker22** [comment]
One use case I've run into is with directives.

For example, if I want to reuse a query for different components, but they query a different subset of fields:

```
query user($id: Int, $withGroups: Boolean = false, $withFriends: Boolean = false) {
    user(id: $id) {
      id
      username
      friends @include(if: $withFriends) {
        id
        username
      }
      groups @include(if: $withGroups) {
        id
        name
        messages(limit: 1) {
          ... MessageFragment
        }
      }
    }
  }
```

Here, it would be nice to default to false for `withGroups` and `withFriends`, and only opt-in with variables. It's a small change, but I imagine could get more complicated if you wanted to have optional filters with defaults, etc.

Maybe there's a nicer way to do this?

Also, when running the code with default values, I would receive an error, but the error message wasn't serializable so it didn't make it into reducer, so I needed to create middleware to log it. I'm working on a RN app so no apollo dev tools yet. I don't know if this is a general issue for some subset of errors that could use improving, but wanted to bring it to your attention, and happy to help if so.

**Comment by calebmer** [comment]
@srtucker22 this is a feature we would be happy to merge if you wanted to implement it 😊

**Comment by srtucker22** [comment]
looking into it. got my apollo-client contributor env setup. hopefully will have some free time soon to mess with it

**Comment by iki** [comment]
@calebmer another common use case is simply whenever it's more appropriate in codebase to setup default query/mutation parameter values in gql, e.h. if they are internal parameters and the user module which attaches given query/mutation to a redux component should not care about those parameters at all.

**Comment by loganpowell** [comment]
Sorry! Nevermind, my issue was that I was loading data from cache. The default variables work!

**Comment by LavaGolem** [comment]
@loganpowell  have you found the solution to your issue? I have the same one.

**Comment by LavaGolem** [comment]
@loganpowell how did you fix it? what do you mean loading data from cache? I have the same issue.

**Comment by loganpowell** [comment]
@LavaGolem out of the box, Apollo caches query responses, so - when testing/developing - you may have to manually [`refetch`](https://www.apollographql.com/docs/react/basics/queries.html#graphql-query-data-refetch) them to refresh the cache.

**Comment by jeet23** [comment]
Has this feature been implemented yet?
