### ISSUE TITLE
Webpack build error 'stringifyForDisplay' (imported as 'stringifyForDisplay') was not found 

### ISSUE THREAD

**Issue by helenlslone** [apollographql/apollo-client#9471]
**Intended outcome:**
I wanted to build my application using webpack (latest at time of writing - 5.69.1) and the latest version of apollo-client

**Actual outcome:**
Got the error ERROR in ../../../node_modules/@apollo/client/cache/inmemory/policies.js 466:87-106
export 'stringifyForDisplay' (imported as 'stringifyForDisplay') was not found in '../../utilities/index.js' (possible exports: Concast, DEV, DeepMerger, Observable, addTypenameToDocument, argumentsObjectFromField, asyncMap, buildQueryFromSelectionSet, canUseSymbol, canUseWeakMap, canUseWeakSet, checkDocument, cloneDeep, compact, concatPagination, createFragmentMap, fixObservableSubclass, getDefaultValues, getDirectiveNames, getFragmentDefinition, getFragmentDefinitions, getFragmentFromSelection, getFragmentQueryDocument, getInclusionDirectives, getMainDefinition, getOperationDefinition, getOperationName, getQueryDefinition, getStoreKeyName, getTypenameFromResult, graphQLResultHasError, hasClientExports, hasDirectives, isDocumentNode, isField, isInlineFragment, isNonEmptyArray, isNonNullObject, isReference, iterateObserversSafely, makeReference, makeUniqueId, maybe, maybeDeepFreeze, mergeDeep, mergeDeepArray, offsetLimitPagination, relayStylePagination, removeArgumentsFromDocument, removeClientSetsFromDocument, removeConnectionDirectiveFromDocument, removeDirectivesFromDocument, removeFragmentSpreadFromDocument, resultKeyNameFromField, shouldInclude, storeKeyNameFromField, valueToObjectRepresentation)

I have to use a version of apollo before 3.5.x to get it to build without the error

**Comment by bignimbus** [comment]
Hi @helenlslone 👋🏻  thanks for your patience here!  Do you still need support on this issue?  Happy to give a second set of eyes here
