### ISSUE TITLE
not es5 compatible?

### ISSUE THREAD

**Issue by JensMadsen** [apollographql/apollo-client#9473]
To reproduce: 

- yarn add apollo/client . I get v3.5.9
- run e.g.: `npx es-check es5 ./node_modules/@apollo/client/core/*.js --verbose`
- not es5. Is that intended and if so is there a recommended way to fix this for IE11 support?

**Comment by benjamn** [comment]
That `*.js` glob is definitely going to pick up `import` and `export` syntax in a number of `.js` files, which is not ES5-safe. However, you should find pure CommonJS syntax (`require` and `exports`) in files with the `.cjs` file extension, though I would be interested to hear about any other ES5 violations you find in those `.cjs` files.

**Comment by JensMadsen** [comment]
Hi @benjamn . Thank you for a quick response. I actually experience the problem when adding @apollo/client to a react project (typescript, babel and webpack). When I do that arrow functions, back ticks, const's and let's show up all over. The es-check was only an easy (but wrong :-)) demonstration :-) I will read up on cjs files (I am very confused about which files webpack actually use when bundling apollo client). Should I post a minimal example?

**Comment by JensMadsen** [comment]
@benjamn so what you say is that you intentionally have the cjs file es5 compatible but not the esm ones? I have a webpack, babel setup but do not know how to force using the cjs files (which are es5 compatible). Can you help? My only solution is to put apollo/client through babel which is slow

**Comment by bignimbus** [comment]
Hi @JensMadsen 👋🏻  try cloning `apollo-client` and following these steps:

```sh
npm install
npm run build
npx es-check es5 ./dist/apollo-client.min.cjs

# output

info: ES-Check: there were no ES version matching errors!  🎉
```

Closing this for now, please feel free to let us know if you have any more questions!
