### ISSUE TITLE
Refetch query does not respect fetchPolicy

### ISSUE THREAD

**Issue by ziggy6792** [apollographql/apollo-client#9479]
**Intended outcome:**

Here is my code sandbox forked from your demo https://codesandbox.io/s/get-started-coinbase-client-forked-66v5e0?file=/src/index.js

I am trying to execute a query using fetchPolicy cache first. Then on refetch the query should be returned from the cache (if available). So I would expect that after the cache has cached a response for {"currrency": "SGD" } then subsequent requests for  {"currrency": "SGD" } should return from the cache and not send a network request.

I would expect this behaviour to be the same for refetch on useQuery and the fetch method returned from useLazyQuery

**Actual outcome:**

Subsequent calls to fetch my query always go over the network and never use the cached responses.
![Issue](https://user-images.githubusercontent.com/60313838/156344218-1b5f0610-309c-442c-b91c-218d473af249.gif)

**How to reproduce the issue:**

https://codesandbox.io/s/get-started-coinbase-client-forked-66v5e0?file=/src/index.js

My example shows the same behaviour present for useQuery as useLazyQuery

**Versions**

See sandbox

**Comment by SamRoehrich** [comment]
What is the use case for refetching data that already exists in the cache? 
According to the docs - `Refetching is an excellent way to guarantee fresh data`. [link](https://www.apollographql.com/docs/react/data/queries/#refetching)

**Comment by ziggy6792** [comment]
Yeh I saw that too so I wondered if maybe I have misunderstood how this works.
My use case is I have a chart that displays search results and the data doesn't change much (once a week maybe).
I want users to be able to search results with some inputs, then change the inputs and search again. If the user repeats the same search from before, no need to send a new request as the data will not have changed. 

I can achieve what I want by updating the inputs to the query with setState (will trigger a refetch and respect fetch policy). But I also want to have a promise for when the query is executing (to return from Formiks submit method) so thats why I am using the refetch functionality.

**Comment by SamRoehrich** [comment]
I am curious if you can use the data fetching method returned from useLazyQuery. I would imagine if you provide the same variables to that method it would return the cached data first then preform a network request after the data has been extracted from the cache. I think it will still make the network request because apollo does not want to infer that you are not looking for new data even though the variables are the same.

**Comment by bignimbus** [comment]
Hi all, thanks for your patience!  A similar issue was raised in https://github.com/apollographql/apollo-client/issues/5515.  This is working as designed 🙏🏻

`readQuery` and `readFragment` may be helpful here, as might `useLazyQuery`, as @SamRoehrich suggested.
