### ISSUE TITLE
Docs: useSubscription provides a skip options but there's nothing in Docs

### ISSUE THREAD

**Issue by ruggi99** [apollographql/apollo-client#9486]
**Intended outcome:**

[docs] for useSubscription options updated with `skip` parameters

**Actual outcome:**

useSubscription hook options is missing 1 option parameter in [docs](https://www.apollographql.com/docs/react/data/subscriptions/#options).
Missing parameter is `skip`

**How to reproduce the issue:**

Look at [docs](https://www.apollographql.com/docs/react/data/subscriptions/#options), [types](https://github.com/apollographql/apollo-client/blob/ba19a45f71040467e6e2891d7448f33875f2a3fa/docs/shared/subscription-options.mdx) and [types](https://github.com/apollographql/apollo-client/blob/ba19a45f71040467e6e2891d7448f33875f2a3fa/src/react/types/types.ts#L201)

**Versions**

System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.13.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.30)
  npmPackages:
    @apollo/client: ^3.5.10 => 3.5.10

I can provide a PR if you want to

**Comment by ruggi99** [comment]
Any updates on this?

**Comment by bignimbus** [comment]
@ruggi99 we'd love a contribution to the docs, thanks for offering!
