### ISSUE TITLE
Not being able to generate mutation functions

### ISSUE THREAD

**Issue by berk-can** [apollographql/apollo-client#9509]
Hello, I am so confused about something so I want to ask it, sorry if I asked something that exists, I am new to graphql and not so-experienced

My question is why cant library generate all the functions for us from schema with enabling us to pass parameters we want as array? As I see on all questions previously asked on internet, answer is create own mutation within gql tag, define all parameters also for function itself, and call useMutation function with variables again it looks so bothersome. I just think it could be done via making generic functions and variables

eg: I have a mutation with update user taking parameters like email,phone,password,name etc. I could be able to just call Mutation.updateUser(email:email_variable, password:password_variable).then((data)=>{
//Handle response data returned from server here
}

I dont get why we still need to create gql for anything manually?

**Comment by bignimbus** [comment]
Hi @berk-can! You  may find [these docs](https://www.apollographql.com/docs/react/development-testing/static-typing) useful.  TypeScript users can use GraphQL Code Generator to generate `useMutation` hooks and types based on your schema.  I hope that helps!
