### ISSUE TITLE
Update to non-deprecated Redux devtools extension API

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-client#952]
https://github.com/zalmoxisus/redux-devtools-extension/issues/220

This is both a better name and (if you use the COMPOSE version) apparently has more features.  You can use an npm module to do the logic if you want (and maybe turn off in production?)

(Not clear how long it will be before you can assume all users have upgraded to the newer extension.)

**Comment by stubailo** [comment]
There's always the workaround of initializing the store yourself and passing it into Apollo as documented in: http://dev.apollodata.com/react/redux.html#creating-a-store

Would be a great PR for someone looking for a first improvement, in this file: https://github.com/apollostack/apollo-client/blob/5ffe05d75a02aa976d3bc873f83b5c3416b406e0/src/store.ts#L131

**Comment by zalmoxisus** [comment]
The idea of "COMPOSE version" came from https://github.com/apollostack/apollo-client/issues/701, so it was intended to solve current issues with `apollo-client`. 

> Not clear how long it will be before you can assume all users have upgraded to the newer extension.

Chrome updates extensions updated automatically. Autoupdates can be disabled only in Firefox, nevertheless I think it's safe to use the new global name.

**Comment by stubailo** [comment]
Oh wow, I didn't realize it was a result of that thread. So should we do something more than just replace the API to take advantage of the new functionality?

**Comment by zalmoxisus** [comment]
@stubailo even though [I am using Apollo](https://github.com/zalmoxisus/remotedev-server/blob/v0.3/lib/middleware/graphql.js) in the bridge for the extension, honestly to say I didn't get a chance to look into the client part yet. Maybe @migueloller and @tmeasday can say if [the suggested change](https://github.com/apollostack/apollo-client/issues/701#issuecomment-252201575) is still necessary.

**Comment by tmeasday** [comment]
#701 was the motivation for being more idiomatic in our Redux usage in the 0.5.0 release. TBH this fell off my radar; I'm not sure if the changes are we made will allow true time-travelling yet.

**Comment by helfer** [comment]
Yeah, I don't think we made the necessary changes there. I think the goal was to use thunks to dispatch actions, but we decided not to rewrite any of that for 0.5, so it's still the same as before. If someone can tell me what exactly would need to be done, I can put it on the roadmap though.

**Comment by glasser** [comment]
Reopening, as we haven't fixed it yet and in theeeeeeory the Redux devtools could get rid of the deprecated version at some point.

**Comment by glasser** [comment]
AC 2.0 will not use Redux. References to window.devToolsExtension have already been removed from the 2.0-alpha branch: https://github.com/apollographql/apollo-client/pull/1949/commits/bba7bce36ee835f09270987c91033fce5e0f7fee

So this can be closed.
