### ISSUE TITLE
React native @apollo/client error while trying to resolve module

### ISSUE THREAD

**Issue by Dhinesh-Dhinesh** [apollographql/apollo-client#9531]
In React native I face this Error:

`Error: While trying to resolve module `@apollo/client/` from file {project-root-folder} the package {project-root-folder} \node_modules\@apollo\client\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (\node_modules\@apollo\client\main.cjs`. Indeed, none of these files exist:`

**Comment by benjamn** [comment]
Please see the note about working around this React Native issue in [the `CHANGELOG.md` from v3.5.4](https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#apollo-client-354-2021-11-19).

**Comment by oxbits** [comment]
This fix break my AWS Amplify Cognito Authentication.

Will there be a fix in the future that does not require the workaround?

**Comment by oxbits** [comment]
AWS closed the same issue on their end because they consider it a third party library issue.  Seems like we are getting stuck in a catch 22 situation.

https://github.com/aws-amplify/amplify-js/issues/9599
