### ISSUE TITLE
watchQuery + reobserve no longer aborts stale queries

### ISSUE THREAD

**Issue by javier-garcia-meteologica** [apollographql/apollo-client#9532]
For a couple of months I've noticed that ~`watchQuery + unsubscribe`~ `watchQuery + reobserve | setOptions | setVariables` is no longer aborting stale HTTP queries.

I've digged into it and I've found that the problem lies in this line:

https://github.com/apollographql/apollo-client/blob/6023763e745120782974bd255695f29ff0f8bc38/src/core/ObservableQuery.ts#L737

When the last parameter is `true`, `removeObserver` will not abort the underlying HTTP query. That last parameter has to be removed for `watchQuery + reobserve` to work.

```ts
        this.concast.removeObserver(this.observer);
```

I suppose that making this change could create other problems that I ignore.

That's why I would like to invite @brainkim to this debate. He is the author of that line and maybe he can help us understand better the problem.

https://github.com/apollographql/apollo-client/commit/d76c5a719244f0014867244ab09ebb0371017200#diff-ebf1072d16b9775e8cae2d74140e5da612378bf107621ab70c3769b3c4d31ee5R688

Related to #8858
PR #9791

**Intended outcome:**

Stale queries should be aborted.

**Actual outcome:**

Stale queries are allowed to finish and return 200 OK.

**How to reproduce the issue:**

1. Use `watchQuery` and subscribe to it
2. Use `.setOptions` to change the query parameters multiple times very quick
3. Take a look at the Network tab of your browser devtools. Stale queries were not aborted.

Create

**Versions**: 3.5.10

```
  System:
    OS: Linux 5.16 Fedora Linux 35 (Workstation Edition)
  Binaries:
    Node: 16.13.1 - ~/.asdf/installs/nodejs/16.13.1/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 8.1.2 - ~/.asdf/installs/nodejs/16.13.1/bin/npm
  Browsers:
    Chrome: 98.0.4758.102
    Firefox: 97.0.1
  npmPackages:
    @apollo/client: ^3.5.10 => 3.5.10
    apollo-upload-client: ^17.0.0 => 17.0.0
```

**Comment by jpvajda** [comment]
@javier-garcia-meteologica thanks for the PR, just a note @brainkim is no longer a maintainer on this project, but I've added @benjamn and @hwillson to consider this change.
