### ISSUE TITLE
LazyQuery does not pickup data from cache

### ISSUE THREAD

**Issue by patchimou** [apollographql/apollo-client#9544]
I don't know if this is a known issue, I don't even know if it is an issue but I found that when you use LazyQuery in the following way, it never read the cache, even when you put a `fetchPolicy: 'cache-only'`.

Example: (I initially did this because I needed to fetch the userEmail to use it as a variable)

```jsx
function Component() {
  const [doQuery, queryResult] = useLazyQuery(query);

  useEffect(() => {
    (async () => {
      const userEmail = await fetchUserEmail();
      doQuery({variables: {userEmail}});
    })();
  }, []);
}
```

**Comment by benjamn** [comment]
@patchimou Can you try the latest v3.6 beta by running `npm i @apollo/client@beta` when you have a chance? I believe PR #9564 will help here (if your issue is similar to #9375).

**Comment by patchimou** [comment]
@benjamn I just tried and I can confirm you it works fine ! No additional networks calls are made after the 1st one.
Thank you for your time
