### ISSUE TITLE
Array of string in mutation variables is converted into comma separated array

### ISSUE THREAD

**Issue by kkawett** [apollographql/apollo-client#9551]
Hello,

**Intended outcome:**
I try to send an array of string as a variable in an input:
{v : ['0A', '0B']}

**Actual outcome:**
But it automatically convert the result into an array of separated character.
{v: [{0: "0", 1: "A"}, {0: "0", 1: "B"}]}

Do I miss something ? The type in the graph is :
{v: [String]}

Thanks.

**Comment by vphilot** [comment]
I'm having the same problem, with not fix so far unfortunately - except for settting all inputs to `JSONObject`s

**Comment by jerelmiller** [comment]
@kkawett thanks for your patience! What version of Apollo client are you using and how are you using the mutations? We have a variety of ways to use mutations (e.g. `client.mutate`, `useMutation`, `<Mutation />`, etc), so a code sample or reproduction of the issue would be super helpful to help narrow down the issue 🙏 . Thanks!
