### ISSUE TITLE
import QueryType not exposed

### ISSUE THREAD

**Issue by reduxdj** [apollographql/apollo-client#9559]
I'm using a strictly typed codebase, unfortunately the QueryType return type of `writeProxy` is not exposed as an import. 
Please advise. I have to cast as any, my eslitnt does not like this:
```
            /* eslint-disable-line  @typescript-eslint/no-explicit-any */
            const dataProxy: any = proxy.readQuery({
              query: MessagesByAssetAndAddressDocument,
              variables,
            });
```

I notice the typescript documentation does not show a way to import types in the project in general.

  "@apollo/client": "3.5.10",
Thanks.

**Comment by jerelmiller** [comment]
Hey @reduxdj! Thanks for your patience 🙏 ! Would you be able to provide more context on how you're using that API? Where are you getting `proxy` from in this case?

We do our best to [export our types](https://github.com/apollographql/apollo-client/blob/main/src/core/index.ts#L28) for use in all TypeScript apps, but understand there might be something that fell through the cracks. If you're aware of the fix you need, we also accept PRs! Let us know how we can be helpful in this case. Thanks!
