### ISSUE TITLE
Fields not marked with @client are being resolved locally

### ISSUE THREAD

**Issue by vigie** [apollographql/apollo-client#9571]
It is important to be able to precisely control which fields are resolved locally versus remotely while a remote service is developed and incrementally replaces a local implementation. Once a remote service starts offering a field, I want to start removing `@client` from some queries that use that field, without yet removing the local resolver definition.

This scenario is not supported today due to a bug.

**Intended outcome:**
Only fields marked `@client` should be sent to local resolvers

**Actual outcome:**
If a `@client` directive appears _anywhere_ in a document, local resolvers are looked for and run for all fields in the entire document, regardless of whether those fields were tagged with the `@client` directive.

**How to reproduce the issue:**
Have a resolver both locally and on the server for a field. Send a query that does not tag that field with `@client`, but does tag some other field with `@client`. Observe that the result for the field not tagged with `@client` was supplied  by the local resolver, despite the lack of tag.

The problem is in the local state code that indiscriminately returns the entire document instead of just stripping out the `@client` parts:

<img width="971" alt="Screen Shot 2022-03-31 at 11 50 13 AM" src="https://user-images.githubusercontent.com/5872403/161129401-b47d8217-11f3-4760-95fa-33468d90bef7.png">

**Versions**
```
  System:
    OS: macOS 12.2
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
  Browsers:
    Chrome: 100.0.4896.60
    Firefox: 84.0.1
    Safari: 15.3
  npmPackages:
    @apollo/client: ^3.4.16 => 3.4.16
    apollo-angular: ^2.6.0 => 2.6.0
```

**Comment by vladar** [comment]
I've faced the same issue, and it turns out that the presence of a single `@client` directive significantly affects the performance of the whole query because of this (because Apollo basically traverses every single item in the GraphQL result, even for selectionSets without the `@client` directive).

Here is a benchmark to demonstrate the impact of this issue: https://github.com/vladar/apollo-at-client-bench

```
Without client resolver
100 items x 1,078 ops/sec ±4.69% (58 runs sampled)
1000 items x 128 ops/sec ±5.05% (57 runs sampled)
10000 items x 11.90 ops/sec ±8.81% (55 runs sampled)

With client resolver
100 items x 494 ops/sec ±7.05% (59 runs sampled)
1000 items x 56.21 ops/sec ±6.67% (56 runs sampled)
10000 items x 5.10 ops/sec ±10.75% (28 runs sampled)
```

Note that the client resolver executes only once for the whole query, but performance degrades significantly. I have a potential fix for this problem, will publish a PR soon.

**Comment by vladar** [comment]
@vigie can you try PR #9573 and see if it fixes the problem for you?

**Comment by vigie** [comment]
Hey @vladar thanks for working on this. I tried to verify this by deleting my `node_modules/@apollo/client` folder and replacing with the content of `dist` after building from your PR.

I'm getting the following runtime errors on app startup:

```
Error: node_modules/@apollo/client/core/index.d.ts:16:10 - error TS2614: Module '"graphql-tag"' has no exported member 'gql'. Did you mean to use 'import gql from "graphql-tag"' instead?

16 export { gql, resetCaches, disableFragmentWarnings, enableExperimentalFragmentVariables, disableExperimentalFragmentVariables, } from 'graphql-tag';
            ~~~


Error: node_modules/@apollo/client/link/core/types.d.ts:19:134 - error TS2707: Generic type 'ExecutionResult<TData>' requires between 0 and 1 type arguments.

19 export interface FetchResult<TData = Record<string, any>, TContext = Record<string, any>, TExtensions = Record<string, any>> extends ExecutionResult<TData, TExtensions> {
```

Here's my env

```
  System:
    OS: macOS 12.3.1
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
  Browsers:
    Chrome: 100.0.4896.75
    Firefox: 84.0.1
    Safari: 15.4
  npmPackages:
    @apollo/client: ^3.4.16 => 3.4.16
    apollo-angular: ^2.6.0 => 2.6.0
 ```

**Comment by vigie** [comment]
Hey @vladar , I finally had time to try your PR and can confirm it fixes the issue. I see the non-client parts only being correct sent across then link and the client parts only being resolved locally.

Thanks for working on this!
