### ISSUE TITLE
🤯 Troubled by `__typename`

### ISSUE THREAD

**Issue by chioio** [apollographql/apollo-client#9574]
### The code first:
```ts
const [updateCreation] = useMutation<Result<Creation>, Variables<UpdateCreationInput>>(UPDATE_CREATION_MUTATION, {
    ...
  })

  const handleSave = () => {
      // const { createdAt, updatedAt, ...rest } = creation as Creation
      updateCreation({
        variables: {
          input: {
            _id: creation?._id,
            author: creation?.author,
            code: {
              html: creation?.code.html,
              css: creation?.code.css,
              javascript: creation?.code.javascript,
            },
          },
        },
      })
  }
```
**Purpose**: I destructed the `creation` and want use the `rest` for the `input` param, but the query result of creation auto generate one `__typename` property.

Does anyone have a good solution?

**Comment by wolffparkinson** [comment]
not a clean solution, but i use lodash or underscore js to pick keys without `__typename`
```js
updateCreation({
  variables: { input: _.pickBy(rest,(v,k)=>k!=="__typename") },
  },
})
```

**Comment by chioio** [comment]
> not a clean solution, but i use lodash or underscore js to pick keys without `__typename`
> 
> ```js
> updateCreation({
>   variables: { input: _.pickBy(rest,(v,k)=>k!=="__typename") },
>   },
> })
> ```

That's awesome! Thanks for your solution. 🤩
