### ISSUE TITLE
useQuery does not immediately trigger on variables change

### ISSUE THREAD

**Issue by jnous-5** [apollographql/apollo-client#9580]
**Intended outcome:**

Given the nature of `useQuery`, I expect it should trigger immediately when `variables` change. I should be able to see the following console logs after clicking the button.
<img width="204" alt="image" src="https://user-images.githubusercontent.com/45154517/161397304-016527a3-0760-4691-bb96-840082d91513.png">

**Actual outcome:**

`useQuery` triggers on second render.
<img width="217" alt="image" src="https://user-images.githubusercontent.com/45154517/161397407-930cb28c-077c-412a-9e8e-65689c7ecddc.png">

**How to reproduce the issue:**

I cloned the demo codesandbox from the documentation and added the minimum reproducible code.
https://codesandbox.io/s/get-started-coinbase-client-forked-ocs4c5?file=/src/index.js:630-674

1. Open console and clear logs.
2. Click the "Change currency" button.
3. Check console logs.

Based on the logs, you'll notice that on the 1st render after the click, the `currency` variable is already updated ("USD" -> "AUD") whereas the `loading` is not (i.e., still `false`). The query then gets executed on the 2nd render (where you'll see `loading` is now `true`).

I'll also have to add that I can only reproduce this on `v3.5.*`. If you try to switch the version to `v3.4.*`, the result is the same as what we expect. I'm not sure if this is an intended change or a possible regression?

**Comment by joshjg** [comment]
Maybe related to #9549

**Comment by dylanwulf** [comment]
Hey guys, please give the new release candidate a try (`@apollo/client@3.6.0-rc.0`) and see if the issue is fixed there

**Comment by jnous-5** [comment]
Sorry, just got back. Confirmed fixed in `v3.6.0`. Thanks, @dylanwulf.

**Comment by bohdanbirdie** [comment]
Can confirm that the 3.6.* release fixed that
