### ISSUE TITLE
Install not working with React 18 and Next 12

### ISSUE THREAD

**Issue by phaniophrero** [apollographql/apollo-client#9581]
Hi I just noticed that the new version of @apollo/client is not working with React 18 and Next.js 12 , I just tried installing apollo on my new project , but it didn't work.

Did anyone else noticed that ?

**Comment by ARKHN3B** [comment]
Same for me.

 If you have a solution, can you share it? 🙂
 
 If I find a solution I will give it here.

**Comment by ARKHN3B** [comment]
Until **Apollo** updates the _peer dependencies_ in its _package.json_ file, you can ignore  all _peerDependencies_ when installing _@apollo/client_ library, like that: 

`npm i --legacy-peer-deps @apollo/client`

It works for me.
More about _peerDependencies_: https://nodejs.org/es/blog/npm/peer-dependencies/

**Comment by sshquack** [comment]
Running into this same issue:

```
❯ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @apollo/client@3.5.10
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
```

Legacy-peer-deps works but would be good to upgrade the support for react 18.

https://github.com/apollographql/apollo-client/blob/8beb4820edc6352996e08f7f73bde3573f1eb666/package.json#L68

**Comment by Deekor** [comment]
Yep cant upgrade to react 18 on next 12. Seems my queries arent populating their headers correctly anymore.

**Comment by paolodedomini** [comment]
Same here!

**Comment by benjamn** [comment]
@phaniophrero @ARKHN3B @Deekor @paolodedomini @sshquack Could you try updating to the latest v3.6 beta by running
```sh
npm i @apollo/client@beta
```
when you have a chance?

We expanded the `peerDependencies` to allow React 18 in PR #9596, which I believe will fix this issue.

A more detailed explanation of how Apollo Client v3.6 supports React 18 can be found in the [`CHANGELOG.md`](https://github.com/apollographql/apollo-client/blob/release-3.6/CHANGELOG.md) (we have plenty more work to do, but updating to `react[-dom]@18` should work now).

**Comment by ARKHN3B** [comment]
@benjamn 

This works! Thank you 🙂

**Comment by benjamn** [comment]
We've merged `release-3.6` into `main` and released PR #9596 in `@apollo/client@3.6.0` just now. That version is still tagged as `next` rather than `latest` on npm, but we will promote it to `latest` after some final testing. Thanks for opening this issue and for your patience waiting for the solution to land!

**Comment by mirkonasato** [comment]
I'm seeing the following warning from Webpack when running `react-scripts start` (using `react-scripts@5.0.1`) after upgrading to `@apollo/client@3.6.0`:

```
Compiled with warnings.

Failed to parse source map from '/path/to/project/node_modules/ts-invariant/src/invariant.ts' file: Error: ENOENT: no such file or directory, open '/path/to/project/node_modules/ts-invariant/src/invariant.ts'
```

**Comment by mirkonasato** [comment]
Raised in the ts-invariant project: [apollographql/invariant-packages#279](https://github.com/apollographql/invariant-packages/issues/279)
