### ISSUE TITLE
I still can't understand why this error keeps showing up while I'm using next js

### ISSUE THREAD

**Issue by WalidMoultamiss** [apollographql/apollo-client#9582]
![image](https://user-images.githubusercontent.com/77829205/161478046-483d46fb-5cbf-4e4d-b31b-ab769048f5f9.png)

![image](https://user-images.githubusercontent.com/77829205/161478079-1bafc6af-77d8-40b2-8f59-fd1ef3d6b753.png)

please provide us a video tutorial because the documentation is sucks

**Comment by othmanekahtal** [comment]
Hi walid
GitHub Issues is used for reporting bugs and requesting features

**Comment by jerelmiller** [comment]
Hey @WalidMoultamiss! Thanks for your patience 🙏. Were you able to figure out what was causing this issue? From your screenshots, it looks like its erroring on the `createClient` call and that `createClient` function comes from [`graphql-ws`](https://github.com/enisdenjo/graphql-ws), which is not a library Apollo maintains.

I found [this discussion](https://github.com/enisdenjo/graphql-ws/discussions/315) that looks very similar to the issue you're seeing. See if that discussion helps point you in the right direction!

We're always looking to improve our documentation, so if you've got some helpful suggestions on how we can improve, we'd love to hear it!

**Comment by jerelmiller** [comment]
I'm doing a bit of housekeeping and since this appears to be an issue with `graphql-ws`, I'm going to close this issue. Feel free to reopen if you do discover this is an issue with Apollo client and we'd be happy to assist further. Thanks!
