### ISSUE TITLE
Browser cookies are not passing in request headers

### ISSUE THREAD

**Issue by Santheepkumarr** [apollographql/apollo-client#9585]
Hi,
**Intended outcome:**
I am tring to pass cookies in request headers. Request headers are set successfully by my graphql server.
<img width="824" alt="Screenshot 2022-04-06 at 6 21 04 PM" src="https://user-images.githubusercontent.com/101556062/161979348-624282f4-864e-461d-ad98-335d9d9cb949.png">

**Actual outcome:**
Cookies are not passing in request headers

<img width="635" alt="Screenshot 2022-04-06 at 6 21 14 PM" src="https://user-images.githubusercontent.com/101556062/161979356-c9c60f6f-85f2-4f27-bc82-b3c58eea362d.png">

**How to reproduce the issue:**
Here is my apollo client setup . I am using Next.js

<img width="673" alt="Screenshot 2022-04-06 at 6 27 13 PM" src="https://user-images.githubusercontent.com/101556062/161979768-d6a32eeb-7d40-4121-a73f-aa37f78995a4.png">

**Versions**

```json
"@apollo/client": "^3.5.10"
    "next": "12.1.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
```

**Comment by vinaynair39** [comment]
@Santheepkumarr I'm facing the same, were you able to solve this?

**Comment by jpvajda** [comment]
Thank you for reporting this! I suggest posting this in our [Apollo Community](https://community.apollographql.com/) for guidance from other Apollo users, as other's may have input into your question. I'll leave this open here as well.

**Comment by tamnguyenandpad** [comment]
@Santheepkumarr @vinaynair39 Have you solved this?

**Comment by jarvistatch** [comment]
Apollo Client doesn't manage cookies natively (i.e., cookies are not passed down between requests), and the native fetch used by the `HttpLink` also doesn't handle cookies automatically. To work around this, I use `isomorphic-fetch` for client-side and wrap it with `tough-cookie` and `fetch-cookie` on the server-side to manage cookies.

Here's my implementation:

```ts
import { ApolloClient, InMemoryCache, HttpLink, from as apolloFrom } from "@apollo/client";
import fetch from "isomorphic-fetch";

// Dynamically choose the fetch implementation
export const getFetch = () => {
  if (typeof window === "undefined") {
    const { CookieJar } = require("tough-cookie");
    const fetchCookie = require("fetch-cookie");
    const cookieJar = new CookieJar();
    return fetchCookie.default(fetch, cookieJar); // Server-side fetch with cookies
  }
  return fetch; // Client-side fetch
};

export const createApolloClient = () => {
  const fetch = getFetch();
  const httpLink = new HttpLink({
    uri: process.env.NEXT_PUBLIC_API_URL,
    credentials: "include", // Ensure cookies are included
    fetch,
  });

  return new ApolloClient({
    link: apolloFrom([httpLink]),
    cache: new InMemoryCache(),
  });
};

const client = createApolloClient();
export default client;
```

**Comment by jerelmiller** [comment]
Appreciate the assist @jarvistatch! I think you do a great job answering the question so I'm going to go ahead and close this issue. 

Let us know if you need any additional assistance. Thanks!
