### ISSUE TITLE
[Unhandled promise rejection: Error: currentFetch is not a function. (In 'currentFetch(chosenURI, options)', 'currentFetch' is false)]

### ISSUE THREAD

**Issue by calboru** [apollographql/apollo-client#9586]
In a very basic react native app with very basic query I got following error without any details. This is a network error, before executing the query.

[Unhandled promise rejection: Error: currentFetch is not a function. (In 'currentFetch(chosenURI, options)', 'currentFetch' is false)]
at node_modules/@apollo/client/errors/errors.cjs:34:20 in ApolloError
at node_modules/@apollo/client/core/core.cjs:1598:18 in utilities.asyncMap$argument_2
at node_modules/@apollo/client/utilities/utilities.cjs:979:79 in Promise$argument_0
at node_modules/@apollo/client/utilities/utilities.cjs:979:23 in promiseQueue.then
at node_modules/@apollo/client/utilities/utilities.cjs:987:35 in <anonymous>
at node_modules/zen-observable/lib/Observable.js:140:15 in notifySubscription
at node_modules/zen-observable/lib/Observable.js:179:20 in onNotify
at node_modules/zen-observable/lib/Observable.js:240:14 in error
at node_modules/@apollo/client/utilities/utilities.cjs:969:4 in iterateObserversSafely
at node_modules/@apollo/client/utilities/utilities.cjs:1068:42 in _this.handlers.error
at node_modules/zen-observable/lib/Observable.js:140:15 in notifySubscription
at node_modules/zen-observable/lib/Observable.js:121:22 in flushSubscription
at node_modules/zen-observable/lib/Observable.js:73:8 in Promise.resolve.then$argument_0

**Comment by calboru** [comment]
It was unrelated to the graphql client.

**Comment by JoymenOpoyi** [comment]
how did you solve this issue, I have got the same one can you help me

**Comment by calboru** [comment]
if you are using react native expo, try "expo run --clean". If it does not work, create new expo app, and move your code one by one. This is how I solved. In my case I was trying to fetch a data with useEffect() at page load and getting this error.
