### ISSUE TITLE
Inline fragment does not return all fields on LazyQuery hook

### ISSUE THREAD

**Issue by PsarewIvan** [apollographql/apollo-client#9608]
Hi all!

**Intended outcome:**
I create inline fragment and use it in request and LazyQuery hook. I want to get all fields from fragment in my request
```
fragment Segment_Conditions on TargetingCondition {
  id
  type
  ... on PageUrlCondition {
   url
  }
  ... on PageTitleCondition {
    title
  }
}

query GetSegmentConditionsDetails($id: ID!) {
  segment(id: $id) {
    conditions {
      ...Segment_Conditions
    }
  }
}
```

**Actual outcome:**

As a result, I can't get the fields from the fragment, the object `conditions` is empty. But if you transfer all the fields from the fragment to the request, everything starts working as it should.

**Versions**

System:
OS: Ubuntu 21.10

Binaries:
Node: v12.22.10
npm: 6.14.16

Browsers:
Chrome: Version 100.0.4896.127 (Official Build) (64-bit)

npmPackages:
"@apollo/client": "^3.4.16",
"@graphql-codegen/typescript-react-apollo": "^2.2.7",

**Comment by benjamn** [comment]
@PsarewIvan Are you configuring [`possibleTypes`](https://www.apollographql.com/docs/react/data/fragments/#defining-possibletypes-manually) when you create your `InMemoryCache`?
```ts
new InMemoryCache({
  possibleTypes: {
    TargetingCondition: ["PageUrlCondition", "PageTitleCondition", ...],
  },
});
```

**Comment by PsarewIvan** [comment]
@benjamn  No, I didn't. I thought that the possible types would be generated from those listed in the fragment.

**Comment by PsarewIvan** [comment]
@benjamn thank you! I added [possibleTypes](https://www.apollographql.com/docs/react/data/fragments/#defining-possibletypes-manually) and its work :)

For automatic type generation I used @graphql-codegen/fragment-matcher
This helped me a lot

Example:
codegen.yml
```yml
generates:
  apollo/__generated__/fragment-matcher.json:
    plugins:
      - fragment-matcher
```

```js
import fragmentMatcher from './__generated__/fragment-matcher.json';

new InMemoryCache({
  possibleTypes: fragmentMatcher.possibleTypes
});
```
