### ISSUE TITLE
useLazyQuery executes query twice the first time on 3.6.x

### ISSUE THREAD

**Issue by dairyisscary** [apollographql/apollo-client#9655]
I have some code like this:

```ts
const [execute, { data, loading }] = useLazyQuery(query, {
  fetchPolicy: "network-only",
  nextFetchPolicy: "cache-first",
  notifyOnNetworkStatusChange: true,
});
const handleClick = () => execute({ variables: { something } });
return <button onClick={handleClick}>do it</button>;
```
I click the button (once) but see two queries in the network tab. If i click the button a second time, with new `something`, the query appears to only fire one more time, as expected

In my debugging, I found that this line is executing the query for the same variables and same options passed to `useLazyQuery`:
https://github.com/apollographql/apollo-client/blob/76ad8a789a20a4962270649dfe5e5fbcfbf9c0fa/src/react/hooks/useQuery.ts#L215

for me, the second extra query has this:
```ts
currentWatchQueryOptions === {
  fetchPolicy: "standby"
  initialFetchPolicy: "network-only"
  nextFetchPolicy: "cache-first"
  notifyOnNetworkStatusChange: true
  query: {…}
  variables: { something }
};
// and
watchQueryOptions === {
  fetchPolicy: "network-only"
  nextFetchPolicy: "cache-first"
  notifyOnNetworkStatusChange: true
  query: {…}
  variables: { something }
}
```
Hopefully this is helpful and not just a red herring :)

**Comment by benjamn** [comment]
@dairyisscary Can you try `npm i @apollo/client@beta` to install version `3.7.0-alpha.1` (still very similar to 3.6.x)? That version includes #9666, which I think may help with this issue.

**Comment by dairyisscary** [comment]
@benjamn thanks for getting back so quickly!

No, unfortunately, I can still reproduce on `3.7.0-alpha.2`. Again, not sure if this is helpful at all but that `!equal()` check is not protecting the `reobserve` call in this case on the first re-render post-click.

**Comment by benjamn** [comment]
@dairyisscary Can you try putting the relevant code into a [runnable reproduction](https://github.com/apollographql/react-apollo-error-template/)? I'll keep trying things on my side, but a reproduction helps a ton.

**Comment by dairyisscary** [comment]
@benjamn https://github.com/dairyisscary/duplicate-lazy-query main branch has it

i struggled at first to reproduce it so i kept adding more and more of my configuration until I got it. it was the `queryDeduplication: false` on the Client constructor. sorry homie.

I'm less certain this is a bug now but i will say on apollo `3.4.17` this does not duplicate the network request twice even with `queryDeduplication` turned off (I'm two releases behind, I never got to 3.5). if its not a bug, what would you recommend benjamn? there doesn't appear to be a way to turn this on and off for a particular individual query -- i would turn it off for this particular query if it were possible.

**Comment by benjamn** [comment]
This is definitely something we (still) want to fix @dairyisscary! Thanks for the reproduction. 🙌

**Comment by benjamn** [comment]
@dairyisscary Figured it out (I think)!
* #9684

**Comment by benjamn** [comment]
@dairyisscary This should be fixed if you run `npm i @apollo/client@next` (to get version 3.6.3)!

**Comment by dairyisscary** [comment]
amazing, seems to fix the issue in real app. thanks @benjamn!
