### ISSUE TITLE
Testing - how to mock different responses for same query

### ISSUE THREAD

**Issue by tim-ninan** [apollographql/apollo-client#9656]
So I'm trying to do some testing of a certain flow where we hit the same query but at different times during the flow, expecting different results. 

My question is, is it possible to provide mock response A for the first time we hit the query, and mock response B for the second time we hit the query? This is with the same query and same variables.

**Comment by tim-ninan** [comment]
@benjamn Need some help on this if possible.

**Comment by jpvajda** [comment]
Thank you for reporting this! I suggest posting this in our [Apollo Community](https://community.apollographql.com/) for guidance from other Apollo users, as other's may have input into your question.

**Comment by thiago-soliveira** [comment]
I'm facing this same issue. I don't think this is possible with the current `MockedProvider`. 
Maybe with the [new approach](https://github.com/apollographql/apollo-client/issues/9738) this might be possible.

**Comment by jpvajda** [comment]
Relates to: #9738
