### ISSUE TITLE
NPM release 3.6.1 diff between compiled and real code

### ISSUE THREAD

**Issue by Joandres-Lara** [apollographql/apollo-client#9660]
Hi guys, I downloaded the latest version 3.6.1, in an app with Next JS 12, React 18 and Apollo 3.6, but when I package all the code, I get this error:
`Error: Missing getServerSnapshot, which is required for server-generated content. It will revert to the client rendering.`, and check the @apollo/client code, and find the difference between the real code and the compiled one, attach a screenshot. I try to remove package-lock.json and remove all files in node_modules but this didn't fix. Have you received more reports of this error?
![image](https://user-images.githubusercontent.com/38198210/166339189-3e6c2ad2-c81f-4988-bbf4-0c9b818e3ca0.png)

**Comment by benjamn** [comment]
No mismatch. We have not published 3.6.2 with the fix for the `getServerSnapshot` errors yet.

**Comment by benjamn** [comment]
@Joandres-Lara Try `npm i @apollo/client@3.6.2` now?

**Comment by Joandres-Lara** [comment]
@benjamn Yes, it seems that the version patch fixed the problem, thank you very much.
