### ISSUE TITLE
Turn off GH Discussions

### ISSUE THREAD

**Issue by jpvajda** [apollographql/apollo-client#9661]
### Related

https://github.com/apollographql/apollo-client/discussions/8247

### Issue 

Given we are moving all of our project / product discussions to our https://community.apollographql.com/ we'll want to turn off Discussions in this repository so the community isn't posting questions in the wrong location. 

We should also ensure our readme mentions clearly where our community can find support.

### Acceptance Criteria

- [ ] Turn off Discussions 
- [ ] Update Readme

**Comment by hwillson** [comment]
GitHub Discussions have been turned off. Please use https://community.apollographql.com for Apollo Client usage related questions. Thanks!
