### ISSUE TITLE
client.query not rejecting promise with error policy "none" on receiving error from apollo server

### ISSUE THREAD

**Issue by lnmp4000** [apollographql/apollo-client#9681]
**Intended outcome:**
A network error received when calling the `query` method of `ApolloClient` should cause the promise to be rejected as stated in the documentation.

> [query(options): Promise<ApolloQueryResult>](https://www.apollographql.com/docs/react/api/core/ApolloClient#ApolloClient.query)
> [(build/repo/src/core/ApolloClient.ts, line 316)](https://github.com/apollographql/apollo-client/blob/main/build/repo/src/core/ApolloClient.ts#L316)
> This resolves a single query according to the options specified and returns a [Promise](https://www.apollographql.com/docs/react/api/core/ApolloClient#Promise) which is either resolved with the resulting data or rejected with an error.

**Actual outcome:**

The code does not reach the catch statement:

```
  let result;
  try {
    result = await client.query({
      fetchPolicy: 'network-only',
     query: myQuery,
     errorPolicy: 'none',
     variables: {
       id:'myId'
     }
    });
} catch (e) {
  //handle error - this block is never reached
}
```

Given the network response:
```
{
  "errors": [
    {
      "message": "Access is denied",
      "details": "Access is denied",
      "status": "Unauthorised",
      "path": [
        "accessRecords",
        "results"
      ],
      "locations": [{ "line": 309, "column": 3 }],
    }
  ],
  "data": null
}
```

This results in an unhandled promise rejection within Apollo client code, instead of allowing me to handle the error in my try/catch block in the calling code.

```
index.js:29 Uncaught (in promise) Error: Access is denied
    at new ApolloError (index.js:29:28)
    at QueryManager.js:596:47
    at both (asyncMap.js:16:53)
    at asyncMap.js:9:72
    at new Promise (<anonymous>)
    at Object.then (asyncMap.js:9:24)
    at Object.next (asyncMap.js:17:49)
    at notifySubscription (module.js:132:18)
    at onNotify (module.js:176:3)
    at SubscriptionObserver.next (module.js:225:5)
```

![image](https://user-images.githubusercontent.com/2903591/166895364-6f367a93-bb18-4d75-8f69-68f8e304fcba.png)

**Versions**
"@apollo/client": "^3.6.2",
System:
    OS: Linux 5.15 Ubuntu 22.04 LTS 22.04 LTS (Jammy Jellyfish)
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Firefox: 99.0.1

**Comment by lnmp4000** [comment]
Was caused by a code error in a custom link in the chain.

**Comment by williamgurzoni** [comment]
@lnmp4000 I'm having the same issue, but not sure if it's generated by a custom code. Could you share a bit more how you solved it, please? Thank you.

**Comment by williamgurzoni** [comment]
I got my issue solved. The problem was that I was setting the client `defaultOptions` as `errorPolicy='all'`. This way the `client.query` was not being rejected when there was an error. You need to set it as `none` if you want the whole query to go to a `catch`.
