### ISSUE TITLE
Refetch all queries cached with any params value

### ISSUE THREAD

**Issue by azappa** [apollographql/apollo-client#9704]
I have a delete mutation
```
mutation DELETE_PROGRAM($input: DeleteProgramInput!) {
  account {
    deleteProgram(input: $input) {
      success
    }
  }
}
```
used in a hook (the `mutate` is from the `useMutation` hook)
```
const result = await mutate({
  variables: { input: { accountId, id } },
  refetchQueries: [{ query:  GET_PROGRAMS_LIST }]
})
```
```
query GET_PROGRAM(
  $accountId: ID!
  $programId: UUID!
) {
  account(id: $accountId) {
    id
    program(id: $programId) {
      ...ProgramFields
    }
  }
}
```
but if I don't pass the `variables` with exact values to the refetchQueries for the query called before navigating through my client it won't update the list.
Since the query called `GET_PROGRAM` has pagination and other types of filters should I have a list of every call I've made and refetch the same query with different params (eg, I have `page/pageSize` param, so everytime I've call it is cached with `page:1`, `page:2` and so on)? Is there a way to avoid this? To me it's ok also having the cache cleared for all the `account.program` query. I know I could use something like 
```
await mutate({
  variables...,
  refetchQueries: ['name.of.the.query.on.apollo.server']
})
```
but I don't know how to handle the nesting (I have the query under `account` parent, so should I write `account.program` as query name?).

**Comment by azappa** [comment]
> @azappa Have you tried passing the query `DocumentNode` in the `refetchQueries` array?
> 
> ```
> refetchQueries: [GET_PROGRAM]
> ```
Nope, so in this way, it refetches every query `GET_PROGRAM` cached with any params value?
> 
> If the query had a name, you can pass that instead:
> 
> ```
> refetchQueries: [“GetQuery”]
> ```
> 
Shouldn't the query name (custom by me) be `GET_PROGRAM`? Or it should be `account.programs` (not the one I've pasted before but the hierarchy is under `account` we have tons of children queries)
> You can also provide multiple documents/names (that’s what the array is for).
> 
> **I would avoid using this syntax**, since it creates a new query that’s not related to any of your existing queries:
> 
> ```
> refetchQueries: [{ query: GET_PROGRAM}]
> ```
Why do you say it create a new query? Shouldn't be `GET_PROGRAM` my custom name for the query?

**Comment by bignimbus** [comment]
Hi all, I'm doing some housekeeping and wanted to check in here.  @azappa thanks for your patience!

> so in this way, it refetches every query GET_PROGRAM cached with any params value?

Yes

> Shouldn't the query name (custom by me) be GET_PROGRAM?

Looking at your code snippet, yes - it appears the name you gave that query was `"GET_PROGRAM"`. For reference, the name of a query is declared after the `query` keyword in your graphql document.  Ex:

```graphql
# this query's name is MyQuery
query MyQuery { foo }
```

> Why do you say it create a new query?

`refetchQueries` can be passed an array of query descriptors.  These descriptors can refer to known queries or can declare new queries.  The syntax Ben warned against is declaring a duplicate query by the same name.

Anyhow, I hope that helps.  I'll close this as completed but please do feel free to ping me if you need more support here.  Our [discord server](https://discord.gg/graphos) is a great place for Q&A like this!
