### ISSUE TITLE
FieldFunctionOptions variables have incorrect data

### ISSUE THREAD

**Issue by rplotkin** [apollographql/apollo-client#9706]
**Intended outcome:**

According to the docs, and also prior @apollo/client implementations, the FieldFunctionOptions type has a _variables_ parameter that contains the variables passed to the query.  (Note, I believe #9572 is likely a related issue; I'll just mention here that _args_ is also supposed to be populated on the FieldFunctionOptions.)

This means that if I do
```
useQuery(
  gql`query MY_QUERY {
      myData([some-params])
  }`,
  {
     variables: [my-variables]
  }
)
```
then I expect FieldFunctionOptions (e.g. `read: (existing, options) => (console.log(options.variables))`) to have a variables property `options.variables === [my-variables]`.

**Actual outcome:**

Instead of `options.variables` being properly populated with the variables passed to useQuery, `options.variables.variables` is populated with data.  `options.variables` is populated with unexpected metadata, as given here:
```
options.variables ===
{
  clientOnly
  deferred
  flavors
  fragmentMap
  incomingById
  merge
  overwrite
  store
  varString
  variables // <-- this contains the variables!
  written
}
```

Another aspect of this problem is that `options.variables.variables` no longer reflects the variables passed to useQuery (`[my-variables]` if we're still using the intended outcome above).  Instead, it reflects the data in `[some-params]`.  The variables as provided in the useQuery options object are gone.  (And this is where I believe the always-null args value may also play a role.)

**How to reproduce the issue:**

Set up a custom type policy for a local-only field, run useQuery with a set of variables, and `console.log(options.variables)` on the read function.  You'll see that the values do not correspond

**Versions**

  System:
    OS: macOS 12.3.1
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Firefox: 99.0.1
    Safari: 15.4
  npmPackages:
    @apollo/client: ^3.6.2 => 3.6.2
    apollo-server-express: ^2 => 2.25.2 
    apollo3-cache-persist: ^0.14.0 => 0.14.0 
    mock-apollo-client: ^1.2.0 => 1.2.0 
    storybook-addon-apollo-client: ^4.0.9 => 4.0.9

**Comment by benjamn** [comment]
Thanks for the update @rplotkin! Please do open that other ticket when you have more to share.

**Comment by stardustxx** [comment]
Hi I also have this exact same issue (except mine is not during SSR) as reproduced here in [codesandbox](https://codesandbox.io/s/quizzical-panka-x9v60j?file=/src/index.js). I can successfully reproduce this problem from version 3.5.0 all the way to the latest 3.6. However 3.3, 3.4 didn't have this issue

In 3.5.0, it passes the `context` object to `normalizeReadFieldOptions` function and later `options.variables` would essentially equal to that `context` object
https://github.com/apollographql/apollo-client/blob/538b79594d02189f511622d8fed85b679d69dfd3/src/cache/inmemory/policies.ts#L915

In 3.4.13, `options.variables` would equal to the `variables` object
https://github.com/apollographql/apollo-client/blob/92141607ff6c650145350c222a2434cd7008e4b5/src/cache/inmemory/policies.ts#L884

Hopefully what I've written is clear, thank you
