### ISSUE TITLE
Update Code Gen documentation on developer tooling page

### ISSUE THREAD

**Issue by jpvajda** [apollographql/apollo-client#9713]
### Relates to:
- https://github.com/apollographql/apollo-client/pull/7517
- https://www.apollographql.com/docs/react/development-testing/developer-tooling

### Issue 

`apollo-codegen` hasn't been a thing for a long time (was replaced by the apollo CLI, which is now deprecated). In #7517  we removed the old documentation but now I think we should replace them with recommendations of how people can successfully use codegen with Apollo Client (e.g. using [graphql-code-generator](https://www.graphql-code-generator.com/)).

**Comment by dylanwulf** [comment]
Related: https://github.com/apollographql/apollo-tooling/issues/2053
