### ISSUE TITLE
useMutation is not calling the latest version of onCompleted

### ISSUE THREAD

**Issue by xudaashuai** [apollographql/apollo-client#9714]
**Intended outcome:**

I set an `onCompleted` callback `funcA` for `useMutation`, `funcA` depends on `state`, when I fetch and modify the state, `onCompleted` still calls the old version of `funcA`.
**Actual outcome:**

**How to reproduce the issue:**

https://codesandbox.io/s/usemutation-example-ke17zm?file=/src/index.jsx

click the add person button, expected to log `after click` in console but `before click`
<img width="683" alt="image" src="https://user-images.githubusercontent.com/19248941/168136916-ebbe59ac-bc5d-4e20-a6f8-ef7fc06f1c54.png">

**Versions**

3.6.3

**Comment by glenndixon** [comment]
Noticed this issue as well. To crystalize the situation, look at this component:

```
const MyComponent = () => {
  const [buttonClickedAt, setButtonClickedAt] = useState(null)

  const [reportClick] = useMutation(REPORT_CLICK, {
    onCompleted() {
      console.log(buttonClickedAt) // shows "null"?!
    }
  })

  const handleClick = () => {
    setButtonClickedAt(new Date())
    reportClick()
  }

  return <button onClick={handleClick}>Click me!</button>
}
```

Should we expect `buttonClickedAt` to be a date object or `null` at the `console.log` line? With the current version, this will output null.

This was not the case before this change: https://github.com/apollographql/apollo-client/pull/8596/files#diff-12d1e8016a676839edfe21e2917bf5acfae3f2bb817955e21394bf88a9fd937c

This is because previously the options were stored in a ref (`mutationDataRef`) and then read from the ref when `onCompleted`/`onError` callbacks are executed. This made it so the "latest" value of the options were always used; rather than the value of the options that were in scope when the mutation was executed.

I'm not sure this change was intentional, but maybe it was?

**Comment by nathanmarks** [comment]
@glenndixon what's the behaviour of the `onCompleted` option for `useQuery`?

curious because whichever way around it is, I imagine it should be consistent within the library itself for both hooks

**Comment by charle692** [comment]
From what I can tell through my attempts at upgrading to 3.5.x, `useQuery`'s `onCompleted` is always up to date.
`useMutation` on the other hand is not using the latest `onCompleted` as you have all mentioned.

I created an issue a while back describing this exact issue with a reproduction comparing 3.4.17 to 3.5.0 which introduced the problem.

#9493

**Comment by charle692** [comment]
Just circling back with some more information, the `onCompleted` function seems to be memoized across the execution of a mutation.

If `onCompleted` changes while the mutation is in flight, it will not be updated internally within the hook until after the mutation is complete. 

This explains why the [example above](https://github.com/apollographql/apollo-client/issues/9714#issuecomment-1126292437) doesn't work as expected:

```jsx
const handleClick = () => {
  setButtonClickedAt(new Date())
  reportClick()
}
```

As we know, `setButtonClickedAt` is asynchronous meaning that `buttonClickedAt` will not be updated until the next React render. By which point, the `reportClick` mutation is already invoked and inflight. 

In the past, the `onCompleted` would be updated no matter if the mutation is inflight or not vs now that's not the case. As soon as a mutation is triggered, `onError`, `onComplete` cannot and will not change until the mutation is completed.

A temporary workaround might be to trigger the mutation within a `useEffect` with a list of deps that are used within the `onCompleted` callback itself.

```jsx
const MyComponent = () => {
  const [buttonClickedAt, setButtonClickedAt] = useState(null)

  const [reportClick] = useMutation(REPORT_CLICK, {
    onCompleted() {
      console.log(buttonClickedAt) // works as expected due to useEffect
    }
  });
  
  useEffect(() => {
    reportClick();
  }, [buttonClickedAt]);

  const handleClick = () => {
    setButtonClickedAt(new Date());
  };

  return <button onClick={handleClick}>Click me!</button>;
}
```

But I really don't think that this should be necessary as it's highly cumbersome and not really intuitive.

**Comment by glenndixon** [comment]
I think even that solution doesn't really solve the problem in the general case. It still fixes uses the version of `options` at the time the exectutor is called (`reportClick` in this case).

A better workaround is to use a ref to store whatever info can potentially change between the executor firing and the callbacks being fired. i.e.:

```
const MyComponent = () => {
  const buttonClickedAt = useRef(null)

  const [reportClick] = useMutation(REPORT_CLICK, {
    onCompleted() {
      console.log(buttonClickedAt.current)// works as expected due to ref
    }
  });

  const handleClick = () => {
    buttonClickedAt.current = new Date()
    reportClick()
  };

  return <button onClick={handleClick}>Click me!</button>;
}

**Comment by charle692** [comment]
> I think even that solution doesn't really solve the problem in the general case. It still fixes uses the version of `options` at the time the exectutor is called (`reportClick` in this case).
> 
> A better workaround is to use a ref to store whatever info can potentially change between the executor firing and the callbacks being fired. i.e.:
> 
> ```js
> const MyComponent = () => {
>   const buttonClickedAt = useRef(null)
> 
>   const [reportClick] = useMutation(REPORT_CLICK, {
>     onCompleted() {
>       console.log(buttonClickedAt.current)// works as expected due to ref
>     }
>   });
> 
>   const handleClick = () => {
>     buttonClickedAt.current = new Date()
>     reportClick()
>   };
> 
>   return <button onClick={handleClick}>Click me!</button>;
> }
> ```

Yup that totally works as well, as long as you don't care about React re-rendering due to the info change. From my testing, either option will work but agree that neither are ideal in general and this should be changed to behave as in 3.4.17 and earlier.

**Comment by charle692** [comment]
Alright, fixed the issue in the linked ^ PR. I've confirmed in my application that is does indeed fix the issue but if you all have the chance to try it out on your end that would be appreciated :)
