### ISSUE TITLE
The onCompleted callback function from useLazyQuery gets executed 2 times instead of 1 on each query execution in NextJS app

### ISSUE THREAD

**Issue by mihail-salari** [apollographql/apollo-client#9729]
**Intended outcome:**

- The onCompleted callback function from useLazyQuery must get executed a single time on each query call, for some reason it executes 2 times even if I see a single one executed query in browser's network tab. This happens in a NextJS app.

**Actual outcome:**

- Expected behaviour is to see onCompleted function executed a single time on each performed lazy query

**How to reproduce the issue:**

- Perform a lazy query with default `fetchPolicy: cache-first` and put a console.log inside the onCompleted callback function provided for the given lazy query, you should see it getting executed 2 times instead of a single time.

⚠️ If I change the fetchPolicy to `no-cache` then it behaves as expected, a single query is getting executed

**Versions**

- It happens for `@apollo/client: 3.5.10` version

**Comment by benjamn** [comment]
@mihail-salari To find out if this is something we've fixed recently (🤞), could you try updating to v3.6.x by running `npm i @apollo/client@next` (to get version 3.6.3) and/or `npm i @apollo/client@beta` (to try 3.7.0-alpha.4)?

**Comment by jpvajda** [comment]
This sounds resolved now, so I'm going to close this issue. I'm happy you were able to resolve the problem.
