### ISSUE TITLE
`Feedback Wanted` Take the Apollo Client survey!

### ISSUE THREAD

**Issue by jpvajda** [apollographql/apollo-client#9732]
👋 The Apollo Client Team is looking for product feedback from our community to help shape the future of our Clients. If you have some time and would like to contribute, please complete [this survey ](https://events097286.typeform.com/to/U8kFGPWb) by `June 17th, 2022.`  

It should take no longer than `10 minutes` and every response will used to help us better understand your use of Apollo Client as well as what type of features and functionality you are looking for in the future.

Thank you 🙏  

> The survey is anonymous and the data will only used for directional product decisions, feature prioritization and the long term planning of our Client roadmaps.

**Comment by dylanwulf** [comment]
This is all I got when I submitted the form, did it submit correctly?
![image](https://user-images.githubusercontent.com/10980555/168867548-0ee777e5-b527-4342-b5f9-c95a52d940f7.png)

**Comment by jpvajda** [comment]
@dylanwulf Thanks for pointing that out! It seems there were multiple endings set in the typeform survey, so I remove the additional ones. It should be all fixed now. 👍

**Comment by dylanwulf** [comment]
@jpvajda Nice, thank you! Should I resubmit or did mine go through successfully?

**Comment by jpvajda** [comment]
@dylanwulf it looked like it went through, at 10:51am with the first question answer as `Retail customer relationship management & Point of Sale`

So if that is you, we have it. 😄

**Comment by dylanwulf** [comment]
@jpvajda Yes that was me, thank you. Are you planning to post the survey on [the community forum](https://community.apollographql.com/) as well?

**Comment by jpvajda** [comment]
@dylanwulf yes! you just reminded me to do that, so thanks! 😄

**Comment by jpvajda** [comment]
https://community.apollographql.com/t/feedback-wanted-take-the-apollo-client-survey/3543

**Comment by hiepxanh** [comment]
I think it's little heavy, I hope we can reduce the bundle size a little bit
![image](https://user-images.githubusercontent.com/16970990/170621447-b0b3dd92-2772-4310-8d7f-94d3bd3241c3.png)

**Comment by jpvajda** [comment]
@hiepxanh thanks for the feedback, we have been looking at reducing the growing bundle size as it's been raised as a concern from others before. 

Did you take the complete survey? We'd love to see all your additional feedback if you have the time to share.

**Comment by jpvajda** [comment]
closing this issue as this survey is closed now.
