### ISSUE TITLE
[3.6 undocumented breaking-change]: previousData new behaviour

### ISSUE THREAD

**Issue by ValentinH** [apollographql/apollo-client#9733]
**Intended outcome:**
In 3.5, `useQuery` `previousData` was always returning the previous data when the query was executed again. This was the case regardless of the query actually being the same or not. As far as I understand, the `previousData` was attached to a specific `useQuery` instance.

**Actual outcome:**
Starting from `3.6`, `previousData` is only returning the previous data when the executed query is the same as the previous execution. The only case where it's actually doing its job is when only the query variables change. As far as I understand, the `previousData` is now attached to a specific graphql query.

I understand that the expected usage is to have one query per `useQuery`. However, with tools like `https://zeus.graphqleditor.com`, we can actually have different queries attached to a single  `useQuery` depending on some state.
Therefore, this change in behavior is a breaking change that hit us while updating to version 3.6. Basically, we cannot rely anymore on `previousData` to show a placeholder while the new query is pending.

**How to reproduce the issue:**
I set up a minimal demo to show the regression. We display a list of countries per continent. When switching from "Europe" to "North-America", the intended behavior is to still show the list while the new data is being fetched.

- **3.5 version** (expected behavior): https://codesandbox.io/s/previousdata-behavior-3-5-ubh13l?file=/src/index.js:1090-1414
- **3.6 version** (broken behavior): https://codesandbox.io/s/previousdata-behavior-3-6-9i1zi4?file=/src/index.js:1090-1414
- **3.6 version** (fixed behavior but not ideal when using `graphql-zeus`): https://codesandbox.io/s/previousdata-behavior-3-6-with-variable-qmf7sh?file=/src/index.js

**Versions**
@apollo-client: 3.6.4

**Comment by benjamn** [comment]
@ValentinH Please have a look at PR #9734 when you have a chance!

**Comment by ValentinH** [comment]
Thanks for the quick answer. I'll have a look ASAP.
Is there a way to get a canary release so I can try it on codesandbox or on my project?
