### ISSUE TITLE
error: Error: Unable to resolve module ../../../../../src/graphql when running the app

### ISSUE THREAD

**Issue by kolyasya** [apollographql/apollo-client#9737]
```
react: 17.0.2 => 17.0.2
react-native: 0.68.1 => 0.68.1
```

After adding `@apollo/client@3.6.4` I get such error:

```
 BUNDLE  ./index.js

error: Error: Unable to resolve module ../../../../../src/graphql from /Users/nikolay/webdev/wm-mobile/node_modules/@apollo/client/utilities/globals/globals.cjs:

None of these files exist:
  * src/graphql(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.cjs|.native.cjs|.cjs)
  * src/graphql/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.cjs|.native.cjs|.cjs)
> 1 | 'use strict';
  2 |
  3 | Object.defineProperty(exports, '__esModule', { value: true });
  4 |
    at ModuleResolver.resolveDependency (/Users/nikolay/webdev/wm-mobile/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:136:15)
    at DependencyGraph.resolveDependency (/Users/nikolay/webdev/wm-mobile/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at Object.resolve (/Users/nikolay/webdev/wm-mobile/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/nikolay/webdev/wm-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/nikolay/webdev/wm-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/nikolay/webdev/wm-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/nikolay/webdev/wm-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async addDependency (/Users/nikolay/webdev/wm-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)


```
    
    
    
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/3371143/169024379-916ea4d6-f780-41e8-9b6d-3005a80ec195.png">

    
 I've tried all available `metro.config.js` variants, as well as removing it.
 For example:

```
 const defaultSourceExts =
 require('metro-config/src/defaults/defaults').sourceExts;
module.exports = {
 transformer: {
   getTransformOptions: () => ({
     transform: {
       experimentalImportSupport: false,
       inlineRequires: true,
     },
   }),
 },
 resolver: {
   sourceExts: process.env.RN_SRC_EXT
     ? [...process.env.RN_SRC_EXT.split(',').concat(defaultSourceExts), 'cjs'] // <-- cjs added here
     : [...defaultSourceExts, 'cjs'], // <-- cjs added here
 },
};

```
    
Still the error appears.

What am I doing wrong? Is that a bug?

**Comment by benjamn** [comment]
If you have a look in the file in question, `node_modules/@apollo/client/utilities/globals/globals.cjs`, the only reference it contains to the `graphql` package is a single `require('graphql')` call, so React Native (or Metro) must somehow be resolving that valid/normal `require` not to the package `node_modules/graphql` but to some directory in your application's source tree (or so I'm guessing), hence that strange relative path `../../../../../src/graphql`.

Do you know where that `src/graphql` directory resides?

Is there anything about your React Native configuration that might cause npm packages to be resolved in source directories of your application?

If you don't want to track this down, you could try changing the `src/graphql` directory name to something else (not matching any npm package names), but that sounds like an effortful and fragile workaround.

**Comment by kolyasya** [comment]
@benjamn thank you! Yes, I think I'm getting an idea what have happened. Me or my team mate will share more information later here

**Comment by Bboyredstar** [comment]
@benjamn Hello, after changing the name of the local folder, everything worked, we will monitor this problem further, thanks!

**Comment by jpvajda** [comment]
I'm glad you were able to work this out! I'm going to close this issue as it sounds resolved. 🙌
