### ISSUE TITLE
Can't get returnPartialData and getDataFromTree (server side rendering) to work at the same time

### ISSUE THREAD

**Issue by ngbrown** [apollographql/apollo-client#974]
I'm using React and Redux and doing server side rendering.

I have a list where you click on it, and it brings up details.  I want to re-use as much as possible from the list fetch (such as title, author, etc.) while pulling down the details.

That all works great on the client when `returnPartialData: true` is set in the `graphql()` enhancer options.  However, when triggering a server side render by going directly to the detail page in the browser, the `getDataFromTree` from `react-apollo/server` skips over the detail query.

I can set `returnPartialData: false` (or unset it), and then the server pulls the data and includes it in the state, but the partial loading of the detail page doesn't work.

I'm guessing this is an oversight, because there's also the `ssr: false` option for queries, that would skip it for server side.

**Comment by helfer** [comment]
@ngbrown Thanks! Can you be a bit more specific about what you mean by "skips over the detail query". Did you reach that conclusion by running a debugger, or just by looking at the rendered page and not seeing what you expected?

**Comment by ngbrown** [comment]
@helfer sorry, I didn't run the debugger so I don't know exactly where in the code it is happening. 

I did see that the `/graphql` endpoint wasn't hit (I would have seen console output if it did) and the page response didn't contain the HTML or `window.__PRELOADED_STATE__` I was expecting.  Turning on and off `returnPartialData` was all that it took to change this.

**Comment by calebmer** [comment]
Hey @ngbrown, could you provide a reproducible test case? Or even better open a PR with a failing test?

**Comment by helfer** [comment]
`returnPartialData` is no longer supported, so closing this old issue.
