### ISSUE TITLE
Understanding relayStylePagination default behavior

### ISSUE THREAD

**Issue by skysantoroa** [apollographql/apollo-client#9743]
It is not clear to me what is the default behavior of the `relayStylePagination` policy for the `read` and `merge` functions. Does `read` append the incoming data and `merge` all? By default, is `relayStylePagination` meant to be used for infinite scrolling pagination?

**Comment by jpvajda** [comment]
@skysantoroa  according to our Docs: https://www.apollographql.com/docs/react/pagination/cursor-based/#relay-style-cursor-pagination

> Note that the relayStylePagination function generates a field policy with a read function that simply returns all available data, ignoring args, which makes relayStylePagination easier to use with fetchMore. This is a [non-paginated read function](https://www.apollographql.com/docs/react/pagination/core-api/#non-paginated-read-functions). There's nothing stopping you from adapting this read function to use args to return individual pages, as long as you remember to update the variables of your original query after calling fetchMore.


Does that help you at all? Or do you feel the docs are lacking some specific context where we can clarify a bit.
