### ISSUE TITLE
TypeDoc generated code in docs pages is showing a reference to a .ts file

### ISSUE THREAD

**Issue by jpvajda** [apollographql/apollo-client#9778]
When viewing Docs pages that seem to use [TypeDoc ](https://typedoc.org/)to generate API documentation from TypeScript we are showing a reference to `.ts` file that doesn't seem to exist.  On click it takes you to a github 404 page.

### Screenshot
![Screen Shot 2022-06-01 at 2 47 00 PM](https://user-images.githubusercontent.com/1395158/171498601-2eadffb1-d164-4a01-a721-f1f569f4bb97.png)

###  Example pages 

https://www.apollographql.com/docs/react/api/core/ApolloClient/#ApolloClient.mutate
https://www.apollographql.com/docs/react/api/core/ApolloClient/#functions

###  Steps to reproduce 

1. go the pages above
2. look for the API reference documentation and click on the link to the .ts file.
3. see the github 404 page. 

### Expected

When doing generated documentation with TypeDoc we don't reference a link to a  file on github at all in our Docs pages.

**Comment by jpvajda** [comment]
@StephenBarlow 👋  Did you have any experience with the setup or use of TypeDoc? I'm curious to hear what you think about this issue I foudnd?

**Comment by hwillson** [comment]
This was resolved - thanks!
