### ISSUE TITLE
useLazyQuery holds previous value in cache in v3 but undefined in v2

### ISSUE THREAD

**Issue by bohdanbirdie** [apollographql/apollo-client#9783]
With apollo client v2, when using the `useLazyQuery` with polling, the `data` property was `undefined` before the first load, then stored value, then `undefined` again on the new loading.

In v3 it holds the previously loaded value until the new has been fetched.

Comparing
| data value                               | V2        | V3            |
|------------------------------------------|-----------|---------------|
| initial                                  | undefined | undefined     |
| after first loading                      | data      | data          |
| after the new polling has been initiated | undefined | **_previous data_** |
| after the new polling is done            | new data  | new data      |

Additional details:
- fetchPolicy is `no-cache`
- polling is stopped with `stopPolling`
- new polling is started with calling the query function again (also tried with `startPolling`

Is there a way to get the `data` to be reset to `undefined` on every new polling initiative?

**Comment by bignimbus** [comment]
Hi @bohdanbirdie 👋🏻 thanks for your patience!  Just trying to narrow down some possible solutions here: have you tried using the `network-only` fetch policy?
