### ISSUE TITLE
Eslint unsafe-assignment of function gql

### ISSUE THREAD

**Issue by thomasender** [apollographql/apollo-client#9796]
**Intended outcome:**
Update of apollo client from 3.2.5 to 3.6.6 to resolve a bug where `useQuery` would deliver the correct data but then give the result of the same query again without the data.

**Actual outcome:**
After the update, the buggy behaviour, that lead to the decision to try an update, was resolved. Unfortunately, since updating to version `3.6.6`, `eslint` is no longer happy with the function `gql` from `@apollo/client` and gives this warning:
<img width="1048" alt="Screenshot 2022-06-08 at 10 00 26" src="https://user-images.githubusercontent.com/73962379/172564190-0498ca8b-238e-4bd0-a7b8-3e36b10caf30.png">

I could not find any posts of other devs having the same issue, so I figured it would be interesting to raise the issue here.

**How to reproduce the issue:**
Not sure if this will help to reproduce, but have apollo client 3.2.5 installed, then update to 3.6.6 using `yarn upgrade`

**Versions**
System:
    OS: macOS 11.6.1
  Binaries:
    Node: 14.17.6 - ~/.asdf/installs/nodejs/14.17.6/bin/node
    Yarn: 1.22.11 - ~/Desktop/Lovley/sc-fe/node_modules/.bin/yarn
    npm: 8.3.2 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 100.0
    Safari: 14.1.2
  npmPackages:
    @apollo/client: 3.6.6 => 3.6.6 
    @apollo/react-ssr: 4.0.0 => 4.0.0 
    apollo-cache-inmemory: 1.6.6 => 1.6.6 
    apollo-link-persisted-queries: 0.2.2 => 0.2.2

**Comment by bignimbus** [comment]
Hi @thomasender 👋🏻 I recommend taking a look at our [TypeScript with Apollo Client docs](https://www.apollographql.com/docs/react/development-testing/static-typing/).  There are some great tools out there like GraphQL Code Generator that can help automate type safety.  I'll close this issue for now but please feel free to reach out if you think there's a bug here!
