### ISSUE TITLE
FieldFunctionOptions return incorrect variables

### ISSUE THREAD

**Issue by stardustxx** [apollographql/apollo-client#9804]
**Intended outcome:**

Prior to 3.5.0 and according to the doc, we can add a local-only field and utilize the policy file to populate the data by using the `read` and `readField` functions if necessary.

Code may look something like this:
```
fields: {
  isCanada: {
    read(_, { readField }) {
      return readField("name") === "Canada";
    }
  },
  name: {
    read(name, { variables }) {
      return name;
    }
  }
}
```
The `variables` in the `read` function should always return the actual variable passed to this particular query. So something like:
```
{
  code: "CA"
}
```
**Actual outcome:**

Instead of returning the actual variables, it returns other metadata like:
<img width="221" alt="image" src="https://user-images.githubusercontent.com/7050316/172903626-434f3813-554b-4767-a552-6b026cf20817.png">

The actual variables are in `variables.variables` now

**How to reproduce the issue:**

Set up a local field and the read function for that field. In that read function, have it access another field using `readField` function.  Set up another read function for the field being accessed, then console log the variables.

https://codesandbox.io/s/quizzical-panka-x9v60j?file=/src/index.js

Sorry I know I'm probably not supposed to share speculation but this is what I've found:
In 3.5.0, it passes the `context` object to `normalizeReadFieldOptions` function and later `options.variables` would essentially equal to that `context` object
https://github.com/apollographql/apollo-client/blob/538b79594d02189f511622d8fed85b679d69dfd3/src/cache/inmemory/policies.ts#L915

In 3.4.13, `options.variables` would equal to the `variables` object
https://github.com/apollographql/apollo-client/blob/92141607ff6c650145350c222a2434cd7008e4b5/src/cache/inmemory/policies.ts#L884
There was probably a reason I wasn't aware of but just want to share what I've found, thank you

**Versions**

System:
    OS: macOS 12.3.1
  Binaries:
    Node: 14.19.3 - /usr/local/opt/node@14/bin/node
    npm: 6.14.17 - /usr/local/opt/node@14/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Edge: 102.0.1245.33
    Firefox: 101.0
    Safari: 15.4
  npmPackages:
    @apollo/client: ^3.5.0 => 3.5.0

**Comment by benjamn** [comment]
Thanks for reporting this issue (and then fixing it!) @stardustxx!
