### ISSUE TITLE
Options Query does not read the standard CORS header from postGraphile

### ISSUE THREAD

**Issue by redaikidoka** [apollographql/apollo-client#9824]
## Expectation:

I should be able to run queries against `postGraphile` with postGraphile's standard allow-cors settings.

## Actual Outcome:

We have 2 graphQL providers. One is rails and we can configure the headers to match what apollo/client expects.

Another is postGraphile and we are trying not to have to run it as an app, but just naked, and its implementation of CORS headers does not match what apollo/client expects. And since Apollo will only send plain text with cors disabled, we can't use that option either, because *postGraphile* will not parse plain text.

1. When **@apollo/client** does an OPTIONS query, *postGraphile* with CORS returns:
```
Access-Control-Allow-Origin: * 
Access-Control-Allow-Headers: Origin, X-Requested-With, Accept, Authorization, X-Apollo-Tracing, Content-Type, Content-Length, X-PostGraphile-Explain
```

2. since it allows `Origin` but not `Access-Control-Allow-Origin`, postGraphile's specification for Access-Control-Allow-Origin is ignored and Apollo Client refuses to execute the query.

## **How to reproduce the issue:**

1. run postgraphile: `npx postgraphile -n lvh.me -c postgres://gemini:abc123@localhost/gemini --watch --enhance-graphiql --skip-plugins graphile-build:NodePlugin --simple-collections both --allow-explain`

2. Apollo Client configuration:
```
// ./apollo-client.js

import {
  ApolloClient,
  InMemoryCache,
  ApolloLink,
  HttpLink
} from '@apollo/client';
import { getCookie } from 'cookies-next';

// use lvh.me for development and localhost for staging and production
const httpMonolithLink = new HttpLink({
  uri: process.env.NEXT_PUBLIC_GQL_SERVER
});
const httpPostGraphileLink = new HttpLink({
  uri: process.env.NEXT_PUBLIC_P_GQL_SERVER
});
const authLink = new ApolloLink((operation, forward) => {
  /*
    NOTE: You need to login to `GQL_URL` (lvh.me:3000) (the monolith) in your browser
    to have the needed auth token cookie accessible to this app
  */
  const userEmail = getCookie('apiTokenEmail');
  const userToken = getCookie('apiToken');

  // Use the setContext method to set the HTTP headers.
  operation.setContext({
    headers: {
      'X-User-Email': userEmail,
      'X-User-Token': userToken,
      'Access-Control-Allow-Origin': '*'
    }
  });

  // console.log('ApolloClient: httpMonolithLink', httpMonolithLink);
  // console.log('ApolloClient: httpPostGraphileLink', httpPostGraphileLink);

  // Call the next link in the middleware chain.
  return forward(operation);
});

// load from server
const client = new ApolloClient({
  link: ApolloLink.split(
    (operation) => operation.getContext().clientName === 'postGraphile',
    authLink.concat(httpPostGraphileLink),
    authLink.concat(httpMonolithLink)
  ), // Chain it with the HttpLink
  cache: new InMemoryCache()
});

export default client;
```

3. simple query: (or any similar simple database query)
```
export default MY_SIMPLE_QUERY = gql` query MyQuery {
  allActionLogs(first: 20) {
    edges {
      node {
        id
        actionLog
        actionSeconds
        affectedRecords
        createdAt
      }
    }
  }
}`;

```

4. Then in a .tsx file:

```
import { useQuery } from '@apollo/client/react/hooks/useQuery';
import MY_SIMPLE_QUERY from 'myFancyQuery.graphql';

const { data, loading, error } = useQuery(MY_SIMPLE_QUERY, {
    context: { clientName: 'postGraphile' }
  });
```

## **Versions**

npx output:
```

  System:
    OS: macOS 12.4
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Safari: 15.5
```

package.json:
```
"dependencies": {
    "@apollo/client": "^3.6.5",
    "@emotion/react": "^11.9.0",
    "@emotion/styled": "^11.8.1",
    "@fortawesome/fontawesome-pro": "^6.1.1",
    "@fortawesome/fontawesome-svg-core": "^6.1.1",
    "@fortawesome/free-solid-svg-icons": "^6.1.1",
    "@fortawesome/pro-light-svg-icons": "^6.1.1",
    "@fortawesome/pro-solid-svg-icons": "^6.1.1",
    "@fortawesome/react-fontawesome": "^0.1.18",
    "@mui/material": "^5.8.1",
    "@mui/x-data-grid": "^5.11.1",
    "cookies-next": "^2.0.4",
    "graphql": "^16.5.0",
    "jest-environment-jsdom": "^28.1.0",
    "next": "^12.1.6",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-hook-form": "^7.31.2",
    "rollbar": "^2.25.0",
    "sass": "^1.52.1",
    "yup": "^0.32.11"
  },
```

**Comment by bignimbus** [comment]
Hi @redaikidoka 👋🏻 thanks for your patience.  Apologies in advance, I'm not the most familiar with some of our networking functionality.  I don't see anything in our docs or source code that seems to conform to these statements:

> And since Apollo will only send plain text with cors disabled

>  postGraphile's specification for Access-Control-Allow-Origin is ignored and Apollo Client refuses to execute the query

Again, apologies if I'm missing something obvious, I'm just wondering whether this is an issue with how the network request is being made rather than something to do with the client itself.  Have you tried using the [`fetchOptions` property](https://www.apollographql.com/docs/react/api/link/apollo-link-http/#fetchoptions) and setting something like `mode: 'cors'`?
