### ISSUE TITLE
[Error: Server response was missing for query 'queryName'.]

### ISSUE THREAD

**Issue by X-vishnu-X** [apollographql/apollo-client#9829]
**Intended outcome:**

In the postman response is successful and the the response i am getting.

```json
{
    "data": {
        "createUser": {
            "success": true,
            "message": "User created",
            "token": "123",
            "login": null,
            "user": {
                "firstname": "123",
                "lastname": "456",
                "username": "user123",
                "phone": "+1111111",
                "email": null,
                "category": 1,
                "userRecovery": null,
                "profileStatus": "USER_ID_CREATED",
                "accountStatus": 1,
                "deleted": false,
                "settings": {
                    "archievedChats": null,
                    "defaultStartScreen": 4
                },
                "blockedUsers": [],
              
            }
        }
    }
}
```

**Actual outcome:**

 Trying to run a query using graphql, but keep getting a Network error.This happening only with few of the queries. whenever the API for this query called directly goes to the `catch (error) {
    return error;`  
Then it shows 
`[Error: Server response was missing for query 'queryName'.]` 

**Versions**

"npm": "8.10.0",
"@apollo/client": "^3.6.8",
"graphql": "^16.5.0",

**Comment by bohdanbirdie** [comment]
How does the query look like?
Also, have you tried fetching with `id` field included?

**Comment by MrDoomBringer** [comment]
Hi @X-vishnu-X, would it be possible to create a reproduction of this issue using https://codesandbox.io/s/github/apollographql/react-apollo-error-template or https://github.com/apollographql/react-apollo-error-template, and linking to it here? Thanks so much :-)

**Comment by bignimbus** [comment]
Hi all 👋🏻  given the lack of activity and nothing actionable emerging for the team I'll close this issue for now.  Let us know if you need more support 🙏🏻
