### ISSUE TITLE
updateQuery documentation error

### ISSUE THREAD

**Issue by KhalfaniW** [apollographql/apollo-client#9832]
The function signature in the documentation for updateQuery says it takes 2 parameters and returns TData
`(previousResult: TData, options: { variables: TVariables }) => TData`

 https://www.apollographql.com/docs/react/api/react/hooks/#updatequery

However in the code it takes a mapFn parameter and returns void
https://github.com/apollographql/apollo-client/blob/3d039f81239018cee0ed8e1c1c1a2770504ce5d1/src/core/ObservableQuery.ts#L602

Please also explain what mapFn is supposed to do because I was confused.

**Comment by jpvajda** [comment]
@KhalfaniW thanks for reporting this. I've added this issue to an Umbrella issue to do some documentation updates.

**Comment by MrDoomBringer** [comment]
@KhalfaniW Thanks for the report. You're correct, updateQuery only takes 1 argument, `MapFn`.

`MapFn` is a function with the signature `(previousResult: TData, options: { variables: TVariables }) => TData`, meaning it takes the `data` object you get from useQuery, etc., an optional variables object, and returns a modified version of that data.

You can see usage in [Reading and Writing Data to the Cache](https://www.apollographql.com/docs/react/caching/cache-interaction/#using-updatequery-and-updatefragment).

Here's a quick example written in the [fullstack tutorial's launch page](https://github.com/apollographql/fullstack-tutorial/blob/main/final/client/src/pages/launch.tsx). 
![image](https://user-images.githubusercontent.com/29008542/184238206-e638cf32-4938-401b-9777-78292a3b1fb0.png)
