### ISSUE TITLE
Doesn't work with Vite 3 , Apollo shipping wrong ESM entries

### ISSUE THREAD

**Issue by brillout** [apollographql/apollo-client#9834]
Because of an ESM compatibility problem. Note that a lot of libraries do work with Vite 3, so I'm leaning towards thinking that it's an issue on Apollo GraphQL's side.

Reproduction: https://github.com/brillout/graphql-apollo_vite-3_bug-2.

(I didn't manage to make a more minimal reproduction because of https://github.com/apollographql/apollo-client/issues/9833.)

**Comment by jpvajda** [comment]
@brillout  Since this is tracked in https://github.com/apollographql/apollo-client/issues/8190 how would you feel about me closing this out for now?

**Comment by brillout** [comment]
Sure.

**Comment by brillout** [comment]
Actually, this one is not related to #8190. This bug seems to be about apollo shipping wrong ESM entries. See https://github.com/brillout/graphql-apollo_vite-3_bug-2.

This may very well break all vite-plugin-ssr Apollo GraphQL users who will want to switch from Vite 2 to Vite 3.

**Comment by jpvajda** [comment]
@brillout Thanks for clarifying, I'll reopen this issue and clarify the title a bit.

**Comment by williamrjribeiro** [comment]
Hello. Any updates on this issue or any idea if a fix is planned for `v3` or just `v4` of Apollo Client? I'm looking forward to upgrading to Vite 3 on my projects that use Apollo Client. 😃

**Comment by alessbell** [comment]
Hi @brillout 👋  thanks for following up here. I took a look at https://github.com/brillout/graphql-apollo_vite-3_bug-2 but was seeing some unrelated errors regarding `@vue/apollo-composable` imports.

In search of a more minimal reproduction, I found the excellent examples in your [vite-plugin-ssr](https://github.com/brillout/vite-plugin-ssr) repo :) I was able to get `examples/graphql-apollo-react` running with Vite v3 with minimal changes and opened a PR here: https://github.com/brillout/vite-plugin-ssr/pull/369

As you know, this example imports from `@apollo/client` on both the client and server. As far as I can see,`@apollo/client` is compatible with Vite v3, but please let me know if you have any other concerns. Thanks!

**Comment by brillout** [comment]
Thanks for the PR! Let's see if the test suites goes green and, if yes, then we can close this 👌.

**Comment by brillout** [comment]
vite-plugin-ssr's Apollo test suites are green again 🟢.

**Comment by alessbell** [comment]
Just saw you merged the PR @brillout, thanks for your help here!
