### ISSUE TITLE
useQuery hook - errorPolicy 'all' - onError callback not called following version 3.4.17

### ISSUE THREAD

**Issue by jwarykowski** [apollographql/apollo-client#9842]
**Intended outcome:**
When you define  `errorPolicy: 'all'` in a `useQuery` hook and provide an `onError` callback we expected this to be called when receiving a response with both data and Graphql errors. Please see the simple example below.

```js
function Dog({ name, onError, onCompleted }) {
  const { loading, error, data } = useQuery(GET_DOG_QUERY, {
    variables: { name },
    onCompleted,
    onError,
    errorPolicy: "all"
  });

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error!</p>;

  return (
    <p>
      {data.dog.name} is a {data.dog.breed}
    </p>
  );
}
```

**Actual outcome:**
The `onError` hook is never called following version `3.4.17`. 

![Screen Shot 2022-06-20 at 12 36 23 pm](https://user-images.githubusercontent.com/406799/174515357-e7060321-f898-44ef-9f03-79233b64efbd.png)

**How to reproduce the issue:**
You can replicate this problem by running the tests within the following code sandbox:

https://codesandbox.io/s/sweet-minsky-5qe67r?file=/src/index.test.js

Note the tests will pass when you change the version of `@apollo/client` to `3.4.17`. The version on the code sandbox is `3.5.0`.

**Versions**
Issue appears to be present on all versions following `3.4.17`.

**Comment by jwarykowski** [comment]
What is the intended behaviour following version `3.4.17`? 

From version `3.5.0` the `onCompleted` callback is called but does not contain the partial errors, furthermore the data returned from the hook also does not contain the error property. After reading the documentation there appears to be some confusion here:

> A callback function that's called when your query successfully completes with zero errors (or if errorPolicy is ignore and partial data is returned).
> 
> This function is passed the query's result data.

Our response has partial errors so I'm assuming after reading the above that the `onCompleted` callback should not be called as we don't have zero errors and our error policy is not `ignore`.

When you compare this to the onError callback documentation below: 

> A callback function that's called when the query encounters one or more errors (unless errorPolicy is ignore).
> 
> This function is passed an [ApolloError](https://github.com/apollographql/apollo-client/blob/d96f4578f89b933c281bb775a39503f6cdb59ee8/src/errors/index.ts#L36-L39) object that contains either a networkError object or a graphQLErrors array, depending on the error(s) that occurred.

In our case given the above, I would expect the `onError` callback to always be called as we have errors and the errorPolicy is not ignore, I assume the data returned from the hook should also contain the error property also.

I'm thinking there is something wrong with my mock here, I'm assuming returning an instance of `GraphQLError` is correct and should be picked up?

**Comment by jpvajda** [comment]
@jwarykowski 👋  sorry for the delay in the response, let me add a few of the core team members to see if anyone has some ideas here.  cc @benjamn @alessbell @bignimbus

**Comment by bignimbus** [comment]
Hi @jwarykowski 👋🏻 thanks so much for bringing this to our attention!  We'd be really interested to learn about the issues you're seeing.  In the meantime, can you try [this fork](https://codesandbox.io/s/throbbing-cherry-cyv438?file=/src/index.test.js) of your codesandbox?  I'm able to get a green test suite by changing the shape of the mock.  Here's the substance of the change:

```js
// before
{
  // ...
  result: {
    data: {
      dog: { id: "1", name: "Buck", breed: "bulldog" }
    },
    errors: [new GraphQLError("Jon!")]
  }
}

// after
{
  // ...
  error: [new GraphQLError("Jon!")],
  result: {
    data: {
      dog: { id: "1", name: "Buck", breed: "bulldog" }
    }
  }
}
```

I hope that helps on the unit testing side!  We'll keep this issue open in case there are other items to cover.  Looking forward to hearing from you!

**Comment by jwarykowski** [comment]
Hi @bignimbus, thanks for the quick feedback. After looking into this further, it appears this was added as a bug between v3.4.4 and v3.4.5 (https://github.com/apollographql/apollo-client/compare/v3.4.4...v3.4.5), if you change the library version in the code sandbox you'll see that my test starts passing from v3.4.5. I haven't dived too much into the code but appears this was a regression which would cause the onError callback to be called until v3.5.0.

Nevermind, it appears that our application code is expecting this so when we update to v3.5.0 a few of our tests fail as the error is on the incorrect property which is causing our confusion. Sorry I'm surprised I didn't notice this at the beginning. I'll try and look into this further over the next few weeks as we would really like to upgrade. I'll let you know if I run into anything else.

Thanks again for your teams help 🙇 I'll close this ticket.
