### ISSUE TITLE
REACT-NATIVE: Invariant Violation: Expecting a parsed GraphQL document. Perhaps you need to wrap the query string in a "gql" tag?

### ISSUE THREAD

**Issue by adembacajmemmo** [apollographql/apollo-client#9847]
Hello everyone, after migrating from Apollo-Client V2 to V3, I am not able to work on debug more anymore. IF I run the app it will work normally as it was working until I do any change in any project file. Each time I save anything from the project, it will crash with the error below

**Intended outcome:**

After migrating from Apollo-Client V2 to Apollo-Client V3, everytime I save anything on my project file, it will crash the app, and will throw this message: 

> Invariant Violation: Expecting a parsed GraphQL document. Perhaps you need to wrap the query string in a "gql" tag? http://docs.apollostack.com/apollo-client/core.html#gql, js engine: hermes

**Actual outcome:**

It should work normally without any issue. I am using gql from @apollo/client library
**How to reproduce the issue:**

**Versions**

**Comment by jpvajda** [comment]
@adembacajmemmo 👋  could you run the following command in your project directory, and paste its (automatically copied to clipboard) results here:

`npx envinfo@latest --preset apollo --clipboard`

**Comment by adembacajmemmo** [comment]
@jpvajda After downgrading to 3.4.17, I can not reproduce this issue anymore, but immediately after upgrading to 3.5.x or bigger version, I am facing this issue.

**Comment by vinaygupta98** [comment]
any updates to this?

**Comment by jpvajda** [comment]
@vinaygupta98 are you also experience this issue? If so do you mind running this command and replying with the output? 

`npx envinfo@latest --preset apollo --clipboard`

**Comment by LukasGrubis** [comment]
Same error with "@nuxtjs/apollo": "^4.0.1-rc.5"

```
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
  Binaries:
    Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
    Yarn: 1.22.19 - ~/call-center-front-end/node_modules/.bin/yarn
    npm: 8.5.5 - ~/node_modules/.bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 106.0.5
  npmPackages:
    apollo-link-error: ^1.1.13 => 1.1.13
```
![image](https://user-images.githubusercontent.com/111849393/200483009-8aac65ed-1b06-4971-9867-bed3862c6c0a.png)

**Comment by bignimbus** [comment]
Thanks for your patience folks, could someone share some code snippets so we can help narrow down the issue here?  I'm also wondering whether the behavior is the same if you remove `react-apollo-network-status` from the link chain?
