### ISSUE TITLE
Apollo cache don`t work for query with param

### ISSUE THREAD

**Issue by pekanboy** [apollographql/apollo-client#9849]
Hello! I making unit test for check cache, when offline. I mocked useQuery response like this:

<img width="463" alt="Screenshot 2022-06-23 at 11 14 23" src="https://user-images.githubusercontent.com/57917516/175250680-b778d5d6-209d-41f9-84e8-e71c925e3a2e.png">

Also i am init cache, and i am write data to cache like this:

<img width="436" alt="Screenshot 2022-06-23 at 11 16 25" src="https://user-images.githubusercontent.com/57917516/175251060-ac13973f-90b8-4d3a-a034-91b8da7a9fe0.png">

I use MockedProvider for mock cache and useQuery response.

The following problem is that useQuery return normal cache if we added simple object in query like this:

<img width="626" alt="Screenshot 2022-06-23 at 11 19 43" src="https://user-images.githubusercontent.com/57917516/175251670-e83fd74e-23cf-4347-8eb0-fa3775bb2fc3.png">

Its work for me, **but if i need provide one parameter then useQuery return undefined response.** I changed graphql query like this:

<img width="597" alt="Screenshot 2022-06-23 at 11 22 09" src="https://user-images.githubusercontent.com/57917516/175252205-73c0d675-91b3-4a3b-8f2a-df25407a87fb.png">

Please follow my problem and help me :(

**Comment by bignimbus** [comment]
Hi @pekanboy 👋🏻  thanks for your patience.  I'm happy to provide an extra set of eyes but I can only get so far with screenshots of code.  If you're still in need of support here, please do provide more detail.  For example, what is the value of `events` being written into the cache?
