### ISSUE TITLE
Apollo returning the wrong data

### ISSUE THREAD

**Issue by servonlewis** [apollographql/apollo-client#9850]
Hello all,

I have been using Apollo Client for a long time now, but have now run into a very weird issue.

If I perform a specific query, it is giving me the wrong data...which I will explain in a moment.  The main part to focus on is that if I view the data in the preview field in the networking tab on Chrome, it shows the correct data, but if I console.log, or show the data on a webpage using @apollo/client, it shows the wrong data.

The following two queries are identical, and point to the same URL, which I was able to verify in the chrome networking tab, however, ONLY the fetch function provides the accurate data.

```typescript
  client
    .query({
      query: gql`
        query someQuery{
          someQuery{
            enrollment_id

          }
        }
      `,
    })
    .then(console.log);

    fetch(url, {
      method: 'POST',
      body: JSON.stringify({
        query: `
    query someQuery{
      someQuery{
        enrollment_id
      }
    }
  `,
      }),
    }).then((x) => x.json().then(console.log));
```

The result of fetch shows correctly, with the following enrollment_ids.

```typescript
     {
        "enrollment_id": 324688375,
      },
      {
        "enrollment_id": 324688379,
      },
```

However, using apollo client, it returns this:

```typescript
     {
        "enrollment_id": 324688375,
      },
      {
        "enrollment_id": 324688375,
      },
```

These are the same urls, same query, same everything, just one is using a fetch request, and the other is apollo client.

I've reinstalled apollo and graphql, which did not help.

Version: "@apollo/client": "^3.6.9", "graphql": "^16.5.0", "react-dom": "^18.1.0",

**Comment by dylanwulf** [comment]
Errors like this are often caused by a misconfigured cache. Try using `fetchPolicy: 'no-cache'`. If that works and you don't mind that caching is unavailable for this query, then you can keep it like that. But if you do need caching for this query, you might need to change some cache configuration options (such as [keyFields](https://www.apollographql.com/docs/react/caching/cache-configuration/#customizing-cache-ids)).

If using `fetchPolicy: 'no-cache'` still gives you the wrong result, then it might be a bug.

**Comment by servonlewis** [comment]
> Errors like this are often caused by a misconfigured cache. Try using `fetchPolicy: 'no-cache'`. If that works and you don't mind that caching is unavailable for this query, then you can keep it like that. But if you do need caching for this query, you might need to change some cache configuration options (such as [keyFields](https://www.apollographql.com/docs/react/caching/cache-configuration/#customizing-cache-ids)).
> 
> If using `fetchPolicy: 'no-cache'` still gives you the wrong result, then it might be a bug.

You are right, setting to no cache fixed it.  I would like to use cache however, as the data only updates once a day.  I will look into kefields!
