### ISSUE TITLE
useMutation encounters error "Can't perform a React state update on an unmounted component"

### ISSUE THREAD

**Issue by tpham** [apollographql/apollo-client#9858]
I'm using useMutation call in a React's useEffect's cleanup function like this:
```
   const [ changeSomething ] = useMutation(...);
  ...
   useEffect(() => {
    return () => {
      changeSomething(...)
   };
  }, []);
```
It seems that depending on the timing of when the component is dismounted, from time to time, the call to mutate would result in the error message "Can't perform a React state update on an unmounted component". Looking at the stack trace, I found the offending line `setResult` in useMutation code:

```
  const execute = useCallback((
    executeOptions: MutationFunctionOptions<
      TData,
      TVariables,
      TContext,
      TCache
    > = {}
  ) => {
    const {client, options, mutation} = ref.current;
    const baseOptions = { ...options, mutation };
    if (!ref.current.result.loading && !baseOptions.ignoreResults) {
      setResult(ref.current.result = {
        loading: true,
        error: void 0,
        data: void 0,
        called: true,
        client,
      });
    }
```

Apparently, this `setResult` call is not protected by a check for unmounted component.

**Intended outcome:**
The mutate call should not result in an attempt to call `setResult` on an unmounted component

**Actual outcome:**
The mutate call results in error message "Can't perform a React state update on an unmounted component" in browser console

**How to reproduce the issue:**
As described.

**Versions**
  System:
    OS: macOS 12.4
  Binaries:
    Node: 14.19.3 - ~/.asdf/installs/nodejs/14.19.3/bin/node
    Yarn: 1.22.19 - ~/node_modules/.bin/yarn
    npm: 8.13.1 - ~/.asdf/plugins/nodejs/shims/npm
  npmPackages:
    @apollo/client: ^3.6.8 => 3.6.8

**Comment by alessbell** [comment]
Thanks for the report @tpham — I've opened PR https://github.com/apollographql/apollo-client/pull/9883 which addresses the issue.

@benasher44 would you mind opening a separate issue for the error you're seeing? Thanks all!

**Comment by benasher44** [comment]
Done! #9899

**Comment by alessbell** [comment]
I've just merged https://github.com/apollographql/apollo-client/pull/9883 which should go out in the next patch release. Thanks again!
