### ISSUE TITLE
useQuery does not get all data

### ISSUE THREAD

**Issue by YasineNifa** [apollographql/apollo-client#9860]
Hey,
I am using `"@apollo/client": "^3.6.8"` and I am trying to retrieve data from my dynamo database 
I have 583 entries in my database but I am getting only 243 entries.
I am wondering if there is a limitation of the number of result we get when we use `useQuery`. if not how can I solve this

Here is the code I am using
```
import { useQuery, gql } from "@apollo/client";
const ALL_BOOKS = gql`
  query books($id_author: String!) {
    books(id_artist: $id_author) {
      id_author
      title
      year   
    }
  }
`;
const { loading, data } = useQuery(ALL_BOOKS , { variables: { id_author: AUTHORNAME }, fetchPolicy: "no-cache" });
loading ? console.log("wait") : console.log("data : ", data.books.length)
```
I am expecting to get 583 but I am getting only 243.

**Comment by dylanwulf** [comment]
As far as I know there should not be any limit to how many results `useQuery` can give you

**Comment by jpvajda** [comment]
There shouldn't be a limit of any sorts, It's possible some of your data is being cached, and returned incorrectly. However I see you have the `fetchPolicy` set to `no-cache`.  So that probably isn't the issue.  It doesn't look like this is a specific relating to the Apollo Client.
