### ISSUE TITLE
useQuery doesn't seem to use the variables i'm sending it

### ISSUE THREAD

**Issue by tychovbh** [apollographql/apollo-client#9861]
**Version**
"@apollo/client": "^3.6.9",

I have a very simple query:

```js
import {useQuery, gql} from '@apollo/client'

const GET_PAGE = gql`
  query Page($slug: String!) {
    entry(slug: $slug) {
      id
    }
  }
`;

const { loading, error, data } = useQuery(GET_PAGE, {
    variables: { slug: "test" },
});
```

But it returns an error:

`Error: Variable "$slug" of type "String!" used in position expecting type "[String]"`

So i'm guessing the query doesn't receive any variables. What am I doing wrong?

**Comment by dylanwulf** [comment]
That error is coming from your server, not from apollo client. It's saying that your query is supposed to accept a string array but your variable is a single string.

**Comment by tychovbh** [comment]
Thanks you were right! Sorry i'm quit new to GraphQL, and I do find it strange that craftcms expected a [String].
Because this works:
```
query Event {
          entry(slug: "test") {
```

And now this works too:

```
query Event($slug: [String]) {
          entry(slug: $slug) {
```

Not sure what the difference is between String and  [String], but i will google that later ;)

Ticket closed!
