### ISSUE TITLE
yarn.lock listed in .gitignore 

### ISSUE THREAD

**Issue by cisnez** [apollographql/apollo-client#9864]
Per yarn documentation  (https://classic.yarnpkg.com/lang/en/docs/yarn-lock/) => "All yarn.lock files should be checked into source control (e.g. git or mercurial). This allows Yarn to install the same exact dependency tree across all machines, whether it be your coworker’s laptop or a CI server."

Why is yarn.lock listed in the .gitignore (https://github.com/apollographql/apollo-client/blob/main/.gitignore)?

**Comment by alessbell** [comment]
That's exactly right, @dylanwulf. Let me know if you have any more questions if you're interested in contributing in the future, @cisnez, as I'm going to close out this issue for now. Thanks!
