### ISSUE TITLE
useQuery returns incorrect data on variable change when using cache

### ISSUE THREAD

**Issue by gustavoem** [apollographql/apollo-client#9868]
When the variable of a query changes, and the result for the new variable value is cached (and used, according to the `fetchPolicy`), there is an iteration in which `data` from `useQuery` is incorrect. Instead of showing the cached value, or even `undefined`, the value of `data` is the previous result of the query, corresponding to the former variable value.

This issue is similar to issue #6300, and I adapted @vishwam sandbox so I can show this issue. [Link to the sandbox](https://codesandbox.io/s/objective-sutherland-mbmmgx?file=/src/App.js:415-420). 

**Intended outcome:**
Since I'm using `cache-first` and the result of my queries have been cached, when the variable change, I expect `data` to contain the cached value, or at least `undefined` while useQuery hasn't resolved the cache.

**Actual outcome:**
`data` contains the previous `data` value, with results corresponding with the former variable value.

**How to reproduce the issue:**
I found out that useQuery works as inteded from version 3.0.0 (and maybe lower, I haven't checked) up to version 3.5.0-beta.5. Versions 3.5.0-beta.6 and above have the unintended outcome.

**Versions**
@apollo/client 3.5.0-beta.6

**Comment by jpvajda** [comment]
@gustavoem Thanks for reporting this, we did a lot of bug fixes for useQuery since the 3.5.0 version, would you be willing to upgrade to our latest version 3.6.8 and see if that resolves the problem?

**Comment by ericbeijer** [comment]
@jpvajda, I can confirm this same issue on both versions 3.5.10 and 3.6.8. Thank you for your efforts.

**Comment by jpvajda** [comment]
@ericbeijer Thanks for confirming!

**Comment by gustavoem** [comment]
The [Link to the sandbox](https://codesandbox.io/s/objective-sutherland-mbmmgx?file=/src/App.js:415-420) seem to be working with 3.6.8

**Comment by ericbeijer** [comment]
@gustavoem, yes, the sandbox works as expected since 3.6.0-rc.0. I'll investigate why my setup doesn't work.
