### ISSUE TITLE
Apollo in Remix - does it still utilize caching when not using hooks?

### ISSUE THREAD

**Issue by yardenhochman** [apollographql/apollo-client#9885]
We're currently adopting Remix for our server side rendering needs, while our entire backend utilizes graphql and apollo. 
To my understanding, even in the case of server side rendering via remix "loader" functions, there's still a significant benefit utilizing apollo's caching behavior to specify api data requirements without worrying about repeating requests, and then letting apollo decide what needs to be fetched via its normalization and caching behavior.

From what I understand from relevant [discussions](https://github.com/remix-run/remix/discussions/3128) on Remix's github, getDataFromTree function should not be used in the context of Remix because it forgoes the benefits of Remix's concurrent fetching. 

Therefore it seems to me that the best way to utilize apollo in this context is to use its client instance directly inside loders and minimizing the JS sent to the user. 

```
//import instance of apollo client

export const loader: LoaderFunction = async () => {
  const data = await client.query({
    query: locationsQuery,
  });

  return data;
};
```
my impression is that this api is still cached, and in case this query will be repeated, it will utilize apollo's caching.

I wonder what other people found and if the caching in apollo does indeed work even when used without hooks or hocs?

**Comment by jpvajda** [comment]
Thank you for reporting this! You can try posting this in our [Apollo Community](https://community.apollographql.com/) for guidance from other Apollo users, as other's may have input into your question, I'll also leave this open for now to see if anyone has thoughts.

**Comment by alessbell** [comment]
Hi @yardenhochman 👋 If you'd like to share more about experiences working with Apollo Client + Remix, I'd be interested to hear about them! Please feel free to share best practices and ask questions in our [Apollo Community](https://community.apollographql.com/) (or anywhere else, and feel free to share the link in a comment 😃).

Since this isn't a bug report, I'm going to close this issue, but thanks for being a part of the Apollo Community!
