### ISSUE TITLE
MockedProvider causes react act warning

### ISSUE THREAD

**Issue by redreceipt** [apollographql/apollo-client#9887]
**Intended outcome:**

Test a component using `MockedProvider` with no warnings

**Actual outcome:**

Produces `act` warning

**How to reproduce the issue:**

I used the example from your docs. Go here and run `yarn test` to see the problem: https://replit.com/@redreceipt/MelodicKosherSubversion

<img width="728" alt="Screen Shot 2022-06-30 at 4 56 59 PM" src="https://user-images.githubusercontent.com/2659478/176777021-609580f7-00eb-40b4-8f10-7efa683d42fa.png">

**Versions**

```
  System:
    OS: Linux 5.15 Ubuntu 20.04.2 LTS (Focal Fossa)
  Binaries:
    Node: 16.13.2 - /nix/store/ra8r42571xvv1m85wanh1ll9mxmp0mwl-nodejs-16.13.2/bin/node
    Yarn: 1.22.17 - /nix/store/ms6qmg7zicwy03rq9radb922ylqywxqq-yarn-1.22.17/bin/yarn
    npm: 8.1.2 - /nix/store/ra8r42571xvv1m85wanh1ll9mxmp0mwl-nodejs-16.13.2/bin/npm
  npmPackages:
    @apollo/client: ^3.6.9 => 3.6.9 
```

**Comment by alessbell** [comment]
Thanks for the report [redreceipt](https://github.com/redreceipt)! This page of the docs was ready for an update — I batched a bunch of changes in https://github.com/apollographql/apollo-client/pull/9888, including updating the [testing codesandbox](https://codesandbox.io/s/react-apollo-testing-rwwrx6) linked at the bottom of the page, and you should no longer see any act warnings.

Closing this issue, but please let me know if you see anything else that can be improved :)
