### ISSUE TITLE
Access to headers in GraphQLWsLink

### ISSUE THREAD

**Issue by sfounder** [apollographql/apollo-client#9893]
Hi everyone👋 How can I get access to headers in `GraphQLWsLink` that I set by `setContext`? I I pass token to the `authorization` header by `setContext`:

```
const authLink = setContext((_, { headers }) => {
  const token = getPlayerSessionToken();
  return {
    headers: {
      ...headers,
      authorization: token ? `Bearer ${token}` : ''
    }
  };
});
```

Then add it to the link chain: `[authLink, mockServiceLink, errorLink, wsLink]`.

`wsLink` is on the last step and should have access to the headers but I din't any info in docs how to get it in `GraphQLWsLink`:

```
const wsLink = new GraphQLWsLink(
    createClient({
      url: `${process.env.NEXT_PUBLIC_NOTIFICATIONS_SERVICE_URL}/graphql`,
      connectionParams: {
        authorization: token ? `Bearer ${token}` : ''
      }
    })
  );
```

**Comment by engeldlgado** [comment]
You can use split from @apollo/client maybe this work for you
`
import {
  ApolloClient, ApolloProvider, HttpLink, InMemoryCache, split
} from '@apollo/client'
import { setContext } from '@apollo/client/link/context'

import { GraphQLWsLink } from "@apollo/client/link/subscriptions";
import { getMainDefinition } from '@apollo/client/utilities';

const authLink = setContext((_, { headers }) => {
  const token = localStorage.getItem('user-token')
  return {
    headers: {
      ...headers,
      authorization: token ? `Bearer ${token}` : null
    }
  }
}
)

const httpLink = new HttpLink({
  uri: 'http://localhost:4000'
})
const wsLink = new GraphQLWsLink({
  uri: 'ws://localhost:4000',
  options: {
    reconnect: true,
  }
}
)
const link = split(
  ({ query }) => {
    const definition = getMainDefinition(query)
    return (
      definition.kind === 'OperationDefinition' &&
      definition.operation === 'subscription'
    );
  },
  wsLink,
  authLink.concat(httpLink)
)

const client = new ApolloClient({
  link: link,
  cache: new InMemoryCache()
})

`
