### ISSUE TITLE
Apollo client doesn't display the data of a graphql interface if the interface is embeded inside a fragment

### ISSUE THREAD

**Issue by TheRogue76** [apollographql/apollo-client#9904]
**Intended outcome:**
For me to be able to call objects that implement a specific interface within a fragment. The data coming from the server should be shown in full.

**Actual outcome:**
The query works fine on the graphql side and fetches the data (I checked via flipper to see that the data is indeed coming in correctly) but then when i log the results of the `useQuery`, it only shows the shared items in the interface. Moving the fragment stuff into the query fixes the issue all together

**How to reproduce the issue:**

```gql
interface RoutineCard {
  id: ID!
}

type RecipeRoutineCard implements RoutineCard {
  id: ID!
  recipe: Recipe
}

type ActionRoutineCard implements RoutineCard {
  id: ID!
  resourceId: String!
}

fragment DailyRoutineCardFragment on RoutineCard {
    __typename
    id
    ... on RecipeRoutineCard {
        recipe {
            ...RecipeFragment
        }
    }
    ... on ActionRoutineCard {
        resourceId
    }
}

query FetchCard {
    getRoutineCards {
        ...DailyRoutineCardFragment
    }
}
```

**Versions**
System:
    OS: macOS 12.4
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.18 - ~/Desktop/rnapp/node_modules/.bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Safari: 15.5
  npmPackages:
    @apollo/client: ^3.6.5 => 3.6.6 
    @apollo/rover: ^0.6.0 => 0.6.0 
    apollo: ^2.34.0 => 2.34.0

**Comment by dylanwulf** [comment]
Have you configured the [possibleTypes](https://www.apollographql.com/docs/react/data/fragments#defining-possibletypes-manually) cache config option?

**Comment by TheRogue76** [comment]
> Have you configured the [possibleTypes](https://www.apollographql.com/docs/react/data/fragments#defining-possibletypes-manually) cache config option?

Not at this point. I will try it out tomorrow to see if it fixes the problem

**Comment by TheRogue76** [comment]
I can validate that adding possibleTypes to the cache config fixed the issue. Thank you @dylanwulf. Maybe we should mention this in the doc as well? https://www.apollographql.com/docs/apollo-server/schema/unions-interfaces/

**Comment by nataliaschlebinger** [comment]
@bignimbus @dylanwulf Do you guys think this issue was fixed by [5c1b6597dd](https://github.com/nataliaschlebinger/apollo-server/commit/5c1b6597dd#diff-cb237d5079746446480c649a417cf68fb33409550e1489a0444663a4d009c8d2) ?

**Comment by phryneas** [comment]
@nataliaschlebinger It is very unlikely that a server update changed anything about this - if you use fragments on interfaces, you **have** to use the `possibleTypes` option to Apollo Client.

**Comment by nataliaschlebinger** [comment]
@phryneas Of course, but this is already clearly mentioned in the React client's doc, and TheRogue76's suggestion is about the server doc. I did make [a pull request](https://github.com/apollographql/apollo-server/pull/7642) over on the server, maybe that would close this issue.

**Comment by jonnyleeharris** [comment]
I encountered this issue when changing the type of a query from a type to an interface. From the server point of view this felt backward compatible, however, I have clients using fragments on what used to be types and are now interfaces.

Removing the fragments or using possibleTypes solves this, but unfortunately this means the server-side change is not as backwards compatible as I would have liked.

**Comment by trevor-scheer** [comment]
We just landed https://github.com/apollographql/apollo-server/pull/7642 thanks to @nataliaschlebinger in case that was sufficient for closing this issue.

**Comment by alessbell** [comment]
Thanks @trevor-scheer & all - I see nothing outstanding mentioned above so I'll go ahead and close this out.
