### ISSUE TITLE
[Field policy read() fn] Is there a way to read a field value without knowing its arguments?

### ISSUE THREAD

**Issue by fabis94** [apollographql/apollo-client#9926]
Imagine a query like this:

```graphql
query {
  webhooks {
    items {
      id
      streamId
      url
      description
      triggers
      enabled
      statusIcon @client
      history(limit: 50) {
        items {
          status
          statusInfo
          lastUpdate
        }
      }
    }
  }
}
```

Each webhook item has a statusIcon client-only field that I wish to implement with a field policy. The status icon value depends on the webhook item's `history` collection.

The problem is that the `read` function has no API for retrieving the value of `history` without knowing the arguments used (the `limit`, which is just a pagination value). Not just that, but there's no way to figure out the arguments that were used for `history`. There's also no way to just get all fields & values of the parent object directly, which would help.

So how am I supposed to read `history({limit: 50})` with `readField` inside the `read` function, without hardcoding the argument to `{limit: 50}` which will break whenever I change the query or the limit argument?

**Comment by bignimbus** [comment]
Hi @fabis94 👋🏻  thanks for your patience.  Our [Discord server](https://discord.gg/graphos) is a great place for Q&A like this.  Can you share some more details about how you're using a `read` function here?  I'm happy to lend an extra set of eyes but need some more details to make a good recommendation 🙏🏻
