### ISSUE TITLE
👋 `Feedback Wanted` Apollo Developer Research Study  🎉

### ISSUE THREAD

**Issue by itsshili** [apollographql/apollo-client#9930]
Hi there!

I'm a product researcher at Apollo and we're looking for developers who are evaluating or setting up Apollo-client to participate in a 60 minute remote research interview. We want to understand how developers are using apollo-client and gather feedback. As a token of our appreciation, we’ll email you a $100 gift card. If you’re interested, please [take this quick survey](https://www.surveymonkey.com/r/3QJ39TL) and we’ll reach out if you’re a fit for this upcoming study.

Thank you in advance for your help! 

> The survey closes on 7/29/2022

Best,
Shili

**Comment by jpvajda** [comment]
This study is closed now.
