### ISSUE TITLE
How does Apollo paginated "read" and "merge" work?

### ISSUE THREAD

**Issue by mabramishvili** [apollographql/apollo-client#9931]
I was reading through the docs to learn pagination approaches for Apollo. This is the simple example where they explain the paginated read function: https://www.apollographql.com/docs/react/pagination/core-api#paginated-read-functions

Here is the relevant code snippet:

```js
const cache = new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        feed: {
          read(existing, { args: { offset, limit }}) {
            // A read function should always return undefined if existing is
            // undefined. Returning undefined signals that the field is
            // missing from the cache, which instructs Apollo Client to
            // fetch its value from your GraphQL server.
            return existing && existing.slice(offset, offset + limit);
          },

          // The keyArgs list and merge function are the same as above.
          keyArgs: [],
          merge(existing, incoming, { args: { offset = 0 }}) {
            const merged = existing ? existing.slice(0) : [];
            for (let i = 0; i < incoming.length; ++i) {
              merged[offset + i] = incoming[i];
            }
            return merged;
          },
        },
      },
    },
  },

});
```

I have one major question around this snippet and more snippets from the docs that have the same "flaw" in my eyes, but I feel like I'm missing some piece.

Suppose I run a first query with `offset=0` and `limit=10`. The server will return 10 results based on this query and store it inside cache after accessing merge function. Afterwards, I run the query with `offset=5` and `limit=10`. Based on the approach described in docs and the above code snippet, what I'm understanding is that I will get only the items from 5 through 10 instead of items from 5 to 15. Because Apollo will see that existing variable is present in `read` (with `existing` holding initial 10 items) and it will slice the available 5 items for me.

My question is - what am I missing? How will Apollo know to fetch new data from the server? How will new data arrive into cache after initial query? Keep in mind `keyArgs` is set to [] so the results will always be merged into a single item in the cache.

**Comment by bignimbus** [comment]
Hi @mabramishvili 👋🏻  thanks for your patience!  To respond to the specific scenario you stipulated, you would get elements 5-15 and not 5-10 as you suggested (provided that your server interprets `offset` and `limit` as they are conventionally used).  Our [Discord server](https://discord.gg/graphos) is a great place for Q&A like this, hope to see you there!
