### ISSUE TITLE
Codesandbox sample app review

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-client#9943]
We're using codesandbox hosted sample applications in several places in our docs. We need to review all of these to:
1. Make sure they're all still working properly; we've noticed some strangeness with `graphql@16` that is causing them to break.
2. Make sure they're all moved over the `apollographql` codesandbox org.
3. Make sure the codesandbox links in the docs are all still pointing to valid sample apps.
4. update issue templates to include new link to template
5. if possible, setup github redirect to point to new template location
6. ensure we updates all references in docs to this template.

**Comment by jpvajda** [comment]
I'm going to link to this issue which had a problem on Code sandbox

**Comment by alessbell** [comment]
Also linking to our docs example repo which @StephenBarlow mentioned can be used to back individual sandboxes so we can update them via PRs https://github.com/apollographql/docs-examples 🎉

**Comment by MrDoomBringer** [comment]
Here's another issue related to this https://github.com/apollographql/apollo-client/issues/9659 (shoutout alessia!)

@alessbell fix in this thread worked. Some changes we can make to the [error-template repo](https://github.com/apollographql/react-apollo-error-template):

1. The `graphql@16` module seems to not transpile correctly on codesandboxes, see [this ](https://codesandbox.io/s/graphql-codesandbox-d9ddu9?file=/src/index.js)for example. I think we can just revert graphql back down to 15.x until this is fixed

2. Codesandbox seems to no longer want `*.jsx` files as entrypoints, though I can't find this actually written anywhere. Very strange. Given that the [fullstack tutorial](https://github.com/apollographql/fullstack-tutorial) uses Typescript, I think we can kill two birds with one stone and convert the `index.jsx` file to an `index.tsx` file, both letting it actually render, and putting it in a language which most apollo-client users are probably using anyways.

CC @hwillson

**Comment by jpvajda** [comment]
@MrDoomBringer  just curious on this finding: 

> The graphql@16 module seems to not transpile correctly on codesandboxes, see [this ](https://codesandbox.io/s/graphql-codesandbox-d9ddu9?file=/src/index.js)for example. I think we can just revert graphql back down to 15.x until this is fixed

Is this something we should make the fine people at Codesandbox aware of? Do we feel it's an issue on their end?

**Comment by MrDoomBringer** [comment]
@jpvajda great question! Given that this only affects versions after 16, I suspect it's an issue on the `graphql` module's end. I went ahead and opened an issue [here](https://github.com/graphql/graphql-js/issues/3685). Let me know if you think we should also open an issue on the codesandbox side of things.

**Comment by MrDoomBringer** [comment]
PR for this open [here](https://github.com/apollographql/react-apollo-error-template/pull/119). I went with the slightly more elegant solution of just manually setting `index.jsx` as the entrypoint for the project. 

There was talk of create-react-app not supporting `*.jsx` as a default entrypoint [here](https://github.com/facebook/create-react-app/issues/3052) many moons ago, and I suspect they may have made good on that claim.

**Comment by alessbell** [comment]
> There was talk of create-react-app not supporting *.jsx as a default entrypoint https://github.com/facebook/create-react-app/issues/3052 many moons ago, and I suspect they may have made good on that claim.

Does that mean we need to use this workaround? https://github.com/facebook/create-react-app/issues/3052#issuecomment-330868560

**Comment by MrDoomBringer** [comment]
> Does that mean we need to use this workaround

Nope! We can just set `"main":"index.jsx"` in the `package.json`, which feels more straightforward.

**Comment by MrDoomBringer** [comment]
Moving the error-template repository over to our docs-examples repo with this PR: https://github.com/apollographql/docs-examples/pull/48

**Comment by hwillson** [comment]
@MrDoomBringer I believe we can close this out now that all code sandboxes have been updated. Thanks for all of your work on this!
