### ISSUE TITLE
API docs are broken

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-client#9947]
I'm not sure when this started happening, but our API docs are broken. Looking at our [`watchQuery`](https://www.apollographql.com/docs/react/api/core/ApolloClient#ApolloClient.watchQuery) section for example:

![Image 2022-07-26 at 8 54 12 PM](https://user-images.githubusercontent.com/137740/181137224-e6a62e9a-bfa1-4c2f-b712-d3ed2de69249.jpg)

Our function / method code doc headers are missing, which means there is a ton of helpful content missing in our docs:

https://github.com/apollographql/apollo-client/blob/main/src/core/ApolloClient.ts#L267-L285

![Image 2022-07-26 at 8 55 10 PM](https://user-images.githubusercontent.com/137740/181137311-a61a9f48-d703-4bf1-825c-662558493585.jpg)

**Comment by alessbell** [comment]
It appears they broke on or around June 24, but looking at https://github.com/apollographql/docs/commit/432f1d83a8cf41809dba5924ffd3bb1e4d8a0898 it doesn't seem clear that any of the changes could have affected this page... would @trevorblades or @StephenBarlow mind helping me take a closer look?

**Comment by hwillson** [comment]
Woohoo - thanks for the research @alessbell and fix @trevorblades! 🎉
