### ISSUE TITLE
wrong type in package.json

### ISSUE THREAD

**Issue by vankop** [apollographql/apollo-client#9952]
**Intended outcome:**

webpack should correctly build `@apollo/client`

**Actual outcome:**

`require("react-dom/server").renderToStaticMarkup` still preserved in output, see https://github.com/webpack/webpack/issues/16089

**How to reproduce the issue:**

https://github.com/webpack/webpack/issues/16089

**Versions**
3.6.9

**Comment by jpvajda** [comment]
Thanks for making us aware of this @vankop!

@MrDoomBringer 👋 I moved this to our board and put it into triage, as it looks like you might be working on a solution here.

**Comment by jorupp** [comment]
For others hitting this issue, we were able to work around it for the moment (though it may have other side effects we haven't observed yet) with https://github.com/webpack/webpack/issues/16089#issuecomment-1199004714, though the approach discussed here (not doing the conditional `require()`) sounds better.
