### ISSUE TITLE
nested fragment data returning null from cache

### ISSUE THREAD

**Issue by AleCatSS** [apollographql/apollo-client#9965]
Hello,

I am experiencing this issue in React Native using Apollo Client: I have a query containing a fragment and in it a nested fragment; when the query runs the first time (empty cache) the result is returned correctly and I can see data inside the fragment and the nested fragment; on the following rendering, when the result returns from the cache (default fetchPolicy), data is correctly returned except the nested fragment which contains "null".
I don’t manually manipulate the cache in any way on this query and we have no inMemoryCache configuration for it or its fields.

The nested fragment does NOT have an id but I tried setting a keyField on another field and nothing changed.
Removing the cache (fetchPolicy=no-cache) solves the problem but we want to use it.

Do you know what can cause the nested fragment data to be null in this situation or similar?

Here is a query example that resemble our query:

```
query MyData($myParam: String!) {
  getMyData(myParam: $myParam) {
    categories {
      catOne {
        ...MyFragmentOne
      }
      catTwo {
        ...MyFragmentOne
      }
      catThree {
        ...MyFragmentOne
      }
    }
    brands {
      brandOne {
        ...Brand
      }
      BrandTwo {
        ...Brand
      }
      BrandThree {
        ...Brand
      }
    }
  }
}
```

```
fragment Brand on Brand {
  id
  name
  keywords {
    ...Keywords
  }
}

```
```
fragment Keywords on Keywords {
  lang1
  lang2
}`

```

Keywords is the data fragment returning null from the cache,

**Versions**
I am are experiencing this in React Native using version '3.3.19', I also tested using '3.4' and the latest '3.6.9' with the same result.

**Comment by dylanwulf** [comment]
Shot in the dark here, but have you set up the [possibleTypes configuration for your schema's unions and interfaces](https://www.apollographql.com/docs/react/data/fragments/#using-fragments-with-unions-and-interfaces)?

**Comment by AleCatSS** [comment]
> Shot in the dark here, but have you set up the [possibleTypes configuration for your schema's unions and interfaces](https://www.apollographql.com/docs/react/data/fragments/#using-fragments-with-unions-and-interfaces)?

nope, no possibleTypes defined so far in this project.
thanks

**Comment by dylanwulf** [comment]
> > Shot in the dark here, but have you set up the [possibleTypes configuration for your schema's unions and interfaces](https://www.apollographql.com/docs/react/data/fragments/#using-fragments-with-unions-and-interfaces)?
> 
> nope, no possibleTypes defined so far in this project. thanks

Ah ok. If any of those fragments use a type that implements an interface, or is part of a union, then adding `possibleTypes` might help. If you're not using any unions or interfaces then I'm not sure what's wrong.

**Comment by mhammerc** [comment]
Hello!

I had the same problem and `possibleTypes` fixed it.

I spent hours not understanding what was happening as Apollo Client doesn't emit any warning or error and I was successfully using `Union` previously without needing to add possibleTypes.

I was thinking my custom `FieldResolver` for pargination was wrong but I couldn't find anything wrong and there wasn't.

Maybe we should consider emitting warnings to prevent this? Maybe each time an union is received by Apollo Client but not present in possibleTypes?

**Comment by mrclay** [comment]
I also wasted hours before figuring out the missing possibleTypes config.

**Comment by mrclay** [comment]
Docs: “[Setting possibleTypes] enables you to look up cached data by interface or by union.” To me that sounds like a nice-to-have but would not imply the client is just going to hide server-returned data from you. If it’s critical for operation, possibleTypes should be required.

**Comment by jerelmiller** [comment]
Hey all 👋 

Since `possibleTypes` resolves the issue as per previous comments, I'm going to go ahead and close this issue. If you feel strongly the behavior should be different, I encourage you to open a new issue where we can have a focused discussion on proposed behavior. Thanks and have a great day!
