### ISSUE TITLE
POST https://xyz.com/graphql 405 (Not Allowed)                                                                  createHttpLink.ts:154          

### ISSUE THREAD

**Issue by deepakkashyap3013** [apollographql/apollo-client#9979]
Since our website is not using any backend server it only uses The Graph's subgraph API endpoint and we are intending to call the graph's API which is working fine but there is an extra overhead call to the ```domain/graphql``` which we don't call explicitly it is being called automatically when the app renders.

The below are the imports:
```
import {
  ApolloLink,
  ApolloClient,
  createHttpLink,
  InMemoryCache,
  ApolloProvider,
} from '@apollo/client';

```
here we are creating the instance of the client 
```
  const client = new ApolloClient({
    cache: new InMemoryCache({
      addTypename: false,
    }),
    link: ApolloLink.split(
      (operation) => operation.getContext().clientName === 'subgraph-network',
      createHttpLink({ uri: Constants.QUERY_REQUEST_INDEXNODE.URL }),
      createHttpLink({ uri: endpoint }),
    ),
  });
```

The below code is the App
```
  return (
    <>
      <ApolloProvider client={client}>
        <div theme-selector={theme} className="App">
          <Switch>
            <Route
              ....Route 1
            ></Route>
            <Route
              ...Route 2
            ></Route>
            <Route path="*">
              <Redirect to="/" />
            </Route>
          </Switch>
        </div>
      </ApolloProvider>
    </>
  );
```

Network Errors:

![Screenshot from 2022-08-03 18-28-46](https://user-images.githubusercontent.com/68886718/182613858-bf516e07-4894-42af-bd10-9bd5ddb31290.png)

:point_right: P.S we don't want this call to happen how can I fix it !!!!

**Comment by jerelmiller** [comment]
Hey @deepakkashyap3013 👋 

Its a bit hard to determine what might be happening here as there are a number of reasons a query might be initiated. I'm afraid I don't have enough information using the code snippets above to be able to determine what might be happening. Would you be able to provide a minimal reproduction of the issue?

Alternatively, this question seems like it might be best posted under our [community forms](https://community.apollographql.com/) or [discord server](https://discord.gg/graphos) where more of the community might be able to help out. It's not clear to me if this is a bug. Thanks!
