### ISSUE TITLE
Queries cancelled in strict mode with nextFetchPolicy: "cache-first"

### ISSUE THREAD

**Issue by markedwards** [apollographql/apollo-client#9989]
**Intended outcome:**

1. Configure a component to use `useQuery` with `fetchPolicy: "network-only"` or `fetchPolicy: "cache-and-network"`, and `nextFetchPolicy: "cache-first"`.
2. Mount the component, query is made.
3. Unmount the component.
4. Mount the component a second time, query should be made.

**Actual outcome:**

In step 4, the query happens, but is immediately cancelled.  So, a query with a given set of variables will only be made once, and can never be made again.  This only happens in React strict mode, the behavior is as-expected with React strict mode off.

**How to reproduce the issue:**

https://codesandbox.io/s/distracted-babbage-ry92hc?file=/src/index.jsx

Toggle mount/unmount with strict mode on, observe cancelled queries.  With strict mode off, queries are not cancelled.

**Versions**

  System:
    OS: Linux 4.14 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
  Binaries:
    Node: 16.15.0 - /usr/bin/node
    Yarn: 1.22.18 - /usr/bin/yarn
    npm: 8.5.5 - /usr/bin/npm
  npmPackages:
    @apollo/client: ^3.6.9 => 3.6.9

**Comment by adrienharnay** [comment]
Also facing this, which makes StrictMode impossible to use 😞 I see there is a reproduction, has work on this been planned? Thanks in advance and have a great day!

**Comment by adrienharnay** [comment]
Hello @hwillson, could you please take a look at this and point us in the right direction? Thanks a lot 🙏

**Comment by SimenB** [comment]
@benjamn @jerelmiller is this something you could take a look at? The reproduction is hort and sweet (and it still reproduces on 3.7.10)

**Comment by SimenB** [comment]
Hmm, that said, it does _not_ reproduce using the alpha (currently `3.8.0-alpha.11`)

**Comment by phryneas** [comment]
Yeah, I would presume that this was fixed with #10629. I wanted to create you a PR build to test it, but it seems that the GitHub action is broken right now.

Either way, we will probably release a new version within the next few days, and this should be included there.

**Comment by phryneas** [comment]
Ah, got it to build with a tip from @alessbell. 
It seems to fix the reproduction - can you try it in your codebase please?

`npm i @apollo/client@0.0.0-pr-10629-20230329120619`

**Comment by SimenB** [comment]
@phryneas yeah, can confirm installing that version specifically also fixes our tests 👍
